### ISSUE TITLE
add_html_dependency – "resources" not being included in HTML content

### ISSUE THREAD

**Issue by orbsmiv** [quarto-dev/quarto-cli#10009]
### Bug description

I am not able to include "arbitrary content" in the HTML file of a RevealJS presentation by using e.g. `quarto.doc.add_html_dependency(resources = 'my_file.cast')`. The `scripts` and `stylesheets` inclusions work without issue.

#### Context
I am trying to develop a Quarto extension to embed _asciinema player_ (https://github.com/asciinema/asciinema-player) in a RevealJS presentation.  
I am planning to use one of the following options for providing the required `*.cast` file: <https://docs.asciinema.org/manual/player/loading/>, which I am presuming will work with the strategy of using `quarto.doc.add_html_dependency(dep)`, as documented here: <https://quarto.org/docs/extensions/lua-api.html#html-dependencies>

### Steps to reproduce

Within the extension Lua file:

```lua
quarto.doc.add_html_dependency {
  name = 'asciinema',
  version = 'v1.0.0',
  -- scripts = { './assets/asciinema-player-3.7.1.min.js' },
  -- stylesheets = { './assets/asciinema-player-3.7.1.css' },
  resources = {'/work/shared/_extensions/asciinema/assets/example.cast'},
}
```
(I've experimented with the resources path as both absolute and relative.)

Build command:
```sh
docker run -it --rm -v $(pwd):/work -p 8083:8083 quarto-dev:1.4.555 quarto render ./my_presentation/my_presentation.qmd --to revealjs --no-cache
```

Also checked using the latest pre-release: `1.5.45`.

### Expected behavior

I would expect the resultant HTML file to include the content of the `example.cast` file, alongside the CSS and JS content.

### Actual behavior

The CSS and JS content is available but anything included via `resources = ` is not available. As an experiment, including the same content but via `scripts = ` does include the file as base64 encoded data, although inside a `<script>` tag, as would be expected.  
Creating the HTML both with and without the `resources = ` inclusion results in an identical output file (verified with `diff` and a sha256 checksum.)

### Your environment

- Quarto running inside Docker container (using `debian:bookworm-20240211-slim` base image) on macOS Sonoma 14.5 system.

#### Dockerfile

```docker
FROM debian:bookworm-20240211-slim

# See https://github.com/quarto-dev/quarto-cli/releases
# Example build command:
# VER=1.4.551 bash -c 'docker build --build-arg QUARTO_VER=${VER} -t quarto-dev:${VER} .'
ARG QUARTO_VER="set_via_command"

ENV TZ=Europe/London

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    fontconfig \
    librsvg2-bin \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN wget --quiet "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VER}/quarto-${QUARTO_VER}-linux-arm64.deb" && \
    dpkg -i "quarto-${QUARTO_VER}-linux-arm64.deb" && \
    rm "quarto-${QUARTO_VER}-linux-arm64.deb" && \
    # quarto install tinytex && \
    mkdir -p /work

WORKDIR /work

CMD ["quarto", "check"]

```

### Quarto check output

```sh
$ docker run -it --rm -v $(pwd):/work -p 8083:8083 quarto-dev:1.4.555 quarto check                                                 
Quarto 1.4.555
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.555
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cderv** [comment]
Do you have the extension your are working on in a public repo so we can try reproduce and investigate ? 

> WORKDIR /work

We don't have access to this - this is where the content is on your computer that you map with `-v $(pwd):/work`

> Quarto 1.4.555

You could try latest 1.5 release candidate to see if this is fixed; 

Thanks

**Comment by orbsmiv** [comment]
Thanks @cderv. I tried with 1.5.45 but the issue still exists.

I'll get a minimal reprod example together and update the ticket again once that's done.

**Comment by cderv** [comment]
@orbsmiv we closed it has it's been 3 weeks already and we're starting on 1.6 prerelease now as 1.5 has been released. 

If you still have issue and manage to provide a reproducible example, please post it and we'll reopen. Thanks !
