### ISSUE TITLE
ojs code missing in code cells

### ISSUE THREAD

**Issue by Carluna** [quarto-dev/quarto-cli#10007]
### What would you like to do?

Give feedback or suggest an improvement

### Description

It would be nice when the code for the [input examples for dashboards](https://quarto.org/docs/dashboards/inputs.html) would be added. 
If I have seen it correctly, the code of the examples is only from the [palmer penguins ojs dashboard](https://github.com/jjallaire/ojs-penguins-dashboard/blob/main/penguins.qmd)?
Thanks a lot for the awesome quarto documentation!

**Comment by mcanouil** [comment]
Thanks for the feedback!

Could you clarify where and what you think is missing in the input page? Which section?

The example you share is a complete dashboard which is not exactly the same thing as code example.
For instance, we have a gallery of dashboards: https://quarto.org/docs/gallery/#dashboards

**Comment by Carluna** [comment]
Sorry, maybe I just didn't understand the purpose of the example code.  I wanted to see how the actual side- and toolbars are created/filled. But that's probably not the purpose of the section **input** and requires further an understanding of shiny or ojs.

**Comment by mcanouil** [comment]
The section is mostly about structure, maybe the Python code cell is a bit miss-leading.

```
## {.toolbar}

Whatever content to be placed in the toolbar as plain text or computed

## {.sidebar}

Whatever content to be in the sidebar as plain text or computed
```
