### ISSUE TITLE
Span asides are not working in HTML output

### ISSUE THREAD

**Issue by tylermorganwall** [quarto-dev/quarto-cli#10018]
### Bug description

Span asides are not working for me in HTML output. It doesn't work regardless of the width of the browser window. They do work with PDF output. I am rendering via the CLI `quarto render`. This is with the current release candidate v1.5.45. I have repeatedly reinstalled Quarto in case there were any installation issues.

### Steps to reproduce

Here is an image of the HTML output:
<img width="736" alt="Screenshot 2024-06-13 at 10 46 46 PM" src="https://github.com/quarto-dev/quarto-cli/assets/297609/4aa725ae-f2b1-4407-bd85-34741295893b">

Here is the qmd file.

```r
---
title: "Quarto Playground"
format: html
---

This is a playground for Quarto.

I'm confused... [why isn't this aside working?]{.aside}

This is very confusing.

::: aside
This aside works!
:::

[This aside doesn't.]{.aside}

```

Here is the HTML:

```html
<p>This is a playground for Quarto.</p>
<p>I’m confused… <span class="margin-aside">why isn’t this aside working?</span></p>
<p>This is very confusing.</p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>This aside works!</p>
</div></div><p><span class="margin-aside">This aside doesn’t.</span></p>
```

### Expected behavior

Aside should appear on the side

### Actual behavior

Aside does not appear on the side

### Your environment

Rendered via CLI
MacOS Ventura + Sonoma 14.5 (confirmed on both)

### Quarto check output

Output of `quarto check`:

```bash
Quarto 1.5.45
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.45
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.07
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/tyler/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1 (Conda)
      Path: /Users/tyler/miniconda3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

      There is an unactivated Python environment in vpype_venv. Did you forget to activate it?

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.47
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by owiecc** [comment]
I tested and it works correctly on v1.4.554 but is broken on v1.4.555

**Comment by mcanouil** [comment]
It comes from 6c5204b914d5e4d7f6b665b69c67828b7b88144e

**Comment by cderv** [comment]
For context, the change cames from 
- https://github.com/quarto-dev/quarto-cli/pull/9596 to fix https://github.com/quarto-dev/quarto-cli/issues/9593
