### ISSUE TITLE
404.qmd does not load resources correctly on preview when site-url is set with a site path

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#10013]
Create a book project
````powershell
quarto create project book test-404-book
````

Add a `404.qmd`

````markdown
---
title: Lost ? 
---

Content
````

And set a `site-url`  in `_quarto.yml`

Example 
````yaml
book:
  title: "Test-404-book"
  author: "Norah Jones"
  date: "14/06/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  site-url: "https://mysite.github.io/quarto-test/"
````

THen

````powershell
quarto render --to html
````

This will correctly create a `404.html` in books, but looking at the head content we get 
````
<script src="/quarto-test/site_libs/quarto-nav/quarto-nav.js"></script>
<script src="/quarto-test/site_libs/quarto-nav/headroom.min.js"></script>
<script src="/quarto-test/site_libs/clipboard/clipboard.min.js"></script>
<script src="/quarto-test/site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="/quarto-test/site_libs/quarto-search/fuse.min.js"></script>
<script src="/quarto-test/site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="/quarto-test/">
<script src="/quarto-test/site_libs/quarto-html/quarto.js"></script>
<script src="/quarto-test/site_libs/quarto-html/popper.min.js"></script>
<script src="/quarto-test/site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="/quarto-test/site_libs/quarto-html/anchor.min.js"></script>
<link href="/quarto-test/site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="/quarto-test/site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="/quarto-test/site_libs/bootstrap/bootstrap.min.js"></script>
<link href="/quarto-test/site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="/quarto-test/site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
````

So all the resources are not found when previewing with `quarto preview`. Found while looking at #9988 

In other file we have correct path at least for previewing
````
<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
````

This is probably due to the fact that `site-url` is supposed to be base url only, but we don't seem to enforce it and other files are fine

🤔 so probably worth investigate this

**Comment by cderv** [comment]
It seems there is specific handling of custom 404 where we force the root.
https://github.com/quarto-dev/quarto-cli/blob/9b77dcabfefe0d5a9db8dba983da697d797f16f5/src/project/types/website/website-resources.ts#L32-L51
https://github.com/quarto-dev/quarto-cli/blob/9b77dcabfefe0d5a9db8dba983da697d797f16f5/src/project/types/website/website-resources.ts#L103-L114

So it seems expected that resource path is absolute in the 404.html and we do handle it 
https://github.com/quarto-dev/quarto-cli/blob/9b77dcabfefe0d5a9db8dba983da697d797f16f5/src/project/serve/serve.ts#L683-L715

So I understand this is something that `quarto preview` handles. 

All seem good. 😓 So closing.

**Comment by cderv** [comment]
> So I understand this is something that quarto preview handles.

To be thorough

- `https://localhost/:<port>/dummy.html` show the 404 page correctly with resources loaded correctly
- `https://localhost/:<port>/404.html` does not show the 404 page correctly. 

Probably we don't handle the request to the 404 page directly. Only redirecting not found error to the 404 pages and fixing the site-url in paths

**Comment by mcanouil** [comment]
A [Future](https://github.com/quarto-dev/quarto-cli/milestone/2) https://github.com/quarto-dev/quarto-cli/labels/enhancement I would say.
