### ISSUE TITLE
`/opt/quarto/share/filters/quarto-pre/quarto-pre.lua:3417: attempt to index a nil value (local 'f')`

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-cli#1001]
We're seeing the following error during CI runs on Ubuntu 20.04

https://github.com/mlr-org/mlr3book/runs/6628847525?check_suite_focus=true

```
Error running filter /opt/quarto/share/filters/quarto-pre/quarto-pre.lua:
/opt/quarto/share/filters/quarto-pre/quarto-pre.lua:3417: attempt to index a nil value (local 'f')
stack traceback:
	/opt/quarto/share/filters/quarto-pre/quarto-pre.lua:3381: in function </opt/quarto/share/filters/quarto-pre/quarto-pre.lua:3374>
make: *** [Makefile:32: pdf] Error 1
Error: Process completed with exit code 2.
```

Rendering locally using MacTex 2022 works fine.

`quarto` 0.9.466 in both setups. Unfortunately the CI run does not really return helpful error contents.
Any idea what we could try?

The source can be found [here](https://github.com/mlr-org/mlr3book/tree/quarto). Thanks for your help!

**Comment by dragonstyle** [comment]
It looks to me like it is trying to read `include-in-header` files - is there any reason to suspect there might be difference there between local and CI?

**Comment by pat-s** [comment]
I don't see any 🤔 
Also made sure to start fresh locally without cache etc - still working locally and failing on CI.

I haven't found any way to enable enhanced logging or similar. 
LMK if you have an idea how I could troubleshoot this :)

**Comment by dragonstyle** [comment]
It seems like we're having trouble reading a file. I tried to add a bit of debugging to the latest version (building now). Do you trying with the latest and perhaps we'll get a more helpful error message... (build 468 should contain debugging if we fail to read an include file properly).

**Comment by pat-s** [comment]
Nice, seems to have helped a bit!

```
compilation failed- error
LaTeX Error: Environment rmdnote undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1632 \begin{rmdnote}
```

Which is caused by the failed attempt to read `preamble.tex`:

```
FAILED TO READ FILE preamble.tex
```

https://github.com/mlr-org/mlr3book/runs/6635192038?check_suite_focus=true

No idea why though - do you have another idea how to move forward from here onwards?

**Comment by jjallaire** [comment]
`rmdnote` is specifically from bookdown (it definitely shouldn't appear in a Quarto book). `preamble.tex` is also typically included in bookdown books (it's to.part of the generated YAML template). Looking at your source code I see that you have an `include-in-header: preamble.tex` but in fact have no `preamble.tex` in your project.

Charles, I think we should improve our error messages (can even do on the typescript side) so that if include files don't exist a hard error occurs w/ a clear message about what's going on.

**Comment by dragonstyle** [comment]
Agree - glad you caught the missing include - I will improve the error message!

**Comment by pat-s** [comment]
@jjallaire Ahh sorry! `preamble.tex` exists in `main` and I did not specifically remove it - turns out all tex files are git-ignore'd and it somehow got removed in the new branch 🤦 
Anyhow, I've removed it entirely now and the PDF builds just fine! 🎉 
We'll evaluate again if we might need some parts of it or we are happy without it.

Sorry for all the trouble!

**Comment by jjallaire** [comment]
Great to hear we got to the bottom of it! Leaving the issue open pending our improving behavior around missing included files

**Comment by fabge** [comment]
I am having similiar issues when trying to render:

```text
Error running filter /opt/quarto/share/filters/quarto-post/quarto-post.lua:
/opt/quarto/share/filters/quarto-post/quarto-post.lua:1752: attempt to index a nil value (field 'attr')
stack traceback:
	/opt/quarto/share/filters/quarto-post/quarto-post.lua:1063: in function </opt/quarto/share/filters/quarto-post/quarto-post.lua:1057>
Error: Process completed with exit code 1.
```

Failing pipeline
https://github.com/fabge/snippets/runs/6769585825?check_suite_focus=true

Repository
https://github.com/fabge/snippets

Thank you for your help!

**Comment by dragonstyle** [comment]
This is likely something I introduced yesterday afternoon- apologies and I’ll look at it first thing this morning!

**Comment by dragonstyle** [comment]
@fabge This should be fix now starting here 8f211f77ebc8aabf9baf6111d4e21a479a244809. A fresh release is being built now and should be available shortly. If you have a moment to confirm that this fixes the issue, I would appreciate it very much.

**Comment by fabge** [comment]
@dragonstyle Like a charm! Thank you!

**Comment by dragonstyle** [comment]
Thanks for the quick verification!
