### ISSUE TITLE
Certain urls get mangled when rendering with python kernel

### ISSUE THREAD

**Issue by machow** [quarto-dev/quarto-cli#10021]
This occurred when running a jupyter kernel.

**example.qmd**

``````
---
jupyter: python3
---

[a link](https://pr-350–quartodoc.netlify.app/api/Auto.html#quartodoc.Auto)
``````

The link target becomes `https://xn--pr-350quartodoc-ju9h.netlify.app/api/Auto.html#quartodoc.Auto`.

Here's a 1 minute screencast demo'ing:   https://www.loom.com/share/ef148ccc145e482abb17c72d62ecd9aa

### quarto version

Using quarto v1.5.45, but checked on several earlier versions of quarto also

<details>
<summary>quarto check</summary>

```
Quarto 1.5.45
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.45
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: /Users/machow/.virtualenvs/quartodoc/bin/python3
      Jupyter: 5.5.0
      Kernels: REDACTED
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
      knitr: 1.39
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK


```

</details>

**Comment by machow** [comment]
After a bit of tinkering, it feels like it has something to do with two hypens around a number, or something like that.

This also gets mangled: `https://a-3–website.com`

**Comment by mcanouil** [comment]
Thanks for the report.

The engine has nothing to do with this behaviour as you can see the same in every engines.

Why do you have a unicode character in the URL?

<img width="493" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/7a175a70-3cd0-4df0-bbc9-7b50266b0336">

**Comment by mcanouil** [comment]
The HTML produced is correct (from Pandoc and Quarto):

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
format: html
minimal: true
engine: markdown
---

[a link](https://pr-350–quartodoc.netlify.app/api/Auto.html#quartodoc.Auto)

````

</td><td>

````html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-99.9.9">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>index</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
</style>




</head>

<body>





<p><a href="https://pr-350–quartodoc.netlify.app/api/Auto.html#quartodoc.Auto">a link</a></p>





</body></html>
````

</td></tr>
</table>

Now, if you open the HTML in a browser, the browser has issues.

The whole issue is the unicode character in the URL.


https://github.com/quarto-dev/quarto-cli/assets/8896044/15175a8e-1265-4066-b1ba-f5180f2e2677

That's not a Quarto issue/bug.

**Comment by cscheid** [comment]
@machow Could you have copied+pasted this URL somewhere, or maybe your text editor replaced the `-` with a unicode dash of some kind?

**Comment by cscheid** [comment]
In any case, I think @mcanouil's diagnosis is correct, and this isn't a Quarto bug. I'm going to close this, but we should reopen if I'm wrong.

**Comment by mcanouil** [comment]
So, your URL comes from YAML.

You see the transformation as endash with the below code.

```qmd
---
format: html
value: https://xn--pr-350quartodoc-ju9h.netlify.app/api/Auto.html#quartodoc.Auto
---

{{< meta value >}}
```

And if you don't want any markdown transformation:

```qmd
---
format: html
value: "`https://xn--pr-350quartodoc-ju9h.netlify.app/api/Auto.html#quartodoc.Auto`{=html}"
---

{{< meta value >}}
```

**Comment by machow** [comment]
I think this is a clear quarto issue and needs to be reopened. Either in terms of needing to communicate to people that URLs in `_quarto.yml` might be transformed in a way (as you showed) might break them, or to fix.

**Comment by mcanouil** [comment]
Sorry, I'm confused.
How does your `https://pr-350--quartodoc.netlify.app/api/Auto.html#quartodoc.Auto` becomes `https://xn--pr-350quartodoc-ju9h.netlify.app/api/Auto.html#quartodoc.Auto`?

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/33e76f99-4096-4864-b1f7-7a31a52d154c">

**Comment by machow** [comment]
Please see my initial issue, which includes instructions to reproduce in a jupyter kernel.

https://github.com/quarto-dev/quarto-cli/issues/10021#issue-2354159783

**Comment by mcanouil** [comment]
FYI, for `href` in Quarto the trick I showed was basically implemented internally: https://github.com/quarto-dev/quarto-cli/commit/6e5976f0a9e84e7562f390a279b39519a8584ad8

**Comment by mcanouil** [comment]
> Please see my initial issue, which includes instructions to reproduce in a jupyter kernel (I suspect the engine is important? but could be wrong).
> 
> [#10021 (comment)](https://github.com/quarto-dev/quarto-cli/issues/10021#issue-2354159783)

That's because the URL is not valid in the first place as it contains an endash.
That's not Quarto or Pandoc. This is done by the browsers as showed in <https://github.com/quarto-dev/quarto-cli/issues/10021#issuecomment-2170423229>.

I'm really confused here.

**Comment by machow** [comment]
> Browsers do not like unicode in URLs and in the case of endash create a very weird URL while the HTML code is "correct".

Ahhh, this is so helpful, thanks! I didn't notice that in the source it's "okay", but has the mixed in characters when hovered over.

I guess it's just the issue of `_quarto.yml` config producing endashes then that is the big issue for me and consumers of quartodoc.

**Comment by mcanouil** [comment]
In your case, is it not possible to write a small LUA filter that adds the raw block/span code?

**Comment by cscheid** [comment]
- The `xn--` etc is punycode, emitted by Pandoc: https://en.wikipedia.org/wiki/Punycode

- We shouldn't be turning `--` into en-dashes. Pandoc is doing that, but Quarto is letting it, and it shouldn't

**Comment by mcanouil** [comment]
The "Punycode" (if did not know the term) is the browser as the emitted HTML is fine, so Pandoc is only responsible for endash, emdash, etc.

**Comment by mcanouil** [comment]
Maybe a more general fix would as the one for `href` keys would be to detect URLs/paths in YAML. (A bit tricky though)

**Comment by mcanouil** [comment]
> So, your URL comes from YAML.
> 
> 
> 
> You see the transformation as endash with the below code.
> 
> 
> 
> ```qmd
> 
> ---
> 
> format: html
> 
> value: https://xn--pr-350quartodoc-ju9h.netlify.app/api/Auto.html#quartodoc.Auto
> 
> ---
> 
> 
> 
> {{< meta value >}}
> 
> ```
> 
> 
> 
> And if you don't want any markdown transformation:
> 
> 
> 
> ```qmd
> 
> ---
> 
> format: html
> 
> value: "`https://xn--pr-350quartodoc-ju9h.netlify.app/api/Auto.html#quartodoc.Auto`{=html}"
> 
> ---
> 
> 
> 
> {{< meta value >}}
> 
> ```
> 
> 
> 
> I am not sure Quarto can do something here.
> 
> 
> 
> Maybe you could have a small Lua filter that ensure the YAML keys are treated as is.
> 
> 
> 
> I don't how how Quarto treats URLs in YAML, but I think it's done via TypeScript and not Lua.

@cscheid the above shows the issue 😉 (in a new issue indeed)

**Comment by cscheid** [comment]
See https://github.com/quarto-dev/quarto-cli/issues/10042

**Comment by cderv** [comment]
> Nothing should be turning -- into en-dashes. (Maybe?) Pandoc is doing that,

Just want to add additional information on this. 

This is Pandoc. It has a `+smart` extension that does this. See https://pandoc.org/MANUAL.html#extension-smart
> Interpret straight quotes as curly quotes, --- as em-dashes, -- as en-dashes, and ... as ellipses. Nonbreaking spaces are inserted after certain abbreviations, such as “Mr.”

This extensions is activated by default and impact how things are written in output. HTML is among the format where en-dash are used 

<table>
<tr>
<td>With smart extension
<td> without smart extensions
<tr>
<td> 

````powershell
❯ quarto pandoc --from markdown --to html
pr--450
pr-450
^Z
<p>pr–450 pr-450</p>
````
<td>

````powershell
❯ quarto pandoc --from markdown-smart --to html
pr--450
pr-450
^Z
<p>pr--450 pr-450</p>
````

Note the two dashes without smart enabled. 

This all happens in the Markdown reader ! 

<table>
<tr>
<td>With smart extension
<td> without smart extensions
<tr>
<td> 

````powershell
❯ quarto pandoc --from markdown --to native
pr--450
^Z
[ Para [ Str "pr\8211\&450" ] ]
````
<td>

````powershell
❯ quarto pandoc --from markdown-smart --to native
pr--450
^Z
[ Para [ Str "pr--450" ] ]
````

Why does it happens with metadata field ? 

Because they are parsed as Markdown values by Pandoc 
From https://pandoc.org/MANUAL.html#extension-yaml_metadata_block
> Metadata can contain lists and objects (nested arbitrarily), but **all string scalars will be interpreted as Markdown**.

We already had issues of this type in the past, and internally using the new `pandoc-native` raw block feature from pandoc was the way 

- https://github.com/quarto-dev/quarto-cli/issues/9117 (https://github.com/quarto-dev/quarto-cli/pull/9221)

Hope it helps understand. I'll also post in the other issue.
