### ISSUE TITLE
Inconsistent table formatting between vanilla Typst output and Typst extension output

### ISSUE THREAD

**Issue by mvuorre** [quarto-dev/quarto-cli#10065]
### Bug description

I created a new Quarto Typst extension called "example" with `quarto create extension format:typst`. I then compared tables within this extension to tables from vanilla Typst output, and the former have gridlines whereas the latter don't. 

(The complete source for this example is in this repo: <https://github.com/mvuorre/quarto-typst-table-reprex> and in example.zip.)
[example.zip](https://github.com/user-attachments/files/15905535/example.zip)

### Expected behavior

````
---
title: Untitled
format:
  typst: default # Tables don't have gridlines
---

```{r}
knitr::kable(data.frame(a = 1:2, b = 3:4))
```

```{r}
#| echo: false
knitr::kable(data.frame(a = 1:2, b = 3:4))
```
````

Renders to
<img width="678" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/7349270/06e9435d-0e8d-4c6b-9fc9-64172aca61fb">

### Actual behavior

````
---
title: Untitled
format:
  example-typst: default # Tables have gridlines
---

```{r}
knitr::kable(data.frame(a = 1:2, b = 3:4))
```

```{r}
#| echo: false
knitr::kable(data.frame(a = 1:2, b = 3:4))
```
````

Renders to 
<img width="714" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/7349270/8c0d998c-c9ad-4ebb-b55a-be7b856b060d">

### Your environment

OS: MacOS Sonoma 14.5
Using Quarto from terminal

### Quarto check output

Quarto 1.5.45
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.45
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources
      LibPaths:
        - /Users/matti/Library/R/arm64/4.4/library
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
May I inquire as to how Quarto is accountable for the retention of the default Typst table style within your extension?
Should the default style not meet your preferences, I would kindly suggest implementing the necessary Typst command to adjust it accordingly.
There are no bugs present in this context.

https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/typst/pandoc/quarto/typst-template.typ#L90-L93

**Comment by cscheid** [comment]
@mcanouil This is actually a bug, just FYI.

**Comment by cscheid** [comment]
The fix here is to sync up the templates with the create files at `src/resources/create/format`

**Comment by mcanouil** [comment]
To be sure, the bug is not the style of the table, but the fact that `How, so quarto create extension format:typst` does not use the correct template, correct?

**Comment by cscheid** [comment]
> To be sure, the bug is not the style of the table, but the fact that `quarto create extension format:typst` does not use the correct template, correct?

Yes.

**Comment by gordonwoodhull** [comment]
Thanks for reporting this @mvuorre!

**Comment by mvuorre** [comment]
Works great, thank you:

<img width="1063" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/7349270/aa863c3e-dfe3-4e60-8f73-539ea8027a82">
