### ISSUE TITLE
Non-breaking space being added in table cell

### ISSUE THREAD

**Issue by dmonder** [quarto-dev/quarto-cli#10089]
### Bug description

I have a Quarto document that in my environment is generated from a Word document using `pandoc` with `--from docx+styles` and `--to markdown+multiline_tables-grid_tables`. These options are needed to ensure proper conversion of tables which have Word styles being used in the cells. A mockup of the table that is generated is shown below. The table includes rows of personnel with their name and position in the first column, separated by a newline. Some personnel have prefixes of `Dr.`. The converted Markdown file shows a blank character in between `Dr.` and their first name. In the example below, I also included `Mr.` and `Mrs.` as well as an entry with `Person.` to see what other items created an invalid conversion. For rows with `Dr.`, `Mr.`, and `Mrs.`, the generated HTML include a `&nbsp;` character between the prefix and their name. This is problematic as I am using a filter that runs based on the style and uses the value in the SPAN (their prefix and name) to create a link to a file. When the filter receives this Markdown for processing, the `&nbsp;` (or technically, it appears the ASCII space character has been converted to a Unicode non-breaking space that is later converted to the `&nbsp;`, or in my case, both a `&nbsp;` and an HTML-escape sequence of `%C2%A0`.)

### Steps to reproduce

```qmd
---
title: Reproducible Quarto Document
format: html
---

This is a reproducible Quarto document using `format: html`. It is written in Markdown and contains an embedded HTML table below. When you render this document, the HTML table will include `&nbsp;` character after the `Dr.`, `Mr.`, and `Mrs.` in the rows that have those. The `&nbsp;` character will not appear anywhere else in the table, even after the other periods in the table.

<table>
<thead>
<tr class="header">
<th>Col1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>Dr. Person One</p>
<p>President</p></td>
</tr>
<tr class="even">
<td><p>Person. Two Jr.</p>
<p>Executive VP of Student Affairs</p></td>
</tr>
<tr class="odd">
<td><p>Mr. Person. Three</p>
<p>VP of Business Services CFO</p></td>
</tr>
<tr class="even">
<td><p><span data-custom-style="Link to Artifact - Resume">Mrs. Person Four</span></p>
<p>VP of Institutional Research</p></td>
</tr>
</tbody>
</table>
```

### Expected behavior

The space after the prefix should remain a normal ASCII space.

### Actual behavior

It is converted to a Unicode non-breaking space which is then converted to either a `&nbsp;` character or the HTML-escape sequence of `%C2%A0`.

### Your environment

- Quarto: 1.4.553 (with Pandoc 3.1.11, Lua 5.4)
- Pandoc: 3.2 (Lua 5.4)
- OS: Windows 11 Enterprise Version 21H2, OS Build 22000.2899

### Quarto check output

```
Quarto 1.4.553                                                    
[>] Checking versions of quarto binary dependencies...            
      Pandoc version 3.1.11: OK                                   
      Dart Sass version 1.69.5: OK                                
      Deno version 1.37.2: OK                                     
[>] Checking versions of quarto dependencies......OK              
[>] Checking Quarto installation......OK                          
      Version: 1.4.553                                            
      Path: C:\Program Files\Quarto\bin                           
      CodePage: 1252                                              
                                                                  
[>] Checking tools....................OK                          
      TinyTeX: v2024.01                                           
      Chromium: (not installed)                                   
                                                                  
[>] Checking LaTeX....................OK                          
      Using: TinyTex                                              
      Path: C:\Users\XXXXX\AppData\Roaming\TinyTeX\bin\windows\  
      Version: 2023                                               
                                                                  
[>] Checking basic markdown render....OK                          
                                                                  
[>] Checking Python 3 installation....OK                          
      Version: 3.11.6                                             
      Path: C:/Python/Python311/python.exe                        
      Jupyter: 5.7.2                                              
      Kernels: python3                                            
                                                                  
[>] Checking Jupyter engine render....OK                          
                                                                  
[>] Checking R installation...........OK                          
      Version: 4.3.1                                              
      Path: C:/R/R-4.3.1                                          
      LibPaths:                                                   
        - C:/R/R-4.3.1/library                                    
      knitr: 1.45                                                 
      rmarkdown: 2.26                                             
                                                                  
[>] Checking Knitr engine render......OK                          
```

**Comment by mcanouil** [comment]
When including raw code such as HTML or LaTeX, you should use RAW block in order to tell Quarto/pandoc that the content should not be touched and taken as is.

See <https://quarto.org/docs/authoring/markdown-basics.html#raw-content>.

**Comment by cscheid** [comment]
I will note that since the content here is a table, you'll need an additional step to stop Quarto from processing the table.

In 1.4, these are the options: https://quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing
In 1.5, there's one additional way to do it: https://quarto.org/docs/prerelease/1.5/lua-table-processing.html

**Comment by dmonder** [comment]
Since I need to have the html processed in the Lua filter, the Raw lock would be necessary. I converted my code over and it worked like a charm.
