### ISSUE TITLE
documentation: add explicit language that modifying grid options is not a document-level property for a quarto website

### ISSUE THREAD

**Issue by markjrieke** [quarto-dev/quarto-cli#10083]
### What would you like to do?

Report an issue on quarto.org

**Comment by markjrieke** [comment]
nevermind, it's 11:30pm & I've just realized there's a note calling out the behavior

**Comment by mcanouil** [comment]
For future issues, please be sure to fill properly your issue. Providing a title is not enough. The description is also important.

**Comment by markjrieke** [comment]
Yes, of course! My apologies, I was working on something late last night and thought I saw a documentation issue. While adding a description to the issue I realized that it was a moot point because the page I was referencing already included the note I was suggesting to add. I closed the issue right after opening since there's not a way to delete issues.
