### ISSUE TITLE
Generation of links to unintended images

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#1009]
It seems that cross reference links are generated for figures with HTML links even if they are not set.
When two figures like the following are embedded in HTML, hover the cursor over the former and the clip symbol will appear.

```md
[![](img/name.png)]()

![](img/name.png)
```

![image](https://user-images.githubusercontent.com/50911393/170830366-992268df-e250-412d-a5be-262d3bb388e3.png)

**Comment by jjallaire** [comment]
It looks like there is a fig-anonymous left over in the DOM that is triggering this:

<img width="682" alt="Screen Shot 2022-05-28 at 8 49 05 PM" src="https://user-images.githubusercontent.com/104391/170847423-e3d36524-9683-450c-b799-316090a659a7.png">

**Comment by jjallaire** [comment]
Thanks again for reporting, should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/c3321ae48ebe452d4b6dce76217117921caf3a10
