### ISSUE TITLE
`quarto serve` vs `quarto preview`

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#101]
With `quarto render` working both on quarto projects as well as with a file argument on individual files I wonder if the same could be achieved to make `serve` and `preview` the same (or one) command as well i.e. so that both work on projects and single documents.

**Comment by jjallaire** [comment]
Excellent point. I have made the change to using `quarto preview` for both sites and documents (`quarto serve` is still there but undocumented b/c RStudio IDE still invokes `quarto serve`)

**Comment by jmbuhr** [comment]
I think it is great that `serve` still works, because hugo uses `serve` (and `server` as an alias) so I would constantly mix it up.
