### ISSUE TITLE
VSCode Extension : Preview not working as expected for websites

### ISSUE THREAD

**Issue by declann** [quarto-dev/quarto-cli#10104]
### Bug description

- `quarto preview` redirects browsers to the actively edited ('saved') document: for any page saved across website projects.
- VSCode extension has a Preview button + a "Render on Save" option, but since the button initiates a `quarto preview path/to/file.qmd` in all cases, then it only ever reacts to saves to a single page (from which the button was clicked), as opposed to *across pages* - as `quarto preview` does

The extension Preview button doesn't correspond to what I expect from `quarto preview` (since it does `quarto preview path/to/file.qmd`)

I don't use the extension because `quarto preview` behavior is a better workflow for me when working with websites.

Perhaps Preview is an ambiguous UI and either behavior is arguably correct. But I am stating specifically what I expected, plus behavior from vanilla `quarto preview`. (and this despite the title - so feel free to close if you disagree)

I don't use the extension because I cannot reproduce the experience of `quarto preview` inside it when working with websites, which is my preferred workflow.

ref #6440

### Steps to reproduce

First turn on Render on Save in extension

then

```sh
quarto create
# then select project, website, name: the-website
cd the-website
code .
# press Preview button on index.qmd
# edit abount.qmd
```

### Expected behavior

Preview pane redirects to re-rendered about.qmd

### Actual behavior

nothing: no render or redirect

### Your environment

vscode 1.90.2

on ubuntu 22.04

### Quarto check output

```
Quarto 1.5.47
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
```

extension v1.113.0

**Comment by declann** [comment]
Moved to https://github.com/quarto-dev/quarto #472

**Comment by mcanouil** [comment]
Your link is not correct.

**Comment by mcanouil** [comment]
- quarto-dev/quarto#472

Issue is more related to VSCode extension than Quarto CLI, *i.e.*, VSCode extension is missing a "preview project" command. Currently, the `quarto preview` command always take an input file so only that file is watched for changes.
See https://github.com/quarto-dev/quarto/issues/472#issuecomment-2185317653
