### ISSUE TITLE
favicon not faund error

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#1010]
When I run quarto preview on the latest build, favicon does not display correctly. (It seems to be looking for absolute paths)

```sh
$ quarto preview
Preparing to preview

Watching files for changes
Browse at http://localhost:4870/
GET: /
  /img/favicon.png (404: Not Found)
```

```yaml
website:
  favicon: img/favicon.png
```

v0.9.429 works, and v0.9.471 does not work.

**Comment by jjallaire** [comment]
This should be fixed here (https://github.com/quarto-dev/quarto-cli/commit/f61d5ec835338ec8b1b224fd34287f5e4202c9c1). Thanks for reporting!
