### ISSUE TITLE
When error happens, show full path of found `_quarto.yml`

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#10125]
The confusion in https://github.com/quarto-dev/quarto-cli/issues/6625 would have been avoided if Quarto showed the path to the detected project.

**Comment by cscheid** [comment]
Fixed by 54bbd977ef278ce014a1562734d45e5c0865e6a6 (no tests because we don't have good infrastructure for testing/regressing on error messages)

**Comment by cderv** [comment]
> (no tests because we don't have good infrastructure for testing/regressing on error messages)

I think we have what is required to test it. I added a test for this in 
- https://github.com/quarto-dev/quarto-cli/pull/11244

That way it is covered
