### ISSUE TITLE
remove polyfill.io integration

### ISSUE THREAD

**Issue by josherrickson** [quarto-dev/quarto-cli#10135]
### Bug description

The polyfill.io domain has been compromised: https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/

A link to the CDN is included in most (all?) websites generated by Quarto through MathJax. Can it be removed, and if it's functionality is deemed to be needed, replaced with the cloudflare or fastly CDNs as linked on that page?

### Steps to reproduce

Grep any html page for "polyfill.io".

### Expected behavior

Links to the polyfill.io CDN should be removed.

### Actual behavior

They are currently not removed.

### Your environment

All.

### Quarto check output

Not relevant.

**Comment by mcanouil** [comment]
It's included in Pandoc templates as part of support for MathJax.
Removing it without proper MathJax/Pandoc update would break all Math equations using the MathJax library.

Note that users can opt-out MathJax by opting in the other math framework.

**Comment by yutannihilation** [comment]
As you can see, Quarto (and Pandoc) already switched the library to the one provided by Cloudflare a while ago. The problem is that old version actually uses polyfill .io (I found my website built with Quarto v1.3 loads polyfill .io). 

https://github.com/search?q=repo%3Aquarto-dev%2Fquarto-cli%20%22polyfill%22&type=code

**Comment by yutannihilation** [comment]
Quarto: https://github.com/quarto-dev/quarto-cli/commit/27c03ce631bf913342064e904af49746eb84aaa9
Pandoc: https://github.com/jgm/pandoc/commit/5877ec546df29115163b36de32837f5e08506092

**Comment by mcanouil** [comment]
> a while ago

It's last march, meaning it is in place only for Quarto 1.5 (release candidate state).
![image](https://github.com/quarto-dev/quarto-cli/assets/8896044/4d6a4566-ebbb-46f5-bb35-5757f6afba96)

**Comment by mcanouil** [comment]
@josherrickson Future the future, let us be judge of if it's relevant or not please. Which in this case, it is.

![image](https://github.com/quarto-dev/quarto-cli/assets/8896044/002f8388-e8da-4f68-bec9-a9451ecd3649)

**Comment by yutannihilation** [comment]
Sorry, I forgot v1.5 is an RC version. Thanks for clarifying.

**Comment by josherrickson** [comment]
This is a rather urgent issue; any chance of a patch for 1.4 (or even earlier versions) with this fix?

**Comment by mcanouil** [comment]
Probably not, as it would mean to backport a Pandoc upgrade.
As said, 1.5 is currently in release candidate state.
If you need, then I suggest to upgrade to 1.5 pre-release.

**Comment by cscheid** [comment]
@josherrickson we've been aware of the polyfill.io issue since March. We're aware and we took steps then. Please don't imply we're not being responsive.

**Comment by cscheid** [comment]
I'm going to go ahead and close this since we've already fixed it. We can have a separate conversation about what to do with Pandoc and backports etc in a separate discussion.

**Comment by cscheid** [comment]
For other folks that might land here, we've fixed this since https://github.com/quarto-dev/quarto-cli/releases/v1.5.24.

**Comment by cscheid** [comment]
New v1.4 release with a direct backport is now being published as well.

**Comment by yutannihilation** [comment]
FYI, I think quarto can actually consider removing polyfill. I filed an issue on Pandoc's side.

https://github.com/jgm/pandoc/issues/9918

**Comment by yutannihilation** [comment]
Pandoc removed polyfill.

https://github.com/jgm/pandoc/commit/59cc5c37251a9a180717474612d6efbd4ad90402

**Comment by mcanouil** [comment]
@yutannihilation Thanks.
It will come to Quarto as soon as there is a Pandoc release.
