### ISSUE TITLE
Language tag `de-CH` seems to be ignored

### ISSUE THREAD

**Issue by rastrau** [quarto-dev/quarto-cli#10141]
I use Quarto for a [personal project](https://github.com/rastrau/monitoring-geodienste-ch). The output format is HTML (single-page). In my [Quarto document](https://github.com/rastrau/monitoring-geodienste-ch/blob/main/index.qmd) I set the language as follows:
```
lang: de-CH
```

However, footnotes (endnotes) are still denoted "Fußnoten" which is `lang: de-DE` (i.e., Germany-based German) style ("ß" is not used in Switzerland at all).

**Comment by cscheid** [comment]
@rastrau we're missing those, but you're always welcome to contribute them! See https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language.
