### ISSUE TITLE
Flextable not printing renderable content in quarto.

### ISSUE THREAD

**Issue by abalter** [quarto-dev/quarto-cli#10147]
### Bug description

Flextable is printing stuff that quarto can't render.

### Steps to reproduce

````
# Representitive Salaries {#sec-representitive-salaries}

```{r, include=F}
library(tidyverse)
library(flextable)

# data = read_csv("data/salaries.csv") %>% rename(`Earner Class` = earner_class)
data = tibble::tribble(
            ~role,     ~Earner.Class, ~Annual.Salary, ~Monthly.Pay, ~Weekly.Pay, ~Hourly.Wage,
   "Data Analyst",     "Top Earners",  "$127,790.00", "$10,649.00", "$2,458.00",     "$61.00",
   "Data Analyst", "75th Percentile",  "$102,900.00",  "$8,575.00", "$1,979.00",     "$49.00",
   "Data Analyst",         "Average",   "$87,640.00",  "$7,303.00", "$1,685.00",     "$42.00",
   "Data Analyst", "25th Percentile",   "$66,300.00",  "$5,525.00", "$1,275.00",     "$32.00",
  "Data Engineer",     "Top Earners",  "$171,801.00", "$14,316.00", "$3,303.00",     "$83.00",
  "Data Engineer", "75th Percentile",  "$145,800.00", "$12,150.00", "$2,803.00",     "$70.00",
  "Data Engineer",         "Average",  "$138,279.00", "$11,523.00", "$2,659.00",     "$66.00",
  "Data Engineer", "25th Percentile",  "$121,400.00", "$10,116.00", "$2,334.00",     "$58.00"
  )

roles = data$role %>% unique() %>% sort()
```

## Representative Salaries {#sec-representative-salaries}

```{r echo=FALSE, message=FALSE, warning=FALSE}

for (role in roles) {
  role_title <- str_to_title(role)
  print(role_title)
  
  salaries <- data %>%
    filter(role == !!role) %>%
    select(-role)
  
  salary_table = 
    salaries %>% 
    flextable() %>% 
    autofit() %>%
    # theme_box() %>%
    set_caption(caption = role_title)
  
  # Print the table using knit_print to render in the document
  print(salary_table, preview="html")
}
```
````

### Expected behavior

I should see tables in the resulting html file. I've tried various combinations of using `preview="html"` and `results="asis"`.

### Actual behavior

> [1] "Data Analyst"
> a flextable object.
> col_keys: `Earner.Class`, `Annual.Salary`, `Monthly.Pay`, `Weekly.Pay`, `Hourly.Wage` 
> header has 1 row(s) 
> body has 4 row(s) 
> original dataset sample: 
>      Earner.Class Annual.Salary Monthly.Pay Weekly.Pay Hourly.Wage
> 1     Top Earners   $127,790.00  $10,649.00  $2,458.00      $61.00
> 2 75th Percentile   $102,900.00   $8,575.00  $1,979.00      $49.00
> 3         Average    $87,640.00   $7,303.00  $1,685.00      $42.00
> 4 25th Percentile    $66,300.00   $5,525.00  $1,275.00      $32.00
> [1] "Data Engineer"
> a flextable object.
> col_keys: `Earner.Class`, `Annual.Salary`, `Monthly.Pay`, `Weekly.Pay`, `Hourly.Wage` 
> header has 1 row(s) 
> body has 4 row(s) 
> original dataset sample: 
>      Earner.Class Annual.Salary Monthly.Pay Weekly.Pay Hourly.Wage
> 1     Top Earners   $171,801.00  $14,316.00  $3,303.00      $83.00
> 2 75th Percentile   $145,800.00  $12,150.00  $2,803.00      $70.00
> 3         Average   $138,279.00  $11,523.00  $2,659.00      $66.00

4 25th Percentile   $121,400.00  $10,116.00  $2,334.00      $58.00

### Your environment

```
(base) balter@expiyes:~$ R --version
R version 4.3.3 (2024-02-29) -- "Angel Food Cake"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

(base) balter@expiyes:~$ conda list | grep flextable
  r-flextable                       0.9.6           r43hc72bb7e_0        conda-forge
(base) balter@expiyes:~$ quarto --version
1.4.550
(base) balter@expiyes:~$ which quarto
/home/balter/micromamba/bin/quarto
```

### Quarto check output

(base) balter@expiyes:~/aagu_main_document$ quarto check
Quarto 1.4.550
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.58.3: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.550
      Path: /home/balter/micromamba/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.06
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/balter/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.9 (Conda)
      Path: /home/balter/micromamba/bin/python
      Jupyter: 5.7.2
      Kernels: python3, ir

[✓] Checking Jupyter engine render....OK

(/) Checking R installation...........starting httpd help server ... done
[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /home/balter/micromamba/lib/R
      LibPaths:
        - /home/balter/micromamba/lib/R/libraries
        - /home/balter/micromamba/lib/R/site-library
        - /home/balter/micromamba/lib/R/library
      knitr: 1.47
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
We expect you to be more constructive in your issues. Please edit it accordingly.

**Comment by mcanouil** [comment]
Also, please be sure to at least update to latest stable version when reporting issues.

Note also that your example is not complete in the sense as it lacks information such as format.

Side note: Quarto uses YAML style for all options. Using the "old" `knitr` inline syntax can lead to spurious results in the future, especially if you start using Quarto specific features (as YAML) at the same time.

**Comment by abalter** [comment]
I was being facetious. I hope my changes are sufficient.

**Comment by cscheid** [comment]
Don't call someone else's library dumb, that's really not acceptable behavior in this repository. I will insist: please edit your title.

**Comment by abalter** [comment]
I didn't call flexbox dumb. I said it was _being_ dumb. It's probably the best R table library right now.

**Comment by abalter** [comment]
Ooops. I did edit the title, but I think it didn't save right.

**Comment by mcanouil** [comment]
Everything you need is in `flextable` documentation: https://davidgohel.github.io/flextable/reference/flextable_to_rmd.html

Checking the documentation of the libraries you are using should be the first thing to do.

<table>
<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
title: "Quarto Playground"
format: html
---

```{r}
#| include: false
library(dplyr)
library(tibble)
library(flextable)

data <- tribble(
            ~role,     ~Earner.Class, ~Annual.Salary, ~Monthly.Pay, ~Weekly.Pay, ~Hourly.Wage,
   "Data Analyst",     "Top Earners",  "$127,790.00", "$10,649.00", "$2,458.00",     "$61.00",
   "Data Analyst", "75th Percentile",  "$102,900.00",  "$8,575.00", "$1,979.00",     "$49.00",
   "Data Analyst",         "Average",   "$87,640.00",  "$7,303.00", "$1,685.00",     "$42.00",
   "Data Analyst", "25th Percentile",   "$66,300.00",  "$5,525.00", "$1,275.00",     "$32.00",
  "Data Engineer",     "Top Earners",  "$171,801.00", "$14,316.00", "$3,303.00",     "$83.00",
  "Data Engineer", "75th Percentile",  "$145,800.00", "$12,150.00", "$2,803.00",     "$70.00",
  "Data Engineer",         "Average",  "$138,279.00", "$11,523.00", "$2,659.00",     "$66.00",
  "Data Engineer", "25th Percentile",  "$121,400.00", "$10,116.00", "$2,334.00",     "$58.00"
  )
```

## Representative Salaries

```{r}
#| output: asis
#| echo: false
#| message: false
#| warning: false

for (role in sort(unique(data[["role"]]))) {
  role_title <- tools::toTitleCase(role)
  print(role_title)

  salary_table <- data |>
    filter(role == !!role) |>
    select(-role) |>
    flextable() |>
    autofit() |>
    set_caption(caption = role_title)

  flextable_to_rmd(salary_table)
}
```
````

</td><td>

<img width="563" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/ddf5780b-9442-419a-ace8-96af7c477b06">

</td></tr>
</table>

**Comment by abalter** [comment]
Ok, so some things:

## YAML vs. Inline Options
I have been struggling hard to get quarto to successfully render my project including tables in three formats consistently: html, docx, PDF. In this process I have been trying multiple table packages and other things. There have been moments when for whatever reason inline options got me closer to what I was trying to get to than YAML options. In fact, I'm pretty sure that changing to inline options was the last thing I "tried" before posting.

So I agree that it's best to use YAML options. However until the entire r+quarto+... ecosystem stabilizes, it is necessary to often try different things so that you can get your project to work. So I'd like to suggest you be more flexible in what you expect of people when using quarto.

## Quarto Version
I've installed the latest conda package for Linux. I see that it is out of date. I'll switch to installing it using apt. HOWEVER, as with the previous issue, not all users are free to update their software all the time. If I didn't have sudo access, I woudl be stuck with conda's version, or whatever R installs. So, again, let's try to all be in this together.

## Reproducible Example
I'm genuinely curious about what is not "reproducible" about my example? There are no additional files.

I put that file in my home directory and rendered it using `quarto render representitive_salaries.qmd --to html` etc.

**Comment by abalter** [comment]
I tried `flextable_to_rmd` as well. Some things about that:

1. It blocks interactive testing.
2. It didn't render in one of my output formats. I'll check again.
3. Notice that the caption is missing.

**Comment by abalter** [comment]
Ok. Your example does successfully render both html and docx. But it is not showing captions.

**Comment by mcanouil** [comment]
> So I'd like to suggest you be more flexible in what you expect of people when using quarto.

"Side note" means exactly that. There was no "you have to", "you must", or "Quarto requires".

> I put that file in my home directory and rendered it using quarto render representitive_salaries.qmd --to html etc. It seems to me like a complete example.

You never stated the format or the command you used. `flextable` supports several.

Regarding `flextable` abilities that's not up to Quarto. The author is quite nice and is trying to address as many issues as possible. Also why "flextable is dumb in Quarto" was really inappropriate.

Note also that there are open issues involving `flextable` (and other table libraries):
- https://github.com/quarto-dev/quarto-cli/issues/7321

There are various discussions on knitr/rmarkdown and Quarto either on discussions or issues regarding printing tables/figures inside loops.
You will find the same answer in every single one of those places: use `knitr::knit_child`.
This is basically what `flextable_to_rmd` does https://github.com/davidgohel/flextable/blob/HEAD/R/printers.R#L88-L110

You could use the same principle to add label and caption, which would make the table cross-referenceable.

<details><summary>Code</summary>

````qmd
---
title: "Quarto Playground"
format: html
---

```{r}
#| include: false
library(dplyr)
library(tibble)
library(flextable)

data <- tribble(
            ~role,     ~Earner.Class, ~Annual.Salary, ~Monthly.Pay, ~Weekly.Pay, ~Hourly.Wage,
   "Data Analyst",     "Top Earners",  "$127,790.00", "$10,649.00", "$2,458.00",     "$61.00",
   "Data Analyst", "75th Percentile",  "$102,900.00",  "$8,575.00", "$1,979.00",     "$49.00",
   "Data Analyst",         "Average",   "$87,640.00",  "$7,303.00", "$1,685.00",     "$42.00",
   "Data Analyst", "25th Percentile",   "$66,300.00",  "$5,525.00", "$1,275.00",     "$32.00",
  "Data Engineer",     "Top Earners",  "$171,801.00", "$14,316.00", "$3,303.00",     "$83.00",
  "Data Engineer", "75th Percentile",  "$145,800.00", "$12,150.00", "$2,803.00",     "$70.00",
  "Data Engineer",         "Average",  "$138,279.00", "$11,523.00", "$2,659.00",     "$66.00",
  "Data Engineer", "25th Percentile",  "$121,400.00", "$10,116.00", "$2,334.00",     "$58.00"
  )
```

## Representative Salaries

```{r}
#| output: asis
#| echo: false
#| message: false
#| warning: false

for (role in sort(unique(data[["role"]]))) {
  role_title <- tools::toTitleCase(role)
  print(role_title)

  salary_table <- data |>
    filter(role == !!role) |>
    select(-role) |>
    flextable() |>
    autofit()

  cat(knitr::knit_child(
    text = c(
      "```{r}",
      "#| echo: false",
      sprintf("#| label: tbl-%s", gsub(" ", ".", role_title)),
      sprintf("#| tbl-cap: %s", role_title),
      "salary_table",
      "```",
      ""
    ),
    envir = environment(),
    quiet = TRUE
  ), sep = "\n")
}
```
````

</summary>

<img width="610" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/745e319e-92d8-4685-ac80-422980be046c">
