### ISSUE TITLE
Detect Microsoft Edge install (if Google Chrome isn't) on MacOS

### ISSUE THREAD

**Issue by jmhammond** [quarto-dev/quarto-cli#10162]
### Bug description

When trying to render documents that include diagrams, we need to have some chrome-based browser installed.  
Because of work, I have Microsoft Edge installed, and I don't have Google Chrome, because the two browsers are both really large.

The [line of code here](https://github.com/quarto-dev/quarto-cli/blob/e512cf662ceae7630eab49723904fe3f3fec60c5/src/core/puppeteer.ts#L205): 
```
    path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
```
looks only for Chrome on MacOS, but checks for Edge when the OS is Windows.  Is it possible to also look for `/Applications/Microsoft\ Edge.app/Contents/MacOS/Microsoft\ Edge` on MacOS?                                                                                             

### Steps to reproduce

```markdown
---
title: "In-Class: Relations - Digraphs"
format: 
  pdf: default
---
Any quarto document that includes a diagram and compiling a PDF; here's a sample:

...

` pretend these are connected... formatted for bugreport ``{dot}
//| fig-width: 2
digraph {
  node [shape = circle, width=0.5];
  rankdir = LR;
  1 -> 1;
  1 -> 2;
  2 -> 4; 
  1 -> 3;
  3 -> 4;
  4 -> 1;
}
` pretend these are connected... formatted for bugreport ``

```

### Expected behavior

Detect Microsoft Edge as my chromium browser [(as noted in the documentation).](https://quarto.org/docs/authoring/diagrams.html#chrome-install)

### Actual behavior

It says I need to install chrome.

### Your environment

- IDE: VS Code
- OS: MacOS 14.5

### Quarto check output

```text
Quarto 1.4.556
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.556
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1 (Conda)
      Path: /opt/homebrew/Caskroom/miniforge/base/envs/pysquirrel/bin/python
      Jupyter: 5.7.1
      Kernels: python3, ir, SageMath-10.1

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
I don't Quarto should try to detect whatever chromium-based browser is installed.
There are way too many, installation path can be very different from one system to another, etc.

This being said, having a `QUARTO_CHROMIUM` environment variable would allow users to set whatever they think might work.

Note that chromium is not a full browser.

**Comment by cscheid** [comment]
> Note that chromium is not a full browser.

What do you mean?

**Comment by mcanouil** [comment]
Sorry, I meant Quarto does not use/install the full version of Chromium and that Chromium has a very minimalist user interface without all the features Chrome/Edge/Brave/etc have

**Comment by jmhammond** [comment]
Having an environment variable would be really helpful. 

My issue with the `quarto install chromium` at the moment is the version it’s pulling crashes every single time with not logging to diagnose the problem.

**Comment by cscheid** [comment]
We'll add an environment variable. Seems like a good thing to do for 1.6.

**Comment by mcanouil** [comment]
@cscheid we probably also need to update the documentation as we currently state that both Chrome and Edge are detected by Quarto.

**Comment by cderv** [comment]
I have opened an macro issue to track a proper solution 
- https://github.com/quarto-dev/quarto-cli/issues/10170

**Comment by cderv** [comment]
> we probably also need to update the documentation as we currently state that both Chrome and Edge are detected by Quarto.

@mcanouil We do detect Edge I believe, but on Windows only it seems 
https://github.com/quarto-dev/quarto-cli/blob/e8c3cbf43a0217c7d4a2afc31b3ee42c5b37db09/src/core/puppeteer.ts#L209-L233

Documentation is not completely incorrect, it is probably just innacurate by not stating it is windows only. 

So I believe this is the part of the code that could be fixed easily to indeed also find Edge on Mac as it is done on Windows, as it happens Edge is available on Mac and Windows.

**Comment by mcanouil** [comment]
`/Applications/Microsoft\ Edge.app/Contents/MacOS/Microsoft\ Edge` from the original post.

**Comment by cderv** [comment]
Ah thanks ! Missed it !
