### ISSUE TITLE
Support `csl` YAML field for Typst as in Pandoc 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#10168]
Pandoc support using csl and fallback to `bibliographystyle` since 3.1.10 (https://github.com/jgm/pandoc/commit/e562d23bc7e21cd7395bee2997c845b3bdfd6afd)

https://github.com/quarto-dev/quarto-cli/blob/5dc09d8b4c61055270d60960020e25efe810c09a/src/resources/formats/typst/pandoc/typst.template#L93-L100

It seems we get it in our pandoc updates, but we didn't port it to our partials 

https://github.com/quarto-dev/quarto-cli/blob/5dc09d8b4c61055270d60960020e25efe810c09a/src/resources/formats/typst/pandoc/quarto/biblio.typ#L1-L5

@cscheid @gordonwoodhull is there a specific reason for this to not break something ? 

Or just an oversight for when we updated pandoc version and then templates ? We may miss other part from pandoc's update.

**Comment by cscheid** [comment]
I think we simply missed it.
