### ISSUE TITLE
Embedding another qmd with title overrides the page's title 

### ISSUE THREAD

**Issue by JAttig** [quarto-dev/quarto-cli#10171]
### Bug description

Embedding a quarto notebook with a markdown h1 header in its first cell, causes that header to override the title of the page.
similar to [issue 5785](https://github.com/quarto-dev/quarto-cli/issues/5785)

### Steps to reproduce

some_doc.qmd

````
---
title: my title
---

# Section 1

{{< include  another.qmd >}}

````

`Another.qmd` looks like this:

````
---
title: this is about some subtopic
---

hi there
````

### Expected behavior

Rendering produces html document with title "my title"

### Actual behavior

output is titled "this is about some subtopic"

### Your environment

- IDE Rstudio 2024.04.2 Build 764
- R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22621)

### Quarto check output

Quarto 1.5.52
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.52
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.4.0
      Path: C:/PROGRA~1/R/R-44~1.0
      LibPaths:
        - C:/Users/attigj/AppData/Local/R/win-library/4.4
        - C:/Program Files/R/R-4.4.0/library
      knitr: 1.47
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Could you make sure your example is reproducible? `{{< another.qmd >}}` is not a valid shortcode in Quarto.

If you are using `{{< include another.qmd >}}` then you missed the important note in the documentation: https://quarto.org/docs/authoring/includes.html#overview

> Include shortcodes are equivalent to copying and pasting the text from the included file into the main file. This means that relative references (links, images, etc.) inside the included file resolve based on the directory of the main file not the included file.
> 
> It also means that if the included file has a metadata block, that block will take effect in all included files. In most cases, having metadata blocks in an included file will cause unexpected behavior.

For short, this is a documented and expected behaviour.

**Comment by JAttig** [comment]
Dear @mcanouil  thank you, indeed I used `{{< include document.qmd>}}` and your  `{{< embed document.qmd >}}` is the desired behaviour. Kind regards, Jan

**Comment by mcanouil** [comment]
Then, I'm closing.

Glad you found the right tool for your use case.
