### ISSUE TITLE
Bug: Terminal Misinterpreting “quarto publish” Command

### ISSUE THREAD

**Issue by Fgazzelloni** [quarto-dev/quarto-cli#10183]
### Bug description

I am encountering a bug when attempting to use the quarto publish command in the RStudio terminal. Despite typing the command correctly, the terminal reports that it does not recognize the command “quarto prublish,” which is not what I typed.

<img width="768" alt="Screenshot 2024-07-01 at 12 59 53" src="https://github.com/quarto-dev/quarto-cli/assets/61802414/f444e0c7-34d9-4215-bf82-268115d5f6cd">

### Steps to reproduce

	1.	Open RStudio.
	2.	Open the terminal within RStudio.
	3.	Type the command quarto publish and press Enter.
	4.	Observe the terminal’s response.

### Expected behavior

The terminal should recognize the quarto publish command and proceed with the publication process as expected.

### Actual behavior

The terminal incorrectly interprets the command as quarto prublish and returns an error stating that the command is not recognized.

### Your environment

- IDE RSTUDIO Version 2024.04.1+748 (2024.04.1+748)
- MAC OS 14.5 (23F79)

### Quarto check output

Federicas-MacBook-Air:R federicagazzelloni$ quarto check
Quarto 1.5.52
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.52
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.06
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/federicagazzelloni/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

**Comment by cderv** [comment]
Can you try in an external Terminal , meaning not inside RStudio IDE ? 

I can't reproduce this, and this is indeed very puzzling. 

It seems like the Terminal inside RStudio IDE is adding some character somehow... 

This could be an RStudio IDE issue rather than Quarto Issue. 🤔 

Thank you

**Comment by Fgazzelloni** [comment]
I usually do not experience this issue. I was recording a live session and just typed the command again and it worked. Could it be copilot? I had a nice conversation with Chat GPT and it agreed that copilot could influence this behavior.

**Comment by mcanouil** [comment]
Copilot doesn't add contents in the terminal by itself that would be very dangerous.

Do you have Zsh or any custom shell profile?

**Comment by cderv** [comment]
> I usually do not experience this issue. I was recording a live session and just typed the command again and it worked. Could it be copilot? I had a nice conversation with Chat GPT and it agreed that copilot could influence this behavior.

I don't know. It seems related to some behavior between all the layer (IDE, terminal, copilot, ...). Glad it works ok now ! 

If it happens again, I don't think this is on Quarto side you should report.
