### ISSUE TITLE
Typst raw code not working (dividing one single page to columns)

### ISSUE THREAD

**Issue by marcboschmatas** [quarto-dev/quarto-cli#10185]
### Bug description

I am trying to divide one single page into two columns for a quarto document that needs to render to typst. However, the typst code I am trying to include does not translate into the typst code.

### Steps to reproduce

````
---
title: "Something"
subtitle: "Something else"
knitr: 
  opts_chunk:
    fig.align: center # this is not working
keep-typ: true
format:
  typst:
    fontsize: 20pt

echo: false
message: false
warning: false
---

# Option 1

```{typst}
#set page(columns: 2)
blablablablabla
#colbreak()
blablablablabla
```

# Option 2
```{typst}
#set page(columns: 2)
```
blablablablabla
```{typst}
#colbreak()
```
blablablablabla

````

### Expected behavior

I should expect to have a page with the text divided into two columns

### Actual behavior

In option one, nothing appears in the .typ file, so you'd have the following.

```{typst}
= Option 1
```

In option two, only the text appears in the .typ.

```{typst}
= Option 2
blablablabla
blablablabla
```

### Your environment

- IDE: RStudio 2023.06.0
- OS: Windows 11

### Quarto check output

```
Quarto 1.4.555
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.555
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

(|) Checking tools....................
```

**Comment by mcanouil** [comment]
You did not write raw code blocks.
You wrote "computational" code cells.

See <https://quarto.org/docs/authoring/markdown-basics.html#raw-content>.
