### ISSUE TITLE
Unable to log back into Quarto Pub with GitHub

### ISSUE THREAD

**Issue by Fgazzelloni** [quarto-dev/quarto-cli#10182]
### Bug description

I am experiencing an issue where I am unable to log back into Quarto Pub using my GitHub account. This issue started on June 28, 2024, and I have not been able to access my account since. Although I can publish from RStudio and have access to published websites.

https://github.com/quarto-dev/quarto-cli/assets/61802414/b39546b8-4b69-4968-ae93-18e0b3e9de7e

### Expected behavior

To be able to login

### Actual behavior

Not able to login

### Your environment

- IDE RSTUDIO Version 2024.04.1+748 (2024.04.1+748)
- MAC OS 14.5 (23F79)

### Quarto check output

Federicas-MacBook-Air:R federicagazzelloni$ quarto check
Quarto 1.5.52
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.52
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.06
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/federicagazzelloni/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

**Comment by cderv** [comment]
Hi, 

as I answered to your previous comment (https://github.com/quarto-dev/quarto-cli/issues/5845#issuecomment-2199773677), we identified an issue with the login infrastructure using external auth workflow. 

This is not straightforward to fix, but we have a team on deck for this. Thanks for your patience. 

As an alternative, Posit.cloud allows to publish Quarto content like with quarto.pub

[quarto.org/docs/publishing/posit-cloud.html](https://quarto.org/docs/publishing/posit-cloud.html)
[docs.posit.co/cloud/guide/publish](https://docs.posit.co/cloud/guide/publish/)

**Comment by cderv** [comment]
@Fgazzelloni this should be resolved. Can you try again ?

**Comment by Fgazzelloni** [comment]
Hi! Thanks, I am back in!!

**Comment by Fgazzelloni** [comment]
Can you tell what has happened?

**Comment by mcanouil** [comment]
A server-side issue.

**Comment by cderv** [comment]
> Can you tell what has happened?

@Fgazzelloni I already shared what happened in my previous command. 

> we identified an issue with the login infrastructure using external auth workflow.

This was solved by support team in charge of the service.
