### ISSUE TITLE
Error running filter when compiling a manusript

### ISSUE THREAD

**Issue by learn2free** [quarto-dev/quarto-cli#10190]
### Bug description

  keywError running filter C:/Users/weipeng/AppData/Local/Programs/Quarto/share/filters/main.lua:
...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:11765: attempt to index a nil value (field 'caption_long')
stack traceback:
        [C]: in ?
        [C]: in method 'walk'
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:557: in function <...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:546>
        (...tail calls...)
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:11762: in local 'filter_fn'
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:635: in function <...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:625>
        (...tail calls...)
        [C]: in ?
        [C]: in method 'walk'
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:557: in function <...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:546>
        (...tail calls...)
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:1334: in local 'callback'
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:1388: in function <...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:1385>
stack traceback:
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:557: in function <...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:546>
        (...tail calls...)
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:11762: in local 'filter_fn'
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:635: in function <...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:625>
        (...tail calls...)
        [C]: in ?
        [C]: in method 'walk'
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:557: in function <...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:546>
        (...tail calls...)
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:1334: in local 'callback'
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
        ...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:1388: in function <...eng/AppData/Local/Programs/Quarto/share/filters/main.lua:1385>
stack traceback:
        

### Steps to reproduce

````
---
title: aaaaaa
encoding: UTF-8
header-includes: \usepackage{ctex}
subtitle: Perspectives from Asian Monsoon Influence and Machine Learning
execute:
  echo: false
author:
  - name: Wei Peng
    email: weipeng_1981@hotmail.com
    affiliations: 
        - id: some-tech
          name: Chinese Research Academy of Environmental Sciences
          department: Department Name
          address: Street Address
          city: Beijing
          state: China
          postal-code: Postal Code
    attributes:
        corresponding: true
    note: This is the first author footnote.

  - name: someone
    email: bob@example.com
    affiliations:
        - id: another-u
          name: Another University
          department: Department Name
          address: Street Address
          city: City
          state: State
          postal-code: Postal Code
    note: |
      Another author footnote, this is a very long footnote and it should be a really long footnote. But this footnote is not yet sufficiently long enough to make two lines of footnote text.

  - name: someone
    email: cat@example.com
    affiliations:
        - ref: another-u
    note: Yet another author footnote.
  - name: Derek Zoolander
    email: derek@example.com
    affilations:
        - ref: some-tech
abstract: |
keywords: 
date: last-modified
bibliography: references.bib
---

# Introduction
Based on data up to and including 1971, eruptions on La Palma happen every 79.8 years on average.

Studies of the magma systems feeding the volcano, such as , have proposed that there are two main magma reservoirs feeding the Cumbre Vieja volcano; one in the mantle (30-40km depth) which charges and in turn feeds a shallower crustal reservoir (10-20km depth).
````

### Expected behavior

generate web preview and pdf file in 1.6

### Actual behavior

stoped in 1.60,1.5
it works in 1.4

### Your environment

Version: 1.90.2 (system setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

### Quarto check output

Quarto 1.6.0
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.6.0
      Path: C:\Users\weipeng\AppData\Local\Programs\Quarto\bin
      CodePage: 936

[>] Checking tools....................OK
      Chromium: 869685
      TinyTeX: (not installed)

[>] Checking LaTeX....................OK
      Using: Installation From Path
      Path: C:\texlive\2024\bin\windows
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.7 (Conda)
      Path: C:/ProgramData/Anaconda3/python.exe
      Jupyter: 5.5.0
      Kernels: ir, python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/weipeng/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Sorry, your document is incomplete (I don't see the abstract or keywords). We really do need a full document to be able to reproduce.

**Comment by mcanouil** [comment]
Could you share a **small self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository? The goal is to make it as easy as possible for us to recreate your problem so that we can fix it: please help us help you! Thanks.


---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by learn2free** [comment]
Hi,
As the article has not been published yet, I shared some of the QMD documents. However, I faced compilation issues on my computer. I ended up downgrading the Quarto version, and now it compiles successfully. Thank you.
________________________________
发件人: github-actions[bot] ***@***.***>
发送时间: 2024年7月19日 9:53
收件人: quarto-dev/quarto-cli ***@***.***>
抄送: learn2free ***@***.***>; Author ***@***.***>
主题: Re: [quarto-dev/quarto-cli] Error running filter when compiling a manusript (Issue #10190)


Thank you for using Quarto and reporting an issue!

Unfortunately, this issue is now considered stale because it has been opened since 14 days without providing a "working" reproducible example to help us investigate.
If you are still facing the issue, please review the "Bug Reports" guide<https://quarto.org/bug-reports.html> on how to provide a fully reproducible example as a self-contained Quarto document or a link to a Git repository.
Without a reproducible example, it is unlikely that the issue will be addressed.

You can share a Quarto document using the following syntax, i.e., using more backticks than you have in your document (usually four ````).

````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````


―

**Comment by mcanouil** [comment]
We don't need your article, we need a small example to reproduce the issue which you can build out of your article replacing content by fake content.
