### ISSUE TITLE
Invalid flags error after upgrading

### ISSUE THREAD

**Issue by postylem** [quarto-dev/quarto-cli#10195]
### Bug description

After `git pull`ing the latest version, quarto now errors when running any command.

### Steps to reproduce

run

```bash
quarto check
```

or other commands, eg
```bash
quarto render 
```

### Expected behavior

running 
```bash
quarto check
```
I expect output showing quarto version and dependencies
```
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
... etc
```

### Actual behavior

but instead, I get the following error
```
error: Uncaught (in promise) SyntaxError: Invalid flags supplied to RegExp constructor 'l'
const kNamedFileRegex = RegExp(kNamedFilePattern, "l");
                        ^
    at RegExp (<anonymous>)
    at file:///Users/j/Documents/GitHub/quarto-cli/src/project/types/website/util/discover-meta.ts:24:25
```

It looks like this 'l' flag was introduced in the commit https://github.com/quarto-dev/quarto-cli/commit/19ef00f8639d210acf699ab646a18569f01b068f.  Is there a dependency that I may be missing?  In the past I've simply git pulled and had no issues.

### Your environment

- IDE: n/a (terminal... I've tried in Terminal.app as well as kitty)
- OS: macOS Sonoma 14.5

### Quarto check output

See above. Currently quarto check doesn't run.

**Comment by mcanouil** [comment]
Are you using the development version?
If so, did you follow the [`README`](https://github.com/quarto-dev/quarto-cli?tab=readme-ov-file#development-version)?
If you don't run the configure script then it's highly expected that everything is going to go wrong.

**Comment by postylem** [comment]
Thanks for the support response. I'm sorry, I am running the dev version yes! 
I did run the config script but only once, after cloning the first time, not after every pull.
I think that's the intended method, right?

In any case, it is fixed now. What I did was I checked out an earlier commit with 
```bash
git checkout -b olderTMP 5d1a873
quarto check
```
and then quarto check rolled back to an older version of deno ("Quarto required reconfiguration to install Deno. Had v1.41.0, needed v1.33.4.").   After that quarto check ran fine. Curious, I just immediately switched back to main
```bash
git checkout main
quarto check
```
and now quarto check reinstalled the latest deno ("Quarto required reconfiguration to install Deno. Had v1.33.4, needed v1.41.0. Please try command again.")  Retrying quarto check, it ran fine.

**Comment by mcanouil** [comment]
The configure script configure Quarto CLI, not the development environment.
If you change the codebase no matter how, you need to rebuild Quarto CLI.

I would strongly suggest you use the builds assets at https://quarto.org/docs/get-started/
You really should know what you are doing and how if you use the development version which can basically break at each commits.

**Comment by postylem** [comment]
I had not changed the codebase. But I should probably switch back to the release version, you're right. Had switched to dev a long time ago to test some changes.

**Comment by cscheid** [comment]
Quarto _should_ detect and rerun `./configure.sh` in these situations, so I'm bit surprised this came up. But, as @mcanouil suggested, it's a good idea to rerun `./configure.sh` or try a clean repo in these cases.

**Comment by mcanouil** [comment]
> I had not changed the codebase.

You actually did by running `git pull` (at least you wrote you did) does change (contrary to `git fetch`) the codebase with all the latest changes you pulled.

**Comment by mcanouil** [comment]
It will avoid future headaches.

You can still run on pre-releases if you'd like to be up to date with a little less risk as with the development version.
