### ISSUE TITLE
Mention that three dashes should not be used in setting `dir/_metadata.yml`

### ISSUE THREAD

**Issue by eliasdabbas** [quarto-dev/quarto-cli#10211]
### What would you like to do?

Give feedback or suggest an improvement

### Description

In [Project Basics](https://quarto.org/docs/projects/quarto-projects.html) the part explaining metadata merging can be improved by mentioning that users shouldn't add `---` in sub-directories as with a regular YAML file. 

<img width="818" alt="Screenshot 2024-07-03 at 2 14 43 PM" src="https://github.com/quarto-dev/quarto-cli/assets/15708966/fa52d6f2-46f4-497d-9825-27daaad3261d">

I had to check an existing Quarto project to figure this out (apologies if this is something I should know about YAML files).

Suggestion: 

Please note that any sub-directory metadata should be included **without** the three dashes used in YAML files, for example: 

`_quarto.yml`:
```yaml
---
format:
  html:
    toc: true
---
```

If you want to set `toc: false` in a sub-directory, you only set this line as follows:

`dir/_metadata.yml`

```yaml
toc: false
```

**Comment by mcanouil** [comment]
Could you explain what is the issue?
`---` is perfectly valid YAML.

Here it seems you are confusing a markdown based document with a YAML block inside (delimited by two `---`) and a YAML configuration file.

**Comment by eliasdabbas** [comment]
Thanks @mcanouil 
Your example is for a qmd file.

Mine is about a `_metadata.yml` file that overrides the project `_quarto.yml` file. 

Here is my configuration: 

<img width="872" alt="Screenshot 2024-07-03 at 2 32 51 PM" src="https://github.com/quarto-dev/quarto-cli/assets/15708966/cdfb9f98-3e59-4b45-b1b9-c4e96eb6a35c">


When I run this I get this error: 

```bash
Preparing to preview
ERROR: YAMLException: expected a single document in the stream, but found more

Stack trace:
    at load$1 (file:///Applications/quarto/bin/quarto.js:17424:11)
    at buildJsYamlAnnotation (file:///Applications/quarto/bin/quarto.js:18196:5)
    at readAnnotatedYamlFromMappedString (file:///Applications/quarto/bin/quarto.js:18096:16)
    at readAndValidateYamlFromMappedString (file:///Applications/quarto/bin/quarto.js:18454:30)
    at readAndValidateYamlFromFile (file:///Applications/quarto/bin/quarto.js:20493:50)
    at directoryMetadataForInputFile (file:///Applications/quarto/bin/quarto.js:40265:32)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async resolveFormats (file:///Applications/quarto/bin/quarto.js:72983:46)
    at async renderContexts (file:///Applications/quarto/bin/quarto.js:72874:21)
    at async Object.renderFormats (file:///Applications/quarto/bin/quarto.js:72918:22)
```

Removing the three dashes from the `_metadata.yml` file fixes this. Or am I missing something?

**Comment by mcanouil** [comment]
Also note that:

```yaml
format:
  html:
    toc: true
```

Means you want a table of content but only for `html` format.

```yaml
toc: false
```

Means you want to disable table of content for all formats.

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/6e0384bf-1d67-43b3-ac2c-a8be6905e0ca">

**Comment by mcanouil** [comment]
> Thanks @mcanouil Your example is for a qmd file.
> 
> Mine is about a `_metadata.yml` file that overrides the project `_quarto.yml` file.
> 
> Here is my configuration:
> 
> <img alt="Screenshot 2024-07-03 at 2 32 51 PM" width="872" src="https://private-user-images.githubusercontent.com/15708966/345404642-cdfb9f98-3e59-4b45-b1b9-c4e96eb6a35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDcwMTQsIm5iZiI6MTcyMDAwNjcxNCwicGF0aCI6Ii8xNTcwODk2Ni8zNDU0MDQ2NDItY2RmYjlmOTgtM2U1OS00YjQ1LWIxYjktYzRlOTZlYjZhMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDExMzgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MzlhNGE4MTI3YjdiM2VmOTU5OWJmMmRkMjRiMTFkMDk4Y2FlMDJlMjYxNDFmNGJkNGU5ZjcwOGQwMzIwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oj2iJDjIiVRq6FqIuS3VgawoOx0zlti5SuHA26Zb5GM">
> When I run this I get this error:
> 
> ```shell
> Preparing to preview
> ERROR: YAMLException: expected a single document in the stream, but found more
> 
> Stack trace:
>     at load$1 (file:///Applications/quarto/bin/quarto.js:17424:11)
>     at buildJsYamlAnnotation (file:///Applications/quarto/bin/quarto.js:18196:5)
>     at readAnnotatedYamlFromMappedString (file:///Applications/quarto/bin/quarto.js:18096:16)
>     at readAndValidateYamlFromMappedString (file:///Applications/quarto/bin/quarto.js:18454:30)
>     at readAndValidateYamlFromFile (file:///Applications/quarto/bin/quarto.js:20493:50)
>     at directoryMetadataForInputFile (file:///Applications/quarto/bin/quarto.js:40265:32)
>     at eventLoopTick (ext:core/01_core.js:153:7)
>     at async resolveFormats (file:///Applications/quarto/bin/quarto.js:72983:46)
>     at async renderContexts (file:///Applications/quarto/bin/quarto.js:72874:21)
>     at async Object.renderFormats (file:///Applications/quarto/bin/quarto.js:72918:22)
> ```
> 
> Removing the three dashes from the `_metadata.yml` file fixes this. Or am I missing something?

You wrote invalid YAML: https://yaml.org/spec/1.2.2/
See for yourself: https://yamlchecker.com/

`---` has a meaning in YAML (so it is valid and there is no reason to forbid something valid) which is not Pandoc meaning inside a markdown document.

**Comment by eliasdabbas** [comment]
@mcanouil You're right. 

YAML files don't contain `---` anyways, this is just for qmd docs.

I think I mixed these two. Thanks a lot!

**Comment by mcanouil** [comment]
YAML file can contain `---`, see "2.2. Structures" of https://yaml.org/spec/1.2.2/
