### ISSUE TITLE
Mermaid in gfm turned into PNG

### ISSUE THREAD

**Issue by rcannood** [quarto-dev/quarto-cli#1021]
I just noticed how the latest build(s) of quarto renders mermaid diagrams as png images instead of the natively supported ` ``` mermaid ` blocks when using the gfm format. This feature appears to have been removed in c4af1a1bed2cf448cb4e10d0d0dcae246a8c0b5e.

This breaks several mermaid functionalities, such as being able to use nodes in the diagram to link to other sections in the document -- shown in Figures 1 and 2.

Why was this feature removed in c4af1a1bed2cf448cb4e10d0d0dcae246a8c0b5e? Can it be parameterised so I have the option of not turning it into a PNG? Or at least allow me to turn it into an SVG?

Kind regards,
Robrecht

---

Example:

<div class="column-page">

<div id="fig-architecture">

<p>

``` mermaid

flowchart LR
  Raw[Raw\nreads]
  Counts[Raw\ncounts]
  SS[Unimodal\nsample]
  MS[Unimodal\nmulti-sample]
  MM[Multi-modal\nmulti-sample]
  Ingestion[/Ingestion/]
  Preproc1[/Single-sample\nprocessing/]
  Preproc2[/Multi-sample\nprocessing/]
  Integration[/Integration/]

  Raw --- Ingestion --> Counts --- Preproc1 --> SS --- Preproc2 --> MS --- Integration --> MM

  Ingestion -.-|"- Demux.\n- Mapping"| Ingestion
  Preproc1 -.-|"- Count QC\n- Doublet calling\n- Ambient RNA\n- Gatekeeper"| Preproc1
  Preproc2 -.-|"- Normalisation\n- Feature filtering\n- Feature selection\n- Batch correction?\n- Dim. red.?"| Preproc2
  Integration -.-|"- Dim. red.\n- Data integration"| Integration

  linkStyle 8,9,10,11 stroke:#fff,stroke-width:0px,text-align:left;

  click Ingestion "https://github.com/openpipelines-bio/openpipeline/blob/e1d4e6675f46e10805fc9f5bbc47917e3c16ea64/docs/design.md#ingestion"

```

</p>

Figure 1: Before commit c4af1a1bed2cf448cb4e10d0d0dcae246a8c0b5e. Notice how clicking the 'Ingestion' box takes you to the section documenting the 'Ingestion' pipeline.

</div>

</div>

<div class="column-page">

<div id="fig-architecture">

<p>

<img src="https://raw.githubusercontent.com/openpipelines-bio/openpipeline/e1d4e6675f46e10805fc9f5bbc47917e3c16ea64/docs/design_files/figure-gfm/mermaid-figure-1.png" data-fig-pos="H"
style="width:13.97803in;height:2in" />

</p>

Figure 2: After commit c4af1a1bed2cf448cb4e10d0d0dcae246a8c0b5e. This PNG does not integrate well with a dark themed github and does not allow for linking to other pages.

</div>

</div>

**Comment by jjallaire** [comment]
We removed it because `gfm` is often used as a shorthand for markdown parsers w/ the standard gfm extensions but NOT being published on Github itself. Since the special mermaid behavior applies to on the GitHub service (and I believe GitLab as well) we didn't want to produce markdown by default that didn't render correctly in other environments.

All of that said we could definitely bring this behavior back as an option. We could also consider SVG rather than PNG (would  that fix the dark themed issue?). @cscheid What do you think?

**Comment by mcanouil** [comment]
To note, GitHub/Mermaid choose the diagram theme based on user defined theme when rendering the diagram.
So for images (SVG/PNG) on GitHub, the "context" is required.
https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/
This means, the device background have to be define and possibly, two versions of the image have to be generated to achieve the GitHub/Mermaid behaviour using static images.

**Comment by cscheid** [comment]
This should be fixed as of the latest checkin, with control over the generation as @jjallaire suggested above. Let us know if it still doesn't work for you.

**Comment by rcannood** [comment]
Thanks @cscheid! :bow: I can confirm that this issue has been fixed.

**Comment by windperson** [comment]
> mermaid-dev: null | svg | png

Hi @rcannood ,

May I ask how to "Not" render mermaid in YAML declaration part in .qmd files?

I try 

---
lang: zh
format:
  gfm:
    wrap: preserve
    mermaid-dev: null
---

But it still result in linking to a generated png file instead of preserve mermaid code block.
