### ISSUE TITLE
Add link to changelog entries for each version

### ISSUE THREAD

**Issue by coatless** [quarto-dev/quarto-cli#10227]
### What would you like to do?

Give feedback or suggest an improvement

### Description

If the Quarto version is either release or pre-release, the release notes are shown under the installer table on the Download page. However, there is no link to a permanent location for the release notes. So, once a new version comes out, we need to specify the changelog.md included as part of the source of this repository for a permanent page.

The ask: 

1. Please add permanent links to the release note page
2. Consider placing pre-release highlights as a permanent entry

## Old release

The old release table only links to the top-level tag. Depending on the tag, it's either the last commit message (1 - 1.3) or the new here's the difference between a smaller version delta and a link to the full release notes (starting at 1.4)

<img width="1291" alt="A screenshot of the old release table" src="https://github.com/quarto-dev/quarto-cli/assets/833642/b5a952e9-6000-402b-abcf-340e189e41de">

## Pre-release 

Immediately proceeding the installer table, there is a link to the release highlights post that describes the top-level features for the release. 

<img width="1293" alt="Screenshot 2024-07-04 at 9 50 51 AM" src="https://github.com/quarto-dev/quarto-cli/assets/833642/dd30ee63-6779-46fd-97fe-b8167c473608">

<img width="1297" alt="Screenshot 2024-07-04 at 9 50 40 AM" src="https://github.com/quarto-dev/quarto-cli/assets/833642/166a1c29-ae97-419d-aa56-a8e4a1b9843f">

**Comment by mcanouil** [comment]
FYI:
If you go to the "older releases" tab, you get the releases links.
Starting in 1.4, the `changelog.md` link was added in the release description.
For all releases, the change log is part of the assets.

**Comment by mcanouil** [comment]
> Consider placing pre-release highlights as a permanent entry

I am not sure what you mean exactly here.
Note that now, pre-release specific documentation updates are published in https://prerelease.quarto.org/

**Comment by mcanouil** [comment]
Would adding the changelog.md links to the release table work?

**Comment by cwickham** [comment]
> Consider placing pre-release highlights as a permanent entry

As @mcanouil said, current pre-release highlights now live on https://prerelease.quarto.org (e.g. https://prerelease.quarto.org/docs/prerelease/1.6/ ). Once released, these pages move to quarto.org (e.g. for 1.5, https://quarto.org/docs/prerelease/1.5/).

> Please add permanent links to the release note page

We have an open issue for this https://github.com/quarto-dev/quarto-cli/issues/5396.

**Comment by cwickham** [comment]
We now have links to the release notes in the Older Releases table at https://quarto.org/docs/download/

In general, you'll find the release notes at `https://quarto.org/docs/download/changelog/1.x/`. The current (https://quarto.org/docs/download/changelog/1.5/) and prerelease (https://quarto.org/docs/download/changelog/1.6/) versions are just aliases to the download pages - this means they are automatically up to date with the current patch version. They'll transition to frozen pages on release.
