### ISSUE TITLE
Including image-files via `knitr::include_graphics()` errors out if image-path is relative to project-root, but document-location is not at root

### ISSUE THREAD

**Issue by Gewerd-Strauss** [quarto-dev/quarto-cli#10232]
### Bug description

Hello,

I have opened this as a discussion in #10226 yesterday. After a bit more deliberation, I think this behaviour warrants an actual issue, and here we are.

Assume I have a website-project, with the following structure:

```
assets\
	obsidian-assets\
		photobox_overview_gfa_coords.jpg
experiments\
	about.qmd
.gitignore
about.qmd
index.qmd
README
styles.css
_quarto.yml

```

You will notice that there are two `about.qmd` - these files are identical besides their location.

Both files contain the following content:

``````qmd
---
title: "About"
---

```{r}
#| warning: false
#| out-width: "100%"
c <- "assets/obsidian-assets/photobox_overview_gfa_coords.jpg" # works
knitr::include_graphics(c)
```
``````

If I try and render the root-level file to html and pdf via `quarto render about.qmd`, the `knitr` finds the image properly, and embeds it in both formats.

If I repeat the same for the nested `experiments/about.qmd`, compilation fails:

## PDF

Executing `quarto render experiments/ --to pdf` emits the following error:

```
[...]
ERROR:
compilation failed- error
Unable to load picture or PDF file 'assets/obsidian-assets/photobox_overview_gfa_coords.jpg'.
<to be read again>
                   }
l.216 ...-assets/photobox_overview_gfa_coords.jpg}


see D:\Dokumente neu\Repositories\quarto-issues\quarto-cli-10226\experiments\about.log for more information.
```

## HTML

Executing `quarto render experiments/ --to pdf` results in apparently successful compilation.
Unfortunately the image itself is not actually embedded: 
![grafik](https://github.com/quarto-dev/quarto-cli/assets/80548781/40f9e972-142f-4faa-9a2a-7efcf07204f3)

Contrary to that, when I target the root-level file `file.qmd`, it converts successfully to both html and pdf:

![grafik](https://github.com/quarto-dev/quarto-cli/assets/80548781/0c9971ca-95d8-490e-a86a-4783b62caa17)

---
---

To my understanding, with the config-setting `execute-dir: project`, paths should be reconstructed from the project's root-level. I don't understand

- why a file nested in another folder does not find `<root>/assets/obsidian-assets/photobox_overview_gfa_coords.jpg`, nor
- how I can rectify this issue.

Can someone help me make sense of this?

Thank you.
Sincerely,  
~Gw

---
---

Project yaml:

```yaml
project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
  - "*.qmd"

website:
  title: "quarto-cli-10226"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about at root
      - href: experiments/about.qmd
        text: about at subfolder

format:
  html:
    toc: true
  pdf:
    toc: true
```

The logfile contains:

```txt
LaTeX Warning: File `assets/obsidian-assets/photobox_overview_gfa_coords.jpg' not found on input line 224.

! Unable to load picture or PDF file 'assets/obsidian-assets/photobox_overview_gfa_coords.jpg'.
```

I am running quarto v.1.5.52.

### Steps to reproduce

A reprex for this issue can be found at https://github.com/Gewerd-Strauss/quarto-cli-10226. Refer to its readme for reproduction steps.

### Expected behavior

From my understanding of the [docs](https://quarto.org/docs/projects/code-execution.html#working-dir), setting the config-option `execute-dir: project` should result in code being executed at the project's root. 
In that case, the r-code of a nested file under `/experiments` being executed with a working directory set to project-root should be able to find the asset-file the same way as a root-level document.

### Actual behavior

For code-cells embedded in documents which are not at project-root-level, the relative path to the asset-file is not resolved, and the code itself will thus error out.

### Your environment

SystemOS : 				10.0.22631 64-bit  v10.0.22631 

### Quarto check output

```bash
$ quarto check | clip
Quarto 1.5.52
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.52
      Path: D:\CLI\quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.02
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\ProgramData\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: C:/Users/redacted Main/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.4.0
      Path: D:/CLI/r/R-4.4.0
      LibPaths:
        - D:/CLI/r/R-4.4.0/library
      knitr: 1.46
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report.

We kindly ask for your cooperation in our issue resolution process. Please allow us the opportunity to review your initial report before opening additional discussions or issues. Often, the matter may involve complex factors that require comprehensive analysis on both Quarto CLI and `knitr`.
Initiating multiple threads can inadvertently expand the workload and complicate the investigation. We greatly value your contributions and would appreciate it if you could continue the conversation within your original thread in the future. This will enable us to conduct a thorough investigation and determine the appropriate next steps.
Thank you for your understanding and support.

**Comment by Gewerd-Strauss** [comment]
> We kindly ask for your cooperation in our issue resolution process. Please allow us the opportunity to review your initial report before opening additional discussions or issues. [...] Initiating multiple threads can inadvertently expand the workload and complicate the investigation. 

I decided to open the issue as I was under the impression that `Discussions` are not the place to report such things, and thus I duplicated it into an issue. 

However, I understand the rationale provided against this process. For future cases, I will refrain from doing so and keep it in a single place.

Should we thus close this issue in favour of the discussion-thread at #10226?

**Comment by cderv** [comment]
> To my understanding, with the config-setting execute-dir: project, paths should be reconstructed from the project's root-level.

The settings means that R code are executing with a working directory being the project. `knitr::include_graphics()` won't modify the relative path you are passing to it - this knitr function is not dependant of the `root.dir`. 

So the intermediates .md file will contain this file path for both your document
````markdown
![](assets/obsidian-assets/photobox_overview_gfa_coords.jpg){width=100%}
````

Which is the wrong path in the case of `experiments/about.qmd`. 

This is a problem in usage with `knitr::include_graphics` (and possibly also an issue in how path is computed in Quarto context). Maybe related to 
- https://github.com/yihui/knitr/issues/2171

You need to switch to a way of specifying your content  path based correct relative path or using absolute path. 

About your question: 
> why a file nested in another folder does not find <root>/assets/obsidian-assets/photobox_overview_gfa_coords.jpg

This is not the path where the image is looked. The markdown I shared above (obtain with `keep-md: true) shows that. Also, If you open `_site/experiments/about.html` for example, you will see that image is 
````html
<figure class="figure">
<p><img src="assets/obsidian-assets/photobox_overview_gfa_coords.jpg" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
````

So this means `<root>/experiments/assets/obsidian-assets/photobox_overview_gfa_coords.jpg` - this is how relative path work in HTML. 

Hope this clarifies.

You could also leverage Quarto feature for root-project path. 

````markdown

```{r}
#| warning: false
#| out-width: "100%"
c <- "/assets/obsidian-assets/photobox_overview_gfa_coords.jpg" # works
knitr::include_graphics(c, rel_path = FALSE, error = FALSE)
```
````

(`rel_path` is required to avoid any transformation, and `error = FALSE` too as the path does not really exists are computation time - see the doc of the R function for more details and options name to customize globally)

This will create 
````markdown
![](/assets/obsidian-assets/photobox_overview_gfa_coords.jpg){width=100%}
````

Using link starting with `/` for resources in Quarto usually means a path from project root. 

Though this will correct render to 
```html
<figure class="figure">
<p><img src="..\assets/obsidian-assets/photobox_overview_gfa_coords.jpg" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
```

Hope this helps.

**Comment by Gewerd-Strauss** [comment]
> Hope this helps.

Huh. Thank you for the explanation, it did indeed help and resolves this issue for me, as far as I am

**Comment by Gewerd-Strauss** [comment]
> Hope this helps.

Huh. Thank you for the explanation, it did indeed help and resolves this issue for me. It works in tests, it works in a real project structure.

This issue can be closed on my end.
