### ISSUE TITLE
Get Started Tutorial 'hello.qmd' file line 23

### ISSUE THREAD

**Issue by tracy-pollard** [quarto-dev/quarto-cli#10323]
### What would you like to do?

Report an issue on quarto.org

### Description

The downloaded file has `{r} nrow(penguins)` which doesn't give the number on rendered file. Should it be `r now(penguins)` instead?

**Comment by cderv** [comment]
> ` {r} nrow(penguins)`

This is valid syntax in Quarto for **knitr** engine. See https://quarto.org/docs/computations/inline-code.html

> doesn't give the number on rendered file. 

The .qmd has 
```` markdown
package contains size measurements for `{r} nrow(penguins)` penguins from three species observed on three islands in the Palmer Archipelago, Antarctica.
````
and I get correct rendering in html
![image](https://github.com/user-attachments/assets/d850ede9-ebbc-43e4-b9dd-eaa806f4048e)

So not sure what you mean here. I used the doc at https://quarto.org/docs/get-started/hello/rstudio.html

Did you get it another place ?

**Comment by tracy-pollard** [comment]
Thanks for replying. I redownloaded the file and retried and it works now as you say. Thanks!
