### ISSUE TITLE
With section-divs disabled, section divs are rendered when wrapped in a div

### ISSUE THREAD

**Issue by sidneygijzen** [quarto-dev/quarto-cli#10338]
### Bug description

Disabling the `section-divs` only seems to work when not wrapping the header in a div. Once the header is wrapped in a div, the section div reappear. 

I would like to disable section divs so I can apply CSS classes to a header. However when the section divs are rendered, the header classes are copied automatically (by Pandoc) to the parent section.

### Steps to reproduce

`index.qmd`:
````qmd
---
title: "Quarto test"
---

# This a header without a section div.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

::: {.a-css-class}
# This header has a section div. {.h2}

This paragraph is now formatted as an h2.
:::
````

`_quarto.yml`:
```
project:
  type: website

website:
  title: "Quarto test"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    minimal: true
    page-layout: custom
    theme: styles.scss
    section-divs: false
```

### Expected behavior

 I would expect that no section divs are rendered, even if the header is wrapped in a div.

### Actual behavior

If a header is wrapped in a div, the HTML section div reappears.

### Your environment

Kubuntu 22.04 and VSCode. However, I am running `quarto preview` directly from the terminal.

### Quarto check output

```bash
Quarto 1.5.55
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.55
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 4.9.1
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 19, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```

**Comment by cscheid** [comment]
This isn't a bug.

With `section-divs: false`, you're asking pandoc to create `<section>` elements instead of section divs. In this setting, Pandoc takes the classes you've added to your header to be the classes you want to add to the section (otherwise, where would they go?). You get this:

<img width="769" alt="image" src="https://github.com/user-attachments/assets/e72b85ef-bb5e-4cd4-a285-5ce059644382">

You've asked for `.h2` class in your section, and so the contents are getting rendered in the style of `H2` elements.
