### ISSUE TITLE
Math in dashboard card titles ignores position in title

### ISSUE THREAD

**Issue by e-miz** [quarto-dev/quarto-cli#10340]
### Bug description

Last dashboard issue today, I promise!

![image](https://github.com/user-attachments/assets/35010207-b8d4-4045-b6b3-52162aca17d3)

Inline math in a dashboard card title seems to come after all words in the title.

Inspecting the output shows something's probably gone wrong with the placement of the inline math div:

![image](https://github.com/user-attachments/assets/59af7abd-5119-41ce-b222-3e849a4347b8)

I'm not actually sure how to come up with a workaround for this one, but I can also probably live without math in my card titles.

### Steps to reproduce

```qmd
---
title: "Test Dashboard"
format: dashboard
---

##
::: {.card title="Math $y=mx+b$ between words"}

Math $y=mx+b$ between words

:::
```

### Your environment

IDE: VSCode 1.91.1
OS: Windows 10 WSL2

### Quarto check output

```bash
Quarto 1.5.55
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.55
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.10
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/emiz/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.7 (Conda)
      Path: /home/emiz/miniconda3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
What if you try without the attribute syntax?

```md
::: {.card}
## Math $y=mx+b$ between words

Math $y=mx+b$ between words
:::
```

**Comment by cscheid** [comment]
(incidentally, please keep the issues coming!)

**Comment by cscheid** [comment]
> What if you try without the attribute syntax?
> 
> ```
> ::: {.card}
> ## Math $y=mx+b$ between words
> 
> Math $y=mx+b$ between words
> :::
> ```

This doesn't work even without math, Quarto doesn't turn the heading into a title:

<img width="891" alt="image" src="https://github.com/user-attachments/assets/4d5a3b44-6cb5-4734-80b1-c837f3cddca2">

**Comment by mcanouil** [comment]
Seems inconsistent compared to other div features.
I would have swear it was a thing 😅

**Comment by cscheid** [comment]
> Seems inconsistent compared to other div features such as call-outs.

Agreed.

**Comment by cscheid** [comment]
It's the processing here that's broken:

https://github.com/quarto-dev/quarto-cli/blob/3fd660eb4af7d0352fb4314d9f467163d9868c2f/src/format/dashboard/format-dashboard-card.ts#L155-L180

We need to move more than just "loose text".

**Comment by cscheid** [comment]
Concretely, the problem is not just with math. Any formatted text breaks in the same way, like `*emphasis*`, etc.
