### ISSUE TITLE
pagetitle not being honored in <title> render

### ISSUE THREAD

**Issue by hodgesmr** [quarto-dev/quarto-cli#10342]
### Bug description

The `pagetitle` variable is not being honored on article pages in the html `<title>` tag.

### Steps to reproduce

```qmd
---
author: "Firstname Lastname"
reading-time: true
title: "The Article Title"
pagetitle: "The Article Title"
subtitle: "I'm testing whether this works"
date: 2024-07-20
---

Test body copy
```

### Expected behavior

I expected `<title>The Article Title</title>` (without the suffix `– Website Title`)

### Actual behavior

but I got `<title>The Article Title – Website Title</title>`

<img width="1469" alt="Screenshot 2024-07-20 at 3 58 32 PM" src="https://github.com/user-attachments/assets/78ed2e48-1446-430d-b212-7ab2b1c9105d">

### Your environment

macOS Sonoma 14.5
```sh
quarto --version
1.5.55
```

### Quarto check output

```bash
Quarto 1.5.55
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.55
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /Users/hodgesmr/.pyenv/versions/3.11.2/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
`pagetitle` is being honoured.
Try with something that is not the same thing as the title.

If you don't want the suffix (which was in Quarto <1.5 a prefix), set `title-prefix`.

By the way your example is not reproducible as you implied it is for single HTML document.
Single HTML document does not use `title-prefix`.
See <https://quarto.org/docs/reference/formats/html.html#metadata>.

<table>
<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
title: "Quarto Playground"
pagetitle: "Whatever"
format: html
---

This is a playground for Quarto.

{{< lipsum 1 >}}

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

````

</td><td>

<img width="877" alt="image" src="https://github.com/user-attachments/assets/c980383a-59b7-4df7-867f-dd74cf8084ea">

</td></tr>
</table>

1. Create a website
```sh
quarto create project website issue10342 Issue-10342
```
2. edit `index.qmd`

```qmd
---
title: "Index"
pagetitle: "Welcome to the Quarto website"
title-prefix: ""
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
```

**Comment by hodgesmr** [comment]
Thank you for directing me to `title-prefix: ""`. That seems to achieve what I'm looking for.
