### ISSUE TITLE
Lua filter error with gfm for a crossref figure 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#10358]
The following example throws an error on quarto 1.5.54

<pre>
---
title: "Minimal example"
format: gfm
---

```{python}
#| label: fig-sin
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0,1,10)
y = np.sin(x)

plt.plot(x,y)
```
</pre>

The error is the following:

```
Error running filter /home/opt/quarto-1.5.54/share/filters/main.lua:
Block, list of Blocks, or compatible element expected, got table
        while retrieving function argument blocks
        while retrieving arguments for function Blocks
stack traceback:
        /home/opt/quarto-1.5.54/share/filters/main.lua:22460: in field 'render'
        /home/opt/quarto-1.5.54/share/filters/main.lua:1233: in local 'filter_fn'
        /home/opt/quarto-1.5.54/share/filters/main.lua:635: in function </home/opt/quarto-1.5.54/share/filters/main.lua:625>
        (...tail calls...)
        [C]: in ?
        [C]: in method 'walk'
        /home/opt/quarto-1.5.54/share/filters/main.lua:557: in function </home/opt/quarto-1.5.54/share/filters/main.lua:546>
        (...tail calls...)
        /home/opt/quarto-1.5.54/share/filters/main.lua:1334: in local 'callback'
        /home/opt/quarto-1.5.54/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
        /home/opt/quarto-1.5.54/share/filters/main.lua:1388: in function </home/opt/quarto-1.5.54/share/filters/main.lua:1385>
stack traceback:
        /home/opt/quarto-1.5.54/share/filters/main.lua:557: in function </home/opt/quarto-1.5.54/share/filters/main.lua:546>
        (...tail calls...)
        /home/opt/quarto-1.5.54/share/filters/main.lua:1334: in local 'callback'
        /home/opt/quarto-1.5.54/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
        /home/opt/quarto-1.5.54/share/filters/main.lua:1388: in function </home/opt/quarto-1.5.54/share/filters/main.lua:1385>
```

It sounds like it has something to do with the `gfm` output format, it works correctly if I render to html. The first time I encountered this bug I was rendering my project to both gfm and html, and changing that to just render html works as expected. I was using gfm because it gives a nice preview on GitHub.

_Originally posted by @mbellitti in https://github.com/quarto-dev/quarto-cli/discussions/9334#discussioncomment-10120331_

**Comment by cderv** [comment]
@cscheid I think this is a required follow up on 

- https://github.com/quarto-dev/quarto-cli/pull/10198 

https://github.com/quarto-dev/quarto-cli/blob/0d87b08a5c1b25ec6c6573e0bed793cd67eb6687/src/resources/filters/customnodes/floatreftarget.lua#L1041-L1057

We probably need to deal with `float.caption_long` the same way everywhere. 

I see addition local to lightbox - should have a new helper to use everywhere ? 
https://github.com/quarto-dev/quarto-cli/blob/0d87b08a5c1b25ec6c6573e0bed793cd67eb6687/src/resources/filters/layout/lightbox.lua#L142-L148

Also sometimes, it seems with use `pandoc.Inlines({})` as default 
https://github.com/quarto-dev/quarto-cli/blob/0d87b08a5c1b25ec6c6573e0bed793cd67eb6687/src/resources/filters/customnodes/floatreftarget.lua#L205

And other time `pandoc.Div({})`, which then handle `float.caption_long.content` correctly. So not the same everywhere. 

Anyhow, handling a default works, 
````diff
diff --git a/src/resources/filters/customnodes/floatreftarget.lua b/src/resources/filters/customnodes/floatreftarget.lua
index 913e7e5fc..6eb085535 100644
--- a/src/resources/filters/customnodes/floatreftarget.lua
+++ b/src/resources/filters/customnodes/floatreftarget.lua
@@ -1037,11 +1037,11 @@ end, function(float)
 
   local open_block = pandoc.RawBlock("markdown", "<div id=\"" .. float.identifier .. "\">\n")
   local close_block = pandoc.RawBlock("markdown", "\n</div>")

   if caption_location == "top" then
     return pandoc.Blocks({
       open_block,
-      float.caption_long,
+      float.caption_long or pandoc.Div({}),
       float.content,
       close_block
     })
@@ -1050,7 +1050,7 @@ end, function(float)
       open_block,
       float.content,
       pandoc.RawBlock("markdown", "\n"),
-      float.caption_long,
+      float.caption_long or pandoc.Div({}),
       close_block
     })
   end
````

but I am thinking maybe we should be sure to handle this everywhere needed. So assigning to you as you know better each part of FloatRefTarget

**Comment by cscheid** [comment]
The root cause of this is the upgrade to Pandoc where accessing the nodes no longer creates empty content. The fix is easy and I'll backport.
