### ISSUE TITLE
Using `prompt/comment/collapse` in an R chunk not working as in Rmarkdown

### ISSUE THREAD

**Issue by ltierney** [quarto-dev/quarto-cli#1035]
Using the `prompt/comment/collapse` options in an R chunk to simulate a CLI interaction does not seem to work. The `prompt` and `comment` options seem to be ignored. This file illustrates the issue:

````
---
execute:
  echo: true
---

```{r, prompt = TRUE, comment = "", collapse = TRUE}
1 + 2
```

```{r}
#| collapse: true
#| prompt: true
#| comment: ""
1 + 2
```
````

**Comment by jjallaire** [comment]
That is very surprising! Currently knitr is handling all of the option parsing for Quarto as AFAIK all the codepaths are the same as for R Markdown. @cderv I know that Yihui is OOF right now and it would be good to run this down before our v1.0 release. Could you take a look at this issue as well as the possibly related https://github.com/quarto-dev/quarto-cli/issues/1034? @yihui and I were also looking at this issue (https://github.com/quarto-dev/quarto-cli/discussions/1005) which could also be related.

**Comment by rcannood** [comment]
@tverbeiren and I struggled with this briefly as well.

---

The following is a small reproducible example:


````markdown
---
title: Foo
---


```{r setup, include = FALSE}
# set default chunk options
knitr::opts_chunk$set(
  echo = TRUE,
  comment = "",
  collapse = TRUE,
  prompt = TRUE
)
```

```{r}
print("Hello world!")
```
````

Command:
```R
library(rmarkdown)
render("test.Rmd", format = md_document())
```

This yields the expected results:
```markdown
    > print("Hello world!")
    [1] "Hello world!"
```

---

Rendering the same component with quarto yields a different output:

````markdown
---
title: Foo
toc-title: Table of contents
---

::: cell
``` {.r .cell-code}
print("Hello world!")
## [1] "Hello world!"
```
:::
````

While the code block was collapsed correctly, the prompt and the comment chunk options were removed.

---


If I move the cluck options inside the header, it becomes more obvious what happens:

````markdown
---
title: Foo
knitr:
  opts_chunk: 
    echo: true
    collapse: true
    comment: "" 
    prompt: true
---

```{r}
print("Hello world!")
```
````

Results in:
````markdown
---
knitr:
  opts_chunk:
    collapse: true
    echo: true
    prompt: true
title: Foo
toc-title: Table of contents
---

::: cell
``` {.r .cell-code}
print("Hello world!")
## [1] "Hello world!"
```
:::
````
---

I think the `nzchar(...)` in [this code](https://github.com/quarto-dev/quarto-cli/blob/94612d2b8bb046823e488116d3a214c72c6f7a8b/src/resources/rmd/hooks.R#L99-L101) results in the `""` being replaced with `"##"`. I'm not sure why the `prompt` is being picked up.

**Comment by cderv** [comment]
Regarding `comment`, you're right that it is realted `collapse` is working fine in my test, but is indeed related to `comment` issue. We should remove this `nzchar` test. PR incoming (I'll took the opportunity to add tests)

For `prompt`, after looking into it, it is an option that is taken into account in the source hook. Quarto does not delegate at all to **knitr** source hook and rewrites it. That is why it is not taken into account. We need to bring support or delegate more to **knitr** on this front. I'll submit a PR.

**Comment by jjallaire** [comment]
The issue with `knitr::read_chunk()` that @yihui and I were discussing is also fixed with https://github.com/quarto-dev/quarto-cli/commit/a120c2a2ddf17d71447315efb6694237545ccf52
