### ISSUE TITLE
On windows, error while removing quarto-sessions temp dir 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#10368]
I am seeing this 

````
WARN: Error removing file C:\Users\chris\AppData\Local\Temp\quarto-session4dc6ef4c3471c0e7\8e1f6186cca530ee: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus. (os error 32): remove 'C:\Users\chris\AppData\Local\Temp\quarto-session4dc6ef4c3471c0e7\8e1f6186cca530ee'
Output created: index.html

Error occurred with cleanup handlers:Error: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus. (os error 32): remove 'C:\Users\chris\AppData\Local\Temp\quarto-session4dc6ef4c3471c0e7'
````

I decided to look into this, and it happens in 
https://github.com/cderv/quarto-cli/blob/f9d1301be63133210a492a04fa02d22e1a5e5111/src/core/temp.ts#L38-L47

Somehow it is called with `tempContext` being undefined but `tempDir` not empty. And on windows, `Deno.removeSync` throug this error reported by Quarto 
````
Uncaught Error Error: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus. (os error 32): remove 'C:\Users\chris\AppData\Local\Temp\quarto-sessionf7c75ac2832789eb'
    at removeSync (deno_fs/30_fs.js:250:3)
    at eval (repl:1:6)
````

So I thought of some OS locking issue and what I am seeing by looking at what could cause the lockup on windows is 
![image](https://github.com/user-attachments/assets/d6597232-7989-4cbb-acc1-84b114dcf9f7)

The PID is the same as the current `Deno.pid` in debug mode I have. So somehow, some of the content of the quarto session temp directory we use for sass bundling probably is still lock on the files. 

This means the session directory can't be cleanup. And I got a lot of those it seems !! 

````r
> length(fs::dir_ls(Sys.getenv("TEMP"), regexp = "quarto-session.*/.*/sass/.*", recurse = TRUE))
[1] 393
````

So something is not right here... 

I believe it happens only with pre-release, so should be quite recent change

**Comment by cderv** [comment]
Quick test shows it happens in v1.6.2 but no 1.6.1

**Comment by cderv** [comment]
Possibly bad commit is 6796ddfd42c87efbc1648b48125c742f12dd90c1 
- https://github.com/quarto-dev/quarto-cli/pull/10218

This seems relevant considering the filename that are locked with Deno.

**Comment by cderv** [comment]
We probably need to add cleanup with `kv.close()` in 
https://github.com/quarto-dev/quarto-cli/blob/6796ddfd42c87efbc1648b48125c742f12dd90c1/src/core/sass/cache.ts#L195-L207

So we need to deal with the cleanup order because it needs to happen before the Quarto session tempdir cleanup registered almost first at 
https://github.com/quarto-dev/quarto-cli/blob/be2792dd8d0960f1d205aeb62fa3544ec956e6d3/src/quarto.ts#L149-L150

**Comment by cscheid** [comment]
Thank you for finding this! My reason to move to Deno.KV was to have fewer issues like this (previously two separate quarto processes could write to the filesystem at the same time and corrupt the json index) :(
