### ISSUE TITLE
Can't render Python script

### ISSUE THREAD

**Issue by mjkrasny** [quarto-dev/quarto-cli#10366]
### Bug description

while following the guide from: https://quarto.org/docs/computations/render-scripts.html#syntax

The rendered document is not executing included python script.
The output looks like in the screenshot attached.
![image](https://github.com/user-attachments/assets/7c84b48b-a89f-4069-87db-3c85f046f691)

### Steps to reproduce

# Python Script file (script.py)

````python
# %% [markdown]
# Test external script

# %%
#| echo: true
x = 35

print (x)
# %% [markdown]
"""
## Exploring the data
...
"""
````

Quarto document (document.qmd)
````qmd
---
title: "Test-document"
author: "XX YY"
execute:
    enabled: true
    echo: true
    python: true
---


{{< include script.py >}}

````

I have fresh quarto install: 1.5.55

### Expected behavior

Expected nice quarto document, with python code executed.

### Actual behavior

Rendered document contains markdown and python syntax, python code is not executed.

### Your environment

- IDE: VSCode (but I don't think it matters)
- Quarto version 1.5.55

### Quarto check output

PS C:\Users\---------------> quarto check
Quarto 1.5.55
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.55
      Path: C:\Users\----------------------------
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.9 (Conda)
      Path: C:/Users/----------------------------
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by cderv** [comment]
The Script rendering in Quarto means you can do `quarto render script.py`

If you want to include python code into a .qmd document, you need to use computation cell with the right syntax. 
https://quarto.org/docs/computations/python.html

Here by using `include` shortcode, you are just "copy pasting" the content of the script.py as a text file into the .qmd body. It won't be executed because there is not python cell in the .qmd

Hope this helps understand.

**Comment by mjkrasny** [comment]
OK. all clear now. Thanks. Running the 'quarto render script.py' works fine.

But is there a way to combine/include more than one python scripts in the one *.qmd document?

Thanks.

**Comment by mjkrasny** [comment]
Ok, I found what I need/want. It is called embed: https://quarto.org/docs/authoring/notebook-embed.html

However it is only limited to other *.qmd files or Jupyter Notebooks. Is there any chance to embed python script file instead of jupyter notebook?

Just as general use case is that I'm working on a report where the main text is kept in the main.qmd file, but all computations and plotting is done in python scripts. Using Spyder IDE is much more convenient (to me) than any other tool to explore and play with data, but the final outcome from the scripts (i.e. plots) should go to the main document. I hope it makes sense?

**Comment by cderv** [comment]
> Is there any chance to embed python script file instead of jupyter notebook?

`embed` feature works by rendering notebook and retrieving code cells output in there.  So even if we make it possibly for a Jupyter percent script version, it will render top ipynb first. 

>  I hope it makes sense?

I understand the usage. **knitr** engine allows such things by allowing storing code in script and loading them in cell specially 
Either [reading a sciprt as a cell content](https://bookdown.org/yihui/rmarkdown-cookbook/option-code.html) or [reading code cells from a script content](https://bookdown.org/yihui/rmarkdown-cookbook/read-chunk.html). But those are knitr engine specific, and Jupyter does not allow such use case. 

For now, `include` and `embed` shortcode are the closest to this. Using `.py` in embed is not supported yet - as we can convert those to Jupyter notebook, I wonder if we could activate it. I'll open an issue to track this idea.

**Comment by mjkrasny** [comment]
Ok. I'm trying to work around using jupyter notebooks rendered from scripts with the use of Jupytext.
The issue I'm facing is that after creation of _script.ipynb_ file I must manually run cells in the noteboook before rendering my document.qmd file.

Is there a way to render the notebook each time at document render?
the "_execute: enabled: true_" in yaml doesn't work.

my working example:

``` qmd

---
title: Test - embedded jupyter
author: XXX YYY
toc: true
execute: 
  enabled: true
  echo: false
format:
  html:
    code-fold: true
---

# Example Heading 1
Here is some text

more text

## Include full notebook
now include python script: script.py, which is translated to jupyter by jupytex

{{< embed script.ipynb >}}


## Embed specific cell
{{< embed script.ipynb#print-data_2 >}}

extra value = 
{{< embed script.ipynb#print-data_3 >}}
```



``` python
# %% [markdown]
# This is a multiline
# Markdown cell

# %% [markdown]
# Another Markdown cell


#%% code cell #0
#| label: read-data
#| code-fold: true
x = 42

#%% code cell #1
#| label: print-data
#| code-fold: true
print(x)



#%% code cell #2
#| label: print-data_2
#| code-fold: true
print(x+58)



#%% code cell #3
#| label: print-data_3
#| code-fold: true
print(x**2)
```

![image](https://github.com/user-attachments/assets/445bbfd8-f8e0-4065-8d21-64fb51d19230)

**Comment by mcanouil** [comment]
use `--execute` flag.

**Comment by mjkrasny** [comment]
I tried, same error:
![image](https://github.com/user-attachments/assets/247bbdf9-fd1f-4992-9ca7-7c949ab0b4ca)

**Comment by cderv** [comment]
@mjkrasny you need to execute your embeded document. Quarto won't render `.ipynb` by default. 
See our doc about workflow with Python engine : https://quarto.org/docs/computations/python.html#workflow and embed from ipynb https://quarto.org/docs/authoring/notebook-embed.html#jupyter-notebooks for more context. 

The errors here is saying that your ipynb to embed does not have the expected cell-id, and tells you to check that it has been executed. Please follow the advices.

**Comment by mjkrasny** [comment]
ok, so the workflow at the moment is like this:

1. generate script.py file
2. convert to jupyter notebook using jupytext
3. open notebook, and run it all
4. render document.qmd

what is the point of "execute" command in YAML, and --execute flag then?

I think it would be great if they could run jupyter notebook in background, so step 3 would be obsolete.

But of course, the ideal case scenario is to work with percent .py script notation as already rised by @cderv (https://github.com/quarto-dev/quarto-cli/issues/10385)

**Comment by cderv** [comment]
> what is the point of "execute" command in YAML, and --execute flag then?

`--execute` flags seems to apply only on the targeted file explicitly in the `quarto render` call, and not to embedded files. It seems ok to me, and this is really targeted option here. `quarto render --execute` could also be called on other notebook individually. 

`execute` command in YAML can be used in `.ipynb` file. As far as I understand, you did not set it in your embed .ipynb file. If you add the YAML metadata field to your document , it will be picked up I believe. 

Though Quarto has a way to set metadata at once for several documents. Either globally in a `_quarto.yml` or on folder level. See about [Directory metadata](https://quarto.org/docs/projects/quarto-projects.html#directory-metadata). If you put all your notebook in a same folder, and add `execute: false` in such config, I believe it will also apply when rendering the embed files. 

So just try to play with what already exist in Quarto Project to handle your specific case. Base hypothesis is that Quarto won't re-execute your Jupyter notebook by default, so you need opt-in by configuration somehow.  If none of the above works, then indeed something is not completely right when embeding `.ipynb`. 

Hope it helps understand

**Comment by mjkrasny** [comment]
Thanks @cderv,

I tried adding YAML in my python script as you suggested
''' markdown

#%% [markdown]
# ---
# execute: 
#  enabled: true
#  echo: false
# jupyter: python3
# ---
``` markdown

but I don't think it is executed by the Quarto engine.

However, running the "jupyter nbconvert --to notebook --execute --inplace script.ipynb"
command, executes the notebook, and it can be later used in Quarto.
