### ISSUE TITLE
Allow zoom on figure in quarto html output (more enhancement than issue)

### ISSUE THREAD

**Issue by Pierre9344** [quarto-dev/quarto-cli#1037]
Hello,

In rmarkdown html output, it was possible to allow a zoom on the included picture and the figure generated with the css and javascript described in the next link: [https://stackoverflow.com/questions/57313317/zoom-in-on-images-in-an-rmarkdown-rendered-to-flex-dashboard](https://stackoverflow.com/questions/57313317/zoom-in-on-images-in-an-rmarkdown-rendered-to-flex-dashboard)

I tested it in a quarto html website and it doesn't work. I don't really know css and javascript so I don't have any idea of how to adapt it.

Can I ask you if it would be possible for you to help me adapt it or even better to include something similar as a base functionnality of the html output?

I thank you in advance for your answer.

**Comment by mine-cetinkaya-rundel** [comment]
I believe this is now implemented with the lightbox extension: https://github.com/quarto-ext/lightbox.
