### ISSUE TITLE
adding shiny components breaks inclusion of local images

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#104]
When including shiny components with `server: shiny`, `quarto run` (and maybe other deployment options, I didn't test them) doesn't serve the root directory. So when including images in the rest of the document:

```
![](dog.jpg)
![](img/dog.jpg)
```
doesn't work, but moving the image to a `www` folder

```
![](www/dog.jpg)
![](www/img/dog.jpg)
```
works.
Images or plots that are included via a link or as output from code chunks (thus e.g. with `src=demo_files/unamed-chunk-1.png`) also still work.

This might be something worth implementing to eliminate differences between regular qmd documents and those with shiny.

PS: I realize I am playing around with lots of features and breaking things in the process, so do let me know if those issues are premature because you are working on it anyways!

**Comment by jjallaire** [comment]
Yes, even though this is confusing it's by design -- the problem is that if we served the root directory then we'd also be serving your source code and data (which may or may not be okay).
