### ISSUE TITLE
Error with `eval: false` and `echo: false` in DOCX output crashes main.lua

### ISSUE THREAD

**Issue by brianmsm** [quarto-dev/quarto-cli#10401]
### Bug description

I'm encountering an error when rendering a Quarto document to DOCX format. The error seems similar to the one described in issue #9863, but it occurs with DOCX output. The issue happens when a chunk is configured with both `eval: false` and `echo: false`.

### Steps to reproduce

1. Create a Quarto document (.qmd) with the following content:
````qmd
---
title: "Untitled"
format: docx
execute:
  echo: false
---

```{r}
#| eval: false
#| label: tbl-t2
#| tbl-cap: hggfh
mtcars |> head() |> knitr::kable()
```
````

2. Render the document to DOCX:

```
quarto render test.qmd --to docx 
```

3. Observe the following error message:

```
processing file: test.qmd
1/2
2/2 [tbl-t2]
output file: test.knit.md

pandoc 
  to: docx
  output-file: test.docx
  default-image-extension: png
  
metadata
  title: Untitled
  
Error running filter C:/Users/brian/AppData/Local/Programs/Quarto/share/filters/main.lua:
...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:22198: attempt to index a nil value (field 'content')
stack traceback:
        ...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:1233: in local 'filter_fn'
        ...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:635: in function <...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:625>
        (...tail calls...)
        [C]: in ?
        [C]: in method 'walk'
        ...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:557: in function <...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:546>
        (...tail calls...)
        ...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:1334: in local 'callback'
        ...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
        ...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:1388: in function <...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:1385>
stack traceback:
        ...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:557: in function <...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:546>
        (...tail calls...)
        ...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:1334: in local 'callback'
        ...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
        ...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:1388: in function <...ian/AppData/Local/Programs/Quarto/share/filters/main.lua:1385>
```

### Expected behavior

The document should render without errors, and the chunk with `eval: false` and `echo: false` should not be included in the output.

### Actual behavior

The rendering process fails with an error related to indexing a nil value in `main.lua`.

### Your environment

- Pandoc version 3.2.0
- Quarto 1.5.5 & Quarto 1.6.4
- Windows 11

### Quarto check output

```bash
> quarto check
Quarto 1.6.4
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.6.4
      Path: C:\Users\brian\AppData\Local\Programs\Quarto\bin
      CodePage: 65001

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\brian\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.9
      Path: C:/Users/brian/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.7.2
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.4.1
      Path: C:/PROGRA~1/R/R-44~1.1
      LibPaths:
        - C:/Users/brian/AppData/Local/R/win-library/4.4
        - C:/Program Files/R/R-4.4.1/library
      knitr: 1.48
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks, I can reproduce on latest.
It's related to the cross-reference, *i.e.*, `tbl- ` prefix.

````qmd
---
format: docx
---

```{r}
#| eval: false
#| echo: false
#| label: tbl-t2
1 + 1
```
````

**Comment by cderv** [comment]
This code is in fact producing an empty cross ref Divs 

Minimal reprex
````markdown
---
title: test
format: 
  docx: default
  pdf: default
  html: default
---


::: {#tbl-t2}

:::

````

So this is really the question: How should empty [cross ref divs](https://quarto.org/docs/authoring/cross-references-divs.html) should be handled ? 

Currently this is not the same in all format

- with docx we get this issue in Lua `floatreftarget.lua`
	```lua
	Error running filter C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/resources/filters/main.lua:
	...2/src/resources/filters/./customnodes/floatreftarget.lua:679: attempt to index a nil value (field 'content')
	```
- with `format: pdf` we get a warning 
	````
	WARNING (C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/resources/filters/./customnodes/floatreftarget.lua:317) FloatRefTarget with no content: tbl-t2
	````
	and nothing in output 
	![image](https://github.com/user-attachments/assets/652e0f91-4871-4de0-83ce-bf3334644315)


- with html we get no warning and an empty cross ref table
	![image](https://github.com/user-attachments/assets/b7a7b493-857c-4e79-a512-bd8f371396ba)

Definitely this Lua issue should not be happening at all, but it raises also various questions: 

- What should be the result of an empty crossref divs in Markdown ? 
- Should `eval: false` in a cell computation output no external `.cell` div at all ? 
	- Answer depends on previous question and,
	- This one is related to 
		- https://github.com/quarto-dev/quarto-cli/issues/7665
		- https://github.com/quarto-dev/quarto-cli/issues/7670 
		- https://github.com/quarto-dev/quarto-cli/issues/7062

@cscheid how do you want to handle it ? Solve this docx format Lua error that should not be there, and then in a later time handle the output across format ?

**Comment by cscheid** [comment]
This is just a matter of adding a warning.
