### ISSUE TITLE
Randomly occuring segfault on empty revealjs document

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#10426]
### Bug description

I'm getting a randomly occurring segfault on an empty revealjs document:

```qmd
---
title: "Presentation - Name"
author: "John Doe"
format: revealjs
---
```

Here's the output I got from the most recent time it happened:

```
$ quarto preview presentation\ -\ name.qmd
/Users/USERS/Applications/quarto/bin/quarto: line 192: 38119 Segmentation fault: 11  "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_MAP_ARG}" "${QUARTO_TARGET}" "$@"
```

Here's the quarto version number:

```
$ quarto --version
1.6.3
```

### Steps to reproduce

1. `quarto create project default` 
2. Change filename to use revealjs

### Quarto check output

```
$ quarto check
Quarto 1.6.3
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.3
      Path: /Users/USERNAME/Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/USERNAME/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.4 (Conda)
      Path: /Users/USERNAME/miniforge3/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cderv** [comment]
I never encountered this one. Which OS are you ? 

It feels this will be hard to reproduce and I would think this is environment dependant. I suspect we need more informations to hope finding what could cause it. 

@cscheid @gordonwoodhull does it ring a bell for you such error ? 

Thanks

**Comment by mcanouil** [comment]
From the paths, I would say it's macOS.

FWIW, I never had a segfault fault in Quarto under any OS.

**Comment by cderv** [comment]
> I was hoping the line number could help here

This line is the call to `deno` command that call the `quarto.ts` main file. So possibly something related to Deno itself.

**Comment by mcanouil** [comment]
@kdheepak Could you provide more details on your environment? macOS version, how you installed Quarto, etc.

**Comment by gordonwoodhull** [comment]
I see deno segfaults on macos but very rarely (less than 1% of the time, and never twice in a row). I'm usually rendering and not previewing.

It would be nice to have a repro for this!

I tried this example about 20 times in a row and didn't see it.

**Comment by cderv** [comment]
@mcanouil we need repro, but this could be hard to have one. I think this is among issue that should stay open to compile further report, even if no repro is provided yet. Just mentioning in case we have a way to tell the bot not to close this one as stale.

**Comment by mcanouil** [comment]
Yes, we are on the same page, but worth making it explicit to avoid closing it in 2/3 weeks. 😉

**Comment by gordonwoodhull** [comment]
I haven't seen a segfault since this conversation last month. I was seeing it rarely but regularly before then.

I don't think we have changed Deno version in that time, but I am inclined to think that it was instability on their side which has passed?

I'll reopen if I see this again.

**Comment by kdheepak** [comment]
I still see this occasionally.

![Image](https://github.com/user-attachments/assets/d79b7326-6801-4860-8afa-e75661ce16d9)

I know I can probably just re-run this however you can imagine how it might be a scary looking message for my peers when I introduce quarto to a team.

**Comment by cderv** [comment]
Can you share `quarto check` @kdheepak ? 

@gordonwoodhull have you seen it since last time ? Was it the same error ?
Should we reopen and investigate ?

**Comment by gordonwoodhull** [comment]
I used to see this regularly. I don’t think I have seen this more than once in the past few months.

Unfortunately there isn’t any useful information in the crash afaict. It just Deno crashed, not where it crashed.

**Comment by mcanouil** [comment]
Even with the Deno update in Quarto CLI 1.6?

@kdheepak you have a typo in the extension of your reference document. FYI, avoid sharing screenshots of code or terminal outputs, especially without alternative text. Prefer copy/pasting the text inside a code block. This will make your content accessible to more users.

**Comment by cscheid** [comment]
@kdheepak I'm not positive if the following suggestion would help, but could you add `RUST_BACKTRACE=1` to your environment? (Something like adding `export RUST_BACKTRACE=1` to your `.bashrc` or `.zshrc`)

That should make it so that future deno segfaults would produce a stack trace, though since I can't repro on my setup, I'm not positive that's going to do it. (It will also add backtraces to any other Rust programs you might run...)

**Comment by kdheepak** [comment]
@mcanouil power point templates are `potx` files: https://support.microsoft.com/en-us/office/start-with-a-template-d3d4ece5-e965-45eb-9423-c34e61b34616

That code works to generate a pptx file correctly.

> FYI, avoid sharing screenshots of code or terminal outputs, especially without alternative text. Prefer copy/pasting the text inside a code block. This will make your content accessible to more users.

Good point! It'll make the issue more searchable.

@cscheid Happy to add that or even `RUST_BACKTRACE=full` to my config and report back if I see anything different next time.

---

Here's the output of quarto check:

```
Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /Users/XXXXXX/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /Users/XXXXXX/Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/XXXXXX/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.7 (Conda)
      Path: /Users/XXXXXX/miniforge3/bin/python
      Jupyter: 5.7.2
      Kernels: python-localvenv, python3

(\) Checking Jupyter engine render....
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Cannot start python-localvenv kernel:

Expected folder ".venv" in notebook directory /private/var/folders/1_/8skv_n7s2h7_ryz240dsr25m0000gp/T/quarto-session2a2d09295b522441/d9a2930e14cae8bd
(or any parent directory)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(/) Checking Jupyter engine render....2025-01-31 09:41:11,005 - traitlets - ERROR - Error occurred while starting new kernel client for kernel 504ee511-e958-4e53-97c3-02af82e03ea4: Kernel died before replying to kernel_info


Kernel died before replying to kernel_info
[✓] Checking Jupyter engine render....OK
```
