### ISSUE TITLE
Plotly plot not anymore rendered when using jupyter notebook in quarto

### ISSUE THREAD

**Issue by scalgary92** [quarto-dev/quarto-cli#1043]
Thanks for the great work
I have uploaded the newest quarto version 498.
I used to be able to render my jupyter notebook with plotly plots in html
now I have the following message 
Unable to display output for mime type(s): application/vnd.plotly.v1+json
How can I revert to previous versions of quarto?
All still works fine in qmd file but I would prefer to stick to Jupyter notebook

Thanks

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?

- [x] upgraded to the latest version (including your versions of R, the RStudio IDE, and relevant R packages)?

**Comment by jjallaire** [comment]
You can get old versions of Quarto here: https://github.com/quarto-dev/quarto-cli/tags

However, that error message looks to me like you have executed a plotly plot within VS Code (which saves the plot as JSON internally, which Quarto currently doesn't know how to render). If you set the rendered to "notebook" as demonstrated here it should work as expected:

```python
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "notebook"
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", 
                 color="species", 
                 marginal_y="violin", marginal_x="box", 
                 trendline="ols", template="simple_white")
fig.show()
```

**Comment by scalgary92** [comment]
Thanks a lot.
strange but the same code wasn't working on 499 but is working on 501.

**Comment by jjallaire** [comment]
I've been making some changes related to this over the past hour or so! Just updated the plotly docs to mention a variation of the workaround that should provide good rendering both in VS Code and in Quarto rendered HTML: https://quarto.org/docs/interactive/widgets/jupyter.html#plotly
