### ISSUE TITLE
`QUARTO_VERSION_REQUIREMENT` env var

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#10442]
(cc @jmcphers)

Quarto should observe and respect `QUARTO_VERSION_REQUIREMENT`. When provided, this would contain a semver-compatible string that Quarto would use as a self-check. When Quarto's own version is incompatible with that provided, Quarto should issue an appropriate warning.

**Comment by pastorn** [comment]
Would this be something also placed in the YML? One thing I really like about Quarto is that I **don't** need to create a giant bash script just to build my docs. It's the main selling point over pandoc.

**Comment by cscheid** [comment]
@sasja-san This feature is mostly for environments to ask Quarto to refuse running. That can be helpful in specific deployment situations.

The feature you're asking for is already supported under `quarto-required`, since Quarto 1.2: https://quarto.org/docs/download/changelog/1.2/index.html#miscellaneous. It works in [extension declarations](https://quarto.org/docs/extensions/project-types.html#complete-example) and in every document/project top level.

**Comment by cscheid** [comment]
Closed by 00249a46bab6e3e45adb9900677a33e599cb10d3
