### ISSUE TITLE
Default Altair chart dimensions are not respected in documents combining python and R code

### ISSUE THREAD

**Issue by joelostblom** [quarto-dev/quarto-cli#10459]
### Bug description

When I create a Altair charts, the default dimensions of the charts are respected when rendered form quarto documents containing only Python code:

![image](https://github.com/user-attachments/assets/996fe736-7e5c-432e-9d84-a9fb13631980)

However, when I mix and match R and Python, the dimensions of the chart are no longer respected and the chart area is stretched so that the chart becomes much too large:

![image](https://github.com/user-attachments/assets/38e0d58d-9d45-494e-93ab-41d046e0035d)

Setting the dimensions explicitly works as expected:

![image](https://github.com/user-attachments/assets/eb096540-0407-45dc-8b20-c4f5be94baf1)

Does quarto automatically switch to the jupyter python kernel if there are only python cell in the document? Then this might be an issue related to knitr + reticulate, but I'm not sure if the bug lies in how reticulate outputs the altair charts or how quarto renders output from reticulate.

### Steps to reproduce

Run `quarto preview name.qmd` with the following doc:

````md
---
format: html
---

Python code:

```{python}
import altair as alt

alt.Chart().mark_point()
```

R code:

```{r}
4 + 4
```
````

### Your environment

ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"

### Quarto check output

```bash
Quarto 1.5.55
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.1: OK
      Dart Sass version 1.58.3: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.55
      Path: /home/joel/miniconda3/envs/viz-oer/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/joel/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.4 (Conda)
      Path: /home/joel/miniconda3/envs/viz-oer/bin/python
      Jupyter: 5.7.2
      Kernels: ir, python3, conda-env-jb-py, conda-env-llm-analysis-py, conda-env-viz-oer-py, conda-env-avenger2-py, conda-env-quarto-py, conda-env-jbb-py, conda-env-agcl3-py, conda-env-573-py, conda-root-py, conda-env-sonalert-py, conda-env-agcl2-py, conda-env-jl-py, conda-env-531-r, conda-env-531-py, conda-env-100py-py, conda-env-avenger-py, conda-env-sdca_admin-py, conda-env-altmain-py, conda-env-nutrimap-py, conda-env-repo-stats-py, conda-env-agcl-py, conda-env-aly-py, conda-env-viz-oer-r, conda-env-532-py, conda-env-ghlms-py, conda-env-llm-analysis-r

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /home/joel/miniconda3/envs/viz-oer/lib/R
      LibPaths:
        - /home/joel/miniconda3/envs/viz-oer/lib/R/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
This would be a reticulate issue I believe as it is `reticulate` that takes over in this case.

**Comment by joelostblom** [comment]
Thanks for pointing me in the right direction. I can confirm that this is an issue in reticulate setting the dimensions explicitly instead of respecting the Altair defaults. I opened https://github.com/rstudio/reticulate/issues/1642 to follow up.
