### ISSUE TITLE
Rstudio render button renders only one option

### ISSUE THREAD

**Issue by jcolomb** [quarto-dev/quarto-cli#10465]
### What would you like to do?

Report an issue on quarto.org

### Description

It seems the render button can only render one type of output at a time, one needs to use the arrow to choose with one (otherwise the first one in the metadata is used).

- indicate how to choose the rendering option
- indicate how to render all output at once (via the terminal I suppose ?)

Maybe this could be changed in Rstudio and the render button could render all output per default ??

**Comment by cscheid** [comment]
We don't control the RStudio IDE - you probably want https://github.com/rstudio/rstudio
