### ISSUE TITLE
AI (Copilot/Codeium) autocompletions not working in visual mode

### ISSUE THREAD

**Issue by kv9898** [quarto-dev/quarto-cli#10474]
### Bug description

In the visual mode, autocompletion with Github Copilot/Codeium does not work anymore. They work fine in the source mode

### Steps to reproduce

1. Create a new quarto document in VSCode/RStudio
2. Turn to visual mode
3. Start a (R/Python) code chunk
4. Start typing - note no completions are available
5. Turn to source mode
6. Note completions work

### Expected behavior

AI autocompletions also work in visual mode

### Actual behavior

AI (Copilot/Codeium) autocompletions not working in visual mode

### Your environment

RStudio 2024.04.2+764 "Chocolate Cosmos" Release (e4392fc9ddc21961fd1d0efd47484b43f07a4177, 2024-06-05) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36, Quarto 1.5.56 (D:/quarto/bin/quarto.exe)

Positron Version: 2024.07.0 (system setup) build 2024.07.0-125
Code - OSS Version: 1.91.0
Commit: cae4905332a0f41a6233e196b48a6679b832000a
Date: 2024-07-31T22:26:02.970Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

### Quarto check output

Quarto 1.5.56
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.56
      Path: D:\quarto\bin
      CodePage: 936

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\kv989\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: D:/Anaconda/python.exe
      Jupyter: 5.3.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.2
      Path: D:/R-4.2.2
      LibPaths:
        - D:/R-4.2.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
This repository is about Quarto CLI.

Visual editor and VSCode extension requests are to be made on https://github.com/quarto-dev/quarto/issues
