### ISSUE TITLE
Giscus theme always defaults to darkMode on page load, even when viewing light webpage

### ISSUE THREAD

**Issue by connortwiegand** [quarto-dev/quarto-cli#10495]
### Bug description

Hello,

I currently have `giscus` (+relevant options) specified in a `_metadata.yml` file within the `posts` directory of my website. I have specified the light and dark `theme` keys, which are respected _upon toggling the theme_. However, if I am browsing the site in light mode, then navigating to a blog post always results in a dark-themed comment box. 

Toggling the website theme twice (to get back to light mode) results in the correctly themed box. However, even upon hitting refresh from here, a dark-themed comment box appears again on the light-themed page. 

### Steps to reproduce

Although perhaps not "minimal", the source code for my website, specifically targeted at the `posts` directory, is available here: https://github.com/connortwiegand/connortwiegand.github.io/tree/main/not-a-blog/posts

### Expected behavior

When viewing the website in light mode, giscus should appear in light mode.

### Actual behavior

Giscus always uses dark mode on page render.

### Your environment

VSCode 1.92.1 
Linux Mint 21.3 "Virginia" (Ubuntu 22.04-based)

### Quarto check output

```
Quarto 1.5.52
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.52
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/cwiegand/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6 (Conda)
      Path: /home/cwiegand/miniconda3/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib/R
      LibPaths:
        - /home/cwiegand/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Seems to be a duplicate of https://github.com/quarto-dev/quarto-cli/issues/8613

**Comment by connortwiegand** [comment]
Yes it seems I missed this, sorry!
