### ISSUE TITLE
RStudio not recognizing ojs using Quarto

### ISSUE THREAD

**Issue by rlin0004** [quarto-dev/quarto-cli#1049]
Hello, I tried to run some simple `ojs` code in `.qmd` under RStudio IDE but it's showing an error message:

![s1](https://user-images.githubusercontent.com/62991563/171760019-2c49cd0c-1906-4b4c-8179-d42b7af583ac.PNG)

`hello.qmd` (https://quarto.org/docs/get-started/hello/rstudio.html) is rendered correctly without any error, but if I try to run `ojs` related code it keeps showing the above error message.

I've checked that Quarto preview is enabled, and both Quarto (quarto-0.9.462-win) and RStudio (v2022.2.2.485) are installed under C:\Program Files.
![s2](https://user-images.githubusercontent.com/62991563/171760222-e6b4e4e9-ca06-4adf-a85d-93a1e4f3c025.PNG)

**Comment by jjallaire** [comment]
RStudio doesn't currently support running OJS chunks.
