### ISSUE TITLE
Possible options for `repo-actions` is not documented

### ISSUE THREAD

**Issue by EmilHvitfeldt** [quarto-dev/quarto-cli#10501]
### What would you like to do?

Report an issue on quarto.org

### Description

Searching for `repo-actions` brings be to the following links

- https://quarto.org/docs/reference/formats/html.html#website
- https://quarto.org/docs/websites/website-navigation.html#github-links

it shows

```yaml
repo-actions: [edit, issue]
```

but doesn't list `source` as an option.

Ref: https://github.com/quarto-dev/quarto-cli/blob/22af0f2f78c2e1b2e966d2bbf9bb71863aa1fc8f/src/resources/schema/definitions.yml#L692-L697

**Comment by mcanouil** [comment]
Thanks PRs are up:

- https://github.com/quarto-dev/quarto-cli/pull/10502
- https://github.com/quarto-dev/quarto-web/pull/1293
