### ISSUE TITLE
Spanners appear incorrect in tables produced with gt

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#10534]
### Bug description

Table spanners in gt-tables appear above the spanner label and not below as it should when rendering to html.

### Steps to reproduce

	---
	format: html
	---

	```{r}
	mtcars[1:3, 1:4] |> 
	  gt::gt() |> 
	  gt::tab_spanner(label = gt::md("Header"), columns = 2:3)
	```

### Expected behavior

![image](https://github.com/user-attachments/assets/4e4f9ab1-9c5b-4758-9f4d-5e304a954c29)

### Actual behavior

![image](https://github.com/user-attachments/assets/ef285aa9-ca1b-493c-84c2-b5677eb3212a)

### Your environment

* On Windows 11.
* gt v. 0.11.0

### Quarto check output

	Quarto 1.6.4
	[>] Checking versions of quarto binary dependencies...
		  Pandoc version 3.2.0: OK
		  Dart Sass version 1.70.0: OK
		  Deno version 1.41.0: OK
		  Typst version 0.11.0: OK
	[>] Checking versions of quarto dependencies......OK
	[>] Checking Quarto installation......OK
		  Version: 1.6.4
		  Path: C:\Users\au234616\AppData\Local\Programs\Quarto\bin
		  CodePage: 1252

	[>] Checking tools....................OK
		  TinyTeX: (not installed)
		  Chromium: (not installed)

	[>] Checking LaTeX....................OK
		  Tex:  (not detected)

	[>] Checking basic markdown render....OK

	[>] Checking Python 3 installation....OK
		  Version: 3.11.1
		  Path: C:/Users/au234616/AppData/Local/Programs/Python/Python311/python.exe
		  Jupyter: 5.2.0
		  Kernels: python3

	[>] Checking Jupyter engine render....OK

	[>] Checking R installation...........OK
		  Version: 4.4.0
		  Path: C:/PROGRA~1/R/R-44~1.0
		  LibPaths:
			- C:/Users/au234616/AppData/Local/R/win-library/4.4
			- C:/Program Files/R/R-4.4.0/library
		  knitr: 1.47
		  rmarkdown: 2.27

	[>] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Thanks, I can repro.

The typical `html-table-processing: none` workaround does apply here, so that might be something you want to use.

**Comment by cscheid** [comment]
This is currently a GT bug. The HTML doesn't validate. Quarto requires the HTML to validate before we can make promises about the behavior.

See below.

<img width="1936" alt="image" src="https://github.com/user-attachments/assets/44c04fbe-0c4c-4179-8a61-89c3d0795b11">
