### ISSUE TITLE
breadcrumbs only appear if title set in topmatter

### ISSUE THREAD

**Issue by machow** [quarto-dev/quarto-cli#10567]
### Bug description

The docs on [breadcrumbs](https://quarto.org/docs/websites/website-navigation.html#breadcrumbs) mention they will be displayed by default. It appears that when `title:` is not set in the top-matter, then they are not displayed.

Note that in this issue I'll refer to three possible meanings of title:

1. `_quarto.yml` sidebar `text:` title
2. qmd topmatter title
3. qmd header title

Currently, quarto requires (2) to be set. When this happens, (1) gets shown if set. Otherwise, (2) gets shown.

### Steps to reproduce

**_quarto.qmd**

```
project:
  type: website

website:
  sidebar:
    - contents:
      - section: "Tutorials"
        contents:
          - text: Tutorial sidebar title
            href: tutorials.qmd
```

**tutorial.qmd**

``````
---
# uncomment below to see breadcrumbs say "Tutorial sidebar title"
# title: Tutorial topmatter title
---

# Tutorial qmd first header

abc
``````

### Expected behavior

breacrumb for tutorial page should say "Tutorial sidebar title".

### Actual behavior

No breadcrumb shown

### Your environment

mac osx

### Quarto check output

```bash
Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.5
      Path: /Users/machow/.pyenv/versions/3.9.5/bin/python3
      Jupyter: 5.3.1
      Kernels: <removed>

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
      knitr: 1.39
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Thanks. We've had similar bugs in the past, so this tracks.

Can you just confirm to me that you're not using _both_ `title: ` and a Header of level 1? It's not perfectly clear from your `tutorial.qmd`.

**Comment by machow** [comment]
The example uses both, but I think the bug is that the breadcrumb only works if `title:` is set. quartodoc unfortunately sets title via the h1 header (`#`), but I'm guessing that will need to change as a separate quartodoc issue 😭

**Comment by mcanouil** [comment]
@machow As a side note, I think `quartodoc` should set `title` as it is safer and more reliable in Quarto. h1 are no title by default. Quarto promotes them in some conditions/context.

**Comment by machow** [comment]
That makes sense, and I'll switch it over!

**Comment by cscheid** [comment]
Quarto's HTML is itself not identical depending on whether the title is specified on `title:` vs on an H1 header. That's a Quarto bug by itself, and it seems to be the cause of this bug.
