### ISSUE TITLE
Document the downside of `html-table-processing: none`

### ISSUE THREAD

**Issue by olivroy** [quarto-dev/quarto-cli#10580]
### What would you like to do?

Report an issue on quarto.org

### Description

https://quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing.

Only talk about the upside of html-table-processing. I wonder if you could include reasons why not to do that. i.e. what features you will not get access to.

For example, this example benefits from `html-table-processing: none` 

https://github.com/rstudio/gt/issues/1850 (with the option enabled, you can get the correct widths)

This one doesn't. Adding `html-table-processing: none` breaks their document https://github.com/rstudio/gt/issues/1822

**Comment by cscheid** [comment]
Fixed by https://github.com/quarto-dev/quarto-web/commit/f85800893c5d6c60a7cb8c0c08e25a3b837e02d8
