### ISSUE TITLE
Potential typo in `--no-browse(r)` flag

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#106]
The corresponding jupyter notebook option is called `--no-browser`, matching it might help some users not to get confused.
`ERROR: Error: Unknown option "--no-browser". Did you mean option "--no-browse"?`

**Comment by jjallaire** [comment]
Yes agreed `--no-browser` would be better. Changed here: https://github.com/quarto-dev/quarto-cli/commit/6589bad0b2db82632864206c841371227c624376
