### ISSUE TITLE
Specifying `layout-ncol` breaks main figure div cross-reference link in HTML output

### ISSUE THREAD

**Issue by salim-b** [quarto-dev/quarto-cli#1060]
When creating a figure div with [subfigures](https://quarto.org/docs/authoring/figures.html#subfigures), the `id` attribute of the *main* figure div is lost in HTML output **as soon as `layout-ncol` is specified**, resulting in broken hyperlinks.

Consider the following reproducible example:

- Source file: [`t.qmd`](https://salim-b.gitlab.io/adhoc/t.qmd)
- Render command: `quarto render t.qmd --to=html --metadata=keep-md:true`
- Intermediate Markdown file: [`t.md`](https://salim-b.gitlab.io/adhoc/t.md)
- Final HTML file: [`t.html`](https://salim-b.gitlab.io/adhoc/t.html)

PDF/LaTeX output is not affected by this bug (i.e. all figure cross-reference links work fine).

Using latest Quato release from GitHub, v0.9.514.

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?

- [x] upgraded to the latest version (including your versions of R, the RStudio IDE, and relevant R packages)?

**Comment by jjallaire** [comment]
Thanks for reporting this! Fixed here (https://github.com/quarto-dev/quarto-cli/commit/da701101ce8cced6d2c1d085a4e73c2fc77559e2). Avail in next build (>= v0.9.515)

**Comment by salim-b** [comment]
Holy... that was fast! 😄 I'll test as soon as the build is ready.
