### ISSUE TITLE
[pandoc 3.2.1] Check for change on table as odd / even / header classes have been removed

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#10607]
Change happened at 
- https://github.com/jgm/pandoc/commit/cd15313216c75e1ff3577da728172db9ff69a6b6

It caused issues with R Markdown 
- https://github.com/rstudio/rmarkdown/issues/2567
- https://github.com/rstudio/rmarkdown/issues/2566

It will be important to check this is not impact too much Quarto. We leverages the class in some places like 
https://github.com/quarto-dev/quarto-cli/blob/814604696f1a36c4351245100f72c7fb75fba5eb/src/format/html/format-html-bootstrap.ts#L453-L454

CSS will need to be updated to 
```css
thead tr { /* targets previous header class */ }
tbody tr:nth-child(2n) { /* targets previous even class*/ }
```

**Comment by cscheid** [comment]
Putting this back to v1.6 in case we merge the new Pandoc by then.

**Comment by cderv** [comment]
Note that this will probably be solved while dealing with 
- https://github.com/quarto-dev/quarto-cli/issues/10904

following the pandoc's update 
- https://github.com/quarto-dev/quarto-cli/pull/10840
