### ISSUE TITLE
Quarto presentation not letting me easily go back from pdf print mode to revealjs presentation mode

### ISSUE THREAD

**Issue by abbyruthe** [quarto-dev/quarto-cli#10610]
### Bug description

When I switch to print view via the [Navigation Menu](https://quarto.org/docs/presentations/revealjs/presenting.html#navigation-menu) in my Quarto presentation, I am unable to switch back to presentation mode without having to edit the URL to remove the `print-pdf=` option in the URL.

### Expected behavior

I would like to be able to switch back to presentation mode seamlessly. I switched to PDF mode to send a colleague a copy of the presentation to show them where it was at and then it was not easy to get back to the presentation mode which is preferred when building the presentation.

### Actual behavior

I am unable to switch back to presentation mode easily. I instead have to alter the URL (which was not documented to my knowledge) which in a presentation setting when I am saving this and sending it while sharing is not a professional look.

### Your environment

- IDE: RStudio Pro 2023.12.1 "Ocean Storm" Release
- R: 4.4.0

### Quarto check output

![image](https://github.com/user-attachments/assets/55014c57-99f2-462c-8d79-332fb67ba12b)

**Comment by cscheid** [comment]
Did hitting the Back button in your browser not work?

**Comment by mcanouil** [comment]
FWIW, if there is an issue there, it's a Reveal.js issue and not a Quarto one.

**Comment by cscheid** [comment]
> the whole thing is Reveal.js.

Well sure - but if navigation doesn't work for some reason, then that's definitely a bug that we need to workaround on our side or report upstream. (In this case, I locally tested the rendering and the Back button worked for me, which is the standard way to go back from one URL to another.)

**Comment by abbyruthe** [comment]
@cscheid and @mcanouil, thank you both for the quick response! Yes, hitting the back button does fix this issue. I think that either including this information to hit the back button in the [documentation ](https://quarto.org/docs/presentations/) in a clear fashion would be helpful or making some sort of button to go back that's clear would be a good solution. 

Thank you again!

**Comment by cderv** [comment]
This was in fact an issue that I'll fix. We closed that too quick.

**Comment by cderv** [comment]
Regarding keybinding, Toggle can be done with `E` which let Toggle on and off Print View. 

Doc has been updated to highlight this keybinding.
