### ISSUE TITLE
Feature - Add cross references for chapters/parts of a book

### ISSUE THREAD

**Issue by pedropark99** [quarto-dev/quarto-cli#1061]
Hey! I am writing a book using Quarto. And I wanted a simple way to reference a chapter or a part of the book. I could just use the Section reference (#sec-...), to reference the first section of the Chapter, so the reader could get to the beggining of the chapter. But the rendered result (like "Section 9.1") would give the impression to the reader, that I am discussing the subject only in that specific Section, when I am actually using a entire Chapter to do so.

As an example, at a specific point of the book, I wanted to reference a chapter like this:

```
You can use the `write()` method, which is described latter in the @chp-import-export.
```

This markdown code could result, for example, in something like this:

```
<p>You can use the <code>write()</code> method, which is described latter in the <a href="09-import.html">Chapter<span>9</span></a>.</p>
```

This way, the reader can understand that he should read all the Chapter 9, to fully understand the `write()` method, and not just a specific section. So the idea, is to add simple keys to reference a part or chapter, like `#chp-` for Chapters, and `#prt-` for Parts, so that, they could be rendered differently that section references (`#sec-`) or figure references (`#fig-`). I do not know if the HTML code above makes sense with Quarto directives for cross-references, but, I think it translates well the intention.

**Comment by jjallaire** [comment]
If you put a `#sec` identifier on a chapter heading then things should work as you expect. e.g.

```markdown
# Import Export {#sec-import-export}
```

The word "Chapter" (or "Appendix" as appropriate) will automatically be used within the reference.

**Comment by pedropark99** [comment]
Thank you! I just made a test for this suggestion, but, for some reason, it did not workout. The reference continues to use the word "Section", although, it did reference the number of the chapter (e.g. 6), and not a number of a specific section (e.g. 6.1). 

What I did, was to add the following markdown at the top of file `07-import.qmd`:

```
# Importing data to Spark {#sec-import-export}
```

And then, at file `05-transforming.qmd`, I have the following cross-reference to this point:

```
The last action would be the `write()` method, but we will explain this method latter, in the @sec-import-export.
```

The end result is presented in the print below. See that "Section 6" should be "Chapter 6", or something like it.

![image](https://user-images.githubusercontent.com/69123925/172051926-f799318f-0988-4258-90be-98f92a4e61ba.png)

If you need to reproduce this, you can access the entire book at (commit [c51285f](https://github.com/pedropark99/Introd-pyspark/commit/c51285fb13e0f1c7ab9f4118ab77091a2da0c838)):

https://github.com/pedropark99/Introd-pyspark

**Comment by jjallaire** [comment]
The problem may be the version of Quarto you are running (as we just fixed some behavior surrounding Chapter/Section headings in the last couple of weeks). What version are you running?

**Comment by pedropark99** [comment]
I am using version 0.9.393 on Linux.

![image](https://user-images.githubusercontent.com/69123925/172053104-058a54b5-c2b4-4cd9-b8eb-d2789067228e.png)

**Comment by pedropark99** [comment]
I upgraded to version 0.9.518

![image](https://user-images.githubusercontent.com/69123925/172053575-4f678b8a-b7b5-41b7-9bc7-308ee2668f03.png)

And, just re-compiled the entire book. Now it worked as expected:

![image](https://user-images.githubusercontent.com/69123925/172053559-5755e541-a3ff-481b-97d8-4ffd6d441af6.png)

Thank you for the attention! I am closing the issue since a solution to the "problem" was found.

**Comment by jjallaire** [comment]
Great, glad that was it!
