### ISSUE TITLE
Compile error for empty proof environments

### ISSUE THREAD

**Issue by d-morrison** [quarto-dev/quarto-cli#10624]
### Bug description

When compiling the qmd below using quarto v1.5.56 with `quarto render test.qmd`, I get a compilation error from main.lua (pasted in "actual behavior" section below.  Using any profile other than "solutions" appears to produce the same error.

### Steps to reproduce

````
---
title: "test"
format: pdf
---

::: {.solution .content-visible when-profile="solutions"}
hello
:::
````

This works: `quarto render test.qmd --profile=solutions`
These don't work:

- `quarto render test.qmd`
- `quarto render test.qmd --profile=default`

### Expected behavior

I expected quarto to compile a pdf with just the title "test" when run **_without_** `profile=solutions`

### Actual behavior

```
Error running filter /Applications/quarto/share/filters/main.lua:
/Applications/quarto/share/filters/main.lua:22821: attempt to index a nil value (field 'integer index')
stack traceback:
	/Applications/quarto/share/filters/main.lua:1233: in local 'filter_fn'
	/Applications/quarto/share/filters/main.lua:635: in function </Applications/quarto/share/filters/main.lua:625>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	/Applications/quarto/share/filters/main.lua:557: in function </Applications/quarto/share/filters/main.lua:546>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:1334: in local 'callback'
	/Applications/quarto/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:1388: in function </Applications/quarto/share/filters/main.lua:1385>
stack traceback:
	/Applications/quarto/share/filters/main.lua:557: in function </Applications/quarto/share/filters/main.lua:546>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:1334: in local 'callback'
	/Applications/quarto/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:1388: in function </Applications/quarto/share/filters/main.lua:1385>
```

### Your environment

run via mac terminal and RStudio "Chocolate Cosmos" Release (e4392fc9, 2024-06-05) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36, Quarto 1.5.56 (/Applications/quarto/bin/quarto)

### Quarto check output

(base) ➜  Downloads quarto check
Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/ezramorrison/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12 (Conda)
      Path: /Users/ezramorrison/miniforge3/bin/python
      Jupyter: 5.7.1
      Kernels: julia-1.9, python3

[✓] Checking Jupyter engine render....OK

(|) Checking R installation...........starting ~/.Rprofile
Ending ~/.Rprofile
[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.47
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
In general, try not to "collapse" divs that have different meanings - this is technically something Quarto could do better but it'll be very hard to do well in general. So, do this instead:

````
---
title: "test"
format: pdf
---

::: {.content-visible when-profile="solutions"}
::: {.solution}
hello
:::
:::
````

**Comment by d-morrison** [comment]
Thanks for that solution; I can work with that. FWIW, my collapsed-div version did work with quarto v1.4.557 (just reinstalled to check), but I understand if it's not a syntax you're going to support going forward.

**Comment by cscheid** [comment]
> but I understand if it's not a syntax you're going to support going forward.

I have a fix coming up which should improve the situation here. The main reason to use that more verbose syntax is that it's "more conservative". Quarto will try to do what you mean with the former, but it's a best-effort situation that can't work in general for all possible div behaviors and combinations.

**Comment by cscheid** [comment]
More specifically, what changed between versions is that we started interpreting conditional content with multiple classes to mean "remove the content but maintain the div". This is a reasonable interpretation for the case where you have other classes in the div (although a different one from what you had!). This doesn't need profiles to trigger the problem. The following will fail in Quarto 1.5 and later:

````
---
format: pdf
---

::: {.solution .content-visible when-format="html"}
hello
:::
````

I've made changes to the proof environment to not crash when it's empty. PR incoming.

**Comment by d-morrison** [comment]
That PR worked for me - thanks!!
