### ISSUE TITLE
double-slash URLs are mistransformed

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#1062]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1058

<div type='discussions-op-text'>

<sup>Originally posted by **bryanhanson** June  3, 2022</sup>
I am using [Goatcounter](https://goatcounter.com) for web page analytics.  I just figured out after a month that it is not working.  Goatcounter says to put this on the page so it will be tracked:

```
<script data-goatcounter="https://chemospec.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
```

So I put in my `_quarto.yml` the following:

```
website:
  body-footer: <script data-goatcounter="https://chemospec.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
```

But when the `body-footer` entry is actually put on the page Quarto changes it just a bit:

```
<script data-goatcounter="https://chemospec.goatcounter.com/count" async="" src="../..//gc.zgo.at/count.js"></script>
```

Any suggestions for doing this differently?  Or is there a bug in how `body-footer` is being parsed?

Full repo is [here](https://github.com/bryanhanson/CSR)  Last updated around 3 May using then-current Quarto. However, I don't see any discussion of `body-footer` in either issues or discussions that I can find since that time.

</div>

**Comment by jjallaire** [comment]
Resolved with: https://github.com/quarto-dev/quarto-cli/commit/fb6a2a41e1c59cfb811efc38add379605dccdb7d

@cscheid Apologize for grabbing this one -- it was in my inbox and I just saw it and fixed it and didn't realize you might have been taking a shot at it.
