### ISSUE TITLE
Issue when configuring platform for windows 11 home edition 

### ISSUE THREAD

**Issue by Thamira2001** [quarto-dev/quarto-cli#10648]
### Bug description

PS C:\Users\thami\dev essentials\Open source projects\Quarto-cli\quarto-cli> .\configure.cmd
The system cannot find the path specified.
The system cannot find the file essentials\Open.
"Translated/recorded configuration settings from unix configuration script"
'win_configuration.bat' is not recognized as an internal or external command,
operable program or batch file.
The syntax of the command is incorrect.
A subdirectory or file \tools already exists.
Bootstrapping Deno...
A subdirectory or file x86_64 already exists.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
tar: Error opening archive: Failed to open 'deno-x86_64-pc-windows-msvc.zip'
tar failed; trying to unzip...
'unzip' is not recognized as an internal or external command,
operable program or batch file.
Unable to decompress deno-x86_64-pc-windows-msvc.zip
 

### Steps to reproduce

fork main branch on to as you the owner 
git clone your fork  on to your windows 11 machine 
cd quatro-cli
./configure.cmd

### Expected behavior

the error message show above in bug description 

### Actual behavior

not sure because this is the first time i tried to configure this repo 
im guessing it should configure the development version properly on windows 11 machine 

### Your environment

Windows 11 home edition , 16GB RAM, I5 processor 13th gen 
used gitbash to clone 
used Microsoft Powershell inside VScode to run configure command 

### Quarto check output

1.6.9
 from version.txt

**Comment by cscheid** [comment]
It's the spaces in your folder names. We should fix this, but let me tell you that you will be saving yourself a _lot_ of heartache over your dev career if you just avoid spaces in folder names.

**Comment by Thamira2001** [comment]
thanks alot for getting back to me and advice on folder names, really appreciate it !
