### ISSUE TITLE
Quarto not finding the file I'm rendering it from

### ISSUE THREAD

**Issue by colinc1994** [quarto-dev/quarto-cli#10662]
I'm trying to run a simple render for a test script and get the error that it can't find "report_markdown.qmd" even though I'm rendering it from the exact file it can't find. Has anyone come across this issue?

![image](https://github.com/user-attachments/assets/174ac1e6-e6c7-4175-82b0-c96a29fddcbb)

**Comment by cscheid** [comment]
We need more information. Please follow the instructions in https://github.com/quarto-dev/quarto-cli/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
