### ISSUE TITLE
Emeding of table or plot figure not working in quatro (manuscript)

### ISSUE THREAD

**Issue by fischer-paul** [quarto-dev/quarto-cli#10687]
### Bug description

Hello, 
i have a problem when try to render a quarto (manuscript) that contains an embeding of a table and/or a plot from another quatro document. 
The other file seems to be found, but there is a error message each time, when i render index.qmd to html: 

`{{< embed ../notebooks/tbls_figs.qmd#fig-one >}}`

```
> Watching files for changes
> Browse at http://localhost:7825/index.html
> ERROR: The cell fig-one does not exist in notebook

```
I have labeled the corresponding chunk like that, but also tried only using {r fig-one} and only using #|label: fig-one

> {r fig-one}
> #| label: fig-one

I have emeded just the whole document. This basically works. But there also the figure / table is not displayed. 

If i run the tbls_figs.qmd "stand-alone" i get a perfect html with the table and figures that are created there by code inside. 

### Your environment

- IDE: Rstudio RStudio 2024.04.2+764 "Chocolate Cosmos"  
- Quarto 1.5.56 
- OS: Windows 10

### Quarto check output

Quarto 1.5.56
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.56
      Path: *********
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: *******
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.4 (Conda)
      Path: *******
      Jupyter: 5.7.2
      Kernels: python3, ir

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.4.1
      Path: C:/PROGRA~1/R/R-44~1.1
      LibPaths:
        - ******
        - ******
      knitr: 1.48
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK

**Comment by fischer-paul** [comment]
It seems to be an issue with the relative path...
If i put the referred document into a subfolder notebooks/ relative to the index.qmd and use `{{< embed /notebooks/tbls_figs.qmd#fig-one >}}` it works. 
Is there any support for referring to a place outside of the main quatro document folder? Or am I doing it wrong?

**Comment by mcanouil** [comment]
@fischer-paul Please follow the issue template guidelines and provide a small fully reproducible example.
We can't use your report as is.
Thank you!

See the template: https://github.com/quarto-dev/quarto-cli/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
