### ISSUE TITLE
broken pdf / tex output

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#107]
When I use `quarto render test.qmd -t pdf` on the test document in `tests/docs/` I get a `missing \begin{document}` error because the intermediate `.tex` file created looks like this:

```
%PDF-1.5
%ÐÔÅØ
5 0 obj
<<
/Length 131       
/Filter /FlateDecode
>>
stream
xÚÎ«1Pß¯Ù^zo_[Kx$àê@A±ü=Ôq¸Âa«Ü\VµØÈÎ$êùr¢äõ½Þ½õNôên¬$}zÞÚdzyC»PÀL%FÊ.ÂBûSëD|A·ÏòçÏºª7x=(
endstream
endobj
14 0 obj
<<
/Length 225       
/Filter /FlateDecode
>>
stream
xÚÅ=OÃ0@÷üíÁîÏvìDAÌÞ*K1I´JóÿCZ¤¡ÓN÷ýz@xmðÊ§ÔìöÁXÝ }Bp9GÒLRñ|%ËüHï»½quôÆ/edu´#Ð¯eo%wÇ±Ê	-C|lïù¿øóEõû?á «ÚD¿¥V%l½Yì¨6wz~ËT¨ÙP¦Ê4´f§áxÅyç<å~ÊçaÎC·yS»2înqC¡v¯S8íuÌöÔ|üoM
endstream
endobj
28 0 obj
<<
/Length1 1772
/Length2 20418
/Length3 0
/Length 21540     
/Filter /FlateDecode
>>
stream
```

[test.zip](https://github.com/quarto-dev/quarto-cli/files/7134654/test.zip)

I noticed this on another document of mine, so I went back to the simplest test possible. I thing it was one of  the more recent commits (last 3 days).

**Comment by jmbuhr** [comment]
## Update

I don't think it was one of the previous commits, I checked with earlier versions that I knew to work and they didn't work now so it must be something with my system.

What is puzzling to me is that `quarto render test.qmd -t pdf` creates the garbled intermediate `.tex`-file, but if I run `quarto render test.qmd -t latex` and then `pdflatex test.tex` it works just fine.

**Comment by cderv** [comment]
Hi @jmbuhr

I can reproduce with your command. Can you try `quarto render test.qmd --to pdf` ? This works fine for me. is it for you ?

**Comment by jmbuhr** [comment]
This gives me an IO error from quarto because `test.tex` is not created (no file output)

**Comment by cderv** [comment]
Yes I don't know about short version of flags. `quarto render --help` does only show long version `--to`. 

FWIW 
* `quarto render test.qmd --to pdf` correctly produce a pdf file
* `quarto render test.qmd -t pdf` does error with same error as you : `LaTeX Error: Missing \begin{document}.`

It is possible that `-t` is not catched by Quarto to map on `--to` and it is passed to Pandoc directly and command line arg. (which you can do with any Pandoc specific command arg). If this is the case this would explain the two different process (Quarto pdf engine or Pandoc running pdf enfine). However, I can't (yet) reproduce the error using Pandoc only.

**Comment by jjallaire** [comment]
We were attempting to support `-t` but there was on oversight that prevented it from working correctly. Here is the fix (+ similar fix for the `-o` option): https://github.com/quarto-dev/quarto-cli/commit/77ae0eb0d1badf9d7bb504b562422bf1d57d0d74

**Comment by jmbuhr** [comment]
With this fix I am now getting the same error for `-t` and `--to`, which is good. But I am not able to produce a pdf wit `quarto render`. Oh, hang on a second, think I found something.

**Comment by jjallaire** [comment]
I am currently able to create pdfs with both flags. LMK what else you
discover!

**Comment by jmbuhr** [comment]
Ok, this is weird now, please bear with me:
- When I add the yaml keyword `keep-tex: true` it works. `quarto render test.qmd -t pdf` correctly produces a pdf.
- When I set it to false, `quarto render test.qmd -t pdf` produces and error (`Input/output error (os error 5)`) and there is no `test.tex` file, but `test.pdf` still get's created and works just fine.
- When I run `quarto render test.qmd -t pdf -o test.something` and then `mv test.something test.pdf`, I get a perfectly valid pdf file.

**Comment by jmbuhr** [comment]
Also, by accident I also found out what the weird garbled intermediate `.tex` file in my initial issue was: This is what a pdf-file looks like, when opened with a text editor! So apparently something had already created the pdf file but called it `.tex` and then tried to convert to to a pdf with `latex` again, which results in the error.

**Comment by jmbuhr** [comment]
Could it be, that somewhere in the quarto rendering process, the pdf is produced twice. Maybe the first time pandoc already calls e.g. `pdflatex` and produces the pdf, but quarto tries to do the same a second time?

**Comment by jjallaire** [comment]
Could you send the src code of the qmd? The error is happening when attempting to clean supporting files (which my doc doesn't have). Just want to see exactly what your doc is producing.

**Comment by jjallaire** [comment]
That `os error 5` is a file permission error. Is it possible that there is a `_files` directory that is owned by a different user?

**Comment by jmbuhr** [comment]
It was the `tests/docs/test.qmd` file that comes with the quarto repo, but you are right, fixing some file permisisons made the error go away, thank you!
