### ISSUE TITLE
blog output: tag links don't work from pages called with an anchor URL

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#10710]
### Bug description

If I open this URL this URL that contains an anchor

https://quarto.org/docs/blog/posts/2024-07-02-beautiful-tables-in-typst/#cars-heatmap-gt-r

the links of the page tags does not work, the links are not active

![image](https://github.com/user-attachments/assets/9dd89f2f-a290-4a72-8330-864d1a3ca7f8)

### Steps to reproduce

- open https://quarto.org/docs/blog/posts/2024-07-02-beautiful-tables-in-typst/#cars-heatmap-gt-r and try to click on a tag

### Expected behavior

To have the tag links work

### Actual behavior

The tag links not work

### Your environment

The env used for quarto website

### Quarto check output

The output of quarto website

**Comment by mcanouil** [comment]
Could you provide the `quarto check output` as requested in the template?

**Comment by aborruso** [comment]
@mcanouil I reproduced the user experience, it is the blog of the repository of the fourth site.
For this reason I did not include what was requested in the template.

This is the repo https://github.com/quarto-dev/quarto-web

Should I download the repo locally, render and see if it doesn't work locally by me as well? I don't think so, I think what you see online may be enough.

Thank you always

**Comment by mcanouil** [comment]
It's not about the reproducible example.
It's really about your environment which is not the one used for Quarto website.
And we have no idea which Quarto and dependencies you are using.

**Comment by mcanouil** [comment]
It seems you are commenting on a rendered page, but did you reproduce the error? Possibly with a simple example.

**Comment by aborruso** [comment]
Thank you, I close it and open again in the repo of website

**Comment by cderv** [comment]
This is fine here. Let's not duplicate on the other side.

**Comment by cderv** [comment]
Problem is in `quarto.js`. The link processing does not account for anchor part in url 
https://github.com/quarto-dev/quarto-cli/blob/962c77e8a56932567360dd3f17a27b81ea12f501/src/resources/formats/html/quarto.js#L227-L260

We'll fix this.

**Comment by mcanouil** [comment]
> Thank you, I close it and open again in the repo of website

That's not what I meant. I meant you seem to report an issue on the website that you did not reproduce using a simple reproducible example with Quarto CLI.

**Comment by aborruso** [comment]
@cderv I also seemed fine here.It was a special case in my opinion, well described, so it didn't make sense to put those two parts of the template. But maybe I'm wrong.

Anyway, thank you very much to you and @mcanouil

**Comment by aborruso** [comment]
And I'm glad I was helpful. Unfortunately, I don't know how to correct the code

**Comment by cderv** [comment]
Yes thanks for the report. We'll handle it from here. 

> It was a special case in my opinion, well described, so it didn't make sense to put those two parts of the template. But maybe I'm wrong.

FWIW I agree with you, it was descriptive enough and reproducible with the website so we can find the issue. This is special case is usually true for JS code part that runs in browser. If is applies on website, then it will most of the time impact our quarto website. 

Thank you, this is enough for me to go fix this.
