### ISSUE TITLE
Local Deno scripts with import statements fail with "Failed writing lockfile"

### ISSUE THREAD

**Issue by ellis** [quarto-dev/quarto-cli#10711]
### Bug description

I'm unable to load deno scripts from qmd files if those deno scripts contain import statements.
In the [documentation](https://quarto.org/docs/projects/scripts.html#deno-scripts), there is a sample script with this import:

```ts
import { parse } from "https://deno.land/std/yaml/mod.ts";
```

That doesn't actually work, at least not on my system.

### Steps to reproduce

Following along with the example in your [documentation](https://quarto.org/docs/projects/scripts.html#deno-scripts), create a file named `test.qmd`:

````qmd
---
title: "Test calling local Deno script"
---

```{ojs}
import { config } from "./test.ts"
config
```
````

Create a file `test.ts` being some form of the example, e.g.:

```ts
/// <reference lib="deno.ns" />
import { parse } from "https://deno.land/std/yaml/mod.ts";
export const config = parse(Deno.readTextFileSync("test.yml"));
console.log("config:", config);
```

Create a file `test.yml`, e.g.:

```yaml
a: 1
b: 2
```

Verify it deno:

```
$ deno --allow-read test.ts
config: { a: 1, b: 2 }
```

### Expected behavior

Quarto should be able to load local Deno scripts.

### Actual behavior

Running with quarto, however, results in this error:

```
$ quarto preview test.qmd --no-browser --no-watch-inputs                                    
ERROR: Compilation of typescript dependencies in ojs cell failed.
[
  "error: Failed writing lockfile.",
  "",
  "Caused by:",
  "    Permission denied (os error 13)",
  ""
]
error: Failed writing lockfile.

Caused by:
    Permission denied (os error 13)
```

Running with `strace -e file -f quarto preview test.qmd --no-browser --no-watch-inputs`  reveals that it's trying to write to `/opt/quarto/share/conf/deno.lock`.  That seems wrong.

Note that if `test.ts` doesn't contain any imports, quarto executes fine.

### Your environment

- IDE: not applicable
- OS: Ubuntu 22.04

### Quarto check output

Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: python3, deno

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")

**Comment by cderv** [comment]
> Quarto should be able to load local Deno scripts.

Do I get it right that you are trying to run `.ts` file for Deno inside an OJS computation cell ? 
Or are you trying to do something else ? Are you expecting that object from the script is available OJS ? 

The doc you linked (https://quarto.org/docs/projects/scripts.html#deno-scripts) are about `quarto run` and pre / post render script, being run using `quarto run` internally

> If you want to create **project scripts** with TypeScript, `quarto run` enables you to use the [Deno](https://deno.land/) TypeScript interpreter bundled with Quarto.

> Following along with the example in your [documentation](https://quarto.org/docs/projects/scripts.html#deno-scripts), create a file named test.qmd:

The example don't show that you can use the .ts script inside an OJS filter. Did you get such example from somewhere else ?

**Comment by ellis** [comment]
Thanks for clarifying questions, @cderv .  As you pointed out, I may have misunderstood the purpose of that particular page in the documentation (more about this below).

> The example don't show that you can use the .ts script inside an OJS filter. Did you get such example from somewhere else ?

Yes, in [code-reuse](https://quarto.org/docs/interactive/ojs/code-reuse.html).  Indeed, code without imports works fine.
But without being able to access external imports ((e.g. not to have to reinvent standard libraries), local code is of extremely limited use.  Based on the [scripts](https://quarto.org/docs/projects/scripts.html#deno-scripts) page, I figured we should be able to use the Deno standard library.

**Comment by mcanouil** [comment]
FYI, the "code-reuse" is mostly/partly a Quarto addition to Observable within Quarto.
This does not support TypeScript thus why it is not documented.

Note also that even if Quarto allows some things Observable is not JavaScript.

**Comment by cderv** [comment]
Thanks for the clarification. This is indeed two distinct topic here. I hope this thread clarifies. 
I'll close this as there is I think nothing to fix. You may be able to manage what you want using libraries in OJS.

**Comment by ellis** [comment]
Thanks for the additional information.

> Did you look at the libraries page for Observable? https://quarto.org/docs/interactive/ojs/libraries.html

Yes, I worked with that information when creating my initial .qmd files.  But the need to modularize code quickly arises.

In R, this is easy enough.  I was hoping to achieve something similar with typescript.

> These two things are very different thus why they are not together in the documentation.

Ok.  Since the external .ts files are executed by Deno anyway, I figured they would have access to the same libraries.

> You may be able to manage what you want using libraries in OJS.

I don't think so... At least I wasn't able to figure out good approach so far.

Next, I'll probably look more into [Projects](https://quarto.org/docs/projects/quarto-projects.html) or the Deno engine in JupyterLab.

If you'd have any other suggestions, I'd be happy to check them out too.

**Comment by cderv** [comment]
> Since the external .ts files are executed by Deno anyway, I figured they would have access to the same libraries.

They are executed only 
- On demand with `quarto run`
- or as way to run the processing before `quarto render` happens, or after it happens. 

It does not run in the middle on `quarto render` while leaving some information available for OJS cell. 

> But the need to modularize code quickly arises.

I don't know OJS that well it works mainly with .js script. Why did you try typescript file ?
Using Observable JS code to do what you want, and then making a module out of it could be a good path to me. Did you try using a .js script containing code for OJS ?

**Comment by ellis** [comment]
> It does not run in the middle on quarto render while leaving some information available for OJS cell.

Thanks, understood now.

> Why did you try typescript file ?

We have a large code base in typescript already, and I'd like to integrate it where appropriate.  When using OJS code, we don't get any code completion and lose all the other benefits of static typing.

> Using Observable JS code to do what you want, and then making a module out of it could be a good path to me.

I'll keep that in mind as we experiment with different options.

I appreciate the feedback!
