### ISSUE TITLE
quarto listing filters return nothing when using any upper case characters

### ISSUE THREAD

**Issue by e-kotov** [quarto-dev/quarto-cli#10720]
I think this must be an issue introduced perhaps in a new release of Quarto? I don't see it in some older versions like:

https://web.archive.org/web/20230329074857/https://quarto.org/docs/extensions/

I think it is worth opening a new issue to track this.

_Originally posted by @dragonstyle in https://github.com/quarto-dev/quarto-cli/issues/6755#issuecomment-2330298287_

# The issue

When using Quarto listings with filters, in some websites the filter returns no matches if the user inputs Any Upper Case Characters.

## Where the problem exits

- https://m.canouil.dev/quarto-extensions/ with source here https://github.com/mcanouil/quarto-extensions
- https://albert-rapp.de/blog with source here https://github.com/AlbertRapp/Blog-1
- http://www.ekotov.pro/mitma-data-issues/ with source here https://github.com/e-kotov/mitma-data-issues

## Where it does not exist and works as expected with Any case of Letters

- https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/ with source here https://github.com/mine-cetinkaya-rundel/quarto-tip-a-day

Frankly, comparing the source and yaml headers of all these sites, I could not figure out what the reason for this behaviour is. Perhaps as suggested by @dragonstyle , this may be an issue that appears with certain versions of `quarto`.

**Comment by dragonstyle** [comment]
The problem exists in:
quarto-1.6.4
quarto-1.6.9
quarto-1.5.56

I think this is likely something new. Mine's tip a day was generated with quarto-1.0.37 fwiw.

Also visible on 
https://quarto.org/docs/extensions/

**Comment by cderv** [comment]
This comes from a patch in list.js that we imported in Quarto at https://github.com/quarto-dev/quarto-cli/commit/a2e298e001d66cc36be88ba9a7ec61238d80f3c8 for 1.5.4. It solves https://github.com/quarto-dev/quarto-cli/issues/8435 but too strong because it will remove the `toLowerCase()`

We need to patch `list.min.js` differently so that #8435 is still solved, but it does not break the search.

**Comment by dragonstyle** [comment]
![who](https://github.com/user-attachments/assets/556fb717-8f4c-4760-9af1-cb89c315c83c)
