### ISSUE TITLE
Conditional content visible for html appears in epub output format too

### ISSUE THREAD

**Issue by sebastiansauer** [quarto-dev/quarto-cli#10726]
### Bug description

Conditional content tagged as html output is not hidden but rendered in html output format.

### Steps to reproduce

`````
---
title: "Untitled"
format: epub
---

::: {.content-visible when-format="html"}

Will only appear in HTML.
::: 
 ``````

### Expected behavior

According to the [docs](https://quarto.org/docs/authoring/conditional.html#content-visible), content tagged as "conditional" should appear only in the respective output format:

````
::: {.content-visible when-format="html"}

Will only appear in HTML.

:::
````

### Actual behavior

However, the content also appears in epub output.

### Your environment

-IDE: RStudio 2024.04.2
- OS: mac Sonoma 14.6.1

### Quarto check output

Quarto 1.6.8
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.8
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/sebastiansaueruser/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /Users/sebastiansaueruser/.pyenv/versions/3.11.1/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/sebastiansaueruser/Rlibs
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
You can instead check negatively for `epub`, and that should work.

::: {.content-visible unless-format="epub"}

Will not appear in epub.
:::

**Comment by sebastiansauer** [comment]
It seems that it is currently not possible to conditionally render some content to epub only (see [this gist](https://gist.github.com/sebastiansauer/d63eb95288f71ec4e357c2a0997858b0)).

I think that being able to (positively) restrict rendering to epub would be worthwhile. My use case is this: I need to handle formulas different in html and epub, [as epub seem not to allow for custom colors in formulas](https://stackoverflow.com/questions/78954161/custom-colors-equation-in-epub-format-is-not-working/78954493#78954493).

**Comment by mcanouil** [comment]
It does work:

````qmd
---
title: "Quarto Playground"
format:
  epub: default
  html: default
---

:::: {.content-visible when-format="html" unless-format="epub"}
HTML content
::: 

:::: {.content-visible when-format="epub"}
EPUB content
::: 
````

**Comment by sebastiansauer** [comment]
Thank you for showing me.
