### ISSUE TITLE
PDF book: main authors are not inferred from `_quarto.yml` but from the last `.qmd` file

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-cli#1073]
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?

- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?

- [x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

- [x] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

## Issue

When creating a PDF with class `srcbook`, the main authors are not taken from `_quarto.yml` but instead from the last `.qmd` rendered.

## Reprex

1. Create book project via `quarto create-project mybook --type book`
2. Add the following header to `summary.qmd`
  ```
  ---
  author:
    - test
  ---
  ```
3. `quarto render --to pdf`

Now the author in the resulting pdf is "test" rather than "Jane Doe" (which is set in `_quarto.yml`).

## Metadata

```
quarto check

[✓] Checking Quarto installation......OK
      Version: 0.9.515
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13
      Path: /opt/homebrew/opt/python@3.9/bin/python3.9
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/pjs/Library/R/arm64/4.2/library
        - /opt/R/4.2.0-arm64/Resources/site-library
        - /opt/R/4.2.0-arm64/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

**Comment by jjallaire** [comment]
Thanks for reporting this! Should be fixed here https://github.com/quarto-dev/quarto-cli/commit/ee772857ac91ebe796a0ee2f45ed4913cd3bd1a5 and available in release v0.9.522: https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.522

**Comment by jjallaire** [comment]
I just realized that while this change fixes the title page author, it leaves the `author` specified within the chapter unrendered. @dragonstyle I think we will want to borrow from the code you created for markdown title block rendering here. Let's discuss realtime later today.

**Comment by pat-s** [comment]
Thanks, can confirm it works now! Honoring `author` fields within chapters would also be great. These work for me in HTML but not in PDF with v0.9.522 - but that was also the case before v0.9.522 AFAIR.

**Comment by jjallaire** [comment]
Yes, we are working on authors inside chapters right now.

**Comment by dragonstyle** [comment]
Ok this should be all set here:
4471ea29d13593ef40b322b53919bf5bbee58e36

I just started a fresh release build.

**Comment by pat-s** [comment]
Unfortunately chapter authors do not show up for me yet in v0.9.531 - in my case I am trying to add the following to `summary.qmd` file 

```yml
---
author:
  - test
---
```

which is references as


```yml
book:
  title: "mybook42"
  author: "Jane Doe"
  date: "6/6/2022"
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - summary.qmd
```

**Comment by dragonstyle** [comment]
Do you mind also giving this a try with latest? I am able to insert authors using just the syntax you specified above - they will appear beneath the title of the chapter (they get a minimal treatment). It could be my changes to title handling in the most recent commit this area fixed what you were seeing.

**Comment by pat-s** [comment]
With v0.9.533 all authors are missing now, i.e. the main book authors and chapter authors.

**Comment by niniack** [comment]
Authors are missing in v0.9.535 as well

**Comment by pat-s** [comment]
> Is that the project that is showing missing main authors?

Yes, just tried it with the `mybook` project. quarto 0.9.533

```yml
project:
  type: book

book:
  title: "mybook42"
  author: "Jane Doe"
  date: "6/6/2022"
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - summary.qmd
    - references.qmd
```

**Comment by dragonstyle** [comment]
Take 2 ( or 3 or 4!) - the latest release which is building now should have restored author functionality as well as per chapter author support in single file formats like PDF. Apologies for the bumps along the way, appreciate your help checking all of this!

**Comment by pat-s** [comment]
Confirmed in v0.9.545! Thanks for the quick fixes!
