### ISSUE TITLE
Notation for inline code not consistent

### ISSUE THREAD

**Issue by raffaem** [quarto-dev/quarto-cli#10748]
### What would you like to do?

Report an issue on quarto.org

### Description

[Here](https://quarto.org/docs/get-started/computations/rstudio.html#inline-code) it says that the notation for inline code is `` `{r} ` ``, but then later on it says:

> The average city mileage of the cars in our data is `r mean_cty` and the average highway mileage is `r mean_hwy`. 

Without the enclosing curly brackets

**Comment by raffaem** [comment]
It's actually documented in the footnote.

Maybe it's better to always use `` `{r} ` `` in the tutorial and leave the knitr syntax for the guide.

**Comment by cscheid** [comment]
Thanks for the suggestion, but the previous syntax is historically very popular and this is an intentional choice.
