### ISSUE TITLE
include-before-body inserts after title page, not after begim document environment

### ISSUE THREAD

**Issue by raffaem** [quarto-dev/quarto-cli#10759]
### Bug description

Hello Quarto devs!

For beamer, the [doc says](https://quarto.org/docs/reference/formats/presentations/beamer.html#includes) that the `include-before-body` option "Include contents [...] after [...] the \begin{document} command in LaTeX".

Where I interpret "after" to mean "right after".

Consider the following example:
```
---
title: "Title"
date: today
author: "Me"
format: 
  beamer:
    keep-tex: true
    include-before-body:
      text: "Hello"
---

# In the morning

## Getting up

Hi
```

If you inspect the generated tex file, you will find:

```
\begin{document}
\frame{\titlepage}
Hello
```

While it should be:
```
\begin{document}
Hello
\frame{\titlepage}
```

This is important as this option is used to adjust some settings and so must come right after `\begin{document}`

### Steps to reproduce

See above

### Expected behavior

See above

### Actual behavior

See above

### Your environment

RStudio 2024.04.2

### Quarto check output

```bash
✦ ❯ quarto check
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.5
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: ir, python3

(|) Checking Jupyter engine render....[IPKernelApp] WARNING | Config option `autoindent` not recognized by `ZMQInteractiveShell`.  Did you mean `autoawait`?
[✓] Checking Jupyter engine render....OK

Using 18 cores for parallelisation
[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/raffaele/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
The include before statement is inserted at the same place as the Pandoc's template 

- Pandoc's template: 	https://github.com/jgm/pandoc/blob/b02654948c50f2690a934377c848193e38a0240f/data/templates/default.latex#L551-L571
- Quarto's imported template 
	https://github.com/quarto-dev/quarto-cli/blob/cf0b7d06e67acb6180c822cc77e89cb936bb3c00/src/resources/formats/pdf/pandoc/template.tex#L423-L429

	the `\frame` part being inserted in this before body part
	https://github.com/quarto-dev/quarto-cli/blob/cf0b7d06e67acb6180c822cc77e89cb936bb3c00/src/resources/formats/pdf/pandoc/before-body.tex#L1-L15


So the issue you raises will require more example to understand the impact of this change. Right now, `include-before-body` means before the body part (but after frontmatter, title or abstract insertion). 
We can't change that easily. 

Note that, for your usage of `include-before-body`, you could also overwrite the `before-body.tex` partial to add your content where you need to exactly. 

- `include-before-body` is a feature from Pandoc which is based on its `include-before` variable. We would prefer keeping it at the same place as Pandoc's template is using it. (You could report to them too to see if they would change)
- `before-body.tex` partial is a Quarto feature to allow you customizing more precisely the template. See https://quarto.org/docs/journals/templates.html#template-partials

````yaml
format: 
  beamer:
    keep-tex: true
    template-partials: 
      - before-body.tex
````

And having the content modified or just tweaked from the partials 
```tex
Hello
$if(has-frontmatter)$
\frontmatter
$endif$
$if(title)$
$if(beamer)$
\frame{\titlepage}
$else$
\maketitle
$endif$
$if(abstract)$
\begin{abstract}
$abstract$
\end{abstract}
$endif$
$endif$
```

If this is common practice in beamer to insert some configuration right after `\begin{document}`, maybe it is worth adding a `after-begin.tex` template 🤔

**Comment by cscheid** [comment]
This all should happen upstream in the Pandoc template, right?

**Comment by raffaem** [comment]
I don't need  this  anymore. Will report upstream if I'll need it again.
