### ISSUE TITLE
Unable to install Quarto using Installation Setup wizard 

### ISSUE THREAD

**Issue by akshit113** [quarto-dev/quarto-cli#10771]
### Bug description

I am unable to install Quarto on my windows Desktop computer using Quarto Setup Wizard. I am being forced to remove the Quarto even when I am trying install Quarto and also don't have it on my computer https://quarto.org/docs/get-started/

### Steps to reproduce

Windows Desktop
Link: https://quarto.org/docs/get-started/
Version: 1.5.57
Date: August 29, 2024

### Expected behavior

should be able to install normally

### Actual behavior

being forced to remove Quarto from my computer
![1](https://github.com/user-attachments/assets/a0ac3fee-5ec5-4331-a286-b48970cead01)
![2](https://github.com/user-attachments/assets/aab01079-b372-44cb-8858-ce3ac32c20e9)
![3](https://github.com/user-attachments/assets/448f3c9a-3181-491e-bc0b-07d19d4950ea)

### Quarto check output

Output of `quarto check` on Windows Powershell:

**quarto** : The term 'quarto' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ quarto check
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (quarto:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by cderv** [comment]
> and also don't have it on my computer

Did you have it installed previously ? Or is this a brand new environment ? 

I wonder if there could be some leftover of a previous installation (like in Registry) that would make the installer think it is. 

Can you also check in Programs on your Windows menu to see if Quarto is there among installed app ? 
Asking in case you just check for `quarto check`. An installed app is not always findable on PATH. So better check this too. 

thanks

**Comment by akshit113** [comment]
Hi @cderv 

Thank you for responding. I found out that Quarto was indeed installed on my computer when I looked up on Windows Installed Apps. I uninstalled and re-installed the quarto. It is working as expected. 

Best wishes, 
Akshit
