### ISSUE TITLE
Aside links not working for PDF rendering

### ISSUE THREAD

**Issue by steamelephant** [quarto-dev/quarto-cli#1077]
Asides formatted using the very nice markdown link syntax `[An aside]{.aside} ` break the XeLaTeX stage of pdf rendering.

Rendering a file containing the following:
```
---
title: "Aside bug"
---

Some standard text. [An aside]{.aside}  
```

Works fine for HTML but gives 

```
compilation failed- error
Undefined control sequence.
l.151 Some standard text. {\marginnote
                                      {\begin{footnotesize}An 
``` 
after `quarto render --to pdf aside_bug.qmd`.

Updating the file to manually use the `marginnote` package  like this
```
---
title: "Aside bug"
format:
    pdf:
        include-in-header: 
            text: \usepackage{marginnote}
---

Some standard text. [An aside]{.aside}  
```
renders the aside in the existing margin. That is almost what I wanted, I would have liked the larger margin set when using `::: {.column-margin}`  but in contrast to the HTML rendering which now puts the de-emphasised text in between paragraphs.

It would be useful to me if this could

1. put the aside in the extended margin
2. do so without interrupting the flow of other paragraphs as `::: {.column-margin}` appears to, for example between bullet points. .

This is using 

- Quarto 0.9.520
- Ubuntu 20.04 in WSL2 on Windows 11
- TinyTex

The HTML behaviour appears to be changing. When I first ran into this problem `[An aside]{.aside} `  rendered `An aside` in the margin while `::: {.aside}`  put the aside between paragraphs in the main body. With this version both calls put the aside between paragraphs.

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [ x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [ x] included a minimal, self-contained, and reproducible example?

- [ x] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?

- [ x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?

- [ x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

- [ x] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by dragonstyle** [comment]
This should be resolved - thanks for catching it! As you expected, asides behavior should match `column-margin`. I didn't see any change in behavior with HTML - the aside might collapse between paragraphs when the viewport width gets small enough.
