### ISSUE TITLE
Conditional content with metadata variable and `#sol-` and `#rem-` doesn't render to pdf.

### ISSUE THREAD

**Issue by 314a** [quarto-dev/quarto-cli#10782]
### Bug description

There seems to be a `main.lua` filter issue with conditional content for cross-ref `#rem-` and `#sol-` .

Rendering a .qmd file with the following conditional (see below) and the metadata `solution: true` and `solution: false`  works fine for html output. It fails with `solution: false` and `format: pdf`.

```r
::: {#sol-example .content-visible when-meta="solution"}
Solution is visible if metadata element `solution: true`. (see @exr-example). 
:::
```

My current workaround is splitting the divs into two, which way less elegant.

```r
::: {.content-visible when-meta="solution"}
::: {#sol-example}
Solution is visible if metadata element `solution: true`. (see @exr-example). 
:::
:::
```

The problem only occurs for the prefix `#sol-`, `#rem-` and not for any of the other reserved prefixes such as `#exm`, `#exr`, `#rem`, `#def`, `#thm`.. (as listed in [Quarto Cross References](https://quarto.org/docs/authoring/cross-references.html#theorems-and-proofs))

### Steps to reproduce

File: exercise.qmd 
Rendering the following file with `quarto render exercise.qmd`

```r
---
title: "Conditional Solution Box"
solution: false
format: pdf
---
Show Solution: {{< meta solution >}}, see @exr-example and  @sol-example.

::: {#exr-example}
Exercise to test conditional boxes using metadata variable `solution`.
:::

::: {#sol-example .content-visible when-meta="solution"}
Solution is visible if metadata element `solution: true`. (see @exr-example). 
:::
```

### Expected behavior

A rendered pdf with a hidden `#sol-example` box.

### Actual behavior

Error message, when rendering the file to pdf:
```
Error running filter C:/Program Files/Quarto/share/filters/main.lua:
C:/Program Files/Quarto/share/filters/main.lua:22821: attempt to index a nil value (field 'integer index')
```

### Your environment

- IDE: RStudio 2024.04.2 Build 764
- OS: Win 11 23H2

### Quarto check output

```
Quarto 1.5.57
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.57
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.4.1
      Path: C:/PROGRA~1/R/R-44~1.1
      LibPaths:
        - D:/library/rpackages/4.4
        - C:/Program Files/R/R-4.4.1/library
      knitr: 1.48
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Conditional content should not be mixed with cross-reference div.
You have to nest the two.

**Comment by cscheid** [comment]
@mcanouil's suggestion should solve the problem. I'm going to go ahead and close this one.

**Comment by 314a** [comment]
While the nested approach works, it would be good that the behavior across cross references is consistent. Maybe this point is something to aid to the [overhaul list for Crossref](https://github.com/quarto-dev/quarto-cli/issues/4944)

Particularly, for exercise templates, it would be a nice feature to be able to conditionally turn solutions on/off with the reference to the exercise with cross-references. 
While this can be partly solved with custom .lua scripts, the appraoch with conditionals consistent in behaviour with the other crossref prefixes would be preferable.

**Comment by 314a** [comment]
I tested it for all the *reserved prefixes* listed in [Quarto Cross References](https://quarto.org/docs/authoring/cross-references.html#overview). That's why I thought it was a feature, even if it's not explicitly documented.
It works for all the *reserved prefixes* if rendered to html. In the case of rendering to pdf, there's a nul pointer error for the prefixes `#sol-` and `#rem-`, the rest is rendered without any issue.

```
---
title: "Conditional Content Test"
solution: false
format: pdf
---
::: {#sol-example .content-visible when-meta="solution"}
Replacing #sol-example with #exm-example, #exr-example, #def-example, #thm-example .... works.
:::
```
I will look into the mentioned discussions.
