### ISSUE TITLE
Quarto files getting corrupted when editing in VSCode

### ISSUE THREAD

**Issue by aaronschiff** [quarto-dev/quarto-cli#10788]
### Bug description

I'm experiencing a frustrating issue where certain actions cause unwanted changes to my Quarto documents in VSCode. Sometimes when I paste into a qmd file or save it, parts of the document will get changed or corrupted. I presume this is happening when the Quarto formatting is running. It does not happen on every paste or save, and I'm not sure exactly what condition triggers this, but it happens quite often for me. It does not happen with editing other types of code files in VSCode, so I guess is related to the Quarto extension. 

As an example, here is a screenshot of a freshly created qmd file: 

<img width="366" alt="Screenshot 2024-09-13 at 09 49 23" src="https://github.com/user-attachments/assets/d2e061c9-190c-4da3-9db9-625e4e234d2e">

Here's what happened when I pasted one line of code into the R code block: 

<img width="348" alt="Screenshot 2024-09-13 at 09 48 43" src="https://github.com/user-attachments/assets/a6ef6dec-5fa6-48e8-a2e3-7a8405fa9a79">

### Steps to reproduce

Create a qmd file in VSCode

Edit the file and paste into it or save it

Occasionally the problem described above occurs

### Expected behavior

Document contents would not get changed except for formatting

### Actual behavior

Some parts of the document are changed in inappropriate ways

### Your environment

- IDE: VSCode 1.93.1
- MacOS 14.6.1
- Quarto: 1.5.57
- Quarto VSCode extension 1.114.0

### Quarto check output

```bash
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/aaron/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.6
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in miniconda3. Did you forget to activate it?

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
You should check your settings as I and other are extensively using Quarto and VSCode and I never faced this.
Note also that this repository is about Quarto CLI not the VSCode extension.

Without clear steps to reproduce, I'm afraid there is not much we can do.

I suggest you disable all extensions you have and re-enable them one at a time starting with the Quarto VSCode extension.

**Comment by aaronschiff** [comment]
@mcanouil thanks for your help. After testing as you suggested, it appears to be some conflict between the Quarto extension and the REditorSupport extension, when editing R code blocks in a qmd file. With only one of those two extensions enabled, I don't see the issue. With both enabled (and all other extensions disabled), I see the issue I described. 

Apologies for posting in the wrong repo, I'll close it here and repost in the VSCode extension repo with these additional details.

**Comment by mcanouil** [comment]
Again, check your non default settings in those extensions.

**Comment by aaronschiff** [comment]
@mcanouil thanks again, the only extension settings I have changed from the defaults are the spellcheck language for Quarto and to enable radian terminal and Httpgd in REditorSupport. After changing those back to defaults, I still have the issue. I created a new issue in the extension repo.
