### ISSUE TITLE
quarto x stargazer label cross reference

### ISSUE THREAD

**Issue by huizezhang-sherry** [quarto-dev/quarto-cli#10783]
### Bug description

It seems that the quarto cross reference style, using "-", is not compatible with the `stargazer::stargazer()` label format. 

When using `label = "tbl-mod-output"` in `stargazer()`, it will print the little Latex code `[H]` before the table. I've played around with different `table.placement` arguement and used the chunk option `results: "asis"` but still can't get rid of it. 

When using a label without "-" will remove the Latex `[H]` but the quarto cross reference no longer works. 

When using the quarto chunk option label to add the label for reference, it seems to create a separate table header (Table 3 in the following code) and Table 4, still with `[H]`. 

### Steps to reproduce

````qmd
---
title: My example
format: pdf
header-includes:
   - \usepackage{float} 
---

this is the cross reference to @tbl-mod-output, this is the second try cross reference to @modoutput, and this is the third try with quarto chunk option label to reference @tbl-mod-output2.

```{r}
#| results: "asis"
mod1 <- lm(mpg ~ wt + hp, data = mtcars)
stargazer::stargazer(
  mod1, header = FALSE, label = "tbl-mod-output",
  table.placement = "H", 
  title = "this is my fancy caption")
```

```{r}
#| results: "asis"
mod1 <- lm(mpg ~ wt + hp, data = mtcars)
stargazer::stargazer(
  mod1, header = FALSE, label = "modoutput",
  table.placement = "H", 
  title = "this is my fancy caption")
```


```{r}
#| results: "asis"
#| label: tbl-mod-output2
mod1 <- lm(mpg ~ wt + hp, data = mtcars)
stargazer::stargazer(
  mod1, header = FALSE, 
  table.placement = "H", 
  title = "this is my fancy caption")
```

````

### Quarto check output

Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/xxx/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Could you properly format your post using code blocks for code and terminal outputs? Thanks.
If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.
See <https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us>.

**Comment by huizezhang-sherry** [comment]
done

**Comment by mcanouil** [comment]
Here is what you should do:

````qmd
---
title: My example
format: pdf
execute:
  echo: false
  message: false
  warning: false
---

this is the cross reference to @tbl-mod-output.

```{r}
#| label: tbl-mod-output
#| tbl-cap: this is my fancy caption
#| output: asis
stargazer::stargazer(
  lm(mpg ~ wt + hp, data = mtcars),
  header = FALSE,
  table.placement = "H",
  float = FALSE
)
```
````
