### ISSUE TITLE
Snapdragon architecture on windows causes trouble

### ISSUE THREAD

**Issue by wesleyburr** [quarto-dev/quarto-cli#10781]
### Bug description

**Context**: student's laptop, standard Windows 10 install **with Powershell installed.** Installed R-4.4.1 fresh, then RStudio, then Quarto-cli. In RStudio terminal, ran `quarto install tinytex` to get a tex distribution sorted. Via R (terminal, administrator console), `install.packages("rmarkdown")`. 

Renders fail if there is any `R` code in the `.qmd` file. Did some digging. quarto-cli couldn't find `Rscript.exe`. Added it to the system PATH, tested, can see `RScript` now. 

Turned on debug mode in for `quarto-cli`. Ran `quarto check`. Everything passed until the `knitr` check (provided below). 

**But** if we run `Rscript C:\Program Files\Quarto\share\capabilities\knitr.R` there is no error, there is no failure. It just returns the YAML chunk listed above as stdout, but nothing else seems to pop up.

Any idea what's going on and why the `quarto-cli` can't successfully test itself against `knitr.R`?

(Note: tested packages installed in User local library and system library, same error message, so it's not something weird with the path or location of the user library, which is actually currently empty because I manually torched it)

### Expected behavior

If Rscript is on the path, it should run the check successfully. 

### Actual behavior

Unknown what this error is and why it is pulling an error code while trying to test against `knitr.r`.

### Your environment

- Windows 10 with Powershell
- R 4.4.1
- RStudio Version: 2024.04.2+764
- Quarto-cli 1.5.57

### Quarto check output

> -- Searching for R binary --
Looking for 'Rscript' in QUARTO_R: undefined
Looking for 'Rscript' in R_HOME: undefined
Looking for 'Rscript' in PATH.
[execProcess] CMD /C where Rscript
(|) Checking R installation...........[execProcess] Success: true, code: 0
Found in PATH at C:\Program Files (x86)\R\R-4.4.1\bin\Rscript.exe
[execProcess] C:\Program Files (x86)\R\R-4.4.1\bin\Rscript.exe --version
[execProcess] Success: true, code: 0
> 
> ++R found at C:\Program Files (x86)\R\R-4.4.1\bin\Rscript.exe is working.
> -- Checking knitr engine capabilities --
> [execProcess] C:\Program Files (x86)\R\R-4.4.1\bin\Rscript.exe C:\Program Files\Quarto\share\capabilities\knitr.R
> (/) Checking R installation...........[execProcess] Success: false, code: -1073741569
> 
> ++ Problem with results of knitr capabilities check.
>     Return Code: -1073741569 (success is false)
>     with stdout from R:
> --- YAML_START ---
> versionMajor: 4
> versionMinor: 4
> versionPatch: 1
> home: C:/PROGRA~2/R/R-44~1.1
> libPaths:
>   - "C:/Program Files (x86)/R/R-4.4.1/library"
> packages:
>   knitr: "1.48"
>   rmarkdown: "2.28"
> --- YAML_END ---
> 
> [>] Checking R installation...........(None)
> 
> R succesfully found at C:\Program Files (x86)\R\R-4.4.1\bin\Rscript.exe.
> However, a problem was encountered when checking configurations of packages.
> Please check your installation of R.
> 
> [NotebookContext]: Starting Cleanup

**Comment by cderv** [comment]
Thanks for the report. I don't really what the cause could be. An error at this step of the check means that somehow running `Rscript` ended up in an error, but 

- `stdout` is correct
- no `stderr` from R process itself

So it seems like a crash. 

A quick google search leads me to https://forum.posit.co/t/error-when-opening-rstudio-with-64-bit-r-on-parallels-arm-windows-10/132063

It seems switching from 64 to 32 binary solved is. Other occurrence of this error code leads to `STATUS_BAD_FUNCTION_TABLE` in Windows (0xC00000FF hexa version) in https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55

Something specific to your environment is creating the issue with running R, which seems to happen only when it is run by another tool (since calling RScript works ok in terminal directly)

🤔 I don't know much how to help more. We'll need to wait for more report of this with more information unfortunately

**Comment by wesleyburr** [comment]
That's a really great suggestion to get me started, thank you. It's such a weird error, just needed a lever to start. I'll do the 32-bit variant. It's entirely possible this is Windows 10 on an ARM architecture and I just didn't notice! Not my computer, so not on my radar.

**Comment by wesleyburr** [comment]
Unfortunately, the 32-bit variant solution does not work. And neither does using the experimental aarch64 option.

So this is generally going to be a bug until R-4.?.? is fully supported on this architecture and we start regularly testing R and packages against it. R runs on the architecture via emulation ok, and can run code in its own environment - and RStudio will happily send chunks to this console and everything is good. But anything from the command line using Rbatch is going to break, which eliminates the ability to Render knitr/rmarkdown/quarto documents.

For now I'm redirecting all my students with these fancy new Microsoft Surface tablets (with the Qualcomm Snapdragon processors) to use my cloud-based Jupyter Hub option. If you want a reproduction on it, @cscheid, that seems to be the way to go - need access to such an architecture, and it should be straightforward to make it crash the same way. 

(they are these things: https://www.qualcomm.com/products/mobile/snapdragon/laptops-and-tablets/laptop-device-finder/microsoft-surface-pro)

**Comment by cderv** [comment]
> But anything from the command line using Rbatch is going to break, which eliminates the ability to Render knitr/rmarkdown/quarto documents.

Are you saying that outside of Quarto context, anything you run with `Rscript` command line is not working ? It would mean that it is not just how quarto is calling `Rscript`. 

Just to confirm I am correctly understanding your conclusion.

**Comment by wesleyburr** [comment]
Not quite. Maybe? Some stuff works, some stuff doesn't. 

Me running `Rscript C:\Program Files\Quarto\share\capabilities\knitr.R` from the terminal **seems** to complete ok. It **may** be crashing, but it just returns the YAML.

Quarto running what seems to be the same command returns an error. 

Sorry I can't be more precise - I'm a bit in the dark testing the method myself vs. pulling the Quarto verbose debug. On a computer that isn't mine.

**Comment by cderv** [comment]
> Quarto running what seems to be the same command returns an error.

Yeah, it could also be a Deno problem on this environment if this is really a specific architectur. Quarto will run `Rscript` from Deno. 

So advanced testing would need to try debug in such environment and see if Deno has trouble running such command (getting stderr and stdout). 

Somehow running `C:\Program Files (x86)\R\R-4.4.1\bin\Rscript.exe C:\Program Files\Quarto\share\capabilities\knitr.R` but `stdout` is ok, and no `stderr` is returned. 

So something like a R crash when existing. Really hard for us to debug this without being able to access a reproducible environment... 😞

**Comment by wesleyburr** [comment]
Architecture bugs are hard! I assume this is all going to be fixed with the aarch64 work on R-Core ... eventually. Until then, unless you folks have access to a hardware budget to buy for testing, you're stuck, I get that. Flag it as a long-term bug on the Snapdragon architecture, and leave it for now, maybe?

**Comment by cscheid** [comment]
> Flag it as a long-term bug on the Snapdragon architecture, and leave it for now, maybe?

Just to clarify: we don't officially support architectures other than the ones in our [releases](https://github.com/quarto-dev/quarto-cli/releases). So this isn't really a bug. It's unfortunate, but we can't promise support for every architecture/OS combination out there.

**Comment by remlapmot** [comment]
In case of interest, I believe I have found the cause of this error.

There are (at least) 4 R packages which when loaded in an x86 R session under the Windows 11 on ARM x86 emulation cause the session to exit with a non-zero exit code. Unfortunately rmarkdown and htmltools are 2 of these packages, and so `quarto render` using the knitr engine can't complete for x86 R; and nor can `quarto check knitr` (which also loads rmarkdown).

Fuller explanation here <https://github.com/rstudio/rstudio/issues/15277#issuecomment-3324415176>

There are several workarounds.

* on Windows 11 on ARM x86 Quarto runs Windows AARCH64 R without problems.
* on Windows 11 on ARM x86 Quarto's jupyter engine seem to run the x86 `ir` kernel from the IRkernel R package in x86 R without problems.

**Comment by cderv** [comment]
Thanks for sharing @remlapmot ! 

I am curious what is causing **htmltools** and **rmarkdown** to fails. If we can help fix something in those packages I am happy to. 

> on Windows 11 on ARM x86 Quarto runs Windows AARCH64 R without problems.

It seems a better solution to run `Windows AARCH64 R` on Windows 11 ARM x86 though, right? 

Anyhow, glad we got to the bottom of this

**Comment by remlapmot** [comment]
Yes certainly for use with Quarto in the Terminal it seems to be totally reliable to use AARCH64 R (it's just people have to wait for their R packages to build from source), or x86 R through `jupyter: ir` appears to run x86 R without problems (which is surprising to me given this non-zero exit code issue I've found).

But for users with Windows 11 on Arm you'll have quite a few users on x86 R because that's the only one which works with RStudio Desktop.

My guess is that the problem is something to do with the compiled x86 machine code in the C/C++ code in possibly all or some of htmltools, cli, and rlang. I have some evidence this is the case below.

In my original tests I installed binary x86 packages from CRAN, so I have tried to rebuild all the offending packages from source under emulation to see if that gives a different outcome.

* **Partial success**: I can get rlang to build from source; which then gives an Rscript exit code of 0 (whereas its binary version from CRAN didn't). Using this version of rlang allows htmltools to compile from source and also give an Rscript exit code of 0 (which again the CRAN binary didn't).
* **Bad news**: I cannot get the cli package to build from source under emulation. With R 4.5.1 and 4.4.2 the building of the machine code seems to compile but then the loading of the package mysteriously fails at what appears to be the last step of the process.
  ```
  installing to C:/Program Files (x86)/R/R-4.4.2/library/00LOCK-cli/00new/cli/libs/x64
  ** R
  ** exec
  ** inst
  ** byte-compile and prepare package for lazy loading
  ** help
  *** installing help indices
  *** copying figures
  ** building package indices
  ** testing if installed package can be loaded from temporary location
  ERROR: loading failed
  ```

  I don't know to debug this further.

So my opinion is that unless we can get the cli package to build under x86 emulation on Windows 11 for Arm I believe that we can't solve this for the knitr engine for x86 R.

In case anyone has any insight, I have put my full output from the failed cli building from source below.

<details>
<summary>Log of failed cli install from source in x86 R 4.4.2</summary>

```
trying URL 'https://cloud.r-project.org/src/contrib/cli_3.6.5.tar.gz'
Content type 'application/x-gzip' length 640240 bytes (625 KB)
==================================================
downloaded 625 KB
* installing *source* package 'cli' ...
** package 'cli' successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: 'gcc.exe (GCC) 13.3.0'
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c ansi.c -o ansi.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c cleancall.c -o cleancall.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c diff.c -o diff.o
diff.c: In function 'clic_diff_chr':
diff.c:104:3: warning: 'sn' may be used uninitialized [-Wmaybe-uninitialized]
  104 |   SET_VECTOR_ELT(result, 0, allocVector(INTSXP, sn));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
diff.c:85:7: note: 'sn' was declared here
   85 |   int sn;
      |       ^~
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c errors.c -o errors.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c glue.c -o glue.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c init.c -o init.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c inst.c -o inst.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c keypress-unix.c -o keypress-unix.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c keypress-win.c -o keypress-win.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c keypress.c -o keypress.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c md5.c -o md5.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c progress-altrep.c -o progress-altrep.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c progress.c -o progress.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c sha1.c -o sha1.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c sha256.c -o sha256.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c thread.c -o thread.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c tty.c -o tty.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c utf8.c -o utf8.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c utils.c -o utils.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c vt.c -o vt.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c vtparse.c -o vtparse.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c vtparse_table.c -o vtparse_table.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c win-utf8.c -o win-utf8.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c winfiles.c -o winfiles.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c xxhash.c -o xxhash.o
gcc  -I"C:/PROGRA~2/R/R-44~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c xxhash2.c -o xxhash2.o
gcc -shared -s -static-libgcc -o cli.dll tmp.def ansi.o cleancall.o diff.o errors.o glue.o init.o inst.o keypress-unix.o keypress-win.o keypress.o md5.o progress-altrep.o progress.o sha1.o sha256.o thread.o tty.o utf8.o utils.o vt.o vtparse.o vtparse_table.o win-utf8.o winfiles.o xxhash.o xxhash2.o -lpthread -Lc:/rtools44/x86_64-w64-mingw32.static.posix/lib/x64 -Lc:/rtools44/x86_64-w64-mingw32.static.posix/lib -LC:/PROGRA~2/R/R-44~1.2/bin/x64 -lR
installing to C:/Program Files (x86)/R/R-4.4.2/library/00LOCK-cli/00new/cli/libs/x64
** R
** exec
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
ERROR: loading failed
* removing 'C:/Program Files (x86)/R/R-4.4.2/library/cli'
The downloaded source packages are in
	'C:\Users\runneradmin\AppData\Local\Temp\RtmpCgtGrQ\downloaded_packages'
```

</details>

<details>
<summary>Log of failed cli install from source in x86 R 4.5.1</summary>

```
trying URL 'https://cloud.r-project.org/src/contrib/cli_3.6.5.tar.gz'
Content type 'application/x-gzip' length 640240 bytes (625 KB)
==================================================
downloaded 625 KB
* installing *source* package 'cli' ...
** this is package 'cli' version '3.6.5'
** package 'cli' successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: 'gcc.exe (GCC) 14.2.0'
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c ansi.c -o ansi.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c cleancall.c -o cleancall.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c diff.c -o diff.o
diff.c: In function 'clic_diff_chr':
diff.c:104:3: warning: 'sn' may be used uninitialized [-Wmaybe-uninitialized]
  104 |   SET_VECTOR_ELT(result, 0, allocVector(INTSXP, sn));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
diff.c:85:7: note: 'sn' was declared here
   85 |   int sn;
      |       ^~
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c errors.c -o errors.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c glue.c -o glue.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c init.c -o init.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c inst.c -o inst.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c keypress-unix.c -o keypress-unix.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c keypress-win.c -o keypress-win.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c keypress.c -o keypress.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c md5.c -o md5.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c progress-altrep.c -o progress-altrep.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c progress.c -o progress.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c sha1.c -o sha1.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c sha256.c -o sha256.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c thread.c -o thread.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c tty.c -o tty.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c utf8.c -o utf8.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c utils.c -o utils.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c vt.c -o vt.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c vtparse.c -o vtparse.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c vtparse_table.c -o vtparse_table.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c win-utf8.c -o win-utf8.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c winfiles.c -o winfiles.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c xxhash.c -o xxhash.o
gcc  -I"C:/PROGRA~2/R/R-45~1.1/include" -DNDEBUG -I../inst/include    -I"C:/rtools45/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c xxhash2.c -o xxhash2.o
gcc -shared -s -static-libgcc -o cli.dll tmp.def ansi.o cleancall.o diff.o errors.o glue.o init.o inst.o keypress-unix.o keypress-win.o keypress.o md5.o progress-altrep.o progress.o sha1.o sha256.o thread.o tty.o utf8.o utils.o vt.o vtparse.o vtparse_table.o win-utf8.o winfiles.o xxhash.o xxhash2.o -lpthread -LC:/rtools45/x86_64-w64-mingw32.static.posix/lib/x64 -LC:/rtools45/x86_64-w64-mingw32.static.posix/lib -LC:/PROGRA~2/R/R-45~1.1/bin/x64 -lR
installing to C:/Program Files (x86)/R/R-4.5.1/library/00LOCK-cli/00new/cli/libs/x64
** R
** exec
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
ERROR: loading failed
* removing 'C:/Program Files (x86)/R/R-4.5.1/library/cli'
The downloaded source packages are in
	'C:\Users\runneradmin\AppData\Local\Temp\RtmpWqGIbj\downloaded_packages'
Warning message:
In install.packages("cli", repos = "https://cloud.r-project.org/",  :
  installation of package 'cli' had non-zero exit status
```

</details>

**Comment by cderv** [comment]
> But for users with Windows 11 on Arm you'll have quite a few users on x86 R because that's the only one which works with RStudio Desktop.

Oh thanks. I understand https://github.com/rstudio/rstudio/issues/15277 better know - we need to follow closely the discussion their. 

To note also that Quarto relies on other tools, and some like Deno is not yet available on ARM windows
- https://github.com/denoland/deno/issues/8422

So it is not just R and RStudio problem at the end.

**Comment by cderv** [comment]
Quick update for reference: 
- https://github.com/denoland/deno/pull/31917
