### ISSUE TITLE
FOOTNOTE TITLE

### ISSUE THREAD

**Issue by SuzannePAYET** [quarto-dev/quarto-cli#10791]
### What would you like to do?

Give feedback or suggest an improvement

### Description

Hello, I'am Suzanne PAYET.
I'm french, working for Insee.
How to do to put a title at a foonote, please ?
Thank you.

**Comment by mcanouil** [comment]
Please, use GitHub Discussion to ask question. Thank you.
See the documentation about footnotes: https://quarto.org/docs/authoring/markdown-basics.html#footnotes

Note that, it's very unclear what a "title" is for a footnote.
