### ISSUE TITLE
Install Quarto Windows MSI file at command line silently (for scripting)

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#108]
cc @dragonstyle as discussed. 

Here is what I have tried 

````powershell
# gh auth must be setup
gh release download --repo quarto-dev/quarto-cli --pattern '*.msi' v0.2.144

# will install interactively with user interaction
msiexec /i "quarto-0.2.144-win.msi"

# will suppress the interaction but some windows open
msiexec /i "quarto-0.2.144-win.msi" /passive

# using quiet mode does not seem to work
msiexec /i "quarto-0.2.144-win.msi" /quiet

# using special /qn flag either
msiexec /i "quarto-0.2.144-win.msi" /qn
````

I don't really know what is supposed to work to install silently on Windows. Are all the usual flag from MSI activated in this bundle ? 

I found this while working on https://github.com/quarto-dev/quarto-actions/tree/main/install-quarto, as I tried to install Quarto MSI release on Windows GHA runner and I had trouble with it. 

Simple test tried on GHA:
* Workflow file: https://github.com/cderv/test-actions/actions/runs/1217636260/workflow
* `quarto` not found but not issue at installation - it seems it is doing nothing: https://github.com/cderv/test-actions/runs/3557169919?check_suite_focus=true

It could be interesting to check that the MSI file can be installed remotely using script. Downloading the release file and installing it on GHA windows runner seems the usual way forward.

How can we install MSI bundle on remote windows host like GHA runner ?

<details>
<summary>About the new  `quarto-dev/quarto-actions/install-quarto` </summary>

For the sake of a working action on all OS, I ended using Scoop to install the binary from [r-bucket](https://github.com/cderv/r-bucket). Scoop does not seem to have issue with the MSI, but maybe because it 'unbundles' it and not really install it. 
So for now, new action `quarto-dev/quarto-actions/install-quarto` is working, but with delay for the availability of the release in the scoop bucket compared to Github release here. I could probably improve this with an action in this repo that would trigger the update of the manifest in the bucket.

Also, for GHA, Windows runner have Chocolatey package manager installed by default. Maybe offering a quarto bundle in Chocolatey would be interesting. It would help for Github action but with the same drawback as current scoop bucket.

</details>

**Comment by dragonstyle** [comment]
The issue is that the installation defaults to machine wide by default and without UI, we can't request elevation (so the silent install fails). It should work under two conditions:

1) From an elevated prompt. just using `msiexec /I quarto.msi` should work since it won't need to prompt for elevation. This will install machine wide.

2) The command `msiexec /i quarto-<x>-win.msi ALLUSERS=2 MSIINSTALLPERUSER=1` will install silently per user.

**Comment by cderv** [comment]
> The command msiexec /i quarto-<x>-win.msi ALLUSERS=2 MSIINSTALLPERUSER=1 will install silently per user.

That is probably what I was missing. I am not sure what I missed and why I did not test that... 🤔 Maybe I did. 

We'll see if I can use our MSI instead of Scoop in the quarto-actions now

**Comment by cderv** [comment]
> we can't request elevation (so the silent install fails)

Just to complete my OP - this was mainly in the context of Github action to use our MSI for `install-quarto` action. 

Github action windows runner are running in Admin mode, and with UAC disabled (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#administrative-privileges). So the UAC prompt should not be a problem. 

That is what I was expecting the usual silent flag for MSI to work. 

Anyhow, I'll try again

**Comment by dragonstyle** [comment]
Interesting - I actually can't explain why that would be failing, though perhaps this will still resolve it. Would be interesting to know why, if this worked, as I agree this shouldn't really change things unless ALLUSERS installs are simply not supported on GH runners.
