### ISSUE TITLE
Incorrect heading level for third publishing option?

### ISSUE THREAD

**Issue by jpierkunke** [quarto-dev/quarto-cli#10802]
### What would you like to do?

Report an issue on quarto.org

### Description

The beginning of the page at Guide > Publishing > GitHub Pages ([linked here](https://quarto.org/docs/publishing/github-pages.html)) outlines three methods, but it seems like the [third method (GitHub Action)](https://quarto.org/docs/publishing/github-pages.html#github-action) is nested under the second method (Publish command). Perhaps this is because it involves the publish command as well, but it might be clearer to indicate which sections are the start of each method.  Thank you for this helpful documentation!

**Comment by cderv** [comment]
Thanks !
