### ISSUE TITLE
GitHub markdown alerts being escaped

### ISSUE THREAD

**Issue by lucaspar** [quarto-dev/quarto-cli#10815]
### Bug description

[GitHub markdown alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) in a `.qmd` file seem to be escaped, causing an incorrect rendering:

```qmd
> [!NOTE]
> Useful information that users should know, even when skimming content.
```

is transformed into the following `.md`:

```md
> \[!NOTE\] Useful information that users should know, even when
> skimming content.
```

which causes the corresponding GitHub markdown to render incorrectly.

I'm reporting this bug more for documentation / discussion purposes. Adopting this feature could be out of scope for `qmd`, in which case it could be marked as e.g. `wontfix`.

### Expected behavior

Do not escape the alert blockquote indicator, i.e.:

```md
> [!NOTE]
> Useful information that users should know, even when
> skimming content.
```

### Quarto check output

```bash
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

```

**Comment by cderv** [comment]
The GFM syntax is not valid in a .qmd source which follows Pandoc's Markdown syntax and some of its variant. 

When you need to use raw output content in source, you should use raw blocks, like when including html for HTML output or latex markup for pdf output. See https://quarto.org/docs/authoring/markdown-basics.html#raw-content

````markdown

```{=gfm}
> [!NOTE]
> Useful information that users should know, even when skimming content.
```

````

You could also just use Quarto callout syntax which will output the right markup when using `format: gfm`

````markdown
---
format: gfm
---

::: {.callout-note}
Useful information that users should know, even when skimming content.
:::
````

This is available since Quarto 1.4

Hope this helps

**Comment by mcanouil** [comment]
This has already been discussed.
Quarto uses a more broad implementation.

````qmd
---
title: "Quarto Playground"
format: gfm
---

::: {.callout-caution}
This is a caution callout
:::
````

which will produce:

```md
# Quarto Playground


> [!CAUTION]
>
> This is a caution callout
```

**Comment by lucaspar** [comment]
@cderv that is certainly helpful, thanks for pointing out the raw content mode.
