### ISSUE TITLE
`linestretch` option must be a string instead of a numeric

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-cli#1081]
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?

- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?

- [x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

- [x] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

## Issue

The `linestretch` options described in https://quarto.org/docs/output-formats/html-themes.html#basic-options must be a string, not a numeric.

## Reprex

```
format:
  html:
    linestretch: 2 # causes error, must be a string
```

causes

```
In file book/_quarto.yml
(line 104, columns 18--21) Key linestretch has value 1.7, which must be a string
104:     linestretch: 1.7
                      ~~~
✖ The value 1.7 is number.
ℹ The error happened in location format:html:linestretch.
```

**Comment by pat-s** [comment]
Additional issue: somehow only integer values have an effect, i.e. `"2"` or `"3"` - values like `"1.4"` are changed into the nearest integer, e.g. `"1"`.

**Comment by dragonstyle** [comment]
I just updated our validation to permit unitless numbers - can you give it another try in the latest release? (should be ready in a few minutes).

Thanks for finding and reporting!

**Comment by pat-s** [comment]
Works in v0.9.533!

**Comment by ramiromagno** [comment]
The example provided here: https://quarto.org/docs/output-formats/html-themes.html#basic-options needs to be updated.

**Comment by dragonstyle** [comment]
What needs to be updated? I think it should be the case that unitless numbers are properly supported.
