### ISSUE TITLE
Dark theme doesn't respect the layering order of the stylesheets

### ISSUE THREAD

**Issue by nsarang** [quarto-dev/quarto-cli#10817]
### Bug description

`boostrap-dark.min.css` doesn't follow the layering order specified in the [documentation](https://quarto.org/docs/output-formats/html-themes-more.html). At the end of the css file, you can find quarto related styles such as `quarto-title-banner`, `quarto-title`, `#title-block-header`, etc which should come before the user-specified styles, not after. Note that this is only an issue with the Dark theme.

### Steps to reproduce

**_quarto.yml**
```
project:  
    type: website

website:
  title: "test2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light:
        - cosmo
        - custom.css
      dark: 
        - darkly
        - custom.css
    toc: true
```

**custom.css**
```
/*-- scss:rules --*/

.custom-style {
    color: red;
}
```

### Expected behavior

**boostrap-dark.min.css**
```
[ bootstrap styles ]

...

.custom-style {
    color: red;
}
```

### Actual behavior

**boostrap-dark.min.css**
```
[ bootstrap styles  - part 1 ]

...

.custom-style {
    color: red;
}

[ bootstrap styles  - part 2 ]

.quarto-title-banner {
    margin-bottom: 1em;
    color: #dee2e6;
    background: #375a7f
}

.quarto-title-banner a {
    color: #dee2e6
}

...

.quarto-title-tools-only {
    display: flex;
    justify-content: right
}
```

### Your environment

- IDE: VSCode 1.92.2
- OS: macOS Sonoma 14.3

### Quarto check output

```
Quarto 1.5.55
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.55
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)
```

**Comment by mcanouil** [comment]
Could you clarify the steps to reproduce and ensure your files are valid?
Also, why are you using CSS files when SCSS files are expected?

**Comment by nsarang** [comment]
@mcanouil 
> Could you clarify the steps to reproduce and ensure your files are valid?
1. Create an empty website project  
2. Use the given `_quarto.yml` configuration
3. Create a `custom.css` file in the root directory with the given content
4. Inspect `_site/site_libs/bootstrap/bootstrap-dark.min.css`
> Also, why are you using CSS files when SCSS files are expected?

The choice of extension doesn't make a difference in the reproducibility. As you can see the content is in SCSS.

**Comment by mcanouil** [comment]
Your files are still not valid: the square brackets and ellipses are no (S)CSS.
Please, make sure we can use your code as is.
Also, is a website project really needed? I believe a simple document should exhibit the issue if there is one.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by nsarang** [comment]
I'm not sure why you're looking for a document to reproduce, when the bug exists in the generated bootstrap.css. Given the simple instructions I provided, it'd take you at most two minutes to reproduce this.

> Your files are still not valid: the square brackets and ellipses are no (S)CSS.

Feel free to rename `custom.css` to `custom.scss` and it'll still reproduce the same problem.

**Comment by mcanouil** [comment]
Sorry, it was not very clear especially since the code provided does not really exhibit a visual issue.

See an example below of the issue for dark theme.

https://github.com/user-attachments/assets/9316d426-2c18-4a6e-a110-a113acdc5250


````qmd
---
title: "Quarto Playground"
format:
  html:
    theme:
      light:
        - cosmo
        - style.scss
      dark: 
        - darkly
        - style.scss
---

This is a playground for [Quarto]{.custom-style}.

{{< lipsum 1 >}}

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}
````

````scss
/*-- scss:defaults --*/

/*-- scss:rules --*/
.quarto-title-banner {
  margin-bottom: 1em;
  color: #dee2e6;
  background: red;
}
````

**Comment by nsarang** [comment]
My apologies on the confusion. I jumped straight into the fact that the order of "/*-- scss:rules --*/" in `bootstrap-dark.min.css` is incorrect.

**Comment by mcanouil** [comment]
> My apologies on the confusion. I jumped straight into the fact that the order of "/_-- scss:rules --_/" in `bootstrap-dark.min.css` is incorrect.

Which is true, so no need to apologise.

**Comment by cderv** [comment]
Thanks for the report. It seems this is indeed wrong 

- We add the layer after user provided one.
	https://github.com/quarto-dev/quarto-cli/blob/ee16c2e1e115411c8165cdfad4496b7b59227247/src/format/html/format-html-scss.ts#L416-L420

- while for light theme do use `unshift` now
	https://github.com/quarto-dev/quarto-cli/blob/ee16c2e1e115411c8165cdfad4496b7b59227247/src/format/html/format-html-scss.ts#L405-L406


and we should do same fix that was done some time ago by @dragonstyle at https://github.com/quarto-dev/quarto-cli/commit/b7a5449b210302a96952cadb5469dbf30e6db375 by using `.unshift()`
