### ISSUE TITLE
Lines containing, but not starting, with "#| echo: fenced" are omitted

### ISSUE THREAD

**Issue by debruine** [quarto-dev/quarto-cli#10821]
### Bug description

This is a tiny minor bug, but if you try to include the text `#| echo: fenced` in a fenced figure caption, that doesn't show up! (I found this while writing the quarto chapter of my MSc methods textbook). 

I assume you just need to add regex to only omit lines that **start** with `#| echo: fenced`

### Steps to reproduce

```` qmd
```{r}
#| echo: fenced
#| label: fig-demo
#| fig-cap: "fig-cap is invisible if it contains `#| echo: fenced`"

hist(rnorm(100000))
```
````

### Expected behavior

The figure caption line should show in the code block

### Actual behavior

The fig-cap line does not show

### Your environment

- IDE: RStudio 2023.06.0+421
- quarto: 1.5.57
- R version 4.2.1 (2022-06-23)

### Quarto check output

Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/lisad/Library/TinyTeX/bin/universal-darwin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Users/lisad/.virtualenvs/r-reticulate/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
I cannot reproduce on the current development version.


<img width="1624" alt="image" src="https://github.com/user-attachments/assets/7db95796-6620-4705-a008-c152c094cdfd">

**Comment by debruine** [comment]
@mcanouil You did reproduce it. The code chunk has the label line, but not the fig-cap line

**Comment by mcanouil** [comment]
How you meant, it's not in the echoed code cell.

**Comment by debruine** [comment]
Super-niche bug, I know

**Comment by debruine** [comment]
I hacked a fix like I describe here: https://github.com/quarto-dev/quarto-cli/discussions/3554#discussioncomment-10670349

**Comment by cscheid** [comment]
The `echo: fenced` removal is indeed super hacky on our side, and it'll be a long time before we can make it perfect. Nevertheless, we should only be a little more defensive and only pluck the lines that have no other content.

**Comment by cscheid** [comment]
FYI the specific line at play is this one:

https://github.com/quarto-dev/quarto-cli/blob/084df08d4e34dd1416d7e575663e092e5f8ec095/src/resources/rmd/hooks.R#L465

**Comment by cscheid** [comment]
In Jupyter, it seems that `echo: fenced` only reproduces the code fence but not any of the YAML options.

**Comment by cscheid** [comment]
In addition, we _also_ seem to be stripping `echo: fenced` from Jupyter cells too aggressively:

````
---
title: issue-10821
format: html
_quarto:
  tests:
    html:
      ensureHtmlElements:
        - []
        - []
---

```{python}
#| echo: fenced
#| label: fig-1
#| fig-cap: "This figure will have 'echo: fenced' in its caption."
import matplotlib.pyplot as plt
plt.plot([1,2,3])
```
````

<img width="1059" alt="image" src="https://github.com/user-attachments/assets/4d5e4b75-c8b0-4108-9ef9-c50d5897580e">

**Comment by cscheid** [comment]
In contrast,

````
---
title: issue-10821
format: html
_quarto:
  tests:
    html:
      ensureHtmlElements:
        - []
        - []
---

```{python}
#| echo: fenced
#| label: fig-1
#| fig-cap: "A regular caption."
import matplotlib.pyplot as plt
plt.plot([1,2,3])
```
````

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/54889e3c-34f0-42d0-a90a-b1d789c9ddc8">

**Comment by devcortex0** [comment]
If I render figures within a tabset, and use echo fenced, it causes the figures to render outside the tabset...
could this be related @cscheid ?

**Comment by cderv** [comment]
@devcortex0 this issue is quite old now. Please open a new one with a reproducible example, and we'll be sure to look at it. It is highly possibly that `echo: fenced` used with Tabset feature could be an edge case that needs better handling. Thanks !
