### ISSUE TITLE
Notebooks outside project folder are not linked properly when running quarto preview

### ISSUE THREAD

**Issue by j-horak** [quarto-dev/quarto-cli#10856]
### Bug description

Notebooks outside the project dir at least for manuscript (and book) projects are linked properly when previewing them. Clicking on the link to the notebook in the browser yields 404 not found.

Even though the html version is rendered properly the link from the article document is wrong. If this is intended behavior and notebooks outside the parent dir are not supported maybe a more clearer error message would be helpful, e.g., `notebooks outside project dir`.

### Steps to reproduce

Basic quarto project with notebook outside the project dir, see [git repo](https://github.com/j-horak/quarto-notebook-in-parent-dir/tree/main).

Run preview command
```bash
quarto preview report
```

Click on link to notebook.

### Expected behavior

Rendered html view of notebooks opens

### Actual behavior

404 error because rendered html is not inside `_manuscript` dir but in directly in project dir.

### Your environment

Linux: Pop!_OS 22.04 LTS

### Quarto check output

Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/jhorak/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /home/jhorak/spack/opt/spack/linux-pop22-zen3/gcc-12.1.0/python-3.10.12-jp65va3vwpqhomuhydms6bsf2nac7ypw/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in micromamba. Did you forget to activate it?

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by cscheid** [comment]
In general, we don't promise support to references to assets outside of the project directory.
