### ISSUE TITLE
Update mathjax default in revealjs

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#10887]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/10885

<div type='discussions-op-text'>

<sup>Originally posted by **olivroy** September 25, 2024</sup>
### Description

In RStudio / rmarkdown, the default mathjax was updated to 2.7.9 recently. I thought it may be good to do the same in Quarto. Simply changing this line would probably do the trick?

https://github.com/quarto-dev/quarto-cli/blob/6b363d996e31c65826c2e8186c14a5da6019af96/src/format/reveal/format-reveal.ts#L90
</div>

**Comment by cderv** [comment]
We can definitely update this URL. It did not benefit from the rstudio cdn update because using another one. 

FWIW this is related to 
- https://github.com/quarto-dev/quarto-cli/issues/4493

we'll add support to Mathjax 3 later, as it requires more change than an url
