### ISSUE TITLE
Callouts: language configuration bugs across formats

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#10894]
### Bug description

The `language` key `callout-tip-title` can be used to set the title of tip callouts. However, when making the callout cross-referenceable this title is ignored and "Tip X" is used instead.

### Steps to reproduce

	---
	format: html

	language: 
	  callout-tip-title: "Note"
	---

	::: {#tip-123 .callout-tip}

	Text

	:::

### Expected behavior

Title of the callout should be "Note 1"

### Actual behavior

Title of the callout is "Tip 1"

### Your environment

Windows 11

### Quarto check output

	[>] Checking versions of quarto binary dependencies...
		  Pandoc version 3.2.0: OK
		  Dart Sass version 1.70.0: OK
		  Deno version 1.41.0: OK
		  Typst version 0.11.0: OK
	[>] Checking versions of quarto dependencies......OK
	[>] Checking Quarto installation......OK
		  Version: 1.6.10
		  Path: C:\Users\au234616\AppData\Local\Programs\Quarto\bin
		  CodePage: 1252

	[>] Checking tools....................OK
		  TinyTeX: (not installed)
		  Chromium: (not installed)

	[>] Checking LaTeX....................OK
		  Tex:  (not detected)

	[>] Checking basic markdown render....OK

	[>] Checking Python 3 installation....OK
		  Version: 3.11.1
		  Path: C:/Users/au234616/AppData/Local/Programs/Python/Python311/python.exe
		  Jupyter: 5.2.0
		  Kernels: python3

	[>] Checking Jupyter engine render....OK

	[>] Checking R installation...........OK
		  Version: 4.4.0
		  Path: C:/PROGRA~1/R/R-44~1.0
		  LibPaths:
			- C:/Users/au234616/AppData/Local/R/win-library/4.4
			- C:/Program Files/R/R-4.4.0/library
		  knitr: 1.48.3
		  rmarkdown: 2.28

	[>] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Thanks. I can spot lots of little bugs in this subsystem.

I'm going to use this issue to solve as many as I can find+fix today.

1. In `html`, as reported.
2. In `revealjs`, we do not add the counter to the crossreferenceable callout title
3. In `pdf`, we repeat the name of the callout and use its name as a default title: "Tip 1: Tip"
4. In `typst`, we have the same bug as in PDF, and we add a spurious line break to the callout title.
5. In `docx`: TBD

**Comment by snhansen** [comment]
@cscheid: Thanks for a quick fix. I just tested it and found out that references to the callout still uses "Tip" though. So `@tip-123` in the above example evaluates to "Tip 1".

**Comment by cscheid** [comment]
There's two separate options: one for the title and one for the reference prefix.

```
language:
  callout-tip-title: "Note" # this one goes on the callout itself
  crossref-tip-prefix: "Note" # this one goes on the references to the callout
```

**Comment by snhansen** [comment]
Ah, that's good to know. Perhaps this page (https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml) should be updated with this information or is there another way to figure that out?

**Comment by cscheid** [comment]
We should change that, but it's complicated. With this fix, you should also now be able to customize language for custom crossref environments, and we can't know ahead of time which those are.
