### ISSUE TITLE
LaTeX `\color{}` command not working for `format: pptx`

### ISSUE THREAD

**Issue by d-morrison** [quarto-dev/quarto-cli#10892]
### Bug description

The `\color{}` TeX math command doesn't compile to `pptx` format (maybe a pandoc problem rather than quarto)?

### Steps to reproduce

````qmd
---
format: pptx
---

$$\color{red}{x}$$
````

### Expected behavior

There should be one slide with:

$$\color{red}{x}$$

### Actual behavior

The LaTeX code is left uncompiled in the output:

![image](https://github.com/user-attachments/assets/f5d83c14-c095-400d-8718-c12184a4c2dc)

[test-ppt.pptx](https://github.com/user-attachments/files/17143878/test-ppt.pptx)

### Your environment

![image](https://github.com/user-attachments/assets/6beea675-23e6-4ff7-8bda-31c3d5d7e769)

### Quarto check output

$ quarto check
Quarto 1.5.57
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.57
      Path: C:\Users\Work\AppData\Local\Apps\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Work\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: C:/Users/Work/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.1.3
      Kernels: julia-1.10, julia-1.8, python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\Work\AppData\Local\Apps\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\Work\AppData\Local\Apps\Quarto\share\jupyter\notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK

**Comment by cscheid** [comment]
`The \color{} TeX math command doesn't compile to pptx format (maybe a pandoc problem rather than quarto)?`

TeX and pptx are separate formats. It's not a Quarto _or_ Pandoc problem, it's that, plainly, TeX commands only work on TeX.

**Comment by cscheid** [comment]
In the future, please consider creating a discussion before filing a bug report. Thanks!
