### ISSUE TITLE
rendering failure when importing  `matplotlib` and/or from `pillow` with `knitr` engine, related to strange linking to `libjpeg.so.8`

### ISSUE THREAD

**Issue by paciorek** [quarto-dev/quarto-cli#10898]
### Bug description

Rendering a qmd file with a Python chunk that imports a particular .so from `PIL/pillow` (or imports `matplotlib`, which in turn imports from PIL/pillow) when using the `knitr` engine fails.

What seems to happen is that somehow during the rendering, `/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2` is being linked against instead of `libjpeg` from Miniconda (in particular `/opt/miniforge/lib/libjpeg.so.8.3.2`). The former does not have the `jpeg12_write_raw_data` symbol, where as the latter does. 

Note that `/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2` is installed as a side effect of installing the `r-base` Ubuntu package. 

As far as I can see, either based on the RPATH embedded within `libtiff.so.6` or running `ldd /opt/miniforge/lib/libtiff.so.6`, the linking should be against `/opt/miniforge/lib/libjpeg.so.8.3.2` rather than `/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2`.

It seems to be a masking issue. If I temporarily move aside `/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2`, then the rendering succeeds, presumably because the "missing" symbol(s) are found in `/opt/miniforge/lib/libjpeg.so.8.3.2`.

I'll note that running the import statements via `reticulate::repl_python` works fine (or in Python itself). So as far as I can see it has something to do specifically with Quarto. But I am not understanding what is going on with the linking.

### Steps to reproduce

````qmd
---
title: test
engine: knitr
---

```{python}
import matplotlib.pyplot as plt
## This import from PIL highlights where the specific issue seems to come from.
# from PIL import _imaging
```
````

Here is a Dockerfile that should allow for reproduction. 

```
FROM ubuntu:22.04

ENV QUARTO_VERSION=1.5.57
ENV PYTHON_VERSION=3.12

RUN apt-get -y update 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN apt-get install -y r-base wget
RUN Rscript -e "install.packages(c('rmarkdown','reticulate'))"
RUN wget https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.tar.gz 
RUN tar -C /opt -xvzf quarto-${QUARTO_VERSION}-linux-amd64.tar.gz
RUN ln -s /opt/quarto-${QUARTO_VERSION}/bin/quarto /usr/bin/
RUN quarto install tinytex
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
RUN bash Miniforge3-Linux-x86_64.sh -b -p /opt/miniforge
ENV PATH=/opt/miniforge/bin:${PATH}
RUN mamba update --all -y 
RUN mamba install -y pillow matplotlib

CMD /bin/bash
```

### Expected behavior

I expect rendering to proceed successfully.

### Actual behavior

```
processing file: test.qmd
1/3                  
2/3 [unnamed-chunk-1]
Error in `py_call_impl()`:
! ImportError: /opt/miniforge/lib/python3.12/site-packages/PIL/../../../libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0
Run `reticulate::py_last_error()` for details.
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 13. knitr (local) engine(options)
 14. reticulate::eng_python(options)
 15. reticulate:::py_compile_eval(snippet, compile_mode)
 20. builtins$eval(compiled, globals, locals)
 21. reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
```

### Your environment

Ubuntu 22.04
Quarto 1.5.57

The Dockerfile results in an old version of R (4.1.2) but this also occurs with R 4.4.0 on a production Ubuntu 22.04 server (which is where the problem originally surfaced).

### Quarto check output

```
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto-1.5.57/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /root/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.6 (Conda)
      Path: /opt/miniforge/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
This isn't a Quarto bug; the issue is somewhere in the way your environment is setup (Quarto knows nothing about how your environment is generally set up, and 

```
! ImportError: /opt/miniforge/lib/python3.12/site-packages/PIL/../../../libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0
```

This indicates to me some mis-installed dependency.

**Comment by paciorek** [comment]
Fair enough, but I'll just note that the error occurs in a simple Linux container with standard software installed and only seems to manifest when using Quarto/knitr (not when simply using Python or using reticulate directly). 

Do you have any thoughts about why linking when rendering in Quarto (or equivalently via `rmarkdown::render`) is behaving differently than other situations?

Obviously I am asking in part for myself, but I wouldn't be surprised if other Quarto users run into this, given the environment is so vanilla.

**Comment by cscheid** [comment]
> when using Quarto/knitr

I'm not sure what you mean here: do you mean you can repro it knitr directly?

> Do you have any thoughts about why linking when rendering in Quarto (or equivalently via `rmarkdown::render`) is behaving differently than other situations?

It might have to do with our configuration of graphics device defaults, or maybe the way that knitr itself configures reticulate? The R code we use to call knitr is in https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/rmd/, but I don't see anything that looks directly suspicious.

**Comment by cscheid** [comment]
In any case, we can't help without a clean, minimal repro, and that would ideally be without a container. (Since you're on Linux, you can eg try to get a repro in a GitHub Actions workflow directly.)

**Comment by cderv** [comment]
> equivalently via rmarkdown::render) is behaving differently than other situations?

If you can reproduce the issue using **knitr** only (`knitr::knit()`) with Python code cell, then it could be something related to **reticulate** engine for knitr. Especially if it works with **reticulate** itself.

Please do try this, and if this is a problem, you can open on **reticulate** (and ping me). 

Thank you !

**Comment by paciorek** [comment]
@cderv thanks. 

To confirm, I see the problem with any of 
 - `quarto render` with the `knitr` engine
 - `rmarkdown::render`
 - `knitr::knit`

I do not see the problem when running directly in R via `reticulate::repl_python`.

I will post a `reticulate` issue.

**Comment by cscheid** [comment]
If you're not seeing a problem when running directly through reticulate, then reticulate is not a suspect.

From your diagnosis, my guess is that it would be something on knitr. quarto and rmarkdown both call knitr internally, and you _are_ seeing a problem in `knitr::knit`.

**Comment by t-kalinowski** [comment]
I suspect this is a conda issue - with the Conda and R packages wanting different versions of `libtiff.so`.

Can you reproduce the issue in a regular venv (e.g., created with `reticulate::virtualenv_create`?

**Comment by paciorek** [comment]
So based on some digging with `strace`, I think I have a better idea of what is going on.

The condition required for this to occur seems to be that `R_X11.so` have been opened from R. That causes `libtiff.so.5` and then `libjpeg.so.8` to be opened. In the configuration shown at the start of this thread, `libjpeg.so.8` is coming from `/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2`. Then when the Python import (`matplotlib.pyplot` or `PIL._imaging`) occurs, `libjpeg.so.8` has already been opened, so it is not opened again. So the libjpeg.so.8.3.2 (from `/opt/miniforge/lib/libjpeg.so.8.3.2`) that is needed for the Python import is never opened and the error occurs.

For reasons I don't understand (and perhaps it's not directly relevant why), any of `quarto render`, `rmarkdown::render` and `knitr:knit` cause `R_X11.so` to be opened. 

This also means that I can reproduce the problem purely via `reticulate::repl_python` if in R (before calling out to Python), I do anything that creates an X11 graphics device. For example,

```
> hist(rnorm(5))
> reticulate::repl_python()
Would you like to create a default Python environment for the reticulate package? (Yes/no/cancel) no
Python 3.12.2 (/system/linux/miniforge-3.12/bin/python3)
Reticulate 1.36.1 REPL -- A Python interpreter in R.
Enter 'exit' or 'quit' to exit the REPL and return to R.
>>> from PIL import _imaging
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/system/linux/lib/R-22.04/4.4.0/x86_64/site-library/reticulate/python/rpytools/loader.py", line 122, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/system/linux/lib/R-22.04/4.4.0/x86_64/site-library/reticulate/python/rpytools/loader.py", line 96, in _run_hook
    module = hook()
             ^^^^^^
  File "/system/linux/lib/R-22.04/4.4.0/x86_64/site-library/reticulate/python/rpytools/loader.py", line 120, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /system/linux/miniforge-3.12/lib/python3.12/site-packages/PIL/../../../libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0
```

I think that suggests that `reticulate` is the place to report. Not clear it's a bug, but the fact that the execution of the Python code is not isolated from libraries loaded on the R side seems like something to consider and at least to have an issue posted that other users might find if they run into a similar problem.

**Comment by cscheid** [comment]
@paciorek god to hear - but this seems unrelated to Quarto, so reporting it on the other repo seems more appropriate.

**Comment by t-kalinowski** [comment]
This can happen when mixing conda and non-conda binaries.

The simplest solution is to consolidate the stack so that either all or none of the dynamically loaded libraries come from conda. In practice, this means either installing all of R and its packages through conda or switching the Python installation to a virtual environment. [uv](https://github.com/astral-sh/uv) is a good option, as it fills many of the same needs as conda without the binary incompatibility issue.

**Comment by cderv** [comment]
> [uv](https://github.com/astral-sh/uv) is a good option, as it fills many of the same needs as conda without the binary incompatibility issue.

Just learning about this tool 👀 Thanks for sharing !

**Comment by paciorek** [comment]
@cderv, given this seems to amount to an incompatibility of the conda and non-conda binaries, I'm not sure if I should report to `reticulate`. It is something that could trip up other users, but not a bug.
