### ISSUE TITLE
watch file modifications by different users

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#109]
Hi there and thank you for your amazing work! My issue might be out of scope but I would be over the moon if it worked.

I am using quarto to build an internal wiki for my research group. We have a shared file system with multiple (linux) users from which I am serving the site through quarto preview as a systemd service. When I, the user who started the service, change a file, the website updates almost instantly.
But when another user changes a file, quarto seems to not recognize this change, but I does appear once I open and save the file myself. Is there some way to make quarto "more alert" to file changes?

**Comment by jjallaire** [comment]
Sadly file monitoring doesn't currently work for network drives (which is what we'd need to make this work).

**Comment by jmbuhr** [comment]
Do you think it is feasible to make this work? Or would it be possible to hack something around it, like e.g. a bash script that runs the `touch` command to trick the system into recognizing other users's changes?

**Comment by jjallaire** [comment]
I think you need something on the host system that keeps list of file modification times and polls the filesystem for updated files (then touches them locally to trigger re-render). I think a bash script could definitely do this.

**Comment by jjallaire** [comment]
i.e. you are basically reproducing what inotify does with the filesystem polling

**Comment by jmbuhr** [comment]
Just in case anyone comes across this crazy idea as well, I am going to leave the solution here (and then I stop posting on a closed issue, sorry!):

```
#!/bin/bash
shopt -s globstar
fswatch -0 -m poll_monitor ./**/*.md | xargs -0 -n 1 touch
```

will watch for file changes and also works on a shared drive. `-m poll_monitor` is necessary in some cases because shared `samba` drives don't send `inotify` events so you have to poll for changes. https://github.com/emcrisostomo/fswatch makes this possible :)
