### ISSUE TITLE
Something wonky is going on with the tables listing the project options

### ISSUE THREAD

**Issue by lwjohnst86** [quarto-dev/quarto-cli#10907]
### What would you like to do?

Report an issue on quarto.org

### Description

If you go to this page: https://quarto.org/docs/reference/projects/options.html and look at the tables showing the options and descriptions of those options, the table is all wonky and not formatted correctly. It looks like the CSS vertical alignment between table column 1 (the options) and table column 2 (the description) are middle aligned vs top aligned. The result makes it look really not aligned properly and is difficult to read (e.g. the description for `type` looks like it is for both `type` and `title`).

**Comment by mcanouil** [comment]
Thanks for the report.
We are aware of the issue which is related to a change in one dependency that is going to be fixed soon.
