### ISSUE TITLE
author and date not displayed in github actions

### ISSUE THREAD

**Issue by sbalci** [quarto-dev/quarto-cli#1091]
Hi,
Hope you are well :)

The GitHub Action generated page does not display author and date. First image.
But the local RStudio generated page renders normally. Second image.

<hr>
<img width="713" alt="Screen Shot 2022-06-07 at 18 57 56" src="https://user-images.githubusercontent.com/7208830/172427690-7104be8c-c825-470e-a820-7a84d2a61527.png">

<hr>
<img width="760" alt="Screen Shot 2022-06-07 at 18 55 00" src="https://user-images.githubusercontent.com/7208830/172427695-e928b70a-65f5-473b-aaff-6055b8649d67.png">

<hr>

Local configuration:

```
(base) Serdars-iMac:patolojiatlasi.github.io serdarbalci$ quarto check

[✓] Checking Quarto installation......OK
      Version: 0.9.495
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: /Users/serdarbalci/miniconda3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.1.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/serdarbalci/Documents/GitHub/patolojiatlasi.github.io/renv/library/R-4.1/aarch64-apple-darwin20
        - /private/var/folders/cd/2ybg5n514bdfsg2n2wnsspmw0000gn/T/Rtmp7cEqH7/renv-system-library
      rmarkdown: 2.13

[✓] Checking Knitr engine render......OK
```

GitHub Action file:

https://github.com/patolojiatlasi/patolojiatlasi.github.io/blob/main/.github/workflows/Quarto-Render-Bilingual-Book-Push-Tweet-Updates.yml#L46

**Comment by dragonstyle** [comment]
We had a regression this morning which broke rendering of authors. That regression should now be fixed - would you mind giving it another try using CI and see whether that resolves the issue (I was able to just verify the proper author rendering with a local version and the latest version of Quarto)? Apologies for the issue!

**Comment by cderv** [comment]
@sbalci 

> The GitHub Action generated page does not display author and date. First image.

looking at your CI, you are using an older action from https://github.com/pommevilla/quarto-render which will install version 0.2.232 of Quarto 
https://github.com/patolojiatlasi/patolojiatlasi.github.io/runs/6777528348?check_suite_focus=true#step:6:22

This is quite an old version of Quarto as last version is 0.9.539

> But the local RStudio generated page renders normally. Second image.

Locall you are using 0.9.245 so this is quite different from the one in your CI. 

You should probably switch to this action that we support https://github.com/quarto-dev/quarto-actions/tree/main/install-quarto and that will install the latest available release by default (you can pin a version is needed). 
Only difference with other action is that you'll need to call `quarto render` with argument you need in another step in your workflow after installation. 

Especially you should try to keep your CI and local environment in sync if you compare results. 

Hope it helps

**Comment by sbalci** [comment]
Thank you for the update. 
@cderv  As you suggested I have changed the action.

I am using R to make some changes and then call `quarto::quarto_render(".", as_job = FALSE)` to generate the page

I am having the following error with the new action:

https://github.com/patolojiatlasi/patolojiatlasi.github.io/runs/6778791739?check_suite_focus=true#step:7:4220

````
Error running filter /opt/quarto/share/filters/quarto-post/quarto-post.lua:
could not get meta value
	while retrieving MetaValue
	while retrieving value
	while retrieving key-value pair
	while retrieving Map
	while retrieving MetaValue
	while retrieving value
	while retrieving key-value pair
	while retrieving Map
	while retrieving MetaValue
	while retrieving index 1
	while retrieving list
	while retrieving MetaValue
	while retrieving value
	while retrieving key-value pair
	while retrieving Map
	while retrieving Meta
	while retrieving function argument meta
	while retrieving arguments for function Pandoc
stack traceback:
	/opt/quarto/share/filters/quarto-post/quarto-post.lua:1166: in function 'compileTemplate'
	/opt/quarto/share/filters/quarto-post/quarto-post.lua:1770: in local 'fn'
	/opt/quarto/share/filters/quarto-post/quarto-post.lua:1063: in function </opt/quarto/share/filters/quarto-post/quarto-post.lua:1057>
Error: <system_command_status_error in processx::run(quarto_bin, args, echo = TRUE):
 System command 'quarto' failed, exit status: 1, stdout & stderr were printed>
Stack trace:
 1. quarto::quarto_render(".", as_job = FALSE)
 2. processx::run(quarto_bin, args, echo = TRUE)
 3. throw(new_process_error(res, call = sys.call(), echo = echo,  ...
 x System command 'quarto' failed, exit status: 1, stdout & stderr were printed 
Execution halted
Error: Process completed with exit code 1.

```

**Comment by sbalci** [comment]
I have forked the pommevilla action and changed the version number: https://github.com/pathologyatlas/quarto-render/blob/main/action.yaml#L14

And the run was successful: https://github.com/patolojiatlasi/patolojiatlasi.github.io/runs/6779693579?check_suite_focus=true#step:8:4219

<img width="547" alt="Screen Shot 2022-06-07 at 20 57 10" src="https://user-images.githubusercontent.com/7208830/172450746-779c04fe-c021-48f0-af37-39630e355bb0.png">

**Comment by sbalci** [comment]
Thank you very much :)
So I will wait for the new version and let you know how it goes.

**Comment by cderv** [comment]
@sbalci hopefully this will fix your issue. Please confirm your next build using at least 0.9.542 is working as expected. Thank you!

**Comment by sbalci** [comment]
@dragonstyle @cderv Thank you very much.
I confirm that the issue is resolved
https://github.com/patolojiatlasi/patolojiatlasi.github.io/runs/6792339110?check_suite_focus=true
