### ISSUE TITLE
https://quarto.org/docs/get-started/ offers to install the older version 1.5.57 while GitHub has the binaries for the latest version 1.6.15

### ISSUE THREAD

**Issue by yurivict** [quarto-dev/quarto-cli#10926]
### Bug description

See the subject.
Please update https://quarto.org/docs/get-started/

### Quarto check output

n/a

**Comment by mcanouil** [comment]
Please do properly describe what it is about.
A title is not a description.

**Comment by TomBener** [comment]
> The page at [quarto.org/docs/get-started](https://quarto.org/docs/get-started/) offers to install the older version 1.5.57 while the GitHub [tags page](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.6.15has) has the binaries for the latest version 1.6.15

The latest _release_ is v1.5.57, while v1.6.15 is the _pre-release_ version. Hope it helps.

**Comment by mcanouil** [comment]
Clic on the link "release notes and more downloads".

**Comment by cderv** [comment]
> while the GitHub [tags page](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.6.15has) has the binaries for the latest version 1.6.15

Latest releases on github can be seen at this link usually: https://github.com/quarto-dev/quarto-cli/releases/latest 

and it will point to 1.5.57. Other released tags are pre-released as explained above.

Hope it helps understand how release process works;
