### ISSUE TITLE
Div breaks continued list

### ISSUE THREAD

**Issue by finkelshtein** [quarto-dev/quarto-cli#10921]
### Bug description

If a list item contains a div-element followed by a text, the latter text is not indented.

### Steps to reproduce

````qmd

---
title: "test"
format: html
---

* We can see then

:::{.divname}

$$
  a+b=c
$$

:::

    as requested.

* Consider now...

````

### Expected behavior

I'd like to have "as requested" aligned with "We can see". Without div-block it works, even with Latex-formula, i.e. 

```` qmd
* We can see then

    $$
    a+b=c
    $$

    as requested.

* Consider now...
````
works as expected. 

### Actual behavior

The text after div ("as requested") is not indented. Moreover, it is recognised as a quote I believe.

### Quarto check output

Quarto 1.5.57
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.57
      Path: C:\Users\dmitri\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: Installation From Path
      Path: C:\texlive\2022\bin\win32
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.4.1
      Path: C:/PROGRA~1/R/R-44~1.1
      LibPaths:
        - C:/Users/dmitri/AppData/Local/R/win-library/4.4
        - C:/Program Files/R/R-4.4.1/library
      knitr: 1.48
      rmarkdown: 2.28

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
There is no bug.
You did not align the sub-elements as documented.

Since you are using empty lines, it means you want a list that is not compacted.
Aligned, means aligned, i.e.:

````qmd
---
title: "test"
format: html
---

* We can see then

  ::: {.divname}

  $$
    a+b=c
  $$

  :::

  as requested.

* Consider now...
````


In the future, please open a GitHub Discussion rather than a GitHub Issue.
