### ISSUE TITLE
How to access nested metadata having a key with dots

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#10936]
Let's support something like `{{< meta nested.a\.b\.c.key >}}`

(Then we ofc also need to figure out what to do with keys that have backslashes in them.0

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/10914

<div type='discussions-op-text'>

<sup>Originally posted by **vlcinsky** September 28, 2024</sup>
### Description

My sample index.qmd:

```
---
title: My Page
nested:
  a.b.c:
    key: Show me
---

I would like to show the "Show me" using a shortcode.

E.g. {{< meta nested["a.b.c"]key >}}

but it fails.
```

My question is: is there a **syntax for accessing keys, which include dot(s) in their name**?</div>

**Comment by mcanouil** [comment]
Wouldn't it be "simpler/better" to support the square brackets (with inside quotes) notation?

**Comment by cscheid** [comment]
> Wouldn't it be "simpler/better" to support the square brackets (with inside quotes) notation?

It would be significantly worse - now we have to care about parsing square brackets and matched quotes.

**Comment by mcanouil** [comment]
I was thinking of using the arg as "raw" and evaluate it it on `meta` but I'm not sure that's something even possible in LUA (also while writing it, might be a bad idea with a possible risk to inject code, although with the computations everywhere, that's not really a new risks😅).

**Comment by cscheid** [comment]
> I was thinking of using the arg as "raw" and evaluate it it on meta

And then someone writes a function call in there. `eval` is a bad idea in general, it makes both error reporting and "restricting" the feature essentially impossible.

**Comment by cscheid** [comment]
The actual syntax needs to have an extra `\` in it, but #10937 will enable `{{< meta nested.a\\.b\\.c.key >}}` It's not particularly pleasing to the eye, but it's narrow and safe, and I hope this is sufficiently rarely used anyway...

**Comment by vlcinsky** [comment]
My use case is to use value from existing meta variable to pick up value available in var.

```md
---
domain-name: "registr.dopravninfo.cz"
---

Title of the domain is {{{< var domain-titles[{{< meta domain-name >}}] >}}
```

The syntax in last line above is completely made up.

I guess, I will have to use python block to do so.

**Comment by mcanouil** [comment]
Well, shortcode in shortcode is not something documented because that's not really supported.
Here, you should use conditional content based on meta value.

**Comment by cscheid** [comment]
I think the easiest way to achieve what you want here is through a Lua filter. You should have access to metadata contents there.
