### ISSUE TITLE
docx files generated from .qmd files that lack a format: docx in the header are invalid

### ISSUE THREAD

**Issue by Robinlovelace** [quarto-dev/quarto-cli#10941]
### Bug description

I get the following message when I try to open docx files generated by Quarto: 

![image](https://github.com/user-attachments/assets/3774beda-3e82-44f2-9c7c-cc5c5f7c5987)

I noticed this will quarto-generated docx files around a month ago, I recall they could not be viewed on Dropbox or Word. I didn't report it then due to lack of time and in case it was a temporary regression that would be fixed in the latest version.

### Steps to reproduce

Create this file as demo.qmd and try running the code:

````
---
title: "Quarto Basics"
---

This is a test.


```{r}
#| echo: false
#| eval: false
file.remove("demo_quarto.docx")
quarto::quarto_render("demo.qmd", output_file = "demo_quarto.docx")
# Convert html to docx with pandoc:
quarto_docx_via_html = function(input) {
  quarto::quarto_render(input, output_format = "html")
  ib = gsub(".qmd", "", input)
  system(glue::glue("pandoc {ib}.html -o {ib}.docx"))
}
quarto_docx_via_html("demo.qmd")
```

````

### Expected behavior

You should see something like this in the resulting docx when uploaded to OneDrive and opened with Office365

### Actual behavior

You cannot open the file as shown above. To work-around I have created the following function that solves the problem:

```r
quarto_docx_via_html = function(input) {
  quarto::quarto_render(input, output_format = "html")
  ib = gsub(".qmd", "", input)
  system(glue::glue("pandoc {ib}.html -o {ib}.docx"))
}
```

That generates the following:

![image](https://github.com/user-attachments/assets/a4afa291-8e99-4a96-93d0-bd4943f667dc)

I would expect 

```r
quarto::quarto_render("demo.qmd", output_file = "demo_quarto.docx")
```

To also generate output that works with Office products. I wonder what Quarto is doing different from pandoc.

### Your environment

- IDE: VS Code but not relevant
- Ubuntu 22.04

### Quarto check output

```
quarto check
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/robin/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3, geocompy, julia-1.10, mojo-jupyter-kernel, mojo-max-jupyter-kernel

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib/R
      LibPaths:
        - /home/robin/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Can you attempt a reproduction that doesn't involve quarto_r? Something we can render with `quarto render file.qmd --to docx`.

**Comment by Robinlovelace** [comment]
I just ran the following command:

```bash
quarto render demo.qmd --output_file demo_quarto_from_bash.docx
```

**Comment by Robinlovelace** [comment]
Uploading on OneDrive. Will let you know what I see...

**Comment by Robinlovelace** [comment]
Update: this seems to be the correct syntax:

```
quarto render --help
quarto render demo.qmd -o demo_quarto_from_bash.docx
```

**Comment by cscheid** [comment]
What I'm asking for is a repro that doesn't go through this step of converting our rendered html to docx.

Specifically, a simple .qmd file where `quarto render` triggers the issue. Your report title says "format: docx generates outputs that cannot be opened by Word", but you haven't provided a document with `format: docx`.

**Comment by Robinlovelace** [comment]
The above bash reprex generates a docx that has the same issue, as shown below:

![image](https://github.com/user-attachments/assets/b3e2c7aa-3231-4f36-96fa-667cc7b5ea7a)

**Comment by Robinlovelace** [comment]
> What I'm asking for is a repro that doesn't go through this step of converting our rendered html to docx.
> 
> Specifically, a simple .qmd file where `quarto render` triggers the issue. Your report title says "format: docx generates outputs that cannot be opened by Word", but you haven't provided a document with `format: docx`.

Oh yes, I see what you mean now. However this:

```bash
quarto render demo.qmd -o demo_quarto_from_bash.docx
```

is the same as adding `format: docx` to the yaml header, right?

**Comment by Robinlovelace** [comment]
Will give it a go and report back in any case.

**Comment by Robinlovelace** [comment]
Update: when you specify the format in the yaml header it works: 

![image](https://github.com/user-attachments/assets/17637c38-9821-4d37-8865-a81689e76459)

Should we update to "docx files generated from .qmd files that lack a format: docx in the header are invalid" or similar?

**Comment by Robinlovelace** [comment]
Having checked 

```bash
quarto::quarto_render("demo.qmd", output_file = "demo_quarto2.docx", output_format = "docx")
```

I think it's more an issue that quarto does not auto-detect output format from output file extension. Would be happy to close this issue and open a new one as a feature request (if it's intended behaviour for now) or bug (if not).

**Comment by cscheid** [comment]
> I think it's more an issue that quarto does not auto-detect output format from output file extension

That's intentional, and because (eg) it's not possible to do so in general. as a concrete example, revealjs and html and dashboard all use `.html` as output, for example. Format variants are another reason.
