### ISSUE TITLE
raw confluence blocks no longer working?

### ISSUE THREAD

**Issue by fkgruber** [quarto-dev/quarto-cli#10944]
### Bug description

I'm getting api errors when trying to add raw confluence blocks.  I'm just using the example in the website (https://quarto.org/docs/publishing/confluence.html#raw-confluence-blocks) and then
```bash
quarto publish confluence test_conf_pdf.qmd
```

### Steps to reproduce

````
---
title: "Test raw code"
---

# Test raw code

```{=confluence}
<ac:task-list>
    <ac:task>
        <ac:task-status>incomplete</ac:task-status>
        <ac:task-body>task list item</ac:task-body>
    </ac:task>
</ac:task-list>

```
````

### Expected behavior

generate a confluence page with the document

### Actual behavior

ERROR: API Error: 400 - Bad Request

Stack trace:
    at ConfluenceClient.handleResponse (file:///Applications/quarto/bin/quarto.js:108210:19)
    at ConfluenceClient.fetch (file:///Applications/quarto/bin/quarto.js:108015:25)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async ConfluenceClient.updateContent (file:///Applications/quarto/bin/quarto.js:108148:25)
    at async updateContent (file:///Applications/quarto/bin/quarto.js:108475:32)
    at async doOperation (file:///Applications/quarto/bin/quarto.js:108589:33)
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:76250:16)
    at async doWithSpinner (file:///Applications/quarto/bin/quarto.js:107563:12)
    at async publishDocument (file:///Applications/quarto/bin/quarto.js:108600:13)
    at async Object.publish5 [as publish] (file:///Applications/quarto/bin/quarto.js:108741:49)

### Your environment

- OS sonoma  14.7

### Quarto check output

Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.8 (Conda)
      Path: /Users/fgruber/miniconda3/bin/python
      Jupyter: 5.5.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26.1

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Our code didn't change - is it possible that your confluence server changed and they no longer support the APIs we use?

**Comment by cscheid** [comment]
This is quite hard for us to test since it's necessarily tied to the server you're using, and the fact that they're returning a very generic 400 "Bad Request" error.

Tracing back from the quarto.js file, I can see that the error is coming from this call:

https://github.com/quarto-dev/quarto-cli/blob/396a8d71ed0e86cd05ea441f895a6df56fb0ebeb/src/publish/confluence/api/index.ts#L243

**Comment by cscheid** [comment]
> So it works for you?

I didn't say that. I said "Our code didn't change", in response to "no longer working" in your report title, which I took to mean 'it used to, but is "no longer working"'. I'm trying to understand the situation first.

**Comment by fkgruber** [comment]
Oh wait it works. It seems that I was missing 
format: confluence-html

thanks
