### ISSUE TITLE
Add `output-dir` to Typst configuration options

### ISSUE THREAD

**Issue by d33bs** [quarto-dev/quarto-cli#10955]
Thanks for the fantastic work on Quarto! I noticed when using Typst formats through Quarto that there is no option for an `output-dir` (where there is an option for `output-file`). `output-file` may only be a file, so it seems like there's no way for the output directory to be specified. When adding the frontmatter option `output-dir` to a Typst focused document Quarto seems to ignore the setting. I believe this is in alignment with the docs, which make no mention of an `output-dir` key: https://quarto.org/docs/reference/formats/typst.html#rendering .

Please don't hesitate to let me know if you have any questions or if I may clarify at all. Thanks again!

**Comment by mcanouil** [comment]
`output-dir` already exist and is a project wide option.
A little search shows that the option is not in any formats.

In the future, please use GitHub Discussion first for feature requests and questions.

Note also that there is a whole discussion on `output-dir` in GitHub Discussion.

**Comment by d33bs** [comment]
Thanks @mcanouil , sorry about not following convention here with a discussion prior to an issue. I'm still finding I cannot use `output-dir` as expected, I'll try reaching out for help within the discussions.

**Comment by mcanouil** [comment]
See:

- https://github.com/quarto-dev/quarto-cli/discussions/2171
