### ISSUE TITLE
Error rendering projects: `ERROR: TypeError: error sending request for url`

### ISSUE THREAD

**Issue by jparisu** [quarto-dev/quarto-cli#10971]
### Bug description

I have been working with quarto for months in my Ubuntu 24.04 laptop without troubles (btw, great job for quarto's team).
However, lately I have been experienced a recurrent error when rendering medium size projects (around 15 revealjs):

```
ERROR: TypeError: error sending request for url (http://localhost:9222/json/list): error trying to connect: tcp connect error: Connection refused (os error 111)

Stack trace:
    at async mainFetch (ext:deno_fetch/26_fetch.js:170:12)
    at async fetch (ext:deno_fetch/26_fetch.js:391:7)
    at async externalRequest (file:///opt/quarto/bin/quarto.js:38425:22)
    at async List (file:///opt/quarto/bin/quarto.js:38452:21)
    at async Chrome._fetchDebuggerURL (file:///opt/quarto/bin/quarto.js:38641:37)
    at async Chrome._start (file:///opt/quarto/bin/quarto.js:38598:25)
```

I have recently updated google chrome in my system. Currently: `Google Chrome 129.0.6668.70`. 
This could be the origin of the problem, however I have not noticed any other strange behavior in my system.

### Steps to reproduce

I just get my old project and type `quarto render` as always.

### Expected behavior

Before, the project worked perfectly.

### Actual behavior

Now, I get different errors.
The most recurrent is the following:

```
[15/15] material/IA_02_01_grafo.qmd
ERROR: TypeError: error sending request for url (http://localhost:9222/json/list): error trying to connect: tcp connect error: Connection refused (os error 111)

Stack trace:
    at async mainFetch (ext:deno_fetch/26_fetch.js:170:12)
    at async fetch (ext:deno_fetch/26_fetch.js:391:7)
    at async externalRequest (file:///opt/quarto/bin/quarto.js:38425:22)
    at async List (file:///opt/quarto/bin/quarto.js:38452:21)
    at async Chrome._fetchDebuggerURL (file:///opt/quarto/bin/quarto.js:38641:37)
    at async Chrome._start (file:///opt/quarto/bin/quarto.js:38598:25)
```

Some other times I am encountering the following issue, that I am not sure whether it is related:

```
[20/21] material/AA_00_quarto_intro.qmd
error: Top-level await promise never resolved
    await mainRunner(async (args)=>{
    ^
    at <anonymous> (file:///opt/quarto/bin/quarto.js:118235:5)
```

### Your environment

- Ubuntu: 24.04
- Google Chrome: 129.0.6668.70 
- bash: version 5.2.21(1)-release (x86_64-pc-linux-gnu)
- quarto: 1.5.56

### Quarto check output

```
Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: ***
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
``

**Comment by mcanouil** [comment]
> I just get my old project and type quarto render as always.

That's not helpful to reproduce.
We do really need the means to reproduce.

Please edit your original report with a fully reproducible example or a clear depiction of the steps (with required materials) for us to reproduce.

You can share a **small self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository? The goal is to make it as easy as possible for us to recreate your problem so that we can fix it: please help us help you! Thanks.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by cscheid** [comment]
You need [1.5.57 or later](https://github.com/quarto-dev/quarto-cli/blob/v1.5.57/news/changelog-1.5.md).

**Comment by jparisu** [comment]
Thank you for the answer.

> You need [1.5.57 or later](https://github.com/quarto-dev/quarto-cli/blob/v1.5.57/news/changelog-1.5.md).

@cscheid sadly the update did not fix the error completely. The error message has disappeared, but now the render process never ends.



> Please edit your original report with a fully reproducible example or a clear depiction of the steps (with required materials) for us to reproduce.

Sorry, my first comment may have not been as clear as I intended.
This is not an issue that I am experienced in a single quarto file, or in a specific quarto project. It is an issue that I am encountering in multiple projects, and in (apparently) random files each time.
For example, I have a 15 files project. It normally gets stuck in the last file `[15/15] material/IA_02_01_grafo.qmd`, sometimes it does, sometimes it does not. However, when I execute `quarto render material/IA_02_01_grafo.qmd` alone it never fails.
The same happens with different projects in random files.

I am sorry I can not be more specific here. Also, these projects are private and I cannot share them. And I have not been able to reproduce it in a small reproducible project.

**Comment by mcanouil** [comment]
To be clear the initial issue is one caused by a change in chromium based browsers which has been addressed with the latest stable version of Quarto.

Regarding your other issue.
If you can't provide us with anything to help us investigate, I'am afraid you are stuck with the issue.
So, you have to figure this out on your own: remove pieces of your project, test your project on other environment, disable sync if you are working inside a synced (with cloud provider) folder, ...
