### ISSUE TITLE
When switching from Source->Visual, an aside that starts with a link is mangled

### ISSUE THREAD

**Issue by DavisVaughan** [quarto-dev/quarto-cli#1097]
Look at the second aside, before and after switching to Visual mode

https://user-images.githubusercontent.com/19150088/172512228-b2469cdb-9a3e-44b7-b497-b01bdc497878.mov

Original code in the qmd:

```
---
title: "2022-05-23_locale-revisited"
editor_options: 
  chunk_output_type: console
---

# Intro

[Hadley is the one who recognized that viewing data frames from this angle opens up powerful new workflows that are especially useful for data analysis.]{.aside}

[[Hadley](https://hadley.nz) is the one who recognized that viewing data frames from this angle opens up powerful new workflows that are especially useful for data analysis.]{.aside}

[A person, [Hadley](https://hadley.nz), is the one who recognized that viewing data frames from this angle opens up powerful new workflows that are especially useful for data analysis.]{.aside}

```

RStudio 2022.06.0-daily+490 "Spotted Wakerobin" Daily (6c526a3d2ada5e2327136ad0f8a568cdb9a2ca07, 2022-06-07) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

quarto 0.9.344

**Comment by jjallaire** [comment]
Thanks for reporting! Ultimately marks have a priority within the visual editor (so some re-nesting is always possible). In this case had link with a higher priority than span which is clearly wrong. I've reversed them here (https://github.com/rstudio/rstudio/commit/be0d860a4650b185132484a0a38dd041bb993cf5) and now your example doesn't get transformed.
