### ISSUE TITLE
Gallery: Mojo's website no longer uses quarto

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#10980]
### What would you like to do?

Report an issue on quarto.org

### Description

There is a link to this site in the gallery, but I don't think it uses Quarto.
https://docs.modular.com/mojo/manual/

Context:
https://github.com/modularml/mojo/discussions/1583#discussioncomment-7989586

**Comment by cscheid** [comment]
I believe they render .qmds to docusaurus, as evidenced by the appearance of code blocks and their subsequent outputs, etc: https://docs.modular.com/mojo/manual/control-flow

**Comment by cscheid** [comment]
Hm. If that's the case, then we should change it. Can you point me to where you're getting this from? Thanks.

**Comment by eitsupi** [comment]
For example, this commit says this.
https://github.com/modularml/mojo/commit/23da6e00fc0f8c79f02ec31d05b3afa0c4d70d62

> This was used with our previous Quarto-based website.

This means that it is not currently a Quarto-based website.

**Comment by cderv** [comment]
Found several comments showing they indeed migrated to docusaurus 
- https://github.com/modularml/mojo/issues/179#issuecomment-1936542597
- https://github.com/modularml/mojo/issues/265#issuecomment-2081888809

And here is some context: https://github.com/modularml/mojo/discussions/2078
