### ISSUE TITLE
Powerpoint template: useless layouts are created

### ISSUE THREAD

**Issue by raffaem** [quarto-dev/quarto-cli#10987]
### Bug description

The [following section of the help](https://quarto.org/docs/presentations/powerpoint.html#creating-a-template) describe how to generate a Powerpoint template to be customized to your needs.

The [preceding section](https://quarto.org/docs/presentations/powerpoint.html#powerpoint-templates) describes what needs to be present in the Powerpoint template.

In particular, the template 

> should contain layouts with the following names [...]:
>
> - Title Slide
> - Title and Content
> - Section Header
> - Two Content
> - Comparison
> - Content with Caption
> - Blank

So we need 6 layouts.

When I run `quarto pandoc -o template.pptx --print-default-data-file reference.pptx `, a presentation with the following layout structure is created:

- Office Theme
  - Title Slide [OK]
  - Title and Content [OK]
  - Section Header [OK]
  - Two Content [OK]
  - Comparison [OK]
  - Title Only [useless?]
  - Blank [OK]
  - Content with Caption [OK]
  - Picture with Caption [useless?]
  - Title and Vertical Text [useless?]
  - Vertical Title and Text [useless?]

Are the slides I indicated as `[useless?]` needed?

### Steps to reproduce

See above

### Expected behavior

Only the layouts strictly needed should be created

### Actual behavior

Some useless layouts are created

### Quarto check output

```
Quarto 1.5.57

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK

[✓] Checking versions of quarto dependencies......OK

[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin


(|) Checking tools....................
(/) Checking tools....................[2K[G
[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)


(|) Checking LaTeX....................
(/) Checking LaTeX....................
(-) Checking LaTeX....................
(\) Checking LaTeX....................
(|) Checking LaTeX....................[2K[G
[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined


(|) Checking basic markdown render....
(/) Checking basic markdown render....
(-) Checking basic markdown render....
(\) Checking basic markdown render....
(|) Checking basic markdown render....[2K[G
[✓] Checking basic markdown render....OK


(|) Checking Python 3 installation....[2K[G
[✓] Checking Python 3 installation....OK
      Version: 3.12.6
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: ir, python3


(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 18, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[2K[G
[✓] Checking Jupyter engine render....OK

```

**Comment by mcanouil** [comment]
You are describing Pandoc output as you are using Pandoc.
Quarto does not define or modify the template for Word and PowerPoint.

**Comment by cderv** [comment]
Regarding those unused layout by Pandoc, this would be a question for them (https://github.com/jgm/pandoc/discussions) as why they are not recognized but present in the document template provided. 

I'll close this but you can share back here their answers. Thanks !
