### ISSUE TITLE
Revealjs Slides Blurry in Safari

### ISSUE THREAD

**Issue by eteitelbaum** [quarto-dev/quarto-cli#10996]
### Bug description

Suddenly my revealjs slides are blurred in Safari (but fine in Firefox and Chrome). As an example:

https://ds4all.rocks/slides/week-5.2#/title-slide

Code is here: 

https://github.com/eteitelbaum/dats1001-fall-2024/blob/main/slides/week-5.2.qmd

It is happening with multiple slide decks and seems to have corresponded with my updating to the pre-release version 1.6.18. 

### Expected behavior

Slides should render clearly.

### Actual behavior

Slides are blurry. 

### Your environment

RStudio: 2024.04.2 Build 764
MacOS: Ventura 13.6.7

### Quarto check output

GW-2J5QJVH:dats1001-fall-2024 ejt$ quarto --version
1.6.18
GW-2J5QJVH:dats1001-fall-2024 ejt$ quarto check
Quarto 1.6.18
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.18
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.06
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/ejt/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.5.0
      Kernels: billionaire_env, python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
[✓] Checking Jupyter engine render....OK

**Comment by mcanouil** [comment]
Please search for issues before opening one.

- https://github.com/quarto-dev/quarto-cli/issues/10842

**Comment by eteitelbaum** [comment]
OK. Just trying to help out. I would not have immediately made the connection between blurry slides and a chalkboard bug.

**Comment by cscheid** [comment]
@eteitelbaum That's a good catch, thank you. I should have added text that described the blurry slides and I didn't. It's fixed now!
