### ISSUE TITLE
Quarto should provide common tool paths to Lua filters

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#10999]
For example, `Rscript` is [hard to properly search for](https://github.com/quarto-dev/quarto-cli/blob/740829733499855335a7861e3c4f1333a09db45d/src/core/resources.ts#L84-L171). This means that extensions that need to find the same `Rscript` that Quarto uses have a hard time. Let's help them.

**Comment by cscheid** [comment]
We'll add `quarto.paths.rscript()` to the Lua API available to extensions.

**Comment by schloerke** [comment]
Thank you!
