### ISSUE TITLE
Feature request: Add support for toggling table of contents

### ISSUE THREAD

**Issue by officialcjunior** [quarto-dev/quarto-cli#110]
On frameworks like mdBook, the user can toggle the table of contents menu and view the reading material out in wide if they wish to.

Here's an example of that from the Rust language's book:
![animated](https://user-images.githubusercontent.com/29057155/133244458-46eb7b26-5bdd-4e34-9742-d0faa5ed933c.gif)

One can also control the width of the table of contents menu using the mouse, as well.

On quarto, it looks such a feature hasn't been implemented yet and would be lovely to have.

**Comment by jjallaire** [comment]
Yes, this is on our short list and will implement this soon!

**Comment by XVilka** [comment]
Sorry for being an annoyance, but had been there any updates on this? It currently prevents us to use Quarto instead of mdBook as the default builder.

**Comment by jjallaire** [comment]
No worries, apologize that we let this go so long. We recently implemented some page layout feature that allow for overflowing content into the margins. As part of this we implement dynamic hiding of the sidebar and doc. You can see if this if you start to scroll down on this page: https://quarto.org/docs/authoring/page-layout.html

It seems to me that we could do what you are looking for by simply allowing the user to manually switch into this "hidden mode"? @dragonstyle What do you think about this and where would be put the affordance to do this?

**Comment by jjallaire** [comment]
We've implement a "reader mode" toggle, documentation is here: https://quarto.org/docs/websites/website-navigation.html#reader-mode (note this works for both books and websites so you can put the `reader-mode` option underneath the `book` key as well)

**Comment by XVilka** [comment]
Thank you!

**Comment by dragonstyle** [comment]
Thanks for letting us know - this should be fixed and available in release v0.9 build 368.

**Comment by mghassany** [comment]
Great thanks, I confirm it is resolved in release v0.9 build 368.

**Comment by mghassany** [comment]
Maybe an additional feature request to this same subject: apply the same sidebar background color to the toggled menu in `reader-mode`. 
I am trying to manually modify it in css but I failed (I am not an expert). I found the background color in a `<div class="sidebar collapse sidebar-navigation docked overflow-auto slow rollup zindex-over-content quarto-sidebar-toggle-contents" style="background: rgb(255,255,255) none repeat scroll 0% 0%;">`

**Comment by dragonstyle** [comment]
Agree! just made that change as well (should be available shortly)
