### ISSUE TITLE
Listing useless items

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#1101]
There seems to be a nonsensical tile mixed in with the HTML site listing page (https://quarto.org/docs/websites/website-listings.html).
Note that it may disappear if I am editing files while `quarto preview` is running.

## `type: grid`

![image](https://user-images.githubusercontent.com/50911393/172596156-342cb1d3-ad0b-4883-8fff-7746d21315aa.png)

## `type: default`

![image](https://user-images.githubusercontent.com/50911393/172596980-331d17ae-4923-4533-b1bb-be71b07d4ead.png)

- Ubuntu 20.04
- quarto 0.9.545

source: https://github.com/rocker-org/website/blob/4b4675886c633b68fd05472eaa6ff2b16dcf0b22/use/index.md

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?

- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?

- [x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

- [x] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by eitsupi** [comment]
Thank you for responding so quickly!
I see that the reason is that I set aliases to `/use/*.md` files.

Unfortunately, however, 0.9.548 does not seem to have solved the problem.

**Comment by dragonstyle** [comment]
That was a great clue, thank you! Take 2 fix here:

30d5d9c45a07a2ee686dc65924f3b0c4fa87bed9

and new release building now...

**Comment by eitsupi** [comment]
0.9.550 seems fine! Thanks again!
