### ISSUE TITLE
images and logo are not displayed

### ISSUE THREAD

**Issue by LuiseSvG** [quarto-dev/quarto-cli#11024]
### Bug description

I am using Quarto Dashboard. Unfortunately, images are not displayed locally or on shinyapps.io. The logo in the navigation bar is also not displayed.

### Steps to reproduce

````markdown

---
title: "Patient*innenbefragung in den NRW Brustzentren"
format: dashboard
theme: Minty
logo: Logo/Logo_IMVR_ZVFK.png # does not work!
server: shiny
---

# start page

## Main body

## row {height="50%"}


![](Logo/Logo_IMVR_ZVFK.png){fig-alt="Image does not load" fig-align="center"}

![](Logo/EMMANRWLogoRosa.jpg){fig-alt="Image does not load" fig-align="center"}

````

### Expected behavior

The images are displayed on my start page.
The logo is displayed at the top left of the navigation bar.

### Actual behavior

The images are not displayed, instead a small icon is displayed and the alternative text.
The logo is not displayed at all.
For example please see ![Image](https://github.com/user-attachments/assets/b8899faa-c3a4-4076-afff-2c1c52f1d82a)
screenshot.

### Your environment

- IDE: R-Studio 2024.04.02+764
- OS: Windows 11

### Quarto check output

```
Quarto 1.5.57
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.57
      Path: C:\Users\goltzheim\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

(|) Checking basic markdown render....
(/) Checking basic markdown render....
(-) Checking basic markdown render....
(\) Checking basic markdown render....
(|) Checking basic markdown render....
(/) Checking basic markdown render....
(-) Checking basic markdown render....
(\) Checking basic markdown render....
(|) Checking basic markdown render....
(/) Checking basic markdown render....
(-) Checking basic markdown render....
[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

(|) Checking R installation...........
(/) Checking R installation...........
(-) Checking R installation...........
(\) Checking R installation...........
(|) Checking R installation...........
[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/goltzheim/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

(|) Checking Knitr engine render......
(/) Checking Knitr engine render......
(-) Checking Knitr engine render......
(\) Checking Knitr engine render......
(|) Checking Knitr engine render......
(/) Checking Knitr engine render......
(-) Checking Knitr engine render......
(\) Checking Knitr engine render......
(|) Checking Knitr engine render......
(/) Checking Knitr engine render......
(-) Checking Knitr engine render......
(\) Checking Knitr engine render......
(|) Checking Knitr engine render......
(/) Checking Knitr engine render......
(-) Checking Knitr engine render......
(\) Checking Knitr engine render......
(|) Checking Knitr engine render......
(/) Checking Knitr engine render......
[>] Checking Knitr engine render......OK
´´´

**Comment by cderv** [comment]
> Unfortunately, images are not displayed locally

Are the images located in your project directory ? is the relative path correct ? 

You did not share a full reproducible example so we can't say for sure what you've done. 

For example this is working with online image

````markdown
---
title: "Patient*innenbefragung in den NRW Brustzentren"
format: dashboard
theme: Minty
logo: https://quarto.org/quarto.png
---

# start page

## Main body

## row {height="50%"}

![](https://quarto.org/quarto.png){fig-alt="Image does not load" fig-align="center"}

![](https://quarto.org/quarto.png){fig-alt="Image does not load" fig-align="center"}

````

And if you download (`xfun::download_file("https://quarto.org/quarto.png", mode = 'wb')`) it works also

````markdown
---
title: "Patient*innenbefragung in den NRW Brustzentren"
format: dashboard
theme: Minty
logo: quarto.png
---

# start page

## Main body

## row {height="50%"}

![](quarto.png){fig-alt="Image does not load" fig-align="center"}

![](quarto.png){fig-alt="Image does not load" fig-align="center"}

````

Please do provide a reproducible example. Thanks !

**Comment by LuiseSvG** [comment]
Hello cderv,

Thank you very much for your quick reply!
Yes, the images are in my project folder and the relative path is correct. I have now also tried it with an online image, which works. Unfortunately, when I download the image and place it in my project folder, it no longer works. But I can also just work easily with the online image. Many thanks for the tip!

Best regards
Luise

**Comment by mcanouil** [comment]
@LuiseSvG How do you render your project and what does it look like?
Also, how to you preview your document?

**Comment by cderv** [comment]
> Unfortunately, when I download the image and place it in my project folder, it no longer works. But I can also just work easily with the online image. Many thanks for the tip!

If you want us to help you understand, please do share your project or a reproducible example that have the issue. 

Otherwise, if you're happy with online image solution, we'll probably close this issue. 

Thanks

**Comment by LuiseSvG** [comment]
Hi together,

I render and preview my project with quarto. To deploy it I use shinyapps.io and the package rsconnect. 
I have created a reproducible example that have the issue, but I honestly haven't figured out how to upload the project folder yet. I am working on it. 
Thanks for your help!

**Comment by mcanouil** [comment]
You can share it as a Git repository.

Is the shiny components required to produce the issue?
The basic idea to create a small reproducible example is to remove pieces one by one.
If you remove something and the error is still there, then keep removing.
If you remove something and the error is not there, then put back the piece you've just removed and remove other pieces.
At the end you should have something small that reproduces the issue.
Most of the time, especially is the issue is not on the software side, this process will help yo fix the issue yourself.

**Comment by LuiseSvG** [comment]
Hi Mcanouil, 
thanks for your tip! I deleted all the code that is not needed to display the images. Then it worked. When I added “server: shiny” to the document options again, it no longer worked. Then I could only use images with web addresses as path, but paths that led to my folders no longer worked.

**Comment by cderv** [comment]
> When I added “server: shiny” to the document options again, it no longer worked.

See our documentation on interactive document using Shiny. There is some specificity as your are working with a Shiny Apps (made from Quarto document, but still the product is a shiny app served through `quarto server`)

- https://quarto.org/docs/interactive/shiny/resources.html#asset-resources

Images needs to be in `images/` folder so that they are correctly made available by the Shiny server.

**Comment by LuiseSvG** [comment]
Thank you very much for this advise! It is now working :)
