### ISSUE TITLE
error: Uncaught 

### ISSUE THREAD

**Issue by 5t4t1ck** [quarto-dev/quarto-cli#1103]
Good morning, I am working on a Python/Django tutorial and I decided to use Quarto to generate the necessary commands.

At the moment of generating the tutorial I get the following error

![image](https://user-images.githubusercontent.com/4395506/172636378-ba87aec9-ab8f-4e74-8039-c2db37a27441.png)

![image](https://user-images.githubusercontent.com/4395506/172633275-dece2cfe-7433-45b8-a82e-5854434a983b.png)

`error: Uncaught (in promise) Error: Is a directory (os error 21)
        return parse6(new TextDecoder("utf-8").decode(await Deno.readFile(filepath)));
                                                      ^
    at async Object.readFile (deno:runtime/js/40_read_file.js:24:20)
    at async parseFileAsync (file:///opt/quarto/bin/quarto.js:22537:55)
    at async config (file:///opt/quarto/bin/quarto.js:22514:18)
    at async Object.dotenv (file:///opt/quarto/bin/quarto.js:22616:28)
    at async file:///opt/quarto/bin/quarto.js:92983:23`

Previously I installed Jupyter Notebook but it does not run.

**Comment by jjallaire** [comment]
Thanks so much for reporting this! Fix is here: https://github.com/quarto-dev/quarto-cli/commit/3f4f116678feab76cddf3e7097fd13e6d5ea9287 (fix is avail in the latest binary release)
