### ISSUE TITLE
Feature request: Show listing `image` on the post as a featured image

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#1105]
It would be nice to have the option to show the listing `image` in the actual post as a featured image. This would require getting the sizing and layout correct and I imagine two types of images might be needed: a square one for listing and a rectangular one as a banner on post page.

**Comment by jjallaire** [comment]
Thanks, we'll look at this after v1.0!

**Comment by mcanouil** [comment]
I believe this to be completed but the other way around.
Preview images are detected when not set, see <https://quarto.org/docs/websites/website-listings.html#listing-fields>.
