### ISSUE TITLE
Quarto website - add "simple publication ready article how-to"

### ISSUE THREAD

**Issue by tomkom** [quarto-dev/quarto-cli#111]
I have just found out the updated version of the Quarto website, nice effort. This is only a small suggestion - the "Projectys" tab could contain one more entry - the very basic use case why this project is of interest - a simple equivalent of a quarto paper.

By that I mean the set up of a project equivalent of a Latex "article" class (no chapters and complex elements like TOC) showing a "reproducible report" setup.

An amazing bonus would be to show the equivalent of what is possible with RMD where a Latex template can be specified. I am not sure whether this is even possible ( yet), but especially in the Python world, the ability to transform a ipynb to a camera-ready result based on a Latex class template is a massive gap in capabilities.

**Comment by jjallaire** [comment]
Thanks for the feedback! I agree that this is left a bit too much to the readers imagination in the current site. We have the Gallery page (https://quarto.org/docs/gallery/) however the PDF example there is the Pandoc manual which isn't terribly illustrative for the case of creating a paper.

You can indeed currently specify a custom template using the `template` option. That said, there is an issue related to the fact that custom templates sometimes miss on integration with various pandoc features (i.e. there is coupling between pandoc's options/behavior and its default template). Our hope is to create a cleaner way to produce custom templates that "inherit" more of the base functionality (and once we have that sorted out produce more documentation on custom templates and even port a bunch of the [rticles](https://pkgs.rstudio.com/rticles/articles/articles/examples.html) templates to Quarto.

**Comment by tomkom** [comment]
Thank you! Yes, for someone who is happy to dig through github etc, I think that a solution can be found. I was just recommending to add a menu item with the *simplest possible camera ready* conference or journal output, based on a tex/bibtex template set. This is what most users ( I believe) would be after.

I would be glad to try to add additional workflows for a specific conference/journal ( in my domains) if we had a template workflow. 

I believe a good start would be something like the ACM template, or something from Taylor&Francis, PLOSOne or similar. If there was a sample workflow, I would try to adapt it to some of the journals/conferences in my field (time permitting), and would be happy to share back. 

Thanks for the stellar work on this!

**Comment by jjallaire** [comment]
Okay, so perhaps a project that contains:

1) A LaTeX template from e.g. ACM
2) A CSL file 
3) A bibliography
4) Skeleton qmd file that uses all of the above

Note that we are hoping to make all of this _much_ more straightforward soon (by allowing packaging of all of the above into an installable custom format). I'd also like to make inclusion of core pandoc "boilerplate" in custom templates much more straightforward than copy and paste via partials.

**Comment by jjallaire** [comment]
You can use CSL files now via the `csl` option: https://quarto.org/docs/authoring/footnotes-and-citations.html#citation-style

**Comment by dragonstyle** [comment]
We are beginning to implemen package extensions that include behavior as described above -  you can see some examples here:

https://www.github.com/quarto-journals/
