### ISSUE TITLE
Hover popup for cross references doesn't work across book chapters

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#11129]
### Bug description

Consider a simple book with two chapters:

`_quarto.yml`:
```
project:
  type: book

book:
  title: "My Book"
  chapters:
    - index.qmd
    - chap-1.qmd
 ```

`ìndex.qmd`:
````
# Introduction {#sec-intro}

Some text and a figure

```{r}
#| label: fig-plot
#| fig-cap: "This is a plot."
plot(1:10)
```

Some references: @fig-plot and @sec-intro.
````

`chap-1.qmd`:
```
# Chapter 1

Some references: @fig-plot and @sec-intro.
```

In this book, the hover popup for references within the `index.qmd`-chapter works, but not for references within the `chap-1.qmd`-chapter which looks like this (the small white rectangle):

![Image](https://github.com/user-attachments/assets/2e70a6d8-062d-4e1f-b012-aad92c3e59d8)

This used to work but I'm unsure when it stopped working. 

### Your environment

- OS: Windows 11

### Quarto check output

```
Quarto 1.6.28
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.6.28
      Path: C:\Users\au234616\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: C:/Users/au234616/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.2.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.4.1
      Path: C:/Users/au234616/AppData/Local/Programs/R/R-4.4.1
      LibPaths:
        - C:/Users/au234616/AppData/Local/R/win-library/4.4
        - C:/Users/au234616/AppData/Local/Programs/R/R-4.4.1/library
      knitr: 1.48.3
      rmarkdown: 2.28

[>] Checking Knitr engine render......OK
```

**Comment by snhansen** [comment]
I just figured out that this is only an issue when previewing the book locally but not when deployed to a web-server, i.e. it works fine here https://biostat.au.dk/stefan/test/chap-1.html but not when previewing it on my local machine (tested both Firefox and Chrome).

**Comment by mcanouil** [comment]
From what you are saying, it will work if you serve the website from a web server, using the Live preview VSCode extension, or using Python to start a web server, etc.

That's a "limitation" of web technologies, they are designed to work through http and other related protocols, not through the file protocol used when you open an HTML file stored locally.
This phenomenon is not limited to Quarto.

**Comment by snhansen** [comment]
Gotcha. I guess this isn't a bug after all then, so I'm closing it. Sorry about the fuss.

**Comment by cscheid** [comment]
Specifically, html files open through `file://` aren't allowed to do a number of things we need, like using ES6 javascript modules. ES6 modules can resolve relative paths, and that would be a massive security risk to run from the file system.
