### ISSUE TITLE
GLightbox options cause HTML output to change

### ISSUE THREAD

**Issue by winniehell** [quarto-dev/quarto-cli#11122]
### Bug description

Order of GLightbox options changes on (almost) every HTML rendering. This may sound like a minor cosmetic detail but it causes the checksum of the output file to change and therefore makes caching more difficult.

### Steps to reproduce

Use any document containing an image, e.g.

```qmd
---
title: "Empty"
format: html
engine: jupyter
---

![An image]()
```

run the following commands:

```shell
quarto render --to html --output-dir output1
quarto render --to html --output-dir output2  # you may need to run this step more than once
diff output1/index.html output2/index.html
```

### Expected behavior

Output does not differ because input has not changed.

### Actual behavior

Order of GLightbox options is changed, e.g.

```diff
515c515
< <script>var lightboxQuarto = GLightbox({"selector":".lightbox","descPosition":"bottom","loop":false,"closeEffect":"zoom","openEffect":"zoom"});
---
> <script>var lightboxQuarto = GLightbox({"loop":false,"selector":".lightbox","openEffect":"zoom","descPosition":"bottom","closeEffect":"zoom"});
```

### Your environment

nixos-version: 24.05.20241012.a3f9ad6 (Uakari)

### Quarto check output

<details>
<summary>quarto check</summary>

```
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      commit: 71945532e1fc1a5cf113117f6d5ff5bee3991797
      Path: ~/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /run/current-system/sw/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.5
      Path: ~/quarto-playground/.venv/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
</details>

**Comment by winniehell** [comment]
I don't know Lua but using `pairsByKeys` for `optionsJson` may solve the problem:

https://github.com/quarto-dev/quarto-cli/blob/71945532e1fc1a5cf113117f6d5ff5bee3991797/src/resources/pandoc/datadir/_utils.lua#L24-L25

https://github.com/quarto-dev/quarto-cli/blob/71945532e1fc1a5cf113117f6d5ff5bee3991797/tests/docs/extensions/basic/_extensions/quarto-ext/lightbox/lightbox.lua#L181-L184

```diff
-      local optionsJson = quarto.json.encode(options)
+      local optionsJson = pairsByKeys(quarto.json.encode(options))
```

**Comment by mcanouil** [comment]
Thanks, I thought I add open an issue about this four months ago but apparently not since I can't find it ...

Here the relevant comments/codes from the previous discussion:

- https://github.com/quarto-dev/quarto-cli/blob/71945532e1fc1a5cf113117f6d5ff5bee3991797/src/resources/filters/layout/lightbox.lua#L371-L382

- > we have implemented sortedPairs multiple times throughout the codebase... we should pull it into quarto.utils.table and then just use that
  > - https://github.com/quarto-dev/quarto-cli/blob/71945532e1fc1a5cf113117f6d5ff5bee3991797/src/resources/pandoc/datadir/_utils.lua#L239-L252
