### ISSUE TITLE
Can't capitalize inline cross-references

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#1113]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1112

<div type='discussions-op-text'>

<sup>Originally posted by **arnaudgallou** June  9, 2022</sup>
I can't manage to capitalize a cross-reference by changing the syntax of the inline reference as explained in the [documentation](https://quarto.org/docs/authoring/cross-references.html#references).

Below is an [example](https://github.com/arnaudgallou/dummy-qmd/blob/main/crossrefs/crossrefs.qmd) with the resulting output being visible [here](https://github.com/arnaudgallou/dummy-qmd/blob/main/crossrefs/crossrefs.md).

```
---
title: Cross references
editor_options:
  markdown: 
    wrap: sentence
format: gfm
crossref: 
  title-delim: .
  fig-title: Fig.
  fig-prefix: fig.
  eq-prefix: eq.
fig-format: svg
---

## Figures

{{< include ../_figure.qmd >}}

**single plot**

@fig-foo

@Fig-foo

**faceted plot**

[@fig-foo]A

**supplementary plot**

Fig. S[-@fig-foo]

## Equations

$$\alpha=2$$ {#eq-a}

@eq-a

@Eq-a
```

I'm using Quarto v. 0.9.549 on RStudio v. 4.2.0, running on macOS Monterey.</div>

**Comment by cderv** [comment]
I believe this is an issue because of several change made in the past. 

First, https://github.com/quarto-dev/quarto-cli/commit/3ea3313465de18dfa5a4842d0692395c11fb4739 needs to take into account the `type` can be `fig` or `Fiq`. However fixing this is not enough 
```diff
--- a/src/resources/filters/crossref/refs.lua
+++ b/src/resources/filters/crossref/refs.lua
@@ -144,7 +144,7 @@ function refLabelPattern(type)
 end

 function isValidRefType(type)
-  return tcontains(validRefTypes(), type)
+  return tcontains(validRefTypes(), text.lower(type))
 end

 function validRefTypes()
````

We will correctly enter the resolution part
https://github.com/quarto-dev/quarto-cli/blob/a450f1c0ff7017c7b28b9c1cc38ce2345a3d0b88/src/resources/filters/crossref/refs.lua#L19-L31

However, `label` is not found 
```
local entry = crossref.index.entries[label]
```
because it has been made case insentive in https://github.com/quarto-dev/quarto-cli/commit/f7adb0af4ab959eb36b239f37edc36a575ba8a25 
https://github.com/quarto-dev/quarto-cli/blob/a450f1c0ff7017c7b28b9c1cc38ce2345a3d0b88/src/resources/filters/crossref/refs.lua#L17

I don't have the whole context for this last change @jjallaire - it seems there was a reason to make this change, however it seems to break the capitalized feature. Putting the `text.lower()` back fix the aforementioned issue. That is why I am reporting here with additional information and not providing a fix.

**Comment by jjallaire** [comment]
Fix for this should be here: https://github.com/quarto-dev/quarto-cli/commit/20fa4b3fca1074a70e9f1255bb9522edb04af138

@cderv I don't recall what the exact motivation for making the lookups case sensitive was (perhaps it's b/c latex refs or html ids are case sensitive? I don't recall). Rather than revisit this I've made a more targeted change that preserves the case sensitivity w/o breaking the lookups:

(1) Make the `refType()` function handle uppercase refs correctly
(2) Lowercase on the first letter of labels for lookups
