### ISSUE TITLE
ref divs are not ignored

### ISSUE THREAD

**Issue by raffaem** [quarto-dev/quarto-cli#11145]
### What would you like to do?

Report an issue on quarto.org

### Description

Consider the following MWE.

main.qmd:
```
---
title: "Title"
bibliography: bibliography.bib
format:
  pdf:
    cite-method: biblatex
---

# Section 1

Lorem ipsum @marshallSamplingQualitativeResearch1996

# References

::: {#refs}
:::

# Appendix 

This is an appendix
```

bibliography.bib
```
@article{marshallSamplingQualitativeResearch1996,
  title = {Sampling for Qualitative Research},
  author = {Marshall, Martin N},
  date = {1996-01-01},
  journaltitle = {Family Practice},
  shortjournal = {Family Practice},
  volume = {13},
  number = {6},
  pages = {522--526},
  issn = {0263-2136},
  doi = {10.1093/fampra/13.6.522},
  url = {https://doi.org/10.1093/fampra/13.6.522},
  urldate = {2024-10-22},
  abstract = {The probability sampling techniques used for quantitative studies are rarely appropriate when conducting qualitative research. This article considers and explains the differences between the two approaches and describes three broad categories of naturalistic sampling: convenience, judgement and theoretical models. The principles are illustrated with practical examples from the author's own research.},
  file = {/mnt/dataint/data/zotero/storage/SY27VB9N/Marshall - 1996 - Sampling for qualitative research.pdf}
}
```

Now render it with
```
quarto render main.qmd
```

In the resulting file the reference section precedes the appendix:
![Image](https://github.com/user-attachments/assets/575846ae-a245-49df-a0eb-ca80a62b8034)

But the [documentation says](https://quarto.org/docs/authoring/citations.html#bibliography-generation):

> If your bibliography is being generated using BibLaTeX or natbib ([Section 7](https://quarto.org/docs/authoring/citations.html#sec-biblatex)), the bibliography will always appear at the end of the document and the #refs div will be ignored.

**Comment by cderv** [comment]
Thanks for catching that. This is indeed now supported since Quarto 1.3 (c15360b663c6ba82520994346e3bfb5b3ef48609)
