### ISSUE TITLE
tinytex installation and location error?

### ISSUE THREAD

**Issue by ifateri** [quarto-dev/quarto-cli#1116]
### Bug description

Hello,

I used the following to install TinyTex in a VSCode terminal on Windows 10.0.19044:
```
quarto tools install tinytex
```
Which outputted:
```
Installing tinytex
[>] Downloading TinyTex v2022.05
[>] Unzipping TinyTeX-v2022.05.zip
[>] Moving files
[>] Verifying tlgpg support
[>] Default Repository: https://ctan.math.illinois.edu/systems/texlive/tlnet/
[>] Updating paths
ERROR: suggestUserBinPaths not currently supported on Windows
```

When I try to render a qmd to PDF I get the error:
```
running xelatex - 1

No TeX installation was detected.

Please run 'quarto tools install tinytex' to install TinyTex.
If you prefer, you may install TexLive or another TeX distribution.
```

Which is weird because I can see the TinyTex folder sitting in C:\Users\myname\AppData\Roaming which as far as I can tell is the intended behaviour? And when I try to re-install TinyTex using the first command it will abort and say there already is a TinyTex installation.

quarto check:
```
[>] Checking Quarto installation......OK
      Version: 0.9.393
      Path: C:\Users\myname\AppData\Local\Programs\Quarto\bin\
      CodePage: unknown

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: C:/Users/myname/scoop/apps/python/current/python.exe
      Jupyter: 4.10.0
      Kernels: python3

[>] Checking Jupyter engine render....OK
```

It looks like TinyTex can't be found whilst rendering? I'm completely clueless about LaTeX installations so I tried following the recommended installation..

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by dragonstyle** [comment]
Thanks for reporting this, this was indeed bad! You should be able to do the following in the latest release:

0) Install the latest release

1) Uninstall the previous version of tinytex, using:

`quarto tools uninstall tinytex`

2) Re-install tinytex (this should work correctly this time)

`quarto tools install tinytex`

3) Render a PDF and enjoy!

**Comment by ifateri** [comment]
Thank you for the quick solution!
