### ISSUE TITLE
Add abstract / summary to html template

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#112]
The default pandoc html template can take an abstract text from the metadata, but for quarto this currently only works for pdf and docx output, and there it omits the "abstract" heading. This would be key for things like research papers (see https://github.com/quarto-dev/quarto-cli/issues/111).

**Comment by jjallaire** [comment]
Interestingly I don't actually see an `abstract` field used in the default HTML template: https://github.com/jgm/pandoc-templates/blob/master/default.html5. Seems like an oversight? Perhaps file an issue on the pandoc repo about this? (we can certainly patch the default template in quarto but I think it's better if this changes makes it into the default template)

**Comment by jmbuhr** [comment]
I made a PR for pandoc :) https://github.com/jgm/pandoc-templates/pull/17

**Comment by jmbuhr** [comment]
It has been merged into pandoc master, so we can close this issue once pandoc has a new release :)

**Comment by jmbuhr** [comment]
Closed by https://github.com/quarto-dev/quarto-cli/commit/4a2f2e35fc13789904118a5d900001b76a7b9d91
