### ISSUE TITLE
Images Not Rendering with Up-Level Paths in HTML Output

### ISSUE THREAD

**Issue by pfaffrob** [quarto-dev/quarto-cli#11217]
### Bug description

When I include a image with a path going up a folder level, then that image is not rendered when rendering as html. (However, it works when setting the output format to pdf.)

### Steps to reproduce

Folder structure:

Project_Name/
  - images/
    - my_image.png
  - html/
    - file.qmd

This is the file.qmd document:

```md
````qmd
---
title: "My Project"
format: html
---


![MyImage](../images/my_image.png)

```

Then in bash: `quarto render file.qmd`

### Expected behavior

The image should be included in the html output.

### Actual behavior

When opening the html file in the web browser, it looks like this:

![Image](https://github.com/user-attachments/assets/276000a8-a320-441e-8ee3-3d6088a56490)

### Your environment

- IDE: VS Code Version: 1.94.2
- OS: Sequoia 15.0.1

### Quarto check output

Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.06
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/robinpfaff/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.4 (Conda)
      Path: /opt/anaconda3/envs/DL/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
      knitr: 1.47
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")

**Comment by mcanouil** [comment]
Are you using `_quarto.yml`?
I'm guessing you don't.
Quarto's philosophy is that all should be within the project.
A project is defined by the file I mentioned earlier or by the single-document.
Paths cannot go outside the project by design and as documented.

**Comment by pfaffrob** [comment]
Oh god, such a simple explanation that I was somehow blind to until now. Major eye-opener. Thank you very much for the quick answer!
