### ISSUE TITLE
`quarto render` with `code-link: true` can report an incorrect warning about package requirements

### ISSUE THREAD

**Issue by DavisVaughan** [quarto-dev/quarto-cli#1121]
It looks like the way `code-link: true` works is through this R script
https://github.com/quarto-dev/quarto-cli/blob/f30845bb322ec9bbfcb4b5e6e12887aa902f5fcc/src/resources/rmd/rmd.R

If I uninstall one of the dependencies you use there, say, jsonlite, and try and run `quarto render` then I get:

```r
[ 1/15] posts/2022-03-11-using-vs-code-to-debug-r-packages-with-c-code/index.qmd
Error in loadNamespace(x) : there is no package called ‘jsonlite’
Calls: .main ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
WARNING: Unable to perform code-link (code-link requires R and the downlit package)
```

So the error message from R is right but the warning from quarto is a little off.

Maybe there should be some kind of up front check for all of the dependencies required to run that script? Like xfun, knitr, rmarkdown, htmltools, etc.

Run with quarto 0.9.344

**Comment by jjallaire** [comment]
What is the dependency list you derived? I'd guess we would need jsonsite and perhaps yaml?

**Comment by cderv** [comment]
is installing **rmarkdown** in addition not enough to get everything else ? 

Out of curiosity I ran **renv** on the `rmd/` folder with the R script 

``` r
unique(renv::dependencies("src/resources/rmd")$Package)
#> Finding R package dependencies ... Done!
#>  [1] "htmltools"   "htmlwidgets" "jsonlite"    "knitr"       "rmarkdown"  
#>  [6] "tools"       "xfun"        "yaml"        "rlang"       "shiny"      
#> [11] "utils"       "downlit"     "xml2"
```

This seems close to [your list](https://github.com/DavisVaughan/blog/actions/runs/2471032800/workflow#L71-L93) @DavisVaughan 

If we remove base package and those that are deps of the other and should be installed anyway we get 
``` r
pkgs <- unique(renv::dependencies("~/DEV_R/quarto-cli/src/resources/rmd")$Package)
#> Finding R package dependencies ... Done!
pkgs <- setdiff(pkgs, xfun::base_pkgs())
pkgs <- purrr::set_names(pkgs)
deps <- purrr::map(pkgs, pak::pkg_deps)
#> 

length(deps)
#> [1] 11

purrr::discard(pkgs, ~ {
  pkg <- .x
  purrr::map_lgl(deps[- which(names(deps) == pkg)], ~ {
    pkg %in% .x$package
  }) |> any()
})
#>   htmlwidgets     rmarkdown         shiny       downlit          xml2 
#> "htmlwidgets"   "rmarkdown"       "shiny"     "downlit"        "xml2"
```

If when freeze is activated, only `rmd.R` is used, then we have a shorter version
``` r
pkgs <- unique(renv::dependencies("~/DEV_R/quarto-cli/src/resources/rmd/rmd.R")$Package)
#> Finding R package dependencies ... Done!
pkgs <- setdiff(pkgs, xfun::base_pkgs())
pkgs <- purrr::set_names(pkgs)
deps <- purrr::map(pkgs, pak::pkg_deps)
#> 

length(deps)
#> [1] 7

purrr::discard(pkgs, ~ {
  pkg <- .x
  purrr::map_lgl(deps[- which(names(deps) == pkg)], ~ {
    pkg %in% .x$package
  }) |> any()
})
#>     downlit   rmarkdown        xml2 
#>   "downlit" "rmarkdown"      "xml2"
```

If only `postprocess()` is called when `freeze` is activated, possibly we could to a subset of **rmarkdown** like 
jsonlite, xfun, knitr, htmltools (and downlit + xml2)

But for documentation or warning report, saying that 3 packages (rmarkdown, downlit, xml2) are needed seems easy.

**Comment by jjallaire** [comment]
Agreed, I think we should just update the message to mention those three packages.

**Comment by DavisVaughan** [comment]
Yea I think mentioning rmarkdown is enough. I just confirmed in https://github.com/DavisVaughan/blog/commit/e20b5d69ad6ac48b2d45d0e75195ed758519f17d that everything works with just rmarkdown

**Comment by jjallaire** [comment]
Addressed here: https://github.com/quarto-dev/quarto-cli/commit/aa4e4795648d1bc473b07f43e37e6176ce54922f
