### ISSUE TITLE
`engine: julia` freezes when using inline Makie Animations (`Record`)

### ISSUE THREAD

**Issue by johannes-menzel** [quarto-dev/quarto-cli#11248]
### Bug description

Hi,

I am trying to use Makie animations in a quarto document, but the execution freezes at the cell in which I create the animation.   
Specifically, if I set `engine: julia` at the top of the document the freeze occurs.
However, if I define `jupyter: julia-1.11` at the top instead, the execution works just fine.   
For the  `engine: julia` case, I have noticed that Makie calls ffmpeg internally, which seems to be the step where the execution gets stuck on.   
See the code below for a test-case.
I used quarto-1.6.32 and Julia 1.11.1 and I have tested this on two different Linux machines.
 

### Steps to reproduce

I tested this scenario with the following .qmd file:

````qmd
---
engine: julia
---

```{julia}
using Pkg
Pkg.activate(".")
Pkg.instantiate()
using CairoMakie
```

## Test

test 

```{julia}
#| output: true
#| label: fig-animation
#| fig-cap: Test animation
function animation()
    points = Observable(Point2f[(0, 0)])

    fig, ax = scatter(points)
    limits!(ax, 0, 30, 0, 30)

    frames = 1:1000

    Record(fig, frames;
            framerate = 30) do frame
        new_point = Point2f(frame, frame)
        points[] = push!(points[], new_point)
    end
end

animation()
```
````
The animation is taken from Makie's documentation: [link](https://docs.makie.org/dev/explanations/animation#Appending-data-with-Observables)
Note that a Julia environment with Makie and CairoMakie needs to installed in the same directory where this sample .qmd file is located.
The render command I used is: `quarto render test.qmd`

### Your environment

- OS1:  Tuxedo OS 2 - kernel: Linux 6.11.0-103009-tuxedo
- OS2: Red Hat Enterprise Linux 8.8 (Ootpa) - kernel: Linux 4.18.0-477.51.1.el8_8.x86_64

### Quarto check output

Quarto 1.6.32
[✓] Checking environment information...
      Quarto cache location: /home/jmenzel/.cache/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.32
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: python3, julia-1.11, julia-1.10

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by mcanouil** [comment]
I'm not sure that's Quarto's fault.
Try the Julia commands outside of Quarto.

It takes "forever" to execute.

**Comment by mcanouil** [comment]
It works with `engine: jupyter`.

![Image](https://github.com/user-attachments/assets/7896c185-f136-4c5c-99bc-5ee1fbe6b5f3)

So I would assume it's an issue with `QuartoNotebookRunner.jl`.

@MichaelHatherly @jkrumbiegel if you have any clue here.

**Comment by jkrumbiegel** [comment]
I don't think we're testing movie MIME types for QuartoNotebookRunner, yet, so it's possible that the problem lies there. I would try a small size recording with one or two frames first to exclude that it just takes really long because there are many frames and QuartoNotebookRunner is slow for some reason. If that also freezes there's probably a more fundamental problem with this MIME  type and it would be interesting to see if any other library that can create videos would also freeze here.

**Comment by jkrumbiegel** [comment]
This was not a video mimetype issue after all, this issue here can be closed as it seems to be a bad interaction between the two Julia packages Makie and IOCapture as noted here https://github.com/MakieOrg/Makie.jl/pull/4562

**Comment by mcanouil** [comment]
Thanks @jkrumbiegel, your help was really appreciated. (I don't use Julia very often).

I'm keeping this open until, your PR is merged upstream.

**Comment by cderv** [comment]
@mcanouil I think we can close as this is related to some Julia packages independant to quarto and https://github.com/MakieOrg/Makie.jl/pull/4562 has been merged. 

So this will require package update in Julia itself by users. 

Thanks everyone !

**Comment by johannes-menzel** [comment]
Thank @jkrumbiegel for fixing this so quickly. Is there any schedule for the next minor release of Makie, so that I can use it without relying on an in-development version?

**Comment by jkrumbiegel** [comment]
@johannes-menzel this will go in the next patch, so within the next couple days probably
