### ISSUE TITLE
`&amp;name=large.png`  added to markdown image urls

### ISSUE THREAD

**Issue by richardsprague** [quarto-dev/quarto-cli#11247]
### Bug description

how come this markdown image

`![](https://pbs.twimg.com/media/Ga-G5MtWIAAjpC6?format=jpg&name=large)`

gets turned into this html:

`<p><img src="https://pbs.twimg.com/media/Ga-G5MtWIAAjpC6?format=jpg&amp;name=large.png" class="img-fluid" data-format="image/jpeg"></p>`

Note the `&amp;name=large.png` appended to the end of the src url.

### Steps to reproduce

make a qmd file with this line

`![](https://pbs.twimg.com/media/Ga-G5MtWIAAjpC6?format=jpg&name=large)`

quarto render

### Quarto check output

Quarto 1.5.45
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.45
      Path: /Applications/quarto/bin

**Comment by cscheid** [comment]
This behavior comes from Pandoc, but in HTML, `&amp;` is a way to escape `&`. This should all work. See the request you get from your browser tools:

![Image](https://github.com/user-attachments/assets/0e2b7079-3902-4e11-ac1d-69a72f47c77d)

I don't think there's a bug here.

**Comment by richardsprague** [comment]
You sure?


Two identical files, one is `pngappend.md` and the other is `pngappend.qmd`
```markdown
![](https://pbs.twimg.com/media/Ga-G5MtWIAAjpC6?format=jpg&name=large)
```

` pandoc -f markdown -t html -o pngappend.html pngappend.md`

correctly renders `pngappend.html`

```html
<p><img

src="https://pbs.twimg.com/media/Ga-G5MtWIAAjpC6?format=jpg&amp;name=large" /></p>
```


but 

`quarto render pngappend.qmd`

generates a bunch of stuff including this line

```html

<p><img src="https://pbs.twimg.com/media/Ga-G5MtWIAAjpC6?format=jpg&amp;name=large.png" class="img-fluid"></p>
```

**Comment by mcanouil** [comment]
The "src" attribute is exactly the same in both of the outputs you shared.

**Comment by cscheid** [comment]
Quoting from your answer:

> ` pandoc -f markdown -t html -o pngappend.html pngappend.md`
> 
> correctly renders `pngappend.html`
> 
> <p><img
> 
> src="https://pbs.twimg.com/media/Ga-G5MtWIAAjpC6?format=jpg&amp;name=large" /></p>

See the `&amp;` string there?

**Comment by richardsprague** [comment]
The `&amp;` string is fine, and it's found it both the Quarto and Pandoc output. But Quarto additionally appends an extra `.png` to the src, and that breaks the image rendering. If I manually remove the Quarto final `.png` it works fine.  

I can also do this workaround, which renders properly in both Quarto and Pandoc:

```markdown
<img src="https://pbs.twimg.com/media/Ga-G5MtWIAAjpC6?format=jpg&name=large" alt="">
```
why does Quarto append that extra `.png` ?

(Might be unrelated, but back in [#7102](https://github.com/quarto-dev/quarto-cli/issues/7102) I thought it was reasonable that Quarto decided to not guess the image type, so I wonder if this is a change?)

**Comment by cderv** [comment]
> why does Quarto append that extra .png ?

This is added because of `default-image-extension` is PNG by default in Quarto. See for more context
- https://github.com/quarto-dev/quarto-cli/issues/6092

If you do `default-image-extension: ""` in the YAML confirm for the document, there should not be any extension added.

**Comment by cscheid** [comment]
> If you do `default-image-extension: ""` in the YAML confirm for the document, there should not be any extension added.

Thanks for the added context. @tarleb what do you think about a change to the default-image-extension behavior where Pandoc would try to append the extension _before_ the URL params, if it finds them?

**Comment by tarleb** [comment]
This seems related to https://github.com/jgm/pandoc/issues/9118. It could be argued that the fix for that issue was incomplete, and that URLs should never be altered. Are there situations in which the `default-image-extension` *should* be added to URLs?

**Comment by cderv** [comment]
> Are there situations in which the default-image-extension should be added to URLs?
> Having that feature limited to local images would seem reasonable to me.

I think most common use case if local image, but you could imagine users (of Quarto or Pandoc) that would have there image online with a .png and .pdf version available and they would like html format to use .png and pdf format to use pdf format. 

Doing this with `default-image-extension` sets to png for html, and to pdf for pdf output would make this markdown syntax work. 
```markdown
[Caption](https://mysite.co/my-img)
```

Not that common but could happen. So it would be a breaking change for such users. A choice to make. 

For the story we do set `default-image-extension: "png"` for `format: html` and `default-image-extension=pdf` for `format: pdf` so that you can use one link for multiformat output
````markdown
---
format:
  pdf: default
  html: default
---

[Caption](images/my-awesome-img)
````

> try to append the extension before the URL params, if it finds them

Doing this would insure nothing is broken IMO. And this would indeed complete https://github.com/jgm/pandoc/issues/9118.

**Comment by tarleb** [comment]
I've opened jgm/pandoc#10355 to keep track of this.
