### ISSUE TITLE
Dashboards - Value Box

### ISSUE THREAD

**Issue by Btibert3** [quarto-dev/quarto-cli#11258]
### What would you like to do?

Report an issue on quarto.org

### Description

I was referring to the documentation for displaying value boxes on a Quarto dashboard.  The code samples show `content:` but it seems we need to use `component:`, which I found by going through some of the examples.

**Comment by mcanouil** [comment]
Thanks for the report, unfortunately, it's hard to understand what you are referring to or even what you are reporting/suggesting here.

Please elaborate on what your feedback is and where you found an issue by providing a link to the rendered documentation or to the source file.

**Comment by Btibert3** [comment]
The documentation on [this page](https://quarto.org/docs/dashboards/data-display.html#value-boxes):  defines the value box with `content`.  A code sample from that page:

```
## Row 

```{python}
#| content: valuebox
#| title: "Articles per day"
#| icon: pencil
#| color: primary
dict(
  value = articles
)
```

I wasn't able to get the value box to render until I changed `content` to `component`.

```{python}
#| component: valuebox
#| title: "Articles per day"
#| icon: pencil
#| color: primary
dict(
  value = 15
)
```

I made the change based on this [example](https://github.com/jjallaire/nfl-injuries-dashboard/blob/main/nfl-injuries.qmd).

**Comment by mcanouil** [comment]
Thanks for the clarification and report.

**Comment by Btibert3** [comment]
Not a problem.  It took me a hot minute to realize the difference.  Not
sure it's relative to my version or local, but wanted to report it in case
there was a change in the library.

**Comment by mcanouil** [comment]
May I ask which version of Quarto you are using?

**Comment by Btibert3** [comment]
Good question.  1.4.554.  It might be time for an upgrade, especially if
the syntax changed.  Thanks for calling that out.  I am using this in my
class later tonight and I am certain the students will be downloading the
latest version.

Cheers.

**Comment by mcanouil** [comment]
Both syntaxes work for your information. Quarto tries to not break anything so the `components` might be an old name.
Could you let us know if you still have an issue with `content` using 1.5.58?
Note that the Quarto website is now displaying the 1.6 Release Candidate, so your student will very likely use a version quite different from yours.
https://quarto.org/docs/get-started/

**Comment by Btibert3** [comment]
No issues, thanks so much for your help!
