### ISSUE TITLE
RevealJS: slides with a level 1 header cannot be scrollable

### ISSUE THREAD

**Issue by GuillaumeDehaene** [quarto-dev/quarto-cli#11300]
### Bug description

Hello everyone,

When creating a revealJS presentation, having a level 1 title followed directly with texts produces a slide with a slightly bigger header
However, these slides behave unexpectedly with respect to the scrollable parameter: they are not scrollable.

This is confusing for the user. While writing a MWE for this bug report, I figured out that scrollable only applies to level 2 headers, but I'm not sure that I would have figured it out otherwise.

I'm not quite sure if this is a bug or a feature. I can update the docs if that is the desired behavior to make it clearer for other users.

### Steps to reproduce

````qmd
---
title: "Scrollable bug: minimal example"
date: "11/04/2024"

format:
    revealjs:
        scrollable: true
        embed-resources: true
---

# Level 1 title: not scrollable

- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin

## Level 2 title: scrollable

- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
- Coin
````

### Expected behavior

I would have expected that both slides are scrollable.

### Actual behavior

Only the second slide (with a level 2 header) is scrollable. The first slide is non-scrollable.
The issue persists when using the {.scrollable} class on the level 1 header.

### Your environment

- IDE: VS Code
- OS: windows 11

### Quarto check output

````bash
Quarto 1.6.32
[>] Checking environment information...
      Quarto cache location: C:\Users\Guillaume\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.6.32
      Path: C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.06
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Guillaume\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.7
      Path: d:/Desktop/Dojo/quarto/notes/.venv/Scripts/python.exe
      Jupyter: 5.7.2
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
````

**Comment by cderv** [comment]
Thanks for the report. 

> When creating a revealJS presentation, having a level 1 title followed directly with texts produces a slide with a slightly bigger header

By default [slide-level: 2](https://quarto.org/docs/presentations/revealjs/#creating-slides), which means level 2 headers creates content slide and level 1 headers create title slide meant for sections, which are centered by default. 

So they are not just slide with a bigger header, they are another type of slide in Revealjs context, where some different defaults applies in Quarto. 

> However, these slides behave unexpectedly with respect to the scrollable parameter: they are not scrollable.

centered slide can't be srollable, like non centered slide. If you make those slides non centered then scrollable will apply to them too. 

````yaml
format:
  revealjs:
    scrollable: true
    center-title-slide: false
````

Unfortunately it is not possible to have centered slide and scrollable feature with current way CSS is applying. 

Hope it clafifies.

**Comment by GuillaumeDehaene** [comment]
Thank you for the clarification.

I have used the web interface to propose this change to the documentation to clarify the docs: https://github.com/quarto-dev/quarto-web/compare/main...GuillaumeDehaene:quarto-web:patch-1

Please let me know if you feel this is appropriate (or feel free to re-use the content in a different PR)

**Comment by cderv** [comment]
Did you open a PR about it ? You can open one and I'll review. Thanks

**Comment by GuillaumeDehaene** [comment]
I had messed up. Here is the correct link https://github.com/quarto-dev/quarto-web/pull/1437
