### ISSUE TITLE
Deno issue with files on network drives

### ISSUE THREAD

**Issue by samlalwani** [quarto-dev/quarto-cli#11332]
### Bug description

Error on trying to render the following default files with 1.6.32

_quarto.yml
```
project:
  type: website

website:
  title: "Articles"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

```
index.qmd
`
---
title: "Articles"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

`

### Steps to reproduce

quarto preview z:/Work/Digital_Twin_Sim/Articles/index.qmd --no-browser --no-watch-inputs
ERROR: PermissionDenied: Requires all access to "Z:\\Work\\Digital_Twin_Sim\\Articles\\_quarto.yml", run again with the --allow-all flag
Path: Z:\Work\Digital_Twin_Sim\Articles\_quarto.yml

Stack trace:
Path: Z:\Work\Digital_Twin_Sim\Articles\_quarto.yml
    at readTextFileSync (ext:deno_fs/30_fs.js:864:10)
    at Object.Deno.readTextFileSync (file:///C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/quarto.js:5124:25)
    at readAndValidateYamlFromFile (file:///C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/quarto.js:20450:29)
    at file:///C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/quarto.js:80774:32
    at projectContext (file:///C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/quarto.js:80556:32)
    at async Command.actionHandler (file:///C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/quarto.js:107867:25)
    at async Command.execute (file:///C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/quarto.js:8086:13)
    at async Command.parseCommand (file:///C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/quarto.js:7976:20)
    at async quarto (file:///C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/quarto.js:126366:9)
    at async file:///C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/quarto.js:126393:9

### Expected behavior

**Version 1.5.57 Works with no issues**

### Your environment

VSCode
Windows 11

### Quarto check output

quarto check
Quarto 1.6.32
[>] Checking environment information...
      Quarto cache location: C:\Users\Sameer\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.6.32
      Path: C:\Users\Sameer\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.10 (Conda)
      Path: C:/Users/Sameer/miniconda3/envs/dap/python.exe
      Jupyter: 5.7.2
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by cscheid** [comment]
I can't reproduce this on macOS. @cderv can you check on windows?

**Comment by cderv** [comment]
It works ok locally 

Though seeing `ERROR: PermissionDenied: Requires all access to "Z:\Work\Digital_Twin_Sim\Articles\_quarto.yml` and the Z letter, I assume this is on a network drive. 

@samlalwani can you confirm ? 

i'll try to do some test on network drive

**Comment by samlalwani** [comment]
Yes this is a network drive.
1.6.33 also has the same issue.
Later today I will try it on a local drive and get back to you.

**Comment by cderv** [comment]
> Yes this is a network drive.

Can you give more information on this network drive ? Thank you

**Comment by samlalwani** [comment]
Is a Synology NAS with a network share mounted as Z: on windows.
https://global.download.synology.com/download/Document/Hardware/DataSheet/DiskStation/19-year/DS1019+/enu/Synology_DS1019_Plus_Data_Sheet_enu.pdf

**Comment by samlalwani** [comment]
ver 1.6.33 works perfectly on windows on a local drive

**Comment by cscheid** [comment]
> Not solved yet on deno side, and if it is, it will be probably for Deno 2.0 😞
> 
> So it is possible that the deno upgrade prevent now quarto to be used on network drive on windows 🙀

We should just add "--allow-all". They recommend you to use the granular options instead, and so we switched to that. But if "--allow-all" solves the problem, then we need to use it.

**Comment by cderv** [comment]
@samlalwani can you try something like this 

Deno should be available at `C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/tools/x86_64/deno.exe`

In a local folder, create a `test.ts` 
```ts
Deno.readTextFileSync("Z:\Work\Digital_Twin_Sim\Articles\index.qmd")
```

Call in a terminal (like powershell)
```bash
C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/tools/x86_64/deno.exe run --allow-read test.ts
```

it should error. And then try 
````
C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/tools/x86_64/deno.exe run --allow-all test.ts
````

Does it works ? 

Thanks

**Comment by samlalwani** [comment]
ERROR :
C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/tools/x86_64/deno.exe run
--allow-read test.ts

NO ERROR :
C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/tools/x86_64/deno.exe run
--allow-all test.ts

It worked as expected.

**Comment by cderv** [comment]
Great thank you !

**Comment by cderv** [comment]
@samlalwani as I can't reproduce can you try also with `--allow-sys` and `--allow-net`

````
C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/tools/x86_64/deno.exe run --allow-read --allow-net  test.ts
````

then 
````
C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/tools/x86_64/deno.exe run --allow-read --allow-net --allow-sys test.ts
````

Thank you

**Comment by cderv** [comment]
Also @samlalwani here is another thing to try as I did a PR with a new build to try out

Open powershell

````powershell
cd $env:TEMP
mkdir test-quarto
cd test-quarto
gh rununzi -R quarto-dev/quarto-cli download 11816181874 --name 'Windows Zip'
unzip -q .\quarto-1.6.34-win.zip -d quarto
````

You can now use this quarto binary to render your document / project on Z:/

````powershell
& "$env:TEMP/test-quarto/quarto/bin/quarto.exe" render "Z:/Work/Digital_Twin_Sim/Articles/"
````

or something like this (if I did not get your path right). 

Thanks a lot for you help !! 

PS: when finished you can run deletion of temp directory
````
cd $env:TEMP
# Do this in the place to not delete something else
rm -Recurse .\test-quarto\ 
# or open the temp directory and delete manually
explorer $env:TEMP # and look for `test-quarto` folder
````

**Comment by samlalwani** [comment]
Both the following options failed:

PS Z:\Work\Digital_Twin_Sim\Articles>
C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/tools/x86_64/deno.exe run
--allow-read --allow-net  test.ts
Error reading file: PermissionDenied: Requires all access to
"Z:/Work/Digital_Twin_Sim/Articles/about.qmd", run again with the
--allow-all flag
    at Object.readTextFileSync (ext:deno_fs/30_fs.js:864:10)
    at file:///Z:/Work/Digital_Twin_Sim/Articles/test.ts:4:26 {
  name: "PermissionDenied"
}

PS Z:\Work\Digital_Twin_Sim\Articles>
C:/Users/Sameer/AppData/Local/Programs/Quarto/bin/tools/x86_64/deno.exe run
--allow-read --allow-net --allow-sys  test.ts
Error reading file: PermissionDenied: Requires all access to
"Z:/Work/Digital_Twin_Sim/Articles/about.qmd", run again with the
--allow-all flag
    at Object.readTextFileSync (ext:deno_fs/30_fs.js:864:10)
    at file:///Z:/Work/Digital_Twin_Sim/Articles/test.ts:4:26 {
  name: "PermissionDenied"
}

**Comment by mcanouil** [comment]
@samlalwani Could you use GitHub for your replies and use markdown to format your message?
It's very hard to read as is. At least, don't keep previous replies when replying by email.

**Comment by cderv** [comment]
@samlalwani thanks ! 

I let you do the last test to confirm the fix is working
https://github.com/quarto-dev/quarto-cli/issues/11332#issuecomment-2473369032

Thank you for your help !

**Comment by samlalwani** [comment]
The updated build  pulled using :
gh run -R quarto-dev/quarto-cli download 11816181874 --name 'Windows Zip' 

worked perfectly

**Comment by cderv** [comment]
Thanks for confirming.

**Comment by jkdel** [comment]
I believe that the issue should be reopened. I am using Quarto 1.7.29 which uses deno with the `--allow-all` option, but I am still seing this issue. I am on a corporate Windows 11 machine without admin rights.

When I try to preview or render any quarto file (from CLI or from RStudio with the quarto version) on a network drive (`H:`) I get the following error:

``` powershell
> C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.exe preview H:/test.qmd

ERROR: PermissionDenied: Zugriff verweigert (os error 5): stat 'H:/test.qmd'

Stack trace:
    at Object.statSync (ext:deno_fs/30_fs.js:425:3)
    at Command.actionHandler (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:109349:14)
    at async Command.execute (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:8253:13)
    at async Command.parseCommand (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:8143:20)
    at async quarto (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:128475:9)
    at async file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:128505:9
    at async file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:128357:20
    at async mainRunner (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:128359:9)
    at async file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:128496:5
```

Previewing or rendering the same file locally works fine.

Running deno as indicated [here](https://github.com/quarto-dev/quarto-cli/issues/11332#issuecomment-2470734738) with `--allow-read` or `--allow-all` works fine...

------------------------

```powershell
> C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.exe check

Quarto 1.7.29
[>] Checking environment information...
      Quarto cache location: C:\Users\USERNAME\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.6.3: OK
      Dart Sass version 1.85.1: OK
      Deno version 1.46.3: OK
      Typst version 0.13.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.7.29
      Path: C:\Users\USERNAME\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking Chrome Headless....................OK
      Using: Chrome found on system
      Path: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
      Source: Windows Registry

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.5.0
      Path: C:/PROGRA~1/R/R-45~1.0
      LibPaths:
        - C:/Users/USERNAME/AppData/Local/R/win-library/4.5
        - C:/Program Files/R/R-4.5.0/library
      knitr: 1.50
      rmarkdown: 2.29

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
This is not a `--allow-all` issue - if it were, you'd be seeing a different error. This exception comes from Windows claiming that you really do not have permission to open the file. There's nothing that Quarto can do in that case, unfortunately

**Comment by jkdel** [comment]
OK great, thank you very much! This happened after an update of R and RStudio. I cannot say what the previous RStudio version was for sure. I tried to find similar issues here and updated quarto to the current version in the hope that the deno-fix would solve the issue.

I can open the file on the network drive from the same terminal session, I have read and write permission for this directory... Any hint on how to investigate the issue?

**Comment by jkdel** [comment]
Thank you for looking into it.

- **From where are you calling quarto render?** \
   Both `H:\> quarto render test.qmd` and `C:\Users\USERNAME\Documents> quarto render H:/test.qmd` result in the above mentioned error. (quarto 1.7.29 *and* 1.5.57)
- **Did you try with same Deno version bundled with quarto?** \
  Good point, I mentioned earlier that calling deno works fine, however this is only true for deno 1.41.0 (bundled with quarto 1.5.57). Is it correct, that the `--allow-all` flag became necessary with deno 1.46.3? If yes, isn't it weird that I get the same both with quarto 1.7.29 and 1.5.57? \
   With deno 1.46.3 I get the `PermissionDenied: Access denied (os error 5)` error, even with the `--allow-all` flag.
- **Can you try to run Deno.statSync command on the file itself ?** \
   This gives a `PermissionDenied: Access denied (os error 5)` error. `deno repl --allow-all` gave the same error.

Here is how I checked file permissions:

```powershell
> icacls H:/test.qmd
H:/test.qmd CORPORATEDOMAIN\USERNAME:(I)(M)
            CORPORATEDOMAIN\USERNAME:(I)(F)
            NT-AUTHORITY\SYSTEM:(I)(F)
            CORPORATEDOMAIN\owncloud-s:(I)(F)
            CORPORATEDOMAIN\sl-fileserver-full:(I)(F)
            CORPORATEDOMAIN\Domain-Admins:(I)(F)
            PREDEFINED\Administrators:(I)(F)
```

I am USERNAME. According to the [icacls doc](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/cc753525(v=ws.11)) I have modify access (M) and full access (F) inherited from the parent directory (i.e., the drive).

Please also note that while a RStudio (unknown to 2024.12.1+563) and R update (4.4 to 4.5) caused the issue, everything worked fine before that. I am not aware of any changes in file permissions on the H: drive.

**Comment by cderv** [comment]
> > Can you try to run Deno.statSync command on the file itself ?
> This gives a PermissionDenied: Access denied (os error 5) error. deno repl --allow-all gave the same error.

I understand you tried Deno 1.46.3 on its own, but it does not work with this access denied error. Is this correct? 

If so, this appears to be a Deno issue - we are calling `Deno.statSync` on its own. Quarto 1.8 should have Deno 2 update, and hopefully, this could solve it (#12580) 

I am not sure we can do something for Quarto 1.7 about this. We are using `--allow-all`, and it does not seem to be working with Deno repl anyway. So something about this Network drive is making Deno fail. For example, I can't reproduce it with a "Google Drive" mounted drive.

**Comment by jkdel** [comment]
> I understand you tried Deno 1.46.3 on its own, but it does not work with this access denied error. Is this correct?

Yes, exactly.

> I am not sure we can do something for Quarto 1.7 about this. We are using `--allow-all`, and it does not seem to be working with Deno repl anyway. So something about this Network drive is making Deno fail. For example, I can't reproduce it with a "Google Drive" mounted drive.

Yes, you are right. I just tried it with the file on another network drive and it works... No idea what's wrong with this drive then.

Thank you for your time!
