### ISSUE TITLE
quarto-ojs-runtime: Uncaught TypeError: can't access property "contains", n.classList is undefined

### ISSUE THREAD

**Issue by eamcvey** [quarto-dev/quarto-cli#11344]
I'm getting an error in the browser tools for my Quarto dashboard (which uses OJS). As far as I know it's not causing any actual problems, but since it's coming from quarto-ojs-runtime.js I assume it's unrelated to anything I'm doing or have control over.

![Image](https://github.com/user-attachments/assets/b67768fd-4fc9-486a-a00c-8da3bd4bb539)

**Comment by cscheid** [comment]
Thanks for the report. We do need a reprex in order to be able to figure out what's going on.

**Comment by mcanouil** [comment]
You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.
