### ISSUE TITLE
Styling regression on border in latest 1.6

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#11348]
I noticed some changes locally when building with dev version and now it is in quarto.org 
as #11283 was added to prerelease

Previous doc

![image](https://github.com/user-attachments/assets/a666acbe-daf0-4978-b076-68985e4495c7)

Now with darker separator 
![image](https://github.com/user-attachments/assets/a9f8d923-7659-4266-b501-55bd1c4d5383)

So we should try mitigate that while keeping #11282 that #11283 dealt with

**Comment by cscheid** [comment]
it turns out that `mix` works backwards from how I thought it did: `mix(a, b, 90%)` means "90% of a, 10% of b". That's completely unintuitive to me, but it's an easy fix. I'll push a quick direct fix to `main`.

**Comment by cderv** [comment]
Thanks !
