### ISSUE TITLE
How do I save a gt docx table from within Quarto?

### ISSUE THREAD

**Issue by robertprince** [quarto-dev/quarto-cli#11354]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/11352

<div type='discussions-op-text'>

<sup>Originally posted by **robertprince** November  9, 2024</sup>
### Description

I wish to save a gt docx table from Quarto and am receiving the following error message:

Pandoc can convert to DOCX, but not to DOC.
Error:
! pandoc document conversion failed with error 22

My r code is:
````
---
title: "Trial3"
format: html
editor: visual
---

{r}
# library(car)
# library(tidyverse)
# library(gtsummary)
# library(flextable)
# library(officer)
library(gt)

tab_1 <-
  gtcars |>
  dplyr::select(model, year, hp, trq) |>
  dplyr::slice(1:5) |>
  gt(rowname_col = "model") |>
  tab_stubhead(label = "car")

tab_1

tab_1 |> gtsave("tab_1.docx")

````
I am using Quarto version 1.6.32 with the latest RStudio running R version 4.2.2 on a Windows 10 pc

</div>

**Comment by mcanouil** [comment]
Please stop multiplying the discussions and issues.
You started with:
- https://github.com/quarto-dev/quarto-cli/discussions/11352

I'am afraid if you keep doing this, we will have to consider this as spam and take the appropriate response.
