### ISSUE TITLE
Referencing a book chapter is not working

### ISSUE THREAD

**Issue by ccamara** [quarto-dev/quarto-cli#1135]
When working in a quarto book, I would like to reference a chapter (ideally, having its name and number) which is located in a different file.

Given the following structure

```
_quarto.yml
intro.qmd
python.qmd
```

I would like to reference `python.qmd`into `intro.qmd`, so following [this guide in the official documentation](https://quarto.org/docs/books/book-crossrefs.html#creating-references), I did the following:

In `python.qmd`:

```quarto

# Introduction to Python {#sec_python}
```

and in `intro.qmd`:

```md
# Introduction

This is where I'd like to reference [Chapter -@sec_python]
```

But when I run `quarto preview` or `quarto render` I get the following warning: `[WARNING] Citeproc: citation sec_python not found`

And this is what I can see:
![Screenshot 2022-05-27 at 11-37-29 Skills Programme - Computational thinking](https://user-images.githubusercontent.com/706549/170684061-b5689940-2cfd-4529-97a6-3ad1d00fe524.png)

I'm using quarto v.0.9.464

**Comment by jjallaire** [comment]
We are not able to reproduce the problems you mention with references when running `quarto render`. If you are continuing to see problems please create a git repo with a minimal reproducible example and post a link to it here and we'll take a closer look.
