### ISSUE TITLE
"include" shortcode in code blocks are broken

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#1136]
### Bug description

I noticed that the shorcode example is missing in the reference page.
Perhaps the behavior of quarto has changed?

https://quarto.org/docs/authoring/includes.html

![image](https://user-images.githubusercontent.com/50911393/173333021-06ce346f-bcc0-4d14-bdf2-9caf96a7d19d.png)

````md
---
title: "Includes"
---

## Overview

Includes are a convenient way to re-use content across documents. Includes work for plain markdown content as well as for `.qmd` files with executable code cells (note however that the cells must all use the same engine -- i.e. knitr or jupyter, but not both).

To include a file, add the `{{< include >}}` shortcode at the location in your document where you want it included:

``` markdown
{{< include _content.qmd >}}
```
````

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [ ] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thanks for the heads up! Addressed here: https://github.com/quarto-dev/quarto-web/commit/b77253a4275035a401edbc701b5b0205ce0180d3

**Comment by eitsupi** [comment]
Thanks. (I should have searched for escaping)

It seems inline code also should be escaped.

![image](https://user-images.githubusercontent.com/50911393/173354599-0d8efd96-7efb-4095-a715-d365f5d05e3f.png)

**Comment by jjallaire** [comment]
Thanks! Done.
