### ISSUE TITLE
Time Zone abbreviation rather than UTC offset

### ISSUE THREAD

**Issue by connorp** [quarto-dev/quarto-cli#1138]
Quarto's custom date format can provide the time zone, but only as UTC offset (e.g. `-6:00`) rather than the time zone name/abbreviation (e.g. `PDT` or `Pacific Daylight Time`). 

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by connorp** [comment]
Ooof, my bad for not reading the docs. Thanks for the nudge!

**Comment by connorp** [comment]
Since it's just barely on-topic still: is there a way to get the timezone abbreviation rather than the UTC offset? E.g. `PDT` rather than `-6:00`

**Comment by dragonstyle** [comment]
Right now, there isn't, but let's leave this open as it may be straightforward for me to add support for that.

**Comment by dragonstyle** [comment]
Ok I just pushed a change that should enable more robust date format support (and updated the date docs). Give it a try starting in release 579.
