### ISSUE TITLE
Category tags do not refresh page in the dropdown memu

### ISSUE THREAD

**Issue by drganghe** [quarto-dev/quarto-cli#1139]
I use the dropdown menu in the main navigation to link the related blog posts/listing categories. 
However, only the first one could automatically refresh the page.
Following categories do not automatically refresh the page when clicking and I have to click return to refresh it.

**Comment by dragonstyle** [comment]
Thanks for reporting this - do you have an example page/site that I could take a look at to be sure I understand what you're saying?
