### ISSUE TITLE
Vscode support equivalent to Rstudio

### ISSUE THREAD

**Issue by fbob** [quarto-dev/quarto-cli#114]
As Vscode is gaining so much popularity (for obvious reasons)  is it planned to enhance vscode's support as it is for Rstudio ?
The work done with Rstudio looks very nice, quarto could grow its user base with equivalent features for vscode.

Anyway, you've made a very good work with quarto.
Thanks !

**Comment by jjallaire** [comment]
Hi there, thanks for the comment. Yes we are definitely looking at creating more/better tooling for other environments. Stay tuned!

**Comment by dpprdan** [comment]
see #149 & #239
