### ISSUE TITLE
Some of the TODOs got into the final rendered HTML

### ISSUE THREAD

**Issue by pawelru** [quarto-dev/quarto-cli#11401]
My auto TODO detector is screaming when looking into the `_site` subdir:
![Image](https://github.com/user-attachments/assets/8de46da7-2088-4e3f-a03a-df09ed6a8af0)

This are repeating across the subpage and it looks like it mostly coming from those two:
https://github.com/quarto-dev/quarto-cli/blob/adc7186f0ee20ed125588cd603330beb2e76bc71/src/resources/formats/html/templates/quarto-html.ejs#L287
https://github.com/quarto-dev/quarto-cli/blob/adc7186f0ee20ed125588cd603330beb2e76bc71/src/resources/formats/html/templates/quarto-html.ejs#L510

It looks like it got injected into every single page I have. Since it's a comment it's probably not a big deal though but I thought I would share this with you.

**Comment by cscheid** [comment]
You're not using the correct EJS comment syntax: https://stackoverflow.com/questions/29180611/how-can-i-comment-the-ejs-code-js-node-without-getting-an-error

**Comment by pawelru** [comment]
These are not my comments :) linked code snippets belong here - `quarto-cli` repo

**Comment by gadenbuie** [comment]
> My auto TODO detector is screaming when looking into the `_site` subdir

You should configure your TODO detector to ignore the `_site` subdir. If you're using Todo Tree in VS Code, look for the "Filtering: Exclude Globs" setting.

**Comment by cscheid** [comment]
Ah, sorry. It turns out that _we_ don't mind those TODOs there, but I'll make the change anyway.
