### ISSUE TITLE
The `self-contained: true` setting in the _quarto.yml is no longer working with images generated by diagram filter

### ISSUE THREAD

**Issue by fuhrmanator** [quarto-dev/quarto-cli#1142]
### Bug description

Sometime prior to 0.9.577 my book project would generate PlantUML/GraphViz images using pandoc's official diagram filter with no troubles, if I used the `self-contained: true` in the html part of the .yml. It seems to be broken now. 

Instead of `data:` uri's for the filter-generated SVGs, I get e.g.:

```html
<img src="b0a06efeb01f6cbd272bae71a5fa8f954dc5413a.svg" class="img-fluid figure-img">
```

They're not stored anywhere, so the server records these errors:

```terminal
[WARNING] Could not fetch resource b0a06efeb01f6cbd272bae71a5fa8f954dc5413a.svg
```

There's a workaround if I hack the command using `quarto preview --to html --extract-media=_book/images`, but it effectively negates the `self-contained: true` option.

To help you with a minimal working example, I created a repo at https://github.com/fuhrmanator/quarto-test

```
quarto check

[>] Checking Quarto installation......OK
      Version: 0.9.577
      Path: C:\Users\fuhrm\AppData\Local\Programs\Quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: C:/Python310/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

Windows 10.

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thank for reporting! This issue should be resolved here: https://github.com/quarto-dev/quarto-cli/commit/dee0d817154a0bdec1a502da715b9e61cff570b0
