### ISSUE TITLE
Rendering files containing mermaid code blocks to docx leaves temporary png files

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#1146]
### Bug description

Rendering a qmd file like the following will leave a file named `qmdfilename_files/figure-docx/mermaid-figure-1.png`.
If this is the expected behavior, it would be a good idea to write to .gitignore to exclude these files.

````qmd
---
title: "Untitled"
format: docx
---

```{mermaid}
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```
````

I tested it on Windows and Linux.

```sh
$ quarto check

[✓] Checking Quarto installation......OK
      Version: 0.9.580
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: 4.10.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/local/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
I think the problem is that we are only removing `supporting` directories and that directory is determined by the knitr/jupyter engine (if one of these is not in play then we may not hit that codepath). We may need to make sure that mermaid/ojs register the `supporting` _files directory.

**Comment by cscheid** [comment]
Thank you for reporting this! It's fixed now on `main`.

All figures auto-generated by cells should now be cleaned up in formats such as `pdf` and `docx`.
