### ISSUE TITLE
Author order different for listings from documents vs. yaml

### ISSUE THREAD

**Issue by felixdidi** [quarto-dev/quarto-cli#11462]
### Bug description

When generating a listing based on a yaml file such as 

````qmd
listing:
  contents: 
    - "publications/pubs.yml"
````

````yaml
- title: "Test 1"
  author:
    - Author A
    - Author B
    - Author C
- title: "Test 2"
  author:
    - Author D
    - Author E
    - Author A
````

the author order in the listing is as I would expect, i.e., Author A is displayed first for Test 1 and last for Test 2.

However, if I do the same based on two individual documents including the same information, Author A is always listed as first author.

````qmd
listing:
  contents: 
    - "publications/*.qmd"
````

### Expected behavior

I would expect the behavior to be the same for both cases, i.e., the author order should be as specified in the YAML.

### Quarto check output

```bash
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/felix/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report!

Can you confirm the behaviour is the same using 1.6 release candidate?

**Comment by felixdidi** [comment]
Yes, it is the same in 1.6 — however, I now figured out that it only happens if I also specify Author A as author in `_quarto.yml`. I don't know if this is the expected behavior. If yes, this issue can be ignored 😊

**Comment by mcanouil** [comment]
This is why we ask for small but complete reproducible example.
This is expected behaviour in this case as metadata are merged as described: https://quarto.org/docs/projects/quarto-projects.html#shared-metadata

i'm going ahead and close as I now believe there are no bugs here.
