### ISSUE TITLE
Brand: Website navbar-bg uses Quarto default rather than `$primary`

### ISSUE THREAD

**Issue by gadenbuie** [quarto-dev/quarto-cli#11471]
### Bug description

Here's a minimal set of files to reproduce the issue. With these files, the website should pick up `color.primary` from `_brand.yml` and use bright orange for the default navbar color, _instead of Quarto's default blue_.

**_quarto.yml**

```yml
project:
  type: website

website:
  title: "Brand navbar-bg default"
  navbar:
    left:
      - index.qmd
```

**_brand.yml**

```yml
color:
  primary: "#ff5100"
```

**index.qmd**

```qmd
---
title: "Hello, world"
---

[xkcd comics](https://xkcd.com) are a unique blend of humor and intellect. They often tackle complex topics like science, technology, and mathematics, making them accessible and entertaining. The stick-figure art style adds to their charm, keeping the focus on the clever punchlines and ideas.
```

The problem is that in [_bootstrap-variables.css](https://github.com/quarto-dev/quarto-cli/blob/603c2374d3562c473d2187269f0bfffd808be44a/src/resources/formats/html/bootstrap/_bootstrap-variables.scss#L63-L67), setting `$navbar-default` to `$primary` only happens when `$theme` is set. This Sass variable has a value if you include e.g. `theme: cosmo` but is empty for `brand`.

```scss
$navbar-default: if(
  variable-exists(theme),
  if(variable-exists(primary), $primary, #517699),
  #517699
);
```

My recommendation is that when `brand` is involved, `$theme` be set to `brand`. If `theme` includes another Bootstwatch theme, then I'm less clear what should happen, e.g. `theme: [brand, cosmo]`. The reason this variable exists is to make last-minute changes to colors from the Bootswatch theme. I think that having `cosmo` win regardless of order is the slightly better choice; `$theme` is primarily used in `theme-override-value()` ([source](https://github.com/quarto-dev/quarto-cli/blob/603c2374d3562c473d2187269f0bfffd808be44a/src/resources/formats/html/bootstrap/_bootstrap-functions.scss#L72)) where most important color changes are gated with a check against the default value (letting user values pass through).

### Quarto check output

```bash
Quarto 99.9.9
[✓] Checking environment information...
      Quarto cache location: /Users/garrick/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      commit: 603c2374d3562c473d2187269f0bfffd808be44a
      Path: /Users/garrick/work/quarto-dev/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/garrick/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.13.0
      Path: /opt/homebrew/opt/python@3.13/bin/python3.13
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources
      LibPaths:
        - /Users/garrick/Library/R/arm64/4.4/library
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
> My recommendation is that when `brand` is involved, `$theme` be set to `brand`.

I like it.


> If `theme` includes another Bootstwatch theme, then I'm less clear what should happen, e.g. `theme: [brand, cosmo]`.

I think the best we can do is to use the name that the configuration deemed to be "the most important", eg `theme: [brand, cosmo]` gets `$theme: "cosmo"` and `theme: [cosmo, brand]` gets `$theme: "brand"`.

**Comment by coatless** [comment]
Huh, I always thought that the first theme was the most important and, then, went downwards in precedents given the `theme: [main, custom.scss]` approach taken usually.

**Comment by cscheid** [comment]
### Teaching myself how this all works

In addition to `theme`, we also have `theme-name`. `_bootstrap-variables.scss` has:

https://github.com/quarto-dev/quarto-cli/blob/8e51fc22e41e58f1c4c7bbedff4a7bdbea58a54d/src/resources/formats/html/bootstrap/_bootstrap-variables.scss#L2

The `theme` variable itself is set by the specific SCSS files directly:

https://github.com/quarto-dev/quarto-cli/blob/e7f8dbe6f3c82ebb16d44b07138bcb47c30f4e0d/src/resources/formats/html/bootstrap/themes/cerulean.scss#L4

https://github.com/quarto-dev/quarto-cli/blob/e7f8dbe6f3c82ebb16d44b07138bcb47c30f4e0d/src/resources/formats/html/bootstrap/themes/cosmo.scss#L4

.. and so on. Those variable assignments all use `!default` and appear in the `scss:defaults` layer.

The theme name is also used by some style settings we have:

- `src/resources/projects/website/listing/quarto-listing.scss`
- `src/resources/projects/website/navigation/quarto-nav.scss`

**Comment by gadenbuie** [comment]
@cscheid We can set `$theme: "brand" !default` in the brand Sass layers. I tried this earlier but I didn't realize I was putting the rule in a place where it was conditionally included only if `defaults.bootstrap.defaults` was included in the `_brand.yml`. #11473 adds the default declaration in `brand.ts`.

**Comment by cscheid** [comment]
Draft https://github.com/quarto-dev/quarto-cli/pull/11474
