### ISSUE TITLE
Dynamic Title example doesn't work

### ISSUE THREAD

**Issue by makiz1999** [quarto-dev/quarto-cli#11506]
### What would you like to do?

Report an issue on quarto.org

### Description

This example doesn't work with R

![Image](https://github.com/user-attachments/assets/f759872a-034e-4cfe-a8e4-af3e380d189a)

Output:
![Image](https://github.com/user-attachments/assets/947b8d27-b2a1-451a-a13a-2e946d08d8e5)

**Comment by mcanouil** [comment]
@makiz1999 Thanks. Could you point to where this is? Screenshots are not helpful to search/find resources.

**Comment by makiz1999** [comment]
Yeah, here is the link: https://quarto.org/docs/dashboards/data-display.html#dynamic-titles

**Comment by makiz1999** [comment]
> [@makiz1999](https://github.com/makiz1999) Thanks. Could you point to where this is? Screenshots are not helpful to search/find resources.

Yeah, here is the link: https://quarto.org/docs/dashboards/data-display.html#dynamic-titles

**Comment by cderv** [comment]
@makiz1999 are you using this in `format: dashboard` ? 

This will only work in this format, and it works for me it seems

````markdown
---
title: Test
format: dashboard
keep-md: true
---

```{r}
library(leaflet)

lat <- 48
long <- 350

cat("title=", "World Map at", lat, long)

leaflet() |> addTiles() |> 
  setView(long, lat, zoom = 2)
```

````

The card correctly get the title
![Image](https://github.com/user-attachments/assets/5c4fa321-1dd4-440a-90c4-06159d6c42a5)

**Comment by makiz1999** [comment]
> [@makiz1999](https://github.com/makiz1999) are you using this in `format: dashboard` ?
> 
> This will only work in this format, and it works for me it seems
> 
> ---
> title: Test
> format: dashboard
> keep-md: true
> ---
> 
> ```{r}
> library(leaflet)
> 
> lat <- 48
> long <- 350
> 
> cat("title=", "World Map at", lat, long)
> 
> leaflet() |> addTiles() |> 
>   setView(long, lat, zoom = 2)
> ```
> The card correctly get the title ![Image](https://github.com/user-attachments/assets/5c4fa321-1dd4-440a-90c4-06159d6c42a5)
> 
> This is specific feature of Dashboard format to set a title to a Card output

Hi, thank you. I missed one element in my code. 

Do you know by chance if it's possible to dynamically change the title using a reactive component? In other words, the title would reflect user input from the dropdown selector

**Comment by cderv** [comment]
I don't think this is possible because the feature is used by `quarto render` and it is only rendered once.

any shiny reactive can't be used in there. 

Maybe there is a way to use some raw HTML that shiny understand, but this is not easy. 

So unfortunately with this syntax, I don't think this can be done. I need to think about how this could be done in a dashboard. 🤔
