### ISSUE TITLE
Preview no longer available in VSCode

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#1154]
I no longer have the prompt (or the preview panel) that ask where to preview the generated HTML file either Windows 10 / MacOS 12.4, while I stil have it within a Docker container running Debian.
The settings were not modified (*i.e.*, default). Any idea, how to fix this, if not on quarto-vscode side?
<img width="366" alt="Screenshot 2022-06-14 at 15 56 26" src="https://user-images.githubusercontent.com/8896044/173595023-dca363f7-c77e-4dcb-9121-bb8a9982b577.png">

Also, I think path resolution for the preview has a bug when trying to render/preview `subfolder/file.qmd` and setting `_quarto.yml` with `execute-dir: project`.
This results in VSCode prompting the user to choose external browser or editor, but in both cases this ends with:

```
...

Output created: index.html

Watching files for changes
Browse at http:///localhost:6840/subfolder/index.html
GET: / (404: Not Found)
```

OS: Windows 10 / MacOS 12.4
VSCode: 1.68
quarto-vscode: 1.24
Quarto: 0.9.573

**Comment by jjallaire** [comment]
I don't seem to be able to reproduce this problem w/ the latest quarto/vscode extension on osx. Could you provide a link to a git repo that exhibits this behavior as well as the specific action you took in VS Code (something in the terminal, keyboard shortcut, etc.) to get into this state.

**Comment by mcanouil** [comment]
I am testing different setup to make a reproducible and working example and get back here with more details.

**Comment by mcanouil** [comment]
I tried on an independent instance of VSCode (without my settings/extensions) using a controlled and identical setup.
With my settings and extension, the issue appears, it does not on the independent instance of VSCode.

This issue is now likely to be a conflict with one of my ~ 40 extensions ^^

**Comment by jjallaire** [comment]
Thank you! That's great slue-thing. Unfortunately it looks like this is a VS Code bug. When this setting is active its impossible for us to forward environment variable to `quarto preview` (which we do here: https://github.com/quarto-dev/quarto-vscode/blob/df686596c2bc9fecc6bb4894e2f1d3a44fb0c93f/src/providers/preview/preview-env.ts#L12-L13).
