### ISSUE TITLE
Classes option on code chunk explodes input class with spaces

### ISSUE THREAD

**Issue by jimjam-slam** [quarto-dev/quarto-cli#1157]
### Bug description

I'd like to attach a CSS class or to a code chunk: `hello`, or example, or `hello` and `goodbye`. But in my rendered output, the chunk element appears to get `class="cell h e l l o"` or `class="cell h e l l o g o o d b y e"` (note the spaces).

Here's my test example:

````
---
title: "Test doc"
format:
  html:
    self-contained: true
---

Here's a chunk:

```{ojs}
//| classes: hello
3 + 3
```
````

The output HTML is attached: [_test.html.zip](https://github.com/quarto-dev/quarto-cli/files/8906351/_test.html.zip)

My Quarto version is as of commit `a450f1c0f` (about six days ago). My R version is 4.1.2, and RMarkdown is 2.11. My MacOS version is 12.3.1.

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
That was definitely a bug. Thanks for catching!
