### ISSUE TITLE
quarto-1.6.39-macos ERROR: TypeError: content.match is not a function

### ISSUE THREAD

**Issue by serhatbe** [quarto-dev/quarto-cli#11580]
### Bug description

Installed quarto-1.6.39-macos and cannot render my blog website that contain **shortcodes** for example  {{< video https://youtube/link >}} 

```
[1/2] posts/2024-11-10/index.qmd
ERROR: TypeError: content.match is not a function

Stack trace:
    at Object.emit (file:///Applications/quarto/bin/quarto.js:37537:42)
    at Object.mappedString (file:///Applications/quarto/bin/quarto.js:37375:14)
    at file:///Applications/quarto/bin/quarto.js:99070:146
    at Array.map (<anonymous>)
    at Object.formatExtras (file:///Applications/quarto/bin/quarto.js:99070:104)
    at async runPandoc (file:///Applications/quarto/bin/quarto.js:77019:63)
    at async renderPandoc (file:///Applications/quarto/bin/quarto.js:78450:26)
    at async Object.onRender (file:///Applications/quarto/bin/quarto.js:85992:36)
    at async renderFileInternal (file:///Applications/quarto/bin/quarto.js:85969:17)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:85793:17)
```

I rolled back to 1.5.57 and no problem rendering the website.

### Your environment

- IDE: RStudio: Version 2024.09.1+394 (2024.09.1+394)
- OS: macOS 15.1.1 (24B91)

### Quarto check output

```
Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /Users/xxxxxxxxx/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.06
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/xxxxxxxxx/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/local/bin/python3
      Jupyter: 5.5.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/xxxxxxxxx/Library/R/arm64/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Can you provide a reproducible example?

**Comment by harrelfe** [comment]
I'm having this problem on 1.7.1 during wrap-up of a long script that does not use shortcodes.

```
output file: index.knit.md

ERROR: TypeError: content.match is not a function

Stack trace:
    at Object.emit (file:///Applications/quarto/bin/quarto.js:37537:42)
    at Object.mappedString (file:///Applications/quarto/bin/quarto.js:37375:14)
    at file:///Applications/quarto/bin/quarto.js:99070:146
    at Array.map (<anonymous>)
    at Object.formatExtras (file:///Applications/quarto/bin/quarto.js:99070:104)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async runPandoc (file:///Applications/quarto/bin/quarto.js:77019:63)
    at async renderPandoc (file:///Applications/quarto/bin/quarto.js:78450:26)
    at async Object.onRender (file:///Applications/quarto/bin/quarto.js:85992:36)
    at async renderFileInternal (file:///Applications/quarto/bin/quarto.js:85969:17)
```

**Comment by cscheid** [comment]
In @harrelfe's stack trace (looking at `quarto.js` and tracing it back to the unbuilt source), the error happens at `pandocNativeStr`: https://github.com/quarto-dev/quarto-cli/blob/99b80b90d7db7b980e56081dc227320f7bf135ce/src/core/pandoc/codegen.ts#L235

Someone is bypassing the `string` check there, since we're getting `content.match is not a function`. Further up in the stack, we get a call at https://github.com/quarto-dev/quarto-cli/blob/8668ceb497d82e466049514dfa8400dd966c66b3/src/project/types/website/website.ts#L211 that has a typecast `as string`, clearly the culprit here.

**Comment by cscheid** [comment]
@harrelfe Do you have documents with `categories` entries that are accidentally not strings, by chance? I can trigger the issue in this way.

I believe `categories` should be an array of strings, and our validation infrastructure isn't currently enforcing that. That's a bug by itself.

I'll make that change in 1.7 on a separate PR, and restore the old behavior for 1.6 in a hot-fix. 

I'm letting you know because this change might mean that your documents need to change.

**Comment by cscheid** [comment]
Ah, it's `2024` as a category, since in YAML that is a number, and not a string. A workaround is for you to use `"2024"` instead. In 1.7, I think we'll make it so that is a requirement, but this is technically a regression without a great diagnostic, so we'll fix.

**Comment by harrelfe** [comment]
Thanks, "2024" made it compile fine.  I assume I only need to change this in old posts when I recompile them.

**Comment by serhatbe** [comment]
Many thanks @cscheid and @harrelfe 

I just updated the YAML front matter categories by wrapping the year entries in quotes. This solved the problem in quarto 1.6.39 under Windows, I'll test it in macOS tonight.

```
categories:
  - "2024"
  - etc
```

**Comment by harrelfe** [comment]
My test was on a Mac, worked fine with [ , , , ] notation.

**Comment by serhatbe** [comment]
All tested fine on macOS.
