### ISSUE TITLE
Styling issues from local preview/render to published site

### ISSUE THREAD

**Issue by melaniewalsh** [quarto-dev/quarto-cli#11648]
### Bug description

We are seeing some styling issues from our local preview/render to the published site, which uses GitHub actions.

Our hero image on the front page is getting messed up, and the category tags for our blog posts do not work. For example, clicking the "education" tag leads to https://data.post45.org/#category=ZWR1Y2F0aW9u rather than http://localhost:6376/#category=education on local.

Does anybody know why this is happening or how we can fix it?

Local preview and local render

![Image](https://github.com/user-attachments/assets/c2099ce5-91a2-458b-9112-273545fd83ea)

![Image](https://github.com/user-attachments/assets/b6418838-dd56-42dc-b326-2ed161c2edc7)

Published site

![Image](https://github.com/user-attachments/assets/7e6b3e1c-c031-42ca-bd40-900d4bcdd5c6)

![Image](https://github.com/user-attachments/assets/5dd92896-7cb9-4fab-abb1-eb7054468175)

### Steps to reproduce

Here is a link to our GitHub repository: https://github.com/Post45-Data-Collective/website

Here is a link to the gh-pages branch: https://github.com/Post45-Data-Collective/website/tree/gh-pages

### Your environment

- MacOS Sonoma 14.3
- VS Code 1.85.2

### Quarto check output

```
quarto check 
Quarto 1.5.47
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.47
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.02
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/melwalsh/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/melwalsh/website/website/renv/library/R-4.3/aarch64-apple-darwin20
        - /Users/melwalsh/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.3/aarch64-apple-darwin20/ac5c2659
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Quarto makes no distinction between a "local" and a "published" render; the only thing that `publish` does is upload your site to the appropriate place. The only thing I can imagine that's happening here is that you're rendering with different Quarto versions on your machine and on CI. Can you confirm that's not the case?

**Comment by mcanouil** [comment]
The version is not the same.
Quarto CLI version reported in the OP is `1.5.47`.
The version used on your CI is the latest stable version `1.6.39`: https://github.com/Post45-Data-Collective/website/blob/gh-pages/index.html#L5

**Comment by cscheid** [comment]
I'm going to go ahead and close this, then.

**Comment by melaniewalsh** [comment]
Thank you @mcanouil for catching this! I appreciate it.
