### ISSUE TITLE
Display quarto version in footer by default

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#11642]
### Bug description

I think the default website should display the quarto version in the footer. e.g.:

![Image](https://github.com/user-attachments/assets/1273e05b-e014-4de4-8cce-4904c96966d4)

I am building locally on a MacOS and deploying on a Windows machine an internal company website but don't have access to the deployment pipelines. Finding out the version of quarto used in deployment was a hassle. 

I had to add the following

```yaml
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/) v{{< meta version >}}"
```

And I had to add the following filter to my `_quarto.yml`

```lua
local function get_command_output(command)
  local handle = io.popen(command)
  local result = handle:read("*a"):gsub("%s+", "")
  handle:close()
  return result
end

function Meta(meta)
  -- Get Quarto version
  local quarto_version = get_command_output("quarto --version")

  -- Add information to metadata
  meta["version"] = (meta["version"] or "") .. quarto_version

  return meta
end
```

It would be nice if 

1. There was a better way to access the quarto version using a shortcode (maybe there is? when I read through the docs / searched the docs I couldn't find it)
2. If the default template for a website came with a `page-footer` section where the version was displayed.

### Quarto check output

not relevant

**Comment by mcanouil** [comment]
The version is available in the html metadata header.

**Comment by cscheid** [comment]
We definitely don't want that, or anything that automatically advertises Quarto. We deeply believe in letting people's content shine exclusively. We're not going to stop extensions from doing that, but (as long as I'm lead developer!) we'll never implement something like that.

**Comment by mcanouil** [comment]
Also the first request is a duplicate:

- https://github.com/quarto-dev/quarto-cli/issues/11379

**Comment by kdheepak** [comment]
I appreciate the approach to advertisement. 

I still think having the following in the default website project might be a good idea:

```
  page-footer:
    right: "v{{< meta version >}}"
```

**Comment by mcanouil** [comment]
@kdheepak that's highly subjective. Default should remain simple in my opinion. I personally never needed to have the version be displayed prominently where a simple right click and inspect in my browser give me the information for absolutely all Quarto documents/projects based on HTML.

**Comment by kdheepak** [comment]
Ah, that's what you meant by metadata! I found it now:

![Image](https://github.com/user-attachments/assets/4909c288-d17b-4594-a85c-a96516b4965e)
