### ISSUE TITLE
Markdown text in mermaid node not vertically centred

### ISSUE THREAD

**Issue by DOSull** [quarto-dev/quarto-cli#11693]
### Bug description

Markdown formatted text in mermaid nodes is not vertically centred.

### Steps to reproduce

````qmd
---
title: "Test"
format: html
---

```{mermaid}
flowchart LR
  A(["`START`"]) 
  B["`Hello
  World`"]
  C(["`END`"])
  A --> B
  B --> C
```
````

### Expected behavior

I expect the node labels to be centred vertically in the boxes, as they are on the mermaid live editor at https://mermaid.live/

### Actual behavior

<img width="328" alt="Image" src="https://github.com/user-attachments/assets/62e1e626-cef2-452f-9022-faf31ccde067" />

### Your environment

- IDE: VSCode 1.95.3
- OS: MacOS Sonoma 14.6.1

### Quarto check output

Quarto 1.4.551
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.551
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.06
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/david/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.7
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.49
      rmarkdown: 2.29

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Thanks for the report.

Mermaid has a lot of update and you are using a quite old version of Quarto, thus Mermaid.js versions used by both tools are quite different.
Please update your version of Quarto.

**Comment by DOSull** [comment]
My apologies... versions updated and it's all good now... I thought my setup was more up to date than it was.
