### ISSUE TITLE
Copilot Stops Working in Saved Quarto (.qmd) Files in RStudio

### ISSUE THREAD

**Issue by mrembert** [quarto-dev/quarto-cli#11708]
### Bug description

Within the RStudio IDE, GitHub Copilot exhibits inconsistent behavior when working with Quarto (.qmd) files. While Copilot functions as expected in unsaved Quarto files and both saved and unsaved R files (.r), it completely ceases to provide code suggestions or completions in Quarto files once they are saved to disk.

Specifically, the following behaviors are observed:

- **Interruption of Service:** After saving a Quarto file, Copilot stops providing automatic code suggestions as you type.
- **Unresponsive to Manual Requests:** Manual requests for Copilot completions (triggered by the keyboard shortcut Ctrl+\) are also ignored. There is no visible activity or response from Copilot in the RStudio console or the Copilot logs when a manual request is made within a saved Quarto file.
- **Inconsistent with File Type:** This behavior is specific to saved Quarto files. Copilot continues to function correctly in unsaved Quarto files and in both saved and unsaved R files.
- **Independent of Project Context:** The issue occurs regardless of whether the Quarto file is part of an RStudio project or a standalone file.
- **Copilot Logs:** The Copilot logs indicate that the extension is successfully indexing all project files, including saved Quarto files. However, no log entries are generated when a completion request is made (either automatically or manually) from within a saved Quarto file, suggesting that RStudio is not forwarding these requests to the Copilot extension.

### Steps to reproduce

1.  Open RStudio.
2. Create a new Quarto document (File -> New File -> Quarto Document).
3. Start typing R code in the document. GitHub Copilot suggestions work as expected.
4. Save the Quarto file (e.g., as test.qmd).
5. Continue typing R code. Copilot suggestions no longer appear.
6. Manually trigger a Copilot completion request using Ctrl+\. No Copilot activity is observed in the RStudio console or the Copilot logs.

### Expected behavior

GitHub Copilot should continue to provide code suggestions and completions in saved Quarto files, just as it does in unsaved Quarto files and in R files.

### Actual behavior

GitHub Copilot does not provide code suggestions and completions in saved Quarto files.

### Your environment

 RStudio Edition : Desktop
 RStudio Version :  2024.12.0 
 OS Version      :  Windows 11 Enterprise Version 21H2
 R Version       :  4.3.1

### Quarto check output

[>] Checking environment information...
      Quarto cache location: C:\Users\####t\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.6.39
      Path: C:\Users\#####\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\####\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: C:/Users/####/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/Users/####/AppData/Local/Programs/R/R-4.3.1
      LibPaths:
        - C:/Users/####/AppData/Local/R/win-library/4.3
        - C:/Users/####/AppData/Local/Programs/R/R-4.3.1/library
      knitr: 1.44
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Thanks for reaching out, but this repo is for the command-line tool. You probably want to file on https://github.com/rstudio/rstudio

**Comment by mrembert** [comment]
Thanks!
