### ISSUE TITLE
Website render consumes all memory

### ISSUE THREAD

**Issue by kubu4** [quarto-dev/quarto-cli#11701]
### Bug description

When I render my website, rendering usually hangs/fails at `index.qmd`. Additionally, no error message is produced; the command just ends and returns control of the terminal window.

I've noticed that rendering my website is consuming all of the memory on my machine (Kubuntu 22.04.5LTS, in VMWare Player):

![Image](https://github.com/user-attachments/assets/94eedb45-260e-40ac-bc05-a69444f6423e)

I'm guessing this is what causes rendering to fail. Of course, it's also surprising that rendering would consume 31GB of RAM...

### Steps to reproduce

I'm unable to provide a reproducible example, as this seems specific to a large website. Small, test websites don't produce this high level of memory consumption and render without issue.

The website repo is here:

https://github.com/RobertsLab/sams-notebook

### Expected behavior

Rending should either finish or if it does not, should generate an error indicating why rendering did not complete.

### Actual behavior

Rendering hangs/fails at `index.qmd` without an error message and then simply returns control of the terminal window.

### Your environment

Command line (no IDE).

Kubuntu 22.04.5LTS, running in VMWare Workstation 17 Player.

### Quarto check output

Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /home/sam/.cache/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.5 (Conda)
      Path: /home/sam/programs/miniforge3-24.7.1-0/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.2
      Path: /usr/lib/R
      LibPaths:
        - /home/sam/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Thanks for the report - this shouldn't be happening.

Unfortunately, I can't repro locally because some of your content assumes specific paths that I don't have in my machine:

```
...
[ 210/1587] posts/2023/2023-11-30-Plotting-Fun---Lab-Meeting-Task/index.qmd
processing file: index.qmd
1/33
2/33 [load-libraries]
3/33
4/33 [check-deep-dive-existence]
sh: line 0: cd: /home/sam/gitrepos: No such file or directory
```

We do know a number of large websites that used to consume large amounts of memory, but we fixed that issue earlier in 2024 (by not keeping all HTML DOMs in memory at the same time). It's possible that we've regressed here, but 

I unfortunately really don't have the resources to fix your website in order to render in my environment; would you be willing to review your repository and produce a branch that doesn't have those entries?

**Comment by kubu4** [comment]
Thanks so much for looking into this (and so quickly)!

Gah! There are some computational notebook posts with paths to files/programs, as you encountered.

I'll try to create a new branch and get rid of those, but it'll take a bit of time.

Thanks again and I'll post once I have that branch ready!

**Comment by cscheid** [comment]
Thanks, that's deeply appreciated.

FWIW, I just monitored memory usage for rendering [quarto.org](https://github.com/quarto-dev/quarto-web), and although it's about 5x smaller at 357 total files, the total memory consumption never went over 500MB locally.

**Comment by kubu4** [comment]
Alrighty, I _think_ I managed to delete all of the computational notebook entries (I attempted to programmatically identify .qmd files containing R code chunks).

Here's a new repo branch _without_ those posts:

https://github.com/RobertsLab/sams-notebook/tree/rm-computational-nbs

**Comment by cscheid** [comment]
I can repro locally. Somehow, _pandoc_ is taking up all RAM here:

<img width="573" alt="Image" src="https://github.com/user-attachments/assets/80de2cdc-746b-4181-8eeb-a9011c4295fe" />

**Comment by kubu4** [comment]
Thanks again for checking this out. I sincerely appreciate it!

**Comment by cscheid** [comment]
Thank you for filing it!

We love to see 1000+ page Quarto websites, and we're aware that there aren't so many of those out there. We appreciate you, sincerely. I think I have a clean fix, and it's something we can do locally in Quarto. I'll run some tests to confirm first.

The context for the bug is that Pandoc's HTML-inside-Markdown appears to be causing a large memory blow-up. There's no reason for us to be emitting naked HTML inside Markdown, as opposed to wrapping the HTML we generate in an HTML raw block node.

**Comment by kubu4** [comment]
Wow! Thanks!!

So, if I wanted to utilize this, I'd have to install the Quarto development version (or, wait until the next release), correct?

**Comment by cscheid** [comment]
I'm building new 1.7 pre-release installers right now. 1.7.5 and later should have the fix in. You can keep an eye out for it on [this page](https://github.com/quarto-dev/quarto-cli/releases).
