### ISSUE TITLE
Image preview / social media card image not working

### ISSUE THREAD

**Issue by melaniewalsh** [quarto-dev/quarto-cli#11739]
### Bug description

We are setting an `image:` in the yaml for the whole website and for individual pages, but the images aren't getting included in social media cards. Here's the page in question: https://data.post45.org/posts/nea-creative-writing-fellowships/

 <img width="595" alt="Image" src="https://github.com/user-attachments/assets/de1cff2d-26ac-4079-bfe0-03c728832b26" />

Here's the `image` on a page included in the page yaml: https://github.com/Post45-Data-Collective/website/blob/b0e715bf3f3489d1dbb95992c591021a650cab38/website/posts/nea-creative-writing-fellowships/index.qmd#L3

Here's the `image` on the website included in the site yaml: https://github.com/Post45-Data-Collective/website/blob/b0e715bf3f3489d1dbb95992c591021a650cab38/website/_quarto.yml#L7-L9

GitHub repo for site (site generated with GitHub Actions): https://github.com/Post45-Data-Collective/website/tree/main

### Your environment

- MacOS Sonoma 14.3
- VS Code 1.85.2

### Quarto check output

```
quarto check
Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /Users/melwalsh/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.02
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/melwalsh/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/melwalsh/website/website/renv/library/R-4.3/aarch64-apple-darwin20
        - /Users/melwalsh/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.3/aarch64-apple-darwin20/ac5c2659
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
From X developper doc: https://developer.x.com/en/docs/x-for-websites/cards/overview/markup
about `twitter:image` meta
> URL of image to use in the card. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. **SVG is not supported.**

You are using `.svg` here: 
````html
<meta name="twitter:image" content="https://upload.wikimedia.org/wikipedia/commons/3/3b/National_Endowment_for_the_Arts_%28NEA%29_Logo_2018_Square_on_Black.svg">
````

So I think this is the issue.

**Comment by melaniewalsh** [comment]
Thanks for the prompt responses! @cderv @mcanouil 

We changed the image to a png (you can see [the yaml here](https://github.com/Post45-Data-Collective/website/blob/a666745c33ebd0f9a2cc7431101d047578fe613e/website/posts/nea-creative-writing-fellowships/index.qmd#L3)), but for some reason it's still not showing up in the social media card...

**Comment by melaniewalsh** [comment]
Also @mcanouil do you have any suggestions to make our setup less weird? haha Should we not render to docs if we're using GitHub Actions?

**Comment by mcanouil** [comment]
You have to choose one GitHub Pages rendering method and not mix several of them.

- https://docs.github.com/en/pages


FYI, `quarto publish gh-pages` uses ‘gh-pages` branch method.

**Comment by cderv** [comment]
It seems it is indeed a caching issue of some sort. This is what I get on Bluesky
![Image](https://github.com/user-attachments/assets/3d28fe45-e826-4acf-b2e9-f9b1f1f71727)

but it seems to still be an issue on X.com
![Image](https://github.com/user-attachments/assets/003a573d-1dab-4615-acfa-b2c478bf0d78)

So not sure why, but this is not quarto issue IMO. You need to check twitter / X.com spec, and maybe tweak your image. (lower size maybe ?)

**Comment by mcanouil** [comment]
Cache refresh on X can no longer be triggered (they removed the tool) and has quite a low rate.

Better to use third party checker which has higher refresh rate:
- https://www.opengraph.xyz
- https://socialsharepreview.com
