### ISSUE TITLE
How to run julia code in positron and RStudio by qmd? How to use QuartoNotebookRunner in positron and RStudio by qmd? https://github.com/PumasAI/QuartoNotebookRunner.jl

### ISSUE THREAD

**Issue by Liu23308** [quarto-dev/quarto-cli#11743]
### Quarto check output

How to run julia code in positron and RStudio by qmd? How to use QuartoNotebookRunner in positron and RStudio by qmd? https://github.com/PumasAI/QuartoNotebookRunner.jl

**Comment by Liu23308** [comment]
```{julia}

1+2

```

Error in julia_setup() : Julia is not found.

**Comment by mcanouil** [comment]
@Liu23308 in the future, please do read the guidelines provided in issues/discussions and DO NOT open several threads at the same time! Thank you for your understanding.
