### ISSUE TITLE
Image column layouts just never work as expected

### ISSUE THREAD

**Issue by peekxc** [quarto-dev/quarto-cli#11741]
### Bug description

The layout functionality in quarto is just completely broken as far as I'm concerned (and has been for sometime)

Here's four different reproducible examples that should all be equivalent but produce a myriad of results (none of which are correct). 

```quarto
---
format: revealjs
---

::: {#fig-elephants layout-ncol=2}

![](hanno.jpg)

![](hanno.jpg)

:::
```

```quarto
---
format: revealjs
---

::: {#fig-elephants layout-ncol=2}

![](hanno.jpg)
![](hanno.jpg)

:::
```

```
---
format: revealjs
---

::: {#fig-elephants layout-ncol=2}
<img src="hanno.jpg"/>
<img src="hanno.jpg"/>
:::
```

```
---
format: revealjs
---

::: {#fig-elephants layout-ncol=2}

<img src="hanno.jpg"/>

<img src="hanno.jpg"/>

:::
```

```
---
format: revealjs
---

::: {#fig-elephants layout-ncol=2}

<img src="hanno.jpg"/>

<img src="hanno.jpg"/>

<!--  -->

:::
```

These produce the following presentations: 

<img width="1721" alt="Image" src="https://github.com/user-attachments/assets/32c531d8-2149-4eff-9423-20980962a61b" />
<img width="1730" alt="Image" src="https://github.com/user-attachments/assets/0b9f46ea-4f38-4ec4-9912-ea2639b1a696" />
<img width="1725" alt="Image" src="https://github.com/user-attachments/assets/2ffbcf0e-d96b-49f5-9489-015c769f1eb3" />
<img width="1723" alt="Image" src="https://github.com/user-attachments/assets/7bde5fa0-3e2e-439c-a281-30c3e7eefb1e" />
<img width="1726" alt="Image" src="https://github.com/user-attachments/assets/716dc3d5-43e3-4fcc-b33e-d9299fe74ad5" />

The same is true for e.g. `layout=[[1,1]]` and similar. 

### Steps to reproduce

Already shown

### Expected behavior

Consistent behaviour: two images in two columns with no figure description.

### Actual behavior

Shown. 

### Your environment

- MacOS Sonoma 14.5
- Quarto version: 1.6.39

### Quarto check output

Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /Users/mpiekenbrock/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/local/texlive/2021/bin/universal-darwin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/local/bin/python3
      Jupyter: 5.1.3
      Kernels: spirit, python3, julia-1.6, blog

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.0.5
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/mpiekenbrock/Library/R/4.0/library
        - /Library/Frameworks/R.framework/Versions/4.0/Resources/library
      knitr: 1.30
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Thanks but as described in the issue template could you use the placeholder shortcode instead of a local image file only you have?

https://quarto.org/docs/authoring/placeholder.html

> has been for sometime

What does this mean? Since which version?

**Comment by gordonwoodhull** [comment]
I know your main issue is with the layout, but

> with no figure description

Making the figures cross-referenceable with `#fig-elephants` causes “Figure 1” to be displayed.

**Comment by mcanouil** [comment]
I think there is a missunderstanding about what the code is supposed to do and what you expect.
The code is working exactly as it is supposed to.

Using `#fig-` means you are building a cross-reference object. A cross-reference object needs a caption.

In the following, the two images have captions so Quarto takes them as sub-figures and no global caption.

<table>
<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
format: revealjs
---

## Slide 1

::: {#fig-elephants layout-ncol=2}

![An image]({{< placeholder 600 400 >}})

![An image]({{< placeholder 600 400 >}})

:::
````

</td><td>

<img width="722" alt="Image" src="https://github.com/user-attachments/assets/e28b71e0-69c0-457f-8eb1-a15ec65c5ea6" />

</td></tr>
</table>

The full correct syntax for cross-reference div as described in the documentation: https://quarto.org/docs/authoring/cross-references-divs.html

<table>

<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
format: revealjs
---

## Slide 1

::: {#fig-elephants layout-ncol=2}
![An image]({{< placeholder 600 400 >}})

![An image]({{< placeholder 600 400 >}})

A caption for the images.
:::
````

</td><td>

<img width="726" alt="Image" src="https://github.com/user-attachments/assets/f2d7bb01-8fcf-41e6-95f4-87b86409dd90" />

</td></tr>
</table>

What you did was the following.
Meaning you are asking Quarto to use the second image (not a figure as it has no caption) as the caption of your cross-reference div. Quarto exactly did that, thus the second image being centred under the first image.

<table>
<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
format: revealjs
---

## Slide 1

::: {#fig-elephants layout-ncol=2}

![]({{< placeholder 600 400 >}})

![]({{< placeholder 600 400 >}})

:::

````

</td><td>

<img width="729" alt="Image" src="https://github.com/user-attachments/assets/06f1e73a-8fcf-459e-b3aa-99dde889b92f" />

</td></tr>
</table>

Now, if your images are no figures (no captions and no cross-references), then don't use `fig-` prefix for IDs.
https://quarto.org/docs/authoring/cross-references.html

<table>

<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
format: revealjs
---

## Slide 1

::: {#elephants layout-ncol=2}

![]({{< placeholder 600 400 >}})

![]({{< placeholder 600 400 >}})

:::

````

</td><td>

<img width="728" alt="Image" src="https://github.com/user-attachments/assets/f21de9ee-74f7-4be8-9654-8e895133de8f" />

</td></tr>
</table>

**Comment by mcanouil** [comment]
To summarise, I don't see any bugs here. Only a miss-use of the cross-reference div syntax.

**Comment by peekxc** [comment]
Thank you @mcanouil for you detailed response. I guess I was indeed misunderstanding the syntax, they all seemed reasonable to me yet lead to very different outputs, and I couldn't find a single one that was working.

I wasn't aware of the cross-reference syntax; I thought the '#' was simply adding an id to the corresponding `div` element, as is common in e.g. CSS, jQuery, pugjs, and similar. 

I will make my issues more reproducible in the future.
