### ISSUE TITLE
Update to Deno 1.22.3

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1175]
@cscheid For our stable release I wanted to take the final patch release of Deno 1.22 (v1.22.3, we are currently back at 1.22.0). I have so far done the following:

- Updates configuration for Deno 1.22.3
- Updates the embedded standard library for quarto run to 0.143.0 (the version that was released with Deno 1.22.3)

These commits are on this branch: https://github.com/quarto-dev/quarto-cli/tree/feature/deno-1.22.3

I wasn't exactly sure how to update the vendored stuff though, so hopefully you can do that so I can get schooled on the process.

One potential snag point is that the cliffy code has full URL imports of the old std library (0.138.0) so it seems like some additional redirection from 0.138.0 to 0.143.0 might be required?

Once you have tests passing and this is ready to merge, let's squash the branch down to a single commit so that we can easily back it out if there are unexpected regressions.

**Comment by cscheid** [comment]
I'll do it, no problem. (FWIW it _should_ be just a matter of editing `src/import_map.json` and then rea-running the configure scripts. It's possible that I messed something up, let me see.)

**Comment by cscheid** [comment]
That appears to have worked.

After editing `src/import_map.json`, the files in `src/vendor` changed, so I just added them back to VC and pushed. See https://github.com/quarto-dev/quarto-cli/pull/1176

**Comment by cscheid** [comment]
It's squashed and merged on `main`, https://github.com/quarto-dev/quarto-cli/commit/f6d7826d389dd2317641e83803c4d6f3457ff5f9

**Comment by jjallaire** [comment]
Awesome, thx!!!
