### ISSUE TITLE
Feature Request: Additional formatting options for markdown tables

### ISSUE THREAD

**Issue by SEthanMilne** [quarto-dev/quarto-cli#1177]
I'm working on a paper that includes many tables in an appendix section. Some tables are too large to be output on a single portrait-oriented page.

A standard practice in my field is to present tables in rotated format — not changing the portrait/landscape orientation of the page, but simply rotating the table.

I've looked around the Quarto documentation and can't find any hints as to how I might do this. Any help would be appreciated.

**Comment by jjallaire** [comment]
There isn't a Quarto feature for this, however if you are emitting LaTeX tables it's possible you can clean a workable hack from this article: https://tex.stackexchange.com/questions/25369/how-to-rotate-a-table (although honestly I know very, very little about this level of LaTeX so I'm not sure how practical this is).

**Comment by LBeaulaton** [comment]
Hi
thanks for the great job.
Any improvement?
I see the [landscape mode](https://quarto.org/docs/authoring/article-layout.html#landscape-mode) is now available. Problem is that it creates a new page "immediately" and prevent to have the table and text place adequately. Below a minimal example. when landscape mode is activated the to "lorem ipsum" are place in 2 separate pages whereas without they are group and the table is in a separate page but in portrait mode (as expected).

````quarto
---
title: "My document"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

lorem ipsum ...

::: {.landscape}
```{r}
#| label: tbl-test
#| tbl-cap: test
#| results: asis
#| echo: FALSE

kableExtra::kbl(
  head(iris, n = 10),
  booktabs = TRUE,
  linesep = "",
  align = "c"
) |>
  kableExtra::row_spec(0, bold = TRUE) |>
  kableExtra::column_spec(1, bold = TRUE) |>
  kableExtra::kable_styling(latex_options = "striped")
```
:::

lorem ipsum ...

````

**Comment by mcanouil** [comment]
@LBeaulaton Please use Discussions for these requests.

You can use any Raw LaTeX (see https://quarto.org/docs/authoring/markdown-basics.html#raw-content) for advanced LaTeX layout, which has some very hard rules. Quarto/Pandoc can't possibly know where to change page orientation. A "landscape" is not a float object in LaTeX by the way which would require some additional commands such as `\afterpage{%`. Unfortunately, the "landscape" shortcode is a general purpose shortcode and there are cases where it's unlikely a user would want the landscape to be a float and have other elements wrap around it.
