### ISSUE TITLE
Problem creating PDFs - 'No TeX installation was detected' (Windows 10)

### ISSUE THREAD

**Issue by lukesdm** [quarto-dev/quarto-cli#1180]
### Bug description

When trying to generate a PDF with the VS extension or e.g.  `quarto.cmd preview paper.qmd`, I get the following error, even after installing tinytex as per the instructions.
 
```
No TeX installation was detected.

Please run 'quarto install tool tinytex' to install TinyTex.
If you prefer, you may install TexLive or another TeX distribution.
```

```
$ quarto.cmd install tool tinytex
tinytex is already installed and up to date.
```

Platform: Windows 10

```
$ quarto.cmd check

[>] Checking Quarto installation......OK
      Version: 0.9.596
      Path: C:\Users\luke\AppData\Local\Programs\Quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.1
      Path: c:/Users/luke/src/cde/cde-stuff/scientific-writing/assignment-4/.venv/Scripts/python.exe
      Jupyter: 4.10.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.1.3
      Path: C:/PROGRA~1/R/R-41~1.3
      LibPaths:
        - C:/Program Files/R/R-4.1.3/library
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by dragonstyle** [comment]
Thanks for reporting this! Would you mind trying a couple of things

1) Exiting and starting a new vscode process. When tinytex is installed, it places TeXLive on the path, but perhaps the running vscode is using the older copy of the path.

2) If that doesn't resolve the issue, could you running the following command and share its output?

`quarto tools info tinytex`

Sorry that you ran into this!

**Comment by lukesdm** [comment]
Thanks very much for your response @dragonstyle . A restart of VS Code did not fix it. However, logging out (of Windows) and logging in again did.
