### ISSUE TITLE
YAML autocompletion for formats is not working anymore

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#1184]
### Bug description

The change in our format regex to support custom formats breaks autocompletions because our "complete through prefixes" code doesn't currently support character classes.

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
As of the latest commit, this should be fixed. @cderv can you check if this works for you on `main`?

**Comment by cderv** [comment]
I confirm this is working after updating main.
