### ISSUE TITLE
[feature request] More informative error messages on YAML errors

### ISSUE THREAD

**Issue by dhicks** [quarto-dev/quarto-cli#1187]
### Bug description

I'm running Quarto 0.9.600. 

When Quarto encounters a YAML error anywhere in the document, it fails with the error message
```{md}
ERROR: Render failed due to invalid YAML.
```
Since in-chunk options are handled as YAML, such errors can appear anywhere in the document's source files.  If it's been a minute since you've re-rendered the output, the lack of information in the error message can make it challenging to locate the problem in a moderately complex document.  

````md
---
title: "This document is broken"
author: "But where?"
---
```{r}
#| include: false
2 + 2
```
The problem isn't in the previous chunk. Maybe it has to do with @tbl-mtcars? 
```{r}
#| label: tbl-mtcars
#| tbl-cap: "Right here! I'm missing my closing quote
knitr::kable(mtcars)
```
````

So as a feature request/enhancement I'd like to request more informative error messages when the YAML parser gets tripped up. 

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Ouch, this is a horrible error, agreed. We will fix right away.

**Comment by cscheid** [comment]
With a release from this morning, I'm seeing a slightly less bad error:

```
$ quarto render bad-yaml-error.qmd
ERROR: Validation of YAML cell metadata failed.
In file bad-yaml-error.qmd
(line 15, columns 4--11) Key tbl-cap has empty value but it must instead be a string
14: #| label: tbl-mtcars
15: #| tbl-cap: "Right here! I'm missing my closing quote

16: knitr::kable(mtcars)

ERROR: Render failed due to invalid YAML.
```

It's not great, but it's at least pointing at a better spot. Before we fix it, I'd like to understand how you're seeing that specific error message.

**Comment by cscheid** [comment]
@dhicks what OS are you running quarto on, and can you give me the output of `quarto check`? Thanks.

**Comment by dhicks** [comment]
I'm not sure how/why I didn't see those better messages yesterday, but I'm seeing them today without updating Quarto again.  So I guess it's resolved.  Sorry to take up your time yesterday!

**Comment by cscheid** [comment]
Don't worry. We had been emitting that bad error message in the past, so it's totally plausible you found some corner case. If you can spot it again, please do reopen the issue!
