### ISSUE TITLE
Broken Quarto 0.9.598 when using `brew install/upgrade quarto`

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#1188]
When filling #1186, I upgraded Quarto as usual with `brew upgrade quarto` and I encountered an error while trying to render #1186 again.

```
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
/Applications/quarto/bin/quarto: line 106: 44356 Trace/BPT trap: 5       "${SCRIPT_PATH}/tools/deno" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"
```

I tried to reinstall 0.9.598 (latest: https://formulae.brew.sh/cask/quarto#default) which produced the same result.

OS: MacOS arm64

**Comment by mcanouil** [comment]
I found the issue, this is (again) related to Shell integration and #1154

**Comment by jjallaire** [comment]
I'd like to understand the exact source of this problem better -- we updated to deno 1.22.3 and @softwarenerd saw this exact same error -- I then downgraded to deno 1.22 and that cleared up the error.

So perhaps some interaction between shell settings and the deno update.

@dragonstyle I don't think we can update to deno 1.22.3 (which I would like to do for this release) until we understand the source of this problem better.

@mcanouil If you have insight about what specifically is different about the shell environment that would help. @softwarenerd are you just using the default `zsh` shell on OS X or something more custom?

**Comment by mcanouil** [comment]
In addition to zsh, I am using https://github.com/romkatv/powerlevel10k which is know to have some issues with VSCode https://github.com/microsoft/vscode/issues/146587
Although, I am not sure how or if it is related to the current issue here.

**Comment by mcanouil** [comment]
I upgraded Quarto to 0.9.600, and now disabling Shell Integration or not does not help with the error.
Quarto 0.9.600 produces the error all the time.

I am wondering could it be a conflict issue with installed binaries?
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/8896044/174788034-a40e94b2-c826-4112-92d5-f26b8c9a1aad.png">

**Comment by ha0ye** [comment]
Had the same issue over the weekend. New binaries and building 0.9.600 from source resolved the issue for me (in both RStudio and CLI).

No particular shell customizations here.

zsh and Mac arm64 (OS 11.6)

**Comment by jjallaire** [comment]
I think the issue here is related an interaction between deno 1.22.3, possibly the deno 0.143.0 standard library, and M1/M2 macs. We have reverted to deno 1.22.0 and deno_std 0.138.0 which should serve as a temporary resolution.
