### ISSUE TITLE
quarto does not know how to render verbatim code chunks

### ISSUE THREAD

**Issue by charliejhadley** [quarto-dev/quarto-cli#1190]
### Bug description

I've moved to `quarto` from RMarkdown where it is possible to insert verbatim code chunks, as in this example document:

`````
---
title: "rmarkdown"
output: html_document
---

````{quarto}
---
output: html_document
---
  
```{r}
2+2
```

````
`````

However, in `quarto` this does not work:

`````
---
title: "{quarto}"
format: html
---

````{verbatim}
---
output: html_document
---
  
```{r}
2+2
```

````
`````

When using RStudio to render the `.qmd` document the following warning is generated:

```
In get_engine(options$engine) :
  Unknown language engine 'quarto' (must be registered via knit_engines$set()).
```

Which suggests if a code chunk is specified in an unknown language engine it defaults to the 'quarto' engine? Conversely, in RMarkdown if you provide an unknown language engine (eg `pretend`) there is an attempt to use that engine

```
Warning message:
In get_engine(options$engine) :
  Unknown language engine 'pretend' (must be registered via knit_engines$set()).
```

### Version info

- Operating System: macOS Monterey

- quarto check

```
[✓] Checking Quarto installation......OK
      Version: 0.9.288
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12
      Path: /usr/local/opt/python@3.9/bin/python3.9
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

- RStudio version `2022.02.3 Build 492`

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [x] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cderv** [comment]
Hi @charliejhadley ! 

This does not give me any error 
`````
---
title: "{quarto}"
format: html
---

````{verbatim}
---
output: html_document
---
  
```{r}
2+2
```

````

`````

Usually when you are not using any R code chunk, but still want **knitr**, you need to add engine binding manually as guessing won't work https://quarto.org/docs/computations/execution-options.html#engine-binding

````yaml
---
title: "{quarto}"
format: html
engine: knitr
---
````

Regarding the first example 
`````` markdown
---
title: "rmarkdown"
output: html_document
---

````{quarto}
---
output: html_document
---
  
```{r}
2+2
```

````
`````

You are explicity asking for a `quarto` engine to run. This is not defined as the error says. What are you trying to do here ? 

Thanks

**Comment by charliejhadley** [comment]
Sorry - I don't think I explained this well.

### RMarkdown verbatim code chunks

If I want to show a code chunk that contains code chunks inside an .Rmd I can do this

`````
---
title: "rmarkdown"
output: html_document
---

````{verbatim}
---
output: html_document
---
  
```{r}
2+2
```

````
`````

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/9363263/174813261-109625b3-3436-4596-952e-510ed6179a1a.png">

### quarto verbatim code chunks

I can't figure out how to do the same with quarto

`````
---
title: "{quarto}"
format: html
engine: knitr
---

````{verbatim}
---
output: html_document
---
  
```{r}
2+2
```
````
`````

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/9363263/174813713-08208714-ac66-4cf8-a17b-c2e9dc2f6ed2.png">

**Comment by cderv** [comment]
As I said in previous post, this working for me 
![image](https://user-images.githubusercontent.com/6791940/174837391-18df15f3-a751-4074-8bc5-7ad4ecac4a7b.png)


So I think you may just need to update Quarto - you are using Version: 0.9.288 and last in Version: 0.9.603
