### ISSUE TITLE
code-tools view source for ojs doesn't always use `{ojs}` 

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1192]
### Bug description

Try rendering the penguins example here: https://github.com/quarto-dev/quarto-web/blob/main/docs/interactive/ojs/examples/penguins.qmd

When you view source, note that the first `{ojs}` cell includes braces but subsequent ones do not:

![Screen Shot 2022-06-21 at 10 27 16 AM](https://user-images.githubusercontent.com/104391/174825042-6d6d26f3-b96c-46ac-bae4-048d2633c420.png)

### Checklist

- [ ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, self-contained, and reproducible example?
- [ ] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Good catch. I know what this is. I'll fix it right now.

**Comment by cscheid** [comment]
Here's what's happening.

- In `command/render/codetools.ts:79`, we are adding sentinels which trim off the `{` and `}` from the cell declaration.
- In `command/render/codetools.ts:107`, we check for the presence of the sentinels, and do some DOM searching to find a place to reinsert the curly brackets.

Somehow, in between sending the sentinel'ed code to pandoc and reading it back, something is processing the first `ojs` block differently from the other ojs blocks in a way that trips up the DOM searching in line 107.

**Comment by cscheid** [comment]
This is fixed on `main` now.
