### ISSUE TITLE
Any way to use shortcode in page heading?

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#120]
I have a shortcode `myvar` defined as "my variable" in `_variables.yml`.  This works as I would expect for the top-level index file, and in sub-headings, but not in the top-level heading for a not-top-level file, where the shortcode results in the page title being truncated to the part before the shortcode - "Before shortcode" in the example below, instead of "Before short code my variable after".

This is the text of the input `.qmd` page:

~~~
# Before shortcode {{< var myvar >}} after

Start my text.

## Sub-heading with {{< var myvar >}} inside

And some text.
~~~

If the heading starts with the short code, Quarto ignores that heading, and uses the second-level heading instead.

<https://github.com/matthew-brett/quarto-test-book>

**Comment by dragonstyle** [comment]
Great bug, thank you for reporting it!

I just pushed a fix in [this commit ](https://github.com/quarto-dev/quarto-cli/commit/93d6d6d1e7a178ac4cba9f6782885e1ba1416cbc)

**Comment by matthew-brett** [comment]
Great - thanks.
