### ISSUE TITLE
`ojs_define` in Julia

### ISSUE THREAD

**Issue by p-gw** [quarto-dev/quarto-cli#1203]
Hi, 

I noticed that `ojs_define` is only defined using Python and R, but not Julia. 
Is there any particular reason why this is the case? 

I coded a quick implementation of it myself and so far it seems to be working fine. 

Here is a MWE notebook code: 

````
---
title: ojs_define using Julia
---

```{julia}
using JSON3, DataFrames, JSONTables


convert(x) = x
convert(x::AbstractDataFrame) = JSONTables.ArrayTable(Tables.rows(x))

function ojs_define(; kwargs...)
    content = Dict("contents" => [Dict("name" => k, "value" => convert(v)) for (k, v) in kwargs])
    tag = "<script type='ojs-define'>$(JSON3.write(content))</script>"
    IJulia.display(MIME("text/html"), tag)
end

ojs_define(
    array=[1,2,3],
    string="somestring",
    dict=Dict("a" => 1, "b" => [1, 2]),
    df=DataFrame(x=randn(100), y=randn(100))
)

```

```{ojs}
array
string
dict
df
Plot.plot({
    grid: true,
    marks: [
        Plot.dot(df, { x: "x", y: "y" })
    ]
})
```
````

I am not familiar with the internals of quarto, but if you think this feature is worth implementing I am glad to open a pull request.

**Comment by cscheid** [comment]
This looks great.

@jjallaire what do you think, could we squeeze this into our 1.0? I can't imagine it regressing anything since it's a new feature.

@p-gw Please take a look at https://quarto.org/about.html#pull-requests (specifically, you need to sign the contributor agreement) to get started on a PR.

**Comment by cscheid** [comment]
## Dependencies

I don't know enough about the Julia ecosystem to know if JSON3, DataFrames and JSONTables are the de facto standard packages for quarto's julia support to entirely depend on.

**Comment by cscheid** [comment]
@p-gw I had to make a number of small changes to your code so I want ahead and made the change myself. Thank you for the suggestion, and let us know if this doesn't work for you!

**Comment by p-gw** [comment]
@cscheid This looks good to me, thanks for implementing this so fast!

If you want to create a more general solution you could also consider implementing the `convert(x)` function based on the [Tables.jl](https://github.com/JuliaData/Tables.jl) interface, which DataFrames.jl is also using. See [here](https://github.com/JuliaData/Tables.jl/blob/main/INTEGRATIONS.md) for a list of packages that integrate with Tables.jl.

However, for the majority of cases I think just supporting DataFrames.jl will suffice.

**Comment by jjallaire** [comment]
Hi there @p-gw, posting back here because I'm giving a talk on Quarto at JuliaCon next month and was hoping to find some good examples of using Julia w/ Quarto. If you are able to share any of your own (or are aware of others) please LMK over on this discussion thread: https://github.com/quarto-dev/quarto-cli/discussions/1261. Thanks!

**Comment by cscheid** [comment]
Incidentally, we should let you know that we had to revert out our definition of `ojs_define` from `setup.jl`. We need to be able to create a definition of `ojs_define` that takes no additional dependencies, and it seems that Julia doesn't allow definitions inside a try-catch block. @p-gw If you know a way to make this work, we'd love to hear it!

**Comment by p-gw** [comment]
@jjallaire Unfortunately I don't have anything to share at the moment. If anything comes up I will let you know. 

@cscheid That's a shame. I think the issue here is that `try ... catch` introduces a local scope in Julia. So to define a function globally you can use the `global` keyword, `@eval` the function definition, or assign the output from the `try ... catch` block.

This will not work
```julia
julia> try
  f(x) = x
catch
end
j(0)
ERROR: UndefVarError: j not defined
```

But either one of these versions will work
```julia
# version 1
julia> try 
  global f(x) = x
catch
end
julia> f(1)
1

# version 2
julia> try 
  @eval g(x) = x
catch
end
julia> g(2)
2

# version 3
julia> h = try
  i(x) = x
catch
end
julia> h(3)
3
```

Regarding dependencies I think it should still work for data types in base Julia (strings, numbers, arrays, dicts), but the more important use case (at least for me) is the definition for table based data (e.g. DataFrames.jl). To dispatch on those data types at least some form of dependency is necessary I think. 

If you do not want to include external dependencies, I have packaged the `ojs_define` function in [OJSDefine.jl](https://github.com/p-gw/OJSDefine.jl) which can be loaded if the functionality is required. It is based on the `Tables.jl` interface, so it also works with `DataFrames`.

**Comment by cscheid** [comment]
@p-gw Thank you for those ideas. We did try `global`, but not exactly in the way you describe. I'll give it another shot.

**Comment by jjallaire** [comment]
This is a re-implementation that seems to work as expected: https://github.com/quarto-dev/quarto-cli/commit/90eb066273132bb16d178e6d47d1a81e7d1f7781

@p-gw or @cscheid if you see things that are problematic here let's definitely take another approach.
