### ISSUE TITLE
Rendered figure size depends on engine

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto-cli#1219]
### Bug description

I am switching between `knitr` and `jupyter` engines for rendering a Matplotlib figure using the following reprex:

````
---
engine: jupyter  # knitr
---

```{python}
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2 * np.pi, 100)  # 100 values from 0 to 2𝜋
plt.plot(x, np.sin(x))
```
````

I noticed that the figure in the rendered HTML looks different depending on the engine.

knitr:
![knitr](https://user-images.githubusercontent.com/4377312/175484173-a425fac3-c7f2-436f-ab8f-e140cd0a1557.png)

jupyter:
![jupyter](https://user-images.githubusercontent.com/4377312/175484202-55a1559e-adaa-4e6f-bcf1-0aac2f3f1ce1.png)

I would expect that figures look identical independent of the rendering engine. Regardless of whether or not this is a bug, is there a workaround that sets a specified figure resolution/DPI/scale/... (for knitr and jupyter engines)?

I tried this on macOS 11.6.7.

<details>
<summary>Output of `quarto --check`:</summary>

```
[✓] Checking Quarto installation......OK
      Version: 0.9.613
      Path: /Users/clemens/Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: /Users/clemens/Repositories/python_data_analysis/.venv/bin/python3
      Jupyter: 4.10.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.13

[✓] Checking Knitr engine render......OK
```
</details>

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thanks for reporting this. Note however that we aren't in full control of the knitr -> reticulate -> matplotlib rendering pipeline nor are we in control of the jupyter -> python3 kernel -> matplotlib rendering pipeline (both of those are code created and maintained by other parties) so there isn't a straightforward way for us to guarantee identical results.

**Comment by cbrnr** [comment]
According to the documentation, Quarto chooses a default figure size:
https://quarto.org/docs/computations/execution-options.html#figure-options

It further says that depending on the engine, it sets corresponding parameters. So shouldn't the output be the same then? Do you have any hints which parameters I could tweak to change the figure size (for both knitr and Jupyter engines)? Is it some setting in reticulate?

**Comment by cbrnr** [comment]
I think I'll ask the reticulate devs where this difference comes from. I tried using the exact same `matplotlib.rcParams`, but the reticulate figure has much larger margins.

**Comment by jjallaire** [comment]
For Knitr we set the default fig.width and fig.height chunk options. What reticulate does with those I don't know.

For Jupyter we do the following: https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/jupyter/lang/python/setup.py#L16-L21

Here are the docs that describe this: https://quarto.org/docs/computations/execution-options.html#figure-options

**Comment by cbrnr** [comment]
For the record, these are the only differences in `matplotlib.rcParams` between the two engines (`knitr` vs. `jupyter`):

`backend: MacOSX` vs. `backend: module://matplotlib_inline.backend_inline`
`figure.dpi: 100.0` vs. `figure.dpi: 96.0`
`figure.edgecolor: white` vs. `(1, 1, 1, 0)`
`figure.facecolor: white` vs. `(1, 1, 1, 0)`
`figure.figsize: [8.0, 5.0]` vs. `[7.0, 5.0]`
`figure.subplot.bottom: 0.11` vs. `figure.subplot.bottom: 0.125`
`interactive: False` vs. `interactive: True`
`savefig.dpi: figure` vs. `savefig.dpi: 96.0`
