### ISSUE TITLE
More exciting templates?

### ISSUE THREAD

**Issue by luzelai** [quarto-dev/quarto-cli#123]
Quarto is a pretty exciting project with many new features that greatly enhance the scientific writing of markdown. However, the amount of templates(especially in journal) much smaller Rmarkdown. I would like to ask if it is possible to migrate Rmarkdown templates to it, and if you have any idea to increase the number of templates.😉

**Comment by jjallaire** [comment]
Yes, absolutely! We plan on porting the templates currently available in the rticles (https://pkgs.rstudio.com/rticles/) package as well as documenting how to create and distribute your own templates. This should happen within the next 3-6 months.

**Comment by luzelai** [comment]
That sounds great!Thank you for your hard work!👏👏👏
