### ISSUE TITLE
PDF: `{.callout}` div with heading and footnote different from HTML output

### ISSUE THREAD

**Issue by fitzchivalrik** [quarto-dev/quarto-cli#1235]
### Bug description

Using a `{.callout}` div with a headline and footnote in HTML results in the expected output of a callout block without an icon,
the provided headline and a footnote at the end of the document.
Rendering the same example to PDF via Latex results in unexpected output (see images).

Minimal example:
```markdown
---
format: pdf
---
# Document Title

Text with a footnote^[saying nothing at all.].

::: {.callout}

## Not visible in PDF output

Some text without a footnote.

:::

::: {.callout}

## Still not visible in PDF output

A footnote^[which is inside the callout instead of outside.].

:::
```
![html](https://user-images.githubusercontent.com/77893938/176167897-58cccc16-730b-410d-9532-b5a26c7c07ab.png)

![pdf](https://user-images.githubusercontent.com/77893938/176167832-8b0817ea-abd8-411b-90e7-a5852d563d4e.png)

On Pop!_OS 22.04 LTS `5.17.5-76051705-generic #202204271406~1653440576~22.04~6277a18`
Quarto check output
```
[✓] Checking Quarto installation......OK
      Version: 0.9.628
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: /usr/bin/python3
      Jupyter: 4.10.0
      Kernels: java, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thanks for reporting this. We are finishing up our v1.0 release right now but should be able to fix this for our v1.1 release.
