### ISSUE TITLE
[Feature Request] Exclude {.absolute} images from autostretch

### ISSUE THREAD

**Issue by yjunechoe** [quarto-dev/quarto-cli#1238]
The current autostretch logic targets stand-alone images created with `{.absolute}`, such that the `width` property specified inside the `{ ... }` is ignored/overriden. This was surprising to me because I expected total control of the image when using `{.absolute}`, including its width. Setting the `height` property works, [as expected](https://github.com/cderv/quarto-cli/blob/1f2c6d4d1707a4b824af672d29faef1f797a57bc/src/format/reveal/format-reveal.ts#L679-L681), but it took a while to understand this distinction.

My thought is that absolute positioning violates the assumptions that make autostretch a good idea, beacuse repositioning an image changes what it means for the image to "stretch to fill up the slide". I don't think adding this exception will be unexpected or difficult to grok for users - it can be part of what you sign up for when you decide to `{.absolute}` an image.

Happy to work on a PR if this makes sense!

Reprex:

```
---
title: "r-stretch-reprex"
format: revealjs
---

## One `absolute` img, width set (autostretch)

![](https://quarto.org/quarto.png){.absolute width=500}

## One `absolute` img, height set (no autostretch)

![](https://quarto.org/quarto.png){.absolute height=100}

## Two `absolute` imgs, width set (no autostretch)

![](https://quarto.org/quarto.png){.absolute width=500}

![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){.absolute top=50% width=300}

```

**Comment by cderv** [comment]
Thanks for the suggestion. I think this makes sense, I opened a PR to ignore images with `.absolute` for the auto stretch feature.

**Comment by cderv** [comment]
PR has been merged. So now, images with `.absolute` won't be impacted by autostretch.
