### ISSUE TITLE
Delta updates

### ISSUE THREAD

**Issue by almereyda** [quarto-dev/quarto-cli#124]
Currently Quarto is distributed as a binary, packaged for Debian, Windows and Mac systems.

Since the releases are updated very often, would it be possible to offer delta updates that do not neccessarily couple the runtime, in case it's not updated?

This is natively implemented in RPM and AppImage, and could speed up the update process, while reducing the download size and thus sparing bandwith, and ultimately physical resources.

---

Found via #121

**Comment by jjallaire** [comment]
The best way to get delta updates is to install the development version (then you can just `git pull` to get the latest version (or any branch). More info on that here: https://quarto.org/docs/getting-started/installation.html#development-version

**Comment by almereyda** [comment]
Thank you!
