### ISSUE TITLE
Feature request: Add "date-title:" option in YAML

### ISSUE THREAD

**Issue by fschaffner** [quarto-dev/quarto-cli#1240]
Would it be possible to add an option to change the date title when using `title-block-style: plain`? I'd usually prefer "DATE" or "CREATED" instead of "PUBLISHED". There is already an `abstract-title:` option that allow changing the abstract title. Could a `date-title:` option be added, too?

**Comment by dragonstyle** [comment]
Hi,

Great question! You can customize the display labels for items in title blocks (though I checked and this isn't current documented, which I will fix!).  You can add the following to your metadata to customize:

`author-title`
`affiliation-title`
`abstract-title`
`description-title`
`published-title`
`doi-title`

For example:

```yaml
published-title: Date
```

I'll update the docs shortly.

**Comment by dragonstyle** [comment]
Ok, I've updated the documentation as well - thanks for reporting / asking this!

https://quarto.org/docs/authoring/title-blocks.html#metadata-labels
