### ISSUE TITLE
'quarto publish gh-pages' does not respect output-dir

### ISSUE THREAD

**Issue by ihnorton** [quarto-dev/quarto-cli#1246]
### Bug description

Quarto docs specify to set `output-dir: docs` for gh-pages: https://quarto.org/docs/websites/publishing-websites.html#github-pages -- and set `docs/` as the target directory in the Github Pages config.

However, running `quarto publish gh-pages` appears to ignore the `output-dir` setting.
- input: https://github.com/ihnorton/quarto-demo
- `gh-pages` after running `quarto publish gh-pages` locally (successfully): https://github.com/ihnorton/quarto-demo/tree/gh-pages

This means I need to set the Github Pages config to use `<root>` instead of `docs/`.

Running `quarto render` locally puts the output in `docs/` as expected.

---

- macOS 12.4

- quarto version:
```
base ❯ quarto check
```
<details>

```
[✓] Checking Quarto installation......OK
      Version: 0.9.629
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: /Users/inorton/opt/conda/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.1.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/inorton/Library/R/x86_64/4.1/library
        - /Library/Frameworks/R.framework/Versions/4.1/Resources/library
      rmarkdown: 2.9

[✓] Checking Knitr engine render......OK
```

</details>

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
The docs on the website need to be updated. `quarto publish gh-pages` is specifically made to work with the `gh-pages` branch not a docs directory. We will do this soon.

**Comment by dragonstyle** [comment]
The updated documentation is available here:

https://quarto.org/docs/publishing/github-pages.html

**Comment by tg-x** [comment]
It would be useful to be able to specify an output path inside the gh-pages branch,
to support publishing different branches to different paths from github actions

**Comment by mcanouil** [comment]
@tg-x Please don't post multiple times the exact same message. It does not help.
See <https://github.com/quarto-dev/quarto-cli/issues/1640#issuecomment-1965479875>.

**Comment by tg-x** [comment]
sorry realized i posted under the wrong one

**Comment by mcanouil** [comment]
Both issues are/were about output directory. You are talking about branches.
