### ISSUE TITLE
Publish gh-pages to non-origin repo?

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1249]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1243

<div type='discussions-op-text'>

<sup>Originally posted by **ihnorton** June 29, 2022</sup>
Is it possible to target a repo other than the `origin` with `quarto publish gh-pages`? I read through the [template](https://github.com/quarto-dev/quarto-cli/blob/046f7fc0228e4480b4d9af57f92b5538f8a27e5b/src/publish/gh-pages/gh-pages.ts) and it appears not, _unless_ I misunderstood something about the handling of `siteUrl`. If not, please consider this a feature request 😄 Thanks!</div>

**Comment by jjallaire** [comment]
There isn't current a way to do this but likely something we'll add in the future.

**Comment by mcanouil** [comment]
Closing as duplicate in favour of the more recent one which contains a bit more discussion:
- #5997
