### ISSUE TITLE
unexpected output-location: slide behaviour in revealjs

### ISSUE THREAD

**Issue by DOSull** [quarto-dev/quarto-cli#1254]
### Bug description

Great tool, which I'm enjoying a lot!

Using revealjs presentation I have a pattern like this:

````md
## Slide before
Words

## The slide with the code 
```{python}
#| echo: true
#| output-location: slide
# code that generates an image
```

## The slide after
Words
````
This causes the image generated by the code in the middle slide not to appear until _after_ the slide after. A bit of experimentation seems to show that the image doesn't appear until before the next slide at the top `# Single hash` level. In other words, the code-generated image doesn't show up until the end of that section of the presentation.

That is the output from the code block isn't 'flushed out' until before the next slide at a 'level above'. The behaviour is a bit reminiscent of how LaTeX flushes a 'float' image to the end of a chapter or article if it can't find a place for it.

I'm using vertical navigation, with slide-level at the default level 2. But changing those settings doesn't make any difference. The only thing that does is starting a new top-level slide. 

In case it matters the code generating the image uses matplotlib plotting.

Here's the `quarto check` output

```
[✓] Checking Quarto installation......OK
      Version: 0.9.600
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.8 (Conda)
      Path: /home/osullid3/anaconda3/bin/python
      Jupyter: 4.10.0
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 17, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```

I had not noticed the reported jupyter engine problem before this and it hasn't affected me making slides so far. 

I am running VSCode 1.67.0 and the Quarto extension 1.24.0 on Ubuntu 20.0.4

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [x] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by DOSull** [comment]
Here is minimal example that has the same behaviour

````md
title: MRE
author: David O'Sullivan
format: 
  revealjs:
    navigation-mode: vertical
    self-contained: true
jupyter: python3
---

```{python}
import matplotlib.pyplot as pyplot
```


# First slide
Hello

## Slide with the code
Hello

```{python}
#| echo: true
#| output-location: slide
x = [_ for _ in range(10)]
y = [_ for _ in range(10)]
pyplot.plot(x, y)
```

## Next slide

## Another one for good measure

## Slide before the next section

# Next section
````

**Comment by cderv** [comment]
Thanks. I can reproduce, and currently working on a fix.
