### ISSUE TITLE
Autocompletion is not correctly showing all possible options

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#1260]
### Bug description

Let's say I want to change `highlight-style` for reveal 
````yaml
format:
  revealjs:
    highlight-style: #<-- won't be suggested in auto completion
````

Other example 

````yaml
format:
  pdf:
    pdf-engine:  #<-- not suggested by auto completion
````

Not sure which is the pattern. 

Using latest quarto (d5203c660d293ae3d3ee1b1055da37b74ec4acf0) on Windows 10

````
❯ quarto check

[>] Checking Quarto installation......OK
      Version: 99.9.9
      Path: C:\Users\chris\Documents\DEV_R\quarto-cli\package\dist\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.12
      Path: C:/Users/chris/scoop/apps/pyenv/current/pyenv-win/versions/3.9.12/python.exe
      Jupyter: 4.10.0
      Kernels: bash, julia-1.7, python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/PROGRA~1/R/R-42~1.0
      LibPaths:
        - C:/Users/chris/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.0/library
      rmarkdown: 2.14.3

[>] Checking Knitr engine render......OK
````

````
> RStudio.Version()
$citation

To cite RStudio in publications use:

  RStudio Team (2022). RStudio: Integrated Development Environment for R. RStudio, PBC, Boston, MA URL http://www.rstudio.com/.

Une entrée BibTeX pour les utilisateurs LaTeX est

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{RStudio Team}},
    organization = {RStudio, PBC},
    address = {Boston, MA},
    year = {2022},
    url = {http://www.rstudio.com/},
  }


$mode
[1] "desktop"

$version
[1] ‘2022.7.0.545’

$long_version
[1] "2022.07.0-preview+545"

$release_name
[1] "Spotted Wakerobin"
````

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Update: this is not a bug where I thought it was.

I thought it was a bug on the calculation of prefixes, but it's not. It's a bug because we can no longer pretend we're always completing through prefixes along the instance path of the completion. That was a convenient lie when our formats were prefix-free, but in the presence of custom formats, they're trivially not prefix-free.
