### ISSUE TITLE
reveal-js: Blockquotes rendered differently from pandoc

### ISSUE THREAD

**Issue by asmaier** [quarto-dev/quarto-cli#1264]
### Bug description

The following file `quote.qmd` contains a quote as suggested at https://stackoverflow.com/questions/2002120/citing-the-author-of-a-blockquote-using-markdown-syntax 

```
---
title: "Famous Quote"
format: revealjs
---

> "God doesn't play dice."
>
> -- <cite>Albert Einstein</cite>
```
When rendering with pandoc like

     pandoc -t revealjs -s -o quote.html quote.qmd
     
the output is as expected: 
![Bildschirmfoto 2022-06-30 um 23 34 00](https://user-images.githubusercontent.com/3169297/176782079-28ac38c4-6fbb-4a1f-b73f-f03c3f6aaa41.png)

However, when rendering the same document with quarto the `<cite>` tags seemed to be ignored and quote and author appear in one line. 

    quarto render quote.qmd
    
![Bildschirmfoto 2022-06-30 um 23 29 41](https://user-images.githubusercontent.com/3169297/176782141-2dc7da56-5a5e-4cab-9238-4c37b0e22b7f.png)

Interestingly when rendered to plain html (`format: html`) instead of reveal-js (`format: revealjs`) the problem does not occur
![Bildschirmfoto 2022-06-30 um 23 37 27](https://user-images.githubusercontent.com/3169297/176782541-153dff18-9d86-4bb9-9472-0a84b4fc99b7.png)

This happens with quarto 0.9.592 and pandoc 2.18 on Mac OS X 10.15.7 .

    

         

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
This is by design - our CSS is not expected to match pandoc's. 

Specifically, you're seeing the outcome of [this](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/revealjs/quarto.scss#L274-L278) rule.

If you want to change that, you can always set your CSS.

Specifically, if you want spacing in block quotes, use:

```css
.reveal blockquote p:first-child,
.reveal blockquote p:last-child {
  display: block;
}
```

**Comment by asmaier** [comment]
> This is by design - our CSS is not expected to match pandoc's.

Ok, I understand that. However I think Quarto should be consistent to itself. I tried to render the example above to html,  powerpoint and beamer pdf. And in all cases the authors name is moved to a new line as it is expected:

![Bildschirmfoto 2022-06-30 um 23 37 27](https://user-images.githubusercontent.com/3169297/176958492-733ad82e-7322-40d1-ad3c-9b675fe156db.png)
![Bildschirmfoto 2022-07-01 um 21 28 26](https://user-images.githubusercontent.com/3169297/176958497-93661787-8607-4542-ac67-fc6d7a1aa99f.png)
![Bildschirmfoto 2022-07-01 um 21 27 17](https://user-images.githubusercontent.com/3169297/176958498-3807352e-141a-4a1b-a923-552889a7e37f.png)

So the CSS of reveal-js is the exception to the rule. So I wonder what is the rational in converting block elements to inline elements within blockquotes in Quartos CSS for reveal-js in opposition to all other output fomats?

**Comment by cscheid** [comment]
That's a compelling argument to me. @jjallaire, what do you think?

**Comment by jjallaire** [comment]
Yes, compelling to me as well! Fixed here: https://github.com/quarto-dev/quarto-cli/commit/23662fcb72d2f2589281a438f7ef4862989085f5
