### ISSUE TITLE
Latex Package 'titlesec'

### ISSUE THREAD

**Issue by joelvonrotz** [quarto-dev/quarto-cli#1273]
### Bug description

Hi Quarto Devs

I've been loving using the tool so far, but have had some hiccups with the PDF generation.
I'm currently using it to write summaries for university and recently wanted to change the section, subsection, etc. -styles with the `titlesec` package. This doesn't seem to work directly with the following added packages.

```latex
\usepackage{multicol}
\usepackage[german]{babel}
\usepackage[utf8]{inputenc}
\usepackage{titlesec}
```

Which gave following output:

```
compilation failed- error
Argument of \paragraph has an extra }.
<inserted text>
                \par
l.1641 \ttl@extract\paragraph
```

I have googled the issue and found this stackoverflow discussion: https://stackoverflow.com/questions/42916124/not-able-to-use-titlesec-with-markdown-and-pandoc, which indicates that a pandoc configuration is required. I don't know how to do this and wanted to know if you could help out.

---

```
[>] Checking Quarto installation......OK
      Version: 0.9.637
      Path: C:\tools\Quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: C:/.../AppData/Local/Programs/Python/Python310/python.exe      
      Jupyter: 4.9.2
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
And Operating System
```
OS Name:	Microsoft Windows 10 Pro
Version:	10.0.19044 Build 19044
System Type:	x64-based PC
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by joelvonrotz** [comment]
Might not really be a bug, sorry

**Comment by cscheid** [comment]
This is not a quarto bug, but I agree that the pandoc documentation around it is not particularly helpful, and the stackoverflow posts are stale. Add this to your metadata:

```
block-headings: false
```

You'll still need to configure `titlesec` correctly, but this minimal example works for me:

```
---
block-headings: false
header-includes: |
    \usepackage{multicol}
    \usepackage[german]{babel}
    \usepackage[utf8]{inputenc}
    \usepackage{titlesec}
    \titleformat{\section}
        {\titlerule
            \vspace{.8ex}%
            \normalfont\itshape}
        {\thesection.}{.5em}{}
    \titleformat{\subsection}
        {\titlerule
            \vspace{.8ex}%
            \normalfont\itshape}
        {\thesection.}{.5em}{}
format: pdf
---


# Section

Hello.

## Subsection

Here.

## Another Subsection.

Also here.
```

**Comment by joelvonrotz** [comment]
Thank you very much for your response! It worked with your solution, thank you!
