### ISSUE TITLE
Fix single tilde (~) strikethrough parsing

### ISSUE THREAD

**Issue by jjyunnn** [quarto-dev/quarto-cli#1280]
### Bug description

Same problem with markdown(https://github.com/microsoft/vscode/issues/146610)

The bug of mrkdown was fixed by [babakks](https://github.com/babakks).

So I think the quarto would be fixed easily. Thanks.

Please refer to the following code.
(https://github.com/microsoft/vscode/pull/147239/commits/23b2e7b41ce9492978fc0079c377dff66942eb03)

### Checklist

- [ ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, self-contained, and reproducible example?
- [ ] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thanks! Fixed here: https://github.com/quarto-dev/quarto-vscode/commit/0b0b56826f6e43cf1122b0079ae8c3f25dc50ee6
