### ISSUE TITLE
Rendering pdf - File `scrartcl.cls' not found

### ISSUE THREAD

**Issue by ca-signorelli** [quarto-dev/quarto-cli#1281]
When rendering pdf from Quarto I get an error, and the following output in the pdf-log.

This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex 2022.7.3)  3 JUL 2022 21:31
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**write_pdf.tex
(./write_pdf.tex
LaTeX2e <2022-06-01> patch level 3
L3 programming layer <2022-06-16>

**! LaTeX Error: File `scrartcl.cls' not found.**

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.10 \usepackage
                {amsmath,amssymb}^^M

**Comment by cderv** [comment]
Can you share your Quarto version ? `quarto check` ? 

Also, can you share `quarto tools list` ? 

`scrartcl.cls` is part of [`koma-script` CTAN package](https://ctan.org/pkg/koma-script) so you could install it, but it should be installed automatically if missing when you are using Quarto with TeX Live (https://quarto.org/docs/output-formats/pdf-engine.html#quarto-pdf-engine). 

Sharing your OS environment info and also TeX Live installation info could help.

**Comment by ca-signorelli** [comment]
Hello,
Thank you for your swift reply. I reinstalled Quarto, and now the messages changed.
When I render a qmd file from RStudio I get the following message:

***@***.***


But the tinytex is already installed.


G:\>quarto install tool tinytex
tinytex is already installed and up to date.

G:\>quarto check

[>] Checking Quarto installation......OK
      Version: 0.9.640
      Path: C:\Program Files\Quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.1.3
      Path: C:/PROGRA~1/R/R-41~1.3
      LibPaths:
        - C:/Users/christiana/Documents/R/win-library/4.1
        - C:/Program Files/R/R-4.1.3/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK

G:\>quarto tools list
(|) Inspecting toolsDownload ***@***.***/directories.ts
(|) Inspecting toolsDownload ***@***.***/deps.ts
[>] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Up to date        v2022.05      v2022.05
WARNING: TeX Live not on path.

**Comment by cderv** [comment]
````
***@***.***
````

This above is the error message ? 

Can you format correctly the code / log part in the github issue so that it is readable ? 

> WARNING: TeX Live not on path.

You may need to restart your terminal session after installing TinyTeX so that `tlmgr` and tools is correctly on PATH.

**Comment by ca-signorelli** [comment]
Hei,
I tried to send a picture of the screen. I have attached it below, it should be visible in Preview.

![image](https://user-images.githubusercontent.com/67708893/177174000-5a85100d-c6ca-4f59-a408-9c1f801f45f7.png)

**Comment by cderv** [comment]
No TeX installation detected means that your installation of TinyTeX is somehow not found. 

`quarto tools list` give you TinyTeX correctly installed right ? 

After you install (`quarto install tool tinytex`), have you restarted your terminal window ? Your editor or other program like RStudio IDE ? Or even your computer ? 

The installation of TinyTeX needs to be put in PATH and, especially on Windows, the PATH env var update may require a restart.

**Comment by ca-signorelli** [comment]
Hello again,
I tried to shut everything down before restart, and now it works.
Thank you so much for your follow up and support.
Going through all the steps you recommended helped me out.

Best regards
Christian

**Comment by cderv** [comment]
Glad it is working now!

**Comment by alireza5969** [comment]
Hi, I have the same problem in the first issue.

`
==> quarto preview test.qmd --to pdf --no-watch-inputs --no-browse

pandoc 
  to: latex
  output-file: test.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: test
  

Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
finding package for scrartcl.cls
ERROR: 
compilation failed- no matching packages
LaTeX Error: File `scrartcl.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.10 ^^M
         

see test.log for more information.
`

Would you please help me?

**Comment by cderv** [comment]
@alireza5969 same things apply: See my question https://github.com/quarto-dev/quarto-cli/issues/1281#issuecomment-1173646681

When comment with a problem you need to help us help you. 

Also, this issue is from 2 years ago. Please open new ones instead of commenting on old one. A lot can have changed in 2 years. If you need help and not opening an issue with quarto, you can also consider opening a discussion : https://github.com/quarto-dev/quarto-cli/discussions

thanks

**Comment by drmowinckels** [comment]
I've been having issues wth pdf rendering on GitHub actions these last days, a workflow that has previously not had an issue. I'm struggling to see where the issue is, as error are somewhat changing between tests. But this error is one of them:

```
endering PDF
running lualatex - 1
  This is LuaHBTeX, Version 1.22.0 (TeX Live 2025) 
   restricted system commands enabled.
  
updating tlmgr

updating existing packages
finding package for scrartcl.cls
ERROR: 
compilation failed- no matching packages
LaTeX Error: File `scrartcl.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)
``

https://github.com/drmowinckels/drmowinckels.github.io/actions/runs/20552986209/job/59033254341

**Comment by mcanouil** [comment]
@drmowinckels Could you open a [Q&A discussion](https://github.com/orgs/quarto-dev/discussions/new?category=q-a) with all context information? You can reference this issue in it if appropriate.

Note that the issue might be intermittent as the resource needs to be downloaded but host might not be reachable at the time.
