### ISSUE TITLE
support knitr::include_graphics in inline r code

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1285]
### Bug description

This currently does not work and yields an obscure error message:

```
Quitting from lines 614-656 (man.Rmd) 
Error in `if (options$fig.show == "hide") ...`:
! argument is of length zero
```

Note that this _does_ work in R Markdown so is something we should definitely support.

cc @hadley

### Checklist

- [ ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, self-contained, and reproducible example?
- [ ] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/f82c0726bfe756120956e066acb52bfe7e97718d

**Comment by hadley** [comment]
Thanks!
