### ISSUE TITLE
Built-in tabbed code blocks

### ISSUE THREAD

**Issue by AshleyHenry15** [quarto-dev/quarto-cli#1287]
Request to have built-in tabbed code blocks as well as terminal/file blocks with the ability to add a title:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/31460023/177347630-3b351a02-83bc-4f4e-ad2a-1a6a2656611d.png">

<img width="608" alt="image" src="https://user-images.githubusercontent.com/31460023/177347657-d97aaf05-d6f4-4459-9369-3c18bc86c1e3.png">

MkDocs - Material examples:

Tabs example:
```
   === "RHEL 8"
        ```
        $ curl -O https://cdn.rstudio.com/connect/{{ vars.connect.rsc.short_version }}/rstudio-connect-{{ vars.connect.rsc.full_version }}.el8.x86_64.rpm
        $ sudo yum install rstudio-connect-{{ vars.connect.rsc.full_version }}.el8.x86_64.rpm
        ```

    === "RHEL/CentOS 7"
        ```
        $ curl -O https://cdn.rstudio.com/connect/{{ vars.connect.rsc.short_version }}/rstudio-connect-{{ vars.connect.rsc.full_version }}.el7.x86_64.rpm
        $ sudo yum install rstudio-connect-{{ vars.connect.rsc.full_version }}.el7.x86_64.rpm
        ```
    
    === "Amazon Linux 2"
        ```
        $ curl -O https://cdn.rstudio.com/connect/{{ vars.connect.rsc.short_version }}/rstudio-connect-{{ vars.connect.rsc.full_version }}.amazonlinux2.x86_64.rpm
        $ sudo yum install rstudio-connect-{{ vars.connect.rsc.full_version }}.amazonlinux2.x86_64.rpm
        ```

    === "Ubuntu 22.04"
        ```
        $ sudo apt-get install gdebi-core
        $ curl -O https://cdn.rstudio.com/connect/{{ vars.connect.rsc.short_version }}/rstudio-connect_{{ vars.connect.rsc.full_version }}~ubuntu22_amd64.deb
        $ sudo gdebi rstudio-connect_{{ vars.connect.rsc.full_version }}~ubuntu22_amd64.deb
        ```

    === "Ubuntu 20.04"
        ```
        $ sudo apt-get install gdebi-core
        $ curl -O https://cdn.rstudio.com/connect/{{ vars.connect.rsc.short_version }}/rstudio-connect_{{ vars.connect.rsc.full_version }}~ubuntu20_amd64.deb
        $ sudo gdebi rstudio-connect_{{ vars.connect.rsc.full_version }}~ubuntu20_amd64.deb
        ```

Code/file block with title example:
```
    ``` bash title="Terminal"
    sudo systemctl stop rstudio-pm
    sudo systemctl start rstudio-pm
    ```
```

**Comment by jjallaire** [comment]
Thanks! We are going to implement extensions for both of these features this week (we'll ultimately add both behaviors as core features but we are at code freeze for v1.0 so for now they will be extensions)

**Comment by cscheid** [comment]
We now have these in https://github.com/quarto-ext/code-filename and https://github.com/quarto-ext/grouped-tabsets. I'm going to close the issue, but let us know if they don't work for your use case and we'll reopen them!

**Comment by jjallaire** [comment]
Going to re-open as I think I'd like to make these extensions built-in features in v1.1

**Comment by jjallaire** [comment]
There are now indeed built-in features for v1.1 (the extensions will still work for v1.0)
