### ISSUE TITLE
netlify's asset optimization pipeline interacts badly with quarto's

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#1290]
### Bug description

[This repository](https://github.com/hadley/r-pkgs/pull/819) builds incorrectly on Netlify's deployment when their asset optimization pipeline is turned on.

There's probably an interaction between our own optimization and minification and Netlify's.

We should at least add a warning in our netlify deploy docs.

This was run on v0.9.640 which GHA CI.

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
For `quarto publish` could we add a netlify.toml file that forces this off?

**Comment by cscheid** [comment]
That sounds like a plan. Given [their documentation](https://docs.netlify.com/configure-builds/file-based-configuration/#post-processing), my guess is that we need this:

```toml
[build.processing.css]
  bundle = false
  minify = false
```

**Comment by jjallaire** [comment]
We should confirm that the this successfully overrides settings in their web based UI. We won't implement this now but let's do it soon after we open `main` back up post v1.0

**Comment by jjallaire** [comment]
Resolved with: https://github.com/quarto-dev/quarto-cli/commit/1150f62c7c69ce132929702e0c533c85f2574360
