### ISSUE TITLE
change version number to v1.0

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1300]

**Comment by eitsupi** [comment]
I am wondering if you do not use pre-release status. (`v1.0.3` and `v1.0.3` were not pre-release)
Frequent version upgrades will not seem stable.

**Comment by jjallaire** [comment]
Every build after 1.0.0. is a "candidate" build for the final v1.0 release (i.e. we think we may have no more bugs to fix). In practice we are finding ~ 1 bug a day to fix (any bug has to be either very low risk or highly critical)  but will soon even close those off. So those are indeed stable releases (and that will receive progressively less patching over time).

**Comment by eitsupi** [comment]
In general, wouldn't a candidate build be pre-release and then switched to release later if there were no problems?
I think it would be difficult to track Quarto versions from other systems if frequent releases are made.

**Comment by jjallaire** [comment]
During initial development we didn't make a Pre-Release vs. Release distinction (just about everything is "Release" and we shipped a few times a day). However, as soon as we create the v1.0 branch (in a few days) we'll start making this distinction and "Release" will always mean the latest validated / stable release and Pre-Release a daily build. 

Net: we aren't currently using the scheme you suggest but will be very, very soon!
