### ISSUE TITLE
Failure to convert equations 

### ISSUE THREAD

**Issue by msh855** [quarto-dev/quarto-cli#1303]
### Bug description

When the notebook has latex equations inside a Markdown cell in Jupyter Lab equations do not appear in the HTML converted by quarto. 

Here is what I get in the html 

![image](https://user-images.githubusercontent.com/26636184/177622105-01ecb3a0-c1a6-492a-959b-7cf986ba792c.png)

and here is the relevant code: 

There are various versions of this equation, depending on the application. For the point I want to make here, a conventional approach more than suffices. In this case, and in order to link inflation, interest rates, consumption and income and substitution effects, I would assume that in the aggregate the path of consumption follows the following rule (See [here](https://core.ac.uk/download/pdf/6377146.pdf) or [here](https://www.thijsvanrens.com/macro/SE_IE_note.pdf) for a simple example)

$$
E_{t} \Delta \overline{ c_{t+1}}=\sigma \widehat{r_{t}}
$$

where 

$$
\Delta \overline{ c_{t+1}} = \log(c_{t+1}) - \log(c_{t}) \quad ( \text{real consumption growth}) 
$$

$$
\widehat{r_{t}} = \log(r_{t}) - \log(r^*) 
$$

$$
\text{and} \quad r_{t} = i_{t} - \pi_{t+1} \quad ( \text{real risk-free/fund rate with } r^* \equiv \text{long-run values})
$$

```

**Comment by cscheid** [comment]
Can you share the raw markdown you're using in those cells? I see you're using square brackets for the equation notations, but I can't make that work in my version of `jupyter notebook`:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/285675/177637378-10831a49-9b76-45fa-97e0-8b291463a220.png">
<img width="371" alt="image" src="https://user-images.githubusercontent.com/285675/177637421-fdcdf2ce-5048-462e-a3ee-79c8d995a717.png">

The [jupyter book](https://jupyterbook.org/en/stable/content/math.html) appears to suggest using `$$` instead, and that works for me, as well as renders ok with quarto:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/285675/177637563-bb0bb854-c9e3-4f17-837b-cb03baf884a7.png">
<img width="750" alt="image" src="https://user-images.githubusercontent.com/285675/177637600-b5b13f4d-3c6b-470b-b534-8f8d28fae7e7.png">
<img width="657" alt="image" src="https://user-images.githubusercontent.com/285675/177637837-ef552a14-47de-4add-a441-cf96a73a6715.png">

**Comment by jjallaire** [comment]
Yes, we use `$$` as the delimiter and specifically do not allow the `\[` syntax (this isn't part of standard Pandoc markdown). You might be able to get this to work by adding:

---
from: markdown+tex_math_single_backslash
---

To your document options (as per https://pandoc.org/MANUAL.html#extension-tex_math_single_backslash)
