### ISSUE TITLE
emacs polymode?

### ISSUE THREAD

**Issue by bbolker** [quarto-dev/quarto-cli#131]
Curious if there is likely to be some support/documentation for emacs [polymode](https://polymode.github.io/) at some point? (That's my current workflow for Rmarkdown files: see also [here](https://www.thetopsites.net/article/59750668.shtml) Or maybe it already works with the right definitions ... ?  (I am *not* an Emacs guru, so I would be cargo-culting my way through trying to make it work ...)

**Comment by jjallaire** [comment]
We now have a Quarto-mode available for Emacs (it integrates w/ polymode and ESS and provides integrated support for Quarto preview): https://github.com/quarto-dev/quarto-emacs
