### ISSUE TITLE
issue with updating tlmgr  updating existing packages

### ISSUE THREAD

**Issue by HomeStayMom** [quarto-dev/quarto-cli#1312]
Hi I have an issue rendering the .qmd pdf. 
Sessioninfo is attached as well as showing you , that there is no way i can update the tlmgr manager

Hi, Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Username> tlmgr update --all
tlmgr.pl: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
tlmgr.pl: no updates available
PS C:\Users\Username>

**Comment by HomeStayMom** [comment]
the render to html works without an issue. I have not yet tried the docx

**Comment by HomeStayMom** [comment]
The error msg is : updating tlmgr starts the process and stay there....

**Comment by dragonstyle** [comment]
Updating the `tlmgr` can take a few minutes, especially the first time. Have you let it run for a few minutes?

**Comment by HomeStayMom** [comment]
sure thing. How? The system, does nota allows to attach .qmd
 _____________

**Comment by dragonstyle** [comment]
Could you try rendering from outside of RStudio (e.g. from Powershell, go to the directory which contains the `qmd` file and try `quarto render <my-file.qmd> --to pdf`) and see whether that shows the same behavior?

**Comment by HomeStayMom** [comment]
see G:\reproducible reporting\Test data cleaning\Test-data-cleaning2.log for more information.
[Test-data-cleaning2.log](https://github.com/quarto-dev/quarto-cli/files/9065106/Test-data-cleaning2.log)

**Comment by HomeStayMom** [comment]
Hi, good evening. I will try your proposal and let you know. compilation failed- error
LaTeX3 Error: Mismatched LaTeX support files detected.
(LaTeX3)        Loading 'expl3.sty' aborted!
(LaTeX3)
(LaTeX3)        The L3 programming layer in the LaTeX format
(LaTeX3)        is dated 2022-06-16, but in your TeX tree the files require
(LaTeX3)        at least 2022-07-04.

**Comment by HomeStayMom** [comment]
good morning, [ Or evening. So I did the reinstall and I still have the same exact issue. I checked as per stack exchange I must have the problem rooting somewhere else.

**Comment by HomeStayMom** [comment]
Good morning, So I installed MKtex and tried to render the pdf. The error I got compilation failed- package installation error
LaTeX Error: File `tabu.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.127 \usepackage
                 {threeparttable}^^M 

see G:\reproducible reporting\Test data cleaning\Test-data-cleaning2.log for more information.

And here I get a bit of concerned:
https://ctan.org/tex-archive/macros/latex/contrib/tabu?lang=en

The original author of tabu appears out of contact, and tabu had not been updated for several years, finally becoming unusable in 2019 as updates to other packages mean some of its patched code did not work as intended. 
Quarto shouldn't be able to run only having TinyTex installed????

**Comment by mcanouil** [comment]
Hi,

which version of PowerShell are you using exactly?
5.1 is the version included in Windows OS.
The latest is 7.2: https://github.com/PowerShell/PowerShell

**Comment by HomeStayMom** [comment]
Hi, As already commented on Github,
I installed MkTex. Then following some SO advise
1. Check for latexextra
tlmgr show collection-latexextra
package:     collection-latexextra
category:    Collection
shortdesc:   LaTeX additional packages
longdesc:    A very large collection of add-on packages for LaTeX.
installed:   No
sizes:       930033k
relocatable: Yes
2. Try to install  - no luck

 tlmgr --reinstall latexextra
tlmgr.pl: unknown action: latexextra; try --help if you need it.
PS C:\Users\Tsaras> tlmgr -- install latexextra
tlmgr.pl: package repository
https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
tlmgr.pl install: package latexextra not present in repository.
tlmgr.pl: action install returned an error; continuing.
tlmgr.pl: An error has occurred. See above messages. Exiting.

3. Check colection


tlmgr show collection
tlmgr.pl: cannot find package collection, searching for other matches:

Packages containing `collection' in their title/description:
adobemapping - Adobe cmap and pdfmapping files
adrconv - BibTeX styles to implement an address database
akktex - A collection of packages and classes
allrunes - Fonts and LaTeX package for almost all runes
amscls-doc - User documentation for AMS document classes
amstex - American Mathematical Society plain TeX macros
archaic - A collection of archaic fonts
automata - Finite state machines, graphs and trees in MetaPost
avantgar - URW 'Base 35' font pack for LaTeX
baskervald - Baskervald ADF fonts collection with TeX/LaTeX support
beamerauxtheme - Supplementary outer and inner themes for beamer
beamertheme-npbt - A collection of LaTeX beamer themes
beebe - A collection of bibliographies
berenisadf - Berenis ADF fonts and TeX/LaTeX support
bibhtml - BibTeX support for HTML files
biblatex-archaeology - A collection of BibLaTeX styles for German prehistory
biblatex-bookinarticle - Manage book edited in article
biblatex-dw - Humanities styles for BibLaTeX
biblatex-fiwi - BibLaTeX styles for use in German humanities
biblatex-luh-ipw - BibLaTeX styles for social sciences
biblatex-morenames - New names for standard BibLaTeX entry type
bookhands - A collection of book-hand fonts
bookman - URW 'Base 35' font pack for LaTeX
booktabs-fr - French translation of booktabs documentation
bosisio - A collection of packages by Francesco Bosisio
bxjscls - Japanese document class collection for all major engines
carlisle - David Carlisle's small packages
carolmin-ps - Adobe Type 1 format of Carolingian Minuscule fonts
cbfonts-fd - LaTeX font description files for the CB Greek fonts
chembst - A collection of BibTeX files for chemistry journals
chemmacros - A collection of macros to support typesetting chemistry
documents
cmbright - Computer Modern Bright fonts
cmextra - Knuth's local information
cochineal - Cochineal fonts with LaTeX support
collection-basic - Essential programs and files
collection-bibtexextra - BibTeX additional styles
collection-binextra - TeX auxiliary programs
collection-context - ConTeXt and packages
collection-fontsextra - Additional fonts
collection-fontsrecommended - Recommended fonts
collection-fontutils - Graphics and font utilities
collection-formatsextra - Additional formats
collection-games - Games typesetting
collection-humanities - Humanities packages
collection-langarabic - Arabic
collection-langchinese - Chinese
collection-langcjk - Chinese/Japanese/Korean (base)
collection-langcyrillic - Cyrillic
collection-langczechslovak - Czech/Slovak
collection-langenglish - US and UK English
collection-langeuropean - Other European languages
collection-langfrench - French
collection-langgerman - German
collection-langgreek - Greek
collection-langitalian - Italian
collection-langjapanese - Japanese
collection-langkorean - Korean
collection-langother - Other languages
collection-langpolish - Polish
collection-langportuguese - Portuguese
collection-langspanish - Spanish
collection-latex - LaTeX fundamental packages
collection-latexextra - LaTeX additional packages
collection-latexrecommended - LaTeX recommended packages
collection-luatex - LuaTeX packages
collection-mathscience - Mathematics, natural sciences, computer science
packages
collection-metapost - MetaPost and Metafont packages
collection-music - Music packages
collection-pictures - Graphics, pictures, diagrams
collection-plaingeneric - Plain (La)TeX packages
collection-pstricks - PSTricks
collection-publishers - Publisher styles, theses, etc.
collection-texworks - TeXworks editor; TL includes only the Windows binary
collection-wintools - Windows-only support programs
collection-xetex - XeTeX and packages
colorprofiles - Collection of free ICC profiles
confproc - A set of tools for generating conference proceedings
context-typescripts - Small modules to load various fonts for use in ConTeXt
courier - URW 'Base 35' font pack for LaTeX
ctex - LaTeX classes and packages for Chinese typesetting
doctools - Tools for the documentation of LaTeX code
dtxgallery - A small collection of minimal DTX examples
dvipsconfig - Collection of dvips PostScript headers
easing - easing functions for pgfmath
easy - A collection of easy-to-use macros
eijkhout - Victor Eijkhout's packages
ektype-tanka - Devanagari fonts by EkType
electrum - Electrum ADF fonts collection
eskdx - Modern Russian typesetting
ethiop - LaTeX macros and fonts for typesetting Amharic
fontools - Tools to simplify using fonts (especially TT/OTF ones)
fonts-tlwg - Thai fonts for LaTeX from TLWG
footmisc - A range of footnote options
footmisx - A range of footnote options
fp - Fixed point arithmetic
fragments - Fragments of LaTeX code
frankenstein - A collection of LaTeX packages
gothic - A collection of old German-style fonts
graphics - The LaTeX standard graphics bundle
hagenberg-thesis - A Collection of LaTeX classes, style files, and example
documents for academic manuscripts
helvetic - URW 'Base 35' font pack for LaTeX
hepunits - A set of units useful in high energy physics applications
histogr - Draw histograms with the LaTeX picture environment
hologo - A collection of logos with bookmark support
hyph-utf8 - Hyphenation patterns expressed in UTF-8
ifsym - A collection of symbols
imtekda - IMTEK thesis class
jknapltx - Miscellaneous packages by Joerg Knappen
js-misc - Miscellaneous macros from Joachim Schrod
juramisc - Typesetting German juridical documents
knuth-hint - HINT collection of typeset C/WEB sources in TeX Live
knuth-lib - Core TeX and Metafont sources from Knuth
knuth-local - Knuth's local information
knuth-pdf - PDF collection of typeset C/WEB sources in TeX Live
komacv-rg - LaTeX packages that aid in creating CVs based on the komacv
class and creating related documents
ksfh_nat - BibTeX style for KSFH Munich
ktv-texdata - Extract subsets of documents
l2picfaq - LaTeX pictures "how-to" (German)
l3experimental - Experimental LaTeX3 concepts
l3packages - High-level LaTeX3 concepts
latex-fonts - A collection of fonts used in LaTeX distributions
latex-graphics-dev - Development pre-release of the LaTeX graphics bundle
latex-tools-dev - Development pre-release of the LaTeX tools bundle
lexend - The Lexend fonts for XeLaTeX and LuaLaTeX through fontspec
lhcyr - A non-standard Cyrillic input scheme
lhelp - Miscellaneous helper packages
lstaddons - Add-on packages for listings: autogobble and line background
ltxmisc - Miscellaneous LaTeX packages, etc
ltxtools - A collection of LaTeX API macros
lua-uni-algos - Unicode algorithms for LuaTeX
lualibs - Additional Lua functions for LuaTeX macro programmers
mdwtools - Miscellaneous tools by Mark Wooding
mfware - Supporting tools for use with Metafont
miniplot - A package for easy figure arrangement
minutes - Typeset the minutes of meetings
modes - A collection of Metafont mode_def's
moreverb - Extended verbatim
ms - Various LaTeX packages by Martin Schroder
nanicolle - Typesetting herbarium specimen labels
ncctools - A collection of general packages for LaTeX
nchairx - Maths macros from chair X of Wurzburg University
ncntrsbk - URW 'Base 35' font pack for LaTeX
oberdiek - A bundle of packages submitted by Heiko Oberdiek
ofs - Macros for managing large font collections
olsak-misc - Collection of plain TeX macros written by Petr Olsak
palatino - URW 'Base 35' font pack for LaTeX
pas-cv - Flexible typesetting of Curricula Vitae
physunits - Macros for commonly used physical units
piff - Macro tools by Mike Piff
platex-tools - pLaTeX standard tools bundle
poltawski - Antykwa Poltawskiego Family of Fonts
preprint - A bundle of packages provided "as is"
present - Presentations with Plain TeX
projlib - A series of tools to simplify your workflow
pst-optexp - Drawing optical experimental setups
pst-sigsys - Support of signal processing-related disciplines
pstricks - PostScript macros for TeX
pstricks-add - A collection of add-ons and bugfixes for PSTricks
pxtxalfa - Virtual maths alphabets based on pxfonts and txfonts
qualitype - The QualiType font collection
ran_toks - Randomise token strings
randomlist - Deal with database, loop, and random in order to build
personalized exercises
roex - Metafont-PostScript conversions
rubik - Document Rubik cube configurations and rotation sequences
ruhyphen - Russian hyphenation
sauerj - A bundle of utilities by Jonathan Sauer
sauterfonts - Use Sauter's fonts in LaTeX
scheme-basic - basic scheme (plain and latex)
scheme-medium - medium scheme (small + more packages and languages)
scheme-minimal - minimal scheme (plain only)
sciposter - Make posters of ISO A3 size and larger
seetexk - Utilities for manipulating DVI files
semtex - Deals with stripped SemanTeX documents
serbian-apostrophe - Commands for Serbian words with apostrophes
shipunov - A collection of LaTeX packages and classes
stex - An Infrastructure for Semantic Preloading of LaTeX Documents
stix2-otf - OpenType Unicode text and maths fonts
stix2-type1 - Type1 versions of the STIX Two OpenType fonts
structmech - A TikZ command set for structural mechanics drawings
sttools - Various macros
symbol - URW 'Base 35' font pack for LaTeX
t1utils - Simple Type 1 font manipulation programs
tdsfrmath - Macros for French teachers of mathematics
templatetools - Commands useful in LaTeX templates
tex-gyre - TeX Fonts extending freely available URW fonts
tex-gyre-math - Maths fonts to match tex-gyre text fonts
tex-ini-files - Model TeX format creation files
thermodynamics - Macros for multicomponent thermodynamics documents
tikz-ladder - Draw ladder diagrams using TikZ
tikz-lake-fig - Schematic diagrams of lakes
tikz-relay - TikZ library for typesetting electrical diagrams
tikz-sfc - Symbols collection for typesetting Sequential Function Chart
(SFC) diagrams (PLC programs)
tikzlings - A collection of cute little animals and similar creatures
times - URW 'Base 35' font pack for LaTeX
tkz-berge - Macros for drawing graphs of graph theory
tocdata - Adds names to chapters, sections, figures in the TOC and LOF
tools - The LaTeX standard tools bundle
turnstile - Typeset the (logic) turnstile notation
twemoji-colr - Twemoji font in COLR/CPAL layered format
urwchancal - Use URW's clone of Zapf Chancery as a maths alphabet
venturisadf - Venturis ADF fonts collection
wallpaper - Easy addition of wallpapers (background images) to LaTeX
documents, including tiling
was - A collection of small packages by Walter Schmidt
xbmks - Create a cross-document bookmark tree
zapfchan - URW 'Base 35' font pack for LaTeX
zapfding - URW 'Base 35' font pack for LaTeX
zebra-goodies - A collection of handy macros for paper writing

 I did a quick search and here are my collections...

Packages containing files matching `collection':
00texlive.image:
        tlpkg/doc/articles/cstug08/gui-collections.png
        tlpkg/doc/articles/cstug08/texcollection2008-large.png
        tlpkg/doc/articles/guit08/gui-collections.png
        tlpkg/tlpsrc/collection-basic.tlpsrc
        tlpkg/tlpsrc/collection-bibtexextra.tlpsrc
        tlpkg/tlpsrc/collection-binextra.tlpsrc
        tlpkg/tlpsrc/collection-context.tlpsrc
        tlpkg/tlpsrc/collection-fontsextra.tlpsrc
        tlpkg/tlpsrc/collection-fontsrecommended.tlpsrc
        tlpkg/tlpsrc/collection-fontutils.tlpsrc
        tlpkg/tlpsrc/collection-formatsextra.tlpsrc
        tlpkg/tlpsrc/collection-games.tlpsrc
        tlpkg/tlpsrc/collection-humanities.tlpsrc
        tlpkg/tlpsrc/collection-langarabic.tlpsrc
        tlpkg/tlpsrc/collection-langchinese.tlpsrc
        tlpkg/tlpsrc/collection-langcjk.tlpsrc
        tlpkg/tlpsrc/collection-langcyrillic.tlpsrc
        tlpkg/tlpsrc/collection-langczechslovak.tlpsrc
        tlpkg/tlpsrc/collection-langenglish.tlpsrc
        tlpkg/tlpsrc/collection-langeuropean.tlpsrc
        tlpkg/tlpsrc/collection-langfrench.tlpsrc
        tlpkg/tlpsrc/collection-langgerman.tlpsrc
        tlpkg/tlpsrc/collection-langgreek.tlpsrc
        tlpkg/tlpsrc/collection-langitalian.tlpsrc
        tlpkg/tlpsrc/collection-langjapanese.tlpsrc
        tlpkg/tlpsrc/collection-langkorean.tlpsrc
        tlpkg/tlpsrc/collection-langother.tlpsrc
        tlpkg/tlpsrc/collection-langpolish.tlpsrc
        tlpkg/tlpsrc/collection-langportuguese.tlpsrc
        tlpkg/tlpsrc/collection-langspanish.tlpsrc
        tlpkg/tlpsrc/collection-latex.tlpsrc
        tlpkg/tlpsrc/collection-latexextra.tlpsrc
        tlpkg/tlpsrc/collection-latexrecommended.tlpsrc
        tlpkg/tlpsrc/collection-luatex.tlpsrc
        tlpkg/tlpsrc/collection-mathscience.tlpsrc
        tlpkg/tlpsrc/collection-metapost.tlpsrc
        tlpkg/tlpsrc/collection-music.tlpsrc
        tlpkg/tlpsrc/collection-pictures.tlpsrc
        tlpkg/tlpsrc/collection-plaingeneric.tlpsrc
        tlpkg/tlpsrc/collection-pstricks.tlpsrc
        tlpkg/tlpsrc/collection-publishers.tlpsrc
        tlpkg/tlpsrc/collection-texworks.tlpsrc
        tlpkg/tlpsrc/collection-wintools.tlpsrc
        tlpkg/tlpsrc/collection-xetex.tlpsrc
biblatex-bookinarticle:

texmf-dist/doc/latex/biblatex-bookinarticle/documentation/example-bookinincollection.bib
biblatex-bookinother:

texmf-dist/doc/latex/biblatex-bookinother/documentation/example-bookincollection.bib

texmf-dist/doc/latex/biblatex-bookinother/documentation/example-bookincollection.dot

texmf-dist/doc/latex/biblatex-bookinother/documentation/example-bookincollection.pdf

texmf-dist/doc/latex/biblatex-bookinother/documentation/example-bookinincollection.bib

texmf-dist/doc/latex/biblatex-bookinother/documentation/example-bookinincollection.dot

texmf-dist/doc/latex/biblatex-bookinother/documentation/example-bookinincollection.pdf
embedfile:
        texmf-dist/doc/latex/embedfile/embedfile-example-collection.tex
exsol:
        texmf-dist/doc/latex/exsol/example-formulacollection.pdf
hyph-utf8:
        texmf-dist/doc/generic/hyph-utf8/img/texlive-collection.png
moderncv:
        texmf-dist/tex/latex/moderncv/moderncvcollection.sty
nwejm:
        texmf-dist/tex/latex/nwejm/images/nwejm-logos-collection.pdf
        texmf-dist/tex/latex/nwejm/images/nwejm-logos-collection.tex
skb:
        texmf-dist/doc/latex/skb/user-guide/database/bibtex/collection.bib
        texmf-dist/doc/latex/skb/user-guide/database/bibtex/incollection.bib
texlive-sr:

texmf-dist/doc/texlive/texlive-sr/images/tl2019-install-tl-collections-sr.png
tlcockpit:

texmf-dist/doc/support/tlcockpit/screenshots/tlcockpit-collections.jpg
tlmgr-intro-zh-cn:

texmf-dist/doc/support/tlmgr-intro-zh-cn/body/schemes_and_collections.tex
        texmf-dist/doc/support/tlmgr-intro-zh-cn/fig/collection.png
xsim:
        texmf-dist/doc/latex/xsim/examples/xsim.collections.pdf
        texmf-dist/doc/latex/xsim/examples/xsim.collections.tex

**Comment by HomeStayMom** [comment]
Windows Terminal
Version: 1.13.11431.0


Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

I will update to recommended one

**Comment by HomeStayMom** [comment]
For clarification : the PVS 5.1 Is part of the OS  and your are
recommending me  to have them both installed ?

**Comment by HomeStayMom** [comment]
as recomended I updatedt to PVS 7.2.5. Re-run the PowerShell 7.2.5
i re-run the tlmgr update -- all command .

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\Tsaras> tlmgr update --all
tlmgr.pl: package repository
https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
tlmgr.pl: no updates available
PS C:\Users\Tsaras>

**Comment by HomeStayMom** [comment]
PS C:\Users\User> tlmgr install latexextra
tlmgr.pl: package repository
https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
tlmgr.pl install: package latexextra not present in repository.
tlmgr.pl: action install returned an error; continuing.
tlmgr.pl: An error has occurred. See above messages. Exiting.
PS C:\Users\User>

**Comment by mcanouil** [comment]
> For clarification : the PVS 5.1 Is part of the OS and your are recommending me to have them both installed ?

Microsoft does.
I thought you were not using PowerShell 5.1 (the Windows integrated version).

The issue you are having is independent of Quarto and I think is some kind of conflicts.

1. Are you sure you have only one LaTeX distribution, i.e., not MiKTex and Tex Live at the same time?
2. You should consider removing any LaTex distribution you have installed (including TinyTex) and reinstalling one of them (I recommend TinyTex since well integrated with Quarto).
  Do not forget to restart your computer/laptop after installation to ensure search path is properly updated.
    - TinyTex: https://quarto.org/docs/output-formats/pdf-engine.html#installing-tex
      > To install TinyTeX, use the following command:
      > 
      > ```
      > quarto tools install tinytex
      > ```
      > 
      > If you prefer TeX Live, you can find instructions for installing it here: https://tug.org/texlive/.
      > 
      > Note that Quarto’s automatic installation of missing TeX packages will work for TinyTeX and TeX Live, but not for other TeX distributions (as it relies on TeX Live’s [tlmgr](https://www.tug.org/texlive/tlmgr.html) command).
    - Tex Live: https://tug.org/texlive/windows.html
    - MiKTex: https://miktex.org/download

---

PS: try to write/edit your messages using the styling options such as code blocks

````
```powershell
Hi, Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Username> tlmgr update --all
tlmgr.pl: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
tlmgr.pl: no updates available
PS C:\Users\Username>
```
````

Which produces:

```powershell
Hi, Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Username> tlmgr update --all
tlmgr.pl: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
tlmgr.pl: no updates available
PS C:\Users\Username>
```

**Comment by HomeStayMom** [comment]
SO Good afternoon,
The initial stage was : I had no other text editor than TinyTex in my Pc.
Tinytext was installed with RMarkdown. Quarto could not update TinyTex for
some reason.
Quatro utilizes some packages  that were missing from the TinyTex install
(tabu) . After I installed MiKTEX incorrectly,  having the hope that the
issue would be solved,Quarto was still running issues. An obsolete
package ( tabu) was required....
Decided to remove ALL Tex Editors aka inclusive TinyTex not from RStudio
but with PVS decided to render the .qmd . Finally this  took care of the
missing packages issues and I didnt have to do anything manually.
For anyone in the future wishing to explore Quarto and experience  similar
issues: 1. Remove All Tex editors from your system using the terminal.
Inclusive TinyTex installed with RMarkdown.2 start the rendering and allow
Quarto to take care of the rest. If no success, repeat the process a good
10-12 times, always restarting your OP  and eventually it will happen.
To my surprise, in my case Quarto uses xelatex as a pdf engine. I do not
mind until work.

**Comment by HomeStayMom** [comment]
Dear Qoarto Devs, thank you for your help. The issue was solved as advised shared above.

**Comment by HomeStayMom** [comment]
Thank you for your style advice. I am still challenged to solve the issue.
In the meantime I went a bit upset and  I just wish share with you

Requirement for robust SW / Package development

1.       Do not assume anything given –

1.1.    By chance you wish to target new users the VS community or just
some very new ones who wish to explore Quarto, do not assume they will have
Any Package installed on their PC

2.       Create detailed step-by-step instructions  about package
installation or as in 1.1 do not assume  the user has any prev versions of
Latex, Miktex or tabu file on its system. For this issue consider creating
comprehensive document with a curated  source link

3.       Do not build a new app requiring a  package where the package is
not being actively maintained

3.1.    Also ensure the install file will not bump in Windows defender
conflict…

4.       I was excited to try out the Quarto as an alternative to RMarkdown
and I think has a great potential BUT pls, consider the above mentioned
challenges and try to address them

4.1.    I am aware of the AGILE SW process, and I am sure the above
mentioned challenges could not be addressed earlier as they didn’t happen
before...

5.       Advising me to use PVS 7.2.5 was a great idea BUT didn’t solve the
Problem….

6.       I am still trying to solve the issue and hopefully it will work
out… if not I will be back…

7.       Again, Quarto has some great potential and I am sure will live

**Comment by mcanouil** [comment]
From what I know, Quarto team is aware that the infrastructure for Windows is not perfect and are working on it to avoid users facing issues.
Regarding issues with LaTeX, in the pre-release version changelog, we can see there are some improvements which should help avoiding conflicts:
> `quarto install tinytex` will now install TinyTex even if a system installation of TeX is detected.
> `quarto install tinytex` will no longer add TinyTex to the system path by default.

> 2.       Create detailed step-by-step instructions  about package
installation or as in 1.1 do not assume  the user has any prev versions of
Latex, Miktex or tabu file on its system. For this issue consider creating
comprehensive document with a curated  source link

Does the following not detailed enough? <https://quarto.org/docs/output-formats/pdf-engine.html#installing-tex>

> 3.1.    Also ensure the install file will not bump in Windows defender
conflict…

Default configuration? Could you report the exact issue to help the dev team?  
For example, I am facing some issues with F-Secure with a highly aggressive protection which block Quarto install on my pro laptop on Windows 10. In this case, I know that Quarto team cannot do anything.

PS: I am only a Quarto user and not affiliated with Quarto/RStudio.

**Comment by HomeStayMom** [comment]
Thank you for the follow up. In the meantime I sorted the issue…. But thanks again.

**Comment by 2catycm** [comment]
> I enter the same issue: running xelatex - 1 This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex) restricted \write18 enabled. entering extended mode
> 
> updating tlmgr
> 
> updating existing packages

I got this issue too!

**Comment by HomeStayMom** [comment]
Hi and wishing you a good day. Back in time i did the following:
1. Remove All Tex editors from your system using the* terminal.* Inclusive
TinyTex installed with RMarkdown.
2 start the rendering and allow Quarto to take care of the rest. If no
success, repeat the process a good 10-12 times, always restarting your OP
and eventually it will happen. Hope this helps.
