### ISSUE TITLE
transfer quarto-web issues to quarto-cli

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1315]

**Comment by eitsupi** [comment]
Since this is confusing for users, why not move all closed issues to this repository as well and disable the issue trucker of the quarto-web repository?

**Comment by dragonstyle** [comment]
- I would agree with this, though I couldn't find a way to bulk transfer issues and don't love the idea of clicking through all 68 back issues to transfer.

- I will ultimately disable the issues for this repo, but currently quarto-web directs users here to report content issues. Once that is cleaned up, I can take care of this.

**Comment by cderv** [comment]
@dragonstyle we could probably pro grammatically transfer issues if you want. `gh` cli can transfer issue (https://cli.github.com/manual/gh_issue_transfer) and so with retrieving all the number and iterating that would do the trick. 

Not sure closed issue are important to transfer though... 

I understand you may want to do that to close issue board, but we could also add a template for github issue to ask to open issue in other repo if that concerns not the website content but the CLI tool. 

Happy to help if this is needed.

**Comment by mcanouil** [comment]
This is actually resolved as issues on the quarto-web has been disabled.
Closing this.
