### ISSUE TITLE
Link to the fork (example of quarto)

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#1329]
I wonder if this link could be set to the fork containing the actual quarto document source code.

https://github.com/quarto-dev/quarto-web/blob/d03cac2dbbaf08555a08a63a4fb232bdbb3644b2/docs/books/book-basics.qmd#L25

https://github.com/jjallaire/visualization-curriculum

**Comment by jjallaire** [comment]
Just resolved, thanks!
