### ISSUE TITLE
Feature request: compiling to jupyter-notebook

### ISSUE THREAD

**Issue by NelleV** [quarto-dev/quarto-cli#133]
Hello,

Collaborators and I are using quarto for reproducible scientific publication purposes. As part of our pipeline, we would like not only to compile to HTML/PDF, but also to have a jupyter-notebook version (in order to then link to binder). 
I believe execution of the code is already performed using the jupyter ecosystem. Is it possible to add as output format a jupyter-notebook?

Many thanks,
Nelle

**Comment by dragonstyle** [comment]
Hi Nelle,

I think that the best way to accomplish this will be to enable `keep-ipynb` (more [here](https://quarto.org/docs/computations/execution-options.html#intermediates)) which will keep that intermediate notebook around after rendering. Let us know if this works for your use case!

**Comment by jjallaire** [comment]
Okay, I've made a some improvements aimed at enabling ipynb as a output format. From a `qmd` you would do this:

```yaml
---
title: "My Document"
format: ipynb
---
```

Standard output types (images, text, stderr, raw HTM, etc.) are handled correctly by the `ipynb` format, however JavaScript based output (e.g. plotly, ipywidgets, etc.) aren't currently working (we do a bunch of things to make these outputs compatible with HTML export which are somewhat at odds with what's needed to create an ipynb -- this can definitely be overcome but will just take a bit more finesse).

**Comment by prosoitos** [comment]
I am also interested in this feature, but for different reasons: I like using JupyterHub for some of the intro programming workshops I give, but I'd much rather work in my favorite text editor while developing the material than in the Jupyter IDE.

So I agree that adding Jupyter notebooks to the list of output formats is a great idea. Thank you!!

**Comment by prosoitos** [comment]
`format: ipynb` is great!

Followed by `jupyter nbconvert --clear-output --inplace doc.ipynb` I can get a notebook without the output from my .qmd file.

**Comment by astamm** [comment]
Hi all. Just jumping in there as I happen to be in a situation similar to Nelle's with colleagues of mine. I have trouble using the output format `ipynb`. My `qmd` source has no JS based outputs but still it fails to run with YAML header:
```
title: "Using up-to-date Gudhi library in R"
author: "Aymeric Stamm"
date: today
title-block-banner: true
format: ipynb
jupyter: ir
editor: visual
```
with the following error:
```
Error running filter /Applications/quarto/share/filters/quarto-post/quarto-post.lua:
...cations/quarto/share/filters/quarto-post/quarto-post.lua:1314: attempt to get length of a nil value (local 'values')
stack traceback:
	...cations/quarto/share/filters/quarto-post/quarto-post.lua:2169: in local 'fn'
	...cations/quarto/share/filters/quarto-post/quarto-post.lua:1073: in function <...cations/quarto/share/filters/quarto-post/quarto-post.lua:1067>
```

It goes all the way through though if I use the `html` output with option `keep-ipynb` activated but, as pointed out by @jjallaire, it does not deal with the YAML header and others.

Am I missing something?
Thanks in advance.

**Comment by astamm** [comment]
I shall add that, as it may be obvious from the choice of the Jupyter engine, my `qmd` document does contain both R and Python chunks of code.

**Comment by jjallaire** [comment]
Thanks for reporting this error! It should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/da6fc9b3983a87c41c6a6c3b594321c240f88873 

Note that Jupyer notebooks have only one type of code cell (determined by the underlying kernel). Obviously cell magics are one way to work around this, but `format: ipynb` is not aware of this. So if you have a mix of R and Python chunks the they will all be treated uniformly as "code" (and the resulting notebook likely not executable).
