### ISSUE TITLE
book: GitHub icon link set by `repo-url` is prefixed with CNAME entry

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-cli#1335]
### Bug description

In https://mlr3book.mlr-org.com/ we see that the GH icon which is populated by defining `repo-url` is prefixed with the CNAME entry (which lives in the [gh-pages](https://github.com/mlr-org/mlr3book/tree/gh-pages) branch).

This only happens when deploying via CI. In local previews, the link is correct (i.e. does not contain the CNAME prefix).

Repo: https://github.com/mlr-org/mlr3book

Workflow: https://github.com/mlr-org/mlr3book/blob/main/.github/workflows/build-book.yml

cc https://github.com/mlr-org/mlr3book/issues/375

### `quarto check` Output

quarto v0.9.655 during the latest CI run

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [ ] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thanks for reporting this, it is fixed here: https://github.com/quarto-dev/quarto-cli/commit/0e6a1a03af35d3569aabd7e99613803d2f5a998b (new build w/ the fix should be available shortly)
