### ISSUE TITLE
Way of specifying code file to be sourced for each page?

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#134]
Our book needs a small suite of R code executed at the beginning of each page, in our case called `_common.R`.

At the moment we are doing this by putting this chunk at the top of each page, as suggested in #38:

~~~
```{r setup, include=FALSE}
source("_common.R")
```
~~~

This issue is to ask for a way to specify such a file to run by default.

Bookdown allows you to do this using the `before_chapter_script` YaML configuration option : https://bookdown.org/yihui/bookdown/configuration.html

**Comment by sbalci** [comment]
Hi,
I want to upvote for this.
I also need `before_chapter_script` as in `bookdown`.
I want to define language to render in one file and then select which chunks to be selected `asis` throughout the book. 
Thank you.

**Comment by mghassany** [comment]
upvote

**Comment by sbalci** [comment]
Hi, those following this feature, this may be a workaround: https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/posts/04-include/
https://twitter.com/quarto_pub/status/1542947672033824769

**Comment by mcanouil** [comment]
I am going to go ahead and close this as per the following comment by @cscheid:

- https://github.com/quarto-dev/quarto-cli/discussions/3250#discussioncomment-4090898

To note, this might be revisited at a later point.
