### ISSUE TITLE
Graphics images not being created in one book chapter

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1340]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1310

<div type='discussions-op-text'>

<sup>Originally posted by **harrelfe** July  6, 2022</sup>
I moved a book to a new directory, removed _freeze, re-started a book project, and rendered all chapters.   All chapters look fine except for one, using `Quarto` 0.9.648.  The directory `_book/chaptername_files` is empty even though there were no execution errors.

I haven't changed any of the chapter script.  I'm sorry I can't produce a short example.

**UPDATE** The chapter starts with two `mermaid` charts.  When I remove those two chunks the graphs render as they are supposed to.

**UPDATE 2** When I put the chapter as a self-contained article there is no problem with the figures.  The `book` environment seems to have a problem.

Here is a minimal failing example book: https://hbiostat.org/attach/btest.zip

**UPDATE 3** I had to go all the way back to `Quarto` 0.9.560 to get the figures rendered when preceded by a `mermaid` chunk.
</div>

**Comment by cscheid** [comment]
This is a fun one.

Somehow, we are getting the following two directories into the array of supporting files for `index.qmd`: `["index_files", "index_files/figure_html"]`. Importantly, they're in this order.

Then, in `project.ts:261 (relocateDir)`:
- handling "index_files", we correctly move `index_files` to the book location. (which contains `index_files/figure_html`)
- handling "index_files/figure_html", we find that the destination directly already contains `index_files/figure_html`. The code assumes that an existing destination means a stale directory, and so deletes it. In this case, however, that was a good directory that we just moved, and so things break.

**Comment by jjallaire** [comment]
@harrelfe a quick update, we understand the source of the problem and are just trying to find the right fix. Expect to land this in a release later today.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/73b3b42365aea6675febfbece4ca250e9f567163

**Comment by harrelfe** [comment]
Thank you, thank you JJ and team.  Working great!   I now have two Quarto books that are rendering beautifully.  One of them is 600 pages long so giving Quarto quite a workout.

**Comment by jjallaire** [comment]
Great to hear! Are there links to those published books and/or their source code?  If so, would you be okay with our listing them in our Gallery of examples?
