### ISSUE TITLE
YAML frontmatter for python path

### ISSUE THREAD

**Issue by amichuda** [quarto-dev/quarto-cli#1341]
I mostly use quarto with a particular conda environment and for some reason even when I run it after activating the environment, it still runs the default python. Is there some frontmatter to force a particular python interpreter? 

Is there a place to read up on all frontmatter options? I couldn't seem to find it in the user guide or reference page.

**Comment by jjallaire** [comment]
You can execute `quarto check` to see what version of Python Quarto is binding to. Quarto will use the version of Python that it finds on the PATH or whatever is specified in the QUARTO_PYTHON environment variable (see https://quarto.org/docs/computations/python.html#installation)

**Comment by baggiponte** [comment]
> You can execute `quarto check` to see what version of Python Quarto is binding to. Quarto will use the version of Python that it finds on the PATH or whatever is specified in the QUARTO_PYTHON environment variable (see https://quarto.org/docs/computations/python.html#installation)

Sorry to come back to this. If I am in an environment (e.g. venv), the recommended workflow is to install in the env jupyter/ipykernel and create a kernel and have quarto point to that kernel? Could quarto instead be shipped with (say) ipykernel or xeus and create these kernels automatically, with the user just passing the interpreter path as VSCode/PyCharm do?

**Comment by jjallaire** [comment]
No, you definitely don't need to install Jupyter kernels inside the `venv` -- they should be globally installed and available (at least that's how I've seen it work). I'm aware of any difference in how we handle kernels from how VSCode does (the notebook or declares the kernel it wants -- in our case if there is no declaration in a `qmd` we simply find the `python3` kernel or failing that any other kernel that can handle Python.

**Comment by baggiponte** [comment]
Oh okay great! So I just need a globally installed jupyter (with, say, `pipx`) and then I just install a kernel from the venv in use - am I right? So I guess there could be a `quarto kernel install path/to/interpreter` that could install kernels and potentially have more kernel-management related functions e.g. `quarto kernel list` and `quarto kernel use`?

**Comment by jjallaire** [comment]
I would say that installing kernels inside virtual envs is an extremely dicey proposition. Now you are forced to maintain (and update!) a kernel for every venv in use. To my knowledge Kernels can be globally shared on a machine (in fact they don't even need to be written in Python so really a very different "resource" than Python packages).

We are really trying to stay out of the business of kernel and venv "management". It's extremely complicated and error prone and layering on an entirely new set of management primitives that are specific to Quarto is likely to make things worse.

**Comment by baggiponte** [comment]
I totally understand your point! I am afraid I was not clear enough - but I might also not have understood the kernel thing.
My workflow with notebooks & python has always been:

- create a venv/conda env
- use `ipython kernel install --name env --display-name "longer descriptive name" --sys-prefix`
- choose that kernel from the dropdown jupyter menu so that it runs all the packages in the environment

Did I use it wrong? Is this what you mean by 'installing kernels inside virtual envs is an extremely dicey proposition'? If so, how could I use the default python3 kernel and have quarto/the kernel use the packages in the venv to run the code?

**Comment by jjallaire** [comment]
My understanding is that kernels are entirely orthogonal to virtual environments (they are a global resource). While you do need to install the `jupyter` package in your virtual environment you do not need to install the kernel. 

The scenario you are describing is exactly what I do all the time (have a venv use an external kernel) and seems to be what others are doing based on discussion online, etc.
