### ISSUE TITLE
LaTeX not adding new line

### ISSUE THREAD

**Issue by RaymondBalise** [quarto-dev/quarto-cli#1348]
### Bug description

LaTeX equations that include a new line code `\\` are not rendered on a new line:

When rendered as a PDF the "Inline math" format (`$math$`) works as it should and it uses the `\\` to print things on a new line. (I know using a new line command with "inline" code is illogical but it was useful to show the issue).  The "Display Math" format (`$$math$$`) does not use the `\\` at all (and it needs to):

````
---
title: "Latex new line issue"
format: pdf
---

Showing Inline Math $1 < 2 \\ \neq -1\cdot 1 < -1 \cdot 2 \\ = -1 > -2$

or Display Math:

$$1 < 2 \\ \neq -1\cdot 1 < -1 \cdot 2 \\ = -1 > -2$$
````
When rendered to HTML neither the "Inline Math" nor "Display Math"  formats use the requested new lines. 

````
---
title: "Latex new line issue"
format: html
---

Showing Inline Math $1 < 2 \\ \neq -1\cdot 1 < -1 \cdot 2 \\ = -1 > -2$

or Display Math:

$$1 < 2 \\ \neq -1\cdot 1 < -1 \cdot 2 \\ = -1 > -2$$
````

The preview in the Studio IDE renders the LaTeX properly.  

I am running:

```
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4, RStudio 2022.2.3.492

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 bslib_0.3.1     digest_0.6.29   evaluate_0.15   fastmap_1.1.0  
  fs_1.5.2        glue_1.6.2      graphics_4.2.0  grDevices_4.2.0 highr_0.9      
  htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.8.0  knitr_1.39      magrittr_2.0.3 
  methods_4.2.0   R6_2.5.1        rappdirs_0.3.3  rlang_1.0.3     rmarkdown_2.14 
  sass_0.4.1      stats_4.2.0     stringi_1.7.6   stringr_1.4.0   tinytex_0.40   
  tools_4.2.0     utils_4.2.0     xfun_0.31       yaml_2.3.5     

Pandoc version: 2.17.1.1
```

### `quarto check` Output

[✓] Checking Quarto installation......OK
      Version: 1.0.7
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.9
      Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
      Jupyter: 4.11.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

### `quarto tools check` Output

[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Up to date        v2022.07      v2022.07
WARNING: TeX Live not on path.

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Somewhat surprisingly, line breaks are [not supported in MathJax](https://github.com/mathjax/MathJax/issues/2312), but they apparently will be soon.

Usually, the kind of behavior you're looking for with line breaks can be emulated by `align`, `eqnarray`, or other such latex environments. When MathJax fixes this, we'll update our dependency right away.
