### ISSUE TITLE
Multiple kernels in same file

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#135]
It would be nice to support executing several languages in the same file. My use case is that I'm using "panel-tabsets" to show solutions implemented in different languages (e.g. Octave and Python). Currently only one of the tabs can show the result of running of the code.

**Comment by baggiponte** [comment]
How does R work? Can't you mix Jupyter and Python code chunks in .Rmd files?

**Comment by jmbuhr** [comment]
Yes, R can do that through the `knitr` package, which calls multiple language engines and can also mix R and python code through the `reticulate` package. You can set the quarto engine to be `knitr` and should be able to use R and python in the same document: https://quarto.org/docs/computations/running-code.html#engine-binding

Thanks to `reticulate` you can even use variables from R in your python chunks and the other way around.
