### ISSUE TITLE
For giscus implement `data-loading: lazy` to speed up page loading

### ISSUE THREAD

**Issue by gustavdelius** [quarto-dev/quarto-cli#1357]
When giscus is enabled, pages can be slow in loading while waiting for giscus to load. However giscus has a `data-loading="lazy"` option. On https://giscus.app this is described as:

> Loading of the comments will be deferred until the user scrolls near the comments container. This is done by adding loading="lazy" to the <iframe> element.

Currently quarto does not recognise the `data-loading` key. See here for the list of currently supported giscus keys: https://quarto.org/docs/reference/projects/websites.html#giscus

I propose to add this key.

**Comment by dragonstyle** [comment]
Great suggestion - we'll take a look post 1.0.
