### ISSUE TITLE
Bad output for display math followed by text on same line

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#136]
For example given the following `test.md`:

```
# Test

a $$x$$ b.
```

calling `quarto render test.md` generates an html page without content (just the title).

Using pandoc directly with `pandoc test.md -s -o test.html` gives a correct output.

**Comment by jjallaire** [comment]
Good one, thanks for reporting!

Should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/9a33c52f9c221b3103fcaf816cdde2cf985e0a63
