### ISSUE TITLE
Using filter extensions from document in subfolder makes pandoc error

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#1361]
### Bug description

````
quarto create-project website-with-ext --type website
cd .\website-with-ext\
quarto install extension quarto-ext/code-filename
mkdir more
echo "---" > more/index.qmd
echo "filters:" >> more/index.qmd
echo "  - code-filename" >> more/index.qmd
echo "---" >> more/index.qmd
quarto render
````

Content for `more/index.qmd` is really simple for the sake of the reprex
````
---
filters:
  - code-filename
---
````

This is the issue we get 
````
> quarto render
[1/3] about.qmd
[2/3] index.qmd
[3/3] more\index.qmd
Error running filter _extensions/quarto-ext/code-filename/code-filename.lua:
cannot open _extensions/quarto-ext/code-filename/code-filename.lua: No such file or directory
````

It seems we have an issue with Pandoc when an extensions filter is used in a subfolder. 
The error above is from Pandoc. `pandoc` CLI is run in which environment ? It seems that the lua filter is not found because path is relative to where Pandoc is run and lua filter is not among the data files folder.

Using last dev version.

**Comment by cderv** [comment]
@dragonstyle sorry about this. I'll rework the reprex as it is not a good one. Something else is problematic. 
The issue is in https://github.com/rocker-org/website/tree/use-ext from https://github.com/quarto-ext/code-filename/issues/2 and I tried to create a reprex, but used the wrong folder. I'll dig further.

**Comment by cderv** [comment]
I confirm that #1362 fix the issue regarding the Lua filter which is found. 

However, we have still an issue (maybe related to the extension itself) as the dependency is not created 

This is the site lib after `quarto render`
````
ls .\_site\site_libs\

    Directory: C:\Users\chris\Documents\DEV_OTHER\ISSUES\quarto\website-with-ext\_site\site_libs

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          12/07/2022    15:36                bootstrap
d----          12/07/2022    14:58                clipboard
d----          12/07/2022    14:58                quarto-html
d----          12/07/2022    14:58                quarto-nav
d----          12/07/2022    14:58                quarto-search
````

But it should have been created  as `quarto.doc.addHtmlDependency` is used
https://github.com/quarto-ext/code-filename/blob/85dc809bb539711fa7767b19cac885e33e2664d1/_extensions/code-filename/code-filename.lua#L41-L45

**Comment by eitsupi** [comment]
I am wondering if there is any need for test cases for extensions.
