### ISSUE TITLE
output-location not working

### ISSUE THREAD

**Issue by meenakshi-kushwaha** [quarto-dev/quarto-cli#1377]
### Bug description

Hello, 

The output-location feature is not working for me while making quarto slides  in Rstudio. Below is a reproducible example with screenshot. none of the options of the feature are working (fragment, column, slide). The output continues to show up below the code on the same slide. 

Rstudio version 2022.02.3 Build 492
macOS Monterey version 12.3.1(21E258)
Quarto Version: 0.9.80

````
---
title: "test"
format: revealjs
---
## Executable Code

```{r}
#| echo: true
#| output-location: slide

3+4
```
````

### `quarto check` Output

[✓] Checking Quarto installation......OK
      Version: 0.9.80
      Path: /Applications/RStudio.app/Contents/MacOS/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.7.4
      Path: /usr/local/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

meenakshikushwaha@MacBook-Pro 2022_July_quarto-slides_data-wrangling % Checking R installation...........OK
quarto tools check
zsh: command not found: Checking
[✓] Reading Tool Data
Tool                Status                          Installed     Latest        
tinytex             Present - ext. managed          ----          v2022.07      
meenakshikushwaha@MacBook-Pro 2022_July_quarto-slides_data-wrangling % /usr/local/bin/quarto check

zsh: no such file or directory: /usr/local/bin/quarto
meenakshikushwaha@MacBook-Pro 2022_July_quarto-slides_data-wrangling % quarto check

[✓] Checking Quarto installation......OK
      Version: 0.9.80
      Path: /Applications/RStudio.app/Contents/MacOS/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.7.4
      Path: /usr/local/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

### `quarto tools check` Output

<img width="550" alt="image" src="https://user-images.githubusercontent.com/52627451/178777342-186797da-6874-4392-8c6d-a1ea11d85d4f.png">

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [ ] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by meenakshi-kushwaha** [comment]
attaching the screenshot again
<img width="550" alt="Screenshot 2022-07-14 at 12 21 18 AM" src="https://user-images.githubusercontent.com/52627451/178783160-4f40e5dc-fa04-4273-a538-3953eddb08da.png">

**Comment by cderv** [comment]
Hi, 

Please format your issue correctly so that it is readable. See https://yihui.org/issue/#please-format-your-issue-correctly
you are probably missing a N+1 backtick somewhere. 

Also, I can't reproduce. We need to see `quarto check` output 

What is the quarto version ? 

I am using last dev version. Are you using last released version ?

**Comment by meenakshi-kushwaha** [comment]
Hello,

Thank you for your reply.

This is the output from quarto check. Could you let me know how to update
to the latest version from within rstudio? Thanks!


[✓] Checking Quarto installation......OK
      Version: 0.9.80
      Path: /Applications/RStudio.app/Contents/MacOS/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.7.4
      Path: /usr/local/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

***@***.*** 2022_July_quarto-slides_data-wrangling %
Checking R installation...........OK
quarto tools check
zsh: command not found: Checking
[✓] Reading Tool Data
Tool                Status                          Installed     Latest

tinytex             Present - ext. managed          ----          v2022.07

***@***.*** 2022_July_quarto-slides_data-wrangling %
/usr/local/bin/quarto check

zsh: no such file or directory: /usr/local/bin/quarto
***@***.*** 2022_July_quarto-slides_data-wrangling %
quarto check

[✓] Checking Quarto installation......OK
      Version: 0.9.80
      Path: /Applications/RStudio.app/Contents/MacOS/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.7.4
      Path: /usr/local/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

*Meenakshi Kushwaha * <https://meenakshi.rbind.io/>

**Comment by meenakshi-kushwaha** [comment]
I have edited the post to include the missing backticks and quarto check output. This is my first bug report. Thanks for handholding and your help.

**Comment by meenakshi-kushwaha** [comment]
Could you please point me to any resources on how to update quarto from within Rstudio IDE? And which is the latest version? 

Thanks again,
Meenakshi

**Comment by meenakshi-kushwaha** [comment]
Thanks! that solved it.
