### ISSUE TITLE
Feature request: tab-complete on chunk options

### ISSUE THREAD

**Issue by MCMaurer** [quarto-dev/quarto-cli#138]
This is probably a bit more of an RStudio integration issue, but I wasn't sure of a better place to open this.

I've been playing around with Quarto a bit, and it has been absolutely fantastic. For the most part, the experience moving from `.Rmd` has been pretty smooth. However, one thing that I really miss is the ability to use tab-completion for chunk options. I can never remember the full set of chunk options, so going between the curly brackets and hitting tab was my go-to move.

This still works if you go into the curly brackets, but it seems like the `#|` is going to be the best practice moving forward, and having some tab-completion functionality would make it a lot more accessible.

**Comment by jjallaire** [comment]
Yes! @cscheid is actually working on this right now over here (https://github.com/quarto-dev/quarto-cli/tree/feature/yaml-validation):

https://user-images.githubusercontent.com/104391/137985993-41709cd7-8d50-439c-9508-4257835f95a3.mov

This will encompass auto-complete, realtime diagnostics, and realtime validation (for much better error messages for incorrect, incomplete, or malformed YAML).

**Comment by jjallaire** [comment]
This is now available in the current release of RStudio IDE as well as in our VS Code Extension (https://marketplace.visualstudio.com/items?itemName=quarto.quarto)
