### ISSUE TITLE
Add Tools Info to `quarto check`

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#1392]
Print tools info for users as a part of `quarto check` (print pretty human readable form).

Remove `quarto tools info` from bug template

**Comment by allenmanning** [comment]
Should this read `quarto tools list` rather than `quarto tools info`?

````
quarto tools help

  Usage:   quarto tools <command> [tool]
  Version: 99.9.9

  Description:

    Installation and update of ancillary tools.

      tools:
        tinytex
        chromium

      commands:
        install
        uninstall
        update

    Use 'quarto tools' with no arguments to show the status of all tools.

  Options:

    -h, --help              - Show this help.
    --log         <level>   - Path to log file
    --log-level   <level>   - Log level (info, warning, error, critical)
    --log-format  <format>  - Log format (plain, json-stream)
    --quiet                 - Suppress console output.
    --profile               - Active project profile(s)

  Commands:

    help  [command]  - Show this help or the help of a sub-command.

  Examples:

    Install TinyTex:   quarto tools install tinytex
    Uninstall TinyTex: quarto tools uninstall tinytex
    Update TinyTex:    quarto tools update tinytex
    Show tool status:  quarto tools list
````

**Comment by allenmanning** [comment]
I also saw this from another post: https://github.com/quarto-dev/quarto-cli/issues/4896#issuecomment-1478295317

              You might find more information with these commands:

```r
Sys.getenv() # env variables
.libPaths() # library paths 
```

_Originally posted by @cscheid in https://github.com/quarto-dev/quarto-cli/issues/4896#issuecomment-1478295317_

**Comment by allenmanning** [comment]
This may also be related https://github.com/quarto-dev/quarto-cli/issues/4845

**Comment by allenmanning** [comment]
Related: https://github.com/quarto-dev/quarto-cli/pull/1376

**Comment by dragonstyle** [comment]
I think that the best thing to do here is to actually provide some custom tooling here that actually tries to answer two questions:

- Is `Tex` installed and if so, what `Tex` will be used to render PDF documents
- Is `Chromium` available and if so, what will be used to render compatible version of images for PDFs and other documents.

I think the the biggest challenge is being sure that a user who isn't interested in rendering PDFs isn't confronted with `quarto check` output that implies that they should install these other tools (e.g. by outputting a simple message that the tools isn't installed, etc). 

As I look at the code for checking, I wonder if we should really add a `pdf` target that will check tools and perform a basic PDF render to confirm that things work (similar to what we do for basic installation and knitr/jupyter) - we could then make this explicitly testable via `quarto check pdf` as well as run when doing `quarto check`

What do you think about this?

**Comment by allenmanning** [comment]
Sending back to @dragonstyle as my Confluence queue needs to be addressed first.

**Comment by cderv** [comment]
Other related issue : https://github.com/quarto-dev/quarto-cli/issues/5980
