### ISSUE TITLE
Autocomplete: Quarto for VSCode

### ISSUE THREAD

**Issue by VivaldoMendes** [quarto-dev/quarto-cli#1399]
I am using Quarto in VSCode. I wonder whether it is possible to use the autocomplete facilities for cross-references and citations. This is a convenient functionality, but I could not find it anywhere.

**Comment by dragonstyle** [comment]
We don't currently support this, but agree that it would be a great feature. We'll mark this as something to consider as an improvement to the extension post 1.0.

**Comment by jjallaire** [comment]
Yes, we have most of the infrastructure required to do this and will certainly make it a priority!

**Comment by VivaldoMendes** [comment]
Sorry for coming back to this issue.  A week ago, a tweet informed us that the autocompletion for citations in the VSCode extension had been implemented.  I have updated my VSCode (with Quarto 1.30.0), but this facility is not working. Do we have to wait some more, or am I making some stupid mistake? Thanks a lot.

**Comment by mcanouil** [comment]
I believe this to be completed as part of the visual editor.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/231bcc35-38f1-458f-8c4b-0b944cf2c5b6">

See:
- https://quarto.org/docs/visual-editor/vscode/
- https://quarto.org/docs/visual-editor/

**Comment by jjallaire** [comment]
This should also work in the source editor.
