### ISSUE TITLE
Can't retrieve author name using meta shortcode `{{< meta author >}}`

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#1406]
### Bug description

Can't retrieve author name using meta shortcode `{{< meta author >}}` as discussed in https://github.com/quarto-dev/quarto-cli/issues/1391#issuecomment-1185384785
````
---
title: "My title"
author: "Mickaël Canouil"
date: last-modified
format: html
self-contained: true
---

{{< meta title >}}
{{< meta author >}}
{{< meta author.name >}}
{{< meta date >}}
````

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/8896044/179202138-a9ffc243-1d5f-4b33-9cc6-e244735ee217.png">

Code: https://github.com/mcanouil/quarto-issues/tree/main/quarto-cli-1406

### `quarto check` Output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.20
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.5
      Path: /opt/homebrew/opt/python@3.10/bin/python3.10
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

(-) Checking R installation...........ℹ R version 4.2.1 (2022-06-23)
! Config '~/.Rprofile' was loaded!
[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.07
```

**Comment by mcanouil** [comment]
Follow-up question, now it's possible (with Quarto 1.0.28) to get the author's name easily, but what's the shortcode (if it exists) to get affiliation or any keys from the author schema (<https://quarto.org/docs/journals/authors.html>?

`{{< meta author.affiliation >}}` is described in the variables/meta (https://quarto.org/docs/authoring/variables.html#meta) but does not work.

```
---
title: "My title"
author:
  - name: Norah Jones
    affiliation: Carnegie Mellon University
date: last-modified
format: html
self-contained: true
---

{{< meta author >}}
{{< meta author.affiliation >}}
```

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/8896044/179424123-28eaaa79-ac84-4494-880e-5f2b53d17b2e.png">

**Comment by mcanouil** [comment]
This is what I had in mind if I really needed to extract those elements.
May I suggest to edit Quarto docs to remove the example using `author.affiliation`?

- https://github.com/quarto-dev/quarto-web/blob/ac7b86a25d1fa197a5fb175c86e1beb9b26c29e5/docs/authoring/variables.qmd#L66-L68  
  ![image](https://user-images.githubusercontent.com/8896044/179530705-f4250b35-fede-4281-80b3-2bdf178ccdf5.png)

**Comment by dragonstyle** [comment]
Ok I've updated the docs to exclude that example - thanks! I'm closing, but if you think there is something for us to consider here post 1.0, please reopen...
