### ISSUE TITLE
New `--no-config` argument is incompatible with some versions of deno

### ISSUE THREAD

**Issue by lkhilton** [quarto-dev/quarto-cli#1420]
### Bug description

I'm running CentOS 7 so the version of deno that's packaged with the current Quarto-CLI is incompatible with my system (see https://github.com/denoland/deno/issues/1658). 

The workaround was to install deno using conda: 
`mamba install -c conda-forge deno`
After that I copied this CentOS7-compatible binary to the original location in the Quarto-CLI folder. 

I first did this after installing Quarto CLI from https://github.com/quarto-dev/quarto-cli/releases/download/v1.0.28/quarto-1.0.28-linux-amd64.tar.gz. I ran the following command and got the subsequent error: 
```
$ ~/software/quarto-1.0.28/bin/quarto tools check                       
error: Found argument '--no-config' which wasn't expected, or isn't valid in this context

USAGE:
    deno run <SCRIPT_ARG>... --unstable

For more information try --help
```

I installed Quarto 1.0.18 instead, which precedes this [pull request](https://github.com/quarto-dev/quarto-cli/pull/1388). 

```
$ ~/software/quarto-1.0.18/bin/quarto tools check                                
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.07
```

Details about my deno install: 
```
$ ~/software/quarto-1.0.18/bin/tools/deno --version                            
deno 1.17.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
```

Reporting this bug in case others trying to run Quarto on CentOS 7 have similar issues implementing this workaround. 

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thanks for pointing this out! I will note however that while you may have gotten it to work w/ Deno 1.17 Quarto internally has a hard requirement on later versions of Deno (as we may be calling APIs that are either not yet available in v1.17 or produce different results). So I'm thinking it is better than you apply a local workaround than we make a change to "enable older versions of deno" when that is definitely a warranty voiding action in the first place. Hope that makes sense.

**Comment by lkhilton** [comment]
Yes, makes sense. Thanks for the reply!

**Comment by dragonstyle** [comment]
Closing this as we currently don't plan to support older versions of Deno (at least for the time being).
