### ISSUE TITLE
Images does not show up

### ISSUE THREAD

**Issue by msh855** [quarto-dev/quarto-cli#1421]
I have created a post with images read from my local machine, but in the preview, the images do not show up:

![image](https://user-images.githubusercontent.com/26636184/179345854-01fa6b13-1b38-44d1-ab2e-6f7f2fcd0d67.png)

I just use markdown to create the post. In my markdown app, images show up perfectly. Here is the code:

`
![Core Inflation](/Users/safishajjouz/GitHub/myblog/posts/inflation_regimes/inflation_pic2.png)
`

**Comment by jjallaire** [comment]
You can't use absolute paths, rather the images need to be located within the directory that contains your document.

You might be able to get this to work by setting `self-contained: true` but I'm not 100% sure about that.

**Comment by jjallaire** [comment]
That's unfortunately not going to work when you deploy the site to another machine (as it won't have `/Users/safishajjouz` on it. You need to use relative links to images within websites.
