### ISSUE TITLE
Document that favicon can be used for HTML book projects too?

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-cli#1424]
I'm using Quarto for an HTML book and it seems https://quarto.org/docs/websites/website-tools.html#social-metadata works in that case too. Should the favicon docs be repeated in the book section?

**Comment by jjallaire** [comment]
Yes indeed they should! I added this catchall section here to let people know that website tools also work for books: https://quarto.org/docs/books/book-output.html#website-tools

**Comment by maelle** [comment]
Awesome, thank you!
