### ISSUE TITLE
UTF-8 characters not properly rendered via VSCode "render" button

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#1429]
### Bug description

When rendering a qmd file with VSCode extension, i.e., using the "render" button, the UTF-8 characters are not rendered properly when knitr engine is used.

<details><summary>See quarto code</summary>

````
---
title: "Untitled"
format: gfm
---

```{r}
1
```

Des accents: éèêàçôö
````

</details>

<img width="600" alt="image" src="https://user-images.githubusercontent.com/8896044/179362288-7f30bcb8-4ca2-4955-bb26-a5d36820b942.png">

Without the R cell chunk, the rendered document is just fine.

<details><summary>See quarto code</summary>

````
---
title: "Untitled"
format: gfm
---

Des accents: éèêàçôö
````

</details>

<img width="600" alt="image" src="https://user-images.githubusercontent.com/8896044/179362304-59aed159-7cfe-4e26-9677-27084bf0ec25.png">

There is no problem using quarto cli (or using quarto R package):  
<img width="350" alt="image" src="https://user-images.githubusercontent.com/8896044/179362412-4a2a9251-89ef-4b95-9cb2-d0af9d45bdad.png"><img width="350" alt="image" src="https://user-images.githubusercontent.com/8896044/179362384-e678266e-8430-4306-9637-689827d35e44.png">

Code: https://github.com/mcanouil/quarto-issues/tree/main/quarto-cli-1429

OS: MacOS latest (arm64)
R: 4.2.1
Quarto: 1.0.25
VSCode/Extension: latest
<details><summary>See `.Rprofile` content</summary>

```
if (nzchar(system.file(package = "cli"))) {
  cli::cli_alert_info(R.version.string)
  cli::cli_alert_warning(paste0("Config '", cli::col_green("~/.Rprofile"), "' was loaded!"))
} else {
  message(R.version.string)
  message("Config '~/.Rprofile' was loaded!")
}

options(
  languageserver.formatting_style = function(options, ...) {
    transformers <- styler::tidyverse_style(indent_by = options$tabSize, ...)
    transformers$indention$update_indention_ref_fun_dec <- NULL
    transformers$indention$unindent_fun_dec <- NULL
    transformers$line_break$remove_line_breaks_in_fun_dec <- NULL
    transformers
  }
)

if (interactive()) {
  options(
    repos = c(
      "CRAN" = if (is.null(getOption("repos")[["CRAN"]]) || getOption("repos")[["CRAN"]] %in% "@CRAN@") {
        "https://cran.r-project.org/"
      } else {
         getOption("repos")[["CRAN"]]
      }
    ),
    width = 150,
    menu.graphics = FALSE,
    reprex.advertise = FALSE,
    usethis.protocol = "https",
    usethis.full_name = "Mickaël Canouil",
    usethis.description = list(
    `Authors@R` = paste0(
        "person(",
          'given = "Mickaël", ',
          'family = "Canouil", ',
          'role = c("aut", "cre"), ',
          'email = "mickael.canouil@cnrs.fr", ',
          'comment = c(ORCID = "0000-0002-3396-454")',
        ")"
      ),
      Version = "0.0.0.9000"
    )
  )

  if (nzchar(system.file(package = "devtools"))) library(devtools, quietly = TRUE, warn.conflicts = FALSE)

  if (nzchar(system.file(package = "prompt"))) prompt::set_prompt(prompt::prompt_git)

}

```

</details>

### `quarto check` Output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.25
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.5
      Path: /opt/homebrew/opt/python@3.10/bin/python3.10
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

(-) Checking R installation...........ℹ R version 4.2.1 (2022-06-23)
! Config '~/.Rprofile' was loaded!
[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.07
```

**Comment by jjallaire** [comment]
Priceless bug to have found right before release! Thank you :-) This is a side effect of our recent switch from using the Terminal for quarto preview to using VS Code Output Channels.

Fixed here: https://github.com/quarto-dev/quarto-vscode/commit/70f5c79aedb9083642057721c6808019d25a4db3

Update to v1.27.0 of the VS Code extension to get the fix. Thanks again!

**Comment by mcanouil** [comment]
You are welcome, it's Easier to notice this with French accents 😅😎
Although, I only discovered this because I manually rendered a Quarto README manually instead of via CI 🙃
