### ISSUE TITLE
References links in revealjs presentation goes to first slide, should go to last

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#1431]
### Bug description

If you include a citation in a `revealjs` presentation, the link for the citation should go to the last slide with references instead of the first slide.

Here is a slide:

```` markdown
---
format: revealjs
bibliography: references.bib
---

## Slide 1

Slide 1 text.

## Slide 2

Slide 2 text.
[@gorman2014]

## References
````

And here is the contents of `references.bib`:

``` markdown

@article{gorman2014,
	title = {Ecological Sexual Dimorphism and Environmental Variability within a Community of Antarctic Penguins (Genus Pygoscelis)},
	author = {Gorman, Kristen B. and Williams, Tony D. and Fraser, William R.},
	year = {2014},
	month = {03},
	date = {2014-03-05},
	journal = {PLOS ONE},
	pages = {e90081},
	volume = {9},
	number = {3},
	doi = {10.1371/journal.pone.0090081},
	url = {https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0090081},
	note = {Publisher: Public Library of Science},
	langid = {en}
}
```

Inspecting the link on Slide 2:

``` html
<a href="#/ref-gorman2014" role="doc-biblioref" onclick="return false;" aria-expanded="false">Gorman, Williams, and Fraser 2014</a>
```

`#/ref-gorman2014` goes to Slide 1 instead of last slide. Either disabling the clickable link or pointing it to the last slide would resolve the issue.

- Quarto version: 1.0.28
- RStudio version: RStudio 2022.07.0+548 "Spotted Wakerobin" Release (34ea3031089fa4e38738a9256d6fa6d70629c822, 2022-07-06) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
- OS: macOS 12.4

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [ ] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/5246d7dd6d1ba97baf2fe0ebc51a3c1a8a64f8f1
