### ISSUE TITLE
Unable to add captions to reactable objects 

### ISSUE THREAD

**Issue by canholyavkin** [quarto-dev/quarto-cli#1435]
While using RStudio, the following code can generate captions above the table.

```{r}
#| label: tbl-iris
#| tbl-cap: "Iris Data"

library(knitr)
kable(head(iris))
```
<img width="596" alt="Screen Shot 2022-07-03 at 13 00 46" src="https://user-images.githubusercontent.com/28393339/177034724-7bad2bc5-1325-4863-bcae-07e50e85b06e.png">

However, when I try the same code with **reactable** objects, it just ignores the caption.

```{r}
#| label: tbl-iris
#| tbl-cap: "Iris Data"

library(reactable)
reactable(head(iris))
```
<img width="614" alt="Screen Shot 2022-07-03 at 13 00 01" src="https://user-images.githubusercontent.com/28393339/177034705-0409abe2-d0db-497d-bd05-631fb5f29e25.png">

How can I solve the problem?

**Comment by eitsupi** [comment]
Some discussion about this already exists.
Please check https://github.com/quarto-dev/quarto-cli/discussions/782#discussioncomment-2669864
