### ISSUE TITLE
twittercard override seems not work

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#1444]
### Bug description

Hi,
in [my yaml](https://github.com/ondata/consultazione-linee-guida-open-data/blob/main/_quarto.yml#L29=) I have 

```
title: "#datiBeneComune per le Linee Guida Open Data"
```

In the rendered site instead I have

```
<meta name="twitter:title" content="#datiBeneComune per le Linee Guida Open Data - I commenti di #datiBeneComune alle Linee Guida Open Data">
```

This last is the title of the page, then the yaml config does not override it.

### `quarto tools check` Output

```bash
Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.07
```

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.28
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: /usr/bin/python3
      Jupyter: 4.10.0
      Kernels: bash, python3, zsh

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.0.4
      Path: /usr/lib/R
      LibPaths:
        - /home/aborruso/R/x86_64-pc-linux-gnu-library/4.0
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.13

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by dragonstyle** [comment]
I can confirm that the Twitter/OpenGraph overrides are not working properly. We have a post processor that is overwriting the value rather than respecting the declared value.

The following needs to be updated to respect the specified name values. 
```
['meta[property="og:title"]', 'meta[name="twitter:title"]'].forEach(
    (sel) => {
      const metaEl = doc.querySelector(sel);
      if (metaEl) {
        metaEl.setAttribute("content", renderedEl.innerText);
      }
    },
  );
```
