### ISSUE TITLE
[FR] Ability to hide footer on specific slides including title-slide

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#1445]
### Bug description

This relates to discussion in https://github.com/quarto-dev/quarto-cli/discussions/825 and comment in https://github.com/quarto-dev/quarto-cli/issues/1391#issuecomment-1186148935

When a custom footer is set to 
````yaml
format: 
  revealjs:
    footer: Custom footer
````

It is possible to hide it on a specific slide using the trick of inserting an empty slide footer

````
# Slide 2

content 

::: footer
:::
````

However, this does not work on first slide at first
````markdown
---
format: 
  revealjs:
    footer: Custom footer
---

# Slide 1 

content

::: footer
:::

# Slide 2

content 
````

This is because the feature (or free riding feature) rely on the per side footer overwrite using a `slidechanged` event which does not happen when presentation is loaded first time
https://github.com/quarto-dev/quarto-cli/blob/763b0ed7f060b206ef9b3a247612126b5f2f1f2a/src/resources/formats/revealjs/plugins/support/support.js#L117-L133

This means that in the example above if you go to slide 2 then back to slide 1, it will hide the footer. 

Hiding footer on title slide can be useful when you want to do a custom one like in https://github.com/quarto-dev/quarto-cli/issues/1391#issuecomment-1186148935 example (https://github.com/giabaio/quarto-slides/blob/main/assets/title-slide.qmd)

Having a real mechanism to hide a footer (like adding `.no-footer` class on a slide maybe ?) would be a plus

**Comment by giabaio** [comment]
Thanks @cderv :+1:

**Comment by mcanouil** [comment]
FYI:
- Opened issue:
  - #1445
- Related discussions:
  - #557
  - #825
  - #4181
  - #5566

**Comment by mcanouil** [comment]
FYI

- to hide the slide menu button on title slide:

```yaml
include-after-body:
  - text: |
      <script type="text/javascript">
      Reveal.addEventListener('ready', (event) => {
        if (event.indexh === 0) {
          document.querySelector("div.slide-menu-button").style.display = "none";
        } else {
          document.querySelector("div.slide-menu-button").style.display = "block";
        }
      });
      Reveal.addEventListener('slidechanged', (event) => {
        if (event.indexh === 0) {
          document.querySelector("div.slide-menu-button").style.display = "none";
        } else {
          document.querySelector("div.slide-menu-button").style.display = "block";
        }
      });
      </script>
```

- to hide only the slide number on title slide

```scss
/*-- scss:rules --*/

.reveal .slide-number > a[href*='title-slide'] {
  display: none;
}
```

**Comment by paddyroddy** [comment]
For the slide number I had to do the following when using `slide-number: c`

```scss
.reveal .slide-number > a[href="#/"] {
  display: none;
}
```

**Comment by giabaio** [comment]
I *think* that the best way to deal with this is actually to modify the `title-slide.html` template partial, for instance to include something like
```
section [WHATEVER YOUR NORMAL OPTIONS ARE]  data-footer="false">
```
The key part is to add `data-footer="false"`, which is what would happen normally if, for any given page (apart from the title) you set 
```
## Slide title {footer="false"}
Slide text
```

Then, you can simply do
```
...
formats:
    revealjs:
      template-partials:
          - title-slide.html
...
```
in the `yml` file for your presentation and things should work perfectly (to remove the footer, at least). I believe some specific (but simple and effective) hack can work for other customisation of the title page...

**Comment by michael-l-AT** [comment]
```
format:
  revealjs:
    title-slide-attributes:
      data-footer: "false"
```

Did the trick for me to hide to footer on the first slide.

On normal slides this worked:
`## SLIDETITLE { footer="false"}`
