### ISSUE TITLE
Scrollbar keeps color when switching themes

### ISSUE THREAD

**Issue by dfalbel** [quarto-dev/quarto-cli#1455]
### Bug description

Switching the website theme is not triggering a change in the scrollbar color.

https://user-images.githubusercontent.com/4706822/179755369-406956c0-7d85-442a-aa6b-b789fa94b30f.mov

The problem only happens in Safari.

In a website project we have customized the navbar color using the scss variable `$navbar-bg` using different colors for light and the dark theme eg:

In the `_quarto.yml` we have: 

```
format:
  html:
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
```

`light.scss` and `dark.scss` both set the `$navbar-bg` with:

```
/*-- scss:defaults --*/

$navbar-bg: #e83e18; 
```

Here's a test repository that can be used to reproduce the issue: https://github.com/dfalbel/test-navbar 

### `quarto check` Output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.32
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.13 (Conda)
      Path: /Users/dfalbel/Library/r-miniconda/envs/r-reticulate/bin/python
      Jupyter: 4.10.0
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 16, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status                    Installed     Latest  
chromium     Not installed             ---           869685  
tinytex      External Installation     ---           v2022.07
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by dragonstyle** [comment]
(perhaps need to explicitly muck with scrollbar style on safari to force a repaint on toggle)
