### ISSUE TITLE
file-specific scss-file is not used after publishing on Netlify

### ISSUE THREAD

**Issue by AlbertRapp** [quarto-dev/quarto-cli#1478]
### Bug description

I am not sure if this is a Quarto problem or a Netlify problem. But I'm giving it a try here anyway:

On my blog's landing page, I want to add a bit of custom scss-code to this one specific page. I have done that by including

```
---
page-layout: full
header-includes: |
  <link href="index-styles.scss" rel="stylesheet">
---
```

in the YAML-header. This works out nicely when I render my blog within RStudio. But once I publish my blog on Netlify, the changes in `index-styles.scss` are ignored. But I've checked: The header of the landing page still includes `<link href="index-styles.scss" rel="stylesheet">`.

### RStudio version
"Prairie Trillium" Release (1db809b8, 2022-05-20) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Ubuntu version
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

### `quarto check` Output

[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/albert/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /home/albert/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

### `quarto tools check` Output

```bash
(|) Inspecting toolsCheck file:///home/albert/quarto-cli/src/resources/vendor/deno-land/x/puppeteer@9-0-2/mod.ts
[✓] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.07
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by dragonstyle** [comment]
I'm not sure what is in your `scss` file, but `scss` files are typically compiled into CSS before they're distributed (e.g. when you provide a `scss` file in our theme, we merge it with our internal `scss` files and compile that into css, then attach that css file to the page). 

If it is just standard CSS in that file, it's possible that the extension is confusing our resource detection? You could try renaming it to CSS, but in any event I would confirm the file is also being deployed to the server (not just being found locally).

**Comment by AlbertRapp** [comment]
The file can be found on the server. But indeed renaming the file to css worked. Thanks for the quick fix.
