### ISSUE TITLE
Blog listings page don't include a title's last word if it is written in {}

### ISSUE THREAD

**Issue by AlbertRapp** [quarto-dev/quarto-cli#1479]
### Bug description

This is a bit odd behavior: Brackets as in `{ggplot2}` are not rendered properly on a listings page if included in a title. But this only happens if a title ends with a word in brackets. I've tried escaping the brackets with `\` or `\\` but that did not help.

### Reprex
I've taken a standard default blog and tweaked a blog post's title a bit. You can find it in the following repo:
https://github.com/AlbertRapp/curly-brackets-blog-issue

### RStudio version

"Prairie Trillium" Release (1db809b8, 2022-05-20) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Ubuntu version

Distributor ID: Ubuntu
Description: Ubuntu 20.04.4 LTS
Release: 20.04
Codename: focal

### `quarto check` Output

[✓] Checking Quarto installation......OK
Version: 99.9.9
Path: /home/albert/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
Version: 3.8.10
Path: /usr/bin/python3
Jupyter: (None)

  Jupyter is not available in this Python installation.
  Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
Version: 4.2.1
Path: /usr/lib/R
LibPaths:
- /home/albert/R/x86_64-pc-linux-gnu-library/4.2
- /usr/local/lib/R/site-library
- /usr/lib/R/site-library
- /usr/lib/R/library
rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

### `quarto tools check` Output

```bash
(|) Inspecting toolsCheck file:///home/albert/quarto-cli/src/resources/vendor/deno-land/x/puppeteer@9-0-2/mod.ts
[✓] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.07
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by AlbertRapp** [comment]
Seems like my development version was not up to date. Even though, I specifically pulled the latest version, this issue still persisted. But installing v. 1.0.35 solved the problem :man_facepalming:

**Comment by dragonstyle** [comment]
We were likely parsing that title and treating what followed as attributes (e.g. `id`, `classes`, or `attributes`) - something we did fix not too long ago- glad this fixed it for you!
