### ISSUE TITLE
Small feature requests for editing blog posts

### ISSUE THREAD

**Issue by AlbertRapp** [quarto-dev/quarto-cli#1480]
Dear Quarto dev-team,

I've got a small feature requests that I hope are is correctly adressed here. Though, I am not sure if this is an issue with Quarto rather than RStudio. In any case, thanks for your amazing work. I really like working with Quarto.

## Save cookie preferences in RStudio

Is there a way to save the cookie preferences in RStudio? It is a tad annoying to close the pop-up window while editing (and re-rendering) a blog post.

**Comment by jjallaire** [comment]
Using the latest versions of Quarto and RStudio IDE (note a new release just came out a few days ago) I do not repro this problem (the listing page is not displayed in the viewer). This is for doing a normal "Render" in RStudio (which automatically kicks off the preview server in the background)

There isn't currently a mechanism for persisting those cookie preferences. You could run `quarto preview` entirely outside RStudio (from a system terminal) with a fixed port, and then just take advantage of the save on render behavior that preview outside of RStudio has by default (so never hit "Render" in RStudio, just save)

**Comment by AlbertRapp** [comment]
Thanks for the quick reply!

Yeah, sorry about the listing page viewing problem. For some reason, I thought my `git pull` updated me to the most recent dev version but then I noticed that filters don't work either. So, I updated manually to `1.0.35` and that fixed it (and I removed that part from my post).

Ah the idea with the terminal sounds great. I will try that out.
