### ISSUE TITLE
[Feature request] VSCode extension for Quarto

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-cli#149]
Do you have any plans to develop VSCode extension tailored for Quarto? Please correct me if I am wrong, but currently, users have to manually type required commands in terminal within VSCode.

Another idea is to support qmd files via [REditorSupport/vscode-R](https://github.com/REditorSupport/vscode-R).

**Comment by amichuda** [comment]
Hi! This is a really great software and thanks so much for working on it.

A quick way to add some nice rstudio-like functionality to this, and make it possible to run code directly from qmd files would be to push this pull request over the finish line which would allow you to have multiple code lenses in one file and have multiple ways of denoting code blocks for the python interactive window: https://github.com/microsoft/vscode-jupyter/pull/4876

I sadly don't have enough to finish it, but I think it would make a `quarto` workflow much more streamlined. Please message me if you want to talk further!

**Comment by jjallaire** [comment]
Thanks! Yes if that got merged it would indeed enable some pretty nice integration. 

We are hoping to do more work on VS Code integration soon so will keep an eye on that PR! (don't have time to work on it now unfortunately)

**Comment by joshhopkins** [comment]
This, together with `[[wikilinks]]` ([Foam](https://github.com/foambubble/foam), etc), would be incredible.

**Comment by gvelasq** [comment]
Would a VS Code extension for Quarto use the native [VS Code Notebook API](https://code.visualstudio.com/api/extension-guides/notebook) to work with .ipynb files, and if so, would Quarto use traditional Jupyter kernels to execute code in R, Python, etc.?

There is ongoing work to integrate R into VS Code notebooks at https://github.com/REditorSupport/vscode-R/pull/394, however it is not clear that there is a plan to adapt IRKernel for this purpose: https://github.com/IRkernel/IRkernel/issues/685

**Comment by jjallaire** [comment]
We have starting working on our VS Code extension. The current release is here: https://marketplace.visualstudio.com/items?itemName=quarto.quarto&ssr=false#overview

@amichuda, we've got Code Lens Run actions working using the `jupyter.execSelectionInteractiveCommand` (which now allows you to pass a string to execute arbitrary code in the interactive python console).
