### ISSUE TITLE
quarto publish netlify does not seem to work on my Windows 11 machine

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-cli#1490]
Not sure if this is a bug as I may be doing something wrong, so not creating an issue yet. Windows and RStudio info are copied at bottom.

Setup:
- I have an RStudio project with multiple subfolders for different elements of the project
- one subfolder is for a reveal.js presentation I am preparing 
- this subfolder has its own _quarto.yml file, and an index.qmd file with the presentation
- when I render the presentation subfolder it creates the presentation in a sub-subfolder called _site
- the presentation looks fine if I double-click its index.html file locally, or if I upload the _site folder to netlify.app manually

Issue:
- I am signed into my netlify account in Chrome, which is also my default browser
- (just to be safe, I repeated this signed into my netlify account in Edge, in case Windows did something to prevent Chrome being the proper default browser, but I get the same result)
- in RStudio, if I open a terminal and cd to the presentation subfolder and then enter in the terminal `quarto publish netlify` it asks me to authorize
- after entering "Y" it tries to do something, but all that happens is that it opens my "Documents" folder in Windows Explorer (i.e, in the file manager) and does not upload the site
- as an experiment, I then tried creating my own _publish.yml file with the proper site id and url. It then asks me if I want to update that site, and I say yes; it then asks for authorization to which I say yes; after which it again opens my Documents folder in Windows Explorer and does not upload the site

Is it possible that I am doing something wrong? Obviously it is not a major issue as I can upload the presentation _site folder manually, but it would be nice to do it with a one-line terminal command. Would appreciate advice. Many thanks.

Edition	Windows 11 Pro
Version	22H2
Installed on	‎5/‎13/‎2022
OS build	22622.436
Experience	Windows Feature Experience Pack 1000.22632.1000.0

RStudio 2022.07.1+551 "Spotted Wakerobin" Release (a1f594a0dbfd7d23a9ba3115277c474bd8642212, 2022-07-08) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**Comment by dragonstyle** [comment]
This should be fixed as of v1.0.36 Thank you!

**Comment by donboyd5** [comment]
Thank you so much. With v1.0.36, for me, the site now uploads but something seems to go wrong and it does not look like a presentation. For example, here is a screenshot of the presentation when I upload via `quarto publish netlify`:

![image](https://user-images.githubusercontent.com/6538392/180643881-5c78adb0-6fb2-4afc-83e3-f08f95df2c67.png)

And here is what the title slide should and does look like if I instead upload the _site folder manually, exactly as created by the `quarto publish netlify` terminal command, via the netlify interface:
![image](https://user-images.githubusercontent.com/6538392/180644096-1fa2dccc-fa43-4790-b17d-177d85a64776.png)

So it looks like the right files are being created when `quarto publish netlify` forces rendering of the site, but something seems to be amiss when it uploads the files (or perhaps in deployment, although I am not sure yet how to investigate that).

As a double-check, I also (1) deleted _site, (2) rendered the site via `quarto render` (which means it does not have the additional files robots.txt and sitemap.xml), and (3) published the site via `quarto publish netlify --no-render` but the same thing happens.

Many thanks for any further comments or adjustments.

**Comment by donboyd5** [comment]
Looks like quarto-1.0.37 fixed this. Thanks!

**Comment by samrit2442** [comment]
I am still facing the same issue.

**Comment by cderv** [comment]
@samrit2442 can you open a new issue with some fresh information of the version you are running and the error you are encountering. This issue pre date v1 release, v1.1 is now out, and 1.2 has a lot of bug fix already. 

Having a new issue to look into and discussion is necessary. Thank you very much !

**Comment by samrit2442** [comment]
@cderv I posted this issue before upgrading Quarto to its latest version. Now, it is fixed. Thanks for the heads up.
