### ISSUE TITLE
Teach reticulate to understand IPython methods

### ISSUE THREAD

**Issue by srvanderplas** [quarto-dev/quarto-cli#1501]
### Bug description

Computationally generated tables from python do not display properly in HTML.

Minimal qmd file:
````md
---
title: "Untitled"
---

## Quarto

```{python}
#| label: tbl-planets
#| tbl-cap: Planets

from IPython.display import Markdown
from tabulate import tabulate
table = [["Sun",696000,1989100000],
         ["Earth",6371,5973.6],
         ["Moon",1737,73.5],
         ["Mars",3390,641.85]]
Markdown(tabulate(
  table, 
  headers=["Planet","R (km)", "mass (x 10^29 kg)"],
  tablefmt="pipe"
))
```
````

Produces this output: 
![image](https://user-images.githubusercontent.com/2127125/180488133-8a071947-11f7-44dc-9bcc-c1b74800d979.png)

Job output:
```bash

/bin/bash: /home/susan/.local/share/r-miniconda/envs/r-reticulate/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/bin/bash: /home/susan/.local/share/r-miniconda/envs/r-reticulate/lib/libtinfo.so.6: no version information available (required by /bin/bash)


processing file: test.qmd
  |.......................                                               |  33%
  ordinary text without R code

  |...............................................                       |  67%
label: tbl-planets (with options) 
List of 3
 $ engine             : chr "python"
 $ original.params.src: chr "python"
 $ chunk.echo         : logi FALSE

  |......................................................................| 100%
  ordinary text without R code


output file: test.knit.md

pandoc 
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Untitled
  
Output created: test.html

Watching files for changes
Browse at http://localhost:5844/
```

Rstudio version information: First tried on 
```
RStudio
2022.02.3 Build 492
© 2009-2022 RStudio, PBC
"Prairie Trillium" Release (1db809b8, 2022-05-20) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```
but also holds when I upgrade to the latest preview release:
```
RStudio
2022.07.0 Build 548
© 2009-2022 RStudio, PBC
"Spotted Wakerobin" Release (34ea3031, 2022-07-06) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

OS information: Ubuntu 21.10

### `quarto check` Output

```bash
(base) susan@Ralph:~/Projects/test$ quarto check

[✓] Checking Quarto installation......OK
      Version: 1.0.35
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.13 (Conda)
      Path: /home/susan/.local/share/r-miniconda/envs/r-reticulate/bin/python
      Jupyter: 4.11.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /home/susan/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
(base) susan@Ralph:~/Projects/test$ quarto tools check
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.07
```

### Checklist

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Thanks for the report! That's strange: I can't reproduce it locally:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/285675/180496221-ea2a1d5a-4f4a-4556-ade1-8819370c9f5f.png">

**Comment by cscheid** [comment]
Interesting. From the output of `quarto render` you shared, it looks like your rendering process is going through knitr and reticulate instead of Jupyter. I don't know why that's happening on a document with only `python` cells, but it shouldn't! Can you try adding

```yaml
jupyter: python3
```

to your front matter to tell quarto explicitly about Jupyter?

**Comment by srvanderplas** [comment]
On the bright side that means I might get it working at home 🙂. Is there
any additional information I can give you to help you narrow it down?

**Comment by srvanderplas** [comment]
I take it back... logged into the rstudio server on my home machine and I
get the same thing there.

**Comment by cscheid** [comment]
Just to confirm, the same issue happens with `jupyter: python3` in your yaml front matter on your home machine?

**Comment by cderv** [comment]
Also, is there by any change any `_quarto.yml` file that could change the behavior of the render ? Or simple document with only default YAML header ?

**Comment by srvanderplas** [comment]
Changing the engine to jupyter: python3 fixes the issue on both my work and
home machines. Unfortunately, this is a reprex; the application I actually
need this functionality in is a quarto book that uses knitr's engine
because it's a book for a course on R and python. So if there's any way to
get this working with the knitr engine and piping python through
reticulate, that would be ideal so that I don't have to create everything
in R just to output it.

**Comment by cderv** [comment]
> is a quarto book that uses knitr's engine
because it's a book for a course on R and python.

Did you set `engine: knitr` globally then ? just to check as that would explain the behavior. 

> So if there's any way to get this working with the knitr engine and piping python through reticulate, that would be ideal so that I don't have to create everything in R just to output it.

It is not clear to me if you are looking to get some document using Jupyter computation engine with Quarto or only document using knitr. With quarto you should be able to mix both. 

* Using **knitr** with reticulate for single document that uses R and Python chunks
* Using Jupyter engine for single document that uses Python only 

Quarto book project should handle the produced outputs correctly. Did you try that already ?

**Comment by cscheid** [comment]
> So if there's any way to get this working with the knitr engine and piping python through reticulate, that would be ideal so that I don't have to create everything in R just to output it.

If you add `#| output: asis` to the `{python}` cell,  and `print()` the output of the `tabulate()` call, I think that should work.

**Comment by srvanderplas** [comment]
Yes, I have tried the quarto book project (without engine:knitr set
globally) and the same behavior appears. Here's the zip file demonstrating
the issue. When the R chunk is removed from index.qmd, things work fine
(presumably because the jupyter engine is used), but as soon as the R chunk
is added, the behavior reappears.

[image: image.png]
(I did modify the R code in the screenshot to only show the first 6 rows).

I would like to be able to output markup from python chunks in the same way
that I output markup from R chunks and have both work within the same
document.

**Comment by cscheid** [comment]
I think the real bug here is that we should detect try to detect the usage of Jupyter print methods in a knitr/reticulate setting, and adjust as best we can. Otherwise our behavior is inconsistent and hard to track down...

**Comment by cderv** [comment]
Wouldn't that be the role of **reticulate** to handle the Python code correctly ? 

It may not be the only differences that we'll fine between python code that goes in Jupyter code cells, and what works in python chunk for reticulate. 

But I am no python expert, so maybe there is no such things except the printing issue.

**Comment by cscheid** [comment]
The problem is the interaction between reticulate and knitr and the way that output methods should be interpreted.

My point more generally is that _quarto_ is making the decision to use reticulate in the presence of knitr engine and `python` chunks, and "plain" jupyter when the engine is jupyter. This is confusing for users (hence the present issue) and we should attempt to improve the situation.

**Comment by cscheid** [comment]
(note that this is no longer a quarto issue, but a reticulate issue. We still should fix it because the pain manifests in quarto.)

**Comment by cscheid** [comment]
As of the latest `main` on `reticulate`, this should now work: https://github.com/rstudio/reticulate/pull/1256#event-7151375375. If you need it to work right away, I think `install_github` should do the trick. Otherwise, the next release of `reticulate` will have this fix.
