### ISSUE TITLE
[Feature Request] Quarto Extensions Library

### ISSUE THREAD

**Issue by noah-silver** [quarto-dev/quarto-cli#1523]
Hello! 

I love using Quarto and I am constantly amazed by the new features I discover daily. In the interest of advancing open source features, would it be possible to create a library on the Quarto website (or elsewhere) of user-generated Quarto extensions and shortcodes? Currently, it seems the only way to find user-generated extensions is to search around GitHub and hope developers have tagged their projects accordingly. A centralized library would be great for discovering new open source content and inspiring additional projects.

Thanks!

**Comment by mcanouil** [comment]
This as been resolved by the addition of a listing updated via PRs.
See <https://quarto.org/docs/extensions/>.

Additionally (and currently), extensions and formats are also listed (some overlap) on the GitHub Awesome Quarto list: https://github.com/mcanouil/awesome-quarto#extensions
