### ISSUE TITLE
Git hangs on preparing worktree with `quarto publish gh-pages` on windows

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#1524]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1509

<div type='discussions-op-text'>

<sup>Originally posted by **jmgirard** July 23, 2022</sup>
Sometimes when I run `quarto publish gh-pages`, it hangs (i.e., gets stuck) on "Preparing worktree."

     * branch            gh-pages   -> FETCH_HEAD
    Rendering for publish:
    
    ...

    branch 'gh-pages' set up to track 'origin/gh-pages'.
    HEAD is now at 2054a64 Built site for gh-pages
    Preparing worktree (resetting branch 'gh-pages'; was at 2054a64)

Any ideas how to troubleshoot, fix, or prevent this?</div>

**Comment by cderv** [comment]
I encounter the same issue in Windows 11 also. Still looking into different scenario to understand the issue. Git commands on their own (outside of Deno / Quarto) are working fine.

**Comment by sureshlazaruspaul** [comment]
I encounter the same issue. 

 `branch 'gh-pages' set up to track 'origin/gh-pages'.
HEAD is now at f73577d Initializing gh-pages branch
Preparing worktree (resetting branch 'gh-pages'; was at f73577d)`

First I thought it was congestion that is slowing down the deployment. But I tried it at different times and encounter the same problem.

**Comment by paniterka** [comment]
@jjallaire @cderv I was able to isolate some scenarios where small changes to the content of `posts/` were causing the command `quarto publish gh-pages` to work correctly vs incorrectly in a reproducible way. The repo with examples is here: https://github.com/paniterka/quarto_debug and the description here: https://github.com/quarto-dev/quarto-cli/discussions/1509#discussioncomment-3409564

**Comment by jjallaire** [comment]
Moving this issue to v1.1 (and have updated the docs to emphasize publishing from `docs` which will definitely work on Windows: https://quarto.org/docs/publishing/github-pages.html#render-to-docs)

**Comment by cderv** [comment]
Update on this: I cannot reproduce anymore this issue, even using the great repo example from @paniterka 

What I did: I updated [Git For Windows](https://gitforwindows.org/) to latest version 
````
> git --version
git version 2.37.3.windows.
````

I am also using latest pre-release  of Quarto for the test  (v1.2.105)

Can anyone confirm that doing the update also solve the issue ?

**Comment by paniterka** [comment]
Great to hear! Only updating git to 2.37.3.windows.1 didn't solve it for me. I am using Quarto 1.1.245, so I'm looking forward to the official release of 1.2 :)

**Comment by cderv** [comment]
You can try 1.2 already by downloading at this page: https://quarto.org/docs/download/

It would be useful if you could try as if it does not work for you, I'll need to still look into it and reproduce again so that we can bring a fix in 1.2. Thank you!

**Comment by paniterka** [comment]
@cderv I updated quarto to 1.2.157 and I'm happy to share it works for me now! 🎉 thank you for fixing this!

**Comment by cderv** [comment]
Awesome. I'll close for now then as it works for me and it works for you. We'll reopen if someone else as the issue.
