### ISSUE TITLE
[Quarto Extension] Base preview/serve URL on `VSCODE_PROXY_URI` if existent

### ISSUE THREAD

**Issue by benz0li** [quarto-dev/quarto-cli#1542]
[code-server](https://github.com/coder/code-server) [sets environment variable VSCODE_PROXY_URI](https://github.com/coder/code-server/issues/1510).

**Comment by benz0li** [comment]
Running code-server on Jupyter at e.g. https://jupyter.b-data.ch, `VSCODE_PROXY_URI` environment variable equals `https://jupyter.b-data.ch/user/benz0li/code-server/proxy/{{port}}` for my account.  
👉 Simply replace `{{port}}` with the actual port.

---

I am currently testing the Quarto extension at https://vscode-r.jupyter.b-data.ch with image `Julia (base:test-quarto) + code-server`.  
ℹ️ @jjallaire You may login there, too, as I have whitelisted your GitHub account for this deployment.

---

P.S.: The [R extension](https://github.com/REditorSupport/vscode-R) also [supports VSCODE_PROXY_URI](https://github.com/REditorSupport/vscode-R/pull/803).

**Comment by benz0li** [comment]
@jjallaire You may also build the docker image yourself with this [Dockerfile](https://github.com/quarto-dev/quarto-cli/files/9207078/Dockerfile.txt).  
ℹ️ Run it like the official Jupyter docker images: https://github.com/jupyter/docker-stacks#quick-start

**Comment by jjallaire** [comment]
@benz0li thanks for the heads up on this. Here is my attempt to code for it: https://github.com/quarto-dev/quarto-cli/commit/c6fd56418bdf5bd3c95636946619e4e3ef548fd4

I think the best approach to making sure have this right is if you install the development version of Quarto on the server (https://github.com/quarto-dev/quarto-cli#development-version) and try it out. If it doesn't work this is the code that is trying to make it happen: https://github.com/quarto-dev/quarto-cli/blob/main/src/command/render/render-shared.ts#L181-L185. If you need to tweak this LMK and I'll update accordingly.

**Comment by benz0li** [comment]
I have tweaked as follows

```diff
diff --git a/src/command/render/render-shared.ts b/src/command/render/render-shared.ts
index 1813a18d2..2af88065e 100644
--- a/src/command/render/render-shared.ts
+++ b/src/command/render/render-shared.ts
@@ -162,7 +162,11 @@ export async function printBrowsePreviewMessage(
   port: number,
   path: string,
 ) {
-  if (isJupyterHubServer()) {
+  if (isVSCodeTerminal() && isVSCodeServer()) {
+    const browseUrl = vsCodeServerProxyUri()!.replace("{{port}}", `${port}`) +
+      "/" + path;
+    info(`\nBrowse at ${browseUrl}`, { format: colors.green });
+  } else if (isJupyterHubServer()) {
     const httpReferrer = `${
       jupyterHubHttpReferrer() || "<jupyterhub-server-url>/"
     }user/${jupyterHubUser()}/`;
@@ -178,10 +182,6 @@ export async function printBrowsePreviewMessage(
     const url = await rswURL(port, path);
     info(`\nPreview server: ${previewURL(host, port, path = "")}`);
     info(`\nBrowse at ${url}`, { format: colors.green });
-  } else if (isVSCodeTerminal() && isVSCodeServer()) {
-    const browseUrl = vsCodeServerProxyUri()!.replace("{{port}}", `${port}`) +
-      "/" + path;
-    info(`\nBrowse at ${browseUrl}`, { format: colors.green });
   } else {
     const url = previewURL(host, port, path);
     if (!isRStudioServer()) {
```

in order to make it work for code-server behind jupyter-server-proxy, too.

Successfully tested at https://vscode-r.jupyter.b-data.ch with [temporary] image `Julia (pubtools:test) + code-server` both in JupyterLab Terminal and code-server Terminal.

**Comment by jjallaire** [comment]
Thanks! Patch applied here: https://github.com/quarto-dev/quarto-cli/commit/bc41cdbf33f9227a77f66f5089cb54be7ad40d66
