### ISSUE TITLE
"TypeError: Plot.dodgeX is not a function" using Plot.dodgeX in quarto

### ISSUE THREAD

**Issue by stuvjordan-uroc** [quarto-dev/quarto-cli#1553]
### Bug description

Trying to use Plot.dodgeX in a ojs cell and getting the following error when I render to HTML:

![image](https://user-images.githubusercontent.com/78857503/181372675-80672b52-5496-4e87-bb11-b954b8b5c90d.png)

Here's a simple example that produces the error when I render:
```{ojs}
testd = [
    {
        n: "bob",
        y: "1",
        c: "a"
    },
    {
        n: "bob",
        y: "2",
        c: "b"
    },
    {
        n: "jane",
        y: "3",
        c: "a"
    },
    {
        n: "jane",
        y: "0",
        c: "b"
    },
]
```
```{ojs}
Plot.plot({
    facet: {
        data: testd,
        x: "c",
    },
    marks: [
        Plot.frame(),
        Plot.dotY(
            testd,
            Plot.dodgeX({
                y: "y",
                fill: "n",
                anchor: "middle"
            })
        )
    ]
})
```

Running exact same cells in an Observable notebook produces the expected plot:
![untitled](https://user-images.githubusercontent.com/78857503/181372567-c39ee546-60cc-4931-8df8-f51e0a5031bf.png)

Note I tried to upload the example in a .qmd file but github says it does not support uploads with that extension!

I'm running Windows 10 Enterprise

### `quarto check` Output

```bash
[>] Checking Quarto installation......OK
      Version: 1.0.36
      Path: C:\Users\sjordan\AppData\Local\Programs\Quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: C:/Python310/python.exe
      Jupyter: 4.11.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/PROGRA~1/R/R-42~1.0
      LibPaths:
        - C:/Users/sjordan/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.0/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685
tinytex      Not installed     v2022.07      v2022.07
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by stuvjordan-uroc** [comment]
Thank you!  Should I close this then?

**Comment by cscheid** [comment]
This is fine, thank you.
