### ISSUE TITLE
Can I use multiple languages in the same notebook?

### ISSUE THREAD

**Issue by gdkrmr** [quarto-dev/quarto-cli#1557]
For now you have to choose a single kernel, right? I think running multi-language notebooks would be great. E.g. I use a lot of Julia but still do most of my plotting in R.

There are different possibilities, e.g. using multiple kernels (R, Julia, Python) to run their respective cells or alternatively using thing like Julia RCall [1] to run `{r}` cells or PyCall [2] to run `{python}` cells. The second option would make it much easier to pass objects between different languages.

[1] https://github.com/JuliaInterop/RCall.jl
[2] https://github.com/JuliaPy/PyCall.jl

**Comment by eitsupi** [comment]
This is not possible with the jupyter engine, but I believe it is with the knitr engine.
Of course, to use this feature, it is necessary to install R and knitr and the corresponding R packages.

https://bookdown.org/yihui/rmarkdown/language-engines.html
