### ISSUE TITLE
UTF-8 Characters not rendering properly in latex output

### ISSUE THREAD

**Issue by abudden** [quarto-dev/quarto-cli#1559]
### Bug description

I've got a Jupyterlab notebook that I'm using to write a report.  It uses greek letters (in particular μ).  These show up correctly in JupyterLab (and also in the ipynb file if I open it in an editor using utf-8 encoding).  However, when quarto converts to a PDF, the μ character is missing (it appears as a blank) and if I set `keep-tex: true`, the (seemingly utf-8 encoded) `.tex` file includes a different character in place of the μ: ¿.

I can work round it with things like `$\mu$`, although that puts the μ in italics (even if I use `\mathrm`), which is undesirable.

I've attached a very simple `.ipynb` file, along with the generated `.tex` and `.pdf` files that are produced when running `quarto render MuTest.ipynb`.

[MuTest.zip](https://github.com/quarto-dev/quarto-cli/files/9208642/MuTest.zip)

I am using Windows 10.  I am not using R at all, so haven't ticked the checklist box associated with RStudio.

### `quarto check` Output

```bash
> quarto check

[>] Checking Quarto installation......OK
      Version: 1.0.37
      Path: C:\Users\ab141979\AppData\Local\Programs\Quarto\bin\
      CodePage: unknown

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.7 (Conda)
      Path: c:/applications/development/languages/python/python.exe
      Jupyter: 4.9.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### `quarto tools check` Output

```bash
> quarto tools check
(|) Reading Tool DataSending fatal alert BadCertificate
[>] Reading Tool Data
ERROR: TypeError: error sending request for url (https://api.github.com/repos/yihui/tinytex-releases/releases/latest): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```

(this is probably due to the corporate zscaler proxy, which replaces SSL certificates and generally makes things difficult...)

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- N/A documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by fuhrmanator** [comment]
I don't use Jupyter but I can reproduce the bad result by compiling your .tex using XeLaTeX.

The answer at https://tex.stackexchange.com/a/172423/17868 speaks of how to get UTF-8 to work in XeLaTeX. Perhaps you can "hack" around the problem by getting the following two lines in your final .tex (see `BEGIN hack` below):

```tex
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  %% BEGIN hack to get UTF-8 to work
  \usepackage{fontspec}
  \setmainfont[Ligatures=TeX]{Linux Libertine O}
  %% END hack to get UTF-8 to work
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
```

With this, I was able to get the mu:
![image](https://user-images.githubusercontent.com/7606540/181771806-45ce2998-0f9a-4fe8-8e3f-59630048591c.png)

Maybe in the metadata of your Jupyter document you can put:

```
format:
  pdf:
    header-includes: 
    - \usepackage{fontspec}
    - \setmainfont[Ligatures=TeX]{Linux Libertine O}
```

**Comment by abudden** [comment]
Thank you: that worked (after I installed the font and changed "Linux Libertine 0" to "Linux Libertine" - presumably an operating system difference).  It would be nice if this was included in the documentation somewhere as I can see it being a relatively common requirement to include unicode symbols in a document.

**Comment by fuhrmanator** [comment]
Glad it's working for you. This  solution works in your case because you specified `pdf-engine: xelatex`, but I think other environments will require other solutions (or the mu will just work without making any changes). I'm not sure what the best long-term solution is.

**Comment by dragonstyle** [comment]
Quarto defaults to xelatex when rendering PDFs largely to improve support for unicode characters. Of course, the font issue will persist in the sense that there is no guarantee that a given font will support a given character. I will leave this open to add a note regarding unicode characters and fonts in our PDF documentation!

**Comment by dragonstyle** [comment]
I've updated the documentation with a note about unicode character support here:

https://quarto.org/docs/output-formats/pdf-basics.html#unicode-characters

**Comment by alan-isaac** [comment]
> I've updated the documentation with a note about unicode character support here:
> https://quarto.org/docs/output-formats/pdf-basics.html#unicode-characters

Could you please explicitly address the box-drawing characters at that link? (Often needed when discussing code.) My understanding (?) was that Quarto's default monospace font used with lualatex was Courier New, which supports these glyphs, yet I did not see them rendered. So I checked and the monospace font used seems instead to be Latin Modern Mono, which apparently does not provide these glyphs. So I set monofont to "Courier New" and got the glyphs, but wow Courier New is very thin! So I switched to Consolas, which is better in some ways, but is perhaps aesthetically poor in given the surrounding text. Bottom line: even if it seems somewhat out of scope, it would really help ordinary users if these docs could suggest some good looking ways to get fuller Unicode support in both the main text and wherever monospace is needed. Imo, ordinary uses (i.e., not typographers) need reliable suggestions for producing good looking documents with Quarto.

**Comment by mcanouil** [comment]
@alan-isaac This is an almost 4 years old issue. Could you please not resurrect old issues? Instead open a documentation issue. Thank you! Note that you can also contribute PRs.
