### ISSUE TITLE
ERROR: API Error: 429 (Too Many Requests)

### ISSUE THREAD

**Issue by eliason-j** [quarto-dev/quarto-cli#1577]
### Bug description

I am having problems publishing Quarto documents to Quarto Pub. After creating a basic Quarto website and authenticating my account through the command line, I was able to successfully publish website content to my quartopub.org domain. However, having successfully published a website, I wanted to next attempt publishing a standalone document. I used the RStudio UI (`File > New File > Quarto Document...`) to create a basic Quarto document. I then tried to publish using `quarto publish quarto-pub document.qmd` but it returned the command line error: `ERROR: API Error: 429 (Too Many Requests)`. 

**All subsequent efforts to use `quarto publish ...` in the command line, regardless of the file type, have resulted in the same message.** To summarize: I was able to publish a toy example once using the command line, but have not been able to successfully do so again even when using the same procedure.

RStudio: `"Spotted Wakerobin" Release (7872775e, 2022-07-22) for macOS`
OS: `macOS Monterrey 12.4`

### `quarto check` Output

```
[✓] Checking Quarto installation......OK
      Version: 1.0.37
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.7 (Conda)
      Path: /Users/jacobeliason/opt/anaconda3/bin/python
      Jupyter: 4.8.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.1/Resources/library
      rmarkdown: 2.12

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.07
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
I am seeing this as well. We'll follow up w/ our back-end publishing provider to resolve ASAP.

**Comment by eliason-j** [comment]
Thanks for such a quick response!

An update: I tried the same steps again just now and was able to publish without issue! I don't know any more about what caused the issue in the first place, but it doesn't seem to be active now.

**Comment by jjallaire** [comment]
Yes, we were able to resolve the issue! Thanks for reporting.
