### ISSUE TITLE
lst-label and lst-cap do not produce listing caption and reference

### ISSUE THREAD

**Issue by alex-vinogradov** [quarto-dev/quarto-cli#1580]
### Bug description

Quarto version: 1.0.37
OS: Windows 10
RStudio: 2022.07.0 Build 548
---
title: "Listing"
author: "Alex"
format: html
---

Listing caption is missing:

```{r}
#| lst-label: lst-first
#| label: lst-second
#| lst-cap: "This is a caption for code listing"

summary(cars)
```

Unable to resolve crossref @lst-first

Unable to resolve crossref @lst-second

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [ ] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by dragonstyle** [comment]
This currently works for display code blocks (e.g. https://quarto.org/docs/authoring/cross-references.html#code-listings ) but doesn't work for executable code cells. We'll take a look at this soon - thank you fore reporting!

**Comment by AmeliaMN** [comment]
In the interim, can you update the documentation to make it clear that this only works for display code blocks? On both the page you linked and the separate knitr page that is not at all clear: https://quarto.org/docs/reference/cells/cells-knitr.html#code-output

**Comment by cscheid** [comment]
@AmeliaMN I did [just that](https://github.com/quarto-dev/quarto-web/commit/3e1c13226cbbd8a90514e182c8ed4bf87132d0df). Thanks for the suggestion!

**Comment by mcanouil** [comment]
Both `lst-cap` and `lst-label` are still listed in computation reference pages which is really confusion since it does not work at the moment.

Here is a workaround using `knitr` as the engine:

````qmd
---
title: "Quarto Playground"
format: html
---

This is a playground for Quarto.

```{r}
#| attr-source: "id=lst-code lst-cap='Some code'"
1 + 1
```

See @lst-code.
````

Note that `attributes` (#5587) could possibly help doing this also when using Jupyter.

**Comment by cscheid** [comment]
@mcanouil Can you point out where they appear in the documentation today?

**Comment by mcanouil** [comment]
In:
- https://quarto.org/docs/reference/cells/cells-jupyter.html#code-output
- https://quarto.org/docs/reference/cells/cells-knitr.html#code-output
- https://quarto.org/docs/reference/cells/cells-ojs.html#code-output

**Comment by cscheid** [comment]
Thank you -

the proper fix here is really for us to support these in executable cells. It might be possible in the new crossref system.

**Comment by cscheid** [comment]
I thought the problem was in our lua filter chain. But if it can be solved in the `rmd/*.R` subsystem that's even better, so I'm going to assign this to you. ok?

**Comment by mcanouil** [comment]
It's nice to solve it in R, but would this also work for other languages as documented?

**Comment by cscheid** [comment]
> It's nice to fix this in R, but would this also work for other languages as documented?

That's a very good point.

**Comment by cderv** [comment]
yes it would be the same type of fix. All our computation handler are assigning `lst-cap` from code chunk to `caption=` attributes. 

* R
  https://github.com/quarto-dev/quarto-cli/blob/7c2cf4928c976995fb299c18dfce32c769ae35d4/src/resources/rmd/hooks.R#L363-L370

* Jupyter
  https://github.com/quarto-dev/quarto-cli/blob/68ade797ab6997851380c455d6078413d02b5efd/src/core/jupyter/jupyter.ts#L1328-L1330

* OJS
  https://github.com/quarto-dev/quarto-cli/blob/6de87b5ed60b9af78c06b4bf9f40f992c4c8a3f3/src/core/observable/compile.ts#L310-L312

* Basic handler
   https://github.com/quarto-dev/quarto-cli/blob/31e987baae7e1cdc7d785d5501c7bffb6b872f35/src/core/handlers/base.ts#L530-L532


However, our new Lua filter processing using `lst-cap` only as attribute for listings
https://github.com/quarto-dev/quarto-cli/blob/68ade797ab6997851380c455d6078413d02b5efd/src/resources/filters/customnodes/decoratedcodeblock.lua#L26-L28
https://github.com/quarto-dev/quarto-cli/blob/68ade797ab6997851380c455d6078413d02b5efd/src/resources/filters/crossref/listings.lua#L17
https://github.com/quarto-dev/quarto-cli/blob/68ade797ab6997851380c455d6078413d02b5efd/src/resources/filters/crossref/listings.lua#L37


So it seems the rule we expect for listings is 

* Codeblock with id `lst-*` are supposed to be listings
* If so, then caption listing is supposed to be found in `lst-cap`

Is that so ? 

I really don't know why all our handler are setting `caption=` when finding `lst-cap` on a Codeblock. Is it safe to change the handler part and not adapt in Lua ?

**Comment by cderv** [comment]
PR sent, we'll see the checks, and I will add tests for those later as I need to end day right now.

**Comment by cderv** [comment]
Just a note that this will now be handled as part of this
* https://github.com/quarto-dev/quarto-cli/issues/4944

Code Listing will be possible for executable code chunk.

**Comment by cscheid** [comment]
This is now fixed on `main` 🎉
