### ISSUE TITLE
FR: add source/output attributes/class option to code blocks

### ISSUE THREAD

**Issue by mivalek** [quarto-dev/quarto-cli#1581]
I don't think this is currently possible in Quarto but it would be great if there were code block options to add HTML attributes to code blocks and code block output similar to knitr's `class.source`, `class.output` or `attr.source`, `attr.output`.

**Comment by cderv** [comment]
This should work - did you try already ? Do you have a reprex of a use case where it does not work ? 

```markdown
---
title: "Untitled"
format: html
keep-md: true
---

```{css, echo = FALSE}
pre.out {
  background-color: lightgreen;
}
pre.sourceCode.src {
  background-color: lightblue;
}
```


# Head 

```{r, class.output = "out", class.source = "src"}
1 + 1
```

````

![image](https://user-images.githubusercontent.com/6791940/181833513-6be557b4-c5cf-4f35-a6c7-8d52c0019319.png)

**Comment by jjallaire** [comment]
Yes you can also use this in YAML as with:

```markdown
```{r}
#| class-output: out
#| class-source: src
1 + 1
```
```

**Comment by mivalek** [comment]
Doesn't seem to work for hugo:


    ---
    title: "02 Test"
    date: 2022-07-29T22:54:22+01:00
    background: intro.jpg
    tags:
        - personal
    featured: false
    # for Quarto posts (must rename to .qmd)
    format: hugo
    jupyter: python3
    ---

    ```{python, class.output = "out", class.source = "src"}
    1+1
    ```

    ```{python}
    #| class-output: my-class
    #| source-output: foo
    1+1
    ```

rendered `.md`

    ``` python
    1+1
    ```

        2

    ``` python
    1+1
    ```

        2

**Comment by cderv** [comment]
First, those option are a **knitr** only features. You can find them on documentation in knitr cells reference page 
https://quarto.org/docs/reference/cells/cells-knitr.html

Also, **knitr** only support these option only on HTML  outputs where they make more sense . It is why it get ignored in Hugo markdown output which is markdown output.

Also sorry for being misleading on the syntax 
````
```{python, class.output = "out", class.source = "src"}
```` 

this is **knitr** notation only and the syntax to use if in-chunk YAML 
````
```{python}
#| class-output: my-class
#| source-output: foo
````
especially with other engine like Jupyter as you are trying to do.

BTW `source-output` is not a valid option either.

What is the targeted Hugo syntax ? Can you share what feature of Hugo Quarto should better support ?

**Comment by mivalek** [comment]
Thank you for the reply. Yes, I know the option exists in `knitr` but my request was for a feature that would allow to easily add HTML classes and other attributes to be added to code blocks and code output for any Quarto. I now realise that that might not be possible since Hugo's goldmark doesn't seem to have syntax for code blocks with classes/attributes.
So, as an alternative, would it be possible to make these options wrap code/output in `<div>`s with the given attribute? So, for instance:

    ```{python}
    #| attr-output: #some-id .my-class
    #| attr-source: .foo attr="value"
    1+1
    ```

in the `.qmd` file would get rendered to `.md` as

    <div class="foo" attr="value">
    ```python
    1+1
    ```
    </div>
    
    <div id="some-id" class="my-class">
    2
    </div>
    
At the moment I'm using a workaround

    :::{.class}
    ```{python}
    1+1
    ```
    :::
    
but the only way I know how to get different attributes for code and output is to use the very inelegant

    :::{.source-class}
    ```{python}
    #| eval: false
    1+1
    ```
    :::

    :::{.output-class}
    ```{python}
    #| echo: false
    1+1
    ```
    :::

**Comment by cderv** [comment]
> my request was for a feature that would allow to easily add HTML classes and other attributes to be added to code blocks and code output for any Quarto.

@mivalek thanks for the precision. This was not clear at first but now I understand that **knitr** feature would be useful in other context


@jjallaire how about considering support for `class.source` `class.output` `attr.source` `attr.output` equivalent in Quarto (not only available for knitr cells) ? Does it seem possible with other computation engine that you know better ?

**Comment by jjallaire** [comment]
This is definitely possible and something we should indeed probably support.

I believe that unknown YAML options are automatically added as as attributes so this could even be done now as a filter/extension (not 100% sure about this though)

**Comment by mivalek** [comment]
I'm glad you agree that this would be useful!

> this could even be done now as a filter/extension 

I've been thinking about writing such a filter but, while I think I might be able to write a basic one to wrap the source code in a `<div>`, I haven't been able to figure out how to do that for output (code block, figure, table...). If you could point me in the right direction, I'd have a go at it.

**Comment by cderv** [comment]
I added #2040 to track the idea then. I choose to create a new issue than reopen this one.
