### ISSUE TITLE
Using html tags in a quarto title document

### ISSUE THREAD

**Issue by adisarid** [quarto-dev/quarto-cli#1584]
### Bug description

The following document:

```
---
title: "<div style='zoom:75%;'>min-reprex</div>"
format: html
editor: visual
---
```

yields this warning:

```
pandoc 
  to: html
  output-file: quarto_bug_warning_reprex.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: '<div style=''zoom:75%;''>min-reprex</div>'
  editor: visual
  
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'quarto-input90370470' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
Output created: quarto_bug_warning_reprex.html
```

HTML tags in the `<h1>` title (within the <body>) are useful, for example, it makes it really easy to add an image above the title, and additional flexibilities of course.

However, quarto yields a warning (and also the html's title is influenced by quarto's behavior).

I suggest that quarto parse html tags and apply them in the body (as it currently does), but for the tab's title (the `<head><title>...</title></head>` use a parsed version without the html tags.

```
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

### `quarto check` Output

```bash
[>] Checking Quarto installation......OK
      Version: 1.0.36
      Path: C:\Program Files\RStudio\bin\quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/PROGRA~1/R/R-42~1.0
      LibPaths:
        - C:/Users/adisa/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.0/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[>] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.07
```

**Comment by cderv** [comment]
`title` will be set into `<title>` element on the HTML page. I don't think you can really add a `div` inside like `<div style='zoom:75%;'>min-reprex</div>`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title

This may be why Pandoc filter out the parsed `title` element and choose a default one. 

Using HTML tag works otherwise 
````markdown
---
title: "<em>min-reprex</em>"
format: html
---

# Content
````

Can you share more on your usage ?

**Comment by dragonstyle** [comment]
(We do strip the HTML out when using the text in the `title` tag AFAIK). I tested using a markdown span with zoom and no issues:

```
title: "[test]{style='zoom:75%;'}"
```

but I can also reproduce the warning when passing the raw HTML tags as in your example. It does appear that this causes some issue, hence the warning. I think it would be worth open an issue-  if the underlying error is something real that we think should be happening, it needs a better message. But more likely, I think there is likely some other underlying bug that is worth figuring out.

**Comment by cderv** [comment]
@dragonstyle several comments on that

* If the HTML tag were stripped, my example with `<em>` would have not lead to emphasize text right ? I don't think any stripping happen. 

*  BTW the issue happens outside of Quarto too with Pandoc only
````
---
title: "<div style='zoom:75%;'>min-reprex</div>"
---

content
````

```powershell
$ pandoc -t html -s -o test.html test.qmd
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'test2' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
````

Passing raw HTML with `<div>` will be parsed by Pandoc AST to Div as `native_divs` is activated. I am not sure Pandoc handles that correctly. But deactivating the extension does not help. 

* Using Spans in title seems better to me as in your working example. That is why I am wondering why using a `<div>` in a title element. We wouldn't express that into YAML using `:::` for fenced div inside `title:`

I don't see that as a bug in Quarto for now. But maybe I am missing something

**Comment by adisarid** [comment]
My use case is for adding a logo image above the title, like this:

```
---
title: "<div style='text-align:center;'><img src='sarid_logo.svg' width = '200'></div><br/>Some title here..."
author: "Adi Sarid"
format: 
  html:
    theme: materia
editor: visual
---
```

Which looks like this:

![image](https://user-images.githubusercontent.com/19262838/181861884-8dbde07a-f94c-47bf-9dd9-eab0d038d7b8.png)

**Comment by cderv** [comment]
I don't think adding a logo in the title block using a div can be done with Pandoc's `title` variable. I think you would need to create a custom format and tweak the title block partials to make that happens. More on this here: https://quarto.org/docs/journals/templates.html#html-partials
Still a bit advanced with not best documentation and example yet, but this is coming

However, not using a `div` and using a custom css rule would help you I think 

````markdown
---
title: |
  ![](https://quarto.org/quarto.png){width=200}<br>
  Adding a Logo to Title
format:
  html: 
    theme: style.scss
---

content

````
* `style.scss`
````scss
/*-- scss:defaults --*/

/*-- scss:rules --*/

h1.title {
  text-align: center;
}
````

![image](https://user-images.githubusercontent.com/6791940/182047114-84b914c0-e0e8-4e32-a511-7dd2b9a6e1a0.png)

**Comment by adisarid** [comment]
I will surely read more about customized templates - I had some in Rmd before moving to quarto and probably migrate them.

The suggestion for embedding the image via markdown tag instead of div yields the same warning message. I.e.:

```
output file: AllJobs_open_comments_analysis.knit.md

pandoc 
  to: html
  output-file: AllJobs_open_comments_analysis.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  editor: visual
  title: '![](sarid_logo.svg)<br>ניתוח נתוני הערות פתוחות - סקר לקוחות<hr>'
  
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'quarto-input688b303d' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
Output created: AllJobs_open_comments_analysis.html

Watching files for changes
AllJobs_open_comments_analysis.html
Browse at: p/4045b61a/AllJobs_open_comments_analysis.html
```

**Comment by EllaKaye** [comment]
Hello. Related to this, I think, is the question asked here: https://github.com/quarto-dev/quarto-cli/discussions/1736.

That use case is to try and recreate the attached logo in CSS and use it as the navbar title. @MayaGans has been incredibly helpful and got as far as figuring this out by styling a `<br>` tag in the title (i.e. `title: "ELLA<br>KAYE"`), but by putting the `<br>` in the title you see it in the tab name.

Any thoughts on ways around that, or other ways to achieve this goal?

Thanks!

By the way, achieving this does away (at least for me), with this: https://github.com/quarto-dev/quarto-cli/discussions/1647 (although I still reckon that feature would be useful for others).

![logo-white-background](https://user-images.githubusercontent.com/7222491/183471041-c60afdc7-387b-48fc-a23c-701df9c27246.png)

**Comment by EllaKaye** [comment]
Update: Question https://github.com/quarto-dev/quarto-cli/discussions/1736 has been answered, but turns out not to solve my original problem of trying to get html into the title in order to recreate my logo in CSS. @MayaGans came up with a hack for styling the `<br>` tag that works perfectly in Chrome but not in other browsers. I'm looking for something that works universally. I'd be grateful for any tips or suggestions. 

Failing this, I can go back to using .png images, but I was also hoping to animate the line, so would need CSS for that.

Thanks!

**Comment by EllaKaye** [comment]
Another update. With a further assist from @MayaGans, I've managed to recreate my logo with the following in `_quarto.yml`

```
website:
  title: "ELLA KAYE"
  navbar:
    title: "ELLA<span class='icon-line'></span>KAYE"
```

and this in the scss file:

```
.icon-line {
  display: block;
  background: $primary;
  width: 100%;
  height: 5px;
  margin: auto;
  display: table;
  margin-top: -4px;
  margin-bottom: -4px;
}
```

Setting the navbar title separately from the website title also avoids issues with the text that appears in browser tabs.

So, that's me sorted on this issue!

**Comment by dmkaplan2000** [comment]
I have identified this same issue, but the solution mentioned above by @EllaKaye would seem to only work if you are creating a full website, correct? I am creating a simple web page (`html` format), so I do not think this will work. The solution of creating a partial is viable, but seems like a pretty complicated way to get a banner image above the title...
