### ISSUE TITLE
Choose preview format?

### ISSUE THREAD

**Issue by githubpsyche** [quarto-dev/quarto-cli#159]
Documentation indicates you can use quarto preview for both HTML and PDF output of both books and individual documents. But how do you choose which, particularly when your YAML includes options for either format? Hard to find this guidance.

**Comment by githubpsyche** [comment]
Oh I see, I should parallel options from quarto render to choose preview format. Thanks for this product.

**Comment by jjallaire** [comment]
Thanks for the suggestion! Just added a note to the docs that spells this out how to do this more explicitly.

**Comment by githubpsyche** [comment]
A problem I'm having with this approach is that the live up

**Comment by githubpsyche** [comment]
A problem I'm having with this approach is that the live updating seems to only affect the default format for the document? For example, if default format is web and I want live preview for my pdf, `quarto preview notebook.ipynb --to pdf` generates a PDF but doesn't seem to trigger automatic updates. 

Maybe my OS though - am using Windows/miniconda or powershell terminal.

**Comment by jjallaire** [comment]
I am seeing the automatic updates work (on Windows w/ PSF Python in the default command shell but I don't see anything in the code that would suggest this wouldn't work or would work differently in another shell). Is there any more detail you can provide here that might yield a clue to the source of the problem?

**Comment by githubpsyche** [comment]
Okay, so this is with the template book project created when you call `quarto create-project mybook --type book` and then calling `quarto preview mybook --to pdf`.

For me, doing this opens a compiled PDF in my browser (Chrome) at `http://localhost:####/mybook.pdf`, but saving changes to one of the QMD files (e.g. `index.qmd`) neither triggers a recompilation of the PDF nor a refresh of my browser. When I leave from that link to just `http://localhost:####/`, the web version of the book is rendered, and whenever I save a change to a QMD file, the web project reloads and reflects the change.

Lately I suspect the problem might be my PDF engine? I already had latex installed before getting quarto, so I didn't get it via `quarto tools install tinytex`. When I run `quarto preview mybook --to pdf`, the logs mention pdflatex:

```
running pdflatex - 2
  This is pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2021/W32TeX) (preloaded format=pdflatex)
   restricted \write18 enabled.
  entering extended mode
```

Could test with the guided latex engine, but I'd rather not have multiple latex engines on my system // have to figure out how the guided one differs from my current one.

**Comment by jjallaire** [comment]
Ah, I see the issue. `quarto preview` for book projects currently only previews the web version of the book (so the behavior you are looking for isn't currently supported).

I think we need to either (a) Get this to work; or (b) Throw an error if you attempt to pass `--to pdf` for `quarto preview` of a book.

**Comment by githubpsyche** [comment]
Would be great if this could work! It looks like I've departed from the original purpose of this issue though, so I'll close and maybe make a separate one for the book pdf preview thing.

**Comment by jjallaire** [comment]
`quarto preview` now also supports PDF preview for book projects (on `main` and in the v0.2.247 release)
