### ISSUE TITLE
Add knitr and jupyter cells option in search 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#1592]
Currently some option cannot be found in search like `class-output` only available for knitr chunks. 

Those should be added, possibly with lower weight than main guide page results.

**Comment by cscheid** [comment]
The solution here is to add the actual yaml entries to the indices as we're building the documentation pages, since google can actually find that page: https://www.google.com/search?q=site%3Aquarto.org+%22class-output%22

**Comment by jjallaire** [comment]
Resolved here: https://github.com/quarto-dev/quarto-web/commit/3c30e3b3e10841165f19d2498703ce1c718e9e0b
