### ISSUE TITLE
Zotero metadata for automatic parsing of citation

### ISSUE THREAD

**Issue by dmi3kno** [quarto-dev/quarto-cli#1609]
In the [Creating Citeable Articles](https://quarto.org/docs/authoring/create-citeable-articles.html#google-scholar) the metadata compatible with Google Scholar is listed. The set of metadata tags accepted by Google Scholar is a subset of a more general open standard parsed by [Zotero](https://www.zotero.org/support/dev/exposing_metadata) based on Highwire vocabulary.  If metadata is done properly, Zotero browser plug-in will be able to generate proper record from the Quarto article.

I suggest we expand the list of metadata included in the `google-scholar` partial or add a new partial called `zotero`, which can include more fields (beyond the minimally required by Google Scholar).

### Google Scholar

| Tag | YAML source | Comment | 
| --- | --- | --- |
| citation_title | title | Document title |
| citation_author | author:name | Should be used for single author documents |
| citation_online_date | date | Online publication date |
| citation_fulltext_html_url | citation:URL | URL of the document |
|  citation_publication_date | date | Publication date - same as online date above? |
|  citation_journal_title | citation:container-title | Journal title | 
|  citation_reference | bibliography (parsed) | One entry per reference in bibliography | 

### Zotero
Everything above plus:

| Tag | Suggested YAML source | Comment | 
| --- | --- | --- |
| citation_editor | citation:editor | One entry per editor name, can be simplified to a single semicolon-separated string passed to citation_editors  |
| citation_date| citation:date | Date for the citation (not necessarily when it appeared online) |
| citation_cover_date| citation:publication_date | Date of publication (date of journal issue). Used by [Springer](https://forums.zotero.org/discussion/59197/springer-useing-first-online-instead-of-real-publication-date)  |
| citation_year | - | Can be automatically computed from one of the date fields |
| citation_journal_abbrev | citation:container-abbr | Correct abbreviation for the journal name |
| citation_book_title | citation:book-title | Name of the book where the paper appears |
| citation_inbook_title | citation:inbook-title | Name of the book where the paper appears |
| citation_firstpage | citation:first-page | First page number for the paper (in the journal issue) |
| citation_lastpage | citation:last-page | Last page number for the paper (in the journal issue) |
| citation_volume | citation:volume | Journal volume number |
| citation_issue | citation:issue | Journal issue number |
| citation_series_title | citation:series-title | Title of journal/book series |
| citation_publisher | citation:publisher | Name of the publisher |
| citation_doi | citation:doi | DOI, existing YAML field |
| citation_isbn | citation:isbn | ISBN |
| citation_issn | citation:issn | ISSN |
| citation_eIssn | citation:eissn | electronic ISSN |
| citation_pmid | citation:pmid | electronic PMID |
| citation_public_url | citation:public-url | URL for publicly available version, e.g. researchgame |
| citation_abstract_html_url | citation:abstract-url| URL for abstract (HTML version) |
| citation_fulltext_html_url | citation:fulltext-url | URL for full text of the paper in HTML format  |
| citation_abstract | abstract | Full text of abstract, existing YAML field  |
| citation_language | citation:language | Language abbreviation (EN, FR)  |
| citation_conference | citation:conference | Conference name  |
| citation_conference_title | citation:conference | Conference name, probably should be same as above  |
| citation_dissertation_institution | citation:institution | University (for theses and dissertations)  |
| citation_technical_report_institution | citation:institution |  Institution (for reports), not sure we can effectively distinguish in YAML  |
| citation_technical_report_number | citation:report-number |  Report number  |
| citation_pdf_url | citation:citation-pdf-url |  URL for PDF version of the paper. Will be used by Zotero to import the paper  |
| citation_keywords | keywords | Semi-colon separated keywords. Can probably be coalesced from existing YAML field  |

Some of these are not consequential and can probably be delayed, while others are more important (such as `citation_doi`, `citation_isbn` and `citation_pdf_url`) and should probably be added to google-scholar partial right away.

**Comment by dragonstyle** [comment]
Pre-release builds of Quarto should include functionality that addresses this. Thank you very much @dmi3kno for the suggestion and especially the extremely thorough and clear write up! I attempted to improve the documentation for metadata generation here as well:

https://quarto.org/docs/authoring/create-citeable-articles.html#citation-fields

**Comment by dmi3kno** [comment]
Well done. A couple of comments to documentation
- In Google Scholar section, it might be worthwhile to mention that meta tag for "citatation_reference" will be generated for every entry in the .bib file. Will it? I think that's what Google Scholar expects.
- The section [Citattion Fields](https://quarto.org/docs/authoring/create-citeable-articles.html#citation-fields) should be called "Other citation fields" as it extends the list of fields required by Google Scholar
- the YAML entry "type" deserves its own entry in the table with the exhaustive list of all supported options
- For YAML entries such as "author" it should be made clear - authors different from the document authors (including in different order) may be provided; multiple authors should be provided as the YAML list (? or as comma-separated string?). The same applies to the field "editor".
- For "issued" YAML entry, it is unclear when citation_cover_date, and citation_year will be populated
- For "url" entry, it is unclear which "site-url" option you are referring to. Might need to be more specific pointing (and href) to Quarto documentation
-  The option "abstract_url" looks strange/inconsistent in use of underscore, rather than dash. is there a reason for it?

It was also unclear how the specification "google-scholar: true" affects producing the (extended set of) metadata. Is it always required to be specified? What else needs to be done for all (beyond Google Scholar required) metadata tags to be generated?

Finally, it would be cool if the documentation page included the metadata tags for this help article as "inbook" or "technical report" so that Zotero owners could see the proper icon when browsing the documentation.

Some typos on the page:
"...you can omit the citation url and **simply** enable..."
"The following fields, when **specified under the `citattion` entry in document YAML** will generate scholarly meta tags..."

**Comment by dragonstyle** [comment]
Thanks for reviewing! I've updated the documentation to address the changes. In general, I just addressed the list with the following notes:

- 'Other Citation Fields'
I didn't rename 'Citation Fields' to 'Other Citation Fields' as this list represents a complete list of all fields (including Google Scholar fields) that may be produced.
- Our `site-url` documentation is pretty limited, but I linked to what exists for the time being. We need to do better here as that is now used by a number of features when synthesizing urls.
- `abstract_url` was merely a typo - ty!

Right now, all the metadata is emitted with no additional control other the value of `google-scholar` being true. 

I didn't follow this item:

> Finally, it would be cool if the documentation page included the metadata tags for this help article as "inbook" or "technical report" so that Zotero owners could see the proper icon when browsing the documentation.

Can you clarify what you mean?

**Comment by dmi3kno** [comment]
Ok. I did some more testing using this YAML. 
```YAML
---
title: "Summarizing Output for Reproducible Documents"
description: | 
  A summary of the best practices for summarizing output of reproducible scientific documents.
date: 5/4/2018
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation-url: https://example.com/spacelysprokets
keywords: bayesian, statistics
citation:
  type: article-journal
  container-title: "Journal of Data Science Software"
  doi: "10.23915/reprodocs.00010"
  url: https://example.com/summarizing-output
  #keywords: bayesian, statistics, citations
  issued: 2022-08-04
  available-date: 2022-08-08
  #pdf-url: https://dmi3kno.researchgate.org/mypaper.pdf
  language: es
  issue: 54
  volume: 2
  page-first: 42
  page-last: 43
  abstract-url: https://dmi3kno.github.com/myabstract/
  publisher: Springer Nature
  container-title-short: "JDSS"
  collection-title: Special editions on errors in software
google-scholar: true
---
```
Comments
- citation:keywords does not work(produces an error), but document keywords work fine. There should be a note to this effect (that only document keywords are expected not citation:keywords. Also keywords are comma-separated, not list!
- citation:pdf-url results in an error. If it is not implemented yet, there should be a note
- citation:lang is producing an error. The YAML option is called citation:language. Please correct the documentation
- citation:page-first and citation:page-last do not get translated into meta tags. Please check

This is the Zotero icon properly identifying the metadata ( whis white icon is what I would expect)
![Screenshot from 2022-08-09 09-42-30](https://user-images.githubusercontent.com/13419011/183594024-832d611c-1e07-4677-92b8-ab5c83f97685.png)

And here's the record I get in Zotero

![Screenshot from 2022-08-09 09-49-05](https://user-images.githubusercontent.com/13419011/183594569-e56d9fcc-9dc2-4b8f-9742-63a11c52786c.png)

I am generally very happy.

**Comment by dragonstyle** [comment]
Thank you- reopening so I can make these fixes in functionality / documentation...

**Comment by dragonstyle** [comment]
Great feedback...

> citation:keywords does not work(produces an error), but document keywords work fine. There should be a note to this effect (that only document keywords are expected not citation:keywords. Also keywords are comma-separated, not list!

Fixed, docs now correctly note that you may use `citation:keyword` as a string.

> citation:pdf-url results in an error. If it is not implemented yet, there should be a note

Fixed (no more error)

> citation:lang is producing an error. The YAML option is called citation:language. Please correct the documentation

Corrected documentation to note that it should be `language`

> citation:page-first and citation:page-last do not get translated into meta tags. Please check

Corrected- they are now functioning. Also added note that you may also choose to write `page` which will be parsed.

**Comment by dmi3kno** [comment]
Sorry about coming back to this issue. There's one bug related to how `google-scholar` YAML tag handles inline r code in `bibliography` field.

Due to the way I use Zotero I do in all of my documents:
```r
google-scholar: true
bibliography: "`r rbbt::bbt_write_bib('test2.bib', translator='bibtex', overwrite = TRUE)`"
```
This R expression parses the file for bibliography keys, fetches them from Zotero, writes them to file and returns the filepath.
Unfortunately this produces an error, unless I remove the `google-scholar: true`
```r
#> [WARNING] Could not deduce format from file extension .bib', translator='bibtex', overwrite = TRUE)`
#> Defaulting to markdown
```
But this works
```r
google-scholar: true
bibliography: "test2.bib"
```
Quarto evaluates the R expression in the field `bibliography` and works just fine, but your code for `google-scholar` tag attempts to read the file name verbatim without evaluating the `r` expression first. Could you please add the field evaluation as Quarto and Rmarkdown do?

**Comment by dragonstyle** [comment]
Your assessment is correct - towards the end of rendering we are reading the raw metadata value for bibliography. I will look into what it will take to use the computed value instead.
