### ISSUE TITLE
PDF output for Julia produces raster instead of vector graphics for plots

### ISSUE THREAD

**Issue by alonsoC1s** [quarto-dev/quarto-cli#1614]
### Bug description

When using Julia and rendering to PDF the figures in the final PDF are raster images instead of the vector graphics that R and Python produce by default. I tried fixing this with

```md
format:
  pdf:
    default-image-extension: tex
```

but the issue persists.

Is this expected behaviour?
Is there a way to fix this?
Why is Julia the only language that does not output vector images by default?

I'm rendering the basic file found in [the Julia tutorial](https://quarto.org/docs/computations/julia.html#overview)

I'm on Pop_OS (22) Linux, kernel 5.17.15 generic

### `quarto check` Output

```bash
❯ quarto check

[✓] Checking Quarto installation......OK
      Version: 1.0.37
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.2 (Conda)
      Path: /home/-/miniconda3/envs/test/bin/python
      Jupyter: 4.9.1
      Kernels: julia-1.7, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.3
      Path: /usr/lib/R
      LibPaths:
        - /home/-/R/x86_64-pc-linux-gnu-library/4.1
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```
### `quarto tools check` Output

```bash
❯ quarto tools check
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.07
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by alonsoC1s** [comment]
Update:
Using CairoMakie.jl produces vector graphics as desired, but Plots.jl does not. Is this a configuration issue?

**Comment by jjallaire** [comment]
I think the issue may be the version of Plots.jl you are running (a change was made fairly recently to support pdf plots within IJulia). It looks like we require Plots.jl > 1.28.1 to enable PDF: https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/jupyter/lang/julia/setup.jl#L31-L44

**Comment by alonsoC1s** [comment]
That was it!
That was some great debugging, thank you


Here is the final result
[jlhello.pdf](https://github.com/quarto-dev/quarto-cli/files/9230133/jlhello.pdf)
