### ISSUE TITLE
Can't render README.qmd by default or recursively

### ISSUE THREAD

**Issue by MCMaurer** [quarto-dev/quarto-cli#1615]
### Bug description

When running `quarto render` with the CLI, `README.qmd` files seem to be treated differently from files with other names. I have created minimal `.qmd` documents with nothing other than a top-level header, and the issue persists, so it is not related to the Quarto syntax of the documents. There are a few different scenarios where this occurs:

1. If I have a top-level file named `README.qmd`, running `quarto render` does not render the file. However, if I modify `_quarto.yml` to include

```
project:
   render:
      - README.qmd
```

then it will render just fine.

2. Even if I modify the `_quarto.yml` file, `README.qmd` files in lower-level directories are not rendered. This doesn't appear to be a globbing issue, as I've tried a few different wildcards.

Perhaps this is desired behavior, but it does not seem to be documented on the Quarto Projects page. It seems that rendering a bunch of README files in GFM for various subdirectories of a GitHub repo is a reasonable use case, so I think others may run into this issue in the future.

If this is indeed desired behavior, a simple workaround I've found is to name the Quarto file something like `read_me.qmd` and include `output-file: README.md` in the YAML header.

I am running this on MacOS Monterey 12.4.

### `quarto check` Output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.37
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13
      Path: /usr/local/opt/python@3.9/bin/python3.9
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/MJ/R_Packages_4.1
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.07
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by MCMaurer** [comment]
@jjallaire thanks for the reply! I figured there was a good underlying reason for it, just couldn't find anything in the documentation about it.

**Comment by jjallaire** [comment]
Okay, docs updated here: https://github.com/quarto-dev/quarto-web/commit/cf6ccdabc5a2afc2b57b20511c9caa4dceb79353

**Comment by jjallaire** [comment]
re-opening to see if we can improve/refine the behavior further

**Comment by eitsupi** [comment]
Note that there are also site generators that generate index.html from README.md.
(I use the include shortcode in index.md to load README.md to do something similar to this with quarto cli)

It would be great if we could be notified on the log of ignored files such as README.md.

**Comment by AbcSxyZ** [comment]
*Just to share some thought as I'm facing issues related to this problem.*

I'm building an open educational resource on a topic, my intent was to build a website (somehow book like) which fit a git repository content. The idea is (was?) to use README files as index, where you can navigate both on a quarto website or directly from a software forge (aka github).

**A situation where the git repository is equal to the website content.**

> Files named `README.md` or `README.qmd` (which are typically not actual render targets but rather informational content about the source code to be viewed in the version control web UI).

The assumption become problematic when we go out of your thought, in some other contexts :) As mention we can't even use globbing, it may be needed to provide each readme file you expect to render. Still figuring out how to deal with it, with even more problem with the need to specify another default index page.

Maybe not a situation too specific, where you would prefer to base your project on forges conventions rather than quarto ones.

**Comment by eitsupi** [comment]
I believe we can use the include shortcode in index.md as I mentioned above to load the contents of README.md into index.md.

**Comment by eitsupi** [comment]
> But there are link issues in this case when you point to nested README files. You still need to find some fixes at a moment.

If you're thinking about what it will look like when you open a GitHub.com in a browser, wouldn't it be nice to omit the README.md and create a link to the directory?
e.g. Using `./foo/` instead of `./foo/README.md`

**Comment by AbcSxyZ** [comment]
> Using ./foo/ instead of ./foo/README.md

Yeah, bad habits from me. But then you will need a `foo/index.html` rendered, it would be convenient to go when using `{{< include _content.qmd >}}` in `index.[q]md`.

So you could have both ways:
- using `index.md` files with include tag
- listing `README` files on the `render` section in `_quarto.yml` (+ link as `foo/README.md`).

It depends on what you may prefer but still need to have extra steps/files in any case. May be great to have a more native approach to avoid this automatic includes of README files. Issues with links will be important to consider for potential improvements.
