### ISSUE TITLE
Subfigures not supported on Julia

### ISSUE THREAD

**Issue by alonsoC1s** [quarto-dev/quarto-cli#1616]
### Bug description

Recreating the exact same code from the [computations tutorial](https://quarto.org/docs/get-started/computations/vscode.html) but using Julia instead of Python breaks the subfigure functionality. Instead of rendering a figure with a main caption and two subcaptions, the first `fig-subcap` is used as the main caption while `fig-cap` is ignored and only the last figure is rendered. Running Pop_OS 22

The minimal example and resulting .pdf are attached below:
[jlhello.pdf](https://github.com/quarto-dev/quarto-cli/files/9229739/jlhello.pdf)
[hello.pdf](https://github.com/quarto-dev/quarto-cli/files/9229740/hello.pdf)

### `quarto check` Output

```bash
❯ quarto check

[✓] Checking Quarto installation......OK
      Version: 1.0.37
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.2 (Conda)
      Path: /home/alonsoc1s/miniconda3/envs/base/bin/python
      Jupyter: 4.9.1
      Kernels: julia-1.7, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.3
      Path: /usr/lib/R
      LibPaths:
        - /home/alonsoc1s/R/x86_64-pc-linux-gnu-library/4.1
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
❯ quarto tools check
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.07
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
The key for multiple outputs is to use the `display()` function (as by default Jupyter will only output the value from the last statement in the cell). For example, the following will do what you expect:

````python
```{julia}
#| label: fig-plots
#| fig-cap: Multiple Plots
#| fig-subcap:
#|   - "Plot 1"
#|   - "Plot 2"
#| layout-ncol: 2

using Plots
display(plot(sin, x -> sin(2x), 0, 2))
display(plot(x -> sin(4x), y -> sin(5y), 0, 2))
```
````

I've just updated the Julia documentation to make this more clear: https://quarto.org/docs/computations/julia.html#multiple-outputs
