### ISSUE TITLE
incompatible with revtex

### ISSUE THREAD

**Issue by Lightup1** [quarto-dev/quarto-cli#1617]
### Bug description

For revtex, `\author` `\title` and etc are included after `\begin{document}`.
But quarto automatically transform  `\author` `\title` before `\begin{document}` which causes errors.
It is  a general issue for using different `documentclass`

Here is the qmd:
[test.txt](https://github.com/quarto-dev/quarto-cli/files/9230447/test.txt)

### `quarto check` Output

quarto is alright

### `quarto tools check` Output

quarto is alright

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [x] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [x] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by Lightup1** [comment]
It seems not a bug, but a function needed to dynamically compatible with document class.

**Comment by dragonstyle** [comment]
We support templates and partials as way to support this - you can replace some or all of the template that we use to generate the LaTeX. More here:

https://quarto.org/docs/journals/templates.html

and more examples of using these to produce journal style articles here:

https://quarto.org/docs/journals/

If you end up packaging this up into an extension (as we have with some journal formats), we'd love to hear about it. HTH!
