### ISSUE TITLE
git status can be slow

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#162]
Tested with 0.2.222.

Some of my testing has had me temporarily creating Quarto project directories within the directory structure of a large Git repository.

Quarto can run `git status` when attempting to determine if it should write a `.gitignore` file. This happens any time a project is rendered and does not already have a `.gitignore` in place.

Running `git status` can be slow if the access to the working directory is not snappy. This can happen when the filesystem is networked or, in my case, macOS filesystem mounted into a Docker container.

Consider replacing `git status` with `git rev-parse`, which is much lighter weight and can still confirm if the project is within a Git repository.

Here is some timing taken from within my Docker container:

```bash
# initial render without .gitignore
time quarto render
#> real	0m14.693s
#> user	0m3.648s
#> sys	0m1.761s

# subsequent render (having .gitignore)
time quarto render
#> real	0m2.037s
#> user	0m2.022s
#> sys	0m0.680s

# now, timing of some git commands
time git status
#> real	0m11.965s
#> user	0m1.521s
#> sys	0m1.037s

time git rev-parse
#> real	0m0.021s
#> user	0m0.002s
#> sys	0m0.003s
```

**Comment by jjallaire** [comment]
Wow, that's a great level up! Thank you :-)

Addressed here: https://github.com/quarto-dev/quarto-cli/commit/84175d1d207a49026d88bc9970f302ebbf6544b1
