### ISSUE TITLE
Mermaid diagrams with inline styles present syntax error

### ISSUE THREAD

**Issue by edavidaja** [quarto-dev/quarto-cli#1621]
### Bug description

calling `quarto render` on a document with an inline style span will present a syntax error in the rendered HTML.
````
```{mermaid}
graph
L --- P1
L(library)
P1("dashboard <br/> <span style='color:red'>dplyr 1.0.5</span>")
```
````

The same document can be rendered and exported correctly by the [mermaid live editor](https://mermaid.ink/svg/pako:eNo1zrEOgkAQBNBf2WyjJoJS2FyQSjsLEtttFm4V4nFHlqMghH8XEu2meJmZGetgBQ2-lfuG_AOSJIEyW9PetZWyTgfyZbYntDw0VWC1kFd6KiAfevYwxMnJdVcHF9So2F1hezcpZOk5veSnzRSEBzxiJ9pxa9etmTwAYWykE0IDW7d-CMkvqxt7y1Huto1B0bzYDXJEHmN4Tr5GE3WUP7q1vP7ufmr5AtJTRD8).

### `quarto check` Output

```bash
❯ quarto check

[✓] Checking Quarto installation......OK
      Version: 1.1.3
      Path: /Users/edavidaja/.local/share/qvm/versions/v1.1.3/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.6
      Path: /Users/edavidaja/.pyenv/versions/3.8.6/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Versions/4.1/Resources
      LibPaths:
        - /Users/edavidaja/Library/R/x86_64/4.1/library
        - /Library/Frameworks/R.framework/Versions/4.1/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

```

### `quarto tools check` Output

```bash
❯ quarto tools check
[✓] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
This is fixed on 1.1.
