### ISSUE TITLE
Great work and what about blog?

### ISSUE THREAD

**Issue by luzelai** [quarto-dev/quarto-cli#163]
I love building my workflow above quarto,I used it to write my paper,.convert my markdown to pdf,word or anything need when submitting.It is a great work.

However,I am now thinking use quarto to build my own Academic blog website(just like https://hugo-blog-theme.netlify.app/ ).I have known that quarto can also build a website.But is it have a proper way to build the blog like hugo or something else.

**Comment by jjallaire** [comment]
Hi there, yes we are absolutely planning on adding features for blogging! We'll be working on that over the next couple of months and will post back here with updates.
