### ISSUE TITLE
Plots not included as expected in quarto document

### ISSUE THREAD

**Issue by sebastian-gerdes** [quarto-dev/quarto-cli#1631]
Dear RStudio Quarto developers,

first of all - in general I like a lot what I have seen so far from quarto in RStudio - thanks a lot!

I have a question regarding an unexpected behavior:
If I render a quarto document, identical plots are omitted in a code chunk, while they show up as expected when they are not identical.

I added a minimal example in this repository:
git@github.com:sebastian-gerdes/quarto_plots.git

Thanks a lot for any answer in advance!

Best greetings,
Sebastian (using RStudio 2022.07.1)

**Comment by cscheid** [comment]
This is a known issue/feature in knitr. Use `fig-keep: all`:

    ---
    title: "Plotting identical plots"
    format: html
    ---
    
    ```{r}
    #| fig-keep: all
    for (i in 1:10) {
      plot(1:10)
    }
    
    for (i in 1:10) {
      plot(rnorm(10))
    }
    ```
