### ISSUE TITLE
Command line bold

### ISSUE THREAD

**Issue by ShKlinkenberg** [quarto-dev/quarto-cli#1632]
https://github.com/quarto-dev/quarto-web/blob/bb8763a1c5164c2ac9b5b72188747e286fe34cc2/docs/projects/quarto-projects.qmd#L70

I would suggest **command line**. It was not directly clear to me looking at the code chunk that you meant bash. 

While we are on the subject, why doesn't hitting the render button on a single page incorporate the _quarto.yml? My revealjs presentation renders to html doc when hitting the render button. While running quarto render-project in bash works as excpected.

**Comment by cscheid** [comment]
Sorry you're running into trouble.

> why doesn't hitting the render button on a single page incorporate the _quarto.yml? My revealjs presentation renders to html doc when hitting the render button. While running quarto render-project in bash works as excpected.

@ShKlinkenberg Can you provide a minimal example where that problem happens? Are you using RStudio? Which version?  It will help us track this down if you can provide the information that's asked in our issue template. Thank you!

**Comment by ShKlinkenberg** [comment]
Never mind, It had to do with my reveal document sitting in a subdirectory.
