### ISSUE TITLE
`quarto publish gh-pages`does not respect `output-dir: _site`

### ISSUE THREAD

**Issue by eyayaw** [quarto-dev/quarto-cli#1640]
### Bug description

Related to #1246, `quarto publish gh-pages`does not respect `output-dir: _site`
instead renders to `./`.

`_quarto.yml` [full [here](https://github.com/eyayaw/eyayaw.github.io/blob/gh-pages/_quarto.yml)]
```yml
project:
  type: website
  output-dir: _site
```

The last `quarto publish` call results can be seen [here](https://github.com/eyayaw/eyayaw.github.io/tree/gh-pages)
```
~/G/eyayaw.github.io (main)> quarto publish gh-pages
```
````
? Update site at https://Eyayaw.github.io/eyayaw.github.io/? (Y/n) › Yes
From https://github.com/Eyayaw/eyayaw.github.io
 * branch            gh-pages   -> FETCH_HEAD
Rendering for publish:

[1/6] bio.qmd
[2/6] posts/2022-07-31_welcome/index.qmd
[3/6] posts/2022-08-01_ten-baser-tips/index.qmd
[4/6] blog.qmd
[5/6] research.qmd
[6/6] index.qmd

Preparing worktree (resetting branch 'gh-pages'; was at b76bb45)
Branch 'gh-pages' set up to track remote branch 'gh-pages' from 'origin'.
HEAD is now at b76bb45 publish gh-pages
[gh-pages 087d8da] Built site for gh-pages
 32 files changed, 6880 insertions(+), 41 deletions(-)
 create mode 100644 bio.html
 create mode 100644 blog.html
 create mode 100644 index.html
 create mode 100644 posts/2022-07-31_welcome/index.html
 create mode 100644 posts/2022-08-01_ten-baser-tips/index.html
 create mode 100644 research.html
 create mode 100644 site_libs/bootstrap/bootstrap-dark.min.css
 create mode 100644 site_libs/bootstrap/bootstrap-icons.css
 create mode 100644 site_libs/bootstrap/bootstrap-icons.woff
 create mode 100644 site_libs/bootstrap/bootstrap.min.css
 create mode 100644 site_libs/bootstrap/bootstrap.min.js
 create mode 100644 site_libs/clipboard/clipboard.min.js
 create mode 100644 site_libs/quarto-html/anchor.min.js
 create mode 100644 site_libs/quarto-html/popper.min.js
 create mode 100644 site_libs/quarto-html/quarto-syntax-highlighting-dark.css
 create mode 100644 site_libs/quarto-html/quarto-syntax-highlighting.css
 create mode 100644 site_libs/quarto-html/quarto.js
 create mode 100644 site_libs/quarto-html/tippy.css
 create mode 100644 site_libs/quarto-html/tippy.umd.min.js
 create mode 100644 site_libs/quarto-html/zenscroll-min.js
 create mode 100644 site_libs/quarto-listing/list.min.js
 create mode 100644 site_libs/quarto-listing/quarto-listing.js
 create mode 100644 site_libs/quarto-nav/headroom.min.js
 create mode 100644 site_libs/quarto-nav/quarto-nav.js
 create mode 100644 site_libs/quarto-search/autocomplete.umd.js
 create mode 100644 site_libs/quarto-search/fuse.min.js
 create mode 100644 site_libs/quarto-search/quarto-search.js
 rewrite sitemap.xml (75%)
origin  https://github.com/Eyayaw/eyayaw.github.io.git (fetch)
origin  https://github.com/Eyayaw/eyayaw.github.io.git (push)
remote: This repository moved. Please use the new location:        
remote:   https://github.com/eyayaw/eyayaw.github.io.git        
To https://github.com/Eyayaw/eyayaw.github.io.git
   b76bb45..087d8da  HEAD -> gh-pages

[✓] Published to https://Eyayaw.github.io/eyayaw.github.io/

To complete publishing, change the source branch for this site to gh-pages.

Set the source branch at: https://github.com/Eyayaw.github.io/eyayaw/Eyayaw.github.io/eyayaw.github.io/settings/page
````

### `quarto check` Output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.37
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: /usr/bin/python3
      Jupyter: 4.10.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /opt/R/4.2.0/lib/R
      LibPaths:
        - /home/eyayaw/R/x86_64-pc-linux-gnu-library/4.2
        - /opt/R/4.2.0/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status               Installed     Latest  
chromium     Not installed        ---           869685  
tinytex      Update available     v2022.05      v2022.08
WARNING: TeX Live not on path.
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Publishing to `gh-pages` always uses the root because that's the default content location for GitHub Pages sites that use the `gh-pages` branch. Remember that the `gh-pages` branch created using `quarto publish` will have no other content in it so it's not really important that a subdirectory be used

**Comment by eyayaw** [comment]
Thank you for the clarification.

**Comment by tg-x** [comment]
It would be useful to be able to specify an output path inside the gh-pages branch,
to support publishing different branches to different paths from github actions

**Comment by mcanouil** [comment]
@tg-x Please open a new thread (https://github.com/quarto-dev/quarto-cli/discussions/categories/feature-requests) with sufficient details for your request after double checking it's not something already possible, if there are alternatives. Thank you!
Note that `quarto publish` is not intended to cover all possible use cases, *i.e.*, you can can use `quarto render` and then take control of the publishing part to do whatever you need to do.
GitHub Pages does not care about branches other than `gh-pages`, so adding a parameter to publish to GitHub Pages on another branch does not make sense.

**Comment by tg-x** [comment]
yes i figured with render & custom publishing it would be possible, will try that approach
