### ISSUE TITLE
Does quarto work with Jupyter Notebooks regardless of the kernel?

### ISSUE THREAD

**Issue by githubpsyche** [quarto-dev/quarto-cli#165]
If I were to use the Julia or R IPython kernels in Jupyter Notebooks, would that work or is notebook support specific to Python?

**Comment by jjallaire** [comment]
Yes it does. Just use e.g. `jupyter: julia-1.5` to specify an alternate kernel.

**Comment by githubpsyche** [comment]
Thanks very much; sorry if this was the wrong context to ask.
