### ISSUE TITLE
Multiple Figure Numbering Environments

### ISSUE THREAD

**Issue by BradyAJohnston** [quarto-dev/quarto-cli#1655]
I'm looking to potentially use multiple figure environments, so that one set of figures can be referenced and numbered as usual (e.g. Figure 1, Figure 2 etc) but also allow for an additional set of numbered figures such as schemes (Scheme 1, Scheme 2 etc..). 

The desired result is something like in this manuscript where chemical diagrams are labelled separately as Schemes to the rest of the figures: https://api.research-repository.uwa.edu.au/ws/portalfiles/portal/142280159/manuscript.pdf

EDIT: I have been able to utilise multiple environments inside of LaTeX to have both he Figure & Scheme labelling / numbering to be separate (using `\usepackage{chemstyle}`) but it would be great to try and have a similar functionality available for the HTML output as well.

**Comment by cscheid** [comment]
This is fixed on 1.4 prereleases.

**Comment by slowkow** [comment]
@cscheid  Could I please ask if there exists an example of how to use multiple figure environments?

If I install the 1.4 pre-release, can I try it out? (How do I install the pre-release?)

Would you recommend that I attempt to write a new extension for this feature? Or would you advise to sit and wait for the next release instead?

**Comment by mcanouil** [comment]
Go to the documentation website: https://quarto.org

**Comment by cscheid** [comment]
@slowkow You've asked the same question here [and elsewhere](https://github.com/quarto-dev/quarto-cli/discussions/3209)

@mcanouil answered your question there already, and it's usually considered somewhat impolite to repeat the question in multiple places like that. Please consider not doing that in the future.

**Comment by slowkow** [comment]
At this link https://quarto.org/docs/download/ we can find a tab that says "pre-release" where we can download and install a prerelease.

Looking through the release notes, it seems like these are the two main pages with examples:

- https://quarto.org/docs/authoring/cross-references-divs.html

- https://quarto.org/docs/authoring/cross-references-custom.html

The custom cross references page looks exactly like what I was originally looking for:

```
crossref:
  custom:
    - kind: float
      reference-prefix: Video
      key: vid
```

**Comment by slowkow** [comment]
@cscheid Hey Carlos, I just wanted to write and say thank you for implementing the custom crossref feature. It is awesome!

I downloaded the 1.4 prerelease from the [Download page](https://quarto.org/docs/download/) and tried it out on my own files, and it works perfectly. I love how the feature is implemented, giving users freedom to label figures as tables and tables as figures, etc. It is a joy to use. Thank you for the excellent work!

I went to the [custom crossref documentation page](https://quarto.org/docs/authoring/cross-references-custom.html) and scrolled all the way to the bottom to find this example, which I copied directly into my `_quarto.yml` file. And it worked on the first try! 😁

```
crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
```

I'm looking forward to using quarto more frequently for more of my work. It's clear there is a lot of thought and consideration going into new features.

Just a minor note about the [custom crossref documentation page](https://quarto.org/docs/authoring/cross-references-custom.html), I think `ref-type` should probably be `key`, but I am not certain.

By the way, sorry for posting in two places, it's my mistake and next time I'll try to keep the discussion in one place.

**Comment by cscheid** [comment]
> Just a minor note about the [custom crossref documentation page](https://quarto.org/docs/authoring/cross-references-custom.html), I think ref-type should probably be key, but I am not certain.

You're absolutely right. Thank you! Fixed now.
