### ISSUE TITLE
cannot get nocite to work

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-cli#1660]
I would like a bibliography that includes many works that may not be referenced specifically. I am using quarto 1.0.37 for Windows, with the latest Wakerobin build of RStudio.

The [quarto documentation](https://quarto.org/docs/authoring/footnotes-and-citations.html) appears to say I can do this by creating a "dummy nocite metadata field" that either has specific references, or all of them. This mirrors the [pandoc user guide](https://quarto-dev.github.io/quarto-gallery/articles/pdf/pandoc-user-guide.pdf), p.101.

I have created such a metadata field and tried putting it everywhere - at the top of my `references.qmd` file, after the header of the file, inside the fenced `{#refs}` part of the file, in a different .qmd file, and as metadeta in my _quarto.yml file, but the uncited works never show in the references list. This is true whether I put specific references (e.g, @item1, @item2) or the wild card for all works (@*) in the metadata field.

Would it be possible to tell me if I am doing something wrong (and how to do it correctly)?

--------------------- Aside -----------------------------------------------------------

FWIW, I found a way to work around this by creating a separate text file with the list of uncited works (constructed with an R program that reads the .bib file of all works) like this:

```
::: {#refs}
{{< include all_cited_and_uncited_works.qmd >}}
:::

```

However, this is not a great solution because when there are multiple works by the same author, where some of them are cited, it is hard to get the sort order of this list synchronized with the works as they appear in the resulting html -- some works in the body of the book will link to the wrong works in the references html file. So I'd rather not try to use this workaround.

**Comment by jjallaire** [comment]
It would be great to see the actual code that you are using to diagnose. We definitely use `nocite` within Quarto itself and I haven't seen problems with it working correctly.

**Comment by donboyd5** [comment]
Great. Am away today will add by tomorrow.

Sent by an android

**Comment by donboyd5** [comment]
Ok, to make sure the problem is not specific to my .bib or _quarto.yml files, here's what I just did:

- From within RStudio, created a new Quarto book project
- Rendered the book via `quarto render` from terminal. As expected, the @knuth84 reference appears in references.html
- Commented out the Knuth citation in intro.qmd:

`<!-- See @knuth84 for additional discussion of literate programming. -->`
- Rendered the book via `quarto render` from terminal. As expected, the @knuth84 reference does NOT appear in references.html.
- Went to the [quarto documentation](https://quarto.org/docs/authoring/footnotes-and-citations.html), copied the "nocite" text, pasted it into references.qmd, and edited it, so that the entire references.qmd file is as follows:

```
# References {.unnumbered}

---
nocite: |
  @knuth84
---

::: {#refs}
:::

```
- Rendered the book via `quarto render` from terminal. Unfortunately, the @knuth84 reference does NOT appear in references.html even though it is in references.bib.
- Tried placing the nocite metadata in various other places, as in my earlier note above, but still no success.

Given that it is working in what you do, my guess is that I am misunderstanding the instructions. Anyway, I would much appreciate advice on what I may be doing wrong.

**Comment by jjallaire** [comment]
Thank you! I see the problem: nocite is not working at all within books b/c we collect all of the cite ids and then render the aggregate bibliography separately.

**Comment by donboyd5** [comment]
Thank you very much.

This makes my workaround of more interest to me. Unfortunately, as mentioned above, it reveals a problem in that citations to work are not synchronized with works as listed in the bibliography. This occurs -- at least -- when an author has multiple works in the same year and one of those works is cited. It may occur in other situations but I have not figured that out.

I have a small reproducible example that I will put in a separate cross-referenced issue that I hope will make this clear.

**Comment by jjallaire** [comment]
Okay, we now have support for `nocite` within books. Note that as with `bibliography` and `csl` this must be specified in the project file (as for non-HTML formats all input documents are concatenated together so multiple instances of these fields would overwrite each other). This is available in our pre-release at https://quarto.org/docs/download/prerelease.html

**Comment by donboyd5** [comment]
Thanks - it works great!

It took me a while to understand what I needed to do to specify the metadata in the project file. If I get a chance, I'll figure out how to do a pull request to offer neophyte-friendly edits to the documentation [here](https://quarto.org/docs/authoring/footnotes-and-citations.html#including-uncited-items).

**Comment by jjallaire** [comment]
Okay, great. Note that we probably won't merge the documentation changes until the release of v1.1
