### ISSUE TITLE
The result of "quarto publish quarto-pub" shows a wrong URL.

### ISSUE THREAD

**Issue by yutannihilation** [quarto-dev/quarto-cli#1662]
### Bug description

It seems "Published document" shows a wrong URL (quartopub\.org doesn't exist).

```
$ /c//Users/Yutani/AppData/Local/Programs/Quarto/bin/quarto.cmd publish quarto-pub ./quarto_test.qmd

...snip...

[>] Preparing to publish document
[>] Uploading files (complete)
[>] Deploying published document
[>] Published document: https://quartopub.org/sites/yutani/quarto_test
[>] Account site updated: https://yutani.quarto.pub
```

### `quarto check` Output

```bash
$ /c//Users/Yutani/AppData/Local/Programs/Quarto/bin/quarto.cmd check

[>] Checking Quarto installation......OK
      Version: 1.0.37
      Path: C:\Users\Yutani\AppData\Local\Programs\Quarto\bin\
      CodePage: 932

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/Yutani/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK


```

### `quarto tools check` Output

```bash
$ /c//Users/Yutani/AppData/Local/Programs/Quarto/bin/quarto.cmd tools check
[>] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by dragonstyle** [comment]
This has been corrected, though any previously published documents may continue to report the incorrect url (the url is cached with the `_publish.yml` file). You could correct it in the `_publish.yml` file if it is a nuisance to you.

**Comment by yutannihilation** [comment]
I see, thanks!
