### ISSUE TITLE
quarto erroneously halts with error: Error: ignoring SIGPIPE signal

### ISSUE THREAD

**Issue by cboettig** [quarto-dev/quarto-cli#1667]
(Apologies for the blank initial post, not getting a raw markdown-based template confused the heck out of me!)

### Bug description

When attempting to render scripts involving arrow S3 operations, quarto fails part way through with this error.  

```r
download.file("https://github.com/cboettig/forecasts-darts-framework/raw/main/weather-covariates.qmd", "sigpipe.qmd")
quarto::quarto_render("sigpipe.qmd")
# ...
#>  $ include: logi FALSE
#> 
#> 
#> [31moutput file: sigpipe.knit.md
#> 
#> [39m[31mError: ignoring SIGPIPE signal
#> Execution halted
#> [39m
#> Error in "processx::run(quarto_bin, args, echo = TRUE)": ! System command 'quarto' failed
```
<sup>Created on 2022-08-03 by the [reprex package](https://reprex.tidyverse.org/) (v2.0.1)</sup>

I understand that this error is at least in some way the fault of `arrow` (see https://issues.apache.org/jira/browse/ARROW-16680?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel), but quarto's handling of this manages to turn what is usually just a nuisance message into a showstopper.  In most other contexts, the code runs without error.  Compare the execution of the same commands, but with:

- `rmarkdown::render()` :  no error
- callr::rscript() : no error
- RScript - throws an error
- knit button in RStudio -- throws the error, but continues to pandoc rendering of the html, so is less problematic
- littler `r`: no error (because unlike R, it can handle a SIGPIPE)

I don't fully understand why arrow throws a SIGPIPE (sometimes?) in it's finalizers here, or why some R tools choose to treat SIGPIPE as an error, but this is rather annoying.  (especially as just about every day I want to show someone the awesomeness of quarto and arrow, and so hitting a opaque error is embarrassing! :face_exhaling: ).

### `quarto check` Output

```
quarto check

[✓] Checking Quarto installation......OK
      Version: 0.9.613
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /home/cboettig/cboettig/forecasts-darts-framework/venv/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/local/lib/R/library
        - /home/cboettig/cboettig/forecasts-darts-framework/renv/library/R-4.2/x86_64-pc-linux-gnu
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```
quarto tools check
(/) Inspecting toolsDownload https://deno.land/x/cache@0.2.12/directories.ts
(|) Inspecting toolsDownload https://deno.land/x/cache@0.2.12/deps.ts
[✓] Inspecting tools

Tool         Status                    Installed     Latest  
chromium     Not installed             ---           869685  
tinytex      External Installation     ---           v2022.08
```

RStudio Server: 2022.02.3 Build 492

(Running in Ubuntu 20.04, e.g. in rocker/geospatial container RStudio instance, but error can also be reproduced in other environments, including on any OS in GH-Actions. )

```
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.1 (2022-06-23)
 os       Ubuntu 20.04.4 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2022-08-03
 rstudio  2022.07.0+548 Spotted Wakerobin (server)
 pandoc   2.18 @ /usr/lib/rstudio-server/bin/quarto/bin/tools/ (via rmarkdown)

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 arrow       * 8.0.0      2022-05-09 [1] RSPM (R 4.2.0)
 assertthat    0.2.1      2019-03-21 [2] RSPM (R 4.2.0)
 bit           4.0.4      2020-08-04 [2] RSPM (R 4.2.0)
 bit64         4.0.5      2020-08-30 [2] RSPM (R 4.2.0)
 bslib         0.4.0      2022-07-16 [1] CRAN (R 4.2.0)
 cachem        1.0.6      2021-08-19 [2] RSPM (R 4.2.0)
 callr         3.7.1      2022-07-13 [1] CRAN (R 4.2.0)
 cli           3.3.0      2022-04-25 [2] RSPM (R 4.2.0)
 crayon        1.5.1      2022-03-26 [2] RSPM (R 4.2.0)
 DBI           1.1.3      2022-06-18 [1] RSPM (R 4.2.0)
 devtools      2.4.4      2022-07-20 [1] RSPM (R 4.2.0)
 digest        0.6.29     2021-12-01 [2] RSPM (R 4.2.0)
 dplyr         1.0.9      2022-04-28 [1] RSPM (R 4.2.0)
 ellipsis      0.3.2      2021-04-29 [2] RSPM (R 4.2.0)
 evaluate      0.15       2022-02-18 [2] RSPM (R 4.2.0)
 fansi         1.0.3      2022-03-24 [2] RSPM (R 4.2.0)
 fastmap       1.1.0      2021-01-25 [2] RSPM (R 4.2.0)
 fs            1.5.2      2021-12-08 [2] RSPM (R 4.2.0)
 generics      0.1.3      2022-07-05 [1] CRAN (R 4.2.0)
 glue          1.6.2      2022-02-24 [2] RSPM (R 4.2.0)
 hms           1.1.1      2021-09-26 [2] RSPM (R 4.2.0)
 htmltools     0.5.3      2022-07-18 [1] CRAN (R 4.2.0)
 htmlwidgets   1.5.4      2021-09-08 [2] RSPM (R 4.2.0)
 httpuv        1.6.5      2022-01-05 [2] RSPM (R 4.2.0)
 jquerylib     0.1.4      2021-04-26 [2] RSPM (R 4.2.0)
 jsonlite      1.8.0      2022-02-22 [2] RSPM (R 4.2.0)
 knitr         1.39       2022-04-26 [2] RSPM (R 4.2.0)
 later         1.3.0      2021-08-18 [2] RSPM (R 4.2.0)
 lattice       0.20-45    2021-09-22 [3] CRAN (R 4.2.1)
 lifecycle     1.0.1      2021-09-24 [2] RSPM (R 4.2.0)
 magrittr      2.0.3      2022-03-30 [2] RSPM (R 4.2.0)
 Matrix        1.4-1      2022-03-23 [3] CRAN (R 4.2.1)
 memoise       2.0.1      2021-11-26 [2] RSPM (R 4.2.0)
 mime          0.12       2021-09-28 [2] RSPM (R 4.2.0)
 miniUI        0.1.1.1    2018-05-18 [2] RSPM (R 4.2.0)
 neon4cast     0.1.0      2022-07-25 [1] Github (eco4cast/neon4cast@3ea5c2e)
 pillar        1.8.0      2022-07-18 [1] CRAN (R 4.2.0)
 pkgbuild      1.3.1      2021-12-20 [2] RSPM (R 4.2.0)
 pkgconfig     2.0.3      2019-09-22 [2] RSPM (R 4.2.0)
 pkgload       1.3.0      2022-06-27 [2] RSPM (R 4.2.0)
 png           0.1-7      2013-12-03 [2] RSPM (R 4.2.0)
 prettyunits   1.1.1      2020-01-24 [2] RSPM (R 4.2.0)
 processx      3.7.0      2022-07-07 [1] CRAN (R 4.2.0)
 profvis       0.3.7      2020-11-02 [1] RSPM (R 4.2.0)
 promises      1.2.0.1    2021-02-11 [2] RSPM (R 4.2.0)
 ps            1.7.1      2022-06-18 [1] CRAN (R 4.2.0)
 purrr         0.3.4      2020-04-17 [2] RSPM (R 4.2.0)
 R6            2.5.1      2021-08-19 [2] RSPM (R 4.2.0)
 Rcpp          1.0.9      2022-07-08 [1] CRAN (R 4.2.0)
 read4cast     0.0.2      2022-07-29 [1] Github (eco4cast/read4cast@28829bf)
 readr         2.1.2      2022-01-30 [2] RSPM (R 4.2.0)
 remotes       2.4.2      2021-11-30 [2] RSPM (R 4.2.0)
 renv          0.15.5     2022-05-26 [1] RSPM (R 4.2.0)
 reprex        2.0.1      2021-08-05 [2] RSPM (R 4.2.0)
 reticulate    1.25       2022-05-11 [1] CRAN (R 4.2.0)
 rlang         1.0.4      2022-07-12 [1] CRAN (R 4.2.0)
 rmarkdown     2.14       2022-04-25 [2] RSPM (R 4.2.0)
 rstudioapi    0.13       2020-11-12 [2] RSPM (R 4.2.0)
 sass          0.4.2      2022-07-16 [1] CRAN (R 4.2.0)
 score4cast    0.0.0.9000 2022-07-29 [1] Github (eco4cast/score4cast@2a6673d)
 sessioninfo   1.2.2      2021-12-06 [2] RSPM (R 4.2.0)
 shiny         1.7.2      2022-07-19 [1] RSPM (R 4.2.0)
 stringi       1.7.8      2022-07-11 [1] CRAN (R 4.2.0)
 stringr       1.4.0      2019-02-10 [2] RSPM (R 4.2.0)
 tibble        3.1.8      2022-07-22 [1] CRAN (R 4.2.0)
 tidyselect    1.1.2      2022-02-21 [2] RSPM (R 4.2.0)
 tzdb          0.3.0      2022-03-28 [2] RSPM (R 4.2.0)
 urlchecker    1.0.1      2021-11-30 [1] CRAN (R 4.2.0)
 usethis       2.1.6      2022-05-25 [1] RSPM (R 4.2.0)
 utf8          1.2.2      2021-07-24 [2] RSPM (R 4.2.0)
 vctrs         0.4.1      2022-04-13 [2] RSPM (R 4.2.0)
 withr         2.5.0      2022-03-03 [2] RSPM (R 4.2.0)
 xfun          0.31       2022-05-10 [1] RSPM (R 4.2.0)
 xtable        1.8-4      2019-04-21 [2] RSPM (R 4.2.0)
 yaml          2.3.5      2022-02-21 [2] RSPM (R 4.2.0)

 [1] /home/cboettig/R/x86_64-pc-linux-gnu-library/4.2
 [2] /usr/local/lib/R/site-library
 [3] /usr/local/lib/R/library
 ```
 

### Checklist

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [x] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [x] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [x] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
We would need some way to reproduce this? For what commands/inputs do you see this behavior?

**Comment by cboettig** [comment]
@jjallaire apologies I struggled with the GitHub Issues template giving me a visual editor -- hadn't seen that before! -- instead of the familiar markdown and hit submit prematurely. Details added above.

**Comment by cscheid** [comment]
I can't seem to reproduce this on macOS.

**Comment by cboettig** [comment]
@cscheid thanks for looking into this and the quick reply. Here's an example of running quarto on GitHub Actions and reproducing this error, causing the action to fail: https://github.com/cboettig/scratch/runs/7662521011?check_suite_focus=true#step:5:138

**Comment by cboettig** [comment]
(also, this may be the result of some kind of race condition created by the finalizers in arrow between the arrow code and curl, which make the bug unreliable to reproduce -- I can get it pretty consistently on my local linux machine, but it is sometimes passing and sometimes reproducing the SIGPIPE error.  

Poking around a little, it looks like there are simpler/other ways in which R will produce the sigpipe error, e.g. https://stackoverflow.com/questions/28915838/piping-rscript-gives-error-after-output , (where the use of a sigpipe is a bit more explicit though and seems like it can be avoided by modifying the R code, which I don't think is an option in the arrow case).

**Comment by jjallaire** [comment]
What happens if you run the dev version and explicitly ignore SIGPIPE here: https://github.com/quarto-dev/quarto-cli/blob/main/src/quarto.ts#L114-L119

**Comment by cboettig** [comment]
Thanks @jjallaire .  Not quite sure I did this right, but looks like I am still getting the same error after installing the dev version, e.g. in this GH-Actions run: https://github.com/eco4cast/neon4cast-dashboard/runs/7738845292?check_suite_focus=true#step:8:1089

Was there a env var or something I was supposed to set to ignore the SIGPIPE?

**Comment by jjallaire** [comment]
Sorry, I was thinking you would actually change the code to ignore the SIGPIPE! I just checked in a change to ignore SIGPIPE -- could you try again?

One thing to keep in mind is that ignoring SIGPIPE might actually throw off some of the networking code in Rust/Deno (hard to say without actually knowing the code). I'd need to investigate further once confirming that this has any impact at all on your scenario (I recall quite a bit of debate about whether it was okay to ignore SIGPIPE in RStudio and some scenarios being broken by doing so).

**Comment by cboettig** [comment]
@jjallaire ah, okay thanks! Sorry I didn't quite understand what had to change.  Yes, as expected, that looks to have fixed it.  (though maybe I should run a few times as the race condition seems to result in a bit of a stochastic error).  

Yup, good question about the downstream consequences of ignoring a SIGPIPE, that's above my pay-grade to be sure!  According to the issue thread in {arrow}, it sounds like the race condition is ultimately due to something in the AWS SDK, https://issues.apache.org/jira/browse/ARROW-16680?focusedCommentId=17575261&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17575261, but might be a while being fixed.  I cannot tell from the discussion there whether there is a CURL env var that can be set instead to ignore this as a one-off.  

FWIW, other execution environments, like Dirk's `littler`, don't throw this error -- I gather littler isn't ignoring SIGPIPE but is a 'pipe-able' interface, unlike, say, RScript.  This seems like a nice feature, at least on Linux-based systems, so not sure if that is behavior quarto could have as well, but again well over my head here.

**Comment by cboettig** [comment]
hm, spoke too soon, subsequent runs do still seem to hit a sigpipe error.  https://github.com/eco4cast/neon4cast-dashboard/runs/7750989020?check_suite_focus=true#step:8:1028  I think I'm correctly installing the most recent dev quarto in that workflow but perhaps still missing something.

**Comment by jjallaire** [comment]
Okay, I think this might need to be handled somewhere else then (as I'm pretty wary of just throwing that ignore into Quarto without understanding all the downstream ramifications)
