### ISSUE TITLE
Citations not properly synchronized with bibliography in certain cases - v.2

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-cli#1678]
Github did not allow me to post the full issue so I will do it in pieces.

Issue #1660 led me to look for a way to include uncited works in a book bibliography, which I am doing by including a text file with the relevant bibtex keys in the #refs div. (A seemingly equivalent approach is to cite those works in a .hidden div.) However, that led to a problem in which citations and the bibliography may not be properly synchronized.

I am not sure of precisely when the problem will occur, but here is a way to produce one circumstance in which it occurs:

- In RStudio, create a new book project.
- Add 2 more Knuth works to the references.bib file. Assume that, in addition to the May 1984 journal article included in the default book project, he had a two-volume technical report put out through ABC Institution called "More Literate Programming", where Volume 1 came out in June 1984 and Volume 2 came out in July 1984. Assume the bibliographic software (Zotero in my case) assigned bibtex keys knuth84b and knuth84a to Volumes 1 and 2 respectively. For my testing purposes I put Volume 2 into the file before Volume 1 but I don't know if that ordering is important. The references.bib file will now look like the code block that I will copy into a subsequent comment.
- Cite Volume 2 (knuth84a) in intro.qmd (in addition to the existing cite of the journal article), but do not cite Volume 1. The relevant line in intro.qmd will now be:

`See @knuth84 and @knuth84a for additional discussion of literate programming.`

- Put the bibtex keys for all 3 works (journal article and 2-volume technical report) in a separate text file, to help implement my workaround to allow a full bibliography in a book. (I would create this file programmatically by reading the references.bib file.) I call the file "all_cited_and_uncited_works.txt". It will look like this:
```
@knuth84
@knuth84a
@knuth84b
```
- Include the file in the references.qmd file, in the #refs div. Here's what my references.qmd file looks like:

```
# References {.unnumbered}

::: {#refs}
{{< include all_cited_and_uncited_works.txt >}}
:::

```
- Render the book. I do this via "quarto render" from the terminal.
- Look at intro.html. You should see the following for the citations

> See Knuth (1984b) and Knuth (1984a) for additional discussion of literate programming.

- Quarto has assigned 1984b to the journal article (1st citation) and 1984a to Volume 2 of the report. While this may seem surprising it is ok as far as I can tell - there's no reason it should have the same year-letter values as the bibtex keys, because quarto should assign them based on appearance in the bibliography, whereas Zotero or other bibliographic software will assign them considering all works by the same author in the particular citation library. Hovering over the hyperlinked 1984b and 1984a values in intro.html shows that they do, indeed, reference the article and Volume 2 report properly.

**Comment by donboyd5** [comment]
I'm describing what you should see as Github is not allowing me to insert screenshots.

- Now open references.html in a browser. You should see the following

> Knuth, Donald E. 1984a. “More Literate Programming Volume 1.” ABC Institution.
> ———. 1984b. “More Literate Programming Volume 2.” ABC Institution.
> ———. 1984c. “Literate Programming.” Comput. J. 27 (2): 97–111. https://doi.org/10.1093/comjnl/27.2.97.

- 1984b appears as Volume 2 and 1984c appears as the journal article, even though when we cited it, Quarto assigned 1984b to the journal article and assigned 1984a to Volume 2 of the report. Thus, the citations and the bibliography are out of sync.

I will try to add screenshots later if Github allows, but hopefully this is enough information to reproduce the issue.

**Comment by donboyd5** [comment]
Here is the references.bib file as extended:

```
@article{knuth84,
  author = {Knuth, Donald E.},
  title = {Literate Programming},
  year = {1984},
  issue_date = {May 1984},
  publisher = {Oxford University Press, Inc.},
  address = {USA},
  volume = {27},
  number = {2},
  issn = {0010-4620},
  url = {https://doi.org/10.1093/comjnl/27.2.97},
  doi = {10.1093/comjnl/27.2.97},
  journal = {Comput. J.},
  month = may,
  pages = {97–111},
  numpages = {15}
}

@techreport{knuth84a,
  author = {Knuth, Donald E.},
  title = { {{More Literate Programming}} {{Volume}} 2},
  year = {1984},
  month = july,
  institution = {{ABC Institution}}
}

@techreport{knuth84b,
  author = {Knuth, Donald E.},
  title = { {{More Literate Programming}} {{Volume}} 1},
  year = {1984},
  month = june,
  institution = {{ABC Institution}}
}


```

**Comment by donboyd5** [comment]
Thanks!

**Comment by jjallaire** [comment]
I don't think the workaround as presented here would actually work -- if you put things into the `#refs` div they will actually be replaced entirely by the bibliography (so not discovered when we try to build the global bibliography).

If you can construct a simpler example with citations and bibliography out of sync that doesn't involve embedding in the `#refs` div please do let me know!

**Comment by donboyd5** [comment]
Thanks. My variant of the workaround is to put the bibtex keys for the desired references into a hidden div in references.qmd as in the code block below. I believe/assume that this is the same as citing these works but just not showing the cites to the reader. It uses the same intro.qmd, references.bib, and all_cited_and_uncited_works.txt files as above.

This succeeds at getting all desired references into the bibliography but unfortunately, the cites in intro.html are out of sync with the references in references.html. They are out of sync whether I put bibtex keys for all references ("@knuth84, "@knuth84a, "@knuth84b) or just for the uncited reference ("@knuth84b) into the .hidden div. (From a user standpoint, it is easier for me to put all references from my bibliography into the .hidden div even though it seems wasteful because then I don't have to look for and remove those already cited.)

```
# References {.unnumbered}

::: {.hidden}
{{< include all_cited_and_uncited_works.txt >}}
:::


::: {#refs}
:::

```

Obviously for purposes of reproducing the out-of-sync issue I don't really need to include the text file of bibtex keys, I could just hard-code the desired bibtex keys into the .hidden div.

**Comment by donboyd5** [comment]
Apparently using a .hidden block hides the citations of otherwise-uncited works when the format is html, but not when the format is pdf. Switching to a .content-hidden block unfortunately does not work because then the otherwise-uncited works apparently do not show in the references.html file.

There might be other workarounds, such as displaying the text but making it the same as the background, but that's well beyond my level of knowledge. For now, .hidden is ok because I'm focused on html output at present.

**Comment by jjallaire** [comment]
Okay, great. Hoping in any case to have support for `nocite` working soon.

**Comment by jjallaire** [comment]
`nocite` now available in books (see https://github.com/quarto-dev/quarto-cli/issues/1660)
