### ISSUE TITLE
Localization for non-English projects

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#168]
Web outputs include navigational elements that are always in English, for example the title "On this page" of the right margin menu, the "Footnotes" header at the bottom of pages, and various strings in the search bar GUI. It would be great to have these translated according to the `lang` variable (as already done by babel for the PDF format).

**Comment by jjallaire** [comment]
As it so happens we are working on this right now! More details soon....

**Comment by jjallaire** [comment]
We've put in the infrastructure for localized language text. More details are here: https://quarto.org/docs/authoring/language.html

Currently we have English, Chinese, and French translations (and we are working on a few more including German and Spanish).

You can also provide your own translation if the language isn't yet supported.

**Comment by knuesel** [comment]
That's awesome, thanks!
