### ISSUE TITLE
require-ing MathJax fully working in Observerable notebook, but NOT in Quarto ojs cell

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#1685]
(Something's happening with our version of `require`.)

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1682

<div type='discussions-op-text'>

<sup>Originally posted by **stuvjordan-uroc** August  4, 2022</sup>
I'm wanting to include some Observable charts in a website I'm building with Quarto.  I'd like these charts to include nicely-typeset math, and for that purpose I'm wanting to use MathJax's `tex2svg` function in the source code.  Relative to other math typesetting solutions one can use in Observable, `tex2svg` is nice because it outputs pure SVG paths...Thus they scale as the svg containing them is resized without any additional code, so the math looks great on every screen size.

I'm running into this **very** weird difference in the result of a call to `require` when that call is made in an Observable Notebook, as opposed to when I make it in an `ojs` cell in a Quarto sourcefile.

First, let's look at what happens when we require `tex2svg` in an Observable Notebook.  You can see the results in [this notebook](https://observablehq.com/@stuvjordan/requiring-mathjax-tex2svg).  Open up the object in the first cell after the title and notice the full list of methods that the object returned by the call to `require` includes.  Notice the list includes the method `.tex2svg`, which is the function I need.  Below is a screenshot.  You'll see `tex2svg` as the fourth method from the bottom.

![image](https://user-images.githubusercontent.com/78857503/182877558-aec76537-8983-4f36-876a-8053401248f8.png)

OK, great, so we can use `tex2svg` in an Observable notebook!

But what happens when we do the same call to `require` in an `ojs` cell in a `.qmd` file?  Here are two cells from my current `.qmd` source:
```{ojs}
//| output: true
MathJax = require('https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js').catch(
  () => window['MathJax']
)
```

```{ojs}
MathJax
```
Here's a screenshot of the output from the second of the above two `ojs` cells when I render/preview the sourcefile:

![image](https://user-images.githubusercontent.com/78857503/182878897-538a83da-691c-47be-b621-d7935ada8515.png)

**Notice that the list of methods does not include `tex2svg`!!!!**  As a result, when I do something like
```{ojs}
MathJax.tex2svg(
    String.raw`\int_0^1 \exp(x)dx`
 );
```
In the quarto sourcefile, the output on render/preview is:

![image](https://user-images.githubusercontent.com/78857503/182879785-70a332fe-3e53-488f-8d99-a671d42624b7.png)

I'm kind of amazed by this.

Help?</div>

**Comment by cscheid** [comment]
@stuvjordan-uroc, I'm having a hard time reproducing your example. This works for me:

    ---
    title: mathjax
    ---
    
    ```{ojs}
    MathJax = require('https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js').catch(() => window['MathJax'])
    MathJax.tex2svg
    ```

It produces the following:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/285675/182917878-9d4f0c94-15e3-431b-909b-38bea08c974f.png">

Can you provide details on your install, from our github issue template?

**Comment by stuvjordan-uroc** [comment]
Hi!  I just figured out what triggers the problem.  (Wrote this as a reply in my post to the discussion forum as well):

In a `qmd` file that includes math in the main body, as in `here is some math in a sentence $\sum_n \frac{1}{2}$`, `require`-ing MathJax in an `ojs` cell results in `tex2svg` not being included in the objected returned from `require`.

On the other hand, in a `qmd` file that does not include math in the main body, the `require` call in an `ojs` cell performs as expected.

I'm getting the behavior when I render a pretty big project.  I will work on creating two very simple `qmd` files that you can use to replicate.  Stay tuned!

**Comment by stuvjordan-uroc** [comment]
OK, text for two qmd sourcefiles below.  Self explanatory.  Render each by itself and you should see the problem.

I'm going to see if I can workaround by putting the ojs code in a separate sourcefile and then including that source into the sourcefile that has math in the body.

If you've got any recommendations for workarounds or alternatives to MathJax for getting pretty math into my ojs figures, please share! (Trying to write classnotes for the upcoming semester in Quarto!)

# source with no math in body
```
---
title: "Trying MathJax With No Math in Body"
format: html
execute: 
  echo: true
  output: true
---

Here is body text with no math.

```{ojs}
SVJMathJax = require('https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js').catch(
  () => window['MathJax']
)
```

```{ojs}
SVJMathJax
```

```{ojs}
SVJMathJax.tex2svg(
  String.raw`\int_0^1 \exp(x) dx`
)
```

# Source with math in body:

```
---
title: "Trying MathJax With Math in Body"
format: html
execute: 
  echo: true
  output: true
---

Here is body text with math $\sum_n \frac{1}{n^2}$

```{ojs}
SVJMathJax = require('https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js').catch(
  () => window['MathJax']
)
```

```{ojs}
SVJMathJax
```

```{ojs}
SVJMathJax.tex2svg(
  String.raw`\int_0^1 \exp(x) dx`
)
```
```
```

**Comment by stuvjordan-uroc** [comment]
Is it possible that [combining freeze with a virtual environment](https://quarto.org/docs/projects/code-execution.html#freeze-virtual-environments) could be a successful workaround here?

Like...put the qmd files containing the ojs blocks that `require` MathJax in an 'env' subfolder and pre-render those files in a virtual env, then freeze?

**Comment by cscheid** [comment]
The issue might be that you simply can't have two separate versions of MathJax in the same JS environment.

If that's so, then one workaround is for your math markdown paragraphs to be rendered by OJS. That's a bit weird, but it works. You can do something like

    ```{ojs}
    md`# Hello`
    ```

And that will do what it looks like. I haven't tested the support for embedded math inside the markdown, but it might be worth a shot..

**Comment by stuvjordan-uroc** [comment]
Thanks @cscheid !

Not sure I follow your workaround.  Observable's tools for generating markup (e.g. `md```, `html``` `tex```) output html.   So the only way to get that output into an svg chart as an axis label or other annotation is either to overlay the chart with a relatively positioned `div` and then put the html in that div, or to add a `foreignObject` to the svg and then stick the html in that.

Is that what you had in mind?  If so, I'm pretty sure doing that in a way that results in pretty math that scales with the chart as the window size changes requires some javascript that is way over my head.  Although if you you know of a good resource describing how to write javascript that scales a child element in response to changes in the scale of it's parent, point me to it!

**Comment by cscheid** [comment]
I was merely talking about the issue with mathjax version conflicts. The idea is that if you use Observable's markdown tools when using math, then _quarto's_ mathjax won't get loaded, and you will end up with the right version of mathjax in observable (and hence with `tex2svg`).

**Comment by cscheid** [comment]
I'm closing this, since managing conflicting versions of js libraries really isn't a bug in scope for quarto.

**Comment by stuvjordan-uroc** [comment]
@cscheid thank you for the explanation!

How do I find out what version of Mathjax quarto uses to render when it encounters math mode in markdown?

Seems from what you've written that if I'm careful to `require` the same version of Mathjax when I need it in an `ojs` cell, maybe I can make this work.

Of course if you're too busy resolving open issues feel free to ignore!

Thank you!

**Comment by cscheid** [comment]
This is a minimal document you can use to figure it out. This version might change as we upgrade quarto, though.

    $$e = mc^2$$
    
    ```{ojs}
    window.MathJax.version
    ```

**Comment by stuvjordan-uroc** [comment]
Thanks!!!
