### ISSUE TITLE
Unexpected Behaviour in Locale Date Processing

### ISSUE THREAD

**Issue by Andy2K11** [quarto-dev/quarto-cli#1688]
## Unexpected Behaviour in Date Processing

This date format:

```
---
date: 04 08 2022
date-format: "Do MMMM YYYY"
lang: en-GB
---
```

correctly produces `4th August 2022` however other entry formats use American date interpretations.

According to the documentation [dates](https://quarto.org/docs/reference/dates.html), this is how it is described, however, it is surprising not to respect the geographic region of the locale `en-GB` 

> The [lang](https://pandoc.org/MANUAL.html#language-variables) document option is used to identifies the main language of the document using IETF language tags (following the [BCP 47](https://tools.ietf.org/html/bcp47) standard), such as en or en-GB.
>
> ...as well as the application of other language specific rules to document processing. - [lang-option](https://quarto.org/docs/authoring/language.html#lang-option)

## Expected Behaviour

```
---
title: Test
date: 04/08/2022
date-format: "Do MMMM YYYY"
lang: en-GB
---
```

Results in `4th August 2022`  not ~~`8th April 2022`~~

## Comparison to Pandoc native behaviour

Having used Pandoc for a while I thought that this worked, however it appears that I was mistaken and Pandoc doesn't format dates. I maybe wrong.

## Additional Info

OS: Linux/Ubuntu 22.04

### `quarto check` Output

[✓] Checking Quarto installation......OK
      Version: 1.0.37
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: /usr/bin/python3
      Jupyter: 4.11.1
      Kernels: python3, julia-1.6, julia-1.7

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

### `quarto tools check` Output

[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by dragonstyle** [comment]
The `date-format` specifically controls the output date format rather than the parsing of the input date. For the input date format, we do our best to parse the string into a date as described here:

<https://quarto.org/docs/reference/dates.html#date-parsing>

The lang might be a useful hint to improve how we parse that input date (I'll have a look though I'm not confident that it will be helpful), but in the meantime your best bet is to think of the date input value a distinct from the formatting and output.

**Comment by Andy2K11** [comment]
Thanks. Yes I realised but thought that it wouldn't be clear that the date wasn't being interpreted correctly if it merely output it `04/08/2022` because the reader would interpret it in the format they are used to. e.g. Americans would erroneously think the document was made in April, not realising that the author was British.

I did link to that documentation in my issue but to me it is still unexpected behaviour and means I have to remember to use a specific input date format with quarto when I'm used to putting dates into grey-matter in any standard format and specifying the `lang`.

If you think this should be marked as an enhancement instead of a bug that would make sense, to me it's a usability issue.

**Comment by dragonstyle** [comment]
I may be missing something - I'm interpreting this as a request to improve the way we parse a date (e.g. we convert that date string into a 'date' that can be formatted). 

- Pandoc provides a pretty standard set of dates it will parse to generate `date-meta` <https://pandoc.org/MANUAL.html#variables-set-automatically>. 
- We have a standard set of formats that we parse as well (derived from Pandoc) and we will ultimately try to guess or use an ISO date if none of those work. But I think guessing shouldn't be trusted in general as it is exactly the ambiguous cases (`01/01/2020`) that really will cause problem for guessing. 
- We could allow you to specify an input format, but that doesn't sound any easier to me versus just providing the date in a standard format. 
- We could try to use the locale to create a different list of formats to use when parsing date inputs, but of course this creates another problem which is that authors in different regions then have to be wary about the form of their date inputs, which could be interpreted wrongly when written. 

I haven't seen text based date input parsing that is locale aware, so if you have examples of this being done well, that would really help me out as I'm having trouble envisioning the best way to accomplish this. I'm happy to leave this open as an enhancement.

**Comment by Andy2K11** [comment]
You might be right, I did a demo in javascript:

```js
const date = new Date("04/08/2022");
console.log(date.toLocaleDateString());
console.log(date.toDateString(), "\n");

const today = new Date();
console.log(today.toLocaleDateString());
console.log(today.toDateString());
```

which produces

```
08/04/2022
Fri Apr 08 2022 

04/08/2022
Thu Aug 04 2022
```

So the current behaviour is consistent with this even if it's a little confusing to me. I shall close the issue and change my expectations.

**Comment by dragonstyle** [comment]
Dates are brutal even without timezones and daylight savings and all the rest! If you do find a good example of how we would make this easier, I would be happy to learn from it...

**Comment by Andy2K11** [comment]
There's a new experimental API in development called [Temporal](https://tc39.es/proposal-temporal/docs/index.html), though I'm not sure if that will directly help here.

Until that comes about the standard way of inputting dates without the locale confusion seems to be to use reverse date format e.g. `yyyy-MM-dd` [ISO8601](https://en.wikipedia.org/wiki/ISO_8601)

This already works in Quarto (I just discovered) and is in the documentation:

```
---
title: Test
date: 2022-08-04
date-format: "Do MMMM YYYY"
lang: en-GB
---
```

From now on I think I shall be using this standard format in my metadata. My only real practical suggestion then would be perhaps highlighting this as the preferred option in the docs, mostly it's a PICNIC problem (Problem In Chair Not In Computer), but I'm probably not the only person to have tripped up on this.

**Comment by Andy2K11** [comment]
Before I get into the weeds looking at this a little futher, I have drafted out some modifications to the documentation that might help. I can create a PR tomorrow for you to look at if you have no objections.

---

According to the [lang-option](https://quarto.org/docs/authoring/language.html#lang-option) docs, Quarto:

> "follows the [BCP47](https://www.rfc-editor.org/info/bcp47) standard"

In [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString#parameters)

> A string with a BCP 47 language tag, or an array of such strings. Corresponds to the locales parameter of the Intl.DateTimeFormat() constructor.

Trying this out with a date created with the ISO 8601 format in JavaScript produces:

```js
const date = new Date("2022-08-04");
console.log(date.toLocaleDateString("en"));         // 8/4/2022
console.log(date.toLocaleDateString("en-GB"));      // 04/08/2022
console.log(date.toDateString());                   // Thu Aug 04 2022
```

Reproducing this in Quarto doesn't yield the same result as the following metadata will produce `8/4/22` as the date, which corresponds to `lang: en`.

```yml
---
title: Test
date: 2022-08-04
date-format: short
lang: en-GB
---
```

Is `short` just an alias for `MM/dd/yy`?

It seems that Quarto isn't using the `en-GB` when ouputting dates either and this, while being a slight different issue, might be easier to fix. On the other hand, using the `short` style leads back to the same issue that readers may misinterpret the date depending on where they're from, so from a usability perspective it's problematic anyway.

What's really confusing is that two wrongs make it appear right:

```yml
---
title: Test
date: 04/08/2022
date-format: short
lang: en-GB
---
```

I think it's telling me the correct date, but actually I am misreading the wrong date. My assumption that the `lang: en-GB` tag would at least have some effect on dates appears to stem from thinking it works like locale strings as per my JavaScript example. Given the complexity of it all I'm not sure if that was a reasonable assumption to make.

A hacky fix to processing input dates could be to do this:

```js
const lang = "en-GB";
const date = new Date("4/8/2022");
const hack = new Date(date.toLocaleDateString(lang));

console.log(hack.toDateString());
```

Not sure how reliable it would be though. As I said, my approach now would be to encourage the use of ISO 8601 formats for date inputs and not to use short date formats in documents intended for an international audience.

**Comment by dragonstyle** [comment]
I was just playing with our support for this as I was expecting `short` to be responsive to the locale. The issue with the example:

```markdown
---
title: Test
date: 2022-08-04
date-format: short
lang: en-GB
---
```

Is that we are incorrectly being case sensitive to the `lang` parameter (try it with `en-gb` and the behavior is likely more what you're expecting). I'll fix that issue to make it case insensitive, which I think it more sensible.
