### ISSUE TITLE
Invalid epub created when index.qmd contains r code chunk

### ISSUE THREAD

**Issue by bwelman** [quarto-dev/quarto-cli#1695]
When index.qmd contains an r code chunk, rendering to epub creates an invalid epub file, that also can't opened as a zip file.

Example to reproduce this problem:

Create a Quarto Book from RStudio. When you specify Knitr as engine then the generated files index.qmd, intro.qmd and summary.qmd contain a simple r chunk. When you specify None as engine then you should add manuallly an R chunk to index.qmd.
Then add "epub: default" to "format:" in _quarto.yml (or replace the existing formats). After rendering the book to this or all formats, an epub file is created. But you can't open the file with an epub reader (Calibre) or with an zip app.

Remove the r chunk from index.qmd and render the book again to get a valid epub.

Used Quarto version: 1.0.37 (Windows 10)

**Comment by jjallaire** [comment]
Thanks for reporting! I can reproduce this locally. Will investigate.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/df7dbeb97e295a4d5f9ce33de779523043b2f9b3

This will be available in tomorrow's v1.1 pre-release build: https://quarto.org/docs/download/prerelease.html
