### ISSUE TITLE
Question: How are Julia environments handled? How to render with a project-specific environment?

### ISSUE THREAD

**Issue by svilupp** [quarto-dev/quarto-cli#1696]
First of all, thank you for this amazing tool!
***
One of the best features of Julia are the super easy project-specific environments, which are captured in the file `Project.toml`. These are meant to be independent of IJulia kernels (unlike conda+python). 

What is the default behaviour of Quarto when a `.qmd` file is rendered within a project with `Project.toml` file available?

What is the recommended approach to make sure that a file is rendered in a prescribed environment?
Is it to simply include an explicit cell with `Pkg`, eg, 
```
```{julia}
##| echo: false
##| output: false
using Pkg; Pkg.activate(".",io=devnull)
```
?

Thank you

**Comment by tbeason** [comment]
See my discussion here: https://github.com/quarto-dev/quarto-cli/discussions/1482

**Comment by jjallaire** [comment]
I appears as if Julia environments are automatically activated by IJulia  (including scanning up the directory tree to look for a Project.toml). This is at least what I am seeing with Julia 1.7 and a recently installed IJuila kernel.

**Comment by svilupp** [comment]
Closing to continue the discussion in #1482
