### ISSUE TITLE
Multi-column layout not supported for OJS

### ISSUE THREAD

**Issue by sushovan4** [quarto-dev/quarto-cli#1698]
### Bug description

The `layout-ncol` option for rendering a multi-column layout is not functional inside ojs code chucks. Despite having set the option `layout-ncol: 2`, the produced plots are stacked vertically.

A qmd fie containing a minimal example is here:
[ojs-plots.zip](https://github.com/quarto-dev/quarto-cli/files/9270061/ojs-plots.zip)

RStudio: 2022.11.0-daily+82
OS: Linux 5.15.0-43-generic Ubuntu 22.04

### `quarto check` Output

[✓] Checking Quarto installation......OK
      Version: 1.0.37
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: /usr/bin/python3
      Jupyter: 4.11.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /home/sushovan/R/x86_64-pc-linux-gnu-library/4.1
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

### `quarto tools check` Output

[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Thank you for catching that! This was a regression I introduced a few months back. Should be fixed now, and available on a 1.1 prerelease build coming up.
