### ISSUE TITLE
Resolve symlinks when installing an extension.

### ISSUE THREAD

**Issue by tarleb** [quarto-dev/quarto-cli#1700]
I have a test extension ([tarleb/test-extension](https://github.com/tarleb/test-extension)) that tries to keep a file outside of the `_extensions` folder. I'd like to use a symlink to make that file part of the extension.  However, `quarto install extension tarleb/test-extension` copies the symlink, which will usually point to a nonexisting file after the installation.

Here's the file structure of the source repository:

```
.
├── _extensions
│   └── test-extension
│       ├── _extension.yml
│       └── test-extension.lua -> ../../test-extension.lua
└── test-extension.lua
```

It would be convenient if the symlinks below `_extensions` could be replaced with the files/dirs that they point to, at least if those link targets are outside of the `test-extension` folder.

Background: I'd like to update the `tarleb/lua-filter-template` and make it easy for users of that template to provide filters as quarto extensions. Symlinking the filter would seem like a simple solution for that.

**Comment by jjallaire** [comment]
One possible alternative: since you have a Makefile already in the repo and presumably this is a part of "publishing" the lua filter, what about if the Makefile did the copy?

Realize that this might not be ideal or what you have in mind, just putting it out there for discussion. 

@dragonstyle Another thing we could consider is allowing references to files outside of the `_extensions` dir within `_extension.yml` (and those files would be automatically copied into `_extensions` and their paths resolved.

One reason I don't love the symlink idea is that it might be hard for us to resolve it on Windows (not sure if the Windows shell is able to resolve Posix symlinks and if not what the recourse would be).

**Comment by tarleb** [comment]
Ah, I hadn't consider Windows. I seem to remember that git has decent support for symlinks on Windows, but that may not be enough.

I'll go for the alternative solution then. Maybe I should also add a GitHub action to add these things when a new tag is pushed.

**Comment by jjallaire** [comment]
Yeah a GH action that runs the Makefile to copy the extension into place when a new tag is pushed would be great.

**Comment by tarleb** [comment]
Another reason that I'd like to have this feature is licensing: most extensions will most likely use an MIT-like license, and those require the copyright notice to be included whenever the code is redistributed. Example: Quarto users who install third-party extensions and check `_extensions` into source control will be violating the license if they open source their project -- at least strictly speaking. I doubt that extension authors would actually care.
I would have solved this by symlinking the LICENSE file, but maybe a `license` field in the `_extension.yml` could be a better solution?

**Comment by jjallaire** [comment]
Good point! Any LICENSE file should also be copied. @dragonstyle I think we should also encourage the use of a `license` field in `_extension.yml`

**Comment by tarleb** [comment]
I added a `make quarto-extension` target to the Makefile in tarleb/lua-filter-template`. It generates the extension files, moves the `.lua` file into a folder below `_extensions`, and replaces the original file with a symlink. So the direction of the symlink is reversed; it seemed like the most pragmatic solution.
https://github.com/tarleb/lua-filter-template/commit/1cdf374d3b267cf10d69578dad6b431261343edf

**Comment by jjallaire** [comment]
I'm going to close this issue now -- feel free to re-open if there are other things we can do to make this more straightforward.
