### ISSUE TITLE
ERROR: NotFound: The system cannot find the path specified. (os error 3), open '/tmp/file1'

### ISSUE THREAD

**Issue by burgerga** [quarto-dev/quarto-cli#1713]
### Bug description

Installing quarto preview to test out a possible bugfix for issue #1320

It seems like a unix path, but I'm on Windows. 

Git blame suggests https://github.com/quarto-dev/quarto-cli/commit/53e730e267e418a30c69a779fb735235d74740fd#diff-5918f8cb78f1ee5f520dadb760486aa0776451a52675a0f239c1829ff498f8c1 is when the issue was introduced.

### `quarto check` Output

```bash
C:\Users\burge\GitHub\quarto-web>quarto check

[>] Checking Quarto installation......OK
      Version: 1.1.48
      Path: C:\Users\burge\AppData\Local\Programs\Quarto\bin\
      CodePage: 65001

[>] Checking basic markdown render....OK

ERROR: NotFound: The system cannot find the path specified. (os error 3), open '/tmp/file1'
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [ ] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Oh yeah, that's ugly and needs fixing asap
