### ISSUE TITLE
Improve error message when you need to run `quarto publish netlify` once locally

### ISSUE THREAD

**Issue by DavisVaughan** [quarto-dev/quarto-cli#1724]
### Bug description

I tried to switch to the new quarto-publish GitHub Actions workflow for my blog and was hit with this

```
ERROR: No previous publishes available to re-publish (previous publish required with --no-prompt)
```

https://github.com/DavisVaughan/blog/runs/7715534347?check_suite_focus=true

I realized after reading more of the documentation that I needed to run `quarto publish netlify` once locally to create the `_publish.yml` locally (I ended up modifying the once it created with my pre-existing site ID and URL, but it was a useful skeleton).

Could this error message suggest: `` "Do you need to run `quarto publish netlify` locally?" ``

Error comes from here https://github.com/quarto-dev/quarto-cli/blob/3c6fa936a0c9a6ae36f127daf4c3b05c83a99f60/src/command/publish/deployment.ts#L117

Quarto 1.0.35

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thanks for this! I think that "Do you need to run `quarto publish netlify` locally?" might be a little too specific (as it doesn't cover your scenario of publishing to an existing site). I have made two changes that will hopefully address this:

(1) Improved error message: https://github.com/quarto-dev/quarto-cli/commit/2c23b8ebf326d9a9c7429918cdb24bbe9f8e9127

(2) Documentation more specifically addresses the scenario of publishing to an existing site: https://quarto.org/docs/publishing/netlify.html#publish.yml
