### ISSUE TITLE
Issue with using quarto template 

### ISSUE THREAD

**Issue by giabaio** [quarto-dev/quarto-cli#1753]
I seem to have a slight issue using a quarto template I have created. I followed the instructions [here](https://quarto.org/docs/extensions/formats.html), but when I pull the template from the GitHub repo I have made, using
```
quarto use template giabaio/my-repo
```
quarto creates a `giabaio` folder under `_extension`. So the resulting files are
```
new_folder
   - new_folder.qmd
   - _extensions
      - giabaio
         - all the stuff that should be under _extension
 ```

This has repercussions to my workflow, because the `template.qmd` file looks for stuff under `_extensions/name_of_the_template`, which is actually now stored under `_extensions/giabaio/name_of_the_template`.

Am I making some silly mistake? Or do I simply need to remove the `giabaio` folder and place everything else under `_extensions` manually?

Thanks!
Gianluca

**Comment by mcanouil** [comment]
This is the expected/intended behaviour at least for now.
The structure is correct, it's simply now there is no proper way to user what's in the extension in the template without providing the full install path, which is `_extensions/<namespace>/<extension-name>/...`.

This issue was first posted in #1538

**Comment by giabaio** [comment]
OK --- thanks. I thought I was messing this up...

**Comment by dragonstyle** [comment]
I'd say that templates shouldn't directly address things within the extensions folder. Extensions exist primarily to provide shortcodes, filters, and formats. If you are referencing a format, it can add metadata that will be used during the render (including elements using file paths that are relative to the `_extension.yml` file). If there is a file that you need to reference directly from the `qmd` source file, you can use the `format-resources` key to have that resource copied to the directory containing the input.

I just fixed #1538 which was preventing this from working properly for HTML formats.

**Comment by mcanouil** [comment]
Thanks @dragonstyle , I'll check this when I can.
I assume it's going to be part of the next pre-release version, right?

**Comment by dragonstyle** [comment]
Yep, exactly! The bug was pretty egregious (overwriting the dependencies when the format was HTML) and your test case was great- thank you!
