### ISSUE TITLE
Quarto-cli called from Rstudio throws 'CreateProcess' failed to run

### ISSUE THREAD

**Issue by pokyah** [quarto-dev/quarto-cli#1760]
## Problem 

Compiling .qmd docs from Windows PowerShell works fine. But while trying to compile from Rstudio it fails. 

## Reprex 

The test file I'm using comes from the official quarto website: https://quarto.org/docs/get-started/hello/rstudio/_hello.qmd

### Powershell
Running `quarto render hello.qmd` within PowerShell works perfectly.

#### Render Button
If I open the `hello.qmd` file in Rstudio en press the Render button I got the following error: 

```
Message d'avis :
Dans system(paste0("quarto render \"", input, "\" ", "--to default")) :
  'CreateProcess' a échoué au lancement de 'C:\Users\TGOOSS~1\AppData\Local\Programs\Quarto\bin\quarto.cmd render "C:/Users/tgoossens/Desktop/test_rmarkdown/test.qmd" --to default'
```

#### R console 

If I call `quarto::quarto_render(hello.qmd)` from the R console I got the following error:

```
Error in `process_initialize(self, private, command, args, stdin, stdout, …`:
! Native call to `processx_exec` failed
Caused by error in `chain_call(c_processx_exec, command, c(command, args), pty, pty_options, …`:
! create process 'C:\Users\TGOOSS~1\AppData\Local\Programs\Quarto\bin\quarto.cmd' (system error 2, The system cannot find the file specified.
) @win/processx.c:1040 (processx_exec)
Type .Last.error to see the more details.
```
Result from `quarto::quarto_path()` : 

`[1] "C:\\Users\\TGOOSS~1\\AppData\\Local\\Programs\\Quarto\\bin\\quarto.cmd"`

Result from `quarto::quarto_version()`:

```
Error in system2(quarto_bin, "--version", stdout = TRUE) : 
  'CreateProcess' failed to run 'C:\Users\TGOOSS~1\AppData\Local\Programs\Quarto\bin\quarto.cmd --version'
```

## Session info : 
```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=French_Belgium.utf8  LC_CTYPE=French_Belgium.utf8    LC_MONETARY=French_Belgium.utf8
[4] LC_NUMERIC=C                    LC_TIME=French_Belgium.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9      ps_1.7.1        digest_0.6.29   later_1.3.0     R6_2.5.1        jsonlite_1.8.0 
 [7] evaluate_0.15   rlang_1.0.4     cli_3.3.0       rstudioapi_0.13 rmarkdown_2.14  tools_4.2.1    
[13] glue_1.6.2      xfun_0.31       yaml_2.3.5      fastmap_1.1.0   compiler_4.2.1  processx_3.7.0 
[19] htmltools_0.5.3 knitr_1.39      quarto_1.2 
```

## Similar issues/threads : 

* https://community.rstudio.com/t/failed-to-run-c-pdflatex-exe/49079/4
* https://github.com/rstudio/tinytex/issues/208
* https://github.com/rstudio/rstudio/issues/5681
* https://community.rstudio.com/t/error-generating-pdf-in-r-markdown/60003

## Remark 

The problem was privately discussed with @cderv 

=========

Thanks or your help

**Comment by cderv** [comment]
@pokyah would you be able to try out our latest version https://quarto.org/docs/download/ ? 

We encountered this type of issue already with TinyTeX as tlmgr also use a BATCH file on windows. 
We are now offering a `quarto.exe` file to overcome several issues we had with path and CMD on Windows. 

RStudio IDE will need to support it though, maybe next version. 

However, **quarto** R package should find it correctly I believe. You can check with `quarto::quarto_path()` as you did.

**Comment by cderv** [comment]
@pokyah can you confirm is 1.1 or 1.2 is solving the issue for you ? 

Thank you !

**Comment by pokyah** [comment]
Hi @cderv.

I'll try these this afternoon and give you a feedback.

Best regards

**Comment by pokyah** [comment]
So a quick test for version 1.2.131 gives the following results :

- Everything running smooth while clicking on the render button
- Still the error while trying to call render from the console : 
```
> quarto::quarto_render("hello.qmd")
Error in `process_initialize(self, private, command, args, stdin, stdout, …`:
! Native call to `processx_exec` failed
Caused by error in `chain_call(c_processx_exec, command, c(command, args), pty, pty_options, …`:
! create process 'C:/Users/tgoossens/AppData/Local/Programs/Quarto/bin/quarto.cmd' (system error 2, The system cannot find the file specified.
) @win/processx.c:1040 (processx_exec)
Type .Last.error to see the more details.
```
Let me know if you need me doing other testing.

Best regards
- still working from Powershell

**Comment by cderv** [comment]
> ! create process 'C:/Users/tgoossens/AppData/Local/Programs/Quarto/bin/quarto.cmd' (system error 2, The system cannot find the file specified.
) @win/processx.c:1040 (processx_exec)

Is this file existing on your environment ? I am wondering why you don't get the exe file now that you are using `1.2.131` 🤔 

Can you share results of `quarto check` in terminal and inside RStudio terminal ? 
What does `Sys.which("quarto")` gives too ? 

does it give the same version as `quarto:::find_quarto()` ? Just to be sure you don't have a `QUARTO_PATH` env var set.

**Comment by pokyah** [comment]
Here is an overview of console/terminal outputs

```
> file.exists("C:/Users/tgoossens/AppData/Local/Programs/Quarto/bin/quarto.cmd
+ ")
[1] FALSE
```

```
> Sys.which("quarto")
                                                                  quarto 
"C:\\Users\\TGOOSS~1\\AppData\\Local\\Programs\\Quarto\\bin\\quarto.exe"
```

```
> quarto:::find_quarto()
[1] "C:/Users/tgoossens/AppData/Local/Programs/Quarto/bin/quarto.cmd"
```

# in terminal
```
$ quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.131
      Path: C:\Users\tgoossens\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: C:/Users/tgoossens/AppData/Local/Programs/Python/Python39/python.exe
      Jupyter: 4.8.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/Users/tgoossens/R/R-4.2.1
      LibPaths:
        - C:/Users/tgoossens/AppData/Local/R/win-library/4.2
        - C:/Users/tgoossens/R/R-4.2.1/library
      rmarkdown: 2.16

[>] Checking Knitr engine render......OK
```

in Rstudio terminal

```
$ quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.131
      Path: C:\Users\tgoossens\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: C:/Users/tgoossens/AppData/Local/Programs/Python/Python39/python.exe
      Jupyter: 4.8.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/tgoossens/AppData/Local/R/cache/R/renv/library/benFactoR-09bc8696/R-4.2/x86_64-w64-mingw32
        - C:/Program Files/R/R-4.2.1/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
> quarto:::find_quarto()
[1] "C:/Users/tgoossens/AppData/Local/Programs/Quarto/bin/quarto.cmd"


Can you check if you have somehow set this env var on your system ? 

````
Sys.getenv("QUARTO_PATH", unset = NA)
````

This would explain why `quarto:::find_quarto()` and `Sys.which("quarto")` ? 

By setting the env var, your are pointing to a specific file that does not exist anymore, and **quarto** R package will use it.

**Comment by pokyah** [comment]
Indeed, I had this : 

> Sys.getenv("QUARTO_PATH", unset = NA)
[1] "C:/Users/tgoossens/AppData/Local/Programs/Quarto/bin/quarto.cmd"

That's pulled outof my .Renviron file.

But I don't remember why I've set this in the past ...

**Comment by cderv** [comment]
Is this working if you remove this ?

**Comment by pokyah** [comment]
Yes!

Sorry for that this stupid remaining ENV VAR was causing such troubles. 

Thanks for helping investigate this @cderv

**Comment by cderv** [comment]
Awesome. Glad it works now.
