### ISSUE TITLE
Can't reproduce Quarto documentation: Component Layout: Input Panel

### ISSUE THREAD

**Issue by novotny1akub** [quarto-dev/quarto-cli#1764]
### Bug description

I can't reproduce an example in the Quarto [documentation](https://quarto.org/docs/interactive/layout.html). The example shows how to change the layout of input filters so that the filters are next to each other. When I try to reproduce this, the inputs are below each other.  I am on Windows and am running the RStudio version 2022.07.1 Build 554

````md
---
title: Issue with multiple columns in input panel
format:
  html:
    self-contained: true
    code-fold: true
---

```{ojs}
//| panel: input
//| layout-ncol: 3

//| https://quarto.org/docs/interactive/layout.html
viewof color1 = Inputs.checkbox(["red", "green", "blue"], {label: "color1"})

viewof color2 = Inputs.radio(["red", "green", "blue"], {label: "color2"})

viewof rng = Inputs.range(
  [1,10],{
  value: 3,
  step: 1
})
```
````

![image](https://user-images.githubusercontent.com/39886440/183700358-65c30b0c-ab38-4f55-8a0c-d4b362afd72f.png)

### `quarto check` Output

```bash
[>] Checking Quarto installation......OK
      Version: 1.0.38
      Path: C:\Users\wn00198624\AppData\Local\Programs\Quarto\bin\
      CodePage: 1250

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/Users/wn00198624/AppData/Local/Programs/R/R-4.2.0
      LibPaths:
        - C:/Users/wn00198624/AppData/Local/Programs/R/R-4.2.0/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```md
Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
The issue here is that those three panels take a lot of room. Stretch your window horizontally and they'll start taking multiple columns:

Narrow window:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/285675/183708824-18584d2d-0ddc-4907-bf89-362577cbfd8f.png">

Wide window:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/285675/183708870-5526f178-9a1e-46f8-a4f8-49426613a78c.png">

**Comment by novotny1akub** [comment]
For some reason, I can't reproduce it.
````
---
title: Test
format:
  html:
    self-contained: true
    code-fold: true
    page-layout: custom
---

::: {.grid}
::: {.g-col-12}

```{ojs}
//| layout-ncol: 3

viewof color1 = Inputs.checkbox(["red", "green", "blue"], {label: "color1"})

viewof color2 = Inputs.radio(["red", "green", "blue"], {label: "color2"})

viewof rng = Inputs.range(
  [1,10],{
  value: 3,
  step: 1
})

```
:::
:::
````

![image](https://user-images.githubusercontent.com/39886440/183714448-71579b6f-1730-45ff-abed-41315a5b6d36.png)

**Comment by novotny1akub** [comment]
I hope it can be seen from the picture how wide my window is yet those three panels do not take multiple columns.

**Comment by cscheid** [comment]
This new document is not the same as the previous one you shared, right? This new one has `page-layout: custom`, which I believe controls the panel behavior.

**Comment by novotny1akub** [comment]
To me, it does not seem to be working even if I add `//| panel: input` in the `ojs` cell. When inspecting Chrome's devtools, I noticed that there were some problems with loading the content of `bootstrap.bundle.min.js.map`. Could this cause this behaviour?

![image](https://user-images.githubusercontent.com/39886440/183872451-227d5227-3917-48a1-90d1-67ecf807af2f.png)

**Comment by cscheid** [comment]
No, that's a warning (yellow sign) and not an error.

With that said, I see that you're running from the `file://` scheme. That won't work for javascript-heavy html pages. You need to be running from `http://`, which means you need to have a web server. `quarto preview` from the command line will do that for you. If you have python installed, you can also type `python3 -m http.server 8080` to start a server on port 8080.

**Comment by novotny1akub** [comment]
I tried your suggestion, but to no avail I am afraid.

![image](https://user-images.githubusercontent.com/39886440/183943680-d4721304-81c7-416d-b9a9-fa4a2fecd062.png)

The code I am using.

````
---
title: Test
format:
  html:
    self-contained: true
    code-fold: true
    page-layout: custom
---

::: {.grid}
::: {.g-col-12}

```{ojs}
//| panel: input
//| layout-ncol: 3

viewof color1 = Inputs.checkbox(["red", "green", "blue"], {label:     "color1"})

viewof color2 = Inputs.radio(["red", "green", "blue"], {label:     "color2"})

viewof rng = Inputs.range(
  [1,10],{
  value: 3,
  step: 1
})

```
:::
:::
````

**Comment by cscheid** [comment]
This file works for me in VS Code and on the latest versions of Chrome, Safari, and Firefox. Are you on Edge, by any chance?

**Comment by cscheid** [comment]
I'll need to coordinate with @cderv as our Windows expert, but that will be a couple of weeks at least.

**Comment by cscheid** [comment]
@novotny1akub Can you try installing the very latest pre-release version of quarto? I think that might have been fixed then.

**Comment by novotny1akub** [comment]
I can confirm that the issue is no longer occuring with `quarto-1.1.57-win.msi` (pre release version). Thanks a lot for your help.
