### ISSUE TITLE
unable to find R installation

### ISSUE THREAD

**Issue by EOneita** [quarto-dev/quarto-cli#1765]
I am using Mac OS Monterey Version 12.5, the latest versions of R (4.2.1), R Studio (2022/07, 1-554), and Quarto (1.0.38), and the `rmarkdown` package (2.14). When attempting to render Quarto (the given `hello.qmd` file), I see the following error:

```
Error in assignInNamespace("htmlPreserve", htmlPreserve, ns = "htmltools") : 
  could not find function "assignInNamespace"
Calls: .main -> source -> withVisible -> eval -> eval
Execution halted
Error in packageVersion("rmarkdown") : 
  could not find function "packageVersion"
Calls: cat -> paste0
Execution halted

Unable to locate an installed version of R.
Install R from https://cloud.r-project.org/
```
What I have done so far to try to address this issue:
1) Tried to manually set the PATH to the R library(s): https://community.rstudio.com/t/adding-to-the-path-variable/12066
```
old_path <- Sys.getenv("PATH")

Sys.setenv(PATH = paste(old_path, "/Library/Frameworks/R.framework/Resources/library", sep = ":"))
```
2) Tried to override QUARTO_R to (what I believe) is the directory R is in (consulting this [issue](https://community.rstudio.com/t/render-with-quarto-error/134403)).

`Sys.setenv('QUARTO_R' = '/Library/Frameworks/R.framework/Resources')`

FYI, R is working otherwise fine. I am able to use it as normal, so R Studio itself can clearly recognize that its there.
 
Render is working just fine on my work desktop, which is running an older version of R (4.1.1), but which is otherwise the same (updated OS, RStudio, and Quarto). The only thing I can think of is that on my laptop, there is something problematic going on with administrator privileges. However, I am not sure how to tinker in Terminal to identify the error and set appropriate paths.

Any assistance is greatly appreciated!

**Comment by EOneita** [comment]
Update: the PATH for my desktop (which is working) is:

`/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/edavis/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Applications/RStudio.app/Contents/MacOS`

The PATH for my laptop (which is not working) is:

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/elizabethdavis/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Applications/[RStudio.app/Contents/MacOS](http://rstudio.app/Contents/MacOS`

Obviously there are some important differences there- but I'm not sure how to address the issues.

**Comment by cscheid** [comment]
It looks like the path on your laptop has a malformed line here:

```
/Applications/[RStudio.app/Contents/MacOS](http://rstudio.app/Contents/MacOS
```

I'm wondering how that entry ended up this way.

**Comment by EOneita** [comment]
My apologies- I think that was an issue with Markdown formatting for GitHub. This is the PATH:

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/elizabethdavis/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Applications/RStudio.app/Contents/MacOS`

I do note that for whatever reason, it does not seem to be looking in my Library. I'll do some digging on my end to see if there's a way to change that. As I said I have tried to manually set the `Sys.setenv()` and it hasn't seemed to work. I think something is going on in the backend to affect this, but I'm not sure what.

**Comment by jjallaire** [comment]
This sort of issue is typically a mismatch between the version of R running and the system or user library it is loading code from (which is likely pointing to another version of R). Often this is due to environment variables left over in shell initialization scripts.

In any case, I don't think this has anything to do with Quarto as we just call R from the shell. Note that one thing which might be of help in debugging is that Quarto will respect a `QUARTO_R` environment variable if defined to tell it where to locate R.
