### ISSUE TITLE
Display style math syntax not compliant with Pandoc documentation

### ISSUE THREAD

**Issue by glimmerphoenix** [quarto-dev/quarto-cli#1781]
### Bug description

Syntax to insert display style math equations in Quarto documents does not follow conventions explained in the [math section of Pandoc user manual](https://pandoc.org/MANUAL.html#math). 

This issue does not affect inline math expressions and it is probably related to issue report #1181, currently in progress.

This is a minimal reproducible example: https://gist.github.com/glimmerphoenix/641d5e35d7194abadb721c0d9b1e14f2.

In summary:

- Math delimiter for display style expressions must be `$$ ... $$` and preferably written in the same line as the math equation.
- The following option documented in the Pandoc user manual does not work in Quarto:
> In this case, the delimiters may be separated from the formula by whitespace.
  
- The parser still works after invalid inline math expressions, but stops working after the first display style math expression with incorrect syntax. Not sure if this is due to Quarto or Pandoc internal conversion.
- Finally, the recommended syntax for Quarto math expressions described in #1181, suggesting to leave each `$$` delimiter in a separate line, is valid according to Pandoc documentation but does not follow the standard syntax for document convertion. In fact, as I have commented in #1181, both syntax alternatives (`$$` in same line vs. `$$` in a separate line) cannot be mixed in the same document, since the parser stops working at all.

**OS and packages info**
- Platform: Linux, Ubuntu 20.04
- R: 4.2.1
- RStudio: 2022.07.1 Build 554
- Quarto: 1.0.38
- quarto CRAN package: 1.2

### `quarto check` Output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in miniconda3. Did you forget to activate it?

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /home/jfelipe/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
I think this may be an issue in Pandoc's math parsing. If I execute the document with raw pandoc (note the `quarto pandoc` command can pass through to the embedded version of pandoc):

```bash
quarto pandoc math.qmd --from markdown --to html --standalone --output math.html
```

I see the same rendering behavior exhibited in math.html and these warnings printed:

```bash
[WARNING] Could not convert TeX math r_1\; = \; \frac{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})(x_{t+1}-\bar{x})}
  {\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})^2}, rendering as TeX
[WARNING] Could not convert TeX math  r_1\; = \; \frac{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})(x_{t+1}-\bar{x})}
  {\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})^2} , rendering as TeX
[WARNING] Could not convert TeX math r_1\; = \; \frac{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})(x_{t+1}-\bar{x})}
  {\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})^2}, rendering as TeX
```

**Comment by jjallaire** [comment]
Going to close this as it seems we are in any case matching the Math rendering behavior of Pandoc (so any change to behavior or documentation would need to happen there).

**Comment by glimmerphoenix** [comment]
Hello, and sorry for the delay in answering.

@jjallaire, the command above to compile the example is incomplete. An argument is missing to indicate the math rendering engine that must be used (see example 17 in [Pandoc demos](https://pandoc.org/demos.html)).

This command produces a correct HTML output file, using the embedded Pandoc version in Quarto:

```
quarto pandoc math.qmd --from markdown --to html --standalone --mathjax --output math.html
```
Note the extra `--mathjax` argument, that can be changed to any of the other valid engines that can also be configured in the Quarto file YAML header for HTML format. 

Thus, I believe Pandoc is working fine and as documented, but Quarto may not be calling the Pandoc command with the correct list of config arguments. I have also tested that it works fine with the standalone, newer Pandoc version 2.5 installed in my system.

Hope this helps.

**Comment by jjallaire** [comment]
@glimmerphoenix Thank you for the persistence, there is indeed a Quarto issue here!

@cscheid The problem appears to be that our `breakQuartoMd()` logic isn't detecting display math as-per Pandoc's rules. After running through our preliminaries the following markdown:

```markdown
$$r_1\; = \; \frac{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})(x_{t+1}-\bar{x})}
{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})^2}$$

$$ r_1\; = \; \frac{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})(x_{t+1}-\bar{x})}
{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})^2} $$
```

Is converted to the following (which breaks the second display math block):

```markdown
$$r_1\; = \; \frac{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})(x_{t+1}-\bar{x})}
{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})^2}$$

$$ r_1\; = \; \frac{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})(x_{t+1}-\bar{x})}


{\displaystyle\sum_{t=1}^{N-1}(x_t-\bar{x})^2} $$
```


If I comment out these lines then things work as expected: https://github.com/quarto-dev/quarto-cli/blob/main/src/core/lib/break-quarto-md.ts#L246-L263

**Comment by cscheid** [comment]
It looks like I introduced this [back in June 2021](https://github.com/quarto-dev/quarto-cli/commit/b94d97f58777a29427bf214789e7ba3234b07c79#diff-7b36f2dd83212fe36232e7225644f8718a17828d0949c4be06cf50aa99d3433eR50).
