### ISSUE TITLE
Add PDF as image leads to unexpected html output in quarto book

### ISSUE THREAD

**Issue by jpmorr** [quarto-dev/quarto-cli#1791]
### Bug description

I've just started using quarto and decided to convert an old `LaTeX` book into a new quarto document and have started the process of learning and translating. I'm come across what I think is strange behaviour for the html output. 

I have a series of figures that were compiled from `tikz` documents into PDF files and I want to include this pdfs as images.
I assume that the simple figure syntax would also work for pdfs so I've added the figure as:
```md
![Particles A and B are in contact for the purposes of bonding](images/ContactRadius.pdf){#fig-bondContactRadius}

```
and this is generated as:
![Rendered quarto html output](https://user-images.githubusercontent.com/10863809/183922407-edadae30-4b15-42b8-bc46-404e85e5f14e.png)

I'm not sure why the figure is a) rendered so small and b) seems to be in some scrolling window. Is there something special needed to include pdf files as images? 

I'm using VS Code on windows if that matters.

### `quarto check` Output

```bash
>quarto check
      Kernels: julia-1.4, julia-1.6, julia-1.7, juliapro_v1.5.4-1-1.5, pycharm-20203b08, python3, iota

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.1.3
      Path: C:/PROGRA~1/R/R-41~1.3
      LibPaths:
        - C:/Users/xxx/Documents/R/win-library/4.1
        - C:/Program Files/R/R-4.1.3/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
>quarto tools check 
[>] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08

D:\Workspace\quarto\book>
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Generally speaking, PDF images are not well supported in html documents. Since you've generated these ahead of time, I think the easiest solution is to batch-convert them to a format like PNG, and then use our content-directives to select between those two at render time: https://quarto.org/docs/authoring/conditional.html

**Comment by jjallaire** [comment]
You can also switch between image formats by just leaving the extension off the file and then relying on `default-image-extension`: https://quarto.org/docs/authoring/figures.html#multiformat-figures

**Comment by jpmorr** [comment]
@cscheid Thanks for the info. Since these are just `.tex` files that compile to pdf, is there a way to  possibly include them into `quarto` so that it compiles the `tex` file and generates the `.svg` file?

I can easily go back and convert these, but just want to figure out what is possible.

**Comment by cscheid** [comment]
@jpmorr I can't think of a straightforward way to do that right away, because those .tex files have to be compiled _before_ the .qmd files, and I don't think we have a concrete mechanism for "inter-file dependencies" like this.

**Comment by jpmorr** [comment]
OK, I'll keep an eye out for something in the future if it happens. Thanks
