### ISSUE TITLE
terminate jupyter daemon on ctrl+c (in preview or render)

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#181]
From @cscheid:

I think I just ran into a bug with quarto preview, the python daemon, and an admittedly funky python chunk. If you have a python cell that runs a long-running subprocess.call , and you ctrl-c the preview while it’s running, the subprocess keeps going.

I don’t know if there’s a not-horrible way to fix it, but it felt bad to have to manually kill -9 some stuff.

**Comment by cscheid** [comment]
Thanks, @jjallaire! I'll work on a minimal repro case in the next day or so (it came up in some research code from a previous proj of mine.)

**Comment by jjallaire** [comment]
This should resolve the issue: https://github.com/quarto-dev/quarto-cli/commit/28c3a8be09c4b2207a962611db854cdd6e7863e2

Now if we encounter any error whatsoever during Jupyter kernel execution we automatically restart the daemon.
