### ISSUE TITLE
Output visibility is not respected for Observable JS cells in Hugo output

### ISSUE THREAD

**Issue by aaronschiff** [quarto-dev/quarto-cli#1812]
### Bug description

When outputting OJS cells in Hugo format, I can't seem to get the output of assignments to disappear. According to the Quarto [documentation](https://quarto.org/docs/interactive/ojs/ojs-cells.html#output-visibility), cells that are only assignments should not print their output, and the `output` option can also be used to suppress output for a cell. However, when I use quarto to render the qmd to a Hugo md, and then Hugo to render html, assignment output always appears. 

Here is a simple qmd example: 

[index.qmd.txt](https://github.com/quarto-dev/quarto-cli/files/9306319/index.qmd.txt)

When I run this I get the following output from Hugo, despite specifying `//| output: false` for the assignment cell. 

<img width="681" alt="Screen Shot 2022-08-11 at 17 39 18" src="https://user-images.githubusercontent.com/10150126/184070638-d2b3c665-6f59-49c8-9d93-5281803933bc.png">

If instead I render directly to html, the assignment output is suppressed as it should be.

<img width="690" alt="Screen Shot 2022-08-11 at 17 40 14" src="https://user-images.githubusercontent.com/10150126/184070699-01bf94df-3aca-4ad4-9ebc-ed8a258823e5.png">

OS: MacOS 12.4

### `quarto check` Output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13
      Path: /opt/homebrew/opt/python@3.9/bin/python3.9
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Up to date        v2022.08      v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
@cscheid This could be because we are relying on the `.hidden` class which is likely not present in Hugo. Ping me when you are online and we can discuss other things that could be going on.

**Comment by cscheid** [comment]
I've improved the CSS handling of OJS elements in non-bootstrap settings somewhat.

A full fix for this class of problems will require a fairly major overhaul of our handling of the DOM across different HTML formats. Progress on this is tracked in #1825.

**Comment by aaronschiff** [comment]
Thanks for looking into this so quickly!
