### ISSUE TITLE
Quarto installation not working on MacBook Air M1

### ISSUE THREAD

**Issue by lilianavalenciar** [quarto-dev/quarto-cli#1819]
### Bug description

I've been trying to get Quarto working with VS code on a MacBook Air M1 (2020). Installing the extension (version 1.30.0) on VS does seem to works, however when I try to render, it always ask me to install quarto and send me to the downloading page. I have downloaded the package for Mac (version 1.0.38) and installed multiple times but it doesn't work. When I try to render it says that quarto is not installed. I have try to run quarto on terminal and I always get command not found. 

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [ ] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
I'm sorry you're running into trouble.

> I have downloaded the package for Mac (version 1.0.38) and installed multiple times but it doesn't work

Our installer should place the binaries in a place that is accessible in your path. Can you share the value of the environment variable `PATH` in your terminal?

```bash
echo $PATH
```

**Comment by lilianavalenciar** [comment]
Hey! Thanks for reaching out. 
This is the output I get from the echo:
"/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

**Comment by dragonstyle** [comment]
Have you restarted vscode since you installed? It could be that it's terminal and process aren't reflecting the updated path....

**Comment by lilianavalenciar** [comment]
Indeed. I have even restarted my laptop.

**Comment by dragonstyle** [comment]
Post install we try to do two things to make quarto accessible:

> create a symlink at `/usr/local/bin/quarto`

Can you check to see whether there is a broken symlink there (I did this on my machine with `find -L /usr/local/bin -maxdepth 1 -type l` which should only print symlinks that point to non-existing files).

> add the quarto bin directory to `.zshenv`

Can you check to see whether that file includes the quarto path?

**Comment by lilianavalenciar** [comment]
Ok... I'll need a little more of detail here. 

I'm trying to create the symlink with 
`ln -s /Applications/quarto/bin /usr/local/bin/quarto` 
However I get this: ln: /usr/local/bin/quarto: No such file or directory

I try to get to the folder  '/usr/local/bin' but that actually doesn't exit on my system, at least as a folder. What I do have is /usr/bin but if I try to do `ln -s /Applications/quarto/bin /usr/bin/quarto` I get this ln: /usr/bin/quarto: Operation not permitted.

I have checked and the quarto folder is in Applications. 

Also, I wouldn't know how to add quarto bin to .zshenv

**Comment by cscheid** [comment]
> Also, I wouldn't know how to add quarto bin to .zshenv

Open `$HOME/.zshrc` in a text editor, and you will see somewhere a statement like

```bash
export PATH=...
```

After this statement, add the following line:

```bash
export PATH=$PATH:/Applications/quarto/bin/
```

**Comment by milti** [comment]
im trying to run quarto in vscodium+Rstudio on an m2 macbook air, it installs and i can get the Rstudio tutorial to work, but dont seem to be able to start another document: the vscode tutorial will not render complaining abt the numpy installation, but the code cell runs w no complaints.

would this be the correct issue OR should i create a new one specifically for my issues?

**Comment by cscheid** [comment]
@milti if you're having trouble with python specifically (numpy), then it's a separate issue. Although you might want to check that the architecture of the binaries for VS code, python, and quarto are all compatible; this is something other Apple silicon users have had trouble with.

**Comment by milti** [comment]
@cscheid thats the curious part, the cell runs fine, even plots the resulting image: its specifically the quarto:render that fails, not the python code; but ill do as directed.

**Comment by cscheid** [comment]
@milti got it. Please file an issue. The more information the better (our template has a checklist that it'd be very helpful if you'd follow).

**Comment by jspaezp** [comment]
in a (maybe) related issue.

Since there is a homebrew cask for quarto. Which worked perfectly for me.
Could the official installation method for mac include it?
https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/quarto.rb
https://github.com/p-linnane seems to be maintaining the formula.

What would be the implications of "supporting" the homebrew installation process, would that be of interest?

Best,
Sebastian

**Comment by cscheid** [comment]
I would be reluctant to burden volunteer developers with an implication that their work is officially supported in any capacity. We are extremely grateful for the work of folks like @p-linnane. If we were to advertise that on our front page, then we risk users reaching out to the formula maintainers at a rate that is disproportionate to the time volunteers dev have to devote to the project.

At the same time, we are ourselves a very small dev team that already has to support three different operating systems. Right now, we would rather use our time to develop a high-quality core product.
