### ISSUE TITLE
Calling gt functions breaks table numbering for kable in PDF

### ISSUE THREAD

**Issue by eeholmes** [quarto-dev/quarto-cli#1826]
### Bug description

RStudio: 2022.07.1 Build 554
OS: M1 Mac Air

A call to make a `gt::gt()` in R, breaks all subsequent table numbering for `kbl()` tables called after the `gt()` call even if the {gt} library isn't loaded. This only happens when building to PDF.  If `eval=FALSE` is added to the `gt()` chunk, then then table numbers re-appear.

Sample qmd file

<pre>
---
title: "test"
format: pdf
---

```{r}
#| label: tbl-kbl
#| tbl-cap: "first kable call: this should have a number"
library(knitr)
kableExtra::kbl(head(mtcars[1:2,]), booktabs=TRUE)
```

```{r}
#| label: tbl-gt
#| tbl-cap: "table numbering is broken with gt"
gt::gt(mtcars[1:2,])
```

```{r}
#| label: tbl-kbl2
#| tbl-cap: "second kable call: this should have a number"
kableExtra::kbl(head(mtcars[1:2,]), booktabs=TRUE)
```
</pre>

<img width="396" alt="image" src="https://user-images.githubusercontent.com/2545978/184181127-45deb863-608c-4c90-a292-70e1054b6470.png">

### `quarto check` Output

```
[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12
      Path: /opt/homebrew/opt/python@3.9/bin/python3.9
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.1.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/eli.holmes/Library/R/x86_64/4.1/library
        - /Library/Frameworks/R.framework/Versions/4.1/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```
[✓] Inspecting tools

Tool         Status                    Installed     Latest  
chromium     Not installed             ---           869685  
tinytex      External Installation     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
All `r` code cells are evaluated in the same context, so in that third cell, `gt` is still definitely loaded.

We try hard to support multiple table libraries, but we cannot practically support different table libraries in a single document.

**Comment by eeholmes** [comment]
Ok. I am teaching Quarto and was writing a doc that compared different table outputs.

**Comment by cscheid** [comment]
Yeah, I understand :( I agree that's a totally reasonable thing to want to do! It's just that on our side, each library does a potentially different thing, and keeping everything in order becomes impractical.

In the medium term (~about 6-12 months), we are going to be more strict about how these different libraries are supposed to work (see #1825), and hopefully most of these issues will go away. But in the short term I would just recommend using different documents to showcase this.

**Comment by eeholmes** [comment]
FYI. unloading the gt() namespace doesn't help. I put this before the second `kbl()` call
```
unloadNamespace(asNamespace("gt"))
isNamespaceLoaded("gt")
```

Also FYI for a minimal example for the GH issue, I made one qmd doc, but I discovered it in a Quarto book. The gt() call is in a separate qmd chapter but a single `gt::gt()` call breaks all table numbers in the PDF for the subsequent chapters.

**Comment by eeholmes** [comment]
Final update. It looks like it is a problem with the {gt} package with Quarto and PDF. A call to `gt()` even breaks these table numbers. Even with the `unloadNamespace(asNamespace("gt"))` above it.

```
| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: My Caption {#tbl-letters}
```

**Comment by cscheid** [comment]
Can you share a github repository with the book setup?

**Comment by eeholmes** [comment]
Here is the repo: https://github.com/RVerse-Tutorials/QmdReport

I am working on a template for government reports using Quarto. So some of the things might look weird. We build R Markdown dynamically based on data, so lots of tables in for loop issues and must have the table cross refs retained across different formats. It's actually mostly working now.

**Comment by cscheid** [comment]
Thank you, that's very helpful. The notes in that repository are also very helpful. Do you mind if I reach out directly to you in email to see if we can help address some of them?

**Comment by cscheid** [comment]
I can reproduce the issue with table numbering in GT. It appears to be a GT bug [here](https://github.com/rstudio/gt/blob/0be501c2aeb2653677778b6f7ca4935f6cc9e977/R/utils_render_latex.R#L80), by inspecting the emitted `.tex` output. I'll follow up with @rich-iannone (GT author directly) about this.

**Comment by eeholmes** [comment]
@cscheid Yes please reach out! eli.holmes @ noaa.gov
