### ISSUE TITLE
virus in css lightable? - only in folder with qmd

### ISSUE THREAD

**Issue by norcalbiostat** [quarto-dev/quarto-cli#1827]
I know this isn't specifically with quarto directly, but with one of the css files that has come with a quarto document that i'm working on.  Deleting it is only temporary, as when i render the file it comes back. Is this a known thing? Box is spamming my email hourly about this file. 

![virus_screenshot](https://user-images.githubusercontent.com/10426521/184182010-3e663327-2304-4be2-b457-8540f644e857.PNG)

**Comment by cscheid** [comment]
It seems that lightable is a feature of https://cran.r-project.org/web/packages/kableExtra/kableExtra.pdf, so this is probably better reported there https://github.com/haozhu233/kableExtra

**Comment by cscheid** [comment]
It seems that lightable is a feature of https://github.com/haozhu233/kableExtra, so this bug is probably better reported there.

**Comment by norcalbiostat** [comment]
TY!
