### ISSUE TITLE
handle tbl-cap-location in cells

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#1829]
We complete `tbl-cap-location` in cells, so we should support their use.

**Comment by cderv** [comment]
@cscheid does this cover only setting `tbl-cap-location` inside code cells ? 

Or does it also cover the fact that `tbl-cap-location` does not work correctly with **knitr** tables even when set from main YAML header ? I am not sure what you have encountered and checking before opening a new issue.
