### ISSUE TITLE
Rendering Tip style callout in PDF

### ISSUE THREAD

**Issue by epabion** [quarto-dev/quarto-cli#183]
Use of callout's type `tip` is not possible in PDF.  The `\faLightbulbO` command which is used  in the `tcolorbox` defintion is a  fontawesome's package command but with the fontawesome5 package the `\faLightbulb[regular]` command must be used.

**Comment by dragonstyle** [comment]
Thank you for finding this - we did just move to the fontawesome5 package and missed it. Will get it fixed ASAP!

**Comment by dragonstyle** [comment]
Fixed here:

https://github.com/quarto-dev/quarto-cli/commit/e080a001fc524fbf0fc3fc6398f068dba42c9256

Ended up using the `\faLightbulb` icon as this seems more consistent with the other icon styles (which are solid).

**Comment by epabion** [comment]
That's awesome, thanks!
