### ISSUE TITLE
kableExtra styling not showing in revealjs

### ISSUE THREAD

**Issue by rjake** [quarto-dev/quarto-cli#1831]
### Bug description

`kableExtra::kable_styling()` doesn't seem to take effect when the format is `revealjs` although the tables look right when the format is `html`. It took us a long time to find `options("kableExtra.html.bsTable" = TRUE)` as a solution. Is it possible for quarto to enable this option automatically? Could the documentation include notes about formatting tables that display data and any caveats to be aware of? Currently, the docs have good examples on how to build tables in markdown-syntax but not much on formatting data frame outputs with `gt`, `kableExtra`, `reactable`, or others.

Also, apologies in advance if this is not the right place to post this. Our other guess was [`revealjs`](https://github.com/rstudio/revealjs)
````
---
title: "data frame printing"
format: revealjs
---

## Kable extra {.smaller .scrollable}
```{r}
options("kableExtra.html.bsTable" = TRUE)

mtcars |>
  knitr: :kable() |> 
  kableExtra: :kable_styling(bootstrap_options = c("striped", "hover"))
```
````

Using
```
RStudio 2022.07.1 Build 554
Windows 10 Build 19042
```

### `quarto check` Output

```bash
quarto check

[>] Checking Quarto installation......OK
      Version: 99.9.9
      Path: C:\Users\rileyj3\github\quarto-cli\package\dist\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.12
      Path: C:/Users/rileyj3/AppData/Local/Programs/Python/Python39/python.exe
      Jupyter: 4.11.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/Users/rileyj3/R/R-4.2.0
      LibPaths:
        - C://Users/rileyj3/R/win-library/4.2/library
      rmarkdown: 2.14
[>] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[>] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
While `options("kableExtra.html.bsTable" = TRUE)` may give you the output you are looking for, that as far as I can tell will end up loading a copy of bootstrap 3.3 CSS into the DOM. This has a very good chance of breaking other revealjs CSS so definitely not something we would enable by default.

We have it on our v1.2 work list to improve table formatting behavior (including many of the customizations currently available in kableExtra). It's desirable to bake this into Quarto core so that plain markdown and/or Jupyter documents can get the same behavior. I am going to target this bug for v1.2

**Comment by cscheid** [comment]
(rich, I'm assigning you just so we remember to close this when your table work is merged)

**Comment by cscheid** [comment]
I've verified this works on 1.3 prereleases now.
