### ISSUE TITLE
[FR] Quarto extension and Github subdirectory

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#1836]
I open the issue to keep track of this here instead/in addition to the discussion.
To note, the repository from the origin discussion no longer exists.

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1440

<div type='discussions-op-text'>

<sup>Originally posted by **mcanouil** July 17, 2022</sup>
Hi,

does Quarto extensions/formats have to be alone in a Github repository?
I wanted to store several formats in one repository (https://github.com/mcanouil/quarto-ext) and apparently this is not currently possible.

```bash
quarto install extension mcanouil/quarto-ext/coeos
# Quarto extensions may execute code when documents are rendered. If you do not 
# trust the authors of the extension, we recommend that you do not install or 
# use the extension.
#  ? Do you trust the authors of this extension (Y/n) › Yes
# ERROR: TypeError: Invalid URL
```

Did I miss something when we want a subdirectory?
</div>
</br>
<div type='discussions-op-text'>

<sup>Originally posted by **dragonstyle** July 17, 2022</sup>

Definitely- we should either support subdirectories or perhaps allow targeting / selection of specific extensions within the same repo. Seems useful!

</div>

**Comment by giabaio** [comment]
I think my question is also related to this. Is there a way to specify a branch from a specific GitHub repo? For instance, imagine I have a repo with 3 branches
- main
- another_branch
- a_third_branch

and each branch has slightly different versions of the extension I've written. Would I be able to use something like
```
quarto install extension giabaio/repo@another_branch
```
or (more specifically to my example)
```
quarto use template giabaio/repo@another_branch
```
? Or is it just the case that each branch should be included in a separate repo to be called by quarto (either as an extension or a template)?

Thanks
Gianluca

**Comment by jjallaire** [comment]
I believe that this should indeed work (at a minimum I know tags work that way, pretty branches do as well). @dragonstyle  ?

**Comment by giabaio** [comment]
Seems to fail for me, I get

```
 ? Do you trust the authors of this template (Y/n) › Yes
 ? Directory name: › als
ERROR: TypeError: Invalid URL

TypeError: Invalid URL
    at Object.opSync (deno:core/01_core.js:172:12)
    at opUrlParse (deno:ext/url/00_url.js:48:27)
    at new URL (deno:ext/url/00_url.js:322:20)
    at new Request (deno:ext/fetch/23_request.js:212:27)
    at deno:ext/fetch/26_fetch.js:429:29
    at new Promise (<anonymous>)
    at fetch (deno:ext/fetch/26_fetch.js:425:20)
    at downloadWithProgress (file:///home/gianluca/Dropbox/Rstuff/Packages/qmd/quarto-cli/src/core/download.ts:22:26)
    at stageTemplate (file:///home/gianluca/Dropbox/Rstuff/Packages/qmd/quarto-cli/src/command/use/commands/template.ts:134:11)
    at useTemplate (file:///home/gianluca/Dropbox/Rstuff/Packages/qmd/quarto-cli/src/command/use/commands/template.ts:66:29)
```
I have cloned quarto from the quarto-cli repo and installed it from there. Everything else seems to work fine (eg if I render a local qmd document, including the one I'm trying to use as a template) all works well...

Thanks!

**Comment by jjallaire** [comment]
@dragonstyle It looks like branches use slightly different URL syntax from tags:

```
https://github.com/quarto-dev/quarto-cli/archive/refs/tags/v1.1.70.zip
https://github.com/quarto-dev/quarto-cli/archive/refs/heads/feature/code-filename.zip
```

Could we update our download logic to try the branch form if the tag form fails?

**Comment by jjallaire** [comment]
@dragonstyle I'm targeting the support for branches to v1.1. If you think we should kick that to v1.2 that's fine. In any case we should ultimately re-target this for v1.2 for subdirectory support.

**Comment by jjallaire** [comment]
@cscheid For v1.1 we are just trying to see if we can get branches working as a fallback for tags (i.e. if the tag gives a 404 try the branch). I'm assigning to you just to rebalance the backlog a bit.

**Comment by mcanouil** [comment]
Amazing! 🎉

**Comment by jjallaire** [comment]
Going to re-open this to track sub-directory support.

**Comment by mcanouil** [comment]
> Going to re-open this to track sub-directory support.

Oh, I misread, I thought the subdirectory was also done at the same time as branches/tags. 🤷‍♂️
