### ISSUE TITLE
ojs engine not enabled in doc containing only inline OJS statements

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#1846]
because of `ojs_define`, It's possible to create valid OJS documents with inline `ojs` statements but without an `ojs` block. Currently, this doesn't work because we process inline `ojs` statements in a lua filter but enable OJS much earlier, in TypeScript.

**Comment by astrowonk** [comment]
Perhaps some key / boolean in the opening YAML could be a short-term workaround to just tell quarto to enable OJS?

**Comment by cscheid** [comment]
This currently exists, although it's not advertised:

    ---
    title: foo
    format: 
      html:
        ojs-engine: true
    ---
    
    ```{r}
    ojs_define(x = 3 * 5)
    ```
    
    The value of x is ${x}.

(I honestly had forgotten about it. We have it for debugging purposes.) 

With that said, we have a hack that will solve this bug, it should be coming up in the next couple of hours.
