### ISSUE TITLE
Netlify caches the CSS file incorrectly when asset optimizaion is enabled

### ISSUE THREAD

**Issue by yutannihilation** [quarto-dev/quarto-cli#1855]
### Bug description

I was trying to migrate my rbind site to Quarto. But, it seems the custom domain site uses wrong CSS.

* wrong: https://yutani.rbind.io/
![image](https://user-images.githubusercontent.com/1978793/184478561-13734d34-7467-4636-9f28-4b9c37ea52ec.png)

* expected: https://ephemeral-salmiakki-4715d0.netlify.app/
![image](https://user-images.githubusercontent.com/1978793/184478569-d8e6fe95-2bee-4b94-a4fc-c3a2d6f5bcf9.png)

It seems the difference comes from these lines:

``` html
<link data-mode='light' href='https://d33wubrfki0l68.cloudfront.net/css/30c383ef0355d535c8656e8fba516e261cd48ded/site_libs/bootstrap/bootstrap.min.css' id='quarto-bootstrap' rel='stylesheet'/>
```

``` html
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
```

Both uses the custom CSS that is generated from [my `custom.scss`](https://github.com/rbind/yutani/blob/master/custom.scss) but it seems the first one on the `*.cloudfront.net` URL is incomplete. I specified "Roboto Slab" as the base font, but it's not found there.

These two sites are published from the repository, so I have no idea why there are some differences. Are there any limitation of using the custom domain on Netlify?

### `quarto check` Output

```
$ quarto.cmd check

[>] Checking Quarto installation......OK
      Version: 1.1.63
      Path: C:\Users\Yutani\AppData\Local\Programs\Quarto\bin\
      CodePage: 932

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/Yutani/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK

```

### `quarto tools check` Output

```
$ quarto.cmd tools check
[>] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.08

```

### Checklist

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [x] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [x] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by yutannihilation** [comment]
Sorry, submitted mistakenly... I'm filling the form.

**Comment by yutannihilation** [comment]
Done.

**Comment by jjallaire** [comment]
I don't know where that cloudfront URL is coming from! Could it be that you have Netlify asset optimization enabled?

**Comment by yutannihilation** [comment]
Thanks for the prompt response! You are right. Yes, the asset optimization was enabled and it seems it matters. If I switch it off, I get the expected result.

My guess is that Quarto generates the same name of minified file, whereas Netlify uses the filename as part of the key of the cache somehow. I'm not sure who is in charge of fixing this... As my problem is solved at least, please feel free to close this issue. Thanks for your help.

**Comment by jjallaire** [comment]
Okay great! I am going to try to make a change to Quarto to proactively disable asset optimization for Netlify (as we've observed it to be incompatible w/ our output and also observed that it seems to have no real practical benefit given that nearly all our CSS is already minified). Will report back on what I find here.

**Comment by jjallaire** [comment]
Resolved with: https://github.com/quarto-dev/quarto-cli/commit/1150f62c7c69ce132929702e0c533c85f2574360

**Comment by yutannihilation** [comment]
Sounds good. Thanks for fixing!
