### ISSUE TITLE
Observable raises "SyntaxError: Unexpected character" for execution options

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#1856]
### Bug description

Consider the following minimal working example:

``````
---
title: "MWE"
---

Text ${foo} text

```{ojs}
#| echo: false

foo = "bar";
```
``````

it raises

```
OJS parsing failed on line 6, column 1
SyntaxError: Unexpected character '#'
----- OJS Source:
#| echo: false
^

foo = "bar";

-----
```

If I add `engine: knitr` to the YAML header the example works.

### `quarto check` Output

```
[✓] Checking Quarto installation......OK
      Version: 1.1.63
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### `quarto tools check` Output

```
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by rgaiacs** [comment]
I forgot that I should use

``````
```{ojs}
//| echo: false

foo = "bar";
```
``````

instead of

``````
```{ojs}
#| echo: false

foo = "bar";
```
``````

First, it would be great if this error is catch by Quarto and say something like "For Observable, you should use `//|` instead of `#|`.

Second, I would like to suggest that in v1.2 or later, we use the same "comment" for all languages and a filter handle the options before send it to the executor.

**Comment by jjallaire** [comment]
I agree that it's confusing that the comment varies across languages and we should definitely have a better error here (e.g. "Did you mean //| ?"

However, I don't want to use the same comment for all languages because that will force any editor or tool that interacts with the document programmatically to be "Quarto aware" and elide those "comments". e.g. a Jupyter notebook front end would need to know to NOT execute those lines b/c they will result in errors.

**Comment by jjallaire** [comment]
@cscheid I am going to target this for v1.2 (improve the error message for this case)

**Comment by cscheid** [comment]
This is going to be the new error message now:

```
ERROR: OJS parsing failed on line 8, column 1
SyntaxError: Unexpected character '#'

(Did you mean to use '//|' instead?)

----- OJS Source:
#| echo: false
^
foo = "bar";
-----
```
