### ISSUE TITLE
`quarto publish gh-pages` hangs if `gh-pages` branch is not the publishing source

### ISSUE THREAD

**Issue by fornaeffe** [quarto-dev/quarto-cli#1860]
### Bug description

On Windows 11

If I run (from Windows PowerShell in RStudio IDE 2022.07.1) `quarto publish gh-pages` when I have not set `gh-pages` as the publishing source of my GitHub repo, it hangs, waiting for a deployment that would never happen:

```bash
[>] Deploying gh-pages branch to website (this may take a few minutes)
```

While it is still hanging, if I go to my GitHub repo and set `gh-pages` as the publishing source, Quarto will resume as soon as GitHub deploys the site, saying:

```bash
[>] Published to ...
```

I suggest to remind the user to set `gh-pages` as the publishing source, for example if after some time Quarto doesn't detect a successful deployment, it should prompt the user to check if `gh-pages` is set as the publishing source.

### `quarto check` Output

```bash
[>] Checking Quarto installation......OK
      Version: 1.0.36
      Path: C:\Program Files\RStudio\bin\quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: C:/Users/Luca/AppData/Local/Microsoft/WindowsApps/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/Luca/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      rmarkdown: 2.13

[>] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[>] Inspecting tools

Tool         Status                    Installed     Latest
chromium     Not installed             ---           869685
tinytex      External Installation     ---           v2022.08
```

**Comment by jjallaire** [comment]
Thanks for reporting this! We've actually had some trouble w/ gh-pages publishing working on Windows at all (there seem to be some configurations where git worktrees don't work as expected on Windows). Anyway, in my experience the `gh-pages` branch is already set as the default on GitHub _expect for user sites_ (e.g. https://username.github.io). Were you publishing a user site or a normal site?

**Comment by fornaeffe** [comment]
Thank you for the reply!

No, I was publishing to a project, not user, site.
I used to enable GitHub Pages going to my GitHub repository page -> Settings -> Pages and, under "Deployment", changing "Branch" source from "none" to the branch I want as my source. But my repositories never had `gh-pages` branch until I explicitly create it, so if a user enables GitHub Pages from repository page before creating `gh-pages` branch, the only branch selectable as publishing source is `main` (or other branches created).

And there may be the case (mine, for example) of a project already published to Pages from branch `main` (or other), in which the user would like to start publishing through `quarto publish gh-pages` but forget to change publishing source...

**Comment by jjallaire** [comment]
Okay, strong points! I've revised the documentation to recommend this for all scenarios not just the user site: https://quarto.org/docs/publishing/github-pages.html#source-branch
