### ISSUE TITLE
Quarto -Tutorial Error on Code-Fold

### ISSUE THREAD

**Issue by annier01** [quarto-dev/quarto-cli#1861]
Hello! I am a new Quarto user and am trying to follow the tutorial. When I get to the code-fold option, I run into the following error: 
I'm not sure, what I'm doing wrong. I think I am following the example exactly. Thanks!

Validation of YAML front matter failed.
In file computations.qmd
(line 4, columns 3--7) Key html has empty value but it must instead be an object
3: format:
4:   html: 
          
5:   code-fold: true
In file computations.qmd
(line 5, columns 14--17) Key format has value true, which must be no possible value
4:   html: 
5:   code-fold: true
                ~~~
6: ---
Render failed due to invalid YAML.

**Comment by dragonstyle** [comment]
It is likely that you have an issue in the indention of the yaml in your document (for example, are the keys under HTML indented?). Can you share your source code?

**Comment by jjallaire** [comment]
Try this in your YAML:

```yaml
html:
   code-fold: true
```

The indentation of `code-fold` is required.

**Comment by annier01** [comment]
Yes! Thank you. I didn't know that indenting mattered. Thanks!
