### ISSUE TITLE
include output from pyviz visualization stack

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1867]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1859

<div type='discussions-op-text'>

<sup>Originally posted by **ea42gh** August 13, 2022</sup>

Anybody here know a quick workaround to get this to work? (I did submit an issue in quarto-python)

````
---
title: "Quarto Basics"
format:
  html:
    code-fold: true
jupyter: python3
---

```{python}
#| label: holoviews
#| fig-cap: "Holoviews plot"

import numpy as np
import holoviews as hv;
hv.extension('bokeh', logo=False);
 
r            = np.arange(0, 2, 0.01)
theta        = 4 * np.pi * r

hv.Curve((theta,r))
```
````

**Comment by jjallaire** [comment]
I was able to get this to work with exactly this source code. Published file here: https://jja.quarto.pub/quarto-basics/

Note that as part of investigating this I fixed an issue where a spurious warning was printed (one of the outputs from holoviews had no data at all which caused us to print a warning, we now ignore this warning but you might see it). That fix is here: https://github.com/quarto-dev/quarto-cli/commit/2a1c06302c178e59de6b9234604e211d069361c9

Note that holoviews has quite a bit of interactive functionality and that will not work with normal web output (for interactive cases you need to deploy it to the web with a Jupyter notebook behind it e.g. w/ Panel)

**Comment by ea42gh** [comment]
I used to get the figure together with extraneous empty captions.
For some reason this changed. I now get
```
Unable to display output for mime type(s): application/javascript, application/vnd.holoviews_Holoviews plot
Unable to display output for mime type(s): application/javascript, application/vnd.holoviews_Unable to display output for mime type(s): text/html
Unable to display output for mime type(s):
:Curve [x] (y)
```
for pdf, and similar messages for html and docx outputs

**Comment by jjallaire** [comment]
Holoviews will not work in PDF and DOCX (it uses JavaScript which aren't supported in those formats)

**Comment by ea42gh** [comment]
1) how about html? that at least should be possible?
2) how was https://jja.quarto.pub/quarto-basics/ generated?
3) I can no longer duplicate it, but got the figure in the output at least once,
together with some spurious empty caption and title text entries.

**Comment by jjallaire** [comment]
Yes HTML will work. I generated that with a simple `quarto render`
