### ISSUE TITLE
Export Annotated Slide Deck to PDF

### ISSUE THREAD

**Issue by paul-sheridan** [quarto-dev/quarto-cli#1868]
How can I export to PDF a slide deck that has been annotated with the chalkboard pen tool?

I followed the instructions to print to PDF using Chrome as described in the [Guide](https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf).

Here is a test annotation on the Quarto Demo Deck title slide:
<img width="1246" alt="screenshot-1" src="https://user-images.githubusercontent.com/11779314/184544535-8de8bab4-0099-4dab-8050-fbb2c5c0eebd.png">

Here what I get when attempting to print to PDF in Chrome:
<img width="998" alt="screenshot-2" src="https://user-images.githubusercontent.com/11779314/184544575-e8de2e90-6537-483e-ad75-71cf971dc369.png">

It would seem that the annotation is being handled properly, but not the slide contents themselves.

Any suggestions?

**Comment by jjallaire** [comment]
I don't believe this works with the current chalkboard and print to PDF functionality (they work on totally different representations of the slide deck)

**Comment by paul-sheridan** [comment]
Is there a suggested workflow for people, like me, who want to annotate their Quarto generated lecture slides and share the results?

**Comment by jjallaire** [comment]
Honestly, print them out, annotate them, then scan the annotated pages back into a PDF. Crude but effective until the PDF printing and chalkboard modules know how to play together.

**Comment by paul-sheridan** [comment]
I'm all for this "whatever works" kind of approach. But I'm missing something about how your suggestion would work for my use case. To be (more) specific, I want to
- Annotate slides using the brush tool while I'm going over them in class.
- Make the annotated version of the slides available to students thereafter.
Will your above suggestion work for this?

**Comment by jjallaire** [comment]
I can't imagine how my suggestion could work for that use case unless you were somehow training a camera on the printed slides as you go over them in class. I'm sorry this doesn't all work together -- we have integrated a 3rd party plugin (chalkboard) that doesn't happen to anticipate this use case. At this point I think we'd need to make direct changes to the plugin (or get them to make it work, looks like they don't intend to implement this but are open to a PR: https://github.com/rajgoel/reveal.js-plugins/issues/97).

So you could go the camera route but that seems quite involved! It is possible to save your annotations in a JSON file and then subsequently reload them: https://quarto.org/docs/presentations/revealjs/presenting.html#restoring-drawings. If you did this along with listing the `chalkboard.json` file as a `resource` then you could publish your slides to gh-pages, Quarto Pub, or Netlify:

```yaml
---
title: "chalkboard"
format: 
  revealjs:
    chalkboard:
      src: chalkboard.json
resources:
  - chalkboard.json
---
```

Then:

```bash
quarto publish quarto-pub slides.qmd
quarto publish netlify slides.qmd
```

See docs on publishing here: https://quarto.org/docs/publishing/

We should be automatically picking up the `chalkboard.json` as a resource but we aren't (I'll make a change to ensure that we are but in the meantime the `resources` technique shown above should work.

**Comment by jjallaire** [comment]
Okay, we are now automatically including the `chalkboard: src` JSON file as a resource when publishing, so no need for for the `resources` key, the following will suffice:

```yaml
---
title: "chalkboard"
format: 
  revealjs:
    chalkboard:
      src: chalkboard.json
---
```

Commit: https://github.com/quarto-dev/quarto-cli/commit/d68bdbcedbc68067c33a4160e9d68a39be492320

This will be available in tomorrow's version of our v1.1 pre-release: https://quarto.org/docs/download/prerelease.html

**Comment by paul-sheridan** [comment]
Awesome. After installing the v1.1.70 pre-release, I tried your above code (saved as slides.qmd) with a sample annotation (saved as chalkboard.json) in the same folder (as slides.qmd). But the annotations to are not reloaded.

Am I missing something here?

**Comment by jjallaire** [comment]
It's working on my end (albeit the chalkboard takes a second or two to load on each slide, that's probably by design to emulate drawing). If you could send a link to Git repo or Gist that fully reproduces what you are seeing and I can debug it from there.

**Comment by jjallaire** [comment]
One note: you do need to re-render the `.qmd` with the `chalkboard: src` entry in order for it to work.

**Comment by paul-sheridan** [comment]
So I made a rudimentary [GitHub repo](https://github.com/paul-sheridan/quarto-annotation-testing) with my `slides.qmd`, `chalkboard.json`, and supporting files.

Is this to what you're referring above by "a link to a Git repo"?

If not, can I ask you to elaborate a bit on what you require?

If so, then here is some extra information about the steps I'm taking that result in the annotations not re-rendering.

1. Render `slides.qmd`.
2. Open the generated `slides.html` file in Chrome.
3. Make a test annotation to the title slide of `slides.html` and download the resulting `chalkboard.json` file to the same folder as `slides.qmd`.
4. Re-render `slides.qmd`.
5. Open the regenerated `slides.html` in Chrome.
6. Observe there are no annotations to be seen.

**Comment by jjallaire** [comment]
Okay, I think I see the problem(s). There are two things that could be preventing you from seeing the annotations:

(1) The chalkboard.json file is loaded as a remote resources so opening slides.html in Chrome won't work. The slides need to be served from a web server (which they will be once you quarto publish them).

(2) Chalkboard annotations don't appear on the title slide until you navigate away from it and back (this is just a bug/vagary of the chalkboard plugin)

From your repo I did this:

```bash
git clone https://github.com/paul-sheridan/quarto-annotation-testing.git
cd quarto-annotation-testing
quarto preview slides.qmd
```

And saw this after navigating away from the title slide and back:

![Screen Shot 2022-08-15 at 5 01 57 PM](https://user-images.githubusercontent.com/104391/184717946-00b41e87-a185-47ca-8bce-d071c4301064.png)

**Comment by paul-sheridan** [comment]
Terrific! Thanks a lot. I'm sorted now. I lost sight of the slides needing to be served from a web server...

**Comment by davi-moreira** [comment]
Are there any updates on directly downloading the PDF file with the annotations, or is this still the only option?

**Comment by sylvaticus** [comment]
I think this issue should be reopen, as publishing the annotated HTML on a web site seems quite a distant workaround to get in-class annotations embedded/printed on a PDF.
At least to understand if this is a feature we may see in the feature or definitely not.

**Comment by mcanouil** [comment]
> I think this issue should be reopen, as publishing the annotated HTML on a web site seems quite a distant workaround to get in-class annotations embedded/printed on a PDF. At least to understand if this is a feature we may see in the feature or definitely not.

Feel free to open a feature request in the discussion board referencing this closed issue.

Closed/Completed issues (especially 4 years old) are not reopened. The initial report has been addressed as confirmed by the author.
