### ISSUE TITLE
Bootstrap CSS loading issue on mobile

### ISSUE THREAD

**Issue by atsyplenkov** [quarto-dev/quarto-cli#1873]
Hi all!

I have found the top drop-down menu very laggy on mobile. See example from my twitter post — https://twitter.com/i/status/1557599480140144640

There is a list of laggy websites:
https://ravi-seeks-alpha-with-quarto.netlify.app/
https://ddimmery.com/posts/quarto-website
https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/

However, this one is working fine — https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html

This issue occurs on both Firefox Mobile (v 103.0.2) and Firefox Desktop (v 103.0)

**Comment by jjallaire** [comment]
I don't know if there is a way to fix this (this is the default bootstrap toggle behavior so likely just a CSS transition that isn't working smoothly. We are planning on re-doing our mobile navigation soon (likely v1.2) so we'll take a closer look at this as part of that work.

**Comment by dragonstyle** [comment]
(Note: the common denominator that determines how smoothly the animation executes is plain versus banner style title blocks - title blocks exhibit the flashing much moreso than the default style).
