### ISSUE TITLE
ERROR: TypeError: lines1.some is not a function

### ISSUE THREAD

**Issue by MoritzLaurer** [quarto-dev/quarto-cli#1874]
I'm following the exact steps described here: https://quarto.org/docs/get-started/computations/jupyter.html
but sometimes I get the error message: `"ERROR: TypeError: lines1.some is not a function"`
when I run `quarto preview computations.ipynb`
I sometimes got the same error with the other tutorials on the website, but don't always get it - I'm not quite sure when it happens and why.  

Environment information: 
- Python 3.9.7
- MacOS 12.4, quarto-1.0.38-macos.pkg
- jupyter notebook via PyCharm Professional

**Comment by cscheid** [comment]
Some investigation points to a potential culprit here:

```bash
$ rg 'lines(1)?.some'
src/core/jupyter/jupyter.ts
1379:          if (lines.some(hasAnsiEscapeCodes)) {
```

`lines1` instead of `lines` because I bet the bundling process renamed aliased variables.

**Comment by MoritzLaurer** [comment]
great, thanks for the quick fix
