### ISSUE TITLE
HTML Options pages without examples 

### ISSUE THREAD

**Issue by ethantenison** [quarto-dev/quarto-cli#1875]
The default font for revealjs presentations is too big. The [documentation ](https://quarto.org/docs/reference/formats/presentations/revealjs.html) says you can add 'smaller' to the yaml header to decrease the font size on all the slides, but it doesn't say what's suppose to come after it. Setting fontsize in the yaml header doesn't do anything either. 

For example

logo: logo.png
or
footer: 'Company tag line here'

but what about smaller? 

smaller: ????

**Comment by jjallaire** [comment]
It's a boolean, so:

```yaml
format: 
  revealjs: 
    smaller: true
```
You are right though that we never say its a boolean in the reference! I've made change in our docs database here (it won't be propagated to the website for a couple of days though): https://github.com/quarto-dev/quarto-cli/commit/9de3c32fd01139c660193263c1e58cc767e4c850

Note that our user guide does currently document this: https://quarto.org/docs/presentations/revealjs/#content-overflow
