### ISSUE TITLE
plots break when i email Quarto html files

### ISSUE THREAD

**Issue by mzobeck** [quarto-dev/quarto-cli#1877]
I often find myself emailing Rmarkdown reports rendered in HTML to collaborators. I recently tried this with an HTML file rendered from a Quarto document. It renders correctly but after I email the document all the plots do not display and instead are replaced by an icon of a broken image. 

This has happened with Quarto documents in a regular R project and a Quarto project. I have tried it on Windows and Mac. I have tried emailing through my work email (Microsoft Outlook) and personal Gmail. 

Minimal reproducible example below:

`---
title: "test"
format: html
---

```{r}

x <- rlnorm(1000, 3, 0.3)
hist(x)
```
`

Rendered document before email:
![image](https://user-images.githubusercontent.com/62612480/183949147-f19fe600-c2d1-4a46-9764-26c30ea029de.png)

Rendered document after email:
![image](https://user-images.githubusercontent.com/62612480/183949311-263462ed-0786-4ecc-b48e-36da69fa495d.png)

R session info: 
`R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0    knitr_1.37     xfun_0.29 `

**Comment by jjallaire** [comment]
Need to use `self-contained: true` to embed images

**Comment by mzobeck** [comment]
Yes, that worked. Thanks!
