### ISSUE TITLE
`penguins` example for OJS uses a modified version of the palmer-penguins.csv

### ISSUE THREAD

**Issue by jthomasmock** [quarto-dev/quarto-cli#1878]
The penguins example in the [OJS](https://quarto.org/docs/interactive/ojs/) and [standalone example](https://quarto.org/docs/interactive/ojs/examples/penguins.html) uses a version of the `palmerpenguins` dataset that varies from the R package itself, namely, removing the units from the col names.

```
names(palmerpenguins::penguins)
[1] "species"           "island"            "bill_length_mm"    "bill_depth_mm"    
[5] "flipper_length_mm" "body_mass_g"       "sex"               "year"     
```

```
names("palmer-penguins.csv")
[1] "species"        "island"         "bill_length"    "bill_depth"     "flipper_length"
[6] "body_mass"      "sex" 
```

This makes sense for the example but is a bit surprising if someone were to try:

```
ojs_define(data = palmerpenguins::penguins)
```

As the colnames mismatch will silently fail at the OJS level - the plots will not be returned and the only errors are seen in the console of the browser itself at JavaScript level. I would suggest either being very clear and providing a direct URL to the used .csv (rather than having to go find it on GitHub) and/or clarifying the changed col names.

Tag @cscheid from our discussion.

**Comment by cscheid** [comment]
@jjallaire I think this is a `quarto-web` issue actually. We just need to update that example to use the correct CSV
