### ISSUE TITLE
Code and output do not match in the final example in https://quarto.org/docs/presentations/revealjs/#line-highlighting

### ISSUE THREAD

**Issue by RaymondBalise** [quarto-dev/quarto-cli#1881]
There is a problem on:  [quarto-web / docs / presentations / revealjs / index.qmd
](https://quarto.org/docs/presentations/revealjs/#line-highlighting)

The code block below:

>You can use this same option within an executable code cell by using the code-line-numbers cell options:

shows/says `#echo: fenced`.  So when the code is rendered the lines with the hash pipes  are shown/counted:

```{.python}
#| echo: fenced
#| code-line-numbers: "|6|9"

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

That is not what is shown in the imbedded content below the code block.  That code (I think) comes from here:

<https://github.com/quarto-dev/quarto-web/blob/main/docs/presentations/revealjs/examples/line-highlighting-4.qmd>

*line-highlighting-4.qmd* has `#| echo: true` instead of `#|echo:fenced`.   So the line numbers do not match.  Instead of showing what is on the web page (https://quarto.org/docs/presentations/revealjs/):

![image](https://user-images.githubusercontent.com/18148282/183258851-382c2a0b-6e20-46cd-a43e-dff6fbd6ae89.png)

... the code running `echo:fenced` highlights a blank line.

<img width="1839" alt="image" src="https://user-images.githubusercontent.com/18148282/183258863-8d9c2d30-5999-447e-8a6a-16d902817a5d.png">

I am thinking both code chunks should use `echo:true` and `echo:fenced` should be explained later.

Also it is very confusing to show code that does not execute in a paragraph about executable code.    Notice the code block shows `.python` instead of `python`.  So.... I think the shown code should be:

````
```{python}
#| echo: echo
````

**Comment by cderv** [comment]
I believe this was fixed in https://github.com/quarto-dev/quarto-web/commit/54037479e72a44319ba0ab45e4f9c3559f995d7f and https://github.com/quarto-dev/quarto-web/commit/a00d5708ade12bf0c18fe0a2adcdf3b14797dd34 

thanks for the report in the first place
