### ISSUE TITLE
quarto publish gh-pages doesn't respect site-url for RSS feeds

### ISSUE THREAD

**Issue by kjelljorner** [quarto-dev/quarto-cli#1885]
### Bug description

quarto publish gh-pages doesn't respect `site-url` for RSS feeds. This seems to contradict the [documentation](https://quarto.org/docs/websites/website-listings.html#feeds) which says that "Generating feeds requires that the site-url be set for the site in your _quarto.yml file."

It automatically seems to set the feed url as the url of the GitHub pages, even if it is specified in `_quarto.yml`. This breaks cases where the GitHub Pages uses a [custom domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages).

As a workaround, I currently run quarto publish without rendering which seems to work.

```console
quarto render
quarto publish gh-pages --no-render 
```

```console
(blog) kjelljorner@mba-m1-kjell-jorner blog % sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```

### `quarto check` Output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: /opt/homebrew/Caskroom/mambaforge/base/envs/blog/bin/python
      Jupyter: 4.11.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

(/) Checking R installation...........During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /opt/homebrew/Cellar/r/4.2.1/lib/R
      LibPaths:
        - /opt/homebrew/lib/R/4.2/site-library
        - /opt/homebrew/Cellar/r/4.2.1/lib/R/library
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
We do attempt to read the domain first from the `CNAME` file -- do you have one of these at the root of your repo pointing to your custom domain?

Whatever the case, I think we need to respect any `site-url` contained within `_quarto.yml` over what we automatically deduce. We should have that fixed soon!

**Comment by kjelljorner** [comment]
It seems like GitHub Pages automatically creates such a file: https://github.com/kjelljorner/blog/blob/gh-pages/CNAME. Not sure what happened when I attempted this first. But I am sure that I manually checked the rss xml in the source and it was wrong. Would probably need to run this again, but I don't want to experiment with my site at the moment.

**Comment by jjallaire** [comment]
Okay, this is fixed here: https://github.com/quarto-dev/quarto-cli/commit/471a1b34963b77c8287f3807c3325a09ba789775
