### ISSUE TITLE
Red/green laser pointer for revealjs

### ISSUE THREAD

**Issue by lbenet** [quarto-dev/quarto-cli#1886]
Thanks a lot for the truly great work!! I recently (JuliaCon 2022) heard about Quarto, and I'm migrating to use it for presentations (for the time being).

I'd like to suggest (to have the possibility) to change the cursor in a revealjs presentation, from the usual one (e.g., a black arrow) to something looking like a red/green laser pointer. It would be something similar like changing the cursor (in the canvas notes mode) but for a fixed-color shiny laser dot.

**Comment by jjallaire** [comment]
There is a Revaljs plugin for this (https://github.com/burnpiro/reveal-pointer). It is possible to use Revealjs but you need to bundle them as described here: https://quarto.org/docs/presentations/revealjs/advanced.html#reveal-plugins

In v1.2 we plan on making it possible to bundle Reveal plugins as Quarto Extensions. @dragonstyle I'm going to keep this open as a reminder to use the Pointer plugin as an example when we implement this feature.

**Comment by lbenet** [comment]
Thanks for the answer and the suggestion!

**Comment by dragonstyle** [comment]
There is now an extension that address support for this, which you can try here:

https://github.com/quarto-ext/pointer

This requires a pre-release build of Quarto that is 1.2.124 or later. You can download pre-release builds here:

<https://quarto.org/docs/download/prerelease.html>
