### ISSUE TITLE
non-root installation of quarto on linux systems

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1890]
We should make it very clear on the installation page how to install if you are non root. This might be invoking the .deb in a fashion that installs into a user context (not sure if that is even possible) or alternatively documenting how to do download and extract the tarball and arrange for quarto to be on the path.

**Comment by jjallaire** [comment]
This is just docs and related to downloads so we can work on this next week when we are overhauling the download experience.

**Comment by dragonstyle** [comment]
I've added an intermediary download page for the tarball case which provides instructions for users.
