### ISSUE TITLE
Suggestion: List Quarto on Jamstack

### ISSUE THREAD

**Issue by a2k42** [quarto-dev/quarto-cli#1891]
[Jamstack.org](https://jamstack.org/generators/) maintain a list of static site generators, could Quarto be added to the list?

**Comment by jjallaire** [comment]
Good idea! Any chance you'd give them a PR for this?

**Comment by Andy2K11** [comment]
Gone ahead with that, shout if you see any problems. Will close this issue once it's merged.

[Preview](https://deploy-preview-802--jamstack-site.netlify.app/generators/quarto/)

[PR](https://github.com/jamstack/jamstack.org/pull/802#issuecomment-1215586668)

**Comment by jjallaire** [comment]
Looks great! Thanks :-)

**Comment by a2k42** [comment]
There are outstanding PRs on the Jamstack repo dating back a year... it looks like the list is not currently being kept up to date sadly.

**Comment by a2k42** [comment]
[Quarto is now listed on Jamstack](https://jamstack.org/generators/quarto/)
