### ISSUE TITLE
Another example for the Quarto gallery (title pages for pdfs)

### ISSUE THREAD

**Issue by eeholmes** [quarto-dev/quarto-cli#1894]
If you are interested, for this section of the gallery: https://quarto.org/docs/gallery/#books

I created pandoc templates (for `template-partials: `) and instructions for including custom title page designs for PDF output. Doesn't use any special LaTeX packages or anything so should be quite robust to different engines and document classes. This is useful for anyone who creates books with Quarto and needs the PDF to have a highly customized title page.

https://nmfs-opensci.github.io/quarto_titlepages/

example title page
![image](https://user-images.githubusercontent.com/2545978/184680824-8e14145c-ecb3-40f5-b653-808745a53256.png)

**Comment by jjallaire** [comment]
Yes that would be great! Do you have a link to a deployed/published PDF that uses the titlepages?

**Comment by eeholmes** [comment]
I add a link to the PDF to the webpage. You can double-click on any title page image to view a PDF of an article with the title page. It's a demo article.
https://nmfs-opensci.github.io/quarto_titlepages/

Here's a direct link to one of them: https://nmfs-opensci.github.io/quarto_titlepages/titlepages/bg-image/article.pdf 

I also added examples with different document classes (scrbook, scrartcl, svmono, krantz, elsarticle) with the vline template. You'll see those links on the main page.

Next up I am working on a template for a NOAA Fisheries Technical Memo, but it'll be awhile before one of those goes live. 

But figuring out how to do this in a way that even a casual LaTeX programmer will find intuitive and easy to modify was quite hard. As is typical, once I figured out exactly how to do it, the solution seems dead easy.  It's is so great to be able to pass in `template-partials: `. Totally changes title page and frontmatter customization needed for big reports.

**Comment by jjallaire** [comment]
Your PDF is now featured in the gallery: https://github.com/quarto-dev/quarto-web/commit/e604e69d26b749be43d9344cf7fd0f43b2f3a6c0

Thanks!

@dragonstyle Should we add some docs to the PDF page describing the use of template-partials outside of custom formats?
