### ISSUE TITLE
Documentation on installing tinytex is incorrect

### ISSUE THREAD

**Issue by halidaee** [quarto-dev/quarto-cli#1900]
Provided terminal command at https://quarto.org/docs/output-formats/pdf-engine.html is 
`quarto install tools tinytex`
while correct command is
`quarto tools install tinytex`.

**Comment by jjallaire** [comment]
The syntax on the website is actually:

```bash
quarto install tool tinytex
```

And this is in fact the correct syntax (the other syntax works but is now depracated)
