### ISSUE TITLE
enumeration in html vs revealjs

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1902]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1897

<div type='discussions-op-text'>

<sup>Originally posted by **hardin47** August 15, 2022</sup>
it seems that when i change the format from `html` to `revealjs`, the enumeration changes.  in fact, with `revealjs`, I can't figure out the correct markdown to get the second layer of enumeration to be letters instead of numbers.  is there a magic indent that I'm missing?  can anyone help me get letters in the `revealjs` enumeration?

```
---
title: "clicker"
format:
  revealjs:
    footnotes-hover: true
---
<!-- the two formats are html and revealjs -->

# Clicker Q

to go with **Probability & Statistics** by DeGroot and Schervish.  Math 152 - Statistical Theory.

---

1. The Central Limit Theorem (CLT) says:[^1]
   a. The sample average (statistic) converges to the true   average (parameter)
   b. The sample average (statistic) converges to some pont
   c. The distribution of the sample average (statistic)    converges to a normal distribution
   d. The distribution of the sample average (statistic)    converges to some distribution
   e. I have no idea what the CLT says
   

[^1]:  c. The distribution of the sample average (statistic) converges to a normal distribution

---

2. Which cab company was involved?[^2]
...

```

`revealjs` rendering:

![image](https://user-images.githubusercontent.com/7210585/184690713-d295a09c-7ae5-4db7-8581-0e2420407274.png)

`html` rendering:

![image](https://user-images.githubusercontent.com/7210585/184690842-25d4d3d1-5fcb-4dfa-8e9b-511f429a47d9.png)

</div>

**Comment by jjallaire** [comment]
Consider making this the default:

```css
.reveal ol ol {
   list-style-type: lower-alpha;
}
```

**Comment by mcanouil** [comment]
If possible and in my opinion, it would be better to have the "type" attribute properly used and not ignored in my opinion as it is the case for HTML.

For example, I do not want:

```
a. Text
   1. Text
   2. Text
b. Text
```

To be rendered as:

```
1. Text
   a. Text
   b. Text
2. Text
```

That being said, maybe it's a Reveal JS issue.
If that is the case, I would rather have a note in the documentation about ordered list in Reveal JS and showing the `.reveal ol ... ol` workaround to get the desired nested item than having a new default which actually does not bring awareness of this behaviour in Reveal JS.

**Comment by cscheid** [comment]
@jjallaire I just learned that Pandoc knows how to track the types of ordered lists:

```$ cat ol-test-1.md
1. test1
2. test2
3. test3

a. test1
b. test2
c. test3
```

```$ pandoc ol-test-1.md --to native
[OrderedList (1,Decimal,Period)
 [[Plain [Str "test1"]]
 ,[Plain [Str "test2"]]
 ,[Plain [Str "test3"]]]
,OrderedList (1,LowerAlpha,Period)
 [[Plain [Str "test1"]]
 ,[Plain [Str "test2"]]
 ,[Plain [Str "test3"]]]]
```

Do we want to go the Pandoc route of respecting whatever the style that the user chose to use, or do we want to go the LaTeX/HTML style of leaving the decision to the stylesheets?

**Comment by jjallaire** [comment]
I think pandoc ends up writing that info into `type` attributes on the list items which we can then target w/ CSS (in fact the pandoc default HTML stylesheet might already do that?)

**Comment by cscheid** [comment]
Ah, good point. I'll check and if so, make the revealjs stylesheet do the same.

**Comment by cscheid** [comment]
There's a funny situation happening here when it comes to the difference between `type="a"` and `type="A"`. It turns out that case-sensitive attribute selectors are a tricky, recent bit of CSS. Although https://caniuse.com/css-case-insensitive claims that the support is broad, this doesn't work on my version of Chrome (104.0.5112.79), or of Safari!

```
<html>
  <head>
    <style>
      ol[type="a" s] {
        list-style-type: decimal;
      }
    </style>
  </head>
  <body>
    <ol type="a">
      <li>item a</li>
      <li>item b</li>
    </ol>
    <ol type="A">
      <li>item A</li>
      <li>item B</li>
    </ol>
  </body>
</html>
```

It _does_ work on Firefox for me, though.

This means that the only way to support different outputs for lower and upper-case versions of `ol` elements is for there to be _no_ CSS applied to them, so that the browser takes over with its (case-sensitive) defaults. Unfortunately, revealjs sets up defaults in its CSS, which means that we need to override them with CSS, which means that we only get broadly-supported case-insensitive results.

The upshot of all of this is that the workaround for reveal will require deciding whether we prefer lower-case or upper-case `ol` elements, so we let CSS ordering decide.

I'm making this change by preferring the lower-case values, but flagging it here in case it comes up in the future.

**Comment by cscheid** [comment]
Here's an full example that works in Firefox but can't quite work in Safari and Chrome:

````
---
format: revealjs
---

## Slide 1

1. a.  item 1-a
   b.  item 1-b
2. 1.  item 2-1
   2.  item 2-2
3. i.  item 2-i
   ii. item 2-ii
4. A.  item 2-A
   B.  item 2-B
5. I.  item 5-I
   II. item 5-II

## Slide 2

a. a.  item a-a
   b.  item a-b
b. 1.  item b-1
   2.  item b-2
c. i.  item c-i
   ii. item c-ii
d. A.  item d-A
   B.  item d-B
e. I.  item e-I
   II. item e-II

## Slide 3

i.   a.  item i-a
     b.  item i-b
ii.  1.  item ii-1
     2.  item ii-2
iii. i.  item iii-i
     ii. item iii-ii
iv.  A.  item iv-A
     B.  item iv-B
v.   I.  item v-I
     II. item v-II

## Slide 4

A.  a.  item A-a
    b.  item A-b
B.  1.  item B-1
    2.  item B-2
C.  i.  item C-i
    ii. item C-ii
D.  A.  item D-A
    B.  item D-B
E.  I.  item E-I
    II. item E-II


## Slide 5

I.   a.  item I-a
     b.  item I-b
II.  1.  item II-1
     2.  item II-2
III. i.  item III-i
     ii. item III-ii
IV.  A.  item IV-A
     B.  item IV-B
V.   I.  item V-I
     II. item V-II
````
