### ISSUE TITLE
Unexpected Include Behavior

### ISSUE THREAD

**Issue by SHogenboom** [quarto-dev/quarto-cli#1903]
I'm trying to use [include](https://quarto.org/docs/authoring/includes.html) to allow re-use of custom created functions across multiple bookchapters. When doing so I encountered multiple unexpected behaviors which I will describe below. Please note: I realize an easy solution to the problem is to include an codeblock where the file is sourced. Neverthless I wasn't sure whether the behaviors were known, expected, and/or desired.

1. The included file must be stored in the same directory as the to-be-rendered file.
I'm working on a book where I have the toplevel files (e.g., `_quarto.yml`; `_functions.R`). I then have each bookchapter stored in a folder called `chapters`. When I want to include (`_functions.R`) in a bookchapter (e.g., `chapters/intro.qmd`) an error occurs when redering: `ERROR: Include directive failed.` If I place the `_functions.R` file also in the `chapters` folder this issue no longer occurs.

2. Including an `.R` file shows the script as regular text instead of executing code
Upon re-reading the documentation this is expected behavior as only `.qmd` and `.md` files are mentioned as suited. However, I somehow expected that you could also include normal .R code - which perhaps others might expect as well.

**Comment by jjallaire** [comment]
Yes, file references need to remain relative to the base file that is doing the including (otherwise all sorts of problems ensue). One way to work around this is to do root level includes (e.g. `/chapters/_functions.R` which will work universally no matter where they are included from.

For including R code you can use the `file` option of a Knitr code cell:

````
```{r}
#| file: code.R
```
````

**Comment by SHogenboom** [comment]
Couldn't get the suggested solutions to work - due to scoping issues.

For my personal use case this is the solution:
```
{{< include ../_functions.qmd >}}
```

The `../` ensures a 'start' at the project level, from where the scoping again makes sense even if the files themselves are nested in subfolders.
