### ISSUE TITLE
building from scratch or using pypi to allow user installs

### ISSUE THREAD

**Issue by RHmilti** [quarto-dev/quarto-cli#1908]
id like to try this but would like pypi pkg to install as a regular user in a linux env where i dont have privileges.

any plans?

**Comment by jjallaire** [comment]
There is a tar.gz version of the installer which you can unarchive and put in whatever directory you want (the `bin` subdir needs to be on the PATH): https://github.com/quarto-dev/quarto-cli/releases/tag/v1.0.38

We plan on making this scenario much more clear on the download page soon!

**Comment by jjallaire** [comment]
Closing as duplicate of https://github.com/quarto-dev/quarto-cli/issues/1890
