### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by statzhero** [quarto-dev/quarto-cli#1919]
Not an issue per se; I'm wondering why the https://quarto.org/docs/publishing/github-pages.html site emphasizes `gh-pages` as the source branch. I understand nowadays you can publish from `main` the same way.

**Comment by jjallaire** [comment]
To publish from the `main` branch doesn't require any special tooling (just set `output-dir` to `docs`) and push as normal. The problem with this is that many users don't like to check their generated site output into version control (as this creates very messy/noisy diffs). Thus the `gh-pages` branch and related tooling.

That said, I do think that we should at least mention the other option (using the `docs` dir on `main`) for those that don't care about checking their source into version control. I'll make that change son.

**Comment by statzhero** [comment]
Sorry just to clarify: when you say ‘docs’ you mean ‘_site’?

**Comment by jjallaire** [comment]
No I mean `docs`. GitHub Pages can either deploy from the root directory or from a `docs` directory (there is no support for custom output directories). Therefore to make it work w/ Quarto you need to change the `output-dir` to `docs`

**Comment by statzhero** [comment]
Got it, thanks.

**Comment by jjallaire** [comment]
We've added a section to the GH Pages docs emphasizing this method: https://quarto.org/docs/publishing/github-pages.html#render-to-docs
