### ISSUE TITLE
Release archive does not start with a directory

### ISSUE THREAD

**Issue by stefanv** [quarto-dev/quarto-cli#192]
```
$ tar xf ../quarto-0.2.291-linux-amd64.tar 
$ ls
bin  COPYING.md  COPYRIGHT  share
```

It is good practice for an archive to start with a folder, otherwise people may run into errors like this one:

```
$ tar xf quarto-0.2.291-linux-amd64.tar
tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwxr-xr-t: Operation not permitted
```

And, if they do it in their home directory, they may pollute that directory instead of having the files extracted into a subfolder.

**Comment by jjallaire** [comment]
Thanks, definitely should be creating a folder! @dragonstyle Let's change this to create a folder that includes the version number (e.g. `quarto-0.2.291`) to account for side-by-size unarchives of different versions.

**Comment by dragonstyle** [comment]
Thanks for reporting this! Should be all set as of `quarto-0.2.294`

**Comment by stefanv** [comment]
Thank you!
