### ISSUE TITLE
update to deno 1.25.0

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1920]
With big changes to Deno coming including node compatiblity and a new http server I'd like us to not fall too far behind. We have attempted to update to Deno 1.24.1 here: https://github.com/quarto-dev/quarto-cli/tree/feature/deno-1.24.1

All of this works great except that we see crashes on M1 macs! This happens during render so possibly related to deno_dom (which we also updated to v0.1.23). Note that disabling deno_dom FFI didn't resolve the crash so possibly also related to WASM.

Anyway, we should once again try updating to 1.24.3. As our build has gotten more complicated (including updating the std library in two places and vendoring) it is less straightforward to do this update. As part of this work we should also create some documentation and perhaps additional documentation.

**Comment by cscheid** [comment]
We should shoot for 1.25.0 now, tracking here: https://github.com/quarto-dev/quarto-cli/tree/feature/deno-1.25.0

**Comment by cscheid** [comment]
We're now on 1.25.1
