### ISSUE TITLE
Add documentation for `bash` chunks

### ISSUE THREAD

**Issue by jeanetteclark** [quarto-dev/quarto-cli#1932]
Apologies if this currently exists, but I've been trying to figure out whether you can execute `bash` chunks in quarto. It doesn't seem to be in the documentation anywhere, though I do see on the [about page](https://quarto.org/about.html#pull-requests) of the quarto project, a bash chunk (though I'm not sure if it actually runs or not).

If this feature is documented somewhere, could someone kindly point me that way? If it is not, could the documentation be added? In general, the only thing I've missed in my transition from bookdown to quarto for authoring books is bash chunks.

Thank you!

**Comment by jjallaire** [comment]
Thanks for pointing this out, will indeed enhance the docs on using bash from Quarto.

In the meantime, you can use `bash` in Quarto just the same way as you do in R Markdown (as they are both based on Knitr which implements a `bash` engine. In Jupyter you would need to use shell magics: https://ipython.readthedocs.io/en/stable/interactive/magics.html

**Comment by cwickham** [comment]
Closing as appears to be covered in https://quarto.org/docs/computations/execution-options.html#shell-commands
