### ISSUE TITLE
Render fails with chunk option including space after a colon

### ISSUE THREAD

**Issue by dmkaplan2000** [quarto-dev/quarto-cli#1947]
### Bug description

The following document fails to render:

````
---
title: "Untitled"
format: html
---

```{r}
#| label: fig-sa-tmap
#| fig-cap: !expr paste("The caption is: ","a caption")
plot(1:10)
```
````

The error message is: 

```
ERROR: YAMLException: bad indentation of a mapping entry (test.qmd, 9:40)
 8: #| label: fig-sa-tmap
 9: #| fig-cap: !expr paste("The caption is: ","a caption")
                                           ~
10: plot(1:10)
```

The document will render if one removes the space after the `:` in `fig-cap`:

````
---
title: "Untitled"
format: html
---

```{r}
#| label: fig-sa-tmap
#| fig-cap: !expr paste("The caption is:","a caption")
plot(1:10)
```
````

### `quarto check` Output

[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: 4.11.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /home/dmk/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

### `quarto tools check` Output

[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
This isn't a bug, it's unfortunately a yaml annoyance. if you have !expr, the next item must be a yaml string, which must be formatted appropriately. That combination of colons and quotes requires escaping. Try something like this instead.

````
---
title: "Untitled"
format: html
---

```{r}
#| label: fig-sa-tmap
#| fig-cap: !expr "paste(\"The caption is: \",\"a caption\")"
plot(1:10)
```
````

**Comment by dmkaplan2000** [comment]
Horrifying...

OK, I guess I will have to live with it, but one would naively expect that `!expr` would turn off looking for further YAML entries.

**Comment by cscheid** [comment]
That's not up to us, that's up to the YAML spec unfortunately.

**Comment by cscheid** [comment]
@dmkaplan2000 We now detect this error message and provide additional guidance. The current error message now reads as follows:

```
ERROR: YAMLException: bad indentation of a mapping entry (expr-test.qmd, 7:32)
6: #| label: fig-1
7: #| fig-cap: !expr paste0("Hello: ", " world.")
                                  ~
8: plot(c(1,2,3))
ℹ YAML tags like !expr must be followed by YAML strings.
ℹ Is it possible you need to quote the value you passed to !expr ?
```

**Comment by dmkaplan2000** [comment]
This is definite progress. Thanks!
