### ISSUE TITLE
`quarto run` doesn't respect stdout/stderr

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#1954]
Instead, it sends [all output through `info()`](https://github.com/quarto-dev/quarto-cli/blob/main/src/core/process.ts#L167-L173), which uses stderr.

Minimal repro:

```
$ cat test-filter.ts
const stdin = new TextDecoder().decode(await Deno.readAll(Deno.stdin));
await Deno.stdout.write(new TextEncoder().encode(stdin));

$ (echo Foo | quarto run test-filter.ts) >/dev/null
Foo

$ (echo Foo | quarto run test-filter.ts) 2>/dev/null

$
```

**Comment by allenmanning** [comment]
@cscheid should this go in 1.1?

**Comment by jjallaire** [comment]
We need to discuss whether it goes in v1.1 b/c its a very low-level change that will affect tons of codepaths (I'd probably vote no but can be convinced otherwise if its logically proven to only _really_ affect quarto run

**Comment by jjallaire** [comment]
I made a change to scope this fix down to `quarto run *.ts` so I think very safe to merge v1.1 (went ahead and did that)

**Comment by joelostblom** [comment]
It seems like this is still an issue on 1.6.4. I need to do something like this to capture output from quarto (and I believe I would not be able to distinguish errors from actual output of the command):

```
quarto_output=$(quarto run test-filter.ts 2>&1)
```

Could this be reopened? Or is there a better way than what I'm trying to capture output on the command line?

**Comment by cscheid** [comment]
I think you're running into something else, because I can't repro your claim:

````
$ cat test-filter.ts
const stdin = new TextDecoder().decode(await Deno.readAll(Deno.stdin));
await Deno.stdout.write(new TextEncoder().encode(stdin));
$ (echo Foo | quarto run test-filter.ts) >/dev/null
$ (echo Foo | quarto run test-filter.ts) 2>/dev/null
Foo
````

Note how redirecting stdout (`>/dev/null`) in the first run causes the output to be omitted, but redirecting stderr (`2>/dev/null`) makes the output go through. So in this case, the output is going to stdout.

**Comment by joelostblom** [comment]
You're right, I see the same as you with `.ts` scripts, only with `.R` scripts I see the erroneous behavior(sloppy testing on my part initially, sorry about that).

To reproduce the issue, create a script with the following code:

```R
# test-r.R
cat('write stdout', file = stdout())  # The default
cat('write stderr', file = stderr())
```

And then run:

```bash
(echo Foo | quarto run test-r.R) >/dev/null
(echo Foo | quarto run test-r.R) 2>/dev/null
```

You will see that both the calls to `cat` outputs when `stdout` is redirected and none when `stderr` is redirected. If I use `Rscript` in place of `quarto run`, I get the expected output as in this screenshot:

![image](https://github.com/user-attachments/assets/16c605f0-3f8f-48a5-976d-f7376d08820c)

**Comment by cscheid** [comment]
Can you open a new issue? Thanks.
