### ISSUE TITLE
Feature request: Bookdown-style text references

### ISSUE THREAD

**Issue by dmkaplan2000** [quarto-dev/quarto-cli#1959]
Hi,

There was a [discussion](https://github.com/quarto-dev/quarto-cli/discussions/1785) about this issue, but I figured I would file a formal feature request. [Bookdown](https://bookdown.org/) allows you to use [text references](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references) to create figure and table captions:

````
---
title: Text references
output: bookdown::html_document2
---

(ref:cap) This is a long complex caption with an equation ($E=mc^2$), some calculated results (`r 5^2`), **bold text** and text in "quotes".

```{r fig.cap="(ref:cap)"}
plot(1:10)
```
````

This is a super handy feature when captions are complicated and long. To my knowledge this feature, or something equivalent to it, does not exist in Quarto. Though the same result can undoubtedly be achieved using `!expr` and `paste` statements with lots of back quoting, it is far less ergonomic.

Would it be possible to implement something like that in Quarto? Basically, you need a way to pass text by reference a bit like one can insert figures and links by reference id. This seems like a feature that could potentially be more generally valuable beyond table and figure captions.

**Comment by jjallaire** [comment]
Thanks for the suggestion! This has come up before and we just need to think about the best way to implement (it wouldn't likely be identical in syntax to bookdown but would functionally provide the same thing).

**Comment by dmkaplan2000** [comment]
Not a problem. Thanks for your hard work on Quarto et al.

**Comment by dmkaplan2000** [comment]
For future reference, the solution to this question is more or less explained at https://github.com/quarto-dev/quarto-cli/discussions/7308#discussioncomment-7339787

**Comment by cscheid** [comment]
Yes, I'm inclined to close this as well. We are encouraging authors to use quarto's new uniform notation for crossreferenceable artifacts. I believe those obviate the need for bookdown-style text references.

The original document would now be written as follows:

<table>
<tr><td>

````
---
title: Text references
---

::: {#fig-1}

```{r}
#| echo: false
plot(1:10)
```

This is a long complex caption with an
equation ($E=mc^2$), some calculated
results (`r 5^2`), **bold text** and 
text in "quotes".

:::

See @fig-1.
````

</td><td>
<img width="783" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/be6c94fa-004b-4e07-8697-4f074558eb0a">
</td></tr></table>

**Comment by giabaio** [comment]
I might have a further quirk on this... The artifact captioning works well combined to `kableExtra`, in my examples, *except* for an even quirkier one, where the table within the fenced environment is a `longtable` spanning across multiple pages... Something like

````
:::{#tbl-dataMTC}

```{r}
#| echo: false
#| message: false
#| warning: false

# Reads the table in & fixes the LaTeX code for the parameters and then 
# formats using kableExtra
tibble(x=runif(100),y=runif(100)) |>
   knitr::kable(escape=FALSE,booktabs=TRUE,longtable=TRUE,format="latex") |> 
   kable_styling(latex_options=c("striped","repeat_header","scaled_down")) |>
   row_spec(0,bold=TRUE)
```

The dataset containing information on the $S=24$ trials on smoking cessation. The data were originally reported in @SOMEREFHERE.
:::
````

Using the artifact trick renders the citation perfectly (with the `$S=24$`raw code parsed correctly, as well as with the reference. BUT the table doesn't span across pages... If I use the "normal" code (adding a `label:tbl-dataMTC` and a `tbl-cap: "The dataset containing information on the $S=24$ trials on smoking cessation. The data were originally reported in @SOMEREFHERE."` does render the table correctly, the not the caption...

Am I missing something obvious?
Thanks!

**Comment by cscheid** [comment]
> Am I missing something obvious?

You need to update to the very latest 1.4 prerelease. This works for me:

````
---
title: hello
format: pdf
keep-md: true
keep-tex: true
---

:::{#tbl-dataMTC}

```{r}
#| echo: false
#| message: false
#| warning: false

library(tidyverse)
library(kableExtra)

# Reads the table in & fixes the LaTeX code for the parameters and then 
# formats using kableExtra
tibble(x=runif(100),y=runif(100)) |>
   knitr::kable(escape=FALSE,booktabs=TRUE,longtable=TRUE,format="latex") |> 
   kable_styling(latex_options=c("striped","repeat_header","scaled_down")) |>
   row_spec(0,bold=TRUE)
```

The dataset containing information on the $S=24$ trials on smoking cessation. The data were originally reported in @SOMEREFHERE.
:::
````

That file produces

<img width="252" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/3c67ad38-ce98-4a67-90eb-ca1052926af5">

**Comment by giabaio** [comment]
Yes --- that works perfectly. Thanks so much!
