### ISSUE TITLE
Automatically convert SVG for PDF output

### ISSUE THREAD

**Issue by kuon** [quarto-dev/quarto-cli#196]
I use SVG images in my quarto document, like so:

```
![Electronic overview](overview.svg){layout-align=center}
```

it works fine for HTML, but for PDF it says:

```
LaTeX Error: Unknown graphics extension: .svg.
```

I know that latex do not support svg, and that the usual workflow is to convert svg to PDF using inkscape or similar.

Is there a way to automate this with quarto?

**Comment by jjallaire** [comment]
The easiest thing to do would be to write a Lua filter (https://quarto.org/docs/authoring/shortcodes-and-filters.html#filters) that automatically uses a (pre-generated) PDF or PNG in place of SVG when rendering to PDF. It would look something like this:

```lua
function Image(el)
  if isLatexOutput() then
    --- check el.src for an svg extension
    --- re-assign el.src to the pdf or png version
    --- return the modified element
   return el
 end
end

local function isLatexOutput()
  return FORMAT == "latex" or FORMAT == "beamer" or FORMAT == "pdf"
end
```


This should indeed be a built in feature (so leaving this open for resolution later on)

**Comment by kuon** [comment]
I got the filter working, but is it possible to have the absolute path to the image file within the filter? I was unable to find how.

For example, if the processed document is `chapter/section/hello.qmd` with `intro.svg` in it, I only get `intro.svg` and no way to get the `chapter/section/intro.svg` full path to access the image.

This would let me to automatic "lazy" pdf conversion within the filter.

**Comment by tarleb** [comment]
The [`pandoc.path`](https://pandoc.org/lua-filters.html#module-pandoc.path) module (and maybe `pandoc.system`) can be helpful here. Maybe something like

```
local path = require 'pandoc.path'
local input_dir = path.directory(PANDOC_STATE.input_files[1])
local relative = path.join{input_dir, 'INPUT-RELATIVE-FILE-PATH-GOES-HERE'}
```

**Comment by jjallaire** [comment]
If you configure your filter to run after the quarto filters like this:

```yaml
filters:
  - quarto
  - filter.lua
```

Then you'll get the right path (it will be `chapter/section/intro.svg` and the current working directory will be the project root, so that relative file reference will work).

I have been debating in my head whether user filters should run before or after Quarto filters --- this makes me think that I may have the default wrong (currently user filters run first).

**Comment by jjallaire** [comment]
I've changed the default to have user filters run after quarto filters here: https://github.com/quarto-dev/quarto-cli/commit/606f92f51f307e4520970a6a8dba0d123d28a437

So your filter should work w/o any special configuration.

We are ultimately going to need to allow fairly fine grained control (i.e. per filter) over where user filters run. We will will also need to make some of Quarto's higher level constructs like tabsets, callouts, etc. directly available to filters.

**Comment by knuesel** [comment]
I think a nice way to solve this particular problem is to write the image filename without extension in the markdown source, e.g. write simply `![Electronic overview](overview)`, and call `quarto` with the option `--default-image-extension=svg` to generate the web version, and with `--default-image-extension=pdf` to generate the PDF.

**Comment by jjallaire** [comment]
FYI we now provide `default-image-extension` automatically (it defaults to `png` and then uses `pdf` for pdf formats): https://quarto.org/docs/authoring/figures-and-layout.html#multiformat-figures

**Comment by fuhrmanator** [comment]
I'm very late to this party, but just wanted to share that I am using `latexmk` for the pdf and `self-contained: true` for html in a book project, and I'm able to see my .svg files just fine (no filter necessary for SVG files, but I do use a filter to convert PlantUML/Graphviz diagrams into SVG).

```yml
format:

  html:
    # needed for inline graphviz figures
    self-contained: true

  pdf:
    # has to be latexmk for graphviz/svg figures
    pdf-engine: latexmk
```

The full repo is at https://github.com/fuhrmanator/quarto-test
