### ISSUE TITLE
FYI - if I clone from GitHub and use a version later than 1.1.75, when I render it seems to be looking for a file quarto.ts that it does not find

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-cli#1960]
Simply FYI - if I clone from GitHub and use a version later than 1.1.75, when I render it seems to be looking for a file quarto.ts that it does not find: 

==> (function(input, ...) { invisible(system(paste0('quarto render "', input, '" ', '--to default'))) })('C:/Users/donbo/Documents/R_projects/MTA2022/sites/baseline/pmtbase/payroll_mobility_tax_base.qmd',  encoding = 'UTF-8');
Check file:///C:/Users/donbo/quarto/QUARTO~1/src/quarto.ts
ERROR: NotFound: The system cannot find the file specified. (os error 2)

NotFound: The system cannot find the file specified. (os error 2)
    at Object.opSync (deno:core/01_core.js:172:12)
    at opRun (deno:runtime/js/40_process.js:28:17)
    at Object.run (deno:runtime/js/40_process.js:111:17)
    at reconfigureQuarto (file:///C:/Users/donbo/quarto/QUARTO~1/src/core/devconfig.ts:138:24)
    at quarto (file:///C:/Users/donbo/quarto/QUARTO~1/src/quarto.ts:55:13)
    at file:///C:/Users/donbo/quarto/QUARTO~1/src/quarto.ts:124:11

**Comment by jjallaire** [comment]
This might just be our on the fly reconfiguration not working correctly on windows. Try exiting everything and doing this from the root of `quarto-cli`:

```
.\configure-windows.cmd
```

**Comment by donboyd5** [comment]
Great, thank you.
