### ISSUE TITLE
Unique labels for distinct figures produced by executable code blocks

### ISSUE THREAD

**Issue by githubpsyche** [quarto-dev/quarto-cli#197]
Subfigures defined in markdown can be given unique captions/labels while belonging to a larger figure with its own caption and label. Can this be done for subfigures produced through computations, such as in the example explored here in the [documentation](https://quarto.org/docs/authoring/figures-and-layout.html#computations)? If so, it might be worth providing some documentation how. If not, it would be a desirable feature.

**Comment by jjallaire** [comment]
Indeed they can! See the docs over in the Crossrefs article: https://quarto.org/docs/authoring/cross-references.html#computations (TLDR; use an array of `fig-subcap`)

Agree that we should also add this to the figures and layout docs.

**Comment by githubpsyche** [comment]
Wow, sorry for missing that! And thanks for the prompt reply.
