### ISSUE TITLE
OJS error: jszip is not defined

### ISSUE THREAD

**Issue by aaronschiff** [quarto-dev/quarto-cli#1981]
### Bug description

Using `FileAttachment.zip()` from OJS produces an error in html output rendered by quarto: `ReferenceError: jszip is not defined`. 

Here is a minimal .qmd example: 

~~~
---
title: zip data test
execute:
    echo: false
    warning: true
format: html
---

```{ojs}
dat_zip = FileAttachment("data.zip").zip();
```
~~~

I have tried deleting and reinstalling quarto but this did not solve the problem. 

MacOS 12.4; VSCode

### `quarto check` Output

```
[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /opt/homebrew/opt/python@3.10/bin/python3.10
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      rmarkdown: 2.15

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Up to date        v2022.08      v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [x] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
@cscheid If this is ~ a one-liner we can take it for v1.1 (targeting now) but feel free to punt to v1.2 if its even moderately involved as we are now past "code freeze"

**Comment by aaronschiff** [comment]
@cscheid thanks for clarifying, I didn't realise the implementation is not equivalent. Will try a workaround as you suggest.

**Comment by cscheid** [comment]
@aaronschiff It's something we really ought to document better.

**Comment by cscheid** [comment]
Sorry about the delay, and thanks for the report! Bugfix incoming.
