### ISSUE TITLE
Julia output not displaying in quarto

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1983]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1980

<div type='discussions-op-text'>

<sup>Originally posted by **DomDF** August 18, 2022</sup>
I have an existing query in the RStudio community page, but have been recommended to ask here too. 
If anyone can provide a solution, I will update on this page too: https://community.rstudio.com/t/julia-output-not-displaying-in-quarto/144462

------------

I am writing a quarto document, which includes code chunks in R, Python and Julia.

The output from the Python and R chunks is displaying correctly. However, while the code for the Julia chunks is displaying, the output is not - see the below image:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/34099039/185512471-14dd6ed5-df8e-4782-b9c8-67e7ac07aa33.png">

My YAML header is included below:

```
format:
  html:
    theme: spacelab
    html-math-mathod: mathjax
    toc: true
    toc-location: right
    number-sections: true
    code-copy: true
    code-fold: true
    code-tools: true
    monofont: Fira Code
execute:
  message: false
  warning: false
bibliography: references.bib
```

Please advise on how I can see the output of my Julia code chunks in this document too.

Many thanks</div>

**Comment by jjallaire** [comment]
Hi there, could you provide the full source of the .qmd file you are running?

**Comment by eitsupi** [comment]
@jjallaire Note that, unlike creating an issue from an issue comment, the discussion creator is not notified when an issue is created from a discussion. (So you need to explicitly mentions it).

**Comment by jjallaire** [comment]
@DomDF We are now tracking this issue here rather than in discussions.

**Comment by cscheid** [comment]
@DomDF If you can download the
[latest prerelease](https://github.com/quarto-dev/quarto-cli/releases)
and reproduce the issue and send us a single .qmd file, I'll be happy to take a look at this. Thanks!
