### ISSUE TITLE
Smooth scrolling causes sidebar to unhide itself

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1995]
(EDIT by @cscheid : See the comment below for the behavior in `main`)

Check out this page: https://camilogarciabotero.github.io/biocomp-book/chs-command-line/git-and-github.html

Note that once the TOC sidebar collapses it never restores itself (I actually saw this on one other site as well). If you look in the JS console there are exceptions occurring in sidebar related code which is almost certainly the culprit.

Targeting for v1.1 as I believe this is a regression.

**Comment by cscheid** [comment]
I can take a stab at this.

**Comment by jjallaire** [comment]
Okay I'll assign you as well.

**Comment by jjallaire** [comment]
okay, great. I'll close.
