### ISSUE TITLE
Strange behavior with RStudio

### ISSUE THREAD

**Issue by kwakuduahc1** [quarto-dev/quarto-cli#1998]
This took me almost 24 hours before I realized this error. 

RStudio does not "Render" if the file name contains a space.

Surprisingly however, it works in Visual Studio Code.

![image](https://user-images.githubusercontent.com/11381582/185624000-bfe8e082-2299-4f0e-a8d2-9bad38699195.png)

**Comment by jjallaire** [comment]
It looks like from the screen shot that this is project creation rather than rendering? What action did you take in the IDE that resulted in this?

**Comment by jjallaire** [comment]
Also which version of the IDE are you running?

**Comment by kwakuduahc1** [comment]
Either way, it does not work if the name of the project or the file has a space in them, at least, on my computer.

**Comment by jjallaire** [comment]
Okay, thank you for the additional details. I can reproduce this in both scenarios!

**Comment by jjallaire** [comment]
This is now tracked on the RStudio repo: https://github.com/rstudio/rstudio/issues/11804
