### ISSUE TITLE
Quarto Document Language for Spanish NOT working

### ISSUE THREAD

**Issue by JuanRodCif** [quarto-dev/quarto-cli#1999]
### Bug description

I need to prepare a '.qmd' document that delivers an output in Spanish. I decided to make a test for both **docx** and **HTML** outputs before I worked on the actual document. This is the code I used in the .qmd file:

````
---
title: "Descarbonización de la Matriz Energética Colombiana"
format: docx
lang: es
---

```{r}
library(tinytex)
```

Hola, ese niño está jugando._
````

But the output for both MS-Word and HTML resulted in text like the one contained in the Word output file I am attaching. 

The RStudio IDE version I am using is 2022.07.1 Build 554.
The Windows version I am using is  Windows 11 Home Single Language.
The processor I am using is Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz.
The installed RAM is 12,0 GB.
I am using the Package quarto version 1.2.
I am using R version 4.0.3.

### `quarto check` Output

C:\R\RStudio\Quarto\CursoUniandesJR_files>quarto check

[>] Checking Quarto installation......OK
      Version: 1.0.38
      Path: C:\Users\maria\AppData\Local\Programs\Quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.0.5
      Path: C:/R/R-4.0.5
      LibPaths:
        - C:/R/R-4.0.5/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK

### `quarto tools check` Output

C:\R\RStudio\Quarto\CursoUniandesJR_files>quarto tools check
[>] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.08

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X ] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X ] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by JuanRodCif** [comment]
If the "Quarto Check Output" and "Quarto Tools Check Output" are needed I would need the favor to instruct me on how to generate them.

**Comment by jjallaire** [comment]
I'm not sure what you are expecting to see. This is what I get in HTML:

<img width="774" alt="Screen Shot 2022-08-19 at 1 34 27 PM" src="https://user-images.githubusercontent.com/104391/185675735-52a5b078-eeab-4167-852a-871737d04a64.png">

And this is what I get in MS Word:

<img width="838" alt="Screen Shot 2022-08-19 at 1 34 37 PM" src="https://user-images.githubusercontent.com/104391/185675792-66e94cf9-c18f-4748-974d-1614744fd5fb.png">

Neither seems problematic.

To run `quarto check` you can just go to the Terminal in RStudio and type:

```bash
quarto check
```

**Comment by JuanRodCif** [comment]
Thanks for your help JJ! I thought I had attached my MS-Word output file. here it is...
[CursoUniandesJR.docx](https://github.com/quarto-dev/quarto-cli/files/9385201/CursoUniandesJR.docx)
As you can see the Spanish characters are not being printed, instead a question mark substitutes for them. The output file you are obtaining is correct, that is the one that I would like to get.

As for the quarto check command, I have included their results above. Thanks for this tip!

I have tried to install the two missing packages, but I receive the following messages (any clue as to how to solve those? I have tried R versions 4.03 and 4.05.

install.packages("tinytex")

  There is a binary version available but the source version is later:
        binary source needs_compilation
tinytex   0.38   0.41             FALSE

installing the source package ‘tinytex’

trying URL 'https://cran.rstudio.com/src/contrib/tinytex_0.41.tar.gz'
Content type 'application/x-gzip' length 32910 bytes (32 KB)
downloaded 32 KB

* installing *source* package 'tinytex' ...
** package 'tinytex' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'tinytex'
    finding HTML links ... done
    check_installed                         html  
    copy_tinytex                            html  
    install_tinytex                         html  
    is_tinytex                              html  
    latexmk                                 html  
    parse_install                           html  
    parse_packages                          html  
    r_texmf                                 html  
    tinytex-package                         html  
    tl_pkgs                                 html  
    tl_sizes                                html  
    tlmgr                                   html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (tinytex)

The downloaded source packages are in
	‘C:\Users\maria\AppData\Local\Temp\RtmpOIGJFl\downloaded_packages’
> install.packages("chromium")
Warning in install.packages :
  package ‘chromium’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by jjallaire** [comment]
Not sure what's going on with you system. It's possible your input file isn't UTF-8 encoded?  I get the correct/expected document testing on both Windows and MacOS.

**Comment by JuanRodCif** [comment]
Good morning JJ!
Thanks for taking time from your Saturday to help me with this issue. I really appreciate it.  The problem has been solved!! 
I was really frustrated because I had done all my Specialization in Statistics with RStudio and it worked perfectly well. But it was in English, this is the first time I was using RStudio with Spanish as the markdown language.

How I solved it? I went to RStudio's 'File' option and chose 'Reopen with encoding'. There, I was able to see that ISO-8859-1 was the default encoding being used by the system. I changed it to UTF-8 and then went to the 'Save with encoding' and again changed the encoding to UTF-8. I had to restart R and re-write the text. I proceeded to Render the .qmd file and the output was perfectlly displayed!

Thanks a million JJ!!

**Comment by JuanRodCif** [comment]
I am incredible greatfull with JJ Allaire for his help. I managed to solve the issue in a couple of days.

**Comment by jjallaire** [comment]
So glad to hear you solved the problem!

Note that in recent years we have made UTF-8 the default for all rmd/qmd files but perhaps this one squeaked through that.

**Comment by JuanRodCif** [comment]
Oh, I understand.
