### ISSUE TITLE
Equations cross-referencing and LaTeX  \mathbb

### ISSUE THREAD

**Issue by VivaldoMendes** [quarto-dev/quarto-cli#2000]
I am using Quarto in VSCode, and both versions are up to date. Quarto's version is 1.32.0.

I am testing it with basic LaTeX things. For example, I try to apply cross-references to maths equations but always get the word "Equation" preceding the equation number. This practice is inconvenient if we have more than one equation or want to use a short name for "equation", e.g., "eq.". How can I customize this type of output?

MWE: 
```
$$
\max_{\left\{C_t, K_{t+1}\right\}} \  \sum_{t=0}^{\infty} \beta^t \ln C_t
$$ {#eq-1}

$$
K_{t+1} + C_t= AK_t^\alpha
$$ {#eq-2}

$$
\hat{y}_{t}=\mathbb{E}_{t} \hat{y}_{t+1}-\frac{1}{\sigma}\left(i_{t}-\mathbb{E}_{t} \pi_{t+1}-r_{t}^{n}\right)
$$ {#eq-3}

See @eq-1, @eq-2, and @eq-3 for further information.
```
The output is below. I would have wanted to see something like:
"See eq. (1), (2), and (3) for ....".

![aa](https://user-images.githubusercontent.com/48516539/185687110-beca79ff-ea0d-470f-bcd7-eda924db3699.png)

Finally, notice the expectations operator displayed above looks rather strange. How can I obtain a more conventional symbol for this operator, usually accomplished in LaTeX, by inserting into the doc's preamble the following code:

```
\usepackage{amsmath,amssymb}
\DeclareMathOperator{\E}{\mathbb{E}}
```
Thank you.

**Comment by jjallaire** [comment]
You can use the `eq-prefix` option to change the standard prefix: https://quarto.org/docs/authoring/cross-references.html#references-1. You can also use the minus (`-`) qualifier before the crossref to supress the prefix entirely: https://quarto.org/docs/authoring/cross-references.html#references

For example:

```markdown
---
title: "Equations"
crossref:
  eq-prefix: "eq."
---

$$
x + 1
$$ {#eq-first}

See @eq-first

$$
y + 1
$$ {#eq-second}

See equation [-@eq-second].
```

Yields this:

<img width="761" alt="Screen Shot 2022-08-20 at 8 01 55 AM" src="https://user-images.githubusercontent.com/104391/185745200-bab092c4-0ff1-452d-85c0-2ddbd9c49972.png">

**Comment by VivaldoMendes** [comment]
Thank you very much for your help. It took me a while to figure out how to set the correct way for the ` eq-prefix:" " ` but I managed to get it. This issue is fundamental in a book or an article; if the docs could provide a simple example, it would be handy.

Example below using the two alternative methods you mentioned:

See Eqs. ([-@eq-1]), ([-@eq-2]), and ([-@eq-3]) for ...  or using _equation prefix_ -- like this: **eq-prefix: "" ** -- to get the desired output: Eqs. (@eq-1), (@eq-2), and (@eq-3).

Output as follows:

![aa](https://user-images.githubusercontent.com/48516539/185768300-f8ef0dd0-a3ac-4b28-b9bb-17f9a33fefa5.png)

Thanks

**Comment by jjallaire** [comment]
Okay, glad you go this working the way you wanted it to! Yes, we will indeed improve docs on this (re-opening this issue as a reminder to improve the docs).

**Comment by cscheid** [comment]
Fixed on `quarto-web/main`.
