### ISSUE TITLE
Extension resources in a symlinked dir aren't found

### ISSUE THREAD

**Issue by wch** [quarto-dev/quarto-cli#2001]
### Bug description

If an extension has resources in a directory which is a symlink to some other directory, then the resource files don't get copied when they are added as HTML dependencies to the document.

```
.
└── _extensions
    └── myext
        ├── myext-resources   <- symlink to a directory with resource files
        │   └── <resource files>
        ├── _extension.yml
        └── myext.lua
```

**Comment by jjallaire** [comment]
@dragonstyle It looks to me like our copying code actually has logic to copy symlinks as symlinks (i.e. not their contents). See `copySymlinkSync()`. Not sure if that code is in play here though. In any case it seems like we'd want to actually resolve the symlink in this case and copy the contents (as w/o that the destination will still depend on the symlink and thus not be deployable). I will target for v1.1 but if this looks involved we can defer to v1.2 given that we are about to hit RC.

**Comment by dragonstyle** [comment]
For the case of HTML dependencies, it looks to me like we are properly copying symlinked files (e.g. we don't explicitly copy the symlink), but we are preventing copying of files that escape the `root directory`, which in a simple case would be the input directory. Worth discussing whether this is in fact the cause and whether the fix to this is desirable.

**Comment by jjallaire** [comment]
@dragonstyle @wch can correct me if I am wrong but these files are effectively a global cache of an expensive to download bundle. This may come up again w/ e.g. map tiles so I think is worth supporting (we might even want to make a cross-platform cache location available as a service to extensions)

**Comment by dragonstyle** [comment]
Ok yeah that makes sense - perhaps we can discuss best approach for 1.1 and long term tomorrow...

**Comment by wch** [comment]
@jjallaire That's exactly right. It's a bundle for Shinylive, which is about 200 MB. It's saved using the user cache dir using Python appdirs package. (On my Mac, the user cache directory is ~/Library/Caches.)

**Comment by jjallaire** [comment]
I believe @wch needs one other thing we discuss on slack next week to make the shinylive extension work -- to be able to target the copying of an HTML dependency to the root directory of the website (this is required for serviceworkers). @wch Maybe we should do a call tomorrow to talk over everything you need for this (including potential tooling hooks e.g. for completion in VS Code) so we make sure to get it into v1.1 (which is going to RC tomorrow or Tuesday)

**Comment by wch** [comment]
A call to discuss this stuff would be great.

I've had some help from @cscheid with this stuff. There are actually two more things that I think that are needed:

* Copying the serviceworker to the root of the website.
* Copying only the needed Python package files to `site-libs/` directory. This can result in a (for example) 28MB deployment instead of one that is 200MB .

Some more detail on the second point:
* There are a number of files that are needed for all Shinylive applications. This includes some JS files, as well as some files from pyodide, like pyodide.js and pyodide.asm.wasm. Currently I'm adding all of these files in a HTML dependency object named `"shinylive-base-deps"`, in `scripts`, `stylesheets`, or `resources`, as appropriate for each file.
* There are other Python packages (in the form of .whl files), some of which are needed for a given application, and some of which are not. Currently, it calls out to Python to figure out which packages are needed for each application on a page. This is where I've hit a roadblock. The idea was to create a new HTML dependency for each package. For example, if an application needs the shiny and matplotlib packages, then the filter would create a separate HTML dependency for each package and add it to the document. This would almost work, but the problem is that each of these files would be copied to a separate subdirectory within `docs/site_libs/quarto-contrib/`, when they need to all go into the same subdir.

**Comment by jjallaire** [comment]
Okay let's try to do the call later on this week. I talked w/ @dragonstyle and the changes required to make all this work are involved enough that we don't want to cram them into v1.1. However, we'll do them early in v1.2 and there will a binary pre-release to make the changes available more broadly.

**Comment by wch** [comment]
One more note: As an alternative to following symlinks, it would also work for me if the HTML dependency files could be copied from a path that's out of the quarto project tree (like `~/Library/Caches`).

**Comment by dragonstyle** [comment]
This should be addressed via recent changes to allow paths to any directory in html dependencies, to add html dependency attachments, and to explicitly support service workers in html dependencies.

**Comment by KeAWang** [comment]
Is there a working example of where I can `quarto render` with symlinked directories?

**Comment by KeAWang** [comment]
I also tried
```
  sidebar:
    style: docked
    contents: my-simlinked-dir/*
```
and
```
  sidebar:
    style: docked
    contents: auto
```
but I get "TypeError: Cannot convert undefined or null to object" for the first method

**Comment by cscheid** [comment]
I think the issue here is that you're using `.md` as an extension. What happens if you use `.qmd`? Though, do note that quarto will use that directory to produce intermediate files, which might not be what you expect (and also, can you open a new issue for this? Thanks.)

**Comment by KeAWang** [comment]
Done! See https://github.com/quarto-dev/quarto-cli/issues/4167. Fails for both `.qmd` and `.md` Thanks!
