### ISSUE TITLE
DLL load failed while importing _device when rendering HTML in VS Code Python

### ISSUE THREAD

**Issue by NovaVolunteer** [quarto-dev/quarto-cli#2002]
### Bug description

I can't seem to clear this error, looks like it has something to do with .ddl, the python kernel renders find by Rendering HTML preview just won't work.  Below is the terminal output. I'm running the latest version, just got it today. 

- [ ] ________________

C:\Users\Brian Wright\Documents\R\jex_matching_algo>cmd /C"quarto preview quarto_demo.qmd --to html --no-browser --no-watch-inputs"
FINDSTR: Cannot open Wright

Starting python3 kernel...Traceback (most recent call last):
  File "C:\Users\Brian Wright\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module> 
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\Brian Wright\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 17, in <module>
    from nbclient import NotebookClient
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\nbclient\__init__.py", line 6, in <module>
    from .client import NotebookClient, execute  # noqa: F401
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\nbclient\client.py", line 14, in <module>
    from jupyter_client import KernelManager
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\jupyter_client\__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\Users\Brian Wright\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
**ImportError: DLL load failed while importing _device: The specified module could not be found.**

![quarto_issue](https://user-images.githubusercontent.com/19676476/185706499-bdeb7e8f-710e-4631-8ccf-66c6254be316.PNG)

### `quarto check` Output

[>] Checking Quarto installation......OK
      Version: 1.0.38
      Path: C:\Users\Brian Wright\AppData\Local\Programs\Quarto\bin\
      CodePage: unknown

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.8.13 (Conda)
      Path: C:/Users/Brian Wright/anaconda3/python.exe
      Jupyter: 4.10.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.1.1
      Path: C:/PROGRA~1/R/R-41~1.1
      LibPaths:
        - C:/Users/Brian Wright/Documents/R/win-library/4.1
        - C:/Program Files/R/R-4.1.1/library
      rmarkdown: 2.11

[>] Checking Knitr engine render......OK

### `quarto tools check` Output

(base) C:\Users\Brian Wright\Documents\R\jex_matching_algo>quarto tools check
FINDSTR: Cannot open Wright
[>] Inspecting tools

Tool         Status                    Installed     Latest  
chromium     Not installed             ---           869685
tinytex      External Installation     ---           v2022.08

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Hi there, sorry you are having trouble with this. This is something to do with your local Python installation and without actually getting hands on your system it's hard to say what. You could try using the **Python: Select Interpreter** command to specify the use of another version of Python on your system?

**Comment by NovaVolunteer** [comment]
Ok thanks for the quick response, I think I'm going to remove my current environment and rebuild. As a side, what pointed you to the python installation?

**Comment by jjallaire** [comment]
Any weird initialization errors from Python means it for some reason can't load/run from within a VS Code terminal.

**Comment by NovaVolunteer** [comment]
Gotcha thanks

Brian Wright

On Aug 20, 2022, at 10:29 AM, J.J. Allaire ***@***.***> wrote:

﻿

Any weird initialization errors from Python means it for some reason can't load/run from within a VS Code terminal.

**Comment by NovaVolunteer** [comment]
Just to close the loop here, I need to add "C:\Users\Brian Wright\miniconda3\Library\bin" the PATH environment variable, during miniconda installation, as seen in the image below, it recommends not adding to PATH, but I assume as a result terminal in VS Code couldn't launch the kernel for the HTML preview. I had to reload the environment to remember this was the case.  


![Add to path Mini-Conda](https://user-images.githubusercontent.com/19676476/186010902-594c46af-e5d7-489b-a762-f1befad0fa4b.PNG)

**Comment by jjallaire** [comment]
Thanks for the follow up! In the very latest version of the VS Code extension (released just a few days ago) we put in some code to wait on the activation of the conda environment in the Terminal before executing `quarto preview`. Sounds like though that this issue went deeper than that (VS Code not being able to see Conda at all due to the PATH issue -- I guess it is mentioned in their installer screen!)

**Comment by NovaVolunteer** [comment]
No worries and yes, I saw that on a different issue thread, which made the problem all the more annoying, lol.  I can imagine others might have the same issue if they follow the miniconda recommended installation instructions.
