### ISSUE TITLE
Installing and using Quarto with VSCode on MacOS 10.13 High Sierra.

### ISSUE THREAD

**Issue by padpadpadpad** [quarto-dev/quarto-cli#2004]
### Bug description

Hi Quarto team

I am trying to use Quarto with VSCode on now un-updateable MacOS 10.13 High Sierra. Quarto installs fine and I can install the Quarto extension for VSCode. However nothing can render due to:

```bash
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
```

When I click Render I get the exact same output as from `quarto check`.

Is this salvageable or is the computer too old!

### `quarto check` Output

``` bash
[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /Applications/quarto/bin

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/quarto/bin/tools/deno (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/quarto/bin/tools/deno (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

/usr/local/bin/quarto: line 106: 25760 Abort trap: 6           "${SCRIPT_PATH}/tools/deno" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"
```

### `quarto tools check` Output

``` bash
Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [x] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Sadly the computer is indeed too old
