### ISSUE TITLE
Fix favicon link used as default image when social sharing or add an OG image ? 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2014]
See slack discussion on this in `#quarto` channel.

This is what we get currently when sharing links on Community 
https://community.rstudio.com/t/cannot-get-quarto-pre-render-to-work/143566/3?u=cderv

and it seems we don't have what is needed to get cards using OG meta 
https://www.opengraph.xyz/url/https%3A%2F%2Fquarto.org%2Fdocs%2Fprojects%2Fscripts.html

We encountered this issue already in other places where sharing link tries to create a card. 

I believe we have at least to fix the favicon links as I think: 

* We don't have OG meta for image it seems so it can't be used to generate an official card
* Some website will try to use other information for that, like the favicon for the image. 

For example, for the discourse sharing above, I think it tries to use this information 
````
<link href="../../favicon.png" rel="icon" type="image/png">
````

but the link is relative so it will generate this in Discourse when used as an image 
```
<img src="[https://quarto.org/docs/projects/scripts.html/../../favicon.png](https://quarto.org/docs/favicon.png)" class="site-icon">
```

Couldn't we use an absolute link for the favicon ? 
````
<link href="/favicon.png" rel="icon" type="image/png">
````

would this break the favicon ? 

At first I believe that is what was done (https://github.com/quarto-dev/quarto-web/commit/c9c59624c39595e5ed5c9c0050a461b4e3712343#diff-469a07f57393912a9c17c3ea50ceebe991e32b008beb167a200b17e91fdac6d2L223) before the quarto feature was used. Is it something we should fix in Quarto-cli ? 

But more generally, what about adding a default OG image maybe for our website ? 

cc @dragonstyle

**Comment by dragonstyle** [comment]
I'm just working through this issue right now. Regarding the favicon (I'll follow up separately regarding a default image):

I don't think that we should change the link behavior - we are forming valid paths to favicon specified in `_quarto.yml` and I would be really surprised if clients weren't resolving this path correctly. I just tried on a number of clients and most seem to ignore it, but for Discourse specifically, it seemed like it was resolved properly:

<img width="768" alt="Screen Shot 2022-08-21 at 11 56 18 AM" src="https://user-images.githubusercontent.com/261654/185799797-5c083f6c-8624-4b56-a50f-5bc376f57faf.png">

Are you still seeing issues when you share links on Discourse?

This all flows through our pretty standard path resolution which allows the user to provide a `_quarto.yml` relative path for the favicon and then makes that path valid for each input that is rendered, and it seems good to me that this is all working without much in the way of special carve outs so long as we're generating valid HTML, which in this case it seems like we are.

**Comment by dragonstyle** [comment]
@cderv Question for you regarding the default image - we've gone around on this before (we used to provide a default image for every page, but found that it essentially resulted in the image being 'noise' since it was frequently not varying when you shared multiple links and frequently had no relation to the content). 

I am thinking that not having an is would be pretty acceptable since clients tend to solve for this case by having a reasonable rendering of previews with no image. I've tested some and felt ok about the way link previews work in the cases that I've seen. Do you have cases that seem pretty broken that I could look at or do you just find that rendering without images generally looks bad?

**Comment by dragonstyle** [comment]
We've add a default image for pages where it makes sense. We have a valid path to our favicon on every page and I just tested using the Discourse test server, which correctly renders a page with no open graph image data:

<img width="832" alt="Screen Shot 2022-09-22 at 8 14 38 PM" src="https://user-images.githubusercontent.com/261654/191872238-b502af9c-d68b-4a5b-875a-2956f4d3c8b3.png">

I think it is likely that the RStudio discourse server is misconfigured or perhaps using an older version of Discourse that doesn't properly handle valid open graph data.

I think we should open an issue there.

**Comment by cderv** [comment]
Thanks @dragonstyle  ! I'll see with Curtis about discourse.
