### ISSUE TITLE
Setting transition="none-*" turns on fading

### ISSUE THREAD

**Issue by EmilHvitfeldt** [quarto-dev/quarto-cli#2016]
### Bug description

Setting either `none-in` or `none-out` results in fading instead of nothing. 

Reprex:

````md
---
format: revealjs
---

## slide 1

## slide 2 {transition="none-in none-out"}

## slide 3

````

results:

![Kapture 2022-08-20 at 18 22 37](https://user-images.githubusercontent.com/14034784/185756814-c45b403a-503d-4ba4-845f-674b80e402bc.gif)

## RStudio about

Using MacOS

<img width="299" alt="Screen Shot 2022-08-20 at 6 26 41 PM" src="https://user-images.githubusercontent.com/14034784/185756882-57d02ad1-b044-4c2f-b661-f4e947a67d0b.png">

### `quarto check` Output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.9
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources
      LibPaths:
        - /Users/emilhvitfeldt/Library/R/arm64/4.2/library
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status               Installed     Latest  
chromium     Not installed        ---           869685  
tinytex      Update available     v2021.12      v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by EmilHvitfeldt** [comment]
Found this problem when debugging the following document

````md
---
format: revealjs
---

## slide 1

## slide 2 {transition="slide-in"}

## slide 3

````

Which resulted in `slide 2` sliding in, and fading out. Please let me know if I should file this behavior as a separate issue.

**Comment by jjallaire** [comment]
This is all controlled by revealjs (we don't implement `transition` directly rather we just pass the attributes on to reveal). I'd say that if the behavior isn't desirable the best thing to do is plead the case w/ reveal directly (as I don't even know how we would override their internal default behavior)
