### ISSUE TITLE
ObservableJS penguins exmaple does not work with transpose but works if you load csv file.

### ISSUE THREAD

**Issue by meldarionqeusse** [quarto-dev/quarto-cli#2018]
I am trying to replicate the example shown here : https://quarto.org/docs/interactive/ojs/ but instead of using the csv file I am using the penguins data set and I am not able to get the plots showing up when I used the transpose function but it work when I use the csv file found [here](https://github.com/quarto-dev/quarto-web/blob/main/docs/interactive/ojs/palmer-penguins.csv) . 

````
---
title: "test observ"
format: html
execute:
  echo: false
---

## Quarto
``` {r, include=FALSE}
library("palmerpenguins")
ojs_define(data = penguins)
```

```{ojs}

viewof bill_length_min = Inputs.range(
  [32, 50], 
  {value: 35, step: 1, label: "Bill length (min):"}
)

viewof islands = Inputs.checkbox(
  ["Torgersen", "Biscoe", "Dream"], 
  { value: ["Torgersen", "Biscoe"], 
    label: "Islands:"
  }
)
```

```{ojs}


filtered = transpose(data).filter(function(penguin) {
  return bill_length_min < penguin.bill_length &&
         islands.includes(penguin.island);
})
Plot.rectY(filtered, 
  Plot.binX(
    {y: "count"}, 
    {x: "body_mass", fill: "species", thresholds: 20}
  ))
  .plot({
    facet: {
      data: filtered,
      x: "sex",
      y: "species",
      marginRight: 80
    },
    marks: [
      Plot.frame(),
    ]
  }
)
```
````

This is what I get the plots are not showing. When I use the csv the plots show up. 

![image](https://user-images.githubusercontent.com/21668964/185757626-5390586d-64d4-4897-9968-9ef572be973c.png)

**Comment by cscheid** [comment]
@meldarionqeusse Can you give https://yihui.org/issue/#please-format-your-issue-correctly a read and follow the instructions there to make your markdown usable for us? Thank you!

**Comment by meldarionqeusse** [comment]
Thanks I edited the original comment. Hope it's more understandable if not I will reformat it once I am on a computer

**Comment by cscheid** [comment]
Your columns are misnamed. The data from the library has slightly different column names from the csv. It's a good practice to check your column names:

````
```{ojs}
data
```
````

<img width="881" alt="image" src="https://user-images.githubusercontent.com/285675/187478677-1b6000f0-fe38-496a-8339-3f8c2c252867.png">

Notice `bill_length_mm` vs `bill_length`, etc.

**Comment by meldarionqeusse** [comment]
Thanks for looking into this the problem I am seeing is with the documentation that is on this link: https://quarto.org/docs/computations/ojs.html 

![image](https://user-images.githubusercontent.com/21668964/187646091-9909db99-ab55-49ac-b7b7-abd7356e0c2b.png)

`penguin.bill_length` should be `penguin.bill_length_mm` or else the plamerpenguis.csv should be update to match the headings of the palmer penguins dataset.
 
````
```{ojs}
filtered = transpose(data).filter(function(penguin) {
  return bill_length_min < penguin.bill_length_mm &&
         islands.includes(penguin.island);
})
```
````

**Comment by cscheid** [comment]
This change is already made on the repo: https://github.com/quarto-dev/quarto-web/edit/main/docs/computations/ojs.qmd and the website will be rebuilt shortly.
