### ISSUE TITLE
Warning: "Unable to display output for mime type(s)"

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#2031]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2030

<div type='discussions-op-text'>

<sup>Originally posted by **lukefullard** August 21, 2022</sup>
Hi,

I'm trying to add a table to my quarto document using the [Panel Tabulator widget](https://panel.holoviz.org/reference/widgets/Tabulator.html). 
While the table displays nicely and is interactive, I get a warning printed into my pdf:

_Unable to display output for mime type(s)_

I googled and found [another document with a similar warning](https://nasa-openscapes.github.io/2021-Cloud-Hackathon/tutorials/05_Data_Access_Direct_S3.html#plot-the-hls-s3-object).
I tried adding 

#| warning: false
#| error: false

to my Python block, bit the warning text still appeared.
Could anyone tell me how to suppress this warning?
Thanks.
</div>

**Comment by jjallaire** [comment]
I believe that we have fixed this in v1.1 (I recall addressing a similar issue w/ another widget and I can't reproduce that message occurring in v1.1 w/ the Tabulator example). You can download the pre-release here: https://quarto.org/docs/download/prerelease.html

**Comment by jjallaire** [comment]
@lukefullard we have moved this to an issue and will delete the discussion.

**Comment by lukefullard** [comment]
> I believe that we have fixed this in v1.1 (I recall addressing a similar issue w/ another widget and I can't reproduce that message occurring in v1.1 w/ the Tabulator example). You can download the pre-release here: https://quarto.org/docs/download/prerelease.html


Thanks! That's great to know.
In the meantime I also found a solution, instead of displaying my widget with
df_widget

I used:
df_widget.embed()

:--)
