### ISSUE TITLE
Quarto not rendering Holoviz plots | Unable to display output for mime type(s):

### ISSUE THREAD

**Issue by lgonzalezsa** [quarto-dev/quarto-cli#2033]
### Bug description

Creating quarto website with a Jupyter Notebook using Python [Holoviz](https://holoviz.org/) plot but getting `Unable to display output for mime type(s):`

I also tested seaborn package and the plots render properly. 

Do I need to configure a property for Holoviz plots to render properly with Quarto?

Please check my minimal reproducible example here:
https://lgonzalezsa.github.io/hello_quarto/testing.html#fig-plot
https://github.com/lgonzalezsa/hello_quarto/blob/main/test/testing.ipynb 

### `quarto check` Output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: /home/gonluisr/miniconda3/envs/conda_dev/bin/python
      Jupyter: 4.10.0
      Kernels: julia-(8-threads)-1.7, julia-1.7, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08
```
Linux OS:
```bash
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 5.19.0-76051900-generic 
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cderv** [comment]
Hello @lgonzalezsa,

Just to share that maybe this is related to https://github.com/quarto-dev/quarto-cli/issues/2031 as the error message is the same. 
See the discussion there: 
* The pre release version may have a fix for this already
* The user there solved this by using `df_widget.embed()`

Hope it helps

**Comment by jjallaire** [comment]
I can confirm that the notebook does render correctly in v1.1
