### ISSUE TITLE
How to cross reference figures from distinct Jupyter Notebooks ?

### ISSUE THREAD

**Issue by lgonzalezsa** [quarto-dev/quarto-cli#2034]
### Bug description

More a question than a bug but wondering if I have multiple Jupyter Notebooks in my project, each of those with different figures that I would like to reference from other notebook, how can I do that?

In the "testing copy.ipynb" notebook I put two cross references: @fig-plot and @fig-plot-copy
fig-plot belongs to testin.ipynb and as shown in the image below, not rendering. Also getting `WARNING: Unable to resolve crossref @fig-plot`

Minimal Reproducible Example here:
https://lgonzalezsa.github.io/hello_quarto/cross_copy.html
https://github.com/lgonzalezsa/hello_quarto/blob/main/test/testing%20copy.ipynb
![image](https://user-images.githubusercontent.com/704686/185818466-69459ec2-5c8e-4b90-8178-ad9f7f5d63f4.png)

### Checklist

- [ ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [ ] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
If you create a project of type 'book' you can resolve references across chapters/pages: https://quarto.org/docs/books/
