### ISSUE TITLE
"\Quarto\bin\ was unexpected at this time" error for all commands

### ISSUE THREAD

**Issue by kpjmcg** [quarto-dev/quarto-cli#2035]
### Bug description

I keep getting the error "\Quarto\bin\ was unexpected at this time" when trying to use a fresh install of Quarto. 

The only command I have found so far that works is "quarto -- version" which outputs:

"1.0.38"

Windows 10  
Version	10.0.19044 Build 19044

I have verified that quarto is in my path. 

### `quarto check` Output

\Quarto\bin\ was unexpected at this time.

### `quarto tools check` Output

\Quarto\bin\ was unexpected at this time.

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Could you try our v1.1 pre-release (it has some fixes for windows shell issues): https://quarto.org/docs/download/prerelease.html

**Comment by dragonstyle** [comment]
We believe this should be fixed in the 1.1 release, which is generally available now.
