### ISSUE TITLE
`code-link` and `code-line-numbers` does not work together when both set to true

### ISSUE THREAD

**Issue by JauntyJJS** [quarto-dev/quarto-cli#2036]
Hi,

I was running a simple Quarto document that just takes the mean of `c(1,2,3)` and wanted to know how `code-link` and `code-line-numbers` work. 
The versions are Quarto 1.0.11, R 4.2.1 and RStudio 2022.07.1 Build 554. 

Hopefully the issue reported can be reproduced.

I understand that both R packages `downlit` and `xml2` need to be installed.

Below is the content of the Quarto document.

```
---
title: "CodeNumberVSCodeLink"
format:
  html:
    code-link: true
    code-line-numbers: true
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

```{r}
mean(c(1,2,3))
```

If I set `code-link: true` and `code-line-numbers: false` and click render, the hyperlink works 

![image](https://user-images.githubusercontent.com/9066508/185841447-780f55c9-9928-43e4-a8de-98a1ec7a0339.png)

If I set `code-link: false` and `code-line-numbers: true` and click render, the code numbering works

![image](https://user-images.githubusercontent.com/9066508/185841533-b4f56945-578d-448d-82ba-0306f2ada545.png)

However when I set both `code-link: true` and `code-line-numbers: true` and click render, **only** the the code numbering works.

![image](https://user-images.githubusercontent.com/9066508/185841667-cfa72099-7f39-4f26-8bc8-6e9e57876909.png)

Is there a reason for this behaviour ?

**Comment by jaredlander** [comment]
Took my a while to figure out that `code-line-numbers` prevented `downlit` from working. Can the [documentation](https://quarto.org/docs/output-formats/html-code.html) be updated until it's fixed so that others don't have to experiment to find this problem?

**Comment by cderv** [comment]
This was added to doc in quarto-dev/quarto-cli#747

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/f6d5b3da-92c3-4e4b-bece-690475ab811b)

We'll track resolution of this in #3519 and this is related to support in **downlit** itself 
* https://github.com/r-lib/downlit/issues/133
