### ISSUE TITLE
self-contained document have broken images

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2037]
### Bug description

````markdown
---
title: "test"
format: 
  html:
    self-contained: true
keep-md: true
---

```{r}
plot(mtcars)
```

````

This will produce with quarto 1.1.107 on the RStudio Viewer preview pane on Windows
![image](https://user-images.githubusercontent.com/6791940/185857724-7c6225f6-7960-4c3e-b9d2-e06938f6d060.png)

This is due to a bug in Pandoc introduced in version 2.19.1 when base64 package was changed. 

See https://github.com/jgm/pandoc/issues/8239

We should probably wait for new Pandoc release before new Quarto release 

FWIW I check with R Markdown document that using Pandoc 2.19 works, and 2.19.1 does not.

**Comment by garthtarr** [comment]
I wonder if this error to the rendering of the fontawesome extension in self-contained mode is related https://github.com/quarto-ext/fontawesome/issues/15

**Comment by jjallaire** [comment]
I just reverted v1.1 to use Pandoc 2.19 which should resolve this
