### ISSUE TITLE
Publish to Confluence

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#2038]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2003

<div type='discussions-op-text'>

<sup>Originally posted by **andrewcstewart** August 19, 2022</sup>
Looking under the list of formats under https://quarto.org/docs/output-formats/all-formats.html, one format that would be nice to add is Confluence's.  I think there are probably a few different options there, but one would be https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html 

Just starting this conversation to see if there is similar interest out there.</div>

**Comment by mcanouil** [comment]
The following could be of interest: <https://github.com/jpbarrette/pandoc-confluence-writer>

**Comment by allenmanning** [comment]
This is now available in the 1.3 pre-release.  https://quarto.org/docs/prerelease/1.3/confluence.html
