### ISSUE TITLE
How does one edit the HTML for a reveal.js theme?

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-cli#204]
I admit this might be a bit niche.

I like using this theme: https://github.com/dzello/revealjs-themes#sunblind

To get the bold border, 

>   1. Add 4 divs to your HTML page:
```html
    <div class="line top"></div>
    <div class="line bottom"></div>
    <div class="line left"></div>
    <div class="line right"></div>+
```

How do I override the basic template to add those? If I add them from the qmd file, they're not at the right level (they have to come after the div "slides").

**Comment by cderv** [comment]
These themes seems pretty specific in the way they work. For reference, instructions is here: 
https://github.com/dzello/revealjs-themes/blob/master/css/theme/sunblind.css

````
/**
  [ sunblind ]
  A blindingly sunny theme for Reveal.js with Lora + Leto fonts and a colorful border.
  By Josh Dzielak, https://dzello.com/, License MIT
  The bold border is optional and requires some HTML. To use it:
  1. Add 4 divs to your HTML page:
    <div class="line top"></div>
    <div class="line bottom"></div>
    <div class="line left"></div>
    <div class="line right"></div>
  2. Set { margin: 0.2 } in the Reveal.js initializer to make sure
  your presentation content doesn't collide with the frame.
  Like the theme but don't like the colors? Don't fret. Just change
  $borderColor and/or $linkColor below to something else and rebuild.
  Or if you don't want to rebuild the theme just override the .line background
  property with some CSS:
  .line {
    background: <new-color>;
  }
*/
````

If those divs can be set anywhere in the body of the document you can use includes features to add them
https://quarto.org/docs/output-formats/html-basics.html#includes

Do they need to be placed somewhere specific in the document ? 

Other ways to modify the HTML in the process: 

* Before by modifying the underlying  Pandoc's template and providing a custom one 
* After by using some JS processing to add or move you specific divs in the right place in your document. You would add those JS script as `include-after-body`

There may be other solutions but those are the first I am thinking about

**Comment by maelle** [comment]
Thank you!!

**Comment by jjallaire** [comment]
@maelle  In case you didn't run across them already here are the docs on creating Reveal themes for use w/ Quarto: https://quarto.org/docs/presentations/revealjs/themes.html

**Comment by jjallaire** [comment]
Note that you can chain an scss file that has the effects you are looking for onto any of the existing themes

**Comment by maelle** [comment]
Thank you, I saw that but that theme also requires some special HTML tweaking :-)

**Comment by jjallaire** [comment]
Ah, got it! (should have read more carefully) Sounds like the include
mechanism did the trick.

**Comment by maelle** [comment]
it did!
