### ISSUE TITLE
For website project, images generated by R code does not display normally in listing page

### ISSUE THREAD

**Issue by psychelzh** [quarto-dev/quarto-cli#2042]
### Bug description

This is a minimal sample project.

[quarto_minimal.zip](https://github.com/quarto-dev/quarto-cli/files/9394347/quarto_minimal.zip)

The post content is simply:

````qmd
---
title: test
---

```{r}
plot(1)
```
````

The rendered site will not display the picture stated in post.

![image](https://user-images.githubusercontent.com/13306020/185921680-8b47fdce-27c0-496e-96de-dc0658b0cb6b.png)

Error message from console is as follows:

```r
#> GET: /
#>  /index_files/figure-html/unnamed-chunk-1-1.png (404: Not Found)
#>  /index_files/figure-html/unnamed-chunk-1-1.png (404: Not Found)
```

<sup>Created on 2022-08-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 (2022-06-23 ucrt)
#>  os       Windows 10 x64 (build 22000)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  Chinese (Simplified)_China.utf8
#>  ctype    Chinese (Simplified)_China.utf8
#>  tz       Asia/Taipei
#>  date     2022-08-22
#>  pandoc   2.18 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.3.0   2022-04-25 [1] CRAN (R 4.2.1)
#>  digest        0.6.29  2021-12-01 [1] CRAN (R 4.2.1)
#>  evaluate      0.16    2022-08-09 [1] CRAN (R 4.2.1)
#>  fansi         1.0.3   2022-03-24 [1] CRAN (R 4.2.1)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.1)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.2.1)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.1)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.2.1)
#>  htmltools     0.5.3   2022-07-18 [1] CRAN (R 4.2.1)
#>  knitr         1.39    2022-04-26 [1] CRAN (R 4.2.1)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.2.1)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.1)
#>  pillar        1.8.1   2022-08-19 [1] CRAN (R 4.2.1)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.1)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.2.1)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.2.1)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.0  2022-06-28 [1] CRAN (R 4.2.1)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.2.1)
#>  rlang         1.0.4   2022-07-12 [1] CRAN (R 4.2.1)
#>  rmarkdown     2.15    2022-08-16 [1] CRAN (R 4.2.1)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.2.1)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.1)
#>  stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.1)
#>  stringr       1.4.1   2022-08-20 [1] CRAN (R 4.2.1)
#>  styler        1.7.0   2022-03-13 [1] CRAN (R 4.2.1)
#>  tibble        3.1.8   2022-07-22 [1] CRAN (R 4.2.1)
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.2.1)
#>  vctrs         0.4.1   2022-04-13 [1] CRAN (R 4.2.1)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.1)
#>  xfun          0.32    2022-08-10 [1] CRAN (R 4.2.1)
#>  yaml          2.3.5   2022-02-21 [1] CRAN (R 4.2.1)
#> 
#>  [1] C:/Users/lenovo/AppData/Local/R/win-library/4.2
#>  [2] C:/Program Files/R/R-4.2.1/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

### `quarto check` Output

```bash
[>] Checking Quarto installation......OK
      Version: 1.0.38
      Path: C:\PROGRA~1\Quarto\bin\
      CodePage: 936

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.5 (Conda)
      Path: C:/Users/lenovo/miniconda3/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

(/) Checking R installation...........
```

### `quarto tools check` Output

```bash
[>] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
@dragonstyle I can repro this as well. Definitely something for v1.1

**Comment by dragonstyle** [comment]
Note there are two considerations here:

1) When we create the listing page, we attempt to discover the `image` for use in the listing. We currently do this by parsing the input markdown, but this allows images that are generated by code to evade detection. Consequently, these images evade detection as the listing image.

2) When we create the listing description, we read the first paragraph of the post page and use that for the description (if none are specified). When we do this, we need to process the elements within the paragraph and properly resolve their paths (we're currently just using the post relative path rather than converting it to a listing page relative path). Alternatively, we should definitely consider just removing the images, as they are likely to be unhelpful or cause unexpected formatting when they appear within descriptions.

**Comment by cderv** [comment]
Just for reference purposes, consideration 1 above has been reported in the community too: https://community.rstudio.com/t/quarto-blog-posts-listing-not-using-first-content-image/144482/7

**Comment by TonyFly3000** [comment]
How can we use ggplot as the listing picture in the main page ? 

One work around solution I can think of is to use ggsave and then display the picture in the post.

**Comment by jjallaire** [comment]
Correct me if I'm wrong @dragonstyle but I think for now you'd need to save a static version of the image and point to that? 

Note that in distill we made a chunk option available to indicate that we wanted the output of the chunk to serve as the preview/listing image: https://rstudio.github.io/distill/blog.html#preview-images. We might consider doing something like that?

**Comment by dragonstyle** [comment]
Yes that is correct - we currently read the preview image from the markdown itself, so generated plots evade our detection. We really should be reading the image from the rendered output and should give the user a way to mark a chunk output as a preview image. This is definitely something that we need to fix and will look at shortly!

**Comment by JoFrhwld** [comment]
Not sure if there's been forward motion on this, but a thought on implementation that could still work within scanning just the markdown.

My own approach has been to specify the image using the path from the rendered documents (e.g. `index_files/figure-html/fig-foo-1.png`), [example here](https://github.com/JoFrhwld/blog/blob/b8fee66f667eb9733e20e4b79bf3acb1fe009746/posts/2023/01/2023-01-22_r-spect/index.qmd#L7). If we could simplify that by just specifying a chunk label, that would be a big step, and could still be done without processing the rendered document. For default behavior, looking for code chunks with a `label: fig-` set could maybe also work.

**Comment by cbrnr** [comment]
I'd love to see this working! In case it is more difficult than originally thought, editing the documentation to state that "the first image in the document" only refers to images included with Markdown syntax and not generated by code cells would be very helpful.

**Comment by dragonstyle** [comment]
This should be fixed in our next pre-release build.
