### ISSUE TITLE
How to change the rendered file path in Quarto books

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#2045]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2043

<div type='discussions-op-text'>

<sup>Originally posted by **maelle** August 22, 2022</sup>
Say I have a chapter file called `abb-blurb.qmd`.

How can I make the corresponding HTML file something else than `abb-blurb.HTML`? Do I need to use a YAML field in the file?</div>

**Comment by jjallaire** [comment]
@dragonstyle See discussion for details. This may be an oversight in our post-processors (not looking at output-file). I think worth a look for v1.1 if its a one-liner.

**Comment by dragonstyle** [comment]
This is now fixed in 1.2 builds.
