### ISSUE TITLE
How to stop CSS styling of a header applying to entire section?

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#2057]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2056

<div type='discussions-op-text'>

<sup>Originally posted by **Hedonical** August 22, 2022</sup>
Hi everyone,

I am trying to make it so only the header of a section is centered and center text as seen in the live editor view:
![Screenshot from 2022-08-22 11-11-08](https://user-images.githubusercontent.com/91704211/185992668-ea435ec6-3cce-40d4-b481-c867d3f87091.png)

But when I render the HTML document, it applys the centering and color to the entire section:
![Screenshot from 2022-08-22 14-24-18](https://user-images.githubusercontent.com/91704211/185992753-fd422d6e-5a8d-4162-947e-9a3ce3b2e9e4.png)

Is there an easy way to make it so the css elements only apply to the header and not all of the text under?
</div>

**Comment by Hedonical** [comment]
Here is a minimum reproducible example. I had to compress it to a zip file as github would not allow me to share a .qmd file.
[example.zip](https://github.com/quarto-dev/quarto-cli/files/9396969/example.zip)

**Comment by cscheid** [comment]
Thanks. You can always just paste the .qmd inside your comment, as suggested [here](https://yihui.org/issue/#bug-reports).

**Comment by cscheid** [comment]
I can reproduce the issue. This seems like a bug, or at least very unintuitive behavior.  The `style` tag is being applied to the `<section>` element instead of the heading, so it applies to all of the content of that subsection. @dragonstyle Is this intended behavior? It doesn't come from pandoc:

## example.qmd

````
---
title: "Minimal Reproducible Error"
format: html
---

# Setup {style="color: #326eb8; text-align: center;"}

------------------------------------------------------------------------

### Python Packages to Install and Version

-   [selenium (4.3.0)](https://anaconda.org/conda-forge/selenium)

    **Selenium** is the central tool of this code. The website does not allow for searching for filings by changing its URL, so we have to navigate the website to reach the parts of the website that store valuable information. Selenium opens a Chrome browser and navigates the HTML elements as if it was a human, interacting with buttons and inserting values into website inputs. If you are using Conda, the traditional paths may not have the latest version of selenium, in which case, you can download the latest version from conda forge using the command:

````

## example.html output (excerpt)

```html
<section id="setup" class="level1" style="color: #326eb8; text-align: center;">
<h1 style="color: #326eb8; text-align: center;">Setup</h1>
<hr>
<section id="python-packages-to-install-and-version" class="level3">
<h3 class="anchored" data-anchor-id="python-packages-to-install-and-version">Python Packages to Install and Version</h3>
<ul>
<li><p><a href="https://anaconda.org/conda-forge/selenium">selenium (4.3.0)</a></p>
<p><strong>Selenium</strong> is the central tool of this code. The website does not allow for searching for filings by changing its URL, so we have to navigate the website to reach the parts of the website that store valuable information. Selenium opens a Chrome browser and navigates the HTML elements as if it was a human, interacting with buttons and inserting values into website inputs. If you are using Conda, the traditional paths may not have the latest version of selenium, in which case, you can download the latest version from conda forge using the command:</p></li>
</ul>
</section>
</section>
```

## pandoc-example.md

```
# Setup {style="color: #326eb8; text-align: center;"}

Hello.

# Another Section.

Hello again.
```

## pandoc-example.html

```
$ pandoc pandoc-example.md --to html
<h1 style="color: #326eb8; text-align: center;" id="setup">Setup</h1>
<p>Hello.</p>
<h1 id="another-section.">Another Section.</h1>
<p>Hello again.</p>
```

**Comment by cscheid** [comment]
@Hedonical In the meantime, a possible workaround is to use CSS directly instead (that's probably better practice anyway, so you don't need to repeat the style on every heading)

## example.qmd

````
---
title: "Minimal Reproducible Error"
format: html
css: example.css
---


# Setup

------------------------------------------------------------------------

### Python Packages to Install and Version

-   [selenium (4.3.0)](https://anaconda.org/conda-forge/selenium)

    **Selenium** is the central tool of this code. The website does not allow for searching for filings by changing its URL, so we have to navigate the website to reach the parts of the website that store valuable information. Selenium opens a Chrome browser and navigates the HTML elements as if it was a human, interacting with buttons and inserting values into website inputs. If you are using Conda, the traditional paths may not have the latest version of selenium, in which case, you can download the latest version from conda forge using the command:

# Another section
````

## example.css

```css
h1 {
 color: #326eb8; 
 text-align: center;
}
```

**Comment by Hedonical** [comment]
Thank you very much!

**Comment by dragonstyle** [comment]
I think this is coming from Pandoc via the `--section-divs` option which we set by default. For example:

```
---
title: Sample
---

## this is a test {style="color: blue;"}

This is some text
```

will result in:

```html
<section id="this-is-a-test" class="level2" style="color: blue;">
<h2 style="color: blue;">this is a test</h2>
<p>This is some text</p>
</section>
```

when rendered with:

`pandoc test.md --from markdown --to html --section-divs `

**Comment by cscheid** [comment]
@Hedonical turns out this _is_ intended behavior from quarto. If you truly need to style your headings like that, then do this:

```
---
title: Sample
section-divs: false
---
```
