### ISSUE TITLE
[revealjs] ojs runtime error: Cannot read properties of null (reading 'clientWidth') from width

### ISSUE THREAD

**Issue by kwangkim** [quarto-dev/quarto-cli#2058]
### Bug description

When I choose `revealjs` as a `format` for a `qmd` document, it does not render `width` variable from `ojs` properly.
````{qmd}
---
format: revealjs
---
## DEMO

```{ojs}
md`${width}`
```
````
![image](https://user-images.githubusercontent.com/10469752/186004708-b1e97dbf-8c70-4f34-8035-35b9c0de83e2.png)

When I render it as `html`, it works well.
![image](https://user-images.githubusercontent.com/10469752/186004760-8875e7bd-91be-424c-bcf8-f6d1a42ad4ff.png)

OS: mac air m1 Venture 13.0 Beta 22A5321d

### Checklist

- [X] upgraded to the [latest nightly quarto version](https://github.com/quarto-dev/quarto-cli/releases)?
- [ ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

**Comment by cscheid** [comment]
Yup, I can reproduce it. @jjallaire I can fix this in a couple of hours in case you're considering sneaking this into 1.1.

**Comment by kwangkim** [comment]
I have one question on your commit [153470a](https://github.com/quarto-dev/quarto-cli/commit/153470a4bf81956119ab5281e8120c2ee34d2d16).

Is there any reason why you chose `div.slides` instead of `div.reveal`?
In my case, 
````
---
format: revealjs
---
```{ojs}
md`${width}`
```
````
always return `1050` regardless of `resize` event.

If I replace  `div.slides` with `div.reveal`, I can see a current `width` properly.

Thank you for your quick fix.

**Comment by cscheid** [comment]
@kwangkim You're right, that would be better. I'll amend.
