### ISSUE TITLE
Quarto hugo: why not index.qmd?

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-cli#207]
In https://quarto.org/docs/output-formats/hugo.html, the resulting md file is named differently from the original qmd file?

**Comment by jjallaire** [comment]
I believe from further reading that in order to get resources files automagically copied we need to be a page bundle (and therefore need to always create `index.md`, see https://gohugo.io/content-management/page-bundles/). So I think the current behavior is correct. LMK if your understanding differs.

**Comment by maelle** [comment]
Yes I agree but in that case in the docs shouldn't index.qmd be recommended so as to not confuse users, even if it gets transformed to the correct filename after rendering? And could one in theory build `_index.md` from `_index.qmd` if one wanted a branch bundle?

**Comment by jjallaire** [comment]
Strong point! I just changed the default to not hard code `index.md`. Update documentation is here: https://quarto.org/docs/output-formats/hugo.html (LMK if this seems clear enough).

Note that I experimented a bit with trying to get multiple `.qmd` files in a directory to publish but it only seemed to publish the `index.md` (whereas the Page Bundles documentation seemed to imply that so long as there is an `index.md` other markdown files will also be published). Let me know if there is something I am missing here as it would be great to support multiple qmd files.

**Comment by maelle** [comment]
The other Markdown files probably need an `_index.md` as well? (underscore at the beginning, it's a "list page")

**Comment by maelle** [comment]
Reg the docs the command in https://quarto.org/docs/output-formats/hugo.html#workflow might be

```
quarto render mysite/content/hello-quarto/index.qmd
```

really a detail :-)

And before that 

> Here’s what the source code hello-quarto.qmd might look like:

Should be

> Here’s what the source code hello-quarto/index.qmd might look like:

**Comment by jjallaire** [comment]
Thanks! Just made those tweaks :-)

**Comment by maelle** [comment]
Thanks, I think this can be closed, at least I have no further comment :grin:
