### ISSUE TITLE
Should PDF export mode transform the title for the filename?

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-cli#208]
At the moment the PDF export names the PDF file `The Exact Same Words As The Title.pdf`.

Should it be transformed to remove space, special characters etc?

(And by the way, the PDF export mode is so useful! :pray: )

**Comment by jjallaire** [comment]
That is unfortunately handled by Chrome so out of our control. If we eventually did something like decktape (https://github.com/astefanutti/decktape) -- i.e. use Chrome dev tools protocol to create the PDF programmatically, then we could control the filename. We will definitely ultimately want to do this so we can create handout / speaker-notes version of the PDF.
