### ISSUE TITLE
Installing extension from Git archive repo does not work

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2081]
This came up in https://github.com/quarto-ext/code-filename/issues/4

Quarto allows to install from a file (https://quarto.org/docs/extensions/distributing.html#archive-files) but expect a specific structure. When downloading from Github source, there is a parent folder to the repo folder. 

We could maybe check for that structure instead of just directly looking for the `_extensions` folder.

See discussion in the issue link

cc @dragonstyle

**Comment by cderv** [comment]
See #2419 for another exemple of this with Gitlab. Example repo to use for reprex: https://gitlab.com/dgkf/quarto-ext-test

**Comment by pat-s** [comment]
Facing the same issue in https://codeberg.org/pat-s/quarto-metropolis. Thanks for addressing! 

FWIW I'd love to see a dynamic version resolution for alternative git hosters which does not require passing a full `.zip` link but only the respective repo link. But this differs across git hosters so probably too much work to maintain for others besides GH.
