### ISSUE TITLE
output-location to column does not work anymore for revealjs

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2093]
### Bug description

Take this example where we have a very wide code chunk

`````markdown
---
title: "Untitled"
format: revealjs
execute: 
 echo: true
---

## Slides 1

```{r}
#| output-location: column

library(ggplot2)
ggplot(airquality, aes(Temp, Ozone)) + geom_point() + geom_smooth(method = "loess")
```
`````

This is what we get with stable quarto 
![image](https://user-images.githubusercontent.com/6791940/186413711-3f269b45-da48-459f-8c44-adf240d7e58c.png)

This is what we get with pre-release

![image](https://user-images.githubusercontent.com/6791940/186413399-f17f574a-7668-49a9-90d0-16b782be1b1b.png)

The second column is outside the slide
![image](https://user-images.githubusercontent.com/6791940/186413522-c76a638d-0441-4259-bf5a-e25f3b7051bc.png)

Possibly related to this change: https://github.com/quarto-dev/quarto-cli/commit/a43090353c454860dca50164f06896dec5a48968 to try fixing https://github.com/quarto-dev/quarto-cli/issues/1940 as `flex` is replacing `width`

![image](https://user-images.githubusercontent.com/6791940/186413851-d41ded98-4296-4dda-9c25-d854aff5bc58.png)

This came up from a discussion in https://github.com/quarto-dev/quarto-cli/discussions/2088#discussioncomment-3464422

**Comment by jjallaire** [comment]
Resolved with update to Pandoc v2.19.2: https://github.com/quarto-dev/quarto-cli/commit/84e611513381537f47bde8ded7e501284377707a
