### ISSUE TITLE
close yaml schemas that can be closed

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#2096]
I've seen many users put document level YAML options in the `project` and `website` keys. This does not get reported as an error b/c those schemas aren't closed. I think we need to close up schemas that can be right away as the longer we wait the more projects/documents will be broken when we do (or at the limit we can never close them).

**Comment by cscheid** [comment]
I agree.

If we accept that we'll change schemas over time, though, I think we should consider deprecation warnings as well.

The idea is to have schemas that "soft fail" and issue deprecation warnings, and schemas that "hard fail". That would be non-zero work for v1.2, but I think it will give us a path for improving things over time.

**Comment by cscheid** [comment]
@jjallaire there's a snag here; doing this for projects will either require changing the schemas more than I expected, or require changing the validator code.

The workaround is to not use `base` or `resolveRef`, which will lead to some schema duplicating. We should prob discuss a bit.
