### ISSUE TITLE
Rendering a basic Rmd on Windows throws lua filter errors

### ISSUE THREAD

**Issue by andrie** [quarto-dev/quarto-cli#21]
I'm rendering a very basic Rmd that knits just fine:

**test2.Rmd**
```
    ---
    title: "Building R from source"
    author: "Andrie de Vries"
    date: "6 July 2018"
    output: 
      html_document: 
        self_contained: no
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    ```
    
    Some text
```

I then run ` quarto render .\test2.Rmd`  but I get this error:

```
Error running filter C:/Program Files/Quarto/share/filters/quarto-pre/quarto-pre.lua:
...ram Files/Quarto/share/filters/quarto-pre/quarto-pre.lua:1343: attempt to index a nil value (local 'f')
stack traceback:
        ...ram Files/Quarto/share/filters/quarto-pre/quarto-pre.lua:1343: in function 'readIncludeFiles'
        ...ram Files/Quarto/share/filters/quarto-pre/quarto-pre.lua:1307: in function <...ram Files/Quarto/share/filters/quarto-pre/quarto-pre.lua:1299>
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at runPandoc (file:///C:/Program%20Files/Quarto/bin/quarto.js:19872:36)
    at async renderPandoc (file:///C:/Program%20Files/Quarto/bin/quarto.js:20008:27)
    at async renderFiles (file:///C:/Program%20Files/Quarto/bin/quarto.js:17379:34)
    at async render (file:///C:/Program%20Files/Quarto/bin/quarto.js:17788:22)
    at async Command.fn (file:///C:/Program%20Files/Quarto/bin/quarto.js:20208:29)
    at async Command.execute (file:///C:/Program%20Files/Quarto/bin/quarto.js:1812:17)
    at async Command.parse (file:///C:/Program%20Files/Quarto/bin/quarto.js:1765:20)
    at async Command.parse (file:///C:/Program%20Files/Quarto/bin/quarto.js:1727:20)
    at async quarto1 (file:///C:/Program%20Files/Quarto/bin/quarto.js:24974:5)
```


My environment:

```
PS C:\Users\apdev\Documents\github\experiments\zendesk_articles> quarto help

  Usage:   quarto
  Version: vv0.1.117
```

**Comment by dragonstyle** [comment]
Hi @andrie thanks for reporting this- we had a path issue with spaces which you ran into on Windows! Should be fixed in the latest release:

https://github.com/quarto-dev/quarto-cli/releases/tag/v0.1.119

Thanks for letting us know!

**Comment by kovinay** [comment]
**Run the project then this type create error ,,,_**

**give some solution**

Error running filter C:/Users/VINAYK~1/AppData/Local/Programs/Quarto/share/filters/main.lua:
Cannot get Attr from TypeNil
stack traceback:
	...vinay\_extensions\quarto-ext\fontawesome\fontawesome.lua:42: in function <...vinay\_extensions\quarto-ext\fontawesome\fontawesome.lua:39>
	(...tail calls...)
	[string "..."]:1789: in function <[string "..."]:1787>
	(...tail calls...)
	...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:14383: in function 'transformShortcodeInlines'
	[C]: in ?
	[C]: in method 'walk'
	...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:449: in local 'callback'
	...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
	...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:495: in function <...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:476>
stack traceback:
	...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:449: in local 'callback'
	...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
	...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:495: in function <...K~1/AppData/Local/Programs/Quarto/share/filters/main.lua:476>_

**Comment by cderv** [comment]
@kovinay this issue was closed 3 years ago already. Lots of version since then. It would be best to open a new issue and follow our issue guide you have when opening a new issue. 

Please do follow the guidelines, especially on formatting (I reformatted your post above for readibility): https://quarto.org/bug-reports.html

Thank you
