### ISSUE TITLE
Multiplex scripts cannot be found

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-cli#210]
- When using self-contained: false I get

```
DevTools failed to load SourceMap: Could not load content for file:///home/maelle/Documents/blablabla/presentation_files/libs/revealjs/plugin/multiplex/socket.io.js.map: System error: net::ERR_FILE_NOT_FOUND
```

- When setting it to true I get

```
DevTools failed to load SourceMap: Could not load content for file:///home/maelle/Documents/blablabla/reveal.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///home/maelle/Documents/blablabla/socket.io.js.map: System error: net::ERR_FILE_NOT_FOUND
```

(from the non speaker file)

**Comment by maelle** [comment]
Maybe the issue is that these are local files.

**Comment by maelle** [comment]
I get an error when putting that file online too.

**Comment by maelle** [comment]
Adding that this error was on Chrome

**Comment by maelle** [comment]
In Firefox, I do not think the multiplex works but I see no error in the console. That might indicate some user mistake. :sweat_smile:

**Comment by jjallaire** [comment]
Those errors are I believe fine (they are just attempts to load source maps that aren't deployed). Firefox is simply choosing not to show a warning for that case. If you send me a screenshot of what you are seeing in devtools I can say for sure.

**Comment by maelle** [comment]
I see

![image](https://user-images.githubusercontent.com/8360597/145457511-0881f45c-efc6-4df4-8885-d203c7b3f0f7.png)

**Comment by maelle** [comment]
Now I still wonder why I can't get multiplex to work (on a minimal presentation, the one gotten via "New File" -- the presentation.html opened on another device doesn't get synchronized with presentation-speaker.html) and will have to investigate another time.

**Comment by maelle** [comment]
(the error is for /favicon.io)

**Comment by maelle** [comment]
https://github.com/reveal/multiplex/issues/12 :eyes:

**Comment by maelle** [comment]
I suppose that if I really wanted to use this I'd need to start my own server. (I was just trying things out, nothing crucial for me :-) )

**Comment by jjallaire** [comment]
You shouldn't need to run your own server....I'll investigate further later on tonight!

**Comment by jjallaire** [comment]
Closing as we've (hopefully) addressed this issue here: https://github.com/quarto-dev/quarto-cli/issues/209
