### ISSUE TITLE
Footnote-style citation in figure caption crashed PDF render

### ISSUE THREAD

**Issue by Benjamin-Lee** [quarto-dev/quarto-cli#2112]
### Bug description

This bug is essentially #1141 but applied to citations in captions when using footnote citation styles. This Markdown doesn't work:

```md
---
csl: oxford-university-press-note.csl
---
![A schematic diagram of known types of viroid-like agents. This figure was published in [@Lee2021a].](figures/viroid-like-schematic.png)
```

The error message also parallels #1141:

```
compilation failed- error
Argument of \caption@ydblarg has an extra }.
<inserted text>
                \par
l.324 ...1093/nar/gkab974}{10.1093/nar/gkab974}.}}
```

### Checklist

- [X] upgraded to the [latest nightly quarto version](https://github.com/quarto-dev/quarto-cli/releases)?
- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

**Comment by dragonstyle** [comment]
Thanks for reporting this - it should be fixed here (https://github.com/quarto-dev/quarto-cli/commit/e250126e08421ebbc70d3f5e40d2f7e8c04426f3), available in the latest pre-release build (1.2.170).
