### ISSUE TITLE
Adapt the documentation about .md document with computation chunk

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2122]
### Bug description

Currently in the doc for engine binding regarding computation chunk (https://quarto.org/docs/computations/execution-options.html#engine-binding) we have mention of two things regarding Markdown file : 

* The table about auto-binding shows `.md` is supported, and no engine will be used 
![image](https://user-images.githubusercontent.com/6791940/186656973-e298287c-2c38-482e-806b-5c14fdbbd647.png)

* `engine: markdown` can be used to deactivate engine
   > You can also specify that no execution engine should be used via engine: markdown.

However, we have a check for computation chunk inside `.md` document that prevent any rendering at all 
https://github.com/quarto-dev/quarto-cli/blob/71310bfd92ce7240042dd29f96a6f305690feb23/src/execute/markdown.ts#L67-L75

Which leads to 
````
> quarto render test.md --to html
ERROR: You must use the .qmd extension for documents with executable code.
````

As discussed with @jjallaire 
> That error is I think more helpful than not because if you have code cells in your .md you definitely aren't getting what you expected (the code won't execute). We could indeed silently send this to pandoc but I sort of view that as similar to eating bad YAML schema. Longer term its better for the user to clean this up.

Should we maybe update the documentation to clearly state that `.md` document works with quarto only if there is no computation chunk ? Or at least remove the `.md` line from the table ?

**Comment by jjallaire** [comment]
update the docs here: https://github.com/quarto-dev/quarto-web/commit/cc1333c3e3ebd7e1ad5bb1057917a4d787fdd9a8
