### ISSUE TITLE
Quarto now disallows lists for bibliography field.

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#213]
In version v0.2.306, and earlier, it was legal, and effective, to give a list for the `bibliography` entry in `_quarto.yml`, e.g.:

```
bibliography: [refs1.bib, refs2.bib]
```

In current main, which is v0.2.346, I get this error on `quarto render`:

```
ERROR: Project _quarto.yml validation failed.
(line 12, columns 15--37): Field /bibliography must be a string
11: 
12: bibliography: [refs1.bib, refs2.bib]
                  ^^^^^^^^^^^^^^^^^^^^^^
13: 
ERROR: Error: Project _quarto.yml validation failed.
```

See: https://github.com/matthew-brett/mysite

I do find it useful to use more than one bibliography in that entry, and it is allowed in standard Pandoc.  Could the validation be relaxed or modified to allow this?

**Comment by dragonstyle** [comment]
This is just an oversight and overly strict validation - we will correct this to continue the previous behavior.

**Comment by jjallaire** [comment]
Thx for reporting, YAML validation is a work in progress and that schema wasn't correct. I've disabled the validation for now (https://github.com/quarto-dev/quarto-cli/commit/a0c531268ed4a97db13df83812425440c64cb3ea). It will come back along with a more comprehensive and hopefully 100% schema next week. This commit is in the update v0.2.347 release.

**Comment by matthew-brett** [comment]
Thanks for the quick fix.
