### ISSUE TITLE
code-fold still exist even if `echo` is set as false

### ISSUE THREAD

**Issue by y9c** [quarto-dev/quarto-cli#2134]
### Bug description

test code

````md
---
title: 'debug code fold'
format:
  html:
    code-fold: true
    embed-resources: true
    standalone: true
execute:
  cache: false
  echo: false
---

```{ojs}
1+1
```
````

output:

![image](https://user-images.githubusercontent.com/5415510/186770778-d1a1f1b3-6f8a-45f1-9c4c-5bf27c3ced5c.png)

This bug is caused by `code-fold: true` in the header. When remove this line, the rendering is ok. But it would better to check if echo == Ture before display the code fold  mark.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
This is now completed on `main`.
