### ISSUE TITLE
new ipynb file not appearing until a new .qmd file is created

### ISSUE THREAD

**Issue by Eclecticdata** [quarto-dev/quarto-cli#2135]
### Bug description

Using MS code, Anaconda with python 3.9.12, when selecting 'file new' if I select a .ipynb file it does nothing, however if I create a .qmb file, and then create a .ipynb it then appears. The MS code extensions I have installed are:

ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-python.vscode-pylance
ms-python.python
quarto.quarto
REditorSupport.r
RDebugger.r-debugger

This occurs on more than one machine, windows 10 professional:

Edition	Windows 10 Pro
Version	20H2
Installed on	‎03/‎08/‎2022
OS build	19042.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I'm not sure I understand how quarto relates to this bug report.

> Using MS code, Anaconda with python 3.9.12, when selecting 'file new' if I select a .ipynb file it does nothing

Who's "it" in this previous sentence?

> however if I create a .qmb file, and then create a .ipynb it then appears

and who's "it" in this other sentence?

**Comment by allenmanning** [comment]
We are going to close for now. If a reproducible case can be found, please post it to the issue and we will re-open and review. Thank you.
