### ISSUE TITLE
[Feature request] Include matplotlib figures as pgf code

### ISSUE THREAD

**Issue by benabel** [quarto-dev/quarto-cli#214]
Currently, the matplotlib figures are included as `pdf` files in latex, but matplotlib allows to export graphs as `pgf` code with the [`backend_pgf`](https://matplotlib.org/stable/api/backend_pgf_api.html).

Using this backend would allow to integrate matplotlib figures using the documents fonts as described in this [blog post](https://jwalton.info/Matplotlib-latex-PGF/). However getting the available `\textwidth` from latex could be tricky.

**Comment by jjallaire** [comment]
I think the best way to make this work is probably to have the cell emit raw LaTeX using `IPython.display.LaTeX` (https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.Latex). That way you can handle both creating the `pgf` code and whatever calculations are required to get the right sizing all within Python.

**Comment by jjallaire** [comment]
Possibly of related interest, we have some direct support for this now. If a markdown image is generated that has a `.tex` file extension then we automatically inline it:

https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/filters/quarto-pre/figures.lua#L110-L136

This was put in for compatibility with the tkiz R graphics device employed by some kntir users.

So if you just emitted a raw markdown image (again using `IPython.display.Markdown`) that had the `pgf` inside a tex file that in turn was the src of an image then things might work as expected.

**Comment by jjallaire** [comment]
Currently the image is sized by looking for `resize.width` and `resize.height` attributes on the image. That is just for compatibility w/ what knitr does, we could certainly work out a more generic / appropriate scheme for the jupyter case.

**Comment by benabel** [comment]
Thanks for your quick and detailed answer. I have testes three approaches. I note it here _for reference_, and close the issue.

## emit raw LaTeX using `IPython.display.LaTeX `

Nice, but I should set my figure size manually because I haven't find a way to pass `\textwidth` to python.

```python
import matplotlib as mpl

# Use the pgf backend (must be set before pyplot imported)
mpl.use("pgf")

import matplotlib.pyplot as plt

# But with fonts from the document body
plt.rcParams.update({
    "font.family": "serif",  # use serif/main font for text elements
    "text.usetex": True,     # use inline math for ticks
    "pgf.rcfonts": False     # don't setup fonts from rc parameters
    })


from scipy.stats import norm

x = norm.rvs(size=100)
y = norm.pdf(x)

plt.scatter(x, y, marker="x")
# Set background color of the outer 
# area of the plt

fig, ax = plt.subplots(1, 1)
ax.scatter(x, y)
fig.set_facecolor('#77777777')
ax.set_ylabel('density')
ax.set_xlabel('$x$')

import io

buf = io.BytesIO()
fig.savefig(buf, format="pgf")
bytestring = buf.getvalue()
pgf = bytestring.decode()

from IPython.display import Latex
Latex(pgf)
```

### Include it from python with `resizebox`

Currently the best approach I've found.

```{python}
plt.savefig('norm.tex', format="pgf")
Latex(r"\resizebox{\textwidth}{!}{\input{norm.tex}}")
```

![image](https://user-images.githubusercontent.com/12530561/145720631-69389afe-90f3-48c1-962f-4f2de3826c2d.png)

### Include it from markdown

Using `resize.width` attribute works, but something like `width=100%` could be more generic. **Maybe this should be considered in another issue**.

```md
![Test image](norm.tex){resize.width=\textwidth}
```

**Comment by jjallaire** [comment]
I wonder if we should just consider supporting the default `width` and `height` attributes for `tex` images (along with `resize.width` and `resize.height` for backwards compatibility w/ knitr). Further, we could make the default `\textwidth` if no width is specified -- does that make sense to you?

**Comment by benabel** [comment]
It would be nice to support defaults width and height attributes allowing also percents values based on `\textwidth`.

Make the default width to \textwidth if no width is specified could be used as I think it is the most common usage.

**Comment by benabel** [comment]
I think it would be better to use `\textwidth` vs `\linewidth` like pandoc https://github.com/jgm/pandoc/blob/921af3085422ed5896db6996c54009cf2a61a517/src/Text/Pandoc/Writers/LaTeX.hs#L938.

**Comment by jjallaire** [comment]
I've seen knitr use `\linewidth` in preference to `\textwidth` -- I think the idea is that `\linewidth` will behave correctly e.g. inside a multi-column layout or a list environment. @yihui Is there a reason to prefer one or the other here? (this is for inclusion of `pgf` graphics in a LaTeX document)

**Comment by benabel** [comment]
I prefer text width for example when you include figures inside tabulated blocks like lists. When using `\linewidth`, the figure will go out in the right margin, with `\textwidth` figure is perfectly aligned with text(assuming width=100%).

**Comment by jjallaire** [comment]
Okay, let's see what @yihui has to say. This is ultimately user customizable by using a literal latex string (e.g. `width="0.8\textwidth"`)

**Comment by yihui** [comment]
I don't remember why I used `\linewidth` in **knitr** now. I vaguely remember that in the very beginning (around 2012?) I was using `\textwidth` but switched to `\linewidth` later. I just read https://tex.stackexchange.com/questions/16942/ again and I feel that `\linewidth` is still preferred, and the following statement seems to contradict the StackExchange answers:

> When using `\linewidth`, the figure will go out in the right margin, with `\textwidth` figure is perfectly aligned with text(assuming width=100%).

That is, `\linewidth` should respect the current width inside lists, but `\textwidth` does not.

**Comment by jjallaire** [comment]
Okay, thanks @yihui! @benabel I am going to stay with `\linewidth` for now as-per that thread. If we later discover that `\textwidth` is preferred we will definitely revisit.
