### ISSUE TITLE
Help with error? property name reader-mode is invalid

### ISSUE THREAD

**Issue by kmkinnaird** [quarto-dev/quarto-cli#2153]
I just updated my quarto (to 1.1.140) and got the following error: 

`ERROR: Project _quarto.yml validation failed.`

`In file www/_quarto.yml`
`(line 10, columns 3--14) property name reader-mode is invalid`
` 9: website:`
`10:   reader-mode: true`

I see that reader-mode is still in the documentation. Any advice would be greatly appreciated.

**Comment by dragonstyle** [comment]
I believe that the issue is that `reader-mode` is missing from our website schema.

**Comment by kmkinnaird** [comment]
Whoops, yes the repo is private. Apologies. 

Thanks for looking into this!

**Comment by dleen** [comment]
Thanks for the quick fix @dragonstyle ! What's the best way to consume this before the next release?

**Comment by dragonstyle** [comment]
Sorry was just finishing up a couple related release chores, but you found the correct release. This fix is present starting in 1.1.141, in case others are looking for it.
