### ISSUE TITLE
failed yaml validation on "pre-render"

### ISSUE THREAD

**Issue by juliantao** [quarto-dev/quarto-cli#2155]
### Bug description

After pulling the commits today, I receive the following error on validation of the pre-render field in the project yaml file `_quarto.yml`:

```bash
ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 4, columns 3--13) property name pre-render is invalid
3:   output-dir: docs
4:   pre-render:
     ~~~~~~~~~~
5:     - ./scripts/todo-pre.py
ℹ The error happened in location project:pre-render.


Error: Project _quarto.yml validation failed.

In file _quarto.yml
(line 4, columns 3--13) property name pre-render is invalid
3:   output-dir: docs
4:   pre-render:
     ~~~~~~~~~~
5:     - ./scripts/todo-pre.py
ℹ The error happened in location project:pre-render.

    at readAndValidateYamlFromFile (file:///home/julian/quarto-cli/src/core/schema/val
idated-yaml.ts:52:11)
    at async projectContext (file:///home/julian/quarto-cli/src/project/project-contex
t.ts:123:28)
    at async Command.fn (file:///home/julian/quarto-cli/src/command/preview/cmd.ts:230
:23)
    at async Command.execute (file:///home/julian/quarto-cli/src/vendor/deno.land/x/cl
iffy@v0.24.2/command/command.ts:1275:7)
    at async quarto (file:///home/julian/quarto-cli/src/quarto.ts:104:3)
    at async file:///home/julian/quarto-cli/src/quarto.ts:124:5
```

I am on Linux Ubuntu 22.04

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Definitely a bug from our recent schema tightening. Fix incoming. Thank you!

**Comment by cscheid** [comment]
New release being build, ETA 10 mins or so. Thanks for the patience!

**Comment by juliantao** [comment]
I can confirm that it works as expected after the fix. Thank you!

**Comment by zeileis** [comment]
I just updated from quarto 1.0.x to 1.1.251 (on Debian GNU/Linux) and get a similar problem with my `_quarto.yml` which previously worked just fine:

```
quarto render --to=html
ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 66, columns 3--12) property name sec-title is invalid
65:   tbl-prefix: Tabelle
66:   sec-title: Kapitel
      ~~~~~~~~~
67:   sec-prefix: Kapitel
ℹ The error happened in location crossref:sec-title.
```

Is this a related problem or am I doing something wrong?

**Comment by zeileis** [comment]
OK, good, thanks. Then probably the `sec-prefix` already did the job and I didn't need `sec-title` in addition. For some of the other keys (maybe `fig-` or `thm-` or so) I thought I needed both `-title` and `-prefix`.

In any case, the good thing was that I now properly understood how the `lang`/`language` settings work and I can leverage these plus a few customizations.

Sorry for the noise and thanks for the support (and the wonderful software).
