### ISSUE TITLE
allow theming & styling Mermaid diagrams

### ISSUE THREAD

**Issue by das-g** [quarto-dev/quarto-cli#2165]
Mermaid allows theming / styling diagrams with
- ready-made built-in themes
- user-provided CSS
- combination of both above

If this can already be used through Quarto, please document how. (I didn't find anything about it in the documentation.)

If not, please consider adding a possibility to do so. (Best probably as YAML options as suggested at https://github.com/quarto-dev/quarto-cli/discussions/1521#discussioncomment-3225243, as that would allow project-wide, file-level and diagram-level control.)

**Comment by das-g** [comment]
Thanks to https://github.com/quarto-dev/quarto-cli/discussions/1521#discussion-4243981 I noticed, that this is already possible on a per-diagram basis by including a special (to Mermaid, not to Quarto) comment like this:

````markdown
```{mermaid}
%%|label: fig-generalization
%%|fig-cap: generalization of classes without shown attributes or methods

%%{init: {
  "theme": "forest",
  "themeCSS": ".extension { fill: #1c1e1f !important; }; .divider { display: none; };"
}}%%

classDiagram
    Vehicle <|-- Car
```
````

However, especially for more involved CSS, this gets rather clumsy, so I'm not sure whether this should be documented until proper YAML options for this exist.

**Comment by kmasiello** [comment]
For reference, here is the mkdocs implementation of mermaid. They have a default theme that is not horrid. https://squidfunk.github.io/mkdocs-material/reference/diagrams/

**Comment by cscheid** [comment]
Lots of testing to be done, but sneak peak of mermaid diagrams automatically themed against quarto's bootswatch themes:

## Sandstone
<img width="735" alt="image" src="https://user-images.githubusercontent.com/285675/202828322-77a5ba0e-cf72-4ed1-9083-6ab6f9933a01.png">

## Cerulean
<img width="733" alt="image" src="https://user-images.githubusercontent.com/285675/202828398-9dbfb81e-489e-4bee-99c4-b2766fd13d67.png">

## Solar
<img width="717" alt="image" src="https://user-images.githubusercontent.com/285675/202828430-968da9cb-d5a6-4e5e-b2f4-86ec70b8bfe6.png">
