### ISSUE TITLE
Heading in theorem is included as item in list in theorem body

### ISSUE THREAD

**Issue by vmichals** [quarto-dev/quarto-cli#2166]
I was sketching a theorem using a bullet point list inside a div and stumbled upon the following issue.

The following minimal example using (un-)ordered lists inside a theorem div

```markdown
---
title: "unexpected caption item"
---

::: {#thm-unordered-list}
## This heading shouldn't have a bullet point

* This 
* unordered list (unexpectedly) includes the caption
:::


::: {#thm-ordered-list}
## This heading shouldn't have a bullet point

1. This 
2. ordered list (unexpectedly) includes the caption
:::
```
renders the  theorem caption as part of the list:
![unexpected_caption_item](https://user-images.githubusercontent.com/1757177/187035748-f024d444-d095-4b39-8627-c5dd787b311d.png)

**Comment by capnrefsmmat** [comment]
I've run into the same issue. Notably, it appears to happen in HTML output but not PDF, so it must be happening later in the conversion process.
