### ISSUE TITLE
book chapters can't be rendered as separate revealjs presentations

### ISSUE THREAD

**Issue by dhicks** [quarto-dev/quarto-cli#2200]
I started this discussion a few months ago.  I have a `book` project with a collection of chapters, which I'd like to render as separate `revealjs` presentations.  Every way I've tried to do this either renders to the `html` format or returns the error `WARNING: The revealjs format is not supported by book projects`.  But this exact workflow will work with `website` projects, as indicated by [this tweet](https://twitter.com/KellyBodwin/status/1552649491815227392), which I believe includes a slide from @mine-cetinkaya-rundel 's presentation at rstudio::conf(2022).  So it seems to me like this is a bug. 

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1433

<div type='discussions-op-text'>

<sup>Originally posted by **dhicks** July 16, 2022</sup>
I'm a university professor.  For one of my classes, I like to present my lecture notes as both a presentation (eg, slidy or revealjs, for use in class) and a unified website (eg, gitbook, for students to consult out of class).  With Rmarkdown, I could do this by having two different recipes in a Makefile:  one that uses `bookdown::render_book()` to create the single gitbook, and another that uses `rmarkdown::render()` to create a presentation for each separate chapter `Rmd` file.  

I'm playing around with Quarto, trying to figure out how I might be able to do this.  Something like `quarto render chfile --to revealjs` in a book project generates a warning: `WARNING: The revealjs format is not supported by book projects`.  (This should probably be an error, because Quarto doesn't go on to executive any code chunks or produce any output files.)  Including `revealjs` as a `format` in `_quarto.yml` does the same thing. I tried setting up a separate metadata file, `_slides.yml`, but `quarto render` doesn't seem to have any flags to select which metadata file should be used.  

So currently the best option seems to be to stick with `rmarkdown::render()` for the slides? </div>

**Comment by mcanouil** [comment]
Did my answer not worked or gave the expected results?

https://github.com/quarto-dev/quarto-cli/discussions/1433#discussioncomment-3220454

**Comment by dhicks** [comment]
Your answer involves renaming the various yml files.  That seems more like a workaround than a bug fix to me? 

This MWE works with a `website` project works as expected: 
```
quarto create-project testproj --type website
cd testproj
## render as a website
quarto render
## render about.qmd as a reveal.js presentation
quarto render about.qmd --to revealjs --output-dir slides
```

**Comment by dragonstyle** [comment]
I believe that the newly introduced [Profiles](https://quarto.org/docs/projects/profiles.html) capability should address this and make this possible. You can try this out in the latest pre-release here:

https://quarto.org/docs/download/prerelease.html
