### ISSUE TITLE
problem with creation of quarto book in RStudio IDE

### ISSUE THREAD

**Issue by linlennypinawa** [quarto-dev/quarto-cli#2208]
I followed the following wizard in RStudio:
1) `New Project`
2) `New Directory`
3) `Quarto book`
4) typed in the directory name
Create project as subdirectory of: [on a local drive] D:/directoryname
5) select "use renv with this project"
6) click `Create Project`

I got this: 
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by linlennypinawa** [comment]
The problem was solved by just reinstalling RStudio.

I uninstalled the RStudio
Reinstalled it to a space-less directory.

Then I created a new project of quarto book. ....

**Comment by linlennypinawa** [comment]
I prefer to put RStudio under the `Program Files`.  So please notify me when the bug is fixed.

**Comment by linlennypinawa** [comment]
> You could update to latest Quarto here: https://quarto.org/docs/get-started/ and see if that change something.

yes, I updated to the latest Quarto.

**Comment by linlennypinawa** [comment]
> are you using the RStudio IDE bundled one ?

I am not aware of it.

**Comment by cderv** [comment]
Ok so to sum up: 

> I uninstalled the RStudio
> Reinstalled it to a space-less directory.

Installing same RStudio version to a space-less directory fixed the issue, correct ? 
Can you confirm this, this is an important information that could help IDE team. Thanks

> I prefer to put RStudio under the Program Files. So please notify me when the bug is fixed.

It was just to test the daily version to see if things where fixed in there. You would then remove the unzipped folder after the test.

> yes, I updated to the latest Quarto.

Then, you are not using the bundled one. Latest quarto is good, and should be installed in Program Files like RStudio I believe

**Comment by linlennypinawa** [comment]
>Installing same RStudio version to a space-less directory fixed the issue, correct ?
>Can you confirm this, this is an important information that could help IDE team. Thanks

Correct.  I created a `RStudio` directory, and install the same version of `RStudio IDE` under it.

> Latest quarto is good, and should be installed in Program Files like RStudio I believe.

Sorry, I did not pay attention to the directory where quarto was placed while I updated it.  I believe it would be the default.

**Comment by cderv** [comment]
@linlennypinawa thanks a lot ! 

I have shared your insight in the RStudio IDE issue too, and hopefully this will be solved quickly

**Comment by jjallaire** [comment]
This needs to be addressed by RStudio calling quarto.exe rather than quarto.cmd (cc @jgutman and @ronblum)
