### ISSUE TITLE
Font import through SCSS file

### ISSUE THREAD

**Issue by rgouveiamendes** [quarto-dev/quarto-cli#2219]
### Bug description

Hello

I was trying to change the font of a Reveal presentation following the themes in GitHub.
I was doing it by adding:  
```scss
/*-- scss:defaults --*/

@import url(http://fonts.googleapis.com/css?family=Montserrat:300,300italic,800,800italic);
```
 to my SCSS file.
Unfortunately, when Quarto renders the presentation it creates a `Quarto.css` file in `./rppresentation_files/libs/revealjs/dist/theme` with all the CSS rules adding another importing rule after mine, like this:
```css
@import"http://fonts.googleapis.com/css?family=Montserrat:300,300i,800,800i";@import"./fonts/source-sans-pro/source-sans-pro.css";:root{ ...
```
This overrules my Montserrat font.

I am running Linux Mint 21, with Quarto 1.1.163 and RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Ubuntu Jammy

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mcanouil** [comment]
You only imported the font, you did not set the font so it is imported but not used.

See for example: https://github.com/mcanouil/quarto-revealjs-coeos/blob/main/_extensions/coeos/coeos.scss#L3-L9

**Comment by rgouveiamendes** [comment]
Dear @mcanouil thank you for the reply.
In fact, I have used it. My entire SCSS file looks like this:
```scss
/*-- scss:defaults --*/

@import url(http://fonts.googleapis.com/css?family=Montserrat:300,300italic,800,800italic);


$main-color: #1e40af;
$light-color: #dbeafe;
$font-family-sans-serif: "Montserrat", "Source Sans Pro", Helvetica, sans-serif;
$presentation-font-size-root: 36px;
$presentation-font-smaller: 0.7;
$presentation-line-height: 1.4;
$link-color: $main-color;
$presentation-heading-color: $main-color;
$presentation-heading-line-height: 1.2;
$presentation-heading-font-weight: 800;
$presentation-h1-font-size: 2.5em;
$presentation-h2-font-size: 1.6em;
$presentation-h3-font-size: 1.3em;
$presentation-h4-font-size: 1em;
$presentation-block-margin: 12px;
$presentation-slide-text-align: left;
$presentation-title-slide-text-align: center;
$light-bg-link-color: $main-color;
$dark-bg-link-color: $main-color;
```

**Comment by mcanouil** [comment]
Do you have a fully (and small) reproducible example then?

**Comment by rgouveiamendes** [comment]
@mcanouil I am sorry for the late reply. Here it goes:

The minimal scss file:
```scss
/*-- scss:defaults --*/

@import url("http://fonts.googleapis.com/css?family=Roboto:300,300italic,900,900italic");
$font-family-sans-serif: "Roboto", "Source Sans Pro", Helvetica, sans-serif;

/*-- scss:rules --*/
```

The minimal `.qmd` file:
```markdown
---
title: "My title"
subtitle: "My subtitle"
author: "My name"
date: "September 2022"
format:
    revealjs:
        slide-number: true
        preview-links: auto
        width: 1600
        height: 900
        theme: minimal.scss
---

## Hello world

This font is not Roboto but Source Sans Pro.

```

Locally, everything works fine. But when I publish the slides in my website, the font no longer works (see for example: https://rgouveiamendes.org/teaching/clsbe/econhist/slides/class01/).

Thank you!

**Comment by rgouveiamendes** [comment]
Solved! The problem was as stupid as omitting the 's' from 'https' on the address to import the font...
Checking the log of the browser I realized it immediately.
Thank you for the time you all looked at this issue!
