### ISSUE TITLE
Add possibility to change the table, figure captions (docx)

### ISSUE THREAD

**Issue by olivroy** [quarto-dev/quarto-cli#2221]
It is probably a pandoc issue.

but would it be possible that the 
```yaml
tbl-cap-location: top
fig-cap-location: top
```
work for docx output?

For the moment, they don't have any effect.

**Comment by iandol** [comment]
This is a limitation of the DOCX format I suspect, there isn't a way to move captions around relative to the figure AFAIK. I suppose a filter could move the captions in the source AST before the DOCX writer was run?

**Comment by cscheid** [comment]
We are doing a significant overhaul of figure handling for 1.2, and it's possible that a fix for this will fall out naturally. With that said, DOCX output has some limitations that we can't work around, so I'm not confident we can fix this in general.

**Comment by mcanouil** [comment]
FYI #3467
