### ISSUE TITLE
Property name prefs-text is invalid

### ISSUE THREAD

**Issue by bryanhanson** [quarto-dev/quarto-cli#2224]
### Bug description

A previously working document just failed after upgrading via `git pull` and `./configure.sh`.  Then I used the installer, and it has the same error (v 1.1.165). This was working 2 days ago.  When I do `quarto preview` the error I see is:

```
~/.../R_Pkgs/CSR(master ✗)> quarto preview
ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 9, columns 3--13) property name prefs-text is invalid
 8:   cookie-consent: true
 9:   prefs-text: "Cookies are used to track visits only"
      ~~~~~~~~~~
10:   body-footer: <script data-goatcounter="https://chemospec.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
ℹ The error happened in location website:prefs-text.
```
This is on MacOS 12.5.1. `quarto check` responds OK at each point.  The full repo should you need it is [here](https://github.com/bryanhanson/CSR).

**Comment by cscheid** [comment]
That's a result of us closing down that schema. Turns out you had a bug in your yaml all along, and we weren't reporting it to you :)

```yaml
cookie-consent: true
prefs-text: "Cookies are used to track visits only"
```

This is an invalid file - `cookie-consent` is either a boolean, or an object with options. Either of these:

```yaml
cookie-consent: true

cookie-consent:
  prefs-text: "Cookies are used to track visits only"
```
