### ISSUE TITLE
unexpected behavior with callout using `#xxx-` label as header

### ISSUE THREAD

**Issue by HelenaLC** [quarto-dev/quarto-cli#2239]
In order to obtain numbered callouts (e.g., for cross-referenceable exercises and solutions), I have attempted to

- set callout captions to be empty via `callout-x-caption: ""`
- use `#exr-` (or similar) to get numbered captions instead

with the following unexpected outcome:

1. The printed name (here, "Exercise") is printed twice; and,
2. The corresponding counter is incremented twice.

I am not sure whether our not this is a bug/issue per se, but any suggestions would be greatly appreciated!

## minimal reproducible example:
- **_quarto.yml:**
```
format: html
language:
  callout-note-caption: ""
```
- **.qmd:**
```
::: {.callout-note #exr-one}
text
:::
See @exr-one.
```
- **output:**
![image](https://user-images.githubusercontent.com/14542264/187739769-ed806d14-8a43-4b62-b3f1-ece6be3776d7.png)
- This works, but is not ideal:
```
::: {.callout-note}
::: {#exr-two}
text
:::
:::
```
![image](https://user-images.githubusercontent.com/14542264/187741101-69e62644-6784-4264-b054-fc6f56a1afdb.png)

**Comment by mcanouil** [comment]
Duplicates of #2241

**Comment by HelenaLC** [comment]
My apologies, I didn't notice the issue had been transferred and re-posted it as I thought it hadn't gone through.

**Comment by mcanouil** [comment]
> My apologies, I didn't notice the issue had been transferred and re-posted it as I thought it hadn't gone through.

I'm pretty it's not you 😉
