### ISSUE TITLE
Different code block color behavior in HTML and PDF output

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-cli#2242]
### Bug description

When using the YAML options `code-block-bg` and `code-block-border-left`, I obtain different behavior in HTML and PDF. The HTML version has the expected behavior, while the PDF does not.

### HTML Document

````
---
title: "test_html"

format:
  html:
    code-block-bg: "#f3f3f3"
    code-block-border-left: "#31BAE9"
---

```{r}
1+2
```
````

#### Output

<img width="859" alt="Screen Shot 2022-08-31 at 13 53 26" src="https://user-images.githubusercontent.com/25734232/187759802-c9118469-9e1b-40c3-a1bf-748621e1071b.png">

### PDF Document

````
---
title: "test_pdf"

format:
  pdf:
    code-block-bg: "#f3f3f3"
    code-block-border-left: "#31BAE9"
---

```{r}
1+2
```
````

#### Output

<img width="825" alt="Screen Shot 2022-08-31 at 13 54 15" src="https://user-images.githubusercontent.com/25734232/187759921-01b1310d-c7b3-4d8b-99bd-5a30b4ec797a.png">

## System Info

```
❯ quarto -v
1.1.168
```

RStudio: 2022.07.1 Build 554

MacOS Monterey 12.5.1

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I can confirm that the implementation for PDF is currently mutually exclusive (and it would be nice if the behavior were consistent across formats). Thanks for reporting!
