### ISSUE TITLE
[FR] New Lua utility function to access qmd input filename

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2249]
Just opening this to track idea from https://github.com/quarto-dev/quarto-cli/discussions/2230

Maybe we could add a feature to add a `quarto.utils.input_files()` (or similar) to easily access the source `.qmd` from a Lua filter. 

Could be useful in certain case, and `PANDOC_STATE.input_files` can probably help for that. 

Let's see if some 👍 are added by users developing with Lua.

**Comment by Nenuial** [comment]
This would be great! As mentioned in my question, `PANDOC_STATE.input_files` didn't work for me, because it contains the path of a temporary *.md* file.

I was trying to write a shortcode that allows me to easily insert a link to the pdf version of a document.

I have a website with articles that have both an html and pdf output format. When rendering the html, I wanted a `{{< pdf-download >}}` shortcode to insert a link to the pdf version of the article automatically.

**Comment by cderv** [comment]
That is indeed a good solution when  `output-file` has not been set. It is possible that when set, the file returned in `PANDOC_STATE` will not be the input file. 

However a good solution for @Nenuial to know the output file name for a known format I believe. Thank you !

**Comment by Nenuial** [comment]
I implemented something along those lines after @mcanouil suggestions to try other variables in `PANDOC_STATE`. It works for my use case, but would indeed fail if the output file is changed. Thanks for sharing your solution!

**Comment by cderv** [comment]
For reference, related question in Posit Community: https://community.rstudio.com/t/find-the-name-of-the-current-file-being-rendered-in-quarto/157756

**Comment by dragonstyle** [comment]
Yep, it will available to any LUA code that is being executed (e.g. filter or shortcode)- it is public but you're right that it is omitted from the documentation (unintentionally)!

We also added some project related functions that are omitted:

```lua
quarto.project.directory
quarto.project.offset
quarto.project.profile
quarto.project.output_directory
```

Let's keep this issue open to track getting the documentation updated to reflect this.

**Comment by ratnanil** [comment]
I've been so looking forward to this! So this should be possible as of Quarto 1.2?

```
{{< quarto.doc.input_file >}}
```

**Comment by cscheid** [comment]
No, `{{< ... >}}` denotes a shortcode. `quarto.doc.input_file` is a Lua function.

**Comment by dragonstyle** [comment]
I think you could write a filter that forwards the value to `meta` and then use the `{{< meta >}}` shortcode to access it...

**Comment by mcanouil** [comment]
I was going to write a new shortcode `{{< quarto <lua-variable> >}}` to read and return the LUA variable, although maybe this is something that could be defined inside Quarto CLI. 🤔

What I don't know (yet) is how to retrieve those variables into code cells.
If the variables are "stored" in meta, this would require a particular scheme to avoid conflict with actual options.
It might be handy to have that I think.


Just me thinking out loud 😇

**Comment by cscheid** [comment]
@mcanouil if you want to give this a shot on in a branch or PR I'd be happy to review it.

**Comment by mcanouil** [comment]
Then I'll think a bit more about the YAML top level option name 😅

**Comment by cscheid** [comment]
That's the kind of thing that's easy to fix in the PR.

Although I do agree that `quarto` as a top-level shortcode is probably something we'll want to keep reserved, I think it's more important to have a proposal on the table. This way, Charles, JJ and I can start mulling it over and thinking about tradeoffs.

**Comment by mcanouil** [comment]
I'll start with a working Lua shortcode filter anyway, the rest can be changed/discussed easily after that, as you said.

**Comment by mcanouil** [comment]
Hum, Ok, I am a working solution but I still need to figure out how to expose the metadata to code cells now.
Here my work in progress repository: <https://github.com/mcanouil/quarto-lua-env>.

**Comment by cderv** [comment]
Thanks for this extension ! 

>  I need to figure out how to expose the metadata to code cells.

There is no easy way to pass information from Lua to code cells. One of the fact is the order of resolution - computation evaluation will happen before pandoc processing and Lua filters. We have some shortcodes that are resolved before though. 

This is a common issue here: Currently [Variables ](https://quarto.org/docs/authoring/variables.html) cannot be access in computation chunk. 

@cscheid is working on a related feature to have some information exchanged between Quarto main processing and computation chunk evaluation (e.g for table captions). 

> I initially thought (for R) rmarkdown::metadata would be the way, but in fact in only contains the YAML header.

Same reason as above - `rmarkdown::metadata` only knows about its meta when `render()` is called. This and knitting happens before any Lua so what happens in Pandoc Lua filter is not known by **rmarkdown**. Anyhow, relying on `rmarkdown::metadata` would not be a good solution as R only. We want something more genereric.

**Comment by mcanouil** [comment]
This is exactly what I noticed while playing around.

I will tweak a bit the filter to recursively extract booleans.
Note that I did not include `pandoc` but this could be done.

Overall, if for you it feels as a good addition to Quarto internals, could you point me to where these Lua scripts should be, for me to make a PR?

**Comment by mcanouil** [comment]
I updated the filter to retrieve and expose more "values" from more LUA variables.
For now, it includes `quarto` and several Pandoc objects.
https://github.com/mcanouil/quarto-lua-env/blob/478a5e3fb366625abad4cb539ab9a1a6004a7401/_extensions/lua-env/lua-env-filter.lua#L74-L85

**Comment by cscheid** [comment]
@mcanouil I've now lost the thread on this issue, and I'm not 100% sure what we're trying to achieve. Do you think you could open a new issue and discuss those meta settings? Your filter looks useful! but I would like to make sure we have collected everything we want in a single place. I'm going to close this one since `quarto.doc.input_file` etc satisfy the _Lua_ function requirements.
