### ISSUE TITLE
Config-based freezing

### ISSUE THREAD

**Issue by GShotwell** [quarto-dev/quarto-cli#2250]
I ran into this problem while deploying a quarto website to Rstudio Connect, but it may be useful for any site that's rendered with a cron job. Basically my site relies on long-running computation that I only want to render on Rstudio Connect The behaviour I'm after is: 

1) Document uses frozen output when `quarto render` is run locally
2) Document runs the computation when deployed to Rstudio Connect
3) Document runs the computation when re-rendered on a schedule by RSC

I tried to do this with 

```
execute: 
    freeeze: !expr Sys.getenv("R_CONFIG_ACTIVE" != "rsconnect")
```
And while that seems to work for a single html file it fails for a full site. It seems like there should be a cleaner interface for these types of config options which wasn't R-specific. For example there could be a config file which allowed the user to define YAML options on Rstudio Connect, Github actions, or when an environment variable was present.

**Comment by cscheid** [comment]
I'm increasingly convinced that our support of knitr's `!expr` is a misfeature which we should fix properly.

However, _freeze_ in general is something that you probably shouldn't ever use `!expr` with! By definition, `!expr` requires executing an engine. So what you're trying to do here cannot really work.

**Comment by GShotwell** [comment]
Right, probably you need an error in that case then. 

Would it work to allow someone specify the environment when defining execution options? Something like: 

```
execute: 
    default: 
        freeze: true
    rsconnect: 
        freeze: false
        echo: false
    github_ci:
        freeze: true 
```

**Comment by cscheid** [comment]
@jjallaire can comment more on freeze options. I think we're currently reluctant to change those because of regression risk.

**Comment by jjallaire** [comment]
In this scenario it seems like you'd also need RSC to commit and push the resulting `_freeze` folder to revision control? I don't know if they have a feature like that today.

Also, setting `_freeze` to `false` won't actually regenerate the `_freeze` folder. What you really want to do is set `freeze` to `true` (in all scenarios) and then do this on RSC:

```bash
rm -rf _freeze
quarto render
git add _freeze
git commit -m'update freezer'
git push
```

**Comment by GShotwell** [comment]
So I think what happens when RSC renders a file it doesn't start from scratch each time, but saves data from previous runs to disk. So the following occurs when `freeze: true`

1) Report renders first time on RSC
2) RSC saves a `_freeze` folder on its disk
3) On rerender the report shows the value that was generated in step `1` instead of the fresh data that the user was expecting. 

Maybe this is more of a Connect issue than a quarto issue, but I do think this would be very useful for commercial clients, and probably has a lot of value for other cron-type systems. 

In Rmarkdown land you'd use the [config package](https://kellobri.github.io/shiny-prod-book/connecting-to-data-in-production.html) to handle this kind of use case, but I don't think that works for quarto.

**Comment by jjallaire** [comment]
That might be something that you want to report to RSC? I'm not sure if its intentional that `_freeze` is resurrected for a scheduled report -- @aronatkins is this expected/intentional?

It is possible to suppress "freeze" from the command line:

```
quarto render -M freeze:false
```

Is there a way in RSC to add arguments to the `quarto render` command? We could certainly also come up with a config or environment variable based approach, just exploring what the potential solutions are.

**Comment by GShotwell** [comment]
Ah okay then that makes it really just a connect issue since other services can set that flag. I'll send something to support, and you can probably close this issue.

**Comment by jjallaire** [comment]
I think we do need some soft of feature to provide environment specific configuration so I'm going to keep this open. Perhaps something like this within `_quarto.yml`:

```yaml
project: 
  type: default

execute:
  freeze: true

environments:
  connect:
    execute:
      freeze: false
```

Where the environment is driven from e.g.

```bash
QUARTO_ENVIRONMENT=connect
```

**Comment by aronatkins** [comment]
Connect does not set `R_CONFIG_ACTIVE` for Quarto renders, today. I'll get that adjusted for our next release. We'll set `R_CONFIG_ACTIVE` for any Quarto content that uses R.

Alternatively, you can set a custom environment variable in Connect and key off of that; this approach should work today.

**Comment by aronatkins** [comment]
Reading through the earlier comments -- Connect renders in a temporary directory containing the original source as deployed; it does not chain a render from earlier results. If you include a `_freeze` directory when deploying, that directory is considered part of the source material and its contents will be used in each subsequent render (however Quarto decides to interpret its presence).

**Comment by jjallaire** [comment]
We now have a Project Profiles feature that will make it possible to do this in a more straightforward fashion: https://quarto.org/docs/projects/profiles.html

Note that if you are running either (a) The upcoming October release of RSC; or (b) Quarto v1.2 then the `QUARTO_PROFILE` will be automatically set to `connect` when running on RSC.
