### ISSUE TITLE
Markdown formatting around observable inline variables renders incorrectly.

### ISSUE THREAD

**Issue by astrowonk** [quarto-dev/quarto-cli#2252]
### Bug description

```md


## Example

I'm going to pull in some dates calculated after this markdown block with Observable.

This works fine:

* Begin date: ${the_dates[0]}
* End date ${the_dates[1]}

So does this:

**${the_dates[1]}**

But this does **not** work!

The range is between **${the_dates[0]}** and **${the_dates[1]}**. 

Yet this does!

The range is between **${the_dates[1]}** and ${the_dates[1]}.


```

Here is the python block that exists in the qmd file below all of this:

```{python}
import datetime

begin_date = datetime.datetime(2022,1,1).strftime("%B %-d, %Y")
end_date = datetime.datetime(2022,1,30).strftime("%B %-d, %Y")

ojs_define(the_dates = [begin_date,end_date])


```

This is running on OS X on a Mac Mini (m1) with Quarto 1.1.168.

It wants to me attach a file but if I drop over a .qmd file it says it's not supported. 😔 I made a [minimal repo here](https://github.com/astrowonk/quarto_bug) and attached a screenshot.

<img width="1058" alt="Screen Shot 2022-09-01 at 9 23 16 AM" src="https://user-images.githubusercontent.com/13702392/187924679-9f7bf192-4115-494c-9bb0-3b5346ed8a36.png">

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by astrowonk** [comment]
I guess since the markdown wraps nothing except the to-be-replaced Observable variable, pandoc is getting confused about where the bolding ends and begins...if I put some text inside the ** next to the observable `${}` block it works, but I really only want to bold the date...

**Comment by cscheid** [comment]
Just to clarify: it's not pandoc that's getting confused here, it's our detection of the `${}` syntax. We expect to have spaces surrounding it (so the first example, `**${var}**`, is working unexpectedly!).

Of course, that makes the markdown syntax trickier. So, for now, I recommend just using `<strong>` instead, and surrounding it with spaces (which is admittedly ugly):

```
The range is between <strong> ${the_dates[0]} </strong> and <strong> ${the_dates[1]} </strong>. 
```

**Comment by astrowonk** [comment]
I tried `<strong>` but didn't think to leave space around the `${}` block. I'll try that for now! thank you.

**Comment by cscheid** [comment]
Yes, sorry about that. This is definitely not ideal behavior on our part. We'll try to make it better in the next three months or so (this feature is surprisingly intertwined with a number of other quarto bits, so it's tricky).

**Comment by astrowonk** [comment]
> Yes, sorry about that. This is definitely not ideal behavior on our part. We'll try to make it better in the next three months or so (this feature is surprisingly intertwined with a number of other quarto bits, so it's tricky).

No worries!  I did try doing ** with spaces, i.e. 

```md


** ${the_dates[0]} ** and ** ${the_dates[1]} ** 


```

but that did not work either. Appreciate the quick replies and workaround!

**Comment by astrowonk** [comment]
Oh, one last comment is the `${the_dates[1]}` notation for Observable documented anywhere? I found it an a discussion thread but I do not see it when in the [inline code documentation here](https://quarto.org/docs/computations/execution-options.html#inline-code).

**Comment by cscheid** [comment]
That needed a documentation fix, yes. Thank you!

**Comment by cscheid** [comment]
Revisiting this to let you know that we are likely going to recommend that folks move away from complex expressions in inline statements. Instead, you should consider creating a new reactive variable, and referencing that directly. It is slightly more verbose, but we are probably going to start using the `${x}` notation for other settings in addition to Observable, and it's not practical to attempt to parse expressions in a large number of programming languages, let alone one.

For the foreseeable future, we're going to continue to support the current state of parsing that is included, but the feature will remain "best-effort", which means that this particular bug won't be fixed.

**Comment by cscheid** [comment]
You used `**${the_dates[0]}**` instead of (for example)

````
```{ojs}
//| echo: false
first_date = the_dates[0]
```
**${first_date}**
````
