### ISSUE TITLE
`quarto.utils.dump` doesn't work with PANDOC_STATE

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#2254]

**Comment by cderv** [comment]
We should probably check any of the Global variable that Pandoc is defining: https://pandoc.org/lua-filters.html#global-variables

`PANDOC_STATE` is of special type [COMMONSTATE](https://pandoc.org/lua-filters.html#type-commonstate) and other may have special types too.

**Comment by cscheid** [comment]
yes, that's precisely what I'm doing.
