### ISSUE TITLE
Problem handling Unicode characters with LaTeX

### ISSUE THREAD

**Issue by XVilka** [quarto-dev/quarto-cli#226]
How to reproduce:
1. `git clone https://github.com/rizinorg/book`
2. `quarto render --to pdf --toc`

This character "┌" (U+250C) occurs in [src/debugger/heap.md](https://github.com/rizinorg/book/blob/master/src/debugger/heap.md)

```
runnning pdflatex - 1
  This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages

compilation failed- error
Package inputenc Error: Unicode character ┌ (U+250C)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1722 \end{verbatim}
                      

Possible unsupported unicode character in this configuration. Perhaps try another LaTeX engine (e.g. XeLaTeX).
see /home/user/rizin/book/index.log for more information.
ERROR: Error
    at Object.onComplete (file:///home/user/quarto/quarto-cli/src/project/types/book/book-render.ts:245:15)
    at async renderFiles (file:///home/user/quarto/quarto-cli/src/command/render/render.ts:222:12)
    at async renderProject (file:///home/user/quarto/quarto-cli/src/command/render/project.ts:157:25)
    at async Command.fn (file:///home/user/quarto/quarto-cli/src/command/render/cmd.ts:164:24)
    at async Command.execute (https://deno.land/x/cliffy@v0.19.3/command/command.ts:997:7)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:918:16)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:870:16)
    at async quarto (file:///home/user/quarto/quarto-cli/src/quarto.ts:71:3)
    at async file:///home/user/quarto/quarto-cli/src/quarto.ts:89:5
```

**Comment by cderv** [comment]
If your document contains unicode character, you could use `lualatex` or `xelatex` which are Unicode aware engine. With pdflatex, it is not by default. 

Switching engine with quarto is possible. You can do that by setting 
```yaml
pdf-engine: xelatex
```
in the configuration file. 

You may be also able to set it at run time 
```bash
quarto render --to pdf --toc --pdf-engine xelatex
```

Hope it helps

**Comment by XVilka** [comment]
@cderv it helped but there are other issues with generated LaTeX, it seems:
# LuaLaTeX
```
$ git clone git@github.com:rizinorg/book; cd book
$ quarto render --to pdf --toc --pdf-engine lualatex  
...
compilation failed- package installation error
LaTeX Error: File `selnolig.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
   
l.143 \fi
       


see /home/akochkov/rizin/book/index.log for more information.
ERROR: Error
    at Object.onComplete (file:///home/akochkov/data/math/quarto/quarto-cli/src/project/types/book/book-render.ts:246:15)
    at async renderFiles (file:///home/akochkov/data/math/quarto/quarto-cli/src/command/render/render.ts:240:12)
    at async renderProject (file:///home/akochkov/data/math/quarto/quarto-cli/src/command/render/project.ts:158:25)
    at async Command.fn (file:///home/akochkov/data/math/quarto/quarto-cli/src/command/render/cmd.ts:164:24)
    at async Command.execute (https://deno.land/x/cliffy@v0.19.3/command/command.ts:997:7)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:918:16)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:870:16)
    at async quarto (file:///home/akochkov/data/math/quarto/quarto-cli/src/quarto.ts:88:3)
    at async file:///home/akochkov/data/math/quarto/quarto-cli/src/quarto.ts:106:5
```
## XeLaTeX
```
$ git clone git@github.com:rizinorg/book; cd book
$ quarto render --to pdf --toc --pdf-engine xelatex  
...

compilation failed- error
Undefined control sequence.
l.3139 string by prepending them with ``\x
                                          '': 

see /home/akochkov/rizin/book/index.log for more information.
ERROR: Error
    at Object.onComplete (file:///home/akochkov/data/math/quarto/quarto-cli/src/project/types/book/book-render.ts:246:15)
    at async renderFiles (file:///home/akochkov/data/math/quarto/quarto-cli/src/command/render/render.ts:240:12)
    at async renderProject (file:///home/akochkov/data/math/quarto/quarto-cli/src/command/render/project.ts:158:25)
    at async Command.fn (file:///home/akochkov/data/math/quarto/quarto-cli/src/command/render/cmd.ts:164:24)
    at async Command.execute (https://deno.land/x/cliffy@v0.19.3/command/command.ts:997:7)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:918:16)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:870:16)
    at async quarto (file:///home/akochkov/data/math/quarto/quarto-cli/src/quarto.ts:88:3)
    at async file:///home/akochkov/data/math/quarto/quarto-cli/src/quarto.ts:106:5
```

**Comment by cderv** [comment]
The first issue means you are missing a required CTAN package called `selnolig`. 
Seems like you are using TeX Live distribution. Missing packages should be installed automatically 🤔 

@dragonstyle does setting `pdf-engine` will deactivate Quarto PDF Engine for automatic installation of missing packages ? 

For the second issue, I believe this is because you used `\x` in markdown. Pandoc will keep this a latex code because of `raw_latex` extension. Saw in LaTeX it will be recognized as a command, and an unknown command. It should be escaped 

```
❯ pandoc -t latex
some text "\x"
^Z
some text ``\x''
````

````
❯ pandoc -t latex
some text "\\x"
^Z
some text ``\textbackslash x''
````

Your markdown file should contains 
```markdown
string by prepending them with "\\x"
```

so that the `\` is escaped (using this `\\`). Otherwise, the conversion will identify that as raw latex
You may need to adapt your project markdown file following the Quarto / Pandoc documentation for other small changes. 

Hope it helps.

**Comment by dragonstyle** [comment]
Setting `pdf-engine` shouldn't bypass our automatic package installation - I'm not sure why it isn't running. It would help to get a look at the quarto command output, which should show the arguments and should help confirm that our latexmk engine is indeed not running.

**Comment by cderv** [comment]
@XVilka I think things are working fine here. You would need to check your project and configure according to Quarto documentation. Maybe that would help.

Although, if you could share the TeX Live version you are using, it could be useful. Thank you !

**Comment by XVilka** [comment]
I use standard TeX tools from Fedora 35 distribution:
```
# dnf info texlive
Last metadata expiration check: 0:18:59 ago on Mon 20 Dec 2021 12:19:08 PM CST.
Installed Packages
Name         : texlive
Epoch        : 9
Version      : 2021
Release      : 45.fc35
Architecture : noarch
Size         : 0.0  
Source       : texlive-2021-45.fc35.src.rpm
Repository   : @System
From repo    : fedora

$ lualatex --version
This is LuaHBTeX, Version 1.13.0 (TeX Live 2021)

$ xelatex --version
XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021)
kpathsea version 6.3.3
Copyright 2021 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 69.1; using 69.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.11.0; using 2.11.0
Compiled with Graphite2 version 1.3.14; using 1.3.14
Compiled with HarfBuzz version 2.8.2; using 2.8.2
Compiled with libpng version 1.6.37; using 1.6.37
Compiled with pplib version v2.05 less toxic i hope
Compiled with fontconfig version 2.13.94; using 2.13.94

$ pandoc --version
pandoc 2.14.0.3
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.2,
citeproc 0.4.0.1, ipynb 0.1.0.1
```

**Comment by cderv** [comment]
@XVilka I don't see what the problem would be in Quarto. We would need more information. The Quarto engine with auto installation of package should work fine with the version of TeX Live you have. Do you have the proper right to install new CTAN package in this installation ? 

As a workaround, I would suggest to install TinyTeX (https://quarto.org/docs/getting-started/installation.html#tex). This is a portable installation and I believe this could live with another one on the system. 

Sharing more from the log file of the compilation could help us diagnose further what is happening. Thanks

**Comment by XVilka** [comment]
@cderv sorry for the delay, was busy. Attaching the log of failing to install `selnolig` with `lualatex` engine:
[lualatex-index.log.zip](https://github.com/quarto-dev/quarto-cli/files/8021861/lualatex-index.log.zip)

But it doesn't show anything useful except `LaTeX Error: File `selnolig.sty' not found.`

**Comment by cderv** [comment]
Thanks. I see this in First line 
> This is LuaHBTeX, Version 1.13.0 (TeX Live 2021)  (format=lualatex 2022.2.8)  8 FEB 2022 15:30

It seems that you are using a specific engine, and maybe we don't handle that well. 

Can you confirm that installing `selnolig` package make this works ? 

This would mean that only the auto-detection for installation is not working. 

@dragonstyle could the specific distribution `LuaHBTeX` be a problem even if this is TeX Live ? 
IDK `LuaHBTeX` so not sure...

**Comment by dragonstyle** [comment]
We should be running the latexmk process (with multiple calls to the PDF engine and attempted installation of required packages) even in this case (with a differing engine). We will bypass attempts at auto installation if `tlmgr` is not available (we just check whether we can call `tlmgr` successfully to determine whether texlive is available). In that case, the missing package would just result in an error.

So two things to investigate:

1) Does installing `selnolig` result the issue (e.g. `tlmgr install selnolig`)

2) Are you seeing messaging from Quarto indicating that it is attempting to install packages when you render? It would looks something like:

```
runnning pdflatex - 1
  This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr                        

updating existing packages            
```

**Comment by XVilka** [comment]
@dragonstyle
1. I probably know the reason. Just plain `tlmgr install selnolig` on my Fedora 35 shows this message:
```
[i] ℤ tlmgr install selnolig                                                                                                                                                                                                      
*** WARNING ***: Performing this action will likely destroy the Fedora TeXLive install on your system.
*** WARNING ***: This is almost NEVER what you want to do.
*** WARNING ***: Try using dnf install/update instead.
*** WARNING ***: If performing this action is really what you want to do, pass the "ignore-warning" option.
*** WARNING ***: But please do not file any bugs with the OS Vendor.
```
If I add this `ignore-warning` option it will request root access:
```
tlmgr install --ignore-warning selnolig                                                                                                                                                                                     You don't have permission to change the installation in any way,
specifically, the directory /usr/share/texlive/tlpkg/ is not writable.
Please run this program as administrator, or contact your local admin.
tlmgr: An error has occurred. See above messages. Exiting.
```
Not sure how to handle this from the Quarto side though.

2. Yes, it was showing these messages:
```
runnning lualatex - 1
  This is LuaHBTeX, Version 1.13.0 (TeX Live 2021) 
   restricted system commands enabled.
  
updating tlmgr

updating existing packages
finding package for selnolig.sty
> 1 package to install
> installing selnolig (1 of 1)
  This is LuaHBTeX, Version 1.13.0 (TeX Live 2021) 
   restricted system commands enabled.
  
finding package for selnolig.sty

compilation failed- package installation error
LaTeX Error: File `selnolig.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
   
l.144 \fi   
```

**Comment by cderv** [comment]
That is helpful ! 

@XVilka you need to use an installation with correct right access to benefit from Quarto auto installation feature. I think you could install TinyTeX in addition to your system installation. https://quarto.org/docs/output-formats/pdf-engine.html#installing-tex

Quarto would use this distribution and would be able to install into it. 

Otherwise, installation using DNF the missing packages manually following the Quarto warning message would be the way I think. 

Glad we got to the bottom of this.

**Comment by XVilka** [comment]
Thank you everyone! We could consider this solved then 💯
