### ISSUE TITLE
Self-contained feature does not include CSS when output-file is specified

### ISSUE THREAD

**Issue by davidbudzynski** [quarto-dev/quarto-cli#2266]
### Bug description

When I'm trying to save a self-contained HTML file to a specific file, it appears that it doesn't contain any CSS. Everything is file when `output-file` is not specified:

without output-file in the YAML header:
![image](https://user-images.githubusercontent.com/56514985/188110451-4e9de7b1-baf9-4873-a8f7-b09284f6a5f4.png)

with output-file:

![image](https://user-images.githubusercontent.com/56514985/188111055-93372f65-d0e2-4819-b4ef-63fc918b0042.png)

![image](https://user-images.githubusercontent.com/56514985/188110626-d95bb8d8-bff3-43e8-a969-ff9a8076b920.png)

I'm using R via Rstudio on Windows:
```
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by rpruim** [comment]
I can confirm seeing this as well and was just going to create a similar issue.

**Comment by dragonstyle** [comment]
Note that the key to triggering this bug is using a path in the output-file (e.g. `../foo.html`).

**Comment by dragonstyle** [comment]
output-file no longer accepts paths and we properly error
