### ISSUE TITLE
Cannot use `rstudioapi::askForPassword()`; works in .Rmd

### ISSUE THREAD

**Issue by rich-iannone** [quarto-dev/quarto-cli#2269]
### Bug description

Taken from [Community](https://community.rstudio.com/t/rstudioapi-askforpassword-function-in-quarto/146254) (2022-01-01):

When running RMD documents I use the rstudioapi::askForPassword function to push passwords to databases. This works both in interactive mode and when knitting.

However when using qmd, when I hit the "render" button in RStudio 2022.07.1 Build 554
I get the error
Quitting from lines 16-19 (test.qmd)
Error: RStudio not running

I'm not sure how to create a reprex since it is an issue with rendering an RMD, but I get the error just by adding the command rstudioapi::askForPassword("testing") to an R chunk inside the default qmd template that is created when you do file > new quarto document

Is it not possible to use the rstudioapi package when rendering a qmd?

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
**rstudioapi** is tied to the RStudio IDE and is an R package that can be used to access some feature from the IDE than an R process is running **by the IDE itself**. 

With Quarto, RStudio IDE is running Quarto binary, and then it is Quarto which will run R to compute code chunks using R. The R process launch by Quarto won't have access to any of the IDE feature as this not interactive and not running in the IDE. 

R function run as part of Quarto code chunks won't be able to prompt the user as R code run in a non interactive background process.  IMO, prompting for password in a rendering of document is not among the best practice in my opinion. 

I am not sure this is really a bug in Quarto. Don't you agree @rich-iannone ? 
I can answer on the community if you want.

**Comment by cscheid** [comment]
(I agree that this looks to me like an RStudio IDE issue.)

**Comment by jjallaire** [comment]
This isn't something that we will ever make work.
