### ISSUE TITLE
`data-background-color` property stopped working in quarto 1.1.179

### ISSUE THREAD

**Issue by ccamara** [quarto-dev/quarto-cli#2277]
### Bug description

[Following pandoc's documentation](https://pandoc.org/MANUAL#on-all-slides-beamer-reveal.js-pptx), I have been using the following code in a qmd document I want to be rendered as a revealjs and where I want the title's slide having a specific background.

```qmd
---
title: "My Fancy title"
title-slide-attributes:
    data-background-image: "https://upload.wikimedia.org/wikipedia/commons/archive/8/8c/20210225154040%21Folio-Quarto-Octavo_Compared.svg"
    data-background-opacity: "0.40"
    data-background-color: "#552D62"
format: 
  revealjs:
    theme: serif
    transition: slide
    background-transition: fade
---

# Some fancy title

```

This code has been working in the past, with Quarto v 1.0.38, but I just updated to 1.1.179 and stopped working.

The error I get now is (either in RStudio and in VS Code):

```
ERROR: Validation of YAML front matter failed.
ERROR: In file slides.qmd
(line 11, columns 5--26) property name data-background-color is invalid
10:     # data-background-size: contain
11:     data-background-color: "#552D62"
        ~~~~~~~~~~~~~~~~~~~~~
12:     data-background-opacity: "0.40"
ℹ The error happened in location title-slide-attributes:data-background-color.

ERROR: Render failed due to invalid YAML.
```

Also, vscode's warning me that `data-background-color`is not a valid property.

If I comment out the line with `data-background-color`the slides are rendered perfectly, but of course, they are not rendered as I'd like them to look like.

**My environment:**

* Quarto version: 1.1.179
* VSCodium: Version: 1.70.2
Release: 22230
Commit: 6c122d9b2d1af2c37bd55caad614321eb53b342f
Date: 2022-08-18T00:40:55.241Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0 
* RStudio: 2022.07.1 Build 554
* OS: MacOS 12.5

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I think this is a result of us closing down the schemas and missing a property.

@jjallaire I can fix this, but should I:

1) reopen the schema, or
2) track down all the usages of the field `title-slide-attributes` and add all fields? I don't know if this is meant to be open-ended or not.

**Comment by jjallaire** [comment]
This is this fix: https://github.com/quarto-dev/quarto-cli/commit/0196d1c727414b7d4a472bf248e9e0e704f3901d

It is indeed open-ended (as pandoc just passes through any attributes provided). I opened it and added `data-background-color` for docs/completion. I will backport this to v1.1 as well
