### ISSUE TITLE
[FR] Extend `code-fold: true` to other formats such as `gfm`

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#2279]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2278

<div type='discussions-op-text'>

<sup>Originally posted by **mavam** September  3, 2022</sup>
I'm outputting my qmd in GFM, which puts code and output adjacent to each other. I would like to wrap *only the code* in a `<details>` section:

I tried this:

    <details><summary>Code</summary>

    ```{r}
    data |> ggplot(..)
    ```

    </details>

But this also puts the output (in this case, a plot) into the details section. I couldn't find an option for that in the [GFM docs](https://quarto.org/docs/reference/formats/markdown/gfm.html).

My hunch is that I need to write a filter, ~but wrangling the AST in Lua is a different ballpark.~  EDIT: I managed to write a filter, but it feels pretty hacky:

```lua
function CodeBlock(code_block)
    if code_block.attributes["code-fold"] == "true" then
        local open = "<details><summary>Code </summary>\n"
        local close = "\n</details>"
        local open_block = pandoc.RawBlock("html", open)
        local close_block = pandoc.RawBlock("html", close)
        return {open_block, code_block, close_block}
    end
    return code_block
end
```

Is that the right approach?

(NB: I'm aware that HTML output does this. But I need to output to GFM where there is no collapse option.)
</div>

**Comment by mavam** [comment]
With the filter I provided, I have solution that works independent of the output format. For example, I can now write:

    ```{r}
    #| code-fold: true
    x <- 42
    ```

I'm not sure what the quarto-native equivalent for the native implementation is, but the UX feels "right" with this approach.

**Comment by mcanouil** [comment]
Not all formats can support this.
`gfm` used by GitHub/GitLab the ne probably other web services are able to handle raw HTML, because it's part of a website? But for example `docx` format will never be able to use it.

**Comment by mavam** [comment]
Makes sense, so then this would be a conditional filter, given that `gfm` is the format? Maybe exposed as a format option?

**Comment by jjallaire** [comment]
This was pretty easy to get working: https://github.com/quarto-dev/quarto-cli/commit/3e071c1e30a4253d9b5640356da6b9c0b4ff7ddd

I made cold-folding available for any markdown output format that supports `raw_html`
