### ISSUE TITLE
Caption and cross-ref for single table generated from code chunk

### ISSUE THREAD

**Issue by JulianTao** [quarto-dev/quarto-cli#228]
It seems that a table generated using a code chunk is thrown into a `layout` environment and treated as a sub table. The caption and cross-ref only work when two captions are defined: both at the code function level and at the chunk level.

For example,

With the code bellow, the table is not numbered and cross-ref does not work.

````markdown
```{r}
#| label: tbl-no_kable_caption
#| tbl-cap: "A table from kable"

knitr::kable(mtcars[1:5, 1:5])
```
@tbl-no_kable_caption
````
With the code below, the table is numbered, cross-ref works, but the resulting table has two captions: the one defined in the kable function is used as a sub-table caption; and the one defined as the chunk option is used as the main caption. 
In addition, the placement of the main caption is below the table, not above it.

````markdown
```{r}
#| label: tbl-with_kable_caption
#| tbl-cap: Chunk Caption

knitr::kable(mtcars[1:5, 1:5], caption = "kable caption")
```
@tbl-with_kable_caption

````
With the code below, everything works fine, but it seems that there is no way to cross-ref the table.  Adding a label in `{r}` like the way in rmarkdown does not help neither.

````markdown
```{r}
knitr::kable(mtcars[1:5, 1:5], caption = "no chunk caption")
```
````
Attached is the output pdf file so you can see the differences.
[table-crossref.pdf](https://github.com/quarto-dev/quarto-cli/files/7732289/table-crossref.pdf)

What is the proper approach?

I understand that this is also related to an earlier issue (#90) that I submitted a while ago. Any improvement on this matter is appreciated.

**Comment by jjallaire** [comment]
I think this is a result of the page layout changes made by @dragonstyle a couple weeks ago and should be easy to remedy (i.e. it shouldn't be behaving the way that it is, likely just an oversight in our code)

**Comment by dragonstyle** [comment]
OK, it looks like things are working as we expect, but the documentation for simple computation wasn't really that helpful. I've updated it to provide a simple example [here](https://quarto.org/docs/authoring/cross-references.html#computations-1). 

The basic summary is that for a single table output, you should use the caption parameter and include the label in the caption, e.g. `caption="kable caption {#tbl-with_kable_caption}"`. 

Let me know if this gets you going!

**Comment by JulianTao** [comment]
OK, I see, it works for me now. But maybe it is a personal preference, I like the way how computation figures are handled [here](https://quarto.org/docs/authoring/cross-references.html#computations). It is cleaner and easy to remember. I feel it is helpful to have syntax consistences in handling figures and tables, so the mental load of the user is minimum.

Another note (reminder #90) on the placement of captions: 
1. can we collect the subcaptions into the main caption? Also, if I give a label to the subfigure without assigning a caption, a question mark will appear.
2. can we place the main caption for tables above the table itself?

For casual documentation, where the captions are placed does not matter much. I am trying to submit a paper using Quarto, the writing process is much simpler than using LaTex or Word directly, but these little things on captions and cross-ref continue to bother me. 

Thank you!

**Comment by jjallaire** [comment]
I think you are correct that this inconsistency will trip people up. One reason it works this way is that embedded tables can be raw LaTeX or HTML, so in order to apply the label and caption we need to successfully parse / interact with the raw code (trickier than interacting with markdown where we have a fully parsed AST). Not to say that it can't be done it's just a bit trickier. 

We'll take a look at this as well as the other issues you re-raised here soon!

**Comment by jjallaire** [comment]
For the requirement of collecting subcaptions into the main caption, would it be enough to just stop emitting the question mark (i.e. just tolerate empty subcaptions). That way you could write whatever you want as the aggregate caption (rather than us creating some collection logic that might not give you exactly the copy you want)

**Comment by JulianTao** [comment]
> would it be enough to just stop emitting the question mark (i.e. just tolerate empty subcaptions)

Yes, this would be enough for most cases. A special case is that if we need to reorder the sub-figures inside the figure-div, we need to manually reorder the sub-captions as defined in the main caption. But that is not a big deal:)

**Comment by jjallaire** [comment]
Okay, we've now made the change to allow empty subcaptions. For plain markdown its enough to just exclude the subcaption. For output generated from code you to need tell us that you want empty subcaptions via e.g. `fig-subcap: ""` (this is to distinguish from the case where two figures created from a chunk are meant to be e.g. Figure 1 and Figure 2)

**Comment by jjallaire** [comment]
Captions are now located above tables by default  (you can change this behavior via `tbl-cap-location: bottom`).

**Comment by jjallaire** [comment]
Docs on caption locations are here: https://quarto.org/docs/authoring/figures-and-layout.html#caption-locations

**Comment by JulianTao** [comment]
Thank you so much! I can confirm that all the new features work as expected.
Just a note that for sub-tables with empty sub-captions, the correct syntax for the sub-captions is `: {#tbl-subcap}`. The space between `:` and `{` is necessary.

**Comment by jjallaire** [comment]
Thanks for the note, I took a look at removing this limitation but pandoc requires the space in order to correctly parse the table caption.

**Comment by jjallaire** [comment]
With this PR (https://github.com/quarto-dev/quarto-cli/pull/236) `tbl-cap` and `tbl-subcap` are now available as code cell options and work the same as `fig-cap` and `fig-subcap` (updated docs here: https://quarto.org/docs/authoring/cross-references.html#computations-1)
