### ISSUE TITLE
improve error message for `#| key = value` validation failure

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#229]
as reported by Mine:

> A suggestion / feature request for helpful error message -- I think the following might be a common error for those coming from knitr/rmarkdown:
> 
> ```
> #| echo = FALSE
> 1 + 1
> ```
>
> Right now the error message says `YAML validation failed - exiting`. Could it say something like `Did you use = instead of : when defining your chunk options?` (like how ggplot2 helps you if you use %>% instead of +).

**Comment by jjallaire** [comment]
cc @mine-cetinkaya-rundel

**Comment by cscheid** [comment]
Fixed in branch `feature/yaml-validation`, this should be live in the next couple of weeks. Thanks for the report!
