### ISSUE TITLE
Update Sass theme format to reflect new sass::sass_layer()

### ISSUE THREAD

**Issue by cpsievert** [quarto-dev/quarto-cli#23]
The format is inspired by the current version of `sass::sass_layer()`

```
/*-- scss:declarations --*/
@function colorToRGB ($color) {
  @return "rgb(" + red($color) + ", " + green($color) + ", " + blue($color)+ ")";
}

/*-- scss:variables --*/
$h2-font-size:          1.6rem !default;
$headings-font-weight:  500 !default;
$body-color:            $gray-700 !default;

/*-- scss:rules --*/
h1, h2, h3, h4, h5, h6 {
  text-shadow: -1px -1px 0 rgba(0, 0, 0, .3);
}
```

We'll likely be deprecating the  concept of `declarations` in favor of `functions` and `mixins` (https://github.com/rstudio/sass/pull/80), which will allow variable defaults to make use of functions

```
/*-- scss:functions --*/
@function color-contrast($color) {
  @return if(
    red($color) * 0.299 + green($color) * 0.587 + blue($color) * 0.114 > 186,
    black, white
  );
}

/*-- scss:variables --*/
$body-color:            color-contrast($body-bg) !default;

/*-- scss:mixins --*/
@mixin body-color {
  color: $body-color
}

/*-- scss:rules --*/
body {
  @include body-color;
}
```

**Comment by dragonstyle** [comment]
This is great- thank you. I will get Quarto updated to match this form / behavior for layering.

**Comment by cpsievert** [comment]
@dragonstyle you may also want to consider changing `variables` -> `defaults`. That's the `sass_layer()` terminology we use, partially to emphasize that the variables should have `!default` flags

**Comment by dragonstyle** [comment]
We would be good with that:

```
/*-- scss:functions --*/
@function color-contrast($color) {
  @return if(
    red($color) * 0.299 + green($color) * 0.587 + blue($color) * 0.114 > 186,
    black, white
  );
}

/*-- scss:defaults --*/
$body-color: color-contrast($body-bg) !default;

/*-- scss:mixins --*/
@mixin body-color {
  color: $body-color
}

/*-- scss:rules --*/
body {
  @include body-color;
}
```

That look good?

**Comment by cpsievert** [comment]
Yes, thank you!

**Comment by dragonstyle** [comment]
Thanks for the review and feedback! I should get this all done in this repo in the next day or so...

**Comment by dragonstyle** [comment]
This should be all set in the next release of Quarto:

https://github.com/quarto-dev/quarto-cli/commit/fb10362fc4b9df0b99b58656a1caed5390514f5f
