### ISSUE TITLE
Block layout imorvement / exception in reveal presentation

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#230]
Just to note some findings about block layout in reveal presentation as documented here: https://quarto.org/docs/authoring/figures-and-layout.html#block-layout. 

It won't work straight away because of header meaning slide section in reveal

## Example 1 

````markdown
---
title: "Title"
format: revealjs
---

## Slide 1

::: {layout-ncol=2}
- Item X
- Item Y
- Item Z

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur gravida eu erat et fring. Morbi congue augue vel eros ullamcorper, eget convallis tortor sagittis. Fusce sodales viverra mauris a fringilla. Donec feugiat, justo eu blandit placerat, enim dui volutpat turpis, eu dictum lectus urna eu urna. Mauris sed massa ornare, interdum ipsum a, semper massa. 
:::

## Slide 2

::: {layout-ncol=2}
### List One

- Item A
- Item B
- Item C

### List Two

- Item X
- Item Y
- Item Z
:::
````

The presentation created can't be navigated. Slides can be seen on the overview but they are split unexpectedly and using the arrow to go toward the last slide send back to the first slide.  I believe this is because headers are handles by reveal conversion as slides 

Setting slide level 3 fix it 
````yaml
title: "Title"
format: 
  revealjs:
    slide-level: 3
````

Maybe we should document this limitation ? 

## Example 2

When we make it work using `slide-level: 3` the layout is not ok
![image](https://user-images.githubusercontent.com/6791940/146766749-ce752d96-1f58-459d-9701-8f2c2232e895.png)

probably some CSS update to do.

**Comment by jjallaire** [comment]
Good catch! Should be resolved here (just using bold text instead of the heading when within reveal): https://github.com/quarto-dev/quarto-cli/commit/8f46447457f54cd8b0faebbfd97293e90ab6e3a0
