### ISSUE TITLE
Using reticulate in VSCode when dynamically executing quarto document

### ISSUE THREAD

**Issue by schae211** [quarto-dev/quarto-cli#2313]
### Bug description

I have simple Quarto document with one R and one Python chunk. I want to access R variables in the python chunk via reticulate (`reticulate::repl_python()`) which works fine when I work with the document in RStudio.

```
---
title: "Example"
format: html
engine: knitr
---
```

```{r}
# r chunk
library(reticulate)
data(cars)
```

```{python}
# python chunk
car_df=r.cars
car_df
```

However, when I am using VSCode it doesn't work anymore. When I execute the python chunk, a Python REPL is started that has nothing to do with the R Session. Thus, I get a NameError in the python chunk because `name 'r' is not defined`.  

Am I using the wrong settings in VSCode? Why isn't the Python REPL started via `reticulate::repl_python()` as it is in RStudio? Funnily, if I knit the Quarto document in VSCode everything is working fine.  It might be important that I am working over an SSH connection in VSCode. 

I know that I could simply type in the R console `reticulate::repl_python()`, but it would be much more convenient if VSCode would "automatically" use the correct repl.

### Version Info

RStudio Server Version: 2022.07.1+554
VSCode Version: Version: 1.71.0
OS: Ubuntu 20.04.5 LTS (Focal Fossa)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by GlekoMa** [comment]
I checked the source code of quarto-vscode. There is the difference between "Run (Python) Cell" and "Run (R) Cell": [172-194 lines](https://github.com/quarto-dev/quarto-vscode/blob/916b69cda1ff2ee1ed2f071f4fae2b7b1be505e0/src/providers/cell/executors.ts)

Maybe the reason for that python chunk is designed to be run in Jupyter Interactive by default is to enable python(jupyter) users get started easily. I think it's the right choice.

> it would be much more convenient if VSCode would "automatically" use the correct repl.

But I also fully agree with your proposal: R users need a more convenient workflow in VScode to use the wonderful bridge(reticulate) between R and Python. Maybe give users a choice to change the python chunk run command to `reticulate::repl_python()` in quarto-vscode extention will be a beautiful thing, just like RStudio does :sparkles:.

> It might be important that I am working over an SSH connection in VSCode.

So I don't think this is an influencing factor :grinning:.

Hope this feature will be developed!

**Comment by bernardo-cruz** [comment]
same issue here. Hope a solution is soon found

**Comment by omarvaldez5** [comment]
+1

**Comment by henningsway** [comment]
+1 :)

**Comment by XeroLen23** [comment]
+1

**Comment by cscheid** [comment]
Hi folks, we hear you and appreciate your involvement. But a `+1` comment on a thread just pollutes our notifications and means we have less time to fix bugs and implement features :).

**Comment by brbarkley** [comment]
Any update on this feature? 

It appears there are other issues that are talking about the same thing. Listing here for awareness:
https://github.com/quarto-dev/quarto/issues/77
https://github.com/REditorSupport/vscode-R/issues/1299
https://github.com/quarto-dev/quarto/issues/112

**Comment by mcanouil** [comment]
As you can see, it's still open.

@jjallaire Do you think the Quarto VSCode extension could send everything to R when `engine: knitr`?

PS: This issue seems more appropriate in <https://github.com/quarto-dev/quarto>, maybe worht transferring it.

**Comment by jjallaire** [comment]
Just implemented this in the VS Code extension: https://github.com/quarto-dev/quarto/commit/5b1e799aae821798d28e24e0dddca0fa31544884

Will be available in the next release (likely later this week)

**Comment by brbarkley** [comment]
> Just implemented this in the VS Code extension: [quarto-dev/quarto@5b1e799](https://github.com/quarto-dev/quarto/commit/5b1e799aae821798d28e24e0dddca0fa31544884)
> 
> Will be available in the next release (likely later this week)

Great news! Look forward to trying it out.

**Comment by mcanouil** [comment]
Closing this as completed.
