### ISSUE TITLE
NotFound Error when rendering Python or Julia cells on an NFS mount 

### ISSUE THREAD

**Issue by white-c** [quarto-dev/quarto-cli#2316]
### Bug description

I have been unable to render my document in versions 1.1.179 or 1.1.189. I am on Windows 10 using VS Code but I have replicated the issue in CLI with Powershell and CMD. I have seen the following error:

```powershell
└─$ quarto render .\test.qmd --to html
ERROR: NotFound: The system cannot find the path specified. (os error 3)
```

The contents of the file are simple:

        ---
        title: Just a test
        author: Me
        date: September 6, 2022
        ---
        
        # My first header
        
        Lorem ipsum.... you know the drill.
        
        ```{python}
        print(f"My Python Cell")
        ```

If I run the render on my local `C:\` drive, it runs successfully. But, if I run on a mapped NFS drive, e.g. `Z:\` -> `\\someserver\somefolder\`, then I get the error. If I include the `--execute-debug` flag I get:

```powershell
└─$ quarto render .\test.qmd --to html --execute-debug
- Connecting to kernel
ERROR: NotFound: The system cannot find the path specified. (os error 3)
```

Any thoughts on what is happening? The `--debug` flags don't add any information.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
> If I run the render on my local C:\ drive, it runs successfully. But, if I run on a mapped NFS drive, e.g. Z:\ -> \\someserver\somefolder\, then I get the error.

This is another instance of the general issue we've been having with non-standard drives on windows.

**Comment by white-c** [comment]
Is there any additional debugging that you think I should run to provide insight for you?

**Comment by cderv** [comment]
Can you try with the pre-release version 1.2.x series  https://quarto.org/docs/download/ ? 

And then, can you run `quarto render` after having activated Quarto Stack print 

In powershell

````powershell
$ENV:QUARTO_PRINT_STACK="true"
quarto render test.qmd --to html
```` 

This should call the stack trace for the error. 

Thank you

**Comment by white-c** [comment]
I have attached the stack output. FYI, for this test I mapped my NFS directory to `Y:\` and ran from that directory.

[stack.log](https://github.com/quarto-dev/quarto-cli/files/9601928/stack.log)

**Comment by cderv** [comment]
Let me put the log in here for easier reading than opening a file 

<details><summary>stack trace </summary>

````

Starting python3 kernel...Done


An error occurred while executing the following cell:
------------------

# imports
import os
import sys
import types
import json

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = fig_dpi
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  pio.renderers.default = "notebook_connected"
except Exception:
  pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass



# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
if r'Y:\':
  os.chdir(r'Y:\')

# reset state
%reset

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v
  
  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define

------------------

  Input In [1]
    if r'Y:\':
              ^
SyntaxError: EOL while scanning string literal

SyntaxError: EOL while scanning string literal (3967143024.py, line 61)

````
</summary>

It seems the issue is from Python directly 

````
  Input In [1]
    if r'Y:\':
              ^
SyntaxError: EOL while scanning string literal

SyntaxError: EOL while scanning string literal (3967143024.py, line 61)
````

What is the path of the project exactly when mounted on Y: ?  Do you mount the root of the project ? 

I am curious if you can convert your document to ipynb : `quarto convert mydocument.qmd` 

and then try to run the cells in Jupyter notebook on your system.  Curious if this is related to Quarto or Jupyter. 🤔

**Comment by white-c** [comment]
I did mount the project directly to `Y:\`. 

When I mount up a level and then run, it is successful. Yay!

Below is the output of convert, which gave no errors.

```
{
  "cells": [
    {
      "cell_type": "raw",
      "metadata": {},
      "source": [
        "---\n",
        "title: Just a test\n",
        "author: Me\n",
        "date: September 6, 2022\n",
        "---"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# My first header\n",
        "\n",
        "Lorem ipsum.... you know the drill."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {},
      "source": [
        "print(f\"My Python Cell\")"
      ],
      "execution_count": null,
      "outputs": []
    }
  ],
  "metadata": {
    "kernelspec": {
      "name": "python3",
      "language": "python",
      "display_name": "Python 3 (ipykernel)"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
```

**Comment by white-c** [comment]
I forgot to mention that this only works with the 1.2.133 dev version I downloaded. As soon as I try 1.1.251, it doesn't work - still.

**Comment by cderv** [comment]
> When I mount up a level and then run, it is successful. Yay!

Regarding what is working with 1.2.133, you mean converting the `.qmd` file or running the ipynb ? 

Sorry I am just unsure of where we're at. 😅

**Comment by white-c** [comment]
Sorry for the confusion. Both the `render` and running the notebook work under 1.2.133. The `render` works as long as I map to at least one level above the file directory I want to `render`. The notebook converts and runs whether I map directly to the folder or to one level up the file structure.

**Comment by cderv** [comment]
> Both the render and running the notebook work under 1.2.133. 

Awesome. So at least we have a way for this to work correctly. 

> The render works as long as I map to at least one level above the file directory I want to render

I am wondering where in the stack this comes from - maybe it is pandoc. If you are still willing to help, can you share with me some more results ? 

Still using `$ENV:QUARTO_PRINT_STACK="true"` and from your same NFS drive. 

* Did you try rendering a `.qmd` document without computation cells ? Pure Markdown with no Python. Like:
````markdown
    ---
    title: Just a test
    author: Me
    date: September 6, 2022
    ---
    
    # My first header
    
    Lorem ipsum.... you know the drill.
    
    ```python
    print(f"My Python Cell")
    ```
````
Do you still have the issue ? 

* When you mount to `Y:/` are you running `quarto render` from that root folder in terminal ? 

This would help me try reproduce. Thank you

**Comment by cderv** [comment]
@white-c Do you still have the issue ? Can you give us more information so that we can reproduce ? thank you
