### ISSUE TITLE
Use plot as blog post image

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#2324]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2319

<div type='discussions-op-text'>

<sup>Originally posted by **11rchitwood** September  6, 2022</sup>
Let's say I have a post whose first code chunk is:

```r
plot(cars)
```

How can I make this be the preview image for the post?</div>

Being able to refer to easily refer to resources generated by the execution engines in our code is a good idea (I can imagine a similar feature being useful for the output of a `dot` or `mermaid` cell, or some arbitrary user shortcode)

**Comment by mcanouil** [comment]
To note, for blog post in Quarto website, if there is an image in the folder it was taken as the preview in the listing page.
So, it would only require to export the chunk as a raster image to the Qmd directory to have the preview.
This could easily be done at least for knitr with reusable code cell.

The above behaviour was observed at least until Quarto 1.0.36.
After I updated the yaml to explicitly list the image and added alt text.
See <https://github.com/RLille/rlille.fr/tree/c6647dc8082caeadab3ec4ea32be3a4f013db192/posts/2022-01-24-golem>.

**Comment by aammd** [comment]
I found this VERY challenging because the documentation states that [this is possible](https://quarto.org/docs/websites/website-listings.html#listing-fields)

> The image for this item, read from the image field of the front matter, or automatically discovered by taking the first of an image of class preview-image, an image with a file name starting with feature, cover, or thumbnail, or the first image to appear in the document.

**Comment by JonGretar** [comment]
Yeah that confuses me as well.

> I found this VERY challenging because the documentation states that [this is possible](https://quarto.org/docs/websites/website-listings.html#listing-fields)
>

**Comment by mcanouil** [comment]
Is this issue not fixed by using the "preview-image" class as stated in the documentation? (I do not know since when)

````
```{r}
#| class-output: preview-image
plot(1)
```
````

**Comment by JonGretar** [comment]
No. 
Nor does it indeed pick, if undefined, any plot as a preview image. It only picks the first static image it sees and leaves it previewless if none are found. I tried all the methods defined in the docs. 

> Is this issue not fixed using the "preview-image" class as stated in the documentation? (I do not know since when)

**Comment by cscheid** [comment]
(@dragonstyle I think I need to do this for mermaid charts, dot, etc)

**Comment by dragonstyle** [comment]
Listings will now generically discover images in the rendered output using our normal preview image semantics, so it could be as easy as improving our preview image detection to include those (which would mean they could participate in things like twitter cards, open graph, etc...)

**Comment by cscheid** [comment]
great, I'll get back to you on this when mermaid+dot are back into rendering static PNG and SVG correctly.

**Comment by cscheid** [comment]
This works on v1.4 right now:

<img width="926" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/a9c7c825-6aea-4451-9c24-1405827c8dd5">

One caveat is that users need to specify `mermaid-format: png` so that the diagram is pre-rendered (instead of being a JS widget). At some point we'd like to improve that situation, but it's a different issue.

**Comment by produnis** [comment]
> starting in the next pre-release, this should be supported like so:
> 
> ```
> ```{r}
> #| classes: preview-image
> plot(mtcars)
> ```
> ```

currently (quarto 1.4.550),  `#| classes: preview-image` seems to be ignored, in my blog, the first picture from a plot chunk is picked as the preview image, no matter if I set the `#| classes: preview-image`  to a specific plot chunk

**Comment by cderv** [comment]
@produnis could you open a new issue with a reproducible example ? Maybe there is a regression. Having a simple example (e.g create using `quarto create project`) will help us look into this. 

Thanks a lot!
