### ISSUE TITLE
How to customise the width and height of Open Graph?

### ISSUE THREAD

**Issue by ambarja** [quarto-dev/quarto-cli#2325]
#### Hi everyone, recently I migrated my website using Quarto and I would like customise the width and height of Open Graph. 👇 
<img src="https://user-images.githubusercontent.com/23284899/188705141-cc7b15a3-ec74-474e-9dee-1b9516c79e89.PNG" width="500px"/>

#### My quarto.yml is the following 👇 
<img src="https://user-images.githubusercontent.com/23284899/188705285-f01a96d8-976d-41fa-aca3-ffa5c2383a9b.png" width="500px"/>

**Comment by ambarja** [comment]
Acoording to documentation the code is:
![image](https://user-images.githubusercontent.com/23284899/188705850-dcc7336c-20ae-45be-b535-ea8916ab12ae.png)
however is not solve my question

**Comment by cscheid** [comment]
Those entries control the width and height of figures generated by code cells, not the width and entry of your `open-graph` card.

Can you share a link to a full, minimal reproducible example? A github repository that we can build ourselves is ideal.

**Comment by dragonstyle** [comment]
We don't current support declaring open graph image sizes but will try to add this soon!

Note to self - need to support 

```
<meta property="og:image:width" content="..." />
<meta property="og:image:height" content="..." />
```

**Comment by ambarja** [comment]
> Those entries control the width and height of figures generated by code cells, not the width and entry of your `open-graph` card.
> 
> Can you share a link to a full, minimal reproducible example? A github repository that we can build ourselves is ideal.

Thanks for the support, I share my repository, you can find my website code [here](https://github.com/ambarja/ambarja.github.io).

**Comment by ambarja** [comment]
> We don't current support declaring open graph image sizes but will try to add this soon!
> 
> Note to self - need to support
> 
> ```
> <meta property="og:image:width" content="..." />
> <meta property="og:image:height" content="..." />
> ```
Thanks, I tried to put manually in the html output, and it's fine, but my website is now with githubaction deploy and when I do a push again, it runs again and it deletes again those parameters. :cry:

**Comment by dragonstyle** [comment]
The current pre-release of Quarto 1.2 now supports this as of 1.2.108, available here:

https://quarto.org/docs/download/prerelease.html

Thanks for reporting, that was a bad oversight!

The yaml as you have it in your original screenshot should work as you expect now!
