### ISSUE TITLE
Render does not move companion files to output directory

### ISSUE THREAD

**Issue by jspaezp** [quarto-dev/quarto-cli#2329]
### Bug description

Hello!

The issues are .... 

1. When rendering a document to markdown format and such document generates images, the directory with the images is not moved to the output directory with the output file
2. When rendering a document with the `--output-dir` argument, it is ignored. (output is still in the source directory of the input)

## Reproducible Example

Using the nightly release of quarto, under mac os

````shell 
+ quarto --version
1.2.69
+ uname
Darwin
+ uname -r
21.6.0
````

Having this dummy directory structure as an example

````shell
+ tree
.
├── output
└── source
    └── file.qmd

2 directories, 1 file
````

Where the input file is this ... (simple file, generates a plot)

````shell
+ cat source/file.qmd

# This is a file

```{python}
print("Hello")

import matplotlib.pyplot as plt
import numpy as np

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```
````

And I run .... (render it with the `--output-dir` option)

````shell
+ quarto render source/file.qmd --output-dir output/ --to gfm

Executing 'file.ipynb'
  Cell 1/1...Done

pandoc 
  to: gfm+footnotes+tex_math_dollars-yaml_metadata_block
  output-file: file.md
  standalone: true
  default-image-extension: png
  
Output created: file.md
````

The output directory looks like this ...

````shell
+ tree
.
├── output
└── source
    ├── file.md
    ├── file.qmd
    └── file_files
        └── figure-gfm
            └── cell-2-output-2.png

4 directories, 3 files
````

Note how the file (`file.md`) is not in the desired output directory at all

A similar thing happens if I render it with the `--output-dir` option and `--output` option pointing to the (not yet existent) output file in the (already existing) output directory.

````shell
+ quarto render source/file.qmd --output-dir output/ --to gfm --output output/file.md

Executing 'file.ipynb'
  Cell 1/1...Done

pandoc --output ../output/file.md
  to: gfm+footnotes+tex_math_dollars-yaml_metadata_block
  standalone: true
  default-image-extension: png
  
Output created: ../output/file.md

+ tree
.
├── output
│   └── file.md
└── source
    ├── file.qmd
    └── file_files
        └── figure-gfm
            └── cell-2-output-2.png

4 directories, 3 files
```

Oddly enough, now the output file is in the correct location BUT the companion files are not

And the content of the output file is ...

````shell
+ cat img output/file.md
cat: img: No such file or directory

# This is a file

``` python
print("Hello")

import matplotlib.pyplot as plt
import numpy as np

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

    Hello

![](file_files/figure-gfm/cell-2-output-2.png)
````

Therefore, the file will not display correctly unless I move as well the `file_files` directory to the `output` directory.

Thanks a lot for the attention!

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jspaezp** [comment]
related to: https://github.com/quarto-dev/quarto-cli/issues/690

**Comment by jspaezp** [comment]
I see, thanks for replying.

In that case would it be possible to have:
1. some form of feedback from the cli if incompatible arguments are passed? (raise error if input is a single file and --output-dir is passed)
2. extended description to make clear render can handle projects/directories, rn the description is `Render input file(s) to various document types.`
3. An example on the cli call to render a project right now it shows:

````
 Examples:

    Render Markdown:    quarto render document.qmd                  
                        quarto render document.qmd --to html        
                        quarto render document.qmd --to pdf --toc   
    Render Notebook:    quarto render notebook.ipynb                
                        quarto render notebook.ipynb --to docx      
                        quarto render notebook.ipynb --to pdf --toc 
    Render w/ Metadata: quarto render document.qmd -M echo:false    
                        quarto render document.qmd -M code-fold:true
    Render to Stdout:   quarto render document.qmd --output -  
````

**Comment by jjallaire** [comment]
Yes, this definitely bears improvement! I've made the changes you suggested here: https://github.com/quarto-dev/quarto-cli/commit/5ac378b2e22f896eedeb78bbeaa5a915e2af8952

**Comment by jspaezp** [comment]
thats amazing, thanks a lot <3
