### ISSUE TITLE
Document RSS feed by categories

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2330]
I looked into this from a question in https://community.rstudio.com/t/setting-up-rss-feed-for-a-category-in-quarto-blog/146489/2

It seems from https://github.com/quarto-dev/quarto-cli/discussions/772#discussioncomment-2667075 that it is already possible to create RSS feed by categories. Right @dragonstyle ? 

If so we may need to update our documentation to explain that : https://quarto.org/docs/websites/website-blog.html#rss-feed

Just opening to track this when we plan a documentation sprint.

**Comment by dragonstyle** [comment]
@cderv Correct on all accounts!
