### ISSUE TITLE
Building from source fails on Mac

### ISSUE THREAD

**Issue by wood-chris** [quarto-dev/quarto-cli#2332]
### Bug description

OS: macOS BigSur

Following the build instructions:

 - clone the repo
 - run `./configure.sh`

results in

```
error: Expected ';', '}' or <eof> at file:///opt/quarto-cli/src/resources/editor/tools/yaml/tree-sitter-yaml.json:1:8
+ return_code=1
+ set -e
+ [[ 1 -ne 0 ]]
+ echo 'deno vendor failed (likely because of a download error). Please run the configure script again.'
deno vendor failed (likely because of a download error). Please run the configure script again.
+ rm -rf vendor
+ mv vendor-2022-09-07 vendor
+ exit 1
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
This is unfortunately a bug in deno 1.25.1: https://github.com/denoland/deno/issues/15634

I thought I had disabled this vendoring on macOS, but clearly I have a bug on the configure.sh script, thanks for reporting. While the fix isn't it, you can temporarily work around it by changing the test on line 83.

**Comment by cscheid** [comment]
@wood-chris Thanks for the report! I fixed this on `main`, and confirmed both that the issue existed before the change and that it doesn't happen for me (on macOS ventura) after the change.
