### ISSUE TITLE
Hover tooltip broken for some citation styles

### ISSUE THREAD

**Issue by kjohnsen** [quarto-dev/quarto-cli#2340]
### Bug description

I am writing a book and I found that the HTML version's citation hover is broken when I use `nature.csl`. Maybe it's for all superscript citation styles?

To reproduce:
- create book
  ```shell
  quarto create-project hover-bug --type book 
  ```
- add `csl: science.csl` to `_quarto.yml`
  - `quarto preview`
  - go to intro page, note that mouse hover over ref brings up tooltip 😃 
- add `csl: nature.csl` to `_quarto.yml`
  - `quarto preview`
  - go to intro page, note that mouse hover over ref **does not** bring up tooltip 😢 

Here are the CSL files I used:
[styles.tar.gz](https://github.com/quarto-dev/quarto-cli/files/9509088/styles.tar.gz)

I'm running Quarto on WSL Ubuntu 18.04, on Windows 10

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
I think it is bug or missing feature. We don't handle correctly references styled like footnotes. 

Reproducible example with R to generate the citation file dynamically

````
---
title: "My Document"
format: html
csl: https://www.zotero.org/styles/nature
bibliography: ref.bib
---

```{r}
knitr::write_bib("knitr", "ref.bib")
```

See @R-knitr

````
![image](https://user-images.githubusercontent.com/6791940/189120863-17418dac-c5f9-40af-b1ff-d7d9a5a71150.png)

Even setting `footnote-hover: true` does not help.
