### ISSUE TITLE
Cell Attachments Are Duplicated In Jupyter Classic

### ISSUE THREAD

**Issue by hamelsmu** [quarto-dev/quarto-cli#2347]
## Issue:

Cell attachments are rendered by Quarto properly w/ Jupyter Lab but not Jupyter Classic

To reproduce this error:

1. Clone [this repo](https://github.com/hamelsmu/attachments_quarto), which is an minimal quarto project
2. Run quarto preview
3. Start **Jupyter Lab**, and in `nb.ipynb` add different cell attachments by taking several screenshots and pasting them into markdown cells directly.  Everything works in Quarto :tada:
4. Start **A Classic Jupyter Notebook (not Jupyter Lab)**, and do the same thing re: cell attachments in `nb-classic.ipynb`, Quarto will repeat the first cell attachment across all of them. 

Upon some investigation, it does indeed appear that Jupyter Lab and Jupyter Classic handle cell attachments differently, which could be causing the issue.  

### Questions:
1. Is Jupyter Classic supported in Quarto?
2. Is this something that is possible to fix?

I'm using quarto version `1.2.73` (pre-release) and `MacOS Monterey 12.5.1` 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/b6b8b377f4df879550fd09f282d1dd04bc74d359 and available in v1.2.100 (https://quarto.org/docs/download/prerelease.html)
