### ISSUE TITLE
Bad error message on invalid YAML

### ISSUE THREAD

**Issue by schochastics** [quarto-dev/quarto-cli#2349]
### Bug description

On my [quarto page](https://github.com/schochastics/quarto-schochastics), I have utterance activated on 2 docs. On these two pages I have the following in my yaml header which has worked at least until quarto 1.1.128 

``` yaml
comments:
  utterances:
    repo: schochastics/quarto-schochastics
    issue-term: pathname
    label: comment
    theme: photon-dark
    crossorigin: anonymous
```
Starting with quarto 1.1.178 I get this error when rendering

```
ERROR: Validation of YAML front matter failed.
ERROR: In file material/netVizR/index.qmd
(line 13, column 3 through line 18, column 26) Key comments has value utterances:
    repo: schochastics/quarto-schochastics
...
    theme: photon-dark
    crossorigin: anonymous, which must be 'false'
12: comments:
13:   utterances:
      ~~~~~~~~~~~
14:     repo: schochastics/quarto-schochastics
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
17:     theme: photon-dark
    ~~~~~~~~~~~~~~~~~~~~~~
18:     crossorigin: anonymous
    ~~~~~~~~~~~~~~~~~~~~~~~~~
19: ---

ERROR: Render failed due to invalid YAML.
```
I did not change any code just wanted to re-render after installing the new quarto version
I am running Ubuntu 20.04

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by schochastics** [comment]
yep that does the trick, thanks!

**Comment by cderv** [comment]
@cscheid Just wondering if we could / should try to improve the error message for a field that is not in the schema ? 

https://github.com/quarto-dev/quarto-cli/blob/bb2d57bdc278941b9df3c5533503e3caf432ed6d/src/resources/schema/definitions.yml#L127-L167

Current error seems to be 
```
crossorigin: anonymous, which must be 'false'
```` 
![image](https://user-images.githubusercontent.com/6791940/189109032-2fe7c49b-9351-4731-9e27-7fd3fe4061fc.png)

Not sure so hence I am asking before reopening or not. thanks !

**Comment by cscheid** [comment]
Yes, that error is atrocious. Thanks for flagging. Let me see if I can figure out why it's coming up like that.

**Comment by cscheid** [comment]
Previous error message:

```
ERROR: Validation of YAML front matter failed.
ERROR: In file issue-2349.qmd
(line 3, column 3 through line 8, column 26) Field "comments" has value

utterances:
  repo: schochastics/quarto-schochastics
...
  theme: photon-dark
  crossorigin: anonymous

The value must instead be 'false'.
2: comments:
3:   utterances:
     ~~~~~~~~~~~
4:     repo: schochastics/quarto-schochastics
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
7:     theme: photon-dark
   ~~~~~~~~~~~~~~~~~~~~~~
8:     crossorigin: anonymous
   ~~~~~~~~~~~~~~~~~~~~~~~~~
9: ---

ERROR: Render failed due to invalid YAML.
```

Yuck.

New error message:

```
ERROR: Validation of YAML front matter failed.
ERROR: In file issue-2349.qmd
(line 8, columns 5--16) property name crossorigin is invalid
7:     theme: photon-dark
8:     crossorigin: anonymous
       ~~~~~~~~~~~
9: ---
ℹ The error happened in location comments:utterances:crossorigin.
```

Yay! Pull request incoming.

**Comment by cderv** [comment]
🤯 so good ! Really cool improvement! 👏
