### ISSUE TITLE
`//| echo: fenced` option remains in rendered OJS code blocks

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#2353]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2344

<div type='discussions-op-text'>

<sup>Originally posted by **allisonhorst** September  8, 2022</sup>
Hi there! Thanks for everything you all do, Quarto is amazing!

I'm starting to work in some `{ojs}` cells in Quarto. When I use `#| echo: fenced` in R or Python blocks, it renders as expected, showing the fenced code delimiters but without showing the `#| echo: fenced` option within the rendered output. When I try `//| echo: fenced` in the `{ojs}` cell, the `//| echo: fenced` shows up in the rendered output. 

It works fine if `echo: fenced` is added in the YAML, so I'm only having this issue if it's added as an option in an individual {ojs} block. Not sure if I'm missing something or if this is unexpected. Thanks for any follow-up! </div>

**Comment by cscheid** [comment]
@allisonhorst Thanks for the report! I'm having a hard time reproducing this. Here's my attempt:

````
---
title: ojs fenced test
---

```{ojs}
//| echo: fenced
x = 8 * 3
x * x
```
````

This .qmd produces the following output:

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/285675/189174786-ba7ad028-6038-435a-a22e-74f006318fcf.png">

I'm also using the very latest version of quarto; can you share a document where you see the issue and also which quarto version you're running? Thanks.

**Comment by allisonhorst** [comment]
Thanks for taking a look! I think this is a misunderstanding on my part. 

Here's my [test](https://allisonhorst.github.io/ojs-fence-testing/ojs-fenced-1.html) doc (in [this repo](https://github.com/allisonhorst/ojs-fence-testing)). At that link, the `//| echo: fenced` does not show up (so is working as expected). 

*So sorry* that I'm sending a screenshot. Just to clarify where my confusion happened: when rendered through RStudio, the preview in the RStudio Viewer pane shows the `//| echo: fenced` (and no output):

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/25372780/189216957-e1fe5e0a-72d4-43dc-a72b-af910db728d1.png">

When I pop that out ("Show in new window"), it shows up as expected:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/25372780/189217066-7305f6e0-18a7-4f78-8883-257ce7b18b87.png">

So I was thrown off by the RStudio preview of the html differing from what appears in the html viewed elsewhere. It seems like it is working as expected, just the Viewer view in RStudio threw me.

**Comment by cscheid** [comment]
Oh, I'm so sorry, I should have noticed that earlier. The hint is in "Chrome/69.0.3497.128". The QtWebEngine versions of RStudio run a _really old_ version of Chrome (that's from a decade ago 😬). In general, you'll need the Electron builds of RStudio in order for OJS to be well-supported. If you want to stick to Spotted Wakerobin (2022.07), then you can grab the experimental Electron versions here: https://dailies.rstudio.com/rstudio/spotted-wakerobin/ (rightmost column)

If you are willing to run the actual RStudio dailies (codename Elsbeth Geranium, 2022.11), then they're all Electron by default, and then OJS works:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/285675/189220535-f97b9604-2a91-4699-9e8e-0222f615cf8a.png">
