### ISSUE TITLE
crossref inside a callout causes latex failure (but works fine in html)

### ISSUE THREAD

**Issue by dpastoor** [quarto-dev/quarto-cli#2354]
### Bug description

```
:::{.callout-note icon="false"}
## response

some text

![multiple versions of R](images/2022-09-08-09-09-16.png){#fig-multiple-version-r}

:::
```

in html looks fine

![image](https://user-images.githubusercontent.com/3196313/189132613-e10748f2-b996-47cf-ac94-d93e98588648.png)

but attempting to render to pdf results latex failure

```
compilation failed- error
LaTeX Error: Not in outer par mode.
```

by removing the callout block and the book renders fine

❯ quarto --version
1.1.189

running in vscode

>   This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

Mac OS

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Should be fixed in: 31e87e6bc022d143970a6a672946c5b581f65e71 - thx for reporting!

**Comment by dpastoor** [comment]
Thanks Charles!!

**Comment by dragonstyle** [comment]
Thanks for the followup. Can you give us some additional information about what you're seeing (e.g. are they failing to render, is there an error)? A sample document that reproduces the issue would be very helpful if you have that at your disposal. (The fix for this bug is very unlikely to have had any impact upon HTML cross refs as the change was implemented in a LaTeX post processor which doesn't execute for HTML output).

**Comment by ljcolling** [comment]
Sure, the following fails in html but passed in latex in v1.2.102. (But, it passed in html in v1.0.37, which is the most recent version I can find where it works, but there might be a more recent version)

```
You can use @exm-boids to explore how these three rules influence the simulated
flocking behaviour in birds.

::::{.callout-tip icon="false" appearance="simple"}

:::{#exm-boids}
#### Explore flocking behaviour 
:::

Use the sliders to make adjustments to each of the three rules that determine
flocking behaviour in the simulated birds.
::::
```

The error appears to be in the crossref.lua filter. Specifically

```
Error running filter /Applications/quarto/share/filters/crossref/crossref.lua:
/Applications/quarto/share/filters/crossref/crossref.lua:2128: attempt to index a nil value (local 'caption')
stack traceback:
	/Applications/quarto/share/filters/crossref/crossref.lua:1225: in function </Applications/quarto/share/filters/crossref/crossref.lua:1219>
```

**Comment by dragonstyle** [comment]
Perfect, ty! I will take a look and get this fixed!
