### ISSUE TITLE
Quarto not respecting twoside=semi for scrbook

### ISSUE THREAD

**Issue by flyaflya** [quarto-dev/quarto-cli#2362]
### Bug description

Trying to do a book layout with margin content always on the right-side:

Here is my `_quarto.yml` file:

```
project:
  type: book

book:
  title: "tempMWE"
  chapters:
    - index.qmd

bibliography: references.bib

format:
  pdf:
    keep-tex: true
    documentclass: scrbook
    classoption: [twoside=semi]
```

And here my `index.qmd`:
```
Here is a bunch of text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur gravida eu erat et fring. Morbi congue augue vel eros ullamcorper, eget convallis tortor sagitt 

::: {.column-margin}
some margin text shown correctly on right side
:::

{{< pagebreak >}}

Here is a bunch of text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur gravida eu erat et fring. Morbi congue augue vel eros ullamcorper, eget convallis tortor sagitt 

::: {.column-margin}
some incorrectly on left-side.
:::

Figures seem to always be placed correctly on the right side.
```

As can be seen from this screenshot, the twoside=semi option (last line of _quarto.yml) is not being respected; it should place all margin content on the right.  Is this a bug or am I doing this wrong?  Thx!!  The cut off margin content shown in below pic:
![image](https://user-images.githubusercontent.com/17184441/189186436-65868bd6-b2c9-4df9-b758-2cb29529b8ff.png)

Content on page 1 is displayed correctly:
![image](https://user-images.githubusercontent.com/17184441/189186170-933c438c-03ec-400c-8390-0ab8035e2b91.png)

Versions:
RSTUDIO (2022.07.0 Build 548).
Windows 10 Enterprise

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thanks for reporting this - I can reproduce this too, and we are definitely looking at the book class and making some assumptions about geometry that aren't working for this case. I'll take a look at what we can do to fix.
