### ISSUE TITLE
embed-resources works from command line, not from rstudio

### ISSUE THREAD

**Issue by mikerspencer** [quarto-dev/quarto-cli#2364]
### Bug description

Using embed-resources to contain output in a single html doesn't work when rendering from rstudio (2022.07.1 Build 554), but does work when using render on the command line (ubuntu 20.04): `quarto render test.qmd --output test.html`

````md
---
title: "param test"
format:
  html:
    embed-resources: true
editor: source
params:
  x: 10
  y: 0.5
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

* The param x is `r params$x`
* The param y is `r params$y`


```{r}
plot(rnorm(n = params$x,
           mean = params$y))
```
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mikerspencer** [comment]
Possibly related, just spotted this warning message in the terminal for a function I'm not using.

![Screenshot from 2022-09-08 18-52-31](https://user-images.githubusercontent.com/7642073/189192429-560db15d-4529-418f-9e1b-dc4402c30a93.png)

**Comment by cderv** [comment]
Thanks for the report. 

> Using embed-resources to contain output in a single html doesn't work 

What does not work exactly ? Just to be sure what to look for. 

> Possibly related, just spotted this warning message 

Looking through the code, I am seeing that we still have one place calling Pandoc with `--self-contained` 

https://github.com/quarto-dev/quarto-cli/blob/31e87e6bc022d143970a6a672946c5b581f65e71/src/command/render/render.ts#L436

I believe that may be why we still see this warning

````
[WARNING] Deprecated: --self-contained. use --embed-resources --standalone
````

However @mikerspencer I got the warning in RStudio and in terminal. Do you run the same Quarto version in RStudio and in Terminal ?

**Comment by mikerspencer** [comment]
Sorry for confusion - end of working day tiredness

When rendering from rstudio I get an html and a folder of images, etc.. When rendering from cli the images are embedded in the html. The latter is expected/desired behaviour.

How can I check which quarto version came bundled in rstudio? The cli version I installed today (1.1.189).

Cheers!

**Comment by cderv** [comment]
> How can I check which quarto version came bundled in rstudio? The cli version I installed today (1.1.189).

It should be the same IMO. Are you already using terminal inside RStudio ? If no, you could try `quarto --version` or `quarto check` inside the IDE terminal. 

> When rendering from rstudio I get an html and a folder of images, etc.. 

When I click the render button in the last IDE version (daily one 2022.11.0-daily+167) for the file `test.qmd`, I see a `test_files` folder created, but then removed. 

So for now I can't reproduce this behavior

**Comment by mikerspencer** [comment]
`quarto --version` in the IDE terminal is also 1.1.189. I was slightly surprised I needed to install it separately to access quarto outside the RStudio IDE. I suspect, like you, it's to do with a version difference.

Thanks for your help and feedback!

**Comment by cderv** [comment]
> I was slightly surprised I needed to install it separately to access quarto outside the RStudio IDE.

quarto is bundled inside the IDE but this is not added to your PATH. We bundle it by convenience for RStudio user, but you will be better served by installing the latest version independently. It will be put in your PATH, and this will be used also by RStudio. 

Sorry to ask again, but no sure I know the state to the issue as I can't reproduce. Do you still have the issue ? 

Step I did with quarto 1.1.189

* Be sure I don't have the `*_files` folder
* Copy your qmd from https://github.com/quarto-dev/quarto-cli/issues/2364#issue-1366749560 to `test.qmd`
* Click the render button in RStudio IDE
* See that `test_files` is created during the rendering, but then removed and not there at the end in the folder

**Comment by mikerspencer** [comment]
Very odd, I've just tried it in a fresh directory and don't get the issue either.

Hmm, I suspect this might be user error. But I'm not sure why. Given we can't replicate, I'll close. Thanks for your help.

**Comment by cderv** [comment]
Great! 

@dragonstyle made the switch to fix the warning  mentioned in https://github.com/quarto-dev/quarto-cli/issues/2364#issuecomment-1241072313 also in https://github.com/quarto-dev/quarto-cli/commit/2bf6e3182fec6b64f19608c993ff80d463194e6c

**Comment by IvanPalm** [comment]
I ma experiencing the same issue despite `embed-resources:true` in the YML header. I have tried both rendering with `Shift+Cmd+K` in RStudio IDE and with the command `quarto render test.qmd [--to html]`. As far as I can tell, the triggered behavior is exactly the same.   

I'm using `quarto 1.2` installed via conda-forge and `RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36`.

@cderv would you please confirm the versions you use to obtain self-contained html files? Thank you


<img width="1381" alt="Screenshot 2022-12-04 at 17 51 25" src="https://user-images.githubusercontent.com/46936982/205504228-d6068e8a-e546-47ed-83b9-97650f1958d3.png">

**Comment by cderv** [comment]
@IvanPalm What is exactly your Quarto version ? You can have it using `quarto --version` in your terminal. 

For the fixed mentioned above it should be 1.2.82 or above I believe. 

I believe the `r-quarto` you are mentioning is the R package of the same name found at https://anaconda.org/conda-forge/r-quarto equivalent of the CRAN version https://cran.r-project.org/web/packages/quarto/index.html 

You need to check the CLI version - Last one is available at https://quarto.org/docs/get-started/

**Comment by IvanPalm** [comment]
Thank you for the feedback @cderv. Your comments are all very relevant: I have made confusion between the `r-quarto` package I have installed through conda and the `quarto-cli` that I had installed through brew (see formula [here](brew_quarto)). While the first was up to date the latter lagged behind to version `1.0.32`. 

I have now updated `quarto-cli` to version `1.2.269`, which is the latest available both on Quarto website and on brew, and I am now able to produce self-contained html reports. Thank you for the hint!  


[brew_quarto]:https://formulae.brew.sh/cask/quarto

**Comment by review-blind** [comment]
I was able to reproduce the problem by setting the `cache: true` option in the YAML header. With this option, not only a "test_cache" folder but also the "test_files" folder will be created and the "test.html" file will not be self-contained. If I set `cache: false` neither folder will be created and the file is self-contained.

RStudio version: 2022.12.0 Build 353
Quarto version: 1.2.269
Windows 10

```
---
title: "param test"
format: 
  html:
    embed-resources: true
params:
  x: 10
  y: 0.5
execute:
  cache: true
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

* The param x is `r params$x`
* The param y is `r params$y`


```{r}
plot(rnorm(n = params$x,
           mean = params$y))
```

```

**Comment by andrewdolman** [comment]
Just to add. I was also having this problem. RStudio Version 2022.07.1+554 (full details below). Installing the latest Quarto fixed the problem. All other changes to YAML and opts_chunk did nothing.

RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 13_1_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

**Comment by r-leyshon** [comment]
Also experiencing this issue on quarto cli version 1.3.340 on mac-os. Renders fine when opened from the quarto render output_file path. Move the file elsewhere and css styling is lost. Tried the workarounds suggested above, upgrading, cache: false, knitr::opt_chunk$set, still no joy with embed-resources: true. Also tried the r quarto package with no joy. Exploring options for inline styling with html style tags hasn't resolved my need either.

Incase I've done something daft with the YAML:

```
---
title: "Foobar"
suppress-bibliography: true
format:
  html:
    embed-resources: true
execute:
  cache: false
---
```

I've found this to contrast with my expectations having used r markdown with self-contained: true for some time. Some guidance would be much appreciated.

**Comment by mcanouil** [comment]
@r-leyshon 
Could you share a small "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

Providing the YAML is not enough, for example, with the below document, it works just fine on MacOS using Quarto v1.3.340, _i.e._, I can move the file everywhere it works.

<details><summary>See example code for a Quarto document.</summary>

````qmd
---
title: "Foobar"
suppress-bibliography: true
format:
  html:
    embed-resources: true
execute:
  cache: false
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````

</details>

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by r-leyshon** [comment]
OK thanks for quick response. Your self contained example also worked for me, so there's some local issue I'm working out. Can't share unfortunately as in a private repo.
