### ISSUE TITLE
qmd won't run mixed Julia and Python blocks (to html) 

### ISSUE THREAD

**Issue by JMLuther** [quarto-dev/quarto-cli#2365]
### Bug description

In VSCode (v1.71.0) I'm trying to convert a .qmd file to html which contains both `Julia` and `python` code blocks.
This generates an html file that executes only the language block which is encountered first, and the second block is not executed. Reversing the order changes the language that succesfully runs.
I assume that you are supposed to be able to mix language code blocks, but maybe this is not meant to be supported yet?

system is Windows 10, Python3.10, Julia 1.8, Quarto CLI 1.1.165 
example below (wouldn't allow me to drop .qmd file):

```

 ---
title: "Quarto Basics"
format:
  html:
    code-fold: true
execute: 
  enabled: true

---

This example runs Python and Julia blocks in one file.


# Julia code
```{julia}
using Plots

plot(sin, 
     x->sin(2x), 
     0, 
     2π, 
     leg=false, 
     fill=(0,:lavender))
```
```
# python code 
```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Yes, this is unfortunate, but we can't really fix it. It comes ultimately from the fact that Jupyter notebooks run with a single kernel.
