### ISSUE TITLE
Display equations should not automatically create new paragraphs

### ISSUE THREAD

**Issue by capnrefsmmat** [quarto-dev/quarto-cli#2373]
### Bug description

In LaTeX, it's common to define display equations that are within one paragraph and do not create a new paragraph. For example, if I write

```latex
The conditional intensity function can be written as 
$$\lambda(t) = \lim_{\Delta t \to 0} \mathbb{E}\left[\frac{N(t + \Delta t) - N(t)}{\Delta t}\right],$$
where $N(t)$ is the counting measure.
```
this is all one paragraph, and "where" is not indented. (If we're using blank spaces between paragraphs instead of indentation, there'd be no extra space here.) That's great for treating equations as part of text. The same applies for HTML, although since HTML documents typically aren't indented, the effect isn't as noticeable since it just changes vertical spacing slightly.

In an Rmd file with Knitr, this works fine:

```
---
title: "Test"
output: pdf_document
indent: true
---

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempus iaculis interdum. Fusce ac pretium orci. The conditional intensity function can be written as
$$
\lambda(t) = \lim_{\Delta t \to 0} \mathbb{E}\left[\frac{N(t + \Delta t) - N(t)}{\Delta t}\right],
$$
where $N(t)$ is the counting measure.

New paragraph. Aliquam sit amet feugiat arcu, sit amet posuere justo. Maecenas maximus ex nec nibh maximus, a mattis nibh convallis. Donec hendrerit tortor at ex ultricies posuere. Vestibulum facilisis maximus eleifend. 
```

This knits to the following:

<img width="635" alt="Screen Shot 2022-09-08 at 7 19 16 PM" src="https://user-images.githubusercontent.com/711629/189242202-4b5c55bd-19b7-4add-aeed-926e6a407132.png">

On the other hand, consider this Qmd:

```
---
title: "Test"
format:
  pdf:
    indent: true
---

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempus iaculis interdum. Fusce ac pretium orci. The conditional intensity function can be written as 
$$\lambda(t) = \lim_{\Delta t \to 0} \mathbb{E}\left[\frac{N(t + \Delta t) - N(t)}{\Delta t}\right],$$
where $N(t)$ is the counting measure.

New paragraph. Aliquam sit amet feugiat arcu, sit amet posuere justo. Maecenas maximus ex nec nibh maximus, a mattis nibh convallis. Donec hendrerit tortor at ex ultricies posuere. Vestibulum facilisis maximus eleifend. 
```

This renders to

<img width="586" alt="Screen Shot 2022-09-08 at 7 20 00 PM" src="https://user-images.githubusercontent.com/711629/189242258-b7e638a0-cd0b-4df1-8cae-643bfff75769.png">

In a math-heavy text where you introduce lots of equations, this is a problem, particularly if you have pages with plots and figures and LaTeX messes with the vertical spacing to get the page to fill up; you can get unsightly gaps before and after equations.

Ideally, when exported to Markdown for Pandoc to render, there should be no blank lines before and after `$$`, so that the equation is treated as part of the paragraph.

Oddly, if I use `\begin{equation*}` and `\end{equation*}` (or other math environments) instead of `$$`, this works correctly, and the equation is part of the same paragraph.

Versions: Quarto 1.1.189, TeX Live 2021, macOS 12.5.1; happens from CLI or RStudio, so not an RStudio thing

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Agreed that this isn't right. I think I know what's causing it.

**Comment by cscheid** [comment]
I can't reproduce this. On the latest version of quarto, your test example generates the following pdf for me:

<img width="738" alt="image" src="https://user-images.githubusercontent.com/285675/189409036-b9c97125-5313-4159-8e94-763cc613ae7c.png">

```
$ quarto tools check
[✓] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Up to date        v2022.09      v2022.09
```

Can you confirm the issue on our latest pre-release? Thanks.

**Comment by capnrefsmmat** [comment]
I can confirm that on Quarto 1.2.81, this problem seems to be gone, thanks. But I did find another rendering issue, so I'll open a separate issue for that.

**Comment by capnrefsmmat** [comment]
Ah, that issue is #2166, so no need to open anything.

**Comment by cscheid** [comment]
Got it. I apologize, though, that a full fix for that one will take 3-4 weeks because it's entangled with some other work we're doing.

**Comment by Voorhoeve** [comment]
I would like to reopen this issue. 
Using quarto 1.9.37 with this qmd script:
```
---
title: "Issues test"
format: pdf
indent: true
---

## Heading

Paragraph text, should not be indented because after heading.

Next paragraph, should be indented. Then the equation

$$y=w\times x,$${#eq-x}

with $w$ the weight of $x$. This paragraph should not be indented.
```
Renders to this:

<img width="950" height="244" alt="Image" src="https://github.com/user-attachments/assets/8742b2ed-91a0-4a72-ac77-4431e86cceed" />

The last line in the output should not be indented.

It is not clear from the quarto documentation what happens exactly when I hit 'render' in R-studio 2026.05.0 Build 218. I see a background job gets created with `quarto preview file.qmd --to pdf` and some julia engine, pandoc and lualatex engine are used, but don't know where to change stuff.

Starting the last line with `\noindent' is a temporary solution, but not for a whole book. Using the lua filter from [https://github.com/dialoa/first-line-indent](https://github.com/dialoa/first-line-indent#readme) and adding the following to the yaml  doesn't solve the problem:

```
filters:
  - first-line-indent
first-line-indent:
  remove-after: Math
```

**Comment by mcanouil** [comment]
@Voorhoeve We don't reopen issues, especially 4-years old ones. Please follow the guidelines and eventually open a new issue using the templates.

This being said, your document has empty lines, so paragraph breaks, somehow you expect two identical syntax to behave differently conditionally to an equation, i.e., you technically wrote four paragraphs in your example (use `format: native` and you'll see them).

```qmd
---
title: "Issues test"
format: pdf
indent: true
---

## Heading

Paragraph text, should not be indented because after heading.

Next paragraph, should be indented. Then the equation
$$y=w\times x,$${#eq-x}
with $w$ the weight of $x$. This paragraph should not be indented.
```

**Comment by Voorhoeve** [comment]
Ok thank you, clear!
