### ISSUE TITLE
`project.execute-dir: file` isn't respected

### ISSUE THREAD

**Issue by Victor-Botelho** [quarto-dev/quarto-cli#2376]
### Bug description

If I have a project setup like this:

Structure:
```bash
.
|____quarto_files
| |____example.qmd
|_____quarto.yml
```

With `_quarto.yml` having the following configuration:

```yaml
project:
 title: GitHub Issue
 execute-dir: file
 render: 
  - "**/*.qmd"

format: gfm
```

And `example.qmd` being the following:

````bash
---
jupyter: python3
---

```{python}
import os

print(os.getcwd())
print(os.environ['QUARTO_PROJECT_DIR'])
```
````

when I render the project in its root directory with `quarto render`, the output of both print commands from the python cell will be `/home/victor/project`, meaning the code was executed at the projects root directory, not at the file location, as specified by the `execute-dir`.

VERSIONS
Quarto: 1.1.149
OS: Ubuntu 20.04.3 LTS

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by Victor-Botelho** [comment]
UPDATE: After trying a few more tweaks, I realized that this behavior is even more strange. I'm considering the output of `print(os.getcwd())` as the "answer":
* If you create the project with `project.execute-dir: file`, it will run correctly on the first try;
* Changing the parameter to `project.execute-dir: project` will instantly yield the correct results as well;
* After changing the same parameter back to `file`, the output will now be wrong, pointing at the project directory;
* After some time waiting, if you again with the `file` parameter, the output will be correct, but only if you wait a few minutes.

For more context, I am editing the `._quarto.yml` file using Vim, and analysing the result by running `cat quarto_files/example.md`, which is the rendered file.

**Comment by jjallaire** [comment]
Thanks for reporting this! I think the strange behavior resulted in the fact that we keep a daemon running with the kernel (to eliminate the 2 or 3 second kernel startup time for interactive use) and it wasn't switching back to `file`. This is fixed here: https://github.com/quarto-dev/quarto-cli/commit/34690d79dd51be19c75f4ec0d135dd5d7065a1a6

**Comment by Victor-Botelho** [comment]
I am still observing the same behavior described in the issue even after having updated to Quarto 1.1.242.

**Comment by jjallaire** [comment]
Sorry I failed to mention that you need to update to the pre-release version of v1.2, which you can download here: https://quarto.org/docs/download/prerelease.html

**Comment by Victor-Botelho** [comment]
Oh, sorry! My bad! Thank you very much!
