### ISSUE TITLE
Bibliography Items are Repeated Twice

### ISSUE THREAD

**Issue by iandol** [quarto-dev/quarto-cli#2393]
### Bug description

I'm not quite sure what is going on, but for fairly basic documents, I see the Bibliography items place twice:

![Screenshot 2022-09-10 at 15 37 50_SMALL](https://user-images.githubusercontent.com/153905/189488468-f83293ca-1a82-4166-8a2d-f1223750e016.png)

I am using macOS 12.5.1 and Quarto 1.1.189 — here is the minimal QMD (save as `RefTest.qmd`) to generate this, I run the command `quarto render RefTest.qmd --to html`:

```markdown
---
title: "Quarto Workflow"
author: 
  - name: Jane Doe
    email: jane@doe.org
    corresponding: true
    affiliations:
      - International Cephalopod Research Institute (ICRI), Pacific Ocean.
  - name: John Doe
    email: john@doe.com
    affiliations:
      - Center for Advanced Octopod Studies (CAOS), Atlantic Ocean.
citeproc: true                # use citeproc for bibliography
bibliography: Refs.json
---

# Abstract #

[This sample project shows a workflow using the Quarto scientific publishing system run using the Scrivener Compiler]{.smallcaps}. [Quarto](http://quarto.org) utilises [Pandoc](http://pandoc.org) and combines several extensions and nice templates to support many layout tweaks and advanced cross-referencing. Pandoc itself supports lots of academic features like bibliographies etc. 

# Introduction #

> *“We don’t see things as they are, we see them as we are.” — Anaïs Nin*

[Lørem ipsum dolør sit amet (this should be underlined)]{.underline}, eu ipsum movet vix, veniam låoreet posidonium te eøs, eæm in veri eirmod [@barrett2015; @crivellato2007]. Sed illum minimum at 3.25×10⁻⁴⁸, est mægna alienum mentitum ne. [Amet equidem](https://pandoc.org/MANUAL.html) sit ex. Ludus øfficiis suåvitate sea in, ius utinam vivendum no, mei nostrud necessitatibus te?  

Sint meis quo et, vis ad fæcete dolorem! Ad quøt moderatius elaboraret eum[@simmons2013; @siegel2015], pro paulo ridens quaestio ut! Iudico nullam sit ad, ad has åperiam senserit conceptåm? Tritani posidonium suscipiantur ex duo [@copenhaver2014], meæ essent mentitum ad. Nåm ex mucius mandamus, ut duo cåusae offendit laboramus [@hoffman2014]. Duo iisque sapientem ad, vølumus persecuti vix cu, **_his åt justo putant comprehensam (strong emphasis)_**.  

```

The references in CSLJSON format are here: 

[Refs.json.zip](https://github.com/quarto-dev/quarto-cli/files/9540631/Refs.json.zip)

Note: if I run Pandoc [`pandoc --citeproc --bibliography=Refs.json -f markdown -t plain RefTest.qmd`] on the same file I don't see any duplication problem.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I was able to reproduce this - it appears to be caused by explicitly adding `citreproc: true` to the document (I'm not sure why!). You can remove that line from the document (we use citeproc by default anyhow) to workaround the issue while I fix the underlying problem for the next release.

Thanks for reporting this!

**Comment by iandol** [comment]
Gosh, such a fast fix, what are guys on!? 

Thanks!!!
