### ISSUE TITLE
quarto background job runs too long in the background

### ISSUE THREAD

**Issue by samperman** [quarto-dev/quarto-cli#2414]
### Bug description

This was an issue we discovered on RStudio Cloud but would apply to any RStudio Workbench installation.

Once a user renders a quarto document, the background job that starts to support the preview will run until killed. This will prevent the user's workbench session from going idle.

This was observed on RStudio Workbench version 2022.07.1-554.pro3 with Quarto version 1.1.179 on Ubuntu Focal.

One thought we had was a way to configure a maximum amount of time that the job is allowed to run but I'm sure there are other alternatives.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by allenmanning** [comment]
@samperman We triaged this and would suggest that you consider something on your end:
- killing the process on your end
- rstudio could control the suspend and decide that preview servers aren't a reason to stay alive

Preview servers are not a reason to stay alive.  This seems like something RStudio could do.

**Comment by jjallaire** [comment]
I took a shot at having RStudio NOT prevent suspend when a Quarto job is running:

https://github.com/rstudio/rstudio/compare/feature/preview-job-transient

Unfortunately this is not enough to actually prevent the suspend, since there is a general check of the processSupervisor for any child process that the preview process gets caught up in as well. I don't feel confident about changing that code correctly.

**Comment by kippandrew** [comment]
@jjallaire Can you transfer this issue to rstudio-pro?

**Comment by kippandrew** [comment]
This can be closed. We have filed an IDE issue instead.
