### ISSUE TITLE
`out-width` and `out-height` for latex figures can't be set to `\textwidth`

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2417]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2415

<div type='discussions-op-text'>

<sup>Originally posted by **shabbychef** September 12, 2022</sup>
It seems that the options
```
#| out-width: "0.5\\textwidth"
#| out-height: "0.32\\textwidth"
```
have no effect on .pdf output: the figure is not half sized; when I save the intermediate .tex file, there are no "textwidth" in the doc, _etc_. 
Is this expected? How should one set the output figure width in pdf output?</div>

**Comment by cderv** [comment]
Our doc mentions the same description as **knitr** options (https://quarto.org/docs/reference/cells/cells-knitr.html#figures)
> Width of the plot in the output document, which can be different from its physical fig-width, i.e., plots can be scaled in the output document. Depending on the output format, this option can take special values. **For example, for LaTeX output, it can be .8\\linewidth**, 3in, or 8cm; for HTML, it can be 300px or 50%.

However, this does not work 

````markdown
---
title: "Untitled"
format: latex
keep-md: true
---

```{r}
#| label: main-plot
#| out-width: 0.5\\textwidth
plot(mtcars)
```
````

Markdown will be
````markdown
![](test2_files/figure-latex/main-plot-1.pdf){width=0.5\\textwidth}
````

Latex will be 
````latex
\includegraphics{test2_files/figure-latex/main-plot-1.pdf}
````

however, this is not something supported by Pandoc. In **knitr**, when `out.width` is used, a special plot hook is used which writes LaTeX directly. 
https://github.com/yihui/knitr/blob/59cf48204a866a2046f00ff6f8a8ca386e2cf563/R/hooks-md.R#L10-L15

We only use a markdown plot hook in Quarto I believe.

**Comment by jjallaire** [comment]
This is definitely something we intended to make work. It looks like we currently never take over the injection of `\includegraphics` from Pandoc, but we actually should whenever there is a `width` attribute (since Pandoc will drop this on the floor).

**Comment by fisher-j** [comment]
I'm not sure if its related, but I also don't see any change in the output when attempting to use `#| fig-width: 3` from in a jupyter lab notebook with `format: pdf` in the yaml block. Similarly, this doesn't have any effect.
```
---
format: 
  pdf:
    fig-width: 3
---
```
Are jupyter notebook cell outputs supposed to respond to these settings?

**Comment by dragonstyle** [comment]
Pandoc does properly handle markdown widths, but not when passed as raw LaTeX as in this example. Here is how widths are handled by Pandoc:

> The width and height attributes on images are treated specially. When used without a unit, the unit is assumed to be pixels. However, any of the following unit identifiers can be used: px, cm, mm, in, inch and %. There must not be any spaces between the number and the unit.

So we should suggest that users write:

````
---
title: "Untitled"
format: latex
keep-md: true
---

```{r}
#| label: main-plot
#| out-width: 50%
plot(mtcars)
```
````

Which will generate correct sizing in multiple formats (e.g.):

```
<img src="test_files/figure-html/main-plot-1.png" class="img-fluid" style="width:50.0%">

\includegraphics[width=0.5\textwidth,height=\textheight]{test_files/figure-latex/main-plot-1.pdf}
```

**Comment by cderv** [comment]
@dragonstyle How do we update the doc about this ? (https://quarto.org/docs/reference/cells/cells-knitr.html#figures)

I open the issue initially to point that we have a difference in treatment from using **knitr** in **rmarkdown**, and in Pandoc. 
In R Markdown, you can pass unit in LaTeX as we handle the creation of the `\includegraphics` creation instead of letting Pandoc do it. In **rmarkdown**, we do that with **knitr** plot hooks and we don't use those in Quarto. 

I thought this is something we could somehow support maybe within Lua processing to bypass Pandoc's writers but I understand here that we don't want to touch the generation of images and let Pandoc always do it, right ?

**Comment by dragonstyle** [comment]
Thank you! Those docs do need to be updated! (I will do it :) ).

We could support this for sure, I just think it is better to really encourage users to author format agnostic metadata any time we can. That will means sizes can be supported across formats rather than being wound up in the specific LaTeX expression...

**Comment by cderv** [comment]
>  I just think it is better to really encourage users to author format agnostic metadata any time we can.

Definitely agree with that. 

So it is an issue with two conclusions: 

* We need to document some of the knitr options differently, than what could be in  the knitr reference page: (https://yihui.org/knitr/options/) 
* We could keep this as feature request in any case we need to support more complexe LaTeX figures that would require bypassing the Pandoc writers for figures. (if we don't do that already). 
**knitr** does this for a subset of options that otherwise Pandoc would not handle correctly (or does not know how I think - until support for Figure in Pandoc AST is better I guess)

**Comment by eyayaw** [comment]
Do you happen to have any updates on this? 

```markdown
---
title: "Customize out-width in multi-plot layouts"
format: 
  pdf:
    keep-tex: true
---

::: {#fig-elephants layout-ncol="2" width="49%"}
![Surus](https://github.com/quarto-dev/quarto-web/blob/main/docs/authoring/_figure-examples/surus.png?raw=true){#fig-surus}

![Hanno](https://github.com/quarto-dev/quarto-web/blob/main/docs/authoring/_figure-examples/hanno.png?raw=true){#fig-hanno}

Famous Elephants
:::

::: {#fig-elephants-1 layout-ncol="2"}
![Surus](https://github.com/quarto-dev/quarto-web/blob/main/docs/authoring/_figure-examples/surus.png?raw=true){#fig-surus-1 width="97.5%"}

![Hanno](https://github.com/quarto-dev/quarto-web/blob/main/docs/authoring/_figure-examples/hanno.png?raw=true){#fig-hanno-2 width="97.5%"}

Famous Elephants 1
:::
```

**Custom widths are completely ignored on pdf output**. 

<details>
<summary> Generated tex</summary>

```tex

\begin{figure}

\begin{minipage}[t]{0.50\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{out-width_files/mediabag/surus.png}

}

}

\subcaption{\label{fig-surus}Surus}
\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{out-width_files/mediabag/hanno.png}

}

}

\subcaption{\label{fig-hanno}Hanno}
\end{minipage}%

\caption{\label{fig-elephants}Famous Elephants}

\end{figure}

\begin{figure}

\begin{minipage}[t]{0.50\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{out-width_files/mediabag/surus.png}

}

}

\subcaption{\label{fig-surus-1}Surus}
\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{out-width_files/mediabag/hanno.png}

}

}

\subcaption{\label{fig-hanno-2}Hanno}
\end{minipage}%

\caption{\label{fig-elephants-1}Famous Elephants 1}

\end{figure}
```
</details>

**Comment by cderv** [comment]
@eyayaw can you open a new issue please ? 

This one is almost 1 year old and we had a number of new version since then. 

We can then discuss the usage and its issues in its own new thread. Thank you !

**Comment by eyayaw** [comment]
> @eyayaw can you open a new issue please ?
> 
> This one is almost 1 year old and we had a number of new version since then.
> 
> We can then discuss the usage and its issues in its own new thread. Thank you !

Thanks, @cderv. I created a new issue under #7074.
