### ISSUE TITLE
Wrong title for PDF table of contents

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#243]
Rendering the book template to PDF with quarto 0.2.423 produces a table of contents with title "On this page", which doesn't make sense for a PDF.

**Comment by jjallaire** [comment]
Thanks! Fixed here: https://github.com/quarto-dev/quarto-cli/commit/24707d6b1749d148b943e9bd362a711f8f93b3e1

**Comment by knuesel** [comment]
Awesome, thanks!
