### ISSUE TITLE
Infinite loop in `quarto preview`

### ISSUE THREAD

**Issue by jph00** [quarto-dev/quarto-cli#2435]
### Bug description

In the following repo:

https://github.com/jph00/test-loop-preview

...typing `quarto preview` and then `touch index.ipynb` in another terminal results in an infinite loop. 

```
Executing 'index.ipynb'
  Cell 1/2...Done
  Cell 2/2...Done

pandoc
  to: html
  output-file: index.html
  standalone: true
  title-prefix: test-evaluate-code-3
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  pagetitle: test-evaluate-code-3
  document-css: false
  link-citations: true
  date-format: long
  lang: en


Executing 'index.ipynb'
  Cell 1/2...Done
  Cell 2/2...Done

pandoc
  to: html
  output-file: index.html
  standalone: true
  title-prefix: test-evaluate-code-3
  section-divs: true
  html-math-method: mathjax
[...]
```

```
$ uname -a
Darwin jhair.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:25 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8110 arm64
```

```
$ quarto --version
1.2.101
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
Thanks for the report. I can reproduce this also.
