### ISSUE TITLE
Wrong spanish translation of propositions

### ISSUE THREAD

**Issue by asalber** [quarto-dev/quarto-cli#2436]
### Bug description

Using a proposition environment with `:::{#prp}` I get the spanish translation `Propocición` that is not correct. The correct translation is `Proposición`.

Example.

```
---
lang: es
---

:::{#prp-my-proposition}
Proposición de ejemplo.
:::
```

quarto version 1.1.189 on Arch linux

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
Thanks for the feedback. I believe this has been fixed, among other tweaks in https://github.com/quarto-dev/quarto-cli/pull/2069 which is available in pre-release v1.2.69+ 

You can either
* Download latest pre-release https://quarto.org/docs/download/
* Change the default value in your YAML for your project with current stable release 1.1 while waiting for future stable 1.2 https://quarto.org/docs/authoring/language.html#alternate-language

I'll close this, but thanks a lot for the report! Very much appreciated !
