### ISSUE TITLE
`output-file` shouldn't take paths

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#2440]
Instead of generating bad output, we should issue an error.

The real bug is here: #2266 . The fix for it is quite tricky, so we should at least disallow this broken usage for the moment.

**Comment by wlandau** [comment]
Will paths be possible again at some point? I find this to be a reasonable expectation and important for downstream tools, e.g. https://github.com/ropensci/tarchetypes/discussions/129.

**Comment by cscheid** [comment]
We hear and understand that they're an important feature. We have a plan. We need to implement it, and then check how bad the breakage will be if we do that.

Currently, our recommendation is the following workaround:

1. use a prerender script to copy the .qmd file to wherever the output path would be
2. render from there
3. remove the copied .qmd file

It's easy to see some pitfalls issues with this approach, and they are precisely the same as our implementation plan:

- your execution paths will change
- you need to be mindful of where you copy the file to, and not overwrite other files (including temporaries!)

Our previous implementation was a brittle, confusing, and ineffective hack. 

I understand and agree that they're a reasonable expectation! The central issue we are facing here is that different reasonable people have different, incompatible, reasonable expectations for the behavior :)
