### ISSUE TITLE
Docx callout images don't scale properly when DPI is set

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#2450]
### Bug description

![Screenshot from 2022-09-15 17-15-20](https://user-images.githubusercontent.com/1506457/190365655-16e4f2ef-7e83-4afa-bde5-337c2de36070.png)

The small example at https://gitlab.com/raniere-phd/quarto-document-template (output in the screenshot above) produces the callout image in DOCX too small.

Small Quarto file: https://gitlab.com/raniere-phd/quarto-document-template/-/blob/main/inst/index.qmd

Render log: https://gitlab.com/raniere-phd/quarto-document-template/-/jobs/3032161518

Environment information

```
$ quarto check
[✓] Checking Quarto installation......OK
      Version: 1.2.108
      Path: /opt/quarto/bin
[✓] Checking basic markdown render....OK
[✓] Checking Python 3 installation....(None)
      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/
[✓] Checking R installation...........OK
      Version: 4.1.3
      Path: /opt/conda/lib/R
      LibPaths:
        - /opt/conda/lib/R/library
      rmarkdown: 2.16
[✓] Checking Knitr engine render......OK
$ quarto tools check
[✓] Inspecting tools
Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.09
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I can verify this with a minimum working example of:

```markdown

---
title: "Untitled"
format:
  docx:
    dpi: 300
---


:::{.callout-warning}

## Test Callout

This is a test callout that verifies the sizing of items.

:::

```

**Comment by rgaiacs** [comment]
@dragonstyle Thanks for the minimum working example. :+1: I never imagine that `dpi` would be the source of the bug.

**Comment by dragonstyle** [comment]
No worries, I was perplexed myself! I'm hoping this won't be bad to fix so will try to get it soon...
