### ISSUE TITLE
Reference citation should be in the margin for this example

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2451]
I believe this example is not working as reference is shown on hover and not in the margin 
![image](https://user-images.githubusercontent.com/6791940/190372019-aa0e4ff9-49ff-47a3-bfc8-f2f0b4302c73.png)

where the doc says
> As an example, when I cite Xie, Allaire, and Grolemund ([2018](https://quarto.org/docs/authoring/article-layout.html#ref-xie2018)), the citation bibliography entry itself will now appear in the margin.

Or maybe it is but far away below... in there: https://quarto.org/docs/authoring/article-layout.html#options-reference

![image](https://user-images.githubusercontent.com/6791940/190372447-dbf0576b-d967-4633-8c43-a22f55f42ebf.png)

**Comment by dragonstyle** [comment]
Are you still able to reproduce this @cderv ? I can't seem to, though I have a couple of theories. If you can reproduce it still, do you mind providing OS + browser you're using (and for bonus points, checking the developer tools console of your browser for a JA error that may be silently lurking)?

**Comment by cderv** [comment]
I have seen this problem in the documentation website initially, here is what I see on Windows on Chrome: 

* The citation referenced is here: https://quarto.org/docs/authoring/article-layout.html#margin-content
![image](https://user-images.githubusercontent.com/6791940/191684128-97ec9155-8940-4b85-87b8-72bff97fbd67.png)

* And it is put in the margin way below, with messed up content in the margin: https://quarto.org/docs/authoring/article-layout.html#options-reference
![image](https://user-images.githubusercontent.com/6791940/191684267-a5c5955b-a343-4497-9438-f6b174b04236.png)

Interesting things is that when I open the developer tools, it will now all show things correctly 

![image](https://user-images.githubusercontent.com/6791940/191684640-2921cf34-cbc4-433a-abfd-53b4a4851760.png)

![image](https://user-images.githubusercontent.com/6791940/191684514-0deec3cc-44f9-4392-a192-be7c5228c2b0.png)

![image](https://user-images.githubusercontent.com/6791940/191684573-948e3c65-4b51-4187-bfcb-c8158ba15cb6.png)

So I am now thinking it was a Cache issue because I got cache disable by default when devtools open 
![image](https://user-images.githubusercontent.com/6791940/191685214-7b47bda7-baeb-47cd-a3ab-b94976a3f978.png)

What do you think ?

**Comment by dragonstyle** [comment]
I think the cache is definitely a possible culprit as I made a change in 1.2 that addresses exactly this type of issues for Chrome / Firefox specifically (specific reload scenarios would somehow cause the layout to get mangled in this way). Now in theory if you have the most recent version cached you should never see that again (the bug would occur when navigating to an anchor after you had loaded the page - e.g. load the page, copy one of the anchor links, paste it in address bar and hit enter).

**Comment by cderv** [comment]
OK great. I'll close this then.
