### ISSUE TITLE
Adds .yml translation for Russian

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [quarto-dev/quarto-cli#246]
Reviews and suggestions are welcome, if possible. 
https://github.com/quarto-dev/quarto-cli/pull/245

Currently there are several  questionable lines: 

15: `code-tools-show-all-code: "Просмотр кода страницы"` makes sense only if this button shows the entire webpage HTML/JS code, identical to "View page source" in browser. 

30, 31: a) As far as I understand, when knitting there will be a line `"X <phrase>"`, where `X` is a number of lines in a document and `<phrase>` is a selected translation for the `"search-more-matches-text"`. Such an expression is pretty odd, the better is literally `"More X matches in this document"`, i. e. I would like X to split the phrase. 
b) Another issue is that the count form for the word `matches` depends on number: viz. I would prefer to write 
"X дополнительный результат в этом документе" for X = 10m+1, where m is 0 or natural. 
"X дополнительных результат**а** в этом документе" for X = 10m+2, 10m +3, 10m + 4  and 
 "X дополнительных результат**ов** в этом документе" otherwise.
So far, the suggested variant (`"Дополнительных результата(-ов) в этом документе"`) encompasses two latter cases as they are more frequent. 

53: I have never seen the word for 'lemma' (`лемма`) to be abbridged anyhow and cannot suggest any viable way to do this, however it is declinable and should turn into `лемме, леммы, лемму, леммой` respectively dependent on the context, which requires a morphotagger which I believe is far beyond the current scope of goals for the project. This is however an unimportant issue since such environments are hardly ever met in real documents.

**Comment by jjallaire** [comment]
`code-tools-show-all-code` does not show the page source, rather it reveals any hidden or collapsed code blocks on the page.

I agree that the numbering w/ `search-more-matches-text` is awkward. Why don't we just go with what you think it best for now and then we'll clean that up once we allow substitutions in localized text.

**Comment by gjirokastrelbasanit34** [comment]
Thank you for the reponse, then I believe it's better to leave it as-is with the enumeration. 

And there is one more thing that I just wanted to figure out: is the "Submit" button expected to be only in context of sending a Direct Message to somebody, or is it merely about publishing a comment, a note, i. a. on one's own webpage? 
Because the english word does not assume necessarily p2p "sending", rather it means general "text saving", but existing European localisations assume that this means the same as "to send to a person".

And I apologise for an off-top question, but doesn't `quarto-cli` currently have a cmd like `$ quarto update --self` which would download a "stable" version if I do not want to install a nightly build every time with `$ git clone`?

**Comment by jjallaire** [comment]
The Submit button is used to submit a website search (so it appears as a button on the right of a search box). That said, we provide that to algolia autocomplete however in the way we currently use algolia I'm not sure if it ever displays.

If you want to incrementally update a git cloned quarto you can just do a `git pull` in the same directory (this can also be used to run branches which is useful from time to time).

**Comment by gjirokastrelbasanit34** [comment]
Oh, this matters, if it is ever displayed I would recommend to change it to `Найти`. I would also question whether the European translations that all mean "send" fit, but I will come to this later.

**Comment by jjallaire** [comment]
Okay, I just made the change to Найти

**Comment by gjirokastrelbasanit34** [comment]
Thanks, now it looks brilliant.
