### ISSUE TITLE
Email subscription embed code file name displays on pages

### ISSUE THREAD

**Issue by rossheat** [quarto-dev/quarto-cli#2467]
The subscription box displays correctly on the index page:

<img width="327" alt="Screenshot 2022-09-16 at 16 43 01" src="https://user-images.githubusercontent.com/45441679/190677995-f35e1023-f4e9-45b9-90e7-da9cce95e823.png">

However, the file name which contains the code required to display the email subscription box shows on other pages:  
<img width="572" alt="Screenshot 2022-09-16 at 16 43 32" src="https://user-images.githubusercontent.com/45441679/190678386-08bde02c-86bb-4824-98c4-a525ab263e5b.png">

The file is named `subscribe.html` and is at the root of my project:

<img width="167" alt="Screenshot 2022-09-16 at 16 45 45" src="https://user-images.githubusercontent.com/45441679/190678490-be26449e-ffb3-466e-ba64-bc2f42340c61.png">

And I have added the file name to `_quarto.yml`: 
```
website:
  margin-header: subscribe.html
```

As per the [docs](https://quarto.org/docs/websites/website-blog.html#subscriptions)

quarto version 1.1.189

**Comment by rossheat** [comment]
A quick fix in `styles.css` while we wait for quarto v1.2: 
```
div.margin-header-item > p {  
   display: none;
}
```

**Comment by dragonstyle** [comment]
If you're brave the prereleases of 1.2 are around here:

https://quarto.org/docs/download/prerelease.html
