### ISSUE TITLE
Mapshot and quarto not playing together?

### ISSUE THREAD

**Issue by ericvmai** [quarto-dev/quarto-cli#2470]
### Bug description

I saw this issue brought up in the mapview discussion [here](https://github.com/r-spatial/mapview/issues/419). But the mapshot function does not seem to be playing well with quarto.  I am trying to render a quarto project to pdf and html. If I leave a leaflet map as-is and render then I get an image that looks like this:

![Screenshot 2022-09-16 174434](https://user-images.githubusercontent.com/30978780/190797950-85b096f7-7aa8-4768-9c21-3c92cf9e0d83.png)

I get the following error when I try correct this issue using mapshot with my leaflet map created.

Could not load c:%5CUsers%5Cericv%5CAppData%5CLocal%5CTemp%5CRtmpeixsB4%5Cfile46f0695b5cb1.html
Error in (function (url = NULL, file = "webshot.png", vwidth = 992, vheight = 744, :
webshot.js returned failure value: 1

Any help addressing this would be helpful in avoiding having to manually screenshot the map and save and then embed a png to the quarto doc!! See here: https://github.com/hdadvisors/chesterfield-market-analysis/blob/quarto-transition/part-1a-3.qmd#L121

I'm running on PC, Windows 11 Pro.  Running 2022.07.1 Build 554
"Spotted Wakerobin" Release (7872775e, 2022-07-22) for Windows

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Apologies for the long turnover time on this one. From the thread you linked, it seems that the recommendation is to upgrade and use mapshot2. Are you still experiencing trouble with this?
