### ISSUE TITLE
absolute image refs don't work for ipynb output in websites

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#2475]
### Bug description

Reported by @hamelsmu. If you include the `ioynb` format in a website absolute image references are not resolved (and result in a pandoc error). The same documents rendered to `html` do not exhibit the error.

Here is a minimal example repo: https://github.com/hamelsmu/quarto_nbcopy

In this repo, the following markdown results in an error when doing a `quarto render` of the entire site (which will pickup the `ipynb` renders):

````markdown
---
author: [Hamel Husain, Jeremy Howard]
date: 2022-07-28
image:  /images/card.png
description: Our favorite tool for software engineering productivity--nbdev, now re-written with Quarto
tags: [technical]
title: 'nbdev+Quarto: A new secret weapon for productivity'
---

_[Originally posted](https://www.fast.ai/2022/07/28/nbdev-v2/) on the fast.ai blog_

![A single notebook can create a python module, tests, CI, pypi/conda packages, and more.](/images/card.png)
````

This version (where the image paths are made relative) does work correctly:

````markdown
---
author: [Hamel Husain, Jeremy Howard]
date: 2022-07-28
image:  /images/card.png
description: Our favorite tool for software engineering productivity--nbdev, now re-written with Quarto
tags: [technical]
title: 'nbdev+Quarto: A new secret weapon for productivity'
---

_[Originally posted](https://www.fast.ai/2022/07/28/nbdev-v2/) on the fast.ai blog_

![A single notebook can create a python module, tests, CI, pypi/conda packages, and more.](../../../images/card.png)
````

Note that the absolute image reference does work in both cases within the YAML (`image` option) but fails in the body.

I know that we are doing some resource resolution in Lua (which in theory should pick this up) but we also have some resolution happening in HTML post-processors (which won't be run for ipynb). My suspicion is that we might be over-relying on the post-processing here and we need to make sure this all happens in Lua.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
This should be fixed in https://github.com/quarto-dev/quarto-cli/issues/2475
