### ISSUE TITLE
Generated feed error

### ISSUE THREAD

**Issue by mrtkp9993** [quarto-dev/quarto-cli#2479]
### Bug description

Hello,

I publish my blog with Quarto. I am getting error with generated XML RSS feed:

```
This page contains the following errors:
error on line 8 at column 30: xmlParseEntityRef: no name
Below is a rendering of the page up to the first error.
```

[Here](https://github.com/mrtkp9993/MyDsProjects/blob/main/docs/index.xml) is the generated XML feed. Error didn't change whether if I build with Rstudio or Quarto CLI.

Quarto version: 1.2.90
RStudio version: 2022.07.1 Build 554
OS: Win 10 Pro Version 10.0.19044 Build 19044

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mrtkp9993** [comment]
Found the problem source. The reason is `&` character.

**Comment by dragonstyle** [comment]
Thanks it sounds like we're missing some escaping - I'll have a look!

**Comment by dragonstyle** [comment]
Thanks for reporting this. It should be resolved here: bbb5a7ab9dcde9f57f984e4b8e8b3f111ca103ed

Build 1.2.126 has the fix: https://quarto.org/docs/download/prerelease.html

**Comment by mrtkp9993** [comment]
Thanks for the quick fix, but Download page for prerelease is empty for me:

![image](https://user-images.githubusercontent.com/17238910/190900420-28c1ef90-6a04-4d98-a1c9-27c069ff0643.png)

**Comment by dragonstyle** [comment]
Thanks for letting us know - should be available once again!

**Comment by mrtkp9993** [comment]
Thanks for the quick fix!
