### ISSUE TITLE
Error using LaTeX formulas in tables

### ISSUE THREAD

**Issue by Gabrielforest** [quarto-dev/quarto-cli#2481]
### Bug description

![image](https://user-images.githubusercontent.com/63704591/190884947-45036a1e-16c0-47b9-8f9d-040288ce4a94.png)
 Everything is right on the visual editor before rendering the pdf document, but I got the above error.

I am writing the formulas as follows:
`$Hd_2 = H d_1 * \left[\frac{ ( 1 - e ^ {\beta_1Id_1} ) ^ { \beta_2} } { ( 1 - e ^ {\beta_2Id_2} ) } \right]$`

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by rgaiacs** [comment]
@Gabrielforest Thanks for the message. Can you provide a copy of the code of your table? Click in "Source" in the edit pane to see the code.
