### ISSUE TITLE
Emojis don't show up in pdf

### ISSUE THREAD

**Issue by mhollanders** [quarto-dev/quarto-cli#2491]
### Bug description

Hi all,

I'm trying to include some emojis in a pdf document. The following code just yields white spaces where the emojis should be:

`--- from: markdown+emoji format: pdf pdf-engine: lualatex --- :house: :telephone_receiver:`

I've tried a few different pdf-engines and stuff. HTML works fine. Using the following RStudio on Mac OS 12.5.1.

RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_5_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

Regards,

Matt

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mhollanders** [comment]
Whoops... I haven't filed many GitHub issues and didn't realise it was in markdown. The code I ran was

`--- from: markdown+emoji format: pdf pdf-engine: lualatex :house: :telephone_receiver: :email:---`

**Comment by dragonstyle** [comment]
This is most likely a result of the font that is being used in the PDF not supporting those emoji. You can confirm by setting `keep-tex: true` and confirming that the TeX output properly contains this characters. For example, here is the body of the above document as LaTeX:

```tex
\begin{document}
\maketitle
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[breakable, boxrule=0pt, borderline west={3pt}{0pt}{shadecolor}, interior hidden, enhanced, frame hidden, sharp corners]}{\end{tcolorbox}}\fi

{🏠}

{📞}



\end{document}
```

**Comment by mhollanders** [comment]
Makes sense. Do you know which fonts have support for Emoji in pdf?
