### ISSUE TITLE
Figure concatenated to previous table in DOCX

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#2493]
### Bug description

Consider the following minimal working example

``````
---
title: "MWE"

format:
  docx: default
---

Some text

```{r}
#| echo: false
#| label: tbl-foo
#| tbl-cap: Some table
iris |>
  head() |>
  knitr::kable()
```

```{r}
#| echo: false
#| label: fig-bar
#| fig-cap: Mininal data visualisation.

plot(iris$Petal.Length, iris$Petal.Width)
```
``````

It produces

![Screenshot from 2022-09-19 10-22-56](https://user-images.githubusercontent.com/1506457/190940531-1f51dfac-0116-4069-818d-c7d3fb778828.png)

Please note that the figure is part of the table. This is more clear when the table spans two pages:

![Screenshot from 2022-09-19 10-25-26](https://user-images.githubusercontent.com/1506457/190940643-dfba2beb-197f-4724-9ded-ef25130c923b.png)

The expected behaviour was

![Screenshot from 2022-09-19 10-24-21](https://user-images.githubusercontent.com/1506457/190941009-819db9a3-ca99-4f71-a605-6f39183260ab.png)

where the figure outside the table.

## System Information

```
$ uname -srv
Linux 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022
$ quarto check
[✓] Checking Quarto installation......OK
      Version: 1.2.131
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[✓] Checking R installation...........OK
      Version: 4.1.3
      Path: /opt/conda/lib/R
      LibPaths:
        - /opt/conda/lib/R/library
      rmarkdown: 2.16

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
Thanks for the report. 

I can reproduce this with 1.2.45 too.  (by adding border on the default table in the output document - I did not have those by default. 

Here is the markdown we produce 
````markdown
---
title: "MWE"

format:
  docx: 
    keep-md: true
---



Some text


::: {#tbl-foo .cell tbl-cap='Some table'}
::: {.cell-output-display}
| Sepal.Length| Sepal.Width| Petal.Length| Petal.Width|Species |
|------------:|-----------:|------------:|-----------:|:-------|
|          5.1|         3.5|          1.4|         0.2|setosa  |
|          4.9|         3.0|          1.4|         0.2|setosa  |
|          4.7|         3.2|          1.3|         0.2|setosa  |
|          4.6|         3.1|          1.5|         0.2|setosa  |
|          5.0|         3.6|          1.4|         0.2|setosa  |
|          5.4|         3.9|          1.7|         0.4|setosa  |
:::
:::

::: {.cell}
::: {.cell-output-display}
![Mininal data visualisation.](test2_files/figure-docx/fig-bar-1.png){#fig-bar}
:::
:::

````

We should definitely make sure that figures is not merged in previous table 

Converting with Pandoc only with this markdown gives the correct separation of both.
