### ISSUE TITLE
Tweak anchored sidebar overflow CSS

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#25]
With an anchored sidebar, the CSS shows:

```
.overflow-scroll {
	overflow: scroll !important;
}
```

I think this is causing the horizontal bar at the bottom of the sidebar here:
<img width="590" alt="Screen Shot 2021-04-23 at 10 26 33 AM" src="https://user-images.githubusercontent.com/12160301/115908126-9cb4c980-a41e-11eb-90b4-f5315807163a.png">

Changing this to:
```
.overflow-scroll {
	overflow-y: scroll !important;
	overflow-x: auto;
}
```

Keeps the y axis scroll but (I believe) will only keep the x axis scroll if someone enters text that is too long:

<img width="1352" alt="Screen Shot 2021-04-23 at 10 29 22 AM" src="https://user-images.githubusercontent.com/12160301/115908350-e998a000-a41e-11eb-8009-6a3d75615c52.png">

**Comment by jjallaire** [comment]
Should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/0f44faea52e9bb9577dcaf15b59a546d8c3aa8d3

@dragonstyle Could you review and close if this looks like the right fix?

**Comment by dragonstyle** [comment]
Yes looks good!
