### ISSUE TITLE
Markdown blocks handled incorrectly when code is runned with jupyter

### ISSUE THREAD

**Issue by benabel** [quarto-dev/quarto-cli#250]
I've encountered this strange bug, when there is code into a block _and_ the document needs to execute code with jupyter.

Here is a mwe.

<pre>
```{python}
for i in range(3):
    print(i)
```

#. Un processus est:

   - [ ] statique
   - [ ] dynamique

#. Un programme est:

   ```python
   print("CODE")
   ```

   - [ ] statique
   - [ ] dynamique
</pre>

Converts markdown loosing the _indentation_ of the blocks.

<pre>
1.  Un processus est:

-   [ ] statique
-   [ ] dynamique

1.  Un programme est:

``` python
print("CODE")
```

-   [ ] statique
-   [ ] dynamique
</pre>

If you remove any or the two code blocks(the executable or the other), markdown is correct. Of course this issue is propagated to all output formats `html`, `tex`...

**Comment by jjallaire** [comment]
Thanks for the report! This should be resolved here: https://github.com/quarto-dev/quarto-cli/commit/2d48fcad40acc5b9a4a511f5b135c599a7c05d98

**Comment by benabel** [comment]
@jjallaire This has been fixed. Five lines of code...  I was wondering to know why did you choose deno for this project, I begin to understand.

Thanks for the fix and the whole project. I'm using it on a daily basis to write my courses materials, this superset of pandoc is really awesome.

**Comment by jjallaire** [comment]
Great to hear that you are finding it so useful! Yes, Deno has worked out terrifically well. Being able to write high-performance code while using such a productive language + taking advantage of the universe of JS and WASM libraries is awesome.
