### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by piotrzientarski** [quarto-dev/quarto-cli#251]
How can I translate "Appendices" inscription?

**Comment by jjallaire** [comment]
That is an oversight -- we'll add a key for that in the next couple of days and ping this thread back once its available.

**Comment by gjirokastrelbasanit34** [comment]
Just to make it clear and elaborate on what is expected to be done: 
AFAIK, currently Appendix is neither an environment for Quarto (or even R Markdown), nor an insertable object, so I suppose we need a div like `:::{#app-<label> caption=}` which would expect either a figure or a table inside and the caption from the div should substitute the caption for a figure/table; a prefix, say `app` (or `append` as less confusing), and a `app-title` setting in cross-references section. Moreover, in Western literature appendices are normally enumerated with Latin letters even if figures are not, so `app-labels` settings is needed. Finally, these appendices need to be included into the table of contents.


Another dream-idea is  that at least for PDF output, an `\appendix` cmd would also be available in `.qmd`, which interprets all following h2-headings as appendices, h3 as subappendices, etc., adds them to the TOC, and enumerates differently, as described above.
AFAIK this is actually the way appendix works in Latex. 
https://latex-tutorial.com/latex-appendix/

**Comment by jjallaire** [comment]
@gjirokastrelbasanit34 I believe that most of what you describe is currently available in Quarto Books, e.g. see https://quarto.org/docs/books/book-structure.html#parts-appendices. In LaTeX output this actually ends up including the `\appendix` cmd at the right spot. 

We don't currently have special Appendix treatment for standalone articles, however we plan on working on this soon.

**Comment by piotrzientarski** [comment]
In Latex output there is:
```latex
\appendix
\addcontentsline{toc}{part}{Appendices}
```
and this is my main problem.

**Comment by jjallaire** [comment]
Just made this change and it will be available in v02.449. Does this look like the proper translation of "Appendices" to Russian? https://github.com/quarto-dev/quarto-cli/commit/42cf9d5e4d9d04f2a8725d5e47595ca39439c72b#diff-0c7bd9aec45edb416ac66665cdd399cbc2b2c8f3db2260ff931d3120b5809eeb

**Comment by piotrzientarski** [comment]
Awesome, thank you!

I am not Russian, but the appendices in Russian are probably вложения.

**Comment by jjallaire** [comment]
Okay, I'll make that change.

**Comment by psychelzh** [comment]
I am sorry to mention this here, but when I set `lang: zh` or any other languages than English, the left side toc always shows `Apendices` not the correspond translation. I am using version `1.1.165` of quarto. Am I missing something?

![image](https://user-images.githubusercontent.com/13306020/188272408-99f814e8-9c63-438c-a5b7-5b3a9ec2aca5.png)

Format setting:

```yml
format:
  html:
    lang: zh
    theme: cosmo
```

**Comment by jjallaire** [comment]
@dragonstyle Could you take a look at this? (potentially a v1.1 backport worthy fix if this is indeed the case)

**Comment by dragonstyle** [comment]
Thanks for letting us know - the issue in this case is that the `lang` is appearing under a specific format (that should work, but doesn't for books specifically). To workaround this for now, can you place the `lang` key in the root of your `_quarto.yml` file? This should get things working as expected.

I'm going to open a separate issue to track this with additional info about the bug.
