### ISSUE TITLE
OJS - not locally interactive

### ISSUE THREAD

**Issue by Lourenzutti** [quarto-dev/quarto-cli#2529]
Hi, sorry if I misunderstood this. 

When I use OJS to make slides interactive, it is only interactive while running on the local server. 
However, if I open the generated `html`  file directly in the browser, the interactive bars do not show up.

Maybe I'm missing something, or this is the expected behaviour. If the former, I apologize. 
If the latter, I'd suggest a modification to the following part of the [documentation](https://quarto.org/docs/interactive/): 

> One benefit of using JavaScript for interactive documents is that all the logic and computation is performed on the client (so no server is required for deployment).

Reproducible Example (please note a space on the triple backtick below): 

```
---
title: "Reproducible Example "
format: revealjs
editor: visual
---

## Home

```{ojs}
viewof size_bar = {
  let input = Inputs.range([50, 150], 
                           {value: 70,
                            step: 1, 
                            label: "Size Bar: "});
  return input;
}
` ``
```

**Comment by cderv** [comment]
Yes this is expected, you need to serve the document / website for it to work. And this is valid probably for other resources that use javascript execution in browser. 

Usually you only need `quarto preview` and no specific external local server. 

Does it work with `quarto preview` ? 

> (so no server is required for deployment).

This really mean that you can deploy to any publishing platform and it will work, without need background server to run some code. 

We welcome any suggestion in the wording. What would you find more precise then ? 

Thanks!

**Comment by Lourenzutti** [comment]
Yeah, it just threw me off a little as when I saw "no server required" I thought somehow it would work as regular JS locally. 

Sorry for the invalid issue; and thank you for the explanation.
