### ISSUE TITLE
Feature request: Side-by-side code chunks

### ISSUE THREAD

**Issue by coatless** [quarto-dev/quarto-cli#253]
Any chance code chunks could be placed side-by-side? 

![side-by-side-code-example](https://user-images.githubusercontent.com/833642/148484764-3ea21439-aa18-403d-823d-2348f57cf560.jpg)

There seems to be existing support for side-by-side content through [Figure Panels](https://quarto.org/docs/authoring/figures-and-layout.html#figure-panels) and [Table Panels](https://quarto.org/docs/authoring/figures-and-layout.html#table-panels).

However, the closest I've come to allowing for a side-by-side comparison is using the panel tabset and switching back and forth. The downside to this approach is content ends up getting hidden/suppressed. 

![combined-tab-view](https://user-images.githubusercontent.com/833642/148485587-6c218cbe-2cf9-4c0c-b73a-1a44d3becff3.jpg)

````
::: panel-tabset
#### R

```{r}
my_list = list(1, 2, 3)
typeof(my_list)
```

#### Python

```{python}
my_list = [1, 2, 3]
type(my_list)
```

:::
````

<details>
<summary>Side-by-side code cells using `xaringan`</summary>

<img width="919" alt="xaringan-side-by-side-code-chunks" src="https://user-images.githubusercontent.com/833642/148485828-52534431-fc1c-48ab-8eb2-595e9c7de531.png">

````
---
output:
  xaringan::moon_reader:
    lib_dir: libs
---

.pull-left[
```{r r-example-tibble, paged.print=FALSE}
library(tibble)
tibble(
  ID = c(1, 2),
  Grade = c("A", "B")
)
```
] 

.pull-right[
```{python py-example-dictionary}
{
  "ID": [1, 2],
  "Grade": ["A", "B"]
}
```
]
````
</details>

**Comment by knuesel** [comment]
What about the [block layout](https://quarto.org/docs/authoring/figures-and-layout.html#block-layout) feature, does it do what you want?

    ::: {layout-ncol=2}
    #### R
    
    ```r
    my_list = list(1, 2, 3)
    typeof(my_list)
    ```
    
    #### Python
    
    ```python
    my_list = [1, 2, 3]
    type(my_list)
    ```
    :::

![image](https://user-images.githubusercontent.com/2412819/148532764-b272ae49-dafb-4060-91dc-2f1308b5931a.png)

However if you want to execute the code of different languages you might run into issue: https://github.com/quarto-dev/quarto-cli/issues/135

**Comment by jjallaire** [comment]
Yes, you can use the `layout` attributes w/ arbitrary content not just figures and tables, see https://quarto.org/docs/authoring/figures-and-layout.html#block-layout

For mixing R and Python in the same document you probably want to use the knitr engine w/ reticulate.
