### ISSUE TITLE
toc-location: left, page-layout: full result in tabs not being clickable

### ISSUE THREAD

**Issue by boshek** [quarto-dev/quarto-cli#2533]
### Bug description

This seems somewhat similar to #2388 but that was fixed in https://github.com/quarto-dev/quarto-cli/commit/335608f88e00721388c25534d1939a9e6889a406. 

Here is a reprex using:

```bash
quarto-theseus-testing quarto --version
1.1.251
```

````md
---
title: "Untitled"
execute: 
  eval: true
  echo: false
  warning: false
format: 
  html:
    toc: true
    toc-location: left
    page-layout: full
---

```{r r-pkgs}
library(dplyr)
library(glue)
library(gt)
library(purrr)
```


# Tables

::: {.panel-tabset}

```{r}
#| output: asis
res <- purrr::map_chr(unique(starwars$homeworld), \(hw) {
    knitr::knit_child(text = c(
      "## `r hw`",
      "", 
      "```{r}",
      "#| echo: false",
      "starwars %>%",
      "  filter(homeworld == hw) %>%",
      "  count(sex) %>%",
      "  head() %>%",
      "  gt()",
      "```",
      "",
      ""
    ), envir = environment(), quiet = TRUE)
  })

cat(res, sep = '\n')
```
:::

````

This appears to be some combination of `toc-location` and `page-layout` as mentioned [here](https://github.com/quarto-dev/quarto-cli/discussions/2173#discussioncomment-3612281). Here is a breakdown of those combinations:

| toc-location | page-layout | clickable_tabs |
|--------------|-------------|----------------|
| left         | full        | no             |
| right        | full        | yes            |
| left         | NULL        | yes            |
| right        | NULL        | yes            |

I can reproduce in RStudio (2022.07.1) and vscode (version 1.71).

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thank for reporting this with a nice reproducible case! I believe that this issue is fixed in the current v1.2.x pre-release, which you can download here https://quarto.org/docs/download/prerelease.html ). If you are still seeing the issue in the pre-release, please re-open this.

**Comment by boshek** [comment]
Ah yes - this absolutely does fix it. Thanks!

**Comment by dragonstyle** [comment]
Great news, thank you for taking the time to confirm!
