### ISSUE TITLE
Feature Request: Allow child documents in Python

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [quarto-dev/quarto-cli#254]
When the file (say, book) itself is enormous, builds take minutes and threaten to hang the editor, `r markdown` allows to set `child="auxfile.md"` parameter to include (or leave out) edited parts, and this works in Quarto, but only in R. 

Since the possibilities to write projects on average are greater on Python, I would appreciate if this "document including" would be available, at least at first for markdown files without code.

**Comment by jjallaire** [comment]
Until Quarto gains this feature natively, you can use the external `include-files` filter to include markdown content: https://quarto.org/docs/authoring/shortcodes-and-filters.html#includes

We do plan on adding an include facility that allows you to include computational markdown (e.g. `.qmd`) soon.

Note that if you use Quarto Books (https://quarto.org/docs/books/) and split your manuscript into chapters then you will get incremental rendering that should mitigate some of the performance problems you are seeing (rendering a single chapter of a book _only_ executes that chapter and uses cached execution output for the other chapters.

**Comment by gjirokastrelbasanit34** [comment]
Thank you so much for the link, and I just would like to apologise profoundly for not reading the entire Books section of the documentation since I intended to write what was "articles" in my perception and did not suppose Books actually have greater number of features even for `.pdf` and `.docx` documents, and hence fit me best. 

There is just a couple of things in Quarto Books that I failed to do and I wonder whether they are implemented or not:
1. How can I make references to chapters with arabic numbers (rather than Roman letters) in a book? In a standalone article, if I add a label to a Section and cross-reference it, it gets a number by default. 

2. How can I assign arabic numbers to Appendices (both in TOC, crossrefs and Headers), rather than Roman letters?   

This is a YAML header that I have in my `index.qmd` file, but `labels: arabic` does not produce expected effect, and I doubt 
```
---
crossref:
    labels: arabic
    sec-labels: arabic
    appendix-title: "Appendix"
    appendix-delim: ":"
    appendix-labels: arabic
    fig-title: Pict.
number-sections: true
format:  docx 
---
```

**Comment by jjallaire** [comment]
Hi there, glad that books is _mostly_ working well for you.

Note that in a book the `crossref` options should go into `_quarto.yml` rather than `index.qmd`.

You are correct that it's not currently possible to customize chapter/section numbering. This is because Pandoc is actually doing the numbering under the hood and we can't customize its behavior. I think there may however be a way for us to override Pandoc entirely -- I will make a note to investigate that.
