### ISSUE TITLE
Warn on missing chapters and undefined references

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#255]
Yesterday I sent a report draft where a chapter was missing... Turns out I had renamed the source file and forgot to update the `_quarto.yml` :-). Shouldn't quarto make an error (or at least a warning) if a file in the chapter list is not found?

Also somewhat related: it would be nice to see in the terminal the list of undefined cross-references...

**Comment by jjallaire** [comment]
I've made missing chapters a hard error here: https://github.com/quarto-dev/quarto-cli/commit/dc970ccf7a84962ed0c152abc97370d307e76ce8

And warn for missing crossrefs here: https://github.com/quarto-dev/quarto-cli/commit/47b3624dfc906c957bbe3a8ac983a9193718c399

**Comment by knuesel** [comment]
Thanks! Do I need to do something to enable the warning? running `quarto render a.md` with version 02.448 on a file containing

```
See @sec-something.
```

doesn't print a warning...

**Comment by jjallaire** [comment]
No that should work fine, although we currently only print crossref warnings for HTML output (as for LaTeX the crossref resolution is handled by LaTeX). Does that explain the behavior you are seeing?

**Comment by knuesel** [comment]
I also don't see a warning for HTML output:

```
$ echo "See @sec-something." > a.md

$ quarto render a.md
pandoc 
  to: html
  output-file: a.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  filters:
    - crossref
  
metadata
  document-css: false
  link-citations: true
  
Output created: a.html

$ grep strong a.html 
<p>See <strong>?@sec-something</strong>.</p>          <-- undefined reference in output

$ quarto --version
0.2.448
```

**Comment by jjallaire** [comment]
Oh I see now, is this NOT in a quarto book project? (the work I did only works in book projects, but I could easily enhance to work on standalone documents)

**Comment by knuesel** [comment]
Ah yes this small test is with a standalone `.md` file without `_quarto.yml`.

My actual project is a quarto book. If I render to HTML I still see no warning... except if I completely remove the `format:   pdf:` section in `_quarto.yml`. Then it works fine!

**Comment by jjallaire** [comment]
I just pushed a change that will also print warnings for standalone files.

I am however seeing the warnings printed for books. Can you provide a MRE for books that exhibits this behavior? What platform are you running on?

**Comment by knuesel** [comment]
Ah you need to remove the `format:    html:` section in the yaml file. Here is a MRE:

```
quarto create-project --type book
echo -e "\nSee @sec-something." >> intro.qmd
sed '/html\|cosmo/d' -i _quarto.yml     # delete the html format section
quarto render --to html
```

**Comment by jjallaire** [comment]
Okay, thanks for your persistence! This actually uncovered a bigger issue with the rendering of projects with a `--to` that isn't in the config file. Should be all resolved w/ this commit: https://github.com/quarto-dev/quarto-cli/commit/fe2e08f26ea5f76b4b0ed23ab7d0d0a9dd2942f7 (will be in v0.2.452 which is building now)

**Comment by knuesel** [comment]
Thanks! and sorry for the delay. I confirm it all works as expected now.
