### ISSUE TITLE
documentclass moderncv needs "footnotes in longtable" to be disabled

### ISSUE THREAD

**Issue by produnis** [quarto-dev/quarto-cli#2553]
### Bug description

Hi there,
I just figured out that if you want to render a PDF with documentclass `moderncv` you need to comment-out these lines in the latex-template:

```
% % Allow footnotes in longtable head/foot
% \IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
% \makesavenoteenv{longtable}
```
If you do not, you will get the error message

`undefined control sequence \begin{document}`

....just sayin... took me a while to find out... ;)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
unfortunately we can't make the Pandoc template work well with the entirety of the LaTeX ecosystem. In general, if you need to change the document class, the preferred way to do it is through a custom format: https://quarto.org/docs/extensions/formats.html

**Comment by cderv** [comment]
@cscheid was faster than me, but I'll post anyway my longer answer I was typing :) 

This is part of the template is not behind a variable on Pandoc's template and will be added to all template
https://github.com/jgm/pandoc/blob/eb1826740711319eccade8a634c03d747f461930/data/templates/default.latex#L253-L255 
So this could be seen as an issue in Pandoc, as it would mean `documentclass: moderncv` would not work. 

However, this part of the template is inside our [table.tex partial](https://github.com/quarto-dev/quarto-cli/blob/7b53645bd0a525674e034264ff5a17607110966d/src/resources/formats/pdf/pandoc/tables.tex#L19)
More on partials in here: https://quarto.org/docs/journals/templates.html#latex-partials

So one would need to specifically provide a partial template commenting this out, and set 
````
format:
  pdf:
   documentclass: moderncv
    template-partials:
      - table.tex
 ````

I believe our extension mechanism to create new format is there to solve such limitation of default pdf format
See link posted by Carlos.
