### ISSUE TITLE
bash code chunks error

### ISSUE THREAD

**Issue by AmelZulji** [quarto-dev/quarto-cli#2557]
### Bug description

Dear support team, 

I have come across a wired behavior of Quarto Book (in Rstudio) when using `bash` chunks. I initiate quarto book project from Rstudio and if I include `bash` chunks in the qmd files which are initiated with the project (index.qmd, intro.qmd etc) it works fine. However, if I create new .qmd file (File > New File > Quarto Document) and include the same `bash` chunk, it throws the following error: 

```
[4/5] test1.qmd

Starting python3 kernel...Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 16, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
Python 3 installation:
  Version: 3.8.9
  Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
  Jupyter: (None)

Jupyter is not available in this Python installation.
Install with python3 -m pip install jupyter
```

R studio: 2022.07.1 Build 554
Operating system: macOS Big Sur; version 11.6.6

What could be the problem?

Kind regards,
Amel

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
@AmelZulji Just to clarify something in case it can help

>  I initiate quarto book project from Rstudio and if I include bash chunks in the qmd files which are initiated with the project (index.qmd, intro.qmd etc) it works fine.

By doing that, you probably have a Quarto book that is using **knitr** engine, as this is the default choice within R Studio menu. Probably with R code chunk inside files. 

Are you inserting the bash chunk inside a `qmd` file with a R code chunks in it ? 

> However, if I create new .qmd file (File > New File > Quarto Document) and include the same bash chunk, it throws the following error:

Is the content of the `qmd` file created the same ? By any chance do you have only bash chunk in the file ? 

Context is that if you are putting bash chunk in a document using knitr engine, then bash chunk will use knitr. If you are using only bash chunk in this document, auto detection of engine will use python by default. Hence the error message you see. 
That is why I am guessing this is what could have happen, and you don't want python. 

Setting 

```
execute:
   engine: knitr
```

in configuration will insure that **knitr** will be used for computation code. 

See more about engine binding in the doc: https://quarto.org/docs/computations/execution-options.html#engine-binding

And previous questions in discussions and issues, for example: 
* https://github.com/quarto-dev/quarto-cli/discussions/1468
* https://github.com/quarto-dev/quarto-cli/issues/558

Hope it helps

**Comment by AmelZulji** [comment]
Thank you very much for quick response, @cderv and @cscheid! 

This was exactly the problem:
> If you are using only bash chunk in this document, auto detection of engine will use python by default. Hence the error message you see.
> That is why I am guessing this is what could have happen, and you don't want python.

This solved the problem: 
```
execute:
   engine: knitr
```

Thank you for your help and kind regards
Amel
