### ISSUE TITLE
Use rsvg-convert when available on the path to convert SVG to PDF like Pandoc

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2575]
@cderv It does seem like we should consider doing this when rsvg-convert is available on the path. We'd just need a Lua filter for this that targets PDF/LaTeX/Beamer. I'd think we'd want to do it automatically (as the other alternative is an error message from LaTeX). Could you take a shot at a PR for this? (note that the node module requires native code so not something we can easily port to deno). 

cc @cscheid

_Originally posted by @jjallaire in https://github.com/quarto-dev/quarto-cli/issues/997#issuecomment-1140310275_

## Context 

This is what Pandoc is [doing in its PDF writer](https://github.com/jgm/pandoc/blob/b263f383040618ff991912512ccd396b83d43da5/src/Text/Pandoc/PDF.hs#L194-L205), and we should probably bring this feature back for our `quarto render --to pdf` format, as this is a difference from `pandoc --to pdf` behavior.

**Comment by dragonstyle** [comment]
Fixed here
68a0b7835e147f767a7d2e16628b50f4c81d7b03

**Comment by cderv** [comment]
Awesome ! Thank you  @dragonstyle !
