### ISSUE TITLE
Issue: Custom language .yml ignorred

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [quarto-dev/quarto-cli#258]
Should `language: custom.yml` setting in YAML root surpress `lang: ...` or the reverse is true? 

This is my sample code, where `de.yml` is located in the same folder as the source, and it is itself identical to the `.yml` suggested by quarto for German, but the HTML output does not look like German-localized (see the `sec.` vs `sek.` and `fig.` vs `sch.`) 

```
---
title: Title
author: Alexander
date: 05/01/22
language: C:/Users/User/qq/de.yml
number-sections: true
format: html 
toc: true
---
# Der Beispiel {#sec-init}

Die erste Sektion @sec-init
 
![Unterschrift](image_table.png){#fig-sample}

Der erste Schaubild @Fig-sample
```
the output is: 

![image](https://user-images.githubusercontent.com/62909272/148683715-ae8ed650-d392-4bd2-9829-b810868fe957.png)

Am I missing something? 

I am asking this because I have also run into another issue: for all 3 formats, in all editors, PDF, HTML and Word, the Chinese and Russian (i. e. non-Latin) prefixes are rendered as `??` in output if I set `lang: ru`, `lang: zh` in YAML root respectively, while non-Latin text in chunks, markdown, and non-latin prefixes and titles for pictures and tables work perfectly. 
But this issue may be related to my PC specifically, while the upper one is not. 

I am on Win 10, dev Quarto version (99.9.9)
Thanks in advance for any response.

**Comment by jjallaire** [comment]
The first issue (custom language yaml ignored) should be resolved here: https://github.com/quarto-dev/quarto-cli/commit/83d0574ab84014459711c3198a8a43062c77ac37

The second issue I am unable to reproduce on OS X however I'll also give a try on Windows and report back.

**Comment by jjallaire** [comment]
I can reproduce the second issue on Windows. Will investigate and hopefully have a fix soon.

**Comment by jjallaire** [comment]
The second issue (mangling of unicode language translations in crossrefs) is fixed here: https://github.com/quarto-dev/quarto-cli/commit/72505912665627440f89748fb2b19f842a64c694

Thanks again for reporting both of these issues!

**Comment by gjirokastrelbasanit34** [comment]
One notable thing is that if the language prefixes are provided by custom `yaml`, in all engines, in PDF, the title for `\tableofcontents` does not get redefined, while the titles of `\listoffigures` and `\listoflistings` do.

**Comment by jjallaire** [comment]
Okay, thanks for catching this! Should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/ca07ad702473b6ae2fce94ae06f3b39dcc122ffd
