### ISSUE TITLE
no render output with output-dir: . 

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#259]
Given an empty directory, create an empty project and configure that project to use the current directory for output.

```bash
# In directory "foo":
quarto create-project
```

Edit the `_quarto.yml`:

```yaml
project:
  title: "foo"
  output-dir: .
```

Rendering produces no output, exits without error, and produces no files on-disk.

```bash
quarto render
echo $?
#=> 0
ls -a
#=> .              ..             .gitattributes .gitignore     _quarto.yml    foo.qmd
```

Using Quarto as of commit ca07ad702473b6ae2fce94ae06f3b39dcc122ffd.

I encountered this situation while trying to determine if I could use `output-dir` for all rendering situations. In particular, I was trying to determine if I could use `output-dir: .` for in-place rendering (interactive documents) and therefore have a similar YAML structure as situations where I want to render into a named output directory.

The issue as described is using a Quarto project, but I am most interested in the behavior when adding a `_quarto.yml` to a single-file Shiny document. For example, create the following `_quarto.yml` file in a directory containing the "Old Faithful" example:

```yaml
project:
  output-dir: .
```

Even in this situation, rendering produces no output and creates no HTML, while still exits with a zero (normal) status:

```bash
quarto render
echo $?
#=> 0
.              ..             .gitattributes .gitignore     _quarto.yml    index.qmd
```

The `.git*` files are created as a side-effect of the render, but there is no HTML produced.

The current behavior implies that we should not use `output-dir: "."` for in-place rendering, which is fine, but it was surprising to receive no error or other feedback.

**Comment by jjallaire** [comment]
This is likely happening because when there is an `output-dir` we mask it from the directories being enumerated for input files. We can work around this by just treating `"."` the same as no `output-dir`. With this change (https://github.com/quarto-dev/quarto-cli/commit/e255fa8d0619bb0cd6905020b75c21a87e9b95af) your project works as you intended.

**Comment by aronatkins** [comment]
Thanks. An error would have also been fine. The "no output" and "no error" was a surprising combination!
