### ISSUE TITLE
Quotation (">") does not work when using pdf-output

### ISSUE THREAD

**Issue by benjaminmoritz** [quarto-dev/quarto-cli#2598]
### Bug description

Quotation (">") does not work when using pdf-output, Ther is no grey line and grey textcolor . 
> Test

### System

I am using Windows and VS Code

**Comment by dragonstyle** [comment]
In my testing, we properly produce the correct quotation environment (which in KOMA appears to be indent the text).

```latex
\begin{quote}
Test
\end{quote}
```

While some features of Quarto produce very similar styling between formats (callouts), others like the aside/quotation environment will use the typesetting provided by the LaTeX class file.
