### ISSUE TITLE
Consider removing button focus effect on sidebar navigation?

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#26]
When you click on a top-level item in the sidebar navigation, a blue box shadow shows up. 

<img width="1130" alt="Screen Shot 2021-04-23 at 12 30 40 PM" src="https://user-images.githubusercontent.com/12160301/115920959-bd394f80-a42f-11eb-87d0-81d185023fdc.png">

Maybe considering removing the box shadow here?

```
.btn-check:focus + .btn, .btn:focus {
	outline: 0;
	/* box-shadow: 0 0 0 .25rem rgba(39,128,227,.25); */
}
```

**Comment by jjallaire** [comment]
Wondering if keeping the box shadow is important for accessibility? I agree it doesn't look very good here, but there is the principle of showing where focus is. @dragonstyle I wonder if there is a way to distinguish between whether a mouse or keyboard gesture was used to drive focus?
