### ISSUE TITLE
Feature request: Allow zero number-depth in PDF? 

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [quarto-dev/quarto-cli#260]
The answer to this post https://tex.stackexchange.com/questions/61033/setting-toc-depth-not-working#61061 contends that in a PDF book, it is possible to number chapters only by setting number-depth to 0. 
I attempted to tweak the intermediary `.tex` file by setting `\setcounter{setnumdepth}{0}`, but that didn't work. 
If I attempt to set `number-depth: 0`, I am getting the full enumeration possible, as if it wasn't set at all.

I would like to number only chapters in PDF book, for example.

Thanks for any response.

**Comment by dragonstyle** [comment]
Great catch - there was an issue where we weren't properly forwarding the `number-depth`. I've corrected that here ab48b07736c3434a97b1c935b521bb2ff18e26ba and `number-depth: 0` should be giving the behavior you're expecting now. Thanks!

https://github.com/quarto-dev/quarto-cli/releases/tag/v0.2.470
