### ISSUE TITLE
Mermaid diagrams in reveal JS don't render after 2nd slide

### ISSUE THREAD

**Issue by d-chambers** [quarto-dev/quarto-cli#2607]
### Bug description

Mermaid diagrams in reveal JS clip the diagram image after the second slide. 

For example, consider the following file (named slides.qmd):

````
---
title: "mermaid crash"
format:
    revealjs
---


# git graph 1

```{mermaid}
gitGraph
   commit id: "Alpha"

```

# git graph 2

```{mermaid}
gitGraph
   commit id: "Alpha"

```

# git graph 3

```{mermaid}
gitGraph
   commit id: "Alpha"

```

````

Creates the expected output for git graph 1 and 2, which look like this:

![image](https://user-images.githubusercontent.com/11671536/192181269-e8133515-b41d-4802-b752-8f801ed65bb0.png)

But slide 3 looks like this (as do any subsequent slides with mermaid content):

![image](https://user-images.githubusercontent.com/11671536/192181354-ee0894ab-c17e-48a2-9591-053d0f548ad0.png)

I am using the latest nightly build (1.2.157) on Ubuntu 20.04.  I am just using quarto from the command line to generate the html (no R studio). 

I get the same problem when viewer rendered html with Chrome or Firefox.  Also, it is not unique to gitGraph, any mermaid content gets distorted and clipped. Interestingly, sometime while in preview mode the problem rights itself after making a change  to any of the slides (but not always).

Thanks!

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by d-chambers** [comment]
Hi @cderv,

Yes, this fixes the issue. Thank you for taking a look. For now I will just set view-distance to the number of slides in the presentation to ensure they render properly. 

Derrick

**Comment by d-chambers** [comment]
update: this did fix the issue for the desktop version of the slides, but the mobile version is still broken.

**Comment by cderv** [comment]
> but the mobile version is still broken.

Yes you need to apply the same configuration but for mobile: `mobile-view-distance`
References are here: https://quarto.org/docs/reference/formats/presentations/revealjs.html#media

> mobile-view-distance	|  Number of slides away from the current slide to pre-load resources for (on mobile devices).

**Comment by cderv** [comment]
For reference, another report of this in https://community.rstudio.com/t/quarto-revealjs-mermaid-diagrams-dont-show-after-r-code-chunks-pictures/148533

**Comment by cscheid** [comment]
We're going to work around it by making the view-distance as big as the slideshow whenever we find mermaid divs. That has some performance consequences, but the alternative is worse.

**Comment by cderv** [comment]
> I just need help to understand better size calculation for mermaid, and how to trigger a possible resize.

Is there no way to trigger resize or svg size calculation from JS for mermaid ? 
Best solution would be to trigger resize or size calculation when we enter the slide - we do that for some HTML widget already.

**Comment by cscheid** [comment]
There's a lot of potential risk there, because mermaid now behaves very differently in mermaidjs format. If we're going to do that, then what we need to do is provide a proper quarto js api for mermaid. That's more than I want to tackle in this issue. But we can have a conversation about it for 1.3.

**Comment by d-chambers** [comment]
Thanks @cscheid  and @cderv! 

For [my site](https://opensourcecourse.dev/modules/git/slides.html#/title-slide) which uses a *ton* of mermaid graphs to teach git, it takes about 5 seconds to load on a desktop, which is no big deal. The mobile version, however, hangs for nearly a minute on my older android phone, but that is certainly better than not rendering correctly. 

I have found huge benefit from quarto, keep up the good work!

**Comment by cscheid** [comment]
@d-chambers Yeah, that's not great, I'm sorry to hear. You might find better luck pre-compiling those mermaid diagrams to PNG or SVG... `%%| mermaid-format: svg` at the beginning of the `{mermaid}` cell.
