### ISSUE TITLE
revealjs: images from external url not rendered

### ISSUE THREAD

**Issue by JulianTao** [quarto-dev/quarto-cli#261]
This also happens on the Quarto web, for example, https://quarto.org/docs/presentations/revealjs/demo/#/absolute-position

**Comment by jjallaire** [comment]
I'm not seeing this locally (the issue you pointed out on our site was due to another problem). Could you give us a small reproducible example?

**Comment by JulianTao** [comment]
OK, I see. I have the pacekitten images as placeholders in my slides. Just tried images from other websites and they are rendered perfectly.  My bad! I am closing this issue now.
