### ISSUE TITLE
My code generated two tables, but Quarto only handled one

### ISSUE THREAD

**Issue by JER-ry** [quarto-dev/quarto-cli#2615]
### Bug description

Working with an **.ipynb** file in **VSCode**. Quarto **0.9.462**. Windows 11.

To reproduce, use the Python package `statsmodels` to generate a summary of an OLS model. That is,

```python
import pandas as pd
import statsmodels.formula.api as smf

df = pd.read_csv("Carseats.csv")  # The one included in ISLR
mod1 = smf.ols(formula='Sales ~ Price + Urban + US', data=df)
res1 = mod1.fit()
res1.summary()
```

Then you get 2 tables

![](https://user-images.githubusercontent.com/30141096/192335494-277bab23-3aa6-40f2-a15f-d1eff8629115.png)

Now render PDF with Quarto

![](https://user-images.githubusercontent.com/30141096/192336051-9fada5f9-e76a-4f54-9020-2f351093a3e1.png)

You only get one table.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Can you share a fully self-contained example in a git repo, or use a dataset that doesn't require us to find out where it's from? That will help us make sure we can see the issue on our side.

**Comment by JER-ry** [comment]
> Can you share a fully self-contained example in a git repo, or use a dataset that doesn't require us to find out where it's from? That will help us make sure we can see the issue on our side.

Ok I’ll modify that a bit later but for a quick reply the dataset can be found in this zip
https://www.statlearning.com/s/ALL-CSV-FILES-2nd-Edition-corrected.zip
the
The issue seems independent of the dataset though, performing linear regression on any dataset produces the similar thing.

**Comment by JER-ry** [comment]
OK here is a minimal example. Just create an ipynb file and paste this. (`pip install statsmodels`)
```python
import statsmodels.formula.api as smf
smf.ols(formula='y ~ x', data={"x": [1, 2], "y": [1, 2]}).fit().summary()
```

**Comment by cscheid** [comment]
Ok, I can reproduce this on the latest prerelease version of quarto.
