### ISSUE TITLE
Unicode cannot be displayed in headings and title

### ISSUE THREAD

**Issue by zhchenyang** [quarto-dev/quarto-cli#2619]
### Bug description

Unicode can be displayed in the body, but not in the title and headings

```
---
title: 青黑體
format: pdf
mainfont: "Noto Sans CJK JP"
---

## 青黑體簡體中文,ヒラギノ

青黑體簡體中文,ヒラギノ角
```

![unicode](https://user-images.githubusercontent.com/28039275/192415842-8b85b85f-8e35-459d-83be-98c73a4e1ecd.png)

os version

```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
```

quarto version

```
quarto check                        

[✓] Checking Quarto installation......OK
      Version: 1.1.251
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.13 (Conda)
      Path: /home/xx/anaconda3/bin/python
      Jupyter: 4.10.0
      Kernels: python2, ir, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.16

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
I can reproduce this. From my quick test, I think this is due to Quarto defaulting to use [Koma scripts](https://ctan.org/pkg/koma-script) and so `documentclass: scrartcl`, equivalent or `article`
See https://quarto.org/docs/output-formats/pdf-basics.html#document-class

If you set 
````
format: 
  pdf:
    documentclas: article
    mainfont: "Noto Sans CJK JP"
````

Maybe there is something to activate specifically to use this Unicode with Koma 🤔

**Comment by cderv** [comment]
Ok it seems that you need to add the CJK package for xelatex `xeCJK`

````yaml
format: 
  pdf:
    mainfont: "Noto Sans CJK JP"
    include-in-header:
      - text: \usepackage{xeCJK}
````

This solves the issue for me. 

I did not found any specific documentation on this . Only some mention in Overleaf: https://fr.overleaf.com/learn/latex/Chinese#xeCJK_with_XeLaTeX

It should solve it for you. Can you confirm ? 

I don't think we can do anything about that, apart from documenting as an example (here and maybe in our example repo)

**Comment by zhchenyang** [comment]
Both works for me, thanks
