### ISSUE TITLE
Formatting breaks listing layout

### ISSUE THREAD

**Issue by Nenuial** [quarto-dev/quarto-cli#2620]
### Bug description

If the first paragraph of a page contains formatting (bold for example) the listing layout breaks. I tried with a page (among a number of other pages without formatting) that contains some bold first paragraph like so:

```md
---
title: "Test1"
---
**Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin maximus turpis id neque pharetra, ut vehicula augue sagittis. Duis pellentesque dolor vel diam imperdiet lacinia.**

Nulla facilisi. Morbi placerat faucibus mauris a luctus. Donec pellentesque mauris auctor tortor laoreet maximus. Maecenas ac risus in turpis suscipit euismod. Cras id congue nibh. Donec efficitur risus nec velit convallis consectetur. Morbi tincidunt non urna non ornare.
```

In a grid listing the cards are stuck in two columns. In a blog style the "columns" break.

I am using Quarto 1.2.157 on Mac OS 12.6.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thanks for letting us know - this should be fixed in the latest pre-release available here <https://quarto.org/docs/download/prerelease.html>.

**Comment by Nenuial** [comment]
I can confirm, it works fine now! Thanks for the fix.
