### ISSUE TITLE
quarto publish in subfolder fails

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto-cli#2623]
### Bug description

I was trying to publish a document contained in a subfolder to Quarto Pub, e.g.

```
quarto publish quarto-pub folder/test.qmd
```

The structure is:

```
.
└── folder
    └── test.qmd
```

And the content of `folder/test.qmd` is not important, e.g.

```
---
engine: jupyter
---

## Test

This is a simple test file.
```

But this didn't work, because after entering the account and document name, I got this error:

```
ERROR: NotFound: No such file or directory (os error 2), stat 'folder/folder/test_files/libs'
```

FWIW, this was a document rendered with the `jupyter` engine (but I get the same error with `knitr`), and I was running Quarto 1.1.251 on macOS.

Also, `quarto preview folder/test.qmd` is working, and publishing from within the `folder` also works.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
I can reproduce with current dev version of quarto. 

> ERROR: NotFound: No such file or directory (os error 2), stat 'folder/folder/test_files/libs'

It seems like there is a duplication for the sub folder

I did create a `dummy` folder in root folder with `test.qmd` inside 
```markdown
---
title: Test
---

## Test

This is a simple test file.
````



then from root folder `uarto publish quarto-pub dummy/test.qmd`

<details>
<summary>Folder organization after rendering </summary>

````
C:\USERS\CHRIS\DOCUMENTS\DUMMY
│   test.html
│   test.qmd
│
└───test_files
    └───libs
        ├───bootstrap
        │       bootstrap-icons.css
        │       bootstrap-icons.woff
        │       bootstrap.min.css
        │       bootstrap.min.js
        │
        ├───clipboard
        │       clipboard.min.js
        │
        └───quarto-html
                anchor.min.js
                popper.min.js
                quarto-syntax-highlighting.css
                quarto.js
                tippy.css
                tippy.umd.min.js
````


</details>


Traceback for this issue
```
NotFound: Le chemin d’accès spécifié est introuvable. (os error 3), stat 'dummy\dummy\test_files\libs'
    at Object.statSync (deno:runtime/js/30_fs.js:239:21)
    at file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/publish.ts:241:14
    at Array.reduce (<anonymous>)
    at normalizePublishFiles (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/publish.ts:239:43)
    at renderForPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/publish.ts:164:16)
    at async renderForPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/common/publish.ts:247:22)
    at async handlePublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/common/publish.ts:116:24)
    at async publishDocument (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/publish.ts:212:36)
    at async publish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:273:9)
    at async doPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:188:7)
```

**Comment by jjallaire** [comment]
Thanks for reporting this! Should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/8ad0761c853a7803eb9e0e4fdd2e15a9d908eb73
