### ISSUE TITLE
Double references

### ISSUE THREAD

**Issue by frankbach** [quarto-dev/quarto-cli#2626]
### Bug description

When I reference a source in Revealjs it appears twice in the end of the presentation. The code looks like:
## Tiden för implementering

::: {#implementering .incremental}
-   En ny betygsskala hade nyligen införts.

-   Kunskapskrav istället för betygskriterier

-   Betygssystemet framstod som icke-kompensatoriskt [@gustafsson2014]

-   Proven skulle både stödja lärares betygssättning och bidra till implementering av styrdokumenten.
:::

and the result:
Gustafsson, J.-E., Cliffordsson, C., & Erickson, G. (2014). Likvärdig kunskapsbedömning i och av den svenska skolan – problem och möjligheter (s. 120). SNS - Studieförbundet Näringsliv och Samhälle. https://www.sns.se/aktuellt/likvardig-kunskapsbedomning-i-och-av-den-svenska-skolan-problem-och-mojligheter/
Gustafsson, J.-E., Cliffordsson, C., & Erickson, G. (2014). Likvärdig kunskapsbedömning i och av den svenska skolan – problem och möjligheter (s. 120). SNS - Studieförbundet Näringsliv och Samhälle. https://www.sns.se/aktuellt/likvardig-kunskapsbedomning-i-och-av-den-svenska-skolan-problem-och-mojligheter/

RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
[Presreligion.qmd.zip](https://github.com/quarto-dev/quarto-cli/files/9654984/Presreligion.qmd.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Hi thank you for reporting this - this issue has been fixed in our latest pre-release, available here <https://quarto.org/docs/download/prerelease.html>.

If you'd like to stick with the current release, you may also workaround the issue by removing the `citeproc: true` from your document front matter (we use citeproc by default, so it isn't strictly necessary and is what is triggering the bug that we fixed).
