### ISSUE TITLE
Links to section open with section header hidden below navbar

### ISSUE THREAD

**Issue by miwojc** [quarto-dev/quarto-cli#2641]
### Bug description

going to this url:

https://quarto.org/docs/presentations/revealjs/#speaker-notes

produced this output:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/32404415/192700494-2669c445-a201-42d1-bca0-8dcde277511a.png">
where section header is hidden under navbar

Expected outcome:
section header not hidden under navbar
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/32404415/192700611-500888ca-85d4-4834-b643-3b76365ebe31.png">

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
This only appears to occur on Firefox browsers.
