### ISSUE TITLE
Render Quarto with HTML or PDF failed in when codechunks with R code are included (Rstudio 2022.07.1 Build 554)

### ISSUE THREAD

**Issue by BertTijhuis** [quarto-dev/quarto-cli#2646]
### Bug description

**Description Issue Render Default R Quarto Document**

Render with yaml extension:
Format: html
Format: pdf

is failing when r code is included

When specifying 

Format: docx

it is rendering fine

---
The failed output is shown as:

```
> quarto::quarto_render('T0002.qmd')

Error in rmarkdown:::abs_path(input) :   
  The file 'T0002.qmd' does not exist.  
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>  
Execution halted  
```

**Code Block:**

````
---
title: "T0002"
format: html
editor: visual
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
````

**End**

Rstudio IDE version:  RStudio 2022.07.1 Build 554

*** Running on Ubuntu 20.04 and on Windows 10

```
Microsoft Windows [Version 10.0.19042.1706]
(c) Microsoft Corporation. All rights reserved.

C:\Users\bert.Tijhuis>quarto check

[>] Checking Quarto installation......OK
      Version: 1.1.163
      Path: C:\R\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: C:/R/Python/Python310/python.exe
      Jupyter: 4.10.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/R/R-4.2.0
      LibPaths:
        - C:/R/R-4.2.0/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK


C:\Users\bert.Tijhuis>
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
Hi, thanks for the report. 

Can you format your issue correctly please ? https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us

This would be easier to read. 

I can't reproduce doing this: 

* Open RStudio
* New file > New Quarto document 
* Create for HTML format, and save the file to `test.qmd`
````markdown
---
title: "Untitled"
format: html
editor: visual
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
````

* Click render button -> It renders fine 
* * Use `quarto::quarto_render("test.qmd")` (this is the name of my file)
![image](https://user-images.githubusercontent.com/6791940/192778072-f21fe41c-2c91-4c43-a679-ee7a825218c3.png)


>````
>Error in rmarkdown:::abs_path(input) :
>The file 'T0002.qmd' does not exist.
>Calls: .main -> execute -> setwd -> dirname ->
>Execution halted
>````

This means that the file is not found. Do you have the file in your current working directory ?
You can check by calling `list.files()` in R console to check

**Comment by BertTijhuis** [comment]
File is called:  T0002.qmd

\> list.files()
[1] "T0001.docx" "T0001.qmd"  **"T0002.qmd"** 

And the file exists

\---
title: "T0002"
format: html
editor: visual
\---

\## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see \<https://quarto.org>.

\## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

\```{r}
1 + 1
\```

You can add options to executable code like this

\```{r}
#| echo: false
2 * 2
\```

The `echo: false` option disables the printing of code (only output is displayed).


When running with format: docx it is running fine

**Comment by cderv** [comment]
Please can you format your issue correctly ? I am putting the link here a third time for a guide on how to format code part in your text to identify it differently. PLease read, https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us

It seems you shared the same code as I have posted above. IT works for me, I can reproduce with latest Quarto. 
You can maybe update using https://quarto.org/docs/download/

Can you run `quarto check` in terminal and share result here (properly formatted) ? 

> When running with format: docx it is running fine

You mean it is not working only for HTML and with this issue ? 
````
Error in rmarkdown:::abs_path(input) :
The file 'T0002.qmd' does not exist.
Calls: .main -> execute -> setwd -> dirname ->
Execution halted
````

* Does `quarto render T002.qmd` is working ? 
* Does using the Render button in RStudio IDE is working ? (or render in VSCODE if that is what you are using) 

Thank you.

**Comment by BertTijhuis** [comment]
Hello
here is the quarto check from a terminal


[>] Checking Quarto installation......OK
      Version: 1.1.163
      Path: C:\R\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: C:/R/Python/Python310/python.exe
      Jupyter: 4.10.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/R/R-4.2.0
      LibPaths:
        - C:/R/R-4.2.0/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK


---
C:\Users\xxxx.yyyy\OneDrive - XXXXX\DIV\samples\Rcourse\test>quarto render T0002.qmd
Error in rmarkdown:::abs_path(input) :
  The file 'T0002.qmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted

C:\Users\xxxx.yyyy\OneDrive - XXXXX\DIV\samples\Rcourse\test>dir
 Volume in drive C is Windows
 Volume Serial Number is B0E6-DCA9

 Directory of C:\Users\xxxx.yyyy\OneDrive - XXXXX\DIV\samples\Rcourse\test

28-09-2022  13:13    <DIR>          .
28-09-2022  13:13    <DIR>          ..
28-09-2022  15:41             3.196 .Rhistory
27-09-2022  10:25            10.476 T0001.docx
27-09-2022  10:25               592 T0001.qmd
27-09-2022  10:26               592 T0002.qmd
               4 File(s)         14.856 bytes
               2 Dir(s)  194.258.407.424 bytes free

C:\Users\xxxx.yyyy\OneDrive - XXXXX\DIV\samples\Rcourse\test>

------

It is working when 

format: docx

or
when I removed the R code chunks

or
when I specify something like 

\```{python}

In the other cases it isn't working

If possible provide me a logging tool so that I figure this out.


So I created a file called:  T0002a.qmd  (Containing only text) and that is working properly

\---
title: "T0002"
format: html
editor: visual
\---

\## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

Running in command prompt:
   quarto render T0002a.qmd 

is generating:

pandoc 
  to: html
  output-file: T0002a.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: T0002
  editor: visual
  
Output created: T0002a.html

And the HTML file looks ok.

So it something related to the knitr engine.

When running the same code as rmarkdown file then this working fine.!

**Comment by cderv** [comment]
Thanks for the additional information. that is helpful. 
but please do read https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us and format code part when you reply. Please do not ignore our guidelines, and help us help you. thank you. 

> So it something related to the knitr engine.

Yes, the error `Error in rmarkdown:::abs_path(input) :` comes from the fact R code is evaluated. I'll look into this with you. 

> `C:\Users\xxxx.yyyy\OneDrive - XXXXX\DIV\samples\Rcourse\test`

It may come from the fact that you are on One Drive or that you have spaces in PATH. 

Can you just run `rmarkdown:::abs_path("T0002.qmd")` for me in you R  console ? What is the about ? 
If an issue, can you run `traceback()` directly after it. thank you

**Comment by BertTijhuis** [comment]
From the Rconsole:

````
> list.files()
[1] "T0001.docx"   "T0001.qmd"    "T0002.qmd"    "T0002a.html"  "T0002a.qmd"
[6] "T0002a_files"
> rmarkdown:::abs_path('T0002.qmd')
[1] "C:/Users/XXXXX/OneDrive - XXXXX/DIV/samples/Rcourse/test/T0002.qmd"
>
````

There was no issue so the traceback() was not showing anything

I'm also able to run this from a folder without spaces eg. c:/temp/test but the same issue is popping up.

**Comment by cderv** [comment]
That is really odd. 

> ```
> [>] Checking Quarto installation......OK
> Version: 1.1.163
> Path: C:\R\Quarto\bin
> CodePage: 1252
> ```

Can you update and try a newer version ? https://quarto.org/docs/download/

I still can't reproduce, so if you can share all the information you can think off on your environment that would help

For the record, I believe this where the error is thrown within Quarto 
https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/rmd/execute.R#L12

Somehow within the rendering, `file.exists()` return FALSE it seems. 
```
if (!file.exists(x)) 
        stop("The file '", x, "' does not exist.")
````

**Comment by BertTijhuis** [comment]
Installed newer version:

````
quarto check

[>] Checking Quarto installation......OK
      Version: 1.1.251
      Path: C:\R\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: C:/R/Python/Python310/python.exe
      Jupyter: 4.10.0
      Kernels: python3

(|) Checking Jupyter engine render....2022-09-28 20:57:12,679 - traitlets - WARNING - Timeout waiting for IOPub output
2022-09-28 20:57:17,032 - traitlets - WARNING - Timeout waiting for IOPub output
2022-09-28 20:57:21,085 - traitlets - WARNING - Timeout waiting for IOPub output
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/R/R-4.2.0
      LibPaths:
        - C:/R/R-4.2.0/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK

````

Running:

````
> quarto::quarto_render('T0002.qmd')
Error in rmarkdown:::abs_path(input) : 
  The file 'T0002.qmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
Error in `processx::run(quarto_bin, args, echo = TRUE)`:
! System command 'quarto.exe' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Type .Last.error to see the more details.
> traceback()
4: stop(cond)
3: throw(new_process_error(res, call = sys.call(), echo = echo, 
       stderr_to_stdout, res$status, command = command, args = args))
2: processx::run(quarto_bin, args, echo = TRUE)
1: quarto::quarto_render("T0002.qmd")
````


When running with the quarto command

````
C:\Temp\test>quarto render T0002.qmd
Error in rmarkdown:::abs_path(input) :
  The file 'T0002.qmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
````

But when I convert it than it works

````
C:\Temp\test>quarto convert T0002.qmd
Converted to T0002.ipynb

C:\Temp\test>quarto render T0002.ipynb
pandoc
  to: html
  output-file: T0002.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: T0002
  editor: visual

Output created: T0002.html
````

But that is not the original idea of it.

In the past I did run into the Same issue: but within rstudio there was under the global options a tab quarto (and when I was disabling it is was working), but this Tab is gone in the never version.

**Comment by cderv** [comment]
Thank you. 

I still don't have a pinpoint what could cause this, and so can't reproduce on my side. 🤔 

Two things we can do: 

You installed 1.1.251 - you could try the latest pre-release version to see if somehow we have fixed it. Same url to find it https://quarto.org/docs/download/

> ```
> > rmarkdown:::abs_path('T0002.qmd')
> [1] "C:/Users/XXXXX/OneDrive - XXXXX/DIV/samples/Rcourse/test/T0002.qmd"
> ```

Does it work when you are not inside OneDrive repository ? or even in a path with no space in it ? 
Can you try this setup with the same files ? 

Thank you

**Comment by BertTijhuis** [comment]
````
C:\Users\xxxx.xxxx>quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.169
      Path: C:\R\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: C:/R/Python/Python310/python.exe
      Jupyter: 4.10.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/R/R-4.2.0
      LibPaths:
        - C:/R/R-4.2.0/library
      rmarkdown: 2.16

[>] Checking Knitr engine render......OK
````

Put the files also into the folder:  c:/temp/test and did the run again

````
> setwd("C:/Temp/test")
> quarto::quarto_render('T0002.qmd')
Error in rmarkdown:::abs_path(input) : 
  The file 'T0002.qmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
Error in `processx::run(quarto_bin, args, echo = TRUE)`:
! System command 'quarto.exe' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Type .Last.error to see the more details.
> list.files()
[1] "T0001.docx"   "T0001.qmd"    "T0002.html"   "T0002.ipynb"  "T0002.qmd"    "T0002_files"  "T0002a.html"  "T0002a.qmd"   "T0002a_files"

````

Pitty same issue,

**Comment by cderv** [comment]
This could indeed be the source of the issue. You are changing the working directory for all R code run, include R in Quarto. When `T0002.qmd` will be looked for by Quarto, it will be relative to the working directory you have configured, and not the directory you expect probably (where you ran `quarto render` I think)

You should probably not configure anything with `setwd()` in file like `.Rprofile` used by all R session. 

What is the purpose of the configuration ? 

We can maybe prevent this from happening, but still I would not do such command in Rprofile

**Comment by BertTijhuis** [comment]
Since 1998 I'm working with R and stored my scripts in a folder that wasn't the default folder from 
And that is the reason why I'm using the initial setwd command.
Till now I never have issue with it.
It seems that quarto is rereading the .Rprofile (when using knitr) but I'm not sure.

**Comment by BertTijhuis** [comment]
>How are you running R or your script usually ? From where do you launch R ? Are you using an IDE or just terminal ?
>It seems you don't work in Project or similar.

Most of the time I'm using an IDE, for interfaces I'm using a terminal (Running R CMD) 
Correct I'm hardly using Projects

>Does rendering using rmarkdown::render("input.Rmd") works fine with this system ? input.Rmd would need to be in your >global working dir or are you using absolute path in this case ?

````
> setwd("C:/Users/xxxx.xxxxx/OneDrive - xxxx/DIV/samples/Rcourse/test")
> rmarkdown::render("input.Rmd")


processing file: input.Rmd
  |....................                                                                                                                           |  14%
   inline R code fragments
````

That is working fine

Indeed running:
````
C:\Users\xxxx.xxxx>\r\R-4.2.0\bin\Rscript.exe -e "getwd()"
[1] "C:/Users/xxxx.xxxx/OneDrive - xxxxx/DIV/samples"
````
or executing a file in folder

````
Rscript my_script.R
````

But when using this, i specify in one of the first lines

````
setwd('to_new_path')  
````

either a folder below the default folder that I'm using or 

Hopes this give you more context.


I've noticed still some weird things (which I can't explain)

When running with
format:   html|pdf  (This issue is occuring)
format:   docx         (everything is running fine)

But anyway I like quarto as the next generation of the Rmarkdown, and I'm using this already quite a lot for reporting.
So keep the good work ongoing

**Comment by cderv** [comment]
add to your use `.Rprofile` (`~/.Rprofile` in Documents on Windows`) the following that forces the default working directory for any R code to be in HOME
````r
message("++ Setting Working Dir to HOME\n")
setwd(Sys.getenv("HOME"))
````

This is exactly what is done above. 

Now create a simple `test.qmd` document not in `HOME` folder. For example 

````powershell
> $qmd
---
title: test
---

```{r}
getwd()
```
> $qmd | Set-Content $env:TEMP/test.qmd
> bat $env:TEMP/test.qmd
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: C:\Users\chris\AppData\Local\Temp/test.qmd
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ ---
   2   │ title: test
   3   │ ---
   4   │
   5   │ ```{r}
   6   │ getwd()
   7   │ ```
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
````

We are in this situation where no matter where R is open, the working directory will be always the same
````powershell
> cd $env:TEMP
> Rscript -e 'getwd()'
++ Setting Working Dir to HOME

[1] "C:/Users/chris/Documents"
````

Now try to render the qmd file 

````
> pwd

Path
----
C:\Users\chris\AppData\Local\Temp

> quarto render test.qmd

++ Setting Working Dir to HOME

Error in `rmarkdown:::abs_path()`:
! The file 'test.qmd' does not exist.
Backtrace:
    ▆
 1. └─global .main()
 2.   └─execute(...)
 3.     ├─base::setwd(dirname(rmarkdown:::abs_path(input)))
 4.     ├─base::dirname(rmarkdown:::abs_path(input))
 5.     └─rmarkdown:::abs_path(input)
Exécution arrêtée
++ Activating rlang global_entrace

++ Setting Working Dir to HOME

ERROR: Error
    at renderFiles (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-files.ts:532:23)
    at async render (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-shared.ts:101:18)
    at async Command.fn (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cmd.ts:210:26)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:119:3)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:151:5
````


We can see that Quarto will run R and the profile will apply which will change the working directory and finding `input` doesn't work. 

* In `quarto render test.qmd`, input is relative to where quarto is called
* But when R is started, the working directory is modified and it is not found 

I believe we should protect against this behavior, even we don't expect and recommend to change a working directory in scripts or in .Rprofile. Quarto should not fail for such type of personal workflow.

**Comment by cderv** [comment]
We are currently adapting the working dir for R in some situations only mainly when using Projects (`renv` R package or Quarto project I guess) 
https://github.com/quarto-dev/quarto-cli/blob/0b46497f75bd63e71fb2d4cea629ef884ea2c394/src/execute/rmd.ts#L198-L200

Considering the above, we don't unsure that R scripts will be run in the correct directory as we just run `rmd/rmd.R` with R in `cwd` needed 
https://github.com/quarto-dev/quarto-cli/blob/0b46497f75bd63e71fb2d4cea629ef884ea2c394/src/execute/rmd.ts#L214-L222

It seems we may need to pass the `cwd` as an input for `rmd.R` to set `setwd()` for R directory, as it seems to me quarto's R script `rmd.R` expects to be run in the `cwd` directory. Otherwise, changing `setwd()` in a user or project .Rprofile will probably cause this type of error. It seems ot

**Comment by cderv** [comment]
Opend https://github.com/quarto-dev/quarto-cli/pull/4749 to show the change I am thinking output and discuss it

**Comment by cderv** [comment]
Thanks for the report @BertTijhuis - next 1.3 build will have the fix, and soon to be stable release.

**Comment by BertTijhuis** [comment]
Thank you
