### ISSUE TITLE
Includes not working in asis code chunk

### ISSUE THREAD

**Issue by zhchenyang** [quarto-dev/quarto-cli#2663]
### Bug description

![asis](https://user-images.githubusercontent.com/28039275/192930141-093b9d93-43a3-450e-bb27-6ab51d09dee7.png)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
`includes` feature is Quarto specific, and especially is resolved before anything knitting happens. 

To do this kind of things from an R chunk directly, you can leverage the Child document feature from **knitr**

look at this examples: https://examples.quarto.pub/create-tabsets-panel-from-r-code/ and its source code. Also related R Markdown Cookbook example https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html

**Comment by zhchenyang** [comment]
Thank you very much for the solution!

```{r}
#| output: asis
for (i in seq_len(3)) {
  res = knitr::knit_child('_comp.qmd', quiet = TRUE)
  cat(res, sep = '\n')
}
```
