### ISSUE TITLE
links to .Rmd files always changed to .html

### ISSUE THREAD

**Issue by daviddalpiaz** [quarto-dev/quarto-cli#267]
When using the `render` option in the `project` YAML, if only `.qmd` files are specified, links to `.Rmd` files are changed to `.html` even through the `.Rmd` files are correctly not rendered.

**Comment by daviddalpiaz** [comment]
While looking into a temporary fix, I'm also noticing that `post-render` does not seem to be invoking a suggested R script. (Will need to investigate this more though. Might be something silly on my end.)

**Comment by jjallaire** [comment]
The first issue should be resolved here (https://github.com/quarto-dev/quarto-cli/commit/ed20ce42d34fe3fdd0b2fcf5493811eed4e18454). Thanks for reporting!

The second issue I can't reproduce. Note that `post-render` is specified as a subkey of `project` rather than `website`

**Comment by daviddalpiaz** [comment]
I made an attempt to reproduce here: https://github.com/daviddalpiaz/quarto-post

I'm guessing it's still me either not understanding execution order or some syntax issue.

**Comment by jjallaire** [comment]
Your example works for me -- what version of Quarto are you running? You can find out with `quarto --version`

**Comment by daviddalpiaz** [comment]
Ah, I'm guessing that's the issue: `0.2.382` (I forget, but this version is either what's bundled in the RStudio Daily build for macOS or installed via the CRAN R package.)

**Comment by jjallaire** [comment]
It's an older version of what's bundled with RStudio. If you update you should get the `post-render` stuff working as expected.
