### ISSUE TITLE
--output-dir option ignored when _quarto.yml file is absent

### ISSUE THREAD

**Issue by castedo** [quarto-dev/quarto-cli#2670]
### Bug description

STEPS:

Run the following in an empty directory:
```
echo Hi > test.qmd
quarto render test.qmd --to markdown --output-dir out
```

EXPECTED:
`test.md` to be written to an `out` subdirectory, not the current directory.

NOTES:
1) This all works as expected if I do
```
touch _quarto.yml
```
to create an empty `_quarto.yml` file.

2) Similarly happens with `--to html` too.

3) `--output-dir` is listed by `quarto render --help`.

ENVIRONMENT:
```
[castedo@quarto-1 1]$ quarto --version
1.1.251
[castedo@quarto-1 1]$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Container Image)"
ID=fedora
VERSION_ID=36
...
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
This requires the presence of a project (note that description in help is for project output and this is expected to be a project relative path) as it is a project feature.
