### ISSUE TITLE
--output-dir fails on cross-device destination

### ISSUE THREAD

**Issue by castedo** [quarto-dev/quarto-cli#2671]
### Bug description

STEPS: from empty directory on Linux
```
sudo mkdir /tmp2
sudo mount -t tmpfs tmpfs /tmp2
echo Hi > test.qmd
touch _quarto.yml
quarto render test.qmd --to markdown --output-dir /tmp2
```

RESULT: quarto outputs:
```
ERROR: Invalid cross-device link (os error 18), rename '/home/castedo/shr/bugs/q2/test.md' -> '/tmp2/test.md'
```

NOTES:
1) This works:
```
quarto render test.qmd --to markdown --output-dir tmp2
```
2) So does
```
echo Hola > /tmp2/hi.txt
cat /tmp2/hi.txt
```
3) These steps with a tmpfs are not my actually usage scenario. I hit this because I run quarto inside a container and was outputing into a public_html directory mounted outside the container. Similar issue should get hit with VMs and shared folders.

Easy for me to work around though.

ENVIRONMENT:
```
[castedo@quarto-1 1]$ quarto --version
1.1.251
[castedo@quarto-1 1]$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Container Image)"
ID=fedora
VERSION_ID=36
...
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
We should probably check `--output` flag also as a similar issue is reported in https://github.com/quarto-dev/quarto-r/issues/35

https://github.com/quarto-dev/quarto-cli/blob/2bdf5e8ab4dd35f52f0ee73b74209ec7fdfcae31/src/command/render/output-tex.ts#L84

What we do in R Markdown to prevent this type of issue is [having a moving function](https://github.com/rstudio/rmarkdown/blob/8fabad00efdd17b2622c12d191a8cffa09547e32/R/util.R#L266-L271) that is 
* Copying and then renaming
* Deleting original files copied

Seems like that is what was adviced in Deno too : https://github.com/denoland/deno/issues/3092

Maybe we should have a wrapper of `Deno.RenameSync` that handles this type error and do a copying instead.

**Comment by grst** [comment]
There seems to be a PR open in `deno` now: 
https://github.com/denoland/deno/pull/19879

**Comment by rcannood** [comment]
Just encountered this issue in pkgdown as well. Would it help to replace all `fs.renameSync(a, b)` with the following?

```
  try {
    fs.renameSync(a, b)
  } catch (err: unknown) {
    core.debug(`Failed to rename file: ${err}`)
    fs.copyFileSync(a, b)
    fs.unlinkSync(a)
  }
```

**Comment by cscheid** [comment]
Not that simple when directories are involved.
