### ISSUE TITLE
Code filename not correctly placed when used on computational chunk

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2683]
### Bug description

From https://github.com/quarto-ext/code-filename/issues/3 but extensions has been included inside core now. 

````markdown
---
title: Test
format: html
---

Non computation code filename

```{.r filename="file.R"}
1 + 1 
```

Inside code-fold

```{r filename="file.R"}
#| code-fold: true

1 + 1
```

````
![image](https://user-images.githubusercontent.com/6791940/193271548-dbf72560-3991-4698-aac2-5ab9decfc7a8.png)

Do we want to support `filename` on computational chunk ? (which does not follow the YAML in chunk syntax) 

If not, we should deactivate. 
If we do, we maybe to introduce as YAML option and/or put the filename inside the folding of source. 

Related Discussion item: https://github.com/quarto-dev/quarto-cli/discussions/2642

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jjallaire** [comment]
Deferring this until we have a better handle on order of AST transformations. I'm not 100% sure what the "correct" behavior is here (i.e. which should compose on the other, whether we should allow both, etc.).
