### ISSUE TITLE
revealjs: highlighting lines with `|` hides the copy button after the first step

### ISSUE THREAD

**Issue by etiennebacher** [quarto-dev/quarto-cli#2685]
### Bug description

In the example below, I highlight some lines progressively using `|` in `code-line-numbers`. However, after the first step, the "copy code" button doesn't appear anymore when I hover the code chunk. 

I'm not sure which behavior is expected: hide the copy button as soon as there's some line highlighting, or enable it all the time?

````rmd
---
format: revealjs
---

```{.r code-line-numbers="1|2"}
line1
line2
```
````
---

quarto v. 1.2.171
Windows 10 x64 (build 19044)
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
I think this could have been solved @etiennebacher 

This is with latest version of pre-release

https://user-images.githubusercontent.com/6791940/223506682-f95e61a7-c3ca-43dd-b931-7363272865a5.mp4

Please reopen if still an issue for you
