### ISSUE TITLE
Nested native divs for custom complex layouts

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#269]
This is a two-part issue. Firstly, I want to make sure that a feature is not accidental (and would thus be prone to breaking) and secondly ask about more elegant solutions for for the same idea.

Since quarto uses pandocs native divs we can create arbitrarily nested divs by adding more `:` to the div separator. So I wondered if this also worked in [quarto's custom figure layouts](https://quarto.org/docs/authoring/figures-and-layout.html#complex-layouts), and indeed it does!

This makes it possible to combine row-first and column-first layout options, which would not be possible with a single layout array definition.

What is still difficult with this approach though is the alignment and sizing of sub-figures if the goal is for example to allign the two 2 small cats with the big cat (note that my numbers don't quite work, there is still a gap at the top and bottom). In theory these numbers could be calculated from the image aspect ratio and the margins.

```
:::: {layout="[[0.75, 1.75], [1]]" layout-valign="center"}
::: {layout-nrow=2}
![ ](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/1200px-Cat_November_2010-1a.jpg)

![ ](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/1200px-Cat_November_2010-1a.jpg)
:::

![ ](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/1200px-Cat_November_2010-1a.jpg)
::::
```

![image](https://user-images.githubusercontent.com/17450586/149985838-9123a9e2-dc7a-4c8b-b5ab-1474bd396c38.png)

**Comment by jjallaire** [comment]
Nested layout divs do indeed work, however I would suspect that getting the alignment on them right would be very tricky (as you've seen).

**Comment by jmbuhr** [comment]
Short update for others trying the same: while nested figure divs work for html output, it errors out for TeX/pdf output (`LaTeX Error: Not in outer par mode`. It does render to  docx output, but breaks the layout a bit.
