### ISSUE TITLE
Embed jupyter widget not working

### ISSUE THREAD

**Issue by byryepez** [quarto-dev/quarto-cli#2693]
### Bug description

Hello,

I'm trying to create an interactive HTML document using jupyter widgets. here are the python code chuck in my qmd file:

````
---
title: "Test - Embed widget"
author: byryepez
format: html
---

## Creating plotting function

```{python}
import pandas as pd
import matplotlib.pyplot as plt
from ipywidgets import widgets, interact

data = {
    'x' : [1,2,3,1,2,3,1,2,3],
    'y' : [1,2,3,4,5,6,7,8,9],
    'p' : ['A','A','A','B','B','B','C','C','C'] 
}

df = pd.DataFrame(data)

def exp_plot(datasource, a):
    dfset = datasource.query('p == @a')
    return dfset.plot.line(x='x',y='y')

def int_plot(param_a):
    return exp_plot(datasource=df, a= param_a);

interact(int_plot, param_a =['A', 'B', 'C']);
plt.show()
```
````

When I render the file to HTML, the document is not interactive, the plot is frozen to the default option. If I render the qmd file to jupyter, the document it is interactive, no issue.

I'm runing in Linux  x64 5.15.65-1-MANJARO, quarto: 1.1.251, python: 3.10.6 64-bit on VSCODE 1.71.2

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Ok, I see it now. I believe `interact` requires a running process in the background, which is not something you can get out of a plain Python notebook rendering. So this isn't a bug, but rather functionality that can't be gotten out of Quarto's rendered HTML.

With that said, I encourage you to look at https://shiny.rstudio.com/py/ which _does_ run a full installation of Python and Matplotlib on the browser, and has quarto support.

**Comment by aarontsaez** [comment]
Did you figure out a solution @byryepez ? I am also running the exact same problem
