### ISSUE TITLE
url fields in bibtex render separately, not as hrefs on the title

### ISSUE THREAD

**Issue by rahuldave** [quarto-dev/quarto-cli#2696]
### Bug description

Url fields in bibtex render separately, not as hrefs on the title.

I believe the default behavior in citeproc is to have the title field from the bibtex to be the text for the link. This is not how they render on the sidebar using quarto (version 1.0.37)

Osx 11.1, m1 macbook.

<img width="1088" alt="Screen Shot 2022-10-01 at 3 57 39 PM" src="https://user-images.githubusercontent.com/43227/193426222-ba0ae528-3e3b-46c4-811a-a4380e69b8cc.png">

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by njbart** [comment]
> I believe the default behavior in citeproc is to have the title field from the bibtex to be the text for the link. 

This is an entirely unfounded “belief”. As per the [pandoc manual](https://pandoc.org/MANUAL.html) (my emph.),

> `link-bibliography`
If true, DOIs, PMCIDs, PMID, and URLs in bibliographies will be rendered as hyperlinks. (If an entry contains a DOI, PMCID, PMID, or URL, *but none of these fields are rendered by the style, then the title, or in the absence of a title the whole entry, will be hyperlinked*.) Defaults to true. 

Hence one may expect hyperlinked titles only when using CSL styles that do not render URLs etc. by themselves. 

The OP does not indicate which CSL style has been used, but it’s clear from the output that this is one that *does* render URL variables.

`journal-of-neurochemistry.csl`, for example, is a style that does not render URLs, and hence does hyperlink titles when used with pandoc; for others, consult https://www.zotero.org/styles/ or https://github.com/citation-style-language/styles.

**Comment by rahuldave** [comment]
I'm using quarto's default, which i went and looked is the Chicago manual of style (I had assumed that link-bibliography being true meant that unless i explicitly supplied a csl in my yaml metadata, I would have title's hyperlinked. I went and looked at the Zotero styles, and there seem to be many Chicago ones: not sure which one is the one quarto uses. I used the one you suggested: neurochemistry, and now i need to understand why it works :-). Didnt see any code which would suggest hyperlinking of titles: must dig! Thanks!

**Comment by njbart** [comment]
The logic described in the snippet from the [pandoc manual](https://pandoc.org/MANUAL.html) quoted above is baked into pandoc, but of course, this depends crucially on the instructions in the particular style: If there are none that call for rendering URL, DOI, etc., *then* the title is hyperlinked. 

In order to achieve this effect with an existing style that does contain such instructions, all of them would have to be removed (and the style renamed, since it would no longer conform to the respective style guide or manual).

quarto’s and pandoc’s default CSL style is `chicago-author-date.csl`, BTW.

**Comment by rahuldave** [comment]
Thanks for this very succinct and nice explanation! Closing this then as not a bug. Wondering if a csl that autolinks title is more appropriate as a default, but then i might not be the target market for this feature :-)
