### ISSUE TITLE
Mistaken expansion of all sections in sidebar section navigation

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#27]
I noticed that if I intentionally close all the sections, but then open a page in an expanded section, all the other sections automatically expand too. See video:

https://user-images.githubusercontent.com/12160301/115921193-025d8180-a430-11eb-91dc-2bb96d724f29.mov

**Comment by dragonstyle** [comment]
This is being driven by the default `collapse-level` which is 2 (by default, when a page loads, we expanded to the second item). If the collapse level were set to 1, all the items would be default collapsed but the opposite could happen (e.g. if you expanded them all and then navigated, it would collapse them all on the next page). 

Note that this behavior does appear to the same as other solutions like `mkdocs` that rely up statically generating tree controls (and generate the expansion state of the tree into the document itself). e.g. [https://docs.rstudio.com](https://docs.rstudio.com )

We'll discuss a bit to figure out what the right thing to do is here.

**Comment by dragonstyle** [comment]
I did a little further review of other static documentation generators and it does like this is a common problem among them (tree expansion state is generated into each generated HTML page). We could store the expansion state in local storage and use that to preserve tree state across navigation- we'll keep this open and give it a second look as more users come online and we gather additional feedback.

**Comment by apreshill** [comment]
Interesting! Bookdown has a setting that allows you to preserve the collapsed sections- you can see it in action here:

https://stat545.com/basic-data-care.html

Here is the setting: https://github.com/rstudio-education/stat545/blob/d15943d04d7ee5556138c061462da457ec756269/_output.yml#L7-L9

Same thing here: https://rstudio4edu.github.io/rstudio4edu-book/make-doc.html

The main reason I was collapsing the top levels was to minimize clutter and distraction as I was reading a section, so perhaps making that sidebar collapsible as a whole piece would serve a similar goal?

**Comment by cderv** [comment]
> Bookdown has a setting that allows you to preserve the collapsed sections

For reference, this is a special plugin added to Gitbook specifically for this I believe. 
https://github.com/rstudio/bookdown/blob/b66380e7c9a478edbebb3c21a0449a5c98f9bddb/inst/resources/gitbook/js/plugin-bookdown.js#L114

**Comment by apreshill** [comment]
I'm not seeing the same thing in the docs site here: https://docs.rstudio.com/rstudio-team/

Maybe I'm missing something, but if I click on a single page in an expanded section, no other sections auto-expand.

https://user-images.githubusercontent.com/12160301/116261944-fb36bc00-a72c-11eb-85a8-688f85fff1a0.mov

**Comment by dragonstyle** [comment]
I think there two issues to discuss here:

1) How expanded is the tree by default.
We default to the second level, but try setting `collapse-level` on your site to 1. This would default collapse the tree. Our default setting expands the tree to the second level by default. On the Rstudio docs site, they are doing the equivalent of `collapse-level: 1`.

```
site:
  title: "Quarto Demo"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Basics"
        contents:
          - index.md
          - basics-knitr.Rmd
          - basics-jupyter.md
      - section: "Layout"
        contents:
```

Results in 

![Screen Shot 2021-04-27 at 12 06 42 PM](https://user-images.githubusercontent.com/261654/116274887-11ef0a00-a751-11eb-8301-98786eb28627.png)


2) Is tree expansion state preserved upon navigation
This is more about whether the tree state is maintained across navigation (e.g if you open and close a bunch of branches of the tree and then click to navigate to another page, is the tree still in the state you put it in).  I was reading this bug as more about preserving the state of the tree across navigates versus just defaulting to the correct expansion level.

Also seems like it may make sense for us to have a mode that just moves the tree out of the way (e.g. a reader mode or some way to reduce envelope noise) to make the reading experience better.

**Comment by cderv** [comment]
> Also seems like it may make sense for us to have a mode that just moves the tree out of the way (e.g. a reader mode or some way to reduce envelope noise) to make the reading experience better.

Oh yes, I remember we talked about that. I like the button to collapse the sidebar in `gitbook()` and `bs4_book()` remove the sidebar with the tree when zooming which is another way.

**Comment by apreshill** [comment]
Indeed- `collapse-section=1` matches what I was expecting!
