### ISSUE TITLE
crossref table error with paged table

### ISSUE THREAD

**Issue by hao203** [quarto-dev/quarto-cli#2712]
Hello,
There is a bug.

In my quarto book file 03-tidy_data.qmd
the code block is

```r
#| label: tbl-birth
#| tbl-cap: "Birth table"
load("dataset/births.rda") 
births
```
_quarto.yml  settings

``` yaml
format:
  html:
    theme: cosmo
    df-print: paged
```

@tbl-birth

when I render the book, there is a warning

> WARNING: 03-tidy_data.html: Unable to resolve crossref @tbl-birth
Watching files for changes

The crossref is available when I change the code block using `kable()`, but it's not paged

```r
#| label: tbl-birth
#| tbl-cap: "Birth table"
births <- import("dataset/births.rda")  
knitr::kable(births)
```

I want both of crossref and paged available.

**Comment by hao203** [comment]
Thanks a lot!

**Comment by cscheid** [comment]
Hello - can you send us a single file that reproducibly causes this issue? Thanks.

**Comment by hao203** [comment]
> Hello - can you send us a single file that reproducibly causes this issue? Thanks.

OK. I create a new quarto file

``` quato
---
title: "Untitled"
format: 
  html:
    df-print: paged
editor: source
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## table1

```{r}
#| label: tbl-test1
#| tbl-cap: "Birth table"
library(magrittr)
tab1 <- esoph  
knitr::kable(tab1) 
```

cross-ref @tbl-test1 

paged is not work

## table2

```{r}
#| label: tbl-test2
#| tbl-cap: "table 2"

tab2 <- esoph  
tab2

```

cross-ref @tbl-test2

cross-ref is not work
```

**Comment by cscheid** [comment]
Thanks for the example. I can't reproduce this locally on the latest quarto version. Can you download a 1.2 prerelease and try again?

<img width="839" alt="image" src="https://user-images.githubusercontent.com/285675/194347459-d4086008-603a-43f8-aa67-c5cab3ec7e08.png">

**Comment by hao203** [comment]
> Thanks for the example. I can't reproduce this locally on the latest quarto version. Can you download a 1.2 prerelease and try again?
> 
> <img alt="image" width="839" src="https://user-images.githubusercontent.com/285675/194347459-d4086008-603a-43f8-aa67-c5cab3ec7e08.png">

Thanks Carlos

It works in quarto 1.2 prerelease version on win 10.
Hope the new stable 1.2 version.
