### ISSUE TITLE
Process content from stdin

### ISSUE THREAD

**Issue by benabel** [quarto-dev/quarto-cli#272]
Is there any way to render content from stdin like pandoc.

```sh
echo "## Title" | pandoc
```
I've found in the docs that quarto can render to stdout with `quarto render notebook.Rmd --output - `, but I didn't find anything for stdin.

**Comment by jjallaire** [comment]
Quarto assumes that it has a path available for its input (so it can calculate the output file, know where to put supporting files, etc.). For that reason can't render markdown from stdin.

**Comment by AlloriMD** [comment]
I do think that processing from STDIN would be a valuable feature. This would permit integration with other tools such as Marked2.app.
