### ISSUE TITLE
figures not rendered in local host when qmd is placed in a sub-directory

### ISSUE THREAD

**Issue by huizezhang-sherry** [quarto-dev/quarto-cli#2730]
### Bug description

I create [this repo](https://github.com/huizezhang-sherry/quarto-include-graphics) to demonstrate the unexpected behavior when inserting figures with `knitr::inclue_graphics()` in qmd.

There are two qmd files: 

1) `main.qmd `under the top level, and 
2) `main-analysis.qmd` in the `analysis` folder. 

A single command is included in both qmd: `knitr::include_graphics(here::here("figures/R_logo.png"))`

Everything is fine when knitting the top level main.qmd, but when knitting `main-analysis.qmd`, the figure is not loaded when viewed in the Viewer window (also not in the browser when clicking the icon Show in a new window):

<img width="1904" alt="Screen Shot 2022-10-05 at 2 34 11 pm" src="https://user-images.githubusercontent.com/36781502/193976546-78d80826-8240-4f31-b315-fac74edb1b58.png">

The figure does appear when opening the `main-analysis.html`. 

A quick inspection of HTML shows that the `figures` folder doesn't seem to be copied across

Maybe this is a bug?

Additional info:
- Rstudio IDE version: 2022.02.2 
- Operating system: macOS Monterey version 12.5.1

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jjallaire** [comment]
The problem is that when viewing files locally you cannot reference content that lies outside of the root directory you are serving the document from. If you want to make references like this you should create a website project.

**Comment by huizezhang-sherry** [comment]
Thanks, I figured that local viewing would work with the following YAML header: 

```
format: 
  html:
    self-contained: true
```

The issue was raised because such local viewing was not a problem with rmd.

**Comment by jjallaire** [comment]
Okay, great! I should have thought of that too :-)
