### ISSUE TITLE
Revealjs hoverCitations popups too narrow/long

### ISSUE THREAD

**Issue by postylem** [quarto-dev/quarto-cli#274]
The mouse-hover popups for citations in Revealjs slides are quite narrow with the default font sizes, which means that they often flow off the bottom of the presentation, when there is more than one citation. 

For instance:

<img width="400" alt="Screen Shot 2022-01-19 at 22 57 43" src="https://user-images.githubusercontent.com/5202957/150270671-37d1437b-ec5c-40ec-a71d-3e11340e877d.png">

I think the setting for what this popup looks like inherited from the setup for rendering HTML (where it is not an issue).  I notice it's possible to improve with a quick hack by making the window wider, by raising `maxWidth` here:
https://github.com/quarto-dev/quarto-cli/blob/b85ce46449e1ee5bcd1d177bb8c88f2ffdc1954b/src/resources/formats/html/templates/quarto-html.ejs#L225

But perhaps this should be addressed in a somewhat more comprehensive way (perhaps smaller typeface for hover citations/footnotes in Revealjs would be better in general?)

**Comment by jjallaire** [comment]
Thanks for reporting this! I've increased the maxWidth to 700 and reduced the font size in this commit: https://github.com/quarto-dev/quarto-cli/commit/37c99438e8e7fb2c0b623e8695687241283bd40e
