### ISSUE TITLE
Figures not identified to cross reference

### ISSUE THREAD

**Issue by GraceEMc** [quarto-dev/quarto-cli#2742]
### Bug description

I am trying to cross reference figures in a quarto book based of the example. It was inserted using the visual editor and uploaded to the images folder
![image](https://user-images.githubusercontent.com/89376037/194209820-c9f94a49-7e2a-4ca1-8f60-a9747d186e57.png)

But the figure is not showing as a cross reference
![image](https://user-images.githubusercontent.com/89376037/194209966-c9b7cd03-cff0-45dc-9fa9-d6692630d7a5.png)

How can I fix this? Am I missing something?

2022.07.2 Build 576
Windows 10

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by ruboerner** [comment]
In order for a figure to be cross-referenceable, its label must start with the fig- prefix. In your case, a valid label would be `#fig-optc`.

**Comment by GraceEMc** [comment]
Thank you!
