### ISSUE TITLE
using subfolders in bibliography does not work

### ISSUE THREAD

**Issue by ati-ozgur** [quarto-dev/quarto-cli#2755]
### Bug description

When we use sub folder name in bibliography keyword in _quarto.yml, we get error.

For example:

`bibliography: references.bib`

works, but

`bibliography: bibFilesAndDocuments/references.bib`

gives following error:

```
File bibFilesAndDocuments.bib not found in resource path
ERROR: File bibFilesAndDocuments.bib not found in resource path
```

I am using Windows 10 with Quarto version 1.1.251

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report. Can you send us a full reproducible example so we can check this on our side?

**Comment by ati-ozgur** [comment]
It took me some time to replicate.

You need to have a references.qmd file in your project and it should be multiple qmd file project otherwise it works as expected.

# References {.unnumbered}

::: {#refs}
:::

I attached multiple file project which replicates problem.
If you comment above file in _quarto.yml, it works.

# comment below to see render works
    - main-files/references/references.qmd
   


[bug-report-quarto-for-bibliography.zip](https://github.com/quarto-dev/quarto-cli/files/9731666/bug-report-quarto-for-bibliography.zip)

**Comment by dragonstyle** [comment]
I was not able to ever reproduce the error `File bibFilesAndDocuments.bib not found in resource path`, I was able to find an error regarding the `ieee.csl` file not being found, which indeed was a bug (and I fixed).
