### ISSUE TITLE
`layout` attribute outside of code chunk doesn't work without `result: asis`

### ISSUE THREAD

**Issue by jmbarbone** [quarto-dev/quarto-cli#2761]
### Bug description

Using the `layout` attribute outside of a code chunk is ignored unless `result: asis` is also specified.

````qmd
---
format: html
---

## in chunk

The `layout` attribute works fine inside chunk

```{r}
#| layout-nrow: 1
plot(1:10)
plot(10:1)
```


## outside

The `layout` attribute seems to be ignored

::: {layout-nrow=1}

```{r}
plot(1:10)
plot(10:1)
```

:::


## `results: asis`

Unless `results: asis`?

::: {layout-nrow=1}

```{r foo}
#| results: asis
plot(1:10)
plot(10:1)
```

:::
````

![image](https://user-images.githubusercontent.com/38573843/194638379-0878c124-518b-40be-af1d-61a8594ae6eb.png)

quarto version v1.1.251

```
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/New_York
 date     2022-10-07
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   2.18 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report! We'll be looking into an overhaul of the figure and layout code in 1.3 and we will address the problem when we do that.

**Comment by cscheid** [comment]
Ok, so looking at this again, and I no longer think this is a bug. 

Is there a reason you need the second syntax to work? laying out multiple computational images in a cell is supposed to happen with yaml as opposed to external divs.
