### ISSUE TITLE
Allow pandoc find CSL files

### ISSUE THREAD

**Issue by jakubkaczor** [quarto-dev/quarto-cli#2764]
### Bug description

I have a [chicago-fullnote-bibliography.csl](https://www.zotero.org/styles/chicago-fullnote-bibliography-16th-edition) file placed in ~/.local/share/pandoc/csl/ directory. I can convert the following file with `pandoc` and also with `quarto pandoc`, but using `render` or `preview` subcommands raises “File chicago-fullnote-bibliography.csl not found in resource path”.
``` qmd
---
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for
    deoxyribose nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: https://www.nature.com/articles/171737a0
  language: en-GB
csl: chicago-fullnote-bibliography
---
Test[@WatsonCrick1953].
```
I am not sure if it is a bug or if it's intended, but as Quarto uses pandoc under the hood, I think the expected behavior is so that pandoc can find files in its data-dir, that is ~/.local/share/pandoc. I am running quarto 1.1.251 on Arch Linux.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by njbart** [comment]
I've already [raised concerns](https://github.com/quarto-dev/quarto-cli/discussions/2331) that currently one cannot specify filters or CSL style files simply by their filename, as one used to be able to do with pandoc and Rmarkdown, but that  users seem to be expected to always either copy these files to a current working directory or use a full path, something I perceive as highly tedious and annoying.

I’ll reiterate that I do not think this is a good solution. Ideally quarto should have a user data directory like pandoc, though not necessarily the same as pandoc, and perhaps only optional and to be enabled e.g. by a flag in a site-wide `.quarto` preferences file or similar.

In addition, I think a good “batteries-indcluded” approach would be to install, together with quarto, a number of popular CSL style files in such a user data directory (e.g. `apa.csl`, `chicago-author-date.csl`, `chicago-fullnote-bibliography.csl`, `ieee.csl` and some others, just like Zotero does upon installation). quarto could also, just like Zotero, regularly update the styles installed in such a directory from the official CSL repository. This could also make it easier for users to easily try out a few different CSL styles, and generally get more familiar with CSL.

**Comment by bhattmaulik** [comment]
I think instead of putting the file in some folder, you can specify
`csl: https://www.zotero.org/styles/chicago-fullnote-bibliography-16th-edition`
in your code. This would allow you to render the quarto document or project.

**Comment by dragonstyle** [comment]
Just to confirm - in Quarto we don't currently support Pandoc's data-dir. As @bhattmaulik and @njbart suggest we currently require you to place a path to the CSL file in the document, a shared `_metadata.yml` file, or a project file (`_quarto.yml`). In general we've found that use of the data-dir may be a hindrance to reproducibility of the document (since it relies on an ambient property of the machine that the document is rendered on) and we've also seen users experience unexpected behaviors that can be troublesome to debug when things are resolved again the data-dir silently.

I'm personally more open to @njbart suggestion regarding 'batteries included' style approach to build in CSL files. We do that in a number of places (allow users to specify built in names OR a path to a file) and that might make sense here too.

**Comment by jakubkaczor** [comment]
> 



> I think instead of putting the file in some folder, you can specify `csl: https://www.zotero.org/styles/chicago-fullnote-bibliography-16th-edition` in your code. This would allow you to render the quarto document or project.

Thank you for the suggestion. Not specifically what I was looking for, but may come handy in the future. 😉

**Comment by jakubkaczor** [comment]
> I've already [raised concerns](https://github.com/quarto-dev/quarto-cli/discussions/2331) that currently one cannot specify filters or CSL style files simply by their filename, as one used to be able to do with pandoc and Rmarkdown, but that quarto users seem to be expected to always either copy these files to a current working directory or use a full path, something I perceive as highly tedious and annoying.
> 
> I’ll reiterate that I do not think this is a good solution. Ideally quarto should have a user data directory like pandoc, though not necessarily the same as pandoc, and perhaps only optional and to be enabled e.g. by a flag in a site-wide `.quarto` preferences file or similar.
> 
> In addition, I think a good “batteries-included” approach would be to install, together with quarto, a number of popular CSL style files in such a user data directory (e.g. `apa.csl`, `chicago-author-date.csl`, `chicago-fullnote-bibliography.csl`, `ieee.csl` and some others, just like Zotero does upon installation). quarto could also, just like Zotero, regularly update the styles installed in such a directory from the official CSL repository. This could also make it easier for users to easily try out a few different CSL styles, and generally get more familiar with CSL.

@njbart, thanks for pointing me to this discussion, I looked into issues, thus didn't see it. I read into and saw that discussion there is broader. That is regarding CSL, filters and data dir. Perhaps renaming it would be beneficial?

**Comment by jakubkaczor** [comment]
> Just to confirm - in Quarto we don't currently support Pandoc's data-dir. As @bhattmaulik and @njbart suggest we currently require you to place a path to the CSL file in the document, a shared `_metadata.yml` file, or a project file (`_quarto.yml`). In general we've found that use of the data-dir may be a hindrance to reproducibility of the document (since it relies on an ambient property of the machine that the document is rendered on) and we've also seen users experience unexpected behaviors that can be troublesome to debug when things are resolved again the data-dir silently.
> 
> I'm personally more open to @njbart suggestion regarding 'batteries included' style approach to build in CSL files. We do that in a number of places (allow users to specify built in names OR a path to a file) and that might make sense here too.

@dragonstyle, thanks for clarification. I will continue in the discussion @njbart pointed me to.
