### ISSUE TITLE
Changing `resource-path` raises error

### ISSUE THREAD

**Issue by jakubkaczor** [quarto-dev/quarto-cli#2765]
### Bug description

Having
``` qmd
---
resource-path: .
---
```
in the file, executing `quarto render main.qmd` results in
```
pandoc
  to: html
  output-file: main.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  resource-path: .

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en

Aeson exception:
Error in $: parsing [] failed, expected Array, but encountered String
```
Note the last two lines. `quarto pandoc` doesn't raise this exception.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jakubkaczor** [comment]
> We should have a better error message than this, but what the message is saying is that you should provide an _array_ of strings, rather than a single string.

But when I use an array, I get this:
```
ERROR: Validation of YAML front matter failed.
ERROR: In file main.qmd
(line 2, columns 16--18) Key resource-path has value [.], which must be a string
1: ---
2: resource-path: [.]
                  ~~
3: ---
✖ The value [.] is an array.
ℹ The error happened in location resource-path.

ERROR: Render failed due to invalid YAML.
```
Pandoc doesn't raise any errors with string, nor with array.

**Comment by cscheid** [comment]
Ok, that's clearly a bug on our side, sorry about that. There seems to be a mismatch between the schema for validation and our usage. I'll investigate.

**Comment by cscheid** [comment]
@jjallaire I think our schema is wrong here, but I want to confirm with you.

This compiles and succeeds:

```
---
resource-path: ["a-path:another-path"]
validate-yaml: false
---

Hello.
```

But this crashes _pandoc_:

```
---
resource-path: .
---
```

I think Pandoc is expecting an array of strings rather than what we are saying in the schema. I've opened https://github.com/quarto-dev/quarto-cli/pull/2804 to track.
