### ISSUE TITLE
website: `resources` option resulted in non-output files/folders being copied into the output directory 

### ISSUE THREAD

**Issue by JulianTao** [quarto-dev/quarto-cli#277]
If the `resources` option is enabled for a site project, after rendering, almost everything in the project directory is copied into the output directory. These include, for example, the README files, the `.git` and `.quarto` directories. 

Previously, when I did not include the `resources` option, only the rendered outputs, the linked resources, and the site-libs were generated in the output directory.

It smells like a bug.

I created a [Github repo](https://github.com/JulianTao/site_resrc_tes) to explain the behavior and hopefully, it can be reproduced.

A detailed explanation of the steps and command line outputs are included in the [README file](https://github.com/JulianTao/site_resrc_tes#readme).

**Comment by jjallaire** [comment]
That's definitely a bug! Will hopefully have a fix very soon (thanks as always for reporting....)

**Comment by jjallaire** [comment]
This was two bugs for the price of one! :-) Fixed here (https://github.com/quarto-dev/quarto-cli/commit/48fdd92b16c7008816a041bc649f189819f45a20) and here (https://github.com/quarto-dev/quarto-cli/commit/6da78c322f9f56572e3a6533c1336fc38470f978)
