### ISSUE TITLE
Embed word files and pdf files into quarto book projects   

### ISSUE THREAD

**Issue by zawkzaw** [quarto-dev/quarto-cli#278]
We have already created some word files or or pdf files while we make some qmd files afresh. How we can embed or integrate these files into quarto book projects and  table of contents with correct new page numbers for integrated files?

Thanks in advance

Ko Ko Zaw

**Comment by jjallaire** [comment]
The best way to do this is to convert your Word and PDF files into markdown. For Word, you can use Pandoc as follows:

```bash
quarto pandoc article.docx --to markdown --output article.qmd
```

For PDF files you'll want to first convert them to a format like Word (e.g. via https://www.adobe.com/acrobat/online/pdf-to-word.html) that can be read directly from Pandoc.

**Comment by zawkzaw** [comment]
Thanks for suggesting the solution.
