### ISSUE TITLE
`quarto render` breaks hugo shortcodes by turning quotes into smart quotes

### ISSUE THREAD

**Issue by cedricbatailler** [quarto-dev/quarto-cli#2783]
### Bug description

Hello there, and before anything, thanks for the terrific work.

I'm in a situation where I don't think that quarto is working as intendend. I want to use [hugo shortcodes](https://gohugo.io/content-management/shortcodes/) inside a quarto document and this feature is documented on the [quarto website](https://quarto.org/docs/output-formats/hugo.html#shortcodes). However, when I am trying to use this feature, the quotes inside the shortcodes are transformed into smart quotes which breaks the code. 

Here is an example quarto document, `test.qmd`.

```
---
format: hugo
---

{{< figure src="/media/spf13.jpg" title="Steve Francia" >}}

{{{< figure src="/media/spf13.jpg" title="Steve Francia" >}}}
```

And here is the rendered `test.md` document.

```
---
format: hugo
---

{{< figure src=“/media/spf13.jpg” title=“Steve Francia” >}}

{{< figure src=“/media/spf13.jpg” title=“Steve Francia” >}}
```

I am almost certain that I had not this problem before (looking back to some old rendered files). I run Quarto version 1.2.188 on a Win11 computer.

Let me know if I can be of any help!

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jjallaire** [comment]
@cedricbatailler, yes this did indeed regress, thanks for letting us know!

Fix is here: https://github.com/quarto-dev/quarto-cli/commit/5a16d05c7987ead3ecc3a8aa072851f0f73e0ced

Fix available now in the v1.2.203 pre-release: https://quarto.org/docs/download/prerelease.html
