### ISSUE TITLE
Error in margin formatting in Tufte example

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-cli#279]
The Tufte example [here](https://quarto-dev.github.io/quarto-gallery/page-layout/tufte.html) is rendering strangely in my browser. I tried both Safari and Chrome.

See attached screenshot.
<img width="1288" alt="Screen Shot 2022-01-23 at 4 30 53 PM" src="https://user-images.githubusercontent.com/25734232/150700701-f6a5a3c5-6172-4b39-bb86-b066dee1a573.png">

**Comment by jjallaire** [comment]
Thanks for catching that! Fixed here: https://github.com/quarto-dev/quarto-cli/commit/120db02644d66fd34bfc07ba2d080b93423c91ef
