### ISSUE TITLE
Wrong date locale when setting lang from command-line

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#2794]
### Bug description

For example with `a.md` containing

```
---
title: Titre
date: now
---

Bonjour.
```

rendering with `quarto render a.md -M lang=fr` produces:

![image](https://user-images.githubusercontent.com/2412819/195086805-22c723aa-1196-43b5-87df-fb9518256a6d.png)

The "DATE DE PUBLICATION" is correctly localized, but the date itself is in English.

Tested with quarto 1.1.251 and 1.2.203 on Pop!_OS 22.04.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
This appears to have the same underlying cause as #2793 -  we aren't properly dealing with certain metadata from command line args.

**Comment by dragonstyle** [comment]
This will be fixed in the next `1.3` pre-release build- ty for following up!
