### ISSUE TITLE
margin-footer image: get relative links bad when files in a folder

### ISSUE THREAD

**Issue by jcolomb** [quarto-dev/quarto-cli#2797]
I used the `margin-footer`option with an image.
Works well on the index and list pages, but if I go deeper, the image link is wrong. (.md files are in a folder called recipes_md)

the browser looks at http://localhost:7037/recipes_md/img/fondlogo.png 
instead of http://localhost:7037/img/fondlogo.png

**Comment by jjallaire** [comment]
For images declared in global content snippets you should use an absolute path to the image (e.g. `/img/fondlogo.png`). Note that Quarto will actually turn this into a relative link in generated HTML (so it won't undermine your ability to deploy the site at any URL path). We probably need to make this more clear in the docs.
