### ISSUE TITLE
Question about Quarto in github pages.

### ISSUE THREAD

**Issue by jamesthesnake** [quarto-dev/quarto-cli#280]
Can you render Quarto in github pages at the moment?

**Comment by jjallaire** [comment]
Yes you can. Here is how you publish a website on GH pages:

https://quarto.org/docs/websites/publishing-websites.html#github-pages

Here is how you publish a single article (w/ its own repo) on GH pages:

https://quarto.org/docs/output-formats/html-publishing.html#github-pages
