### ISSUE TITLE
Quarto unable to render PDF - lua filter error

### ISSUE THREAD

**Issue by jpmorr** [quarto-dev/quarto-cli#2803]
### Bug description

I've recently just updated quarto and I'm now unable to render pdfs. Instead I get a rather cryptic error message that I'm not able to directly relate to anything. Only thing that has changed since my last successful usage is my quarto version. Here's the current error message:

```
Error running filter C:/Users/xxxxx/AppData/Local/Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:
.../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:2003: attempt to index a nil value (global 'path')
stack traceback:
        .../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:1974: in local 'fn'
        .../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:4807: in function <.../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:4801>

```
This only affects pdf rendering, html rendering is still working fine.

```
>quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.198
      Path: C:\Users\jpmor\AppData\Local\Programs\Quarto\bin
      CodePage: unknown

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: C:/Users/xxxxx/anaconda3/python.exe
      Jupyter: 4.11.1
      Kernels: julia-1.4, julia-1.6, julia-1.7, juliapro_v1.5.4-1-1.5, pycharm-20203b08, python3, iota

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.1.3
      Path: C:/PROGRA~1/R/R-41~1.3
      LibPaths:
        - C:/Users/xxxxx/OneDrive/Documents/R/win-library/4.1
        - C:/Program Files/R/R-4.1.3/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
```

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jpmorr** [comment]
@cscheid  Annoyingly it seems to be project specific to this particular book - a very simple book from template works fine. I'm not quite sure what the lua filters are referring to, so not quite sure how to go about finding the problem with this specific project.

**Comment by cscheid** [comment]
@dragonstyle The line

```
.../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:2003: attempt to index a nil value (global 'path')
```

is from book-links.lua, and `git blame` has this:

```
76d5fe4de0 (Charles Teague 2021-08-03 14:54:58 -0400 69) function flatten(targetPath)
76d5fe4de0 (Charles Teague 2021-08-03 14:54:58 -0400 70)   local pathParts = path.split(targetPath)
a9fe37e66c (JJ Allaire     2021-11-01 11:20:11 -0400 71)   local resolvedPath = pandoc.List()
```

I think that is meant to be `pandoc.path`, right? I'll make a fix, but I assigned you so you can review.

**Comment by jpmorr** [comment]
@dragonstyle @cscheid Thanks for fixing this so quickly.
