### ISSUE TITLE
Improve repository description on GitHub

### ISSUE THREAD

**Issue by dumblob** [quarto-dev/quarto-cli#281]
This is just a nit pick but anyway :wink:.

Could you change "Quarto command line interface" to something more descriptive (I like the description in readme)?

This'd make it much easier to search through repos etc.

>Quarto is an open-source scientific and technical publishing system built on Pandoc. Quarto documents are authored using markdown, an easy to write plain text format.

(won't probably fit in the GitHub constraints, but nicely shows what I mean)

**Comment by jjallaire** [comment]
Thanks, just changed!
