### ISSUE TITLE
[feature question] plans for debugging capabilities?

### ISSUE THREAD

**Issue by romunov** [quarto-dev/quarto-cli#282]
Are there any plans of integrating debugging capabilities into this? It's not hard to imagine having a long report with many references and chunks and it would be nice to be able to debug this elegantly. Or at least have some verbose output that enables to trace the logic of the script. Looking forward to hear your thoughts on this.

**Comment by mcanouil** [comment]
I believe this to be resolved in the documentation and is improving over time with other opened issues.

- https://quarto.org/docs/troubleshooting/index.html

**Comment by cscheid** [comment]
I think this comment meant "debugging the execution", not "debugging quarto itself".

**Comment by mcanouil** [comment]
Hum, in this case is it not upon the engine/kernel used? 🤔

**Comment by romunov** [comment]
Verbose output at the minimum is in line with what I was after. Let's close this for now.
