### ISSUE TITLE
revealjs presentation - inconsistent handling of css link colors for body / footer elements

### ISSUE THREAD

**Issue by kmasiello** [quarto-dev/quarto-cli#2820]
### Bug description

For revealjs formatted presentation, the color of links and the page numbers in the footer are not controlled as expected by the CSS variable `$linkColor`.  

Expected behavior:
`$linkColor` and `$linkColorHover` should apply to links in the footer and the page numbers

Observed behavior:
Footer link color is changed with a different CSS variable called `$link-color`
Page number color is not affected by `$link-color` or `$linkColor`, but is affected by `$linkColorHover`

Reprex here:
https://github.com/kmasiello/reprex-footer-link

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Ok, we fixed it. Thanks for letting us know!

**Comment by kmasiello** [comment]
dazzling!
