### ISSUE TITLE
[Feature question] Marktext as a supported visual editor (?)

### ISSUE THREAD

**Issue by camilogarciabotero** [quarto-dev/quarto-cli#284]
Hi all,

I guess this was the new project @yihui mentioned in his [talk](https://www.youtube.com/watch?v=T24nt-d4cEg&t=3074s). Anyway, this project looks very promising regarding the next generation of publishing systems. 

I was wondering about the possibility that there will be a standalone visual editor with the quarto engine (later came across that this is being considered), and parallelly was wondering if [marktext](https://github.com/marktext/marktext/issues/2821) could also leverage on something like markdown or knitr to allow a coding experience inside the editor. So why not consider a combination of these two brilliant tools?

**Comment by jjallaire** [comment]
It would absolutely be possible to have marktext support the qmd format, and even to include commands for rendering and previewing quarto documents. That would be very cool!

As regards the visual editor, yes, we will eventually make that available standalone (not exactly sure when though).

**Comment by camilogarciabotero** [comment]
Hi @jjallaire 

That was a flash response, thank you. That would be awesome to see if this idea makes it through! Do you if there is any way to ping Ran Luo here or Felix Häusler (both contributors of Marktext)? My guess is that they would be willing to collaborate to improve Marktext experience!
