### ISSUE TITLE
Project profiles ignoring output-dir in _quarto-advanced.yml

### ISSUE THREAD

**Issue by cathblatter** [quarto-dev/quarto-cli#2840]
### Bug description

 I observe some unexpected behaviour when trying to use quarto project profiles: while the content in the body (defined with `:::{.content-visible when-profile="advanced"} ... :::` is correctly shown or hidden, the title and output-dir that should change are ignored. 

I've set up a project with: 

`quarto create-project test-proj`

and added the following files following [the steps here](https://quarto.org/docs/projects/profiles.html#profile-configuration): 

<details><summary> test-proj.qmd </summary>

```
## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.


:::{.content-visible when-profile="advanced"}

## only in advanced 
Some text
:::
```
</details>

<details><summary> _quarto.yml </summary>

```
project:
  title: "my website"
  type: website
```

</details>

<details><summary> _quarto_advanced.yml </summary>

```
project:
  title: "My Website (Advanced)"
  output-dir: _site-advanced
```

</details>

Observation:

- using `quarto render` creates a subdirectory `_site` with `test-proj.html` and the title "my website" with the correct content in body

- using `quarto render --profile advanced` overwrites test-proj.html in the `_site` subdirectory and keeps the old title "my website" (unexpected) - but the content in the body (## only in advanced - Some text) is shown as expected

Thus somehow the `output-dir:`and the `title`is not being used from the `_quarto-advanced.yml ` - I am not sure if this is a bug or if I am not applying it correctly - thanks

<details> <summary> Sessioninfo & quarto check </summary>

RStudio: 2022.07.0 Build 548
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

```
[✓] Checking Quarto installation......OK
      Version: 1.2.210
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.5
      Path: /usr/local/opt/python@3.9/bin/python3.9
      Jupyter: 4.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Versions/4.2/Resources
      LibPaths:
        - /Users/cb/Library/R/4.0/library
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

</details>

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jjallaire** [comment]
Profiles are a new feature of Quarto v1.2. When I run the code/scenario you describe above locally I get the expected `_site-advanced` directory. What version of Quarto are you running? If you are indeed running Quarto v1.2 it would be great if you could create a simple git repo with a site that recreates the problem (just so I am 100% sure to be running the same code you are).

**Comment by cathblatter** [comment]
thanks for your reply! this is the repository I set up: https://github.com/cathblatter/test-proj 
and out of better options I recorded my workflow, showing that it creates _site (not _site-advanced) and while the content of the body is shown, the title belongs to the 'basic' website. 

https://user-images.githubusercontent.com/24943957/196511286-b91032ab-3f98-4b56-8750-f458377992bc.mov

It might very well be that I just misunderstood the workflow - I appreciate your feedback, thanks (the profile feature sounds VERY helpful for my work!)


corresponding sessions/versions:

<details><summary>quarto check</summary>

```
[✓] Checking Quarto installation......OK
      Version: 1.2.225
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources
      LibPaths:
        - /Users/blacat01/Library/R/arm64/4.2/library
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      rmarkdown: 2.16

[✓] Checking Knitr engine render......OK

```

</details>

<details><summary>session info</summary>

```
xfun::session_info()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6, RStudio 2022.7.2.576

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  compiler_4.2.1  crayon_1.5.1   
  graphics_4.2.1  grDevices_4.2.1
  methods_4.2.1   rstudioapi_0.14
  stats_4.2.1     tools_4.2.1    
  utils_4.2.1     xfun_0.32      
```

</details>

**Comment by jjallaire** [comment]
I see the problem, it needs to be `_quarto-advanced.yml` (with a dash) rather than `_quarto_advanced.yml` (with an underscore)

**Comment by cathblatter** [comment]
mea culpa - thanks for spotting this! 
now it works as expected - small feedback though: I was really baffled by the fact that part of advanced profile seemingly got respected (cause the content in the body was shown) and only the title and output-dir was not...but maybe thats just me.
