### ISSUE TITLE
Remote jupyter server for cell rendering (like vscode already supports)

### ISSUE THREAD

**Issue by fradav** [quarto-dev/quarto-cli#2852]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2829

<div type='discussions-op-text'>

<sup>Originally posted by **fradav** October 13, 2022</sup>
Hi all,

Visual Studio Code already supports running “in-editor” cells on remote jupyter just by specifying an url to a jupyter server directly

![image](https://user-images.githubusercontent.com/701587/195567092-68205426-5247-4085-91b9-f919be513104.png)

As for quarto, my understanding is it isn’t possible. There are use cases where it would be very practical or even necessary to edit/render everything but jupyter cells by a locally installed quarto, and also render jupyter cells in a remote server, who sometimes doesn’t even offer the possibility to run or install quarto (Jupyterhub containerized instances for example).

I am a member of the staff of an online journal centered on reproductible research and we use quarto as the mandatory format and tooling for submissions. We would like to offer our authors and editors the possibility to run computations inside article submissions on external (possibly heavily equipped, cluster-like or with gpu) computational ressources, and let authors/editors handle the editing/rendering on their local computers.

Regards,
</div>

**Comment by cscheid** [comment]
Hi - if folks haven't responded to your original thread, it's probably because no one has information that can help. Please refrain from creating new threads in this format.
