### ISSUE TITLE
PDF is cropping ggplot figures

### ISSUE THREAD

**Issue by flyaflya** [quarto-dev/quarto-cli#2861]
### Bug description

I have a very simple `qmd` file (add three backticks to close chunk at end):

````
---
format: pdf
---

```{r}
#| warning: false
#| message: false
library(tidyverse) ##load for plotting

ggplot(data = starwars %>% drop_na()) +
  geom_point(mapping = aes(x = height, y = mass)) +
    annotate("text", x = 150, y = 750, 
             label = "Annotation to show it is not a font issue.")
    labs(caption = "A caption that gets cropped.")
# add three backticks here to close chunk... having trouble getting markdown to work right here
```
````

In the below picture, you can see that the plot displays correctly on the left-hand side, but gets cropped improperly for pdf output (previewed on the right-hand side); the axis labels and ticks are gone.

![image](https://user-images.githubusercontent.com/17184441/195909773-b75a8464-3410-4a75-b966-31c46ad8676c.png)

I am using dev Quarto version 1.2.209 (needed a different bug to be fixed).  I cannot seem to downgrade Quarto to see if bug is in the current release.  Windows 10, RSTUDIO 2022.07.9 Build 548.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I think you're missing a `+` between `annotate()` and `labs()`. I also cannot reproduce this locally (on macOS):

<img width="841" alt="image" src="https://user-images.githubusercontent.com/285675/195913199-672e615e-7a77-4a32-8818-4924df93aabe.png">

**Comment by flyaflya** [comment]
Thanks for taking a look.  Yes, I am missing the `+` sign, although not the cause of the issue.  Not sure how to debug further... hoping a windows user can try it.  HTML output is perfect and I am experiencing the same issue when knitting .RMD to .pdf.

If it is the "dev" version causing my issue, anyone know how to downgrade Quarto?  I keep getting this message when trying to reinstall:

![image](https://user-images.githubusercontent.com/17184441/195918355-c706a3b6-57f7-4942-b866-e8426ee16a9d.png)

**Comment by flyaflya** [comment]
I think this is some local config issue for me.  my other Windows computer does not reproduce it either.

**Comment by baptiste** [comment]
I'm also finding it difficult to prevent knitr from cropping pdf figures. Looking at the source code, it seems crop is set to TRUE regardless of my knitr opts:

https://github.com/quarto-dev/quarto-cli/blob/574396e68882c41336e9f539f4aee7ace6485f03/src/resources/rmd/execute.R#L272

The following MRE illustrates the problem:

````
---
title: "test"
format: pdf
---


```{r setup, include=FALSE}
# knitr::knit_hooks$set(crop = function(...){})
knitr::opts_chunk$set(echo = FALSE, crop=FALSE)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```{r}
library(ggplot2)
ggplot() + theme(plot.margin = margin(t=2,b=2,unit='cm'))
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

````

<img width="634" alt="Screenshot 2022-10-16 at 14 25 02" src="https://user-images.githubusercontent.com/18970/196013574-de0464cf-88f4-4d5d-b806-0e4a2a6a5908.png">

As a workaround I can uncomment the line `knitr::knit_hooks$set(crop = function(...){})` to get the expected output


<img width="643" alt="Screenshot 2022-10-16 at 14 24 41" src="https://user-images.githubusercontent.com/18970/196013590-f277fa4d-2cd0-47fe-8b30-f3175be95815.png">

but one would expect `opts_chunk(crop=FALSE)` to prevent cropping without having to redefine the hook.

**Comment by remlapmot** [comment]
I had the same problem as in the first message in this issue, see rstudio/tinytex#391 for more info.

One way to fix this is to make an environment variable `TEXLIVE_WINDOWS_EXTERNAL_GS` set to the path of the `gswin32c.exe` in a standard installation of 32bit Ghostscript 9.56.1, which you can do as usual in Windows System settings or in the `texmf.cnf` file as follows
```
TEXLIVE_WINDOWS_EXTERNAL_GS = C:/Program Files (x86)/gs/gs9.56.1/bin/gswin32c.exe
```
(use whatever filepath you chose in your installation).
