### ISSUE TITLE
column-body-right not applied to table

### ISSUE THREAD

**Issue by lcnbr** [quarto-dev/quarto-cli#2878]
### Bug description

It seems I can't get tables to be fullwidth in the pdf output no matter what I try:

```
+---------------+---------------+--------------------+
| Fruit         | Price         | Advantages         |
+===============+===============+====================+
| Bananas       | $1.34         | - built-in wrapper |
|               |               | - bright color     |
+---------------+---------------+--------------------+
| Oranges       | $2.10         | - cures scurvy     |
|               |               | - tasty            |
+---------------+---------------+--------------------+

: Sample grid table. {.column-page-right}
```

this does not work in the pdf output

**Comment by lcnhb** [comment]
In the latex output, the longtable should in this case use \linewidth along with the lp directive!

**Comment by dragonstyle** [comment]
Ultimately there are two things at work here:

- Static tables are bypassing processing that is happening for computational tables
- computational tables are getting handled by wrapping them in a figure* environment, which is its own badness

I think in general, we need to let the tables be emitted by pandoc as is and we need to deal with them in the post processor.

Correct fixup is the adjust the column sizing to from using only column width:

```latex
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.7500}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
```

to using column width + the margin width (with sep):

```latex
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\marginparwidth + \marginparsep + \columnwidth - 2\tabcolsep) * \real{0.7500}}
  >{\raggedright\arraybackslash}p{(\marginparwidth + \marginparsep + \columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
```
