### ISSUE TITLE
Blog listing from metadata not sorted correctly with other listing items (date not converted to epoch milliseconds)

### ISSUE THREAD

**Issue by bpkent** [quarto-dev/quarto-cli#2880]
### Bug description

For a blog listing page, the sort date is not working properly when I try to combine a directory listing with a metadata listing. Here's my listing page config, that pulls in all of the posts in the current working directly and has one additional item that's specified as metadata:

````md
---
title: "Blog"
listing:
  contents:
    - "."
    - title: "My special blog post, with an external link"
      date: "2022-10-16"
      author: Brian Kent
      categories: [interviews]
      description: "I recently sat down with John Doe to talk about data science."
      href: https://www.johndoedatascience.com/interviews/briankent
  sort: "date desc"
  type: default
---
````

I expected all of the listing items to be sorted globally, but the metadata item is not (and ends up at the bottom). When I inspect the page source, I see that the items specified by directory have dates that have been converted to epoch milliseconds, while the metadata listing item has not been converted and remains a string.

So, for example, one of the regular blog posts has a date "2021-01-09" and the corresponding html div has `data-listing-date-sort=1610172000000`

```html
<div class="quarto-post image-right" data-index="23" data-categories="" data-listing-date-sort="1610172000000" data-listing-file-modified-sort="1665932827072" data-listing-reading-time-sort="2.67">
...
</div>
```

But the ad hoc, metadata-based listing item---which has date "2022-10-16"---has a div that looks like this

```html
<div class="quarto-post image-right" data-index="24" data-categories="interviews" data-listing-date-sort="2022-10-16" data-listing-file-modified-sort="null">
...
</div>
```

So the date just hasn't been converted to epoch milliseconds.

I'm using Ubuntu 20.04.5 with Quarto version 1.1.251. I also installed the latest Quarto pre-release 1.2.219 and see the same issue.

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thanks for reporting this! The fix for this should be available in the pre-release version  v1.2.222, available at:

<https://quarto.org/docs/download/prerelease.html>
