### ISSUE TITLE
`link-citations` not documented anywhere

### ISSUE THREAD

**Issue by mattwarkentin** [quarto-dev/quarto-cli#2893]
Hi,

I don't think the `link-citations` YAML parameter is documented anywhere and I think it is necessary to enable in order to get hyperlinked things, at least in PDF, in my testing.

The use of `colorlinks` and the `*color` set of parameters had no apparent affect unless `link-citations: true`, like with R Markdown. I found this out through some trial and error.

**Comment by dragonstyle** [comment]
Note we need to add the following to the document schema:

`link-citations`
`link-bibliography`
`notes-after-punctuation`

**Comment by dragonstyle** [comment]
Fixed in above commit
