### ISSUE TITLE
thanks in book

### ISSUE THREAD

**Issue by lcnhb** [quarto-dev/quarto-cli#2896]
### Bug description

There seems to be no way to have an aknowledgement section in a book. Ideally, this comes before the toc, and could either be directly in the metadata, or provided in a file. Probably even more generally it would be nice to be able to put things in the front, main and back matter explicitly.

**Comment by cscheid** [comment]
This should be possible with a custom template. (Custom sections, in general, will require a custom template.) https://quarto.org/docs/journals/templates.html#templates
