### ISSUE TITLE
[Feature request] Allow config of biblatex as citation processor

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [quarto-dev/quarto-cli#290]
As of now, AFAIK there is no such option as `citation-package: pandoc|natbib|biblatex` for the Quarto PDF output front matter. 
This works in R Markdown via `citation_package`, but as I've just tried, not in Quarto so far. 

There are some special features of `biblatex` such as back references from bibliography onto inline citations, which are handy during reading and refactoring even if not allowed in the final documents (to the best of my knowledge, this is not possible via `pandoc` citations processor, though I may be errant). Notably, in LaTeX these are enabled via options `backref=true`, and for R Markdown this can be enabled with options `biblatexoptions: [backref=true]`, which is not supported in Quarto PDF options and ignorred if placed in YAML root. 

I understand that I can just add the pandoc flag `--biblatex` in cmd command to force biblatex citations processing and I even tried to write `--variable="biblatex:backref=true"` but the latter did nothing since this is probably not how this works. 

Of course I understand that currently I can just retain the `.tex` file and then run `latexmk` or any other engine with reference resolution pipeline.

Thanks in advance for any response!

**Comment by dragonstyle** [comment]
Hello! This should already be possible now, using YAML such as:

```
format:
  pdf:
    cite-method: biblatex
    biblatexoptions:
      - "backref=true"
```

There is a little more information about PDF bibliography / citation processing [here](https://quarto.org/docs/output-formats/pdf-basics.html#citations) (though not a ton more than listing the options)... Hope this gets you going!

**Comment by gjirokastrelbasanit34** [comment]
Thank you very much for this hint, and I apologise again for missing out this part of documentation.

**Comment by dragonstyle** [comment]
No worries- appreciate you raising it as the docs were pretty hard to find where they were (they definitely weren’t where you’d expect them to be!)… good luck!

**Comment by pipme** [comment]
Hi @dragonstyle, I tried the setting but it doesn't work correctly. My quarto version is 1.3.361. Then I tried to keep the quarto-generated tex file and compile directly with [pdflatex+biber in a Makefile](https://github.com/pipme/pipme.github.io/blob/main/posts/2023-06-10-Quarto-set-up/Makefile) and it output backlinks in reference correctly. Please find my qmd file in [here](https://github.com/pipme/pipme.github.io/blob/main/posts/2023-06-10-Quarto-set-up/index.qmd). 

Thanks!

**Comment by dragonstyle** [comment]
To help with this I need more information - a full reproducible example would be very helpful.

I suggest that a great place to start since we aren't sure this is a bug with Quarto yet, is the [discussions](https://github.com/quarto-dev/quarto-cli/discussions), which are a great place to pose initial questions and debug a little in the community of experts until we've narrowed down the issue to a Quarto bug. This is especially helpful if you're doing something a bit more advanced with formats like LaTeX since they often bring their own complexity independent of Quarto.

**Comment by pipme** [comment]
Thanks, I put a reproducible example in #5895.
