### ISSUE TITLE
Trying to use quarto on Windows

### ISSUE THREAD

**Issue by carlkl** [quarto-dev/quarto-cli#291]
Hi!

I'm trying to use `quarto` on windows with a specific Python installation, that is available on the `PATH` environment variable. Both `python` and `jupyter` can be started from the command line. Unfortunately `quarto` locates a very different Python installation that comes with VS Studio and that I never want to use.

**quarto check**

```
[>] Checking Quarto installation......OK
      Version: 0.3.37
      Path: C:\Users\devel\AppData\Local\quarto\bin\

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.7.8
      Path: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/python.exe   <<< WRONG
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter
......
```

Q: how to specify a dedicated python installation for quarto?

**Comment by jjallaire** [comment]
On Windows we use the [Python Windows Launcher](https://docs.python.org/3/using/windows.html#launcher) rather than the PATH (as this has much greater configurability than the PATH). Details are here: https://quarto.org/docs/getting-started/installation.html#jupyter. I

**Comment by carlkl** [comment]
Python Windows launcher:
```
Unlike the PATH variable, the launcher will correctly select the most appropriate version 
of Python. It will prefer per-user installations over system-wide ones, and orders by language 
version rather than using the most recently installed version.
```
Unfortunately this doesn't work for portable Python environments like winpython as they do not write anything in the registry. 

Can I request to change this behaviour with the help of an environment variable?

**Comment by jjallaire** [comment]
Yes, we will add a `QUARTO_PYTHON` environment variable (will try to do that later today)

**Comment by carlkl** [comment]
no hurry, please do so if time permits. It's Open Source...
this project looks very promising (found it via HN),

**Comment by jjallaire** [comment]
This has been implemented here (https://github.com/quarto-dev/quarto-cli/commit/9aab5bdb83ae567b4a38c9374a58412dea41a8de), docs updated here: https://quarto.org/docs/getting-started/installation.html#python-versions

**Comment by carlkl** [comment]
Works! Many thanks for your great support!
