### ISSUE TITLE
minimal html output still has lot of unneeded javascript in the output

### ISSUE THREAD

**Issue by drrajeshtalluri** [quarto-dev/quarto-cli#292]
When using `minimal: true` option for HTML output there is a lot of extra javascript included after the body in the html source output. Is this intended?

**Comment by drrajeshtalluri** [comment]
Closing this as I was mistaken. It only shows up in the preview for error debugging. Thanks!

**Comment by jjallaire** [comment]
Correct, that code is dynamically injected for quarto preview but not in the actual file.
