### ISSUE TITLE
Quarto doesn't parse \( \) (inline LaTeX math) correctly with pdf and html documents

### ISSUE THREAD

**Issue by maikol-solis** [quarto-dev/quarto-cli#2924]
### Bug description

In any quarto project (website, book, etc) with pdf/latex output, if you type something like  
```
\(F_{X}(x)=\operatorname{Pr}(X \leq x)\).
```

quarto parses it as 

```
(F\_\{X\}(x)=\operatorname{Pr}(X\leq x)).
```

Causing the following error 

```
Missing $ inserted.
<inserted text> 
                $
l.241 ... (F\_\{X\}(x)=\operatorname{Pr}(X 

You may need to $ $ around an expression in this file.
see index.log for more information.
```

For html document, here  is the final output 

![image](https://user-images.githubusercontent.com/4078489/196559896-6b7f1cf5-4d26-4d5d-a80f-83148734a218.png)

The same code in `bookdown` looks like this 

![image](https://user-images.githubusercontent.com/4078489/196559988-f8b9f4db-91c0-42cf-afaf-b01432e30e2a.png)

The `\( \)` is the "newer" (LaTeX) inline mode of the classic `$ $` (TeX). A discussion about their features is here: https://tex.stackexchange.com/a/513/42627

I think that quarto should be support both ways to guarantee maximum compatibility. 

Here is a full qmd example 

```
---
title: "Latex inline \( \) doesn't work"
format: pdf
---


\(F_{X}(x)=\operatorname{Pr}(X \leq x)\).
```

My quarto version is ` 1.2.226`. 

Best. 
 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by maikol-solis** [comment]
The problem seem related to pandoc. 

If `latex.qmd` is this document

```
---
title: "Latex inline doesnt work"
format: pdf
---

\(F_{X}(x)=\operatorname{Pr}(X \leq x)\).

$F_{X}(x)=\operatorname{Pr}(X \leq x)$.
```

Then `pandoc  latex.qmd -o latex.tex` parses it to 

```
(F\_\{X\}(x)=\operatorname{Pr}(X \leq x)).

\(F_{X}(x)=\operatorname{Pr}(X \leq x)\).
```

The first form is incorrect, while the second one is valid.

**Comment by maikol-solis** [comment]
I found the solution. 

The command,

```
pandoc  latex.qmd -f markdown+tex_math_single_backslash  -o latex.tex
```

parses correctly both inline LaTeX inputs 

```
\(F_{X}(x)=\operatorname{Pr}(X \leq x)\).

\(F_{X}(x)=\operatorname{Pr}(X \leq x)\).
```

How could this option be enabled by default in quarto?

**Comment by njbart** [comment]
Try 

```
---
from: markdown+tex_math_single_backslash
---
```

as described in the [pandoc manual](https://pandoc.org/MANUAL.html), and recommended for quarto, e.g., [here](https://github.com/quarto-dev/quarto-cli/issues/1303#issuecomment-1176700039).

Furthermore, I do not think it is necessary or desirable to change the default settings of quarto, especially since this would mean a deviation from pandoc that would cause more confusion than benefit.

**Comment by maikol-solis** [comment]
Thank you very much for the hint. I didn't know about this option.

Just to be sure. If I want this behavior globally, the `from` tag should be in the `_quarto.yml` or elsewhere?

**Comment by cscheid** [comment]
@maikol-solis Yes, `_quarto.yml` should be the place to do it.
