### ISSUE TITLE
[Feature request] Render reference keys to references when converting to plain markdown

### ISSUE THREAD

**Issue by pat-alt** [quarto-dev/quarto-cli#293]
In R Markdown you can specify the output format of an .Rmd document to .md like so

```
---
output: github_document
bibliography: bib.bib
---
```
and generate a plain markdown document with bibliographic references. This is very useful for writing tutorials that include references and hosting them on Github (pages), for example.

When I run

`quarto render my_tutorial_with_references.qmd --to markdown` 

the references are not rendered (even though they are rendered when rendering to HTML). 

Would much appreciate support for this (or in case I'm missing something and this can already be achieved in some other way, fire at me!)

Many thanks - awesome project!

**Comment by cderv** [comment]
@pat-alt what is the content of the Rmd file with this header ? 

I am just curious to reproduce and see what flag to pass to quarto. I believe something working with **rmarkdown** should work with Quarto. 🤔

**Comment by pat-alt** [comment]
Thanks for your response @cderv. After doing the whole thing in R Studio I just realised that the following does what I want:

`quarto render my_tutorial_with_references.qmd --to gfm`

Have created a minimal working example [here](https://github.com/pat-alt/quarto-example) including a plain text .qmd

Thanks again!

**Comment by cderv** [comment]
Great ! thanks !
