### ISSUE TITLE
No formatting when specifying 'output-file' and 'output-ext' in YAML header

### ISSUE THREAD

**Issue by daranzolin** [quarto-dev/quarto-cli#2931]
### Bug description

I'm on Windows 10 running RStudio 2022.07.2 Build 576. I created a new Quarto Project with the following YAML header:

```
---
title: "reprex-quarto"
output-file: "test"
output-ext: "html"
---
```

Per @cscheid  request on quarto-dev/quarto-r#89, when I include an `output-file` and `output-ext` in the YAML header of a quarto document, and click the 'Render' button, the corresponding document is created, but sans formatting. In the 'Background Jobs' tab I see an error: `ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123)`. When I open 'test.html' it looks like this:

![reprex-quarto](https://user-images.githubusercontent.com/9537384/196743908-356d1961-3641-4df9-af85-d742c49e59fc.PNG)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Have you tried replacing `output-file: "test"` with `output-file: "test.html"`? I think we expect these to have extensions.

**Comment by cscheid** [comment]
Hm. I can't repro this on the latest pre-release version and macOS:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/285675/196750418-844e6761-2188-4dc6-8659-8f28563e4d52.png">

produces this:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/285675/196750478-934e473d-5f37-4929-b220-0209d6ddd4b8.png">

**Comment by cderv** [comment]
@cscheid I can't reproduce either on Windows with Quarto 1.2.231

@daranzolin can you share more maybe on your project setup or tools versions ? 

thank you

**Comment by daranzolin** [comment]
Hmm, I'm not sure what else to share. 

```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)
```

Here's the output of the Background Job when I specify the output-file:

```
pandoc 
  to: html
  output-file: 'C:\Users\dranzolin\Documents\Projects\reprex-quarto\test.html'
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  editor: visual
  title: reprex-quarto
  
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123)
```

Here's the directory tree. I'm not sure why the `reprex-quarto_files` directory appeared, as I don't have that directory in the project where I originally observed this behavior.

```
├── reprex-quarto.html
├── reprex-quarto.qmd
├── reprex-quarto.Rproj
├── reprex-quarto_files
│   ├── libs
│   │   ├── bootstrap
│   │   │   ├── bootstrap-icons.css
│   │   │   ├── bootstrap-icons.woff
│   │   │   ├── bootstrap.min.css
│   │   │   └── bootstrap.min.js
│   │   ├── clipboard
│   │   │   └── clipboard.min.js
│   │   └── quarto-html
│   │       ├── anchor.min.js
│   │       ├── popper.min.js
│   │       ├── quarto-syntax-highlighting.css
│   │       ├── quarto.js
│   │       ├── tippy.css
│   │       └── tippy.umd.min.js
│   └── mediabag
├── test.html
└── _quarto.yml
```

To recap: `reprex-quarto.html` looks good, it was only when I specify the output-file that `test.html` looks bad.

**Comment by cscheid** [comment]
We need your actual .qmd file.

**Comment by daranzolin** [comment]
Oh, sorry! Below:

```
---
title: "reprex-quarto"
output-file: "test.html"
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

```{r}
1 + 1
```
```

**Comment by cscheid** [comment]
I still cannot reproduce this. I get the following:

```
$ quarto render 2931.qmd


processing file: 2931.qmd
  |.......................                                               |  33%
  ordinary text without R code

  |...............................................                       |  67%
label: unnamed-chunk-1
  |......................................................................| 100%
  ordinary text without R code


output file: 2931.knit.md

pandoc
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: reprex-quarto

Output created: test.html
```

And opening this file on a web server shows this:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/285675/197047641-dfb679ef-5690-4d9c-8f51-33b3a851d906.png">

**Comment by cscheid** [comment]
Can you share the generated .html that you're getting?

**Comment by daranzolin** [comment]
I can't share HTML files here, but does this link work? https://drive.google.com/file/d/1XD1BGrtI2ybTzQXQ1H0B1Q2cDDN-xodh/view?usp=sharing

**Comment by cderv** [comment]
Also I did try as close as your project

* I created a new RStudio project called `reprex-quarto`
* I created a new file called `reprex-quarto.qmd` and pasted your code.
* It renders ok - I don't see the full path name in the Background job logging and file it correctly rendered.

I am using Quarto 1.2.231
