### ISSUE TITLE
Custom fonts for revealjs presentation half working

### ISSUE THREAD

**Issue by Eric-Hacker** [quarto-dev/quarto-cli#294]
I'm trying to use a custom font in a presentation. I have a .sscs file with the following lines:
`@import url(./nunito.css);`
`$font-family-sans-serif: Nunito, sans-serif !default;`
`$presentation-heading-font: Nunito, sans-serif !default;`

When I run preview, the heading font is done correctly. The body text is not and is still the default font. I also get a warning `  /Presentation_files/libs/revealjs/dist/theme/nunito.css (404: Not Found)`

Now obviously I can copy the CSS file and related font files to the above referenced location after the first time I try running preview, but that seems like an ugly hack. It also doesn't explain how the font is working for headings. I can't figure out how it is working in one place and not in the other.

Here is the beginning of quarto.css `@import"./nunito.css";@import"./fonts/source-sans-pro/source-sans-pro.css";:root{--r-background-color: #660000;--r-main-font: Nunito, sans-serif;--r-main-font-size: 40px;--r-main-color: #ff0;--r-block-margin: 12px;--r-heading-margin: 0 0 12px 0;--r-heading-font: Nunito, sans-serif;`
That is the only file in the libs directory tree that contains "nunito". 

I had this font working in Revealjs, but its markdown isn't as nice as Quarto, and I thought I'd learn Quarto for other projects in the future. This isn't urgent, I'm old enough to have learned I need to play with something before I rely on it for an important project.

Thank you for a cool publishing platform.

**Comment by jjallaire** [comment]
Currently referencing local fonts in Reveal theme doesn't work. However, you can do the following:

```scss
/*-- scss:defaults --*/
@import url('https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,300;0,700;1,300;1,700&display=swap');
$font-family-sans-serif: Nunito, sans-serif !default;
$presentation-heading-font: Nunito, sans-serif !default;
```

**Comment by Eric-Hacker** [comment]
Thank you for the reply. I'll use externally referenced fonts.

Though since it half works, I'll admit there is a temptation to take a machine learning approach and iteratively change bits of the source code until I get the desired results. :)

**Comment by jjallaire** [comment]
We are hopefully soon going to enable SCSS `@use` statements in theme files (which will actually fully embed the referenced files)
