### ISSUE TITLE
Book structure doesn't explain index.qmd

### ISSUE THREAD

**Issue by fuhrmanator** [quarto-dev/quarto-cli#2941]
In a book project, `index.qmd` is required (else you get an error).

The documentation at https://quarto.org/docs/books/book-structure.html doesn't explain how `index.qmd` works in the context of a book project.

**Comment by jjallaire** [comment]
@dragonstyle Could we enhance these docs a bit to describe the specific role of `index.qmd` in books (and how it relates to docx and pdf output, I believe we made some changes to that in v1.2?)

**Comment by dragonstyle** [comment]
This is addressed here: 

[cfcf06c6f2523e645c5ceb57c4614f4ad8a0c245](https://github.com/quarto-dev/quarto-web/commit/cfcf06c6f2523e645c5ceb57c4614f4ad8a0c245)

which should be live on the website in a few minutes.

**Comment by cderv** [comment]
Related question some time after: https://github.com/quarto-dev/quarto-cli/discussions/4024
