### ISSUE TITLE
::: {.incremental} syntax return non-incremental list

### ISSUE THREAD

**Issue by Pierre9344** [quarto-dev/quarto-cli#2943]
### Bug description

Hello,

I observed that the `::: {.incremental}` syntax create non-incremental bullet list instead of incremental list. In the example belliw, both the .incremental and .non-incremental div return the same non-incremental bullet list.

```
::: {.incremental}
- List element A
- List element B
:::

::: {.nonincremental}
- List element A
- List element B
:::
```

![2022-10-20_090814](https://user-images.githubusercontent.com/86181677/196880184-89cd7b4c-73de-4eaa-8b81-8a619792b272.png)

I observed this in html document and MS Word output. The other output format are probably the same. Could this be corrected in a future update? This syntax is used by the _quartostamp_ package which make it useful to quickly insert numbered list.

I'm using RStudio 2022.07.1 Build 554 with the latest version of quarto.
My operating system is Windows 10.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by lcnhb** [comment]
This option does not do what you think it does! For quarto this means incrementally displaying the list, in a powerpoint for exampli. See https://quarto.org/docs/presentations/powerpoint.html#incremental-lists

**Comment by lcnhb** [comment]
That is also what is documented here:

https://matt-dray.github.io/quartostamp/reference/stamp_incremental.html
