### ISSUE TITLE
Problem with html render of a book with csl file

### ISSUE THREAD

**Issue by jfbarthelemy** [quarto-dev/quarto-cli#2945]
### Bug description

Hi,

First of all thanks for this fantastic tool!

I have been trying to build a project of *book* type with a cls file for the bibliography. Although the pdf render works well, the html one triggers an error. So as to keep a minimal example, I have tried with the initial files built after the command `quarto create-project mybook --type book` only adding the cls file (official elsevier-harvard.cls) and adding the line `csl: elsevier-harvard.csl` in `_quarto.yml`. The same file works well on a classical project (not book).

The error is
```
File C:.barthelemy_workspace-harvard.csl not found in resource path
ERROR: File C:.barthelemy_workspace-harvard.csl not found in resource path
```

I put in attachment the full log of console output from rendering on a Windows 10 system.
[config.log](https://github.com/quarto-dev/quarto-cli/files/9827341/config.log)

Thanks in advance for your help.

Best regards
JF Barthélémy

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Could you share the `_quarto.yml` or even the whole project which is causing this issue? (when I try on a simple local book project on windows, I don't see the issue)

**Comment by jfbarthelemy** [comment]
Yes of course, here is the full folder after launching `quarto render` with quarto 1.2.231 under Windows 10.
[mybook.zip](https://github.com/quarto-dev/quarto-cli/files/9830698/mybook.zip)

It is only the initial project provided by the command `quarto create-project mybook --type book` in which I put the file elsevier-harvard.csl (I also tried with elsevier-vancouver.csl with the same result) and added the line `csl: elsevier-harvard.csl` in `_quarto.yml`.

Thanks

**Comment by dragonstyle** [comment]
I'm still not able to reproduce this error testing locally :(. It is as if the path to `elsevier-harvard.csl` is somehow being transformed to `.barthelemy_workspace-harvard.csl`, which I can't explain, especially given that log output. Is there anything unusual about the environment that might be relevant?

**Comment by jfbarthelemy** [comment]
I tried to run quarto in a `cmd` console but also in a `msys2` and even `powershell` console but all of them lead to the same error. And I've never had such an error in any other program (I mean this kind of transform of string). What is indeed strange is that the error explicitly mentions my name which is not even written anywhere in the project config here! I'll try to investigate again.
Thanks for any hint.

**Comment by jfbarthelemy** [comment]
I've just tried to move the project at the root of the system, I mean `C:\mybook` and the error becomes:
```
File C:-harvard.csl not found in resource path
ERROR: File C:-harvard.csl not found in resource path
```
The name of the unknown pseudo-file is thus built from the whole path of the project. This is strange.
And once again, I can use the `csl` option without any problem with a classical project (not a `book`).

**Comment by jfbarthelemy** [comment]
After some investigations in `quarto.js`, it seems that the problem arises when `pandoc` is invoked in the function `generateBibliographyHTML` with the variable `csl` defined after joining the full path to the file given in metadata in `_quarto.yml`. (joining done at line 85793 of `quarto.js` of version 1.2.231).

Commenting these lines at line 85793 of `quarto.js`
```javascript
            if (csl) {
                csl = join3(firstFileDir, csl);
            }
```
solves the problem but I guess this is not satisfactory.

Before that, I checked that the joined path to csl was the good one (not the one given by the error message) but the problem arised when `pandoc` was called at line 85870 with the `execProcess` function. I am afraid I can't do more at this level due to limited skills in javascript. Do you have an idea for the reason why pandoc induces an error in the path to the csl file when the full path is given?

**Comment by dragonstyle** [comment]
This is great progress, thank you! If you're up to it, I would love for you to let me know what the contents of `firstFileDir` and `csl` look like just before those lines:

```javascript
console.log(`firstFileDir: ${firstFileDir}`);
console.log(`csl: ${csl}`);
 if (csl) {
  csl = join3(firstFileDir, csl);
}
```

That join is using the first input file's directory to create a path to the CSL file, but I'm not sure why in your case the directory is so unusual looking (assuming that join is the root cause)...

**Comment by jfbarthelemy** [comment]
I have indeed already done that and figured out that these variables contain what they are supposed to, namely the path to the project directory and the path to the csl file relatively to the project directory. After the join the csl variable finally contains the whole path to the csl file. I guess that is what is actually expected from this code part.

However the problem comes just after that when the csl file is processed by pandoc I think. I don't understand why my csl path is altered there when the whole path is introduced where everything goes right if the relative path is kept.

**Comment by dragonstyle** [comment]
Great detective work - I was able to reproduce this all just using Pandoc before it hit me - the `\` is an escape prefix in strings that appear in YAML. If you are writing a path like that in a YAML string, you should use double `\` like so:

```markdown
---
title: Hello
bibliography: reference.bib
csl: 'C:\\Users\\User\\test.foo\\harvard-elsevier.csl'
---

## Section 1

See @CameronTrivedi2013
```

This resolved the issue for me. Do you mind giving that a try?

**Comment by ati-ozgur** [comment]
This issue is very easily reproduced. I confirm that it is reproduced in the mybook.zip file and using following commands.

```
quarto create-project mybook2 --type book
```

adding to following line to _quarto.yml and of course adding elsevier-harvard.csl file to project.

```
csl: elsevier-harvard.csl
```

Going to directory of project and using

```
quarto render
```
command gives following error:

```
File D:-harvard.csl not found in resource path
ERROR: File D:-harvard.csl not found in resource path
```
My quarto and windows information

```
mybook2 $ quarto --version
1.2.269
mybook2 $ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
```

**Comment by ati-ozgur** [comment]
This issue still exists as quarto version: 1.2.280 and still gives an error.

**Comment by dragonstyle** [comment]
I believe the fix is available in the 1.3 prerelease and hasn't been back ported to 1.2. Can you try with the latest 1.3 release?

**Comment by ati-ozgur** [comment]
I confirm that this bug resolved in quarto version 1.3.56

**Comment by ThierryO** [comment]
I'm having a related bug when the csl is defined in an extension. Both in 1.2.313 and 1.3.97 on Windows. It works fine on Ubuntu.

```
File _extensions-institute-for-nature-and-forest.csl not found in resource path
ERROR: File _extensions-institute-for-nature-and-forest.csl not found in resource path
```

The report and extension are available at https://github.com/inbo/inboqmd_examples/tree/main/source/report/en

**Comment by cscheid** [comment]
> Both in 1.2.313 and 1.3.97 on Windows. It works fine on Ubuntu.

One workaround (that's generally prudent anyway) is to use forward slashes instead of backslashes as path separators. That should work on windows and will make your document more portable across operating systems.

On our side, we should probably add something to the documentation to that effect...

**Comment by cderv** [comment]
@cscheid see https://github.com/quarto-dev/quarto-cli/issues/3944 - Quarto is converting forward to backward slash.
