### ISSUE TITLE
[Hindenbug] Quarto doesn't run on Windows due to deno path processing

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [quarto-dev/quarto-cli#295]
Hello!

Being on `Windows 10` on build `0.3.60` which is nearly same as the dev version, I am experiencing errors launching  anything with quarto. 
The error I am getting after `$ quarto render myfile.qmd` is this
```
TypeError: Unsupported scheme "c" for module "c:\Users\User\quarto-cli\share\editor\tools\yaml\standalone-schema-validators.js". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
```
and apparently this is due to the `deno` that requires `file://`  in front of any file path on non-unix/linux systems, as mentioned in this [issue](https://github.com/denoland/deno/issues/8389). Unfortunately, I am not able to resolve it myself unlike the author of the issue, since any path I am passing with `file://` prefix is interpreted as local path by `quarto` and therefore, the project dir is prepended to it. Therefore, the `deno` anyway receives a path starting with `C:/`, which it does not support. 
All projects builds with simple `$ quarto render` fail likewise, since `quarto` tries to do the same under the hood.
Thanks in advance for any response.

**Comment by jjallaire** [comment]
Thanks for reporting this! Fixed here: https://github.com/quarto-dev/quarto-cli/commit/1013198062caf9ccd17871c493fe41510c9e1cf3 (and available in v0.3.62)

**Comment by anitagraser** [comment]
Hitting the same error today with version 0.9.61

```
quarto preview .\01-introduction.qmd
ERROR: TypeError: Unsupported scheme "c" for module "c:\Program Files\Quarto\share\editor\tools\yaml\yaml-intelligence-resources.json". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
```

**Comment by Robinlovelace** [comment]
Confirmed, seems like a regression.
