### ISSUE TITLE
`render-on-save: true`  does not consistently work VScode + Jupyter + Python + Revealjs

### ISSUE THREAD

**Issue by rleyvasal** [quarto-dev/quarto-cli#2967]
### Bug description

Os: Ubuntu 22.04
VScode: 1.72.2
Quarto: 1.1.251
Quarto VScode extension: v1.50.0

`render-on-save: true` on yaml header does not work consistently. Only the first time the notebook is saved with `Ctrl+s` the notebook renders, but as soon as a new cell is added to the notebook and `Ctrl+s` used again, rendering does not work. 
 
# Steps to reproduce

1. Open notebook
2.  Ctrl+S     - renders the slides without issue
3.  Click on yaml header
4.  Press keyboard  key 'b'  - adds empty header below the yaml header
5.  Ctrl+S     -  does not render the slides

# Screenshot of empty cell added below yaml header

![add empty cell below yaml](https://user-images.githubusercontent.com/61335136/197248581-f1c7a8f0-d7bf-415f-89b2-34707e410f37.png)

# Reproducible example

[slides_quarto_sample_render_on_save.zip](https://github.com/quarto-dev/quarto-cli/files/9840965/slides_quarto_sample_render_on_save.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I'm keeping this here but this is a https://github.com/quarto-dev/quarto-vscode/ issue.

**Comment by rleyvasal** [comment]
I updated Quarto to  quarto-1.2.240-linux-amd64.deb, but still not working, As soon as I make a change to the notebook and save Ctrsl+s, the notebook does not render.

Note: If I open a .qmd file and render and move back to the Jupyter notebook to do Ctrl+s, the notebook renders.

**Comment by rleyvasal** [comment]
Yes

**Comment by jjallaire** [comment]
It's possible that we aren't actually reading the YAML from the first cell of the notebook. Will take a closer look soon.

**Comment by cscheid** [comment]
@jjallaire My understanding is that @rleyvasal means the application launched by `jupyter notebook`. We can't make `jupyter notebook` invoke `quarto render`, can we?

**Comment by jjallaire** [comment]
render-on-save is a feature of VS code.

If you just launch quarto preview in a terminal (not in vs code) and then edit the jupyter notebook you will get render on save behavior by default.

**Comment by rleyvasal** [comment]
@jjallaire just to confirm. Are these the correct steps?

1. Run in terminal `quarto preview slides_quarto_sample_render_on_save.ipynb`  
2. Open in VScode the notebook and save it Ctrl+s

Note: the above steps did render the notebook only the first time.

**Comment by jjallaire** [comment]
I have confirmed that `render-on-save: true` in notebook front matter does not enable it for that notebook (we were relying on parsing the markdown as plain text). I have just made a change though to _always_ enable render on save for notebooks (as they only reason to distinguish between render and save is for expensive to execute qmds, and notebooks don't actually execute during preview).

This change is now available in v1.51.0 of the VS Code extension. Also in that version is some improved behavior for Revealjs preview w/ notebooks (we now retain the currently viewed slide in preview).

Note that I wasn't able to reproduce the save => preview not working when preview is run from the terminal (it worked for me every time).

**Comment by rleyvasal** [comment]
Thanks @jjallaire! 
I confirm the notebook renders on save and the Revealjs slides stay on the current slide.

Interesting you were  not able to "reproduce the save => preview not working". I had to Ctrl+c in terminal to exit quarto rendering so I could run the `quarto preview` again,  maybe something to do with WLS (running ubuntu on Windows).
