### ISSUE TITLE
Get Started page, Step 1, Install Quarto button is not working, in Chrome on Debian Linux 12 (testing)

### ISSUE THREAD

**Issue by sswam** [quarto-dev/quarto-cli#2977]
### Bug description

I'm using Chrome beta Version 107.0.5304.36 in Debian Linux 12 (testing).

Here's a screenshot of the Getting Started page that I see:

![Screenshot from 2022-10-22 23-32-18](https://user-images.githubusercontent.com/801764/197339211-264e8239-a64f-4040-b710-05ab2d59a48a.png)

Here's what I see after I click the "Install Quarto" button with a mysterious underscore:

![Screenshot from 2022-10-22 23-32-38](https://user-images.githubusercontent.com/801764/197339214-85c0ec65-9a07-4213-8e3c-b7d9f2a79ac2.png)

I found a "Download Quarto" page through Google, which also features an undescore button which doesn't go anywhere.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by sswam** [comment]
I meant to raise this on the quarto-web repo, but I didn't notice that when I clicked the top button there, it had sent me here instead.

**Comment by dragonstyle** [comment]
Thanks for letting us know - this is the right place to report this. I'll take a look.

If you have a moment and could look at the developer tools console, there is likely a JS error happening that is causing this - if you see errors there it would be helpful to have them (if not I should still be able to track this down).

**Comment by eitsupi** [comment]
I recently saw this view from Firefox on Android.

**Comment by dragonstyle** [comment]
This should be resolved now- thanks for brining it to our attention!
