### ISSUE TITLE
`code-link` option doesn't work with `code-fold`

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-cli#298]
When I set `code-link: true` and `code-fold: true`, the functions are linked to the documentation as intended, but they aren't hidden by the code folding, and the fold toggles don't do anything.

Example:

```
---
title: "code_link"
format:
  html:
    theme: simplex
    code-fold: true
    code-tools: true
    code-link: true
---

```{r}
hist(rnorm(50))
``
```

![code_fold](https://user-images.githubusercontent.com/25734232/151715202-23866200-2756-47db-93d8-0b3fb6e06978.gif)

**Comment by jjallaire** [comment]
Thanks for reporting this, should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/60d6a766a0366cdc1e414890ef9fe3dcec214382 (rebuilt the binaries so fix should be in the latest release as well)
