### ISSUE TITLE
Warning for `--self-contained` when using `--embed-resources --standalone`

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-cli#2981]
### Bug description

When I use the `standalone` and `embed-resources` YAML options, Quarto still returns the following warning:

```
[WARNING] Deprecated: --self-contained. use --embed-resources --standalone
```

## Example
````
---
title: "standalone_bug"
format:
  html:
    standalone: true
    embed-resources: true
---

```{r}
1+1
```

````

### Rendering output

```
❯ quarto render standalone_bug.qmd


processing file: standalone_bug.qmd
  |.......................                                               |  33%
  ordinary text without R code

  |...............................................                       |  67%
label: unnamed-chunk-1
  |......................................................................| 100%
  ordinary text without R code


output file: standalone_bug.knit.md

pandoc
  to: html
  output-file: standalone_bug.html
  standalone: true
  embed-resources: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: standalone_bug

[WARNING] Deprecated: --self-contained. use --embed-resources --standalone
Output created: standalone_bug.html
```

### OS Info

Mac OS Monterey (12.6)

### Quarto Version

```
❯ quarto -V
1.1.251
```

### R Version

```
R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
This is resolved in our latest pre-release, where we've switched to using `embed-resources`.
