### ISSUE TITLE
Fonts for beamer theme no longer being rendered correctly

### ISSUE THREAD

**Issue by grantmcdermott** [quarto-dev/quarto-cli#299]
I recently updated to the latest binary release of Quarto and noticed that my math fonts aren't being rendered correctly anymore. Well, actually, the main font is slightly off too but the math font is the most obvious. I'm using the popular [metroplis beamer theme](https://github.com/matze/mtheme) and the format section of my YAML is as follows:

```yaml
...
format:
  beamer:
    # classoption: "handout" # uncomment to remove pauses
    aspectratio: 169
    theme: metropolis
    link-citations: true
...
```

Here are two screenshot showing the change in appearance. First, the original correct version:

![quarto1](https://user-images.githubusercontent.com/10285037/152023495-5910da61-058e-43ac-a9f6-eb2b5adf19c1.png)

Second, what I get following the update (i.e. ugly/unmatched fonts).

![quarto2](https://user-images.githubusercontent.com/10285037/152023873-239a06b2-1811-4f95-9aa0-7e5ec5d6990a.png)

Any ideas for how to fix? Should I specify the mathfont in the YAML?

This hiccup aside, I'm very impressed with Quarto. It's been a pleasure to work with. Thanks in advance for any help!

PS. I'm running Quarto through RStudio on Arch Linux. I originally installed and and have just updated Quarto through this [AUR package](https://aur.archlinux.org/packages/quarto-cli-bin/). 

```sh
quarto check install                                               

[✓] Checking Quarto installation......OK
      Version: 0.3.74
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

```

And here's my R sessionInfo().

```r
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblas_haswellp-r0.3.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quarto_1.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8      ps_1.6.0        digest_0.6.29   later_1.3.0     jsonlite_1.7.2  evaluate_0.14  
 [7] rlang_1.0.0     cli_3.1.1       rstudioapi_0.13 remotes_2.4.2   rmarkdown_2.11  tools_4.1.2    
[13] yaml_2.2.1      xfun_0.29       parallel_4.1.2  fastmap_1.1.0   compiler_4.1.2  processx_3.5.2 
[19] htmltools_0.5.2 knitr_1.37   
```

**Comment by jjallaire** [comment]
I noticed that in the very last update to Pandoc there were two changes related to Beamer output:

- Allow arbitrary frameoptions to be passed to a beamer frame, using the frameoptions attribute ([#7869](https://github.com/jgm/pandoc/issues/7869)).
- Add s and squeeze to recognized beamer frameoptions ([#7869](https://github.com/jgm/pandoc/issues/7869)).

My guess is that the issue originates in one of those changes.  Try changing your metadata to this (+ whatever title you have, etc):

```yaml
aspectratio: 169
theme: metropolis
link-citations: true
```

Then running this through raw pandoc (you can access the underlying pandoc binary used by quarto via `quarto pandoc`):

```bash
quarto pandoc pres.md --to beamer --output-file pres.pdf
```

If you see the same behavior across versions then I'd report this on the Pandoc repo.

**Comment by grantmcdermott** [comment]
Thanks for the suggestion @jjallaire. 

I just tried going directly through raw pandoc and it produces the correct fonts. So, good news on that score and a workaround in the interim. 

Unfortunately, going through Quarto (both from RStudio or straight from the command line executable) still produces the undesirable fonts.

**Comment by jjallaire** [comment]
I think I now know exactly what the problem is. We recently switched to using `xelatex` as our default PDF engine rather than `pdflatex`. Ironically one of the main advantages of `xelatex` is improved font handling, so it's not surprising that this triggered a change in font appearance. The big deal w/ xelatex and fonts is that you can use any system font you have installed. 

So a couple of workarounds are possible:

1) Play with the Beamer `fonttheme` or other xelatex compatible font options (https://quarto.org/docs/reference/formats/presentations/beamer.html#fonts)

2) Switch your PDF engine back to pdflatex:

```yaml
...
format:
  beamer:
    pdf-engine: pdflatex
```

Let me know if my speculation is correct and how (1) and/or (2) pan out.

**Comment by grantmcdermott** [comment]
Sorry for being slow, but can confirm that setting `pdf_engine: pdflatex` solves the problem.

(Agree that it's quite strange given XeLaTex's superior font handling. My "native" LaTeX build runs through LaTeX without a hitch, so  I'm not quite sure what to make of this.)

Once again, many thanks for your help @jjallaire and for continuing stream of fantastic open-source products.
