### ISSUE TITLE
 Rstudio: Quarto file within a subdirectory and gt tables not rendering

### ISSUE THREAD

**Issue by tdemarchin** [quarto-dev/quarto-cli#2996]
### Bug description

Hi,

First, thanks for this awesome Quarto!

I am trying to render a quarto document containing gt tables and have an issue.
The document does not render if the .qmd file is located in a subdirectory of my project directory (with option execute-dir: project). The document renders well without the gt table or if the document is located at the root of the project directory.

The error is:

Quitting from lines 29-31 (test.qmd)
Error in readLines(con, warn = FALSE) : cannot open the connection
Calls: .main ... -> enumerate_output_formats -> read_utf8 -> readLines

Any idea?
Running Rstudio 2022.07.2 on Windows.
Thanks,
Thomas.

Here is a small code to reproduce:

````
---
title: "Untitled"
format: html
editor: visual
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
library(gt)
gt(airquality)
```
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Can you include a full .zip file with the directory structure that causes the problem?

**Comment by tdemarchin** [comment]
Here it is! The file "test.qmd" at the root renders well but the one in the "4_codes" subfolder doesn't.

[test.zip](https://github.com/quarto-dev/quarto-cli/files/9849616/test.zip)

**Comment by cscheid** [comment]
Thanks. I can reproduce this locally.

`enumerate_output_formats` appears to be an rmarkdown function: https://github.com/search?q=enumerate_output_formats&type=code. I'm going to leave this to @cderv, our rmarkdown expert.

**Comment by cderv** [comment]
The function comes indeed from **rmarkdown** but this is an issue with its use in **gt**. 
Traceback is the following: 

````
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 25. gt:::knitr_is_word_output()
 27. rmarkdown::all_output_formats(knitr::current_input())
 28. rmarkdown:::enumerate_output_formats(input, output_yaml = output_yaml)
 29. rmarkdown:::read_utf8(input)
 30. base::readLines(con, warn = FALSE)
 ````
 
 Culprit is here: 
 https://github.com/rstudio/gt/blob/5b5226ac3e116c25bb23848399732b3ae0586092/R/print.R#L25-L29
 
 
 @rich-iannone we talked about this as it is known issue - I don't think you need to use (and should use) `rmarkdown::all_output_formats` in this function. I'll send a quick PR to fix this once and for all.

**Comment by cderv** [comment]
The PR in **gt** should solve the issue here with Quarto.

**Comment by cderv** [comment]
PR is merged in **gt** now (https://github.com/rstudio/gt/pull/1084), please try again with dev version of **gt** and this should solve the issue with Quarto. If not please do reopen this. Thank you !
