### ISSUE TITLE
table default style: not the same for markdown tables and code tables

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#2997]
### Bug description

Hi,
the default style of a 1️⃣ markdown table is not the same of 2️⃣ the one generated by code.
I think they should have the same style. Moreover I prefer the code table one.
I'm using quarto 1.2.226.

Distributor ID: Debian
Description:    Pengwin
Release:        11
Codename:       bullseye

Here a sample code: https://gist.github.com/aborruso/47aa44e894b942d8303abdaad3679674

Thank you

![image](https://user-images.githubusercontent.com/30607/197405586-0009ea1f-2865-4259-91f8-4c767e645d18.png)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I agree that this is unexpected, but it looks to be by design, cf https://github.com/quarto-dev/quarto-cli/commit/42305132f781c546893aa6ce09e9493145f88d3e.

@jjallaire do you remember why we choose to have different styles for these tables?

On top of that, the CSS rule we're using to get stripes is a bit too restrictive, and so we can't wrap a "plain" table in a div with class `table-striped`. Ideally, we'd write

```
::: table-striped

Planet      R (km)    mass (x 10^29 kg)
--------  --------  -------------------
Sun         696000           1.9891e+09
Earth         6371        5973.6
Moon          1737          73.5
Mars          3390         641.85

:::
```

But `_tables.scss` comes from the scss distribution, and looks like this:

```scss

// Zebra-striping
//
// Default zebra-stripe styles (alternating gray and transparent backgrounds)

.table-striped {
  > tbody > tr:nth-of-type(#{$table-striped-order}) > * {
    --#{$variable-prefix}table-accent-bg: var(--#{$variable-prefix}table-striped-bg);
    color: var(--#{$variable-prefix}table-striped-color);
  }
}
```

That `>` in `> tbody ...` means that the table-striped selector needs to be in the direct parent of the `tbody`, and we don't control that element. @aborruso if you want to work around this, you can add your own theme file, like this:

### 2997.scss

```scss
/*-- scss:rules --*/

.table-striped {
  tbody > tr:nth-of-type(#{$table-striped-order}) > * { // notice the removed ">"!
    --#{$variable-prefix}table-accent-bg: var(--#{$variable-prefix}table-striped-bg);
    color: var(--#{$variable-prefix}table-striped-color);
  }
}

```

Then change your front matter like this:

````
---
title: "table"
format: 
  html:
    theme:
      - 2997.scss
execute:
  daemon: false
  freeze: auto
````

Notice that you need to use a _theme_ as well as that `/*-- scss:rules --*/` directive to trigger the sass compiler.

When you do that, you can wrap your tables with the `table-striped` div like above, and then it all works:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/285675/197587138-59992481-e477-4215-b8c8-09d11886def9.png">

**Comment by aborruso** [comment]
@cscheid is there currently, in some quarto pre-release, a way to use directly a [bootstrap tables classes](https://getbootstrap.com/docs/5.0/content/tables/) to format a markdown table?

Thak you

**Comment by jjallaire** [comment]
I believe that there is some work that has been done here. @cscheid Do we have docs anywhere yet for this?

**Comment by aborruso** [comment]
> I believe that there is some work that has been done here. @cscheid Do we have docs anywhere yet for this?

Thank you very much. Moreover, I do not if it's related, but I'm not able to apply class even [using pandas `set_table_attributes`](https://github.com/quarto-dev/quarto-cli/discussions/3456#discussioncomment-5116526).

**Comment by aborruso** [comment]
> @jjallaire Thank you very much. Moreover, I do not if it's related, I'm not able to apply class even [using pandas `set_table_attributes`](https://github.com/quarto-dev/quarto-cli/discussions/3456#discussioncomment-5116526).

My stupid error I had `#| output: false`. Sorry

**Comment by cscheid** [comment]
@rich-iannone You should add documentation for the bootstrap table features to https://quarto.org/docs/prerelease/1.3/

The tl;dr is that any bootstrap attribute `table-*` can be set on the table element itself by using `*`. For example:


```
---
title: table-attributes
---

Planet      R (km)    mass (x 10^29 kg)
--------  --------  -------------------
Moon          1737          73.5
Mars          3390         641.85

: {.hover}


Planet      R (km)    mass (x 10^29 kg)
--------  --------  -------------------
Moon          1737          73.5
Mars          3390         641.85

: {.striped}

Planet      R (km)    mass (x 10^29 kg)
--------  --------  -------------------
Moon          1737          73.5
Mars          3390         641.85

: {.borderless}
```

will produce

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/285675/221605970-53014c74-661d-4845-bdca-539c7aad2864.png">

**Comment by aborruso** [comment]
@cscheid @rich-iannone it works, and it's a great new feature.

I have a strane behavior using `responsive` class.

If I apply it using python, I have a responsive table (see the image below).

~~~~python
```{python}
#| echo: false
#| warning: false

import pandas as pd

df=pd.read_csv("riga-esempio.csv")

(df.style.hide(axis='index').set_table_attributes("class='dataframe table-striped table-sm table-responsive'"))
```
~~~~

![resp](https://user-images.githubusercontent.com/30607/221690847-ec3079bd-2a85-4aef-8be3-7648fd5ffab5.gif)


If I use it via markdown `: {.striped .sm .responsive}`, the table does not scroll horizzontaly.

You can see it in action [here](https://pnrr.datibenecomune.it/table.html) and [this is the code](https://github.com/ondata/italian-public-sector-pnrr-data-guide/blob/main/table.qmd).

Is it normal?

**Comment by cscheid** [comment]
@rich-iannone Are we not forwarding `-responsive`? Maybe we decided not to do it and I forgot the reasons why?

**Comment by jjallaire** [comment]
I think tables normally _do_ scroll horizontally in quarto (at least they used to). We should check to see if any of the new table work changed this behavior.

**Comment by aborruso** [comment]
> I think tables normally _do_ scroll horizontally in quarto (at least they used to)

Hi @jjallaire , a markdown table does not scroll in quarto (the [code](https://github.com/ondata/italian-public-sector-pnrr-data-guide/blob/main/table.qmd#L40-L53)): https://pnrr.datibenecomune.it/table.html#wide-markdown-table

And moreover it's not possible to apply `: {.responsive}`.

The way to do it, currently for me, it's to use pandas `set_table_attributes`, but it is inconvenient to use it for a simple table.

Thank you

**Comment by rich-iannone** [comment]
This seems possible to get done in `v1.3`. I'll take a look!

**Comment by rich-iannone** [comment]
After having a closer look at this, I've learned why this doesn't work. We can now (in `main`) add responsive classes (any of `"responsive"`, `"responsive-sm"`, `"responsive-md"`, `"responsive-lg"`, `"responsive-xl"`, `"responsive-xxl"`). However, to make the table actually need an outer `<div>`. Here's the necessary structuring (from https://getbootstrap.com/docs/5.0/content/tables/#responsive-tables):

```
<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>
```

I think what we need to do here is automatically wrap the table in a `<div>` and use that `"table-responsive"` Bootstrap class. I tried that with a render of your .qmd and it worked perfectly.

<img width="997" alt="outer-div-responsive-table" src="https://user-images.githubusercontent.com/5612024/223236765-864d6dec-4639-4208-8fed-43490a6e1054.png">

**Comment by cscheid** [comment]
@rich-iannone We could inject that div programmatically if we detect a `responsive` class in the Table element. The one snag is that we probably need to do it sufficiently late, so that the rest of our Lua filters don't get confused by a new div. This could happen around the end of the `quarto-post` filter, for example.

**Comment by aborruso** [comment]
@cscheid @rich-iannone you are great. Thank you
