### ISSUE TITLE
Quarto TinyTex installation fails due to space in Windows username

### ISSUE THREAD

**Issue by JimInNashville** [quarto-dev/quarto-cli#2998]
### Bug description

Let me begin by thanking you for the very fine work with RStudio, RMarkdown, and now Quarto.  I was using Tex Live with no issues up until 2016, and am now returning to writing documents.  I decided to reinstall R, RStudio, and use TinyTex. 

Current Windows Operating System: **Windows 10 Pro Version 21H2**

After installing  **Rstudio 2022.07.02 Build 576** and beginning my transition to Quarto, I discovered that TinyTex will not install properly on my Windows 10 computer. It appears almost certain that the problem is related to a space in the Windows username, "James Nash".  

Below is the code that appears in the Quarto terminal window. As you can see, the installation process misinterprets the path, 
chopping it at the space in the username "James Nash." As a result, TinyTex installation fails, and  I've been unable to implement the ability to compile to pdf format.  I searched for documentation about TinyTex installation issues, but could find nothing.

Can you fix this, or suggest a workaround?  Since Windows supports (almost encourages) user names with spaces, this problem will recur.  Many thanks,  

### Quarto Terminal Record

```Microsoft Windows [Version 10.0.19044.2130]
(c) Microsoft Corporation. All rights reserved.

C:\Users\James Nash\Documents>quarto install tool tinytex

Installing tinytex
[>] Downloading TinyTex v2022.10
(-) Unzipping TinyTeX-v2022.10.zipExpand-Archive : A positional parameter cannot be found that accepts argument
'Nash\AppData\Local\Temp\50c9640e\TinyTeX-v2022.10.zip'.**
At line:1 char:1
+ Expand-Archive C:\Users\James Nash\AppData\Local\Temp\50c9640e\Tin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Expand-Archive

[>] Unzipping TinyTeX-v2022.10.zip
[>] Moving files
ERROR: NotFound: The system cannot find the file specified. (os error 2), stat 'C:\Users\James Nash\AppData\Local\Temp\50c9640e\TinyTeX'

C:\Users\James Nash\Documents>quarto tools list
[>] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.10

C:\Users\James Nash\Documents>
```

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by JimInNashville** [comment]
A subsequent check revealed that indeed R 4.2.1 bombs for the same reason. It turns out that the TEMP and TMP environment variables contain paths that have the username in them. Most software handles paths with spaces. A temporary workaround to this is to create a new directory without any spaces in its path and change the TEMP and TMP environment variables to this directory path. (I used C:\temp).  That simple change allowed R 4.2.1 AND Quarto's TinyTex installation to proceed without problems.

**Comment by dragonstyle** [comment]
Thanks for debugging this further and sharing the workaround. I agree we should definitely handle the space - will work on getting it fixed!
