### ISSUE TITLE
Using natbib as cite-method creates bibliography at end of document and not at specified location

### ISSUE THREAD

**Issue by jpmorr** [quarto-dev/quarto-cli#3002]
### Bug description

In order to work around some `hyperref` option issues that exist with using `citeproc` I started to use `natbib` as the latex engine, as per discussion in #2017.  

I've just noticed a side-effect of this change now: `natbib` creates a Bibliography section at the end of the document regardless of the placement of the following .qmd references file:
```
# References {.unnumbered}

::: {#refs}
:::
```

In my case, I had placed some appendices after the reference section but when I use `natbib` I get a blank references page, then appendices and then a bibliography section. The HTML output follows the .yml specification, as does the pdf when using the default `citeproc` but the natbib creates it own section.

I don't mind the references/bibliography getting shifted to the end, but the blank references page and use of bibliography instead of reference creates an inconsistency with the HTML version.

I'm not sure if this is a bug or a feature of `natbib` that requires some additional parameters being set in the yaml file.

I'm using window on my computer but the GitLab Pages instance is built in Linux and this happens in both cases. I'm using the latest `quarto` version (1.2.237).

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Currently, the positioning of the bibliography for `natbib` is specified in the core template itself (based upon the Pandoc template) - relocating the position of the bibliography is only supported when using `citeproc` for the `cite-method`. We are tracking a request to improve upon this here:

https://github.com/quarto-dev/quarto-cli/issues/2024

I'm closing this in favor of that issue - I tried a quick fix of this one time but ultimately had to revert it as it caused as many problems as it solved. I'm hoping to take another look at again soon...

**Comment by jpmorr** [comment]
@dragonstyle Thanks for the info, will follow that issue for updates.
