### ISSUE TITLE
Margin footnotes/references in callout messes the page layout

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#3003]
### Bug description

When adding and setting the references and footnotes to be located on the margin within a callout fenced divs, the layout is not longer respected and the divs takes the whole width.

````
---
format: html
reference-location: margin
---

:::{.callout}
Something
:::

:::{.callout}
Something^[Something in the margin]
:::

:::{.callout}
Something[^1]
:::

[^1]: Something in the margin


::::{.callout}
Something

:::{.aside}
Simply something aside for reference
:::

::::
````

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/8896044/197538051-8399e417-3202-456b-9b4e-c713e2345ccb.png">

---

System:
- OS: MacOS Monterey (Apple Silicon)
- IDE: VSCode
- Quarto: v1.2.237

**Comment by dragonstyle** [comment]
This appear to be fixed by the commit above.

![Screenshot 2023-02-21 at 3 07 25 PM](https://user-images.githubusercontent.com/261654/220447461-38158db5-21c6-49a4-85e7-8b3250977c4b.png)
