### ISSUE TITLE
Fedora error with version >=1.2

### ISSUE THREAD

**Issue by alxsimon** [quarto-dev/quarto-cli#3012]
### Bug description

I installed Quarto on Fedora 37 through the tar archive, for any version >=1.2.

When trying to run quarto, e.g. `quarto check` I end up having this error:
```
tcc: error: mprotect failed: did you mean to configure --with-selinux?
```

Quarto works perfectly with version 1.1.251

I don't really know where to start to track where the issue is coming from.

**Comment by cscheid** [comment]
This is truly strange. `tcc` is, [as far as I can tell](https://www.google.com/search?q=tcc%3A+error%3A+mprotect+failed%3A+did+you+mean+to+configure+--with-selinux), the "tiny c compiler". I don't know how that's getting involved at all in this...

**Comment by jjallaire** [comment]
This could be the new version of Demo. What happens if they try to run deno directly?

**Comment by alxsimon** [comment]
Hi, I don't seem to have the error with deno.
```
❯ deno --version
deno 1.25.3 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
❯ deno
Deno 1.25.3
exit using ctrl+d or close()
>
```
Any command you would like me to try specifically?

**Comment by jjallaire** [comment]
I was thinking the version of deno included in quarto, but I think the fact that 1.25.3 works rules that out.

**Comment by cscheid** [comment]
@alxsimon I can only think of two other commands to try:

- `quarto pandoc --help`
- ```
  $ echo "console.log(3)" > test.ts
  $ quarto run test.ts
  ```

**Comment by dragonstyle** [comment]
We're currently shipping 1.25.1 I believe, and this issue appears to have been fixed post 1.25.1:

https://github.com/denoland/deno/issues/15306

I think we will need to take an update to deno to fix this.

**Comment by alxsimon** [comment]
I've come up with something reproducible using a singularity container if that can help.

file `fedora37_quarto.def`
```
BootStrap: docker
From: fedora:37

%post -c bash
	dnf upgrade --refresh -y
	dnf install -y \
	git \
	unzip
	
	cd /opt
	git clone https://github.com/quarto-dev/quarto-cli
	cd quarto-cli
	./configure.sh
	ln -s /opt/quarto-cli/package/dist/bin/quarto /bin/quarto

%apprun run
	exec /bin/bash "$@"

%runscript
	exec /bin/bash "$@"
```

In command line
```
sudo singularity build fedora37_quarto.sif fedora37_quarto.def
sudo singularity exec fedora37_quarto.sif quarto check
sudo singularity exec fedora37_quarto.sif /opt/quarto-cli/package/dist/bin/tools/deno --version
```

outputs:
```
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /opt/quarto-cli/package/dist/bin

tcc: error: mprotect failed: did you mean to configure --with-selinux?

deno 1.25.1 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
```

Exactly the same thing happening with Fedora 36.

**Comment by cscheid** [comment]
We have a PR open now: https://github.com/quarto-dev/quarto-cli/pull/3014/

**Comment by alxsimon** [comment]
Thank you all for the amazing reactivity, working now with the last commit.
