### ISSUE TITLE
Ipywidgets interactive sliders do change plot in rendered slides VScode + Jupyter + Python + Revealjs 

### ISSUE THREAD

**Issue by rleyvasal** [quarto-dev/quarto-cli#3016]
### Bug description

Bug description:  Ipywidgets work in jupyter notebook to change a plot, but when rendering to Revealjs slides the interactivity of the sliders does not work on the plot.

Os: Ubuntu 22.04
VScode: 1.72.2
Quarto: 1.1.251
Quarto VScode extension: v1.50.0

# Screenshot of Ipywidget in browser (slides move but plot does not change)
![ipywidgets](https://user-images.githubusercontent.com/61335136/197634893-75ac2d8e-e75b-456c-9ebb-b547e5882933.png)

[Ipywidgets_jupyter.zip](https://github.com/quarto-dev/quarto-cli/files/9855499/Ipywidgets_jupyter.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
That's not a bug. That version of `interactive` requires a running Python process, which can't work as is on a static webpage as produced by quarto. If you need that kind of interactivity, consider using the [ObservableHQ engine](https://quarto.org/docs/interactive/ojs/), or [Shiny for Python](https://shiny.rstudio.com/py/), which embeds a webassembly version of Python on the webpage.
