### ISSUE TITLE
citing quarto

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#303]
I am using quarto for a scientific publication. Do you already have a `bib` entry for how your would like quarto to be cited? GitHub recently added support for adding a citation to repositories: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

PS: The new landing page of quarto.org looks great!

**Comment by jjallaire** [comment]
Just added the `CITATION.cff` file to the repo....
