### ISSUE TITLE
Latest GitHub release

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-cli#3032]
We're scraping the latest GH release version from this repo automatically for some internal automation. Is it planned to keep it up-to-date? 

The latest Quarto release is 1.2.242 since some days but this repo is still sitting at 1.1.251 :)

**Comment by eitsupi** [comment]
In general, "Release Candidate" is not a stable version?
The two versions displayed on the website are written in the following two json files.
https://quarto.org/docs/download/_download.json
https://quarto.org/docs/download/_prerelease.json

**Comment by pat-s** [comment]
Ahh, I didn't read the RC in the label. I assumed that you might only display the latest release on the landing page of the official website. 

I found the actual "stable" release here then: https://quarto.org/docs/download/

All good then! 

And WRT to the actual point: as long as the "latest" release here follows the link above, I am happy 😄

**Comment by cscheid** [comment]
@pat-s Just to give you extra information: our general release schedule is to be on "pre-release versions" for about 3 months, then switch to "release candidate" versions for a few weeks, and then release. Right now, we're on "Release Candidate" for v1.2. When that becomes the stable release in the near future, we'll move `main` to v1.3 prereleases, and then the behavior of the quarto.org website will revert to what we had until last week.

**Comment by pat-s** [comment]
Thanks for the heads-up! Sounds great!

Putting the prelease out in front makes sense as you get some feedback from users while all other channels are still on the "old" stable.

Happy to follow the "stable" GH releases from here!
