### ISSUE TITLE
SELinux execheap access violation generating HTML

### ISSUE THREAD

**Issue by castedo** [quarto-dev/quarto-cli#3036]
### Bug description

There was a change between quarto 1.1.251 and 1.2.242 such that rendering html fails with SELinux enabled.

With a trivial hello world test.qmd file I get the following with 1.2.242:
```
$ quarto render test.qmd
tcc: error: mprotect failed: did you mean to configure --with-selinux?
```
With 1.1.151 is works fine. Disabling SELinux allows quarto 1.2.242 to work as expected. Generating other formats
like jats or tex does not hit this issue.

This happens with both Fedora 36 (in a container) and RHEL 9.0.

The SELinux violation is a deno process attempting execheap access. The default SELinux policy is to not permit this. From my understanding execheap access is to allow heap memory to be both writable and executable. This in turn allows a greater attack surface.

Here's what the SELinux Alert Browser reports:
```
The deno application attempted to change the access protection of memory on the
heap (e.g., allocated using malloc).  This is a potential security problem.
Applications should not be doing this. Applications are sometimes coded
incorrectly and request this permission.  The SELinux Memory Protection Tests
web page explains how to remove this requirement.  If deno does not work and you
need it to work, you can configure SELinux temporarily to allow this access
until the application is fixed. Please file a bug report against this package.

If you do not think /home/castedo/shr/quarto-1.2.242/bin/tools/deno-x86_64-unknown-linux-gnu/deno
 should need to map heap memory that is both writable and executable.
you need to report a bug. This is a potentially dangerous access.
Contact your security administrator and report this issue.
```

Seems strange that authoring software to generate HTML from markdown needs to be doing something exotic like writing machine code to the heap and then have it executed. Version 1.1.251 didn't need to do this to generate HTML. Seems far less annoying to stop doing this, especially if a server process is having quarto generate static HTML files.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
This is a duplicate of https://github.com/quarto-dev/quarto-cli/issues/3012, should be fixed with the very latest pre-rerelease build, 1.2.251.
