### ISSUE TITLE
Latex Matrix not rendering in Word

### ISSUE THREAD

**Issue by ralmond** [quarto-dev/quarto-cli#3037]
### Bug description

I'm working in Quarto and needing to convert to Word for the sake of my co-authors.  I'm getting a problem with the way a display equation containing a matrix is rendering.

[MatrixTest.qmd.txt](https://github.com/quarto-dev/quarto-cli/files/9863877/MatrixTest.qmd.txt)

In my Markdown document I have

```md
$$ \begin{array}{ccccc}
\end{array} $$
```
In RStudio, it is working fine.  However, when I try to render it as word, instead of rendering the equation, I get the raw latex commands (i.e, everything between the dollars).

I'm using RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

I'm attaching a small example that breaks.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I believe you need to write your table in Markdown format in order for it to be visible in Word. In HTML you're "getting lucky" that MathJax is picking it up, but from my understanding, Word's equation support does not include tables.

**Comment by cscheid** [comment]
The documentation for table formatting that's portable across formats is here: https://quarto.org/docs/authoring/tables.html
