### ISSUE TITLE
[feature-request] Support for giscus

### ISSUE THREAD

**Issue by KeAWang** [quarto-dev/quarto-cli#304]
Would it be possible to support [giscus](https://giscus.app/)? It's the same setup as utterances but uses Github Discussions instead of Github Issues. Utterances and giscus are almost identical in their setup.

**Comment by jjallaire** [comment]
Yes, giscus is on our radar and should be supported soon.

In the meantime, you can get it to work by placing your giscus `<script>` tag in a file (e.g. `giscus.html`) and then specifying that file in the `include-after-body` option, e.g.

```yaml
format:
  html:
    include-after-body: giscus.html
```

**Comment by jjallaire** [comment]
Giscus is now formally supported (docs here: https://quarto.org/docs/output-formats/html-basics.html#commenting)
