### ISSUE TITLE
Quarto preview only loading homepage in Firefox

### ISSUE THREAD

**Issue by tomvaneyck** [quarto-dev/quarto-cli#3045]
### Bug description
When previewing a website in Firefox using `quarto preview`, only the homepage loads; whenever clicking any other link in both the navbar or sidebar, the homepage reloads. Quarto gives the following output on clicking a link (but only sometimes):
```
GET: /about.html
WARNING: connection closed before message completed
GET: /
```
while Firefox shows the following in the developer tools:

![afbeelding](https://user-images.githubusercontent.com/17331687/198028000-e8eb8211-dae2-46bd-a5c5-ad1a98738bea.png)

I'm using Quarto v1.2.242 and see the result both running on Windows 11 in Powershell and in WSLv1.

### Reproducing
1. Create a new website using `quarto create project website`.
2. Execute `quarto preview`.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I can reproduce this on OS X as well.

**Comment by jjallaire** [comment]
This is going to have to do with how we subscribe/unsubscribe from socket messages in devserver-core.html (I made a change there recently to handle a behavior I saw in Electron (computer suspend causes websockets to get disconnected) but doesn't happen in Chrome:

```js
 // if the socket closes for any reason (e.g. this occurs in electron apps
      // when the computer suspends) then reload to reestablish the connection 
      devServerSocket.onclose = () => {
        console.log('Socket connection closed. Reloading.');
        window.location.reload(true);
      }
```

We definitely need to keep this behavior, but it may need some adaptation for Firefox.

**Comment by cscheid** [comment]
The issue seems to be "simply" that Firefox closes websockets on navigation events, and Chrome doesn't: https://stackoverflow.com/questions/10965720/should-websocket-onclose-be-triggered-by-user-navigation-or-refresh

**Comment by jjallaire** [comment]
Since the workaround I put in is just for Electron, we could just scope
that code to Electron (or Chomium) only? (or not Firefox if that works
better)

**Comment by nil-is-lin** [comment]
WARNING: connection closed before message completed. I meet this problem again, quarto 1.3.450, windows 11, edge and chrome have been test.
