### ISSUE TITLE
python inline code results displays over revealjs slides

### ISSUE THREAD

**Issue by KeAWang** [quarto-dev/quarto-cli#305]
Copying the inline examples from the quarto docs, we have the following reproduction steps:

1. Create `inline.qmd`:
```
---
title: "Title"
author: "Author"
date: "Today"
format: revealjs
jupyter: python3
---

## Attempt at inline code

```{python}
#| echo: false
radius = 10
from IPython.display import display, Markdown
display(Markdown("""
## Circle

The radius of the circle is {radius}.
""".format(radius = radius)))
```
2. run `quarto render inline.qmd`

This causes in the inline results to display over every revealjs slide

**Comment by jjallaire** [comment]
Writing `## Circle` is actually creating a new RevealJS slide. However, it.s also part of cell output, which we include in a special div. The nesting of the heading within this div is confusing reveal. 

There are therefore two ways to prevent this:

1) Add the `output: asis` option to the cell (to prevent the writing of the enclosing div).e.g.

````
```{python}
#| echo: false
#| output: asis

radius = 10
from IPython.display import display, Markdown
display(Markdown("""
## Circle

The radius of the circle is {radius}.
""".format(radius = radius)))
```
````

Don't write the heading:

````
```{python}
#| echo: false

radius = 10
from IPython.display import display, Markdown
display(Markdown("""
**Circle**

The radius of the circle is {radius}.
""".format(radius = radius)))
```
````
