### ISSUE TITLE
Crossrefs in revealjs link incorrectly

### ISSUE THREAD

**Issue by KeAWang** [quarto-dev/quarto-cli#306]
Consider `crossrefs.qmd`:
```
---
title: "Title"
author: "Author"
date: "Today"
format: revealjs
---

## Equation 1

See @eq-equivalence2 on the next slide.
$$ E = mc^2 $$ {#eq-equivalence1}


## Equation 2

See @eq-equivalence1 on the previous slide.
$$ E = mc^2 $$ {#eq-equivalence2}
```
and run `quarto render crossrefs.qmd`.

The links given by cross refs are to `crossrefs.html#/eq-equivalence1` and `crossrefs.html#/eq-equivalence2` which don't exist as slides. Clicking on them results in returning to the title slide. Instead I think some logic needs to be there to link to the slide containing the target reference, i.e. `crossrefs.html#/equation-1` and `crossrefs.html#/equation-2`

**Comment by jjallaire** [comment]
Yes, internal linking is indeed completely busted in revealjs b/c reveal hijacks browser history changes. Hopefully we can write a plugin to overcome this.

**Comment by mcanouil** [comment]
In the latest development version, the issue does not seem to be there.


https://github.com/quarto-dev/quarto-cli/assets/8896044/88f6e28c-c19c-4e77-b0f3-9ebfc9b83fbf

**Comment by cderv** [comment]
Yes it seems fixed to me. I don't remember which change we did to fix that 🤔 

I think we could close
