### ISSUE TITLE
code content auto breakline

### ISSUE THREAD

**Issue by Achuan-2** [quarto-dev/quarto-cli#3081]
### Bug description

![Snipaste_2022-10-28_13-24-14](https://user-images.githubusercontent.com/60436214/198509461-2e1b8ae6-4ba9-4032-b9ee-4e62d036e9bd.png)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
We've generally found that it is better to leave code blocks as is when rendering through LaTeX as authors often want control of the appearance of their code blocks rather than relying on simply wrapping.
