### ISSUE TITLE
Image from parent folder not shown in `html` format

### ISSUE THREAD

**Issue by mingsu** [quarto-dev/quarto-cli#3086]
Referring  images from parent folder can not be shown correctly in `html` format, see demo code below:

````qmd
---
format: html
---

```{r}
#| echo: false
#| include: false

# generate a image
require(ggplot2)
qplot(1)
ggsave("../img.png")
```
![](../img.png)

````

I understand that the `html` can not use the resource not inside the working folder, but should we include these resources when rendering to `html` in a smart way?

**Comment by cscheid** [comment]
The short answer is that we won't support that.

Simply put, that would violate a typical expectation that projects don't access files outside their root folders.

You can, however, create a project root on the parent directory, and then this _should_ work.
