### ISSUE TITLE
regression in `quarto preview`

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#311]
With the latest builds I noticed that `quarto preview` only re-renders after the first change / save and ignores following changes. I am currently doing a sort of manual bisect with daily builds. It works on https://github.com/quarto-dev/quarto-cli/tree/v0.2.475. I will let you know if I find the exact commit when it stopped working.

**Comment by jmbuhr** [comment]
works: https://github.com/quarto-dev/quarto-cli/tree/v0.3.9, 
fails: https://github.com/quarto-dev/quarto-cli/tree/v0.3.25

**Comment by jjallaire** [comment]
Thank you for sifting through to find the culprit!

Interestingly, that change was I believed a big improvement as previously we were constantly tearing down and re-creating filesystem watches. It seems like in your environment we need these to be refreshed though.

I don't currently observe this locally. Could you provide more info on your exact configuration (OS, filesystem, what sort of document or project you are previewing, etc.). Ideally if we do need to sync more aggressively I could narrow it down so its not done everywhere all the time.

**Comment by jmbuhr** [comment]
I'm on linux (pop-os) and tested it with a very simple plain qmd document.

**Comment by jjallaire** [comment]
Are you running from inside RStudio (e.g. via the embedded terminal) or are you running from the shell?

**Comment by jmbuhr** [comment]
Just from the command line, editing the file with neovim. Let me try other editor to see if this has an effect.

**Comment by jjallaire** [comment]
I just repro'd, thanks again, will sort this out soon!

**Comment by jmbuhr** [comment]
Not sure if this helps (and it confuses me a lot): when I edit the file in VS Code it re-renders on save fine. If I then open the same file in neovim while VS Code is still open it re-renders on last time after the first save in nvim but doesn't on subsequent saves in with either editor.

**Comment by jjallaire** [comment]
I think it's probably related to how the editor actually saves the file (does it open, truncate, and append or does it delete and re-write). nvim is probably doing the latter so we lose the file handle. FWIW I was able to repro w/ GEdit so I think many editors will exhibit the same issue.

**Comment by jjallaire** [comment]
Okay, I think I was just getting a bit too cute w/ trying to re-use watcher instances. We now refresh them every time (https://github.com/quarto-dev/quarto-cli/commit/3462feb34888a00ba6b3c751a70f0be2dbac8daf), which likely heads off some other subtle issues w/ longstanding file watches we haven't seen yet. I also verified that the existing watches are correctly cleaned up (no longer consume OS resources).

**Comment by JulianTao** [comment]
I feel the problem I am having is related to this so I report it here.

With the latest build, `quarto preview` still ignores changes at times. Its behavior is not very consistent, sometimes it works, sometimes it does not. I have not found a pattern.

**It also seems to ignore some styles for the revealjs formats.**  For example, with preview, the footer, slide number and control icons appear too small, the sizes of the images are also off and not responsive. **But when the rendered HTML files are opened directly in the browser, they appear as expected.**

**Comment by jjallaire** [comment]
Are you also on Linux? No matter your platform, what's the editor you are using? Finally, are the renders that occur when you save relatively long or are they short?

**Comment by JulianTao** [comment]
I'm also on Linux, using Neovim. The renders are relatively short. It may also be related to changes to dependency files such as the project yaml file, style files and source codes. It's a gut feeling and I'm not 100% sure about it. I can test more at night.

**Comment by jjallaire** [comment]
Okay, let me know what you find. I just checked on Ubuntu 20 w/ Neovim and I am seeing the updates happen.

**Comment by jmbuhr** [comment]
I did also experience having to go back to the `qmd` file and saving it in order for changes in supporting files like `css` to show up, so those changes didn't cause a re-render. But I haven't tried with the latest commits.

**Comment by JulianTao** [comment]
First of all, the style related problem (font size of footer, image scaling etc) seems to be related to the browser. I changed a computer with a different version of the Brave browser (based on Chromium), the problem is gone.

For the `quarto preview` behavior, it is a bit complicated. I tried many times but still could not identify the reason. Every time, the behavior is different...
I share some of my observations.

1. For a standalone `qmd` file with `revealjs` format without external theme file or style files, the `preview` function never break.
2. For a `revealjs qmd` file in a project with customized `revealjs` options and theme files, the `preview` ignores changes to the project `yaml` file. When I went back to the `qmd` file and save it, `preview` worked again. But when I change some metadata such as title and author inside the `qmd` file, the preview browser did not refresh immediately although I can see from the terminal that the quarto log indicated that quarto successfully rerun and showed the updated metadata. I then save multiple times from within Neovim, the browser refreshes again. 
3. Unfortunately, the behavior above does not always reproduce. Sometimes, I got complains like the following. But it is strange sometimes even with the following errors massages, the web browser will in fact refresh and re-render the file. That's very weird.

```{markdown}
ERROR: NotFound: No such file or directory (os error 2),
copy '/home/julian/Dropbox (ASU)/sites/site_resrc_tes/sit
e_libs/quarto-html/tippy.css' -> '/home/julian/Dropbox (A
SU)/sites/site_resrc_tes/.quarto/_freeze/site_libs/quarto
-html/tippy.css'

NotFound: No such file or directory (os error 2), copy '/
home/julian/Dropbox (ASU)/sites/site_resrc_tes/site_libs/
quarto-html/tippy.css' -> '/home/julian/Dropbox (ASU)/sit
es/site_resrc_tes/.quarto/_freeze/site_libs/quarto-html/t
ippy.css'
    at Object.opSync (deno:core/01_core.js:149:12)
    at Object.copyFileSync (deno:runtime/js/30_fs.js:46:1
0)
    at copyFileSync (https://deno.land/std@0.122.0/fs/cop
y.ts:106:8)
    at copySync (https://deno.land/std@0.122.0/fs/copy.ts
:305:5)
    at copyFileIfNewer (file:///home/julian/quarto-cli/sr
c/core/path.ts:213:5)
    at copyMinimal (file:///home/julian/quarto-cli/src/co
re/path.ts:197:5)
    at copyToProjectFreezer (file:///home/julian/quarto-c
li/src/command/render/freeze.ts:175:5)
    at freezeLibDir (file:///home/julian/quarto-cli/src/c
ommand/render/project.ts:328:13)
    at renderProject (file:///home/julian/quarto-cli/src/
command/render/project.ts:334:11)
    at async renderForPreview (file:///home/julian/quarto
-cli/src/command/preview/preview.ts:183:24)

```

```markdown
ERROR: NotFound: No such file or directory (os error 2),
stat '/home/julian/Dropbox (ASU)/sites/site_resrc_tes/sit
e_libs/revealjs/plugin/highlight/plugin.js'

NotFound: No such file or directory (os error 2), stat '/
home/julian/Dropbox (ASU)/sites/site_resrc_tes/site_libs/
revealjs/plugin/highlight/plugin.js'
    at Object.opSync (deno:core/01_core.js:149:12)
    at Object.lstatSync (deno:runtime/js/30_fs.js:220:22)
    at copySync (https://deno.land/std@0.122.0/fs/copy.ts
:292:24)
    at copyFileIfNewer (file:///home/julian/quarto-cli/sr
c/core/path.ts:213:5)
    at copyMinimal (file:///home/julian/quarto-cli/src/co
re/path.ts:197:5)
    at copyToProjectFreezer (file:///home/julian/quarto-c
li/src/command/render/freeze.ts:175:5)
    at freezeLibDir (file:///home/julian/quarto-cli/src/c
ommand/render/project.ts:328:13)
    at renderProject (file:///home/julian/quarto-cli/src/
command/render/project.ts:334:11)
    at async renderForPreview (file:///home/julian/quarto
-cli/src/command/preview/preview.ts:183:24)
    at async render (file:///home/julian/quarto-cli/src/c
ommand/preview/preview.ts:74:14)

```
I tested using a minimal quarto project [here](https://github.com/JulianTao/site_resrc_tes), but as I mentioned, it does not always reproduce the behavior I described above. Sorry that I could not do a more thorough testing to provide a clearer report.

**Comment by jmbuhr** [comment]
When I try `quarto preview` in your project it get `ERROR: PermissionDenied: Permission denied (os error 13), copy '/home/jannik/playground/site_resrc_tes/.git/objects/pack/pack-6782fb74457dd1718b7027355d4002842c1d219e.idx' -> '/home/jannik/playground/site_resrc_tes/_site/.git/objects/pack/pack-6782fb74457dd1718b7027355d4002842c1d219e.idx'` and after removing the cache and `_site` folder and another preview I get `ERROR: NotFound: No such file or directory (os error 2), rename '/tmp/quarto-sessionae9252fb/36fa965f/a7606463/index.html' -> '/tmp/quarto-sessionae9252fb/36fa965f/a7606463/_site/index.html'`

**Comment by jmbuhr** [comment]
Update: the latest commits fixed re-rendering for saving the `qmd` file, but not for re-rendering on changes of supporting files such as `css`.

**Comment by jjallaire** [comment]
After the change I made to always re-sync the file watcher after a render I noticed that on OS X we would sometimes "lose" our connection to the filesystem. I think the main trouble w/ all of this is that individual file watches are more flaky and platform-dependent than directory level watches. Consequently I implemented a polling based file watcher (every 150ms) which I am hoping will be much more rock solid: https://github.com/quarto-dev/quarto-cli/commit/52997951b972ae0ffba21e32502101f20c886214. This will end up checking the file modification time of ~ 2-6 files every 150ms so extremely lightweight in terms of cycles.

**Comment by jmbuhr** [comment]
I need to test it still, but if I read the code correctly this will also make https://github.com/quarto-dev/quarto-cli/issues/109 work out of the box! :)

**Comment by jjallaire** [comment]
I don’t think this will solve that issue because this is polling for a
single file preview vs. a website (which still needs to use inotify b/c
it’s recursive over the whole project

**Comment by JulianTao** [comment]
So far so good!

**Comment by jmbuhr** [comment]
Note: with `self-contained: true` supporting files like css do not trigger a re-render. Maybe this could be added to the documentation: https://quarto.org/docs/output-formats/html-basics.html#self-contained as a tip to essentially use this only once you are ready to publish the document. From a usability out-of-the-box standpoint it might also be an option for `preview` to ignore the self contained option, but this would create more surprises, as then render and preview would function differently and "least surprise" seems like the more important metric.
