### ISSUE TITLE
revealjs vertical slides: columns settings does not work well

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#3111]
### Bug description

I have the input below:

- if I  use markdown headings, the slide is not readable

![image](https://user-images.githubusercontent.com/30607/198874576-95d6c24b-b27c-468a-ab3a-fb5dfe39324f.png)

- if I use html headins, it's all ok

![image](https://user-images.githubusercontent.com/30607/198874589-db457c9c-b214-47b3-b298-4602ba76b128.png)

I think quarto should manage also the first kind of syntax.

I'm using quarto 1.2.251.

Distributor ID: Debian
Description: Pengwin
Release: 11
Codename: bullseye

```
---
title: "Hello world"
format:
  revealjs:
    slide-number: true
    preview-links: auto
    theme: [dark]
    navigation-mode: vertical
    center-title-slide: false
    chalkboard: true
---

# Using Markdown headings

:::: {.columns}

::: {.column width="50%"}
## Colonna 1
:::

::: {.column width="50%"}
## Colonna 2
:::

::::

# Using HTML headings

:::: {.columns}

::: {.column width="50%"}
<h2>Colonna 1</h2>
:::

::: {.column width="50%"}
<h2>Colonna 2</h2>
:::

::::
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mcanouil** [comment]
A slide is supposed to start with a level 2 header as described in the documentation (<https://quarto.org/docs/presentations/revealjs/#creating-slides>).
Level 1 header are for parts, those are not really supposed to have contents, but I guess it could still be improved.
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/8896044/198884550-c946bde7-cb83-4462-8ed8-09e69860c4c3.png">

**Comment by aborruso** [comment]
> Level 1 header are for parts, those are not really supposed to have contents, but I guess it could still be improved.

Thank you @mcanouil 

I use a lot [vertical slides](https://quarto.org/docs/presentations/revealjs/advanced.html#vertical-slides) in which "Level 2" are for vertical slide and "Level 1" for horizontal. I think it's the way to use them. Am I wrong?

And sometime I add some content also the horizontal slide. Ok, it's better not to.

Thank you

**Comment by mcanouil** [comment]
> I use a lot [vertical slides](https://quarto.org/docs/presentations/revealjs/advanced.html#vertical-slides) in which "Level 2" are for vertical slide and "Level 1" for horizontal. I think it's the way to use them. Am I wrong?

Yes. Navigation mode defines how to read the slides structure, it does not define the slides structure.
Press "o" to get the overview, thus the structure of the slides, you'll see that it does not change when you change the navigation mode.
See <https://revealjs.com/vertical-slides/>.
