### ISSUE TITLE
Custom appendix sections appear in table of contents

### ISSUE THREAD

**Issue by mccarthy-m-g** [quarto-dev/quarto-cli#3113]
### Bug description

When you add [custom appendix sections](https://quarto.org/docs/authoring/appendices.html#custom-appendix-sections) to a post, they are included in the table of contents. I believe this is a bug, as other non-custom sections such as "Citation" are not.

You can see this behaviour in this [blog post](https://blog.djnavarro.net/posts/2022-10-18_arrow-flight/#acknowledgements). The custom "Acknowledgements" section can be seen in the table of contents, but the other sections provided by Quarto are not. The behaviour should be consistent whether an appendix section is custom or not.

As a default leaving appendix entries out of the table of contents makes sense for things like blog posts. But it might be nice to give users control of whether appendix sections are included in the table of contents (e.g., with an `include_appendix` YAML option under `toc`).

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by ASNDataAnalytics** [comment]
@mccarthy-m-g, thanks for raising this issue. I would like to add the "Citation" to the TOC of an article so readers know there's a (very nicely) pre-formatted BibTex cite and "For attribution..." they can copy/paste.
