### ISSUE TITLE
YAML => problem with layout: full

### ISSUE THREAD

**Issue by Felipepereyra** [quarto-dev/quarto-cli#3129]
When i use layout: full, the right margin is not going interactive. I can't make any click over there, i tried to reach how to solve it but the only way is taking out the layout function

**Comment by Felipepereyra** [comment]
> * Can you let us know the Quarto version that you're using when you see this issue?

its 1.2.258

> * If possible, can you please provide a simple cmd that illustrates the problem?

i just try with this one and makes the same! i can't uncheck carnames. thanks
---
title: "mtcars"

format: 
  html:
    page-layout: full
    mainfont: Calibri #formato de texto
    toc: true #tabla de contenidos
    toc-location: left 
    toc-title: Indice
---

# TOC1 
 
```{r}
library(tidyverse)
library(plotly)
library(ggplot2)
library(tibble)
```

# TOC2

```{r}
mtcars <- mtcars %>%
  rownames_to_column(var="carnames")


ggplotly(
mtcars %>%
ggplot(aes(mpg, hp, colour = carnames)) +
  geom_point()
)

```

**Comment by Felipepereyra** [comment]
---
title: "mtcars"

format: 
  html:
    page-layout: full
    mainfont: Calibri #formato de texto
    toc: true #tabla de contenidos
    toc-location: left 
    toc-title: Indice
---

# TOC1 
 
```{r}
library(tidyverse)
library(plotly)
library(ggplot2)
library(tibble)
```

# TOC2

```{r}
mtcars <- mtcars %>%
  rownames_to_column(var="carnames")


ggplotly(
mtcars %>%
ggplot(aes(mpg, hp, colour = carnames)) +
  geom_point()
)

```

**Comment by cscheid** [comment]
I can't reproduce this on macOS and the latest version of quarto: (the fonts look wrong because I don't have Calibri installed)

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/285675/199790531-af30378a-2cf7-4f8b-afe4-b52ae90fdfa3.png">

After double-clicking on "Fiat 128":

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/285675/199790641-5fe2295f-d9c0-47a2-a7fe-e663ba35c6c2.png">

**Comment by Felipepereyra** [comment]
I got macOS too. I tried with safari or google chrome and I can’t make it work. The problem it’s the quarto version?
I attach HTML and qmd if you could watch it! thanks

De: Carlos Scheidegger ***@***.***>
Fecha: jueves, 3 de noviembre de 2022, 14:20
Para: quarto-dev/quarto-cli ***@***.***>
CC: Felipepereyra ***@***.***>, Author ***@***.***>
Asunto: Re: [quarto-dev/quarto-cli] YAML => problem with layout: full (Issue #3129)

I can't reproduce this on macOS and the latest version of quarto: (the fonts look wrong because I don't have Calibri installed)

[image]<https://user-images.githubusercontent.com/285675/199790531-af30378a-2cf7-4f8b-afe4-b52ae90fdfa3.png>

After double-clicking on "Fiat 128":

[image]<https://user-images.githubusercontent.com/285675/199790641-5fe2295f-d9c0-47a2-a7fe-e663ba35c6c2.png>

**Comment by Felipepereyra** [comment]
Now it's working OK, thank you!
