### ISSUE TITLE
proof div: add one extra space in the HTML output

### ISSUE THREAD

**Issue by AlbertLei** [quarto-dev/quarto-cli#314]
The html output of the proof environemnt needs an extra space between `Proof.` and the proof body.
A minimal example:
```
:::{.proof}
See Appendix 1.
:::
```
![image](https://user-images.githubusercontent.com/16741954/152691167-39f20232-bb3c-44fc-a9ee-87b421dc5d17.png)

I am using v0.3.102.

**Comment by AlbertLei** [comment]
Moreover, there is a minor issue that the proof environment does not have a QED sign at the end (like the pdf output). So it's hard to tell when a proof ends if it consists of multiple pars.
A quick fix is to add a QED sign.

**Comment by jjallaire** [comment]
Thanks, spacing fixed here: https://github.com/quarto-dev/quarto-cli/commit/f65fcc4ff199ad673e3fedc2766eb6627c1fb773

Will take a look add adding the QED sign
