### ISSUE TITLE
theorem div fails to render in the HTML output

### ISSUE THREAD

**Issue by AlbertLei** [quarto-dev/quarto-cli#316]
I am using quarto 0.3.102 on mac os 10.15. The thm, prp divs do not render in the HTML output.
[The example](https://quarto.org/docs/authoring/cross-references.html#theorems-and-proofs) in quarto guide works, but fails once there is no equation at the end.

A minimal example:
```
::: {#thm-line}

## Line

The equation of any straight line, called a linear equation, can be written as:
:::
``` 

Here is the error info when I run `quarto render -t html`

```
Error running filter /Applications/quarto/share/filters/crossref/crossref.lua:
/Applications/quarto/share/filters/crossref/crossref.lua:466: attempt to get length of a Block value (local 'values')
stack traceback:
        /Applications/quarto/share/filters/crossref/crossref.lua:2224: in local 'fn'
        /Applications/quarto/share/filters/crossref/crossref.lua:1470: in function </Applications/quarto/share/filters/crossref/crossref.lua:1464>
```

Meanwhile, `quarto render -t pdf` works as expected.
![image](https://user-images.githubusercontent.com/16741954/152727475-f03ea6cf-9e59-44a6-8ed1-7c4d3ba4bc78.png)

**Comment by AlbertLei** [comment]
I am also confused by the theorem syntax of quarto. Specifically, currently each theorem-style div must have a user-inputed name. Otherwise, it is automatically named `unname`.
It's better to make the naming optional. Many theorems/lemma/etc do not need a name.

**Comment by jjallaire** [comment]
This should resolve both issues (the error message + making `name` optional for themes): https://github.com/quarto-dev/quarto-cli/commit/3950263b598c8f04721ac520b614e9af823316af

Building a new release w/ this change now.

**Comment by AlbertLei** [comment]
Confirm it works now. Thanks!
