### ISSUE TITLE
Can't include file with absolute path with include directive

### ISSUE THREAD

**Issue by benabel** [quarto-dev/quarto-cli#3160]
It seems that paths beginning with `/` are treated as relative paths.

For example when running quarto 1.2.258, with this content in aquarto project in `/home/user/Documents/Boulot/`:

```md
---
format:
  latex:
    papersize: a5
    classoption:
      - fontsize=10pt
      - DIV=calc
---


# Exercices sur le chapitre 2: Représentation des entiers relatifs

{{< include /home/user/_file.qmd >}}
```

Gives this error:

```
ERROR: Include directive failed.
  in file ..., 
  could not find file /home/user/Documents/Boulot/home/user/_file.
```

**Comment by cscheid** [comment]
This is by design; we don't allow absolute references in documents for security reasons. If you have a quarto project, then paths starting with `/` will be resolved relative to the root of the project.
