### ISSUE TITLE
Quarto with SQLite does not seem to be working

### ISSUE THREAD

**Issue by novotny1akub** [quarto-dev/quarto-cli#3163]
### Bug description

I tried to use Quarto with a sqlite database, but it does not seem to be working. Below is an error message I get when I open the generated html file in the browser. The reprex is also below. [Here ](https://observablehq.com/d/a9047fb68f840243)is an observablehq workbook where this sqlite database works with no issues. I assume this happens because sqlite.js is not loaded in Quarto whilst in observablehq, it is a part of their standard library. In addition, Quarto [documentation ](https://quarto.org/docs/interactive/ojs/data-sources.html) links [observablehq/stdlib](https://github.com/observablehq/stdlib#attachment_sqlite) which I think is rather unfortunate because the examples from there need to be first translated to ojs dialect of JavaScript. For example, the observablehq/stdlib documentation mentions this code `const db = await FileAttachment("chinook.db").sqlite();`, which contains the const, which is not used in Quarto context I believe.

![image](https://user-images.githubusercontent.com/39886440/199946915-b44b0d4f-5220-452f-81ec-d6784772872d.png)

````
---
title: "Quarto with sqlite database"
format:
  html:
    self-contained: true
mode: visual
---

```{r include=F}

library(DBI)

n <- 10000
df <- data.frame(
  cat = letters[1:2] |> sample(size = n, replace = T),
  num = runif(n)
)

con <- dbConnect(RSQLite::SQLite(), "sqlite.db")
dbWriteTable(con, "table", df, overwrite = T)

dbDisconnect(con)

```

```{ojs}
//| echo: false

db = await FileAttachment("sqlite.db").sqlite();

```
````
Windows operating system

RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I think this should work with Elsbeth Geranium RStudio builds. (You're correct that we should improve our docs to make that clear in the [website](https://quarto.org/docs/interactive/ojs/)).

**Comment by novotny1akub** [comment]
I don't think the issue is necessarily in the RStudio's version. The problem occurs even when I render the quarto file using Quarto command line (`quarto render quartofile.qmd`). My Quarto version is 1.2.262.

**Comment by cscheid** [comment]
Thanks for clarifying. This is fixed with the `arrow` commit. On `main`, your example runs (slightly changed to display the `db` variable):

<img width="464" alt="image" src="https://user-images.githubusercontent.com/285675/200354382-97844b16-d892-4dd3-b678-a20ea6efe854.png">

**Comment by cscheid** [comment]
We're trying to build new installers right at this moment, but there's something happening with Apple's notarization service and our workflow is not succeeding. We'll have one up the moment that everything is back running.

**Comment by cscheid** [comment]
@novotny1akub Can you try this one? https://github.com/quarto-dev/quarto-cli/releases/tag/v1.2.267

**Comment by novotny1akub** [comment]
Sure, but it's pretty late in central Europe so probably in the morning. Thanks!

**Comment by cscheid** [comment]
Of course! I just wanted to let you know that the installer finally built successfully. Thanks again.

**Comment by novotny1akub** [comment]
I downloaded Quarto 1.2.267 and can confirm I can render the html without an error. However, when I try to use the SQLite database, it still does not seem to be working. See a slightly modified reprex, and the errors I get. The `chinook.db` is taken from the file attachements in [this notebook](https://observablehq.com/@observablehq/sqlite).

![image](https://user-images.githubusercontent.com/39886440/200520232-1837fb43-3509-4910-9d73-6e3d87e76afc.png)

````
---
title: "Quarto with sqlite database"
format:
  html:
    self-contained: true
mode: visual
---



```{r include=F}

library(DBI)

df <- data.frame(
  cat = letters[1:2] |> rep(5),
  num = runif(10)
)

con <- dbConnect(RSQLite::SQLite(), "sqlite.db")
dbWriteTable(con, "table", df, overwrite = T)

dbGetQuery(con, 'SELECT * FROM "table"') # did not work when table was unquoted

dbDisconnect(con)

```


```{ojs}

db = await FileAttachment("sqlite.db").sqlite()
db.query('SELECT * FROM "table"') // identical to the R query above that works

```

```{ojs}

db2 = await FileAttachment("chinook.db").sqlite()
db2.query(`SELECT * FROM customers`)

```
````

**Comment by cscheid** [comment]
Ok, I can reproduce. Something is wrong with the way we're locally decoding that file; uploading `sqlite.db` to observablehq and running it on their implementation works. This is a mess, I'm sorry. I'll look into it today.

**Comment by cscheid** [comment]
There are a couple of issues, only some of which I have managed to fix so far. But the good news is that I could get (a version) of this to work.

The main thing that I haven't figured out yet is that `self-contained: true` appears to be causing `sqlite()` to fail (specifically, our conversion of the file into a data URI does not appear to be working.). So, you'll need to do two things:

1. upgrade again to the latest version of quarto (I'll post here when an installer is available)
2. remove the `self-contained: true` option

**Comment by novotny1akub** [comment]
I can confirm that after installing Quarto 1.2.269 it is now working. Thanks a lot for a prompt fix.
