### ISSUE TITLE
navbar hiding and appearing adds infinitely many `style` tags to html `head`

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#3172]
### Bug description

When scrolling on a quarto website, e.g. https://quarto.org/, the navbar is meant to disappear and appear on scrolling. 

Every time this happens, a style tag is added to the head:
![image](https://user-images.githubusercontent.com/17450586/200012524-9ff5b561-bdfc-4433-8995-df52d9a9766f.png)

```
      section:target::before {
        content: "";
        display: block;
        height: 66px;
        margin: -66px 0 0;
      }
```

I am not sure what, but something is not right here.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
(I wonder if this is what's causing the hard-to-reproduce eventual slowdown we see in Safari sometimes?)
