### ISSUE TITLE
Improve error message when Chrome and Chromium are not installed

### ISSUE THREAD

**Issue by philwunderlich** [quarto-dev/quarto-cli#3177]
### Bug description

# Configuration

quarto release `1.2.258` 

quarto tools:

```
[✓] Inspecting tools
Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Up to date        v2022.11      v2022.11
```

OS:

```
Systemversion:	macOS 13.0 (22A380)
Kernel-Version:	Darwin 22.1.0
```

# Minimal example

I created the following quarto document called `test.qmd`

````{quarto}
---
format:
  pdf:
    default
---

```{dot}
//| fig-cap: "Caption"
//| label: fig-efa
digraph D {

  A [shape=diamond]
  B [shape=box]
  C [shape=circle]

  A -> B [style=dashed, color=grey]
  A -> C [color="black:invis:black"]
  A -> D [penwidth=5, arrowhead=none]

}
```

````

Subsequently I render the document using the following command from the command line or use the inbuilt quarto render function of the vscode extension.

```{bash}
quarto render test.qmd
```

# Expected behavior

I would expect a PDF document to render, including the graph diagram.

# Actual Behavior

I receive the following error message and no PDF or intermediary files are produced.

````
ERROR: NotFound: No such file or directory (os error 2)
````

# Remarks

Rendering html documents works with  the example above when changing

```{yaml}
format:
  pdf:
    default
```

to

```{yaml}
format:
  html:
    default
```

in the file `test.qmd`.

Rendering the document without the `dot` code chunk works without problems

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I don't see this locally when I test the above example, so it is likely something related to a difference in our environments. If you could, setting the environment variable `QUARTO_PRINT_STACK` to `true` before your render and the error message will include a stack trace which would be very helpful for us.

**Comment by philwunderlich** [comment]
Thanks for your reply!

With `QUARTO_PRINT_STACH` `true` I get the following output:

```
ERROR: NotFound: No such file or directory (os error 2)

NotFound: No such file or directory (os error 2)
    at opRun (deno:runtime/js/40_process.js:29:16)
    at Object.run (deno:runtime/js/40_process.js:112:17)
    at criClient (file:///Applications/quarto/bin/quarto.js:43081:26)
    at async file:///Applications/quarto/bin/quarto.js:43053:22
    at async Semaphore.runExclusive (file:///Applications/quarto/bin/quarto.js:42775:29)
    at async Object.createPngsFromHtml (file:///Applications/quarto/bin/quarto.js:43224:44)
    at async Object.cell (file:///Applications/quarto/bin/quarto.js:70334:52)
    at async Promise.all (index 0)
    at async Object.document (file:///Applications/quarto/bin/quarto.js:43448:25)
    at async handleLanguageCells (file:///Applications/quarto/bin/quarto.js:43419:42)
```

**Comment by cscheid** [comment]
It looks like quarto is unable to find a Chrome executable. Do you by chance not have Chrome installed in your OS? I see chromium is not installed:

```
[✓] Inspecting tools
Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Up to date        v2022.11      v2022.11
```

If Google Chrome is not installed, you need to `quarto tools install chromium`.

**Comment by philwunderlich** [comment]
Thanks, of course, this solved the problem! Sorry, I was not aware that chromium was needed, particularly for pdf output. Maybe, a more descriptive error message would have helped me to figure this out myself.

**Comment by cscheid** [comment]
@philwunderlich I agree with you: the error message here is terrible. We should fix that!

**Comment by cscheid** [comment]
We [now have an error message if we can't find Chrome or Chromium](https://github.com/quarto-dev/quarto-cli/blob/main/src/core/puppeteer.ts#L260-L264).
