### ISSUE TITLE
TOC is covered by figures (flakey)

### ISSUE THREAD

**Issue by filipj8** [quarto-dev/quarto-cli#3196]
When I render a notebook in quarto within a headless job (OS Shell), the matplotlib figures in the notebook don't have the `img-fluid` class (just `class= "column-page-left"`), and end up covering up the TOC. When I render the notebook manually on the server (Jupyterlab terminal) it looks correct and the images have the `img-fluid` class (`class="column-page-left img-fluid"`). 
This is using the same docker file / environment in both cases, the difference is the way the render command is executed. 

Is there a way to prevent the figures from covering the TOC?

**Ubuntu 20.04.5 LTS
Kernel version 5.4.217-126.408.amzn2.x86_64
Quarto v1.1.251**
___

`quarto render test.ipynb --execute` (_Jupyterlab terminal_):
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/13021405/200091680-0b863179-037f-46fe-be3a-42ae4e5bd3ff.png">

___

`quarto render test.ipynb --execute` (_Job OS Shell_):
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/13021405/200091801-387d3bbc-58ff-4c72-8a02-074541ac5dd9.png">

**Comment by cscheid** [comment]
Thanks for the report! I'm not sure I understand what you mean by "headless job (OS Shell)" and "render the notebook manually on the server (Jupyterlab terminal)". Can you provide explicit instructions to create the environment that causes the issue you're seeing?

**Comment by dragonstyle** [comment]
We've fixed a number of issues related to TOC folding and margin content in Quarto 1.2 and 1.3. Could you please try with these and if the issue persists, reopen this with details on how to reproduce. TY!
