### ISSUE TITLE
`quarto serve` saying that directory is not a project

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-cli#32]
I created a small page using Quarto and Github Pages ([repo](https://github.com/pommevilla/friendly-dollop), [page](https://pommevilla.github.io/friendly-dollop/)). I first wrote an Rmd and a R script, made sure they were working as desired, then called `quarto create-project` in that directory. A minimal `_quarto.yml` is created and the related `quarto` statements are added to `.gitignore`.

When I call `quarto render`, I get the expected html. However, when I call `quarto serve,` I get this error:
![image](https://user-images.githubusercontent.com/6981612/120709341-583b3580-c482-11eb-8262-7ae573a1daf0.png)

I deleted `_quarto.yml`, `.quarto/`, and the output created by `quarto` and then rendered everything without those quarto files. I got the same html document that I did with the `quarto.yml` in my directory. I also reproduced this error on other repos. 

I think this also has to do with a problem I was having with changing `output-dir` in `_quarto.yml`. I tried setting `_quarto.yml: docs`, but the output directory never showed up. It looks like `quarto serve` isn't seeing `_quarto.yml` for some reason.

**Steps to reproduce**

1. `git clone https://github.com/pommevilla/friendly-dollop.git`
2. `cd friendly-dollop`
3. `quarto serve`

**Error**
- See picture above.

**System**: 

- Windows 10

**Comment by jjallaire** [comment]
Thanks for reporting! I was also able to repro on OS X.

This should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/4f403577056b6d58e68d2dc11c004227dacb38d8

Note however that `quarto serve` is only supposed to work for `site` and `book` projects so this still might not give you what you are looking for (I'll add an additional check to that effect).
