### ISSUE TITLE
quarto render -h throws an error if not inside a quarto project

### ISSUE THREAD

**Issue by g-simmons** [quarto-dev/quarto-cli#3202]
### Bug description

`quarto render --help` works as expected, displays a typical help menu

The shorthand `quarto render -h` gives

```
ERROR: The specified directory ('.') is not a Quarto project
```

MacOS Monterey, Quarto 1.2.262 installed via .pkg

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by JanPalasek** [comment]
This happens to me when I perform:

```shell
quarto render --to html file.qmd
```

Instead of:

```shell
quarto render file.qmd --to html
```
