### ISSUE TITLE
output of bash block not rendered. 

### ISSUE THREAD

**Issue by bayeslearner** [quarto-dev/quarto-cli#3203]
### Bug description

````md

---
title: "Untitled"
format: 
    revealjs: 
        center: true
        theme: beige
        fig-align: center
filters:
    - filters/diagram-generator.lua
    - quarto
---

# hello
```{.plantuml width=80%}
@startuml
skinparam backgroundcolor transparent
A -> B : hello
@enduml
```


# hello 2

```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()

``` 


```{python}
!ls
```

# test bash
```{bash}
ls
```
````

The output of the bash block is not rendered.  Why? 
Rstudio: 2022.07.2 Build 576

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jmbuhr** [comment]
When the first code chunk found is not R, quarto uses a jupyter kernel to execute the code (https://quarto.org/docs/computations/execution-options.html#engine-binding). However, jupyter can only execute one type of code, so the python kernel doesn't execute the bash chunk.
The default R execution engine `knitr` however can execute multiple languages (not just R). You can use it by adding `engine: knitr` to your yaml header.

**Comment by jmbuhr** [comment]
Note, that you will need an installation of R for this. And if you want `knitr` to also execute your python code, you will have to install the `reticulate` R package: https://rstudio.github.io/reticulate/index.html

**Comment by bayeslearner** [comment]
this IS run in rstudio, and the pyrhon block is rendered with reticulate,  so maybe i just need to force it to use knitr. 

when jupyter is used by quarto,  in vs code or rstudio, will it work with sos or other polyglot kernel? How to specify explicitly what kernel to use.

I will give both a try

**Comment by bayeslearner** [comment]
I can confirm that
1. manually forcing it to use knitr will allow you to render plantuml, python (recticulate) and bash in the same document/slide;  Although ipython magic (!ls) won't work. 

2. I can't get jupyter polyglot kernel to work.  It seems that sos kernel doesn't run macbook m1.  It died with message:
```
Starting sos kernel...ERROR: 
Kernel died before replying to kernel_info
```
Also not sure how to specify the specific language for individual block, even if I can get it to run.

**Comment by cscheid** [comment]
@bayeslearner it looks like your first suggestion solves the problem for you. I'm going to go ahead and close this, then.
