### ISSUE TITLE
Property name appendix-title is invalid

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#3205]
### Bug description

The [documentation](https://quarto.org/docs/books/book-structure.html#parts-appendices) has

```
crossref:
  appendix-title: "App."
  appendix-delim: ":"
```

as example. `quarto render` gives

```
ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 73, columns 3--17) property name appendix-title is invalid
72:   ref-hyperlink: true
73:   appendix-title: "Supplement"
      ~~~~~~~~~~~~~~
ℹ The error happened in location crossref:appendix-title.
```

`quarto check` reports

```
[✓] Checking Quarto installation......OK
      Version: 1.2.134
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.1.3
      Path: /opt/conda/lib/R
      LibPaths:
        - /home/rstudio/R/x86_64-conda-linux-gnu-library/4.1
        - /opt/conda/lib/R/library
      rmarkdown: 2.16

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Fixed here 277b812178cda840581d6e792f902a309e1ab968 - ty!
