### ISSUE TITLE
Long strings in backticks do not wrap

### ISSUE THREAD

**Issue by jthomasmock** [quarto-dev/quarto-cli#3221]
### Bug description

Long strings in backticks or code chunks do not wrap - this can lead to content overflowing into the gutter and covering the floating ToC.

The problem at: https://twitter.com/mariviere1/status/1589662823378194433 appears to be fixed per #2649:

![image](https://user-images.githubusercontent.com/29187501/200386543-e9899e1c-f36c-4e1c-bcaa-cbe770242982.png)

But the wrapping isn't applied within tables:

````
---
format: html
---

## Accessibility

Really long string below:


| Description                         | Windows & Linux        | Mac                      |
|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------|
| `Toggle Screen Reader Support`      | Alt+Shift+/            | Ctrl+Option+/            |
| `Speak Text Editor Location`        | Alt+Shift+1            | Ctrl+Option+1            |
| Focus Console Output                | Ctrl+\` or Alt+Shift+2 | Ctrl+\` or Ctrl+Option+2 |
| `Toggle Tab Key Always Moves Focus which is a long sentence and will it ever wrap nope still won't wrap in a table` | Alt+Shift+\[           | Ctrl+Option+\[           |
| Focus Next Pane                     | F6                     | F6                       |
| Focus Previous Pane                 | Shift+F6               | Shift+F6                 |
| Focus Main Toolbar                  | Alt+Shift+Y            | Ctrl+Option+Y            |

\

````

![image](https://user-images.githubusercontent.com/29187501/200398016-fe70ac7e-464a-4b69-afe3-22012fb99fb7.png)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Somehow github has figured this out, though:

| Description                         | Windows & Linux        | Mac                      |
|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------|
| `Toggle Screen Reader Support`      | Alt+Shift+/            | Ctrl+Option+/            |
| `Speak Text Editor Location`        | Alt+Shift+1            | Ctrl+Option+1            |
| Focus Console Output                | Ctrl+\` or Alt+Shift+2 | Ctrl+\` or Ctrl+Option+2 |
| `Toggle Tab Key Always Moves Focus which is a long sentence and will it ever wrap nope still won't wrap in a table` | Alt+Shift+\[           | Ctrl+Option+\[           |
| Focus Next Pane                     | F6                     | F6                       |
| Focus Previous Pane                 | Shift+F6               | Shift+F6                 |
| Focus Main Toolbar                  | Alt+Shift+Y            | Ctrl+Option+Y            |
