### ISSUE TITLE
Search works in HTML book preview, but not in rendered HTML book

### ISSUE THREAD

**Issue by psvelayudhan** [quarto-dev/quarto-cli#3230]
### Bug description

I am using Ubuntu 20.04 and am experiencing this issue in version 1.1.251 and 1.2.262 of quarto-cli. No editor/IDE was used, just terminal.

The minimal example in my case is one of the tutorial commands here: https://quarto.org/docs/books/

```
quarto create-project mybook --type book
```

With no other changes, if I open the book by running:

```
quarto preview mybook
```

The book works perfectly fine and the search bar functions as expected:
- If I search for something that isn't in the book, I see a *No results* result
- If I search for something that is in the book, I see several matches drop down

But if I open the book by running:
```
quarto render mybook
```

Followed by either:

```
firefox mybook/_book/index.html
```

or

```
microsoft-edge mybook/_book/index.html
```

I see the html book exactly as it was in the preview, all the links and formatting work fine, but the search bar does not work. No results (not even the phrase *No results*) pop up from the search bar regardless of what I type or enter. Is this expected behaviour when not using the preview command?

Thanks for any assistance.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
This is not a bug. In order for much of javascript to work, HTML files must be served from a web browser. If you have python installed, you can run 

```
python -m http.server
```

to start a local web server. quarto will also preview and serve the file in a server for you with `quarto preview`.

**Comment by psvelayudhan** [comment]
Ah, got it - thanks so much!
