### ISSUE TITLE
Mix R and python code in Quarto presentation

### ISSUE THREAD

**Issue by NRaillard** [quarto-dev/quarto-cli#3244]
### Bug description

Hi all,

I am trying to write a presentation using Reveal.js that mix R and python code. I think it is possible to mix code in Quarto documents, I do not understand what's going on here.

It seems not possible, or I am missing something. Here is a simple example of qmd file that does not compile.

````md
---
title: "test"
format: revealjs
---

```{r}
#| echo: true
hist(rnorm(1000))
```

---

```{python}
#| echo: true
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```
````

which gives an error concerning TCL:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
  _tkinter.TclError: Can't find a usable init.tcl in the following directories:  [...]

I'm using the latest Quarto (1.2.267), under Windows 10 and RStudio 2022.07.1 Build 554. The python environment is created with only the latest versions of jupyterlab and matplotlib.

Thanks for you time !

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Your example worked locally for me.

I suspect the issue you're running into is that when mixing `r` and `python` code cells, the execution of python cells happens through `reticulate`, an R package. So it's probably the case that there's a mismatch between the python environment configuration that reticulate is using, and that of jupyter.

**Comment by NRaillard** [comment]
Thanks for the quick response !
I am using `reticulate` also, and I make sure to use the same environment, by calling `reticulate::use_virtualenv("./env/")`, but I am still stuck...

**Comment by cscheid** [comment]
Have you tried printing out the paths of the imported libraries explicitly to see if they match?

**Comment by cscheid** [comment]
Have you verified that this works on your python-only environment (and then, on jupyter?)

**Comment by NRaillard** [comment]
Everything is working fine on python-only, and on jupyter.
And the qmd file is compiling with python only, or R only, but not with both...
I was suspecting that my version or R was responsible (I was using 4.1), but even with the latest version (4.2.2) that corrects a bug in Tk I still face the issue.

**Comment by NRaillard** [comment]
Some update: I think it's a bug (not sure about it) using `venv` in windows. Anyway, I copied the `tcl` folder of my python installation in the root folder of my virtual env and things are OK...
