### ISSUE TITLE
putting qmd-files in a subdir causes image-rendition to fail, wether it's markdown style or with knitr::include_graphics()

### ISSUE THREAD

**Issue by emilBeBri** [quarto-dev/quarto-cli#3245]
### Bug description

So I have some issues with including pictures in a quarto project, and it seems to be persisent even in very simple examples, so I think it's a bug. As this is  concerned with folder structure, the issue is a bit hard to reproduce. Bear with me, and please ask  and I'll happy to clarify. 

Let's start with something that does work:

 I have a project structure like this:

```
.
├── img
│

 └── test.png
├── index.qmd
├── _quarto.yml
└── test.qmd



```

e.g. a yaml, a directory called img with an image 'test.png', an index.qmd 

the yaml contains this:

```
project:
  type: book

book:
  title: "this is a title"
  chapters:
    - index.qmd

``` 

the index.qmd contains this (I put forward brackes on the backticks to not mess with the formatting in here, but in the file the forward slashes are of course not present)

```

this works

\```{r}
library(knitr)
include_graphics('img/test.png')


\```

``` 

ok, so this works.  test.qmd in the qmd-directory contains the the same content as index.qmd. 

However, suppose I want to keep my qmd-files in a subdirectory, and have the img folder in the project dir. That would look Like this:

```
.
├── img
│

 └── test.png
├── index.qmd
├── qmd
│

 └── test.qmd
└── _quarto.yml



``` 

the yaml now looks like this, as I include a subfolder called 'qmd' with quarto files.

``` 
project:
  type: book

book:
  title: "this is a title"
  chapters:
    - index.qmd
    - qmd/test.qmd
``` 

index.qmd have the same content as before. test.qmd in the qmd-directory contains the the same content as index. 

When I run quarto preview, the image is displayed in the index.qmd file. However, the file test.qmd gives cause to the following error

``` 
Error in include_graphics("img/test.png") :
  Cannot find the file(s): "img/test.png"
``` 

I cannot seem to get around this. including this in the yaml:

``` 
output-dir: _output
execute-dir: project
``` 

does not work. Neither does Setting this in the chunk:

``` 
knitr::opts_chunk$set(root.dir = normalizePath("img"))  
knitr::opts_chunk$get("root.dir")  
```

I also tried making an _eviroment file in the root dir with the following content:

``` 
QUARTO_PROJECT_DIR='path-to-project-dir'
```

still no dice. 
 
the strange thing about it is that non-image related inputs, like using read.csv() works fine (e.g. putting a csv file in the img folder and loading that works. it's only related to images, as fas as I can tell, where the project dir fails.)

this also applies to markdown style images .  It tries to find the folder under 'qmd' no matter how I try to change it (also: putting the img-folder under the 'qmd' folder also fails, which you would think it wouldn't.

I updated to version 1.2.237 of quarto  to see if using the project envir variables would work. I'm on Manjaro linux w. i3, fully updated.

I use the cli version of quarto, not thru Rstudio. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.b

**Comment by cscheid** [comment]
The "current directory" is `qmd`, so I believe you need `../img/test.png`, etc.

**Comment by emilBeBri** [comment]
This does not work either - the '..' does not get expanded. 

the bottom line of this is that you cannot add an image file to any qmd-file that is not the project dir - this makes project management unnecessarily untidy, since you can't have a folder called 'qmd' which all the book-chapters, for example - not if you're trying to add image-files. 

Please tell me how I can help you reproduce this, as this is very important for my work

**Comment by emilBeBri** [comment]
The output is:

```
Quitting from lines 9-13 (que-1.qmd)
Error in knitr::include_graphics(".. /img/test.png") :
  Cannot find the file(s): ".. /img/test.png"
Calls: .main ... eval_with_user_handlers -> eval -> eval -> <Anonymous>

Execution halted

```

so the expansion does not take place.

**Comment by dragonstyle** [comment]
That output makes is appear that there is a space in the path - is that an output artifact or could that be the cause of the issue? I would also expect `../img/test.png` to be correct.

**Comment by dragonstyle** [comment]
(didn't mean to close)

**Comment by emilBeBri** [comment]
my mistake, I also did it without the space. 

It seems that the 'img' folder cannot be placed in the project subdir, like 'qmd', but have to be in the project folder. So this works:
```
knitr::include_graphics("img/test.png")


```
but this does not:

```
knitr::include_graphics("qmd/img/test.png")


```

**Comment by emilBeBri** [comment]
It's not optimal, but it is ok, though - as long as I don't have to place all the qmd files in the project dir, but can stow them away in the qmd folder, I can live with having the img-folder in the project dir :)  

HOWEver, it would be REALLY nice, and a lot less confusing,  if there was a yaml option that would set the project directory once and for all, and that also got respected by knitr by default. I tried making a file called 
_enviroment, and place this in it:

```
QUARTO_PROJECT_DIR='/home/emil/Dropbox/data-science/quarto/test-01

````
but that is not respected by knitr, either.

**Comment by emilBeBri** [comment]
this might be of use for troubleshooting more?  it seems to be confused about what's the root folder is, even though I have explicitly set it in all all the (global) places I could think of: 
```
compilation failed- missing packages (automatic installed disabled)
Unable to load picture or PDF file 'qmd/qmd/img/test.png'.
<to be read again>
                   }
l.251 ...ng \includegraphics{qmd/qmd/img/test.png}
```

again, placing the img folder in the project dir, this goes away. But it really should work I think.

**Comment by emilBeBri** [comment]
No wait what I said above is wrong:  You need to have have a symlink so that the img folder is in BOTH the project dir AND the qmd folder, otherwise it fails...!!

**Comment by mcanouil** [comment]
I am not 100 % sure the "needs-repro" label is outdated here.

Would it be possible to share a reproducible (not working) example, maybe as a Git repository, in order to have all pieces in one place?

Meanwhile, I flag this as "stale" at least temporarily.

---

Thank you for using Quarto and reporting an issue!

Unfortunately, this issue is now considered stale because it has been opened since 14 days without providing a "working" reproducible example to help us investigate.
If you are still facing the issue, please review the ["Bug Reports" guide](https://quarto.org/bug-reports.html) on how to provide a fully reproducible example as a self-contained Quarto document or a link to a Git repository.
Without a reproducible example, it is unlikely that the issue will be addressed and thus will be closed.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

_Remove `stale` / `needs-repro` labels or this will be closed in 14 days._
