### ISSUE TITLE
`::: {.content-hidden unless-format="html"}` with `plotly` seems to end up in pdf output

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#3254]
### Bug description

There seems to be an issue with plotly inside of divs that normally shouldn't be run and displayed e.g. in the following qmd file:

````md
---
title: "Untitled"
# prefer-html: true
format:
  html: default
  pdf: default
---

# Test

::: {.content-hidden when-format="html"}
Will not appear in HTML.
:::

This works:

::: {.content-hidden unless-format="html"}
Should appear in the html

```{r}
knitr::kable(mtcars, format = "html")
```
:::


The following fails with

> Error: Functions that produce HTML output found in document targeting pdf output.

::: {.content-hidden unless-format="html"}
Should appear in the html, but not in the pdf:

```{r}
library(tidyverse)
plt <- ggplot(mtcars, aes(mpg, disp)) +
  geom_point()

plotly::ggplotly(plt)
```

:::

or when forced through `prefer-html: true` with:

> LaTeX Error: Missing \begin{document}.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.78 <
>       script src="test_files/libs/htmlwidgets-1.5.4/htmlwidgets.js"></script> 
````

quarto version: 1.2.269

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jmbuhr** [comment]
That makes sense. I think it was discussed at some point whether it is possible to prevent execution, but with independent engines it seems hard.

However, I still wonder about
> Error: Functions that produce HTML output found in document targeting pdf output.

Because if we render to html and look at the intermediat markdown generated by  `knitr` using `keep-md: true` we find:
````
::: {.content-hidden unless-format="html"}
(...)
::: {.cell-output-display}
```{=html}
(the plotly output)
```
:::
:::
````
which renders just fine with quarto.
(i.e. `quarto render test.qmd -t html` followed by `quarto render test.md -t pdf`)

So I think the safeguard in quarto to check for html-producing functions is overeager in this case.

**Comment by jmbuhr** [comment]
Interestingly, if I ignore this error with `prefer-html: true` things like
```
<script src="test_files/libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="test_files/libs/plotly-binding-4.10.0/plotly.js"></script>
```
end up raw in the `.tex` file, causing it to fail.

So, not using `prefer-html` and instead `quarto render test.qmd -t html` followed by `quarto render test.md -t pdf` works, but `quarto render test.qmd -t pdf` does not. It's a bit puzzling to me why it works in two steps but not in one.

**Comment by katossky** [comment]
Run into the same issue. Tried to deactivate all cells containing HTML within `knitr` directly, but HTML content is nevertheless detected and <script> tags injected into `md`, resulting into the same error as described here.

**Comment by cderv** [comment]
@jmbuhr @katossky just to add some explanation context as I am passing by: 

* Using HTML widgets like plotly with **knitr** computation engine should do a screenshot to insert into PDF output. So no error should be thrown. This requires **webshot2** or **webshot** R 📦 . Detail in https://github.com/quarto-dev/quarto-cli/issues/4225#issuecomment-1418709061

* `prefer-html` is not to be used with PDF output as it will effectively try to force insertion of HTML. I need to adapt the documentation. This is a R Markdown backported feature that should not be useful for Quarto. 

* @katossky about 
  > Tried to deactivate all cells containing HTML within knitr directly, but HTML content is nevertheless detected and <script> tags 
  injected into md, resulting into the same error as described here.

  I am reading 'within knitr directly' as using R code in a chunk - It may be something else. Can you open an new issue ? 

  Thank you

**Comment by cderv** [comment]
FWIW this has been fixed already and not the OP example works ok. 

No leakage anymore in the .tex file of the HTML dependencies.
