### ISSUE TITLE
Rendering to docx hangs when flextable used; new issue with Quarto v 1.2

### ISSUE THREAD

**Issue by eeholmes** [quarto-dev/quarto-cli#3257]
Quarto Version: 1.2.246
flextable 0.8.3 (latest)

### Bug description

When I render (in RStudio or terminal), it hangs if I have a flextable. Hanging started with Quarto 1.2 release. Still works fine with Quarto 1.1 on RStudio Cloud.

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.

```
    ---
    format: docx
    ---

    ```{r}
    flextable::flextable(head(mtcars))
    ```
```

The output is this and then after the last line, the render spinwheel spins forever.
```
processing file: test.qmd
  |..............                                                        |  20%
  ordinary text without R code

  |............................                                          |  40%
label: unnamed-chunk-1 (with options) 
List of 2
 $ results: chr "asis"
 $ eval   : logi FALSE

  |..........................................                            |  60%
  ordinary text without R code

  |........................................................              |  80%
label: unnamed-chunk-2
  |......................................................................| 100%
  ordinary text without R code

output file: test.knit.md

pandoc 
  to: docx
  output-file: test.docx
  default-image-extension: png
  
metadata
  editor: visual
```
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- 
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?

2022.07.1 Build 554

But same rendering hang happens when I do `quarto render test.qmd`

- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

Apple M1, BigSur

**Note renders fine on RStudio Cloud with Quarto 1.1.251**

**Comment by cscheid** [comment]
Thanks for the reports. Unfortunately, I can't reproduce. I'm on an Apple M1 as well (though on Monterey) and on the latest version of Quarto, I see this:

````
$ quarto render 3257.qmd


processing file: 3257.qmd
  |...................................                                   |  50%
  ordinary text without R code

  |......................................................................| 100%
label: unnamed-chunk-1

output file: 3257.knit.md

pandoc
  to: docx
  output-file: 3257.docx
  default-image-extension: png

Output created: 3257.docx
````

## 3257.qmd

````
---
format: docx
---

```{r}
flextable::flextable(head(mtcars))
```
````

## 3257.docx

<img width="704" alt="image" src="https://user-images.githubusercontent.com/285675/200954950-4bb3faa6-c380-4aff-82a5-761a6d510d31.png">

**Comment by cscheid** [comment]
Can you try [v1.2.269](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.2.269)?

**Comment by eeholmes** [comment]
Ok v1.2.269 works!
