### ISSUE TITLE
`output-location` doesn't work in YAML header

### ISSUE THREAD

**Issue by wklimowicz** [quarto-dev/quarto-cli#3261]
### Bug description

Thanks for all your work on this!

`output-location` should work when placed in the YAML header. Currently this option only works when placed inside individual chunk options. Example:

````md
---
format: revealjs
knitr: 
  opts_chunk: 
    echo: true
    output-location: fragment
---

```{r}
5 + 5
```
````

Tested on Fedora 37 and Windows 10, and development version and on 1.1.251.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
@wklimowicz thanks for the report. Do we have documentation stating that "`output-location` should work when placed in the YAML header"? The only reference I see is in ["code cells"](https://quarto.org/docs/reference/cells/cells-knitr.html#cell-output).

**Comment by wklimowicz** [comment]
I think it's implied [here](https://quarto.org/docs/presentations/revealjs/index.html#output-location) - this section refers the user to the [execution options](https://quarto.org/docs/computations/execution-options.html) section, which states:

> All of these options can be specified either globally (in the document front-matter) or per code-block.

If this is working as intended then this could possibly be an enhancement? The rationale would be that most options can be set as default in the front-matter, although this might be a special case because it only works with revealjs.

**Comment by cscheid** [comment]
TODO:

- [ ] add `output-location` to revealjs schema
- [ ] add documentation about supported opts_chunk options

**Comment by dragonstyle** [comment]
I've updated the schema to include `output-location` as a top level and cell level option. I didn't make any changes to `opts_chunk` as I think our approach here should be to support this as a simple top level option rather than going through opts_chunk:

```
---
title: "sample"
format:
  revealjs:
    output-location: slide
---
```
