### ISSUE TITLE
Computed notebook figure cross reference not rendered in html format

### ISSUE THREAD

**Issue by jensodeg** [quarto-dev/quarto-cli#3295]
### Bug description

Cross references to a figure I create in a Jupyter Notebook cell do not render in other cells in the notebook.
I've tested this on both Windows 11 and Ubuntu 22.10. Quarto version `1.2.269`.

How to reproduce:
Create a test notebook with a raw cell, a code cell and a markdown cell.

```
---
title: Test
format: 
  html:
    code-fold: true
jupyter: python3
---
```
```
#| label: demolabel
#| fig-cap: Figure caption

import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot([1, 2, 3])
```
```
See @demolabel
```

Here's the result when I use `quarto preview test.ipynb`. As you can see @demolabel hasn't been turned into a cross reference to the figure, which is what I expected.

![bilde](https://user-images.githubusercontent.com/68481529/201398276-e292a745-026c-489e-963b-9bb30be4dc63.png)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Have you tried `fig-demolabel` as your crossref key? The labels need to correspond to the appropriate types. This is described in our crossref documentation https://quarto.org/docs/authoring/cross-references.html

**Comment by jensodeg** [comment]
Thank you, it works fine. I did not realize that I had to use label prefixes such as `fig-` and `tab-`.
