### ISSUE TITLE
Feature request - sort listings by specified order

### ISSUE THREAD

**Issue by kmasiello** [quarto-dev/quarto-cli#3296]
In the case of

```
listing: 
      contents: 
        - should be first.qmd
        - I'm second.qmd
        - third.qmd
``` 

the default ordering of listing items will be based on title, which in the case above, would list articles as:
1. I'm second
2. should be first
3. third 

Using `sort` with its current implementation, I can only sort by a listing field within each document, which may not be appropriate for organizing the listings on the page. I would like the ability to sort the listing order based on the order the items are specified in `contents` 

My workaround is to create a yml file with the listing contents in the order I desire, but I'd rather not add additional complexity

**Comment by dragonstyle** [comment]
We need to include a way to specify original order (the underlying system supports it but there is no way for a user to specify this, currently!)
