### ISSUE TITLE
index.html redirects to incorrect file

### ISSUE THREAD

**Issue by poldrack** [quarto-dev/quarto-cli#3297]
### Bug description

When I render a qmd file to a website, the index.html points to the incorrect file. reproducible exampl here: https://github.com/poldrack/talks-nipreps. inside cloned repo:

```
rm -rf docs 
quarto render NiPreps.qmd
```

This renders to docs/talk - index.html in that folder should redirect to NiPreps.html, but instead redirects to LICENSE.html:

```
% more docs/talk/index.html
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Redirect to LICENSE.html</title>
    <meta http-equiv="refresh" content="0;URL='LICENSE.html'" />
  </head>
  <body>
  </body>
</html>
```

This is using quarto CLI version 1.2.267 on Mac OS 12.6

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mcanouil** [comment]
Your project is not a Quarto website project.
I do not understand what you do to make this happen.
The Quarto command you show cannot make what you described considering your GitHub repository directory tree:

```sh
❯ tree -L 2
.
├── LICENSE.md
├── Makefile
├── README.md
├── docs
│   ├── index.html
│   ├── pdfs
│   └── talk
└── talk
    ├── NiPreps.qmd
    ├── images
    └── rp-theme.scss

5 directories, 6 files
```

Also what's your `index.html`, I do no believe it was created by Quarto based on your repository.

Could you make your example fully reproducible and/or explain with more details your workflow?

**Comment by poldrack** [comment]
sorry the organization wasn't clear. Here is a fully reproducible example:

```
% git clone https://github.com/poldrack/quarto-test.git
% cd quarto-test
% make test-broken
rm -rf docs/*
quarto render .
[1/2] LICENSE.md
[2/2] talk.qmd

Output created: docs/LICENSE.html

cat docs/index.html
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Redirect to LICENSE.html</title>
    <meta http-equiv="refresh" content="0;URL='LICENSE.html'" />
  </head>
  <body>
  </body>
</html>
``` 

in this first example you will see that the index.html file created by `quarto render` links to the LICENSE.html file.

If we hide the LICENSE.md file, then you see that it properly links to test.html:

```
% make test-works
echo "Hiding LICENSE.md"
Hiding LICENSE.md
mv LICENSE.md .License_hidden
rm -rf docs/*
quarto render .
...
Output created: docs/talk.html

cat docs/index.html
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Redirect to talk.html</title>
    <meta http-equiv="refresh" content="0;URL='talk.html'" />
  </head>
  <body>
  </body>
</html>

```

There thus seems to be some problem with the logic of how the file selected as the index is being chose - seems like it should automatically refer to the talk file.

**Comment by mcanouil** [comment]
Follow-up on this after quite a while.
It seems Quarto takes the ~~first markdown-based document~~ `LICENSE.md as the index page, _i.e._, I quite don't really understand why this particular file ...
It does not seem to be related to alphabetical order of the files.

Note that `touch index.md` "solves" the issue.

```sh
git clone https://github.com/poldrack/quarto-test.git .
touch index.md
#> quarto render
#> [1/3] LICENSE.md
#> [2/3] talk.qmd
#> [3/3] index.md
#> 
#> Output created: docs/index.html
```

In my opinion, `Quarto` should error out if no index file is provided in a book or website project.


In addition, I noticed something weird, while `touch index.md` "worked", the following raised a warning that in my opinion should appear also for `index.md`.

```sh
touch 0000.md
quarto render 
#> [1/4] LICENSE.md
#> [2/4] talk.qmd
#> [3/4] 0000.md
#> [WARNING] This document format requires a nonempty <title> element.
#>   Defaulting to 'quarto-input0e9ca484' as the title.
#>   To specify a title, use 'title' in metadata or --metadata title="...".
#> [4/4] index.md
#> 
#> Output created: docs/index.html
```

Output/results from Quarto CLI v1.3.153 pre-release.

**Comment by dragonstyle** [comment]
I'm actually ok with how we're behaving in this situation - since we can't determine what the index page should be, we use the first file in the render list. This is controllable in a number of ways:

1) Create a file that results in an index.html (for example `index.md`). This will mean we won't generate a redirect file.

2) Use project > render to control what files are rendered, for example:

```
project:
  type: website
  output-dir: docs
  render: 
    - talk.qmd
```

3) Use project > render to control the order in which files are rendered, for example:

```
project:
  type: website
  output-dir: docs
  render: 
    - talk.qmd
    - LICENSE.md
```

I don't think there is way for us to know which file should be the index (short of you making it be the index or it being the first file in the rendered list).

HTH!
