### ISSUE TITLE
Python not found by Quarto

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-cli#33]
I've been getting this error whenever I try to render Python code:

![image](https://user-images.githubusercontent.com/6981612/121452484-19ffb380-c965-11eb-8b12-eb80b7a02105.png)

I'm running the code from the [Hello, Quarto](https://quarto.org/#hello-quarto) example. I'm able to execute it as a Jupyter Notebook and as standalone Python script and save the output as an image.  This error happens when I try to render it either as a Jupyter Notebook or as a qmd file.

I thought this might have been because I was originally doing this from a conda virtual environment, but I uninstalled all the Python versions on my machine and did a fresh reinstall and am still getting the same error.

The path given by `which python` matches the one in my `quarto env`...

![image](https://user-images.githubusercontent.com/6981612/121453551-f9385d80-c966-11eb-8bb9-c24ef1de23ef.png)

![image](https://user-images.githubusercontent.com/6981612/121453472-d6a64480-c966-11eb-9085-1a0cc66a27e0.png)

...though there is another entry in there that I'm not quite sure got there.

This is on the most recent version of `quarto-cli` though it has been happening for the past couple of days.

**Comment by cderv** [comment]
> there is another entry in there that I'm not quite sure got there.

FWIW The second entry is from the python installation that you get from WindowsStore. You can install python this way and the executable will be available (aliased ?) there. The folder is in PATH by default. You should be able to check on WindowsStore that it is installed.

**Comment by pommevilla** [comment]
Resolved by https://github.com/quarto-dev/quarto-cli/commit/227e6bb6d02fed6a061fc0c94812d15cbd87e373.

**Comment by cderv** [comment]
@pommevilla installing Python using the one from python.org makes it works as we discussed. 
So installing like this is ok to have a working setup as python will be added to PATH
```powershell
winget install 'Python 3'
```` 

Windows Store version is another story.
