### ISSUE TITLE
html `number-sections: false` does not remove numbering from html <head>

### ISSUE THREAD

**Issue by alxsimon** [quarto-dev/quarto-cli#3304]
### Bug description

html option `number-sections: false` does not remove numbering in
html `<head><title>` metadata, leaving numbering in tabs.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report. Can you give us a .qmd that triggers the issue for you?

**Comment by alxsimon** [comment]
I have the issue with this book https://github.com/alxsimon/ecoevo.social-docs
It's not a minimal example but really small and compiles in a few seconds.

I don't really see how I can have a book with several chapters in only one .qmd file, is that possible?
