### ISSUE TITLE
Numbered and cross-referencable Remarks

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#3323]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3322

<div type='discussions-op-text'>

<sup>Originally posted by **AlbertRapp** November 14, 2022</sup>
Would it be possible to transform the `.remark` class into a `#rem-` name such that remarks are numbered and become cross-referenceable?

According to the [docs](https://quarto.org/docs/authoring/cross-references.html#theorems-and-proofs) this is intended behavior.
In mathematics, we use remarks all the time and cross-reference them too. That's easy in LaTeX. Would be great if that's possible in Quarto too.</div>

**Comment by cscheid** [comment]
This is effectively a duplicate of #1655.

Using the upcoming terminology of crossrefs in Quarto 1.4, this issue is about customizable "categories" of "Block" crossrefs, and #1655 is about customizable "categories" of "Float" crossrefs.

(For quarto users: we'll be documenting all of this thoroughly. I'm targeting these comments for the quarto developers right now)

**Comment by cscheid** [comment]
@ute Thanks for the link! I tried to render your example file but it seems I'm missing a `list-of-mathstuff.qmd` file.

**Comment by ute** [comment]
Thank you, @cscheid !
It was an include shortcut in an html comment that caused the example not to work without `list-of-mathstuff.qmd`. But embarrassingly, I realized that I had pushed a fix for books without testing on single documents again. That bug is also fixed now.

**Comment by cscheid** [comment]
Documentation for this is still incoming, but on main, `#rem-...` divs are crossreferenceable in HTML and LaTeX as "Remark" environments, as are `#sol-` divs, for "Solution" environments.

Unfortunately, doing "Proof" was annoying because of the way it works in LaTeX. The building blocks are there but it'll have to wait for 1.5, as will formats other than LaTeX and HTML.
