### ISSUE TITLE
No way to escape special characters in mermaid embedded in quarto docs. 

### ISSUE THREAD

**Issue by bayeslearner** [quarto-dev/quarto-cli#3328]
### Bug description

 I took a json string and escaped it, and it works fine as text embedded inside mermaid (tested using mermaid online https://mermaid.live/), but quarto fails to compile the mermaid graph as part of a slide presentation. 

```
graph TD
    A["{&quot;a&quot;:2,&nbsp;<br/>&nbsp;&nbsp;&nbsp;&quot;b&quot;:3,&nbsp;&nbsp;<br/>&nbsp;&nbsp;&nbsp;&quot;d&quot;:&quot;b&quot;}"] -->|jq| B(Go shopping)
    B --> C{Let me think}
```

graph TD
    A["{&quot;a&quot;:2,&nbsp;<br/>&nbsp;&nbsp;&nbsp;&quot;b&quot;:3,&nbsp;&nbsp;<br/>&nbsp;&nbsp;&nbsp;&quot;d&quot;:&quot;b&quot;}"] -->|jq| B(Go shopping)
    B --> C{Let me think}

<img width="224" alt="image" src="https://user-images.githubusercontent.com/68746303/201810969-15d7817b-6358-43d3-9a27-a2291f880267.png">

2022.07.2 Build 576

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I can't reproduce this on `v1.3` with the following .qmd file:

````
---
title: "3328"
format: revealjs
---

```{mermaid}
graph TD
    A["{&quot;a&quot;:2,&nbsp;<br/>&nbsp;&nbsp;&nbsp;&quot;b&quot;:3,&nbsp;&nbsp;<br/>&nbsp;&nbsp;&nbsp;&quot;d&quot;:&quot;b&quot;}"] -->|jq| B(Go shopping)
    B --> C{Let me think}
```
````

**Comment by bayeslearner** [comment]
Really?  I'm getting this: 
<img width="322" alt="image" src="https://user-images.githubusercontent.com/68746303/202871717-af159916-7ca4-4904-84c6-d673ab8c94d9.png">

**Comment by cscheid** [comment]
Oh, I think I know what this is, unfortunately. It's not really something we can control. Can you take a look at the "About" page on your installation of RStudio? Does it say something about Qt/WebEngine or similar?

**Comment by bayeslearner** [comment]
Yes, that seems to have solved the issue.

**Comment by cscheid** [comment]
Glad to hear.

I'm following up with the RStudio team to see if we can have quarto figure out that this problem is about to happen and then warn the user rather than have mermaid fail opaquely
