### ISSUE TITLE
Title color in beamer themes unmatched

### ISSUE THREAD

**Issue by Gabrielforest** [quarto-dev/quarto-cli#333]
Hi! I am trying to use themes from beamer but all the themes that I have tried has the same blue color in the title from this figure below instead of different tons of red:

![image](https://user-images.githubusercontent.com/63704591/153508378-5925b6f6-631b-4297-87ad-f145559d484a.png)

The following code was used in this figure above:

![image](https://user-images.githubusercontent.com/63704591/153508668-84474bed-9087-4af8-b346-8bd06421ad67.png)

Obs.: I have tried the problem solution suggested at #299 but it didn't solve.

**Comment by dragonstyle** [comment]
Thanks for letting us know! It looks like we're coloring links by default for all latex/pdf output, which isn't desirable in this case (beamer). I'll get a fix on the way and post here when it is ready.

**Comment by dragonstyle** [comment]
OK this should be fixed here:

https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.4

Thanks again for taking the time to report this issue!

**Comment by Gabrielforest** [comment]
This works perfectly, thanks a lot!
