### ISSUE TITLE
Changing `code-block-border-left-size`, `code-block-border-left-style` and `max-width` 

### ISSUE THREAD

**Issue by elgabbas** [quarto-dev/quarto-cli#3337]
### Bug description

Hello,

I am trying to change the values of `code-block-border-left-size`, `code-block-border-left-style` and `max-width`, without success. Do I correctly change them or is this due to a bug?

````
---
format:
  html:
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-block-border-left-style: "dotted" # no effect
    code-block-border-left-size: "10px" # also tried 10px or 10 without quotation
    max-width: "1800px" # no effect
---
```{r}
#
1 + 1
```
```{r}
#
2 * 2
```
````

![image](https://user-images.githubusercontent.com/7375051/202016853-79149760-3170-4a18-8f00-b94f675d54db.png)

Thanks, Ahmed

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
`code-block-border-left-size` and `code-block-border-left-style` are SCSS variables, not HTML format options. They should be instead configured by providing a custom [theme](https://quarto.org/docs/output-formats/html-themes.html).

`max-width`, if I understand your intent correctly, is a CSS property of some of the elements in the HTML page. That should be configured by identifying the correct selectors, creating the appropriate CSS rules, and adding the CSS to your page.

**Comment by elgabbas** [comment]
This was not clear for me.... Thanks @cscheid ... 

I want to increase the width of the HTML page. I used `page-layout: full` to make it somehow wider, but was expecting that I can make it wider (probably fit the width of the screen) by changing the `max-width` option. Is it possible to make the HTML wider than using `page-layout: full`?

Thanks, Ahmed

**Comment by cscheid** [comment]
For these general questions, you can go to quarto.org, hit the search button, and then type in your terms. In this case, `page-layout` leads to https://quarto.org/docs/output-formats/page-layout.html

**Comment by elgabbas** [comment]
Thanks.....
