### ISSUE TITLE
Invisible links in mermaid

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#3350]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3349

<div type='discussions-op-text'>

<sup>Originally posted by **aghaynes** November 16, 2022</sup>
According to the help files for mermaid, it is possible to have invisible links between nodes in mermaid charts, which can be particularly useful for enforcing a particular layout. https://mermaid-js.github.io/mermaid/#/flowchart?id=an-invisisble-link E.g. the following code should produce the flowchart further down.

````
```{mermaid}
flowchart LR
  box1 --> box2
  box2 --- box3
  box4 ~~~ box2
```
````

![grafik](https://user-images.githubusercontent.com/6594028/202184980-eb80dff4-305e-4c94-96c5-fcf78c9f62bb.png)

Executing the chunk in quarto produces a syntax error though. 

It seems like the invisible links are probably a new feature (there's an issue referencing a commit in mid-October - https://github.com/mermaid-js/mermaid/issues/3192). 

I guess this would require an update to the version of mermaid in quarto?</div>

**Comment by fkohrt** [comment]
@cscheid It seems invisible links have been removed as a feature in mermaid v9.3.0 again. At least I cannot find the changes that were introduced by the following two commits neither in [`v9.3.0`](https://github.com/mermaid-js/mermaid/tree/v9.3.0) nor in [`develop`](https://github.com/mermaid-js/mermaid/tree/develop):

- mermaid-js/mermaid@eec97d10af2ba016f26fe0e772d2405689441e58
- mermaid-js/mermaid@4d46ea9801ad1d6e8eddf6e97f2e89e8fc993c26

**Comment by cscheid** [comment]
@fkohrt I apologize, but we will be upgrading mermaid once per release and no further; it's not sustainable for us to continually chasing their changes. If your setup requires `mermaid` to be on the very latest version, I think the best shot is for you to download the github repo for quarto, and update `mermaid.js` and `mermaid.min.js` yourself based on the commit 75fd336.

**Comment by fkohrt** [comment]
@cscheid Thank you very much for your hints and pointers. However, there is no feature that a more recent version of mermaid has that I want. Rather, I wanted to inform you that _in case_ you decide to bump your mermaid dependency in the future, you will have to re-open this issue, as invisible links have been removed as a feature in mermaid v9.3.0. This is not actionable, just a heads-up :)

**Comment by cscheid** [comment]
@fkohrt I appreciate the heads up!

**Comment by fkohrt** [comment]
Invisible links will be re-introduced with mermaid v10.0.0 (see mermaid-js/mermaid#4113).
