### ISSUE TITLE
Render PDF: 'Open in Browser' opens wrong link (code-server with Jupyter Server Proxy)

### ISSUE THREAD

**Issue by benz0li** [quarto-dev/quarto-cli#3352]
### Bug description

<img width="958" alt="render-pdf_open-in-browser" src="https://user-images.githubusercontent.com/20233085/202265650-f31857fe-c785-4506-99e3-2605a49c593f.png">

'Open in Browser' opens https://coder.jupyter.b-data.ch/hub/proxy/7095/web/viewer.html, which is wrong.

---

<img width="958" alt="render-pdf_browse-at" src="https://user-images.githubusercontent.com/20233085/202265934-2a898c15-23d0-4d90-8133-19f3ce67c659.png">

Browse at shows https://coder.jupyter.b-data.ch/user/benz0li/code-server/proxy/7095/web/viewer.html, which is correct.

---

@jjallaire @cscheid @dragonstyle May be reproduced at https://coder.jupyter.b-data.ch with image `R (jupyterlab/r/verse:latest-devtools)` using

````qmd
---
title: "ggplot2 demo"
author: "Norah Jones"
date: "5/22/2021"
format: 
  html:
    code-fold: true
    fig-format: svg
---

## Air Quality

@fig-airquality further explores the impact of temperature on ozone level.

```{r}
#| label: fig-airquality
#| fig-cap: Temperature and ozone level.
#| warning: false

library(ggplot2)

ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess"
)
```
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by benz0li** [comment]
`R (jupyterlab/r/verse:latest-devtools)` is based on [`debian:11`](https://hub.docker.com/_/debian) and has a [patched](https://github.com/quarto-dev/quarto-cli/commit/e0c4d8d093ff454136c94d99c8d595b3583c63b3) version of Quarto 1.2.269 installed.

**Comment by benz0li** [comment]
ℹ️ The link for 'Open in Browser' is only wrong for 'Render PDF'. For 'Render DOCX' and 'Render HTML' the link is correct.

Please consider this issue for a patch release of v1.2.

**Comment by benz0li** [comment]
> Is this a regression?

No.

**Comment by benz0li** [comment]
'Open in Browser' for 'Render DOCX' and 'Render HTML' work *out of the box*.

I am quite sure, that the 'Open in Browser' URL for 'Render PDF' is being tampered with somewhere.

**Comment by jjallaire** [comment]
That popup isn't one that we are creating (that's VS Code / Code Server detecting a port). I think difference is that PDFs are hosted inside a special viewer URL whereas DOCX and HTML are hosted at the main root URL. Note that we do redirect from the main URL to the special viewer URL.

**Comment by benz0li** [comment]
> Note that we do redirect from the main URL to the special viewer URL.

I will check where the 'special viewer URL' is created and add a special handling for `isVSCodeTerminal() && isVSCodeServer()`.
