### ISSUE TITLE
quarto publish quarto-pub put user sites in bad state

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#3365]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3362

<div type='discussions-op-text'>

<sup>Originally posted by **robertwelz** November 17, 2022</sup>
Hi,

i wanted to deploy a website (created with quarto) using QuartoPub using the `quarto publish quarto-pub.` command. I believe i followed all steps in the documentation carefully, but when i publish the website, it only shows a "Page not found" error. I even deleted the old project and started a new website-project from scratch but without success. Here is the link to the website: 

[https://robertwelz.quarto.pub/mockwebsite_statistics/](https://robertwelz.quarto.pub/mockwebsite_statistics/)

If i can provide more information to solve this problem, please let me know. I'm a total beginner in this.

Thanks
Robert
</div>

**Comment by cscheid** [comment]
@robertwelz Can you try the following?

1. log on to https://quartopub.com with the credentials you use to publish
2. find the site that isn't working and click on it. For me, this looks like this: 
<img width="1682" alt="image" src="https://user-images.githubusercontent.com/285675/202570759-262cb422-d5c2-4c0f-9a71-fd4df07ea97f.png">
3. You should land at a page that looks like this: 
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/285675/202570906-0c3473e7-cde9-45d1-80c8-e0c235e3205b.png">
4. Click on "delete site" on the bottom right: 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/285675/202570947-30d6c8a1-bb15-4ef7-aa92-94cb9fc47890.png">
5. try publishing again?

**Comment by robertwelz** [comment]
Unfortunately it still does not work.

**Comment by cscheid** [comment]
@robertwelz Can you provide more information about what happened? Did `quarto publish` go through fine? Were there error messages anywhere? Did `_publish.yml` change?

**Comment by cscheid** [comment]
(Thanks for the continued patience!)

What happens if you change the site name from `mockwebsite_statistics` to something else? I ask because I wonder if the error is associated to that specific site or to your account more generally.

**Comment by cscheid** [comment]
Don't apologize, this is 100% a bug on our side. Thanks for tracking it down, and I'm happy changing the account is a sufficient workaround for you.

@softwarenerd we might want to figure out what's happening with Robert's old account specifically, since the problem seems to be persistent.

**Comment by softwarenerd** [comment]
@cscheid, yes. I will be looking into this. Thanks for letting us know, @robertwelz.

**Comment by jacciz** [comment]
I'm having this same issue.  Seems like it publishes just fine and I can see the preview. But when I click on the preview it says 'Not Found - Request ID: 01xxxxxxxxxxxx'. Tried changing the name to test, tried a new project with a basic qmd. Also tried to publish using my Quarto pub auth token in .Renviron .  I created a new account and still having issues (different, but similar).

**Comment by jacciz** [comment]
I got it to work! 3rd account later... also uninstalled quarto cli and reinstalled it. Updated R from 4.2.1 to 4.2.2. I still keep having to authorize after even publish.

**Comment by jkylearmstrong** [comment]
Has there been any update on this? 

I was just trying to push some changes I made the landing page 
```
https://user.quarto.pub/book/
```
looks fine, but when I try to navigate to another page with the the next page button or the chapter select I get this message:
![image](https://github.com/quarto-dev/quarto-cli/assets/29757798/5903c185-39b2-4405-9e5a-0293882451e7)

I am noticing is that when I try to navigate to a different page it goes to 
```
https://user.quarto.pub/chapter/section
```

as opposed to 
```
https://user.quarto.pub/book/chapter/section
```
If I add the book to the url link I can see my updates to the pages

**Comment by mcanouil** [comment]
I don't know if it is exactly the same thing.
FYI:
- #6469

**Comment by jkylearmstrong** [comment]
@mcanouil yes, that's it exactly! Thank you!

**Comment by mcanouil** [comment]
I cannot reproduce.
Which version of Quarto are you using?

**Comment by andreasludvig** [comment]
Wow, quick answer. I am using:
SUN-SDU+alosvendsen@ADM-128030 MINGW64 ~/OneDrive - Syddansk Universitet/PhD/Kurser/Biostat 2/justdelete
$ quarto --version
1.4.515

First i could not publish at all, from this pc (university pc), but succeeded from my personal pc. I then tried to >quarto publish within powershell opened with admin privileges' and it rendered, and prompted me to accept publication at my account. The preview looks fine:
![image](https://github.com/quarto-dev/quarto-cli/assets/98429673/e130d739-14b5-4ad1-b065-0a32ac82a328)
But opening the site just yields:
![image](https://github.com/quarto-dev/quarto-cli/assets/98429673/e8566190-86fd-4263-97f1-29684a8a3865)

**Comment by mcanouil** [comment]
Since no reports of issues were made regarding this recently and that I am unable to reproduce, it does not seem to be an issue with the cloud provider used for Quarto Pub.
When did you create your account?
Do you have another account you could try?

**Comment by frankcsliu** [comment]
I still see the same issue in 2026. Quite upset about this unstable feature.

**Comment by cderv** [comment]
@frankcsliu can you open a new issue sharing your URL and detail so we can investigate ? Thank you
