### ISSUE TITLE
Documented "Language Content" feature not implemented

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#3372]
The "language content" feature described in the [documentation](https://quarto.org/docs/projects/profiles.html#language-content) doesn't seem to be implemented: rendering the example gives a document with both the English and French quotes.

I think the feature would be bad as default behavior anyway: the `lang` attribute on divs and spans is an established feature in pandoc (unrelated to conditional content), and it's useful in its own right. For example, if I write an English document and add a French paragraph in a div tagged with `{lang=fr}`, for PDF output pandoc will wrap the paragraph in `\begin{otherlanguage}{french}...\end{otherlanguage}` which will apply the correct typographic rules for French.

Maybe this section of the documentation can removed?

Otherwise the feature could be implemented as opt-in behavior? (I agree it can be useful, I actually use `{lang=...}` for conditional content in some projects using a custom Lua filter.)

**Comment by cscheid** [comment]
You're correct! We misread Pandoc's [language docs](https://pandoc.org/MANUAL.html#language-variables). We'll remove that documentation right away. Thank you!
