### ISSUE TITLE
Auto-resolve external figures in PDF format

### ISSUE THREAD

**Issue by johannes4998** [quarto-dev/quarto-cli#3375]
When I change the format from html to pdf in the getting-started [example](https://quarto.org/docs/get-started/hello/rstudio.html)

I get the error
```
compilation failed- error
Unable to load picture or PDF file 'https://quarto.org/docs/get-started/hello/images/rstudio-hello.png'.
```
When I save the image local it works but I would prefer using the link.

**Comment by jjallaire** [comment]
I believe that @dragonstyle  just implemented a feature to download images during PDF rendering so this _should_ be resolved by this once its merged.

**Comment by dragonstyle** [comment]
We just merged these changes and a fresh pre-release build is on the way.
