### ISSUE TITLE
`keyboard-shortcut` shortcode  

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#3384]
We have inconsistently rendered descriptions of keyboard shortcuts on the website

- https://quarto.org/docs/get-started/authoring/rstudio.html ("Ctrl-Shift-P")
- https://quarto.org/docs/get-started/computations/rstudio.html ("⇧⌘K")

It would be really slick to have a `keyboard-shortcut` shortcode which rendered a default version of the description on non-interactive formats, but, optionally in javascript formats, sniffed the environment and only showed the os-specific version of the shortcut.

**Comment by jjallaire** [comment]
This should probably be a `{{< kbd Ctrl-Shift-P >}}` shortcode (matching the `<kbd>` HTML tag which is what we use in HTML output) that also works well in docx and pdf output.

**Comment by cscheid** [comment]
@jjallaire I have a 4 hour flight coming up. Let's see what happens :)

**Comment by cscheid** [comment]
This uses the `kbd` element in HTML formats, attempts to detect the OS and change the content in Javascript formats, and produces a simple written enumeration of shortcuts in other formats.
