### ISSUE TITLE
Author email and time not showing in html reports 

### ISSUE THREAD

**Issue by tmss1** [quarto-dev/quarto-cli#3393]
### Bug description

I am trying to to include the render date, time and author email addresses in html reports as in Rmd. For example:

![image](https://user-images.githubusercontent.com/32617414/202862718-de786a7e-720d-4ae6-b291-555ae83c1877.png)

However, I am not able to do that in Quarto, and the time and email just would not show, despite following the instructions here for author information:
https://quarto.org/docs/journals/authors.html 

```
title: "Main title in Qmd"
subtitle: "Subtitle"
author:
- name: Adam Smith
  affiliation: ABC institute
  email: "abc@email.com"
```

![image](https://user-images.githubusercontent.com/32617414/202862742-1da91153-caf5-4c0f-9552-5ca28049ba18.png)

System:
RStudio 2022.07.2 Build 576, in Windows 10 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Currently, the title block treatment for HTML documents in Quarto doesn't display the author's email address. If you're up for it, you can provide a custom title block to implement completely custom layout. More here: https://quarto.org/docs/journals/templates.html#html-partials

For display of the time, you should be able to provide a date with time and use a date format that includes time. For example:

```
---
date: last-modified
date-format:  YYYY-MM-DD HH:mm:ss
---
```

More on date formatting here: https://quarto.org/docs/reference/dates.html
