### ISSUE TITLE
`quarto install -lt` errors on Windows

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#34]
In powershell
````powershell
❯ quarto --version
v0.1.250
❯ quarto install -lt
ERROR TypeError: Error parsing args: serde_v8 error: ExpectedString
````

`-lt` is indicated as the shorter form of `--list-tools` which works.

**Comment by dragonstyle** [comment]
I overhauled the commands and have migrated `quarto install|update|uninstall` to:

`quarto tools`
`quarto tools list`
`quarto tools install tinytex`

etc... So this bug no longer exists. Thx for reporting it!
