### ISSUE TITLE
ERROR: TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by renenadorp** [quarto-dev/quarto-cli#3411]
I'm running quarto on MacOS Monterey (12.1).
When issueing the render command I get the following error:
ERROR: TypeError: Cannot read properties of undefined (reading 'toLowerCase').

I've tried rendering from within VSCode and Jupyter Lab. Both give the same error message. 
No clue what causes this.

**Comment by dragonstyle** [comment]
Would you mind sharing what version of Quarto that you are using a sample document that reproduces the issue?
