### ISSUE TITLE
Impossible to render both Observable table and altair chart

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#3424]
### Bug description

Hi,
I have the code below.

If I try to render it, the altair chart is not rendered.

If I remove the OJS table the chart is rendered.

In the browser console I have these vega errors:

![image](https://user-images.githubusercontent.com/30607/203311284-6d0e6bd1-4ddf-4215-9e54-ba038d66f3a9.png)

I'm using quarto 1.3.19 in debian 11.

Thank you

### the code

~~~~
---
title: "tmp"
format:
  html:
    toc-depth: 4
jupyter: python3
---

## OJS

```{ojs}
//| echo: false
data = FileAttachment("tmp-ojs.csv").csv({ typed: true })
Inputs.table(data)
```

## altair

```{python}
#| echo: false
import pandas as pd
import altair as alt

df = pd.read_csv("tmp.csv",keep_default_na=False)

df['year'] = pd.to_datetime(df['year'], format='%Y')

alt.Chart(df).mark_area().encode(
    alt.X('year:T', timeUnit = 'year',title='year',axis=alt.Axis(tickCount='year')),
    alt.Y('v:Q',axis=alt.Axis(format='%'),title='percentage'),
    color='i:N'
)
```
~~~~

#### tmp-ojs.csv

```
F,G,C
9470719.0,1688.0,0.0
5459.0,371872.0,0.0
122.0,2.0,12366.0
26.0,17.0,0.0
```

####  tmp.csv

```
year,i,v
2016,F,0.9599716561118586
2016,G,0.0382418519682473
2016,C,0.0012657864805693667
2016,W,1.2161279236855405e-05
2016,S,4.5402109150926846e-05
2016,O,0.00046314205093691
2017,F,0.9598036277704027
2017,G,0.03840420504605933
2017,C,0.0012674079844676141
2017,W,1.5302943039709717e-05
2017,S,4.864511694742162e-05
2017,O,0.0004608111390831794
2018,F,0.959801296858549
2018,G,0.038401570102224676
2018,C,0.001268016048429457
2018,W,1.6519070963395258e-05
2018,S,5.3610972635804244e-05
2018,O,0.0004589869471976511
2019,F,0.9598036277704027
2019,G,0.03840420504605933
2019,C,0.0012674079844676141
2019,W,1.5302943039709717e-05
2019,S,4.864511694742162e-05
2019,O,0.0004608111390831794
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Unfortunately, this currently almost impossible to fix; altair uses one particular style of javascript imports (and overrides a global `require` function), and observable uses another.

**Comment by aborruso** [comment]
I'm adding the edited code. Thank you very much @cscheid 

~~~~
---
title: "tmp"
format:
  html:
    toc-depth: 4
jupyter: python3
---

## OJS

```{ojs}
//| echo: false
data = FileAttachment("tmp-ojs.csv").csv({ typed: true })
Inputs.table(data)
```

## altair

```{python}
#| echo: false
import pandas as pd
import altair as alt

df = pd.read_csv("tmp.csv",keep_default_na=False)

df['year'] = pd.to_datetime(df['year'], format='%Y')

chart=alt.Chart(df).mark_area().encode(
    alt.X('year:T', timeUnit = 'year',title='year',axis=alt.Axis(tickCount='year')),
    alt.Y('v:Q',axis=alt.Axis(format='%'),title='percentage'),
    color='i:N'
)
chart.save('chart.json')
```

```{ojs}
//| echo: false
file = FileAttachment("chart.json").json()
embed = require("vega-embed@6")
embed(file)
```
~~~~

**Comment by joelostblom** [comment]
@aborruso @cscheid A workaround for this seems to be to set `engine: knitr` instead of `jupyter: python3`. I'm not sure how jupyter and knitr kernels would impact the javascript rendering differently, but when I make that change and run `quarto preview my-file.qmd` I see both the OJS table and altair chart. 

![image](https://github.com/user-attachments/assets/6b8fb3d3-a662-4d5c-8d16-69b8b7d5d613)

**Comment by aborruso** [comment]
Wow, thank you very much @joelostblom !!

**Comment by cscheid** [comment]
They're completely different code paths. Python execution in knitr happens through reticulate, and reticulate appears to be doing a better job here.

**Comment by joelostblom** [comment]
The comment https://github.com/r-wasm/quarto-live/issues/47#issuecomment-2318271213 mentions general issues with pyodide and require.js, which might be related to that switching to the knitr kernel seems to fix the issue here?

**Comment by cscheid** [comment]
🤷? Sorry, we can't help you without specifics, and pointing to other issues in this way only tends to increase the confusion.

**Comment by joelostblom** [comment]
Sorry for being unclear. No help needed as I'm happy with using the `knitr` kernel as a workaround.

I just pointed to that issue in case it would be helpful to understand what is going on with the jupyter kernel here. That issue also reports a problem with require.js in a python context (but with pyodide) and you mentioned above that the main issue here might be a conflict between how altair and ojs use a require function, which only occur in a jupyter kernel context, so it seems to depend on something more than altair and ojs.

**Comment by aborruso** [comment]
> to set `engine: knitr` instead of `jupyter: python3`.

Hi @joelostblom if I set in this way, I have the quarto error below.

What else do I need to change, after having set `engine: knitr`?

Thank you

```
Quitting from lines 11-25 [unnamed-chunk-1] (input.qmd)
Error in `loadNamespace()`:
! there is no package called 'reticulate'
Backtrace:
  1. global .main()
 16. base::loadNamespace(x)
 17. base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 18. base (local) withOneRestart(expr, restarts[[1L]])
 19. base (local) doWithOneRestart(return(expr), restart)
Warning message:
The 'python' engine in knitr requires the reticulate package. If you do not want to use the reticulate package, set the chunk option python.reticulate = FALSE. 
Execution halted
```

**Comment by aborruso** [comment]
> What else do I need to change, after having set `engine: knitr`?

I think I should install reticulate in R `install.packages("reticulate")`

**Comment by joelostblom** [comment]
@aborruso yup, after installing reticulate it should work for you, but let me know if it doesn't for some reason!
