### ISSUE TITLE
Converting TeX math for `format: hugo`

### ISSUE THREAD

**Issue by pat-alt** [quarto-dev/quarto-cli#344]
When using `format: hugo` (or `gfm`) I believe that TeX is converted to unicode under the hood. The conversion seem to fail in some cases for no obvious reason (at least not obvious to me). Here's a minimal example of one such case:

```
Could not convert TeX math \mathbf{H}(\hat{\mathbf{w}}), rendering as TeX
```

I assume part of that TeX simply cannot be mapped to unicode, but what specifically? What's a good way to deal with this in practice?

PS: I continue to be amazed by this project. Recently stumbled across the VS Code extension, which is a really nice add-on. Love this :heart:

**Comment by jjallaire** [comment]
Could you post a complete document that exhibits this error message? I tried pasting it into a hugo document and the generated SVG url rendered fine.

**Comment by pat-alt** [comment]
I managed to fix it in the end by changing the TeX from this `$\mathbf{H}(\hat{\mathbf{w}})$` to this `$\mathbf{H}({\mathbf{\hat{w}})$`. Since updating to version 0.9.21 earlier today, I cannot reproduce the error anymore so will close with this comment. But [this issue](https://github.com/quarto-dev/quarto-cli/issues/346#issue-1141262578) still occurs.

Thanks for your quick feedback!
