### ISSUE TITLE
Can you insert a pdf into a quarto document?

### ISSUE THREAD

**Issue by PublicHealthDataGeek** [quarto-dev/quarto-cli#3447]
Building on this previous question about pdf in quarto books #1270, can you insert a pdf into a quarto document - for example as you can in latex? https://stackoverflow.com/questions/2739159/inserting-a-pdf-file-in-latex

_Originally posted by @PublicHealthDataGeek in https://github.com/quarto-dev/quarto-cli/issues/1270#issuecomment-1326643660_
      
Many thanks

**Comment by cscheid** [comment]
No, not directly (because we target more than just PDF). If you know you're generating a PDF document through LaTeX, you can use the solution in stackoverflow
