### ISSUE TITLE
Unable to Push to Github for continuous deployment to Netlify

### ISSUE THREAD

**Issue by cgoo4** [quarto-dev/quarto-cli#3450]
### Bug description

Hi - I'm getting the error below when attempting to push my [Quarto](https://www.quantumjitter.com/) site to Github for continuous deployment using the [Github Action](https://quarto.org/docs/publishing/netlify.html#github-action) approach. `publish.yml` is set up per [this doc](https://quarto.org/docs/publishing/netlify.html#publish-action).

> To https://github.com/cgoo4/quantumjitter.git
>  ! [remote rejected] HEAD -> main (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/publish.yml` without `workflow` scope)
> error: failed to push some refs to 'https://github.com/cgoo4/quantumjitter.git'

I've instead used the [publish-from-git-provider](https://quarto.org/docs/publishing/netlify.html#publish-from-git-provider) approach which is working fine.

RStudio: Version 2022.12.0-daily+295 (2022.12.0-daily+295)
macOS Monterey version 12.6

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mcanouil** [comment]
Apparently your CI branch is modifying the workflow and trying to push the modified workflow back to the repository branch.

**Comment by cgoo4** [comment]
Thanks for checking. I deployed successfully with the publish-from-git-provider approach, so will close if it can't be recreated.
