### ISSUE TITLE
Missing space in quarto preview --help output

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-cli#3452]
In `quarto preview --help` output, the following line needs a space:

> Automatically reloads the browser *wheninput* files or document resources 

* "wheninput" -> "when input"

Tested in quarto version 1.3.26:

![image](https://user-images.githubusercontent.com/19754711/203885640-6e68cee6-a90b-40ae-98d8-2864c8af966b.png)

**Comment by cscheid** [comment]
Can you open a pull request? Thanks.

**Comment by jooyoungseo** [comment]
@cscheid I was trying to do, but I wasn't able to `grep` that string. Please give me the pointer. :)

**Comment by jooyoungseo** [comment]
@cscheid -- Found it! No worries. I will close this shortly.
