### ISSUE TITLE
Presentation view does not update automatically.

### ISSUE THREAD

**Issue by piiskop** [quarto-dev/quarto-cli#3458]
### Bug description

This anomaly occurs in RStudio Server. i had created a QMD-file inside a subfolder that was inside a subfolder. Testing via Render was no problem. Suddenly rendering did not work anymore and instead of a rendered presentation a rendered webpage was displayed in Presentation view.

i created a test file and that was rendered fine. i even copied and pasted the content of the test file into the first-mentioned file and rendering did not work. In Jobs:

Watching files for changes

/presentation_files/libs/revealjs/dist/reset.css (404: Not Found)
/presentation_files/libs/revealjs/dist/reveal.css (404: Not Found)
/presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css (404: Not Found)

These files are all there, i mean in the subfolder of the subfolder.

Renaming the file made rendering work correctly however Presentation view would not show any changes inside the file afterward.

> RStudio Server
> 2022.02.2 Build 485

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.5 LTS
> Release:	20.04
> Codename:	focal

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report. We will need a full git repo with the directory structure to be able to reproduce your issue.

**Comment by allenmanning** [comment]
Expiring this issue for now, let's re-open if a reproducible case is available.
