### ISSUE TITLE
Quarto does not respect my markdown extension

### ISSUE THREAD

**Issue by ratnanil** [quarto-dev/quarto-cli#3461]
### Bug description

I have a qmd file as follows named `hard-line-breaks.qmd`:

```markdown
---
title: "Hard Line Breaks"
format: 
  html:
    md_extensions: +hard_line_breaks
---

these
words
should
be
on
seperate
lines
```

If I run `pandoc -f markdown+hard_line_breaks -t html hard-line-breaks.qmd` I get the following. Note how `+hard_line_breaks` includes a `<br>` after every word. So far so good. 

```html
<p>these<br />
words<br />
should<br />
be<br />
on<br />
seperate<br />
lines</p>
```

However, if I run `quarto render hard-line-breaks.qmd`, I get the following output (top and bottom truncated for brevity):

```html
<p>these words should be on seperate lines</p>
```

Am I doing something wrong? How can I successfully activate the extension [`hard_line_breaks`](https://pandoc.org/MANUAL.html#extension-hard_line_breaks)?

```
> quarto --version
1.2.269

> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
As with Pandoc, you should be able to use `--from` or `-f` to control how markdown is read. For example:

`quarto preview test2.qmd --from markdown+hard_line_breaks`

**Comment by ratnanil** [comment]
Ok perfect, that works! Out of interest: Why doesn't adding `md_extensions: +hard_line_breaks` to the yaml header work?
