### ISSUE TITLE
Sidebar subtitle not rendering

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#3462]
### Bug description

In https://github.com/quarto-dev/quarto-cli/commit/0f56fc0aabe39778f5aab79c5ad4bef27307776c, the `subtitle` field was added as an option for sidebars. It also pops up as a valid option in RStudio:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/73663/204073770-15bcd9ad-2be9-4e7d-81f2-d7e9aea4ecf5.png">

However, with Quarto 1.2.269, the subtitle does not get generated when using this YAML:

**_quarto.yml**

```yaml
project:
  type: website

website:
  title: "Site title"
  
  sidebar:
    title: "Sidebar title"
    subtitle: "Here's a subtitle for the sidebar"
    contents:
      - text: "About"
      - text: "Blog"
```

It renders like this—the sidebar-specific title overrides the site title, as expected, but no subtitle appears:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/73663/204073855-eb7a3b36-02de-4f8b-b077-f10df83c1424.png">

It doesn't look like a theme issue—the HTML for the subtitle just doesn't get generated:

```html
<div class="pt-lg-2 mt-2 text-left sidebar-header">
  <div class="sidebar-title mb-0 py-0">
    <a href="http://localhost:3580/">Sidebar title</a> 
  </div>
</div>
<div class="mt-2 flex-shrink-0 align-items-center">
  <div class="sidebar-search">...</div>
</div>
<div class="sidebar-menu-container"> 
  <ul class="list-unstyled mt-1">
    <li class="sidebar-item">About</li>
    <li class="sidebar-item">Blog</li>
  </ul>
</div>
```

---

This is with Quarto v1.2.269 in RStudio 2022.07.2+576 (and also in VS Code) on macOS Monterey 12.6

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thanks for reporting this - we removed support for controlling the sidebar title and missed cleaning up the schema that provides autocompletion and reference documentation. I've cleaned that up!
