### ISSUE TITLE
bash aliases not recognized in quarto

### ISSUE THREAD

**Issue by elgabbas** [quarto-dev/quarto-cli#3465]
### Bug description

Hello,

I can not use/create bash aliases in quarto bash chunks. 

The following returns nothing [it should show the list of available aliases]
````
```{bash}
alias
```
````
Assigning new aliases returns this error: "`/usr/bin/bash: line 2: l: command not found`"
````
```{bash}
alias l='ls -CF'
l
```
````

The same commands work fine in the terminal windows.

****

Another related question:

Is it possible to allow commands in a single chunk effective outside of the chunk. I mean, if I changed the working directory in a specific chunk, this is only effective inside of this chunk; i.e., the working directory in the next chunk returns to the home directory. 

This same issue also implements to variables:

````
```{bash}
x=10
echo $x                  # this prints 10
```
````

````
```{bash}
echo $x                 # Nothing printed!
```
````

****

Thanks, Ahmed

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
These are not bugs, they are how bash works. You're expecting `bash` to be equivalent of `source`ing each file, but instead, what it does is:

- run the cell contents as if they're a script file that starts with `/bin/bash` (or equivalent)
- they run in a _separate process_.

> The same commands work fine in the terminal windows.

Running commands on a terminal windows is not equivalent to executing scripts in a subprocess. That also explains this issue of yours:

````
```{bash}
x=10
echo $x                  # this prints 10
```
```{bash}
echo $x                 # Nothing printed!
```
````

The bottom cell is executed in a _new process_, which does not see the environment variables set by the previous script.
