### ISSUE TITLE
Ability to show the TOC both in body and right simulataneously

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#3473]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3336

<div type='discussions-op-text'>

<sup>Originally posted by **AlFontal** November 15, 2022</sup>
As far as I know, it's possible to select a single location to show the Table of Contents, but while the dynamic TOC that always stays on the right is useful, sometimes I also want to show a full TOC just after the header in an article/blog post. 

Is there any mechanism to have it behave like that right now?</div>

**Comment by dragonstyle** [comment]
This seems like a good way to accomplish this. I think that supporting both left and right simultaneously is going to be a little annoying to implement because our grid system has some special accommodations for `toc: left` and I'm not completely sure how that grid will work with elements in both the left and right margins (it might be ok, but not sure).

**Comment by allenmanning** [comment]
It doesn’t seem that there is a need currently for both right and left just body and one of the sides.
Another approach could be `right-body` `left-body` that captures both locations as a single value.  

It isn't super clean, although we wouldn’t be implementing features that folks likely don’t want.

**Comment by dragonstyle** [comment]
That would definitely be a way to simplify things without creating weird scenarios like 

```markdown
toc-location:
  - left
  - right
```

I actually really like it- it feels like it keeps things simple.
