### ISSUE TITLE
Need to clarify configure file per OS platform

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-cli#3476]
In [CONTRIBUTING.md#L21](https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md?plain=1#L21), it says:

> # configure for your platform (./configure-macos.sh, ./configure-linux.sh, or ./configure-windows.cmd

However, there are only two configure files without platform name: "configure.cmd" and "configure.sh"

This needs clarification.

**Comment by cscheid** [comment]
Thank you, that's stale documentation. We now have ./configure.sh for POSIX platforms (mac and linux, really), and configure.cmd for windows.
