### ISSUE TITLE
cannot locate deno: issue with configure.cmd

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-cli#3477]
It seems like there are some issues in locating deno in `configure.cmd` script.

Tested on Windows 11 Education (Version 10.0.22621 Build 22621).

## Output

``` bash
configure.cmd
find: '/I': No such file or directory
find: 'deno.exe': No such file or directory
"Translated/recorded configuration settings from unix configuration script"
Bootstrapping Deno...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

 37 26.8M   37 10.1M    0     0  9953k      0  0:00:02  0:00:01  0:00:01 9953k
100 26.8M  100 26.8M    0     0  16.1M      0  0:00:01  0:00:01 --:--:-- 27.2M
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
.
Configuring Quarto from C:\test\quarto-cli\package\src
'"C:\test\quarto-cli\\package\dist\bin\tools\deno.exe"' is not recognized as an internal or external command,
operable program or batch file.
Configuration done
Revendoring quarto dependencies
Downloading Deno Stdlib
'C:\test\quarto-cli\\package\dist\bin\tools\deno.exe' is not recognized as an internal or external command,
operable program or batch file.
NOTE: To use quarto please use quarto-cmd (located in this folder) or add the following path to your PATH
C:\test\quarto-cli\\package\dist\bin
```

**Comment by cscheid** [comment]
It looks like we're attempting to `tar xf` a file that isn't a tar archive. I wonder if this should have been `unzip` instead. @cderv?

**Comment by dragonstyle** [comment]
FWIW I can't reproduce this on my Windows VM when testing locally, which makes we wonder whether there is something environmental specific to this configuration or this particular run (for example, my Deno download was 28.5MB rather than 26.8MB).

**Comment by cderv** [comment]
Same as @dragonstyle for me. Download is 28.5MB and everything install fine - I can't reproduce

@jooyoungseo I suppose you are running `configure.cmd` in CMD or in Powershell, not git bash ? 

Also is this with `main` branch of Quarto CLI or another PR branch ? 

As a note, I am seeing this in your log
```
find: '/I': No such file or directory
find: 'deno.exe': No such file or directory
```

I don't have it in mine, and I think this comes from 
https://github.com/quarto-dev/quarto-cli/blob/41ed7dac9c67db78064a4875244173e3bef4a61e/configure.cmd#L9-L10

So you could try running those command on their own in your CMD terminal window to see if they result correctly.

**Comment by cscheid** [comment]
> BTW The tar command on Windows at least, know how to decompress zip file.

Ah ok, thanks. I didn't know about that.

**Comment by cderv** [comment]
This was fixed as part of our work for running tests on CI with windows. https://github.com/quarto-dev/quarto-cli/commit/e505add089a9c234107164c3b8d65ace18419d76
