### ISSUE TITLE
[Mac M1] - quarto not recognized in terminal after installation

### ISSUE THREAD

**Issue by edoson** [quarto-dev/quarto-cli#3484]
### Bug description

I'm on Apple M1, downloaded the dmg file for mac and installed Quarto. Everything completed successfully. Quarto files are under Macintosh HD/Applications/quatro. Opened the terminal and typed `quarto --help` and i'm getting 

`zsh: command not found: quarto`

Yes, I'm using zshell. 

Ideas? 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
We attempt to add the path to the Quarto bin directory to the `.zshenv` file post installation. A couple of things you could check:

1) Have you restarted the terminal since installation?

2) Can you see whether the installation path (with a `bin` directory) is in the path declared in `.zshenv`?

Sorry you've run into this!

**Comment by edoson** [comment]
Hi, 

I don't have a .zshenv file in my home dir, just .zshrc.. Should I have one?

**Comment by mercush** [comment]
Hi, I was wondering if this was resolved? I seem to be running into the same issue. I've tried downloading Quatro using this [link](https://quarto.org/docs/get-started/) as well as by using the CLI command `brew install quatro --cask quatro`. 

After trying both of these, I still get the error `zsh: command not found: quatro`. 

I have `/Applications/quarto/bin:/Users/mauriciobarba/.cargo/bin` in my PATH variable, so I don't think this is a path issue. 

Do you have ideas here?

**Comment by mcanouil** [comment]
@mercush The issue was closed thus resolved.
If you are having issue, please open a GitHub Discussions.
Note that `quatro` is not `quarto`. I don't know what is the former, but the latter is for Quarto CLI.

**Comment by mercush** [comment]
Thanks, must've just been a typo!
