### ISSUE TITLE
`output-dir` parameter only used in top-level `_quarto.yml` file

### ISSUE THREAD

**Issue by anielsen001** [quarto-dev/quarto-cli#3487]
### Bug description

The `output-dir` yaml parameter is only being pulled from the top-level `_quarto.yml` file. My expectation was that I could set a sub-directory specific, or file specific `output-dir` parameter.

I created a [simple repository to demonstrate the issue](https://github.com/anielsen001/quarto_output_dir_issue) since it requires more than 1 file to demonstrate. (The README.md in the repo contains similar information as this report.)

To demonstrate the issue run:
```bash
quarto render sub1/sub1.qmd
```

The file `sub1/sub1.qmd` contains the yaml:
```yaml
---
title: sub topic 1
output-dir: ../docs
---
```

The expected result is the output in the `docs` directory but the output is created in the `sub1` directory. 

Running quarto yields the following terminal output
```
quarto render sub1/sub1.qmd 
pandoc 
  to: html
  output-file: sub1.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  output-dir: ../docs
  title: sub topic 1
  
Output created: sub1.html

```

Adding the `output-dir` parameter to `sub1/_metadata.yml` does not change the result.

I'm using:
- quarto version 1.1.141
- Ubuntu Linux 20.04, 5.15.0-53-generic # 59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- VSCode as IDE, but running quarto from terminal CLI

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Currently `output-dir` is a capability that is limited to quarto projects (we actually expect it to appear as a subkey of `project:`). As a result, it is expected that you may not set this per directory, per file etc, since it is project wide (and applies to all project output). 

We don't currently have a great way to use different output folders per file or folder, though I'm sure we have enhancement requests (perhaps related to `output-file`) as others have requested this.
