### ISSUE TITLE
bug: rendering document that ends with index.html causes quarto preview to serve wrong route

### ISSUE THREAD

**Issue by dpastoor** [quarto-dev/quarto-cli#349]
Given a document `foo-index.qmd` when editing the document, quarto preview attempts to reload the page, but 
tries to push the route `/foo-` instead of `/foo-index.html`

I'm guessing some logic around stripping `index.html` if its on the end of the URL designed for the root route?

**Comment by jjallaire** [comment]
I think it's here: https://github.com/quarto-dev/quarto-cli/blob/8ac64c5e50f3445170284b78eecd2bf48747dec5/src/resources/editor/devserver/devserver-core.html#L645

Related:  https://github.com/quarto-dev/quarto-cli/blob/0ba4ad1ae1e6831a68d79db9737966b6fb5de7f6/src/project/types/website/website-navigation.ts#L841

I think we want something more like this: https://github.com/quarto-dev/quarto-cli/blob/a65564caac6708545ca328f2c516b729baac8046/src/resources/projects/website/navigation/quarto-nav.js#L174
