### ISSUE TITLE
Difficulties re-rendering qmd documents containing only Julia code

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-cli#35]
After installing [IJulia](https://github.com/JuliaLang/IJulia.jl) and [JuliaCall](https://cran.r-project.org/web/packages/JuliaCall/index.html) on Windows 10, I'm able to get qmd files containing R, Python, and Julia running (though it seems to be running quite slowly). If I try to render a qmd only containing Julia code, a Julia daemon pops up and the file renders fine as long as I keep that open. If I close it, a new daemon doesn't start and I get this error:
![image](https://user-images.githubusercontent.com/6981612/121590028-6e567200-c9fd-11eb-8122-cb96df8bb5c3.png).

If I restart the quarto-cli shell and try to render it again, I get the same error. If I open Task Manager and close this Python application...

![image](https://user-images.githubusercontent.com/6981612/121590507-018fa780-c9fe-11eb-875e-9d112ff86770.png)

...I'm able to render Julia files again. I'm guessing it has something to do Julia being computed through a Jupyter kernel and even though the Julia daemon gets closed, the Python/Jupyter app is staying open and messing with stuff. 

**Steps to reproduce**

A small example file named `julia.qmd`:

    ---
    title: "Matplotlib Demo"
    author: "Norah Smith"
    date: "May 22nd, 2021"
    format: 
      html:
        code-fold: true
    ---
    ## Julia 
    
    ```{julia}    
    using Plots
    x = 1:10; y = rand(10, 2);
    plot(x, y)
    ```
I then ran `quarto render julia.qmd` and ran into the experience outlined above.

**Comment by jjallaire** [comment]
Good one! I think that your diagnosis is correct here. First off we need to make sure that console window is hidden! (that way no one can inadvertently close it). Then we obviously need to do a better job diagnosing the "dead" kernel daemon.

**Comment by pommevilla** [comment]
It looks like the latest Quarto release solved this problem. I was able to successfully render pure and mixed Julia documents, both individually and as a part of rendering a whole directory. I was not able to reproduce the errors above in neither the Windows command prompt nor in Git Bash. I'll go ahead and close this.
