### ISSUE TITLE
[Feature Request] Ggplot animations

### ISSUE THREAD

**Issue by halidaee** [quarto-dev/quarto-cli#350]
This may already be possible and I haven't troubleshooted properly. However, it would be great if there were support for animations between ggplot outputs that are rendered in SVG. 

For example, imagine the first slide has a ggplot with a single geom_point layer. The second side has a plot that is identical but adds a second layer consisting of geom_line. It would be nice to have only the additional layer, geom_line, fade in. 

Thanks for this amazing tool!

**Comment by jjallaire** [comment]
You could try a `fade` transition: https://quarto.org/docs/presentations/revealjs/advanced.html#slide-transitions

**Comment by jjallaire** [comment]
You could also use two absolutely positioned images (w/ the same position) and use a fade-out fade-in transition: https://quarto.org/docs/presentations/revealjs/advanced.html

**Comment by halidaee** [comment]
Alas, tried both approaches but it fades in the whole plot instead of just the additional elements. 

```

## Plot Slide {auto-animate='true'}

```{r echo=FALSE, dev.args = list(bg = 'transparent'), fig.retina=2, strip.white=TRUE, fig.asp=0.2,fig.align='left'}

iris %>%
  ggplot(aes(x=Sepal.Length, y=Sepal.Width)) + 
  geom_point()
```


```
## Plot Slide {auto-animate='true'}

```{r echo=FALSE, dev.args = list(bg = 'transparent'), fig.retina=2, strip.white=TRUE, fig.asp=0.2,fig.align='left'}

iris %>%
  ggplot(aes(x=Sepal.Length, y=Sepal.Width)) + 
  geom_point() +
  geom_line()
```

**Comment by jjallaire** [comment]
You could also use knitr plot animation: https://bookdown.org/yihui/rmarkdown-cookbook/animation.html

**Comment by halidaee** [comment]
Yeah. Was hoping to switch to native HTML SVG animation since it is smoother without cranking up fps, which I need in a few particular use case. No worries if this isn't feasible; I can just edit the raw output produced from Quatro.  

P.S. Just noticed the by-line. Hi from Mac '13 :)

**Comment by jjallaire** [comment]
Hi from Mac '87! and Mac '95 (@dragonstyle who is also full time on Quarto)
