### ISSUE TITLE
Asterisk in html output tables in get converted to markdown (ie. italics and bold marks)

### ISSUE THREAD

**Issue by fBedecarrats** [quarto-dev/quarto-cli#3509]
### Bug description

Hello, 
I use R code to produce regression summary tables that include asterisks (`*`, `**`, or `***`). For html outputs, some asterisks disappear and some italics and bold section appear. It seems to be a confusion in quarto between markdow and html in this case.

Please find below a reproducible example. Github doesn't allow for *.qmd files, so I had to rename the extension to *.txt:
[reprex_bug_quarto_asterisk_qmd.txt](https://github.com/quarto-dev/quarto-cli/files/10116808/reprex_bug_quarto_asterisk_qmd.txt)

My RStudio version is `2022.07.2 Build 576` (Spotted Wakerobin)
It is running on Windows 11 (I get the same issue on Ubuntu).

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
If you choose to use `asis`, then we'll interpret the output, well, _as is_. `*` and `**` indicate italics and bold, so this is working as intended. You'll need to have `stargazer` emit escaped asterisks.

**Comment by fBedecarrats** [comment]
I am sorry, but I do think that this is an issue with Quarto and not stargazer. I can modify the output to escape the asterisks, but this is still not picked up  by quarto. Example below: 
```{r}
#| output: asis
stargazer(my_model, type = "html") %>%
  str_replace_all("\\*", "\\\\*")
```
See updated quarto file below (as previously, with an extension renamed from `.qmd` to `.txt` to be able to load it to Github)
[reprex_bug_quarto_asterisk_escaped_backslashes_qmd.txt](https://github.com/quarto-dev/quarto-cli/files/10121629/reprex_bug_quarto_asterisk_escaped_backslashes_qmd.txt)
Please feel free to close again the issue, but in that case I would appreciate an indication on how asterisks should be escaped in html tables to be correctly interpreted by Quarto.

**Comment by cscheid** [comment]
The way to get an asterisk in Markdown is, in fact, to escape it with a backslash. This markdown

```
Here is an escaped asterisk: \*.
```

produces this output:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/285675/204833926-6347e016-a162-4a71-a429-ca679c98fbbf.png">

You can inspect the output generated by using the `keep-md: true` option in your front matter. I'm not the author of stargazer nor have I used it before, so I don't know how to tell you how to fix the output. But I'm fairly confident this isn't a quarto issue.

**Comment by fBedecarrats** [comment]
Thanks a lot for your answer! I'll try to figure out how to remplace `x` by `\x` with regex (I can't manage to do that for now).
