### ISSUE TITLE
Quarto rendering pdf, running xelatex 10 times

### ISSUE THREAD

**Issue by jpatteet** [quarto-dev/quarto-cli#3518]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3517

<div type='discussions-op-text'>

<sup>Originally posted by **jpatteet** November 30, 2022</sup>
I asked a question on stackoverflow and got an answer that resolved the problem. I am posting both here, maybe it is worth some modifications in quarto or not, let me know what you think.

**Question:**

I am wondering if it is possible to render quarto document faster.

When I render my document I get these messages in the "Background Jobs" window:

```
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
running xelatex - 3
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
```

All the way until:

```
running xelatex - 10
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
WARNING: maximum number of runs (9) reached
```

Output created:

Does anyone know what those 10 "running xelatex mean ? Is there a way to decrease this number of runs and what is the impact on the final rendering ?

**Answer:**

Quarto generates PDF via LaTeX by default. The LaTeX processors sometimes require multiple runs, as they step through the document sequentially and need a another run to, for example, update the table of contents after seeing another heading. Usually two runs are enough, but some LaTeX packages require more runs to get the correct output. Ten runs is quite unusual though, there might be something wrong elsewhere.

Quarto uses a heuristic to determine if it needs to run the LaTeX engine once more. Quarto also installs any missing LaTeX packages automatically. However, the tool latexmk is probably better in determining when to do additional calls to xelatex. You can use this tool with Quarto:

```
---
format:
  pdf:
    pdf-engine: latexmk
    pdf-engine-opt: -xelatex
---
```

If the document still requires 10 runs, then there might be an issue with a LaTeX package somewhere.

**Comment:**

I added pdf-engine: latexmk and pdf-engine-opt: -xelatex and now it does not even tell me running xelatex and renders the document very quickly </div>

**Comment by wuqui** [comment]
I had the same issue with a document yesterday, and I haven’t been able to figure out what caused this. XeTeX usually does 2 runs for me, for this project it kept doing 10 runs. I didn’t change the default configuration for the LaTeX engine at all.

**Comment by cderv** [comment]
Do one of you have the log file from the rendering ? This would help know probably what would trigger another run. 
We parse the log to know if a recompilation is needed so the information would be there. 

Thank you

**Comment by jcarpi** [comment]
I cannot share my log file, but I want to add that if I do not cite anything in my document body, the issue goes away. I suspect there's an output generated (another `.bib` file) and the built-in PDF engine is seeing that file generated as "new", and is re-running. I'll add that my log file does not contain any errors.

I've tried to avoid the issue by setting `latex-auto-mk: false`, and `pdf-engine: latexmk, pdf-engine-opt: -xelatex`, but this results in the build hanging forever. If `latex-auto-mk: true`, and `pdf-engine: latexmk, pdf-engine-opt: -xelatex`, then the first build is fine, and the second build fails on the bibliography. 

All of this is to say — I think there's a bad interaction between `biblatex` and the Quarto built-in PDF engine.

**Comment by jcarpi** [comment]
I've found a bit more about this. With `pdf-engine=latexmk` and `pdf-engine-opt=-xelatex`, the first complication is fine, as I say above. The second compilation fails on the bibliography, because the `.aux` file is completely deleted at the beginning of the rendering process, even when `latex-clean=false`.

The `latexmk` engine is parsing the `.aux` file for the citations defined in `.bbl`, etc. When it finds no citations in the (now empty) `.aux` file, it errors out.

**Comment by mcanouil** [comment]
Thank you for using Quarto and reporting an issue!

Unfortunately, this issue is now considered stale because it has been opened since 14 days without providing a "working" reproducible example to help us investigate.
If you are still facing the issue, please review the ["Bug Reports" guide](https://quarto.org/bug-reports.html) on how to provide a fully reproducible example as a self-contained Quarto document or a link to a Git repository.
Without a reproducible example, it is unlikely that the issue will be addressed and thus will be closed.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

_Remove `stale` / `needs-repro` labels or this will be closed in 14 days._

**Comment by cderv** [comment]
@jpatteet is this still happening for you ? Do you have a log file to share ? Thank you

**Comment by jpatteet** [comment]
@cderv I have not been rendering this file for a long time but it seems to work now with running latexmk twice.

Is the log file what appears in the "Background jobs" tab in rstudio ?
If yes, should I just copy paste it in a docx and drag/drop it here ?

**Comment by cderv** [comment]
The log file should be among your produced file **when** there is an issue with LaTeX running. If this is working ok, the log file won't be kept. 

And yes the background tab shows part of the log file **when** there is an error. Otherwise, it is just showing progress. 

> I  have not been rendering this file for a long time but it seems to work now with running latexmk twice.

We have made some general improvment so it is possible this is working ok now;

**Comment by blacksqr** [comment]
In case it is of future value to anyone else, today I encountered the problem of xelatex running ten times and then getting the warning of maximum number of runs reached.

It boiled down to the fact that I had copied text from a Google Docs document to a markdown text file, which contained an e with diaresis.  This took the form of two characters (U+0065 : LATIN SMALL LETTER E and U+0308 : COMBINING DIAERESIS), the latter of which is UTF-16 which xelatex doesn't like.

But the problem only occurred when the two-character combination occurred in a header line. In other words, a .qmd file containing only the line:

`# Charlotte Brontë`

rendered 10 times then quit, but a file containing only the line:

`Charlotte Brontë`

rendered without a problem.

Replacing the two-character combo by copying and pasting a proper single UTF-8 character (U+00EB) solved the problem for me.

**Comment by cderv** [comment]
@blacksqr it would be best to open a new issue with a full example to reproduce. Setting also `keep-tex: true` and sharing the tex content that causes this issue would help. Thanks

**Comment by blacksqr** [comment]
I'm not sure it's actually an issue, since strictly speaking xelatex doesn't accept UTF-16 characters. I posted in hopes of helping the next poor sap diagnose their problem.

**Comment by emilBeBri** [comment]
Thank you this helped me too! I think it is because I sometimes have several qmds in a book project, and I turn some of them 'off" to render only parts. But then if there are referencres to parts that are now turned off, without having:


    pdf-engine: latexmk
    pdf-engine-opt: -xelatex


IT tries to run xelatex 10 times to find it I think. This makes it go down to 2 times. Thank you so much for sharing.

**Comment by PKMitra** [comment]
Same problem. quarto not even making empty book pdf ! it is becoming a nightmare like markdown

**Comment by mcanouil** [comment]
@PKMitra unfortunately, there is nothing we can do to help you without any information.
Please open a new discussion (or eventually issue) and provide a small fully reproducible example as described when you open issues/discussions, and provide information regarding your environment such as the Quarto version.

**Comment by tezabhamidi** [comment]
> I've found a bit more about this. With `pdf-engine=latexmk` and `pdf-engine-opt=-xelatex`, the first complication is fine, as I say above. The second compilation fails on the bibliography, because the `.aux` file is completely deleted at the beginning of the rendering process, even when `latex-clean=false`.
> 
> The `latexmk` engine is parsing the `.aux` file for the citations defined in `-blx.bib`, etc. When it finds no citations in the (now empty) `.aux` file, it errors out.

Hi @jcarpi I was getting a similar variant of the issue and a response on Stackoverflow helped:

Reference: https://tex.stackexchange.com/questions/602962/error-with-biblatex-using-biber

"when the biber log stops like this, it often indicates a faulty cache. Run biber --cache on a terminal to get the location, delete the cache and then try again. biber will then unpack itself anew. – 
[Ulrike Fischer](https://tex.stackexchange.com/users/2388/ulrike-fischer)
 Commented Jun 28, 2021 at 11:34"

**Comment by JohsEnevoldsen** [comment]
> In case it is of future value to anyone else, today I encountered the problem of xelatex running ten times and then getting the warning of maximum number of runs reached.
> 
> It boiled down to the fact that I had copied text from a Google Docs document to a markdown text file, which contained an e with diaresis. This took the form of two characters (U+0065 : LATIN SMALL LETTER E and U+0308 : COMBINING DIAERESIS), the latter of which is UTF-16 which xelatex doesn't like.
> 
> But the problem only occurred when the two-character combination occurred in a header line. In other words, a .qmd file containing only the line:

Thanks. I had the same problem.
It was an "ε" in a figure caption. It rendered fine when I changed it to `$\\epsilon$`, and also if I put "ε" in the main text.
