### ISSUE TITLE
Figure caption missing for single figure

### ISSUE THREAD

**Issue by adauphin** [quarto-dev/quarto-cli#3525]
### Bug description

Hello,

I am trying to have a figure in a jupyter notebook (in python) with a figure caption that can be cross-referenced in the text.

Following the documentation [here](https://quarto.org/docs/authoring/figures.html), I put the follwing

```
::: {#fig-elephant}

![](hanno.png)

Famous Elephants
:::
```

However, this leads to the following figure caption `Figure 2: ?(caption)`. It does not work neither with the following code

```
::: {#fig-elephant}

![Famous Elephants](hanno.png)


:::
```

This bug is not present when one has two subfigures, as shown in the documentation.

```
::: {#fig-elephants layout-ncol=2}

![Surus](surus.png){#fig-surus}

![Hanno](hanno.png){#fig-hanno}

Famous Elephants
:::
```

Tested on Mac Os 12.0.1.

Thanks a lot for the help!

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I wasn't to reproduce this using a Jupyter Notebook when I tried what you described (the figure appeared correctly in my testing). Could you share a note book that reproduces this issue?

**Comment by adauphin** [comment]
Hello,

Thank you for your quick answer. Here is a link to a [Jupyter notebook](https://www.dropbox.com/s/ejgwt71nuo68hri/test.zip?dl=0) with the issue on my computer.

When executing this notebook, I have the following output

![test](https://user-images.githubusercontent.com/25903687/205011784-aa1cc188-77e4-47cb-94a5-23d6ff616026.png)


Details of my quarto version and my computer

```
quarto check

[✓] Checking Quarto installation......OK
      Version: 1.2.110
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: /Users/xxx/opt/anaconda3/bin/python
      Jupyter: 4.11.2
      Kernels: python3
```

**Comment by dragonstyle** [comment]
Just adding a newline after the image resolves the issue. See attached.

[Archive.zip](https://github.com/quarto-dev/quarto-cli/files/10141421/Archive.zip)

**Comment by adauphin** [comment]
Thanks a lot! 

It now works. Would it be possible to add this example to the documentation?
