### ISSUE TITLE
gfm improper handling of escapes in math environments

### ISSUE THREAD

**Issue by agerlach** [quarto-dev/quarto-cli#3526]
### Bug description

`\r` and `\n` in math environments get interpreted as carriage return and line feed when using gfm

OS: OSX and Debian 11
Quarto v 1.3.34

````md
---
format: gfm
---

$$\left{a\right}$$
$$\nabla$$
````

renders as

````md
$$\left{a
ight}$$

$$
abla$$
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I am not able to reproduce this. Here is what I observe:

```bash
$ cat test.qmd
---
format: gfm
---

$$\left{a\right}$$

$$\nabla$$%
```

```bash
$ quarto render test.qmd && cat test.md
pandoc
  to: >-
    commonmark+autolink_bare_uris+emoji+footnotes+gfm_auto_identifiers+pipe_tables+strikeout+task_lists+tex_math_dollars
  output-file: test.md
  standalone: true
  default-image-extension: png

Output created: test.md


$$\left{a\right}$$

$$\nabla$$
```

Is there anything else might be modifying the files?

**Comment by dragonstyle** [comment]
The version of Quarto pre-release you're using is pretty old (we're currently building 1.3.211) - perhaps try updating to the latest pre-release to see whether that addresses the issue?
