### ISSUE TITLE
Hyperlinks of equation numbers do not work in quarto presentation (revealjs)

### ISSUE THREAD

**Issue by ChoCho66** [quarto-dev/quarto-cli#3533]
### Bug description

For the quarto presentation (revealjs),
we will move to the first page if we click the hyperlinks of equation numbers.

It is OK for other hyperlinks, e.g. Theorem.

The following is an easy test `qmd` file.

```
---
title: "Untitled"
format: revealjs
---

## A

$$
\begin{aligned}
  f(X) = y.
\end{aligned}
$$ {#eq-EEE}

## B
  
See @eq-EEE.

::: {#thm-TTT}
Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.
:::

## C

See @thm-TTT.
```

My device:
- RStudio 2022.07.2 Build 576
- quarto version: 1.2.269

-
  ```
  > sessionInfo()
  R version 4.2.2 (2022-10-31 ucrt)
  Platform: x86_64-w64-mingw32/x64 (64-bit)
  Running under: Windows 10 x64 (build 19044)
  ```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by ChoCho66** [comment]
The hyperlinks of the code numbers also have this problem (link to title page).

![image](https://user-images.githubusercontent.com/72805700/208809423-b64bbf51-0e72-4f21-b966-633a26d13a81.png)

**Comment by cscheid** [comment]
We've noticed that the click handler that resolves the anchors from the ids to the titles only appears to work on `div` elements, and not `span`. We should fix or work around this somehow.

**Comment by cscheid** [comment]
Huh. From reading the relevant code in `revealjs`, [it clearly is only expecting to receive _slide elements_](https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L1990-L2007), and not arbitrary spans and divs. So the fact that this works on quarto so far is a lucky coincidence, caused by the specific way in which the DOM is built.

It's not about divs vs spans; it's about whether a direct parent of the resulting DOM is a `section` node.
