### ISSUE TITLE
Images are not copied into docs if the link adds optional parameter (e.g. image.jpg?2134)

### ISSUE THREAD

**Issue by eliocamp** [quarto-dev/quarto-cli#3543]
### Bug description

I'm creating a website with images that update daily. However, users sometimes don't get the latest image because their browser shows them a cached copy. I found that adding `?1234`  with a different number at each update can solve the issue. 

So I created an R variable called date with the current date and then inserted the image like this:

```
![](/images/plots/latest3.png?`r date`)
```

The problem is that quarto now is not copying latest3.png to the correct docs directory. My guess is that it's looking for a latest3.png?20221201 file to copy it, but since it doesn't exist, it doesn't do it. 

Reproducible example: https://github.com/eliocamp/asymsam-web/blob/4c9866320489526245c7ac5c47e804acade99e8a/monitoring/index.qmd

I'm running the latest version of quarto-cli on Debian GNU/Linux 9.13 (stretch). 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
This isn't a bug; the `r` syntax is meant to generate full markup. What you're attempting is probably achievable with a [lua filter](https://quarto.org/docs/extensions/lua-api.html#overview) instead.
