### ISSUE TITLE
Table cross-refs don't work when referring to tables in non-visible tabs (in tabset panel)

### ISSUE THREAD

**Issue by emmansh** [quarto-dev/quarto-cli#3557]
### Bug description

I want to [cross-reference to tables](https://quarto.org/docs/authoring/cross-references.html#tables) that are inside a tabset panel. It turns out that only if the table being referenced is _in the tab that is currently visible_, the cross-ref link would work. By contrast, if the cross-ref link refers to the table that is in the non-visible tab, then clicking the link doesn't do anything.

**`.qmd` file**

<pre>
---
title: "cross-refs to inside-tabset-panel-tables work only if those tables are already visible"
format: html
---

::: {.panel-tabset}

## iris
```{r}
#| label: tbl-iris
#| tbl-cap: Iris

knitr::kable(head(iris))
```

## mtcars
```{r}
#| label: tbl-mtcars
#| tbl-cap: Mtcars

knitr::kable(head(mtcars))
```

:::

---
## content; keep scrolling down
Here I want to refer to `mtcars` table from above: @tbl-mtcars
However, clicking on this cross-ref link would work only if _mtcars_ tab is already selected and visible up there.
Otherwise, if _iris_ tab is displayed above, then clicking on _mtcars_ cross-ref link here won't do anything.

</pre>

------

- Quarto version: `1.2.269`
- RStudio version: `2022.07.2+576 Spotted Wakerobin (desktop)`

<details>
  <summary>Session Info</summary>

  ``` r
  sessioninfo::session_info()
  #> - Session info ---------------------------------------------------------------
  #>  setting  value
  #>  version  R version 4.2.2 (2022-10-31 ucrt)
  #>  os       Windows 8.1 x64 (build 9600)
  #>  system   x86_64, mingw32
  #>  ui       RTerm
  #>  language (EN)
  #>  collate  English_United States.1252
  #>  ctype    English_United States.1252
  #>  tz       Asia/Jerusalem
  #>  date     2022-12-03
  #>  pandoc   2.19.2 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)
  #> 
  #> - Packages -------------------------------------------------------------------
  #>  package     * version date (UTC) lib source
  #>  cli           3.4.1   2022-09-23 [1] CRAN (R 4.2.1)
  #>  digest        0.6.30  2022-10-18 [1] CRAN (R 4.2.1)
  #>  evaluate      0.18    2022-11-07 [1] CRAN (R 4.2.2)
  #>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.2)
  #>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.2.2)
  #>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.1)
  #>  highr         0.9     2021-04-16 [1] CRAN (R 4.2.2)
  #>  htmltools     0.5.3   2022-07-18 [1] CRAN (R 4.2.1)
  #>  knitr         1.40    2022-08-24 [1] CRAN (R 4.2.1)
  #>  lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.1)
  #>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.1)
  #>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.2.1)
  #>  rlang         1.0.6   2022-09-24 [1] CRAN (R 4.2.1)
  #>  rmarkdown     2.18    2022-11-09 [1] CRAN (R 4.2.2)
  #>  rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.1)
  #>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.2)
  #>  stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.1)
  #>  stringr       1.4.1   2022-08-20 [1] CRAN (R 4.2.1)
  #>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.1)
  #>  xfun          0.34    2022-10-18 [1] CRAN (R 4.2.2)
  #>  yaml          2.3.6   2022-10-18 [1] CRAN (R 4.2.1)
  #> 
  #>  [1] C:/Program Files/R/my_packages
  #>  [2] C:/Program Files/R/R-4.2.2/library
  #> 
  #> ------------------------------------------------------------------------------
  ```

</details>

**Comment by cscheid** [comment]
Can you send me a fully self-contained .qmd that reproduces this issue? It's hard to know from a general description of this sort. Thanks!

**Comment by cscheid** [comment]
@emmansh I apologize, this is my fault. The source code you send had prose comments in it and content that looked like place-holders, and I didn't realize it was actually enough to trigger the bug!

The issue is not that the cross-ref doesn't work; they are rendered correctly. It's that _clicking_ on the icon doesn't navigate the page to the definition.

This is a fun one. I agree with you that ideally what you want to do should work, so I'm inclined to agree that it's a bug. But it's not trivial at all to fix, because the anchor you're looking to find is hidden (and so it doesn't have a location in the DOM). So there's no simple way for the web browser to know what else needs to happen on the page in order for that element to become visible.

**Comment by emmansh** [comment]
@cscheid  yup I understand the technical complexity underlying the problem (although by no means am I a front-end expert). Anyways, I can only say that as a Quarto _user_, I find _Tabset Panel_ an increadibly useful feature of Quarto. Mostly, I use it for showing alternative code chunks and their outputs (e.g., plots, tables). By incorportaing tabset panels in the page, I encourage my _audience_ to engage with the content. It is therefore critical, from my prespective, to be able to crossref to whatever content in whatever panel tab. 

In the same spirit, even a cross-ref to a specific tab _itself_ is a needed feature. Meaning, that once _clicking_, it takes you to the tabset panel location _and_ shows the desired tab.

Of course it's easy to request than do! But that's my take on the issue, as a user.

And many thanks for the outstanding work on this project! It's an amazing tool.

**Comment by gorkang** [comment]
This is an example file reproducing the issue. 

The first link works (because tabset ONE is active), but the second link does not work. If you click on tabset TWO, then the reverse happens (first link does not work, but second link does).

[BUG.zip](https://github.com/quarto-dev/quarto-cli/files/10538692/BUG.zip)

**Comment by xtimbeau** [comment]
Slightly related, whan using quarto beta 1.3.247 not only the lonks are not functionning but are not resolved. fig-cap is not recognize and displayed in any of the tabs. With quarto 1.2, tabs and fig-cap are displayed as expected.

**Comment by cscheid** [comment]
@xtimbeau can you share a document where that happens? Thank you.

**Comment by xtimbeau** [comment]
sure
Here is the qmd:
```
---
title: "tabsets"
cap-location: margin
html: true
---

content @fig-plot1 and @fig-plot2

::: panel-tabset
## plot1

```{r, echo=FALSE}
#| fig-cap: figure 1
#| label: fig-plot1
plot(mtcars$mpg)
```

## plot2

```{r, echo=FALSE}
#| fig-cap: figure 2
#| label: fig-plot2
plot(mtcars$cyl)
```
:::

```
With quarto 1.3.242., caps are not in the margin and cross-refs are unresolved. (both macos and windows)
With 1.3.250 it's working !

**Comment by victorleitejardim** [comment]
Hello,
I still have the same problem with the cross-refs links in hidden panels in quarto 1.3.340 macOS.
Both in a big project of my own and in the example by  @xtimbeau:

---

title: "tabsets"

cap-location: margin

html: true

---

content @fig-plot1 and @fig-plot2

::: panel-tabset
## plot1

```{r, echo=FALSE}
#| fig-cap: figure 1
#| label: fig-plot1

plot(mtcars$mpg)
```

## plot2

```{r, echo=FALSE}
#| fig-cap: figure 2
#| label: fig-plot2
plot(mtcars$cyl)
```
:::

**Comment by cscheid** [comment]
@victorleitejardim I can't reproduce on macOS, same quarto:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/285675/235956628-db98741f-13e4-45df-8533-fc177aec440d.png">

Are you sure you're running that specific version of quarto? (Note also that "html: true" isn't a valid option for us. It doesn't hurt, but it doesn't do anything. I'm not sure why you're using that.)

**Comment by victorleitejardim** [comment]
> 

Thank you for your answer. 

> Are you sure you're running that specific version of quarto?
Yes, I checked it with quarto::quarto_version()

> (Note also that "html: true" isn't a valid option for us. It doesn't hurt, but it doesn't do anything. I'm not sure why you're using that.)
I just kept it from the example previously posted by @xtimbeau, but don't actually use it in my personal project (in which I still have the same problem). 

Just to be clear: all cross-references are resolved with no problem, what doesn't work is that the links do not redirect the reader to figures or tables contained in a hidden tabset.  Does that work for you?

**Comment by cscheid** [comment]
> Just to be clear: all cross-references are resolved with no problem, what doesn't work is that the links do not redirect the reader to figures or tables contained in a hidden tabset. Does that work for you?

Oh, that's unfortunately not a bug we can solve easily. It's not a crossref issue: it's a limitation of tabby (the library we use for tabsets), and it's a duplicate of https://github.com/quarto-dev/quarto-cli/issues/3416
