### ISSUE TITLE
HTML book rendering and titles margin top in mobile view

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#3562]
### Bug description

I'm starting to create a book, and it's rendered properly on a desktop monitor.

![image](https://user-images.githubusercontent.com/30607/205498004-3b814deb-b45c-434b-bcf6-23dd4c77e34f.png)

If I open it in a smartphone browser, the top title is not visible at all, and is covered by the section title.

![image](https://user-images.githubusercontent.com/30607/205498056-2036d889-3bf8-4f2b-9610-fb2f01b395d7.png)

Here a sample URL: https://aborruso.github.io/asud-vademecum-monitoraggi/cultura-dato/licenza.html

Here the source repo: https://github.com/aborruso/asud-vademecum-monitoraggi

I think it's a bug, because I do not have customized any style.

I'm using quarto 1.3.21 in debian 11.

Thank you

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Absolutely - I just initiated a fresh pre-release build and it should be ready shortly! Thanks for reporting the issue!

**Comment by aborruso** [comment]
@dragonstyle only to say once again thank you. I tried it and it works!!
