### ISSUE TITLE
Table numbering inconsistent between html and pdf (incorrect in pdf)

### ISSUE THREAD

**Issue by rmcd1024** [quarto-dev/quarto-cli#3571]
### Bug description

Tables without a caption should not be numbered. In the following test document, the second table is captioned and is correctly numbered 1 with html output and incorrectly numbered 2 with pdf output. Rendered files are attached. Quarto version is 1.2.269. Linux version is Ubuntu 22.04.

````
---
title: test
format: pdf
##format: html
---

```{r, echo=FALSE, message=FALSE}
library(knitr )
opts_chunk$set(echo = FALSE
              ,message = FALSE)
library(gt)
library(tidyverse)
mt <- mtcars[1:4, 1:4]
```

```{r}
gt(mt)  ## does not display a number
```

```{r}
#| label: tbl-num
#| tbl-cap: 'here is a caption using chunk options'
mt %>%
    gt()  ## table number is 1 in html and 2 in pdf
```
Here is a cross-reference to  @tbl-num

```{r}
sessionInfo()
```
````

Rendered from command line; didn't use RStudio

[test_quarto.zip](https://github.com/quarto-dev/quarto-cli/files/10157208/test_quarto.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by rmcd1024** [comment]
In the intermediate tex file produced by `quarto`, changing to first table environment to `longtable*` fixes the problem. I presume that `gt` should in general use the starred form of the environments when there's no caption or cross-referencing label.

**Comment by cscheid** [comment]
`gt` doesn't know whether there'll be captions or not. We need to do the fixup ourselves in a Lua filter.

**Comment by Xinenomine** [comment]
Hello, 

I still have the exact same problem when using subtables… I have the right numbering a) and b) in html but a) and c) in pdf. 

The @tbl-connectors summarizes the different information developped in the previous section in a more concise way for reference. 

see @tbl-connectors1 and @tbl-connectors2

::: {#tbl-connectors layout-ncol=1}

 Pin # | Instrumentation  | Instr. # | Pin pairs | R ($\Omega$) |
 ----- | :--------------- | -------- | --------- | ------------ |
 1,2   | Heater HTR1      | 9        | 1-2       | 7.3          |
 3,4   | Heater HTR2      | 10       | 3-4       | 4.1          |

: Summary of the pins available and the associated instruments {#tbl-connectors1 tbl-colwidths="[20,35, 25, 25, 25]"}
 
 Pin # | Instrumentation  | Instr. # | Pin pairs | R ($\Omega$) |
 ----- | :--------------- | -------- | --------- | ------------ |
 1,4   | Bottom CLTS      | 12       | -         | -            |
 5,8   | CLTS top sample  | 6        | 5-6       | 111.9        |

: Summary of the pins available and the associated instruments {#tbl-connectors2 tbl-colwidths="[20,35, 25, 25, 25]"}


Summary of the pins available for each instrumentation connected to the connector TC1 (top) and TC2 (bottom)
:::

![image](https://github.com/user-attachments/assets/404b5ed9-edaa-4df5-b40f-bca7a95d7baf)

**Comment by mcanouil** [comment]
@Xinenomine This issue is more than a year old. Please open a new discussion or an issue if you really feel it's a bug after checking using the latest version of Quarto. Thank you.
