### ISSUE TITLE
Make command line robust against argument order

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#3581]
### Bug description

`quarto render --help` says

```
  Usage:   quarto render [input] [args...]
```

and `quarto render mwe.qmd --to docx` works as expected

```
pandoc 
  to: docx
  output-file: mwe.docx
  default-image-extension: png
  
metadata
  title: Minimal Working Example
  
Output created: mwe.docx
```

Unfortunately, `quarto render --to docx mwe.qmd` produces a document with duplicated content (see https://github.com/quarto-dev/quarto-cli/issues/3579).

Will be possible to include a warning in the command line output if the input file is not the first argument?

`quarto check` reports

```
[✓] Checking Quarto installation......OK
      Version: 1.3.34
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.10 (Conda)
      Path: /home/raniere/mambaforge/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /home/raniere/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.16

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
FWIW I think this may also be related to projects - if I use the command `quarto render --to docx test.qmd` in an empty directory, I receive the error `The specified directory ('.') is not a Quarto project`. I'm guessing that we're actually rendering the whole directory in the event that the `input` arg is 'omitted' (e.g. the order is such that we don't see it).

**Comment by cscheid** [comment]
Yup, I can repro this in html projects as well.

**Comment by cscheid** [comment]
@dragonstyle @jjallaire What do you think about adding the following heuristic to our command line parsing?

Heuristic: If input is `null` but first pandoc argument looks like an input file (ie, it ends with `.qmd` or `.ipynb`), assign first pandoc argument to `input` instead.

**Comment by cscheid** [comment]
We now issue the following warning if we suspect a bad parameter order:

```
$ quarto render --to html issue-3579.qmd
WARNING: `quarto render` invoked with no input file specified (the parameter order matters). Quarto will render the current directory by default.
Did you mean to run `quarto render issue-3579.qmd --to html`?
Use `quarto render --help` for more information.
```
