### ISSUE TITLE
`_quarto.yml`'s schema

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#359]
I think we can use [vscode-yaml](https://github.com/redhat-developer/vscode-yaml) or something similar to do auto-completion based on the schema when editing yaml files.
If the schema of `_quarto.yml` is provided, it would be great because it would save me the trouble of editing the file while staring at the reference.

https://www.schemastore.org/json/

**Comment by jjallaire** [comment]
We do in fact have a JSON schema for `_quarto.yml`. We currently use it within RStudio to do completion and we are currently working on adding this to our VSCode extension.

**Comment by jjallaire** [comment]
The latest release of the Quarto VS Code extension has completion and diagnostics for `_quarto.yml` (as well as document and cell option YAML): https://marketplace.visualstudio.com/items?itemName=quarto.quarto&ssr=false#overview

**Comment by eitsupi** [comment]
I tried a little quarto-vscode. This seems to be working very well!

**Comment by cscheid** [comment]
@eitsupi I'm going to assume this is ok to close. If you need an actual spelled-out JSON schema for that file (we have reasons to use a slight variant), please comment on this and I should be able to come up with a way to extract it for you.
