### ISSUE TITLE
Notes on making a quarto-render Github Action

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-cli#36]
I took a stab at making a Github action that renders the contents of a repo. I'm definitely no actions expert, but I tested rendering R documents and Python documents  `windows-latest` and `ubuntu-latest`. Short story: R was fine, but I ran into issue with Python because of the same Jupyter error I was seeing earlier last week. See the example workflows [here](https://github.com/pommevilla/quarto-action-tests/tree/main/.github/workflows).

Once the action is made, if the user wants to use it, they will have to supply a list of packages that they're using in their documents so that Quarto can actually render them. Python makes that easy with `pip freeze > requirements.txt`, and we can use `Renv` lockfiles to handle that for R. I haven't done much work with Julia, but it looks like we can do [something similar](https://discourse.julialang.org/t/install-a-packages-from-a-list/30920) ([also here](https://discourse.julialang.org/t/installing-packages-from-a-list/20450)). 

There may be some errors in installing packages depending on what OS the user is writing on. For instance, I wrote [these examples](https://github.com/pommevilla/quarto-action-tests) on a Windows machine. When I went to test on `ubuntu-latest`, it ran into an error because `pywin32` and `pywinpty` are Windows-only packages and won't install on Ubuntu. We can get around this either by structuring the requirements [like this](https://github.com/pommevilla/quarto-action-tests/tree/main/requirements) and calling the `pip install` command accordingly or by just parsing requirement files for platform-specific packages.

There will also probably be errors if the packages that the person is using is not found on CRAN, PyPI, or whatever the Julia equivalent is.

Rendering R Markdown documents seems to work fine.  Here is an [example workflow](https://github.com/pommevilla/quarto-action-tests/blob/main/.github/workflows/min-r.yml) I wrote that installs the latest Quarto-CLI (hardcoded for now), restores the R packages used via `Renv`, and renders the RMarkdown file. Just a note that sometimes this Install packages step took a long time for the R case, sometimes upwards of 10 minutes. There's also an example step at the bottom that pushes the new renders to the repo. 

I only tested R on Ubuntu because setting up Quarto through Github Actions was...challenging. I originally tried to do silent install via `msiexec`, but I wasn't able to get the options I found via Orca to work. I eventually ended up using Christophe's [scoop bucket](https://github.com/cderv/r-bucket) to get it to work on `windows-latest`, but then `scoop` wasn't persisting between steps, so I had to make everything into one big step and it kind of sucks. This is my first time writing actions, though, so I'm probably forgetting something. 

Quarto's having problems rendering Python, though, and it's the same error I was experiencing with running `quarto` commands on Windows outside of the symbolic link that the development version of `quarto-cli` sets up - `quarto` is unable to start up a Jupyter kernel, producing this error:

![image](https://user-images.githubusercontent.com/6981612/121795485-0d829180-cbd7-11eb-96ce-fad3e9c89a39.png)

I reproduced this problem on [Linux ](https://github.com/pommevilla/quarto-action-tests/blob/main/.github/workflows/min-linux-python.yml) and [Windows](https://github.com/pommevilla/quarto-action-tests/blob/main/.github/workflows/min-windows-python.yml) (I had to make it all one big step in the Windows workflow because `scoop` wasn't persisting between steps for some reason).

I remember that this error has to do with Quarto starting a Jupyter daemon in the background - I just wanted to share this issue so everyone's aware of it.

**Comment by pommevilla** [comment]
# Update

## Short story: 

After the CLI update, most everything seems to be working for `quarto render` through workflows. You can see it The workflow is here: [quarto-render.yml](https://github.com/pommevilla/quarto-action-tests/blob/main/.github/workflows/quarto-render.yml).

## Details

After the recent quarto-cli update, I was able to get an action up and running that `quarto renders` a directory successfully. The workflow is here: [quarto-render.yml](https://github.com/pommevilla/quarto-action-tests/blob/main/.github/workflows/quarto-render.yml). The workflow performs the steps described [here](https://github.com/pommevilla/quarto-action-tests#readme), as well as a `quarto env` and `quarto capabilities` call.  You can see the output of the most recent runs of this workflow [here](https://github.com/pommevilla/quarto-action-tests/actions/workflows/quarto-render.yml), and a small example site built with it [here](https://pommevilla.github.io/quarto-action-tests/).

Additionally, `quarto render` is called with `--execute-debug` so we can debug the workflow output.

## Multiple OSs

I suggest just sticking to running the workflow on `ubuntu-latest`. As long as we parse the `requirements.txt` file for system specific packages (ie, `pywin`, `pywinpty`) that are known to crash a workflow when installing on another OS, I think this will be the best choice. This will also improve the user experience since they won't have to do the weird file structure I suggested above to accommodate different operating system quirks. 

For now, I'm just searching for any packages with `win` in them and installing the rest: 

https://github.com/pommevilla/quarto-action-tests/blob/db8cba1848d1c76699abc6ef45a7585d1ed23adf/.github/workflows/quarto-render.yml#L21-L24

We can build on this step by making an `ignore_reqs.txt` file containing the names of packages that break the installation and do  `grep -fv ignore_reqs.txt requirements.txt` .

## "Hidden" package dependencies

I had to install `reticulate` as part of the workflow setup since I couldn't figure out a nice way to throw it into the `renv` lockfile without using `library("reticulate")`, and this seems like a weird thing to ask users to do if they want to use the workflow. Apparently `renv` supports [supports working with Python](https://rstudio.github.io/renv/articles/python.html) - it looks handy, but I haven't had the chance to test it out. I'll do so later.

I got an error when trying to `render` a pure Python document with the minimal R install that comes with `ubuntu-latest` because `quarto` couldn't find `jsonlite` ([full workflow here](https://github.com/pommevilla/quarto-action-tests/runs/2815734493?check_suite_focus=true)):
![image](https://user-images.githubusercontent.com/6981612/121831586-6ad91a00-cc8d-11eb-8816-68de0ab45832.png)

I'll add a line in the workflow later to handle this for quarto users who don't use R. But this makes me think about `quarto` users - do we expect someone who is a pure Python user and has no interest in R to use Quarto for their document rendering? 

I'll continue testing the workflow out in the coming days. I'm happy to continue working on this so we can turn this into an official action, either by myself or with someone who has more experience making Actions.

**Comment by jjallaire** [comment]
This all looks great! Note that rendering a Python document will never have any R dependencies. I see in the screenshot above that it's rendering an `r_example.Rmd` -- my guess is that this is where the jsonlite dependency is coming from. Note that the same goes for reticulate, it shouldn't ever be needed unless you are executing Python code from within an Rmd.

It's really surprising that the whole `pywin` thing is even a problem -- you would think that pip would have figured out a way for users to automatically avoid this (e.g. marking packages as platform specific). Seems bound to frustrate users who try to collaborate across operating systems.

**Comment by pommevilla** [comment]
Ooh, right - in that screenshot above, I was calling `quarto render --execute-debug python_example.qmd` (which renders the whole directory) instead of `quarto render python_example.qmd --execute-debug` (which only renders `python_example.qmd`). Running this on my local machine now works as expected. 

What's weird is that when I run the [full workflow](https://github.com/pommevilla/quarto-action-tests/blob/main/.github/workflows/quarto-render.yml), everything completes fine, but when I run a [Python only workflow](https://github.com/pommevilla/quarto-action-tests/blob/main/.github/workflows/min-linux-python.yml), I get the following errors: 

![image](https://user-images.githubusercontent.com/6981612/121915129-8a595c80-ccf8-11eb-92ee-0f8766880c71.png)

I also tried `nbconvert` and got this error:

![image](https://user-images.githubusercontent.com/6981612/121915203-9f35f000-ccf8-11eb-8987-3e41ddb51d4c.png)

`pandoc` shows up in `quarto env`: 

![image](https://user-images.githubusercontent.com/6981612/121917510-ce4d6100-ccfa-11eb-961d-97f007fa39ed.png)


What's weird is that the only difference between the [fully functional workflow](https://github.com/pommevilla/quarto-action-tests/blob/main/.github/workflows/quarto-render.yml) and this [minimal python workflow](https://github.com/pommevilla/quarto-action-tests/blob/main/.github/workflows/min-linux-python.yml) is that I restored all the R packages in the full workflow. You can see the output of the latest run of the [full workflow here](https://github.com/pommevilla/quarto-action-tests/runs/2820938387?check_suite_focus=true) and of the [Python only workflow here](https://github.com/pommevilla/quarto-action-tests/runs/2820938206?check_suite_focus=true). (Note that the the `nbconvert` step doesn't show up as an error because I set `continue-on-error` to `true` in the Python-only workflow.) 

The `python` section of `quarto capabilities` looks exactly the same in both workflows...
![image](https://user-images.githubusercontent.com/6981612/121917971-3a2fc980-ccfb-11eb-9907-a10c0bacb3e5.png) (full workflow)
![image](https://user-images.githubusercontent.com/6981612/121918010-43b93180-ccfb-11eb-857d-92ddbd8381e2.png) (python only)

...and the `python` and `jupyter` sections of `quarto env` do, too:

![image](https://user-images.githubusercontent.com/6981612/121918383-9bf03380-ccfb-11eb-82df-a0a8dfbf6928.png) (full workflow)

![image](https://user-images.githubusercontent.com/6981612/121918448-a90d2280-ccfb-11eb-9bde-b9897595fc28.png)(Python-only workflow)

The differences in the line counts are due to additional `R` stuff found in the full workflow.

I'll continue to use the full workflow since it seems to be working so far, but I just wanted to point out this situation.

**Comment by jjallaire** [comment]
The difference is that for the python only workflow it's trying to create the daemon, whereas for the full workflow it's not (because it's a project render).

The idea behind the daemon is to make iterative rendering faster in an interactive session. We specifically avoid using the daemon if there is no `tty` (interactive terminal). So for example in a cron job or other headless server environment we wouldn't create it). For whatever reason GH actions must be creating a "fake" interactive terminal so we are creating the daemon anyway. 

You can get this to work by adding the `--no-execute-daemon` flag to the command line. However, I wonder if we don't want to go one step further and actually detect that we are running in a GH action and do this proactively. Is there an environment variable you know of that we could use for this?

**Comment by cderv** [comment]
> I wonder if we don't want to go one step further and actually detect that we are running in a GH action and do this proactively. Is there an environment variable you know of that we could use for this?

Usually we detect we are in CI using `CI=true` (used by `testthat::skip_on_ci()`). There are also GHA specific environment variable if we want to detect more specific like `GITHUB_ACTIONS=true` 


GITHUB_ACTIONS | Always set to&nbsp;true&nbsp;when GitHub Actions is running the workflow. You can use this variable to differentiate when tests are being run locally or by GitHub Actions.
-- | --




From here: https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

**Comment by pommevilla** [comment]
Good find @cderv! I added an `if` statement to check for `GITHUB_ACTIONS == true` before calling `quarto render --no-execute-daemon` and the workflow was able to successfully render the Python document (workflow output [here](https://github.com/pommevilla/quarto-action-tests/runs/2822640214?check_suite_focus=true) if interested). 

I can add this check in the full workflow, but is this check necessary if we're always going to run this workflow through Github Actions? Is there any drawback/downside to just adding `--no-execute-daemon` to the `quarto render` call in the workflow?

**Comment by cderv** [comment]
The if inside the action directly won't be necessary. The env var will always be true inside GHA and I don't know a way to run an action locally for testing (is there ?). 
This is really useful for code itself to differentiate for run inside GHA or not (a `testthat::skip_on_gha()` for example. )

So inside the action workflow you can definitely always set `--no-execute-daemon` to be sure. However, this is a documentation thing in this case - This is like with chrome headless where flags needs to be set but you never remember which. Maybe Quarto could detect this as suggested and the user would not even need to know. 

I looked for TTY information for GHA runner but I did not find anything yet why there would be a fake interactive terminal. 🤔

**Comment by jjallaire** [comment]
Since we don't know of any circumstances under which it's a good idea to use the daemon under GH actions I made this change to disable it by default: https://github.com/quarto-dev/quarto-cli/commit/4a3109674d8f65d0e9580abdff19b1634bc7e1af. 

@cderv It could be that some GH actions use expect (https://en.wikipedia.org/wiki/Expect) type functionality to automatically answer prompts (which could be where a pseudo-terminal is introduced).

**Comment by pommevilla** [comment]
Ah, I see, I was misunderstanding where we would use such a conditional. Thanks for the explanation, @cderv + JJ. FWIW, it looks like [Act](https://github.com/nektos/act) lets you run actions locally.

I'll test the workflow with the next package release of Quarto CLI.

**Comment by jjallaire** [comment]
This commit will provide much better detection for all well known CI systems: https://github.com/quarto-dev/quarto-cli/commit/7c7fd67606325e42314b03cd4db3306bc97e6df5

**Comment by pommevilla** [comment]
Tested on both the full workflow and the Python-only workflow and everything worked fine! I'm closing this issue.
