### ISSUE TITLE
Error in page with multiple listings 

### ISSUE THREAD

**Issue by ivelasq** [quarto-dev/quarto-cli#366]
The ability to create blogs with Quarto is amazing! I am converting my website from blogdown and it has been very easy. Thank you.

I ran into errors when trying to make a page with multiple listings. I copied the following from the [guide](https://quarto.org/docs/websites/website-listings.html#multiple-listings):

```
---
title: Team Documents
listings: 
  - id: lab-reports
    content: "lab-reports/*.qmd"
    type: table
  - id: meeting-notes
    content: "meeting-notes/*.qmd"
    type:table
---

## Lab Reports

:::{#lab-reports}
:::

## Meeting Notes

:::{#meeting-notes}
:::
```

When rendering, I receive the error:

```
ERROR: YAMLError: can not read an implicit mapping pair; a colon is missed at line 9, column 15:
        type:table
                  ^
```

I added a space between `type:` and `table` and received the error:

```
ERROR: Validation of YAML front matter failed.
ERROR: In file test.qmd
(line 4, column 3 through line 9, column 15) Key listings has value - id: lab-reports
    content: "lab-reports/*.qmd"
    type: table
  - id: meeting-notes
    content: "meeting-notes/*.qmd"
    type: table but it must instead be `true` or `false`
 3: listings:
 4:   - id: lab-reports
      ~~~~~~~~~~~~~~~~~~
 5:     content: "lab-reports/*.qmd"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 6:     type: table
    ~~~~~~~~~~~~~~~~
 7:   - id: meeting-notes
    ~~~~~~~~~~~~~~~~~~~~~~
 8:     content: "meeting-notes/*.qmd"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 9:     type: table
    ~~~~~~~~~~~~~~~
10: ---
✖ The value - id: lab-reports
    content: "lab-reports/*.qmd"
    type: table
  - id: meeting-notes
    content: "meeting-notes/*.qmd"
    type: table is a object.
ℹ The error happened in location listings.

ERROR: Render failed due to invalid YAML.
```

I tried with `contents` instead of `content` and received a similar error:

```
ERROR: Validation of YAML front matter failed.
ERROR: In file test.qmd
(line 4, column 3 through line 9, column 15) Key listings has value - id: lab-reports
    contents: "lab-reports/*.qmd"
    type: table
  - id: meeting-notes
    contents: "meeting-notes/*.qmd"
    type: table but it must instead be `true` or `false`
 3: listings: 
 4:   - id: lab-reports
      ~~~~~~~~~~~~~~~~~~
 5:     contents: "lab-reports/*.qmd"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 6:     type: table
    ~~~~~~~~~~~~~~~~
 7:   - id: meeting-notes
    ~~~~~~~~~~~~~~~~~~~~~~
 8:     contents: "meeting-notes/*.qmd"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 9:     type: table
    ~~~~~~~~~~~~~~~
10: ---
✖ The value - id: lab-reports
    contents: "lab-reports/*.qmd"
    type: table
  - id: meeting-notes
    contents: "meeting-notes/*.qmd"
    type: table is a object.
ℹ The error happened in location listings.

ERROR: Render failed due to invalid YAML.
```

One last thing I tried was `listing` rather than `listings`. The page renders but does not show the .qmd items, and throws this error:

```
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Scanner error: while scanning a simple key at line 8, column 5 could not find expected ':' at line 9, column 1
```

I appreciate you taking a look at this issue. Thanks again!

**Comment by dragonstyle** [comment]
You are correct that the example doesn't work (really at all). There were a number of typos in the schema, which our validator was rightfully complaining about:

- It should be `type: table` not `type:table` (as you noted)
- It should be `listing` not `listings`
- It should be `contents` not `content`

I've updated the example to correct all of these issues and thank you for finding and reporting the issue!

Note that for the example to truly work, you'll want to be sure its in a website project + that those directories contain `qmd` files... It will render without error otherwise but the contents of the listing will be empty.

**Comment by dragonstyle** [comment]
Here is the correct scheme (updated on quarto.org now)


```markdown
---
title: Team Documents
listing: 
  - id: lab-reports
    contents: "lab-reports/*.qmd"
    type: table
  - id: meeting-notes
    contents: "meeting-notes/*.qmd"
    type: table
---

## Lab Reports

:::{#lab-reports}
:::

## Meeting Notes

:::{#meeting-notes}
:::
```

**Comment by ivelasq** [comment]
Thank you so much @dragonstyle! The scheme works well now. However, when running the full example, the level 2 headers do not show up on the page. Here is a screenshot (the contents from this example are empty, but I ran into the same issue on my blog where I do have content in the listings).

![get_hangouts_attachment_url](https://user-images.githubusercontent.com/12236152/155913285-36a0af43-b75f-4eda-b706-ad2b9eb25ccf.png)

**Comment by dragonstyle** [comment]
Hmmm... I'm not seeing that when I test locally using the example (I also double checked just using a plain 'blog' project that I modified to have multiple listings:

```
---
title: "listings2"
listing:
  - id: listing1
    contents: posts
    sort: "date desc"
    type: default
    categories: true
  - id: listing2
    contents: posts
    sort: "date asc"
    type: grid
    categories: true    
---

## Section 1

::: {#listing1}
:::

## Section 2

::: {#listing2}
:::
```

Which does seem to be rendering as I'd expect it to. Do you mind sharing the contents of the markdown file that contains the listings for me to take a look at?

**Comment by ivelasq** [comment]
Interestingly, I can run the listing2 example and it renders how we'd expect ([code](https://github.com/ivelasq/pipedream/blob/c6d0cec8f837946aa2a9cc012ede433e06680262/listing2.qmd), [page](https://github.com/ivelasq/pipedream/blob/c6d0cec8f837946aa2a9cc012ede433e06680262/listing2.qmd)). However, I don't see the headings for the team documents example ([code](https://github.com/ivelasq/pipedream/blob/c6d0cec8f837946aa2a9cc012ede433e06680262/team-docs.qmd), [page](https://deploy-preview-15--compassionate-benz-9a12b2.netlify.app/team-docs.html)) or the projects page I created ([code](https://github.com/ivelasq/pipedream/blob/c6d0cec8f837946aa2a9cc012ede433e06680262/team-docs.qmd), [page](https://github.com/ivelasq/pipedream/blob/c6d0cec8f837946aa2a9cc012ede433e06680262/project.qmd)).

In case it's helpful, I am using the `litera` theme. Thanks so much for taking a look!

**Comment by dragonstyle** [comment]
Thanks for sharing all that - I cloned your repo and am able to reproduce just what you're seeing. I'm working on tracking down the issue and will post here when I have a release that fixes the issue. Thank you for finding this!

**Comment by dragonstyle** [comment]
OK This release should fix the issue:

https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.48

The key was actually that the section names and the div `#ids` for the listings were identical (case insensitive). We generate id attributes for those headings based upon the name and in this case, the ids we generate were identical to the ids being used to target the listings. So we ended up writing the listing into the sections, overwriting the heading! 

I was able to better target the divs by id + mutate the output div ids to reduce the frequency of these types of id conflicts. This was a great bug to find, thank you!

**Comment by ivelasq** [comment]
Just tried it out and it is fixed!

I ran:
```
---
title: Team Documents
listing: 
  - id: lab-reports
    contents: "lab-reports/*.qmd"
    type: table
  - id: meeting-notes
    contents: "meeting-notes/*.qmd"
    type: table
---

## Lab Reports

:::{#lab-reports}
:::

## Meeting Notes

:::{#meeting-notes}
:::
```

And got:
<img width="1247" alt="Screen Shot 2022-02-28 at 4 26 23 PM" src="https://user-images.githubusercontent.com/12236152/156068947-f60b851f-2a94-4b8b-9dea-5714f049e018.png">

Thank you so much again. I think this issue is okay to close!
