### ISSUE TITLE
question about quarto filters

### ISSUE THREAD

**Issue by abergou** [quarto-dev/quarto-cli#368]
Hello,
I suspect the answer to this is `no`, but is it possible to add a filter to quarto that is run _before_ quarto processes a qmd file to replace executable code snippets?
Thanks!

**Comment by cderv** [comment]
Possibly a ` pre-render` project script option could help ? 
https://quarto.org/docs/projects/quarto-projects.html#project-scripts

**Comment by abergou** [comment]
Thanks! I think that'll work.
