### ISSUE TITLE
fa shortcode broken in navbar?

### ISSUE THREAD

**Issue by giabaio** [quarto-dev/quarto-cli#3686]
### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by giabaio** [comment]
I think there's a bug since one of the latest updates. I'm using a shortcode in my navbar --- my _quarto.yml file reads something like
```
...
      - text: '{{< fa brands r-project >}} Binder VM'
        href: SOME_URL_HERE
        rel: noreferrer noopener
        target: _blank 
```

This was working perfectly and producing the `R` symbol next to the text "Binder VM", with the underlying URL, which would open in a new page, as per `target` option. Since updating (I pulled the latest release from GitHub on my fork, so I'm now synced with the upstream: [55a0f79](https://github.com/giabaio/quarto-cli/commit/55a0f7978caf19ac1576dc945e61f814233be8a9)), I **think** there's a bug in how the shortcode gets parsed in the main html text and it appears in the source html as
```
<li class="nav-item">
    <a class="nav-link" href="[https://mybinder.org/v2/gh/StatisticsHealthEconomics/stat0019_binder/main?urlpath=rstudio](view-source:https://mybinder.org/v2/gh/StatisticsHealthEconomics/stat0019_binder/main?urlpath=rstudio)" rel="noreferrer noopener" target="_blank">
 <span class="menu-text">{{&lt;<i class="fa-brands fa-r-project" aria-hidden="true"></i> Binder VM</span></a>
  </li>
```
so there's a couple of curly brackets and a "less-than" symbol too many (`{{&lt;`), like in the screenshot below:
![image](https://user-images.githubusercontent.com/8723145/208078016-b9952704-c298-4730-97fd-c5aed6d8eec2.png)

Am I missing something obvious? Or has one of the very latest changes broken it?

**Comment by giabaio** [comment]
I think the breaking changes happen with [afca0c8](https://github.com/giabaio/quarto-cli/commit/afca0c8be9212acc6eae41ab9a7dc12faa5da415). Before that commit, the shortcode still works OK...

**Comment by cscheid** [comment]
Thank you for the precise bisection! I'll fix this right away.

**Comment by giabaio** [comment]
Thanks!
