### ISSUE TITLE
Quarto and R packages on Windows: different user lib depending on shell used

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#37]
I tested Quarto this morning on Windows with various shells and stumbled again on an old issue regarding using R in terminal on Windows. This caused me pain with Quarto not finding the R packages depending on where it is used. Best thing would be to show you but in short: R user's lib path is not the same depending on the shell used ! It seems crazy but I think it relies on the HOME folder not being the same either. 

With an R Session on RStudio and cmd, lib path will be inside `Documents`
```r
> Sys.getenv("R_LIBS_USER")
[1] "C:\\Users\\chris\\Documents/R/win-library/4.1"
> path.expand('~')
[1] "C:\\Users\\chris\\Documents"
```
but with Powershell or minGW, user lib path will be elsewhere, inside user directory.
```r
> Sys.getenv("R_LIBS_USER")
[1] "C:\\Users\\chris/R/win-library/4.1"
> path.expand('~')
[1] "C:\\Users\\chris"
```

As I am an R users using mainly RStudio, my packages are installed in `C:\\Users\\chris\\Documents/R/win-library/4.1`. This causes Quarto to no find out R packages on Powershell and MinGW (`quarto env` results). It would require maintaining two user libraries to render the same no matter which tool is used.

This is an issue I already encountered when using Makefile with R. This home directory behavior is painful on Windows. 

I am not sure which is the best solution, but I think this will clearly creates pain for users trying to use Quarto and R outside of RStudio. (Using Powershell or MinGW inside RStudio Terminal does not have this issue). 

I opened this issue as notes for our discussions. Maybe one of you encountered that already

**Comment by jjallaire** [comment]
I could be missing something, but I don't think that R having different default user libraries depending on what shell is used is in Quarto's domain to solve. This is super-unfortunate but short of actually redirecting the libraries (which seems very, very aggressive esp. for users knowledgeable enough to use Git Bash or PowerShell) there isn't really any way to overcome this at the Quarto level.

My guess is that RStudio fixes this automatically b/c the user has already clearly established a scope for their R session via RStudio (so redirecting libraries of child shells isn't particularly aggressive).

**Comment by cderv** [comment]
> I could be missing something, but I don't think that R having different default user libraries depending on what shell is used is in Quarto's domain to solve

I agree. I don't think this is directly in Quarto scope. If R user will be using Quarto mainly inside RStudio, then it will / may not be noticed. However, this may worth document (aim of this issue) because the behavior will definitely be different from terminal call inside RStudio Terminal, and another powershell terminal outside. This could cause unexpected behavior. it certainly did to me while testing in different shells - but I guess this is a specific use case.

If there are powershell / git bash R user, I guess they don't use RStudio or they set the R_LIBS_USERS env var (or HOME) the same so that they don't have different behavior depending on how they call R in which shell.

The aim for me was to document, I was not sure this was known. We'll see how often this come up among the Windows testers and users. Promoting the use of a project environment with renv is clearly a way to diminish this unfortunate behavior.
