### ISSUE TITLE
'_files' folder not inheriting from output filename set on cli

### ISSUE THREAD

**Issue by macroscian** [quarto-dev/quarto-cli#3703]
### Bug description

I'm running quarto 1.2.269 on the command line of centos 7.  My use-case is to use the same R script to generate multiple reports, and I like to avoid self_contained/embed-resources so users can easily access individual plots etc. 

```bash
quarto render '01_heatmaps.rmd'   -o 'binarised_v0.0.1-0-ga74c32d.html' -P assay:"binarised" 
```

In Rmarkdown the '*_files' would inherit the name of the output, so I'd get something like `binarised_v0.0.1-0-ga74c32d_files`, but in quarto I'm getting `01_heatmaps_files` - so if I attempt to iterate through a set of parametrised reports, I'll over-write the dependencies.  In [the documentation](https://quarto.org/docs/output-formats/html-basics.html#self-contained) it says that this is the 'default' behaviour, but I can't find any way of over-riding this default.  I don't think I can simply rename the folder, as the links then won't work?  Is there a way of reverting the behaviour so that the dependency folder inherits from the output name. Many thanks.

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Just realized that we have an open issue tracking this here: #2363. Closing in deference to that issue.
