### ISSUE TITLE
Hidden revealjs slides are still shown on the table of contents

### ISSUE THREAD

**Issue by KeAWang** [quarto-dev/quarto-cli#371]
When I set the .qmd header to be:
```
toc: true
```
revealjs slides that are hidden via:
```
## Slide Title {visibility="hidden"}
```
are still shown in the table of contents. Is there a way to hide them from the TOC?

**Comment by jjallaire** [comment]
Good catch! Fixed here: https://github.com/quarto-dev/quarto-cli/commit/7e9d75e0fcd4269f034e7e3001d89216108673dc
