### ISSUE TITLE
Weird `fig-cap` placement with `fig-subcap` with pdf output

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#3711]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3710

<div type='discussions-op-text'>

<sup>Originally posted by **agerlach** December 19, 2022</sup>
When using `fig-cap` with `fig-subcap` I am getting a weird layout for the main caption with pdf output. `fig-cap` is placed fine when `fig-subcap` is not used. Is this a bug, or am I doing something incorrectly?

````markdown
---
title: Hello World
jupyter: julia-1.8
---

```{julia}
#| echo: false
#| fig-cap: "My Plots"
#| fig-subcap: 
#|   - "Plot A"
#|   - "Plot B"
#| layout-ncol: 2

using Plots

plot(rand(25)) |> display
plot(rand(25)) |> display
```

```{julia}
#| echo: false
#| fig-cap: "My Plots 2"

plot(rand(25)) |> display
```
````
![Screen Shot 2022-12-19 at 9 14 11 AM](https://user-images.githubusercontent.com/599421/208445399-d1875fc9-7f08-4c18-b254-496c8dc38023.png)

![image](https://user-images.githubusercontent.com/599421/208445594-4418339d-1529-42d6-a971-9e0fc0bf08b2.png)

The resulting *.tex contains

```latex
\begin{figure}

\begin{minipage}[t]{0.50\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{subcap_files/figure-pdf/cell-2-output-1.pdf}

}

\caption{Plot A}

}

\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{subcap_files/figure-pdf/cell-2-output-2.pdf}

}

\caption{Plot B}

}

\end{minipage}%
\newline
\begin{minipage}[t]{0.50\linewidth}

{\centering 

My Plots

}

\end{minipage}%

\end{figure}
```

</div>

**Comment by cscheid** [comment]
Sorry for the delayed response. The problem here is that quarto 1.3 expects figures to have a label (having captions but no associated labels is not allowed in quarto 1.3).

Adding `label: fig-1` to your code cell produces this:

<img width="725" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/3f1ddca6-9f9f-4e6a-ad64-51e2162bdc27">

We might make our crossref system more robust against this in 1.4, but I'm not sure what the best solution here would be.

**Comment by cderv** [comment]
Passing by here looking for figure layout issue and I think this is fixed. 

Example from https://github.com/quarto-dev/quarto-cli/issues/3711#issue-1503126678 is now rendering to
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/88bd3380-1e48-44bb-a843-1cb0ec9ae16e)

Adding `label` in chunks to trigger cross reference gives 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/748e6814-2af5-49e8-9098-ac551387c21c)

So it seems all good.  

Also it seems that OP was looking to `label` indeed: https://github.com/quarto-dev/quarto-cli/discussions/3710#discussioncomment-4451008

Hence, I am closing this. Thanks for all your work on this crossref Carlos !
