### ISSUE TITLE
ERROR: Invalid Confluence parent URL

### ISSUE THREAD

**Issue by zachcp** [quarto-dev/quarto-cli#3720]
### Bug description

Hi Quarto-Dev,

I've been kicking the tires on the Confluence publishing feature but I have been unable to push to  Confluence due to an `Invalid Confluence parent URL` issue. Is there a regex matcher for Confluence URLs? If so, I'd be happy to try a few pages. 

```bash
quarto publish confluence
? Publish with account: › <elided>
? Space or Parent Page URL: ›  <elided>
ERROR: Invalid Confluence parent URL:  <elided>
```

In the above example, I am attempting to use as a parent is a simple page under my Personal Space.  I tried with and without spaces and also using the `share link` link version of the page. In all cases the URL fails. Notable, this is a private Atlassian instance so perhaps that is part of the issue?

Thanks,
zach cp

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by zachcp** [comment]
While the PR above addresses the initial issue with Parent URL handling, I then run into a Lua issue during rendering where the lua import paths are not finding the `overrides`. I'm fairly unfamiliar with Lua imports but will try to hunt this down.

```bash
Rendering for publish:

pandoc
  to: publish
  output-file: index.xml

metadata
  title: Testdir

Error running Lua:
[string "..."]:1338: module 'overrides' not found:
	no field package.preload['overrides']
	no file '/usr/local/share/lua/5.4/overrides.lua'
	no file '/usr/local/share/lua/5.4/overrides/init.lua'
	no file '/usr/local/lib/lua/5.4/overrides.lua'
	no file '/usr/local/lib/lua/5.4/overrides/init.lua'
	no file './overrides.lua'
	no file './overrides/init.lua'
	no file '/Users/zcharlop-powers/Documents/Projects/quarto-cli/src/resources//pandoc/datadir/overrides.lua'

       # seems like this file path is wrong and its adding an additional directory
	no file '../../Documents/Projects/quarto-cli/src/resources/extensions/quarto/confluence/publish.lua/overrides.lua'


	no file '/usr/local/lib/lua/5.4/overrides.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './overrides.so'
stack traceback:
	[string "..."]:1338: in function 'require'
	...i/src/resources/extensions/quarto/confluence/publish.lua:6: in main chunk
```

**Comment by allenmanning** [comment]
It isn't quite ready yet for pre-release testing, but it should be out there soon.  Thanks for your PR and fix, I was able to make the fix and am now running into limitations with the Confluence REST API making CQL with personal space keys.

**Comment by allenmanning** [comment]
This should be working in the 1.3 pre-release.  https://quarto.org/docs/prerelease/1.3/confluence.html
