### ISSUE TITLE
Could not fetch resource site_libs/tabwid-1.1.2/tabwid.css

### ISSUE THREAD

**Issue by dmenne** [quarto-dev/quarto-cli#3734]
### Bug description

quarto 1.3.26, Windows, RStudio Desktop. Make sure you reset everything to see the warning, when run multiple times it does not show.

index.qmd (nothing else)

````

```{r}
library(flextable)
head(mtcars)[,1:6]  |>
  flextable() 
```

````

Background job output on build:

```

Rendering:
[1/1] index.qmd
[WARNING] Could not fetch resource site_libs/tabwid-1.1.2/tabwid.css

Watching files for changes
Browse at http://localhost:6698/
GET: /
  /site_libs/tabwid-1.1.2/tabwid.css (404: Not Found)

```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I can't repro this on [v1.3.231](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.3.231). Can you check if this was fixed for you? Thanks!

**Comment by dmenne** [comment]
No longer reproducible with current version. Closing.
