### ISSUE TITLE
tidy: true globally

### ISSUE THREAD

**Issue by benjaminschlegel** [quarto-dev/quarto-cli#3735]
### Bug description

````
---
title: "Minimal Working Example"
execute: 
  tidy: true
---

```{r}
#| eval: false

df_ches = read_csv("1999-2014_CHES.csv") %>% 
  select(country, party, year, galtan) %>% 
  mutate(
    galtan = recode(galtan, "center" = "5", "extreme tan"="10") %>% as.numeric()
  )
```
````

When I add it locally in the chunk with #| tidy: true, it works [as.numeric() on a new line], but not globally in the yaml header ][stays on the same line].

R Studio: 2022.12.0 Build 353 on Windows 11

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mcanouil** [comment]
Where did you see that ˋtidy` was an option in `execute`.

ˋtidy` is a knitr specific option and usually specific knitr options are specified as in the code below.

```yaml
knitr:
  opts_chunk:
    tidy: true
```

This should work, if not, then indeed it is a bug.

**Comment by benjaminschlegel** [comment]
Thanks that did it. I didn't know that some chunk options had to go into execute while others are in opts_chunk
