### ISSUE TITLE
QMD Rendering Fails  - Error: Is a directory (os error 21)

### ISSUE THREAD

**Issue by msummersgill** [quarto-dev/quarto-cli#3739]
### Bug description

I recently finished upgrading a server to Posit Workbench 2022.07.2 Build 576.pro12, which bundled Quarto 1.1.189. In case it's relevant, immediately prior, I upgraded the OS in place from Ubuntu 16.04 -> 20.04. When I attempt to test out the Quarto rendering functionality, I get an error. 

Steps in IDE are File -> New File -> Quarto Document -> Create (HTML, knitr engine), save as "test2.qmd". _(file attached as [test2.qmd.txt](https://github.com/quarto-dev/quarto-cli/files/10290707/test2.qmd.txt) since GitHub didn't allow the .qmd extension)_

![Quarto IDE](https://user-images.githubusercontent.com/19575728/209234135-ccf0fb91-955b-4439-83fa-6384699c8328.PNG)

When I test running quarto from a simple SSH terminal, I get similar results. I also tested using a standalone install of version 1.2.280 and got the same results.

![Quarto Error](https://user-images.githubusercontent.com/19575728/209234193-864a6eb2-2fa3-4e58-a822-97ec0db05959.PNG)

Full stack trace of the error is as follows:
```
ERROR: Is a directory (os error 21)
Error: Is a directory (os error 21)
at Object.opSync (deno:core/01_core.js:172:12)
at Object.readTextFileSync (deno:runtime/js/40_read_file.js:41:17)
at readTheme (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:43539:21)
at readHighlightingTheme (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:43502:26)
at resolveTextHighlightingLayer (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:60313:33)
at resolveThemeLayer (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:60378:31)
at resolveBootstrapScss (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:60262:55)
at boostrapExtras (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:63753:25)
at themeFormatExtras (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:64966:16)
at Object.formatExtras (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:64584:96)
```

Output of Quarto Check:

![Quarto Check](https://user-images.githubusercontent.com/19575728/209234404-2696b3a6-9c5e-4cb1-b16e-ab41a1ae38d4.png)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thank you for the report. Can you try the latest stable 1.2.280 version?

**Comment by msummersgill** [comment]
Sorry, perhaps I could have clarified better. I had tested with 1.2.280 previously and ran into the same error:
![image](https://user-images.githubusercontent.com/19575728/209573634-f33bdacc-3c61-4019-95d9-a4b37ae27402.png)

**Comment by cscheid** [comment]
Can you try running the command from the directory? `cd /home/matthew...; quarto render test2.qmd` instead of `quarto render /home/matthew...` ?

**Comment by msummersgill** [comment]
Same result: 
![image](https://user-images.githubusercontent.com/19575728/209586644-b8c9fc62-b88c-470d-94a0-56d57117de9d.png)

I can definitely say that something about this issue is clearly environment specific -- when I test on a vanilla Ubuntu 20.04 VM running in the windows subsystem for Linux environment, I don't have any issues. Unfortunately, the machine I have the issue on is a production server so I can't get away with blowing it away and starting with a fresh installation. 


![image](https://user-images.githubusercontent.com/19575728/209586814-7db3109b-9d4f-4f32-be10-5082d8549c64.png)
![image](https://user-images.githubusercontent.com/19575728/209586779-b673631e-3301-4efe-bbc6-4f80f05b39ac.png)
![image](https://user-images.githubusercontent.com/19575728/209586788-ee12a878-2a9b-4c3f-b4f0-6003b9e97b5e.png)

Are there any "usual suspect" type system dependencies or versioning issues that I could start looking into as a potential root causes? Is it possible this could be related to the relatively new R version that was only released at the end of October? Posit Workbench version released in December? Python version? etc?

One bread-crumb that makes me curious is that on the server with the error, if I create a new "Quarto Project" through the RStudio Workbench UI...
![image](https://user-images.githubusercontent.com/19575728/209587003-8c91d66d-d063-4843-b5ae-79a92f5f1ed7.png)

I can then create a .qmd document and it renders as expected, which would lead me to believe I have all the necessary components for a functional Quarto toolchain.
![image](https://user-images.githubusercontent.com/19575728/209587086-e2030b57-0716-469f-ba7b-0bc5e2369a6c.png)

**Comment by cscheid** [comment]
The error message you're seeing specifically is coming from quarto attempting to read a file and finding a directory instead. It's definitely a weird one.

**Comment by cscheid** [comment]
Sorry for the delay - could you try this with our latest 1.3 prerelease and, in case it fails, could you share the website or .qmd that causes the problem? Thanks.

**Comment by msummersgill** [comment]
File in question here is as follows: [test2.qmd.txt](https://github.com/quarto-dev/quarto-cli/files/10925700/test2.qmd.txt)

When I attempt to render with latest dev build (cloned just now) error message is the same as previous versions.

```
matthew14786@<servername>:~$ /home/matthew14786/quarto-cli/package/dist/bin/quarto


processing file: test2.qmd
  |..............                                                        |  20%
  ordinary text without R code

  |............................                                          |  40%
label: unnamed-chunk-1
  |..........................................                            |  60%
  ordinary text without R code

  |........................................................              |  80%
label: unnamed-chunk-2 (with options)
List of 1
 $ echo: logi FALSE

  |......................................................................| 100%
  ordinary text without R code


output file: test2.knit.md

ERROR: Is a directory (os error 21)

Error: Is a directory (os error 21)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:42:16)
    at readTheme (file:///home/matthew14786/quarto-cli/src/quarto-core/text-highlighting.ts:122:17)
    at readHighlightingTheme (file:///home/matthew14786/quarto-cli/src/quarto-core/text-highlighting.ts:66:22)
    at resolveTextHighlightingLayer (file:///home/matthew14786/quarto-cli/src/format/html/format-html-scss.ts:242:27)
    at resolveThemeLayer (file:///home/matthew14786/quarto-cli/src/format/html/format-html-scss.ts:380:29)
    at resolveBootstrapScss (file:///home/matthew14786/quarto-cli/src/format/html/format-html-scss.ts:140:53)
    at boostrapExtras (file:///home/matthew14786/quarto-cli/src/format/html/format-html-bootstrap.ts:192:23)
    at themeFormatExtras (file:///home/matthew14786/quarto-cli/src/format/html/format-html.ts:946:12)
    at Object.formatExtras (file:///home/matthew14786/quarto-cli/src/format/html/format-html.ts:145:11)
    at async runPandoc (file:///home/matthew14786/quarto-cli/src/command/render/pandoc.ts:336:10)

```

Here is output of `quarto check`:

```
matthew14786@<servername>:~$ /home/matthew14786/quarto-cli/package/dist/bin/quarto check
Check file:///home/matthew14786/quarto-cli/src/quarto.ts

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.0: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/matthew14786/quarto-cli/package/dist/bin

matthew14786@<servername>:~$ /home/matthew14786/quarto-cli/package/dist/bin/quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.0: OK
      Dart Sass version 1.55.0: OK

[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/matthew14786/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /opt/R/4.2.2/lib/R
      LibPaths:
        - /opt/R/4.2.2/lib/R/library
      knitr: 1.41
      rmarkdown: 2.18

[✓] Checking Knitr engine render......OK

```

**Comment by cscheid** [comment]
This is very strange. I can't reproduce it (we have hundreds of these files in our test suite running on OS X, Linux, and Windows), and there's nothing special going on in that .qmd. How did you install quarto?

**Comment by msummersgill** [comment]
> This is very strange. I can't reproduce it...

Yes, unfortunately - as mentioned previously, I can't even reproduce it myself on different machines running the same OS, or in different directories on the server in question.

> How did you install quarto?

Quarto 1.2.280 and dependencies were bundled and included as part of the Posit Workbench installation - specifically, 2022.12.0+353.pro20 Workbench (Elsbeth Geranium) for Ubuntu Bionic


> Is it possible that this file is in a website?

This file is in my home directory _(not sure if that might have some special significance)_, which dozens of subdirectories and 100+ completely unrelated files. Included in that mix of files are, among a hodgepodge of other types, files with extensions including `.qmd`,  `.Rmd`, `.ipynb`, `.html`, `.yml`, `.R`, `.py`, etc... I'm guessing it's possible the presence of another object in the directory is causing the engine to behave differently and interpret this file as a web site?

**_In fact, when I copy the file into it's own empty subdirectory, `/home/matthew14786` -> `home/matthew14786/New` it renders just fine._**

>In that case, could we get access to the full repository?

Unfortunately, the directory contains a couple hundred Gb of files, along with lots of sensitive things I wouldn't be able to share for security reasons. I have added a gist here: https://gist.github.com/msummersgill/60741f32dd81bd1809d5ab092ec56e26 that gives an idea of the contents, with some redactions where necessary and some pruning of directories that I assume aren't the problem to make this more manageable to skim though.  Are there any specific file types or "special" directory names quarto auto-detects that I can check for?

> would it be possible for you to edit src/quarto-core/text-highlighting.ts...

With the added `console.log...` output is as follows:

```
matthew14786@hprstudio01:~$ /home/matthew14786/quarto-cli/package/dist/bin/quarto render test2.qmd
Check file:///home/matthew14786/quarto-cli/src/quarto.ts

processing file: test2.qmd
  |..............                                                        |  20%
  ordinary text without R code

  |............................                                          |  40%
label: unnamed-chunk-1
  |..........................................                            |  60%
  ordinary text without R code

  |........................................................              |  80%
label: unnamed-chunk-2 (with options)
List of 1
 $ echo: logi FALSE

  |......................................................................| 100%
  ordinary text without R code


output file: test2.knit.md

{ resolvedTheme: "arrow", inputDir: ".", userThemePath: "arrow", exists: true }
ERROR: Is a directory (os error 21)

Error: Is a directory (os error 21)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:42:16)
    at readTheme (file:///home/matthew14786/quarto-cli/src/quarto-core/text-highlighting.ts:125:17)
    at readHighlightingTheme (file:///home/matthew14786/quarto-cli/src/quarto-core/text-highlighting.ts:69:22)
    at resolveTextHighlightingLayer (file:///home/matthew14786/quarto-cli/src/format/html/format-html-scss.ts:242:27)
    at resolveThemeLayer (file:///home/matthew14786/quarto-cli/src/format/html/format-html-scss.ts:380:29)
    at resolveBootstrapScss (file:///home/matthew14786/quarto-cli/src/format/html/format-html-scss.ts:140:53)
    at boostrapExtras (file:///home/matthew14786/quarto-cli/src/format/html/format-html-bootstrap.ts:192:23)
    at themeFormatExtras (file:///home/matthew14786/quarto-cli/src/format/html/format-html.ts:946:12)
    at Object.formatExtras (file:///home/matthew14786/quarto-cli/src/format/html/format-html.ts:145:11)
    at async runPandoc (file:///home/matthew14786/quarto-cli/src/command/render/pandoc.ts:336:10)


```

**Comment by cscheid** [comment]
I see `userThemePath: "arrow"`

and I see

```
drwxr-xr-x+  21 username domain users      4096 Mar  6  2021  arrow
```

in your gist. When you're setting a custom theme, that needs to point to a _file_, rather than a directory. I expect this to be the source of your problem (I don't understand why you wouldn't see this issue in other scenarios, but it certainly needs to point to a file, and not a directory).

In hindsight, I notice that `userThemePath`, (emphasis on _path_), is an unfortunate name. We should consider changing it. (cc @dragonstyle)

**Comment by cscheid** [comment]
> `userThemePath` is just a variable name

Oof, of course. Long day, sorry 😬

**Comment by msummersgill** [comment]
> I see `userThemePath: "arrow"`
> 
> 
> 
> and I see
> 
> 
> 
> ```
> 
> drwxr-xr-x+  21 username domain users      4096 Mar  6  2021  arrow
> 
> ```
> 
> 
> 
> in your gist. When you're setting a custom theme, that needs to point to a _file_, rather than a directory. I expect this to be the source of your problem (I don't understand why you wouldn't see this issue in other scenarios, but it certainly needs to point to a file, and not a directory).
> 
> 
> 
> In hindsight, I notice that `userThemePath`, (emphasis on _path_), is an unfortunate name. We should consider changing it. (cc @dragonstyle)

Ahh, figured I was hitting a weird corner case of some kind! If it makes you worry about `userThemePath` confusion less, I didn't read documentation and come away with a misunderstanding - that `arrow` directory is completely unrelated - just a local copy of the Apache Arrow repository.

Thanks for running this one down and fixing, love using quarto and seeing the ongoing progress!
