### ISSUE TITLE
Quarto code and options use terms `blacklist` and `whitelist`

### ISSUE THREAD

**Issue by datakid** [quarto-dev/quarto-cli#3741]
### Bug description

Quarto uses the terms whitelist and blacklist. 

https://github.com/quarto-dev/quarto-cli/blob/85c9e303ece91e77a404e04eeeb2bb4270aecfc7/src/resources/editor/devserver/devserver-core.html#L205

https://github.com/quarto-dev/quarto-cli/blob/5bfd77217530c7a79123e90e3ee840e5300d4d4f/src/vendor/cdn.skypack.dev/-/ansi_up%40v5.1.0-ifIRWFhqTFJbTEKi2tZH/dist%3Des2019%2Cmode%3Dimports/optimized/ansi_up.js#L55

https://github.com/quarto-dev/quarto-cli/blob/d16d9f13110e084ef3c5a4b0f9561a5eb5f3158f/src/resources/formats/html/bootstrap/dist/scss/vendor/_rfs.scss#L1

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Yes, these are very problematic terms. But they come from dependencies that we don't control, so we can't fix them.

**Comment by datakid** [comment]
For future reference, I see that the first two references are to `whitelist` in anso_up.js. An issue has been opened against their repo here: https://github.com/drudru/ansi_up/issues/71

The reference to `blacklist` is in Bootstrap, and is upstream to them in stylelint:
- Bootstrap removes language https://github.com/twbs/bootstrap/issues/31064
- Bootstrap PR: https://github.com/twbs/bootstrap/pull/31066
- stylelint removes language: https://github.com/stylelint/stylelint/releases/tag/13.7.0

**Comment by datakid** [comment]
Hi @cscheid I see that Bootstrap [has updated](https://github.com/twbs/bootstrap/pull/37788) to remove `blacklist` and that ansi_up removed `whitelist` in a [commit on Aug 15](https://github.com/drudru/ansi_up/commit/e16e2d90dee03c8876297f8f1ebf386270ad4e28). 

Is it possible for these changes to be imported to Quarto now? Thanks!

**Comment by dragonstyle** [comment]
We have updated our bootstrap dependency in Quarto 1.4 and it incorporates this change. Leaving open as I believe that we still have the issue with anso_up.js.

**Comment by datakid** [comment]
@dragonstyle thank you - is that because more testing is needed before using the latest version of `anso_up.js`?

**Comment by dragonstyle** [comment]
No I'm just not that familiar with our use of `ansi_up`. I will take a closer look soon.
