### ISSUE TITLE
When using the video shortcut with a YouTube video url

### ISSUE THREAD

**Issue by directknowledge** [quarto-dev/quarto-cli#3744]
when the video id contains two dashes next to each other: i.e. BbTyu8zE--w

This does not work:
{{< video https://www.youtube.com/embed/BbTyu8zE--w  >}}

But this does:
{{< video https://www.youtube.com/embed/BbTyu8zE\-\-w  >}}

Just FYI

**Comment by cscheid** [comment]
This is indeed unfortunate. The issue is that Pandoc recognizes `--` as an en-dash and handles it differently. We probably need to tighten up our parsing of shortcode handlers more generally. This is good evidence that we probably want an intermediate `Shortcode` AST node that does the right thing.

**Comment by cscheid** [comment]
Specifically, this is the `--to native` output for `{{< video https://www.youtube.com/embed/BbTyu8zE--w >}}`:

```
[ Para
    [ Str "{{<"
    , Space
    , Str "video"
    , Space
    , Str "https://www.youtube.com/embed/BbTyu8zE\8211w"
    , Space
    , Str ">}}"
    ]
]
```

Pandoc is replacing `--` with the unicode code point `\8211`, "courtesy" of the [`smart` typography extension](https://pandoc.org/MANUAL.html#extension-smart).

**Comment by directknowledge** [comment]
Thank you.

**Comment by mcanouil** [comment]
FYI, #3681 which requires to fix a bug or update the documentation about valid YouRube URL.

**Comment by mcanouil** [comment]
While making https://github.com/quarto-dev/quarto-cli/pull/3824 I noticed the following shortcode does not work in 1.3.77

```markdown
---
format: html
---

{{< video https://players.brightcove.net/1460825906/default_default/index.html?videoId=5988531335001" >}}

```

```bash
> quarto preview /Users/mcanouil/Projects/misc/quarto-playground/quarto-playground.qmd --no-browser --no-watch-inpu
ts
pandoc 
  to: html
  output-file: quarto-playground.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  
No video source specified for video shortcode
```

Far as I can tell, it should work.

https://github.com/quarto-dev/quarto-cli/blob/1d97a285830eae785b08eba2a15c1422dac96d0a/src/resources/extensions/quarto/video/video.lua#L237-L266

**Comment by cscheid** [comment]
I know what's happening. Our shortcode parsing is recognizing `https://players.brightcove.net/1460825906/default_default/index.html?videoId=5988531335001` as a keyword argument. Its "key" is `https://players.brightcove.net/1460825906/default_default/index.html?videoId`, and the value is `5988531335001`. That's unfortunate, and I'm pretty sure it's a bug on the API of shortcode. I'll bring this up with the team and propose a fix (I believe we need `rawargs` on top of `args` and `kwargs`)

**Comment by cscheid** [comment]
(for my own records) https://github.com/quarto-dev/quarto/blob/60907deb986d06a7cf3402025d4c0596c573f19f/packages/editor/src/behaviors/smarty.ts#L4

**Comment by cscheid** [comment]
Ok, new problem. The AST contents of `{{< video *asterisk* _underline_ https://www.youtube.com/embed/BbTyu8zE--w >}}` are:

```
1: Str "{{<"
2: Space
3: Str "video"
4: Space
5: Emph [Str "asterisk"]
6: Space
7: Emph [Str "underline"]
8: Space
9: Str "https://www.youtube.com/embed/BbTyu8zE\8211w"
10: Space
11: Str ">}}"
```

Note what happens under "asterisk" and "underline".
