### ISSUE TITLE
behavior of `render` and `preview` of `revealjs` files that are listed in an index html file

### ISSUE THREAD

**Issue by juliantao** [quarto-dev/quarto-cli#375]
When a listed (child?) page is re-rendered, the listing (parent?) page is also re-rendered automatically.  It seems that this is necessary since the `data-listing-file-modified-sort` field needs to be updated on the parent page. 

However, I encountered a problem when I listed a number of `revealjs` files on an index html page. When I re-render or preview an updated `revealjs` file, the index page is also re-rendered, but into a `revealjs` format. Right now, I need to re-render the index page again to recover it back to a conventional `html` format.

**Comment by dragonstyle** [comment]
This is a great find- thank you for reporting it! It should be fixed now as of:

https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.57

**Comment by juliantao** [comment]
Thank you! I can confirm that it works as expected.
