### ISSUE TITLE
`title:` in {{< include _foobar.qmd >}} affects site search results

### ISSUE THREAD

**Issue by cgoo4** [quarto-dev/quarto-cli#3751]
### Bug description

When using a computational `{{< include /project/_toolbox.qmd >}}` at the very bottom of each of my projects e.g. [example](https://github.com/cgoo4/quantumjitter/blob/main/project/footnote/index.qmd), all the site search results then used the title of the `_toolbox.qmd` rather than the title in the project's `.qmd` which weakened the usefulness of the search.

The easy fix was to _not_ have a YAML `title:` in the included document, and the search now uses the title of the respective project.

I'm just raising this in case it's an unintended behaviour or worth noting in the [documentation](https://quarto.org/docs/authoring/includes.html#computations).

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
This is unintuitive, but the documentation covers it. Note that we warn about the behavior of `include`, from the page you linked:

> A very important thing to understand about includes is that they are equivalent to copying and pasting the text from the included file into the main file.
