### ISSUE TITLE
Broken layout when a list is the first child of .proof/.solution/.remark environment.

### ISSUE THREAD

**Issue by fulem** [quarto-dev/quarto-cli#3772]
### Bug description

Broken layout when a list is the first child of `.proof`/`.solution`/`.remark` environment.

Reproduce:
```
::: {.proof}

1. First part
2. Second part
:::

::: {.remark}

1. First part
2. Second part
:::

::: {.solution}

1. First part
2. Second part
:::
```
Html render is completely broken:
<img width="146" alt="image" src="https://user-images.githubusercontent.com/98791224/209713201-c6b6900f-003c-438e-9fc3-633c7422ba3f.png">

Pdf render is not that bad, but there is some issue with the position of the list:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/98791224/209713405-2923845d-8442-410b-ae2c-b883fa9c37d8.png">

More info:

- Quarto 1.2.280
- R studio 2022.12.0 Build 353
- Windows 11 Pro 22H2

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by fulem** [comment]
Possible alternative for the time being is to put something invisible as the first child:
```
::: {.proof}
$\phantom{some invisible text}$

1. First part
2. Second part
:::
```

However, this obviously produces a white gap. JS code can remove it after page loading, but is overkill.

**Comment by cscheid** [comment]
As another workaround, you can also wrap your numbered list in an unstyled div:

```
---
title: Xref Test
format: html
---

::: {.proof}

::: {}

1. First part
2. Second part

:::

:::
```
