### ISSUE TITLE
Citeproc Warning bibliography: value

### ISSUE THREAD

**Issue by davedoesmath** [quarto-dev/quarto-cli#3797]
.

**Comment by dragonstyle** [comment]
Does your document have the string `@directknowledge` in it somewhere? That warning is typically caused by a citation reference that isn't found in the bibliography...

**Comment by directknowledge** [comment]
Yes I found this in the json schema and the socail header on all pages, (e.g. my youtube handle and my contact information)
So I create a citation for it and place it in the _quarto.yml file and it stops makes this waring on every page. 

Now it places a reference section on everypage, inlcuding the homepage where it is not wanted. 

Thank You.

**Comment by dragonstyle** [comment]
I'm not sure what you mean by the JSON schema. You should be able to escape the `@` sign (which means 'citation' to Pandoc/Quarto) like so:

`\@dragonstyle`

**Comment by directknowledge** [comment]
Here is a link to learn about json scehma
https://json-schema.org

It is standard stuff for webpages.

Okay so I'll give a specific example, even though this problem effects every webpage.

Here is a url that you go check out
https://directknowledge.com/math/mathematical-induction/introduction-to-mathematical-induction/

When you view the source code and search for @directknowledge you get three instances:

The first two.
<script type="application/ld+json">
    {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "David A. Smith",
    "url": "https://directknowledge.com",
    "logo": "http://directknowledge.com/assets/directknowledge-logo.svg",
    "foundingDate": "2017",
    "founders": [
    {
    "@type": "Person",
    "name": "Dave A. Smith"
    },
    {
    "@type": "Person",
    "name": "David A. Smith"
    } ],
    "address": {
    "@type": "PostalAddress",
    "addressLocality": "Fort Worth",
    "addressRegion": "Texas",
    "addressCountry": "United States"
    },
    "contactPoint": {
    "@type": "ContactPoint",
    "contactType": "customer support",
    "email": "contact@directknowledge.com"
    },
    "sameAs": [
    "https://youtube.com/@directknowledge",
    "https://github.com/directknowledge/"
    ]
    }
</script>

These are for my email address and youtube handle which both contain @directknowledge but are not cititations. 


and the third instances of @directknwowledge is here: 

<a class="nav-link" href="https://youtube.com/@directknowledge">

whcih is in my website header, so again NOT a citation. 



When I do quarto render on this webpage it give this 3 times:

[WARNING] Citeproc: citation directknowledge not found
[WARNING] Citeproc: citation directknowledge not found
[WARNING] Citeproc: citation directknowledge not found


When I do quarto render for 150 web pages, it gives the warning 450 times.

How can I remove the warning?

Thank You.

**Comment by directknowledge** [comment]
OKay I did more testing (see above).

I use this in the _quarto.yml file

website:
  navbar:
    right:
      - href: https://youtube.com/@directknowledge
        icon: youtube
        aria-label: YouTube

To get the youtube channel link in my navbar. 

On pages that have a bibliography, for example,
https://directknowledge.com/math/mathematical-induction/introduction-to-mathematical-induction/

I receive the warning 
[WARNING] Citeproc: citation directknowledge not found
when I do quarto render.

Thank You.

**Comment by davedoesmath** [comment]
Yeah this is till not working, whenver I use @something in the meta and have and have a bib on the page, it warns of citation not found. Can we fix this bug?

**Comment by dragonstyle** [comment]
In my testing, using the escape that I suggested last week prevents the warning, since it ensures that Pandoc treats the `@` character as a literal. Is this not working for you?

For example:

```
project:
  type: website

website:
  title: "Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: https://youtube.com/\@directknowledge
        icon: youtube
        aria-label: YouTube      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: bib.bib
```

**Comment by davedoesmath** [comment]
Dear Quarto,

Thank you for your reply.  



1) This code leads to citation warning on every page but the link works:

> href: ***@***.***

Here is the link that quarto produces: 

<a class="nav-link" ***@***.***"><i class="bi bi-youtube" role="img" aria-label=“YouTube"></i></a>

 


2) This code DOES NOT give a citation warning on every page but the link DOES NOT works:

>    - href: ***@***.*** 

Here is the link that quarto produces: 

<a class="nav-link" ***@***.***"><i class="bi bi-youtube" role="img" aria-label="YouTube"></i></a>





3) Here are somethings I have noticed:


3a) I do not get citation warnings when using:

    html-math-method:
      method: mathjax
      url: ***@***.***/es5/tex-mml-chtml.js"  

Which also has a @ symbol in it. Strange?


3b) When I use either of these 
> - href: ***@***.***”
> - href: ***@***.***'


The links produced by quarto do not work.



3c) When I use 
> - href: ***@***.***”
> - href: ***@***.***'

I get citation warnings (on every page that has a bibliography).



I hope this helps us figure it out.

Have a great day.

Thank you.

**Comment by davedoesmath** [comment]
I replied from an email, and came here and saw the mess.

**Comment by davedoesmath** [comment]
Your suggestion does not work.

**Comment by dragonstyle** [comment]
Can you share the literal yaml / source code example (ideally something simple) that is causing the issue? When I tested the above example with the navbar element locally, I don't see a warning. The use of `\` to escape the `@` is the documented way that Pandoc handles character escaping, so I'll be surprised if it doesn't work (unless there are other things in play, which there may be depending upon exactly where you're using it).

**Comment by davedoesmath** [comment]
Here is a working example.
https://github.com/davedoesmath/testing-quarto-2

In particluar, you can see that if you run quarto render there are no citation errors but the link in the url is wrong:
line 133 in this file
https://github.com/davedoesmath/testing-quarto-2/blob/main/_site/posts/post-with-code/index.html
has this code:
<a class="nav-link" href="https://www.youtube.com/\@davedoesmath">
which is not ocrrect because of the \ symbol.

However, if you goto into the file 
https://github.com/davedoesmath/testing-quarto-2/blob/main/_quarto.yml

and change to 
href: https://www.youtube.com/\@davedoesmath
to 
href: https://www.youtube.com/@davedoesmath
then I get the citation warnings, bu tthe link is correct. 

Thank you for your time.

**Comment by dragonstyle** [comment]
Ok, I was able to reproduce this (I was missing the fact that YouTube would redirect from a URL with an extra slash to a URL with the correct slashes). It's a little tricky to fix, but I will try to get to it for this upcoming release...

**Comment by dragonstyle** [comment]
(Note to self - the underlying issue is that website metadata is making its way into the defaults files for formats).
