### ISSUE TITLE
Where do we ask questions about Quarto?

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#38]
I am very sorry if I missed this - but where is the best place to ask support-like questions about Quarto?  Is that here?  Or somewhere else?

We've very interested in Quarto for an R / Python book we are writing, but I couldn't immediately see how to execute code before knitr rendering, for each book chapter - a nice feature of Bookdown.

@stefanv  is my book co-author, and pointed me to Quarto.

**Comment by jjallaire** [comment]
Right here is a great place to ask!

One difference between Quarto and bookdown is that Quarto executes each chapter in a fresh R session, so hopefully you can get the behavior you want by just including the appropriate code in your setup chunk (or a `.First` hook in .Rprofile, see https://www.statmethods.net/interface/customizing.html)

Hopefully this does what you are looking for, if not we'll see if we can add a way to execute the sort of hooks you need.

**Comment by matthew-brett** [comment]
Thanks - that's helpful.   To give you an idea, our current Bookdown build has a pretty substantial startup file : https://github.com/resampling-stats/resampling-with/blob/master/source/_common.R .  It would be pretty inconvenient to have that as a startup chunk in every chapter, or to have all the defined functions loaded for all R sessions (book or not).

We've got used to using R functions inlined in the text as macros for various things - so we are defining many of these in the startup file.

Although we are using Bookdown, Quarto looks like a cleaner option, but we don't want to set you on the path of making it less clean :)

**Comment by jjallaire** [comment]
Okay, let me think about how I might do that generally for both knitr and jupyter. 

In the meantime, would it work to put this setup chunk in each chapter:

````
```{r setup, include=FALSE}
source("_common.R")
```
````

**Comment by matthew-brett** [comment]
:) - yes - thanks - we could surely get going like that ...
