### ISSUE TITLE
Version 1.3.75 breaks R

### ISSUE THREAD

**Issue by justanothergithubber** [quarto-dev/quarto-cli#3801]
### Bug description

In the latest version (1.3.75), the following line seems to look for `pagebreak.lua`,

https://github.com/quarto-dev/quarto-cli/blob/912a4962cd361fc092a7f52e720c13199fe39131/src/resources/rmd/execute.R#L187

but the filters seem to have been taken out in this [large commit](https://github.com/quarto-dev/quarto-cli/commit/56888bb94984fd93f16edb42dbe5564c6dc65eaa), with this line

https://github.com/quarto-dev/quarto-cli/blob/912a4962cd361fc092a7f52e720c13199fe39131/package/src/common/prepare-dist.ts#L153

The minimal reproduction example is simple: an empty file with only an `r` code block, or any inline `r` will do as well.

````qmd
```{r}
```
````

where upon trying to render I get errors:
```
Error running filter .../quarto-prerelease/current/share/filters/rmarkdown/pagebreak.lua:
cannot open .../quarto-prerelease/current/share/filters/rmarkdown/pagebreak.lua: No such file or directory
```

As above my `quarto` is 1.3.75 and I am on Windows.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
@justanothergithubber Thanks for catching it! It's a bit of a bummer that our CI tests didn't trigger this, but you're completely right, that filter should still be inlined and copied to the distributions. I'm going to fix this and fire off a new release in the next few minutes.
