### ISSUE TITLE
Change the title

### ISSUE THREAD

**Issue by directknowledge** [quarto-dev/quarto-cli#3803]
Hi,

The default for a webpage title seems to be 
<title>{{< meta website.title >}} - {{< meta title >}}</title>
For example, this page
https://quarto.org/docs/websites/
has the webpage title
<title>Quarto - Creating a Website</title>

How can I change it to:
<title>{{< meta title >}} - {{< meta website.title >}} </title>
so the (webpage) title would be 
Creating a Website - Quarto

I tried using the shortcodes
<title>{{< meta title >}} - {{< meta website.title >}} </title>
But the originally <title> tag is still in the page source. 

Thank You.

**Comment by mcanouil** [comment]
I believe what you are looking for is what is described in #1236, _i.e_, `pagetitle`.

**Comment by davedoesmath** [comment]
Yes, I can use pagetitle for each individual page. Thank You. 
That does help, but not as helpful as I like because this is not a good solution for hundreds of pages.
Thank You.

**Comment by mcanouil** [comment]
Still, because you don't provide an actual working example, it is hard to actually help.
