### ISSUE TITLE
SVGs fail in LaTeX output

### ISSUE THREAD

**Issue by kjohnsen** [quarto-dev/quarto-cli#3804]
I'm having an issue including just any SVG in LaTeX output---it complains about not having a bounding box, even with height and width defined. I'm using Quarto 1.2.280 and just barely upgraded TinyTex to v2022.12.12. I'm on Ubuntu 18.04 WSL on Windows 11.

`test.svg`:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
```

`test.qmd`:
```qmd
# hello there

![test SVG](test.svg)
```

Render, and for me it complains about the bounding box:
```sh
quarto render test.qmd --to pdf
```

```
LaTeX Error: Cannot determine size of graphic in test.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
```

_Originally posted by @kjohnsen in https://github.com/quarto-dev/quarto-cli/discussions/3283#discussioncomment-4551997_

**Comment by dragonstyle** [comment]
PDFs don't natively support SVG images. Starting in the Quarto 1.3 prerelease we will automatically convert SVG images for you, but if you're on an earlier version you should convert the images to another format like PDF.
