### ISSUE TITLE
Quarto cannot render mermaid or dot images to docx and pdf formats

### ISSUE THREAD

**Issue by Jiayou-Chao** [quarto-dev/quarto-cli#3809]
The `qmd` file cannot be rendered to `docx` or `pdf` files if it contains mermaid or dot images, although it works for `html` files. If I run
```
quarto preview test.qmd --to docx --no-browser --no-watch-inputs
```
on quarto 1.3.75, it pops up an error message:
```
ERROR: Internal error: temporarily disabled until deno 1.28.* gets puppeteer support
```
If I run it on quarto 1.2.269, it doesn't show or output anything but keeps running the command forever.

I tested this on both Windows 10 and 11.

A minimal reproducible for the `qmd` file can be:

<pre>
---
title: "test"
format: docx
---

## Quarto

```{mermaid}
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```
</pre>

Everything will work if the mermaid images are removed or the file is rendered to html. Upgrading deno doesn't help.

**Comment by cscheid** [comment]
Yes, unfortunately we're blocked on this by an upstream dependency, for the reason pointed out by the error message.

**Comment by alexkyllo** [comment]
I noticed that rendering Mermaid diagrams to PDF used to work and no longer does, for reasons mentioned above--I have another machine that still has Quarto 0.9.468 on it, and it does work on that one. I would like to install the latest version where this is still enabled--would you be able to help me pinpoint which version that is? Thank you.

**Comment by Antyos** [comment]
> I noticed that rendering Mermaid diagrams to PDF used to work and no longer does, for reasons mentioned above--I have another machine that still has Quarto 0.9.468 on it, and it does work on that one. I would like to install the latest version where this is still enabled--would you be able to help me pinpoint which version that is? Thank you.

I tried Quarto 0.9.468 and couldn't get it to render Mermaid until installing Chromium with
```bash
quarto tools install chromium
```

After doing that, it seems like even Quarto 1.2.269 is able to render Mermaid properly from a `.qmd` or even a `.ipynb`. 

Since I just learned of this program's existence today, I was confused at first that I had to wrap the codeblock in curly braces, i.e., `` ```mermaid `` as `` ```{mermaid}``. Also, Mermaid doesn't seem to render properly in quoted sections, but that may be another bug report.

**Comment by cscheid** [comment]
Puppeteer is now reenabled on quarto 1.3 prereleases.

**Comment by Jiayou-Chao** [comment]
> title: "test"
> format: docx
> ---
> 
> ## Quarto
> 
> ```{mermaid}
> flowchart LR
>   A[Hard edge] --> B(Round edge)
>   B --> C{Decision}
>   C --> D[Result one]
>   C --> E[Result two]
> ```

Hello,

After upgrading quarto to `1.3.290`, I still cannot use mermaid for pdf and docx documents. After I run `quarto render test.qmd --to docx` it opens my Chrome browser and does nothing else. If I close the browser, it pops up the following error message:

```
ERROR: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.

Error: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.
    at externalRequest (file:///C:/Users/chaoj/AppData/Local/Programs/Quarto/bin/quarto.js:55893:15)    
    at async New (file:///C:/Users/chaoj/AppData/Local/Programs/Quarto/bin/quarto.js:55931:21)
    at async defaultTarget (file:///C:/Users/chaoj/AppData/Local/Programs/Quarto/bin/quarto.js:55967:26)
    at async Chrome._fetchDebuggerURL (file:///C:/Users/chaoj/AppData/Local/Programs/Quarto/bin/quarto.js:56109:37)
    at async Chrome._start (file:///C:/Users/chaoj/AppData/Local/Programs/Quarto/bin/quarto.js:56065:25)
```

**Comment by cscheid** [comment]
Tracking on https://github.com/quarto-dev/quarto-cli/issues/4991
