### ISSUE TITLE
automatic addition of \ in front of @ when toggling from "source" to "visual" and back

### ISSUE THREAD

**Issue by gp1d** [quarto-dev/quarto-cli#3814]
I am recycling old R markdown in Quarto. I need to render as pdf to use as class notes. The old code includes references that work.
If I now toggle the RStudio viewer from "Source" to "Visual" and render the pdf, the references fail to appear. If I toggle back I see that [@definetti] has been turned into [\@definetti]. is this a bug? In practice, for my use case, this means I can only work in "Source" or "Visual" but not both, which is not ideal. Alternatives are clunky (e.g. search replace \@ with @ before the final rendering, which is never really final for a living document like class materials).

**Comment by mcanouil** [comment]
This would be better suited for https://github.com/RStudio/RStudio

RStudio visual editor has nothing to do with Quarto CLI.

**Comment by gp1d** [comment]
Apologies and thanks for the redirect.

> On Jan 1, 2023, at 1:55 PM, Mickaël Canouil ***@***.***> wrote:
> 
>         External Email - Use Caution        
> 
> 
> 
> This would be better suited for https://github.com/RStudio/RStudio <https://secure-web.cisco.com/1G7ZThMggs8ioKzI1B86l4GUbu0lwtv1_DtchAV8wJGPeLIgGo5DBNGzCR_o-p9JjzOvHVs2GRy1IlnURMhO3buVYrZFm56smKxv-M7NaAk-rnE-ncji2rd41Pd5BJTZ1V8uwDf4caGFPBkCos2lTbBCs9YJDiPqUTpUIpOp0wLlgZTWaoKYoxvUialyCxsGKoiKoq6eWZVHwSYWhBfyeWeOrhNh4m3qY06SQrBW1-6VjpHjYPnZLE10Hpe_f9Suo0FBAaKKi4HcZ5BWK0mloTeBY2wwDZHuXeNeY9h2gzZJBXCNh8aIEomlJEqA7aAGX/https%3A%2F%2Fgithub.com%2FRStudio%2FRStudio>
> RStudio visual editor has nothing to do with Quarto CLI.
> 
> —
> Reply to this email directly, view it on GitHub <https://secure-web.cisco.com/1c5Km6RrggA1Ptj8kePYhSueevSxn_KIQ-jBY-IliDPPlLJJ9A6HnbDUUdw015snwj8ah0yC6msN2gQd62eHEtxdYoiw1dMVqOWmaUWNAsZF_p9bXzeEfGQ8Z8wLsn4sr9GG-dJXuElx-IvD_ef-PqD75cP5XRsvGqnrp5n3eMIw6epLivAlT5hPrGqa-VG8biy2cmvDYi_N2RH53j0ZrNz1SkvX34DvViayc9q2U-ayOffSlRiCPhb9LpuZvyi7kuw4S3NII6HNEBP4Idno4LB0JApkTRClnAXoIGj33rF9gmQW2cSD1BLkkffxFxhAL/https%3A%2F%2Fgithub.com%2Fquarto-dev%2Fquarto-cli%2Fissues%2F3814%23issuecomment-1368507817>, or unsubscribe <https://secure-web.cisco.com/1YQPNMOQ_jF9tBhtmHX7TuP4jNjDMKcDc66ePmGdNZdN2MvVbPgamYiaV3PlmOMHNz6oLOl_U2nBMqx1U-qw8yK5NoJCn2OjGDeOFQNcCLrQd8bQtETYeENLLUGSY8ljFs2tJsE0SZ8jSxgj86SVrnPuCsOJRDZr2d46SKjjMHEVH8MJIPes1ofG8TN-PJh2q5D_0GtAmJmzO33qal4EPZHJcBAJDxx2jbQBcnsCOaj-4M9_zgygd4hOwLYPgVY7Lq1upVrhAtChTfY9UgfOWZt1X5gCOPCGl61ESEF9NL9wPGTXg4CUICikqG0zYtId-/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJXYPJH2S5JNJBT6BQVXMJDWQHHL3ANCNFSM6AAAAAATOFMOGI>.
> You are receiving this because you authored the thread.
> 

The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.
