### ISSUE TITLE
Document inline conditional content

### ISSUE THREAD

**Issue by mccarthy-m-g** [quarto-dev/quarto-cli#3863]
The documentation for [conditional content](https://quarto.org/docs/authoring/conditional.html) only discusses the use of divs, but you can also use inline CSS for conditional content. It would be nice if this was documented on the conditional content page too.

Here's a reprex .qmd for demonstration:

```qmd
---
title: "Reprex"
format:
  pdf: default
  html: default
---

::: {.content-visible when-format="html"}

Will only appear in HTML. (div)

:::

::: {.content-visible when-format="pdf"}

Will only appear in PDF. (div)

:::

[Will only appear in HTML. (inline)]{.content-visible when-format="html"}

[Will only appear in PDF. (inline)]{.content-visible when-format="pdf"}
```

**Comment by cscheid** [comment]
You're correct! We typically only document features we're confident are going to stick around, and you've spotted one of the ones we're experimenting with :)

**Comment by cwickham** [comment]
Closing via https://github.com/quarto-dev/quarto-web/pull/849
