### ISSUE TITLE
Chunk labels create empty figure captions when `fig-cap` is undefined

### ISSUE THREAD

**Issue by mccarthy-m-g** [quarto-dev/quarto-cli#3878]
### Bug description

Adding a label to a chunk will create an empty figure caption when `fig-cap` is undefined (this happens with the knitr-style syntax for chunk labels too). Figure captions should only appear if you opt into them with `fig-cap`, so this feels like a bug.

Here's a reprex:

````qmd
---
title: "Reprex"
format: html
---

```{r}
#| label: fig-cars
plot(cars)
```
````

![Screen Shot 2023-01-06 at 2 56 57 PM](https://user-images.githubusercontent.com/51542091/211113679-26e678d6-3d6e-45fc-99f3-7a0d72828516.png)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
This is currently by design (we can debate if it's wise design or not). If you want to refer to the cell but _not_ use a caption, do not use `fig-` as your prefix. When `fig-` is there, quarto believes you told it that the cell would be a figure, and figures need captions.

**Comment by mschubert** [comment]
I ran into the same issue, where I tried to:

1. Change the label to `#| label: nocap-fig-mylabel`, which led to figures running out of frame (horizontal scroll bar, but still a part wasn't displayed correctly)
2. Reverted to `#| label: fig-mylabel` but set CSS to not display figure legends (this works, but only if you want to remove all figure captions)

```css
```{css}
.figure-caption {
    display: none;
}
'``
```

**Comment by cscheid** [comment]
@mschubert That's a neat workaround, thanks for sharing! If you need the selector to be more specific, you can wrap the figures whose captions you want to hide in a fenced div with appropriate classes, like this:

````
::: {.hide-captions}
your-figure-content-with-no-caption-here
:::
````

And then add css like so:

```css
.hide-captions .figure-caption {
    display: none;
}
```

This should make the CSS selector pick only the figures inside divs with that class.

**Comment by jonastheiler** [comment]
You can also add a class to the figure-parameters like:

```{r}
#| echo: false
#| label: fig-plot
#| classes: map

plot(cars)
```


And add the following to css:

```
.map figcaption {
  display: none;
}
```
