### ISSUE TITLE
Crossreferencing between documents doesn't work

### ISSUE THREAD

**Issue by joelvonrotz** [quarto-dev/quarto-cli#3880]
### Bug description

Hello everyone

I'm having difficulties with crossreferencing a table in a separate document. Does crossreferencing between documents, which are included with the include-shortcode in a main file, even work?

I have a table in a file called `linux_bash_commands.qmd` that is given the following parameters, including the reference `#tbl-bash-commands`. The table compiles fine.

``` qmd
: Table of Linux Commands {tbl-colwidths="[20,20,25,35]" #tbl-bash-commands}
```

In another file called `linux_and_raspberry_pi4.qmd` I try to reference the table with following snippet.

``` qmd
Siehe @tbl-bash-commands
```

Both files `linux_and_raspberry_pi4.qmd` & `linux_bash_commands.qmd` are included in a main file called `main_aprog.qmd`. Following shows the contents of the file.

``` qmd
---
title: "Some interesting title"
author: "Some Authors"
date: "01.01.2023"

lang: de

# [RENDER CONFIGURATION] ==============================
format:
  pdf:
    include-in-header:
      - config.tex

pdf-engine: pdflatex
# [DOCUMENT CONFIGURATION] ============================
geometry: 
- "top=25mm"
- "bottom=30mm"
- "left=15mm"
- "right=15mm"
papersize: a4paper
fontsize: 9pt

code-block-border-left: false
code-block-bg: "#f7f7f7"

toc: true
toc-depth: 3
number-sections: true
number-depth: 3
pagenumbering: none
highlight-style: github
---


...

# Linux & Raspberry Pi 4

{{< include chapters/linux_and_raspberry_pi4.qmd >}}

...

{{< include chapters/linux_bash_commands.qmd >}}

...

```

Compiling the document results in following result:

![grafik](https://user-images.githubusercontent.com/41155337/211140575-b0cc7b94-5e37-4dfb-804f-ba97aa3b55b9.png)

---

Quarto Version: 1.2.280
OS System: 64-Bit Windows 10 Pro
LaTex Version: pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020/W32TeX)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by joelvonrotz** [comment]
I've found the issue, it was the way I configured the table.

I've changed

```
: Table of Linux Commands {tbl-colwidths="[20,20,25,35]" #tbl-bash-commands}
```

to

```
: Table of Linux Commands {#tbl-bash-commands tbl-colwidths="[20,20,25,35]"}
```

And it fixed the issue. Is this documented somewhere?

**Comment by cscheid** [comment]
This is indeed unfortunate behavior, but we inherit it from Pandoc's "fenced div attributes". I believe we don't document the required order anywhere, but it's a very good suggestion.

**Comment by cscheid** [comment]
I've opened a new issue to track the documentation improvement.

**Comment by joelvonrotz** [comment]
Thank you for taking the time! So far love to use Quarto!
