### ISSUE TITLE
Anchors not showing while hovering over headers of level 1 (h1)

### ISSUE THREAD

**Issue by prosoitos** [quarto-dev/quarto-cli#3891]
### Bug description

Unless I missed something, it seems that the anchor symbols do not appear for headers of level 1.

On your documentation site built with Quarto, it isn't an issue as your top level is `h2` (`## Some section title`), but on my site, I am starting at level 1 and I am missing those nice easy anchors for all `h1` (`# Some section title`) headers.

Here is one of the pages of the site to test it out: https://mint.westdri.ca/git/intro.html.

I did not add anything in my yml file on this nor did I customize anything linked with this.

Thank you!

---

OS: Arch Linux (6.1.3-arch1-1)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
We currently don't recommend that you use H1 directly in your content as the title of the page is typically an H1 (meaning that if you also use them in your content, there will be multiple H1 sections that are peers). Can you say more about why you'd rather start with H1 vs H2? Perhaps I can help find another solution.

**Comment by cscheid** [comment]
(Adding the `lint` label because flagging `h1`'s would be a prime candidate for a future warning)

**Comment by prosoitos** [comment]
I guess there was no particular reason to start with `h1` and I could change that by editing my css.

Since bootstrap as a `h1.title` class that allows to customize the title differently from the `h1` sections, I didn't see why not to start with that.

**Comment by prosoitos** [comment]
In short, if you think that Quarto websites should use `h2` as their top level, just confirm this and I will edit my site accordingly and close this issue. (Maybe a note on this should be added to the doc? Did I miss it?)

**Comment by prosoitos** [comment]
Well, one reason would be to have access to an additional level since pandoc seems to be limited to 6 header levels.

Started at `h2` reduces this to 5. Granted, 6 levels is not often needed, but that might be useful on occasions.

**Comment by prosoitos** [comment]
OK. I will do that and close the issue then. Thank you for this info. I didn't know.

Unless it is already there and I missed it, it might be worth adding this in the doc maybe?
