### ISSUE TITLE
Embedding local videos with the video shortcode fails.

### ISSUE THREAD

**Issue by Balaika** [quarto-dev/quarto-cli#3892]
## Description: 
Embedding local videos with the video shortcode fails.

## Steps to Reproduce:
- Create `index.qmd`
Where `local-video.mp4` is in the same directory as `index.qmd`.

```
---
format: 
  revealjs:
    embed-resources: true
---

{{< video local-video.mp4 >}}

```
or

```
---
format: 
  html:
    embed-resources: true
---

{{< video local-video.mp4 >}}

```

- `quarto preview index.qmd`

### Expected Result:
The video loads and is playable just like it would be if `embed-resources: false`

### Actual Result:
The video doesn't load.

reveal-js: an error message `No compatible source was found for this media.` is displayed.
html: no error message, video is not playable

#### Workaround
- Use `![](local-video.mp4)` instead of the shortcode.  The video is not responsive.
- `embed-resources: false`

----

### Bug description

Hi,

I would like to build a self contained html-revealjs with local videos. Yet, `embed-ressources: true` does not include videos added with `{{< video local-video.mp4 >}}` while it does with `background-video="local-video.mp4"` (Ubuntu 22.04, quarto v1.2).

```md
---
title: ""
format: 
  revealjs:
    embed-resources: true
---
  
##  {background-video="local-video.mp4"}

## 

{{< video local-video.mp4 >}}
```

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by ianxek** [comment]
Hi,
Using 1.2.313, I have the same problem as here and in [this topic](https://community.rstudio.com/t/how-to-insert-local-video-into-quarto-blog/155201) but it used to work for me.

I use nbdev and running the preview in directory `A`, it reads notebooks in directory `A/B` and reads figures in `A/B/Figures` given as `Figures//figure.png` but fails to see the video in `Figures/video.mp4` which means `{{< video Figures/video.mp4 >}}` fails with error `/Figures/video.mp4 (404: Not Found)`

**Comment by JeremyBYU** [comment]
I am having a similar issue where the local video is not being copied to the output directory and therefore is not found when presenting slides. Windows 11, Quarto 1.2.313. If I copy manually then it works.

**Comment by gustavdelius** [comment]
I am not sure why the {{< video >}} shortcode also accepts local videos in the first place, because for local videos we already have the standard markdown notation like 
`![](video.mp4) `
When using that markdown notation the local video is correctly copied to the output directory.

**Comment by allenmanning** [comment]
As requested @cscheid I've added you as an assignee.

**Comment by cderv** [comment]
I believe this is indeed all related to https://github.com/quarto-dev/quarto-cli/issues/5268 and we just need to add some HTML element to our resource detection.

**Comment by cderv** [comment]
Should be fixed by fixed by [eb969b2](https://github.com/quarto-dev/quarto-cli/commit/eb969b2b0625d785ec57665e65129bf1c9dbde36)

**Comment by lxj4321** [comment]
html文档：

1. 使用{{< video local-video1.mp4 >}}插入视频，无播放控件，edge右键显示全部控件，才可以播放；
2. {{< video local-video2.mp4 >}}插入第二个视频提示quarto  No compatible source was found for this media。

试了下上面提到的![](video.mp4) ，两个视频完美显示，并且可以播放。

**Comment by mcanouil** [comment]
@lxj4321 Please don't comment on closed issues, especially when they are few years old. Open a new [GitHub Discussion](https://github.com/quarto-dev/quarto-cli/discussions) in English.
