### ISSUE TITLE
Can not change the text color for the output of R code

### ISSUE THREAD

**Issue by guoruizhong** [quarto-dev/quarto-cli#3893]
Hi, 
I seeking help to change the color for the text output form the R code execution. The result I want is the text output to be white color, not the black color
I put the following setting for in the scss, but it not working
// Body
$body-color: $gray-400 !default;
$body-bg: $gray-900 !default;

Thanks very much
![output](https://user-images.githubusercontent.com/62880485/209456880-386ad18a-c93c-4899-8426-cf904937e6d8.jpg)

**Comment by cderv** [comment]
@guoruizhong which is your theme and highlight configuration ? 

Some quick test with a `dark` theme shows me a white color for the output without the need to customize. 

Can you help us reproduce ? 

Thank you !

**Comment by guoruizhong** [comment]
> @guoruizhong which is your theme and highlight configuration ? 
> 
> 
> 
> Some quick test with a `dark` theme shows me a white color for the output without the need to customize. 
> 
> 
> 
> Can you help us reproduce ? 
> 
> 
> 
> Thank you !

Thanks! i changed the parameters and now the output go with the code chunk, which is i want.

**Comment by cderv** [comment]
So no more issue @guoruizhong ? We can close ?

**Comment by guoruizhong** [comment]
> 

Yes!
