### ISSUE TITLE
"Error" messages when refreshing during `quarto serve`

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-cli#39]
When you're editing documents while using `quarto serve` on the command line, you get these "error" messages upon saving changes to any files:

![image](https://user-images.githubusercontent.com/6981612/122677957-422fb380-d1aa-11eb-997b-f4a46ce6c68a.png)

Is there a way we can change this message so a less experienced user doesn't get worried by all the "error" messages? Or is this just something we'll have to bring to the user's attention in the docs?

**Comment by jjallaire** [comment]
No we definitely shouldn't be showing this error! It's a result of an expected condition (breaking the websocket connection between client and server before reload) but we have logic to suppress it that isn't working in your config. 

I tried to repro with Chrome but couldn't. What browser are you using?

**Comment by jjallaire** [comment]
I see the error w/ Edge, should be able to easily track it down now....

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/d50849e1b945041651261bfe6a5675d1831a9424

**Comment by pommevilla** [comment]
Thanks JJ! All good now!
