### ISSUE TITLE
`default` document listing does not display `subtitle`

### ISSUE THREAD

**Issue by DayalStrub** [quarto-dev/quarto-cli#390]
Unless I am missing something, whereas with `table` and `grid` I can get `subtitle` to display, I cannot manage to do so with `default`. Indeed, I cannot see subtitle displayed in the [listing examples](https://quarto.org/docs/websites/website-listings.html#customizing-fields) in the docs. I'm assuming this is a bug, rather than intentional, as the [docs](https://quarto.org/docs/websites/website-listings.html#listing-fields) mentions `subtitle` for `default` mode in the default fields.

How to reproduce issue:

- set up a dummy blog `quarto create-project myblog --type website:blog`
- tweak demo posts by adding `subtitle: "This is a subtitle"` to yaml
- tweak main index.qmd by adding `fields: [date, title, subtitle, categories]` to yaml
- build/preview with `quarto preview blog`
- note the difference if you set `type: grid` rather than `default`

**Comment by dragonstyle** [comment]
Thanks for letting us know - indeed a bug! Should be fixed in the latest build.
