### ISSUE TITLE
Auto binding will use knitr engine when only a inline code syntax is in the doc

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#3908]
From https://github.com/quarto-dev/quarto-r/issues/40

Simple `.qmd` document with only inline code syntax, starting with `r`

````markdown
`r ** 2`
````

This will be recognized as R inline code and knitr engine will be required. However, for users doing only markdown writing this is surprising.

Unfortunate syntax clash in our discovery.  

I don't know if we can do better, but I was thinking maybe only code cells should trigger engine - Will it be that common to only have R inline code in a document without a code cell in the document ? 

Anyway, probably worth considering if we can.

**Comment by cscheid** [comment]
It seems that we're doing this on purpose, there's a [particular commit](https://github.com/quarto-dev/quarto-cli/commit/4240d00e97fe232adcf8a2fd23da4242d795c9a9) where jj added this feature. So we should make sure that we want to disable it.

**Comment by cderv** [comment]
I thought we discussed that already and we decided that it was not so bad to deactivate if there are only inline R code in the document, and no chunk at all. It seems very rare to have only inline R code in a document with no R code cells. Forcing **knitr** for verbatim inline strating with r (i.e `` `r ``) can be annoying for Quarto users having documents with no computation. 

At least this is what I remember and was planning to do.

**Comment by cscheid** [comment]
I agree with all of that! The only issue is that the code path I mentioned is triggered exactly "if there are only inline R code in the document, and no chunk at all", so that change appears to be intentional.

**Comment by cderv** [comment]
From meeting discussion: 
* We do the change yes and we add specific note in the release notes

**Comment by cderv** [comment]
@cscheid I let you handle this
