### ISSUE TITLE
CNAME is deleted in the docs folder when rendering quarto book in Rstudio

### ISSUE THREAD

**Issue by sbalci** [quarto-dev/quarto-cli#391]
Hi,
Thanks for the quarto.

I use CNAME for custom github page address.
CNAME is deleted in the docs folder when rendering quarto book in Rstudio, and the address forwarding does not work.

I have other pages with Rmarkdown (distill) and they copy the CNAME to docs folder when rendering.

Thank you.

Serdar

**Comment by jjallaire** [comment]
We added support for automatically copying `CNAME` to `docs` a couple of weeks ago so this should be working if you are on a recent version. What version of Quarto are you running?

**Comment by sbalci** [comment]
Hi,
Thank you. After updating to 0.9.71 the problem is solved.
