### ISSUE TITLE
Rstudio 2022.12.0 Build 353 Quarto Preview option not available

### ISSUE THREAD

**Issue by dschief001** [quarto-dev/quarto-cli#3915]
Hi!

When using Rstudio, Quarto is installed locally, the option to use the Quarto preview/in general the whole Global options Quarto tab is missing, is this intentional?

Thanks a lot for checking.

![grafik](https://user-images.githubusercontent.com/35806794/211549676-f26d9f65-cd1f-4842-8fc6-ce96e6d4628a.png)
 compare this with the instructions given at https://quarto.org/docs/tools/rstudio.html

**Comment by dragonstyle** [comment]
Yes, this is intentional - the 'Quarto' tab is used to activate the version of Quarto that is bundled with RStudio, if Quarto has been installed by the user, we just use that system and there is no need for the panel to allow activation of the embedded copy.
