### ISSUE TITLE
Problems with the feed in my quarto blog

### ISSUE THREAD

**Issue by jrcuesta** [quarto-dev/quarto-cli#3916]
for some reasons the feed does not work in my blog when I use:
 https://simplepie.org/demo/?feed=https://jrcuesta.quarto.pub/nir-chemometrics%2Findex.xml
If I click on the link to the blog gives a 404 error, and for other side the images does not appear.
Please let me know if something can be done 
Thanks

**Comment by dragonstyle** [comment]
Can you please share the source code for your site? In testing locally with a simple blog I can't reproduce the issue, but I'm not explicitly setting a `site-url` in my `_quarto.yml` (as Quarto Pub will automatically provide the correct `site-url` for use in the feed).

**Comment by jrcuesta** [comment]
Thanks a lot for your quick reply. 
This is the link for the repo on github.
hope is what you ask me for.
https://github.com/jrcuesta/QUARTO

**Comment by dragonstyle** [comment]
I believe that the issue is that the `site-url` that appears in the `_quarto.yml` file is pointing to the incorrect URL. Can you try either omitting it altogether (we will automatically coordinate with Quarto Pub specifically to get the correct URL) or setting it to:

`site-url: https://jrcuesta.quarto.pub/nir-chemometrics/`

**Comment by jrcuesta** [comment]
I change it in the _quarto.yml, save it and publish it in the _quarto.yml,
 but I see that in the publish.yml file remains:
https://quartopub.com/sites/jrcuesta/nir-chemometrics
if I changes manually again goes back to the previous one.
Another thing is that un the feed appear always:
<atom:link href="https://quartopub.com/sites/jrcuesta/nir-chemometrics/index.xml" rel="self" type="application/rss+xml"/>

**Comment by dragonstyle** [comment]
Just to keep things simple to start, you can ignore the `publish.yml` and let's just focus on the `_quarto.yml`. In that file can you try setting the `site-url:` to `https://jrcuesta.quarto.pub/nir-chemometrics/`. This is the url that is used when generating the feed. Once you've made that edit, try re-generating the site with this URL and see how the feed looks - I am expecting this will cause the the feed to be located correctly and the images to work correctly.

**Comment by jrcuesta** [comment]
Thanks a lot.

**Comment by jrcuesta** [comment]
Now with either of then give me this problem
![image](https://user-images.githubusercontent.com/1682388/212038753-555f2a7e-0674-4e3e-8ca7-21c28ed4b07a.png)
![image](https://user-images.githubusercontent.com/1682388/212039258-9cfc72ab-58ae-46da-a186-e014a0d40bd8.png)
I press allow, but it does not work.

**Comment by dragonstyle** [comment]
There was a Quarto Pub related bug that should be fixed now (was just bad luck, should not have been related to your issue specifically)

**Comment by jrcuesta** [comment]
Thanks a lot .
It works fine now.
