### ISSUE TITLE
embedding external images for epub books

### ISSUE THREAD

**Issue by sbalci** [quarto-dev/quarto-cli#392]
Hi,

When I try to embed external images to html I have no problem. But epub book rendering gives error.

- When I use `![]()` syntax I get following error:

`![saplı polip](https://pathologyatlas.github.io/tubularadenoma/tubular-adenoma-with-stalk-macroscopy.jpg)
`

```
! Unable to load picture or PDF file 'https://github.com/pathologyatlas/tubular
adenoma/raw/main/tubular-adenoma-with-stalk-macroscopy.jpg'.
<to be read again> 
```

- If I use `img src` I get following error:

`<img src="https://pathologyatlas.github.io/tubularadenoma/tubular-adenoma-with-stalk-macroscopy.jpg">`

```
Error running filter /Applications/quarto/share/filters/quarto-pre/quarto-pre.lua:
...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:1774: attempt to concatenate a nil value
stack traceback:
	[C]: in function 'string.gsub'
	...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:1773: in function 'handleHtmlRefs'
	...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:1759: in function 'handleRawElement'
	...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:3946: in function <...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:3940>
```

I am using 0.9.71

Best wishes

Serdar

**Comment by jjallaire** [comment]
The second error was a bug in our `<img>` tag parsing. Fixed here: https://github.com/quarto-dev/quarto-cli/commit/4212c4979e0e4810217e946692f3dee7cdf94527. The "unable to load picture" issue is not something I can reproduce (the image embeds fine in epubs I render locally)
