### ISSUE TITLE
figure paths are broken in hugo-md format

### ISSUE THREAD

**Issue by cboettig** [quarto-dev/quarto-cli#3930]
As you probably know, [Hugo renders content](https://gohugo.io/content-management/organization/) from a path such as `content/section/my_page.md` to `publish/section/my_page/index.html`.  This breaks the default image links, which assumes the rendered version remains at the same directory depth, instead of being promoted from `section/` to `section/my_page`.  Thus `index.html` will contain figure links like `my-page.markdown_strict_files/figure-markdown_strict/pressure-1.png` which do not resolve, because it should be `../my-page.markdown_strict_files/figure-markdown_strict/pressure-1.png`.  

I thought I might be able to work around this with knitr `fig.path` options, but that just opens a rabbit hole (e.g. `fig.path="../`" doesn't help any, but has the side effect of two copies of the figure being created, one with `my-page.markdown_strict_files/figure-markdown_strict` path and one with no additional path.  The `.md` and `.html` use the one with no additional path, but this only causes more chaos with hugo's mapping conventions....

**Comment by cscheid** [comment]
Thanks for the report! Can you provide us with a minimal example that fails to build? There are some details about the interaction between quarto and hugo which need to happen.

Just to make sure we're on the same page, did you make sure to follow the instructions here? https://quarto.org/docs/output-formats/hugo.html

**Comment by cboettig** [comment]
Ah thanks, it looks like this issue may only occur if quarto files use names like `contents/page-name.qmd` instead of `contents/page-name/index.qmd` as the docs suggest!  (I didn't fully appreciate the doc's warnings about needing to stick with this format to conform to being a [page bundle](https://gohugo.io/content-management/page-bundles/) in hugo!
