### ISSUE TITLE
Code annotations in the v1.3.97 pre-release are not working when `code-link: true`

### ISSUE THREAD

**Issue by cgoo4** [quarto-dev/quarto-cli#3945]
### Bug description

Code annotations in the v1.3.97 pre-release are not working when `code-link: true`:

A reproducible example may be made in RStudio with New Project > Quarto Website, then add `code-link: true` to the _quarto.yml.

````markdown
---
title: "Reprex"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{r}
1 + 2 # <1>
```

1.  Simple calculation
````

Sample Quarto site with `code-link: true` added:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/32419319/212060887-c1fdcf78-94fe-4576-a65a-5a7b55862eea.png">

Sample Quarto site without

<img width="829" alt="image" src="https://user-images.githubusercontent.com/32419319/212061613-fefccb21-ac24-4731-b228-0c159bb55fd8.png">

RStudio Version 2022.12.0+353 (2022.12.0+353)
macOS Monterey v12.6

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I took a look at this issue and I'm not sure I see way to make this work, unfortunately. `code-link` is very invasive to the code cells and appears to transform the cells into a single large cell, dropping some HTML along the way. As a result, we are rendering the annotations below as a simple definition list and the annotations in the code are not rendering.

**Comment by dragonstyle** [comment]
Great idea, I'll do that!
