### ISSUE TITLE
revealjs - fontawesome icon in section header does not appear in presentation outline

### ISSUE THREAD

**Issue by kbvernon** [quarto-dev/quarto-cli#3950]
### Bug description

Hi. As always, thank you, thank you, thank you for this awesome software. 

As the title states, for revealjs documents, fontawesome icons used in section headers do not appear in the presentation outline. Unicode/HTML does, though.

````md
---
title: "Test Prez"
format: revealjs
---

## Slide 1 📋 

## Slide 2 {{< fa brands r-project >}}

## Slide 3 &#x1F3AF;
````

Output:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/53311626/212113357-6aae228e-65b4-4c6e-8e52-62ac7bde7ea1.png">

```
> sessioninfo::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 22621)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/Denver
 date     2023-01-12
 rstudio  2022.12.0+353 Elsbeth Geranium (desktop)
 pandoc   NA
```
Not sure why it's not showing my pandoc version, but here's this:
```
> rmarkdown::find_pandoc()
$version
[1] ‘2.19.2’

$dir
[1] "C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools"
```

Thanks!

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I think this is a revealjs limitation. If you use other sources of raw html (like a link or something like that) on the title, do those show up on the outline?

**Comment by kbvernon** [comment]
Here are some different link options:

````md
---
title: "Test Prez"
format: revealjs
---

## Slide 1 📋 

## Slide 2 {{< fa brands r-project >}}

## Slide 3 &#x1F3AF;

## Slide 4 <https://github.com/>

## Slide 5 [bob](https://github.com/)

## Slide 6 <a href="https://github.com/">bob</a>
````

Output:
<img width="233" alt="image" src="https://user-images.githubusercontent.com/53311626/212133307-ce7445cb-dfb5-4d75-9022-8780b802bb5b.png">

**Comment by cscheid** [comment]
Right, so notice that what's happening is that you don't get a link; you get the plain text. A font-awesome icon is an `<i>` tag with extra information. This is consistent with my current hypothesis that this is a revealjs limitation.

**Comment by kbvernon** [comment]
Ah. I think I see what you mean. 

```
<i class="fa-brands fa-r-project fa-"></i>
```

There's no text inside that tag to get added to the outline. Any suggestions for how to get around this? Should I submit an issue to revealjs?

**Comment by cscheid** [comment]
Yes, I think that would be appropriate. But if you choose to go that route, please create a self-contained `revealjs` document to confirm the issue outside of quarto.

**Comment by kbvernon** [comment]
Alright. Thanks for the help!
