### ISSUE TITLE
Line numbers of code blocks are not 

### ISSUE THREAD

**Issue by sebffischer** [quarto-dev/quarto-cli#3954]
### Bug description

When we include R code in quarto files, the same code chunk (with our current setup) is split into multiple rendered junks (even though it belongs to the same junk in the source code. Each of these rendered junks starts with the number 1, which is not desirable as it prevents referring to the line numbers correctly.

E.g. in the image below, we might have something like this in the qmd file: 

```r
task_mtcats$nrow
task_mtcars$ncol
```

I would expect the first line to get the number 1 and the second line to get the number 2, but both get number 1 because in the rendered output they become two junks. 

![mlr32](https://user-images.githubusercontent.com/20975557/212129037-ef82ff15-190e-459c-837f-b623b3a9c493.png)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Could you add `result: hold` to your cell? This will group the output after the code cell:

````markdown
```{r}
#| results: hold
task_mtcats$nrow
task_mtcars$ncol
```
````

Should do what you're looking for, I believe.
