### ISSUE TITLE
Error on rendering r code

### ISSUE THREAD

**Issue by AbdurrahmanMN** [quarto-dev/quarto-cli#3967]
Just getting started with quarto. I used it in VSC and it rendered with python code..but with r code, using the file from the official site
https://quarto.org/docs/get-started/hello/rstudio/_hello.qmd
from here
https://quarto.org/docs/get-started/hello/rstudio.html
 the following error occured when trying to render this r code both in vsc and rstudio
Output:
```
processing file: hello.qmd
  |..............                                                        |  20%
  ordinary text without R code

  |............................                                          |  40%
label: load-packages (with options) 
List of 1
 $ include: logi FALSE

  |..........................................                            |  60%
   inline R code fragments

  |........................................................              |  80%
label: plot-penguins (with options) 
List of 3
 $ warning: logi FALSE
 $ echo   : logi FALSE
 $ message: logi FALSE

Quitting from lines 28-43 (hello.qmd) 
Error in png(..., res = dpi, units = "in") : unable to start png() device
Calls: .main ... in_dir -> plot2dev -> do.call -> <Anonymous> -> png
In addition: Warning messages:
1: In png(..., res = dpi, units = "in") :
  unable to open file 'hello_files/figure-html/plot-penguins-1.png' for writing
2: In png(..., res = dpi, units = "in") : opening device failed

Execution halted
```

Thanks a lot

**Comment by cscheid** [comment]
Can you answer the questions in [this template first](https://github.com/quarto-dev/quarto-cli/issues/new?assignees=&labels=bug&template=bug_report.yml) Thank you.

**Comment by AbdurrahmanMN** [comment]
The version of quarto:[quarto-1.2.313]
    The operating system : win 10
    The IDE :Rstudio 2022.12.0-353 and vsc v 1.74.2

**Comment by cscheid** [comment]
@cderv it looks like this sort of error comes from dev() not having the right permissions. Do you know what could be causing it in this context?

**Comment by mcanouil** [comment]
I saw some errors like this in the past under Windows OS related to paths, especially non ascii characters and for very long root path, might it be this?

**Comment by cderv** [comment]
@AbdurrahmanMN in which paths context are you running this document ? Can you share more on the paths you are using ? 

You could try changing the document to a place where you are sure you can write to it, and it is not a synced path (like OneDrive folder). 

This sort of error comes from R directly and something is not correct with the path. It is also possible that the PNG file is opened elsewhere, and somehow locked for writing. You can also check that this is ok.
