### ISSUE TITLE
Quarto Render button not working but `quarto render` in command line works

### ISSUE THREAD

**Issue by sweiner123** [quarto-dev/quarto-cli#3968]
### Bug description

Hello! I am getting an issue when I press the render button in Rstudio vs running `quarto render` in the CLI. When I press Render in Rstudio, my python installation is not being found, but when I run 'quarto render' everything works just as expected. 

Here are the outputs from trying to press Render and running 'quarto check jupyter` in the CLI respectively. 
I am using Windows 10  and RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

![image](https://user-images.githubusercontent.com/69181144/212436709-1b9ac825-54e0-4e3f-a76a-816e53870928.png)

![image](https://user-images.githubusercontent.com/69181144/212436766-b717c064-cf12-4c3e-86d5-49683bd51ff8.png)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
> but when I run 'quarto render' everything works just as expected.

The environment is likely different across the installations. `nbformat` is a required package, and I imagine it's installed in one of our Python setups, but not in the other.

**Comment by cderv** [comment]
@sweiner123 it seems you are running anaconda on windows, and that you are using a some conda environment from your Terminal screenshot. (seeing the `(base)`). 

Are you setting a specific terminal in RStudio IDE ? 

It seems that IDE is not running the background job in a session where anaconda is activated or found. Quarto will look into the PATH to find for python (or use `py.exe` on windows  `py --list`). 

Not that you can force a Python version to be used with `QUARTO_PYTHON` env var (this could be useful if you always want to use a specific conda env maybe). IDE also have a way to pin a python version in setting. 

So do check that your python is correctly found on your system without needed a specific `activate` for a conda env. 

Hope it helps

**Comment by sweiner123** [comment]
Hi sorry for the late response. I added `reticulate::use_condaenv()` in my script which worked with the render button in the IDE. I will try to add my conda env in the way you specified and see if that works too. 

Thank you for your help!
