### ISSUE TITLE
rendering a document with online image to pdf is not possible on Windows

### ISSUE THREAD

**Issue by hemonika** [quarto-dev/quarto-cli#3982]
I tried to render the quarto example document "hello.qmd" to pdf. This throws an error, because an external image is linked in Markdown (the same problem would appear in R Markdown). As soon as I comment out the image the pdf document can be created.

I think it is not ideal to use an example document that cannot be rendered in all widely used formats html, pdf, docx.

**Comment by cscheid** [comment]
> It seems to have suffered Unix->DOS conversion.
Somewhere, some code is opening that binary file in text mode, and all `\n` are getting converted to `\r\n` 😬

**Comment by tarleb** [comment]
I've just opened a PR in pandoc that might help in the future: jgm/pandoc#8552.
