### ISSUE TITLE
Unable to publish on quartopub blog

### ISSUE THREAD

**Issue by bhattmaulik** [quarto-dev/quarto-cli#3990]
### Bug Description
My issue is exactly the same as issue #3941. I have tried everything mentioned in it, and still unable to publish on quarto pub. Every time I attempt, I am asked to re-authorize my account. And even after re-authorization, the publishing process doesn't go ahead at all. I updated RStudio version to 2023.03.0 +79 and quarto to version 1.3.112. But still the issue persists.
### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by bhattmaulik** [comment]
Let me know if you need further inputs from my side.

**Comment by softwarenerd** [comment]
@bhattmaulik, please check your email!

**Comment by bhattmaulik** [comment]
I am closing this issue now, as I can publish my blog on quartopub website now. For this, I had to update the quarto version to 1.3.140. Thank you @softwarenerd and @cderv for your support.
