### ISSUE TITLE
Syntax highlighting messed up by profvis::profvis()

### ISSUE THREAD

**Issue by prosoitos** [quarto-dev/quarto-cli#3991]
### Bug description

The function `profvis::profvis()`, somehow, messes up the syntax highlighting of R code blocks.

## Example

File:

````Rmd
---
format: html
---

```{r}
library(profvis)

f <- function() {
  pause(0.1)
}

# profvis(f())
```
````

Normal syntax highlighting:

![2023-01-16_22-30_1](https://user-images.githubusercontent.com/4634851/212826982-703d5f36-32da-4416-887f-b17ad1a6869b.png)

With `profvis::profvis()`:

````Rmd
---
format: html
---

```{r}
library(profvis)

f <- function() {
  pause(0.1)
}

profvis(f())
```
````

Syntax highlighting totally messed up:

![2023-01-16_22-30_2](https://user-images.githubusercontent.com/4634851/212826353-b17f6799-2313-41c5-86b1-25f0db10fcfd.png)

## Context

Same behaviour with any highlight style, with `format: revealjs` and `format: html`, within a website or outside.

*Note: this might be something weird that the function is doing and may not be a Quarto bug per se.*

## OS

Arch Linux (6.1.6-arch1-1)

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by prosoitos** [comment]
Note that it might not seem like a big deal with the default theme as the messed up version is readable. But in my website, I use the monokai highlight theme and instead of the normal great looking code blocks I get:

![2023-01-16_22-50](https://user-images.githubusercontent.com/4634851/212829415-e3f648a6-25b2-48e2-8d5b-4fa604acc9ae.png)

**Comment by prosoitos** [comment]
Also: as the function, somehow, seems to interfere with the CSS section that has to do with syntax highlighting in `<head>` of the rendered html file, it is of course all the R code blocks that are messed up. Not just the one with the function.

Of note, I have some Bash blocks on the same file and those are not affected. If I add some `{.python}` or `{.julia}` blocks, those are also not affected. So only the CSS part of the R blocks gets messed up.

**Comment by prosoitos** [comment]
For comparison, if I don't run the `profvis()` line (here I am putting it in a `{.r}` block), the normal highlighting looks like this:

![2023-01-16_22-59](https://user-images.githubusercontent.com/4634851/212831097-29facc66-6e1c-4d68-bdee-931403e9a9bb.png)

**Comment by cderv** [comment]
@prosoitos if you look at the HTML code with and without `profvis()` activated, you'll see that the `<head>` in HTML will contain some specific content introduced by profvis dependencies. 

`profvis::profvis()` returns an HTMLWIDGETS which brings some JS dependencies, among which `highlight.js` 

* here is the widget manifest : https://github.com/rstudio/profvis/blob/56909161249ef1b9308ccba99eb1917a13828bf0/inst/htmlwidgets/profvis.yaml#L19-L23
* The HTML deps for highlight brought by **profvis** with a specific `textmate.css`: https://github.com/rstudio/profvis/tree/56909161249ef1b9308ccba99eb1917a13828bf0/inst/htmlwidgets/lib/highlight
* and `profvis.js` which run highlighting function on the HTML code https://github.com/rstudio/profvis/blob/56909161249ef1b9308ccba99eb1917a13828bf0/inst/htmlwidgets/lib/profvis/profvis.js

Quarto is using Pandoc syntax highlighting with HTML, and use some CSS theme accordingly. Using **profvis** will bring highlight.js, run it and bring a theme `texmate.css`. This will mess up the Quarto syntax highligting procesing, and overwrite the theme. 

I am surprised that **profvis** actions are not scoped and applies also on other code blocks (looking at the HTML on the code blocks, it seems they get process by highlight.js functions too). 

So I would say this is an issue with **profvis** directly. 

> For comparison, if I don't run the profvis() line (here I am putting it in a {.r} block), the normal highlighting looks like this:

By not running `profvis()`, `highlight.js` is not added with the CSS theme and so Quarto syntax highlighting applies. 

BTW this is the same with R Markdown as with Quarto - Same behavior when you tell R Markdown to highlight using Pandoc but it gets messed up by Profvis

<details>
<summary>Example Rmd</summary>

````markdown
---
title: "R Notebook"
output:
  html_document: 
    highlight: arrow
---

```{r}
library(profvis)

f <- function() {
  pause(0.1)
}

profvis(f())
```
````


</details>

**Comment by prosoitos** [comment]
Right. Thank you.

Should I then open an issue in the profvis project? Since the package is also developed by Posit, maybe it is fine to keep it here??

**Comment by cderv** [comment]
> Should I then open an issue in the profvis project? Since the package is also developed by Posit, maybe it is fine to keep it here??

It is not develop by the same team, and the maintainer of **profvis** does not track in Quarto. I can't migrate the issue between Quarto org and RStudio org. So if possible, it is best to open an issue in Profvis as it affect also R Markdown. 

Thank you !

**Comment by prosoitos** [comment]
OK, will do and I guess I should close this issue here.

Thank you!
