### ISSUE TITLE
Feature request: option to render chunk as separate HTML file and embed as iframe

### ISSUE THREAD

**Issue by jimjam-slam** [quarto-dev/quarto-cli#400]
I love that I can use Quarto to do my data analysis in R or Python and then switch to an OJS chunk to visualise. What would be amazing is if I could render that visualisation in a separate, child HTML file and have that file embedded in the main rendered doc as an `<iframe>`. That way I could still read the rendered document to see the visualisation's analysis context, but I could also embed the visualisation elsewhere if I uploaded the rendered output to a server (in a similar fashion to the way the hosted Observable service allows you to embed a single chunk from a notebook elsewhere). The default would be the current behaviour, where the chunk output is inlined.

This would have implications for overall file size, as well as whether Quarto styles and other dependencies are duplicated across files, but I think it would really open up some other use cases!

**Comment by jjallaire** [comment]
I think a variation of this is possible by importing reactive data sources from other qmd files: https://quarto.org/docs/interactive/ojs/code-reuse.html#data

So you'd do all of the analysis in the main file, then the iframe could be another qmd that imports that data and is in turn pointed to from an `iframe`. There is an order of execution dependency, but that could probably be managed.

The other way to do would be to simply do everything in the main file, then create another qmd that imports the outputs  (https://quarto.org/docs/interactive/ojs/code-reuse.html#output) which could then serve as the embeddable version.

@cscheid Will know if there is yet an even better way to handle this scenario.

**Comment by jimjam-slam** [comment]
I really like that second idea, @jjallaire! The second qmd that imports the main version's output could be customised to strip back some of the other layout, too. I'll have a tinker with this and see what I come up with!

**Comment by jjallaire** [comment]
For the second `.qmd` you might want to use `page-layout: custom` to eliminate all of the standard padding in HTML documents (you can of course use CSS to add padding back in as required)

**Comment by jimjam-slam** [comment]
> For the second `.qmd` you might want to use `page-layout: custom` to eliminate all of the standard padding in HTML documents (you can of course use CSS to add padding back in as required)

This works quite well for a plot on its own, but I'd love to be able to combine some Observable Inputs with a plot. See for example:

https://jimjam-slam.github.io/quarto-embed-test/article.html
https://jimjam-slam.github.io/quarto-embed-test/embedded-ozone.html

In the second file, I've tried to import the input and the plot, but I only get the default value of the input:

https://github.com/jimjam-slam/quarto-embed-test/blob/main/embedded-ozone.qmd

What do you think? Is there a way I can do this?

**Comment by cscheid** [comment]
Hi @jimjam-slam - glad you're finding the OJS support useful!

Off the top of my head, I don't think fully reactive inputs and outputs across .qmd files will work,  _in its present state_.

I can explain the technical issues in more detail, but the short of it is that Observable's runtime needs to know about the full javascript source of the file we're importing from, and we currently don't expose that.

There are some things you can do in the meantime.

1) If the content you want to reuse is hosted on observablehq.com, then we _do_ support importing reactives from that, quite directly.
2) If the content you want to use is Javascript (and not reactive observable inputs), then you can import them from the `{ojs}` tags as if they were plain ES6 modules, and reusability should just work.

I'm sorry we don't support this right now. But a full, better story of includes and reusability of OJS across .qmd cells is on our radar, though, so stay tuned!

**Comment by jimjam-slam** [comment]
Thanks for the explanation, @cscheid! That makes sense. Really appreciate the advice, and I'm looking forward to where things go. Quarto is a delight 🥳

**Comment by jimjam-slam** [comment]
After [a bit of reading](https://observablehq.com/@bryangingechen/imports-tips-and-tricks#importViewof), it turns out this is indeed possible and still appears to work with Quarto! I modified the embedded version so that the both the import statement and the reference to my dropdown menu were prefixed with `viewof`, just as the original declaration was.

Here's the commit in my demo with the change: https://github.com/jimjam-slam/quarto-embed-test/commit/1e1da75d311c89c1151db485115a36fa318eed2e?diff=split#diff-86c1ec18c8e0992808c11788e75898c4e7875910b6ecea4a322f847e3601aece

It's very cool that this workflow just seems to work! I'm not sure if you expected it, but feel free to take a look at it if you like!

**Comment by cscheid** [comment]
I don't think I expected that, but it's indeed excellent that it does!
