### ISSUE TITLE
`Cannot read properties of undefined (reading 'map')` on quarto install tinytex

### ISSUE THREAD

**Issue by DOH-FAA3303** [quarto-dev/quarto-cli#4005]
Hello,

I've been having a really hard time getting Github Actions to render my site. I keep getting this error and wonder if anyone knows how to solve it. I think there is a version issue going on but I don't understand how to fix it

![image](https://user-images.githubusercontent.com/92396451/209726904-8f50b9f1-5364-4e83-8c48-443061742c6a.png)

edit:
The build seems to fail, but sometime after the site will still publish. Is this to be expected? In the image below, the summary.qmd build failed but then that git push seemed to still trigger and successfully publish the quarto site. So maybe this is a non issue?

![image](https://user-images.githubusercontent.com/92396451/209727393-01d146ea-740d-4b9d-8aef-f863d2e3789c.png)

**Comment by dabreegster** [comment]
FWIW, I got a successful run by installing tinytex later down. Seems equivalent to the action, so probably just a sign of flakiness somewhere. Let me know how I can help debug, and thanks for all the work on Quarto!
https://github.com/alan-turing-institute/uatk-spc/commit/01713ae9fda5fe0d59fa65274b3e833435f1c720

**Comment by cscheid** [comment]
@dabreegster Thank you! I've updated [quarto-dev/quarto-actions](https://github.com/quarto-dev/quarto-actions) to print a stack trace by default, so that if/when this happens in the future, the error output should be more actionable. I'll keep this one open until we track the issue down.
