### ISSUE TITLE
Post-render TS script can't find uncached modules

### ISSUE THREAD

**Issue by wch** [quarto-dev/quarto-cli#401]
I have a `post-render` script written in TypeScript. At the top it has the following import:

```ts
import * as fs from "https://deno.land/std@0.129.0/fs/mod.ts";
```

When I run `quarto-render`, I get the following error:

```
scripts/post-render.ts
error: Specifier not found in cache: "https://deno.land/std@0.129.0/fs/mod.ts", --cached-only is specified.
```

I think the way to solve this would be to run `deno cache scripts/post-render.ts`. However I don't see an easy way of running the copy of `deno` that `quarto` uses. I could figure this out for my system, but it wouldn't be easy for other people working on the same project.

**Comment by jjallaire** [comment]
You can't use the version specifier directly in these imports (see https://quarto.org/docs/projects/quarto-projects.html#deno-scripts). If you remove the version then it will automatically use the version cached by Quarto in its installation.

**Comment by jjallaire** [comment]
You generally can't run any remote code w/ this mechanism b/c we didn't want random URL imports automatically running during render (as that would essentially be like running `install.packages` as a hidden side effect of running an R script.

**Comment by jjallaire** [comment]
Okay, I think we just need to pull a more recent version of the standard library. Note that you should also be able to do `await fs.copy("test.txt", "testcopy.txt")` 

We don't want to allow any executing of downloaded code by default for principle of least surprise (i.e. users don't expect doing `git pull && quarto render` will download and execute remote code).

**Comment by jjallaire** [comment]
My previous suggestion actually might not work but this would w/ 1.22.0:

```typescript
import { copySync } from "https://deno.land/std/fs/copy.ts";
```

They were requiring a special sub-import in earlier versions of the standard library b/c `copySync` relied on an `--unstable` API (which is now likely stable)

**Comment by jjallaire** [comment]
FYI we've now updated to Deno std v0.129.0: https://github.com/quarto-dev/quarto-cli/commit/3a8bd41cf960b40e063e2feb608c06434c3ce4a6
