### ISSUE TITLE
Formation of docx file failed

### ISSUE THREAD

**Issue by LiangChen3519** [quarto-dev/quarto-cli#403]
I was trying to formate a "docx" file (MS word file), but failed. And i don't know the reason why. strange thing was that when i switch to Rmarkdown, the docx file was successfully produced.

here is what i wrote in yaml of qmd File:
![image](https://user-images.githubusercontent.com/61409749/157880064-8857d2b4-b074-4a1e-8ca9-d23b956a7931.png)
 
And here are the errors:
![image](https://user-images.githubusercontent.com/61409749/157880161-245225a3-4921-4b7f-8870-b44a2807e7ce.png)

ps: 
1. Rstudio version
RStudio 2022.02.0+443 "Prairie Trillium" Release (9f7969398b90468440a501cf065295d9050bb776, 2022-02-16) for Windows

2. Rversion
R version 4.1.2 (2021-11-01) -- "Bird Hippie"

Thanks in advance.

**Comment by cderv** [comment]
FWIW I am using last dev version of Quarto and last daily RStudio version with this YAML header on the template document and I am not able to reproduce 

````yaml
---
titre : "test"
format : 
  docx:
      toc: true
      number-sections: true
editor : visual
---
````

I used less indentation as recommended but even with more I don't reproduce.

Error is with `create_output_format()` function which is from **rmarkdown** initially. Do you have Knit or Render in the button in the IDE ? It is as if `rmarkdown::render()` was run... 

RStudio Edition : Desktop [Open Source]
RStudio Version : 2022.6.0.203
OS Version      : Windows 10 x64 (build 22000)
R Version       : R version 4.1.2 (2021-11-01)

**Comment by LiangChen3519** [comment]
Hi, I don't know what happened, after i updated all packages and the word file was successfully produced!!!!

**Comment by jjallaire** [comment]
I can confirm that the current RStudio daily build on windows (daily-300) does not currently detect and use the embedded version of Quarto when running through the "Render" pane (as happens w/ docx). Here's what I see when attempting to render a docx:

![Screen Shot 2022-04-14 at 10 21 44 AM](https://user-images.githubusercontent.com/104391/163410892-e58520f5-6ad9-4447-ae11-2d34878e1bfb.png)

Further, quarto does not appear to be on the path when running a terminal.

I know that we just made some changes to the embedding of Quarto in the IDE and this is likely the culprit. We'll investigate ASAP.
