### ISSUE TITLE
background-color hides logo

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#4031]
### Bug description

With Quarto 1.2.280 (included in recent RStudio daily builds), the presence of a `background-color` in a reveal.js presentation hides a configured `logo`, while the `footer` stays visible.

````markdown
---
title: "logo and footer"
format:
  revealjs:
    theme: simple
    logo: posit-logo-black-TM.svg
    footer: "the footer text"
---

## Nothing special

No background color. Footer and logo present.

## Background color {background-color="white"}

Background color. Footer, but no logo.
````

The first content slide, as rendered:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/362187/213723798-f72a67b9-6731-421a-ab83-6755fd4b6656.png">

The final content slide, as rendered:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/362187/213723876-14429cab-d7fe-48c4-9b8a-03b0c7291290.png">

The final slide is configured with a background color and the logo SVG does not display.

Note: I originally thought that this was a problem with `background-image`, but the disappearing `logo` appears connected to a background color, not image. My original example was providing both image and color as given in the documentation example <https://quarto.org/docs/presentations/revealjs/#image-backgrounds>

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thank you! This will fixed in our next pre-release available shortly.
