### ISSUE TITLE
Empty slide after title slide in Beamer

### ISSUE THREAD

**Issue by aimundo** [quarto-dev/quarto-cli#4034]
### Bug description

I created a Beamer presentation using Quarto, and noticed there was a blank slide after the title slide. After doing some testing, it seems that this issue is caused by having an R chunk before the first slide (I usually have one chunk before the first slide where I load packages etc). Doing some reading, I found that Pandoc causes this same issue when comments are placed before the first slide (https://tex.stackexchange.com/questions/480125/blank-slide-generated-between-the-title-and-the-first-content-slides-when-using) but I am wondering how having an R chunk plays into this.  For context, I am using a Windows 10 machine and Rstudio 2022.12.0 Build 353.

See repex below:

````
---
title: "repex"
author: | 
  | None
date: "`r Sys.Date()`"
format: 
  beamer:
    incremental: true
keep-tex: true
---

````{r,prepare-data}
#| echo: false
#| warning: false
#| message: false


#some code

z=3+4
````

# Slide 1

- Some text

# Slide 2

- Some text

````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
@aimundo can you format your code correctly with some backticks around code, one more backtick than the chunks as shown in https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us 

This allows to be sure to use the same qmd content as you to reproduce

**Comment by cderv** [comment]
(Thanks @cscheid for the editing)

If you put some content before the first header, it will be accounted for a slide content. For example, if you add return a value in the chunk it would have been expected to be shown in a slide 

Example 
````markdown
---
title: "repex"
author: | 
  | None
date: "`r Sys.Date()`"
format: 
  beamer:
    incremental: true
keep-tex: true
---

```{r,prepare-data}
#| echo: false
#| warning: false
#| message: false
z=3+4
z
```

# Slide 1

- Some text

# Slide 2

- Some text
````

Here z is expecting to be shown, hence a slide for that content
![image](https://user-images.githubusercontent.com/6791940/213791655-6f71663f-a5a0-4431-badc-e91b916c2dfa.png)

> I usually have one chunk before the first slide where I load packages etc).

Why not just do that inside the first slide ? if you have `echo: FALSE` and nothing as output, then it won't clutter your first slide as it is hidden content. 

<details>
<summary>Example</summary>

````markdown
---
title: "repex"
author: | 
  | None
date: "`r Sys.Date()`"
format: 
  beamer:
    incremental: true
keep-tex: true
keep-md: true
---

# Slide 1

```{r,prepare-data}
#| echo: false
#| warning: false
#| message: false
z=3+4
```

- Some text

# Slide 2

- Some text
````

</details>

That being said, I believe we could indeed be more clever in detecting no source code and not output. Currently we got this in  the intermediate markdown for Pandoc 

````markdown
---
title: "repex"
author: | 
  | None
date: "2023-01-20"
format: 
  beamer:
    incremental: true
keep-tex: true
keep-md: true
---


::: {.cell}

:::


# Slide 1

- Some text

# Slide 2

- Some text
````

@cscheid do you agree that this empty `.cell` div should / could be remove when empty ? 

This would prevent such issue in slide format as it creates some content above first title for Pandoc, as said by the OP it causes side effect with Pandoc.

**Comment by aimundo** [comment]
Thanks @cderv, I think I'll follow your advice from now on about putting the content in the first slide. Still, if the slides are made with RMarkdown I don't recall having this same issue, but I'll follow your advice and use the first slide to put the chunk for libraries etc.

**Comment by cderv** [comment]
> Still, if the slides are made with RMarkdown I don't recall having this same issue

No you won't have it with R Markdown because Quarto does some different processing in the intermediary file that R Markdown does not (my last message above).

**Comment by aimundo** [comment]
Got it, I'll close the issue then now. Thanks a lot for your help!

**Comment by cderv** [comment]
I will reopen because I still want to check if we can improve this

**Comment by allenmanning** [comment]
Meeting Notes:  Let's consider just filtering out Empty Cell divs.  Maybe this should be done in Lua.

```
::: {.cell}

::: 
```
