### ISSUE TITLE
Interaction issue with `pander` package as Markdown is not correctly formated in output

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#4057]
Simple example 

````markdown
---
title: "repex"
format: html
keep-md: true
---

```{r}
pander::pander(list("1", "2", 3, c(1, 2)))
```
````

Which gives us this results 

![image](https://user-images.githubusercontent.com/6791940/214011147-dca0577c-ba59-410b-abe8-782413d963e4.png)

Somehow the markdown list is not correctly formatted as sub bullet are introduced. 
Our intermediary md is the one messed up somehow
````markdown
---
title: "reprex"
format: html
keep-md: true
---


::: {.cell}

```{.r .cell-code}
pander::pander(list("1", "2", 3, c(1, 2)))
```

::: {.cell-output-display}
* 1
  * 2
  * _3_
  * _1_ and _2_

<!-- end of list -->
:::
:::

````

The knitted result with `knitr::knit("test.qmd")` gives us correct formatting 
````markdown
---
title: "reprex"
format: html
keep-md: true
---


```r
pander::pander(list("1", "2", 3, c(1, 2)))
```



  * 1
  * 2
  * _3_
  * _1_ and _2_

<!-- end of list -->

````

So some processing somewhere is not correctly parsing.

**Comment by cscheid** [comment]
It looks like we're trim()'ing the string which doesn't work when the first line has meaningful indentation...

**Comment by cscheid** [comment]
Note that this trimming is happening on the _output_ of a call. So it seems it must be happening in our .R files somewhere.

**Comment by norcalbiostat** [comment]
Any update with this?

**Comment by mcanouil** [comment]
It seems not as the current status of the issue is opened.

**Comment by cderv** [comment]
> Note that this trimming is happening on the output of a call. So it seems it must be happening in our .R files somewhere.

The trimming is here @cscheid 
https://github.com/quarto-dev/quarto-cli/blob/d076ea1e07e496ef879c31c1adb645318587ab9d/src/resources/rmd/hooks.R#L891-L904 line 901

We do it for all content we put in `cell-output-display` div. I wonder if removing the trim would break stuff... 

It would probably change some current output but it seems we shouldn't trim... 

What do you think about this ?

**Comment by cscheid** [comment]
@cderv the current behavior is definitely a bug. I would start by replacing `trimws(x)` with `x` in a branch and running the test suite...
