### ISSUE TITLE
Problem with procedural tabset in the pre-release 1.3.124

### ISSUE THREAD

**Issue by Pierre9344** [quarto-dev/quarto-cli#4068]
### Bug description

Hello,

I tried the lastest pre-released 1.3.124 version of quarto and I observed a problem with the tabset in the html format. With the version 1.2.313 my tabset and their content (plot and text) are correctly created. But with the pre-released version the content of the tabset is not show.
I'm using R4.2.2 and RStudio 2022.12.0+353 on windows 11

Here is the code I use to generate my tabset:

````
::: panel-tabset
## LONGMIXR plot

::: {.panel-tabset group="GROUP"}
```{r}
#| results: 'asis'

rm(list = "ls2")
res <- list()
res[["FILES"]] <- ls
for (i in c("ALL", "A", "B", "C")) {
  # create tab for each groups of individuals and prepare the sub-tabs for the different clustering on this group
  cat("### ", i, "\n::: {.panel-tabset group='CLUSTERING'}\n")
  for (j in rownames(ls)) {
    if (!is.na(ls[j, i])) {
      # check if the file exist
      cat("#### ", j, "\n") # create the clustering sub-tabs
      load(ifelse(i == "ALL",
        paste0("./data/", permut, " permut/", ls[j, i]),
        paste0("./data/", permut, " permut/", i, "/", ls[j, i])
      ))
      cat("\n\n")
      plot(cluster_model)
      cat("\n\n")
    }
  }
  cat("\n:::\n") # end CLUSTERING tabset
}
cat("\n:::\n") # end of GROUP tabset
```
:::

## Similarity index

some R plot
````

I trid a simplest code and tt look like the reason is that we can't add a tabset inside another tabset.:

````
::: panel-tabset
### Tab A

Content for Tab A

::: panel-tabset
### sub-Tab A

Content for Tab A

```{r}
plot(1)
```

### sub-Tab B

Content for Tab B
:::

### Tab B

Content for Tab B
:::
````

Would it be possible that in the full release it is possible to add a tabset inside another tabset? I use this feature a lot to present similar figures across different group/timepoint.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I can confirm. This is a regression from a recent change. We'll fix before 1.3 release.
