### ISSUE TITLE
Parsing format string with Pandoc's extensions 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#4080]
I believe we could have an issue in how we parse format and triage between supported Markdown variants and what we call modifiers (e.g `pdf+draft` and `pdf+final`). 

This is what we get when running the command above 
````
> quarto render doc.qmd --to docx+native_numbering

processing file: doc.qmd

output file: doc.knit.md

pandoc
  to: docx
  output-file: doc.docx
  default-image-extension: png

metadata
  title: test

Output created: doc.docx
````

No `native_numbering` in the `to` field for `pandoc`

From debugging within VSCode it seems we are seing `docx+native_numbering` not as the `+native_numbering` variants and then build the wrong format string. 

Talking about this part of the code 
https://github.com/quarto-dev/quarto-cli/blob/main/src/core/pandoc/pandoc-formats.ts#L171-L216

called 
https://github.com/quarto-dev/quarto-cli/blob/main/src/core/pandoc/pandoc-formats.ts#L171-L12

I feel something is not right there but not sure as it seems the list to detect variants was built on the Markdown format supported ones. 
https://github.com/quarto-dev/quarto-cli/blob/main/src/core/pandoc/pandoc-formats.ts#L218

@dragonstyle knows better this part of the code.  If this is confirmed, we should transfer to an issue probably

Note that doing 
````yaml
format: docx
variant: +native_numbering
````

seems to correctly pass the variant as quarto command prints 
````
pandoc 
  to: docx+native_numbering
````

but we document variant only for `markdown` output. 

Hope it helps

_Originally posted by @cderv in https://github.com/quarto-dev/quarto-cli/discussions/4020#discussioncomment-4732171_

**Comment by cderv** [comment]
Cool ! Thanks @dragonstyle  ! 

I'll check with the `docx` example that it works better now;

**Comment by cderv** [comment]
@dragonstyle I don't think a variant passed to format gets picked up. I think it is pretty rare usage, and maybe we should not support but I am curious why this does not work and if we have an issue.

Example 

* `test2.qmd`
````markdown
---
title: test
format: docx+native_numbering
---

![R Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/R_logo.svg/724px-R_logo.svg.png)
````

Convert with pandoc 

```
# No numbering of figure 
quarto pandoc test2.qmd --to docx -o test2.docx -f markdown
```
![image](https://user-images.githubusercontent.com/6791940/214538711-2113f2a1-8a7a-4988-b70d-39e5534db6f8.png)

````
quarto pandoc test2.qmd --to docx+native_numbering -o test2.docx -f markdown
````
![image](https://user-images.githubusercontent.com/6791940/214538807-ca055023-51d7-4609-a972-455f261a0ef8.png)


Now with Quarto 
````
> quarto render test2.qmd
pandoc
  to: docx
  output-file: test2.docx
  default-image-extension: png

metadata
  title: test

Output created: test2.docx
````
![image](https://user-images.githubusercontent.com/6791940/214539215-25935e8c-6ef9-4601-b1d5-7711231ecb7b.png)

The extensions variant is not taken into account. Same with `quarto render test2.qmd --to docx+native_numbering`

It seems it is working ok with `from` key - I can see the extension
````
pandoc 
  to: html
  from: markdown-task_lists
````

So I wonder what are we supporting in `to` exactly ? Both Pandoc's extensions (that we call variants) and modifiers ?

Am I missing something or should this indeed work ? 

Sorry for the trouble with this

**Comment by cderv** [comment]
FWIW I can get the variant to apply by using `variant` key, but I really don't think this is supported for other than `markdown` format (https://quarto.org/docs/reference/formats/markdown/commonmark.html#format-options) 

<details>
<summary>with lhs example from above</summary>


```` 
format: 
  html:
    variant: +literate_haskell
````
as I see in CLI terminal 
````
pandoc 
  to: html+literate_haskell
````

But we loose any formatting, probably because the format is no more HTML and Theming does not get picked up
![image](https://user-images.githubusercontent.com/6791940/214547196-34e57ff7-cbc3-40ae-818a-0bf6e44fff3d.png)

</details>

We probably introduce the modifier for 1.3 PDF (https://quarto.org/docs/prerelease/1.3/pdf.html#filenames-with-modifiers) and this has side effect depending how users are trying to use it. Better be aware. 

Maybe some YAML schema updated or fail safe if something is provided ? 

Happy to discuss this further.

**Comment by dragonstyle** [comment]
This is correct- we are discarding the format variants in `formats.ts` once we determine the writer format (it has been this way for a while). A couple of additional notes:

1) We can take a look at potentially letting  those modifiers through, but will need to review this change carefully as we've been ignoring those in the `to` string for some time and I don't fully understand the downstream consequences of this change. Alternatively when we are getting the default writer format, we could also collect those variants and place them in the format's targetFormat.variants which will be used downstream.

2) When you use the `variants` key, we are ultimately forming the correct pandoc.to but we are passing that through our functions to determine if the output is HTML and this failing since it is performing a simple string match. We should fix this to use the base format, most likely.

**Comment by cderv** [comment]
My understanding is now that 

* we don't support setting Pandoc's extensions for our format in `to`
* we support setting Pandoc's extensions for our format with `variants` but it applies only to markdown output format as documented - **Should our YAML intelligence detect that maybe ?**
 
I feel it is not a bug but a limitation for now. Maybe this is a topic for 1.4 if we want to change this. What do you think ?

**Comment by cderv** [comment]
I believe this was fixed by https://github.com/quarto-dev/quarto-cli/commit/075919d80956897e791be54dd5113492f77bfb80 but somehow another commit is linked above but not merged in main, so this issue was not closed. 

I'll close this as I verified it works ok now.
