### ISSUE TITLE
Cannot find `rmarkdown` package from a user library

### ISSUE THREAD

**Issue by PierreMasselot** [quarto-dev/quarto-cli#4081]
### Bug description

I am trying to use Quarto from my work computer in which I cannot write in the usual `C:/Program Files/R/R-4.2.2/library` and use a personal library instead (let's say `C:/user/r-lib`). I have therefore installed the `rmarkdown` package there.

When trying to render a document with Quarto, it cannot find the `rmarkdown` package as it is not in the system library. A `quarto check` command returns

```
$ quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.269
      Path: C:\Program Files\RStudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.2
      Path: C:/PROGRA~1/R/R-42~1.2
      LibPaths:
        - C:/Program Files/R/R-4.2.2/library
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

I wonder if it is possible to add my user library in the LibPaths checked by Quarto? Note that it is returned by the `.libPaths()` command in R.

I am using RStudio 2022.12.0 Build 353 on Windows 10.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mcanouil** [comment]
Depending on your working directory settings (see <https://quarto.org/docs/projects/code-execution.html#working-dir>, adding an `.Rprofile` in it with the proper `.libPaths(c("/custom/path/library", .libPaths())` should work as expected.

You could also use `renv` which uses the same "trick".

**Comment by PierreMasselot** [comment]
It works thanks! I had it in the default directory and the user library path was showing in `.libPaths()` but with this method Quarto is also able to find it.

Thank you for the help.
