### ISSUE TITLE
Code annotation doesn't work in some languages

### ISSUE THREAD

**Issue by seeM** [quarto-dev/quarto-cli#4091]
### Bug description

This doesn't work on Quarto v1.3.124 on macOS 13.0.1:

    ```swift
    let foo = "bar" // <1>
    ```

    1. Test

The code block is rendered with the `// <1>` as if it were standard code, and the ordered list a standard list.

Changing the `// <1>` to `# <1>` doesn't work either. Neither does changing `swift` to `javascript`. Changing it to `python` or `r` works, but syntax highlighting is wrong.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thanks for reporting this - it will be fixed in our next pre-release build via

https://github.com/quarto-dev/quarto-cli/commit/d06e936242f00305e40e7185b75728be306d54dd

**Comment by seeM** [comment]
Thanks for the quick response! I'm loving these new features 😄
