### ISSUE TITLE
Multiple Python environments in the same project

### ISSUE THREAD

**Issue by betolink** [quarto-dev/quarto-cli#41]
I'm currently working on a project that tentatively will have many contributors and each chapter will probably use its own python environment. Right now Quarto uses the active environment to render the final output and I wonder if there is a way that Quarto can be environment aware, i.e. each chapter or sub directory could have a  `.python-version` that can be activated by Quarto (Conda or pyenv). It will be up to the users to install these environments, Quarto will only activate them to render the output.

**Comment by jjallaire** [comment]
I think the way to go here is to use a combination of `freeze` and sub-directory local virtual environments. I've written up how to do this here:

https://quarto.org/docs/getting-started/quarto-projects.html#code-execution

Note you need the very latest build of quarto for this to all work as documented (we needed to add a feature for rendering sub-directories within projects): https://github.com/quarto-dev/quarto-cli/releases

What's nice about `freeze` is that it gives you ironclad protection that your entire book will render (e.g. on a CI server) and that collaborators won't need to fully reproduce each other's virtual environments. Let me know if you think this will do what you need.

**Comment by betolink** [comment]
Nice, this is what I was looking for. I'm going to test it as soon as possible. Thanks!

**Comment by betolink** [comment]
Hi @jjallaire I just tested the latest build and Quarto is now able to render a local directories without touching the parent locations (yay!).

Now just to clarify this workflow, say that there are 2 teams each with its own environment. Ideally each team will render their part locally and commit it to the repo (content of `_freeze`). Does this mean that CI shouldn't try to render the whole output? otherwise the CI configuration will have to take into account these differences and render `team_A` using team's A environment and `team_B` using team's B environment. Is this correct?

**Comment by jjallaire** [comment]
It depends on what you are looking for from CI -- by default CI can definitely render the whole site (it won't actually execute any code b/c all of the execution results are already in `_freeze`). For a site that has hundreds of pages and/or several major contributors **and** which has content contributed at varying times (even spanning years) the idea that CI would be able to successfully re-execute it all might be a bit optimistic.

However, if you want CI to execute it all you can certainly do that! You would just need to orchestrate those executions. For example, if you have `team_a` and `team_b` directories in a site it might go like this:

```bash
# execute team_a code
cd team_a
python3 -m venv env
source env/bin/activate
python3 -m pip install -r requirements.txt
quarto render

# execute team_b code
cd ../team_b
python3 -m venv env
source env/bin/activate
python3 -m pip install -r requirements.txt
quarto render

# now render the entire site
cd ..
quarto render
```

**Comment by betolink** [comment]
Yup, this is what I had in mind to handle our CI builds. I'm closing the issue as there is a clear path forward to handle multiple environments. Thanks for the help, Quarto is looking great!

**Comment by jjallaire** [comment]
@betolink, I'm curious as to what your execution model is for these sub-projects. I believe that your main project has `ipynb: false` set, which means that if you are authoring in ipynb there is no execution happening anyway (since it all happens in the juptyer notebook).

Note that you can override this behavior when doing a project-level render with this:

```bash
quarto render --execute
```

Note that you'd definitely want to do that on CI as well if you have `ipynb: false` defined.

So if you wanted the incremental workflow of using jupyter to execute for individual notebooks, but then always make sure you can fully re-execute them in a clean session.

Another alternative would be to set `execute: true` within the metadata of individual notebooks to override the global default. I guess the final alternative would be to remove the `ipynb: false` from the global config if you prefer to execute from `quarto render`.

**Comment by betolink** [comment]
Yeah, as it is right now we are not executing ipynbs as you noticed. Depending on how we decide to handle our team environments this may change. IMO it will be nice if CI can handle this orchestration, this way we'll make sure the code in our notebooks can be successfully executed. And of course there are some cases that require a particular deployment to work so maybe those will have to be rendered in place and skipped in CI etc.
