### ISSUE TITLE
Page navigation shows chapter number when "number-sections: false" set

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#410]
Quarto 0.9.30 on Linux.

When I set "number-sections: false" in the html section of _quarto.yml in a book project, chapter numbers as expected are not shown in headers or table of contents, but they are shown in the page navigation links at the bottom of each page.

This can be reproduced simply by creating a new book project, adding "number-sections: false" in the html section of _quarto.yml, then using quarto preview to view the book project site.

**Comment by jjallaire** [comment]
Should be resolved here: https://github.com/quarto-dev/quarto-cli/commit/b0f54aab054dd6e97920483b4e16890ff559dfde

**Comment by blacksqr** [comment]
Still occurs in Quarto 0.9.140

**Comment by dragonstyle** [comment]
I was able to reproduce this as well - I'll have a look!

**Comment by dragonstyle** [comment]
This should be fixed here: f5152c9e3e73e15d0bbf28f77b018730a2a9b5ed

I have a fresh release being built - thanks for following up on this!
