### ISSUE TITLE
Issue with renderring Quarto hellp.qmd file

### ISSUE THREAD

**Issue by SelinaS37** [quarto-dev/quarto-cli#4103]
I tried to use Quarto for schoolwork and I have Rstudio 2022.07.1 installed. Also, I downloaded the latest version of Quarto v1.2.313. I tried to use Rstudio and Powershell to render and both gives me the same results and error message. I posted it on the Rstudio Community and I got an answer that it might because my computer language is not in UTF-8 and the ??? is some character in non-English language.

Here is the error message:
-------------------------------------------------------------
Error running filter C:/Quarto/share/filters/quarto-finalize/quarto-finalize.lua:
[string "..."]:268: cannot open file 'C:\Users\?????\AppData\Local\Temp\quarto-session5c7e9c46\44cf15db\7c187dce' (Invalid argument)
stack traceback:
        [string "..."]:268: in function 'io.lines'
        [string "..."]:1476: in field 'processDependencies'
        C:/Quarto/share/filters/quarto-finalize/quarto-finalize.lua:41: in function <C:/Quarto/share/filters/quarto-finalize/quarto-finalize.lua:38>

**Comment by dragonstyle** [comment]
This does look like it is potentially a path issue related to your system encoding. We attempt to respect this but perhaps it isn't working in this case. Can you try a couple of things:

1) Find your system encoding by using the `chcp` command from the CMD.exe terminal. This should print the active code page.

2) Run the command `quarto check` just to see whether there are other errors in play.

**Comment by SelinaS37** [comment]
My active code page is 936 and the quarto check provides the following:

[>] Checking Quarto installation......OK
      Version: 1.2.313
      Path: C:\Quarto\bin
      CodePage: unknown

(|) Checking basic markdown render....Error running filter C:/Quarto/share/filters/quarto-finalize/quarto-finalize.lua:
[string "..."]:268: cannot open file 'C:\Users\?????\AppData\Local\Temp\quarto-sessiond59fbdba\deacc1d4\49164bd2' (Invalid argument)
stack traceback:
        [string "..."]:268: in function 'io.lines'
        [string "..."]:1476: in field 'processDependencies'
        C:/Quarto/share/filters/quarto-finalize/quarto-finalize.lua:41: in function <C:/Quarto/share/filters/quarto-finalize/quarto-finalize.lua:38>
[>] Checking basic markdown render....OK

Thanks!

**Comment by cderv** [comment]
For reference related Community post https://community.rstudio.com/t/error-when-first-using-quarto/157366

**Comment by dragonstyle** [comment]
I'm stumped. I just configured a local Windows 11 installation to use codepage 936 and placed both the Quarto installation and test document in a folder using unicode characters and didn't have any issues with rendering (either via powershell or the built in terminal in RStudio.

The biggest clue that I see is that the codepage is displaying as `unknown` when you are running `quarto check` whereas it appears in my case we're detecting the codepage properly. 

We find the code page by reading this registry value:

```
    const value = await registryReadString(
      [kHKeyLocalMachine, kHKeyCurrentUser],
      "SYSTEM\\CurrentControlSet\\Control\\Nls\\CodePage",
      "ACP",
    );
```

and then cache that in 

```
%LOCALAPPDATA%\quarto\codepage
```

Can you see whether that file exists and what the value for that file is? If that file exists, could you try deleting it and rendering again to attempt to trigger us to re-detect the code page?

**Comment by cderv** [comment]
@SelinaS37 here are some command you can run in Powershell so that we can see what is configured on your environment 

````powershell
# The property we use - at least one of them should return a value
Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage" -Name ACP
Get-ItemPropertyValue -Path "HKCU:\SYSTEM\CurrentControlSet\Control\Nls\CodePage" -Name ACP

# The key we need 
Get-ChildItem -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage"
Get-ChildItem -Path "HKCU:\SYSTEM\CurrentControlSet\Control\Nls\CodePage"


# All properties available 
Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage"
Get-ItemProperty -Path "HKCU:\SYSTEM\CurrentControlSet\Control\Nls\CodePage"
````

You can try run them and see if this give you something.
