### ISSUE TITLE
Why flextables won't show after render

### ISSUE THREAD

**Issue by dax44** [quarto-dev/quarto-cli#411]
I try to use 'flextable' package function to create table in quarto file, but after rendering to html file the table won't show. I wrote the following code

```
mtcars |> 
  flextable::flextable()
```

and I've got only R code without table
<img width="589" alt="Zrzut ekranu 2022-03-12 o 21 48 16" src="https://user-images.githubusercontent.com/8738353/158034509-b63f2ccb-4418-44de-ac21-bc022dcce932.png">

Please help

**Comment by jjallaire** [comment]
That definitely should work! We'll investigate and hopefully find a fix very soon.

**Comment by dax44** [comment]
Thank you. I'll wait for any news

**Comment by jjallaire** [comment]
Should now be resolved w/ this: https://github.com/quarto-dev/quarto-cli/commit/d2b4ea25624a143572556c67ee29587b4443f710
