### ISSUE TITLE
revealjs slides + quarto website publishing issue via github actions due to provisioning multiplex token

### ISSUE THREAD

**Issue by coatless** [quarto-dev/quarto-cli#4117]
### Bug description

When using the quarto Render/Publish GitHub Action to create a quarto website embedded with Revealjs slides, I'm receiving: 

```
ERROR: Error attempting to provision multiplex token from 'https://reveal-multiplex.glitch.me/': Unexpected token '<', "<html>
<h"... is not valid JSON

Error: Error: Error attempting to provision multiplex token from 'https://reveal-multiplex.glitch.me/': Unexpected token '<', "<html>
<h"... is not valid JSON
    at revealMultiplexToken (file:///opt/quarto/bin/quarto.js:73046:15)
    at async postprocessors (file:///opt/quarto/bin/quarto.js:72986:35)
    at async renderPandoc (file:///opt/quarto/bin/quarto.js:69679:13)
    at async Object.onRender (file:///opt/quarto/bin/quarto.js:79336:32)
    at async renderFiles (file:///opt/quarto/bin/quarto.js:78709:21)
    at async renderProject (file:///opt/quarto/bin/quarto.js:78844:25)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:79396:32)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:4107:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:107017:5)
    at async file:///opt/quarto/bin/quarto.js:107028:9
Error: Process completed with exit code 1.
```

Visiting the URL:

```
https://reveal-multiplex.glitch.me
```

Yields:

```
This project has received too many requests, please try again later.
```

Is there a way to embed the necessary multiplex token? 

---

Using:

quarto-1.2.313-linux-amd64.deb 
r-4.2.2_1_amd64.deb
pandoc-2.19.2-1-amd64.deb

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
In our docs: https://quarto.org/docs/presentations/revealjs/presenting.html#multiplex

**Comment by coatless** [comment]
@cscheid I suppose this is more of a request for a better error message.
