### ISSUE TITLE
jupyter_client 8 issues

### ISSUE THREAD

**Issue by JeremyBYU** [quarto-dev/quarto-cli#4122]
Quarto does not work with the latest version of jupyter_client that was recently released.

In the meantime, quarto devs have verified that the issue does not exist with version 7.4.9 of jupyter_client. So if you're a python quarto user, please pin your jupyter_client version to 7.4.9 while we diagnose and fix the issue.

In order to pin a version, the easiest way is to add the following line to your `requirements.txt` file in a venv (or similar)

```
jupyter_client < 8.0.0
```

**Comment by aronatkins** [comment]
I've reproduced this using latest jupyter and recent Quarto (all Quarto versions, perhaps). The jupyter-client had a major release recently and likely broke something with our integration.

```bash
quarto create-project --type default --engine jupyter experiment
```

Contents of `requirements.txt`

```txt
jupyter
nbconvert
ipykernel
```

```bash
python3 -m venv venv
. ./venv/bin/activate
pip install --upgrade setuptools pip
pip install -r requirements.txt
```

With this environment, the `quarto render` never completes;  it sits at `Starting python3 kernel...`

**Comment by cscheid** [comment]
@JeremyBYU we believe this is an interaction with jupyter-client version 8 and later (which was just released). Can you pin your jupyter-client version to 7.4.9 while we fix this?

**Comment by JeremyBYU** [comment]
Yep will do it later today. Thanks for the quick reply!

**Comment by astayleraz** [comment]
This started to show failing in our vs code tests, just like this. 
![Screen Shot 2023-01-26 at 4 57 49 PM](https://user-images.githubusercontent.com/1482677/215131963-c1fb6bc4-f57b-4c47-87a7-cacf0c875799.png)

**Comment by cscheid** [comment]
@astayleraz Can you try pinning jupyter-client to 7.4.9?

**Comment by cscheid** [comment]
@aronatkins Thank you for that very short repro! I can see it locally as well.

**Comment by cscheid** [comment]
@JeremyBYU I'm taking the liberty to edit your issue to make it easier for other folks to find a quick workaround. I hope that's ok with you.
