### ISSUE TITLE
Custom font and Latex 's \text{} error

### ISSUE THREAD

**Issue by vfacta** [quarto-dev/quarto-cli#4125]
### Bug description

System: Debian 11

RStudio: RStudio 2022.12.0+353 "Elsbeth Geranium". All packages up to date, using default quarto (could not check version)

In quarto book, using text commands inside equations, such as \text{} or \mathrm{}, produces a fatal error when a custom main font is used. Below, a code example:

```
\begin{align*}
a^n &=  \underbrace{a \cdot a \cdot a \cdot \ldots}_{n \text{ times}} \\ \\
a^n &= p
\end{align*}
```
In the yml file, the main font is set to EB Garamond:

```
pdf:
    mainfont: EB Garamond
```

This will generate the following error:

```
  This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/Debian) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
  xdvipdfmx:fatal: Cannot proceed without the font: /usr/share/fonts/woff/ebgaramond/EBGaramond08-Regular.woff
  
  No output PDF file written.
```

The removal of the \text command in the equation outputs a pdf file with no error and correct custom font.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Do you have the required font file installed?

**Comment by vfacta** [comment]
In the path  /usr/share/fonts/woff/ebgaramond, i have the current files:

EBGaramond08-Italic.woff  
EBGaramond-InitialsF1.woff
EBGaramond08-Regular.woff  
EBGaramond-InitialsF2.woff
EBGaramond12-AllSC.woff    
EBGaramond-Initials.woff
EBGaramond12-Bold.woff     
EBGaramondSC08-Regular.woff
EBGaramond12-Italic.woff   
EBGaramondSC12-Regular.woff
EBGaramond12-Regular.woff

**Comment by cscheid** [comment]
That's strange. Is it possible that these were installed with different permissions somehow? I don't quite understand how the file could be there while xdvipdfmx successfully uses the _other_ files in that directory. One thing you can attempt is to use quarto to produce a latex file (`format: latex`), and then try to render that file with the latex command-line chain, and see if the error persists.

**Comment by vfacta** [comment]
I checked with `ls  -l` in the folder and all files have the same permission (`-rw-r--r--`)

**Comment by dragonstyle** [comment]
As @cscheid suggests, I think that you might want to try adding `keep-tex: true` to your document (this will keep the tex artifacts around when producing the PDF) then use tex directly to attempt to create the PDF (e.g. run `xelatex <mydoc.qmd>` from the terminal) and see whether you see the same error.

**Comment by vfacta** [comment]
Producing a PDF file with `xelatex` directly from a .tex file, with `\setmainfont{EB Garamond}` command, resulted in `! File ended while scanning use of \@writefile.`

However, there where no errors when using `lualatex`.

I went to back to RStudio and changed the `pdf-engine` to `lualatex`, which also produced a PDF with the correct font when rendering book.

**Comment by cscheid** [comment]
> However, there where no errors when using `lualatex`.

This seems to be a LaTeX setup issue. then. I'm going to go ahead and close this one. Please re-open if you haven't solved it or you believe it to be a Quarto bug.
