### ISSUE TITLE
Error including shiny app in quarto website

### ISSUE THREAD

**Issue by asalber** [quarto-dev/quarto-cli#4130]
### Bug description

Hi!
I want to incluye a small Shiny app in a page of a website generated with quarto. To reproduce the error, create a new quarto website project with Rstudio.
This is the source code of the `index.qmd` file.

````
---
title: "Old Faithful"
format: html
server: shiny
---

```{r}
sliderInput("bins", "Number of bins:", 
            min = 1, max = 50, value = 30)
plotOutput("distPlot")
```

```{r}
#| context: server
output$distPlot <- renderPlot({
  x <- faithful[, 2]  # Old Faithful Geyser data
  bins <- seq(min(x), max(x), length.out = input$bins + 1)
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```
````

And this is the `_quarto.yml` generated by default by Rstudio.
````
project:
  type: website

website:
  title: "web-shiny"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
````

When I render de website, I get the error
```
Error in shiny_prerendered_html(input_rmd, render_args) : 
  Prerendered HTML file not found at /run/media/tmp/quarto/web-shiny/index.html
Calls: .main ... <Anonymous> -> shiny_prerendered_app -> shiny_prerendered_html
Execution halted
```

I am running quarto version 1.2.313 and Rstudio version 2022.12.0 Build 353 on Arch Linux.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report, but please don't open copies of issues on different repositories :) I've answered your question on the quarto-web issue.
