### ISSUE TITLE
Misformatted Quarto R magic chunk output

### ISSUE THREAD

**Issue by psads-git** [quarto-dev/quarto-cli#4133]
Consider the following `quarto` document:

````
---
title: "Untitled"
format: pdf
jupyter: python3
---

```{python}
#|echo: false

%load_ext rpy2.ipython
```

```{python}
#| result: asis

%%R

x <- c(1, 2)
names(x) <- c('a', 'b')
print(x)
```
````

The output is misformatted:

![x](https://user-images.githubusercontent.com/75945439/214046829-96531b7d-f270-4dc5-9ef1-523852730d5f.png)

**Comment by cscheid** [comment]
You have this:

````
```{python}
#| result: asis

%%R

x <- c(1, 2)
names(x) <- c('a', 'b')
print(x)
```
````

I don't think we support cell magics in .qmd files, especially with `result: asis`; the results are completely unpredictable (for example, this is a "python" cell that actually has R code). If you need to mix R and Python code, consider using the knitr engine and `{r}` and `{python}` cells. knitr will use the `reticulate` package, and we will know how to format things properly
