### ISSUE TITLE
Can't modify Bootstrap theme at all

### ISSUE THREAD

**Issue by jimjam-slam** [quarto-dev/quarto-cli#415]
Hi there! Not sure if I'm misunderstanding how themes are specified, but I can't get them working at all.

`test.qmd`:

```
---
title: "Test test test"
author: "jimjam-slam"
format:
  html:
    theme: darkly
---

Check this out! Woo!
```

Output:

![image](https://user-images.githubusercontent.com/6520659/158100147-d75b1ee6-0839-4af5-966e-482c136a7917.png)

I'm also unable to specify an SCSS file in the `theme` option (it isn't recognised). However, the `css` option is:

`style.css`:

```
body: background-color: red;
```

`test.qmd`:

```
---
title: "Test test test"
author: "jimjam-slam"
format:
  html:
    css: test.css
---

Check this out! Woo!
```

![image](https://user-images.githubusercontent.com/6520659/158100282-0a1d738b-4281-48ec-a9bf-c62f66d621c3.png)

Is there something I'm missing? Thanks very much!

(I'm using Quarto version 0.9.76)

**Comment by cderv** [comment]
Hi, 

This works ok for me when I copy your example: 
![image](https://user-images.githubusercontent.com/6791940/158149472-565f7963-9607-42b4-81e0-01534cba62b5.png)

Regarding using `.scss` file, you need to follow the convention from custom theme 
* https://quarto.org/docs/output-formats/html-themes.html#custom-themes
* https://quarto.org/docs/output-formats/html-themes-more.html

Your SCSS file must contains at leat one special comments as described in the doc. Some SASS variables are also directly implemented so only changing the variable would work without writing the rules

This works for me 
* `style.scss`
````scss
/*-- scss:uses --*/

/*-- scss:functions --*/

/*-- scss:defaults --*/
$body-bg: red;

/* -- scss:mixins --*/

/*-- scss:rules --*/
````
````markdown
---
title: "Test test test"
author: "jimjam-slam"
format:
  html:
    theme: style.scss
---

Check this out! Woo!
````

![image](https://user-images.githubusercontent.com/6791940/158150509-9bdc3279-7fcf-49d6-8784-ca30e5be874e.png)


Maybe you can try update your version ? 

I am using last dev version here.

**Comment by dragonstyle** [comment]
One other thought that could be in play - if you're in the context of a website project, using page specific bootstrap / scss theming will not work (because the theme is being provided by the website for all the pages within it).

**Comment by jimjam-slam** [comment]
@dragonstyle Ahh, that's it! I should've asked about a project—I'd thought that it might be overriding things, but it didn't occur to me it might still override if the project file didn't specify a theme.

Is it possible to explicitly not define a theme in the project file, or to allow specific pages to override theming? In my case, I'm importing an OJS cell into a separate `.qmd` in order to make it embeddable externally (see https://github.com/quarto-dev/quarto-cli/issues/400#issuecomment-1066025754), and I'd like to use `theme: none` alongside the `css` option to keep the embed lean!

If not, no biggie - I can always just run `quarto render --output-dir docs *.qmd` instead of `quarto render`!

**Comment by dragonstyle** [comment]
There is definitely something unexpected happening, because I expect that in a `website` project, the CSS and so on is global, and so it isn't possible to individually theme files. In the case a simple quarto project, however, I'm not sure why the same would be true. I'll look into this and report back...

**Comment by jjallaire** [comment]
It seems like we might want to make an exception whereby `theme: none` is valid even within a website?

**Comment by dragonstyle** [comment]
Quick follow up. We were forcing the theme even when the project type wasn't a website or book (which we shouldn't be doing). I've fixed that here https://github.com/quarto-dev/quarto-cli/commit/4c7a8a3e41d3388260a6b471442f3ca1e3bb531c. You should now be able to make a plain Quarto project of html documents that are all independently themed. Release should be available shortly here: https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.99.

In addition, I double checked that we do allow either `none` or `pandoc` themes even when an html document appears in a website.

**Comment by jimjam-slam** [comment]
Amazing! I'll see if I can update Quarto to give it a crack 😊
