### ISSUE TITLE
Can't embed video using raw Dropbox link

### ISSUE THREAD

**Issue by tobydriscoll** [quarto-dev/quarto-cli#4153]
### Bug description

I am trying to embed videos on a book site using raw links from Dropbox. However, the video shortcode can't seem to parse the URL. For example, if a qmd document tries to include [this video file](https://www.dropbox.com/s/h3ezvnpyn8xe5ch/Section1_4_c.mp4?raw=1) using

````
Here is the video:

{{< video https://www.dropbox.com/s/h3ezvnpyn8xe5ch/Section1_4_c.mp4?raw=1 >}}
````

then rendering complains that "No video source specified for video shortcode".

This is in 1.2.280 on macos Ventura, in an empty default website template.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
@allenmanning I suspect what's happening is that our extension detection code is not taking the `?raw=1` fragment into account.

**Comment by cscheid** [comment]
@tobydriscoll pull requests are always appreciated! Start here: https://quarto.org/about.html#contribute

**Comment by allenmanning** [comment]
Thanks for contributing Toby, I will have a look.

**Comment by allenmanning** [comment]
From my local testing, this seems to be working.  It is accepting the drop-box URL and rendering using Video JS.  I'm adding some testing around this as part of closing this issue.
