### ISSUE TITLE
Footer text colour doesn't change with darker background colours

### ISSUE THREAD

**Issue by Sparrow0hawk** [quarto-dev/quarto-cli#4156]
### Bug description

When using revealjs mode with Quarto if you set a slide to a dark background and include a footer the footer colour does not adjust to the dark background.

The footer appears to be moved outside of the slide section where revealjs sets `has-dark-background` class so it isn't possible to just apply scss logic within `src/resources/formats/revealjs/quarto.scss`.

## Steps to reproduce

Using the [attached file](https://github.com/quarto-dev/quarto-cli/files/10544325/footer-colour.txt) do the following:

```bash
$ mv footer-colour.txt footer-colour.qmd

$ quarto preview footer-colour.qmd
```

## OS Information

I've tested this on the most recent nightly release and still have this issue.

Running on macOS Ventura 13.1.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Hi thanks for reporting an issue. I'm having trouble being sure that we're reproducing what you're seeing. 

When I render the attached file, here is what I see:

![Screenshot 2023-01-31 at 9 05 43 AM](https://user-images.githubusercontent.com/261654/215782287-47bf80a2-3d1f-4c56-931f-aee26981a1f0.png)

which seems correct to me. Can you clarify what you're seeing / what isn't working as expected just to be sure I understand it?

**Comment by Sparrow0hawk** [comment]
Hi @dragonstyle 

Sorry for not being clear, my issue is that the footer text is grey by default regardless of the slide background colour, whereas slide body text changes. 

I'm unsure if the footer text not changing colour is expected behaviour, perhaps it is and what I should be suggesting is an improvement rather than a bug.

**Comment by dragonstyle** [comment]
Ok I see that now, thanks! Let me have a look...

**Comment by dragonstyle** [comment]
We are currently always using `$text-muted` no matter the background color with no special handling for background colors. It would be nice if we better supported this, though it is slightly more tricky than I anticipated. We'll take a look at improving as soon as we can!
