### ISSUE TITLE
number-offset implies number-sections, maybe the later when former is set ? 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#417]
Currently, this won't have effect because sections are not numbered
````markdown
---
titre : "Sans titre"
format:
  html:
    number-offset: [5]
---

# Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.
````

`number-sections` needs to be set explicitly 
````markdown
---
titre : "Sans titre"
format:
  html:
    number-sections: true
    number-offset: [5]
---

# Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.
````

It seems like it was the case in the past when it was implemented: https://github.com/quarto-dev/quarto-cli/commit/7e963f54996ec090271db57395bd230849d76e66 but doesn't seems to be the case anymore.

Was it removed on purpose or lost in refactoring ?

**Comment by jjallaire** [comment]
It does seem to have been removed during refactoring. Here I restore the behavior: https://github.com/quarto-dev/quarto-cli/commit/75bf3c03fc1af5267040cba8e13e6da7216136fb
