### ISSUE TITLE
Rendering a self contained format after a non-self-contained format deletes _files folder needed by first format

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#418]
Assuming a qmd file `index.qmd`

```
---
title: "Test"
format:
  html:
    self-contained: false
---

# Hello

World.
```

Running `quarto render index.qmd -t html` (or `preview`) generates `index.html` and `index_files/` on which it relies.
However, generating a different output format from the same document, e.g. `quarto render index.qmd -t pdf` deletes the `index_files/` folder.

**Comment by jjallaire** [comment]
Thanks for reporting! Should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/c900072528dbe26c676165ebf4768121922f8023

**Comment by jmbuhr** [comment]
I can confirm that this works for pdf output, but what I don't understand is why is doesn't work for
`quarto render index.qmd -t epub`, which still deletes the folder.

**Comment by jjallaire** [comment]
I overlooked one case in my fix, final fix should be here: https://github.com/quarto-dev/quarto-cli/commit/b84978119f357da657a10cd2149abd9e3fe3ac59 (note that this isn't yet in a binary release but should be shortly)

**Comment by jmbuhr** [comment]
Just pulled and can confirm that this fixes the issue.
