### ISSUE TITLE
Missing hyperlink

### ISSUE THREAD

**Issue by randrescastaneda** [quarto-dev/quarto-cli#4188]
### Bug description

Dear Quarto team, 

This issue is on the web. Not on the CLI. I wanted to create the issue in the web repo, but I ended up here. 

In any case, the following url is not working. In fact, the documentation for the citations is missing. 

https://quarto.org/docs/visual-editor/technical.html#citations 

Thanks. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
That URL is working from where I'm trying it. I'm not quite sure what happened on your end. Can you clarify? Thanks!

**Comment by randrescastaneda** [comment]
Thank you for your quick reply. 
I noticed that the problem is browser-dependent. When I try the link in the Brave Browser or Microsoft Edge, it is working fine, but when I try it in Chrome it is not. see the images below. The chrome one does not take me to the right place. I can't even get to the right part of the page by scrolling down. It is as if it disappeared.

I hope this helps... (Maybe the problem is in my machine, but I have no idea how to check for that.)

Best, 

## Brave Browser (working well)
![image](https://user-images.githubusercontent.com/35301997/216391689-18b7e595-3b9e-4bb4-a72f-99dc953d0798.png)
 
## MS Edge (working well)
![image](https://user-images.githubusercontent.com/35301997/216391818-ac1edaa7-3dbe-4efe-9fe7-476e517b8e5c.png)

## Google Chrome (**NOT** working well)
![image](https://user-images.githubusercontent.com/35301997/216392130-0677c0b6-4af2-4382-ad18-9db8101e6c33.png)

**Comment by cscheid** [comment]
I'm on Chrome and this works locally for me:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/285675/216411209-d8390b24-0b7b-4fc6-b96c-e090d926090d.png">

**Comment by randrescastaneda** [comment]
I asked some colleagues to test it on Chrome for Windows in their machines and it worked for them, so I think the problem is in my computer. I have no idea why it does not work on Chrome but it works in other browsers. I wonder it something like that is happening to someone else. The weird thing is that this behavior only happens in this particular link.... 
Thanks for the help. You can close this issue now. Best,
