### ISSUE TITLE
Speaker notes are printed in pdf output

### ISSUE THREAD

**Issue by rmcd1024** [quarto-dev/quarto-cli#4189]
### Bug description

Speaker notes print in pdf output. They are appropriately hidden in html output. This illustrates the issue:
````
---
title: Test
format: pdf
---

# A section head

Some text

::: {.notes}
Hidden speaker notes
:::

````
Attached are a qmd file and output:
[quarto-issue-speaker-notes.zip](https://github.com/quarto-dev/quarto-cli/files/10564504/quarto-issue-speaker-notes.zip)

This is using quarto version 1.3.146 (also occurred in earlier 1.3 versions) under Ubuntu 22.04. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I think there's a bit of confusion here. In html format, `.notes` doesn't hide the output:

````
---
format: html
---

::: {.notes}
Hello.
:::
````

<img width="299" alt="image" src="https://user-images.githubusercontent.com/285675/216253772-bdacf144-76f7-41df-bb33-cb89ff1f5a6e.png">

In a _presentation_, `.notes` denotes speaker notes (and are hidden). But in a regular document, `.notes` is simply a class applied to the span or div. That's the same thing that happens for a PDF document. This is the intended behavior.
