### ISSUE TITLE
Cannot generate separate Markdown cells in Jupyter

### ISSUE THREAD

**Issue by syclops** [quarto-dev/quarto-cli#4195]
### Bug description

From #3847, it seems like it should be possible to use fenced divs to indicate that a section of Markdown in .qmd should be converted into two separate Markdown cells in Jupyter, but this does not seem to be the case.

Tested on Quarto v1.2.335, on both Arch Linux and Ubuntu 22.04.

Here is a sample file `simple.qmd`:

```markdown
---
title: Simple version
---

# Lorem ipsum

**Lorem ipsum** dolor sit amet, consectetur adipiscing elit. Nunc luctus
bibendum felis dictum sodales.

:::::: {.cell .markdown}
# Lorem ipsum

**Lorem ipsum** dolor sit amet, consectetur adipiscing elit. Nunc luctus
bibendum felis dictum sodales.
::::::
```

Expected Jupyter notebook after running `quarto convert simple.qmd`:

```json
{
  "cells": [
    {
      "cell_type": "raw",
      "metadata": {},
      "source": [
        "---\n",
        "title: Simple version\n",
        "---"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Lorem ipsum\n",
        "\n",
        "**Lorem ipsum** dolor sit amet, consectetur adipiscing elit. Nunc luctus\n",
        "bibendum felis dictum sodales.\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "\n",
        "# Lorem ipsum\n",
        "\n",
        "**Lorem ipsum** dolor sit amet, consectetur adipiscing elit. Nunc luctus\n",
        "bibendum felis dictum sodales."
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3 (ipykernel)",
      "language": "python",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
```

Actual Jupyter notebook output (`simple.ipynb`):

```json
{
  "cells": [
    {
      "cell_type": "raw",
      "metadata": {},
      "source": [
        "---\n",
        "title: Simple version\n",
        "---"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Lorem ipsum\n",
        "\n",
        "**Lorem ipsum** dolor sit amet, consectetur adipiscing elit. Nunc luctus\n",
        "bibendum felis dictum sodales.\n",
        "\n",
        ":::::: {.cell .markdown}\n",
        "# Lorem ipsum\n",
        "\n",
        "**Lorem ipsum** dolor sit amet, consectetur adipiscing elit. Nunc luctus\n",
        "bibendum felis dictum sodales.\n",
        "::::::"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "name": "python3",
      "language": "python",
      "display_name": "Python 3 (ipykernel)"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
```

As a side note, the command mentioned in #3847 (`quarto convert simple.qmd --to ipynb`) does not work, and the `--to` option does not appear in the output of `quarto help convert`. It may be that there's another setup step or command flag that I've missed, but I couldn't seem to find a fix.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
> As a side note, the command mentioned in https://github.com/quarto-dev/quarto-cli/issues/3847 (quarto convert simple.qmd --to ipynb) does not work, and the --to option does not appear in the output of quarto help convert. It may be that there's another setup step or command flag that I've missed, but I couldn't seem to find a fix.

That comment came from one of our users, and the command is incorrect: it's `quarto render file --to format`.

**Comment by cscheid** [comment]
For context:  my comment on #3847 was responding to the _conditional content_ part of the comment, not the "make a cell". My impression is we do not intend `.cell` to denote "render this into a separate .ipynb cell".

**Comment by cscheid** [comment]
Update:

We currently _do_ have a `convert` command, `quarto convert foo.qmd`, which converts a .qmd file to .ipynb.

We also have a `quarto render foo.qmd --to ipynb`, which goes through which I can confirm is a different codepath that generates different output for your input. I'm pretty sure we are not going to change the behavior of `quarto render --to ipynb`, so if that works in your case, you're safe to use it in your future. But I'll get back to you about the intended differences between `convert` and `render` in this cas.e

**Comment by cscheid** [comment]
I've now talked with the other quarto devs.

@lexnederbragt: we won't change that behavior, that's intended on `quarto render`

@syclops: the difference between `quarto convert` and `quarto render` is that `quarto convert` produces a document that is intended to be used as _input_ for the rest of our pipeline (there are use cases when folks want to use .ipynb as inputs because of their project pre-render scripts, for example). `quarto convert` will not actually create those cells (by design, because we are purposefully not going through the jupyter+pandoc chain), but `quarto render` will. So you should simply continue to use `quarto render` and that behavior won't change.
