### ISSUE TITLE
Code annotation disables copy code button

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#4196]
### Bug description

Code annotations disable the "copy code" button.

````
---
format: html
---

Code without annotation - has code copy button on hover:
```r
1 + 1
```

Code with annotation - no code copy button:
```r
1 + 1 # <1>
```
1. Arithmetic
````

I think it makes sense for the copy to exclude the annotation. So "copying"  second chunk should give just contents of the first chunk:
```r
1 + 1
```

Dev Quarto, Mac OS, RStudio Version 2022.12.0+353 (2022.12.0+353)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Note to self: gutter for annotations is overlaying the code copy button. Perhaps need to tinker with z-index for button.

**Comment by dragonstyle** [comment]
This should be fixed in the latest prerelease - thanks for letting me know!
