### ISSUE TITLE
suggestion: site/book creation should .gitignore _site/_book

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#42]
The `_site`/`_book` directories should be added to the `.gitignore` when initializing a new website/book.

```
quarto create-project my-site --type site
echo _site >> my-site/.gitignore

quarto create-project my-book --type book
echo _book >> my-book/.gitignore
```

**Comment by jjallaire** [comment]
I think that many users want to render and check in to version control for "push to deploy" scenarios where they don't re-render on CI. For example, you can't currently run `quarto render` on Netlify so your only choice if you want easy git push triggered deployments is to check `_site` into version control. It's also often the case that even if you can run `quarto render` on CI you have specialized data access or dependencies installed on the dev workstation such that you still want/need to render locally and check in.

Not saying these patterns are ideal or even the majority case, but they are prevalent enough that I don't think we should ignore those directories by default. I do however think that we should include docs on deployment that emphasize the desirability of git ignoring these directories once you have the right configuration (note that we are also creating pre-packaged github actions for pushing to GH Pages and Netlify and will certainly emphasize .gitignore of `_site` there.

**Comment by aronatkins** [comment]
This all makes sense. Withdrawing my suggestion given the frequent commit-the-result workflow.
