### ISSUE TITLE
Feature request: allow About content to be assigned to a div

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#420]
It would  be nice to be able to use the "About Page" feature to design a hero banner for the top of a page that has additional content below it.

It would, for example, be helpful if the "About" feature had the same flexibility as the "Listing" feature; i.e., an option for the feature code to appear in a specified div block in addition to the option for a dedicated page.

That is, I'd like to be able to write a index.qmd file that looked something like the following:

```
---
about:
  id: herobanner
  template: trestles
  image: profile.jpg
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: https://github.com
---

::: {#herobanner}
Finley Malloc is the Chief Data Scientist at Wengo Analytics. When not innovating on data platforms, Finley enjoys spending  time unicycling and playing with her pet iguana.

## Education

University of California, San Diego | San Diego, CA
PhD in Mathematics | Sep 2011 - June 2015

Macalester College | St. Paul MA
B.A in Economics | Sep 2007 - June 2011

## Experience

Wengo Analytics | Head Data Scientist | April 2018 - present

GeoScynce | Chief Analyst | Spet 2012 - April 2018
:::

Additional markdown content here
```

**Comment by dragonstyle** [comment]
Hi- thanks for the suggestion. This should be supported started in this release (building now) https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.94

We will continue to support about pages with no id, but if you do provide an id, we will use the contents of the div with that id to create the about content and position the about page contents in the same position as the div.
