### ISSUE TITLE
Error installing Quarto extension

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#4203]
### Bug description

I'm getting an error when trying to install the `parse-latex` extension available [here](https://github.com/tarleb/parse-latex).

Here is the error message from running `quarto install extension tarleb/parse-latex`:
```
Quarto extensions may execute code when documents are rendered. If you do not
trust the authors of the extension, we recommend that you do not install or
use the extension.
 ? Do you trust the authors of this extension (Y/n) » Yes
[>] Downloading
parse-latex-main/parse-latex.lua: Can't create '\\\\?\\C:\\Users\\au234616\\AppData\\Local\\Temp\\quarto-sessionb2f134f6\\4905fc74\\a45d7e9e\\archive\\parse-latex-main\\parse-latex.lua'
tar: Error exit delayed from previous errors.
[>] Unzipping
ERROR: Failed to unzip extension.
parse-latex-main/parse-latex.lua: Can't create '\\\\?\\C:\\Users\\au234616\\AppData\\Local\\Temp\\quarto-sessionb2f134f6\\4905fc74\\a45d7e9e\\archive\\parse-latex-main\\parse-latex.lua'
tar: Error exit delayed from previous errors.
```

This is running Quarto 1.3.142 on Windows 10. Any ideas what's causing this error?

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
@snhansen I can't reproduce this. I am using 1.3.151. 

> tar: Error exit delayed from previous errors.

You are on Windows right ? Is this happening in a specific shell on Windows ? 

Can you share what is the `tar` used ? In powershell you can run 
```
Get-Command tar
```

I am trying to understand the difference in environment that leads to this. 

@dragonstyle It is possible that `tar` is not available on all windows and I am wondering if we should instead download the .zip archive on windows instead of `.tar.gz` always for remote github extension. You see what I mean ? 

I can make a change for this - what do you think ?

**Comment by cderv** [comment]
Interesting - I can't reproduce your issue on my Windows, but it seems I got an update `tar` 
````powershell
> gcm tar

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     tar.exe                                            10.0.2262… C:\Windows\System32\tar.exe

> (gcm tar).Version                                                                                                     
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      22621  1
````

The version you have could be broken somehow... I don't know if / how you can update 

Anyway, this tool is available in Windows 10 (1903) [from build 17063 or later](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows). So maybe we should have another default it is fails like in your case 🤔 

Thanks for the report

**Comment by snhansen** [comment]
Just tried a different machine also running Windows 10 where I'm getting the same error. The `tar` version appears to be the same:
```
PS C:\Users\stefan> (gcm tar).version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19041  1466
```

I can't seem to figure out a way to update `tar`. How did you manage to get on a different build than me?

**Comment by cderv** [comment]
Maybe I get a higher Windows version ? 
````
> Get-ComputerInfo | select OsName, OsVersion, WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer

OsName                     : Microsoft Windows 11 Professionnel
OsVersion                  : 10.0.22621
WindowsProductName         : Windows 10 Pro
WindowsVersion             : 2009
OsHardwareAbstractionLayer : 10.0.22621.819
````

I can't find versions or release notes anywhere. As a workaround, you can probably use another tar.exe and put in PATH. 

However, I still believe we need to improve this for Windows as this could happen again on older windows, if this is indeed related. Can't test for sure unless you manager de update somehow.

**Comment by snhansen** [comment]
Yup, that's the difference:
```
OsName                     : Microsoft Windows 10 Education
OsVersion                  : 10.0.19044
WindowsProductName         : Windows 10 Education
WindowsVersion             : 2009
OsHardwareAbstractionLayer : 10.0.19041.2251
```
Couldn't get it work with a different `tar.exe`, so I just ended up using Debian via WSL which worked without any hassle.

**Comment by cderv** [comment]
Thanks for the confirmation. We'll fix this by not using `tar.exe` by default on Windows for extension. thanks

**Comment by snhansen** [comment]
@cderv: Great. Can confirm that it works now. Cheers.

**Comment by cderv** [comment]
Awesome thank you for confirming!

**Comment by cderv** [comment]
> ```
>  [>] Checking Quarto installation......OK
>      Version: 1.3.142
>```

The fix done in https://github.com/quarto-dev/quarto-cli/pull/4665 is available from v1.3.249 - you are using an older version so this is expected that you have the same issue. 

Please do check you version when you have an issue, and do update at least to the last release https://quarto.org/docs/download/

**Comment by dragonstyle** [comment]
I just gave the same extension a try on a local windows 10 machine without issue - here is my powershell commands and output:

```
PS C:\Users\User\test> quarto add pandoc-ext/section-bibliographies

Quarto extensions may execute code when documents are rendered. If you do not
trust the authors of the extension, we recommend that you do not install or
use the extension.
 ? Do you trust the authors of this extension (Y/n) » Yes
[>] Downloading
[>] Unzipping
    Found 1 extension.

The following changes will be made:
pandoc-ext/section-bibliographies   [Install]   0.0.1 (filter)
 ? Would you like to continue (Y/n) » Yes

[>] Extension installation complete.
Learn more about this extension at https://www.github.com/pandoc-ext/section-bibliographies
```

It makes me think that there is something different between our test cases in your environment. I'm not sure what that would be however-  it seems that we're somehow failing while unzipping into a working temp directory that we've created, so I'm not sure what in the environment would cause this. Are there anti-malware and anti-virus tools in play that may be blocking the writing of a LUA file like that?

**Comment by jpatteet** [comment]
@cderv was right, it works after installing quarto version 1.3.361
Sorry and thank you !

**Comment by dragonstyle** [comment]
@cderv makes that a habit! 😉 Glad you're up and running.
