### ISSUE TITLE
When an error is rendered in the output, the ascii escape codes should be stripped or processed to HTML

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#4204]
### Bug description

Currently when an `error` is rendered in the output, the ascii escape codes are also printed out

![image](https://user-images.githubusercontent.com/1813121/216607951-2a210511-98f6-4f63-a0fb-76718f543529.png)

This is what it looks like in the terminal:

![image](https://user-images.githubusercontent.com/1813121/216607870-710be043-e1ee-4817-8798-80c6089da0ac.png)

It would be nice if either quarto

1) starts julia with the flag `--color=no`. This is the same output in the terminal with that flag

![image](https://user-images.githubusercontent.com/1813121/216608240-3e55e1ee-af3f-4a85-9e9a-15db7b13641a.png)

OR

2) parses ascii codes in outputs using a javascript library to generate color html output. For example, you could vendor this: https://github.com/drudru/ansi_up

Reproducible example:

Create a `_quarto.yml` file:

```
project:
  type: website
  title: "MethodError"
  output-dir: _output
  execute-dir: project

execute:
  output: true
  echo: true
  warning: true
  error: true
  freeze: auto
  eval: true
  cache: true

jupyter: julia-1.8
```

Create a `index.qmd` file:

````md
---
title: Method error
---

#### MethodError

```{julia}
ceil(1.2 + 2.3im)
```
````

Version information:

```julia
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by kdheepak** [comment]
Looks like this is already discussed here: https://github.com/quarto-dev/quarto-cli/issues/929

I see that there's a comment mentioning it is fixed for outputs. However, it doesn't seem to be fixed for `error`s.

![image](https://user-images.githubusercontent.com/1813121/216612869-24c6c325-3efb-4ad2-846a-6782e64e7dbb.png)

**Comment by MHellmund** [comment]
May I suggest adding an option switch to quarto? 
 ```
process-ansi-escapes: strip|yes|no
```
Either strip ANSI escape codes from all output and error cells (as default) or process them in quarto or keep them unprocessed for pandoc.   

I started writing a quarto extension (see https://gitea.math.uni-leipzig.de/hellmund/julia-color)  which is essentially a lua filter for pandoc and handles ANSI colors for HTML and LaTeX/PDF output. But at the moment it needs a patched version of quarto and is more of a hack.

**Comment by sje30** [comment]
We are also seeing this problem with Julia errors in 1.9.2
@jmb280cam
