### ISSUE TITLE
Code annotations don't work well with `output-location: slide`

### ISSUE THREAD

**Issue by pmagwene** [quarto-dev/quarto-cli#4213]
### Bug description

I'm testing the new code annotations feature in Quarto pre-release 1.3.154 (MacOS; RStudio IDE Version 2022.12.0+353 (2022.12.0+353)) in a Reveal JS presentation.

When using the `output-location: slide` option, the annotations appear on the output slide rather than on the slide associated with code.

Here's a reprex:

````
---
title: "reprex"
format: revealjs
---

## Code with annotation

```{r}
#| echo: true
#| output-location: slide

x <- seq(-2*pi, 2*pi, by=pi/100) # <1>
y <- sin(x) # <2>
plot(x, y, type = "l")
```

1.  Annotation 1
2.  Annotation 2

````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by Lulliter** [comment]
I actually was looking for the way to keep the annotations in the output slide -- e.g. when output is a plot and I am pointing out what the plot shows. Is there any chance to make this an option as well?

**Comment by mcanouil** [comment]
@Lulliter Please open a GitHub Discussion preferably with a small self-container document containing format, code and a clear explanation of the results you want. Thank you.
