### ISSUE TITLE
Other Formats links not appearing in margin

### ISSUE THREAD

**Issue by mroberts1** [quarto-dev/quarto-cli#4218]
### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Can you provide a little more detail? A sample document and the version of quarto that you're using would be great if possible!
