### ISSUE TITLE
data-background renders the same image differently on level 2 (ok) vs level 1 (not ok) slide

### ISSUE THREAD

**Issue by TomGeens** [quarto-dev/quarto-cli#422]
Dear Collegues,

Congratulations with the great improvements with revealjs presentations through quarto & rstudio!

While experimenting wih the many, easy, usefull,... possibilities, I noticed some strange behaviour in rendering a same 1920px*1080px data-background on a level 2 versus a level 1 slide. The same image shows up slightly different. At level 1 it seems to be shrinked (only vertically?) a bit, resulting in a white band at the bottom edge of the slide. I suppose this behaviour is not intended?

The pdf print and image I used are in attachment. qmd upload does not seem to be supported while reporting this issue, so I'll just paste the contents of my qmd file here. Many thanks in advance! 

Kind regards,
Tom Geens.

---
title: "data-background test level 2 vs level 1"
author: "Tom Geens"
format: revealjs
---

## Agenda (level 2) {data-background="s05agendaW.PNG"}

- no white band below

# Agenda (level 1) {data-background="s05agendaW.PNG"}

- white band below

## Agenda (level 2 ){data-background="s05agendaW.PNG"}

- no white band below

![s05agendaW](https://user-images.githubusercontent.com/11273878/158541877-78529c4d-de9c-42fe-ae39-8a974c0b178d.PNG)
[data-background test level 2 vs level 1.pdf](https://github.com/quarto-dev/quarto-cli/files/8259913/data-background.test.level.2.vs.level.1.pdf)

**Comment by jjallaire** [comment]
Thanks for reporting this! We have some CSS for title slides that was applying to backgrounds where it shouldn't have been. Fix is here: https://github.com/quarto-dev/quarto-cli/commit/cc28387d3322a61cbafe02b39b23e9e88691cf66 (new build w/ fix will be available in an hour or two).

**Comment by TomGeens** [comment]
No problem! I've installed quarto 0.9.105, restarted rstudio-server, but I still get the same result.
[data-background test level 2 vs level 1.pdf](https://github.com/quarto-dev/quarto-cli/files/8266065/data-background.test.level.2.vs.level.1.pdf)

**Comment by TomGeens** [comment]
@jjallaire, another test with build 0.9.106: when I incorporate background-position="0px +15px" manually in the vertical slide definition, the position of the image (liantis logo) is more or less ok in full screen display in the browser, but there still remains a white bar at the bottom edge of the vertical slide, which is not present in the horizontal slide (two png attachments). The behaviour in the overview (png attachment) and the printed version is also different (pdf attachment).

# Agenda (level 1) {data-background="s05agendaW.PNG" background-position="0px +15px"}

![level1](https://user-images.githubusercontent.com/11273878/158709342-538b4e6f-63a9-4d65-9ed3-9fa0739038ed.PNG)
[data-background test level 2 vs level 1 (px shift).pdf](https://github.com/quarto-dev/quarto-cli/files/8275855/data-background.test.level.2.vs.level.1.px.shift.pdf)
![level2](https://user-images.githubusercontent.com/11273878/158709346-12c0d121-cdf9-43ce-a7be-790e60f63cf7.PNG)
![overview](https://user-images.githubusercontent.com/11273878/158709641-101172ee-dfd3-4f3a-8ab9-c4ed78686423.PNG)
[data-background test level 2 vs level 1 (px shift).pdf](https://github.com/quarto-dev/quarto-cli/files/8275855/data-background.test.level.2.vs.level.1.px.shift.pdf)

**Comment by jjallaire** [comment]
In this commit I remove the -15px treatment unconditionally: https://github.com/quarto-dev/quarto-cli/commit/a8e82471fde620f848bd6e21e98a069a41ce71d7

In my local testing this results in the background image always having the right baseline.

Note that this is **not** the case for PDF output (which has different dimensions due to be being 8.5x11 so the background images don't land in the bottom right corner -- I don't think there is anything we can do about this, it's just the nature of Reveal print CSS.
