### ISSUE TITLE
Other formats not posting in margin

### ISSUE THREAD

**Issue by mroberts1** [quarto-dev/quarto-cli#4224]
### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mroberts1** [comment]
I am using the latest version of Quarto (1.2.335) + RStudio (2022.12.0+353).

When rendering index.qmd, "Other formats" list is not generating in margin, even though pdf options appear to be correct in _quarto.yml.

I have tried:

- using format:pdf options only in front matter of index.qmd
- adding <format-links: [pdf]> in front matter of index.qmd
- adding <format-links: [pdf]> in _quarto.yml

In all cases, no "Other formats" list is generated. 

I can render a PDF into _sites folder, but Quarto is not adding a link to it from index.qmd.

I have experienced the same error with single-page sites, i.e. no _quarto.yml, using only front matter of index.qmd.

**Comment by cscheid** [comment]
The "Other formats" option requires [quarto 1.3 prereleases](https://quarto.org/docs/prerelease/1.3/). Did our documentation imply differently somewhere? We want to minimize this type of confusion. I'm going to go ahead and close this, but if you find a piece of documentation implying elsewhere, please open a separate documentation bug. Thank you!

**Comment by mroberts1** [comment]
Thank you! I had been using 1.3.154 and Other Formats was working fine. But I tried to update my Quarto install to the latest version and somehow ended up installing the old version listed on the download page (1.2.335), after which the Other Formats feature stopped working. 

When I looked for what I thought was the current version for Mac, [the page that lists it](https://quarto.org/docs/get-started/) is actually a downgrade. So as a result I spent an afternoon trying to debug the problem between index.qmd and _quarto.yml. I was assuming that I had the latest version of both Quarto and RStudio, which was not the case.

**Comment by cscheid** [comment]
> Since the Pre-Release version is required for these new features, why post an old version on the Mac download page?

That's because 1.2 is not an old version, it's the current stable version, and 1.2.335 is the latest stable version.

Version 1.3 is a prerelease, and "Other formats" is a new feature on the pre-release. We advertise 1.3 on the https://quarto.org/docs/download/ page as a "pre-release" version, which I think appropriately indicates it's the latest version.

We don't advertise 1.3 in "getting started" because the documentation on the website is designed for the current stable version, 1.2.
