### ISSUE TITLE
Quarto - Panel Tabset

### ISSUE THREAD

**Issue by racing-focus** [quarto-dev/quarto-cli#4230]
### Bug description

I have been copying and running the same qmd file week in and week out.  This week when I ran it, it printed:

::: panel tabset

:::

Instead of creating tabs it worked only as headers, but when I threw in some dummy tabs elsewhere in the document, tabs were created, ie.

::: panel tabset

## does
this

## work
oh

## my
it did

:::

The website I have been populating is:

https://racing-focus.netlify.app/posts/hk_2023-02-01/standard.html

If you look at the posts, todays post I reverted to a table of contents style post with conventional headers.

I tried to drag and drop the qmd files, but that failed so I renamed them .txt.  The file I used today and the previous ones that worked. I am not a 'good' programmer and apologise for the code you will see.

The qmd file relies on a couple of csv files which I have added too.

I am using the following version of rstudio and I have been for a little while now.

RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

I am using a Mac.  I don't have a bug report, because it works, it just prints ::: panel tabset.

I googled for an answer and couldn't find one or one on here.  Thanks and Sorry.

[standard_prev.txt](https://github.com/quarto-dev/quarto-cli/files/10610738/standard_prev.txt)
[standard_today
[hkedit.csv](https://github.com/quarto-dev/quarto-cli/files/10610744/hkedit.csv)

[red.csv](https://github.com/quarto-dev/quarto-cli/files/10610742/red.csv)
.txt](https://github.com/quarto-dev/quarto-cli/files/10610739/standard_today.txt)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I'm not sure what is the cause here - it looks like you're using Quarto 1.1.189 and I'm not aware of anything that changed there unless you installed a newer version of Quarto recently. Can you share the exact source code that is causing the issue (ideally strip out the content so only the problem remains). I think based upon that we can probably point you in the right direction...

**Comment by mcanouil** [comment]
From experience, `::: {.tabset-panel}` got displayed in the output when there is a fenced fix matching issue, i.e., fenced div not properly closed or improperly nested.

Having a look at the source code might help.

**Comment by racing-focus** [comment]
Thankyou.  This is the part of the code with the tabset.

::: panel-tabset
```{r}
#| echo: false
#| results: asis


j <- 1
for (j in 1:nrow(as))   
{
  cat("### race", as$race[j], "\n")
  cat("\n")
  
  bs <- as$venue[j]
        cs <- as$race[j]
        ar <- mb %>%
          filter(venue == bs) %>%
          filter(r_no == cs) %>%
          select(colors, n, tr, pre_com) %>%
          rename(silks = colors) %>%
          rename(horse = n) %>%
          rename(note = pre_com) %>%
          distinct()
        
        print(ar %>%
                  gt() %>%
                  gt_theme_espn() %>%
                  tab_header(title = paste0("race ", as$race[j], " - ", as$name[j], " - ", as$class[j], " - ", as$dist[j], "m")) %>%
                gt_img_rows(columns = silks, height = 30) %>%
                gt_merge_stack(col1 = horse, col2 = tr) %>%
                  cols_width(
                    silks ~ px(50),
                    horse ~ px(150),
                    note ~ px(480)) %>%
                cols_align(
    align = "center",
    columns = silks))

}


```
:::

When you say to do something properly as requested, I don't understand what that fully means.  I read the rules, the first rule was to post if you fully don't understand.  the second was to provide the full qmd, which I did as a .txt.  I am not a coder as such, but what I had been doing was working from week to week, then stopped without me making a change.
  The source code is in the .txt files as I may have mentioned in the original message.  I don't even know if the copy and paste above is the correct way to present the portion of code, I just don't know.  I hope someone can help or offer a reason why rendering of the file changed.  I haven't updated quarto.  

Cheers,

**Comment by mcanouil** [comment]
It's about formatting which makes your post legible.
Maybe the link in the item to check was not clear enough about how to format.

Note that GitHub uses Markdown as in Quarto.
For example, to embed text/code with code cells, you need to encapsulate the whole thing with more backticks.

Below, I used five `` ` `` to show you what structure/formatting your post needs to be legible.

`````
````
---
title: Title
format: html
---

## Section

```{r}
1 + 1

```

Text
````
`````

**Comment by racing-focus** [comment]
thanks, I think I understand, the qmd is the format for raising of the issue, not the issue I have with the qmd itself.

the repository for this is:

https://github.com/racing-focus/racing/tree/main/posts

it will be interesting to see what the typo may be, all I do is change the:

---
title: Title
date: date
---

each meeting.

**Comment by mcanouil** [comment]
Because I noticed the "hidden" text file which is in fact a Quarto document (no need to hide the real extension, qmd is fine).

- Code cells should always be surrounded by empty lines.
- figures caption even using `knitr::include_graphics` should use `#| fig.caption: Caption`, see <https://quarto.org/docs/computations/r.html#chunk-options>. There are other places where `fig-cap` is shown as well.
- you should not mixed inline code options as well as yaml code option.
- in your final code cell, what you want to do (as it seems) is to produce a tab set panel with one tab for each iteration. If that is indeed the case, then it's better to simply use `#| classes: panel-tabset` as a code cell option.

**Comment by racing-focus** [comment]
thanks, 

I did add it as a .txt file, because GitHub wouldn't let me drag and drop a .qmd file.

I won't be able to check it until Wednesday, the next race meeting.

```{r}
#| classes: panel-tabset
```

thanks, I didn't know that.  can I ask why you think it was working until yesterday without that in the code block?

**Comment by mcanouil** [comment]
There is no way we can guess what changed if Quarto team or I don't have enough information to reproduce.

**Comment by racing-focus** [comment]
I have Version: 1.1.189

I don't recall adding it, I believe it was in the RStudio I have.

**Comment by racing-focus** [comment]
just as an update, I tried the following:

::: panel-tabset
```{r}
#| echo: false
#| results: asis
#| classes: panel-tabset


j <- 1
for (j in 1:nrow(as))   
{
  cat("### race", as$race[j], "\n")
  cat("\n")
  
  bs <- as$venue[j]
        cs <- as$race[j]
        ar <- mb %>%
          filter(venue == bs) %>%
          filter(r_no == cs) %>%
          select(colors, n, tr, pre_com) %>%
          rename(silks = colors) %>%
          rename(horse = n) %>%
          rename(note = pre_com) %>%
          distinct()
        
        print(ar %>%
                  gt() %>%
                  gt_theme_espn() %>%
                  tab_header(title = paste0("race ", as$race[j], " - ", as$name[j], " - ", as$class[j], " - ", as$dist[j], "m")) %>%
                gt_img_rows(columns = silks, height = 30) %>%
                gt_merge_stack(col1 = horse, col2 = tr) %>%
                  cols_width(
                    silks ~ px(50),
                    horse ~ px(150),
                    note ~ px(480)) %>%
                cols_align(
    align = "center",
    columns = silks))

}


```
:::

and render returned:

```{r}
Error running filter /Applications/RStudio.app/Contents/Resources/quarto/share/filters/quarto-pre/quarto-pre.lua:
PandocLuaError "string expected, got nil\n\twhile retrieving index 1\n\twhile retrieving list"
stack traceback:
	[C]: in metamethod 'index'
	...Resources/quarto/share/filters/quarto-pre/quarto-pre.lua:417: in function 'tabsetDiv'
	(...tail calls...)
	...Resources/quarto/share/filters/quarto-pre/quarto-pre.lua:4579: in function <...Resources/quarto/share/filters/quarto-pre/quarto-pre.lua:4573>

```

I then removed:
```{r}

#| classes: panel-tabset

```

ran it and it worked again.....

I published it.

https://racing-focus.netlify.app/posts/hk_2023-02-08/standard.html

and the repository is here.

https://github.com/racing-focus/racing/tree/main/posts/hk_2023-02-08

thanks for your help @mcanouil, I don't really know what occurred on the weekend.

**Comment by mcanouil** [comment]
Strange ...

Anyhow, I noticed your "post" are a lot alike, are you aware that you can use parametrised document and/or include small Quarto document inside any Quarto document?
i.e., you could put your processing code cells in a document `_processing.qmd`, and add `{{< include _processing.qmd >}}` in your actual Quarto post document, while, data and file path are stored in `params` YAML.
This would allow you to not have to copy/paste contents and to decrease the amount of time spent to "write" those posts.

See <https://quarto.org/docs/computations/parameters.html> and <https://quarto.org/docs/authoring/includes.html>.


PS: feel free to close this issue and eventually reopen it in the future if it happens again more reliably.

**Comment by racing-focus** [comment]
thanks, I will have a look at those options, I could probably improve the efficiency.  at the moment I just copy the folder, change the title and date of the standard.qmd file and render.
