### ISSUE TITLE
Quarto preview of PDF fails in Windows 1.3.178

### ISSUE THREAD

**Issue by fuhrmanator** [quarto-dev/quarto-cli#4271]
### Bug description

After updating to 1.3.178 on Windows 10, previews of PDFs fail for my book project. See the MWE at https://github.com/fuhrmanator/quarto-test

It a git bash terminal, I usually type `quarto preview --to pdf` and it builds the PDF in `_book/book-pdf` (I think the subdir for the PDF is new?). When the viewer in the browser is opened at e.g. http://localhost:6369/web/viewer.html, there's a page with `Not Found`. 

I can view the PDF with a system viewer, however, so the problem seems to be related to the browser-based previewer not finding the PDF.

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thanks for reporting this - I confirmed that it was related to the change in output file location for PDF books. I've rolled that change back for the time being (which addresses this bug) - we'll need to consider relocating those outputs a little more carefully as there are some assumptions in the system about where they end up.

**Comment by fuhrmanator** [comment]
No problem anymore in 1.3.185

**Comment by dragonstyle** [comment]
Thanks as always for reporting and confirming!
