### ISSUE TITLE
Table caption doesn't work with gt-tables on newer Quarto versions

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#4272]
### Bug description

The following code yields different results for Quarto versions 1.1 and 1.3.154. In 1.1 it renders fine, caption shows and cross-referencing works. In 1.3.154 neither captioning nor cross-referencing works. Moreover, the styling of the tables is very different.

	---
	format: html
	---

	```{r}
	#| include: false
	library(gt)
	```

	```{r}
	#| echo: false
	#| label: tbl-mytable
	#| tbl-cap: "Caption"
	head(mtcars) %>% gt()
	```

	@tbl-mytable

It works when using `knitr::kable()` instead of `gt()` but I'm particularly interested in using `gt()` here. This issue persists on Windows 10 and Debian.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report. This is a 1.3 regression. We'll fix it later today.

**Comment by cscheid** [comment]
In quarto, `tbl-cap` requires `label: tbl-`: https://quarto.org/docs/authoring/tables.html We don't presently support table captions without the following id.

If you must use captions without crossref labels, you should rely on the generated HTML from the library (and in that case, we can't guarantee that things will work smoothly.)

**Comment by snhansen** [comment]
I don't follow. The issue in my most recent post isn't about the labeling but about how the table is rendered (or displayed if you will). Here is the result without a caption https://imgbox.com/rpuiu3SY and with a caption (and label) https://imgbox.com/OteD8NyX

That's not intended, right?

**Comment by cscheid** [comment]
The issue is that quarto currently interprets "table captions" as objects that must exist in the crossref subsystem, which itself requires valid table labels. So you can't use `tbl-cap:` without also using `label: tbl-*`.

**Comment by snhansen** [comment]
Alright, but the second image in my previous post does use both `tbl-cap:` and `label: tbl-*` but the table is processed incorrectly (compare with the first image). The code is:

	---
	format: html
	---

	```{r}
	#| include: false
	library(tidyverse)
	library(gt)
	```

	```{r}
	#| echo: false
	#| tbl-cap: "Caption"
	#| label: tbl-test
	dat <- tribble(~a, ~x, ~y, ~z,
				   "A", 1, 12, 13,
				   "B", 2, 9, 11)

	dat %>%
	  gt() %>%
	  tab_spanner(
		label = "Subheader",
		columns = c(x, y)
	  )
	```

	@tbl-test

**Comment by cscheid** [comment]
Are you running the latest version of quarto and gt? This is what I see:

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/285675/218143957-4b7c9796-9c25-434d-a539-67afaaaf7998.png">

**Comment by snhansen** [comment]
Yes, and that's not correct. The "x" and "y" are being pushed down, they should be in the same row as "a" and "z" and then "Subheader" should be on top of "x" and "y". Should look like this:
![](https://images2.imgbox.com/da/78/rpuiu3SY_o.png)

which it does when rendering without a caption and also if I just run it in R.

Quarto version 1.3.189 and gt v. 0.8.0 which should be the latest.

**Comment by cscheid** [comment]
I see. I think this is a CSS bug with spanners in quarto specifically. @rich-iannone what do you think?

**Comment by rich-iannone** [comment]
Will investigate within that open issue. Thanks for opening it.

**Comment by schwa021** [comment]
Still broken!
