### ISSUE TITLE
Cannot paste Windows screenshot into qmd file, in visual editor, in RStudio Desktop 2023.03.0-daily+301 but can in 2022.12.1+363

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-cli#4277]
### Bug description

If I am:
- working in RStudio Desktop 2023.03.0-daily+301
- in a .qmd file, in visual editor mode
- then take a windows screenshot, directed to the clipboard, and
- copy it into the visual editor window

Then, instead of getting the expected image of the screenshot, I get a broken link, such as:

![image](https://user-images.githubusercontent.com/6538392/217536497-e921c462-e9b1-4425-a43b-4353ff9159c3.png)

By contrast, if I do this in RStudio Desktop 2022.12.1+363 the image will appear as expected.

Possibly related to #12270 and #12466.

I have seen this occur before, where in daily builds of an RStudio Desktop version, image pasting into qmd files stops working, but later it is fixed. I think it happened with Elsbeth Geranium, but if not with that, with an earlier version for sure. Because it seems like you are getting close to release of Cherry Blossom, I thought I should mention it now.

> Edition	Windows 11 Pro
> Version	22H2
> Installed on	‎5/‎13/‎2022
> OS build	22623.1250
> Experience	Windows Feature Experience Pack 1000.22639.1000.0

> platform       x86_64-w64-mingw32               
> arch           x86_64                           
> os             mingw32                          
> crt            ucrt                             
> system         x86_64, mingw32                  
> status                                          
> major          4                                
> minor          2.2                              
> year           2022                             
> month          10                               
> day            31                               
> svn rev        83211                            
> language       R                                
> version.string R version 4.2.2 (2022-10-31 ucrt)
> nickname       Innocent and Trusting  

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Can you file this at the [RStudio](https://github.com/rstudio/rstudio) repo? Thanks.

**Comment by donboyd5** [comment]
Oops, sorry, oddly and erroneously that's what I thought I was doing; just filed it at RStudio [here](https://github.com/rstudio/rstudio/issues/12270).
