### ISSUE TITLE
Wrong URL for twitter cards/open graph

### ISSUE THREAD

**Issue by ddobrinskiy** [quarto-dev/quarto-cli#4278]
It appears that when I'm publishing my Jupyter notebooks to quartopub, the OG/twitter preview image urls are wrong.

Code in jupyter/qmd: 

```
![](images/streamlit-jupyter-logo.png){.preview-image}
```

What is rendered in html:

```html

<meta property="og:image" content="https://quartopub.com/sites/ddobrinskiy/blog/posts/2023/02/nbdev_streamlit_jupyter/images/streamlit-jupyter-logo.png">

<meta name="twitter:image" content="https://quartopub.com/sites/ddobrinskiy/blog/posts/2023/02/nbdev_streamlit_jupyter/images/streamlit-jupyter-logo.png">

```

However, the [links from above](https://quartopub.com/sites/ddobrinskiy/blog/posts/2023/02/nbdev_streamlit_jupyter/images/streamlit-jupyter-logo.png) lead to 404, page not found.

The correct URL would be the following: https://ddobrinskiy.quarto.pub/blog/posts/2023/02/nbdev_streamlit_jupyter/images/streamlit-jupyter-logo.png

I'm wondering if this is a bug, or something wrong with my config?

I run `quarto publish` from the CLI to publish my website.

The source code is available here:

* quarto config: https://github.com/ddobrinskiy/blog
* jupyter notebook: https://github.com/ddobrinskiy/blog/tree/master/posts/2023/02/nbdev_streamlit_jupyter

**Comment by dragonstyle** [comment]
This is actually fixed in our Quarto 1.3 release- could you give that a try and see if it resolves the issue?

(for reference- dug this up)
https://github.com/quarto-dev/quarto-cli/commit/47f12b052a07ed5bb07bafe6448cddd4d9eec4a6
