### ISSUE TITLE
Quarto does not render titles as atx-style H1s in Markdown

### ISSUE THREAD

**Issue by tomshafer** [quarto-dev/quarto-cli#4280]
### Bug description

Given this document:

```markdown
---
title: Example Title
format:
    gfm:
        markdown-headings: atx
---

# Heading

Here's some text.

## Heading 2

Here's some more text.
```

I receive the following output:

```markdown
Example Title
================

# Heading

Here’s some text.

## Heading 2

Here’s some more text.
```

Because I asked for atx-style headers, I would also like to get atx-style header for the title as well so I can then shift the heading level if needed.

Thanks!

### System info

- macOS 13.2 (22D49)
- Quarto 1.2.313

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
With GFM format I don't think the `title` YAML field should be shown this way. It is not part of the default Pandoc template 

I wonder if this is not part of the regression we had in https://github.com/quarto-dev/quarto-cli/issues/4210 

Note about this : 

The `========` is hard coded in the markdown template we use internally for some format
https://github.com/quarto-dev/quarto-cli/blob/904fe181c792e44dc937825452dd98651d27dc57/src/resources/pandoc/templates/default.markdown?plain=1#L1-L4

I think default pandoc template should be use with **gfm**, and not the one above 
https://github.com/quarto-dev/quarto-cli/blob/904fe181c792e44dc937825452dd98651d27dc57/src/command/render/pandoc.ts#L787-L806

and using Pandoc to convert to gfm does not output a title
````markdown
> pandoc -f markdown -t gfm --markdown-headings=atx
---
title: Example Title
---

# Heading

some text.

## Heading 2

some more text.
^Z
# Heading

some text.

## Heading 2

some more text.
````

This is worth looking into

**Comment by dragonstyle** [comment]
We're purposely using a distinct template from Pandoc as we believe including the title is useful for these formats. That said, I think we should just switch that template to use an ATX style heading for the title rather than the current non-ATX that we're using.

**Comment by cderv** [comment]
Oh it is the otherway around then ! Thanks for the precision. 

I agree with you that we should respect the default which is atx for gfm. However, issue with still by the same with 
````
format: 
  gfm:
    markdown-headings: setext
````

but I guess this is uncommon maybe. 

I think it is possible know to catch the information of command flag in Lua, so in theory, we could set a variable that would help us know which style to use.

**Comment by dragonstyle** [comment]
agreed - if it was easy to support that flag in the template, it seems good. But it does seem likely to be infrequent...
