### ISSUE TITLE
QUARTO_DENO wrongly set internally in `quarto.exe` on Windows ? 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#4281]
On Windows 
````
> quarto --version
1.3.184
> echo 'console.log("hello")' > test.js
> quarto run test.js
WARNING: Specified QUARTO_DENO does not exist, using built in deno
hello
> $ENV:QUARTO_DENO
````

See the warning but `QUARTO_DENO` is not set on the system. Something is off. 

@dragonstyle I need your help here as I don't know exactly how we are bundling the `.exe`. I know we set `QUARTO_DENO` on the `quarto.cmd` file and maybe this is still the case in the `.exe` and path is not correct ? 

Logging here to not forget.

**Comment by dragonstyle** [comment]
From looking at the code, it looks like a false warning (e.g. we're warning but the using the provided path anyhow). 

We're setting the path here:
https://github.com/quarto-dev/quarto-cli/blob/b4c7f87a2b5a5f1371a3fb15826161ad800a946e/package/launcher/src/main.rs#L52

using the path to `deno` with no extension (the file is actually `deno.exe`). We check for that path's existence before we use it, but we ultimately just warn the user and then continue on with that path. It looks like on window, a path excluding the `.exe` is still actually a valid path and likely should be permitted without warning.

**Comment by dragonstyle** [comment]
Yeah we are setting that path in our rust launcher to:

```
deno_file = bin_dir
                .join("tools")
                .join(deno_dir())
                .join("deno");
```

which is pointing to the full executable, not to a directory. I think executing that path on windows will succeed (you can run `deno` or `deno.exe`), so we should be omitting that warning altogether since that is in fact validly pointing to a path that can be executed.

**Comment by cderv** [comment]
OK I can confirm that on Windows we have this 
````typescript
> existsSync("C:/Users/chris/scoop/apps/quarto-prerelease/current/bin/tools/deno")
false
> existsSync("C:/Users/chris/scoop/apps/quarto-prerelease/current/bin/tools/deno.exe")
true
````

So Warning is thrown from there: 
https://github.com/quarto-dev/quarto-cli/blob/b4c7f87a2b5a5f1371a3fb15826161ad800a946e/src/core/resources.ts#L42-L43

We'll use the same path afterward without the extension 
https://github.com/quarto-dev/quarto-cli/blob/b4c7f87a2b5a5f1371a3fb15826161ad800a946e/src/core/resources.ts#L58

it works ok because calling deno with absolute path without extension works
