### ISSUE TITLE
blockquote padding with embedded heading

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#429]
Using Quarto 0.9.80.

When a blockquote element contains a heading, the blockquote is given padding.

````markdown
---
title: "quarto-blockquote-bug"
---

This is some text that is at the start of the document.

> ## Something important
>
> This is the text for something important that is part
> of a blockquote paragraph. Is it actually important?
> That is impossible to know.
````

Rendered and viewed in Safari, this looks like:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/362187/158847894-71984403-38a6-4e6f-9cfe-6a5ad7ebe58d.png">

Some separation feels necessary, but the blockquote grey bar feels artificially long in this context.

I encountered this when trying to embed some text that was extracted from another document, so a blockquote felt appropriate, but feel free to suggest an alternative.

**Comment by jjallaire** [comment]
fixed here: https://github.com/quarto-dev/quarto-cli/commit/0f397327fa8922693169ae77afac655e6b120f2e
