### ISSUE TITLE
citations in tex sometimes keep first name or initials

### ISSUE THREAD

**Issue by edzer** [quarto-dev/quarto-cli#4294]
### Bug description

The inline citations of literature resources sometimes, wrongly, keeps the initials or first name with the last name, for some authors, where it shouldn't. Wrong:
![Screenshot from 2023-02-09 14-40-51](https://user-images.githubusercontent.com/520851/217829425-ec102af4-7d0e-47b0-baf0-7bcce0b1cdf7.png)
Right:
![Screenshot from 2023-02-09 14-40-08](https://user-images.githubusercontent.com/520851/217829566-269fc333-034f-4c14-bdc0-a153ad0c9852.png)
In my example reprex, If I change the name in the second ref (Bivand -> Bivnd), _both_ come out correctly. Also, in the example, if I remove the reference to @R-spdep in index.qmd, the rendering of the _first_ references becomes correct!

It is not as simple as a single name; this happens to multiple references (also without "and" in them) in [this book](https://github.com/edzer/sdsr); I'd be happy to share more details / examples.

Zip file: 
[bug.zip](https://github.com/quarto-dev/quarto-cli/files/10697808/bug.zip)

I'm using R 4.2.2 on Ubuntu 22.04, no Rstudio, and quarto 1.2.335

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by njbart** [comment]
The author (“Bivand”) is inconsistently named in the bib file. See https://www.zotero.org/support/kb/given_name_disambiguation for an explanation - relevant since Zotero's citeproc-js follows the same [CSL specs](https://docs.citationstyles.org/en/stable/specification.html#disambiguation) as Pandoc's citeproc, which is being used here.

**Comment by cscheid** [comment]
Thanks for tracking that down, @njbart. I'm going to go ahead and close this one.
