### ISSUE TITLE
Quarto run freezes when used to install rmarkdown (via quarto run)

### ISSUE THREAD

**Issue by pecanka** [quarto-dev/quarto-cli#4300]
I hope this is not an issue specific to my machine/setup, but I have observed the following behavior. When quarto (via `quarto run`) is used to install the rmarkdown package on a windows machine, it seems to freeze up indefinitely. Other packages (e.g., magrittr) install fine via `quarto run`. 

Call: `quarto run code.R`

File `code.R`:

```
install.packages(pkgs = 'rmarkdown', character.only = TRUE, repos = 'http://cran.us.r-project.org', type = "win.binary")
```

The problem seems to occur at step 26 within `utils::install.packages`, specifically the call to ` .install.winbinary()`:
```
if (.Platform$OS.type == "windows") {
        if (startsWith(type, "mac.binary"))
            stop("cannot install macOS binary packages on Windows")
        if (type %in% "win.binary") {
            .install.winbinary(pkgs = pkgs, lib = lib, contriburl = contriburl,
                method = method, available = available, destdir = destdir,
                dependencies = dependencies, libs_only = libs_only,
                quiet = quiet, ...)
            return(invisible())
        }
        have_spaces <- grep(" ", pkgs)
        if (length(have_spaces)) {
            p <- pkgs[have_spaces]
            dirs <- shortPathName(dirname(p))
            pkgs[have_spaces] <- file.path(dirs, basename(p))
        }
        pkgs <- gsub("\\", "/", pkgs, fixed = TRUE)
    }
    else {
        if (startsWith(type, "mac.binary")) {
            if (!grepl("darwin", R.version$platform))
                stop("cannot install macOS binary packages on this platform")
            .install.macbinary(pkgs = pkgs, lib = lib, contriburl = contriburl,
                method = method, available = available, destdir = destdir,
                dependencies = dependencies, quiet = quiet, ...)
            return(invisible())
        }
        if (type %in% "win.binary")
            stop("cannot install Windows binary packages on this platform")
        if (!file.exists(file.path(R.home("bin"), "INSTALL")))
            stop("This version of R is not set up to install source packages\nIf it was installed from an RPM, you may need the R-devel RPM")
    }
```
Quarto version 1.1.189.
Output of `R.version`:
```
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          2.1                              
year           2022                             
month          06                               
day            23                               
svn rev        82513                            
language       R                                
version.string R version 4.2.1 (2022-06-23 ucrt)
nickname       Funny-Looking Kid 
```

**Comment by cderv** [comment]
Quarto depends on the **rmarkdown** package, which is required when using R with Quarto. This is not a good idea to install **rmarkdown** from within a script run with Quarto. Same goes from within a Rmd document, or within a Qmd document. 

I would run this with
```
Rscript -e 'install.packages(pkgs = "rmarkdown", character.only = TRUE, repos = "http://cran.us.r-project.org/", type = "win.binary")'
```

This is especially true with windows binaries which get lock and can't be updated in R session when the older version is loaded. **pak** is recommended to help for that matter (https://pak.r-lib.org/)

What push the need of installing R Markdown with Quarto script ?

**Comment by pecanka** [comment]
Yes, I admit that it is somewhat unusual to be attempting to install **rmarkdown** that way. The construct came about as a matter of convenience to avoid having to locate R when R is not in the Windows PATH variable (while Quarto is). Since `quarto run` seems to be a legitimate way to run R scripts, it seems like it should not fail that way. There might be others that attempt to use it that way. Speaking of failing, however, I just tested the same call on another machine with Quarto 1.2.269, and the example code runs fine. Whatever the cause of the problem, it seems to have been fixed in the more recent version of Quarto. Thanks for the great work to the Quarto team! 👏

**Comment by cderv** [comment]
> avoid having to locate R when R is not in the Windows PATH variable (while Quarto is).

That is indeed an interesting usage as quarto try to guess where R is if not out on PATH. 

> it seems like it should not fail when used that way.

Probably yes it should your right. R package should not be loaded for quarto run.  

> I just tested the same call on another machine with Quarto 1.2.269, and the example code runs fine. 

Awesome. Let's close this then. 

Note that my comment still applies on windows. You can have dll locked issue if you run your install but some of the updated packages are loaded in another R session. 

And thanks for the nice encouraging words !
