### ISSUE TITLE
spaces in filenames don't seem to always be handled correctly: a special embed-resources case

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#4310]
### Bug description

Hi,
I have this input qmd file

~~~~
---
title: "Test Kakumbi 2018-2020"
format:
  html:
    toc-depth: 5
    toc-location: left
    footnotes-hover: true

---


<img src="file:///home/aborruso/lavagna/tmp file.png" style="width: 100%;"/>
~~~~

And this setting file

~~~~
sidebar: false
navbar: false
embed-resources: true
~~~~

When I run

```
quarto render input.qmd --metadata-file settings.yml
```

I have this error

```
pandoc: /home/aborruso/lavagna/tmp%20file.png: withBinaryFile: does not exist (No such file or directory)
```

It seems related to [this pandoc issue](https://github.com/jgm/pandoc/issues/7819#issuecomment-1008220337), but I think there is something to do here in quarto to manage it.

I'm using Debian 11 and quarto 1.3.189

Thank you

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I can reproduce this with an even simpler document:

```markdown
---
title: Test Space
format: html
embed-resources: true
---

<img src="file:///Users/foo/Desktop/test copy.png" style="width: 100%;"/>
```

It appears to be related to the use of the HTML tag / file URI specifically, as this doesn't exhibit the same issue:

```markdown
---
title: Test Space
format: html
embed-resources: true
---

![](/Users/foo/Desktop/test copy.png){width="100%"}
```

For now you can workaround this using the markdown syntax rather than the html (which has the benefit for being format portable as well :) ).

**Comment by aborruso** [comment]
Thank you @dragonstyle
