### ISSUE TITLE
gt table spanners and quarto captions

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#4316]
````
---
format: html
---

```{r}
#| include: false
library(tidyverse)
library(gt)
```

```{r}
#| echo: false
#| tbl-cap: "Caption"
#| label: tbl-test
dat <- tribble(~a, ~x, ~y, ~z,
			   "A", 1, 12, 13,
			   "B", 2, 9, 11)

dat %>%
  gt() %>%
  tab_spanner(
	label = "Subheader",
	columns = c(x, y)
  )
```

@tbl-test
````

Produced output:

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/285675/218155441-d762063a-3043-43f6-8543-8dd200e73854.png">

Desired output:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/285675/218155490-0e0014c7-5dde-4ba8-8b6a-9a39f4405732.png">

This is either CSS or our table processing failing in the presence of spanners. Maybe a combination of both, since it only happens when we inject a caption.

**Comment by cscheid** [comment]
(See the comments on #4272 after the original issue was closed).

**Comment by rich-iannone** [comment]
Thanks for letting me know about this. Will test and figure out the problem.

**Comment by cscheid** [comment]
Upstream Pandoc issue that is causing the problem: https://github.com/jgm/pandoc/issues/8647

**Comment by cscheid** [comment]
Update:

Their parser is not actually fully generic of the possible HTML tables, and some of these issues are triggered by tables emitted by gt.  Specifically, Pandoc is fairly opinionated in where it expects to read and emit th vs td elements, and mixes them up in an HTML->Native->HTML round trip for a number of scenarios.
Unfortunately, I think quarto should support a pretty faithful preservation of th vs td, in particular because this has accessibility impacts. This change is unlikely to appear in Pandoc (see discussion in the link above), so we'll have to work around it on our side.

**Comment by snhansen** [comment]
If I understand correctly, this should be fixed as of 1.3.222. I just updated to 1.3.224 and is still experiencing the issue with the example code above.

**Comment by cscheid** [comment]
I can repro it here, thanks for flagging.

**Comment by cscheid** [comment]
I had missed a difference instance of the same bug elsewhere in the source (and had tested with a different, simpler repro that was insufficient). I've now added this exact invocation to our regression tests so it hopefully doesn't come up again anytime soon.

**Comment by snhansen** [comment]
Can confirm that this works as of 1.3.228. Cheers.

The resulting table does not respect the column widths set by the `cols_width()` function though. Not sure if I should report this as a separate issue.

Example code:

	---
	format: html
	---

	```{r}
	#| include: false
	library(tidyverse)
	library(gt)
	```

	```{r}
	#| echo: false
	dat <- tribble(~a, ~x, ~y, ~z,
				   "A", 1, 12, 13,
				   "B", 2, 9, 11)

	dat %>%
	  gt() %>%
	  cols_width(
		a ~ px(50),
		x ~ px(100),
		y ~ px(100),
		z ~ px(200),
	  )
	```

The column widths produced by this example are just the default widths.

**Comment by cscheid** [comment]
This seems to be a limitation in [Pandoc's Table node](https://pandoc.org/lua-filters.html#type-colspec), which doesn't support `colgroup` specifications in pixels. @rich-iannone it would be a good thing for us to figure out exactly what's allowed in Pandoc's colspecs, how it interprets those in html input, and provide a way for gt to emit html in that style.

We could attempt to catch these elements, escape them, and replace them, but this whole endeavor is brittle and pretty regression-prone. The `th` vs `td` issue is acute, and worth the workaround, but I'm not convinced that the risk is worth it in this specific scenario.

@snhansen If you need to make sure your gt table will be processed exactly, use `quarto.disable_processing = TRUE` as a gt option (you will also need to install `gt` from github, this is a very recent addition). Do note that in that case, captions etc. will not be processed (the table will go through entirely untouched).

**Comment by snhansen** [comment]
@cscheid: Thanks for the response. Just noticed that `gt` supports `cols_width` specification by `pct()` rather than `px()` and together with the `tab_options(table.width = ...)` it seems that I can achieve what I want. So not sure this is worth the hassle. Thanks again and let me just say that I appreciate the very responsive dev team you people have for Quarto.
