### ISSUE TITLE
Table endnotes don't work in margins

### ISSUE THREAD

**Issue by mikheyev** [quarto-dev/quarto-cli#4324]
### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mikheyev** [comment]
**System:**
Mac OS =
VSCode Version: 1.75.0 (Universal)
tlmgr using installation: /usr/local/texlive/2022
TeX Live (https://tug.org/texlive) version 2022

**Description**

If you combine margin references with table footnotes, the processor errors out

````
---
format:
  pdf: default
reference-location: margin
---

fruit | count
---|---
apple  | 1[^1]
banana | 2

: Fruits and the animals that eat them {#tbl-fruit}

[^1]: This is the best fruit
````

You get an error:

````
compilation failed- error
LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.168 ...ote{\footnotesize This is the best fruit}
                                                   \\ 
````

If you just run in regular mode, no problem:
````
---
format:
  pdf: default
---

fruit | count
---|---
apple  | 1[^1]
banana | 2

: Fruits and the animals that eat them {#tbl-fruit}

[^1]: This is the best fruit
````

**Comment by dragonstyle** [comment]
This should be fixed in our next pre-release build. Thanks for reporting it!
