### ISSUE TITLE
LaTeX Error: Cannot determine size of graphic in loss.webp (no BoundingBox).

### ISSUE THREAD

**Issue by Waterkin** [quarto-dev/quarto-cli#4326]
To reproduce my error, run `quarto render`

**Comment by dragonstyle** [comment]
I'm guessing that your source code includes a url to a webp image? Could you share the qmd that is causing the issue?

**Comment by Waterkin** [comment]
> I'm guessing that your source code includes a url to a webp image? Could you share the qmd that is causing the issue?

Hi, here is the code: 
`![](loss.webp){width=100%}`

**Comment by Waterkin** [comment]
> > I'm guessing that your source code includes a url to a webp image? Could you share the qmd that is causing the issue?
> 
> Hi, here is the code: `![](loss.webp){width=100%}`

Adding `pdf-engine: pdflatex` solves this issue, but a new bug rises 
```
running pdflatex - 1
  This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages

compilation failed- error
LaTeX Error: Unicode character 机 (U+673A)
               not set up for use with LaTeX.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.200 \part{机器学习}
```

**Comment by dragonstyle** [comment]
I don't believe that you're going to be able to render a webp image from LaTeX to PDF (based upon my limited searching). I think your best bet will be to convert any such images to PNG or another such format.

**Comment by Waterkin** [comment]
> I don't believe that you're going to be able to render a webp image from LaTeX to PDF (based upon my limited searching). I think your best bet will be to convert any such images to PNG or another such format.

Thanks for your advice. I will convert the webp images to PNG.
