### ISSUE TITLE
Blog posts include inlined CSS styles that are hard to overwrite

### ISSUE THREAD

**Issue by gadenbuie** [quarto-dev/quarto-cli#4334]
### Bug description

I've been working on a custom code syntax theme and have run into a couple of limitations. I made [a repo with a basic blog website](https://github.com/gadenbuie/quarto-reprex/tree/website-syntax-styles) that demonstrates the problem. The links below are to specific commits or diffs (I also described the problems/steps [in the commit history](https://github.com/gadenbuie/quarto-reprex/commits/website-syntax-styles)).

1. pandoc's default color scheme is [inlined in the rendered website content](https://github.com/gadenbuie/quarto-reprex/blob/587c29f5cf001e4fc2043c2d72a4b77ed8906957/syntax-styles/_site/posts/post-with-code/index.html#L59-L87).
    * The default styles contain `font-weight` and `font-style` properties.
    * If a custom theme [sets `italic: false` for these tokens](https://github.com/gadenbuie/quarto-reprex/commit/8407c0366dda2dd97e5c2c12da6cfe9839d8db8b#diff-1b543bdd0b13564bb5975b178bee67565f30217b9cca4bd48d27b722d2e38a24), the `font-style: italic` property [is removed in quarto-syntax-highlighting.css](https://github.com/gadenbuie/quarto-reprex/commit/8407c0366dda2dd97e5c2c12da6cfe9839d8db8b#diff-4420bcdaeeb0c6e5a17f8da212ecce3c6a7f5f3d62d3f838377967ec53aaa392), but this does not disable the italics [due to the inlined rules](https://github.com/gadenbuie/quarto-reprex/commit/39a96a16ca947a14d744a8fb04f5905cb8319e37).
    * I came up with [a (hopefully temporary) solution](https://github.com/gadenbuie/quarto-reprex/commit/7014a645229a87cd1056943abac9fc53dbe84fd4) to remove the `code span.xx` rules in the browser with JavaScript. Alternatively, one can write additional custom rules that override the inlined rules.

2. The syntax `.theme` to `quarto-syntax-highlighting.css` translation [doesn't include token background colors](https://github.com/gadenbuie/quarto-reprex/commit/80eef62d32c19513cafe4540255351abbe7f1d14). These aren't very common, but I'm a fan of subtle background colors on specific tokens and use them in my site.

```
# System Version: macOS 13.0 (22A380)
quarto --version
1.2.335
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thanks for reporting this! I've cleaned up the inline styles that were appearing when you specify a style. In addition, we're now properly forwarding the font style and background, meaning no JS should be needed. 

Thanks for great and easy to understand bug - made fixing this straightforward!
