### ISSUE TITLE
Adapt tests for qualified paths for Windows

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#4339]
Qualified paths were added in https://github.com/quarto-dev/quarto-cli/pull/2429

* https://github.com/quarto-dev/quarto-cli/blob/main/src/core/qualified-path.ts

Currently, tests are not made for windows:  https://github.com/quarto-dev/quarto-cli/blob/main/tests/unit/paths/qualified-path.test.ts

In #4099, I'll ignore tests for now until this is fixed.

**Comment by cscheid** [comment]
(Let's close this one and reopen when we actually have started using `QualifiedPath` consistently in the code)
