### ISSUE TITLE
Reveal: Code highlighting for lines of code below the fold don't work. 

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#434]
Reported by @mine-cetinkaya-rundel  (Reprex here: https://gist.github.com/mine-cetinkaya-rundel/3e46083d87db9637b725c977b0b12e9f)

@cderv Could you take a look at this?

**Comment by cderv** [comment]
Yes I will

**Comment by cderv** [comment]
I think it is working ok now with the PR. Some conflicts between our fixes and those in Pandoc not yet aligned.
