### ISSUE TITLE
Extention filename incorrect  OS error

### ISSUE THREAD

**Issue by M-Russell** [quarto-dev/quarto-cli#4346]
I am trying to render a pdf using the asc extention: https://github.com/quarto-journals/acs

I am running quarto version 1.2.335 on windowsWindows 10 Enterprise Version 10.0.19044 Build 19044 through Rstudio.

I set up a new dir containing the extention template:

`quarto use template quarto-journals/acs`

Then render:

`quarto render template.qmd --to acs-pdf`

I get error:

`ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'D:\Repositories\bugErrorHelp\template\_extensions\quarto-journals\acs\_extensions\quarto-ext\latex-environment\D:\Repositories\bugErrorHelp\template\_extensions\quarto-journals\acs\_extensions\quarto-ext\latex-environment\latex-environment.lua'`

It looks like quarto concatinating the full path of latex-environment.lua file into the directory path of the file resulting in an unfindable path. I can't see anywhere where the path might manually be tweeked.

The extention offeres an html render as well, which works just fine.

 As this bug seems not to be previosly reported I wonder if it is an issue with my machine.

**Comment by cscheid** [comment]
(@cderv @dragonstyle this looks like another Windows absolute path concat issue, so I've assigned you)

**Comment by cderv** [comment]
Yes definitely. I wonder if this is not already fix in 1.3: https://github.com/quarto-dev/quarto-cli/issues/3850 by https://github.com/quarto-dev/quarto-cli/commit/db2f57665b4cb8381d6510c888c46e25828049c5  available from `v1.3.86`

> I am running quarto version 1.2.335 on windows

You could try updating to use pre-release of Quarto: https://quarto.org/docs/download/prerelease.html

I believe it will solve the issue

**Comment by M-Russell** [comment]
updateing to pre-release quarto v 1.3.197 has fixed the issue. Thanks very much.
