### ISSUE TITLE
Tracking newer Observable Plot (or Inputs) releases

### ISSUE THREAD

**Issue by jimjam-slam** [quarto-dev/quarto-cli#435]
(I understand that you've had a few issues around dependencies lately! Please feel free to shut this down if it's not appropriate.)

I've been experimenting with importing a newer version of Observable Plot than the one bundled with Quarto so that I can take advantage of newer features (eg. the new ARIA accessibility support in [Observable Plot 0.4.1](https://github.com/observablehq/plot/blob/main/CHANGELOG.md#041)). It _seems_ like it's as easy as changing the reference in the `esbuild-bundle.js` included in my built project files:

```js
var q = T("@observablehq/inputs", "0.9.1", "dist/inputs.min.js");
var M = T("@observablehq/plot", "0.2.0", "dist/plot.umd.min.js");
```

If I `quarto render`, modify the bundle file and then run another web server, it seems to work well (although I acknowledge that "my one sample plot worked with a new feature" isn't a thorough test regime!).

What I'm hoping is that there might be a way for me to flag the Plot (or Inputs) version that Quarto builds from - either on a per-project basis or, failing that, just globally for my Quarto installation- so that I don't have to make this modification every time I `quarto render`.

I can see that there's a [`src/resources/formats/html/ojs/esbuild-bundle.js`](https://github.com/quarto-dev/quarto-cli/blob/2a16e6ce2b6f62209b881a27c5bdfaf3d29a27f5/src/resources/formats/html/ojs/esbuild-bundle.js) i nthe installation; I'm assuming that gets copied in when I `quarto render`. I can also see from the `README` in that folder that this bundle gets built from the [`stdlib.js`](https://github.com/quarto-dev/quarto-cli/blob/2a16e6ce2b6f62209b881a27c5bdfaf3d29a27f5/src/resources/formats/html/ojs/stdlib.js) file, which also refers to the Plot and Inputs versions, and that's there's a `quarto build-js` command to run this build (although I get `Error executing '/Users/james/Applications/quarto/bin/esbuild': No such file or directory` when I try to run it).

I'm not quite sure how to bring these pieces together. It seems like the easy way could be to edit the bundle file that Quarto's sitting on, although I can't find the corresponding file in my installation. It also seems intuitively like I might introduce dependency problems for myself if I modify the bundle myself rather than modifying its sources. Is there a way I can try this out (on a _strictly_ at-your-own-risk basis, since I'm not asking you to change your schedule for managing Quarto's dependencies)? or should I just continue to modify the bundle file that is created when I `render`?

**Comment by jjallaire** [comment]
Your are mostly on the right track here! You should be able to run `quarto build-js` if you install and run the development version of Quarto as described here: https://github.com/quarto-dev/quarto-cli#development-version (the error message above indicates to me that you are hitting the release rather than development version)

You could then just maintain a branch that has your desired changes on it (and we'll also be sure to update this dependency soon)

**Comment by awconway** [comment]
Just wanted to upvote the request that a newer version of Observable Plot gets added in - the very handy legends feature from plot is missing from the current install of Quarto. Thanks

**Comment by jimjam-slam** [comment]
@jjallaire Building the dev version worked a treat! I built it according to [the README instructions you linked](https://github.com/quarto-dev/quarto-cli#development-version), modified [src/resources/formats/html/ojs/stdlib.js](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/html/ojs/stdlib.js) to use Observable Plot `0.4.2` and Inputs `0.10.4`, ran `quarto build-js` and now I'm off the races whenever I `quarto render` 🚀
