### ISSUE TITLE
Cross reference does not work on headings (pdf)

### ISSUE THREAD

**Issue by matthewgson** [quarto-dev/quarto-cli#4356]
### Bug description

````md
---
title: "Untitled"
format: pdf
editor: visual
---

Please see @ref1.

## Quarto {#ref1}

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.
````

I hope I'm not making a simple mistake, but the code autocompletion does not recognize `ref1` in visual mode, nor is the document properly generating the link.. 

RStudio
2022.12.0 Build 353

```{r}
> Sys.info()
                                                                                          sysname 
                                                                                         "Darwin" 
                                                                                          release 
                                                                                         "22.3.0" 
                                                                                          version 
"Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64" 
                                                                                         nodename 
                                                                   "Matthews-MacBook-Pro-2.local" 
                                                                                          machine 
                                                                                         "x86_64" 
                                                                                            login 
                                                                                           "root" 
                                                                                             user 
                                                                                     "matthewson" 
                                                                                   effective_user 
                                                                                     "matthewson" 
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
There are a couple of issues in your .qmd:

- As we point out in the [overview of the crossref documentation](https://quarto.org/docs/authoring/cross-references.html#overview), labels need to have a specific prefix (for sections, it's `sec-`).
- In order to get the heading references to resolve correctly, you need `number-sections: true` (we should have a warning about this one, but currently don't).

Try this one:

````
---
title: "Untitled"
number-sections: true
format: pdf
---

Please see @sec-1.

# Quarto {#sec-1}

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.
````

**Comment by matthewgson** [comment]
Thanks for speedy feedback. I did come across the prefix on the docs but forgot to put in the reprex. The number-sections part was the issue.
