### ISSUE TITLE
invalid date in books

### ISSUE THREAD

**Issue by sbalci** [quarto-dev/quarto-cli#436]
Hi @dragonstyle 
Thank you.
I am now getting result as "invalid date".

<img width="1561" alt="Screen Shot 2022-03-17 at 23 23 21" src="https://user-images.githubusercontent.com/7208830/158889078-6b8f81c9-ab74-4b8a-881f-033b3d847577.png">

_Originally posted by @sbalci in https://github.com/quarto-dev/quarto-cli/issues/402#issuecomment-1071377274_

**Comment by dragonstyle** [comment]
I'm having trouble reproducing this issue on the latest version of Quarto. Would you mind checking the version of Quarto that you're using and giving it another try on the latest version (I did continue to improve our date handling after the commit referenced in #402, so its possible that I fixed this issue with one of those changes).

I tried this document it rendered without issue:

```
---
date: "`r Sys.time()`"
date-format: "DD MMMM, YYYY"
author: Norah Jones
lang: tr
---
# Introduction

Hello world. this is an introduction
```

![Screen Shot 2022-03-18 at 6 52 09 AM](https://user-images.githubusercontent.com/261654/158990112-1f07afff-465d-42e5-840c-17c6760ca0ce.png)

In addition, I noticed the unrendered markdown in your author list - I'm going to take a look at making sure that rendered properly this AM!

**Comment by sbalci** [comment]
Dear @dragonstyle 
Thank you for your time. I am on v0.9.112
The date renders correctly if it is a standalone document. When using date under book menu, it gives the error. 

For authors, in book it renders in two different places. One is above the title and one is below.

Below is the code and repo link

```
project:
  type: book
  output-dir: docs

lang: tr

book:
  title: "Patoloji Atlası"
  subtitle: "Patoloji Atlası: Tıp Fakültesi ve Sağlık Bilimleri Öğrencileri İçin Patoloji Laboratuvar Notları: Görerek Öğrenin"
  author: |
    **Derleyen:** [Serdar Balcı](https://www.serdarbalci.com)
    **Yazarlar:** [Memorial Patoloji](https://MemorialPath.github.io) Hekim ve Teknikerleri
  description: |
    Patoloji Atlası: Tıp Fakültesi ve Sağlık Bilimleri Öğrencileri İçin Patoloji Laboratuvar Notları. Görerek Öğrenin.
    Patoloji Ders Notları ve Patoloji Atlası Memorial Patoloji arşivinden derlenen vakalardan oluşmaktadır.
  abstract: |
    Patoloji Atlası: Tıp Fakültesi ve Sağlık Bilimleri Öğrencileri İçin Patoloji Laboratuvar Notları.
    Görerek Öğrenin.
    Patoloji Atlası Memorial Patoloji arşivinden derlenen vakalardan oluşmaktadır.
    [Katkı yapmak ve kendi vakalarınız ekletmek için lütfen iletişime geçin](https://www.patolojiatlasi.com/katki.html).
  date: "`r Sys.time()`"
  date-format: "DD MMMM, YYYY"
  image: images/cover.png`
```

https://github.com/patolojiatlasi/patolojiatlasi.github.io/blob/main/_quarto.yml

**Comment by dragonstyle** [comment]
This is great, thank you. I'll get something in the works and update here when I've got it ready!

**Comment by dragonstyle** [comment]
Ok one thing I see right away is that you're writing the author block as:

```
author: |
    **Derleyen:** [Serdar Balcı](https://www.serdarbalci.com)
    **Yazarlar:** [Memorial Patoloji](https://MemorialPath.github.io) Hekim ve Teknikerleri
```

Which is causing the authors to appear in a new paragraph (rather than the expected 'author' element). I've fixed the issue with markdown rendering, but I think the way you'd like write this is either:

```
author:
    - "**Derleyen:** [Serdar Balcı](https://www.serdarbalci.com)"
    - "**Yazarlar:** [Memorial Patoloji](https://MemorialPath.github.io) Hekim ve Teknikerleri"
```
<kbd>
<img width="536" alt="Screen Shot 2022-03-18 at 8 49 12 PM" src="https://user-images.githubusercontent.com/261654/159100244-0e0e13cf-c59e-4ee3-9553-d432ad45bee5.png">
</kbd>

&nbsp;

or 

```
  author: 
    - name: "**Derleyen**, Serdar Balcı" 
      url: https://www.serdarbalci.com
    - name: "**Yazarlar**, Hekim ve Teknikerleri"
      affiliation: "Memorial Patoloji"
      affiliation-url: https://MemorialPath.github.io
```
<kbd>
<img width="452" alt="Screen Shot 2022-03-18 at 8 49 23 PM" src="https://user-images.githubusercontent.com/261654/159100245-f9ce80a3-acbd-467a-8922-930cb321780a.png">
</kbd>

&nbsp;

I've made the both the above render properly (e.g. the markdown in the author name or affiliation name with now render). I will be looking at the date next!

We will continue to improve the author and affiliation handling over the coming weeks, just FYI.

**Comment by sbalci** [comment]
Hi, Thanks.
- I was not using bullets because epub validation was giving error to not include <li>
- For authors please consider adding editor and contributor roles
Best wishes

**Comment by dragonstyle** [comment]
> I was not using bullets because epub validation was giving error to not include `<li>`

Since those `-` chars are outside the string, they're actually a yaml array of authors (e.g. a list of authors) rather than a markdown list- we know how to render multiple authors.

> For authors please consider adding editor and contributor roles

Definitely will do, thank you for the suggestion!

**Comment by sbalci** [comment]
Thank you very much for your efforts.
I used last-modified and it works also as Turkish language.
👍🏼 :) 

<img width="1445" alt="Screen Shot 2022-03-22 at 18 16 52" src="https://user-images.githubusercontent.com/7208830/159515881-0f2bcc07-b71b-43bf-b2c9-1fe346183a40.png">

**Comment by jtr13** [comment]
Love the `today` option. A note that it's not well documented, might want to add it here: https://quarto.org/docs/books/
