### ISSUE TITLE
cannot find ojs_define function within RStudio quarto doc

### ISSUE THREAD

**Issue by libjohn** [quarto-dev/quarto-cli#4363]
### Bug description

Running 

```{r}
ojs_define(my_ojs = my_sw)
```
yields error message:

> Error in ojs_define(my_ojs = my_sw) : 
  could not find function "ojs_define"

I've tried this on
- Windows 10 Enterprise ; RStudio 2022.12.0 ; Quarto v 1.1.179
- Windows 10 Enterprise ; RStudio 2022.12.0+353 ; Quarto 1.3.202 
- Ubuntu 22.04.1 LTS ; RStudio 2022.12.0 Build 353 ; Quarto 1.2.269

Qmd document attached.  Had to save as .md to get past the GitHub filters.  [foo_quarto.md](https://github.com/quarto-dev/quarto-cli/files/10744471/foo_quarto.md)

Any help greatly appreciated. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
`ojs_define` only works on a full document render (the "render" button), not with the "run cell" button on RStudio IDE. We are aware that this is confusing and will fix this in the near future. I believe this is the source of your bug, so I'm going to close this one. But if my suggestion doesn't solve your problem, please feel free to reopen it! Thanks.
