### ISSUE TITLE
asis from Rmarkdown

### ISSUE THREAD

**Issue by sbalci** [quarto-dev/quarto-cli#437]
Hi,
I want to make conditional rendering of chunks as described in: [rmarkdown cookbook
](https://bookdown.org/yihui/rmarkdown-cookbook/eng-asis.html)

The asis engine is recognised as python script and I get error below.

Is it possible to use asis engine for markdown content?

`Starting Jupyter kernel...Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 13, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
Python 3 installation:
  Version: 3.8.9
  Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
  Jupyter: (None)

Jupyter is not available in this Python installation.
Install with python3 -m pip install jupyter
`

**Comment by jjallaire** [comment]
`asis` should work fine in Quarto (just make sure you have the most recent version of knitr installed)

If you are having problems w/ your document being mis-detected as Python you can force the engine to knitr this way:

```yaml
---
title: "My Document"
engine: knitr
---
```

See the docs on this here: https://quarto.org/docs/computations/execution-options.html#engine-binding

That said, I'm not sure why that Python detection is happening here -- when I executed the simple example linked to above in Quarto locally it works fine (no Python issue).

**Comment by sbalci** [comment]
Hi @jjallaire 
Thank you.
Using engine as knitr as below solved the problem.

```
project:
  type: book
  output-dir: docs

lang: tr

book:
  title: "Patoloji Atlası"
  engine: knitr
```
