### ISSUE TITLE
Figures not adapting width for landscape

### ISSUE THREAD

**Issue by shirdekel** [quarto-dev/quarto-cli#4373]
### Bug description

I'm using a lua filter I got from [here](https://stackoverflow.com/a/73787848/13945974) to change the orientation of certain pages so that the figures within them end up larger, but they end up the same size as in the portrait pages. Increasing `out-width` doesn't help.

[2023-02-16_quarto.qmd.zip](https://github.com/quarto-dev/quarto-cli/files/10750788/2023-02-16_quarto.qmd.zip)
[2023-02-16_quarto.docx](https://github.com/quarto-dev/quarto-cli/files/10750790/2023-02-16_quarto.docx)
[docx-landscape.lua.zip](https://github.com/quarto-dev/quarto-cli/files/10750791/docx-landscape.lua.zip)

Quarto version: 1.2.313
Mac 12.6

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by shirdekel** [comment]
Here's how it should look using `officedown`:

[2023-02-16_officedown.Rmd.zip](https://github.com/quarto-dev/quarto-cli/files/10750868/2023-02-16_officedown.Rmd.zip)
[2023-02-16_officedown.docx](https://github.com/quarto-dev/quarto-cli/files/10750865/2023-02-16_officedown.docx)

**Comment by dragonstyle** [comment]
This appears to be resolved in Quarto 1.4
