### ISSUE TITLE
Wrong linux permissions when rendering

### ISSUE THREAD

**Issue by ucpresearch** [quarto-dev/quarto-cli#4380]
### Bug description

When rendering a qmd document to pdf using Rstudio's (2022.12.0 Build 353) quarto engine (v. 1.2.269) from the command line and using keep-tex, the .tex file permissions are 600, rather than the directory default. This is problematic in my usage case because I rely on group permissions. Knitting / rendering from the GUI interface makes no difference.

Linux: Ubuntu 22.04.1, texlive 2021.20220204-1, pandoc 3.0.1

**How to replicate**

Start with filename.qmd file with the following content:
```
---
format:
   pdf:
      keep-tex: true
output: 
   pdf_document:
      keep_tex: true
---

Hello
```

1. Render the file using Rmarkdown: `Rscript -e 'rmarkdown::render("filename.qmd")'`, list the file permissions
2. Do the same using quarto render, list file permissions. 

I get: 

1. 
```
-rw-rw-r--  1 user user    99 Feb 16 13:11 filename.qmd
-rw-rw-r--  1 user user  2347 Feb 16 13:21 filename.tex
-rw-rw-r--  1 user user 23111 Feb 16 13:21 filename.pdf
```

2.
 
```
-rw-rw-r--  1 user user    99 Feb 16 13:11 filename.qmd
-rw-------  1 user user  4760 Feb 16 13:25 filename.tex
-rw-rw-r--  1 user user  2702 Feb 16 13:25 filename.pdf
```

Thanks!

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
Thanks I can reproduce that. This will be hard to track... @dragonstyle do you have an idea ? @yihui do you know if we do something specific with how LaTeX is generating the document in **tinytex** ?

**Comment by ucpresearch** [comment]
If I had to guess what's going on, then there's a mktemp-equivalent somewhere in the code to create the tex file, and keep-tex simple renames it to the .tex output, rather than create a non-temporary file. It should happen before tex processing begins. 

One suspect is in ormat/pdf/format-pdf: 391:
`const outputFile = temp.createFile({ suffix: ".tex" });`.

**Comment by cderv** [comment]
Yes spot on. This is indeed in this part of the code that we are not keeping the right of the file when we process and copy back. 

Thanks

**Comment by dragonstyle** [comment]
I believe this is caused by this underlying issue in Deno:

https://github.com/denoland/deno/issues/16921

We have included an updated version of Deno which I confirmed fixes this issue in our Quarto pre-release. If you'd like you can give that a try at:

https://quarto.org/docs/download/prerelease

**Comment by cderv** [comment]
@dragonstyle I could reproduce on my side with pre-release... 🤔 Something must be wrong in my environment

**Comment by dragonstyle** [comment]
or vice versa 😉

**Comment by cderv** [comment]
@ucpresearch this should be fixed in next pre release built (very soon)
