### ISSUE TITLE
quarto create-project new book preview breaks chapter heading in mobile responsive mode

### ISSUE THREAD

**Issue by fortunewalla** [quarto-dev/quarto-cli#4388]
### Bug description

Is this a bug or am I doing something incorrect?

quarto version: 1.3.203
Windows 10
deno 1.30.3 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4

1) Created a new book
```
C:\sw>quarto create-project qbook2 --type book
Creating project at G:\gdac\qbook2:
  - Created _quarto.yml
  - Created index.qmd
  - Created intro.qmd
  - Created summary.qmd
  - Created references.qmd
  - Created cover.png
  - Created references.bib
```

2) started local preview without modifications.

```
C:\sw>cd qbook2

C:\sw\qbook2>quarto preview
Preparing to preview
[1/4] index.qmd
[2/4] intro.qmd
[3/4] summary.qmd
[4/4] references.qmd

Watching files for changes
Browse at http://localhost:3286/
GET: /
GET: /intro.html
GET: /intro.html
GET: /summary.html
GET: /intro.html
GET: /intro.html
```

### Desktop Mode: Chapter 1 Introduction heading is displayed properly.

![image](https://user-images.githubusercontent.com/7158596/219428463-3b0cf0b0-b5c3-4ac7-a6e8-dbc3ed7d2708.png)

### Mobile Mode: Chapter 1 Introduction heading is displaying its code as a string. 

![image](https://user-images.githubusercontent.com/7158596/219428937-9b09d004-d805-44cd-8d33-db7d5433c008.png)

![image](https://user-images.githubusercontent.com/7158596/219429134-b11fdf96-eb5a-407b-a88c-7c28128baacc.png)

"Preface" and "References as headings display properly but Chapters don't display properly in mobile or responsive mode.

```html
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="http://localhost:3286/intro.html">&lt;span class='chapter-number'&gt;1&lt;/span&gt;&nbsp; &lt;span class='chapter-title'&gt;Introduction&lt;/span&gt;</a>
  </li>
</ol>
```

### Similar for Chapter 2 in mobile mode.

![image](https://user-images.githubusercontent.com/7158596/219430709-fbee6e93-e26d-4bcf-ade8-5a1edd4df3dc.png)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report.

> quarto version: 1.3.203
> Windows 10
> deno 1.30.3 (release, x86_64-pc-windows-msvc)
> v8 10.9.194.5
> typescript 4.9.4

We don't bundle deno 1.30.3, so I'm a little confused. Can you provide the output of `quarto check` instead?

**Comment by fortunewalla** [comment]
> Thanks for the report.
> 
> (fwiw, we don't bundle deno 1.30.3, so the output of `quarto check` is more useful)
> 
> With that said, I can repro this locally.

Yes, while running quarto, it kept giving the message that deno upgrade is available, so I upgraded it from the cli.

```
C:\sw>quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 2.19.2: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.203
      Path: C:\sw\quarto\bin
      CodePage: 65001

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.15 (Conda)
      Path: C:/sw/envs/jupyter/python.exe
      Jupyter: 5.1.0
      Kernels: ir, python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.2
      Path: C:/sw/R/App/R
      LibPaths:
        - C:/sw/R/App/R/library
      rmarkdown: 2.19

[>] Checking Knitr engine render......OK
```

Thanks for the quick response and to all your efforts in this monumental attempt of trying to standardize scientific & documentation publishing across frameworks. 👍🏼

**Comment by cscheid** [comment]
> Yes, while running quarto, it kept giving the message that deno upgrade is available

Oof, that's super annoying, I'm sorry. We're supposed to have a command-line flag to disable that warning, but clearly it's not working for you. @cderv do you see this upgrade nag on windows?

**Comment by fortunewalla** [comment]
> > Yes, while running quarto, it kept giving the message that deno upgrade is available
> 
> Oof, that's super annoying, I'm sorry. We're supposed to have a command-line flag to disable that warning, but clearly it's not working for you. @cderv do you see this upgrade nag on windows?

Luckily my CLI window was still open, this is what the message looks like

```
C:\swc>cd qweb

C:\sw\qweb>quarto preview
A new release of Deno is available: 1.28.2 → 1.30.3 Run `deno upgrade` to install it.
Terminating existing preview server....DONE

Preparing to preview

Watching files for changes
Browse at http://localhost:6925/
GET: /
GET: /
GET: /
```

**Comment by cscheid** [comment]
From my shell:

```
$ cd quarto-cli
$ rg DENO_NO_UPDATE_CHECK
package/scripts/common/quarto
154:export DENO_NO_UPDATE_CHECK=1

package/scripts/windows/quarto.cmd
97:SET "DENO_NO_UPDATE_CHECK=1"
```

@cderv I wonder if this syntax is wrong.

**Comment by cderv** [comment]
> @cderv do you see this upgrade nag on windows?

Yes I have it. I am just ignoring as I thought it was something messed up on my side. I'll check the syntax now I know where this is coming from
