### ISSUE TITLE
Ensure deno upgrade warning deactivation works on Windows 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#4394]
> Yes, while running quarto, it kept giving the message that deno upgrade is available

Oof, that's super annoying, I'm sorry. We're supposed to have a command-line flag to disable that warning, but clearly it's not working for you. @cderv do you see this upgrade nag on windows?

_Originally posted by @cscheid in https://github.com/quarto-dev/quarto-cli/issues/4388#issuecomment-1433511448_

## Context 

https://deno.com/blog/v1.27#upgrade-checker

> We took special care to ensure that these checks don't impact the performance of your applications - they only happen in the background at most once a day. This feature can be disabled entirely by setting the environment variable: DENO_NO_UPDATE_CHECK=1

Somehow it does not seem to work on Windows

**Comment by cderv** [comment]
This is hard to test or understand why it does not seem to work. We correctly set the variable it seems 
https://github.com/quarto-dev/quarto-cli/blob/b5c6ddc37cb2c34e7d6da01cff13b640e97c22cc/package/scripts/windows/quarto.cmd#L97

Maybe it is not in the right place. 

@dragonstyle for the `quarto.exe` on Windows, what is the file that we execute really ? Is this still `quarto.cmd` but packaged ?

**Comment by cderv** [comment]
Oh so this may be it: 
https://github.com/quarto-dev/quarto-cli/blob/360ace09d1f3e78592bbfbb4c332c06d818746f6/package/launcher/src/main.rs#L70-L74

We probably need to add `DENO_NO_UPDATE_CHECK` env var at this place then. 

We do this in all our other script I think
https://github.com/search?q=repo%3Aquarto-dev%2Fquarto-cli%20DENO_NO_UPDATE_CHECK&type=code

**Comment by dragonstyle** [comment]
Just fixed it...

**Comment by cderv** [comment]
Awesome thank you ! Will see if this disappear for real now.

**Comment by neellab-umd** [comment]
I realize this issue is closed but the Deno upgrade message is still appearing on Windows 10 with RStudio "Desert Sunflower" Release (cd7011dc, 2023-10-16) Build 494.

**Comment by cscheid** [comment]
@neellab-umd What do you get as the output of `quarto check`?

**Comment by neellab-umd** [comment]
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/mneel/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.44
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
> Version: 1.3.450

This was a 1.4 fix.

<img width="408" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/fa080fad-dc8d-40a9-aa15-0bc814be205c">
