### ISSUE TITLE
`quarto publish --profile` is not working

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#4396]
I haven't been able to get this working. Here's a minimal repo: [https://github.com/andrewpbray/publish-profile](https://github.com/andrewpbray/publish-profile).

`quarto render --profile alternate` works just fine and `quarto publish` works just fine (it goes to `gh-pages`). But when I run `quarto publish --profile alternate` I get `ERROR: Publishing source 'alternate' not found`.

Is there something I'm missing with the syntax?

I have been able to publish profiles using environmental variables (see [this workflow](https://github.com/stat20/course-materials/blob/main/.github/workflows/publish-partial.yml)) but doing it via an option on `quarto publish` is where I get hung up.

_Originally posted by @andrewpbray in https://github.com/quarto-dev/quarto-cli/discussions/4076#discussioncomment-5000552_
      

It is documented 

````bash
$ quarto publish --help

  Usage:   quarto publish [provider] [path]
  Version: 99.9.9

  Description:

    Publish a document or project. Available providers include:

     - Quarto Pub (quarto-pub)
     - GitHub Pages (gh-pages)
     - RStudio Connect (connect)
     - Netlify (netlify)

    Accounts are configured interactively during publishing.
    Manage/remove accounts with: quarto publish accounts

  Options:

    -h, --help              - Show this help.
    --id          <id>      - Identifier of content to publish
    --server      <server>  - Server to publish to
    --token       <token>   - Access token for publising provider
    --no-render             - Do not render before publishing.
    --no-prompt             - Do not prompt to confirm publishing destination
    --no-browser            - Do not open a browser to the site after publishing
    --log         <level>   - Path to log file
    --log-level   <level>   - Log level (info, warning, error, critical)
    --log-format  <format>  - Log format (plain, json-stream)
    --quiet                 - Suppress console output.
    --profile               - Active project profile(s)
 ````

But not working somehow it seems.

**Comment by cderv** [comment]
Is this because missing from ? 
https://github.com/quarto-dev/quarto-cli/blob/b01c1dfaa69ccfe7beb053da94861071a4ca15e0/src/command/publish/options.ts#L8-L15

We add to the help of the command through a global addition so unsure if all options are supposed to be supported 
https://github.com/quarto-dev/quarto-cli/blob/b01c1dfaa69ccfe7beb053da94861071a4ca15e0/src/quarto-core/profile.ts#L33-L41
https://github.com/quarto-dev/quarto-cli/blob/b01c1dfaa69ccfe7beb053da94861071a4ca15e0/src/quarto.ts#L137-L141

**Comment by jjallaire** [comment]
The problem is that `publish` in particular is looking for positional arguments (so it is reading the profile args directly). The solution is to remove the `--profile` arg as soon as we read it: https://github.com/quarto-dev/quarto-cli/commit/4b28364be7671c6b051faabf59389576c0d2fcbd
