### ISSUE TITLE
code blocks have wrapping

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#44]
Quarto version: 0.1.296

Using a Markdown document with  very-long-line code block:

````markdown
---
title: wrapping
---

A very long fixed-font block.

```bash
export SOME_VERY_LONG_VARIABLE="https://${SOME_VERY_LONG_SERVER_NAME}:${SOME_VERY_LONG_PORT}/"
```
````

Rendering this document:

```bash
quarto render index.md
```

Produces the layout (on Safari):

<img width="822" alt="image" src="https://user-images.githubusercontent.com/362187/123644734-a5959300-d7f3-11eb-8260-a9e191b5957b.png">

The `export` is on a separate line than the variable definition.

Additionally, the scrollable region has the following appearance when scrolled to the right:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/362187/123644844-c362f800-d7f3-11eb-8415-98982dc8ed90.png">

The code-block text bleeds out of the grey box is is supposed to be contained in.

On hover:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/362187/123644943-dfff3000-d7f3-11eb-8aa9-5ef679e7402b.png">

The copy button stays with the box, which means it is to the left of the end of the text.

**Comment by aronatkins** [comment]
In comparison, a simple `pandoc` render (using zenburn to make the boundaries more obvious):

```bash
/Library/Quarto/bin/pandoc --self-contained --highlight zenburn index.md -o index.html
```

produces no line wrapping:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/362187/123645445-5a2fb480-d7f4-11eb-974b-f8886170c4d5.png">

and correctly bounds the code:

![Uploading image.png…]()

**Comment by jjallaire** [comment]
Thanks! Fixed via https://github.com/quarto-dev/quarto-cli/commit/047d1423465fadce07451b585f44669e1dea458c

cc @dragonstyle could you review this?
