### ISSUE TITLE
VS Code internal preview not working anymore

### ISSUE THREAD

**Issue by shifubear** [quarto-dev/quarto-cli#4408]
I've been using Quarto for my personal page and blog for a few months now, but starting a few weeks back I haven't been able to access the internal preview feature from VS code. When I click render, the terminal executes the command
`quarto preview /Users/shio
nfukuzawa/shifubear.github.io/posts/lglar-ch3/index.qmd --no-browser --no-watch-inputs`

Then after generating the preview, prints out this message and I get no response after
`Browse at <jupyterhub-server-url>/user/myemail/proxy/4560/posts/lglar-ch3/index.html`
I'm not sure if there is not supposed to be a jupyterhub-server-url here, and haven't been able to find anyone having similar issues. I've tried uninstalling and reinstalling Quarto but it doesn't seem to help. 

Any suggestions on how to fix this?

**Comment by shifubear** [comment]
@jjallaire 
I'm running it locally on my computer, and I did have the environment variable `$JUPYTERHUB_USER` set to my email address. I may have set it for some other application I was running before, but I think I can safely remove it. 
I tried removing it and the preview is working now! This is great to know, thanks so much for the help :D

**Comment by jjallaire** [comment]
That's great to hear! The other change I put in should also take care of it (as we now look for both `JUPYTERHUB_USER` and another well known JupyterHub environment variable to more faithfully determine whether we are on JupyterHub)
