### ISSUE TITLE
RevealJS Hidden TeX macros not defined

### ISSUE THREAD

**Issue by agerlach** [quarto-dev/quarto-cli#441]
Defining macros per [docs](https://quarto.org/docs/authoring/markdown-basics.html#equations) like

```
::: {.hidden}
$$
 \def\RR{{\bf R}}
 \def\bold#1{{\bf #1}}
$$
:::

$$\RR$$
```

Does not work with Revealjs. The output is simply `\RR`.  The same occurs when using a hidden slide, e.g. 

```
## Setup {visibility="hidden"}
$$
\def\RR{{\bf R}}
\def\bold#1{{\bf #1}}
$$

## Title
$$\RR$$
```

However, doing
```
## Title
$$
\def\RR{{\bf R}}
\def\bold#1{{\bf #1}}
$$

$$\RR$$
```

Does work.

**Comment by jjallaire** [comment]
The first variation is definitely working for me (on OSX w/ Chrome, Safari, and Firefox). What is your configuration?

**Comment by agerlach** [comment]
Updating to Quarto 0.9.123 fixes this issues.

**Comment by jjallaire** [comment]
For the second variation `visibility="hidden"` slides are actually removed entirely from the HTML (so the LaTeX therein never executes). I would use the `.hidden` idiom here.

**Comment by agerlach** [comment]
I figured that may be the case. I noticed I could execute code chunks in a hidden slide, so I had been using that to essentially create hidden "font-matter" slides. I'll move forward with `.hidden`. Thanks
