### ISSUE TITLE
`hash-type: number` breaks alignment on title slide

### ISSUE THREAD

**Issue by wklimowicz** [quarto-dev/quarto-cli#4418]
### Bug description

Using `hash-type: number` misaligns the title slide on revealjs. Reprex:

````qmd
---
title: Test
subtitle: Test
author: Test
institute: Test
date: today
format:
  revealjs:
    hash-type: number # "title" works fine
---
````

Version with `hash-type: number`
![Broken_Version](https://user-images.githubusercontent.com/62679873/219854721-1916fb66-f79d-438f-aa6f-9f956af87ae9.png)

Version with `hash-type: title`
![Working_Version](https://user-images.githubusercontent.com/62679873/219854738-3b097a5d-85e7-45d6-a8e7-ee1572d265d4.png)

---

Using the latest nightly build on Fedora 37.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
Here is the HTML diff between two options. 
````diff
-<section class="quarto-title-block">
+<section id="title-slide" class="quarto-title-block center">
   <h1 class="title">Test</h1>
   <p class="subtitle">Test</p>
````

Somehow the id is removed (not set) and we use that for styling

https://github.com/quarto-dev/quarto-cli/blob/f00d8fd7fee31e2bf5d4e30ec81d87bb2e43479d/src/resources/formats/revealjs/quarto.scss#L201-L207

Either an issue with hash value effect, or just some CSS adjustment for when this hash is used.

**Comment by cderv** [comment]
We are removing the id explicitly , which mess up the CSS has it is based on it.
https://github.com/quarto-dev/quarto-cli/blob/1366f078a03d14af2f5ee532eb03214a74b209a6/src/format/reveal/format-reveal.ts#L388-L395

We're removing the id otherwise, the title slide won't have a number as `hash-type` is defining. 

One solution could be to adapt the CSS to target without the id
