### ISSUE TITLE
Setting working directory

### ISSUE THREAD

**Issue by davidbudzynski** [quarto-dev/quarto-cli#442]
Not sure if this isn't documented or isn't possible but how can I pass a path to be used as a working directory? I usually have the src folder with code and one folder up is the top of a "project" although I'm not using rstudio and projects.

**Comment by jjallaire** [comment]
If you create a _quarto.yml project file in the root directory you can
specify an execute-dir there:
https://quarto.org/docs/projects/code-execution.html#working-dir

**Comment by davidbudzynski** [comment]
Thanks for pointing me to this, though I think having a `.yml` file in the root directory is quite messy (just my opinion!). I'd be neat if I could either put it into the `./src/` directory, or skip this file altogether if I'm working with only 1 `.qmd` file. Is it possible to set a root directory directly from a quarto document?

**Comment by jjallaire** [comment]
You can do this:

```bash
quarto render src/document.qmd --execute-dir .
```

**Comment by davidbudzynski** [comment]
thanks!
