### ISSUE TITLE
Mermaid diagram color scheme and formating not as specified

### ISSUE THREAD

**Issue by bryanhanson** [quarto-dev/quarto-cli#4421]
### Bug description

* Mac OS 12.6.3.
* Latest Quarto downloaded a few minutes ago by pulling and building locally.
* Behavior checked on Safari, Chrome and Firefox, and behavior is the same.
* Running Quarto from the command line
* Complete repo is [here](https://github.com/bryanhanson/CSR) and the page with the bad behavior is [here](https://github.com/bryanhanson/CSR/tree/master/posts/2022-09-26-Linear-Alg-Notes-Pt4).

Not sure what's going on here.  I'm hoping you all will recognize the problem.  Glad to build a MWE if the problem is not immediately apparent.  This was working, not sure when it broke.

A Mermaid diagram on my blog [here](https://chemospec.org/posts/2022-09-26-Linear-Alg-Notes-Pt4/Linear-Alg-Notes-Pt4.html) has the wrong colors, the html formatting of some labels is displayed rather than rendered, and the arrows appear to be pure white (they seem invisible/missing but under the right conditions you can see them as white on a barely grey background).

The Mermaid code works fine if I put it in [Mermaid Live](https://mermaid.live/edit#pako:eNqNkstOwzAQRX_FMhtXKipdsImqIEpJn3QDS2-cZNpa8qM4NiVE-XfcKUGiyoKdde6ZK4_lhha2BJrQnbKn4iCcJ28zbh6ZUIpo4Z0soCKT3I1SYsgn0QNye5uSJ-bs6Tofx9wM4jAqM1ZYFbTpaxn_WFGbsuo9CAd92rlsimXPLByP4EhUhNkHJRxa3cyvl7G4xj-8edNM8hSkP4CbjPIULVmRSl6mHtq2Uxeo2j-aNB_gvMwVoLhAcdk0MSql2FsjlPwSXbzEeIWxsU4LhXiFeM2qWms43y_ebo1sw7qWiDaIXpgswXjp60E3ucVC6_zBooul24vNTeVrBWROdlKp5CbLsrvsvqOLXrrspateur2idEg1xM1kGb9Sww0hnMa31cBpEo8l7ERQnlNu2qiK4O1rbQqaeBdgSMOxFB5mcWcn9AW2379o2lU), here's a png of what it should look like:

![mermaid-diagram-2023-02-17-210328](https://user-images.githubusercontent.com/140350/219877509-881f0aea-09bb-4dba-8553-8a58f34ba29d.png)

Screenshot of (part of) the mis-behaving version (also visible at the link to the post above):

<img width="781" alt="Screen Shot 2023-02-18 at 10 21 00 AM" src="https://user-images.githubusercontent.com/140350/219877794-9c73fefd-80c8-4bce-b303-a5100b922cf0.png">

Any ideas of what's happening?  Thank you!

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by bryanhanson** [comment]
This appears to have something to do with blog processing, because, if I do a separate project with a single page the diagram appears correctly (simple page appended below).  If the same page is in a blog project, the diagram renders with the formatting problems described above.

mwe.qmd:

```
---
title: "Problematic Mermaid Diagram"
format:
  html
----

Mermaid diagram follows... It appears fine in a single page project, but incorrectly formated in a blog project.

```{mermaid}
%%| label: fig-flow
%%| fig-cap: "Heiarchical relationships between different types of matrices. *Blue Rectangles* denote matrices with particular, recognizable *structures*.  *Pink Hexagons* indicate properties that can be *queried*."
flowchart TD
A(all matrices <br/> n x m) --> C(row matrices <br/> 1 x n)
A --> D(column matrices <br/> n x 1)
A ---> B(square matrices <br/> n x n)
B --> E(upper triangular<br/>matrices)
B --> F(lower triangular<br/>matrices)
B --> G{{<b>either</b><br/>is singular?}}
B --> H{{<b>or</b><br/>is invertible?}}
H --> I{{is diagonalizable?}}
I --> J{{is normal?}}
J --> K(symmetric)
K --> L(diagonal)
L --> M(identity)
J --> N{{is orthogonal?}}
N --> M
style G fill:#FFF0F5
style H fill:#FFF0F5
style I fill:#FFF0F5
style J fill:#FFF0F5
style N fill:#FFF0F5
```

````

**Comment by bryanhanson** [comment]
Further update: creating a MWE blog project from the command line and adding the Mermaid code to `posts/post-with-code/index.qmd` produces a properly formatted diagram.  So, I need to dig deeper to find out what's up with my blog structure...

**Unless you recognize the problem when you see the diagram, don't work on this until I troubleshoot a bit more.  I will comment and close if I can find the problem.  Thanks.**

**Comment by cscheid** [comment]
@bryanhanson The defaults _have_ changed: https://quarto.org/docs/prerelease/1.3/mermaid.html

It's likely we've missed some classes, but I'm giving you that info in case it helps you as well.

**Comment by bryanhanson** [comment]
Thank you.  Fixed everything except html tags for bold, e.g. `<b>text</b>` is passed through verbatim.  Tag `<br/>` is honored.

**Comment by bryanhanson** [comment]
Closing, I can work on the remaining details another time.  Thank you.

**Comment by cscheid** [comment]
Thanks for closing it, but I'm going to keep this open for our own internal tracking!

**Comment by cscheid** [comment]
I confess I don't understand why `<br>` tags are resolving correctly, but `<b>` are not, and specifically why that's working on mermaid's live editor. I suspect it's some mermaid version issue. We've already updated mermaid for 1.3, and we try to limit the number of library upgrades per release (so that we don't spend all of our time tracking downstream dependencies).

We'll bump all of our dependencies in about 6 weeks when we move to 1.4 development, and then I'll revisit this.

**Comment by bryanhanson** [comment]
Sounds good.  I thought some tags are fine but others are not was pretty peculiar too.  Not sure how that even happens.  Appreciate everything you all are doing.

**Comment by cscheid** [comment]
I can no longer reproduce this in 1.6 prereleases:

![Image](https://github.com/user-attachments/assets/3704c0dc-abfb-4666-b71c-84bbc88343e9)

I'm going to close this one, but please reopen if you can provide a reprex.
