### ISSUE TITLE
Footnote was broken with quarto v0.9.116

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#443]
I rendered a revealjs slide with the latest version and the footnote was broken.
(The footnote page is not generated at the end of the slide)

**Comment by eitsupi** [comment]
I checked the commit message, is this an intentional change?
8f3f634f6be0d6d01ead231271c64b07abb25c41

**Comment by eitsupi** [comment]
Ok, I checked the updated guide.
https://quarto.org/docs/presentations/revealjs/#asides-footnotes

Would it be possible to combine the footnotes into a page at the end using the previous method?
(I simply didn't want to mess up the layout since I had created the current slides with the assumption that that would happen)

**Comment by jjallaire** [comment]
Yes, we'll provide an option for you to get the previous behavior (should have that in within the next day or two)

**Comment by jjallaire** [comment]
You can now specify `reference-location: document` to get the old behavior. See updated docs here: https://quarto.org/docs/presentations/revealjs/index.html#asides-footnotes

**Comment by eitsupi** [comment]
Thanks for the quick fix!
I got the same output as before.
