### ISSUE TITLE
Is `_quarto.yml` in the parent directory affected when trying to render files in subdirectories?

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#444]
I tried to generate HTML files in a subdirectory, but it did not work as it seems to be affected by the project settings in the parent directory.

I have a project with the following directory structure.

```shell
$ tree
.
├── _quarto.yml
└── sub-proj
    └── index.qmd

1 directory, 2 files
```

I would like to obtain the following outputs.

```shell
$ tree
.
├── _quarto.yml
└── sub-proj
    ├── index.html
    └── index.qmd

1 directory, 3 files
```

However, when I move to a subdirectory and execute the `quarto render index.qmd` command, the output seems to be affected by the settings in the parent directory, as shown below.

```shell
$ tree
.
├── _quarto.yml
├── _site
│   └── sub-proj
│       └── index.html
└── sub-proj
    └── index.qmd

3 directories, 3 files
```

The actual project is below and the target subdirectory is [here](https://github.com/eitsupi/tokyorslide/tree/3dff50c9d73f84bd1b53b0538788e4233aaa9a60/tokyor_97).
<https://github.com/eitsupi/tokyorslide/tree/3dff50c9d73f84bd1b53b0538788e4233aaa9a60>

**Comment by jjallaire** [comment]
You basically just need to make sure the subproject directories are not in the render list for the main project. There are 2 ways to do this:

1. Use an explicit render list for the parent project (rather than auto-rendering recursively which is the default). For example:

    ```yaml
    project:
      render: 
        - index.qmd
        - about.qmd
    ```


2. Name the subproject directories with a leading underscore (e.g. `_sub-proj`) which will also avoid their being included in the parent render.

**Comment by eitsupi** [comment]
I am sorry that my explanation was not adequate.
My question is that even when I am in a subdirectory (e.g. execute `cd sub-proj`) the `quarto render` command seems to be affected by the `_quarto.yml` in the parent directory.

Does quarto find the root directory of the project in some way (e.g. with or without a `.git` directory) and recursively explore the parent directories?

**Comment by jjallaire** [comment]
Yes, `_quarto.yml` is indeed recursive (without this the scale/complexity of projects would be severely limited).  The tips I provided in the previous message were ways to make sure that your subdirectories escape the recursive reach of `_quarto.yml`

**Comment by eitsupi** [comment]
Thank you for your explanation. (Perhaps it would be good if the rules for quarto to look for `_quarto.yml` are clearly stated somewhere)

And as explained in #446, I got the output I wanted by running `quarto render sub-proj/index.qmd` after setting `_quarto.yml` like the following!

```yml
project:
  render: 
    - /index.qmd
```

```shell
$ tree
.
├── _quarto.yml
└── sub-proj
    ├── index.html
    └── index.qmd
```
