### ISSUE TITLE
Confluence Pre-release Highlight Docs

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#4460]
Review and update: https://quarto.org/docs/prerelease/1.3/confluence.html (once published)

**Comment by allenmanning** [comment]
It is awesome to see you improving this, please let me know if I can help support this work.  🙌

**Comment by cwickham** [comment]
Audience: Quarto users publishing to Confluence

I think, the existing docs take a little too long to get to the "getting stuff on Confluence step". Lean more on most early users knowing Quarto, and lead with an example of getting a page published. Then, dive into details of key differences a user needs to wrap their head around: Quarto project structure vs. Confluence page structure; Quarto publishing model vs. Confluence publishing model. Finally, cover details and limitations. 

# Rough Outline of Proposed Docs

## Overview

Expand existing to add motivation: why manage Confluence content with Quarto? Use markdown. Put in version control. Single source of truth. Code output. Quarto natives publish to internal corporate venues. 

Show visual that helps cement what this looks like. 

* Side-side: .qmd, rendered page in Confluence
* Side by side: directory listing in Quarto; sidebar navigation in confluence

## Publishing a Document to Confluence

Get to meat (`quarto publish confluence`) early, and avoid most details on first run. You want someone to be able to test this out with their own Confluence site ASAP.

Do a single document:

```
format: confluence-html
```

Show locally rendered version.

Use existing Publish section, but maybe up front describe the things you need to do first (figure out your email, generate token, select destination).

Show Confluence rendered site. 

Point to other parts of docs: content limitations, publishing model, what happens when you publish again, how to publish a collection of docs...

## Publishing a Collection of Pages

Now introduce a collection of pages / project: 

```
project:
  type: confluence
```

Publishing process: 
```
quarto publish confluence
```

How project structure (folders and files) translates to Confluence structure (pages and nested pages).  Maybe some examples with publishing to space, vs. parent page. 

## Publishing Workflow

Workflow in Quarto confluence vs. Confluence
Quarto: One "publisher", collaboration happens outside Confluence 
Confluence: Many creators and editors, collaborating in Confluence

Permissions / Data Loss / One way flow model

No permissions in Free spaces

Existing "_publish.yml" and "Account Management" sections in here?

## Limitations

Limitations of page content, using existing table, but with edits:

* Order these based on Description
* What is the difference in meaning between "yet" "future"?

Limitation in terms of other Confluence features e.g. commenting

* Page level emojis and comments are preserved across comments
* Inline level comments are not preserved

**Comment by cwickham** [comment]
@allenmanning Do you have a favorite .qmd that highlights how things translate to Confluence that might be nice to use for the examples/screenshots?
