### ISSUE TITLE
Reference to old or pre-release RStudio/Quarto versions

### ISSUE THREAD

**Issue by jthomasmock** [quarto-dev/quarto-cli#4463]
Tag @dragonstyle per discussion, here are the pre-release references. It might be helpful to formalize the strategy of if y'all do or do not want to indicate a minimum version when introducing new features that aren't backported.

Reference to 0.9: [Mermaid Diagrams](https://github.com/quarto-dev/quarto-web/blob/5a79cba1d466d55da139cd447c9f3fe1fc812d4d/docs/authoring/diagrams.qmd#L22)
Reference to 1.0.15: [Shortcodes](https://github.com/quarto-dev/quarto-web/blob/5a79cba1d466d55da139cd447c9f3fe1fc812d4d/docs/extensions/shortcodes.qmd#L105)
Reference to 0.9: [YAML Intelligence](https://github.com/quarto-dev/quarto-web/blob/5a79cba1d466d55da139cd447c9f3fe1fc812d4d/docs/tools/vscode.qmd#L124)

**Comment by cwickham** [comment]
Another example via Slack https://quarto.org/docs/computations/r.html#rstudio

**Comment by allenmanning** [comment]
As part of starting up a new milestone should clean up these out-of-date references?  Are there opportunities to reduce toil through automation?

**Comment by cwickham** [comment]
I think at the very least we could standardize references to versions with include shortcodes. For example, we might have _requires-1.3.qmd, and _requires-1.2.qmd we can pull in with `{{< include  _requires-1.3.qmd >}}` wherever we need alert that a new (or newish) version is required for a feature. 

It might not be completely automated, but at least retiring old alerts would be as easy as a search and replace.
