### ISSUE TITLE
social media share button configuration

### ISSUE THREAD

**Issue by sbalci** [quarto-dev/quarto-cli#447]
Hi,

LinkedIN and Facebook shares contain metadata code characters. See images. How can I further configure shared links?

<img width="644" alt="Screen Shot 2022-03-19 at 21 12 16" src="https://user-images.githubusercontent.com/7208830/159133636-888a84f5-047a-4cd7-897a-941ee3a1bc6f.png">

<img width="542" alt="Screen Shot 2022-03-19 at 21 12 28" src="https://user-images.githubusercontent.com/7208830/159133644-204a67d9-c877-4cbf-b54b-e091df0eb173.png">

**Comment by dragonstyle** [comment]
Sorry about that! This is fixed here: 219be4a4950c0c3d2faefacfbde9f1594d3e2451 . A fresh release build is running right now and installers should be available within a few minutes. This will be available in build 119.

**Comment by sbalci** [comment]
tested with 119 and it works 👍🏼 
Thank you
