### ISSUE TITLE
Add Support: Confluence Raw Block

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#4472]
### Description

Add support for Confluence Raw Blocks that let's CSF just "pass-through" to Confluence.

### Steps to Reproduce
- Create the following quarto document

````
---
title: "Simple Doc - Confluence Raw Block"
format: native
---

```{=confluence}
<ac:task-list>
    <ac:task>
        <ac:task-id>1</ac:task-id>
        <ac:task-status>incomplete</ac:task-status>
        <ac:task-body><span class="placeholder-inline-tasks">Al</span></ac:task-body>
    </ac:task>
    <ac:task>
        <ac:task-id>2</ac:task-id>
        <ac:task-status>incomplete</ac:task-status>
        <ac:task-body><span class="placeholder-inline-tasks">JJ</span></ac:task-body>
    </ac:task>
</ac:task-list>
```
````
- Publish to Confluence

### Expected Result
The task list (and other such Raw Blocks) are preserved.

### Actual Result
It is filtered out.

**Comment by allenmanning** [comment]
@cwickham This may require your review as well.  It seems that we could add this to the docs for more advanced users.

There are some more [examples here](https://github.com/rstudio/quarto-confluence-test/blob/main/simple-documents/confluence-raw-blocks.qmd).

**Comment by cwickham** [comment]
@allenmanning I think the feature is cool, and deserves to be in the docs. It could naturally fit in the Authoring Section of the pre-release highlights, with maybe one example. We could leave it at that with the understanding, if people are are doing that, they'll be able to figure the details out on their own, or we could link out to something else for more detail. 

How do you figure out the XHTML for macros. E.g. I found [this page](https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html) describing some things like emojis and task lists, but how did you figure out how to get a page tree, or a decision?

**Comment by cwickham** [comment]
FYI I merged in the current highlight release docs. Let's use this issue (or create a new one) to keep track of additional changes we want to make.

**Comment by allenmanning** [comment]
I would prefer using this issue as I'd like to be disciplined about our Definition of Done.  It isn't releasable to customers without the proper docs.
