### ISSUE TITLE
Corruption of bootstrap.min.css

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#448]
Quarto 0.9.100 on Linux.  Installed via .deb file.

I made a YAML syntax error in _quarto.yml, and got the following error output when executing "quarto render" on the command line:

```
ERROR: Theme file compilation failed:

Error: Undefined variable.                                                                                                                                                     
    ╷                                                                                                                                                                          
921 │ $navbar-bg: $light !default;                                                                                                                                             
    │             ^^^^^^                                                                                                                                                       
    ╵    
```

I then reverted my project directory to a previous working version, deleted the _site dir and all the /tmp/quarto-sessions dirs.  A new render completed without error, but now the output files are corrupted -- when I execute "quarto preview" and view in my browser the error text appears at the top of each html file, and it appears that proper css files didn't load.

When I look in the file _site/site_libs/bootstrap/bootstrap.min.css this is the entire content of the file:

```
/* Error: Undefined variable.
 *     ,
 * 921 | $navbar-bg: $light !default;
 *     |             ^^^^^^
 *     '
 *   /tmp/quarto-session57e1c2f0/64698842/8abdecaescss 921:13  root stylesheet */

body::before {
  font-family: "Source Code Pro", "SF Mono", Monaco, Inconsolata, "Fira Mono",
      "Droid Sans Mono", monospace, monospace;
  white-space: pre;
  display: block;
  padding: 1em;
  margin-bottom: 1em;
  border-bottom: 2px solid black;
  content: "Error: Undefined variable.\a     \2577 \a 921 \2502  $navbar-bg: $light !default;\a     \2502              ^^^^^^\a     \2575 \a   /tmp/quarto-session57e1c2f0/64698842/8abdecaescss 921:13  root stylesheet";
}

```
Note that the specified quarto-sessions dir no longer exists.

It seems as though the original command line error overwrote quarto's internal copy of bootstrap.min.css, and the quarto program itself now appears to be corrupted and won't output a proper bootstrap.min.css file in new render attempts.  I can no longer get the quarto program to produce proper output from my previously-working project directory.

**Comment by jjallaire** [comment]
@dragonstyle Will know more about this, but if you look in the XDG cache directory (XDG_CACHE_HOME) you should see a Quarto directory that has this cached bootstrap.min.css in it. If you delete that directory perhaps it will clear the error? In any case we of course shouldn't ever let that corrupted file enter the cache.

**Comment by blacksqr** [comment]
I found the corrupt file at $HOME/.cache/quarto/sass/9161419e6f82ea4435380a70856fa72b.css

I deleted the entire quarto directory and reran "quarto render", and the project html files again appear as expected.

Thanks for preserving my sanity, at least for tonight.

**Comment by dragonstyle** [comment]
If you wouldn't mind, I'd be very curious to identify the invalid YAML that produced this error - it seems that beyond not caching the erroneous result, it would be great if we could provide a more helpful error message...

**Comment by blacksqr** [comment]
Sorry, I didn't preserve the erroneous code, I reverted my changes before I realized the it would be the source of so much trouble.  If the issue occurs again I'll make more of an effort to capture the relevant info.
