### ISSUE TITLE
"HTML themes more" article not linked to sidebar

### ISSUE THREAD

**Issue by jthomasmock** [quarto-dev/quarto-cli#4503]
This page is currently an orphaned page: https://quarto.org/docs/output-formats/html-themes-more.html - it has no left-sidebar.

The link to this page can be seen at: https://quarto.org/docs/output-formats/html-themes.html#:~:text=For%20more%20information%20about%20available%20Sass%20variables%2C%20see

May need to be added at: https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml#L142-L149 ?

![image](https://user-images.githubusercontent.com/29187501/192337002-b2159fb6-174c-4214-9755-c1545657d286.png)

**Comment by cscheid** [comment]
We have some pages that are missing from the sidebar by design.

We want them there to send people links to it when applicable, but we don't want to overwhelm users with in-the-weeds content that will more likely than not confuse them.
