### ISSUE TITLE
added another exampe to the gallery (website)

### ISSUE THREAD

**Issue by jcolomb** [quarto-dev/quarto-cli#4506]
https://fluidsyndicate.com

very simple website, but using an advanced R tool for visualisation, and listing page for non-blog content.

an open source art project :)

**Comment by cscheid** [comment]
@jcolomb Thanks for the feedback. Do you mean you'd like to add that to our gallery? If so, can you open a PR?

**Comment by jcolomb** [comment]
I had issue finding the right place, so that previous example were added via an issue here.... if you can point me to the right file, I could add it in a PR.

**Comment by cscheid** [comment]
https://github.com/quarto-dev/quarto-web/blob/main/docs/gallery/gallery.yml

**Comment by cwickham** [comment]
Closed based on merged PR https://github.com/quarto-dev/quarto-web/pull/646
