### ISSUE TITLE
Create a Quarto cheatsheet

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#4520]
To live alongside other posit cheatsheets: https://posit.co/resources/cheatsheets/?type=posit-cheatsheets&_page=1/

**Comment by bhattmaulik** [comment]
In RStudio's Helo Menu > Cheat sheets, we can see two items: R Markdown Cheat Sheet, and R Markdown Reference Guide. So, I have a feature request: can such a quarto cheat sheet be incorporated in RStudio's Helo Menu as well?

**Comment by cwickham** [comment]
### Some notes from discussion in Dev Rel Sync

Official posit cheatsheets: https://github.com/rstudio/cheatsheets/

Accessible cheatsheets: https://github.com/mine-cetinkaya-rundel/accessible-cheatsheets

Start with accessible version, then figure out how to spatially organize in Keynote.

Probably need more than one cheatsheet:

* Quarto for R/RStudio users
*  Quarto for Python/ (Jupyter/VS Code) users

Focus on beginners - the different paths through "Getting Started" on docs site are probably a good way to think about possible content

[Rmarkdown cheatsheet](https://posit.co/blog/the-r-markdown-cheat-sheet/) a good inspiration for R/RStudio version

**Comment by cwickham** [comment]
Closed with https://github.com/rstudio/cheatsheets/pull/314
