### ISSUE TITLE
Merge conflict indicators in contents of `_freeze` result in uninformative JSON error

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#4529]
### Bug description

If there's a merge conflict indicator in contents of `_freeze`, `quarto render` fails with a JSON error that is not very informative.

<img width="742" alt="Screenshot 2023-02-24 at 6 36 32 PM" src="https://user-images.githubusercontent.com/5965649/221321149-d992d559-8185-4e53-a5f7-d76e0f2dc13c.png">

The current solution is to delete `_freeze` and re-render. This solution works for my use-case but it could be frustrating for a project where maintaining `_freeze` is important. From the message there is no way to identify which file in `_freeze` is causing the issue.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
@mine-cetinkaya-rundel I'm closing this one but we should check to see if the warning shows up when freeze actually has real-life git conflict markers in the wild.
