### ISSUE TITLE
Lua error when cell output contains square brackets in braces

### ISSUE THREAD

**Issue by seeM** [quarto-dev/quarto-cli#4535]
### Bug description

I'm using Quarto v1.3.222 on macOS 13.2.1.

The simplest example I could find is a Jupyter notebook with a single cell with source:

```py
print("{[}")
```

Then run `quarto render` and hit the error:

```
Error running Lua:
/Applications/quarto/share/filters/qmd-reader.lua:83: malformed pattern (missing ']')
stack traceback:
        /Applications/quarto/share/filters/qmd-reader.lua:83: in function 'escape_invalid_tags'
        /Applications/quarto/share/filters/qmd-reader.lua:96: in function 'Reader'
```

Adding a `]` after the `[` doesn't help.

I encountered this while displaying the following dictionary:

```py
{'cells': [], 'metadata': {}, 'nbformat': 4, 'nbformat_minor': 5}
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report, this is a pretty bad one (sorry I was asleep when you filed it :)).

It'll be fixed on `main` soon.

**Comment by cscheid** [comment]
This [workflow](https://github.com/quarto-dev/quarto-cli/actions/runs/4271076118) will build a release with the fix.

Again, thanks for the report and great repro case.

**Comment by seeM** [comment]
@cscheid amazing, thanks for the quick fix!
