### ISSUE TITLE
Google Analytics tag integration -  no data influx

### ISSUE THREAD

**Issue by dschief001** [quarto-dev/quarto-cli#4538]
### Bug description

Hi,

didn't test on the latest nightly release, but
the issue is as follows:

trying to get google-analytics working on my quarto blog, but this doesn't get an influx of data.
If I investigate the site there is an error popping up which seems to me related to the tag implementation.
The issue can be reproduced as follows:

1. https://quarto.org/docs/websites/website-tools.html
and investigating,
for me the first hightlighted issue is the one related to the g-tag:
2. **Issue** Laden fehlgeschlagen für das <script> mit der Quelle **"https://www.googletagmanager.com/gtag/js?id=G-FV9Z7SDZ0M".**
So it seems that maybe the google script is not correctly implemented, or this should be like that?

Thanks a lot for checking this out.

##  in short: A screenshot of the site investigation:
3. ![grafik](https://user-images.githubusercontent.com/35806794/221379046-36abb69a-2b3c-4e15-bf66-26be1dee3a40.png)

Rstudio version:
"Elsbeth Geranium" Release (7d165dcf, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
Windows 10 x64

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I checked on the Quarto website and it appears to be properly forming and loading the google tag URL. Is there something on your machine that might be blocking that URL or otherwise preventing google tag manager from loading?

**Comment by dragonstyle** [comment]
When I visit that page, I am able to see Google Analytics loading correctly and a ping being sent (from what I infer) to collect analytics data. I'm not a GA expert, so can't really troubleshoot much further, but this appears to be configured correctly as far as I can tell...

**Comment by cscheid** [comment]
@dschief001 I'm speculating here, but is it possible that you're running an ad blocker somewhere in your network setup? That could be anywhere from an extension in your browser to a custom /etc/hosts file to a network device like a DNS sinkhole.

**Comment by dragonstyle** [comment]
Please feel free to re-open this issue if you can provide some additional information to help us debug the issue.

**Comment by DayuanJiang** [comment]
Has this problem been solved? I had the same issue. I set the GA4 ID, but the GA console shows that it has not received any data from my site.

Here is my site:
https://www.jiang.jp/

**Comment by ASNDataAnalytics** [comment]
Hi @dragonstyle, @dschief001, and @DayuanJiang, 

First, thank you and everyone on the Quarto team for creating and maintaining such a great publishing system. I *think* I may know what is behind this issue. Entering the gtag in the `_quarto.yaml` injects into all the quarto site's `html` files, like previously with the (soon-to-be) previous version of GA.

However, according to [https://developers.google.com/tag-platform/devguides/datalayer](https://developers.google.com/tag-platform/devguides/datalayer) (and my IT guy, props!), there is an additional `gtag.js` JS function script that's required to trigger the data, where `TAG_ID` = your gtag. 

```
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'TAG_ID');
</script>
```


The complete GA4 `gtag.js` should look like (including the comment):

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=TAG_ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'TAG_ID');
</script>
```

I hope this helps. Please let me know. 

Thanks,

Kurtis Pivert

**Comment by dragonstyle** [comment]
Thanks for sharing that - the user who previously reported the issue has the following script definition, which seems correct to me (<https://www.jiang.jp/>):

```javascript
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-XXXXXXXX', { 'anonymize_ip': true});
```

Are you also having the issue and if so could you share some way we could reproduce it? For example, a simple website with a `_quarto.yml` file with GA configuration that shows invalid script tags?

With a third party service like GA, it is very often simply a misconfiguration of the account or a delay of data processing on the Google end...

**Comment by ASNDataAnalytics** [comment]
Hey @dragonstyle, thanks very much for your quick response. I was mistaken. Quarto, as always, nicely places the required gtag.js function in the head. Sorry for the false positive, and thanks again for all your work on Quarto, which I use everyday. 

Kurtis

**Comment by dragonstyle** [comment]
No worries- it was actually very helpful for to have a second opinion and to double check that we were doing the right thing!
