### ISSUE TITLE
Mermaid output style is affected by `highlight-style` theme in reveal.js

### ISSUE THREAD

**Issue by pedrotercero3** [quarto-dev/quarto-cli#4545]
### Bug description
Mermaid's output is affected by the code highlighting theme specified with `highlight-style` in the YAML options.

### Output (with bug)

![image](https://user-images.githubusercontent.com/90156958/221413228-6bad4cab-29aa-4355-874b-edc8523a1084.png)

### Expected output

![image](https://user-images.githubusercontent.com/90156958/221413265-b8eb87dc-ff2a-4fd7-894c-e471ba21fbd7.png)

### Reprex (Quarto Reveal.js)
````
---
title: "Mermaid style bug"
format:
  revealjs:
    theme: default
    highlight-style: nord
editor: source
---

## Mermaid diagram

```{mermaid}
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```
````

### Session info
OS: macOS Monterey 12.2
RStudio version: 2022.07.1 Build 554
Quarto version: 1.2.231
```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] es_ES.UTF-8/es_ES.UTF-8/es_ES.UTF-8/C/es_ES.UTF-8/es_ES.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I can't reproduce this on the latest 1.3 prerelease, where we [changed the way mermaid styling works](https://quarto.org/docs/prerelease/1.3/mermaid.html).

**Comment by pedrotercero3** [comment]
> I can't reproduce this on the latest 1.3 prerelease, where we [changed the way mermaid styling works](https://quarto.org/docs/prerelease/1.3/mermaid.html).

What a timely (pre)release! I just downloaded it and I can confirm that the bug no longer happens and the diagram renders as expected. Thank you.
