### ISSUE TITLE
No Images, when rendering content to confluence

### ISSUE THREAD

**Issue by henningsway** [quarto-dev/quarto-cli#4550]
### Bug description

Using Quarto 1.3.231 on Mac OS 13.2.1 i haven't yet gotten images to show up in my confluence post. Publishing via CLI in VSCode.

**HTML Rendering**
![HTML](https://user-images.githubusercontent.com/1403304/221539940-550fa0d0-bfed-435f-a878-f9884096777f.png)
**HTML Rendering in Confluence (without images)**
![image](https://user-images.githubusercontent.com/1403304/221540448-23cca1ca-d5f4-4a5d-849e-700cffcfde79.png)

**Minimal example**
```
---
format: confluence-html
---

# test
foo

![](example.png)  

```{r}
plot(1)
```
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by allenmanning** [comment]
Thank you for logging this issue.  

I attempted to [publish this to confluence directly from the CLI](https://allenmanning.atlassian.net/wiki/spaces/QUARTOCONF/pages/68976668/bug-4550) and I couldn't reproduce it. 

I'm now going to attempt to do it from inside of VS Code to see if there is something there that may be a bug.

**Comment by allenmanning** [comment]
I was able to use the integrated terminal in VS Code to publish this example and the images loaded.

Can you please try the following:

- Wait a bit for the images to load and check again.  Sometimes there is a delay for Confluence to prepare the images.

- Check that they have been attached.  Please check to see if files have been attached.
![image](https://user-images.githubusercontent.com/674792/221583337-aaeacee9-52f0-44ca-8f79-a0302a02678e.png)

- See if any errors have been reported in the publish log.  If we can't find an image, or there is a problem calling the Confluence API, then error should be reported to you in the logs.  Did you see any errors?

**Comment by henningsway** [comment]
Thank you for testing this quickly. I just rechecked, as I didn't have file attachments in Confluence.

I noticed, that my document was in a subdirectory (reports/) of the project and there was actually also an error

```
quarto publish confluence reports/test-confluence.qmd
#> ERROR: NotFound: No such file or directory (os error 2), stat '[...]/reports/reports/confluence-test_files/figure-publish'
```

I moved the file to the project root and the upload worked.

PS: After testing I have multiple confluence destinations to choose from, when republishing the file. Is there a way to clean this up again, where is that information stored? :)
