### ISSUE TITLE
[Confluence] "Flatten" `index.qmd` to parent folder.

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#4551]
Use the contents of an `index.qmd` document as the contents for the parent folder of a Confluence project.
 
- When the parent folder is first created, check to see if there is an immediate child `index.qmd` that can be used to populate it's `title` and body.
- When the child `index.qmd` is updated, also update the parent.

**Comment by allenmanning** [comment]
@cwickham We might want to update our docs to mention this.

**Comment by cwickham** [comment]
@allenmanning Added discussion of `index.qmd` to https://github.com/quarto-dev/quarto-web/pull/645/commits/8472e7adeb5fd1460a5f3bf0af62fad94018cab2

**Comment by allenmanning** [comment]
Great work.  Great teamwork.  I will move this to Done once the docs are merged to main.
