### ISSUE TITLE
Rendering should not open embedded iframe links

### ISSUE THREAD

**Issue by cynthiahqy** [quarto-dev/quarto-cli#4557]
### Bug description

Rendering a quarto html document triggers iframe links to open in the default browser. This is slightly annoying but not terrible when embedding simple webpages, but embedding the reveal js quarto docs triggered 15+ tabs to open (the website page and all slides in the example deck).

The behaviour occurred when rendering via RStudio render button and via `quarto render` command inside RStudio terminal.

Minimal reproducible example tested on:
- Quarto version: 1.2.335, 1.2.269
- RStudio IDE: (Version 2022.12.0+353 (2022.12.0+353)
- MacOS: Ventura 13.1
- Default Browser: Safari, Chrome

````md
---
title: "Untitled"
format: revealjs
---

## Quarto

Quarto enables you to weave together content and executable code into a finished presentation. To learn more about Quarto presentations see <https://quarto.org/docs/presentations/>.

## Iframe

```{=html}
<iframe width="780" height="500" src="https://quarto.org/docs/presentations/revealjs/" title="Quarto revealjs Documentation"></iframe>
```
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by TengMCing** [comment]
This issue only happens when you use Rstudio with the `qmd` file opened and the preview option being set to `Preview in Viewer Pane`. In this case, both the render button and the `quarto render xxx.qmd` command will trigger the issue. 

If you close the `qmd` file or choose another preview option such as `Preview in Window`. The rendering will work correctly.

**Comment by cscheid** [comment]
This looks to be an issue with RStudio specifically, is that right? In that case, I think the correct repository to file an issue is https://github.com/rstudio/rstudio/

**Comment by cderv** [comment]
This is a known issue solved already in https://github.com/rstudio/rstudio/issues/12494 for next release. Probably already available in daily.  Still not perfect and next step is tracked in https://github.com/rstudio/rstudio/issues/12766

This is not Quarto only. it happend with R console, and also R Markdown. 

I am closing here as this is a RStudio IDE issue. 

thanks !
