### ISSUE TITLE
Unable to determine type for... error parsing yaml cell options

### ISSUE THREAD

**Issue by bvancil** [quarto-dev/quarto-cli#4573]
### Bug description

Last tested using Quarto v1.3.234 on WSL2 (Ubuntu 22.04.1 LTS) and Windows 10, the test from issue #3901 https://github.com/quarto-dev/quarto-cli/blob/main/tests/docs/partition-cell-options/issue-3901.qmd results in the following error when running `quarto preview issue-3901.qmd --to html`:

```

Starting c kernel...Done

Executing 'test-c-2.ipynb'
  Cell 1/4...Done
  Cell 2/4...ERROR:

Unable to determine type for "'The classic ''Hello, world!'' program for C.' "
```

In my own tests, it seems to have to do with having a colon (":") or a comma (",") in the input string. For example:

````
---
jupyter: c
---

## Success

```{c}
/*| label: helloWorld1 */
/*| fig-cap: "«single»: “words”" */
/*| fig-alt: "C source code for \"hello world\" program" */
/*| echo: true */

#include <stdio.h>

int main() {
    printf("Hello, world!");
}
```

## Failure

```{c}
/*| label: helloWorld2 */
/*| fig-cap: "«single» “words”" */
/*| fig-alt: "C source code for \"hello, world\" program" */
/*| echo: true */

#include <stdio.h>

int main() {
    printf("Hello, world!");
}
```
````

I'm not sure whether the error happens for languages that use only an initial comment character, but I would guess that this would have been reported earlier were that the case.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by bvancil** [comment]
Further testing indicated that the octothorpe ("#") also caused problems.

**Comment by cscheid** [comment]
Hm. This seems to be a bug in `poyo` (the YAML parser we use) where it sometimes doesn't seem to like lines that end with spaces (which we currently produce in the case of `/*` `*/` comments).

```
$ python
$ import poyo
$ >>> poyo.parse_string('fig-cap: "test"')
{'fig-cap': 'test'}
>>> poyo.parse_string('fig-cap: "test" ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/poyo/parser.py", line 280, in parse_string
    return parser()
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/poyo/parser.py", line 273, in __call__
    match = self.find_match()
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/poyo/parser.py", line 254, in find_match
    node = callback(match)
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/poyo/parser.py", line 67, in _wrapper
    result = wrapped_function(parser, match, **kwargs)
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/poyo/parser.py", line 166, in parse_simple
    value = self.read_from_tag(groups["value"])
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/poyo/parser.py", line 128, in read_from_tag
    raise NoTypeException(error_message.format(string))
poyo.exceptions.NoTypeException: Unable to determine type for ""test" "
```

We'll have to work around it.

**Comment by cscheid** [comment]
I've added a workaround to `main`, and this appears to no longer be happening. Thanks for the report!
