### ISSUE TITLE
quarto publish gh-pages --no-browse Issue

### ISSUE THREAD

**Issue by ksasi** [quarto-dev/quarto-cli#4575]
### Bug description

Hi,

It appears despite running "quarto publish gh-pages --no-browse", the rendered code is staying in intermediate directory and not getting deployed/copied into gh-pages explicitly. Despite following the instructions from https://quarto.org/docs/publishing/github-pages.html

Thanks

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report. We need more details than you've provided in order to reproduce the issue. Can you give us:

- a repository that exhibits the issue
- the version of quarto you're running
- the operating system you're running

**Comment by ksasi** [comment]
Hi,

Below are the details : 

- a repository that exhibits the issue : https://github.com/ksasi/ai-notes
- the version of quarto you're running : 1.2.335
-  he operating system you're running : macOS Monterrey Version 12.6.3

Thanks

**Comment by cscheid** [comment]
Thanks. Can you try the [1.3 prerelease](https://quarto.org/docs/prerelease/1.3/)? And can you paste a terminal transcript so we can see what messages are being emitted?

**Comment by ksasi** [comment]
Hi,

I tried with 1.3 prerelease , but getting an error message. Below is the terminal script/output : 

 % quarto publish gh-pages
Quarto v1.3.235
? Update site at https://ksasi.github.io/ai-notes/? (Y/n) › Yes
From https://github.com/ksasi/ai-notes
 * branch            gh-pages   -> FETCH_HEAD
Rendering for publish:

[1/6] posts/2020-06-30-Time-Matters-in-Regularizing-Deep-Networks.md
[2/6] posts/2023-02-13-Research-Week-With-Google.md
[3/6] posts/2020-02-20-test.ipynb
[4/6] posts/2020-08-24-Self-Supervised-Learning.md
[5/6] index.qmd
[6/6] about.qmd

error: unknown option `track'
usage: git worktree add [<options>] <path> [<branch>]
   or: git worktree list [<options>]
   or: git worktree lock [<options>] <path>
   or: git worktree prune [<options>]
   or: git worktree unlock <path>

    -f, --force           checkout <branch> even if already checked out in other worktree
    -b <branch>           create a new branch
    -B <branch>           create or reset a branch
    --detach              detach HEAD at named commit
    --checkout            populate the new working tree
    --lock                keep the new working tree locked

ERROR: Error executing 'git': No such file or directory (os error 2)

**Comment by cscheid** [comment]
Thanks.

in `gh-pages.ts`, we call
```ts
  await execProcess({
    cmd: [
      "git",
      "worktree",
      "add",
      "--track",
      "-B",
      "gh-pages",
      siteDir,
      "origin/gh-pages",
    ],
    cwd: dir,
  });
```

And this appears to be causing the `error: unknown option 'track'` error. I confess I don't understand how you get a followup error `Error executing 'git': No such file or directory (os error 2)` given that we just saw a message about how `git worktree` is not recognizing an option.

I apologize for the continued questions, but can you please run the following? This is what I see. I'm on macOS as well (though on Ventura, not Monterey).

```
$ which git
/usr/bin/git
$ git --version
git version 2.37.1 (Apple Git-137.1)
```

**Comment by ksasi** [comment]
Below are the details :

% which git
/usr/local/bin/git
% git --version
git version 2.15.0

**Comment by cscheid** [comment]
Yes, so this is the issue. You're running a [5-year-old version of git](https://github.com/git/git/blob/master/Documentation/RelNotes/2.15.0.txt), that was installed to `/usr/local/bin/git` by some third-party software, and it's getting resolved before Apple's git version.

We should do better in our case, but you'll need to keep your dependencies updated.

**Comment by cscheid** [comment]
We're now emitting an error message if we find an old version on git.

**Comment by ksasi** [comment]
Thanks very much for this. The issues are resolved after upgrading git to the latest version.
