### ISSUE TITLE
Bug in v1.3.237 with citation date

### ISSUE THREAD

**Issue by EllaKaye** [quarto-dev/quarto-cli#4586]
### Bug description

In quarto v1.3.237 there is a bug (not present in v1.2.x) regarding how the date appears in the citation.

As a reprex, I have the following yaml:

```
title: "Citation date bug"
format: html
date: 2023-03-01
citation: true
```

In the generated citation, the bibtex part is fine, but for the attribution, it gives the year as 23AD (not 2023).

Example at <https://ellakaye.github.io/quarto-bug/> from repo <https://github.com/EllaKaye/quarto-bug>

I'm on macOS Ventura 13.2.1 working in RStudio 2023.03.0-daily+30. That said, I switched back to Quarto v1.2.335 and the issue went away, so it does seem to be an issue with the latest Quarto rather than the OS or RStudio.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I can repro this. @dragonstyle, the relevant diffs appear to be

```
$ git diff v1.3.34..v1.3.47 src/command/render/pandoc.ts
$ git diff v1.3.78..v1.3.83 src/command/render/pandoc.ts
```

**Comment by cscheid** [comment]
Thanks for the report! This is fixed on `main` now, and we'll make a new release shortly.

**Comment by EllaKaye** [comment]
Thanks for the quick response and fix 😄 working for me now on the latest pre-release.
