### ISSUE TITLE
ERROR: PermissionDenied: Permission denied (os error 13), mkdir '/run/user/1960/jt'

### ISSUE THREAD

**Issue by dpabon** [quarto-dev/quarto-cli#4594]
### Bug description

When I try to render the following on VSCode
```bash
---
title: "Untitled"
format: html
---

  ```{julia}
println()

```

I got

```
Quarto v1.3.235
ERROR: PermissionDenied: Permission denied (os error 13), mkdir '/run/user/1960/jt'
```

my setup

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.0: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.235
      Path: /Net/Groups/BGI/people/dpabon/bin/quarto/quarto-1.3.235/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.8 (Conda)
      Path: /User/homes/dpabon/miniconda3/bin/python
      Jupyter: 5.1.5

[✓] Checking Jupyter engine render....OK

```

OS:

```
Distributor ID: CentOS
Description:    CentOS Linux release 8.3.2011
Release:        8.3.2011
```

VSCode:
```
version: 1.76.0
```
Quarto extension:
```
1.71.0
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report. Can you run with `QUARTO_PRINT_STACK=true` in your environment?

**Comment by dpabon** [comment]
Thanks for your reply, I did ```QUARTO_PRINT_STACK=true``` but after running quarto. I get the same error without any new information.
```bash
quarto preview /User/homes/dpabon/dpabon/Deliverable_3_Notebook_1.qmd --no-browser --no-watch-inputs
Quarto v1.3.235
ERROR: PermissionDenied: Permission denied (os error 13), mkdir '/run/user/1960/jt'
```

**Comment by dpabon** [comment]
Ok here a MWE:

```quarto
---
title: "Deliverable_3_Notebook_1"
author: "Norah Jones"
date: "5/22/2021"

---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.


```{julia}
print("test")

```
produced the error.

```quarto
---
title: "Deliverable_3_Notebook_1"
author: "Norah Jones"
date: "5/22/2021"

---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.


```{R}
print("test")

```
Works fine.

**Comment by dpabon** [comment]
I'm running quarto on a remote machine via ssh VS Code. In this case, I don't have admin rights and by default the folder permissions are group-specific and not user specific. However, I can change the permissions on the folder. In this machine, there is an outdated R version that quarto recognized and compiled the code without problem. 

![image](https://user-images.githubusercontent.com/13040959/222896792-9dc5e6c7-0b50-4d72-b44f-a1487924d075.png)

As I don't have admin rights, I have my local Conda environment and I set up ```export QUARTO_PYTHON="/User/homes/dpabon/miniconda3/bin/python"``` on my .bashrc file.

If I Change R to python, the get the error message. 
 
I think this is related to this issue: https://github.com/systemd/systemd/issues/3355

**Comment by petrelharp** [comment]
I've hit this on our cluster as well (running RHEL7.9); there `$XDG_RUNTIME_DIR` resolves to `/run/user/$UID` which is apparently [set by `pam_systemd`](https://wiki.archlinux.org/title/XDG_Base_Directory), and so is not something specific to our cluster. The docs for [XDG at Arch](https://wiki.archlinux.org/title/XDG_Base_Directory) say for `$XDG_RUNTIME_DIR` that it is `"Not required to have a default value; warnings should be issued if not set or equivalents provided."`; maybe that's supposed to mean that it might not actually be there? Or maybe it's a misconfigured system, but that's not something I have control over, and seems maybe not uncommon? FWIW, `mktemp` works on the same system, so there *is* a generic mechanism that works to get temporary directories.

It seems like the thing to do is to try to use $XDG_RUNTIME_DIR but fall back to a different mechanism, if that fails?

**Comment by petrelharp** [comment]
A workaround is to manually set `XDG_RUNTIME_DIR` to something that works, e.g.
```
export XDG_RUNTIME_DIR=$(mktemp -d)
```

**Comment by cderv** [comment]
> It seems like the thing to do is to try to use $XDG_RUNTIME_DIR but fall back to a different mechanism, if that fails?

Just noticed we have a fallback if the value is not set 
https://github.com/quarto-dev/quarto-cli/blob/179f686963a5bd4993d357a116ca20150c844a10/src/core/appdirs.ts#L118-L125

Maybe this fallback should apply also if the folder does not exists ?

**Comment by petrelharp** [comment]
That sounds reasonable; however, looking at the code I think (could be wrong?) that the fallback would be $XDG_DATA_HOME; or if that is unset (as it is on my system), either $HOME (?) or ~/.local/share, maybe? Not knowing anything about deno I wonder about the [TempDir](https://examples.deno.land/temporary-files) function? It looks like unfortunately `mktemp` is [not POSIX but there are workarounds](https://unix.stackexchange.com/questions/614808/why-is-there-no-mktemp-command-in-posix).

**Comment by cscheid** [comment]
@cbrnr Excellent catch, that's exactly what the issue is. It's another instance of a problem in our automatic project root discovery. Can you open a new issue?

**Comment by cscheid** [comment]
If you are reading this comment, the underlying issue is that your environment is likely exposing a directory in the `XDG_RUNTIME_DIR` environment variable which exists, but is not writable by your user. This is, strictly speaking, [against the XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and so it's not a bug we can fix in general on our side.

However, it is possible for you to run quarto with a workaround that should ameliorate your issue:

- create a directory that your user has permissions to write,
- set the `XDG_RUNTIME_DIR` environment variable to that directory,
- run `quarto` as you otherwise would.

**Comment by petrelharp** [comment]
> This is, strictly speaking, [against the XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and so it's not a bug we can fix in general on our side.

You can't fix non-writeability of XDG_RUNTIME_DIR, but you can check if it's writeable, and fallback to something else if not?

**Comment by cderv** [comment]
@petrelharp I agree with you. 

@cscheid can't we do the same as we do in other place ? See my earlier comment: https://github.com/quarto-dev/quarto-cli/issues/4594#issuecomment-1511329766

**Comment by cscheid** [comment]
> You can't fix non-writeability of `XDG_RUNTIME_DIR`

that will require a slightly different refactoring, but yeah, it should be possible. @cderv Notice that the fallback is slightly different; we check for the _existence_ of the file versus checking by _writing_ into the directory. I am slightly wearing of adding a check that requires writing against the directory because I don't know how often we'll call it, and I don't know the performance implications. We should be able to cache that information as well, but this is a relatively big change that only affects an environment that we are currently incapable of testing. It's not clear to me that the risk tradeoff is worth it.

**Comment by cderv** [comment]
I understand. Thanks for adding your thoughts on that.

**Comment by w75086** [comment]
I encountered this similar issue for my Ubuntu 22 running quarto-1.6.42-linux-amd64.deb

`
➜  quarto-test echo $XDG_RUNTIME_DIR 
/run/user/1000/
➜  quarto-test 
`

My workaround was to create the directory with my UID and also make sure my UID is the owner:
`
sudo mkdir /run/user/1000
sudo chown richardaik /run/user/1000
`

Hopefully that's helpful.

**Comment by kelly-sovacool** [comment]
I'm encountering a similar but slightly different error when trying to run quarto in a singularity container:

```
Command error:
  error: Uncaught Error: Read-only file system (os error 30): mkdir '/home/sovacoolkl/.cache/quarto'
          Deno.mkdirSync(dir, {
               ^
      at Object.mkdirSync (ext:deno_fs/30_fs.js:132:7)
      at ensureDirSync (file:///opt2/quarto-1.4.550/bin/quarto.js:9288:14)
      at quartoDir (file:///opt2/quarto-1.4.550/bin/quarto.js:33006:5)
      at quartoCacheDir (file:///opt2/quarto-1.4.550/bin/quarto.js:32998:12)
      at file:///opt2/quarto-1.4.550/bin/quarto.js:39501:25
```

is it possible to override the location of `/home/$USER/.cache/quarto` to get around this?

**Comment by mcanouil** [comment]
@kelly-sovacool First, i would suggest to upgrade Quarto as 1.4.550 is quite old now. (Current is 1.6.42).

You might also find some useful informations/tips in the two following threads:

- https://github.com/quarto-dev/quarto-cli/discussions/10617
- https://github.com/quarto-dev/quarto-cli/discussions/2559

**Comment by cderv** [comment]
@kelly-sovacool for more context, we use `HOME` only when the usual `XDG_CACHE_HOME` is not available
https://github.com/quarto-dev/quarto-cli/blob/9bb900606e8235805b0e880edd73fca71e79aff5/src/core/appdirs.ts#L140-L144

Quarto uses several `XDG_*` variables per the spec: https://specifications.freedesktop.org/basedir-spec/latest/

**Comment by mcanouil** [comment]
This is what the second discussion is about and using flags such as `--no-home`, etc. in Singularity.

- https://github.com/quarto-dev/quarto-cli/discussions/2559

**Comment by kelly-sovacool** [comment]
> This is what the second discussion is about and using flags such as `--no-home`, etc. in Singularity.
> 
> * [Running quarto in singularity #2559](https://github.com/quarto-dev/quarto-cli/discussions/2559)
> 
> See for instance the below comment about setting the XDG_ environment variables.
> 
> * [Running quarto in singularity #2559 (comment)](https://github.com/quarto-dev/quarto-cli/discussions/2559#discussioncomment-5947349)

thanks, setting `XDG_CACHE_HOME` and `XDG_DATA_HOME` worked for me!
