### ISSUE TITLE
A gt table with header causes table to not render correctly

### ISSUE THREAD

**Issue by rich-iannone** [quarto-dev/quarto-cli#4603]
With the latest `quarto-cli` on `main`, a gt table that contains a header does not get rendered correctly. Here is a minimal reproducible example that creates a 1x1 table in two ways: (1) without a header (*not* using the `tab_header()` function) (this renders correctly), and (2) with a header (using the `tab_header()` function (this doesn't render correctly).

Here is the .qmd:

````
---
format: html
---

```{r}
#| echo: false
library(gt)

exibble[1, 1] %>% gt()
```

```{r}
#| echo: false

exibble[1, 1] %>% gt() %>% tab_header("title")
```
````

Here is a screen capture of the rendered document:

<img width="1058" alt="gt-table-quarto" src="https://user-images.githubusercontent.com/5612024/222486124-5afed58f-30a0-4ef8-8227-5fd79904a91a.png">

This may be related to https://github.com/quarto-dev/quarto-cli/issues/4419 since there is a gt table (more complex) with a header that has similar rendering problems.

**Comment by cscheid** [comment]
Conclusion: Rich and I found that the root cause here is that GT sometimes emits invalid HTML (and so Pandoc parses it incorrectly). Starting in 1.3, quarto requires HTML tables to be valid.
