### ISSUE TITLE
jupyter-cache installation instructions incorrect in "Using Julia" documentation

### ISSUE THREAD

**Issue by keatonmill** [quarto-dev/quarto-cli#4607]
### Bug description

The `jupyter-cache` package is currently maintained in the `conda-forge` channel (see [this search on `anaconda.org`](https://anaconda.org/search?q=jupyter-cache)) which is not included in the list of default channels used by `Conda.jl` on a fresh install on Windows 10.

Thus, to install `jupyter-cache`, the correct command is 
```julia
Conda.add("jupyter-cache"; channel="conda-forge")
```

On a fresh install, attempting to use `Conda.add("jupyter-cache")` as instructed by the [Using Julia](https://quarto.org/docs/computations/julia.html#jupyter-cache) documentation page results in the following error:

```
julia> Conda.add("jupyter-cache")
[ Info: Running `conda install -y jupyter-cache` in root environment
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - jupyter-cache

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
@cderv Can you confirm this is the behavior you see on Windows?

**Comment by cderv** [comment]
Looking at the documentation, it seems to me that `conda-forge` (what they called Miniforge) will be used by default on some system (https://github.com/JuliaPy/Conda.jl#using-miniforge)

> Note that Conda.jl 1.6 and above will use miniforge by default on x86_64, aarch64 and ppc64le systems.

Either you are not using version 1.6+ of Conda.jl, or you have a different system where it will be false, but I understand this should be false on unsupported platform for conda-forge only 

What is you Conda.jl version ?

**Comment by keatonmill** [comment]
After a couple of hours of fooling around, it appears that my "fresh install" wasn't as fresh as I believed. Looks like I had a bunch of  package and settings files from an old version of Julia that didn't get deleted when I uninstalled. After clearing that and re-running, I now get the same output you do and everything appears to be working as intended.

Sorry for the waste of time, and thanks for checking out your install for me!
