### ISSUE TITLE
epubcheck complains about epubs generated with Quarto

### ISSUE THREAD

**Issue by b-rodrigues** [quarto-dev/quarto-cli#4615]
### Bug description

Dear Quarto team

I’m struggling to solve an issue with epub generated using Quarto. Here is a repo with a simple book: https://github.com/b-rodrigues/epubcheck_quarto_test that causes the issue. 

using `quarto render` creates an epub version of the book in the _book folder. But using epubcheck on it (https://www.w3.org/publishing/epubcheck/) I get the following error message:

```
ERROR(RSC-005): example_book.epub/EPUB/content.opf(6,39): Error while parsing file: character content of element "dc:date" invalid; 
be a string with length at least 1 (actual length was 0)
WARNING(OPF-053): example_book.epub/EPUB/content.opf(6,39): Date value "" does not follow recommended syntax as per http://www.w3.orNOTE-datetime:zero-length string.
```

and indeed, if I take a look at the ` example_book.epub/EPUB/content.opf` file, I see that the `dc:date` tag is empty. However, in the `_quarto.yml` file, you’ll see that I’ve added the following:

```
format:
  html:
    theme: cosmo
  epub:
    toc:
      true
    date:
      "2023-03-01"
```

I have the same issue on Linux (see Github actions, and the generated ebook in the gh-pages branch) and on Windows 10 with the latest version of Quarto installed (1.2.335).

### EDIT

The error message disappears if I add the language as well:

```
format:
  html:
    theme: cosmo
  epub:
    toc:
      true
    lang:
      en-GB
    date:
      "2023-03-01"
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thanks for letting us know- I can confirm that I reproduce this in a simple book using Quarto 1.2. It is fixed in the current pre-release of Quarto 1.3 (and I can confirm that the date is properly populated in the content.opf file).
