### ISSUE TITLE
`link-external-icon` should not be line-wrapped

### ISSUE THREAD

**Issue by salim-b** [quarto-dev/quarto-cli#4619]
### Bug description

I just tried out the [external links](https://quarto.org/docs/output-formats/html-basics.html#external-links) feature of Quarto's HTML format and noticed that the icon after external links gets line-wrapped like regular whitespace-separated text which is clearly undesirable.

Example screenshot:

![Bildschirmfoto am 2023-03-03 um 17 30 47](https://user-images.githubusercontent.com/20040931/222774953-8a1175ed-5e87-4b39-9ed7-df8d9efb2cbd.png)

I see that technically no whitespace is used between the link and the icon. Instead it is inserted via the CSS pseudo-element [`::after`](https://developer.mozilla.org/en-US/docs/Web/CSS/::after). I'm no CSS expert, so I can't judge what the best solution looks like. A possible solution would be to [move `display:inline-block;` from `a.external::after` to `a.external`](https://stackoverflow.com/questions/14851320/how-to-avoid-line-breaks-after-before-in-css). But maybe you got an even better solution.

Thanks for looking into this!

<sup>I'm using the latest stable Quarto CLI v1.2.335</sup>

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by allenmanning** [comment]
Here are a few suggestions on how to approach this with CSS: 

https://stackoverflow.com/questions/14851320/how-to-avoid-line-breaks-after-before-in-css
https://stackoverflow.com/questions/16100956/prevent-after-element-from-wrapping-to-next-line
