### ISSUE TITLE
margin figures error for pdf output

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#462]
Embedding an image with a caption (and/or a label) creates a figure environment, which errors on latex output when included in the page margin:

```
:::column-margin
![A dog](./www/dog.jpg)
:::
```
`LaTeX Error: Not in outer par mode.`

It works without the caption, as then there is not figure environment being created

```
:::column-margin
![](./www/dog.jpg)
:::
```

Tested with `lua/xe/pdf-latex`

**Comment by dragonstyle** [comment]
Thanks for letting us know- fixed here 21b4f27e4790bd62167d8ff88293dc130c2c7432. 

We definitely should have been handling this case, but just FYI, you can also write:

```
![A dog](./www/dog.jpg){.column-margin}
```

I've got a fresh release building now- thanks again!

**Comment by jmbuhr** [comment]
Ah yes, when I discovered this I had multiple figures in the margin, which overlap if you assign them to the margin individually, so this is why it is it's own div.
![image](https://user-images.githubusercontent.com/17450586/160141981-9fd86785-1429-4d5c-834c-7453c1e9417b.png)
vs.
![image](https://user-images.githubusercontent.com/17450586/160142082-a8c937b4-905f-4d48-98b1-e7aed225d979.png)

**Comment by dragonstyle** [comment]
An even better reason why this must be supported. I appreciate the followup, learned something new!

**Comment by deckold** [comment]
The same problem seems to occur if the figure is produced in a code block too. i.e.:

:::{.column-margin}

some text also in the margin.

```{<lang>}
#: fig-cap: "example caption"

<<code that produces plot>>
```
:::
 
With no caption given using the `#| fig-cap: ` option no error is produced. But the inclusion of a caption causes the same error as above `LaTeX Error: Not in outer par mode.`

I'd like to be able to do this for the same reason as above, using `#| column: margin` in the code block will produce an overlapping figure on top of other margin notes and grouping them together inside one block solves this problem.
