### ISSUE TITLE
Figure crossref not resolving in callout (new in v1.3)

### ISSUE THREAD

**Issue by EllaKaye** [quarto-dev/quarto-cli#4621]
### Bug description

Hello,

Crossrefs are not resolving when figure is created inside a div. The crossref doesn't work either inside the div or outside.

````
---
title: "Crossref bug"
---

:::{.callout-note}
```{r}
#| label: fig-div-plot
#| fig-cap: my plot!
plot(1:10, 1:10)
```
Check out @fig-div-plot
:::

Check out @fig-div-plot
````

(If the figure is created outside of a div, the crossref *does* resolve inside a div).

Example at <https://ellakaye.github.io/quarto-bug/> from repo <https://github.com/EllaKaye/quarto-bug>

This is a bug that has appeared in the pre-release (v1.3.242). It works fine in the current stable release (v.1.2.335).

I'm on macOS Ventura 13.2.1 working in RStudio 2023.03.0-daily+30. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Nice catch. Fix incoming.

Do note that figures inside callouts will probably only work in HTML, though! In other formats, figures have to be "top-level" because of restrictions that we can't easily work around.

**Comment by EllaKaye** [comment]
Thanks Carlos. Noted about other formats. Having a figure in a callout was a bit of an off-piste thing I did in a blog post once, and I noticed this error kick in when I rebuilt the site after installing the pre-release.

**Comment by cscheid** [comment]
> Having a figure in a callout was a bit of an off-piste thing I did in a blog post once, and I noticed this error kick in when I rebuilt the site after installing the pre-release.

It totally surprised us when we saw the bug report come in, but there's no reason to not do it in HTML (and it surfaced a large number of other lurking bugs in quarto, so thank you for that!)

We're hoping to work on a linter for late 2023/early 2024, which will do more strict syntax checking to reduce the chances of breakage like this in the future.

**Comment by EllaKaye** [comment]
Thank you very much for your speedy reply and fix. This is working for me now on the latest pre-release. It's good to know that this fixed a bunch of other bugs too, not just my one-off use case (which, in case you're curious, is [here](https://ellakaye.co.uk/posts/2021-05-26_custom-highlighting-distill-2/#building-a-palette-based-on-my-pink-using-colour-theory-1)).

And, just a quick note while I'm here - thank you for all your awesome work building Quarto. It's a fabulous piece of software that I use extensively for personal, academic and profession projects. It's a joy to work with 😄

**Comment by cscheid** [comment]
> And, just a quick note while I'm here - thank you for all your awesome work building Quarto. 

We super appreciate the kind words. Your website is a favorite among the quarto dev crew, I assure you!

That post is 🔥 too. If we ever cross paths at a conf or something and we have a spare afternoon, it would be _really fun_ to do some interactive OJS widgets for exploring color palettes. Back when I was an academic in a related field, this work came out: http://vrl.cs.brown.edu/color I keep thinking about how neat it'd be to do something similar but more directly tied in to the rest of the content on a webpage. Your post reminded me of that.

**Comment by EllaKaye** [comment]
Aww, thanks Carlos. Those comments about my post and site made my day 😄 I do hope our paths cross at some point. Colorgorical looks interesting - thanks for bringing it to my attention. It would indeed be fun to do some kind of OJS widget. I don't actually know OJS, but I'd like to learn. I'm learning (vanilla) JavaScript at the moment and it's always more motivating to study with a project in mind.
