### ISSUE TITLE
Defining TeX macros in`include-in-header` does not work in HTML output

### ISSUE THREAD

**Issue by XiangyunHuang** [quarto-dev/quarto-cli#4629]
## Here is a minimal example.

````
---
title: "Untitled"
format:
  html:
    include-in-header:
      - header.html
---

## Math

$$
\bm{x} + x + \cancel{\text{///}}
$$
````

## The content of `header.html` as follow

```js
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      TeX: {
        Macros: {
          bm: ["{\\boldsymbol #1}",1],
        },
        extensions: ["cancel.js"]
      }
    });
</script>
```

## The output is

![](https://user-images.githubusercontent.com/12031874/222962318-9eda0493-ae02-4b3a-8c64-6cc63583e3c3.png)

That means user-defined TeX macros doesn't work.

## Quarto and RStudio IDE

I use Quarto 1.3.242

RStudio 2023.03.0+382 "Cherry Blossom" Release (3a8b92eb66f0754a31f03c010b41496abc65fb70, 2023-03-01) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+382 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I agree with you that I can't seem to get our MathJax version to see your configuration block. I'll follow up separately

However, in your particular case, there's an easier solution:

````
---
title: "Untitled"
format: html
---

## Math

$$
\newcommand{\bm}[1]{\textbf{#1}}
$$

$$
\bm{x} + x + \cancel{\text{///}}
$$
````

It turns out that MathJax supports `\newcommand` blocks "in math mode" natively, so that just works. (If you need these definitions in every file, then you can use `include` shortcodes.)

All that said, I still want to understand why the configuration block strategy isn't working.

**Comment by cscheid** [comment]
Ok, I see the issue. You're using MathJax 2's configuration style, while the html format uses MathJax 3.

Annoyingly, we need to use an older MathJax 2 version in the `revealjs` format, so your configurations will have to work differently if you use both the `revealjs` and `html` formats. This is something we'll fix in the future, but we're constrained by upstream requirements.

**Comment by XiangyunHuang** [comment]
Thank you for telliing me so many details about MathJax.
