### ISSUE TITLE
Quarto does not find chromium on Arch Linux, even though it is installed

### ISSUE THREAD

**Issue by astoeriko** [quarto-dev/quarto-cli#4648]
### Bug description

I am trying to render a Quarto document that includes a Mermaid diagram. I get this error message:

```
ERROR: Chrome not found

No Chrome or Chromium installation was detected.

Please run 'quarto tools install chromium' to install Chromium.
```

However, I have [Chromium](https://archlinux.org/packages/extra/x86_64/chromium/) installed through the Archlinux package manager pacman. `chromium --version` gives me `Chromium 110.0.5481.177 Arch Linux`, and I can also open the browser.

I suppose the problem is that the command is called `chromium` on my system, whereas Quarto [expects it to be named `chromium-browser`](https://github.com/quarto-dev/quarto-cli/blob/063c6a1422883a229f091bc949a9690c7b2318d1/src/core/puppeteer.ts#L209).

I am running Quarto version 1.2.313.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Unfortunately, we can't guess the name of chromium in every possible OS. Note that `chromium`, for example, _does_ exist in other Linux distros and is not to be chosen over `chromium-browser`. See eg https://forums.raspberrypi.com/viewtopic.php?t=281697

We could attempt to resolve `chromium` _after_ `chromium-browser`, but I'm not sure it's a net positive:

- If we resolve `chromium` after `chromium-browser`, then a user who installed `chromium` by accident would now experience a bug, exactly for the reasons described in the Rpi forum post above
- It seems like you can still `quarto tools install chromium` and that would still work
- You could set up `ln -s \`which chromium\` $HOME/.local/bin/chromium-browser`

If we were to resolve this properly, I think it should be with distribution-specific configurations that target `chromium` under Arch, and only under Arch. This would require a bigger architectural change, and be another situation where I don't know if the extra complication is worth the risk.

**Comment by astoeriko** [comment]
Thanks for having a look. I understand that it is difficult to account for differences in all the distributions.

I hesitate to use `quarto tools install chromium` because I do not really want Quarto to install software on its own, but linking to the existing executable sounds like a good option.
Maybe it would be best if distribution-specific packages do this “customization” step. (There is no official quarto package for Arch Linux, but there is a user-provided package in the Arch Linux user repository – that is how I installed Quarto.)

It could also be helpful to add a remark in [this section](https://quarto.org/docs/authoring/diagrams.html#chrome-install) of the Quarto documentation that Quarto expects `chromium-browser` and that it might be necessary to link that to `chromium`.

**Comment by cscheid** [comment]
> Maybe it would be best if distribution-specific packages do this “customization” step? (There is no official quarto package for Arch Linux, but there is a user-provided package in the Arch Linux user repository – that is how I installed Quarto.)

That seems like a good idea, except that we're not the ones building quarto packages for Arch.

**Comment by astoeriko** [comment]
> except that we're not the ones building quarto packages for Arch

Sure, I know. I will see if I can suggest a change in the packaging instruction to the respective maintainer.

Feel free to close this issue, as there does not seem to be a lot that can be done about it on the Quarto side (other than better explaining the problem and how to solve it).

**Comment by cscheid** [comment]
Thanks! I'll keep it open to track this general kind of issue in the future.

**Comment by cderv** [comment]
> Unfortunately, we can't guess the name of chromium in every possible OS. 

@cscheid just to share experience of our other R tools that are working with chrome 

* [`pagedown::find_chrome()`](https://github.com/rstudio/pagedown/blob/6f27778df1acf592206a5a06d01ced04b2d2e0d1/R/chrome.R#L301-L330)  will look for chrome for each OS, on Linux checking for `c('google-chrome', 'chromium-browser', 'chromium', 'google-chrome-stable')` and using first found. Setting env var `PAGEDOWN_CHROME` allow to specific a specific one to use 
* [`chromote::find_chrome()`](https://github.com/rstudio/chromote/blob/e1d2997932671642d12bef0b4c58611e322035c7/R/chrome.R#L41-L81) will so similarly, looking for `google-chrome`, `chromium-browser` and `chromium` , or using `CHROMOTE_CHROME` if set.

I think this cover all usage encountered with those tools. 

do you think we could offer a configuration through an environment variable so that user can configure the chrome binary to use with Quarto ? 

But if we can do same detection logic that would be great - we do some detection for R already to find where it is on Windows for example. 

Anyway, sharing for reference and inspiration for when we can tackle this.

**Comment by cderv** [comment]
For future reference, related issue where chromium is not found but an env var could help configure what to use https://github.com/quarto-dev/quarto-cli/issues/2980

**Comment by cderv** [comment]
I have opened an macro issue to track a proper solution 
- https://github.com/quarto-dev/quarto-cli/issues/10170

**Comment by arinbasu** [comment]
@cscheid , I have Vivaldi installed on OpenSuse, but quarto cannot find it either, and linking Vivaldi to chromium-browser does not help either.

**Comment by mcanouil** [comment]
@arinbasu Could you give the default path where it is located? As is your comment is not really useful unfortunately.
