### ISSUE TITLE
ERROR: "No inspectable targets"-error when rendering PDF containing Mermaid diagram

### ISSUE THREAD

**Issue by streepvaren** [quarto-dev/quarto-cli#4653]
### Bug description

Hello,

Í'm using:
- Latest version of R (4.2.2)
- Latest version of Rstudio  (2022.12.0 Build 353)
- Latest Quarto (version 1.2.335)
- Windows 10 Enterprise 22H2

When rendering a PDF from a .QMD-file containing a Mermaid diagram [(https://quarto.org/docs/authoring/diagrams.html)](https://quarto.org/docs/authoring/diagrams.html), my Rstudio gives the error "ERROR: No inspectable targets" and crashes (I'm unable to press stop).
In the past the same .QMD file rendered to PDF without any problem. Rendering to .HTML still works. The same error was recently reported by an Obsidian user: [https://forum.obsidian.md/t/about-quarto-no-inspectable-targets-error/54757](https://forum.obsidian.md/t/about-quarto-no-inspectable-targets-error/54757).

The .QMD-file i'm using can be found in the attached .ZIP (Github doesn't allow uploading QMD's directly, therefore I zipped).

Thanks for the good work!

Best,
Thomas

[testdia.zip](https://github.com/quarto-dev/quarto-cli/files/10902790/testdia.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Can you try with our 1.3 prereleases? I'm not on windows, but I can't reproduce the issue:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/285675/223234368-47ebeab0-347e-4741-ae91-d02c09573a3c.png">

**Comment by streepvaren** [comment]
Dear Carlos,

After installing the 1.3.247 prerelease I still get the error when rendering a PDF (HTML works fine).

This time the error is more complex:

```
ERROR: No inspectable targets

Error: No inspectable targets
    at defaultTarget (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:55313:23)
    at Chrome._fetchDebuggerURL (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:55436:37)
    at async Chrome._start (file:///C:/Users/20003963/AppData/Local/Programs/Quarto/bin/quarto.js:55392:25)
```

Best regards,
Thomas

**Comment by cscheid** [comment]
@cderv will know the details, but there are issues with Windows and headless Chrome.

**Comment by cderv** [comment]
I can reproduce with using Chrome browser from my system. 

It works ok if I use `chromium` install with Quarto `quarto install tools chromium` - something must have changed with newest Chrome browser. I need to look into that.

**Comment by streepvaren** [comment]
Thank you very much for the quick help @cscheid and @cderv!  `quarto install tools chromium` fixed the problem!

Best regards,
Thomas

**Comment by cderv** [comment]
@cscheid  should we reopen to solve this for Chrome browser, or do you consider our internal chromium to be the solution ? 

Here are some detailts on what happens. 

We are retrieving the debugger url 
https://github.com/quarto-dev/quarto-cli/blob/e72f556f7e0867c1daec95fadc5d34b305ffa723/src/core/cri/deno-cri/chrome.js#L158

For that some targets are looked into , default being using `defaultTarget` function
https://github.com/quarto-dev/quarto-cli/blob/e72f556f7e0867c1daec95fadc5d34b305ffa723/src/core/cri/deno-cri/chrome.js#L74

For the default targets we are calling 
https://github.com/quarto-dev/quarto-cli/blob/e72f556f7e0867c1daec95fadc5d34b305ffa723/src/core/cri/deno-cri/chrome.js#L210-L211
which query  `json/list` endpoint, calling `defaultTarget()` on it.

I don't know yet why but with the Chrome browser version mentioned above, this will be empty 
````
targets
(0) []
````

No targets to inspect. 

This why code currently throw the error from 
https://github.com/quarto-dev/quarto-cli/blob/e72f556f7e0867c1daec95fadc5d34b305ffa723/src/core/cri/deno-cri/chrome.js#L59-L64

@cscheid hope it helps you know what can be done. I'll look closer tomorrow about why we get this in Chrome now. 

Maybe we need to open a target if none exists. FWIW, testing with chromium from quarto install, the targets to explore was `about:blank` 

````
$ targets
[
  {
    description: "",
    devtoolsFrontendUrl: "/devtools/inspector.html?ws=localhost:9222/devtools/page/BA596C8DC87F7F55499F46F0EC363E27",
    id: "BA596C8DC87F7F55499F46F0EC363E27",
    title: "about:blank",
    type: "page",
    url: "about:blank",
    webSocketDebuggerUrl: "ws://localhost:9222/devtools/page/BA596C8DC87F7F55499F46F0EC363E27",
  },
]
````

> and crashes (I'm unable to press stop).
 
I reproduce this also. We throw the error and then impossible to stop Quarto.

**Comment by cscheid** [comment]
@tomkom Oof, that's really no good. I'm on OSX Ventura as well and thought I had fixed this issue. I'm no longer seeing the crash, but clearly the fix didn't stick.

**Comment by cscheid** [comment]
Unfortunately, I can't seem to make the crash stop with Chromium on OS X Ventura.

So, we're changing the resolution order of browsers. If we find Google Chrome (for which the crash doesn't happen), then we use that directly, even if the user has installed Chromium.

We will still use Chromium if we don't find Google Chrome, but using Chromium will likely cause this crash.

**Comment by rgayler** [comment]
I am getting the original problem "ERROR: No inspectable targets" rendering a mermaid diagram to PDF (HTML works OK).

Ubuntu 22.04.2
R 4.2.2
RStudio 2023.03-0 build 386 
quarto 1.2.335
chrome installed
chromium installed
`quarto install tools chromium` installed

Let me know if there's something diagnostic I can do to get some more info on what's happening here.

Thanks.

**Comment by cscheid** [comment]
> quarto 1.2.335

You need to download and install a newer version of quarto.

**Comment by rgayler** [comment]
Thanks @cscheid - that worked perfectly. I had misread the quarto version number and wrongly believed I was using the latest version.
