### ISSUE TITLE
Jupyter Cell Embedding Notebook View "Download link" downloads HTML not ipynb

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#4654]
### Bug description

Attempted to "Download Notebook" at:  https://quarto.org/docs/prerelease/1.3/plots.ipynb

File that is downloaded has `.ipynb` extension, but the contents is actually HTML.

This line in the page source is the culprit:

```html
<a href="https://quarto.org/docs/prerelease/1.3/plots.html" class="btn btn-primary quarto-download-embed" download="plots.ipynb">Download Notebook</a>
```

However, I don't know where this gets generated. @dragonstyle this is part of the Jupyter Cell Embedding feature so perhaps your domain.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thank you for finding this!!
