### ISSUE TITLE
Jupyter Cell Embedding: Embedding Code `echo` doesn't seem to work

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#4656]
### Bug description

The [docs](https://quarto.org/docs/prerelease/1.3/embed.html#embedding-code) suggest this should show the **code** and output:
```
{{< embed plots.ipynb#plot-dot echo=true >}}
```

I'd expect to see the code:
```
import matplotlib.pyplot as plt
x=[3,4,5,6,7,8,9,10,11,12]
y= [9,16,25,36,49,64,81,100,121,144]
plt.scatter(x,y)
plt.show()
```
But, no code is shown.

@dragonstyle Also checked in a minimal project locally and don't get an echo.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
This is a great catch, thank you.

**Comment by cscheid** [comment]
This should be closed on `main` now. Thanks for catching the regression!
