### ISSUE TITLE
unable to resolve crossref in callouts of a book

### ISSUE THREAD

**Issue by bwelman** [quarto-dev/quarto-cli#4672]
### Bug description

In a book project with Quarto 1.3.247 (and 1.3 versions before) there is an issue with cross references when the document contains a list (numbered or bulleted), and later in the document a callout with a figure in it. Rendering gives then a warning: unable to resolve crossref.

Commenting out the list clears the error. And when the list is after the callout then also no problem. Furthermore there are no problems when rendering with Quarto version 1.2.335

OS: Windows 10, Repro: [crossreftest](https://github.com/bwelman/crossreftest)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
This works for me on `main`:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/285675/223802508-696858bd-04b3-4335-88b7-a9cd9b4a2729.png">
