### ISSUE TITLE
Document or support minimum rmarkdown version

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#4673]
In my testing, we appear to require markdown 2.3 or later. We should consider either documenting / checking this minimum in `quarto check`, or adding support for older versions, whatever makes the most sense.

**Comment by cderv** [comment]
Thanks @dragonstyle ! 

For reference, it seems to be an issue with `extract_preserve_chunks` that error when rmarkdown before 2.3 is installed.

Also for reference and context, this relates to work in #4647 adding minimum version requirement check for **knitr**

**Comment by coatless** [comment]
Maybe related to https://github.com/quarto-dev/quarto-cli/issues/6960
