### ISSUE TITLE
latex block-layout return `LaTeX Error: Something's wrong--perhaps a missing \item.`

### ISSUE THREAD

**Issue by benabel** [quarto-dev/quarto-cli#469]
Hi dear developers, and as allways thanks for this program.

I found compilations errors rendering the [block-layout examples from the doc](https://quarto.org/docs/authoring/figures.html#block-layout) to latex/pdf. 

```md
::: {layout-ncol=2}
### List One

- Item A
- Item B
- Item C

### List Two

- Item X
- Item Y
- Item Z
:::
```

I tried the example in html and docx, they both work as expected.

**Comment by jjallaire** [comment]
@dragonstyle I did some debugging and discovered that this issue occurs b/c of the `\raisebox` wrapper we put around the minipage contents. I'm not familiar w/ that, but it seems like it has something to do with figures so perhaps something we shouldn't be emitting in any case here?

**Comment by dragonstyle** [comment]
I'll take a closer look!

**Comment by dragonstyle** [comment]
Ok this should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/3b81e3650293222d6e7c6398fcfa1ffb69a200ed

A fresh release is on the way!

**Comment by benabel** [comment]
I tested on main branch, it's fixed on my builds. Thank you very much.
