### ISSUE TITLE
Different callout border color behavior in HTML and PDF output 

### ISSUE THREAD

**Issue by XiangyunHuang** [quarto-dev/quarto-cli#4690]
## A minimal example

````
---
title: "My document"
format: 
  pdf:
    documentclass: article
  html:
    theme: cosmo
---

# Callout

All callout's border color are different in HTML and PDF output since Quarto 1.3.x, I prefer HTML output than PDF.

::: {.callout-tip}
hello
:::

::: {.callout-note}
hello
:::

::: {.callout-warning}
hello
:::

::: {.callout-caution}
hello
:::
````

### HTML

<img width="840" alt="截屏2023-03-08 08 35 10" src="https://user-images.githubusercontent.com/12031874/223588508-30366588-6856-4c71-bb46-46a268e40096.png">

### PDF

<img width="665" alt="截屏2023-03-08 08 34 28" src="https://user-images.githubusercontent.com/12031874/223588343-692cd930-ca03-4679-b1be-8f15c5f53e6d.png">

## Quarto and RStudio version

I use Quarto 1.3.242

RStudio 2023.03.0+382 "Cherry Blossom" Release (3a8b92eb66f0754a31f03c010b41496abc65fb70, 2023-03-01) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+382 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by XiangyunHuang** [comment]
BTW, It seems that table header much heavy than before in HTML output, is it intentional?

## Quarto 1.3.242

<img width="768" alt="截屏2023-03-08 08 41 13" src="https://user-images.githubusercontent.com/12031874/223589271-6c752e0c-9273-4818-b7f7-b48795e9a8d4.png">

## Quarto 1.2.335

<img width="823" alt="截屏2023-03-08 08 47 24" src="https://user-images.githubusercontent.com/12031874/223590101-9c0421bd-b1f2-4ebe-80e4-87612f3df509.png">

**Comment by cscheid** [comment]
@XiangyunHuang Thanks for the followup. It's easier for us to track issues if you keep different problems on different issues. Can you open a new issue to discuss the table style? As usual, please share a full .qmd.

**Comment by dragonstyle** [comment]
We've restored the previous callout behavior for PDF. Thx for raising the issue!

**Comment by XiangyunHuang** [comment]
@cscheid Ok, another issue #4717  is opened, honestly, I'm not sure if it is a bug.
