### ISSUE TITLE
404 not behaving correctly for subdirectories

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-cli#47]
I have a `404.md`  in the root directory of the preview site for the Workbench redesign:

- [Repo](https://github.com/pommevilla/incog-workbench)
- [Preview site](https://pommevilla.github.io/incog-workbench/)

When I serve this locally, the 404 page works as expected: going to `http://localhost:4848/fake.html` and `http://localhost:4848/getting_started/fake.html` both show the correctly rendered 404 page and in both cases I am able to navigate away via the sidebar and the navbar.

When I try this on the live preview site, the 404 page correctly renders for [https://pommevilla.github.io/incog-workbench/fake.html](https://pommevilla.github.io/incog-workbench/fake.html) and I am able to navigate away as above. However, when I try [https://pommevilla.github.io/incog-workbench/getting_started/fake.html](https://pommevilla.github.io/incog-workbench/getting_started/fake.html), the 404 page doesn't render correctly and I can't navigate away from the sidebar and the url just keeps piling up as I click around to something like `https://pommevilla.github.io/incog-workbench/getting_started/getting_started/authenticating_users/access_and_security/access_and_security/authenticating_users/access_and_security/secure_sockets.html` - all the links I'm clicking are taken as relative to the directory of the incorrect page. 

I've set `site-url: https://pommevilla.github.io/incog-workbench`. I tried this with and without the `permalink: /404.html` suggested by Github [here](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site) and still get the same behavior. 

I looked around and found several places saying that custom 404 pages for subdirectories don't work when served out of the root directory: [here](https://github.community/t/links-on-custom-404-page-broken-when-accessed-from-subdirectory-solved/10443). Since the issue seemed to be around working out of a subdirectory, I copied the repo and hooked that up to a [custom domain](https://incog-workbench.com/), but I'm still getting the same behavior: links like [https://incog-workbench.com/broken.html](https://incog-workbench.com/broken.html) work fine, but links like [https://incog-workbench.com/load_balancing/broken.html](https://incog-workbench.com/load_balancing/broken.html) still lead to the same behavior above.

**Comment by jjallaire** [comment]
Okay, Netlify and GH Pages might work differently here. I'll take a closer look.

**Comment by jjallaire** [comment]
We should be okay serving out of the root directory so long as we write the HTML correctly. I just pushed a change that I verified writes the links correctly in my own fork of your repo. Could you sync to the latest dev version and try doing a full re-render? I'll also kick off a new build in case it's easier for you to try from an installed version (should be ready in ~ 1hr)

**Comment by pommevilla** [comment]
Everything appears to be working now. For both sites, 404 pages are rendering correctly from subdirectories and I can navigate away from 404s that show up in subdirectories. 

I had an issue originally where the fix wasn't working, but that was because the `quarto-render` action I use in my repos was pulling an older build. The action is updated to the build that just came out (v0.1.130) that was released and everything is working fine.  Thanks!
