### ISSUE TITLE
make conda package report version accurately

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#4707]
Our current conda package reports a wrong quarto version, which is problematic:

```
The following NEW packages will be INSTALLED:

  dart-sass          conda-forge/osx-arm64::dart-sass-1.58.3-hce30654_0
  deno               conda-forge/osx-arm64::deno-1.25.2-hce30654_0
  deno-dom           conda-forge/osx-arm64::deno-dom-0.1.23-hb9e0d3b_0
  esbuild            conda-forge/osx-arm64::esbuild-0.15.5-hce30654_1
  pandoc             conda-forge/osx-arm64::pandoc-2.19.2-hce30654_2
  quarto             conda-forge/osx-arm64::quarto-1.2.335-hce30654_1

The following packages will be UPDATED:

  conda                             22.11.1-py310hbe9552e_1 --> 23.1.0-py310hbe9552e_0


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
$ which quarto
/Users/cscheid/conda/bin/quarto
$ quarto --version
1.2.1
```

Our build script is here https://github.com/conda-forge/quarto-feedstock/blob/main/recipe/build.sh

And @msarahan tells me that the conda version information is taken from https://github.com/quarto-dev/quarto-cli/blob/v1.2/configuration#L46. Instead, `build.sh` should be setting QUARTO_VERSION to whatever the right information is. In the installers, I believe this info comes ultimately from the git tag (@dragonstyle can confirm). So we need to figure out where this mismatch happens and fix.

**Comment by msarahan** [comment]
The conda version info isn't specifically taken from `configuration`. The conda package (in terms of conda metadata) is correct. What is incorrect is quarto's internal version. That version starts with `configuration` and then seems to get appended to. We have to have a way to override or avoid the append process, or otherwise short-circuit a hard-coded version number.

**Comment by msarahan** [comment]
Here's where it happens: https://github.com/quarto-dev/quarto-cli/blob/2f3507a1231e1e28cd0684259681938492f140ce/package/src/common/prepare-dist.ts#L127

Since the check for appending the .1 is just based on the length, I think I can work this out. Probably new packages by end of workday.

**Comment by msarahan** [comment]
fix in the works at https://github.com/conda-forge/quarto-feedstock/pull/5
