### ISSUE TITLE
Unable to show or hide code that is not executable

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#4714]
It would be nice if we could add the same `code-fold` options to a markdown code block that is not a computation block just by adding appropriate classes. 

I would like something like `{.julia code-fold=true}` to make that specific code block collapsed by default with an option to expand it.

**Comment by cderv** [comment]
For reference I believe we have a duplicate issue with #4693

**Comment by GegznaV** [comment]
As the issues duplicate, there is an HTML workaround for this issue: https://github.com/quarto-dev/quarto-cli/issues/4693#issuecomment-1464883131
You can create an RStudio or VSCode snippet to save some typing.

There are R Markdown-like options for Quarto too (use `{julia}`, not `{.julia}`).
- For non-executable code: 
```r
```{julia, eval=FALSE}
````

    Non-executable code:
![image](https://user-images.githubusercontent.com/12725868/224484179-ebc64bb7-ebee-4408-ac35-e3945147e564.png)

- For executable code: 
```r
```{julia}
````
    Executable code:
![image](https://user-images.githubusercontent.com/12725868/224484175-4ae1d873-d1c8-4f80-8883-8972dfd84c45.png)
