### ISSUE TITLE
Table header rule much heavy than before in HTML output

### ISSUE THREAD

**Issue by XiangyunHuang** [quarto-dev/quarto-cli#4717]
### Bug description

Table header rule much heavy than before in HTML output, is it intentional?

## a minimal example

````
---
title: "My document"
format: 
  html:
    theme: cosmo
---

# Table

```{r}
knitr::kable(head(iris,3))
```
````

##  HTML output from Quarto 1.2.335

<img width="843" alt="截屏2023-03-09 08 38 58" src="https://user-images.githubusercontent.com/12031874/223885184-4ffb4a62-7f89-435b-894f-d4523b65d450.png">

## HTML output from Quarto 1.3.250

<img width="835" alt="截屏2023-03-09 08 43 39" src="https://user-images.githubusercontent.com/12031874/223885747-89a5cf88-c074-4138-b078-87d2500f59f1.png">

## RStudio Info

RStudio 2023.03.0+382 "Cherry Blossom" Release (3a8b92eb66f0754a31f03c010b41496abc65fb70, 2023-03-01) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+382 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
yes, this is the same style we use for regular tables:

````
---
title: "My document"
keep-md: true
format: 
  html:
    theme: cosmo
---

# Table

```{r}
knitr::kable(head(iris,3))
```

| Sepal.Length| Sepal.Width| Petal.Length| Petal.Width|Species |
|------------:|-----------:|------------:|-----------:|:-------|
|          5.1|         3.5|          1.4|         0.2|setosa  |
|          4.9|         3.0|          1.4|         0.2|setosa  |
|          4.7|         3.2|          1.3|         0.2|setosa  |

````

<img width="873" alt="image" src="https://user-images.githubusercontent.com/285675/223891487-64bf983c-e8cf-42e5-b5e1-de455ec04baf.png">
