### ISSUE TITLE
Light and dark themes in a custom format

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#4731]
(This appears to work in document front matter, but not extensions for some reason:

```
---
title: Untitled
format:
  html+bar: 
    toc: false
author: Charles Teague
date: last-modified
---
```

works as I'd expect, but not:

```
  formats:
    html:
      toc: true
      theme: [yeti, custom.scss]
    html+bar:
      toc: false
      theme: [sketchy, custom.scss]
```

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4700

<div type='discussions-op-text'>

<sup>Originally posted by **juba** March  8, 2023</sup>
Hi,

I'm currently developing a custom HTML format which provides both a light and dark theme. I have something like the following in my `_extension.yml` :

```yaml
      theme:
        light: [bookup.scss]
        dark: [bookup.scss, bookup_dark.scss]
```

This is working fine, but maybe the custom format users will want to only use the light theme, or only the dark theme, or even provide both but with the dark one by default. Is there a way to provide such a feature in a custom format ? I took a look at the documentation but didn't find a way to do this.

Thanks in advance !
</div>

**Comment by dragonstyle** [comment]
This should work in our next pre-release build!

**Comment by juba** [comment]
Hi,

Thanks, I can confirm it is working in the development version. Thanks a lot !

Just a minor issue : this doesn't work if there is an hyphen in the variant name. So `html+dark-only` generates an error message, but `html+darkonly` is working fine.

Thanks again, this will be very useful for custom formats.
