### ISSUE TITLE
Grid view doesn't display default first image in post

### ISSUE THREAD

**Issue by richardsprague** [quarto-dev/quarto-cli#4744]
### Bug description

A listing grid view should, by default, display the first image found in the post.  That's what I get in v1.2
![Pasted_Image_3_9_23__1_54_PM](https://user-images.githubusercontent.com/2120747/224169042-3070c88d-e7d8-4fb1-a4a0-f4d722d44599.jpg)

But in v1.3.253, the image is greyed out.
![image](https://user-images.githubusercontent.com/2120747/224169127-24a7fae5-8c89-46c6-8ca8-395ba02f2b51.png)

gridpost.qmd
```
---
title: "Typical grid"
listing: 
    categories: true
    type: grid
    sort: date desc
---
```

index.qmd
```
---
title: "Intro"
---

# Sample Page

This is a simple page with the following image:

![Caption for Quarto Logo Image](https://quarto.org/quarto.png)
```
Note: the error happens whether it's a remote URL image or local.

See a working example [here](https://github.com/richardsprague/quartosample)

FWIW I'm using VS Code on OSX 13.2.1

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks! I can repro this here.

Interestingly, I get a warning `[WARNING] Could not fetch resource ./gridpost.html` in both 1.2 and 1.3, but 1.2 does seem to locate the image successfully.

**Comment by cscheid** [comment]
Hm. git bisect points at 7ebcc5e4360fc026f3144c0bda5edba5eed78261 which clearly makes no sense.

I'm also suspicious of the nearby c372f62971b07c0661917f11a4e22a57ee56aa9c

I suspect it was the move to Pandoc 3, since v1.3.217 doesn't show the bug, but v1.3.222 does.

**Comment by dragonstyle** [comment]
I'm very suspicious about the second commit you highlighted which may have made the rules for discovering preview images more strict.

**Comment by dragonstyle** [comment]
(I'll take a closer look for 1.3!)

**Comment by dragonstyle** [comment]
Thanks for catching this - the logic for discovering images and become more strict, which should be remedied in our next pre-release build.
