### ISSUE TITLE
PDF with embedded images from remote URL with odd filenames

### ISSUE THREAD

**Issue by richardsprague** [quarto-dev/quarto-cli#4747]
### Bug description

Quarto outputs proper HTML for an image file like this one:
```
![Great Pyramid](https://sat02pap004files.storage.live.com/y4m52ot143vPFNPo0C4wwvFwbWGJz9PYvIxAv3aPcZV9KHpimnZ2ErrEafT22gFuFM3lP-nJYiGpwzfq1wJ2X-kPIroYIPqhzYm01Hx6B4x40cPkesS9FVXJvFfkj9mtdBGFOhl1WVJd0xushOybTa9GTYsn-tKZCn7T0IAHSplCK-VBGhncjA-D09aJ-fJ8Ldq?width=256&height=192&cropmode=none)
```

![Great Pyramid](https://sat02pap004files.storage.live.com/y4m52ot143vPFNPo0C4wwvFwbWGJz9PYvIxAv3aPcZV9KHpimnZ2ErrEafT22gFuFM3lP-nJYiGpwzfq1wJ2X-kPIroYIPqhzYm01Hx6B4x40cPkesS9FVXJvFfkj9mtdBGFOhl1WVJd0xushOybTa9GTYsn-tKZCn7T0IAHSplCK-VBGhncjA-D09aJ-fJ8Ldq?width=256&height=192&cropmode=none)

But v1.3.253 will not embed that into a PDF.  Instead, I get this error:

```
compilation failed- error
Missing endcsname inserted.
<to be read again> 
                   &
l.200 ...width=256\&height=192\&cropmode=none.pdf}
```
I assume that's an [issue with how TeX handles filename characters](https://tex.stackexchange.com/questions/448314/not-able-to-use-images-if-i-call-gb4e-sty) ?

P.S.  Full working example is [in this repo.](https://github.com/richardsprague/quartosample)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Yes, I think that's exactly right.

Specifically, I think we need to be more defensive in `src/resources/filters/quarto-post/pdf-images.lua`.

**Comment by cscheid** [comment]
This was a fun one, thanks for reporting!

There are a couple of things going on. We had a bug, which we just fixed, and it was exactly related to the issue with filenames.

However, there's a new wrinkle. Your URL doesn't end in an extension. That means that quarto assumes the extension will be .pdf. We will make an enhancement in the future that takes the fetched mimetype into account, but we don't want to risk a bigger change close to our 1.3 release.

In your specific case, though, there's a simple workaround, which is to introduce a knowingly-bogus URL parameter that happens to end with `.jpg`. So, do this:

```
![Great Pyramid](https://sat02pap004files.storage.live.com/y4m52ot143vPFNPo0C4wwvFwbWGJz9PYvIxAv3aPcZV9KHpimnZ2ErrEafT22gFuFM3lP-nJYiGpwzfq1wJ2X-kPIroYIPqhzYm01Hx6B4x40cPkesS9FVXJvFfkj9mtdBGFOhl1WVJd0xushOybTa9GTYsn-tKZCn7T0IAHSplCK-VBGhncjA-D09aJ-fJ8Ldq?width=256&height=192&cropmode=none&please_make_it=.jpg)
```

Note the `&please_make_it=.jpg` end.

With this (and the latest quarto version on `main`), your file works.
