### ISSUE TITLE
HTML format: lists with extra <p>

### ISSUE THREAD

**Issue by MHellmund** [quarto-dev/quarto-cli#4750]
### Bug description

Quarto version: pull from today, code executed by jupyter

example.qmd:

    # header 1

    - item1
    - item2
    - item3a

    ```{python}
    1 + 1
    ```

 `quarto render example.qmd --to html`  generates: 

```
....
<ul>
<li><p>item1</p></li>
<li><p>item2</p></li>
<li><p>item3a</p></li>
</ul>
....
```
This didn't happen with my last pull from a week ago. It only happens when a code cell is present. 
 I tried to bisect it and it seems that   https://github.com/quarto-dev/quarto-cli/commit/d03158946ddeef6fef7c1b9b1a702bc8d051df92  is related. 

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I just tried executing this and I get:

```
<ul>
<li>item1</li>
<li>item2</li>
<li>item3a</li>
</ul>
```

Is it possible that your file had a line break between the list items at some point? Pandoc has a feature that distinguishes between "tight" and "loose" lists. If there are any breaks between any items in a list, Pandoc will emit a "loose" list, which means "lists where every element is a paragraph".

**Comment by cscheid** [comment]
@MHellmund Turns out the problem was _precisely_ where you pointed out, thank you!! We'll fix in the next few hours.

**Comment by MHellmund** [comment]
Thanks, you are super fast! I actually met the bug working on a 'book'. For most chapters I don't need metadata outside of  `_quarto.yaml` and I feel that

```
# chapter title

## section title
```

looks somewhat more in the spirit of markdown than

```
---
title: chapter title
---

## section title
```

So thank you for supporting it!

**Comment by cscheid** [comment]
> Thanks, you are super fast!

We're hoping to ship 1.3 in the next few weeks so are being hypervigilant on our incoming bug queue. The pull request is up: https://github.com/quarto-dev/quarto-cli/pull/4753
