### ISSUE TITLE
Error using _variables.yml with self-contained markdown formatting

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#4758]
Hi -

I set up a `_variables.yml` file for a Quarto book project here:
https://github.com/dspatterns/dspatterns-book/blob/main/_variables.yml

I followed the example from the [docs](https://quarto.org/docs/authoring/variables.html) to format my markdown links:
```
version: 1.2

email:
  info: info@example.com
  support: support@example.com

engine:
  jupyter: "[Jupyter](https://jupyter.org)"
  knitr: "[Knitr](<https://yihui.name/knitr>)"
```

This works-ish: the self-contained markdown formatted links always render perfectly on the first use of the variable in a given `.qmd`. The problem is using that variable again in the same `.qmd`: it looks like it doesn't parse correctly. I tried this by switching out several different variables and this was always true: the first works, any other uses of the same variable in the same `.qmd` are gobbledy-gook. Here is a good example using `{{< var gha.docs >}}` and `{{< var web.host >}}` 2x each:

```
The combination of Link ("",[],[]) [Str "GitHub",Space,Str "Actions",Space,Str "(GHA)"] ("https://github.com/features/actions","") and Link ("",[],[]) [Str "Netlify"] ("https://www.netlify.com","") means that the book is automatically updated after every commit to the main branch on GitHub.
```

Source:
https://github.com/dspatterns/dspatterns-book/blob/main/onboarding/book.qmd

You can see what happens here:
https://dspatterns.netlify.app/onboarding/book.html

**Comment by cscheid** [comment]
(👋 !!)

We _just_ fixed a similar bug recently with multiple invocations of shortcodes. Before we go figure this one out, do you mind trying your code on our latest pre-release? I just fired off [a build](https://github.com/quarto-dev/quarto-cli/actions/runs/4388784081), but it's not ready yet. If you keep an eye on the [releases page](https://github.com/quarto-dev/quarto-cli/releases), can you try anything later than 1.3.253? Thanks!

**Comment by cscheid** [comment]
https://github.com/quarto-dev/quarto-cli/releases/tag/v1.3.255

**Comment by apreshill** [comment]
hey hey!

Alright I updated and didn't change anything in my source and I'm seeing:

```
Error running Lua:
/Applications/quarto/share/filters/qmd-reader.lua:90: invalid pattern capture
stack traceback:
        /Applications/quarto/share/filters/qmd-reader.lua:90: in function 'escape_invalid_tags'
        /Applications/quarto/share/filters/qmd-reader.lua:103: in function 'Reader'
```

**Comment by cscheid** [comment]
Hi. This is clearly a bug on our side, but I need some help installing some of the packages:

```
Error in library(dspatterns) : there is no package called 'dspatterns'

> install.packages("dspatterns")
Error: package 'dspatterns' is not available
```

@rich-iannone you can slack me if needed.

**Comment by apreshill** [comment]
Hey @cscheid - thank you! And sorry re: non-reprexes. The package is on github:
https://github.com/dspatterns/dspatterns

```
devtools::install_github("dspatterns/dspatterns")
```

**Comment by cscheid** [comment]
Ok, this is a bug on our side, but check this out:

https://github.com/dspatterns/dspatterns-book/blame/main/appendix/90-lists-and-factors.qmd#L416

That is _one weird code cell_ :)

I need to make our code robust against these characters, but if you fix that line, then the book compiles (and then you can tell me if the original issue is resolved!)

**Comment by cscheid** [comment]
This should be fixed on `main`. We'll fire off a new build later tonight. Thanks!

**Comment by apreshill** [comment]
haha I cannot do the 😱 as a reaction - thank you! I'll fix that right away.
