### ISSUE TITLE
create-project "." creates "..qmd"

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#476]
Using Quarto 0.9.80:

```bash
quarto create-project .
# => Creating project at <FULL-PATH-TO-DIR>:
# =>   - Created _quarto.yml
# =>   - Created ..qmd
``` 

The "." directory name does not indicate its name and should not be used when creating the initial `*.qmd` file.

The `quarto create-project .` should produce the same result as `quarto create-project` or `quarto create-project <FULL-PATH-TO-DIR>`.

**Comment by dragonstyle** [comment]
Should be fixed here: 64cffd5b7bbd64e2edbfd5cc33d7b64563d0961c

Thanks for finding this!
