### ISSUE TITLE
PAckages causing incosistency

### ISSUE THREAD

**Issue by mchruszczewski** [quarto-dev/quarto-cli#4762]
### Bug description

Hi, 
![Screenshot 2023-03-11 at 10 47 17](https://user-images.githubusercontent.com/119865563/224477420-a43b2825-ec07-4f59-898f-8a789ed6b1c6.png)

I get this error when I try to execute: conda install r-quarto. Can you please help me? I tried to update conda, anaconda, but nothing works for me and I would like to use quarto in jupyter lab in Anaconda Navigator.

Thanks an regards from Poland!
Michal

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
Are you referring to this conda-forge package ? https://anaconda.org/conda-forge/r-quarto

Just to be clear, this is the R package from CRAN https://cran.r-project.org/web/packages/quarto which is only useful to run Quarto CLI from R - you still need to install Quarto CLI on its own. 

Regarding the R package Quarto available on Conda forge, I don't know how this is built. We do nothing specific on the R package https://github.com/quarto-dev/quarto-r for its availability on conda. Maybe there is a conflict between your conda project and how R package can be installed with conda. Usually installing R package from CRAN is the best way for an R installation. Not sure where you can report. Maybe at https://github.com/conda-forge/r-quarto-feedstock ? 

However, the Quarto CLI installer is at https://anaconda.org/conda-forge/quarto and we (@msarahan) maintain this at https://github.com/conda-forge/quarto-feedstock/ - But this is not what you installed here.

**Comment by msarahan** [comment]
"inconsistency" means you have at least two packages in your environment that have conflicting requirements. Once this happens, conda will not behave well. Your solve times will skyrocket. I recommend abandoning this environment and creating new environments that are more focused to individual projects. If this is your base environment, you might want to start with a fresh miniconda install, and build up your new environments from scratch.

https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
https://www.machinelearningplus.com/deployment/conda-create-environment-and-everything-you-need-to-know-to-manage-conda-virtual-environment/

**Comment by mchruszczewski** [comment]
Thank you!
