### ISSUE TITLE
Listings won't display image thumbnails when in a subdirectory

### ISSUE THREAD

**Issue by richardsprague** [quarto-dev/quarto-cli#4774]
### Bug description

To simplify my large project, I rely on subdirectories, each of which contains a "listing" file.
For example:
```
├── grid
│   ├── famous_deaths.qmd
│   └── gridpost.qmd
- index.qmd

```
where `gridpost.qmd` just has a `listing` item in its metadata yml.

the output correctly shows the grid listing, but the thumbnails are missing. 

Hint: from inspecting the html code that was generated, it appears that the pathnames are screwed up. Instead of `<src = "image.jpg" /> ` it generates `<src = "grid/image.jpg" />

I placed a simple example of this in [my github repo](https://github.com/richardsprague/quartosample/tree/extrapage).  The thumbnails display correctly on v1.2, but not on v1.3.257.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I believe that this is fixed in the latest version of the pre-release. (Probably fixed here 5d8246a0d2825994738ad8db5d82bfb0cbb51681)
