### ISSUE TITLE
`quarto preview --port xxx` silently uses other port if port is already in use

### ISSUE THREAD

**Issue by wch** [quarto-dev/quarto-cli#479]
For example, if port 4000 is already in use, then this just uses another port.

```
$ quarto preview --port 4000
Check file:///Users/winston/quarto-cli/src/quarto.ts
Preparing to preview

Watching files for changes
Browse at http://localhost:7936/
```

It would be helpful to print a warning or throw an error.

**Comment by jjallaire** [comment]
Agreed this should be an error condition. Fixed here: https://github.com/quarto-dev/quarto-cli/commit/243dbf035df98ce49217482d542d0c789a5f8e8b
