### ISSUE TITLE
in a book refs are repeated at the end of the chapter and in references.qmb in quarto 1.3.260, but not in quarto 1.2.335 

### ISSUE THREAD

**Issue by xtimbeau** [quarto-dev/quarto-cli#4791]
### Bug description

Just create a book project and render it. References should be rendered in the page references as stipulated by the yaml. However in quarto 1.3.260 references are also included in each chapter where they are referenced.

`quarto create-project abook --type book
`
render from RStudio

quarto version 1.3.260, RStudio version 2022.12.1 Build 362, windows 11 OS and macOS as well. (note deno is up to date)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
@dragonstyle it seems something maybe off here. `citation-location` is not working as expected it seems either.

**Comment by dragonstyle** [comment]
Thanks for catching this - it will be fixed in our next pre-release build (building now!)

**Comment by xtimbeau** [comment]
fantastic, 1.3.262 is working as expected. Thanks.

Le lun. 13 mars 2023 à 13:40, Charles Teague ***@***.***> a
écrit :
