### ISSUE TITLE
Update Revealjs to latest version 5

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#4795]
Edit 30/10/2023: 5.0.0 is now out: https://github.com/hakimel/reveal.js/releases/tag/5.0.0

Edit: 26/04/2024 5.1.0 is now out: https://github.com/hakimel/reveal.js/releases/tag/5.1.0

## Main 

- [x] Update main dependency
	- [x] JS scripts
	- [x] Themes
- [x] Update plugins
	- [x] chalkboard - 2.3.3 update in revealjs-plugin 4.2.5 update (https://github.com/rajgoel/reveal.js-plugins/releases/tag/4.2.5)
		- [x] 	Patched version required for a fix (https://github.com/rajgoel/reveal.js-plugins/pull/180)
	- [x] menu - no update
	- [x] pdfexport - no update
	- [x] multiplexer - no release but new security stuff it seems: https://github.com/reveal/multiplex/commits/master/. Not in update dependency tools
- [x] Check and document new features 
- [ ] Update tests 

## New features 
- [ ] [Revealjs 5 release notes](https://github.com/hakimel/reveal.js/releases/tag/5.0.0)
	- [ ] 	Scroll View (https://github.com/hakimel/reveal.js/pull/3482) ([Announcement](https://slides.com/news/scroll-mode/scroll)).  Docs: https://revealjs.com/scroll-view
	- [x] The new URL query for activating the print view is ?view=print. It used to be ?print-pdf, which is still supported for backwards compatibility.
- [x] [Reveal 4.6](https://github.com/hakimel/reveal.js/releases/tag/4.6.0)
	- [x] Add the `enter-fullscreen` class to any element in your presentation to turn it into fullscreen trigger (https://github.com/hakimel/reveal.js/commit/2927be34d83bc0f0552867092272390ae951a715)
	  - It is working, and I believe nothing specific to do in Quarto for this. 
	- [x] add support for links to the id of an element nested inside slide (https://github.com/hakimel/reveal.js/pull/3444)
		- Should help solve https://github.com/quarto-dev/quarto-cli/issues/9742 and other related link issue in slides
- [x] [Reveal 4.5](https://github.com/hakimel/reveal.js/releases/tag/4.5.0)
	- [x] [Custom fragments](https://revealjs.com/fragments/#custom-fragments) (https://github.com/quarto-dev/quarto-cli/discussions/4794)  (Revealjs 4.5)
		- [ ] https://github.com/quarto-dev/quarto-cli/discussions/9643 (from 4.5)
	- [x] New Dracula theme (https://github.com/hakimel/reveal.js/pull/3324) in [4.5.0](https://github.com/hakimel/reveal.js/releases/tag/4.5.0) (https://github.com/quarto-dev/quarto-cli/discussions/4027#discussioncomment-7149980)
	- [x] [Jump To Slide](https://revealjs.com/jump-to-slide/) shortcute 
	    - https://github.com/quarto-dev/quarto-cli/pull/10998

- From 4.4 no yet integrated  or to check
	- [x] [gradient slide background](https://revealjs.com/backgrounds/#gradient-backgrounds) - in [4.4.0](https://github.com/hakimel/reveal.js/releases/tag/4.4.0) (https://github.com/quarto-dev/quarto-cli/discussions/6873)
	- [x] Multiple note support (https://github.com/hakimel/reveal.js/commit/f9ce61e34af22458c7a38bda4084513c566fcee4)
	- [x] `zoom` should not be used anymore and css transforms are prefered (https://github.com/hakimel/reveal.js/commit/e281b3234e7991283ce4dcca705dd9a6a9ebe5d2)

## Probably fix

- [x] https://github.com/quarto-dev/quarto-cli/issues/3997
- [x] https://github.com/quarto-dev/quarto-cli/issues/9699 (fixed in 4.6)

**Comment by mcanouil** [comment]
Is it worth updating to 4 while 5 just got released?

**Comment by cderv** [comment]
Probably not... I was not aware of 5 being out. Really recent... Thanks for the heads up !

**Comment by cderv** [comment]
Though this will depend on Pandoc support to be able to provide some new feature like scroll maybe 🤔 
We'll see

**Comment by ha0ye** [comment]
I am very interested in the expected timeline for this.

Also, would be interested in a basic guide to dropping in an updated version of revealjs in my quarto stack manually until such a time as an official release!

**Comment by cscheid** [comment]
> Also, would be interested in a basic guide to dropping in an updated version of revealjs in my quarto stack manually until such a time as an official release!

That's not a thing that will ever work well in Quarto, so please don't expect it.

**Comment by cderv** [comment]
NEWS: First part of the work done with dependency updated, which includes JS scripts and theme files.
