### ISSUE TITLE
code block given newline

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#48]
Using a development Quarto build (a53ce3b8937f3e222628c79a3c97856a2d09be6b).

The Markdown file:

````markdown
---
title: "code block newline"
---

``` {.dockerfile}
RUN curl -fsSL -O https://cdn.rstudio.com/r/${R_DISTRIBUTION}/pkgs/${R_INSTALLER} && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -f -y ./${R_INSTALLER} && \
    rm ${R_INSTALLER} && \
    rm -rf /var/lib/apt/lists/*
```
````

`quarto render` has the code block with an additional line of whitespace between the `RUN curl` and the `export DEBIAN...` lines.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/362187/124001472-ac163d00-d9a2-11eb-857f-6af6f485f192.png">

This may be related to #44, which documented a different consequence of long-lines in code blocks.

**Comment by aronatkins** [comment]
Observation: The additional newlines are exactly where the wrapping would be, if it were to be allowed.

Here is a Markdown document with multiple long lines having the same text in language-tagged and bare code blocks:

````markdown
---
title: "code block newline"
---

```bash
echo "this is the first long line that is bound to wrap if we let it get long enough. we cannot fail."
echo "this is the second long line that is bound to wrap if we let it get long enough. we cannot fail."
echo "this is a short line."
```

```
echo "this is the first long line that is bound to wrap if we let it get long enough. we cannot fail."
echo "this is the second long line that is bound to wrap if we let it get long enough. we cannot fail."
echo "this is a short line."
```
````

Its rendered form:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/362187/124013395-3dd87700-d9b0-11eb-8131-2b59a19e926f.png">

The bare code block has wrapping, and that wrapping coincides to where the blank lines appear in the styled output.

**Comment by jjallaire** [comment]
Interesting, this is what I see when rendering that doc:

<img width="711" alt="Screen Shot 2021-06-30 at 3 13 25 PM" src="https://user-images.githubusercontent.com/104391/124018391-cc032c00-d9b5-11eb-9c74-ac60d9997861.png">

And this for the first one:

<img width="702" alt="Screen Shot 2021-06-30 at 3 14 35 PM" src="https://user-images.githubusercontent.com/104391/124018546-f6ed8000-d9b5-11eb-920b-2c9a048ba20f.png">

Are you running the latest dev version? (I did make a fix to #44 and perhaps that resolved this as well?)

**Comment by aronatkins** [comment]
This appears to be a browser difference.

Firefox:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/362187/124028889-839e3b00-d9c2-11eb-9a45-5f088cc9989f.png">

Safari:

<img width="814" alt="image" src="https://user-images.githubusercontent.com/362187/124028914-8a2cb280-d9c2-11eb-9168-a00e4bcc0247.png">

Chrome:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/362187/124028947-96b10b00-d9c2-11eb-9b50-2f974af0ee6c.png">

**Comment by aronatkins** [comment]
I had tried to make sure that I had the fix for #44, but it's possible that I didn't have a quite-right dev environment (see https://github.com/quarto-dev/quarto-cli/pull/50). That said, I think that's sorted and I'm still seeing rendering differences (just Safari?).

**Comment by jjallaire** [comment]
okay let me check safari!

**Comment by jjallaire** [comment]
This appears to a vagary of safari's pre rendering.

I did not that if I revert the fix to #44 then we get the rendering you probably want:

<img width="645" alt="Screen Shot 2021-06-30 at 5 00 03 PM" src="https://user-images.githubusercontent.com/104391/124030886-a3366300-d9c4-11eb-939c-855e11fbad01.png">

That fix was to allow pandoc's `white-space: pre` to govern text wrapping. Previously we had used `white-space: pre-wrap`.

So the question is, which bug would you rather see fixed! I personally like `pre-wrap` because it means you never have to scroll to see source code. LMK what you think.

**Comment by aronatkins** [comment]
This is sad! I don't know which of the alternatives I prefer. Scrolling to see source has always felt suboptimal, but word-wrapping in code blocks has caused a number of problems where folks accidentally think wrapped commands are really two distinct commands. This causes problems when folks line-by-line copy command examples, for example.

#44 was trying to document that code blocks were both wrapping and scrolling, with an incorrectly bounded box around that code. The wrapping was with word-breaks, which felt less natural for code.

My original code example is a better one than the "echo" example, since it is a real code snippet.

Here it is again, rendered by Quarto:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/362187/124121944-7f663200-da43-11eb-92a4-11640c0da7c0.png">

There is a small scroll region; the `&& \` characters in the first line are outside the visible area.

Here is that same document rendered only by pandoc using its defaults:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/362187/124122060-a02e8780-da43-11eb-8506-7466594271bc.png">

Pandoc has that same "blank line" problem, so maybe this is a pandoc issue?

Here is that same document rendered with rmarkdown; we don't get a scroll region here since we don't have the same constraints:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/362187/124122151-c522fa80-da43-11eb-94ad-678cd405bdb1.png">

We do get the wrapping in rmarkdown with a narrow enough screen:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/362187/124122220-d9ff8e00-da43-11eb-822d-838f5e043a28.png">

Here are my current feelings:

* The insertion of a blank line feels incorrect.
* Wrapping feels OK, but not perfect. The writer should try to format their code examples so they avoid wrapping in "reasonably sized" bounding boxes.
* Scrolling feels OK, but not perfect. For some naturally long-lines (log text), both scrolling and wrapping feel OK; otherwise, code samples should be crafted to avoid needing to choose.

So, maybe: Pandoc bug for the blank line and your preference for wrapping vs scrolling; perhaps revisiting the breaks used when wrapping.

**Comment by aronatkins** [comment]
It appears as if adding `word-wrap: normal` to the pandoc `pre > source.code` style avoids the addition of a newline. Some related discussion is here: https://stackoverflow.com/a/56961220

**Comment by aronatkins** [comment]
````yaml
format:
    html:
        css: styles.css
````

```css
pre > code.sourceCode {
    word-wrap: normal;
}
```

**Comment by aronatkins** [comment]
I've filed https://github.com/jgm/pandoc/issues/7423, as the newlines happen with vanilla pandoc.

**Comment by aronatkins** [comment]
A data point in the scroll-vs-wrap debate (accepting still that both options are awkward): GH issue comments scroll wide code blocks. See my code block with "The quick brown fox..." in https://github.com/jgm/pandoc/issues/7423#issuecomment-872486424

**Comment by jjallaire** [comment]
The default CSS generated by pandoc uses `pre-wrap`:

<img width="666" alt="Screen Shot 2021-07-01 at 8 37 42 PM" src="https://user-images.githubusercontent.com/104391/124204090-401ffb80-daac-11eb-9d32-6a1f49ae9a97.png">

**Comment by aronatkins** [comment]
It appears as if jgm/pandoc#7423 will be resolved, which is the underlying cause of this issue. Feel free to close or use to track an update to pandoc. I'm happy using the CSS workaround for now.
