### ISSUE TITLE
Knitr cache breaks ojs_define

### ISSUE THREAD

**Issue by jimjam-slam** [quarto-dev/quarto-cli#480]
It looks like if I add `execute: cache: true` to my YAML header to use the Knitr cache, `ojs_define` stops working and my OJS cells fail.

For example, if I run a test with an R chunk and an OJS chunk, like:

```r
#| label: testin

ojs_define(test = data.frame(
  x = 1:100,
  y = rnorm(100)
))
```

```js
//| label: testout

Plot.dot(transpose(test), {x: "x", y: "y"}).plot();
```

This works great as-is, but if I add the following to my YAML header:

```yaml
execute:
  cache: true
```

And then `quarto render` and `quarto preview` the file again, I get:

![image](https://user-images.githubusercontent.com/6520659/160734132-69e17c2a-c488-4e42-86fa-f74da961fd2a.png)

**Comment by jjallaire** [comment]
Thanks for reporting this! `ojs_define()` is not cacheable so the solution _should_ be this:

````markdown
```{r}
#| label: testin
#| cache: false

ojs_define(test = data.frame(
  x = 1:100,
  y = rnorm(100)
))
```
````

However that wasn't working for me when I tried it. Just pushed this fix to make it work: https://github.com/quarto-dev/quarto-cli/commit/d923bb92181ed609bcd9f12bd323f496c555ea7e

**Comment by jimjam-slam** [comment]
Ahh, that makes sense! I hadn't realised that `ojs_define` was not cacheable. Perhaps it's appropriate to add a note to the docs, or to add a warning to the render process when it's called in a chunk that doesn't have caching turned off?

**Comment by jjallaire** [comment]
You are correct that is too easy a trap to fall into! I think it's better if we actually error with a clear message during render (vs. waiting for the more mysterious error condition downstream). I made that change here: https://github.com/quarto-dev/quarto-cli/commit/0642e1ba75d353bbaa984548f45aaccc83b3eb13. This is now what you will see as output in this case

<img width="644" alt="Screen Shot 2022-03-30 at 8 51 16 PM" src="https://user-images.githubusercontent.com/104391/160954696-2af83778-9740-4a7e-9579-e36d3502a256.png">
