### ISSUE TITLE
[VSCode] Rendering Deletes ipynb File

### ISSUE THREAD

**Issue by Servinjesus1** [quarto-dev/quarto-cli#4802]
When I render a qmd in a directory with a notebook, it overwrites and deletes the notebook. This happens both when rendering on the CLI and when using "Quarto: Render Project".

I believe this is happening during execution. Can Quarto please rely on a temporary notebook for rendering qmd files rather than potentially clobbering the existing one?

Quarto-VS v1.73.0

**Comment by mcanouil** [comment]
Also reported in:

- https://github.com/quarto-dev/quarto-cli/issues/6463
