### ISSUE TITLE
Code chunks not displaying language correctly at https://quarto.org/docs

### ISSUE THREAD

**Issue by kelly-sovacool** [quarto-dev/quarto-cli#4811]
### Bug description

There are a few places on the docs website where the code chunk language is not correct. It appears to be a random (?) string of letters instead of the actual language for the code chunk. These are the places where I've seen the problem:

- At [Authoring > Diagrams](https://quarto.org/docs/authoring/diagrams.html#overview)
  ![image](https://user-images.githubusercontent.com/17768269/224803532-008b671c-d4d7-4012-8c9f-90c5ae32726c.png)
- At [Authoring > Figures > Cross-references](https://quarto.org/docs/authoring/figures.html#cross-references)
  ![image](https://user-images.githubusercontent.com/17768269/224803822-70a31bfe-de1e-41ea-b0ed-caf7cd1d74bf.png)
 

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Fixed on `main`. Building new release now which should fix the website.
