### ISSUE TITLE
Code blocks on the website have random characters instead of language specification

### ISSUE THREAD

**Issue by jcmkk3** [quarto-dev/quarto-cli#4812]
I noticed that on the website, the area of a code block where you would normally specify a programming language has random characters instead. It seems like this is the case throughout the website. I also checked on another device just to be sure that it wasn't a weird browser issue, but I'm still seeing it.

![Screenshot 2023-03-13 12 09 53 PM](https://user-images.githubusercontent.com/45919695/224808057-3c444fb1-5fb1-4d47-9f36-3476ee227ffd.png)

**Comment by cscheid** [comment]
@jjallaire That's on me, sorry! I'm on it.

**Comment by jjallaire** [comment]
This commit looks like the culprit: https://github.com/quarto-dev/quarto-cli/commit/be1f37e89c69886927f3c8d6463acb033b80d261

**Comment by cscheid** [comment]
Fixed on `main`, firing off new release which should fix the website.
