### ISSUE TITLE
Quarto is unable to find IJulia jupyter installation automatically

### ISSUE THREAD

**Issue by DhruvaSambrani** [quarto-dev/quarto-cli#4821]
### Bug description

# Version
`1.3.264`

# Possible Issue
IJulia decided to move the location of python

# Workaround
Use `QUARTO_PYTHON=~/.julia/conda/3/x86_64/bin/python`

# OS
Linux - Arch

### Checklist

- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
That's not a bug. You need to setup your Python environment appropriately (especially since you have a custom one.)

**Comment by DhruvaSambrani** [comment]
@cscheid, as per https://github.com/quarto-dev/quarto-cli/discussions/1540#discussioncomment-3409771, Quarto has logic to search for IJulia python/jupyter environments. If this is still the case in the codebase, then it is a bug. If this feature was dropped, then could you point me towards why it was dropped? This seems like a common enough use-case, given that its even documented in the guide on the website.

Other's have also found this issue - https://github.com/quarto-dev/quarto-cli/discussions/4625

**Comment by cscheid** [comment]
Well, TIL. I apologize!! Thanks for following up.

Here's the [relevant source code](https://github.com/quarto-dev/quarto-cli/blob/main/src/core/jupyter/capabilities.ts#L76-L93). What's happening is we're looking for `python3`, and your environment is providing `python`.

I'm reluctant to use `python`, because other distributions still have `python` pointing to python 2, and that will make it more confusing.

Is Arch the only distro out there that made `python` be Python 3 or are there other ones?

**Comment by cscheid** [comment]
This should be available in our installers in a few hours. Thanks for the report!

**Comment by DhruvaSambrani** [comment]
Hi @cscheid I think versions after https://github.com/quarto-dev/quarto-cli/commit/9a8a8954ddbf7cbc90cac2e203a068dccd3edbc4 (>1.3.268) should have this fix right?

I'm on `1.3.269`, and still don't see expected behavior.

```
$ quarto check
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.269
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

Please note that `QUARTO_PYTHON=~/.julia/conda/3/x86_64/bin/python3` works. It seems like the location for the python executable was moved, rather than renamed from python3 -> python as suggested in the changelog. As per https://github.com/quarto-dev/quarto-cli/discussions/1540#discussion-4253877, it was `~/.julia/conda/3/x86_64/bin/python3`. Note the missing `x86_64` folder in the path. Also note that this may not be the case in other OS environments or Julia packs, but I suppose this does not vary for the same Julia+Conda.jl version.

**Comment by DhruvaSambrani** [comment]
I suppose https://github.com/quarto-dev/quarto-cli/blob/55bbafd66326172bd63aea6d4d681d1b771951a3/src/core/jupyter/capabilities.ts#L87 should also have `"x86_64"` in the list for it to work.

That said, is it better to recursively look for `python` exec in `~/.julia/conda/` to support both cases instead?

**Comment by cscheid** [comment]
> It seems like the location for the python executable was moved, rather than renamed from python3 -> python as suggested in the changelog

Ok. The issue is we have to be very careful with changes like this, because there's people currently depending on the _previous_ location.

> That said, is it better to recursively look for `python` exec in `~/.julia/conda/` to support both cases instead?

This might not be as safe as it seems: do we know for sure that there aren't other `python` binaries in the installations which would be picked over this new one? I _really_ don't want to break existing users. Like I said, this is already exceedingly confusing for people.

I think the only solution is to do a recursive search as a last resort, in case all the other paths fail.

**Comment by DhruvaSambrani** [comment]
Another way, which I don't like, is to completely drop auto-finding of the path, and document explicitly that python path must be set.

**Comment by cscheid** [comment]
We're not going to drop features that don't work for you but work for other users ;)

**Comment by cscheid** [comment]
I just made a push to `main`. Can you try installing quarto from github and see if that solves your problem?

```
$ git clone https://github.com/quarto-dev/quarto-cli/
$ cd quarto-cli
$ ./configure.sh
$ quarto
...
Creating Quarto Symlink
Found 1 paths to try.
> Trying /usr/local/bin/quarto
> Symlink created at /usr/local/bin/quarto
> Success
++ type -p quarto
+ quarto_loc=/usr/local/bin/quarto
+ [[ -z /usr/local/bin/quarto ]]
+ export QUARTO_DENO_EXTRA_OPTIONS=--reload
+ QUARTO_DENO_EXTRA_OPTIONS=--reload
+ quarto --version
99.9.9
```

Thanks.

**Comment by DhruvaSambrani** [comment]
https://github.com/JuliaPy/Conda.jl/pull/232 References the change in `Conda.jl` which caused the regression here. So all new users will face this issue.

Running `julia --project=@. -E "using Conda; Conda.ROOTENV"` will give the path for the parent of the `bin` dir in all Julia installations. Possible drawback is that the julia environment in which Conda is actually added can be at some other location, causing `quarto check` will become directory dependent, and I don't know how to fix THAT :P

**Comment by cscheid** [comment]
That won't work in cases where users have _old_ Conda.jl setups. Does my solution not work for you?

**Comment by DhruvaSambrani** [comment]
Going through the Conda.jl code, Conda.jl first loads `~/.julia/conda/deps.jl` which is where ROOTENV is actually set up. Even if Conda.jl is up/downgraded, it still uses the same ROOTENV. Therefore, reading `~/.julia/conda/deps.jl` and capturing the regex `const ROOTENV = \"(.*)\"` will give us the current installation location, regardless of `Conda.jl` version.

As for your solution, running `sudo ./configure.sh` and then running `/usr/local/bin/quarto` gives 

```
Check file:///home/dhruva/src/quarto-cli/src/quarto.ts

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/dhruva/src/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
Which means it isn't picking the julia installation I guess

**Comment by cscheid** [comment]
(fwiw, `sudo ./configure.sh` you shouldn't need to sudo this; we should find `~/.local` for the symlink.)

**Comment by cscheid** [comment]
My apologies, I had a dumb operator precedence bug in the check that would prevent us from finding the executable. I fixed it. Can you try again?

**Comment by DhruvaSambrani** [comment]
This works! However, please do consider looking at `~/.julia/conda/deps.jl` to find the location of the installation.
