### ISSUE TITLE
Cannot install quarto on macOS Ventura

### ISSUE THREAD

**Issue by yevgenryeznik** [quarto-dev/quarto-cli#4825]
### Bug description

I am getting an error while installing quarto on macOS Ventura 13.2.1:

_**The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance**_.

I have tried to install it by running a command in a terminal:

_sudo installer -pkg ~/Downloads/quarto-1.2.335-macos.pkg -target /Applications_.

Still getting an error:

installer: Package name is Quarto
installer: Upgrading at base path /
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while extracting files from the package “quarto-1.2.335-macos.pkg”.)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
Unfortunately, I can't reproduce this issue (just installed locally using that command on Ventura 13.2.1). You should have an error log from the installation attempt here:

`/var/log/install.log`

(This is a global installation log so would have messages from anything that you've installed, including Quarto, fyi). Could you look there to see if there are related errors or messages or if you feel comfortable, share the contents of the log file for me to take a look?

**Comment by yevgenryeznik** [comment]
This is what I have in that file.

[install.log](https://github.com/quarto-dev/quarto-cli/files/10971984/install.log)

**Comment by dragonstyle** [comment]
Hmmm. The archive is not being opened, I'm not sure why. We've had one other report of this that I can recall, and moving the archive to another location (e.g. the Desktop) and installing from there seemed to resolve the issue.  Could you give that a try?

It seems like it could possibly be related to folder permissions or perhaps could be related to something else on the system which has affected the way the Downloads folder works (e.g. is it included in Dropbox or something else unusual). But we never were able to identify a concrete problem we could solve in that case...

**Comment by yevgenryeznik** [comment]
That works! I moved the *.pkg file to the /User folder. 

Thank you very much for looking into the problem and providing a working solution!
