### ISSUE TITLE
Math symbols in Table caption

### ISSUE THREAD

**Issue by giorgiopaulon** [quarto-dev/quarto-cli#4830]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4756

<div type='discussions-op-text'>

<sup>Originally posted by **giorgiopaulon** March 10, 2023</sup>
I am interested in exporting a Quarto table to a .pdf document. The only resources I found suggest to use the following

```{r}
#| tbl-cap: !expr sprintf("A caption with some math, $\\gamma \\geq 0.5$, ($N = %s$)", nrow(iris))
head(iris) %>% 
  flextable()
```

However, this results in the following 

![Screenshot 2023-03-10 at 1 17 45 PM](https://user-images.githubusercontent.com/90702867/224406387-d5ed5b51-8223-4956-9406-196499c4784f.png)
</div>

**Comment by giorgiopaulon** [comment]
Your code still does not work for me. How can I help you reproduce it? 

I am running: 

R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.2.1

**Comment by cscheid** [comment]
Start with the checklist [here](https://github.com/quarto-dev/quarto-cli/issues/new?assignees=&labels=bug&template=bug_report.yml)

**Comment by giorgiopaulon** [comment]
````md
---
format: pdf
title: quarto-issue
---

#| tbl-cap: !expr sprintf("A caption with some math, $\\gamma \\geq 0.5$, ($N = %s$)", nrow(iris))

library(flextable)

```{r}
head(iris) |> 
  flextable()
``` 

````

<img width="730" alt="Screenshot 2023-03-14 at 6 05 23 PM" src="https://user-images.githubusercontent.com/90702867/225161819-b120f176-9a36-4ff8-9853-32b723e04b40.png">


Rstudio version: 2022.12.0+353
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.2.1

Quarto check: 

[✓] Checking Quarto installation......OK
      Version: 1.2.335
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
`Version: 1.2.335`

Great, this is it. Can you try installing one of the 1.3 prerelease versions, like https://github.com/quarto-dev/quarto-cli/releases/tag/v1.3.268?

**Comment by giorgiopaulon** [comment]
That fixed it. Thank you so much!
