### ISSUE TITLE
Fix Preview for PRs on quarto-web

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#4835]
**Use case:** It's nice to get feedback on docs/blog from people outside of the dev team (e.g. #os-dev-rel, or #quarto), but it's a big ask to have people outside the team render the docs locally to review a PR.

Related issue in quarto-dev/quarto-actions#33

**Comment by allenmanning** [comment]
@cderv It seems like you are currently looking into this, if I'm not mistaken.

**Comment by allenmanning** [comment]
It seems that we are missing some documentation around the current state.  I’m going to add that to the issue as part of this work item.  It seems like the first step is to characterize the current state then we can see if we want to fix it or take a new approach.

**Comment by cderv** [comment]
@allenmanning I have done a PR with a solution that works, and gave details there.
