### ISSUE TITLE
Lua Internals: replace standard Lua Patterns with `lpeg` grammars

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#4843]
We use Lua patterns everywhere, but pandoc ships with lpeg and (lpeg.re) specifically. We should _definitely_ switch to those.

(cc @cderv: lpeg is a great parsing engine, it turns out, and lpeg.re is a regex engine with `|` inside it :))

**Comment by allenmanning** [comment]
- [Lua Patterns](https://www.lua.org/pil/20.2.html)
- [lpeg](https://www.inf.puc-rio.br/~roberto/lpeg/) 
- [lpeg.re](http://www.inf.puc-rio.br/~roberto/lpeg/re.html)
