### ISSUE TITLE
OS-specific keyboard shortcuts fail with HTML

### ISSUE THREAD

**Issue by etiennebacher** [quarto-dev/quarto-cli#4844]
### Bug description

OS-specific keyboard shortcuts seem to fail with HTML but not PDF (using the example in the [pre-release docs](https://quarto.org/docs/prerelease/1.3/kbd.html)).

PDF:
```md
---
format: pdf
---

To print, press {{< kbd Shift-Ctrl-P >}}. To open an existing new project, press
 {{< kbd mac=Shift-Command-O win=Shift-Control-O linux=Shift-Ctrl-L >}}.
```
![image](https://user-images.githubusercontent.com/52219252/225346026-85790e9d-d08c-405d-804e-aa93bd3f25e0.png)

HTML:
```md
---
format: html
---

To print, press {{< kbd Shift-Ctrl-P >}}. To open an existing new project, press
 {{< kbd mac=Shift-Command-O win=Shift-Control-O linux=Shift-Ctrl-L >}}.
```
![image](https://user-images.githubusercontent.com/52219252/225346122-0b565f12-36bb-415a-a4ac-c783bf8be85e.png)

Note that this is also the case in the pre-release docs:

![image](https://user-images.githubusercontent.com/52219252/225347258-23d26dcd-2b14-4c8d-9c3a-a97cb76cf5c3.png)

---

RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

 Windows 10 x64 (build 19044)

```
> quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.271
      Path: C:\Users\etienne\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.2
      Path: C:/R
      LibPaths:
        - C:/Users/etienne/AppData/Local/R/win-library/4.2
        - C:/R/library
      knitr: 1.42
      rmarkdown: 2.20

[>] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Thanks for the report! I think we're doing something wrong on Windows. On macOS I see this:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/285675/225354597-49b8136d-7ca1-444d-aa5b-8b0d345127ec.png">

**Comment by cscheid** [comment]
@cderv I bet I screwed up the user agent sniffing in `src/resources/extensions/quarto/kbd/resources/kbd.js`

**Comment by cscheid** [comment]
Thanks for catching this! This was a silly mistake, and one that's annoying to test because of dynamically-generated content and OS dependence. It's fixed on `main` now.

**Comment by cderv** [comment]
😅 You did not let me time to looked at that. This was indeed the issue, I confirm it works ok on Windows now.
