### ISSUE TITLE
Confluence publishing to internally hosted confluence spaces

### ISSUE THREAD

**Issue by saptarshiguha** [quarto-dev/quarto-cli#4846]
### Bug description

Hello,
Thanks for releasing another great version of Quarto. Excited to make use of Confluence publishing. i tried the minimal example using my custom confluence hosted domain but unfortunately, 

```
quarto publish confluence qtr.qmd
? Confluence Domain: ›  https://x.y/
(\) Verifying...Sending fatal alert BadCertificate
[✓] Verifying...
ERROR: https://x.y/  doesn't exist

Error:  https://x.y/ doesn't exist
    at verifyLocationExists (file:///Applications/quarto/bin/quarto.js:110729:15)
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:56753:9)
    at async verifyWithSpinner (file:///Applications/quarto/bin/quarto.js:110707:12)
    at async verifyLocation (file:///Applications/quarto/bin/quarto.js:110720:12)
    at async Object.promptAndAuthorizeToken [as authorizeToken] (file:///Applications/quarto/bin/quarto.js:123813:5)
    at async resolveAccount (file:///Applications/quarto/bin/quarto.js:125466:21)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:125764:65)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:125802:13)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:125754:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)
 ```
    
Given i'm not the adminstrator, what can I do? I can confirm this space works since i've successfully used the Rmarkdown [confluence. plugin](https://engineering.linecorp.com/en/blog/conflr-published) (which takes domain, username, password for uploads)
    
Much appreciated
Saptarshi

Output of `quarto check`
```

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.272
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13
      Path: /opt/homebrew/opt/python@3.9/bin/python3.9
      Jupyter: 4.11.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /opt/homebrew/Cellar/r/4.2.0/lib/R
      LibPaths:
        - /opt/homebrew/lib/R/4.2/site-library
        - /opt/homebrew/Cellar/r/4.2.0/lib/R/library
      knitr: 1.39
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by allenmanning** [comment]
Thanks for reporting this.

We test that we can connect to your confluence server by making a simple fetch call from the Quarto CLI.

````
 const result: Response = await fetch(server);
````

It seems that this call is failing with a `fatal alert BadCertificate`.  We aren't doing a good job of reporting that in verbose logging so [we are going to improve that](https://github.com/quarto-dev/quarto-cli/issues/4852).  

Can you please describe more about how your Confluence provisioned?  Is it Confluence Server rather than Confluence Cloud?

**Comment by allenmanning** [comment]
You can test this by using the following simple Deno script

```typescript
const myServerURL = "https://#mydomain#.atlassian.net/";

const result = await fetch(myServerURL);
console.log(result);
```

`quarto run fetch-url.ts`

**Comment by saptarshiguha** [comment]
Hello,
This is the output (and i think it's confluence server, i'm going to assume its hosted on our servers, but can't be sure, but it doesnt go to atlassian like your example above).

```
Sending fatal alert BadCertificate
error: Uncaught (in promise) TypeError: error sending request for url (https://x.a.b.c/confluence): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
const result = await fetch(myServerURL);
               ^
    at async mainFetch (deno:ext/fetch/26_fetch.js:247:14)
    at async fetch (deno:ext/fetch/26_fetch.js:464:9)
    at async file:///Users/sguha/tmp/fetch-url.ts:3:16
```

**Comment by saptarshiguha** [comment]
Hello
Thanks for the clarification.

**Comment by fortune9** [comment]
> Unfortunately, we don't support Confluence server which I think is why it isn't working for you.
> 
> We made this decision early on in the development to only focus on Confluence Cloud as Atlassian is EoLing Confluence Server in favor of cloud.
> 
> More information on this can be found here: https://www.atlassian.com/migration/assess/journey-to-cloud.
> 
> Based on this, I'm going to close this as Won't Fix.
> 
> @cwickham It may be wise for us to include a note about this in our Confluence docs to reduce potential confusion from existing Server users.

But the same error showed up when I tried to connect the confluence pages hosted at atlassian.net cloud. Do you have any advice on this issue? Thank you.

**Comment by allenmanning** [comment]
@fortune9 Thanks for posting.

Can you please create a new issue with clear steps to reproduce following the issue template.  I look forward to continuing the discussion in that issue.
