### ISSUE TITLE
Book - Chapter crossref breaks if file contains code blocks

### ISSUE THREAD

**Issue by DhruvaSambrani** [quarto-dev/quarto-cli#4866]
### Bug description

# Example
[test.zip](https://github.com/quarto-dev/quarto-cli/files/11000206/test.zip)

# OS
Linux - Arch

# Quarto check

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.272
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /home/dhruva/.julia/conda/3/x86_64/bin/python3
      Jupyter: 5.2.0
      Kernels: julia-1.9, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by xtimbeau** [comment]
There is a different behaviour between quarto 1.2 and 1.3 when conditional div are introduced plus use of .column-screen.
The following qmd has a very large right margin in 1.3.272 and not in 1.2.
When the conditional content is commented out, every thing looks as expected. The culprit is .column-screen. I am aware that div content is only hidden, but I definitively prefer 1.2 way to deal with it.

```
---
title: problème with .column-screen
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    classoption: 
      - DIV=12
    papersize: a4
    fontsize: 10pt
---

## Introduction

blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla
blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla
blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla


:::{.content-visible when-format="HTML}
::::{.column-screen}
Hello
::::
:::
```

**Comment by cscheid** [comment]
Hi, thanks for the report and the precise repro! It's definitely a bug.

The code blocks observation was almost exactly right. Here's what's truly going on.

We've recently introduced a fix that lifts `#` headings to yaml blocks in jupyter notebooks (so that they would render more nicely when the output is .ipynb). Unfortunately, that codepath is getting triggered in book rendering, and it shouldn't. We'll fix that shortly.

**Comment by DhruvaSambrani** [comment]
A temporary work-around is to drop the space between the heading and label `{`, for example `# heading{#sec-label}`. This somehow works for the pdf output, but doesn't for html. I'm currently writing my master's thesis, and need an immediate workaround, and I assume others may also want this.

Meanwhile, is there a version which shouldn't have this bug?

**Comment by cscheid** [comment]
> need an immediate workaround

Hi, a real fix is coming in half an hour. I hope you don't mind me putting my former professor hat here, and tell you that you should consider being more conservative in your tool choices! We won't always have the time to address this sort of issue right away.

**Comment by DhruvaSambrani** [comment]
> We won't always have the time to address this sort of issue right away.

Oh no definitely! I absolutely understand that it takes time to fix things, especially with something that works with so many different tools and environments like quarto does. It took me 2 days to figure out what wasn't working in the first place (which is why I was trying out the crossrefs to parts issues). Currently the "remove the space" fix was working so I continued with it, but asked in case an older version may still have worked! Anyway, thanks for the super quick fix, I shall try it out to see if it works!
