### ISSUE TITLE
conditional div

### ISSUE THREAD

**Issue by xtimbeau** [quarto-dev/quarto-cli#4867]
### Bug description
When rendering with quarto 1.2 to pdf, the conditional div does not change anything.
In quarto 1.3.272 however right margins are way too large.
When commenting out the div part, or removing the .column-screen everything works as expected.
HMTL rendering is OK.

```
---
title: problème with .column-screen
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    classoption: 
      - DIV=12
    papersize: a4
    fontsize: 10pt
---

## Introduction

blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla
blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla
blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla


:::{.content-visible when-format="HTML}
::::{.column-screen}
Hello
::::
:::
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

A new release of Deno is available: 1.28.2 → 1.31.3 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.272
      Path: C:\Users\timbe\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.3
      Path: C:/PROGRA~1/R/R-42~1.3
      LibPaths:
        - C:/Users/timbe/RLibs/4.2.3
        - C:/Program Files/R/R-4.2.3/library
      knitr: 1.42
      rmarkdown: 2.20

[>] Checking Knitr engine render......OK

OS windows 11, Rstudio 2023.03.0 Build 386
Same problem on macos

**Comment by dragonstyle** [comment]
We'll take a look at this - it appears that we're detecting that `screen` targeted div during latex rendering even though it will not be rendered. Thanks for reporting!
