### ISSUE TITLE
plot using an ordered categorical variable does not work

### ISSUE THREAD

**Issue by Rasoul82** [quarto-dev/quarto-cli#487]
Using `seaborn` in `python` to generate a bunch of `displot`s and publishing them as html or docx, there is a bug with ordered categorical data. The published plot doesn't present the categorical data in its order. I assume this is happening as there is a conversion of the variable to string when serialising the plots for publication. Note that I put the code in a chunk in .qmd file.

I end up adding a separate function to generate the plots and save them on disk, then call them in the .qmd file.

**Comment by jjallaire** [comment]
If you could provide a minimal reproducible example of what you are seeing that would be helpful. We are using the standard Jupyter notebook client ([nbclient](https://github.com/jupyter/nbclient)) so you should in general not observe differences in output between Quarto and Jupyter Notebooks.
