### ISSUE TITLE
Provide more informative error message when chunk labels are duplicated

### ISSUE THREAD

**Issue by IndrajeetPatil** [quarto-dev/quarto-cli#4878]
### Bug description

Currently, if two chunks have the same label, the error the user gets back is not that informative.

```r
Calls: .main ... process_file -> split_file -> lapply -> FUN -> parse_block
Backtrace:
 1. global .main()
 2. execute(...)
 3. rmarkdown::render(...)
 4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
 5. knitr:::process_file(text, output)
 6. knitr:::split_file(lines = text)
 7. base::lapply(...)
 8. knitr (local) FUN(X[[i]], ...)
 9. knitr:::parse_block(g[-1], g[1], params.src, markdown_mode)
Execution halted
Error in `processx::run(quarto_bin, args, echo = TRUE)`:
! System command 'quarto' failed
---
Exit status: 1
stdout & stderr: <printed>
---
```

I actually had to change from `.qmd` to `.Rmd`, and then I got an informative error message about chunk labels being duplicated.

I observed this issue on macOS and with Quarto version `1.3.275`.

---

To reproduce this error, create `.qmd` file with two chunks that have the same label and try to render the document.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Thank you for the report.

>  [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.

Please actually include "a minimal, fully reproducible example", and not a description of one. Thank you.

**Comment by IndrajeetPatil** [comment]
Sure, here it is:

````
---
title: "My title"
output: html_document
---

```{r df}
x <- 1
```

```{r df}
x <- 2
```

````

**Comment by cscheid** [comment]
Thanks. Here's precisely why we ask.

1. You've provided an rmarkdown document, not a quarto document.
2. If you change the `output: html_document` line to `format: html`, which is what quarto expects, then you get this:

```
$ quarto render 4878.qmd


processing file: 4878.qmd
Error in parse_block(g[-1], g[1], params.src, markdown_mode) :
  Duplicate chunk label 'df', which has been used for the chunk:
x <- 1
Calls: .main ... process_file -> split_file -> lapply -> FUN -> parse_block
Execution halted
ERROR: Error
```

Note the clearer error mesage.

**Comment by IndrajeetPatil** [comment]
Oops, sorry about that! 🙈
