### ISSUE TITLE
Allow specifying canonical URL, link RSS, og:url etc

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#4882]
### Bug description

For my personal blog, these are all the options I had that are currently not present in my quarto version of the blog:

```
  <link rel="canonical" href="https://kdheepak.com/blog/{metadata.slug}" />
  <meta name="robots" content="index, follow" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="https://kdheepak.com/blog/{metadata.slug}" />
  <meta property="og:published_time" content={metadata.date} />
  <meta property="og:site_name" content={metadata.title} />
  <link rel="alternate" type="application/rss+xml" title="RSS" href="/index.xml" />
```

The `canonical` link was referenced in this discussion (https://github.com/quarto-dev/quarto-cli/discussions/3976) but I don't see how you could do it using `includes` because the url data isn't available to us as a user. Also, as far as I can tell the twitter and opengraph metadata are being added in post processing in typescript, so template partials or any other method is not available for users to add this manually. Is that correct? 

I think I would be able to write a `post-render` script to add all this but that seems unnecessary and I think Quarto should just do this for all users, OR make an option available for users to do it.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
I should note that the only things I believe we don't directly support above is `link|canonical` and `meta|robots`. Open graph and RSS feeds are both features that emit HTML metadata when configured correctly.
