### ISSUE TITLE
Mermaid doesn't work in Quarto PDF

### ISSUE THREAD

**Issue by QuintenSand** [quarto-dev/quarto-cli#4883]
### Bug description

I would like to use Mermaid diagrams in Quarto pdf. But when I run the following simple example, it returns an error. Here is some reproducible code:

```
---
format: pdf
---

```{mermaid}
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```

This is the error:

`ERROR: No inspectable targets`

So I was wondering if it is possible to use Mermaid diagrams in a Quarto pdf document? Thanks in advance!

***
I am using the following:
- RStudio/2022.12.0+353
-  running on a Mac system
***
Output of quarto check:

```
[✓] Checking Quarto installation......OK
      Version: 1.0.35
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.5 (Conda)
      Path: /Users/quinten/opt/miniconda3/bin/python
      Jupyter: 5.1.1
      Kernels: julia-1.8, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

***

Please note: I also ask a question about this on [Stackoverflow](https://stackoverflow.com/questions/75746323/mermaid-in-pdf-quarto).

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
```
[✓] Checking Quarto installation......OK
      Version: 1.0.35
      Path: /Applications/quarto/bin
```

That version is almost a year old. Can you please install one of the quarto prerelease versions? Thanks.

**Comment by QuintenSand** [comment]
After installing the latest Version: 1.3.276 of Quarto it is fixed, thanks!
