### ISSUE TITLE
Creating different custom formats with same name but different bases fails

### ISSUE THREAD

**Issue by allefeld** [quarto-dev/quarto-cli#4889]
### Bug description

I'm trying to create an extension with custom formats, as described here <https://quarto.org/docs/extensions/formats.html>. The second example on that page refers to several custom formats with the same name, `acm-pdf` and `acm-html`. Similar to that, I would like to have custom formats called `document-docx`, `document-html`, and `document-pdf`.

So I ran, in the same folder,
```
quarto create extension format:docx
quarto create extension format:html
quarto create extension format:pdf
```
answering the question for the extension name always with "document".

However, the second time I got `ERROR: The file /home/ca/Code/quarto/document/_extensions/document/_extension.yml already exists.`

It appears that I cannot create different custom formats with same name but different bases within the same folder, because the created subfolder does not contain the base name suffix.

The page mentions under "Example: Revealjs":

> Note that the format suffix (revealjs) is excluded from the directory name (this is to account for the possibility of multiple formats e.g. lexconf-revealjs, lexconf-pptx, etc.)

This seems to suggest that it should be possible to put the different custom formats even into the same *subfolder*, called "document" in my case – but I don't know how to achieve that.

- Is it indeed possible to put the different custom formats into the same subfolder?
  In that case, there would be a bug in `quarto create extension`.

- If not, wouldn't it make more sense to include the suffix in the subfolder name?
  In that case, the behaviour of  `quarto create extension` should be changed.

- Is it okay to rename the created subfolders, or do I need to wrap each of them in yet another subfolder?

`quarto check`:
```
[✓] Checking Quarto installation......OK
      Version: 1.2.335
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: /usr/bin/python3
      Jupyter: 4.9.1
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK
```
Debian GNU/Linux 11.6

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [x] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
We should probably have a better error for you in this scenario (or support creation in this way, though this is a riskier proposition since it involves modifying a file that you may have edited). 

You can add ore than one format to an extension by adding more than one format in the `format` key in the `_extension.yml`. For example, the Elsevier custom format is relatively simple and looks like:

```markdown
title: Elsevier Journal Format
author: Charles Teague
version: 0.4.2
quarto-required: ">=1.2.198"
contributes:
  formats:
    common:
      date-format: full
      filters:
        - elsevier.lua
    pdf:
      documentclass: elsarticle
      template-partials: ["partials/before-body.tex", "partials/title.tex"]
      format-resources:
        - elsarticle.cls
      cite-method: natbib
      number-sections: true
    html:
      theme: styles/elsevier.scss
```

Note that multiple formats are allowed in the `contributes > formats` keys, and that anything in the `common` key will be merged with all of the formats.
