### ISSUE TITLE
code blocks without language tags have no visible bounding box

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#49]
Using a development Quarto build (a53ce3b8937f3e222628c79a3c97856a2d09be6b).

The Markdown file:

````markdown
---
title: "commands and logs"
---

Let's celebrate Wilco, shall we?

```bash
for i in yankee hotel foxtrot ; do echo $(date) $i ; done > data.log
```

Your `data.log` file should now look like:

```
Wed Jun 30 13:01:08 EDT 2021 yankee
Wed Jun 30 13:01:08 EDT 2021 hotel
Wed Jun 30 13:01:08 EDT 2021 foxtrot
```

That's quite nice, no?
````

The `quarto render log.md` command produces HTML that does not have any sort of visible bounding box around the second code block (which has no language tag). 

<img width="701" alt="image" src="https://user-images.githubusercontent.com/362187/124002701-0ebc0880-d9a4-11eb-9faf-57e60c19eec5.png">

Compare to result produced by `rmarkdown::render("log.md")`:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/362187/124002635-fcda6580-d9a3-11eb-84b1-0a75790decfa.png">

Visually, the R Markdown version is nicer, as it marks the fixed-font region apart from the surrounding text.

I can appreciate that some fixed-font blocks won't want framing (background or border), but there doesn't appear to be a way of marking this as "program output" without giving it a language tag, which has additional baggage (syntax highlighting).

Workaround is to declare a custom highlighting syntax definition, making this look like a language when it isn't.

The modified Markdown:

````markdown
---
title: "commands and logs"
syntax-definition: log.xml
---

...

```log
Wed Jun 30 13:01:08 EDT 2021 yankee
Wed Jun 30 13:01:08 EDT 2021 hotel
Wed Jun 30 13:01:08 EDT 2021 foxtrot
```
````

The syntax definition:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="LOG Files" section="Configuration" extensions="*.log" mimetype="" version="10" kateversion="5.0" author="Jan Janssen (medhefgo@web.de)" license="LGPL">

<highlighting>
  <contexts>
    <context name="log" attribute="Normal Text" lineEndContext="#pop">
    </context>
</contexts>
</highlighting>

</language>
```

Given this,  the rendering becomes:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/362187/124004621-32804e00-d9a6-11eb-9286-4b1dca27738c.png">

**Comment by jjallaire** [comment]
We do this specifically so that we don't get a super boxy feel for the page content (too many lines). That said I agree that tastes can vary quite a bit here and we should provide some options (we'll do that). 

BTW pandoc actually has a `default` highlighting engine that just treats as plain text.

**Comment by aronatkins** [comment]
Oh, perfect. `default` works fine in our case. I didn't come across it in any of my searching, as I was looking for "log" or "text" or ... random other keywords other than "default"!
