### ISSUE TITLE
Python table and captions generated by code block

### ISSUE THREAD

**Issue by amichuda** [quarto-dev/quarto-cli#490]
I know that with kable, you can generate a table with captions from a code block.

Is the same true for python generated tables?

What about latex tables generated in python code blocks?

Thank you!

**Comment by jjallaire** [comment]
Yes, this is indeed possible! But your filing this issue revealed the fact that we currently have no docs describing how :-\

I added some docs here: https://quarto.org/docs/authoring/tables.html#computations

That will create a markdown table (which will then get turned into LaTeX by pandoc). 

If you want to generate raw latex you can use `output: asis` to ensure that whatever you print is passed straight through to Pandoc (which can handle raw latex): https://quarto.org/docs/computations/execution-options.html#raw-output

Alternatively you can use the `IPython.display.Latex` function anywhere in a code cell: https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.Latex
