### ISSUE TITLE
Support YAML file with list of files for listing contents.

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#4903]
### Bug description

In a web site project, a page with

```
---
title: "Data Visualization"
listing: 
  - id: methods
    contents: listing-contents.yml
    type: table
---

Lorem ipsum

:::{#methods}
:::
```

and `listing-contents.yml` as

```
- `awesome.md`
```

gives the error

```
Unexpected listing contents in file /tmp/quarto/gallery/data_visualization/network_visualisation/listing-contents.yml. The array may only contain listing items, not paths or other types of data.
```

But embedding the YAML into the Markdown works without problem:

```
---
title: "Network Visualization"
listing: 
  - id: methods
    contents:
      - "awesome.md"
    type: table
---

:::{.column-screen}

Lorem ipsum

:::{#methods}
:::

:::
```

The pages that I want to include in the list is in directories above the file with the listing.

# Environment

`uname -a` returns

```
Linux 5b7bffab04a5 6.2.7-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Mar 18 17:15:16 UTC 2023 x86_64 GNU/Linux
```

`quarto check` returns

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.280
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
Thanks for reporting this and the complete information!

Did you try simply providing the md directly in the listing yaml, like:

```markdown
---
title: "Data Visualization"
listing: 
  - id: methods
    contents:
      - awesome.md
    type: table
---

Lorem ipsum

:::{#methods}
:::
```

I would expect that to work, and the metadata for the item to come from the `.md`  file. Usually .yml files in listings are used when you want to provide a list of custom objects for rendering into a listing.

**Comment by rgaiacs** [comment]
[Files for reproduction](https://github.com/quarto-dev/quarto-cli/files/11112008/4903.zip)

The above zip folder provides a minimal reproductible example.

Run `quarto render .` produces

```
[1/3] post.md
[2/3] about.qmd
ERROR: Unexpected listing contents in file /tmp/4903/listing.yml. The array may only contain listing items, not paths or other types of data.

Error: Unexpected listing contents in file /tmp/4903/listing.yml. The array may only contain listing items, not paths or other types of data.
    at readContents (file:///opt/quarto/bin/quarto.js:95833:39)
    at readListings (file:///opt/quarto/bin/quarto.js:95525:44)
    at listingHtmlDependencies (file:///opt/quarto/bin/quarto.js:97118:53)
    at Object.formatExtras (file:///opt/quarto/bin/quarto.js:97645:55)
    at async runPandoc (file:///opt/quarto/bin/quarto.js:79911:63)
    at async renderPandoc (file:///opt/quarto/bin/quarto.js:80945:26)
    at async Object.onRender (file:///opt/quarto/bin/quarto.js:86569:36)
    at async renderFiles (file:///opt/quarto/bin/quarto.js:86532:25)
    at async renderProject (file:///opt/quarto/bin/quarto.js:86695:25)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:90751:32)
```

Environment information

Output of `quarto check`:

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.296
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: 5.2.0
      Kernels: python3

(-) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```

**Comment by muellerzr** [comment]
I highly recommend the docs for listings be updated with better information on this. Specifically here: https://quarto.org/docs/websites/website-listings.html#yaml-listing-content

Because what we really want to show here isn't the `href`, we want `path` instead:

```
- title: "Archived Item 1"
  author: Norah Jones
  date: 2020-01-01
  path: "archived/archived-item-thing.html"
  categories: [archived, technology]
```

**Comment by muellerzr** [comment]
Don’t have the time to do it myself but if anyone else does feel free :)

**Comment by mcanouil** [comment]
@muellerzr @cscheid I made the PR https://github.com/quarto-dev/quarto-web/pull/838
