### ISSUE TITLE
Long author name of posts loses spaces in listing page

### ISSUE THREAD

**Issue by mfherman** [quarto-dev/quarto-cli#4910]
### Bug description

When creating a website with posts and a listing page, if the author of a post as a long name, the name gets squished and loses white space between words on the listing page.

For example, this is what the listing page looks like for the two posts copied below.
![image](https://user-images.githubusercontent.com/24945757/226700854-85433e37-acf9-4ef0-8c5c-f368802f48d2.png)

<details><summary>Post 1 code</summary>

```
---
title: "Post 1"
subtitle: "The first post"
author: "An author with a long name"
---

This is a blog post written by someone with a long name.
```
</details>

<details><summary>Post 2 code</summary>

```
---
title: "Post 2"
subtitle: "The second post"
author: "Short name"
---

This is a blog post written by someone with a short name.
```
</details>

<details><summary>system details</summary>

Windows 10
RStudio 2023.03.0 Build 386

```
$ quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.280
      Path: C:\Users\mherman\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/PROGRA~1/R/R-42~1.0
      LibPaths:
        - C:/Users/mherman/r-library/4.1
        - C:/Program Files/R/R-4.2.0/library
      knitr: 1.42
      rmarkdown: 2.20

[>] Checking Knitr engine render......OK
```
</details>

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
Thanks for reporting - we have a fix on the way!
