### ISSUE TITLE
Problems rendering HTML

### ISSUE THREAD

**Issue by friosavila** [quarto-dev/quarto-cli#4918]
### Bug description

Im encountering an odd problem when rendering documents into HTML.
First a bit of background. Im using the kernel nbstata to use Stata directly with quarto and VScode.
So far I have no problems, running code, or getting outputs. However, any now and then, when I display the output straight from Stata, something odd happens.

My QMD file is as follows:

```
---
title: "Untitled"
format: 
    html: default
    ipynb: default
    pdf: default
jupyter: nbstata
---
``` 
First setup

```{stata}
clear
ssc instal jwdid
set linesize 250
set seed     111
set sortseed 111
set obs 100  // <- 100 units
gen id = _n
gen ai = rchi2(2)
// determines When would units receive treatment
gen     g = runiformint(2,10)
replace g = 0 if g>9   // never treated       
expand 10   // <-T=10
bysort id:gen t=_n 
gen event = max(0,t-g)
gen aux = runiform()*2
bysort t:gen at = aux[1] // Determines Time fixed effect
gen te = (1-g/10)+(1-event/10)  
// Treatment effect but vanishes with time
gen eit= rnormal()
gen trt  = (t>=g)*(g>0)
gen teff = te * trt 
gen y = ai + at + te * trt + eit
```

then 2 regressions

```{stata}
qui: jwdid y, ivar(i) tvar(t) gvar(g)
estat simple
```

but also

```{stata}
qui: jwdid y, ivar(i) tvar(t) gvar(g) never
estat simple
```

Everything runs correctly, but when looking at the output in HTML, i get two different behaviors.

1. Everything is fine, and produces the following:
```
------------------------------------------------------------------------------
             |            Delta-method
             | Coefficient  std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at |
   (2 vs 1)  |   1.543749   .1567784     9.85   0.000     1.236469    1.851029
------------------------------------------------------------------------------
```
2. For no reason that I can understand, it also produces the following:
```
------------------------------------------------------------------------------
             |            Delta-method
             | Coefficient  std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at |
   (2 vs 1)  |
   1.458058   .1494798     9.75   0.000     1.165083    1.751033
------------------------------------------------------------------------------
```
Notice the second line, there is a misalignment, compared to the first line.

Exploring the HTML files, the same commands and outcome produce two different things:
When things are correctly rendered
```html
<div class="cell-output cell-output-stdout">
<pre><code>------------------------------------------------------------------------------
             |            Delta-method
             | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
         _at |
   (2 vs 1)  |   1.543749   .1567784     9.85   0.000     1.236469    1.851029
------------------------------------------------------------------------------</code></pre>
</div>
```
when things are not correctly rendered

```html
<pre><code>------------------------------------------------------------------------------</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             |            Delta-method
             | Coefficient  std. err.      z    P&gt;|z|     [95% conf. interval]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>-------------+----------------------------------------------------------------
         _at |
   (2 vs 1)  |</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   1.458058   .1494798     9.75   0.000     1.165083    1.751033
------------------------------------------------------------------------------</code></pre>
```
Do you think its something to do with the kernel,? or at the rendering step?

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Thanks for the report.

Can you add `keep-ipynb: true` to your YAML, and then share the .ipynb file of both cases?

**Comment by friosavila** [comment]
Not sure if im doing this right
but, I'm sending you the ipynb file, and the qmd.
When rendering them, (only with ipynb) it produces two files. So I'm
sending you both, for each case (4 files total)
Thank you
Fernando

**Comment by cscheid** [comment]
@friosavila FYI, email attachments don't work on GitHub issues - you need to use the website to add the files (by dragging the file from your desktop onto the issue text box).

**Comment by cscheid** [comment]
Unfortuntately, I think this is a bug in the stata jupyter engine. I see a bad output on the .ipynb file inside jupyter:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/285675/226994033-7d094182-6b8d-4dbc-886f-e51c2b4d3610.png">

This is the output that their engine is producing:

````json
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "------------------------------------------------------------------------------"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "             |            Delta-method"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "             | Coefficient  std. err.      z    P>|z|     [95% conf. interval]\n",
            "-------------+----------------------------------------------------------------\n",
            "         _at |\n",
            "   (2 vs 1)  |"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "   1.458058   .1494798     9.75   0.000     1.165083    1.751033"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "------------------------------------------------------------------------------"
          ]
        }
````

Note the breaks between the different outputs. We need to respect those breaks because they're supposed to mean "here's a new output", and so we wrap each of those outputs in some scaffolding. I don't know why their behavior is not consistent across runs, but a good output instead looks like this:

````json
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "WARNING: Singleton observations not dropped; statistical significance is biased (link)"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "------------------------------------------------------------------------------\n",
            "             |            Delta-method\n",
            "             | Coefficient  std. err.      z    P>|z|     [95% conf. interval]\n",
            "-------------+----------------------------------------------------------------\n",
            "         _at |\n",
            "   (2 vs 1)  |   1.543749   .1567784     9.85   0.000     1.236469    1.851029\n",
            "------------------------------------------------------------------------------"
          ]
        }
      ],
````

If you inspect the output carefully, you'll note that there's no pattern for when their end of output implies a line break and where it doesn't, so joining the outputs will not work in general either. (note how it would put the "WARNING: Singleton observations" line in the same place as the beginning of the next table)

**Comment by cscheid** [comment]
I suspect the issue arises from the fact that we're using `nbclient` as the python library to execute the jupyter engines, and there's some difference in the way `nbclient` sets up the engines compared to jupyter.

I know this is unfortunate for your use case, because reproducing this will be nontrivial for you. But there's nothing much we can do our side (and I don't have access to stata)

**Comment by friosavila** [comment]
In case anyone is interested in, or if similar problems emerge using other languages.
I managed to fixed the problem using the following:

```{stata}
*| echo: false
*| outcome: asis
display "```"
qui: jwdid y, ivar(i) tvar(t) gvar(g)
estat simple
qui: jwdid y, ivar(i) tvar(t) gvar(g) never
estat simple
display "```"
```

Basically, I request the outcome to be deployed "asis" without modification, adding the "```" quotes directly within Stata.
This avoid the weird error I reported earlier.

HTH
F

**Comment by cscheid** [comment]
@friosavila we just added a workaround to the latest version of quarto that should fix your problem. A new release will be out shortly.

**Comment by friosavila** [comment]
Awesome! thank you!
