### ISSUE TITLE
[revealjs] Equation in speaker notes

### ISSUE THREAD

**Issue by juliantao** [quarto-dev/quarto-cli#494]
Currently, the rendering of equations in the speaker notes is problematic: they are rendered both as equations AND texts at the same time. 

```markdown
---
title: Testing equation in speaker note
format: revealjs
---

## Test equation in speaker notes

Sometimes, I want to include some equations in the speaker notes.

::: {.notes}
An equation in display
$$
E = mc^2
$$

or an in-line equation

$E=mc^2$
:::

```
Gives the following in speaker view,

![Speaker view](https://user-images.githubusercontent.com/60116296/161162174-c0704c53-eb33-4bad-834d-213709c337f8.png)

**Comment by jjallaire** [comment]
Possibly related: https://github.com/hakimel/reveal.js/issues/1726

**Comment by jjallaire** [comment]
Fixed here w/ this hack: https://github.com/quarto-dev/quarto-cli/commit/9999e2ef7b4350241cb4a1a28657889af604c1cc

Note we can remove this when we update Reveal to use MathJax 3 (this in turn pending Pandoc updating its template to make this possible)

**Comment by juliantao** [comment]
Sounds good. Thank you as always!

**Comment by juliantao** [comment]
Just tried it out. But now everything is gone, including the equations themselves.

![all gone](https://user-images.githubusercontent.com/60116296/161192243-3c6bea84-8219-4091-9dce-d7a4cc2ea491.png)
