### ISSUE TITLE
erreur lors de la compilation en pdf

### ISSUE THREAD

**Issue by GuyNYAMSI** [quarto-dev/quarto-cli#4940]
### Bug description

updating existing packages
finding package for tikzfill.image.sty

compilation failed- no matching packages
LaTeX Error: File `tikzfill.image.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Emergency stop.
<read *>

l.24 ^^M

see test.log for more information.
<img width="618" alt="code_test_renderpdf_revealjs" src="https://user-images.githubusercontent.com/39628456/227474508-820a9878-4b9f-43e9-a385-29b814d19a05.png">

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
Bonjour 👋 

Can we get more details ? Screenshot show revealjs doc but error looks like PDF rendering issue. 

Regarding PDF rendering, this type of issue 
```
LaTeX Error: File `tikzfill.image.sty' not found.
```

Usually means that there is a missing LaTeX package to install.

**Comment by GuyNYAMSI** [comment]
when I compile to pdf I get this error
<img width="671" alt="code_test_renderpdf_revealjs" src="https://user-images.githubusercontent.com/39628456/227501515-9d66ff97-f330-4ed5-a5e7-acf9759f7951.png">

**Comment by cderv** [comment]
Then this is related to what I said above. 

> Usually means that there is a missing LaTeX package to install.

Quarto should install that for you **if you are using a TeX Live** distribution like TinyTeX or usual TeX Live.  
https://quarto.org/docs/output-formats/pdf-engine.html#installing-tex

> Note that Quarto’s automatic installation of missing TeX packages will work for TinyTeX and TeX Live, but not for other TeX distributions (as it relies on TeX Live’s [tlmgr](https://www.tug.org/texlive/tlmgr.html) command).

If you are using another distribution like MikTeX, then you need to do the installation of missing LaTeX dependencies by yourself.

**Comment by GuyNYAMSI** [comment]
Merci, problème résolu !

**Comment by gustavovargas** [comment]
In case anyone has had this error. The problem is that it doesn't find `tikzfill.images`, so you need to update the `tikz` library. 

If you are using quarto, this can be easily done by using the command:
```
quarto update tinytex
```
More info, [here](https://quarto.org/docs/output-formats/pdf-engine.html)
