### ISSUE TITLE
Broken link to Fenced Echo

### ISSUE THREAD

**Issue by WillemSleegers** [quarto-dev/quarto-cli#495]
On https://quarto.org/docs/get-started/computations/rstudio.html there is a broken link to the [Fenced Echo](https://quarto.org/docs/computations/running-code.html#fenced-echo) documentation.

**Comment by jjallaire** [comment]
Thanks for reporting this! Fixed here: https://github.com/quarto-dev/quarto-web/commit/f8190c093ec3e5b5bee9ed6b00b05d02d1493cdc
