### ISSUE TITLE
xelatex not found

### ISSUE THREAD

**Issue by yoyo25** [quarto-dev/quarto-cli#4951]
### Bug description

Any help?

processing file: try.qmd
                                                                                                                        
output file: try.knit.md

pandoc 
  to: latex
  output-file: try.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  toc: true
  number-sections: true
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: My document
  colorlinks: true
  
running xelatex - 1
command xelatex not found, attempting install
finding package for xelatex
> 1 package to install
> installing xelatex (1 of 1)
ERROR: tlmgr returned a non zero status code
The system cannot find the path specified.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by yoyo25** [comment]
I am using the Rstudio to work with quarto

**Comment by cderv** [comment]
> it is possible you are on windows and updated to TeX Live 2023 

And do you know if you updated to TeX Live 2023 ? Do you know which LaTeX  distribution you have installed ? 

Can you run `tlmgr --version` in your terminal ? or `tinytex::tlmgr_version()` in R with the **tinytex** package ? 


If you are using 2023, then you'll need to update to 1.2 patch version or 1.3 Release candidate as the RStudio bundled quarto version does not work with new TeX Live (released last week). 

This is also some guess as you did not share the information about your LaTeX distribution

**Comment by yoyo25** [comment]
I don't have texlive installed I work with MikTek and used to work fine with Quarto before the last update.

tlmgr revision 66457 (2023-03-08 00:07:12 +0100)
tlmgr using installation: C:/Users/OS/AppData/Roaming/TinyTeX
TeX Live (https://tug.org/texlive) version 2023

**Comment by cderv** [comment]
> I don't have texlive installed I work with MikTek 

If you use MikTeX you need to install / update the package manually 

> tlmgr revision 66457 (2023-03-08 00:07:12 +0100)
tlmgr using installation: C:/Users/OS/AppData/Roaming/TinyTeX
TeX Live ([tug.org/texlive](https://tug.org/texlive)) version 2023


But this shows you have TinyTeX installed. So Quarto is probably using it. As I thought it got updated to 2023 version, and you are on windows. 

This means you are encountering this issue: https://github.com/quarto-dev/quarto-cli/issues/4908

it has been fixed but you need to use 1.2 patched version or new Release candidate 1.3. You can install them independent from RStudio IDE. It will not use the bundled quarto if another newer one is found on PATH.

**Comment by cderv** [comment]
@yoyo25 still an issue or can we close ? Thanks

**Comment by yoyo25** [comment]
No it’s solved. Thank you so much.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
