### ISSUE TITLE
Code annotation followed by enumerated list doesn't render the list

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#4953]
### Bug description

Here is a reprex:

````
---
format: html
---

```{r}
2 + 2         # <1>     
summary(cars) # <2>
```
1. Add 2 to 2
2. Summary of `cars` dataset

1. Followed by
2. an enumerated list about something else
````

The result is:

<img width="800" alt="Screenshot 2023-03-24 at 12 25 56 PM" src="https://user-images.githubusercontent.com/5965649/227584642-2153531a-c883-4341-b704-1e1ef8ea565e.png">

The enumerated list isn't in the output. And actually there is a warning Quarto emits:

```
WARNING: List item 3 has no corresponding annotation in the code cell
(Followed by)
WARNING: List item 4 has no corresponding annotation in the code cell
(an enumerated list about something else)
```

Adding some text in between the two enumerated lists is the only solution I found so far.

I'm using:

- Quarto 1.3.287
- RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

```
Mines-MacBook-Pro---Posit:quarto-for-academics mine$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.287
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.1
      Path: /usr/local/bin/python3
      Jupyter: 4.9.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
We took a closer look at this issue, and after looking more at the implications of treating those lists special for annotations, we think the best approach is to live with the current limitation and require that lists be separated by something other than merely whitespace.

While this isn't great, doing special handling for code annotations is likely to result in additional confusion as the behavior will be further inconsistent and it will be difficult to distinguish between truly incorrect list/annotation pairings and incorrect list/annotation pairings that arise from sequential lists.
