### ISSUE TITLE
`code-annotation-higlight-*` SASS variables not documented

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#4966]
Currently `$code-annotation-higlight-color` and `$code-annotation-higlight-bg` are not described in Quarto's documentation, either on <https://quarto.org/docs/authoring/code-annotation.html> or <https://quarto.org/docs/output-formats/html-themes.html#sass-variables>[^1].

[^1]: Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4960

**Comment by mcanouil** [comment]
Related to this (maybe not for 1.3), having some SASS variables to control the tippy box (`.tippy-box`) could b useful I guess.

```scss
$code-annotation-tippy-bg
$code-annotation-tippy-color
```

**Comment by cderv** [comment]
Thanks @mcanouil - I opened a new feature request specifically for this as this one is a documentation issue

**Comment by allenmanning** [comment]
Moving to 1.4
