### ISSUE TITLE
output is split over several cells

### ISSUE THREAD

**Issue by allefeld** [quarto-dev/quarto-cli#4968]
### Bug description

When using the [Matlab kernel](https://github.com/Calysto/matlab_kernel) in a qmd file

``````
---
jupyter: matlab
---

```{matlab}
fprintf('First line\n')
fprintf('Second line\n')
fprintf('Third line ')
fprintf('in two parts\n')
```
``````

it appears in Quarto's HTML output as

![image](https://user-images.githubusercontent.com/1738353/227738522-f0be05da-eb85-4f1d-bba0-c4f42b3a976e.png)

though it should be like in Matlab itself:

![image](https://user-images.githubusercontent.com/1738353/227739222-4f1525c0-269c-43ba-bf22-b7f653f46f06.png)

The reason is that in the intermediate notebook, there are separate output cells:

``````
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6a87d088",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "First line\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Second line\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Third line "
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "in two parts\n"
     ]
    }
   ],
   "source": [
    "fprintf('First line\\n')\n",
    "fprintf('Second line\\n')\n",
    "fprintf('Third line ')\n",
    "fprintf('in two parts\\n')"
   ]
  }
``````

If I have a code cell with the same contents in a regular Jupyter notebook, everything is fine:

![image](https://user-images.githubusercontent.com/1738353/227738717-686c1071-b6ab-475d-9c6a-2ae189a0814a.png)

The underlying code is

``````
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "First line\n",
      "Second line\n",
      "Third line in two parts\n"
     ]
    }
   ],
   "source": [
    "fprintf('First line\\n')\n",
    "fprintf('Second line\\n')\n",
    "fprintf('Third line ')\n",
    "fprintf('in two parts\\n')"
   ]
  },
``````

***

My system:
Debian GNU/Linux 11.6, kernel 5.10.0-21-amd64
MATLAB 9.13.0.2166757 (R2022b) Update 4

`quarto check`:

````

[✓] Checking Quarto installation......OK
      Version: 1.2.335
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.5 (Conda)
      Path: /home/ca/.conda/envs/std/bin/python
      Jupyter: 4.10.0
      Kernels: python3, matlab, matlab_connect

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.0.4
      Path: /usr/lib/R
      LibPaths:
        - /home/ca/.local/lib/R
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.11

[✓] Checking Knitr engine render......OK
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [x] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
We can't control this behavior, unfortunately (we can't assume that different outputs are supposed to be concatenated or not). We've recently [seen a similar behavior with the `stata` jupyter engine](https://github.com/quarto-dev/quarto-cli/issues/4918). Quarto executes the .ipynb files through `nbclient`, so maybe that's a place to track this down?

Unfortunately, I don't have access to matlab (or stata), so I can't help on this.

**Comment by allefeld** [comment]
Thanks for the comment. I don't understand much of the workings of Jupyter, so could you please give me a few pointers how to track this down? What should I look at? For example, I can't even find `nbclient`...

What I don't understand is, if Quarto uses Jupyter, then why does the executed notebook (left by `keep-ipynb: true` vs saved by Juypter notebook) look different? Does Quarto pass any options to Jupyter which might be different from those used under the Jupyter notebook interface?

**Comment by cscheid** [comment]
> What I don't understand is, if Quarto uses Jupyter, then why does the executed notebook (left by keep-ipynb: true vs saved by Juypter notebook) look different?

The difference is precisely that we use `nbclient` to execute the notebook. nbclient is this: https://github.com/jupyter/nbclient a jupyter client library to execute notebooks.

**Comment by MHellmund** [comment]
I have the same problem with Julia code cells and I also meet  https://github.com/quarto-dev/quarto-cli/issues/3093 from time to time. 

Furthermore, IJulia produces different output cells for (a) `print()/println()` to `stdout` and (b) showing the result of the last line of a code cell using `display()`, which may or may not be what you want in your quatro document.

So I wrote a pandoc-lua filter which merges consecutive output cells. This is all very  unfinished  and only tested with my own narrow kind of Quarto use. If you like, have a look at the function ` blockMerge()` here:  https://gitea.math.uni-leipzig.de/hellmund/julia-color/src/branch/main/_extensions/julia/ansi2htmltex.lua

**Comment by cderv** [comment]
> I have the same problem with Julia code cells

@MHellmund Could you share a document using Julia and that has the issue of split cells ? That would help as I think we had until now example with Stata and Matlab kernel. With Julia kernel, it should be easier to reproduce on our side. 

Thanks !

**Comment by MHellmund** [comment]
A simple multiline output triggers sometimes  https://github.com/quarto-dev/quarto-cli/issues/3093 for me. E.g.

```{julia}
for x ∈ (42, 12.0, 3.3e4, "Hallo!", true, 1+2im)
    println("x = ", x, " ..... type: ", typeof(x))
end
```
produces sometimes one output cell and sometimes the output is splitted in two cells. It looks like a real heisenbug to me. 

The following **is** reproducible for me under Linux: 
```{julia}
for x ∈ (42, 12.0, 3.3e4, "Hallo!", true, 1+2im)
    println("x = ", x, " ..... type: ", typeof(x))
    flush(stdout)
end
```
produces one output cell in Jupyter and six consecutive output cells in Quarto., which seems wrong to me.

**Comment by cscheid** [comment]
@MHellmund Thank you, that's very helpful. I can now repro this locally!

I'm pretty sure this is an `nbclient` bug. Here's a repro:

### `nbclient_test.py`

```python
#!/usr/bin/env python3

import nbformat
import sys
from nbclient import NotebookClient
import atexit

notebook_filename = sys.argv[1]
nb = nbformat.read(notebook_filename, as_version=4)
client = NotebookClient(nb, timeout=600, kernel_name='julia-1.8')

# client.execute()

client.create_kernel_manager()
client.start_new_kernel()
client.start_new_kernel_client()
atexit.register(client._cleanup_kernel)

for index, cell in enumerate(client.nb.cells):
  if cell.cell_type == 'code':
    cell = client.execute_cell(
        cell = cell,
        cell_index = index)
    client.nb.cells[index] = cell
nbformat.write(client.nb, sys.argv[2])
```

### `issue-4968.qmd`

```
---
format: html
title: issue-4968
---

```{julia}
for x ∈ (42, 12.0, 3.3e4, "Hallo!", true, 1+2im)
    println("x = ", x, " ..... type: ", typeof(x))
    flush(stdout)
end
```
````

```
$ quarto convert issue-4968.qmd
$ ./nbclient_test.py issue-4968.ipynb issue-4968-nbclientout.ipynb
$ cat issue-4968-nbclientout.ipynb
{
 "cells": [
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "---\n",
    "format: html\n",
    "title: issue-4968\n",
    "keep-ipynb: true\n",
    "keep-md: true\n",
    "---"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-03-30T08:37:03.142000Z",
     "iopub.status.busy": "2023-03-30T08:37:02.875000Z",
     "iopub.status.idle": "2023-03-30T08:37:03.606000Z",
     "shell.execute_reply": "2023-03-30T08:37:03.582000Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "x = 42 ..... type: Int64"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "x = 12.0 ..... type: Float64\n"
     ]
    },
...
```

Compare this to the executed output of issue-4968.ipynb from inside `jupyter lab`:

```
$ cat issue-4968.ipynb
{
 "cells": [
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "---\n",
    "format: html\n",
    "title: issue-4968\n",
    "keep-ipynb: true\n",
    "keep-md: true\n",
    "---"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "x = 42 ..... type: Int64\n",
      "x = 12.0 ..... type: Float64\n",
      "x = 33000.0 ..... type: Float64\n",
      "x = Hallo! ..... type: String\n",
      "x = true ..... type: Bool\n",
      "x = 1 + 2im ..... type: Complex{Int64}\n"
     ]
    }
   ],
...
```

**Comment by cscheid** [comment]
In the meantime, I think we should add a jupyter fixup that merges all consecutive cells that are `name: stdout` and `output_type: stream`.

**Comment by cscheid** [comment]
@MHellmund Thanks! I'll update the upstream issue report (in the meantime, I have a fix for quarto incoming)
