### ISSUE TITLE
I am unable install latex with tinytex due to a bug.  Can Anyone Help? 

### ISSUE THREAD

**Issue by lbui30** [quarto-dev/quarto-cli#4972]
### Bug description

I am having trouble rendering my quarto documents as pdfs similar to issue #4951 .  I am unable to install tinytex due to an error.   Such weird errors I am not sure if I am even able to properly uninstall.   All I can tell there seems to be a folder missing called "win32". 
 
I am worried about both install and uninstall because I get errors with both. 

Can anyone help me install or check my uninstall?  

### Technical Specifications  

**OS Version** Windows 10 
**OS Distribution**  Windows 10 Home 21H2 Build 19044.2728
**OS "Experience Version":** Windows Feature Experience Pack 120.2212.4190.0
**Rstudio Build version:**  RStudio 2022.07.2 Build 576
**Tinytex package version:** 0.44

**Processor:** AMD Ryzen 9 5900X 12-Core Processor 3.70 GHz
**RAM:** 64 Gb
**Windows and Application Disk:** C:/ with 200 Gb
**Primary Document Disk and Large Applications Disk:**  D:/ with 3 Tb 

### Install Error
I the primary error seems to be this OS error 3 error.  I have looked in the folder where it is installed and have not found it listed

```
Microsoft Windows [Version 10.0.19044.2728]
(c) Microsoft Corporation. All rights reserved.

C:\Users\secret\Documents>quarto install tool tinytex
Installing tinytex
[>] Downloading TinyTex v2023.03.21
[>] Unzipping TinyTeX-v2023.03.21.zip
[>] Moving files
[>] Verifying tlgpg support
ERROR: Error executing 'C:\Users\secret\AppData\Roaming\TinyTeX\bin\win32\tlmgr.bat': 
The system cannot find the path specified. (os error 3)
```

There is a windows folder but there is no win32 folder.   The file its looking for seems to be under a "windows" folder....

![image](https://user-images.githubusercontent.com/55963851/227753489-0f1d2b27-a08d-444e-9b77-8c186305f9b7.png)

### Output and Error when I try to detect my version of tinytex
I get this error when I try to detect my tlmgr.  Tinytex does detect something, but its like something is missing....
```
C:\Users\secret\Documents>tlmgr --version
'tlmgr' is not recognized as an internal or external command,
operable program or batch file.
```
```
tinytex::tlmgr_version()
tlmgr revision 66457 (2023-03-08 00:07:12 +0100)
tlmgr using installation: C:/Users/OS/AppData/Roaming/TinyTeX
TeX Live (https://tug.org/texlive) version 2023
```

### Uninstall error
I am still not sure if I did this correctly, as the uninstallation produces errors too.  

```
tinytex::uninstall_tinytex()
tlmgr.pl: no auxiliary texmf trees defined, so nothing removed
tlmgr.pl: action conf returned an error; continuing.
tlmgr.pl: An error has occurred. See above messages. Exiting.
```

### Test Quarto Document
I am not sure how to upload a qmd would be even helpful as this is an installation bug.  I did at least test to see if thing were working good enough and this is the error I got. 

```
---
title: "test"
format: pdf
editor: visual
---
Quarto

Quarto enables you to weave together content and executable code into a finished document. 
To learn more about Quarto see https://quarto.org.
Running Code
When you click the Render button a document will be generated that includes both content 
and the output of embedded code. You can embed code like this:
{r}
1 + 1
You can add options to executable code like this
{r}
#| echo: false
2 * 2
The echo: false option disables the printing of code (only output is displayed).
```
### Error when I run the template quarto document shown here

This is the render I receive constantly when trying to render the above test .qmd

```
processing file: test2.qmd
  |..............                                                        |  20%
  ordinary text without R code

  |............................                                          |  40%
label: unnamed-chunk-1
  |..........................................                            |  60%
  ordinary text without R code

  |........................................................              |  80%
label: unnamed-chunk-2 (with options) 
List of 1
 $ echo: logi FALSE

  |......................................................................| 100%
  ordinary text without R code

output file: test2.knit.md

pandoc 
  to: latex
  output-file: test2.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: test
  editor: visual
  
running xelatex - 1

No TeX installation was detected.

Please run 'quarto install tool tinytex' to install TinyTex.
If you prefer, you may install TexLive or another TeX distribution.
```

P.S. I have tried MikeTex on many computer is the past and been very frustrated trying to install or get it even to work.  So I would like to avoid manual install of MikeTex as much as humanly possible because I am worried I will mess it up. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
Do you have an username with spaces and/or accents?

**Comment by cscheid** [comment]
The issue here is you need to update your quarto version. TeXLive changed their windows paths on their latest updates to a backwards-incompatible location. Unfortunately there's nothing we can do on this besides have everyone update their installations.

(Notice that you didn't produce the output of `quarto check` on your issue. We ask that question so that we can actually inspect the output. Please do read the checkbox text before clicking them!, thank you)

Given you mentioned `win32`, I'm pretty sure that's the issue so I'm going to go ahead and close this one.

**Comment by lbui30** [comment]
> The issue here is you need to update your quarto version. TeXLive changed their windows paths on their latest updates to a backwards-incompatible location. Unfortunately there's nothing we can do on this besides have everyone update their installations.
> 
> (Notice that you didn't produce the output of `quarto check` on your issue. We ask that question so that we can actually inspect the output. Please do read the checkbox text before clicking them!, thank you)
> 
> Given you mentioned `win32`, I'm pretty sure that's the issue so I'm going to go ahead and close this one.

Below is my quarto output.  @cscheid before you close can you tell me how to update my quarto since I use Rstudio? I am really not good with computers.

```
C:\Users\secret\Documents>quarto check
[>] Checking Quarto installation......OK
      Version: 1.1.189
      Path: C:\Program Files\RStudio\bin\quarto\bin
      CodePage: 1252
[>] Checking basic markdown render....OK
[>] Checking Python 3 installation....(None)
      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/
[>] Checking R installation...........OK
      Version: 4.2.2
      Path: C:/Users/secret/Documents/R/R-4.2.2
      LibPaths:
        - C:/Users/secret/Documents/R/R-4.2.2/library
      rmarkdown: 2.18
[>] Checking Knitr engine render......OK
```

> Do you have an username with spaces and/or accents?

Nope its a letters, but I will get in super big uber trouble if I share my username outside the fire department as an account that one of the one's gives access to other accounts for people to see almost everyone's medical records.   So neither the username nor password can be shared.

**Comment by lbui30** [comment]
Also thank you for the help

**Comment by dragonstyle** [comment]
You can download the latest Release Candidate (v1.3) or the latest patch release of Quarto 1.2 here:

https://quarto.org/docs/get-started/

RStudio will automatically detect the installed version of Quarto and use that.

HTH!

**Comment by mcanouil** [comment]
> Nope its a letters, but I will get in super big uber trouble if I share my username outside the fire department its an account that can grants temporary medical access to other accounts for people to see almost everyone's medical records. So neither the username nor password can be shared.

@lbui30 Note that I did not ask for you to share the username because it was pretty obvious it was hidden for a reason.
I know that Windows does a really bad job as dealing with non-ascii characters in path thus in username. Anyway, here the issue was indeed related to path resolution but not because of non-ascii characters.
