### ISSUE TITLE
Content "jumps" from a page with a toc on the right compared to a page without a toc

### ISSUE THREAD

**Issue by jakobschumacher** [quarto-dev/quarto-cli#498]
Quarto is great! I dont like that the content "jumps" or "shifts" between two pages if there is a  toc (the one usually on the right that says "on this page" and one page that doesnt have a toc. So when you click yourself through a book really fast, the content jumps from left to right and vice versa.

**Comment by dragonstyle** [comment]
Thanks for reporting this - I see the same thing and will take a look!

**Comment by dragonstyle** [comment]
This should be fixed here:

f0895f84e72f8bcaf32644f3bf675e4c831173cb

A fresh release should be ready in 10 minutes or so!
