### ISSUE TITLE
No preview image on contained folder

### ISSUE THREAD

**Issue by richardsprague** [quarto-dev/quarto-cli#4999]
### Bug description

My listing grid lays each item correctly for the following directory, but the preview image doesn't display.

As expected (and consistent with the behavior in 1.2) a directory like this one generates a website that shows each of the rendered .md and .qmd files contained within `/grid`.  The preview images also display, except for the one associated with the .md file contained in a subdirectory (`/grid/diet/`).

```sh
grid
├── diet
│   ├── 2017-02-02-clabbered-milk.md
│   └── diet-assets
│       └── clabberedMilk.jpg
├── famous_deaths.qmd
├── gridpost.qmd
├── microbiome-assets
│   └── coverPersonalScience-quarto.jpg
└── psm.qmd
```

Output:
![image](https://user-images.githubusercontent.com/2120747/228355703-e477e9a5-efbe-4cc6-bf12-2c020ff74851.png)
I expected to see the preview image contained in the 'clabbered milk' file.

Reproducible example in this repo [richardsprague/quartosample: extrapage](https://github.com/richardsprague/quartosample/tree/extrapage)

(Maybe related to [#4998: Preview images are distorted](https://github.com/quarto-dev/quarto-cli/issues/4998))
Using 1.3.290 on OSX 13.2.1

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
Thanks for reporting this - are all the files pushed to that linked repo (thanks for including that, it should make tracking this down a lot easier!)? I couldn't seem to find the md/qmd that was generating that problematic grid entry - can you point me in the right direction?

**Comment by richardsprague** [comment]
Oops! Sorry, try again!

**Comment by dragonstyle** [comment]
Thank you!

Hmmm... I'm testing using the very latest version and am seeing the preview image. Two questions

- Are you using Windows? We have definitely seen path issues specific to windows, so perhaps this would explain why I'm not seeing it.
- If you are not on Windows, could you give it a try using our very latest pre-release? This should have the fix for the image scaling issue + might be resolving this (though I am not aware of a specific change to address this)

**Comment by allenmanning** [comment]
No longer an issue.
