### ISSUE TITLE
Mac Quick Look support for .qmd files

### ISSUE THREAD

**Issue by mattwarkentin** [quarto-dev/quarto-cli#500]
Hi,

Loving Quarto so far. This is all very exciting.

This suggested feature is more of a "quality of life" feature, but it would be great to have Quick Look support on Macs for `.qmd` files. I love being able to quick look (press space bar for a file preview) at other plain-text files like R and Python scripts. it would be great to have support for `.qmd`. Possibly with syntax highlighting options.

Tools like https://github.com/sbarex/SourceCodeSyntaxHighlight go the next step to provide syntax highlighting in quick looks. Anyway, maybe this is outside the scope of Quarto. If so, please feel free to close this issue.

**Comment by jjallaire** [comment]
There's enough to this that I don't think we'll do it in the short term (but I agree it would be great to have!). I wonder if the shortest path to this might be giving the SourceCodeSyntaxHighlight folks a PR to support `.qmd` files (highlighted as markdown)

**Comment by mattwarkentin** [comment]
I'm on it!

https://github.com/sbarex/QLMarkdown/issues/104

**Comment by jjallaire** [comment]
Fantastic!!!!
