### ISSUE TITLE
quarto RC 1.3.290 breaks revealjs {.panel-tabset} tbl- cross reference on code that ran fine on previous stable release

### ISSUE THREAD

**Issue by JeffreyRacine** [quarto-dev/quarto-cli#5001]
### Bug description

Greetings,

I just tried updating from 1.2475 to RC 1.3.290 and this RC breaks code that previously ran. I am running RStudio Version 2023.03.0+386 (2023.03.0+386) on macOS, R version 4.2.3 (2023-03-15)

Here is a minimal case... the warning message is

WARNING: Unable to resolve crossref @tbl-a
WARNING: Unable to resolve crossref @tbl-b

But this runs fine reinstalling the previous stable release (1.2.475)

Thanks for your incredible efforts and contributions to the community. I scanned and didn't see this reported, if it has kindly accept my apologies.

Jeff

    ---
    title: "Untitled"
    format: revealjs
    ---
    
    ## Issue
    
    ::: {.panel-tabset}
    ## A
    
    @tbl-a
    
    ```{r}
    #| label: tbl-a
    #| tbl-cap: a
    knitr::kable(table(rbinom(100,2,.5)))
    ```
    
    ## B
    
    @tbl-b
    
    ```{r}
    #| label: tbl-b
    #| tbl-cap: b
    knitr::kable(table(rbinom(100,2,.5)))
    ```
    :::
    
    ## Not Issue - Below continues to work fine
    
    ### C
    
    @tbl-c
    
    ```{r}
    #| label: tbl-c
    #| tbl-cap: c
    knitr::kable(table(rbinom(100,2,.5)))
    ```
    
[issue.pdf](https://github.com/quarto-dev/quarto-cli/files/11094065/issue.pdf)

    quarto check
    
    [✓] Checking versions of quarto binary dependencies...
          Pandoc version 3.1.1: OK
          Dart Sass version 1.55.0: OK
    [✓] Checking versions of quarto dependencies......OK
    [✓] Checking Quarto installation......OK
          Version: 1.3.290
          Path: /Applications/quarto/bin
    
    [✓] Checking basic markdown render....OK
    
    [✓] Checking Python 3 installation....OK
          Version: 3.8.2
          Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
          Jupyter: (None)
    
          Jupyter is not available in this Python installation.
          Install with python3 -m pip install jupyter
    
    [✓] Checking R installation...........OK
          Version: 4.2.3
          Path: /Library/Frameworks/R.framework/Resources
          LibPaths:
            - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
          knitr: 1.42
          rmarkdown: 2.21
    
    [✓] Checking Knitr engine render......OK

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Thank you for the report and the precise reprex! It's definitely a bug, I can reproduce it locally. Fix incoming soon.

**Comment by allenmanning** [comment]
https://github.com/quarto-dev/quarto-cli/pull/5009
