### ISSUE TITLE
No in-line code execution for R

### ISSUE THREAD

**Issue by richardsprague** [quarto-dev/quarto-cli#5007]
### Bug description

```yaml
---
format: html
---

I am `r 5+25` years old.

```
output is

![image](https://user-images.githubusercontent.com/2120747/228377287-a0de8c90-66e9-465d-8ab5-f1390dc83617.png)

```sh
 quarto check knitr

(/) Checking R installation...........loading Sprague .Rprofile
[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.41
      rmarkdown: 2.19

[✓] Checking Knitr engine render......OK
```
quarto version 1.3.294
I'm on Mac OSX 13.2.1

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
When using only inline chunk (no other computation code chunk), you need to specify the engine you want to use by providing 
```yaml
engine: knitr
```
in your document

When no `engine` field is provided, there is a autobinding feature as described in https://quarto.org/docs/computations/execution-options.html#engine-binding

Auto binding works based on which code chunk is in the document. 

Hope it helps

**Comment by cscheid** [comment]
To be clear, this is an intentional change in our behavior from 1.2. It comes from the fact that we no longer want to auto-bind the knitr engine when Python documents use, for example `r * 2`.

We apologize for the temporary confusion, but the autobinding in this case was causing a large range of problems!

**Comment by allenmanning** [comment]
As Designed
