### ISSUE TITLE
A more general review of our patterns to see if we have more instances of `[]`

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#5015]
This is a follow-up issue for the discussion here:

> Should we do a more general review of our patterns to see if we have more instances of `[]` doing unexpected things?

_Originally posted by @cscheid in https://github.com/quarto-dev/quarto-cli/pull/4993#pullrequestreview-1361351276_

**Comment by dragonstyle** [comment]
Carlos and I did a review of this during the code review (both that specific pattern and the more general usage of `[` and `[` in Lua files / patterns.

**Comment by cderv** [comment]
I also looked into this with a quick search in VSCODE, and did not found anything else suspicious.
