### ISSUE TITLE
Option out-width not working with Julia if no r code is included

### ISSUE THREAD

**Issue by gdietl** [quarto-dev/quarto-cli#5034]
### Bug description

I am working on a quarto book and included some julia chunk like

```
\```{julia}
#| out-width: 80%
JULIA CODE
\```
```

If the document contains no R code, i.e., Jupyter is used to generate the figures, the size of the figure is 100% instead of 80%. However, if I insert some R code such that knitr is used to compile the Julia code, the size is correctly set to 80%

**Comment by allenmanning** [comment]
@cderv Thanks for your comment.  It isn't clear to me what the bug is here based on the discussion.  Can you please provide some reproducible steps or close if it isn't an issue.

**Comment by cderv** [comment]
@gdietl In chunk option for Jupyter can be followed in #3155 - I'll close this one following my explanation above. 

If there is anything more to it, please reopen thanks !
