### ISSUE TITLE
[Revealjs] Allow customisation of callouts similar as in HTML 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#5038]
From discussion in https://github.com/quarto-dev/quarto-cli/discussions/4755

* `html` format support some variables for callout (https://quarto.org/docs/output-formats/html-themes.html#callouts) 
* This is because it is part of bootstrap SCSS file that we compile (
* For revealjs, this is just a `<style>` node that [we insert in header](https://github.com/quarto-dev/quarto-cli/blob/242276f1af2bce3a93560c55d7087cf98fafec6c/src/format/reveal/format-reveal.ts#L282-L284) of document (https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/html/styles-callout.html)

We should make that part of the default theme for revealjs, so that it is compile as a SASS theme, and variables can also be used (see https://github.com/quarto-dev/quarto-cli/discussions/4755#discussioncomment-5476737 by @EllaKaye)

**Comment by EllaKaye** [comment]
This would be excellent, thank you!

**Comment by sasja-san** [comment]
The callout blocks in my current project (right side) looks kinda bad. Will this change make it so they adopt the color/style of the "Card" elements seen to the left?

If not - is there some way to make a custom div which acts like a `.callout-X` but which renders to a Card?

![callout-blocks-slate-look-bad](https://github.com/user-attachments/assets/37d31bce-5fef-4ea8-9d3b-e07c34c709fd)

**Comment by mcanouil** [comment]
@sasja-san what does your comment have to do with Reveal.js?
