### ISSUE TITLE
Provide a bibliography partial so fixing `biblatex-apa` issues doesn't require a template-wide changes

### ISSUE THREAD

**Issue by netique** [quarto-dev/quarto-cli#5058]
### Bug description

If I use biblatex with APA citation style and use a language for which biblatex-apa doesn't have a special definition, I get some errors about undefined control sequences. Check the following MWE (`.bib `file content does not matter as soon as it contains the "citation", entry):

````md
---
format:
  pdf:
    lang: cs-CZ
    cite-method: biblatex
    biblio-style: apa
    bibliography: refs.bib
---

[@citation]
````
results in

```
compilation failed- Error compiling latex
Undefined control sequence.
<argument> \datecircaprint \mkbibdateapalongextra 
                                                  {labelyear}{labelyeardivis...
l.167 \autocite{citation}
```

Note that this is all because `biblatex-apa` doesn't have any `czech-apa` format. It's easy to solve using

```latex
\DeclareLanguageMapping{czech}{american-apa}
```

Now I get to the point of my issue – **there is no way how to include the line above at the correct place in the `.tex` document without replacing the whole `template.tex`.** It has to be placed after `babel` and `biblatex`, so I cannot use `include-in-header`, it has to be in the preamble, so `before-body` isn't an option either.

I think the solution may be to create a new template partial wrapping around this bibliography setup that would be easier to replace, benefiting from the template's other components getting updated along with quarto.

<details><summary>Versions</summary>
RStudio 2023.05.0-daily+165
macOS Ventura 13.3

quarto check:
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.299
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /Users/netik/.julia/conda/3/bin/python3
      Jupyter: 5.3.0
      Kernels: julia-1.8, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources
      LibPaths:
        - /Users/netik/Documents/git/diplomka/renv/library/R-4.2/aarch64-apple-darwin20
        - /Users/netik/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.2/aarch64-apple-darwin20/fd29d0b8
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
</details>

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
Not a good long term solution as the name is not helpful but a possible current workaround would be to leverage the `tilte.tex` partials. Did you see this [LaTeX partials](https://quarto.org/docs/journals/templates.html#latex-partials) ? 

This is a partial you can replace and that will be the last things put before `\begin{document}`
https://github.com/quarto-dev/quarto-cli/blob/45f6955378250e8288a79cd176c2dce92b279d2b/src/resources/formats/pdf/pandoc/template.tex#L346-L348

It is the last things in preamble. Content is quite simple, and you could copy and add to it. 
See file https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/pdf/pandoc/title.tex

That is not the perfect solution, but could be helpful to not modify the whole template but just this partial. Adding a new partials is still a better idea.

Hope it helps.

**Comment by netique** [comment]
Thanks, makes sense! If I set `biblio-config: false` and initialize `biblatex` on my own with the "language mapping" line added in the title partial, then it works. I can imagine that the "partialization" of pandoc's LaTeX template can be challenging. I believe this bibliography issue is an edge case, so I'm pretty fine with this solution.

**Comment by cderv** [comment]
Glad it works for you that way ! 

> I can imagine that the "partialization" of pandoc's LaTeX template can be challenging. I believe this bibliography issue is an edge case, so I'm pretty fine with this solution.

@dragonstyle I let you decide if this is worth adding a new partial at this place in the template. Probably not for next release 1.4 as I don't think we'll work on template tweaking for next release.

**Comment by dragonstyle** [comment]
I think anothe approach for us to consider would be to directly enable setting bib latex language mappings (pandoc/quarto already has a number of biblatex specific options, so perhaps we should just also support something like that here). I'll leave this target for 1.4 for the time being so we can consider it.
