### ISSUE TITLE
When using `latex-auto-mk: false` files under `format-resources`don't get copied to execution directory

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#5078]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4888

<div type='discussions-op-text'>

<sup>Originally posted by **kernie** March 19, 2023</sup>
Hi!

I have defined a section
```
format-resources:
        - resources/fonts/Eurostile.ttf
        - resources/formats/pdf/eforms.sty
```
in the `pdf`area and with `latex-auto-mk: true` these get copied into the execution dir.

However, I want to establish an own compilation chain and use external latexmk... When I set this to `latex-auto-mk: false` it starts rendering but complains:
```
Error producing PDF.
! LaTeX Error: File `eforms.sty' not found.
```

Can somebody enlighten me, what I'm doing wrong? How can I get more debug output?

Thank you!</div>

**Comment by kernie** [comment]
Hi,
thanks for coming back to this.

I prepared a MWE of the issue: [test_book.zip](https://github.com/quarto-dev/quarto-cli/files/11150295/test_book.zip)

**Comment by kernie** [comment]
Hi,

I want to use the latex glossaries package, this needs to run makeglossaries which is a customised makeindex command.

I asked here about it: https://github.com/quarto-dev/quarto-cli/discussions/4872

Thanks

04.04.2023 21:31:24 Charles Teague ***@***.***>:

**Comment by dragonstyle** [comment]
Makes sense - we'll also put it on the radar to potentially add either direct glossaries support or to at least try to make out pipeline more amenable to this type of addition... Ideally it wouldn't require opting out of our pipeline!

**Comment by cderv** [comment]
> glossaries support

About this, just creating some reference links as this is an issue we've heard already 
* https://github.com/quarto-dev/quarto-cli/issues/1697
* https://github.com/quarto-dev/quarto-cli/discussions/1763
* https://github.com/quarto-dev/quarto-cli/discussions/4872 (that was linked above already)
