### ISSUE TITLE
`quarto render --execute` doesn't run embedded Jupyter cells

### ISSUE THREAD

**Issue by nebfield** [quarto-dev/quarto-cli#5081]
### Bug description

Hello,

Thanks for making quarto, it's super cool 😄 

If I embed a Jupyter cell as described here:

https://quarto.org/docs/authoring/notebook-embed.html

in a small document `test.qmd`:

```
---
title: Exploration of penguin characteristics
author: Norah Jones
toc: true
format:
  html:
    code-fold: true
---

# Embedded report

{{< embed penguins.ipynb  >}}
```

and render the document with:

```
$ quarto render test.qmd --to html --execute --no-cache -o test.html
```

The code in the embedded Jupyter notebook isn't evaluated. 

This isn't what I expect with the `--execute` flag. Instead, to update the Jupyter cell content dynamically I have to run:

```
$ jupyter nbconvert --to notebook --inplace --execute penguins.ipynb
$ quarto render test.qmd --to html --execute --no-cache -o test.html
```

I'm not sure if this is expected behaviour, but it took me a little while to figure out.

Thanks!

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?

N/A

- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

maxOS 13.3

- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.296
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.5
      Path: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.39
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
From the doc I believe it is by design (https://quarto.org/docs/authoring/notebook-embed.html)

> You can include the **output** of an external Jupyter notebook in a Quarto document with the embed shortcode.

@dragonstyle can you confirm about the `embed` feature ?

**Comment by dragonstyle** [comment]
Exactly correct @cderv - the `--execute` flag controls the execution of the parent / root notebook rather than the behavior of notebooks from which embeds are taken.

**Comment by nebfield** [comment]
Cool! Thanks for the quick response 😄
