### ISSUE TITLE
`resource-path` not working as expected in HTML document

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#5084]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5080

<div type='discussions-op-text'>

<sup>Originally posted by **sje30** April  4, 2023</sup>
I'm trying to use --resource-path to point to a different folder for where I store images.

With the following simple example:

````
---
title: "test 1"
resource-path: ["/tmp"]
format:
  html:
    embed-resources: true
---
# Generate a plot

```{r}
png(file="/tmp/temp.png")
plot(1:10)
dev.off()
```


# show the plot v1

![alt text](/tmp/temp.png "tooltip")

# show the plot v2

![alt text](temp.png "tooltip")
````

when I render in quarto, v1 of the plot appears, but not v2.

    quarto render temp.qmd

However, if I run pandoc from the command line, it works (as in the plot appears twice):

    pandoc --resource-path='/tmp' --self-contained -s -o temp.html temp.qmd

what am I missing?

Thanks, Stephen

```
pandoc v 3.1.1
quarto  v 1.2.475
running on Mac
```</div>

**Comment by cderv** [comment]
FWIW I have a fix for this - I'll make a PR to discuss

**Comment by sje30** [comment]
Thank you for investigating this so promptly.

For a bit of context: I'm investigating how to replicate the functionality of what you get in latex.  i.e. \includegraphics{} will search for a file using kpsewhich functionality, which allows me as a user to include images without using the full path.  This works today in quarto when exporting from quarto to pdf via tex, as it should do.  

Having the ability for similar functionality in html modes would be great, hence my discussion issue.  It would also be great if it would work irrrespective of embedding the file in a standalone html.
