### ISSUE TITLE
link-citations bug?

### ISSUE THREAD

**Issue by noahmf** [quarto-dev/quarto-cli#5088]
### Bug description

When I implement "loud" citations, e.g., "... Berry (2021) ...", **only the year is hyperlinked, not the name(s)**.  Is this intentional?  Seems odd.

PDF format.  I have "link-citations: true" in my yaml header.  Default citation method.  Have tried changing document class etc.

RStudio version 2023.03.0+386.  macOS Ventura 13.3

Quarto check:

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.302
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK

Thanks

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by noahmf** [comment]
It does not appear to be possible according to your documentation.  The examples shown, e.g., in the [second table](https://quarto.org/docs/authoring/footnotes-and-citations.html) (" ... Knuth (1984) ..."), demonstrate the behavior I am describing.  ("1984" is hyperlinked, "Knuth" is not.)  I have tried using an external ".csl" file and different options for the "cite-method: " yaml argument.

**Comment by cscheid** [comment]
the `csl:` option should be what you need. Can you share the full example you've tried and didn't work for you?

**Comment by cscheid** [comment]
I'm going to go ahead and close this one since I haven't heard back from you. If you provide us with the example that uses an external CSL file and doesn't work, we'll be happy to take another look at it.
