### ISSUE TITLE
Nonstandard image URL won't render (PDF)

### ISSUE THREAD

**Issue by richardsprague** [quarto-dev/quarto-cli#5089]
### Bug description

I'm trying to render this page as PDF. 
```qmd
---
title: Non-standard URL
---


![](https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F9b7345d9-5f62-46dc-8062-d704c2c014a5_289x174.jpeg)
```

Breaks with this error:

```
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages

compilation failed- error
Unable to load picture or PDF file 'badurl_files/mediabag/https://bucket.jpeg'.
<to be read again> 
                   }
l.159 ...adurl_files/mediabag/https://bucket.jpeg}
```

Quarto version 1.3.306
OSX 13.3

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by richardsprague** [comment]
btw, this still fails in 1.3.309.

Try on this URL:
https://substackcdn.com/image/fetch/w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%253A%252F%252Fsubstack-post-media.s3.amazonaws.com%252Fpublic%252Fimages%252Fced5d5ad-a0d6-44aa-b6f5-73c0a937d016_3553x5273.jpeg

**Comment by richardsprague** [comment]
Ugh, on 1.3.310 now I get a different error: with this URL:

https://substackcdn.com/image/fetch/w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%253A%252F%252Fsubstack-post-media.s3.amazonaws.com%252Fpublic%252Fimages%252Fced5d5ad-a0d6-44aa-b6f5-73c0a937d016_3553x5273.jpeg

`LaTeX Error: Cannot determine size of graphic in index_files/mediabag/ced5d5ad-a0d6-44aa-b.webp (no BoundingBox)`

**Comment by cscheid** [comment]
@richardsprague if substack is emitting a webp file (instead of a jpeg or png) there's not much we can do.

**Comment by richardsprague** [comment]
But that URL points to a legitimate jpeg.  I don't know how quarto thinks it's a webp...

Since this was closed, I filed a different bug #5113 with more details.

**Comment by cscheid** [comment]
@richardsprague it's not a jpeg:

```
$ curl -LO https://substackcdn.com/image/fetch/w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%253A%252F%252Fsubstack-post-media.s3.amazonaws.com%252Fpublic%252Fimages%252Fced5d5ad-a0d6-44aa-b6f5-73c0a937d016_3553x5273.jpeg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  131k  100  131k    0     0   593k      0 --:--:-- --:--:-- --:--:--  602k
$ file https%253A%252F%252Fsubstack-post-media.s3.amazonaws.com%252Fpublic%252Fimages%252Fced5d5ad-a0d6-44aa-b6f5-73c0a937d016_3553x5273.jpeg
https%253A%252F%252Fsubstack-post-media.s3.amazonaws.com%252Fpublic%252Fimages%252Fced5d5ad-a0d6-44aa-b6f5-73c0a937d016_3553x5273.jpeg: RIFF (little-endian) data, Web/P image
```

**Comment by richardsprague** [comment]
darn it, you're right.  Bummer.
