### ISSUE TITLE
Quarto Preview: Access Denied

### ISSUE THREAD

**Issue by arthurgailes** [quarto-dev/quarto-cli#5104]
### Bug description

Hello,

I receive the following error during quarto preview of a website build:
`ERROR: PermissionDenied: Access is denied. (os error 5), stat 'NETWORK\PATH\quarto_site_error\_site'`

To trigger the error, all of the following have had to be true.

* Previewing a website.
* Directory is on a network drive (which I am not the administrator of)
* The qmd file has any script rendering a leaflet or mapview map (likely caused by htmlwidgets)

Happens in either RStudio or VScode. Rendering works fine; only affects the preview. Using Windows. 

Full reproduction here: https://github.com/arthurgailes/repro_quarto_preview_error

quarto.yml:
```
project:
  type: website
```

Quarto check:
      Version: 1.2.269
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

Thank you for your help.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by arthurgailes** [comment]
Error log:

```
Browse at http://localhost:5030/test/test.html
ERROR: PermissionDenied: Access is denied. (os error 5), stat 'W:\arthur\misc\one_off\2023\quarto_site_error\_site'

PermissionDenied: Access is denied. (os error 5), stat 'W:\arthur\misc\one_off\2023\quarto_site_error\_site'
    at Object.lstatSync (deno:runtime/js/30_fs.js:223:21)
    at ensureDirSync (file:///C:/Program%20Files/Quarto/bin/quarto.js:6562:31)
    at renderProject (file:///C:/Program%20Files/Quarto/bin/quarto.js:78835:9)
GET: /test/test.html
ERROR: 500 (Internal Error): Access is denied. (os error 5), stat 'W:/arthur/misc/one_off/2023/quarto_site_error/_site/favicon.ico'
```

**Comment by MethodenKompetenzZentrum-TUC** [comment]
I have get the same Error Code, when I try to setup a new quarto blog via Rstudio


R-4.3.2
RStudio-2023.09.1-494
Quarto 1.3.450
Windows10 Enterprise Version 10.0.10240 Build 10240
I freshly installed R, RStudio and Quarto and changed nothing in the configurations. When I try to setup a simple quarto blog in Rstudio (new Project -> quarto blog) and then press the render button, I get the error:

> ERROR: PermissionDenied: Zugriff verweigert (os error 5), stat 'D:\Arbeit\ooo\index_files

I run Rstudio as administrator and checked the security settings of the directory (tried other folders, partitions and even an other PC)

Searched the internet but I found no solutions. Hopefully somebody has an idea

Thanks in advance

**Comment by mcanouil** [comment]
Could you try to follow previous request:
- https://github.com/quarto-dev/quarto-cli/issues/5104#issuecomment-1508884021
- Could you, if possible, try with the 1.4 pre-release?

**Comment by MethodenKompetenzZentrum-TUC** [comment]
> Could you try to follow previous request:
> 
> * [Quarto Preview: Access Denied #5104 (comment)](https://github.com/quarto-dev/quarto-cli/issues/5104#issuecomment-1508884021)
> * Could you, if possible, try with the 1.4 pre-release?


Ok, I used the 1.4 pre-release, same error:

> $ quarto render index.qmd
> ERROR: PermissionDenied: Zugriff verweigert (os error 5), stat 'D:\Arbeit\ooo\index_files'
> 
> PermissionDenied: Zugriff verweigert (os error 5), stat 'D:\Arbeit\ooo\index_files'
>     at Object.statSync (deno:runtime/js/30_fs.js:322:9)
>     at createWalkEntrySync (file:///C:/Program%20Files/Quarto/bin/quarto.js:2754:23)
>     at walkSync (file:///C:/Program%20Files/Quarto/bin/quarto.js:2793:15)
>     at walkSync.next (<anonymous>)
>     at walkSync (file:///C:/Program%20Files/Quarto/bin/quarto.js:2814:20)
>     at walkSync.next (<anonymous>)
>     at advanceMatch (file:///C:/Program%20Files/Quarto/bin/quarto.js:2901:20)
>     at advanceMatch.next (<anonymous>)
>     at expandGlobSync (file:///C:/Program%20Files/Quarto/bin/quarto.js:2916:24)
>     at expandGlobSync.next (<anonymous>)
>

**Comment by cderv** [comment]
@MethodenKompetenzZentrum-TUC do you have writing access to `D:\Arbeit\ooo` ?

**Comment by MethodenKompetenzZentrum-TUC** [comment]
Yes, I have. When start a new project, then a new directory is created (in this case 'ooo') including the default files like index.qmd etc.
I checked the security options for this directory and my profil aswell as the admin profil have all rights for it

**Comment by mcanouil** [comment]
Is your "D" drive local?

**Comment by cderv** [comment]
> Yes, I have. When start a new project, then a new directory is created (in this case 'ooo') including the default files like index.qmd etc. I checked the security options for this directory and my profil aswell as the admin profil have all rights for it

Then it seems it could come from a conflict access problem. On windows, access can be denied if another process is locking the file. Could be a Network drive sync tools or maybe a malware virus scanner, or other process. 

Hard to reproduce and debug ... 🤔

**Comment by MethodenKompetenzZentrum-TUC** [comment]
Yes D: is local. I also tried C:, same error.
I don't use a third party anti virus software on this machine and I have no network drives. 
I also tried it on an other PC, but got the same result.

**Comment by MethodenKompetenzZentrum-TUC** [comment]
> Hard to reproduce and debug
I know, thank you anyway for your help. 

I tried to kill all background processes in Windows that are not needed, but still no change

**Comment by cderv** [comment]
@cscheid @dragonstyle any ideas what could cause this behavior  ?

**Comment by dragonstyle** [comment]
I don't have a great one that you haven't already covered - e.g. inspecting the folder that is causing the error for unusual permissions or configurations or being suspicious of things like file synchronization utilities... Sorry :(

**Comment by cscheid** [comment]
The only one I can think of is that Quarto might have been installed in a directory without write permissions, and that somehow we're inheriting those permissions when copying the files. We had a bug like that in the past, but we fixed it. So it's also possible that @MethodenKompetenzZentrum-TUC needs to install a new version of Quarto.

**Comment by mcanouil** [comment]
@MethodenKompetenzZentrum-TUC Did you try to fully remove and clean any previous Quarto installation, restart, then install the latest Quarto version?

**Comment by serrulate** [comment]
This is also an issue for me i  am trying to create Quarto documents on a machine i do not have admin rights to.  i do have full access to the Appdata/Local/Programs/Quarto/Bin folder 
i have tried re-installing rstudio and also tried creating a quarto document in VS Code but receive the same  Error executing 'reg': Access is denied. (os error 5). i am able to knit markdown documents with out issue. i just have never been able to render quarto documents.

**Comment by cderv** [comment]
@serrulate thanks a lot for your report. 

Can you give us more detail on your environment, version used, sharing the exact error you get, also activating trace (https://quarto.org/docs/troubleshooting/) ? 

We need as much detail as possible. As noted in previous comment, we can't repro yet, and don't have enough details to allow us to investigate and understand. 

Thank you

**Comment by serrulate** [comment]
here is my output when i ran the quarto check, the errors in the quarto.js files displayed below are also what appears when i try to render a sample quarto document. 


Test.User@PHX-111 MINGW64 ~/Desktop/Brain2/R/quatro1/test2
$ quarto check
Quarto 1.4.539
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.539
      Path: C:\Users\Test.User\AppData\Local\Programs\Quarto\bin
      CodePage: unknown

error: Uncaught (in promise) Error: Error executing 'reg': Access is denied. (os error 5)
        throw new Error(`Error executing '${options.cmd[0]}': ${e.message}`);
              ^
    at execProcess (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:5295:15)
    at registryReadString (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:26513:27)
    at registryReadString (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:26498:31)
    at cacheCodePage (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:39487:29)
    at readCodePage (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:39520:13)
    at checkInstall (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:98441:30)
    at check (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:98384:19)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Command.fn (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:98667:5)
    at async Command.execute (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:8102:13)

**Comment by serrulate** [comment]
Yes, perhaps i am not in the correct forum for finding a solution to this issue, as its not a quarto bug. I'm grasping for straws as i have been unable to use quarto on a computer where i do not have admin rights to and forsee this lack of admin rights continuing for the foreseeable future.  i can use markdown fine and i have full access to the AppData folders indicated in the file paths.

**Comment by cderv** [comment]
I have moved your feedback to another issue to discuss. We at least need to make the error message better. Let's continue there

**Comment by huangde** [comment]
with quarto version 1.4.554, I get the same permission deny error when running "quarto render" to a web project. It happens on both the network and local drive. my latter debugging shows if I used the **live server plug in in vscode** to preview the generated html pages once, it locks the _site folder, even when it is closed.  Closing the whole vscode help solve this problem.
 
I guess it is somehow related to this issue.

**Comment by cscheid** [comment]
We need a reprex in order to be able to go on. We don't have one, so I'm closing. Please feel free to reopen should you have a reproducible example. Thanks!

**Comment by cderv** [comment]
> @arthurgailes @MethodenKompetenzZentrum-TUC Do you still have issues ?
> 
> We don't have much to investigate and any further details helping use reproduce would help ! Thanks

@arthurgailes the last message we shared was this one above from December 2023 (https://github.com/quarto-dev/quarto-cli/issues/5104#issuecomment-1858065074) asking for more information, and if issue still happened. It has no answer since. 

Our issue board triaging process include closing old issues with no more activities, especially those we miss some information to act on it on our own. This is what the https://github.com/quarto-dev/quarto-cli/labels/needs-repro label is about. 

Providing a fully minimal and running reprex is not the only thing that can be provided to help. This is best case scenario to have one, but indeed not all can have one. What is sure is that those type of issues are hard to investigate for us and to fix if we have not enough information. So as much as we can get is necessary so that we can try reproduce the issue; Without being able to reproduce on our side, this is very hard to do something about it. 

So usually there is two cases :
- Either we have all the information so that we can try reproduce (which would take time to setup an environment with the information shared anyway)
- Either we help to investigate on the non-reproducible environment, but this involves some time from the user with the problem and a lot of back and forth to try identify what is happening. 

I hope this helps understand our process and the reason behind the closing. We are more than happy to reopen if this is still an issue that reproduce on your side with latest Quarto version. And if that is the case, we need more information about the environment, and how this can be triggered (project example, environment information, ...) 

Thanks !
