### ISSUE TITLE
How to see the chunk label by `#| label` on the outline?

### ISSUE THREAD

**Issue by Doubt-0KB** [quarto-dev/quarto-cli#511]
When I make a long report, I want to see some chunks quickly.
In R Markdown, I check the outline that is a function of RStudio, check the chunk label and click it (like the figure below).
But in Quarto, when I set the chunk label by `#| label:` in the chunk, I can't see the label on the outline.
Is there any way to display the label on the outline?

![Example](https://user-images.githubusercontent.com/98461207/161414238-6a076b83-6e4f-4d03-ba7a-b38ea4b122c2.png)

**Comment by jjallaire** [comment]
You are correct that this doesn't work as you expect today -- we are hoping to fix this in the next release of RStudio (you can track this work here: https://github.com/rstudio/rstudio/issues/10473)
