### ISSUE TITLE
codefilename not shown anymore for md output

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#5112]
````markdown
---
title: foo
format: commonmark
keep-md: true
---

```{.python filename="matplotlib.py"}
import matplotlib.pyplot as plt
plt.plot([1,23,2,4])
plt.show()
```
````

This outputs with latest 1.3
````markdown
# foo

``` python
import matplotlib.pyplot as plt
plt.plot([1,23,2,4])
plt.show()
```
````

but it outputs with latest 1.2 release
````markdown
foo
================

<div class="code-with-filename">

**matplotlib.py**

``` python
import matplotlib.pyplot as plt
plt.plot([1,23,2,4])
plt.show()
```

</div>

````

It was lost in https://github.com/quarto-dev/quarto-cli/pull/4118/files#diff-3c9439f2bc27c905f44644b44dee252c2d2729b5da73484cbfc22e814137f98d while introducing `DecoratedCodeBlock` I believe. 

@cscheid is it a regression on purpose ? Or could we port back the old behavior ? 

Previously we did 
````lua
    return pandoc.Div(
      { pandoc.Plain{pandoc.Strong{pandoc.Str(filename)}}, el:clone() },
      pandoc.Attr("", {"code-with-filename"})
    )
````
for non HTML format  and now we just return the content of the code block
https://github.com/quarto-dev/quarto-cli/blob/37ce04581238dc036985fcdab20534aaf78732de/src/resources/filters/customnodes/decoratedcodeblock.lua#L106-L109

(from a discussion in https://github.com/quarto-dev/quarto-cli/issues/5101)

**Comment by cscheid** [comment]
It's not on purpose.

**Comment by cderv** [comment]
Ok good to know. I was going to make the PR but wasn't sure.  I let you handle it then

**Comment by cscheid** [comment]
It would be great if you wanted to make the PR! The main thing is that we need DecoratedCodeBlock to handle more than just filenames (I created it to solve an HTML render ordering issue). Happy to help you if you want to make the fix.

**Comment by cscheid** [comment]
Thanks for catching this. I got confused between the listings support (which involves crossrefs) and filename support (which doesn't). I have a fix incoming.
