### ISSUE TITLE
Dynamic date via R not honored in book project

### ISSUE THREAD

**Issue by bryanhanson** [quarto-dev/quarto-cli#5114]
### Bug description

I created the default book project via the CLI, using `quarto create-project mybook --type book`, then changed the `_quarto.yml` date entry from the default hard-wired date to ` date: "`r Sys.Date()`"` and when rendered/previewed, the date is reported as "Invalid Date".  This works fine for a website, so I'm wondering if this is a bug or intentional (due to an underlying belief about how a book should "work").

Setting `engine: knitr` does not change anything.

On macOS 12.6.4; `quarto check` gives:

```
^C~/Desktop/mybook> quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/bryanhanson/Documents/Professional/Research/R_Pkgs/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
In general, we'd prefer you avoid using expressions to synthesize dates in this way. If possible you could use `now` which should give you the same result. 

> In addition to writing a standard date, you may also use a few special keywords which will generate a date for you. `today` will provide the current date with the current time set to 0, `now` will provide the current date and time, and `last-modified` will provide the file modification date and time of the input document itself.

Would this work for you?

**Comment by bryanhanson** [comment]
Certainly, thanks!  A habit I brought over from markdown documents I think.
