### ISSUE TITLE
Appendix table with inline code fails to render with values

### ISSUE THREAD

**Issue by mverouden** [quarto-dev/quarto-cli#5121]
### Bug description

When adding a table with inline code in an appendix, the inline code is shown instead of the values.

### Minimal Example
In **RStudio 2023.03.0 Build 386** I have created a Quarto Book named "Minimal Example", and added the following table at the end of the `intro.qmd` file:
```
## Table

| $n$ | $k$ | $\pi =$ 0.05 | 0.10 | 0.15 | 0.20 | 0.25 | 0.30 | 0.35 | 0.40 | 0.45 | 0.50 |
|--:|--:|-------------:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|
| 1 | 0 | 0.9500 | 0.9000 | 0.8500 | 0.8000 | 0.7500 | 0.7000 | 0.6500 | 0.6000 | 0.5500 | 0.5000 |
| 1 | 1 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 |
| | | | | | | | | | | | |
| 2 | 0 | `r round(pbinom(q = 0, size = 2, prob = 0.05), digits = 4)` | 0.8100 | `r round(pbinom(q = 0, size = 2, prob = 0.15), digits = 4)` | 0.6400 | `r round(pbinom(q = 0, size = 2, prob = 0.25), digits = 4)` | 0.4900 | `r round(pbinom(q = 0, size = 2, prob = 0.35), digits = 4)` | 0.3600 | `r round(pbinom(q = 0, size = 2, prob = 0.45), digits = 4)` | 0.2500 |
| 2 | 1 | `r round(pbinom(q = 1, size = 2, prob = 0.05), digits = 4)` | 0.9900 | `r round(pbinom(q = 1, size = 2, prob = 0.15), digits = 4)` | 0.9600 | `r round(pbinom(q = 1, size = 2, prob = 0.25), digits = 4)` | 0.9100 | `r round(pbinom(q = 1, size = 2, prob = 0.35), digits = 4)` | 0.8400 | `r round(pbinom(q = 1, size = 2, prob = 0.45), digits = 4)` | 0.7500 |
| 2 | 2 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 |
| | | | | | | | | | | | |
```

I have also created a file named `appendix-table.qmd` with the following content:
```
# The Binomial Distribution

$P(y \leq k)$ for $y \sim \mbox{Bin}(n, \pi)$.
Please note that these tables provide cumulative probabilities.

| $n$ | $k$ | $\pi =$ 0.05 | 0.10 | 0.15 | 0.20 | 0.25 | 0.30 | 0.35 | 0.40 | 0.45 | 0.50 |
|--:|--:|-------------:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|
| 1 | 0 | 0.9500 | 0.9000 | 0.8500 | 0.8000 | 0.7500 | 0.7000 | 0.6500 | 0.6000 | 0.5500 | 0.5000 |
| 1 | 1 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 |
| | | | | | | | | | | | |
| 2 | 0 | `r round(pbinom(q = 0, size = 2, prob = 0.05), digits = 4)` | 0.8100 | `r round(pbinom(q = 0, size = 2, prob = 0.15), digits = 4)` | 0.6400 | `r round(pbinom(q = 0, size = 2, prob = 0.25), digits = 4)` | 0.4900 | `r round(pbinom(q = 0, size = 2, prob = 0.35), digits = 4)` | 0.3600 | `r round(pbinom(q = 0, size = 2, prob = 0.45), digits = 4)` | 0.2500 |
| 2 | 1 | `r round(pbinom(q = 1, size = 2, prob = 0.05), digits = 4)` | 0.9900 | `r round(pbinom(q = 1, size = 2, prob = 0.15), digits = 4)` | 0.9600 | `r round(pbinom(q = 1, size = 2, prob = 0.25), digits = 4)` | 0.9100 | `r round(pbinom(q = 1, size = 2, prob = 0.35), digits = 4)` | 0.8400 | `r round(pbinom(q = 1, size = 2, prob = 0.45), digits = 4)` | 0.7500 |
| 2 | 2 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 |
| | | | | | | | | | | | |
```
When rendering the `_quarto.yml` file:
```
project:
  type: book

book:
  title: "Minimal example"
  author: "Norah Jones"
  date: "4/7/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - appendix-table.qmd

bibliography: references.bib
```
with  the command  `quarto render --to pdf` in the console, the first table in the intro is created as expected. However, the same table in the appendix displays the inline code instead of the values. 

**I expected to see the same table as in the intro.**

 I updated on April 7, 2023 to quarto version 1.3.310 and the appendix table was working in my previous version (quarto version 1.2.475). In the end I went back to quarto version 1.2.475, to be able to create my book with the intended table in the appendix. 

In my humble opinion it is a bit premature to put the candidate release as default download on https://quarto.org/docs/get-started/ and suggest to leave the default on the current release.

### Output from `cat /etc/os-release`
```
username@machinename:~$ cat /etc/os-release
NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal
```
### quarto check output
```
username@machinename:~$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.310
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: 4.10.0
      Kernels: julia-1.8, python3, ir

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /usr/lib/R
      LibPaths:
        - /home/username/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Are you only using inline code and no code chunks? In 1.3, you have to declare it as `engine: knitr` in the front matter. You'll correctly note that this is breaks backwards compatibility. But unfortunately it's necessary because of issues with different engines.

**Comment by mverouden** [comment]
In my book I am using code chunks as well. However, in the appendix there is a huge table with a lot of inline R code. This table renders well as long as it is not in an appendix.

The RC release notes do mention it, which I have seen. However, I can not find in the documentation, where to specify `engine: knitr` to resolve the backwards compatibility.

**Comment by cscheid** [comment]
Can you share a full reproducible example, not just the snippet that you think is causing it? In this case, that would be the entire book project.

**Comment by mverouden** [comment]
I have created a repo. You will find my example on [https://github.com/mverouden/mat14303-lecture-notes](https://github.com/mverouden/mat14303-lecture-notes)

**Comment by cscheid** [comment]
I think you didn't add `cover/cover.png` to your project.

But I see that none of your .qmd files have front matter; try adding

````
---
engine: knitr
---
````

to appendix-binonmial-tables.qmd

**Comment by cscheid** [comment]
This is described in our documentation here: https://quarto.org/docs/computations/execution-options.html#engine-binding
