### ISSUE TITLE
Flextable doesn't work in book format

### ISSUE THREAD

**Issue by jonpeake** [quarto-dev/quarto-cli#5126]
### Bug description

When I render a book project to PDF with a flextable printed, I get the following error:

```
compilation failed- error
Undefined control sequence.
<argument> \Oldarrayrulewidth 
                              
l.260 ...ngth{\Oldarrayrulewidth}{\arrayrulewidth}
```

It produces this error on this minimal example in a newly created Quarto book project (showing just index.qmd):
````
# Preface {.unnumbered}

This is a Quarto book.

To learn more about Quarto books visit <https://quarto.org/docs/books>.

```{r}
library(flextable)
```

df <- data.frame(c(1:3),c(4:6))

flextable(df)
````
(and the _quarto.yml:)
```
project:
  type: book

book:
  title: "flextable_book_test"
  author: "Norah Jones"
  date: "4/7/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
```

If I render a PDF outside of a book project (even with an scrreprt document class), it works perfectly fine. Any ideas what could be causing it to only throw this error in the book project?

I'm running RStudio 2023.03.0, Build 386, with Quarto version 1.3.310:
```
C:\Users\jonathan.peake\OneDrive - Florida Fish and Wildlife Conservation\Documents\FIM Data Projects\flextable_book_test>quarto check
A new release of Deno is available: 1.28.2 → 1.32.3 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.310
      Path: C:\Users\jonathan.peake\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.7
      Path: C:/Users/jonathan.peake/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 4.11.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/jonathan.peake/Documents/R
        - C:/Program Files/R/R-4.2.1/library
      knitr: 1.42
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
I believe this is a current issue with flextable, see the comments in #5093.

**Comment by jonpeake** [comment]
Why would it work in a non-book quarto format though?

**Comment by cderv** [comment]
Yes this is an issue with current (newest) version of **flextable** - it will be solved once https://github.com/davidgohel/flextable/pull/533 is merged. You can downgrade flextable or build from the PR if you need a workaround.
