### ISSUE TITLE
Compilation failed when rendering to PDF with Graphviz diagrams in Quarto 1.3

### ISSUE THREAD

**Issue by marklhc** [quarto-dev/quarto-cli#5128]
### Bug description

Hi,

I'm trying out quarto 1.3.313, and noted an error when trying to render a qmd file with a graphviz diagram to PDF. Here's an example:

````md
---
title: "PDF Test"
format: pdf
---

```{dot}
graph G {
  layout=neato
  run -- intr;
  intr -- runbl;
  runbl -- run;
  run -- kernel;
  kernel -- zombie;
  kernel -- sleep;
  kernel -- runmem;
  sleep -- swap;
  swap -- runswap;
  runswap -- new;
  runswap -- runmem;
  new -- runmem;
  sleep -- runmem;
}
```

````

The error I got with xelatex is:

```
compilation failed- error
Unable to load picture or PDF file 'undefined.pdf'.
<to be read again> 
                   }
l.160 ...[width=5.5in,height=3.5in]{undefined.pdf}
```

In the output .tex file, the relevant lines are

```
\begin{figure}[H]

{\centering \includegraphics[width=5.5in,height=3.5in]{undefined.pdf}

}

\end{figure}
```

The file is rendered with no problem in quarto 1.2.475. Do you have any idea why this happens? I'm using Pandoc 3.1.2, with Ubuntu 22.04.

Here is my RStudio version:

RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

And `quarto check` output:

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.313
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.7.6 (Conda)
      Path: /home/markl/.julia/conda/3/bin/python3
      Jupyter: 4.6.1
      Kernels: python3, julia-1.7

(-) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Strange, I can't reproduce this on my side. Compiling your qmd file gives me the following relevant lines in the .tex file:

```
\begin{figure}[H]

{\centering \includegraphics[width=5.5in,height=3.5in]{5128_files/figure-latex/dot-figure-1.png}

}

\end{figure}
```

**Comment by cscheid** [comment]
I don't know exactly why you'd get an undefined result from this call (rather than an actual error), but the only thing I can imagine is happening is this:

Our detection of Google Chrome/Chromium and use of the Chrome Desktop Protocol is going badly on your setup. If the code fails, we should be getting an exception (and I think we aren't). If somehow we don't get an exception but CDP fails to generate a screenshot, then [this line](https://github.com/quarto-dev/quarto-cli/blob/main/src/core/handlers/dot.ts#L160) will yield an undefined value as the value in sourceName.

(This, incidentally, appears to be something that TypeScript is failing to warn us about.)

Like I said, in regular operations, we should never get to this point, and we have code upstream of this that should be raising an exception. But something is going wrong there...

**Comment by marklhc** [comment]
Thank you for taking a look, @cscheid. I tried two computers (both with Ubuntu, so probably had similar setups) and got the same error. But as soon as I downgrade it to quarto 1.2.475, it has no problem and gives basically the same lines in the .tex file as you got.

**Comment by cscheid** [comment]
Our test suite runs on Ubuntu in CI. Let's see if it fails there.

**Comment by cscheid** [comment]
This is your file, rendering without issue on Ubuntu in our CI: https://github.com/quarto-dev/quarto-cli/actions/runs/4642683026/jobs/8217538102#step:22:2205

Do you have Google Chrome installed, and it might be an old version somehow?

**Comment by marklhc** [comment]
Interesting. I have Chromium (Version 111.0.5563.146) installed, but not Google Chrome.

**Comment by cscheid** [comment]
I don't know the details of Ubuntu distros well enough anymore to say anything more meaningful, but I specifically ran into so much trouble with snaps that I don't use them at all.

But the fact that you had installed chromium with a snap is enough information for us to at least consider an additional workaround in that case.

**Comment by marklhc** [comment]
Thanks. FYI: after removing chromium from snap and using `quarto tools install chromium`, the file is rendered properly.
