### ISSUE TITLE
Should help be printed when no arguments provided to quarto?

### ISSUE THREAD

**Issue by kevinushey** [quarto-dev/quarto-cli#5149]
### Bug description

For example:

```
kevin@MBP-P2MQ:~
$ /opt/local/bin/quarto
kevin@MBP-P2MQ:~
$ /opt/local/bin/quarto --help

  Usage:   quarto
  Version: 1.3.313

  Description:

    Quarto CLI

  Options:

    -h, --help     - Show this help.
    -V, --version  - Show the version number for this program.

  Commands:

    render          [input] [args...]     - Render files or projects to various document types.
    preview         [file] [args...]      - Render and preview a document or website project.
    serve           [input]               - Serve a Shiny interactive document.
    create          [type] [commands...]  - Create a Quarto project or extension
    create-project  [dir]                 - Create a project for rendering multiple documents
    convert         <input>               - Convert documents to alternate representations.
    pandoc          [args...]             - Run the version of Pandoc embedded within Quarto.
    run             [script] [args...]    - Run a TypeScript, R, Python, or Lua script.
    add             <extension>           - Add an extension to this folder or project
    install         [target...]           - Installs an extension or global dependency.
    publish         [provider] [path]     - Publish a document or project. Available providers include:
    check           [target]              - Verify correct functioning of Quarto installation.
    help            [command]             - Show this help or the help of a sub-command.
```

That is, invoking `quarto` (without arguments) just silently does nothing. Should it instead print help by default, or something similar?

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by allenmanning** [comment]
Meeting Notes:  Let's consider putting it in the error message.

**Comment by cscheid** [comment]
We revisited this a while back, and the decision was to keep the current behavior.
