### ISSUE TITLE
Code is run again for every output type in a book project

### ISSUE THREAD

**Issue by DhruvaSambrani** [quarto-dev/quarto-cli#5150]
### Bug description

Code is run twice (atleast for the `book` project) on `quarto render`. In the MWE below, the code appends `"Test"` to a file called `text.txt`. Starting by removing `text.txt` and running `quarto render` once leads to the file having `TestTest`, where it should just be `Test`.

[test.zip](https://github.com/quarto-dev/quarto-cli/files/11197283/test.zip)

Output of `quarto check`
```
❯ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.313
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /home/dhruva/.julia/conda/3/x86_64/bin/python3.10
      Jupyter: 5.2.0
      Kernels: julia-1.9, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

<details>
<summary>
Output of quarto render
</summary>
<pre><code>
❯ quarto render
[1/4] index.qmd
[2/4] intro.qmd

Starting python3 kernel...Done

Executing 'intro.ipynb'
  Cell 1/1...Done

Starting python3 kernel...Done

Executing 'intro.ipynb'
  Cell 1/1...Done

[3/4] summary.qmd
[4/4] references.qmd

pandoc 
  to: latex
  output-file: index.tex
  standalone: true
  toc: true
  number-sections: true
  top-level-division: chapter
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  crossref:
    chapters: true
  documentclass: scrreprt
  papersize: letter
  classoption:
    - DIV=11
    - numbers=noendperiod
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  bibliography:
    - references.bib
  title: test
  author: Norah Jones
  date: 4/11/2023
  
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023/Arch Linux) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023/Arch Linux) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  

Output created: _book/index.html
</code></pre>
</details>
</summary>

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
This is by design. Different formats may result in different output from the execution of code cells (for example, a plot may be produced as a PNG or as a PDF depending upon the target format). We do the same thing for simple documents like the below which specify multiple formats.

````
---
title: Hello World
format:
  html: default
  docx: default
date: now
---

## Hi

```{r}
plot(cars)
```
````

If you'd like to re-use execution, you can use freeze to control this how you'd like. See more about managing execution here: https://quarto.org/docs/projects/code-execution.html#overview

**Comment by DhruvaSambrani** [comment]
Hi @dragonstyle, thanks for the quick reply. In case I have turned on freeze, then is the expected action to run multiple times? I suppose this is the case, but just clarifying

**Comment by dragonstyle** [comment]
It should be the case that code will be executed if the freeze contents for a particular format aren't present, or if you trigger re-execution using one of the described approaches. So, for example, the very first time that you render a document, it will execute for each different format (building up the freezer), then use that frozen content for corresponding formats in subsequent renders.
