### ISSUE TITLE
Code line numbers for Docusaurus

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#5152]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5139

<div type='discussions-op-text'>

<sup>Originally posted by **eitsupi** April  9, 2023</sup>
Quarto supports the display of line numbers in code blocks in HTLM format, etc.
https://quarto.org/docs/output-formats/html-code.html

The syntax is thus.

````qmd
```{.python code-line-numbers="true"}
import matplotlib.pyplot as plt
plt.plot([1,23,2,4])
plt.show()
```
````

The syntax in Docusaurus seems to be as follows, ` showLineNumbers` is needed.
https://docusaurus.io/docs/markdown-features/code-blocks#line-numbering

````md
```python showLineNumbers
import matplotlib.pyplot as plt
plt.plot([1,23,2,4])
plt.show()
```
````

It would be great if Quarto could support this conversion.</div>

**Comment by jjallaire** [comment]
This is addressed in this PR for v1.4: https://github.com/quarto-dev/quarto-cli/pull/5291
