### ISSUE TITLE
Filters that call pandoc use system pandoc not Quarto pandoc

### ISSUE THREAD

**Issue by lyndondrake** [quarto-dev/quarto-cli#5163]
I am trying to use a filter (in this case, https://bcdavasconcelos.github.io/citetools/) which in turn relies on pandoc. My system currently has pandoc 3 in its path, and the installed quarto is 1.2 which uses pandoc 2. As a consequence, the marshalling of data is done by quarto's pandoc 2, and the demarshalling is attempted by the system's pandoc 3.

I realise that this particular problem will be removed once quarto 1.3 is released, as both quarto's pandoc and my system pandoc will be v1.3.

But it strikes me that there is no obvious reason for filters which are initiated within quarto to use a version of pandoc other than the one included in quarto itself — I can't think of a good outcome from that, and it could easily run into other weird incompatibilities.

Could quarto be modified to ensure that Lua filters run by quarto only make the quarto pandoc installation visible to the filters?

**Comment by cderv** [comment]
Can you share an example of what you observe exactly ? This would help us understand what could happen here.

A Lua filter run within Quarto will be run using the Pandoc version associated with that Quarto version. All the 

I can thing of some exception if the Lua filters in question calls `pandoc` binary directly itself (which will be searched on PATH), and does not just use LUA api.  This would probably not call the pandoc binary in quarto installation folder. 

Here (https://github.com/bcdavasconcelos/citetools/blob/main/_extensions/citetools/section-bibliographies.lua#L56-L65), they use [`utils.run_json_filter`](https://pandoc.org/lua-filters.html#pandoc.utils.run_json_filter) with for example 
````lua
run_json_filter(doc, 'pandoc', args)
````
By calling `pandoc` as the filter to use, they will call the `pandoc` binary found on PATH. 
However, it seems those kind of calls are protected by PANDOC_VERSION checks. 

> Could quarto be modified to ensure that Lua filters run by quarto only make the quarto pandoc installation visible to the filters?

What suggestion to you have on that ? I think we need to be able to reproduce this issue you see to understand what could cause this wrong pandoc version to be used. 

Also, can you share your exact quarto version, and extension version you use ? 

Thank you

**Comment by lyndondrake** [comment]
Sure:

```
quarto --version
1.2.475
```

The extension is the most recent GitHub version.

The error I got on the earlier version was this (I didn't save a copy of the error from the updated version):

```
JSON parse error: Error in $: Incompatible API versions: encoded with [1,22,2,1] but attempted to decode with [1,23].
Error running filter /Users/lyndon/.local/share/pandoc/filters/multiple-bibliographies.lua:
PandocFilterError "pandoc" "Filter returned error status 64"
stack traceback:
	.../.local/share/pandoc/filters/multiple-bibliographies.lua:50: in upvalue 'run_citeproc'
	.../.local/share/pandoc/filters/multiple-bibliographies.lua:82: in function <.../.local/share/pandoc/filters/multiple-bibliographies.lua:68>
```

**Comment by lyndondrake** [comment]
Oh and here's the output from `quarto pandoc --version`:

```
quarto pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: /Users/lyndon/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

You'll see the pandoc-types version corresponds to the encoding version number in the error message. I guess my point would be, is it really intended behaviour that quarto or one of its filters would ever call a version of pandoc different from the one embedded in quarto itself? And given that, why not ensure that the path is set up within quarto so that e.g. `run_json_filter(doc, 'pandoc', args)` calls the quarto pandoc, not the system one?

**Comment by mcanouil** [comment]
@cderv I let you confirm there is still a need for repo, thus that this issue is indeed stale.

**Comment by cderv** [comment]
It is still waiting for user feedback yes. We need more information. So I guess our stale policy applies. 

@lyndondrake is this still an issue ? If so we need more information to help. Thank you !

**Comment by cscheid** [comment]
We're closing this stale issue. Please reopen with the needed information if you still need help.

**Comment by anielsen001** [comment]
I came across this issue while trying to use quarto v1.2 with a newer version of pandoc installed (3.1). I don't know if this information is helpful, but I'll add it here in case anyone else find this. 

I was trying out the template for the [quarto-cv extension](https://github.com/mps9506/quarto-cv). To work with quarto 1.2 you need [quarto-cv@v1.0.0](https://github.com/mps9506/quarto-cv/tree/v1.0.0).

I have some docker containers built with various combinations of quarto and pandoc (as well as some other tools I use) in this [quarto-docker repo](https://github.com/anielsen001/quarto-docker). The [main branch has a dockerfile](https://github.com/anielsen001/quarto-docker/blob/main/Dockerfile-12) quarto 1.2 and pandoc 2.19.2 which work fine. The [test-pandoc branch has a dockerfile](https://github.com/anielsen001/quarto-docker/blob/test-pandoc/Dockerfile-12) which reproduces the error with a combination of quarto 1.2 and pandoc 3.1.

Hopefully this information is useful to someone in the future who comes across this problem.

**Comment by mcanouil** [comment]
Why would you work with 1.2 when 1.3 is the current stable version?

**Comment by anielsen001** [comment]
> Why would you work with 1.2 when 1.3 is the current stable version?

so I was trying to use [conditional includes with spans](https://github.com/quarto-dev/quarto-cli/discussions/8064) and it doesn't work. There was an issue with the quarto-cv extension supporting the pre-release 1.4 so I tried 1.2 where everything I want to do should be supported.

**Comment by mcanouil** [comment]
I suggest you report the issue in the extension then for the author to make the required changes or report a possible bug in Quarto.
