### ISSUE TITLE
template.html vs html.template

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#5173]
### Bug description

I noticed that https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/html/pandoc has a file named `template.html` and another file named `html.template` and their content if very similar. Do we need both files?

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
We do indeed- one is used to track the Pandoc template exactly while the other is our modified version. We keep the Pandoc version in the tree so that when we update Pandoc we can easily see the diffs (if any) in the template and apply those to our own...

**Comment by rgaiacs** [comment]
Thanks for the explanation.
