### ISSUE TITLE
Detecting Windows Store Python

### ISSUE THREAD

**Issue by BradyAJohnston** [quarto-dev/quarto-cli#519]
I have python installed from the windows store, currently python 3.10 and I am an unable to get quarto to detect it when attempting to render notebooks that include Python or Julia. 

The installation is on PATH, and I am able to start python from either `python` or `python3` in `cmd.exe` and Windows PowerShell, but Quarto still seems unable to detect it. 

I have also tried using RStudio and explicitly specifying the python interpreter in the python options in RStudio, but get the same problem with attempting to render the document
```bash 
[1/2] posts\test-julia\index.qmd

Starting Jupyter kernel...
ERROR: Error executing 'python': program not found
Unable to locate an installed version of Python 3.
Install Python 3 from https://www.python.org/downloads/
```

I was able to solve this by creating a `venv` but without it, quarto wasn't able to detect the Windows store python installation.

Thought I should let you know, and thanks for all the great work on such an awesome system!

**Comment by jjallaire** [comment]
Yes, we use the Windows Python Launcher to detect/manage Python installations. This eliminate a huge swatch of problems related to inconsistent `PATH` entries, unintentionally binding to older versions, etc. Unfortunately this currently doesn't work with Windows Store Python: https://docs.microsoft.com/en-us/windows/python/faqs#what-is-py-exe-

**Comment by BradyAJohnston** [comment]
Ah of course, here I was trying to keep things clean and manageable by using the Windows store python, but Microsoft was just making it more difficult than it needed to be, for seemingly no real reason.

I've installed it from python.org and it has now fixed the issue.
