### ISSUE TITLE
[Docusaurus] code block with filename placed at the top of the tab item does not work

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#5190]
### Bug description

Similar to #5103

This qmd file in Docusaurus project

````qmd
---
title: foo
---

:::{.panel-tabset}

## Not work

```{.python filename="Python"}
print("bar")
```

## Work

```{.python}
print("bar")
```

:::
````

will be converted to this md file

````md
---
title: foo
---

import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

<Tabs>
<TabItem value="Not work">
```python title="Python"
print("bar")
```

</TabItem>
<TabItem value="Work">

``` python
print("bar")
```

</TabItem>
</Tabs>

````

and rendered like this.

![image](https://user-images.githubusercontent.com/50911393/232023044-c8f94a9b-a1b1-49e1-9900-cb59beb17a55.png)

I tested it with the edge dev version of Quarto CLI.

```sh
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /tmp/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Sorry about the continued docusaurus issues - it wants a particular whitespace setup that we need to work around in a number of different places. (another) PR incoming.

**Comment by eitsupi** [comment]
Thanks for fixing it so quickly.

I feel that the Docusaurus integration is really great. Happy to contribute in any way to improving this.
