### ISSUE TITLE
Question: Is it possible to hide a Jupyter code cell in a PDF?

### ISSUE THREAD

**Issue by ericmjl** [quarto-dev/quarto-cli#520]
Hello Quarto team! I've been test-driving Quarto since last night, and I'm very excited about what I've experienced with Quarto thus far. Thank you all for putting out a great tool! The default templates are tasteful and gorgeous, and the documentation is well-written.

I have a question regarding hiding Jupyter code cells in a PDF. I've tried adding the following to a Jupyter code cell (VSCode is my editor):

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/2631566/161537813-6afa90a0-a82b-44e2-a6f4-5355a648be8a.png">

However, I still get the code cell rendering in the final PDF:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/2631566/161537721-5f852e24-c77a-4499-a392-a61832f19fc2.png">

I think I might be doing something incorrectly here. May I ask, is it possible to hide a Jupyter code cell in a rendered PDF?

**Comment by jjallaire** [comment]
I'm having trouble reproducing this locally (`echo` seems to work correctly for PDFs). Here is the full source code I am using:

````markdown
---
title: "PDF Echo"
format: pdf
---

For a demonstration of a line plot on a polar axis, see @fig-polar.

```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"
#| echo: false
#| code-overflow: scroll
#| warning: false

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```
````

If you could post a minimal reproducible example of the failure case your are seeing that would be great.

**Comment by ericmjl** [comment]
Ah! I think I found the issue! There was an extra space before the `|` in my notebooks :smile:. 

For the benefit of others:

Quarto requires: 

```
#| echo: false
```

However, I had done:

```
# | echo: false
```

Thank you for responding, @jjallaire! I believe the issue can be closed and will take the liberty of closing it.
