### ISSUE TITLE
`toc-location: left` not handled properly in (at least) "about" page (website)

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#5204]
```qmd
quarto create-project --type website:blog demo-toc-left
echo "toc-location: left" >> demo-toc-left/_quarto.yml
quarto render demo-toc-left
````

From the dev version, `toc-location: left` produces an empty left sidebar and "glass" side abr at the top[^1].
<img width="1512" alt="Screenshot 2023-04-16 at 20 34 23" src="https://user-images.githubusercontent.com/8896044/232334406-57857bb9-b23a-4553-819e-bba677c90548.png">

From the latest 1.2, only the empty sidebar
<img width="1508" alt="Screenshot 2023-04-16 at 20 37 53" src="https://user-images.githubusercontent.com/8896044/232334493-4a19f7e5-3886-4617-9d16-7a1a372a30f2.png">

Note that, I did not noticed unexpected behaviour with `toc-location: right` and `toc-location: body`.

[^1]: Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5203

**Comment by xuefeng-xu** [comment]
So for the about page, toc-location cannot be at left? 

https://github.com/quarto-dev/quarto-cli/blob/fcb70f3ec3a0e9211c9ddefc4903cac53d4cf507/news/changelog-1.4.md?plain=1#L167

**Comment by mcanouil** [comment]
@xuefeng-xu this issue is closed. Please open a new discussion or issue following the guidelines and templates with sufficient information such as the steps to reproduce and the output of `quarto check`.
Linking to 1.4 change log is not very helpful.
