### ISSUE TITLE
Adding a second class onto the callouts works in html format but not revealjs format

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#5208]
Adding a second class onto the callouts for HTML works — One usage example is to target a callout using CSS

```
::: {.callout-note .my-callout}
Hello!
:::
```

And the CSS file:

```
.callout.callout-style-default.my-callout .callout-body {
    font-size: 1.0rem;
}
```

_From a post by @jimjam-slam in https://github.com/quarto-dev/quarto-cli/discussions/4755#discussioncomment-5631059_

This works for HTML format as we pass attributes and classes, but not in revealjs format where it seems we don't.

**Comment by cderv** [comment]
@cscheid I think we need to adapt our callout custom node creation to allow passing attributes for revealjs format as we allow for html format. I can handle it for 1.4 or later, part of revealjs work.

**Comment by cscheid** [comment]
Agreed. I'm surprised that this doesn't work. I wonder if it's hiding a bigger bug.

**Comment by cderv** [comment]
I don't think so. From what I saw this morning, we are using a specific function for revealjs output 
https://github.com/quarto-dev/quarto-cli/blob/710f5b4ef5cf6e0644402cf4849b3fe2af3e3e9f/src/resources/filters/quarto-pre/callout.lua#L66-L67

but we are not inheriting the `node.attr` when creating the callout, as we do for HTML with bootstrap
https://github.com/quarto-dev/quarto-cli/blob/710f5b4ef5cf6e0644402cf4849b3fe2af3e3e9f/src/resources/filters/quarto-pre/callout.lua#L795-L808

I think we should have a specific `revealjsCallout()`, or non boostrap HTML callout. I don't know if we can pass any class and attributes to epub structure. Anyway, I was planning to make a proposal for 1.4 later. Happy to let you handle it as you know better this part of the code.
