### ISSUE TITLE
CSV files read with observable are interjected with html when File Extension is txt

### ISSUE THREAD

**Issue by nwvhb** [quarto-dev/quarto-cli#5215]
### Bug description

Hello, 

I have a strange bug, when reading CSVs. I think that it is the fault of Quarto given the results array, which appears to end up getting interjected with html to try to set up a table?  When the file extension is changed to csv, everything works as expected. 

Code
====
```{ojs}
result = FileAttachment("path/to/csv_saved_as_txt.txt").csv()
console.dir(result)
```

Contents of file
====
```
a, b, c
1, 2, 3
4, 5, 6
```
Output
====
![image](https://user-images.githubusercontent.com/131018245/232558722-4481b78b-12d2-4ee7-bd93-d8a3867287c8.png)

Notes
=====
I am Running in VSCode on Windows 7 with Preview set to External and Render on Save

[>] Checking Quarto installation......OK
      Version: 1.2.335
      Path: C:\Users\nwilley\AppData\Local\Programs\Quarto\bin
      CodePage: 1252
[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Thanks for the report. Can you:

- try this with a later version of quarto from [here](https://quarto.org/docs/get-started/)?
- prove a full reproducible example that we can render ourselves in a repository or attachment?

**Comment by nwvhb** [comment]
Here are the two files for reproduction.  I tested in the latest version and saw the same result.  GitHub wouldn't let me upload a QMD file, so it will have to be renamed from md.  Let me know if you need anything else. 
[ojs_csv_bug_repro.md](https://github.com/quarto-dev/quarto-cli/files/11578129/ojs_csv_bug_repro.md)
[csv_saved_as_txt.txt](https://github.com/quarto-dev/quarto-cli/files/11578130/csv_saved_as_txt.txt)

**Comment by mcanouil** [comment]
@nwvhb Could you provide them as plain text using code blocks?

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by cscheid** [comment]
I remain unable to reproduce this. I think the issue might be that the web server you're using is interpreting the .csv file as html, in which case there's nothing we can do.

**Comment by nwvhb** [comment]
@cscheid - Hmm, I am using deno with observable and running as localhost.

**Comment by cscheid** [comment]
I'm on VS code too:

<img width="1759" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/c9cbdc83-b6d8-43c7-aa95-31c92027a261">


<img width="737" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/8c8f1cce-10a6-4584-bbff-4651c14270f0">

**Comment by cscheid** [comment]
Wait, I take it back. Both my previous attempt and this had me accidentally inside a quarto website. I just noticed it now, and I can definitely see the issue.

**Comment by nwvhb** [comment]
Ok, great.  For reference, I'm using an external browser, if that matters.  Here's the render output. 
```
to: html
  output-file: ojs_csv_bug_repro.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png       

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
```
Output created: ojs_csv_bug_repro.html

**Comment by cscheid** [comment]
Specifically, this only happens with `quarto preview` of the standalone file: if you `quarto render` the file and then serve the .html with a static web server, this problem doesn't happen.

What seems to be going on, then, is that `quarto preview` is seeing a request for a `.txt` file and deciding to call `quarto render` on it rather than simply serving the content. Somehow, we don't do this for `.csv` files.

**Comment by cscheid** [comment]
This is now fixed on `main`, and should be available in our upcoming prerelease distributions. Thanks again for reporting!
