### ISSUE TITLE
epubcheck fails on figcaption

### ISSUE THREAD

**Issue by richardsprague** [quarto-dev/quarto-cli#5234]
### Bug description

I created an ePub version of my Quarto project, and although the ePub appears to work correctly, it fails a check on W3.org's [epubcheck](https://www.w3.org/publishing/epubcheck/) which is how Apple Books and others ensure that ePub is publishable. 

error:
`Error while parsing file: element "figcaption" not allowed here; expected the element end-tag, text, element "a", "abbr", "area", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "datalist", "del", "dfn", "em", "embed", "epub:switch", "i", "iframe", "img", "input", "ins", "kbd", "label", "link", "map", "mark", "meta", "meter", "ns1:math", "ns2:svg", "object", "output", "picture", "progress", "q", "ruby", "s", "samp", "script", "select", "small", "span", "strong", "sub", "sup", "template", "textarea", "time", "u", "var", "video" or "wbr" (with xmlns:ns1="http://www.w3.org/1998/Math/MathML" xmlns:ns2="http://www.w3.org/2000/svg") or an element from another namespace`

This is the epub source that fails.
```xml
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img src="../media/file0.jpg" /></p>
<p><figcaption>Local Image</figcaption></p>
</figure>
</div>
```
which looks fine to me, but I'm reporting this in case it's a known issue, or in case there's something weird about Quarto's `quarto-figure` class.  epubcheck is widely used, so I don't think this is a bug in the checker.

You can view my project on my Github Repo [quartosample](https://github.com/richardsprague/quartosample).

View the error yourself if you run epubcheck against [docs/This-is-a-book.epub](https://github.com/richardsprague/quartosample/blob/main/docs/This-is-a-book.epub)

I'm on OSX 13, using Quarto 1.3.330

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Wow, nice catch: we've been emitting bad HTML for a while, and this is not unique to epub. Bugfix incoming!

**Comment by cscheid** [comment]
@allenmanning That wasn't a regression - it's been like that as far as we could test.
