### ISSUE TITLE
Twitter link & account broken

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [quarto-dev/quarto-cli#525]
Hello lovely people !

I am reading your website building [guide](https://quarto.org/docs/websites/website-navigation.html) and clicked on the Twitter icon on the top right hand corner but it says the Twitter account does not exist.

![Screen Shot 2022-04-04 at 6 01 21 PM](https://user-images.githubusercontent.com/55933131/161652850-f357db33-e2d4-4d07-8552-6a19f756334e.png)

I discovered this when I was wanting to Tweet about how I was using your product. I was typing `@Quarto` but it lists other companies. 

Anyway, thanks for this software. 💯

**Comment by jjallaire** [comment]
Thanks for the heads up! We just switched our handle to quarto_pub (just fixed....)
