### ISSUE TITLE
Option to disable default image functionality

### ISSUE THREAD

**Issue by seeM** [quarto-dev/quarto-cli#5251]
Apologies if I'm missing something, but there doesn't seem to be a way to disable Quarto from setting the image of a post to the first image. I was thinking of something like setting `image: null` in the post metadata.

**Comment by cderv** [comment]
If you are referring to social preview, same as your question in Discussion, you can configure this in some settings https://quarto.org/docs/reference/projects/websites.html#social

If you are referring to listing feature, we have some information at https://quarto.org/docs/websites/website-listings.html#listing-fields to change the image 

Or do you want no image at all ?

**Comment by seeM** [comment]
Yes, I would like no image at all

**Comment by cderv** [comment]
> Yes, I would like no image at all

No image at all where ? in a Listing page ? In social preview ?

**Comment by seeM** [comment]
No image in the listing and social preview.

**Comment by dragonstyle** [comment]
Right now I don't think there is a way to disable this - the auto discovery is always finding an image.

We have a couple of options:
- We could relax the auto-discovery (as it was previous versions) so it less frequently finds preview images (e.g. the older versions required specific file names, class names, or document metadata to count as preview images). This old was was changed to make it easier to use computational images as preview images, so I'm loathe to go back.
- We could support `image: false` in the front matter as a way to disable preview image discovery. I'm in favor of this.

**Comment by seeM** [comment]
Thanks @dragonstyle! I agree on the `image: false` option. I don't think it's worth rolling back the auto-discovery feature just for this option

**Comment by nsfinkelstein** [comment]
Using the `image: false` option has produced the following error for me, under Quartion version 1.4.549

```
ERROR: TypeError: path.startsWith is not a function

Stack trace:
    at listingItemHref (file:///opt/quarto/bin/quarto.js:89130:37)
    at listItemFromFile (file:///opt/quarto/bin/quarto.js:88951:71)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async readContents (file:///opt/quarto/bin/quarto.js:88780:34)
    at async readListings (file:///opt/quarto/bin/quarto.js:88416:36)
    at async listingHtmlDependencies (file:///opt/quarto/bin/quarto.js:90080:45)
    at async Object.formatExtras (file:///opt/quarto/bin/quarto.js:90400:45)
    at async runPandoc (file:///opt/quarto/bin/quarto.js:68741:63)
    at async renderPandoc (file:///opt/quarto/bin/quarto.js:70041:26)
    at async Object.onRender (file:///opt/quarto/bin/quarto.js:77261:36)
```

I was able to disable images in the listing by setting `image-height: "0"` in the [listing options](https://quarto.org/docs/websites/website-listings.html#default-1).

**Comment by cscheid** [comment]
@nsfinkelstein We need a reproducible document to test.

**Comment by nsfinkelstein** [comment]
Thanks for the response. I happy with the approach of setting `image-height: "0"` in the listing options, so I don't mean to request that the issue be reopened. I just wanted to share that approach with anyone else who happens upon the same error and github issues I did.

**Comment by dragonstyle** [comment]
I can reproduce this (`image: false` was initially intended to affect editing image metadata on the page, but it should work in this context too). Here's that issue:

https://github.com/quarto-dev/quarto-cli/issues/8715
