### ISSUE TITLE
background image title banner being double rendered

### ISSUE THREAD

**Issue by KaiWaldrant** [quarto-dev/quarto-cli#5257]
### Bug description

When adding the metadata `title` and `title-block-banner` with an image path. The background image is rendered in the banner and the H1 in the banner.

![image](https://user-images.githubusercontent.com/80908902/233412025-00c2e185-8ff1-431d-9ef4-d22a4eea7201.png)

This is caused by quarto adding following to the html page:
```html
<style>
    .quarto-title-block .quarto-title-banner,
    .quarto-title-block .quarto-title-banner h1,
    .quarto-title-block .quarto-title-banner h2,
    .quarto-title-block .quarto-title-banner h3,
    .quarto-title-block .quarto-title-banner h4,
    .quarto-title-block .quarto-title-banner h5,
    .quarto-title-block .quarto-title-banner h6
    {
      background-image: url(images/heros/home_hero.jpg);
background-size: cover;
    }
    </style>
``` 
The background-image is added to `.quarto-title-block .quarto-title-banner` and `.quarto-title-block .quarto-title-banner h1`.

This is rendered using RC quarto 1.3.333, fedora 37. You can find a small repo preview in https://github.com/KaiWaldrant/quarto-title-block.

quarto check output:

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.333
      Path: /home/kai/opt/quarto-1.3.333/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /home/kai/anaconda3/bin/python
      Jupyter: 5.2.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /usr/lib64/R
      LibPaths:
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: (None)
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
``` 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Your metadata is asking to use both:

```
title: '![Open Problems in Single-Cell Analysis](images/heros/home_hero_text.png){width="80%"}'
title-block-banner: images/heros/home_hero.jpg
```

One of them is 
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/285675/233413894-3a46cd62-1442-43ea-a60c-712f15a732fa.png">

And the other is:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/285675/233414021-faf4fc30-111f-4beb-b9bc-243afcb21104.png">

These are the two different files you requested quarto to use, so quarto is using them. I'm not sure what you're expecting should happen.

**Comment by KaiWaldrant** [comment]
It is not that clear to see i'll try to make it more clear

**Comment by KaiWaldrant** [comment]
As you can see it is also on the `H1` element:
![image](https://user-images.githubusercontent.com/80908902/233426960-b61d7d82-9254-4668-b532-45368feb924b.png)

If I remove it from the banner it looks like this:

![image](https://user-images.githubusercontent.com/80908902/233427375-d306a15a-12ff-49b5-86a0-734dc67788f4.png)

The background-image should not be there as the image used for the title is transparant. It will also render like this when using text.

**Comment by cscheid** [comment]
> As you can see it is also on the H1 element:

Yes, I pointed that out in my comment above. It's there because you're asking it to be the background of the banner. You specified: 

```
title-block-banner: images/heros/home_hero.jpg
```

And then you've asking the H1 content to be

```
title: '![Open Problems in Single-Cell Analysis](images/heros/home_hero_text.png){width="80%"}'
```

When a banner exists, we use the `title` field as the content of the H1 heading that goes inside the banner. That's by design.

> The background-image should not be there as the image used for the title is transparant

If you don't want `background-image` to be the background of the banner, don't use `title-block-banner: images/heros/home_hero.jpg`.

I still don't understand what you're trying to achieve, sorry.
