### ISSUE TITLE
column-margin, wrong positioned

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#5289]
### Bug description

Hi,
I have this "hello world" qmd file: https://gist.github.com/aborruso/a9a95b902b35e77b0042e66dd7714a8f
It reads a CSV and an image. 
In [this zipped file](https://github.com/quarto-dev/quarto-cli/files/11311360/files.zip), the qmd file, the CSV, the image and the HTML output.

The problem I have is that the column margin text is not aligned correctly, it is moved further down.
I removed other output blocks from this example: in the original, the further I scroll down, the more this shift increases.
And the column-margin content is no longer aligned to its reference section, but to the next one.

If I remove the charts generated with altairs, everything realigns. What am I doing wrong?

I'm using Debian 11 and  quarto 1.3.253.

Thank you very much

![image](https://user-images.githubusercontent.com/30607/234024537-93166bca-f5c1-4eca-81f7-378e537db703.png)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
Thanks for reporting this - I can see that we're adding margin to the top of the margin element (which we do to try to offset it properly in the case of other margin content sharing the same cell). But it seems like we shouldn't need to be doing this in this case, so something has us confused - I'll take a look!

**Comment by aborruso** [comment]
> Thanks for reporting this - I can see that we're adding margin to the top of the margin element (which we do to try to offset it properly in the case of other margin content sharing the same cell). But it seems like we shouldn't need to be doing this in this case, so something has us confused - I'll take a look!

Is there some CSS temporary hack I can apply, before the release of the next version?

Thank you always for all

**Comment by dragonstyle** [comment]
One thing you could try that I _definitely_ would call a massive hack is:

```css
#consequat-duis-lorem div.column-container {
  margin-top: -31px;
}
```

Which I think should essentially shift the parent div up by 31 pixels (or whatever amount looks right to you).

**Comment by dragonstyle** [comment]
I've done a little more research on this one - the issue is really caused by the image itself. We're computing the positions of the margin elements and adding offsets before the image is fully loaded, so we aren't taking the height of the image into account when we're positioning the margin elements below it. 

I experimented with a few simple fixes to this issue, but didn't have success, so I think we'll likely have to something a bit more clever...

**Comment by aborruso** [comment]
Thank you very much. I think it will be really useful.

Will you release it in the next 1.3.x?

**Comment by dragonstyle** [comment]
I will back port this to 1.3 so it will ship with any patch that we make to 1.3 (though we don't currently have a concrete plan / ETA for this).

**Comment by aborruso** [comment]
@dragonstyle fingers crossed then, because I created some long reports, which have become difficult to read. And I can't fix it myself :(

I don't want to pressure you, I can only say thank you!

**Comment by aborruso** [comment]
@dragonstyle I have installed 1.4.11 and it works. Thank you very much.

But I have a new problem: the footnotes is now inside `.column-margin`

Is it right?

Thank you

![image](https://user-images.githubusercontent.com/30607/234994213-a4d0e5e7-caf9-4ace-ba8c-393a9d4a470e.png)

**Comment by dragonstyle** [comment]
Would you mind opening a new issue for that and point me at the file / qmd causing it (shouldn't be happening!) ?

**Comment by aborruso** [comment]
> Would you mind opening a new issue for that and point me at the file / qmd causing it (shouldn't be happening!) ?

Thank you https://github.com/quarto-dev/quarto-cli/issues/5338
