### ISSUE TITLE
Smoke tests for Hugo, Docusaurus, etc.

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#5309]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5304

<div type='discussions-op-text'>

<sup>Originally posted by **eitsupi** April 25, 2023</sup>
At this time, no Hugo or Docusaurus format testing is being done in this repository.
I believe this was one of the reasons for the serious regression in the 1.3 Docusaurus format (#5079).

I believe there has been discussion of adding tests for these formats (e.g., comment #5087), but it has not been possible due to additional dependencies (e.g., Docusaurus itself).

However, for Hugo and Docusaurus formats, the `quarto render` command only does markdown output, and I believe the functionality used in tests is not actually dependent on Hugo or Docusaurus.
So I think something like snapshot tests can be performed only with Quarto CLI itself, how about that?

(I think it would be easier for less experienced people like myself to make contributions to the code base if something like snapshot tests were in place.)</div>

**Comment by allenmanning** [comment]
@cscheid @eitsupi I've moved this to an issue, thank you for posting this @eitsupi.  👍

**Comment by eitsupi** [comment]
FYI, this seems the tracking issue of supporting docusaurus by deno denoland/deno#19395

**Comment by cscheid** [comment]
(This is ongoing in the feature-format matrix, `dev-docs/feature-format-matrix`)
