### ISSUE TITLE
using bootstrap icons

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#532]
Is it possible to use the bootstrap icons that quarto uses for e.g. the github icon of a quarto website (https://quarto.org/docs/websites/website-navigation.html#sidebar-tools) in other places such as inline in a quarto document or a presentation?

**Comment by jmbuhr** [comment]
Maybe the real question should be: which output formats automatically include the icons? Since adding them to the css manually is straightforward with `@import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css");`

And the you can use them in markdown with e.g.: `[](https://github.com/){.bi-github}`

**Comment by jjallaire** [comment]
They are included in websites but not in standalone documents (just to not add this payload automatically to every doc). At least that's what I recall -- @dragonstyle is that correct?

**Comment by jmbuhr** [comment]
sounds reasonable, thanks :)

**Comment by dragonstyle** [comment]
We actually currently are including bootstrap icons along with any bootstrap themed html output (our html format). If you are using one of our bootstrap themes (or our default themes), you should have access to bs icons. If you choose `theme:none` or `theme:pandoc`, we will exclude any of the bootstrap theming dependencies, including the bootstrap icons.

They aren't available in revealjs (even though this is HTML output, it relies on its own theming and so doesn't carry any of the bootstrap dependencies along with it).
