### ISSUE TITLE
Failed to render with PaddleOCR used while jupyter notebook generated is OK

### ISSUE THREAD

**Issue by Romc3** [quarto-dev/quarto-cli#5331]
### Bug description

I am writing a document with python code using PaddleOCR. When Quarto starts to render and executes notebook cells, a `FileNotFoundError` exception is raised. However, I could run the cell from the Jupyter Notebook generated by Quarto without any error, via the Jupyter Notebook extension in VS Code.

The quarto code cauing the problem is as follows:
````quarto
---
title: "Problem with PaddleOCR"
jupyter: python3
---

```{python}
from paddleocr import PaddleOCR

OCR = PaddleOCR(use_angle_cls=True, show_log=False)

print("OK")
```
````

The output from VS Code's terminal is as follows

```log
❯ quarto preview e:/Development/comprehensive/dipExp/tasks/homework/task2/issue.qmd --no-browser --no-watch-inputs

Starting python3 kernel...Done

Executing 'issue.ipynb'
  Cell 1/1...ERROR: 

An error occurred while executing the following cell:
------------------
from paddleocr import PaddleOCR

OCR = PaddleOCR(use_angle_cls=True, show_log=False)

print("OK")
------------------

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 1
----> 1 from paddleocr import PaddleOCR
      3 OCR = PaddleOCR(use_angle_cls=True, show_log=False)
      5 print("OK")

File e:\Development\comprehensive\dipExp\tasks\.venv\lib\site-packages\paddleocr\__init__.py:14
      1 # Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from .paddleocr import *
     16 __version__ = paddleocr.VERSION
     17 __all__ = [
     18     'PaddleOCR', 'PPStructure', 'draw_ocr', 'draw_structure_result',
     19     'save_structure_res', 'download_with_progressbar', 'sorted_layout_boxes',
     20     'convert_info_docx', 'to_excel'
     21 ]

File e:\Development\comprehensive\dipExp\tasks\.venv\lib\site-packages\paddleocr\paddleocr.py:21
     17 import importlib
     19 __dir__ = os.path.dirname(__file__)
---> 21 import paddle
     23 sys.path.append(os.path.join(__dir__, ''))
     25 import cv2

File e:\Development\comprehensive\dipExp\tasks\.venv\lib\site-packages\paddle\__init__.py:76
     74 import paddle.jit  # noqa: F401
     75 import paddle.amp  # noqa: F401
---> 76 import paddle.dataset  # noqa: F401
     77 import paddle.inference  # noqa: F401
     78 import paddle.io  # noqa: F401

File e:\Development\comprehensive\dipExp\tasks\.venv\lib\site-packages\paddle\dataset\__init__.py:27
     25 import paddle.dataset.
```

The `quarto check` command's output is as follows:

```log
❯ quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.340
      Path: D:\Program Files\Quarto\bin
      CodePage: 936

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: E:/Development/comprehensive/dipExp/tasks/.venv/Scripts/python.exe
      Jupyter: 5.3.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

In the same virtual environment (created by poetry), I can also run the python code via the python interpretor without any error.

I am using Quarto's VS Code extension, I don't have RStudio installed.
I am using Python 3.10.10 on Windows 11

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
This kind of import resolution problem happens when quarto finds a different Python installation than the one you're using for your standalone notebook execution. We follow the information from your environment, so unfortunately you will have to figure out what's causing the discrepancy.

It's possible that the library paths are misconfigured in your shell (and that VS Code is succeeding because it's using different information)

**Comment by Romc3** [comment]
This is where things goes weird, if I modify the qmd file like this:

````quarto
---
title: "Problem with PaddleOCR"
jupyter: python3
---

```{python}
import numpy as np

arr = np.array([1, 2, 3])
print(arr)
```

```{python}
from paddleocr import PaddleOCR

OCR = PaddleOCR(use_angle_cls=True, show_log=False)
print("OK")
```
````

Then quarto will succeed to execute the first cell. I have checked my python interpretor installation and `numpy` only exists inside the virtual environment.

If quarto failed to configure the virtual environment, `ModuleNotFoundError` would be raised instead of `FileNotFoundError`. If there are some problem in the virtual environment, the jupyter notebook should raise `FileNotFoundError` too.

**Comment by cscheid** [comment]
> If quarto failed to configure the virtual environment, ModuleNotFoundError would be raised instead of FileNotFoundError. 

That's not how this works: Quarto doesn't configure the virtual environment. It simply forwards the information from your environment. What I suspect is happening (I've seen this in several other reports of jupyter issues) is that your command-line environment in windows is providing different information than what visual studio is using.

For example, in your windows env you could have a python directory that takes priority over the virtual environment, and that's only seen by Quarto. Quarto then calls jupyter with this same environment, and loading the libraries failed. VS Code, on the other hand, uses some other method of resolving Python path/library information, which ignores your command-line environment.

**Comment by Romc3** [comment]
Having used windows terminal instead of VS Code's integrated terminal, but the problem still exists. After activating the environment by `poetry shell` (otherwise `ModuleNotFoundError` would be raised), the python source file could work but quarto still raises `FileNotFoundError`.
I have been discovering that when I running `quarto preview` there is a terminal flashing past while when I executing the code via Jupyter Notebook or python interpreter it doesn't pop out.
The python package `PaddleOCR`'s API is heavily relied on its CLI tool, maybe its execution is automatically terminated by quarto, but I have no idea how to resolve this.

**Comment by cscheid** [comment]
> maybe its execution is automatically terminated by quarto

We don't have any code that would do that, and I don't see any evidence that suggests to be that this is what happening. I would like, though, to see the full stack trace from VS code. Can you post that? What you have posted stops halfway through a line:

```
File e:\Development\comprehensive\dipExp\tasks\.venv\lib\site-packages\paddle\__init__.py:76
     74 import paddle.jit  # noqa: F401
     75 import paddle.amp  # noqa: F401
---> 76 import paddle.dataset  # noqa: F401
     77 import paddle.inference  # noqa: F401
     78 import paddle.io  # noqa: F401

File e:\Development\comprehensive\dipExp\tasks\.venv\lib\site-packages\paddle\dataset\__init__.py:27
     25 import paddle.dataset.
```

**Comment by Romc3** [comment]
In fact this is not truncated by me but the terminal's output *suddenly ended*, so I don't know what the complete stack trace is.

```log
❯ quarto preview issue.qmd

Starting python3 kernel...Done

Executing 'issue.ipynb'
  Cell 1/2...Done
  Cell 2/2...ERROR:

An error occurred while executing the following cell:
------------------
from paddleocr import PaddleOCR

OCR = PaddleOCR(show_log=False)
print("OK")
------------------

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[2], line 1
----> 1 from paddleocr import PaddleOCR
      3 OCR = PaddleOCR(show_log=False)
      4 print("OK")

File E:\Development\comprehensive\dipExp\tasks\.venv\lib\site-packages\paddleocr\__init__.py:14
      1 # Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from .paddleocr import *
     16 __version__ = paddleocr.VERSION
     17 __all__ = [
     18     'PaddleOCR', 'PPStructure', 'draw_ocr', 'draw_structure_result',
     19     'save_structure_res', 'download_with_progressbar', 'sorted_layout_boxes',
     20     'convert_info_docx', 'to_excel'
     21 ]

File E:\Development\comprehensive\dipExp\tasks\.venv\lib\site-packages\paddleocr\paddleocr.py:21
     17 import importlib
     19 __dir__ = os.path.dirname(__file__)
---> 21 import paddle
     23 sys.path.append(os.path.join(__dir__, ''))
     25 import cv2

File E:\Development\comprehensive\dipExp\tasks\.venv\lib\site-packages\paddle\__init__.py:76
     74 import paddle.jit  # noqa: F401
     75 import paddle.amp  # noqa: F401
---> 76 import paddle.dataset  # noqa: F401
     77 import paddle.inference  # noqa: F401
     78 import paddle.io  # noqa: F401

File E:\Development\comprehensive\dipExp\tasks\.venv\lib\site-packages\paddle\dataset\__init__.py:27
     25 import paddle.dataset.wmt14  # noqa: F401
     26
```
This is the deepest stack trace by far.

**Comment by cscheid** [comment]
This is strange. To be clear, quarto is not doing this; that stack trace is coming from the python interpreter (which is itself coming from [`nbclient`](https://github.com/jupyter/nbclient), the library we use to execute jupyter notebooks).

**Comment by Romc3** [comment]
It seems that it is the compatibility issue in `paddlepaddle`, which supports, according to its PyPI page, up to Python 3.8 while I am using Python 3.10. When I trying to reproduce this problem in Windows Sandbox, installing Python 3.8 the expected problem doesn't appear and quarto goes well too. For some reason `poetry` didn't detect the compatibility issue and successfully installed `paddlepaddle` in my previous virtual environment and the problem behaves like the `vcredist` is not installed appropriately, which makes it strange. Thanks for your patience, it was a rookie mistake.
