### ISSUE TITLE
Reveal JS code annotation broken when `scrollable: true`

### ISSUE THREAD

**Issue by jarbet** [quarto-dev/quarto-cli#5339]
### Bug description

**Attached is my example .qmd file**:
[test.qmd.zip](https://github.com/quarto-dev/quarto-cli/files/11348406/test.qmd.zip)

**Problem**:

- Notice the annotation comment does not fit/display correctly on the screen when hovering over it (using `code-annotations: select` instead of `hover` has the same problem):
- Yes, a horizontal scroll-bar appears on the bottom, however, trying to click on this scroll bar causes the annotation comment to disappear.

![image](https://user-images.githubusercontent.com/103967480/235005604-a58418ef-2f1a-4899-8ac2-b0cd35fcc77d.png)

**RStudio IDE version:**

![image](https://user-images.githubusercontent.com/103967480/235005201-b427d4ba-80ad-4123-9889-1834dd2b932b.png)

**OS:**

![image](https://user-images.githubusercontent.com/103967480/235005305-33c8a3f6-c1f4-43bc-817b-66aa1b8bc74b.png)

**quarto check**

```
[✓] Checking Quarto installation......OK
      Version: 1.2.335
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: /Users/jarbet/opt/anaconda3/bin/python
      Jupyter: 4.9.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

quarto check
(base) RELMJCCADM27261:group-statistics jarbet$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: /Users/jarbet/opt/anaconda3/bin/python
      Jupyter: 4.9.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.41
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Can you first check with a new quarto version? https://quarto.org/docs/get-started/

**Comment by jarbet** [comment]
> Can you first check with a new quarto version? https://quarto.org/docs/get-started/

Still having the same issue:

![image](https://user-images.githubusercontent.com/103967480/235009778-e74fafe6-d513-4ce1-8138-9a26ed4f6568.png)

New `quarto check`:

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: /Users/jarbet/opt/anaconda3/bin/python
      Jupyter: 4.9.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.41
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Ok, thanks!

I can reproduce this locally. To make it easier, the contents of that .qmd file are here:

````
---
title: "test"
format: revealjs
scrollable: TRUE
code-annotations: hover
---

## Nearest neighbor caliper matching

```{r, echo = TRUE, eval = FALSE}
#| code-line-numbers: "1,3,7,8,10,11"
library(MatchIt);

set.seed(1234);
match.nnc.logit <- matchit( # <1>
    treat ~.,
    data = psdata,
    method = 'nearest',
    distance = 'glm',
    replace = FALSE,
    caliper = 0.2,
    std.caliper = TRUE,
    ratio = 1 # 1:1 matching
    );
```

1. Stuart, Elizabeth A., et al. "MatchIt: nonparametric preprocessing for parametric causal inference." Journal of statistical software (2011)
````
