### ISSUE TITLE
typst not found yet installed.

### ISSUE THREAD

**Issue by sje30** [quarto-dev/quarto-cli#5353]
### Bug description

Taking the example from  https://quarto.org/docs/prerelease/1.4/typst.html

````md
---
title: "My document"
format: typst
---

Hello, typst!


````

when I run this on my Mac I get:
```
quarto render typst1.qmd 
pandoc 
  to: typst
  output-file: typst1.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  
metadata
  title: My document
  
ERROR: You need to install the Typst CLI in order to render typst documents.

Installing Typst: https://github.com/typst/typst#installation
```

typst is installed though (via home-brew)

```
$  which typst
/opt/homebrew/bin/typst
```

```
$   quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.14
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /Users/stephen/.pyenv/versions/3.11.1/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /opt/homebrew/Cellar/r/4.2.3/lib/R
      LibPaths:
        - /Users/stephen/NOBACKUP/RLIB
        - /opt/homebrew/Cellar/r/4.2.3/lib/R/library
      knitr: 1.41
      rmarkdown: 2.19

[✓] Checking Knitr engine render......OK

$ uname -a
Darwin blur.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Thanks for the report. Can you run `typst --version`?

From [the source](https://github.com/quarto-dev/quarto-cli/blob/main/src/core/typst.ts#L70), it looks like [`typstVersion`](https://github.com/quarto-dev/quarto-cli/blob/main/src/core/typst.ts#L52) is returning `undefined`. We should have better diagnostics for errors, but maybe the output of `typst --version` will help.

In my macOS, I get this:

```
$ which typst
/opt/homebrew/bin/typst
$ typst --version
typst 0.3.0
$ quarto render typst-test.qmd
pandoc
  to: typst
  output-file: typst-test.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none

metadata
  title: My document

[typst]: Compiling typst-test.typ to typst-test.pdf...DONE

Output created: typst-test.pdf
$ uname -a

Darwin Lydian-2.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64
```

**Comment by sje30** [comment]
thanks -- this was the problem.  I had an older version of typst installed:

```
typst --version 
typst 23-03-28
```

upgrading it (to 0.30) solved the problem

```
$ brew upgrade typst
$typst --version
typst 0.3.0

$  quarto render typst1.qmd
pandoc 
  to: typst
  output-file: typst1.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  
metadata
  title: My document
  
[typst]: Compiling typst1.typ to typst1.pdf...DONE

Output created: typst1.pdf
```

**Comment by cscheid** [comment]
> so it looks like the logic for detecting typst version is slightly fragile; but perhaps this is a small issue as presumably future versions of typst will follow a semantic version, rather than date format?

that's correct.

**Comment by TrillStones** [comment]
> > so it looks like the logic for detecting typst version is slightly fragile; but perhaps this is a small issue as presumably future versions of typst will follow a semantic version, rather than date format?
> 
> that's correct.

My circumstance：

1、typst 0.4.0

2、pandoc 3.1.2
Features: +server +lua
Scripting engine: Lua 5.4


it occur the problem again .

**Comment by sje30** [comment]
Hmmm... I have the same versions (i.e. now typst 0.4.0), but for me it is working:

```
 typst --version
typst 0.4.0

pandoc --version
pandoc 3.1.2
Features: +server +lua
Scripting engine: Lua 5.4
```

can you run `quarto check` ?

**Comment by cscheid** [comment]
(I believe this is now solved with our bundling of `typst` and their usage of semantic version numbers)
