### ISSUE TITLE
First heading transformed to title when dynamic python content

### ISSUE THREAD

**Issue by benabel** [quarto-dev/quarto-cli#5363]
### Bug description

Hello dear quarto developers.
When upgrading to quarto 1.3, quarto changed the way to transform may `qmd` files with python executable cells to `html`.

This bug appeared after 1.3.146 that worked normally and current 1.3.340 where the first heading is moved to top of file as a title **when there is a notebook intermediate file**.

Example:

    Some paragraph

    ## This is first heading and not the title

    The first heading is transformed in title and placed at the top of the document.

    ## Exécution

    ```{python}
    print("Hello")
    ```

Will be rendered with `This is first heading and not the title` as the title in the top of the document in the title block. **But**, if the python cell is converted to normal code block(not executed)  `This is first heading and not the title`  stays where it is as a h2 heading like this was rendered in previous quarto versions.

It seems that the bug occurs when converting the `ipynb` file to `html` because in the notebook the first heading is preserved.

Example runned on fresh archlinux.

```
[ben@archben ~]$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: lua, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
Could you provide a complete Quarto document by the following <https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us>?

**Comment by benabel** [comment]
This is because I indented the code block? Here is the minimal `qmd` example with four backticks.

````
Some paragraph

## This is first heading and not the title

The first heading is transformed in title and placed at the top of the document.

## Exécution


```python
print("Hello")
```
````

**Comment by benabel** [comment]
When the process pass by an intermediate notebook it renders like this: 

```html
<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">This is first heading and not the title</h1>
</div>
<div class="quarto-title-meta">
  </div>
</header>

<p>Some paragraph</p>
<p>The first heading is transformed in title and placed at the top of the document.</p>
```

But everything is ok(and was previously OK) if the cell is not executed(turned into `{.python}`.

```html
<p>Some paragraph</p>
<section id="this-is-first-heading-and-not-the-title" class="level2">
<h2 class="anchored" data-anchor-id="this-is-first-heading-and-not-the-title">This is first heading and not the title<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="[#this-is-first-heading-and-not-the-title](view-source:file:///home/ben/Bureau/demo.html#this-is-first-heading-and-not-the-title)" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>
<p>The first heading is transformed in title and placed at the top of the document.</p>
</section>
```

**Comment by mcanouil** [comment]
I think this is a side effect of an intended behaviour added during 1.3 development, see #5228.
_i.e._, not only the first level 1 heading is treated as title, but the first of any level of heading.
This can be easily seen by using `quarto convert` command as captured in the below screenshot.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/8896044/235457928-739ddf69-0c47-47e1-a575-c844fcb7c083.png">

**Comment by benabel** [comment]
It seems weird that the document is different when passing by an iynb intermediate file. Pandoc allows to convert a heading to title with the `shift-heading-level-by` negative numbers which seems more predictive, why don't use the same trick when needed in quarto.

**Comment by cscheid** [comment]
@allenmanning I know very little about this part of the codebase. I think you were looking for @dragonstyle ...

**Comment by benabel** [comment]
This issue is still relevant in latest version (1.4.146) even after #5785.

**Comment by nathancunn** [comment]
Similarly, this issue occurs when you try to dynamically set a document title. See below. The Section 1 header disappears when rendered.

It seems to be that the first pass of the document pulls in header 1 into the title, which subsequently gets overwritten by the dynamic title setting. This can be overcome specifying a placeholder title in the static front matter, but I don't think this behaviour overall is desired.

`markdown

---
format: pdf
execute:
    echo: false
---
```{python}
#| output: asis
title = "test"
print(f"""
---
title: {title}
---
"""
)
```

# Section 1 (disappears)
# Section 2


`

**Comment by cderv** [comment]
@dragonstyle I am reputting this issue in the backlog following https://github.com/quarto-dev/quarto-cli/issues/6411 report (maybe same issue). 

Though, I understand from @mcanouil that it could be on purpose (https://github.com/quarto-dev/quarto-cli/issues/5363#issuecomment-1529712609). In that case, only  #6411 is relevant as currently `title` metadata defined in `_quarto.yml` is ignored. 

So if https://github.com/quarto-dev/quarto-cli/issues/5363#issuecomment-1529712609 is true, then we have a difference in behavior for knitr engine document and jupyter engine document. I know we are tracking those difference in behavior, so pointing that out.

**Comment by benabel** [comment]
Thank you very much @dragonstyle and all the quarto team for taking into account this issue.
