### ISSUE TITLE
Long code chunks don't break in pdf

### ISSUE THREAD

**Issue by louisahsmith** [quarto-dev/quarto-cli#537]
Code chunks longer than a page are continuing off the page when rendered in Latex, instead of breaking and starting a new page. I believe this would be fixed by adding `breakable` to the `tcolorbox` options [here](https://github.com/quarto-dev/quarto-cli/blob/52fb262c7651c5c0d508ce2b9264f843f0ead48a/src/resources/filters/layout/meta.lua#L39).

**Comment by dragonstyle** [comment]
That you - exactly right! The fix is here 5cfe5046f1df1e55c611056f5ca5d51273b52bf0 and a fresh build is on the way!
