### ISSUE TITLE
Description generation do not work properly for none-English post

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#5371]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5369

<div type='discussions-op-text'>

<sup>Originally posted by **DayuanJiang** May  1, 2023</sup>
My first paragraph is quite lengthy in my post, but when the description is generated on the index page, it only displays the first few words. How can I control the behavior of the description generation?
My blog site is here: [blog](https://www.jiang.jp/)

**post page**
![post page](https://res.cloudinary.com/jiang/image/upload/v1682935832/Untitled.png)
**index page**
![index page](https://res.cloudinary.com/jiang/image/upload/v1682935832/Untitled_1.png)
</div>

**Comment by mcanouil** [comment]
Example:

```qmd
---
title: "InPars V2 論文解読"
date: "2023-05-01"
---

InPars V2論文では、Query生成に使用するLLMがGPT3からオープンソースのGPT-J(6B)に変更され、生成したQueryのフィルタリング方法がLog Probabilityからmonot5(3B)をRerankerとして利用する方法に変更された点を挙げている。実験結果としては、V2の精度がV1と比べてわずかに向上したことが報告されて
```
