### ISSUE TITLE
Broken link in "notebook embed" feature guide

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#5372]
At the bottom of "notebook-views" section the link to the "live preview for the Penguins notebook" is broken (see <https://quarto.org/docs/authoring/notebook-embed.html#notebook-views>)[^1].
<img width="1508" alt="Screenshot 2023-05-01 at 15 08 18" src="https://user-images.githubusercontent.com/8896044/235455841-b0e6f57e-7360-4d2f-b800-60aa6817d41c.png">

[^1]: There is no notebooks in <https://github.com/quarto-dev/quarto-web/tree/main/docs/prerelease/1.3> and no idea where the notebook might be or what it should be.

**Comment by cderv** [comment]
I believe it was lost while moving the `.ipynb` file with others in https://github.com/quarto-dev/quarto-web/pull/678

**Comment by cderv** [comment]
Do we report broken links in other places already ? 😲 

Reporting broken links would be a nice feature ! Or having  a tooling that would parse links and checks for bad links like **urlchecker** 📦 in R.

**Comment by mcanouil** [comment]
There are many tools that can be implemented as a GHA workflow, such as https://github.com/stevenvachon/broken-link-checker.

**Comment by mcanouil** [comment]
Would be tricky to test links locally and as some kind of "post-render" step, because base URL would need to set to localhost:PORT.
This being said, the repository I mentioned also check for missing images which can be handy when linking to external images.

**Comment by cscheid** [comment]
> Do we report broken links in other places already ? 😲

We report broken .qmd links, yeah. Since .ipynb is a legit quarto format, I think we should consider reporting that too :)

**Comment by cderv** [comment]
> We report broken .qmd links, yeah

Always discovering new stuff 😄 

> Since .ipynb is a legit quarto format, I think we should consider reporting that too :)

I agree. I let you open an issue if you want to track that
