### ISSUE TITLE
Can't specify subdirectory in repo-url

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#538]
Quarto assumes that when a project is stored in a Github repository, the toplevel of the Quarto project directory is the same as the toplevel of the repository file hierarchy.

Thus if I specify the following in _quarto.yml:

```
repo-url: "https://github.com/<myhandle>/<myhandle>.github.io/projects/proj1"
repo-branch: public
repo-actions: [source]
```

Then the "View Source" link of e.g. index.qmd  in proj1 looks like:

`https://github.com/<myhandle>/<myhandle>.github.io/projects/proj1/blob/public/index.qmd`

which is nonsensical to Github and it returns a 404.  The URL should look like:

`https://github.com/<myhandle>/<myhandle>.github.io/blob/public/projects/proj1/index.qmd`

i.e. the "blob/public" section of the URL should always come after the repository name ("&lt;myhandle&gt;.github.io"), not simply appended to the repo-url value.

Your website says one of the uses of Quarto is to "Publish collections of articles as a website".  I think that's a great goal and I'm trying to build toward it.  But if I want to store multiple Quarto article projects in a single repository, there seems to be no way right now to utilize Quarto's Github collaboration features for those projects.

**Comment by jjallaire** [comment]
Thanks for reporting this. Should be addressed here: https://github.com/quarto-dev/quarto-cli/commit/be5d38f7de5e031a041583ef533725362a117727
