### ISSUE TITLE
Disable filter in folder search

### ISSUE THREAD

**Issue by fire** [quarto-dev/quarto-cli#539]
Is it possible to disable filter search here in the folder search? I'm not sure what it is called in code. The problem is someone mentioned that searches are confusing.

https://v-sekai.github.io/decisions.html

**Comment by dragonstyle** [comment]
Yes you sure can! Just use yaml like this to disable 

'''
listing:
  filter-ui: false
'''

**Comment by fire** [comment]
Thanks.
