### ISSUE TITLE
Embedding Vimeo video does not work with "unlisted" links

### ISSUE THREAD

**Issue by Joda66** [quarto-dev/quarto-cli#5390]
## Description
Unlisted Vimeo videos produce a link that does not work with the Quarto shortcode {{ video }}

## Steps to Reproduce
- Log in with a Standard Account. 
- select a video with privacy settings "unlisted"
- click the share link button
- The link copied to the clipboard is `https://vimeo.com/800138810/fdcc90d662?share=copy`
- Use this link in the video short code `{{< video https://vimeo.com/800138810/fdcc90d662?share=copy >}}`

## Expected Result: 
A video snippet is created with  the url.  The video snippet can load the video.

## Actual Result:
Using this link with the shortcode results in the error message "Invalid embedding-code"

### Workaround
Replace the slash in the privacy hash with `"?h="` and delete `"?share=copy"` so 
`{{< video https://vimeo.com/800138810?h=fdcc90d662 >}}`

Please note: the privacy setting "Hide from Vimeo", that creates links for embedding only, does not (!) contain a privacy hash and works well with the shortcode `{{< video https://vimeo.com/800139587?share=copy >}}` so no problem for "Hide-from-Vimeo" videos as of writing this post, but only for "Unlisted" videos.

**Comment by Joda66** [comment]
Embedding a Vimeo-video does not work anymore.
Rendering the shortcode

{{< video https://vimeo.com/user188343875/010?share=copy >}}

produces the error

"No video source specified for video shortcode"

Embedding works with "old" Vimeo-links links like 
{{< video https://vimeo.com/817906412 >}}

but Vimeo has changed the links, they are production to the example shown above.

**Comment by cderv** [comment]
@allenmanning are vimeo videos supposed to be supported by our own Lua filter or by video.js integration ? 

I am still unsure about this and this is not the first time I am asking myself this question. I am wondering because currently with both example above, I believe video.js will be used because there is no `https://` in the link used. Our video builder will quit early
https://github.com/quarto-dev/quarto-cli/blob/4a4e9f1226df1f6f994ac084b226150966bc7aa5/src/resources/extensions/quarto/video/video.lua#L118-L119

Videojs builder will then be used, but it is unclear to me what we package for this because [vimeo is supposed to be surported with a plugin](https://videojs.com/guides/faqs/#q-can-videojs-play-vimeo-videos)

Anyhow, you know the feature the best.

**Comment by allenmanning** [comment]
> @allenmanning are vimeo videos supposed to be supported by our own Lua filter or by video.js integration ?
> 
> I am still unsure about this and this is not the first time I am asking myself this question. I am wondering because currently with both example above, I believe video.js will be used because there is no `https://` in the link used. Our video builder will quit early
> 
> https://github.com/quarto-dev/quarto-cli/blob/4a4e9f1226df1f6f994ac084b226150966bc7aa5/src/resources/extensions/quarto/video/video.lua#L118-L119
> 
> Videojs builder will then be used, but it is unclear to me what we package for this because [vimeo is supposed to be surported with a plugin](https://videojs.com/guides/faqs/#q-can-videojs-play-vimeo-videos)
> 
> Anyhow, you know the feature the best.

This is a good point as it seems we could use VideoJS for this.  I think that we want to use the vendor snippets like we do for YouTube as this really seems to be more the expected behaviour.  We could consider adding support for VideoJS if there seems like there is a real demand for this.

VideoJS is the fall-back if we don't recognize the URL as being mapped to an existing vendor snippet.

**Comment by Joda66** [comment]
Thanks, @allenmanning, for your response.

I´m selection "Hide from Vimeo" and also disable sharing for my videos, as I want only a group of selected students to work on those. This worked fine in the past, I copied the generated link not from the sharing icon you show in your screenshot, but from the sharing button in the dialog where I can customize the settings.

<img width="1345" alt="Bildschirmfoto 2023-05-04 um 15 16 19" src="https://user-images.githubusercontent.com/32894954/236216062-2dfbc98f-0e72-4fac-9446-92ceffd0cce8.png">

A few days ago Vimeo changed something here and is informing the user, the "hide from Vimeo" will be depreciated.
However, the created links still work fine.

When I create a new video an prepare it for sharing, the "Hide from Vimeo"-Option has been replaced by the "Unlisted" option an the created links show the new pattern: 
https://vimeo.com/823137111/7da580d79b?share=copy

<img width="1345" alt="Bildschirmfoto 2023-05-04 um 15 19 28" src="https://user-images.githubusercontent.com/32894954/236216838-b9b4b896-3a29-4727-96e3-ae314c70210c.png">

Thanks for looking into the topic. 
In the meantime I´m uploading to youtube which works fine, but I wanted to present my videos without ads, when it is  stopped.

**Comment by Joda66** [comment]
Thanks, @cderv for your reply!

The link I get when klicking on the link-icon is
https://vimeo.com/823137111/7da580d79b?share=copy

A workaround (that is also recommended for wordpress in the article you provided) is embedding html. This works fine with the code, that vimeo is providing, but obviously, it is not the solution we are looking for.

**Comment by cderv** [comment]
> The link I get when klicking on the link-icon is

So this link seems better, isn't it ? does it work with the video shortcode ? 

> A workaround (that is also recommended for wordpress in the article you provided) is embedding html.

The video shortcode is supposed to write this specific HTML code for you based on the link you are passing to the shortcode.

**Comment by Joda66** [comment]
Thx @cderv for your reply.

It is strange, rendering resulted in the "No video source specified for video shortcode" - error yesterday a this morning, but not it renders without complaints. However, the video is not displayed.

In the screenshot I tried shortcode (results in video not found), html-embedding (this works) and publishing a video via shortcode that is not unlisted. This works also. So I assume, the problem could be the "privacy key" which is added to links for unlisted videos?

![Bildschirmfoto 2023-05-04 um 18 15 30](https://user-images.githubusercontent.com/32894954/236265282-36ef408d-1b4b-48e7-81b7-a7d426bd29ad.jpg)

**Comment by cderv** [comment]
Possibly related to privacy hash yes. 

FWIW the link `vimeo.com/823137111/7da580d79b?share=copy` gives me page not found on my side. What does it get you when you click on it ? 

Possibly related to 
> If your video has the privacy setting "Hide from Vimeo," viewers will be able to watch your video embedded on another website, but the Vimeo.com video page will only be visible to you (as the video owner)

It is possibly that for unlisted video, one need to use the specific url with `?h=` 

If this url `vimeo.com/823137111/7da580d79b?share=copy` is valid from vimeo share button, I don't know if we can make a rule to extract the part after / and consider it the hash to put after `?=` when building the embed html part. 

Our vimeo builder is here
https://github.com/quarto-dev/quarto-cli/blob/07931d0351001cf3c91f5228a4d03f411733c4e2/src/resources/extensions/quarto/video/video.lua#L115-L134
and we build the iframe by inserting the video link to src. If you use video shortcode with the same url as you have in embed test then it should work. 

So it seems some special treatment needs to be done for unlisted video - but can we know for sure this is unlisted ? Is this `https://vimeo.com/<video_id>/<privacy_hash>` really a pattern ? I can't find the spec.

**Comment by Joda66** [comment]
The link which does not work for you is fine at my account, because I'm logged in to Vimeo.
It is according to the description of Vimeo, that it does not work at your computer, because it should be valid for embedding only, according to the description of Vimeo, but not for sharing.
Following your hint and replacing the privacy hash
**/7da580d79b** 
with the code used in the embedding from Vimeo
**?h=7da580d79b**
finally worked!

Thanks a lot for this idea.
Would be great, if the shortcode could cope with this matter in the future.
Thx, Markus

**Comment by allenmanning** [comment]
Thanks @cderv and @Joda66 for the research and additional information.
