### ISSUE TITLE
Pandoc filters are not working anymore with quarto

### ISSUE THREAD

**Issue by FabienSe** [quarto-dev/quarto-cli#5392]
### Bug description

I was using quarto with a filter for pandoc, it was working great but it is not working anymore.
I am working on a custom filter developed with [panflute](https://github.com/sergiocorreia/panflute) to render plantuml diagram in image. A library used to develop pandoc filter with python.
A similar filter can be found [here](https://github.com/timofurrer/pandoc-plantuml-filter). I was trying to improve it.
I got the same error with this filter too.

I was using it with the `filters` parameter like this in a `index.qmd` file:
```yaml
    ---
    execute:
      echo: false
    pagination_next: null
    filters:
      - custom-filter
    editor:
      render-on-save: true
    ---
    
    # Welcome for fun
    
    ```plantuml
    @startuml
    actor "User" as user
    @enduml
    ```
```
_This file is in a quarto project to render it in a docusaurus website._


The code block was rendered into image by my custom filter. I assume the filter was passed to pandoc directly because the filter is working great with `--filter` of pandoc cli.

Now I got the following error:
```console
> quarto preview /home/user/project/template_docs/docs/index.qmd --no-browser --no-watch-inputs
pandoc 
  to: >-
    markdown_strict+raw_html+all_symbols_escapable+backtick_code_blocks+fenced_code_blocks+space_in_atx_header+intraword_underscores+lists_without_preceding_blankline+shortcut_reference_links+autolink_bare_uris+emoji+footnotes+gfm_auto_identifiers+pipe_tables+strikeout+task_lists+tex_math_dollars+pipe_tables+tex_math_dollars+header_attributes+raw_html+all_symbols_escapable+backtick_code_blocks+fenced_code_blocks+space_in_atx_header+intraword_underscores+lists_without_preceding_blankline+shortcut_reference_links
  output-file: index.md
  standalone: true
  default-image-extension: png
  wrap: none
  html-math-method: webtex
  
metadata
  pagination_next: null
  editor:
    render-on-save: true
  
Error running filter /opt/quarto/share/filters/main.lua:
Error running filter /home/user/project/template_docs/docs/custom-filter:
Could not find executable /home/user/project/template_docs/docs/custom-filter
stack traceback:
        /opt/quarto/share/filters/main.lua:4026: in function </opt/quarto/share/filters/main.lua:4005>
        [C]: in ?
        [C]: in method 'walk'
        /opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        /opt/quarto/share/filters/main.lua:449: in local 'callback'
        /opt/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/main.lua:495: in function </opt/quarto/share/filters/main.lua:476>
stack traceback:
        /opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        /opt/quarto/share/filters/main.lua:449: in local 'callback'
        /opt/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/main.lua:495: in function </opt/quarto/share/filters/main.lua:476>
```

Operating system : WSL on Ubuntu 20.04.6 
Quarto check:
```
> quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /home/user/.pyenv/versions/3.11.3/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
Thanks for the report. `custom-filter` is a python script right ? Did you try adding an extension ? 

I pinged @cscheid who knows more about our filter execution layer.

**Comment by cscheid** [comment]
Note the error message:

`Could not find executable /home/user/project/template_docs/docs/custom-filter`

Panflute should work (there are a number of caveats wrt custom AST nodes though); the issue here is that we are not finding the filter where we expect to, and we no longer resolve arbitrary executable files (like pandoc does). 

We can reconsider that decision, but the easiest way for you to solve it right now is to add (eg) a python script to the path that then calls the files on your path.

**Comment by cscheid** [comment]
> This was my missing part. I wasn't ware of that change. Thanks for the clarification

We have to wrap user filters so they can handle custom AST nodes, and that requires special code. The last time I thought through this I came to the conclusion that it would be hard to do this portably in Lua, but I could be wrong.

I also think that allowing a filter from the user's PATH goes against quarto's philosophy of keeping everything important in the project source, so I'm actually happy with this new restriction. (Otherwise, the result of rendering this file would be non-obviously dependent on the surrounding environment.)

**Comment by cderv** [comment]
> I would like to use Quarto extension but I did not see how to use non-lua filter in the linked [documentation](https://quarto.org/docs/extensions/filters.html#filter-extensions).

Yes we don't document it with example, but we say 

> You can write Pandoc filters using Lua (via Pandoc’s built-in Lua interpreter) or using any other language using a JSON representation of the Pandoc AST piped to/from an external process. We strongly recommend using Lua Filters

So I am assuming we support already other type of filter. @dragonstyle do we support non lua filter in extension ? Do we have an example somewhere ,

**Comment by cscheid** [comment]
> So I am assuming we support already other type of filter. @dragonstyle do we support non lua filter in extension ? Do we have an example somewhere ?

Extensions won't know the difference, this distinction happens entirely inside of the Lua filter chain now. ([quartodoc](https://github.com/machow/quartodoc) used to work like that but I helped those folks convert it to a Lua filter exactly because of these limitations.)

**Comment by cderv** [comment]
> Is it possible to do stuff like create folder or file, call external command line in Lua ?

Yes it is possible Look at our doc https://quarto.org/docs/extensions/lua-api.html and the other linked doc 

* You can access Lua library like the `io` or `file` one 
   > The I/O library provides two different styles for file manipulation: one uses implicit file handles and the other explicit handles.

* You can access Pandoc API also which as a [`pandoc.pipe()` function to run some program](https://pandoc.org/lua-filters.html#pandoc.pipe)

 * We also expose with Quarto a specific LUA API for better integration with Quarto feature. 

In addition to Quartodoc example, here is another:  [shinylive ](https://github.com/quarto-ext/shinylive) [calls a custom program (from a python package) from within the LUA filter](https://github.com/quarto-ext/shinylive/blob/main/_extensions/quarto-ext/shinylive/shinylive.lua#L4-L12)

You can do a lot with Lua !

**Comment by stefanv** [comment]
I can confirm that this is a backward incompatible change in Quarto that has not been advertised. We had filters installed via a Python package, and that simply had to be on the path. Those filters used to work, but no longer do.

We will also follow the Python wrapper approach for now, but this is perhaps a common enough use case that it warrants a section in the docs?

**Comment by matthew-brett** [comment]
Just to say - the ability to use Panflute for filters was a big sell us, as Python programmers using Quarto.   It made it easy and pleasant to switch from e.g. Jupyter-book.   Forcing the use of Lua would be a significant barrier to uptake, I suspect - because filters are so important to customising output.

**Comment by cscheid** [comment]
Let me be clear: you can 100% still use panflute. The only change is that binaries on your path are no longer interpreted as JSON filters. All you need to do is provide a `filter.py` file that does the processing you want.

**Comment by albert-ying** [comment]
It also breaks the zotero.lua, which is a popular lua filter that allows to link citation to zotero in Word output.

Yaml:
```
---
title: '****'
author: 'NA'
format:
  docx:
    reference-doc: manuscript_style.docx
bibliography: /Users/A.Y/OneDrive - Harvard University/My Library.bib
csl: /Users/A.Y/Zotero/styles/nature.csl
filters: 
 - zotero.lua
---

```

```
Error running filter /Applications/quarto/share/filters/main.lua:
zotero.lua:70: attempt to index a nil value (global '_G')
stack traceback:
        [C]: in upvalue 'orig_require'
        [string "..."]:1353: in function 'require'
        zotero.lua:1716: in local 'chunk'
        /Applications/quarto/share/filters/main.lua:4073: in local 'callback'
        [string "..."]:1789: in function <[string "..."]:1787>
        (...tail calls...)
        /Applications/quarto/share/filters/main.lua:368: in function 'make_wrapped_user_filters'
        /Applications/quarto/share/filters/main.lua:15395: in main chunk
```

See also this issue https://github.com/retorquere/zotero-better-bibtex/issues/2497

Any idea how could I make it work again?

**Comment by cscheid** [comment]
That looks like a different problem. Can you open a new issue?

**Comment by matthew-brett** [comment]
I opened a new issue for another `nil` error above - maybe related, maybe not:

https://github.com/quarto-dev/quarto-cli/issues/5461

**Comment by ChrisJefferson** [comment]
Is there an easy / documented way to wrap an executable pandoc filter?

I want to use the filter `pandoc-katex`, which is a rust program. I can run it by adding `--filter pandoc-katex` to the render command line, but I could figure out how to put it in `_extensions`, or if that's possible.

**Comment by cscheid** [comment]
@ChrisJefferson Interesting. Did you try just adding `pandoc-katex` to your extension filter declaration (instead of `foo.lua`). The following syntax works for sure in single documents:

````
---
title: Test Python Filter
filters:
  - type: json
    path: behead.py
---

## This is a test

## This should be em
````

And I think we use the same codepath in extensions. Here, `behead.py` is a generic `+x` file that we run through a JSON filter.

**Comment by ChrisJefferson** [comment]
It works if I write `path: _extensions/pandoc-katex`, or if I put `pandoc-katex` in the same directory as my source and run `pandoc-katex`. In fact (and this is what I'll use for now, unless it's horrible, the easiest thing to write is:

```  - _extensions/pandoc-katex```

Then put a symlink to `pandoc-katex` in my `_extensions` directory.

I'd prefer not to put filters in the same directory as my `.qmd` files, but it does work.

**Comment by cscheid** [comment]
Hm. This looks like a bug on our side.

**Comment by jonassmedegaard** [comment]
Do I understand it correctly, that the following should work currently for Rust filters?:
```YAML
---
title: Test Rust Filter
filters:
  - _extensions/pandoc-katex
---
Foo
```

I ask because it is unclear from the conversation above it that was the exact syntax proposed, and also if it was confirmed working or not. And because when I try that syntax with [pandoc-filter-diagram](https://gitlab.com/larswirzenius/pandoc-filter-diagram) it fails like this:
````
FATAL (/opt/quarto/share/filters/main.lua:3369) An error occurred:
Could not run /home/jonas/Projects/RUC/PROJECTS/piller/report/../_extensions/pandoc-filter-diagram as a JSON filter.
Please make sure the file exists and is executable.

Did you intend 'pandoc-filter-diagram' as a Lua filter in an extension?
If so, make sure you've spelled the name of the extension correctly.

The original Pandoc error follows below.
Error running filter /home/jonas/Projects/RUC/PROJECTS/piller/report/../_extensions/pandoc-filter-diagram:
Filter returned error status 101
```

**Comment by ChrisJefferson** [comment]
To be clear the following message is **not recommend quarto practice**, I'm just some person, getting my filter working. Long term, there will be better ways of doing this.

In your situation, I'm assuming you've globally installed `pandoc-filter-diagram`, you can check that by running `which pandoc-filter-diagram`, on my computer I get:

```
> which pandoc-filter-diagram
/home/caj/.cargo/bin/pandoc-filter-diagram
```

You can pop a link to it into the current directory (`ln -s` = make symbolic link, `$(...)` puts the result of that command here, you could cut+paste it instead if you like).

```
ln -s $(which pandoc-filter-diagram) ./pandoc-filter-diagram
```

Then if you just refer to it, like this:

```
---
title: "Example"
filters:
  - pandoc-filter-diagram
---
## Heading
```

The `_extensions`, is for neatness I did:

```
mkdir _extensions
ln -s $(which pandoc-filter-diagram) _extensions/pandoc-filter-diagram
```

Just so the pandoc filter diagram link was in a subdirectory, rather than mixed in with my `.qmd` files.

**Comment by cscheid** [comment]
I really don't think there's a bug here; if there is one, I'd like to ask folks to open a new issue. 

Here's a specific example of using a binary inside a Quarto filter extension:

````
$ cat example.qmd
---
title: "Issue-5392 Example"
filters:
  - issue-5392
---

## Heading

This filter replaces the entire document with a pre-computed "Foo. This is silly." document.
$ cat _extensions/issue-5392/_extension.yml
title: Issue-5392
author: Carlos Scheidegger
version: 1.0.0
quarto-required: ">=99.9.0"
contributes:
  filters:
    - an_executable_filter
$ cat _extensions/issue-5392/an_executable_filter
#!/usr/bin/env python3

import sys
sys.stdout.write('{"pandoc-api-version":[1,23,1],"meta":{},"blocks":[{"t":"Header","c":[2,["foo",[],[]],[{"t":"Str","c":"Foo"}]]},{"t":"Para","c":[{"t":"Str","c":"This"},{"t":"Space"},{"t":"Str","c":"is"},{"t":"Space"},{"t":"Str","c":"silly."}]}]}')
$ quarto render example.qmd --to md -o -
pandoc -o /var/folders/nm/m64n9_z9307305n0xtzpp54m0000gn/T/quarto-session1a14ffba7d4ce1c0/c58737780b146d7f/281a41bec75ca8b3.md
  to: >-
    markdown_strict+raw_html+all_symbols_escapable+backtick_code_blocks+fenced_code_blocks+space_in_atx_header+intraword_underscores+lists_without_preceding_blankline+shortcut_reference_links
  standalone: true
  default-image-extension: png

metadata
  title: Issue-5392 Example



## Foo

This is silly.
````

In this example, `an_executable_filter` has 755 permissions so it can be executed. Quarto is successfully finding that binary inside the extension folder and running it.
