### ISSUE TITLE
Update publisher in our bundles 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#5398]
This came up in https://github.com/microsoft/winget-pkgs/pull/103701#discussion_r1183721670 where it seems our wix bundle still have RStudio as publisher. 

https://github.com/quarto-dev/quarto-cli/blob/4a4e9f1226df1f6f994ac084b226150966bc7aa5/package/src/windows/quarto.wxs#L4

This will show in the Windows install, and also prevent updating manifest for Windows bundle on winget

Do think there is other places @dragonstyle to update ? 

Probably for other installer too 
https://github.com/quarto-dev/quarto-cli/blob/4a4e9f1226df1f6f994ac084b226150966bc7aa5/package/src/linux/installer.ts#L82
https://github.com/quarto-dev/quarto-cli/blob/4a4e9f1226df1f6f994ac084b226150966bc7aa5/package/src/linux/installer.ts#L108

Thanks to @dpprdan finding all this 

Too bad I did not knew about that before the release... 😞

**Comment by dragonstyle** [comment]
Good one.

Also in our linux installer:

`package/src/linux/installer.ts`
`package/src/windows/quarto.wxs` (as noted)

Authors of extensions in `quarto-ext` should also be reviewed

**Comment by cderv** [comment]
> Authors of extensions in quarto-ext should also be reviewed

I updated all the copyright in our quarto-extension, and modified some authors field that were at RStudio.

**Comment by cderv** [comment]
FWIW, `.wxs` has been updated by community PR https://github.com/quarto-dev/quarto-cli/pull/5525
