### ISSUE TITLE
Inline Python variable rendering

### ISSUE THREAD

**Issue by ropeladder** [quarto-dev/quarto-cli#5401]
Hi, we are looking at using Quarto but the ability to render Python variables into markdown text, using something similar to the `` `r variable` `` syntax is very important for us, as we have lots of titles and captions with auto-updating dates. Unfortunately, per [this recent comment](https://community.rstudio.com/t/how-can-i-use-inline-code-in-a-quarto-document/160575/3), it's not currently possible.

Is this on the roadmap, or are there any recommended workarounds? (shortcodes don't seem to be a good option because the variables are computed at runtime)

**Comment by mcanouil** [comment]
Depending on the metadata you wish to modify, you can generate the yaml from a code cell[^1].

[^1]: I can't provide an example right now though.

**Comment by cscheid** [comment]
It's on the roadmap. Hopefully we'll land it in 1.4.
