### ISSUE TITLE
Confluence Spaces with "." returns ERROR: Invalid Confluence parent URL:

### ISSUE THREAD

**Issue by smithbn** [quarto-dev/quarto-cli#5405]
### Bug description

- I am trying to publish a Quatro document to my personal space in Confluence. 
- When I provide the parent URL for my personal space, it returns "ERROR: Invalid Confluence parent URL:" My personal space key is "~brian.smith". 
- I tried removing the "." and using a parent url with the space "~briansmith" and the command gets to "[✓] Verifying...", but fails because of course that space doesn't actually exist. 
- macOS 13.2.1 (22D68)
- RStudio IDE: Version 2023.03.0+386

The .qmd is just:
```
---
title: "Confluence Document Test"
author: "Brian Smith"
format: html-confluence
---
## Overview
My text will go here. 
---
```
quarto check:

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.25
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.1.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.1/Resources/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by smithbn** [comment]
Full Parent Page URL: https://basis.atlassian.net/wiki/spaces/~brian.smith/pages/126583477

**Comment by allenmanning** [comment]
Thank you for finding and posting this bug.  

I'm not able to reproduce although I can attempt a patch from the unit tests.

I'm curious to know how the space was setup to contain dots?

![image](https://user-images.githubusercontent.com/674792/236145264-0339f710-c29d-4f95-9072-3859c583c3fe.png)

![image](https://user-images.githubusercontent.com/674792/236146294-9295bb50-ef54-4e8a-b78b-48e0870477cf.png)

**Comment by smithbn** [comment]
Thank you @allenmanning. Originally we were on an older version of Jira server, but migrated this year to cloud. So perhaps that could have something to do with why our space keys don't match the key requirements you posted? Here's a screenshot of my current space settings:
<img width="950" alt="Screenshot 2023-05-04 at 9 25 43 AM" src="https://user-images.githubusercontent.com/1291718/236237658-29edd582-e4a4-4e86-aabb-0ff574a10cd3.png">
