### ISSUE TITLE
`quarto --help` provides incorrect commands

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#5421]
`create-project` removed
`install` out of date description
`use` missing
`remove` missing
`tools` missing
`update` missing
`uninstall` missing

**Comment by VladimirAlexiev** [comment]
Two adjustments from #5675
- `tools` is now present
- `list` is missing

**Comment by mcanouil** [comment]
I am dropping this here: currently there are two commands to install tinytex, but users might get confused as in _quarto-web_ both are used.
So, what's the correct/preferred command: `quarto install tool tinytex` or `quarto install tinytex`?

There are other commands in _quarto-web_ that were superseded/deprecated such as `quarto install extension` in favour of `quarto add`, but without a clear view of the status of the commands, documentation can't really be updated/corrected.

**Comment by dragonstyle** [comment]
We should be documenting the newer/simpler syntax of `quarto install tinytex` and still supporting the old syntax. I like the idea of adding a warning / notice when using an 'out of date' command.
