### ISSUE TITLE
Swapping between Source and Visual Editor breaks citations

### ISSUE THREAD

**Issue by tim-newans** [quarto-dev/quarto-cli#543]
I've started out writing out a book and swap relatively frequently between the source and visual editors. However, currently the citations don't seem to be processing correctly in visual editor. Here is my workflow:

Image 1 is what I have currently written in source:

![Pic 1](https://user-images.githubusercontent.com/69664059/161872933-01c62410-b821-4377-8d1a-4958dc014b38.PNG)

This renders correctly as seen in Image 2:

![Pic 2](https://user-images.githubusercontent.com/69664059/161872971-42edf411-6837-46ef-a635-1c87468211bb.PNG)

I swap to the visual editor and see this:

![Pic 3](https://user-images.githubusercontent.com/69664059/161873007-d0b1fd47-6d42-4d42-b28b-4cb9239625de.PNG)

And then when I swap back to the source editor it has reformatted it as seen here:

![Pic 4](https://user-images.githubusercontent.com/69664059/161873041-faacaf89-3fc0-4843-9f31-bfbf2e05bef7.PNG)

So then all the citations don't work on rendering because of the different backslashes.

Any ideas on what I should be doing in my workflow to prevent this from occuring?

**Comment by dragonstyle** [comment]
I think this is caused by a bug we just recently fixed. See here:

https://github.com/quarto-dev/quarto-cli/discussions/504#discussioncomment-2491915

You could either use the suggested YAML change to temporarily work around the escaping issue (as suggested in the thread), or I believe the latest daily build of 'Prairie Trillium' has the fixes here:

https://dailies.rstudio.com/rstudio/prairie-trillium/

(if you're comfortable running a daily build)

Sorry for the issue!

**Comment by tim-newans** [comment]
Oh perfect, sorry I didn't see that issue! That's no worries at all, thanks!!

**Comment by tim-newans** [comment]
It seems after installing the daily build and inserting the YAML change this is still appearing. It is working fine when there is only 1 citation per `[]`; however, when I place a citation with two references (i.e., if there is a `;` within the citation), it escapes the `]` to the citation immediately prior to the double citation and still escapes the `[` for the double citation. Can you think of another YAML change to prevent these escapes?

**Comment by jjallaire** [comment]
Can you provide us with a minimal example that exhibits this behavior?

**Comment by tim-newans** [comment]
```
---
title: "Example Citation"
---
[@ref1] [@ref2; @ref3]
```

If you open this in Source, then change to Visual, and go back to Source it becomes:

```
---
title: "Example Citation"
---

[@ref1\] \[@ref2; @ref3]
```

**Comment by jjallaire** [comment]
Okay, thank you! I can reproduce that. We will fix ASAP and report back.
