### ISSUE TITLE
Multiple tables produced by Python in a single code cell not showing

### ISSUE THREAD

**Issue by sun123zxy** [quarto-dev/quarto-cli#5432]
### Bug description

[The authoring guide on tables](https://quarto.org/docs/authoring/tables.html#computations) provided an example producing multiple tables in R in a single code cell. However, when using Python to do so, only the last table shows in the output, with its subcaption wrongly assigned to be the first one stated in `tbl-subcap`.

Here's a minimal example, modified from the code provided in the guide mentioned above.

`````md
---
title: "Test"
---

```{python}
#| label: tbl-planet-measures
#| tbl-cap: Planets
#| tbl-subcap: 
#|   - "Planets"
#|   - "Satellites"
#| layout-ncol: 2
#| echo: false

from IPython.display import Markdown
from tabulate import tabulate
table1 = [["Earth",6371,5973.6],
          ["Mars",3390,641.85]]
table2 = [["Moon",1737,73.5]]
Markdown(tabulate(
  table1, 
  headers=["Planet","R (km)", "mass (x 10^29 kg)"]
))
Markdown(tabulate(
  table2, 
  headers=["Planet","R (km)", "mass (x 10^29 kg)"]
))
```
`````

In contrast, multiple figures work well in Python. Here's a comprehensive qmd file illustrating the issue. [index.md](https://github.com/quarto-dev/quarto-cli/files/11404725/index.md)

![snap](https://user-images.githubusercontent.com/44888975/236419685-38eaf7c3-a69f-46d1-a43e-7475c5945bf5.jpg)

Apologize if I've missed something obvious. Thanks.

---

Quarto version: 1.3.340

system: Windows 11

Quarto check:
```
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.340
      Path: C:\Program Files\Quarto\bin
      CodePage: 936

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.8.13 (Conda)
      Path: C:/Users/sun123zxy/.conda/envs/data/python.exe
      Jupyter: 4.11.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
Does your python code as is output several tables in single cell if you use `.ipynb` ?

I think you need to use the `display` function from IPython - https://ipython.readthedocs.io/en/stable/interactive/plotting.html

````markdown
---
title: "Test"
---

```{python}
#| label: tbl-planet-measures
#| tbl-cap: Planets
#| tbl-subcap: 
#|   - "Planets"
#|   - "Satellites"
#| layout-ncol: 2
#| echo: false

from IPython.display import Markdown, display
from tabulate import tabulate
table1 = [["Earth",6371,5973.6],
          ["Mars",3390,641.85]]
table2 = [["Moon",1737,73.5]]
display(Markdown(tabulate(
  table1, 
  headers=["Planet","R (km)", "mass (x 10^29 kg)"]
)))
display(Markdown(tabulate(
  table2, 
  headers=["Planet","R (km)", "mass (x 10^29 kg)"]
)))
```

````

![image](https://user-images.githubusercontent.com/6791940/236439382-02807967-6d8d-4749-9b78-c7cff9d8eff5.png)

Hope it helps

**Comment by sun123zxy** [comment]
> Does your python code as is output several tables in single cell if you use `.ipynb` ?
> 
> I think you need to use the `display` function from IPython - https://ipython.readthedocs.io/en/stable/interactive/plotting.html See also this [IPython notebook example](https://nbviewer.org/github/ipython/ipython/blob/1.x/examples/notebooks/Part%205%20-%20Rich%20Display%20System.ipynb)
> 
> Here is with your code
> 
> ```gfm
> ---
> title: "Test"
> ---
> 
> ```{python}
> #| label: tbl-planet-measures
> #| tbl-cap: Planets
> #| tbl-subcap: 
> #|   - "Planets"
> #|   - "Satellites"
> #| layout-ncol: 2
> #| echo: false
> 
> from IPython.display import Markdown, display
> from tabulate import tabulate
> table1 = [["Earth",6371,5973.6],
>           ["Mars",3390,641.85]]
> table2 = [["Moon",1737,73.5]]
> display(Markdown(tabulate(
>   table1, 
>   headers=["Planet","R (km)", "mass (x 10^29 kg)"]
> )))
> display(Markdown(tabulate(
>   table2, 
>   headers=["Planet","R (km)", "mass (x 10^29 kg)"]
> )))
> ```
> ```
> 
> ![image](https://user-images.githubusercontent.com/6791940/236439382-02807967-6d8d-4749-9b78-c7cff9d8eff5.png)
> 
> Hope it helps

Ahh I see, in `.ipynb` only the last output is rendered if `display()` is not used.

I'm not quite familiar with Jupyter, so blindly following the guide results in this fault. 😂 I guess an update on the guide (to use `display()` in code) to avoid this kind of misuse is OK?

**Comment by cwickham** [comment]
Closing documentation issue as the example was made clearer in: https://github.com/quarto-dev/quarto-web/commit/58d5601cadecdc6c7fd87e4eace9f7af6bf1837c
