### ISSUE TITLE
Add Posit Cloud as a publishing provider

### ISSUE THREAD

**Issue by mslynch** [quarto-dev/quarto-cli#5436]
Posit Cloud is adding support for publishing static content. `quarto publish` should support publishing through Cloud.

**Comment by allenmanning** [comment]
@mslynch Many thanks for posting this.  Is there some API documentation that you can add as a link to this issue?

**Comment by mslynch** [comment]
@allenmanning The hosted apps team was planning on handling this work (either myself, @omar-rs, or @m--). There's no public documentation for the API, but we do have some internal API docs that aren't especially helpful without a lot of background knowledge, if you're interested.

**Comment by cscheid** [comment]
Fixed in https://github.com/quarto-dev/quarto-cli/commit/f65180a75e1cf2996328cd51cb4fd5d02d391511
