### ISSUE TITLE
 decouple package working dir from `package` path

### ISSUE THREAD

**Issue by msarahan** [quarto-dev/quarto-cli#5444]
### Bug description

In https://github.com/quarto-dev/quarto-cli/commit/9cf8ffa5eb5cfd5922eb7949ca17fd4325db797f#diff-714357551c8de50d816a92a684e8370e04f8b18c7441f311e4a81a1c2eb28132,

the dist dir was basically replaced with a new notion of a package working dir. This was disruptive to the conda recipe, since setting the QUARTO_DIST_DIR was how we told `quarto-bld` to put stuff into the conda package. Unfortunately, we can't readily adjust the conda recipe to the new pattern, because the QUARTO_PACKAGE_PATH that sets the pkgWorkingBase is used for both internal scripts and for what conda wants to be an external path.

Now conda/quarto can address this maybe 2 ways:

1. conda can patch https://github.com/quarto-dev/quarto-cli/commit/9cf8ffa5eb5cfd5922eb7949ca17fd4325db797f#diff-714357551c8de50d816a92a684e8370e04f8b18c7441f311e4a81a1c2eb28132R65 such that we can set an env var instead of just extending QUARTO_PACKAGE_PATH

2. Perhaps a better long-term solution is to make a new installer script, similar to https://github.com/quarto-dev/quarto-cli/blob/main/package/src/macos/installer.ts, that doesn't create a tarball, but instead just copies files into OUT_DIR (minus vendored stuff that conda provides in other packages). Conda recipe would then need to call this new command from bld.ts, like https://github.com/quarto-dev/quarto-cli/blob/main/package/src/bld.ts#L93

Either way, we'll be happy to prototype this in the conda recipe at https://github.com/conda-forge/quarto-feedstock/pull/7

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
I added the command `./quarto-bld make-installer-dir` based upon the patch in the referenced PR. Please feel free to use this if helpful and thank you for providing the simple code and template!
