### ISSUE TITLE
Rendering chunk which reads a file (or has a cache=true) fails with long paths (MAX_PATH)

### ISSUE THREAD

**Issue by sda030** [quarto-dev/quarto-cli#5457]
### Bug description

Not sure if this is an Rstudio or Quarto issue.
Setup:
This issue persists in 
* Quarto 1.4.37
* Rstudio 2023.03.0 Build 386 
* R 4.3.0
* Windows 11 (all updated)
* Windows 11 has been set to accept long paths (confirmed by checking registry key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled equals 1
* I suspect {fs} involved somehow, which has version 1.6.2

Problem: 
Rendering a chunk (pressing green triangle button) or running "manually" with Ctrl+Enter fails for reading in a file (e.g. `readRDS()`) if filepath is longer than 260 (cf. MAX_PATH).
Error message does not direct the user towards this cause, but _moving files to a lower working directory solves the problem_.
```
Error in gzfile(file, "rb") : cannot open the connection
Warning: cannot open compressed file 'Behov omkring kvalitetsutvikling/uni_cat_prop_plot/I_hvilken_grad_opplever_dere_at_følgende_prøver__undersøkelser__verktøy_og_datakilder_er_nyttige_i_d.rds', probable reason 'No such file or directory'Error in gzfile(file, "rb") : cannot open the connection
```
Interestingly, pressing Render or using quarto::quarto_render _does_ work nevertheless. Though it can be cumbersome without the  "inline preview" feature (which is otherwise awesome). Moreover, the problem is an even greater issue when using 
```
execute:
  cache: true 
```
since it adds the long hash to the filename. 

``` r
long_path <- paste0(tempdir(), "/sdfsdfsdfwfhwebfwhjebfewhjbwhjbfehbfjewh/smnfbkjebfwhjefbwefbewhj/smbfehbfsehmsbemfhbsemhs/skfbjhebfwhjebfwhjebfewhe/mhesbmehfbmhsbmhebf/sjefbshembfmshfb/msbfeshef/bhsfbsemhfbsmhfesb/mshfbshmesbfsm/sbefhbsmhebfmhesb/mshbfsmhebfesm/hbsmfsmehfbs")
dir.create(long_path, recursive = TRUE)
saveRDS(letters, paste0(long_path, "test_obj.rds"))
cat(paste0('---\nformat: html\n---\n\n```{r}\nx <- readRDS("test_obj.rds")\nx\n```'), file=paste0(long_path, "/test.qmd"))
rstudioapi::documentOpen(paste0(long_path, "/test.qmd"))
#> Error: RStudio not running
# Run chunk manually
```

<sup>Created on 2023-05-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<sup>Created on 2023-05-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

quarto check:
Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.1: OK
Version: 1.4.37
      Path: C:\Users\py128\AppData\Local\Programs\Quarto 1.4.37\bin
      CodePage: 1252
Checking Python 3 installation....(None)
      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/
Version: 4.3.0
      Path: C:/PROGRA~1/R/R-43~1.0
      LibPaths:
        - C:/Users/py128/AppData/Local/R/win-library
        - C:/Program Files/R/R-4.3.0/library
      knitr: 1.42
      rmarkdown: 2.21
(everything else says OK)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
@sda030 I cannot even create the temporary directory as it is too long on my system 

````r
> long_path <- paste0(tempdir(), "/sdfsdfsdfwfhwebfwhjebfewhjbwhjbfehbfjewh/smnfbkjebfwhjefbwefbewhj/smbfehbfsehmsbemfhbsemhs/skfbjhebfwhjebfwhjebfewhe/mhesbmehfbmhsbmhebf/sjefbshembfmshfb/msbfeshef/bhsfbsemhfbsmhfesb/mshfbshmesbfsm/sbefhbsmhebfmhesb/mshbfsmhebfesm/hbsmfsmehfbs")
> dir.create(long_path, recursive = TRUE)
Warning message:
In dir.create(long_path, recursive = TRUE) : cannot create dir
'C:\Users\chris\AppData\Local\Temp\RtmpIr8hS6\sdfsdfsdfwfhwebfwhjebfewhjbwhjbfehbfjewh\smnfbkjebfwhjefbwefbewhj\smbfehbfsehmsbemfhbsemhs\skfbjhebfwhjebfwhjebfewhe\mhesbmehfbmhsbmhebf\sjefbshembfmshfb\msbfeshef\bhsfbsemhfbsmhfesb\mshfbshmesbfsm\sbefhbsmhebfmhesb',
reason 'No such file or directory'
````

In R console it says "Path too long"

So I really thing this is some limitation with R directly.

**Comment by sda030** [comment]
@cderv, have you set your system to accept LongPathEnabled, per my 5th point above? I have no issue with R in general.

**Comment by cderv** [comment]
Oh sorry I missed that 😓 🤦  Let me check again then. 

But probably related to RStudio IDE itself as you described it not working in interactive chunk mode only.

**Comment by onurcanbektas** [comment]
I have the same issue as well.

**Comment by cderv** [comment]
Coming back to this, I still cannot reproduce. 

* `LongPathEnabled` is set to 1 in registry
* Using current dev quarto (1.4)
* Using daily version of RStudio 
	````r
	> rstudioapi::versionInfo()$long_version
	[1] "2023.12.0-daily+234"
	````
* Using latest R package
	```r
	> packageVersion("rmarkdown")
	[1] ‘2.25’
	> packageVersion("knitr")
	[1] ‘1.44’
	```

**Comment by sda030** [comment]
Hm, now I am unable to reproduce the error myself on the most recent dev quarto, seems fixed somehow! Let's close this in an effort to reduce the vast ocean of issues open :)
