### ISSUE TITLE
multiline caption failure

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#5461]
### Bug description

To reproduce:

```
git clone https://github.com/matthew-brett/test-quarto-2
cd test-quarto-2
quarto render
```

This gives error:

```
Error running filter /Users/mb312/dev_trees/quarto-cli/src/resources/filters/main.lua:
...ees/quarto-cli/src/resources/filters/./common/tables.lua:107: attempt to call a nil value (method 'clone')
...
```

The page generating the error consists only of:

~~~
```{r}
kableExtra::kable(cars,
            caption = 'Caption
            {#tbl-veh-numbers}')
```
~~~

The error requires the caption to run over more than one line, and to contain the table label.

New issue opened as requested from: https://github.com/quarto-dev/quarto-cli/issues/5392

This is on macOS 13.3.1 on M2.

```
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.1: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/mb312/dev_trees/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.11
      Path: /Users/mb312/.virtualenvs/resampling-with/bin/python3
      Jupyter: 5.3.0
      Kernels: python3, ir

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /opt/homebrew/Cellar/r/4.3.0_1/lib/R
      LibPaths:
        - /Users/mb312/Library/R/arm64/4.3/library
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.0_1/lib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Thanks for the report! This is now fixed on `main` and should be available in the next pre-release.

@dragonstyle https://github.com/quarto-dev/quarto-cli/commit/b8730e5df33f576829d33cfbe3373a6e78c5fe65 is a simple fix and good backport candidate.

**Comment by cscheid** [comment]
This is now cherry-picked into our `v1.3` hotfixes branch.
