### ISSUE TITLE
Is code annotations in call out blocks supported

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#5485]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5484

<div type='discussions-op-text'>

<sup>Originally posted by **cudawarped** May 10, 2023</sup>
I can use [code annotation](https://quarto.org/docs/authoring/code-annotation.html#annotation-syntax) inside a single [callouts](https://quarto.org/docs/authoring/callouts.html#markdown-syntax) block without any issues, however if I try to use it in a second call outblock it fails.  e.g. the "more addition" annotation is not shown in

````
::: {.callout-tip}
            
Python annotation 1

```{.python}
   1 + 1 # <1>
```
1. addition

:::
            
::: {.callout-tip}
            
Python annotation 2

```{.python}
   1 + 1 # <1>
```
1. more addition

:::
````

</div>

**Comment by cderv** [comment]
I believe this is solved by https://github.com/quarto-dev/quarto-cli/commit/e127a051adbe68ae07f09126c9a1d1e57dea5707 and now working with current pre-release
