### ISSUE TITLE
quarto-view.js won't be build from release

### ISSUE THREAD

**Issue by trap000d** [quarto-dev/quarto-cli#5492]
### Bug description

quarto-cli: latest pre-release (1.4.51 at the time I'm writing this bug description)

O/S: Arch Linux (I'm maintainer of `rstudio-desktop` and `quarto-cli` AUR packages)

Build script src/webui/quarto-preview/build.ts assumes we're inside the git repo. If it runs against the source code from release archive, `git ls-files` returns `fatal: not a git repository (or any of the parent directories): .git` , however the error message gets suppressed. Effectively there is no notification if the mentioned module is not built.

Quick'n'dirty solution to me was to force rebuild quarto-preview:
[quarto-cli-pre-release/force_build_quarto_preview_js.diff](https://github.com/trap000d/aur/blob/master/quarto-cli-pre-release/force_build_quarto_preview_js.diff)

P.S. I've spotted it only because noticed the warning message in RStudio (2023.03.0.386) console: "Can't find quarto-preview.js"

Output of `quarto check`:
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.0.1: OK
      Dart Sass version 1.62.0: OK
      NOTE: Deno version 1.33.0 is too old. Please upgrade to 1.33.1 or later.
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.51
      Path: /usr/lib/quarto-cli/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/lib64/R
      LibPaths:
        - /home/trap000d/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by jjallaire** [comment]
Should be fixed here: https://github.com/quarto-dev/quarto-cli/commit/8d93989f4b057930560d51a305fb4bea21725184

**Comment by trap000d** [comment]
> Should be fixed here: [8d93989](https://github.com/quarto-dev/quarto-cli/commit/8d93989f4b057930560d51a305fb4bea21725184)

Seems it doesn't work. Error is not throwing, only non-zero return code (128), so catch is not triggered. I guess you should check `command.CommandStatus.code` then set `build=true`

**Comment by jjallaire** [comment]
Yikes, thanks again for catching this. Should be finally resolved here: https://github.com/quarto-dev/quarto-cli/commit/59a865f351f92431eca8454124afe4c345517c2f

**Comment by trap000d** [comment]
All good now. Thanks.
