### ISSUE TITLE
CSS selectors for TOC items break when markdown header contains an umlaut

### ISSUE THREAD

**Issue by robfuscator** [quarto-dev/quarto-cli#550]
First of all: I love Quarto, thank you! :partying_face: 

I work on a Quarto website which contains text mostly written in German. There are some headers in articles that contain an _umlaut_ (e.g. __ü__). The TOC does not seem to work properly for those articles, it does not collapse when a graphic is scaled to the page column and it does not update the current location.

On my browser console I get the following error:

```
Uncaught DOMException: Document.querySelector: '#variablen-%C3%BCberpr%C3%BCfen' is not a valid selector
```

I seems to me that my header `# Variablen überprüfen` does not get transformed to a valid CSS selector. I don't know where or how this transformation takes place, but I think there is something wrong.

Tell me if you need more info.

**Comment by robfuscator** [comment]
Sure. At least on my side, it happens here:

- https://kogpsy.github.io/neuroscicomplab_fs22_quarto/pages/chapters/02_importing_data.html

**Comment by dragonstyle** [comment]
Yep, that was perfect, thank you! Fix should be here:

a71714cd9df32bf06bc299596742f50c084aa661

I have a fresh build running now so a release should be available in a few minutes.. Thank you for letting us know about this!

**Comment by robfuscator** [comment]
Wow, that was quick, thank you! :tada: Seems to be fixed for me too.

**Comment by jjallaire** [comment]
Note that CSS selectors support escaping which we could use here. Note also that we have a pandoc compatible version of slugify already in the codebase here: https://github.com/quarto-dev/quarto-cli/blob/main/src/core/pandoc/pandoc-id.ts

**Comment by dragonstyle** [comment]
> ([This](https://kogpsy.github.io/neuroscicomplab_fs22_quarto/pages/chapters/06_signal_detection_ii.html) is the site where it occurs)

I'm not reproducing the issue any longer. I noticed that the page you're seeing the error on was generated using `quarto-0.9.242` (we add a generator tag to the page metadata). Is it possible that you've just not rendered the complete site using the fixed version of Quarto? (This fix should be in releases post build 280).

**Comment by robfuscator** [comment]
Thanks for your response!

I've just rendered the page using `quarto-0.9.282` and published the result (same URL). Sadly, the problem persists.

**Comment by dragonstyle** [comment]
Ok, it turns out that the issue was caused not be unicode characters, but instead by the section which ended with a `.` character! We were using querySelector() to manage scroll highlighting and that is confused by the sections which end with a dot. I've switched to using getElementByID when possible and that seems to resolve it. 

8c2d86da66a5aeb54cc07db4545d4dcf5dfffb8e

A fresh release is being built now!
