### ISSUE TITLE
compilation failed- error Text line contains an invalid character : 

### ISSUE THREAD

**Issue by shmuhammad2004** [quarto-dev/quarto-cli#551]
Hi,

Thank you for the good work.

Please, I am using JupyterNotebook in VScode and I cannot render Quatro.

Here is the error: 

`compilation failed- error Text line contains an invalid character. l.613 ^^[ [0;31mDocstring:^^[[0m `

VScode provides line number for each cell, and I cannot see how to find line number 163.

Please, can you advise,

**Comment by jjallaire** [comment]
We will need a minimum reproducible example to debug productively. If you can attach a full ipynb file that doesn't render to this issue we will investigate further!
