### ISSUE TITLE
Margin figures not being scaled (as of `matplotlib-inline>=0.1.5`)

### ISSUE THREAD

**Issue by warrickball** [quarto-dev/quarto-cli#5516]
### Bug description

I've been trying to emulate some Tufte-like elements from the [example HTML in the Quarto gallery](https://quarto-dev.github.io/quarto-gallery/page-layout/tufte.html) but I'm finding that the margin figures aren't being properly scaled. Here's a short Quarto markdown example:
````
# MWE

```{python}
#| fig-cap: "ReLU function"
#| column: margin
#| echo: false
import matplotlib.pyplot as pl

pl.plot([-1, 0, 1], [0, 0, 1])
pl.show()
```

Some text.  Here's a margin figure.

Here's some more text and a main figure.

```{python}
#| fig-cap: "ReLU function"
#| echo: false
import matplotlib.pyplot as pl

pl.plot([-1, 0, 1], [0, 0, 1])
pl.show()
```

````
which I build with this `_quarto.yml`:
```
format:
  html: default
```
and `quarto render mwe.qmd` with Quarto 1.3.340 on Fedora 37 (more system info at the end).

I've pinned a relevant change down to the package `matplotlib-inline`. With version 0.1.5, I get too large a figure in the margin. With 0.1.3, the margin figure is scaled correctly. (0.1.4 has been yanked from PyPI.) I noticed that the [changes between 0.1.3 and 0.1.5](https://github.com/ipython/matplotlib-inline/compare/0.1.3...0.1.5) include some matplotlib rcParams but adding those to a local `matplotlibrc` file didn't fix the scaling. At a glance, I'm not sure the main-column figure is being expanded to fill the column any more either.

I'm using Python 3.11 on Fedora 37 (though I encountered this with 3.9 on a Ubuntu 22.04 container too). `quarto check` gives:
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /home/wball/Downloads/quarto-1.3.340/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: 5.2.0
      Kernels: python3

(|) Checking Jupyter engine render....[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /usr/lib64/R
      LibPaths:
        - /home/wball/R/x86_64-redhat-linux-gnu-library/4.2
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK

```

Here are some verison numbers for potentially relevant Python packages (selected from `pip freeze`):
```
bokeh==3.0.3
colorama==0.4.6
colour==0.1.5
ipykernel==6.15.2
ipython==8.5.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
jupyter==1.0.0
jupyter-console==6.6.2
jupyter-events==0.6.3
jupyter_client==7.4.9
jupyter_core==5.2.0
jupyter_server==2.3.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
kaleido==0.2.1
Markdown==3.3.7
MarkupSafe==2.1.1
matplotlib==3.6.3
matplotlib-inline==0.1.5
nbclassic==1.0.0
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
notebook==6.5.2
notebook_shim==0.2.3
pandocfilters==1.5.0
pycairo==1.21.0
Pygments==2.14.0
PyQt5==5.15.9
PyQt5-sip==12.11.0
qtconsole==5.4.0
QtPy==2.1.0
widgetsnbextension==4.0.5
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
From what you are saying, the issue is from matplotlib not Quarto.

**Comment by mcanouil** [comment]
It appears when using the Jupyter kernel, `img-fluid` class is not added to the produced image.
I can't tell if it's Quarto or Jupyter.

Note that using `knitr` as the engine, it works as intended.

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/6bae9893-ce83-45b4-a199-0fd501cd61f0">

**Comment by cderv** [comment]
This happens because in the intermediate `.md` for Quarto and Pandoc processing we now get some size applied to the image produced 

````markdown
::: {#e70ae11b .cell .column-margin execution_count=1}

::: {.cell-output .cell-output-display}
![ReLU function](test2_files/figure-html/cell-2-output-1.png){width=571 height=411}
:::
:::
````

The `img-fluid` attributes is not set, because we don't apply responsive style when an image already has a `height` 
https://github.com/quarto-dev/quarto-cli/blob/6892e66a2df20625e2fc62fd6f091ff6b6159840/src/resources/filters/quarto-post/responsive.lua#L4-L16

I believe the relevant change in upstream lib is the setting not overridden anymore https://github.com/ipython/matplotlib-inline/commit/a433a899280c9cf801ccb5eb99faa1e15fc8a459

@dragonstyle when `column: margin` is set, we may need to remove those attributes ? 

Or do we do something specific with matplotlib size already for margin plotting and we should so the same for `matplot-line` now ? 

I am not sure who is writting the markdown syntax from the Jupyter notebook results. Is it Quarto ? 

Thanks

**Comment by ahasha** [comment]
I don't have a reproducible example to post, but I ran into this issue for `matplotlib` plots in the main body of my page, not just for margin figures.  I tried every metadata option I could find to change the figure width and nothing seemed to work.  Then I found this and downsgraded `matplotlib-inline` from 0.1.6 -> 0.1.3 and everything is working fine.

**Comment by cderv** [comment]
@birnstiel this issue is quite old now, and we are working on 1.6. It could be a regression so I'll move to its own ticket and we can look into it (I can reproduce)
