### ISSUE TITLE
Invalid YAML front matter syntax in examples in "slides" documentation

### ISSUE THREAD

**Issue by fingolfin** [quarto-dev/quarto-cli#5517]
### Bug description

There is an issue with the documentation for slides, visible on at least these pages:
- https://quarto.org/docs/presentations/
- https://quarto.org/docs/presentations/revealjs/
- https://quarto.org/docs/presentations/powerpoint.html
- https://quarto.org/docs/presentations/beamer.html

The examples listed there look like this:
```
---
format: revealjs---
```
instead of this:
```
---
format: revealjs
---
```
If one copy&pastes the "bad" versions, quarto rejects this input with an error:
```
ERROR: Expected front matter to end with '---'
```

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
Thanks, we are aware of this issue which is in fact a bug in Quarto CLI.

See #5490

**Comment by mcanouil** [comment]
Fixed!
