### ISSUE TITLE
PDF output not fetching a particular remote JPEG

### ISSUE THREAD

**Issue by warrickball** [quarto-dev/quarto-cli#5537]
### Bug description

The [Quarto 1.3 release notes say](https://quarto.org/docs/prerelease/1.3/pdf.html#remote-images) remote images will be fetched in PDF but this snippet
```
---
title: "Quarto Playground"
format: pdf
---

![DKIST first light](https://nso1.b-cdn.net/wp-content/uploads/2016/04/Full-Image-medium-scaled.jpg)
```
gives me the error
```
pandoc 
  to: latex
  output-file: remote-images.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Quarto Playground
  
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages

compilation failed- error
Unable to load picture or PDF file 'https://nso1.b-cdn.net/wp-content/uploads/2016/04/Full-Image-medium-scaled.jpg'.
<to be read again> 
                   }
l.160 ...ads/2016/04/Full-Image-medium-scaled.jpg}


see /home/wball/work/quarto-mwe/remote-images.log for more information.
```
when I run `quarto render`.

I tried with [the Wikipedia logo](https://en.wikipedia.org/static/images/icons/wikipedia.png) or [an image from today's featured article](https://upload.wikimedia.org/wikipedia/commons/3/37/Rockwell-Norman-LOC.jpg), both of which worked as expected. I also tried downloading the ill-behaved image and checking that it is, in fact, a JPEG:
```
$ file Full-Image-medium-scaled.jpg 
Full-Image-medium-scaled.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 2560x2560, components 3
```
I also tried escaping the dashes (`-` → `\-`), placing the URL in quotes and using `pdflatex` instead of `xelatex`, none of which worked.

I'm not sure if this is a pandoc issue but a quick search online and in their issues didn't turn up anything obvious and I'm not familiar enough with it to create a relevant test.

This is Fedora 37 with the following output from `quarto check`:
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /home/wball/Downloads/quarto-1.3.340/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: 5.2.0
      Kernels: python3

(-) Checking Jupyter engine render....[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /usr/lib64/R
      LibPaths:
        - /home/wball/R/x86_64-redhat-linux-gnu-library/4.2
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
It seems Quarto is doing something on the image here, _i.e._, the following works.

```sh
quarto pandoc index.qmd --from markdown --to pdf -o index.pdf
```

**Comment by dragonstyle** [comment]
Pandoc only does the remote image fetching when targeting PDF format (and we actually target LaTeX and then handle the PDF generation ourselves). This means we have our own implementation of the URL fetching, which in this case incorrectly excluded URLS with some characters (the `-` in your example URL was causing the failure). 

I went ahead and corrected the pattern to be more permissive of special characters. Thanks for reporting this!

**Comment by the-solipsist** [comment]
This URL is still causing PDF rendering to fail on Quarto v1.4.355:

https://the-ken.com/wp-content/uploads/2016/12/GOI-Fake-App.png

**Comment by cderv** [comment]
@the-solipsist it would have been better to share a reproducible example, in a new issue, possibly linking to this one. 

Your URL works on my side 
````markdown
---
title: test
format: pdf
keep-tex: true
---

![](https://the-ken.com/wp-content/uploads/2016/12/GOI-Fake-App.png)

````

The `.tex` document contains 
````tex
\begin{document}
\maketitle
\includegraphics{index_files/mediabag/GOI-Fake-App.png}



\end{document}
````
and PNG image is correctly downloaded. 

If you have issue with  this simple document, please do open a new issue in this repo with a reproducible example and context. Thank you !

**Comment by the-solipsist** [comment]
Thanks, @cderv, and sorry about hijacking this issue: I thought it was the same bug.

I'm facing a peculiar problem where `quarto render <filename>` leads to xetex choking on the jpg file when it is part of a website project, but that same qmd file is rendering fine when it is standalone in the /tmp folder.  The .tex file produced in both cases is identical.

In short: I'm unable to figure out how to reproduce the issue.  

At any rate, it is clearly not the same bug, even though the symptoms are the same.  If I figure out how to create a reproducible example, I'll open a new issue.

**Comment by cderv** [comment]
> I'm facing a peculiar problem where quarto render <filename> leads to xetex choking on the jpg file when it is part of a website project,

LaTeX and website does not quite work together as you can't build a PDF from a website. So I am unsure to understand the exact context. 

Try to 
* Create a Quarto project 
* Add some content with what you think is failing
* See if that reproduce. If not then it is something specific within your particular project that could conflict.
