### ISSUE TITLE
"The system cannot find the path specified" error on running Quarto in Miniconda virtual environment 

### ISSUE THREAD

**Issue by Darren-Ray** [quarto-dev/quarto-cli#5541]
### Bug description

I am trying to setup and run Quarto on Windows 10 using Miniconda virtual environment for running Jupyter.

I installed Quarto using the CLI 1.3.353 from https://quarto.org/docs/get-started/ 

into the recommended folder, for all users.

I set up a fresh Miniconda virtual environment and downloaded  the hello.ipynb and have that saved on the C: drive

On trying to run quarto preview hello.ipynb or quarto render hello.ipynb --to html in the Minconda terminal  
I get 
"The system cannot find the path specified" 

Looked through  the issues and found some past issues that suggest Linux /Windows path differences, that were resolved, but might the case with this. 

quarto check returns the same message in the terminal

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
Thanks for the report!

Please (re)read the checklist in your post and provide the information requested in it such as IDE (if any) and most importantly the results of `quarto check` within your Quarto repository.

**Comment by dragonstyle** [comment]
Closing as the issue is stale.
