### ISSUE TITLE
Improve `data-quarto-disable-processing="true"` documentation

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#5562]
Quarto 1.3 brought the ability to disable Quarto processing of tables, this was highlighted in a "prerelease" stand-alone page, see <https://quarto.org/docs/prerelease/1.3/tables.html>.

The issue is that this page is not easy to find and this `data-quarto-disable-processing="true"` feature/trick can't be found easily without knowing what you are looking for.

I believe, parts of or the whole content of the "prerelease" page could be added in a new subsection of <https://quarto.org/docs/authoring/tables.html>.

Happy to make a PR later, if appropriate.

**Comment by cscheid** [comment]
Totally agreed. Generally speaking, we would benefit from a concrete workflow on how to take documentation information from the prerelease announcements to the main page.

**Comment by mcanouil** [comment]
I can try to come up with something to start discussing a workflow, especially since I discussed with @allenmanning  about a related subject, namely "feature requests follow up".

**Comment by mcanouil** [comment]
PR made 😉
See <https://github.com/quarto-dev/quarto-web/pull/745>.

**Comment by liquidcarbon** [comment]
Trying to use [itables](https://mwouts.github.io/itables/advanced_parameters.html#column-width)(based on DataTables and jQuery) with Quarto.  Most of the functionality works, but Quarto overrides somehow the column width.

Datatables changes column widths through JS:
`let dt_args = {"columnDefs": [{"width": "100px", "targets": "_all"}], ... ` 

And the `<table data-quarto-disable-processing="true" ` flag takes no effect.

Any suggestions?

**Comment by mcanouil** [comment]
Please open a Q&A discussion or a separate issue as this issue was completed and is not related to your issue.
