### ISSUE TITLE
Quarto installation not found when rendering .qmd on remote server in VScode

### ISSUE THREAD

**Issue by pakiessling** [quarto-dev/quarto-cli#5572]
### Bug description

I am using Quarto on a remote server I ssh into in VScode.

Versions are the following:

Windows 10 local - Centos 7.9 remote
VScode insiders: 1.79.0
Quarto extension: 1.85.0
Quarto package on remote server: 1.3.121

I am able to run cells in my .qmd and see their output, however the Render button just produces a "Quarto Installation Not Found" error. Rendering with` quarto render test.qmd --to pdf` on the command line on the remote server in VScode works correctly.

I have attached a picture showing the error and the correct conversion on the CLI.
Please let me know if this features is not available yet or if I need to configure Quarto differently.

![grafik](https://github.com/quarto-dev/quarto-cli/assets/104848590/ac932e2e-2ccd-4572-8210-9d983c0d1562)

Quarto -check output:

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 2.19.2: OK
      Dart Sass version 1.32.8: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.121
      Path: /rwthfs/rz/cluster/home/mz637064/software/quarto-1.3.121/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.15 (Conda)
      Path: /home/mz637064/mambaforge/bin/python
      Jupyter: 4.11.1
      Kernels: ir, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /rwthfs/rz/cluster/home/mz637064/mambaforge/lib/R
      LibPaths:
        - /rwthfs/rz/cluster/home/mz637064/mambaforge/lib/R/library
      rmarkdown: (None)

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /rwthfs/rz/cluster/home/mz637064/mambaforge/lib/R
      LibPaths:
        - /rwthfs/rz/cluster/home/mz637064/mambaforge/lib/R/library
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK


quarto check  9.96s user 2.62s system 42% cpu 29.506 total

```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
Something does not this right in your installation, _i.e._, Quarto is probably not on your shell `PATH`.

The easy workaround (as an alternative to what `PATH` issue you have, if not a bug on Quarto side eventually), would be for you to set `"quarto.path": ""` VSCode setting.
<img width="1194" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/e1494a9f-fbcb-4c77-b402-c22427e7e963">

**Comment by pakiessling** [comment]
@mcanouil Thank you for your message. I have confirmed that Quarto is in the PATH on the remote machine. 

Adding the Quarto installation path in the Vs code settings did not fix the issue.

My impression is that the Quarto extension is looking on my local machine for the Quarto executable instead of the remote ssh host?

**Comment by pakiessling** [comment]
@mcanouil Thank you for your message. Quarto is definetely in my path.

Your suggestion of manually adding the path in the **remote** extension settings fixed the issue.

**Comment by mcanouil** [comment]
Did you restart your VSCode after changing the setting?

I have been using VSCode and Quarto VSCode for months in devcontainers, via SSH and using WSL, and I am pretty sure the VSCode and extension are not trying to look for local configuration when on remotes.

**Comment by pakiessling** [comment]
@mcanouil Somewhere during this process Quarto forgot the correct python installation on the remote 😅 

Quarto -check now reports the old system python installation without Jupyter.
I am able to set the correct python installation in the interactive viewer, but not for the rendering.
![grafik](https://github.com/quarto-dev/quarto-cli/assets/104848590/5b1e5074-6aae-4301-a3fa-21eb40287ccb)


Any advice?

**Comment by mcanouil** [comment]
Apparently and as documented, the `PATH` takes precedence over VSCode settings (not sure that's a good thing).

Either use virtual environment (see <https://quarto.org/docs/projects/virtual-environments.html>) which should be properly detected or using environment variable (_i.e._, `QUARTO_PYTHON`), see <https://quarto.org/docs/projects/environment.html>.

**Comment by pakiessling** [comment]
Ok thanks a lot. export QUARTO_PYTHON=/python/path indeed fixed the issue.

I am exclusively working with Conda enviroments and installed Quarto outside of those.
Is the recommendation to install Quarto inside the same enviroment as the python version I want to use for rendering?

**Comment by mcanouil** [comment]
I personally dislike so much Conda environments for so many reasons, that I personally would never recommending it to anyone.

This being, Quarto is available in Conda, so maybe it would make sense to make full use of Conda since you already use it.

**Comment by pakiessling** [comment]
Thanks a lot for your continued help
