### ISSUE TITLE
Discolored box around images in docx

### ISSUE THREAD

**Issue by eeenilsson** [quarto-dev/quarto-cli#5577]
### Bug description

When using `quarto_render('example_image.qmd', output_format = "docx")` on the sample .qmd below the resulting word document displays a discolored yellowish box around the image. 

**This does not appear** when rendering in using `markdown::render("example_image.rmd")`, ie not using Quarto. 

System is windows, using R version 4.2.3, quarto-1.3.353-win, MS Word 2016.

The example_image.qmd file below.
The resulting docx output: ([link](https://ibb.co/5Gxh9V3))

````

---
title: Test including figure in docx
format: docx
---

```{r} 
#| label: fig-elephant 
#| fig-cap: "This is an elephant."
download.file("https://quarto.org/docs/authoring/images/crossref-figure.png", 'elephant.png', mode = 'wb')
knitr::include_graphics('elephant.png')

``` 
````
```

> quarto check output:

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.353
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.3
      Path: C:/PROGRA~1/R/R-42~1.3
      LibPaths:
        - C:/Users/user/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.3/library
      knitr: 1.42
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
This seems to be fixed now. 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/31077e98-3b19-48a6-8178-1ddf7b699c09)

So closing.
