### ISSUE TITLE
RHEL7 packages :`quarto check` fails due to deno error: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by cregouby** [quarto-dev/quarto-cli#5581]
### Bug description

Using de RHEL7 package v 1.3.353, I run into an GLIBC version error due to Deno

# Current behavior
```bash
$ /opt/quarto/"${QUARTO_VERSION}"/bin/quarto -v
1.3.353
$ /opt/quarto/"${QUARTO_VERSION}"/bin/quarto check
/opt/quarto-1.2.313/1.3.353/bin/tools/deno-x86_64-unknown-linux-gnu/deno: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/quarto-1.2.313/1.3.353/bin/tools/deno-x86_64-unknown-linux-gnu/deno)
$ /opt/quarto/"${QUARTO_VERSION}"/bin/quarto -h
/opt/quarto-1.2.313/1.3.353/bin/tools/deno-x86_64-unknown-linux-gnu/deno: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/quarto-1.2.313/1.3.353/bin/tools/deno-x86_64-unknown-linux-gnu/deno)

```
# ReprEx

I used the standard installation procedure on RHEL7

```bash
export QUARTO_VERSION="1.3.353"
curl -o quarto.tar.gz -L     "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.tar.gz"
sudo tar -zxvf quarto.tar.gz -C "/opt/quarto/${QUARTO_VERSION}" --strip-components=1
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
`/opt/quarto-1.2.313/1.3.353/` is a little suspicious to me; is it possible that you might have two installations stepping on each other's toes?

**Comment by cregouby** [comment]
You're right, I didn't remove previous install indeed. I'll redo the install after this and let you know...

**Comment by cregouby** [comment]
Sure, I'll do that and get back to you soon.

**Comment by dragonstyle** [comment]
Thank you such much for your help testing. What you propose in the short term should be a valid fix (that is essentially what the package should be doing for you). It is possible that we are including the wrong version of the Deno in package, though I tried checking that initially and felt like that wasn't the issue. That said, now that you have confirmed that this resolves it for you, there are really only 2 possible causes IMO:

1) You happened to inadvertently install a non RHEL version of the bundle for 1.3.353
2) The bundle is including or installing the incorrect Deno version

I'll assume it is 2 for the time being, but if you can confirm that it isn't 1, that would be helpful. I'll have a look at this tomorrow!

**Comment by dragonstyle** [comment]
I just double checked the version of `deno` being bundled with the RHEL zip, and that appears to be the correct version (and I confirmed it is executable on RedHat 7). I think it is most likely that you may have inadvertently downloaded the non-RHEL version.

**Comment by klosinho00** [comment]
Hi everyone, I just wanted to share that I had the same problem when installing quarto on the high performance computer of my university. 

`[mklose@curta ~]$ quarto check`

lead to 

`/home/mklose/opt/quarto-1.3.361/bin/tools/deno-x86_64-unknown-linux-gnu/deno: /lib64/libc.so.6: version 'GLIBC_2.18' not found (required by /home/mklose/opt/quarto-1.3.361/bin/tools/deno-x86_64-unknown-linux-gnu/deno)`

The discussed fix also worked for me, after replacing deno `quarto check` successfully passed and I was able to render .qmd documents. Since this is a HPC system and I am not familiar with the whole server setup I can only share the SessionInfo from R (in case that helps).

`sessionInfo()`

```
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /trinity/shared/easybuild/software/FlexiBLAS/3.2.1-GCC-12.2.0/lib64/libflexiblas.so.3.2

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] htmlwidgets_1.6.1 compiler_4.2.2    fastmap_1.1.1     cli_3.6.0        
 [5] tools_4.2.2       htmltools_0.5.4   yaml_2.3.7        rmarkdown_2.20   
 [9] knitr_1.42        jsonlite_1.8.4    xfun_0.37         digest_0.6.31    
[13] rlang_1.1.0       evaluate_0.20
```

**Comment by aersoares81** [comment]
Hi, I also had the same problem with "GLIBC_2.18' not found". So I did what you guys did, downloaded deno, copied it over `opt/quarto-1.4.549/bin/tools/x86_64/deno` and now `quarto check` works. BUT it spits out an error message too.

```
**⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags**
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
warning: Use of deprecated "Deno.run()" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.40.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /domus/h1/asoares/opt/quarto-1.4.549/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /sw/apps/texlive/2023-08-14/rackham/bin/x86_64-linux
      Version: 2023

**⚠️  The `Deno.dlopen` API was used with `--unstable` flag. The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-ffi` instead.**
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /sw/apps/conda/latest/rackham_stage/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /sw/apps/R/4.3.1/rackham/lib64/R
      LibPaths:
        - /domus/h1/myusername/R/x86_64-pc-linux-gnu-library/4.3
        - /sw/apps/R/4.3.1/rackham/lib64/R/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

This is with `pkg-deno-1.40.2-hfc7925d_0` and `Quarto 1.4.549`. All Quarto actions have the same warning actually. For example:

```

(base) [myusername@rackham4 ~]$ quarto -V
**⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags**
1.4.549
```

**Comment by allefeld** [comment]
Same issue on a HPC running OpenFlight r2023.2 based on CentOS Linux 7.9.2009.

Quarto installed from `quarto-1.5.46-linux-amd64.tar.gz`.

The workaround failed for me because `unzstd` is not available.

Instead, I installed `deno` via conda into my environment `r`, and then did

```
cp ~/.conda/envs/r/bin/deno ~/opt/quarto-1.5.46/bin/tools/x86_64/
```

Now `quarto check´ works.

**Comment by cscheid** [comment]
@allefeld Quarto also observes the `QUARTO_DENO` environment variable, if you want a solution less drastic than copying a binary over.
