### ISSUE TITLE
`preview` regression: no longer watching `.js` resources properly

### ISSUE THREAD

**Issue by declann** [quarto-dev/quarto-cli#5611]
### Bug description

On Ubuntu, using Quarto 1.2.335 preview reloads when I modify local `.js` files that I require into my qmd file in ojs blocks

On 1.3.353 and 1.4.78, this isn't working when I update the .js file or `echo "hi" > ` it. *It does work when I **remove** and write a new file.*

`.js` file is in a resources folder, listed in `format: html: resources` yml.

1.4.78 info:

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
```

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK

      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.78
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
> On Ubuntu, using Quarto 1.2.335 preview reloads when I modify local .js files that I require into my qmd file in ojs blocks

Can you help us by providing a simple reproducible example so that we can check this on our side ? 

Thank you

**Comment by declann** [comment]
Sure.

https://github.com/declann/quarto-issue-5661

Git clone this and do `quarto preview index.qmd`, then modify the `umd.js` file in resources folder.

**Comment by declann** [comment]
Reload for `umd.js` changes works whenever I specify the complete rather than directory path i.e.

```
  html:
    resources:
    - ./resources
```

becomes
```
  html:
    resources:
    - ./resources/umd.js
```

The first approach worked for me in earlier versions of Quarto. Is it intended to work?

If so, I think the isResourceFile logic in watch.ts here should be relaxed a little to allow for directories: 
https://github.com/quarto-dev/quarto-cli/blob/179078bfd8d6d41ea64b0f3a66da88856d9d4e64/src/project/serve/watch.ts#L89

**Comment by cscheid** [comment]
I believe this was changed on purpose because our previous watching infrastructure was using too many OS resources (right, @jjallaire?)

**Comment by jjallaire** [comment]
The issue ended up being that we don't handle `./` prefixes correctly for path globs. The following actually works as you are expecting:

```yaml
html:
    resources:
    - /resources
```

Fixed here: https://github.com/quarto-dev/quarto-cli/commit/0cc8bd77db0f8de3f44812cd9e01a211dacb3e3f
