### ISSUE TITLE
Feature request: Some way to reset number counter for tables and figures.

### ISSUE THREAD

**Issue by eeenilsson** [quarto-dev/quarto-cli#5614]
### Bug description

I have been using the code below in rmarkdown::knitr to MS Word docx (via `output: officedown::rdocx_document:`) successfuly to reset the numbering counter for tables and figures, inserting it where I need to reset the counter. Unfortunately it does not work in Quarto docx documents.

It would be very nice to be able to use this or something similar in Quarto.

```

```{r} 
#| output: false
officer::run_autonum(
             seq_id = "fig",
             pre_label = "",
             start_at = 0,
             prop = fp_text(
  color = "white",
  font.size = 0)
  )
## Note: Reset figure numbering NOT working in qmd
``` 

```

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by eeenilsson** [comment]
...in the meantime, one could use this [hack](https://stackoverflow.com/questions/75445753/is-it-possible-to-reset-and-re-number-cross-references-to-figures-in-quarto-r)

Using  book output one can have separate numbering of figures for each chapter, but unfortunately, then cross references between chapters must be set to false.

The goal for me is to be able to write a scientific article with separately numbered figures and tables in the supplement, which are cross-referenced from the main body of the manuscript. This is doable in knitr with the solution above.

**Comment by eeenilsson** [comment]
Thanks!

It shouldnt have to be via knitr I believe. Maybe it could be possible using the "book" format, if one can use crossrefs between chapters without automatic numbering of the headers and have more control of numbering tables/figures in each chapter, eg adding a prefix "S" to get the first figure in chapter 2 as "Figure S1".

**Comment by mcanouil** [comment]
Related to this, there is a more general need to have the ability to reset numbering of pretty much everything.

- #5987

For `pdf`, there is a known solution:

- https://github.com/quarto-dev/quarto-cli/discussions/1283#discussioncomment-5313032

**Comment by cscheid** [comment]
The ability to create fresh counters for crossreferences is now available on our prereleases. See https://quarto.org/docs/prerelease/1.4/crossref.html for preliminary documentation, and we'll have full docs by the time the 1.4 release is out.
