### ISSUE TITLE
Matlab code cells not recognized by VS Code

### ISSUE THREAD

**Issue by allefeld** [quarto-dev/quarto-cli#5616]
### Bug description

Matlab code cells in qmd files are not recognized by the Quarto Extension for VS Code:

![Screenshot_20230520_215232](https://github.com/quarto-dev/quarto-cli/assets/1738353/78204b80-1574-4b69-8057-c28ea1fc92c1)

Within such cells, there is no syntax highlighting or other language support, and the cells do not have the minitoolbar to execute them separately.

Processing the qmd file works, and the code cells are executed without problem.

As seen on the right side of the screenshot, syntax highlighting in Matlab script files (`.m`) works.

__quarto check:__

````
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.313
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: /usr/bin/python3
      Jupyter: 4.9.1
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK
````

__System:__
Debian GNU/Linux 11.7, kernel 5.10.0-23-amd64
VS Code 1.78.2
  Python extension 2023.8.0
  Jupyter extension 2023.4.1011241018
  Quarto extension 1.85.0
Jupyter matlab_kernel 0.17.1

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
FYI https://marketplace.visualstudio.com/items?itemName=MathWorks.language-matlab

**Comment by allefeld** [comment]
> FYI https://marketplace.visualstudio.com/items?itemName=MathWorks.language-matlab

Good to know, thanks! I previously had the [Matlab Unofficial extension](https://marketplace.visualstudio.com/items?itemName=Gimly81.matlab) installed, replaced it now by the new official one.

Unfortunately, that doesn't fix the problem.

**Comment by mcanouil** [comment]
I know, it's mostly for the Quarto VSCode extension to rely on as it is the case for other languages.

**Comment by jjallaire** [comment]
Just added support for Matlab blocks in the VS Code extension here: https://github.com/quarto-dev/quarto/commit/db52c7e4b6919dfb7b7e4db551cac6c4f5f2d344.  This is not yet released but should be in the next couple of weeks.

**Comment by allefeld** [comment]
Wow, thanks for the extremely quick fix!

**Comment by mcanouil** [comment]
For future bug report or feature request for the Quarto VSCode extension, prefer the following repository: https://github.com/quarto-dev/quarto 😉

**Comment by allefeld** [comment]
Sorry to come back so quickly, but I now have the Quarto extension v1.87.1 installed, and @jjallaire's code seems to have been integrated since v1.87.0. Syntax highlighting and completion now work, but *Add line comment* puts the line into `<!--  -->` instead of prepending `%`.

**Comment by jjallaire** [comment]
I don't have a good explanation for why this is happening as other languages seem to get their native line comment and the Matlab extension appears to register their line comment correctly.
