### ISSUE TITLE
Undefined control sequence, cannot handle double ended inequality when render PDF

### ISSUE THREAD

**Issue by Fred-Wu** [quarto-dev/quarto-cli#5619]
### Bug description

```
Quarto: 1.3.24 and 1.3.353 in VSCode
Windows 10. 
```

My document was running well with quarto in vscode a few days ago. However, after I added a few inline equations in a numbered list like below, the following error occurred during the compilation to PDF. 

5.  For one uncensored survival time, we could define $N_i(t)=I(T_i\leq t)$, and then $dN(t) = I(T_i \leq t+dt) - I(T_i \leq t) = I(t \lt T_i \leq t+dt)$

```
compilation failed- missing packages (automatic installed disabled)
Undefined control sequence.
l.174 ...(T_i \leq t+dt) - I(T_i \leq t) = I(t \lt
                                                   T_i \leq t+dt)\)
```
Also, there is no issues to render the equation in the Quarto assist panel. 

After some experimenting,  I think the issue is due to the double ended inequality, such as $I(t \lt T_i \leq t+dt)$.  
If I placed this in the beginning of the document, no matter as inline or displayed math, the compilation would stop with the same error pointing to that. 

```
quarto check

A new release of Deno is available: 1.28.2 → 1.33.4 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.353
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.11 (Conda)
      Path: C:/Users/xxxxx/AppData/Local/miniforge3/envs/mytensor/python.exe
      Jupyter: 5.3.0
      Kernels: python3, powershell, pysparkkernel, sparkkernel, sparkrkernel

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.3
      Path: C:/PROGRA~1/R/R-42~1.3
      LibPaths:
        - C:/Users/xxxxx/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.3/library
      knitr: 1.42
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK
```

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
Thanks for the report!

Could you share a small "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by Fred-Wu** [comment]
The following will show the issue with the inclusion and exclusion of the $I(t \lt T_i \leq t+dt)$ in the equation. 
```
---
title: Counting process
format: 
    pdf: 
        include-in-header: 
            - text: |
                \usepackage{amsmath, amssymb}
                \usepackage{cases}
---

Counting process

1.  For one uncensored survival time, we could define $N_i(t)=I(T_i\leq t)$, and then 
$dN(t) = I(T_i \leq t+dt) - I(T_i \leq t) = I(t \lt T_i \leq t+dt)$
```

**Comment by cderv** [comment]
@Fred-Wu where do `\lt` command comes from ? It is my understanding that LaTeX uses `<` for the "lower than" operator 
In the AMS math guide, `\leq` is referenced but for `<` it uses `<` directly: http://tug.ctan.org/info/short-math-guide/short-math-guide.pdf

Other web related question on this `\lt` command: https://tex.stackexchange.com/questions/12519/what-library-do-i-have-to-use-such-that-the-document-can-render-lt-and-gt-as-l

So my understanding is that your document is erroring when converting to PDF with LaTeX because you are using a command that does not exists. Nothing related to Quarto. 

> Also, there is no issues to render the equation in the Quarto assist panel.

The assist panel will not compile with LaTeX but use Mathjax and it seems `\lt` [does exist within mathjax](https://docs.mathjax.org/en/latest/input/tex/macros/index.html#l)

Hope it helps understand
