### ISSUE TITLE
`-v` flag isn't recognised

### ISSUE THREAD

**Issue by BradyAJohnston** [quarto-dev/quarto-cli#562]
When checking quarto version, `--version` succeeds and `-v` fails.
```
❯ quarto --version
0.9.155
```

```
❯ quarto -v
ERROR: Unknown option "-v". Did you mean option "-h"?
```

I have tested on both mac and windows builds.

**Comment by dragonstyle** [comment]
Should be fixed here:

e19e6acb8c271569a137c7363a239b134e3290d0

**Comment by BradyAJohnston** [comment]
Yep I installed the laters build `0.9.209` and it now works fine.
