### ISSUE TITLE
excessive spacing within panel-tabset

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#5626]
### Bug description

Using Quarto 1.3.340 (1.3.353 also shows the same behavior) on macOS:

Given the Markdown file:

````markdown
---
title: callout text
---

this is a paragraph

this is another paragraph

::: {.panel-tabset}

## one option

this is text for one option

some more text for one option

## two option

this is text for two option

some more text for two option

:::

this is some text after the tabset

this is more text after the tabset
````

This is rendered with more line spacing within the panel tabset than outside.

<img width="331" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/31f6b45e-55dd-428c-9470-04276248791d">

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 3.6.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/3.6/Resources/library
      knitr: 1.42.8
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [x] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
I agree that the spacing looks out of place, but this behavior appears to be [on purpose](https://github.com/quarto-dev/quarto-cli/blame/main/src/resources/formats/html/bootstrap/_bootstrap-rules.scss#L787-L792). @dragonstyle that commit was 2 years ago but would you by chance remember what it was trying to solve?
