### ISSUE TITLE
Word experienced an error trying to open the file

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#5650]
### Bug description

On Windows, when I convert a document to word using quarto 1.4.84, I get the following error:

![image](https://github.com/quarto-dev/quarto-cli/assets/1813121/6230f2d5-d768-4db2-96e6-42c960c3b523)

I don't get this error with quarto 1.3.353. 

I'm currently in the middle of trying to get a report out. Once I've finished the submission, I will come back to this issue and submit a reproducible example.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
With just this popup, it's going to be hard to figure out the issue.

Are you using a Cloud drive of some kind?
Does this error is limited to Word documents? Any Word documents? Only the one you are working on?

**Comment by kdheepak** [comment]
I was getting this error on my local machine and not the cloud. It was only with word. The pdf and html versions work fine. After uninstalling 1.4 and reinstalling 1.3, the word document opened fine. 

This started happening after I upgraded office to Office365. Previously I had Office 2014. 

I’m sure it is not straightforward to figure out. I’m hoping to test a smaller document at some point.

**Comment by mcanouil** [comment]
Did you activate synchronisation on Cloud via Office365? (I don't believe this to be a Quarto issue itself)

**Comment by mcanouil** [comment]
If you get this error with ANY document, please try `quarto pandoc test.md --to docx -o test.docx` or similar command to render the document using Pandoc.

**Comment by kdheepak** [comment]
That wouldn’t work if I have computable cells, right?

**Comment by kdheepak** [comment]
I will have to try it next week. I need to get a report out this week and need to have quarto 1.3 installed to generate the word copy that my colleagues can use.
