### ISSUE TITLE
crossrefs-hover doesn't work with the book format

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#5659]
### Bug description

The hover feature for cross-references of sections, equations, etc. doesn't work for me when compiling books. No errors are given, just nothing happens when hovering the links.

If I compile a standalone document such as:

	---
	format: html
	---

	# Introduction

	This is a book created from markdown and executable code.

	See @knuth84 for additional discussion of literate programming.

	In @sec-test something will happen.

	## Test {#sec-test}

	Here's an equation
	$$
	x^2=1
	$$ {#eq-test}

	In @eq-test there's an equation.

then it works fine. 

If I instead `quarto create project book` and include the following as a chapter

	# Introduction

	This is a book created from markdown and executable code.

	See @knuth84 for additional discussion of literate programming.

	In @sec-test something will happen.

	## Test {#sec-test}

	Here's an equation
	$$
	x^2=1
	$$ {#eq-test}

	In @eq-test there's an equation.

then hovering doesn't work for the section and equation reference. This is using Quarto 1.4.84 on Windows 10.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
This is, unfortunately by design for the time being - since book cross references can refer to elements that aren't present in the current document (but are in some other chapter or page), it is non-trivial to make cross reference previewing work for books. I'll leave this open and targeted for the future as an item to improve in books.

**Comment by snhansen** [comment]
@dragonstyle: All right, good to know. Pretty sure it did work in a previous pre-release version such as 1.4.50 for books. Any way to enable it within-chapter?
