### ISSUE TITLE
HTML block containing comment not left as-is

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#5660]
### Bug description

Using Quarto 1.3.340 on macOS

Given the Quarto document:

````markdown
---
title: raw
---

```{=html}
<p
    id="raw"
    <!-- this is an important comment -->
    class="raw"
>
  apples are red.
</p>
```
````

This content is rendered to look like:

<img width="281" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/206ecf21-ffe8-44b1-8758-1d3458c20e4a">

Asking Quarto to process the file:

```bash
quarto pandoc raw.qmd -f markdown -t html
```

is fine:

```html
<p
    id="raw"
    <!-- this is an important comment -->
    class="raw"
>
  apples are red.
</p>
```

The generated HTML by Quarto (extracted from the full doc):

```html
<p id="raw" <!--="" this="" is="" an="" important="" comment="" --="">
    class="raw"
&gt;
  apples are red.
</p>
```

The presence of the HTML comment is causing trouble. Without that comment, Quarto can handle this content without issue.

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 3.6.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/3.6/Resources/library
      knitr: 1.42.8
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by aronatkins** [comment]
This issue is not the same as https://github.com/quarto-dev/quarto-cli/issues/5631, which was trying to use bare HTML without a surrounding marker.

**Comment by cscheid** [comment]
@aronatkins This is invalid HTML, and we require HTML to be valid:

https://stackoverflow.com/questions/5926580/html-comments-inside-opening-tag-of-the-element

**Comment by cscheid** [comment]
Specifically, we need HTML tags to be well formed in order for our postprocessor to run correctly.

**Comment by mcanouil** [comment]
See for example W3C Markup Validation Service <https://validator.w3.org/#validate_by_input>.
<img width="786" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/229f1119-4987-4b36-b651-46c5a27df866">

**Comment by aronatkins** [comment]
Sorry about that. You're right. I was trying to use a custom tag that has oodles of arguments and wanted comments to leave breadcrumbs about some of my choices...
