### ISSUE TITLE
Callouts in shortcodes don't get "styled" with Quarto 1.4

### ISSUE THREAD

**Issue by Nenuial** [quarto-dev/quarto-cli#5661]
### Bug description

In Quarto 1.4, when creating callouts in a shortcode, the necessary "code" doesn't make it to the latex. The callout gets printed but without the box around it. In html I have the impression that the callout doesn't show at all.

I have created a small extension that showcases this :
[https://github.com/Nenuial/callout-test](https://github.com/Nenuial/callout-test)
It can be installed using `quarto add nenuial/callout-test`
The shortcode is `{{< callout-test >}}`

Quarto check information on MacOS:
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.84
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
First "content" is a content "a `pandoc.Blocks` object, or a plain list in the constructor" not  a `pandoc.Str`.
With that being fixed, it indeed works in 1.3.353 but not in development version.

I slightly modified the shortcode as follow:
```lua
return {
  ['callout-test'] = function(args, kwargs, meta) 
    local c = quarto.Callout({
      type = "note",
      content = { pandoc.Div(pandoc.Plain("This is a note")) },
      title = "Note title"
    })

    print(c)

    return c
  end
}
```

Quarto 1.3.353:
```txt
RawInline (Format "QUARTO_custom") "Callout 1 Block"
```

Quarto dev:
```txt
Div ("",[],[("__quarto_custom","true"),("__quarto_custom_type","Callout"),("__quarto_custom_context","Block"),("__quarto_custom_id","2")]) [Div ("",[],[]) [Plain [Str "Note title"]],Div ("",[],[]) [Div ("",[],[]) [Plain [Str "This",Space,Str "is",Space,Str "a",Space,Str "note"]]]]
```

**Comment by mcanouil** [comment]
No worries and thank you for finding this regression/bug!

**Comment by cscheid** [comment]
Ok, I know what the problem is; thanks for reporting! The issue is that the handling of a single shortcode in a paragraph was being done in an _inline context_ (because contents of paragraphs are inlines), but it should have been special cased as a _block context_, where the shortcode stands by itself.

I'm adding regression tests and the fix should be up shortly.

**Comment by Nenuial** [comment]
Thank you for the fix!!
