### ISSUE TITLE
quarto.doc.include_text does not add text into revealjs

### ISSUE THREAD

**Issue by coatless** [quarto-dev/quarto-cli#5666]
### Bug description

If we have the following code inside of a Lua filter that is included as a `quarto` extension:

```lua
  -- Sample initialization
  local example_text = [[
    <script>
    // the hello world program
    document.write('Hello, World!');
    </script>
  ]]

  -- Insert the web initialization
  -- https://quarto.org/docs/extensions/lua-api.html#includes
  quarto.doc.include_text("in-header", example_text)
```

The `quarto.doc.include_text()` fails to include the text inside of the `header` under the `revealjs` format. However, it works under the `html` format option. Per the Lua documentation at:

<https://quarto.org/docs/extensions/lua-api.html#includes>

I feel like this should be a bug as the `revealjs` format is a version of an `html` document.

You can experiment and see more details on the `quarto.doc.include_text()` use with the filter here:

https://github.com/coatless/quarto-ext-revealjs-bug 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
Thanks a lot for the great report! 

This is indeed an issue in our processing here: 
https://github.com/quarto-dev/quarto-cli/blob/4b7c0fe6c42bb69b0f343c04bdcc0bf108b11e86/src/resources/pandoc/datadir/init.lua#L1544-L1553

It seems `FORMAT` should be tweaked to `html` when `revealjs` as it is seems to be no valid for `rawBlock()` 

I think this is why it gets ignored at the end. 

Maybe this is a Pandoc issue where using the `revealjs` format as same name as output should work maybe. 

@dragonstyle we can definitely patch and handle but what is your thoughts about what Pandoc should be doing with `pandoc.RawBlock()`

**Comment by dragonstyle** [comment]
Woah that is a surprising and cool bug. I'm honestly not sure the best approach to this- overall specifying a raw block of the current format seems correct, but perhaps we need to provide per format overrides here.

Have you confirmed that manually tweaking the `FORMAT` to html resolves the issue?

**Comment by cderv** [comment]
Yes this is surprising - I asked in Pandoc discuss to confirm what Pandoc expects https://groups.google.com/g/pandoc-discuss/c/2ffxC1uLh2M

> Have you confirmed that manually tweaking the FORMAT to html resolves the issue?

Yes I have confirm. I wonder if this is not related to the Writer .hs file in pandoc. Revealjs is part of `html` writer. This would mean the same for `beamer` and other format that are sub format of another. 

I didn't find the code in Pandoc code where under which contidion a `rawBlock` is ignored or not. cc @tarleb as you could be interested in this. 

This is a current fix that covers slides mainly 
````diff
diff --git a/src/resources/pandoc/datadir/init.lua b/src/resources/pandoc/datadir/init.lua
index 533c8b742..dac5cdcf1 100644
--- a/src/resources/pandoc/datadir/init.lua
+++ b/src/resources/pandoc/datadir/init.lua
@@ -1540,7 +1540,14 @@ local function processTextDependency(dependency, meta)
    if meta[textLoc] == nil then
       meta[textLoc] = {}
    end
-   meta[textLoc]:insert(pandoc.RawBlock(FORMAT, rawText.text))
+   local rawFormat = FORMAT
+   -- Some output formats requires raw blocks in another format
+   if format.isHtmlSlideOutput() then 
+      rawFormat = "html"
+   elseif format.isLatexOutput() then
+      rawFormat = "latex"
+   end
+   meta[textLoc]:insert(pandoc.RawBlock(rawFormat, rawText.text))
  end
````

**Comment by cderv** [comment]
> I didn't find the code in Pandoc code where under which contidion a rawBlock is ignored or not. cc @tarleb as you could be interested in this.

Ok found it. 

https://github.com/jgm/pandoc/blob/4a6950200ff148b44b38c20f015100bb4d7e5033/src/Text/Pandoc/Writers/HTML.hs#L908-L920

This check for `html` only and not revealjs.
https://github.com/jgm/pandoc/blob/4a6950200ff148b44b38c20f015100bb4d7e5033/src/Text/Pandoc/Writers/HTML.hs#L1737-L1741

LaTeX handle beamer format ok 
https://github.com/jgm/pandoc/blob/4a6950200ff148b44b38c20f015100bb4d7e5033/src/Text/Pandoc/Writers/LaTeX.hs#L467-L474

I would think this is an issue in Pandoc. We'll see what they answer.

**Comment by cderv** [comment]
So @dragonstyle this will be an issue for sure with current pandoc with all HTML slide formats that are defined in the `writer.hs`

https://github.com/jgm/pandoc/blob/4a6950200ff148b44b38c20f015100bb4d7e5033/src/Text/Pandoc/Writers/HTML.hs#L26-L30
```
  writeS5,
  writeSlidy,
  writeSlideous,
  writeDZSlides,
  writeRevealJs,
```

We could patch only those, or look into all the writers to find all the possible format that are not correctly handle as raw block.

**Comment by cscheid** [comment]
We can add a `quarto-post` filter pass that takes the "sub-html" raw blocks like `revealjs` and re-issues them as `html`. Would that solve the problem?

**Comment by cderv** [comment]
Issue has been opened upstream, so it could be fixed in next Pandoc maybe 

* https://github.com/jgm/pandoc/issues/8880

**Comment by coatless** [comment]
Submitted a PR to Pandoc (https://github.com/jgm/pandoc/pull/9110) that covers just the HTML writer for the moment. We'll see what happens next.

**Comment by dlsun** [comment]
The [upstream fix](https://github.com/jgm/pandoc/pull/9110) has been merged into Pandoc. So are we now just waiting for the next version of Pandoc to be released and then for Quarto to re-build with the new Pandoc?

**Comment by mcanouil** [comment]
Basically yes, but note that this will only be available in the 1.4 pre-release.

**Comment by coatless** [comment]
Pandoc v3.1.9 was just released yesterday and included a fix for this.

https://github.com/jgm/pandoc/releases/tag/3.1.9

Can the included pandoc version in Quarto get upgraded this week? Unfortunately, I can't bump the version in an official way given dependencies are cached in an RStudio/Posit S3 bucket.

**Comment by cscheid** [comment]
> Can the included pandoc version in Quarto get upgraded this week?

Hopefully. We'll try to get it done quickly (and certainly before 1.4 is out), but in general we can't promise a specific time.

**Comment by coatless** [comment]
I think this was just taken care of in PR https://github.com/quarto-dev/quarto-cli/pull/7419. So, I'm going to close out this issue and _eagerly_ awaiting for the pre-release binaries to be updated. 

Thank you for fast-tracking an update @cscheid!
