### ISSUE TITLE
"ERROR: The format pdf does not support providing any template partials" with quarto-journals/elsevier and tinytex

### ISSUE THREAD

**Issue by VladimirAlexiev** [quarto-dev/quarto-cli#5677]
### Bug description

```
# quarto use template quarto-journals/elsevier
# quarto install tool tinytex
```
Edit `paper.qmd` preamble and put that `pdf-engine`. So now it looks like:
```yaml
format:
  elsevier-pdf:
    pdf-engine: tinytex
    keep-tex: true
    journal:
      name: Automation in Construction
      formatting: preprint
      model: 3p
      cite-style: super
```

Then:
```
# quarto render paper.qmd --log-level info --log log.txt --debug
## quarto render paper.qmd --log-level info --log log.txt --debug --to elsevier-pdf : same result
ERROR: The format pdf does not support providing any template partials.

Error: The format pdf does not support providing any template partials.
    at runPandoc (file:///C:/Program%20Files/Quarto/bin/quarto.js:80075:23)
    at async renderPandoc (file:///C:/Program%20Files/Quarto/bin/quarto.js:81042:26)
    at async Object.onRender (file:///C:/Program%20Files/Quarto/bin/quarto.js:86671:36)
    at async renderFiles (file:///C:/Program%20Files/Quarto/bin/quarto.js:86634:25)
    at async render (file:///C:/Program%20Files/Quarto/bin/quarto.js:90678:21)
    at async Command.fn (file:///C:/Program%20Files/Quarto/bin/quarto.js:90853:32)
    at async Command.execute (file:///C:/Program%20Files/Quarto/bin/quarto.js:8437:13)
    at async quarto (file:///C:/Program%20Files/Quarto/bin/quarto.js:127539:5)
    at async file:///C:/Program%20Files/Quarto/bin/quarto.js:127557:9
```
A similar problem is discussed in https://github.com/quarto-dev/quarto-cli/discussions/1555 
and was diagnosed by @dragonstyle to " incorrectly configuring our PDF rendering when the engine was `latexmk`".

I'm trying to use `tinytex` as recommended at https://quarto.org/docs/output-formats/pdf-engine.html ,
and I don't have any `template-partials` in the preamble (but I guess that `quarto-journals/elsevier` uses them extensively)

Versions:
```
# uname
CYGWIN_NT-10.0

# quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.353
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: C:/Python310/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

The complete `paper.qmd` is below:
````markdown
---
title: Short Paper
subtitle: A Short Subtitle
author:
  - name: Alice Anonymous
    email: alice@example.com
    affiliations: 
        - id: some-tech
          name: Some Institute of Technology
          department: Department Name
          address: Street Address
          city: City
          state: State
          postal-code: Postal Code
    attributes:
        corresponding: true
    note: This is the first author footnote.
  - name: Bob Security
    email: bob@example.com
    affiliations:
        - id: another-u
          name: Another University
          department: Department Name
          address: Street Address
          city: City
          state: State
          postal-code: Postal Code
    note: |
      Another author footnote, this is a very long footnote and it should be a really long footnote. But this footnote is not yet sufficiently long enough to make two lines of footnote text.
  - name: Cat Memes
    email: cat@example.com
    affiliations:
        - ref: another-u
    note: Yet another author footnote.
  - name: Derek Zoolander
    email: derek@example.com
    affilations:
        - ref: some-tech
abstract: |
  This is the abstract. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum augue turpis, dictum non malesuada a, volutpat eget velit. Nam placerat turpis purus, eu tristique ex tincidunt et. Mauris sed augue eget turpis ultrices tincidunt. Sed et mi in leo porta egestas. Aliquam non laoreet velit. Nunc quis ex vitae eros aliquet auctor nec ac libero. Duis laoreet sapien eu mi luctus, in bibendum leo molestie. Sed hendrerit diam diam, ac dapibus nisl volutpat vitae. Aliquam bibendum varius libero, eu efficitur justo rutrum at. Sed at tempus elit.
keywords: 
  - keyword1
  - keyword2
date: last-modified
bibliography: bibliography.bib
format:
  elsevier-pdf:
    pdf-engine: tinytex
    keep-tex: true
    journal:
      name: Automation in Construction
      formatting: preprint
      model: 3p
      cite-style: super
---

Please make sure that your manuscript follows the guidelines in the 
Guide for Authors of the relevant journal. It is not necessary to 
typeset your manuscript in exactly the same way as an article, 
unless you are submitting to a camera-ready copy (CRC) journal.

For detailed instructions regarding the elsevier article class, see   <https://www.elsevier.com/authors/policies-and-guidelines/latex-instructions>

# Bibliography styles

Here are two sample references:  @Feynman1963118 @Dirac1953888.

By default, natbib will be used with the `authoryear` style, set in `classoption` variable in YAML. 
You can sets extra options with `natbiboptions` variable in YAML header. Example 

```
natbiboptions: longnamesfirst,angle,semicolon
```

There are various more specific bibliography styles available at
<https://support.stmdocs.in/wiki/index.php?title=Model-wise_bibliographic_style_files>. 
To use one of these, add it in the header using, for example, `biblio-style: model1-num-names`.

## Using CSL 

If `cite-method` is set to `citeproc` in `elsevier_article()`, then pandoc is used for citations instead of `natbib`. In this case, the `csl` option is used to format the references. By default, this template will provide an appropriate style, but alternative `csl` files are available from <https://www.zotero.org/styles?q=elsevier>. These can be downloaded
and stored locally, or the url can be used as in the example header.

# Equations

Here is an equation:
$$ 
  f_{X}(x) = \left(\frac{\alpha}{\beta}\right)
  \left(\frac{x}{\beta}\right)^{\alpha-1}
  e^{-\left(\frac{x}{\beta}\right)^{\alpha}}; 
  \alpha,\beta,x > 0 .
$$

Inline equations work as well: $\sum_{i = 2}^\infty\{\alpha_i^\beta\}$

# Figures and tables

@fig-meaningless is generated 

# Tables

Tables can also be generated, as shown in @tbl-simple example.

# References {-}
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
`tinytex` is not a PDF engine, it's a Tex distribution, thus the exact same issue you mentionned (#1555).

For example, I am using TinyTex LaTeX distribution with the default pdf engine (xelatex).

```bash
tlmgr --version
#> tlmgr revision 66798 (2023-04-08 02:15:21 +0200)
#> tlmgr using installation: /Users/mcanouil/Library/TinyTeX
#> TeX Live (https://tug.org/texlive) version 2023
```

**Comment by cderv** [comment]
Thanks @mcanouil. I believe TinyTeX was correctly installed as @VladimirAlexiev shared as a step to reproduce its installation.
> ```
> quarto install tool tinytex
> ```

As here @VladimirAlexiev said in #5678, `xelatex` is not working for him. hence here tried changing the `pdf-engine` value. 

I don't think it is a LaTeX issue here.  The error does not seems related oddly... 🤔 I am looking into it.

**Comment by cderv** [comment]
> However I don't think this is the issue. Do you get the same by changing to pdf-engine: pdflatex ?

@VladimirAlexiev I confirm this is because you used `pdf-engine: tinytex` that you get this issue. So do set a valid engine.

I still believe this is a weird issue as it is not related directly to a `pdf-engine`

@dragonstyle you could be interesting into this. I am surprised this is the issue you get when providing a non pdf latex engine. 

Issue is here that we skip this because of `pdf-engine: tinytex`
https://github.com/quarto-dev/quarto-cli/blob/4b7c0fe6c42bb69b0f343c04bdcc0bf108b11e86/src/command/render/output.ts#L80-L81

and this lead to an error with the `template-partials` - quite cryptic. Any idea ?

**Comment by dragonstyle** [comment]
I am thinking the issue is that the format extension is providing template partials but that because the PDF engine is not well specified, we are likely not creating the proper template context for the PDF format. It feels to me like we should be throwing a validation error when the value of `pdf-engine` isn't something we expect.

**Comment by dragonstyle** [comment]
> This means to have an exhaustive (updatable) list of PDF engines to render LaTeX though.

That doesn't seem too tall of an order - Pandoc has a limited supported list and ours is even a subset of that since we treat pdf engines like `ConTeXt` and `typst` as formats...

**Comment by cderv** [comment]
Glad it solve this for you ! 

@dragonstyle should we keep this open regarding the `pdf-engine` checking for unknown value ? It seems important. Maybe better tracked idea in a new issue though

**Comment by dragonstyle** [comment]
I went ahead and opened a fresh issue to track improving our validation. Thanks all!

**Comment by VladimirAlexiev** [comment]
@cderv @dragonstyle I posted a small doc fix.

https://quarto.org/docs/output-formats/pdf-engine.html says
> We also recommend the use of Quarto's built in PDF compilation engine, which among other things performs automatic installation of any missing TeX packages.

Which is this builtin engine? It's worth mentioning this in the doc.

**Comment by cderv** [comment]
You mean adding a link to the section below this sentence called Quarto PDF engine at https://quarto.org/docs/output-formats/pdf-engine.html#quarto-pdf-engine ? Or rather which value to set for `pdf-engine` key in YAML ?
