### ISSUE TITLE
Observable inputs fail to render, non-reproducibly

### ISSUE THREAD

**Issue by ijlyttle** [quarto-dev/quarto-cli#568]
First of all, really digging Quarto - glad to use it "for real" now! 

I've got a bunch of things that have come-up with Observable, I'll post issues in order of importance :)

I'm afraid the most important thing is not really reproducible, but it does happen very often.

Here's a project I'm working on, it has an Observable chapter: https://ijlyttle.github.io/reactivity-three-ways-quarto/observable.html#showcase

The first time the page loads, things seem to go well - generally.

When I reload the page, Observable inputs fail to render, and a console message appears:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/2800934/162200332-d7d10abb-0a6f-4ab3-90a3-707c7a1e0bde.png">

I noticed this happening as I added inputs to a page - the page has nine Observable inputs, I started noticing this as I went beyond five.

FWIW, this happens both on my local machine, and when deployed on gh-pages.

(Link to the source, if interested: https://github.com/ijlyttle/reactivity-three-ways-quarto)

Thanks!

**Comment by jjallaire** [comment]
I know that @cscheid has some Observable work in flight right now so hopefully it will be a convenient time to address some of the issues you identify. One thing which we have seen is issues w/ performance and reliability of CDN hosted observable runtime JS. As a result I believe we are moving to embedding these components so they can run entirely self-contained (no external CDN calls).

**Comment by ijlyttle** [comment]
Thanks - I know I unloaded a bunch of stuff here, so I very much appreciate you having a looking at it, especially @cscheid!

**Comment by ijlyttle** [comment]
Thanks! 

On my local machine, if I use the "standard" version of arquero (removing the import cell), the problem does not appear.

I'll leave the GitHub version alone for now, to keep something to test against.

**Comment by cscheid** [comment]
@arbelt Thanks, I can reproduce this, and I think the issues are indeed related. There's some race condition on the imports which doesn't appear to happen on observablehq.com. I've improved our error reporting so that on `main` you'll at least see this now:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/285675/168893456-058ef9c5-79f3-43aa-a485-3b2116fb69fc.png">

I'll investigate and report back.

**Comment by cscheid** [comment]
@arbelt I believe I fixed your specific case on our latest commit. We're creating a new quarto release, 0.9.427. Once that's available you can try it (or if you're running from source, anything later than 97b69958010cc5321b2e8d688d189b2a7d52d9f0 should work.)

@ijlyttle I'm not sure if this is the same race condition you were seeing. I'll check and report back

**Comment by cscheid** [comment]
It seems that this commit fixed the race condition in import cases as well, so I'm going to go ahead and close the issue. @ijlyttle if you still run into trouble, please reopen this.

**Comment by arbelt** [comment]
Thanks for sorting this so quickly!

**Comment by cscheid** [comment]
@arbelt your repro made it easy to track it down; thank _you_!

**Comment by ijlyttle** [comment]
thanks @cscheid  and @arbelt!
