### ISSUE TITLE
[Website] Not possible to download pre-release (v1.4)

### ISSUE THREAD

**Issue by GegznaV** [quarto-dev/quarto-cli#5684]
### Bug description

On https://quarto.org/docs/download/ not possible to download v1.4 anymore:

![image](https://github.com/quarto-dev/quarto-cli/assets/12725868/7388a758-13d3-419f-a7ad-66d0211f92ac)

**Comment by dragonstyle** [comment]
Looking at this now.

**Comment by dragonstyle** [comment]
This is being caused by shortcodes attempting to render the escaped shortcode that appears in docs/authoring/markdown-basics.qmd:

```
You can include videos in documents using the `{{{< video >}}}` shortcode. For example, here we embed a YouTube video:
```

I will pin to an older version of Quarto to get builds going again.

**Comment by cscheid** [comment]
A partial followup.

> /opt/quarto/share/extensions/quarto/video/video.lua:295: attempt to call a nil value (global 'fail')

This call shouldn't work; "fail" is not exposed to shortcode lua files; it's only defined in `src/resources/filters/common/debug.lua` and not exposed in general. This is a bug on `video.lua` that we should fix.
