### ISSUE TITLE
Figure caption error with multibyte characters and non-English locale

### ISSUE THREAD

**Issue by Gedevan-Aleksizde** [quarto-dev/quarto-cli#57]
I found the follwing error when I render a qmd file which contains multibyte characters in `fig.cap` under non-English locale (`jp_JP.utf8`, Ubuntu 20.04 on WSL2).

```
quarto render reprex.qmd

...

Error in yaml::yaml.load(yaml, eval.expr = TRUE):
  Scanner error: while scanning a quoted scalar at line 1, column 10 found unexpected end of stream at line 1, column 12
Calls: .main ... parse_block -> partition_yaml_options -> <Anonymous>
Execution halted
```

`reprex.qmd` is like this.

````
---
title: "Untitled"
format:
  html:
    theme: default
---

```{r}
#| fig.cap: "α"
plot(1)
```
````

I can avoid this error by executing `LOCALE=en_US.utf8 quarto render ....` in the terminal. But it's inconvenient on RStudio.

NOTE: Pandoc's native syntax (like `![Elephant](elephant.png)`) doesn't return error.

**Comment by jjallaire** [comment]
Thanks for reporting! This should be the fix: https://github.com/quarto-dev/quarto-cli/commit/4e4cf10268bc2d9be2b32eb8802e993c908ac31e

Available in the latest release: https://github.com/quarto-dev/quarto-cli/releases/tag/v0.2.12

**Comment by Gedevan-Aleksizde** [comment]
Great. I confirmed this issue is fixed.
