### ISSUE TITLE
Observable `Inputs.table()` formatting

### ISSUE THREAD

**Issue by ijlyttle** [quarto-dev/quarto-cli#570]
When a table input renders, it seems to cut off the left edge (the selection check-boxes):

<img width="788" alt="image" src="https://user-images.githubusercontent.com/2800934/162205538-b87602b2-16be-488d-8afa-259c4826fc5b.png">

**Comment by cscheid** [comment]
You're right - I missed this because by default they're not selected, and they render as such:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/285675/162225345-49aa9080-3d9e-4531-826a-52404d829281.png">

I'm working on a fix right now.

**Comment by cscheid** [comment]
I don't super love the default look now, but at least the checkboxes don't get truncated:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/285675/162240137-69dcc47b-4a59-44b3-aa3f-9aef568e9dbf.png">
Thanks for the report!

**Comment by ijlyttle** [comment]
I'm with you on the default look.

It would be a question for the Observable folks, but I wonder if there could be an option to suppress the check-boxes, i.e. a read-only mode.

Thanks!

**Comment by cscheid** [comment]
Unfortunately we don't control Observable's behavior here, so we're limited on what we can do.

**Comment by ijlyttle** [comment]
Understood and agree.

I am tempted to fiddle with the workaround suggested, but I realize it will just blow up in may face if/when they add the option to suppress :)
