### ISSUE TITLE
Slider appears when hovering for code annotations

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#5700]
### Bug description

When hovering on a code annotation and the corresponding code is highlighted, there is a slider appearing at the bottom like this. Perhaps the highlighting is a tad too wide?

![ss1](https://github.com/quarto-dev/quarto-cli/assets/45770265/40f89e19-ac7a-4bd1-9e8f-1315af51ca28)
![ss2](https://github.com/quarto-dev/quarto-cli/assets/45770265/45d133bc-7d6e-434e-b39b-8f8f11cd34d6)

This is using Quarto v. 1.4.90 on Windows.

Minimal example:

	---
	format: 
	  html:
		code-annotations: hover
	---

	```{r}
	test <- mtcars # <1>
	```
	1. Annotations

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
I am not able to reproduce this on MacOS Safari or Chrome. It may be browser/platform specific and could also be affected by any other CSS styling or themes in play. Can you share a little more info about where you see this happening?

**Comment by snhansen** [comment]
@dragonstyle: It's triggered by all code annotations when hovering is enabled. I tried Firefox, Chrome and Edge, and the slider appears using all of them. I've uploaded the compiled minimal example to here <https://biostat.au.dk/stefan/test/test.html>, so you can see if it appears on your browser.

I haven't used any custom CSS styling, it's literally just the code from the minimal example above.

**Comment by snhansen** [comment]
@dragonstyle: Very odd. I just checked with a Mac myself, and I'm not seeing it there either. But it's definitely present on Windows 10. Firefox on my Android phone has it briefly when clicking the annotation number, but disappears hereafter.

**Comment by dragonstyle** [comment]
Ok I can take a look on a Windows machine, thanks for helping me narrow it down!

**Comment by dragonstyle** [comment]
I can confirm I'm seeing it on windows too!
