### ISSUE TITLE
Website crash, possible memory leak

### ISSUE THREAD

**Issue by scottamain** [quarto-dev/quarto-cli#5708]
### Bug description

Adding `?q=&` to just about any URL will crash the page. This happens on my site built with Quarto, but also yours (and others I tried in your website gallery). For example: https://quarto.org/docs/get-started/?q=&

### Steps to reproduce

Go to  https://quarto.org/docs/get-started/?q=&

### Expected behavior

Page loads

### Actual behavior

Page starts loading and keeps going, eventually crashing:

![Screenshot 2023-05-26 at 11 08 29 AM](https://github.com/quarto-dev/quarto-cli/assets/1672461/2918bbc0-adef-4bfb-a02e-f5e68ecd9b56)

In Safari, it takes much longer to stop trying:

![Screenshot 2023-05-26 at 11 13 44 AM](https://github.com/quarto-dev/quarto-cli/assets/1672461/10e28e28-b873-48b1-b9d3-2695dca19e50)

### Your environment

macOS 13.3.1, Chrome 112.0.5615.137 and Safari 16.4 (18615.1.26.110.1)

**Comment by cscheid** [comment]
@scottamain Thanks for the report. how did you construct this URL, if you don't mind my asking?

This seems like an Algolia bug to me (in that it should detect and disallow this kind of obviously-going-to-DOS-us request), but given that it happens, we definitely should be working around it on our side.

**Comment by dragonstyle** [comment]
(I think the issue is actually likely that we're doing match highlighting on the page and are getting stuck in a loop trying to highlight these matches in some malformed way...)

**Comment by scottamain** [comment]
Thanks @cscheid, this was actually reported to me by one of our website users.
