### ISSUE TITLE
Observable buttons formatting

### ISSUE THREAD

**Issue by ijlyttle** [quarto-dev/quarto-cli#571]
I know I'm getting picky with this one.
I realize it's tricky because there are competing styles from Observable and Bootstrap, but I'm wondering if there's a way to apply Bootstrap styling here:

```js
viewof clicks = Inputs.button("OK", {label: "Click me"})
```

<img width="246" alt="image" src="https://user-images.githubusercontent.com/2800934/162206802-6068f0a2-7788-45f3-9516-e81b33e724f2.png">

I think would get trickier to try to apply different classes, e.g. `"btn-primary"` and `"btn-success"`, within an `Inputs.form()`, so I open this issue with some hesitation.

**Comment by cscheid** [comment]
There should be. You've noticed that our CSS support is pretty patchy right now, and needs some good TLC. A full pass over the ojs engine is on my timeline between now and conf, so stay tuned :)

**Comment by cscheid** [comment]
With @dragonstyle's mad SCSS skills, we've now improved this. The default looks quite a bit better now:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/285675/167728730-7b6d6a1e-d42b-4663-8093-841af3ebc185.png">

And, more importantly, we have SCSS variables that you can customize in case you want to change the behavior. These are `btn-bg` and `btn-fg`. We expect to do a longer CSS pass over observable after June 1st, but this should help you right now.

**Comment by ijlyttle** [comment]
Wonderful! Thanks, @dragonstyle and @cscheid!
