### ISSUE TITLE
The Zip File Release for Windows (`quarto-1.3.361-win.zip`) Is Missing

### ISSUE THREAD

**Issue by RoyiAvital** [quarto-dev/quarto-cli#5716]
### Bug description

The latest release, `quarto-1.3.361` is missing the Windows ZIP file: `quarto-1.3.361-win.zip`.

**Comment by mcanouil** [comment]
![image](https://github.com/quarto-dev/quarto-cli/assets/8896044/51b0fc61-51b9-46b1-b087-41eae6293369)

What's missing exactly?

**Comment by RoyiAvital** [comment]
That's strange, it was missing on my side.
I now reloaded without cache and it shoed up.

Sorry for the trouble.

**Comment by mcanouil** [comment]
The build is not old, since the release can appear before all assets are ready and attached to it, it might have been attached a bit later.
For these things, better to be a little patient.
