### ISSUE TITLE
Observable inputs in dark mode

### ISSUE THREAD

**Issue by ijlyttle** [quarto-dev/quarto-cli#572]
I *know* I'm getting picky, here :)

I suspect part of the problem here is that Observable itself has [stepped back from supporting dark mode](https://talk.observablehq.com/t/feature-unannouncement-dark-mode/1440).

When I invoke dark-mode, some inputs stay partially in light-mode:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/2800934/162208187-5cee0aa4-ed80-4a1e-af1c-2adfdf03f07e.png">

<img width="404" alt="image" src="https://user-images.githubusercontent.com/2800934/162208254-c925a983-a3a9-4deb-bd17-32c16cbee6c8.png">

<img width="130" alt="image" src="https://user-images.githubusercontent.com/2800934/162208297-b25dc73d-e65e-46b3-883e-767713f6b5ff.png">

Again, I suspect this comes down to competing styles...

**Comment by cscheid** [comment]
We won't be able to generally handle all of the possible styling combinations. But you can add your own CSS. You have to be a little sneaky to find a selector that has higher specificity than the ones provided by observablehq's runtime, but this general kind of trick works:

```html
<style>
    div.observablehq table {
        background-color: red;
    }
</style>
```

And you get: (:scream:)

<img width="707" alt="image" src="https://user-images.githubusercontent.com/285675/167730175-2cd84f2e-65ba-4c30-a0c1-b0a3a34ed1aa.png">

**Comment by ijlyttle** [comment]
Thanks! I'll wrestle with it some...

**Comment by ijlyttle** [comment]
FWIW, here's what I added:

```css
div.observablehq table thead tr th {
    background-color: var(--bs-body-bg);
}

input, button, select, optgroup, textarea {
    background-color: var(--bs-body-bg);
}
```

It seemed to do the trick: https://ijlyttle.github.io/reactivity-three-ways-quarto/observable.html#showcase

Thanks!
