### ISSUE TITLE
Shortcodes no longer read in "HTML tables with embedded markdown"

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#5730]
### Bug description

As with the current development version of Quarto, the shortcodes are no longer read in "HTML tables with embedded markdown" (1.3 feature).

### Steps to reproduce

Render the following document using Quarto 1.3.361 and development version:

````qmd
---
format: html
---

```{=html}
<table>
  <caption><span data-qmd="As described in @Lovelace1864, computers are great."></span></caption>
  <thead>
    <tr>
      <th><span data-qmd="_Header 1_"></span></th>
      <th><span data-qmd="_Header 2_"></span></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><span data-qmd="{{< video https://www.youtube.com/embed/wo9vZccmqwc >}}"></span></td>
      <td>Regular output</td>
    </tr>
  </tbody>
</table>
```
````

### Expected behavior

<img width="733" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/b4201521-1628-4831-bc78-fc34bbd623c4">

### Actual behavior

<img width="732" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/78fd225f-0447-4dd0-879d-e32e29fbb7ad">

### Your environment

- IDE: VSCode Insiders
- OS: macOS Ventura 13.4

### Quarto check output

<img width="1202" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/c2a717f3-02c5-4b23-99f1-aab424d5ad19">

**Comment by mcanouil** [comment]
Additional note, in the example, there is a cross-reference, but it does not work in 1.3.361 or development version. Is it supposed to work?

**Comment by cscheid** [comment]
Thanks for the report! This is fixed now.
