### ISSUE TITLE
Trying to install chromium tool fails

### ISSUE THREAD

**Issue by DhruvaSambrani** [quarto-dev/quarto-cli#5732]
### Bug description

Chromium does not install

### Steps to reproduce

In any project, running `quarto install tool chromium` fails.

### Expected behavior

Should install successfully

### Actual behavior

```
ERROR: TypeError: Relative import path "puppeteer/mod.ts" not prefixed with / or ./ or ../

Stack trace:
    at async getPuppeteer (file:///opt/quarto/bin/quarto.js:35241:24)
    at async fetcher (file:///opt/quarto/bin/quarto.js:35370:22)
    at async Object.installed (file:///opt/quarto/bin/quarto.js:35300:24)
    at async toolSummary (file:///opt/quarto/bin/quarto.js:82880:27)
    at async updateOrInstallTool (file:///opt/quarto/bin/quarto.js:83039:21)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:86622:17)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8104:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:102201:5)
    at async file:///opt/quarto/bin/quarto.js:102219:9
```

### Your environment

OS: Arch Linux

### Quarto check output

<details>
<summary>
<pre>quarto check</pre>
</summary>
<pre>

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.78
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /home/dhruva/.julia/conda/3/x86_64/bin/python3.10
      Jupyter: 5.2.0
      Kernels: julia-1.9, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
</pre>
</details>

**Comment by mcanouil** [comment]
I can reproduce, thanks for the report.

- Latest stable
  ```sh
  docker container run --platform linux/amd64 -it --rm ghcr.io/quarto-dev/quarto:1.3.361 quarto install chromium
  ```
  <img width="799" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/58323269-9a26-4a93-a02c-b0eb59ba4b31">
- Latest pre-release
  ```sh
  docker container run --platform linux/amd64 -it --rm ghcr.io/quarto-dev/quarto:1.4.104 quarto install chromium
  ```
  <img width="816" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/3dcf9d33-437a-45b7-a10d-f4212704073e">

**Comment by cscheid** [comment]
(just adding context) This doesn't appear to happen for me on OS X in our dev builds.

**Comment by mcanouil** [comment]
I have to admit that I did not test directly on macOS, because I don't want chromium.
At least, with the Docker images, you have a not working environment 😏

**Comment by cderv** [comment]
FWIW no problem installing chromium on Windows.

**Comment by DhruvaSambrani** [comment]
Probably fixed in https://github.com/quarto-dev/quarto-cli/commit/e69c6ec2898b84ba2073cba57c433742d7b3051e, it now works on pre-release (`1.4.130`<)
