### ISSUE TITLE
`embed-resources: true` in a project causes "shared" `libs` to be embedded

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#5748]
### Bug description

When inside a project such as a website, if the last document to be rendered includes `embed-resources: true`, the shared "libs" is embedded, thus is missing for the project.

Behaviour initially discovered in #5738.

`embed-resources` should raise a warning and be ignored inside a Quarto project.

### Steps to reproduce

````sh
cat << EOF > _quarto.yml
project:
  type: website

website:
  title: "Quarto-project-embed-resources"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - zzz.qmd
      
EOF

cat << EOF > index.qmd
---
title: "Quarto-project-embed-resources"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

EOF


cat << EOF > zzz.qmd
---
title: 'Reveal.js Presentation'
format: revealjs
embed-resources: true
---

## Slide

EOF
````

```sh
quarto render
```

### Expected behavior

```
tree _site -L 2
_site
├── index.html
├── search.json
├── site_libs
│   ├── bootstrap
│   ├── clipboard
│   ├── quarto-html
│   ├── quarto-nav
│   ├── quarto-search
│   └── revealjs
└── zzz.html

8 directories, 3 files
```

### Actual behavior

```
tree _site -L 2
_site
├── index.html
├── search.json
└── zzz.html

1 directory, 3 files
```

### Your environment

- VSCode Insiders
- macOS Ventura 13.4

### Quarto check output

<img width="1111" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/3fed9b29-585b-4db5-9c00-5260af2b8afb">

**Comment by cderv** [comment]
> Behaviour initially discovered in https://github.com/quarto-dev/quarto-cli/issues/5738.

To give more context on this : The behavior described here causes the shared lib to be removed, and thus deleted when publishing (e.g to `gh-pages`). We got two report of non-working website because of this and the GHA logs shows clearly removal of the shared lib dir. 

Thanks to @mcanouil we now know why.

**Comment by dragonstyle** [comment]
Note to self - doesn't appear to be a way for Pandoc to not 'clean up' the ingested resources, so we may just have to disable this for website projects.

Could consider attempting to decorate the `libs` script and CSS tags with `data-external="1"` but not sure how effectively we'll be able to ensure that all are decorated.

**Comment by dragonstyle** [comment]
I'm actually not 100% sure of that - if we are the ones cleaning things up, it would actually be pretty awesome since it would be much more straightforward to fix!

**Comment by dragonstyle** [comment]
In fact, this looks awfully suspicious:

```
      withTiming("render-cleanup", () =>
        renderCleanup(
          context.target.input,
          finalOutput!,
          format,
          selfContained! ? supporting : undefined,
          executionEngineKeepMd(context.target.input),
        ));

```

**Comment by cderv** [comment]
From my R Markdown and Pandoc experience, I don't think Pandoc will remove any resources. So I would say we do it ourself, and we could indeed fix it. Probably where you found the suspicious part...
