### ISSUE TITLE
[FR] Replace "Cell 1/N" by label (if provided) when using Jupyter

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#5752]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5714

<div type='discussions-op-text'>

<sup>Originally posted by **bryanwhiting** May 27, 2023</sup>
### Description

This isn't helpful:
```
Cell 1/20...Done
  Cell 2/20...Done
  Cell 3/20...Done
  Cell 4/20...Done
  Cell 5/20...Done
  Cell 6/20...Done
  ```

What would be helpful is for it to print the name of the code chunk, like Rmarkdown does.</div>

**Comment by mcanouil** [comment]
This seems to be a small modification of:

https://github.com/quarto-dev/quarto-cli/blob/f42c7a990680ba8158db3c0a029ac4ac7a367df5/src/resources/jupyter/notebook.py#L161-L165

**Comment by jssonx** [comment]
Hi @mcanouil ,

I hope you're doing well. I came across this issue and found it interesting. I believe I have the skills and experience to contribute to resolving this problem. If you don't mind, I'd like to give it a try and submit a pull request for your review.

Please let me know if there's any specific information or guidelines I should be aware of before starting. I'm looking forward to contributing to your project and working together to improve it.

Thank you for your time and consideration.

Best regards,
jsson

**Comment by mcanouil** [comment]
Here are the contributing guidelines: <https://github.com/quarto-dev/quarto-cli/blob/main/.github/CONTRIBUTING.md>.

**Comment by jssonx** [comment]
> Here are the contributing guidelines: https://github.com/quarto-dev/quarto-cli/blob/main/.github/CONTRIBUTING.md.
> 
> Small implementation thing, I would personally keep the "Cell 1/N" format, but add the label from `label` option if not empty. Maybe: `" Cell '<label>' {0}/{1}..."`

Thank you for sharing the contributing guidelines. I completely agree with your implementation suggestion to keep the "Cell 1/N" format and add the label when available. I'll go ahead and work in that direction.

**Comment by jssonx** [comment]
Hi @mcanouil,

I've resolved the discussed issue and submitted a PR. All checks have passed. If there are any adjustments or modifications needed, I'm more than willing to make them. Thank you!

-Jsson
