### ISSUE TITLE
GraphViz dot graph not rendering in chunk but on full render

### ISSUE THREAD

**Issue by Obsidian-user** [quarto-dev/quarto-cli#5769]
### Bug description

When trying to run the Graphviz/dot template from the Quatro diagram's page in a chunk with Ctrl/Cmd+Enter, I get an error. When I select `Render on Save` the correct diagram is produced.

Perhaps this is intended behaviour, but `nomnoml` has an option for a RMarkdown chunk where only that chunk is rendered.

### Steps to reproduce

````{quatro}
```{dot}
graph G {
  layout=neato
  run -- intr;
  intr -- runbl;
  runbl -- run;
  run -- kernel;
  kernel -- zombie;
  kernel -- sleep;
  kernel -- runmem;
  sleep -- swap;
  swap -- runswap;
  runswap -- new;
  runswap -- runmem;
  new -- runmem;
  sleep -- runmem;
}
```
````

### Expected behavior

A diagram is produced at the bottom of the chunk

### Actual behavior

```
running: dot dot12e8d768ebc4.dot -T -o dot12e8d768ebc4.dot
Warning in system2(cmd, shQuote(a), stdout = TRUE, stderr = f2, env = options$engine.env) :
  running command ''dot' 'dot12e8d768ebc4.dot' '-T' '-o' 'dot12e8d768ebc4.dot' 2> 'dot12e8d794e94a8'' had status 1
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  Missing argument for -T flag
Usage: dot [-Vv?] [-(GNE)name=val] [-(KTlso)<val>] <dot files>
(additional options for neato)    [-x] [-n<v>]
(additional options for fdp)      [-L(gO)] [-L(nUCT)<val>]
(additional options for memtest)  [-m<v>]
(additional options for config)  [-cv]

 -V          - Print version and exit
 -v          - Enable verbose mode 
 -Gname=val  - Set graph attribute 'name' to 'val'
 -Nname=val  - Set node attribute 'name' to 'val'
 -Ename=val  - Set edge attribute 'name' to 'val'
 -Tv         - Set output format to 'v'
 -Kv         - Set layout engine to 'v' (overrides default based on command name)
 -lv         - Use external library 'v'
 -ofile      - Write output to 'file'
 -O          - Automatically generate an output filename based on the input filename with a .'format' appended. (Causes all -ofile options to be ignored.) 
 -P          - Internally generate a graph of the current plugins. 
 -q[l]       - Set level of message suppression (=1)
 -s[v]  
```

### Your environment

- IDE: RStudio 2023.03.1+446
- OS: MacOS Ventura 13.4

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: python3

(\) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Thanks for the report.

> page in a chunk with Ctrl/Cmd+Enter

I think this means you're filing a bug about your IDE/editor support for quarto. In that case, you should file it with https://github.com/quarto-dev/quarto. This repo is for the command-line `quarto` utility.

**Comment by Obsidian-user** [comment]
Thank you for your help and polite response.

I've raised the issue with the RStudio.

Here is the link for those who may find this thread in the future.

https://github.com/rstudio/rstudio/issues/13187
