### ISSUE TITLE
Quarto documents using R fail when using reticulate from within an R package

### ISSUE THREAD

**Issue by jburos** [quarto-dev/quarto-cli#577]
I am having trouble rendering quarto docs using R, where the R code uses a package that calls out to a python method via reticulate.

I created a minimal example using a very simple R package (`botor`) wrapping python's `boto3` library.

    ---
    title: "Test R package with reticulate"
    format: html
    ---
    
    ```{r load-library}
    library(botor)
    ```
    
    Check the current AWS user’s name:
    
    ```{r whoami}
    iam_whoami()
    ```
    
    ```{r get_user}
    iam()$get_user()
    ```
    
Saving as a qmd file & rendering using quarto results in a failure in the `whoami` block. The same file renders fine as an Rmd file using `rmarkdown::render`.

I have observed the same behavior when using another package referencing a python library via reticulate, always in the block that calls out to the Python library.
  
The log looks like the following:

```
MacBook-Pro-8:deliverables jburos$ quarto render examples/Test-quarto-with-reticulate.qmd 


processing file: Test-quarto-with-reticulate.qmd
  |..........                                                            |  14%
  ordinary text without R code

  |....................                                                  |  29%
label: load-library
  |..............................                                        |  43%
  ordinary text without R code

  |........................................                              |  57%
label: whoami
MacBook-Pro-8:deliverables jburos$
```

Session info:  [session_info.txt](https://github.com/quarto-dev/quarto-cli/files/8445486/session_info.txt)

```r
> reticulate::py_config()
python:         /Users/jburos/Library/r-miniconda/envs/r-reticulate/bin/python
libpython:      /Users/jburos/Library/r-miniconda/envs/r-reticulate/lib/libpython3.6m.dylib
pythonhome:     /Users/jburos/Library/r-miniconda/envs/r-reticulate:/Users/jburos/Library/r-miniconda/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, May  7 2020, 23:06:31)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/jburos/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.18.1
```
 
 Quarto version is: `0.9.194`

**Comment by jjallaire** [comment]
In theory there shouldn't be any difference in the way that Quarto and R Markdown handle reticulate (but that doesn't rule out some subtle problem I'm not aware of!). If you could provide an example that has less external dependencies (so I can execute it w/o error in the normal case) that would be great. For this example I get an error relating to not having any AWS credentials (I get this error in both `.qmd` and `.rmd`):

```
Quitting from lines 13-14 (qmd-reticulate.qmd) 
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  NoCredentialsError: Unable to locate credentials

Detailed traceback:
  File "/Users/jjallaire/quarto/dev/qmd-reticulate/env/lib/python3.9/site-packages/botocore/client.py", line 401, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jjallaire/quarto/dev/qmd-reticulate/env/lib/python3.9/site-packages/botocore/client.py", line 717, in _make_api_call
    http, parsed_response = self._make_request(
  File "/Users/jjallaire/quarto/dev/qmd-reticulate/env/lib/python3.9/site-packages/botocore/client.py", line 737, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/jjallaire/quarto/dev/qmd-reticulate/env/lib/python3.9/site-packages/botocore/endpoint.py", line 107, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/jjallaire/quarto/dev/qmd-reticulate/env/lib/python3.9/site-packages/botocore/endpoint.py", line 180, in _send_request
    request = self.create_reque
Calls: .main ... iam_whoami -> iam_get_user -> <Anonymous> -> py_call_impl

Execution halted
```

**Comment by jburos** [comment]
Thanks for taking a look at this so quickly.

I'm seeing the same behavior when calling a python function directly, rather than from within an R package. 

For example:

    ---
    title: "Test R package with reticulate"
    format: html
    ---
    
    ```{r load-library}
    library(reticulate)
    ```
    
    ```{r load-numpy}
    # reticulate::py_install('numpy')
    np <- reticulate::import('numpy', convert = FALSE)
    np$arange(10)
    ```
    
    ```{r print-hello}
    print("hello")
    ```

**Comment by jjallaire** [comment]
Unfortunately I can't repro this. There must be some difference in the environment between the Qmd Render and the Rmd render. You could try putting a `Sys.getenv()` in both documents and see what differences in python, conda, virtualenv, or path related environment variables exist.

**Comment by jburos** [comment]
The only differences I could find between the environments were the R versions: `4.0.3` (rmarkdown) vs `4.0.5` (quarto). 

I upgraded both to 4.1.3 (& re-installed miniconda to the latest version) and now my qmd docs render whether I use reticulate or not.
