### ISSUE TITLE
Ubuntu post installation script fails

### ISSUE THREAD

**Issue by TLouf** [quarto-dev/quarto-cli#5777]
This is not a huge problem, but when installing `quarto` on an Ubuntu-based distro, I get the following error:
```
ln: failed to create symbolic link '/usr/local/man/quarto.1': No such file or directory
```
caused by this line:

https://github.com/quarto-dev/quarto-cli/blob/9402ca9ad15b8c693fcc2c7691df3becb3d3631e/package/scripts/linux/deb/postinst#L9

which I commented out to solve the issue. I don't know if it's different for Debian, but for Ubuntu the `ln` should rather link to `/usr/share/man/man1`, I think.

`quarto` still works despite the error, but getting it might be disconcerting for some.

**Comment by dragonstyle** [comment]
Fixed here: 48a485c1267d4d7997a9296f80d52e220f887724

Thanks for letting us know
