### ISSUE TITLE
Issue executing Python cells with cell magic plus code block options 

### ISSUE THREAD

**Issue by c-zippel** [quarto-dev/quarto-cli#578]
First, thank you for creating this amazing tool. 

I'm having trouble rendering Quarto documents that include a Python cell with both cell magic *and* code block options. Cells with cell magic and no options execute just fine. However, cells with both cell magic and options do not execute. (Line magic works fine whether or not there are options.)

As an example, if I attempt to render this document:

````
---
title: "Cell Magic"
format: html
jupyter: python3
---

## Cell magic without code block options

```{python}
%%html
<span>Something</span>
```

## Cell magic with code block options

```{python}
#| echo: false

%%html
<span>Something else</span>
```
````

I see this error message:

```
Executing 'try_cell_magic.ipynb'
  Cell 1/2...Done
  Cell 2/2...ERROR: 

An error occurred while executing the following cell:
------------------
#| echo: false

%%html
<span>Something else</span>
------------------

  Input In [8]
    <span>Something else</span>
    ^
SyntaxError: invalid syntax

SyntaxError: invalid syntax (3512398949.py, line 3)
```

**Comment by jjallaire** [comment]
I think the problem is that both processors are looking for content at the beginning of the cell. I'd suggest perhaps using alternatives to magics or using global cell options, e.g.

````
```{python}
#| echo: false
from IPython.core.display import HTML
HTML('<a href="http://example.com">link</a>')
```
````

or 

```yaml
---
title: "Doc"
execute:
  echo: false
---
```

**Comment by c-zippel** [comment]
Thanks! I've used both those alternatives. I think that for Quarto users who interested in multi-language documents (e.g., #135), cell magics are a nice solution -- but not being able to control code and cell output for individual cells is a certainly a downside.

The incompatibility of code block options and cell magics could be worth noting in the documentation (e.g. [here](https://quarto.org/docs/reference/cells/cells-jupyter.html)). If you think it's worthwhile I could file an issue in that repo. 

Thank you again!

**Comment by jjallaire** [comment]
Okay, let me see if there is something I can do to make these work together. Will report back soon.

**Comment by jjallaire** [comment]
Managed to sort out how to make this work (https://github.com/quarto-dev/quarto-cli/commit/82ae95dbaf92e229269861500e8b93e2a9c2c8d4). Should be in tomorrow's build.

**Comment by lgonzalezsa** [comment]
Today I notice in my Jupyter notebook executed in vscode, having a cell with quarto and magic throw me the following error: `UsageError: Line magic function `%%time` not found.`
The recommended action is still to find alternative to the ipython magic ?
```
#|hide
%%time

```

**Comment by jjallaire** [comment]
I'm not sure what this is (it's not valid yaml option syntax, it's just a string "hide"):

```python
#|hide
```

In terms of cell magics in VS Code notebooks I don't know which ones are supported but it seems like this one isn't.

**Comment by lgonzalezsa** [comment]
Let me clarify my code bit more:
```
```{python}
#|hide
%%time
sleep 2``` 
```
If I run the notebook cell only with `%%time` it works in vscode, adding the `#|hide` fails.
I was assuming `#|hide` is a quarto directive but seems is from [nbdev](https://github.com/fastai/nbdev)

**Comment by hamelsmu** [comment]
I have opened this PR on nbdev to support cell magic https://github.com/fastai/nbdev/pull/905

Note that cell magic needs to be the first thing in the cell so after that PR is merged, it would be something like

```python
%%timeit
#|hide
print('time me')
```
