### ISSUE TITLE
Unexecuted code block feature does not work when code line numbers on chunk is activated

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#5783]
````markdown
---
format: revealjs
---

## test

```{{python}}
1 + 1
```

````

This will give 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/20c6ade2-cc53-42e8-9f4f-619b7d7dd385)

while for HTML

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/aa7998a6-87ec-4380-bcad-67e855b96baa)

I believe we should have the same output for this feature to work

https://quarto.org/docs/computations/execution-options.html#unexecuted-blocks

Edit: See later post for more details: https://github.com/quarto-dev/quarto-cli/issues/5783#issuecomment-1573978213

**Comment by coatless** [comment]
Just about to post this one! Thanks for adding it.

**Comment by cscheid** [comment]
I don't know whether this is intentional or not, but from tracing the lua filters, I can tell that the difference is coming from somewhere in `pre-combined-figures-theorems-etc`. In the HTML format, we perform this step:

<img width="445" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/8b4ddf55-040a-485d-852c-ddd39d93dd59">

In revealjs, on the other hand, we do this:

<img width="473" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/9635334c-a2de-458f-936e-fa24e70914d7">

**Comment by cderv** [comment]
Ok I don't think this is on purpose, but this is because our processing does not account for some other processing that happens for **revealjs**

engine escaping happens here: 
https://github.com/quarto-dev/quarto-cli/blob/b5c6ddc37cb2c34e7d6da01cff13b640e97c22cc/src/resources/filters/quarto-pre/engine-escape.lua#L11-L18

This is only happening if there is only one classe. But in revealjs case, we code this for `el`
````haskell
CodeBlock {
  attr: Attr {
    attributes: AttributeList {}
    classes: List {
      [1] "{{python}}"
      [2] "number-lines"
    }
    clone: function: 000000000b3e8ec0
    identifier: ""
  }
  clone: function: 000000000b3e8580
  show: function: 000000000b3e8080
  text: "1 + 1"
  walk: function: 000000000b3e8e40
}
````
This is inserted has part of the line number feature to activate Pandoc feature
https://github.com/quarto-dev/quarto-cli/blob/b5c6ddc37cb2c34e7d6da01cff13b640e97c22cc/src/resources/filters/quarto-pre/line-numbers.lua#L5-L22

And revealjs format does have line number activated by default. So if we do 
````markdown
---
format: 
  html:
    code-line-numbers: true
---

## test

```{{python}}
1 + 1
```
````

then it also fails. So the real bug is 

Escaping the chunk using `` ```{{ engine }} `` syntax, does not work when `code-line-numbers` is `true`

@cscheid do you think 
* we should fix `engine-escape.lua` to take into account possible other class added on the CodeBlock 
* or this is a matter of orders in the filter chain ? 

https://github.com/quarto-dev/quarto-cli/blob/b5c6ddc37cb2c34e7d6da01cff13b640e97c22cc/src/resources/filters/main.lua#L264-L265

Changing the order does solve this. 

```diff
diff --git a/src/resources/filters/main.lua b/src/resources/filters/main.lua
index 5b55984c4..c2b7adcb2 100644
--- a/src/resources/filters/main.lua
+++ b/src/resources/filters/main.lua
@@ -261,8 +261,8 @@ local quartoPre = {
     quarto_pre_theorems(),
     docx_callout_and_table_fixup(),
     code_filename(),
-    line_numbers(),
     engine_escape(),
+    line_numbers(),
     bootstrap_panel_input(),
     bootstrap_panel_layout(),
     bootstrap_panel_sidebar(),
```

**Comment by cscheid** [comment]
I would prefer to not depend on the order, because that tends to be brittle. I think we should change `engine-escape.lua` to work in the presence of multiple classes (but then we should double check about a potential reason for only escaping one-class code blocks)

**Comment by cderv** [comment]
> https://github.com/quarto-dev/quarto-cli/blob/b5c6ddc37cb2c34e7d6da01cff13b640e97c22cc/package/scripts/windows/quarto.cmd#L97

yeah I think this could be by convenience as we would expect only one class in the .qmd doc parsed. 

I believe for this feature, checking the first class that appears (which should be the engine) would work. 

But to be conservative we can add a specific check about "if other class is number line" because we know we add this one. But which other are we added potentially in other format or features ? 🤷

**Comment by cscheid** [comment]
> But to be conservative we can add a specific check about "if other class is number line" because we know we add this one. But which other are we added potentially in other format or features ? 🤷

Yes, I like adding a warning in case we see escaped engine classes together with classes other than `number-lines`, so that users know this is potentially going to cause issues. I can't think of any way in which that could happen, but I can't convince myself that it won't happen either.

**Comment by cderv** [comment]
Awesome thanks !
