### ISSUE TITLE
Embedding a notebook with title overrides the page's title

### ISSUE THREAD

**Issue by machow** [quarto-dev/quarto-cli#5785]
### Bug description

Embedding an ipynb notebook with a markdown h1 header in its first cell, causes that header to override the title of the page.

### Steps to reproduce

**some_doc.qmd**

```
---
title: real title
---

# a title

{{< embed notebook.ipynb >}}
```

**notebook.ipynb**

A notebook with a single cell that is essentially this markdown

```
# A notebook title
```

**result**

The notebook title is put at the top of the page, the rest of the notebook content where you expect it to be embedded.

<img width="1186" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/2574498/ff2b2998-2776-4fd6-a5ec-80e75d28e461">

### Expected behavior

The title configured in the .qmd will be the title. Or if no title configured in the config, then the header that would normally become the title should not be overriden.

### Actual behavior

Notebook title becomes header.

### Your environment

MacOS

### Quarto check output

(Edit: I've also checked with quarto v1.3.361 and see the same behavior)

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: /Users/machow/.virtualenvs/plotnine-docs-demo/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
      knitr: 1.39
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK

**Comment by dragonstyle** [comment]
Good one! Fix is on the way and should be available in the next update.
