### ISSUE TITLE
Previewing hits scss error when using revealjs format within a webpage

### ISSUE THREAD

**Issue by dgkf** [quarto-dev/quarto-cli#5786]
### Bug description

Including a subpage of a website that renders to `revealjs` causes `quarto` to fail to discover some scss variables resulting in a scss compilation error.

### Steps to reproduce

1. Clone reproducible example in [this repo](https://github.com/dgkf/quarto-revealjs-theme-reprex)
   - This repo contains an extension that provides a custom `html` and `revealjs` format
   - The project intends to build a website with a navbar item that links to a presentation (using the `revealjs` format)
   - Both leverage a `_variables.scss` file `@include`ed in a theme to define a `$primary` variable
3. `quarto preview`
4. Observe build failure

### Expected behavior

The website renders and the presentation navbar item takes you to a page where you can view the presentation in the browser.

### Actual behavior

`quarto` fails to render the website

### Your environment

- `quarto-cli`
   - 553fec5f3c421a8c0e9a533ef47d76c6f002e437 (from June 1)
   - 1.3.361 installed via homebrew
- on MacOS

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: julia-1.8

      NOTE: No Jupyter kernel for Python found

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by dragonstyle** [comment]
The issue is specifically caused by the use of the `import` from within the theme.scss file.

Writing:

```scss
/*-- scss:defaults --*/
$primary: #f00;
```

Resolves the issue. I'm still digging into why the import is failing (I'm guessing that we don't 'know' about the imported file and so aren't copying it when actually rendering the css).

**Comment by dragonstyle** [comment]
The issue is actually further specific to the imported file being named `_variable.scss`, which is also a file that is visible in our bootstrap distribution. We were searching the bootstrap load paths first when resolving imports. I've fix that, but you can either

- place variables inline
- rename your partial to something like `_custom-variables.scss`
- Update to our next build and change nothing

Thanks for the good bug and repro!

**Comment by dgkf** [comment]
Thanks for the followup! Ill or not, I think following up within a week for an open-source ticket is still amazingly responsive and I continue to be impressed by how quick this project moves in general.

Thanks for confirming the issue on your end and I hope you're feeling better!

**Comment by dragonstyle** [comment]
Ok found the error and have made a fix. I'll start a build, so it should be available in our next preview release. Thanks for your patience and help tracking down these errors - I hope we've uncovered all of them!
