### ISSUE TITLE
document feature: control conditional content with boolean metadata

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#5791]
We need to add documentation about #5755 to the website.

**Comment by mine-cetinkaya-rundel** [comment]
In the documentation of this, would be good to give an example of how to use it alongside profiles, i.e., how to nest conditioning based on `profile` and `meta`.

**Comment by cscheid** [comment]
Fixed on quarto-web.

> In the documentation of this, would be good to give an example of how to use it alongside profiles

This would mean that the documentation reader would already know what a project is and what a profile is. I'm not sure it's a good idea. Instead, I added a short paragraph linking to project profiles.
