### ISSUE TITLE
Missing option in rstudio for .qmd files

### ISSUE THREAD

**Issue by jardel20** [quarto-dev/quarto-cli#5792]
### Bug description

There is no option for .qmd files in "file > new file" in my Rstudio.

### Your environment

- RStudio 2023.03.1+446 "Cherry Blossom" Release (6e31ffc3ef2a1f81d377eeccab71ddc11cfbd29e, 2023-05-12)
-  Fedora release 38 (Thirty Eight)
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.12 Chrome/87.0.4280.144 Safari/537.36

**Comment by mcanouil** [comment]
No worries, we appreciate the report anyway.
It's simply that it will be addressed in the proper repository.
Thanks again for the report!
