### ISSUE TITLE
listing: undefined shown for item with missing date

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#5802]
### Bug description

The table view shows _undefined_ when a listing item does not contain date information.

<img width="845" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/13888691-d84e-4f54-8ad4-bda0052bcdd4">

### Steps to reproduce

The `_quarto.yml`:

```yaml
project:
  type: website

format:
  html:
    toc: true
    theme: cosmos
```

The `index.qmd`:

```markdown
---
title: the things
listing:
  contents: posts
  type: table
  fields: [date, title]
  sort-ui: false
  filter-ui: false
---
```

The `posts/1.qmd`

```markdown
---
title: one thing
---

this is one thing
```

The `posts/2.qmd`

```markdown
---
title: two thing
date: Jun 3, 2023
---

this is one thing
```

### Expected behavior

A blank value should be shown when date is missing, not _undefined_.

The "default" listing view is OK.

<img width="797" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/6db74098-945a-48be-b52d-7e633f0d0d18">

The "grid" view is also OK.

<img width="585" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/54596ba6-965e-4b6c-83aa-5ea27c976e4f">

Only the "table" view has this problem.

### Actual behavior

An _undefined_ value is presented.

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.353
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 3.6.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/3.6/Resources/library
      knitr: 1.42.8
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

**Comment by nilayrajderkar** [comment]
Can i pick this issue?
