### ISSUE TITLE
Confluence:  Figure Sizing is ignored

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#5814]
## Description: 
Confluence: Figure Sizing is ignored

## Steps to Reproduce:
- Create a simple document with an image that has its width sized

```
---
title: "Bug: Figure Sizing is ignored"
---

![Image](images/quarto-hex.png){width=120}

```

### Expected Result:
The figure's width is 120.  

Note:  This can be set in the CSF as so
```
... ac:width="120"
```

### Actual Result:
The figure is of the original size.

**Comment by cscheid** [comment]
(I'm assigning myself to this and marking as `crossref` because our treatment of images will change in the new crossref work. I want to make sure we don't regress on it.)
