### ISSUE TITLE
Jupiter widgets docs should indicate that no Jupyter kernel is provided once published

### ISSUE THREAD

**Issue by saeejithnair** [quarto-dev/quarto-cli#5834]
### Bug description

I don't seem to be able to capture `on_selection()` or `on_click()` events for interactive plots with plotly. I've tried both native `.qmd` files and Quarto snippets inside jupyter notebooks in VSCode, by trying to display outputs with `fig.show()`. 

However, the events do get captured correctly inside the notebook cell output when the output is displayed with just `fig` (as the last line of the cell). But, HTML render still fails to capture the events, even in this case.

### Steps to reproduce

````qmd
---
title: Quarto Unable to Capture Click Events
jupyter: python3
---

## Combining Parcats with Scatter
Check out [Parallel Categories Linked Brushing section for source](https://plotly.com/python/parallel-categories-diagram/)

```{python}
import plotly.graph_objects as go
from ipywidgets import widgets
import pandas as pd
import numpy as np

cars_df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/imports-85.csv"
)

# Build parcats dimensions
categorical_dimensions = ["body-style", "drive-wheels", "fuel-type"]

dimensions = [
    dict(values=cars_df[label], label=label) for label in categorical_dimensions
]

# Build colorscale
color = np.zeros(len(cars_df), dtype="uint8")
colorscale = [[0, "gray"], [1, "firebrick"]]

# Build figure as FigureWidget
fig = go.FigureWidget(
    data=[
        go.Scatter(
            x=cars_df.horsepower,
            y=cars_df["highway-mpg"],
            marker={"color": "gray"},
            mode="markers",
            selected={"marker": {"color": "firebrick"}},
            unselected={"marker": {"opacity": 0.3}},
        ),
        go.Parcats(
            domain={"y": [0, 0.4]},
            dimensions=dimensions,
            line={
                "colorscale": colorscale,
                "cmin": 0,
                "cmax": 1,
                "color": color,
                "shape": "hspline",
            },
        ),
    ]
)

fig.update_layout(
    height=800,
    xaxis={"title": "Horsepower"},
    yaxis={"title": "MPG", "domain": [0.6, 1]},
    dragmode="lasso",
    hovermode="closest",
)


# Update color callback
def update_color(trace, points, state):
    # Update scatter selection
    fig.data[0].selectedpoints = points.point_inds

    # Update parcats colors
    new_color = np.zeros(len(cars_df), dtype="uint8")
    new_color[points.point_inds] = 1
    fig.data[1].line.color = new_color


# Register callback on scatter selection...
fig.data[0].on_selection(update_color)
# and parcats click
fig.data[1].on_click(update_color)

# Doesn't capture click events in VSCode Jupyter Notebook
# fig.show(renderer="plotly_mimetype+notebook_connected")

# Doesn't capture click events in .qmd
fig.show()
```
````

### Expected behavior

When you select points in the scatter plot, the corresponding rows should be highlighted in the parcats plot and when you click on the parcats plot, the corresponding points should be highlighted in the scatter plot

![](https://user-images.githubusercontent.com/15064365/48087050-4a3eae80-e1cc-11e8-94c9-c0ffcedd3aa9.gif)

### Actual behavior

While you can select points in the scatter plot, the corresponding data points do not get highlighted in the parcats plot

<img width="767" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/16181437/50eecce9-d2ef-4fe7-a16f-5b11d1dbdd88">

### Your environment

- IDE: VSCode
- Quarto: 1.3.361
- Python: 3.9.16
- OS: Linux 8bed2c0d09ad 5.19.0-40-generic # 41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- plotly: 5.14.1

### Quarto check output

```bash
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.16
      Path: /home/user/venv/bin/python
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment]
I can partially reproduce this, but I confess I can't make the linked views coordinate even in the plain `fig.show()` case. Unfortunately, I don't know nearly enough plotly to be able to tell you what could be going wrong, though.

**Comment by saeejithnair** [comment]
Thanks for looking into this @cscheid! From a bit of digging, it seems like Quarto isn't able to capture ipywidget events correctly. For example, I'm also unable to reproduce this demo snippet's output gif in the browser https://github.com/plotly/plotly.py/issues/1292#issuecomment-443504338


Also tried following the suggestions in this thread using `IPython.display.display(f)` but then I simply don't see any output once the cell gets rendered https://github.com/plotly/plotly.py/issues/3066#issuecomment-1063774207

**Comment by saeejithnair** [comment]
Unsure if this is a regression or if I'm doing something wrong, but the [Leaflet example in the Quarto docs](https://quarto.org/docs/interactive/widgets/jupyter.html#leaflet-example) doesn't work for me either @cscheid 

It displays correctly within the VSCode Jupyter notebook but upon rendering to HTML, the cell output is empty

```python
from ipyleaflet import Map, Marker, basemaps, basemap_to_tiles
m = Map(
  basemap=basemap_to_tiles(
    basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-04-08"
  ),
  center=(52.204793, 360.121558),
  zoom=4
)
m.add_layer(Marker(location=(52.204793, 360.121558)))
m
```

**Comment by rtjeannier** [comment]
I am having the same issue.

Also , fig.show() will never work with plotly callbacks. This is not an issue with Quarto, this is true in a Jupyter Notebook as well.

But there is something missing with Quarto here. I think it has to do with Quarto not having a local python instance after the file is rendered. 

The other Plotly interactive features are Javascript native I think.

**Comment by cscheid** [comment]
> But there is something missing with Quarto here. I think it has to do with Quarto not having a local python instance after the file is rendered.

I'm not sure what you mean by "missing" here. To be clear, you are correct that quarto produces an HTML file that is meant to be served by HTTP servers, without a Python instance. But the live execution of a kernel in a page view isn't a quarto feature that we advertise anywhere. So if click events need to happen through a live instance of Python, then this isn't a feature that we support now (or in the medium-term future). I might be the one missing something, though.

**Comment by rtjeannier** [comment]
> I'm not sure what you mean by "missing" here 

I should have been clearer.

I am speculating that there are Javascript on click events that are generated by plotly that Quarto does handle (i.e. zooming in on a chart). Then there are potentially python on click events (like the example posted in this issue) that would require a python instance running for Quarto to handle. I do not know this to be true, but this is my best guess given a full day of debugging.

So what is missing is an actual understanding of why we cannot replicate some jupyter widgets in Quarto. I've read through the documentation multiple times and scoured the internet for an explanation and I cannot find clear reason why this code fails. All I have are my speculations. 

If my speculation is correct and this functionality does not work in Quarto, it might be useful to ammend the Quarto documentation around interactivity to specify Plotly is only partiality supported. 

https://quarto.org/docs/interactive/widgets/jupyter.html 

> [Jupyter Widgets](https://jupyter.org/widgets) enable you to use JavaScript visualization libraries like [Leaflet](https://ipyleaflet.readthedocs.io/en/latest/), [Plotly](https://plotly.com/python/), and [threejs](https://pythreejs.readthedocs.io/) directly from Python.

From reading the description you can see why someone might be confused.

Effectively none of the examples listed in this link are available if you use Quarto. 

https://plotly.com/python/chart-events/

At least having a better understanding when we should expect widgets to work and when we should not expect them to work. Right now there is nothing indicating this example should not work. I encounter no errors or warnings. I imagine there is another me out there who has also lost an entire day trying to solve why they cannot reproduce in Quarto what works in a Jupyter Notebook.

**Comment by devmcp** [comment]
> I imagine there is another me out there who has also lost an entire day trying to solve why they cannot reproduce in Quarto what works in a Jupyter Notebook

I have just lost a day on exactly this ☹️

It makes sense now from this thread why these are not working, but some indication of this, at least in the docs, and ideally with a warning in quarto at the point of rendering would be very useful.

**Comment by devmcp** [comment]
> I imagine there is another me out there who has also lost an entire day trying to solve why they cannot reproduce in Quarto what works in a Jupyter Notebook

I have just lost a day on exactly this ☹️

It makes sense now from this thread why these are not working, but some indication of this, at least in the docs, and ideally with a warning in quarto at the point of rendering would be very useful.
