### ISSUE TITLE
lubridate wday(label=T) creating error in Quarto

### ISSUE THREAD

**Issue by jonathanmburns** [quarto-dev/quarto-cli#5835]
### Bug description

When I execute `r wday(Sys.Date())`, I get the expected response.
However, when I try to include the character label, using `r wday(Sys.Date(), label=T)`, I get an error:

> Error in wday(Sys.Date(), label = T) : unused argument (label = T)
Calls: .main ... inline_exec -> hook_eval -> withVisible -> eval -> eval
Execution halted

I also get a pop-up with the following error:
![Quarto Lubridate Error](https://github.com/quarto-dev/quarto-cli/assets/82161318/578a2175-32b7-46b7-8479-66ca9e298c46)

### Steps to reproduce

````qmd

---
title: "Reproducible Error"
format: html
editor: visual
execute:
  echo: false
  warning: false
---



## Reproducible code

````{r}
library(lubrdiate)
````

Some text...  `r wday(Sys.Date(), label=T)`, some more text

### Expected behavior

I should see today's date in English.  For example, since today is Tuesday, I should see:
Some text...  Tuesday, some more text

### Actual behavior

Instead, I get an error and the code crashes

### Your environment

IDE - RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

OS - Windows 10

R version 4.2.0 (2022-04-22 ucrt) -- "Vigorous Calisthenics"

### Quarto check output

[>] Checking Quarto installation......OK
      Version: 1.2.335
      Path: C:\Program Files\RStudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: C:/Users/225022/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 4.10.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/PROGRA~1/R/R-42~1.0
      LibPaths:
        - C:/Users/xxxx/Documents/R/win-library/4.2
        - C:/Program Files/R/R-4.2.0/library
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Please do include your actual file that causes the issue. The .qmd you're reporting has a typo, I don't think it's the one you're using:

```
library(lubrdiate)
```

**Comment by cscheid** [comment]
The error I get with 1.4 is different:

```
...
Quitting from lines 21-26 (5835.qmd)

Error in wday(Sys.Date(), label = T) : unused argument (label = T)
...
```

> I did some debugging; it appears that it is the inclusion of data.table that is causing the issue.

What's happening is that data.table also exports a `wday()` call with a different interface; this isn't a quarto issue:

````
$ R

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin20 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(data.table)
data.table 1.14.6 using 1 threads (see ?getDTthreads).  Latest news: r-datatable.com
**********
This installation of data.table has not detected OpenMP support. It should still work but in single-threaded mode.
This is a Mac. Please read https://mac.r-project.org/openmp/. Please engage with Apple and ask them for support. Check r-datatable.com for updates, and our Mac instructions here: https://github.com/Rdatatable/data.table/wiki/Installation. After several years of many reports of installation problems on Mac, it's time to gingerly point out that there have been no similar problems on Windows or Linux.
**********
> wday(Sys.Date(), label = T)
Error in wday(Sys.Date(), label = T) : unused argument (label = T)
```

**Comment by cderv** [comment]
> I also note that when I explicitly call Some text.  Since today is `r lubridate::wday(Sys.Date(), label=T)`. it works. 

@jonathanmburns using namespacing as you did here is the solution. 

Otherwise tools like **conflicted** can help you - see https://conflicted.r-lib.org/
