### ISSUE TITLE
Refuse to connect in preview-links.

### ISSUE THREAD

**Issue by fecet** [quarto-dev/quarto-cli#5850]
### Bug description

Some links cannot be previewed in revealjs.

Could we set proxy and headers for request happlen in quarto document?  

### Steps to reproduce

```qmd
---
format: 
    revealjs:
        preview-links: true
---

## sd

[link](https://huggingface.co/datasets/imdb)
```

### Expected behavior

Links can be previewed correctly as in browser

### Actual behavior

it says "huggingface.co refuse to connect"

### Your environment

- Arch Linux
- Chrome

**Comment by cderv** [comment]
Thanks for the report. 

What I see in the console is 

> Refused to display 'https://huggingface.co/' in a frame because it set 'X-Frame-Options' to 'deny'.

So it seems that `https://huggingface.co/` does not allow for being included as an iframe. I don't think we can do anything here... 


> Could we set proxy and headers for request happlen in quarto document?

What is the content to be set exactly that would make this works ?

**Comment by mcanouil** [comment]
> Refused to display 'https://huggingface.co/' in a frame because it set 'X-Frame-Options' to 'deny'.

See:
> These measures are put in place to protect users and their data, and attempting to bypass them can be illegal and unethical. It's important to respect the security measures put in place by website owners and developers.

**Comment by fecet** [comment]
I know very little about HTML. Initially, I thought it could be fixed by adding a proxy or modifying the request settings.

But I found many sites cannot be seen by `preview-links`, including arxiv and google
```
Refused to display 'https://www.google.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.)
```
Is there any way to bypass this restriction? Otherwise, this feature is ineffective for me in most scenarios.

**Comment by mcanouil** [comment]
> These measures are put in place to protect users and their data, and attempting to bypass them can be illegal and unethical. It's important to respect the security measures put in place by website owners and developers.

@fecet It's not about the preview feature, it's security measure taken by website owners/developers. The only thing you can do is to ask them to lift this security measure.

**Comment by cderv** [comment]
Thanks for your additional information @fecet. Indeed @mcanouil gave you the context and why this happens. 

There is nothing you can really to include as an iframe a website that do not allow it. 

We'll add some note about checking for website to be used with `preview-links` in our doc.
