### ISSUE TITLE
Add an example of listing feed options to docs

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#5858]
> It would be helpful to see an example showing how to set listing.feed.items, or any of the feed-specific options. It was unclear at first that these options were supposed to be associated with the listing.feed sub-object, since the other examples on that page only set listing.feed: true. https://quarto.org/docs/websites/website-listings.html#feeds

E.g. 

```
listing:
  feed:
    items: 5
```

**Comment by amanpandey3956** [comment]
Can you assign me this issue would work to work on it

**Comment by mcanouil** [comment]
Feel free to make a PR on the Quarto Web repository mentioning this issue using the usual GitHub cross-link system.
