### ISSUE TITLE
Interactive mode with quarto documents in RStudio does not like `--|` code cell option, requires `#|`. 

### ISSUE THREAD

**Issue by coatless** [quarto-dev/quarto-cli#5864]
### Bug description

When interactively running quarto cells inside of RStudio, the SQL code chunk runs into problems if we use `--| connection: value` instead of `#| connection: value`.

Example of the error message:

```
Error in .rs.runSqlForDataCapture("--| label: join-using-example\n--| connection: db_lahman\nSELECT yearID, playerID, HR, salary\nFROM Batting JOIN Salaries USING(yearID, playerID)\nLIMIT 10",  : 
  The 'connection' option (DBI connection) is required for sql chunks.
Failed to execute SQL chunk
```

### Steps to reproduce

The quarto document is given as:

````
---
title: "SQL Cell Issue"
author: "JJB"
embed-resources: true
format:
  html:
    toc: true
---


```{r}
#| label: download-lehman
#| cache: true
# Download the data into your project workspace
download.file(
  "https://github.com/coatless/raw-data/blob/main/lahman2016.sqlite?raw=true",
  "lahman2016.sqlite")
```

```{r}
#| label: working-with-lehman
library("DBI")
db_lahman = DBI::dbConnect(RSQLite::SQLite(), 
                           dbname = "lahman2016.sqlite")

# View listed tables
DBI::dbListTables(db_lahman)
```

```{sql}
--| label: join-using-example
--| connection: db_lahman
SELECT yearID, playerID, HR, salary
FROM Batting JOIN Salaries USING(yearID, playerID)
LIMIT 10
```

````

### Expected behavior

There should be no error.

### Actual behavior

Example of the error message:

```
Error in .rs.runSqlForDataCapture("--| label: join-using-example\n--| connection: db_lahman\nSELECT yearID, playerID, HR, salary\nFROM Batting JOIN Salaries USING(yearID, playerID)\nLIMIT 10",  : 
  The 'connection' option (DBI connection) is required for sql chunks.
Failed to execute SQL chunk
```

### Your environment

macOS: 

macOS 13.4 (22F66)

R Version: 

R version 4.3.0 (2023-04-21)

RStudio: 

$mode
[1] "desktop"

$version
[1] ‘2023.6.0.421’

$long_version
[1] "2023.06.0+421"

$release_name
[1] "Mountain Hydrangea"

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10 (Conda)
      Path: /Users/ronin/miniconda3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Huh. That's surprising to me.

@cderv, is this a knitr bug? It feels like knitr should respect the comment syntax of the language chunk, just like quarto does.

**Comment by cderv** [comment]
This is RStudio IDE behavior and bug. `.rs.runSqlForDataCapture` is the hint about that. 

Also I don't think interactive mode in RStudio IDE uses **knitr** at all. 

I thought this would have been fixed in https://github.com/rstudio/rstudio/issues/11606 but it seems they handled only `#|` comment (https://github.com/rstudio/rstudio/pull/12011) and they do not do a matching between language and comment as we do in **knitr** and Quarto 

This issue will be for Quarto and R Markdown, or more generally **knitr** document.

**Comment by cscheid** [comment]
> This is RStudio IDE behavior and bug. `.rs.runSqlForDataCapture` is the hint about that.

(TIL about `.rs.`, thank you!)

**Comment by cderv** [comment]
Side note: Using `#|` will always work with **knitr** as this is the default comment. So using `#|` should solve the issue in the meantime. 

@coatless would you like to open issue in RStudio IDE repo ? Otherwise I can do it.

**Comment by coatless** [comment]
@cderv I'll let you open the issue if that's okay. I think it would get processed at a faster rate.

**Comment by cderv** [comment]
Note that sure -  I can also comment on yours to give more context if that can help it. 

I'll do it on Monday if none if opened yet. Week end for me rn.

**Comment by coatless** [comment]
@cderv bump

Did the ticket get opened over at RStudio? (Can you move the issue over to that repo?)

**Comment by cderv** [comment]
Thanks for the reminder. 

* https://github.com/rstudio/rstudio/issues/13240

> (Can you move the issue over to that repo?)

We can't move issue across organisation AFAIK

**Comment by cderv** [comment]
FWIW this should be fixed upstream now for [Ocean Storm version](https://dailies.rstudio.com/rstudio/ocean-storm/) has issue has been closed
* https://github.com/rstudio/rstudio/issues/13240
