### ISSUE TITLE
auto-animate as global option

### ISSUE THREAD

**Issue by albert-ying** [quarto-dev/quarto-cli#5866]
### Bug description

Currently put auto-animate: true in the yaml seems not working

```
---
format:
  revealjs:
    auto-animate: true
---
```

**Comment by cscheid** [comment]
Thanks for the feedback. I don't think we ever described this as an option, looking at https://quarto.org/docs/presentations/revealjs/advanced.html#auto-animate. Where in the documentation did you read about this?

**Comment by albert-ying** [comment]
Oh I just saw this https://github.com/quarto-dev/quarto-cli/actions/runs/1503861024/usage

so I thought it was implemented...

**Comment by cscheid** [comment]
Like the title says, that's talking about propagating the auto-animate global options. It's not saying that auto-animate is a global option.
