### ISSUE TITLE
Mermaid syntax error (version 9.1.1).

### ISSUE THREAD

**Issue by avhz** [quarto-dev/quarto-cli#5877]
### Bug description

I receive:

"""
Syntax error in graph
mermaid version 9.1.1
"""

This is caused by using `namespace` in a Mermaid Class Diagram.

I am writing a quarto presentation (format: revealjs).

Output from quarto --version: 1.3.361

My understanding is that Mermaid should be at version 10+ in quarto 1.3. 

### Steps to reproduce

This works:

```{mermaid}
classDiagram
    class World {
        + msg : String
    }
```

This does not work:

```{mermaid}
classDiagram
namespace Hello {
    class World {
        + msg : String
    }
}
```

### Expected behavior

I should not get a syntax error. 

It works perfectly fine on the mermaid online editor: https://mermaid.live/edit

### Actual behavior

"""
Syntax error in graph
mermaid version 9.1.1
"""

### Your environment

IDE:
RStudio 2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-06) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.06.0+421 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

OS:
Ubuntu 23.04

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.16 (Conda)
      Path: /home/user/.local/share/r-miniconda/envs/r-reticulate/bin/python
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/lib/R
      LibPaths:
        - /home/user/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
> Output from quarto --version: 1.3.361

> My understanding is that Mermaid should be at version 10+ in quarto 1.3.

Your understanding is wrong; quarto 1.4 upgraded to version 10. As the message you see indicates, quarto 1.3 uses mermaid 9. We upgrade dependencies once per release.

**Comment by mcanouil** [comment]
> Still get syntax error with mermaid version 9.1.1

You get the 9.1.1 warning with Quarto 1.4?

**Comment by mcanouil** [comment]
Well, the latest Quarto version has `mermaid version 10.2.0-rc.2`, so there is something wrong in your setup.

That being said, using the development version of Quarto I get the error which was expected since the "namespace" seems to have been deployed in Mermaid.js [10.2.0](https://github.com/mermaid-js/mermaid/releases/tag/v10.2.0)
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/30c655d7-be2e-4c58-ab2a-7957a063cd49">
