### ISSUE TITLE
No yaml validation for `highlight-style`

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#5881]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5873

<div type='discussions-op-text'>

<sup>Originally posted by **dense-set** June 11, 2023</sup>
### Description

(Not sure if this is a (even a?) bug of Quarto or something else, hence asking in Q&A.)

I am learning to use Quarto. Playing around, I discovered that passing wrong arguments to the header YAML sometimes gets undetected and the file still renders. For instance, with `highlight-style: bad123`, the following still renders:

````qmd
---
title: test
highlight-style: bad123
jupyter: python3
---

```{python}
import numpy as np

a = np.arange(15).reshape(3, 5)
a.shape
```
````

However, if I mess up the argument of `jupyter`, I get greeted with an error.

Why is so? Is this expected behaviour?</div>

**Comment by mcanouil** [comment]
While Pandoc does error out if the string does not match known styles or does not end with `.theme` extension (if the extension is something else, Pandoc considers it as a name of a style and not as a file), Quarto does not.

See <https://pandoc.org/MANUAL.html#option--highlight-style>.

**Comment by cscheid** [comment]
It's impossible for us to do "perfect" YAML validation in the sense that Pandoc will run correctly if and only if our validation passes. We cover a lot of the possibilities, but we can't solve all of them. Specifically, IIUI, in this case the behavior depends on existing files in the file system, and so isn't covered by a static schema, in which case this isn't a bug.

**Comment by mcanouil** [comment]
Thanks for the explanation.
(Wasn't sure about checking files)

**Comment by cscheid** [comment]
Here's some more background.

The semantics of JSON Schema are meant to be determinable as a function of _only the document_. There's very good reasons for this. The general principle is that you want to be able to say whether the document is valid independent of how the document will eventually be interpreted.

This is a pragmatic consideration, and it's exactly like type checking. You want to be able to constrain the space of valid documents before even attempting to execute them.

With that said, it would be useful be able to do more sophisticated analyses of the YAML data, ones which might include some limited amounts of code execution. This wouldn't really be a "YAML validation" pass, but in modern CS parlance it would be a "YAML analysis pass". It's a good candidate for our future quarto LSP.
