### ISSUE TITLE
Ambiguous attributes in the author/affiliation schemas

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#5890]
Some useful suggestions from a discussion about authors and affiliations.

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5860

<div type='discussions-op-text'>

<sup>Originally posted by **arnaudgallou** June  9, 2023</sup>
### Description

[Quarto's author and affiliation schemas](https://quarto.org/docs/journals/authors.html) both have an attribute `number`. I find the name of that attribute ambiguous and would recommend using a more specific name (if possible) or explaining what these attributes are in the documentation.

I guess most people (myself included) understand the `number` attribute in the author schema as phone number. If this is what it actually is, wouldn't it be better to rename that attribute as `phone-number` instead?

Now the affiliation schema also has an attribute `number` and that is very confusing. Are we talking here of another phone number? If so, what's the difference with the one in the author schema? Is one number a personnal phone number and the other an office phone number? Or is it something else, e.g. the number of the office/room where the author works?

Not completely related but that would also be great to have a bit more details on the attribute `acknowledgements`. In my field (Natural Sciences), acknowledgements and authors are two distinct things. I've never seen an author who's also acknowledged so having some insights on how one should use that attribute (and what it actually does) would be helpful.</div>

**Comment by cwickham** [comment]
Closed via [quarto-web/pull/718](https://github.com/quarto-dev/quarto-web/pull/718)

**Comment by mcanouil** [comment]
FYI, I just formerly closed it 😉
