### ISSUE TITLE
Tight layout doesn't persist after rendering document for book project

### ISSUE THREAD

**Issue by ercbk** [quarto-dev/quarto-cli#5905]
### Bug description

I want my bullet point lists in my book project to have a tight layout. When I specify this layout in the visual editor manually by editing the attributes of the bullet point or using keyboard shortcut and render the document, the layout is not present in the rendered HTML output. The HTML has default spacing and spaces between list items have been added to the source document. I've also tried changing Global Options >> R Markdown >> Visual >> Default Spacing Between List Items to "tight." In the source document, I've removed spaces between list items. This issue only occurs in specific sections of the document. I am including a section of document where issue occurs.

### Steps to reproduce

````
# Test Doc

## Terms {#sec-py-class-terms .unnumbered}

-   [**Class inheritance**]{style="color: #14adff"} - mechanism by which one class takes on the attributes and methods of another

    ``` python
    class Employee:
        def __init__(self, name, salary=0):
            self.name = name
            self.salary = salary
    ```

-   `__init__()` is a [**constructor method**]{style="color: #14adff"}. It assigns (or initializes) attributes that every object (aka instance) for this class must have.
-   `self` is the 1st argument in any method definition. It refers to a particular instance.
    -   e.g. `self.salary  = salary` creates an attribute called salary and assigns to it the value of the salary parameter (default set to 0)
-   [**Class attributes**]{style="color: #14adff"} are attributes that have the same value for all class instances.
    -   Accessing a class attribute

        ``` python
        # access first employee's name attribute
        e1.name
        # access second employee's salary attribute
        e2.salary
        ```

-   [**Instance Attributes**]{style="color: #14adff"} - Values for these attribute depend on the instance (e.g. they vary depending on each employee)
-   [**Instantiate**]{style="color: #14adff"} - Creating a new object from a class

    ``` python
    e1 = Employee("yyy", 5000)  # name, salary
    e2 = Employee("zzz", 8000)
    ```

````

### Actual behavior

[HTML output image](https://www.dropbox.com/s/arw7j6jy7k4ezma/Screenshot%20%281482%29.png?dl=0)
[Background Jobs panel output image](https://www.dropbox.com/s/ggxkccgljadmitg/Screenshot%20%281483%29.png?dl=0l)

### Your environment

RStudio 2023.06.0 Build 421
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.7.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10      rstudioapi_0.14  knitr_1.43       magrittr_2.0.3   xtable_1.8-4     R6_2.5.1         rlang_1.1.1      fastmap_1.1.1    tools_4.2.3     
[10] xfun_0.39        miniUI_0.1.1.1   cli_3.6.1        clipr_0.8.0      jquerylib_0.1.4  withr_2.5.0      htmltools_0.5.5  ellipsis_0.3.2   digest_0.6.31   
[19] lifecycle_1.0.3  later_1.3.0      sass_0.4.6       fs_1.6.2         promises_1.2.0.1 memoise_2.0.1    cachem_1.0.8     glue_1.6.2       mime_0.12       
[28] reprex_2.0.2     compiler_4.2.3   bslib_0.4.2      jsonlite_1.8.5   httpuv_1.6.9    

### Quarto check output

```bash
$ quarto check
A new release of Deno is available: 1.28.2 → 1.34.2 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.340
      Path: C:\Users\tbats\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.8.1 (Conda)
      Path: C:/Users/tbats/Miniconda3/python.exe
      Jupyter: 4.9.1
      Kernels: python3

(\) Checking Jupyter engine render....2023-06-13 09:30:53,339 - traitlets - WARNING - Kernel Provisioning: The 'local-provisioner' is not found.  This is likely due to the presence of multiple jupyter_client distributions and a previous distribution is being used as the source for entrypoints - which does not include 'local-provisioner'.  That distribution should be removed such that only the version-appropriate distribution remains (version >= 7).  Until then, a 'local-provisioner' entrypoint will be automatically constructed and used.
The candidate distribution locations are: ['C:\\Users\\tbats\\Miniconda3\\lib\\site-packages\\jupyter_client-5.3.4.dist-info', 'C:\\Users\\tbats\\Miniconda3\\lib\\site-packages\\jupyter_client-7.0.6.dist-info']
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.3
      Path: C:/PROGRA~1/R/R-42~1.3
      LibPaths:
        - C:/Users/tbats/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.3/library
      knitr: 1.43
      rmarkdown: 2.22

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
This is a Pandoc issue about markdown syntax rules, see <https://pandoc.org/MANUAL.html#bullet-lists>.
Unfortunately, Pandoc also has a rule to have an empty line surrounding code blocks.

**Comment by mcanouil** [comment]
@cderv Do you think there is something that can be done here?
