### ISSUE TITLE
Quarto does not render custom PowerPoint template from Jupyter notebook

### ISSUE THREAD

**Issue by Fohlen** [quarto-dev/quarto-cli#5918]
### Bug description

I followed the instructions provided by the [quarto documentation](https://quarto.org/docs/presentations/powerpoint.html#powerpoint-templates) to customise my PPTX presentations via a template. I customised this simple template. When I render a presentation, it does not use the template.

### Steps to reproduce

1. Create quarto template via `quarto pandoc -o template.pptx --print-default-data-file reference.pptx`
2. Create sample presentation
3. Render via `quarto render hello.ipynb --to pptx`

See attached `template.pptx`, `hello.ipynb` and the resulting `hello.pptx`.
[Archive.zip](https://github.com/quarto-dev/quarto-cli/files/11743118/Archive.zip)

### Expected behavior

It should render my presentation using the template.

### Actual behavior

It uses the default template regardless.

### Your environment

- OS: MacOS Ventura 13.3.1 (a) 
- Python: 3.10.12
- Quarto: 1.3.361

```bash
pip freeze | grep jupyter
jupyter-events==0.6.3
jupyter-lsp==2.2.0
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.6.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.2
jupyterlab-pygments==0.2.2
jupyterlab_server==2.23.0
```

### Quarto check output

```bash
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /Applications/quarto/bin
```

**Comment by cderv** [comment]
Thanks for opening the issue. 

I believe you did not modify the template as expected. This is explained in Pandoc documentation at: https://pandoc.org/MANUAL.html#option--reference-doc

PPTX output will use the Layout slides from the reference doc. So the content does not matter, only the layout. 

In powerpoint this is called the slide master 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/3085e495-2ee7-4e7a-9f8e-34abbcf87813)

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/28458106-8293-4c50-a404-1e9acf78837e)


You need to make modification to the Layout slides (those with names as described in the doc https://pandoc.org/MANUAL.html#option--reference-doc for powerpoint). 

I don't think there is good example of this anywhere yet. Probably some tutorial to do at some point. 🤔 

If you do that, then this is working - no specific issue related to ipynb file. 

i'll reclassify this issue as documentation to keep the idea of documenting this better somewhere

**Comment by Fohlen** [comment]
Indeed, I am a very novice with PPTX, and this was the solution. My bad. Can be closed. A link to [PowerPoint slide masters](https://support.microsoft.com/en-us/office/what-is-a-slide-master-b9abb2a0-7aef-4257-a14e-4329c904da54) would be sufficient! 😄
