### ISSUE TITLE
In TeX, table caption is inserted between \begin{table} and [placement options]

### ISSUE THREAD

**Issue by hughjonesd** [quarto-dev/quarto-cli#593]
This relates to https://github.com/hughjonesd/huxtable/issues/223. Huxtable produces TeX tables programmatically from within R. The table starts like 

```
\begin{table}[ht]
...
```

In a Quarto code block with a label and/or caption set via a chunk option, a TeX caption is produced:

```
\begin{table}
\caption{\label{tbl-iris}Iris Data }
[ht]
```

The problem is that the `\caption` statement is being placed between `\begin{table}` and the table placement options `[ht]`.
Instead, the caption should be placed after the `[ht]`.

Test case:

    ---
    title: "test"
    format: pdf
    editor: visual
    ---

    ```{r}
    #| include: false
    library(huxtable)
    ```

    @tbl-iris shows up and can be cross-referenced, but it has an "\[ht\]" in front of it.

    ```{r}
    #| label: tbl-iris
    #| tbl-cap: "Iris Data"

    hux(head(iris, n = 1))
    ```

**Comment by jjallaire** [comment]
Good catch! Thanks for reporting. Here is where we define the patterns for finding table envelopes: 

https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/filters/quarto-pre/table-captions.lua#L7-L9

I am not 100% familiar with all of the things that could be included in table placement options (nor whether they are valid in all of the forms of table we seek with our patterns). Could you suggest some changes to these patterns that would work w/ this scenario? If you want to experiment directly you can install the development version as follows:

https://github.com/quarto-dev/quarto-cli#development-version

You can then just modify the Lua script linked to above and run (there is no compile or build step).

**Comment by hughjonesd** [comment]
I've made a suggested change directly via github.

**Comment by jjallaire** [comment]
Fixed with: https://github.com/quarto-dev/quarto-cli/commit/0a47ba0648ba59ee09966a33414275e83dc7e6a2
