### ISSUE TITLE
Fedora 38: SVG device breaks PDF format

### ISSUE THREAD

**Issue by wklimowicz** [quarto-dev/quarto-cli#5950]
### Bug description

On Fedora 38, when setting `dev: svg` with the pdf format, the svg generated from rendering has size 0, and throws an error at the `rsvg-convert` step:

```
Error reading SVG test_files/figure-pdf/unnamed-chunk-1-1.svg: XML parse error: Input file is too short
ERROR: Failed when attempting to convert a SVG to a PDF for output.
 An error occurred while attempting to run rsvg-convert.
Error code 1
```

The generated svg file in `_files/figure-pdf/unnamed-chunk-1-1.svg` is empty. 

### Steps to reproduce

test.qmd:
````
---
format: pdf
---

```{r}
#| dev: svg
plot(cars)
```
````

### Expected behavior

Should generate a valid svg file, which is then converted to pdf and put in `_files/mediabag`

### Actual behavior

Produces an empty svg file and an error.

### Your environment

- IDE: NVim v0.10.0
- OS: Fedora 38

This does not occur on Ubuntu, and replicates on a clean Fedora installation.

### Quarto check output

[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/wojtek/bin/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3, octave, julia-1.9

(/) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /opt/R/4.3.0/lib64/R
      LibPaths:
        - /home/wojtek/R/x86_64-pc-linux-gnu-library/4.3
        - /opt/R/4.3.0/lib64/R/library
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Could you try to render to SVG with R only?

**Comment by wklimowicz** [comment]
This code works fine, and creates a valid svg:

```r
svg("plot.svg")
plot(cars)
dev.off() 
```

**Comment by mcanouil** [comment]
I am adding "needs-repro" as for now, I can't reproduce.

**Comment by wklimowicz** [comment]
I've looked into this more and it seems the issue is pairing quarto with the Fedora `texlive-scheme-full` installation.

After removing the fedora version with `sudo dnf remove texlive-\*`, and using `tinytex::install_tinytex()`, everything works as it should. I have no clue why this happens, since I thought the svg file is generated further up the chain, before any calls to LaTeX are made.

The `rmarkdown` version doesn't work either way, but I don't think [it works out of the box for Rmd](https://github.com/rstudio/rmarkdown/issues/2238).

Happy to close this issue if you think it's a problem with Fedora and not Quarto.

**Comment by cscheid** [comment]
Hm. That's unfortunate, but we can't generally test every possible distribution for their dependencies to be compatible with Quarto, and we [recommend tinytex in general anyway](https://quarto.org/docs/output-formats/pdf-engine.html).

@mcanouil I think this is enough evidence that we should add a note to our debugging list, to the effect of "if the bug report is on the PDF engine, first ask users to try tinytex"

**Comment by mcanouil** [comment]
To include SVG in LaTeX, you need to allow them first using for example `\usepackage{svg}`.

I created an environment in Fedora 38 from scratch (inside a Docker container) and it worded as intended at least with TinyTex.

@cscheid I agree with you. Do you think, `quarto check` could show if TinyTex is installed or being used, _i.e._, results of `quarto list tools`?

**Comment by cscheid** [comment]
Yes, this would be a good new enhancement.
