### ISSUE TITLE
 Indentation Error with Quarto's YAML Parser

### ISSUE THREAD

**Issue by LeoLin990405** [quarto-dev/quarto-cli#5979]
### Bug description

I have encountered a problem when using Quarto in RStudio. When I attempt to parse a YAML file, I get an error message indicating a bad indentation of a mapping entry at line 9, column 8. The specific error message is YAMLError: bad indentation of a mapping entry at line 9, column 8: toc: true. I have tried various combinations of indents and spaces, but the error persists. I am unsure about what has gone wrong.

### Steps to reproduce

---
title: "Challenge 9 "
author: "Zhongyue Lin"
description: "Creating a function"
date: "6/19/2023"
format:
  html:
    df-print: paged
    toc: true
    code-copy: true
    code-tools: true
categories:
  - challenge_9
---
ERROR: YAMLError: bad indentation of a mapping entry at line 9, column 8:
        toc: true
           ^

YAMLError: bad indentation of a mapping entry at line 9, column 8:
        toc: true
           ^
    at generateError (file:///Applications/quarto/bin/quarto.js:10719:12)
    at throwError (file:///Applications/quarto/bin/quarto.js:10722:11)
    at readBlockMapping (file:///Applications/quarto/bin/quarto.js:11361:20)
    at composeNode (file:///Applications/quarto/bin/quarto.js:11528:84)
    at readBlockMapping (file:///Applications/quarto/bin/quarto.js:11346:17)
    at composeNode (file:///Applications/quarto/bin/quarto.js:11528:84)
    at readDocument (file:///Applications/quarto/bin/quarto.js:11642:5)
    at loadDocuments (file:///Applications/quarto/bin/quarto.js:11679:9)
    at load (file:///Applications/quarto/bin/quarto.js:11684:23)
    at parse3 (file:///Applications/quarto/bin/quarto.js:11694:12)

### Expected behavior

I expect the YAML file to be parsed correctly without any errors.

### Actual behavior

I expect the YAML file to be parsed correctly without any errors.

### Your environment

IDE: RStudio 2023.06.0+421
OS: macOS Monterey, Version 12.6
quarto --version 1.3.361

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: /Users/leo/opt/anaconda3/bin/python
      Jupyter: 4.11.1
      Kernels: python3, julia-1.8, matlab, matlab_connect, ir

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Thanks for the report.
Could you use markdown code blocks ` ``` ` to embed the code, please?

**Comment by LeoLin990405** [comment]
````qmd
---
title: "Challenge 9 "
author: "Zhongyue Lin"
description: "Creating a function"
date: "6/19/2023"
format:
  html:
    df-print: paged
    toc: true
    code-copy: true
    code-tools: true
categories:
  - challenge_9
---

```{r setup, include=FALSE}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```
```{r}
clean_data <- function(file_path, drop_columns = NULL) {
  # Read the CSV file
  data <- read_csv(file_path)
  
  # Drop rows with NA values in the 'children' column
  data$children[is.na(data$children)] <- 0
  
  # Combine year, month, and day of month into a single date column and then remove the original columns related to date
  data <- data %>%
    mutate(arrival_date = as.Date(paste(arrival_date_year, arrival_date_month, arrival_date_day_of_month, sep = "-"), format = "%Y-%B-%d")) %>%
    select(-arrival_date_year, -arrival_date_month, -arrival_date_week_number, -arrival_date_day_of_month)

  # Convert the variables 'is_canceled' and 'is_repeated_guest' to logical (boolean) values
  data <- data %>%
    mutate(is_canceled = as.logical(is_canceled), is_repeated_guest = as.logical(is_repeated_guest))

  # Convert categorical variables into factors
  cat_cols <- c('hotel', 'meal', 'country', 'market_segment', 'distribution_channel', 'reserved_room_type', 
                'assigned_room_type', 'deposit_type', 'customer_type', 'reservation_status')
  data[cat_cols] <- lapply(data[cat_cols], factor)

  # Drop specified columns if provided
  if (!is.null(drop_columns)) {
    data <- data %>% select(-all_of(drop_columns))
  }
  
  return(data)
}

# Use the function to read and clean the data
hotel_bookings <- clean_data("_data/hotel_bookings.csv", drop_columns = "reservation_status_date")
head(hotel_bookings)
```
The end.
````

**Comment by mcanouil** [comment]
Can't reproduce the issue, although I had to comment the "hotel_bookings" line since the csv does not exist.
But, I don't believe it's going to make a difference as the YAML is parsed way before the code is evaluated.

---

See <https://quarto.org/docs/computations/r.html#knitr-options> and <https://quarto.org/docs/computations/execution-options.html#figure-options> on how to define knitr options in Quarto (recommended approach).
Also don't mixed YAML, multi-line and inline code cell options.

````
---
title: "Challenge 9 "
author: "Zhongyue Lin"
description: "Creating a function"
date: "6/19/2023"
format:
  html:
    df-print: paged
    toc: true
    code-copy: true
    code-tools: true
categories:
  - challenge_9
execute:
  echo: true
  warning: false
  message: false
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(ggplot2)
```

...
````

**Comment by cscheid** [comment]
You're using RStudio and not getting a visual marker of the YAML error on the .qmd file? Can you upload this file exactly as you have it to a git repository?
