### ISSUE TITLE
`quarto check`: report on tinytex usage

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#5980]
See #5950 for a use case. We should be encouraging users to try `tinytex` before reporting a latex bug, since we've been having a number of issues with incompatible system installations of texlive etc.

**Comment by cderv** [comment]
FYI there is a more generic issue that covers this one: https://github.com/quarto-dev/quarto-cli/issues/1392

Just sharing to cross reference them

**Comment by cderv** [comment]
And FWIW you also opened this one in the past: https://github.com/quarto-dev/quarto-cli/issues/4845 😉

**Comment by cscheid** [comment]
Closing as duplicate. The fool who reported this issue should know better!
