### ISSUE TITLE
Problem with plotly in rendered Jupyter Notebooks

### ISSUE THREAD

**Issue by nomadiq** [quarto-dev/quarto-cli#5990]
### Bug description

When rendering a .ipynb file to html the resultant html file has some code like:

requirejs.config({
    paths: {
        'plotly': ['https://cdn.plot.ly/plotly-2.12.1.min']
    }
});

But https://cdn.plot.ly/plotly-2.12.1.min no longer exists. The plots are no longer being generated.

I was able to fudge by editing the html with different location of plotly:

cdnjs.cloudflare.com/ajax/libs/plotly.js/2.24.2/plotly

Has plotly moved its repository for the library and quarto needs to be updated?

**Comment by nomadiq** [comment]
Problem is with plotly's CDN. Should hopefully be rectified soon.

**Comment by nomadiq** [comment]
Would be nice to have a feature where one can use a local copy rather than rely on the CDN

**Comment by cscheid** [comment]
That's unfortunately not something quarto can control, since it's the plotly library itself emitting the code.
