### ISSUE TITLE
Passing non default extension to markdown input format 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#60]
Using command line I can do 
````shell
pandoc --from markdown+emoji --to revealjs -s -o test.html test.qmd
````

Is this supporting in quarto ? I tried a few thing with odd result

Doing 
```
---
format: revealjs
variant: +emoji
---
````

will lead to  adding the extension to the `to` format

````
pandoc 
  to: revealjs+emoji
  from: markdown
  standalone: true
  filters:
    - crossref
 ````

I also tried at command line but no luck passing the `--from` argument from pandoc command line to `quarto render`. It does the same (moving the extensions to the to format)

```
❯ quarto render test2.qmd --from markdown+emoji
pandoc --from markdown+emoji
  to: revealjs+emoji
  from: markdown
  standalone: true
  filters:
    - crossref

metadata
  hash: true

The extension emoji is not supported for revealjs
```

````
❯ quarto render test2.qmd --to revealjs --from markdown+emoji
pandoc --from markdown+emoji
  to: revealjs+emoji
  from: markdown
  standalone: true
  filters:
    - crossref

metadata
  hash: true

The extension emoji is not supported for revealjs
````

## test file 

````markdown
---
title: test
format: revealjs
# variant: +emoji
---

# Slide with emoji

Here is a emoji

:smile:
````

**Comment by jjallaire** [comment]
This should work fine if you just use the `from` option (not variant):

```markdown
---
title: "Untitled"
format:
  html:
    from: markdown+emoji
---

:smile:
```

This should also work w/ the explicit command line `pandoc foo.qmd --from markdown+emoji`

```markdown
---
title: "Untitled"
format: html
---

:smile:
```

You will see `format: markdown` printed as part of the render output but you'll also see the command line above overrides that default.

**Comment by apreshill** [comment]
Thank you! Can confirm this works with revealjs in Quarto:
![Uploading Screen Shot 2021-07-23 at 2.45.00 PM.png…]()
