### ISSUE TITLE
Crosstalk filter_checkbox not working in Quarto

### ISSUE THREAD

**Issue by jonathanmburns** [quarto-dev/quarto-cli#6004]
### Bug description

When I use plotly and crosstalk to create an interactive graph and render it in Quarto, the checkboxes don't show for filter_checkbox.

The functionality is there; I can select and deselect the options; however, the actual checkboxes don't show and there is no indication within the crosstalk filter_checkbox which fields have been selected.

The titles for the filters are also cut off on the left side.

### Steps to reproduce

````qmd

---
title: "Reprex"
format: html
execute:
  echo: false
  warning: false
---

## Reproducible Example



```{r}
library(dplyr)
library(plotly)
library(data.table)
library(crosstalk)

reprex<-data.frame(
  "Category" = c("a", "b", "c", "d", "e", "f", "g"),
  "Today" = seq(1, 7, 1),
  "Yesterday" = seq(1, 14, 2),
  "Two.Days.Ago" = seq(3, 9, 1)
)

figrepex <- reprex |>
  setDT() |>
  melt(id.vars="Category", measure.vars=c("Today", "Yesterday", "Two.Days.Ago"), value.name = "Counts", variable.name="Compare") |>
  mutate(Compare = factor(Compare, levels=c("Today", "Yesterday", "Two.Days.Ago")) 
  )|>
  setDF() |>
  SharedData$new()

figrep<-figrepex %>% 
  plot_ly(x = ~Category, y = ~Counts, color = ~Compare, type='bar')

bscols(
  widths = c(3,NA),
  list(
    filter_checkbox(id="Compare", label="Compare",
                    sharedData = figrepex, group=~Compare),
    filter_checkbox(id = "Category", label="Category",
                    sharedData = figrepex, group=~Category)
  ),
  figrep
)
```

````

### Expected behavior

When I run the code, I should see the output with checkboxes visible:

![Plotly and Crosstalk in RStudio](https://github.com/quarto-dev/quarto-cli/assets/82161318/6e1fad4c-cb65-4045-b828-9077bfe117be)

This is obtained from the following code:

````
reprex<-data.frame(
  "Category" = c("a", "b", "c", "d", "e", "f", "g"),
  "Today" = seq(1, 7, 1),
  "Yesterday" = seq(1, 14, 2),
  "Two.Days.Ago" = seq(3, 9, 1)
)

figrepex <- reprex |>
  setDT() |>
  melt(id.vars="Category", measure.vars=c("Today", "Yesterday", "Two.Days.Ago"), value.name = "Counts", variable.name="Compare") |>
  mutate(Compare = factor(Compare, levels=c("Today", "Yesterday", "Two.Days.Ago")) 
  )|>
  setDF() |>
  SharedData$new()

figrep<-figrepex %>% 
  plot_ly(x = ~Category, y = ~Counts, color = ~Compare, type='bar')

bscols(
  widths = c(3,NA),
  list(
    filter_checkbox(id="Compare", label="Compare",
                    sharedData = figrepex, group=~Compare),
    filter_checkbox(id = "Category", label="Category",
                    sharedData = figrepex, group=~Category)
  ),
  figrep
)
````

### Actual behavior

Instead, the checkboxes don't show and the filter headers are chopped off as well:

![Plotly and Crosstalk in Quarto](https://github.com/quarto-dev/quarto-cli/assets/82161318/53d8969c-eb57-45de-aee8-94083c28223f)

### Your environment

- IDE:  I have replicated this on two different versions of RStudio:
RStudio 2023.03.0+386 
RStudio 2023.06.0+421 
- OS: I have replicated this on laptop running Windows 10 Enterprise (using RStudio 2023.03.0+38) and a server running Windows Server 2019 (running RStudio 2023.06.0+421)

### Quarto check output

On the laptop, quarto check gives:
[>] Checking Quarto installation......OK
      Version: 1.2.335
      Path: C:\Program Files\RStudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: C:/.../AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 4.10.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/PROGRA~1/R/R-42~1.0
      LibPaths:
        - C:/.../Documents/R/win-library/4.2
        - C:/Program Files/R/R-4.2.0/library
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK

On the server, quarto check gives:

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.361
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.4
      Path: C:/Program Files/Python39/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.2.3
      Path: C:/PROGRA~1/R/R-42~1.3
      LibPaths:
        - C:/Users/.../AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.3/library
      knitr: 1.42
      rmarkdown: 2.22

[>] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
I suspect it's `bscols()` emitting some output that doesn't play well with our CSS.

**Comment by cscheid** [comment]
> Version: 1.2.335

You're also running a relatively old version of `quarto`. Can you try installing the stable version and confirming the issue is still there?

**Comment by jonathanmburns** [comment]
Yes, sure.
On the server (runnings Windows Server 2019), I am running version 1.3.361 and I have the same issue.

```
On the server, quarto check gives:
[>] Checking versions of quarto binary dependencies...
Pandoc version 3.1.1: OK
Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
Version: 1.3.361
```

I also updated it now on my laptop (Windows Enterprise 10) to version 1.3.361 and, yes, the problem persists.
Thanks
