### ISSUE TITLE
fig-width and fig-height only set by first chunk for python/matplotlib

### ISSUE THREAD

**Issue by thatchermo** [quarto-dev/quarto-cli#6008]
### Bug description

I've noticed that fig-width and fig-height, when set in a Python code chunk, only seem to work once. In other words, their first appearance in a code chunk sets their values for all further Python code chunks. Contrast this with R behavior, where each code chunk can have a different width and height. I've seen bug reports for the Jupyter engine, but this is behavior using knitr, I believe. I haven't seen exactly this bug report in the list, but could have missed it.

Thanks for your work on Quarto!

### Steps to reproduce

````qmd

---
title: "fig-width test"
format: html
editor_options: 
  chunk_output_type: console
---

## Make a Wide R Plot

```{r}
#| fig-width: 8
#| fig-height: 2
plot(x=c(1, 2, 3, 4), y=c(1, 4, 9, 16))
```

## Make a Square R Plot

```{r}
#| fig-width: 3
#| fig-height: 3
plot(x=c(1, 2, 3, 4), y=c(1, 4, 9, 16))
```

## Make a Wide Python Plot

```{python}
#| fig-width: 8
#| fig-height: 2
import matplotlib.pyplot as plt
plt.plot([1,2,3,4], [1,4,9,16], 'ro')
plt.show()
```

## Make a Square Python Plot

```{python}
#| fig-width: 3
#| fig-height: 3
plt.plot([1,2,3,4], [1,4,9,16], 'ro')
plt.show()
```

````

### Expected behavior

All plots should have dimensions set by chunk's fig-width, fig-height.

### Actual behavior

After first python chunk, fig-height, fig-width not respected.

### Your environment

Quarto Version: 1.3.361
RStudio: 2023.06.0+421
R: 4.3.0 (2023-04-21)
Python: Python 3.8.13 (reported by reticulate)
Reticulate 1.29 REPL
OS: Linux (Ubuntu Jammy)

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/lib/R
      LibPaths:
        - /home/thatcher/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK

**Comment by cderv** [comment]
This has now been fixed in **reticulate** dev version. if you update, it should work properly within Quarto now.
