### ISSUE TITLE
ERROR: API Error: 429 - Too Many Requests

### ISSUE THREAD

**Issue by hopezh** [quarto-dev/quarto-cli#6014]
### Bug description

Basically, I had the same issue as the one reported in [#1577](https://github.com/quarto-dev/quarto-cli/issues/1577), i.e., " was able to publish a toy example once using the command line, but have not been able to successfully do so again even when using the same procedure", quoting [@jcblsn](https://github.com/quarto-dev/quarto-cli/issues/1577#issue-1322204864). 

May I ask how to solve this issue, considering that no solution was mentioned in #1577. 

The complete error message I had is shown below. 

```Shell
> quarto publish quarto-pub
? Publish with account: › myGmail@gmail.com
? Site name: › oatsite2

[✓] Creating quarto-pub site
ERROR: API Error: 429 - Too Many Requests

Error: API Error: 429 - Too Many Requests
    at QuartoPubClient.createSite (file:///Applications/quarto/bin/quarto.js:111358:23)
    at async file:///Applications/quarto/bin/quarto.js:108983:26
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:56613:9)
    at async handlePublish (file:///Applications/quarto/bin/quarto.js:108980:9)
    at async publishSite (file:///Applications/quarto/bin/quarto.js:121225:38)
    at async publish5 (file:///Applications/quarto/bin/quarto.js:121443:61)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:121399:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:121435:13)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:121387:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13) 
```

### Steps to reproduce

1. I use `quarto create-project oatsite2 --type website` to create a quarto website project.
2. Then, I `CD oatsite2`, and run `quarto publish quarto-pub`. 

### Expected behavior

I should get the example website published on `quartopub.com`, just as the one I have published here [oatsite](https://oat.quarto.pub/oatsite/).  

### Actual behavior

I got the following error:

```Shell
> quarto publish quarto-pub
? Publish with account: › myGmail@gmail.com
? Site name: › oatsite2

[✓] Creating quarto-pub site
ERROR: API Error: 429 - Too Many Requests

Error: API Error: 429 - Too Many Requests
    at QuartoPubClient.createSite (file:///Applications/quarto/bin/quarto.js:111358:23)
    at async file:///Applications/quarto/bin/quarto.js:108983:26
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:56613:9)
    at async handlePublish (file:///Applications/quarto/bin/quarto.js:108980:9)
    at async publishSite (file:///Applications/quarto/bin/quarto.js:121225:38)
    at async publish5 (file:///Applications/quarto/bin/quarto.js:121443:61)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:121399:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:121435:13)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:121387:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13) 
```

### Your environment

- IDE: Neovim v0.10.0-dev-532+gc07dceba3-Homebrew
- OS: Mac OS Ventura 13.4.1
- Quarto: 1.3.361

### Quarto check output

```Shell
> quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10 (Conda)
      Path: /Users/minioat/opt/anaconda3/envs/dl/bin/python
      Jupyter: 4.7.1
      Kernels: julia-1.6, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
Mostly for context, are you using a proxy, firewall or anything like that (_e.g._, enterprise network, _etc._)?

**Comment by victorfeagins** [comment]
I get the same error but with just publishing a simple qmd file.

**Comment by mcanouil** [comment]
@victorfeagins Same question as above. The more context you give, the better Quarto team can address the issue.

**Comment by victorfeagins** [comment]
I am on campus wifi but never had a problem before.  Used the quarto-pub eariler this week.

**Comment by mcanouil** [comment]
We are investigating the issue.
We'll report back here.

**Comment by hopezh** [comment]
> Mostly for context, are you using a proxy, firewall or anything like that (_e.g._, enterprise network, _etc._)?

I'm using a home fiber broadband internet, and my computer is connected to it using wire, not wifi. I'm not uisng a proxy, and I have no firewall installed, as far as I know.

**Comment by mcanouil** [comment]
Some update, the "ERROR: API Error: 429 - Too Many Requests" is actually not a user side error, nor a Quarto CLI error.
The message is somehow a bit miss-leading.
To note, it should work properly now.

CC @softwarenerd

**Comment by hopezh** [comment]
> Some update, the "ERROR: API Error: 429 - Too Many Requests" is actually not a user side error, nor a Quarto CLI error. The message is somehow a bit miss-leading. To note, it should work properly now.
> 
> CC @softwarenerd

I confirm that I no longer have the error as reported above after successfully published a few test websites and a book to `quartopub.com`. 

Thanks @mcanouil and the team for the quick response and fix. 

<img width="1209" alt="Screen Shot 2023-06-24 at 19 15 30 PM" src="https://github.com/quarto-dev/quarto-cli/assets/23435810/10f35406-1ab3-46d4-8d55-a33b1cf8642e">
