### ISSUE TITLE
docx table: set columns width seems not work

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#6015]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/6006

<div type='discussions-op-text'>

<sup>Originally posted by **aborruso** June 22, 2023</sup>
### Description

Hi,
when I render this qmd, the columns width it not the one I have set. How to force it to be `50,30,20`?

I'm using quarto 1.4.43 in Debian 11.

````qmd
---
title: "UV2"
format:
  docx:
    toc: false
    number-sections: false
    highlight-style: github
    tbl-colwidths: [50,30,20]
---

# test


| Question | Reply | Note |
| --- | --- | --- |
|aMagna sint duis proident do. Laboris Lorem exercitation consectetur quis|a|b|
|aMagna sint duis proident do. Laboris Lorem exercitation consectetur quis|a|b|

````

![image](https://github.com/quarto-dev/quarto-cli/assets/30607/b914aa07-4cd8-48f8-b8ae-f78044c83f94)
</div>

**Comment by mcanouil** [comment]
@aborruso Did you open this from the discussion you opened yesterday by mistake?

**Comment by aborruso** [comment]
> @aborruso Did you open this from the discussion you opened yesterday by mistake?

Why by mistake @mcanouil ?
After I have created the discussion, I've reviewed and tested it other times: the output doesn't produce what is expected by the documentation, so an issue seems more useful and fairer to me.
Am I wrong?

**Comment by mcanouil** [comment]
It's not about right or wrong.
I discovered the discussion and the issue nearly at the same time without any comment explaining why the issue has been opened or without any additional information.
One could read the fast to open an issue from a discussion without reply (yet) as "being impatient" amongst other interpretation.
This also means two places for the same discussion.
It would have been better to open either an issue or a discussion and wait from there.

This being said:

- `tbl-colwidths` is indeed listed in the reference page for Word document format.
It does have an effect, as the table occupies the full width of the page, but indeed, the column width is not respected (more of a side effect of Pandoc I believe).
- column specification does not work in Pandoc itself for Word document (<https://pandoc.org/MANUAL.html#extension-pipe_tables>)

Take the following table:

````qmd
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Column 1                                                Column 2
------------------------------------------------------  ------------------------------------------------------------------------------------------------------------------------------------------------------------------
I want the contents of this cell to fit into one line   Word1 Word2

------------------------------------------------------  ------------------------------------------------------------------------------------------------------------------------------------------------------------------

: **Column 1 is narrow.** For column 1: 54 dashes in Markdown source for
separator line; for column 2: 162 dashes in separator line (300% of column 1).
````

Then:

- `quarto pandoc index.qmd --from markdown --to html -o index.html`  
  <img width="818" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/cf868711-f83f-4a63-9328-c4b7bef2af4b">
- `quarto pandoc index.qmd --from markdown --to docx -o index.docx`  
  <img width="634" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/23030084-6c9c-47b2-9fe4-9698d89624ae">

**Comment by mcanouil** [comment]
@dragonstyle Does `tbl-colwidths` supposed to work in Word document? I did not see anything in the codebase showing that Quarto is handling that itself.

**Comment by aborruso** [comment]
Hi @mcanouil ,

> One could read the fast to open an issue from a discussion without reply (yet) as "being impatient" amongst other interpretation.

It's not nice to be rated as impatient. Especially in this wonderful discussion space, a fantastic application.

> This also means two places for the same discussion.
> It would have been better to open either an issue or a discussion and wait from there.


I had opened a discussion, but then i did some more tests and it seemed like a bug. And I thought it best to report it.

In [word documentation](https://quarto.org/docs/reference/formats/docx.html) I read `An array of numbers (e.g. `[40, 30, 30]`): Array of explicit width percentages.`

If in example I have,

````quarto
---
title: "UV2"
format:
  docx:
    toc: false
    number-sections: false
    highlight-style: github
    tbl-colwidths: [40,30,30]
---

# test


| Question | Reply | Note |
| --- | --- | --- |
|c|a|b|
|c|a|b|
````

I have  `[40, 30, 30]` columns table


![image](https://github.com/quarto-dev/quarto-cli/assets/30607/5a765150-517d-496a-9d85-ffe564735d1f)


If I have long cells text

````quarto
---
title: "UV2"
format:
  docx:
    toc: false
    number-sections: false
    highlight-style: github
    tbl-colwidths: [40,30,30]
---

# test


| Question | Reply | Note |
| --- | --- | --- |
|aMagna sint duis proident do. Laboris Lorem exercitation consectetur quis|a|b|
|aMagna sint duis proident do. Laboris Lorem exercitation consectetur quis|a|b|
````

I have that `tbl-colwidths: [40,30,30]` does not work.

![image](https://github.com/quarto-dev/quarto-cli/assets/30607/bc6e700c-6033-4cc2-9bcd-00529605c37f)

It seems to me a bug and I thought it was useful to report it here in the issues section. If it's not a bug I'll close it immediately, and I open a PR to add in the word documentation "be careful, it doesn't work correctly with cells that contain long text".

**Comment by mcanouil** [comment]
> It's not nice to be rated as impatient. Especially in this wonderful discussion space, a fantastic application.

@aborruso I did not say you were. I say one could think you were.
This is also why I asked the reason to open the issue while there was already the discussion.
All is fine from my end.

**Comment by mcanouil** [comment]
Thanks for the additional examples.

**Comment by aborruso** [comment]
> @aborruso I did not say you were. I say one could think you were.

My first post here at the beginning seems well documented to me.
It seems to me that it clearly reports - looking at the documentation - what appears to be a bug.
For bugs, I've always understood that it was better to open an issue and I never thought to make people think I was impatient.
I was hoping to appear as someone who wanted to give a small, little contribution.

Thank you for the pandoc note. If it has an impact on quarto, it would be better to include it in the quarto documentation as well.

**Comment by mcanouil** [comment]
We are making sure any question not matter if they are bugs or actual questions are being answered, no matter if they are posted as GitHub Issues or Discussions.
My point is that since we go through both, you could have put a note in the discussion to state that you felt it was better to open an issue (which is 100% fine), hence to disregard the Discussion in favour of the issue.

There are currently no strict rules on where to post what by the way, so again nothing "wrong".

**Comment by mcanouil** [comment]
Some more investigation/clues that the issue is either with Word and/or Pandoc.

From the below code.

````qmd
---
format: native
---

| fruit        | price        |
|--------------|--------------|
| apple juice  | 2.05         |
| pear juice   | 1.37         |
| orange juice | 3.09         |

: Fruit prices {tbl-colwidths="[1,99]"}
````

```sh
quarto render index.qmd
```

Then using Pandoc to render based on the AST/native format.

- Pandoc: AST to HTML
  ```sh
  quarto pandoc index.native --from native --to html -o index.html
  ```
  <img width="1511" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/04938ca2-9a40-4148-b5d6-babf1f143356">


- Pandoc: AST to DOCX
  ```sh
  quarto pandoc index.native --from native --to docx -o index.docx
  ```
  <img width="633" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/3f265837-8174-4f11-98c8-b9db4f5cc42f">

**Comment by cderv** [comment]
it seems like something related to how Docx works. 

When `[1, 99]` is set in Native form, the OPENXML output for Docx will be 
```openxml
            <w:tblGrid>
                <w:gridCol w:w="79" />
                <w:gridCol w:w="7840" />
            </w:tblGrid>
```

where `79 = ~1% x 7920` and  `7840 = ~99% x 7920`  where `7920` is the textwidth use for docx document and tables (from Pandoc's [source](https://github.com/jgm/pandoc/blob/14f86c348171f44ec0973c3fb0ca30ed182167ac/src/Text/Pandoc/Writers/Docx/Table.hs#L164))

So it seems Pandoc is writing something that takes into account the colwidth and it seems to be the right way from [openxml spec](http://officeopenxml.com/WPtableGrid.php). ([other](http://officeopenxml.com/WPtable.php)

Not sure how DOCX should behave on this OPEN XML. Maybe Word is "fixing" some too small size, or maybe something is missing by Pandoc so that the sizing in OPEN XML works. 

@rich-iannone maybe you have insight on column size in tables for DOCX ? 🤷

**Comment by aborruso** [comment]
Is there some other ways to define a columns width and to have it properly rendered in a docx output?

If I start from some coded tables (python or R) do I have a way to have in docx output the right column width?

Thank you

**Comment by cderv** [comment]
> If I start from some coded tables (python or R) do I have a way to have in docx output the right column width?

If that is the question to use R Package, Possibly **flextable** has some width options https://ardata-fr.github.io/flextable-book/layout.html
**gt** also have a [`cold_width`](https://gt.rstudio.com/reference/cols_width.html) feature, which may work in DOCX output. 
@rich-iannone can tell us more when he'll pass around.

**Comment by aborruso** [comment]
The problems seems to be Office. If I open the quarto docx output in LibreOffice, I have the right width.

But now I have no idea how this is fixable, because if it depends on Office, if it's an Office bug, I'm afraid everything will be hard to fix :(

![image](https://github.com/quarto-dev/quarto-cli/assets/30607/e4ef8498-e158-4961-ae2b-3b7849f92791)

**Comment by aborruso** [comment]
But in LibreOffice I have two strange square brackets. It seems another bug

![image](https://github.com/quarto-dev/quarto-cli/assets/30607/04b6ae6a-9232-402e-83fe-2bcd67bb73fe)

**Comment by aborruso** [comment]
I'm writing about it, also in pandoc discussion group: https://groups.google.com/g/pandoc-discuss/c/ZHJu54jokp8/m/QvpruPAXAQAJ

**Comment by aborruso** [comment]
And we have a fix in pandoc repo

https://github.com/jgm/pandoc/commit/e634d8b87d9fb877658583b03418c23748b70dc5

**Comment by bryanhanson** [comment]
Here's another example I just came across.  When generating a table with `kable`, two ways of controlling the table width seem to be ignored.  The fix in the pandoc repo looks like it doesn't cover this case.  I can open a new issue if you like.

[test.zip](https://github.com/quarto-dev/quarto-cli/files/11928542/test.zip)

**Comment by aborruso** [comment]
> Here's another example I just came across. When generating a table with `kable`, two ways of controlling the table width seem to be ignored. The fix in the pandoc repo looks like it doesn't cover this case. I can open a new issue if you like.

I think it's better that you open a new issue.

**Comment by aborruso** [comment]
@mcanouil the [pandoc fix](https://github.com/jgm/pandoc/commit/e634d8b87d9fb877658583b03418c23748b70dc5) will solve the problem related to the number of dashes in the line separating the table header from the table body.

I don't know if that issue will have an impact as well in quarto setting `tbl-colwidths: [50,30,20]`.  How can I build a pandoc example, which mimics what quarto does when I set tbl-colwidths: [50,30,20]?

Thank you

**Comment by mcanouil** [comment]
In the end, it should work the same way, because the AST was left untouched. The Pandoc fix only tweak the writer.
So my guess, is it should fix any column width specification regardless of if it was a pipe table, a grid table or an HTML table.

FYI: markdown is translated to AST which is then translated to the formats.

**Comment by aborruso** [comment]
> In the end, it should work the same way, because the AST was left untouched. The Pandoc fix only tweak the writer.

Thank you very much.

**Comment by cderv** [comment]
> And we have a fix in pandoc repo
> 
> [jgm/pandoc@e634d8b](https://github.com/jgm/pandoc/commit/e634d8b87d9fb877658583b03418c23748b70dc5)

@aborruso thanks a lot for your investigation and opening an issue with Pandoc ! Glad to know it is fixed. 

Hopefully, there will be a new Pandoc update to include with our next Quarto release.

**Comment by aborruso** [comment]
> @aborruso thanks a lot for your investigation and opening an issue with Pandoc ! Glad to know it is fixed.

Failing to achieve something as simple as setting the width of a column seemed like something I needed to figure out and try to fix.
I may have also made a little confusion and I apologize.

But I'm glad I was able to make a small contribution.


thank you all

**Comment by mcanouil** [comment]
Any report is contribution enough 😉
Thanks again for it!

**Comment by aborruso** [comment]
> Hopefully, there will be a new Pandoc update to include with our next Quarto release

We have it

https://github.com/jgm/pandoc/releases/tag/3.1.5

**Comment by aborruso** [comment]
> FWIW the current dev branch (and soon next pre-release) now bundles Pandoc 3.1.5

Thank you very much!
