### ISSUE TITLE
CrossRef Intellisense not working in VSCode (only in Quarto v1.3.427)

### ISSUE THREAD

**Issue by justinaskav** [quarto-dev/quarto-cli#6020]
### Bug description

When using CrossRef autocomplete feature for references in VSCode I get this error.

```
Error running filter /Applications/quarto/share/filters/crossref/crossref.lua:
/Applications/quarto/share/filters/crossref/crossref.lua:3448: attempt to call a nil value (global 'init_crossref_options')
stack traceback:
[Error - 01:36:53] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Command failed: /Applications/quarto/bin/tools/pandoc --defaults defaults.yml
Error running filter /Applications/quarto/share/filters/crossref/crossref.lua:
/Applications/quarto/share/filters/crossref/crossref.lua:3448: attempt to call a nil value (global 'init_crossref_options')
stack traceback:

  Code: -32603 
```

I guess the bug is caused by a function naming inconsistency in the release version of v1.3.427.

[crossref.lua](https://github.com/quarto-dev/quarto-cli/blob/1412f03797ca3446cec67d190b8dbd66fff8e5f5/src/resources/filters/crossref/crossref.lua)

```lua
-- chain of filters
return {
  init_crossref_options(),
  ...
}
```

[options.lua](https://github.com/quarto-dev/quarto-cli/blob/1412f03797ca3446cec67d190b8dbd66fff8e5f5/src/resources/filters/crossref/options.lua)

```lua
function initCrossrefOptions()
  return {
    Meta = function(meta)
      crossref.options = readFilterOptions(meta, "crossref")

      -- automatically set maxHeading to 1 if we are in chapters mode, otherwise set to max (7)
      if crossrefOption("chapters", false) then
        crossref.maxHeading = 1
      else
        crossref.maxHeading = 7
      end

    end
  }
end
```

The `main` branch is not affected by this issue, only the current release (v1.3) branch.

### Steps to reproduce

1. Use current Quarto version (v1.3.427)
2. Try to use VSCode Intellisense in .qmd file, that tries to lookup a [reference](https://quarto.org/docs/authoring/cross-references.html#references)

### Expected behavior

Autocomplete works and no error is shown.

### Actual behavior

Autocomplete doesn't work and an error is shown in the output.

### Your environment

- IDE: Visual Studio Code 1.79.2
- OS: MacOS Ventura 13.4

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.427
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
      Jupyter: 4.11.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/justinas/Library/R/arm64/4.2/library
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
To note, this is an issue with the IDE, see <https://github.com/quarto-dev/quarto>.

CC @jjallaire I believe you can transfer issues across repositories.

**Comment by jjallaire** [comment]
@dragonstyle and @cscheid  I think this was introduced in the back port on Friday? Let's see if we can patch this again right away.

**Comment by darthlite** [comment]
Having the same issue. Same version of Quarto and same exact error. Using VSCodium instead of VSCode, though.

**Comment by mcanouil** [comment]
Could you try v1.3.433?

**Comment by justinaskav** [comment]
The https://github.com/quarto-dev/quarto-cli/commit/07a37d748ddd9504d56016c6961803a3d6c4ce61 (v1.3.433) release fixed this issue for me, thanks! I will close the issue.

**Comment by robjhyndman** [comment]
Having the same issue with v1.4.367, and vscode extension v1.101.0. 

```
[Error - 09:52:14] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Command failed: /opt/quarto/bin/tools/pandoc --defaults defaults.yml
Error running filter /opt/quarto/share/filters/crossref/crossref.lua:
/opt/quarto/share/filters/crossref/crossref.lua:5310: attempt to index a nil value (field '?')
stack traceback:
	/opt/quarto/share/filters/crossref/crossref.lua:5030: in function </opt/quarto/share/filters/crossref/crossref.lua:4981>
	[C]: in ?
	[C]: in method 'walk'
	/opt/quarto/share/filters/crossref/crossref.lua:148: in local 'checked_walk'
	/opt/quarto/share/filters/crossref/crossref.lua:200: in function 'run_emulated_filter'
	/opt/quarto/share/filters/crossref/crossref.lua:725: in local 'callback'
	/opt/quarto/share/filters/crossref/crossref.lua:738: in upvalue 'run_emulated_filter_chain'
	/opt/quarto/share/filters/crossref/crossref.lua:773: in function </opt/quarto/share/filters/crossref/crossref.lua:770>
stack traceback:
	/opt/quarto/share/filters/crossref/crossref.lua:148: in local 'checked_walk'
	/opt/quarto/share/filters/crossref/crossref.lua:200: in function 'run_emulated_filter'
	/opt/quarto/share/filters/crossref/crossref.lua:725: in local 'callback'
	/opt/quarto/share/filters/crossref/crossref.lua:738: in upvalue 'run_emulated_filter_chain'
	/opt/quarto/share/filters/crossref/crossref.lua:773: in function </opt/quarto/share/filters/crossref/crossref.lua:770>

  Code: -32603 
```

**Comment by jjallaire** [comment]
@cscheid any idea what this might result from?

@robjhyndman could you send a link to a document (or project as appropriate) that exhibits this?

**Comment by robjhyndman** [comment]
https://github.com/robjhyndman/weird
I tried making a MRE from this repo, and the problem disappeared. I removed all temp files and folders in case something old was causing the problem, but that didn't help.

**Comment by jjallaire** [comment]
Interesting, I too seem to find the crossers completions working as expected. 

What happens if you fully render the book, then reload VS Code, then try to get completions?

**Comment by robjhyndman** [comment]
Still causing problems. I've managed to create a MRE at https://github.com/robjhyndman/quarto-problem

If I try to add a reference to `index.qmd`, I get the error. If I remove the cross-reference to `@sec-test`, the problem goes away. So the ref/cross-ref to `sec-test` seems to create the problem.

**Comment by cscheid** [comment]
@jjallaire I'm seeing precisely the same thing.

**Comment by robjhyndman** [comment]
This is what I get running the above command from a terminal on my MRE.

```
Error running filter /opt/quarto/share/filters/crossref/crossref.lua:
/opt/quarto/share/filters/crossref/crossref.lua:5310: attempt to index a nil value (field '?')
stack traceback:
        /opt/quarto/share/filters/crossref/crossref.lua:5030: in function </opt/quarto/share/filters/crossref/crossref.lua:4981>
        [C]: in ?
        [C]: in method 'walk'
        /opt/quarto/share/filters/crossref/crossref.lua:148: in local 'checked_walk'
        /opt/quarto/share/filters/crossref/crossref.lua:200: in function 'run_emulated_filter'
        /opt/quarto/share/filters/crossref/crossref.lua:725: in local 'callback'
        /opt/quarto/share/filters/crossref/crossref.lua:738: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/crossref/crossref.lua:773: in function </opt/quarto/share/filters/crossref/crossref.lua:770>
stack traceback:
        /opt/quarto/share/filters/crossref/crossref.lua:148: in local 'checked_walk'
        /opt/quarto/share/filters/crossref/crossref.lua:200: in function 'run_emulated_filter'
        /opt/quarto/share/filters/crossref/crossref.lua:725: in local 'callback'
        /opt/quarto/share/filters/crossref/crossref.lua:738: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/crossref/crossref.lua:773: in function </opt/quarto/share/filters/crossref/crossref.lua:770>
ERROR: Error running Pandoc: Error running filter /opt/quarto/share/filters/crossref/crossref.lua:
/opt/quarto/share/filters/crossref/crossref.lua:5310: attempt to index a nil value (field '?')
stack traceback:
        /opt/quarto/share/filters/crossref/crossref.lua:5030: in function </opt/quarto/share/filters/crossref/crossref.lua:4981>
        [C]: in ?
        [C]: in method 'walk'
        /opt/quarto/share/filters/crossref/crossref.lua:148: in local 'checked_walk'
        /opt/quarto/share/filters/crossref/crossref.lua:200: in function 'run_emulated_filter'
        /opt/quarto/share/filters/crossref/crossref.lua:725: in local 'callback'
        /opt/quarto/share/filters/crossref/crossref.lua:738: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/crossref/crossref.lua:773: in function </opt/quarto/share/filters/crossref/crossref.lua:770>
stack traceback:
        /opt/quarto/share/filters/crossref/crossref.lua:148: in local 'checked_walk'
        /opt/quarto/share/filters/crossref/crossref.lua:200: in function 'run_emulated_filter'
        /opt/quarto/share/filters/crossref/crossref.lua:725: in local 'callback'
        /opt/quarto/share/filters/crossref/crossref.lua:738: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/crossref/crossref.lua:773: in function </opt/quarto/share/filters/crossref/crossref.lua:770>
```

**Comment by robjhyndman** [comment]
Could it be a pandoc error? My pandoc version is 3.1.8

**Comment by robjhyndman** [comment]
I've just updated to quarto v1.4.398 and the problem has disappeared.
