### ISSUE TITLE
`quarto preview` displays listing page instead of edited page when hot reloading

### ISSUE THREAD

**Issue by mfisher87** [quarto-dev/quarto-cli#6026]
### Bug description

Repro repo: https://github.com/mfisher87/sscce-quarto-preview-hot-reload-listing

Either use this repo to test, or find details below.

When editing a page that is part of listing, `quarto preview` will hot reload.

In Quarto `1.3.361` and prior, the edited page was correctly displayed after the hot reload.

In Quarto `1.3.427`, the listing page is displayed instead.

### Steps to reproduce

* `quarto create-project --type website`
* `mkdir listing`
* Create `listing/index.md` with barebones `listing` front-matter.
* Edit `_quarto.yml` to add a link to `listing/index.md`.
* Create `listing/foo.md` with barebones content.

Try the following steps with different versions of Quarto

* `quarto preview`
* Edit `listing/foo.md`, and write.
* The browser will refresh automatically. Is the test post displayed, or is the listing
  page displayed?
    * In Quarto `1.3.427`, the latter is the case, which is unintuitive to me. In
      previous versions, the former is the case. I expect the page I edited to be
      displayed!

### Expected behavior

When editing a page, triggering a hot reload by `quarto preview`, I expect to see the page I edited.

### Actual behavior

If the edited page is part of a listing, the listing index is displayed instead of the edited page in Quarto 1.3.427.

### Your environment

Ubuntu 22
Quarto 1.3.427

### Quarto check output

```bash
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.58.3: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.427
      Path: /home/robatt/.local/share/miniconda3/envs/itsarobin-homepage/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /home/robatt/.local/share/miniconda3/envs/itsarobin-homepage/bin/python
      Jupyter: 5.3.1
      Kernels: python3

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by dragonstyle** [comment]
Potentially introduced here:
2f9f2319ef810bd4a7079c4892d8fd56d9d154c2

**Comment by dragonstyle** [comment]
I've made the fix to the 1.4 (main) branch and will back port to 1.3 branch for our next patch release, which is likely a couple weeks away. Thx for reporting this was an unexpected side effect and a great thing to fix.

**Comment by mfisher87** [comment]
Wonderful, thanks :heart: 

If you drop me a ping/mention when the 1.3 backport is available, I'll get it [released to `conda-forge`](https://github.com/conda-forge/quarto-feedstock) ASAP :)

**Comment by mfisher87** [comment]
Hey @dragonstyle is a backport release still planned? Thanks :)

**Comment by dragonstyle** [comment]
Apologies for the delay! Yes it should be coming this afternoon (within the next couple of hours). I'll update here when it is completed.

**Comment by mfisher87** [comment]
>Apologies for the delay! 

No sweat, I understand you're busy! Thanks very much, Charles :) I've got it on my list later tonight to open a PR on the conda-forge feedstock.
