### ISSUE TITLE
observablehq plot version embedded in quarto

### ISSUE THREAD

**Issue by linogaliana** [quarto-dev/quarto-cli#6031]
I have noticed that the `Plot` version is a little bit late with [latest observablehq plot version](https://github.com/observablehq/plot/blob/main/CHANGELOG.md#068) 

https://github.com/quarto-dev/quarto-cli/blob/121d710f7c02f00de0c6f4fa06db83587d751b3a/src/resources/formats/html/ojs/quarto-ojs-runtime.js#L208

0.6.6 and 0.6.7 bring some new nice features like tooltips that would be great for quarto users. 

Latest Plot version is `0.6.8`. Would you consider updating the version embedded with quarto by default ?

**Comment by cscheid** [comment]
Our policy is to update once per version. We've updated when we started work on 1.4, and will update again when we start work on 1.5.

**Comment by cscheid** [comment]
With that said, you can use a later version of Plot yourself by importing it explicitly from esm.sh

**Comment by linogaliana** [comment]
> With that said, you can use a later version of Plot yourself by importing it explicitly from esm.sh.

Yes that's what I am doing. I was not aware of your update policy
