### ISSUE TITLE
sass doesn't seem to work

### ISSUE THREAD

**Issue by Liripo** [quarto-dev/quarto-cli#6034]
### Bug description

I can't directly include sass in the chunk to modify my background color.

### Steps to reproduce

````qmd
---
format: 
  html
engine: knitr
---

```{sass}
$body-bg: black !default;
```
````

### Your environment
- quarto version:  1.4.80

**Comment by cscheid** [comment]
That's not how our scss system works. Please read the documentation for details: https://quarto.org/docs/output-formats/html-themes.html

**Comment by cderv** [comment]
Just to add to this to try explain the context here. 

**knitr** does support a `saas` engine (https://bookdown.org/yihui/rmarkdown-cookbook/eng-sass.html). It can be used to write your CSS for a document using SCSS or SASS in a chunk. **knitr** will use the **sass** R package to compile your chunk content to a CSS and include it in your document. **This is independant of any of tool themeing - R Markdown or Quarto**

From your usage, I believe you are coming from the R ecosystem. In R ecosystem, there is the **bslib** package. This package offers some Bootstrap improvment to R Markdown formats, and also offer a  `bslib` engine, that allows to tweak some Bootstrap themeing from a chunk. Doc is here: https://rstudio.github.io/bslib/articles/theming.html#add-rules
**This is only working for R in the context of a R Markdown document**

For Quarto, this is all different. There is no engine to modify the Quarto theme to mix some variables with the overall theme of the HTML document. You need to follow the link shared above to understand how that works. 

Only way to have a chunk create the style would be to leverage [**knitr** `cat` engine](https://bookdown.org/yihui/rmarkdown-cookbook/eng-cat.html) that knows how to write chunk content to file. The chunk would be the same content as an external Quarto theme file. 

<details>
<summary>Example </summary>

````markdown
---
format: 
  html:
    theme: style.scss
engine: knitr
---

```{cat}
#| engine.opts:
#|   file: style.scss
/*-- scss:defaults --*/
$body-bg: black !default;
$body-color: lightgrey !default;

/*-- scss:rules --*/
h1 {
  color: red;
  font-weight: 100
}
```

# Title

Content
````

</details>


Hope it helps. If you tried the syntax described in your issue for another reason, I would be curious to know the context.

**Comment by Liripo** [comment]
Thanks for the explanation, it was very helpful to me

**Comment by cderv** [comment]
> The reason is I just want to change the primary color scheme of bootstrap, so I may not want to use an extra file.

There is a small set of Basic option that you can set in YAML header: https://quarto.org/docs/output-formats/html-themes.html#basic-options

Otherwise, you just need an extra file with only the variables set. This is a very simple file.
