### ISSUE TITLE
Link to rsvg-convert for Windows is broken in docs

### ISSUE THREAD

**Issue by liyongg** [quarto-dev/quarto-cli#6048]
### Bug description

The link referring to the rsvg-convert package https://quarto.org/docs/prerelease/1.3/pdf.html#svg-images does not resolve to the correct page.

### Steps to reproduce

Go to: https://quarto.org/docs/prerelease/1.3/pdf.html#svg-images

Click on the link for Windows: https://community.chocolatey.org/packages/r%E2%80%A6

### Expected behavior

URL should link to the correct page. I believe that should be: https://community.chocolatey.org/packages/rsvg-convert

### Actual behavior

URL renders the default 'page not found' page.

**Comment by liyongg** [comment]
@cscheid  Ah, I did not know. Sorry, still trying to find my way around. Will keep in mind to check more thoroughly in other repo next time. Thanks for tackling it!

**Comment by cscheid** [comment]
@liyongg I was wrong! @mcanouil pointed out to me that we closed that repo, and website reports actually belong here. Sorry about that.
