### ISSUE TITLE
Incorrect R user library path

### ISSUE THREAD

**Issue by mattpollock** [quarto-dev/quarto-cli#6058]
### Bug description

When running `quarto check` I see the following:

```bash
[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/local/lib/R/library
        - /home/mpollock/R/x86_64-pc-linux-gnu-library/4.0
      knitr: 1.43
      rmarkdown: 2.22
```

It knows that I'm running R version 4.3.0, and there exists a `/home/mpollock/R/x86_64-pc-linux-gnu-library/4.3` that RStudio will pick up and use by default. Why does quarto want to use the older 4.0 user library?

Within RStudio my default library paths are
```r
.libPaths()
#> [1] "/home/mpollock/R/x86_64-pc-linux-gnu-library/4.3"
#> [2] "/usr/local/lib/R/site-library"                         
#> [3] "/usr/local/lib/R/library"
```

A secondary question is about library path ordering. RStudio will defer to the user library, while quarto appears to prioritize the system library. I can split this into a separate issue if that's useful.

### Steps to reproduce

Install multiple versions of R, install packages to the user library path for both. Then run `quarto check`

### Expected behavior

Quarto uses the user library path consistent with the R version being used.

### Actual behavior

It is using an old user library path. If the old library path is deleted is used no user library path at all.

### Your environment

- IDE: RStudio 2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-06) for Ubuntu Jammy
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15

- Running via jupyter using and extension of the [rocker/binder:4.3.0](https://rocker-project.org/images/versioned/binder.html) image

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.353
      Path: /usr/lib/rstudio-server/bin/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: ir, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/local/lib/R/library
        - /home/mpollock/R/x86_64-pc-linux-gnu-library/4.0
      knitr: 1.43
      rmarkdown: 2.22
```

**Comment by mcanouil** [comment]
Run `Rscript -e '.libPaths()'` in a terminal outside of RStudio, the result should be the same as Quarto.

**Comment by mattpollock** [comment]
Thanks. So I think that the underlying issue is that the `R_LIBS_USER` environment variable (which `Rscript` uses) is incorrectly set in my environment. And the way to configure `quarto` is via that env.

**Comment by mcanouil** [comment]
To note RStudio fiddle with the library paths, hence the difference of behaviour.
Since Quarto run its own R session independently of RStudio, it does not get the modified library paths.

**Comment by nicogeorg** [comment]
I had an issue related to your second question. That the order of library paths in quarto is different to the one working in Rstudio, caused a problem for me. I could not update any libraries because while rendering a quarto document, packages installed in the site library would always have precedence over packages installed in the user library. This creates problems, especially, if I need an updated version of a dependency of an explicitly called package.

I use R 4.4.1, ubuntu 22.04 and rstudio-server-2024.04.2+764.

The solution was to add following line to .Rprofile (user) or Rprofile.site (admin):
`.libPaths <- .libPaths(Sys.getenv("R_LIBS_USER"))`
