### ISSUE TITLE
pagebreak seems not work for docx

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#6065]
### Bug description

When I render a qmd file that has inside a [pagebreak](https://quarto.org/docs/authoring/markdown-basics.html#page-breaks), and I render it to docx, I'm not able to open the output and I have this error

![image](https://github.com/quarto-dev/quarto-cli/assets/30607/f3b0d13d-4aaa-49b5-bda4-6902b7b93b5f)

### Steps to reproduce

I have tested using this input and running `quarto render test.qmd --to docx  -o test.docx`.

My OS is Debian 11 and I'm using quarto 1.4.43.

````qmd
---
title: "Title"
format:
  docx:
    toc: false
    number-sections: false
    highlight-style: github
---

# A title

Lorem ipsum

{{< pagebreak >}}

# Another title

Lorem ipsum
````

### Expected behavior

To be able to open a paginated docx.

### Actual behavior

Opening the output in office fow win I have this error

![image](https://github.com/quarto-dev/quarto-cli/assets/30607/5d1e9db2-7851-4278-b42f-d3e7c614e496)

### Your environment

My OS is Debian 11 and I'm using quarto 1.4.43.

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.1: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.43
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: /usr/bin/python3
      Jupyter: 5.1.2
      Kernels: bash, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.0.4
      Path: /usr/lib/R
      LibPaths:
        - /home/aborruso/R/x86_64-pc-linux-gnu-library/4.0
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.41
      rmarkdown: 2.19

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Hm. I don't have access to word right now, but according to [this validator](https://github.com/devoidfury/docx-validator), this generated document is good.

**Comment by cderv** [comment]
I can confirm this works well on Windows with Word. 

The document is correctly generated and includes the pagebreak
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/f9db0754-0119-46b1-9713-8589075a986d)

Same if I render from Ubuntu 20

This is with the latest Quarto version

**Comment by mcanouil** [comment]
This also works well on macOS Ventura.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/3536d9f1-080d-44dd-95ce-068ad6eb4685">

**Comment by aborruso** [comment]
Thank you very much to all.

[This](https://github.com/quarto-dev/quarto-cli/files/11908092/test.zip) is my output.

Could you evaluate, if you are able to open it?

If yes, I must update my quarto version

**Comment by mcanouil** [comment]
Your Word document might be corrupted as per the message from Word itself.
I suggest you:
- update your Quarto pre-release version as pre-release are not stable by definition, thus you have to keep it up to date (current is [v1.4.176](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.176)).
- close Word
- delete the Word document
- restart your terminal/IDE
- render again

**Comment by aborruso** [comment]
@mcanouil as usual you are kind and accurate. What's the quarto version did you have use for your test?

So I line up.

Thank you

**Comment by mcanouil** [comment]
> This also works well on macOS Ventura using latest stable and development version of Quarto. 

@aborruso both above mentioned versions on macOS worked properly.

**Comment by aborruso** [comment]
Using v1.4.176 it works great!

Thank you

**Comment by mcanouil** [comment]
Glad to hear it's resolved!
