### ISSUE TITLE
Improper spacing of QED symbol in PDF output

### ISSUE THREAD

**Issue by sun123zxy** [quarto-dev/quarto-cli#6077]
### Bug description

A reminder for a left-behind problem mentioned in #3776. 

### Steps to reproduce

````qmd
---
title: "QED symbol test"
format:
    pdf:
        keep-tex: true
---

:::{.proof}
This is a proof.
:::
````

### Expected behavior

Should produce LaTeX code like this:
```latex
\begin{proof}
This is a proof.
\end{proof}
```
which handle the spacing of QED symbol properly.

### Actual behavior

However, Quarto actually produces this
```latex
\begin{proof}

This is a proof.

\end{proof}
```
The empty line inserted before `\end{proof}` causes the QED symbol lies in a new line, instead of the end of the last line of the proof.

[Probably helpful](https://tex.stackexchange.com/questions/51781/qed-symbol-on-the-same-page-as-proof)

### Your environment

- IDE: vscode
- OS: Windows 11

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.340
      Path: C:\Program Files\Quarto\bin
      CodePage: 936

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment]
(note to self: I think the problem here comes from pandoc latex RawBlocks forcing line spaces around them. We have a design for a filter-based partial solution in a branch, but this argues for a more comprehensive fix.)
