### ISSUE TITLE
tbl-colwidths ignored when table is created by kable, as is full_width = FALSE

### ISSUE THREAD

**Issue by bryanhanson** [quarto-dev/quarto-cli#6089]
### Bug description

*Originally raised [here](https://github.com/quarto-dev/quarto-cli/issues/6015#issuecomment-1616288334) and possibly related but it was suggested to open a new issue.  That problem was related to pandoc's handling of docx files and was fixed by pandoc for that format.  This maybe a similar problem, IDK.*

I was trying to control the overall table width of a kable-generated html table in a website project.  I tried to specify `tbl-colwidths` in the chunk but this was ignored.  Then I tried the `kable_styling(full_width = FALSE)` which normally does a good job of adjusting overall width and individual column width, but this was also ignored.

It appears the settings are ignored or perhaps overridden.  At least in the case of `tbl-colwidths` I can see the information passed to the html in the page source but it looks like it is echoed there and not really used (my best guess).

## _quarto.yml
```
project:
  title: "test"
  type: "website"
```

## test.qmd
````
---
title: "Two Ways to Handle Table Width Using kable; Neither Works"
---

@tbl-results1 shows how to control the table column widths; however, the settings seem to be ignored.  At the same time, another way to control this with `kable` doesn't work either, see @tbl-results2.

```{r}
#| echo: false
library("kableExtra")
library("magrittr")
```

```{r}
#| label: tbl-results1
#| tbl-cap: "mtcars using colwidths doesn't work."
#| tbl-colwidths: [15, 15, 15, 15]
kable(mtcars[,1:3]) %>%
  kable_styling(c("striped", "bordered"))
```

```{r}
#| label: tbl-results2
#| tbl-cap: "mtcars with full_width = FALSE doesn't work."
kable(mtcars[,1:3]) %>%
  kable_styling(c("striped", "bordered"), full_width = FALSE)
```

````

### Expected behavior

I want the table column widths to shrink to contain the contents w/o a lot of white space, and in turn, this will make the table overall narrower.

### Actual behavior

Right now the table occupies the full width with a lot of white space.

### Your environment

-IDE: command line
-OS: MacOS 12.6.7

### Quarto check output

```bash

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/bryanhanson/Documents/Professional/Research/R_Pkgs/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK

```

**Comment by cderv** [comment]
> I tried to specify tbl-colwidths in the chunk but this was ignored. 

It seems there is indeed a problem with that. Simpler example with only `kable()` producing a Markdown table. 

````markdown
---
title: "tbl-colwidths"
keep-md: true
---

```{r}
#| label: tbl-results1
#| tbl-cap: "mtcars using colwidths doesn't work."
#| tbl-colwidths: [25, 25, 25, 25]
knitr::kable(mtcars[,1:3])
```
````

It is working with latest 1.3 so it seems to be a regression in current dev version  (@bryanhanson you can use latest 1.3 for now instead of dev version - though thanks a lot for testing dev version, that is really helpful !! )

As it was a regression I did a quick `git bisect` and it ends up that commit c5b6176d824aae87667f7925132e6638320f135e from #5245 introduced the regression. 

It seems we are not handling `tbl-colwidths` chunk option the same following the big Lua rewrite for performance. FYI  @cscheid as you did the work on that. 

I'll try to find the specific regression inside this big change.

**Comment by cderv** [comment]
> Then I tried the kable_styling(full_width = FALSE) which normally does a good job of adjusting overall width and individual column width, but this was also ignored.

@bryanhanson regarding this, it has to do with Quarto special table processing. Some of `kableExtra` specific feature won't work correctly as Quarto will parse the HTML table, and do its processing for layout and style. 

If you want to keep the **kableExtra** special behavior, you need to deactivate quarto processing. This is mentioned in doc at 
https://quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing : `data-quarto-disable-processing="true"` needs to be set on the tables. 

We don't say exactly why for all ways to do tables, but one can look how to do for specific tool. For example, with `knitr::kable()` passing attributes is an argument (or even an option). See https://bookdown.org/yihui/rmarkdown-cookbook/kable.html#customize-html-tables

````markdown
---
title: "Disabling processing"
---

```{r}
library(kableExtra)
```

```{r}
#| label: tbl-results2
#| tbl-cap: "mtcars with full_width = FALSE doesn't work."
kable(mtcars[,1:3], table.attr = "quarto-disable-processing=true") |>
  kable_styling(c("striped", "bordered"), full_width = FALSE)
```
````

This will target a specific chunk, so specific table. To set for all tables on a document, the attributes can also be set using `knitr.table.html.attr` options.
````markdown
---
title: "Disabling processing"
---

```{r}
library(kableExtra)
options(knitr.table.html.attr = "quarto-disable-processing=true")
```

```{r}
#| label: tbl-results2
#| tbl-cap: "mtcars with full_width = FALSE doesn't work."
kable(mtcars[,1:3]) |>
  kable_styling(c("striped", "bordered"), full_width = FALSE)
```
````

Also possible to set using [special knitr options through YAML header](https://quarto.org/docs/computations/r.html#knitr-options)
````markdown
---
title: "Disabling processing"
knitr: 
  opts_chunk: 
    R.options: 
      knitr.table.html.attr: "quarto-disable-processing=true"
---

```{r}
library(kableExtra)
```

```{r}
#| label: tbl-results2
#| tbl-cap: "mtcars with full_width = FALSE doesn't work."
kable(mtcars[,1:3]) |>
  kable_styling(c("striped", "bordered"), full_width = FALSE)
```
````

Hope it helps

I'll add an example in documentation somewhere.

**Comment by mcanouil** [comment]
🤯 I did not know, it was possible to target specific content and add attributes only to those.

```yaml
knitr: 
  opts_chunk: 
    R.options: 
      knitr.table.html.attr: "quarto-disable-processing=true"
```

**Comment by aborruso** [comment]
> 🤯 I did not know, it was possible to target specific content and add attributes only to those.

@cderv  Can I test something similar for generic markdown table? If yes, how to?

**Comment by cderv** [comment]
> Can I test something similar for generic markdown table? If yes, how to?

It would be better to discuss anything specific in a new Github discussion as this issue related really to the Lua problem (fix in the way FWIW). You can then provide more details on your question. This would be helpful as I am not sure to follow the question. Why deactivate the Quarto processing on Markdown tables ? 

Anyhow, attributes can be set on Markdown tables the same way as you set `tbl-colwidths` or bootstrap class as shown in doc ://quarto.org/docs/authoring/tables.html

So you should be able to add the attributes on the table this way.

**Comment by cderv** [comment]
> I'll add an example in documentation somewhere.

I have published an example on this https://examples.quarto.pub/opt-out-table-processing-kable/

**Comment by bryanhanson** [comment]
@cderv and @mcanouil you are the best, thanks for the fix and the good explanations!

**Comment by ulyngs** [comment]
@cderv is there a way to opt out of the table processing for LaTeX output?

**Comment by mcanouil** [comment]
@ulyngs I don't believe there is any processing of the table for LaTeX. By processing here we mean styling.

**Comment by mcanouil** [comment]
You have to understand what `kable` w/o `kableExtra` outputs.
`kable` output by default a `pipe` markdown table.
If you set the format argument to LaTeX you'll see that colwidths no longer works.
`kableExtra` can't work with `pipe` table as stated in the documentation. The format needs to be either `html` or `latex`.

````qmd
---
format: pdf
---

```{r}
#| label: tbl-results1
#| tbl-cap: "mtcars using colwidths doesn't work."
#| tbl-colwidths: [10, 30, 30, 30]
knitr::kable(mtcars[1:2,1:3], format = "latex")
```

```{r}
#| label: tbl-results2
#| tbl-cap: "mtcars using colwidths doesn't work."
#| tbl-colwidths: [10, 30, 30, 30]
knitr::kable(mtcars[1:2,1:3], format = "pipe")
```

```{r}
#| label: tbl-results3
#| tbl-cap: "mtcars using colwidths doesn't work."
#| tbl-colwidths: [10, 30, 30, 30]
knitr::kable(mtcars[1:2,1:3])
```
````

Regarding `kableExtra` full width option, this changes the LaTeX environment from `tabular` to `tabu`. The two have different styling before even Quarto read them.
You can see that using  `keep-tex: true` or just using the function in an R terminal.
