### ISSUE TITLE
Should a badge be used as image in a post listing

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-cli#6091]
### Bug description

For a blog with a default post listing, if one of the posts has a badge as only image, the badge is used as image in the listing. 

I was surprised by this behavior but it might be intended?

![image](https://github.com/quarto-dev/quarto-cli/assets/8360597/03d1d52c-0364-4a4f-b896-5d00b5a5b95a)

### Steps to reproduce

https://github.com/maelle/badgeblog/blob/fadf0dc478982e8fff2f8ec186432de951590875/posts/post-with-code/index.qmd#L8

### Expected behavior

I would expect no image to be used (except for a placeholder image if one was defined).

### Your environment

- RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 2.19.2: OK
      Dart Sass version 1.32.8: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.49
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /opt/R/4.2.0/lib/R
      LibPaths:
        - /home/maelle/R/x86_64-pc-linux-gnu-library/4.2
        - /opt/R/4.2.0/lib/R/library
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Quarto will try to guess what's the feature image, if none are explicitly provided in the YAML front matter, then it uses the first image it sees.
Because a badge is an image, if that's the first thing found, it is used.

@dragonstyle can elaborate more on this.
A possible improvements would be to not use "small size" images unless explicitly told to do so.

**Comment by dragonstyle** [comment]
Thanks for reporting this. I further narrowed our auto discovery such that it will not use remote images unless they are explicitly specified in the document front matter. We can keep narrowing it further - let's see how this works.

@mcanouil - great suggestion re: size, though in the remote case like this we don't really have our hands on the image to compute its size without actually fetching it (which I'd like to avoid). If we start getting issues related to selecting small local images, this would be a good thing to try next for the local case...

**Comment by maelle** [comment]
Thanks both :pray: :rocket:
