### ISSUE TITLE
Add 'do-not-track' / 'dnt' option for the 'cookie-consent' config

### ISSUE THREAD

**Issue by Bisaloo** [quarto-dev/quarto-cli#610]
In https://quarto.org/docs/reference/projects/websites.html#meta-project-type-upper, we learn that cookies can be allowed or blocked by default.

It would be amazing if we could get the visitors' preferences by following the 'Do Not Track' browser setting. If 'Do Not Track' is set, then cookies are blocked. If not, cookies are enabled.

**Comment by jjallaire** [comment]
@dragonstyle Can we indeed sniff the do not track preference from the user agent?

**Comment by dragonstyle** [comment]
That would be pretty cool. The Do Not Track setting that I'm familiar with has been deprecated ( https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack ) and they don't recommend using it. If there is an alternative way to detect it that you know of, I would be interested in checking it out and seeing whether I could make that work.

**Comment by Bisaloo** [comment]
Oh no, I missed the news that it's now deprecated :disappointed: 

I'm not sure if there is a way to do this then :thinking:
