### ISSUE TITLE
Python plots with knitr engine not showing

### ISSUE THREAD

**Issue by sebastian-gerdes** [quarto-dev/quarto-cli#6101]
### Bug description

Python plots from python chunk are not shown in a quarto-document with knitr engine. However, with the jupytr engine it works.

### Steps to reproduce

`````qmd
---
title: 'Plots not showing'
format: html
# engine: jupytr
engine: knitr

---

```{python}
import statsmodels.api as sm
import pandas
df = sm.datasets.get_rdataset("Guerry", "HistData").data

fm = sm.formula.ols('Lottery ~ Literacy + Wealth + C(Region)', data = df).fit()
print(fm.summary())

fig = sm.graphics.influence_plot(fm, criterion="cooks")
fig.show()
```


### Expected behavior

The plot should be included in the rendered html file

### Actual behavior

The plot is not shown

### Your environment

- IDE RStudio: Version 2023.06.0+421 (2023.06.0+421)
- MacOS 12.6.2

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10 (Conda)
      Path: /Users/seb/Library/r-miniconda-arm64/bin/python
      Jupyter: 5.3.0
      Kernels: julia-1.8, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
You forgot to close your example.

The following works fine:

````qmd
---
title: 'Plots not showing'
format: html
engine: knitr
---

```{python}
import statsmodels.api as sm
import pandas
df = sm.datasets.get_rdataset("Guerry", "HistData").data

fm = sm.formula.ols('Lottery ~ Literacy + Wealth + C(Region)', data = df).fit()
# print(fm.summary())

sm.graphics.influence_plot(fm, criterion="cooks")
```
````

It's likely to be an issue with `reticulate`, as such I suggest to go on<https://github.com/rstudio/reticulate/>.

**Comment by cderv** [comment]
Is the initial python working in Jupyter or another environment ? 

From documentation at https://www.statsmodels.org/dev/generated/statsmodels.graphics.regressionplots.influence_plot.html
I understand you may need `matplotlib` to output the plot. 

Try 

````markdown
---
title: 'Plots not showing'
format: html
engine: knitr
---

```{python}
import statsmodels.api as sm
import matplotlib.pyplot as plt
import pandas
df = sm.datasets.get_rdataset("Guerry", "HistData").data

fm = sm.formula.ols('Lottery ~ Literacy + Wealth + C(Region)', data = df).fit()
print(fm.summary())

fig = sm.graphics.influence_plot(fm, criterion="cooks")
plt.show()
```
````

This is like the above but with explicit call I think

**Comment by sebastian-gerdes** [comment]
Thanks for your answers! Both seem to help, even though I don't entirely understand why, but I will continue trying to understand :-)

**Comment by mcanouil** [comment]
The "issue" is mostly Python and module implementation.
As highlighted the function actually outputs the figure without the need to explicitly ask for this, which means it either require to use the internal module "matplotlib" to display the plot "on command" or use the implicit display of the function you are using.
`reticulate` tries to be smart thus leading to some inconsistencies when using R to call the code compared to when Jupyter calls directly the code.

**Comment by xiaoxl** [comment]
I meet the same issue. Quarto 1.4.530.
When I use knitr + reticulate to show python plots, the plot will be generated in local folders but won't be moved to the output folder. 
I tried "plt.show()" but it doesn't work either.

**Comment by mcanouil** [comment]
Please open a new discussion or issue with a small reproducible example.
Also, please upgrade to latest stable version (Quarto 1.4.549), including `knitr` and `reticulate`.
