### ISSUE TITLE
Any way to create api docs like sphinx or mkdocs?

### ISSUE THREAD

**Issue by amichuda** [quarto-dev/quarto-cli#611]
Is there any way that quarto can take docstrings from python files and create docs with those docstrings such as in Sphinx or mkdocs?

**Comment by jjallaire** [comment]
There isn't currently a feature that does this, but so long as you can generate clean markdown from the docstrings there is no reason you couldn't include that markdown as pages in a quarto website. You could use a pre-render or periodically run script to do the markdown generation: https://quarto.org/docs/projects/quarto-projects.html#project-scripts

**Comment by mcanouil** [comment]
Closing as completed with the use of <https://pypi.org/project/quartodoc/>:

- #2111

**Comment by ecomodeller** [comment]
> Closing as completed with the use of https://pypi.org/project/quartodoc/:
> 
> * [Extension to autogenerate API reference docs for Python #2111](https://github.com/quarto-dev/quarto-cli/discussions/2111)

`quartodoc` is done by @machow, will this eventually be transferred to @quarto-dev org, or how should this be interpreted?

**Comment by cscheid** [comment]
> how should this be interpreted?

@ecomodeller the author of `quartodoc` works at Posit. Not all quarto tools live on `quarto-dev`, though it might make sense to do it at some point. We've discussed it but we have other priorities right now - I wouldn't read too much into it.
