### ISSUE TITLE
Quarto not recognizing python packages

### ISSUE THREAD

**Issue by joaoaugustofrei** [quarto-dev/quarto-cli#6113]
### Bug description

I am running Quarto to produce a report in which I mix python with R (using 95% R). When I started trying to use python, I believe that RStudio is not recognizing my python installation and packages:

```
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ModuleNotFoundError: No module named 'pandas'
```

Any ideas?

### Steps to reproduce

```qmd
---
title: 'Nota Técnica - Índice Socioeconômico dos Estudantes'
author: ''
format: 
  html:
    encoding: 'UTF-8'
    theme: style.css
editor: visual
lang: pt
execute:
  echo: false
  warning: false
---

```{python}
#| label: load-py-pckgs
import pandas as pd
import seaborn as sns
```
```
### Expected behavior

I expected it to load python packages and modules with no problems.

### Actual behavior

Error when loading any python package.

### Your environment

IDE: RStudio 2022.07.2 Build 576
R version 4.1.0 (2021-05-18) (can't update because of internal packages built with this version)
OS: Windows 11

### Quarto check output

`quarto check` gives me:
C:\Users\joao.freire\Documents>quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.433
      Path: C:\Users\joao.freire\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Program Files/Python311/python.exe
      Jupyter: 5.3.1
      Kernels: python3

(/) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this
validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this
validation.
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.1.0
      Path: C:/Users/joao.freire/Documents/R/R-4.1.0
      LibPaths:
        - C:/Users/joao.freire/Documents/R/R-4.1.0/library
      knitr: 1.42
      rmarkdown: 2.23

[>] Checking Knitr engine render......OK


C:\Users\joao.freire\Documents>quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.433
      Path: C:\Users\joao.freire\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Program Files/Python311/python.exe
      Jupyter: 5.3.1
      Kernels: python3

```
(\) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this
validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this
validation.
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.1.0
      Path: C:/Users/joao.freire/Documents/R/R-4.1.0
      LibPaths:
        - C:/Users/joao.freire/Documents/R/R-4.1.0/library
      knitr: 1.42
      rmarkdown: 2.23

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Your installation seem fine but you need to install the module mentioned in the error.
Basically, you need to install Python modules you are going to use before trying to use it.
See <https://quarto.org/docs/computations/python.html> and Python pip documentation.

**Comment by joaoaugustofrei** [comment]
The packages are already installed. When I try installing again on RStudio terminal I get this warning:

```
WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\joao.freire\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed contourpy-1.1.0 cycler-0.11.0 fonttools-4.40.0 kiwisolver-1.4.4 matplotlib-3.7.2 pillow-10.0.0 pyparsing-3.0.9 seaborn-0.12.2
```

**Comment by joaoaugustofrei** [comment]
And this for Pandas:

`WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\joao.freire\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed contourpy-1.1.0 cycler-0.11.0 fonttools-4.40.0 kiwisolver-1.4.4 matplotlib-3.7.2 pillow-10.0.0 pyparsing-3.0.9 seaborn-0.12.2`

**Comment by cderv** [comment]
>  I mix python with R

I understand from this you are using Python chunk inside a R document, meaning **knitr** is ran, and **reticulate** R package will run the python code. Is that right ? 

If you are not, then @mcanouil comment https://github.com/quarto-dev/quarto-cli/issues/6113#issuecomment-1622526840 does apply (for python computaton with Jupyter). 

Otherwise, you need to check the packages inside the environment used by **reticulate**.  I read you check in R terminal, but is this within the python environment that will be used by reticulate ? 

Usually install package using **reticulate** directly (and not the terminal), will help be sure it is in the right place for **reticulate** to work. See https://rstudio.github.io/reticulate/articles/python_packages.html

**reticulate** as a doc on Python version configuration: https://rstudio.github.io/reticulate/articles/versions.html
Setting `RETICULATE_PYTHON` to your main system python you are using could be a solution to force **reticulate** to use this version. 

Anyhow, I believe these config needs to be check. There could be some side effect behavior depending how you may have configured reticulate in the past to work with R and R Markdown.

**Comment by joaoaugustofrei** [comment]
Installing the python packages with reticulate worked! Thank you so much!
