### ISSUE TITLE
revealjs pdf export splits pages unexpectedly

### ISSUE THREAD

**Issue by ig0101** [quarto-dev/quarto-cli#6120]
### Bug description

When the "pdf-max-pages-per-slide: 1" option is used, printing to pdf in chrome (Save as PDF, all pages, 1 page per sheet, margins=None) results in unexpected page splits.

In the qmd below the "long slide" splits pages after the title, and the "short slide" has a blank page printed after it. The pdf output is also attached.

I would expect that setting the "pdf-max-pages-per-slide: 1" option would lead to a 2-page pdf.

Pdf output:
[pdf-split-page-test.pdf](https://github.com/quarto-dev/quarto-cli/files/11966316/pdf-split-page-test.pdf)

### Steps to reproduce

````qmd
---
format: 
  revealjs:
    pdf-max-pages-per-slide: 1
incremental: false
editor: source
---

## a long slide
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20

## a short slide
- 1
- 2
- 3
- 4
- 5
````

### Expected behavior

I would expect that setting the "pdf-max-pages-per-slide: 1" option would lead to a 2-page pdf.

### Actual behavior

The "long slide" splits pages after the title, and the "short slide" has a blank page printed after it.

### Your environment

- IDE: RStudio 2023.06.0 Build 421
- Windows: Windows 10 Pro 22H2 Build 19045.3086

**Comment by cderv** [comment]
We are currently not passing the option [pdfMaxPagesPerSlide](https://revealjs.com/pdf-export/#page-size) to reveal even when set in the YAML.

I'll fix this. 

However, even after that, the chrome print could be buggy. There is a generic issue to provide other methods than built in one in revealjs https://revealjs.com/pdf-export

* https://github.com/quarto-dev/quarto-cli/issues/4677

> the "short slide" has a blank page printed after it.

I believe this is a reveljs issue. It happens also in other case

Related to 

* https://github.com/quarto-dev/quarto-cli/issues/3997
* https://github.com/quarto-dev/quarto-cli/issues/5998

**Comment by cderv** [comment]
PR is now opened to correctly set the option 

Though, it seems **revealjs** still has an issue with the context 

With the config first slide is correctly cropped, but chrome printing will still get you some blank slide and unwanted page break

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/855d3f8c-1619-4ede-841f-e58f9ef199ba)

Without the config, the first slide is not cropped

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/97635666-79fb-4b37-9f07-607f2bed4f68)


How revealjs is doing the pagebreak is a revealjs issue. Maybe updating will fix this 🤔 
This will be done in 
* https://github.com/quarto-dev/quarto-cli/issues/4795

**Comment by ig0101** [comment]
Thank you! I will try out the fixed version.

**Comment by cderv** [comment]
Please do. It will be available in our next pre-release build later today or tomorrow. 

Though, you won't get the output you expect even with this fix. The configuration is passed, but then as I said this is a revealjs issue.

**Comment by ig0101** [comment]
Understood. Thanks again.

**Comment by jarbet** [comment]
@cderv: can you please clarify the solution for how to print Quarto HTML slides such that each slide fits on 1 page of the resulting PDF?

I often have a slide that is fairly long and is scrollable.  Is it still possible to print that entire slide on only 1 page, or will it always be split onto >= 2 pages in the PDF?

**Comment by cderv** [comment]
> I often have a slide that is fairly long and is scrollable.

If the slide content is wider or longer that a page, I don't think you'll be able to print it on a single page. This is a matter of page size and content size. 

Please to open a new discussion with an example so that we can discuss on your specific case. This is always better than commenting an old thread.
