### ISSUE TITLE
DENO_DIR ignored

### ISSUE THREAD

**Issue by jrowen** [quarto-dev/quarto-cli#6142]
I'm running `quarto_render` from within a docker container and setting `ENV DENO_DIR=/tmp`.  The environment variable is ignored and instead deno writes to the working directory.  Is there another way to specify the deno directory?

**Comment by cderv** [comment]
@dragonstyle does it looks like an error that should happen with our bundled version of quarto ?

**Comment by dragonstyle** [comment]
I wouldn't expect Quarto to be needed to compile or cache anything - we explicitly prohibit downloading package and should be used cache packages only.

Do you know what Deno is trying to write? I wouldn't expect it to be needing to do that...
