### ISSUE TITLE
quarto check on command line cannot find R installation if `.Rprofile` is present

### ISSUE THREAD

**Issue by bryanhanson** [quarto-dev/quarto-cli#6154]
### Bug description

I noticed that if I have an `.Rprofile` present in my R environment that on the command line

```
quarto check
```

fails to find the R installation.  If I remove `.Rprofile` `quarto check` does find the R installation.

Update: I should have noted that Quarto documents with R code chunks work just fine regardless of what `quarto check` reports, so the problem is with the `check` code itself.

### Steps to reproduce

Put a `.Rprofile` file in `/Users/your_user_name` on a Mac

### Expected behavior

`quarto check` should find the R installation.

### Actual behavior

`quarto check` cannot find the R installation if a `.Rprofile` is present; see the Quarto check output below.

### Your environment

Using the command line with macOS 13.4.1 on an M2 chip.

### Quarto check output

This shows the "error" condition, seen when `.Rprofile` is present.

```bash
~> quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

(|) Checking R installation...........✔ All clear for ChemoSpec2D, exCon, FuncMap, HiveR, LearnPCA, LindenmayeR, readJDX, roxut, SpecHelpers!
✖  Package with errors on CRAN: 
  - ChemoSpec (2)
★  Package with notes on CRAN: 
  - ChemoSpecUtils (1)
[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

```

**Comment by jimmyday12** [comment]
I am getting a similar error but on a Github Action where I render a Quarto website. I thought it was an error in the Github actions https://github.com/r-lib/actions/issues/741

**Comment by cderv** [comment]
A note that this does not reproduce on Windows. I have .Rprofile setup and all good. 

> ✔ All clear for ChemoSpec2D, exCon, FuncMap, HiveR, LearnPCA, LindenmayeR, readJDX, roxut, SpecHelpers!
> ✖  Package with errors on CRAN: 
>  - ChemoSpec (2)
> ★  Package with notes on CRAN: 
>  - ChemoSpecUtils (1)

@bryanhanson what is the content of you .Rprofile ? This comes from it right ? 

> I am getting a similar error but on a Github Action where I render a Quarto website. I thought it was an error in the Github actions https://github.com/r-lib/actions/issues/741

Are you having error with `quarto check` only and `quarto render` running as @bryanhanson described ? From your issue at `r-lib/actions` is seems like something else at the **renv** restore step where no Quarto is involved AFAIK

**Comment by bryanhanson** [comment]
Yes, the output you see is from my `.Rprofile` which contains the following:

```
cat("\n")
cat(">>>  Loading Bryan's .Rprofile\n")
cat("\n")

options(prompt = "R > ") # useful mostly for command line ops
options(repos = c(CRAN = "https://cloud.r-project.org"))
foghorn::summary_cran_results("hanson@depauw.edu")
cat("\n")
```

I suspect it is the `foghorn` call that causes the problem as that queries the package status pages for problems.  So there is a delay while this check is done.

**Comment by mcanouil** [comment]
You should not have things that change R behaviour in non interactive session in your `.Rprofile` for kind of obvious reasons.
I suggest you put your `.Rprofile` code inside an `if (interactive()) ...` statement.

**Comment by bryanhanson** [comment]
Fair enough, excellent idea.  I'll make the change.  I'll let you close because I don't know if you are thinking you should do things differently from your end.  Thanks!

**Comment by mcanouil** [comment]
As for RMarkdown, knitr or actually anything in R, it's not up to packages/softwares developers to tell the users what to do with their `.Rprofile` or `.Renviron`.
If a user set something, it means he/she knows what he/she is doing and the possible drawbacks that come with it.
Of course, the same applies to any programming languages you can use with knitr/jupyter. This is why Quarto can't predict what users might or might not have in their configurations, but ne it's also why we ask for fully reproducible examples in GitHub Issues/Discussions.

**Comment by cderv** [comment]
Just to clarify things here -  I do agree that .Rprofile is not ideal here - `interactive()` can be used for sure to help. However, I don't think we should error on `quarto check knitr` for this, especially as `quarto render` is working. 

The issue here is that we run a capabilities scripts which is supposed to writer JSON string for us to parse in `stdout`. But this fails here because of the various `cat()` used in the `.Rprofile`. I would say my first advice is to use `message()` and not `cat()` to write some status from your `.Rprofile` running. 

I think we can improve and make `quarto check` works. Calling **foghorn** should not be an issue for Quarto.

**Comment by cderv** [comment]
I have made a PR that makes `quarto check` works, even with your .Rprofile.

**Comment by cderv** [comment]
Thanks for the report @bryanhanson - this should now work without error even with your `.Rprofile`. 
Though, you should adapt it to follow previous advice probably.

**Comment by bryanhanson** [comment]
Roger that!Sent from an undisclosed location - check with the NSA.On Jul 11, 2023, at 6:44 AM, Christophe Dervieux ***@***.***> wrote:﻿
Thanks for the report @bryanhanson - this should now work without error even with your .Rprofile.
Though, you should adapt it to follow previous advice probably.

**Comment by bryanhanson** [comment]
For anyone visiting this topic, oddly, `if (interactive) {...}` is not recognized during the startup process (what I would call "interactive").  I'm using `message()` instead of `cat()` and it does not interfere.

**Comment by mcanouil** [comment]
Not `interactive` but `interactive()`.

**Comment by bryanhanson** [comment]
My apologies... I did have it as `interactive()` but after some experimentation I discovered that I was missing a final return after the closing `}` of the `if` statement which was preventing that statement from running.
