### ISSUE TITLE
Multicolumn figures doesn't work well with code-annotations with the hover-option

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#6157]
### Bug description

When doing a multicolumn figure with e.g. the `layout-ncol: 2` option, and code-annotations are enabled, the first figure is pushed down to make room for the code annotation text. This makes sense when `code-annotations: below` is used but not when `code-annotations: hover` is used. Seems like it makes room for the text below even though it never displays it there.

### Steps to reproduce

	---
	format: 
	  html:
	    code-annotations: hover
	---

	```{r}
	#| echo: true
	#| layout-ncol: 2
	#| fig-cap: "Caption."
	#| fig-subcap: 
	#|   - "Subcaption 1."
	#|   - "Subcaption 2."
	#| fig-align: center
	library(ggplot2)
	p1 <- ggplot() + # <1>
	  geom_point(data = mtcars, aes(x = wt, y = mpg))

	p1
	p1
	```

	1. Code annotation text.

### Expected behavior

The two figures should be aligned as there is no code annotation text below.

### Actual behavior

First figure is pushed down to make room for the code annotation text even though it's never displayed due to the `code-annotation: hover`-option.

### Quarto check output

    [>] Checking Quarto installation......OK
          Version: 1.4.193
          Path: C:\Users\au234616\AppData\Local\Programs\Quarto\bin
          CodePage: 1252
    
    [>] Checking basic markdown render....OK

**Comment by dragonstyle** [comment]
See also #7594
