### ISSUE TITLE
After 1.4.217 VSCode "Edit In Visual Mode" Fails with missing pandoc install

### ISSUE THREAD

**Issue by krishaamer** [quarto-dev/quarto-cli#6186]
### Bug description

`Request pandoc_list_extensions failed with message: Command failed: /Applications/quarto/bin/tools/pandoc --list-extensions markdown /Applications/quarto/bin/tools/pandoc: line 13: ./x86_64/pandoc: No such file or directory`

### Steps to reproduce

Click "Edit In Visual Mode" in VSCode using Quarto 1.4.217.

Tested [v1.4.205](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.205) and 13.433 and in both cases Visual Mode still worked.

### Expected behavior

VSCode should show the Visual Editor.

### Your environment

MacOS Ventura 13.4 (22F66)
Visual Studio Code Version: 1.80.0
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0
VSCode Quarto extension v1.89.0
Zotero 6.0.26
Docusaurus 2.4.0

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.5: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.217
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /Users/krishaamer/anaconda3/bin/python
      Jupyter: 5.2.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK

**Comment by dragonstyle** [comment]
Thanks for reporting this- I just made changes in this area that are the cause… will take a look first thing this morning.

**Comment by dragonstyle** [comment]
This is is fixed as of 1.4.219 - thanks again for catching it!
