### ISSUE TITLE
`include` shortcode doesn't work if child qmd contains `{{< embed ...>}}`

### ISSUE THREAD

**Issue by hamelsmu** [quarto-dev/quarto-cli#6194]
### Bug description

I have a file named [`gallery.qmd`](https://github.com/hamelsmu/include-embed-bug/blob/main/gallery.qmd) that looks like this:

```
---
---

::: {.content-block .grid .gap-4}


::: {.g-col-6 .g-col-md-4}
{{< embed PlotnineAnimation.ipynb#spiral >}}
:::


:::
```

This file renders properly as a page with the plot.  I then include this in [`index.qmd`](https://github.com/hamelsmu/include-embed-bug/blob/main/index.qmd) like so:

```
---
title: "Home"
---

This is a gallery

{{< include gallery.qmd >}}
```

The plots from `gallery.qmd` do not appear.  

I have a [minimal repro of this at this GitHub repo](https://github.com/hamelsmu/include-embed-bug/blob/main/index.qmd)

### Steps to reproduce

I have a [minimal repro of this at this GitHub repo](https://github.com/hamelsmu/include-embed-bug/blob/main/index.qmd)

### Expected behavior

I expect the plot from the included qmd to show up.

### Actual behavior

The plot doesn't show up from the included qmd

### Your environment

- IDE: VSCode
- MacOS Ventura 13.4.1 (22F82)

### Quarto check output

quarto check                                                (main)include-embed-bug

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: /opt/anaconda3/bin/python
      Jupyter: 5.1.0
      Kernels: python3, mojo-jupyter-kernel, javascript

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.0.4
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.0/Resources/library
      knitr: 1.31
      rmarkdown: 2.7

[✓] Checking Knitr engine render......OK

**Comment by hamelsmu** [comment]
cc: @dragonstyle @jjallaire I am trying to solve this in order to figure out a paved path for creating galleries for quartodoc (related issue: https://github.com/machow/plotnine-docs-demo/issues/3)

**Comment by dragonstyle** [comment]
I'll have a look on this tomorrow. One `embed` limitation that I'm aware of and should be able to fix this week has to with path resolution inside projects (embeds currently don't resolve paths that start with `/` against the project root, but they should).

**Comment by mcanouil** [comment]
FYI the mentioned issue about path resolution: <https://github.com/quarto-dev/quarto-cli/issues/6147>

**Comment by dragonstyle** [comment]
In my testing this is now fixed!
