### ISSUE TITLE
Problems with Block Code Formatting with "other" 

### ISSUE THREAD

**Issue by friosavila** [quarto-dev/quarto-cli#6197]
### Bug description

Hi, 
I encounter a problem when formating some codechunks when attempting to use in combination with -nbstata- a jupyter plug in to use Stata.

Basically, I'm trying to incorporate an executable code chunk on my quart page

` ``{stata}
sysuse auto, clear

reg price mpg
` ``

But since I want the code to come up with larger fontsizes i try adding some additional properties to the chunk:

` ``{stata}{style="font-size: 60px"}
sysuse auto, clear

reg price mpg
` ``

This increases the size of the text, but its no longer recognized as executable code.

For further reference, I'm using VCode, -nbstata- and Stata18
my quarto version is 1.3.299

Thank you

**Comment by cscheid** [comment]
That's not the syntax to use. Instead, you should wrap your code chunk in a div with a given class (and add css) or style attributes directly

**Comment by friosavila** [comment]
How do you do that?
Couldn’t find a way on the webpage

**Comment by cscheid** [comment]
Search for "div" on the search bar, you get [this](https://quarto.org/docs/authoring/markdown-basics.html#divs-and-spans).

**Comment by cderv** [comment]
@friosavila another way is that you should be able to use a cell option to add a class to the cell container. This would allow you to target using CSS. See `classes`
https://quarto.org/docs/reference/cells/cells-jupyter.html#attributes

Theme variables using SASS should also help you change the monospace font size for your document if you are targetting all code cells https://quarto.org/docs/output-formats/html-themes.html#fonts
