### ISSUE TITLE
Highlight the "reserved" labels (HTML ids) prefixes

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#6201]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3044

<div type='discussions-op-text'>

<sup>Originally posted by **mcanouil** October 26, 2022</sup>
Recently and few times already, some issues were reported when using some of the prefixes defined in Quarto for cross-references.
- <https://twitter.com/PipingHotData/status/1585067723268050944?s=20&t=QMv2ClFJdoD8W6cWpy0-5A>
- <https://twitter.com/LisaDeBruine/status/1584586868058132481?s=20&t=QMv2ClFJdoD8W6cWpy0-5A>
- #6200

I think, it would be a good idea to highlight somewhere (maybe in <https://quarto.org/docs/authoring/cross-references.html>) that there are some "reserved" prefixes for labels and HTML ids, such as `fig-`, `tbl-`, `thm-`, `eq-`, _etc._</div>

**Comment by cscheid** [comment]
Could we postpone the work on this until I have the new crossref work? It would reduce duplication.

**Comment by mcanouil** [comment]
Yes of course!
I simply opened the issue to better track this than the discussion as we will want to do it.

**Comment by cwickham** [comment]
It also feels like this needs to be wherever people are first encountering `label`. E.g. someone using `label` to allow a knitr chunk reference (`<<chunk1>>`) may never have visited the cross reference page. A note on the reference pages might be one other place to mention it.

**Comment by cscheid** [comment]
> It also feels like this needs to be wherever people are first encountering `label`.

I agree, but not exclusively so; the prefixes are also important to know when creating crossreferenceable artifacts "the markdown way", such as

```
## an image

![A caption](./image.png){#fig-1}

## a div

::: {#fig-2}

![](./image.png)

A caption

:::

## A markdown table

| hi | there |
|---|---|
| some | rows |
| go | here |
: A table caption {#tbl-3}

```

And so on.

**Comment by cwickham** [comment]
Adding a note: where we discuss things you shouldn't put in labels also mention underscores.
