### ISSUE TITLE
prefer-html:true and (Python) pandas render to Markdown has invalid YAML front matter

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#6237]
### Bug description

Use `prefer-html:true` produces an invalid YAML front matter in Markdown output when using Python pandas library.

### Steps to reproduce

Consider the [Jupyter Notebook minimal working example](https://github.com/quarto-dev/quarto-cli/files/12067462/mwe-javascript.zip) that has a single Python code cell with

``````
import pandas as pd

data = {
  "foo": ['f', 'o', 'o'],
  "bar": ['b', 'a', 'r']
}

df = pd.DataFrame(data)

df
``````

`quarto render mwe.ipynb --execute --to markdown --metadata="prefer-html:true"` executes and shows

``````
Executing 'mwe.ipynb'
  Cell 1/1: ''...Done

pandoc 
  to: markdown
  output-file: mwe.md
  standalone: true
  default-image-extension: png
  
metadata
  title: MWE
  author: Raniere Silva
  prefer-html: true
  
Output created: mwe.md
``````

Now, run `quarto render mwe.md --to html`.

Note: `quarto render mwe.ipynb --to html --metadata="prefer-html:true" --execute` work as expected.

### Expected behavior

`quarto render mwe.ipynb --execute --to markdown --metadata="prefer-html:true"` to produce a Markdown file with valid YAML front matter. For example

``````
---
author:
- Raniere Silva
header-includes:
- <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
- <script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
title: MWE
toc-title: Table of contents
---

::: {.cell execution_count="1"}
``` {.python .cell-code}
import pandas as pd

data = {
  "foo": ['f', 'o', 'o'],
  "bar": ['b', 'a', 'r']
}

df = pd.DataFrame(data)

df
```

::: {.cell-output .cell-output-display execution_count="8"}
```{=html}
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
```
      foo   bar
  --- ----- -----
  0   f     b
  1   o     a
  2   o     r

```{=html}

</div>
```
:::
:::
``````

### Actual behavior

`quarto render mwe.ipynb --execute --to markdown --metadata="prefer-html:true"` produces an invalid YAML front matter.

``````
---
author:
- Raniere Silva
header-includes:
- |
  <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
  <script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
title: MWE
toc-title: Table of contents
---

<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


::: {.cell execution_count="1"}
``` {.python .cell-code}
import pandas as pd

data = {
  "foo": ['f', 'o', 'o'],
  "bar": ['b', 'a', 'r']
}

df = pd.DataFrame(data)

df
```

::: {.cell-output .cell-output-display execution_count="8"}
```{=html}
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
```
      foo   bar
  --- ----- -----
  0   f     b
  1   o     a
  2   o     r

```{=html}

</div>
```
:::
:::
``````

The error reported by `quarto render mwe.md --to html` is

```
ERROR: Validation of YAML front matter failed.
ERROR: In file mwe.md
(line 5, column 3) Array entry 1 is empty but it must instead be a string.
4: header-includes:
5: - |
    ~
6:   <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

ERROR: Render failed due to invalid YAML.
```

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.5: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.230
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /home/raniere/micromamba/envs/debug-ipynb/bin/python
      Jupyter: 5.3.1
      Kernels: python3

(\) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /usr/lib/R
      LibPaths:
        - /home/raniere/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Thanks for the report. I think there are several topics in this issue: 

1.  as others issue opened already, there is some work to do to make Markdown output a first class output. I believe we need some improvement on that matter.  

    Though I think at some point, some [Discussions](https://github.com/quarto-dev/quarto-cli/discussions) could be needed so that you can clearly detail and explain what you are trying to do with Quarto regarding Markdown outputs. It would help us know what to target and what to improve. 

	With the number of issue you are opening on this, I believe you have a pretty specific usage and you are on the edge of what Quarto can do, or even is supposed to support regarding Markdown output.  

2.  maybe a clarification. I understand you are doing `--to markdown` with some content, and then trying `--to html` on the `.md` result. 
   As of now, there is no guarantee that the `.md` produced by `format: markdown` is a Quarto markdown valid input. It should in most of the case, but it is not designed to this. We should do our best effort to fix any issue that could be though. @cscheid you may have thought on that and maybe correct me if I am wrong. 

 `header-includes` result is part of this. In Quarto, the YAML field to use is [`include-in-header`](https://quarto.org/docs/output-formats/pdf-basics.html#latex-includes). 

3. The error you encounter has nothing to do with Mardown output or `prefer-html`, nor `Python`. This is only a YAML validation issue of `header-includes` field which does not support this form of setting multiline field (`- |`). Another minimal example would be 

````markdown
---
title: "Latex Header include"
format: latex
header-includes:
  - |
    ```{=latex}
    \let\oldsection\section
    \renewcommand{\section}[1]{\clearpage\oldsection{#1}}
    ```
---

Test document with LaTeX

````

````
ERROR: Validation of YAML front matter failed.
ERROR: In file C:\Users\chris\Documents\DEV_OTHER\DEMOS\test-quarto\test.qmd
(line 5, column 5) Array entry 1 is empty but it must instead be a string.
4: header-includes:
5:   - |
      ~
6:     ```{=latex}

ERROR: Render failed due to invalid YAML.
````

Where correct syntax for Quarto would be
````markdown
---
title: "Latex Header include"
format: 
  latex:
    include-in-header: 
      - text: |
          \let\oldsection\section
          \renewcommand{\section}[1]{\clearpage\oldsection{#1}}
---

Test document with LaTeX
````

@cscheid on this, this is YAML validation matter. Do we miss a valid form of `header-includes` ? This is supposed to be valid in [Pandoc's YAML block](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block)
````yaml
header-includes:
- |
  ```{=latex}
  \let\oldsection\section
  \renewcommand{\section}[1]{\clearpage\oldsection{#1}}
  ```
````

**Comment by rgaiacs** [comment]
@cderv Thanks for the fast reply.

> Though I think at some point, some [Discussions](https://github.com/quarto-dev/quarto-cli/discussions) could be needed so that you can clearly detail and explain what you are trying to do with Quarto regarding Markdown outputs.

I created https://github.com/quarto-dev/quarto-cli/discussions/6240

> As of now, there is no guarantee that the `.md` produced by `format: markdown` is a Quarto markdown valid input. It should in most of the case, but it is not designed to this.

Will be more value for the Quarto core team if I target a [official supported Markdown flavour like Hugo](https://quarto.org/docs/output-formats/hugo.html)?

> This is only a YAML validation issue of `header-includes` field

My intention was to provide context of where the invalid field was coming from.

**Comment by mcanouil** [comment]
Maybe the best target format as intermediary file would be the `native` format which you can use with Pandoc and Quarto (in theory, as I don't know if we can ask Quarto to use this as input).
The `native` format is the AST and it supposed to include a better representation of the document.

**Comment by cscheid** [comment]
@cderv 

> 3\. @cscheid on this, this is YAML validation matter. Do we miss a valid form of `header-includes` ? This is supposed to be valid in [Pandoc's YAML block](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block)
>     ```yaml
>     header-includes:
>     - |
>       ```{=latex}
>       \let\oldsection\section
>       \renewcommand{\section}[1]{\clearpage\oldsection{#1}}
>       ```
>     ```

This looks like a bug on our validator. I'll follow up separately.

**Comment by cscheid** [comment]
Bugfix for #6269 is now merged to `main`.

**Comment by cderv** [comment]
@rgaiacs the error you see will now be different I believe. Maybe no more error and maybe still no the expected behavior for all the reason discussed above. 

When next daily build is ready (version strictly above v1.4.236), can you try again and update us ?

**Comment by rgaiacs** [comment]
Thanks @cscheid for the bug fix. It works on my machine.
