### ISSUE TITLE
Supporting category like feature for listing authors (e.g. filter by author like categories)

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#6246]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/6243

<div type='discussions-op-text'>

<sup>Originally posted by **maelle** July 17, 2023</sup>
### Description

Is there a way to set up listings by author similar to the listings by categories https://quarto.org/docs/websites/website-listings.html#categories? I was also hoping to link author names to their post listings. From what I see in the docs, the taxonomy support in Quarto is (understandably!) less complete than with, say, Hugo?

Sorry in advance if I missed something. :pray: </div>

**Comment by maelle** [comment]
In case this is similar, let me mention the idea of doing the same things for tags (not only categories). :slightly_smiling_face:

**Comment by mcanouil** [comment]
FYI, a bit related to:
- https://github.com/quarto-dev/quarto-cli/issues/4669

**Comment by jpmorr** [comment]
This exactly what I was trying to do, so that each person can have a publications list on their profile of only their work, but generated from the central publications list. 

The extra enhancement I'd like to suggest is something related to publication type which is the final part of the sorting trilogy of author, topic and publication type. I'm currently testing adding a `publication_type` entry to the metadata - would I be able to filter on this custom field for the listing?

**Comment by maelle** [comment]
@dragonstyle thanks! Will one be able to create listing for all authors without having to explicitely set up a listing for each of them?

**Comment by maelle** [comment]
I think my feature request was a bit different: I'd like to have a general way to turn on "filtering by author" without creating one listing for each author, if that makes sense?

**Comment by dragonstyle** [comment]
Can you say a bit more about what you mean by this? You can enable user filtering UI for your global listing here:

https://quarto.org/docs/websites/website-listings.html#filtering

Are you looking for something different?

**Comment by maelle** [comment]
Oh, this search bar is great! 

Then I think the idea of "author pages" (listing by author, for all authors) is in #4669

**Comment by maelle** [comment]
Thanks!!

**Comment by mcanouil** [comment]
- From https://github.com/quarto-dev/quarto-cli/issues/4669

> Unsure whether a new issue is needed: it'd be nice to also be able to store an URL by author, in blogs for instance. This way in the blog metadata in each post, the author name could be a link to that URL.

FYI I went with the generated approach where there is a listing per author and I link to that listing in relevant places. https://m.canouil.dev/quarto-extensions/

https://github.com/quarto-dev/quarto-cli/issues/4669 is not about listing but about metadata storage/reference.
