### ISSUE TITLE
Add `attributes` as code cells option (alongside `classes`)

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#6253]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5587

<div type='discussions-op-text'>

<sup>Originally posted by **mcanouil** May 17, 2023</sup>
From #5456 and https://github.com/yihui/knitr/issues/2256, I believe it would be very useful to be able to add any kind of attributes and not only classes to cell container.
For instance, `knitr` offers `class-*` and the general `attr-*` options to customise code cells.

This `attributes` could help leverage many Bootstrap features already embedded in Quarto, such as popover or tooltip which uses `data-bs-*` attributes.</div>

**Comment by dragonstyle** [comment]
Currently, any non-Quarto attributes that are present in the Quarto metadata for code cells will be included in the output code cell div as a 'data' attribute. For example:

````markdown
```{r}
#| label: fig-cars
#| bs-parent: "#my-parent"
plot(cars)
```
````

results in:

```html
<div class="cell" data-bs-parent="#my-parent">
...
</div>
```

I think this should be enough (and so I'm closing this), but re-open if there is more we need to do!
