### ISSUE TITLE
some Latex symbols/annotation not displaying correctly with revaljs presentation 

### ISSUE THREAD

**Issue by danieltomasz** [quarto-dev/quarto-cli#6263]
### Bug description

I have presentation in revealjs, the latex displays fine in Rstudio editor but some parts of it are cut in Revealjs presentation 
![image](https://github.com/quarto-dev/quarto-cli/assets/7980381/c5dbbc74-ebd0-4410-9aad-e0ee6ffa5027)
![image](https://github.com/quarto-dev/quarto-cli/assets/7980381/94badb54-2fb3-4dca-9bcc-ff6929f57f1a)

### Steps to reproduce

MVE 
```
---
title: "Statistical Learning"
execute:
 echo: false
 warning: false
 message: false
 cache: false
format:
  revealjs:
    standalone: true
    embed-resources: true
    width: 1600
    height: 900
    slide-number: true
    fig-cap-location: top
    fig-format: svg
    pdf-separate-fragments: false
---

## Bias-Variance Tradeoff 

- Variance refers to the amount by which $\hat{f}$ would change if we estimated it using a different training data set - small change in data change much the result
- Bias is a diffence between this estimator's expected value and the true value

$$\text{MSE} = \underbrace{\text{Var}(\hat{f}(x_0))}_{\text{Variance}} + \underbrace{[\text{Bias}(\hat{f}(x_0))]^2}_{\text{Bias}^2} + \underbrace{\text{Var}(\varepsilon)}_{\text{Irreducible Error}}$$

- Flexible methods have higher variance, less bias
- Simple methods have lower variance, more bias  
- Want to balance bias and variance
```

### Expected behavior

Latex will display ok

### Your environment

- IDE Version 2023.09.0-daily+233 (2023.09.0-daily+233)
- MacOS 13.4
- Quarto: 1.4.232

**Comment by cderv** [comment]
I don't see any issue on my side rendering your example
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/97ec53ad-fb33-45d9-8bf8-4b86640159cd)

> ```
>  revealjs:
>    standalone: true
>    embed-resources: true
> ```

I see you are using this. 

Can you clean existing resource folder and re render ? Or try without those options ? 

Maybe there is a dependency or caching issue somewhere.

**Comment by danieltomasz** [comment]
I moved qmd to empty folder and tried to run it, with simplified yaml I am getting the same result; I might try to downgrade quarto to see the effect

**Comment by danieltomasz** [comment]
downgrading and updating tinytex doesnt change it, there was different problem with uderbrace with pdf output, it was solved by changing font, might my problem caused by system font? (Rstudio might use different font for generating preview)

https://github.com/quarto-dev/quarto-cli/discussions/5564

**Comment by danieltomasz** [comment]
Using 
```
format: 
  revealjs:
    html-math-method: mathjax
```
Fixes my problem (as it was discussed here https://github.com/quarto-dev/quarto-cli/discussions/3127)

**Comment by cderv** [comment]
Ok good! Still surprised I can't reproduced. 

Glad it works ! 

> downgrading and updating tinytex doesnt change it,

BTW TinyTeX won't be involved when you are rendering Math to HTML

**Comment by danieltomasz** [comment]
@cderv  which version Rstudio are you using? There might be some  differences in rendering (and maybe you could reproduce if you set the preview in the browser?) 

Thanks for help!
