### ISSUE TITLE
failed to highlight tikz code when `engine: "tikz"`

### ISSUE THREAD

**Issue by XiangyunHuang** [quarto-dev/quarto-cli#6264]
### Bug description

I use TikZ to create a figure. I notice that Quarto failed to highlight tikz code in Quarto Document.

<img width="784" alt="tikz" src="https://github.com/quarto-dev/quarto-cli/assets/12031874/01e0fb1d-74f1-4956-aff0-fb19262f1623">

### Steps to reproduce

Here is a minimal example.

````qmd

---
title: "Untitled"
---

```{r}
#| label: fig-tikz-plot3d
#| engine: "tikz"
#| echo: false
#| fig-cap: TikZ
#| engine-opts: !expr list(extra.preamble=c("\\usepackage{pgfplots}","\\pgfplotsset{width=7cm,compat=1.18}"))

\begin{tikzpicture}
\begin{axis}[
    hide axis,
    colormap/viridis,
]
\addplot3[
    mesh,
    samples=50,
    domain=-8:8,
]
{ sin(deg(sqrt(x^2+y^2)))/sqrt(x^2+y^2) };
\addlegendentry{$\frac{\sin(r)}{r}$}
\end{axis}
\end{tikzpicture}
```

````

### Expected behavior

The TikZ code can be correctly identified as LaTeX code.

### Actual behavior

<img width="784" alt="tikz" src="https://github.com/quarto-dev/quarto-cli/assets/12031874/01e0fb1d-74f1-4956-aff0-fb19262f1623">

### Your environment

RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-06) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

### Quarto check output

```
❯ quarto check
```
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/local/Cellar/r/4.3.1/lib/R
      LibPaths:
        - /usr/local/lib/R/4.3/site-library
        - /usr/local/Cellar/r/4.3.1/lib/R/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Where exactly are you expecting to see some highlighting?

**Comment by XiangyunHuang** [comment]
Hopefully TikZ code is treated the same as LaTeX code .

<img width="803" alt="latex" src="https://github.com/quarto-dev/quarto-cli/assets/12031874/2fa8ecff-6e6e-49e5-bf46-9ca6a00d5ae4">

**Comment by cderv** [comment]
Are you referring to highlighting in source document opened in an IDE (RStudio IDE or VSCODE ?) ? 

Or are you referring to highlighting in output code for the source code chunk ? 

In the former case, this would be an issue for IDE to know how to highlight. However in RSTUDIO IDE for example, it should already be the case but just do not use `{r}` but `{tikz}` directly. 

````markdown

```{tikz}
#| label: fig-tikz-plot3d
#| fig-cap: TikZ
#| engine-opts: !expr list(extra.preamble=c("\\usepackage{pgfplots}","\\pgfplotsset{width=7cm,compat=1.18}"))

\begin{tikzpicture}
\begin{axis}[
    hide axis,
    colormap/viridis,
]
\addplot3[
    mesh,
    samples=50,
    domain=-8:8,
]
{ sin(deg(sqrt(x^2+y^2)))/sqrt(x^2+y^2) };
\addlegendentry{$\frac{\sin(r)}{r}$}
\end{axis}
\end{tikzpicture}
```
````

(and add `engine: knitr` in YAML of your document if you don't have any other R chunk in your doc - or to be sure that **knitr** will be used to run computation). 

In the latter case, Quarto (through **knitr**) should already output a code block with LaTeX highlighting.

**Comment by XiangyunHuang** [comment]
> Are you referring to highlighting in source document opened in an IDE (RStudio IDE or VSCODE ?) ?

Yes, I use RStudio IDE.

> it should already be the case but just do not use `{r}` but `{tikz}` directly.

Thanks, I don't know this before. So, I'm gone to close this report.

**Comment by XiangyunHuang** [comment]
````
---
title: "Untitled"
engine: knitr
format: pdf
---

```{tikz}
#| label: fig-tikz-plot3d
#| fig-cap: TikZ
#| engine-opts: !expr list(extra.preamble=c("\\usepackage{pgfplots}","\\pgfplotsset{width=7cm,compat=1.18}"))

\begin{tikzpicture}
\begin{axis}[
    hide axis,
    colormap/viridis,
]
\addplot3[
    mesh,
    samples=50,
    domain=-8:8,
]
{ sin(deg(sqrt(x^2+y^2)))/sqrt(x^2+y^2) };
\addlegendentry{$\frac{\sin(r)}{r}$}
\end{axis}
\end{tikzpicture}
```

``` tex
\begin{tikzpicture}
\begin{axis}[
    hide axis,
    colormap/viridis,
]
\addplot3[
    mesh,
    samples=50,
    domain=-8:8,
]
{ sin(deg(sqrt(x^2+y^2)))/sqrt(x^2+y^2) };
\addlegendentry{$\frac{\sin(r)}{r}$}
\end{axis}
\end{tikzpicture}
```

````


<img width="800" src="https://github.com/quarto-dev/quarto-cli/assets/12031874/65c09901-ede9-4bcb-945b-e03a190f8e25">

### If `{tikz}` source code chunk is highlighted as LaTeX code, it will be great.

**Comment by cderv** [comment]
It is highlighted as TeX in Source mode, but it does not seem to be the case in Visual mode. 

This would be an issue for the RStudio IDE
