### ISSUE TITLE
Inline Python code should not include quotes for strings

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#6288]
From <https://quarto.org/docs/prerelease/1.4/inline.html>, it is now possible through Jupyter as the engine to have inline code.

`` `{python} "French"` `` currently produces `"French"` which is what `"French"` default print in a code cell would print.
Most users are likely to want to include strings as is, _i.e._, without the quotes.
In a Python cell, it's possible to get the wanted result using `print("French", end="")` which produces `French`.
  
To note, `` `{r} "French"` `` (via `knitr`) produces `French`.

**Comment by GitHunter0** [comment]
> Most users are likely to want to include strings as is, _i.e._, without the quotes

I agree @mcanouil , I believe it's very important to be that way. 

For example, I'm trying to dynamic change the title of a section with something like this:
Run in terminal:
```
quarto render myfile.qmd -P section_title:'Some Title'
```
In `myfile.qmd`:
```
# `{python} section_title`
```
The result is:
`'Some Title'` instead of `Some Title`. 

Is there currently a workaround to achieve the expected result without the quotes?

**Comment by mcanouil** [comment]
@GitHunter0 keep in mind that this new feature is less than a week old and is in the pre-release version for a reason.
By using the pre-release version you basically agree with the fact that not everything works.
There is no reason to figure out a possible workaround for a "work in progress" feature.

**Comment by GitHunter0** [comment]
@mcanouil , for sure, I forgot it was a pre-release feature.

**Comment by cscheid** [comment]
For documentation, this is the current behavior for knitr:

````
---
title: "inline r examples"
engine: knitr
keep-md: true
echo: false
---


```{r}
v1 <- "test"
v2 <- 3
v3 <- "*foo*"
v4 <- FALSE
v5 <- TRUE
v6 <- NULL
```

Examples:

- `{r} v1`
- `{r} v2`
- `{r} v3`
- `{r} v4`
- `{r} v5`
- `{r} v6`

```{r}
v1
v2
v3
v4
v5
v6
```
````

MD output from knitr:

````
---
title: "inline r examples"
engine: knitr
keep-md: true
echo: false
---


::: {.cell}

:::


Examples:

- test
- 3
- *foo*
- FALSE
- TRUE
- 


::: {.cell}
::: {.cell-output .cell-output-stdout}
```
[1] "test"
```
:::

::: {.cell-output .cell-output-stdout}
```
[1] 3
```
:::

::: {.cell-output .cell-output-stdout}
```
[1] "*foo*"
```
:::

::: {.cell-output .cell-output-stdout}
```
[1] FALSE
```
:::

::: {.cell-output .cell-output-stdout}
```
[1] TRUE
```
:::

::: {.cell-output .cell-output-stdout}
```
NULL
```
:::
:::
````

I genuinely don't like the defaults from knitr here, but we're clearly stuck with them.
