### ISSUE TITLE
Bad `code-annotations` behaviour when no "list" annotation is provided

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#6313]
### Bug description

While checking #6297 I noticed a bad behaviour of the code annotation feature when the annotation comment is added to the code cell without the associated list annotation.

CC. @cderv 

### Steps to reproduce

````qmd
---
format: html
---

```{r}
stats::rnorm(2) # <1>
```

````

### Expected behaviour

If no list is provided just below the code cell, annotation should not exist and the code cell should behave as if `code-annotations: false`.

See <https://github.com/mcanouil/quarto--code-link--code-annotations>.

### Actual behavior

The code cell (source and output) is completely removed.

**Comment by cderv** [comment]
Note that this happens only when there is really no content below the code cells; If there is content (but still not a list annotation), the cell source and results is not removed. 

````markdown
---
format: html
---

```{r}
stats::rnorm(2) # <1>
```

Content
````

**Comment by cderv** [comment]
Ok this is really that the problem. When there is no block after the  executable code block, then we don't add to the `outputs` we save to return in `allOutputs()`

@dragonstyle here my digging

We do process annotations for executable code cells but we store in `pendingCodeCell`
https://github.com/quarto-dev/quarto-cli/blob/907d4c265173d22362e510866b67f724c5150c96/src/resources/filters/quarto-pre/code-annotation.lua#L380-L383
we don't add it to `outputBlock()` , so after the above, as we don't have any other blocks we don't go to 
https://github.com/quarto-dev/quarto-cli/blob/907d4c265173d22362e510866b67f724c5150c96/src/resources/filters/quarto-pre/code-annotation.lua#L502-L504
and we directly return 
https://github.com/quarto-dev/quarto-cli/blob/907d4c265173d22362e510866b67f724c5150c96/src/resources/filters/quarto-pre/code-annotation.lua#L506

but `outputs` is still empty 

I'll do a PR with an idea to fix, but please to change it if I did not get it right.
