### ISSUE TITLE
Cannot render/preview inside a docker container due Segmentation fault error

### ISSUE THREAD

**Issue by bastianabaleiv** [quarto-dev/quarto-cli#6315]
### Bug description

Hi, 

I'm trying to use quarto inside a docker container (`Dockefile` below) and i got a Segmentation fault error when checking installation and rendering or previewing `.qmd` files.

### Steps to reproduce

``` docker
FROM python:3.11.4-slim-bullseye

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    curl \
    gdebi-core \
    && rm -rf /var/lib/apt/lists/*

ENV QUARTO_VERSION="1.3.433"

RUN curl -o quarto-linux-amd64.deb -L https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb && \
    gdebi --non-interactive quarto-linux-amd64.deb && \
    rm quarto-linux-amd64.deb

RUN opt/quarto/bin/quarto check
```

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/quarto/bin

/opt/quarto/bin/quarto: line 158:   845 Segmentation fault      "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"
```

### Expected behavior

Check quarto installation / render / preview a `.qmd` succesfully.

### Actual behavior

Segmentation fault error as:

`/opt/quarto/bin/quarto: line 158:   845 Segmentation fault      "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"`

### Your environment

- Docker Desktop 4.21.1 (114176)
- macOS Ventura 13.4.1 (c) Intel Processor

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/quarto/bin

/opt/quarto/bin/quarto: line 158:   845 Segmentation fault      "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"
```

**Comment by mcanouil** [comment]
Could you make sure your example is reproducible?
There is at least one typo in your Dockerfile.

**Comment by bastianabaleiv** [comment]
I was able to build with the same image in another laptop. Sorry about all the fuss.

**Comment by chasemc** [comment]
Ran into this today after upgrading Docker desktop on Mac.
```
FROM ubuntu:24.04
RUN apt-get update && apt-get install -y wget && \
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb && \
    dpkg -i quarto-1.3.450-linux-amd64.deb && \
    rm quarto-1.3.450-linux-amd64.deb
```


Problem seems to be with Docker's virtualization on Mac (related https://github.com/docker/for-mac/issues/6824)

Changing file sharing implementation from VirtioFS to osxfs and turning off `Use virtualization framework` solved the segfault issue for me

<img width="918" alt="Screenshot 2023-12-29 at 9 40 53 AM" src="https://github.com/quarto-dev/quarto-cli/assets/18691127/9670abf4-3713-4835-a628-2b0ca23a671e">
