### ISSUE TITLE
Using unicode character EM DASH and R chunk breaks rendering

### ISSUE THREAD

**Issue by bhaurb** [quarto-dev/quarto-cli#6339]
### Bug description

If you add an EM DASH character in the text of a .qmd file, and include an R-chunk, then rendering stops with a premature EOF error. I ran into this because I copied an APA citation that secretly included an EM DASH instead of a "normal" hyphen. 

The same issue occurs with EN DASH symbols. 

### Steps to reproduce

````
Hello. This is an em dash — and it causes issues. 

```{r}
  a <- 1
```
````

### Expected behavior

I would expect the code to render. 

### Actual behavior

You receive an error message. 

```
Error: parse error: premature EOF
                                       {"action":"execute","params":{"
                     (right here) ------^
Execution halted
```

### Your environment

IDE: RStudio 2022.07.2 Build 576
OS: Windows 10 22H2. 

### Quarto check output

```
[>] Checking Quarto installation......OK
      Version: 1.2.269
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.15 (Conda)
      Path: C:/ProgramData/Miniconda3/python.exe
      Jupyter: 5.1.3
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.2
      Path: C:/PROGRA~1/R/R-42~1.2
      LibPaths:
        - P:/r_packages/R-4.2.2
        - C:/Program Files/R/R-4.2.2/library
      rmarkdown: 2.18

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report!

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by bhaurb** [comment]
Yeah, I can do that.

````qmd
---
title: "Reproducible EM/EN DASH issue" 
format: html
---

Hello. This is an em dash — and it causes issues. 

```{r}
  a <- 1
```

Rendering does not work for me.
````

**Comment by cderv** [comment]
I can't reproduce this with latest Quarto on Windows. 

You are using 1.2 - can you update to latest stable 1.3 or even latest pre-release 1.4 ?

**Comment by bhaurb** [comment]
As I have no control over what versions are installed on this PC, no I cannot. However, I think we should be updating to 1.4 in the near future. Maybe the issue can be closed, and if I run into a similar issue when we've upgraded, I can open another issue?

**Comment by mcanouil** [comment]
@bhaurb What's the `knitr` version you are using? Could you double check your example in a closed environment, _i.e._, in a separate directory/project without anything such as `_quarto.yml`, etc.?

**Comment by sda030** [comment]
For what it's worth, it renders perfectly for me. Using Quarto 1.4.435 and RStudio 2023.12.0 Build 170.
