### ISSUE TITLE
Captions with `=` returns warning message under R chunk in RStudio

### ISSUE THREAD

**Issue by petzi53** [quarto-dev/quarto-cli#6341]
### Bug description

Whenever there is a mathematical operator containing the equal sign `=` in a caption string, RStudio displays a warning message under the chunk output.

### Steps to reproduce

```{r}
#| label: tbl-test
#| tbl-cap: "Caption with mathematical operator =" 

tibble::tibble(x = runif(10), y = x * 2)
```
The warning message appears with all captures (table, figure, etc.) and with all mathematical operators containing the `=` sign (=, <=, >=,  !=, ==).

Enclosing the operator like '=', $=$, `=` could not prevent the warning.

### Expected behavior

Working without warning.

### Actual behavior

RStudio displays the following warning under the chunk that contains the caption with the `=` 

```
Warning messages:
1: In value[[3L]](cond) : Failed to parse chunk options in body:
Error in parse(text = code, keep.source = FALSE): <text>:1:24: unexpected symbol
1: alist( label: tbl-test tbl
                           ^

2: In opts$engine <- unlist(strsplit(rmdChunkOpts, split = "(\\s|,)+"))[[1]] :
  Coercing LHS to a list
```

### Your environment

- R: 4.3.1 (2023-06-16)
- IDE: Studio Version 2023.06.1+524
- OS: MacOS Ventura 13.4.1
- Quarto: 1.4.232

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.5: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.232
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.3
      Path: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

(-) Checking R installation...........R version 4.3.1 (2023-06-16)
[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/library
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Can you please file this at https://github.com/rstudio/rstudio? Thanks.

**Comment by cderv** [comment]
I'll close this and you can track the RStudio IDE issue
