### ISSUE TITLE
Quarto with OJS should work from file:// URLs with embed-resources

### ISSUE THREAD

**Issue by romanzenka** [quarto-dev/quarto-cli#6371]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5680

<div type='discussions-op-text'>

<sup>Originally posted by **harrylojames** May 25, 2023</sup>

> After doing "quarto render file.qmd --to html" I am unable to double click and view the html file. Here is the error.  It does as stated work from a web server i.e. with preview. 
> 
> "The OJS runtime does not work with file:// URLs. Please use a web server to view this document."
> 

...</div>

After some experimenting, I found out that if I embed resources and manually remove the JavaScript code that tests for file:// URL from the resulting HTML, I get a fully functional, interactive, ObservableJS-enabled document. I think it is logical this works - the file:// URLs disable loading files saved next to the document, but once those resources get embedded, the resulting .html file works ok.

This functionality is very important for us, as we rely on it to deliver "self-contained" html documents to our clients, that can be viewed and interacted with independently on any software they might have installed on their machines. It is not realistic for us to teach them how to run local webservers just so they can look at our files.

I propose a fix that would disable the `file://` URL checking code in case quarto is running in `embed-resources` mode. Otherwise I can keep using Quarto, but I'd have to pass every file being generated through a small `sed` script that would yank the offending JavaScript, which is quite inconvenient.

I am not familiar with the codebase, but I'll try to take a shot at a PR, as this is unfortunately a show-stopper for us.

**Comment by cscheid** [comment]
> I am not familiar with the codebase, but I'll try to take a shot at a PR, as this is unfortunately a show-stopper for us.

I would warn you that I'm pretty familiar with the code base and I've already spent about 2-3 full days trying this. It's much harder than you'd think.

> After some experimenting, I found out that if I embed resources and manually remove the JavaScript code that tests for file:// URL from the resulting HTML, I get a fully functional, interactive, ObservableJS-enabled document. I think it is logical this works - the file:// URLs disable loading files saved next to the document, but once those resources get embedded, the resulting .html file works ok.

> I propose a fix that would disable the file:// URL checking code in case quarto is running in embed-resources mode.

That would not be an acceptable fix for us. There are OJS features which simply don't work in file:// mode. Specifically, dynamic JS module imports simply don't work (see https://github.com/whatwg/html/issues/8121)

**Comment by romanzenka** [comment]
@cscheid Ok, I understand. I will provide a PR for those users who need this anyway, even if it does not make it to the main branch. I would be grateful if you glanced at it (it is very short) and maybe hinted at how to make this properly, but this is purely optional as I realize you are busy. Thank you for your valuable input regarding this issue.

**Comment by BenoitGoutorbe** [comment]
Standalone interactive HTML reports are a hudge matter for many of us. I hope this issue will be fixed soon !

**Comment by mcanouil** [comment]
FYI:
- #7671

**Comment by novotny1akub** [comment]
@mcanouil I would still welcome a clear stance on this issue. Some OJS features were clearly supported in Quarto 1.2.280, and as a consequence, standalone Quarto html with OJS worked. This seems to be no longer the case with the most recent version of Quarto, possibly due to some downstream changes (e.g. Observable stdl). It would be helpful to know if standalone html documents are likely to work again in the foreseeable future or one should downgrade to 1.2.280 or possibly use a completely different tool than Quarto. In addition, I can't find any information on the standalone html documents with OJS to be discontinued  in the Quarto release notes. It might be worthwhile to warn users that the new Quarto version may cause their code stop working.

**Comment by novotny1akub** [comment]
Although I am sad there is not going to be a fix, it is good to have a resolution on it. Thanks a lot for looking into it @cscheid For me, "emailable Observable" that I can combine with R based preprocessing was a game changer. Still trying to get my head around the fact that all features of OJS that I ever needed, work just fine even today when on 1.2.280 :-(

For anyone trying to keep the "emailable OJS" on more recent versions of Quarto, I recommend looking into Mongoose. It is an additional file (but really tiny!) that will create a web server for your users in case you are not able to host your solution.

**Comment by cscheid** [comment]
> Still trying to get my head around the fact that all features of OJS that I ever needed, work just fine even today when on 1.2.280

It's relatively simple. Observablehq changed the entirety of their code base to use module-based imports (for good reason: it's what all modern js tooling expects and builds upon). Module-based imports are not allowed in file:// contexts. So we'd have to fork and maintain all of observablehq's code base for all time, all the while using legacy tooling whose support will only reduce over time. We can't justify it.

**Comment by anthonynorth** [comment]
Can we test for OJS features being used that aren't compatible in file:// contexts? E.g. Module imports.
Or could we add an option for allowing OJS features in file:// contexts? 

The only thing stopping Inputs being used for instance, is the file:// tests in javascript.

**Comment by anthonynorth** [comment]
AFAIK, it's local file modules that aren't supported in file:// contexts; e.g. `import * as foo from "./foo.js"` or `<script type="module" src="./foo.js"></script>` 

Inline modules and modules from another service work ok in file:// contexts.

Example: an inline module with an external dependency (works in chrome and edge from file://
```html
<html>
  <script type="module">
    import * as d3 from "https://cdn.skypack.dev/d3";
    console.log(d3);
  </script>
</html>
```

Should `embed-resources: true` have modules in external scripts?

**Comment by cscheid** [comment]
> Should `embed-resources: true` have modules in external scripts?

I'm not sure if you're implying this is a bug, but converting external imports into a single page ranges from (conservatively), multiple person-years of development effort to (realistically) fundamentally impossible. Consider `import()` statements with dynamically constructed strings. This is what observablehq.com uses.

**Comment by romanzenka** [comment]
> I'm not sure if you're implying this is a bug, but converting external imports into a single page ranges from (conservatively), multiple person-years of development effort to (realistically) fundamentally impossible. Consider `import()` statements with dynamically constructed strings. This is what observablehq.com uses.

I looked through observable stdlib, searching for `import()` and I found three occurrences the look like this:

```
export async function loadArrow() {
  return await import(`${cdn}${arrow.resolve()}`);
}
```

I looked at the runtime: https://cdn.jsdelivr.net/npm/@observablehq/runtime/dist/runtime.js and there are 2 places where `import()` is performed on a string, (related to DuckDB??). I suspect all this code is there to load few large third party modules on demand, allowing the user to choose which CDN they prefer.

I totally get that the Quarto developers are busy with important stuff, and I wouldn't want to burden them. But maybe the community could pitch in to solve this problem. It might involve swapping out a few Observable imports with something else while embedding, possibly using a simple regex. I wouldn't officially support this feature, as it could get broken with Observable updates. But for those who really need it, it would be a godsend.

**Comment by cscheid** [comment]
> But maybe the community could pitch in to solve this problem

@romanzenka, you've tried to do this in the past and didn't succeed. I'm just being clear here because this is not a matter of "community pitching in". This is _not_ "swapping out a few Observable imports". 

I promise you all I am not exaggerating the engineering effort involved here. You're either forking ObservableHQ source code _forever_, or, conservatively, integrating `embed-resources` with (in the limit) a system like `esbuild` in the middle of Pandoc's document generation.

In reality, because user code can _also_ do imports from dynamically generated strings, what you're trying to do runs into [Rice's theorem](https://en.wikipedia.org/wiki/Rice%27s_theorem). This is literally an undecidable problem.

I'm sorry, folks, I understand you'd like this to be a feature. But what you're actually asking for is (being very conservative about what gets actually fixed!) an entirely new product.

**Comment by romanzenka** [comment]
> > But maybe the community could pitch in to solve this problem
> 
> @romanzenka, you've tried to do this in the past and didn't succeed. I'm just being clear here because this is not a matter of "community pitching in". This is _not_ "swapping out a few Observable imports".

I have spent a very short time disabling two if statements in Quarto, I have not put serious effort into this.
 
> I promise you all I am not exaggerating the engineering effort involved here. You're either forking ObservableHQ source code _forever_, or, conservatively, integrating `embed-resources` with (in the limit) a system like `esbuild` in the middle of Pandoc's document generation.

But do we have to do this for embedding observable? I would say we can use pre-compiled Observable javascript modules, that will have a ton of imports already resolved, as it is a single javascript file.

> In reality, because user code can _also_ do imports from dynamically generated strings, what you're trying to do runs into [Rice's theorem](https://en.wikipedia.org/wiki/Rice%27s_theorem). This is literally an undecidable problem.

This is a very common fallacy. The problem itself IS indeed undecidable, but your specific instance of the problem can be so simple, it can be easily decidable. This is a situation where knowing too much prevents people from getting work done, because they categorize as "impossible" before they even start.

> I'm sorry, folks, I understand you'd like this to be a feature. But what you're actually asking for is (being very conservative about what gets actually fixed!) an entirely new product.

Well, I think the easiest way to prove you wrong would be to make it actually happen, but then you'd have to be prepared to merge it in, instead of rejecting it on the basis of Rice's theorem. ;)

**Comment by cscheid** [comment]
> This is a very common fallacy.

Let me be more blunt. I have a PhD in computer science. I was a CS professor for the better part of a decade. I taught this. You are wrong.

> The problem itself IS indeed undecidable, but your specific instance of the problem can be so simple, it can be easily decidable.

The specific instance is _not_ simple. You have to do this for arbitrary code coming from user code in `ojs` blocks as well, _on top_ of doing it for the instances you're seeing in the observablehq source code.

> Well, I think the easiest way to prove you wrong would be to make it actually happen, but then you'd have to be prepared to merge it in, instead of rejecting it on the basis of Rice's theorem. ;)

I've already told you once that PR's are welcome, and I'm sorry to be blunt again, but your PR didn't solve the problem. We are quickly approaching non-productive levels of discussion here. If folks have substantive comments to add, please do so, but down this path we will end up locking this discussion.

**Comment by romanzenka** [comment]
I am in no way discounting your academic expertise. What I am saying instead is that while the problem as posed is genuinely unsolvable, we can instead deploy a solution where - for instance - the human will manually add that one resolved extra URL they need, thus solving the problem in a practical sense. No arguing with theorems, but we don't have solve the problem as posed! We can cheat as much as we like, as long as the result works.

I'll dig around and see what I can do, because this issue made me originally abandon Quarto.

Yes, the proposed solution might not be pretty, and I absolutely do NOT expect you to support it, but if an advanced user really needs this, they should be allowed to work hard for it and get it done if they so choose.

**Comment by cscheid** [comment]
> No arguing with theorems, but we don't have solve the problem as posed! We can cheat as much as we like, as long as the result works.

You haven't addressed the substantive part of my comment: "You have to do this for arbitrary code coming from user code in ojs blocks as well, on top of doing it for the instances you're seeing in the Observablehq source code."

I'm sorry, I'm locking this.
