### ISSUE TITLE
code block table cross references and captions fail, but figure cross references and captions work

### ISSUE THREAD

**Issue by anielsen001** [quarto-dev/quarto-cli#6374]
### Bug description

Generating a table from a code block fails to correctly cross-reference the table or put in the table caption. Replacing the label and caption identifiers to look like a figure causes things to work. 

### Steps to reproduce

The document below will render and generate the problem

````qmd
---
title: "quarto-table"
format: html
---

Look at @tbl-info for more information. 

```{python}
#| echo: false
#| label: tbl-info
#| tbl-cap: "Informative table."
import pandas as pd
df = pd.DataFrame(
    data = { 
      'Column 1': [1,2,3],
      'Column 2': [4,5,6],
    },
    index = [
      "Row 1", 
      "Row 2",
      "Row 3",
    ]
)
df.to_html()
```

````

When rendered, the following output is generated:
```bash
$ quarto render quarto-table.qmd

Executing 'quarto-table.ipynb'
  Cell 1/1...Done

pandoc 
  to: html
  output-file: quarto-table.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: quarto-table
  
WARNING: Unable to resolve crossref @tbl-info
Output created: quarto-table.html

```

The rendered html output looks like this: 
![image](https://github.com/quarto-dev/quarto-cli/assets/9733765/d8f78ebb-cc48-47cb-83fc-752c683ffcb0)

If I pretend the table is a figure by replacing the `tbl-` with `fig-` then the document renders properly with a caption and the cross-reference works. 

````qmd
---
title: "quarto-figure"
format: html
---

Look at @fig-info for more information. 

```{python}
#| echo: false
#| label: fig-info
#| fig-cap: "Informative table."
import pandas as pd
df = pd.DataFrame(
    data = { 
      'Column 1': [1,2,3],
      'Column 2': [4,5,6],
    },
    index = [
      "Row 1", 
      "Row 2",
      "Row 3",
    ]
)
df.to_html()
```

````

![image](https://github.com/quarto-dev/quarto-cli/assets/9733765/a2f6782e-84e1-40cf-af20-2e8f8a60e61f)

### Expected behavior

The cross-reference to the table and it's caption should correctly appear within the document.

### Actual behavior

The cross-reference to the table cannot be resolved and the table caption appears as an error. 

### Your environment

- Ubuntu 20.04
- Using emacs as text editor

### Quarto check output

```bash
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.3
      Path: /home/apn/sw/bin/python3
      Jupyter: 4.10.0
      Kernels: julia-1.8, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by mcanouil** [comment]
The issue is that you are not outputting an actual table which can be recognise by Quarto.

The following work just fine:

````qmd
---
title: "quarto-table"
format: html
---

Look at @tbl-info for more information. 

```{python}
#| echo: false
#| label: tbl-info
#| tbl-cap: "Informative table."
import pandas as pd
df = pd.DataFrame(
    data = { 
      'Column 1': [1,2,3],
      'Column 2': [4,5,6],
    },
    index = [
      "Row 1", 
      "Row 2",
      "Row 3",
    ]
)
df
```
````

Note that in the future, it might just work with the work ongoing:

- #4944

**Comment by anielsen001** [comment]
If it refer to it as a figure, quarto likes it, but it's not really a figure either. Aside from me calling it a table, does quarto do something with the contents of the table? I would also like to generate an image of a table and have it referred to as a table in the cross-references.

**Comment by mcanouil** [comment]
See the "epic" issue I linked.

**Comment by anielsen001** [comment]
Thanks. Currently, I can call my table a figure and the cross ref works. I've been doing this for lack of a better table option. Is this likely to break at some point?

**Comment by cscheid** [comment]
(context: I'm working on crossrefs right now) I don't expect your usage to break in the new system.

**Comment by anielsen001** [comment]
Thank you. I'll just close this issue since it looks covered elsewhere.
