### ISSUE TITLE
special date using r inline does not work anymore

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#6380]
I started using quarto after Mar 2022, but when I would like to use

```{r}
title: "title"
date: "`r Sys.time()`"
image: "preview.png"
```
It produces a date in the html I am producing, but the index page of my quarto blog says.

```{r}
Invalid Date.
``` 
Anyway. Cheers,

_Originally posted by @racing-focus in https://github.com/quarto-dev/quarto-cli/issues/402#issuecomment-1656691242_

**Comment by cderv** [comment]
I can confirm that this does not work anymore 
````markdown
---
title: "title"
date: "`r Sys.time()`"
---

Test

````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/ea2dca70-7976-4449-b0a0-3b2093ddec6e)

cc @dragonstyle did we remove support ? 

It seems like the alias is no more a special date. 
https://github.com/quarto-dev/quarto-cli/blob/d076ea1e07e496ef879c31c1adb645318587ab9d/src/core/date.ts#L96-L99
so we don't parse it as such 
https://github.com/quarto-dev/quarto-cli/blob/d076ea1e07e496ef879c31c1adb645318587ab9d/src/core/date.ts#L101-L108

**Comment by cderv** [comment]
Oh I see. We changed the way it is processed in https://github.com/quarto-dev/quarto-cli/commit/f0f04bb10baccc14d4e45113078c1174135f7ad1

Now **knitr** resolves it. So it requires engine ! Make sense. 

`````markdown
---
title: "title"
date: "`r Sys.time()`"
engine: knitr
---

Test
````

@dragonstyle shouldn't we remove all reference to `rSysDate` then ? 

https://github.com/quarto-dev/quarto-cli/blob/d076ea1e07e496ef879c31c1adb645318587ab9d/src/core/date.ts#L25

**Comment by dragonstyle** [comment]
Yes this would def make sense! I will do it!

**Comment by dragonstyle** [comment]
OK this should be square away!

**Comment by racing-focus** [comment]
Thankyou for looking at this, but I did as you suggested,

```{r}
title: "some chances today"
date: "`r Sys.time()`"
image: "preview.png"
engine: knitr

```

the date prints on the html blog I am writing, like so,

![Screen Shot 2023-08-10 at 2 07 16 pm](https://github.com/quarto-dev/quarto-cli/assets/121075286/5a6be4bb-63cf-445e-bc29-0ec2f90d2d2b)

but, it doesn't appear on the index of the blog, like so.
 

![Screen Shot 2023-08-10 at 2 07 29 pm](https://github.com/quarto-dev/quarto-cli/assets/121075286/d9d73297-e3b3-445f-8ddd-d733b696e074)

does that make sense?

**Comment by mcanouil** [comment]
To note, inline R expression for date is a "`knitr` hack".
Quarto provides everything you need to define the date dynamically, see <https://quarto.org/docs/reference/dates.html>.

**Comment by racing-focus** [comment]
Hi,

The date when you use r Sys.time() does not transfer to the index page of the blog. Nothing on the link you posted tells me why the date on a blog doesn't transfer to the index page of the blog when I would like to use r Sys.time().

I don't think I am after a format?


Cheers,

**Comment by mcanouil** [comment]
Indeed, as I said, you should not use inline expression in YAML, in particular date, use:

```yaml
date: today
```

See <https://quarto.org/docs/reference/dates.html>.

**Comment by cderv** [comment]
@dragonstyle should there be a follow up to https://github.com/quarto-dev/quarto-cli/commit/f0f04bb10baccc14d4e45113078c1174135f7ad1 as it seems it won't work in some cases like index pages ? 

Or should we disallow using inline expression in YAML field like date ? 
This would avoid confusion for sure and quarto offers a new good way to do it.

**Comment by racing-focus** [comment]
thank you, I never quite understood it could be as simple as writing 

```{r}
date: today
```

Online searches and stack hadn't thrown that up to use. My bad.

Cheers,

**Comment by mcanouil** [comment]
The best documentation is the actual documentation which we linked several times here and in the discussion thread.
