### ISSUE TITLE
VSCode browser preview updates to wrong URL after reload

### ISSUE THREAD

**Issue by m-guggenmos** [quarto-dev/quarto-cli#6409]
Transferring from https://github.com/quarto-dev/quarto-cli/discussions/6330

Steps to reproduce:

`_quarto.yml`
```
project:
  output-dir: _slides
  render:
    - test.qmd

title: "Title"
author: "John Doe"

format: revealjs
```

`test.qmd`
```
## Heading

Text

## Heading2

Text

## Heading3

Text

## Heading4

Text
```

Quarto settings:
Quarto > Render: Preview Type: internal

1. Start preview, e.g. by clicking "Render" in VSCode on the `test.qmd` file. 
2. Navigate to Heading4 (-> the URL correctly updates to `test.html#/heading4`)
3. Make a change to the text in `test.qmd` under `## Heading4`. Save file.
4. If "Render on save" is enabled, the website preview refreshes automatically. The browser either jumps back to the title page (the URL also changes to the title page's URL/anchor) or to the previous slide and I can't live monitor the changes I have made to the current slide with Heading4. The same issue occurs without "Render on save" when manually clicking the preview browser's reload button.

With a bit further testing after the discussion, I realized that there seems to be a mechanism behind the scenes which monitors in which slide a change has been made and the browser jumps to this place. However, with the above example, this mechanism seems to get it wrong "by one slide" and that's why it often jumps to the previous slide. Even this behavior is not super consistent for me though. Sometimes this mechanism doesn't work at all and it just reloads the present slide irrespective of where the change has been made. Sometimes it jumps back to the first slide. In my limited testing time I couldn't pinpoint this exactly.

VSCode version 1.80.1
Quarto Extension v1.90.0
OS: Ubuntu Linux

**Comment by mcanouil** [comment]
@m-guggenmos Indeed, could you open a new issue in this repository (Quarto CLI) following the template preferably to track this potential bug.
Thank you!
