### ISSUE TITLE
Preview  (but not render) sometimes do  not use  quarto extension when running non-default profile

### ISSUE THREAD

**Issue by danieltomasz** [quarto-dev/quarto-cli#6414]
### Bug description

Below my minimalized thesis project (without my files)
[test-vault.zip](https://github.com/quarto-dev/quarto-cli/files/12244949/test-vault.zip)

The problem:

```quarto preview --profile thesis```

and 

```
quarto render --profile thesis 
```

give me different result; quarto 

I installed template from  https://github.com/nmfs-opensci/quarto-thesis which I didn't updated;

The new version of the extension  from github render fine, but I made my own custom edits so I don't want to reinstall it 

I am sharing a problematic  profile thesis`  and default one, others works as expected;

### Steps to reproduce

1. Download zip file with project
2. Run both commands
- `quarto preview --profile thesis` & open the pdf 
- `quarto render --profile thesis` &  open & compare with the output pdf ( pdf could be renamed)
3. The output is different, quarto preview doesn't use installed template `quarto-thesis-pdf` instead it switches to settings from `_quarto.yml` formatting

### Expected behavior

Preview will pick the extension and not switch to tex settings from `_quarto.yml` 

### Actual behavior

Output is different:

![image](https://github.com/quarto-dev/quarto-cli/assets/7980381/cd0416c1-9a19-4c22-a7b4-d90dbead6792)

vs

![image](https://github.com/quarto-dev/quarto-cli/assets/7980381/5c3dc60b-dade-4fc6-b09d-ca378c90706e)

### Your environment

- OS MAcOS 13.4

### Quarto check output

Both latest beta 1.4 and latest stable 1.3 give me the same results

Potentially related issues(?):
https://github.com/quarto-dev/quarto-cli/issues/4469

**Comment by danieltomasz** [comment]
```quarto render --profile thesis``` actually render with the first xelatex run the same un-templated output as ```quarto preview```, only in second xelatex run it picks the template/extension

**Comment by danieltomasz** [comment]
renaming the profile '_quarto-thesis.yml` to `_quarto.yml` fixes the error (both `render` and  `preview` give supposed output) but the bug in quarto is evident

**Comment by danieltomasz** [comment]
Switche the profile name to `_quarto-thesis.yml` again reintroduce the bug

**Comment by danieltomasz** [comment]
I dont know if this is related, but running profile thesis quite often I was receiving this error
```
ERROR: Executed file not found for book item: index.qmd

Error: Executed file not found for book item: index.qmd
    at file:///Applications/quarto/bin/quarto.js:99015:23
    at Array.reduce (<anonymous>)
    at mergeExecutedFiles (file:///Applications/quarto/bin/quarto.js:98954:34)
    at async renderSingleFileBook (file:///Applications/quarto/bin/quarto.js:98927:30)
    at async Object.onComplete (file:///Applications/quarto/bin/quarto.js:98906:48)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:86654:16)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:86800:25)
    at async serveProject (file:///Applications/quarto/bin/quarto.js:103193:26)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:103749:13)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)
```
even if index.qmd was present  whole time, running another profile usually fixed it   when I run again the thesis profile

**Comment by mcanouil** [comment]
I am a bit lost in all your posts, could you summarise and share a Git repository?

**Comment by danieltomasz** [comment]
Thanks for feedback, I will try to create an repo out of this example
( sorry for chaos, I was figuring out what was going out while writing, basically my pdf-template-extension set in my `_quarto-thesis.yml` is ignored when I run `quarto preview --profile thesis` (and the pdf settings looks like they are picked from my basis `_quarto.yml`,

 Preview  works as expected when I rename `_quarto-thesis.yml`  profile and replace  with it the default  `_quarto.yml` (extension is picked).

I will try to provide reproducible example aas git repo.

**Comment by Sciemon** [comment]
> I dont know if this is related, but running profile thesis quite often I was receiving this error
> 
> ```
> ERROR: Executed file not found for book item: index.qmd
> 
> Error: Executed file not found for book item: index.qmd
>     at file:///Applications/quarto/bin/quarto.js:99015:23
>     at Array.reduce (<anonymous>)
>     at mergeExecutedFiles (file:///Applications/quarto/bin/quarto.js:98954:34)
>     at async renderSingleFileBook (file:///Applications/quarto/bin/quarto.js:98927:30)
>     at async Object.onComplete (file:///Applications/quarto/bin/quarto.js:98906:48)
>     at async renderFiles (file:///Applications/quarto/bin/quarto.js:86654:16)
>     at async renderProject (file:///Applications/quarto/bin/quarto.js:86800:25)
>     at async serveProject (file:///Applications/quarto/bin/quarto.js:103193:26)
>     at async Command.fn (file:///Applications/quarto/bin/quarto.js:103749:13)
>     at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)
> ```
> 
> even if index.qmd was present whole time, running render the same profile fixed it so I could run preview again

If your issue is similar to mine, then what might help is using different `output-file` names in the yaml for the various formats, e.g.:

```
format:
  revealjs:
    output-file: reveal 
  html:
    output-file: html
```

**Comment by danieltomasz** [comment]
Yes ,I quite often received this error, the output files were named differently in different profiles (but  in the same format)

**Comment by cscheid** [comment]
I'm going to go ahead and close this one since we don't have a repro case. If you can provide one please comment and we'll reopen.
