### ISSUE TITLE
In PDF output, table caption breaks when using kableExtra::kable_styling(full_width = TRUE)

### ISSUE THREAD

**Issue by ulyngs** [quarto-dev/quarto-cli#6417]
### Bug description

When using `full_width = TRUE` from kableExtra, then table caption breaks

### Steps to reproduce

````
---
format: pdf
---

```{r}
#| label: tbl-results1
#| tbl-cap: "This caption doesn't show up"
mtcars[,1:3] |> 
    knitr::kable() |> 
    kableExtra::kable_styling(full_width = TRUE)
```
````

Gives this

<img width="612" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/23137032/db4f0e6b-5ed4-4856-921c-b721786e5f22">

### Expected behavior

Table caption should show up as normal...

here's with full_width = FALSE

<img width="394" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/23137032/df1a9c8f-d654-49f3-ad31-4fb2916afc3f">

### Actual behavior

It doesn't...

### Your environment

- RStudio 2023.06.1+524
- OS: MacOS 13.4.1 

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.8
      Path: /usr/local/opt/python@3.10/bin/python3.10
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Closing this as duplicate:

- #5138

**Comment by mcanouil** [comment]
@ulyngs Thanks for the report.

I confirm the described behaviour on the latest development version of Quarto for pdf/latex.
To note, this bug seems to be there since at least v1.1.

**Comment by cderv** [comment]
I believe this is fixed 

````markdown
---
format: pdf
---

```{r}
#| label: tbl-results1
#| tbl-cap: "This caption doesn't show up"
mtcars[,1:3] |> 
    knitr::kable() |> 
    kableExtra::kable_styling(full_width = TRUE)
```

````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/0dac4373-182a-4eb2-98dd-ed9334cf1de4)


````markdown
---
format: pdf
---

```{r}
#| label: tbl-results1
#| tbl-cap: "This caption doesn't show up"
mtcars[,1:3] |> 
    knitr::kable() |> 
    kableExtra::kable_styling(full_width = FALSE)
```

````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/fd519ba4-036f-4d2c-9d48-6dad4278200a)
