### ISSUE TITLE
Quarto Pub dropping the slug for website pages

### ISSUE THREAD

**Issue by rressler** [quarto-dev/quarto-cli#6425]
### Bug description

This just seems to have started this afternoon. I have quarto pub sites for a "personal website" and for two "books".

If I make any of them the default site for quarto pub, then the links in the TOC work.

However, the other two (non-default sites) will show the top level page (index) but all links in the TOC drop the slug from the index and return a page not found error.

If I switch the default site to one of the other two, then the new default works fine but the other two do not work.

One site is published on both netlify and quarto from the same repo and the netlify site works fine.

Appreciate any suggestions,
Richard
 

### Steps to reproduce

Change default site for quarto pub.

_publish.yml
- source: project
  quarto-pub:
    - id: 0c432f40-fccd-4267-ad39-9743db75428c
      url: 'https://rressler.quarto.pub/data-413-613'

### Expected behavior

The slug should be in the TOC links as before.

### Actual behavior

Non-default sites for books and web sites (not presentations) drop the slug from the links so return page not found error.

### Your environment

RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-06) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.16 (Conda)
      Path: /Users/rressler/Library/r-miniconda-arm64/envs/r-reticulate/bin/python
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/rressler/Library/CloudStorage/OneDrive-american.edu/Courses/DATA-413-613/lectures_book/renv/library/R-4.3/aarch64-apple-darwin20
        - /Users/rressler/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.3/aarch64-apple-darwin20/84ba8b13
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
See:

- #6419

**Comment by rressler** [comment]
Thanks,
I did not see this as I searched for slug!
Thanks,
Richard

From: Mickaël Canouil ***@***.***>
Date: Thursday, August 3, 2023 at 5:56 PM
To: quarto-dev/quarto-cli ***@***.***>
Cc: Richard Ressler ***@***.***>, Author ***@***.***>
Subject: Re: [quarto-dev/quarto-cli] Quarto Pub dropping the slug for website pages (Issue #6425)

External Email: Use caution with links and attachments.

See:

  *   #6419<https://urldefense.com/v3/__https:/github.com/quarto-dev/quarto-cli/discussions/6419__;!!IaT_gp1N!3iFQSmgfvXayHgxFvZuYTG48pLfIdk-0Se1VfTD2bl9YGeex7EQlJ5-OcRPtcXCB4GopZkwgRFyDM7_HMeLvN0x8Uzk$>

**Comment by dragonstyle** [comment]
This should be resolved now (it appears to be from checking the linked website). Sorry for the hiccup and thank you for reporting it!

I'm closing this assuming all is well but please feel free to re-open if you notice issues.

**Comment by rressler** [comment]
Looks good, thanks!
