### ISSUE TITLE
external link icon and tool items

### ISSUE THREAD

**Issue by ChristopherBarrington** [quarto-dev/quarto-cli#6432]
### Bug description

An external link icon can be shown next to a tool's icon in the sidebar.

![image](https://github.com/quarto-dev/quarto-cli/assets/7288036/16625a50-00fb-48da-a24c-a8cd7cd66817)

### Steps to reproduce

With the following config options:

```
format:
  html:
    link-external-icon: true

website:
    tools:
      - icon: google
        url: https://google.co.uk
      - icon: tools
        url: internal/page
```

### Expected behavior

The external link icon should be suppressed when showing a tool icon. It is good to include in main text to make it clear but next to icons it is cluttered and confusing

### Actual behavior

There are two icons

### Your environment

- Sublime Text
- Mac OS Ventura

### Quarto check output

```bash
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.58.3: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/miniconda3/envs/r-4.3.1/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /opt/miniconda3/envs/r-4.3.1/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /opt/miniconda3/envs/r-4.3.1/lib/R
      LibPaths:
        - /path/to/new-project/renv/library/R-4.3/x86_64-apple-darwin13.4.0
        - /path/to/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.3/x86_64-apple-darwin13.4.0/88f79fa1
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report.
Although your example is not reproducible as the `tools` key is misplaced.

**Comment by ChristopherBarrington** [comment]
sorry yes - I missed a level in the yaml but left the spacing. I was using the sidebar but it also happens in the navber as your example shows, thanks.

**Comment by dragonstyle** [comment]
These should be properly handled in the most recent version of Quarto pre-release builds.
