### ISSUE TITLE
Hello, Quarto VS Code tutorial - mention installing jupyter extension?

### ISSUE THREAD

**Issue by garrettgman** [quarto-dev/quarto-cli#6437]
### Bug description

When I followed the instructions from the [Hello, Quarto VS Code tutorial](https://quarto.org/docs/get-started/hello/vscode), I ran into a bug mentioned [here](https://github.com/quarto-dev/quarto/issues/104#issuecomment-1666223668). The Run Cell buttons did not work as in the tutorial because I didn't have the Jupyter extension installed. Installing the extension fixed the bugs.

**If the Jupyter extension is a requirement for the Run Cell button, should we amend the tutorial to tell readers to install it?**

### Steps to reproduce

1. Don't have the jupyter VSCode extension installed
2. Follow the [Hello, Quarto VS Code tutorial](https://quarto.org/docs/get-started/hello/vscode)
3. When the tutorial tells you to click the Run Cell buttons, notice that they do not work

### Expected behavior

The tutorial should instruct users to install the Jupyter extension, likely right around where it tells them to install the Quarto extension

### Your environment

- OS: Mac Monterrey 12.6.3
- VSCode: 1.80.2

### Quarto check output

Checking Quarto installation......OK
      Version: 1.0.37
      Path: /Applications/quarto/bin

(|) Checking basic markdown re(/) Checking basic markdown re(-) Checking basic markdown re(\) Checking basic markdown re(|) Checking basic markdown re(/) Checking basic markdown re(-) Checking basic markdown re(\) Checking basic markdown re(|) Checking basic markdown re
[✓] Checking basic markdown render....OK

(|) Checking Python 3 installa(/) Checking Python 3 installa(-) Checking Python 3 installa(\) Checking Python 3 installa(|) Checking Python 3 installa(/) Checking Python 3 installa(-) Checking Python 3 installa(\) Checking Python 3 installa
[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /Users/garrettgrolemund/Desktop/quarto-tutorial/.venv/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

(|) Checking Jupyter engine re(/) Checking Jupyter engine re(-) Checking Jupyter engine re(\) Checking Jupyter engine re(|) Checking Jupyter engine re(/) Checking Jupyter engine re(-) Checking Jupyter engine re(\) Checking Jupyter engine re(|) Checking Jupyter engine re(/) Checking Jupyter engine re(-) Checking Jupyter engine re(\) Checking Jupyter engine re(|) Checking Jupyter engine re(/) Checking Jupyter engine re(-) Checking Jupyter engine re(\) Checking Jupyter engine re(|) Checking Jupyter engine re(/) Checking Jupyter engine re(-) Checking Jupyter engine re(\) Checking Jupyter engine re(|) Checking Jupyter engine re(/) Checking Jupyter engine re(-) Checking Jupyter engine re(\) Checking Jupyter engine re(|) Checking Jupyter engine re(/) Checking Jupyter engine re(-) Checking Jupyter engine re(\) Checking Jupyter engine re(|) Checking Jupyter engine re(/) Checking Jupyter engine re(-) Checking Jupyter engine re(\) Checking Jupyter engine re(|) Checking Jupyter engine re(/) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
(-) Checking Jupyter engine re(\) Checking Jupyter engine re(|) Checking Jupyter engine re
[✓] Checking Jupyter engine render....OK

(|) Checking R installation...(/) Checking R installation...(-) Checking R installation...(\) Checking R installation...(|) Checking R installation...
[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.21

(|) Checking Knitr engine rend(/) Checking Knitr engine rend(-) Checking Knitr engine rend(\) Checking Knitr engine rend(|) Checking Knitr engine rend(/) Checking Knitr engine rend(-) Checking Knitr engine rend(\) Checking Knitr engine rend(|) Checking Knitr engine rend(/) Checking Knitr engine rend
[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
I made a PR to add a note about the Jupyter extension required to run code cell when using Jupyter as the engine.

- https://github.com/quarto-dev/quarto-web/pull/803

**Comment by jjallaire** [comment]
Thanks for reporting this! I has assumed that this extension was installed automatically in VS Code but it's not. I've declared a dependency here so that it is indeed always installed: https://github.com/quarto-dev/quarto/commit/7a94f8c769091bceb1853a1ffa2c0c61b3625a1f
