### ISSUE TITLE
support creating special counter scopes for crossrefs

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#644]
e.g. for something like this: http://bytesizebio.net/2013/03/11/adding-supplementary-tables-and-figures-in-latex/

See also this discussion: https://github.com/quarto-dev/quarto-cli/discussions/609

**Comment by grasshoppermouse** [comment]
The ability to separately number supplementary figures/tables is the most important feature I'm missing in rmarkdown.

**Comment by pagyeman** [comment]
Agree.
Quarto is really great. But when preparing medical publications i miss the possibility to add correct labels for supplementary tables, figures and potentially other Material (e.g. ref to sections in Supplement).

**Comment by jjallaire** [comment]
Yes, we are definitely going to tackle this over the next few months!

**Comment by timwoelfle** [comment]
That's great to hear! Do you have an estimate on when this will arrive? There doesn't seem to be a milestone attached yet. Keep up the great work!

**Comment by cscheid** [comment]
(#4944)

**Comment by cscheid** [comment]
This is now available in our pre-release version. We'll have extensive docs by the time the release comes out (in a few months), but in the meantime, here's a bare-bones documentation page.
