### ISSUE TITLE
Documentation for variable `beamerarticle` in wrong section

### ISSUE THREAD

**Issue by PeterWang-dev** [quarto-dev/quarto-cli#6445]
### Bug description

> In the documentation, the variable beamerarticle is under the beamer section of variables. However, in the templates, it is only loaded if the output type is latex (article), not beamer. So really this variable should be under the latex variables. If the option beamerarticle is given when the output format is given as beamer, it does nothing. If the variable is given with the output format as latex, then you get what you want.

For Quarto, when using `beamerarticle` in beamer option, it is not that "does nothing", but doesn't compile at all, as `beamerarticle` redefines `{frametitle}`. Documentation here is really misleading.

See also: [Issue in pandoc](https://github.com/jgm/pandoc/issues/7874)

### Steps to reproduce

<img width="967" alt="图片" src="https://github.com/quarto-dev/quarto-cli/assets/59994316/562aceb2-f828-462d-93cd-5a9b2f378ea8">

### Expected behavior

`beamerarticle` variable should in pdf section

### Actual behavior

`beamerarticle` variable now in beamer section which is really confusing.

### Your environment

- IDE: VSCode
- OS: Arch Linux `Linux 6.4.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023 16:01:52 +0000 x86_64 GNU/Linux`

### Quarto check output

```bash
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.294
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
@dragonstyle I just noticed you fixed this, so #6456 could be closed 😅
