### ISSUE TITLE
Non-root path website problem

### ISSUE THREAD

**Issue by reuning** [quarto-dev/quarto-cli#6453]
### Bug description

This is a a [follow up to this post](https://github.com/quarto-dev/quarto-cli/discussions/3615).  

As mentioned in the discussion there is [one issue](https://github.com/quarto-dev/quarto-cli/discussions/3615#discussioncomment-5242541) where the loaded scripts do not have the relative URLs fixed. You can see this in: 

```
<script src="site_libs/quarto-nav/quarto-nav.js"></script> 
<script src="site_libs/clipboard/clipboard.min.js"></script> 
<script src="site_libs/quarto-search/autocomplete.umd.js"></script> 
<script src="site_libs/quarto-search/fuse.min.js"></script>
```

This leads to a problem where you the URL works fine as long as there is a backslash at the end. Try https://kevinreuning.com/presentations/ vs https://kevinreuning.com/presentations

If you want more of an MWE let me know the relevant part of the yaml is:

```
website:
  title: "Presentations"
  site-url: "https://kevinreuning.com/presentations/"
```

**Comment by mcanouil** [comment]
Would you mind sharing a reproducible example? (preferably as a Git repository in this case)

**Comment by reuning** [comment]
I tried putting one together here: https://github.com/reuning/quarto_root_url_demo/

**Comment by cscheid** [comment]
@reuning I don't believe this is something we can solve on our side. I explain the situation [here](https://github.com/quarto-dev/quarto-cli/issues/5267#issuecomment-1675138776).

**Comment by reuning** [comment]
Okay, thanks for the info @cscheid.
