### ISSUE TITLE
div syntax for content that is included for only certain formats

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#646]
Would likely want to support our format aliasing shortcuts as seen here: https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/schema/format-aliases.yml

**Comment by cscheid** [comment]
Yup. Once we have the "xml component syntax", this is pretty straightforward for me to implement. We'll get it together with the include functionality.

**Comment by cderv** [comment]
For reference, some discussion about this kind of feature in https://github.com/quarto-dev/quarto-cli/discussions/373 I believe

**Comment by cscheid** [comment]
This is now supported with `.content-hidden`, `.content-visible`, `when-format` and `unless-format`. Examples:

    ::: {.content-hidden when-format="pdf"}
    This will not appear in a PDF
    :::

    ::: {.content-visible unless-format="docx"}
    This will not appear in word output
    :::

    ::: {.content-hidden unless-format="html"}
    This will only be visible in HTML output
    :::

**Comment by cderv** [comment]
Awesome ! Thanks!
