### ISSUE TITLE
Invalid cross-device link when output-dir is not on same device as the source file

### ISSUE THREAD

**Issue by grst** [quarto-dev/quarto-cli#6466]
I have the source code of the quarto project checked out in my home directory. I want the rendered report to be stored on a shared group drive that is on a different network mount than my home directory. Therefore I render the document with

```bash
quarto render analysis.qmd --to html --embed-resources --standalone --output-dir /shared_data/analysis.html
```

This results in the following error 

```
ERROR: Invalid cross-device link (os error 18), rename '/home/sturmgre/<path redacted>/analysis.html' -> '/data/<path redacted>/analysis.html'

Error: Invalid cross-device link (os error 18), rename '/home/sturmgre/<path redacted>/analysis.html' -> '/data/<path redacted>/analysis.html'
    at Object.renameSync (deno:runtime/js/30_fs.js:175:9)
    at renderProject (file:///home/sturmgre/apps/quarto/bin/quarto.js:86845:22)
    at async Command.fn (file:///home/sturmgre/apps/quarto/bin/quarto.js:90869:32)
    at async Command.execute (file:///home/sturmgre/apps/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///home/sturmgre/apps/quarto/bin/quarto.js:127555:5)
    at async file:///home/sturmgre/apps/quarto/bin/quarto.js:127573:9
```

**Comment by mcanouil** [comment]
I cannot reproduce using the development version of Quarto.
To note, `--output-dir` is only a valid option within a Quarto project which means the presence of `_quarto.yml` that you did not provide.

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by grst** [comment]
The following reproduces the problem for me
```bash
ANALYSIS_DIR=/home/sturmgre/quarto-test
DATA=/data/test

cd $ANALYSIS_DIR
echo "Hello World" > test.qmd
touch _quarto.yml

# Creating a hard link should fail - this is to test that the two devices are really independent
ln test.qmd $DATA/test.qmd
```
```
ln: failed to create hard link ‘/data/clinbias_data6/tmp_sturmgre//test.qmd’ => ‘test.qmd’: Invalid cross-device link
```
```bash
quarto render test.qmd --to html --standalone --embed-resources --output-dir $DATA
```
```
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en

ERROR: Invalid cross-device link (os error 18), rename '/home/sturmgre/transient/quarto-test/test.html' -> '/data/clinbias_data6/tmp_sturmgre/test.html'

Error: Invalid cross-device link (os error 18), rename '/home/sturmgre/transient/quarto-test/test.html' -> '/data/clinbias_data6/tmp_sturmgre/test.html'
    at Object.renameSync (deno:runtime/js/30_fs.js:175:9)
    at renderProject (file:///home/sturmgre/apps/quarto/bin/quarto.js:86845:22)
    at async Command.fn (file:///home/sturmgre/apps/quarto/bin/quarto.js:90869:32)
    at async Command.execute (file:///home/sturmgre/apps/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///home/sturmgre/apps/quarto/bin/quarto.js:127555:5)
    at async file:///home/sturmgre/apps/quarto/bin/quarto.js:127573:9
```

Tested with both `v1.3.427` and the latest development version.

**Comment by mcanouil** [comment]
I still can't reproduce and don't understand the goal of trying to hard link the file.
Below my reproducible example (_i.e._, yours is not):
```sh
echo "Hello World" > test.qmd
touch _quarto.yml
mkdir /tmp/test
quarto render test.qmd --to html --standalone --embed-resources --output-dir /tmp/test
```
<img width="1423" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/63dbaa81-a9de-4e16-ba03-6eac65c2becf">


Is `DATA=/data/test` a local drive/volume?

**Comment by grst** [comment]
Executing your reproducible example leads to exactly the same error for me. 

My point was that `$DATA` and `$HOME` are different network volumes. Therefore it's not possible to create a hard link between them. 

What happens if you try creating a hard link to your `/tmp` directory? 
```
ln test.qmd /tmp/test
```

Depending on you system, `/tmp` may or may not be an independent volume and therefore not suitable to reproduce my issue.

**Comment by mcanouil** [comment]
>Executing your reproducible example leads to exactly the same error for me.

Your home is not on the same volume as `/tmp`?

---

Because, as I said, `--output-dir` is for Quarto project and is not designed for simple document (see #2171), you should consider using `quarto render test.qmd --to html --standalone --embed-resources && mv test.html $DATA/`.

**Comment by grst** [comment]
> Your home is not on the same volume as /tmp

No, on the server I'm working on `/tmp` is  stored entirely in RAM. 

> You seem to imply, if you use an output directory within the same volume, it works, but is it?

Exactly, if I use 

```
quarto render test.qmd --to html --standalone --embed-resources --output-dir ..
```

it works flawlessly. Sorry if this hasn't been clear before.

**Comment by mcanouil** [comment]
Still without the means to reproduce, it's very unlikely the issue can be solved.
