### ISSUE TITLE
Quarto + Docusaurus: Charts from Mathplotlib Only Render in PDF (Broken in HTML)

### ISSUE THREAD

**Issue by krishaamer** [quarto-dev/quarto-cli#6468]
### Bug description

It seems to be a simple wrong url issue. The charts are created inside a "design_files" folder however the img src inside the html is incorrect.

### Your environment

- Quarto 1.3.296

**Comment by mcanouil** [comment]
Thanks for the report!

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by krishaamer** [comment]
@mcanouil I tested with v.1.4.322 and it has been fixed meanwhile however I'm stuck at v.1.3.326 (where it's still broken) because of https://github.com/quarto-dev/quarto-cli/issues/6046

**Comment by mcanouil** [comment]
Thanks for the update.
I am closing this as resolved then.

**Comment by krishaamer** [comment]
Well it's still broken for me

**Comment by mcanouil** [comment]
You are confusing me ...
If the issue does not exist in current pre-release version, then it is fixed.
You not wanting to upgrade due to other issue is unrelated and unfortunate.
To note, you are not on the latest stable 1.3 version of Quarto.

**Comment by krishaamer** [comment]
From me as the user perspective the various issues related to Docusaurus need to be fixed before you could announce as officially supporting it. Docusaurus kinda works until v.1.3.326 .

**Comment by mcanouil** [comment]
Still, this issue is fixed as you said.
Software version are never overwritten with patches. So you version will never be fixed, _i.e._ an update/upgrade will always be required as for any software.

This issue is not about docusaurus support.
