### ISSUE TITLE
self-contained revealjs slide cannot be displayed

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#648]
I have noticed that slides previously rendered (quarto 0.9.120) cannot be displayed when rendered again with the latest version (quarto 0.9.256).

The HTML file contains links to `index_files` that does not exist with the `self-contained: true` option.

**Comment by jjallaire** [comment]
I can repro this and I believe I know the cause.

@dragonstyle We are injecting plugins by post-processing HTML but this evades Pandoc's automatic downloading. I think we do in fact need to patch the reveal template after all.

**Comment by dragonstyle** [comment]
This should be fixed as of this commit:

d0d50d0f7fcb78cbec897e790238318ccb273f2c

I have started a new release and it should be ready in a few minutes!

**Comment by eitsupi** [comment]
quarto 0.9.260 works again, thanks for your quick fix!
