### ISSUE TITLE
qmd file containing mermaid diagram cannot be rendered into a pdf file (Updated)

### ISSUE THREAD

**Issue by likanzhan** [quarto-dev/quarto-cli#6481]
### Steps to reproduce

1. To build a minimal example, create a qmd file named `intro.qmd`, containing only the following `mermaid` code block:

````qmd
```{mermaid}
graph TD
  A[ Anyone ] --> | Can help | B( Go to github.com/yuzutech/kroki )
  B --> C{ How to contribute? }
  C --> D[ Reporting bugs ]
  C --> E[ Sharing ideas ]
  C --> F[ Advocating ]
```
````

Here is the zipped [intro.qmd.zip](https://github.com/quarto-dev/quarto-cli/files/12327326/intro.qmd.zip) file

2. In the terminal, set the directory containing the qmd file as the current directory.
3. When I run `quarto preview intro.qmd` in the terminal, I can get the expected diagram in my browser. 
4. When I run `quarto render intro.qmd --to pdf` in the terminal, I expect to obtain an pdf file containing the diagram.
5. But the terminal is stuck in the command, no error is printed and no pdf file is obtained.

### Your environment

OS: MacOS Ventura 13.4.1 (c) 
chip: Apple M1 Max

### Quarto check output

```bash
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12 (Conda)
      Path: /Users/likanzhan/.julia/conda/3/x86_64/bin/python
      Jupyter: 5.3.1
      Kernels: julia-1.8, julia-1.9, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report.

This seems to be a duplicate of:

- https://github.com/quarto-dev/quarto-cli/issues/3052

**Comment by cscheid** [comment]
I'm on a very similar machine/OS and cannot reproduce this:

<img width="192" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/48c23882-deb8-4118-bb16-3d80be4a666f">

<img width="1677" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/a0fab561-ea3c-41c0-8fe7-f0125437ac84">

**Comment by likanzhan** [comment]
@cscheid 

Thanks for the responses.
Is the format of your output PDF? Thanks

**Comment by mcanouil** [comment]
It is a PDF that is previewed in the screenshot.

**Comment by likanzhan** [comment]
@mcanouil @cscheid 

Thanks, what could possibly be reason in my case?

**Comment by mcanouil** [comment]
Anything you did not tell use 🤷‍♂️
Your example is not a full Quarto document for starters.
Make sure to try in a new empty directory.

Also, I am pretty sure Carlos is using TinyTex which can be installed by Quarto.

**Comment by likanzhan** [comment]
I didn't use TinyTex.
But even if I used 
`quarto install tool tinytex`
  `quarto install tool chromium`
to installed the two tools, the problem persists.

PS, I created a new empty directory.

**Comment by mcanouil** [comment]
@likanzhan I realise that your issue title mentioned "md" but in your issue description you mentioned qmd files.
Could you provide a fully reproducible example and not just mermaid code?

**Comment by likanzhan** [comment]
@mcanouil, I've updated my description. Please let me know if I didn't make myself clear. Thanks.

**Comment by cscheid** [comment]
Is it possible that you don't have Chrome installed? That's one code path that could make a difference.

**Comment by likanzhan** [comment]
@cscheid. The chrome is installed. Here is an updated output of `quarto check` after I installed the prereleased quarto:

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.315
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/likanzhan/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12 (Conda)
      Path: /Users/likanzhan/.julia/conda/3/x86_64/bin/python
      Jupyter: 5.3.1
      Kernels: julia-1.9, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK

```

**Comment by mcanouil** [comment]
Would you be able to try in a Docker container?
As currently we can't reproduce your issue, it's likely about something in your setup that causes this.

**Comment by mcanouil** [comment]
Did you try to install the library and see if it solves the issue?

**Comment by cderv** [comment]
> When I intend to draw the diagram with the `julia` interface:
> 
> ```
> ```{julia}
> using Kroki
> Diagram(:mermaid, """
> graph TD
>   A[ Anyone ] --> | Can help | B( Go to github.com/yuzutech/kroki )
>   B --> C{ How to contribute? }
>   C --> D[ Reporting bugs ]
>   C --> E[ Sharing ideas ]
>   C --> F[ Advocating ]
> """)
> ```
> ```
> 
> I got the following error:
> 
> ```
> FATAL (/Applications/quarto/share/filters/main.lua:4879) An error occurred:
> Could not convert a SVG to a PDF for output. Please ensure that rsvg-convert is available on the path.
> ```
> 
> Is this related to the problem when I use `mermaid` directly?
> 
> Thanks

About this one @likanzhan , this is different than initial issue because 

* You are using a specific Julia Package to draw diagrams
* This package will generate for your by default some .svg content
* Showing .svg content in a PDF document is not possibly without converting it
* As the error tells you, you need a tool `rsvg-convert` to do that ( `"Please ensure that rsvg-convert is available on the path."`) 

Using Julia, you could either 
* Install `rsvg-convert` to allow the conversion to happen
* Configure your tool Kroki to output something compatible with PDF 

The initial issue is about PDF rendering of mermaid diagram through Quarto supports, this implies a Chrome print of the diagram to include as image. I believe this is where something is not right, and possibly a duplicate as already mentioned above: https://github.com/quarto-dev/quarto-cli/issues/6481#issuecomment-1672521910

**Comment by cscheid** [comment]
I'm closing this stale issue. Please reopen with the necessary information if you want to.
