### ISSUE TITLE
SQL code chunks not evaluated correctly

### ISSUE THREAD

**Issue by jmehringer-iis** [quarto-dev/quarto-cli#6483]
### Bug description

When executing a SQL code chunk, it won't be evaluated correctly UNLESS I include a R code chunk 

### Steps to reproduce

this fails:

````qmd

---
title: "Untitled"
format: pdf
---


```{sql}
#| eval: false
#| code-fold: true
#| code-summary: "Show the code"
SELECT 1 FROM *
```
````

but this works:

````qmd
---
title: "Untitled"
format: pdf
---


```{r}
#| eval: false
#| include: false

# Quarto and sql chunks will need another chunk before execution
```

```{sql}
#| eval: false
#| code-fold: true
#| code-summary: "Show the code"
SELECT 1 FROM *
```
````

### Expected behavior

The code chunk should be evaluated correctly, and syntax should be formatted like SQL

![grafik](https://github.com/quarto-dev/quarto-cli/assets/126784821/2e783562-19c3-401d-bb45-5ebf6ec2c09a)

### Actual behavior

Instead, Quarto prints the code chunk, but does not include syntax highlighting or evaluation

![grafik](https://github.com/quarto-dev/quarto-cli/assets/126784821/93bfb726-eaa8-49f4-9ec0-ebe63acf592e)

### Your environment

- IDE: VSCode
- Debian 12

### Quarto check output

```
quarto check


[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3 (Conda)
      Path: /opt/conda/envs/dev/bin/python
      Jupyter: 5.3.0
      Kernels: python3

(\) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

(-) Checking R installation...........During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
6: Setting LC_PAPER failed, using "C" 
7: Setting LC_MEASUREMENT failed, using "C" 
[✓] Checking R installation...........OK
      Version: 4.0.4
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
SQL is not a default language of Jupyter or `knitr`.
Jupyter can support it as long as you have installed the right module first.
For `knitr`, you have to tell Quarto to use it explicitly if you don't have any R code cell.

There is no bug here.
I am closing this ahead but feel free to reopen if you do think there is a bug.

````qmd
---
title: "Untitled"
format: pdf
engine: knitr
---

```{sql}
#| eval: false
#| code-fold: true
#| code-summary: "Show the code"
SELECT 1 FROM *
```
````

**Comment by jmehringer-iis** [comment]
This definitely makes sense! Thank you for the explanation and the hint with specifying knitr as engine 👍 

I guess it would be nice to have some sort of message for the user if the engine is Jupyter and a code block is interpreted as raw text and thus printed to a document without any use of the specified language. 
Or, to install a needed package for Jupyter in the process of rendering the document. I would have never guessed that Jupyter needs a specific extension (that does not get shipped with Quarto) in order to even display a code chunk. After all, the VSCode Quarto extension allows me to choose a SQL code chunk.

But only printing the code chunk without any message or fallback was irritating, especially since `knitr` is able to provide syntax highlighting out of the box. I would expect to see the same behaviour from Jupyter, or a message.

Regarding `code-fold`: Sorry for the confusion! This just served as my showcase :) I expected it to be ignored there, but the behaviour is equivalent when rendering to `html` which is why I didn't bother with the output format. We're using Quarto in order to generate `html` and `pdf` from the same files.

**Comment by jmehringer-iis** [comment]
Ah wow, this definitely solves my issue! Didn't know about the possibility to just leave out the brackets!
Thanks a lot!

Also, I agree, checking all possible user inputs is infeasible.
As soon as a SQL query is being evaluated in the code chunk and `ipython-sql` is not installed, Jupyter will complain anyway I guess.
Again, thanks!

**Comment by jmehringer-iis** [comment]
Ah, but if specify the cell without brackets, I can't make use of `code-fold: true`; or can I somehow?

**Comment by mcanouil** [comment]
Indeed, you can't, but you can do the following:

````qmd
---
title: "Quarto Playground"
format: html
---

This is a playground for Quarto.

<details><summary>Show the code</summary>]

```sql
SELECT 
  employee_id,
  last_name,
  first_name,
  salary,
  RANK() OVER (ORDER BY salary DESC) as ranking
FROM employee
ORDER BY ranking
```

</details>
````

**Comment by jmehringer-iis** [comment]
This is magic :) Wonderful!
Thank you so much for your time and effort!
