### ISSUE TITLE
Unable to Attach Image with Observable's File Attachment function

### ISSUE THREAD

**Issue by scottfranz** [quarto-dev/quarto-cli#649]
I am using the vscode Quarto extension and I have a local .jpg file named `Cabin.jpg` and was hoping to attach it as shown in this [Observable example](https://observablehq.com/@observablehq/file-attachments).

I tried both this `image = FileAttachment("Cabin.jpg").image()` within an OJS cell.

And I tried `${await FileAttachment("Cabin.jpg").image()}` within the Quarto Markdown.

Neither option worked.  But I found a solution to displaying an image in this [Observable Notebook](https://observablehq.com/@eczajk1/convert-an-image-to-base64-data-url). 

Looks like I could copy the image address and convert the URL it to Base64 data.

```
cabinPic = 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=600&q=80'

cabin = {
  let img = new Image();
  img.crossOrigin = '*';
  img.src = cabinPic;
  await new Promise(resolve => img.addEventListener('load', resolve));
  let ctx = DOM.canvas(img.width, img.height).getContext('2d');
  ctx.drawImage(img, 0, 0);
  return ctx.canvas;
}
```
This rendered an image. As well as when I used `${cabin}` to place the image somewhere else on the page. 

But I was hoping to take advantage of Observable's `image()` function to leverage things like the [Color.js](https://github.com/luukdv/color.js) library. I was following this [Observable Notebook](https://observablehq.com/@mukhtyar/day-4-flora) when I ran into this problem. I am still not able to extract the color palette even when using the image URL. Not sure what is going on here. Any ideas?

**Comment by cscheid** [comment]
This is a current shortcoming of our observable runtime implementation.

What's going on under the hood is that we need our own implementation of `FileAttachment`. Observable's goes through their API to access the files rather than directly through direct accessing a static HTTP resource, which is what we need. But as you noticed, we are presently lacking features from their API.

It seems that Color.js requires an `img` element to work. If you absolutely need to make this work, you can hack around it by storing the image data in some format, rendering it to a canvas like you did, and then grabbing the `img` element via a data URL. This would be similar to what you did, something like this:

``` javascript
// data is something you obtained from FileAttachment, in JSON.

let ctx = DOM.canvas(data.width, data.height).getContext('2d');
// render image to ctx pixel by pixel here 
return ctx.canvas.toDataURL(); // this should return an img element
```

**Comment by scottfranz** [comment]
Ah this makes sense. Thanks for the workaround! 

I am just playing around with third-party libraries at the moment to see what I could do.

Very excited about combining R with Observable. Thanks for such great work!

**Comment by cscheid** [comment]
Hi, I'm looping back on this and I think this actually should work with our OJS runtime now. We recently updated to their more recent runtime, so perhaps that's what was causing the issue. Here's my attempt at reproducing a simple version of the notebook:

    ---
    format: html
    ---

    ```{ojs}
    //| echo: false
    flora = new Map([
    ["Abraham Darby", FileAttachment("IMG_4931.JPG")],
    ["Gertrude Jekyll", FileAttachment("IMG_4705.JPG")],
    ])
    viewof selection = Inputs.select(flora, {label: "Favorite Rose", format: x => x[0]})
    ```

    ```{ojs}
    await selection.image()
    ```

    <style>
        div.observablehq img { max-width: 100%; }
    </style>

If I `quarto render` this file in a directory with the two images from the linked notebook, I get the following output:

<img width="738" alt="image" src="https://user-images.githubusercontent.com/285675/167733233-649eb61f-cc20-45a7-be03-8e52b8d75f2b.png">

**Comment by scottfranz** [comment]
Thanks so much for the update! Awesome! I also didn't even know you could do inline CSS like that! Good to know.

**Comment by cscheid** [comment]
@scottfranz just to expand on that CSS trick: Pandoc will accept most HTML inline, which is useful for one-off hacks like this. But for larger styles, we have

```
---
format: 
  html:
    css: style.css
---
```

or

```
---
format: 
  html:
    css: [style-1.css, style-2.css, style-etc.css]
---
```
