### ISSUE TITLE
julia chunk not runable in quarto (RStudio)

### ISSUE THREAD

**Issue by durraniu** [quarto-dev/quarto-cli#6492]
### Bug description

I am trying to run R and Julia in the same quarto document. But in RStudio, I see that the julia chunk is not runnable (no 'play' button). 

### Steps to reproduce

Following are the contents of test.qmd:  

---
    title: "Untitled"
    format: html
    ---
    
    ```{r}
    1+1
    ```
    
    ```{julia}
    using DataFrames
    ```

I am not sure how to provide an example of no 'play' button for julia chunk.

### Expected behavior

There should be a 'play' button for julia chunk. And the quarto doc should render to html after clicking render.

### Actual behavior

When I click render, the process is stuck at the julia chunk. I have waited for about 15 minutes with no result.

    processing file: test.qmd
    1/5                  
    2/5 [unnamed-chunk-1]
    3/5                  
    4/5 [unnamed-chunk-2]
    Julia version 1.9.2 at location C:\Users\USERNAME\AppData\Local\Programs\JULIA-~1.2\bin will be used.
    Loading setup script for JuliaCall...

### Your environment

- OS: Windows 10
- julia 1.9.2 
- R version is 4.3.1
- quarto version is 1.3.450

**Comment by cscheid** [comment]
This is an RStudio issue; please file it over at https://github.com/rstudio/rstudio. Thanks!

**Comment by cscheid** [comment]
> Please note that I checked today and I get the same issue on VSCode also.

Thank you for being thorough; that's a separate issue to be raised at https://github.com/quarto/quarto (where the editor support code goes)
