### ISSUE TITLE
Navbar doesn't render logo and title at the same time

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-cli#65]
I updated the Quarto version in the Workbench Docker file to 0.2.34 and navbar title is no longer being printed out.

Here is the navbar render with v0.2.28:

![image](https://user-images.githubusercontent.com/6981612/127420551-02d29d15-a3a5-4732-9829-f231d2f19b65.png)

And the navbar rendered with v0.2.34:

![image](https://user-images.githubusercontent.com/6981612/127420972-c5612f00-a757-43c7-b3c3-5c6199414bbc.png)

The yaml is the same between each render. If I comment out the logo in `quarto-yml`, then the navbar title will appear:

![image](https://user-images.githubusercontent.com/6981612/127420999-c7c4ef70-e483-4e88-9a47-83a55b6f0abd.png)

### To reproduce

* clone `https://github.com/pommevilla/quarto-navbar-issue`
* `quarto serve` - the logo shows up in the navbar but the title doesn't
* Comment out the logo line in `_quarto.yml` - the site title reappears.

**Comment by jjallaire** [comment]
I made a change whereby if you include a logo then we don't automatically pull the `title` from the site YAML. I believe that if you add a `title` within the `navbar` then you'll see it again.

**Comment by jjallaire** [comment]
I am going to change this behavior so your site will continue working w/o YAML changes (I'll make opt-out for the title explicit)

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/5c35e69458cc6a93489f634e3e459c10b53857d6
