### ISSUE TITLE
\QuartoMarkdown "LaTeX" command

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#6503]
cf my comment in the discussion below,

> I wonder if Quarto could support a (fake) LaTeX command like
> 
> ```
> \QuartoMarkdown{We will convert this `Markdown` to LaTeX for you, including citations to @cite-foo and references like @fig-bar}
> ```

This would be the LaTeX equivalent of `<span data-qmd="..."></span>`, and would be useful for similar reasons: although markdown is our primary input language, we often do get HTML and LaTeX input as well, and we'd like to support as much of Quarto's features as we can.

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/6394

<div type='discussions-op-text'>

<sup>Originally posted by **avhz** August  1, 2023</sup>
### Description

I have a Latex table inside my Quarto document (PDF output), and I am trying to cite something from my bibliography, but just end up with the question marks indicating that Latex can't find my bibliography (I think). 

Citations elsewhere in my document work fine (I use the Quarto `[@citation]` format elsewhere), but using `\cite{}` does not seem to work within the Latex section (nor does the Quarto format).

The Latex table is like:

```qmd
\newcommand\ytl[2]{
    \parbox[b]{8em}{
        \hfill{\color{cyan}\bfseries\sffamily #1}~$\cdots\cdots$~
    }
    \makebox[0pt][c]{$\bullet$}\vrule\quad
    \parbox[c]{10cm}{
        \vspace{7pt}
        \color{red!40!black!80}
        \raggedright\sffamily #2 \\[7pt]
    }\\[-3pt]
}
\begin{table}[!h]
\caption{\label{timeline}Table with failing citations.}
\begin{minipage}[t]{1\linewidth}
\color{gray}
\rule{\linewidth}{1pt}
    \ytl{1995}{Attempting to cite: \cite{@citation}}            % <-- HERE
\rule{\linewidth}{1pt}
\end{minipage}
\end{table}
```

I generate my bibliography using the refs div:

```qmd
::: {#refs}
:::
```

I am not sure what else to include since citations work fine everywhere else. </div>

**Comment by cscheid** [comment]
We implemented this in `\QuartoMarkdownBase64`. We require the contents to be base64-encoded because investing in a full-blown LaTeX parser written in Lua is not feasible for us. Since this is designed to be used by libraries emitting content computationally, it's not an issue to require the use of a base-64 parser. See https://quarto.org/docs/prerelease/1.4/ast.html

**Comment by sebacea** [comment]
I would like to share a comment that I think is related to this issue. Maybe I am a bit lost, but It will be interesting to have support to include raw latex with cross-references and citations. For instance if I use:

```{=latex}
\input{document.tex}
```

where `document.tex` has:

```
This is a citation of \cite{key}.
```

I don't get the citation.

**Comment by cscheid** [comment]
> Maybe I am a bit lost, but It will be interesting to have support to include raw latex with cross-references and citations

We're not going to do that. It would require us to be able to parse LaTeX in full generality while processing the document in Lua. As mentioned above:

> We require the contents to be base64-encoded because investing in a full-blown LaTeX parser written in Lua is not feasible for us.

**Comment by cscheid** [comment]
With that said, the following _does_ work, so I'm not sure what's going with your document:

### 6503.qmd

````
---
format: pdf
---

::: {#fig-1}

This is a figure.

This is a caption.

:::

In @fig-1, you can see that this markdown citation works.

```{=latex}
\input{document.tex}
```
````

## document.tex

````
See \ref{fig-1}.
````

## Output

<img width="788" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/fdc12075-cc95-4da7-90b7-33e19eba21dc">

**Comment by sebacea** [comment]
thanks @cscheid, cross-reference work. Citations are not working. In your example if `6503.qmd`is modified to:

````
---
format: pdf
bibliography: references.bib
---

::: {#fig-1}
This is a figure.

This is a caption.
:::

In @fig-1 of some reference @nash1950, you can see that this markdown citation works.

```{=latex}
\input{document.tex}
```

````

Provided `references.bib` like:

````

@article{nash1950,
	title = {Equilibrium Points in n-Person Games},
	author = {Nash, John F.},
	year = {1950},
	date = {1950},
	journal = {Proceedings of the National Academy of Sciences of the United States of America},
	pages = {48--49},
	volume = {36},
	number = {1},
	url = {http://www.jstor.org/stable/88031},
	langid = {en}
}

````

I am producing:

<img width="606" alt="Captura de pantalla 2023-12-04 a las 15 13 54" src="https://github.com/quarto-dev/quarto-cli/assets/7935588/b22f2d68-41f5-482c-a585-2fbb4bac75cb">

**Comment by cscheid** [comment]
What's your new `document.tex`?

**Comment by sebacea** [comment]
Sorry, this line: `See \ref{fig-1} in \cite{@nash1950}.`

**Comment by cscheid** [comment]
The problem is that citations are resolved by Pandoc, and `\input{...}` is resolved by pdflatex (or whatever your latex engine is).

You can see this by using `keep-tex: true`. Note the end of the document:

```
...




\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-nash1950}
Nash, John F. 1950. {``Equilibrium Points in n-Person Games.''}
\emph{Proceedings of the National Academy of Sciences of the United
States of America} 36 (1): 48--49.
\url{http://www.jstor.org/stable/88031}.

\end{CSLReferences}



\end{document}
```

Note that there's no (eg) `\bibliography` command there, so there's nothing for `\cite` to find. In order for what you want to do to work, Pandoc needs to see your input, it needs to find the citation, and it needs to process it. 

So, `\input{}` specifically is entirely out of the question, and I don't think there's anything we can do about this. (Of course, you could choose to do citation resolution entirely on your own, but then you're not working within Quarto/Pandoc)

Even if the input was in a "plain" rawblock, it's very hard in general to do what you want, because we would need to inspect very specific parts of the input, parse it robustly, and then splice the result very carefully inside the raw block (to avoid issues like stray line breaks and paragraph breaks).

I really don't think we can make this feature have the quality that we expect out of Quarto, so right now I'm relatively strongly inclined to not do it.

**Comment by sebacea** [comment]
Ok, but how do you integrate work from non-quarto workers? Thanks for taking time to think about this.

**Comment by mcanouil** [comment]
I don't follow.
If your coworkers work with LaTeX, let them contribute to your computed LaTeX document.

If you want to do some kind of patchwork between markdown and ne LaTeX using both input and output document, then you'll have to handle that yourself as this is definitely not an intended workflow in Quarto but in many other softwares.

My suggestion is either to try to onboard them on Markdown and teach them raw LaTeX block for examples tables.
