### ISSUE TITLE
Embedding for a quarto document doesn't work with Julia cells

### ISSUE THREAD

**Issue by tpoisot** [quarto-dev/quarto-cli#6520]
### Bug description

Following #6499, embedding from a quarto document generates the notebook, but it seems to use a different jupyter install than before?

Previous to this change, I could set the kernel to a notebook as *Julia release channel* and it Just Worked (tm), but now rendering the qmd file (with Julia code cells) requires to install Jupyter from scratch, and the julia kernel is not listed when I do `jupyter kernelspec list`.

### Expected behavior

Working from the notebook correctly picked the julia kernel that is distriubted with Juliaup. Working from a qmd document should have the same behavior and not require a different jupyter install?

### Quarto check output

````bash

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/tpoisot/.opt/quarto-cli/package/dist/bin

Check file:///home/tpoisot/.opt/quarto-cli/src/resources/vendor/deno-land/x/puppeteer@9-0-2/mod.ts
[✓] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/tpoisot/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /bin/python3
      Jupyter: 4.12.0
      Kernels: python3

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
````

**Comment by tpoisot** [comment]
This seems to be solved by manually installing `IJulia` in the default (`@1.9`) environment, which still feels off since it's not required when directly interacting with a notebook

**Comment by dragonstyle** [comment]
Question for you - is the specification of the Julia configuration / execution happening via the project file (`_quarto.yml`). If so, that is likely the issue and I have some more work to do...

**Comment by tpoisot** [comment]
@dragonstyle nope -- the only thing in `_quarto.yml` (aside from book metadata) is the `execute-dir`

**Comment by dragonstyle** [comment]
Ok it seems like it is perhaps related to the execution dir (another issue I believe that you opened). I'll have a look at that first.
