### ISSUE TITLE
Multi-line fig-cap are broken when rendering a notebook from a qmd file

### ISSUE THREAD

**Issue by tpoisot** [quarto-dev/quarto-cli#6521]
### Bug description

The markup for multiline figure captions does not survive the rendering of a qmd file in a notebook when embedding a figure from the former

### Steps to reproduce

Have a qmd document with a multiline caption, embed this figure from another qmd document. For example:

````md
#| label: fig-gradient-residuals
#| fig-cap: >
#|  Overview of the distributions of residuals
````

### Expected behavior

The legend is rendered in the notebook as 

````md
#| label: fig-gradient-residuals
#| fig-cap: >
#|  Overview of the distributions of residuals
````

### Actual behavior

Error: None of the known patterns match for   (part of legend text here)

The legend in the notebook appears as

````md
#| fig-cap: |
#| 
#|   Overview of the distributions of residuals
````

### Your environment

- IDE: VSCode
- OS: Linux Ubuntu 22.04

**Comment by cscheid** [comment]
What happens if you use the literal `|` indicator, cf https://yaml-multiline.info/?

**Comment by tpoisot** [comment]
This breaks in a new (fun!) way:

```md
#| label: fig-gradient-data
#| fig-cap: |
#|   First line of the legend
#|   This is another line
```

is rendered in the notebook as 

```md
#| label: fig-gradient-data
#| fig-cap: |
#| 
#|   First line of the legend
#| 
#|   This is another line
```

Even giving the number of spaces explicitly (`|2` or `>2` for example) makes no difference.

**Comment by cscheid** [comment]
Thanks for following up. That's definitely a bug on our side.

**Comment by cscheid** [comment]
@dragonstyle I have a minimal repro.

I pushed it to https://github.com/quarto-dev/quarto-cli/tree/bugfix/6521

```
$ cd tests/docs/smoke-all/2023/10/02/6521
$ quarto render nb.qmd --to ipynb
ERROR:

None of the known patterns match for   Overview of the distributions of residuals
ERROR: Error
    at renderFiles (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/render-files.ts:334:23)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async renderProject (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/project.ts:266:23)
    at async Command.fn (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/cmd.ts:212:26)
    at async Command.execute (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/quarto.ts:135:3)
    at async file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/quarto.ts:167:5
```
