### ISSUE TITLE
Inline `R` code not generating output

### ISSUE THREAD

**Issue by r-cheologist** [quarto-dev/quarto-cli#6536]
### Bug description

When rendering a document to pdf that contains an `R` code chunk, followed by an inline code statement, the former gets executed, echoed, included, etc. just fine, while the latter does not.

As the chunk exists, the [known problem](https://github.com/quarto-dev/quarto-cli/discussions/4855) of having to call `engine: knitr` explicitly should not impact this.

### Steps to reproduce

Generate the following document

````quarto
```{r}
#| output: asis
cat("Chunk Test")
```

`r cat("Inline Test")`
````

And render it to PDF

### Expected behavior

Both `R` calls should generate output.

### Actual behavior

Only the chunk-wrapped code generates output.

### Your environment

- IDE: RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

### Quarto check output

````bash
[x] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[x] Checking versions of quarto dependencies......OK
[x] Checking Quarto installation......OK
      Version: 1.4.320
      Path: /opt/quarto/bin

[x] Checking tools....................OK
      TinyTeX: undefined
      Chromium: (not installed)

[x] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/rstudio/.TinyTeX/bin/x86_64-linux
      Version: 2023

[x] Checking basic markdown render....OK

[x] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[x] Checking R installation...........OK
      Version: 4.2.3
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/local/lib/R/library
        - /home/rstudio/R/x86_64-pc-linux-gnu-library/4.2
      knitr: 1.43
      rmarkdown: 2.24

[x] Checking Knitr engine render......OK
````

**Comment by cscheid** [comment]
I think this is not a bug; `cat` _emits output_, and inline evaluation expects a _value_. You want `r "Inline Test"` instead.

@cderv, is my understanding correct?

**Comment by r-cheologist** [comment]
Indeed. Sorry for the noise. Incredible how much time I wasted on this!

**Comment by cderv** [comment]
@cscheid yes this is correct. Inline R code expects an output as character (or coercible to character). **knitr** inline R output will be emitted "asis" by default to be included inlined in the text. `cat()` returns NULL, and `as.character(NULL)` returns `character(0)` - so nothing is shown in output. Which is expected here.

 So no need for `cat()` or special treatment here, just output a string.
