### ISSUE TITLE
output: asis suppressed label: xxx 

### ISSUE THREAD

**Issue by tpoisot** [quarto-dev/quarto-cli#6538]
### Bug description

When making some tests for #4797 , I came across a strange bug. If I only use `#| label: tab-whatever` in my file, I can embed the output just fine. Since the output in my case is a markdown table, I added `#| output: asis`, and then quarto started complaining that there was no cell with this label (even though, there is).

I have attached a zip file with a demo project, line 13 in `notebooks/tables.qmd` is where you can switch the output

[quarto-table-test.zip](https://github.com/quarto-dev/quarto-cli/files/12354399/quarto-table-test.zip)

### Steps to reproduce

In the attached project, at line 13 in the `.qmd` notebook, change the line to activate `output: asis` 

### Expected behavior

The cell label is recognized, and (in an ideal world?), the table is outputted as Markdown and rendered in the document.

### Actual behavior

~~~
Starting julia-1.9 kernel...Done

Executing 'tables.ipynb'
  Cell 1/2: ''...........Done
  Cell 2/2: 'tab-test'...Done

ERROR: The cell tab-test does not exist in notebook
~~~

### Your environment

- IDE: VS Code
- OS: Linux Ubuntu 22.04
- Julia: 1.9

### Quarto check output

````bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/tpoisot/.opt/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/tpoisot/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /usr/bin/python3
      Jupyter: 4.12.0
      Kernels: julia-1.9, python3

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
````

**Comment by mcanouil** [comment]
`output: asis` is an "advanced" option as it delegates the whole
cell output to the user, in this case, it is you.
If you use `knitr`, you can leverage `knitr::knit_child()` (and possibly `knitr_knit_expand()`).

**Comment by tpoisot** [comment]
Do you know if there are updated information about how to do this last part for Julia?

**Comment by tpoisot** [comment]
The packages I use do return markdown, I'm just looking for a way to get it to render in the document in a way that can be cross-referenced. I'm not sure what the blockage is, here, since I'm pretty sure the tables are returned with the correct mime type and everything?

**Comment by mcanouil** [comment]
For now, since I am away from a keyboard and because the reprex is a zip archive, I can't try or look at it.

**Comment by cscheid** [comment]
One small thing: the cross-referenceable prefix for table is `tbl`, not `tab`. I wonder if this could be the culprit.

**Comment by mcanouil** [comment]
Nice catch, indeed from the log output (since recently printing cell label), the prefix seems to be `tab-`.
Very likely to be it.

**Comment by tpoisot** [comment]
@cscheid sorry about this -- this doesn't solve the issue, using `tbl-` with `asis` still gives the same output (cell not found), and removing `asis` shows the markdown code but not the rendered table

**Comment by tpoisot** [comment]
using the html rendering works:

```julia
out = pretty_table(String, df, tf= tf_html_minimalist)
display("text/html", out)
```

For some reason, I'm unable to get the same result using the `"text/markdown"` type, but this also renders in PDF and removes the need for `asis` output. This might me worth adding to the doc (I can open a PR)

**Comment by cscheid** [comment]
> using the html rendering works:
> 
> ```julia
> out = pretty_table(String, df, tf= tf_html_minimalist)
> display("text/html", out)
> ```
> 
> For some reason, I'm unable to get the same result using the `"text/markdown"` type, but this also renders in PDF and removes the need for `asis` output. This might me worth adding to the doc (I can open a PR)

Sorry you're still running into trouble here. If you want to debug further, trying to do the similar thing with a Python notebook (through `IPython.display.Markdown`) and inspecting the generated .ipynb (use `keep-ipynb: true`) might offer a way forward.

**Comment by tpoisot** [comment]
Thanks for the info, I might do this when I have a bit of time. As long as I have a working solution, I'm good. Thanks!!

**Comment by mcanouil** [comment]
@tpoisot Is the following what you had (I used your zip archive).
<img width="1460" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/ae7c2d59-ee5a-4f54-b287-5c29a6dd876d">

**Comment by tpoisot** [comment]
Yup, exactly -- but using the solution [here](https://github.com/quarto-dev/quarto-cli/issues/6538#issuecomment-1681104061) works just fine. There's probably an issue with markdown specifically at some point.

**Comment by mcanouil** [comment]
Additional note, the issue is not really on Quarto as the same thing occurs using a Jupyter notebook.

<img width="1460" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/8c2addb5-02aa-4bb6-a410-99db7d40958c">

**Comment by donert** [comment]
I encountered the same problem with an R based qmd. (I want my gt tables to look the same when rendering pdf and html; style and word wrapping in cells) Sample code attached.
[asis_cross_refernce-broke.qmd.txt](https://github.com/quarto-dev/quarto-cli/files/12728646/asis_cross_refernce-broke.qmd.txt)
![asis-no-work-example](https://github.com/quarto-dev/quarto-cli/assets/13247714/25cc4ae3-972e-495f-bd3d-aa8b56011058)

**Comment by cscheid** [comment]
> I want my gt tables to look the same when rendering pdf

That's unfortunately not possible in general, because the set of styles available in HTML is different than that in PDF. We would like to support something like automatic screenshotting of the HTML content for other formats, but we haven't implemented that yet.
