### ISSUE TITLE
The fonts in the code blocks in revealjs slides will be changed by the language setting of the document

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#656]
I added the `lang: ja` setting to the following document and noticed that the inline code and code block fonts are no longer monospaced fonts.
https://github.com/eitsupi/tokyorslide/blob/c094cae5e4dce8ddd140c4e9236c6297689091c0/tokyor_97/index.qmd

no `lang` setting
![image](https://user-images.githubusercontent.com/50911393/163659284-cb558b5d-5e06-4271-9dc3-168fb5e4416e.png)

with `lang: ja`
![image](https://user-images.githubusercontent.com/50911393/163659289-8bf8def0-19aa-486f-95f0-561f388da470.png)

When set to `lang: zh`, it also changed to other fonts.
I don't think the fonts in a code blocks should change depending on the language setting.

quarto version 0.9.260

**Comment by jjallaire** [comment]
Hmm.....I'm not able to repro this running latest Quarto on OS X (w/ your exact repo/code).  Here is what I see:

<img width="789" alt="Screen Shot 2022-04-17 at 7 17 43 AM" src="https://user-images.githubusercontent.com/104391/163712137-d7c1db9a-13e9-4106-8609-89ce0bfde41f.png">

What platform are you running on?

**Comment by eitsupi** [comment]
This seems related to the browser font settings.
I work in a Docker container on WSL2 and usually use Firefox on Windows.

When I viewed it in Edge, I noticed that it was not monospaced from the beginning.
And Edge was not affected by the language setting.

Firefox (without `lang` setting)
![image](https://user-images.githubusercontent.com/50911393/163714536-3e052980-2f16-4177-b68f-e8924b00aa1b.png)

Edge (without `lang` setting)
![image](https://user-images.githubusercontent.com/50911393/163714541-3a681313-e2c3-488e-9716-b3bbe3bece52.png)

Firefox (`lang: ja`)
![image](https://user-images.githubusercontent.com/50911393/163714504-873d143e-5e04-4b84-ab1a-ce0427a3de1c.png)

Edge (`lang: ja`)
![image](https://user-images.githubusercontent.com/50911393/163714512-f234fe06-7f8a-40fa-a308-4bf483f85c41.png)

generated html file (`lang: ja`)
[index.zip](https://github.com/quarto-dev/quarto-cli/files/8501592/index.zip)

**Comment by eitsupi** [comment]
It appears that Edge always uses the monospace font setting set in the browser, while Firefox switches the font used depending on the language.
Sorry, this may not be a quarto problem...

**Comment by eitsupi** [comment]
https://quarto.org/docs/presentations/revealjs/themes.html#saas-variables

Perhaps because `$font-family-monospace` is set to `monospase` here?
I wonder if it is possible to default to a specific font instead of monospase for fonts in code blocks.

I think the current specification is confusing to users, since the HTML documentation does not seem to indicate that language settings affect the appearance in a code block.

**Comment by jjallaire** [comment]
Good sleuthing! I've made the change to use more explicit monospaced fonts here: https://github.com/quarto-dev/quarto-cli/commit/6cf2f748e3722fe6d87694397faa5c5e6cdb4ece

**Comment by eitsupi** [comment]
quarto 0.9.275 works nicely! Thanks!

![image](https://user-images.githubusercontent.com/50911393/163808341-3b49f365-1693-4b24-8559-8f96963d8490.png)
