### ISSUE TITLE
LaTeX to Typst Math

### ISSUE THREAD

**Issue by cadojo** [quarto-dev/quarto-cli#6560]
### Bug description

When creating a Typst document, equations seems to no-longer use Pandoc (LaTeX) formatting, but _Typst_ math formatting. This is a bit unexpected to me --- I think of `.qmd` files as extensions of Pandoc markdown, which uses LaTeX math (I think). Perhaps I'm wrong about the intent! I think I saw a [math writer](https://github.com/jgm/pandoc/issues/8713) for Typst merged into Pandoc, but I don't know what's working and what's not working.

In case you are also expecting Pandoc render of the TeX equations, I'm writing this issue to document the behavior!

I understand Typst support is in-development, and not yet released. I saw no open issues relating to Typst math, so I'm filing this in case the information is helpful. I apologize if this is an inappropriate use of an issue. Thank you for Quarto!

### Steps to reproduce

I'm using 1.4.322 on MacOS 13.4.1.

```qmd
---
format:
  typst: default
---

## Math

For more information, see @eq-proof.

$$
\frac{1}{2} \equiv 1 \div 2
$$ {#eq-proof}

```

### Expected behavior

I expected the math to be read as LaTeX math, and I expected a Pandoc math writer to translate the math to Typst math. 

### Actual behavior

The following error is thrown.

```
[typst]: Compiling template.typ to template.pdf...error: unknown variable: rac
    ┌─ /template.typ:115:2
    │
115 │ \frac{1}{2} \equiv 1 \div 2
    │   ^^^
```

### Your environment

- IDE: Visual Studio Code
- OS: MacOS Ventura 13.4.1

### Quarto check output

```

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.322
      Path: /Users/joey/Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /opt/homebrew/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: python3, julia-1.9

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
Thanks for the report!

Could you format your post properly so we can use your example?
You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by cadojo** [comment]
> Could you format your post properly so we can use your example? You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four `` ```` ``).

Was not aware of that trick! Great, just updated my post, so it should be formatted now.

**Comment by cderv** [comment]
FWIW this convert with pandoc 
````markdown
---
format:
  typst: default
---

## Math


$$
\frac{1}{2} \equiv 1 \div 2
$$

````

using `quarto pandoc -t typst -o test.pdf index.qmd`

So it seems to be our special syntax for cross referencing that makes things not work. https://quarto.org/docs/authoring/cross-references.html#equations

**Comment by sverrirarnors** [comment]
If this is the desired functionality for me (using typst to render equations instead of latex), is there an option to toggle this?

**Comment by mcanouil** [comment]
@sverrirarnors please open a GitHub Discussion referencing this issue to start a discussion.
This issue was closed and is more than one year old.
