### ISSUE TITLE
Add a `prepare-external` command to `quarto-bld` 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#6575]
This follows discussion at 

* https://github.com/conda-forge/quarto-feedstock/issues/27

Idea is to move the patch there (https://github.com/MattF-NSIDC/quarto-feedstock/blob/95a3bd9494f63a8d1eafd18395be9437e31943d3/recipe/0001-add-external-installer-command-for-packagers-like-co.patch) as a command in `quarto-bld`

cc @mfisher87

**Comment by cderv** [comment]
Ok in fact it was a duplicate of 
* https://github.com/quarto-dev/quarto-cli/issues/5444 

And this has been solved by @dragonstyle at https://github.com/quarto-dev/quarto-cli/commit/0fea9ec2462db44e3e343b8eabe86950b90117fe

**Comment by mfisher87** [comment]
Thank you!
