### ISSUE TITLE
`fig-dpi` is not working on cell level for knitr

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#6576]
From documentation, `fig-dpi` seems to be working at cell level to change the DPI settings 
https://quarto.org/docs/reference/cells/cells-knitr.html#figures

However, it seems it does not apply at the cell level at least for **knitr** to set the knitr's equivalent `dpi` setting

````markdown
---
title: "test"
format: html
---

```{r}
knitr::opts_current$get("dpi")
```

```{r}
#| fig-dpi: 72
knitr::opts_current$get("dpi")
```
````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/dae5c3df-3ad1-413e-9948-75bada141016)

So I think this is either 

* A documentation change if `fig-dpi` is like `fig-format` and only used at YAML header level
* An issue to fix if this is supposed to be a quarto way to set `dpi` for knitr

Considering this in our code base 
https://github.com/quarto-dev/quarto-cli/blob/f356b962eb8551e2748242d7c9bfc8de24acd861/src/resources/rmd/execute.R#L253-L267

I think `fig-dpi` is currently working if set in YAML header
```yaml
execute:
  fig-dpi: 96
```

but our YAML autocompletion and our doc does not help know that
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/faceb67d-09b9-4ab2-8e7f-608ce4beffda)

@jjallaire should `fig-dpi` and `fig-format` be made aliases for `dpi` and `dev` at chunk level ? 
Or is this not the case on purpose ? 

Thank you.

**Comment by jjallaire** [comment]
This definitely is supposed to work! I think I see where the problem is: initially this _did work_, but when we switched over to Knitr handling the YAML options it stopped working. See this code:

https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/rmd/hooks.R#L628

Note that in the first branch we do the aliasing but in the second branch that aliasing doesn't occur. So either (a) Knitr should do this along with any other Quarto-specific behavior around cell options; or (b) We should do that aliasing for both branches.

**Comment by cderv** [comment]
Oh I see. I already need to tweak our option handling for fixing 

* https://github.com/quarto-dev/quarto-cli/issues/5852 

as we're not correctly merging modified option. 

As those options are Quarto specific, it seems ok to handle that in Quarto rather than in **knitr**. We already do the option normalization (`-` to `.` in Quarto). 

I'll make a PR for fixing both issues.

**Comment by cderv** [comment]
> So either (a) Knitr should do this along with any other Quarto-specific behavior around cell options;

@jjallaire with @yihui we went that path and from **knitr** 1.44 next release (current 1.43.7 dev version), the normalization from dash version to dot version will be done by knitr itself. And the alias replacement for `fig-format` and `fig-dpi` too. 

Not sure how to handle the transition in Quarto. I'll add a comment at least, as keeping current code should not conflict, so it should not be used anymore with future knitr version

**Comment by jjallaire** [comment]
Okay, sounds great!
