### ISSUE TITLE
Absolute path is treated as a relative path

### ISSUE THREAD

**Issue by onurcanbektas** [quarto-dev/quarto-cli#659]
I'm trying to include a figure into a .qmd file file as

![](`r here::here("data/F220416/F220416S2214/raw/IMG_1785.png")`)
(`here` library makes sures that the path is an absolute path)

But in the html file that is created, the resulting path looks like

`<p><img src="./Users/onurcanbektas/junction/projects/apm.alim.raedler/data/F220416/F220416S2214/raw/IMG_1785.png" class="img-fluid"></p>`

i.e the absolute path has `.` in front of it. 

During the rendering, quarto is warning me that I supplied an absolute path, so it is recognising that it is absolute, but still treats it as a relative path. I think this behaviour is unintendend, hence a bug.

**Comment by jjallaire** [comment]
You are going to end with all sorts of problems if you try to use absolute paths in qmds so I'd recommend you find a way to use a relative path. 

Any use of absolute paths will break "quarto preview" (as it hosts a webserver that can only access the top level directory of the document). I noted that for a standalone document (not in a website) you actually can use absolute paths only if you open the file directly with Chrome from the filesystem.

In a website, we have a feature that allows you to use "absolute" website paths (e.g. `/images/foo.png` will resolve to the root directory of your website). That is I believe what you are seeing here (we are treating your filesystem absolute path like a website absolute path). Note that even if we didn't do this to your path, you wouldn't be able to see the image in "quarto preview" (you'd only see it when opening w/ Chrome) and you wouldn't see it on any deployed version of your site (as that path would be outside the `_site` directory).

**Comment by shalom-lab** [comment]
I meet a similar error. My absolute image src was treated as relative path.

``![](https://haha-1257749604.cos.ap-shanghai.myqcloud.com/image/202204171955796-collinearity.png)``
ERROR: 鏂囦欢鍚嶃€佺洰褰曞悕鎴栧嵎鏍囪娉曚笉姝ｇ‘銆?(os error 123), stat 'D:\Github\blog\https:\haha-1257749604.cos.ap-shanghai.myqcloud.com\image\202204060942551-sh.png'

**Comment by cderv** [comment]
For reference, duplicate of https://github.com/quarto-dev/quarto-r/issues/10
