### ISSUE TITLE
Windows release not working

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-cli#66]
The last Quarto version to work for me on Windows was v0.2.28. When I install v0.2.32 or v.02.34 and run `quarto check`, I get this error:

![image](https://user-images.githubusercontent.com/6981612/127421905-5eb9fcc5-1aed-4ebf-95cf-8950b07082d3.png)

I get the same error on `serve`, `render`, and `preview`.  

FWIW, the v0.2.34 executable in the Workbench Docker container is working with no problems

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/06e564d192a56f3383badb72c84a5078e956d60f
