### ISSUE TITLE
Defining affiliations in front matter is not working

### ISSUE THREAD

**Issue by lillemets** [quarto-dev/quarto-cli#6600]
### Bug description

Defining multiple affiliations and assigning them to authors is described in the [documentation](https://quarto.org/docs/authoring/front-matter.html#multiple-authors)  and an example is provided. However, the example given prints an error.

### Steps to reproduce

Copy the [example from documentation](https://quarto.org/docs/authoring/front-matter.html#multiple-authors) (below) and attempt to render it.

```qmd
---
title: "Untitled"
format: html
author:
  - name: Norah Jones
    affiliation:
      - ref: cmu
      - ref: chicago
  - name: John Hamm
    affiliation:
      - ref: cmu
affiliation:
  - id: cmu
    name: Carnegie Mellon University
  - id: chicago
    name: University of Chicago
---
```

### Expected behavior

A document should be renderd with multiple affiliations per author in front matter.

### Actual behavior

The following error message is printed: 

`ERROR: Undefined affiliation 'cmu' for author 'Norah Jones'.`

### Your environment

- IDE: RStudio 2023.06.1
- OS: Linux

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/jrl/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK

**Comment by rgaiacs** [comment]
I confirm this bug in Quarto v1.4.330.

Please not that

```
---
author:
  - name: Norah Jones
    affiliation:
      - id: cmu
        name: Carnegie Mellon University
      - id: chicago
        name: University of Chicago
  - name: John Hamm
    affiliation:
      - ref: cmu
---
```

works as expected.

**Comment by cderv** [comment]
I think this is just a typo in the example in website. `affiliation` should be `affiliations` with an **s** , as documented in the schema doc : https://quarto.org/docs/journals/authors.html#affiliations-schema

So try 
````markdown
---
title: "Untitled"
format: html
author:
  - name: Norah Jones
    affiliation:
      - ref: cmu
      - ref: chicago
  - name: John Hamm
    affiliation:
      - ref: cmu
affiliations:
  - id: cmu
    name: Carnegie Mellon University
  - id: chicago
    name: University of Chicago
---
````
