### ISSUE TITLE
AsciiDoc figure code lacks trailing whitespace

### ISSUE THREAD

**Issue by jeroenjanssens** [quarto-dev/quarto-cli#6623]
### Bug description

The figure code produced by [asciidoc.lua](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/filters/layout/asciidoc.lua) is correct, expect that it lacks trailing whitespace. The result is that figures are not displayed when rendering a Quarto document to AsciiDoc.

PS. I'm a big fan of Quarto. We're currently using it to write our next O'Reilly book (hence the AsciiDoc).

### Steps to reproduce

Consider a minimum working example called *mwe.qmd* with the following contents:

````qmd
---
title: Tiger
format: asciidoc
---

As you can see, @fig-tiger shows a tiger.

![A tiger](tiger.png){#fig-tiger}

Roar.
````

### Expected behavior

The command `quarto render mwe.qmd` should produce the following AsciiDoc:

````asciidoc
= Tiger

As you can see, <<fig-tiger>> shows a tiger.

[[fig-tiger]]
.A tiger 
image::tiger.png[""]

Roar.
````

### Actual behavior

Instead, `quarto render mwe.qmd` currently produces the following AsciiDoc:

````asciidoc
= Tiger

As you can see, <<fig-tiger>> shows a tiger.

[[fig-tiger]]
.A tiger 
image::tiger.png[""]Roar.
````

The difference with the expected output is the lack of white space between the figure code (`image::tiger.png[""]`) and the next paragraph (`Roar.`).

### Your environment

- IDE: Neovim
- OS: macOS Monterey 12.5

### Quarto check output

````bash
$ quarto check
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /Users/jeroen/.pyenv/versions/3.11.1/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /opt/homebrew/Cellar/r/4.3.1/lib/R
      LibPaths:
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.1/lib/R/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
````

**Comment by cscheid** [comment]
Thanks for the report. This bug should be closed by https://github.com/quarto-dev/quarto-cli/pull/6620. Keep an eye open on that one.

**Comment by cscheid** [comment]
If you need to work around that bug for the time being, you can add `` `\n\n`{=asciidoc} `` to the beginning of the following paragraph.

**Comment by jeroenjanssens** [comment]
Thanks for the quick reply. I see that #6620 is a big effort, fixing not only this bug, but many others as well. I believe that changing

```
figure:extend({"image::" .. image.src .. "[\"" .. altText .. "\"]"})
```

to 

```
figure:extend({"image::" .. image.src .. "[\"" .. altText .. "\"]\n\n"})
```

also fixes this particular bug. Would it be worthwhile to make that change to [that line](https://github.com/quarto-dev/quarto-cli/blob/59ff6aadb6c15ef052b07cd08ecc350e24c15a81/src/resources/filters/layout/asciidoc.lua#L32)? I'd be happy to submit a PR, even if it is just 4 characters. If not, I'm OK with using the workaround you suggested.

One more question if I may, out of curiosity. Earlier, I tried to "fix" this issue by using a custom Lua filter, but `image.attr.identifier` turned out to be empty. Do you happen to know why this is? Perhaps it's being emptied by another filter?

**Comment by cscheid** [comment]
> Would it be worthwhile to make that change to [that line](https://github.com/quarto-dev/quarto-cli/blob/59ff6aadb6c15ef052b07cd08ecc350e24c15a81/src/resources/filters/layout/asciidoc.lua#L32)?

That change has [already been made](https://github.com/quarto-dev/quarto-cli/pull/6620/files#diff-24a346ec11250ddc94f8ac9d6423ae2d9e056cc49c535f9e58e339ea9599a7d7).

> One more question if I may, out of curiosity. Earlier, I tried to "fix" this issue by using a custom Lua filter, but `image.attr.identifier` turned out to be empty. Do you happen to know why this is? Perhaps it's being emptied by another filter?

Yes, that's likely what it is. If you're (morbidly perhaps?) curious about the inner workings of our filter chain and want to go down this rabbit hole, you can do the following.

1. Clone the development version of quarto from the github repo here. You don't need to install it, but you need the `tools` subdirectory.

```
$ QUARTO_TRACE_FILTERS=output.json quarto render my-file.qmd
$ cd ${wherever-you-put-your-quarto-repo}/tools/trace-viewer
$ quarto preview trace-viewer.qmd
```

That will open a webpage. Now take the `output.json` file and drag it into the "Trace 1" text. You'll be able to see our filters as they change the input, and find where the identifier is moved.

With that said, I don't know why you want to be writing directly to the image identifier in a Lua filter in the first place; that's unlikely to do anything useful.

**Comment by cscheid** [comment]
> I only wanted to use the identifier so that the image can be referenced.

This should already be happening for you, in 1.3's implementation of asciidoc output, right now. All you need to do is use an image with a caption (A "Figure", in quarto parlance). If any of the syntax [discussed here](https://quarto.org/docs/authoring/figures.html) doesn't work for you, that's a quarto bug.

**Comment by jeroenjanssens** [comment]
> If any of the syntax [discussed here](https://quarto.org/docs/authoring/figures.html) doesn't work for you, that's a quarto bug.

Yep, that's why I submitted this issue :)

**Comment by cscheid** [comment]
Sorry, I meant _aside from the whitespace issue_.

**Comment by jeroenjanssens** [comment]
Got it. Thanks. 

For anyone else bumping into this issue, the following syntax works for me:

````qmd
---
title: Tiger
format: asciidoc
---

As you can see, @fig-tiger shows a tiger.

![A tiger](tiger.png){#fig-tiger}

` `{=asciidoc}  <!-- Temporary workaround -->

Roar.
````

The empty lines before and after the workaround are required. This generates:

```asciidoc
= Tiger

As you can see, <<fig-tiger>> shows a tiger.

[[fig-tiger]]
.A tiger
image::tiger.png[""]

Roar.
```

**Comment by cscheid** [comment]
Thank you! That PR should be landing in about a week.

**Comment by cscheid** [comment]
This is fixed on `main`.
