### ISSUE TITLE
No whitespace between check boxes and ordered list item

### ISSUE THREAD

**Issue by patgd** [quarto-dev/quarto-cli#6627]
### Bug description

Check boxes on an ordered list item do not produce whitespace between check box and text.

<img width="1014" alt="SCR-20230826-myox" src="https://github.com/quarto-dev/quarto-cli/assets/88806542/7ab681d4-c62c-43ec-a79e-f9951939c284">

Similar to [Issue 4556](https://github.com/quarto-dev/quarto-cli/issues/4556). 

### Steps to reproduce

```
1. [ ] Markdown checkbox
2. <input type="checkbox" unchecked>HTML tag checkbox </input>
```

### Expected behavior

A space between the checkbox and text.

### Actual behavior

No space between checkbox and text

### Your environment

- IDE: VSCode 1.81.1
- OS: MacOS Ventura 13.5.1

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /Users/pat/bin/miniconda3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
I can't reproduce on latest Quarto and three browser.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/0333c08e-f2a7-4cb0-8486-5487ea058bec">
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/64290f87-4de2-4de7-b377-e95b2891737c">
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/88baa043-2630-43ec-bb87-985f55d48715">

**Comment by patgd** [comment]
Apologies,

**Comment by cscheid** [comment]
> Is the lack of whitespace between ordered item text and its checkbox, when using markdown syntax, desired and intended?

I personally think it doesn't look great.

**Comment by mcanouil** [comment]
A simple CSS tweak to add right padding would do the job.

**Comment by mcanouil** [comment]
I don't know where to put the change but here is a possible solution:

````qmd
---
title: "Quarto Playground"
format: html
include-in-header:
  - text: |
      <style>
      input[type="checkbox"] {
        margin-right: 0.5ch;
      }
      </style>
---

This is a playground for Quarto.

1. [ ] Markdown checkbox
2. <input type="checkbox" unchecked>HTML tag checkbox </input>
````

**Comment by cscheid** [comment]
> Note that `revealjs` has some additional styles which interacts with checkbox.

The situation there is worse, and probably shouldn't stop us from making a small good fix like yours in .html formats. I'll make the change.
