### ISSUE TITLE
dates for observable using quarto, ojs and arquero

### ISSUE THREAD

**Issue by racing-focus** [quarto-dev/quarto-cli#6630]
### Bug description

I started to use observable, quarto and ojs, it wasn't plotting dates.  So I looked around.

I ended up at stackoverflow and tried to modify my code to suit.  It didn't work, so I tried the example provided and it didn't work either.

```{r}

https://stackoverflow.com/questions/76499928/passing-dates-from-r-chunk-to-ojs-chunk-using-ojs-define-in-quarto

```

---
title: "Code example"
format: html
execute:
  echo: false
  warning: false
---

```{r}
library(dplyr)

df <- data.frame(day = seq.Date(
        from = as.Date('2023-01-01'),
        to = as.Date('2023-06-15'),
        by = 'days'
      )) %>%
  mutate(
    values = rnorm(mean = 10, sd = 2, n = n())
  )

ojs_define(plot_data=df)
```

```{ojs}
import { aq } from '@uwdata/arquero'
d3 = require("d3@7")
parser = d3.timeParse("%Y-%m-%d");
```

## Plot

```{ojs}
final_data = aq.from(transpose(plot_data))
  .derive({ day: aq.escape(d => parser(d.day)) })
```

```{ojs}
Chart = Plot.plot({
  marks: [
    Plot.line(final_data, 
      {x: "day", y: "values"}, 
      { stroke: "black" }
    )
  ]}
)
```

The error I get is.

![Screen Shot 2023-08-27 at 11 59 06 pm](https://github.com/quarto-dev/quarto-cli/assets/121075286/7e0e064e-d1d8-4b29-be62-d631dea9666d)

I also noticed the same on the quarto site.

![Screen Shot 2023-08-28 at 12 00 39 am](https://github.com/quarto-dev/quarto-cli/assets/121075286/bcf3222d-e09a-47e4-a186-dc186c7ea5f6)

I updated my rstudio today to.

```{r}
RStudio 2023.06.2+561 "Mountain Hydrangea" Release (de44a3118f7963972e24a78b7a1ad48b4be8a217, 2023-08-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.2+561 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

```

### Expected behavior

I should get a plot with a formatted x-axis for dates.

### Actual behavior

I get the following.

![Screen Shot 2023-08-27 at 11 59 06 pm](https://github.com/quarto-dev/quarto-cli/assets/121075286/2c4d7eac-fe29-4424-927c-a53492cb66ad)

**Comment by mcanouil** [comment]
Thanks for the report!

Could you format properly your post?

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by racing-focus** [comment]
Inside an additional 'backtick'.

````{r}
---
title: "Code example"
format: html
execute:
  echo: false
  warning: false
---

```{r}
library(dplyr)

df <- data.frame(day = seq.Date(
        from = as.Date('2023-01-01'),
        to = as.Date('2023-06-15'),
        by = 'days'
      )) %>%
  mutate(
    values = rnorm(mean = 10, sd = 2, n = n())
  )

ojs_define(plot_data=df)
```

```{ojs}
import { aq } from '@uwdata/arquero'
d3 = require("d3@7")
parser = d3.timeParse("%Y-%m-%d");
```

## Plot

```{ojs}
final_data = aq.from(transpose(plot_data))
  .derive({ day: aq.escape(d => parser(d.day)) })
```

```{ojs}
Chart = Plot.plot({
  marks: [
    Plot.line(final_data, 
      {x: "day", y: "values"}, 
      { stroke: "black" }
    )
  ]}
)
```


````

**Comment by cscheid** [comment]
I can't reproduce the website issue you're experiencing:

<img width="1232" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/5cbc3979-c241-4c4a-8f2d-362b7e4d869f">

What browser/OS are you running?

**Comment by cscheid** [comment]
Still can't reproduce, this is on Safari.

<img width="1148" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/5fbdb2cf-2d96-4e6b-90c4-4f4ea1cf5083">

**Comment by racing-focus** [comment]
I don't know what to say then, do you think I doctored my screenshot of a quarto website?



![Screen Shot 2023-08-30 at 10 38 47 am](https://github.com/quarto-dev/quarto-cli/assets/121075286/79eab7d6-dfbb-4410-bb20-8f4a29a38a16)
![Screen Shot 2023-08-30 at 10 38 04 am](https://github.com/quarto-dev/quarto-cli/assets/121075286/428c4da6-9ba4-48be-b192-103778f4f029)

**Comment by cscheid** [comment]
(Please be mindful of the tone in your messages. I am trying to diagnose the issue, and pointing out that the behavior you're experiencing is not consistent with what we are seeing.)

I note that you're running an older version of Safari than I, one that hasn't been updated in 2 years. I wonder if that could be the reason.

**Comment by racing-focus** [comment]
I apologise for my comment.

Apple like to link safari updates with a Mac OS update and they can be painful. I only do them when someone I trust says, you need to do it.

**Comment by cscheid** [comment]
> Apple like to link safari updates with a Mac OS update and they can be painful.

I hear you. Unfortunately, we don't test on old browsers, especially when the newer version is provided in OS updates; there are simply too many different incompatible browsers for the size of our development team. I can only recommend that you use an up-to-date browser.
