### ISSUE TITLE
FR: Code output to the side

### ISSUE THREAD

**Issue by grantmcdermott** [quarto-dev/quarto-cli#664]
A common pedagogical tool is providing code and the resulting output _side-by-side_ ([simple example](https://raw.githack.com/edrubin/EC607S21/master/notes-lecture/04-inference/04-inference.html#37)). While not as important for long-form document formats, this is especially nice for presentation formats that usually take on a "wide" aspect ratio like 16:9 or 4:3.

Quarto offers a number of really nice features for controlling multi-column layouts (`{.columns}` & co.). So you can mimic this behaviour by duplicating the code across columns (but not evaluating one of them). Something like:

````
:::: {.columns}

::: {.column width="50%"}
```r
library(dplyr, warn.conflicts=FALSE)
mtcars |>
  filter(cyl>=4) |>
  summarise(mean_mpg = mean(mpg))
```
:::

::: {.column width="50%"}
```{r}
library(dplyr, warn.conflicts=FALSE)
mtcars |>
  filter(cyl>=4) |>
  summarise(mean_mpg = mean(mpg))
```
:::

::::

````

However, AFAICT, there's no way to specify that code should evaluate "to the side" automatically, thus avoiding the code duplication.

Is this something that you would consider supporting? 

Regardless, I've really been enjoying Quarto so far. Many thanks to all the devs!

**Comment by jjallaire** [comment]
We actually do have a way to do this for revealjs, see https://quarto.org/docs/presentations/revealjs/index.html#output-location

**Comment by grantmcdermott** [comment]
Ah, very nice. I've been using a custom beamer template lately, but perhaps time I switched to revealjs anyway. Feel free to close unless you'd like to keep this open as a prompt for other formats. Thanks again JJ.

**Comment by jjallaire** [comment]
Yeah, we don't have quite as many degrees of freedom for stuff like this in Beamer and Powerpoint. It's not impossible but its entirely different code so I think we will leave this as a revealjs feature for now.
