### ISSUE TITLE
Quarto with PyScript with Three.js creates a ton of white space

### ISSUE THREAD

**Issue by axiomtutor** [quarto-dev/quarto-cli#6649]
I'm using Quarto to build out a web page, and inside it I'm trying to use PyScript with Three.js.  Here are the source files:

`trans.qmd`

```
---
title: "Transformations"
format: 
    html:
        include-in-header:
            - pyscript.html
        resources:
            - trans1.py
---

<script type="module">
import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.154.0/build/three.module.js';
globalThis.THREE = THREE;
</script>

# Problem 1

Ok, so you already know how to rotate a figure about the origin by certain angles like 90-degrees and 180-degrees and so on.

But suppose that you would like to rotate a figure about a point that is NOT the origin!  Like this:

<div id="p1"></div>
<py-script src="./trans1.py" output="p1"></py-script>

# Problem 2
```

`trans1.py`

```
import js, pyodide
from pyodide.ffi import create_proxy, to_js
from js import window
from js import Math
from js import THREE
from js import performance
from js import Object
from js import document
import asyncio

mouse = THREE.Vector2.new()

renderer = THREE.WebGLRenderer.new({"antialias":True})
rendersize = 500
renderer.setSize(rendersize, rendersize)
renderer.shadowMap.enabled = False
renderer.shadowMap.type = THREE.PCFSoftShadowMap
renderer.shadowMap.needsUpdate = True
document.body.appendChild( renderer.domElement )

def onMouseMove(event):
    event.preventDefault()
    mouse.x = (event.clientX / window.innerWidth) * 2 - 1
    mouse.y = -(event.clientY / window.innerHeight) * 2 + 1
js.document.addEventListener('mousemove', pyodide.ffi.create_proxy(onMouseMove))

fov = 75
aspect = 1
near = .1
far = 10
camera = THREE.PerspectiveCamera.new(fov,aspect,near,far)
camera.position.set(0,-4,3)
camera.up.set(0,0,1)
camera.lookAt(0,0,0)

scene = THREE.Scene.new()
scene.background = THREE.Color.new("black")

light = THREE.DirectionalLight.new("white",intensity=3)
light.position.set(-1,2,8)
scene.add(light)

gridsize = 6
xy = THREE.GridHelper.new(gridsize,gridsize)
xy.rotation.set(Math.PI/2,0,0)
scene.add(xy)

async def main():
    while True:
        renderer.render( scene, camera )
        await asyncio.sleep(0.02)
asyncio.ensure_future(main())
```

`pyscript.html`

```
<link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css"/>
<script defer src="https://pyscript.net/latest/pyscript.js"></script>
<py-config>
    packages = []
</py-config>
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        inlineMath: [ ['$','$'], ["\\(","\\)"] ],
        processEscapes: true
      }
    });
</script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

Everything basically works, but the problem is that it places the rendered animation off the quarto page.  Here is a screenshot:

![Screenshot 2023-08-29 092649](https://github.com/quarto-dev/quarto/assets/27108390/6f978272-bb45-4a25-8356-5e9f3b81cb29)

What I'm guessing is the problem, is that the PyScript HTML object that results, is getting placed after all of Quarto's HTML.  However, I don't really understand why that would be since it is inserted in-place and the `<py-script>` tag is inside the body of the page.  I tried having it output to a dedicated div element, but this still didn't change the rendering.  

I've also tried rendering this in pure HTML to see if that causes some kind of white space issue too, but it doesn't.  So my guess is that this is more a Quarto issue than a PyScript issue -- but I don't know.  Anyway, I'd appreciate any insight or fixes.

**Comment by cscheid** [comment]
Have you looked at the source of the resulting HTML to see if it matches your expectations?

**Comment by axiomtutor** [comment]
@cscheid  I have looked at the HTML and it doesn't match my expectations -- or at least, my hopes.  I have since asked about how to set the target of the PyScript render but didn't get anywhere with that.  Since that seems like a bit of a dead-end, I've started considering the possibility of instead using `pythreejs` instead.  Still I wasn't sure if somehow this was affected by Quarto styling since the large amount of white space does not appear when I put the same Three.js rendering inside bare HTML.

**Comment by cscheid** [comment]
> I have looked at the HTML and it doesn't match my expectations.

Ok, what did you expect and what looks different? Describing these explicitly in an issue will help us help you.

**Comment by dragonstyle** [comment]
trans1.py is where the connection to the document is happening, specifically:

```
document.body.appendChild( renderer.domElement )
```

which is placing the rendered element as the last thing in the HTML body. 

You should be able to target an element more specifically just by using `document.body.querySelector` to find which element you'd like to use when appending your rendered element (e.g. or you could place a DIV with an ID in the document and target that using `getElementById`).

Something like:

```
renderTarget = document.body.getElementById("p1")
renderTarget.appendChild( renderer.domElement )
```

HTH!
