### ISSUE TITLE
`ERROR: Expected front matter to end with '---'` when trying to Render RStudio's qmd template

### ISSUE THREAD

**Issue by dojobo** [quarto-dev/quarto-cli#665]
In RStudio I select File > New > Quarto Presentation... and fill the fields. Once the template qmd appears, I click on Render. I get this error in RStudio's Jobs tab: `ERROR: Expected front matter to end with '---'`. However, there is clearly a `---` at the end of the YAML header. I also tried replacing the hyphens and playing with the whitespace. The only way for the qmd to Render was to remove the header completely.

Running: Windows 10 x64, RStudio 2022.02.1 Build 461, Quarto 0.9.265.

Apologies if this is an RStudio issue rather than a Quarto one.

**Comment by jjallaire** [comment]
This looks like a legit issue on Windows (and it occurs outside of RStudio as well). We just landed a big change today which is likely the culprit. cc @cscheid

**Comment by jjallaire** [comment]
Thanks for reporting this! Fix is here: https://github.com/quarto-dev/quarto-cli/commit/59697d78364bff2db9a5fdaaf9da2a7cd82481e4

This fix is available in v0.9.267 (https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.267)
