### ISSUE TITLE
Author error in Quqrto Blog

### ISSUE THREAD

**Issue by shalom-lab** [quarto-dev/quarto-cli#666]
When  the AUTHOR only includes one word,such as "Shalom", the following erros arise, render fail. The error will disappear when AUTHOR  includes not less than two words. If I want to use a one-word nickname as author,what should I do?

Error running filter D:/Program Files/Quarto/share/filters/authors/authors.lua:
D:/Program Files/Quarto/share/filters/authors/authors.lua:1686: attempt to index a nil value (global 'n')
stack traceback:
	D:/Program Files/Quarto/share/filters/authors/authors.lua:1474: in function 'processAuthor'
	D:/Program Files/Quarto/share/filters/authors/authors.lua:1352: in function <D:/Program Files/Quarto/share/filters/authors/authors.lua:1336>

**Comment by jjallaire** [comment]
Thanks for reporting this. Addressed here: https://github.com/quarto-dev/quarto-cli/commit/2cf07759af16d6e3a2377befa59b7f13160c60e8

Fix is available in v0.9.270 (https://github.com/quarto-dev/quarto-cli/releases/latest)
