### ISSUE TITLE
Render a document from a script (.R, .py)

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#6660]
This idea cames from several discussion - especially on the R side as we have `knitr::spin()` and `rmarkdown::render()` working with R script

* https://github.com/quarto-dev/quarto-cli/discussions/4969
* https://github.com/yihui/knitr/issues/2284
* https://github.com/quarto-dev/quarto-cli/issues/588

`quarto render` could consider rendering to output format a .R / .py script that represents a notebook. 

* Existing syntax for R script to represent Notebook content (text, code, chunk option, ...): https://bookdown.org/yihui/rmarkdown-cookbook/spin.html
* Existing syntax for Python script to represent Notebook content: https://jupytext.readthedocs.io/en/latest/formats-scripts.html

## Notes

These are from internal discussion on this already

### General 

* This kind of feature would be opt-in to avoid rendering a script that shouldn't be. Probably by using a specific comment in the script that quarto could check
  * Example for .py : `# %% [markdown]` if we see this, then we auto render 
    ````
	# %% [markdown]
	# ---
	# title: "My document"
	# ---
	````

  * Other idea: Requiring a title field in YAML header
	  * For R 
	     ```
		#' ---
		#' title: "My document"
		#' ---
		```
	  * For Python
	     ```
		# %% [markdown]
		# ---
		# title: "My document"
		# ---
		```
	  
### For Python 

* The [percent format](https://jupytext.readthedocs.io/en/latest/formats-scripts.html#the-percent-format) seems a good idea considering it is widely used

This issue is to track the idea and have a place for further notes.

**Comment by kylebutts** [comment]
In this line, [VSCode has support](https://code.visualstudio.com/docs/python/jupyter-support-py) for plain `.py` files with the `# %%` code format: 

![CleanShot 2023-08-30 at 10 21 07@2x](https://github.com/quarto-dev/quarto-cli/assets/19961439/ddc1725e-3d34-422e-b68c-b9b2875966d2)

This lets you work with plain text files but have the ability to view output like a notebook. If this is your development flow (like it is mine), being able to "log" the script afterwards would be delightful!

**Comment by cderv** [comment]
1.4 prerelease support for rendering script using Jupyter engine
https://quarto.org/docs/prerelease/1.4/script.html

**knitr** engine support coming soon

**Comment by kylebutts** [comment]
Getting this to work (minimally) should work for an `.R` script with https://github.com/yihui/knitr/pull/2307

For markdown, currently you use roxygen style comments `#'`. Adding the option for `# %% [markdown]` and `# %% [raw]` should be possible with R raw strings with a some work on the `knitr::spin` function

`````md
# %% [markdown] 
r'(
# Header


)'
`````
