### ISSUE TITLE
Compatibility with Plotly FigureWidget

### ISSUE THREAD

**Issue by devmcp** [quarto-dev/quarto-cli#6663]
### Bug description

The following code renders an empty plot, when it is expected to show a plot with the added data trace:

```{python}
import plotly.graph_objects as go

fig_wid = go.FigureWidget()
fig_wid.add_trace(go.Scatter(x=[1, 2, 3]))
fig_wid
```

I'm not sure if this is a bug or a missing feature?

### Steps to reproduce

Example in Quarto doc:

````qmd
---
title: Test
format: html
---


```{python}
import plotly.graph_objects as go
```

Works as expected:
```{python}
fig = go.Figure()
fig.add_trace(go.Scatter(x=[1, 2, 3]))
fig
```

Works as expected:
```{python}
figwid = go.FigureWidget(go.Scatter(x=[1, 2, 3]))
figwid
```

Doesn't work, renders an empty plot:
```{python}
figwid = go.FigureWidget()
figwid.add_trace(go.Scatter(x=[1, 2, 3]))
figwid
```
````

### Expected behavior

Should get a plot with data:

![image](https://github.com/quarto-dev/quarto-cli/assets/48351339/0b3bcaaf-84e2-4da0-927e-17c8de5bafb8)

### Actual behavior

Get an empty plot:

![image](https://github.com/quarto-dev/quarto-cli/assets/48351339/22b84d44-ee47-4535-8728-3f897447f2ec)

### Your environment

IDE: Same with RStudio or Jupyter Lab
OS: Windows 11

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.8
      Path: C:/Users/mp59/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.2.2
      Path: C:/Users/mp59/AppData/Local/Programs/R/R-4.2.2
      LibPaths:
        - C:/Users/mp59/AppData/Local/R/win-library/4.2
        - C:/Users/mp59/AppData/Local/Programs/R/R-4.2.2/library
      knitr: 1.42
      rmarkdown: 2.20

[>] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
I think you'll find answer in this plotly documentation: https://plotly.com/python/renderers/#setting-the-default-renderer

If you follow example in our doc too (https://quarto.org/docs/interactive/widgets/jupyter.html), you would see that `fig.show()` is used to display figures. 

Adding it to your last cells makes it works
````
```{python}
fig = go.FigureWidget()
fig.add_trace(go.Scatter(x=[1, 2, 3]))
fig.show()
```
````

Example for `add_trace()` also use `fig.show()` : https://plotly.com/python/creating-and-updating-figures/#adding-traces

So I believe when using `fig.add__trace()`, something is not triggering the show method correctly if you do not explicitly call it. 

This is not at the Quarto level though.  You shoud look at the doc about renderers and configure accordingly or use the right display function

**Comment by cderv** [comment]
I'll close this as using `fig.show()` makes it work and is the documented way in plotly.

**Comment by devmcp** [comment]
Thanks for your swift response to this 🙏
