### ISSUE TITLE
`author` and `date` metadata arrays not read correctly

### ISSUE THREAD

**Issue by the-solipsist** [quarto-dev/quarto-cli#6680]
### Bug description

I'm building a website with my publications using Quarto, and creating citations for each page (publication) using Zotero & BetterBibTex.

### Steps to reproduce

If I have the following in the YAML metadata for a page, the "title metadata" block doesn't detect the author:
```
author:
  - family: Prakash
    given: Pranesh
```
However, if I have this, then it gets detected:
```
author:
  - name:
      family: Prakash
      given: Pranesh
```

The same is true in citation block as well.

Additionally, a date array is not parsed:

```
citation: 
  issued:
    - year: 2010
      month: 2
      day: 19
```

However, this works fine:
```
citation:
  issued: 2010-02-19
```

### Expected behavior

1. The name gets picked up in the title metadata block and citation
2. The date gets parsed correctly.

### Actual behavior

The YAML gets ignored.

### Your environment

- VS Code: 1.81.1 / x64
- OS: Linux Endeavour OS (Arch, rolling distro)

### Quarto check output

```bash
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by dragonstyle** [comment]
1. The first example isn't a valid author since the author name should be placed under the `name` key in this case. The YAML isn't really being ignored, the fields at the root level that are unrecognized are being normalized into `metadata` that is available to template authors. Generally, the name will be parsed from the string so this object syntax is really there to allow you the flexibility to control the detailed structure of complex names. 

2. For dates, the array syntax for you example would actually look like this:
    ```
    issued:
      - 2010
      - 2
      - 19
    ```
     The presence of the keys in the date (`year`, `month`, etc) make that an object rather than an array. Once again, this is   pretty low level syntax- the preferable way to provide a date is as an iso string (year-month-day) which will be parsed.

**Comment by dragonstyle** [comment]
This is helpful context (a good explanation for why this syntax is desirable / superior to what we have now). I take a look at supporting it...
