### ISSUE TITLE
Link does not work as shown in documentation

### ISSUE THREAD

**Issue by catmoez** [quarto-dev/quarto-cli#6682]
### Bug description

The official documentation says that links in the format [Google](google.com) will display as a link, but this does not work.

### Expected behavior

link to [Google](google.com)

### Actual behavior

no link to Google.com

**Comment by mcanouil** [comment]
Thanks for the report!

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````
