### ISSUE TITLE
Bootstrap code-bg SASS variable does not work

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#67]
Hello (related to Workbench docs conversion)-

I'm using Bootstrap SASS variables to change the way inline code looks:

```
/*-- scss:defaults --*/
$code-color: #702459;
$code-bg: #edf2f7;
```

The above works to change the text color of inline code (as intended), but the background color does not change.

Related: https://github.com/rstudio/rstudio-pro/issues/2756

**Comment by jjallaire** [comment]
@dragonstyle I looked through all of the bootstrap css we import and didn't see a `code-bg` variable. Do they have any standard variables that target this?

**Comment by apreshill** [comment]
If you're in BS5 it is here: https://github.com/rstudio/bslib/blob/78960cb/inst/lib/bs5/scss/_variables.scss#L1481

BS4: https://github.com/rstudio/bslib/blob/78960cb/inst/lib/bs4/scss/_variables.scss#L1192

**Comment by apreshill** [comment]
These are from bslib, but I presume they map onto Bootstrap variables?

**Comment by apreshill** [comment]
Just did a search in Bootstrap on GitHub and don't see this variable, so perhaps it is a bslib creation then?

**Comment by dragonstyle** [comment]
Yeah we do not - ours is currently `$code-background`. Would prob make sense to standardize this if possible...

**Comment by jjallaire** [comment]
Why don't we just change to `code-bg` then? (+ update the docs)

**Comment by dragonstyle** [comment]
This is what we provide currently, above and beyond BS:

```
$callout-border-width: 5px !default;
$callout-border-scale: 0% !default;
$callout-icon-scale: 10% !default;
$callout-margin-top: 1.25rem !default;
$callout-margin-bottom: 1.25rem !default;

// code-left-border
$code-border-left: false !default;
$code-border-left-style: solid !default;
$code-border-left-size: 3px !default;
$code-padding-left: 0.6em !default;

// code-background
$code-background: true !default;
$code-background-padding: 0.4em !default;
$code-background-alpha: -0.35 !default;

$code-theme-dark-threshhold: 40% !default;

$sidebar-bg: $body-bg !default;
```

This is a pretty good list - we could consider using either `-bg` or `-background` for both code and sidebar. Also on a separate thread we're thinking about adding `navbar-bg / navbar-background`...

**Comment by dragonstyle** [comment]
> Why don't we just change to `code-bg` then? (+ update the docs)

I can do this...

**Comment by apreshill** [comment]
When I test with the variable `$code-background`, it changes the background of my code chunks, but not the background of inline code

**Comment by apreshill** [comment]
In using the other formats, that is how this variable has been implemented (leaving styling of code chunks to the syntax highlighter). But I may be wrong here, I can test with flexdashboard quickly to see.

**Comment by apreshill** [comment]
OK update I am wrong! Flexdashboard applies `code-bg` to chunks *and* inline code:

![Uploading Screen Shot 2021-07-29 at 12.12.14 PM.png…]()

**Comment by apreshill** [comment]
`$code-color` on the other hand only does apply to inline code:
<img width="1413" alt="Screen Shot 2021-07-29 at 12 15 08 PM" src="https://user-images.githubusercontent.com/12160301/127552389-d8ab5c4a-058a-4db8-a2eb-69b1e3c52011.png">


```
    theme:
      code-color: red
      code-bg: orange
```

**Comment by jjallaire** [comment]
I do think it's valuable to distinguish between background treatment for
blocks and inline code.

**Comment by dragonstyle** [comment]
I'm going to take a second pass through all of our variables and see if I can get things a bit more consistent around:

sidebar
navbar
code-block
code

**Comment by dragonstyle** [comment]
This should work now! I added documentation of the most commonly used sass variables here:

https://quarto.org/docs/output-formats/html-themes-sass.html

We differentiate the treatment of `code` and `code-blocks`, but have variables supporting both.

**Comment by dragonstyle** [comment]
updated: https://quarto.org/docs/output-formats/html-themes.html#sass-variables
