### ISSUE TITLE
Warn if user provides SCSS theme files in documents within books / websites.

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#6703]
### Bug description

- I have a website with an [SCSS file](https://github.com/mine-cetinkaya-rundel/test-website/blob/main/styles.scss) that is being applied to all pages on the website. It's called from [`_quarto.yml`](https://github.com/mine-cetinkaya-rundel/test-website/blob/main/_quarto.yml): https://mine-cetinkaya-rundel.github.io/test-website/.

- I then have [another SCSS file](https://github.com/mine-cetinkaya-rundel/test-website/blob/main/posts/posts.scss) that should be applied to a subset of pages. This is not working as expected: https://mine-cetinkaya-rundel.github.io/test-website/posts/post1.html.

- However if I instead use a [CSS file](https://github.com/mine-cetinkaya-rundel/test-website/blob/main/posts/posts.css), styling works as expected: https://mine-cetinkaya-rundel.github.io/test-website/posts/post2.html.

### Steps to reproduce

The repo with the source code is at https://github.com/mine-cetinkaya-rundel/test-website.

### Your environment

- IDE: RStudio 2023.09.0 Build 380
- OS: Mac 13.5

### Quarto check output

```bash
Mines-MacBook-Pro:test-website mine$ quarto check
Quarto 1.4.346
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.346
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mine/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/mine/Desktop/teaching/Duke/sta113-f23/sta113-f23.github.io/renv/library/R-4.3/aarch64-apple-darwin20
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```

**Comment by dragonstyle** [comment]
SCSS does behave differently than CSS since any SCSS files are compiled into a single global stylesheet that is shared by the entire website. This is essential so that theme files have access to (and can redefine) the shared variables and rules used to theme the site. This also means that you can't provide per page themes within a website-  every page will inherit the CSS generated by the SCSS.

In the case of CSS, all that is really happening is that we're linking to the CSS file, which can be done on a per page bases.

**Comment by mine-cetinkaya-rundel** [comment]
This makes sense to me, except if you have revealjs slides inside a project you can have a separate SCSS file that applies to only a subset of pages (slides). I think this might be because slides don't behave like child pages of a website.

**Comment by dragonstyle** [comment]
That is just so - you are exactly correct! Basically any page which takes on the appearance of the website itself will use a single CSS theme generated from the SCSS file. In the case of RevealJS, they don't use site styling, but just use their own styling / theming.

**Comment by dragonstyle** [comment]
Yes indeed - I am going to update title of this issue and re-open.

**Comment by asmaier** [comment]
Unfortunately the documentation at https://quarto.org/docs/output-formats/html-themes.html only mentions SCSS files to define custom themes. Maybe the problem discussed here, that it is not possible to have different themes defined by SCSS in subdirectories, should be mentioned in the documentation. 

Also how can I create a custom theme using only css, not scss , so that I can have different themes in different subdirectories?

**Comment by asmaier** [comment]
Another observation: When I render each subdirectory individually my custom themes based on SCSS are used correctly. However even with `freeze` set to `true`, when I run `quarto render` in the root directory all custom theming is lost again. I think this is confusing. I expected freeze to also freeze the theme of each subdirectory, but that doesn't seem to be the case.

**Comment by dragonstyle** [comment]
> Also how can I create a custom theme using only css, not scss , so that I can have different themes in different subdirectories?

You can just include css files directly like so:

```
---
title: "My document"
format:
  html:
    toc: true
    html-math-method: katex
    css: styles.css
---
```

>  I expected freeze to also freeze the theme of each subdirectory, but that doesn't seem to be the case.

Freeze is related to the execution of code within documents (it freezes the output of code execution). It isn't related to theming or the rendering of markdown itself within the document.

Websites and books share a single site wide `scss` generated theme, so it isn't possible to theme sections or pages using `scss`. Using a `css` file would be a good approach.

**Comment by cscheid** [comment]
> I think this is confusing. I expected freeze to also freeze the theme of each subdirectory

I see where you're coming from, but our [freeze documentation](https://quarto.org/docs/projects/code-execution.html#freeze) is relatively explicit about `freeze` being about computational content, and not themes. Did something explicit in our docs make you think that?

**Comment by asmaier** [comment]
From the documentation
> You can use the freeze option to denote that computational documents should never be re-rendered during a global project render
It says "should never be re-rendered". For me that implies, that the
layout and style of the document should not change.

**Comment by mcanouil** [comment]
We could update/replace "documents" by "elements" then.

**Comment by cscheid** [comment]
@asmaier you're right, that's bad wording on our part. It was probably meant under the "computational documents" qualification (that is, running `knitr` or `jupyter`). We need more consistent wording, especially since `render` is used as the overall verb.

**Comment by asmaier** [comment]
Actually I have exactly the problem described by https://github.com/quarto-dev/quarto-cli/issues/6703#issuecomment-1706806146 . 

I have a website with an overview of several revealjs presentations. But even without using custom SCSS there is an issue: It doesn't seem to be possible that the revealjs presentations in different subfolders can have different themes. See my test repo and test website here:

* https://github.com/asmaier/test-presentations
* https://asmaier.github.io/test-presentations/

I would expect one presentation to use the dark theme and the other presentation should use the default theme. But when rendering the project in the root folder with `quarto render`, all presentations just use the dark theme. Or am I doing something wrong here?
