### ISSUE TITLE
Reinstalling extension results in noninformative error

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#6707]
### Bug description

Reinstalling an extension results in a non-informative / diffcult-to-decipher error. For example, this is what I get when I install and then re-install the lightbox extension:

```bash
ERROR: TypeError: error sending request for url (https://codeload.github.com/quarto-ext/lightbox/tar.gz/refs/heads/main#undefined): http2 error: stream error received: refused stream before processing any application logic

Stack trace:
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
    at async extensionSource (file:///Applications/quarto/bin/quarto.js:97550:26)
    at async installExtension (file:///Applications/quarto/bin/quarto.js:97719:20)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:105044:13)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8105:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:110974:5)
    at async file:///Applications/quarto/bin/quarto.js:110992:9
```

This behavior is not specific to lightbox, happens with fontawesome extension as well.

### Steps to reproduce

Install the lightbox extension with

```bash
quarto add quarto-ext/lightbox
```

Once successfully installed, install again with the same command.

### Expected behavior

I would expect an error like "Already installed, do you want to overwrite?", in case the extension has been updated since last time installed.

### Actual behavior

The error is shown above.

### Your environment

- IDE: RStudio 2023.09.0 Build 380
- OS: Mac 13.5

### Quarto check output

```bash
Mines-MacBook-Pro:test-website mine$ quarto check
Quarto 1.4.346
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.346
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mine/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/mine/Desktop/teaching/Duke/sta113-f23/sta113-f23.github.io/renv/library/R-4.3/aarch64-apple-darwin20
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
I wonder if it could be transcient as Github has some issues recently. We have some test failing currently also regarding extension installation. 

I tried to reproduce on Linux, and I can't recreate the issue. 

First time you install 
````bash
$ quarto add quarto-ext/lightbox --no-prompt
[✓] Downloading
[✓] Unzipping
    Found 1 extension.

The following changes will be made:
Lightbox   [Install]   0.1.9 (filter)

[✓] Extension installation complete.
Learn more about this extension at https://www.github.com/quarto-ext/lightbox
```` 

Second times right after tells you no change 
````bash
$ quarto add quarto-ext/lightbox --no-prompt
[✓] Downloading
[✓] Unzipping
    Found 1 extension.

The following changes will be made:
Lightbox   [No Change]    (filter)

[✓] Extension installation complete.
Learn more about this extension at https://www.github.com/quarto-ext/lightbox
````

We'll probably retry later today - or maybe it is related somehow to MacOS

**Comment by mcanouil** [comment]
Is it on a shared drive of some kind? What's the access rights on the directory in which the extension is installed?

**Comment by mine-cetinkaya-rundel** [comment]
No it's not a shared drive.

Based on the comment re: potential network issues, I tried again this morning in the same directory and things worked as expected:

```
Mines-MacBook-Pro:test-website mine$ quarto add quarto-ext/lightbox

Quarto extensions may execute code when documents are rendered. If you do not 
trust the authors of the extension, we recommend that you do not install or 
use the extension.
 ? Do you trust the authors of this extension (Y/n) › Yes
[✓] Downloading
[✓] Unzipping
    Found 1 extension.

The following changes will be made:
Lightbox   [No Change]    (filter)
 ? Would you like to continue (Y/n) › Yes

[✓] Extension installation complete.
Learn more about this extension at https://www.github.com/quarto-ext/lightbox 
```

So, I imagine this was an issue on my end, so this issue can be closed, unless there's a better message Quarto could have emitted at the time. I did try multiple times over a ~15 min period so it wasn't a single blip, but perhaps trying too many times contributed to the issue.

**Comment by cderv** [comment]
I don't know if we can do better here 🤔 I am thinking this could also be some server issue when contacting github which would not process. Just thinking that because we have other issue related to accessing some github endpoint since yesterday in our ci. But different error. 

Anyhow, I'll let @dragonstyle give its thought about maybe better error message if we can detect a wrong communication when downloading from github.
