### ISSUE TITLE
YAML project validation fails with recent releases

### ISSUE THREAD

**Issue by jchiquet** [quarto-dev/quarto-cli#672]
Rendering a quarto document with format HTML / article fails at the yaml validation stage, at least since last Sunday (everything was working until then).

Have you tightened these validation rules recently?

The error message is the following (see [there for details](https://github.com/computorg/template-computo-quarto/actions/runs/2178416467)):

```
ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 4, column 5 through line 32, column [25](https://github.com/computorg/template-computo-quarto/runs/6050879186?check_suite_focus=true#step:5:25)) Key html has value page-layout: article
    include-in-header: includes/pseudocode-header.html
...
    html-math-method: katex
    self-contained: true, which must be 'default'
 3:   html:
 4:     page-layout: article
        ~~~~~~~~~~~~~~~~~~~~
 5:     include-in-header: includes/pseudocode-header.html
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
31:     html-math-method: katex
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
32:     self-contained: true
    ~~~~~~~~~~~~~~~~~~~~~~~~
33: crossref:
```

The configuration file is there:

[https://github.com/computorg/template-computo-quarto/blob/main/_quarto.yml](https://github.com/computorg/template-computo-quarto/blob/main/_quarto.yml)

I have tried to change or comment on various options without success. I suspect maybe a parsing problem in the yaml check.

Thank you for your help

**Comment by jjallaire** [comment]
I can repro this locally (note that it also affects vscode and rstudio yaml diagnostics). @cscheid I've disabled project file validation entirely here: https://github.com/quarto-dev/quarto-cli/commit/1afc228c288977028ae77b62e764cab41016c33c

@jchiquet The build with this change is v0.9.274: https://github.com/quarto-dev/quarto-cli/releases/latest

@cscheid It appears to me as if this is the YAML that is causing the validator to barf:

```yaml
 toc-title: >
      <a href="https://computo.sfds.asso.fr"><img style="width: 96px;" alt="Computo" src="https://computo.sfds.asso.fr/assets/img/logo_text_vertical.svg"/></a> <br/><br/>
      Contents
```

**Comment by cscheid** [comment]
It's a simple fix, coming right up. Our code only understands `literal`-style block scalars, and not `folded`-style block scalars. I'm sorry about that, @jchiquet !

**Comment by jchiquet** [comment]
no need to say sorry! Thanks for the quick diagnosis.

**Comment by cscheid** [comment]
Here is a [relevant unit test I added, passing](https://github.com/quarto-dev/quarto-cli/runs/6065306499?check_suite_focus=true#step:11:309). This should be fixed in our next release. Thanks!

**Comment by cscheid** [comment]
I'm going to close this, but please reopen if the latest release (as of about half an hour ago) doesn't solve the issue for you!
