### ISSUE TITLE
missing callout label (`caution` and `danger`)

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#673]
While testing the translation function, I noticed that "callout-caution" is not a target for translation.
I also noticed that "callout-danger" is not listed in the reference and [no image is provided](https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/docx).

https://github.com/quarto-dev/quarto-cli/blob/a84fe78aea1a3cbd0ee086d6a1a6a92c86cd59c5/src/resources/language/_language.yml#L20-L24

https://quarto.org/docs/authoring/markdown-basics.html#callout-blocks

![image](https://user-images.githubusercontent.com/50911393/163791436-8576a8e2-1707-4f97-833e-d72ec8647c09.png)

Try rendering the following Markdown file:

````qmd
---
title: test
# lang: ja
---

:::{.callout-note}
test
:::
:::{.callout-tip}
test
:::
:::{.callout-warning}
test
:::
:::{.callout-caution}
test
:::
:::{.callout-important}
test
:::
:::{.callout-danger}
test
:::

````

![image](https://user-images.githubusercontent.com/50911393/163792256-e7f5170b-2e70-4c93-af02-7144efa4f0f6.png)

When set to `lang: ja`

![image](https://user-images.githubusercontent.com/50911393/163792720-3cead1f5-8e62-453d-8b62-dfb8904ba06d.png)

**Comment by jjallaire** [comment]
@dragonstyle It looks like "callout-danger" (which we don't actually support) is currently localized rather than "callout-caution". Could you take a look at this? I think it's fine to use Google Translate for this commit and then cc all of the folks that originally provided translations for input/revision.

**Comment by dragonstyle** [comment]
OK this is corrected now (danger isn't a valid callout type, so just a mistake on my part when localizing). Caution should be properly supported now as of fd269312c4084e977b2df9c5f61527239cc76ca4 .

New release is being built!
