### ISSUE TITLE
(Python) Syntax highliting was broken?

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#674]
After rendering a flatly themed (i.e., switchable between light and dark mode) website containing Python code blocks, I noticed that the Python code blocks were hard to see.
Is this change intentional?
It would be easier to read if they were color coded as before.

quarto 0.9.272

![image](https://user-images.githubusercontent.com/50911393/163794565-b1094f1f-3b29-47a2-b805-417405261220.png)

quarto 0.9.100

![image](https://user-images.githubusercontent.com/50911393/163795216-85318341-09ef-4101-860b-207b1d1cd720.png)

When compared to the syntax highlighting on GitHub below, does it look like the syntax highlighting is too close in color rather than broken?

````qmd
---
title: test
theme: flatly
---

```py
import pandas as pd
pd.read_csv("test.csv")
```

```r
library(readr)
readr::read_csv("test.csv")
```
````

**Comment by dragonstyle** [comment]
Thanks for reporting this. I agree that this took a step backwards (although interestingly, the previous version wasn't properly applying the theme to the black text - we fixed that bug and the properly applied theme wasn't as readable!). I've tweaked the appearance of arrow light to try to improve the readability and make it closer to what we were previously rendering (here: https://github.com/quarto-dev/quarto-cli/commit/efebd73c4426f5cf4f54eed7d2aafc87a65f8ca2 ). A fresh release is being built now!

**Comment by dragonstyle** [comment]
Great catch! A small typo in our dark theme version, which has been fixed (7e360ff885985e243976d1adbf339ba542f678a5). I've started a fresh release...

**Comment by eitsupi** [comment]
Thanks, it looks nice!

![image](https://user-images.githubusercontent.com/50911393/164247803-cd3084f1-5f22-4276-8fd5-7522870db4c3.png)
![image](https://user-images.githubusercontent.com/50911393/164247812-48c736b6-c8e9-42ca-a24f-aeebafe89952.png)

**Comment by dragonstyle** [comment]
It's looking much better! Thanks for for finding these for us!
