### ISSUE TITLE
r inline code does work when starting a new book project without an r junk

### ISSUE THREAD

**Issue by petzi53** [quarto-dev/quarto-cli#6752]
### Bug description

When I start a new Quarto book project with just text and R inline code in it—but (yet) not an R code junk --, the r inline code is not evaluated.

When I add an R code chunk (even this code chunk is empty, or `#| eval: false` and / or `#| include: false`) the R inline code evaluates correctly. It doesn't matter where the code chunk appears. If the R code chunk appears after the inline code, the inline R code is still evaluated.

### Steps to reproduce

````
---
title: "Test Inline R Code"
format: html
---


2 + 2 = `r 2 + 2`.
````

### Expected behavior

2 + 2 = 4.

### Actual behavior

2 + 2 = r 2 + 2.

### Your environment

IDE RStudio Version 2023.06.2+561 (2023.06.2+561)
MacOS 13.5.1

### Quarto check output

Quarto 1.4.349
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.7: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.349
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /Users/petzi/anaconda3/bin/python
      Jupyter: 5.2.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

(|) Checking R installation...........R version 4.3.1 (2023-06-16)
[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/library
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK

**Comment by cderv** [comment]
@petzi53 For reference, our documentation about engine binding is at https://quarto.org/docs/computations/execution-options.html#engine-binding and you can understand how this is triggered. 

Also duplicate of 
* https://github.com/quarto-dev/quarto-cli/issues/5349

where you'll find some discussion about the change too.

**Comment by petzi53** [comment]
Thank you for the links and the explanation. It works when I include `engine: knitr` in the YAML header of the file. But as I am working on a Quarto book, I added `engine: knitr` in the `_quarto.yml` file. But this does not work.

Additionally: I have in all my books, e.g., in my  `_quarto.yml` files the following lines:

```
knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true
```

As I understand, this should be enough to work: "Variations with additional engine-specific options also work to override the default engine" ([Engine binding](https://quarto.org/docs/computations/execution-options.html#engine-binding)). So my problem never should have been arisen.

There is a [GitHub repo](https://github.com/petzi53/bayesian-fun) to inspect my problem.

**Comment by mcanouil** [comment]
See:
- https://github.com/quarto-dev/quarto-cli/issues/3157

**Comment by petzi53** [comment]
This is precisely what I have done, with the only difference that my project is not a website but a book. But it does not work for me. I did not open the project via terminal but via RStudio "New Project…". But this shouldn't make any difference.

**Comment by cderv** [comment]
> This is precisely what I have done,

What have you done ? If you have done what is described in #3157 then this is expected to not work as the issue is still opened. 

`engine` needs to be set by document for now, and not at project level.

**Comment by petzi53** [comment]
Oh, thank you for the clarification. I misunderstood [#3157](https://github.com/quarto-dev/quarto-cli/issues/3157).
