### ISSUE TITLE
Could not find executable when trying to use a filter whose name doesn't correspond to the extension name

### ISSUE THREAD

**Issue by multimeric** [quarto-dev/quarto-cli#6754]
### Bug description

If the name of the filter does not correspond to the name of the extension, you will get the following error when trying to use it:
```
Error running filter /Users/milton.m/Applications/quarto/share/filters/main.lua:
Error running filter /private/var/folders/q5/fvpyppm924525yl9m3xpgjm400031g/T/tmp.DN29oBXb/quarto-filter-name-bug/bar:
Could not find executable /private/var/folders/q5/fvpyppm924525yl9m3xpgjm400031g/T/tmp.DN29oBXb/quarto-filter-name-bug/bar
stack traceback:
	/Users/milton.m/Applications/quarto/share/filters/main.lua:4030: in function </Users/milton.m/Applications/quarto/share/filters/main.lua:4009>
	[C]: in ?
	[C]: in method 'walk'
	/Users/milton.m/Applications/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	/Users/milton.m/Applications/quarto/share/filters/main.lua:449: in local 'callback'
	/Users/milton.m/Applications/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
	/Users/milton.m/Applications/quarto/share/filters/main.lua:495: in function </Users/milton.m/Applications/quarto/share/filters/main.lua:476>
stack traceback:
	/Users/milton.m/Applications/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	/Users/milton.m/Applications/quarto/share/filters/main.lua:449: in local 'callback'
	/Users/milton.m/Applications/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
	/Users/milton.m/Applications/quarto/share/filters/main.lua:495: in function </Users/milton.m/Applications/quarto/share/filters/main.lua:476>
```

### Steps to reproduce

The exact code and instructions to replicate this bug can be found here: https://github.com/multimeric/quarto-filter-name-bug.

In short, run the following:
```bash
git clone https://github.com/multimeric/quarto-filter-name-bug.git
cd quarto-filter-name-bug
quarto render example.qmd
```

### Expected behavior

Since `contributes.filters` is an array, it is my expectation that each extension can export multiple filters. The documentation doesn't clarify one way or the other. Thus, I would expect an extension called `foo` that exports a filter called `bar` to work perfectly.

### Actual behavior

An error is thrown, as seen above.

### Your environment

- OS: MacOS Monterey 12.6
- VS Code Version: 1.79.2 

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Users/milton.m/Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.16 (Conda)
      Path: /opt/anaconda3/bin/python
      Jupyter: 4.11.1
      Kernels: bash, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /opt/homebrew/Cellar/r/4.3.1/lib/R
      LibPaths:
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.1/lib/R/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK
```

**Comment by dragonstyle** [comment]
This is not an issue as this is working as expected. Extensions can contribute one or more filters (as you expect) - each of the filters will be included in the rendering when the *extension name* is placed in the list of filters by the user.

So in your example, the qmd should read:

```markdown
---
title: "Foo Example"
filters:
  - foo
---

## Heading

This filter adds formatting to heading text.
```

for extension yaml like:

```yaml
title: Foo
author: Michael Milton
version: 1.0.0
quarto-required: ">=1.3.0"
contributes:
  filters:
    - bar.lua
    - bar2.lua
```

which would result in both the `bar.lua` and `bar2.lua` filters being used when rendering (all the filters that the extension contributes will be used).

When you use an extension that provides LUA filter(s), you can't target the individual filters directly (that would require 'seeing inside' the extension), you simply place the name of the extension in the list of filters and its filters will be merged.

You have a couple of options if you'd like to do something complicated with multiple filters:

1) Package the extensions separately (1 extension for distinct filter that can be loaded).

2) Writer a single root filter that uses metadata or other user input to determine what code to execute and what filtering to perform conditionally.

HTH!

**Comment by multimeric** [comment]
Thanks, yes that does help. It would be great for this to be in the documentation actually, but at least having this answer here on GitHub will help people who encounter this same issue!

**Comment by dragonstyle** [comment]
I'll reopen this a doc bug to try to improve that part of the docs! Thanks for reporting with such a clear repro, it made understanding the question/issue really easy!

**Comment by cderv** [comment]
TIL - did not know that. 

We should definitely not use the same for extension name a filter name in our doc: https://quarto.org/docs/extensions/filters.html#quick-start as I think the value in `filters` field was the name of the lua filters 😅 
Mainly because this what you do when using a local filter (not in an extension) (https://quarto.org/docs/extensions/filters.html#activating-filters) 

This was not expected ! 🤯  

Thank for asking the question @multimeric !
