### ISSUE TITLE
`identifier-prefix` breaks internal links pointing to another page

### ISSUE THREAD

**Issue by edornshuld** [quarto-dev/quarto-cli#6763]
### Bug description

Using `identifier-prefix` in a Quarto book can break internal links.

Consider a simple case of two files: file1.qmd and file2.qmd

file1.qmd contains the following internal links:

- #link-to-section-A-in-file1 (producing file1.html#link-to-section-A-in-file1)
- #link-to-section-B-in-file2 (producing file2.html#link-to-section-B-in-file2)

When placing the following YAML at the top of file1.qmd and file2.qmd

```
format:
    html:
        identifier-prefix: foo
```

the internal links in file1.qmd _compile to_

- #foo-link-to-section-A-in-file1 (producing file1.html#foo-link-to-section-A-in-file1)
- #foo-link-to-section-B-in-file2 (producing file1.html#foo-link-to-section-B-in-file2)

Notice how the second internal link now points to **a non-existent section file1 when it should be pointing to file2**.

### Expected behavior

I would have expected that the links would point to the appropriate files but `identifier-prefix` seems to change this.

### Your environment

- IDE: RStudio 2023.06.1 Build 524
- OS: Windows 10
- Quarto 1.3.450

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.5
      Path: C:/Python/Python39/python.exe
      Jupyter: 4.7.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/R/R-4.3.1
      LibPaths:
        - C:/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.23.4

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report!

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````
