### ISSUE TITLE
typos, sorry

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-cli#677]
Don't really know how to do PRs or I would do one.

However, FYI, in lines 16  and 17 of [_language.yml](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml), "Affilliation" and "Affilliations" should have only one "l".

**Comment by jjallaire** [comment]
Thanks! Note that to do a PR for a simple typo you can just hit the "Edit"
button on the file, make the correction, then GitHub will automate creating
a PR.
