### ISSUE TITLE
Code annotation does not for SQL code.

### ISSUE THREAD

**Issue by yoonghm** [quarto-dev/quarto-cli#6788]
### Bug description

Code annotation does not work for SQL code but work for Python code:

```SQL
SELECT * FROM users LIMIT 10;                                 # <1>
```

```Python
SELECT AVG(age) FROM users WHERE country = 'Singapore';       # <2>
```

These code is rendered below:

![image](https://github.com/quarto-dev/quarto-cli/assets/4215991/94ece3b5-e985-4014-952f-4ce6cdfe299c)

**Comment by eitsupi** [comment]
Isn't it because the comment character in SQL is `--`?

**Comment by mcanouil** [comment]
Please provide a complete Quarto document, currently we can't reproduce what you are seeing.

Note the following is perfectly working.

````qmd
---
title: "Quarto Playground"
format: html
code-annotations: true
---

This is a playground for Quarto.

```sql
SELECT * FROM users LIMIT 10;    -- <1>
```

1. A SQL query
````

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/0289b3f8-215c-4e55-b8a1-e592b7820260">

**Comment by yoonghm** [comment]
I know the issue now. I should have use `--` instead of `#` in SQL code. Thanks.
