### ISSUE TITLE
@Citation fails to include first authors name in the text

### ISSUE THREAD

**Issue by rwbaer** [quarto-dev/quarto-cli#6790]
### Bug description

Attempt to use **insert > citation > R package**  to reference an R package named openCyto from Bioconductor.  The citation() function shows an @Article format.  

The reference in the Reference section looks okay, but the citation rendered in the text fails to include the Finak name of **Finak et al 2014**  and only says **et al 2014**.

I don't know if the fact that the citation has about 10 authors is affecting things or something else.  don't know if it is package specific way the citation was inscibed in source or the way quarto is rendering it. 

### Steps to reproduce

A reproducible example of the citation problem is show in the  .qmd file entitled: 

````` qmd
---
title: "Illustrate OpenCyto Citation problem"
format: 
  html:
    embed-resources: true
editor: visual
bibliography: references.bib
---

## Making a citation to a well-known BioConducter Package

The paragraph below illustrates working and non-working versions of R package citations.

When doing flow cytometry analysis in R, two packages of great interest are flowWorkspace [@flowWorkspace] and openCyto. [@openCyto-2]

Notice that the first author is missing from the openCyto citation. We can try using the other format to cite openCyto and see if it works better. @openCyto-4

Here is some R code for looking at the citations

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("openCyto")


library(openCyto)
library(flowWorkspace)


citation("flowWorkspace")
citation("openCyto")


```

## References



`````

### Expected behavior

Expected behavior was to cite the R package openCyto from Bioconductor as Finak et al 2014 as implied in the rendered Reference list.  The uploaded .qmd file will demostrate the behavior and show the entry for this package extracted by the citation() R function.

### Actual behavior

 Citation for  the R package "openCyto" from Bioconductor is simply "et al 2014" rather than "Finak et al 2014"

### Your environment

RStudio 2023.06.2 Build 561 Windows 11

> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 25941)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggcyto_1.28.1        ncdfFlow_2.46.0      BH_1.81.0-1          flowCore_2.12.2     
[5] ggplot2_3.4.3        flowWorkspace_4.12.1 **openCyto_2.12.0**     

loaded via a namespace (and not attached):
 [1] utf8_1.2.3          generics_0.1.3      lattice_0.21-8      magrittr_2.0.3     
 [5] grid_4.3.1          RColorBrewer_1.1-3  plyr_1.8.8          graph_1.78.0       
 [9] gridExtra_2.3       fansi_1.0.4         scales_1.2.1        XML_3.99-0.14      
[13] Rgraphviz_2.44.0    cli_3.6.1           rlang_1.1.1         RProtoBufLib_2.12.1
[17] Biobase_2.60.0      munsell_0.5.0       withr_2.5.0         cytolib_2.12.1     
[21] tools_4.3.1         parallel_4.3.1      dplyr_1.1.3         colorspace_2.1-0   
[25] BiocGenerics_0.46.0 vctrs_0.6.3         R6_2.5.1            matrixStats_1.0.0  
[29] stats4_4.3.1        lifecycle_1.0.3     zlibbioc_1.46.0     S4Vectors_0.38.1   
[33] RBGL_1.76.0         pkgconfig_2.0.3     pillar_1.9.0        hexbin_1.28.3      
[37] gtable_0.3.4        rsconnect_1.1.0     data.table_1.14.8   glue_1.6.2         
[41] Rcpp_1.0.11         flowClust_3.38.0    xfun_0.40           tibble_3.2.1       
[45] tidyselect_1.2.0    rstudioapi_0.15.0   knitr_1.43          compiler_4.3.1

**Comment by mcanouil** [comment]
Is it from the Visual editor menu?

**Comment by rwbaer** [comment]
Thanks for the information on self-contained.  I'm a "first time outer newbie" so such notes are quit helpful.

The references.bib is attached as a .zip.  It seems to have a extra leading comma for the reference in question, but I created the refterence directly by the R package citation using Insert > Citation > R Package.  This in turn created the references.bib file.

Here is what the rendered text lookl like:

```
When doing flow cytometry analysis in R, two packages of great interest are flowWorkspace ([Finak and Jiang 2023](http://localhost:4739/#ref-flowWorkspace)) and openCyto ([ et al. 2014](http://localhost:4739/#ref-openCyto)).

Notice that the first author is missing from the openCyto citation. We can try using the other format to cite openCyto and see if it works better et al. ([2014](http://localhost:4739/#ref-openCyto)).
```
[references.zip](https://github.com/quarto-dev/quarto-cli/files/12578040/references.zip)

**Comment by rwbaer** [comment]
IF it helps, here is what access to the original citation look like from the R command line:

```
> citation("openCyto")
To cite package ‘openCyto’ in publications use:

  Finak G., Frelinger J., Newell E.W., Ramey J., Davis M.M., Kalams S.A., De Rosa S.C., Gottardo R. (2014) OpenCyto: An Open Source
  Infrastructure for Scalable, Robust, Reproducible, and Automated, End-to-End Flow Cytometry Data Analysis. PLoS Comput Biol
  10:e1003806.

A BibTeX entry for LaTeX users is

  @Article{Finak2014,
    author = {{Finak, Greg} and {Frelinger, Jacob} and {Jiang, Wenxin} and {Newell, Evan W.} and {Ramey, John} and {Davis, Mark M.} and {Kalams, Spyros A.} and {{De Rosa}, Stephen C.} and {Gottardo, Raphael}},
    journal = {PLoS Computational Biology},
    keywords = {Bioinformatics,Biology and life sciences,Computer and information sciences,Computer architecture,Computer software,Cytophotometry,Database and informatics methods,Flow cytometry,Immunology,Medicine and health sciences,Open source software,Pipelines (computing),Preventive medicine,Public and occupational health,Research Article,Research and analysis methods,Software engineering,Software pipelines,Software tools,Spectrophotometry,Spectrum analysis techniques,Vaccination and immunization,Vaccine development},
    month = {Aug},
    number = {8},
    pages = {e1003806},
    publisher = {Public Library of Science},
    title = {OpenCyto: An Open Source Infrastructure for Scalable, Robust, Reproducible, and Automated, End-to-End Flow Cytometry Data Analysis},
    volume = {10},
    year = {2014},
  }
```

**Comment by mcanouil** [comment]
I still don't know what "Insert > Citation > R Package" means or where it comes from.

**Comment by rwbaer** [comment]
This is from RStudio 2023.06.2 Build 561on Windows 11 Build 22H2 22631.1835.

It is the menu driven way to insert a citation into a .qmd document.  It theoretically goes out to the R package in question and uses the built in citation in the header of the R package as I understand it.  You should be able to see the citation from within R I expect by using the R citation() command.

**Comment by mcanouil** [comment]
It seems to be an RStudio issue which should be reported in the appropriate repository if not already reported, see <https://github.com/rstudio/rstudio>.

Also, to extract R packages references, `knitr` offers a function to properly extract the citations: `knitr::write_bib(c("flowWorkspace", "openCyto"), "references.bib")` which you can use in the text.
