### ISSUE TITLE
Bootstrap navbar-bg SASS variable does not work

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#68]
Hello (related to Workbench docs conversion)-

```
/*-- scss:defaults --*/
$navbar-bg: #fff;
```

I also tried: $navbar-light-bg. Is there a different variable that works here? No matter what I try to change I see:
<img width="1413" alt="Screen Shot 2021-07-29 at 11 06 17 AM" src="https://user-images.githubusercontent.com/12160301/127543433-e7b667d4-8e7c-4097-bf17-b0670af47ec1.png">

This ultimately works, but a Bootstrap SASS variable should work:

```
/*
.bg-primary {
  background-color: #ffffff !important;
}*/
```

**Comment by apreshill** [comment]
Ah! Thank you- that makes sense. Still learning the Bootstrap ropes myself, but in the absence of one of these variables that cascade makes sense, but if one of these is set, I would expect it to override `$primary`

<img width="1413" alt="Screen Shot 2021-07-29 at 11 40 52 AM" src="https://user-images.githubusercontent.com/12160301/127548129-3d0b6421-dbf5-4fa0-8024-84dea119a5ba.png">

I believe `navbar-bg` is empowered by flexdashboard and will be by pkgdown too: https://pkgs.rstudio.com/flexdashboard/articles/theme.html

So folks like me may start memorizing that variable.

**Comment by dragonstyle** [comment]
Let me take a second look - I had exactly the same initial reaction....

**Comment by dragonstyle** [comment]
This should work now! I added documentation of the most commonly used sass variables here:

https://quarto.org/docs/output-formats/html-themes-sass.html

**Comment by dragonstyle** [comment]
updated: https://quarto.org/docs/output-formats/html-themes.html#sass-variables
