### ISSUE TITLE
Invalid ARIA attribute for tabsets (due to typo)

### ISSUE THREAD

**Issue by batpigandme** [quarto-dev/quarto-cli#681]
Apologies for not knowing where to fix what appears to be a simple typo. In Quarto books (and I'm guessing websites as well) the `div`s for a tabset looks something like:
``` html
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labeledby="tabset-1-1-tab">
...
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labeledby="tabset-2-1-tab">
```
The issue is that `aria-labeledby` is missing an "l" (it should be [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby)).

Thanks!

**Comment by dragonstyle** [comment]
Nice one! This should be fixed in our next release!
