### ISSUE TITLE
Typst: use tablex for output

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#6811]
https://github.com/PgBiel/typst-tablex offers great table support. We should be able to use Pandoc's new table AST (with row and colspans) and compile it down to a tablex statement.

**Comment by reknih** [comment]
Just wanted to note that the stock Typst table (0.11) now supports row and colspans

**Comment by gordonwoodhull** [comment]
Thanks @reknih, yes, these features just landed in Pandoc and I've been testing them with Typst 0.11 for Quarto 1.5. (They work great!)

@cscheid, are there other reasons for considering tablex or should we close this?

**Comment by mcanouil** [comment]
I believe the reason was mostly because there were no native thing at the time, and `tablex` was the only thing available.
So, I would go in favour of closing this in favour of the native new features from Typst v0.11. (it avoids adding a dependency also)

**Comment by cderv** [comment]
I believe the new item about Typst 0.11 in tablex readme is to read 
https://github.com/PgBiel/typst-tablex#important-note-regarding-typst-0110-and-tablex

> A large amount of tablex's features have successfully been upstreamed by this package's author to Typst's built-in table and grid elements

The new Typst support has been done by the author of tables

> Therefore, for the vast majority of use cases, you will no longer need to use this library
> (...)
> Not all tablex features are present in built-in tables, at least yet. (...). It is expected, however, that built-in tables will eventually have support for most of the missing features in future Typst releases.

I think **tablex** won't be needed and we can indeed close this @gordonwoodhull  !

**Comment by gordonwoodhull** [comment]
Nice!
