### ISSUE TITLE
Compilation failed to PDF with Quarto 1.4.358

### ISSUE THREAD

**Issue by lorenzoFabbri** [quarto-dev/quarto-cli#6819]
### Bug description

I am trying to render a Quarto document that was rendering fine with the latest release. I am now using Quarto version 1.4.358, and I get the following error message:
```
Rendering PDF
running lualatex - 1
  This is LuaHBTeX, Version 1.17.0 (TeX Live 2023) 
   restricted system commands enabled.
  
updating tlmgr
-
updating existing packages
ERROR: 
compilation failed- error
LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.544 \end{CSLReferences}
```

### Steps to reproduce

I have the following in the YAML:
```
---
title: "Some Fancy Title"

metadata-files:
  - ../../../../all_phd/authors.yml

format:
  docx:
    reference-doc: reference_document.docx
  pdf:
    pdf-engine: lualatex
    number-sections: true
    toc: false
    keep-tex: true
    include-in-header:
      text: |
        \usepackage{lineno}
        \usepackage{rotating}
        \usepackage{float}
        \usepackage{typearea}
    include-before-body:
      text: |
        \linenumbers

bibliography: bibliography.bib
csl: ama11.csl

link-citations: true
linkcolor: blue

filters:
  - authors-block
  - ../../../../all_phd/_extensions/acronyms/parse-acronyms.lua
  - ../../../../all_phd/_extensions/wordcount/citeproc.lua
  - ../../../../all_phd/_extensions/wordcount/wordcount.lua

acronyms:
  fromfile: ../../../../all_phd/acronyms.yml
  insert_links: false
  insert_loa: false
  sorting: alphabetical

editor_options: 
  chunk_output_type: console

execute:
  echo: false
  warning: false
  error: false
  message: false
---
```

### Your environment

```
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.1                         
year           2023                        
month          06                          
day            16                          
svn rev        84548                       
language       R                           
version.string R version 4.3.1 (2023-06-16)
nickname       Beagle Scouts
```

### Quarto check output

```
Quarto 1.4.358
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.7: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.358
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/lfabbri/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib/R
      LibPaths:
        - /home/lfabbri/Documents/edu/phd/papers/paper3_helixSC_neuro/paper-helixSC-neuro/renv/library/R-4.3/x86_64-pc-linux-gnu
        - /usr/lib/R/library
      knitr: 1.44
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Can you provide a reproducible example ? 
https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines

As of now, we can run your document and so we can't see what could go wrong. It could be something from the content of your document itself. 

There is a lot of things happening in the YAML, including some lua filters, so maybe it could be link too. 

I don't say it does not come from a Quarto change, just that without being able to reproduce, it will be hard to find the change in `.tex` output that would make latex error

**Comment by lnnrtwttkhn** [comment]
hey @lorenzoFabbri, could you share the solution, if you found one?

I'm currently receiving the same error here: <https://github.com/lnnrtwttkhn/fair-teaching-proposal/tree/draft> but only using GitHub Actions (see example here: <https://github.com/lnnrtwttkhn/fair-teaching-proposal/actions/runs/8893520433/job/24419870767>), local rendering works fine.

thanks!

**Comment by lorenzoFabbri** [comment]
> hey @lorenzoFabbri, could you share the solution, if you found one?
> 
> 
> 
> I'm currently receiving the same error here: <https://github.com/lnnrtwttkhn/fair-teaching-proposal/tree/draft> but only using GitHub Actions (see example here: <https://github.com/lnnrtwttkhn/fair-teaching-proposal/actions/runs/8893520433/job/24419870767>), local rendering works fine.
> 
> 
> 
> thanks!

Hello. I sort of gave up on Quarto for the moment... It's too annoying and I'd rather focus on the content of my papers 😅.
Which version are you using?

**Comment by lnnrtwttkhn** [comment]
Thanks for the quick response @lorenzoFabbri. ok, good to know that you didn't pursue this further.

@cderv, my repo (see link above) provides an example, although it's not *minimal*. Also it seems to be a problem that occurs in GitHub Actions for me, local rendering works fine. I'll try to investigate this further, but just flagging this in case you want to consider re-opening the issue. thanks!

**Comment by cderv** [comment]
@lnnrtwttkhn I don't think you have the same issue as @lorenzoFabbri . Error message is different in the latex log - similar but different. 

In your case this is related to bibliography problem. It can be reproduced by the following 

````markdown
---
title: "Table"
format: pdf
bibliography: bibliography.bib
---

::: {#refs}
:::
````

There is a bibliography provided, and a `#refs` block, but no bibliography item in the document. 

Errors also happens with Pandoc directly 
````powershell
❯ quarto pandoc index.qmd --from markdown --to pdf --bibliography=bibliography.bib --citeproc -o test.pdf
Error producing PDF.
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.96 \end{CSLReferences}
````

This is a single doc, but this is what happens in your project too, as you are using
- A website project
- `format: pdf`

Each .qmd will be rendered independently from each other to pdf. 

I don't know what you expect for your `references.qmd` for the pdf output. Not sure why / how it works locally. 

You could either include all your bib for uncited item : https://quarto.org/docs/authoring/footnotes-and-citations.html#including-uncited-items
or maybe you are expecting a book output with all reference from what is used across other formats. But book project is different than website project. 

Please do open a new discussion if you have any follow up question thanks

**Comment by lnnrtwttkhn** [comment]
Thanks @cderv!

> Each .qmd will be rendered independently from each other to pdf.

This was the crucial insight for me here. So as you suggested, adding

```
nocite: |
  @*
```

to the YAML header of `references.qmd` made it work.

**Comment by raffaem** [comment]
@cderv I don't think we should crash if there are no citations, just print an empty reference section.

Can I open an issue about this?

**Comment by cderv** [comment]
Yes please do with a reproducible example. Only thing that we'll need to check :
* Is this Pandoc generating the LaTeX that then fails or is it Quarto ? 

Anyhow, a new issue is always welcome to discuss rather than old one. Thanks !

**Comment by raffaem** [comment]
Reported upstream here: https://github.com/jgm/pandoc/issues/10185

**Comment by raffaem** [comment]
@cderv it got fixed upstream. How does it propagate downstream? Is quarto just calling the system-wide pandoc?

**Comment by cderv** [comment]
Thanks for opening upstream ! Really appreciated ! 

> How does it propagate downstream? Is quarto just calling the system-wide pandoc?

Quarto uses its bundled version. This is because a Quarto version works with a specific Pandoc version, and can't work with a new one necessarilly without some tweaks to adapt to Pandoc potential change and breaking change. 

We did not do the dependency update for Pandoc yet. So it will propagate when Quarto will use the latest pandoc in a future update. And should be for next 1.6 stable release, and a soon to be pre-release in the meantime.

**Comment by mcanouil** [comment]
In addition, Pandoc first needs to make a release. The current fix is only available on the default branch of Pandoc.

**Comment by billspat** [comment]
This is an old issue but I also encountered errors as a Quarto novice when rendering PDF, due to having an entry in the big but not referencing it.    I encountered this when editing a quarto project Rstudio's template, removing the ref but not the corresponding bib entry.     I'm Using quarto 1.6.42 which bundles Pandoc version 3.4.0 ( *I do have Pandoc 3.6 installed via homebrew but I don't know how to tell Quarto to use that one instead of the bundled Pandoc*).   Other tools:  TinyTeX: v2025.03   Chromium: 869685 
I can reproduce the error by starting with the following working files, deleting removing the `@` reference.    This may be avoidable by setting an environment variable, but inside Rstudio and for novices, this error is, as the other issue states, hard to understand.    If there is a pre-flight "check for stupid mistakes" function, that would also be helpful.   

**_quarto.yml**:
```
project:
  type: book

book:
  title: "quarto-missing-ref-error"
  author: "quarto user"
  date: "3/2/2025"
  chapters:
    - index.qmd

bibliography: references.bib

format:
  pdf
```

**index.qmd**

```
# INDEX 

reference @knuth84
deleting the reference above will cause rendering errors

::: {#refs}
:::
```

**references.bib**:

```
@article{knuth84,
  author = {Knuth, Donald E.},
  title = {Literate Programming},
  year = {1984},
  journal = {Comput. J.},
}
```


The above will work and render a PDF using xelatex.   If you remove the reference 
`@knuth84` from index.qmd, it will fail with the following output: 

```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
LaTeX Error: Something's wrong--perhaps a missing \item.

**Comment by mcanouil** [comment]
That's a known Pandoc issue possibly fixed in the next version of Quarto which will have the latest Pandoc.
