### ISSUE TITLE
Spacing issue in callouts without titles in Reveal presentations

### ISSUE THREAD

**Issue by c-zippel** [quarto-dev/quarto-cli#6827]
### Bug description

Hello,

In revealjs presentations, default callouts and simple callouts with icons have excess spacing at the top if there is no title in the callout. 

This may be related to an issue I'd previously filed about callouts in HTML documents, which has been fixed (thank you!).
- https://github.com/quarto-dev/quarto-cli/issues/5955

I filed this as a new issue because #5955 was specifically about HTML format; if that was the wrong call, apologies and I would be happy to copy this into a reply on the original issue.

In simple and default callouts without titles, there is a blank space to the right of the icon and above the callout body text where a title would be. 

![image](https://github.com/quarto-dev/quarto-cli/assets/41382462/0c22fd30-1489-4843-b321-dbdbd24fed53)

In default callouts with neither a title nor icon, there is a shorter, colored empty space above the callout body text.

![image](https://github.com/quarto-dev/quarto-cli/assets/41382462/7045906e-495a-4640-a73d-3022caa8559f)

Other types of callouts look as expected without titles.

I'm using Quarto 1.4.358, the latest available as of this writing.

Thanks very much!

### Steps to reproduce

````qmd
---
title: "Callouts"
format: revealjs
---

## These callouts don't look as expected

::: {.callout-caution appearance="simple"}
A simple callout with no title
:::

::: {.callout-caution appearance="default"}
A default callout with no title
:::

::: {.callout-caution appearance="default" icon="false"}
A default callout with no title or icon
:::

## These callouts look as expected:

::: {.callout-caution appearance="simple" icon="false"}
A simple callout with no title or icon
:::

::: {.callout-caution appearance="minimal"}
A minimal callout with no title
:::

````

### Expected behavior

I expected that callouts without titles would look basically the same in Reveal presentations as they do in HTML documents, with no excess vertical spacing and a default title on default callouts:

![image](https://github.com/quarto-dev/quarto-cli/assets/41382462/782cfa48-6232-42b9-9382-48ffb120bc23)

### Actual behavior

Default callouts and simple callouts with icons have blank spaces above the callout body text where a title would be. 

![image](https://github.com/quarto-dev/quarto-cli/assets/41382462/20a8fe20-9fb7-4b3b-bd1b-0c104e8109c6)

### Your environment

- IDE: RStudio 2023.06.2 Build 561
- OS: Windows 10 Pro

### Quarto check output

```bash
Quarto 1.4.358
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.7: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.358
      Path: C:\Users\czippel\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.04
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\czippel\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/Users/czippel/AppData/Local/Programs/R/R-4.3.1
      LibPaths:
        - C:/Users/czippel/AppData/Local/Programs/R/R-4.3.1/library
      knitr: 1.44
      rmarkdown: 2.24

[>] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
@dragonstyle just happened to look into something related for revealjs so I'll fix this. PR incoming

**Comment by cderv** [comment]
This is now fixed in dev version, and available in next pre-release build 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/c5bbdaca-f77b-4ffb-a381-97056317f682)

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/454c9a0e-2856-4502-ae73-dd97c04ff15f)

**Comment by c-zippel** [comment]
Thank you!!

**Comment by dragonstyle** [comment]
Thanks for fixing this @cderv !
