### ISSUE TITLE
Documentation is missing abstract from MSWord Options

### ISSUE THREAD

**Issue by mlamias** [quarto-dev/quarto-cli#6836]
### Bug description

[This page](https://quarto.org/docs/reference/formats/docx.html) seems to be missing the `abstract:` as a possible yaml header for docx formats.  
 I've verified that abstract works with docx.
 
 https://quarto.org/docs/reference/formats/docx.html

**Comment by mcanouil** [comment]
Thanks for the report, I made a PR to add `abstract` YAML key to  `docx` format.

- https://github.com/quarto-dev/quarto-cli/pull/6840
