### ISSUE TITLE
Issues with Mermaid in Quarto

### ISSUE THREAD

**Issue by bkostadi** [quarto-dev/quarto-cli#6850]
### Bug description

Mermaid flowcharts not working properly in Quarto. 

### Steps to reproduce

An example mermaid code from the [Mermaid Live Editor](https://mermaid.live/edit#pako:eNpVkE2LwjAQhv_KMNdt6HotKqxGrcqe1pOJh2DjWrCT0iZQKf3vO21pYW-Th_cjvC3eXWYxwd_KlE-4SE1fqvam8jch1hsV51QGD01807QBRrBVQJCs4JPJdiCybWDNADpNkgm5nu5agiWIhuGO4dvWTI9q8BJ8wIL9x9E_KkbbXsUu-L5TUF-6Z3jgH7mSH3LKSVvOWC2h6TvTOR5O__PTOfY8x5JY9Lmnqfo8HAeMsLBVYfKMx2g1AWj0T1tYjQmfmX2Y8PIaNXUsNcG7nzfdMfFVsBGGMjPeytzwjMUEbZZ7V32P-w4zR1gaujrHkod51bb7A0ZWc_o) is given below:

```{mermaid}
graph TD
A[start]-->B[/input x/]
B --> C[ n := 0]
C --> D{x >= 0 }
D --no--> E{n < -x}
E --yes-->I[n := n + 1]
I --> D
E --no--> F[/output -n/]
F-->G[stop]
D--yes-->H{ n =< x }
H --yes--> J[n := n + 1]
H --no--> K[/output n-1/]
J --> D
K --> G
```

### Expected behavior

The mermaid code should produce a flowchart without any issues in the nodes `E{n < -x}` and `H{ n =< x }`. 

### Actual behavior

There are issues in the nodes `E{n < -x}` and `H{ n =< x }`. 

It works fine in the Mermaid Editor, but **it does not work in a Quarto notebook**. More specifically, the lines:

- `D --no--> E{n < -x}`  and
- `D--yes-->H{ n =< x }` 

create a problem and it appears to be related to the `<` symbol. The problem is still there even if I make the expressions strings and put them inside double quotes. 

### Your environment

- Version 2023.06.2+561 (2023.06.2+561)
- MacOS Monterey V. 12.6.8
- RStudio Version 2023.06.2+561 (2023.06.2+561)

### Quarto check output

```{bash}
quarto check
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/local/bin/python3
      Jupyter: 4.11.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Note that mermaid version between the mermaid live editor and within Quarto are not the same.
In 1.4, mermaid version is `10.2.0-rc.2`
In 1.3, mermaid version is `9.2.2`
While on the mermaid live editor, the version is `10.4.0`

Could you try Quarto pre-release version which at least is using the same major version?

**Comment by bkostadi** [comment]
Thanks for the suggestion! I installed the Quarto pre-release version 1.4.366 and the Mermaid issue got fixed. I hope Quarto 1.4 will be released soon since I am using the mermaid diagrams in class and I don't have the option to install the pre-release version of Quarto there.

**Comment by mcanouil** [comment]
I can't give you a date, but "soon".
I am going to close this as it is simply a version issue.

If you can't use the pre-release, I suggest you write your mermaid diagram using the version embedded in Quarto 1.3.
