### ISSUE TITLE
The `.callout-note` Block Rejects the `.fragment` Class

### ISSUE THREAD

**Issue by RoyiAvital** [quarto-dev/quarto-cli#6853]
### Bug description

It seems one cannot have both the `callout-note` and the `fragment` class for the same `div` element.

### Steps to reproduce

```qmd
---
format:
  revealjs:
    theme: default
---

## Slide 1

:::{.fragment}
Some text
:::

:::{.callout-note .fragment}
 - Some note...
:::
```

### Expected behavior

- The text to appear on click.
- The callout block to appear on click next.

### Actual behavior

- The text to appear on click (Works).
- The callout block to appear on click next (Doesn't work).

### Your environment

- IDE: Visual Studio `1.82.2`.
- Quarto CLI `1.3.450`.
- OS: Windows.

### Quarto check output

```cmd
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: D:\Applications\Programming\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by RoyiAvital** [comment]
In the `HTML` output one can see the `fragment` class is missing from the `div` element of the callout.

**Comment by mcanouil** [comment]
Callouts (and `fragment) are not exactly/entirely CSS classes, they are constructs in Quarto.

````qmd
---
format: revealjs
---

## Slide 1

::: {.fragment}
Some text
:::

:::: {.fragment}
::: {.callout-note}
 - Some note...
:::
::::
````

**Comment by cscheid** [comment]
> Callouts are not exactly/entirely CSS classes, they are constructs in Quarto.

That's the true source of the trouble here; that .callout-note is indicating a custom AST node, while (understandably) one could imagine it's "just a class in a div". This is an admittedly confusing part of how we structure things.

What should probably happen here is that, in html, callouts should forward the other declared classes to the div we end up producing.
 >

**Comment by mcanouil** [comment]
> What should probably happen here is that, in html, callouts should forward the other declared classes to the div we end up producing.

More generally, attributes should be passed on in HTML-based formats.

**Comment by cscheid** [comment]
> More generally, attributes should be passed on in HTML-based formats.

That doesn't work everywhere: custom AST nodes are not required to render into enclosing divs or spans. (I don't know if they should, but this isn't a promise we want to make)

**Comment by mcanouil** [comment]
I see, so better to show a warning when "foreign" elements are passed with call-outs (tabsets also?)

**Comment by cscheid** [comment]
> I see, so better to show a warning when "foreign" elements are passed with call-outs (tabsets also?)

Something like that, yes. I think the constructors of each of the custom AST elements should always check for extra attributes and classes, include them in divs when possible, and show a warning when not possible. That's an improvement we need to make.

**Comment by RoyiAvital** [comment]
@cscheid , I guess once you solve this, it will also solve https://github.com/quarto-dev/quarto-cli/issues/5208.
I hope I'm right here (Not a JavaScript / HTML specialist at all).
