### ISSUE TITLE
Dead link on website docs

### ISSUE THREAD

**Issue by axiomtutor** [quarto-dev/quarto-cli#6862]
### Bug description

Just a little heads up, at this page: 

https://quarto.org/docs/interactive/ojs/libraries.html

there is a link to this page:

https://www.jsdelivr.com/features#npm 

in the section on NPM.  It weirdly redirects to a 404.

**Comment by mcanouil** [comment]
Thanks for the report.

See:
- https://github.com/quarto-dev/quarto-web/pull/830
