### ISSUE TITLE
output of R's gt table-creating package will not render to docx but does render to html and pdf

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-cli#687]
The output of R's `gt` table-creating package will not render to docx but does render to html and pdf (with certain imperfections discussed in #685).

A workaround for now may be to save the output to a file with `gtsave`, and include it as an image.

---------------------------- minimal reproducible example --------------------------------------------------------

# Create data

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(gt)

df <- tibble(rank=1:10, money=seq(100, 1000, 100))

```

# This renders successfully as html, almost successfully as pdf, and only partially as docx

-   as html everything looks correct

-   as pdf, the line break does not occur

-   as docx, the echoed code is shown but the table does not appear to be in the docx file

```{r}

df %>% 
  gt() %>% 
  cols_label(rank=html("Rank"), money=md("Amount<br>$"))

```

**Comment by jjallaire** [comment]
@rich-iannone Does any of your recent work on quarto & gt improve things here?

**Comment by rich-iannone** [comment]
@jjallaire Issue has been moved to https://github.com/rstudio/gt/issues/928 and it will be tracked there so it's okay to close this one.

**Comment by donboyd5** [comment]
Thanks!
