### ISSUE TITLE
Wrong echo default for beamer format

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#6886]
### Bug description

With beamer output, `echo` defaults to `false` contrary to other formats (and contrary to the documentation):

### Steps to reproduce

Render the following with Beamer output:

````qmd
```{python}
2+2
```
````

### Expected behavior

The codeline should be shown.

### Actual behavior

The codeline is not shown unless `echo: true` is set.

### Your environment

- OS: Pop!_OS 22.04

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3, julia-1.8, octave, sos, julia-1.9, atk, sagemath

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /home/j/R/x86_64-pc-linux-gnu-library/4.1
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.40
      rmarkdown: 2.17

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
This is not a bug, the same things also happen for PowerPoint and Revealjs presentations.
That is by design.
To enable `echo: true` set it in your YAML frontmatter, see <https://quarto.org/docs/computations/execution-options.html>:

```yml
execute:
  echo: true
```

>  contrary to the documentation

Where exactly do you thing there is an issue in the documentation?

**Comment by knuesel** [comment]
The documentation at https://quarto.org/docs/reference/formats/presentations/beamer.html states that `true` is the default.

Are you sure it's not a bug in all the presentation formats? It seems odd to have this behave differently for presentations, and I can't find anything about that in the documentation.

**Comment by cscheid** [comment]
@knuesel Thanks for pinpointing the source! It's a documentation bug. We ask folks to be precise so we understand where to fix.

> It seems odd to have this behave differently for presentations, and I can't find anything about that in the documentation.

We do set this on purpose for presentations because there's significantly less space available, and we find that folks tend to prefer to have the result show up more prominently.

With that said, we should 100% fix the documentation problem you're seeing.

**Comment by cscheid** [comment]
For our own consideration: this is happening because our schemas are not capable of showing different documentation entries for different formats when the schema is reused.

I'm not sure how we can fix this cleanly in our YAML intelligence setup, but I think we should think about it seriously.

**Comment by knuesel** [comment]
Thanks for the explanation and quick fix!

**Comment by cderv** [comment]
Just for reference, we usually document change in default or specificity to formats in their own guide. 
See https://quarto.org/docs/presentations/beamer.html#overview

> By default, the Beamer format has `echo: false` and `warning: false`. As a result, executable code cells in standard Beamer documents won’t show their source or warnings generated. As with other options, you can override this behavior in the document metadata or individually in each executable cell.

Not ideal, so thanks for the report ! Hopefully #6889 will help us maintain better documentation between guide and reference.
