### ISSUE TITLE
stray whitespace

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#689]
We're generating some stray whitespace after the merging of the `cell-language-handler` branch. See [this](https://github.com/quarto-dev/quarto-web/commit/a80db52e7b9bb07f441f4d663edc3a3b38322783).

**Comment by dragonstyle** [comment]
I think this is a change I introduced when I changed the way we're injecting reveal-js plugin scripts (at least that is the one I can see). I'm testing a fix right now...

**Comment by dragonstyle** [comment]
OK fixed the reveal script tag white space here:

https://github.com/quarto-dev/quarto-cli/commit/4ddbb4df5bfa622449cdc52c5d9a6999a496bc43

**Comment by cscheid** [comment]
I had another bug myself 😭 fixed here: e87a9e7a59dc519f16fc6129df1c51f19239fd11
