### ISSUE TITLE
Lightbox fails with computational cells in self-contained HTML docs

### ISSUE THREAD

**Issue by jack-davison** [quarto-dev/quarto-cli#6892]
### Bug description

Using the v1.4 pre-release, the lightbox feature fails when the HTML is self-contained. It works perfectly when not self-contained, but when resources are embedded nothing pops up:

![image](https://github.com/quarto-dev/quarto-cli/assets/45171616/55355fae-65ab-4355-9da4-a503bf2ea1e8)

And you get this message in the render screen: 

```
Watching files for changes
  /testqmd_files/figure-html/fig-mypic-1.png (404: Not Found)
```

### Steps to reproduce

````qmd
---
title: "lightbox test"
format: 
  html:
    embed-resources: true
editor: visual
lightbox: auto
---

## Lightboxes (click the pics!)

See @fig-mypic

```{r}
#| label: fig-mypic
#| fig-cap: "A delightful plot."
plot(iris)
```
````

### Expected behavior

I would expect that, on clicking on the plot, a lightbox should show containing a big version of it.

### Actual behavior

Instead, a circle spins infinitely with the background shaded out, as pictured above. The RStudio render pane complains about failing to find the PNG file.

### Your environment

- IDE RStudio 2023.03.0 Build 386
- Windows 10

### Quarto check output

```
$ quarto check
Quarto 1.4.371
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.371
      Path: C:\Users\jd38\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\jd38\AppData\Roaming\TinyTeX\bin\win32\
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.3
      Path: C:/Users/jd38/AppData/Local/Programs/R/R-4.2.3
      LibPaths:
        - C:/Users/jd38/AppData/Local/R/win-library/4.2
        - C:/Users/jd38/AppData/Local/Programs/R/R-4.2.3/library
      knitr: 1.44
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report!

Could you edit your post to make your example usable?

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by jack-davison** [comment]
@mcanouil - sure thing, just edited it now.

**Comment by cderv** [comment]
Just for reference with initial issue on this front: 
* https://github.com/quarto-ext/lightbox/issues/1

**Comment by wilcar** [comment]
I have the same issue. Do you think it is possible to fix it in a next release ?

**Comment by mcanouil** [comment]
See the milestone attached/scheduled.
![image](https://github.com/quarto-dev/quarto-cli/assets/8896044/bd03691f-64db-4d8f-8af5-63d8844af274)
