### ISSUE TITLE
[FR] Display Quarto version used to build projects

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#69]
Hi- 

Request from Workbench team to be able to plop the version of Quarto used to build the Admin Guide somewhere visible: https://github.com/rstudio/rstudio-pro/issues/2815

Something like the footer in pkgdown?
<img width="1413" alt="Screen Shot 2021-07-29 at 3 37 35 PM" src="https://user-images.githubusercontent.com/12160301/127574405-56c7f074-f629-4820-aa31-c26167ec6996.png">

**Comment by jjallaire** [comment]
We don't have this feature yet. In the meantime we've added a `generator` meta-tag with the quarto version here https://github.com/quarto-dev/quarto-cli/commit/3e80c78d6fece0a8ff4152c5afaa41f2321955c2. 

```html
<meta name="generator" content="quarto-0.2.42">
```

You need to do View Source to see this but at least it's recorded as part of the page/site. Will that do the trick for now?

**Comment by apreshill** [comment]
This does indeed work, thanks!
