### ISSUE TITLE
Installing 1.3 deb file over 1.4 gives corrupted installation

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#6901]
### Bug description

Downgrading from 1.4.373 to 1.3.450 using the deb files gives a corrupted installation.

### Steps to reproduce

Start with an empty system, for example with Docker:

```
docker run -it ubuntu:22.04
```

Then in the container:

```
apt update; apt install -y wget
wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb
wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.373/quarto-1.4.373-linux-amd64.deb
dpkg -i quarto-1.4.373-linux-amd64.deb
dpkg -i quarto-1.3.450-linux-amd64.deb
touch a.qmd
quarto render a.qmd
```

### Expected behavior

It should generate a (blank) html file.

### Actual behavior

It complains that pandoc is not found:

```
pandoc 
  to: html
  output-file: a.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  
ERROR: Error executing '/opt/quarto/bin/tools/pandoc': No such file or directory (os error 2)

Error: Error executing '/opt/quarto/bin/tools/pandoc': No such file or directory (os error 2)
    at execProcess (file:///opt/quarto/bin/quarto.js:5630:15)
    at runPandoc (file:///opt/quarto/bin/quarto.js:80367:27)
    at async renderPandoc (file:///opt/quarto/bin/quarto.js:81044:26)
    at async Object.onRender (file:///opt/quarto/bin/quarto.js:86673:36)
    at async renderFiles (file:///opt/quarto/bin/quarto.js:86636:25)
    at async render (file:///opt/quarto/bin/quarto.js:90681:21)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:90856:32)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:127545:5)
    at async file:///opt/quarto/bin/quarto.js:127563:9
```

and indeed:

```
root@8feca44b3651:/# find /opt/quarto/bin/tools/ 
/opt/quarto/bin/tools/
/opt/quarto/bin/tools/deno-x86_64-unknown-linux-gnu
/opt/quarto/bin/tools/deno-x86_64-unknown-linux-gnu/deno
/opt/quarto/bin/tools/deno_dom
/opt/quarto/bin/tools/deno_dom/libplugin.so
/opt/quarto/bin/tools/esbuild
/opt/quarto/bin/tools/dart-sass
/opt/quarto/bin/tools/dart-sass/src
/opt/quarto/bin/tools/dart-sass/src/LICENSE
/opt/quarto/bin/tools/dart-sass/sass
```

**Comment by mcanouil** [comment]
You should first uninstall previous version then install new version as with merely every software.
Could you try to uninstall before installing over?

I don't believe this to be a bug but a misuse of system installer.

**Comment by knuesel** [comment]
Actually I was wrong: downgrading without uninstalling is not officially supported by Debian packages (at least according to https://wiki.debian.org/Glossary)

It's still unusual I think that this doesn't work (I don't recall stumbling on this problem before in ~20 years of using Debian-based systems, though I don't downgrade packages particularly often :) )

**Comment by mcanouil** [comment]
I find it odd to not uninstall before doing a downgrade.
A lot of software have warnings/notes that users should uninstall/remove first when installing a new version (installing a new version does not necessarily means updating).

**Comment by knuesel** [comment]
I guess that depends on your operating system... You mentioned how users are supposed to uninstall a software before installing a new version but that's definitely not the case on Debian (though it's true that the downgrade case without uninstalling, while usually working, is not officially supported).

I edited the title to clarify that this concerns the deb files. Note that the deb file installer (dpkg) does execute the pre and post install scripts from the previous package to handle the version transition. I think the problem is that the new `postrm` script (in 1.4) has added the following line:

```
rm -f /opt/quarto/bin/tools/pandoc
```

Maybe this should be in a `prerm` script instead. (Actually maybe the whole `postrm` content would be better placed in `prerm`?)

**Comment by dragonstyle** [comment]
I think this last comment is correct- it is caused by the symlink we're creating and we need to be cleaning that up (and `prerm` is a good approach).
