### ISSUE TITLE
PDF: Figure caption footnote LaTeX compilation error

### ISSUE THREAD

**Issue by stefanbringuier** [quarto-dev/quarto-cli#6907]
### Bug description

When rendering a document to PDF that contains a footnote in a figure caption and the specification in the `format: -> pdf: -> fig-pos: "H"` , the LaTeX engine will fail to compile. This is most likely due to the fact that LaTeX requires the footnote text to be on the same page as the float object ( see https://tex.stackexchange.com/questions/281420/error-in-footnote-inside-figure-caption). Removal of the the specification `fig-pos: "H"` provides expected behavior however does not allow for control of figure placement. 

The solution should be to ensure the footnote text (i.e., `\footnotetext`) is not within the `\begin{figure} ... \end{figure}` environment, but also still allow for float object placement specification.

### Steps to reproduce

````qmd
---
title: "Footnote in Fig. Caption PDF issue."

format:
    pdf:
        pdf-engine: xelatex
        documentclass: scrartcl
        fig-pos: "H"
        output: true
        toc: true
        lof: true
        colorlinks: true
        code-line-numbers: true
---


## A Figure

![The caption of a figure with a footnote ^[This is a figure caption footnote containing a link <https://quarto.org/quarto-dark-bg.jpeg>]](https://quarto.org/quarto-dark-bg.jpeg)

````

### Expected behavior

```latex
....

\begin{figure}

{\centering \includegraphics{FigureFootnoteCaption_files/mediabag/quarto-dark-bg.jpg}

}

\caption[The caption of a figure with a footnote ]{The caption of a figure with a footnote \footnotemark{}}

\end{figure}
\footnotetext{This is a
  figure caption footnote containing a link
  \url{https://quarto.org/quarto-dark-bg.jpeg}}

...

```

### Actual behavior

```latex
....

\begin{figure}[H]

{\centering \includegraphics{FigureFootnoteCaption_files/mediabag/quarto-dark-bg.jpg}

}

\caption{The caption of a figure with a footnote \footnote{This is a
  figure caption footnote containing a link
  \url{https://quarto.org/quarto-dark-bg.jpeg}}}

\end{figure}

...
```

```log
compilation failed- error
Argument of \caption@ydblarg has an extra }.
<inserted text> 
                \par 
l.176 ...https://quarto.org/quarto-dark-bg.jpeg}}}

```

### Your environment

- IDE: VSCode 1.81.1
- OS: Ubuntu 22.04 
- Quarto: 1.3.450

### Quarto check output

```bash
[?] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[?] Checking versions of quarto dependencies......OK
[?] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[?] Checking basic markdown render....OK

[?] Checking Python 3 installation....OK
      Version: 3.10.12 (Conda)
      Path: ~/.julia/conda/3/x86_64/bin/python3.10
      Jupyter: 5.3.1
      Kernels: julia-1.9, python3

[?] Checking Jupyter engine render....OK

[?] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment]
> The solution should be to ensure the footnote text (i.e., \footnotetext) is not within the \begin{figure} ... \end{figure} environment, but also still allow for float object placement specification.

Captions need to be inside the figure environment, so what you're asking for is unfortunately not possible in LaTeX (we would not be able to place the footnotes accurately.)

**Comment by stefanbringuier** [comment]
> > The solution should be to ensure the footnote text (i.e., \footnotetext) is not within the \begin{figure} ... \end{figure} environment, but also still allow for float object placement specification.
> 
> Captions need to be inside the figure environment, so what you're asking for is unfortunately not possible in LaTeX (we would not be able to place the footnotes accurately.)

There might be a misunderstanding, It is not the caption per se its the footnote inside the caption.

If you look at the **Expected Behavior** section, the `\footnotetext` is not in the `\begin{figure} ... \end{figure}` environment;  and this is what is produces if one removes `fig-pos: "H"` from the `format: -> pdf:` section!

The problem is that when the float object placement is specified, Quarto seems to want to place the `\footnote` inside the caption, but it should just do what the default is without specifying `fig-pos`

**Comment by cscheid** [comment]
> It is not the caption per se its the footnote inside the caption.

I'm not sure what we can do if you put the footnote inside the caption:

`![The caption of a figure with a footnote ^[This is a figure caption footnote containing a link <https://quarto.org/quarto-dark-bg.jpeg>]](https://quarto.org/quarto-dark-bg.jpeg)`

The output you're suggesting is not valid output:

```
\caption[The caption of a figure with a footnote ]{The caption of a figure with a footnote \footnotemark{}}

\end{figure}
\footnotetext{This is a
  figure caption footnote containing a link
  \url{https://quarto.org/quarto-dark-bg.jpeg}}
```

The footnote marker won't be accurate in this case (consider that more than one footnote is possible in a document). The solution is very case-dependent, and so in your case you should simply insert the raw latex blocks necessary.

Quarto needs to be general across formats, as well as general for use-cases within formats. Pulling a single footnote is unfortunately not robust enough for us, but you can do that in your document, and we encourage users to use the escape hatches like raw latex blocks in those cases!

**Comment by stefanbringuier** [comment]
I see. Thank you very much for giving your thoughts and suggestions.

**Comment by cscheid** [comment]
I followed up with the other devs, and we already do some of this processing for some cases (including managing counters for footnotes etc). Somehow this is failing in your situation.
