### ISSUE TITLE
No TOC or github links unless more than one header in page

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#691]
Quarto version 0.9.271 installed on Ubuntu from .deb release package

When I create and preview a new book project, the rendered index.qmd page has a table of contents on the right.  None of the other pages has a table of contents.

If I add a second header to e.g. the intro.qmd page, the page is re-rendered with a table of contents.

Maybe you made the design decision to omit a table of contents if there is only one header.  But a consequence of that is that if I try to include Github links via the "repo-url:" etc.  options in _quarto.yml, the Github links are missing along with the toc in the rendered pages.

Behavior is similar for a new website project, but in that case there is no TOC or links on the rendered index.qmd page either.

I want to make sure there are Github links on every page of my book.  If you don't want to create a full table of contents on pages with only one header, can you make it so that at least the Github links will appear?

**Comment by dragonstyle** [comment]
Agree this isn't great that without a toc, no GH tools will appear! I'll take a look at this and see how we can improve it...

**Comment by dragonstyle** [comment]
This shoudl be fixed here: 9a09753bc91f3d4c3506fadb959a2608e98cbd86.

Release coming soon

**Comment by eitsupi** [comment]
Maybe 9a09753bc91f3d4c3506fadb959a2608e98cbd86 cause #1066

**Comment by dragonstyle** [comment]
We're going to leave this one open for a bit while we stabilize the release- we'll come back to this one soon.

**Comment by huntley-link** [comment]
Workaround:

I really wanted this feature, so I installed Quarto v v0.9.515 (apparently the last version with the fix to this issue).  In the pages I didn't want the Github links to show, I pasted the following into the page's .qmd file:

```
<style>
#quarto-margin-sidebar {visibility: hidden;}
#quarto-document-content {grid-column:page-start/page-end !important;}
div.column-page-left {grid-column:page-start/page-end !important;}
</style>
```

This makes the sidebar invisible and fixes the layout so the page looks like it would if the Github link feature were not specified at all.

In a page where I want to keep the table of contents but hide the Github links, I add the following to the page's .qmd file:

```
<style>
div.toc-actions {visibility: hidden;}
</style>
```

Maybe you could start integrating this fix by keeping the status quo as the default, but adding an option to turn the fix on, for those of us willing to hack our way to a solution, but still get the benefits of the latest releases' features and fixes.

**Comment by blacksqr** [comment]
Workaround:

I really wanted this feature, so I installed Quarto v v0.9.515 (apparently the last version with the fix to this issue).  In the pages I didn't want the Github links to show, I pasted the following into the page's .qmd file:

```
<style>
#quarto-margin-sidebar {visibility: hidden;}
#quarto-document-content {grid-column:page-start/page-end !important;}
div.column-page-left {grid-column:page-start/page-end !important;}
</style>
```

This makes the sidebar invisible and fixes the layout so the page looks like it would if the Github link feature were not specified at all.

In a page where I want to keep the table of contents but hide the Github links, I add the following to the page's .qmd file:

```
<style>
div.toc-actions {visibility: hidden;}
</style>
```

Maybe you could start integrating this fix by keeping the status quo as the default, but adding an option to turn the fix on, for those of us willing to hack our way to a solution, but still get the benefits of the latest releases' features and fixes.

**Comment by seeM** [comment]
@dragonstyle any chance of revisiting this issue soon? I just encountered it too

**Comment by dragonstyle** [comment]
Can you say a little more specifically what you're seeing? This issues mentions a few things about the TOC behavior and a lot has changed since v0.9, so I want to be sure I'm considering what you'd like to see changed!

**Comment by seeM** [comment]
Ah! My specific issue is that the Github links only show if both the toc is
enabled and the page has headings, which I found surprising/unexpected

**Comment by dragonstyle** [comment]
Are you seeing this for websites or books? I'm thinking websites and what 1.3 _should_ be doing is 'finding' a place to put the GitHub links (attempting to use the TOC, but actually placing the links in the page footer if not TOC is present to use).

![Screenshot 2023-04-21 at 8 40 29 AM](https://user-images.githubusercontent.com/261654/233638497-bef3f5b5-d9e2-4b48-a4f2-e4b9469be2f8.png)


We found that in pages with no natural TOC, having the Github links just floating alone felt a bit weird...

**Comment by blacksqr** [comment]
This appears to me to be fixed as of closing of #2142 . I'm in the process of rebuilding my web site going from v 0.9.515 to v 1.3.282.  I'm using both website and book project types.  I suggest @seeM check to ensure they have an up-to-date version of Quarto.

**Comment by seeM** [comment]
Ahhh yes it is for a website and it is on the bottom of the page, thanks! It’s a bit unexpected but I can definitely see how it might look odd floating on the right 🤔

**Comment by dragonstyle** [comment]
One other option - you can force it on if you set repo-actions like:

```markdown
---
repo-actions: true
---

This is a document with no header or TOC
```

which will make it appear where the TOC goes, if that is preferable for you!

**Comment by dragonstyle** [comment]
(I'm closing because I think this is good, but please re-open if there is more to be done!)

**Comment by seeM** [comment]
Oh neat, I think that’s what I’m looking for. Thanks again!
