### ISSUE TITLE
code-summary is ignored in YAML

### ISSUE THREAD

**Issue by daranzolin** [quarto-dev/quarto-cli#6910]
### Bug description

Whatever value I specify for `code-summary` is ignored in the YAML. `code-summary` works, however, on an individual chunk basis.

### Steps to reproduce

Here is my Quarto document. 'Show the code' is ignored for the first chunk.

````qmd
---
title: "My Document"
format:
  html:
    code-fold: true
    code-summary: "Show the code"
---

```{r}
#| echo: true
head(mtcars)
```

```{r}
#| echo: true
#| code-summary: "This works"
head(mtcars)
```
````

### Expected behavior

'Show the code' should appear above the first chunk. 

### Actual behavior

The default 'Code' appears.

### Your environment

IDE: RStudio 2023.06.2
Windows 11

### Quarto check output

````bash
A new release of Deno is available: 1.28.2 → 1.36.4 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Users\dranzolin\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/dranzolin/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      knitr: 1.43
      rmarkdown: 2.16

[>] Checking Knitr engine render......OK
````

**Comment by mcanouil** [comment]
To note, this is the same behaviour for `Jupyter` as it is for `knitr`.
Global value from the front matter YAML is not sent to all code cells.

**Comment by cderv** [comment]
This is definitely a regression as we have documented it in https://quarto.org/docs/output-formats/html-code.html#folding-code

It is working with 1.2.475 but no working with latest 1.3.450. So looking for the commit that breaks it, it seems this is the language processing 37afc8e6d88207d69eab19204a56c1d02f58ec2b introduced in 1.3

That should help fix it

**Comment by cderv** [comment]
Or maybe we should just update our doc, as new way to set `code-summary` is to use the `language` key as explained by @mcanouil (https://github.com/quarto-dev/quarto-cli/issues/6910#issuecomment-1726400515) 

@dragonstyle what is your take ? Documentation issue ?

**Comment by mcanouil** [comment]
Since the key is localised, I would move `code-summary` from the references pages to computations pages.

I wonder if there should be some kind of interactive table of what keys are localised or not.
It could be generated directly from the localised files and show which languages are supported.
Currently, user has to go to the source code to know.

**Comment by dragonstyle** [comment]
I think the intent here was to support this as a feature (not really via the `language` key). That fix to improve language handling was correct, but I think here we should actually forward this value to the language key when set, so it will be respected.

**Comment by cderv** [comment]
> That fix to improve language handling was correct, but I think here we should actually forward this value to the language key when set, so it will be respected.

Ok I was hesitating about this. But I do believe though that `code-summary` as a feature under `html` is worth keeping.
