### ISSUE TITLE
1.4.376 Manuscript not recognized anymore

### ISSUE THREAD

**Issue by xtimbeau** [quarto-dev/quarto-cli#6927]
### Bug description

Using 1.4.376 manuscript are no longer compiling. website is compiling
1.4.358 compiles manuscript and website
best,

### Steps to reproduce

`_quarto.yml`

````_quarto.yml
project:
  type: manuscript
manuscript:
  article: doc.qmd
format: html
````

`doc.qmd`

````doc.qmd
---
title: "doc"
---
text
````

### Your environment

RStudio 2023.09.0 Build 432
quarto 1.4.376
win 11

**Comment by dragonstyle** [comment]
I wasn't able to reproduce this using Quarto 1.4.376 (on MacOS). Is there an error message that you are receiving or is there more you can say about what is failing?

**Comment by xtimbeau** [comment]
Hi, apparently after restarting windows, manuscript works fine.
I should have done the 1.4.376 install without restarting and that is triggering the error, which is not a bug.
Thanks !
