### ISSUE TITLE
VSCode browser preview updates to wrong URL after reload when ToC is enabled

### ISSUE THREAD

**Issue by chhoumann** [quarto-dev/quarto-cli#6933]
### Bug description

After enabling `toc` in my metadata configuration, like so:

```markdown
---
title: "XGBoost: A Scalable Tree Boosting System"
subtitle: "@XGBoost"
author: "Christian Bager Bach Houmann"
date: 2023-09-22
date-format: "D MMM YYYY"
slide-number: true
bibliography: static/references.bib
format: 
    revealjs:
        theme: default
        toc: true
---
```

I find that the VSCode browser view updates to the wrong presentation slide when reloading.

Similar to https://github.com/quarto-dev/quarto-cli/issues/6409.

### Steps to reproduce

This is automatically run when I click the `Render` button in VSCode.
```bash
source /home/christian/projects/xgboost_presentation/env/bin/activate
quarto preview /home/christian/projects/xgboost_presentation/presentation.qmd --no-browser --no-watch-inputs
```

I have reload on save turned on.

Whenever I write to & save a `.qmd` file, it reloads. However, it loads to the wrong slide.

### Expected behavior

I expect it to redirect the browser to the correct URL.

See this GIF for a demonstration:
![Code_tbMDqyE1ih](https://github.com/quarto-dev/quarto-cli/assets/29108628/3df8f14d-f282-4acd-b232-eb3cabd71e3c)

### Actual behavior

It redirects me to the slide prior to the one I edited.

### Your environment

Using Visual Studio Code through WSL on a Windows 11 machine. Using a Python virtual environment as well.

I have tested with both [v1.4.376](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.376) and `quarto-1.3.450-linux-amd64.deb`

### Quarto check output

```bash
❯ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: /home/christian/anaconda3/bin/python
      Jupyter: 5.3.1
      Kernels: python3, mojo-jupyter-kernel

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
Thanks for the report.

Note that VSCode related issue are better to be posted on <https://github.com/quarto-dev/quarto>.

Here I am not completely sure, it's only in VSCode.
Would you be able to try in RStudio IDE?

**Comment by jjallaire** [comment]
This should be fixed here: https://github.com/quarto-dev/quarto/commit/78d6dfbadeb5c862fdd622c7b38d86929233d834

Note this isn't yet in a released version but will be within a week or two.

**Comment by chhoumann** [comment]
Thank you!
