### ISSUE TITLE
Callout rendering in `gfm`

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#6935]
This should be a matter of adding a custom renderer for the Callout node in `gfm` output.

**Comment by cscheid** [comment]
See https://github.com/quarto-dev/quarto-cli/discussions/1495

**Comment by cderv** [comment]
Just a note that this is still in Beta : [github.com/orgs/community/discussions/16925](https://github.com/orgs/community/discussions/16925)

> Let us know what you think and how this helps you provide better documentation. Please note that this is a beta feature that might be subject to change.

With a few updates since May 2022. 

I can't find any other mention in Github doc, spec or blog post.

**Comment by cscheid** [comment]
Good to know. With that said, it's really very easy for us to do, so it wouldn't be hard to change our rendering if they change their syntax.
