### ISSUE TITLE
Line return between table number and table caption

### ISSUE THREAD

**Issue by aghaynes** [quarto-dev/quarto-cli#6951]
### Bug description

A colleague has mentioned a strange case where there is a line break between table numbers and captions. This doesnt seem to happen with figures, nor does it happen on my machine. 

This is how the document renders for my colleague:

![grafik](https://github.com/quarto-dev/quarto-cli/assets/6594028/c41e7aa4-502c-4282-9b4c-81a5836dac5d)

And here is my version:

![grafik](https://github.com/quarto-dev/quarto-cli/assets/6594028/ee324861-936b-4209-b719-86a61432b538)

(I suspect the difference in font is something to do with the document being sent over teams, so can be ignored)

I have version 1.2.269 and he has 1.3.450, both installed via RStudio. 

### Steps to reproduce

```` qmd
---
title: "Untitled"
format: html
---

```{r}
#| tbl-cap: "foobar"
#| label: tbl-foobar

gt::gt(mtcars |> head())
```
```` 

### Expected behavior

The table caption should be on the same line as the table number

### Actual behavior

The table caption is placed on the line after the table number

### Your environment

Colleague:

- IDE: RStudio 2023.06.02
- OS: Windows 11

### Quarto check output

Colleagues machine:

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.44
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
> (I suspect the difference in font is something to do with the document being sent over teams, so can be ignored)

I suspect it's the other way around: both differences come from the same cause. By sending the document over teams, you're currently not sending any of the document styling, which is required in order for the appearance to be correct. For documents to be attached in messages, etc, you need them to render with

````html
format:
  html:
    embed-resources: true
````

I'm pretty sure this will solve your problem.

**Comment by aghaynes** [comment]
He showed me live on his machine as well and it also had the line break between the table number and table caption, so it's not to do with sending it over teams...

**Comment by cscheid** [comment]
Have you tested the `embed-resources: true` method I mentioned? I cannot reproduce your issue as reported.

For example, if your colleague is not using `quarto preview`, then it's very possible that his method of looking at the file will also be missing the styling elements and will cause precisely the same issue.

For reasons like this, it's useful that you describe to us _precisely_ how you're experiencing the bug. Specifically, "showed me live on his machine" is not enough for use to track down how it happened.

**Comment by aghaynes** [comment]
This is a part of the raw HTML of the file:

![grafik](https://github.com/quarto-dev/quarto-cli/assets/6594028/6bf2dd6b-4146-4a5b-b702-580036510c31)

@lbueti, i think you will need to be involved here... can you try embedding the resources to see if that helps?

**Comment by aghaynes** [comment]
OK, i just upgraded my version of quarto to 1.3.450 (the latest version from the quarto website) and I now have the issue too. I am using R 4.2.1 still, @lbueti was using 4.3.2 (i believe), so its not down to the R issue. 

Embedding the resources does not help, here viewed in RStudio:
![grafik](https://github.com/quarto-dev/quarto-cli/assets/6594028/ed1ed4c2-9beb-414d-9985-8516118659cb)

and the same HTML file in Firefox:
![grafik](https://github.com/quarto-dev/quarto-cli/assets/6594028/ce9cd059-087c-4850-ae30-2f16fb6eb956)

And the same paragraph tags around the tbl-cap: 
![grafik](https://github.com/quarto-dev/quarto-cli/assets/6594028/916fe549-c90b-41a0-ac8c-29127b82057b)

**Comment by cscheid** [comment]
> I have version 1.2.269 and he has 1.3.450, both installed via RStudio.

Ok, this is helpful. The issue here is that I suspect you're running a very recent `gt` version, for which you will want quarto's 1.4 prereleases. This is the rendering I get:

<img width="679" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/fbdfb7bd-ad51-4bbb-ba4c-eaf20ebae038">

**Comment by aghaynes** [comment]
He got a new laptop today, so he probably is indeed using the newest version of gt... I have gt 0.9.0 (which is also the version currently on CRAN).

Is the release version of 1.4 in the near future? 

We could always roll back to 1.2, or use an older version of gt in the meantime I suppose... or not use `tbl-cap`s for now

**Comment by cscheid** [comment]
> Is the release version of 1.4 in the near future?

We expect it in Fall 2023. With that said, the 1.4 prereleases are what we ourselves use in daily work, and we try very hard to not break things (we build http://quarto.org itself with the latest 1.4 prereleases binary as a matter of practice-what-you-preach!)

**Comment by aghaynes** [comment]
I just updated to 1.4.376 and can confirm that the caption position is indeed as i would expect. Thanks again @cscheid :)

**Comment by aghaynes** [comment]
@cscheid we have noticed that there is a large (25px) margin after the caption, which looks very strange (it's also visible in your screenshot above). 

Using this CSS works to remove it, but it's odd that it's there at all...
```
caption, .table-caption, .quarto-float-caption {
	margin-bottom: 0px;
}
```

Would this be something for a new issue?

**Comment by cscheid** [comment]
Yes, please. Our CSS does need some tweaking because of the new DOM we're using. We just haven't gotten around to it yet.

**Comment by obrl-soil** [comment]
I don't know if this helps, but I just tried switching from publishing via /docs/ to using the GitHub Actions workflow described [here](https://quarto.org/docs/publishing/github-pages.html#publish-action), and it triggered the same behaviour in gt table captions (it also completely broke captions on gt's new interactive tables). Rolling back to using /docs/ fixed the problem. Affected repo is https://github.com/obrl-soil/wrbsoil2022.

Setup is:
OS: Win 11
Quarto: 1.4.533
R: 4.3.2
RStudio: 2023.12.0 Build 369
gt: 0.10.0

**Comment by cderv** [comment]
> I just tried switching from publishing via /docs/ to using the GitHub Actions workflow described [here](https://quarto.org/docs/publishing/github-pages.html#publish-action),

Did you check you were using the exact same Quarto version. Via docs you are rendering locally before publishing through git, and when using actions, the rendering happens inside Github Action. You need to recreate your local environment there to have the same results. If you are using latest version of tools it should be ok. 

Note: By default, the quarto action to setup quarto is using the latest stable release not 1.4 version where this issue is fixed (see the milestone)

**Comment by obrl-soil** [comment]
Ah, that explains it 🤦🏻‍♀️I'm ahead locally.
