### ISSUE TITLE
number-sections nor working for Beamer presentation

### ISSUE THREAD

**Issue by luifrancgom** [quarto-dev/quarto-cli#6956]
I am building a presentation in quarto where I am using version 1.4.274. I have installed a LaTeX distribution based on TeX Live `tinytex::install_tinytex()` where I am using version 0.45.

My document with the YAML is as follows:

```
---
title: "Title"
format: 
  beamer:
    pdf-engine: xelatex
    number-sections: true
    number-depth: 3
editor: visual
---

## Section

This is the content of the section

### Subsection

This is the content of the subsection
```

However the sections are not numbered where I am getting the following result:

![slide_1](https://github.com/quarto-dev/quarto/assets/50002526/527bf1b3-e2f2-41ba-8cfd-f4ae4c8b473f)
![slide_2](https://github.com/quarto-dev/quarto/assets/50002526/91597d89-a1a2-4ee9-a7e5-43d48de4d311)

This is not the case for example when you create the document using Revealjs or PowerPoint:

```
---
title: "Title"
format: 
  revealjs:
    number-sections: true
    number-depth: 3
editor: visual
---

## Section

This is the content of the section

### Subsection

This is the content of the subsection
```

![slide_3](https://github.com/quarto-dev/quarto/assets/50002526/7e7352e0-0f46-4236-bd39-581c4aed19a2)
![slide_4](https://github.com/quarto-dev/quarto/assets/50002526/11e5d019-49bb-40c5-90f8-6a43278ecafb)

```

---
title: "Title"
format: 
  pptx:
    number-sections: true
editor: visual
---

## Section

This is the content of the section

### Subsection

This is the content of the subsection
```
![slide_5](https://github.com/quarto-dev/quarto/assets/50002526/a1d73122-4f1a-4126-85ca-66157f51860f)
![slide_6](https://github.com/quarto-dev/quarto/assets/50002526/7050c3c2-9bc6-40dd-85f7-a1bb09054984)

I already posted the issue in stackoverflow, [here](https://stackoverflow.com/questions/76807033/quarto-beamer-presentation-number-sections/76807168#76807168), but I didn't get a satisfactory answer.

**Comment by cderv** [comment]
It seems to be an issue with Pandoc. When `--number-sections` is passed, it will trigger this line in template
https://github.com/quarto-dev/quarto-cli/blob/ac01707b939303ae01d08a408aefba8edd2aac65/src/resources/formats/pdf/pandoc/latex.template#L312-L316

This is for LaTeX and also beamer. 

However, it seems `\setcounter{secnumdepth}{3}` has no effect in Beamer. I tried calling
````
quarto pandoc -t beamer -o test.pdf -s --number-sections index.qmd
````

I don't really know if / how beamer is supposed to work for session. However I know that in Quarto we emulate Number Sections. 
So doing this change 
```diff
diff --git a/src/resources/filters/crossref/sections.lua b/src/resources/filters/crossref/sections.lua
index 12266c57c..ce4853658 100644
--- a/src/resources/filters/crossref/sections.lua
+++ b/src/resources/filters/crossref/sections.lua
@@ -97,7 +97,7 @@ function currentSectionLevel()
 end

 function numberSections()
-  return not _quarto.format.isLatexOutput() and
+  return (not _quarto.format.isLatexOutput() or _quarto.format.isBeamerOutput()) and 
          not _quarto.format.isTypstOutput() and
          not _quarto.format.isMarkdownOutput()
          and numberSectionsOptionEnabled()
```

would apply Quarto processing I guess. 

@dragonstyle @cscheid : Any of you know how to number section in beamer ?

**Comment by cscheid** [comment]
I don't.

**Comment by cderv** [comment]
I opened 
* https://github.com/jgm/pandoc/issues/9099

I wonder if we should just defer to our processing as this is not working in pandoc 🤔
