### ISSUE TITLE
Unable to embed plot from source qmd to destination qmd like in tutorial

### ISSUE THREAD

**Issue by coltongearhart** [quarto-dev/quarto-cli#6959]
### Bug description

Using the minimal working example below, a plot should show up in the index.html, but it does not. And the reference is unable to be resolved.
<img width="482" alt="Screenshot 2023-09-22 at 11 13 33 PM" src="https://github.com/quarto-dev/quarto-cli/assets/49720025/513ac15a-c084-462b-bb39-67815b00e382">
<img width="482" alt="Screenshot 2023-09-22 at 11 13 40 PM" src="https://github.com/quarto-dev/quarto-cli/assets/49720025/7cec5056-a060-46ba-b31f-2a1868bbe775">
<img width="482" alt="Screenshot 2023-09-22 at 11 14 01 PM" src="https://github.com/quarto-dev/quarto-cli/assets/49720025/1451c4bd-8429-4860-86f2-0067b09717d8">

### Steps to reproduce

Using the template found / tutorial found here and making a minimal example: [Manuscripts](https://quarto.org/docs/manuscripts/authoring/rstudio.html)

Destination file:
````
---
title: Test
author: Colton Gearhart
---
## Introduction
{{< embed notebooks/test.qmd#fig-norm >}}

@fig-norm is shown.
````

Source file located at notebooks/test.qmd:
````
---
title: test
---
```{r}
#| label: fig-norm
plot(rnorm(10))
```
````

### Expected behavior

This plot should be rendered in the article.
![Rplot](https://github.com/quarto-dev/quarto-cli/assets/49720025/61263a3e-c4ab-4701-bb18-1e61f5e9e799)

### Actual behavior

<img width="909" alt="Screenshot 2023-09-22 at 11 16 15 PM" src="https://github.com/quarto-dev/quarto-cli/assets/49720025/f9922c07-1d95-4ecc-9871-e62a1aa39150">

And reference doesn't work
<img width="482" alt="Screenshot 2023-09-22 at 11 14 01 PM" src="https://github.com/quarto-dev/quarto-cli/assets/49720025/1451c4bd-8429-4860-86f2-0067b09717d8">

### Your environment

RStudio: Version 2023.06.2+561 (2023.06.2+561)
MacOS: 13.5.2 (22G91)

### Quarto check output

Quarto 1.4.376
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.376
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2018

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/local/Cellar/r/4.3.1/lib/R
      LibPaths:
        - /usr/local/lib/R/4.3/site-library
        - /usr/local/Cellar/r/4.3.1/lib/R/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by dragonstyle** [comment]
This is a bug caused by omitting a `fig-cap` for the figure - we are in the midst of some big changes in behavior regarding figures with and without captions, so this is something that we'll look at more closely. In the meantime, you can add a caption to resolve the issue:

````markdown
---
title: test
---

```{r}
#| label: fig-norm
#| fig-cap: This is the figure's caption
plot(rnorm(10))
```
````

**Comment by cderv** [comment]
@dragonstyle shouldn't we keep that open to track resolution despite the workaround ?

**Comment by coltongearhart** [comment]
Apologies, I closed it. Still new to github :)
