### ISSUE TITLE
[Feature Request] Special code blocks for comments

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#696]
It would be useful to have something like [knitr's comment code block](https://github.com/yihui/knitr/releases/tag/v1.37) to leave comments that are not included in the output.

input

````qmd
---
title: test
format: commonmark
engine: knitr
---

<!-- comment (to be output) -->

```{comment}
not to be output
```
````

output

````md
<!-- comment (to be output) -->
````

(I noticed that the output file has no title.  I reported this bug in another issue. #697)

**Comment by jjallaire** [comment]
There are a couple of options here:

- Comments with a triple dash (`<!--- comment --->`) should be stripped from the output
- The `ignore-comments` option will strip all comments from the output

**Comment by eitsupi** [comment]
Thanks for your quick reply.

> Comments with a triple dash () should be stripped from the output

I did not know this. This sounds nice!
I hope it is highlighted somewhere in the reference.

I close this issue as I think this way will fulfill our needs.

**Comment by cderv** [comment]
You could also use this lua filter to add some block part in your document that would be ignored in the output.

````lua
Div = function(div)
  if (div.classes:includes("comment")) then
    return {}
  end
end
````

This will allow you to write content such as 
````markdown
::: comment
Any content written as markdown that would be ignored in any output type
:::
````

Basically, this is a generalization of the `comment` engine in **knitr**. Compare to **knitr** special engine, you get nicer writing experience which markdown highlighting for your block. 
Main use case I encountered for this is when writing some template and you want to give advice to users without adding the output when the source template is rendered. 

To add some filters with Quarto you can look at https://quarto.org/docs/authoring/shortcodes-and-filters.html#pandoc-filters

@jjallaire would this be worth it adding such small filter as a default feature in Quarto for non-knitr user ?

**Comment by jjallaire** [comment]
@cderv Yes I think it would! Let's hold off though to make sure it aligns with whatever syntax/idiom we use for format-specific divs/blocks. 

cc @cscheid

**Comment by eitsupi** [comment]
> ```gfm
> ::: comment
> Any content written as markdown that would be ignored in any output type
> :::
> ```

Perhaps this could be considered in a future release?

**Comment by cooknl** [comment]
The only mention of this kind of commenting in the docs is
https://quarto.org/docs/visual-editor/content.html#commenting
When reviewing a document you often want to provide inline comments with suggested revisions. This is possible in Quarto using HTML comments (which are ignored by all output formats). Visual mode includes a command for inserting HTML comments as well as special highlighting treatment to easily parse out editing comments from surrounding text.

![image](https://user-images.githubusercontent.com/5116899/184277799-69c6f90e-a668-4cf2-8663-2ccffd97bd3a.png)

This implies a double dash, the standard HTML comment, per https://www.w3schools.com/html/html_comments.asp

This works fine.

**Comment by cscheid** [comment]
Open PR: https://github.com/quarto-dev/quarto-cli/pull/1906

**Comment by eitsupi** [comment]
#1906 did not seem to be merged.
I am wondering if you decided to favor HTML comment syntax instead of implementing comment blocks?

**Comment by cderv** [comment]
I believe you can use conditional content block for this purpose (https://quarto.org/docs/authoring/conditional.html#content-hidden) 

````markdown
---
title: test
format: commonmark
---

<!-- comment (to be output) -->

::: {.content-hidden}
not to be output
:::

````

**Comment by eitsupi** [comment]
Thank you for pointing that out! I had not checked the documentation recently.
It looks so great!

**Comment by wangzk** [comment]
I suggest adding the commenting mechanisms to the official tutorial. The commenting mechanism is essential for review in document collaboration through git repo. The commenting mechanism helps two or more persons collaborate based on Quarto document.
