### ISSUE TITLE
Matplotlib image has extremely small height on margin in html

### ISSUE THREAD

**Issue by finkelshtein** [quarto-dev/quarto-cli#6961]
### Bug description

Hi,
It may be related to #6865 which closed the issue I raised in #6863.
#6865 fixed the issue for PDF, however, now the image is not visible in HTML (it has a very small height).

### Steps to reproduce

````qmd

---
title: "matplotlib demo"
format:
  html: 
      self-contained: true
      grid: 
          margin-width: 350px
  pdf: default
jupyter: python3
---

Demo

```{python}
#| echo: false
#| column: margin

import matplotlib.pyplot as plt

plot = plt.figure()
plot.set_figwidth(2)
plot.set_figheight(3)

x = [1, 2]
y = [2, 3]

plt.plot(x,y)

```

````

### Actual behavior

![issue](https://github.com/quarto-dev/quarto-cli/assets/35048241/f9ca8701-95ed-49d3-ab68-e3d4aac00bad)

### Your environment

- Quarto 1.4.376
- IDE: VS Code 1.82.2
- Windows 10

**Comment by finkelshtein** [comment]
Just to add, the bug is also reproducible on the Gallery example 
https://github.com/quarto-dev/quarto-gallery/blob/main/page-layout/tufte.qmd
It seems that, in that example, "Full width" feature does not work either.

**Comment by cscheid** [comment]
Thanks for the report. I can repro this. It's a regression from a recent big change, and our tests aren't covering it properly. I'll fix right away.
