### ISSUE TITLE
Fatal error in PanelLayout renderer

### ISSUE THREAD

**Issue by ptram** [quarto-dev/quarto-cli#6965]
### Bug description

While trying to render an .md file from the Terminal (Mac Monterey v12.7, Quarto v1.4.376) I got the following error:

```
FATAL (/Applications/quarto/share/filters/main.lua:17615) An error occurred:
PanelLayout renderer requires a float in typst output
This is a quarto bug. Please consider filing a bug report at https://github.com/quarto-dev/quarto-cli/issues
Error running filter /Applications/quarto/share/filters/main.lua:
/Applications/quarto/share/filters/main.lua:2009: attempt to call a nil value (global 'crash_with_stack_trace')
stack traceback:
	/Applications/quarto/share/filters/main.lua:1590: in function 'fail'
	/Applications/quarto/share/filters/main.lua:1582: in function 'fail_and_ask_for_bug_report'
	/Applications/quarto/share/filters/main.lua:17615: in field 'render'
	/Applications/quarto/share/filters/main.lua:670: in local 'filter_fn'
	/Applications/quarto/share/filters/main.lua:226: in function </Applications/quarto/share/filters/main.lua:216>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	/Applications/quarto/share/filters/main.lua:148: in function </Applications/quarto/share/filters/main.lua:138>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:725: in local 'callback'
	/Applications/quarto/share/filters/main.lua:738: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:773: in function </Applications/quarto/share/filters/main.lua:770>
stack traceback:
	/Applications/quarto/share/filters/main.lua:148: in function </Applications/quarto/share/filters/main.lua:138>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:725: in local 'callback'
	/Applications/quarto/share/filters/main.lua:738: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:773: in function </Applications/quarto/share/filters/main.lua:770>
```

The PDF file didn't render.

### Steps to reproduce

The file is very long and complex, and I can't even share the content without scrambling it. Is there some usual suspects that I could isolate?

### Expected behavior

The PDF to be rendered (maybe with a list of errors).

### Actual behavior

The PDF file didn't render.

### Your environment

Just the Mac Terminal.

### Quarto check output

```
Quarto 1.4.376
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.376
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in .installbuilder. Did you forget to activate it?

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

```

As for the unactivated Python environment, I guess this is the Mac installing version 2.x, and someone else (Quarto?) installing version 3.x.

**Comment by cscheid** [comment]
> The file is very long and complex, and I can't even share the content without scrambling it. Is there some usual suspects that I could isolate?

It's something that we interpret as a complex layout, likely a div with layout information like "margin" or "layout-ncol" or something like that. And it's happening because the contents of the div are not crossreferenceable.

You're seeing the bug because we haven't implemented that behavior yet. It is 100% a bug we need to fix, but we need to know what you typed in order to see what's breaking.

**Comment by ptram** [comment]
I removed the `{layout}` and `<div>` marks, and it indeed compiled. An example of a possibly offending code is this one:

```
:::: {layout="[15,85]"}

::: {custom-style="Image"}
![](images/exclamation-mark.pdf){width=80 fig-alt="Image of an exclamation mark"}
:::

<div>
::: {custom-style="Safety Body"}
**WARNING** -- Do not ingest battery, chemical burn hazard. This product contains a coin/button cell battery.
:::

::::

```

**Comment by ptram** [comment]
> It doesn't look like the `<div>` tag is doing anything there, though.

In a Website, without the <div> statement inside the fenced layout, I get the image side by side with the first paragraph (of the ones I enclosed in the <div> block). The following paragraphs are moved to the wrong column.

I should probably avoid making separate paragraphs, but end them with a <br> tag.

**Comment by cscheid** [comment]
> In a Website, without the `<div>` statement inside the fenced layout, I get the image side by side with the first paragraph (of the ones I enclosed in the `<div>` block). The following paragraphs are moved to the wrong column.

You should still use the following syntax instead:

```
::: {}
Content
:::
```

That's equivalent to `<div>Content</div>` and is safer in the presence of other markdown content.
