### ISSUE TITLE
`ìnclude` shortcode overrides title with that from last included document

### ISSUE THREAD

**Issue by sda030** [quarto-dev/quarto-cli#6966]
### Bug description

The following behaviour applies to both single document rendering and website project.
When including (shortcode) in a parent document one or more child documents that already contain `title: ` in the YAML-header, the rendered document gets the title of the last included child document. Before you rebut that multiple titles are not intended usage - it actually makes sense in website and book projects to have child documents that should work independently, and yet have a rendered (index.qmd) all-in-one document of all the chapters/child documents. Would at least be nice to have Quarto disregard the titles of the included documents.

### Steps to reproduce

index.qmd:
````qmd
---
title: "Parent"
---

{{< include child1.qmd >}}

{{< include child2.qmd >}}

````

child1.qmd:
````qmd
---
title: "Child1"
---
# Heading in child1
text
````

child2.qmd:
````qmd
---
title: "Child2"
---
# Heading in child2
text
````

#### Heading from child1
text

#### Heading from child2
text

#### Heading from child1
text

#### Heading from child2
text

### Your environment

- IDE: RStudio 2023.06.1. Build 524
- Windows 11

### Quarto check output

```bash
Quarto 1.4.376
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.376
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\py128\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Users/py128/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/py128/AppData/Local/R/win-library
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.44
      rmarkdown: 2.24

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
This isn't a bug; as we mention in the documentation, include statements work precisely like copying and pasting. If your last document has title metadata, then metadata merging will use that value. This is intended behavior.
