### ISSUE TITLE
Rendered markdown file has no title when qmd include executable code block

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#697]
When rendering the following three different qmd files, only the first example has a title.

````qmd
---
title: test
format: commonmark
---

```r
1 + 1
```
````

````qmd
---
title: test
format: commonmark
---

```{r}
1 + 1
```
````

````qmd
---
title: test
format: commonmark
---

```{python}
1 + 1
```
````

**Comment by jjallaire** [comment]
Thanks for reporting this! Should be fixed here https://github.com/quarto-dev/quarto-cli/commit/f2f5bb47606eb79f444ee39ef3ed67e0e3695dd9 (build available shortly)

**Comment by dragonstyle** [comment]
I added a simple set of tests using the above example- thanks for finding this!
