### ISSUE TITLE
figure directory not created

### ISSUE THREAD

**Issue by rkb965** [quarto-dev/quarto-cli#6981]
### Bug description

Thank you for the wonderful software! I think this is a quarto bug — but I am not entirely sure. It may be a misunderstanding on my part or perhaps a {knitr} bug, but I could not recreate this solely within .Rmd.

When rendering `myfile.qmd` with knitr and saving figures via `fig.path: my-figs`, if a folder exists called `myfile_files` (that is populated with some relevant files — I cannot recreate this if `myfiles_files` is an empty directory), then `my-figs` is not created.

Unnecessary background: I am not entirely sure how I ended up with `myfile_files` (I do not use keep_md), but I ran into this issue of a missing directory when I was trying to move to quarto and created `myfile.qmd` in a directory that already had `myfile.Rmd`. 

### Steps to reproduce

First, create the directory `myfile_files` via rendering the below file `myfile.qmd`:

````
---
title: "trying to save figures"
format: html
self-contained: true
---

```{r pressure}
plot(pressure)
```
````

Next, modify the file `myfile.qmd`:

````
---
title: "trying to save figures"
format: html
embed-resources: true
knitr:
  opts_chunk:
    fig.path: "my-figs/"
---

```{r pressure}
plot(pressure)
```
````

and render this file.

### Expected behavior

I would expect rendering the second time would create a directory `my-figs`, populated with `pressure.png`

### Actual behavior

`my-figs` is not created

### Your environment

RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-07) for CentOS 7
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.353
      Path: /usr/lib/rstudio-server/bin/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /spack/2206/apps/linux-centos7-x86_64_v3/gcc-11.3.0/r-4.2.2-hj45qaa/rlib/R
      LibPaths:
        - /home1/rb_913/R/x86_64-pc-linux-gnu-library/4.2
        - /spack/2206/apps/linux-centos7-x86_64_v3/gcc-11.3.0/r-4.2.2-hj45qaa/rlib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

**Comment by cderv** [comment]
I can't reproduce with **knitr** 1.44 and Quarto 1.4

> knitr: 1.42

Can you try with latest **knitr** ? We are at 1.44 now and we fixed some issues recently. 

> [✓] Checking Quarto installation......OK
> Version: 1.3.353

Also, it could be something related to matching Quarto 1.4 and recent **knitr**. Can you try with Quarto 1.4  pre-release ? 
You can install from https://quarto.org/docs/download/prerelease.html

Note that you are also running with `embed-resources: true` (or `self-contained: true`. This could have effect on the intermediate directory as all resources should be embed and you won't see folder at the end. 

Anyhow, please do try updated versions
