### ISSUE TITLE
getYamlIntelligenceResource called with missing resource pandoc/formats.yml

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#699]
This error happens in https://github.com/mwouts/jupytext/issues/949

````
E           jupytext.quarto.QuartoError: quarto convert --log-level warning /tmp/tmplcv1q4a2.qmd exited with return code 1
E           ERROR: Internal Error: getYamlIntelligenceResource called with missing resource pandoc/formats.yml
````

See discussion there. It seems it was working fine in `0.9.243` but now fail with `0.9.282` and `0.9.285`

We don't have yet more precise information but I am opening here anyway to discuss. 

I understand `pandoc/formats.yml` is a key for which value should be computed internally 
https://github.com/quarto-dev/quarto-cli/blob/af5c051e8251d3a0535f2e8dcf62d011259c8fb2/src/core/schema/yaml-schema.ts#L31-L32

@cscheid was there any change that could break something ?

Thanks 

cc @mwouts

**Comment by cscheid** [comment]
I fixed the issue.
This was introduced a good while back, and I believe our test suite wasn't catching it because the missing initialization was being done by a separate test. Thank you for the report!

**Comment by cderv** [comment]
Awesome! Thanks @cscheid !
