### ISSUE TITLE
license not rendered as expected from documentation

### ISSUE THREAD

**Issue by jonassmedegaard** [quarto-dev/quarto-cli#6992]
### Bug description

[Documentation](https://quarto.org/docs/authoring/front-matter.html#license) says I can declare license either as text + type + url, or a CC license shortname (which I then assume will expand to *descriptive* text + url.

But for html the former ignores url, and the latter simply uses the rather non-descriptive shortname as text.
And for PDF the whole license is ignored.

### Steps to reproduce

Test1:
````qmd
---
license: "CC BY-SA"

lang: da

format:
  html:
    toc: true
  pdf:
    toc: true
---
````

Test2:
````qmd
---
license:
  text: >
    Dette værk er licenseret
    under en Creative Commons Kreditering-Deling på samme vilkår 4.0 International-licens.
  type: open-access
  url: https://creativecommons.org/licenses/by-sa/4.0/deed.da

lang: da

format:
  html:
    toc: true
  pdf:
    toc: true
---
````

### Expected behavior

For both tests, a section `Genbrug` with text `Dette værk er licenseret under en Creative Commons Kreditering-Deling på samme vilkår 4.0 International-licens.` linking to `https://creativecommons.org/licenses/by-sa/4.0/deed.da`.

### Actual behavior

For test1, html text is `CC BY-SA 4.0`, and PDF lacks section `Genbrug` altogether.

For test2, html text is plain without a link, and PDF lacks section `Genbrug` altogether.

### Your environment

- IDE: none
- OS: Debian linux

### Quarto check output

```bash
$ quarto check
Quarto 1.4.366
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.366
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      Chromium: 869685
      TinyTeX: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

```

**Comment by dragonstyle** [comment]
Thanks for reporting this- I've marked this an enhancement as I think the HTML suggestions make sense and are improvements to our current output which we should make.

I'm not as sure about the PDF changes as we most often take a minimal approach to our PDF output and rely on custom templates and template-partials to provide specific / advanced formatting for things such as this.

**Comment by mcanouil** [comment]
`license` is not part of Pandoc PDF/LaTeX template thus is not used, see <https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/pdf/pandoc/template.tex>

Regarding the full specification of license, there is indeed an issue :

```
license:
  text: >
    Dette værk er licenseret
    under en Creative Commons Kreditering-Deling på samme vilkår 4.0 International-licens.
  type: open-access
  url: https://creativecommons.org/licenses/by-sa/4.0/deed.da
```

**Comment by dragonstyle** [comment]
I've fixed the issue where we wouldn't properly include the `url` in our HTML output. The rest of the described behavior is currently by design (e.g. we don't include license in our PDF output, you may provide a `template` or `template-partials` to render this, we render CC license shorthand)
