### ISSUE TITLE
Quarto fails to render figure layout with subcaptions

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#6993]
### Bug description

(This might be related to #6912.)

When using subcaptions with the layout option for custom figure layouts, Quarto gives an error.

```
Error running filter /Applications/quarto/share/filters/main.lua:
/Applications/quarto/share/filters/main.lua:16847: attempt to index a nil value (field 'content')
```

### Steps to reproduce

This works (no image-specific captions):

````qmd
---
title: Layout test
---

```{r}
#| label: fig-charts
#| fig-cap: "Charts"
#| layout: "[1, 1]"

plot(cars)
plot(pressure)
```
````

This works (image-specific captions): 

````qmd
---
title: Layout test
---

```{r}
#| label: fig-charts
#| fig-cap: 
#|   - "Speed and Stopping Distances of Cars"
#|   - "Vapor Pressure of Mercury as a Function of Temperature"
#| layout: "[1, 1]"

plot(cars)
plot(pressure)
```
````

This doesn't work (image-specific subcaptions):

````qmd
---
title: Layout test
---

```{r}
#| label: fig-charts
#| fig-cap: "Charts"
#| fig-subcap: 
#|   - "Cars"
#|   - "Pressure"
#| layout: "[1, 1]"

plot(cars)
plot(pressure)
```
````

```
Error running filter /Applications/quarto/share/filters/main.lua:
/Applications/quarto/share/filters/main.lua:16847: attempt to index a nil value (field 'content')
stack traceback:
	/Applications/quarto/share/filters/main.lua:17242: in function 'float_reftarget_render_html_figure'
	/Applications/quarto/share/filters/main.lua:13546: in field 'render'
	/Applications/quarto/share/filters/main.lua:670: in local 'filter_fn'
	/Applications/quarto/share/filters/main.lua:226: in function </Applications/quarto/share/filters/main.lua:216>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	/Applications/quarto/share/filters/main.lua:148: in function </Applications/quarto/share/filters/main.lua:138>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:725: in local 'callback'
	/Applications/quarto/share/filters/main.lua:738: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:773: in function </Applications/quarto/share/filters/main.lua:770>
stack traceback:
	/Applications/quarto/share/filters/main.lua:148: in function </Applications/quarto/share/filters/main.lua:138>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:725: in local 'callback'
	/Applications/quarto/share/filters/main.lua:738: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:773: in function </Applications/quarto/share/filters/main.lua:770>
```

### Expected behavior

There should be subcaptions with images.

### Actual behavior

Nothing renders :)

### Your environment

- IDE: RStudio 2023.06.2+561
- OS: macOS Ventura 13.5.2

### Quarto check output

```
Quarto 1.4.382
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.382
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/andrew/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Thank you! We'll fix ASAP.

**Comment by cscheid** [comment]
Another immediate workaround, if you're looking for one, is to not use `layout: [1, 1]`. (It's clearly a bug on our side, but this will stop Quarto from crashing for the next few hours...)

**Comment by andrewheiss** [comment]
Oh that's just for the sake of the reprex—IRL it's a more complex multipanel layout like `[[70,30], [100]]`, but I've just turned off the captions for now, so it's all good :)

**Comment by andrewheiss** [comment]
Oh, and idk if it's related to this issue or if I should open a new one, but `layout-valign` seems to be emitting a `quarto-layout-valign-top` class regardless of whether the option is top, center or bottom

**Comment by cscheid** [comment]
> Oh, and idk if it's related to this issue or if I should open a new one, but layout-valign seems to be emitting a quarto-layout-valign-top class regardless of whether the option is top, center or bottom

Probably a new one. (I ripped out all of the old crossref to support #4944 and we're going through a bit of regression churn. I apologize!!)

**Comment by radovan-miletic** [comment]
Hi @cscheid,

I'm not sure if this is the case for opening new issue...
I'm getting the same error with option `eval: false`:

````
---
title: Layout test
---

```{r}
#| label: fig-charts
#| fig-cap: "Charts"
#| fig-subcap: 
#|   - "Cars"
#|   - "Pressure"
#| layout: "[1, 1]"
#| eval: false

plot(cars)
plot(pressure)
```
````  

Thank you!

**Comment by cscheid** [comment]
Ok, we do need to fix that error, but I'm not sure what output you're expecting to get if the code cell itself has `echo: false`

**Comment by radovan-miletic** [comment]
Thanks @cscheid !
I'm using the option `eval: false` when I need to switch between chunks without evaluating one of them.
In my understanding, with `eval: false` we can tell Quarto not to run the code and generate output for one particular code chunk.

**Comment by mcanouil** [comment]
@radovan-miletic Have you considered using project profiles and conditional contents?
- https://quarto.org/docs/projects/profiles.html
- https://quarto.org/docs/authoring/conditional.html

**Comment by radovan-miletic** [comment]
Thanks @mcanouil , it's certainly worth exploring!

**Comment by cscheid** [comment]
> I'm using the option eval: false when I need to switch between chunks without evaluating one of them.

Ok. But what I meant is that your code cell has labels, captions, and layout options, but with `eval: false`, we have no content with which to build a figure.

**Comment by radovan-miletic** [comment]
I should have been more explicit. 
Up to the `v.1.4.366`, `eval: false` had the ability to instruct Quarto not to run the code / generate output for one particular chunk, even with labels, captions, and layout options.
After that version, `eval: false` still can tell Quarto not to run the code, with the exception of `tbl-cap`, as far I can see.
I just noticed that behavior after your last comment. 
It could be another issue, if not intentional.

**Comment by cderv** [comment]
@cscheid @radovan-miletic I opened a new issue at #7118 to continue discussion there in its proper thread. It seems there are some changes to discuss.
