### ISSUE TITLE
jupyterlab-quarto installed but not working, seems extension expecting jupyterlab 4 0 greater?

### ISSUE THREAD

**Issue by lgonzalezsa** [quarto-dev/quarto-cli#6994]
### Bug description

I am running JupyterLab v3.4.8, the extension is installed but not OK

jupyterlab-quarto v0.2.8 enabled  X (python, jupyterlab-quarto)

Listing the extensions and see this compatibility notice, this means the extension needs jupyterlab 4 or greater?
Any chances to make it work on 3.5.x?

"jupyterlab-quarto@0.2.8" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.4.8 <3.5.0          >=4.0.0 <5.0.0 @jupyterlab/application
>=3.4.8 <3.5.0          >=4.0.0 <5.0.0 @jupyterlab/codemirror

### Steps to reproduce

Using JupyterLab v3.4.8
install with python3 -m pip install jupyterlab-quarto

### Expected behavior

The extension to run

### Actual behavior

Jupyter Lab does not finish to load

### Your environment

opensuse 15.5
python 3.8.13

**Comment by mcanouil** [comment]
This is an issue to be reported in <https://github.com/quarto-dev/jupyterlab-quarto> I believe.

CC @dragonstyle

**Comment by dragonstyle** [comment]
We do have a JL3 version available. More here:

https://quarto.org/docs/tools/jupyter-lab-extension.html#installing-the-extension

HTH!

**Comment by lgonzalezsa** [comment]
ops! I missed the tabs! my bad, testing version 3, thank you!

**Comment by lgonzalezsa** [comment]
A minir typo in the documentation:
https://quarto.org/docs/tools/jupyter-lab-extension.html#installing-the-extension:~:text=python3%20%2Dm%20pip%20install%20jupyterlab%2Dquarto%3D%3D0.1.4.5

![image](https://github.com/quarto-dev/quarto-cli/assets/704686/92deb8d8-8b83-4bc2-a107-4c87c08af14e)


```bash
# python3 -m pip install jupyterlab-quarto==0.1.4.5
ERROR: Could not find a version that satisfies the requirement jupyterlab-quarto==0.1.4.5 (from versions: 0.1.40, 0.1.41, 0.1.42, 0.1.43, 0.1.45, 0.2.3, 0.2.4, 0.2.5, 0.2.7, 0.2.8)
ERROR: No matching distribution found for jupyterlab-quarto==0.1.4.5
```

**Comment by mcanouil** [comment]
What does work? This `python3 -m pip install jupyterlab-quarto==0.1.45`?

**Comment by lgonzalezsa** [comment]
yeap! that works
```bash
python3 -m pip install jupyterlab-quarto==0.1.45
Collecting jupyterlab-quarto==0.1.45
  Downloading jupyterlab_quarto-0.1.45-py3-none-any.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 387.5 kB/s eta 0:00:00
Installing collected packages: jupyterlab-quarto
Successfully installed jupyterlab-quarto-0.1.45
```

**Comment by mcanouil** [comment]
Thanks fixing the typo.

**Comment by mcanouil** [comment]
FYI, PR:
- https://github.com/quarto-dev/quarto-web/pull/837
