### ISSUE TITLE
Embed shortcode not working

### ISSUE THREAD

**Issue by apsteinmetz** [quarto-dev/quarto-cli#6996]
### Bug description

I'm just cloning the manuscript template from github. When rendering the Earthquakes template the embedded chunk shows up as a link to the source markdown file "explore earthquakes.qmd" but the figure cross reference doesn't appear.  It appears in the document as "?@fig-spatial-plot shows the location of recent Earthquakes on La Palma."

The "source"  link, "http://localhost:6596/notebooks/explore-earthquakes-preview.html#cell-fig-spatial-plot" link does take me to the render of the "explore earthquakes.qmd" but the "back to article" link takes me to "not found."

As an aside, I would like to turn off the source link visibility index.qmd. Is there a flag for that?

### Steps to reproduce

I am running the cloned template from Github.

### Actual behavior

see above

### Your environment

2023.06.2 Build 561
Windows 11

### Quarto check output

```bash
Quarto 1.4.383
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.383
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Apste\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: C:/Program Files/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

      There is an unactivated Python environment in miniconda3. Did you forget to activate it?

[>] Checking R installation...........OK
      Version: 4.3.0
      Path: C:/PROGRA~1/R/R-43~1.0
      LibPaths:
        - C:/Users/Apste/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.0/library
      knitr: 1.44
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
I think we've _just_ fixed something related. @dragonstyle is this the embed issue we were observing as well?

**Comment by dragonstyle** [comment]
This definitely could be related - I'll take a closer look.

As far as controlling the source notebook links, see this documentation which lays out the options:

https://quarto.org/docs/authoring/notebook-embed.html#linked-source-notebooks

**Comment by dragonstyle** [comment]
I do think we'll have a fix for this shortly (sometime tomorrow AM EST) - it is an issue we've been digging into.

**Comment by dragonstyle** [comment]
A build which resolves this and updated template repos should now be available. Thank you for catching this and letting us know!
