### ISSUE TITLE
[FR] Quarto SASS variable to control padding of all non-navbar content

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#70]
This may already exist, so please let me know if there is an easier way. Workbench team wanted more whitespace above the main content, and I wanted all the elements to stay aligned- this proved harder than I thought! It would be great if Quarto used a variable to control that top padding, which users could also grab onto and change. As is, this was a lot of trial and error, eyeballing things, and holding rulers up to my screen. Here was my outcome:

<img width="1413" alt="Screen Shot 2021-07-29 at 3 54 43 PM" src="https://user-images.githubusercontent.com/12160301/127575822-fb5340aa-f210-4d82-a314-cf29174303e8.png">

And my CSS:
```
/* increase padding above ALL content */
.sidebar {
  padding-top: 50px;
}
.sidebar-menu-container {
  padding-top: 25px;
}
main {
  padding-top: 28px;
}

```

**Comment by dragonstyle** [comment]
Add `content-padding-top`- thanks for the detailed write up and suggestion!

http://quarto.org/docs/output-formats/html-themes.html#layout
