### ISSUE TITLE
Publish new page on Confluence non-interactively

### ISSUE THREAD

**Issue by Zeno-of-Elea** [quarto-dev/quarto-cli#7011]
### Bug description

I am trying to set up a job that publishes a new Confluence page every time it runs but I am getting various errors like the following:

`[91mERROR: No _publish.yml file available (_publish.yml specifying a destination required for non-interactive publish)`

`[91mERROR: Multiple previous publishes exist (specify one with --id when using --no-prompt)`

I don't want to specify an existing page ID because I want to create a new page every time the job runs. I don't want to overwrite an existing one. You can do that interactively by selecting "Add new destination..." and then specify the parent page. Can I not do the same non-interactively? I might be missing something.

**Comment by macebal** [comment]
I encountered the same issue as @Zeno-of-Elea while trying to do the same thing with Quarto and I fixed it by creating a script that does the following:

1. Uses Confluence's REST API to create a new page in a given space and under a certain parent. 
2. Grabs the returned `id` for the new page and modifies `_publish.yml` to point to that page in the `url` section and to that `id` in the `id` section
3. Executes `quarto publish confluence` which will then edit the newly created page, achieving what we wanted in the first place.

**Comment by hutch3232** [comment]
@macebal thanks for sharing your solution! I think that will work for me.

That said, it would be super handy if there was a way to create _new_ pages by configuring `_publish.yml`. It seems overly complicated for less familiar users to have to use the REST API as an intermediate step. 

Thanks for considering, @dragonstyle

**Comment by hutch3232** [comment]
@dragonstyle @cderv would you consider re-opening this issue? The docs show how to publish _updates_ to pages non-interactively, but there isn't a nice way to create _new_ pages non-interactively. As shown above, it currently requires users to make a separate API call.

I also found this discussion that seemed relevant: https://github.com/quarto-dev/quarto-cli/discussions/7779

Thanks for considering!

**Comment by martheveldhuis** [comment]
New year, new person asking for this to be reopened! Needing a manual step for an otherwise hands-off process is unfortunate and quite clunky. @cscheid @dragonstyle

**Comment by cderv** [comment]
@martheveldhuis Do I understand correctly that the issue you encounter is how to publish **non-interactively** the same document to a new page ? 

I think it would be best to open a new issue, linking to this one for past context, but detailing the use case: 
- What is the encountered problem ? 
- What is the actual behavior ? 
- What is the expected behavior ? 

This way we can better classify the feature request to plan it in the future. Thank you !

**Comment by martheveldhuis** [comment]
The issue is

> how to publish non-interactively ~~the same document~~ to a new page "

I can make a new issue.
