### ISSUE TITLE
Inconsistent behaviour in Julia-1.9 between plot alone and inside gif

### ISSUE THREAD

**Issue by dgomezcastro** [quarto-dev/quarto-cli#7023]
### Bug description

When using Julia-1.9 setting the dpi in a plot the behaviour is inconsistent whether the plot is inside a `@gif` or not.

This is likely related to issue https://github.com/quarto-dev/quarto-cli/issues/6806 

### Steps to reproduce

Use the following code:

---
jupyter: julia-1.9
---

```{julia}
using Plots
```

```{julia}
plot(x->x,dpi=300)
```
```{julia}
@gif for i=1:1
  plot(x->x, dpi=300)
end
```

### Expected behavior

The size of the images in the html should be same, and be properly rescaled to text width

### Actual behavior

When doing a plot, the size is correct. When using it inside @gif, it is too big. This worked properly with Julia-1.8 (as https://github.com/quarto-dev/quarto-cli/issues/6806 ). 

Using `default(fmt="image/svg+xml")` does not help.

### Your environment

- Quarto: 1.3.450

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.3.1
      Kernels: julia-1.9, python3, SageMath-10.0

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK
```

**Comment by cscheid** [comment]
If something changes from `julia-1.8` to `julia-1.9`, it's likely that what's happening is that the generated output across different Plots versions is changing. Can you confirm that this is indeed the case? (Ideally, by inspecting the .ipynb generated directly by Jupyter Lab)

We'd like to fix this, but it's generally hard for us to chase that fast-moving target.
