### ISSUE TITLE
Caption formatting is ignored in lightbox view

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#7031]
### Bug description

When using the lightbox feature for images, any changes in the alignment of the caption is ignored. Say I use some CSS to center figure captions in the document, in the lightbox view the caption is still left aligned. Here's a couple of screenshots showing the issue:

![ss1](https://github.com/quarto-dev/quarto-cli/assets/45770265/ef8bde88-fb55-495e-a688-fea1521f542e)
![ss2](https://github.com/quarto-dev/quarto-cli/assets/45770265/22474afd-17f8-4382-b057-200a84c133c8)

### Steps to reproduce

	---
	format: html
	lightbox: true
	---

	```{css}
	/*| echo: false */
	figcaption {
	  margin: auto;
	  text-align: center;
	}
	```

	```{r}
	#| fig-cap: "Caption."
	library(ggplot2)
	ggplot(aes(x = wt, y = hp), data = mtcars) +
	  geom_point()
	```

### Quarto check output

```
Quarto 1.4.383
[>] Checking Quarto installation......OK
      Version: 1.4.383
      Path: C:\Users\au234616\AppData\Local\Programs\Quarto\bin
      CodePage: 1252
```

**Comment by mcanouil** [comment]
The caption inside the lightbox is not the same thing as the caption of the figure.
It's an entirely different HTML/CSS component.

You need to target the proper element if you want to change the styling inside the lightbox.
Use your favourite browser inspect/developer mode.

**Comment by snhansen** [comment]
@mcanouil: Of course, I'm still new to the whole CSS thing, so sorry for mislabeling this as a bug. I found the correct class to alter (`.gslide-desc` for books). 

And thanks for the note, I do include my CSS in a standalone `.css` document. The example here was just to keep is as minimal as possible.

**Comment by mcanouil** [comment]
No need to apologise. Everything is fine 😉
When unsure if it is a bug or not, you can always go to Discussion. We'll open an issue when needed from there.
