### ISSUE TITLE
typst: stop emitting figure scaffolding in non-figure images

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#7041]
````
---
format: typst
---

An image without captions.

![](./elephant.jpg)

This should work.
````

It doesn't:

<img width="706" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/08f2ba00-3883-4928-8a61-526968a4e180">

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/7036

<div type='discussions-op-text'>

<sup>Originally posted by **ptram** September 27, 2023</sup>
### Description

Hi,

I see several discussions about captions, but can't find anything related to my question. So, I'll ask.

I'm trying to have images with no "Figure" caption. When rendering to a Website, just leaving the caption between square parentheses empty, in the markdown source, works fine: the image is rendere with no caption.

When rendering to PDF through Typst, a 'Figure [#]:' always appears below the image. I would like it not to appear, since it is not needed in the style I'm after (a user manual). Said in another way: I don't want a caption under the images.

How to do to hide it? I've tried a few solutions found on the web, but none did work. Is there a direct way, maybe something already described in the manuals, but that I've not yet been able to find?

</div>

**Comment by cscheid** [comment]
This turned out to be a lot more general problem than `typst` output.

The good news is that we now have more robust marginfigure rendering in LaTeX, and HTML output that's closer to 1.3, and still have all the new features of 1.4

**Comment by ptram** [comment]
I can confirm that the figure caption no longer appears, when rendering with Typst from Quarto 1.4.391. Thank you for fixing it!
