### ISSUE TITLE
Quarto pre-release spitting error on Windows 10 machine

### ISSUE THREAD

**Issue by jonpeake** [quarto-dev/quarto-cli#7046]
### Bug description

I have tried to install the latest quarto pre-release (1.4.388) on a Windows 10 machine and I keep running into an error post-installation when I try to run `quarto help` or `quarto check` from command line: `error: the filename, directory name, or volume label syntax is incorrect. (os error 123)`

I have tried installing it to multiple locations on my PC, and I receive the same error no matter where it's installed. This does not occur when installing current release 1.3.450.

### Steps to reproduce

1. Download quarto-1.4.388-win.msi from Quarto website

2. Install just for single user (in any location under user folder) following on-screen prompts

3. Restart machine

4. Run `quarto check` or `quarto help` in command prompt

### Expected behavior

Quarto should run properly

### Actual behavior

`error: the filename, directory name, or volume label syntax is incorrect. (os error 123)`

### Your environment

- OS: Windows 10 build 19044.3448

**Comment by cderv** [comment]
Hi @jonpeake 

I can't reproduce this on my windows environment. MSI is installing find and then running ok. I installed it under default path, wichh should be `%LOCALAPPDATA%\Programs\Quarto` (or `$env:LOCALAPPDATA\Programs\Quarto` for pwsh version). 

Does it don't work there either for you ? 

Do you have an uncommon UserProfile path ? Can you share value of `LOCALAPPDATA` environment variable ? 

Also can you activate stack trace so that we can have more information on where from the error is thrown ? 
See https://quarto.org/docs/troubleshooting/#get-a-stack-trace

Thank you

**Comment by jonpeake** [comment]
Out of curiosity I tried an earlier pre-release, and it worked. Then I managed to triage down to the first pre-release where the issue started occurring, and it looks like 1.4.138 introduces the error; 1.4.134 works fine. Maybe this helps narrow down where the error is coming from?

**Comment by jonpeake** [comment]
I managed to figure out what was going on. I had installed deno separately when trying to figure out a memory leak issue, and I think this caused some compatibility issues. After taking the location to that deno install off of my path, it seems to have resolved the issue.

**Comment by cderv** [comment]
> I had installed deno separately when trying to figure out a memory leak issue, and I think this caused some compatibility issues. After taking the location to that deno install off of my path, it seems to have resolved the issue.

@dragonstyle @cscheid is it expected that an external deno on PATH would caused some issue ? 🤔 It seems not desired. 
Should we try to track what happens here ? 

> Then I managed to triage down to the first pre-release where the issue started occurring, and it looks like 1.4.138 introduces the error; 1.4.134 works fine. Maybe this helps narrow down where the error is coming from?

@jonpeake definitely helps. do you remember which version of Deno you had locally in PATH ?

**Comment by jonpeake** [comment]
Looks like the deno version was v1.35.3

**Comment by cscheid** [comment]
We should not be using an installed deno at all; if that's happening it's a bug we absolutely need to fix.
