### ISSUE TITLE
Unable to plot using Julia via JuliaCall

### ISSUE THREAD

**Issue by justanothergithubber** [quarto-dev/quarto-cli#7055]
### Bug description

I am unable to generate any plot with Julia's [`Plots.jl`](https://github.com/JuliaPlots/Plots.jl) in Quarto, only while using the `knitr` engine. This seems likely to be a `knitr` problem, as I get the following error:
```
Error in set2(resolve(...)) : 
  The object is read-only and cannot be modified.
Calls: <Anonymous> -> <Anonymous> -> set2
```
This should come from [this line in `knitr`](https://github.com/yihui/knitr/blob/42f6b3ad75f8245d26c1de3d3e0b9fa018566af3/R/defaults.R#L34) but I am not too sure how to proceed or debug from here.

Things I have tried:
- Plotting using the [`IJulia`](https://github.com/JuliaLang/IJulia.jl) Jupyter kernel seems to work fine. So this really could be an upstream (`knitr` specifically) issue. For the example, removing the `R` block will use `IJulia`, resulting in a successful render with a plot.
- Changing the `Julia` version to LTS did not fix the issue
- Issue persists in `quarto` version `1.4.388`

### Steps to reproduce

````qmd

```{r}
1
```

```{julia}
using Plots
plot(x->x)
```

````

### Expected behavior

Quarto should render without issue.

### Actual behavior

Quarto errors. For the code cell, I get the text
```
Plot{Plots.GRBackend() n=1}
```
returned instead.

### Your environment

IDE: VSCodium
OS: Windows 11

### Quarto check output

```
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: %USERPROFILE%\scoop\apps\quarto\current\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: %USERPROFILE%/scoop/apps/python/3.11.5/python.exe
      Jupyter: 5.3.2
      Kernels: julia-1.9, python3

(-) Checking Jupyter engine render....0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: %USERPROFILE%/scoop/apps/r/current
      LibPaths:
        - %USERPROFILE%/scoop/persist/r/site-library
        - %USERPROFILE%/scoop/apps/r/4.3.1/library
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Did you install the R package `JuliaCall`?

**Comment by cderv** [comment]
The error you see 
````
Error in set2(resolve(...)) : 
  The object is read-only and cannot be modified.
````

is from a change in **knitr** 1.44: https://yihui.org/en/2023/09/knitr-1-44/

Using `opts_current$set()` is not allow. This is read-only configuration, and it was always documented that way. Recently we enforce this by adding an error. 

I believe **JuliaCall** is among package using this internally, and not in their tests on CRAN so we did not detect breakage, and haven't contacted them. They use it internally at https://github.com/Non-Contradiction/JuliaCall/blob/c05473bea78a0197c639f7e82ab1c6f2e943e1cc/R/RMarkdown.R#L56C1-L60

So they need to update their version. I'll make a PR there. Sorry for the trouble, it seems the JuliaCall authors are not currently responsive so they did not see the issue before you : https://github.com/Non-Contradiction/JuliaCall/issues/208
So hopefully it will be merged.

**Comment by cderv** [comment]
So I have a PR in JuliaCall. You have two workaround now 

1. Install from the PR branch: `pak::pak("Non-Contradiction/JuliaCall#210")` 
2. Install an older version of **knitr** `devtools::install_version("knitr", "1.43")`

1 is probably prefered as 1.44 could have other fix interesting. You should check NEWS. 

Hopefully PR will be merged soon and JuliaCall updated on CRAN. 

Follow linked issue for updates

**Comment by cscheid** [comment]
@cderv you probably used the wrong milestone here :)

**Comment by cderv** [comment]
wow weird ... how did this happen... It seems I created a milestone by mistake. Sorry. I'll delete it

**Comment by cscheid** [comment]
I've already done that, no worries!

**Comment by cderv** [comment]
An update on this: As it is unresponsive on JuliaCall side, we have done some changes in **knitr** so that it won't be a problem to use JuliaCall. This will take effect in **knitr** 1.45 (and currently works in dev version)
