### ISSUE TITLE
toccolor has no effect when using typst

### ISSUE THREAD

**Issue by psads-git** [quarto-dev/quarto-cli#7061]
Consider the following quarto document:

```
---
title: "My first contact with Typst"
format: typst
toc: true
toccolor: blue
number-sections: true
---

# Section 1

Hello, typst!

## Subsection 

Hello again!
```

The table of contents comes in _black_ in the pdf output, despite using `toccolor: blue`.

**Comment by psads-git** [comment]
Maybe this is not a bug, as `toccolor` is not listed at:

[Typst Format](https://quarto.org/docs/prerelease/1.4/typst.html#typst-format)

**Comment by mcanouil** [comment]
Indeed, `toccolor` is only for LaTeX and is not even part of Typst template, see <https://quarto.org/docs/prerelease/1.4/typst.html>.
