### ISSUE TITLE
Problem with PDFs with certain characters in file names

### ISSUE THREAD

**Issue by the-solipsist** [quarto-dev/quarto-cli#7065]
### Bug description

I am generating a website using quarto. 

Some of the files have an ampersand: `author1-&-author2_2015_title.qmd`.  I've asked quarto to generate html, pdf, epub, and pandoc.md files.

The pdf files take the format `author1---author2_2015_title.pdf`, with the `&` being converted into a `-`.

The link in the "Other Formats" section on the website links to the non-existent file `author1-&-author2_2015_title.pdf`.

### Steps to reproduce

1. Create file with `&` in the file name.
2. Generate a website with quarto render.
3. Check the filename in the `_sites/` directory.
4. Check the link under "Other Formats"

### Expected behavior

Either:

1. The filename retains the `&`, or
2. The link under "Other Formats" correctly points to the created PDF, which has `-` instead of `&`.

### Your environment

- running `quarto render` from the command line.
- OS: Endeavour OS (Arch-based rolling distro)

### Quarto check output

```bash
> quarto check
Quarto 1.4.382
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.382
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/sol/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cderv** [comment]
@dragonstyle do you know where we sanitize filename for rendering ? We should probably do the same for link or get the info of modified output filename correctly ? 

If you don't know exactly where, I'll try to find exactly where this happens and why we don't get the same filename

**Comment by the-solipsist** [comment]
One clarification: the other files have ampersands. It's only the PDF that has the problem.

**Comment by dragonstyle** [comment]
I know right where this is... I'll get a fix out shortly!

**Comment by cderv** [comment]
Thank you ! I know it would be more efficient 😄 And now I know 😉
