### ISSUE TITLE
`kLatexMaxRuns` is set two times

### ISSUE THREAD

**Issue by samcarter** [quarto-dev/quarto-cli#7075]
In `formats-shared.ts`, the value for `kLatexMaxRuns` is set two times in a row. Is this deliberate or should the first one be `kLatexMinRuns`?

https://github.com/quarto-dev/quarto-cli/blob/3aeabd403a2938d4286ebbdf61c684810b0c4c97/src/format/formats-shared.ts#L247-L248

**Comment by mcanouil** [comment]
Indeed, this is incorrect.
<img width="693" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/8bbb3114-9457-404b-bf08-6f52035e299e">
Thanks for catching this (introduced 2 years ago).
https://github.com/quarto-dev/quarto-cli/pull/52/files#diff-0833118058e79b060fa03161a8abca8f5072bfe75cce90c802f800df17bbd100
