### ISSUE TITLE
knitr 1.44 breaks Quarto's figure layout classes

### ISSUE THREAD

**Issue by salim-b** [quarto-dev/quarto-cli#7078]
### Bug description

The [`fig-column` code cell option](https://quarto.org/docs/authoring/article-layout.html#code-cell-options) has no effect anymore with [**knitr 1.44**](https://github.com/yihui/knitr/releases/tag/v1.44). With knitr 1.43 it's fine. A workaround for knitr 1.44 is to set the `column` instead of the `fig-column` code cell option, which is properly respected.

### Steps to reproduce

1. Copy the following content into a new file `test.qmd`

    ````rmd
    ---
    title: "test"
    ---
    
    ## Quarto
    
    Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.
    
    ```{r}
    #| fig-cap: "Speed and Stopping Distances of Cars"
    #| fig-column: page
    #| out-width: 100%
    
    plot(cars)
    ```
    ````

2. Make sure knitr 1.44 is installed, e.g. via:

   ```r
   remotes::install_github("yihui/knitr@v1.44")
   ```

3. Render the document to HTML:

   ```sh
   quarto render test.qmd
   ```

### Expected behavior

`fig-column: page` is respected, so the figure is wider than the article body. With knitr 1.43[^down], the above `test.qmd` results in the following rendered HTML:

<img alt="Screenshot knitr 1.43" src="https://github.com/quarto-dev/quarto-cli/assets/20040931/a8c67617-68c2-4914-a714-7ddaa0b7da1d" height="800px">

[^down]: knitr 1.43 can be installed e.g. via `remotes::install_github("yihui/knitr@v1.43")`.

### Actual behavior

`fig-column: page` is **not** respected, i.e. the figure width is equal to the article body. With knitr 1.44, the above `test.qmd` results in the following rendered HTML:

<img alt="Screenshot knitr 1.44" src="https://github.com/quarto-dev/quarto-cli/assets/20040931/ac9d1a2f-65a4-4b08-a1f0-ef617fec89dd" height="800px">

### HTML output diff

The HTML output (`test.html`) differs between knitr 1.43 and knitr 1.44:

```diff
--- knitr 1.43
+++ knitr 1.44
@@ -75,7 +75,7 @@
 
 <div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
 
-<main class="content page-columns page-full" id="quarto-document-content">
+<main class="content" id="quarto-document-content">
 
 <header id="title-block-header" class="quarto-title-block default">
 <div class="quarto-title">
@@ -94,12 +94,12 @@
 
 </header>
 
-<section id="quarto" class="level2 page-columns page-full">
+<section id="quarto" class="level2">
 <h2 class="anchored" data-anchor-id="quarto">Quarto</h2>
 <p>Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <a href="https://quarto.org" class="uri">https://quarto.org</a>.</p>
-<div class="cell page-columns page-full">
+<div class="cell" data-fig-column="page">
 <div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
-<div class="cell-output-display column-page">
+<div class="cell-output-display">
 <div class="quarto-figure quarto-figure-center">
 <figure class="figure">
 <p><img src="test_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" style="width:100.0%"></p>

```

### Your environment

OS: Ubuntu 22.04

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib/R
      LibPaths:
        - /home/salim/.software/managed/r
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Thanks for the report. It seems it breaks in our website also...  https://quarto.org/docs/authoring/article-layout.html#multiple-outputs

**Comment by salim-b** [comment]
See the HTML output diff above I've added, that should probably give some clues.

**Comment by cderv** [comment]
I know exactly what happens. I am onto it. We need to add compatibility layer for pre 1.44 and post 1.44 as we change some options handling to fix #5852 and #6576 within **knitr**. In fact we miss some required adjustment in Quarto. 

However, there is a second issue when using Quarto pre-release. @cscheid if you want to look at it, you can just use 
```r
renv::install("knitr@1.43")
```
to install old knitr and see that `.fig-column-page` attributes is not working. 

<details>
<summary>intermediate .md looks like this</summary>

````markdown
::: {.cell .fig-column-page}

```{.r .cell-code}
plot(cars)
```

::: {.cell-output-display}
![Speed and Stopping Distances of Cars](test2_files/figure-html/unnamed-chunk-2-1.png){width=100%}
:::
:::
````

</details>

**Comment by cscheid** [comment]
@cderv I think this is a perfect opportunity for us to fix this through #7062. We can make sure we check for the same intermediate markdown given different knitr versions (we can make the fixups ideally on rmd.R, or very early on in the filter chain)

**Comment by cderv** [comment]
So #7084 is first step to solve this but it won't work completely because Quarto 1.4 is breaking the effect of 

```markdown
::: {.cell .fig-column-page}
```

Did not found where it happens yet...

**Comment by cderv** [comment]
> but it won't work completely because Quarto 1.4 is breaking

I have open https://github.com/quarto-dev/quarto-cli/issues/7085 to track this separately. 

#7084 should solve this issue here only.
