### ISSUE TITLE
Article layout for computation chunk does not work anymore 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7085]
https://quarto.org/docs/authoring/article-layout.html#multiple-outputs

Figure is not in the margin while `fig-column: margin` is set 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/a5bd193e-0809-49eb-ac93-3042d2713aee)

This was found in  #7078 but is really a separate issue. as knitr 1.44 was breaking the markdown output and not creating the class. 
#7084 solve that one but still this issue remain

**Comment by cscheid** [comment]
Yeah, this one is tricky. I _think_ this is happening because that element is not crossreferenceable (it's an _image_, not a figure). It gets even trickier because in 1.4, table elements can be inside figures, etc.

**Comment by cscheid** [comment]
There's a simple fix for this in `src/resources/filters/layout/columns-preprocess.lua`, but then the result triggers the same bug as #6961.
