### ISSUE TITLE
Feature request: variables in ojs chunk options (`!expr` for ojs}

### ISSUE THREAD

**Issue by bennotkin** [quarto-dev/quarto-cli#7093]
Like @agerlach in https://github.com/quarto-dev/quarto-cli/discussions/3260, I am trying to conditionally run chunks in my Quarto doc.

With R I can do this, using the front matter params and `!expr` in the chunk options (as shown in [Quarto documentation](https://github.com/quarto-dev/quarto-cli/discussions/3260)).

### Sample QMD

```
---
format: html
params:
  run: false
---
```

````
```{r}
#| eval: !expr params$run
paste("This isn't supposed to run if `run` is false. `run`= ", params$run)
```
````

And, because `!expr params$run` evaluates to `false`, that chunk doesn't run. Good!

For Observable JS, I can *kind of* do this ... and not sure how much it's working.

I can pass `params$run` to ojs with `ojs_define()`, and use this new variable in the ojs chunk options with `ojs_define()`

````
```{r}
ojs_define(run = params$run)
```
````

and check that ojs does indeed have it

````
```{ojs}
"OJS knows run = " + run
```
````

Prints: `"OJS knows run = false"`

and then test it out in the `eval` chunk option.

````
```{ojs}
//| eval: !expr run

"Will an undefined variable trigger an error?"
run // Try a defined variable (defined as false in YAML)
undefined_variable // Try an undefined variable
```
````

Prints:
`"Will an undefined variable trigger an error?"`
`false`

So, we see that the code _does_ run, but interestingly the undefined variable doesn't cause a runtime error. (The rendered output also frames the cell with ":::{.cell eval=“{”value”:“run”,“tag”:“!expr”}“}" at the start and ":::" at the end.". These can be fairly easily hidden with CSS.)

Whereas, if we run the same chunk with `eval: true` we _do_ get a runtime error.

````
```{ojs}
//| eval: true

"Will an undefined variable trigger an error?"
run // Try a defined variable (defined as false in YAML)
undefined_variable // Try an undefined variable
```
````

Prints:
`"Will an undefined variable trigger an error?"`
`false`
Errors: `undefined_variable is not defined`

**All to say, `!expr` is doing something in the ojs cell, but I'm not sure what, and it would be great to have an actual way to use variables as chunk options.**

**Comment by cscheid** [comment]
````
```{ojs}
//| eval: !expr run

"Will an undefined variable trigger an error?"
run // Try a defined variable (defined as false in YAML)
undefined_variable // Try an undefined variable
```
````

`!expr` is a knitr-specific hack that isn't supported in OJS. Unfortunately, the very hack that enables us to make that work in quarto (disabling validation) makes it impossible for us to tell you that you shouldn't use it in OJS.

> it would be great to have an actual way to use variables as chunk options.
This is not possible in general, because those are fundamentally different aspects of evaluating code. Code cell options often need to be known _ahead of evaluation_, and so this isn't a well-defined thing to want to have. The fact that this works in knitr (barely! It's one of the most common sources of issue reports in our repo) unfortunately doesn't translate to any of the other engines.

**Comment by bennotkin** [comment]
Thanks for the explanation and clarification.

An alternate approach I considered, which I think would be cleaner overall, would be using conditional [includes](https://quarto.org/docs/authoring/includes.html) as you can, for example, in Jekyll with Liquid and in Hugo with Go. You could then conditionally include different QMD files based on the base file's metadata.

I've not seen anything about logic in Quarto's shortcodes – or , so I didn't pursue this farther. Would this be possible?

**Comment by cscheid** [comment]
We have this: https://quarto.org/docs/authoring/conditional.html

**Comment by bennotkin** [comment]
Thanks. I had seen this, and like https://github.com/quarto-dev/quarto-cli/discussions/3260, am looking for conditional evaluation. Do


 For now, I think I'll either maintain separate files or maybe pre-process the file before running Quarto

**Comment by bennotkin** [comment]
Thanks. I had seen this page, and like https://github.com/quarto-dev/quarto-cli/discussions/3260, am looking for conditional evaluation.

Do you think it will be possible at some point to conditionally include QMD files? For now, I think I'll try to pre-process the file before running Quarto, and would think this would be implementable on Quarto's end too

**Comment by cscheid** [comment]
> Thanks. I had seen this page, and like https://github.com/quarto-dev/quarto-cli/discussions/3260, am looking for conditional evaluation.

Every cell the form

````
```{r}
#| eval: !expr foo
...
```
````

should be exactly equivalent to

````
```{r}
if (foo) {
    ...
}
```
````

Does this fit your requirement?
