### ISSUE TITLE
Nested call out blocks not showing when setting appearance="minimal"

### ISSUE THREAD

**Issue by lloydhamilton** [quarto-dev/quarto-cli#710]
Hey, I seem to have found an unexpected behaviour with nested callout blocks. Perhaps I am not using it as designed. 😂

Any help would be appreciated.

### When **NOT** defining appearance="minimal' 

```
:::{.callout-tip}
# Task - 5 mins

Starting with the string: `task = 'working with strings'`

Do the following:

1. Convert everything to lower case.
2. Get the length of your string.
3. Add the text: `'in Python'`, separated by a space `(' ')`, save this as a new variable `task_py`.
4. Split up `task_py` into a list.

:::{.callout-caution collapse=true}
# Minimal

Text text texts

:::
:::
```
<img width="902" alt="Screenshot 2022-04-22 at 10 17 31" src="https://user-images.githubusercontent.com/64639944/164676469-48a2c59f-1182-4146-bea0-a5031e5876c7.png">

### When appearance="minimal"

```
:::{.callout-tip}
# Task - 5 mins

Starting with the string: `task = 'working with strings'`

Do the following:

1. Convert everything to lower case.
2. Get the length of your string.
3. Add the text: `'in Python'`, separated by a space `(' ')`, save this as a new variable `task_py`.
4. Split up `task_py` into a list.

:::{.callout-caution collapse=true appearance="minimal"}
# Minimal

Text text texts

:::
:::
```
<img width="902" alt="Screenshot 2022-04-22 at 10 18 38" src="https://user-images.githubusercontent.com/64639944/164676680-9993b960-0300-4816-b634-6b1778ab8a04.png">

**Comment by dragonstyle** [comment]
Thanks for letting us know (here 81ebc1c3f8da60b47fc185f7739886f2788a59db).

A fresh release is being built now...
