### ISSUE TITLE
Missing results using search widget on quarto website

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#7105]
### Bug description

I occasionally felt like the search function was missing some results but I just stumbled on an egregious example: searching for "format" with the search widget on quarto.org yields only one matching document.

### Steps to reproduce

Go to https://quarto.org/, click the search icon and type "format".

### Expected behavior

Lots of results , as in https://www.google.com/search?q=%22format%22+site%3Aquarto.org

### Actual behavior

Only results from the "PDF Options" page are listed.

### Your environment

- Browser: Chrome 116
- OS: Pop!_OS 22.04

**Comment by knuesel** [comment]
This does reproduce the issue: see the "1 matching documents" at the top of the results. You're only getting results from "PDF Options"...

**Comment by mcanouil** [comment]
Since Quarto web is building the search index and providing it to Algolia, I am not sure if the issue is in the index or on Algolia script/algorithm.
