### ISSUE TITLE
Quarto doesn't render properly

### ISSUE THREAD

**Issue by HVinther** [quarto-dev/quarto-cli#7107]
### Bug description

Quarto file doesn't appear in file > new file  list. qmd-files only renders as hmtl regardsless of format option.

### Steps to reproduce

Follow the setup guide and dowload the provided .qmd file in the getting started section. Change format to anything, fx. beamer or revealjs and render

### Expected behavior

Output should be a slideshow

### Actual behavior

Output is a continuous html page

### Your environment

- Ide: Rstudio 2023.06.2 Build 561
- os: Fedora 39

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /home/hansvl/opt/quarto-1.3.450/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/bin/python3
      Jupyter: 5.3.2
      Kernels: python3

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/hansvl/R/x86_64-redhat-linux-gnu-library/4.3
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
> appear in file > new file list. qmd-files only renders as hmtl regardsless of format option.

It seems to me that you're using RStudio. Is that the case? If so, the place to file a bug report is https://github.com/rstudio/rstudio

**Comment by dragonstyle** [comment]
Closing as this issue is now outdated.
