### ISSUE TITLE
Unknown shortcodes are no more passed unmodified as our hugo docs says

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7108]
This follows question by @lwasser in https://github.com/quarto-dev/quarto-cli/issues/5902

Our Hugo doc on shortcodes (https://quarto.org/docs/output-formats/hugo.html#shortcodes) says: 

> Note that Hugo [shortcodes](https://gohugo.io/content-management/shortcodes/) and Quarto [shortcodes](https://quarto.org/docs/extensions/shortcodes.html) share the same basic syntax (e.g. {{< var foo >}}). **This is normally not a problem as shortcodes not recognized by Quarto are passed through unmodified to Hugo.**

However it does not seem to be true anymore

````markdown
---
title: "Test"
format: hugo-md
---

The below shortcode is not known and should be passed as-is

{{< noticeowl "learn" >}}

````

With 1.3 we correctly get 
````markdown
---
title: "Test"
format: hugo-md
---

The below shortcode is not known and should be passed as-is

{{< noticeowl “learn” >}}
````

With 1.4 we get 
````markdown
---
title: "Test"
format: hugo-md
---

The below shortcode is not known and should be passed as-is
````

Maybe this is expected as we now get the warning 
````
WARNING (C:\Users\chris\Documents\DEV_R\quarto-cli\src\resources\filters\./customnodes/shortcodes.lua:370) Shortcode 'noticeowl' not found
````

and we do indeed return nothing 
https://github.com/quarto-dev/quarto-cli/blob/cae0b3182e536fcb47ec71038f37274986120327/src/resources/filters/customnodes/shortcodes.lua#L333-L337

* If really this is new behavior, we should update documentation, and probably offer another escape mechanism, at least for Hugo 
* Either a regression in feature to fix

**Comment by cscheid** [comment]
I think _this_ one is relatively easy to fix! It's "just" a matter of reconstructing the shortcode as the default renderer for the Shortcode AST node. I simply wasn't aware of the "send shortcodes unchanged" behavior when I implemented a change. My apologies. We'll get that sorted out.

**Comment by cscheid** [comment]
@lwasser Let us know if this unblocks you, and thanks for the continued patience!
