### ISSUE TITLE
Search bar only works when scrolled to top of page on mobile

### ISSUE THREAD

**Issue by prncevince** [quarto-dev/quarto-cli#7117]
### Bug description

On mobile, when clicking the search bar after slightly scrolling down from the top of the page, then clicking the search box to activate keyboard, the UI un-focuses the search box.

This does not happen when scrolled to the top of the page, and thus, searching can occur normally. 

### Your environment

- Apple iPhone, Safari

**Comment by mcanouil** [comment]
For illustration purposes:

https://github.com/quarto-dev/quarto-cli/assets/8896044/2a8fed73-ccea-4eab-8c9f-b731557a6728

**Comment by prncevince** [comment]
Thanks for illustrating @mcanouil!
