### ISSUE TITLE
Multilevel `{{< include ... >}}` calls fail

### ISSUE THREAD

**Issue by r-cheologist** [quarto-dev/quarto-cli#7123]
### Bug description

Given the following project:
```
.
├── 00_Presentation.qmd
├── level_1
│   ├── level_2
│   │   └── index_level_2.qmd
│   └── _r_conf.qmd
└── _quarto.yml
```
, where `./_quarto.yml` looks like:
```qmd
format:
  revealjs
```
, `./00_Presentation.qmd` like:
```qmd
---
title:
  "A Presentation"
subtitle:
  "to demonstrate inclusion issues"
author:
  "`r-cheologist`"
format:
  revealjs
---

{{< include level_1/level_2/index_level_2.qmd >}}
```
, `./level_1/_r_conf.qmd` like:
````qmd
---
---

```{r}
#| label: package-loading
#| echo:  false
library(magrittr)
```
````
and `./level_1/level_2/index_level_2.qmd` like this:
```qmd
---
---

{{< include ../_r_conf.qmd >}}
```
`quarto` is getting variously confused regarding where to look for the two levels of includes.

With the setup as presented above, `quarto render` issued in the top level directory fails as follows:
```bash
[1/2] level_1/level_2/index_level_2.qmd


processing file: index_level_2.qmd
                                                                                                            
output file: index_level_2.knit.md

[2/2] 00_Presentation.qmd
ERROR: Include directive failed.
  in file /home/rstudio/quarto/00_Presentation.qmd, 
  in file level_1/level_2/index_level_2.qmd, 
  could not find file /home/rstudio/_r_conf.qmd.

Stack trace:
  in file /home/rstudio/quarto/00_Presentation.qmd, 
  in file level_1/level_2/index_level_2.qmd, 
  could not find file /home/rstudio/_r_conf.qmd.
...
```
while if changing the path in the include call in `./level_1/level_2/index_level_2.qmd` to `level_1/_r_conf.qmd`, as apparently expected according to the `could not find file /home/rstudio/_r_conf.qmd` bit in the error message, the `quarto render` call never even proceeds to the second stage and fails with:
```bash
[1/2] level_1/level_2/index_level_2.qmd
ERROR: Include directive failed.
  in file /home/rstudio/quarto/level_1/level_2/index_level_2.qmd, 
  could not find file /home/rstudio/quarto/level_1/level_2/level_1/level_2/_r_conf.qmd.

Stack trace:
  in file /home/rstudio/quarto/level_1/level_2/index_level_2.qmd, 
  could not find file /home/rstudio/quarto/level_1/level_2/level_1/level_2/_r_conf.qmd.
...
```
I read this as a divergence in relative path expectation of first and second processing stage.

### Steps to reproduce

See above.

### Expected behavior

Multiple levels of includes should path-resolve cleanly, respectively all processing stages of `quarto` should handle relative includion paths identical. 

### Actual behavior

See above.

### Your environment

- IDE: RStudio Server 2023.03.0 Build 386
- OS: docker image `bioconductor/bioconductor_docker:devel`

### Quarto check output

```bash
Quarto 1.4.398
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.398
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.10
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/rstudio/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/local/lib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
This is working as intended. Include paths are not resolved wrt to the location of the include file. They're resolved relative to the original file.

(I understand that you probably think this is unintuitive. In fact, the behavior you're expecting is what we originally shipped `include` with, but it was even more unintuitive for complex projects, and so we switched to a simpler, more direct one.)

**Comment by mcanouil** [comment]
Note that you could use path relative to the root of the project using a leading `/` which would allow your file to be included to behave uniformly independently of where the file is included via the shortcode.

**Comment by r-cheologist** [comment]
Uff. Thanks, @cscheid and @mcanouil . Not intuitive and as you pointed out was working differently with earlier versions, which is how I ran into this: revisiting earlier code... Thans for the absolute path relative to the project root hint!
