### ISSUE TITLE
equals sign in figure/table legend causes warning in inline result

### ISSUE THREAD

**Issue by mjsmith037** [quarto-dev/quarto-cli#7136]
### Bug description

When a figure or table caption contains an equals sign (=), running the chunk produces a warning. This has no discernible effect when knitting: both legends are printed correctly and the warning is not displayed in the knitted document. It also appears that the warning is only displayed when displaying output inline.

### Steps to reproduce

````
---
title: "Untitled"
format: html
---

```{r}
#| label: fig-one
#| fig-cap: "this is fine"
plot(cars)
```

```{r}
#| label: fig-two
#| fig-cap: "this is not = fine"
plot(cars)
```

# Warning messages:
# 1: In value[[3L]](cond) : Failed to parse chunk options in body:
# Error in parse(text = code, keep.source = FALSE): <text>:1:23: unexpected symbol
# 1: alist( label: tbl-one tbl
#                           ^
#
# 2: In opts$engine <- unlist(strsplit(rmdChunkOpts, split = "(\\s|,)+"))[[1]] :
#   Coercing LHS to a list
````

### Your environment

- IDE: RStudio 2023.06.1+524
- OS: Ubuntu 22.04.3 LTS

### Quarto check output

```bash
quarto check
```

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.353
      Path: /usr/lib/rstudio/resources/app/bin/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.18
      Path: /home/michalsm/.virtualenvs/r-reticulate/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib/R
      LibPaths:
        - /home/michalsm/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Where does this warning come from / appear exactly?
Using the latest development version I cannot reproduce this in VSCode.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/620ee417-ac2b-4e9c-afbf-5b555088069c">

**Comment by cscheid** [comment]
Thanks for the report. Unfortunately, I have the same versions of quarto, knitr, and rmarkdown, and cannot reproduce the issue:

````
$  cat 7136.qmd
---
title: "Untitled"
format: html
---

```{r}
#| label: fig-one
#| fig-cap: "this is fine"
plot(cars)
```

```{r}
#| label: fig-two
#| fig-cap: "this is not = fine"
plot(cars)
```

$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.353
      Path: /Users/cscheid/repos/github/cscheid/quarto-regress/releases/v1.3.353/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /Users/cscheid/virtualenvs/homebrew-python3/bin/python3
      Jupyter: 5.1.3
      Kernels: python3, julia-1.9

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK

$ quarto --version
1.3.353
$ quarto render 7136.qmd

processing file: 7136.qmd
1/5
2/5 [fig-one]
3/5
4/5 [fig-two]
5/5
output file: 7136.knit.md

pandoc
  to: html
  output-file: 7136.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Untitled

Output created: 7136.html
````

**Comment by cderv** [comment]
I believe this was a RStudio issue and it has been fixed 
* https://github.com/rstudio/rstudio/issues/13326

It should be available in latest daily build of RStudio https://dailies.rstudio.com/rstudio/ocean-storm/

**Comment by mjsmith037** [comment]
My apologies for missing these duplicates

**Comment by mcanouil** [comment]
No worries, it is not that easy to find the issue in the right repository since the different tools interact together.
