### ISSUE TITLE
Expected a cached code page for this installation

### ISSUE THREAD

**Issue by tomicapretto** [quarto-dev/quarto-cli#715]
Hi!

When I try to use `quarto render` I have the following error

```shell
ERROR: Expected a cached code page for this installation
```

Then I do 

```shell
C:\Users\caprettot>quarto check
```

And I get

```shell
C:\Users\caprettot>quarto check

[>] Checking Quarto installation......OK
      Version: 0.9.298
      Path: C:\Users\caprettot\AppData\Local\Programs\Quarto\bin\
      CodePage: Unable to read code page

[>] Checking basic markdown render....OK

ERROR: Expected a cached code page for this installation
```

What does this error mean? How can I fix it? Thanks a lot for this tool!

**Comment by jjallaire** [comment]
@dragonstyle It seems like at a minimum we should survive the failure to read a cached code page

**Comment by dragonstyle** [comment]
@jjallaire you are right! I've hardened this a bit here f17f5fc43ddf20a5f3598a26053bbf25f1407a1e and a release is being built with this change right now. @tomicapretto would you mind giving it a try and letting me know how things look (I simulated the condition, but would love to hear it works in the wild)?

**Comment by tomicapretto** [comment]
Works like a charm! Thanks for the prompt response.

```shell
quarto render README.md --to html
pandoc
  to: html
  output-file: README.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  filters:
    - crossref

metadata
  document-css: false
  link-citations: true
  lang: en

Output created: README.html
```
