### ISSUE TITLE
Blockquote border misplaced when footnote is in the margin

### ISSUE THREAD

**Issue by petrbouchal** [quarto-dev/quarto-cli#7153]
### Bug description

When a blockquote contains a footnote reference placed into the margin, the left border of the blockquote is placed on the left page margin. 

This seems to be because the blockquote gets assigned some extra classes when the page layout is affected by the presence of notes in the margin.

### Steps to reproduce

Create and render (`quarto render file.qmd`) the following file, with no _quarto.yml or CSS file.

````qmd
---
title: hello
format: 
  html: default
reference-location: margin
---

> Blockquote
> 
> on multiple lines
> with a footnote [^1]

[^1]: Hello

> Blockquote without 
> a
> 
> footnote

````

### Expected behavior

The blockquote border should appear close to the left margin of the paragraphs whether or not there is a margin note.

### Actual behavior

The left border of the blockquote is placed on the left page margin for the blockquote with a margin-placed note, while other blockquotes on the same page render correctly if they do not contain a margin note.

<img width="1215" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/1666657/1ddc9335-5ef1-4f42-9707-de851d5dc059">

### Your environment

- OS: MacOS Sonoma 14.0 (23A344)
- no IDE used, just quarto CLI

Occurs on quarto stable release as well as latest pre-release.

### Quarto check output

Quarto 1.4.398
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.398
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/petr/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.1.3
      Kernels: python3, ir

(/) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources
      LibPaths:
        - /Users/petr/Library/R/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK

**Comment by cderv** [comment]
While confirming things for #8036, here is a small reprex

````markdown
---
title: "Title"
format:
  html:
    toc: true
---

> text [^note]

[^note]: Footnote.

````

The HTML produced after quarto post processor is this one, 
````html
<blockquote class="blockquote page-columns page-full">
<p>text <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;Footnote.</p></li></div></blockquote>
````

from this one 
````html
<blockquote>
<p>text <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</blockquote>
````

We probably want something like that 
````html
<div class="page-columns page-full">
<blockquote class="blockquote">
<p>text <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref" aria-expanded="false"><sup>1</sup></a></p>
</blockquote>
<div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;Footnote.</p></li</div></div>
````
