### ISSUE TITLE
VS Code outline panel gets confused by callout titles

### ISSUE THREAD

**Issue by wch** [quarto-dev/quarto-cli#716]
In VS Code's Outline panel, it thinks that callout titles are level 2 headers, but that doesn't really reflect the structure of the document. Screenshot:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/86978/164774714-02375963-c2c6-4f68-aac9-d862da1bb187.png">

I think that it would make sense to not show them in the outline at all.

**Comment by jjallaire** [comment]
Good catch! I will make this change before we announce the extension

**Comment by jjallaire** [comment]
Fixed with https://github.com/quarto-dev/quarto-vscode/commit/5e9e20f67a2a4da07ee9a391c4d25ac2a486e2a6
