### ISSUE TITLE
The Generated HTML Is Different from the One Served by `quarto preview`

### ISSUE THREAD

**Issue by RoyiAvital** [quarto-dev/quarto-cli#7162]
### Bug description

I have a simple example where the output HTML looks different from the HTML served by `quarto preview`.  
In this case the output HTML doesn't show element which works as expected in the preview.

The issue happens when using the [`animate`](https://github.com/fradav/quarto-revealjs-animate) extension.  
Yet the actual issue is the difference between the preview and the generated HTML which shouldn't be different regardless.

**Remark**: When I mean preview, I mean copying the address given in the preview window of VS Code: `http://localhost:<SocketNumber>`.

### Steps to reproduce

Install the [`animate`](https://github.com/fradav/quarto-revealjs-animate) extension.

Render the following:

````qmd
---
title: My Presentation
format: 
  revealjs:
    theme: [default]
    width: 1200
    height: 800
revealjs-plugins:
  - animate
filters: 
  - animate
---

## Conversion {.unlisted auto-animate="true"}

:::{.callout-warning icon=false data-id="ColGrayEx"}

#### [{{< iconify ph eyedropper-sample >}}]{style="color: #f0ad4e;"} Example

```yaml { .animate src="YChannelTrickYuv.svg" }
setup:
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-34"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "2"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-12"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "1"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-35"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "3"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-31"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "3"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-36"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "5"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-32"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "6"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-37"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "7"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-38"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "9"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-39"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "8"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-40"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "11"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-33"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "11"
```

:::
````

Make sure to download the attached SVG and put in the same place named `YChannelTrickYuv.svg`.

![YChannelTrickYuv](https://github.com/quarto-dev/quarto-cli/assets/7347975/9a5b8209-afd8-467e-b557-16791ce6b229)

### Expected behavior

I expect the generated HTML to match the preview.

### Actual behavior

It seems the generated HTML is missing some code at the end of the file.
I can attach the code of each.

### Your environment

- IDE: Visual Studio 1.83, Quarto Extension `1.101`, Quarto CLI 1.3.450`.
- OS: Windows 10.

I tried the HTML on Firefox, Edge, Chrome.

### Quarto check output

```bat
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: D:\Applications\Programming\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK
```

**Comment by cscheid** [comment]
Can you produce a smaller example and show us exactly what's the difference between the outputs? We need a more direct example to go on.

You can inspect the .html from `quarto preview` by opening a text editor while `quarto preview` is running.

**Comment by RoyiAvital** [comment]
OK, I think I know what's going on.
The extension asks for a source file.

I provide it (Next to the HTML file) and the path.
For some reason, security I guess, it can't access it on the HTML file but it does on the preview served.

If I upload the SVG somewhere with a reachable URL, then it seems to work in both cases.
Does it make sense?

**Comment by cscheid** [comment]
We really do need a small repro.

**Comment by RoyiAvital** [comment]
@cscheid , For `animate` to work and SVG is needed.
So if you download the SVG image in my previous post this will also give the same issue (Just removed some of the animations):

````qmd
---
title: My Presentation
format: 
  revealjs:
    theme: [default]
    width: 1200
    height: 800
revealjs-plugins:
  - animate
filters: 
  - animate
---

## Conversion {.unlisted auto-animate="true"}

:::{.callout-warning icon=false data-id="ColGrayEx"}

#### [{{< iconify ph eyedropper-sample >}}]{style="color: #f0ad4e;"} Example

```yaml { .animate src="YChannelTrickYuv.svg" }
setup:
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-34"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "2"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-12"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "1"
```

:::
````

**Comment by cscheid** [comment]
I am going to repeat what I said earlier:

- Can you produce a smaller example and show us exactly what's the difference between the outputs?

I'm sorry for being blunt, but you only addressed the first part. We won't be able to help you if you don't provide us with the information we need.

**Comment by RoyiAvital** [comment]
@cscheid , Could you explain me what do you mean by a smaller?

The difference is that in the preview things works while in the HMTL it doens't.

**Comment by mcanouil** [comment]
The following is small:
- number of lines,
- number of dependencies,
- *etc.*

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by RoyiAvital** [comment]
OK, I can do this:

```qmd:
---
title: My Presentation
format: revealjs
revealjs-plugins:
  - animate
filters: 
  - animate
---

## Conversion

:::{.callout-warning}

```yaml { .animate src="YChannelTrickYuv.svg" }
setup:
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-34"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "2"
  - element: "#cell-SkosRxTPTDDGwb4RYgK4-12"
    modifier: attr
    parameters:
      - class: fragment
        data-fragment-index: "1"
```

:::
```

All the other things are needed to observe the missing functionality.

**Comment by RoyiAvital** [comment]
OK, There is more information on https://github.com/fradav/quarto-revealjs-animate/issues/3.
It seems the Plug In requires the assets to be in `resources` flag. 
So if they are not, it will work on preview yet not on HTML.

I am not near my workstation to verify, until I do, I think this should be put in _hold_.

Thanks for the assistance.
