### ISSUE TITLE
How do I set the default engine for Rmd files?

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#7166]
### Bug description

I have an `.Rmd` file for which I want to use the `jupyter` engine.  I have tried setting `engine: jupyter` in the `_quarto.yml` file, and in the `.Rmd` file, but I always get Knitr engine rendering.    See the repo (below) for the exact incantation, that I believe is correct according to the docs.   Have I missed something?

### Steps to reproduce

```bash
git clone https://github.com/matthew-brett/minquarto
cd minquarto
quarto render
```

You will see that Knitr does the rendering despite `engine: jupyter` in `_quarto.yml` and (twice) in the YaML metadata for `test.Rmd`.

### Expected behavior

Code chunk should be rendered with Jupyter.

### Actual behavior

Code chunk rendered with Knitr.

### Your environment

- OS Mac Sonoma 14.0 on M2

### Quarto check output

```bash
$ quarto check
Quarto 99.9.9

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK

[✓] Checking versions of quarto dependencies......OK

[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/mb312/dev_trees/quarto-cli/package/dist/bin


(|) Checking tools....................
(/) Checking tools....................
(-) Checking tools....................
(\) Checking tools....................
(|) Checking tools....................[2K[G
[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)


(|) Checking LaTeX....................
(/) Checking LaTeX....................
(-) Checking LaTeX....................
(\) Checking LaTeX....................
(|) Checking LaTeX....................
(/) Checking LaTeX....................
(-) Checking LaTeX....................
(\) Checking LaTeX....................
(|) Checking LaTeX....................
(/) Checking LaTeX....................
(-) Checking LaTeX....................
(\) Checking LaTeX....................
(|) Checking LaTeX....................[2K[G
[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2022


(|) Checking basic markdown render....
(/) Checking basic markdown render....
(-) Checking basic markdown render....
(\) Checking basic markdown render....
(|) Checking basic markdown render....
(/) Checking basic markdown render....
(-) Checking basic markdown render....[2K[G
[✓] Checking basic markdown render....OK


(|) Checking Python 3 installation....
(/) Checking Python 3 installation....
(-) Checking Python 3 installation....
(\) Checking Python 3 installation....[2K[G
[✓] Checking Python 3 installation....OK
      Version: 3.10.13
      Path: /opt/homebrew/opt/python@3.10/bin/python3.10
      Jupyter: 5.1.0
      Kernels: python3, ir


(|) Checking Jupyter engine render....
(/) Checking Jupyter engine render....
(-) Checking Jupyter engine render....
(\) Checking Jupyter engine render....
(|) Checking Jupyter engine render....
(/) Checking Jupyter engine render....
(-) Checking Jupyter engine render....
(\) Checking Jupyter engine render....
(|) Checking Jupyter engine render....
(/) Checking Jupyter engine render....
(-) Checking Jupyter engine render....
(\) Checking Jupyter engine render....
(|) Checking Jupyter engine render....
(/) Checking Jupyter engine render....
(-) Checking Jupyter engine render....
(\) Checking Jupyter engine render....
(|) Checking Jupyter engine render....
(/) Checking Jupyter engine render....
(-) Checking Jupyter engine render....
(\) Checking Jupyter engine render....
(|) Checking Jupyter engine render....
(/) Checking Jupyter engine render....
(-) Checking Jupyter engine render....
(\) Checking Jupyter engine render....
(|) Checking Jupyter engine render....
(/) Checking Jupyter engine render....
(-) Checking Jupyter engine render....
(\) Checking Jupyter engine render....
(|) Checking Jupyter engine render....
(/) Checking Jupyter engine render....
(-) Checking Jupyter engine render....
(\) Checking Jupyter engine render....
(|) Checking Jupyter engine render....
(/) Checking Jupyter engine render....
(-) Checking Jupyter engine render....[2K[G
[✓] Checking Jupyter engine render....OK


(|) Checking R installation...........
(/) Checking R installation...........
(-) Checking R installation...........[2K[G
[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /opt/homebrew/Cellar/r/4.3.1/lib/R
      LibPaths:
        - /Users/mb312/Library/R/arm64/4.3/library
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.1/lib/R/library
      knitr: 1.44
      rmarkdown: 2.24


(|) Checking Knitr engine render......
(/) Checking Knitr engine render......
(-) Checking Knitr engine render......
(\) Checking Knitr engine render......
(|) Checking Knitr engine render......
(/) Checking Knitr engine render......
(-) Checking Knitr engine render......
(\) Checking Knitr engine render......
(|) Checking Knitr engine render......[2K[G
[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Why are you using Rmarkdown file in Quarto? As the name suggest Rmarkdown is for R thus knitr.
You need to use "qmd" files for Quarto.

I am goign ahead and close this as it's not a bug but an improper usage.

**Comment by matthew-brett** [comment]
I'm sorry - but I believe you are incorrect and this issue should be opened again.   The documentation clearly implies that you can change the engine type for notebooks.    `.Rmd` files are absolutely supported in `quarto`, and I have been using them for a long time.  For example <https://quarto.org/docs/get-started/hello/rstudio.html>:

> Quarto is a multi-language, [next-generation](https://quarto.org/docs/faq/rmarkdown.html) version of R Markdown from Posit and includes dozens of new features and capabilities while at the same being able to render most existing Rmd files without modification.

**Comment by matthew-brett** [comment]
And in case it wasn't clear - here are the docs on changing the engine for a given notebook <https://quarto.org/docs/computations/execution-options.html#engine-binding> - including - according to that page - `.Rmd` notebooks.

**Comment by mcanouil** [comment]
> while at the same being able to render most existing Rmd files without modification.

To me it does not mean Rmd files behave as Quarto files, but that Quarto can use them.

> And in case it wasn't clear - here are the docs on changing the engine for a given notebook https://quarto.org/docs/computations/execution-options.html#engine-binding - including - according to that page - .Rmd notebooks.

Possibly some documentation improvement, as to me it makes no sense to have `engine: knitr` for a Jupyter notebook or `engine: jupyter` for an Rmarkdown document.

@cscheid @cderv Is the engine really supposed to be changed from their default binding engine for "ipynb" and "rmd" files?

**Comment by matthew-brett** [comment]
Certainly the documentation is immensely confusing if in fact you mean that you can only change the engine for `.qmd` files and not any other valid notebook type - `.Rmd`, `.ipynb`, or `.md`.

**Comment by mcanouil** [comment]
That is my belief since the way Rmarkdown and Jupyter notebooks are supposed to work.
Also as far as I know this was never possible (at least from 1.1 to now).

**Comment by cscheid** [comment]
> Certainly the documentation is immensely confusing if in fact you mean that you can only change the engine for .qmd files and not any other valid notebook type - `.Rmd`, `.ipynb`, or `.md`.

I believe this limitation exists for `.Rmd` and `.ipynb`. I'm sorry you're left confused, but if you can point to us what we should improve in the documentation, we can then try and fix it.

`.Rmd` implies "rmarkdown" fairly strongly, which in turn implies knitr; that's what RMarkdown _is_. `.ipynb`, in turn, implies "IPython notebook", which in turn implies jupyter.

**Comment by mcanouil** [comment]
@cscheid i see where the confusion comes from, since you confirmed I'll make a PR later this weekend to make explicit what was implicit.

**Comment by matthew-brett** [comment]
Is there a reason why it is not possible to change the engine for e.g. .Rmd files?   I ask because qmd files are less common, and don't render as well in JupyterLab by default, so it would be much preferable to me if I could use the Jupyter engine for `.Rmd`.

**Comment by mcanouil** [comment]
"Less common" as was rmd files when rmarkdown got released that did not imply changing how things work.

If you have issue with Quarto documents in Jupyter Lab, please open a GitHub discussion to sort this out.
Changing what rmarkdown/opt n are is not the solution.

**Comment by matthew-brett** [comment]
Just to say - I'm an experienced open-source developer - and I'm involved in the maintenance of quite a few packages.

In this case - where you have reason to think I've thought through what I am asking - what I would have hoped for in your final response would be something like:

"""
I'm sorry - I don't understand why you prefer .Rmd files over .qmd files for use with Jupyter.  Can you say more?

or

I think I understand why you prefer to use Jupyter kernels with `.Rmd` files, but there are <some technical reasons explained> that make this difficult.
"""

But your response above comes across as impatient and lacking detail - and I don't think I've given you any reason to be impatient.

**Comment by mcanouil** [comment]
I did not assume anything about your use case or your experience.
Here you are assuming some intent behind my message for some reasons ...

Please refrain making assumptions on my intent based on wording on a language that is not my native one.

This is part of the code of conduct by the way.

**Comment by cscheid** [comment]
> Is there a reason why it is not possible to change the engine for e.g. .Rmd files?

To the best of my understanding, the answer is that .Rmd, for quarto, implies "be compatible with RMarkdown", and jupyter engines are not.

But, let me ask you differently. Have you tried simply renaming those files to .qmd? If you're editing the .Rmd to add `engine: jupyter` (which isn't an rmarkdown feature to begin with), then why not rename them to .qmd and actually use them as quarto files? Much of rmarkdown works in quarto unchanged.

**Comment by cscheid** [comment]
Actually let me be more direct here.

".Rmd", in quarto, is a direct synonym for "use the knitr engine". See `src/execute/rmd.ts`, line 59. Similarly, line 129 in `src/execute/jupyter.ts` means that `.ipynb` is a direct synonym for "use the jupyter engine". That's just how quarto works.

To "use knitr as engine for ipynb" (or vice-versa), we would have to substantially change how engine detection happens. This would have consequences for a wide number of subsystems in quarto (embeds, includes, the new manuscript format, etc).

In the meantime, I don't see the value this would get. We would have to reteach our users about the logic in file detection, which, currently, is: "if .qmd, then `engine:` is used. Otherwise, file extensions are used". That logic accomodates well the backwards compatibility that we value in .rmarkdown files, as well as prevents jupyter users from being surprised that knitr is being used as their engine because of a `_quarto.yml` option.

This really is working as designed.

**Comment by cscheid** [comment]
All this said, I agree with you that our documentation page badly describes the situation. I'll make the fix right away.

**Comment by matthew-brett** [comment]
Yes - that is what I was expecting you to say - that it would introduce substantial complications in the code to allow setting the engine for `.Rmd` files.  I suppose it's just possible that soneone has `.Rmd` files, maybe with `.qmd` files, and has set `engine` in `_quarto.yml` - and so they would see a change in behavior if you made the `engine` setting effective for `.Rmd` files.   I don't think it's very hard to explain though - that is what your current docs appear to be explaining - and that seemed clear enough to me.

Closing - I get that this change is too complex, and my use-case is relatively obscure.
