### ISSUE TITLE
There are two .column-screen-inset-left, zero .column-screen-inset-right when editing in vscode.

### ISSUE THREAD

**Issue by lequangphu** [quarto-dev/quarto-cli#7167]
### Bug description

When editing in vscode, the option .column-screen-inset-left is duplicated while .column-screen-inset-right doesn't appear.
![Screenshot 2023-10-07 at 17 59 00](https://github.com/quarto-dev/quarto-cli/assets/33654804/3efa146b-6879-45d8-b521-82c1a6715380)

### Your environment

- IDE: VSCode 1.81.1
- MacOS Sonoma 14.0

**Comment by jjallaire** [comment]
Thanks! This is fixed in v1.4 (https://github.com/quarto-dev/quarto-cli/commit/dd031b3f6b5f973d7dc07929ad52258585b95d49)
