### ISSUE TITLE
iframe not properly rendered with self-contained

### ISSUE THREAD

**Issue by fyemath** [quarto-dev/quarto-cli#718]
I tried to create reveal slides with embedded webpage and noticed that the iframe was not rendered properly.
Here is a MWE:
`````
---
title: Testing Self-contained for iframe
format: 
  revealjs:
    self-contained: true
---

## A slide that contains an iframe

Iframe doesn't seem work properly with self-contained.

<iframe src="https://quarto.org/" title="https://quarto.org/" width="960" height="500"></iframe>

`````
The output:
![image](https://user-images.githubusercontent.com/8799996/164865528-b35df479-c026-4c42-ad7e-3d90bb752f72.png)

Any suggestion on how to handle this?

**Comment by fyemath** [comment]
Just found a solution. Using `knitr::include_url` as follows works.
````
```{r}
#| echo: false
knitr::include_url({"https://quarto.org/"})
```
````

**Comment by jjallaire** [comment]
Note that you can also do this by applying the `data-external=1` attribute to the iframe:

```html
<iframe src="https://quarto.org/" title="https://quarto.org/" width="960" height="500" data-external="1"></iframe>
```

**Comment by fyemath** [comment]
> Note that you can also do this by applying the `data-external=1` attribute to the iframe:
> 
> ```
> <iframe src="https://quarto.org/" title="https://quarto.org/" width="960" height="500" data-external="1"></iframe>
> ```

Great! It works! Thank you!

**Comment by gadepallivs** [comment]
I'm adding an iframe, output of `glimma` which is a wrapped HTML widget. When I include output.html one is Tab1, it works. However, the output.hmtl is tab2 does not display anything.  

```.qmd

::: panel-tabset
## Tab1

 ```{r}
 #| echo: false
 knitr::include_url({"results/output1.html"})

## Tab2

```{r}
#| echo: false
knitr::include_url({"results/output2.html"})
```
