### ISSUE TITLE
Can HTML documents only be opened with Google?

### ISSUE THREAD

**Issue by lxj4321** [quarto-dev/quarto-cli#719]
Can HTML documents, book HTML documents only be opened with Google?  When opened with Ie or Firefox, the page format changes.

**Comment by dragonstyle** [comment]
No, it should be viewable in most modern browsers (including Firefox). If you can provide some details about the differences that you're seeing we'll take a closer look at the issue.

**Comment by lxj4321** [comment]
@dragonstyle 
Firefox：
![1](https://user-images.githubusercontent.com/19354503/164952582-42184daf-0b06-4c28-9c52-860b68fbc014.PNG)
IE：
![image](https://user-images.githubusercontent.com/19354503/164952471-cc74a929-95b1-482d-b569-e2a8dcb855d4.png)
Google：
![1650765445(1)](https://user-images.githubusercontent.com/19354503/164952524-6255a317-981d-4666-ab1a-f80e5b221d1a.png)

**Comment by dragonstyle** [comment]
I'm not sure the details around versions and so on. I just tried a simple book project (and also switched the `title-banner-style` to enabled and everything appeared to be fine in Edge, Firefox, and Chrome (and Safari on MacOS). 

In the case of IE, I am able to reproduce the layout issues that you report. From a cursory look, this boils down to our use of CSS Grid. Internet Explorer did eventually support CSS grid, but using special IE only syntax which we currently aren't emitting (hence the page layout not really working). I will leave this open to take a look at when I can get to it. 

If you have additional detail on the issue regarding Firefox (platform, OS, project that exhibits it), that would help me pin down any issue there.

**Comment by jjallaire** [comment]
@dragonstyle I think there are many other cases where Quarto HTML/CSS/JS won't work in IE so it's not even worth making use of their Grid equivalents (b/c something else will go wrong after that).

**Comment by lxj4321** [comment]
@dragonstyle Thanks for your answer, Firefox was tested on 51.0 (32-bit);  It works fine after updating the latest version:(99.0.1 (64-bit)).

**Comment by jmbuhr** [comment]
I think you are probably fine not trying to support internet explorer, given this:
![image](https://user-images.githubusercontent.com/17450586/165297283-3104945e-e77d-40ae-8145-3846f1e4b313.png)
(https://support.microsoft.com/en-us/windows/internet-explorer-downloads-d49e1f0d-571c-9a7b-d97e-be248806ca70)

**Comment by dragonstyle** [comment]
Just have to hold on a couple more months :)
