### ISSUE TITLE
Quarto ReavelJS presentation and shiny Picture not showing 

### ISSUE THREAD

**Issue by alsonicr** [quarto-dev/quarto-cli#7194]
### Bug description

I was working on a presentation and notice that picture were not displayed when R shiny server was up.

### Steps to reproduce

````qmd
---
title: "Not working exemple"
format:
  revealjs: 
    slide-number: true
server: shiny

---


## Hello world 


```{r}

sliderInput("value", "mean", 
            min = 0, max = 10, value = 5)


plotOutput("distPlot")
```

```{r}
#| eval: true
#| context: server

library(ggplot2)

# input = list('value'=3)

output$distPlot <- renderPlot({
    val <- rnorm(50, mean= input$value)
    dat <- data.frame(val)

    ggplot(dat, aes(x=val)) + geom_density()

})


```

## Picture not workind

![](images.jpeg)
````

### Expected behavior

Normally the picture should be display 

### Actual behavior

Figure is not display 

### Your environment

IDE RStudio
2023.06.2 Build 561

Ubuntu 22.04.3 LTS

### Quarto check output

````
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.353
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /bin/python3
      Jupyter: 5.3.1
      Kernels: python3

(-) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK
````

**Comment by mcanouil** [comment]
Thanks for the report!
Unfortunately, it is not currently legible, could you properly format your post and use code block for `quarto check` output?

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by alsonicr** [comment]
I follow your recommendations

**Comment by dragonstyle** [comment]
I was able to reproduce this issue - ty we'll take a look!

**Comment by JFViola** [comment]
Hi everyone, 
i ran into the same problem.

Figures do not show up: 
![grafik](https://github.com/quarto-dev/quarto-cli/assets/33548469/5f1cb4d6-f8f0-4d89-b70f-c8b9e42a1468)

- regardless of relative or full path
- regardless of filetype (tested png,gif,bmp)
- regardless of added manually or in visual editor
- figure previews work (with and without visual editor)
- biglogo: and logo: have the same issue
- plots of code chunks plot properly (as well as interactive elements)

I thought that i was just stupid, so i am somehow relieved that more people have this problem.
However, I have 4 days left before i need to abort and go back to another format with my presentation to meet my deadline..

I hope that you can fix it easily or someone has a neat workaround.

Cheers

**Comment by jjallaire** [comment]
For R Shiny interactive documents you need to put static images in a dedicates `images/` directory. Docs here: https://quarto.org/docs/interactive/shiny/resources.html#asset-resources
