### ISSUE TITLE
Table subcaptions don't display in newer pre-release versions

### ISSUE THREAD

**Issue by tegorman13** [quarto-dev/quarto-cli#7197]
### Bug description

Table subcaptions don't display in newer pre-release versions. 
- does work properly in older versions. 

### Steps to reproduce
````qmd
---
title: "Table subcaption issue"
format: 
  html: default
  pdf: default
---


```{r}
#| label: tbl-example
#| tbl-cap: "Example"
#| tbl-subcap: 
#|   - "Cars"
#|   - "Pressure"
#| echo: fenced

library(knitr)
kable(head(cars))
kable(head(pressure))
```
````

### Expected behavior

Table sub-cations inserted over each table when rendering to html or pd
![Screenshot 2023-10-11 at 6 12 31 AM](https://github.com/quarto-dev/quarto-cli/assets/77428165/3ab79a92-fc8a-4f3c-932a-64c2be9263c5)

### Actual behavior

No sub-captions displayed for either html or pdf - only primary table caption. 

sub-captions do display correctly when testing identical code using an older version of Quarto (1.3458). 
![Screenshot 2023-10-11 at 6 11 15 AM](https://github.com/quarto-dev/quarto-cli/assets/77428165/28e95ff4-6861-4275-a17a-b7b27e451d72)

### Your environment

RStudio 2023.09.0+463
Mac OS Ventura 13.6

### Quarto check output

Quarto 1.4.415
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.415
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking basic markdown render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Thanks for the report!

Could you make your example ready to use and possibly include the format if the behaviour is only for one format?
You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by tegorman13** [comment]
> Thanks for the report!
> 
> Could you make your example ready to use and possibly include the format if the behaviour is only for one format? You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four `` ```` ``).
> 
> ```
> ````qmd
> ---
> title: "Reproducible Quarto Document"
> format: html
> ---
> 
> This is a reproducible Quarto document using `format: html`.
> It is written in Markdown and contains embedded R code.
> When you run the code, it will produce a plot.
> 
> ```{r}
> plot(cars)
> ```
> 
> The end.
> ````
> ```

Updated my original post to make the example ready to use, and to indicate which formats are affected.

**Comment by cscheid** [comment]
This is definitely a regression we're going to fix right away.

In the meantime, you can use the following syntax:

````
---
title: "Table subcaption issue"
format: html
---

```{r}
#| echo: false
library(knitr)
```

::: {#tbl-example}

```{r}
#| label: tbl-cars
#| tbl-cap: "Cars"
#| echo: false
kable(head(cars))
```

```{r}
#| label: tbl-pressure
#| tbl-cap: "Pressure"
#| echo: false
kable(head(cars))
```

Example

:::

````

**Comment by cderv** [comment]
@cscheid Just a heads up that it seems `echo: fenced` is specifically messing with this. #7277 does not solve all the issue because this 
`````markdown
---
title: "Table subcaption issue"
format: 
  html: default
  pdf: default
---


```{r}
#| label: tbl-example
#| tbl-cap: "Example"
#| tbl-subcap: 
#|   - "Cars"
#|   - "Pressure"
#| echo: fenced

library(knitr)
kable(head(cars))
kable(head(pressure))
```

````

Still produce no sub caption for table 2
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/77d470f6-7472-4631-80ba-f8d5b7736340)

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/b294d373-fd13-4745-ad71-d379dce64fe4)


This is due to the fact that source code is one code block, and output tables are in one div only I guess. See intermediary .md

<details>
<summary>Intermediary md</summary>

````markdown
::: {#tbl-example .cell tbl-cap='Example' tbl-subcap='["Cars","Pressure"]'}

````{.cell-code}
```{{r}}
#| label: tbl-example
#| tbl-cap: "Example"
#| tbl-subcap:
#|   - "Cars"
#|   - "Pressure"

library(knitr)
kable(head(cars))
kable(head(pressure))
```
````

::: {.cell-output-display}


| speed| dist|
|-----:|----:|
|     4|    2|
|     4|   10|
|     7|    4|
|     7|   22|
|     8|   16|
|     9|   10|



| temperature| pressure|
|-----------:|--------:|
|           0|   0.0002|
|          20|   0.0012|
|          40|   0.0060|
|          60|   0.0300|
|          80|   0.0900|
|         100|   0.2700|


:::
:::
````

While without echo fenced

````markdown
::: {#tbl-example .cell tbl-cap='Example' tbl-subcap='["Cars","Pressure"]'}

```{.r .cell-code}
library(knitr)
kable(head(cars))
```

::: {.cell-output-display}


| speed| dist|
|-----:|----:|
|     4|    2|
|     4|   10|
|     7|    4|
|     7|   22|
|     8|   16|
|     9|   10|


:::

```{.r .cell-code}
kable(head(pressure))
```

::: {.cell-output-display}


| temperature| pressure|
|-----------:|--------:|
|           0|   0.0002|
|          20|   0.0012|
|          40|   0.0060|
|          60|   0.0300|
|          80|   0.0900|
|         100|   0.2700|


:::
:::

````


</details>

It seems we need to modify our `echo: fenced` md output for expected md output, in order to process correctly. 
Maybe it is better to open another issue for this ?

**Comment by cscheid** [comment]
Good catch. The easiest is probably simply to not walk with cell-output-display divs before trying to find the tables.

**Comment by cscheid** [comment]
@cderv https://github.com/quarto-dev/quarto-cli/pull/7277/files#diff-b4c5a1eefab8a1e59169ee2e08d8776a4aa9282640795e27f011322a9caf9144R582-R584 I added the cell-output-display check there, but I didn't know if it was necessary. It's probably actually just wrong.
