### ISSUE TITLE
What should a file within a project look like?

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#72]
In looking through the existing docs (cc @pommevilla @rich-iannone), I realized I never see an example of what goes inside a `.qmd`, `.Rmd`, etc. file within a chapter. I know the option to have a shared YAML, but I assumed that meant an individual item's YAML would override that. 

In an existing Quarto book project, we have several chapters, with this YAML at the top as an example:

```
---
title: Importing data for the first time
---

## Introduction
some text here
```

When I render this, the level 2 header (`## Introduction`) is the chapter title. I would expect the `title` in the YAML to show up though instead. To get this outcome, we had to do:

```
---
title: Importing data for the first time
---

# Importing data for the first time

## Introduction
some text here
```

But even more surprising, if I have a bunch of text at the top then a header down below:

```
---
title: Importing data for the first time
---

lines and lines of text here
lines and lines of text here
lines and lines of text here
lines and lines of text here
lines and lines of text here

## Introduction

more text here
```

The same thing happens- the first `## Introduction` header becomes the chapter title, and the placeholder between `lines and lines of text here` and `more text here` is gone. This appears to happen with the first header I provide, regardless of the level header (I tested up to level 5), and regardless of placement (as in, it could be paragraphs into the chapter and still get transported up to the chapter title).

1. Are project files intended to have their own YAML, and if so, which options are valid there? 
2. If I'm not supposed to put the title in the YAML, will the chapter title always be the first header (regardless of level and placement)?

**Comment by jjallaire** [comment]
Currently project files in books are supposed to use an `#`  rather than `title` in YAML (similar to bookdown). That said, we are just about to change this so you can use `title` instead.

**Comment by apreshill** [comment]
Ah perfect, per .Rmd YAMLs are 👍  I thought I remembered being able to set knitr chunk options in the YAML as well- will those be enabled per file?

**Comment by jjallaire** [comment]
Yes, those will work per-file
