### ISSUE TITLE
Numbered list loses numeration when there are divs inside items

### ISSUE THREAD

**Issue by finkelshtein** [quarto-dev/quarto-cli#7209]
### Bug description

Numbered list with divs inside items displays correctly in htmlformat, however, in ipynb - all items have the number 1.

### Steps to reproduce

````qmd

---
title: "Test"
format: 
    html: default
    ipynb: 
        output-file: TestSaved
---

1. Calculate $2+2$.

::: {.solution}
$2+2=4$
:::

2. Calculate $3+3$.

::: {.solution}
$3+3=6$
:::


````

### Expected behavior

The html version is as expected. 

![image](https://github.com/quarto-dev/quarto-cli/assets/35048241/40e93dba-cbfe-4ec4-846b-ae337b83d2a3)

### Actual behavior

The saved ipynb file, however, looks as follows:
![image](https://github.com/quarto-dev/quarto-cli/assets/35048241/15242b9b-d29d-40be-a88c-b32c81a19746)

### Your environment

- VS Code 1.83.1
- Quarto 1.4.376

**Comment by cscheid** [comment]
This isn't a bug; that's the way an enumerated list goes. What's happening is that your solution block needs to be inside the itemized list. The way you have it, you're accidentally creating multiple lists.

**Comment by cscheid** [comment]
This is the right way to do it:

````
---
title: "Test"
format: 
    html: default
    ipynb: 
        output-file: TestSaved
---

1. Calculate $2+2$.
   
   ::: {.solution}
   $2+2=4$
   :::

2. Calculate $3+3$.
   
   ::: {.solution}
   $3+3=6$
   :::
````
