### ISSUE TITLE
Strange behavior of code chunks on quarto website

### ISSUE THREAD

**Issue by hail2thief** [quarto-dev/quarto-cli#7225]
### Bug description

I'm running into some strange behavior on my Quarto site where the code chunks are not displaying correctly (dark, nearly invisible text), see an example here: https://quantpol.juanftellez.com/example/03-example. I can see that the problem is with the html files themselves within the generated `site/` folder. 

I *suspect* this has something to do with having recently set `freeze` to "on", but I'm not 100% sure. I'm still confused by what `freeze` is doing, exactly. RStudio still seems to render every `qmd` file regardless of whether its set to on or off. For reference, to make changes to my site I work within RStudio, make changes, render the site, and then use `quarto publish` to publish to Netlify. 

Here is a link to the code repository: https://github.com/hail2thief/quantpol_quarto

Any help would be greatly appreciated!

### Your environment

platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          2.2                         
year           2022                        
month          10                          
day            31                          
svn rev        83211                       
language       R                           
version.string R version 4.2.2 (2022-10-31)
nickname       Innocent and Trusting  

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

(/) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Thanks for the report, but we need a reproducible example to go on.

> Here is a link to the code repository: https://github.com/hail2thief/quantpol_quarto

That link doesn't work. My guess is it's a private repo.

**Comment by hail2thief** [comment]
Thanks for looking, here is the source code: https://github.com/hail2thief/quantpol_quarto

**Comment by cscheid** [comment]
do you have a smaller example? It's not very practical to try and figure out what's happening here.

**Comment by hail2thief** [comment]
That'd probably be a tall order. I use Quarto a lot for work and have smaller sites than the one linked and haven't run into this issue. To reverse engineer a smaller example that still produces the weird code chunks I'd probably have to identify what was wrong in the first place 😄 . But I totally get on your end that help is impossible without a reproducible example. Just thought I'd ask in case it might be something obvious to others. I'll just close this. Appreciate you taking the time!
