### ISSUE TITLE
Raw LaTeX tables with cross-references no longer render

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#7236]
### Bug description

In Quarto 1.3, it was possible to use Quarto's cross references with raw LaTeX tables by including `{#tbl-id}` in the table caption ([see here](https://github.com/quarto-dev/quarto-cli/issues/5161#issuecomment-1507043400)). In Quarto 1.4.x, this doesn't work anymore.

### Steps to reproduce

This document would render fine in 1.3:

````qmd
---
title: "Raw TeX cross referencing"
format: 
  pdf: default
---

See @tbl-tex.

\begin{table}[]
\caption{Some letters with LaTeX {#tbl-tex}}
\begin{tabular}{@{}lll@{}}
\toprule
Column 1 & Column 2 & Column 3 \\ \midrule
A        & B        & C        \\
D        & E        & F        \\
G        & H        & I        \\ \bottomrule
\end{tabular}
\end{table}
````

### Expected behavior

That document would render into this (lol horribly placed table)

<img width="677" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/1edb1a0a-d8c7-4da1-a3fa-aa0396adc1d8">

### Actual behavior

Quarto 1.4 produces this warning before invoking `xelatex`:

```
WARNING (/Applications/quarto/share/filters/main.lua:10047) Unable to resolve crossref @tbl-tex
```

And then after starting `xelatex` and showing the dreaded `updating tlmgr` message, it produces this error:

```
ERROR: 
compilation failed- error
Illegal parameter number in definition of \GetTitleStringResult.
<to be read again> 
                   t
l.147 \caption{Some letters with LaTeX {#tbl-tex}}
```

### Your environment

- IDE: Version 2023.09.0+463
- OS: macOS Sonoma 14.0

### Quarto check output

```
Quarto 1.4.424
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.424
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/andrew/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Thanks for the report. There's a bit of a regression that we will fix right away, but that's not the entire situation. Some of this LaTeX code will unfortunately have to change a bit.

Specifically, the problem here is that `table` is a float environment, and Quarto needs to take control of those, and emit that code itself.

**Comment by cscheid** [comment]
Quick workaround first. If you need this to work right away, the following will get you back on track:

````
---
title: "Raw TeX cross referencing"
format: 
  pdf: default
---

See @tbl-tex.

::: {#tbl-tex}

```{=latex}
\begin{tabular}{@{}lll@{}}
\toprule
Column 1 & Column 2 & Column 3 \\ \midrule
A        & B        & C        \\
D        & E        & F        \\
G        & H        & I        \\ \bottomrule
\end{tabular}
```

Some letters with LaTeX
:::
````

Note, for future reference, that we expect latex raw blocks to be surrounded by `` ```{=latex} `` and `` ``` ``, so that the entire block is recognized as a single node in the Pandoc AST.

I'm going to fix the regression so that the following syntax works:

````
---
title: "Raw TeX cross referencing"
format: 
  pdf: default
---

See @tbl-tex.

```{=latex}
\begin{tabular}{@{}lll@{}}
\caption{Some letters with LaTeX {#tbl-tex}}
\toprule
Column 1 & Column 2 & Column 3 \\ \midrule
A        & B        & C        \\
D        & E        & F        \\
G        & H        & I        \\ \bottomrule
\end{tabular}
```
````

Note the rawblock syntax, and note the lack of `\begin{table}` and `\end{table}`). I'll take a shot at restoring the previous syntax, but unfortunately I cannot make promises there.

**Comment by cscheid** [comment]
All the following raw block syntaxes should be respected once the PR lands:

````
---
title: "Raw TeX cross referencing"
format: 
  pdf: default
---

See @tbl-tex, @tbl-2, @tbl-3.

```{=latex}
\begin{tabular}{@{}lll@{}}
\label{tbl-tex}
\caption{Some letters with LaTeX}
\toprule
Column 1 & Column 2 & Column 3 \\ \midrule
A        & B        & C        \\
D        & E        & F        \\
G        & H        & I        \\ \bottomrule
\end{tabular}
```

```{=latex}
\begin{tabular}{@{}lll@{}}
\caption{Some letters with LaTeX {#tbl-2}}
\toprule
Column 1 & Column 2 & Column 3 \\ \midrule
A        & B        & C        \\
D        & E        & F        \\
G        & H        & I        \\ \bottomrule
\end{tabular}
```

As best effort, we try to remove `\begin{table}` as well:

```{=latex}
\begin{table}
\begin{tabular}{@{}lll@{}}
\caption{Some letters with LaTeX {#tbl-3}}
\toprule
Column 1 & Column 2 & Column 3 \\ \midrule
A        & B        & C        \\
D        & E        & F        \\
G        & H        & I        \\ \bottomrule
\end{tabular}
\end{table}
```
````

**Comment by andrewheiss** [comment]
This may have re-regressed? This doesn't work with 1.4.504:

````qmd
---
title: "Raw TeX cross referencing"
format: 
  pdf: default
---

See @tbl-tex:

```{=latex}
\begin{tabular}{@{}lll@{}}
\label{tbl-tex}
\caption{Some letters with LaTeX}
\toprule
Column 1 & Column 2 & Column 3 \\ \midrule
A        & B        & C        \\
D        & E        & F        \\
G        & H        & I        \\ \bottomrule
\end{tabular}
```
````

It causes this error:

```
Error running filter /Applications/quarto/share/filters/main.lua:
Inline, list of Inlines, or string expected, got nil
	while retrieving function argument inlines
	while retrieving arguments for function Inlines
stack traceback:
	/Applications/quarto/share/filters/main.lua:10697: in upvalue 'index_caption'
	/Applications/quarto/share/filters/main.lua:10784: in function 'writeFullIndex'
	/Applications/quarto/share/filters/main.lua:10685: in field 'Pandoc'
	/Applications/quarto/share/filters/main.lua:216: in function 'run_emulated_filter'
	/Applications/quarto/share/filters/main.lua:917: in local 'callback'
	/Applications/quarto/share/filters/main.lua:932: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:968: in function </Applications/quarto/share/filters/main.lua:965>
```

**Comment by andrewheiss** [comment]
In 1.4.504, I actually can't seem to run anything in this test https://github.com/quarto-dev/quarto-cli/blob/cfebb28fedb4ddd530bdcd7f4d7ffd782a5a6509/tests/docs/smoke-all/2023/10/16/7236.qmd —it leads to the same error:

```
Error running filter /Applications/quarto/share/filters/main.lua:
Inline, list of Inlines, or string expected, got nil
	while retrieving function argument inlines
	while retrieving arguments for function Inlines
stack traceback:
	/Applications/quarto/share/filters/main.lua:10697: in upvalue 'index_caption'
	/Applications/quarto/share/filters/main.lua:10784: in function 'writeFullIndex'
	/Applications/quarto/share/filters/main.lua:10685: in field 'Pandoc'
	/Applications/quarto/share/filters/main.lua:216: in function 'run_emulated_filter'
	/Applications/quarto/share/filters/main.lua:917: in local 'callback'
	/Applications/quarto/share/filters/main.lua:932: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:968: in function </Applications/quarto/share/filters/main.lua:965>
```

**Comment by cderv** [comment]
> In 1.4.504, I actually can't seem to run anything in this test [cfebb28/tests/docs/smoke-all/2023/10/16/7236.qmd](https://github.com/quarto-dev/quarto-cli/blob/cfebb28fedb4ddd530bdcd7f4d7ffd782a5a6509/tests/docs/smoke-all/2023/10/16/7236.qmd) —it leads to the same error:

Our test passes though... 😓 🤔 
https://github.com/quarto-dev/quarto-cli/actions/runs/6906144301/job/18790515928#step:26:155

**Comment by cscheid** [comment]
That error makes me suspect a stale `.quarto` directory somewhere.

**Comment by cderv** [comment]
Yes I can verify that this happens only when the document is inside a quarto project, even of `type: default`

**Comment by cscheid** [comment]
I actually can repro this myself outside of a project, so it's something else.

We should never crash. With that said, I'll reiterate my previous "using raw latex for \label{}s etc is fraught, and you should really really consider if that's what you need to do" stance.

**Comment by cderv** [comment]
> We should never crash.

Agree with that - especially I don't expect a rendering for a same .qmd working when outside a project context and not working inside a project context, especially with default type project.

**Comment by andrewheiss** [comment]
This error does indeed happen inside a quarto project

---

haha I'm all for avoiding using raw latex :)

This was just one of my attempts to try sticking a longtable (https://github.com/quarto-dev/quarto-cli/issues/7604#issuecomment-1815184668) in the document, but then I ran into this weird issue 🤷‍♂️

**Comment by cscheid** [comment]
> This was just one of my attempts to try sticking a longtable (https://github.com/quarto-dev/quarto-cli/issues/7604#issuecomment-1815184668) in the document, but then I ran into this weird issue 🤷‍♂️

Andrew can you please not use our software in a completely reasonable manner? :lolsob:

**Comment by cscheid** [comment]
This is a "fun" one that happens more broadly than we might expect. What's going on is that since we now have the ability to catch and treat raw latex blocks as real cross-referenceable elements inside Quarto, the caption content can itself be entirely a raw block. That confuses `index_caption` in `src/resources/filters/crossref/index.lua`, and that file only comes up in a project setting.

In 1.5 we're probably going to do away with the distinction between project and non-project renders entirely, which should make this class of bugs go away.

(PR incoming.)

**Comment by likanzhan** [comment]
Is this problem being resolve in `1.5.57` ?
It seems I still experience the same thing.

**Comment by mcanouil** [comment]
@likanzhan please open a GutHub Discussion if you are not sure there is still a bug. You can reference this issue.
Also note, that we need a fully reproducible example to work with.
