### ISSUE TITLE
Fig captions not rendering in pdf output

### ISSUE THREAD

**Issue by jazzbuck** [quarto-dev/quarto-cli#724]
Thanks for all the work on quarto - I've been really enjoying the flow of it.

I'm using quarto to render my jupyter notebook to pdf file.  

I expect to see standard behaviour of cross-referencing between markdown cells to cells containing my tables. This works when rendering to html, but fails when rendering to pdf.

Example cells:

Cell 1:
```markdown
In @tbl-summary-gen we see...
```

```python
#| echo: false
#| label: tbl-summary-gen
#| tbl-cap: "summary of hypothesis generation datasets"

df = pd.DataFrame(
    {
    "a":["2,3,4,5"],
    "b":["3,4,5,6"],
    }
)
df
```

**Comment by jjallaire** [comment]
The problem is likely that when you executed the notebook in Jupyter (or VS Code) that HTML output (rather than markdown) was produced. Then, when rendering to PDF you get LaTeX attempting to process the HTML. If you render with execution like this:

```bash
quarto render notebook.ipynb --to pdf --execute
```

Then you'll get the expected output.
