### ISSUE TITLE
Render failing when requiring documentclass to be downloaded

### ISSUE THREAD

**Issue by tjisousa** [quarto-dev/quarto-cli#725]
Dear all,

I can't render any document using the following configuration:

```
project:
  title: 'thesis'

format:
  pdf:
    documentclass: thesis
```

The problem seems related to the download of the `.cls` files required. I also tried to download the `classithesis` and `cleanthesis` document class and got the same problem.

I get the following error:

```
❯ quarto render
pandoc
  to: latex
  output-file: thesis.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  filters:
    - crossref

metadata
  block-headings: true
  documentclass: thesis
  title: thesis

runnning xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages
finding package for thesis.cls

compilation failed- no matching packages
LaTeX Error: File `thesis.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name:
! Emergency stop.
<read *>

l.8 \usepackage
               {amsmath,amssymb}^^M
```

I tested on two different machines using on one TinyTex while on the other, using MacTex.

**Comment by cderv** [comment]
Hi @tjisousa 

When setting `documentclass`, if the `.cls` is not found on the system, there will be a try to download a CTAN package that contains that file. However, in this case `thesis.cls` is not found in any package on CTAN. 

Where is the `thesis` document class coming from ? Is this a local `.cls` file ? Are they available somewhere not on CTAN ? 

Thanks

**Comment by tjisousa** [comment]
> Hi @tjisousa 
> 
> 
> 
> When setting `documentclass`, if the `.cls` is not found on the system, there will be a try to download a CTAN package that contains that file. However, in this case `thesis.cls` is not found in any package on CTAN. 
> 
> 
> 
> Where is the `thesis` document class coming from ? Is this a local `.cls` file ? Are they available somewhere not on CTAN ? 
> 
> 
> 
> Thanks
> 
> 

Hi @cderv,

I was expecting it would be able to find the following: [https://ctan.org/pkg/thesis](https://ctan.org/pkg/thesis)

Additionally, I added the manually and did not work.

**Comment by cderv** [comment]
> I was expecting it would be able to find the following: [ctan.org/pkg/thesis](https://ctan.org/pkg/thesis)

Indeed, if this is on CTAN it should find it 🤔 But did you manage to install this manually ? I can't on my side. 
````
❯ tlmgr install thesis
tlmgr.pl: package repository https://ctan.crest.fr/tex-archive/systems/texlive/tlnet (verified)
tlmgr.pl install: package thesis not present in repository.
tlmgr.pl: action install returned an error; continuing.
tlmgr.pl: An error has occurred. See above messages. Exiting.
````

I wonder if this is because it is available only for MikTeX and not TeX Live
![image](https://user-images.githubusercontent.com/6791940/165042339-11c87061-128a-40b6-91d5-860c3c7dc949.png)

If this is not downloadable using `tlmgr install`, then Quarto won't be able to auto download `thesis.cls` if not available

However, if you download locally using curl or any other tools
````
curl -O http://mirrors.ctan.org/macros/latex/contrib/thesis/thesis.cls
````

You may be able to use it after. This render without error for me 
````markdown
---
title: test
format: 
  pdf:
    documentclass: thesis
---

# Hello

World 
````

You may need to download other file too maybe from the archive https://ctan.org/tex-archive/macros/latex/contrib/thesis

**Comment by tjisousa** [comment]
@cderv So far, thank you for the help!

I managed to render following your instructions. However, it seems to me that if a package does not have a `.cls` file, it will not work. For example, if I try with [classicthesis](https://ctan.org/pkg/classicthesis), it does not work. 

Even if we install with `tlmgr install classicthesis`, quarto will try to download the `.cls` from the package, which does not exist.

Is there a workaround ?

**Comment by cderv** [comment]
I suggest you read the documentation of the CTAN package you are trying to use. For [`classicthesis`](https://ctan.org/pkg/classicthesis), you can see in their template and docs that it is not a class file but a package file (`.sty`), that should be loaded using `\usepackage{}`, or using there `[classicthesis-config.tex](https://bitbucket.org/amiede/classicthesis/src/master/classicthesis-config.tex)` file. You can look at the source in https://bitbucket.org/amiede/classicthesis

That is why `documentclas: classicthesis` won't work. There is no Quarto issue here, just how to correctly use CTAN package for your usage. Once you understand what you should do to use a package, then with Quarto you can customize some part of the template if needed (specically in-header to load some packages for example) : https://quarto.org/docs/output-formats/pdf-basics.html#latex-includes

Hope it helps

**Comment by tjisousa** [comment]
@cderv I understood now. Thank you for all the help!
