### ISSUE TITLE
figure/table environment should be removed when using `layout`/`.columns`

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#7262]
The following will work on HTML based format, but will fail in LaTeX, because figure/table environment cannot be inside minipage.

````qmd
---
format:
  pdf: default
  html: default
execute:
  echo: false
---

::: {layout-ncol="2" layout-valign="bottom"}

```{r}
#| label: fig-example
#| fig-cap: Figure caption
plot(cars)
```

```{r}
#| label: tbl-example
#| tbl-cap: Table caption
knitr::kable(head(cars))
```

:::
````

Note that simply removing the environment might not be enough when mixing tables and figures, because the two minipages are inside a figure environment.

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/7250

<div type='discussions-op-text'>

<sup>Originally posted by **MohamedaliS** October 17, 2023</sup>
### Description

Apologies in advnace if these are silly questions. I am new to Quarto and using it to compile a teaching material. I need some guidance with,

(1) Including citation for figures.
For example: If we use ![MSC GÜLSÜN [@tornEersteBezoekAan2019]](images/MSC.jpg){#fig-MSC-GÜLSÜN}, the citation also appears in the list of figures at the book index. How to avoid it. I need only the name of the figure and not the citation in the "List of Figures"
![image](https://github.com/quarto-dev/quarto-cli/assets/50414472/f3ba5f0f-85ae-487f-b574-242db7c26aff)

(2) The second issue is the same as  "https://stackoverflow.com/questions/72799825/side-by-side-caption-positions-of-figure-and-table". Using the codes chunk makes an additional caption. Looking for a solution to include a plot and table in a single chunk. 

```{r}
#| layout-ncol: 2
#| layout-valign: bottom
#| fig-cap: "A plot"
#| tbl-cap: "A table"

library(knitr)

# plot on the left
plot(cars)

# table on the right
kable(head(cars))
```

Thanks
</div>

**Comment by jchiquet** [comment]
Dont know (but I thing it is) if it is related, but I was about to open an Issue for a conflict between `kable_styling` and the Quarto table labeling . Compilation fails in PDF (not HTML) because of a double table environment (one included by quarto, the other by kable)

```
---
title: "failing table"
format: 
  html: default
  pdf: default
---

Works: 

```{r}
library(kableExtra)
kable(head(cars)) %>% kable_styling()
```

Doesn't work

```{r}
#| label: tbl-label1

library(kableExtra)
kable(head(cars)) %>% kable_styling()
```

```
