### ISSUE TITLE
Unable to use fig-scap in custom layout figures in PDF latex

### ISSUE THREAD

**Issue by Minh-AnhHuynh** [quarto-dev/quarto-cli#7269]
Currently the fig-scap parameter for short captions in the list of figures is working as expected:

> ```
> ![This is the long R logo caption.](R_logo.png){#fig-R-short-cap fig-scap="R logo"}
> ```
> 
> It works out of the box.
> 
> _Originally posted by @cscheid in https://github.com/quarto-dev/quarto-cli/issues/4776#issuecomment-1465239714_

However when used inside custom layout, it seems none of the parameters such as fig-scap and width function at all. Cross references do work however.

Here is a minimal reproductible example:

```
---
title: Layout title
format: pdf

---

# Layout with 3 figures, 2 in a row and 1 in a column.

\listoffigures

This is @fig-logo-1, @fig-logo-2, @fig-logo-3 and @fig-logo-standalone.

::: {layout="[[55, -5, 55], [100]]"}
![**logo 1**](r_logo.png){#fig-logo-1 fig-scap="short logo 1"}

![**logo 2**](r_logo.png){#fig-logo-2 fig-scap="short logo 2"}

![**logo 3**](r_logo.png){#fig-logo-3 width="50%" fig-scap="short logo 3"}

:::

![**logo 3**](r_logo.png){#fig-logo-standalone width="50%" fig-scap="short logo 3"}

```
https://user-images.githubusercontent.com/96783020/276311256-80f702a1-bf98-4084-a769-6ab0c67beeae.png

I would like ideally to be able to use the provided quarto syntax to generate my custom layout with short captions and width without resorting to more latex again.

**Comment by cscheid** [comment]
I'm not sure we can support this, unfortunately.

fig-scap exists for the captions in "lists of figure", etc, and I'm not sure how this could be well supported for subfigures. Can you show a pure latex example of what you're hoping to achieve?

**Comment by cderv** [comment]
@cscheid I believe here subfigures are not involved. This is just about the layout option that create a layout in LaTeX with `minipage`. 

LaTeX produced should be 
````latex
\caption[short capton]{\label{fig-id}caption}
```` 

`fig-scap` is lost when images are inside the layout div. Without you will have this 
```latex
\caption[short logo 1]{\label{fig-logo-1}\textbf{logo 1}}
```
with the layout div you get
````latex
\caption{\label{fig-logo-1}\textbf{logo 1}}
````

so `fig-scap` is lost. This is with 1.3 by the way! 

Because I think 1.4 fix it as it produce the right LaTeX code 
````latex
\caption[short logo 1]{\label{fig-logo-1}\textbf{logo 1}}
````

but there is another issue 
* #7309 

So fixing #7309 should fix this one - I confirmed it by modifing the intermediate `.tex` as described in #7309 

Hope it helps

**Comment by cderv** [comment]
> I'm not sure how this could be well supported for subfigures.

Also about this, this is another issue IMO - possibly encompassed in this discussion: 
* https://github.com/quarto-dev/quarto-cli/issues/3498

Short caption for subfigures are well support through `\subcaption` command that we use. I explained in the linked issue

**Comment by cscheid** [comment]
The immediate problem in this issue is now resolved on `main`:

<img width="363" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/31885596-6988-4b9c-8a0a-83f203f112bf">

The `-scap` support for Float crossrefs in general will be solved in the other issue.
