### ISSUE TITLE
Quarto Pub 429 Error "Too Many Requests"

### ISSUE THREAD

**Issue by eteitelbaum** [quarto-dev/quarto-cli#7281]
### Bug description

I am getting this error when trying to publish to Quarto Pub

[✓] Creating quarto-pub document
ERROR: API Error: 429 - Too Many Requests

Stack trace:
    at QuartoPubClient.createSite (file:///Applications/quarto/bin/quarto.js:100984:23)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async file:///Applications/quarto/bin/quarto.js:98614:26
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:39042:16)
    at async handlePublish (file:///Applications/quarto/bin/quarto.js:98611:9)
    at async publishDocument (file:///Applications/quarto/bin/quarto.js:104927:38)
    at async publish6 (file:///Applications/quarto/bin/quarto.js:105019:132)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:104979:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:105011:13)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:104967:9)

### Steps to reproduce

It is a long revealjs slide show. Cannot share here.

### Expected behavior

Expected to publish to Quarto Pub.

### Actual behavior

Got Error instead.

### Quarto check output

Quarto 1.4.395
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.395
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.10
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/ejt/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
This is a server side issue:
-

**Comment by ezraschwartzMD** [comment]
Receiving the same issue.
I am able to publish my project under one quarto pub account (personal account). When I try to publish the same project under a different account (work account) I receive the "ERROR: API Error: 429 (Too Many Requests)" error. 

Thoughts? Help appreciated!

**Comment by mcanouil** [comment]
@ezraschwartzMD see <https://github.com/quarto-dev/quarto-cli/issues/7281#issuecomment-1770060609>.

**Comment by mcanouil** [comment]
The important information in all those thread and in my comment: "This is a server side issue".
As in all the other thread, when resolved, the issue will be closed with a comment.

**Comment by mcanouil** [comment]
The issue should be resolved, please let us know if not.
