### ISSUE TITLE
Support RCall.jl syntax highlighting

### ISSUE THREAD

**Issue by wetlandscapes** [quarto-dev/quarto-cli#729]
Hi,
I'm really loving the project! You all are killing it.

One feature I might suggest is syntax highlighting of RCall.jl code chunks of the form:

``` {julia}
using RCall

R"""
library(tidyverse)
df <- tibble(x = rnorm(10), y = runif(10))
#df %>%
#  ggplot() +
#  geom_point(aes(x, y))
"""
```

Which currently results in:

![image](https://user-images.githubusercontent.com/18599142/165144595-90f1c59e-122a-4a54-a6be-b207acea3f02.png)

That's fine, but becomes a bit difficult to read. However, in vscode I have an extension, which highlights R code in RCall, resulting in:

![image](https://user-images.githubusercontent.com/18599142/165144656-bea6d885-cc64-4ece-a40a-b79b69affef9.png)

The specific extension doing the highlighting is: https://github.com/haberdashPI/vscode-r-in-julia. Note that it seems to allow highlighting for all RCall.jl syntax, and not just the example I used.

Thanks!

**Comment by jjallaire** [comment]
Thanks for this! Unfortunately I don't think we have a way to do embedded highlighting _within_ embedded highlighting right now. Note that we register for embedded Julia highlighting here (https://github.com/quarto-dev/quarto-vscode/blob/main/package.json#L103) but there isn't a way to go further than that.

**Comment by wetlandscapes** [comment]
Ah, got it. Well thanks for at least considering it.

**Comment by jjallaire** [comment]
Hi there @wetlandscapes, posting back here because I'm giving a talk on Quarto at JuliaCon next month and was hoping to find some good examples of using Julia w/ Quarto. If you are able to share any of your own (or are aware of others) please LMK over on this discussion thread: https://github.com/quarto-dev/quarto-cli/discussions/1261. Thanks!

**Comment by wetlandscapes** [comment]
My journey with R and Julia in Quarto are just beginning, so I don't have any examples that are not contrived, but I will keep this issue in mind as I develop some projects I'm working on.
