### ISSUE TITLE
Mathematical content in chapter headings not always recognized

### ISSUE THREAD

**Issue by rstub** [quarto-dev/quarto-cli#73]
I am test-driving quarto by converting my old diploma thesis originally done in LaTeX to it.  I have found that math content in headings is sometimes not correctly displayed, e.g. https://rstub.github.io/diploma-thesis/period_efa.html:

* In the main text the math content is correctly shown in both the chapter and the section heading
* The math content in the section heading is also correctly shown in the on-page TOC
* The math content from the chapter heading and the title is shown in raw form in the main TOC and on the chapter navigation lins in the previous/next chapter

Anything I can do to fix this?

In addition, I have the impression that the math content in the chapter heading is breaking recognition of the chapter label. At least I don't see what is wrong with https://github.com/rstub/diploma-thesis/blob/main/period_efa.qmd#L7 and the label works once I remove the math content. However, references to section 2.1 with the same math content do work w/o problems. Any idea what is going on here? 

BTW, is there a way to retain the intermediate markdown files (after knitr/jupyter but before pandoc)? That would help me debugging stuff like this.

**Comment by jjallaire** [comment]
Thanks for reporting! We'll take a look at this soon. 

Note you can preserve intermediate markdown output with `keep-md`.

**Comment by dragonstyle** [comment]
This build:

https://github.com/quarto-dev/quarto-cli/releases/tag/v0.2.68

should contain changes that fix the issues with rendering math in titles, page navigation, and elsewhere. If you have a moment to take a look and let me know how things look to you, I'd appreciate it. Thanks for reporting this- it was a great bug to get fixed!

**Comment by dragonstyle** [comment]
Hmm... I do see an issue when I view the bibliography, but I think I may be missing the issue on the page you pointed to. Here is what I'm seeing...

![Screen Shot 2021-08-09 at 4 53 18 PM](https://user-images.githubusercontent.com/261654/128773074-d7220db4-5d7b-4986-990f-0a5b5ddea8c4.png)

I do see this issue on the bibliography page.... (I'll take a closer look at that one).

![Screen Shot 2021-08-09 at 4 54 25 PM](https://user-images.githubusercontent.com/261654/128773215-ecc119da-4a4f-4336-8e6f-858400bf174e.png)

**Comment by rstub** [comment]
I now see the same results as you. Looks like my browser did cache to aggressively. Thanks!

**Comment by rstub** [comment]
The issue in the references section has been solved by including the LaTeX abbreviations from `header.tex` also in `refernces.qmd`. Thanks @dragonstyle!
