### ISSUE TITLE
Quarto hangs on cell that can be executed through any other way

### ISSUE THREAD

**Issue by tpoisot** [quarto-dev/quarto-cli#7301]
### Bug description

This is a *strange* issue. I have a document that can run when I use "Quarto > Run all cells", or the keyboard shortcut within the cell, or the notebook generated by quarto itself. But for a reason that I do not understand, quarto chokes on one cell.

I have written an MRE, and the content of the cell is very important -- this happens when using a `heatmap` in Makie.jl. When using `quarto render --to html` (or `quarto preview`), the execution of this cell doesn't finish.

I let one run for a few hours just to be sure.

Even calling `jupyter nbconvert --execute --to=html` on the notebook that quarto generates works. The only way that doesn't work is when running quarto.

### Steps to reproduce

````qmd
---
title: "Untitled"
format: html
---

```{julia}
# import Pkg; Pkg.activate("."); Pkg.add("CairoMakie")
using CairoMakie
```


```{julia}
fig = Figure(; resolution=(500, 240))
ax = CairoMakie.Axis(fig[1,1]; aspect=DataAspect())
D = rand([1,2,3], (400, 200))
heatmap!(ax, D; colormap=[:red, :green, :blue])
hidedecorations!(ax)
current_figure()
```
````

### Expected behavior

It works

### Actual behavior

It doesn't

### Your environment

- IDE: VS Code
- Julia: 1.9.3
- OS: OpenSUSE Tumbleweed

~~~
Status `~/Test/Project.toml`
  [13f3f980] CairoMakie v0.10.11
~~~

### Quarto check output

```bash
Quarto 1.4.429
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.429
      Path: /home/tpoisot/opt/quarto-1.4.429/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/tpoisot/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/bin/python3
      Jupyter: 5.4.0
      Kernels: julia-1.9, python3, python3.11

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
What if you try to render the following:

```qmd
---
title: "Untitled"
format: html
jupyter: julia-1.9
---

Nothing to compute.
```

**Comment by cscheid** [comment]
Can you try the following:

- convert your qmd to a .ipynb with `quarto convert`
- run the following script with `python run_notebook.py input.ipynb output.ipynb`?

## `run_notebook.py`

```
#!/usr/bin/env python3

import nbformat
import sys
from nbclient import NotebookClient
import atexit

notebook_filename = sys.argv[1]
nb = nbformat.read(notebook_filename, as_version=4)
client = NotebookClient(nb, timeout=600, kernel_name='julia-1.9')
client.create_kernel_manager()
client.start_new_kernel()
client.start_new_kernel_client()
atexit.register(client._cleanup_kernel)

for index, cell in enumerate(client.nb.cells):
  if cell.cell_type == 'code':
    cell = client.execute_cell(
        cell = cell,
        cell_index = index)
    client.nb.cells[index] = cell
nbformat.write(client.nb, sys.argv[2])
```

**Comment by tpoisot** [comment]
Using the python version that ships with the Julia conda environment, the output notebook works (and has the correct results).

By splitting the code one instruction per cell, it looks like the blocking point is at `current_figure()` (which just shows the figure).

**Comment by cscheid** [comment]
> By splitting the code one instruction per cell, it looks like the blocking point is at current_figure() (which just shows the figure).

I imagine what's going on here is that the other programs you tried know to notify CairoMakie that it's running on a non-interactive setting.

**Comment by tpoisot** [comment]
> But, more concretely, you're also experiencing the hanging on a non-quarto setting. Then I think the issue here is with nbclient, and nothing we can truly fix on Quarto.

I am not -- this is running fine on everything *but* quarto.

**Comment by cscheid** [comment]
> By splitting the code one instruction per cell, it looks like the blocking point is at current_figure() (which just shows the figure).

I thought you were referring to the run_notebook.py script I shared, I apologize. So, you're confirming this executes properly through that script?

**Comment by tpoisot** [comment]
Yes -- using the script you provided, this runs. The figure renders and displays.

**Comment by cscheid** [comment]
The only thing I can imagine might be going on is a discrepancy between the environment that `python` is seeing and the one that quarto uses.

Can you check with `quarto check` and `python --version`?

**Comment by cscheid** [comment]
I've now installed Julia 1.9 and prerequisites on my machine, and your .qmd file renders fine for me:


````
quarto render 7301.qmd

Starting julia-1.9 kernel...Done

Executing '7301.ipynb'
  Cell 1/2: ''...Done
  Cell 2/2: ''...Done

YES
pandoc
  to: html
  output-file: 7301.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Untitled

Output created: 7301.html
````

**Comment by tpoisot** [comment]
Quarto check:

~~~
[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/bin/python3
      Jupyter: 5.4.0
      Kernels: julia-1.9, python3, python3.11
~~~

Python version

~~~
~/Test> python3 --version
Python 3.11.5
~~~

**Comment by cscheid** [comment]
I can repro this locally now.

**Comment by cscheid** [comment]
I truly don't understand what's going on, but I do see a julia process at 100% CPU:

```
Processes: 614 total, 3 running, 611 sleeping, 3872 threads                                                                                        12:43:54
Load Avg: 2.24, 2.71, 2.86  CPU usage: 15.78% user, 4.97% sys, 79.23% idle  SharedLibs: 718M resident, 143M data, 56M linkedit.
MemRegions: 587319 total, 11G resident, 711M private, 6215M shared. PhysMem: 31G used (3032M wired, 1099M compressor), 352M unused.
VM: 281T vsize, 4285M framework vsize, 0(0) swapins, 0(0) swapouts. Networks: packets: 3230259/2984M in, 1295302/587M out.
Disks: 1545131/20G read, 1092338/20G written.

PID    COMMAND      %CPU  TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS  PGRP  PPID  STATE    BOOSTS          %CPU_ME %CPU_OTHRS UID  FAULTS    COW
24729  julia        99.7  01:05.60 12/1   1    58    579M   0B     0B     24729 24726 running  *0[1]           0.00000 0.00000    501  308818    15148
```

**Comment by tpoisot** [comment]
For what it's worth, when I render with quarto, a python _3.10_ process is spawned, even though quarto says python 3.11.

**Comment by cscheid** [comment]
> For what it's worth, when I render with quarto, a python 3.10 process is spawned, even though quarto says python 3.11.

That's both unfortunate and a _separate_ bug, but I think not the one at play here, since I can reproduce your issue locally and I'm relatively confident I'm running the same python version.

**Comment by cscheid** [comment]
Minor progress. I think `current_figure()` is a red herring. I can get the same hang replacing `current_figure()` with `fig`. 

I now think this is literally something about the heatmap's algorithm taking too long (or hanging). For example, something about the DPI settings we set.

**Comment by cscheid** [comment]
I can now get your notebook to hang with `run_notebook.py`, by more faithfully approximating our Julia setup.

Quarto renders to svg by default by configuring CairoMakie at startup. This probably makes a gigantic heatmap. The following .qmd fails in run_notebook.py:

---
title: Untitled
format: html
jupyter: julia-1.9
---

```{julia}
# import Pkg; Pkg.activate("."); Pkg.add("CairoMakie")
using CairoMakie

CairoMakie.activate!(type = string(:svg))
CairoMakie.update_theme!(resolution=(7, 5))
```

```{julia}
fig = Figure(; resolution=(500, 240))
ax = CairoMakie.Axis(fig[1,1]; aspect=DataAspect())
D = rand([1,2,3], (400, 200))
heatmap!(ax, D; colormap=[:red, :green, :blue])
hidedecorations!(ax)
```

```{julia}
fig
# current_figure!(fig)
# current_figure()
```

So, the solution for you is to use `png` as the format. Manually, it'd go like this:

````
---
title: Untitled
format: html
jupyter: julia-1.9
---

```{julia}
# import Pkg; Pkg.activate("."); Pkg.add("CairoMakie")
using CairoMakie

CairoMakie.activate!(type = "png")
CairoMakie.update_theme!(resolution=(7, 5))

fig = Figure(; resolution=(500, 240))
ax = CairoMakie.Axis(fig[1,1]; aspect=DataAspect())
D = rand([1,2,3], (400, 200))
heatmap!(ax, D; colormap=[:red, :green, :blue])
hidedecorations!(ax)

fig
```

````

**Comment by cderv** [comment]
> For what it's worth, when I render with quarto, a python 3.10 process is spawned, even though quarto says python 3.11.

I would say you can get this difference depending on how you configured your Julia Kernel. IJulia can be configured to use a Jupyter and a Python that could be different that the one we see when finding Python on your system. 

Especially, 

* Julia can be configured to use an internal Conda.jl version (https://quarto.org/docs/computations/julia.html#installation)

* IJulia can be build to use a specific Jupyter otherwise (https://julialang.github.io/IJulia.jl/stable/manual/installation/#Installing-IJulia)

There was some discussion in the past that relates to this (https://github.com/quarto-dev/quarto-cli/discussions/6667)

You could check your kernels (`jupyter kernelspec list`) and look into the file for `julia-1.9` kernel to see which python version it uses. 

`quarto checks` currently finds python and list available kernels through that command, but it does not check configuration. However, when using `julia-1.9` kernel with Quarto document, it will this configuration that will be used. 

I hope to improve quarto check on this matter. 

Hope it helps

**Comment by tpoisot** [comment]
@cscheid that solved it -- interestingly, using the same setup in a RevealJS presentation worked "out of the box" (the heatmaps are png, the rest of the figures are svg). Is there something different in the way these are rendered?
