### ISSUE TITLE
include shortcode with python code does not work properly after installing v1.4.424 and later versions.

### ISSUE THREAD

**Issue by kwangkim** [quarto-dev/quarto-cli#7311]
### Steps to reproduce

bug.qmd
````{qmd}
---
title: "My Document"
---
```{python}
x=1
```
{{< include one.qmd >}}
````

one.qmd
````{qmd}
Hello!
````

I render bug,qmd.
But it does not work properly with 1.4.424 or higher version.

### Expected behavior

![Screenshot 2023-10-20 at 11 07 08 PM](https://github.com/quarto-dev/quarto-cli/assets/10469752/41b9c31d-8f6d-4928-8998-266b0339735f)

### Actual behavior

![Screenshot 2023-10-20 at 11 00 31 PM](https://github.com/quarto-dev/quarto-cli/assets/10469752/ea4d9850-8f53-478c-8b26-644eb484b913)

### Your environment

- IDE: vscode
- M2 Mac Mini Sonoma 14.1

### Quarto check output

```
Quarto 1.4.435
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.435
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /Users/kwangkim/.pyenv/versions/3.11.2/bin/python3
      Jupyter: 5.2.0
      Kernels: mojo-jupyter-kernel, python3, SageMath-9.8, SageMath-10.1

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
(/) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
Thanks for the report, I can reproduce.

**Comment by cscheid** [comment]
(@jjallaire I don't know the context in which you made that change, but we can coordinate a fix together. Let me know)

**Comment by jjallaire** [comment]
The context was the `fileExecutionEngineAndTarget` is a actually potentially expensive (as it results in our converting `.qmd` to `.ipynb` to fulfill the target). I actually separately found that in the normal course of things for preview we were doing it 5 times (!) so made a series of changes to get it town to 2 (this was one of them). What I was trying to do here was only run the code if an _include_ actually happened (so the markdown would have changed) but I clearly mis-identified. It could be enough to check fi the markdown changed _or_ there is an `{{< include >}}` in the file. If there are good reasons to go back to the old behavior we can, it will just slow things down.

**Comment by cscheid** [comment]
> I actually separately found that in the normal course of things for preview we were doing it 5 times (!) so made a series of changes to get it down to 2 (this was one of those changes)

Thanks, that's helpful and (!!) indeed. This is one instance of the type of things I hope our 1.5 execution planning work can start to target. Let me see if I can come up with a fix.

**Comment by cderv** [comment]
FWIW the commit was reverted: https://github.com/quarto-dev/quarto-cli/commit/1815be5e4d6e902525f478366caad089d3cc37df and [v1.4.184](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.484) should solve this issue.

**Comment by cscheid** [comment]
I've verified this is fixed on `main`.
