### ISSUE TITLE
Page navigation duplicates previous chapter names

### ISSUE THREAD

**Issue by road2you** [quarto-dev/quarto-cli#7324]
### Bug description

When applying the (Book) page navigation feature, it duplicates the names of previous chapters.
![quarto_page_nav_error](https://github.com/quarto-dev/quarto-cli/assets/35862752/0b6905ab-4a68-4d67-b513-bc80aede2bc3)

### Expected behavior

The chapter title should follow the left arrow.
![image](https://github.com/quarto-dev/quarto-cli/assets/35862752/fe87d121-68dd-4b13-b293-cd4eb769ba84)

### Actual behavior

However, the chapter title is duplicated to the left of the left arrow, followed by a double quotation mark and a 'Greater than sign(>)'". 

![image](https://github.com/quarto-dev/quarto-cli/assets/35862752/460d5905-d2ef-402d-9179-acae2eaa6c34)

### Your environment

- IDE: RStudio 2023.09.2+508
- OS: Ubuntu 23.04
- 

### Quarto check output

```bash
Quarto 1.4.439
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.439
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      Chromium: 869685
      TinyTeX: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.13 (Conda)
      Path: /home/snoopy/miniconda3/envs/pytorch/bin/python
      Jupyter: 5.3.0
      Kernels: pytorch, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /opt/R/4.3.1/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /opt/R/4.3.1/lib/R/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Closing as duplicate.

- https://github.com/quarto-dev/quarto-cli/issues/7319
