### ISSUE TITLE
table in a div in pdf not working

### ISSUE THREAD

**Issue by xtimbeau** [quarto-dev/quarto-cli#7334]
### Bug description

When rendering a table from knitr::kable, gt, flextable with tbl-cap and label in a div, pdf through latex is not generated with an error `LaTeX Error: Not in outer par mode.`

### Steps to reproduce

````qmd
---
title: "table in a div"
format:
  html: default
  pdf: default
---
Table in a div

::: callout-tip
```{r, echo=FALSE, message=FALSE, warning=FALSE}
#| label: tbl-table1
#| tbl-cap: "A table"
library(tidyverse)
table <- tribble(~a, ~b, ~c,
                "text", 1, "Long text",
                "others", 2, "Long text") 
knitr::kable(table)
```
:::
````

### Expected behavior

pdf generated with cross reference working (as in html)

### Actual behavior

error in pdf generation
html is OK

### Your environment

IDE RStudio 2023.09.2 Build 508
Quarto 1.4.444

### Quarto check output

```bash
Quarto 1.4.444
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.444
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.02
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/xt/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

-ne 
```

**Comment by cscheid** [comment]
The issue here is not that it's in a div - it's that it's in a _callout_. Unfortunately, the code used for callouts does not allow floating environments in its contents. That's not something we can control.

We should be able to detect this problem and emit an error, but the functionality will unfortunately not be possible to implement.

**Comment by mcanouil** [comment]
@xtimbeau Slight note you should not mix code cell options syntax, even in rmarkdown/knitr it is not recommended.
Quarto recommends and uses YAML style code cell options thus:

````qmd
```{r}
#| label: tbl-table1
#| tbl-cap: "A table"
#| echo: false
#| message: false
#| warning: false
...
```
````

**Comment by cscheid** [comment]
With the fix in #7341, this is what you'll see:

```
$ quarto render 7334.qmd --to pdf


processing file: 7334.qmd
1/3
2/3 [tbl-table1]
3/3
output file: 7334.knit.md

pandoc
  to: latex
  output-file: 7334.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: table in a div

WARNING (/Users/cscheid/repos/github/quarto-dev/quarto-cli/src/resources/filters/./quarto-post/latex.lua:216)
Table elements are not allowed inside callouts in LaTeX.
Lifting tbl-table1 out of callout.

Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

Output created: 7334.pdf
```

Of course, the table itself is now outside the callout:

<img width="765" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/0a5e3562-d3f1-4a95-87db-4ebff0043b25">

That's unavoidable in LaTeX.

**Comment by xtimbeau** [comment]
Ok, I see.
So there is no way to produce a box in latex with a table in the box. That is a bit annoying for academic/technical documents where boxes are frequent.

**Comment by mcanouil** [comment]
You can keep the pretty output for HTML and deal with LaTeX output separately using conditional contents.
See <https://quarto.org/docs/authoring/conditional.html>.

Maybe an alternative would be the Typst format added in the 1.4 pre-release.

**Comment by xtimbeau** [comment]
typst is indeed working quite well in that case (see the pic. despite the fact the icon is back when `icon=false`). However, it is unclear that everything latex/pdf are doing can be done in typst ?
<img width="600" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/54633745/fe077c88-4ff4-4f25-bc0b-ccd6432e6315">

**Comment by cscheid** [comment]
> see the pic. despite the fact the icon is back when icon=false

That's a separate bug!

> However, it is unclear that everything latex/pdf are doing can be done in typst ?

No, not everything will be doable right away; it's a brand new format and although the community support is growing quite fast, it doesn't have 40 years of tool development.

**Comment by xtimbeau** [comment]
typst looking very cool (compared to latex the nightmare)

**Comment by cscheid** [comment]
Ok, I have good news! I learned that there _is_ a way to make the crossref work inside a callout. I have a real fix incoming.

**Comment by xtimbeau** [comment]
🫶
