### ISSUE TITLE
Unable to increase memory allocation for LaTex 

### ISSUE THREAD

**Issue by Inyourfacer** [quarto-dev/quarto-cli#7346]
### Bug description

I am running into an error when trying to render a jupyter notebook to pdf with the command:
quarto render notebook.ipynb --to pdf

TeX capacity exceeded, sorry [main memory size=5000000]

I have tried the command:
export QUARTO_DENO_EXTRA_OPTIONS=--v8-flags=--max-old-space-size=32768

It does not seem to impact the main memory size. I have also added it to the texmf.cmf file as:
main_memory = 7000000

The machine running everything has plenty of memory ~250gb.
Is there a different method to allocate more memory for this process?

### Your environment

- OS: Linux Fedora 8.8
- JupyterLab 1.2.6
- Quarto 1.3.433

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/quarto/1.3.433/bin

 

[✓] Checking basic markdown render....OK

 

[✓] Checking Python 3 installation....OK
      Version: 3.7.6 (Conda)
      Path: /opt/anaconda3/bin/python
      Jupyter: 4.6.1
      Kernels: python3, great_expectations_global

 

(-) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/1.3.433/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/1.3.433/share/jupyter/notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
There is a environment.yml file in this directory. Is this for a conda env that you need to restore?

 

[✓] Checking Jupyter engine render....OK

**Comment by cscheid** [comment]
This is LaTeX running our of memory:

> TeX capacity exceeded, sorry [main memory size=5000000]

This configures deno:

> export QUARTO_DENO_EXTRA_OPTIONS=--v8-flags=--max-old-space-size=32768

Try `format: latex`, and then running `pdflatex $OUTPUT_FILE` yourself. If you run out of memory in that scenario, then I think there's nothing we can do; is there something about your document in particular that might be causing LaTeX to allocate too much memory?

**Comment by cderv** [comment]
Something in your document is taking a lot of resource. As @cscheid said this is a LaTeX problem. You should look at this issue from a LaTeX point of view and not Quarto. Quarto only calls pdf engine for you (by default `xelatex` or other pdf engine set)

**Comment by Inyourfacer** [comment]
You are correct that it was the notebook itself that was causing the memory issue. I was unable to determine what was causing it specifically but moving to a new notebook resolved it. Thank you for your help.
