### ISSUE TITLE
Callouts in dashboard have wrong display

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#7350]
### Bug description

The callouts in `dashboard` are not properly displayed, *i.e.*, the icon is on a separate line and the callouts is stretched inside a card (in some aspects it is kind of expected but quite not eye pleasing). 

### Steps to reproduce

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr>
<td>

````qmd
---
title: Dashboard
format: dashboard
---

# About

::: {.callout-note}
This is a note about this dashboard.
:::
````

</td>
<td>
<img width="727" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/83db011c-ae89-45c6-a2c2-1559eeb3480d">
</td>
</tr>
</table>

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr>
<td>

````qmd
---
title: Dashboard
format: dashboard
---

# About

::: {.card}

::: {.card-header}
About
:::

::: {.card-body}
::: {.callout-note}
This is a note about this dashboard.
:::
:::
:::
````

</td>
<td>
<img width="579" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/d89407df-37aa-4559-bf8d-44599efa8a91">
</td>
</tr>
</table>

### Quarto check output

Quarto: 452eea694f326cf024c0637981588b203d11c1cc

**Comment by cscheid** [comment]
This is probably a matter of changing the postprocessor so that html-fill is not so aggressively recursed into.
