### ISSUE TITLE
Error message not clear when no title provided in dashboard

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#7351]
### Bug description

Currently, when using pages and no title metadata, Quarto outputs `ERROR: Expected a navbar in the dashboard output since pages are specified.` which is not very clear.
Since this error is only displayed when the title is missing, rephrasing this message to actually say the title is missing would help.

### Steps to reproduce

````qmd
---
format: dashboard
---

# About

::: {.callout-note}
This is a note about this dashboard.
:::

````

### Quarto check output

Quarto: 452eea694f326cf024c0637981588b203d11c1cc

**Comment by dragonstyle** [comment]
Fixed here - it is no longer an error:

https://github.com/quarto-dev/quarto-cli/commit/d6415dd61e19321bd90d3ea50ccac41eb82400ab
