### ISSUE TITLE
`copyright` and `license` added as a scrollable block in dashboards

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#7352]
### Bug description

It appears dashboard uses `copyright` and `license` but kind of the same way as in regular HTML, *i.e.*, as sections which looks not great in the dashboard.

Probably better to add it in/as the website footer.

### Steps to reproduce

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr>
<td>

````qmd
---
title: Dashboard
format:
  dashboard:
    orientation: columns
    theme: litera
copyright: "A copyright."
license: "A license."
---

# Analysis

## Row

### Column

```{python}
import matplotlib.pyplot as plt
import numpy as np

# Generate some random data
x = np.random.rand(50)
y = np.random.rand(50)

# Create a scatter plot
plt.scatter(x, y)

# Show the plot
plt.show()
```

### Column

The figure is amazing!

## Row

### Column

The figure is amazing!

### Column

```{python}
import matplotlib.pyplot as plt
import numpy as np

# Generate some random data
x = np.random.rand(50)
y = np.random.rand(50)

# Create a scatter plot
plt.scatter(x, y)

# Show the plot
plt.show()
```

````

</td>
<td>

https://github.com/quarto-dev/quarto-cli/assets/8896044/aa015359-f2d3-48b0-b3ee-18ee4101f7b7

</td>
</tr>
</table>

### Quarto check output

Quarto: 452eea694f326cf024c0637981588b203d11c1cc

**Comment by dragonstyle** [comment]
Support for Appendix fields including `copyright` and `license` is no longer supported in dashboards (these fields are now ignored in dashboards)
