### ISSUE TITLE
Quarto PDF render adding blank pages

### ISSUE THREAD

**Issue by SEthanMilne** [quarto-dev/quarto-cli#736]
Hi, first time posting an issue on GitHub, so please let me know if this isn't formatted properly.

I'm experimenting with Quarto on an M1Max MacBook Pro, using R 4.2.0. When I create a Quarto file to generate a pdf, I'm finding the render process is inserting an extra blank page despite no instructions to do so (e.g. \pagebreak).

Here's the entirety of the file:

```
---
title: "TestFile"
format: pdf
editor: visual
author: "For Quarto Issue"
date: "`r format(Sys.time(), '%B %d, %Y')`"
abstract: "This is a test"
---

# Introduction

# Conceptual Development

# Overview of Studies

# Study 1

## Methods

## Results

## Discussion

# Study 2

## Methods

## Results

## Discussion

# Study 3

## Methods

## Results

## Discussion

# Study 4

## Methods

## Results

## Discussion

# Study 5

## Methods

## Results

## Discussion

# General Discussion

# Appendix

# References

```
Which outputs the following PDF file -- you can see there's a blank page in between the title/abstract and the first Introduction header.

(Edit: I just noticed this now -- the 3rd page also does not include all headers. After "General Discussion" the headers disappear instead of showing up on a new page)

[quarto_issue_file.pdf](https://github.com/quarto-dev/quarto-cli/files/8565323/quarto_issue_file.pdf)

**Comment by jjallaire** [comment]
This is an artifact of the way LaTeX is typesetting when there are only headings and no content. If you add some text below `# Introduction` you'll see the problem dissapear:

```markdown
---
title: "TestFile"
format: pdf
editor: visual
author: "For Quarto Issue"
date: "`r format(Sys.time(), '%B %d, %Y')`"
abstract: "This is a test"
---

# Introduction

Introduction

# Conceptual Development

etc.
```

You'll still see the blank page but as you fill content into your sections the problem will go away.

**Comment by SEthanMilne** [comment]
Thank you, that fixed it!
