### ISSUE TITLE
Nested layout not working as expected

### ISSUE THREAD

**Issue by juliantao** [quarto-dev/quarto-cli#7363]
### Bug description

If a `layout` div is nested in a master `layout` div. The top-level `layout` div has no effect. 

### Steps to reproduce

````qmd
title: "Nested Layout"
date: "2023-10-25"
format: revealjs
---

## Actual behavior using `layout` 

::: {layout="[1, 1]"}

![](https://placehold.co/300x300)

::: {layout="[1, 1]"}
![](https://placehold.co/300x300)

![](https://placehold.co/300x300)
:::
:::


## Expected behavior (achieved using `columns`)


::: {.columns}
::: {.column width="50%"}
![](https://placehold.co/300x300)

:::
::: {.column width="50%"}
::: {layout="[1, 1]"}
![](https://placehold.co/300x300)

![](https://placehold.co/300x300)
:::

:::
:::

````

### Expected behavior

![image](https://github.com/quarto-dev/quarto-cli/assets/60116296/03356242-a7c1-4b43-b3c1-0e8d8f647ab3)

### Actual behavior

![image](https://github.com/quarto-dev/quarto-cli/assets/60116296/b39b3707-3999-4633-b84b-30dd863cb1bf)

### Your environment

- OS: Linux Pop!_OS 22.04 LTS x86_64

### Quarto check output

Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/julian/quarto-cli/package/dist/bin

Check file:///home/julian/quarto-cli/src/resources/vendor/deno-land/x/puppeteer@9-0-2/mod.ts
[✓] Checking tools....................OK
      TinyTeX: v2023.06
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/julian/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 4.10.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

R scripting front-end version 4.1.2 (2021-11-01)
[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by mcanouil** [comment]
I do not think there is a bug, this is not how layout is supposed to work or be used.

````qmd
::: {layout="[4,2,2]"}
![](https://placehold.co/300x300)

![](https://placehold.co/300x300)

![](https://placehold.co/300x300)
:::
````

**Comment by cscheid** [comment]
You should be able to use something like

````
::: {.panel-fill layout="[ [1], [1,1] ]"}

(outputs)

:::
````

I don't think layouts were designed to work with nesting (that would be quite hard to do in formats like LaTeX)

**Comment by mcanouil** [comment]
@cscheid your example will produce the screenshot showed in "actual behaviour".

I am going ahead and close this, because layout is intended for complex layout as it allows to specify that complex layout in the square bracket format which will cover any nested thing you might want to do.

**Comment by juliantao** [comment]
Thanks for the very quick response. @mcanouil @cscheid.
It was strange, but it worked before. I used this "nesting" approach extensively before. When I re-render some old files today, it no longer works.

**Comment by cscheid** [comment]
@juliantao That's why I mentioned "designed to work" as opposed to "happened to work". I'm sorry you depended on this behavior, but unfortunately, some of the changes we had to make will cause nested layouts to not work. We should emit an error message or a warning, but you shouldn't depend on that. In the meantime,  @mcanouil showed a way to do what you wanted.

**Comment by mcanouil** [comment]
If it worked before it was unintended bacause layout is designed for complex layout.
There is no point to want to nest those divs.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/367e540b-9410-499d-bd17-48dbdf04056c">

**Comment by juliantao** [comment]
Understood. Thanks again! @cscheid @mcanouil
