### ISSUE TITLE
Empty RevealJS plugin makes presentation blank

### ISSUE THREAD

**Issue by davidahirshberg** [quarto-dev/quarto-cli#7365]

**Comment by davidahirshberg** [comment]
I'm trying to wrap a revealJS plugin and finding that, if it's included, I get a blank presentation. This happens with an empty revealJS plugin as shown below.

<img width="2560" alt="Screenshot 2023-10-25 at 10 43 34 PM" src="https://github.com/quarto-dev/quarto-cli/assets/1794012/5106300f-1a3a-477c-8df2-5db5b88231ff">
<img width="2560" alt="Screenshot 2023-10-25 at 10 44 08 PM" src="https://github.com/quarto-dev/quarto-cli/assets/1794012/0234c66e-ee14-4e1a-a84c-8137ad9b6863">

**Comment by mcanouil** [comment]
Please edit and complete your post with all the requested informations.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by cscheid** [comment]
We do need a fully reproducible example in text from you so that we can proceed. I'm going to close this as stale but please reopen if you can provide one.
