### ISSUE TITLE
Shiny app "not found" using shinylive-r extension

### ISSUE THREAD

**Issue by cgoo4** [quarto-dev/quarto-cli#7370]
### Bug description

I'm unable to render an example shinylive-r app within Quarto.

### Steps to reproduce

I'm following the [example here](https://quarto.thecoatlessprofessor.com/r-shinylive-demo/) to render an r-shinylive app.

Installed the R package with `pak::pak("posit-dev/r-shinylive")`

Created a new Quarto project and added the extension with `quarto add quarto-ext/shinylive`

Set up the `qmd` per below:

````
---
title: "test2"
filters:
  - shinylive
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

```{shinylive-r}
#| standalone: true
#| viewerHeight: 600
library(shiny)

# Define UI for app that draws a histogram ----
ui <- page_sidebar(
  sidebar = sidebar(open = "open",
    numericInput("n", "Sample count", 100),
    checkboxInput("pause", "Pause", FALSE),
  ),
  plotOutput("plot", width=1100)
)

server <- function(input, output, session) {
  data <- reactive({
    input$resample
    if (!isTRUE(input$pause)) {
      invalidateLater(1000)
    }
    rnorm(input$n)
  })
  
  output$plot <- renderPlot({
    hist(data(),
      breaks = 40,
      xlim = c(-2, 2),
      ylim = c(0, 1),
      lty = "blank",
      xlab = "value",
      freq = FALSE,
      main = ""
    )
    
    x <- seq(from = -2, to = 2, length.out = 500)
    y <- dnorm(x)
    lines(x, y, lwd=1.5)
    
    lwd <- 5
    abline(v=0, col="red", lwd=lwd, lty=2)
    abline(v=mean(data()), col="blue", lwd=lwd, lty=1)

    legend(legend = c("Normal", "Mean", "Sample mean"),
      col = c("black", "red", "blue"),
      lty = c(1, 2, 1),
      lwd = c(1, lwd, lwd),
      x = 1,
      y = 0.9
    )
  }, res=140)
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
````
Rendering created the expected file structure:

<img width="180" alt="Screenshot 2023-10-26 at 16 49 16" src="https://github.com/coatless-quarto/r-shinylive-demo/assets/32419319/99444690-8638-4f88-85e3-f86b1f5067b0">

### Expected behavior

Per [example](https://quarto.thecoatlessprofessor.com/r-shinylive-demo/).

### Actual behavior

App "Not Found" when rendering locally:

<img width="829" alt="Screenshot 2023-10-26 at 16 50 23" src="https://github.com/coatless-quarto/r-shinylive-demo/assets/32419319/53aa218b-dd59-45d0-8ff1-3b88d86f94ac">

### Your environment

- RStudio Version 2023.09.1+494
- macOS Sonoma 14.0

### Quarto check output

```bash
Quarto 1.4.446
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.446
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Thanks for the report.

Please note that you're filing a bug report using information from a third-party site, using an extension that has a separate issue tracker: https://github.com/quarto-ext/shinylive/

It would make our lives easier if you could confirm that the issue isn't with the extension itself first. Have you done that?

**Comment by cscheid** [comment]
That website has a bad example. It's missing `library(bslib)` in the snippet.

see https://github.com/coatless-quarto/r-shinylive-demo/blob/main/R-shinylive-demo.qmd for the correct file. The example works:

<img width="886" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/aa5b994f-23a7-4c9d-bb1b-bc3a92fcba48">
