### ISSUE TITLE
listings pages sometimes generate two entries for pages in folder... sometimes

### ISSUE THREAD

**Issue by DOSull** [quarto-dev/quarto-cli#7379]
I know you are going to request a minimal reproducible example for this, but I have been unable to create one that is fully repeatable. However, in the attached zip you'll find files for a very simple website, with a drop-down menu leading to a listings page. One page is generated from RMarkdown in a .qmd file, the other from a Jupyter notebook. The contents specification in the listings page is given as 

```
  contents:
    - "page*"
```
but I also see the behaviour with other listings specifications (like e.g., `page*.*`)

This configuration produces this listing web page (also in the zip file):
![image](https://github.com/quarto-dev/quarto/assets/8213420/bd0dc500-73cf-4f53-9cbe-5cddfb8ce9cb)

where each page appears twice, once as a blank card. 

The behaviour is not reliable however, and seems to change in ways I cannot account for. For example, if I add a new page then maybe it will be fine for a while. I first saw the behaviour developing a more complicated site, and it seems only to happen when there are a mix of Jupyter notebooks and qmd files in a folder. It seems not to happen if I explicitly list all the contents with their full names (but that is annoying to do on a large site).

I wonder if it has something to do with the difference between how qmd and ipynb files get converted to HTML. Or is it the timing of the render process? (this might account for the unpredictable behaviour and how it changes seemingly at random when I make a new page in a folder). 

I'm running VSCode and have seen this on both Mac and Linux with quarto 1.3.45.

[mre-website.zip](https://github.com/quarto-dev/quarto/files/13186280/mre-website.zip)

**Comment by DOSull** [comment]
You could try the thing I included in the zip file, which did produce the output shown, just to confirm there's a bug? if it doesn't do that at your end, I can keep trying - it is definitely a behaviour I'm seeing!

**Comment by dragonstyle** [comment]
This issue is caused by the fact that the glob that you are providing matches both the notebooks and the generated HTML pages that are rendered when rendering the site:

```
[listing] Contents: section1/page*.*
[listing] matches 4 files:
[listing] Reading file /Users/ct/Downloads/mre-website/sections/section1/page1.html
[listing] Missing Title in File /Users/ct/Downloads/mre-website/sections/section1/page1.html
[listing] Reading file /Users/ct/Downloads/mre-website/sections/section1/page1.qmd
[listing] Reading file /Users/ct/Downloads/mre-website/sections/section1/page2.html
```

Updating to a folder only will limit it to inputs only:

```
---
title: Title
subtitle: Subtitle
listing:
  contents:
    - "section1"
  sort: false
  type: grid
---

Notebooks appear twice once as a blank card...
```

We currently process globs that include wildcards very literally, mostly because we want to enable an escape hatch for folks that would like to include non-quarto input files in their listings...

**Comment by DOSull** [comment]
This is unfortunate, as I was trying to use this to control the order in which pages are listed with globs like

```
  contents:
    - "page0*.qmd"
    - "page1*.qmd"
  sort: false
```

or similar, but when python notebooks are also present I have to switch to the `page1*.*` or similar and then I get the duplicated entries. Just letting quarto do the sorting by specifying the field results in sort orders I don't want.

Oh well I'll just have to list the listings page contents by hand if I want the behaviour I'm after.

Thanks for looking into it.

**Comment by dragonstyle** [comment]
You can use curly braces to provide two different extensions that match, like:

```
---
title: Title
subtitle: Subtitle
listing:
  contents:
    - "section1/**/*.{qmd,ipynb}"
  sort: false
  type: grid
---
```

**Comment by DOSull** [comment]
I'll give it a try and report back!

**Comment by DOSull** [comment]
Yes! This kind of contents specification gives me the behaviour I was after:
```
  contents:
    - "**/prefix1-0*.{qmd,ipynb}"
    - "**/prefix1-1*.{qmd.ipynb}"
    - "**/prefix2-0*.{qmd,ipynb}"
    -   ... etc.
```
_relatively_ painlessly.

Seems like a case of READ ALL OF THE ... MANUAL - YES! THE WHOLE THING!

Thanks for taking the time, and the suggestion.
