### ISSUE TITLE
Footnotes don't play well in dashboard sidebar

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#7390]
### Bug description

With Quarto 1.4.451, if you add a footnote in a dashboard sidebar, I think it should show up in the sidebar, and hide away when sidebar is collapsed. Currently, it shows up at the bottom of the page.

### Steps to reproduce

Reproduce the following dashboard and interact with the footnote and the sidebar.

````markdown
---
title: "Sample dashboard"
format: dashboard
---

#  {.sidebar}
Hello.[^1]


[^1]: I'm a footnote.

# Page 1

```{r}
plot(cars)
```

# Page 2

```{r}
plot(cars)
```
````

### Actual behavior

At the start:

<img width="500" alt="Screenshot 2023-10-28 at 6 22 59 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/1c8c1095-91a3-4e8f-b1a6-3f60a85619f2">

When you click on footnote number -- note that the page contents are no longer visible:

<img width="500" alt="Screenshot 2023-10-28 at 6 23 06 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/0052f3ae-3a6e-4dc3-b682-f29252c52c1d">

When sidebar is collapsed:

<img width="500" alt="Screenshot 2023-10-28 at 6 23 13 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/5f97ba23-1691-485a-8509-d4cc3ff03d0d">

**Comment by sj-io** [comment]
Could there also be an option to hide the footnote section all together? I have a small footnote I'd like viewable on hover and I'd rather not add a footnote section for it.

**Comment by dragonstyle** [comment]
Footnotes should now work properly. Footnote contents in dashboard are always shown on hover only (there is no footnotes section)
