### ISSUE TITLE
mermaid error with revealjs output-location: fragment AND echo: true

### ISSUE THREAD

**Issue by irmoodie** [quarto-dev/quarto-cli#7394]
### Bug description

If a quarto document is specified as in the reprex with `output-location: fragment` AND `echo: true`, the mermaid output fails with:

```
Syntax error in text 
mermaid version 10.2.0-rc.2
```

![image](https://github.com/quarto-dev/quarto-cli/assets/38960700/bb8d58b1-1486-468b-88b2-6ef9d035b07f)

Changing `echo: false` results in the correct output, as does `output-location: default`. I think I have narrowed it down to the combination being the issue.

### Steps to reproduce

````qmd
---
title: "reprex"
format: 
  revealjs:
    output-location: fragment
execute:
  echo: true
---

```{mermaid}
flowchart LR
A[Input]
```
````

### Expected behavior

The mermaid code should be shown, an on progression of the slide, the mermaid output shown.

### Actual behavior

The mermaid code is shown, but on progression of the slide an error is shown instead of the mermaid plot.

### Your environment

- IDE: VSCode 1.83.1
- OS: MacOS Sonoma 14.0

### Quarto check output

```bash
Quarto 1.4.451
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.451
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: julia-1.8

      NOTE: No Jupyter kernel for Python found

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
This is fixed on `main` by https://github.com/quarto-dev/quarto-cli/commit/a1777f93761a9d0524842622fca74083ef11c18b.
