### ISSUE TITLE
Error when trying to publish a Quarto revealjs presentation

### ISSUE THREAD

**Issue by mauriziopassariello** [quarto-dev/quarto-cli#7397]
### Bug description

Hi,
When I try to publish a Quarto presentation and put the command in the terminal "quarto publish quarto-pub" I get this error:
ERROR: Unknown command "publish". Did you mean command "preview"?
I am running R on RStudio on a mac. I. recently updated R and Rstudio.
Can someone help me fix this? 
Thanks!

```[tasklist]
### Tasks
```

**Comment by mcanouil** [comment]
Please fill in the section for the template, in particular the environment and Quarto version.

**Comment by mauriziopassariello** [comment]
Im using a mac with macos 14 sonoma
Quarto check produces this result:
[✓] Checking Quarto installation......OK
      Version: 0.9.298
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

I'm using RStudio Version 2023.09.1+494 (2023.09.1+494)

**Comment by mcanouil** [comment]
There is no bug here, you are using a very old version of Quarto.
Please either upgrade RStudio to get an updated version or install Quarto as a standalone software.
See <https://quarto.org/docs/get-started/>.

**Comment by mauriziopassariello** [comment]
Thanks very much
