### ISSUE TITLE
Puzzling difference in behavior of code chunks in lists

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#74]
When porting a project from Bookdown, I found the following behavior surprising.

We are embedding code chunks in list items, for example:

```
#.  First item:

    ```{python}
    print("First item code")
    ```
```

When using `rmarkdown::render()`,  this executes and renders as I would expect with the rendered code output under the indented code block.

When rendering the same Rmd file in Quarto, the code executes correctly, but the rendered doc has lots of stray Markdown in it, such as:

~~~
::: {.cell indent=” “}

```{.python .cell-code}
print("First item code")
```

::: {.cell-output-stdout}
```
First item code
```
:::

:::
~~~

With Qmd format, the rendering does not interpret the in-list code blocks correctly, and leaves output like the following:

~~~
    First item:

    print(“First item code”) ```
~~~

The repo <https://github.com/matthew-brett/quarto-test/tree/main> has a MWE of Markdown, Rmd via Quarto, Rmd via `rmarkdown`, and Qmd format, generated with `make all`.

I am using the latest development version of Quarto, as of this evening.

**Comment by jjallaire** [comment]
Thanks for reporting this! We'll take a look right away. I'm sure there are a couple of bugs in here, but note that the extra markdown output is there on-purpose. It's there so that CSS / Lua filters can do additional styling/layout of the content, it won't result in additional visible output, it's just semantic).

**Comment by matthew-brett** [comment]
Thanks for quick reply. The markup appears in the HTML.  I guess that isnt intended?

**Comment by jjallaire** [comment]
No that's probably b/c the markup is malformed. Once this works as it
should that markup will only be in the HTML as divs that won't occupy any
visible space -- again they are just semantic.

**Comment by jjallaire** [comment]
This should now be fixed with https://github.com/quarto-dev/quarto-cli/commit/235f9e95d657069fca5eca6255a8bb2d27b0aea2.

This is available on `main` as well as in the updated release build v0.2.46.

**Comment by matthew-brett** [comment]
Thanks again for the quick response.  Updating to latest `main` I now get the expected result for the `.qmd` file, but I still get the leaked Markdown in the generated HTML from the `.Rmd` file: <https://github.com/matthew-brett/quarto-test/blob/main/code_in_list_rmd.html>.

**Comment by jjallaire** [comment]
Ah, I had missed that. Fix for the Knitr engine case is here: https://github.com/quarto-dev/quarto-cli/commit/87f12428f31d0624ec2062197dbf126efa4c6504

**Comment by matthew-brett** [comment]
Excellent - thanks - that fixes it.
