### ISSUE TITLE
Cards, valueboxes, etc.. within tabset

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#7405]
Should we make nested cards, valueboxes, etc... work within tabsets?

**Comment by pensivedog** [comment]
I'm trying to add a valuebox as a tab in a tabset using Quarto 1.5.57 and it's not working. Can you please provide some instruction on how to make this work?

**Comment by mcanouil** [comment]
@pensivedog please don't ping developers for questions especially on a very old and closed issue.
Please read carefully the documentation then, eventually go to the repository Discussion board and do read carefully the guidelines to ask questions.
Thank you!
