### ISSUE TITLE
Generating Altair concatenated / layered chart gets overlapped div id

### ISSUE THREAD

**Issue by plasmak11** [quarto-dev/quarto-cli#7418]
Issue related to the displaying mechanism for Altair charts are programmed either in Quarto or Altair

# What works:
For simple charts:

```python
import altair as alt
from vega_datasets import data

source = data.movies.url

fig1 = alt.Chart(source).mark_rect().encode(
    alt.X('IMDB_Rating:Q').bin(maxbins=60),
    alt.Y('Rotten_Tomatoes_Rating:Q').bin(maxbins=40),
    alt.Color('count():Q').scale(scheme='greenblue')
)

# For the sake of the example same figure

fig2 = alt.Chart(source).mark_rect().encode(
    alt.X('IMDB_Rating:Q').bin(maxbins=60),
    alt.Y('Rotten_Tomatoes_Rating:Q').bin(maxbins=40),
    alt.Color('count():Q').scale(scheme='greenblue')
)
```

```rmd

```{python}
fig1
\```

```

```rmd
```{python}
fig2
\```
```

Will generate two figures, each in their cell blocks.

-------
## Problem: 
When the charts are "layered" or "concatenated charts", the first chart gets replaced by the next chart, next chart, subsequent charts. First rendering block ends up with the last complex Altair chart. 

Basically "overwriting" the chart as it renders

```rmd

```{python}
fig2 + fig1
\```
```

```rmd

```{python}
fig1 | fig2
\```
```

-------

What I can discover from the HTML preview on web browser:

Altair layered/concatenated charts don't end up with unique `div id`, but rather a default `vis`. All subsequent charts get this ID:
![WhatsApp Image 2023-10-30 at 10 02 17 AM](https://github.com/quarto-dev/quarto/assets/10780685/c598cbdc-57ea-40c5-84fc-c66a31afacc1)

Simple charts end up with unique ID, which can be changed via naming the chunks.
![WhatsApp Image 2023-10-30 at 10 03 20 AM](https://github.com/quarto-dev/quarto/assets/10780685/de21e5a1-b5c9-454a-bc3a-a856523c5c8d)

Unsure if this is Altair issue or Quarto issue. 

P.S. Full .qmd file:

````
---
title: "Report"
date: "2023-10-29"
toc: true
execute:
    echo: false
    warning: false
    error: false
---

```{r}
library(reticulate)
reticulate::use_python("~/.virtualenvs/r-reticulate/bin/python3.9", required=T)
```

# Heading
```{python}
import altair as alt
import pandas as pd

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

fig1 = alt.Chart(source).mark_bar().encode(
    x='a',
    y='b'
)
fig2 = alt.Chart(source).mark_bar().encode(
    x='a',
    y='b',
    color='b:N'
)
fig3 = alt.Chart(source).mark_bar().encode(
    x='a',
    y='b',
    color='a:N'
)
```

## Chart1 
```{python}
(fig1 | fig2).properties(title="This is the First Chart")
```

## Chart2 
```{python}
(fig2 | fig1).properties(title="This is the Second Chart")
```

## Chart3 
```{python}
(fig2 | fig1 | fig3).properties(title="This is the Third Chart")
```


# Table 
```{r}

source <- py$source

knitr::kable(
    source
)
```

````

![WhatsApp Image 2023-10-30 at 11 31 22 AM](https://github.com/quarto-dev/quarto-cli/assets/10780685/be4ea508-bf54-4777-8782-47a683c22768)

**Comment by cderv** [comment]
Thanks for the report. Could you provide a full document .qmd reproducible example using correct markdown syntax to include it ? 
https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us

You can edit your post to include this. Thanks - that will help us help you

**Comment by cscheid** [comment]
I can't reproduce this:

<img width="474" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/a00bb2f6-3b17-43aa-99bc-bd32c9c919ff">

**Comment by plasmak11** [comment]
Working with sensitive data so will try iron out something simple to replicate...

**Comment by plasmak11** [comment]
> Thanks for the report. Could you provide a full document .qmd reproducible example using correct markdown syntax to include it ? https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us
> 
> You can edit your post to include this. Thanks - that will help us help you


Working with sensitive data so will try iron out something simple to replicate...

**Comment by plasmak11** [comment]
@cderv @cscheid 

Seems like this is a weird outlier combination of using R and python, using reticulate environment.

Tried out deleting all of the R chunks --> all Altair charts render as designed, with unique `<div id=` 

When adding R chunks --> Altair charts `<div id="vis"`

**Comment by cscheid** [comment]
> reticulate environment

That's for here, then: https://github.com/rstudio/reticulate

**Comment by cderv** [comment]
This is open now at 
* https://github.com/rstudio/reticulate/issues/1500
It should be tracked there

**Comment by plasmak11** [comment]
Thank you for the redirection! @cderv @cscheid - looking into reticulate python renderer -- current workaround will be re-rendering it using `vegawidget`

- Store as `chart1 = fig1.to_json()`
- Render it in R block as `as_vegaspec(py$chart1)`

e.g. Someone's gist snippet:

https://gist.github.com/ijlyttle/aa314d02b5f7f85702ea2a648393b21f
