### ISSUE TITLE
Layout attributes for figures produced by executable code blocks fails in PDF output

### ISSUE THREAD

**Issue by finkelshtein** [quarto-dev/quarto-cli#7429]
### Bug description

The example [from the documentation](https://quarto.org/docs/authoring/figures.html#complex-layouts) fails in PDF format, though works in HTML.

### Steps to reproduce

````qmd
---
title: Test
format: pdf
---

Example 
```{python}
#| layout-ncol: 2
#| fig-cap: 
#|   - "Line Plot 1"
#|   - "Line Plot 2"

import matplotlib.pyplot as plt
plt.plot([1,23,2,4])
plt.show()

plt.plot([8,65,23,90])
plt.show()
```
````

### Expected behavior

THe output should be similar to the HTML output

![image](https://github.com/quarto-dev/quarto-cli/assets/35048241/e47f3d07-fdce-414d-9c93-fac3849a82b5)

### Actual behavior

The generated TeX-file contains lines:

````latex

\begin{figure}
\begin{minipage}[t]{0.50\linewidth}
\begin{figure}
{\centering \includegraphics{figs_files/figure-pdf/cell-2-output-1.pdf}
}
\caption{Line Plot 1}
\end{figure}%
\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}
\begin{figure}
{\centering \includegraphics{figs_files/figure-pdf/cell-2-output-2.pdf}
}
\caption{Line Plot 2}
\end{figure}%
\end{minipage}%
\end{figure}%

````

Nested figures would not work, they are redundant. The following output would be compiled as expected:

````latex

\begin{figure}
\begin{minipage}[t]{0.50\linewidth}
{\centering \includegraphics{figs_files/figure-pdf/cell-2-output-1.pdf}
}
\caption{Line Plot 1}
\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}
{\centering \includegraphics{figs_files/figure-pdf/cell-2-output-2.pdf}
}
\caption{Line Plot 2}
\end{minipage}%
\end{figure}%

````

### Quarto check output

Quarto 1.4.455
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
      Version: 1.4.455
      Path: C:\Users\dmitri\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

      TinyTeX: (not installed)
      Chromium: (not installed)

      Using: Installation From Path
      Path: C:\texlive\2022\bin\win32
      Version: 2022

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

      Version: 4.2.2
      Path: C:/PROGRA~1/R/R-42~1.2
      LibPaths:
        - C:/Users/dmitri/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.2/library
      knitr: 1.42
      rmarkdown: 2.20

**Comment by cscheid** [comment]
We really do need your `quarto check` information.

**Comment by finkelshtein** [comment]
Apologies. Updated. 

P.S. Don't know why it says that Python is not located, it works fine (e.g. for HTML output).

**Comment by cderv** [comment]
I believe this could be duplicate or at least related to 
* https://github.com/quarto-dev/quarto-cli/issues/7262
* https://github.com/quarto-dev/quarto-cli/issues/7309

They all are about layout not working in PDF because too many `\begin{figure}` nested

**Comment by cscheid** [comment]
They're definitely related.
