### ISSUE TITLE
Render to several formats by declaring them in YAML header

### ISSUE THREAD

**Issue by larnsce** [quarto-dev/quarto-cli#743]
# Goal

Render to html and pdf by declaring both formats in YAML header.

# Problem

Using the GUI Render button only yields output in the format that is mentioned first.

# Reproducible Example

On RStudio Cloud: https://rstudio.cloud/project/3967937

```
---
title: "Render to several document formats"
format:
  html:
    toc: true
  pdf:
    toc: true
editor: visual
---

# Goal

Render to html and pdf by declaring both formats in YAML header.

# Problem

Using the GUI Render button only yields output in the format that is mentioned first.
```

**Comment by jjallaire** [comment]
You can either use the drop down menu to render to the other format:

<img width="643" alt="Screen Shot 2022-04-27 at 5 39 38 AM" src="https://user-images.githubusercontent.com/104391/165489934-68572213-1204-4296-8896-9b2327ac4bcf.png">

Or call render from the bash or R command line:

```bash
quarto render document.qmd
```

```r
library(quarto)
quarto_render("document.qmd")
```

**Comment by larnsce** [comment]
I would bet anything that the dropdown menu wasn't there earlier. ;) 

Thanks for the quick response! That sorted it.
