### ISSUE TITLE
Bibliography placement not working in v1.4

### ISSUE THREAD

**Issue by benjaminschlegel** [quarto-dev/quarto-cli#7432]
### Bug description

Since I installed v1.4 the placement of the bibliography doesn't work anymore. Before it worked with the following comment which is also stated in the Quarto documentation:

```
::: {#refs}
:::
```

### Steps to reproduce

````
---
title: "Title"
author: "Benjamin Schlegel"
format: 
  pdf:
    documentclass: scrreprt
bibliography: https://benjaminschlegel.ch/files/bibliography.bib
execute:
  echo: false
---

# Intro

@Kriesi2006 blablabla...

```{r}
# some R code for the appendix
```


# Bibliography

::: {#refs}
:::


# Appendix

```{r ref.label=knitr::all_labels()}
#| echo: true
#| eval: false

```
````

### Expected behavior

Bibliography should be printed at the place of:

```
::: {#refs}
:::
```

### Actual behavior

It gets printed at the end of the document after the appendix.

### Your environment

- IDE: 

RStudio 2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-05) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.0+421 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

- OS: Windows 11 Pro 22H2 22621.2506

### Quarto check output

$ quarto check
Quarto 1.4.460
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.460
      Path: C:\Users\benja\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\benja\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: C:/ProgramData/Anaconda3/python.exe
      Jupyter: 4.9.2
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 22, in <module>
    from IPython.core.application import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\__init__.py", line 52, in <module>
    from .terminal.embed import embed
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 73, in <module>
    from IPython.core.history import HistoryManager
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\history.py", line 11, in <module>
    import sqlite3
  File "C:\ProgramData\Anaconda3\lib\sqlite3\__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "C:\ProgramData\Anaconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: Das angegebene Modul wurde nicht gefunden.
(|) Checking Jupyter engine render....

Kernel died before replying to kernel_info
[>] Checking Jupyter engine render....OK

**Comment by cscheid** [comment]
This was closed by #7621.
