### ISSUE TITLE
Resource Path Issue

### ISSUE THREAD

**Issue by ollyhensby** [quarto-dev/quarto-cli#7434]
### Bug description

Rendering to PDF with a specified resource path doesn't appear to work as expected. I am specifying an image directory but I receive an error saying that the images cannot be located.

Quarto documentation referring to resource path parameter: https://quarto.org/docs/reference/formats/pdf.html#rendering

### Steps to reproduce

Here is a small demo I created and zipped up:

[quarto-cli-resource-path-issue.zip](https://github.com/quarto-dev/quarto-cli/files/13218507/quarto-cli-resource-path-issue.zip)

It contains a `document.md`, `images`, and `README.md`.

In here I am trying to render `document.md` as a PDF by running:

```bash
quarto render document.md --to pdf --resource-path=./images
```

The following error is returned:

```bash
compilation failed- error
Unable to load picture or PDF file 'radiator.jpg'.
<to be read again> 
                   }
l.172 }
```

Note that resource path works with pandoc

```bash
pandoc document.md --to pdf -o document.pdf --resource-path=./images
```

### Expected behavior

I expect the `--resource-path` parameter to be applied so that the images are located successfully, and the compilation to PDF is successful.

### Actual behavior

The compilation fails due to not being able to locate the images as the resource path is not applied.

### Your environment

- IDE: VSCode 1.83.1
- OS: Ubuntu 20.04

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.58.3: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /home/jovyan/mambaforge/envs/quarto-resource-path-issue/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by ollyhensby** [comment]
I also have just tried adding `resource-path` to the metadata however I received the same error.

```markdown
---
title: Resource Path Issue
author: Oliver Hensby
format:
    pdf:
        pdf-engine: xelatex
        resource-path: [./images]
---
```

**Comment by cderv** [comment]
@ollyhensby thanks for the report. I think `resource-path` is indeed not supported for PDF as of now... 

@dragonstyle Just to share that I had a look. `--resource-path` is correctly pass to the Pandoc command line  but I don't think we handle it correctly in our `pdfImages()` Lua function when handling mediabag. 

`pandoc.mediabag.fetch()` should handle the `resource-path` but not sure it pass, or maybe we do some check of file existence without considering the `resource-path`

**Comment by Reledia** [comment]
The same problem is still present in two cases (that I could find):
- export to html, both passing the path in the cli or in the metadata result into a "could not fetch resource" (even if it could with the export in pdf);
- passing the path in the metadata inside the `_quarto.yml` file under the `pdf` format. The project renders only if I pass it using the cli

**Comment by cderv** [comment]
@Reledia could you open a new issue (linking to this one for context) with some details about version used and examples ? 

This will be easier for us to look at. 

Thank you
