### ISSUE TITLE
Image Height Issue in Column Layout Div

### ISSUE THREAD

**Issue by ollyhensby** [quarto-dev/quarto-cli#7438]
### Bug description

Image height is not applied when using an image within column layout.

### Steps to reproduce

Here is a zip folder containing `document.md`, `document.pdf`, and `images` which demonstrates the issue:

[quarto-cli-height-issue.zip](https://github.com/quarto-dev/quarto-cli/files/13219428/quarto-cli-height-issue.zip)

Within the markdown, setting

```markdown
![Another radiator](images/radiator-2.jpg){height=30mm}
```

sets the height correctly when rendering to PDF.

However, trying to set the height when within a column layout does not work.

```markdown
::: {layout-ncol=2}
![Another radiator](images/radiator-2.jpg){height=30mm}

![Look at that, another radiator!](images/radiator-3.jpg){height=10mm}
:::
```

This behaviour can be seen in the rendered PDF.

### Expected behavior

I expect the heights of the images to be adjusted appropriately based on the height value passed

### Actual behavior

Currently the image height is not changed within a layout column div.

### Your environment

- IDE: VSCode 1.83.1
- OS: Ubuntu 20.04

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.58.3: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /home/jovyan/mambaforge/envs/quarto-resource-path-issue/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by mcanouil** [comment]
Thanks for the report.

Could you provide the reproducible example as plain text?

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by ollyhensby** [comment]
@mcanouil Thanks for the quick reply!

As requested:

````qmd
---
title: Image Height Issue in Column Layout
author: Oliver Hensby
format:
    pdf:
        pdf-engine: xelatex
---

## Some Images

![A flower](https://www.gstatic.com/webp/gallery3/1_webp_ll.png){height=30mm}

![A penguin](https://www.gstatic.com/webp/gallery3/2_webp_a.png){height=10mm}

::: {layout-ncol=2}
![A flower](https://www.gstatic.com/webp/gallery3/1_webp_ll.png){height=30mm}

![A penguin](https://www.gstatic.com/webp/gallery3/2_webp_a.png){height=10mm}
:::
````

PDF Output:

![image](https://github.com/quarto-dev/quarto-cli/assets/79875276/ab743cd3-918b-48d4-a029-382b9c0471fe)
![image](https://github.com/quarto-dev/quarto-cli/assets/79875276/652cb67a-aacb-4eff-a129-2941a8450b60)

The first page shows the images on their own. The second page shows the images within a layout column div.

**Comment by cscheid** [comment]
This has been fixed on 1.4 prereleases:

<img width="688" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/e5bb0db6-9dd2-4344-bffd-60211d7761a9">

**Comment by ollyhensby** [comment]
Perfect, thank you!

**Comment by ollyhensby** [comment]
@cscheid, which pre-release are you running to compile this successfully? 

I installed the latest pre-release and tried to run the above and got the following error:

```bash
ERROR: 
compilation failed- error
LaTeX Error: Not in outer par mode.
```

**Comment by mcanouil** [comment]
Did you try 1.4.466?

**Comment by ollyhensby** [comment]
I tried with `1.4.458` but I shall try `1.4.466` now and let you know.

**Comment by ollyhensby** [comment]
@mcanouil, that resolved the issue for me:

![image](https://github.com/quarto-dev/quarto-cli/assets/79875276/c491a0a0-ff33-41a3-a917-d5cbe66238be)

Thank you for resolving this so quickly!
