### ISSUE TITLE
Some elements of Observableplot not showing on Firefox

### ISSUE THREAD

**Issue by homerhanumat** [quarto-dev/quarto-cli#7440]
### Bug description

Some elements of an interactive Obervable plot are not showing, on the Firefox browser

### Steps to reproduce

See this URL:  [https://homerhanumat.github.io/test-ojs/articles/penguins/](https://homerhanumat.github.io/test-ojs/articles/penguins/)

At [this commit](https://github.com/homerhanumat/test-ojs/commit/f84a09ad01c0e220dd59a6a409988b7c2f71b321) all is well at the above URL.

At the [next commit](https://github.com/homerhanumat/test-ojs/commit/7201c17d507ee37d0d6dfdb2e8791bc8bd531efc) marks and axes do not appear, *on Firefox*.  On Google Chrome and Safari it is fine.

Other info (deducible from source code):

* importing the latest version of Plot
* only change was in the variable mapped to y-axis, plus some options for that axis

### Expected behavior

Plot at last commit should still show elements.

### Actual behavior

It does not.

### Your environment

* MacOS Monteray 12.7
* Quarto 1.3.450
* Firefox 119.0

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.1
      Path: /usr/local/opt/python@3.9/bin/python3.9
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by homerhanumat** [comment]
On my home computer now:  I can confirm that the issue manifest on a more recent MacOs version:  Ventura 13.5.2.  Also, adding the "bug" label was not meant to imply that it's a flaw in Quarto.  (Maybe the browser this time?)

**Comment by cscheid** [comment]
I think you might be running into a race condition with this statement:

```
race.forEach(function(runner) {runner.timeMinutes = runner.time / 60;})
```

You're mutating the elements in `race` in a way that isn't exactly compatible with ObservableHQ's reactivity. You should avoid doing that. It's probably going to be fruitful for you to go through the ObservableHQ's reactivity tutorials: https://observablehq.com/@observablehq/learning-observable-reactive-dataflow

**Comment by cscheid** [comment]
Yup, I can confirm that the following version works on all browsers:

````
---
title: "Another Test"
format:
  html:
    echo: false
    code-tools: true
---

```{ojs}
Plot = import("https://esm.run/@observablehq/plot")
```




```{ojs}
race = {
  const race = await FileAttachment("TenMileRace.csv").csv({typed: true});
  race.forEach(function(runner) {runner.timeMinutes = runner.time / 60;});
  return race;
}
```

```{ojs}
minTime = d3.min(d3.map(race, d => d.timeMinutes))
```

```{ojs}
maxTime = d3.max(d3.map(race, d => d.timeMinutes))
```

```{ojs}
minAge = d3.min(d3.map(race, d => d.age))
```

```{ojs}
maxAge = d3.max(d3.map(race, d => d.age))
```
    
    





```{ojs}
//| panel: input
viewof sex = Inputs.select(["F", "M"], {label: "Sex of runner: "})
viewof opacity = Inputs.range([0, 1], {label: "Opacity: ", step: 0.01})
```

```{ojs}
Plot.plot({
  inset: 8,
  grid: true,
  marks: [
    Plot.dot(
      d3.filter(race, d => d.sex == sex), 
      {x: "age", y: "timeMinutes", fill: "black", fillOpacity: opacity}
    )
  ],
  y: {label: "time (minutes)", domain: [minTime, maxTime]},
  x: {domain: [minAge, maxAge]}
})
```

````

**Comment by homerhanumat** [comment]
Yes, that worked.  Thanks, and sorry for the bother!  I'll check that reactivity reference.
