### ISSUE TITLE
multiples unwanted hyperlink icons in listing pages

### ISSUE THREAD

**Issue by wilcar** [quarto-dev/quarto-cli#7442]
### Bug description

My listings pages have unwanted hyperlinks all over the place.

![image](https://github.com/quarto-dev/quarto-cli/assets/18226229/970a04e7-9358-41c3-99a9-1fb7b6065f2c)

### Your environment

Quarto 1.3.450
RStudio 2023.09.1+494 "Desert Sunflower" Release (cd7011dce393115d3a7c3db799dda4b1c7e88711, 2023-10-16) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.09.1+494 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

**Comment by mcanouil** [comment]
Thanks for the report!

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by wilcar** [comment]
You will find a zip file on this repo :
https://github.com/wilcar/geomatique_historique/tree/bc8a51517f1153b142bedcfe571903003bb47bce

Everything in ok on preview but my I display the  _site version I have this issue.

**Comment by mcanouil** [comment]
Could you share the repository if you can't share code as shown and since you are using Git?

**Comment by wilcar** [comment]
Done !
https://github.com/wilcar/geomatique_historique.git

**Comment by mcanouil** [comment]
What we need is the source code.
See for example:
- https://github.com/mcanouil/quarto-issues/tree/main/quarto-cli-7185
- https://github.com/mcanouil/quarto-callouts-tabsets
- https://github.com/mcanouil/quarto-issue7231

**Comment by wilcar** [comment]
Done...
https://github.com/wilcar/geomatique_hist

**Comment by mcanouil** [comment]
Thanks.

FYI, there is a short code extension for Iconify, see <https://github.com/mcanouil/quarto-iconify>.

**Comment by mcanouil** [comment]
`index2.qmd` makes your example not work at all.
After removing it, I don't have any issues using the latest development version of Quarto.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/cd1304f3-2be1-4015-908f-aad5b0662b9f">

**Comment by wilcar** [comment]
I downloaded my files from github and builded the website.
When I open the website from the  _site directory I find the same issue

![image](https://github.com/quarto-dev/quarto-cli/assets/18226229/322f71ad-7170-449c-94d2-da57cb5a11b9)

**Comment by mcanouil** [comment]
Could you try using the pre-release?

**Comment by wilcar** [comment]
I used the 1.4.475 pr with success. The issue is solved with this version.
