### ISSUE TITLE
$navbar-bg no longer defaulting to $primary in v1.4.455

### ISSUE THREAD

**Issue by EllaKaye** [quarto-dev/quarto-cli#7447]
### Bug description

The `$navbar-bg` colour no longer defaults to `$primary` in the pre-release (v1.4.455). This behaviour is different than in the current release, where it does default to `$primary`. 

I'm not sure if this is a bug or a deliberate design decision change. The documentation still states that [$navbar-bg should default to $primary](https://quarto.org/docs/output-formats/html-themes.html#navigation), though the documentation is of course for the current release not the pre-release. If it is a deliberate change, I don't see it listed on the pre-release notes (unless I'm missing something).

### Steps to reproduce

See <https://github.com/EllaKaye/navbar-bug> and the corresponding site at <https://ellakaye.github.io/navbar-bug/>.

This is created by starting a new Quarto website project within RStudio, then adding a `custom.scss` file with

```
/*-- scss:defaults --*/
$aubergine: #552D62;
$primary:   $aubergine !default;
```

and linking to it appropriately in `_quarto.yml`:
```
format:
  html:
    theme: [cosmo, custom.scss]
```

### Expected behavior

The navbar should default to the primary colour (aubergine).

Explicitly adding `$navbar-bg: $primary;` does change the colour.

### Actual behavior

The navbar remains the default colour for the `cosmo` theme, not the custom theme. If I remove cosmo from the theme listing, the navbar defaults to blue (also not in `custom.scss`!)

The link colour on the site is `$primary`, so the theme is getting picked up elsewhere.

### Your environment

- IDE: RStudio 2023.09.1+494
- MacOS: Ventura 13.6

### Quarto check output

```bash
Quarto 1.4.455
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.455
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.11
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/u2175871/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources
      LibPaths:
        - /Users/u2175871/Library/R/arm64/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
I think this is a matter of order. We are doing the creation of hover box with tippy before we research the links to add the icon. 

If we do the external link processing before, this would work. I don't think this would have some bad effect. 

@dragonstyle I can do a PR, but probably worth your thoughts before merging... 🤔
