### ISSUE TITLE
Windows-specific OS error 123 when URL is interpreted as local path

### ISSUE THREAD

**Issue by martinfleis** [quarto-dev/quarto-cli#7448]
### Bug description

I have encountered a strange error. When trying to use `quarto render` on Windows, I hit an error using a qmd which, when executed via Jupyter normally works as expected. I wasn't able to isolate the issue to a minimal example as the cell that I suppose causes it works when I leave only that one in the qmd.

### Steps to reproduce

The whole source is available https://github.com/martinfleis/sds/blob/main/chapter_10/hands_on.qmd with the specification of Jupyter kernel living at https://github.com/martinfleis/sds/blob/main/environment.yml.

The error was caught by CI, so you can check the error logs yourself https://github.com/martinfleis/sds/actions/runs/6730344861/job/18292878261

As mentioned, I wasn't able to get a minimal qmd because it always worked with that one... So I am not certain where the issue is but from the log it seems that the notebook correctly executes and the issue comes after from `quarto`.

### Expected behavior

It should work as it does on Linux and macOS.

### Actual behavior

The process fails with:

```
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'D:\a\sds\sds\chapter_10\"https:\martinfleischmann.net\sds\chapter_10\data\education.csv"'

Error: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'D:\a\sds\sds\chapter_10\"https:\martinfleischmann.net\sds\chapter_10\data\education.csv"'
    at Object.lstatSync (deno:runtime/js/30_fs.js:305:9)
    at existsSync (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:492:14)
    at inputTargetIndex (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:83490:10)
    at resolveInputTarget (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:83583:25)
    at file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:93022:55
    at async file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:81203:33
    at async withTimingAsync (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:19633:25)
    at async runHtmlPostprocessors (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:81196:9)
    at async Object.complete (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:81073:43)
    at async Object.onPostProcess (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:86678:36)
```

### Your environment

- OS Windows (windows-latest runner on GitHub Actions and Win 10 locally)
- IDE irrelevant, the issue comes from CLI
- Quarto 1.3.450

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Users\runneradmin\scoop\apps\quarto\current\bin
      CodePage: unknown
(|) Checking basic markdown render....
[>] Checking basic markdown render....OK
(|) Checking Python 3 installation....
[>] Checking Python 3 installation....OK
      Version: 3.11.6 (Conda)
      Path: C:/Users/runneradmin/micromamba/envs/sds/python.exe
      Jupyter: 5.5.0
      Kernels: python3, sds
(|) Checking Jupyter engine render....0.02s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

[>] Checking Jupyter engine render....OK
(|) Checking R installation...........
[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Program Files/R/R-4.3.1/library
      knitr: (None)
      rmarkdown: (None)
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by cscheid** [comment]
> ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'D:\a\sds\sds\chapter_10\"https:\martinfleischmann.net\sds\chapter_10\data\education.csv"'

The error is coming from the double quotes there. We need to understand what's causing those to appear.

**Comment by martinfleis** [comment]
> do you have filenames with backslashes in their names, on windows? I cannot imagine that's a good idea.

nope. That happened somewhere out of my reach. This is the source code https://github.com/martinfleis/sds/blob/68ab2f39f27f0d588a3463ac94735b486dbd5a53/chapter_10/hands_on.qmd#L71

**Comment by mcanouil** [comment]
Did you try those lines in a Jupyter Notebook or in Python REPL directly?

**Comment by martinfleis** [comment]
Yes, it works as expected. The whole notebook runs without any issues. Only when executing it using `quarto render` I hit this issue. If you check the log, it also shows that the error does not come from Python while executed the cell but from some process that comes after.

**Comment by cscheid** [comment]
> > do you have filenames with backslashes in their names, on windows? I cannot imagine that's a good idea.
>
> nope. That happened somewhere out of my reach. This is the source code https://github.com/martinfleis/sds/blob/68ab2f39f27f0d588a3463ac94735b486dbd5a53/chapter_10/hands_on.qmd#L71

Ok. So _we_ create filenames with backslashes in their names, on windows. I cannot imagine that's a good idea! :) Thanks for the report again, we'll get to the bottom of it.

**Comment by cderv** [comment]
> ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'D:\a\sds\sds\chapter_10"https:\martinfleischmann.net\sds\chapter_10\data\education.csv"'

I don't think this is a double quotes or backslash issue here - we are finding something a resource as a URL and we are trying to build an absolute path from it. Obviously appending a url to a filepath does not play well with `existSync()` which on Windows will **always** error. While on Linux, it will just return FALSE (which do not error but hide the underlying pass issue). 

(TBH We may construct invalid path on purpose by expecting `existSync()` to return FALSE, which do no happen on Windows)

@martinfleis are you able to try the Quarto 1.4 pre-release ? I remember we dealt with stuff like this. I'll try to find it but if you could run your CI with latest pre-release that would help confirm this is fixed.

**Comment by cderv** [comment]
> I'll try to find it but if you could run your CI with latest pre-release that would help confirm this is fixed.

And this is where I think it has been fixed in 1.4: https://github.com/quarto-dev/quarto-cli/commit/df1c25c99037ae2d7bd02974aef3e7f30c3e6651

I am waiting for confirmation on your side before closing

**Comment by martinfleis** [comment]
Yay! Can confirm locally that this is fixed. The Github action has just started but I don't expect any difference. Sorry for not testing on pre-release in the first place!

**Comment by cderv** [comment]
No problem ! Always happy to get reports anyway. Sure it is better to test with dev version if you can, but it is not always easy. 

I'll close this now.
