### ISSUE TITLE
Switching from source to visual editor breaks bib key linkage

### ISSUE THREAD

**Issue by quinfer** [quarto-dev/quarto-cli#747]
When I switch from source to visual editor in RStudio, my bib keys loose their linkage to the .bib file, and upon rendering they references are not capture in the output.  I am not sure if this is a bug or it is my inappropriate usage.

**Comment by jjallaire** [comment]
If you could provide a sample file that exhibits this behavior that would be great. We did just fix a couple of bugs in the visual editor where it would inappropriately escape the citation brackets (e.g. `\[@foo\]`). If you are seeing this behavior you might first try the very latest release of RStudio as it may fix the problem. If it doesn't post a version of the document that you are seeing the behavior with (ideally as minimal as possible so that we can open/render it)

**Comment by quinfer** [comment]
Are there plans to update the workbench IDE or is this a rabbit hole for another issue thread?

**Comment by jjallaire** [comment]
It's should be in the most recent patch release of RStudio 2022.02 (https://www.rstudio.com/products/rstudio/release-notes/). That said, perhaps the patch with this fix hasn't gone out yet?

**Comment by jjallaire** [comment]
Let me make sure though that the patch release out now actually has this fix...

**Comment by quinfer** [comment]
Thanks I will keep an eye out

Barry Quinn CStat | Lecturer of Financial Technology and Data Science | Director -MSc Quantitative Finance | Queen’s Management School | ***@***.*** | +44  0 28 9097 4824 | https://quinference.com |

[X][X]

On 27 Apr 2022, at 18:29, J.J. Allaire ***@***.***> wrote:

﻿
This message is from an external sender. Please take care when responding, clicking links or opening attachments.

The PT patch is going out in the next day or two. This daily build will likely be what we actually release: https://dailies.rstudio.com/version/2022.02.2+485.pro2/<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdailies.rstudio.com%2Fversion%2F2022.02.2%2B485.pro2%2F&data=05%7C01%7Cb.quinn%40qub.ac.uk%7C1e596193bc0342514ac708da28736d29%7Ceaab77eab4a549e3a1e8d6dd23a1f286%7C0%7C0%7C637866773468034102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BJvMEvFwHjL5lj5%2FPOjkGqClHZmwKQ%2Bm4AgbSYT0BMg%3D&reserved=0>
