### ISSUE TITLE
Quarto unable to find R if located on path with non-ASCII characters

### ISSUE THREAD

**Issue by sda030** [quarto-dev/quarto-cli#7473]
### Bug description

A colleague with a non-ascii character in his username has R installed in "c:\users\Ørjan\appdata\Local\Programs\R"
Rendering of R-chunk errors with
```bash
ERROR: Error executing 'C:\Users\�rjan\AppData\Local\Programs\R\R-4.3.2\bin\x64\Rscript.exe': Systemet finner ikke angitt bane. (os error 3)
Unable to locate an installed version of R.
Install R from https://cloud.r-project.org/
```
R works perfectly fine elsewhere, and Quarto renders if not containing any R chunks. We tried to install R in regular Program Files path but some strange admin rights are missing so not an option for now. Other colleagues (and I) have no problems, and we also have no non-ascii characters in our R paths. Sos suspecting his "Ø" in the path. Related to #4956.

NOTE: Although I suspect Quarto has the bug, I am open for the idea that there is something strange in the RStudio locale setup for Norwegian, as all my Norwegian colleagues have needed to set LC_ALL="nb.utf8" for non-ascii characters to work - despite R 4.2 supposedly having made everything utf8 default (https://github.com/rstudio/rstudio/issues/12668). 

### Steps to reproduce

`````qmd
---
format: html
---

# Regular text works

```{r}
1+1 # R chunk fails
```
`````

### Expected behavior

No error.

### Your environment

Operating system: Windows 11
R-path: 'C:\Users\Ørjan\AppData\Local\Programs\R\R-4.3.2\bin\x64\Rscript.exe' 
``` powershell
[System.Text.Encoding]::Default.EncodingName
Vesteuropeisk (Windows)
```
``` powershell
Get-WinSystemLocale | Select-Object Name, DisplayName, 
                        @{ n='OEMCP'; e={ $_.TextInfo.OemCodePage } }, 
                        @{ n='ACP';   e={ $_.TextInfo.AnsiCodePage } }
```
``` powershell
Name  DisplayName            OEMCP  ACP
----  -----------            -----  ---
nb-NO Norsk (bokmål) (Norge)   850 1252
```

```r
Sys.getenv("LC_ALL") # Note that this must be set to nb.utf8, otherwise we are unable to even run the string "øæå" to the console.
"nb.utf8"
```

### Quarto check output

``` bash
Quarto 1.4.468
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.468
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252
 
[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)
 
[>] Checking LaTeX....................OK
      Tex:  (not detected)
 
[>] Checking basic markdown render....OK
 
[>] Checking Python 3 installation....(None)
 
      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/
 
[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/ØrjanArnevigSamuelse/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25
 
[>] Checking Knitr engine render......OK
```

**Comment by schwa021** [comment]
I am not sure if this is the same/related problem...

I am working through the Quarto dashboard tutorial. I am trying to run the example with a shiny server

The example that starts with...

```
---
title: "Diamonds Explorer"
author: "Barkamian Analytics"
format: dashboard
1server: shiny
---
```

My organization has an apostrophe in its name (e.g., Children'sHospital)

When I click the "Run Document" button, nothing happens, and there is an error message:

> Error: unexpected symbol in "})('C:/Users/myname/OneDrive - Children\'sHospital/Test.qmd', shiny_args = list(launch.browser = FALSE), auto_reload = "
> Execution halted

If, instead, I run it from the terminal: `quarto serve Test.qmd` it runs succesfully (though not in my viewer, I need to click a link to a local server http::blahblah

**Comment by cderv** [comment]
> When I click the "Run Document" button, nothing happens, and there is an error message:

This would be something to report to RStudio IDE as they are building the command your see in the error message
```` 
Error: unexpected symbol in "})('C:/Users/myname/OneDrive - Children'sHospital/Test.qmd', shiny_args = list(launch.browser = FALSE), auto_reload = "
````

Also, I see `OneDrive` in the path, and this could cause issue. Quarto and RStudio could have trouble working from remote directory which is synced live. 

Anyhow, you should report to https://github.com/rstudio/rstudio by providing detailled context about the situation

> I am not sure if this is the same/related problem...

Usually in this case, it is best to open a new issue and link to the other so that thread are separated and possibly different topic (like here)  are mixed.

**Comment by sda030** [comment]
> Also, I see OneDrive in the path, and this could cause issue. Quarto and RStudio could have trouble working from remote directory which is synced live.

@cderv, I can falsify the hypothesis that OneDrive in itself is a general problem. I use OneDrive and Sharepoint extensively with R/Quarto and only face (typical Windows) issues if the paths exceed 260 characters (or of course if one forgets to have OneDrive app on and syncing, or a very slow connection).

**Comment by schwa021** [comment]
> > When I click the "Run Document" button, nothing happens, and there is an error message:
> 
> This would be something to report to RStudio IDE as they are building the command your see in the error message
> 
> ```
> Error: unexpected symbol in "})('C:/Users/myname/OneDrive - Children'sHospital/Test.qmd', shiny_args = list(launch.browser = FALSE), auto_reload = "
> ```
> 
> Also, I see `OneDrive` in the path, and this could cause issue. Quarto and RStudio could have trouble working from remote directory which is synced live.
> 
> Anyhow, you should report to https://github.com/rstudio/rstudio by providing detailled context about the situation
> 
> > I am not sure if this is the same/related problem...
> 
> Usually in this case, it is best to open a new issue and link to the other so that thread are separated and possibly different topic (like here) are mixed.

Damned if you do, damned if you don't.

I have been scolded for starting new issues when related ones are open.

I'll put it over on Rstudio as you suggested. It's clearly the apostrophe (not OneDrive) causing the problem.

**Comment by cscheid** [comment]
Both of the issues described here seem to be specific to RStudio, and go away when `quarto render` or `quarto serve` is used on the command line. I'm going to go ahead and close the issue here, and encourage you to file them at the appropriate repo: https://github.com/rstudio/rstudio
