### ISSUE TITLE
Page breaks via {{< pagebreak >}} do not create page breaks in rendered docx files

### ISSUE THREAD

**Issue by pcdx0** [quarto-dev/quarto-cli#7476]
### Bug description

Page breaks via {{< pagebreak >}} do not create page breaks in the created DOCX files. However, {{< pagebreak >}} is working as expected for PDF targets.

### Steps to reproduce

Use {{< pagebreak >}} in a qmd-file and render it to the docx format without using a DOCX template file. 
The created DOCX file will not contain any page breaks.

### Expected behavior

Page breaks via {{< pagebreak >}} work as documented for DOCX file targets.
See https://quarto.org/docs/authoring/markdown-basics.html#page-breaks .

### Actual behavior

The produced DOCX file does not contain any page breaks.

### Your environment

- RHEL7.9
- Quarto 1.4.480 

### Quarto check output

Quarto 1.4.480
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.480
      Path: .../quarto-1.4.480/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: .../x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: .../bin/python
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by mcanouil** [comment]
What is you use `\newpage` instead of the shortcode?

**Comment by pcdx0** [comment]
Unfortunately, neither `\newpage` nor `\pagebreak` work. Adding empty lines above and below `\newpage`, `\pagebreak` or {{< pagebreak >}} does not help as well.

**Comment by mcanouil** [comment]
I cannot reproduce with the latest development version and I don't believe there was any changes regarding this.

<img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/eb80868c-65ea-4e75-bcab-51108b81c59e">

**Comment by pcdx0** [comment]
@mcanouil: 
Thank you for your tests with a plain environment. 
I was able to fix this problem and a seemingly unrelated cross-ref problem for docx targets by moving the quarto project type declaration to the top of the _quarto.qmd file. 

This order in the _quarto.qmd file **SOLVED** the reported problem(s):

**project:
     type:                     book**

date:                       2023-11-02  
date-modified:         today
from:                       markdown+emoji  

header-center:         ""
titlepage:                  true
titlepage-logo:             mypic.png
toc:                        true
toc-depth:                  2
toc-own-page:               true
toc-title:                  "Table of Contents"
number-sections:            true
number-depth:               4
...

This order in the _quarto.qmd file **CAUSED** the reported problem(s):

date:                       2023-11-02  
date-modified:         today
from:                       markdown+emoji  

header-center:         ""
titlepage:                  true
titlepage-logo:             mypic.png
toc:                        true
toc-depth:                  2
toc-own-page:               true
toc-title:                  "Table of Contents"
number-sections:            true
number-depth:               4

**project:
    type:                     book**
...

**Comment by cderv** [comment]
> by moving the quarto project type declaration to the top of the _quarto.qmd file.

Do you mean `_quarto.yml` ?

**Comment by mcanouil** [comment]
Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

I played around and moving the elements in the YAML and cannot reproduce at all.
Also, it seems very odd that the order matters in the YAML.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by pcdx0** [comment]
Despite my previous long-standing troubles I was not able to reproduce the issue after changing the location of the project type back and forth. I suggest to close the item.
