### ISSUE TITLE
Sharing language specific objects in single `.qmd`?

### ISSUE THREAD

**Issue by hathawayj** [quarto-dev/quarto-cli#749]
Is there or will there be the ability to pass objects between R, Python, Observable?

Specifically, I would like to use Python or R to manipulate data and then use an observable plot in a different chunk.

Here is a description of what is available in `.Rmd` - https://rpubs.com/keithmcnulty/r_and_python.

**Comment by hathawayj** [comment]
Thanks!

**Comment by niniack** [comment]
It seems like the `ojs_define()` is not available to python when using the knitr engine. I get the following error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  NameError: name 'ojs_define' is not defined
Calls: .main ... py_capture_output -> force -> <Anonymous> -> py_call_impl

Execution halted
```

This is fixed if I set `jupyter: python3` in the YAML frontmatter

**Comment by jjallaire** [comment]
That's correct, we don't currently support ojs_define from reticulate.
