### ISSUE TITLE
Custom layout with single figure results in panel layout with no content

### ISSUE THREAD

**Issue by e-miz** [quarto-dev/quarto-cli#7494]
### Bug description

I noticed there's a lot of issues with layouts and figures; this one seems a bit unique so I'm adding it.

Specifying a custom layout in a figure div with only one figure results in a warning:

```ascii
WARNING (/opt/quarto/share/filters/main.lua:15323) Panel layout for fig-1 has no content
```

And the entire figure is absent from the document.

Adding a _second_ "dummy" figure to the figure div seems to "fix" this problem, although that's not a workaround; just relevant information.

This issue was not present in 1.4.63, but is present in 1.4.480.

### Steps to reproduce

Reproducer:

```qmd
---
title: Test Doc
author: Eli Mizrachi (they/them)
format: 
    html: default
---

::: {#fig-1 layout="[-15,70,-15]"}

::: {.figure-content}
This is my figure!
:::

:::
```

Adding a second figure fixes the warning:

```qmd
::: {#fig-1 layout="[-15,70,-15]"}

::: {.figure-content}
Test Figure
:::

::: {.figure-content}
Second Figure
:::

:::
```
Both figures show up and no warnings are emitted.

### Expected behavior

`layout` should work with one figure, instead of needing a second "dummy" figure.

Some imperfect workarounds:

Removing the cross reference works as expected:

```qmd
::: {layout="[-15,70,-15]"}

::: {.figure-content}
Test Figure
:::

:::
```

Cross-ref _inside_ of the layout div works as expected:

```qmd
::: {layout="[-15,70,-15]"}

::: {#fig-1}

::: {.figure-content}
Test Figure
:::

:::

:::
```

### Actual behavior

A warning is emitted when only one figure is present, and no content is emitted.

### Your environment

IDE: VSCode 1.84.0
OS: Windows 10 / WSL2 Ubuntu 20.04.6 LTS

### Quarto check output

```bash
Quarto 1.4.480
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.480
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.10
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/emiz/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /home/emiz/miniconda3/envs/sv_SEDecayTime/bin/python
      Jupyter: 5.4.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
I believe the issue is that you combine two different things within the new cross-reference system, i.e., the following will work as expected.

````qmd
---
title: Test Doc
format: html
---

::: {#fig-1}

::::: {layout="[-15,70,-15]"}

:::: {.figure-content}
Test Figure
::::

:::::

:::
````

**Comment by cscheid** [comment]
Thanks for the report! @mcanouil's workaround should get you sorted out for the time, but I think your syntax should still work.

**Comment by mcanouil** [comment]
Note that the issue is for all `layout*` options/specification.

**Comment by e-miz** [comment]
Thanks for the quick response! I just tried @mcanouil's example and it does work for HTML. However it unfortunately doesn't work for latex/pdf output--I get the dreaded `not in outer par mode` error. I apologize I didn't specify this use case in my initial report.

I do have some good news news though: this is an issue for _only_ one figure. More than one figure does not cause any problems, e.g.

```qmd
::: {#fig-1 layout="[50,50]"}

::: {.figure-content}
Test Figure
:::

::: {.figure-content}
Second Figure
:::

:::
```

works fine, which is good because this is a more general case that extends to n > 1 figures.

So for now I'll be sticking with the layout outside of the figure div approach, i.e.

```qmd
::: {layout="[-15,70,-15]"}

::: {#fig-1}

::: {.figure-content}
Test Figure
:::

:::

:::
```

when I have _only_ one figure that needs resizing in both latex and html.

**Comment by mcanouil** [comment]
The other issue raised here seems to be an edge case of #7262.
Although, why use layout for one figure?
The correct and more obvious method would be to set width for the figure.

**Comment by e-miz** [comment]
That's a fair question, and maybe I'm missing something. Let me elaborate:

In my workflow I have a lot of jupyter cell embeds across multiple documents. It's a bit too restrictive to set `fig-width` in the cell since I might need to size the figure differently in different documents.

So a lot of my figures look like this:

```qmd
::: {#fig-1 layout="[-15,70,-15]"}
{{< embed nb1.ipynb#out1 >}}
:::
```

Basically I want to keep my cell outputs as generic as possible (typically I only specify a cell label) because I can't predict how I might use them future documents. So I manipulate the outputs by toying with the div instead of the cell directly.

If I was only using HTML then I would set the div width with `style="width: 70%"` but that doesn't work for latex output.

I'm open to suggestions though if you have ideas on how to improve this!

**Comment by cscheid** [comment]
> It's a bit too restrictive to set fig-width in the cell since I might need to size the figure differently in different documents.

I just want to point out that this currently is a real shortcoming of the way jupyter cell embeds work on Quarto. I have no good suggestion on how to solve it, but I wanted to acknowledge the issue.
