### ISSUE TITLE
Thesis no longer rendering to PDF in v1.4

### ISSUE THREAD

**Issue by EllaKaye** [quarto-dev/quarto-cli#7499]
### Bug description

I wrote my thesis as a Quarto book. Under the current release, it renders without a problem. Since updating to the pre-release (v1.4.487), it no longer compiles. I get the message

```
ERROR: 
compilation failed- error
Too many }'s.
l.361 contents}
```

I'm not sure why I'd get that error under v1.4 when it's fine under v1.3.

### Steps to reproduce

I'm really sorry, but I haven't been able to create a minimal reproducible example for this. My thesis is big and, for various reasons, I cannot make the source code public. I've tried stripping it back in various ways, but haven't been able to reproduce the bug. Would you be able to guide me on some useful things to try that might help you narrow down what's going on here? (I could temporarily make a member of the Quarto team a collaborator in the private thesis repo to see how the thesis is set up, but they wouldn't be able to compile the thesis because it relies on sensitive data in a private R package).

### Expected behavior

My thesis should render without issue.

### Actual behavior

My thesis fails to render.

### Your environment

- IDE: RStudio 2023.09.1+494
- macOS 14.1

### Quarto check output

```bash
Quarto 1.4.487
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.487
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/ellakaye/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources
      LibPaths:
        - /Users/ellakaye/Admissions_project/student-trajectories-thesis/renv/library/R-4.2/aarch64-apple-darwin20
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.40
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
The cross-reference system had a major refactoring to improve it.
See <https://quarto.org/docs/prerelease/1.4/crossref.html>.

Very likely to be related to your cross-reference content.

Note that without the means to reproduce or look at the source code, there is nearly no way to tell you which part of your document is faulty under the new cross-reference system or if it is indeed a Quarto bug/regression.

**Comment by EllaKaye** [comment]
Thanks @mcanouil. I'll take a look at the cross-refs. That's a helpful place to start, and thank you also for your tip r.e. `keep-tex`. Hopefully then I'll be able to narrow down on the problem and report back with a proper reprex. Iteratively will definitely help - there are an awful lot of cross-refs to check!

**Comment by cderv** [comment]
The error log shows this 

> ```
> l.361 contents}
> ```

If you can indeed find in your `.tex` file which TeX content it is, and which .qmd content it is related too, you may indeed be able to narrow done and reproduce. 

By configuring the render target, you can also easily render your book with only a subset of chapters: https://quarto.org/docs/projects/quarto-projects.html#render-targets

Hopefully, you'll manage to find what is the culprit, as we would like to know about this regression ! 😅 

At last resort, using a tool like [**qvm**](https://github.com/dpastoor/qvm) that allows installing many Quarto version, it would be possible to do a bisect search to find the version that creates the issue (starting for latest 1.3 that works). But it is quite time consuming, though efficient. (Using quarto dev version, with `git bisect` is also an option) 

Hope it helps

**Comment by EllaKaye** [comment]
Right, I've dug down a lot and I think I've figured out where the issue is appearing, though I still haven't been able to reproduce it in a reprex. A key bit of information that I forgot to mention in the initial report is that I'm using the [titlepage](https://nmfs-opensci.github.io/quarto_titlepages/) extension. When I render to standard pdf format, it still works under v1.4. 

With the titlepage extension inside my thesis repo, I'm seeing this in my kept `index.tex`:

```
%%%%% end titlepage extension code\renewcommand*\contentsname{Table of
contents}
```

In particular, `contents}` is on its own line, which is where the extra `}` is being found, whereas there should be a line break after `%%%%% end titlepage extension code`.

I can't seem to reproduce this. I've figured out that the error occurs just from my front-matter (without any sensitive code or content), so I've created a repo with a minimal version of that: <https://github.com/EllaKaye/book-bug>. However, the equivalent line in `book-bug.tex` is

```
%%%%% end titlepage extension code
\renewcommand*\contentsname{Table of contents}
```

There, the line break is where it is supposed to be, and no error occurs, even in v1.4.

Another thing I've noticed, and I don't know if this is the problem or a red herring, is that when I'm working in my thesis directory and watching the console, I see the following just before the error occurs:

```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
Too many }'s.
```

In contrast, when working in the book-bug project, I get

```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
running xelatex - 2
```

i.e. it doesn't try to update `tlmgr` or existing packages. Could that be part of the issue or a key to the solution?

Thank you for your interest in this. It doesn't actually make much difference to me - my thesis has just passed and all I need to do is print out a copy for the library, which I can easily do from v1.3 or the PDF I already have - but I figured this might be indicative of a wider bug, hence reporting it.

**Comment by mcanouil** [comment]
Hum, with what you said, I wonder if it is not related to:
- #7293

**Comment by EllaKaye** [comment]
@mcanouil agreed, that does seem to be a very similar issue. Thanks for making the connection. Though I'm stiff confused about why I'm getting the bug in my thesis and not in my attempt at a reprex.

**Comment by cderv** [comment]
> Though I'm still confused about why I'm getting the bug in my thesis and not in my attempt at a reprex.

Just in case, this bug is known and even reported in 
* https://github.com/nmfs-opensci/quarto_titlepages/issues/47

And there has been a commit there to "fix" the issue  (https://github.com/nmfs-opensci/quarto_titlepages/commit/876d8f0a2e3064218127402f4cd329c5ff34deb2) 

So if you are attempting a reprex by creating a new project and adding the extension, you will get the new version with the fix. 
And in your project, you may still be using the version of the extension without the fix. 

The version of the extension was not updated though, so [`quarto update`](https://quarto.org/docs/extensions/managing.html#updating) does not work, you may need to add the missing newline directly in the file in the `_extension` folder.

**Comment by EllaKaye** [comment]
> So if you are attempting a reprex by creating a new project and adding the extension, you will get the new version with the fix. And in your project, you may still be using the version of the extension without the fix.

Thanks @cderv - so obviously once you say it!

Yes, it was that titlepage issue that was the cause of the problem. Thank you so much @mcanouil and @cderv for helping me get to the bottom of it (and apologies for getting you involved before it occurred to me to search in the quarto-cli or titlepage issues pages for this exact thing that had already been solved).
