### ISSUE TITLE
Advice for formatting according to output

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#75]
Can I ask for advice about how to replicate some formatting we developed in Bookdown?

We were using the `kableExtra` package to tweak the formatting of tables, so it differed in HTML and PDF output.  Specifically, we were using a custom table output function like this:

```
﻿﻿ketable <- function(df, caption) {
    rt <- kableExtra::kable(df, caption = caption, booktabs = T)
    if (knitr::is_latex_output()) {
        return(kableExtra::kable_styling(rt, latex_options = 'scale_down'))
    }
    # See https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html
    # Update table-style.html to match
    kableExtra::kable_paper(rt,
                            lightable_options = c("striped", "hover"),
                            latex_options = c("striped", "scale_down"),
                            full_width = F,
                            position = "center"
    )
}
```

with some custom CSS to make our HTML tables look nice.  Is there an equivalent way to tweak table formatting in Quarto?   How can we make it differ according to output format (HTML or PDF)?

**Comment by jjallaire** [comment]
You should be able to use exactly the same code assuming you are in a Knitr engine document (LMK if you can't).

If you are in a plain markdown or Jupyter document things are trickier. In Python I know for sure there is no equivalent to kable (you would need to build something on top of the IPython package that generates LaTeX and HTML -- e.g. see https://quarto.org/docs/computations/running-code.html#jupyter). Although that's something we might be working on soon.

In plain markdown you need to this sort of heavy lifting in Lua Filters (see https://quarto.org/docs/authoring/shortcodes-and-filters.html#filters). But again that's quite a bit of engineering to replicate something you've already got in kableExtra, etc. 

Over time we would definitely like to replicate many of these capabilities in a cross-language fashion but for now sticking to tried and true R packages that generate raw output is probably the best way.

**Comment by matthew-brett** [comment]
Thanks for the discussion - I am getting a better feel for the architecture.

For the particular case though - in HTML, we are getting no table, and stray Markdown, for the output of `kableExtra::kable_styling`.  The PDF output is correct.

Have a look at <https://github.com/matthew-brett/qbt>, and in particular, at <https://github.com/matthew-brett/qbt/blob/main/_book/intro.html> - generated from `quarto render`.  It contains the following rendered in HTML, instead of the table:

~~~
```{=html} 
~~~

The `rmarkdown::render` output is in <https://github.com/matthew-brett/qbt/blob/main/rmintro.html> - that is what we were expecting.

**Comment by jjallaire** [comment]
Okay, that's definitely a bug as well. Investigating now.

**Comment by jjallaire** [comment]
It looks like `kableExtra::kable_styling` is parsing the results of `kable_html` with an XML parser (not an unreasonable thing to do). This however confounds our attempt to enclose the HTML in a pandoc raw block. I've modified this behavior here (https://github.com/quarto-dev/quarto-cli/commit/df23641ec5e8e686a860c6b9514076e37f1a464f) so your example now works correctly.

**Comment by matthew-brett** [comment]
Thanks for that - yes - it works correctly now.

**Comment by matthew-brett** [comment]
Oops - I now see that I cannot reference the table label embedded in the table caption, with kableExtra.  Is this what you expected?   Specifically, for this markup:

~~~
```{r, echo=FALSE}
knitr::kable(df, caption = "A caption {#tbl-my-kable}")
```

See @tbl-my-kable for a Kable table.

```{r, echo=FALSE}
kableExtra::kable(df, caption = "A caption {#tbl-my-kekable}")
```

See @tbl-my-kekable for a Kable Extra table.
~~~

the first reference `@tbl-my-kable` references correctly, and removes the embedded lable, but the second `@tbl-my-kekable` does neither.

Example files in <https://github.com/matthew-brett/qbt/tree/main>, and particularly <https://github.com/matthew-brett/qbt/blob/main/_book/intro.html>.

**Comment by jjallaire** [comment]
That is one thing that I feared would occur (as we are perhaps now not able to see the table HTML in our pandoc filter). Let me investigate further.

**Comment by jjallaire** [comment]
Okay, here is a fix that adds the ```` ```{=html} ```` a bit later in the pipeline: https://github.com/quarto-dev/quarto-cli/commit/d73cf5a45f6f825f303bddb0fc4dd0dbe49715a3

**Comment by matthew-brett** [comment]
Thanks - yes - that fixes the example - but if I then wrap the table thus, the referencing fails again:

~~~
```{r, echo=FALSE}
kt <- kableExtra::kable(df,
    caption = "A caption {#tbl-my-fkekable}")
kableExtra::kable_styling(kt, latex_options = 'scale_down')
```

See @tbl-my-fkekable for a formatted Kable Extra table.
~~~

<https://github.com/matthew-brett/qbt>

**Comment by jjallaire** [comment]
Thanks again for your patience and diligence! This should do the trick: https://github.com/quarto-dev/quarto-cli/commit/b5949614040c904698a0f3f6c160bad09d2ad7b3

**Comment by matthew-brett** [comment]
Yes!  Thanks - that works.
