### ISSUE TITLE
combine visual plot output of both python and R chunks

### ISSUE THREAD

**Issue by quinfer** [quarto-dev/quarto-cli#750]
Hi, I have a .qmd document which have both R and Python plotting output chunks.  When rendering the R plots come out fine but the python plots do not appear.  I have attached a repex of my issue
[test.qmd.zip](https://github.com/quarto-dev/quarto-cli/files/8581540/test.qmd.zip)
.
My computing environment is
RStudio 2022.06.0-daily+333 "Spotted Wakerobin" Daily (222a55f07242ae455bf0a79b44d4ff729a346568, 2022-04-26) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_1_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

**Comment by jjallaire** [comment]
I've run the test.qmd file on both OSX and Linux and I do see the plot appearing (although on OS X I see a terminal window briefly flashing open on the dock -- to me this implies that some external library e.g. X11 is being utilized by plotnine and perhaps this isn't available on your system?)

**Comment by quinfer** [comment]
That is strange as I do have XQuartz installed. At least it is not a quarto issue so thanks for checking @jjallaire. I have a linux machine which I will try and run it on later.

**Comment by quinfer** [comment]
So I am still getting this behaviour on Linux, but I think the error I am getting reveals my issues.  

_Quitting from lines 38-41 (test.qmd) 
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ModuleNotFoundError: No module named 'pandas'

Detailed traceback:
  File "<string>", line 1, in <module>
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
Calls: .main ... py_capture_output -> force -> <Anonymous> -> py_call_impl`_

It looks like quarto ,as I have set it up, is using reticulate to run my python codes.  Is there something I missed in this set up?  This even happens when I use a quarto project with a python virtual environment setup like here https://quarto.org/docs/tools/rstudio.html

**Comment by cderv** [comment]
@quinfer What engines are you using in your document ? In your project ? 

> It looks like quarto ,as I have set it up, is using reticulate to run my python codes. Is there something I missed in this set up?

Quarto will use **knitr** by default if there are any R chunks to run in the document. (`.qmd` containing any `{r}` chunk). And in that case, python chunks will be run with **reticulate** as this is how the **knitr** computation engine handles python. 

Engine binding is explained in this part of the doc: https://quarto.org/docs/computations/execution-options.html#engine-binding

**Comment by quinfer** [comment]
@cderv Thanks for the swift response.  OK, I am a little confused regarding the docs then.  I appreciate **knitr** will automatically look for **recticulate** to run  `{python}` chunks, so as described (or my interpretation) in the above docs do I just code my  python chunks as follows?:

```{python}
#| engine: /<file path to my choice of juypter>
```

**Comment by jjallaire** [comment]
You can't fix the use of R and Jupyter in the same document (the engine is bound globally). So if there are any R chunks in the file you'll use reticulate for Python chunks.

**Comment by quinfer** [comment]
OK, thats clears up my fogged thought process.  Thanks @jjallaire @cderv
