### ISSUE TITLE
Using `data-qmd` in `div` does not seem to work as expected (gt usecase) 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7501]
This was found in the context of https://github.com/quarto-dev/quarto-cli/discussions/7493

From https://github.com/rstudio/gt/issues/146 I understand that using HTML in a table colums to show as HTML in gt table, it requires to use `fmt_markdown`

`````markdown
---
title: "Test"
format: html
keep-md: true
---

```{r}
library(gt)
data.frame(A = "Text", B = "**Text**") |> 
  gt() |> 
  fmt_markdown(B)
```
`````

With 1.4 we get a Lua error 
```
Error running filter C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/resources/filters/main.lua:
...2/src/resources/filters/./quarto-pre/parsefiguredivs.lua:425: attempt to index a nil value (field 'classes')
```

<details>
<summary>Stacktrace</summary>

````lua
Error running filter C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/resources/filters/main.lua:
...2/src/resources/filters/./quarto-pre/parsefiguredivs.lua:425: attempt to index a nil value (field 'classes')
stack traceback:
	...DEV_R/QUARTO~2/src/resources/filters/./common/pandoc.lua:52: in function <...DEV_R/QUARTO~2/src/resources/filters/./common/pandoc.lua:46>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:86: in function <...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:76>
	(...tail calls...)
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:40: in local 'callback'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:54: in upvalue 'run_emulated_filter_chain'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:89: in function <..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:86>
stack traceback:
	...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:86: in function <...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:76>
	(...tail calls...)
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:40: in local 'callback'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:54: in upvalue 'run_emulated_filter_chain'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:89: in function <..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:86>
ERROR: Error
    at renderFiles (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render-files.ts:343:23)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async renderProject (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/project.ts:268:23)
    at async renderForPreview (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:426:24)
    at async render (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:162:22)
    at async preview (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:179:18)
    at async Command.fn (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/cmd.ts:401:7)
    at async Command.execute (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/quarto.ts:155:3)
    at async file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/quarto.ts:186:5
````

</details>

Error is from 
https://github.com/quarto-dev/quarto-cli/blob/95c6dd6ad4809d38e520d5b427689e1586ea093c/src/resources/filters/quarto-pre/parsefiguredivs.lua#L425

from https://github.com/quarto-dev/quarto-cli/pull/7449  (cc @cscheid )

The HTML table we get is this one 
```html
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="A">A</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="B">B</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="A" class="gt_row gt_left">Text</td>
<td headers="B" class="gt_row gt_left"><div data-qmd="**Text**"><div class='gt_from_md'><p><strong>Text</strong></p>
</div></div></td></tr>
  </tbody>
  
  
</table>
````

The `div data-qmd` has indeed no class. 

I would say 

* either we always need to test for existence before using includes 
	```lua
	if div.classes and div.classes:include("cell")
	```
	which solve the issue here.

	if we do this fix, it seems there is a bunch of places where we need to do that, looking at our usage of `:includes()`

* either this is a broader issue where the HTML table parsing is not correctly setting an empty classes attributes. Which `pandoc.Div()` seems to do by default
	````powershell
	$ pandoc lua -i
	Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
	Embedded in pandoc 3.1.9
	> div = pandoc.Div({})
	> div.classes
	List {}
    > div.classes:includes("dummy")
	false
	````

**Comment by cscheid** [comment]
Thanks! I can repro this.

`div.classes` should _always_ be a list inside a Div() walk handler. Somehow that's being called with a `Blocks` instead. It's a bug in the way I implement our custom AST walking code.

**Comment by cscheid** [comment]
This was a fun, tricky one. Let me document it here for future reference.

We have a utility function called `combineFilters` that allows us to merge multiple Pandoc filters in one, so they run "in parallel". This function is useful, but has a limitation where filters that are merged are expected to either return nil or a node of the same type that was called.

The crash here is coming from the fact that `parse_md_in_html_rawblocks()` is called inside `quarto_ast_pipeline()` in a inside a `combinedFilters`, but it currently returns Inlines and Blocks from a call to Span and Div handlers.

Ultimately, we need to fix combinedFilters, but that's surprisingly tricky to do correctly without causing performance issues (which is what combinedFilters was created to solve). So we'll work around the issue for now by wrapping the Inlines from `parse_md_in_html_rawblocks` in a scaffolding Span and Div. We already have code to remove scaffolding in a downstream filter too, so this should be pretty safe.
