### ISSUE TITLE
Documentation of `--execute-debug` flag

### ISSUE THREAD

**Issue by sebffischer** [quarto-dev/quarto-cli#7502]
The documentation of the `--execute-debug` is (via `quarto render help`): 

```
    --execute-debug                     - Show debug output for Jupyter kernel.   
```

However, when I set this flag, I also get some more information about the knitr engine, such as 

```
[knitr engine]: writing results
[knitr engine]: exiting
[knitr engine]: execute
```

This can be useful debugging output (that is not present without the flag) but I don't understand how this is related to the jupyter kernel.

**Comment by mcanouil** [comment]
This relates to:
- #5421
