### ISSUE TITLE
Custom crossref types only work with fenced divs?

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#7507]
### Bug description

Using the super new custom crossref types (https://quarto.org/docs/prerelease/1.4/crossref.html#custom-crossreferenceable-types) doesn't seem to work with computational output or with tables. It does work when wrapping content in a fenced div.

### Steps to reproduce

Here's a reproducible qmd showing four different tables with a custom `supptbl` type/prefix:

````qmd
---
title: "Testing"
crossref:
  custom:
    - kind: float
      prefix: Table S
      space-before-numbering: false
      name: Table S
      ref-type: supptbl
      latex-env: supptbl
      latex-list-of-file-extension: lost
      latex-list-of-description: Supplementary Table
---

# Manual table, directly labeled

See @supptbl-letters. This doesn't work.

| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: My Caption {#supptbl-letters}


# Computational table, directly labeled

See @supptbl-cars. This doesn't work.

```{r}
#| label: supptbl-cars
#| tbl-cap: "This is a test"
mtcars |>
  head() |>
  gt::gt()
```


# Manual table, wrapped in div

See @supptbl-letters-div. This *does* work.

::: {#supptbl-letters-div}

| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: My Caption

:::


# Computational table, wrapped in div

See @supptbl-cars-div-gt. This doesn't work.

::: {#supptbl-cars-div-gt}

```{r}
#| label: supptbl-cars1
#| tbl-cap: "This is a test"
mtcars |>
  head() |>
  gt::gt()
```
:::

````

### Expected behavior

I might be reading the documentation wrong, but I'd expect there to be four tables labelled S1 through S4

### Actual behavior

Instead, only one cross reference works. The other three can't be found:

<kbd><img width="671" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/da3fcd51-5716-479f-8e8c-d61e9080b3bf"></kbd>

<kbd><img width="675" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/c040aa5d-81ed-4fb5-a51d-ca3628c8d1fb"></kbd>

### Your environment

- IDE: RStudio 2023.12.0-daily+170
- OS: macOS Sonoma 14.0

### Quarto check output

```
Quarto 1.4.487
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.487
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/andrew/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
You're right that custom crossrefs require the div syntax. That's a limitation that's quite hard for us to lift at the moment, so we're going to first try to teach everyone about the general div syntax, and only add the smart parsing if it turns out to be necessary.

You also need to make sure you're using the correct syntax. The div syntax requires a caption in the div, not in the cell options.

<table>
<tr><td>**Don't do this**</td><td>Do this</td></tr>
<tr><td>

````
::: {#supptbl-cars-div-gt}

```{r}
#| label: supptbl-cars1
#| tbl-cap: "This is a test"
mtcars |>
  head() |>
  gt::gt()
```
:::

````

</td><td>

````
::: {#supptbl-cars-div-gt}

```{r}
mtcars |>
  head() |>
  gt::gt()
```

This is a test

:::

See @supptbl-cars-div-gt.
````
</td></tr></table>

**Comment by cscheid** [comment]
Actually, what I said is not true. We also support the image and linked image syntax:

````
---
title: "Testing"
crossref:
  custom:
    - kind: float
      prefix: Table S
      space-before-numbering: false
      name: Table S
      ref-type: supptbl
      latex-env: supptbl
      latex-list-of-file-extension: lost
      latex-list-of-description: Supplementary Table
---


![A caption](./image.png){#supptbl-1}

[![A caption](./image.png){#supptbl-1}](./a-page.html)

````

What we specifically don't support is the markdown + caption table syntax, or the knitr code cell syntax.

**Comment by andrewheiss** [comment]
Ah ok, got it!

The only downside I can see with that is that the caption is formatted and placed differently since it's not technically a table. With "real" tables, the caption goes at the top and is centered and gray (though horizontal justification and color are addressable with CSS):

<img width="680" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/2962879a-e80f-4abe-b380-d468d243b9e3">

&nbsp;

With the tables-in-divs tables, the caption goes at the bottom:

<img width="674" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/45249d7b-879e-479a-b9c4-46f327f04512">

The `tbl-cap-location` document option can't control that either, since it'd technically be `supptbl-cap-location` and that option doesn't exist bc it's dynamic

**Comment by cscheid** [comment]
Note, finally, that the syntax you used here worked somewhat luckily:

````
::: {#supptbl-letters-div}

| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: My Caption

:::
````

The recommended syntax is: content is all but the last paragraph, and caption is the last paragraph. So, no starting colon on the caption:

````
::: {#supptbl-letters-div}

| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

My Caption

:::
````

We have a plan for a linter that will tell you about all of these issues, but that's a big feature and it'll take a while for us to get there.

**Comment by cscheid** [comment]
> With "real" tables, the caption goes at the top and is centered and gray (though horizontal justification and color are addressable with CSS):

That's because it's a _table_ caption, and not a _Supplemental Table_ caption. You can control your caption location just like you can with the other options:

````
---
supptbl-cap-location: bottom
---
````

(This is admittedly something we need to document well because our YAML completion and validation doesn't have the ability to configure itself based on that same YAML, and so this is a bit obscure. But it works.)

You'll also need to configure the CSS to do the right thing, of course.

**Comment by andrewheiss** [comment]
Perhaps some sort of `cap-location` option for a custom type would fix the caption location issue:

```yaml
crossref:
  custom:
    - kind: float
      prefix: Table S
      space-before-numbering: false
      cap-location: top
```

**Comment by andrewheiss** [comment]
Ahhh yep, there it is :) https://github.com/quarto-dev/quarto-cli/issues/7507#issuecomment-1799781158

**Comment by cscheid** [comment]
I like the idea of controlling that directly on the custom definition. We haven't done that yet because there are annoying interactions with _other_ features. With that said, `cap-location` should just work, so I think we should do that one asap.
