### ISSUE TITLE
Setting max-width

### ISSUE THREAD

**Issue by JamesHM1995** [quarto-dev/quarto-cli#751]
Hello,
I'm trying to increase the max-width value in a quarto markdown. I would like the content of my document to fill my screen instead of being confined within roughly less than half of it.
I carefully read the documentation, however, the only time I've succefully managed to increase the width was when setting the theme to pandoc (which I find looks atrocious).
Is there a way to make the content adjust to the screen size for the default theme?

So far I've tried:
max-width: 1900px (trying to increase from the default 1400px)
max-width 100%
I've added !important at the end
I've tried other themes
I tried to use 72em instead of px

I'm able to change the font size though. I really don't understand what's wrong. Any help would be much appreciated.

**Comment by jjallaire** [comment]
Yes, should use the `page-layout` option for this: https://quarto.org/docs/output-formats/page-layout.html

**Comment by JamesHM1995** [comment]
Thank you!
