### ISSUE TITLE
"Jupyter kernel '...' not found" message could be morehelpful

### ISSUE THREAD

**Issue by ChrisJefferson** [quarto-dev/quarto-cli#7512]
I was recently trying to use the Jupyter kernel for a system called GAP, but I kept getting:

ERROR: Jupyter kernel 'gap' not found.

I was not sure exactly what name quarto wanted, so eventually I rewrote the line which generates the message (quarto.js:31901 in jupyterKernelspecFromMarkdown on my system):

```
const kernels = await jupyterKernelspecs();
return Promise.reject(new Error("Jupyter kernel '" + kernel + "' not found. Known kernels :" + JSON.stringify(...kernels.keys())))
```

I do not know Javascript, so I suspect there is a better way to print those keys (which is also why i haven't made a PR). However, this did help me find the language name I wanted (the name used seems to be the name of the directory, which doesn't seem to be obviously listed in the jupyter notebook GUI, which is why I didn't try that name).

**Comment by mcanouil** [comment]
The name should one of the ones listed by `jupyter kernelspec list`.

**Comment by ChrisJefferson** [comment]
Thank you very much! Maybe suggesting `quarto check`, in the error, which would certainly have helped me find the kernel names (and checked if it was just missing rather than mispelt)?

**Comment by cderv** [comment]
Thanks for the suggestion @ChrisJefferson !
