### ISSUE TITLE
Figure alignment for code chunks doesn't work

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#7516]
### Bug description

After updating Quarto, figure alignment for code chunks doesn't work anymore.

### Steps to reproduce

````
---
format: html
---


```{r}
#| fig-align: center
library(ggplot2)
ggplot(mtcars, aes(x = cyl, y = mpg)) +
    geom_point()
```
````

### Expected behavior

Figure should be centered.

### Actual behavior

Figure is left-aligned.

### Your environment

OS: Windows 11

### Quarto check output

```
Quarto 1.4.489
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.489
      Path: C:\Users\au234616\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: C:/Users/au234616/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.2.0
      Kernels: python3
```

**Comment by cscheid** [comment]
Thanks - I can repro this. We've updated the classes for the new crossref work but this is a codepath that shares the crossref classes without sharing the crossref DOM, so our CSS selectors are now wrong. I'll fix this today.

**Comment by snhansen** [comment]
That's perfectly fine. Thanks for a quick fix!

**Comment by cderv** [comment]
> What's happening here is that knitr is honoring fig- attributes even in the case where the result is not a cross-referenceable figure. We don't want to regress on knitr's specific behavior in 1.3 here, so I'm adding a fixup.

To add context for later us: `fig-align` as a chunk option, is mapped to `fig.align` **knitr** option. Quarto R code does handle it to add `fig-align` attributes on the the markdown image syntax, and alias it to `layout-align` to put on the `.cell` div 

Further processing is indeed Lua. 

Sharing this, in case we need to revisit and this should be dealt with at the R level + CSS instead of specific handling with Lua for knitr stuff.

**Comment by snhansen** [comment]
@cscheid: Unfortunately, the fix doesn't work when lightbox is enabled. Consider this example:

	---
	format: 
	  html:
	    lightbox: true
	---


	```{r}
	#| fig-align: center
	library(ggplot2)
	ggplot(mtcars, aes(x = cyl, y = mpg)) +
		geom_point()
	```

Any chance for a fix in this case as well?

**Comment by cscheid** [comment]
(@dragonstyle, my fixup and your auto-lightboxing are stepping on each other's toes. Tagging you just in case you know an immediate fix)

**Comment by dragonstyle** [comment]
I'm not certain of this, but a theory that comes to mind is the possibility that we're breaking figure discovery by injecting the hyperlink into a paragraph e.g. a paragraph that once contained only an image now contains an image with a link around it. We have the whole discoverLinkedImage thing, but perhaps this is somehow involved...

This is the mutation that causes the issue:

```lua
      -- this catches images in paragraphs by themselves
      -- without captions, since Pandoc doesn't convert those to Figures
      Para = function(para)
        local image = discoverFigure(para, false)
        if image ~= nil then
          local lightboxedFigEl = processImg(image, { automatic = true })
          if lightboxedFigEl ~= nil then
            return pandoc.Para({lightboxedFigEl}), false
          end
        end
      end,
```

(Processing the figure is really just wrapping it in a link)

**Comment by cscheid** [comment]
That would do it, given that my fixup looks for this specifically: https://github.com/quarto-dev/quarto-cli/pull/7519/files#diff-386ee10eae7d7052b880bf1048bc189c5796263f59c521da9b1fcce1df34e827R34

**Comment by cscheid** [comment]
> I'm not certain of this, but a theory that comes to mind is the possibility that we're breaking figure discovery by injecting the hyperlink into a paragraph e.g. a paragraph that once contained only an image now contains an image with a link around it.

Just for future reference in case we regress again, the issue is that this bugfix is explicitly _not_ for the case of "figure discovery". It's for the special case in 1.3 where `fig-align` works for any images that come from a code cell, including non-crossreferenceable ones.

In any case, the PR I opened should fix this.
