### ISSUE TITLE
crossref: listings with no output with div syntax

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#7522]
(Thanks, @cwickham!)

This is a fun one.

<table>
<tr><td></td><td>input</td><td>output</td><tr>
<tr><td>bad</td><td>

````
---
format: html
---


::: {#lst-assign}

```{r}
x <- 10
```

An assignment

:::
````
</td><td>
<img width="225" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/c1e1bcee-9e76-40ad-8a03-c3ac442b9538">
</td></tr>
<tr><td>good</td><td>

````
---
format: html
---

```{r}
#| lst-label: lst-assign
#| lst-cap: An assignment
x <- 10
```


See @lst-assign.
````

</td><td>

<img width="235" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/c70339e9-1c0e-4257-bf53-bd8d38a2c9ff">

</td></tr></table>

What's going on is that our div syntax has a code path to remove code blocks from the outputs, because most of the time we don't want the code to show up as part of the content of a Figure or Table. So we see the code cell, see a crossreferenceable entry (a listing) and process the cell "as usual". This removes the code block from the cell, and presents the result as a Listing, which is now empty.

**Comment by cscheid** [comment]
A thorny question: how do we think the following should be interpreted?

````
::: {#tbl-assign}

```{r}
x <- 10
```

Ok, I'm a table.

:::
````

Right now you get an empty table:

<img width="699" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/9a305876-43d6-4eb5-afb9-fc3f5496dbe9">

But it's not clear to me that moving the code block inside the cell is any better.

**Comment by cscheid** [comment]
The following example makes me think we should treat listings and figures uniformly:

````
::: {#fig-assign-2}

```{r}
x <- 10
```

This is a figure, let's make sure the code is removed.

:::
````

**Comment by cwickham** [comment]
Yeah, I'm for treating all the floats uniformly. 

What happens if we change the code to produce a plot? 
````
::: {#fig-assign-2}

```{r}
plot(1:10)
```

This is a figure, we currently lift the code but probably shouldn't.

:::
````
Does the behavior change (i.e. now code is lifted)?

**Comment by cwickham** [comment]
Should we allow for a situation where someone wants both the code and its output to be treated as a single cross-referenceable element?

**Comment by cderv** [comment]
> What happens if we change the code to produce a plot?
> Does the behavior change (i.e. now code is lifted)?

I believe it is (I ran your code with the PR)
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/7cef3554-0abf-4784-b247-be708d24e996)


But what about 
````markdown
::: {#fig-assign-2}

```{r}
#| eval: false
plot(1:10)
```

This is a figure, we currently lift the code but probably shouldn't.

:::

See @fig-assign-2

````

Now the code block is not removed 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/45af7d31-42bb-466d-8d28-68533bb55a5d)

> The following example makes me think we should treat listings and figures (and so probably all floats) uniformly:

This is probably related to 
* #7520 

and how it should be have when floats are created through cells options. 

<table>
<tr>
 <td>

````markdown
---
format: html
keep-md: true
---

```{python}
#| label: tbl-1
#| tbl-cap: This is a table
from tabulate import tabulate
from IPython.display import Markdown
table = [['First Name', 'Last Name', 'Age'], 
         ['John', 'Smith', 39], 
         ['Mary', 'Jane', 25], 
         ['Jennifer', 'Doe', 28]]
Markdown(tabulate(table))
```

See @tbl-1
````

 <td>

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/6475c7f1-5e47-497d-856c-4cc9563a664d)
<tr>
 <td>

````markdown
---
format: html
keep-md: true
---

```{python}
#| label: tbl-1
#| tbl-cap: This is a table
#| eval: false
from tabulate import tabulate
from IPython.display import Markdown
table = [['First Name', 'Last Name', 'Age'], 
         ['John', 'Smith', 39], 
         ['Mary', 'Jane', 25], 
         ['Jennifer', 'Doe', 28]]
Markdown(tabulate(table))
```

See @tbl-1
````


 <td>

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/67a1f068-42d3-4b53-a82b-d5c6895b3f5e)

</table>

**Comment by cscheid** [comment]
Ok, I'm convinced the fix I made is good. I think as a side-effect it does something reasonable for #7520, but I don't consider #7520 to be a bug; there's nothing quarto can do that's perfect there anyway...
