### ISSUE TITLE
Long kableExtra footnote not spanning full width

### ISSUE THREAD

**Issue by blaidd4drwg** [quarto-dev/quarto-cli#7530]
### Bug description

I posted this issue already on the [kableExtra repo issue tracker](https://github.com/haozhu233/kableExtra/issues/772#issue-1976470819) but it seems to be a Quartos-specific issue.
When rendering a kable table with a long kableExtra footnote, the footnote gets wrapped after one column instead of running full width (works correctly with Rmarkdown files). 

### Steps to reproduce

````
---
title: "footnote-test"
---

```{r}
library(kableExtra)

iris %>% 
  dplyr::slice(1:4) %>% 
  kableExtra::kbl(format = "html") %>%
  kableExtra::footnote(
      general = c("A very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long footnote"),
      general_title = "Legend:"
    )
```
````
<img width="844" alt="SCR-20231109-qhka" src="https://github.com/quarto-dev/quarto-cli/assets/18100143/4e581f4a-eeda-4ff9-bc37-b18964fa9bfe">

### Expected behavior

A long footnote should span the whole table.

### Actual behavior

The footnote breaks onto a newline after the first column. The first column additionally fills all possible space.

### Your environment

- Quarto version: 1.4.489 (pre-release) 
- OS: macOS 14.0 (but same issue on Windows 10)
- IDE: RStudio 2023.09.1+494

### Quarto check output

Quarto 1.4.489
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.489
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/X/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /Users/X/.pyenv/versions/3.11.2/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/X/Y/renv/library/R-4.3/aarch64-apple-darwin20
        - /Users/X/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.3/aarch64-apple-darwin20/ac5c2659
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
You likely need to disable Quarto processing as described in the documentation, see <https://quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing>.

**Comment by blaidd4drwg** [comment]
That works indeed, thanks! But if I do that, I lose the table styling (e.g. the stripes). Is there a way to keep that?

**Comment by cscheid** [comment]
Unfortunately no. I'll note that kableExtra appears to be emitting invalid HTML, and that's what's causing the trouble.

````
<tr><td style="padding: 0; " colspan="100%"><span style="font-style: italic;">Legend:</span></td></tr>
<tr><td style="padding: 0; " colspan="100%">
<sup></sup> A very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long footnote</td></tr>
````

In order for us to process colspans correctly, we need to have correctly specified colspans. Colspans are integers, not percentages: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td

Browsers happen to do the right thing here but that doesn't work in our case, because Pandoc needs to know the actual colspan in order to process the table correctly. This is a bug in kableExtra; we can only do the right thing with good HTML. See the output from w3c's validator:

<img width="961" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/27d8b629-b604-42e4-a3ac-0400b872aa3a">

**Comment by stibu81** [comment]
This is indeed an issue in kableExtra. If one uses an integer in colspan, the footnote indeed spans multiple columns:

    ---
    title: "footnote-test"
    ---
    
    ```{r}
    library(kableExtra)
    
    tab <- iris %>% 
      dplyr::slice(1:4) %>% 
      kableExtra::kbl(format = "html") %>%
      kableExtra::footnote(
          general = c("A very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long footnote"),
          general_title = "Legend:"
        )
    tab
    ```
    
    ```{r}
    tab_mod <- stringr::str_replace_all(tab, "colspan=\"100%\"", "colspan=5")
    attributes(tab_mod) <- attributes(tab)
    tab_mod
    ```

The modified table looks like this:

![Image](https://github.com/user-attachments/assets/aa41386b-5143-444e-b734-80e86d44c4ab)

Clearly, after changing the colspan, Pandoc can handle the footnote correctly. (I'm not sure that the right alignment is expected, though.)
