### ISSUE TITLE
Can't do multiple paragraph footnotes in the margin of a PDF

### ISSUE THREAD

**Issue by bweatherson** [quarto-dev/quarto-cli#7534]
### Bug description

The PDF version won't compile if the footnotes are put in the margin, and any of the footnotes have more than one paragraph.

This isn't a problem with either margin notes, or multiple paragraph notes. The example below compiles fine if the format is changed to html, the reference-location is changed to document, or the second paragraph is deleted from the footnote.

### Steps to reproduce

````qmd
---
title: "Example"
format: 
    pdf:
        reference-location: margin
---

Some text.[^note] Some more text.

[^note]: The first paragraph.   
    
    The second paragraph.
````

### Expected behavior

A PDF should be built with a two paragraph footnote.

### Actual behavior

It doesn't compile with the following message.

ERROR: 
compilation failed- error
Paragraph ended before \IfNoValueOrEmptyTF  was complete.
<to be read again> 
                   \par 
l.152   The second paragraph.}
                               Some more text. 

### Your environment

- IDE: RStudio Version 2023.09.1+494 (2023.09.1+494)
- Mac running OS 13.6.1 (22G313)

### Quarto check output

Quarto 1.4.470
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.470
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.11
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/weath/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.5.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/miworkspace-library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

**Comment by cderv** [comment]
FWIW it seems to be an issue with **sidenotes** package (https://ctan.org/pkg/sidenotes) that we use I think for this feature : 
https://tex.stackexchange.com/questions/649471/sidenotes-with-multiple-paragraphs

Two possible solution: 

* Provide our patched version of `sidenotes.sty` to render with it
* Use the trick to include `\endgraf` betwen Para

This lua filters seems to work 
```lua
Note = function(n)
  n.content = pandoc.Para(pandoc.utils.blocks_to_inlines(n.content, {pandoc.RawInline('latex', '\n\\endgraf\n')}))
  return n
end
```

````markdown
---
title: "Example"
format: 
  pdf:
    reference-location: margin
keep-tex: true
filters:
  - notes.lua
---

Some text.[^note] Some more text.

[^note]: The first paragraph.   
    
    The second paragraph.
````
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/7cce5650-ccb0-4c12-b29a-e46186291ac3)

**Comment by cscheid** [comment]
@cderv very nice trick. We have a number of latex fixups already, this should be another one. render_latex() is called after layout calculation (so the AST has information about this being a margin note) and before rendering (so we can still do the fixups before it's all RawBlocks).

**Comment by cderv** [comment]
Thanks ! I wasn't sure where to put it, also because we do some post processing for footnotes in Typescript to. 

I'll try to add it in `render_latex()`
