### ISSUE TITLE
Check support of new `tab.cap` chunk option in knitr 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7555]
Next release of **knitr** will have a `tbl.cap` chunk options handling 
* https://github.com/yihui/knitr/issues/1679 (https://github.com/yihui/knitr/commit/638d3ecad8e6985dd86797c8a71185c126ca86bc)

As quarto does use `tbl-cap` also, the support should be checked for correct behavior. Especially because `tbl-cap` is supposed to be today a forwarded attributes in Quarto to the cell

**Comment by cderv** [comment]
So in fact, **knitr** introduced `tab.cap` and not `tbl.cap`... 

@yihui just so you know in Quarto this is `tbl-cap`  that complements `fig-cap`. 

I wonder if 
* both should stay separate options, as Quarto has already its own handling, 
* we should make `tab-cap` option map to `tbl-cap` when inside Quarto (this would one in Quarto R code)
* Add to `knitr::convert_chunk_header()` to transform `` ```{r, tab.cap="content"}`` to its ``#| tbl-cap: content` counterpart with Quarto

Probably the second is the best choice

**Comment by yihui** [comment]
Oh I didn't know `tbl.cap` has existed in Quarto. Name-wise, I prefer `tab.cap` over `tbl.cap` since the naming is more consistent (first three letters of a word: `figure` -> `fig`, `caption` -> `cap`, so `table` -> `tab`). Anyway, I have added support for `tbl.cap` in **knitr**: https://github.com/yihui/knitr/commit/c9473adf8602482f8f4add300d98bffe0658f64c

**Comment by cscheid** [comment]
"tab" clashes with "tabsets" for us, which is why I think we went with "tbl". Sorry for the confusion, and thanks for adding that as well!

**Comment by cderv** [comment]
All seems to work as expected because we handle caption set in Markdown, LaTeX and HTML and that what **knitr** is producing. 
So even with `tbl-cap` not set but `tab-cap` we do get a caption. 

<table>
<tr>
 <td>

````markdown
---
title: Hello
format: pdf
keep-md: true
---

```{r}
#| tab-cap: test
knitr::kable(head(cars), format = 'latex')
```

````
 <td>

````latex
\begin{table}

\caption{\label{tab:unnamed-chunk-1}test}
````

<tr>
 <td>

````markdown
---
title: Hello
format: html
keep-md: true
---

```{r}
#| tab-cap: test
knitr::kable(head(cars), format = 'html')
```
````

 <td>

``````
`````{=html}
<table>
<caption>test</caption>
``````

<tr>
 <td>

````markdown
---
title: Hello
format: html
keep-md: true
---

```{r}
#| tab-cap: test
knitr::kable(head(cars), format = 'pipe')
```

`````

 <td>

````markdown
::: {.cell-output-display}


Table: test

| speed| dist|
|-----:|----:|
|     4|    2|
|     4|   10|
|     7|    4|
|     7|   22|
|     8|   16|
|     9|   10|
```` 
</table>

So it won't break anything, but still `tbl-cap` should be used with Quarto.
