### ISSUE TITLE
New Quarto Project "Type:Website" ERROR: Unsuppported project type site

### ISSUE THREAD

**Issue by jslingsby** [quarto-dev/quarto-cli#756]
I've just discovered Quarto and it looks like the answer to all my bugbears! You're my heroes! So much so that I want to abandon the Hugo Wowchemy website I've been working on for a week and start again with Quarto, but when I try:

New Project > New Directory > Quarto Project > and choose "Type: Website" I get:

"ERROR: Unsuppported project type site"

I've tried with and without the git repo and renv options and get the same result. The "(Default)" and "Book" options work fine, as do the Terminal commands `quarto create-project mysite --type website` etc

I suspect the "ppp" in "Unsuppported" may help find where the error is flagged? If nothing else, pedantically pointing out the spelling error may justify submitting an issue even if this is user error? :)

My RStudio version is not 2022.02, which I suspect is the issue... but when I check for updates I get "You're using the newest version of RStudio". I haven't tried uninstalling and reinstalling RStudio to see if the updater is missing something as it's bed time in Cape Town... I figure you may tell me to do that in the morning... And then we can start a new issue on RStudio's update checker ;)

Thanks!

**Setup**

RStudio 2021.09.0+351 "Ghost Orchid" Release (077589bcad3467ae79f318afe8641a1899a51606, 2021-09-20) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

`sessionInfo()`
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_ZA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_ZA.UTF-8        LC_COLLATE=en_ZA.UTF-8    
 [5] LC_MONETARY=en_ZA.UTF-8    LC_MESSAGES=en_ZA.UTF-8   
 [7] LC_PAPER=en_ZA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_ZA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.3 tools_4.1.3    renv_0.15.4

**Comment by jjallaire** [comment]
Yes, that is indeed a result of the older version of RStudio creating a legacy syntax. I would super strongly recommend updating to RStudio 2022.02 (we just actually put out a patch release today that has a couple of quarto related fixes). Note that you can fix the project you generated by changing to `type: website` and renaming the `site` key to `website`

**Comment by jslingsby** [comment]
Yup, that fixed it. Weird that the IDE wasn't detecting a new version when I went "Help > Check for updates".

Thanks!
