### ISSUE TITLE
globToRegExp is not defined on pre-release 1.4.498

### ISSUE THREAD

**Issue by majidaldo** [quarto-dev/quarto-cli#7561]
### Bug description

```
❯ quarto preview .
ERROR: ReferenceError: globToRegExp is not defined
```

### Steps to reproduce

reverting to previous 1.4.4*89*, problem goes away.

### Your environment

Windows.

**Comment by cscheid** [comment]
Thank you! We're aware and a PR that fixes this is [up](https://github.com/quarto-dev/quarto-cli/pull/7562).

It's ultimately a bug in the deno TS bundler that is inconsistently triggered by circular imports in our codebase. We do our best to avoid them but they sneak in over time.

**Comment by cscheid** [comment]
This is closed with 1.4.501. Thanks for the patience! It's a novel bug on `deno bundle`...

**Comment by coatless** [comment]
Minor note: It looks like Quarto books are failing in the updated pre-release with 

```
ERROR: ReferenceError: isGlob is not defined
```

**Comment by cscheid** [comment]
Sigh, thank you. Looks like a long night over here.

**Comment by coatless** [comment]
I'm so sorry for being the bearer of bad news @cscheid. Other formats are working nicely though!

**Comment by cscheid** [comment]
1.4.502 is on the way. I'm more confident this one will stick:  we've added a sanity check to the result of `deno bundle` which picked up the previous problems, and that is now coming up clean.

**Comment by cderv** [comment]
Thanks a lot for the hard work on fixing that quickly Carlos ! 

> we should have some test actions on the bundles, like rendering all the smoke-all files (not testing the invariants, but just checking if we crash)...

I'll adapt our nightly run to add this to the matrix. This nightly run is also in a bad state... I'll invesitgate.
