### ISSUE TITLE
Commented code not displaying in PDF when annotated

### ISSUE THREAD

**Issue by emitanaka** [quarto-dev/quarto-cli#7568]
### Bug description

When rendering the document with commented + annotated code, the line is missing in pdf output, although it works as expected in html output. 

### Steps to reproduce

````qmd
---
title: "Test"
format: pdf
---

```{r}
#| warning: false
#| eval: false
library(dplyr)
cars %>%  # <1>
  #mutate(speed = speed * 2) %>%  # <2>
  mutate(speed = speed * 4) # <3>
```

1. test1
2. test2
3. test3
````

### Expected behavior

Similar output to html format where the 3rd line is visible:

<img width="605" alt="Screenshot 2023-11-14 at 4 32 27 pm" src="https://github.com/quarto-dev/quarto-cli/assets/7620319/d21b9623-e6f2-4d5a-af27-8219f9195a13">

### Actual behavior

3rd line is missing:

<img width="540" alt="Screenshot 2023-11-14 at 4 32 16 pm" src="https://github.com/quarto-dev/quarto-cli/assets/7620319/d505ad45-f2c1-4102-9844-46ddaa9fa540">

### Your environment

- IDE: Rstudio 2023.09.0+463
- MacOS: Sonoma version 14.0

### Quarto check output

Quarto 1.4.502
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.502
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10 (Conda)
      Path: /Users/emitanaka/miniconda/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

-ne

**Comment by cderv** [comment]
We indeed have an issue with this. We don't support the double comment 

LaTeX produce before post processing is 
````
\NormalTok{cars }\SpecialCharTok{\%\textgreater{}\%}\CommentTok{\# \textless{}1\textgreater{}}
  \CommentTok{\#mutate(speed = speed * 2) \%\textgreater{}\%\# \textless{}2\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{speed =}\NormalTok{ speed }\SpecialCharTok{*} \DecValTok{4}\NormalTok{)}\CommentTok{\# \textless{}3\textgreater{}}
````

And we have a Regex that aims to replace the `# <2>` which is in latex `\CommentTok{\# \textless{}2\textgreater{}}` by the `\circled` annotation - but in case of commented line the `\CommentTok` does include the whole line and the just the last one which is not seen as a comment... 

We'll see how we can adapt the regex without breaking the logic with any language comment 🤔

**Comment by cderv** [comment]
Ok I got something with regex. Let's open a PR to check the tests
