### ISSUE TITLE
layout-ncol does not render well in other pdf-engines 

### ISSUE THREAD

**Issue by a3VonG** [quarto-dev/quarto-cli#7578]
### Bug description

When using "weasyprint" the generated pdf does not put the on the same row. 

Html in preview: 
![image](https://github.com/quarto-dev/quarto-cli/assets/32267348/05611b9f-9a5d-4fc8-9f81-9e06de110f53)

Generated pdf: 
![image](https://github.com/quarto-dev/quarto-cli/assets/32267348/e2a05979-204a-4969-94cf-c8e40de349c8)

### Steps to reproduce

_quarto.yml 

```
project:
  type: website
```

example_picture_layout.qmd

```
These pictures should appear side by side.

::: {layout-ncol=2}
![](images/paste-1.png)

![](images/paste-2.png)
::: 
```

Create an images folder and paste  the following images into it: 
![image](https://github.com/quarto-dev/quarto-cli/assets/32267348/43bce39d-70af-4b70-81e2-5fca89cd43ae)
![image](https://github.com/quarto-dev/quarto-cli/assets/32267348/8a90ea81-8d3e-4292-9d4d-19a5110221e2)

Run the command: 
`quarto render example_picture_layout.qmd --to pdf --pdf-engine weasyprint` 
also the case with 
`quarto render example_picture_layout.qmd --to pdf --pdf-engine wkhtmltopdf`

With the default engine the pictures do appear side by side. 

### Expected behavior

The pictures appear side by side when using wkhtml. 

### Actual behavior

The pictures do not appear side by side. 

### Your environment

- Mac 0S 13.4 Ventura

### Quarto check output

```
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.5
      Path: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/ 
```

**Comment by mcanouil** [comment]
Here is a reprex showing that the latex code and html code are correct and working.
I am not an expert with weasyprint and wkhtmltopdf but they seem to do a bad job here for some reason.

````qmd
---
title: "PDF"
format:
  html: default
  pdf:
    output-file: latex.pdf
    pdf-engine: xelatex
  pdf+weasyprint:
    output-file: weasyprint.pdf
    pdf-engine: weasyprint
  pdf+wkhtmltopdf:
    output-file: wkhtmltopdf.pdf
    pdf-engine: wkhtmltopdf
---

These pictures should appear side by side.

::: {layout-ncol=2}
![](https://placehold.co/100x50.png)

![](https://placehold.co/100x50.png)
::: 
````

**Comment by a3VonG** [comment]
Agreed. The html comingf rom quarto looks good.
When I run weasyprint and wkhtmltopdf on this html through the command line, so not using quarto, I get the same result.
 The issue is thus on their side and not from quarto! 

As a workaround I used [puppeteer](https://pptr.dev/) to generate a nice looking pdf that is much closer to the html that is generated by quarto. 

Including this workaround for reference (maybe worth thinking to include this as a pdf engine as well?): 

``` 
const puppeteer = require('puppeteer');

(async () => {
  // Check if the correct number of arguments are provided
  if (process.argv.length < 4) {
    console.log("Usage: node script.js <html path> <output pdf path>");
    process.exit(1);
  }

  // The third argument (index 2) is the HTML file path
  const htmlPath = process.argv[2];

  // The fourth argument (index 3) is the output PDF file path
  const outputPath = process.argv[3];

  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  // Use the provided HTML path
  await page.goto(`file://${htmlPath}`, { waitUntil: 'networkidle2' });

  // Use the provided output path for the PDF
  await page.pdf({ path: outputPath, format: 'A4' });

  await browser.close();
})();
```
node node_script_to_get_pdf.js path/to/html/generated/by/quarto.html output/path.pdf

``
generates the following on a pdf: 
![image](https://github.com/quarto-dev/quarto-cli/assets/32267348/9cc37f17-9f47-4a02-8156-6ac39f435c39)
