### ISSUE TITLE
Release notes aren't updated with latest pandoc and typst version 

### ISSUE THREAD

**Issue by danieltomasz** [quarto-dev/quarto-cli#7579]
### Bug description

Quarto 1.4.502 ships
```
quarto pandoc -v
pandoc 3.1.9
```
and 
```
quarto typst --version
typst 0.9.0 (7bb4f6df)
```

while pre-release notes https://quarto.org/docs/download/  for `1.4.502' says
```
Dependencies
Update to Pandoc 3.1.8
Update to Typst 0.7.0
```

**Comment by danieltomasz** [comment]
Changelog https://github.com/quarto-dev/quarto-cli/blob/v1.4.504/news/changelog-1.4.md isn't updated as well

**Comment by mcanouil** [comment]
Note that the website uses this file.
There are not two independent things.
