### ISSUE TITLE
pagebreak.lua: No such file or directory

### ISSUE THREAD

**Issue by WillemSleegers** [quarto-dev/quarto-cli#759]
I just installed the latest Preview release and now I get the following error when I try to render a Quarto document (default document from New File -> Quarto Document):

> Error running filter /Applications/quarto/share/filters/rmarkdown/pagebreak.lua:
> cannot open /Applications/quarto/share/filters/rmarkdown/pagebreak.lua: No such file or directory

My session information:

> R version 4.1.3 (2022-03-10)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Monterey 12.3.1
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] compiler_4.1.3 tools_4.1.3

**Comment by cderv** [comment]
I can confirm I have push a fix in #760 that should be included in a release soon.

**Comment by jjallaire** [comment]
Yes, this is now fixed in this release: https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.326
