### ISSUE TITLE
About Pages Title Replaced when using {{< include _file.qmd>}} outside about section with title of _file.qmd

### ISSUE THREAD

**Issue by pjkreutzer** [quarto-dev/quarto-cli#7590]
### Bug description

When including a file on a page with an about section, the about section title is replaced with the title value of the included file. 

## Content of about page

````qmd 
---
title: "Finley Malloc"
about:
  id: hero-heading
  template: jolla
  image: profile.jpg
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: https://github.com
---

### This content appears above the formatted about page content.

:::{#hero-heading}

Finley Malloc is the Chief Data Scientist at Wengo Analytics. When not innovating on data platforms, Finley enjoys spending time unicycling and playing with her pet iguana.

## Education

University of California, San Diego | San Diego, CA
PhD in Mathematics | Sept 2011 - June 2015

Macalester College | St. Paul MA
B.A in Economics | Sept 2007 - June 2011

## Experience

Wengo Analytics | Head Data Scientist | April 2018 - present

GeoScynce | Chief Analyst | Sept 2012 - April 2018

:::

## Included File
{{< include _file.qmd >}}

### This content appears below the formatted about page content.
```` 

## Content of _file.qmd

```qmd
---
title: File
---

Some text
````

### Expected behavior

Expected behavior would be that the title yaml value of the about page is used to render the title field in the about section.

### Your environment

- Quarto Version: 1.3.340
- Ubuntu 20.04.6 LTS (GNU/Linux 4.4.0-19041-Microsoft x86_64)
- Visual Studio Code  1.84.2

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.18 (Conda)
      Path: /home/pjk/miniconda3/bin/python
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/lib/R
      LibPaths:
        - /home/pjk/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.41
      rmarkdown: 2.18

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
This is not a bug. The documentation https://quarto.org/docs/authoring/includes.html points out that including is equivalent to copying and pasting the entire file, including the metadata block (because sometimes you need `_file.qmd` to have some common metadata). In your case, `_file.qmd` can't have a title, or that title will be used by all included files

**Comment by pjkreutzer** [comment]
Great! Thanks for the quick help :thumbsup:
