### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by matthewfinkbeiner** [quarto-dev/quarto-cli#7603]
### Bug description

FATAL (C:/Users/MFINKB~1/AppData/Local/Programs/Quarto/share/filters/main.lua:18424) An error occurred:
This is an internal error. Please file a bug report at https://github.com/quarto-dev/quarto-cli/
Error running filter C:/Users/MFINKB~1/AppData/Local/Programs/Quarto/share/filters/main.lua:
...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:2081: attempt to call a nil value (global 'crash_with_stack_trace')
stack traceback:
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:1669: in function 'fail'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:1674: in function 'internal_error'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:18424: in function 'decorate_caption_with_crossref'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:16033: in field 'render'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:744: in local 'filter_fn'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:243: in function <...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:233>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:165: in function <...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:155>
	(...tail calls...)
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:803: in local 'callback'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:817: in upvalue 'run_emulated_filter_chain'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:852: in function <...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:849>
stack traceback:
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:165: in function <...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:155>
	(...tail calls...)
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:803: in local 'callback'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:817: in upvalue 'run_emulated_filter_chain'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:852: in function <...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:849>

**Comment by mcanouil** [comment]
Please fill in properly the issue template and format properly your post.
As is, we'll have to close the issue as there is no information in it.
Thank you for your understanding.

**Comment by cderv** [comment]
See our guidelines at https://quarto.org/bug-reports.html to help

thank you !
