### ISSUE TITLE
`panel: XXX` does not work or no longer work in Jupyter

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#7607]
From <https://quarto.org/docs/reference/cells/cells-jupyter.html#cell-output>, it is possible to define `panel: tabset` instead of surrounding a code cell with a div.
This works as of the current Quarto development version with `engine: knitr` but not with `engine: jupyter`.

Also note, that `echo` is turned off when using `knitr`.

I believe, the usage should be consistent across engines.

<table>
<tr><th>Engine</th><th>Quarto document</th><th>HTML</th></tr>
<tr>
<td>Jupyter</td>
<td>

````qmd
---
title: "`panel: tabset`"
format: html
---

```{python}
#| panel: tabset
#| output: asis
from IPython.display import display, Markdown
for i in ['a', 'b', 'c']:
  display(Markdown(f'## Heading {i}\n\n'))
  display(Markdown(f'content {i}\n\n'))
```
````

</td>
<td>
<img width="581" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/096ed67c-dfde-476f-a007-6e04b265d5db">
</td>
</tr>
<tr>
<td>knitr</td>
<td>

````qmd
---
title: "`panel: tabset`"
format: html
---

```{r}
#| panel: tabset
#| output: asis
for (i in letters[1:3]) {
  cat("## Heading", i, "\n\n")
  cat("content", i, "\n\n")
}
```
````

</td>
<td>
<img width="576" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/c03fae3a-13fc-4fdc-be6c-3876d97809e5">
</td>
</tr>
</table>

Behaviour observed using:
- development version (9b9e48340e84a13c17ce4e8d21ad58a8af386dc5)
- 1.3.450
- 1.2.475

<details><summary>Quarto check output.</summary>
<p>

```sh
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/mcanouil/Projects/quarto/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.10
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mcanouil/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /Users/mcanouil/Projects/misc/quarto-playground/.venv/bin/python3
      Jupyter: 5.4.0
      Kernels: julia-1.9, python3

[✓] Checking Jupyter engine render....OK

(/) Checking R installation...........ℹ R version 4.3.2 (2023-10-31)
! Config '~/.Rprofile' was loaded!
[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/mcanouil/Projects/misc/quarto-playground/renv/library/R-4.3/aarch64-apple-darwin20
        - /Users/mcanouil/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.3/aarch64-apple-darwin20/ac5c2659
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

</p>
</details>

**Comment by mcanouil** [comment]
> Side note: I don't know what is the advantage of the option compared to using Markdown syntax directly

It's a Quarto layout feature 🤷‍♂️ (it actually comes with more than just tabset)

**Comment by cderv** [comment]
From discussion with @dragonstyle and @cscheid , I think here the Jupyter behavior is the right one.  If you use `output: asis` then, cell options are not taken into account because you are removing the scafolding - all the internal Div. 

**knitr** is adding one  back, but not sure it should.

**Comment by mcanouil** [comment]
Anyway works for me as long as it is consistent.

Side note: whatever behaviour chosen might have some implication in shiny layout where most of `panel` options are actually used (in the documentation), see <https://quarto.org/docs/interactive/shiny/>.
If `knitr` behaviour is to change, this means you could no longer generate your own complex component this way (not the best way anyway).

**Comment by cderv** [comment]
Ok so looking closer into this, our current R code for knitr is designed to ignore `output: asis` in some cases: 

https://github.com/quarto-dev/quarto-cli/blob/f38a30e63607a6cfec3a770ca8c0a70e865f7b4d/src/resources/rmd/hooks.R#L400-L416

It means that with **knitr** document, `output: asis` won't remove the `.cell` output div when 
* There is specific `label` 
	* Figure label `fig-*`
	* Table label `tbl-`
	* Specific `notebook-preserve-cells` feature 
* more than one `classes` that needs to be through (usually more than just `.cell`)
	* This is related to specific quarto cell option like  `classes` , `panel`, `column`, `fig-column`, `tbl-column`, `cap-location`, `fig-cap-location`, `tbl-cap-location`, 
	* Other feature like `keep-hidden` 
* Any attributes to set like `layout` or `tbl-cap`, or main `fig-cap`, or any options pass through as is. specific to quarto 


So I guess this issue is about : Should `output: asis` be lowest priority or highest priority ? 

It seems Jupyter and **knitr** does not behave the same on that topic.

**Comment by cderv** [comment]
> this is different from what we thought the resolution would be, just to be clear!)

Yeah all clear. This was one of the possibility I had in mind, and what I had understand from our latest discussion on Slack. So all good. Thanks for the fix !
