### ISSUE TITLE
knitr chunk option that start with `.` break output

### ISSUE THREAD

**Issue by gadenbuie** [quarto-dev/quarto-cli#762]
When chunk options start with `.`, e.g. `.value = "foo"`, they become part of the `.cell` fenced div. Then pandoc fails to render the fenced divs because `.value` is an invalid HTML attribute name.

Here's a very minimal and contrived reprex:

````markdown
---
title: "Reprex dots in chunk opts"
format: html
engine: knitr
execute:
  keep-md: true
---

```{r reprex, .test = "foo"}
runif(1)
```
````

The markdown and html output are

````markdown
::: {.cell .test='foo'}

```{.r .cell-code}
runif(1)
```

::: {.cell-output .cell-output-stdout}
```
[1] 0.9368014
```
:::
:::
````

![image](https://user-images.githubusercontent.com/5420529/165957331-40a92f03-346e-4a19-ade2-8c4899328c75.png)

Here's a less-contrived example where `.`-prefixed chunk options are used by a knitr language engine:

````markdown
---
title: "Reprex dots in chunk opts"
format: html
engine: knitr
execute:
  echo: false
  keep-md: true
---

```{r setup}
library(glue)
rand_5 <- function() signif(mean(runif(5)))
```

```{glue expected}
The average of 5 random numbers is {rand_5()}.
```

```{glue problem, .open = "{{", .close = "}}"}
The average of 5 random numbers is {{rand_5()}}.
```

```{glue user-fixed, .open = "{{", .close = "}}"}
#| output: asis
The average of 5 random numbers is {{rand_5()}}.
```
````

In this second example, there is an easy work around of adding `output: asis`, but that solution is probably unique to this use case.

![image](https://user-images.githubusercontent.com/5420529/165957881-8d9b05e3-271b-4c69-8e94-f033b88a4714.png)

**Comment by jjallaire** [comment]
Thanks! Fixed here: https://github.com/quarto-dev/quarto-cli/commit/b6f063af7197ea5004b343f894eb4ff18d4a8b75

We forward all "unknown" knitr options onto the containing div (this is to allow for new cell features to be added e.g. via filters that look for the options). Here we just need to exclude options that start with `.`
