### ISSUE TITLE
When using `citations: true` and `ieee.csl`, `pages = {undefined}` is being printed

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#7638]
### Bug description

When using `citations: true`, `pages = {undefined}` is being printed, e.g.:

```
@online{krishnamurthy2023,
  author = {Krishnamurthy, Dheepak},
  title = {Publishing Documents with {Quarto}},
  pages = {undefined},
  date = {2023-11-19},
  url = {https://kdheepak.com/blog/publish-documents-with-quarto},
  langid = {en}
}
```

See https://kdheepak.com/blog/publish-documents-with-quarto/ as a live example.

I tried with a new project and using `ieee.csl` seems to cause this issue. Here's the test project for your reference:

[test-citations.zip](https://github.com/quarto-dev/quarto-cli/files/13413716/test-citations.zip)

### Steps to reproduce

Use the test project attached in the previous form input to reproduce the bug.

### Expected behavior

if no pages, then remove that entry.

### Your environment

- OS: MacOS Ventura 13.5.2

### Quarto check output

```bash
quarto check
Quarto 1.4.489
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.489
      Path: /Users/USERNAME/Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12 (Conda)
      Path: /Users/USERNAME/miniforge3/bin/python
      Jupyter: 5.4.0
      Kernels: julia-1.9, rust, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

```

**Comment by cderv** [comment]
Thanks for the report. I believe we do have a regression since 2e7ba02abf92f3ef01d3fb9fdbc8e1734c10f8be because we convert to string , and `undefined` becomes `"undefined"` which end up in output, instead of being ignored. 

I'll make a PR for this
