### ISSUE TITLE
I cannot pubish any website anymore API Error: 500 - Internal Server Error

### ISSUE THREAD

**Issue by gregoireurvoy** [quarto-dev/quarto-cli#7639]
### Bug description

Hello,

Since this morning I cannot publish any website that contains more than 1 file .qmd anymore. 

I got the following error ERROR: API Error 500 - Internal Server Error.

I tried to republished some old files or to create new documents with a few files and it doesnt work either.

Thank you so much and have a nice day,

Grégoire

### Steps to reproduce

quarto publish 

### Expected behavior

It should create all the html files and then the website. 

### Actual behavior

API Error: 500 - Internal Server Error

### Your environment

MacOS Ventura 13.2.1 or Windows 11

**Comment by tanduc307** [comment]
I have the same problem, still ERROR: API Error 500 - Internal Server Error.

**Comment by gregoireurvoy** [comment]
Also only since this morning ?

**Comment by tanduc307** [comment]
Since last night 22h Sunday 19/11 UTC/GMT +7 , I cannot publish to quartopub as usual. Today, I try again but fail. I hope this problem soon resolved.

**Comment by cderv** [comment]
I believe you are both talking about quartopub service ?  Or are you publishing elsewhere ? 

Sorry to ask, but there is no context about the publishing service used, and Quarto support to publish to different services

**Comment by andypicke** [comment]
I've been having the same issue since yesterday (Sunday 11/19). I am trying to publish my quarto website from RStudio (using "quarto publish quarto-pub" in the terminal, it renders and previews fine on my local machine. It seems to build fine, but then I get the following error:

[✓] Preparing to publish site
ERROR: API Error: 500 - Internal Server Error

Error: API Error: 500 - Internal Server Error
    at QuartoPubClient.createDeploy (file:///Applications/quarto/bin/quarto.js:111379:23)
    at async file:///Applications/quarto/bin/quarto.js:109021:22
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:56613:9)
    at async handlePublish (file:///Applications/quarto/bin/quarto.js:108999:5)
    at async publishSite (file:///Applications/quarto/bin/quarto.js:121225:38)
    at async publish5 (file:///Applications/quarto/bin/quarto.js:121443:61)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:121399:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:121410:9)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:121387:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)

quarto -V
1.3.361

I am running MacOs Sonoma Version 14.1.1 (23B81)

quarto check doesn't return any issues

**Comment by softwarenerd** [comment]
We are investigating this issue. There appears to be an intermittent outage with our cloud provider.

**Comment by BisangL** [comment]
Still same problem here...

**Comment by krcabrer** [comment]
I have the same problems.
I try from a Windows platform, and a Linux one, with rstudio server and it works in either.

**Comment by mcanouil** [comment]
@BisangL and @krcabrer 
https://github.com/quarto-dev/quarto-cli/issues/7639#issuecomment-1819545535

**Comment by fileds** [comment]
I have the same issue from a Linux machine.

**Comment by mcanouil** [comment]
Please avoid posting comments which actually hides the one stating the issue is under investigation to future users that have the issue.

Instead, use reaction, either on the original report or on the status comment:
- https://github.com/quarto-dev/quarto-cli/issues/7639#issue-2002127549
- https://github.com/quarto-dev/quarto-cli/issues/7639#issuecomment-1819545535

Thank you all for your understanding!
We'll hope to get the issue with the cloud provider sorted out as soon as possible and will update here.

**Comment by Fgazzelloni** [comment]
I experienced the same issue and tried `quarto::quarto_publish_site()`. I have been able to publish some of the updates using `bookdown`, which turned out to be another feasible option. However, I experienced further disruption today with the rendering functions—both the `quarto::quarto_render()` from the console and the `quarto render` from the terminal. The content is not updated, and the quarto files are not rendered.

**Comment by JulianRamajo** [comment]
Just now I got the same result when trying to update:

quarto publish quarto-pub --no-render

[✓] Preparing to publish site
ERROR: API Error: 500 - Internal Server Error

Error: API Error: 500 - Internal Server Error
    at QuartoPubClient.createDeploy (file:///Applications/quarto/bin/quarto.js:111384:23)
    at async file:///Applications/quarto/bin/quarto.js:109026:22
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:56614:9)
    at async handlePublish (file:///Applications/quarto/bin/quarto.js:109004:5)
    at async publishSite (file:///Applications/quarto/bin/quarto.js:121230:38)
    at async publish5 (file:///Applications/quarto/bin/quarto.js:121448:61)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:121404:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:121415:9)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:121392:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)

**Comment by mcanouil** [comment]
@JulianRamajo https://github.com/quarto-dev/quarto-cli/issues/7639#issuecomment-1821442133

**Comment by HisLabAAU** [comment]
Got this as well. ERROR: API Error: 500 (Internal Server Error)

**Comment by mcanouil** [comment]
> [!IMPORTANT]
> Please avoid posting comments which actually hides the one stating the issue is under investigation to future users that have the issue.

Instead, use reaction, either on the original report or on the status comment:
- https://github.com/quarto-dev/quarto-cli/issues/7639#issue-2002127549
- https://github.com/quarto-dev/quarto-cli/issues/7639#issuecomment-1819545535

Thank you all for your understanding!

> [!NOTE]
> We'll hope to get the issue with the cloud provider sorted out as soon as possible and will update here.

**Comment by victorfeagins** [comment]
I was able to publish to quarto pub today

**Comment by mcanouil** [comment]
The issue should be resolved now and publishing to Quarto Pub should no longer return the error.
Thank you all for the reports.
Please react (or eventually comment) if you no longer has the issue.

*For eventual future readers, the issue is not from Quarto CLI but from Quarto Pub hosting services.*

**Comment by ef10007** [comment]
I can publish now. Thanks for the help!

**Comment by tom67** [comment]
Thanks for resolving the issue, I've pretty got used to quarto and quarto pub.

**Comment by dani-f** [comment]
Hi, is it possible that this error 500 is appearing again? In my case, I cannot republish a website on quarto-pub, unfortunately. Would appreciate if you have a look into this. Thank you!

**Comment by ASKurz** [comment]
As of this morning, I'm currently getting

> ERROR: API Error: 500 - Internal Server Error

**Comment by ntluong95** [comment]
I got the same error today: ERROR: API Error: 500 - Internal Server Error

**Comment by dnidz** [comment]
I'm also getting the same error publishing to quarto.pub: ERROR: API Error: 500 - Internal Server Error

**Comment by BisangL** [comment]
Hello,

the issue has reappeared today. Everything was functioning normally last Monday/Tuesday, but I am now (and yesterday) unable to publish either new or previously created documents.

Error encountered:
API Error: 500 – Internal Server Error

Thank you very much!
Léonie
(Posting this update as the problem has resurfaced.)

**Comment by raldoori** [comment]
Hello,

I also just encountered the same error:
[>] Preparing to publish site
ERROR: API Error: 500 - Internal Server Error

Could it be due to the Cloudflare outage that happened yesterday?

**Comment by cderv** [comment]
We're looking into it: 
- #13706
