### ISSUE TITLE
Banner Image Not Showing On All Pages

### ISSUE THREAD

**Issue by zief0002** [quarto-dev/quarto-cli#7647]
### Bug description

 I want a banner-like image to show up on all of my pages. I am using the YAML `body-header: "./assets/body-header.qmd"`, which works for all of my pages except for the blog posting pages. On those pages, instead of showing the image, I just get the path name at the top of the post written as text. You can see the results at:

The GH repo with all of the files is: [https://github.com/zief0002/data-dreaming-quarto](https://github.com/zief0002/data-dreaming-quarto). I have kludged this by adding the image separately to the main pages.

The `body-header.qmd` file includes the following:

```
:::{.column-screen}
![](./img/typewriter.png)
<div class="banner-text">
# Andrew Zieffler

Academic. Data lover. Statistics enthusiast.
</div>
:::
```

<br />

I was thinking it might be a file hierarchy issue,since all of the pages it is working on are at the same level:

```
├── index.qmd
├── assets
│   ├── body-header.qmd
├── img
│   ├── typewrtiter.png
├── posts
│   ├── 2022-11-21-graduation-2022
│   │   └── index.qmd
```

[This page ](https://quarto.org/docs/websites/website-tools.html)seems to suggest that starting the figure path with a slash will allow it to be used on all levels of the page, but that doesn't work. (I have tried this in both the pathname in the YAML and for the figure pathname in the body-header.qmd file.) I was hoping using the root in the pathname (`./assets/...`) would alleviate that, but it did not.

Thanks
Andy

### Steps to reproduce

<https://github.com/zief0002/data-dreaming-quarto>

### Expected behavior

I expected the banner image to show up on all of the posts and main pages

### Actual behavior

Depending on the pathname used in the YAML, the banner image shows up in the main pages or the posts, but not both

### Your environment

- IDE: RStudio Version 2023.06.1+524 (2023.06.1+524)
- OS: MacOS Sonoma 14.0 (23A344)

### Quarto check output

```{bash}
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.44.1
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Could you share a smaller example? I don't think everything n your repository is needed and is actually making difficult to focus on your issue.

**Comment by dragonstyle** [comment]
Per the documentation (<https://quarto.org/docs/websites/website-tools.html#headers-footers>, the `body-header` field accepts markdown to display on each page (not a file to render). Something like this should be more like what you're after:

````
website:
  title: "Andrew Zieffler"
  site-url: "https://datadreaming.org"
  repo-url: "https://www.github.com/zief0002/data-dreaming-quarto"
  body-header: |
    ::::{.column-screen}
    ![](/img/typewriter2.png)
    
    :::{.banner-text}
    # Andrew Zieffler
    Academic. Data lover. Statistics enthusiast.
    :::
    
    ::::

    <br />
````
