### ISSUE TITLE
Shortcodes for embedding tweets

### ISSUE THREAD

**Issue by alexpghayes** [quarto-dev/quarto-cli#765]
On https://quarto.org/docs/authoring/shortcodes.html I see that tweet shortcodes are on the todo list. I just want to say that I will use them as soon as they are available!

If you can point me in the right direction I can also start on a PR for this.

**Comment by jjallaire** [comment]
We are working on this now and will have some updates soon!

**Comment by jjallaire** [comment]
There is now an API for adding your own shortcodes: https://quarto.org/docs/authoring/shortcodes.html

We will definitely be adding a built-in shortcode for tweets -- if you want to take a shot at prototyping it using the API that would be great!

**Comment by alexpghayes** [comment]
I start looking into this but got a little overwhelmed. Here's what I've found so far.

The canonical way to embed a tweet is request an HTML embedding of the tweet from twitter, using [this endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/get-statuses-oembed). There are several options for this endpoint we probably also want to expose. Note that you do not need the user handle, only the tweet id (https://stackoverflow.com/questions/41090108/how-to-embed-a-tweet-on-a-page-if-i-only-know-its-id).

Twitter then returns an HTML chunk like the following:

```html
<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Sunsets don&#39;t get much better than this one over <a href=\"https://twitter.com/GrandTetonNPS?ref_src=twsrc%5Etfw\">@GrandTetonNPS</a>. <a href=\"https://twitter.com/hashtag/nature?src=hash&amp;ref_src=twsrc%5Etfw\">#nature</a> <a href=\"https://twitter.com/hashtag/sunset?src=hash&amp;ref_src=twsrc%5Etfw\">#sunset</a> <a href=\"http://t.co/YuKy2rcjyU\">pic.twitter.com/YuKy2rcjyU</a></p>&mdash; US Department of the Interior (@Interior) <a href=\"https://twitter.com/Interior/status/463440424141459456?ref_src=twsrc%5Etfw\">May 5, 2014</a></blockquote>\n<script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>
```

The way this works is that, if the tweet is still publicly available on Twitter, the Twitter Javascript goes off and turns this blockquote in a nice twitter card. If the tweet has been deleted, the text of the tweet remains in the blockquote but the tweet isn't turned into a nice card. This is a nice failsafe against deleted tweets. However, it means that the lua shortcode filter needs to be able to make an http request. I don't know how to do this, mostly because I'm not sure if an http library comes bundled with the Pandoc lua stuff.

In any case, I think we want the logic of the shortcode to work like this:

1. Request the HTML embedding of the tweet from Twitter.
2. If we get a response, use it
3. If we don't embed the tweet with the following:

```html
<blockquote class="twitter-tweet">
  <a href="https://twitter.com/x/status/{{status id}}"></a> 
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
```

This fallback embedding should work roughly the same as the canonical approach, but if the tweet is deleted it won't retain the text of the tweet.

**Comment by jjallaire** [comment]
I'm wondering why we need the fallback at all? (i.e. what are the conditions under which the initial request would fail but the subsequent one would complete)

**Comment by DavisVaughan** [comment]
I would also like to request a YouTube shortcode, in blowdown it looked like `blogdown::shortcode("youtube", id = "_u5k-Fk2bfU")`

**Comment by mcanouil** [comment]
I am going to close this as there quite few extensions now for this:
look for "social" on <https://m.canouil.dev/quarto-extensions/extensions.html> or <https://quarto.org/docs/extensions/>.
