### ISSUE TITLE
Undefined variable when using custom scss

### ISSUE THREAD

**Issue by Tutuchan** [quarto-dev/quarto-cli#7651]
### Bug description

Hi,

I'm trying to use custom theming for a website, using [this documentation](https://quarto.org/docs/output-formats/html-themes.html#theme-options).

However, even when using the examples in the documentation, I get an `Undefined variable` error when using any Bootstrap Sass variable.

### Steps to reproduce

Here is a [reprex repository](https://github.com/Tutuchan/quartotheme).

### Expected behavior

I expect the SCSS to compile successfully to CSS using the provided SASS variables.

### Actual behavior

```
Error: Undefined variable.
     ╷
1041 │ $body-color:            $gray-700 !default;
     │                         ^^^^^^^^^
```

### Your environment

- IDE: VSCode 1.84.2 
- macOS Sonoma 14.0 (23A344)

I tried both with Quarto 1.3.450 and 1.4.507.

### Quarto check output

```
❯ quarto check
Quarto 1.4.507
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.507
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /Users/pformont/.pyenv/versions/3.11.1/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.39
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
This is not a bug but a matter of ordering the elements, see <https://quarto.org/docs/output-formats/html-themes-more.html>.
You are trying to retrieve a variable not yet known in "default".

The following will work:

```sccs
/*-- scss:defaults --*/
$h2-font-size:          1.6rem !default;
$headings-font-weight:  500 !default;

/*-- scss:rules --*/
$body-color:            $gray-700 !default;
h1, h2, h3, h4, h5, h6 {
  text-shadow: -1px -1px 0 rgba(0, 0, 0, .3);
}

**Comment by cderv** [comment]
@mcanouil if this is really how a custom variables that uses Bootstrap variables needs to be defined (in `rules`), then we definitely need to update our documentation at https://quarto.org/docs/output-formats/html-themes.html#theme-options

as we show exactly what @Tutuchan has tried.

**Comment by cderv** [comment]
This was asked in the past at 

* https://github.com/quarto-dev/quarto-cli/discussions/4071 (with answers https://github.com/quarto-dev/quarto-cli/discussions/4071#discussioncomment-6720268) 

and we did no update our doc, so we need not to forget this time.

**Comment by Tutuchan** [comment]
Thanks for the quick answers @mcanouil @cderv !

I figured it was something really simple but I couldn't find any related issue, so thank you for that.

I indeed no longer have an error when moving to the `rules` section.

However, specifying, _e.g._ `$body-bg: $orange-800 !default;` has no impact on the document, while using:

```
body {
  background-color: $orange-800;
}
```

properly changes the background color.

I understand this is a different issue, do you want me to open another ticket ?

**Comment by mcanouil** [comment]
This is the same ordering issue described in the link I shared.

**Comment by Tutuchan** [comment]
Ok, I understand better now, sorry for the inconvenience.
