### ISSUE TITLE
Logical values given to the execute_params list of quarto_render incorrectly parsed

### ISSUE THREAD

**Issue by Eugloh** [quarto-dev/quarto-cli#7662]
### Bug description

Logical parameters in the list given to execute_params for R quarto::quarto_render will be converted to yaml yes/no and interpreted as characters.  

### Steps to reproduce

**example file: test.qmd** 

```
---
title: "test"
format: html
params:
  adcode: yes
---
```

```{r}
class(params$adcode)
```

**render with command line:**

quarto::quarto_render(
    input = "test.qmd",
    execute_params = list("adcode"=T)
)

### Expected behavior

class(params$adcode)

[1] "logical"

### Actual behavior

class(params$adcode)

[1] "character"

### Your environment

- IDE : RStudio 2023.09.1 Build 494
- OS : Ubuntu 22.04.3 LTS

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.5: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.232
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 4.9.1
      Kernels: julia-1.6, python3

(-) Checking Jupyter engine render....[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fd9a58f3370>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_events.py", line 690, in __del__
    self.close()
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 87, in close
    self._close_self_pipe()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 94, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 272, in _remove_reader
    key = self._selector.get_key(fd)
  File "/usr/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
I think `quarto::quarto_render` is creating yaml 1.1 output instead of yaml 1.2.

With that said, this should be filed at https://github.com/quarto-dev/quarto-r

**Comment by mcanouil** [comment]
FYI, it's the R package `yaml` that does that and to avoid this, you need to use an "handler", e.g.:

```r
yaml::write_yaml(
  ...,
  handlers = list(
    logical = function(x) {
      result <- ifelse(x, "true", "false")
      class(result) <- "verbatim"
      result
    }
  )
)
```

Note that indeed it uses YAML 1.1 as they do state: https://cran.r-project.org/package=yaml

CC @cderv

**Comment by cderv** [comment]
This has already been reporting in **quarto** R package 

* https://github.com/quarto-dev/quarto-r/issues/124

and fixed last month https://github.com/quarto-dev/quarto-r/commit/5207b6c1bfe2e3dca12d45644227945c5312abf3 

You need for now dev version of the package but we'll make a release soon. 
You can install easily using 
````r
install.packages('quarto', repos = c('https://quarto-dev.r-universe.dev', 'https://cloud.r-project.org'))
````
