### ISSUE TITLE
Insert key

### ISSUE THREAD

**Issue by Emily-A-Roberts** [quarto-dev/quarto-cli#7664]
### Bug description

Hi, I was typing in a code chunk and noticed that I must have accidentally toggled the insert key, activating the text overwrite function. However, I couldn't turn off the overwrite function using the insert key toggle. Later I was typing outside of the code chunk and realized that I could again toggle the insert key and finally turn overwrite off. It's as if the insert key toggle outside of the code chunk turns on the insert key toggle in the code chunk and this can't be turned off inside the code chunk. 

### Steps to reproduce

Click "insert" button outside a code chunk to toggle the overnight function on
Write inside a code chunk
Toggle "insert" button inside a code chunk to turn "insert" on and off. The bug was that the overwrite function did not turn off. 
Click "insert" button outside a code chunk to toggle the overwrite function off again.

### Expected behavior

The overwrite function should always toggle on and off based on the insert button

### Actual behavior

There is some strange dependency of whether you are in or out of a code chunk. 

### Your environment

IDE R studio 2022.07.0 +548
Windows 10 Enterprise

### Quarto check output

A new release of Deno is available: 1.28.2 → 1.38.2 Run `deno upgrade` to install it.
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.340
      Path: C:\Users\emily.roberts\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/Users/emily.roberts/AppData/Local/Programs/R/R-4.3.1
      LibPaths:
        - C:/Users/emily.roberts/AppData/Local/Programs/R/R-4.3.1/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
I am not entirely sure to follow but it seems it has nothing to do with Quarto the command line tool instead it seems to be RStudio IDE problem.

If so it has to be reported on RStudio IDE GitHub repository at <https://github.com/rstudio/rstudio>.
