### ISSUE TITLE
Self-contained html with OJS stopped working

### ISSUE THREAD

**Issue by novotny1akub** [quarto-dev/quarto-cli#7671]
### Bug description

Self-contained html documents with OJS code seem to stop working with the latest Quarto (stable). It worked with version 1.2.280. Currently, one needs a webserver to correctly display OJS html documents (e.g. using Render in RStudio IDE).

### Steps to reproduce

````qmd
---
title: "Issue"
format:
  html:
    self-contained: true
---

```{ojs}
//| echo: false

data = [
  { "x": 1, "y": 1 },
  { "x": 2, "y": 2 },
  { "x": 3, "y": 3 }
]

Plot.plot({
  marks: [
    Plot.lineY(data, {x: "x", y: "y"})
  ]
})

```
````

### Expected behavior

This code should produce a working html document as it worked with Quarto version 1.2.280 as can be seen in this picture.
![quarto_1_2_280](https://github.com/quarto-dev/quarto-cli/assets/39886440/b959c850-8a9d-4ba3-8917-27fb432dd4f6)

### Actual behavior

With the latest Quarto version (stable), the standalone html document no longer works. One needs to use a webserver (e.g. Quarto render).
![quarto_latest_stable](https://github.com/quarto-dev/quarto-cli/assets/39886440/cdfc9046-5263-46df-94be-f355e25e668c)

### Your environment

IDE: RStudio 2023.06.1 Build 524
OS: Windows 10 Pro

### Quarto check output

![image](https://github.com/quarto-dev/quarto-cli/assets/39886440/005410d5-78e0-4df3-a130-4a8b7f1f972b)

**Comment by novotny1akub** [comment]
There is a post in Quarto CLI discussion about this issue, but it does not contain a formal error description and a reprex for the issue [post](https://github.com/quarto-dev/quarto-cli/discussions/7487).

**Comment by mcanouil** [comment]
Thanks for the report and the code example.

Side note: `self-contained` is deprecated nearly since Quarto 1.0 as highlighted in the documentation.
Please use `embed-resources` instead.

**Comment by mcanouil** [comment]
Your issue is actually the one in #5680.

**Comment by novotny1akub** [comment]
Thank you for your swift answer @mcanouil. It seems to me that you are able to reproduce the issue. My reprex works for you with a webserver. It does not work when opening the standalone html file. I just want to reiterate that with Quarto 1.2.280, this example worked without a webserver.

**Comment by mcanouil** [comment]
> I just want to reiterate that with Quarto 1.2.280, this example worked without a webserver.

Observable version in it aren't the same.

**Comment by novotny1akub** [comment]
So this behaviour emerges as a consequence of changes in OJS stdl recent versions? I wasn't aware, thanks for bringing this to my attention. I thought this was caused by changes in Quarto.

**Comment by novotny1akub** [comment]
I had a brief look at the [PR](https://github.com/romanzenka/quarto-cli/commit/91957158f08d414932dc15e87e118e10828b3ad4) from romanzenka that might be able to bring some of the OJS functionality back for standalone html documents. It seems to me that he does not change the OJS stdl although I stand corrected on this one.

**Comment by mcanouil** [comment]
I can't tell you with certainty:
- changes in Pandoc
- changes in Observable
- changes in Quarto
- changes in Quarto & Pandoc
- changes in Pandoc & Observable
- etc.

Many things interplay here and Quarto tries to make those third parties play nice together but those third parties do not care if they break or not something.

If the issue is opened, it means it was not intended by Quarto.
Otherwise, the issue would have been closed as "not planned" and the change log would have a line stated that this is no longer possible (very very unlikely to just remove partially a feature).

You may have noticed that there are more than a thousand issues but not that many developers.
So there are priorities which can be changed for example if "a lot" of users react/upvote an issue which will tell the team that maybe that should be the focus for the current or next release.

**Comment by mcanouil** [comment]
> I had a brief look at the [PR](https://github.com/romanzenka/quarto-cli/commit/91957158f08d414932dc15e87e118e10828b3ad4) from romanzenka that might be able to bring some of the OJS functionality back for standalone html documents. It seems to me that he does not change the OJS stdl although I stand corrected on this one.

This is not PR, it is simply a fork, the team cannot use that (see the [Pull Request list](https://github.com/quarto-dev/quarto-cli/pulls)).

Also this fork is quite obsolete/outdated.

**Comment by novotny1akub** [comment]
I understand Quarto is a complex project trying to stitch together many different technologies, and it is often very hard to make them play nicely together. It would be helpful to have a rough estimate of when this might be solved. Apologies for calling it a PR.

**Comment by cscheid** [comment]
> It would be helpful to have a rough estimate of when this might be solved

We've now concluded that this is simply not a practical problem for us to solve. So the estimate, is, unfortunately, "never".

**Comment by gl2324** [comment]
For everybody that is using VSCode with quarto, there is the possibility of using the [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) Addon to host the HTML-Result. 

It is not an optimal solution but it lets me share the Quarto Output with my colleagues at least.

Don't forget to check the **Use Local Ip** setting when using the Live Server Addon
