### ISSUE TITLE
When rendering a .qmd file using knitr and importing pymc >=v5.9.0, quarto crashes

### ISSUE THREAD

**Issue by jobrachem** [quarto-dev/quarto-cli#7684]
### Bug description

When rendering a .qmd file using knitr and importing pymc >=v5.9.0, quarto crashes.

Notably, this does NOT happen, if I simply execute the code chunk manually. It only occurs while rendering. It also does NOT happen, if I do not specify `knitr` as the engine.

### Steps to reproduce

Try to render the following `.qmd` document, using a Python virtual environment with `pymc` version `5.9.0` or higher.

````qmd
---
engine: knitr
---

```{python}
import pymc as pm
```
````

### Expected behavior

Rendering the minimal example file should result in the following `.html` output file:

![image](https://github.com/quarto-dev/quarto-cli/assets/37882800/dc4e8e4b-6b9a-4bcd-95d4-8f2da378dff6)

### Actual behavior

First, RStudio produes the following pop-up:

![image](https://github.com/quarto-dev/quarto-cli/assets/37882800/f3d0b606-9c79-464b-a650-47f3346fe52f)

The rendering output contains the following error message:

```
processing file: 017-pymc-test.rmarkdown
  |...................................                 |  67% (unnamed-chunk-1)Quitting from lines 6-7 (017-pymc-test.rmarkdown) 
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  TypeError: decode() argument 'encoding' must be str, not None
Run `reticulate::py_last_error()` for details.
Calls: .main ... py_capture_output -> force -> <Anonymous> -> py_call_impl
                                                                                                            
Execution halted
```

No `.html` output is produced.

### Your environment

- RStudio Version 2023.09.1+494 (2023.09.1+494)
- MacOS Ventura 13.4.1

### Quarto check output

```bash
quarto check             

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.42
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
> It also does NOT happen, if I do not specify knitr as the engine.

When you are running a python chunk while setting `engine: knitr`, it will run python through **reticulate** R package. You need to be sure that your reticulate python environment is correctly setup, as this could be different from the Python 3 installation detected in `quarto check` - this will be **reticulate** detecting python. See https://github.com/rstudio/reticulate/

Quarto default behavior for python cell when no engine is set, is to evaluate using Jupyter as engine. https://quarto.org/docs/computations/execution-options.html#engine-binding

So if error there is, then it comes for **reticulate**. 

Error is the same with R Markown - so it is not just Quarto. I would open an issue on **reticulate** repo for this 

```markdown
---
title: "unicode_pdf"
output: html_document
---

```{python}
import pymc as pm
```
````

````
==> rmarkdown::render('test.Rmd');

  |....................................................| 100% [unnamed-chunk-1]

processing file: test.Rmd

Quitting from lines 9-10 [unnamed-chunk-1] (test.Rmd)
Error in `py_call_impl()`:
! TypeError: decode() argument 'encoding' must be str, not None
Run `reticulate::py_last_error()` for details.
Backtrace:
  1. rmarkdown::render("C:/Users/chris/Documents/test.Rmd", encoding = "UTF-8")
  2. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. knitr:::process_file(text, output)
  8. knitr:::process_group.block(group)
  9. knitr:::call_block(x)
     ...
 13. knitr (local) engine(options)
 14. reticulate::eng_python(options)
 15. reticulate:::py_compile_eval(snippet, compile_mode)
 18. builtins$eval(compiled, globals, locals)
 19. reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
                                                                                                            
Exécution arrêtée
````

**Comment by jobrachem** [comment]
Alright, thanks for the quick reply @cderv ! I'll open an issue with reticulate and link it here when I have done that.

**Comment by cderv** [comment]
I opened it already 

https://github.com/rstudio/reticulate/issues/1508

**Comment by jobrachem** [comment]
Awesome, thanks!

**Comment by cderv** [comment]
This was an upstream upstream issue, and this is now fixed it seems. So I am closing. 

Context of the issue at
* https://github.com/pymc-devs/pytensor/pull/617
