### ISSUE TITLE
Easier way to get just the prefix under the figure (and not the caption text) when journals ask for figure captions on separate page?

### ISSUE THREAD

**Issue by tonyaseverson** [quarto-dev/quarto-cli#7691]
Some scientific journals ask for figure captions to be provided on a separate manuscript page rather than underneath the figure. I can get Quarto to render "Figure 1. Caption text." on a separate page, but when I provide fig-cap: "" in the chunk, captions displayed in the document under the figure are like this: "Figure 1: ?(caption)".

Other things I tried include leaving out the fig-cap line, which yielded "Figure 1: TRUE", and each of the following:
#| fig-cap:               # Complains, but runs and shows Figure 1: FALSE
#| fig-cap: " "          # Figure 1: ?(caption)
#| fig-cap: FALSE    # Figure 1: FALSE

Finally, while writing this, I found something that will do what I want, but something less clunky would be nice.
#| fig-cap: \hspace{1 mm}

**Comment by cderv** [comment]
Did you try just not passing Caption ? 

````
---
title: "Untitled"
format:
  html: default
---

```{r}
#| label: fig-test
plot(head(cars))
```
````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/5ad446a8-39e3-488a-93f8-7feeb46acd51)

**Comment by tonyaseverson** [comment]
Yes, I did. 

> Other things I tried include leaving out the fig-cap line, which yielded "Figure 1: TRUE"

And I just checked to see if the document format makes a difference--it doesn't. (I originally rendered a docx file.)

**Comment by mcanouil** [comment]
Which version of Quarto are you using?

**Comment by tonyaseverson** [comment]
> quarto_version()
[1] ‘1.3.326’

**Comment by mcanouil** [comment]
Could you try at least the latest stable 1.3? (And possibly the latest 1.4 pre-release)

**Comment by tonyaseverson** [comment]
````qmd

---
title: "Untitled"
format: 
  docx: default
---

{r}
#| label: fig-test
plot(head(cars))

````

Here is a minimum reproducible example (still with v1.3.326). The format I'm using is docx, but when I ran cderv's example with html, that also was messed up. 

I will install the latest stable 1.3 next.

**Comment by tonyaseverson** [comment]
Same issue occurs using v. 1.3.450.

When I try to install a development version I get this error message when trying to get the quarto_version:

Error in fetch(key) : 
lazy-load database '/Users/me/Library/R/4.0/library/quarto/help/quarto.rdb' is corrupt

**Comment by mcanouil** [comment]
This is an error from the R package not Quarto CLI which is corrupted as the message says, thus you need to reinstall it.

Could you try without using R?
You don't need R to run Quarto.

**Comment by tonyaseverson** [comment]
Yes! That works! 

Thanks to everyone for all your help.

**Comment by mcanouil** [comment]
Thanks for verifying it was indeed working in 1.4.
