### ISSUE TITLE
`quarto preview` with post-render step doesn't launch preview server

### ISSUE THREAD

**Issue by gadenbuie** [quarto-dev/quarto-cli#7710]
### Bug description

With quarto 1.4, the presence of a `post-render` step seems to prevent `quarto preview` from launching the preview server.

### Steps to reproduce

I have a website with essentially the following `_quarto.yml`

```yaml
project:
  type: website
  post-render:
    - "cp static/foo _site/foo"
```

### Expected behavior

With quarto 1.3.450, or when commenting out the `post-render` setting, `quarto preview` launches a preview server and opens the browser window.

```
> quarto -v
1.3.450
> quarto preview
Preparing to preview

Watching files for changes
Browse at http://localhost:6180/

GET: /
```

If I modify a file to get `quarto preview` to render a qmd before serving, it renders the changed document, calls `cp`, and then starts the preview server.

```
> quarto preview
Preparing to preview
[1/2] blog/awesome-post/index.qmd
[2/2] index.qmd

cp

Watching files for changes
Browse at http://localhost:5048/blog/awesome-post/index.html
GET: /blog/awesome-post/index.html
```

### Actual behavior

Running `quarto preview` with 1.4 calls the `cp` command and then exits without starting the preview server.

```
> quarto -v
1.4.510
> quarto preview
Preparing to preview

cp
> 
```

### Your environment

- OS: MacOS Ventura 13.6
- IDE: N/A (Terminal)

### Quarto check output

```
Quarto 1.4.510
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.510
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/garrick/Library/TinyTeX/bin/universal-darwin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.0
      Path: /Users/garrick/.pyenv/versions/3.10.0/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources
      LibPaths:
        - /Users/garrick/Library/R/x86_64/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK 
```

**Comment by jjallaire** [comment]
Thanks for reporting this but I am unable to repro! I did note that in your repro you used `_stie` (which is a folder that wouldn't actually exist).

**Comment by gadenbuie** [comment]
Oops. The `_stie` typo was my fault in thinking I could type the reprex instead of copying it 😆.

Thanks for looking into this! I think I've uncovered the problem: I was actually using `cp -rn source dest`, which exits with status code 1 if there are no files to copy. So I guess the change that happened here is the `quarto preview` would previously start even if the post-render scripts errored, and now it stops. Which certainly seems like the right thing to do. 

Maybe quarto could add an error message in case the process exits with an error but without an additional message (as happens with `cp -rn`?

**Comment by jjallaire** [comment]
Okay, glad we got to the bottom of it!
