### ISSUE TITLE
Typst: Images aren't sized responsively in divs that use layout attributes

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#7718]
### Bug description

When `format: typst`, images placed side by side inside a fenced div with `layout-ncol: 2` aren't resized to fit. 

Intermediate `.typ` shows:
````
#block[
]
#grid(
columns: (50.0%, 50.0%), gutter: 1em, rows: 1,
  rect(stroke: none, width: 100%)[
#box(width: 1080.0pt, image("cat.jpg"))

],
  rect(stroke: none, width: 100%)[
#box(width: 1080.0pt, image("dog.jpg"))

],
)
````
Switching the `width` inside the `box` calls to `100%` solves the problem.

### Steps to reproduce

````
---
title: Layout with images
format: pdf
---

::: {layout-ncol=2} 

![](cat.jpg)

![](dog.jpg)

:::
````

[dog.jpg](https://github.com/quarto-dev/quarto-cli/assets/25964/c5f02842-acb0-4214-852c-6108c0a13540)
[cat.jpg](https://github.com/quarto-dev/quarto-cli/assets/25964/abde8515-0551-49d4-aedb-6c8c38c45794)

### Expected behavior

<img width="200" alt="Screenshot 2023-11-27 at 1 47 50 PM" src="https://github.com/quarto-dev/quarto-cli/assets/25964/ad08ebd8-6143-4f7f-8d0e-50c3522a4cab">

### Actual behavior

<img width="200" alt="Screenshot 2023-11-27 at 1 47 30 PM" src="https://github.com/quarto-dev/quarto-cli/assets/25964/d4a4483c-ca21-4a0d-8c98-110c9149fdee">

### Your environment

OS: MacOS Sonoma 14.0

### Quarto check output

```
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/wickhamc/Documents/posit/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/wickhamc/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.0
      Path: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Thanks, I can repro this.

Element sizing in Typst works differently from LaTeX, and I'm sure we have a number of other such issues lurking. ([so does Pandoc](https://github.com/jgm/pandoc/issues/9104), it turns out)

What's happening here is that, because of that issue, Pandoc now inserts the image width into the document. Unfortunately, Typst takes width in pixels to mean "yes, make it this big, independently of what the outside constraints say".

I'm not sure about the best fix here. Setting `width: 100%` to _these_ images solves the problem indeed, but I'm not sure if it would introduce other layout problems.
