### ISSUE TITLE
quarto-blog: references are not rendering in a blog post 

### ISSUE THREAD

**Issue by ManuelSpinola** [quarto-dev/quarto-cli#775]
References are not rendering in a quarto blog post. I have the references.bib file in the folder of the post but is not rendered in the html output. 

In my YAML I have:

bibliography: references.bib

**Comment by jjallaire** [comment]
Could you provide a more complete example or what is failing? (as when we test this locally the bibliography does in fact work)

If you aren't actually citing any of the bibliography items you might need a `nocite` directive:

```yaml
nocite: @*
```

**Comment by ManuelSpinola** [comment]
Thank you very much.  I was doing a mistare, is working fine right now.
