### ISSUE TITLE
`include`d files with footnotes break enumerated counters

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#7772]
### Bug description

When adding items to an enumerated list via `include`, footnotes break the counter. I think this is because of the footnote that is not aligned with the text in the enumerated item in the  `include`d file. However, the RStudio Visual Editor does not align it there.

### Steps to reproduce

Clone and render https://github.com/mine-cetinkaya-rundel/test-include-footnote.

This repo includes an `index.qmd` that calles the `_item_1.qmd` and `item_2.qmd` files via `include` shortcode and attempts to place their contents in an enumerated list.

### Expected behavior

I expected the counter to continue to `2` for Item 2.

### Actual behavior

The counter breaks, starting with `1` again. See https://mine-cetinkaya-rundel.github.io/test-include-footnote/.

And here are screenshots of the issue:

- No footnote in Item 1, no problem:

<img width="1624" alt="Screenshot 2023-12-03 at 4 39 00 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/d1493d97-abe8-4633-8f24-40299a8a5bad">

- Footnote in Item 1, counter broken for Item 2:

<img width="1624" alt="Screenshot 2023-12-03 at 4 40 44 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/ebb54740-0021-404b-b8d1-6ab8110af279">

- Footnote in Item 1 indented to align with text of Item 1, counter *not* broken for Item 2:

<img width="1624" alt="Screenshot 2023-12-03 at 4 41 31 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/ddc8aae2-b74c-4a36-9c4a-d3ac02c9e825">

- Switching over to visual editor moves footnote in Item 2, breaking the counter again for Item 2:

<img width="1624" alt="Screenshot 2023-12-03 at 4 42 19 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/3e8058f8-ce26-46ff-b704-62f7275a7128">

Maybe this can be solved with a fix to the visual editor (which means moving this issue to the rstudio repo) or maybe it can be fixed with how `include` operates in these situations. I feel like fix to the visual editor might not be the way to go since I've never seen footnotes indented like that in documents authored with the source editor. But I'm not sure what the best approach is.

### Your environment

- IDE: RStudio Version 2023.12.0+351 (2023.12.0+351)
- Mac OS: Ventura 13.5

### Quarto check output

```bash
Quarto 1.4.515
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.515
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mine/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Thanks for the report ! 

I believe `include` feature is currently equivalent to a copy paste of the content from included doc to main. 
And I think you cannot add footnote in list item under an item without using proper indentation as you did later

Footnotes can be placed anywhere including in List 
> They may appear anywhere except inside other block elements (lists, block quotes, tables, etc.). Each footnote should be separated from surrounding content (including other footnotes) by blank lines.

but indentation needs to be done 
> A list item may contain multiple paragraphs and other block-level content. However, subsequent paragraphs must be preceded by a blank line and indented to line up with the first non-space content after the list marker.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks @cderv! I wonder if this means visual editor behaviour needs to change then?

**Comment by cscheid** [comment]
Yes, @cderv is correct. It's not feasible for include statements to be aware of Markdown syntax (so that they would, eg, automatically indent themselves to the right place in a code block or enumerated list). You really ought to think of them as "paste the contents of the included file here", and our documentation is [relatively explicit about that](https://quarto.org/docs/authoring/includes.html). I'm not sure about the interactions with the rest of the system, but I'm pretty sure this isn't an include bug.

**Comment by cscheid** [comment]
Thinking a bit further about this, it _is_ unfortunate that the syntax of Markdown is not well-suited for nested, "syntax-oblivious" includes.

There are some parts of Pandoc's Markdown syntax that are well-suited for this, namely fenced divs. So, although this is admittedly ugly, one way to get the nesting to work is to use divs instead of lists in the input, and then replace the divs with lists in a Lua filter (for example, by tagging the divs with a particular class).

**Comment by mine-cetinkaya-rundel** [comment]
This might be a good / the only solution. I'm using `include` to include exercises in a textbook from individual .qmd files for each exercise and I need them listed in an enumerated list.

**Comment by cscheid** [comment]
(I'm going to close this one, but we can continue having the discussion of how to work around the Markdown syntax)
