### ISSUE TITLE
Discrepancy between `output: 'asis'` and `result: 'asis'`

### ISSUE THREAD

**Issue by kylebutts** [quarto-dev/quarto-cli#7781]
I'm trying to understand if this is a bug or not, or if the documentation should be improved. There is a discrepancy when using `output: 'asis'` and `result: 'asis'` based on the indentation (see below for reprex). When using `result = 'asis'` as suggested in [the docs](https://quarto.org/docs/reference/cells/cells-knitr.html), the result is indented in the resulting markdown file, making it not render properly on github and other places. Using `output: 'asis'` does not indent as is preferred.

## Reprex:
Rendering this `.qmd` file:
```````md
---
format: gfm
---

```{r markdown-result, result = 'asis'}
cat(r'(
# Header

Text
)')
```

```{r markdown-output, output = 'asis'}
cat(r'(
# Header

Text
)')
```
```````
yields this `.md` file:
```````md

``` r
cat(r'(
# Header

Text
)')
```


    # Header

    Text

``` r
cat(r'(
# Header

Text
)')
```

# Header

Text

```````

Rendering that produces the following markdown:

``` r
cat(r'(
# Header

Text
)')
```

    # Header

    Text

``` r
cat(r'(
# Header

Text
)')
```

# Header

Text

**Comment by cderv** [comment]
Yes I do believe `results: asis` should lead same results to `output: asis` for **knitr** engine. 

Running latest dev version, and packages I don't see any difference in indentation from both options. 

Can you share your Quarto version and knitr version (and try again with updated version if not the latest) ? 

This may be something we have fixed in 1.4 already (I don't recall specifically)

Thank you

**Comment by cderv** [comment]
Oh sorry I got mixed up by your example. 

````
```{r markdown-result, result = 'asis'}
````

You are using `result` with an **s**, the options is `results` with an **s**. 

So what I said before (https://github.com/quarto-dev/quarto-cli/issues/7781#issuecomment-1839013395) applies, it can't be reproduced and it works ok. 

You just need to use the right options, and preferably the right syntax. 

````markdown
---
format: gfm
keep-md: true
---

```{r markdown-result, results = 'asis'}
cat(r'(
# Header

Text
)')
```

```{r markdown-output}
#| label: markdown-2
#| results: asis
cat(r'(
# Header

Text
)')
```
````

Both above are equivalent and give same results regarding **knitr**, and using `output: asis` is also equivalent. 

I'll close this. 

Please reopen if I missed something

**Comment by kylebutts** [comment]
Ahh, sorry for that @cderv!! I suppose my intuition was off with `error`/`warning`/etc. being singular
