### ISSUE TITLE
Compilation to typst file in subdirectory cannot use project-root `.bib` file set in `_quarto.yml`

### ISSUE THREAD

**Issue by petrbouchal** [quarto-dev/quarto-cli#7784]
### Bug description

For files with `format: typst` that live in a subdirectory, Typst is unable to use the `.bib` referred by the `bibliography` entry in `_quarto.yml`.

### Steps to reproduce

```bash
quarto create project website quarto-typst --no-open
cd quarto-typst
echo "bibliography: refs.bib" >> _quarto.yml
touch refs.bib
mkdir subdir
echo "---\ntitle: \"subdir index\"\nformat: typst\n---" > subdir/index.qmd
quarto render
```

### Expected behavior

When compiling typst to PDF, the project-root bibliography specified in `_quarto.yml` should be used also for files in subdirectories.

Presumably for files in subdirs, quarto should call typst with the appropriate `--root` arg as specified in the hint (see below).

This is related to #7354 but in this case I expect quarto can and should make the adjustment to how Typst is called.

Otherwise, it becomes impossible to (a) render via Typst any qmd file a subdirectory and by implication (b) have files in subdirs render to both Typst PDF and another format simultaneously (which is a use case for websites, where subdirs hold specific pages which I also want to offer to people in PDF format.)

A workaround would be to copy the bibliography file to each directory before rendering the site, via a pre-render script, but that would be quite messy, and would only work for files that only render into Typst format.

### Actual behavior

```
Creating project at /Users/petr/csandbox/quarto-typst:
  - Created _quarto.yml
  - Created index.qmd
  - Created about.qmd
  - Created styles.css
[1/3] subdir/index.qmd
[typst]: Compiling index.typ to index.pdf...error: failed to load file (access denied)
    ┌─ subdir/index.typ:239:14
    │
239 │ #bibliography("../refs.bib")
    │               ^^^^^^^^^^^^^
    │
    = hint: cannot read file outside of project root
    = hint: you can adjust the project root with the --root argument
```

### Your environment

MacOS 14.1.2 (23B92)

### Quarto check output

```
quarto check
```
Quarto 1.4.515
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.515
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/petr/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.0
      Path: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources
      LibPaths:
        - /Users/petr/Library/R/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
This one I think we can fix, because Typst _does_ allow us to configure the "typst root", as indicated here:

```
    = hint: cannot read file outside of project root
    = hint: you can adjust the project root with the --root argument
```

**Comment by emstruong** [comment]
Hi,

I was just wondering how this is supposed to be configured? Because I don't seem to be able to change the project root dir using any of the options listed:

1. https://quarto.org/docs/reference/formats/typst.html
2. https://quarto.org/docs/reference/projects/options.html  ?

```yaml
project:
    execute-dir:
        project: /home/.../.../
```

seemed close, but typst doesn't seem to change where it searches for the bibliography file...

**Comment by mcanouil** [comment]
@emstruong This is a closed issue. Please open a GitHub discussion (Q&A) to ask your question with sufficient information, as "it does not work" is not something that can be act on.
As documented `execute-dir` is for code execution.
As you can see on the PR, Quarto is handling the setting internally.

**Comment by emstruong** [comment]
Sorry! @mcanouil
