### ISSUE TITLE
quarto-blog: Post titles are lost when put in narrow mode

### ISSUE THREAD

**Issue by DavisVaughan** [quarto-dev/quarto-cli#779]
You can see this in action here if you make the browser window narrow https://blog.djnavarro.net/posts/2022-03-04_data-types-in-arrow-and-r/

From Charles:

> We probably are trying to put it on the collapsed 'sidebar' but there is no sidebar

<img width="1920" alt="Screen Shot 2022-04-30 at 3 59 02 PM" src="https://user-images.githubusercontent.com/19150088/166120905-efc6ccbb-4735-450e-a67c-5c0413b0d789.png">
<img width="1917" alt="Screen Shot 2022-04-30 at 3 59 13 PM" src="https://user-images.githubusercontent.com/19150088/166120906-ae29c0b3-b4ea-4b7c-877f-9c98f3250e75.png">

**Comment by dragonstyle** [comment]
Fix here - it was even easier than I expected as we were being fooled by the newly supported left side toc. e1a9c37d251be33c9828a8c861dd8ffa64b3d7c4 (a fresh release is being built now)

Thanks for taking the time to discover and write this up!
