### ISSUE TITLE
Is there a way of specifying another `_quarto.yml` file on command line?

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#78]
Please forgive my endless questions, but

Is there a way of specifying the configuration that is usually in `_quarto.yml`  - on the command line? As in:

```
quarto render . --config=alternative_quarto.yml
```

Our use-case is that we want to build the site as GFM, in order to resolve things like citations and execute any `r` macros, before post-processing into notebooks, but building in GFM is forbidden for the `book` type, which is the type specified in our standard `_quarto.yml` file.

**Comment by jjallaire** [comment]
You can't do this right now (and I think it would be tricky to make it work b/c internally quarto assumes it can deduce the project context for a file from only the filesystem state). For this customized a scenario you might just create a wrapper script that substitutes another config file).

**Comment by matthew-brett** [comment]
Totally fair enough - just thought I'd ask to see if I'd missed something.
