### ISSUE TITLE
Typst: Improve section numbering support

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#7823]
### Bug description

Bring typst support up to the level of PDF as described in [PDF Basics](https://quarto.org/docs/output-formats/pdf-basics.html#section-numbering).

In particular, add support for the `number-depth` option and `.unnumbered` class.

### Steps to reproduce

````qmd
---
title: TOC
format: pdf
number-sections: true
number-depth: 2
---

## Section

### Subsection 

#### Subsubsection 

## Unnumberd Section {.unnumbered}
````

### Expected behavior

Like PDF output:
<img width="211" alt="Screenshot 2023-12-07 at 1 08 51 PM" src="https://github.com/quarto-dev/quarto-cli/assets/25964/304b6ec1-c4f6-46e3-8be5-8d00ff6e2b2f">

### Actual behavior

<img width="206" alt="Screenshot 2023-12-07 at 1 08 36 PM" src="https://github.com/quarto-dev/quarto-cli/assets/25964/a5c164de-4c69-4b3b-bb1f-6d6b2da5a5ac">

**Comment by cscheid** [comment]
Thanks for all of these, and keep them coming.

(We really do need a big matrix of feature x format test documents...)

**Comment by cscheid** [comment]
On `main`, now:

<img width="599" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/95e17be0-ebb9-456f-a615-981d44dec8c2">
