### ISSUE TITLE
Review Typst Reference Page

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#7836]
This [PR](https://github.com/quarto-dev/quarto-web/pull/939) adds the Reference page for Typst, generated using `quarto use tools/reference.ts`, which in turn relies on [src/resources/schema](https://github.com/quarto-dev/quarto-cli/tree/4590b39630270c28b838c798f07bcc477e346e9b/src/resources/schema).

Preview the generated page at: https://deploy-preview-939--mystifying-jepsen-fa4396.netlify.app/docs/reference/formats/typst.html

I'd like to use this to check:

* We aren't missing options that are implemented
* We aren't including options that shouldn't be included

We might also compare to the [PDF reference page](https://deploy-preview-939--mystifying-jepsen-fa4396.netlify.app/docs/reference/formats/pdf.html), for any low-hanging fruit to implement in 1.4

I'm happy to do this, but the first pass might be quicker from someone involved on the dev side.

**Comment by cwickham** [comment]
I've already noticed `margin` is listed under "Slide Layout", which is a bit confusing.

**Comment by cscheid** [comment]
I noticed one thing that needed removing: 988c517c13fbb7150ff46d1054ac36c0cf1b9e09

We should have a more robust suite of documents, ideally one for each of these reference entries, but I think that's a "future us" task.

**Comment by cscheid** [comment]
I'm going to close this issue, and then I think that the quarto-web PR can be updated to use the new YAML.
