### ISSUE TITLE
'Part' placement in pdf TOC

### ISSUE THREAD

**Issue by m-clark** [quarto-dev/quarto-cli#7856]
When using parts and creating a pdf for a quarto book, it seems the placement of parts in the TOC is off.

What's working:
- page number associated with the part location within the text
- where the parts are in the actual text
- default pdf documentclass

What's not:
- Just the ToC placement it seems
- krantz.cls

In the image below, part 1 should come before introduction as the page number indicates. There is also a part 2 that is not shown at all, but I've actually not seen that before until creating this demo. I've attached a working demo book (with the krantz.cls file).  Any advice or assistance would be appreciated!

[quarto_toc_part_issue.zip](https://github.com/quarto-dev/quarto/files/13624863/quarto_toc_part_issue.zip)

![image](https://github.com/quarto-dev/quarto/assets/4720569/1953a625-d97e-4fd2-891d-1352108fddbb)

**Comment by cscheid** [comment]
This issue doesn't happen when `krantz.cls` is removed. I think you need to request support from the authors of this file. It will help you debug the issue if you use `keep-tex: true` as a PDF format option. You'll see that our LaTeX output appears well-formed:


````tex
...

\begin{document}
\maketitle

\renewcommand*\contentsname{Contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}
\bookmarksetup{startatroot}

\chapter{Preface}\label{preface}

This is a Quarto book.

To learn more about Quarto books visit
\url{https://quarto.org/docs/books}.

\part{Part 1}

\chapter{Introduction}\label{introduction}

This is a book created from markdown and executable code.

See Knuth (1984) for additional discussion of literate programming.

\chapter{DEMO CHAPTER}\label{demo-chapter}

\section{Introduction}\label{introduction-1}

\subsection{What is this book about?}\label{what-is-this-book-about}

This book is about blah blah blah.

\subsection{Why blah?}\label{why-blah}

\section{Getting Started}\label{getting-started}

...
````

Just adding the `krantz.cls` file you provided to a clean book project in quarto appears to generate a bad TOC, so I don't think this is a Quarto issue. I'm going to go ahead and close this one, but if you can isolate this issue within Quarto itself, please go ahead and reopen!

**Comment by m-clark** [comment]
That's what I was seeing as well, but wasn't sure it was specific to that cls. I'll pass the word along to the CRC press folks to see if they can sort it out.  Thanks for taking a look @cscheid !

**Comment by cscheid** [comment]
> CRC press folks to see if they can sort it out

Thank you - If they have a specific quarto workflow, please tell them that they can contact us directly as well! (carlos.scheidegger@posit.co)

**Comment by higgicd** [comment]
> That's what I was seeing as well, but wasn't sure it was specific to that cls. I'll pass the word along to the CRC press folks to see if they can sort it out. Thanks for taking a look @cscheid !

@m-clark were you able to figure this out with CRC? We're encountering the same issue.

**Comment by m-clark** [comment]
@higgicd I wasn't planning on bothering with it until most everything else was almost done, as I wasn't even sure what parts I was going to end up with!  I meant to mention it to them but have forgotten in the interim. I can do so when I get in touch next though.

**Comment by higgicd** [comment]
@m-clark good news - I've just rendered with a v1.23 of the `krantz.cls` provided by CRC and this issue is fixed. Still getting repeating Preface and References in the TOC per https://github.com/bgreenwell/quarto-crc/issues/1#issue-1850525666 though, an issue for another day...

**Comment by m-clark** [comment]
Thanks for the update! At least one mole has been whacked!

**Comment by francojc** [comment]
> @m-clark good news - I've just rendered with a v1.23 of the `krantz.cls` provided by CRC and this issue is fixed. Still getting repeating Preface and References in the TOC per [bgreenwell/quarto-crc#1 (comment)](https://github.com/bgreenwell/quarto-crc/issues/1#issue-1850525666) though, an issue for another day...

@higgicd I'm also working with krantz for a Taylor and Francis publication. Might you be able to share the newer `krantz.cls` file?

**Comment by giabaio** [comment]
Sorry to reopen this one, but I'm seeing the same issue as in this thread -- when using the `krantz.cls` file from this repo, most things work OK (including avoiding duplication of some chapters -- only need to add `{.unlisted}`), but the parts are out of sync... 

@higgicd you mentioned having a fix for this -- could you perhaps share the file? Do you mean that v1.3 is the previous one than that used in this repo (which I think is 1.4)?

**Comment by mcanouil** [comment]
To be clear `krantz.cls` is a third party class not used or provided by Quarto CLI.
The class defines a lot of LateX which even on its own has issues.
See the following discussion showing one issue that the class has in some versions

- https://github.com/orgs/quarto-dev/discussions/13479

Note that the file itself does not seem to come from one source of truth, even when version number is the same, the content differs.

you are probably better off asking the authors (CRC) for the current version of the file, or go on an internet hunt, maybe starting on GitHub (https://github.com/search?q=path%3Akrantz.cls&type=code)

**Comment by giabaio** [comment]
Thanks. Yes -- I'm aware that `krantz` is a separate, non quarto thing that has its own issues... I just thought I asked because it seemed like this issue may have been resolved using a specific version of that file...

**Comment by mcanouil** [comment]
The most recent version I was able to find is 1.4n (https://github.com/Fgazzelloni/hmsidR/blob/8f10ef381b11d7895ec88400b91375ed66a4906b/krantz.cls#L4)
I would suggest to try this one.

**Comment by m-clark** [comment]
@giabaio I [ultimately abandoned 'parts'](https://www.taylorfrancis.com/books/mono/10.1201/9781003451501/models-demystified-michael-clark-seth-berry). I may come back to them in a future iteration of the web version, but you will fight a lot of battles with krantz.cls no matter what, so I can just say take the easier path when a fork in the road comes and you will likely save at least some time and headaches.

**Comment by giabaio** [comment]
I actually think I may have found a decent hack. It *IS* a hack (as it seems it must be the way with lots of `krantz` quirks...), but: if  you add this to a preamble (which I make sure runs through `include-in-header`):
```
%% Patch to fix the appearance of the parts in the TOC
\makeatletter
\renewcommand*\l@part[2]{%
  \addpenalty{-\@highpenalty}%
  \vskip 1em plus 1pt%
  \begingroup
    \parindent 0pt
    \rightskip 0pt plus 2em % give some stretch
    \parfillskip 0pt
    \leavevmode
    \bfseries
    #1\hfill #2\par
  \endgroup
}
```
then it appears that the parts (which I define as separate `.qmd` files with a single title, but specify as parts in the `_quarto.yml`, as per normal quarto book implementation) are formatted correctly in the TOC...
