### ISSUE TITLE
nav-buttons not available in Quarto dashboard

### ISSUE THREAD

**Issue by jhk0530** [quarto-dev/quarto-cli#7867]
### Bug description

There's option for nav-buttons in quarto [dashboard](https://quarto.org/docs/dashboards/layout.html#navigation)

However, as in local (or in [youtube guide](https://youtu.be/_VGJIPRGTy4?si=qua-cPW6OdjDdLIz) )

I couldn't use that feature. 

### Steps to reproduce

Here's minimal reproducible code and result as `index.qmd`

```
---
title: "dashboard"
format: 
  dashboard: 
    nav-buttons: 
      - twitter
      - github
---

:::{.card}
Card 1
:::

```

### Expected behavior

Button not available (even in HTML level)

### Actual behavior

![스크린샷 2023-12-11 오후 3 42 24](https://github.com/quarto-dev/quarto-cli/assets/6457691/503963f7-74d0-49f9-82cf-015754bfdab3)

### Your environment

Quarto: 1.4.455
Rstudio: 2023.09.1 Build 494
OS: macOS sonoma 14.1.2

### Quarto check output

I replaced path name

``` bash
(base) **-MacBookAir:** **$ quarto check
Quarto 1.4.455
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.455
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/**/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /Users/**/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by dragonstyle** [comment]
I added a warning that will appear if the GitHub repository url can't be found. In my testing, the nav button for Twitter is appearing as:

![Screenshot 2023-12-11 at 8 29 14 AM](https://github.com/quarto-dev/quarto-cli/assets/261654/d8899fd0-e2c8-4b92-8824-7ecf6afc0b98)

**Comment by jhk0530** [comment]
### Solution

I updated quarto version as **1.4.525** from **1.4.455**. at it runs as expected.

![스크린샷 2023-12-11 오후 11 02 09](https://github.com/quarto-dev/quarto-cli/assets/6457691/23cfefe5-5421-4a6b-95d5-19df4fcc29b6)

Also below is code of qmd

```
---
title: "dashboard"
format: 
  dashboard: 
    nav-buttons: 
      - twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
---

:::{.card}
Card 1
:::
```

Thanks !
