### ISSUE TITLE
Extra pandoc arguments are parsed incorrectly for --katex

### ISSUE THREAD

**Issue by ChrisJefferson** [quarto-dev/quarto-cli#7868]
### Bug description

I have a bad internet connection, so i want to use a local copy of katex. I try running quarto as:

quarto render longer-example-questions.qmd --katex="/home/caj/bin/lib/katex/"

However, this gives the error:

`pandoc: /home/caj/bin/lib/katex/: withBinaryFile: inappropriate type (is a directory)`

Looking at https://github.com/jgm/pandoc/issues/8013 , this suggests this is what you get when you remove the `=` from the `--katex` option. Indeed, if I hack quarto to dump the options passed to pandoc, I get:

```
[
  "/home/caj/files/web/quarto-bin/bin/tools/x86_64/pandoc",
  "+RTS",
  "-K512m",
  "-RTS",
  "--defaults",
  "/tmp/quarto-session5baed564/e42157de/quarto-defaults7c9c20b8.yml",
  "/tmp/quarto-session5baed564/e42157de/quarto-inputec7e5781.md",
  "--metadata-file",
  "/tmp/quarto-session5baed564/e42157de/quarto-metadatada6feca9.yml",
  "--katex",
  "/home/caj/bin/lib/katex/",
  "--data-dir",
  "/home/caj/files/web/quarto-bin/share/pandoc/datadir"
]
```

I am on quarto 1.4.424

### Your environment

- Ubuntu 22.04

### Quarto check output

```
Quarto 1.4.424
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.424
      Path: /home/caj/files/web/quarto-bin/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2023

(-) Checking basic markdown render....
[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")

**Comment by ChrisJefferson** [comment]
I think my problem comes from this code, in `quarto-cli/src/command/render/cmd.ts`:
```
    for (const arg of args){
        const equalSignIndex = arg.indexOf("=");
        if (equalSignIndex > 0 && arg.startsWith("-")) {
            normalizedArgs.push(arg.slice(0, equalSignIndex));
            normalizedArgs.push(arg.slice(equalSignIndex + 1));
        } else {
            normalizedArgs.push(arg);
        }
    }
```

This code is purposesfully splitting pandoc arguments on `=`. If I remove the check about `=`, that fixes my problem -- but I'm sure that will break other things, as this code was introduced in commit b2a46fa1bd9497048582c6e1dd6338ac11bf8cb0 explictly to do this splitting.

**Comment by ChrisJefferson** [comment]
Maybe (sorry for so many messages), this was added to deal with arguments that start with a single `-` (which use a space for arguments), but shouldn't split arguments that start `--`, which from me looking at pandoc always use an `=`?

**Comment by cderv** [comment]
We definitely need to check out option handling considering jgm's comment https://github.com/jgm/pandoc/issues/8013#issuecomment-1094162866 

> The information that `--katex` takes an optional argument, while --filter has a mandatory argument, is encoded in the manual: `--filter=PROGRAM` vs `--katex[=URL]`. What we don't say explicitly that would have helped you:
> 
> The `=` isn't needed for options that have a required argument
>The `=` can't be omitted with an optional argument.
> I assumed these were standard conventions, but (1) may be idiosyncratic to the Haskell option parsing library I'm using.
I think (2) can be inferred, if you think about it, since without the = there would be an ambiguity.
But both of these things should probably be said somewhere.

We may not follow that, and `--katex` may not be the only issue. 

@dragonstyle do you know if we are handling `=` differently depending on the flag ?

**Comment by cderv** [comment]
Thanks Carlos !
