### ISSUE TITLE
Conflictted HTML id in Reveal.js when gt-formatted table column and slide header share the same name

### ISSUE THREAD

**Issue by harrysw1729** [quarto-dev/quarto-cli#7875]
### Bug description

When some packages such as `gt` prepare a `data.frame` for HTML presentation, for each column, they would create a `th` element with its `id` attribute derived from the `data.frame`. In Quarto's Reveal.js format, a `section` element would be created for each slide with its `id` attribute derived from the slide header. Thus, whenever the slide header coincides with a column name from a `data.frame` prepared by `gt`, the two `id` attributes would conflict in the output HTML. In Reveal.js, this leads to the slide with a conflicted header being skipped and directed to the title page whenever one attempts to navigate to this slide. Whenever `decktape` attempts to print this slide, it will be directed to the title page, leading to an infinite loop.

A workaround is to assign a unique identifier to the slide header to avoid conflict, but it is not always straightforward to spot the `id` conflict.

The following minimal example reproduces the issue. In the example below, both the table header and the slide header share the same `id="summary"`.

### Steps to reproduce

`````qmd

---
title: Hello
format:
    revealjs: default
---

## Hello

```{r}
library(gt)
df = data.frame(summary="hello")
gt(df)
```


## Summary

hello


`````

### Expected behavior

If everything works well, we should be able to navigate to the slide titled "Summary".

### Actual behavior

Instead, whenever we tried to navigate to the slide titled "Summary", we would be directed to the title page.

### Your environment

- IDE: 1.85.0 (Universal)
- OS: macOS 14.1.2

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
      Jupyter: 5.5.0
      Kernels: python3

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
> If everything works well, we should be able to navigate to the slide titled "Summary".

This is a GT bug, or at least something that should be configurable on GT. The HTML emitted by GT has this (as can be seen by `keep-md: true`:

````
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="summary">summary</th>
````

Note `id="summary"`. Unfortunately, that HTML is passed directly to the output, and then we have a conflicting id. There's not much that Quarto can do here.

@rich-iannone This belongs in `rstudio/gt`, right?
