### ISSUE TITLE
Error `charmap` when `quarto render`  my project

### ISSUE THREAD

**Issue by nqt2022** [quarto-dev/quarto-cli#7883]
### Bug description

- If I `quarto render myfile.qmd` then OK, 
- but when I `quarto render` for Myfolder, error flowwing

>ERROR:

>'charmap' codec can't decode byte 0x81 in position 1075: character maps to <undefined>`

### Steps to reproduce

I use code `python` in quarto, with RStudio.
In Myfolder, I create a project.
I create file `_quarto.yml` and a file `myfile.qmd` (have 'code` python) flowwing:

```python
```{python}
#| code-fold: true
#| code-summary: "code Python"
from sympy import *
a = 5
print(a)
```

### Your environment

- IDE: RStudio 2023.09.1 Build 494
- OS: 
+ Windows 11 Home Single Language
+ Version	23H2

### Quarto check output

Quarto 1.4.525
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.525
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: C:/Users/nguye/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.3.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/nguye/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.24

[>] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
I can't repro this locally. I'm on macOS, so maybe that has to do with it.

```
$ quarto render
[1/2] 7883.qmd
[2/2] myfile.qmd

Executing 'myfile.ipynb'
  Cell 1/1: ''...Done

Output created: myfile.html
```

**Comment by nqt2022** [comment]
sorry, I'm a newbie for github. I shall add the `repo`. Thanks

**Comment by cderv** [comment]
I can't reproduce either. 

Can you share a Github Repo with your quarto project that reproduce the issue for you ? 

Also about the Error, can you share the log part that throws it ? You get this error in console ? 

It would help us know if this comes from Quarto, or Python directly. 

We may need to have info to reproduce your python environment.

**Comment by nqt2022** [comment]
> 

> I can't reproduce either.
> 
> Can you share a Github Repo with your quarto project that reproduce the issue for you ?
> 
> Also about the Error, can you share the log part that throws it ? You get this error in console ?
> 
> It would help us know if this comes from Quarto, or Python directly.
> 
> We may need to have info to reproduce your python environment.

hi, my repo [(https://github.com/nqt2022/error_project_quarto.git)] for the error
When I remove char `Đ`, the `quarto render` is ok. I think char "Đ" (char Vietnam for unicode utf-8) have error

**Comment by cscheid** [comment]
Your repository is missing files in the render list. Can you also please try to create a smaller example? Your _quarto.yml file seems to have a large number of configuration options that are unrelated to the bug report.

**Comment by nqt2022** [comment]
@cscheid, I upadated my repo. I create a small example. 

The error raise when I use `quarto render` for my project or **click** `render pdf` (or `revealjs`) (in **RStudio**) for file `thucode.qmd`

If I don't update `_quarto.yml`, error raise when I `quarto render` for my project!

PS: when I delete line: `subtitle: Đ` (or **delete** char `Đ` (char for vietnam, unicode)) in `_quarto.yml`, quarto ok, don't raise error!

**Comment by nqt2022** [comment]
Sorry, I can't only render to `pdf` for file `thucode.qmd` (from button `render` in **Rstudio**) (in the repo) but also use `quarto render` for `my project`.
But, when I delete `line subtitle: Đ `(or delete char `Đ` (char for vietnam, unicode)) in `_quarto.yml`
1. my `_quarto.ym`:

>project: 
  render:
    - thucode.qmd
title: The error of project Quarto
subtitle: Đ
format: 
  pdf:
    documentclass: article
  revealjs:
    title-slide-attributes:
      data-background-size: contain

2. my `thucode.qmd`, a simple example:
> 
```{python}
#| code-fold: true
#| code-summary: "code Python"
from sympy import *
a = 5
print(a)

```

I see error:
`'charmap' codec can't decode byte 0x90 in position 6416: character maps to <undefined>`

**Comment by cderv** [comment]
Here is a minimal  reproducible example 

````markdown
---
title: "test"
format: html
subtitle: Đ
keep-md: true
---

```{python}
from sympy import *
a = 5
print(a)
```
````

`quarto render` this document leads to 
````
==> quarto preview index.qmd --to html --no-watch-inputs --no-browse

ERROR: 

'charmap' codec can't decode byte 0x90 in position 517: character maps to <undefined>
ERROR: Error
    at renderFiles (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render-files.ts:346:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async renderProject (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/project.ts:268:23)
    at async renderForPreview (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:436:24)
    at async render (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:167:22)
    at async preview (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:184:18)
    at async Command.fn (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/cmd.ts:415:7)
    at async Command.execute (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/quarto.ts:155:3)
    at async file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/quarto.ts:186:5
````

It definitely seems like an encoding issue.

**Comment by cderv** [comment]
The issue happens with jupyter execution. 
````
 jupyter nbconvert --to notebook --execute index.ipynb

Let's not that 
`````



https://github.com/quarto-dev/quarto-cli/blob/53fca915ad653145c6aa2ddd51b105239fa9e351/src/execute/jupyter/jupyter-kernel.ts#L267-L292

**Comment by cderv** [comment]
And I can confirm this has to do with the Daemon execution of Jupyter Kernel. If you exectute with no deamon it works well. 
See https://quarto.org/docs/computations/python.html#kernel-daemon about daemon.

````powershell
quarto render index.qmd --no-execute-daemon
````

So as a workaround for now, you can add `daemon: false`
````markdown
---
title: "test"
format: html
subtitle: Đ
keep-md: true
keep-ipynb: true
execute:
  daemon: false
---

```{python}
1 + 1
```
````

**Comment by dragonstyle** [comment]
I'll take a look at this and loop @cscheid in if needed... thanks for narrowing the case so much!

**Comment by cscheid** [comment]
That was definitely me, working around that Deno connect issue. Thanks, @dragonstyle !!

**Comment by nqt2022** [comment]
Thanks @cscheid, @cderv for your support.
