### ISSUE TITLE
Installing Extensions from a github renamed repo does not handle redirect 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7886]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/7851

<div type='discussions-op-text'>

<sup>Originally posted by **axiomtutor** December  8, 2023</sup>
### Description

I'm trying to install extensions for Quarto presentations (for example, the `illinois-revealjs` extension) inside of RStudio.  My computer runs Windows 11.  

I tried using the documentation https://quarto.org/docs/extensions/managing.html

and https://quarto.org/docs/extensions/revealjs.html

and also following the instructions from the extension's GitHub.  https://github.com/coatless-quarto/illinois-revealjs

I also tried looking for any info on RStudio and its GitHub page but struck out there -- I think someone over there actually asked the same question a while ago and got no responses.  

---

After trying all of the above, I *think* it successfully downloaded the extension, but when I try to run 

```
---
title: "title"
author: "me"
format: 
  illinois-revealjs:
    chalkboard: true
editor: visual
---

## TEST
```

I get the error message

```
ERROR: Unable to read the extension 'illinois'.
Please ensure that you provided the correct id and that the extension is installed.

Stack trace:
Please ensure that you provided the correct id and that the extension is installed.
    at loadExtension (file:///C:/Users/username/AppData/Local/Programs/Quarto/bin/quarto.js:42097:15)
    ...
```

and the `...` just covers up a bunch of other very similar lines.  

However, when I set `illinois-revealjs` to just `revealjs` then it renders.

Anyone have guidance on how to do the installation / use inside of RStudio? Thanks! :)</div>

**Comment by cderv** [comment]
This happens because I believe the repo has been renamed, and the url redirect. 

* New repo : https://github.com/coatless-quarto/illinois-revealjs
* README instruction: `quarto add coatless/quarto-illinois`

Quarto does follow redirect, but we do get the subdir and build all information based on argument passed

https://github.com/quarto-dev/quarto-cli/blob/a4a20497359efdcf3592e779d2c7fc7bbfcac79b/src/extension/extension-host.ts#L229-L253

So download happens correctly, but then there is issue at the installation stage because folder archive name is not the expected one 

`````
 quarto add coatless/quarto-illinois

Quarto extensions may execute code when documents are rendered. If you do not
trust the authors of the extension, we recommend that you do not install or
use the extension.
 ? Do you trust the authors of this extension (Y/n) » Yes
[>] Downloading
[>] Unzipping
ERROR: NotFound: Le chemin d’accès spécifié est introuvable. (os error 3): readdir 'C:\Users\chris\AppData\Local\Temp\quarto-session03c2cc05\7555b26b\d8bee72b\archive\quarto-illinois-main\_extensions'

Stack trace:
    at Object.readDirSync (ext:deno_fs/30_fs.js:149:14)
    at readExtensions (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/extension/extension.ts:403:30)
    at readAndCopyExtensions (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/extension/install.ts:336:28)
    at copyExtensions (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/extension/install.ts:327:9)
    at unzipAndStage (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/extension/install.ts:310:9)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async installExtension (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/extension/install.ts:64:26)
    at async Command.fn (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/add/cmd.ts:50:11)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:155:3)
`````


````
. # C:\Users\chris\AppData\Local\Temp\quarto-session3630d3c9\281dea6f\d8d5455b\archive
+¦¦ illinois-revealjs-main
-   +¦¦ README.md
-   +¦¦ template.qmd
-   +¦¦ title-slide-quarto-illinois.png
-   L¦¦ _extensions
-       L¦¦ illinois
-           +¦¦ imtheme.scss
-           +¦¦ logo-illinois-block-i.png
-           L¦¦ _extension.yml
L¦¦ staged
    L¦¦ _extensions
        L¦¦ coatless
````

So `quarto-illinois-main` does not exist, as the new name is `illinois-revealjs-main`

@dragonstyle we may need to handle redirect. Either with error and warning message, or just by trying to get information for the resolved url and not just the `quarto add` argument.

**Comment by coatless** [comment]
Sorry about the re-shuffle folks! Thanks for the patch @mcanouil and quick upstream fix.
