### ISSUE TITLE
`crossref:` in includes seem to completely overwrite that of main file

### ISSUE THREAD

**Issue by sda030** [quarto-dev/quarto-cli#7895]
### Bug description

Not very important, but having a `crossref:` in a sub-document with any setting will completely disregard all crossref-settings in the "mother document". Is this intentional? I could not find this issue in the [Crossref Overhaul-list](https://github.com/quarto-dev/quarto-cli/issues/4944) or elsewhere. Persists in today's build. 
It is not a very common situation as one typically would want to address all such settings in the mother document anyway. I discovered it after a while because a chapter co-author had inserted `list-title:` to fix a local "issue". As an "editor" I think I would prefer a warning or even an error instead of silently ignoring it.

P.S. Impressed by your big bite on open issues recently, from 1100+ to 877. 👍 

### Steps to reproduce

Mother document:
````qmd
---
format:
  html: default
crossref:
  chapters: true
---

{{< include "test1.qmd" >}}

{{< include "test2.qmd" >}}
````

test1.qmd:
````qmd
---
format: html
---

# Introduction


What an interesting issue!
````

test2.qmd:
````qmd
---
format: html
crossref:
  lst-title: "Overview "  # Move this to mother  document to get it to work as expected
---

# Method

Text about @fig-1.

```{r}
#| label: 'fig-1'
plot(mtcars)
```


## Data
@Fig-2 is another figure.

```{r}
#| label: 'fig-2'
plot(datasets::anscombe)
```


## Analysis
````

### Expected behavior

Either the typical approach (child document only oversteering mother doc for the given setting, otherwise inheritance),
or a warning/error if there is no forseeable future where one would want to do this with crossref.

### Actual behavior

![image](https://github.com/quarto-dev/quarto-cli/assets/13221371/72c7295f-96b8-427c-8cca-3d773eecc18b)

### Your environment

- IDE: RStudio 2023.12.0 Build 170
- Windows  11

### Quarto check output

```bash
Quarto 1.4.526
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.526
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\py128\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.0
      Path: C:/Program Files/Python312/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/py128/AppData/Local/R/win-library
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
This is not a bug and is described in several issues/discussions and in the documentation.

Include shortcode is simply a copy/paste of the content of the file being included in the main document.

If you set any key in the included document frontmatter it will override the ones from the main document.

**Comment by cscheid** [comment]
Just to be specific, this is on the top of the includes documentation:

https://quarto.org/docs/authoring/includes.html

<img width="868" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/382ebf74-c614-4871-86f8-64aa072fda05">

**Comment by sda030** [comment]
Apologies, thought it would only be the links, not the YAML. Also, I thought for some unknown reason that `knitr::knit_child()` would be replaced by `include`, so I had needlessly moved away from that.. I have now fully read up on the includes-feature vs. knit_child().
