### ISSUE TITLE
`render` list not respected in project

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#79]
I noticed that Quarto seems to ignore my list of documents to render:

```
# _quarto.yml
project:
  render:
    - index.qmd
    - about.qmd
```

I also have a document `another.qmd` in the same directory, and I get the following output from `quarto render .`:

```
[1/3] index.qmd
[2/3] another.qmd
[3/3] about.qmd
```

I was expecting, from the [docs](https://quarto.org/docs/projects/quarto-projects.html#render-targets), that Quarto would ignore `another.qmd`.  Is that not so?

**Comment by jjallaire** [comment]
It should be working as you expect, will investigate!

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/3f1d59991fec95dfaee8f6b1120760ebe21e8c46

Build v0.2.55 will have the fix.

**Comment by matthew-brett** [comment]
Great - thanks.
