### ISSUE TITLE
[1.4 Docs] Add Inline Code Page

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#7902]
Add new page at: Guide > Computation > Inline Code (listed after "Using x" pages)

* Merge [Inline Execution for Jupyter](https://quarto.org/docs/prerelease/1.4/inline.html) highlight, with existing [Computation > Execution Option > Inline Code](https://quarto.org/docs/computations/execution-options.html#inline-code) section (removing inline code section from this page).
* Clarify what is the same and what is different between engines. Promote unified syntax but comment on native syntax too.
* Add links to Inline Code from the "Computations > Using x" pages

**Comment by mcanouil** [comment]
I don't know if that's plan, but while merging, I think `knitr` inline examples should be updated to Quarto inline syntax: `` `r code` `` to `` `{r} code` ``.

**Comment by gyansinha** [comment]
> I don't know if that's plan, but while merging, I think `knitr` inline examples should be updated to Quarto inline syntax: `` `r code` `` to `` `{r} code` ``.

Does the same hold for Julia as well?

**Comment by cscheid** [comment]
> Does the same hold for Julia as well?

Until v1.4, cells that run through the Jupyter engine hadn't supported inline syntax. So no, that update shouldn't be necessary because such cells don't exist.

**Comment by cwickham** [comment]
Closed with https://github.com/quarto-dev/quarto-web/pull/953
