### ISSUE TITLE
Confusing error when creating extension in same directory as source file

### ISSUE THREAD

**Issue by ChrisJefferson** [quarto-dev/quarto-cli#7909]
### Bug description

`quarto create` puts new filters in a directory with the same name as the filter. However, this directory then seems to confuse pandoc (or quarto?) looking for the filter later, if I run `quarto render` in the directory where I ran `quarto create`.

### Steps to reproduce

(Do all this in an empty directory):

```
> quarto create --no-open
(create an extension, filter, called 'mynewfilter')
 ? Create › extension
 ? Type › filter
 ? Extension Name › mynewfilter
Creating extension at /home/caj/test/mynewfilter:
  - Created _extensions/mynewfilter/_extension.yml
  - Created _extensions/mynewfilter/mynewfilter.lua
  - Created README.md
  - Created example.qmd
  - Created .gitignore
> cp mynewfilter/example.qmd .
> quarto add mynewfilter --no-prompt
> quarto render example.qmd
pandoc
  to: html
  output-file: example.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Mynewfilter Example

FATAL (/home/caj/progs/quarto-cli/src/resources/filters/./common/wrapped-filter.lua:129) An error occurred:
Could not run /home/caj/teaching/Dundee/test/mynewfilter as a JSON filter.
Please make sure the file exists and is executable.

Did you intend 'mynewfilter' as a Lua filter in an extension?
If so, make sure you've spelled the name of the extension correctly.

The original Pandoc error follows below.
Error running filter /home/caj/teaching/Dundee/test/mynewfilter:
Could not find executable /home/caj/teaching/Dundee/test/mynewfilter
Error running filter /home/caj/progs/quarto-cli/src/resources/filters/main.lua:
.../progs/quarto-cli/src/resources/filters/./common/log.lua:30: attempt to call a nil value (global 'crash_with_stack_trace')
stack traceback:
        ...rogs/quarto-cli/src/resources/filters/./common/error.lua:14: in function 'fail'
        ...to-cli/src/resources/filters/./common/wrapped-filter.lua:129: in field 'Pandoc'
        ...s/quarto-cli/src/resources/filters/./ast/customnodes.lua:97: in function 'run_emulated_filter'
        .../quarto-cli/src/resources/filters/./ast/runemulation.lua:82: in local 'callback'
        .../quarto-cli/src/resources/filters/./ast/runemulation.lua:97: in upvalue 'run_emulated_filter_chain'
        .../quarto-cli/src/resources/filters/./ast/runemulation.lua:133: in function <.../quarto-cli/src/resources/filters/./ast/runemulation.lua:130>
ERROR: Error
    at renderFiles (file:///home/caj/progs/quarto-cli/src/command/render/render-files.ts:346:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async render (file:///home/caj/progs/quarto-cli/src/command/render/render-shared.ts:99:18)
    at async Command.fn (file:///home/caj/progs/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///home/caj/progs/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///home/caj/progs/quarto-cli/src/quarto.ts:155:3)
    at async file:///home/caj/progs/quarto-cli/src/quarto.ts:186:5
```

This confusion seems to be because `mynewfilter` is in a directory called `mynewfilter`. If I rename this directory, the `quarto render example.qmd` works fine.

### Expected behavior

I should be able to create a filter in the same directory as I then use and test it

### Your environment

Ubuntu 22.04

### Quarto check output

```
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/caj/progs/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by ChrisJefferson** [comment]
The easiest fix for this (I think) would be to change the name `quarto create` uses, to maybe `filtername-src` (there are probably better names?), but not sure what else that might break?

**Comment by mcanouil** [comment]
Why are you using `quarto add mynewfilter --no-prompt`? The extension is already "installed", i.e., in the _extensions directory at the root of your project.

**Comment by ChrisJefferson** [comment]
If I create a project with `quarto create-project`, then an extension with `quarto create`, I end up with this directory structure:

```
.
./myfilter
./myfilter/_extensions
./myfilter/_extensions/myfilter
./myfilter/_extensions/myfilter/_extension.yml
./myfilter/_extensions/myfilter/myfilter.lua
./myfilter/example.qmd
./myfilter/README.md
./myfilter/.gitignore
./w.qmd
./_quarto.yml
```

So, in my project, `myfilter` isn't installed, it's in the `_extensions` directory of `myfilter`, I (think) I need to add it, to then get:

```
.
./_extensions
./_extensions/myfilter
./_extensions/myfilter/_extension.yml
./_extensions/myfilter/myfilter.lua
./myfilter
./myfilter/_extensions
./myfilter/_extensions/myfilter
./myfilter/_extensions/myfilter/_extension.yml
./myfilter/_extensions/myfilter/myfilter.lua
./myfilter/example.qmd
./myfilter/README.md
./myfilter/.gitignore
./w.qmd
./_quarto.yml
```

Now, if I move the `myfilter` directory, I'll be able to use `myfilter`.

My original workflow was:

* Work on some documents
* Decide I'd like to write my first filter
* Follow instructions for running `quarto create`, just doing it in the directory of my project (as that's where I already was). Finding that doesn't load the filter, so doing `quarto add mynewfilter`.

**Comment by mcanouil** [comment]
The issue is that you are confusing Quarto/Pandoc by having twice the extension in your project.

```
tree -L 1
.
├── _extensions
├── example.html
├── example.qmd
├── example_files
└── mynewfilter

4 directories, 2 files
```

Here, Quarto/Pandoc has two available locations to find the filter `_extensions/mynewfilter` and `mynewfilter`.
1. I don't think you should create an extension within a Quarto project and install it in that same project or simply create a filter without the extension packaging which is mostly to distribute the filter.
2. Here, there is an issue which is not limited to the case your reported. If you have a directory (even empty) with the name of the filter/extension, Quarto/Pandoc will show the exact same error. So there is something to be done in how Quarto/Pandoc look for filters in a project.


`quarto create-project` is obsolete since 1.2, you should only use `quarto create`.

**Comment by mcanouil** [comment]
> My original workflow was:
> 
> * Work on some documents
> * Decide I'd like to write my first filter
> * Follow instructions for running `quarto create`, just doing it in the directory of my project (as that's where I already was). Finding that doesn't load the filter, so doing `quarto add mynewfilter`.

Extension mechanism is to distribute/share what you made, you don't need that to develop a filter. (cc @cwickham)
Write your `mynewfilter.lua` and in your options:

```yaml
filters:
  - mynewfilter.lua
```

With the `lua` extension.

**Comment by ChrisJefferson** [comment]
Thanks. I do now feel like I have a good direction, but I feel this bug might be easy to hit (although maybe I'm the first to do this!), and then very hard to debug (it took me quite a while to digest the feedback, and why I was being told about `JSON filters`).

I'm not sure the best way of improving the error. Looking at wrapper-filter.lua, it could just say something like (assuming it's true) `mynewfilter is a directory. Cannot have a directory in the project with the same name as a filter`, which would at least point in the right direction? (although maybe sometimes directories are parsed?)

**Comment by mcanouil** [comment]
Few more tests:

```
.
├── example.qmd
└── mynewfilter
    └── mynewfilter.lua

2 directories, 2 files
```

```qmd
---
title: "Mynewfilter Example"
filters:
  - mynewfilter
---

## Heading

This filter adds formatting to heading text.
````

This is enough to reproduce the issue.
