### ISSUE TITLE
error when rendering braket equation to docx

### ISSUE THREAD

**Issue by delsuc** [quarto-dev/quarto-cli#7912]
### Bug description

In a text with equations coded with the dollar notation, in an equation using brakets, the closing brakets are changed to parenthesis when exporting to docx. Works fine with html and pdf, but not docs:

For instance in
`$\dots [ 0 \ldots F_{max} ] [( 0 \ldots F_{max} )] ([ 0 \ldots F_{max} ]) ( 0 \ldots F_{max} ) \ldots$`
the three first ones are rendered wrong in docx, only the last one is ok

with `render -t docx` 
![image](https://github.com/quarto-dev/quarto-cli/assets/9403064/764011a7-2943-4dab-9c4f-ede8d3d79506)

with `render -t html`  it's ok
![image](https://github.com/quarto-dev/quarto-cli/assets/9403064/9d0a7241-e7cf-437d-ac33-ffeb97b46d45)

tested with 1.3.450

### Your environment

quarto render test.qmd -t html
on ubunu 22-04

### Quarto check output

✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /home/mad/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by cscheid** [comment]
```
quarto render test.qmd -t html
on ubunu 22-04
```

Where are you opening this file? I think you're experiencing a font bug on your side. Is there a chance that the client you're opening the file with (which I assume isn't Microsoft Word given your "ubuntu 22.04" comment) has a font that's missing the `]` glyph?

**Comment by delsuc** [comment]
Your are right !

The bug was actually detected by a colleague to whom I sent the file. However, I had slightly modified it in LibreOffice. If I send it to a windows machine untouched and open with Word, the bug is not present !

However it seems it is not a font pb but rather an LO equation parser problem. On the example I sent, the untouched file displays correctly in Word, however if I open it in LO, and click on the equation it is displayed as follows :
`… left [0 … {F} rsub {m a x} right ) left [left (0 … {F} rsub {m a x} right ) right ) left (left [0 … {F} rsub {m a x} right ) right ) left (0 … {F} rsub {m a x} right ) …`
so clearly `left [` balanced with `right )`

so... a LibreOffice or quarto bug ?.... 🤔

**Comment by cderv** [comment]
> a LibreOffice or quarto bug ?

I believe the equation rendering to docx is done by Pandoc directly and not Quarto; You could run `quarto pandoc` to get access to Pandoc CLI directly. Example: 

````
> quarto pandoc -t docx -o test.docx
$\dots [ 0 \ldots F_{max} ] [( 0 \ldots F_{max} )] ([ 0 \ldots F_{max} ]) ( 0 \ldots F_{max} ) \ldots$
^Z
````

This should give you a docx document produced directly by pandoc, and if it has the issue you see, then this could be libre office or Pandoc. 

Not that pandoc also has a `odt` output format, probably more suited for Libre Office. `format: odt` in Quarto should work.

**Comment by cscheid** [comment]
> If I send it to a windows machine untouched and open with Word, the bug is not present !

> however if I open it in LO, and click on the equation it is displayed as follows

> so... a LibreOffice or quarto bug ?.... 🤔

If you sent it untouched and it opens well with Word, then I'm not sure why you think it's a Quarto bug. I'm going to go ahead and close this one, but if you add more information that points to quarto, please feel free to reopen it!

**Comment by delsuc** [comment]
@cderv I ran your test
It confirms the bug is already in pandoc 
upstream !
Thanks to all.
