### ISSUE TITLE
Using `meta` shortcode with Div blocks and HTML

### ISSUE THREAD

**Issue by mccarthy-m-g** [quarto-dev/quarto-cli#792]
I'm attempting to use the `meta` shortcode to add a link inside a Div block; however, it doesn't seem to work. Here's a minimal example to demonstrate:

```
---
title: A Minimal Example
registration:
  link: https://github.com/
---

::: {.tool}
<a href="{{< meta registration.link >}}">
Sign Up
</a>
:::
```

My expectation is that this would create a link to <https://github.com/> in the rendered output. Instead `{{< meta registration.link >}}` is treated literally, turning into `%7B%7B%3C%20meta%20registration.link%20%3E%7D%7D`.

Removing the quotation marks around `{{< meta registration.link >}}` doesn't work either. That results in the following output: "\<a href=https://github.com/> Sign Up".

Is there any way to get this working with the `meta` shortcode or is this shortcode only intended for body text?

**Comment by cscheid** [comment]
You're correct that this should work. I'm investigating.

**Comment by cscheid** [comment]
The underlying issue is we're not handling raw HTML correctly. While we work on the fix: is the Markdown syntax for a link an option for you? This works for me:

```
---
title: A Minimal Example
registration:
  link: https://github.com/
---

::: {.tool}
[Sign Up]({{< meta registration.link >}})
:::
```

**Comment by mccarthy-m-g** [comment]
Thanks for the quick response!

My actual use case is a button link that includes a fontawesome icon like:

```
---
title: A Minimal Example
registration:
  link: https://github.com/
---

::: {.tool}
<a href="{{< meta registration.link >}}" role="button" class="btn btn-outline-dark">
<i class="fas fa-user-plus"></i>
Sign Up
</a>
:::
```

So I'll probably just remove the shortcode for now and implement it later.

**Comment by jjallaire** [comment]
This is fixed here: https://github.com/quarto-dev/quarto-cli/commit/b3305787ada17443f99cc225bbbbdb8b5a539187

Should be available in a new build within the next hour.

**Comment by mccarthy-m-g** [comment]
Works great. Thanks for the quick turnaround!
