### ISSUE TITLE
Shortcode in website sidebar regression from 1.4.526

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#7926]
Shortcodes are no longer working inside website sidebar.
Working fine in v1.4.526 but fails to render properly since v1.4.527 (tested also on v1.4.528).

See reprex at: <https://github.com/mcanouil/quarto-issues-experiments/tree/main/quarto-cli-7926>

**Comment by cderv** [comment]
> Working fine in v1.4.526 but fails to render properly since v1.4.527

Meaning it happens somewhere in those 96 commits 
https://github.com/quarto-dev/quarto-cli/compare/v1.4.526...v1.4.527

Probably something related to the Markdown pipeline @dragonstyle ?

**Comment by mcanouil** [comment]
Yes, I would have done a bisect, but no time right now.

**Comment by dragonstyle** [comment]
I have a good guess- I made a change related to this that is likely the cause. Thanks for catching I'll fix!

**Comment by mcanouil** [comment]
I'll test the fix probably next week ;)
