### ISSUE TITLE
Raw LaTeX tables fail in Quarto >= 1.4.507 due to extraneous table environment insertion

### ISSUE THREAD

**Issue by christopherkenny** [quarto-dev/quarto-cli#7937]
### Bug description

When making a `table*` in raw LaTeX, Quarto now fails with:
```
ERROR: 
compilation failed- error
LaTeX Error: Not in outer par mode.
```

This LaTeX corresponds to Quarto placing the `table*` within an extraneous `table` environment and steals the caption from the inner `table*` environment. More precisely, it changes the opening to be:

```
\begin{table}

\caption{\label{tbl-wide}Automobile Land Speed Records (GR 5-10).}

\centering{

\begin{table*}

\begin{tabular}{l l l l r}
```
followed by the contents of the table (see example below). 

In older versions of Quarto, the generated LaTeX would be.
```
\begin{table*}
\caption{Automobile Land Speed Records (GR 5-10).}
\label{tbl-wide}

\begin{tabular}{l l l l r}
```

After some searching across old daily releases, this appears to be due to changes around release 1.4.507, though not 100% clear to me what changed. Timewise, that looks like it could be related to changes in handling captions in https://github.com/quarto-dev/quarto-cli/pull/7629 responding to https://github.com/quarto-dev/quarto-cli/issues/7236. That would seem to coincide well with the `\label{tbl-wide}` also being moved.

Thanks, as always, for your work on incredible tools like Quarto!

(If helpful, the original context here is using a `table*` environment within a journal template, which uses `figure*` and `table*` environments, see [christopherkenny/apsr](https://github.com/christopherkenny/apsr).)

### Steps to reproduce

Make a `table*` environment in raw latex, such as below, then try to render it with a recent version of Quarto:

````
---
title: "Test table*"
format: pdf
editor: source
keep-tex: true
---

Some text

```{=latex}
\begin{table*}
\caption{Automobile Land Speed Records (GR 5-10).}
\label{tbl-wide}

\begin{tabular}{l l l l r}
Speed (mph) & Driver          & Car                        & Engine    & Date     \\
\midrule
407.447     & Craig Breedlove & Spirit of America          & GE J47    & 8/5/63   \\
413.199     & Tom Green       & Wingfoot Express           & WE J46    & 10/2/64  \\
434.22      & Art Arfons      & Green Monster              & GE J79    & 10/5/64  \\
468.719     & Craig Breedlove & Spirit of America          & GE J79    & 10/13/64 \\
526.277     & Craig Breedlove & Spirit of America          & GE J79    & 10/15/65 \\
536.712     & Art Arfons      & Green Monster              & GE J79    & 10/27/65 \\
555.127     & Craig Breedlove & Spirit of America, Sonic 1 & GE J79    & 11/2/65  \\
576.553     & Art Arfons      & Green Monster              & GE J79    & 11/7/65  \\
600.601     & Craig Breedlove & Spirit of America, Sonic 1 & GE J79    & 11/15/65 \\
622.407     & Gary Gabelich   & Blue Flame                 & Rocket    & 10/23/70 \\
633.468     & Richard Noble   & Thrust 2                   & RR RG 146 & 10/4/83  \\
763.035     & Andy Green      & Thrust SSC                 & RR Spey   & 10/15/97\\
\end{tabular}

\end{table*}
```
````
### Expected behavior

A wide table should be generated.

### Actual behavior

Quarto tries to place a wide (2-column) `table*` inside a regular (1-column) `table`, causing rendering failures.

### Your environment

- IDE: RStudio 2023.09.1 Build 494
- OS: Microsoft Windows 11 Home 10.0.22621

### Quarto check output
````
Quarto 1.4.528
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.528
      Path: C:\Users\chris\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\chris\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.1
      Path: C:/Users/chris/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-4.3.2
      LibPaths:
        - C:/Users/chris/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.43
      rmarkdown: 2.23

[>] Checking Knitr engine render......OK
````

**Comment by christopherkenny** [comment]
Actually, this looks like it could be related to https://github.com/quarto-dev/quarto-cli/pull/7240, as it tries to capture `\begin{table}` within blocks?

**Comment by cscheid** [comment]
We should add a mode that disables latex table processing, the same way that we have a mode that disables html table processing.

**Comment by cscheid** [comment]
This is a combination of a number of things. Quarto recognizes the combination of `\begin{tabular}`, `\label` and `\caption` as a LaTeX crossreferenceable environment (we need to do that in order for features like caption positioning to work). However, the specific combination of:

1) `\begin{tabular}`, `\label` and `\caption`
2) and a `table*` environment specifically

confuses Quarto. What needs to happen here is for Quarto to detect `table*` in addition to `table`.

**Comment by christopherkenny** [comment]
Thanks @cscheid. Appreciate the fix and speed very much. I know the use of raw LaTeX is suboptimal here, but it is quite useful for some of the stricter journal submission templates which use 2-column formats.

**Comment by cscheid** [comment]
@christopherkenny it was definitely a bug! Thank you for clean reproducible example. We'll have a new prerelease installer out soon.
