### ISSUE TITLE
Links without link text break quarto render

### ISSUE THREAD

**Issue by has2k1** [quarto-dev/quarto-cli#7945]
### Bug description

Rendering of links without link text e.g. `[](https://quarto.org)` is broken. This is regression in a recent pre-release.

### Steps to reproduce

```sh
echo "[](https://quarto.org)" > link.qmd; quarto render link.qmd
```

### Expected behavior

```
Output created: link.html
```

### Actual behavior

```
Error running filter /Applications/quarto/share/filters/main.lua:
/Applications/quarto/share/filters/main.lua:2479: attempt to index a nil value (local 'el')
stack traceback:
        /Applications/quarto/share/filters/main.lua:5940: in upvalue 'needs_forward_align'
        /Applications/quarto/share/filters/main.lua:5995: in function </Applications/quarto/share/filters/main.lua:5987>
        [C]: in ?
        [C]: in method 'walk'
        /Applications/quarto/share/filters/main.lua:205: in function </Applications/quarto/share/filters/main.lua:195>
        (...tail calls...)
        /Applications/quarto/share/filters/main.lua:917: in local 'callback'
        /Applications/quarto/share/filters/main.lua:932: in upvalue 'run_emulated_filter_chain'
        /Applications/quarto/share/filters/main.lua:968: in function </Applications/quarto/share/filters/main.lua:965>
stack traceback:
        /Applications/quarto/share/filters/main.lua:205: in function </Applications/quarto/share/filters/main.lua:195>
        (...tail calls...)
        /Applications/quarto/share/filters/main.lua:917: in local 'callback'
        /Applications/quarto/share/filters/main.lua:932: in upvalue 'run_emulated_filter_chain'
        /Applications/quarto/share/filters/main.lua:968: in function </Applications/quarto/share/filters/main.lua:965>
```

### Your environment

- OS: macOS Sonoma 14.1.1

### Quarto check output

```
╰─ quarto check
Quarto 1.4.528
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.528
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.11
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/hassan/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: /Users/hassan/.pyenv/versions/3.10.4/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.43
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

```

**Comment by mcanouil** [comment]
Well even if it is indeed a regression, this is invalid markup, you can test it for yourself even on GitHub. It does not crash but there is "nothing" either.
Bare links are written as `<https://quarto.org>`.

**Comment by has2k1** [comment]
`[](https://quarto.org)` is valid commonmark. Using pandoc directly,

```sh
echo "[quarto](https://quarto.org)" | pandoc --from markdown --to html
```

gives

```
<p><a href="https://quarto.org">quarto</a></p>
```


On github, you can inspect the html. e.g. there is a link without link text at the end of this sentence [](https://quarto.org).

**Comment by mcanouil** [comment]
By invalid I meant that it's like doing nothing: `<a href="https://quarto.org"></a>` is no usable.

**Comment by has2k1** [comment]
> By invalid I meant that it's like doing nothing: `<a href="https://quarto.org"></a>` is no usable.

You are correct about `<a href="https://quarto.org"></a>`, it passes through pandoc unchanged and is not that useful, but `[](https://quarto.org)` is processed and you can modify it with a filter.

**Comment by cderv** [comment]
Thanks for the report! 

I believe our Lua processing should not throw an error at this place. The processing is unrelated to Links, but should apply only on images. 

Error is thrown from 
https://github.com/quarto-dev/quarto-cli/blob/b268f5decb10a2da5132d403be6959cc44ffb2bc/src/resources/filters/quarto-post/html.lua#L8-L10

which is called at 
https://github.com/quarto-dev/quarto-cli/blob/b268f5decb10a2da5132d403be6959cc44ffb2bc/src/resources/filters/quarto-post/html.lua#L56-L66

and also at 
https://github.com/quarto-dev/quarto-cli/blob/b268f5decb10a2da5132d403be6959cc44ffb2bc/src/resources/filters/quarto-post/html.lua#L25-L35

The latter is not relevant here as this is not a `Figure`. But the former is as we have a `Para`. Though we should apply the function only if `img` is found. So we have an issue in our check 
https://github.com/quarto-dev/quarto-cli/blob/b268f5decb10a2da5132d403be6959cc44ffb2bc/src/resources/filters/quarto-post/html.lua#L60

* `quarto.utils.match("Para/[1]/Image")(para)` does return `false`
* `quarto.utils.match("Para/[1]/Link/[1]/Image")` does not. It return a function (as I can see with a `quarto.log.output()`) 

So we don't opt out the filter processing as we should. Something we need to handle in `quarto.utils.match()`

**Comment by cscheid** [comment]
Definitely a silly (but big!) bug. I'll fix right away.

**Comment by cscheid** [comment]
I think the issue here is simply that I'm testing for `img == false` and match is returning nil.
