### ISSUE TITLE
[solved] Quarto does not render if df-print is kable and the tibble has lots of columns

### ISSUE THREAD

**Issue by produnis** [quarto-dev/quarto-cli#7954]
### Bug description

Hi there, it took me a while to figure out why my quarto-document was not rendering.
Consider this code:

````
---
title: "Kable test"
author: "Me"
date: 2023-12-18
lang: de
format: 
  pdf:
    df-print: kable
---

## Tibble with lot of columns

```{r}
df <- tibble::tibble(Adam = 1,
             Eva =2,
             Kevin = 0,
             August = 1,
             Steve = 3,
             Laura = 2,
             Emma = 1,
             Kiara =3,
             John =10,
             Patrick = 1,
             Penelope = 2,
             Angelika = 1
             )
df
```
````

If you click "render," Quarto does not render the document to PDF. I could not find any comments or error messages.

I then figured out that it is because the dataframe is too long for a PDF page, with too many columns. If you comment out the `df` call, then the PDF will render.

Alternatively, you could change to df-print: tibble, as this would resize the tibble to fit the page.

I was wondering if this is the expected behavior, as it took me a long time to figure out what was going wrong.

### Steps to reproduce

try to render the code above

### Expected behavior

give a message like "too many columns"

### Actual behavior

just does not render without comment

### Your environment

Archlinux,

### Quarto check output

18:06:22|produnis@Terri:~$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /sbin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib64/R
      LibPaths:
        - /home/produnis/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib/R/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Can you try updating to the latest 1.4 prerelease? I can't repro it there:

<img width="622" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/06e3be29-4a11-407f-9e92-e3f1da530001">

**Comment by produnis** [comment]
Hi, I updated to quarto 1.4.528 and the error is gone.
It just works with quarto 1.4.528.
Sorry for the hassle....
