### ISSUE TITLE
Install extensions from branch and subdirectory

### ISSUE THREAD

**Issue by Felixmil** [quarto-dev/quarto-cli#7955]
### Bug description

I am trying to install an extension that exists in a repo branch and is stored in nested directory:

https://github.com/esqLABS/esqlabsR/tree/add-project-template/inst/extdata/examples/TestProject

I found [in the documentation](https://quarto.org/docs/extensions/distributing.html#github-distribution) how to distribute from repo branch OR repo subdirectory but could not find a way to combined the two.

What I tried:

```ssh
quarto use template esqLABS/esqlabs/inst/extdata/examples/TestProject@add-project-template
> Extension not found in local or remote sources

quarto use template esqLABS/esqlabsR@add-project-template/inst/extdata/examples/TestProject/
> Extension not found in local or remote sources
```

### Steps to reproduce

```ssh
quarto use template esqLABS/esqlabs/inst/extdata/examples/TestProject@add-project-template
```

### Your environment

- OS: Windows 11

**Comment by cscheid** [comment]
I'm pretty sure that was the issue! I'm going to go ahead and close this one. If it turns out not to be the case, please reopen!

**Comment by Felixmil** [comment]
That was the issue, sorry for this mistake 🙈

However, maybe adding such an example in the documentation would be nice ?
