### ISSUE TITLE
typst: do not center code in listings

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#7959]
See `typst-float-caption-formatting-1.qmd`

**Comment by cderv** [comment]
Related issue i think upstream: 
* https://github.com/typst/typst/issues/1498

**Comment by cderv** [comment]
Though doing this seems to work 🤔 so probably only an issue for the caption 
````typst
#figure([
#set align(left)
```
SELECT * FROM Customers
```

], caption: figure.caption(
position: top, 
[
Customers #emph[query]
]), 
kind: "quarto-float-lst", 
supplement: "Listing", 
numbering: "1", 
)
<lst-customers>
````

I see if I can add to `#show figure` instead
