### ISSUE TITLE
typst: add support for remote images

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#7962]
typst doesn't seem to support remote images. E.g. this fails with an error:

````qmd
---
title: "Remote Image"
format: typst
---

![](https://raw.githubusercontent.com/quarto-dev/quarto-web/main/docs/get-started/hello/rstudio/lter_penguins.png)
````

```
error: file not found (searched at /Users/wickhamc/Documents/posit/weekly-log/2023-12-04/typst/https:/raw.githubusercontent.com/quarto-dev/quarto-web/main/docs/get-started/hello/rstudio/lter_penguins.png)
    ┌─ remote-image.typ:246:27
    │
246 │ #box(width: 720.0pt, image("https://raw.githubusercontent.com/quarto-dev/quarto-web/main/docs/get-started/hello/rstudio/lter_penguins.png"))
```

It would be nice to support this like we do for `format: pdf`.

**Comment by cderv** [comment]
For reference we do the fetching for PDF in there
https://github.com/quarto-dev/quarto-cli/blob/204f18a2331cac03c26f187ee5c48e382af71318/src/resources/filters/quarto-post/pdf-images.lua#L115-L164

We would need to refactor the Lua filters from `pdf-images.lua`

**Comment by gordonwoodhull** [comment]
Just ran into this as I need this to write my tests properly. 

Will work around with a static svg for now, but will get to this soon.

**Comment by cscheid** [comment]
That's great, let me know if you need help with it.

**Comment by cwickham** [comment]
Closing, since this now works as of 1.5.40  (https://github.com/quarto-dev/quarto-cli/pull/9723)
