### ISSUE TITLE
jupyter_core not detected

### ISSUE THREAD

**Issue by Matoyatapika** [quarto-dev/quarto-cli#7964]
### Bug description

`quarto check` fails to detect Jupyter installed in my python environment. 

from `pip list`:
```
jupyter                   1.0.0
jupyter_client            8.6.0
jupyter-console           6.6.3
jupyter_core              5.5.1
jupyter-events            0.9.0
jupyter-lsp               2.2.1
jupyter_server            2.12.1
jupyter_server_terminals  0.5.0
jupyterlab                4.0.9
jupyterlab_pygments       0.3.0
jupyterlab_server         2.25.2
jupyterlab-widgets        3.0.9
```

I traced part of the likely cause of this issue to the python function definition, `discover_package()`.

from `quarto-cli/src/resources/capabilities/jupyter.py`:

```python
def discover_package(pkg):
  sys.stdout.write('\n' + pkg + ': ')
  try:
    imp = importlib.import_module(pkg)
    sys.stdout.write(str(imp.__version__))
  except Exception:
    sys.stdout.write('null')
```

`jupyter.py` output:
```
versionMajor: 3
versionMinor: 12
versionPatch: 1
versionStr: "3.12.1 (main, Dec 11 2023, 12:40:04) [GCC 13.2.1 20230801]"
conda: false
execPrefix: "/home/lb/Packages/pyenv/versions/3.12.1"
executable: "/home/lb/Packages/pyenv/versions/3.12.1/bin/python"
jupyter_core: null
nbformat: 5.9.2
nbclient: 0.9.0
ipykernel: 6.27.1
shiny: null
```

The other part of the cause seems to be in the way`jupyter_core` 5.5.1's version is (not) provided. 

When I modify the `discover_package()` to show the actual exception, I see: `Exception: module 'jupyter_core' has no attribute '__version__'`.

Alternatively, looking at metadata for the version resolves the problem, and all `discover_package` checks work as expected.

modified `try` block in `jupyter.py` to read metadata:
```python
     version = importlib.metadata.version(pkg)
     sys.stdout.write(version)
```

`jupyter.py` output after modification:
```
versionMajor: 3
versionMinor: 12
versionPatch: 1
versionStr: "3.12.1 (main, Dec 11 2023, 12:40:04) [GCC 13.2.1 20230801]"
conda: false
execPrefix: "/home/lb/Packages/pyenv/versions/3.12.1"
executable: "/home/lb/Packages/pyenv/versions/3.12.1/bin/python"
jupyter_core: 5.5.1
nbformat: 5.9.2
nbclient: 0.9.0
ipykernel: 6.27.1
shiny: null
```

### Steps to reproduce

`quarto check` (pulled 2023-12-18 4:47PM CST) with `jupyter_core` 5.5.1

### Expected behavior

Jupyter check should succeed.

### Actual behavior

Jupyter check fails.

### Your environment

IDE: neovim 0.9.4-2
OS: EndeavourOS Linux x86_64 (kernel: 6.6.7-arch1-1)
pyenv: 2.3.35-2-g96f93fd5
python: 3.12.1
quarto: 99.9.9 (pulled 2023-12-18 04:47PM CST)
jupyter:
```
❯ jupyter --version
Selected Jupyter core packages...
IPython          : 8.18.1
ipykernel        : 6.27.1
ipywidgets       : 8.1.1
jupyter_client   : 8.6.0
jupyter_core     : 5.5.1
jupyter_server   : 2.12.1
jupyterlab       : 4.0.9
nbclient         : 0.9.0
nbconvert        : 7.13.0
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : 5.5.1
traitlets        : 5.14.0
```

### Quarto check output

```
> quarto check
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/lb/Packages/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/lb/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: /home/lb/Packages/pyenv/versions/3.12.1/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib64/R
      LibPaths:
        - /home/lb/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Thanks a lot for the report. It seems `importlib.metadata` is available since pandoc 3.8 only (https://docs.python.org/3/library/importlib.metadata.html). It seems there is a [backport library](https://importlib-metadata.readthedocs.io/en/latest/), but we can't assume it is available by default; 

@jjallaire which are the python versions we need to support ? Do we have some guideline yet ? 

Python 3.8 seems the older active python version (https://www.python.org/downloads/)
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/7ac0bd75-07c5-40c9-9334-2769edceb946)

We could add some try and fallback otherwise. 

Not sure why `jupyter_core` 5.5.1 does not have `__version__` anymore though... 🤔

**Comment by cderv** [comment]
@cscheid do you know if we have a minimum Python requirement ? 

Currently this issue make Quarto fails to detect python when `jupyter_core` is the latest.

**Comment by cscheid** [comment]
We shouldn't support any version that has been EOL'd, so 3.8 looks good.

(Kind of a harsh move for jupyter_core to remove `__version__`, but yeah, we should be using the new way)

**Comment by cderv** [comment]
Ok. We should probably highlight the change in our changelog if we go this road. 

> Kind of a harsh move for jupyter_core to remove __version__

Exactly what I thought. The new version is from yesterday, but I doubt they did that inadvertently.

**Comment by cscheid** [comment]
> Ok. We should probably highlight the change in our changelog if we go this road.

I think we might not need to, because importlib.metadata seems to work with older versions of jupyter_core too:

````
python
Python 3.10.12 (main, Jul 28 2023, 18:34:01) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib.metadata
>>> importlib.metadata.version("jupyter_core")
'5.1.3'
```

**Comment by cderv** [comment]
I meant that `importlib.metadata` was added in Python 3.8 from the doc. So if we use it, I guess it will fail on Python 3.7 and earlier.

**Comment by cderv** [comment]
I know about old (corporate) environment that don't update that easily 😅  But that is probably consider bad practice to use EOL python. So it seems like a good rule to support all active Python versions only.

**Comment by cscheid** [comment]
> But that is probably consider bad practice to use EOL python

Yes, especially because EOL'd Python versions get no security updates at all. And this EOL announcement happened in 2018...

**Comment by cscheid** [comment]
Fixed on `main`.

**Comment by astrowonk** [comment]
> Fixed on `main`.

Incredible, I just ran into this bug and then see the fix merged into main an hour ago!

**Comment by cscheid** [comment]
New installers will be out once the [GHA](https://github.com/quarto-dev/quarto-cli/actions/runs/7269819860) finishes running.

**Comment by cderv** [comment]
For reference, fixed by ccfdc52daeae74c66e4d6715ef5bbbcf2ccac05f and available in https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.531

**Comment by cderv** [comment]
Just for cross reference and tracking, this has been reported upstream later on at 
* https://github.com/jupyter/jupyter_core/issues/384

**Comment by joelostblom** [comment]
To follow up on the issue @cderv link, one of the devs responded that it was indeed an oversight to remove `__version__` and it will be back in the next jupyter_core version
