### ISSUE TITLE
image-alt / title fails in About pages

### ISSUE THREAD

**Issue by ehudkr** [quarto-dev/quarto-cli#7979]
### Bug description

`image-alt` and `image-title` are actually not supported in About pages.
Although enhancement raised in https://github.com/quarto-dev/quarto-cli/issues/3010 and presumably added in https://github.com/quarto-dev/quarto-cli/pull/3077 and included in version 1.3 (and the [docs](https://quarto.org/docs/websites/website-about.html#image)),
it seems both `image-alt` and `image-title` cause rendering to fail due to invalid YAML (and also properties are not autocomplete by vscode).

### Steps to reproduce

Assume simple About qmd file:

````qmd
---
title: "About me"
about:
  template: solana
  image: profile.jpg
  image-alt: "Does not work"
---
About me
````

### Expected behavior

About page should properly render with image having alt text and title.

### Actual behavior

Render fails with `ERROR: Render failed due to invalid YAML.`

Full error stack:
```
Error: Error in watcher: Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: ["C:\\some\\path\\to\\project\\dir\\4656678f"] }
    at new FsWatcher (deno:runtime/js/40_fs_events.js:19:23)
    at Object.watchFs (deno:runtime/js/40_fs_events.js:64:12)
    at runWatcher (file:///C:/Users/me/AppData/Local/Programs/Quarto/bin/quarto.js:102963:30)
    at file:///C:/Users/me/AppData/Local/Programs/Quarto/bin/quarto.js:102974:45
    at Array.forEach (<anonymous>)
    at watchForChanges (file:///C:/Users/me/AppData/Local/Programs/Quarto/bin/quarto.js:102968:37)    
ERROR: Validation of YAML front matter failed.
ERROR: In file C:\D\workspaces\open_source\ehudkr.github.io\index.qmd
(line 7, columns 3--12) property name image-alt is invalid
6:   image: profile.jpg
7:   image-alt: "Alt text"
    ~~~~~~~~~~
8:   links:
i The error happened in location about:image-alt.

ERROR: Render failed due to invalid YAML.
```

### Your environment

- IDE: VSCode 1.85.1
- OS: Windows 11

### Quarto check output

```Powershell
PS C:\> quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Users\me\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.1.3
      Path: C:/PROGRA~1/R/R-41~1.3
      LibPaths:
        - C:/Users/me/Documents/R/win-library/4.1
        - C:/Program Files/R/R-4.1.3/library
      knitr: 1.42
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK
```

**Comment by ehudkr** [comment]
Hi, @dragonstyle, sorry for bothering, but I skimmed c97e4ef, and although I have zero knowledge in your source, the diff suggests the fix pushed only deals with `image-alt`. 
However, and I'm sorry my original message is not as clear, there is also a similar problem with `image-title`. 
Could you please verify your fix covers that as well? Thank you.

**Comment by dragonstyle** [comment]
Good catch, thank you! See also: 75673285219ffb6f6dd6f204842b589f5ae61074 (just added)
