### ISSUE TITLE
dashboard's metadata error

### ISSUE THREAD

**Issue by lequangphu** [quarto-dev/quarto-cli#8003]
### Bug description

got value error when configure `scrolling:` and `css:` options in dashboard's metadata.
![Screenshot 2023-12-21 at 17 05 46](https://github.com/quarto-dev/quarto-cli/assets/33654804/2ec2fd60-936b-48e5-bc5b-de1e938f08d9)

### Steps to reproduce

````qmd
---
format:
  dashboard:
    scrolling: true
    css: style.css
---
````

### Expected behavior

scrolling and css works locally, and should work when deploying on github.

### Actual behavior

scrolling and css works locally, but doesn't work when deploying on github.

### Your environment

- VSCode
- MacOS Sonoma 14.2

### Quarto check output

````bash
Quarto 1.4.533
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.533
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /Users/phu/.pyenv/versions/3.11.2/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in .venv. Did you forget to activate it?

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
````

**Comment by mcanouil** [comment]
When you say "deploying on GitHub" what do you mean?
The log you shared is unrelated to that.
Are you using GitHub Actions to render your document? If so, you need to use the pre-release version, not the release.

**Comment by cderv** [comment]
I did try with 
```` markdown
---
format:
  dashboard:
    scrolling: true
    css: style.css
---

# Content

````

And it renders ok 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/ab4f380b-90da-49b6-a9b4-210cd9eeeaeb)

**Comment by lequangphu** [comment]
> When you say "deploying on GitHub" what do you mean? The log you shared is unrelated to that. Are you using GitHub Actions to render your document? If so, you need to use the pre-release version, not the release.

I meant publish the dashboard to gh pages. You are right, when it works locally but not in gh action, I should've checked quarto's version.

Could you point me to any guide to set gh action to use the pre-release version?

**Comment by mcanouil** [comment]
Either go to Quarto documentation or to the GitHub repository there actions source code are located.

**Comment by lequangphu** [comment]
I found it, share it here for others

https://github.com/quarto-dev/quarto-actions/tree/main/setup#inputs-available
