### ISSUE TITLE
Cannot access dimensions of image within two column layout

### ISSUE THREAD

**Issue by acebulsk** [quarto-dev/quarto-cli#8009]
### Bug description

Cannot adjust images to the same height using `height="500"` i.e.,

```![Image 1](img_link.jpg){#fig-a height="500"}```

when within a two column layout (i.e., ::: {#fig-maps layout-ncol=2}) within a quarto doc with HTML output.

### Steps to reproduce

````
---
title: "Untitled"
format: html
editor: visual
---

::: {#fig-maps layout-ncol=2}

![Image 1](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg/200px-African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg){#fig-a height="500"}

![Image 2](https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Elephas_maximus_%28Bandipur%29.jpg/200px-Elephas_maximus_%28Bandipur%29.jpg){#fig-b height="500"}

Image of elephant (a) and elephant (b).
:::
````

### Expected behavior

Works outside of the div:

```
![Image 1](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg/200px-African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg){#fig-a height="500"}

![Image 2](https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Elephas_maximus_%28Bandipur%29.jpg/200px-Elephas_maximus_%28Bandipur%29.jpg){#fig-b height="500"}
```

### Actual behavior

No adjustment to images when inside the div.

### Your environment

- IDE RStudio 2023.06.1 Build 524
- OS Ubuntu 22.04.3 LTS

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.1.4
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib/R
      LibPaths:
        - /home/alex/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK```
```

**Comment by cderv** [comment]
Can you try with Quarto 1.4 pre-release ?  I can't reproduce

Without `height` set we get 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/d712ec56-459c-4c8b-9fac-d6212aeb7d13)


with your code we get 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/47624e81-4071-458a-8c79-985d624a6d24)

**Comment by acebulsk** [comment]
Okay it is working now with quarto (1.4.533). Thank you! Enjoying some of the new changes already (html preview keeps its position after rendering, and better error messaging).

Cheers! 
Alex
