### ISSUE TITLE
Text in book footnotes are the ONLY thing found in search

### ISSUE THREAD

**Issue by sjspielman** [quarto-dev/quarto-cli#8011]
### Bug description

In my quarto book, the search is _only_ returning text in the footnotes, not in the main text.  I came across this issue when looking for a solution to this problem, perhaps it's related - https://github.com/quarto-dev/quarto-cli/issues/4601

In this screenshot, you can see that the word "thousands" was not found, but it is clearly in the text. Navigate to https://sjspielman.github.io/sam-kasten/chapters/01_1946-09-07.html (or any book chapter) and search to see search behavior. 

<img width="870" alt="Screenshot 2023-12-21 at 10 48 37 PM" src="https://github.com/quarto-dev/quarto-cli/assets/4701111/93c3684e-10ce-4175-8eb6-092909afac09">

**Comment by dragonstyle** [comment]
Thanks for reporting this! The fix will be available in our next 1.4 pre-release build.

**Comment by sjspielman** [comment]
Thanks, @dragonstyle!
