### ISSUE TITLE
Rendering _index.qmd (hugo) files in quarto projects

### ISSUE THREAD

**Issue by linogaliana** [quarto-dev/quarto-cli#802]
- I have seen [in the doc](https://quarto.org/docs/projects/quarto-projects.html#render-targets) the following statement :

> By default, all valid Quarto input files (.qmd, .ipynb, .md, .Rmd) in the project directory will be rendered, save for ones with a file or directory prefix of . (hidden files) or _ (typically used for non top-level files, e.g. ones included in other files).

- which makes the `**/_index.md` files ignored (a question that has been discussed in #207).

However, from [`hugo` doc](https://gohugo.io/content-management/organization/#index-pages-_indexmd) :

> `_index.md` has a special role in Hugo. It allows you to add front matter and content to your [list templates](https://gohugo.io/templates/lists/). These templates include those for [section templates](https://gohugo.io/templates/section-templates/), [taxonomy templates](https://gohugo.io/templates/taxonomy-templates/), [taxonomy terms templates](https://gohugo.io/templates/taxonomy-templates/), and your [homepage template](https://gohugo.io/templates/homepage/).
> 
> You can create one _index.md for your homepage and one in each of your content sections, taxonomies, and taxonomy terms. The following shows typical placement of an _index.md that would contain content and front matter for a posts section list page on a Hugo website

When using the following rule in `_quarto.yml`, the `_index.qmd` files are still also ignored. 

```yaml
  render:
    - content/**/*.qmd
```

They are also ignored when hardcoding the path in `_quarto.yml`, e.g. in my case:

```yaml
project:
  title: "python-datascientist"
  render:
    - content/**/*.qmd
    - content/course/manipulation/_index.qmd
```

(the file exists at `content/course/manipulation/_index.qmd`)

When executing `quarto render content/course/manipulation/_index.qmd --to hugo`, everything works fine.

Is there an additional option to use not to ignore `_index.qmd` files at project level ?

**Comment by jjallaire** [comment]
Yeah, the `_` prefixed directories and files are hard-ignored. What'd I'd recommend is providing an explicit `output-file` in the YAML for listing indexes (which you could use the source file name `index.md` for:

```yaml
---
output-file: _index.md
---
```

**Comment by linogaliana** [comment]
Thanks for the suggestion. It solved my issue.

I proposed https://github.com/quarto-dev/quarto-web/pull/152 to let people know about that recommendation
