### ISSUE TITLE
Left and Right margins are obstructing content on the page.

### ISSUE THREAD

**Issue by ajay333a** [quarto-dev/quarto-cli#8020]
### Bug description

On the page of "Article Layout" I scrolled up and the table of content appeared which was good but after I started scrolling up or down on the page table of contents did not shrink, kindly please fix the as it is difficult to find what was on the margin when I am on this page.

### Steps to reproduce

Land on the page "https://quarto.org/docs/authoring/article-layout.html" then scroll down for some length and scroll up the
 side bar and toc appear but don't shrink after scrolling down again or by pressing the button on the "toc" or the "article"

### Expected behavior

"sidebar" and "toc" to shrink once I start scrolling down.

**Comment by cderv** [comment]
I can't see what you are seeing it seems 

https://github.com/quarto-dev/quarto-cli/assets/6791940/732c6aea-e09f-418d-981f-8ca39bab0200

**Comment by aborruso** [comment]
@cderv I see this


https://github.com/quarto-dev/quarto-cli/assets/30607/97fe7c2f-1a3d-475f-b878-51dbea6c29e2

**Comment by dragonstyle** [comment]
Something is definitely not quite right here. I made a change related to sidebar height that is likely related - I'll investigate further.
