### ISSUE TITLE
Request:  allow user to specify "nomangle" to OJS code

### ISSUE THREAD

**Issue by zachcp** [quarto-dev/quarto-cli#803]
Hi Team Quarto,

Thank you for this awesome project. I have been absolutely loving the incorporation of Observable into MD - its a real killer combo.  

Is it possible to turn off the OJS compilation step that mangles/minimizes names? When developing locally you can always tweak an active Quarto session, however, when using Quarto as a template in a data pipeline it can be difficult to troubleshoot javascript issues because the original names are lost.

zach cp

**Comment by cscheid** [comment]
We currently don't have a non-minified OJS runtime available, but that's a good idea. I'm about to start some work in refreshing our OJS infrastructure, so I'll add it to the list.

**Comment by cscheid** [comment]
We recently switched to a non-minified, bundled version of the quarto+observable JS runtime. You should be able to more easily navigate the internal behavior now.

<img width="1769" alt="image" src="https://user-images.githubusercontent.com/285675/167731092-f421c147-5090-4ec7-a3a2-f20aec79e843.png">

**Comment by zachcp** [comment]
Fantastic. Thank you
