### ISSUE TITLE
preview does not show plot after rebuild of document

### ISSUE THREAD

**Issue by MarcSkovMadsen** [quarto-dev/quarto-cli#8030]
### Bug description

I'm trying to learn how to use Quarto with the HoloViz ecosystem of tools.

When I create a very simple example using hvPlot it works initially, but upon re-rendering my plot is not shown.

### Steps to reproduce

````
---
title: hvPlot in Quarto Examples
format: html
---

This is a hvPlot embedded in a Quarto document

```{python}
import hvplot.pandas
import pandas as pd

df=pd.DataFrame({"x": [1,2,3], "y": [1,3,2]})

df.hvplot(x='x', y='y', height=400, responsive=True)
```
````

```bash
quarto preview script.qmd --port 5008
```

https://github.com/quarto-dev/quarto-cli/assets/42288570/9838ed1c-2162-4b4f-a708-6fffbc3e2cd6

(download and run the video if it does not display well when embedded on github)

### Expected behavior

When I trigger the quarto preview to rerender by adding ` SOME CHANGE` then I would expect the plot to be shown.

### Actual behavior

The plot is not shown

### Your environment

OS: linux
Python 3.11
quarto: 1.3.450
r-quarto: 1.3
hvplot: 0.9.1

Everything is installed in a fresh conda environment from scratch using

```bash
conda create -n quarto-holoviz -c conda-forge python=3.11 r-quarto perl hvplot matplotlib panel jupyter
```

### Quarto check output

```bash

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.58.3: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /home/jovyan/conda-envs/quarto-holoviz/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7 (Conda)
      Path: /home/jovyan/conda-envs/quarto-holoviz/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /home/jovyan/conda-envs/quarto-holoviz/lib/R
      LibPaths:
        - /home/jovyan/conda-envs/quarto-holoviz/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

The above says that jupyter is not installed in the environment. But it actually is

![image](https://github.com/quarto-dev/quarto-cli/assets/42288570/753bdd76-f5d0-4a0b-8626-b7ba3a1af8e1)

## Browser Console

On the initial rerender the `bokeh` js extension is loaded and the plot renders.

![image](https://github.com/quarto-dev/quarto-cli/assets/42288570/aef5f76b-ab12-401d-b71a-6e5024c20a4f)

On the second rerender the `bokeh` and/ or `panel` js extension is not available.

![image](https://github.com/quarto-dev/quarto-cli/assets/42288570/6fa61a2b-770e-4708-9736-db9daef178b1)

FYI. hvPlot and Panel are build on top of Bokeh.

## Refreshing the browser

If I refresh the browser after the rerender the plot is not shown.

## Contact HoloViz

If the issue is HoloViz related please let me know, contact the holoviz developers via discord https://discord.gg/rb6gPXbdAr or make an issue on the [hvPlot Github](https://github.com/holoviz/hvplot). Thanks.

**Comment by MarcSkovMadsen** [comment]
I can see that if you add a `hvplot.extension` line it works.

````
---
title: hvPlot in Quarto Examples
format: html
---

This is a hvPlot embedded in a Quarto document.

```{python}
import hvplot.pandas
import pandas as pd

hvplot.extension()

df=pd.DataFrame({"x": [1,2,3], "y": [1,3,2]})

df.hvplot(x='x', y='y', height=400, responsive=True)
``
````

https://github.com/quarto-dev/quarto-cli/assets/42288570/1d404551-41d4-48ac-8e45-4d2db80d3a50

**Comment by MarcSkovMadsen** [comment]
## Same for HoloViews

Its the same issue for HoloViews plots. Here the workaround is to add the line `hv.extension(...)` once.

**Comment by MarcSkovMadsen** [comment]
I will close this. I believe this should be handled on the HoloViz side.

**Comment by nickvazz** [comment]
Hi @MarcSkovMadsen, I tried using your example and it doesn't seem like the resultant hvplot is interactive. Is there some setting I need to set?

<img width="848" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8573886/30b5106c-9846-47a6-9fc7-2c584ab4f0f8">

Thank you!

**Comment by mcanouil** [comment]
@nickvazz Could you open a GitHub discussion and reference this issue that has been closed for more than six months? Thank you.
