### ISSUE TITLE
Table and figure captions not working in AsciiDoc

### ISSUE THREAD

**Issue by jeroenjanssens** [quarto-dev/quarto-cli#8055]
### Bug description

The latest pre-release of Quarto (v1.4.533) produces AsciiDoc syntax that causes figure and table captions to be disconnected. The captions appear as a numbered list with a single item. This problem does not exist for HTML and PDF outputs.

### Steps to reproduce

Save the following code to *caption.qmd*.

````qmd
---
title: Caption
---

@tbl-fruit shows just how expensive fruit is these days.

fruit| price
-----|-----:
apple|2.05
pear|1.37
orange|3.09

: Various fruits and their prices {#tbl-fruit}


And if that's not convincing, consider @fig-fruit.

```{mermaid}
%%| label: fig-fruit
%%| fig-cap: Pretty convincing
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```

Fin.
````

### Expected behavior

I'm not exactly sure what the correct AsciiDoc syntax is, but the latest Quarto release (v1.3.450) produces: 

```
= Caption

<<tbl-fruit>> shows just how expensive fruit is these days.

[[tbl-fruit]]
.Various fruits and their prices
[cols=",>",options="header",]
|===
|fruit |price
|apple |2.05
|pear |1.37
|orange |3.09
|===

And if that’s not convincing, consider <<fig-fruit>>.

.Pretty convincing
[#fig-fruit]
image:caption_files/figure-asciidoctor/mermaid-figure-1.png[caption_files/figure-asciidoctor/mermaid-figure-1,width=550,height=133]

Fin.
```

### Actual behavior

The command:

```
$ quarto render caption.qmd --quiet --to asciidoc --output -
```

Produces:

```
= Caption

<<tbl-fruit>> shows just how expensive fruit is these days.

. Various fruits and their prices
[[tbl-fruit]]
====

[cols=",>",options="header",]
|===
|fruit |price
|apple |2.05
|pear |1.37
|orange |3.09
|===

====

And if that’s not convincing, consider <<fig-fruit>>.

. Pretty convincing
[[fig-fruit]]
====

image:caption_files/figure-asciidoc/mermaid-figure-1.png[caption_files/figure-asciidoc/mermaid-figure-1,width=550,height=133]

====

Fin.
```

### Your environment

OS: macOS Monterey 12.5

### Quarto check output

```
Quarto 1.4.533
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.533
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/jeroen/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /Users/jeroen/.pyenv/versions/3.11.1/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by jeroenjanssens** [comment]
I was wondering, which AsciiDoc implementation do you use as reference? Is it https://docs.asciidoctor.org/ by any chance?

**Comment by cderv** [comment]
> I was wondering, which AsciiDoc implementation do you use as reference? Is it [docs.asciidoctor.org](https://docs.asciidoctor.org/) by any chance?

We should produce asciidoc based on `--to asciidoc`. Per: https://pandoc.org/MANUAL.html#option--to 
> (modern [AsciiDoc](https://www.methods.co.nz/asciidoc/) as interpreted by [AsciiDoctor](https://asciidoctor.org/))

So we do handle Tables caption as part of new float ref, and not producing right syntax it seems

**Comment by cderv** [comment]
Currently the 1.4 version produced asciidoc shows this (in https://asciidoclive.com/)

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/b056ccae-7dd5-4efe-a0ba-78654f056f84)

I believe there are first is several issues here: 

```asciidoc
. Various fruits and their prices
```

There should not be a space after the `.` here. 

````asciidoc
image:caption_files/figure-asciidoc/mermaid-figure-1.png[caption_files/figure-asciidoc/mermaid-figure-1,width=550,height=133]
````

There should be probably two colons after image i.e  `image::`  (https://docs.asciidoctor.org/asciidoc/latest/macros/images)

but even changing this does get only thus far
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/46e9912c-6a5a-4f76-a87d-7379483a8df5)

So get the caption outside of Figure and Table blocks, which leads to having them numbered by asciidoc differently. 

But let's note that Quarto 1.3 produces this 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/c9fc9c14-0e33-4c19-96d3-3befb0a564c9)

the `image:` issue is present in 1.3. Fixing it get us this 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/341810a1-9c46-4475-8a9d-e71b29744eec)


So definitely some problems: 

- Wrong syntax produced for figures in 1.3 and 1.4
- Wrong caption placement causing wrong labelling and numbering in 1.4

**Comment by cderv** [comment]
This was modified in #6620 where previous function for figures `asciidocFigure` and `asciidocDivFigure` from `asciidoc.lua` are no more used now. (we should probably document that in note in code that they are unused now... 🤔 )

Asciidoc generation is done here I believe:
https://github.com/quarto-dev/quarto-cli/blob/27b29d91edb577c1bf4e3b2e7958be0239eddfaf/src/resources/filters/customnodes/floatreftarget.lua#L780-L798

Space after dot is there at least.
https://github.com/quarto-dev/quarto-cli/blob/27b29d91edb577c1bf4e3b2e7958be0239eddfaf/src/resources/filters/customnodes/floatreftarget.lua#L789

For the `image:` , I believe this is due to the float content generation, that produce inline 

Intermediate md is 
````markdown
:::{.cell layout-align="default"}

:::{.cell-output-display}

:::{#fig-fruit}

:::{}

![](index_files\figure-asciidoc\mermaid-figure-1.png){width="5.74in" height="1.4in"}
:::


Pretty convincing
:::
:::
:::
````

So it seems the mermaid output is producing a `Div` around the image, which leads to the asciidoc output - Without this div the figure would be ok. This works fine for example 

````markdown
---
title: Caption
format: asciidoc
keep-md: true
---

::: {#fig-elephant}

![](elephant.png)

This is a a caption

:::

````

So overall, several issues / questions here with asciidoc generation - we may need to handle them one by one ... 🤔

**Comment by cscheid** [comment]
I'm going to add the immediate fixes to 1.4, but we definitely need to get asciidoc in that "features x formats" table we've been talking about. I'm sure there's going to be other bugs lurking..

**Comment by cscheid** [comment]
PR is up. @jeroenjanssens Would you mind doing a spot check on the output we're generating in that branch? Thank you!

**Comment by jeroenjanssens** [comment]
Looks good to me. Thanks!

Generated AsciiDoc:

```asciidoc
= Caption

<<tbl-fruit>> shows just how expensive fruit is these days.

[[tbl-fruit]]
.Various fruits and their prices
[cols=",>",options="header",]
|===
|fruit |price
|apple |2.05
|pear |1.37
|orange |3.09
|===

And if that’s not convincing, consider <<fig-fruit>>.

.Pretty convincing
[#fig-fruit]
image::caption_files/figure-asciidoc/mermaid-figure-1.png[Pretty convincing,width=550,height=133]

Fin.
```

PDF generated with `asciidoctor-pdf`:

<img width="583" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/1368256/25ed8370-9e32-4425-a62c-4bacf27d94ca">
