### ISSUE TITLE
Add automated testing for platform support

### ISSUE THREAD

**Issue by jthomasmock** [quarto-dev/quarto-cli#807]
Quarto has been confirmed to run on the various platforms as indicated on [Platform Support](https://www.rstudio.com/about/platform-support/), outside of CentOS7 which is a known issue #61 

It would be good to add a minimal automated test for the linux distros on [Platform Support](https://www.rstudio.com/about/platform-support/) that Quarto can be compiled, installed, and CLI is usable to prevent any regressions or failures to build/compile over time.

**Comment by jjallaire** [comment]
For now we'll rely on the basic `quarto render` tests for RStudio on all of its platforms to ensure that we at least work.
