### ISSUE TITLE
Mobile view of blog post listing uses just half of the horizontal space

### ISSUE THREAD

**Issue by TheGoodCartman** [quarto-dev/quarto-cli#8070]
### Bug description

When I open my blog homepage (listing of the blog posts) on a mobile device, the posts just use the left half of the screen.

The error comes from css:
<img width="1085" alt="with width" src="https://github.com/quarto-dev/quarto-cli/assets/114695669/b2576e90-a663-49b5-a8a7-e96c8542c541">

If you remove the `width`-Attribute, it looks correct:
<img width="1091" alt="without width" src="https://github.com/quarto-dev/quarto-cli/assets/114695669/a8f5e8e0-10f1-4805-b2b8-92bca887501a">

The `width`-Attribute was added with this Commit: https://github.com/quarto-dev/quarto-cli/commit/70005c1421e40468a21a52ac2c1e1b7fb9aefd9a

### Expected behavior

On mobile view blog posts in listing use the full width of the screen.

### Actual behavior

On mobile view blog posts in listing use just half of the screen.

### Your environment

I use Github Action Runner
```
Operating System
  Ubuntu
  22.04.3
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20231217.2.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231217.2/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231217.2
```

### Quarto check output

I use the Github Action.
```
Run quarto-dev/quarto-actions/setup@v2
  with:
    version: pre-release
    tinytex: false
```
In the end it installs https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.533/quarto-1.4.533-linux-amd64.deb

**Comment by mcanouil** [comment]
I can reproduce on the latest pre-release version.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/be9a9957-c4a9-445a-beb3-f3be9608ab2e">

Note that this is a regression as it was displayed correctly in 1.3.450.
