### ISSUE TITLE
Bibliography: Title all lowercase

### ISSUE THREAD

**Issue by roland-KA** [quarto-dev/quarto-cli#8072]
### Bug description & Actual behavior

When generating a bibliography specifying a csl-file in `_quarto.yml` as e.g.

```
bibliography: SoftwareEngineering.bib
cite-method: citeproc
csl: ieee
```

The resulting bibliography in my documents generated using

```
::: {#refs}
:::
```

print the titles (as well as other parts of the citation) of the literature referenced always completely in lowercase letters as e.g.

> H. Balzert and P. Liggesmeyer, Lehrbuch der softwaretechnik. 2: Entwurf, implementierung, installation und betrieb / helmut balzert. Unter mitw. Von peter liggesmeyer, 3. Auflage. in Lehrbücher der informatik. Heidelberg: Spektrum, Akademischer Verlag, 2011.

### Expected behavior

Actually it should print the title "Lehrbuch der **S**oftwaretechnik. 2: **E**ntwurf, **I**mplementierung, **I**nstallation und **B**etrieb / **H**elmut **B**alzert. Unter mitw. von **P**eter **L**iggesmeyer ..."

I've tried several csl-files, but this problems occurs in every case I've tried. The title gets printed correctly when I omit the csl-file specification thus using Quartos defaults.

How can I get correct titles using csl-files?

### Your environment

IDE: VS Code 1.85, Quarto-Plugin v1.109.0
OS: MacOS Sonoma 14.2.1 (23C71)

### Quarto check output

```
quarto check

[✓] Checking Quarto installation......OK
      Version: 1.2.335
      Path: /Users/roland/Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.8 (Conda)
      Path: /Users/roland/.julia/conda/3/bin/python3
      Jupyter: 5.2.0
      Kernels: julia-1.8, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
This is unrelated to Quarto.
CSL are not defined by Quarto (or Pandoc).

If you need to modify CSL, then you'll have to look for online resources such as <https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step>.
Alternatively, there are plenty of CSL files and derivatives in Zotero and GitHub (links in the documentation: https://quarto.org/docs/authoring/footnotes-and-citations.html#sec-citations-style).

I am going ahead and closing as it is a third party issue.

**Comment by roland-KA** [comment]
Sorry, but I think that is a misunderstanding. My issue is not about specific CSL definitions.

**ALL** CSL-files I've tried show this behaviour in Quarto! So the problem is caused either by Quarto or by Pandoc when handling these files.

Where does the processing of the bibliography (and the CSL-files) take place?

**Comment by mcanouil** [comment]
Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Comment by roland-KA** [comment]
Thank you for your feedback! I've upgraded Quarto now to the current release 1.3.450.

# Minimal setting to reproduce the error

The minimal setting to reproduce the problem consists of four files:
- `BibTest.qmd` 
- `_quarto.yml`
- `SoftwareEngneering.bib`
- `ieee.csl` (you can get it via this [Link](https://www.zotero.org/styles/ieee?source=1) from the Zotero Style Repository; as mentioned above, I've used several other CSL-files which show exactly the same behaviour)

`BibTest.qmd` contains:
````qmd
## A new slide

see [@balzert_lehrbuch_2011]

---

## References 

::: {#refs}
:::
````

`_quarto.yml` looks as follows:

```
bibliography: SoftwareEngineering.bib
cite-method: citeproc
csl: ieee

format:
  revealjs:
    theme: [default]
```

This is the Bibtex-file `SoftwareEngineering.bib` containing one reference:

```
@book{balzert_lehrbuch_2011,
	location = {Heidelberg},
	edition = {3. Auflage},
	title = {Lehrbuch der Softwaretechnik. 2: Entwurf, Implementierung, Installation und Betrieb / Helmut Balzert. Unter Mitw. von Peter Liggesmeyer},
	isbn = {978-3-8274-1706-0},
	series = {Lehrbücher der Informatik},
	shorttitle = {Lehrbuch der Softwaretechnik. 2},
	pagetotal = {596},
	publisher = {Spektrum, Akademischer Verlag},
	author = {Balzert, Helmut and Liggesmeyer, Peter},
	date = {2011},
	file = {Table of Contents PDF:/Users/roland/Zotero/storage/IVY9MMS2/Balzert und Liggesmeyer - 2011 - Lehrbuch der Softwaretechnik. 2 Entwurf, Implemen.pdf:application/pdf},
}
```

# How to reproduce the error

Using `quarto render --to revealjs` generates a HTML-file `BibTest.html`

The resulting Bibliography looks as follows:

<img width="806" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/80126696/fa3b7f5a-c175-4375-8e72-691fbde0d368">

# (Almost) Expected behaviour

Deleting the line `csl: ieee` in `_quarto.yml` uses the Quarto default mechanism to generate a bibliography. This results in:

<img width="836" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/80126696/c439a68a-2331-4be5-832a-c2987a65287c">

Here we see a spelling with capitals ... but it is also not completely correct as it capitalizes now all words from the BibText-reference. The correct behaviour would be to leave the text unchanged as it is in the BibText file.

**Comment by mcanouil** [comment]
The issue has nothing to do with CSL, Pandoc, or Quarto.
Most CSL uses first letter in uppercase only. To go against that you need additional brackets.
This is described in many places, for example and amongst other places: https://pandoc.org/MANUAL.html#capitalization-in-titles


```bib
@book{balzert_lehrbuch_2011,
	location = {Heidelberg},
	edition = {3. Auflage},
	title = {{Lehrbuch der Softwaretechnik. 2: Entwurf, Implementierung, Installation und Betrieb / Helmut Balzert. Unter Mitw. von Peter Liggesmeyer}},
	isbn = {978-3-8274-1706-0},
	series = {Lehrbücher der Informatik},
	shorttitle = {Lehrbuch der Softwaretechnik. 2},
	pagetotal = {596},
	publisher = {Spektrum, Akademischer Verlag},
	author = {Balzert, Helmut and Liggesmeyer, Peter},
	date = {2011},
	file = {Table of Contents PDF:/Users/roland/Zotero/storage/IVY9MMS2/Balzert und Liggesmeyer - 2011 - Lehrbuch der Softwaretechnik. 2 Entwurf, Implemen.pdf:application/pdf},
}
```

**Comment by roland-KA** [comment]
Thank you very much for your help! With a tool like Quarto, that integrates several other tools, it is often difficult to know, which part of the technology stack is the root for some behaviour.

**Comment by njbart** [comment]
What has been overlooked here is quite simply that non-English titles require a `langid` tag for proper capitalisation. Try `langid={de-DE}`, `langid={german}`, or `langid={ngerman}`. This applies both to CSL (which is used here under the hood) and to biblatex.

**Comment by roland-KA** [comment]
That's the point.

I'm using Zotero for bibilographies (and generate Bibtex-files from there). Titles which are added from central catalogs by using an ISBN or similar identifiers often don't have a value this field. So it has to be added manually.
