### ISSUE TITLE
Update Menu to include Theme options and Transitions

### ISSUE THREAD

**Issue by rleyvasal** [quarto-dev/quarto-cli#808]
Can the Menu be updated to allow user to change Themes and Transitions on the fly?

Menu plugin from https://github.com/rajgoel/reveal.js-plugins  can change the theme of the slides and transition right from the menu.

![menu](https://user-images.githubusercontent.com/61335136/167005372-7123b143-38c4-4ccc-84ce-da23128feadf.PNG)

**Comment by jjallaire** [comment]
We don't have a way to do that b/c of the way we compile themes (we do an SCSS compilation on the fly rather than having them all sitting in a static directory).
