### ISSUE TITLE
TLA+ code isn't recognized by Quarto

### ISSUE THREAD

**Issue by younes-io** [quarto-dev/quarto-cli#8081]
### Bug description

I wrote this code:

![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/b804cfc2-70f9-4327-a490-cb1f542ab577)

which should be highlighted like this:

```tla
EXTENDS Integers
```

```python
print("This works! But why doesn't TLA+ work?")
```

Unfortunately, the TLA+ code isn't highlighted / recognized by Quarto.

### Steps to reproduce

Described above (cf. description)

### Expected behavior

The TLA+ code should be highlighted.

### Actual behavior

![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/52beb201-41ad-4226-bdeb-981e766827b8)

### Your environment

- IDE: VSCode
- Windows 11 & WSL2

### Quarto check output

`` bash
$ quarto check
A new release of Deno is available: 1.28.2 → 1.39.1 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: C:/Users/youne/AppData/Local/Programs/Python/Python312/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

      There is a requirements.txt file in this directory. Is this for a venv that you need to restore?

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/youne/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by younes-io** [comment]
Just found this https://github.com/jgm/skylighting/tree/master/skylighting-core/xml
Indeed, Pandoc doesn't support TLA+, it seems

**Comment by mcanouil** [comment]
As you noticed yourself, this isn't a Quarto/Pandoc issue.
You can submit a new language to <https://github.com/jgm/skylighting>.

I am closing this as there is nothing to be done on Quarto side.
