### ISSUE TITLE
Setting `eval` in Jupyter code cell causes non-evaluation

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8089]
### Bug description

When setting `eval` in a Julia code cell, plots are no longer displayed.
Defining `eval` at the top level (execute) works properly.

CC @cderv (he tested with 1.9 before the holidays)

````qmd
---
title: "Plot"
format: html
jupyter: julia-1.10
execute:
  echo: false
---

## Plot with default

```{julia}
using Plots

x = -3.0:0.01:3.0
y = rand(length(x))
plot(x, y)
```

## Plot with `eval: true`

```{julia}
#| eval: true
using Plots

x = -3.0:0.01:3.0
y = rand(length(x))
plot(x, y)
```

## Plot with `eval: false`

```{julia}
#| eval: false
using Plots#| 

x = -3.0:0.01:3.0
y = rand(length(x))
plot(x, y)
```

````

<img width="721" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/dcb3902e-73d2-479b-97a7-f3a1719d4018">

**Comment by cscheid** [comment]
I can verify that the .ipynb that we get from nbclient doesn't have outputs from the `eval: true` cell.

**Comment by cscheid** [comment]
This is not julia-specific. The following .qmd fails similarly

````
---
title: "Plot"
format: html
keep-md: true
keep-ipynb: true
execute:
  echo: false
---

## Plot with default

```{python}
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
```

## Plot with `eval: true`

```{python}
#| eval: true
plt.plot([2, 3, 4, 5])
```

## Plot with `eval: false`

```{python}
#| eval: false
plt.plot([1, 2, 3])
```
````

**Comment by cscheid** [comment]
Our Python jupyter.py code is interpreting `true` as the string `true` and not as the boolean `True`.

**Comment by cscheid** [comment]
PyYAML, why!??!!

```
> yaml.load("foo: true", yaml.BaseLoader)
{'foo': 'true'}
```
