### ISSUE TITLE
ERROR: Template partial was not found

### ISSUE THREAD

**Issue by pieterprovoost** [quarto-dev/quarto-cli#8103]
### Bug description

I'm not able to render a minimal dashboard with quarto-cli 1.4.534, presumable due to incorrect partials path resolution. `quarto render test.qmd` results in:

```bash
ERROR: Template partial /Users/pieter/Desktop/quarto/Applications/quarto/share/formats/dashboard/title-block.html was not found. Please confirm that the path to the file is correct.

Stack trace:
    at file:///Applications/quarto/bin/quarto.js:41469:19
    at Array.flatMap (<anonymous>)
    at readPartials (file:///Applications/quarto/bin/quarto.js:41463:20)
    at runPandoc (file:///Applications/quarto/bin/quarto.js:68818:30)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async renderPandoc (file:///Applications/quarto/bin/quarto.js:70020:26)
    at async Object.onRender (file:///Applications/quarto/bin/quarto.js:77193:36)
    at async renderFileInternal (file:///Applications/quarto/bin/quarto.js:77170:17)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:76994:17)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:77321:25)
```

Source:

```qmd
---
title: "Testing dashboard"
author: "Test Author"
format: dashboard
---

Test.
```

### Your environment

- OS: macOS Sonoma 14.2.1

### Quarto check output

```bash
Quarto 1.4.534
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.534
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Users/pieter/.pyenv/versions/3.9.6/bin/python3
      Jupyter: 4.10.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
I cannot reproduce using the latest development version.

**Comment by cscheid** [comment]
Something strange is happening with paths here. Note that we're attempting to resolve the title-block partial in this path:

```
/Users/pieter/Desktop/quarto/Applications/quarto/share/formats/dashboard/title-block.html
```

While quarto itself is located at

```
file:///Applications/quarto/bin/quarto.js:41463:20
```

I don't understand how that could be happening, even with multiple Quarto installations. Do you have a non-standard environment variable setup?

The code for readPartials is:

```ts
export function readPartials(
  metadata: Metadata,
  inputDir?: string,
) {
  if (typeof (metadata?.[kTemplatePartials]) === "string") {
    metadata[kTemplatePartials] = [metadata[kTemplatePartials]];
  }
  const result = (metadata?.[kTemplatePartials] || []) as string[];

  inputDir = inputDir ? normalizePath(inputDir) : undefined;
  const resolvePath = (path: string) => {
    if (!inputDir || isAbsolute(path)) {
      return path;
    } else {
      return join(inputDir, path);
    }
  };

  return result.flatMap((path) => {
    const result = [];
    for (const walk of expandGlobSync(resolvePath(path))) {
      result.push(walk.path);
    }
    if (!isGlob(path) && result.length === 0) {
      throw new Error(
        `Template partial ${path} was not found. Please confirm that the path to the file is correct.`,
      );
    }
    return result;
  });
}
```

It seems that something is confusing the `resolvePath` call, but I don't understand what that could be.

**Comment by cderv** [comment]
@cscheid I am not a MAC user and can't test but 

* `inputDir = inputDir ? normalizePath(inputDir) : undefined;` : I believe this will be the input directory which is probably the `/Users/pieter/Desktop/quarto/` part

* `return join(inputDir, path);` which get appended if `path` is not seen as absolute by `isAbsolute` somehow

In this case  I believe `isAbsolute` should be true on the partial path

That would explained the wrong built path to me... 

What do you think ? 

@dragonstyle did we deal with something similar recently with absolute path being not detected ? But it was on windows I think.

**Comment by pieterprovoost** [comment]
@cscheid I don't have a non-standard install as far as I'm aware, this is a fresh first-time installation. I did try the 1.4.451 pre-release build now which works fine, but it breaks when I install 1.4.534 again.

**Comment by dragonstyle** [comment]
I'll have a look at this- I added a check for template resolution that now throws an error instead of silently failing, so this is something likely related to non-developer install locations. I'll update here shortly.

**Comment by dragonstyle** [comment]
Well I spent some time testing with a variety of local installations and I can't get this to happen either. 

A couple questions:

1) When you run `which quarto | xargs ls -ln` what is the path that you see? 
```bash
$ which quarto | xargs ls -ln
lrwxr-xr-x  1 0  80  31 Jan  3 12:28 /usr/local/bin/quarto -> /Applications/quarto/bin/quarto
```

2) Could there be a path cached in your shell/terminal that is somehow confusing us? Could you try a fresh terminal session and see whether it still reproduces?

I'm thinking that 1.4.451 likely 'works' in the sense that it doesn't error, but it is likely silently using this incorrect path and failing to properly render the title block for the dashboard.

**Comment by dragonstyle** [comment]
That seems correct- the project change was a recent one which likely introduced this. Thanks for clue and pointer to the code. I'll test with a project!

**Comment by odysseu** [comment]
Hi, I am having a similar issue. But this time it is with the `_title-meta-author.html` file : 

Under windows (with French parameters), using a git bash terminal :

> ```batch
> [DEDACTED] MINGW64 /c/[DEDACTED]/gitlab/Guide_Informatique (main)
> $ quarto --version
> 1.8.23
> 
> [DEDACTED] MINGW64 /c/[DEDACTED]/gitlab/Guide_Informatique (main)
> $ quarto preview
> Preparing to preview
> [ 1/19] index.qmd
> ERROR: Template partial C:\[DEDACTED]\Programmes\quarto\share\formats\html\templates\_title-meta-author.html was not found. Please confirm that the path to the file is correct.
> 
> Stack trace:
>     at file:///C:/[DEDACTED]/Programmes/quarto/bin/quarto.js:79036:13
>     at Array.flatMap (<anonymous>)
>     at readPartials (file:///C:/[DEDACTED]/Programmes/quarto/bin/quarto.js:79030:18)
>     at runPandoc (file:///C:/[DEDACTED]/Programmes/quarto/bin/quarto.js:113732:26)
>     at eventLoopTick (ext:core/01_core.js:178:7)
>     at async renderPandoc (file:///C:/[DEDACTED]/Programmes/quarto/bin/quarto.js:115282:24)
>     at async Object.onRender (file:///C:/[DEDACTED]/Programmes/quarto/bin/quarto.js:140305:34)
>     at async renderFileInternal (file:///C:/[DEDACTED]/Programmes/quarto/bin/quarto.js:123952:9)
>     at async renderFiles (file:///C:/[DEDACTED]/Programmes/quarto/bin/quarto.js:123681:9)
>     at async renderProject (file:///C:/[DEDACTED]/Programmes/quarto/bin/quarto.js:124208:23)
> 
> [DEDACTED] MINGW64 /c/[DEDACTED]/gitlab/Guide_Informatique (main)
> $ 
> ```

Even though the file actually exists :

> ```batch
> C:\[DEDACTED]\PROGRAMMES\QUARTO\SHARE\FORMATS\HTML\TEMPLATES
> │   after-body-article-postamble.ejs
> │   after-body-article-preamble.ejs
> │   after-body-custom-postamble.ejs
> │   after-body-custom-preamble.ejs
> │   before-body-article.ejs
> │   before-body-custom.ejs
> │   quarto-html-after-body.ejs
> │   quarto-html-before-body.ejs
> │   title-block.html
> │   title-block.scss
> │   title-metadata.html
> │   _title-meta-author.html          <--- Here !
> │
> ├───banner
> │       title-block.html
> │
> └───manuscript
>         title-block.html
>         title-metadata.html
> ```

However, I remember trying quarto versions `1.7.34`, all the way down to `1.4.4` that did not work; Only the ones equal or before `1.3.450` did work ! I get lost in the commits between `1.3.450` and `1.4.4` that could actualy change the template's paths behaviors though.


I believe this is close to https://github.com/quarto-dev/quarto-cli/discussions/6756 's problem.

**Comment by cderv** [comment]
> C:\[DEDACTED]\Programmes

Do you have any special character in the [DEDACTED] part ? Just to be sure... 


The file is included in your installation correctly. So I wonder what could make this path unreadable. 

Is this only happening with `quarto preview` or also with `quarto render` ? 

BTW I am replying in this thread, but please open a new one with all the useful information, linking to this one and other possible related one. This is always better than commented on closed thread from years ago. Thank you:!

**Comment by odysseu** [comment]
Yes, I have a `!` at the beginning, something like `!MYPATH`. This was done by a IT engineer so we bypass the enterprise security protocols and so we can install stuff in `C:/!MYPATH/`.

And I have exactly the same error for both `quarto preview` and `quarto render`

**Comment by odysseu** [comment]
Any news on that, plz ?
Cheers

**Comment by cderv** [comment]
@odysseu Please do follow our advice. Last time I shared
> BTW I am replying in this thread, but please open a new one with all the useful information, linking to this one and other possible related one. This is always better than commented on closed thread from years ago. Thank you:!

And this is still valid. You are commenting in a closed issue. Please, open a new one sharing the details of your specific environment, and a reproducible example. 

Thank you !
