### ISSUE TITLE
`bread-crumbs` cannot be disable on a specific book page

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8108]
Initially reported by @aborruso on #6183 and #8109

Code: https://github.com/mcanouil/quarto-issues-experiments/tree/main/quarto-cli-8108

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/96ce49e3-0d8f-4ba5-a48f-70c4e5d99bbe">

**Comment by aborruso** [comment]
Hi @mcanouil ,
I have set 

```

**Comment by cscheid** [comment]
We need a minimal reprex instead of a big repo before we can help further.

**Comment by aborruso** [comment]
> We need a minimal reprex instead of a big repo before we can help further.

No @cscheid the problem is that I'm stupid: I have written `breadcrumb` and not `bread-crumbs`.

sorry for the confusion
