### ISSUE TITLE
Replace `&` with `&amp` in URLs to create well-formed XML for the sitemap

### ISSUE THREAD

**Issue by the-solipsist** [quarto-dev/quarto-cli#8132]
### Bug description

I have a file with an ampersand in the filename. 
When generating `sitemap.xml`, the ampersand is retained as `&`, rather than being converted to `&amp`.  
This causes an XML error.

### Quarto check output

```
quarto check
Quarto 1.4.533
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.533
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.11
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/sol/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cderv** [comment]
@dragonstyle maybe we should just use `lodash/escape` when we write the URL in sitemap ? 

https://github.com/quarto-dev/quarto-cli/blob/ae8c854bff30f9c14f224c3314e6d6eee0fea9f1/src/project/types/website/website-sitemap.ts#L164-L173

Or when creating the urlset entry maybe 🤔 

https://github.com/quarto-dev/quarto-cli/blob/ae8c854bff30f9c14f224c3314e6d6eee0fea9f1/src/project/types/website/website-sitemap.ts#L88-L97
