### ISSUE TITLE
[quarto.org] Size issue in gallery thumbnail

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#8135]
Here: https://quarto.org/docs/gallery/

This is 100% zoom so thumbnails are way to big ! 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/680a7397-a70a-414f-aa03-ab5b0ad357c8)

**Comment by dragonstyle** [comment]
This was a Quarto bug, fixed here:

86d7218312a9c05ff4583d30d2b6267799107dad

**Comment by cderv** [comment]
Awesome thanks !
