### ISSUE TITLE
Default type project error on and after v1.4.527

### ISSUE THREAD

**Issue by robolyst** [quarto-dev/quarto-cli#8143]
### Bug description

When running quarto 1.4.527+ and executing `quarto preview` in a hugo project, I get the error:
```
ERROR: The project '' is a default type project. Default Quarto projects don't support project wide previewing since there is no project wide navigation.
```

### Steps to reproduce

Use this `Dockerfile`:
```
FROM python:3.12-slim-bookworm

RUN apt update
RUN apt install -y npm hugo wget git

# WORKS
# ENV VERSION=1.4.526

# DOES NOT WORK
ENV VERSION=1.4.527

# Install quarto
RUN wget -q -O /tmp/quarto.deb https://github.com/quarto-dev/quarto-cli/releases/download/v$VERSION/quarto-$VERSION-linux-arm64.deb \
  && dpkg -i /tmp/quarto.deb

RUN hugo new site quickstart
WORKDIR quickstart

CMD quarto preview --no-browser
```

and build and run with:
```
docker run -ti --rm $(docker build -q .)
```

### Expected behavior

When running with `VERSION=1.4.526` I get the expected output:
```
                   | EN
-------------------+-----
  Pages            |  3
  Paginator pages  |  0
  Non-page files   |  0
  Static files     |  0
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Built in 2 ms
Watching for changes in /quickstart/{archetypes,assets,content,data,layouts,static}
Watching for config changes in /quickstart/config.toml
Browse at http://localhost:6733/
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:6733/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

### Actual behavior

When running with `VERSION=1.4.527` I get:
```
ERROR: The project '' is a default type project. Default Quarto projects don't support project wide previewing since there is no project wide navigation.

Please preview an individual file within this default project instead.

Stack trace:

Please preview an individual file within this default project instead.
    at serveProject (file:///opt/quarto/bin/quarto.js:97235:19)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:97963:9)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8095:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:114673:5)
    at async file:///opt/quarto/bin/quarto.js:114691:9
```

**Comment by mcanouil** [comment]
Could you try the latest pre-release?
Some changes were made regarding this, *i.e.*, as long as there is an "index" file it should work otherwise you have to tell Quarto what is the file you want to preview.

**Comment by robolyst** [comment]
Hey, setting:
```
ENV VERSION=1.4.536
```
produces the same error.

I'm not sure what you mean by "As long as there is an 'index' file it should work". A Hugo project doesn't have an "index" file for the whole project.

**Comment by mcanouil** [comment]
I mean exactly literally what I wrote.

What I don't understand is that you are trying to use Quarto on a hugo project without any Quarto configuration.
What is it you are trying to do here?

See documentation on using Quarto and Hugo at <https://quarto.org/docs/output-formats/hugo.html>.

**Comment by robolyst** [comment]
Thanks for the quick reply.

Here's my situation. I have a large hugo project. That project does have a `_quarto.yml` file in it. I've been running `v1.4.526` with any problems. I'd like to use the latest pre-release to take advantage of a recently merged PR. I tried updating the the latest pre-release `v1.4.536` to upgrade Quarto however I got this error.

Rather than copying in my whole repo I figured I'd make the smallest `Dockerfile` I could that reproduced the error.

My site's repo is at: https://github.com/robolyst/osquant.

Let me know what information would be useful to help debug.

**Comment by mcanouil** [comment]
`quarto preview` behaviour has been changed to only preview index file when there is one for "default" project.
Your example in the Dockerfile is a default project because you did not set any project type.

This being said, it seems there something else at play here, because using the latest development version display the error message which is incorrect.

Thanks for the report.

**Comment by dragonstyle** [comment]
I've made a change to never block previewing with a browser (the real main issue that we were trying to address was preview opening a browser to a non-existent page and helping users understand why). I will start a fresh build with this improvement, I am also considering not erroring but instead issuing a warning...

https://github.com/quarto-dev/quarto-cli/commit/3ef00d58ea2b551cf3a5f3bd1dd807e7ae6dad20
