### ISSUE TITLE
Listing globs will crawl project output directory

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8147]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8122

Here is the repository a bit cleaned up: https://github.com/mcanouil/test_portfolio/tree/chore/example-cleanup

| Render | Preview |
|--------|--------|
| <img width="1061" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/43020703-9afc-4c1d-b55a-10a5ace24d42"> | <img width="1063" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/1afc5906-82cb-4750-aa65-ddeee318eb3f"> |

**Comment by mcanouil** [comment]
Some follow up using `quarto preview --no-browser` does not produce the warning and the issue with the resource being "uploaded" every time.

**Comment by dragonstyle** [comment]
Changing the glob to: `contents: "/portfolio/**/index.qmd"` resolves the issue.

Without the leading `/`, the path matches subfolders in the output directory since our 'smart globbing' automatically does this:

```typescript
  if (!glob.startsWith("/")) {
    if (smartGlob) {
      return "**/" + glob;
    } else {
      return glob;
    }
  } else {
    return glob.slice(1);
  }
```

**Comment by dragonstyle** [comment]
One other thought- we are often protected by this since we default output directories to start with a leading `_`, making them excluded from any of these types of searches. I wonder whether this is another good note for a 'best practices' type doc...

**Comment by dragonstyle** [comment]
And one other note-  I think it would be nice to improve our glob documentation to at least discuss the idea of smart globbing (it is a little complicated, so we'll have to see how easy it is to explain):

https://quarto.org/docs/reference/globs.html

**Comment by mcanouil** [comment]
Why does it only happen when using `quarto preview`?

**Comment by mcanouil** [comment]
> One other thought- we are often protected by this since we default output directories to start with a leading `_`, making them excluded from any of these types of searches. I wonder whether this is another good note for a 'best practices' type doc...

`docs` is the directory used by GitHub Pages when not using the `gh-pages` branch.
Also I tried using `render: "!docs"` but without any luck.

**Comment by dragonstyle** [comment]
> Why does it only happen when using quarto preview and not with quarto preview --no-browser?

It is actually the rendering of `index.qmd` (which contains the listing) in the presence of this `doc` directory state that causes the issue. `no-browser` doesn't open the browser and navigate to `index.html` so the `index.qmd` file isn't rendered again. If you manually open a browser, you'll see the warning.

**Comment by dragonstyle** [comment]
The issue with `!docs` not working is very specific to listings. Listing globs can discover files that are not project inputs (since it could point to all types of files) and the project inputs are the only thing filtered by the render list. So it is very specifically the `listing` glob that is tripping things up here.

I think we could improve listings by having them never crawl project exclude dirs (e.g. output directories), which I think we should do in a future release. I'm going to move this to Quarto 1.5 for us to address.

**Comment by dragonstyle** [comment]
(One other side note -you can also repro this using `quarto render --no-clean` - the second render will cause the warning since the doc dir wasn't cleaned)
