### ISSUE TITLE
quarto-1.4.537-macos.pkg installs disaggregated folders with macOS Sonoma 14.2.1 & Apple M3 Max

### ISSUE THREAD

**Issue by macgarvin** [quarto-dev/quarto-cli#8152]
### Bug description

As described in the title - using the MacOS download on https://quarto.org/docs/get-started/  installer reports successful installation but installs a folder 'quarto' with 'bin' and 'share' folders within? Double checked that it was the macOS install.
Malcolm

### Steps to reproduce

Download from web address on appropriate Mac, install and inspect result

### Expected behavior

A clickable app rather than folders

### Actual behavior

-[quarto-1.4.537-macos.pkg](https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.537/quarto-1.4.537-macos.pkg)
- MacBook Pro, 16-inch Nov 2023, Apple M3 Max
- macOS Sonoma 14.2.1

### Quarto check output

not relevant - see download link for version

**Comment by dragonstyle** [comment]
Quarto is a command line application rather than an application that is launched via finder, so `launching` Quarto would do nothing. Perhaps we could place Quarto in a different location, but this is currently as designed.

**Comment by macgarvin** [comment]
Thank you Charles

I understand now, and 

Perhaps the following account of how this came about could be useful for the authors of the quarto website.

I’m an occasional user of RStudio, and could vaguely remember being able to use python within RStudio, and now need to use these tools again after a break of a couple of years. With this vague memory, looking through the posit website, I falsely thought that quarto was now an IDE equivalent to RStudio, but more orientated towards Python and Jupyter. After seeing and installing with the conventional  Apple pkg installer, I was surprised to see the folder structure in the Applications folder, but went ahead with the Jupyter examples. When the results started displaying (as intended) in Safari browser, that’s when I thought the installation had partially screwed up.

Perhaps a single sentence on the home page with an explicit statement/reminder/ that, among other routes, quarto can be directly with RStudio would help some people!

Malcolm

**Comment by cderv** [comment]
> Perhaps a single sentence on the home page with an explicit statement/reminder/ that, among other routes, quarto can be directly with RStudio would help some people!

In our Get -Started (https://quarto.org/docs/get-started/) page you can easily access from Homepage, we do have RStudio IDE mong obvious choices:
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/1b6adf73-e96f-4523-b7c9-315d01d6cb2e)

In which website do you suggest we had this sentence ? 

> With this vague memory, looking through the posit website, I falsely thought that quarto was now an IDE equivalent to RStudio, but more orientated towards Python and Jupyter.

What was your route for this ? I do believe https://posit.co/ link directly to https://quarto.org when you look in the product menu
