### ISSUE TITLE
Code Reuse article broken

### ISSUE THREAD

**Issue by pastorn** [quarto-dev/quarto-cli#8168]
### Bug description

[This article](https://quarto.org/docs/interactive/ojs/code-reuse.html) is broken. Hopefully it's not me (running latest vivaldi).

![code-reuse-borked](https://github.com/quarto-dev/quarto-cli/assets/712688/3b0db04e-2f96-4132-8e9a-71b3e40e40cc)

### Steps to reproduce

I was looking for a place to put code blocks in the margin. Last week I saw it in *ONE* weird article but I can't for the life of mine find it again. So browsing around in **everything** in the guide, I saw this.

### Expected behavior

Finding the article showing how to put code blocks in the margin.

### Actual behavior

Found an article that seemed broken.

**Comment by cscheid** [comment]
> Hopefully it's not me (running latest vivaldi).

It's not you! That's badly broken and needs fixing. Thank you for letting us know!
