### ISSUE TITLE
Code annotation doesn't gobble "# <num>" markers for non R/python.

### ISSUE THREAD

**Issue by pastorn** [quarto-dev/quarto-cli#8173]
### Bug description

There seems to be an issue with the code annotation syntax being left in the code for anythnig that isn't R/python when PDF is the format (haven't tested HTML).

````markdown
---
format:
    pdf:
      code-annotations: true
      code-block-bg: "#FFFFE8"
---

## Starting with `c`

```c
int main()
{
  printf("Hello, World!\n"); # <1>
  return 0;                  # <2>
}
```
1. Say hello.
2. Leave.


## Starting with `.c`

Note how *some* gobbling is occuring here:

```.c
int main()
{
  printf("Hello, World!\n"); # <1>
  return 0;                  # <2>
}
```
1. Say hello.
2. Leave.

## Starting with `r`

```r
library(tidyverse)
library(palmerpenguins)
penguins |>                                      # <1>
  mutate(                                        # <2>
    bill_ratio = bill_depth_mm / bill_length_mm, # <2>
    bill_area  = bill_depth_mm * bill_length_mm  # <2>
  )                                              # <2>
```
1. Take `penguins`, and then,
2. add new columns for the bill ratio and bill area.
````

![quarto-pdf-code-annotation-bug](https://github.com/quarto-dev/quarto-cli/assets/712688/ba46ad9c-dea7-4ab5-8a00-21a10c0acb58)

**Comment by mcanouil** [comment]
Note that this is not LaTeX specific (happens with all formats as far as I can tell) and this occurs in the latest 1.4 version.

@pastorn Please do provide at least Quarto version when reporting bugs.

**Comment by cscheid** [comment]
You need to use the comment syntax of the language. `# is not C comment syntax.

**Comment by pastorn** [comment]
As mentioned in [this comment](https://github.com/quarto-dev/quarto-cli/issues/8173#issuecomment-1881648187) I was being stupid ;)

Sorry! I was probably too focused on the examples (which all have the same syntax) to notice point 1 [here](https://quarto.org/docs/authoring/code-annotation.html#annotation-syntax) . Perhaps an example with another language (comment syntax) could be added?
