### ISSUE TITLE
Rust syntax highlighting error (for Rust macros).

### ISSUE THREAD

**Issue by pastorn** [quarto-dev/quarto-cli#8209]
Parenthenses inside the macro syntex aren't matching properly. Can be seen in both HTML and PDF.

``````markdown
---
highlight-style: pygments # for visibility
---

```.rs
#[task(
    binds  = TIM4,
    local  = [ ms_timer ],
    shared = [ current_tick ])]
fn milli_irs(
    mut cx: milli_isr::Context) {

    let u = TimerInterrupt::Update
    cx.local.ms_timer.clear_interrupt(u);

    cx.shared.current_tick.lock(
        |tref| { *tref += 1; });

    let ev = Event::TickMillesec;
    main_task::spawn(ev).ok();
}
```
``````

![quarto-rust-syntax-error](https://github.com/quarto-dev/quarto-cli/assets/712688/d6e8e159-6ac2-4371-9bf8-7f0ffadc031d)

On `main` branch: pulled & configured an hour ago.

**Comment by cscheid** [comment]
That's unfortunately not a Quarto bug; we don't do the highlighting ourselves. That comes, I believe, from Pandoc.

**Comment by mcanouil** [comment]
See <https://pandoc.org/chunkedhtml-demo/13-syntax-highlighting.html>.

**Comment by pastorn** [comment]
Closing because there's nothing to be done from here. Used the XML file provided [here](https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/rust.xml) but got the same error. The error also appears in `kate` which relies on the same files.

**Comment by cderv** [comment]
> Used the XML file provided [here](https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/rust.xml?rgh-link-date=2024-01-10T15%3A03%3A57Z) but got the same error. The error also appears in kate which relies on the same files.

This would be to report upstream (https://github.com/KDE/syntax-highlighting/tree/master?tab=readme-ov-file#report-bug-or-help-to-fix-them) so that it could in the future be updated in Pandoc and thus in quarto
