### ISSUE TITLE
Quarto not rendering proper LaTeX code when specifying option `fig-pos` [PDF]

### ISSUE THREAD

**Issue by lbelzile** [quarto-dev/quarto-cli#821]
With the YAML option `fig-pos: 'h'`, the following chunk

```
::: {#fig-somefigure}

![](figures/somefile)

A caption

:::
```
leads to the following invalid LaTeX code which fails to compile due to the nested figure environments.

```
\begin{figure}

{\centering 

\begin{figure}[ht!]

{\centering \includegraphics{./figures/somefile.png}

}

\end{figure}

}

\caption{\label{fig-somefigure}A caption}

\end{figure}

```

This behaviour is inconsistent: I have blocks of code that are exactly the same format and compile just fine. Instances with `knitr::include_graphics()` also work or systematically fail.

Removing `fig-pos` from the YAML file fixes the problem, which suggests it's the likely culprit...

**Comment by jjallaire** [comment]
You are correct that `fig-pos: h` is causing us to create a figure for the inner image (b/c that's the only way to apply that behavioral attribute to an image). Unfortunately we don't currently have a way to "see" nested figures and therefore know to stand down (this is in in principle possible just not accessible given how our filters currently work).

I can think of a couple of options here:

1. Re-write the above as an ordinary figure with a caption: 

```markdown
![A caption](foo.png){#fig-somefigure}
```

2. Implement a rule whereby `fig-pos` is not applied to images that lack a caption. That seems a bit too aggressive to me.

3. Attempt to automatically "fold" the code you showed into option (1). I think this might be a bit too much magic though.

I'm inclined to leave this as guidance to use the more compact form of figures (option 1) when targeting LaTeX.

**Comment by lbelzile** [comment]
The first option works for me. Perhaps adding a note in the documentation about the incompatibility in the [LaTeX figure section](https://quarto.org/docs/authoring/figures.html#latex-figures) would be worthwhile?

There may be need for some magic (there are numerous problems in LaTeX with captions for tables and incorrect output, but I will file other issues for this).

**Comment by jjallaire** [comment]
Okay, thanks. I added a note to that effect here: https://quarto.org/docs/authoring/figures.html#latex-figures

Does that look like appropriate language to you?
