### ISSUE TITLE
Unconsistent behaviour with revealjs background video

### ISSUE THREAD

**Issue by eduardob999** [quarto-dev/quarto-cli#8257]
### Bug description

The background video will play without problems the first time, but when I change the slide and get back to the slide with the video, most of the time it won't play. I'm also attaching the example background video I'm using. Tried changing browsers too, nothing actually helped but refreshing the presentation.

https://github.com/quarto-dev/quarto-cli/assets/47163267/274cef2b-1482-48dc-ac49-c0845c1a23f7

### Steps to reproduce

```qmd
---
title: "Test"
author: "eduardob999"
format: revealjs
---

## Any Slide

## Any other slide

## {background-video="animation.mp4"}

## This is another slide
```

### Expected behavior

It should play seamlessly everytime I switch back into that slide

### Actual behavior

The video doesn't play again when I return to the slide with the video

### Your environment

VSCode 1.85.1, WSL Server, Windows 11

### Quarto check output

```bash
pandoc 
  to: revealjs
  output-file: slides.html
  standalone: true
  wrap: none
  default-image-extension: png
  html-math-method:
    method: mathjax
    url: >-
      https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML-full
  slide-level: 2
  
metadata
  link-citations: true
  width: 1050
  height: 700
  margin: 0.1
  center: false
  navigationMode: linear
  controlsLayout: edges
  controlsTutorial: false
  hash: true
  history: true
  hashOneBasedIndex: false
  fragmentInURL: false
  transition: none
  backgroundTransition: none
  pdfSeparateFragments: false
  lang: en
  auto-stretch: true
  title: Habits
  author: John Doe
  
Output created: slides.html

Watching files for changes
Browse at http://localhost:4875/
```

**Comment by mcanouil** [comment]
I strongly believe this is how Reveal.js works.
Autoplay is activated when going forward in a presentation.
Usually when you go backward in a presentation you don't want things to automatically happen because you are going back to a particular content.

**Comment by eduardob999** [comment]
That makes sense, what's interesting though is that it seems to have some sort of random behaviour, sometimes the background video will play back, and sometimes just won't. Also, clicking over the progress bar right over the postion of the slide with the clip will trigger the animation again. Having some sort of real control of the background video would be nice.

Understood that this is revealjs business though. Thanks for the support, feel free to close the issue.

**Comment by mcanouil** [comment]
If you want "real control" why set the video as background and not as content?

**Comment by eduardob999** [comment]
Overall because of aesthetic reasons.

**Comment by cderv** [comment]
I was curious so I tried. 

If you open browser console you may see this error like me 
````
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
````

Issue is described here: https://developer.chrome.com/blog/play-request-was-interrupted?hl=en

So it seems to be an issue in Revealjs directly in the way they are handling Video when provided as `background-video` (https://revealjs.com/backgrounds/#video-backgrounds)

You can report there the issue maybe.
