### ISSUE TITLE
mermaid figure does not render even after successful chromium install

### ISSUE THREAD

**Issue by pem725** [quarto-dev/quarto-cli#8275]
### Bug description

Setup quarto so it works with everything but when I introduce a simple mermaid figure into a qmd file, I initially got a warning that chromium was not installed.  Installed with the proper (new) command:

quarto install chromium

Success!

Listed as installed with:

quarto tools:

✓] Inspecting tools

Tool         Status         Installed     Latest  
chromium     Up to date     869685        869685  
tinytex      Up to date     v2024.01      v2024.01

so we are good so far.  

Just in case, I restarted R to ensure that quarto was all updated and ready to run some mermaid diagrams.

Well...no.

ERROR: Chrome not found
and later...
No Chrome or Chromium installation was detected.

So, I think quarto is not finding the install of chromium.  Need anything else to help solve this issue?

Quarto rocks.  Thanks all.   

### Steps to reproduce

Inserted this code block into my previously working qmd file:

```{mermaid}
flowchart TB
    A[Introductions] --> B[Course Overview]
    B --> C[Readings] & D[Assignments] & E[Participation] --> F[Learning Objectives]
    F --> G[Personal Responsibilities]
    G --> H[Setup your rigs NOW!]
    H --> I[Probability Theory]
```

### Expected behavior

render the diagram in both html and pdf (as it should).

### Actual behavior

Error and no render output.  Very sad.

### Your environment

RStudio 2023.12.0+369 "Ocean Storm" Release (33206f75bd14d07d84753f965eaa24756eda97b7, 2023-12-17) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.12.0+369 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

### Quarto check output

Quarto 1.4.537
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.537
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/pem725/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /tmp/RtmptvWbbj/rstudio/terminal/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib/R
      LibPaths:
        - /home/pem725/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.
A mermaid snippet is not enough, we need the format, etc.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Comment by mcanouil** [comment]
> Just in case, I restarted R to ensure that quarto was all updated and ready to run some mermaid diagrams.

How do you run Quarto exactly?
Quarto is not like rmarkdown, it does not need R, so restarting R has no effect on Quarto.

**Comment by pem725** [comment]
mcanouil, I run quarto either by the cli or by the Render button - depending upon my mood.  How do you run it?

Oh, R not relevant.  OK.  Fine.  Quarto still not working.  Any suggestions?

**Comment by mcanouil** [comment]
Hard to tell here, since we cannot reproduce.
It might be a bug and/or something in your setup.

Could you create a Git repository with a small complete reproducible example in which you have the error?
It might help.

**Comment by jannismain** [comment]
I have added a project where I reproduce the issue that mermaid diagrams prevent pdf format from being generated:

https://github.com/jannismain/quarto-mermaid-pdf-issue

<details><summary>Output of <code>quarto check</code></summary>
<p>
<pre>
❯ quarto check           
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/mkj/Developer/quarto-mermaid-pdf-issue/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mkj/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.0
      Path: /Users/mkj/.pyenv/versions/3.12.0/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /opt/homebrew/Cellar/r/4.3.2/lib/R
      LibPaths:
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.2/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
</pre>
</p>
</details> 

<details><summary>My Environment</summary>
<p>
- MacBook Pro with M1 Max CPU running macOS Sonoma 14.2.1
- `quarto-cli` installed from `main` branch

I have observed the same issue inside a `python:bookworm` container, where I installed quarto-cli.
</p>
</details>

**Comment by cderv** [comment]
What is the error you get exactly ? It seems from your quarto check that you have indeed chromium installed, so it should find it.

FWIW I can't reproduce on my side but I am on Windows. 

> I have observed the same issue inside a python:bookworm container, where I installed quarto-cli.

Is this something that woud allow us to reproduce easily ?

**Comment by jannismain** [comment]
> What is the error you get exactly ? It seems from your quarto check that you have indeed chromium installed, so it should find it.
> 
> FWIW I can't reproduce on my side but I am on Windows.
> 
> > I have observed the same issue inside a python:bookworm container, where I installed quarto-cli.
> 
> Is this something that woud allow us to reproduce easily ? Don't know what `python:bookworm` container. Is it docker ?

I since tried it on a completely new machine and the error no longer occurs. I'm getting a chromium crash notification, but the PDF builds fine.

![CleanShot 2024-01-31 at 09 40 20@2x](https://github.com/quarto-dev/quarto-cli/assets/14290527/f26a79e7-4c8f-4bbd-b9fe-e329097cb918)

So I guess it was related to my setup after all.

The error I had previously was that `quarto render` simply runs forever without any output or error.
[`python:bookworm` is indeed a docker container from hub.docker.com](https://hub.docker.com/_/python).
