### ISSUE TITLE
GitLab CI error: Permission denied (os error 13): mkdir '/var/cache/quarto'

### ISSUE THREAD

**Issue by nhoffman** [quarto-dev/quarto-cli#8278]
### Bug description

I'm attempting to render and deploy a static site to a self-hosted GitLab instance using GitLab pages. I'm using an image provided from quarto-forge using CI configuration suggested there (https://gitlab.com/quarto-forge/docker):

```yaml
image: registry.gitlab.com/quarto-forge/docker/python:latest

pages:
  script:
    - quarto render --execute --to html --output-dir public
  artifacts:
    paths:
      - public
```

The CI task fails with the following error:

```
Running with gitlab-runner 16.6.0 (3046fee8)
  on gitlab-runner-spawner hVAK5X3Y, system ID: s_e0b34fb943a3

Preparing the "docker+machine" executor
00:01
Using Docker executor with image registry.gitlab.com/quarto-forge/docker/python ...
Pulling docker image registry.gitlab.com/quarto-forge/docker/python ...
Using docker image sha256:ea7861bd994f050d1194ba2e52194c3efb10de74e199e4b7d7a7c05529db6cb4 for registry.gitlab.com/quarto-forge/docker/python with digest registry.gitlab.com/quarto-forge/docker/python@sha256:9a94d45a6f3ec4688a543de3f1418693be9b9bf8d85f36571edac728b1114a44 ...

Preparing environment
00:01
Running on runner-hvak5x3y-project-844-concurrent-0 via runner-hvak5x3y-gitlab-runner-spawner-1705334399-7ffc9df7...

Getting source from Git repository
00:00
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/hVAK5X3Y/0/uwlabmed/dlmpy/.git/
Checking out 52b40c98 as detached HEAD (ref is main)...
Skipping Git submodules setup

Executing "step_script" stage of the job script
00:01
Using docker image sha256:ea7861bd994f050d1194ba2e52194c3efb10de74e199e4b7d7a7c05529db6cb4 for registry.gitlab.com/quarto-forge/docker/python with digest registry.gitlab.com/quarto-forge/docker/python@sha256:9a94d45a6f3ec4688a543de3f1418693be9b9bf8d85f36571edac728b1114a44 ...
$ quarto render --execute --to html --no-cache --output-dir public
error: Uncaught PermissionDenied: Permission denied (os error 13): mkdir '/var/cache/quarto'
        Deno.mkdirSync(dir, {
             ^
    at Object.mkdirSync (ext:deno_fs/30_fs.js:132:7)
    at ensureDirSync (file:///opt/quarto/bin/quarto.js:9279:14)
    at quartoDir (file:///opt/quarto/bin/quarto.js:32903:5)
    at quartoCacheDir (file:///opt/quarto/bin/quarto.js:32895:12)
    at file:///opt/quarto/bin/quarto.js:39365:25

Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

### Steps to reproduce

Fails with any document

### Expected behavior

Static site published to GitLab pages

### Actual behavior

CI job fails with error in description

### Your environment

Hopefully the relevant version information in provided in the configuration and traceback. If not, happy to provide more information.

### Quarto check output

not applicable

**Comment by mcanouil** [comment]
You need to test locally the Docker image you are using and get back to the author/maintainer of that image.

**Comment by cscheid** [comment]
```
error: Uncaught PermissionDenied: Permission denied (os error 13): mkdir '/var/cache/quarto'
        Deno.mkdirSync(dir, {
             ^
    at Object.mkdirSync (ext:deno_fs/30_fs.js:132:7)
    at ensureDirSync (file:///opt/quarto/bin/quarto.js:9279:14)
    at quartoDir (file:///opt/quarto/bin/quarto.js:32903:5)
    at quartoCacheDir (file:///opt/quarto/bin/quarto.js:32895:12)
```

`quartoCacheDir` eventually calls `userCacheDir`:

```ts
export function userCacheDir(appName: string) {
  switch (Deno.build.os) {
    case "darwin":
      return darwinUserCacheDir(appName);
    case "windows":
      return windowsUserDataDir(appName);
    default: // assume generic unix
      // in 1.32.5 this is:
      // case "linux":
      // case "netbsd":
      // case "aix":
      // case "solaris":
      // case "illumos":
      // case "freebsd":
      return xdgUserCacheDir(appName);
  }
}
```

`xdgUserCacheDir` uses `XDG_RUNTIME_DIR`. The [spec says](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

> There is a single base directory relative to which user-specific runtime files and other file objects should be placed. This directory is defined by the environment variable $XDG_RUNTIME_DIR.

Although the spec doesn't explicitly state that the directory should be user-writable, I don't understand how it could possibly work without that being the case. So I don't think this is a Quarto bug.

**Comment by mcanouil** [comment]
CC @rgaiacs

**Comment by nhoffman** [comment]
Thanks a lot for the quick response - apologies, I assumed that quarto-forge (https://gitlab.com/quarto-forge/docker) was  officially supported by the quarto project, and most google searches for issues that seemed vaguely related led here. Agreed that this seems to be an issue related to the configuration of that docker image. I'll raise an issue there.

**Comment by rgaiacs** [comment]
@nhoffman I created the Docker images that you are using. Declare the `$XDG_CACHE_HOME` might be missing.

**Comment by nhoffman** [comment]
Hi @rgaiacs - thanks for the response - I raised an issue (with follow up questions) in your repo:

https://gitlab.com/quarto-forge/docker/-/issues/3
