### ISSUE TITLE
labeling equation in `\begin{align}`

### ISSUE THREAD

**Issue by mghassany** [quarto-dev/quarto-cli#828]
Hello,
I am migrating from bookdown to quarto book and I have used a lot of `\begin{equation}` and sometimes `\begin{align}`. 
I get how to label the equations starting by `$$` from the [documentation](https://quarto.org/docs/authoring/cross-references.html#equations). But it doesn't work when I add the label after `\end{equation}` or `\end{align}`. 
It is ok when I replace `\begin{equation}` by `$$` but I doesn't work for `\begin{align}`.
Is there a way or a fix for this ? 
Thanks

**Comment by mghassany** [comment]
ps, was working fine in bookdown, like explained [here](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations) by Yihui.

**Comment by jjallaire** [comment]
Does it work to put the `\begin{align}` within the `$$` ?

**Comment by mghassany** [comment]
No I already tried and it doesn't work. the `$$` appear in the html output with the label.
![image](https://user-images.githubusercontent.com/11962615/167271216-e6a043e8-fde4-4aa1-b2b7-51920c8d5289.png)

**Comment by jjallaire** [comment]
I tried the `\begin{align}` within the `$$` and got this:

<img width="1176" alt="Screen Shot 2022-05-08 at 6 17 12 AM" src="https://user-images.githubusercontent.com/104391/167291743-53d97417-0f02-4d20-aa20-0040451fe0ec.png">

**Comment by mghassany** [comment]
That is indeed weird. Here is a screen capture :

![](https://user-images.githubusercontent.com/11962615/167303011-bbaf2040-123c-4b50-8b30-1fff25c
Ps, I'm using version 0.9.368

**Comment by jjallaire** [comment]
Could you provide the source of the qmd file as a minimal reproducible example (i.e. https://en.wikipedia.org/wiki/Minimal_reproducible_example)

**Comment by mghassany** [comment]
@jjallaire, Thanks for your replies. I was editing a reprex and weirdly it worked. So I investigated the whole text, part by part and discovered that a previous equation is causing the error because it was like this:
```
$$p(x)= \sum_{k=1}^{K} \pi_k \mathcal{N}(x| \mu_k, \Sigma_k)$${#eq-gaussian}
```
and when I modified it to 
```
$$p(x)= \sum_{k=1}^{K} \pi_k \mathcal{N}(x| \mu_k, \Sigma_k)
$${#eq-gaussian}
```
I had no more the warning, and the label appears (not beside the equation but at least appears):

<img width="648" alt="image" src="https://user-images.githubusercontent.com/11962615/167308727-19a95464-566b-4856-83b9-842f2815dcb8.png">

By the way, it would be nicer if the equation number appears at the right of the equation in the same place for all the equations, like in bookdown. Here is a comparison:

In quarto:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/11962615/167308864-46bd47d0-af8e-472e-99e4-1898b9c8a501.png">

In bookdown: 
<img width="529" alt="image" src="https://user-images.githubusercontent.com/11962615/167308879-f2e4daf8-7598-4650-b3a5-f97bbd144adb.png">

Also, the equation number in my equation above (using `align`) is appearing correctly beside the equation in bookdown. 

Thanks again :)

**Comment by jjallaire** [comment]
Good catch re: the alignment of the numbers! That is resolved here: https://github.com/quarto-dev/quarto-cli/commit/58aa6143fcfecdb65382f55b905ab799677991cf

**Comment by mghassany** [comment]
Thank you @jjallaire. I will close the issue if you don't mind.

**Comment by jjallaire** [comment]
Could you post exactly the code you are using?

**Comment by ratnanil** [comment]
> was editing a reprex and weirdly it worked. So I investigated the whole text, part by part and > discovered that a previous equation is causing the error because it was like this:
> ```
> $$p(x)= \sum_{k=1}^{K} \pi_k \mathcal{N}(x| \mu_k, \Sigma_k)$${#eq-gaussian}
> ```
> and when I modified it to 
> ```
> $$p(x)= \sum_{k=1}^{K} \pi_k \mathcal{N}(x| \mu_k, \Sigma_k)
> $${#eq-gaussian}
> ```
> I had no more the warning


Thank you so much for catching and posting this, I would *never* have found the culprit!
