### ISSUE TITLE
Consider render Math with Mathjax in GFM HTML preview

### ISSUE THREAD

**Issue by aravezskinteeth** [quarto-dev/quarto-cli#8283]
### Bug description

I'm trying to render a `.qmd` file to github flavored markdown, however all the equations that are using `\frac{}{}` are not getting rendered. Which is weird because the equations do get rendered in visual mode and the source code, but not on my web browser.

I tried a workaround that I found on the [docs](https://quarto.org/docs/output-formats/gfm.html), which is to convert all the equations to `html-math-method: webtex`. 

````qmd
---
title: Some title
format:
  gfm:
    html-math-method: webtex
---
````

This renders all the equations but they aren't centered and in paragraphs, inline math looks a bit messy. 

### Steps to reproduce

````qmd
---
title: Some title
format: gfm
---

$$H_{0}:\:\mu_{1}-\mu_{2}=0$$         
$$H_{1}:\:\mu_{1}-\mu_{2}\neq0$$

$$d=\frac{\mu_{1}-\mu_{2}}{\sigma}$$

$$\sigma=\sqrt{\frac{\sigma_{1}^{2}+\sigma_{2}^{2}}{2}}$$

Sin embargo, si ambos grupos tienen grandes diferencias de tamaño, $n_{1}\neq n_{2}$, entonces se usa la desviación estándar entre cada grupo (*pooled standard deviation*) en lugar de $\sigma$.
````

### Expected behavior

I expected to get all the formulas rendered in the `localhost` instance on my browser (Firefox 121.0.1).

### Actual behavior

This is what happens if I don't use the `html-math-method: webtex` rendering method:

<img width="709" alt="Screenshot 2024-01-14 at 21 22 48" src="https://github.com/quarto-dev/quarto-cli/assets/104392087/833ee517-0bd9-47a3-a068-407d79f73177">

I was considering that maybe the web environment that I'm publishing into doesn’t support dollar-delimited math, however if that were the case, none of the equations would get rendered.

### Your environment

- IDE: RStudio 2023.12.0+369
- OS: MacOS Sonoma 14.2.1

### Quarto check output

```bash
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /Users/skinofmyeden/miniconda3/bin/python
      Jupyter: 5.3.0
      Kernels: ir, julia-1.9, python3

(/) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
I'm not sure I follow: `gfm` is a _markdown_ output; what do you mean by this?

> I expected to get all the formulas rendered in the localhost instance on my browser (Firefox 121.0.1).

**Comment by mcanouil** [comment]
The code shared produce the following:
```md
# Some title


$$H_{0}:\:\mu_{1}-\mu_{2}=0$$  
$$H_{1}:\:\mu_{1}-\mu_{2}\neq0$$

$$d=\frac{\mu_{1}-\mu_{2}}{\sigma}$$

$$\sigma=\sqrt{\frac{\sigma_{1}^{2}+\sigma_{2}^{2}}{2}}$$

Sin embargo, si ambos grupos tienen grandes diferencias de tamaño,
$n_{1}\neq n_{2}$, entonces se usa la desviación estándar entre cada
grupo (*pooled standard deviation*) en lugar de $\sigma$.
```

Which on GitHub produces:

# Some title


$$H_{0}:\:\mu_{1}-\mu_{2}=0$$  
$$H_{1}:\:\mu_{1}-\mu_{2}\neq0$$

$$d=\frac{\mu_{1}-\mu_{2}}{\sigma}$$

$$\sigma=\sqrt{\frac{\sigma_{1}^{2}+\sigma_{2}^{2}}{2}}$$

Sin embargo, si ambos grupos tienen grandes diferencias de tamaño,
$n_{1}\neq n_{2}$, entonces se usa la desviación estándar entre cada
grupo (*pooled standard deviation*) en lugar de $\sigma$.


---

There are no issue with the code produced.

Now, maybe you are talking about the HTML preview of the markdown produced in your IDE.
In this case, the web browser used might not have the same Math JavaScript library which is independent of Quarto.

Note that markdown is a flat tex file, so there is no math formatting in it.
This is all done by the website (and your browser) hosting the markdown file.
For instance, GitHub uses MathJax to format LaTeX math equation: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

I am going ahead and close this as there is no bug here on Quarto side.

**Comment by cderv** [comment]
> Now, maybe you are talking about the HTML preview of the markdown produced in your IDE.
In this case, the web browser used might not have the same Math JavaScript library which is independent of Quarto.

@mcanouil Quarto is rendering to HTML for a GFM preview when `quarto preview` is used. 
https://github.com/quarto-dev/quarto-cli/blob/6821f7197aff2b18132e3d1de8720ddaf7599ec9/src/preview/preview-text.ts#L78-L81

In this HTML we build with `gfmPreview()`, we correctly have `$math$` in the template used
https://github.com/quarto-dev/quarto-cli/blob/6821f7197aff2b18132e3d1de8720ddaf7599ec9/src/resources/formats/gfm/template.html#L30-L32

but we don't pass any math flag
https://github.com/quarto-dev/quarto-cli/blob/6821f7197aff2b18132e3d1de8720ddaf7599ec9/src/preview/preview-text.ts#L226-L242

So there is only plain math rendering in the HTML produced - which is why `\frac` is not rendered: Pandoc's does not convert this command to anything with default plain math (https://pandoc.org/MANUAL.html#math-rendering-in-html)

As Github now renders Math using Mathjax (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions), it would make sense to add the rendering of Math expression in HTML Preview for gfm too IMO.

**Comment by mcanouil** [comment]
> As Github now renders Math using Mathjax (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions), it would make sense to add the rendering of Math expression in HTML Preview for gfm too IMO.

Indeed.
In this case, it would also means that the HTML preview of GFM should not account for `html-math-method` since GitHub only uses MathJax, and kind of hardcode the default MathJax method.

**Comment by cderv** [comment]
> In this case, it would also means that the HTML preview of GFM should not account for html-math-method since GitHub only uses MathJax, and kind of hardcode the default MathJax method.

Not sure I follow. Sorry;

the HTML preview does not account for anything from the user. Quarto itself is calling Pandoc to create the preview HTML, and we pass flags directly to pandoc CLI. So there is no question of `html-math-method` for the HTML preview, or did I miss something ¿

**Comment by mcanouil** [comment]
> Quarto itself is calling Pandoc to create the preview HTML, and we pass flags directly to pandoc CLI

That's the thing I did not know. If the preview for GFM is independent, that's perfect.

**Comment by aravezskinteeth** [comment]
> I'm not sure I follow: `gfm` is a _markdown_ output; what do you mean by this?
> 
> > I expected to get all the formulas rendered in the localhost instance on my browser (Firefox 121.0.1).

The HTML preview that opens on my browser when I click the render button.
