### ISSUE TITLE
Quarto render deletes PDF image assets

### ISSUE THREAD

**Issue by sapphire008** [quarto-dev/quarto-cli#8299]
### Bug description

Hi, I have an asset folder that stores svg and pdf version of the same image. My document references the svg version. When I run quarto render, the pdf version of the images are deleted. I have tested that if I convert the image to eps version or other image formats, these other variants do not get deleted by quarto render. I have tried with the --no-clean flag as well, but these images still got deleted. So my question is how can I keep the pdf version of my images around?

Here is a simple repository to illustrate the issue I am facing: https://github.com/sapphire008/quarto-pdf-deletion

Running `quarto render` deletes the file `assets/sliding-moving-average.pdf`.

Linking original question asked: https://github.com/quarto-dev/quarto-cli/discussions/8297

### Steps to reproduce

Checkout the repository `https://github.com/sapphire008/quarto-pdf-deletion.git` and run `quarto render`.

### Expected behavior

I would expect the pdf files are being kept around.

### Actual behavior

The pdf asset file is being deleted

### Your environment

MacOs 14.1.1. Quarto 1.3.450

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.10 (Conda)
      Path: /Users/edward/opt/miniforge3/bin/python
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment]
Thank you! What's happening is exactly what I suspected: our pdf-images filter sees the document, sees an `svg` image, and wants to be helpful, so it converts the `svg` to `pdf`, but then deletes it because it thinks that this was an auto-generated file.

I think we need an option to disable this filter.
