### ISSUE TITLE
1.4 Changelog Updates: Giscus light/dark themes

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#8306]
Moved from [#7906 ](https://github.com/quarto-dev/quarto-cli/issues/7906)

- [ ] ([#4820](https://github.com/quarto-dev/quarto-cli/issues/4820)): Add support for setting the Giscus light/dark themes.

**Comment by cderv** [comment]
it seems for the commenting section we are keeping things short: https://quarto.org/docs/output-formats/html-basics.html#commenting
> Review the [Giscus documentation](https://giscus.app/) for instructions on setting up Giscus in your repository. Additional options are [covered here](https://quarto.org/docs/reference/projects/websites.html#giscus).

Currently, the reference documentation should already cover the new options through the schema 
https://github.com/quarto-dev/quarto-cli/blob/d58718087d3ac38b876d4ce882007bf81b3ec9b8/src/resources/schema/definitions.yml#L269-L294

However, the description could be improved with details about the possible values. 

So, should we document this new light/dark theme as part of the schema long description? 
Or do we want to add more to https://quarto.org/docs/output-formats/html-basics.html#commenting? 

Or even mention this elsewhere in themes (maybe a link, at least in that case ?)

I can definitely work on this, but needed do discuss this before doing a PR. Thanks

**Comment by cwickham** [comment]
Since we don't talk about `theme` on <https://quarto.org/docs/output-formats/html-basics.html#commenting>, I think the changes should be to the Reference page. 

The reference page generation script doesn't reveal parts of the schema below the top-level options, so I think editing the long description is the best option here.
