### ISSUE TITLE
Metadata includes do not work within profile-specific config files

### ISSUE THREAD

**Issue by nickvigilante** [quarto-dev/quarto-cli#8323]
### Bug description

I tried combining both [metadata includes](https://quarto.org/docs/projects/quarto-projects.html#metadata-includes) and [project-specific configuration](https://quarto.org/docs/projects/profiles.html#profile-configuration) together, but it seems as though metadata includes only apply to the main `_quarto.yml` file.

### Steps to reproduce

1. Run the following:
 
```bash
quarto create project website config-include-profile-bug
cd config-include-profile-bug
touch _quarto-production.yml
touch _navbar-production.yml
```

2. Insert the following into both `_quarto-production.yml ` and `_navbar-production.yml`:

```yaml
website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
```

3. Remove lines 6 through 10 from `_quarto.yml`:

```yaml
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
```

4. Run the following commands:

```bash
quarto preview --profile production
```

You should see links for "Home" and "About" in the navbar.

5. Replace `_quarto-production.yml` with the following:

```yaml
metadata-files:
  - _navbar-production.yml
```

Expected: the navbar should still be displayed.
Observed: no navbar is displayed.

### Expected behavior

The navbar should be displayed.

### Actual behavior

No navbar is displayed.

### Your environment

- OS: macOS Sonoma 14.2.1

### Quarto check output

```bash
(base) ➜  config-include-profile-bug quarto check
Quarto 1.4.537
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.537
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12 (Conda)
      Path: /Users/nickv/miniforge3/bin/python
      Jupyter: 5.5.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")

(base) ➜  config-include-profile-bug 
```

**Comment by mcanouil** [comment]
Thanks for the report.

Would you mind sharing a Git repository with the setup to reproduce the issue?
It's way easier, faster, and reliable than copy/pasting.

**Comment by nickvigilante** [comment]
This is the repo I used: https://github.com/nickvigilante/quarto-issue-8323

**Comment by mcanouil** [comment]
Seems related to if not the same:
- https://github.com/quarto-dev/quarto-cli/issues/6859

**Comment by dragonstyle** [comment]
Indeed this is the same issue. I'm going to close this in favor of the older bug, but we appreciate the clear reproducible case you provide in this issue (which will be linked from the older one). Thank you!
