### ISSUE TITLE
Table of contents is not created under DOCX output

### ISSUE THREAD

**Issue by acebulsk** [quarto-dev/quarto-cli#8330]
### Bug description

Table of contents does no appear as expected in DOCX output. Using the same quarto file a toc is output for pdf and html.

### Steps to reproduce

```
---
title: "My Document"
format:
  # pdf:
  #   toc: true
  #   number-sections: true
  # html:
  #   toc: true
  #   number-sections: true
  docx:
    toc: true
    number-sections: true
---

# test

sfdsgdfg 

## test123

dfgsdfgs

# test1234

dfgsdfgsd
```

### Expected behavior

Toc should be rendered in the output .docx

### Actual behavior

The title of the table of contents is rendered but it is not populated. 

### Your environment

- IDE:  rstudio/2023.06.1+524
- OS: Ubuntu 22.04.3 LTS

### Quarto check output

b
ash quarto check
Quarto 1.4.533
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.533
      Path: /opt/quarto/bin

(|) Checking tools...........[✓] Checking tools....................OK
      TinyTeX: v2023.06
      Chromium: (not installed)

(|) Checking LaTeX...........(/) Checking LaTeX...........[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/alex/.TinyTeX/bin/x86_64-linux
      Version: 2023

(|) Checking basic markdown r(/) Checking basic markdown r(-) Checking basic markdown r(\) Checking basic markdown r(|) Checking basic markdown r(/) Checking basic markdown r[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.1.4
      Kernels: python3

(|) Checking Jupyter engine r(/) Checking Jupyter engine r(-) Checking Jupyter engine r(\) Checking Jupyter engine r(|) Checking Jupyter engine r(/) Checking Jupyter engine r(-) Checking Jupyter engine r(\) Checking Jupyter engine r(|) Checking Jupyter engine r(/) Checking Jupyter engine r(-) Checking Jupyter engine r(\) Checking Jupyter engine r(|) Checking Jupyter engine r(/) Checking Jupyter engine r(-) Checking Jupyter engine r(\) Checking Jupyter engine r(|) Checking Jupyter engine r(/) Checking Jupyter engine r(-) Checking Jupyter engine r(\) Checking Jupyter engine r(|) Checking Jupyter engine r(/) Checking Jupyter engine r(-) Checking Jupyter engine r(\) Checking Jupyter engine r(|) Checking Jupyter engine r[✓] Checking Jupyter engine render....OK

(|) Checking R installation..(/) Checking R installation..[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib/R
      LibPaths:
        - /home/alex/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.23

(|) Checking Knitr engine ren               (/) Checking Knitr engine ren              (-) Checking Knitr engine ren               (\) Checking Knitr engine ren               (|) Checking Knitr engine ren               (/) Checking Knitr engine ren               (-) Checking Knitr engine ren            (\) Checking Knitr engine ren               (|) Checking Knitr engine ren               [✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
@acebulsk Could you properly format your post using markdown code blocks for your code? Thank you.

**Comment by cderv** [comment]
Here is a simple document for word 

````markdown
---
title: "Minimal example"
format: 
  docx:
    toc: true
    number-sections: true
---

# Title 1

## Subsection

Content

## Subsection 2

Content

# Part 2

## Another subsection

Content
````

it renders correctly a TOC

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/ee741d36-7843-4dec-983a-597424dee988)


I am using Quarto 1.4

**Comment by dragonstyle** [comment]
When including a TOC in a word document, the reader will see a prompt regarding field update. 

![Screenshot 2024-01-18 at 9 13 18 AM](https://github.com/quarto-dev/quarto-cli/assets/261654/680a998d-71be-4281-bbb8-d229533ab94d)

This is because the TOC needs to be generated with page numbers (which are generated when the document is opened). Selecting `yes` for me shows a proper TOC, selecting `no` doesn't populate TOC contents since the TOC fields are not allowed to be updated.

Open the document, accepting the prompt, and making any change and then saving the document (or saving a copy to another file name) will remove the need for this prompt as the TOC field will be saved.

**Comment by acebulsk** [comment]
> When including a TOC in a word document, the reader will see a prompt regarding field update.
> 
> ![Screenshot 2024-01-18 at 9 13 18 AM](https://private-user-images.githubusercontent.com/261654/297768582-680a998d-71be-4281-bbb8-d229533ab94d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTQ0NDgsIm5iZiI6MTcwNTU5NDE0OCwicGF0aCI6Ii8yNjE2NTQvMjk3NzY4NTgyLTY4MGE5OThkLTcxYmUtNDI4MS1iYmI4LWQyMjk1MzNhYjk0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxNjA5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzdjZmVjNDI1ZDQzZjIxZWNlNjYxMDE3YmM1YzkyM2VlNTU0NzZmNTA2OTFlNGI4NWU0NzU0OWRlNzk0MmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FJMW-ukPK4IBVDP52blllcv3Mp-MFJeSfbSOqjSfbOE)
> 
> This is because the TOC needs to be generated with page numbers (which are generated when the document is opened). Selecting `yes` for me shows a proper TOC, selecting `no` doesn't populate TOC contents since the TOC fields are not allowed to be updated.
> 
> Open the document, accepting the prompt, and making any change and then saving the document (or saving a copy to another file name) will remove the need for this prompt as the TOC field will be saved.

Okay good to know this works on microsoft word. I am on Linux and do not see this pop up on Libre Office Writer. However, if I right-click the TOC title and left-click `Update Index` the TOC is inserted.

**Comment by cderv** [comment]
All good then. Thanks for confirming !
