### ISSUE TITLE
Error with chromote R package when trying to render HTML like mermaid or ploty in PDF format

### ISSUE THREAD

**Issue by Patrikios** [quarto-dev/quarto-cli#8341]
### Bug description

```
==> quarto preview test.qmd --to pdf --no-watch-inputs --no-browse

- The project is out-of-sync -- use `renv::status()` for details.


processing file: test.rmarkdown
  |...       |  32% [Ursprung]                                                                    
Quitting from lines 653-704 [Ursprung] (test.rmarkdown)
Error in `startup()`:
! Chrome debugging port not open after 10 seconds.
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 34. Chrome$new()
 35. chromote (local) initialize(...)
 36. chromote:::launch_chrome(path, args)
 37. chromote:::with_random_port(...)
 42. chromote (local) startup(port = port, ...)
                                                                                                                                                                         
Ausführung angehalten

Unable to locate an installed version of R.
Install R from https://cloud.r-project.org/
```

### Expected behavior

webshot and webdhor 2 is installed
quarto install chromium run Okay,
Seperate google-chrome-stable_current_amd64.deb installed.
I am on debian 10, R 4.3.2 quarto version CLI 1.4.454

**Comment by mcanouil** [comment]
Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Comment by cderv** [comment]
Just some context. 

When using some Plotly HTML output inside a document that will render to PDF, **knitr** will try to make a screenshot of the plotly graph using **webshot** or **webshot2** (preferring **websho2** as default if both are present). 

From the error message I see, **webshot2** is used, and for some reason it does not manage to connect to Chrome (it uses **chromote** for this) and so unable  to make the screenshot. 

This is a R issue - you should check that **webshot2** is working on your environment. 

I see you are using **renv** so you should check the version and see if updating would help.

**Comment by Patrikios** [comment]
That would explain it @cderv as the linux 10 is a gui-less server, hence no virtual chorme windows can be opened, if that is how it works??

**Comment by cderv** [comment]
**chromote** is a tool to communicate with chrome headless. So no need to open a visual within a browser window. 

You can maybe try **chromote** directly to see if **webshot2** would work on your environment See its doc at https://rstudio.github.io/chromote/

**Comment by Patrikios** [comment]
I think it has something to do with the proxy setting on the server.

**Comment by jannismain** [comment]
Find a minimal reproduction here: https://github.com/jannismain/quarto-mermaid-pdf-issue

**Comment by jannismain** [comment]
@cderv thanks for checking out the example I provided. From the title of this issue, I thought they were related, but I will find a better place to discuss the issue I am experiencing :+1:

**Comment by cderv** [comment]
> From the title of this issue, I thought they were related, 

yeah I guess it right. That is why I tweaked the title of this issue
