### ISSUE TITLE
Do code annotations work for Rust ?

### ISSUE THREAD

**Issue by younes-io** [quarto-dev/quarto-cli#8348]
### Bug description

I have this code in my quarto blogpost:

![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/e3c9d86b-d11f-4f4f-a828-8eccc4f4b3f2)

And it renders this:

![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/d6dba2e3-6456-4d05-ab39-0280e45177b6)

I followed [these steps](https://quarto.org/docs/authoring/code-annotation.html#annotation-syntax) but it doesn't work. Am I missing something ?

### Expected behavior

I should have code annotations just as it works for R

### Your environment

- Windows 11

```
$ quarto --version
1.3.450
```

### Quarto check output

```
$ quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: C:/Python312/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

      There is a requirements.txt file in this directory. Is this for a venv that you need to restore?

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/youne/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

```

**Comment by younes-io** [comment]
Doesn't work neither with `code-annotations: none` not `code-annotations: false`

**Comment by mcanouil** [comment]
Please share code not screenshots of code which can't be used or read by screenreaders.

Under 1.4 I have no issues:

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr>
<td>

````qmd
---
title: "Quarto Playground"
format: html
code-annotations: hover
---

This is a playground for Quarto.

```rust
fn main() {
  println!("Hello, world!"); // <1> 
}
```
1. This is a comment
````

</td>
<td>
<img width="690" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/f65025cf-c452-4719-a3b8-12488f7182c3">
</td>
</tr>
</table>

**Comment by younes-io** [comment]
@mcanouil 

1. I did a screenshot because when I pasted the Rust code, it wasn't interpreted well by the Github markdown.. I don't know which feature you use to have this table..

This is what happens:

```

---
code-annotations: hover
---

```rust
fn main() {
    let s = String::from("hello");              // <1>
}

```
1. something...

```


2. I upgraded to Quarto 1.4.545 and it does work now, but at the expense of breaking the frontend.. Many CSS classes have no effect any more and a new bar called "Render" appears with a field..
Also I noticed this weird warning all over my logs.. I think if I manage to fix this lua warning, maybe the frontend could get back to "normal"

WARNING (C:/Users/...../AppData/Local/Programs/Quarto/share/filters/main.lua:18351) Shortcode 'fa' not found

**Comment by mcanouil** [comment]
> I did a screenshot because when I pasted the Rust code, it wasn't interpreted well by the Github markdown.. 

It's regular markdown as you would use inside Quarto or elsewhere.
You need extra backticks to enclose code with backticks.

> I don't know which feature you use to have this table.

You don't need the table, simply use markdown properly to share code.

> I upgraded to Quarto 1.4.545 and it does work now, but at the expense of breaking the frontend.. Many CSS classes have no effect any more and a new bar called "Render" appears with a field..
Also I noticed this weird warning all over my logs.. I think if I manage to fix this lua warning, maybe the frontend could get back to "normal"
WARNING (C:/Users/...../AppData/Local/Programs/Quarto/share/filters/main.lua:18351) Shortcode 'fa' not found

This has nothing to do with the code you shared.
It's really important you share the code/setup needed to reproduce.
We cannot help you if you don't provide all the information (properly formatted).

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````
