### ISSUE TITLE
Render popup appears after upgrade to  Quarto 1.4.545

### ISSUE THREAD

**Issue by younes-io** [quarto-dev/quarto-cli#8350]
### Bug description

I upgraded to Quarto 1.4.545 and I noticed two things:

1. this popup starts to appear when I click on a link of the navbar:

![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/7fd7922c-fe06-4799-a85e-c709213475e9)

2. This warning appears in the logs: **SOLVED** (installing `font-awesome` extension)
`WARNING (C:/Users/youne/AppData/Local/Programs/Quarto/share/filters/main.lua:18351) Shortcode 'fa' not found` 

This obviously breaks the HTML as now my footer looks like this:

![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/0a67f246-d56e-4cce-8b5d-f4e0ab3b4d48)

The footer code in `_quarto.yaml` :

````qml
 
  page-footer:  
    left: >-
     &#169; 2023 - {{YEAR}} | &#8729; Built with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="https://github.com/some_user" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
    
````

### Steps to reproduce

Upgrade to Quarto 1.4.545

### Your environment

- Windows 11
- Quarto 1.4.545

### Quarto check output

```
$ quarto check
Quarto 1.4.545
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.545
      Path: C:\Users\some_user\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\some_user\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: C:/Python312/python.exe
      Jupyter: 5.5.1
      Kernels: python3

(/) Checking Jupyter engine render....Could not find platform independent libraries <prefix>
(-) Checking Jupyter engine render....Could not find platform independent libraries <prefix>
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/some_user/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

```

**Comment by mcanouil** [comment]
Please @younes-io do format properly your post to make it legible.
I showed you how to share code in the other issue.
See also <https://quarto.org/bug-reports.html>.

Note that "fa" shortcode does not come with Quarto, it's an extension you need to install.
https://github.com/quarto-ext/fontawesome

If you don't install the extension, you don't have the shortcode.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/b48b2247-be44-409f-b363-d87dda0005ab">

**Comment by younes-io** [comment]
I just forgot one tick; I fixed it.
Thank you, I installed the font-awesome extension and now it's working.

However, I don't know exactly what you expect to have for the Render popup issue.. I don't know which part of the code you want to have..

Also, I noticed a really heavy CPU/Mem consumption when I run the blog after the upgrade.

I would definitely try to provide you with all the details you need, I just don't know where this Render popup comes from:



![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/bf921f05-6f95-4259-a1d9-7663a2b719b0)

When I looked into the console, it's actually appended after the footer:

![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/b5702ebf-1831-4455-9972-d7a50fec4131)

**Comment by younes-io** [comment]
Also got this in the logs after the upgrade:

```

GET: /
WARNING: connection closed before message completed
GET: /
  /assets/img/logo.svg (404: Not Found)

GET: /blog/
WARNING: connection closed before message completed

GET: /
WARNING: connection closed before message completed

GET: /blog/
WARNING: connection closed before message completed

GET: /blog/
```

**Comment by mcanouil** [comment]
Can you share your project as a Git repository?

**Comment by younes-io** [comment]
Here you go https://github.com/younes-io/blog

**Comment by cderv** [comment]
The render pop up you see should come for the preview server. You must be running `quarto preview`. The preview server tries to be clever and will render what is necessary, and can trigger new render when you navigate the preview if needed. That is what the render popup is about. 

How are you looking at your website ? `quarto preview` ? 

If you `quarto render` and the  publish to your hosting service than when you'll go on the website there should be no render popup. 

If I go to https://younes.io/ or https://younes-io.github.io/blog - I don't see the popup 

Is this all happening when you are developing ? Can you tell us more about the workflow ?

**Comment by younes-io** [comment]
@cderv I haven't deployed it, so in the website, you still see the version pre-upgrade.

This is the local workflow: When I make a local change, say to `random_file.qmd`, and I save on VSCode, I have my command always running `quarto render && quarto preview`, which detects the changes and refreshes the page on the browser (I noticed that sometimes, the popup also gets filled with YAML data before the page refreshes).

Btw, is there a way to disable the popup ?

Thank you for your feedback, Christophe

**Comment by mcanouil** [comment]
> Btw, is there a way to disable the popup?

As said by Christophe, `quarto preview` render and watch your project for changes. There is no popup is `quarto preview` did not detect changes, there is one when it detects changes. This is the whole purpose of `quarto preview`.
Disabling the popup to use your words, means to disable `quarto preview`, so of that is what you want then don't use `quarto preview`, use `quarto render` and serve yourself the website.
For instance, in VSCode there is a "Live Preview" (<https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server>) extension you could use (it does watch the HTML files, but not the Quarto document as `quarto preview` does).

**Comment by younes-io** [comment]
Thank you @mcanouil for the clarification. Understood.

Although, when I run `quarto preview` locally, the code annotations are generated correctly:

![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/865a88f3-3ec8-4751-8169-b018349ce07d)

However, on the deployed [blog post](https://younes.io/blog/2024-01-17-rust-memory-model/#ownership), I have:

![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/cb15cdb1-c559-490c-9f0b-7b6a897a0c82)

**Comment by mcanouil** [comment]
You need to specify to same version.

**Comment by cderv** [comment]
@younes-io to be clear

- Your website is built using Quarto 1.3.450 - current stable
- Your initial question was about Quarto 1.4 that you upgraded

If you want to use Quarto 1.4 in the Github action, you need to ask for it - default is the latest release no pre-release
https://github.com/quarto-dev/quarto-actions/tree/main/setup#inputs-available

**Comment by younes-io** [comment]
Thank you both for bringing this to my attention.

@cderv, to provide some context, I upgraded because code annotations were not functioning correctly in the current stable version. Following @mcanouil’s recommendation, I proceeded with the update. Now, I am in the process of making adjustments to accommodate the new version.

However, the issues I encounter locally are also present in the deployed version: inconsistent rendering, incomplete page displays, and seemingly random visibility of various page sections.

Additionally, the github icon in the footer is not centered as it should be. Are these known issues that are being addressed, or should I file separate issues for each?

![image](https://github.com/quarto-dev/quarto-cli/assets/3153107/03408827-d621-4ec3-940c-08f59df2f7f6)

**Comment by mcanouil** [comment]
As no breakage has been reported so far regarding something like that, It's very likely to be something related to the specificity of your website, in particular all the customisation you made.
Try disabling your CSS/SCSS and other non Quarto changes to see what is causing this.

It's unfortunate but Quarto cannot guards against CSS conflicts from user customisation.

Again, you need to provide a small reproducible example.
