### ISSUE TITLE
Reference page item `giscus: theme` doesn't have correct description

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#8352]
[PR#8342](https://github.com/quarto-dev/quarto-cli/pull/8342) added a more detailed `description` for the `theme` option to giscus. 

Currently, running `quarto run tools/reference.ts` results in this wrong description:
```json
{ 
  "name": "theme", 
  "description": "The light theme name."
}
```
It should be:
```json
 {
  "name": "theme",
  "description": "The giscus theme to use when displaying comments. Light and dark themes are supported. If a single theme is provided by name, it will be used as light and dark theme. To use different themes, use `light` and `dark` key: \n\n```yaml\nwebsite:\n  comments:\n    giscus:\n      light: light # giscus theme used for light website theme\n      dark: dark_dimmed # giscus theme used for dark website theme\n```\n"
}
```

It seems we are picking up the description for `giscus:theme:light`. 

A solution that works is moving up the `description` element in the schema to come right after `theme:`, suggesting `reference.ts` is just picking up the first `description`, not the top-level `description`.

I think it boils down to the [`findVal()` function in reference.ts](https://github.com/quarto-dev/quarto-web/blob/6c369c6209bd0163b61d1e9ae5b55f9f0e76933b/tools/reference.ts#L298-L311) doing a depth-first as opposed to breadth-first search for key names.

**Comment by dragonstyle** [comment]
Should be fixed here:

[73c0912fcae362850818fd0ac7e088cc9f65ccba](https://github.com/quarto-dev/quarto-web/commit/597495ffc22c8ebdf6755ced1f0293620fcced77)
