### ISSUE TITLE
ojs not respecting output: false or include: false

### ISSUE THREAD

**Issue by robolyst** [quarto-dev/quarto-cli#8372]
### Bug description

I am using Quarto to render ObservableJS cells in a Hugo blog. I would like to use ObservableJS to import a csv file and plot the results. I would like to use a separate cell for the FileAttachment call so that I can have an interactive input modify the plot without constantly re-downloading the csv file. I do not want any output shown for the FileAttachment cell.

Adding
```js
//| echo: false
//| output: false
//| include: false
```
to the top of the `{ojs}` cell that imports the csv file correctly prevents the code from displaying. However the cell output is still shown.

### Steps to reproduce

Using the following file `example.qmd`:
``````md
---
title: "Ojs Test"
format: hugo-md
---

Lorem ipsum dolor sit amet, consectetur adipiscing elit.

```{ojs}
//| echo: false
//| output: false
//| include: false
a = 5;
```

```{ojs}
b = 6;
```

Nulla at varius turpis. Ut nec purus efficitur, dictum urna eget, molestie ante.
``````

render it with:
```bash
quarto render example.qmd
```

### Expected behavior

I expect to see no output for the first cell.

### Actual behavior

There is a `div` outputted for the first cell:
``````md
---
title: "Ojs Test"
format: hugo-md
---

<script type="module" src="example_files/libs/quarto-ojs/quarto-ojs-runtime.js"></script>
<link  href="example_files/libs/quarto-ojs/quarto-ojs.css" rel="stylesheet" />

Lorem ipsum dolor sit amet, consectetur adipiscing elit.

<div id="ojs-cell-1"></div>

``` js
b = 6;
```

<div id="ojs-cell-2"></div>

Nulla at varius turpis. Ut nec purus efficitur, dictum urna eget, molestie ante.

<script type="ojs-module-contents">
eyJjb250ZW50cyI6W3sibWV0aG9kTmFtZSI6ImludGVycHJldCIsImNlbGxOYW1lIjoib2pzLWNlbGwtMSIsImlubGluZSI6ZmFsc2UsInNvdXJjZSI6ImEgPSA1O1xuIn0seyJtZXRob2ROYW1lIjoiaW50ZXJwcmV0IiwiY2VsbE5hbWUiOiJvanMtY2VsbC0yIiwiaW5saW5lIjpmYWxzZSwic291cmNlIjoiYiA9IDY7XG4ifV19
</script>
<script type="module">
if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
window._ojs.paths.runtimeToDoc = "../../..";
window._ojs.paths.runtimeToRoot = "../../..";
window._ojs.paths.docToRoot = "";
window._ojs.selfContained = false;
window._ojs.runtime.interpretFromScriptTags();
</script>
``````

### Quarto check output

```bash
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /quarto-cli/package/dist/bin

Check file:///quarto-cli/src/resources/vendor/deno-land/x/puppeteer@9-0-2/mod.ts
[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: /usr/local/bin/python3
      Jupyter: 5.5.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment]
Unfortunately, I don't think this is going to be easy for us to solve. `output: false` is what we use to denote "do not produce visible output". The execution of the OJS cell `ojs-cell-1` is still requested (some other cell might want to use the value of `a`), and the OJS runtime needs a div in order to initiate the execution of that cell.

The cell itself shouldn't be producing any visible output, and so I don't think this has an effect on your rendered page.

I'm going to go ahead and close this as `wontfix`. But please feel free to comment and we'll reopen if my assessment is wrong.

**Comment by robolyst** [comment]
Hey @cscheid thank you so much for following up with this.

There is indeed visible output from the OJS cell `ojs-cell-1`. Here's a screen shot of the rendered page in browser (The unwanted output is "a = 5"):

![image](https://github.com/quarto-dev/quarto-cli/assets/7521223/4a44b2ec-a752-4a6b-86e0-e14584663340)

And here's a screenshot of the element in Google chrome explorer:

![image](https://github.com/quarto-dev/quarto-cli/assets/7521223/ef95b331-3d2c-4bf4-8168-01e29dcd05b0)

You can even see a basic example of this on observablehq.com in their own notebooks, they by default show output for every cell:

![image](https://github.com/quarto-dev/quarto-cli/assets/7521223/ddcca704-b5c8-4f6e-8b96-ae67a574138a)


Please please please reopen 🙏🏻

**Comment by cscheid** [comment]
Thanks - we definitely were emitting incorrect output here.

The fix _will_ make the .md a bit uglier. Specifically, we now will emit this:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

<div class="cell hidden">
<div class="cell-output cell-output-display hidden">
<div id="ojs-cell-1"></div>
</div>
</div>
<div class="cell">

``` js
b = 6;
```

<div class="cell-output cell-output-display">
<div id="ojs-cell-2"></div>
</div>
</div>

Nulla at varius turpis. Ut nec purus efficitur, dictum urna eget, molestie ante.
```

**Comment by robolyst** [comment]
Thank you! I do have an engineering bias, but working + ugly is better than not working but pretty.

Will keep an eye out for the update. Thanks again!
