### ISSUE TITLE
figure lables with underscore not working when rendering to pdf (latex)

### ISSUE THREAD

**Issue by Sciemon** [quarto-dev/quarto-cli#8374]
### Bug description

quarto changes a label with underscore, such as 'fig-SVS_droop' to '\label{fig-SVS\_droop}', replacng '_' with '\_'. Then latex throws an error because of that. 

### Steps to reproduce

render the .qmd file in the repo https://github.com/Sciemon/issue_figure_label

### Expected behavior

no '\_' in the label

### Actual behavior

ERROR:
compilation failed- error
Missing \endcsname inserted.
<to be read again>
                   \protect
l.10 ... FACTS droop control}{figure.caption.2}{}}

### Your environment

- IDE: vscode
- OS: Windows 10

### Quarto check output

Quarto 1.4.545
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.545
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\seberlein\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: C:/Users/seberlein/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.7.1
      Kernels: python3

(\) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Program Files\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Program Files\Quarto\share\jupyter\notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK

**Comment by cscheid** [comment]
That's unfortunately a limitation with LaTeX, and not a quarto bug. We should emit a warning in this case, but labels with underscores is not a thing you can do in LaTeX at all.

**Comment by Sciemon** [comment]
Ok,I was and not aware of that as I have been using underscores in figure labels a lot in latex and not encountered problems as far as I remember. But there seem to be problems in combination with certain packages.

This is already discussed in #7307 , where it is also mentioned to add to the documentation to avoid underscores in labels.

**Comment by olivroy** [comment]
May I suggest to add a warning directly in the IDE?

I used an R function to display what I mean, 
![image](https://github.com/quarto-dev/quarto-cli/assets/52606734/0d5f9116-a78f-45e7-ae55-5b72f00823d8)

but instead of x a warning tooltip that says that you should not use `_` in label if it is detected?

**Comment by cscheid** [comment]
yes, that's the plan.

**Comment by mcanouil** [comment]
FYI, the documentation now states to avoid the use of underscores for labels (<https://quarto.org/docs/authoring/cross-references.html>).
