### ISSUE TITLE
Different revealjs formats in a Quarto website don't work as expected

### ISSUE THREAD

**Issue by Nenuial** [quarto-dev/quarto-cli#8383]
### Bug description

I have multiple revealjs presentations that are included in a quarto website. I use different formats (using extensions) to have different templates.

I have observed that when you render the website, all presentations have the same template. `quarto render` probably generates only one css file for all quarto presentations and all presentations end up with the same template.

### Steps to reproduce

To reproduce this:

* Extension with revealjs formats: https://github.com/Nenuial/quarto-theme
* Example website: https://github.com/Nenuial/ThemeTest

Live example: https://test.nenuial.org
The vignettes show the desired theme.

### Expected behavior

Each revealjs presentation with a different format should have its own css file.

### Actual behavior

All revealjs presentations have the same css file.

### Your environment

- IDE: RStudio Version 2023.12.0+369 (2023.12.0+369)
- MacOS Sonoma 14.2.1

### Quarto check output

Quarto 1.4.545
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.545
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/admin/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /opt/homebrew/Caskroom/miniconda/base/bin/python
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by dyavorsky** [comment]
I'm reporting the same issue when multiple revealjs presentations are included on a website and only one references a custom scss theme.  The scss theme was "not registering" leading me to believe it is being assigned the "default theme" per this issue.

**Comment by cscheid** [comment]
This should be fixed in https://github.com/quarto-dev/quarto-cli/releases/tag/v1.6.7.
