### ISSUE TITLE
Web server shuts down too eagerly when error occurs

### ISSUE THREAD

**Issue by wch** [quarto-dev/quarto-cli#839]
In a Quarto document, I have an iframe which initially points to a file on disk named loading.html, but then after a small amount of time, there is JS code replaces the URL with another one. If this change happens quickly, the Quarto server shuts down and displays this error message:

```
ERROR: connection closed before message completed
```

Previously, this was just a warning. It looks like the change was made in 7cd7bb8718b9c06eced8379554c53fdbd0fc7834. I think it can make sense for the server to shut down for some errors, but shutting down for this particular one is a bit aggressive.

**Comment by jjallaire** [comment]
Agreed. This was put in b/c there was at least one case on OS X where a networking error rendered the server inoperable so I did this imagining there could be others (but it is more likely as you point out that there are benign errors that we would do well to ignore). I'll make a change scope the hard failure case down more aggressively.

**Comment by jjallaire** [comment]
Okay, I've reverted that change entirely as I can no longer repro the error I was seeing. It was an OS X networking error about "wrong protocol for port" -- I'm wondering if it had something to do with my laptop switching networks -- anyway, just be on the lookout for seeing this condition again and creating a localized workaround as required.
