### ISSUE TITLE
Publishing resets `highlight-style`

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto-cli#840]
Consider this reprex:

````
---
title: "test-highlighting"
format: html
engine: knitr
highlight-style: github
theme:
  light: flatly
  dark: darkly
---

```{r}
r = 1 + 2 + 3
```
````

The important bits are `highlight-style: github` and the custom themes. If I render this to HTML, I get the expected GitHub-style syntax highlighting:
<img width="612" alt="before" src="https://user-images.githubusercontent.com/4377312/167646958-0d70789e-580e-4183-817d-5d0517f4bbf0.png">
However, publishing this (e.g. to RPubs) seems to reset the highlighting style, because then the document looks like this:
<img width="612" alt="after" src="https://user-images.githubusercontent.com/4377312/167647143-8c6f6b94-4010-4988-a667-a1ecbd2f580b.png">

I think that this might be a bug – or did I make a mistake somewhere?

**Comment by cbrnr** [comment]
Of course, here's the URL of the published project: https://rpubs.com/cbrnr/test-highlighting

**Comment by dragonstyle** [comment]
Thanks! That was very helpful. I'm definitely able to see the issue at the URL you shared, but I'm still not reproducing it myself. I did notice that your example was generated using an older version of Quarto (v0.9.80)-  would you mind trying to update to the latest version of Quarto and see whether you still reproduce the issue?

**Comment by dragonstyle** [comment]
No worries at all- only occurred to me once I saw the differing output! Glad its working.
