### ISSUE TITLE
Quarto rendering some equations but not all

### ISSUE THREAD

**Issue by mkrasmus** [quarto-dev/quarto-cli#8406]
### Bug description

When rendering my quarto file using 

```
title: "Value-Added Model: Naplan 2021 - 2023"
format:
  html:
    code-copy: true
    code-fold: true
    highlight-style: zenburn
    df-print: paged
    html-math-method:
      method: mathjax
```
I get some equations displaying correctly, according to the mathjax script, and others that just display the mathjax script like for example:

`
$$

y_{i,j,t} = _0 + _j + C_1*y_{i,j,t-1} +e_{ij}

$$
`

### Steps to reproduce

````
---
title: "Value-Added Model: Naplan 2021 - 2023"
format:
  html:
    html-math-method:
      method: mathjax
---

##Mathjax

Mathematically, the regression model in Figure 2 can be written as:


$$

y_{i,t} = \beta_0 + \beta_1*y_{i,t-1} +e_i \tag{1}

$$

The simplest multilevel model with no explanatory variables (often referred to as the ‘null model’) can be written as

$$
level-1: y_{i,j} = \beta_{0j} + e_{ij} \tag{3} \\
$$
$$
level-2: \beta_{0j} = \beta_0 + u_{0j} \tag{4} 
$$
````

### Expected behavior

The first equation should be parsed and presented as the second and third equations

### Actual behavior

The first equation doesn't parse the test.

### Your environment

- IDE: 2023.06.1 Build 524, R version 4.3.2 (2023-10-31 ucrt) -- "Eye Holes", Windows 11.

### Quarto check output

```quarto check
Quarto 1.4.542
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.542
      Path: C:\Users\10456721\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\10456721\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/10456721/Documents/R/x86_64-w64-mingw32-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
There is no bugs here.
Empty lines is not valid equation syntax.

Also `##Mathjax` is not valid for section. `## Mathjax` is.

you can easily see that in GitHub.

1. No empty lines

$$
y_{i,t} = \beta_0 + \beta_1*y_{i,t-1} +e_i \tag{1}
$$

3. With empty lines

$$

y_{i,t} = \beta_0 + \beta_1*y_{i,t-1} +e_i \tag{1}

$$

**Comment by mkrasmus** [comment]
Should Rstudio preview it correctly if *Empty lines are not valid equation syntax.* ?

**Comment by mcanouil** [comment]
When you say "RStudio preview" what are you referring to exactly?

**Comment by cderv** [comment]
@mkrasmus There is two topics here to understand

Empty lines are not valid in a Markdown file where Pandoc will process math syntax.  The `tex_math_dollars` extension doc mentions this https://pandoc.org/MANUAL.html#extension-tex_math_dollars
> **Anything between two $ characters will be treated as TeX math. The opening $ must have a non-space character immediately to its right**. In contrast, the closing $ must have a non-space character immediately to its left, and must not be followed immediately by a digit.

In markdown `$$content` is equivalent to 
````markdown
$$
content
````
because newlines have not the effect of newlines unless two spaces or empty lines. 

This is why adding spaces in your example does not work - Pandoc won't parse it correctly as Math 
See the difference in how Pandoc parses it
* First case with no space leads to `DisplayMath`
* Second with case leads to no `DisplayMath` (which means it won't be converted as Mathjax syntax in HTML)
````powershell
> pandoc -t native
$$
y_{i,t} = \beta_0 + \beta_1*y_{i,t-1} +e_i \tag{1}
$$
^Z
[ Para
    [ Math
        DisplayMath
        "\ny_{i,t} = \\beta_0 + \\beta_1*y_{i,t-1} +e_i \\tag{1}\n"
    ]
]

> pandoc -t native
$$

y_{i,t} = \beta_0 + \beta_1*y_{i,t-1} +e_i \tag{1}

$$
^Z
[ Para [ Str "$$" ]
, Para
    [ Str "y_{i,t}"
    , Space
    , Str "="
    , Space
    , RawInline (Format "tex") "\\beta"
    , Str "_0"
    , Space
    , Str "+"
    , Space
    , RawInline (Format "tex") "\\beta"
    , Str "_1*y_{i,t-1}"
    , Space
    , Str "+e_i"
    , Space
    , RawInline (Format "tex") "\\tag{1}"
    ]
, Para [ Str "$$" ]
]
````

RStudio preview (or usually any HTML preview) won't use Pandoc to render the equation. It will directly use Mathjax library to do it. And I believe that Mathajx itself has no problem with space. For example 
````html
<span class="math display">\[

level-1: y_{i,j} = \beta_{0j} + e_{ij} \tag{3} \\

\]</span>
````
This would be rendered correctly. The difference is that is directly Mathjax syntax. 

Anyhow, I hope this helps clarify the behavior and what was meant by "Empty lines are no supported" in the context of Quarto. 

If you think RStudio IDE preview should do better, do open an issue in https://github.com/rstudio/rstudio

Thanks!

**Comment by mkrasmus** [comment]
Ok thank you, for taking time out of your day for the explanation. 

My take away is that when I render the Qmd/Rmd to html it gets piped through Pandoc and as it abides by Pandoc rules empty spaces/lines creates a new Para. No equation. But RStudio IDE **preview** shakes hands with Mathjax directly and within the preview displays equations as I intended.

Not sure if making RStudio IDE preview better represent a rendered doc, it might be better in that it would force us to code more cleanly/better.

Thanks both

**Comment by mcanouil** [comment]
"How it works" => https://quarto.org/docs/get-started/hello/vscode.html#how-it-works

![How it works](https://quarto.org/docs/get-started/hello/images/qmd-how-it-works.png)
