### ISSUE TITLE
How can I justify my article in .docx and change the default font?

### ISSUE THREAD

**Issue by rtheodoro** [quarto-dev/quarto-cli#841]
Hi, guys! I'm new with `quarto` in `RStudio`.

I need to generate an `.docx` with justified text and Times New Roman font (or similar in Linux).

To justify a `html` file with `.rmd` I used to put `<div style="text-align: justify">` at the begin of the file and close with `</div>`.

But this is not working with `quarto`. How can I fix it? 

Also, how can I change my main font in `quarto`?

My code:

I also tried to create a  template.docx but nothing happened (maybe because I use LibreOffice??)

```quarto
---
title: "My simple title"
description: | 
  Text proof
author: "My name and ID"
format: 
  docx:
    geometry: 
      - top=30mm
      - left=30mm
editor: visual
---

<div style="text-align: justify"> 

**UNIVERSIDADE DE SÃO PAULO - USP**

-   Program

-   Date: 10/05/2022

-   Subject: Calc

-   Professor: Marcelo 

# Question
**1)** Text textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textText textxt textText textText textText textText textText textText textText textText textText textText textText textText textxt textText textText textText textText textText textText textText textText textText textText textText textText text

</div>
```

**Comment by LiangChen3519** [comment]
I think you need a template docx file to custom your word output.
[Read here](url: https://quarto.org/docs/output-formats/ms-word-templates.html)
