### ISSUE TITLE
Citation text element makes text exceed width of column.

### ISSUE THREAD

**Issue by pastorn** [quarto-dev/quarto-cli#8416]
### Descrption

Okay, so this is tricky to get right. I'll try my best to describe it.

Here's what it looks like:
![too-wide-reference](https://github.com/quarto-dev/quarto-cli/assets/712688/eb34ad51-0266-4dbe-9b5c-ea4869e61ddc)

### Source

```.qmd
---
bibliography: references.bib
csl: apa.csl

lang: sv

format:
    pdf:
      papersize: a4
      geometry:
        - showframe
        - left=15.0mm
        - textwidth=102.0mm
        - marginparsep=7.7mm
        - marginparwidth=70.3mm
        - top=20mm
      mainfont: ETbb
---

Fögvr att kunna tala om expertis så kommer arbetet som bröderna @dreyfus publicerade om färdighetsinlärning och dess relation till regler att nämnas.


# References {.unnumbered}

::: {#refs}
:::
```

[This is the CSL file I use](http://www.zotero.org/styles/apa)

```.bib
@article{dreyfus,
  author = {Dreyfus, S.E. and Dreyfus, Hubert},
  year = {1980},
  month = {02},
  pages = {22},
  title = {A Five-Stage Model of the Mental Activities Involved in Directed Skill Acquisition},
  journal = {Distribution}
}
```

### Things that make it go away

  1. Removing "gv" from the first word (it's actually a misspelled word, the "gv" got in there due to some vim stuff).
  2. Changing to `lang: en`
  3. Removing the `mainfont` line
  4. Removing `csl: apa.csl`

I'm way too bad at latex to figure out what's going on here. But it seems bug-like enough for me to report it.

### Quarto version

Just did a pull from main branch:

```console
$ git show -s --format="%as %H"
2024-01-23 71c6e09c4ffa985011e3b767e85859dceb6362a0
```

**Comment by cscheid** [comment]
Quarto defers to LaTeX for actual typesetting, so this isn't a Quarto issue. This looks like an overfull hbox caused by "färdighetsinlärning" See https://tex.stackexchange.com/questions/182569/how-to-manually-set-where-a-word-is-split
