### ISSUE TITLE
v1.4.549 introduces major formatting inconsistencies for static {gt} tables in HTML

### ISSUE THREAD

**Issue by jimgar** [quarto-dev/quarto-cli#8417]
### Bug description

I have a HTML report that was developed with quarto versions 1.3.xxx, and works perfectly on the latest stable release of 1.3.450.

Rendering the report with quarto v1.4.549 results in several dramatic changes to the formatting of static {gt} tables, and I get the sense these are not just stylistic changes but are undesired effects. I don't know much about the underlying behaviour at all but my hunch is that certain styles in the gt tables are being overridden. But there are also layout issues. So a bit of a grab bag.

I've included a reprex that shows the various changes that I'm seeing.

### Steps to reproduce

````
---
pagetitle: "test"
format:
  html:
    embed-resources: true
execute:
  echo: false
---

```{r libraries}
#| warning: false
library(dplyr)
library(gt)
library(gtExtras)
library(janitor)
library(palmerpenguins)
```

# One

```{r cars}
m <- mtcars[1:3,] |> 
  gt()

m
```

# Two

```{r iris}
i <- iris[1:3,] |> 
  gt()

i
```

# Three

```{r tables}
#| layout: [[50, 50]]
m
i
```

# Four

```{r penguins}
p <- palmerpenguins::penguins |> 
  dplyr::summarise(n = dplyr::n(), .by = species) |> 
  janitor::adorn_totals() |> 
  gt::gt() |> 
  gt::tab_header(
    title = gt::html("Penguins<br><br>"),
  ) |> 
  gtExtras::gt_duplicate_column(
    column = n,
    dupe_name = "n %",
    after = n
  ) |>
  gtExtras::gt_plt_bar_pct(
    column = "n %",
    fill = "orange",
    background = "yellow"
  ) |> 
  gt::cols_width(tidyselect::contains("%") ~ gt::px(50)) |> 
  gt::cols_label("n %" = "") |> 
  gt::tab_style(
    locations = list(
      gt::cells_title(),
      gt::cells_body(rows = `species` == "Total"),
      gt::cells_column_labels(columns = tidyselect::everything())
    ),
    style = gt::cell_text(weight = "bold")
  ) |>
  gt::cols_align(
    align = "right",
    columns = tidyselect::everything()
  ) |>
  gt::tab_style(
    locations = list(
      gt::cells_body(),
      gt::cells_title()
    ),
    style = gt::cell_borders(style = "hidden")
  )

p
```

# Five

```{r colouring}
p |> 
  gt::tab_style(
    locations = gt::cells_body(rows = `species` == "Adelie" | `species` == "Gentoo"),
    style = gt::cell_fill(color = "#ffeed5")
  )
```

# Six

```{r penguin-tables}
#| layout: [[50, 50]]
p
p
```

# Seven

```{r peng}
#| layout: [[50, 50]]
p_i <- palmerpenguins::penguins |> 
  dplyr::summarise(n = dplyr::n(), .by = species) |> 
  janitor::adorn_totals() |> 
  gt::gt() |> 
  gt::tab_header(
    title = gt::html("Penguins<br><br>"),
  ) |> 
  gtExtras::gt_duplicate_column(
    column = n,
    dupe_name = "n %",
    after = n
  ) |>
  gtExtras::gt_plt_bar_pct(
    column = "n %",
    fill = "orange",
    background = "yellow"
  ) |> 
  gt::cols_width(tidyselect::contains("%") ~ gt::px(50)) |> 
  gt::cols_label("n %" = "") |>
  gt::cols_align(
    align = "right",
    columns = tidyselect::everything()
  ) |>
  gt::tab_style(
    locations = list(
      gt::cells_body(),
      gt::cells_title()
    ),
    style = gt::cell_borders(style = "hidden")
  ) |> 
  gt::opt_interactive()

p_i
p_i
```
````

### Expected behavior

Screenshots below of the output using v1.3.450

<img width="977" alt="1 3 450-1" src="https://github.com/quarto-dev/quarto-cli/assets/90831652/b36db325-25b4-4c51-8eb7-50516bf662a0">
<img width="985" alt="1 3 450-2" src="https://github.com/quarto-dev/quarto-cli/assets/90831652/65464dca-4bf2-4781-8dc2-591a262580c1">
<img width="984" alt="1 3 450-3" src="https://github.com/quarto-dev/quarto-cli/assets/90831652/4909c00d-ba33-45b3-b1ba-8baf4dbb6479">

Note that the tables all have vanilla formatting, are level with one another when appearing side-by-side, and formatting is consistent for static tables no matter if they are singular or side-by-side. Interactive tables reflect the formatting of the static ones.

### Actual behavior

Screenshots below of the output using v1.4.549

<img width="1129" alt="1 4 549-1" src="https://github.com/quarto-dev/quarto-cli/assets/90831652/086a0557-5873-47fc-990b-f4012ffa94c0">
<img width="981" alt="1 4 549-2" src="https://github.com/quarto-dev/quarto-cli/assets/90831652/29887324-b0dc-41a3-a2e3-3896632ec116">
<img width="1011" alt="1 4 549-3" src="https://github.com/quarto-dev/quarto-cli/assets/90831652/9b15de25-81cb-4027-8926-76619543cce1">

Tables are now striped. Their formatting changes when placed side-by-side c.f. single. In section 6, the righthand table has lost some content. Tables are being pushed up to the page edges as well. Cell colouring is being affected by the grey in the table stripes.

Interestingly if the tables are made interactive (section 7) then the formatting does look as expected.

### Your environment

- IDE: RStudio Version 2023.12.0+369 (2023.12.0+369)
- OS: macOS Sonoma 14.2.1

### Quarto check output

# For version 1.4.549

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.7
      Path: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

# For version 1.3.450

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.7
      Path: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Did you consider disabling Quarto table processing? `tab_options(quarto.disable_processing = TRUE)` (https://gt.rstudio.com/reference/tab_options.html)

Side note: do not mix inline syntax and YAML syntax.

- This is inline label syntax.

````qmd
```{r libraries}
```
````

- This is YAML label syntax (recommended syntax in Quarto).

````qmd
```{r}
#| label: libraries
```
````

**Comment by cscheid** [comment]
I can confirm that adding `html-table-processing: none` to the document metadata restores the behavior to that of 1.3.

So the issue here is that the parsing of some of this tables is failing. I'll continue investigating.

**Comment by jimgar** [comment]
Wow, amazing response rate folks! Thanks!

@mcanouil that works for me.
And @cscheid that also (separately) works for me.

**Comment by cscheid** [comment]
@jimgar FYI, some of the stylistic changes are by design: we want Quarto tables to be by default somewhat uniform in their look, and that includes setting some styles.

The breakage in vertical alignment, on the other hand, is not good. We'll definitely want to fix that.

**Comment by nclsbarreto** [comment]
I am having a similar issue (I think). I have tried adding `tab_options(quarto.disable_processing = TRUE)`, placed `#| html-table-processing: none` in the chunk heading, and tried both (in that order in the pdf image below), but when i look at the rendering, the column header is left aligned. Is this just because I am outputting a PDF and not HTML?

any help would be greatly appreciated. 

ps i have to leave out and censor a lot of info but i hope the code below is still of use. 

this is the pdf output
![Image](https://github.com/user-attachments/assets/e28804e9-5714-4346-a845-684090499a39)

this is the output in R (that i would like). 
![Image](https://github.com/user-attachments/assets/5e3f53d8-e65b-4a2a-bf76-48b7dbe95e74)


this is the code i used 
`tbl1_dat %>%
  gt(rowname_col = "v1") %>%
  cols_label(v1~ "",
             v2~ html("<p style='text-align: center;'>fill<br>filler</p>"),
             v3 ~ html(glue::glue("<p style='text-align: center;'>", gsub("\\(.*\\)", "", "filler filler filler"), "<br>Overall</p>")),
             v4 ~ html("<p style='text-align: center;'>&percnt;<br>fill</p>")
  ) %>%
  cols_align(
    columns = matches("txt1|txt2"),
    align = "center"
  ) %>%
  sub_values(values = "val1",
             replacement = glue::glue("replaced replaced replaced replaced replaced replaced replaced replaced replaced replaced")
  ) %>%
  sub_values(values = "val2",
             replacement = glue::glue("replaced replaced replaced replaced replaced replaced replaced replaced replaced replaced")
  ) %>%
  sub_values(values = "val3",
             replacement = glue::glue("replaced replaced replaced replaced replaced replaced replaced replaced replaced replaced")
  ) %>%
  sub_values(values = "val4",
             replacement = glue::glue("replaced replaced replaced replaced replaced replaced replaced replaced replaced replaced")
  ) %>%
  sub_values(values = "val5",
             replacement = glue::glue("replaced replaced replaced replaced replaced replaced replaced replaced replaced replaced")
  ) %>%
  sub_missing(missing_text = html("&mdash;")) %>%
  cols_width(!v1~ px(100)
  ) %>% 
  text_replace(
    locations = cells_body(columns = v4),
    pattern = "%",
    replacement = "&percnt;"
  ) %>% 
  tab_options(table.align = "left") `

**Comment by mcanouil** [comment]
@nclsbarreto please open a GitHub discussion with a readable/properly formatted small reproducible example. Guidelines are provided when opening the one.

**Comment by nclsbarreto** [comment]
My apologies. I just created a new one. Thank you for any time and help you can provide.
