### ISSUE TITLE
Autocompletion for `#| content:` in dashboards

### ISSUE THREAD

**Issue by olivroy** [quarto-dev/quarto-cli#8422]
### Bug description

The autocompletion does not show `content` in Quarto dashboards. https://quarto.org/docs/dashboards/data-display.html#value-boxes

### Steps to reproduce

````qmd
---
title: dashboard
format: dashboard
---

```r
#| cont
```
````

### Expected behavior

Should show content and suggestions. as well as possible values. like for code-fold, it shows true, false, and show.
![image](https://github.com/quarto-dev/quarto-cli/assets/52606734/0e9b9ad4-2e2b-4124-88c2-8bc4833886ed)

### Actual behavior

No autocomplete. If it is used for other things than valuebox, it would be great if the possible options were enumerated as well.

### Your environment

RSTudio 2023.12.0
Windows 10
Quarto 1.4.545

**Comment by cderv** [comment]
Thanks @dragonstyle ! I knew you would be more efficient to fill the right values. Thanks !
