### ISSUE TITLE
Python table with jupyter is showing label in caption when not a cross referenced table 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#8428]
````markdown
---
title: "Test"
format: html
keep-md: true
---

```{python}
#| label: test
#| tbl-cap: 
#|  - Test caption
import pandas as pd
from IPython.display import display, Markdown
penguins = pd.read_csv("https://pos.it/palmer-penguins-github-csv")
markdown_result = penguins.groupby("species").size().to_markdown(index=False, tablefmt="pipe", stralign="right")
display(Markdown(markdown_result))
```
````

This output to 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/634dc286-9418-4c31-ab4f-0886babc594a)

See `{#cell-test}` appearing in table caption 

Intermediate md is 
````markdown
---
title: "Test"
format: html
keep-md: true
---


::: {#cell-test .cell tbl-cap='["Test caption"]' execution_count=1}
``` {.python .cell-code}
import pandas as pd
from IPython.display import display, Markdown
penguins = pd.read_csv("https://pos.it/palmer-penguins-github-csv")
markdown_result = penguins.groupby("species").size().to_markdown(index=False, tablefmt="pipe", stralign="right")
display(Markdown(markdown_result))
```

::: {#test .cell-output .cell-output-display .cell-output-markdown}
|   0 |
|----:|
| 152 |
|  68 |
| 124 |
:::
:::
````

This should not be there

**Comment by cderv** [comment]
This is a regression as in 1.3 we get 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/75346776-05b6-4b61-8ca6-d6ccf4d634d1)

**Comment by cscheid** [comment]
Note that this only _barely_ works in 1.3; table captions by default should be on top of the table in our style, and it's not showing up there either.

We'll fix in 1.5 and backport the fix to 1.4 on the first patch, but this doesn't qualify as a must-fix issue for me.

**Comment by simonleandergrimm** [comment]
How can I fix this myself? I have the same issue.

**Comment by simonleandergrimm** [comment]
How can I fix this myself? I have the same issue.

**Comment by cscheid** [comment]
You can add `#| label: tbl-mytable` to the cell. It will become a crossreferenceable table with `Table 1: ...` etc.
