### ISSUE TITLE
New Quarto doc: State not recoverable; NotFound: no such file or directory (os error 2)

### ISSUE THREAD

**Issue by jfberner** [quarto-dev/quarto-cli#8429]
### Bug description

I'm not able to either:
1) open a new quarto document using "New File>Quarto Document...", which shows a message **State not recoverable**
![image](https://github.com/quarto-dev/quarto-cli/assets/75185995/74d64f4d-2c78-4bec-955f-efd4a59cd710)

2) render old preexisting ones, which throws the same error as `quarto check` (below)

Even though the file is present - as shown in the output of find_pandoc() below.

Furthermore, the output of `quarto_inspect('my_file.qmd')` throws a bit more detail:

> ERROR: NotFound: No such file or directory (os error 2)
> 
> NotFound: No such file or directory (os error 2)
>     at makeTempDirSync (deno:runtime/js/30_fs.js:80:16)
>     at file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:5958:29
>     at withAttempts (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:5917:20)
>     at Object.makeTempDirSync (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:5958:12)
>     at initSessionTempDir (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:47813:20)
>     at quarto (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:127543:5)
>     at file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:127563:15
> Error: lexical error: invalid char in json text.
>                                                 NA
>                      (right here) ------^
> In addition: Warning message:
> In system2(quarto_bin, stdout = TRUE, c("inspect", path.expand(input))) :
>   running command ''/usr/lib/rstudio/resources/app/bin/quarto/bin/quarto' inspect my_file.qmd' had status 1

Seeing other issues, I assume the output of `rmarkdown::find_pandoc()` will also be relevant:
```
$version
[1] ‘3.1.1’
$dir
[1] "/usr/lib/rstudio/resources/app/bin/quarto/bin/tools"
```

Trying to directly render the file using `quarto_render()` throws the following error (with details):
```
ERROR: NotFound: No such file or directory (os error 2)

NotFound: No such file or directory (os error 2)
    at makeTempDirSync (deno:runtime/js/30_fs.js:80:16)
    at file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:5958:29
    at withAttempts (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:5917:20)
    at Object.makeTempDirSync (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:5958:12)
    at initSessionTempDir (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:47813:20)
    at quarto (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:127543:5)
    at file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:127563:15
Error in `processx::run(quarto_bin, args, echo = TRUE)`:
! System command 'quarto' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Type .Last.error to see the more details.
> .Last.error
<system_command_status_error/rlib_error_3_0/rlib_error/error>
Error in `processx::run(quarto_bin, args, echo = TRUE)`:
! System command 'quarto' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Backtrace:
1. quarto::quarto_render("CNU_estudo.qmd")
2. processx::run(quarto_bin, args, echo = TRUE)
3. processx:::throw(new_process_error(res, call = sys.call(), echo = echo, …
```

### Steps to reproduce

Even hello.qmd is not working.

However, this is the header for the current file I'm trying to render:
```
---
title: "MyTitle"
subtitle: "MySubtitle"
author: "Me"
format:
    bookup-html+dark:
        toc: true
        toc-depth: 10
        # embed-fonts: true
editor: visual
toc-title: "Index"
abstract: "This is my abstract"
---
```

### Your environment

```
> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.2                         
year           2023                        
month          10                          
day            31                          
svn rev        85441                       
language       R                           
version.string R version 4.3.2 (2023-10-31)
nickname       Eye Holes
```
```
> RStudio.Version()
...
$mode
[1] "desktop"

$version
[1] ‘2023.12.0.369’

$long_version
[1] "2023.12.0+369"

$release_name
[1] "Ocean Storm"
```
```
> quarto_version()
[1] ‘1.3.450’

```
```
> Sys.info()
                                                           sysname 
                                                           "Linux" 
                                                           release 
                                         "6.6.10-76060610-generic" 
                                                           version 
"#202401051437~1704728131~22.04~24d69e2 SMP PREEMPT_DYNAMIC Mon J" 
                                                          nodename 
                                                          "pop-os" 
                                                           machine 
                                                          "x86_64" 
```

### Quarto check output

ERROR: NotFound: No such file or directory (os error 2)

NotFound: No such file or directory (os error 2)
    at makeTempDirSync (deno:runtime/js/30_fs.js:80:16)
    at file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:5958:29
    at withAttempts (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:5917:20)
    at Object.makeTempDirSync (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:5958:12)
    at initSessionTempDir (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:47813:20)
    at quarto (file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:127543:5)
    at file:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js:127563:15

**Comment by cscheid** [comment]
I think you're running RStudio? In this case, the place to report is https://github.com/rstudio/rstudio. I'm going to go ahead and close this but please reopen if I'm wrong.
