### ISSUE TITLE
Error while opening file at every render

### ISSUE THREAD

**Issue by guilhermegarcia** [quarto-dev/quarto-cli#8432]
### Bug description

Every time I render a `Qmd` file using RStudio, I get the same error: Error while opening file. It looks like it's looking for a file and it can't find it. It does render correctly, but the multiple error messages are annoying. It might be some Quarto extension, or maybe something very simple that I'm missing.

Context: I have an entire folder for my website, and use an `RProj` to manage it. Any `Qmd` file I render will throw the error. My RStudio is up-to-date (most recent version as of today). I've tried reinstalling RStudio, Quarto, and rebooting the system.

![Fig-2024-01-24](https://github.com/quarto-dev/quarto-cli/assets/4550337/cef142ee-cf5b-4500-bab9-592360aa4d13)

Using Terminal, no errors. Finally, everything worked out before installing Quarto `1.4.549`.

### Steps to reproduce

Render any `Qmd` from RStudio, not Terminal.

### Expected behavior

Render ends without any error messages/windows.

### Actual behavior

Error message is thrown regardless of which `Qmd` file is rendered in RStudio: Error while opening file. No such file or directory.

### Your environment

- IDE: RStudio 2023.12.0+369 (2023.12.0+369)
- Mac OS Sonoma 14.3

### Quarto check output

```bash quarto check

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/gdgarcia/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.7.1
      Kernels: julia-1.7

      NOTE: No Jupyter kernel for Python found

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK


```

**Comment by cscheid** [comment]
It looks like you're describing an issue with RStudio. Please file the bug at https://github.com/rstudio/rstudio. Thanks!
