### ISSUE TITLE
list filter not working with special characters

### ISSUE THREAD

**Issue by drtingtp** [quarto-dev/quarto-cli#8435]
Quarto Version: 1.3.450

### Problem:
Table listing does not allow filtering using special characters (e.g. dash).

### Reproduction steps:

1. Create a listing document with contents having dash in its title.
2. Render/preview as website.
3. Filter the document using dash.

### Possible cause:
I believe the cause lies in `list.min.js` module in `listing`

https://github.com/quarto-dev/quarto-cli/blob/037736475e1b0b61573306581eb109b44d3ab578/src/resources/projects/website/listing/list.min.js#L1

``` js
setSearchString: function(e) {
    e = (e = t.utils.toString(e).toLowerCase()).replace(/[-[\]{}()*+?.,\\^$|#]/g, "\\$&"),
    r = e
},
```

There is a replacement of a set of characters, so `-` is replaced by `"\-"`.

I am not sure what is the purpose of replacing the string but I am guessing my issue is due to either

- The unnecessary replacement; or
- The matching part did not consider the replacement that has taken place during the processing of the search string

**Comment by mcanouil** [comment]
Thanks for the report!
Could you use the latest stable version (which is 1.4)?
And could you share a Git repository with the small reproducible setup to reproduce?

**Comment by dragonstyle** [comment]
Root cause is here:
https://github.com/javve/list.js/issues/699

**Comment by drtingtp** [comment]
> Could you use the latest stable version (which is 1.4)? And could you share a Git repository with the small reproducible setup to reproduce?

Done https://github.com/drtingtp/quarto-cli-issue-8435

On another note, is there a temporary fix I can apply to my project as a Band-Aid?

**Comment by dragonstyle** [comment]
- The underlying filtering implementation  of `listjs` is using spaces to split terms for matching, so unfortunately it isn't a meaningful way to filter. 

- All I ended up doing was removing the line of code which was escaping characters. You could do the same thing perhaps in a post render script (just go in the output directory and open the list.min.js file and remove the offending code, then rewrite it).

More on post render scripts here:
https://quarto.org/docs/projects/scripts.html#pre-and-post-render
