### ISSUE TITLE
data.table is printed even when it shouldn't when rendering docx with cache enabled

### ISSUE THREAD

**Issue by achetverikov** [quarto-dev/quarto-cli#8436]
### Bug description

When rendering to docx, the markdown file generated includes a data.table even though it should not be printed. This seem to happen only when the cache is enabled on a second pass (so after the cache has been created). I've tried updating to the latest versions of RStudio/quarto and updating all R packages, still does not help. 

### Steps to reproduce

Render the following document in all three formats:

````qmd 
---
title: "Untitled"
format: 
  html: default
  docx: default
  pdf: default
editor: visual
editor_options: 
  chunk_output_type: console
knitr:
  opts_chunk: 
    echo: false
    message: false
    warning: false
    comment: NA
    cache.path: "cache/"

execute: 
  keep-md: true
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

```{r setup, cache = F}
library(data.table)
```

Problematic chunk:

```{r read_data, echo = F, results = 'show', cache = T}
#| tbl-cap: "ex"

data <- data.table(x = runif(5000))
data[,subject:=paste0('S',sample(1:100, .N, replace = T))]
data[,feature:=sample(c('A','B'), .N, replace = T)]
```
````

### Expected behavior

The outputs of the second chunk should be empty. 

### Actual behavior

Instead, they are empty when rendering to html or pdf but for docx they include a formatted output of the data.table. 
[mwe_label.pdf.md](https://github.com/quarto-dev/quarto-cli/files/14050512/mwe_label.pdf.md)
[mwe_label.docx.md](https://github.com/quarto-dev/quarto-cli/files/14050501/mwe_label.docx.md)
[mwe_label.html.md](https://github.com/quarto-dev/quarto-cli/files/14050502/mwe_label.html.md)

### Your environment

- RStudio 2024.04.0 Build 297 "Chocolate Cosmos" Daily (8a7fa575, 2024-01-25) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0-daily+297 Chrome/120.0.6099.56 Electron/28.0.0 Safari/537.36

### Quarto check output

```
$ quarto check
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\anche7026\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.13
      Path: C:/Users/anche7026/AppData/Local/Programs/Python/Python39/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.0
      Path: C:/R/R-4.3.0rc
      LibPaths:
        - C:/Users/anche7026/AppData/Local/R/win-library/4.3
        - C:/R/R-4.3.0rc/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
There are few "issues" likely because you come from rmarkdown.
Quarto recommends YAML syntax for all code cells options, see <https://quarto.org/docs/reference/cells/cells-knitr.html>.

Options like message, echo, warnings, are to be passed to `execute`: https://quarto.org/docs/reference/formats/html.html#execution

**Comment by achetverikov** [comment]
I still get the same results when I use your version =( 

![image](https://github.com/quarto-dev/quarto-cli/assets/1465806/ccfe8ff3-9414-4445-bfda-02723531d6f2)

[mwe_label.html.md](https://github.com/quarto-dev/quarto-cli/files/14051155/mwe_label.html.md)
[mwe_label.pdf.md](https://github.com/quarto-dev/quarto-cli/files/14051156/mwe_label.pdf.md)
[mwe_label.docx.md](https://github.com/quarto-dev/quarto-cli/files/14051157/mwe_label.docx.md)

**Comment by mcanouil** [comment]
Could you purge your cache and render again?
That's likely an issue with knitr caching.

You might also want to use `freeze`: https://quarto.org/docs/projects/code-execution.html#freeze

**Comment by achetverikov** [comment]
indeed, clearing the cache and re-rendering helped, I can't reproduce this anymore
thanks a lot for looking into this! I'll stick to using YAML for options

**Comment by mcanouil** [comment]
I forgot to mention that using underscores in label is heavily discouraged especially if you intend to use LaTeX/PDF format, *_i.e_*, `read_data` in your example.
