### ISSUE TITLE
quarto inspect with unsupported format gives stack trace

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#8451]
### Bug description

Using a document having an unrecognized format:

````markdown
---
title: whatever
format: unrecognized
---

document using an unrecognized format
````

The `quarto inspect` command produces an error and a stack trace.

### Steps to reproduce

Use the described document and run `quarto inspect <filename>.qmd`.

```
ERROR: Unknown format unrecognized

Stack trace:
    at resolveFormats (file:///Applications/quarto/bin/quarto.js:72373:19)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async renderContexts (file:///Applications/quarto/bin/quarto.js:72185:21)
    at async renderFormats (file:///Applications/quarto/bin/quarto.js:72234:22)
    at async inspectConfig (file:///Applications/quarto/bin/quarto.js:98729:29)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:98776:20)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8104:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:114968:5)
    at async file:///Applications/quarto/bin/quarto.js:114986:9
```

Compare this to what is produced by `quarto render <filename>.qmd`:

```
ERROR: Validation of YAML front matter failed.
ERROR: In file index.qmd
(line 3, columns 9--20) Field "format" has value unrecognized, which must instead be 'asciidoc'
2: title: whatever
3: format: unrecognized
          ~~~~~~~~~~~~
4: ---

ERROR: Render failed due to invalid YAML.
```

### Expected behavior

The `quarto inspect` should not reveal a stack trace for unsupported formats.

### Actual behavior

The `quarto inspect` reveals a stack trace for unsupported formats.

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/aron/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
I think this actually evinces a separate, actual bug, where `quarto inspect` will fail to detect the correct engine if that's determined by the content of a `{{< include >}}` shortcode.

**Comment by cscheid** [comment]
I wonder if the correct response here is to produce a machine-readable version of this error.

`quarto inspect` is almost certainly going to be called by a software rather than people, and so I think the error should be readable by software as well.

**Comment by cscheid** [comment]
> `quarto inspect` is almost certainly going to be called by a software rather than people, and so I think the error should be readable by software as well.

That's a bit more than we can chew right now, so instead I've improved the situation so that the output looks like this:

```
$ quarto inspect 8451.qmd
ERROR: Validation of YAML front matter failed.
ERROR: In file 8451.qmd
(line 3, columns 9--20) Field "format" has value unrecognized, which must instead be 'asciidoc'
2: title: whatever
3: format: unrecognized
          ~~~~~~~~~~~~
4: ---

ERROR: 8451.qmd is not a valid Quarto input document
```

The squiggles remain unaligned and that specific error message remains terrible. But it's an improvement.

**Comment by cscheid** [comment]
Let's see what the test suite says. As I think about this some more, I'm not convinced it's a good fix. The error is slightly better in the case of unrecognized formats, but there could be validation errors that shouldn't cause `quarto inspect` to throw, and so we are slightly changing `quarto inspect`'s contract here.
