### ISSUE TITLE
knitr+reticulate cannot show plots when the root.dir is changed

### ISSUE THREAD

**Issue by xiaoxl** [quarto-dev/quarto-cli#8460]
### Bug description

I use `knitr`+`reticulate` to run `python` codes. When I change the working folder of `knitr`, the `python` plot won't show.

### Steps to reproduce
````
---
engine: knitr
---

```{r}
library(knitr)
library(reticulate)
knitr::opts_knit$set(root.dir='data/')
```

```{r}
x <- 1:5
plot(x, x)
```

```{python}
import matplotlib.pyplot as plt
x = [1,2,3,4,5]
plt.plot(x, x)
```

````

### Expected behavior

The first block is the setting. The directory is changed to be a subfolder of the current folder.
The second block is a R chunk while the third is a Python chunk. 
We expect to see both plots in the rendered document.

### Actual behavior

The R plot is shown correctly. The Python plot file will be generated in the temporal folder, but cannot be shown in the rendered document. It will show a (404: Not Found) error message in the quarto console.

If I don't change working directory, the Python plot will be shown as expected.

### Your environment

- IDE: VSCode 1.85.2
- OS: Windows 11 Pro 22H2

### Quarto check output

Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\Xinli\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Xinli\AppData\Roaming\TinyTeX\bin\win32\
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.7 (Conda)
      Path: C:/Users/Xinli/miniforge3/envs/ds24/python.exe
      Jupyter: 5.5.1
      Kernels: ds24

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/Xinli/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by cderv** [comment]
I believe this is an issue with **reticulate** itself. It seems that the python engine for **knitr** provided by **reticulate** does not handle this the same as the R engine. 

Reproducible example with R Markdown 

````markdown
---
title: "reticulate"
output:
  html_document:
    keep_md: true
---

```{r}
library(knitr)
library(reticulate)
knitr::opts_knit$set(root.dir='data/')
```

```{r}
x <- 1:5
plot(x, x)
```

```{python}
import matplotlib.pyplot as plt
x = [1,2,3,4,5]
plt.plot(x, x)
```
````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/725993a2-3a24-4e4f-90a1-331ce588d56c)

So this is not on Quarto IMO. 

Also, for Quarto, changing the working directory for code execution in a project is best done using `execute-dir` configuration
See https://quarto.org/docs/projects/code-execution.html#working-dir

**Comment by cderv** [comment]
Related issues about this : 

* https://github.com/yihui/knitr/issues/1783
* https://github.com/rstudio/reticulate/issues/645#issuecomment-566616817
* https://github.com/rstudio/reticulate/pull/671

**Comment by cderv** [comment]
Issue reported at 
* https://github.com/rstudio/reticulate/issues/1526

**Comment by cderv** [comment]
This is now solved upstream - use the dev version of **reticulate** 

Thanks a lot for the report!
