### ISSUE TITLE
The include-code-files extension can not work in the latest version 1.4.549.

### ISSUE THREAD

**Issue by wangwei1237** [quarto-dev/quarto-cli#8470]
### Bug description

When I upgraded from version 1.3.450 to version 1.4.549, I found that the `include-code-files` extension could not render the code from the file as before.

```
{#lst-demo .python include="test.py" code-line-numbers="true" lst-cap="title"}
```

The example can found from: https://github.com/wangwei1237/LLM_in_Action/releases/tag/v0.0.33

**Comment by mcanouil** [comment]
What is the "code-file" extension you are referring to exactly?
As far as I know, there are two.

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.
I don't believe there is a need for an archive.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Comment by wangwei1237** [comment]
> What is the "code-file" extension you are referring to exactly?您所指的 “代码文件” 扩展名究竟是什么？ As far as I know, there are two.据我所知，有两个。
> 
> Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.你能分享一个小型的自包含的 “工作”（可复制）示例吗？例如，一个完整的 Quarto 文档或 Git 存储库？谢谢 I don't believe there is a need for an archive.我认为不需要档案。
> 
> You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four `` ```` ``).您可以使用以下语法共享 Quarto 文档，即使用比文档中更多的回溯标记（通常为四个 ```）。
> 
> ```
> ````qmd
> ---
> title: "Reproducible Quarto Document"
> format: html
> engine: knitr
> ---
> 
> This is a reproducible Quarto document using `format: html`.
> It is written in Markdown and contains embedded R code.
> When you run the code, it will produce a plot.
> 
> ```{r}
> plot(cars)
> ```
> 
> ![A placeholder image](https://placehold.co/600x400.png)
> 
> The end.
> ````
> ```

I use the `python` include code file. 
I have an example for `include-code-file` extension in my ebook as the following link: 

https://github.com/wangwei1237/LLM_in_Action/blob/main/langchain_agent_chat.qmd

The head of the `langchain_agent_chat.qmd`: 

```
---
filters:
   - include-code-files
code-annotations: below
---
```

In the line 31, I include a python file:
````
```{#lst-la_chat_conversation_demo .python include="./code/test_chat_coversation_agent.py" code-line-numbers="true" lst-cap="Chat Conversation Agent"}
```
````

And the `test_chat_coversation_agent.py` can find from: https://github.com/wangwei1237/LLM_in_Action/blob/main/code/test_chat_coversation_agent.py.

You can use my ebook repository to debug this issue: https://github.com/wangwei1237/LLM_in_Action

**Comment by mcanouil** [comment]
There is no filter and no extensions in your repository.

For example:
- <https://github.com/quarto-ext/include-code-files>
- <https://github.com/shafayetShafee/add-code-files> (this was the other one which seems to have been renamed possibly to avoid confusion).

You need to follow the instructions about the extensions you want to use.

Note that your repository is not small and noisy as it contains a lot of stuff not relavant with your issue, so not really usable.
It's important you make a small and reproducible example as I showed. This will help us help you and possibly help future readers.
