### ISSUE TITLE
API Error: 404 - Not Found

### ISSUE THREAD

**Issue by jj11031** [quarto-dev/quarto-cli#8471]
Sharing the terminal output here: 

Microsoft Windows [Version 10.0.22631.3085]
(c) Microsoft Corporation. All rights reserved.

D:\ElephantDataAnalysis\Metrics and RSF>quarto publish quarto-pub
? Publish update to: » https://jj11031.quarto.pub/spatiotemporal-movement-metrics-of-wild-elephants (Quarto Pub - jayjit11031@gmail.com)
Rendering for publish:

processing file: Metrics-and-RSF.rmarkdown
  |.                                       |   3% [Loading essential libraries]trying URL 'http://cran.rstudio.com/bin/windows/contrib/4.3/lattice_0.22-5.zip'
Content type 'application/zip' length 1380440 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

output file: Metrics-and-RSF.knit.md

pandoc
  to: html
  output-file: Metrics and RSF.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  toc: true

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  bibliography:
    - reference.bib
  title: Spatiotemporal movement metrics of wild elephants
  author: Jayjit Das

[WARNING] Citeproc: citation Benhamou2004 not found
[>] Preparing to publish document
ERROR: API Error: 404 - Not Found

Stack trace:
    at QuartoPubClient.createDeploy (file:///C:/Users/jayji/AppData/Local/Programs/Quarto/bin/quarto.js:102930:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///C:/Users/jayji/AppData/Local/Programs/Quarto/bin/quarto.js:102043:22
    at async withSpinner (file:///C:/Users/jayji/AppData/Local/Programs/Quarto/bin/quarto.js:75270:16)
    at async handlePublish (file:///C:/Users/jayji/AppData/Local/Programs/Quarto/bin/quarto.js:102021:5)
    at async publishDocument (file:///C:/Users/jayji/AppData/Local/Programs/Quarto/bin/quarto.js:106587:38)
    at async publish6 (file:///C:/Users/jayji/AppData/Local/Programs/Quarto/bin/quarto.js:106679:132)
    at async doPublish (file:///C:/Users/jayji/AppData/Local/Programs/Quarto/bin/quarto.js:106639:13)
    at async publishAction (file:///C:/Users/jayji/AppData/Local/Programs/Quarto/bin/quarto.js:106650:9)
    at async Command.fn (file:///C:/Users/jayji/AppData/Local/Programs/Quarto/bin/quarto.js:106627:9)

D:\ElephantDataAnalysis\Metrics and RSF>quarto check
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\jayji\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\jayji\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.18 (Conda)
      Path: C:/Users/jayji/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[>] Checking R installation...........OK
      Version: 4.3.0
      Path: C:/PROGRA~1/R/R-43~1.0
      LibPaths:
        - C:/Users/jayji/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.0/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Could you properly format your post using code blocks and could you properly describe the issue your having? Than you!

**Comment by mcanouil** [comment]
Please edit your posts and use code blocks to put terminal outputs separately from the text.

**Comment by jj11031** [comment]
qmd file inputs:

````
---
title: "Spatiotemporal movement metrics"
author: Jayjit Das
format:
  html:
    toc: true
    warning: false
    freeze: true
bibliography: reference.bib
---

#### Goal: Exploratory data analysis 

In this project, we shall go through various movement metrics to understand spatio-temporal movement of animals. This entire exercise shall consist of data wrangling, analysis and visualizations.

We will derive step lengths (SL), turning angles (TA), net squared displacement (NSD) and explore them to try and make ecological sense of the data.

Step lengths, is the Euclidean distance between two consecutive tracked locations, and turning angles, the angle made by the animal’s turn during three consecutive tracked locations, describe distance and direction, respectively. By accounting for the temporal difference between tracked locations they can be used to evaluate an animal’s speed and tortuosity. Both of these metrics are widely used in movement ecology. @avgar2016a

![](images/Example-of-movement-pathway-in-SSFs-Example-of-how-a-movement-pathway-can-be-simplified.png){width="636"}

Figure above aids in visualizing the step length and turning angle concepts.

Later we will also derive daily movement metrics like Daily Distance Traveled (DDT), Daily Overall Displacement (DOD), Daily Maximum Displacement (DMD) and Straightness of Daily Path (SDP). We shall learn about them in details gradually. 


```{r}
  E$week <- as.numeric(strftime(as.POSIXlt(E$t_),format="%W"))
  E$year <- as.numeric(strftime(as.POSIXlt(E$t_),format="%Y"))
  E$day <- as.numeric(strftime(as.POSIXlt(E$t_),format="%j"))
  str(E)
```
````
Here's the messgae from terminal: 
D:\ElephantDataAnalysis\Metrics and RSF>quarto publish quarto-pub
? Publish update to: » https://jj11031.quarto.pub/spatiotemporal-movement-metrics-of-wild-elephants (Quarto Pub - jayjit11031@gmail.com)
Rendering for publish:



processing file: Metrics-and-RSF.rmarkdown
  |.                                       |   3% [Loading essential libraries]trying URL 'http://cran.rstudio.com/bin/windows/contrib/4.3/lattice_0.22-5.zip'
Content type 'application/zip' length 1380440 bytes (1.3 MB)
==================================================
downloaded 1.3 MB


output file: Metrics-and-RSF.knit.md

pandoc
  to: html
  output-file: Metrics and RSF.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  toc: true

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  bibliography:
    - reference.bib
  title: Spatiotemporal movement metrics of wild elephants
  author: Jayjit Das

[WARNING] Citeproc: citation Benhamou2004 not found
[>] Preparing to publish document
**ERROR: API Error: 404 - Not Found**

Kindly let me know if this helps. Also, I already have my .html file rendered and ready to publish. Still, even after using the "feeze" command in _quarto.yml and the .qmd file, it takes forever to render the document and publish it. Kindly let me know if there's a workaround to fasten the process.

**Comment by mcanouil** [comment]
@jj11031 Please take few minutes to format all your posts.

I just try to publish to Quarto Pub and did not encounter any issues.
This seems, it's either temporary issue on Quarto Pub (not Quarto CLI), or something in your setup (proxy, firewall, bad internet connection, etc.)

**Comment by jj11031** [comment]
.qmd file is below

````
---
title: "Spatiotemporal movement metrics"
author: Jayjit Das
format:
  html:
    toc: true
    warning: false
    freeze: true
bibliography: reference.bib
---

#### Goal: Exploratory data analysis 

In this project, we shall go through various movement metrics to understand spatio-temporal movement of animals. This entire exercise shall consist of data wrangling, analysis and visualizations.

We will derive step lengths (SL), turning angles (TA), net squared displacement (NSD) and explore them to try and make ecological sense of the data.

Step lengths, is the Euclidean distance between two consecutive tracked locations, and turning angles, the angle made by the animal’s turn during three consecutive tracked locations, describe distance and direction, respectively. By accounting for the temporal difference between tracked locations they can be used to evaluate an animal’s speed and tortuosity. Both of these metrics are widely used in movement ecology. @avgar2016a

![](images/Example-of-movement-pathway-in-SSFs-Example-of-how-a-movement-pathway-can-be-simplified.png){width="636"}

Figure above aids in visualizing the step length and turning angle concepts.

Later we will also derive daily movement metrics like Daily Distance Traveled (DDT), Daily Overall Displacement (DOD), Daily Maximum Displacement (DMD) and Straightness of Daily Path (SDP). We shall learn about them in details gradually. 


```{r}
  E$week <- as.numeric(strftime(as.POSIXlt(E$t_),format="%W"))
  E$year <- as.numeric(strftime(as.POSIXlt(E$t_),format="%Y"))
  E$day <- as.numeric(strftime(as.POSIXlt(E$t_),format="%j"))
  str(E)
```
````


Output from the terminal is velow: 

````
output file: Metrics-and-RSF.knit.md

pandoc
to: html
output-file: Metrics and RSF.html
standalone: true
section-divs: true
html-math-method: mathjax
wrap: none
default-image-extension: png
toc: true

metadata
document-css: false
link-citations: true
date-format: long
lang: en
bibliography:
- reference.bib
title: Spatiotemporal movement metrics of wild elephants
author: Jayjit Das

[WARNING] Citeproc: citation Benhamou2004 not found
[>] Preparing to publish document
ERROR: API Error: 404 - Not Found

````
The problem is **ERROR: API Error: 404 - Not Found**

Let me know if it helps now. Also, I already have my .html file rendered and ready to publish. Still, even after using the "feeze" command in _quarto.yml and the .qmd file, it takes forever to render the document and publish it. Kindly let me know if there's a workaround to fasten the process.

**Comment by mcanouil** [comment]
@jj11031 you don't have to post multiple times. Simply use the edit button.
