### ISSUE TITLE
Embed does not include the figures generated by Julia

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8472]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8468

<div type='discussions-op-text'>

<sup>Originally posted by **mpf** January 27, 2024</sup>
### Description

[This is a follow-up to [this question](https://github.com/quarto-dev/quarto-cli/discussions/8400#discussion-6123491) on embeds, which went unresolved. Link to MWE at end of post.]

According to the documentation for [embedding from Quarto documents](https://quarto.org/docs/authoring/notebook-embed.html#quarto-documents), it should be possible to embed figures generated from within other `qmd` files, eg,

`index.qmd`:
````qmd
---
title: "Quarto MWE"
format: html
---

```{julia}
#| echo: true  # <-- preview throws error if 'false'
#| label: fig-index-plot
#| output: true
#| fig-cap: "A plot of the sine function"
using Plots
plot(sin, -2π, 2π)
```
````
`about.qmd`:
````qmd
---
title: "About"
format: html
---

{{< embed index.qmd#fig-index-plot >}}
````

But when I do this, the embed reproduces the code but not the figure, eg,

<img width="487" alt="Screenshot 2024-01-27 at 11 44 51 AM" src="https://github.com/quarto-dev/quarto-cli/assets/109942/f1755cda-cf99-4034-b58a-799117f59f6a">

Moreover, setting `echo: false` in the source cell causes preview to throw an error:
```
Rendering qmd embeds
[1/1] index.qmd

Executing 'index.ipynb'
  Cell 1/1: 'fig-index-plot'...Done

ERROR: The cell fig-index-plot does not exist in notebook

Stack trace:
    at file:///Applications/quarto/bin/quarto.js:69687:23
    at Array.map (<anonymous>)
    at notebookMarkdown (file:///Applications/quarto/bin/quarto.js:69684:40)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async replaceNotebookPlaceholders (file:///Applications/quarto/bin/quarto.js:69628:32)
    at async renderPandoc (file:///Applications/quarto/bin/quarto.js:69987:28)
    at async Object.onRender (file:///Applications/quarto/bin/quarto.js:77261:36)
    at async renderFileInternal (file:///Applications/quarto/bin/quarto.js:77238:17)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:77062:17)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:77389:25)
```

1. Is it possible to include figures (but not code) from other qmd files?
2. Is it possible to hide the code in the source qmd file?

Here's a repo with a minimal working example, and also quarto version I'm using:
- [github repo](https://github.com/mpf/quarto-mwe.git)
- Quarto version 1.4.549

</div>

**Comment by mcanouil** [comment]
Note that this seems specific to Julia as, the same code using knitr/R or Jupyter/Python did give the expected results.

**Comment by cscheid** [comment]
> `#| echo: true  # <-- preview throws error if 'false'`

I can't repro this part; can you clarify?

**Comment by dragonstyle** [comment]
(Note as I fix this - the issue is caused when `echo` is explicitly set on a cell, this is overriding the overall echo behavior that we rely upon internally when generating an ipynb to provide the source of the embed. We need to override this value, when explicitly set. If the value is omitted altogether, our behavior is all good. This behavior reproduces for any Jupyter kernel, not just Julia)

The workaround for now is to omit `echo` from notebooks that provide embeds. You can control the `echo` behavior within the host page like so:

```
{{< embed notebook.qmd#fig-index-plot echo=true >}}
```

I'll work to fix this but just in the meantime.
