### ISSUE TITLE
Jupyter notebook non-adjacent stream outputs rendered as a group

### ISSUE THREAD

**Issue by loneguardian** [quarto-dev/quarto-cli#8473]
## Bug description

Currently Quarto-rendered Jupyter notebook has their stream outputs grouped up regardless of other output within the same code cell.

### Background

I managed to come across the following issue and PR, which I believe is the cause to the behaviour.

* Issue: #4968
* PR: https://github.com/quarto-dev/quarto-cli/pull/5042
* Commit: https://github.com/quarto-dev/quarto-cli/commit/5ca37a380466b974669ac0c4346b79c7fbd1c672

Upon examining [the code as of today](https://github.com/quarto-dev/quarto-cli/blob/312912c165a51f82f8fd0ba6b5f8e6f850294a90/src/core/jupyter/jupyter-fixups.ts#L17), I noticed that the stream outputs for a code cells are being merged without checking whether there are anything in between the streams.

### Steps to reproduce

Code a cell that outputs:

1. stdout print
2. a table
3. stdout print

[Minimal reproducible example repo is here](https://github.com/loneguardian/quarto-cli-issue-8473)

### Expected behavior

Rendered output should show

1. stdout print
2. a table
3. stdout print

### Actual behavior

Currently quarto renders it as

1. stdout print
2. stdout print
3. a table

### Your environment

- Quarto: 1.4.549  
- OS: Windows 10 x64  
- IDE: VSCode 1.85.2

### Quarto check output

```
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: Installation From Path     
      Path: [redacted]\texlive\2022\bin\win32   
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.1 (Conda)
      Path: [redacted]/python.exe
      Jupyter: 5.5.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: [redacted]/R/R-43~1.1
      LibPaths:
        - [redacted]/AppData/Local/R/win-library/4.3
        - [redacted]/Program Files/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.23

[>] Checking Knitr engine render......OK
```

### 2: Fix `fixupStreams()`

I propose the following pseudocode:

When `output.output_type === "stream"` is found, the function should only match with the next `output` if it has a similar `output_type && name`, until it fails to find one.

I have initiated a [pull request](https://github.com/quarto-dev/quarto-cli/pull/8477) for this.

---

Edit 1: Add [minimal reproducible example repo](https://github.com/loneguardian/quarto-cli-issue-8473)
Edit 2: Add proposed fix [pull request](https://github.com/quarto-dev/quarto-cli/pull/8477)

**Comment by mcanouil** [comment]
Are you talking about something similar to?
- https://github.com/quarto-dev/quarto-cli/issues/8179

**Comment by loneguardian** [comment]
> Are you talking about something similar to?
> 
> * [Code cells of different languages are wrongly merged when inside a layout #8179](https://github.com/quarto-dev/quarto-cli/issues/8179)

I do not think so, I think it is an entirely different issue.

**Comment by cderv** [comment]
@loneguardian I do think your issue is fixed. Not sure what fixed it but the document I get has the expected behavior described
![Image](https://github.com/user-attachments/assets/93626eac-ac32-4bb5-9dfa-c267d090806e)

Can you confirm with latest 1.6 pre-release ? 

Thank you

**Comment by loneguardian** [comment]
> Can you confirm with latest 1.6 pre-release ?

I have only checked with 1.5.57 and yes, the issue appears to be fixed.

> I do think your issue is fixed. Not sure what fixed it but the document I get has the expected behavior described

I checked the git blame for the said function, seems like https://github.com/quarto-dev/quarto-cli/commit/ad39413e9c2e30fb59a297ff34150ee60a49c767 fixed the issue.

**Comment by cscheid** [comment]
@loneguardian thank you for confirming! I'm going to go ahead and close this.
