### ISSUE TITLE
Code within a bullet list does not show correctly in HTML when the code block is indented

### ISSUE THREAD

**Issue by aster-hu** [quarto-dev/quarto-cli#8480]
### Bug description

If the code block is indented within a bullet list and if there isn't a line break, the block shows incorrectly as if it's inline code in the output HTML:

**Input**:
```md
1.  The code block does not show correctly when the code block is indented without a linebreak.
    ```r
       library(dplyr)
       library(tidyr)
    ```
```

However, it shows correctly when the code is not indented:

**Output**:
![Screenshot 2024-01-28 at 5 09 48 PM](https://github.com/quarto-dev/quarto-cli/assets/29766504/88e53f26-e28d-4e87-a33e-71e11b48e884)



### Steps to reproduce

Create a website with quarto and then put the following text in a .md or .qmd file:

```md
1.  The code block does not show correctly when the code block is indented without a linebreak.
    ```r
       library(dplyr)
       library(tidyr)
    ```
2.  It does work when the code is not indented.
```r
library(dplyr)
library(tidyr)
```
```

### Expected behavior

The code block should show normally even when it's indented.

### Actual behavior

The code block shows as if it's inline code.

### Your environment

- Quarto version: 1.4.449
- MacOS Ventura 13.6.3

I'm not using RStudio for this particular activity. I run the command in terminal.

### Quarto check output

Quarto 1.4.449
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.449
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.16 (Conda)
      Path: /Users/aster/opt/anaconda3/bin/python
      Jupyter: 5.2.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
That's not a bug.
Code blocks should have empty lines before and after.

**Comment by cderv** [comment]
For reference, this is explained clearly in Pandoc's Manual (https://pandoc.org/MANUAL.html#block-content-in-list-items)
> A list item may contain multiple paragraphs and other block-level content. However, subsequent paragraphs must be preceded by a blank line and indented to line up with the first non-space content after the list marker.

In our doc (https://quarto.org/docs/authoring/markdown-basics.html#lists), this is shown by example 2 

````markdown
*   item 2

    Continued (indent 4 spaces)
````

We could probably add something in our Quarto documentation about list regarding block content in list. We only show different type of list for now 


> I don't know if some markup validation are in place in RStudio and VSCode extension for this.

@aster-hu as often with Markdown syntax questions / issues, using Visual Editor in RStudio (https://quarto.org/docs/visual-editor/) or VSCODE (https://quarto.org/docs/visual-editor/vscode/)

Switching from source mode to visual mode helps see the difference. Editing in visual mode insure always proper syntax. 

Sharing in case it helps
