### ISSUE TITLE
Problems from version 1.4.542 upwards: rendering empties the docs folder

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#8481]
### Bug description

Hi,
I had version 1.4.536 and upgraded it to 1.4.549.

Today I gave `quarto render` on a project I am working on, where the output folder is `docs`. As soon as I launch the command, the `docs` folder empties.

And the same happens if I launch `quarto preview` on the same project: I open the preview URL and I have "file not found" error.

There was something strange, because I had already worked in that project without any problems, so I thought it depended on the update. 
So I downgraded, one release at a time. And each time I would launch the render again. Until I got to version 1.4.541, I still have the same problem: the `docs` folder empties.

### Steps to reproduce

Currently I cannot share anything, because it is a project that I cannot make public because it contains confidential data. Tomorrow I hope to share a site where I can replicate it.

### Expected behavior

To have the rendering of the project, without leaving the docs folder empty.

### Actual behavior

I have the empty docs folder after rendering.

### Your environment

- VSCode
- debian 11

### Quarto check output

```
Quarto 1.4.541
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.541
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2020

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /usr/bin/python3
      Jupyter: 5.3.2
      Kernels: bash, python3

(|) Checking Jupyter engine render....Could create runtime directory for jupyter transport.
This is possibly a permission issue in the environment Quarto is running in.
Please consult the following documentation for more information:
https://github.com/quarto-dev/quarto-cli/issues/4594#issuecomment-1619177667
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
When you cannot share, create a small reproducible example.
For instance:
1. `quarto create project website`
2. `mkdir custom-directory`
3. Add under `project`, `output-dir: custom-directory`
4. `quarto render`
5. `touch custom-directory/keep-this.txt`
6. `quarto render`

`custom-directory/keep-this.txt` is no longer there.

Note that I do not believe this to be a bug.
This ensure you do not have artefacts from previous build.
If you want to have other resources in the output directory, then use `resources` to list additional resources, see <https://quarto.org/docs/websites/website-tools.html#site-resources>.

**Comment by dragonstyle** [comment]
A couple of notes:

- In general, `quarto render` of a project does default clean the `output-dir`- this is expected behavior.
- It looks like our only real change between .541 and .542 has to with reverting our attempts at support only a negation glob in the render list. If you're relying upon this in your project, it isn't working as adding support for that created too many other issues, so we ended up reverting that.

**Comment by aborruso** [comment]
Hi @dragonstyle and thank you very much

> * It looks like our only real change between .541 and .542 has to with reverting our attempts at support only a negation glob in the render list. If you're relying upon this in your project, it isn't working as adding support for that created too many other issues, so we ended up reverting that.

In my `_quarto.uml` I have 

```
project:
  type: website
  output-dir: docs
  resources: "immagini/grid-ph.jpg"
  render:
  - "!note.md"
 ```

If I understand correctly, what is causing problems is ` - "!note.md"`.

However, I did not understand what I need to do. Will you update the 1.4 and I will not have this problem with the updated version?

Thanks again

**Comment by cderv** [comment]
> However, I did not understand what I need to do. Will you update the 1.4 and I will not have this problem with the updated version?

You need to update your YAML so that you include every files before using the negation. 

This is mentioned in https://quarto.org/docs/projects/quarto-projects.html#render-targets briefly 
> You can also use the prefix ! to ignore some files or directories in the render list. Note that in that case you need to start by specifying everything you do want to render

> Will you update the 1.4 and I will not have this problem with the updated version?

We won't update 1.4 to support negation first. We tried in 1.4 but it failed. We'll probably solve this for 1.5 after thorough testing !

**Comment by aborruso** [comment]
Thank you very much
