### ISSUE TITLE
accented character (e.g. `à`) in shortcode raises error `pandoc: Cannot decode byte '\xc3': Data.Text.Encoding: Invalid UTF-8 stream` in v.1.4.549

### ISSUE THREAD

**Issue by kompre** [quarto-dev/quarto-cli#8485]
### Bug description

Hello,

upgrading from 1.3.450 to 1.4.549, a document that rendered fine in the earlier version, now raises the following error:

`pandoc: Cannot decode byte '\xc3': Data.Text.Encoding: Invalid UTF-8 stream`

after some investigation, I was able to pinpoint the cause to an accented character present in a shortcode, like so:

```
{{< meta classe_rugosità>}}
```

The issue seems to be only in the source file (qmd), because the presence of an accented character in the yaml doesn't seems to bother it.

I'm using accented character in the yaml because my language has them, so it' nicer to be able to define yaml keys in my natural language (italian).

### Steps to reproduce

Here the minimal working example that produce the error:

```qmd
---
title: "enconding "
format: pdf
---

this shortcode will raise a encoding erro on 1.4.549

{{< meta classe_rugosità >}}
```

### Expected behavior

The presence of "special character" in shortcode shouldn't raise an error. Should work  like it was in the 1.3.450 version

### Actual behavior

rendering of document fails before starting with error message:

`pandoc: Cannot decode byte '\xc3': Data.Text.Encoding: Invalid UTF-8 stream`

### Your environment

- vscode 1.85.2
- win 10 pro v. 10.0.19045
- quarto v. 1.4.549
- quarto vscode extension v1.110.1

### Quarto check output

```bash
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\xxx\AppData\Local\Programs\Quarto\bin
      CodePage: unknown

[>] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\xxx\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: C:/Users/xxx/AppData/Local/Programs/Python/Python312/python.exe
      Jupyter: 5.7.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment]
This [pandoc upstream issue](https://github.com/jgm/pandoc/issues/9385) is part of the problem, and the reason we don't get a useful stack trace. I'm now investigating how we get a bad UTF-8 string to begin with.
