### ISSUE TITLE
Mermaid flowchart text overflows nodes when format is revealjs (but works when format is html)

### ISSUE THREAD

**Issue by schwa021** [quarto-dev/quarto-cli#8488]
### Bug description

When I create a flowchart with mermaid in revealjs, the text overflows the nodes
When I render the same qmd file as html, the flowchart looks fine
Changing the fig-width does not alter the behavior - it simply scales everytihng up/down

### Steps to reproduce
````qmd
---
title: "Test"
format: revealjs

---

## Mermaid Flowchart

```{mermaid}
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```
````

### Expected behavior

a pretty chart with text contained in nodes

### Actual behavior

an ugly chart with text overflowing nodes

![image](https://github.com/quarto-dev/quarto-cli/assets/25011558/7088dfd4-56ac-4321-9173-39f9ed53ab29)

Note that if I change format: revealjs to format:html (no other changes), then I get the pretty chart I want

![image](https://github.com/quarto-dev/quarto-cli/assets/25011558/f79cdd9d-72ce-45a9-ace4-947fd439c9fb)

### Your environment

RStudio 2023.12.0+369 "Ocean Storm" Release (33206f75bd14d07d84753f965eaa24756eda97b7, 2023-12-17) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.0+369 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

Edition	Windows 10 Pro
Version	22H2
Installed on	‎8/‎7/‎2021
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Quarto check output

![image](https://github.com/quarto-dev/quarto-cli/assets/25011558/65925f71-4ae9-4ddd-84c2-1bdd5d1bc70e)

**Comment by mcanouil** [comment]
Could you properly format your code? You need to enclose it with four backticks ` ```qmd `.

**Comment by schwa021** [comment]
It looks similar to what you produced in response to issue #7156 (https://github.com/quarto-dev/quarto-cli/issues/7156)

https://github.com/quarto-dev/quarto-cli/issues/7156#issuecomment-1751172867

**Comment by cscheid** [comment]
I think what's happening here is that mermaid tries to resolve font metrics and compute its layout before some dynamic styles are resolved in revealjs.

**Comment by schwa021** [comment]
> I think what's happening here is that mermaid tries to resolve font metrics and compute its layout before some dynamic styles are resolved in revealjs.

Forgive me for my **ignorance**. I'm just a poor research who struggles to understand all the programming aspects of how these amazing magical things - html, css, Rstudio, quarto, etc... - all work together.

Am I supposed to read your comment as a solution? Is there something I can implement or circumvent? Are you suggesting some action I can take to solve this?

**Comment by cscheid** [comment]
> Am I supposed to read your comment as a solution? Is there something I can implement or circumvent? Are you suggesting some action I can take to solve this?

Nothing of the sort - I'm simply trying to diagnose the issue out loud so we can determine whether it's something we can solve on our end or not.

In terms of an immediate workaround, you might be able to use `mermaid-format: png` so that Quarto attempts to render it ahead of time as a PNG file. This is not ideal, because we can't then use all the theming options that would otherwise be available. But you might find that acceptable:

````
---
title: "Test"
format: revealjs
---

## Mermaid Flowchart

```{mermaid}
%%| mermaid-format: png
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```
````

**Comment by schwa021** [comment]
Got it. Thank you for the explanation. 

As I alluded to - I hack my way through and generally get really useful results from quarto, but I don't always understand the lingo here, and periodically get scolded for using the wrong terms, formatting incorrectly, etc.. I couldn't tell if you were giving a solution or "_diagnos[ing] out loud_".

At the same time - I want to be clear that I am **constantly amazed at and appreciative** of how useful these **FREE** products and support are for me. I fully understand that it is not always practical to explain things down to an "_idiot proof_" level.

For example - the mermaid-format: png works beautifully. But I don't actually know what theming options I'm missing out on. Ignorance is bliss, I suppose, and I'll use that for now, and watch this space for a "real" solution.

**Comment by mcanouil** [comment]
This feature: https://quarto.org/docs/authoring/diagrams.html#mermaid-theming

**Comment by cscheid** [comment]
The issue, simply, is that the width of the screen needs to be big enough. If I maximize my browser window, I get this:

<img width="633" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/b52074ac-7903-48b3-ba9e-68d65cc733b5">

In a narrower window, I get this:

<img width="416" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/a818300f-0efe-408f-a40f-599c7863bf07">

I still don't understand why this only happens in the revealjs format.
