### ISSUE TITLE
markdown markup in tables not rendered with quarto

### ISSUE THREAD

**Issue by JulienGAMartin** [quarto-dev/quarto-cli#8493]
### Bug description

Table including markdown code are not rendered correctly.

For ex

### Steps to reproduce

Here is a small quarto file to reproduce the problem
`format="html"` for the kable function is needed to use kableExtra styling after

````qmd
---
title: "Markdown link not rendered"
format: html
---


```{r}
#| echo: false
dat <- data.frame(week = c(1, 2), links = c("[quarto site](https://quarto.org/)", "[quarto site](https://quarto.org/)"))
knitr::kable(dat, format = "html")
```
````

### Expected behavior

I expect the table to show two clickable link to the quarto website

<table>
 <thead>
  <tr>
   <th style="text-align:right;"> week </th>
   <th style="text-align:left;"> links </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:left;"> <a href="https://quarto.org/">quarto site</a></td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:left;"> <a href="https://quarto.org/">quarto site</a></td>
  </tr>
</tbody>
</table>

### Actual behavior

links in table are in markdown markup and not rendered

here is what I obtain

<table>
 <thead>
  <tr>
   <th style="text-align:right;"> week </th>
   <th style="text-align:left;"> links </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:left;"> [quarto site](https://quarto.org/) </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:left;"> [quarto site](https://quarto.org/) </td>
  </tr>
</tbody>
</table>

### Your environment

- IDE: VSCode 1.85.2
- OS: Ubuntu 22.04LTS

### Quarto check output

Quarto 1.4.544
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.544
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib/R
      LibPaths:
        - /home/julien/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
```
knitr::kable(dat, format = "html")
```

You've requested html format, so you can't use Markdown in it.

**Comment by cscheid** [comment]
If you want to combine HTML and Markdown, the best approach at the moment is to use the [GT package](https://gt.rstudio.com/). Kable would probably need to be updated to support that usage.

**Comment by JulienGAMartin** [comment]
Well the exact same code and file file with an Rmd extension knitted with rmarkdown would render correctly. When using the qmd extension and rendered with quarto, it does not work anymore. So I was just expecting code to work similarly.

**Comment by cscheid** [comment]
> Well the exact same code and file file with an Rmd extension knitted with rmarkdown would render correctly.

Quarto is not meant to be an exact clone of RMarkdown, and it needs to be more careful about HTML + Markdown mixing.

With that said, you can do that in GT handily:

````
---
title: markdown + html
---

```{r}
#| warning: false

library(gt)
library(dplyr)

dplyr::tribble(
  ~Markdown, ~text,
  "[Quarto](https://quarto.org)",   "[Quarto](https://quarto.org)",
) |>
  gt() |>
  fmt_markdown(columns = c("Markdown"))
```
````

<img width="689" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/23e06385-c186-47a4-8a7a-bf67e09fdad7">

**Comment by cscheid** [comment]
To expand on this:

If you look at the output being emitted by kable (using `keep-md: true`), you get this:

``````
---
title: "Markdown link not rendered"
format: html
keep-md: true
---


::: {.cell}
::: {.cell-output-display}

`````{=html}
<table>
 <thead>
  <tr>
   <th style="text-align:right;"> week </th>
   <th style="text-align:left;"> links </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:left;"> [quarto site](https://quarto.org/) </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:left;"> [quarto site](https://quarto.org/) </td>
  </tr>
</tbody>
</table>

`````

:::
:::
``````

It's impossible for quarto to know whether you meant the _text_ `[quarto site](https://quarto.org/)` in HTML or you meant "the Markdown that would be a link otherwise". `[quarto site](https://quarto.org/)` is actually completely valid HTML, so we quarto is rendering precisely what kable asked.

**Comment by JulienGAMartin** [comment]
Thanks a lot for all the info. I will use gt now
