### ISSUE TITLE
Untrusted jupyter notebook when using JS for hugo format

### ISSUE THREAD

**Issue by linogaliana** [quarto-dev/quarto-cli#850]
Hi, once again thanks a lot for `quarto` which is an excellent tool.

I tried to use `folium` with `quarto` to build a `Python` course website. The output format is `hugo`.  Instead of the map the python block should have produced, this message appeared:

> Make this Notebook Trusted to load map: File -> Trust Notebook<iframe srcdoc="<!DOCTYPE html> <head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />

This is a typical Jupyter security message as stated in the [doc](https://jupyter-notebook.readthedocs.io/en/latest/notebook.html?highlight=trust#signing-notebooks). 

I put a minimal reproducible exemple at the end of the _issue_ based on `folium` documentation to show how to recreate the problem.

Is there some way, behind the stage, to make jupyter trust all sessions launched by quarto ?

What is surprising is that this behavior does not happen when using `html` output

## Reprex

Let's create a file `example.qmd` :

~~~markdown
---
title: "Plotly example"
html: default
---

```{python}
import folium
m = folium.Map(location=[45.5236, -122.6750])
```

```{python}
m
```
~~~

When using `quarto render example.qmd --to html`, no problem at all. Map is visible. 

When using `quarto render example.qmd --to hugo`, instead of the map we have the `Make this Notebook Trusted to load map` (and lot's of misformed content I don't understand)

I also tried to replace the printing of the map using `m` by

~~~markdown
```{python}
#| include: false
#| eval: false
map = m._repr_html_()
```

```{python}
#| echo: false
#| output: asis
#| eval: false
print(map)
```
~~~
(which was my R Markdown way of doing) but the result is the same

Update: it works as expected for `ipynb` output. Problem is really for `hugo` format

**Comment by jjallaire** [comment]
This works fine for in Hugo so long as I've followed the instructions to enable HTML output in Hugo (see https://quarto.org/docs/output-formats/hugo.html#site-config)

Here is my `config.toml`:

```toml
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"

ignoreFiles = [ "\\.qmd$", "\\.ipynb$" ]

[markup.goldmark.renderer]
unsafe= true
```

**Comment by linogaliana** [comment]
I tested in local and indeed I did not face that problem. I am going to further inquire on this subjevt (but my guess is that it is related to the fact I was building the qmd->md from github actions but used a different machine to run `hugo serve`)

**Comment by linogaliana** [comment]
found that the problem was my academic theme that was not digesting well raw html. Solved the issue that is not quarto related
