### ISSUE TITLE
[PDF] Cross referencing code blocks disables syntax highlighting

### ISSUE THREAD

**Issue by joelvonrotz** [quarto-dev/quarto-cli#8519]
### Bug description

Hello

I've noticed when cross referencing code blocks, they lose their syntax highlighting. I don't know why it would have the syntax highlighting removed. Is it a pandoc thing or is this handled via Quarto?

### Steps to reproduce

Render following Quarto document

````qmd
---
title: syntax
format: pdf
---

```cpp
int8_t hello;

void main(void) {
  hello = 1;

  while(true) {
    hello++;
    if(hello=10) {
      hello = 0;
    }
  }
}
```

```{#lst-hello .cpp lst-cap="hello"}
int8_t hello;

void main(void) {
  hello = 1;

  while(true) {
    hello++;
    if(hello=10) {
      hello = 0;
    }
  }
}
```

Referencing @lst-hello now.
````

### Expected behavior

Both code blocks have syntax highlighting (both code blocks use the `Shaded` and `Highlighting` environment). The cross referenced code block is contained in the `codelisting` float-environment.

![image](https://github.com/quarto-dev/quarto-cli/assets/41155337/7a20cfdc-8851-4c05-9c3d-1ad6dba65f91)

### Actual behavior

The referenced code block uses a `verbatim` environment, but is contained in the `codelisting` float-environment.

![image](https://github.com/quarto-dev/quarto-cli/assets/41155337/103706ec-2622-4ba0-aa8a-6c1d42dfbafc)

```latex
% here is a normal code block
\begin{Shaded}
\begin{Highlighting}[]
\DataTypeTok{int8\_t}\NormalTok{ hello}\OperatorTok{;}

\DataTypeTok{void}\NormalTok{ main}\OperatorTok{(}\DataTypeTok{void}\OperatorTok{)} \OperatorTok{\{}
\NormalTok{  hello }\OperatorTok{=} \DecValTok{1}\OperatorTok{;}

  \ControlFlowTok{while}\OperatorTok{(}\KeywordTok{true}\OperatorTok{)} \OperatorTok{\{}
\NormalTok{    hello}\OperatorTok{++;}
    \ControlFlowTok{if}\OperatorTok{(}\NormalTok{hello}\OperatorTok{=}\DecValTok{10}\OperatorTok{)} \OperatorTok{\{}
\NormalTok{      hello }\OperatorTok{=} \DecValTok{0}\OperatorTok{;}
    \OperatorTok{\}}
  \OperatorTok{\}}
\OperatorTok{\}}
\end{Highlighting}
\end{Shaded}

% here is the cross referenced code block
\begin{codelisting}
\caption{\label{lst-hello}hello}
\centering{
  \begin{verbatim}
  int8_t hello;
  
  void main(void) {
    hello = 1;
  
    while(true) {
      hello++;
      if(hello=10) {
        hello = 0;
      }
    }
  }
  \end{verbatim}
}
\end{codelisting}%
```

### Your environment

**Visual Studio Code**

Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

### Quarto check output

```bash
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\Joel\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.03.21
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Joel\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: C:/Users/Joel/AppData/Local/Programs/Python/Python312/python.exe
      Jupyter: 5.7.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.2
      Path: C:/PROGRA~1/R/R-42~1.2
      LibPaths:
        - C:/Users/Joel/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.2/library
      knitr: 1.41
      rmarkdown: 2.20

[>] Checking Knitr engine render......OK
```

**Comment by joelvonrotz** [comment]
Oh shoot, didn't know about this at all. Thank you very much for your response and the provided solution. After rereading the cross reference page on the Quarto doc, it does mention the fenced div solution.

Would it make sense to extend the code listing cross reference documentation part to describe why it would make sense to use one over the other?

**Comment by cscheid** [comment]
> Would it make sense to extend the code listing cross reference documentation part to describe why it would make sense to use one over the other?

I understand where you're coming from, but no - the traditional listings from RMarkdown and plain LaTeX tend to not be highlighted, and our default document class is conservative by default. This would dilute the documentation, and once you internalize the rules of composition in Quarto, these techniques should come naturally. (We should, instead, have a separate discussion about documenting these rules of composition. I agree with you that we need a document that teaches people. We're working on it).

**Comment by joelvonrotz** [comment]
That's understandable! Thanks again for your help!
