### ISSUE TITLE
action-links are not shown if page has not toc

### ISSUE THREAD

**Issue by nichtich** [quarto-dev/quarto-cli#852]
action-links [are not shown](https://github.com/quarto-dev/quarto-cli/blob/e1a9c37d251be33c9828a8c861dd8ffa64b3d7c4/src/project/types/website/website-navigation.ts#L553) if the current page has no table of contents, e.g. because it contains no sub-headings.

**Comment by huntley-link** [comment]
Appears to be the same or similar issue as #691

**Comment by blacksqr** [comment]
Appears to be the same or similar issue as #691

**Comment by nichtich** [comment]
Yes, duplicate of #691
