### ISSUE TITLE
runtime.txt does not get generated from `quarto use binder`

### ISSUE THREAD

**Issue by libjohn** [quarto-dev/quarto-cli#8524]
### Bug description

I'm looking at this page:  https://quarto.org/docs/projects/binder.html

I may not have read all of that page, but I've run `quarto use binder` on about five GitHub repos.  And the runtime.txt file **never** gets created.  The text of the page  (url above) indicates, "if you continue, quarto will list the files it will create"

`runtime.txt` is one file that is reported to be created.

Again, none of my five tests has found the runtime.txt file created.  Again, I may have missed steps but I think I'm doing it properly because I can add that runtime.txt file and then everything seems fine.  

So, just in case this feedback is helpful.  Manually adding the runtime.txt file seems to make everything work just fine but it seems like the "quarto use binder" procedure is missing a documented step.

Cheers.

### Steps to reproduce

   console: renv::init()
   console:  renv::snapshot()
   terminal: quarto use binder

### Expected behavior

has a runtime.txt file consisting of the R runtime information

Then, https://mybinder.org/v2/gh/<<my github ID>>/<<my GitHub repo>>/HEAD?urlpath=rstudio

### Actual behavior

Does not have a runtime.txt file (should be r-4.3.1-2023-06-16)

### Your environment

RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-28) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎10/‎11/‎2023
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Quarto check output

$ quarto check
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\jrl\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\jrl\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/Users/jrl/AppData/Local/Programs/R/R-4.3.1
      LibPaths:
        - C:/Users/jrl/Documents/refq_fgsea/renv/library/R-4.3/x86_64-w64-mingw32
        - C:/Users/jrl/AppData/Local/R/cache/R/renv/sandbox/R-4.3/x86_64-w64-mingw32/cec413b1
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
I can't reproduce the claim that `runtime.txt` would be created:

````
quarto use binder
Determining configuration
[✓] Detected Project configuration:

    Quarto       most recent prerelease
    JupyterLab   default
    Engine       markdown
    Editor       vscode

The following files will be written:
┌───────────┬─────────────────────────────────────────────────┐
│ postBuild │ Configures Quarto and supporting tools          │
├───────────┼─────────────────────────────────────────────────┤
│ .jupyter  │ Configures JupyterLab with necessary extensions │
├───────────┼─────────────────────────────────────────────────┤
│ apt.txt   │ Installs Quarto required packages               │
└───────────┴─────────────────────────────────────────────────┘

 ? Continue? (Y/n) ›
````

We should make sure our documentation explains this situation better.

**Comment by cwickham** [comment]
With the addition of a `renv.lock` file I get:
```
quarto use binder
Determining configuration
[✓] Detected Project configuration:

    Quarto       most recent prerelease
    JupyterLab   default               
    Engine       markdown              
    Editor       vscode                
    Environments renv.lock             

The following files will be written:
┌───────────┬────────────────────────────────────────────────────┐
│ install.R │ Activates the R environment described in renv.lock │
├───────────┼────────────────────────────────────────────────────┤
│ postBuild │ Configures Quarto and supporting tools             │
├───────────┼────────────────────────────────────────────────────┤
│ .jupyter  │ Configures JupyterLab with necessary extensions    │
├───────────┼────────────────────────────────────────────────────┤
│ apt.txt   │ Installs Quarto required packages                  │
└───────────┴────────────────────────────────────────────────────┘
```

Which adds `install.R` which sort of implies there should be a `runtime.txt`, right? 

I set up this project with no files that actually use R, i.e. no `.qmd` that has an executable R code chunk. As soon as I add one, `runtime.txt` is created.

**Comment by cwickham** [comment]
Also, I don't get a `runtime.txt` if there are R script files (but no Quarto files with executable R code). With the addition of script rendering, I feel like this is a bug, not just a documentation issue.
