### ISSUE TITLE
More informative error for trailing `-`s on top of document above YAML

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#8532]
This can be reproduced by adding 4+ `-`s on top of any otherwise functional Quarto document. Is emitting a more informative error feasible here?

This is with 1.4.549.

<img width="1624" alt="Screenshot 2024-01-31 at 10 24 01 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/708e2986-b135-464c-8eb2-c600c1a0467b">

**Comment by cscheid** [comment]
Yeah, the error message here is super unfortunate.

(The true underlying problem is we don't have a syntax checker for valid syntax, and this means we continuously play a game of error-message whack-a-mole when the input is not what we expect it to be.)

**Comment by mcanouil** [comment]
May I suggest to add YAML in the sentence to make sure what it is about?

```sh
ERROR: Expected YAML front matter to have at least 3 lines in 8532.qmd
```
