### ISSUE TITLE
Rendering html book image-folder not created

### ISSUE THREAD

**Issue by Juuso1** [quarto-dev/quarto-cli#8537]
### Bug description

I updated new versio of Quarto (latest) and use same code to generate html book. Everthing works fine except cover image don´t show up. Looking for solution I noticed that there is no image folder? 

OLD CODE (not working anymore?)
format:
  html: 
    cover-image: themes/images/front/Front071.png

### Steps to reproduce
**Step 1:** quarto render 

**_quarto.yml file below**

````qmd
project:
  type: book
  output-dir: kirjat/tilannekuva/
lang: fi
bibliography: references.bib
number-sections: true
editor: visual  
execute:
  echo: false
  warning: false
  cache: true


book:
  title: "{{< var general.title >}}"
  author: "{{< var general.city >}}"
  date: today
  date-format: "DD-MM-YYYY"
  page-navigation: true
  cover-image: themes/images/front/Front071.png
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  search:
    location: sidebar
    type: overlay
  sidebar:
    collapse-level: 3
    pinned: false

  chapters:
    - index.qmd
    - asuminen.qmd
    
  appendices:
    - lahteet.qmd

  page-footer:
    center: 
      - text: "{{< var general.license >}} {{< var general.year >}}, {{< var general.copyright >}}"

format:
  html: 
    cover-image: themes/images/front/Front071.png
    code-link: true
    pagetitle: "{{< var general.title >}} {{< var general.year >}}"
    keywords: "{{< var general.keywords >}}"
    copyright: "{{< var general.copyright >}}"
    license: "{{< var general.license >}}"
    description-meta: "{{< var general.description_meta >}}"
    author-meta: "{{< var general.author_meta >}}"

````
### Expected behavior

Normally image folder and Front071.png image is created automatic while rendering book. Cover-image shows up in index.html

### Actual behavior
No image folder and no image Front071.png

### Your environment
latest R-Studio and latest Quarto [quarto-1.4.549-win.msi](https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.549/quarto-1.4.549-win.msi)

### Quarto check output
Everything is OK

**Comment by mcanouil** [comment]
@Juuso1 Please fill in properly and completely the issue template. If you don't, we won't be able to help you. Thanks!

**Comment by Juuso1** [comment]
> @Juuso1 Please fill in properly and completely the issue template. in particular, we need code we can use to reproduce the issue. If you don't, we won't be able to help you. Thanks!

I modified response

**Comment by Juuso1** [comment]
> @Juuso1 Please fill in properly and completely the issue template. in particular, we need code we can use to reproduce the issue. If you don't, we won't be able to help you. Thanks!

@MickaelCanouil now added

**Comment by mcanouil** [comment]
There is no code provided and no description of the steps to reproduce.

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Comment by Juuso1** [comment]
> There is no code provided and no description of the steps to reproduce.
> 
> Also please format your post using markdown, for instance, use code blocks for code.
> 
> Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.
> 
> You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four `` ```` ``).
> 
> ```
> ````qmd
> ---
> title: "Reproducible Quarto Document"
> format: html
> engine: knitr
> ---
> 
> This is a reproducible Quarto document using `format: html`.
> It is written in Markdown and contains embedded R code.
> When you run the code, it will produce a plot.
> 
> ```{r}
> plot(cars)
> ```
> 
> ![A placeholder image](https://placehold.co/600x400.png)
> 
> The end.
> ````
> ```

@mcanouil added quarto.yml file

**Comment by Juuso1** [comment]
@mcanouil added yml-file

**Comment by cscheid** [comment]
We need a full example, especially since we need the image to be able to check. Please share a zip file with the entire repro or a github repository. Thank you.
