### ISSUE TITLE
About page behaviour changed between 1.4.533 and 1.4.534

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8544]
It appears between 1.4.533 and 1.4.534, the elements of "about" is no longer respecting the position defined by the use of the id of the about element.
Moving the fenced div around has no effect.

Reproducible example at: https://github.com/mcanouil/quarto-issues-experiments/tree/main/quarto-cli-8544

| v1.4.533 | v1.4.534 |
|--------|--------|
| <img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/d433cf4f-1c87-4100-a9ed-882cc01ca9c1"> | <img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/9cbc7f89-cca6-47a8-a458-ff7ca8cc9270"> | 

If you put the whole "content" in a fenced div, everything stays together but still on top of the about element.

<img width="600" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/64d981df-a51e-4ebb-a17f-278f55c47d3f">

**Comment by mcanouil** [comment]
Side note: the "content" is not inside the fenced divs on purpose.

| Aim/before | if inside the div |
|--------|--------|
| <img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/d60c51a2-90a8-42d9-9c73-f1a418505372"> | <img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/3ae170fa-4414-41a9-a267-5ffde4ebd05e"> |

**Comment by mcanouil** [comment]
I found a fix (#8753) (cc @dragonstyle)

**Comment by dragonstyle** [comment]
I believe this is now fixed as of:

https://github.com/quarto-dev/quarto-cli/commit/0128bfa184e3be29b67e421cfffc50f8306fb326
