### ISSUE TITLE
css style sheet appears to be ignored in v 1.4?

### ISSUE THREAD

**Issue by pgseye** [quarto-dev/quarto-cli#8548]
### Bug description

I noticed on an existing blog that I update weekly, that the colour I had set my post headers to on the blog landing page was gone and the headers were just a plain black colour. I'm not sure if this has got anything to do with the upgrade to Quarto version 1.4?

### Steps to reproduce

I also tested this by creating a new Quarto blog and replacing the exisiting styles.css file with a new one that contained the following code:

```
/* css styles */

h1, h2, h3, h4 {
  color: #1f7de6;
}
```

### Expected behavior

I would expect the headings would be a shade of blue in colour.

### Actual behavior

The headings remain black.

### Your environment

- IDE: Rstudio: 2023.12.1+402
- OS: Mac Sonoma: 14.3

### Quarto check output

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OKQuarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by pgseye** [comment]
I can confirm that the colours were reproduced in v 1.0.28 (as my laptop was running that). I then updated my laptop to version 1.4.549 and the colours seemed to be dropped again.

**Comment by cscheid** [comment]
I can't reproduce this. Adding 

````
/* css styles */
h1, h2, h3, h4 {
    color: green;
  }
````

to `styles.css` and running preview yields this:

<img width="518" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/ffced1f0-889d-4089-8b42-471dcc3629aa">

**Comment by pgseye** [comment]
Thank you.

Yes, it seems to also work for me in reproducing the correct colour when I create a new Quarto Website, but not when I create a new Quarto Blog. Does a blog also work for you? If so, then it must be at my end, but that is strange, as all I am doing is literally creating a new blog project from the menu, replacing the styles.css file and then rendering the project.

**Comment by cscheid** [comment]
Still can't repro:

````
---
title: "Post With Code"
author: "Harlow Malloc"
date: "2024-02-01"
categories: [news, code, analysis]
image: "image.jpg"
---

## A heading

This is a post with executable code.
````

<img width="631" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/9488e370-e563-4867-8af1-4926552e879e">

You do need to note that the title of the blog post has the following DOM:

`<h1 class="title">Post With Code</h1>`

```
/* css styles */
h1, h2, h3, h4 {
    color: green;
  }

  h1.title {
    color: red
  }
```

and h1.title is a more specific selector than `h1`. So you need to say `h1.title` in your CSS if you want _that_ to change.
<img width="563" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/044d8efe-457e-489e-856f-43c7553f7665">

**Comment by pgseye** [comment]
Thank you - ok I can reproduce that. But where I am running into problems is I don't know how to change the colour of the blog post titles on the landing page. See attached - on the 'Post with Code' page the title is coloured but on the main page, it's not. 

This used to work with just my original css style code - now it doesn't.

Is there a way to change the colours of the title posts on the main page?

<img width="1076" alt="screenshot_05" src="https://github.com/quarto-dev/quarto-cli/assets/12015304/9cd0701a-4df6-4760-a255-ba9ed863ceb1">
<img width="1350" alt="screenshot_04" src="https://github.com/quarto-dev/quarto-cli/assets/12015304/63add77f-8ddc-43c9-a5e6-89fe00f4cec9">

**Comment by mcanouil** [comment]
Everything is controlled by CSS.
Use your browser and its developer/inspect mode to understand the structure of the HTML and you'll know what (S)CSS to use.
Unfortunately, teaching CSS is out of the scope of Quarto.

**Comment by pgseye** [comment]
ok thanks - I'll try and figure it out

**Comment by pgseye** [comment]
For interest,

That element class is listed as 
```
h3.no-anchor.listing-title
```

Neither:
```
  h3.title {
    color: green
  }
```
or
```
  h3.no-anchor.listing-title {
    color: green
  }
```
works.
But I'm certainly no expert in css. 

I will just resign my fate to the new behaviour.

<img width="1259" alt="Untitled" src="https://github.com/quarto-dev/quarto-cli/assets/12015304/d9499199-5b2e-494f-85d2-6f9ebff5afe7">

**Comment by cscheid** [comment]
You need to be able to see what's causing the current CSS to be used. If you look at the DOM, you'll see that the blog post text is inside an anchor, `<h3 class="no-anchor listing-title"><a href="...">text here</a></h3>` and your browser should be able to tell you that the rule is

<img width="232" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/6461a62d-9f3f-4c12-a0dc-849deab846c5">

So you need a CSS rule that takes precedence over that.

Unfortunately, you do need to know CSS in order to use CSS to control the style of a webpage.

**Comment by pgseye** [comment]
Thanks very much for your assistance.

Unfortunately I don't know css to be able to make the appropriate tweak. I tried various things. Adding that code (div.quarto-post a...) to the css style sheet changes the colour of all the text and I can't figure out how to just change the post title.

it doesn't matter - I will live with it as it. Thanks again.

**Comment by pgseye** [comment]
For anyone interested, I managed to fix this problem with:

```
/* css styles */

h1, h2, h3, h4 {
  color: #1f7de6;
}

div.quarto-post h3 a {
  color: #1f7de6;
}
```
