### ISSUE TITLE
XWiki supported but not documented?

### ISSUE THREAD

**Issue by dpprdan** [quarto-dev/quarto-cli#858]
xwiki is [supported](https://cs.github.com/quarto-dev/quarto-cli?q=xwiki), but not [documented](https://quarto.org/docs/output-formats/all-formats.html#wikis).

Atlassian seems to have dropped support for Jira wiki markup, OTOH, so it may not be worth supporting? 

> We’ve removed wiki markup from the new editor in favor of full markdown support.
[Jira Cloud new issue view editor changes - Jira Development](https://community.developer.atlassian.com/t/jira-cloud-new-issue-view-editor-changes/29993)

**Comment by jjallaire** [comment]
Good catch! (that was an oversight). Docs now published here: https://quarto.org/docs/reference/formats/wiki/xwiki.html
