### ISSUE TITLE
32 Vulnerabilities Reported from OpenSSF's Scorecard CLI Utility

### ISSUE THREAD

**Issue by gregorywaynepower** [quarto-dev/quarto-cli#8589]
### Bug description

I have sincerely enjoyed learning and using the Quarto-CLI tool and more than willing to work with y'all throughout this process.

- Running [Open SSF's Scorecard Github Action](https://github.com/ossf/scorecard) to this project.

The reason I bring this up is due to me running [OpenSSF's Scorecard CLI Tool](https://securityscorecards.dev/#using-the-cli) against this repo which is at [this point](https://github.com/quarto-dev/quarto-cli/tree/060779e57d3d9f356b210ac2f4b5d074762a9734) in the commit history at time of running.

I take most of the report with a grain of salt but wanted to share the following vulnerabilities that were reported against the repo that match with Google's [Open Source Vulnerabilities database](https://osv.dev/). If these are false positives, I'd be more than willing to create an `osv-scanner.toml` that silences these false positives.

RESULTS
-------
| SCORE  |      NAME       |             REASON             |            DETAILS             |                                           DOCUMENTATION/REMEDIATION                                            |
|--------|-----------------|--------------------------------|--------------------------------|----------------------------------------------------------------------------------------------------------------|
| 0 / 10 | Vulnerabilities | 32 existing vulnerabilities    | Warn: Project is vulnerable    | https://github.com/ossf/scorecard/blob/c90e0bb4d3cf7b0cf83e942f6e159d3f615b0943/docs/checks.md#vulnerabilities |
|        |                 | detected                       | to: GHSA-h5c8-rqwp-cp95 Warn:  |                                                                                                                |
|        |                 |                                | Project is vulnerable to:      |                                                                                                                |
|        |                 |                                | GHSA-4qhp-652w-c22x Warn:      |                                                                                                                |
|        |                 |                                | Project is vulnerable to:      |                                                                                                                |
|        |                 |                                | GHSA-h56g-gq9v-vc8r Warn:      |                                                                                                                |
|        |                 |                                | Project is vulnerable to:      |                                                                                                                |
|        |                 |                                | GHSA-44cc-43rp-5947 Warn:      |                                                                                                                |
|        |                 |                                | Project is vulnerable to:      |                                                                                                                |
|        |                 |                                | GHSA-4m77-cmpx-vjc4 Warn:      |                                                                                                                |
|        |                 |                                | Project is vulnerable to:      |                                                                                                                |
|        |                 |                                | GHSA-3f63-hfp8-52jq Warn:      |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-43fp-rhv2-5gv8        |                                                                                                                |
|        |                 |                                | / PYSEC-2022-42986 Warn:       |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-xqr8-7jwr-rhp7        |                                                                                                                |
|        |                 |                                | / PYSEC-2023-135 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable to:      |                                                                                                                |
|        |                 |                                | GHSA-29gw-9793-fvw7 Warn:      |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-pq7m-3gw7-gq5x        |                                                                                                                |
|        |                 |                                | / PYSEC-2022-12 Warn:          |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-m678-f26j-3hrp        |                                                                                                                |
|        |                 |                                | / PYSEC-2022-42974 Warn:       |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-64x5-55rw-9974        |                                                                                                                |
|        |                 |                                | / PYSEC-2023-157 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-p737-p57g-4cpr        |                                                                                                                |
|        |                 |                                | / PYSEC-2022-179 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-q874-g24w-4q9g        |                                                                                                                |
|        |                 |                                | / PYSEC-2022-211 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-r726-vmfq-j9j3        |                                                                                                                |
|        |                 |                                | / PYSEC-2023-155 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-4952-p58q-6crx        |                                                                                                                |
|        |                 |                                | / PYSEC-2021-130 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-9jmq-rx5f-8jwq        |                                                                                                                |
|        |                 |                                | / PYSEC-2022-249 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable to:      |                                                                                                                |
|        |                 |                                | GHSA-hwvq-6gjx-j797 Warn:      |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-m87f-39q9-6f55        |                                                                                                                |
|        |                 |                                | / PYSEC-2022-180 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-v7vq-3x77-87vg        |                                                                                                                |
|        |                 |                                | / PYSEC-2022-212 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable to:      |                                                                                                                |
|        |                 |                                | GHSA-6p56-wp2h-9hxr Warn:      |                                                                                                                |
|        |                 |                                | Project is vulnerable to:      |                                                                                                                |
|        |                 |                                | GHSA-fpfv-jqm9-f5jm Warn:      |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-mrwq-x4v8-fh7p        |                                                                                                                |
|        |                 |                                | / PYSEC-2023-117 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-j8r2-6x86-q33q /      |                                                                                                                |
|        |                 |                                | PYSEC-2023-74 Warn: Project is |                                                                                                                |
|        |                 |                                | vulnerable to: PYSEC-2023-206  |                                                                                                                |
|        |                 |                                | Warn: Project is vulnerable    |                                                                                                                |
|        |                 |                                | to: GHSA-hj3f-6gcp-jg8j        |                                                                                                                |
|        |                 |                                | / PYSEC-2023-75 Warn:          |                                                                                                                |
|        |                 |                                | Project is vulnerable to:      |                                                                                                                |
|        |                 |                                | GHSA-qppv-j76h-2rpx Warn:      |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-g4mx-q9vg-27p4        |                                                                                                                |
|        |                 |                                | / PYSEC-2023-212 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-q2q7-5pp4-w6pg        |                                                                                                                |
|        |                 |                                | / PYSEC-2021-108 Warn:         |                                                                                                                |
|        |                 |                                | Project is vulnerable          |                                                                                                                |
|        |                 |                                | to: GHSA-v845-jxx5-vc9f /      |                                                                                                                |
|        |                 |                                | PYSEC-2023-192 Warn: Project   |                                                                                                                |
|        |                 |                                | is vulnerable to: [RSEC-2023-8](https://osv.dev/vulnerability/RSEC-2023-8)  |                                                                                                                |
|        |                 |                                | Warn: Project is vulnerable    |                                                                                                                |
|        |                 |                                | to: [RSEC-2023-3](https://osv.dev/vulnerability/RSEC-2023-3)                |                                                                                                                |

### Steps to reproduce

If y'all want to run it for yourselves of what the scorecard produces here's a command that will give you an at-a-glance output.

```shell
sudo docker run -e GITHUB_AUTH_TOKEN=GITHUB_AUTH_TOKEN_with_pub_repo_permissions_here gcr.io/openssf/scorecard:stable --repo=https://github.com/quarto-dev/quarto-cli
```

If you want to isolate a particular check you can use the `--checks` flag.

```shell
sudo docker run -e GITHUB_AUTH_TOKEN=GITHUB_AUTH_TOKEN_with_pub_repo_permissions_here gcr.io/openssf/scorecard:stable --repo=https://github.com/quarto-dev/quarto-cli --checks=Vulnerabilities  
```

If you want particular insight on what a particular check means:

```shell
sudo docker run -e GITHUB_AUTH_TOKEN=GITHUB_AUTH_TOKEN_with_pub_repo_permissions_here gcr.io/openssf/scorecard:stable --repo=https://github.com/quarto-dev/quarto-cli --checks=Vulnerabilities  --show-details
```

**Comment by cscheid** [comment]
These automated tools have an unacceptably high rate of false positives, and you shouldn't take their input blindly. We do run our own scanning internally and adjust accordingly.

**Comment by cscheid** [comment]
If you want to take on the work of maintaining the false-positive mitigation configuration yourself, I encourage you to do it on your own fork. We have the internal security team at Posit working on this already and we won't repeat their efforts given our limited number of hours in the day.

**Comment by gregorywaynepower** [comment]
My apologies, I know this report is largely unhelpful in it’s current
state. I’ll run through the list of vulnerabilities and list the causes.
I’d be more than willing to submit a PR so you don’t get false positives
for the hard work y’all are already have done since I know these tools can
be pretty noisy.

**Comment by cscheid** [comment]
Please don't, really. We're unlikely to take them and this creates an implicit promise of future maintenance that we are not interested or capable of honoring.

**Comment by gregorywaynepower** [comment]
No worries, I'll close it. I can understand the frustration, security tooling doesn't get the best wrap and you have enough on y'all's plate as maintainers.

**Comment by cscheid** [comment]
Thanks, appreciate it. But, to be clear: we _already have our own internal security tooling, managed by our security team, and we will not promise compatibility with an unbounded set of unvetted security tools in the world_.
