### ISSUE TITLE
Front matter in notebook doesn't seem to require raw type

### ISSUE THREAD

**Issue by memeplex** [quarto-dev/quarto-cli#8590]
### What would you like to do?

Report an issue on quarto.org

### Description

In https://quarto.org/docs/tools/vscode-notebook.html#yaml-front-matter it's said that:

> The first cell of your notebook should be a Raw cell that contains the document title, author, and any other options you need to specify. Note that you can switch the type of a cell to Raw using the cell type menu at the bottom right of the cell.

But setting the first cell type to Markdown instead seems to perfectly work and gives you a nicely highlighted front matter.

**Comment by cscheid** [comment]
@memeplex Please don't assign people to issues - we'll do that.

**Comment by cscheid** [comment]
We don't want to document options that we might not intend to support in the future. We only promise it to work for `raw` for a reason. This is working as intended.

**Comment by memeplex** [comment]
I'm not aware of having done anything like that. If it were just a label I would assume that I mistakenly pressed the wrong button, but two labels and one assignee is too much except that I were a sleepwalker. Are you sure that you don't have an automation in place for "Documentation issue" reports?

**Comment by memeplex** [comment]
That said, which is that is not planned? I reported something that, even if not a strict contradiction, kind of goes against of what is documented. Could you clarify the resolution? Thanks.

**Comment by mcanouil** [comment]
@memeplex no worries. It's not you but it's pretty new.

**Comment by cscheid** [comment]
> Are you sure that you don't have an automation in place for "Documentation issue" reports?

That must be what it is.

@memeplex, I apologize.

@mcanouil if that's the case, can we please remove those from the issue? They will inevitably cause more confusion and we should reserve the `triaged-to` label for ourselves.

**Comment by memeplex** [comment]
No worries.

I believe that what's documented is at odds with the observed behavior. If you require front matters in raw cells, then it's arguably a bug to also modify the behavior of quarto for other cell types. If it's an unspecified behavior then a warning may be sensible: "be aware that if your document starts with a markdown cell containing a yaml front matter it might or might not alter the operation of quarto". After all, one may want to put a yaml front matter in the first markdown cell for whatever reasons.

That said, if a quarto markdown document can start with a front-matter, and if markdown cells in a notebook provide fragments of such a document, it seems reasonable to accept a front-matter in a markdown cell. To me it feels even more natural than having it be a raw cell, since I think of markdown cells as parts of an underlying markdown document.

But it's your decision. In any case, if you decide not to support front matters in markdown cells, then I do insist in either changing the code so that said front matters are ignored or in adding a warning like the aforementioned one to the documentation (even if it sounds a bit bizarre).
