### ISSUE TITLE
Allow `quarto use` to download to the current directory

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#8595]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8593

<div type='discussions-op-text'>

<sup>Originally posted by **malcolmbarrett** February  4, 2024</sup>
### Description

I use `quarto use` to make use of my custom template, but I almost always start with an RStudio Project, not a Quarto command. Quarto then fights with me about the directory already existing, making me create a subdirectory. The default behavior would be better if, instead, you confirmed you want it in an existing directory.</div>

**Comment by cwickham** [comment]
Adding an alternate use case for this feature:

When teaching it would be nice to build projects, e.g. a website, incrementally, i.e. maybe `quarto use cwickham/website-template` into a new directory to get started, but then have learners add content to that directory from other templates. In that case, it would be nice to add content to the existing directory with `quarto use` e.g. add a `custom.scss` file something like `quarto use cwickham/website-components/custom.scss`, or a set of blog posts and a listing page in a similar way.
