### ISSUE TITLE
[FR] Allow smart navbar dropdowns

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#86]
After using the new docs layout a bit, the streamlined navbar is quite nice but it can be hard to know what is inside each item. I know you can currently do a manual dropdown item in the navbar, but would it be possible to have a smart navbar dropdown that shows you the exact same menu as shown on the section's left table of contents?
<img width="1353" alt="Screen Shot 2021-08-06 at 9 10 28 AM" src="https://user-images.githubusercontent.com/12160301/128540724-e44cc78c-13bd-4f51-bcb0-176dc667925b.png">

When navigating from other pages, this preview would help you find your way without having to click on each section to see its TOC. I know I *could* do this manually, but it seems quite tedious 😉 

Here are some similar ideas in practice:

[GatsbyJS](https://www.gatsbyjs.com/)
<img width="1209" alt="Screen Shot 2021-08-06 at 9 00 19 AM" src="https://user-images.githubusercontent.com/12160301/128540847-fe11c373-10a7-40aa-8e39-2c948568f699.png">

[rstudio.com](https://www.rstudio.com/)
<img width="1353" alt="Screen Shot 2021-08-06 at 9 17 05 AM" src="https://user-images.githubusercontent.com/12160301/128540895-60529332-434f-44e5-8ade-ea75fea0e98f.png">

[algolia](https://www.algolia.com)
<img width="1353" alt="Screen Shot 2021-08-06 at 9 18 27 AM" src="https://user-images.githubusercontent.com/12160301/128541094-0fb39844-2b0f-4ee8-9ee2-3c41774fde10.png">

**Comment by jjallaire** [comment]
Fixed w/ https://github.com/quarto-dev/quarto-cli/commit/77be6854025c44c71a235a90af1948a3db21ba37
