### ISSUE TITLE
plotly plots don't work with shiny ui inputs for Quarto dashboards

### ISSUE THREAD

**Issue by lostmygithubaccount** [quarto-dev/quarto-cli#8608]
### Bug description

I'm trying to have a UI input and use the value(s) of the input to adjust plotly charts. The inputs documentation for Quarto dashboards is all empty Python code blocks currently: https://quarto.org/docs/dashboards/inputs.html

I was able to find some examples:

- https://quarto.org/docs/dashboards/interactivity/shiny-python/index.html
- https://github.com/quarto-dev/quarto-web/blob/8dac33b1e847a06215d07f5a0b31b52052672cd3/docs/dashboards/_inputs.qmd#L71C1-L76

While this seems to work fine with other plotting libraries, plotly charts don't seem to work and I'm not sure where to go from here.

### Steps to reproduce

first example -- no Ibis:

````qmd
---
title: "Penguin Bills"
format: dashboard
server: shiny
---

```{python}
import seaborn as sns
import plotly.express as px

import plotly.io as pio
#pio.renderers.default = "notebook"
pio.renderers.default = "iframe"
#pio.renderers.default = "html"

penguins = sns.load_dataset("penguins")
```

## {.sidebar}

```{python}
from shiny import render, ui
ui.input_select("x", "Variable:",
                choices=["bill_length_mm", "bill_depth_mm"])
ui.input_select("dist", "Distribution:", choices=["hist", "kde"])
ui.input_checkbox("rug", "Show rug marks", value = False)
```

## Column

```{python}
@render.plot
def displot():
    #sns.displot(
    #    data=penguins, hue="species", multiple="stack",
    #    x=input.x(), rug=input.rug(), kind=input.dist())

    px.histogram(penguins, x=input.x(), y="species")
```
````

the seaborn plot works fine, the plotly plot is just blank on the dashboard

<img width="670" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/54814569/b33aea22-032b-49ae-868c-3198d2db4041">

second example with Ibis (same issue):

````qmd
--- 
title: "repro"
format:
  dashboard:
    theme: darkly
    scrolling: true
server: shiny
--- 

```{python}
#| echo: false
#| output: false
import ibis

import plotly.express as px

from shiny import ui, render
from itables import show

# set plotly express to dark mode
px.defaults.template = "plotly_dark"

ibis.options.interactive = True

t = ibis.examples.penguins.fetch()
```

## {height=25%}

```{python}
show(t.limit(10).to_pandas())
```

```{python}
show(
  t.group_by(ibis._.species)
  .agg(
    count=ibis._.count()
  )
  .order_by(ibis._["count"].desc())
  .to_pandas()
)
```

## {.toolbar}

```{python}
#| panel: input
ui.input_text("species", "Species:", value="Gentoo")
```

### plot

```{python}
@render.plot
def bar_chart():

    species = input.species()
    #species = "Adelie"

    px.bar(
        t.filter(t.species == species)
        .group_by(ibis._.island)
        .agg(
            count=ibis._.count()
        ),
        x="island",
        y="count",
    )
```
````

### Expected behavior

plotly plots "just work" as in other dashboarding frameworks

### Actual behavior

blank space where the plot should be 

### Your environment

- IDE: VSCode + Quarto extension
- OS: MacOS

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /Users/cody/repos/pypi-analytics/venv/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

```

**Comment by mcanouil** [comment]
- https://github.com/quarto-dev/quarto-cli/discussions/8574

**Comment by lostmygithubaccount** [comment]
for added context this is desired for:

- in-documentation dashboards: 
    - https://github.com/ibis-project/ibis/pull/8085#issuecomment-1928080267
    - https://ibis-project.org/support_matrix
- analytic dashboards:
    - converting over https://ibis-analytics.streamlit.app/
    - a new dashboard for PyPI statistics powered by ClickHouse: https://github.com/ibis-project/pypi-analytics
    
nothing in the linked discussion worked

**Comment by cwickham** [comment]
Plotly plots aren't static images (like Seaborn), so you need to use `@render_widget` (not `render.plot()`) from `shinywidgets`:

````qmd
---
title: "Penguin Bills"
format: dashboard
server: shiny
---

```{python}
import seaborn as sns
import plotly.express as px
from shinywidgets import output_widget, render_widget  

penguins = sns.load_dataset("penguins")
```

## {.sidebar}

```{python}
from shiny import render, ui

ui.input_select("x", "Variable:",
                choices=["bill_length_mm", "bill_depth_mm"])
ui.input_select("dist", "Distribution:", choices=["hist", "kde"])
ui.input_checkbox("rug", "Show rug marks", value = False)
```

## Column

```{python}
@render_widget
def displot2():
    return px.histogram(penguins, x=input.x(), color="species", marginal="rug",
                 histfunc="count", barmode="overlay")
```

````

This is indeed a shiny question rather than a Quarto one, but I respect that our docs don't give you many pointers on how to get started with Shiny for Python and Quarto. I'll be looking at those docs soon, so I'll keep this issue in mind.

**Comment by lostmygithubaccount** [comment]
awesome, thanks @cwickham! that works

**Comment by candronikos** [comment]
> Plotly plots aren't static images (like Seaborn), so you need to use `@render_widget` (not `@render.plot`) from `shinywidgets`:
> 
> ---
> title: "Penguin Bills"
> format: dashboard
> server: shiny
> ---
> 
> ```{python}
> import seaborn as sns
> import plotly.express as px
> from shinywidgets import output_widget, render_widget  
> 
> penguins = sns.load_dataset("penguins")
> ```
> 
> ## {.sidebar}
> 
> ```{python}
> from shiny import render, ui
> 
> ui.input_select("x", "Variable:",
>                 choices=["bill_length_mm", "bill_depth_mm"])
> ui.input_select("dist", "Distribution:", choices=["hist", "kde"])
> ui.input_checkbox("rug", "Show rug marks", value = False)
> ```
> 
> ## Column
> 
> ```{python}
> @render_widget
> def displot2():
>     return px.histogram(penguins, x=input.x(), color="species", marginal="rug",
>                  histfunc="count", barmode="overlay")
> ```
> 
> <img alt="Screenshot 2024-02-08 at 10 15 16 AM" width="1436" src="https://private-user-images.githubusercontent.com/25964/303139463-03d9a8f1-77af-46d9-a7a2-d0ae411f33a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI3NjYyMzAsIm5iZiI6MTc0Mjc2NTkzMCwicGF0aCI6Ii8yNTk2NC8zMDMxMzk0NjMtMDNkOWE4ZjEtNzdhZi00NmQ5LWE3YTItZDBhZTQxMWYzM2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzIzVDIxMzg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNDhiMmRiYzM4MGE2NDk0OTZhNTY3ZWMzOGRlNzM4ZGY3ZGQ2ZGI4MzU0ZjNhNTkzMGNkNzQ3ZDEzZTdmOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Sjib03WLu9_r6LiHHDt-owyGmmnuNdCoG9l_5sYe79M">
> 
> This is indeed a shiny question rather than a Quarto one, but I respect that our docs don't give you many pointers on how to get started with Shiny for Python and Quarto. I'll be looking at those docs soon, so I'll keep this issue in mind.

I ran your script in quarto version 1.6.42 in windows and still don't see the plots rendered correctly. What else can I do to rectify the issue?

![Image](https://github.com/user-attachments/assets/4b82fde1-9856-41fc-b89f-9c7159788342)

**Comment by mcanouil** [comment]
Please don't resurrect old threads.
Open a new discussion referencing this issue and any relevant materials.
Also, please check your dependencies.
