### ISSUE TITLE
Grid not working when using fenced `{.grid}` div inside fenced `{.column-page}`

### ISSUE THREAD

**Issue by teecrow** [quarto-dev/quarto-cli#8614]
### Bug description

Reprex below. My original use case was to have a side-by-side DT::datatable and ggplot spanning most of the page at the very bottom of a Quarto document. Before, with 1.3, I'd used the default page layout (which I assume is `page-layout: article`?) with a `{.grid}` div with two `{.g-col-6}`, producing a table on the left and a plot on the right. 

Now, if I try to do that in the confines of the standard body column -- i.e., without also nesting it inside a fenced `{.column-page}` -- there's no issue. But because I want my side-by-side table + plot to span across much more of the page than the standard body column, I use `:::: {.column-page}` before  `::: {.grid}` etc etc. This worked without issue in 1.3 (at least up to 1.3.450), but does not work in 1.4.549 nor in 1.5.8. 

### Steps to reproduce

````
---
title: "testing bootstrap grid with comp cells"
format: 
  html:
    page-layout: article
    embed-resources: true
---

The below two computational chunks are expected to produce a table and a plot side-by-side, by using `::: {.grid}` with `::: {.g-col-6}` underneath `::: {column-page}`.

::::: {.column-page}

::::: {.grid}

::: {.g-col-6}

```{r}
#| label: tbl-iris

"there was a table here...but it was unnecessary for the reprex."

```
:::

::: {.g-col-6}

```{r}
#| label: fig-plot
#| fig-cap: "my caption"
#| fig-cap-location: bottom
#| out-width: "30%"
#| echo: true

data(iris)
hist(iris$Sepal.Length)


```
:::

:::::

:::::
````

### Expected behavior

**The two chunks' output (and echoed code) should appear side-by-side, each taking up 6 out of 12 'units' of the bootstrap grid within `column-page`:**

![image](https://github.com/quarto-dev/quarto-cli/assets/51515693/79da02ac-a73a-4bd1-8ba0-25c18ca258d6)

### Actual behavior

**Something about trying to specify {.column-*} makes the grid not work...it seems to ignore the grid (screenshot below rendered from Quarto 1.4.549):**

![image](https://github.com/quarto-dev/quarto-cli/assets/51515693/ffa856e4-041c-48a2-96a5-453c77bb69f3)

### Your environment
- IDE: Rstudio 2023.12.1+402
- OS: Windows 10 22H2
- Quarto version 1.4.549 
  - (I replaced 'bin' and 'share' folders within the RStudio installation with this newer Quarto version. When I switch it back to 1.3, the problem disappears.)

### Quarto check output

````
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\MYUSERNAME\R\Rstudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2022.10
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\MYUSERNAME\AppData\Roaming\TinyTeX\bin\win32\
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

(|) Checking R installation...........
[my custom Rprofile startup text]

*** Library paths are ***
C:/Users/MYUSERNAME/R/R-library-USERNAME
C:/Users/MYUSERNAME/R/R-4.3.2/library

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/Users/MYUSERNAME/R/R-4.3.2
      LibPaths:
        - C:/Users/MYUSERNAME/R/R-library-USERNAME
        - C:/Users/MYUSERNAME/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
````

**Comment by mcanouil** [comment]
@teecrow could you format your post properly? Use code blocks to share code.

**Comment by teecrow** [comment]
> @teecrow could you format your post properly? Use code blocks to share code.

Done - my apologies for the ugly formatting!

**Comment by mcanouil** [comment]
@teecrow your document is invalid, especially the YAML frontmatter which should be delimited with `---`.
Please do check that your example works.

**Comment by teecrow** [comment]
Just changed and tested - can confirm it's now working.

**Comment by dragonstyle** [comment]
Bisects to this commit:
71a64a4ff65d68e2f7feed3f30b8435709f578ea
