### ISSUE TITLE
Error when using new crossref syntax for algorithm package in Latex

### ISSUE THREAD

**Issue by phongphuhanam** [quarto-dev/quarto-cli#8618]
### Bug description

Error when using new crossref syntax (v1.4) for algorithm package (`\usepackage{algorithm`} in Latex.

### Steps to reproduce

Example qmd
```qmd
---
title: My Algorithm review
format:   
  pdf:
    pdf-engine: pdflatex
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{algorithm}
        \usepackage{algorithmic}

crossref: 
  custom: 
    - kind: float
      reference-prefix: Algorithm
      key: alg
      latex-env: algorithm
---

# Quarto new reference syntax

::: {#alg-postprocess}

\begin{algorithmic}[1]
  \STATE \textbf{Input}.
  \STATE \textbf{Output}.
  \FOR{$t\in T$}
    \STATE Process
  \ENDFOR
\end{algorithmic}

Proposed post-processing algorithm.
:::

@alg-postprocess shows dummy algorithms.
```

### Expected behavior

The PDF should be built without error. 

### Actual behavior

Here is the error log:
```bash
ERROR: 
compilation failed- error
LaTeX Error: Command \listofalgorithms already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.89 ...ms{\listof{algorithm}{List of Algorithms}}
```

### Your environment

- IDE: VSCode: 1.85.2
- OS: Debian Trixie
- Quarto version: 1.4.549

### Quarto check output

```bash
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /usr/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

```

**Comment by phongphuhanam** [comment]
Quick updated. In the new crossref syntax, the following line is added to the output Tex file for the `algorithm` float:
```latex
\@ifundefined{c@chapter}{\newfloat{algorithm}{h}{loalg}}{\newfloat{algorithm}{h}{loalg}[chapter]}
\floatname{algorithm}{Algorithm}
\newcommand*\listofalgorithms{\listof{algorithm}{List of Algorithms}}
```
The error occurs because  `listofalgorithms` is already defined in the `algorithm` package, which was previously loaded in the `include-in-header` option. 
My quick solution is to comment out these lines in the output Tex file.

**Comment by mcanouil** [comment]
There is no bugs here.
1. If you duplicate `include` statement, you have to fix that yourself. `keep-tex: true` is a good way to do that.
2. If you really need to modify the LateX template or part of it, then see <https://quarto.org/docs/journals/templates.html#template-partials>.
3. Bare LaTeX should not be in your Quarto document.


<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr>
<td>

````qmd
---
title: My Algorithm review
format:   
  pdf:
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{algorithmic}
crossref: 
  custom: 
    - kind: float
      reference-prefix: Algorithm
      key: alg
      latex-env: algorithm
---

# Quarto new reference syntax

::: {#alg-postprocess}

```{=latex}
\begin{algorithmic}[1]
  \STATE \textbf{Input}.
  \STATE \textbf{Output}.
  \FOR{$t\in T$}
    \STATE Process
  \ENDFOR
\end{algorithmic}
```

Proposed post-processing algorithm.
:::

@alg-postprocess shows dummy algorithms.

````

</td>
<td>
<img width="511" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/1d2af43e-de86-4b3f-8201-bac7be1fdd08">
</td>
</tr>
</table>

I am going ahead and close this, as I don't see anything to be done on Quarto side.

**Comment by cscheid** [comment]
@mcanouil's answer is slightly inaccurate - the issue you're experiencing is not going to be visible in the template. What's happening is that a custom crossref environment [creates a `listof` command for the custom environment you create](https://quarto.org/docs/authoring/cross-references-custom.html#example-supplemental-figures). The name of that command is conflicting with the definition that the `algorithm` package creates. Unfortunately, since you're the one importing this package (which we have no knowledge of), we can't control what it defines.

**Comment by phongphuhanam** [comment]
Thanks to @mcanouil and @cscheid for commenting on this issue.
Fortunately, as @mcanouil suggested, one clean and elegant solution is using the partial template.

For anyone facing a similar issue, here is my example qmd:

```md
---
title: My Algorithm review
format:   
  pdf:
    keep-tex: true
    template-partials: 
        - before-title.tex

crossref: 
  custom: 
    - kind: float
      reference-prefix: Algorithm
      key: alg
      latex-env: algorithm
---

# Quarto new reference syntax

::: {#alg-postprocess}

    ```{=latex}
\begin{algorithmic}[1]
  \STATE \textbf{Input}.
  \STATE \textbf{Output}.
  \FOR{$t\in T$}
    \STATE Process $\leftarrow$
  \ENDFOR
\end{algorithmic}
    ```

Proposed post-processing algorithm.
:::

@alg-postprocess shows dummy algorithms.

``` 

before-title.tex file

```latex
\let\listofalgorithms\undefined
\usepackage{algorithm}
\usepackage{algorithmic}
```
