### ISSUE TITLE
"Filter" placeholder in listing filter-ui not customisable via language

### ISSUE THREAD

**Issue by petrbouchal** [quarto-dev/quarto-cli#8627]
### Bug description

In listings, when `filter-ui` is `true`, the placeholder in the search box is always "Filter", regardless of the language used. The [language file](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml) does not contain an item for customising this placeholder.

### Expected behavior

This item should be customisable as are other parts of the listing UI.

### Your environment

Quarto 1.5.9

**Comment by mcanouil** [comment]
Thanks for the report.
Could you provide the steps and possibly code to reproduce?

**Comment by petrbouchal** [comment]
Thank you!
