### ISSUE TITLE
No padding between columns in HTML, but in RevealJS

### ISSUE THREAD

**Issue by TS-CUBED** [quarto-dev/quarto-cli#8629]
### Bug description

When using the `:::{.columns}` environment in my lecture slides I get the desired result in the RevealJS slides (see attached screenshot). But in the HTML output the colums don't have any padding between then (see attached screenshot, the notes text is for my colleagues who use the template to explain what's going on. The top section is the original, the lower one has an additional column between the two image columns).

Is there a way to add some padding between the columns to make this consistent between the outputs?

![Screenshot from 2024-02-07 12-24-38](https://github.com/quarto-dev/quarto-cli/assets/52218856/21d125ef-15a9-412d-bd48-2d7aa58332e6)
![Screenshot from 2024-02-07 12-24-09](https://github.com/quarto-dev/quarto-cli/assets/52218856/d48ef904-093a-472d-a703-6c0effb98281)

The code is:

```
## Airspeed measurement

::::{.columns}
:::{.column width=40%}
![Pitot tube on an aircraft.](./images/pitotTubeAircraft.jpg)
:::
:::{.column width=60%}
![Static port on an aircraft.](./images/staticPort.jpg)
:::
::::


## Airspeed measurement

::::{.columns}
:::{.column width=39%}
![Pitot tube on an aircraft.](./images/pitotTubeAircraft.jpg)
:::
:::{.column width=2%}
:::
:::{.column width=59%}
![Static port on an aircraft.](./images/staticPort.jpg)
:::
::::
```

In the pdf, the columns get unwrapped, so it's a single column text, which is OK for that output. I tried using the `layout` option which works for HTML and RevealJS, but doesn't play nicely with the Latex engine. 

### Quarto check output

$ quarto check    
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 4.10.0
      Kernels: python3, julia-1.10, sagemath

[✓] Checking Jupyter engine render....OK

R scripting front-end version 4.1.2 (2021-11-01)
[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by mcanouil** [comment]
Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.
Format, etc. matters.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Comment by mcanouil** [comment]
> I tried using the layout option which works for HTML and RevealJS, but doesn't play nicely with the Latex engine.

Could you clarify/explain as I don't see issues?

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
title: Theorems don't work here
format: pdf
---

## Airspeed measurement

:::: {layout="[[4,6]]"}
![Pitot tube on an aircraft.](https://placehold.co/600x400.png)

![Static port on an aircraft.](https://placehold.co/600x400.png)
::::

````

</td><td>

<img width="643" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/b3b46022-1f20-4662-ac12-2c3912b6ef7c">

</td></tr>
</table>

**Comment by TS-CUBED** [comment]
Will need to set up a MWE. The current setup has too many dependencies. 

Re Latex and layout: It seems I had a conflict with captions in the margin and the layout feature. If I disable margin captions it does indeed work as you show. With ` cap-location: margin` it does not show any caption for the two figures.

With two small issue: all other figures that get created use the [H] location, while the one containing the layout minipages does not. This means the figure in my lecture notes are not displayed in the right section. The two column figure also only gets (a) and (b) as in your example, while all others get full captions with figure numbers.

**Comment by mcanouil** [comment]
Please share complete example, not simply snippet without formats.
The issue is about Reveal.js, but you talk about LaTeX and at the end about HTML.

This being said, you need the following code in Quarto:

````qmd
---
format: html
---

::: {#fig-myfigure}

:::: {layout="[[4,6]]"}
![A sub caption 1](https://placehold.co/600x400.png){#fig-sub1}

![A sub caption 2](https://placehold.co/600x400.png){#fig-sub2}
::::

A main caption for the figure.
:::
````

Or if you don't want to reference sub elements.

````qmd
---
format: html
---

::: {#fig-myfigure}

:::: {layout="[[4,6]]"}
![A sub caption 1](https://placehold.co/600x400.png)

![A sub caption 2](https://placehold.co/600x400.png)
::::

A main caption for the figure.
:::
````
