### ISSUE TITLE
Warning: The computation used to determine source line information from the engine timed out

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8635]
In some circumstances (computationally heavy projects/documents), the below warning is displayed.

The warning really stands out in the trace as it is in yellow in the middle of the green text log, thus users are likely to wonder what this is about and how bad is it.

![Quarto log showing a yellow warning message about source line information from the engine timed out](https://github.com/quarto-dev/quarto-cli/assets/8896044/dcefd519-d044-4798-a47d-f3a3337dada3)

> WARNING: Warning: The computation used to determine source line information from the engine timed out.

Suggested solution:

> JJ: I am wondering if we are seeing this often enough that we should consider disabling it by default (as it will tend to compound performance problems w/ large output documents?). Alternatively, we could set a very low timeout.

> JJ/Carlos: 0.2s

> Carlos: Ideally we’d only show the warning if we needed to show line information but that was going to require a big structural change in the code.
JJ’s solution is very clean, I’ll go ahead with it

**Comment by Oscie** [comment]
I got this warning when updating RStudio and R (v 4.2 to 4.4). Now my Quarto document table of contents is incomplete. So it's not been resolved and it does impact documents.

**Comment by mcanouil** [comment]
It's resolved but you need Quarto 1.5.
