### ISSUE TITLE
Quarto autocompletion fails for chunks with options in chunk header

### ISSUE THREAD

**Issue by kevinushey** [quarto-dev/quarto-cli#8652]
### Bug description

From here:

https://github.com/quarto-dev/quarto-cli/blob/7b1e6d1cda0ae363de3ae602e3839562765b0dee/src/resources/editor/tools/yaml/web-worker.js#L33143-L33146

It appears that the YAML web worker that handles completions doesn't allow headers like:

`````
```{r label}
#| echo: 
```
`````

That is, the inline "label" chunk option causes rejection of the completion request.

### Steps to reproduce

Create an R Markdown document in RStudio, open it in the visual editor, and try to include Quarto-style YAML chunk options. For example:

`````
```{r label}
#| echo: 
```
`````

Then, request completions.

### Expected behavior

Quarto's bundled YAML web-worker should be able to provide completions.

### Actual behavior

Nothing is provided.

### Your environment

RStudio 2024.04.1 (dev build); macOS 14.2.1.

### Quarto check output

```
> system("quarto check")
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin
```

**Comment by kevinushey** [comment]
For posterity, the relevant lines of code in web-worker.js:

```
      const m = codeLines[0].substring.match(/.*{([a-z]+)}/);
      if (!m) {
        return noIntelligence(kind);
      }
```

Could the regular expression be relaxed, to allow some arbitrary content following the engine name?

**Comment by cscheid** [comment]
Technically, it definitely could.

But I don't know if we _want_ to support this. My understanding is that Quarto docs actively discourage users from mixing and option styles, specifically because the knitr style of option declaration is not supported in any other engine. Can you give a bit more context for why we want to do it?

**Comment by mcanouil** [comment]
FYI, mixing syntaxes was already discouraged by Yihui when multiline R syntax and YAML syntax was introduced in `knitr`.

**Comment by cscheid** [comment]
The salient point here for Quarto is that if this is a syntax we want to support, then this is a syntax we _should_ support. But it needs to be supported everywhere, and not only on there.

This class of issues would also go away if we had a linter/syntax checker that would actually tell users that this syntax isn't support and we don't have that right now.

**Comment by kevinushey** [comment]
Thanks -- for context, from the perspective of RStudio, Quarto tools are used for both R Markdown and Quarto documents, and we also support the source editor as well as the visual editor for each as well. From a user's perspective, because of the substantial overlap in syntax between the two styles, it can be surprising to see that YAML autocompletion appears to work in some contexts, but not in others.

This is then further confounded via the fact that autocompletion appears to work in the Source editor in RStudio, but not in the Visual editor.

<img width="196" alt="Screenshot 2024-02-08 at 4 11 11 PM" src="https://github.com/quarto-dev/quarto-cli/assets/1976582/0bb0ee92-a0c2-4837-8272-5604f0c9d74d">

<img width="218" alt="Screenshot 2024-02-08 at 4 11 04 PM" src="https://github.com/quarto-dev/quarto-cli/assets/1976582/f9702855-44e0-41d1-9329-35ab462524b6">

Presumedly that is because of the more permissive regex here?

https://github.com/quarto-dev/quarto-cli/blob/d74c2edee420d4c9ac140f996cacce236814fd34/src/resources/editor/tools/yaml/web-worker.js#L32124-L32126

**Comment by cscheid** [comment]
> Quarto tools are used for both R Markdown

Hm. This is troubling on our aside. Does RStudio report, eg, validation errors on RMarkdown document metadata?

> it can be surprising to see that YAML autocompletion appears to work in some contexts, but not in others.

I don't dispute that; but do these code cells _actually work_? My impression is that mixed content of this kind is not actually well supported.

> This is then further confounded via the fact that autocompletion appears to work in the Source editor in RStudio, but not in the Visual editor.

This is definitely a bug. I think you won't like my suggestion, but maybe the solution here is to not offer completion on either case rather than on both?

**Comment by cscheid** [comment]
After tracking down the source of the more permissive regex, I'm now back on your side - it's much less risky for us to change the regexp that is less permissive than to change the regex that is more permissive. The former is only used for yaml intelligence, but the latter is part of a really finicky code path for us, one which I'm very reluctant to change.

**Comment by kevinushey** [comment]
> Hm. This is troubling on our side. Does RStudio report, eg, validation errors on document metadata of RMarkdown documents?

Can you give an example of the sort of validation you might expect (or not expect) for R Markdown documents? For what it's worth, the heuristic used in RStudio is that documents with a `format: <>` entry in the document header should be rendered by `quarto`. But it seems like the answer is "yes".

<img width="193" alt="Screenshot 2024-02-08 at 4 51 25 PM" src="https://github.com/quarto-dev/quarto-cli/assets/1976582/75e3ddfe-9b8c-49cc-8931-74d0eb8a5643">

> I don't dispute that; but do these code cells actually work? My impression is that mixed content of this kind is not actually well supported.

For the case described here, where we're just supplying a chunk label in the chunk header, everything works fine on render (since that label is AFAIK only used for e.g. navigation in the IDE / editor; from what I can see, it's not ultimately relevant when rendering the document).

That all said ... it does seem like everything works as expected, even with a document like this:

`````
---
title: "Untitled"
format: html
---

```{r echo=TRUE}
#| message: false
print(1 + 1)
message(2 + 2)
```
`````

presumedly because `knitr` is processing the chunks, and does permit mixing styles. (not advocating this as a good idea; just something that does work, for better or worse)

**Comment by cscheid** [comment]
> Can you give an example of the sort of validation you might expect (or not expect) for R Markdown documents? For what it's worth, the heuristic used in RStudio is that documents with a format: <> entry in the document header should be rendered by quarto, and so in this context those diagnostics are turned on. But it seems like the answer is "yes".

The example you shared, where RMarkdown supports `date: true` while Quarto doesn't is exactly the kind of thing that makes me quite surprised to learn that .rmd files are currently run through Quarto's YAML validator.

But that's neither here nor there, since I realized that it's safer for us to support the relaxed syntax during completions than it is to disallow mixed syntax in the finicky code-path that I'm very reluctant to change.

@kevinushey would replacing `/.*{([a-z]+)}/` with `/.*{([a-z]+)\s*.+}/ alleviate the RStudio problem?

**Comment by cscheid** [comment]
This is a very minor thing that we wouldn't usually backport. But if we _do_ backport it, then the new stable 1.4 that is expected to ship with RStudio would include this fix, and that would be pretty nice.

**Comment by kevinushey** [comment]
> The example you shared, where RMarkdown supports date: true while Quarto doesn't is exactly the kind of thing that makes me quite surprised to learn that .rmd files are currently run through Quarto's YAML validator.

Sorry, that's not something supported by R Markdown either; it was just an example to show that Quarto's YAML diagnostics were indeed running and were displayed in this case.

To clarify, these diagnostics are only shown if the document has something like `format: html` in its YAML header. RStudio takes this as a sign that the document should be rendered with Quarto, rather than `rmarkdown::render()` -- and so the diagnostics only activate when Quarto will be used to render the R Markdown document.

I don't think regular R Markdown would support `date: true` either, but I think it's correct to show these diagnostics in R Markdown documents which are intended to be rendered with Quarto?

> @kevinushey would replacing /.*{([a-z]+)}/ with /.*{([a-z]+)\s*.+}/ alleviate the RStudio problem?

It indeed would -- thank you!

**Comment by cderv** [comment]
> but I think it's correct to show these diagnostics in R Markdown documents which are intended to be rendered with Quarto?

Yes it is because even if they are `.Rmd` document, they can be rendered through `quarto render`. Just `output` will be ignored, and `format: html` used, unless another format is provided. 

We have always communicated that migrating to Quarto does not mean that `.Rmd` file needs to be change - they will work as is for most of them. (I making exception of document that would use specific R Markdown package syntax). 

> do these code cells actually work? My impression is that mixed content of this kind is not actually well supported.

Mixing options in YAML and in the chunk header is perfectly fine for **knitr** as it will merge them together. This is not that is not well supported it is that :
- this is knitr only syntax
- YAML validation does not work for option in cell header

So we have always advice users not to mix them.

**Comment by cscheid** [comment]
> To clarify, these diagnostics are only shown if the document has something like format: html in its YAML header. RStudio takes this as a sign that the document should be rendered with Quarto, rather than rmarkdown::render() -- and so the diagnostics only activate when Quarto will be used to render the R Markdown document.
> 
> I don't think regular R Markdown would support date: true either, but I think it's correct to show these diagnostics in R Markdown documents which are intended to be rendered with Quarto?

I think I just completely misunderstood the situation. If RStudio is rendering the .rmd with Quarto then the current behavior is correct. What I thought you were describing was a situation with an .Rmd file containing (say)

```
---
output: html_document
...
---
```

, and that Quarto's YAML diagnostics were being shown in that case. That is what I would have been surprised about!

**Comment by mcanouil** [comment]
Why I think supporting mixed syntax is *
*at best* confusing:

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
title: "knitr options syntax"
format: html
fig-height: 2
fig-width: 3
---

## R inline and R multiline syntaxes.

```{r fig-my-label-1, fig.cap="My caption 1"}
#| label = "fig-my-label-2",
#| fig.cap = "My caption 2"
plot(1)
```

@fig-my-label-1 the ref to `fig-my-label-1`.

@fig-my-label-2 the ref to `fig-my-label-2`.

## R inline and YAML syntaxes.

```{r fig-my-label-3, fig.cap="My caption 3"}
#| label: "fig-my-label-4"
#| fig-cap: "My caption 4"
plot(1)
```

@fig-my-label-3 the ref to `fig-my-label-3`.

@fig-my-label-4 the ref to `fig-my-label-4`.

````

</td><td>

<img width="605" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/87410ec9-61ea-4962-8d53-a059ba232189">

</td></tr>
</table>

**Comment by cscheid** [comment]
Right - the problem is that our YAML validation doesn't know how to match the options and warn people when they're incompatible. This is something we'll need to fix with linting.

But the inconsistency of completion between editor modes is a worse problem, and one we can solve.
