### ISSUE TITLE
Website: Sidebar header disappears when navbar is activated. I would like to keep the sidebar header

### ISSUE THREAD

**Issue by Santonia27** [quarto-dev/quarto-cli#8661]
### Bug description

When the navbar is activated the sidebar header that I configurated disappears. 
However I would like to have the tools (Github icon and toggle to darkmode) in my header/ navbar and the title of my page defined and showing in the sidebar covering the full left side of my website. 

If I have no navbar defined I have a sidebar header. as soon I create a navbar the header disappears.

is it possible to just add a header with the icons instead of a navbar or to keep navbar and sidebar+header ?

**Comment by mcanouil** [comment]
Would you mind sharing the requested information? Thanks.

Do you use `style: "docked"` as documented? See <https://quarto.org/docs/websites/website-navigation.html#side-navigation>.

You can share a small **self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository.

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.
