### ISSUE TITLE
Impossible to preview docusaurus website

### ISSUE THREAD

**Issue by FabienSe** [quarto-dev/quarto-cli#8662]
### Bug description

Hello !

I am trying to migrate to the latest version of quarto, while doing this migration I discovered it is impossible for me to preview my docusaurus website with the command `quarto preview`.

After some debug, I found it is because I have a `_quarto.yml` to define configurations at project level.
If I remove it, it is working good. It seems quarto got difficulty to parse this file.

### Steps to reproduce

1. Create a basic docusaurus website
2. Add the following `_quarto.yml` file

```yml
project:
  type: docusaurus

format:
  docusaurus-md:
    code-fold: true

execute:
  warning: false
```
3. Run the command `quarto preview`

### Expected behavior

Project preview should be supported for docusaurus project.

### Actual behavior

It crashs with the following error.

```console
ERROR: The project '' is a default type project which doesn't support project wide previewing unless there is an 'index' file present.

Please preview an individual file within this project instead.

Stack trace:

Please preview an individual file within this project instead.
    at serveProject (file:///home/fabien/.local/opt/quarto-1.4.549/bin/quarto.js:97425:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Command.fn (file:///home/fabien/.local/opt/quarto-1.4.549/bin/quarto.js:98149:9)
    at async Command.execute (file:///home/fabien/.local/opt/quarto-1.4.549/bin/quarto.js:8104:13)
    at async quarto (file:///home/fabien/.local/opt/quarto-1.4.549/bin/quarto.js:114968:5)
    at async file:///home/fabien/.local/opt/quarto-1.4.549/bin/quarto.js:114986:9
```

### Your environment

- IDE: VS Code
Version: 1.86.1 (user setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
- OS: WSL1 with Ubuntu 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

### Quarto check output

```bash
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /home/fabien/.local/opt/quarto-1.4.549/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment]
@dragonstyle I remember you added this specific error message for a specific reason, but I can't remember what it was; tagging you just so you can refresh me and we'll handle it.

**Comment by dragonstyle** [comment]
For default Quarto projects (for example a collection of HTML documents), there isn't a 'main file' to open when previewing, so the result was just that tooling/users would  often run `quarto preview` with no target, which would open a preview at the root which would result in a 404 error (which was confusing users, understandably). This error is mostly designed to help users in this scenario, so is definitely bug that we're blocking docusaurus (I though we attempted to allow this, but perhaps we missed it).

**Comment by dragonstyle** [comment]
Definitely surprising that this is happening:

```typescript
    const projType = projectType(project?.config?.project?.[kProjectType]);
    if (
      projType.type === "default" && project?.config?.format !== "docusaurus-md"
    ) {
         // Do error stuff here
```

**Comment by dragonstyle** [comment]
Ok I understand why this is happening and it is definitely a bug - we'll get this fixed ASAP and back port it to a 1.4 patch.

**Comment by dragonstyle** [comment]
Yes, thank you! We haven't yet built an installable version of Quarto 1.4, but the chance is also present in our 1.5 pre-release builds. If you could, you can install a pre-release here and test (then go back to 1.4 while you await a 1.4 patch release which should be coming soon).

https://quarto.org/docs/download/prerelease.html

**Comment by cscheid** [comment]
@lwasser We need a reproducible example to be able to help.

**Comment by lwasser** [comment]
here you go - i just submitted a PR. it runs fine in CI because i have a docker container running quarto 1.3x. but locally this is what i get:

```
➜ quarto preview
ERROR: The project '' is a default type project which doesn't support project wide previewing unless there is an 'index' file present.

Please preview an individual file within this project instead.

Stack trace:

Please preview an individual file within this project instead.
    at serveProject (file:///Applications/quarto/bin/quarto.js:97961:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:98692:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8104:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:115789:5)
    at async file:///Applications/quarto/bin/quarto.js:115801:9
    at async mainRunner (file:///Applications/quarto/bin/quarto.js:115698:9)
    at async file:///Applications/quarto/bin/quarto.js:115792:5
(dataskills) 
dss-web (☊ func-lessons) [✎ ×16 ] is 📦 v3.2.0 via 🐹 v1.21.0 via  v21.5.0 via 🐍 pyenv via 🅒 dataskills 
❯ quarto -v     
1.5.21
(dataskills) 
```

but locally i just built the site about 20 minutes ago with 1.3x. open to any ideas or to a workflow to help me downgrade quarto?

**Comment by cscheid** [comment]
> here you go - i just submitted a PR.

Sorry, but what PR?

**Comment by lwasser** [comment]
my apologies - [a link would be helpful](https://github.com/data-science-skills/dss-web/pull/11/files) 

now i've tested on 1.3, 1.4 and 1.5 locally. it builds on 1.3x! not 1.4 or 1.5 . i'm also pushing an update to the readme now

**Comment by mcanouil** [comment]
Your project is not a project.
Quarto preview requires a project or to specify a file to be previewed.
That's a change that so believe is described in the changelog.

**Comment by cscheid** [comment]
@mcanouil that's not true: https://github.com/lwasser/dss-web (and same with the branch)

**Comment by cscheid** [comment]
@lwasser I can reproduce. To be clear, you will not run into problems in CI because CI doesn't run `quarto preview`, and `quarto render` works correctly.

**Comment by mcanouil** [comment]
I think there was an issue that was fixed about Hugo project time and `quarto preview`.

**Comment by cscheid** [comment]
I've now adapted the fix from @dragonstyle for hugo projects in addition to docusaurus projects (I believe these are the two markdown-based projects that we have special handling for in preview).

@lwasser I can't actually run hugo succesfully on your website, either with 1.3.450 or with `main`, but I believe that my fix will get you unblocked. I'll wait for test suite to pass, make a new pre-release build and you should be good to try the new 1.5.

**Comment by lwasser** [comment]
hey @cscheid thank you! interesting - i am probably missing a step in the documentation is my guess. 🤷‍♀️
i will spend some time cleaning it up.
t i'm also game to test with the new 1.5 to see if it works for me locally as well. many thanks!

**Comment by cscheid** [comment]
FWIW here is the hugo output I got from a fresh install of hugo via homebrew:

````
Watching for changes in /Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/{_vendor,archetypes,assets,content,data,hugo_stats.json,i18n,layouts,package.json,postcss.config.js,static,themes}
Watching for config changes in /Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/hugo.toml, /Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/config/_default, /Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/_vendor/github.com/gohugoio/hugo-mod-bootstrap-scss/v5/config.toml, /Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/_vendor/github.com/gohugoio/hugo-mod-jslibs-dist/popperjs/v2/config.toml, /Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/_vendor/github.com/gethugothemes/hugo-modules/pwa/config.toml, /Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/go.mod
Start building sites …
hugo v0.123.4-21a41003c4633b142ac565c52da22924dc30637a+extended darwin/arm64 BuildDate=2024-02-26T16:33:05Z VendorInfo=brew

ERROR render of "page" failed: "/Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/layouts/lessons/single.html:73:38": execute of template failed: template: lessons/single.html:73:38: executing "main" at <.Content>: error calling Content: "/Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/content/english/lessons/git-github/git-intro/3-fork-clone.md:107:1": failed to render shortcode "image": failed to process shortcode: "/Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/layouts/shortcodes/image.html:31:52": execute of template failed: template: shortcodes/image.html:31:52: executing "shortcodes/image.html" at <add `static/` $imagePath>: error calling add: can't apply the operator to the values
ERROR render of "page" failed: "/Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/layouts/lessons/single.html:73:38": execute of template failed: template: lessons/single.html:73:38: executing "main" at <.Content>: error calling Content: "/Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/content/english/lessons/python/install-python/2-why-conda-for-science.md:50:1": failed to render shortcode "image": failed to process shortcode: "/Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/layouts/shortcodes/image.html:31:52": execute of template failed: template: shortcodes/image.html:31:52: executing "shortcodes/image.html" at <add `static/` $imagePath>: error calling add: can't apply the operator to the values
Built in 380 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/layouts/lessons/single.html:73:38": execute of template failed: template: lessons/single.html:73:38: executing "main" at <.Content>: error calling Content: "/Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/content/english/lessons/git-github/git-intro/2-what-is-version-control.md:54:1": failed to render shortcode "image": failed to process shortcode: "/Users/cscheid/Desktop/daily-log/2024/02/26/dss-web/layouts/shortcodes/image.html:31:52": execute of template failed: template: shortcodes/image.html:31:52: executing "shortcodes/image.html" at <add `static/` $imagePath>: error calling add: can't apply the operator to the value
````

**Comment by lwasser** [comment]
@cscheid thank you - i'll turn this into an issue. you are using a newer version of hugo than i have. But also, this is my first hugo / quarto site after using jekyll for a long time. so it's very possible that i set something up in a funky way. i'll look into it. i really appreciate seeing that error so i can look into this! 🙌
