### ISSUE TITLE
Duplicated documentation information for left and right menu (navbar)

### ISSUE THREAD

**Issue by Lextuga007** [quarto-dev/quarto-cli#8676]
### What would you like to do?

Report an issue on quarto.org

### Description

In the documentation on page [https://quarto.org/docs/reference/projects/websites.html the ](https://quarto.org/docs/reference/projects/websites.html#navbar) the documentation information for left and right menu is the same - should the second say right instead of left? :

![image](https://github.com/quarto-dev/quarto-cli/assets/39963221/dfc75197-9d3f-434b-9e82-bc4076625741)

https://github.com/quarto-dev/quarto-web/blob/1ee5c33c9f88ca0f626cee6708b734d046b97ad1/docs/reference/projects/navbar.json#L48

**Comment by cwickham** [comment]
This one is actually hard-coded in `quarto-web/tools/reference.ts`. Fix in https://github.com/quarto-dev/quarto-web/pull/1015
