### ISSUE TITLE
Chrome is not found when trying to render document with Graph and it errors

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#868]
I tried example at https://quarto.org/docs/authoring/diagrams.html

````markdown
---
title: "My simple title"
format: html
---

# Head

```{mermaid}
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```
````

and I get this when `quarto render`

````
WARNING: Capturing of embedded web content disabled (chromium not installed)
ERROR: TypeError: Cannot read properties of undefined (reading '0')

TypeError: Cannot read properties of undefined (reading '0')
    at Object.cell (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/handlers/mermaid.ts:84:69)
    at async Promise.all (index 0)
    at async Object.document (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/handlers/base.ts:367:20)
    at async handleLanguageCells (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/handlers/base.ts:330:34)
    at async renderFiles (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-files.ts:384:39)
    at async render (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-shared.ts:91:18)
    at async Command.fn (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cmd.ts:183:26)
    at async Command.execute (https://deno.land/x/cliffy@v0.19.3/command/command.ts:997:7)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:918:16)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:870:16)
````

I am using last dev version (946b31a703bda35218c26323d1c2349f0cca08a5) on windows 10

**Comment by jjallaire** [comment]
Here is the code where we try to discover Chrome: https://github.com/quarto-dev/quarto-cli/blob/main/src/core/puppeteer.ts#L193-L207

Could you see what's happening on your system when we hit this code?

**Comment by cderv** [comment]
Issue seems to be that the `reg.exe query` called from `Deno.run()` result in an error of type "Invalid Key". 
It seems that the query KEY is not correctly pass inside Deno.run().  

I can confirm that the query is ok locally on windows, and oddly working with `Deno.run()` interactively in console.

**Comment by cderv** [comment]
Ok so after discussing with @dragonstyle I am convinced this is the same type of issue we encountered with `tlmgr` in https://github.com/quarto-dev/quarto-cli/issues/336

it is still the same issue in Deno and someone has the exact same problem with `reg.exe query` too. https://github.com/denoland/deno/issues/8852#issuecomment-1126113436

Oddly, things are working in my terminal as shown above. 

Anyway, I'll do the same trick that for `tlmgr` with a bit of refactoring using `safeWindowsExec`. 

or better as suggested by @dragonstyle, I can try make `execProcess` handles this correctly on Windows. 

I'll do that next week.

**Comment by cderv** [comment]
I can confirm using same as for tlmgr fix the first issue. `reg.exe query` works. 

However, we are doing a regex search considering a `keyname`
https://github.com/quarto-dev/quarto-cli/blob/3ad9ed9ac35ce6f3f7ba1e85601ba53b230d3d67/src/core/windows.ts#L22-L29

https://github.com/quarto-dev/quarto-cli/blob/3ad9ed9ac35ce6f3f7ba1e85601ba53b230d3d67/src/core/windows.ts#L42-L44

And unfortunately, this is localized. On my French computer, it won't match as the key return is as above in https://github.com/quarto-dev/quarto-cli/issues/868#issuecomment-1126485578
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe
    (par défaut)    REG_SZ    C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
```

I'll handle that to somehow

**Comment by jjallaire** [comment]
I think that (Default) is a special virtual key name that can be addressed without reference to its translation — I don’t recall exactly how to do this but I remember this being the case

**Comment by jjallaire** [comment]
It looks like you can read the "(Default)" value by specifying the `/ve` flag: https://renenyffenegger.ch/notes/Windows/registry/tree-structure/default-value
