### ISSUE TITLE
Custom Float objects not rendered in PDF after a longtable object

### ISSUE THREAD

**Issue by marklhc** [quarto-dev/quarto-cli#8711]
### Bug description

When making a table with `knitr::kable()` in R, which gives a longtable object with PDF output, a custom float object in the same document does not work. This has been tested with quarto 1.4.549 and 1.5.10. The custom float object is rendered properly without the longtable object. This may be related to #7604

### Steps to reproduce

````qmd
---
title: "Untitled"
format:
  pdf:
    keep-tex: true
crossref:
  custom:
    - kind: float
      key: out
      latex-env: output
      reference-prefix: Output
---

```{r}
knitr::kable(mtcars)
```

::: {#out-2}

```{r}
#| echo: false
## Example from stats::aov()
aov(yield ~ block + N * P + K, npk)
```

Sample ANOVA output

:::

See @out-2
````

### Expected behavior

The custom float object should be shown.

### Actual behavior

I got the error

```
ERROR: 
compilation failed- error
Missing } inserted.
<inserted text> 
                }
l.307 \end{longtable}
```

### Your environment

- IDE: VSCode 1.86.1
- OS: Ubuntu 20.04

### Quarto check output

```
Quarto 1.5.10
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.10
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/hokchiol/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib/R
      LibPaths:
        - /home/hokchiol/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Unfortunately I don't think we can't fix this. Longtables hardcode the `table` crossref counter in LaTeX. We try to detect and work around that, but if the library emits `longtable`, our crossref system cannot possibly work in LaTeX.

**Comment by cscheid** [comment]
On the other hand, I'd like for us to not _crash_ here.

**Comment by cscheid** [comment]
This is even stranger. The mere declaration of the custom output is enough to break longtables.

**Comment by cscheid** [comment]
There appears to be some deep incompatibility between the `float` latex package and the `longtable` package. Honestly, `longtable` is badly broken in a variety of ways (for example, it hardcodes its crossref counter to `table`). We already do a large number of workarounds. I unfortunately don't think we can fix this.

**Comment by marklhc** [comment]
Thanks for taking a look @cscheid. I guess I'll have to find a workaround to not use `longtable` until they fix the issue.

**Comment by cscheid** [comment]
Specifically, this is the definition in our custom float declaration that causes `longtable` to fail. Note that this has nothing to do with longtables:

```
\@ifundefined{c@chapter}{\newfloat{output}{h}{loout}}{\newfloat{output}{h}{loout}[chapter]}
```

**Comment by marklhc** [comment]
Hi @cscheid, thank you and I see the fix in #8714. However, it seems that `longtable` is still used when a table caption is added:

````qmd
---
title: "Untitled"
format:
  pdf:
    keep-tex: true
crossref:
  custom:
    - kind: float
      key: out
      latex-env: output
      reference-prefix: Output
      caption-location: top
---

```{r}
#| label: tbl-1
#| tbl-cap: Table caption
knitr::kable(mtcars)
```

See @tbl-1.

::: {#out-2}

```{r}
#| echo: false
## Example from stats::aov()
aov(yield ~ block + N * P + K, npk)
```

Sample ANOVA output

:::

See @out-2
````

Would it be possible to use `tabular` for tables with captions too? Thank you so much.

**Comment by cscheid** [comment]
> Would it be possible to use tabular for tables with captions too?

That should already be happening.

**Comment by cscheid** [comment]
I can't get your document to render because kable seemingly fails for me with a knitr error message:

````
processing file: 8717.qmd
1/2
2/2 [unnamed-chunk-1]
output file: 8717.knit.md

Error: Functions that produce HTML output found in document targeting docx output.
Please change the output type of this document to HTML.
If your aiming to have some HTML widgets shown in non-HTML format as a screenshot,
please install webshot or webshot2 R package for knitr to do the screenshot.
Alternatively, you can allow HTML output in non-HTML formats
by adding this option to the YAML front-matter of
your quarto file:

  prefer-html: true

Note however that the HTML output will not be visible in non-HTML formats.

Execution halted
````

I don't know when kable decides to emit html tables vs markdown, but it seems that you're running a different version than I am (I'm on knitr 1.45).

@cderv will know more, but he's not available in the next few days.

**Comment by marklhc** [comment]
That's odd. I'm also on `knitr` 1.45 and using the developmental version of quarto. I got the same error of

```
ERROR: 
compilation failed- error
Missing } inserted.
<inserted text> 
                }
l.311 \end{longtable}
                      

see test-float-1.log for more information.
```

Render is fine without 

```
#| tbl-cap: Table caption
```

**Comment by mcanouil** [comment]
Are you using `freeze` option?
Try in a clean project.

**Comment by cscheid** [comment]
I don't understand why knitr does that, tbqh. But I can repro your issue by switching to our div syntax.

**Comment by marklhc** [comment]
Thanks for making another fix @cscheid, and I feel bad for making another report on the same issue . . . but here it is, for regular markdown tables:

````qmd
---
title: "Untitled"
format:
  pdf:
    keep-tex: true
crossref:
  custom:
    - kind: float
      key: out
      latex-env: output
      reference-prefix: Output
---

| Default | Left | Right | Center |
|---------|:-----|------:|:------:|
| 12      | 12   |    12 |   12   |
| 123     | 123  |   123 |  123   |
| 1       | 1    |     1 |   1    |

: Demonstration of pipe table syntax

::: {#out-2}

```{r}
#| echo: false
## Example from stats::aov()
aov(yield ~ block + N * P + K, npk)
```

Sample ANOVA output

:::

See @out-2
````

The tex file now has the caption outside of the `tabular` environment in the developmental version of quarto. It also results in a error with quarto 1.4/1.5 as it uses the `longtable` environment. I also checked that the file rendered correctly without the table caption.

**Comment by cscheid** [comment]
Thank you for the continued reports! We're the one to be apologizing. We'll look at this right away.

**Comment by cscheid** [comment]
So this is tricky. What's happening here is that we can't emit `longtable` environments because that package doesn't work with the `float` packages.

When the `float` package is disable, Pandoc emits tables always through the longtable environment. That environment is unique in that it's both displays a table, and increments the `table` latex counter specifically (this is why we already originally disabled longtables inside custom crossrefs).

To make matters more complicated, LaTeX doesn't support captions at all outside floats, and so the standard code we use for rendering `tabular` environments assumes that the code will be emitted inside a float, and issues a `\caption{}` command.

So now we have to decide what to do when we see a Table outside of a float with a caption, which needs to be rendered with `tabular`. In Quarto 1.3, the unlabeled table would increment the `counter` table (because that's what `longtable` does). Here, though, I'm not sure what we should do. In HTML, we have custom code to render tables and figures with captions but no labels. In LaTeX, this just isn't a thing that really exists.

One solution is to wrap the code in a `\begin{table}` environment, so that the counter is incremented just like `longtable` would. I don't love it (because it's unintuitive and makes the counters in LaTeX and HTML inconsistent), but it seems less bad than dropping the caption or attempting to render it by ourselves.

Another solution is for us to create a "hidden" float environment for these unlabeled tables, and configure its captions to not show any counter information. That is closer to what Quarto does in HTML, but will probably confuse users expecting the old behavior.

**Comment by marklhc** [comment]
Hi @cscheid, I just found out that if I don't call the new latex environment as `output`, it renders correctly:

````qmd
---
title: "Untitled"
format:
  pdf:
    keep-tex: true
crossref:
  custom:
    - kind: float
      key: out
      latex-env: abc
      reference-prefix: Output
---

```{r}
#| label: tbl-1
#| tbl-cap: Table caption
knitr::kable(mtcars)
```

See @tbl-1.

::: {#out-2}

```{r}
#| echo: false
## Example from stats::aov()
aov(yield ~ block + N * P + K, npk)
```

Sample ANOVA output

:::

See @out-2
````

So maybe it's just because of the name I chose?

**Comment by mcanouil** [comment]
The example you shared also works with "output", but https://github.com/quarto-dev/quarto-cli/issues/8711#issuecomment-1944961595 won't work whatever the name of `latex-env` is.

**Comment by marklhc** [comment]
Sorry I should have clarified: the original example works with the current release of quarto 1.4 or 1.5, before fixing the longtable issue, once I changed `latex-env` to something other than "output." So it seems longtable breaks because I call the float object "output." For example, in the [minimal example](https://github.com/quarto-dev/quarto-cli/issues/8711#issuecomment-1939784585) @cscheid shared, `xelatex` works when I use another name:

```tex
\documentclass{article}

\usepackage{float}
\newfloat{abc}{h}{loout} % <--- This line is the problem

\usepackage{longtable,booktabs,array}
\usepackage{calc}

\begin{document}

\begin{longtable}[]{@{}l@{}}
  \toprule\noalign{}
  \endhead
  \bottomrule\noalign{}
  \endlastfoot
  foo \\
\end{longtable}

\end{document}
```

**Comment by cscheid** [comment]
I believe @marklhc is correct here

I'm testing on commit 449f9b0fd (before my first fix) and changing the float name to `somethingelse` avoids the problem.  It's likely not safe for us to try to pick a different name, so we'll issue an error if the user tries to choose `output` as the environment name.

**Comment by cscheid** [comment]
@marklhc is correct, and this enables a good fix for us, happily; PR is up. Thank you for the careful, precise debugging work here, @marklhc!

**Comment by cscheid** [comment]
I'll daringly call this fixed now, but please let us know if it rears its head again!
