### ISSUE TITLE
quarto won't render

### ISSUE THREAD

**Issue by John-Pebbles** [quarto-dev/quarto-cli#8729]
### Bug description

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
chdir: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
error: Failed getting cwd.

Caused by:
    Operation not permitted (os error 1)

**Comment by cscheid** [comment]
Sorry, we need a more carefully written report than this to be able to help. Please give [this](https://github.com/quarto-dev/quarto-cli/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) a read and feel free to file a new issue.
