### ISSUE TITLE
Light box image group image duplicated when scrolling

### ISSUE THREAD

**Issue by OrenBochman** [quarto-dev/quarto-cli#8739]
### Bug description

When I scroll through the lightbox images on this page, which share a lightbox group, each of the images appears twice.

### Steps to reproduce

reproduction is now available at: https://github.com/OrenBochman/quatro-cli-bugs/tree/main/bugs/bug2

### Expected behavior

I expected to see each image when scrolling back and forth in the light box group only once.

### Actual behavior

I see each image appear twice.

### Your environment

Pop!_OS 22.04 LTS
RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-29) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

R 

> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie                 
Warning message:
No Python documentation found for 'lime_tabular.LimeTabularExplainer'. 

Python 3.10.12

### Quarto check output

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.11
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/oren/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /home/oren/work/blog/env/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

R scripting front-end version 4.1.2 (2021-11-01)
[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by cscheid** [comment]
We need a document to know what you mean.

**Comment by mcanouil** [comment]
@OrenBochman Please, follow the template and include all required information. If you don't provide us with the information, we can't help you or even identify if there is a bug.

**Comment by OrenBochman** [comment]
1. I pasted a shorter plaintext quarto page in the bug report. - you may be able to view it live [at this link](https://orenbochman.github.io/blog/qa_demo2.html)

**Comment by mcanouil** [comment]
Are all the options you set required to reproduce your issue?
Remove everything not necessary, please and ensure it is reproducible by running the document you shared on your computer, as we need to be able to render it.

**Comment by dragonstyle** [comment]
FWIW, I tried with the sample document and wasn't able to reproduce the issue. here is example:

https://asdasdasdsada.quarto.pub/lecture-1-----introduction-to-xai/

(I suspected the issue to be related to `link-external` options)

**Comment by OrenBochman** [comment]
@mcanouil I've updated the reproduction with a minimal sample.

@dragonstyle the original issue was with local images - the sample now has a second file local.qmd with the same issue on local files.

**Comment by mcanouil** [comment]
Sorry but what are we supposed to see exactly?


https://github.com/quarto-dev/quarto-cli/assets/8896044/0111bf1e-924f-4827-846e-7cb7293e692d
