### ISSUE TITLE
Shinylive installation breaks the GitHub page update.

### ISSUE THREAD

**Issue by OrenBochman** [quarto-dev/quarto-cli#8740]
### Bug description

I added the sine demo shinylive demo to my blog which supported automated builds of new content (using the first option in the docs). After making minor changes the gh pages would not update.

The build failed with reference to missing the latest version of shineylive.

I also added shinylive to my python requirements.txt but I guess it is not being used by cicd script.

Using the quarto publish is my current workaround. But this raises space warnings on my machine. 

### Steps to reproduce

the only use of shinylive is in the following: https://github.com/OrenBochman/blog/tree/main/docs/posts/2024/shinylive

### Expected behavior

I was expecting the gh pages to update per: https://quarto.org/docs/publishing/github-pages.html#publish-action

> This action will run whenever you push to the main branch of your repository

1. running a quarto render
2. git add . 
3. git commit -a -m 'yada yada'
4. git push 

### Actual behavior

The remote build step fails e.g. https://github.com/OrenBochman/blog/actions/runs/7818210595/job/21327898671

this is an exctracpt from the failure: from the Render and Publish step:

````
[74/84] posts/2024/shinylive/demo.qmd
(E) Error running 'shinylive' command. Perhaps you need to install / update the 'shinylive' Python package?
 Error:
 PandocError {}
Error running filter /opt/quarto/share/filters/main.lua:
...blog/blog/_extensions/quarto-ext/shinylive/shinylive.lua:40: Error running 'shinylive' command. Perhaps you need to install / update the 'shinylive' Python package?

stack traceback:
	...blog/blog/_extensions/quarto-ext/shinylive/shinylive.lua:40: in global 'throw_quarto_error'
	...blog/blog/_extensions/quarto-ext/shinylive/shinylive.lua:57: in global 'callPythonShinylive'
	...blog/blog/_extensions/quarto-ext/shinylive/shinylive.lua:111: in global 'callShinylive'
	...blog/blog/_extensions/quarto-ext/shinylive/shinylive.lua:253: in global 'ensurePyshinyliveVersion'
	...blog/blog/_extensions/quarto-ext/shinylive/shinylive.lua:312: in global 'ensureLanguageSetup'
	...blog/blog/_extensions/quarto-ext/shinylive/shinylive.lua:414: in function <...blog/blog/_extensions/quarto-ext/shinylive/shinylive.lua:398>
	[C]: in ?
	[C]: in method 'walk'
	/opt/quarto/share/filters/main.lua:224: in local 'checked_walk'
	/opt/quarto/share/filters/main.lua:276: in function 'run_emulated_filter'
	/opt/quarto/share/filters/main.lua:936: in local 'callback'
	[string "..."]:[188](https://github.com/OrenBochman/blog/actions/runs/7818210595/job/21327898671#step:4:190)8: in field 'withScriptFile'
	/opt/quarto/share/filters/main.lua:952: in upvalue 'run_emulated_filter_chain'
	/opt/quarto/share/filters/main.lua:990: in function </opt/quarto/share/filters/main.lua:987>
stack traceback:
	/opt/quarto/share/filters/main.lua:224: in local 'checked_walk'
	/opt/quarto/share/filters/main.lua:276: in function 'run_emulated_filter'
	/opt/quarto/share/filters/main.lua:936: in local 'callback'
	[string "..."]:1888: in field 'withScriptFile'
	/opt/quarto/share/filters/main.lua:952: in upvalue 'run_emulated_filter_chain'
	/opt/quarto/share/filters/main.lua:990: in function </opt/quarto/share/filters/main.lua:987>
ERROR: Error
    at renderFiles (file:///opt/quarto/bin/quarto.js:77074:29)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async renderProject (file:///opt/quarto/bin/quarto.js:77389:25)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:106423:33)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:10[210](https://github.com/OrenBochman/blog/actions/runs/7818210595/job/21327898671#step:4:212)9:24)
    at async Object.publish1 [as publish] (file:///opt/quarto/bin/quarto.js:102565:26)
    at async publishSite (file:///opt/quarto/bin/quarto.js:106460:38)
    at async publish6 (file:///opt/quarto/bin/quarto.js:106679:61)
    at async doPublish (file:///opt/quarto/bin/quarto.js:106639:13)
    at async publishAction (file:///opt/quarto/bin/quarto.js:106650:9)
Error: Process completed with exit code 1.
```



### Your environment

Pop!_OS 22.04 LTS
RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-29) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

R 

> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie                 
Warning message:
No Python documentation found for 'lime_tabular.LimeTabularExplainer'. 

Python 3.10.12

### Quarto check output

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.11
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/oren/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /home/oren/work/blog/env/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

R scripting front-end version 4.1.2 (2021-11-01)
[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by cscheid** [comment]
@OrenBochman, we've asked you for reproducible cases twice in other situations. We can't help you if you don't help us.

**Comment by mcanouil** [comment]
> Hi, I opened these issues during a commute and without my PC... The guidelines suggest that you'd rather know about issues than not and I thought it best just get started.

Yes, but you did not mention that you were going to update or anything, suggesting your report was complete.
To put it plainly "rather know about issues than not" does not mean to open issue saying only "there is a bug" which is not really helpful as we can't act on that, thus you don't get any help either. Kind of a lose-lose situation.
We do appreciate the bug reports, so keep making ones, but make it counts.
Complete bug reports from you means, less exchange, less time consumed, and quicker fix/solution/workaround => win-win situation.

> But the blog repo is public.

Then something is missing, because you did not share here or in the other issues a link to that repository.

**Comment by OrenBochman** [comment]
Ok as I intimated above, I've updated the above template with the full details.
 I apologize for not being better at this  -- it took me some time to figure out how to report this kind of bug. The page itself does not have an issue as far as I can see.

My  current workaround for updating the GitHub pages is to run the following:
 
````
quarto publish
````

The reality is that I don't understand how the GitHub action does its magic - I was just happy to follow the instructions as long as it worked.

**Comment by dragonstyle** [comment]
As far as I know, our actions don't do anything specific to restore the execution environment (e.g. `pip install -r requirements.txt`). I think you likely just need to add a step to your action which gets any dependencies installed (there are a bunch of GH actions that do this and handle caching and other useful things)- that step should happen prior to the render.

**Comment by mcanouil** [comment]
You might want to read the Actions documentation and look at the examples: https://github.com/quarto-dev/quarto-actions
