### ISSUE TITLE
Diagram should be responsive to columns in revealjs slides

### ISSUE THREAD

**Issue by jebyrnes** [quarto-dev/quarto-cli#8748]
### Bug description

I've been working to try and make a slide for a presentation with a 4x4 set of figures showing four different Directed Acyclic Graphs. However, it seems that Quarto won't resize the diagrams for the columns. I tried simplifying this down and noticed that not only would it not resize them, but, it would also cut off graphs if a column width was too narrow.  Here is a reprex showing this odd behavior that I believe is a bug.

First, this looks fine.

    ---
    title: "test"
    format: revealjs
    ---
    
    # DAG Before You Model
    
    ```{dot}
    digraph {
    
    layout = neato
    
    m [
        shape = none
        pos = "-1,1!"
    ]
    
    d [
        shape = none
        pos = "0,0!"
    ]
    
    
    a [
        shape = none
        pos = "1,1!"
    ]
    
    
    m -> d
    a -> d
    }

[![works][1]][1]


But, with this modification, things get weird and cut-off.

    ---
    title: "test"
    format: revealjs
    ---
    
    # DAG Before You Model
    
    ::: {.columns}
    
    ::: {.column width="50%"}
    
    ```{dot}
    digraph {
    
    layout = neato
    
    m [
        shape = none
        pos = "-1,1!"
    ]
    
    d [
        shape = none
        pos = "0,0!"
    ]
    
    
    a [
        shape = none
        pos = "1,1!"
    ]
    
    
    m -> d
    a -> d
    }
    ```
    
    :::
    
    
    ::: {.column width="50%"}
    :::
    
    :::

[![The cutoff diagram][2]][2]

If you mess with the column widths, you can start getting the cutoff part back, but, the diagram never resizes.

Running quarto 1.4.549 R 4.3.2

  [1]: https://i.stack.imgur.com/JWw9m.png
  [2]: https://i.stack.imgur.com/8hKpU.png

**Comment by cderv** [comment]
First, one thing about Quarto Slide usage with revealjs. You are using only `#`. Be aware that by default, this is for Title slide content and that `##` is for normal slide content. This is mentioned in the part about slide creation : https://quarto.org/docs/presentations/revealjs/#creating-slides

Using title slide, especially for some complex content, can have some undesired effect in some case, as Revealjs really consider those as Title section slide (so usually a main Title section and some sub content under). 

That being said, let's see your issue. 

What do you expect exactly when using column ? Are you expecting the diagram to be resized automatically ? 

The auto sizing behavior that you can have for image (https://quarto.org/docs/presentations/revealjs/advanced.html#stretch) is for Image only - this is a revealjs feature we benefit. 

For complex content like `svg` (which is what `dot` computation engine outputs by default), there is no auto sizing by  revealjs. 

I don't know exactly if we can make `fig-responsive` behavior from Diagram (https://quarto.org/docs/authoring/diagrams.html#sizing) works well in RevealJS context and the RevealJS framework does already a lot of things regarding sizing. 

I'll see what we can do. For now, you will need to specify size manually. Try `//| fig-width: 50%` 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/9a3789b7-1e5a-4e78-be2f-35b3d83a7f72)

**Comment by jebyrnes** [comment]
First, great solution! Second, sorry for the # - I am using this inside of a presentation where I also have vertical slides, so, hence the # and ## as different.

As for expectations, yes, I'd expect it to be resized. This is actually a simpler reprex from what I was doing, where I was trying to make a 4x4 grid of different DAGs. Honestly, for those of us in the causal diagram world, having the ability to make multi-panel figures - whether in slides or in quarto bookdowns - would be killer. I had assumed that it was possible at present, but, perhaps I'm wrong - although your sizing solution might make it work. Particularly if I did that for both width and height for the 4x4.

**Comment by cderv** [comment]
Regarding 4x4, did you try the layout feature of Quarto : https://quarto.org/docs/authoring/figures.html#multiple-rows ? 

It could be a bit different than just the column 🤔

**Comment by jebyrnes** [comment]
Huh. I thought that would only work for images directly. Would it work for code-generated images?

**Comment by cderv** [comment]
Yeah sorry - wrong part of the doc linked 🤦 

https://quarto.org/docs/authoring/figures.html#block-layout

We have a generic feature 

> While the examples above illustrate laying out figures, it’s important to note that layout attributes can be used to layout any sort of block content.

**Comment by jebyrnes** [comment]
The sizing solution works perfectly.

```
//| fig-width: 50%
//| fig-height: 50%
```

Let me even make a nice 4x4.

Using the block layout also worked well!

For code for anyone who wants to look at this in the future for a 4x4 design, here are both ways:
https://gist.github.com/jebyrnes/800881335d01356a3a61e6f1020fb00d
