### ISSUE TITLE
quarto publish connect from windows corrupts path delimiters in the bundle tar.gz

### ISSUE THREAD

**Issue by eugen-lounkine-bms** [quarto-dev/quarto-cli#8749]
### Bug description

I am trying to get a blog hosted on Post Connect. I write it locally on my windows machine, with a local python environment, coding in VS Code, and using Git Bash as my terminal (I did try with windows cmd, and it has the same behavior as Git Bash);

When I do so with `quarto publish connect`, it creates the bundle, uploads it, and hosts the content, but it has a bug during bundle creation: relative paths (local folders) are not represented as folders in the bundle tar.gz;
This makes only the main index.html accessible on Posit Connect, without any of the blog posts (they are in a subfolder).
The path delimiters are replaced with a \uf05c character.

### Steps to reproduce

Shift+Ctrl+P -> Create new quarto Project -> Blog

This creates the default blog setup
![image](https://github.com/quarto-dev/quarto-cli/assets/149062543/b88ef8ec-e9cb-4d58-900b-5ceae87556df)

### Expected behavior

After I `quarto publish connect`, the blog should render correctly on posit.

### Actual behavior

The blog lacks styles, and the links to the posts do not work.
The bundle has replaced path delimiter (\ on windows, should be / in the bundle) with a \uf05c character.
![image](https://github.com/quarto-dev/quarto-cli/assets/149062543/b52c43f6-f4ce-4da4-94fc-e213b9a66be2)

[bundle-41602.tar.gz](https://github.com/quarto-dev/quarto-cli/files/14302248/bundle-41602.tar.gz)

### Your environment

- OS: Win10
- IDE: VSCode
- language: Python
- terminal: Git Bash and CMD have same behavior

### Quarto check output

Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\lounkine\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/Users/lounkine/AppData/Local/Programs/R/R-4.3.2
      LibPaths:
        - C:/Users/lounkine/AppData/Local/Programs/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by cderv** [comment]
Definitely an issue in the way the tar.gz bundle is created. Folder are clearly omitted because of a path transformation problem 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/7974ec2a-9626-45a8-b4df-3b73f9df86e3)

I'll investigate this

**Comment by cderv** [comment]
This will be fixed in 1.4 next patch release and in so in 1.5 pre-release. 

Thanks for the report
