### ISSUE TITLE
Markdown not parsed in listings with custom EJS

### ISSUE THREAD

**Issue by petrbouchal** [quarto-dev/quarto-cli#8756]
### Bug description

Using a simple custom EJS template for a listing, markdown contained in listing fields is not parsed.

### Steps to reproduce

Clone the repo at https://github.com/petrbouchal/quarto-listings-markdown and run `quarto render`. This is a bare-bones quarto project created via RStudio.

What I have tested:
- links and italic/bold formatting is parsed in built-in listings but not in custom ones
- markdown parsing is done by built-in listings in both default and grid mode (not seen in reprex)
- I used a simplified version of the example custom EJS template provided at https://github.com/quarto-dev/quarto-cli/discussions/7089

### Expected behavior

I would expect custom listings to behave the same as built-in ones with respect to parsing listing fields.

### Actual behavior

![image](https://github.com/quarto-dev/quarto-cli/assets/1666657/70234394-8198-467c-9574-8d85fd120a1a)

### Your environment

- IDE: RStudio Version 2024.04.0-daily+426 (2024.04.0-daily+426)
- MacOS 14.2.1 (23C71)
- quarto 1.5.14

### Quarto check output

```bash
quarto check
Quarto 1.5.14
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.14
      Path: /Users/petr/.local/share/qvm/versions/v1.5.14/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/petr/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.0
      Path: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources
      LibPaths:
        - /Users/petr/csandbox/quarto-listings-markdown/renv/library/R-4.3/aarch64-apple-darwin20
        - /Users/petr/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.3/aarch64-apple-darwin20/ac5c2659
      knitr: 1.37
      rmarkdown: 2.13

[✓] Checking Knitr engine render......OK

```

**Comment by petrbouchal** [comment]
Related to #3468 but not quite a duplicate - here, even standard fields are not parsed, not just custom ones.

**Comment by mcanouil** [comment]
There is no bug here I'm afraid.
You enclosed your EJS template within a raw HTML block meaning you don't want the content to be read as markdown, thus you don't get the content parsed as markdown.

**Comment by petrbouchal** [comment]
Thanks for the clarification. The bit about writing the template in Markdown might be worth documenting - the docs currently make an impression that one should write HTML in the EJS templates.

Part of the problem was that I was going off the built-in templates linked from the discussion, which probably are treated differently.

**Comment by mcanouil** [comment]
EJS template is not a Quarto thing.

Note that you used a raw block. That's not HTML. That's markdown.

**Comment by tim-at-topos** [comment]
> Thanks for the clarification. The bit about writing the template in Markdown might be worth documenting - the docs currently make an impression that one should write HTML in the EJS templates.
> 
> Part of the problem was that I was going off the built-in templates linked from the discussion, which probably are treated differently.

Yeah, this tricked me as well, especially since e.g. https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/projects/website/listing/item-grid.ejs.md uses `<div>` rather than `:::`.
