### ISSUE TITLE
fig column instead of column for tutorial on side by side columns

### ISSUE THREAD

**Issue by lmullany** [quarto-dev/quarto-cli#8774]
### What would you like to do?

Report an issue on quarto.org

### Description

I believe `fig-column` intead of `column` should be used in the tutorial on layout of two plots in the basic tutorial found here:
https://quarto.org/docs/get-started/computations/rstudio.html

**Comment by mcanouil** [comment]
Where exactly? Could you link at least to the section rather than the page?
Thank you.

**Comment by cscheid** [comment]
(@mcanouil we'll solve this sooner rather than later. If you see other duplicates go easy on them; it's on us that this bug is triggered by some of our very first lessons.)
