### ISSUE TITLE
Julia plots not respecting embed-resources

### ISSUE THREAD

**Issue by jsks** [quarto-dev/quarto-cli#8777]
### Bug description

The [html documentation](https://quarto.org/docs/reference/formats/html.html) states that `embed-resources` can be used to create a standalone html that should inline figures created from execution blocks through a data URI. Apologies if I missed something in the documentation, but I assume that setting this to false would save any figures as external files in the default  `<document>_files` directory with a src link in an img tag in the html output.

This works when creating a figure with R or python + matplotlib; however, when running Julia through Jupyter, plots are embedded as base64 strings in the html output even when `embed-resources` is set to false. Note, issue persists even in the latest quarto pre-release.

### Steps to reproduce

Compare the html output from the following qmd snippets, one creating a plot through R with knitr and the other creating a plot through Julia using Jupyter.

````qmd
---
title: "Test document"
execute:
    fig-format: png
format:
    html:
        embed-resources: false
---

R plot

```{R}
plot(1:10, 1:10)
```
````

````qmd
---
title: "Test document"
jupyter: julia-1.10
execute:
    fig-format: png
format:
    html:
        embed-resources: false
---

Julia plot

```{julia}
using Plots

plot(1:10, 1:10)
```

````

### Expected behavior

In both cases the figures should be saved as external files and linked in the html output through a `src` attribute.

### Actual behavior

For the Julia version the plot is inlined as a base64 string.

### Your environment

Linux amd64 

### Quarto check output

Quarto 1.4.550
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.550
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /usr/bin/python3
      Jupyter: 5.7.1
      Kernels: ir, julia-1.10, python3, octave

(/) Checking Jupyter engine render....[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib64/R
      LibPaths:
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
`embed-resources: false` is the default.

It does not specify that figures should be written to files.
If set to true, it means Pandoc will embed the files as base64.
Thus, if Jupyter/Julia does not output files in the first place, there is no reason to see those.

R/knitr as internals that does save figures to files.
I don't think Jupyter does the same as results are stored within the notebook, so base64.

**Comment by jsks** [comment]
Alright, thanks for the response, I got confused because Jupyter/python3 works similar to R and knitr. For example,

````qmd
---
title: "Test document"
jupyter: python3
format:
    html:
        embed-resources: false
---

Python plot

```{python}
import matplotlib.pyplot as plt

plt.plot([1, 2, 3], [1, 2, 3])
plt.show()
```
````

Also, I know the documentation says that `fig-format` is for R graphics and matplotlib, but it does affect the output of Julia plots. If it's changed to the default of svg, then a svg element will be directly embedded in the html output instead of a base64 string with a image/png mimetype.

**Comment by cscheid** [comment]
This is intended behavior; if a downstream library wants to emit its output as a base64 string, we respect that. `embed-resources: true` forces linked images to be embedded, but it doesn't go the other way.

**Comment by cscheid** [comment]
You're seeing that behavior because Julia and Python use different libraries; they're not the same code base.
