### ISSUE TITLE
Cross references of equations are broken using xelatex

### ISSUE THREAD

**Issue by braniii** [quarto-dev/quarto-cli#8782]
### Bug description

Hi
I am not able to cross reference math equations within my Quarto document.  So using the examples from the docs

```Markdown
$$
x + 1
$$ {#eq-first}

See @eq-first
```
Results in a PDF with `See Equation. ??`. I am afraid, that I've simply messed up with my setup. But I haven't found the issue yet :thinking: 

Btw. as a long term LaTeX user I really appreciate Quarto to spend more time writing and less with setting up documents :blush: 

### Steps to reproduce

Using the example from #2000 

````Markdown
---
title: "Equations"
crossref:
  eq-prefix: "eq."
---

$$
x + 1
$$ {#eq-first}

See @eq-first

$$
y + 1
$$ {#eq-second}

See equation [-@eq-second].
````

Running this on my machine results in

``` Bash
$ quarto render test.qmd --to pdf
pandoc 
  to: latex
  output-file: test.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Equations
  crossref:
    eq-prefix: eq.
  

Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023/Arch Linux) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023/Arch Linux) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  

Output created: test.pdf
```

### Expected behavior

`See eq. (1) ... See equation (2).`

### Actual behavior

`See eq. ?? ... See equation ??.`

### Your environment

- terminal
- Manjaro-Linux

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.65.1: OK
      Deno version 1.38.5: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /usr/lib/quarto-cli/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
FWIW, I cannot reproduce the issue on the latest version of Quarto.
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/334fd076-0458-4465-a103-25d9d511ff2c">

**Comment by braniii** [comment]
Thx for your help :) I will try your suggestions out.

**Comment by braniii** [comment]
Installing TinyTex did not help. I've checked the generated `LaTeX` code and it does not compile correctly running Xelatex. 

Do you get also this source code? I will retry once the quarto update is available on my distro.

``` LaTeX
\begin{document}
\maketitle

\begin{equation}\protect\label{eq-first}{
x + 1
}\end{equation}

See eq.~\ref{eq-first}

\begin{equation}\protect\hypertarget{eq-second}{}{
y + 1
}\end{equation}

See equation \ref{eq-second}. \protect\hyperlink{eq-second}{2}



\end{document}
```

**Comment by cderv** [comment]
I got this 
````latex
\begin{document}
\maketitle

\begin{equation}\phantomsection\label{eq-first}{
x + 1
}\end{equation}

See eq.~\ref{eq-first}

\begin{equation}\phantomsection\label{eq-second}{
y + 1
}\end{equation}

See equation \ref{eq-second}.



\end{document}
````

using your document with slight YAML addition 

````markdown
---
title: "Equations"
format: pdf
keep-tex: true
crossref:
  eq-prefix: "eq."
---

$$
x + 1
$$ {#eq-first}

See @eq-first

$$
y + 1
$$ {#eq-second}

See equation [-@eq-second].
````

And it works too. 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/8761eacb-5818-4344-9447-0ca5e34c5fbe)


I used 1.4.549 like you and got same log 
````
pandoc
  to: latex
  output-file: index.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Equations
  crossref:
    eq-prefix: eq.
````

Maybe this is a difference in CTAN packages installed somehow, or you are running your document in another context. (Quarto project maybe ?)

I am surprised using TinyTeX did not help with this. 

Do you have a specific error message or something else in the console when rendering ? 

Maybe share a full reproducible example of your issue as a github repo so we work on the same content exactly

**Comment by braniii** [comment]
Sorry for my late reply. Upgrading to `pandoc 3.1.8` fixed the issue for me. @cderv @mcanouil thank you for your time and help :)

**Comment by braniii** [comment]
> Just FYI, Quarto ships its own Pandoc version, and shouldn't be using system Pandoc at all.

Good to know. I guess the issue was that I've used the AUR package [quarto-cli](https://aur.archlinux.org/packages/quarto-cli) which depends on the system Pandoc, instead of [quarto-cli-bin](https://aur.archlinux.org/packages/quarto-cli-bin) which uses your binary.

**Comment by cscheid** [comment]
@braniii FWIW we did't create, and don't maintain any of those packages, and Quarto needs pretty precise coordination with Pandoc, because minor changes in Pandoc's readers and writers have an outsized impact in our own. I don't know if `quarto-cli` ships our https://github.com/quarto-dev/quarto-cli/blob/main/configuration file, but that's where we declare the expected Pandoc version.
