### ISSUE TITLE
Observable value box not style as Python/R

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8823]
<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
title: "test"
format: dashboard
---

## Row 

```{ojs}
//| content: valuebox
//| title: "Articles per day"
//| icon: pencil
//| color: primary
12
```

```{python}
#| content: valuebox
#| title: "Articles per day"
#| icon: pencil
#| color: primary
dict(
  value = 12
)
```
````

</td><td>

<img width="730" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/c63173dc-1781-4222-b953-e6223d77157f">

</td></tr>
</table>

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8822

<div type='discussions-op-text'>

<sup>Originally posted by **h3ndrik** February 21, 2024</sup>
### Description

Is there a way to fill the dasboard valuebox with `ojs`?

````qmd
---
title: "test"
format: dashboard
---

```{ojs}
value = 42
```

```{ojs}
//| content: valuebox
//| title: "Test"
//| icon: pencil
//| color: primary
???
```

````

Unfortunately the documentation doesn't include an example for ojs. And I can't get the dict right. I've had a look at the ojs documentation. And I was able to output a JS Object with a value key, but that's also not rendered like the numbers from R or python, but shows up as Object {value: 42}</div>

**Comment by mcanouil** [comment]
FYI, using inline observable and markdown fenced divs works as expected.

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd

````qmd
---
title: "test"
format: dashboard
---

## Row 

```{ojs}
//| include: false
value = 12
```

::: {.valuebox icon="pencil" color="primary"}
Articles per day

`{ojs} value`
:::
````
````

</td><td>

<img width="727" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/59e8c314-08ff-43aa-9e13-1e3d5b1955c7">

</td></tr>
</table>

**Comment by cscheid** [comment]
This is probably our OJS cells not forwarding classes correctly. We should encourage people to use the div notation for now.

**Comment by cscheid** [comment]
This is the behavior on `main` now:
<img width="1972" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/1c298b2b-cf60-4e74-8ec1-0cbf8a1bd99c">

**Comment by CoryMcCartan** [comment]
String values still do not work, but do with interpolation. Is that expected behavior? E.g. the first cell shows a small `"12"` and the second matches the above output

````md
---
title: "test"
format: dashboard
---

```{ojs}
value = "12"
```

```{ojs}
//| content: valuebox
//| title: "Test"
//| color: primary
value
```

::: {.valuebox color="primary"}
Test

`{ojs} value`
:::
````

If this example should work, then it seems like the cause is the way the cell outputs are parsed [here](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/filters/modules/dashboard/valuebox.lua). Fixing it could also allow cells to emit objects which would allow OJS to support dynamic values of eg `title` and `color`.

Happy to move this to a new issue if in-scope.

**Comment by mcanouil** [comment]
@CoryMcCartan Please open a new thread (discussion or eventually an issue). You can reference this issue from there.
Finally, when adding link, please use descriptive link text, not "here", "this", "that", etc.

> [!IMPORTANT]
> Accessibility: For better accessibility, please ensure link text is descriptive and meaningful rather than using generic terms such as "here". This helps all users understand the link's destination. See [Writing meaningful link text (WCAG)](https://www.wcag.com/blog/writing-meaningful-link-text/).


Note that the issue you are describing, is unrelated to value boxes.
You are not emitting the same thing with both code, see:

````qmd
---
format: html
execute:
  echo: false
---

```{ojs}
"value"
```

```{ojs}
md`value`
```

`{ojs} "value"`

```{ojs}
value="12"
```

```{ojs}
md`${value}`
```

`{ojs} value`
````
