### ISSUE TITLE
quarto inserts \centering between \table and options when table label contains a dash

### ISSUE THREAD

**Issue by hughjonesd** [quarto-dev/quarto-cli#8841]
### Bug description

The following example shows a bug where quarto is mistakenly putting a `\centering{` between `\table` and `[ht]`. Cf. #593  for a similar earlier issue, and #8564 for a more recent one.

<img width="636" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/5818871/fd8e2e73-7582-452e-8199-f786ae9964f3">

I suspect this is related to the line here: https://github.com/quarto-dev/quarto-cli/blob/d047195554ca875b420b99d98be5593810e3ee5e/src/resources/filters/quarto-pre/table-captions.lua#L30

### Steps to reproduce

This quarto file should do it when compiled to PDF. It also shows several examples which do not trigger the bug.

````
---
title: "Table test"
format: pdf
execute:
  echo: false
---

```{r}
library(huxtable)
```

```{r}

hux("table with width set") |> 
  set_width(0.8) |> 
  set_caption("blah") |> 
  set_label("dash-1")

```

```{r}

hux("table with caption and dash in label (BUG: shows [ht])") |> 
  set_caption("blah") |> 
  set_label("has-dash")

```

```{r}

hux("table with no dash in label") |> 
  set_caption("blah") |> 
  set_label("nodash")
```

```{r}
#| label: dash-4
#| warning: false

hux("table with no caption and dash in label") |> 
  set_label("dash-4")

```

````

This quarto file shows the same behaviour but using raw TeX:

````
---
title: "Table test"
format: pdf
execute:
  echo: false
---

\begin{table}[ht]
\begin{tabular}{ll}
foo & bar
\end{tabular}
\caption{label has dash: problem}
\label{has-dash}
\end{table}

\begin{table}[ht]
\begin{tabular}{ll}
foo & bar
\end{tabular}
\caption{label has no dash: ok}
\label{nodash}
\end{table}

\begin{table}[ht]
\begin{tabular}{ll}
foo & bar
\end{tabular}
\caption{no label: ok}
\end{table}

\begin{table}[ht]
\begin{tabular}{ll}
label has dash, but & no caption: ok
\end{tabular}
\label{has-dash-2}
\end{table}

````

### Expected behavior

`\centering` should be inserted before or after the table-and-options `\table[ht]`.

### Actual behavior

The `\centering` breaks the table positioning and causes the options to be displayed as raw text.

### Your environment

MacOS Sonoma 14.21
RStudio Version 2023.12.1+402

### Quarto check output

```bash
$ quarto check  
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/davidhugh-jones/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/davidhugh-jones/Dropbox/text and cooperation experiment/data-analysis/renv/library/R-4.3/aarch64-apple-darwin20
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Hm. I can't even get this to compile:

````
---
title: "Table test"
format: pdf
keep-md: true
keep-tex: true
execute:
  echo: false
---

```{r}
library(huxtable)
```

```{r}
hux("table with caption and dash in label (BUG: shows [ht])") |> 
  set_caption("blah") |> 
  set_label("has-dash")
```
````

**Comment by cscheid** [comment]
The problem here is slightly worse. `huxtable` is trying to use a crossreferenceable float, and we're failing to correct it.

The relevant output from keep-md is:

````
```{=latex}
 
  \providecommand{\huxb}[2]{\arrayrulecolor[RGB]{#1}\global\arrayrulewidth=#2pt}
  \providecommand{\huxvb}[2]{\color[RGB]{#1}\vrule width #2pt}
  \providecommand{\huxtpad}[1]{\rule{0pt}{#1}}
  \providecommand{\huxbpad}[1]{\rule[-#1]{0pt}{#1}}

\begin{table}[ht]
\begin{centerbox}
...
````

That large amount of initialization code is confusing our processing. Unfortunately, you'll have to generally use huxtable in a manner that makes it start its output on `\begin{centerbox}`, and not `\begin{table}`

We probably should add a `latex-table-processing` option in the same way that we have `html-table-processing`, so that we don't try to touch this kind of latex code. However, when that is set, you won't be able to use `hux` tables outside of anything but `Table 1, Table 2`, etc. Starting in Quarto 1.4, tables can be part of [custom crossrefs](https://quarto.org/docs/authoring/cross-references-custom.html) which is ultimately the source of this problem.

**Comment by hughjonesd** [comment]
Note that the TeX-only doc also triggers the bug. Also, the original huxtable doc (including the first table) seems to avoid crashing, for some reason. 

On the grand scale a no-preprocessing directive would help. I've given up on integrating huxtable with quarto labels anyway for now, and just advise people to use TeX \ref style cross refs. 

On the small scale, I think this particular bug could be fixed in a similar way to #593, just by recognising the `\begin{table}[xx]` pattern. 

LaTeX question, does it matter which order `\centering` and `\begin{table}` go? If not I could just swap them round.

**Comment by cscheid** [comment]
> On the small scale, I think this particular bug could be fixed in a similar way to https://github.com/quarto-dev/quarto-cli/issues/593, just by recognising the \begin{table}[xx] pattern.

I don't want to be curt, but we _do_ recognize it. The issue, like I said above, is the initialization code that's happening. We need to do a lot more processing than you might expect, so it's generally not helpful to say "just by recognising". We always appreciate pull requests in simple and hard fixes alike, but I think you'll find that it's not "just by".

> LaTeX question, does it matter which order \centering and \begin{table} go? 

`\begin{table}` introduces a whole float environment, adding `\centering` before it is likely to do nothing.

**Comment by hughjonesd** [comment]
I understand that you're doing a lot, and sure "just by" is easier said than done. But it can't be purely the huxtable-specific initialisation code: the pure TeX example that I gave also triggers the bug.

**Comment by cscheid** [comment]
> But it can't be purely the huxtable-specific initialisation code: the pure TeX example that I gave also triggers the bug.

I explained that in my [first comment](https://github.com/quarto-dev/quarto-cli/issues/8841#issuecomment-1959667121), and it's a different bug. That one we're going to fix right away.

**Comment by hughjonesd** [comment]
Great. That's the bug I actually reported. I spent an hour coming up with two test cases for you. I do not appreciate being patronised for it.

**Comment by cscheid** [comment]
I think I'm getting my tone wrong. I wrote that to document the current behavior of the code, and to acknowledge that your assessment of that part was correct, but that we won't be able to fix the more general behavior.

In any case, the PR should be up shortly.
