### ISSUE TITLE
Quarto Book won't render PDF with flextable

### ISSUE THREAD

**Issue by jonpeake** [quarto-dev/quarto-cli#8843]
### Bug description

I had previously reported this for a previous version of quarto/flextable (https://github.com/quarto-dev/quarto-cli/issues/5126) but it seems that this issue has reared its head again. When I try to render a pdf book with a basic flextable in the latest version of quarto release (1.4.550), I get the error message from the previously referenced issue:
```
compilation failed- error
Undefined control sequence.
<argument> \Oldarrayrulewidth 
                              
l.260 ...ngth{\Oldarrayrulewidth}{\arrayrulewidth}
```
If I revert back to the version of quarto that ships with the current RStudio version (1.3.450), things work as expected and the pdf renders fine. Any idea what may have changed between the latest version and the earlier version that has broken this functionality again?

### Steps to reproduce

Create quarto book project, add following to index.qmd:
````
```{r}
library(flextable)
flextable(head(mtcars))
```
````

### Expected behavior

PDF should render as it does in quarto v1.3.450

### Actual behavior

Quarto renders latex output, then xetex spits out the following error message:
```
compilation failed- error
Undefined control sequence.
<argument> \Oldarrayrulewidth 
                              
l.260 ...ngth{\Oldarrayrulewidth}{\arrayrulewidth}
```

### Your environment

RStudio 2023.12.1 Build 402
Windows 10

### Quarto check output
```
Quarto 1.4.550
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.550
      Path: C:\Users\jonathan.peake\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.02
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\jonathan.peake\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.7
      Path: C:/Users/jonathan.peake/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 4.11.1
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\jonathan.peake\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\jonathan.peake\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK
```

**Comment by jonpeake** [comment]
Quarto 1.4.550
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.550
      Path: C:\Users\jonathan.peake\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.02
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\jonathan.peake\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.7
      Path: C:/Users/jonathan.peake/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 4.11.1
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\jonathan.peake\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\jonathan.peake\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK

**Comment by cscheid** [comment]
I confess to be confused by what's going on.

- This works in 1.3, doesn't in 1.4.

- The latex dependency is added by `flextable` and somehow not captured in book rendering anymore

The specific lines that are missing come [from here](https://github.com/davidgohel/flextable/blob/master/R/latex_str.R#L52-L58):
```r
  x$hhline <- latex_dependency(
    name = "hhline",
    extra_lines = c(
      "\\newlength\\Oldarrayrulewidth",
      "\\newlength\\Oldtabcolsep"
    )
  )
```

- We have you reported a bug on flextable in the past about [named latex dependencies](https://github.com/davidgohel/flextable/pull/533)

But, again, this works in 1.3 and doesn't in 1.4. I can't think of anything we changed in the process that would cause us to no longer track the unnamed dependency

**Comment by cderv** [comment]
For single document, we get the dependencies from **knitr** run to include at this step: 
https://github.com/quarto-dev/quarto-cli/blob/ef2c9266221bcce6fcebc0bee32a54e19196a594/src/command/render/render.ts#L75-L81

For book project it seems `executeResult.includes` is empty somehow, and later step return nothing  either
https://github.com/quarto-dev/quarto-cli/blob/ef2c9266221bcce6fcebc0bee32a54e19196a594/src/command/render/render.ts#L89-L109

Now I need to understand why...

**Comment by cderv** [comment]
Ok found the problem. 

> But, again, this works in 1.3 and doesn't in 1.4. I can't think of anything we changed in the process that would cause us to no longer track the unnamed dependency

This is a change in R code I made about dependency handling in 1.4. 

As you said, the fix is not correct for books. For books, we are leveraging some R code to detect dependencies outside of knitr process and context. So function used during this specific code path in R can't assume some knitr options are set. 

I have a fix - probably worth backporting is you are ok.

**Comment by jonpeake** [comment]
Thanks for the timely fix on this, greatly appreciate it!

**Comment by 406396** [comment]
@cderv When will the 1.4 patch be released?

**Comment by cscheid** [comment]
@406396 please don't tag individual devs directly in this way to ask general questions; instead, just respond to the issue and we'll get to it when we get a chance. 

We release stable patches about every two weeks

**Comment by egouldo** [comment]
I'm having this very same problem on quarto 1.7.33 and the latest version of flexible 0.9.10 (built after https://github.com/davidgohel/flextable/pull/533 has been merged). 

Is there a quick workaround possible? And would you prefer I created a new issue to track this?

**Comment by mcanouil** [comment]
@egouldo This issue was fixed and closed. Please open a [new discussion](https://github.com/orgs/quarto-dev/discussions) with sufficient information for the team to reproduce. Please use latest version of Quarto (1.8)
