### ISSUE TITLE
Cannot insert image-only page (without a title) into a presentation (unless a workaround is used)

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-cli#885]
Cannot insert image-only page (without a title) into a presentation (unless a workaround is used).

See minimal reproducible example [here](https://github.com/donboyd5/mres/blob/main/quarto_pres_imagepage/index.qmd).

**Comment by jjallaire** [comment]
@cderv Could you take a look at this?

**Comment by cderv** [comment]
The [`auto-stretch` feature](https://quarto.org/docs/presentations/revealjs/advanced.html#stretch) is causing this. 

@donboyd5 current workaround is to add `.nostretch` class on the section, or deactivate `auto-stretch` in YAML. 

I'll push a PR with a fix soon though.

**Comment by cderv** [comment]
@donboyd5 should be solved now. Thanks a lot for the report!

**Comment by donboyd5** [comment]
Thank you!

Don
