### ISSUE TITLE
keep-md with pdf format is returning a pdf.md file rather than an md file

### ISSUE THREAD

**Issue by pschloss** [quarto-dev/quarto-cli#8855]
### Bug description

With previous versions of quarto, rendering a PDF formatted file with the argument `keep-md` would generate a file ending in `.md`. Now it is producing `.pdf.md`

### Steps to reproduce

`test.qmd`:

````
---
format:
  pdf:
    documentclass: article
    keep-md: true
---

This is a test
````

Running...
```
quarto render test.qmd
```

### Expected behavior

Should produce `test.pdf` and `test.md`.

### Actual behavior

 Produces `test.pdf` and `test.pdf.md` instead. The `test.pdf.md` file looks like a normal markdown file...

````
---
format:
  pdf:
    documentclass: article
    keep-md: true
---



This is a test
````

### Your environment

- VSCode
- Linux

### Quarto check output

```
Quarto 1.4.550
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.58.3: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.550
      Path: /home/pschloss/miniconda3/envs/martino/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/pschloss/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6 (Conda)
      Path: /home/pschloss/miniconda3/envs/martino/bin/python
      Jupyter: 5.5.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /home/pschloss/miniconda3/envs/martino/lib/R
      LibPaths:
        - /home/pschloss/miniconda3/envs/martino/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
That's not a bug, that's an intentional change so that intermediate files of different formats are available.

**Comment by mcanouil** [comment]
If you need/want a markdown file as output `keep-md` is not the option for that, `format: markdown` is.

**Comment by cscheid** [comment]
> If you need/want a markdown file as output keep-md is not the option for that, format: markdown is.

To expand: the output of `keep-md: true` is not the same as the output of `format: markdown`. The output of `format: markdown` goes through quarto's processing (so shortcodes, crossrefs etc are resolved). `keep-md` refers to the result of the engine execution. It's really meant as a debugging option more than anything else.

**Comment by pschloss** [comment]
Thanks for the help - this did the trick.
