### ISSUE TITLE
Publish workflow for scientific papers does not run

### ISSUE THREAD

**Issue by tcbakker** [quarto-dev/quarto-cli#8861]
### Bug description

In Github in the actions tab the following error message is returned after following the instructions for https://quarto.org/docs/manuscripts/publishing.html from the tutorial on atuthoring https://quarto.org/docs/manuscripts/authoring/rstudio.html:

build-deploy Process completed with exit code 1.
--
build-deployNode.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Process completed with exit code 1.
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Expected behavior

A published paper.

### Actual behavior

The error code above.

**Comment by dragonstyle** [comment]
Thanks for reporting this! I've updated the template repositories to use the latest version of the `checkout` action which doesn't depend upon node 16. The commit is here in case you'd like to apply this locally:

https://github.com/quarto-ext/manuscript-template-jupyter/commit/817eebedd3d1e883363afc52564e6169376f09de

This shouldn't result in the publish failing, AFAIK - it is merely a warning about an upcoming deprecation. If you are still seeing a publishing error, it would be helpful to see the actual action output (or a link to the failing publish run) to   assist debugging!

**Comment by mcanouil** [comment]
FYI, <https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/> about Node 16 end of life and deprecation notice.
