### ISSUE TITLE
Quarto document gets corrupted on save

### ISSUE THREAD

**Issue by shirikov** [quarto-dev/quarto-cli#8879]
### Bug description

When working on a Quarto document (markdown text + R code chunks), sometimes, when I press Ctrl+S (or click "Save" in the menu), the document is replaced with empty lines, each starting with a symbol "#". It's not saved, however. When I revert back to the previous text (via Ctrl+Z), in most cases, Ctrl+S works correctly the second time and saves the document. However, sometimes, I have to repeat this multiple times (Ctrl+S, Ctrl+Z, Ctrl+S, Ctrl+Z, etc.) to save the document correctly. This happens both in VSCode and RStudio.

### Steps to reproduce

I can't reproduce it because it happens randomly with different documents.

### Expected behavior

The document should be saved normally.

### Actual behavior

The document is replaced with empty lines.

### Your environment

- IDE: RStudio 2023.06.1 Build 524, VS Code 1.86.2
- OS: Windows 11

### Quarto check output

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: C:/Users/shiri/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.5.0
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Program Files\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Program Files\Quarto\share\jupyter\notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[>] Checking Jupyter engine render....OK

**Comment by cscheid** [comment]
For this particular behavior you're describing, I believe VS Code and RStudio use different code paths, and they're unrelated to Quarto. That makes me suspect that you either have found exactly the same bugs in two different code bases (https://github.com/quarto-dev/quarto and https://github.com/rstudio/rstudio) or there's something in your computer setup that is causing the issue.

In either case, though, this is not the correct repository to file the issue, so we won't be able to help you.
