### ISSUE TITLE
pdf-engine-opt doesn't support multiple engine options

### ISSUE THREAD

**Issue by memeplex** [quarto-dev/quarto-cli#8897]
### Bug description

pandoc `--pdf-engine-opt` option has to be given multiple times in order to pass multiple arguments to the underlying engine. But `pdf-engine-opt` metavar can only take one string value. Then a value like `-auxdir=/tmp/aux -emulate-aux-dir` will behave as if `auxdir='/tmp/aux -emulate-aux-dir'` had been passed instead, because there is no further splitting of arguments.

### Steps to reproduce

Create a project with a config like this:

```
project:
  title: "test"

format:
  pdf:
    pdf-engine: latexmk
    pdf-engine-opt: -auxdir=/tmp/aux -emulate-aux-dir
    latex-auto-mk: false
```

Add an empty `test.qmd` file.

Then run `quarto render test.qmd --to pdf` and check that the directory `/tmp/aux -emulate-aux-dir` has been created.

### Expected behavior

Passing multiple options to the underlying engine must be supported. Some possibilities:

- Using an escapable separator in the `pdf-engine-opt` string.
- Making `pdf-engine-opt` a list, but brings backwards compatibility problems.
- Adding a `pdf-engine-opts` list to the metadata.

I believe the first one is ok. For example `,` as a separator and `,,` if you want an actual comma.

### Actual behavior

Described above.

### Your environment

macOS Sonoma 14.3.1
VSCode  1.86.2

### Quarto check output

```
Quarto 1.4.550
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.550
      Path: /Users/carlos/.venvs/base/lib/python3.11/site-packages/quarto_cli/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.02
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/carlos/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.8
      Path: /Users/carlos/.venvs/base/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /opt/homebrew/Cellar/r/4.3.2_1/lib/R
      LibPaths:
        - /Users/carlos/.rlibs/base
        - /Users/carlos/Documents/Util
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.2_1/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by memeplex** [comment]
By the way, the report was motivated because when trying to configure quarto to run with `latexmk` and `-outdir=/tmp/out`, which is how I usually invoke pandoc in order to keep intermediate files and accelerate the build, quarto was producing corrupted pdfs. More precisely, the one in `/tmp/out/input.pdf` was fine, but the final one, say, `test.pdf` was larger and I wasn't able to open it with Preview. So I start trying other combinations of engine parameters and realized that it was having trouble with multiple parameters. But I feel that the combination `latexmk -outdir=/tmp/out` should be working as well. At least I see no difference in behavior for pandoc when running it like:

```
pandoc test.md --to pdf --pdf-engine latexmk --pdf-engine-opt '-outdir=/tmp/out' -o test.pdf
```

or like

```
pandoc test.md --to pdf --pdf-engine pdflatex -o test.pdf
```

it just produces `test.pdf` in the current directory. If you think this should be working as well for quarto I can file another report.

**Comment by cderv** [comment]
Let me try clarify existing behavior for Quarto and Pandoc too. Our doc is not the clearest on this I believe, and some info are still in Pandoc's Manual. 

There is available two options `pdf-engine-opt` and `pdf-engine-opts`. Both are available to be set in YAML 
* `pdf-engine-opt` is taking a single string, following `--pdf-engine-opt` CLI flag for pandoc, also a CLI flag for quarto.
* `pdf-engine-opts` is another supported way to pass options as YAML field using array. 

They are both available for pandoc in the default file syntax (https://pandoc.org/MANUAL.html#options-affecting-specific-writers-1) which is what Quarto uses to pass command line options to Pandoc. 

Our doc for alternated engines (https://quarto.org/docs/output-formats/pdf-engine.html#alternate-pdf-engines) tells 
> You can use the `pdf-engine` and `pdf-engine-opts` to control the PDF engine that Quarto uses to compile the LaTeX output into a PDF

(note the `s` for `pdf-engine-opts`) but shows an example with `pdf-engine-opt` as a string. 

The pandoc's manual does not make it clear what is really supported as a string in the doc (https://pandoc.org/MANUAL.html#option--pdf-engine-opt) 
> Use the given string as a command-line argument to the pdf-engine. For example, to use a persistent directory foo for latexmk’s auxiliary files, use [--pdf-engine-opt=-outdir=foo](https://pandoc.org/MANUAL.html#option--pdf-engine-opt). Note that no check for duplicate options is done.

So we could understand that a string with several CLI flag could be working. However, trying your options with bare pandoc 
(to be clear, setting `latex-auto-mk: false`  means that Pandoc will handle the conversion)
````powershell
pandoc -t latex -o test.pdf --pdf-engine=latexmk --pdf-engine-opt='-auxdir=aux -emulate-aux-dir' index.md
````
it will create the `aux -emulate-aux-dir` and not just the `aux`.  So it seems Pandoc is not splitting the arg, and this creates the issue. As you said, the flag needs to be passed several times. 

If you now leverage `pdf-engine-opts` with an **s**, this should work in Quarto 

````yaml
format:
  pdf:
    pdf-engine: latexmk
    pdf-engine-opts:
      - '-auxdir=auxdir'
      - '-emulate-aux-dir'
    latex-auto-mk: false
```` 

`auxdir` is created for me and no more merged with `-emulate-aux-dir`


So we have a documentation to improve, but there could also be a Pandoc bug if you would like to report.

**Comment by memeplex** [comment]
Thank you for the very detailed explanation!

> There is available two options pdf-engine-opt and pdf-engine-opts

And I thought you weren't ever going to accept this suggestion :)

> The pandoc's manual does not make it clear 

That's true. I inferred it from some examples and from the "Note that no check for duplicate options is done" caveat. Notice that this warning in quarto's documentation of `pdf-engine-opt` (which is taken directly from pandoc's) leads one to believe that `pdf-engine-opt` supports multiple options somehow.

>  So it seems Pandoc is not splitting the arg, and this creates the issue.

IMO this is quite standard behavior, it would be weird if a command split an argument in an undocumented fashion, trying to emulate the shell. Shells have their own complex ways. I don't think there is a bug in pandoc in this regard but it's certainly missing some documentation explaining that the flag can be passed multiple times. That said, it's a pattern that one comes to expect from pandoc since it's not the only option that works like that.

What do you think of this other problem https://github.com/quarto-dev/quarto-cli/issues/8897#issuecomment-1965776022? There's probably some bad interaction going between the options quarto is passing to pandoc and the latexmk engine, some assumption about where the output or some intermediary file ends up that is wrong, but in standard pandoc invocations like the ones I presented the behavior is similar to that of other engines.

**Comment by memeplex** [comment]
> I inferred it from some examples and from the "Note that no check for duplicate options is done" caveat.

And also because of this comment: https://github.com/jgm/pandoc/issues/3195#issuecomment-464302841

Notice that the latexmk engine was added to pandoc addressing an old FR of mine, so perhaps you can understand why I'm so obsessed with getting it work nicely in quarto too :). Seriously, it's quite faster if you keep the intermediate files somewhere.

**Comment by cderv** [comment]
> And I thought you weren't ever going to accept this suggestion :)

This was already there, just undocumented - unless you knew about Pandoc's variable name, this was not findable. This is fixed now. 

> keep the intermediate files somewhere

If you set `latex-clean: false`, the intermediate should not be removed after compilation. See https://quarto.org/docs/output-formats/pdf-engine.html#pdf-compilation

Maybe this is what you are looking for ? 

> What do you think of this other problem https://github.com/quarto-dev/quarto-cli/issues/8897#issuecomment-1965776022?

> simple test.qmd input produces a test.pdf that Preview can't open (although /tmp/out/input.pdf is of different size and opens fine)

Quarto Preview isn't meant to work with situations where you are changing the way Quarto expect structure, especially regarding directories. Quarto is designed to work inside a Project structure. By setting `-oudir` to an absolute path elsewhere, this breaks the expectation of a relative to project path. 

I would not expect Quarto preview to work in this situation where you tweak the pdf rendering behavior. It also breaks Preview is you set to a relative directory, e.g `-outdir=out`, but this is also expected to break as Quarto has no knowledge of `latexmk` option. `-outdir` is only passed to `latexmk` - quarto feature like preview needs to no where the file to open is and it can't know in this situation. 

`quarto render` works fine to produce the pdf in `-outdir` - with `latex-auto-mk: false`, pandoc will do the pdf rendering, and it works like pandoc is working. Note that Pandoc does not have a preview feature. 

For quarto feature to work, it is best to use Quarto direct features. You could something like this 

````yaml
format: 
  pdf: 
    pdf-engine: latexmk
    latex-clean: false
    latex-output-dir: "out"
````

`quarto preview` now know `what the `latex-output-dir` is and it will work. 


Though even with this, there is an issue with previewing in RStudio IDE - they must use another logic than `quarto preview` server and it needs to be made aware of `latex-output-dir`. 

Hope it helps understand the whole logic

**Comment by memeplex** [comment]
I think we have a misunderstanding, I was talking about macOS Preview, not quarto preview. What I meant was that the produced pdf was corrupt.

This is enough to reproduce the problem:

```
echo foobar > test.qmd
quarto render test.qmd --to pdf -M pdf-engine:latexmk -M pdf-engine-opt:-outdir=/tmp/out -M latex-auto-mk:false
open test.pdf
```

<img width="268" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/2845433/ad720e63-bce5-4807-8b6e-fd17ba609f21">

```
❯ ls -l /tmp/out/input.pdf
-rw-r--r-- 1 carlos wheel 25023 Feb 28 12:49 /tmp/out/input.pdf

❯ ls -l test.pdf
-rw-r--r-- 1 carlos wheel 44512 Feb 28 12:49 test.pdf
```

**Comment by cderv** [comment]
Oh I see. Yes the correct PDF is in `-outdir=/tmp/out` - it was not renamed by with qmd input file probably because `-oudir` is not known to Quarto, so quarto expects as output a test.pdf in the working directory.

There should be no `test.pdf` in project folder, and as `-outdir` was provided directly to latexmk. 

We'll see if we can avoid this - but this is really edge case usage as it is not using Quarto feature made to control LaTeX rendering. I shared what I think is the expected usage at https://github.com/quarto-dev/quarto-cli/issues/8897#issuecomment-1969236737

**Comment by memeplex** [comment]
Moreover, notice that as I mentioned before, pandoc correctly produces a pdf output in the current directory in each case, it's not like the outdir option is confusing it (that was my first thought and the reason why I attempted to change it to auxdir, but it doesn't seem to be the cause, although I don't know how to inspect the specific CLI args pandoc is getting from quarto).

```
❯ cp test.qmd test.md

❯ rm test.pdf
❯ pandoc test.md --to pdf --pdf-engine latexmk --pdf-engine-opt '-outdir=/tmp/out' -o test.pdf
❯ ls -l test.pdf
-rw-r--r-- 1 carlos wheel 25026 Feb 28 12:55 test.pdf

❯ rm test.pdf
❯ pandoc test.md --to pdf --pdf-engine pdflatex -o test.pdf
❯ ls -l test.pdf
-rw-r--r-- 1 carlos wheel 25026 Feb 28 12:55 test.pdf
```

**Comment by memeplex** [comment]
> I shared what I think is the expected usage at https://github.com/quarto-dev/quarto-cli/issues/8897#issuecomment-1969236737

Yes, I know, I was trying to put the clutter elsewhere. If there is a way to know the exact pandoc invocation quarto is doing, I can help trace the source of the problem. In any case, I'm closing this because the multiple engine options issue was already addressed. Thanks!
