### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by fernandortdias** [quarto-dev/quarto-cli#8902]
### What would you like to do?

Report an issue on quarto.org

### Description

https://quarto.org/docs/projects/quarto-projects.qmd#directory-metadata is broken in Quarto Tutorial.

**Comment by mcanouil** [comment]
Thanks for the report.
Could you link to the page (and section) of the broken link rather than sharing the broken link? Thank you.

**Comment by cderv** [comment]
We use it here: 
https://github.com/quarto-dev/quarto-web/blob/cd710d94b8318cbeeb3b56ecaccabbbe3c158a6b/docs/output-formats/html-multi-format.qmd#L90

This links works ok if we look at the rendered link at  https://quarto.org/docs/output-formats/html-multi-format.html#controlling-formats-at-a-project-level 

and also here in a file we will include

https://github.com/quarto-dev/quarto-web/blob/cd710d94b8318cbeeb3b56ecaccabbbe3c158a6b/docs/websites/_page-navigation.md#L20

And this is where it does not work, seeing the link at the place where they are included: 
- https://quarto.org/docs/websites/website-navigation.html#page-navigation
- https://quarto.org/docs/books/book-structure.html#page-navigation

We use this in markdown link
````mardkown
[`_metadata.yml`](https://quarto.org/docs/projects/quarto-projects.qmd#directory-metadata)
```

Usually a link ending with `.qmd` will be change to `.html`, e.g 
````markdown
[link](https://quarto.org/docs/projects/quarto-projects.qmd)
````

but here they are not transformed. Maybe something related to `include` shortcode ? 

Or just a documentation rendering issue. We need to check

cc @cwickham as you added this in a PR recently (quarto-dev/quarto-web#968) - checking the preview which is still up, it was already broken at the time.

**Comment by mcanouil** [comment]
Why does an internal link use `https://quarto.org/`? It should be an absolute path (from Quarto project root), to ensure it works everywhere, i.e., `/docs/projects/quarto-projects.qmd`. I might be missing the rational behind the use of `https://quarto.org/`.

**Comment by fernandortdias** [comment]
> Thanks for the report. Could you link to the page (and section) of the broken link rather than sharing the broken link? Thank you.

At https://quarto.org/docs/books/book-structure.html

**Comment by cwickham** [comment]
You are right, those links should definitely not start with `https://quarto.org/`. Probably a copy-paste-edit error on my part. 

@mcanouil I think a PR to fix all these links would be great! 

We had talked about link checking before (#5399), I wonder if this is a good time to implement that too. Not that all of those 178 links are broken, but it'd be good to check we don't break them in the process.
