### ISSUE TITLE
[GHA] Adapt our release-info action to Node 20

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#8906]
Github is transitioning from node 16 to node 20 
* https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

and one of our custom action is using node 16
https://github.com/quarto-dev/quarto-web/blob/1e689477e543b13d11ec5b3393e4a396f8538bc4/.github/workflows/actions/release-info/action.yml#L29-L31

So we'll need to adapt.

This is related to #7922 too

**Comment by mcanouil** [comment]
FYI;
- https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by cderv** [comment]
Yes I saw that - thanks for adding the link
