### ISSUE TITLE
Missing Edit this page button in book parts

### ISSUE THREAD

**Issue by olivroy** [quarto-dev/quarto-cli#8908]
### Bug description

In R4DS, deployed via gh actions, there is no Edit this page link for Parts on the right.
![image](https://github.com/quarto-dev/quarto-cli/assets/52606734/d0497cdf-3240-403e-a008-8cfba6cbc9f9)

https://r4ds.hadley.nz/visualize

While it is present in regular chapters
https://r4ds.hadley.nz/data-tidy

Seeing the same thing in https://r-spatial.org/book/part-3.html

### Steps to reproduce

Go to the website and see that the button is not there on the right side

### Expected behavior

No Edit this page button in Parts

### Actual behavior

I would expect the Edit this page button to show for both parts and regular chapters.

### Your environment

N/A

### Quarto check output

Quarto latest release 1.4.550

**Comment by cscheid** [comment]
Sorry, it's typically not very helpful for us if youfile bug reports on _other people's documents_. Can you create a minimal document that reproduces your expectations and you control?

**Comment by mcanouil** [comment]
There is no bugs.
Firstly, users can disable the button on specific pages, so if you are not the author of the content please, report first to the authors.
Secondly, the button is there. If there is a table of contents it is placed below it, but when there is no table of contents, it's in the footer.

I am going to close this as there is no bug and the contents is from someone else.

**Comment by olivroy** [comment]
Apologies, I didn't notice it defaulted to going to the footer when there was no table of content in the chapter. Thanks!
