### ISSUE TITLE
Blog listing with combination of posts and metadata file incomplete

### ISSUE THREAD

**Issue by bbac63** [quarto-dev/quarto-cli#8914]
### Bug description

I have a website defined with an embedded blog where I want to show the contents as listing merged from posts and a yaml (metadata) file as documented [here](https://quarto.org/docs/websites/website-listings.html#yaml-listing-content). However, when I render the website only posts are shown in the output not the content from the metadata file. When I render locally (within the Blog directory) it works as expected: The items from the metadata file and the posts are listed.

### Steps to reproduce

Files for a minimal project are attached [Quarto_Testing.zip](https://github.com/quarto-dev/quarto-cli/files/14432169/Quarto_Testing.zip)

### Expected behavior

List the contents from the posts directory as well as from the metadata file.

### Actual behavior

Only the contents from the posts directory are listed. When I remove the posts as input (in index.qmd) the content from the metadata file is shown.

### Your environment

IDE:  RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-29) for Ubuntu Jammy Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

OS: Linux Mint 21.3 Virginia (Ubuntu 22.04)

### Quarto check output

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/bernd/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /tmp/RtmpabXgIO/rstudio/terminal/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

R scripting front-end version 4.1.2 (2021-11-01)
[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by mcanouil** [comment]
Thanks for the report.
Could you share your website project as a Git repository which is much easier to handle and also allows us to directly spot any obvious mistake in the setup?

**Comment by bbac63** [comment]
Does [this](https://github.com/bbac63/Quarto_Testing) work for you?

**Comment by mcanouil** [comment]
Yes. <https://github.com/bbac63/Quarto_Testing> works.

Side note: do not "hide" URL behind uninformative words such as "this", "here", etc. Screen readers won't be able to tell users what "this" is, only that's a link.

**Comment by mcanouil** [comment]
Why is there a project inside your project?

```txt
.
├── News
│   ├── _quarto.yml
│   ├── about.qmd
│   ├── archived-items.yaml
│   ├── index.qmd
│   ├── posts
│   │   ├── _metadata.yml
│   │   ├── post-with-code
│   │   │   ├── image.jpg
│   │   │   └── index.qmd
│   │   └── welcome
│   │       ├── index.qmd
│   │       └── thumbnail.jpg
│   ├── profile.jpg
│   └── styles.css
├── Website.Rproj
├── _quarto.yml
├── about.qmd
├── index.qmd
└── styles.css

5 directories, 16 files
```

**Comment by bbac63** [comment]
I am going to build a website with several levels of content, each of which can be a separate project, e.g. a blog, a newsfeed, a book, html pages. Does this mean that I have to model everything directly at the top level and not build some logical substructure?

I took the term "metadata" for the `archived-items.yaml` file from the Quarto documentation at https://quarto.org/docs/websites/website-listings.html#yaml-listing-content. It is not metadata from a Quarto point of view, but the metadata of the content to be listed.

**Comment by mcanouil** [comment]
Thanks for explaining the rational here.
Projects were never intended to be nested.

FYI:
- https://github.com/quarto-dev/quarto-cli/discussions/3505

In the end, I am pretty sure there is no bug but rather a misuse.

**Comment by bbac63** [comment]
Thx. @mcanouil for the clarification: I will reorganize the project and may work with scripts to shuffle some data around.
