### ISSUE TITLE
Lists are not aligned properly inside `.columns` div containers with Revealjs

### ISSUE THREAD

**Issue by mroavi** [quarto-dev/quarto-cli#892]
<details>
  <summary>Minimal working example</summary>
  
  ```md
---
title: "Habits"
author: "John Doe"
format:
  revealjs:
    incremental: false   
    footer: "Footer text"
---

## Minimal working example

Normal alignment

- Element 1

- Element 2

* Element 3

:::: {.columns}

::: {.column width="50%"}
Buggy alignment

- Element 1

- Element 2

* Element 3

:::

::: {.column width="50%"}
Buggy alignment

- Element 1

- Element 2

* Element 3

:::

::::

  ```
</details>

produces

![image](https://user-images.githubusercontent.com/19517248/168594881-19391e12-88c0-4736-acb6-8486ac77350a.png)

**Comment by mroavi** [comment]
I copy-pasted the changes you made in https://github.com/quarto-dev/quarto-cli/commit/d987a8c5323da914ee7f3e3c553c111c15569ec6 to a custom theme. Unfortunately, the problem does not seem to be fixed.

**Comment by jjallaire** [comment]
You shouldn't need to put those in a theme since they are built in to Quarto

**Comment by mroavi** [comment]
But as far as I understand, these should overwrite them.. right? The thing is that I still have an old build and wanted to check if these changes solve the issue indeed.

**Comment by jjallaire** [comment]
I don't know for certain how the theme css composes with our built in css rules (they may have priority as they are considered "application level" behavior that shouldn't be customized). I would just try the new build

**Comment by mroavi** [comment]
I verified that this is fixed indeed in the latest build.

**Comment by jjallaire** [comment]
Great, thanks!
