### ISSUE TITLE
New toolbar preview for Quarto VS CODE extension

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#8943]
### What would you like to do?

Give feedback or suggest an improvement

### Description

Following change in VS CODE, quarto-dev/quarto#387 was reported for change in toolbar 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/cfc0da0a-ee83-40c2-b1ab-3ec714d9a608)

It was fixed ( in https://github.com/quarto-dev/quarto/commit/55b895015ba207e95f9a332304989e3520ea91b6) and new extension version was published as 1.111.0. 

It now looks like 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/057e6b29-9eac-4ba5-b2ff-d4417454d465)
Our docs needs to be updated to reflect this.

**Comment by cwickham** [comment]
Adding some instances where this needs changing.

Explicit mentions/screenshots of button (some of which still refer to "Render button"):

* https://quarto.org/docs/tools/vscode.html#render-and-preview
* https://quarto.org/docs/get-started/hello/vscode.html#render-and-preview
* https://quarto.org/docs/get-started/computations/vscode.html#overview
* https://quarto.org/docs/manuscripts/authoring/vscode.html#workflow
* https://quarto.org/docs/computations/r.html#vs-code (no screenshot here, but "Preview" button will need clarifying)
* https://quarto.org/docs/books/index.html#quick-start
* https://quarto.org/docs/websites/website-blog.html#quick-start
* https://quarto.org/docs/websites/index.html#quick-start

There are lots of screenshots where the old "Preview", or even older "Render", button are shown, but where they aren't the focus of the content. I suggest we leave these for now and update as the content is updated.
