### ISSUE TITLE
Code execution failure in documents on Windows mapped drives

### ISSUE THREAD

**Issue by Hemken** [quarto-dev/quarto-cli#8972]
### Bug description

When attempting to render documents with executable R code cells in a QMD file, the document fails to render.

This is specifically a problem when the document is on a Windows mapped drive.  Documents that are pure Markdown render correctly from the mapped drive.  And the same documents render correctly when rendered from a local drive.

### Steps to reproduce

- In a mapped network drive on a Windows computer, create a default test project `quarto create project <default> testq`
- Add to file `Testq.qmd` any R code block
  ````
  ```{r}
  2 + 2
  ```
  ````
- render the file

### Expected behavior

This should have produced an output document

### Actual behavior

Instead it produces the error message, and indeed the temporary folder mentioned is left behind:

ERROR: An unexpected network error occurred. (os error 59): remove 'Z:\testq\Testq_files\execute-results'

Stack trace:
    at Object.removeSync (ext:deno_fs/30_fs.js:189:7)
    at removeIfExists (file:///C:/Program%20Files/Quarto/bin/quarto.js:5336:14)
    at removeFreezeResults (file:///C:/Program%20Files/Quarto/bin/quarto.js:76955:5)
    at renderExecute (file:///C:/Program%20Files/Quarto/bin/quarto.js:77043:9)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async renderFileInternal (file:///C:/Program%20Files/Quarto/bin/quarto.js:77194:43)
    at async renderFiles (file:///C:/Program%20Files/Quarto/bin/quarto.js:77062:17)
    at async renderProject (file:///C:/Program%20Files/Quarto/bin/quarto.js:77389:25)
    at async renderForPreview (file:///C:/Program%20Files/Quarto/bin/quarto.js:82813:26)
    at async render (file:///C:/Program%20Files/Quarto/bin/quarto.js:82698:29)

### Your environment

- IDE:  VS Code Version: 1.86.2 (system setup)
- OS: Windows_NT x64 10.0.19045

### Quarto check output

Quarto 1.4.550
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.550
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: Installation From Path
      Path: C:\Program Files\texlive\2023\bin\windows
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: C:/ProgramData/Anaconda3/python.exe
      Jupyter: 4.10.0
      Kernels: julia-1.6, julia-sscc-1.6, sas, stata, python3

[>] Checking Jupyter engine render....OK

(/) Checking R installation...........Finished Rprofile.site
[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - U:/R/4.3.2
        - C:/Program Files/R/R-4.3.2/site-library
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Duplicate of a number of issues here: https://github.com/quarto-dev/quarto-cli/labels/file-systems
