### ISSUE TITLE
Add documentation on how to use environment variables

### ISSUE THREAD

**Issue by maia-sh** [quarto-dev/quarto-cli#8973]
### What would you like to do?

Report an issue on quarto.org

### Description

I would suggest adding documentation on how to use environment variables within the page https://quarto.org/docs/projects/environment.html
Why? I just spent a while trying to figure out this seemingly basic task 😅 and eventually stumbled on https://github.com/quarto-dev/quarto-cli/discussions/2531 and https://github.com/quarto-dev/quarto-cli/discussions/5593

I'd suggest a small section with links to the other sections, e.g., https://quarto.org/docs/authoring/variables.html#env
Currently, the `env` shortcode is not mentioned in the Environment page.
Nice to have would be basic info on usage in the supported languages, e.g., `Sys.getenv()` in R

**Comment by cscheid** [comment]
Thanks for the feedback.

> Nice to have would be basic info on usage in the supported languages, e.g., Sys.getenv() in R

We're unlikely to do this; Quarto's documentation is meant to teach Quarto, and using it to teach people how to use the languages supported in its engines would make it less focused and harder to search for.

> Currently, the env shortcode is not mentioned in the Environment page.

That page describes how Quarto configures the environment for projects; it's not for authoring documents. The documentation for authoring is in the authoring guide. A search for "environment variable" shows it:

<img width="952" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/b510090b-c2a1-463b-b78f-0e26631c8148">

The relevance of the project page being higher than that of the authoring page is unfortunate, but it's still the second page.
