### ISSUE TITLE
Variable substitution does not work for title in head block

### ISSUE THREAD

**Issue by has2k1** [quarto-dev/quarto-cli#8987]
### Bug description

Variable substitution using the `var` shortcode does not work for the project title in the `<head>` block. It is a regression compared to the stable version `1.4.550`.

### Steps to reproduce

1. Create quarto websiteproject with a title that uses a `var` shortcode.
2. Create variables file & define the variabl.
3. Render website and search for unsubstituted shortcode.

**copy & paste test**
```sh
quarto create project website . Title --no-prompt;
echo "version: 1.2.3" >> _variables.yml;
sed -i '' -e 's/  title: "Title"/  title: "{{< var version >}}"/' _quarto.yml;  # macos sed
# sed -i 's/  title: "Title"/  title: "{{< var version >}}"/' _quarto.yml;  # gnu sed
quarto render;
grep "var version" _site/index.html
```
Creates the key files

**_quarto.yml**

```yaml
project:
  type: website

website:
  title: "{{< var version >}}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

**_variable.yml**

```yaml
version: 1.2.3
```

### Expected behavior

```html
<title>1.2.3 – Title</title>
```

### Actual behavior

```html
<title>{{&lt; var version &gt;}} – Title</title>
```

The release version works but renders with some lua noise.

```console
$ quarto render
[1/2] index.qmd
r1      [Str "1.2.3"]
r2      [Str "1.2.3"]
r1      [Str "1.2.3"]
r2      [Str "1.2.3"]
r1      [Str "1.2.3"]
r2      [Str "1.2.3"]
r1      [Str "1.2.3"]
r2      [Str "1.2.3"]
r1      [Str "1.2.3"]
r2      [Str "1.2.3"]
r1      [Str "1.2.3"]
r2      [Str "1.2.3"]
```

### Quarto check output

```bash
Quarto 1.5.23
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.23
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.11
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/hassan/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: /Users/hassan/.pyenv/versions/3.10.4/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Thanks for the report. 

I can confirm this worked in 1.4 and now don't in 1.5. The breakage happens in this commit c8676ca24762ebdb63a2b48f69608c1773be6a36 (PR #8430) to fix #7318 

@dragonstyle , I see your not in PR 
> Note that I confirmed that shortcodes will still render properly and behave in a sane fashion as expected.

Did you expect this usage to work ? If so we should try add a test and fix support.

**Comment by dragonstyle** [comment]
I was expecting that to still work and I think it is important that it does so (often used for things like version numbers in documentation...)

**Comment by cderv** [comment]
Ok. Let's fix then. If you want me to have a look because too busy on other stuff, I can. Just assign back to me.

**Comment by andrewheiss** [comment]
Oh, I'm glad I found this issue! Using stable 1.4.551, variable substitution works fine in the head block, as reported in this issue, but it emits all sorts of extra Lua messages that didn't previously appear (at least up to 1.4.529). It seems that every shortcode is getting two messages in the console output:

<img width="737" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/73663/84cca03f-a2a8-462c-8647-ad9ebf79cd1e">

The extra Lua output doesn't appear in 1.5.27 though, so something has fixed it in the meantime 🤷‍♂️

**Comment by cscheid** [comment]
@andrewheiss We need to hotfix these messages, thank you for letting us know!

**Comment by cscheid** [comment]
This is fixed on 1.4, and a new stable release with this is coming out soon.

**Comment by petrbouchal** [comment]
Not sure if this is the same issue or not: when I try to set title via metadata like so:

```r
quarto::quarto_render("template.qmd", metadata = list(title = "Hahaha", author = "Whoever"))
```

the title set in metadata is not used in the header block or HTML header (nor emitted correctly via `{{< meta title >}}` in the body) *when* a title is set in the document header. When there is no title entry in the YAML header, the title set in metadata is used and does appear in the body.

Setting e.g. the author via metadata works correctly.

**Comment by cscheid** [comment]
This was a totally unrelated bug. The problem here is the existence of this function:

https://github.com/quarto-dev/quarto-cli/blob/4ee3e32ca9f3f920f408ea1973beed528170f34b/src/project/types/website/website-shared.ts#L84-L109

It's called here:

https://github.com/quarto-dev/quarto-cli/blob/92cad4456c4e8b635979d6b39f45b507aba70edb/src/project/types/website/website-meta.ts#L523

The immediate problem is that the function hardcodes the format of the title element. We had changed the template in a few ways and the typescript code wasn't updated. I have a PR that fixes this.

The bigger problem is that this means that our template can't ever change the format of the title, or shortcodes won't expand properly. This is a big bummer that we won't be able to fix in 1.5.

**Comment by cderv** [comment]
> We had changed the template in a few ways and the typescript code wasn't updated

Just for cross-reference, this is where the change in template was discussed. 
- https://github.com/quarto-dev/quarto-cli/issues/8904

> it looks like we don't allow users to change the metadata.html partial, so this isn't a problem.

Which partials are we talking about ? AFAIK `metadata.html` can be modified by user, by providing a file with same filename and setting 

```yaml
format:
  html:
    template-partials:
      - metadata.html
```

If I try this quickly based on this issue example, I can reproduce the shortcode expansion issue. So I think it is still a problem to fix at some point.

**Comment by cscheid** [comment]
We should open a separate issue to track, but it will be a _very_ hard bug to fix.

**Comment by matthew-brett** [comment]
In case it's useful, we just hack round this by post-processing the HTML output : https://github.com/resampling-stats/resampling-with/blob/main/scripts/postprocess_site.py

**Comment by hasibagen** [comment]
I'm encountering a similar issue and wondering if it's caused by the same underlying reason. I’ve opened a new GitHub discussion here with details:

https://github.com/quarto-dev/quarto-cli/discussions/13146

Would appreciate any insights!
