### ISSUE TITLE
Multiple paths  in resource-path cause an issue -- [WARNING] Could not fetch resource 

### ISSUE THREAD

**Issue by elchorro** [quarto-dev/quarto-cli#8989]
### Bug description

Let say I have a folder ` ../Figures` which contains two sub-folder `model1` and `model2`

When I try to add the figures in my document I can use

```
resource-path: 
          - ../Figures
```
and then use relative paths to images e.g. `model1/figA.png` and `model2/figB.png`

However, I would prefer to include both of these folders e.g. 
 ```resource-path: 
          - ../Figures/model1
          - ../Figures/model2
``` 
and then just use `figA.png` and `figB.png`

### Steps to reproduce

Create a .qmd file in `./Code` with the below in configuration
```
format:
    html:
        smooth-scroll: true
        code-fold: true
        resource-path: 
                  - ../Figures/model1
                  - ../Figures/model2
        embed-resources: true
``` 
create images in `../Figures/model1` and `../Figures/model2`

### Expected behavior

Images can be referred to by name in quarto

### Actual behavior

`[WARNING] Could not fetch resource figA.png`
`[WARNING] Could not fetch resource figB.png`

Note also that if I remove one line form `resource-path`, e.g. 

```
resource-path: 
          - ../Figures/model1
```

then figA.png is being found. 

### Your environment

- VSCode
- R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"
- Quarto as below:
quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.330
      Path: C:\Users\elchorro\AppData\Local\Programs\Quarto\bin
      CodePage: 1252
```

### Quarto check output

```

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.330
      Path: C:\Users\XXX\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: C:/Users/XXX/AppData/Local/anaconda3/python.EXE
      Jupyter: 5.3.0
      Kernels: ir, python3

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/XXX/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.24

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Relative paths that take you outside of the project (in the case of a project), or outside of the current directory (in the case of a single-file render) are generally not supported in Quarto.

We need a full repro to be able to know more (a description of how to create a repro is not a good substitute because we might recreate something different from what you have and then both of us waste time figuring it out. Please do send an actual repro.)

With that said, if anything, the issue here appears to be that the first case is succeeding rather than the second case is failing.
