### ISSUE TITLE
render not-a-script.R produces a stack trace

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#8996]
### Bug description

Attempting to `quarto render` an R script that lacks the preamble block produces a stack trace without an explanation of why the content cannot be rendered.

### Steps to reproduce

```bash
mkdir not-a-script
cd not-a-script
touch not-a-script.R
quarto render not-a-script.R
```

### Expected behavior

Quarto tells me that it is unable to identify the script preamble .. or otherwise verify that the script is runnable.

### Actual behavior

```
ERROR: Unable to render not-a-script.R

Stack trace:
    at fileExecutionEngineAndTarget (file:///Applications/quarto/bin/quarto.js:41256:15)
    at renderFileInternal (file:///Applications/quarto/bin/quarto.js:77115:42)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:77062:17)
    at async render (file:///Applications/quarto/bin/quarto.js:81807:21)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:81954:32)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8104:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:114968:5)
    at async file:///Applications/quarto/bin/quarto.js:114986:9
```

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/aron/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
For what it worth, the new message is this one in 1.5

````powershell
> quarto render not-a-script.R
ERROR: Can't determine execution engine for not-a-script.R

Stack trace:
    at fileExecutionEngineAndTarget (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/execute/engine.ts:200:11)
    at async render (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-shared.ts:112:22)
    at async Command.actionHandler (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:149:3)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:163:5
    at async mainRunner (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/main.ts:35:5)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:153:3
````

So it is not detailed about it being an R script, but it mentions no execution engine is detected. 

Do you think this is clearer ? Or do you still think we should try to have more specific error and advice depending on the script itself (.R, .qmd, .ipynb, ...) ? 

The latter would be great user experience for sure.

**Comment by aronatkins** [comment]
The error message in Quarto 1.5 is much better, yes! File-specific messages don't feel needed.

The stack trace feels unnecessary, since this is a problem with the input file and not a Quarto internal error.

**Comment by cderv** [comment]
Yes I was just looking into that. Usually, it appears when in debug mode (when using dev version which set `QUARTO_DEBUG` env var or when explicitly opting in stack trace with `QUARTO_PRINT_STACK` env var. 

But it seems to be shown here without those being set... 🤔 

So I looked and we have now: 
https://github.com/quarto-dev/quarto-cli/blob/b222df50198848437ebcaa2b6489b4b29ddfc907/src/core/log.ts#L335

This changed in 1.4 at 2e405396ec96d7da89b3f717de474637e7f7acdc
````diff
- if (isDebug && err.stack && err.printStack) {
+ if (err.stack && (isDebug || err.printStack)) {
````

And now we print always when `err.printStack` is `true`... This is a change in behavior. 

And in fact I think `printStack` is always set to `true` because we normalize
https://github.com/quarto-dev/quarto-cli/blob/b222df50198848437ebcaa2b6489b4b29ddfc907/src/core/log.ts#L318-L320
and `errorEx` will always set `printStack` when there is a `message`
https://github.com/quarto-dev/quarto-cli/blob/b222df50198848437ebcaa2b6489b4b29ddfc907/src/core/lib/error.ts#L47-L60

So I think we are now always printing the stack trace.

@cscheid is this really the intended change ? 

Thanks

**Comment by cscheid** [comment]
> @cscheid is this really the intended change ?

My intention, iirc, was to have a stack trace when it was requested in an exception without a message. The original commit message for 2e405396ec96d7da89b3f717de474637e7f7acdc says "print stack even if no message is present". We need to think about this more carefully.

**Comment by cderv** [comment]
I understand thanks. We are currently opting-out printing Stack when no message 
https://github.com/quarto-dev/quarto-cli/blob/4b0bbb9709044ff26deb3833a06aa99dc69836f2/src/core/lib/error.ts#L55

So it seems to me that we would like to remove this. 

I still believe we should print stack trace only when `isDebug` is `true`
https://github.com/quarto-dev/quarto-cli/blob/4b0bbb9709044ff26deb3833a06aa99dc69836f2/src/core/log.ts#L332-L334

**Comment by aronatkins** [comment]
Another example of an error that presents a stack: #9030

**Comment by cderv** [comment]
Stack trace issue is now followed at 
* https://github.com/quarto-dev/quarto-cli/issues/9032

@aronatkins I'll close this one as you said 
> The error message in Quarto 1.5 is much better, yes! File-specific messages don't feel needed.

Thanks for the report !
