### ISSUE TITLE
Fix external broken links in documentation broken

### ISSUE THREAD

**Issue by jasonpott** [quarto-dev/quarto-cli#9005]
### What would you like to do?

Report an issue on quarto.org

### Description

The hyperlink to hypothesis documentation is broken.
https://quarto.org/docs/reference/projects/websites.html#hypothesis

![Screenshot 2024-03-07 at 18 29 15](https://github.com/quarto-dev/quarto-cli/assets/43917006/5d51a5b7-dbc9-4d54-b716-bbb0b9db36d7)

![Screenshot 2024-03-07 at 18 30 00](https://github.com/quarto-dev/quarto-cli/assets/43917006/c7806fb5-06f9-4de3-92f1-acd40ca392f2)

**Comment by cderv** [comment]
Thanks for the report. 

Hypothesis changed their website it seems. This is now at https://h.readthedocs.io/projects/client/en/latest/publishers/config.html

**Comment by mcanouil** [comment]
See:
- https://github.com/quarto-dev/quarto-web/pull/1031

**Comment by mcanouil** [comment]
FYI, the current external broken links:

```sh
Getting links from: https://quarto.org/docs/computations/julia.html
└─BROKEN─ http://conda.pydata.org/docs/install/quick.html (HTTP_404)

Getting links from: https://quarto.org/docs/publishing/rstudio-connect.html
├─BROKEN─ https://typst.app/docs/reference/meta/bibliography/ (HTTP_404)

Getting links from: https://quarto.org/docs/authoring/figures.html
├─BROKEN─ https://tablesgenerator.com/markdown_tables (BLC_UNKNOWN)
├─BROKEN─ https://www.tablesgenerator.com/text_tables (BLC_UNKNOWN)

Getting links from: https://quarto.org/docs/authoring/videos.html
├─BROKEN─ https://isni.org/ (HTTP_403)

Getting links from: https://quarto.org/docs/output-formats/html-themes.html
├─BROKEN─ https://rajgoel.github.io/reveal.js-demos/fullscreen-demo.html (HTTP_404)

Getting links from: https://quarto.org/docs/websites/index.html
└─BROKEN─ https://example.com/mysite/ (HTTP_404)

Getting links from: https://quarto.org/docs/websites/website-blog.html
├─BROKEN─ https://www.algolia.com/api-keys (HTTP_404)

Getting links from: https://quarto.org/docs/websites/website-tools.html
└─BROKEN─ https://support.google.com/analytics/answer/2763052?hl=en (HTTP_404)

Getting links from: https://quarto.org/docs/interactive/ojs/libraries.html
├─BROKEN─ https://observablehq.com/@d3/zoomable-sunburst%3E (HTTP_404)

Getting links from: https://quarto.org/docs/interactive/ojs/data-sources.html
└─BROKEN─ https://quartopub.com/profile (HTTP_500)

Getting links from: https://quarto.org/docs/publishing/github-pages.html
└─BROKEN─ https://deno.land/manual/standard_library (HTTP_404)

Getting links from: https://quarto.org/docs/extensions/starter-templates.html
└─BROKEN─ https://www.w3.org/publishing/epub3/epub-packages.html#bib-typesregistry (HTTP_404)

Getting links from: https://quarto.org/docs/reference/formats/presentations/revealjs.html
└─BROKEN─ https://wwwimages.adobe.com/content/dam/acom/en/devnet/indesign/sdk/cs6/idml/idml-specification.pdf (HTTP_404)

Getting links from: https://quarto.org/docs/reference/formats/tei.html
├─BROKEN─ https://deno.land/std@0.125.0/datetime (HTTP_404)
└─BROKEN─ https://h.readthedocs.io/projects/client/en/latest/publishers/config/ (HTTP_404)

Getting links from: https://quarto.org/docs/reference/projects/books.html
├─BROKEN─ https://h.readthedocs.io/projects/client/en/latest/publishers/config/ (HTTP_404)
├─BROKEN─ https://deno.land/std@0.125.0/datetime (HTTP_404)

Getting links from: https://quarto.org/docs/manuscripts/authoring/
├─BROKEN─ https://quartopub.com/profile (HTTP_500)
```

**Comment by mcanouil** [comment]
The following broken links is in Quarto CLI side: `https://www.w3.org/publishing/epub3/epub-packages.html#bib-typesregistry`

- https://github.com/mcanouil/quarto-web/blob/efd2643949850f8a66463c16a0bb3882fb636a46/docs/reference/formats/epub.json#L120-L121

The best replacement I have found is: `https://www.w3.org/publishing/epub32/epub-packages.html#bib-typesregistry` but not quite sure it is correct.

**Comment by mcanouil** [comment]
The two links for ICML have no replacement. The link was already hidden has it appears only in a forum about the ICML specification not very publicly available.
The link was never a very robust one it appears.

- https://github.com/quarto-dev/quarto-web/blob/main/docs/reference/formats/icml.qmd

Any suggestions?

**Comment by mcanouil** [comment]
- https://github.com/rajgoel/reveal.js-demos no longer have the page or code.

```txt
Getting links from: http://127.0.0.1:3002/_site/index.html
├─BROKEN─ https://rajgoel.github.io/reveal.js-demos/fullscreen-demo.html (HTTP_404)
```

**Comment by mcanouil** [comment]
```txt
Getting links from: https://quarto.org/docs/dashboards/examples/index.html
https://github.com/jjallaire/ojs-penguins-dashboard/blob/main/penguins.qmd
-> Very likely a "private repository" => Awaiting feedback about visibility change of the repository.

Getting links from: https://quarto.org/docs/reference/formats/epub.html
https://www.w3.org/publishing/epub3/epub-packages.html#bib-typesregistry
-> outdated with Epub 3.3 => No obvious replacement found.

Getting links from: https://quarto.org/docs/reference/formats/icml.html
https://wwwimages.adobe.com/content/dam/acom/en/devnet/indesign/sdk/cs6/idml/idml-specification.pdf
-> very hidden link initially found on a forum => No replacement found.
```

For the last two, I have no idea on how or with what to fix the links.

**Comment by cderv** [comment]
> Getting links from: https://quarto.org/docs/reference/formats/epub.html
https://www.w3.org/publishing/epub3/epub-packages.html#bib-typesregistry
-> outdated with Epub 3.3 => No obvious replacement found.

The new link is this one: https://www.w3.org/publishing/epub32/epub-packages.html#bib-typesregistry 
This points to Registry link :  https://idpf.github.io/epub-registries/types/ that we could also use

However, the question to update the description could be dealt with.  I don't know if we (through Pandoc) are producing Epub 3.3 compatible output (or still 3.2). Equivalent for 3.3 is https://www.w3.org/TR/epub/#sec-opf-dctype and it says 

> The dc:type element [[dcterms](https://www.w3.org/TR/epub/#bib-dcterms)] is used to indicate that the [EPUB publication](https://www.w3.org/TR/epub/#dfn-epub-publication) is of a specialized type (e.g., annotations or a dictionary packaged in EPUB format).

>
> [EPUB creators](https://www.w3.org/TR/epub/#dfn-epub-creator) MAY use any text string as a [value](https://www.w3.org/TR/epub/#dfn-value).
> NOTE
> The former IDPF EPUB 3 Working Group maintained a [non-normative registry of specialized EPUB publication types](http://idpf.org/epub/vocab/package/types/) for use with this element. This Working Group no longer maintains the registry and does not anticipate developing new specialized publication types.

So if 3.3 is what we output, we could just adapt the description to this new one (but there is probably others - so it would be its own update issue I guess). 

For now, you can probably put the new link:  https://www.w3.org/publishing/epub32/epub-packages.html#bib-typesregistry

**Comment by cderv** [comment]
> Getting links from: https://quarto.org/docs/reference/formats/icml.html
https://wwwimages.adobe.com/content/dam/acom/en/devnet/indesign/sdk/cs6/idml/idml-specification.pdf
-> very hidden link initially found on a forum => No replacement found.

Those pages can be created based on Pandoc information. So usually, you can try find information there too. So for replacement see 
* https://github.com/jgm/pandoc/issues/9563 (https://github.com/jgm/pandoc/commit/7e4569d19684e49347db009a92dd8266eda6893b) 

New link would be https://manualzz.com/doc/9627253/adobe-indesign-cs6-idml-cookbook

**Comment by mcanouil** [comment]
Regarding Epub, that's the "outdated" link I've found but don't know if it makes sense as you pointed out (https://github.com/quarto-dev/quarto-cli/issues/9005#issuecomment-2002134988).

For Adobe InDesign, there are no official or reliable source, the issue of the link being broken will be a continuous concern while I don't see what the link brings in Quarto.
I would be in favour of removing it.

**Comment by cderv** [comment]
* EPUB:

This is the current equivalent link: https://www.w3.org/publishing/epub32/epub-packages.html#bib-typesregistry (`epub3` replaced by `epub32`). This would  mean no other change for now - just fixing the broken link. 

* ICML

> the issue of the link being broken will be a continuous concern

We could do like Pandoc and use the other one, or just remove the link. The latter is probably fine.

> Possible links:

Is IDML equivalent to ICML ?

**Comment by mcanouil** [comment]
I believe ICML is a typo (made several times by the authors of Pandoc and issues) as IDML stands for InDesign Markup Language (file extension is `.idml` amongst others).

`ICML` is the file type/extension for InCopy (Markup Language).

Content can be migrated between InDesign and InCopy. Here it is very ambiguous on Pandoc side.
![image](https://github.com/quarto-dev/quarto-cli/assets/8896044/99dc3258-7198-4255-b6c4-14f517c697c1)

**Comment by cderv** [comment]
> ICML is the file type/extension for InCopy (Markup Language).

Oh so it makes sense that `--to icml` is used but they should talk about InDesign IDML. Did not know that. 

Anyhow, no need to spend more time on that. Just remove the link as you are suggesting. 

Thanks a lot for the explanation !

**Comment by mcanouil** [comment]
The only remaining issue is:

```txt
Getting links from: https://quarto.org/docs/dashboards/examples/index.html
https://github.com/jjallaire/ojs-penguins-dashboard/blob/main/penguins.qmd
-> Very likely a "private repository" => Awaiting feedback about visibility change of the repository.
```
