### ISSUE TITLE
Revealjs: Fragment animation of a bullet point inside a list

### ISSUE THREAD

**Issue by mroavi** [quarto-dev/quarto-cli#901]
How can I animate a bullet point inside a list in a Reactive.js animation?

This code generates an unwanted space between the last and previous bullet points:
```
- Bullet point
- Bullet point

::: {.fragment .fade-in}
::: {.fragment .highlight-red}
- Bullet point
:::
:::
```
![image](https://user-images.githubusercontent.com/19517248/168660372-54375126-ead7-4c68-b58d-fe9cf5494c0f.png)

Removing the space between the bullets does not help:
```
- Bullet point
- Bullet point
::: {.fragment .fade-in}
::: {.fragment .highlight-red}
- Bullet point
:::
:::
```
![image](https://user-images.githubusercontent.com/19517248/168660479-2f56e27c-8b49-42e5-9657-6eb35bc67d41.png)

I suspect that there is a way to do this that I haven't been able to find. Since this is such a common scenario, it would be great if it was added to the Presentations/Revealjs documentation.

**Comment by jjallaire** [comment]
You can do this with spans rather than divs:

```markdown
- Bullet point
- Bullet point
- [[Bullet point]{.fragment .highlight-red}]{.fragment .fade-in}
```

**Comment by mroavi** [comment]
Thanks! However, I see that the bullet is displayed before the animation occurs:
![image](https://user-images.githubusercontent.com/19517248/168664257-642f3139-514a-4a49-b916-efdc3286f08a.png)
Is there any way to hide it initially as well?

**Comment by jjallaire** [comment]
You'd have to make the entire list incremental:

````markdown
::: incremental
- Bullet point
- Bullet point
- [[ Bullet point]{.fragment .highlight-red}]{.fragment .fade-in}
::: 
````
