### ISSUE TITLE
Inline code not rendering if no block code is included

### ISSUE THREAD

**Issue by juliantao** [quarto-dev/quarto-cli#9010]
### Bug description

If there is no block code included in the source markdown file, the inline code does not render. 

The inline code renders properly if there is a code block in the markdown file.

### Steps to reproduce

If there is no block code:

````qmd
---
title: "Inline Code Rendering"
---

If there is no block code included in the source markdown file, the inline code does not render. 

For example, three plus two equals `r 3+2`

````

Result:

![image](https://github.com/quarto-dev/quarto-cli/assets/60116296/b5c254f1-59cc-4156-98bf-8e2e072421a3)

If there is a block code:

````qmd
---
title: "Inline Code Rendering"
---

If there is no block code included in the source markdown file, the inline code does not render. 

The inline code renders properly if there is a code block in the markdown file.
Even if the block is empty.

```{r} 
```

For example, three plus two equals `r 3+2`

`````

Result:

![image](https://github.com/quarto-dev/quarto-cli/assets/60116296/ae5ae954-0da1-49bf-852d-b970311deb49)

**Comment by mcanouil** [comment]
There is no bugs.
As documented, auto detection of engine only happens for code cell.
When using only inline, you need to explicitly states the engine/kernel. In your case: `engine: knitr`.

See <https://quarto.org/docs/computations/inline-code.html#engine-binding>.

**Comment by juliantao** [comment]
> There is no bugs.
> As documented, auto detection of engine only happens for code cell.
> When using only inline, you need to explicitly states the engine/kernel. In your case: `engine: knitr`.
> 
> See <https://quarto.org/docs/computations/inline-code.html#engine-binding>.

Indeed! My bad. Thank you!
