### ISSUE TITLE
How to debug YAML parsing errors?

### ISSUE THREAD

**Issue by ym-han** [quarto-dev/quarto-cli#903]
Hi, I've been trying to debug a YAML parsing error

`ERROR: YAMLError: can not read a block mapping entry; a multiline key may not be an implicit key at line 14, column 1:`

in my Quarto presentation, but I'm not sure how to go about doing this in a productive way --- I've just been removing stuff and checking to see if it's still broken, but it's not viable to keep doing that. Would you happen to have any tips on how to debug issues like these? 

(The issue is probably not with the front matter.)

**Comment by jjallaire** [comment]
YAML parsers are notoriously obscure in their error reporting so we do quite a bit of work internally to provide coherent and actionable YAML error messages. Clearly in this case though we've failed! The best way to debug an issue like this is to post your YAML here and let us:

(1) Identify the cause and resolution; and

(2) See if we can generalize this to a more clear error message for future users '

**Comment by ym-han** [comment]
Alright, here's the presentation (had to rename the extension to .md so I could drag and drop it here). Thanks in advance!

[presentation.md](https://github.com/quarto-dev/quarto-cli/files/8708450/presentation.md)

**Comment by jjallaire** [comment]
@cscheid I can reproduce this error with the provided file. I think that the use of `---` (horizontal rule) as a slide separator is confusing our `breakQuartoMd` logic. Note that we have some logic here that we use when attempting to extract all YAML from a file that excludes `---` delimited regions that are nevertheless NOT YAML (based on Pandoc's parsing rules): https://github.com/quarto-dev/quarto-cli/blob/main/src/core/yaml.ts#L93-L106

**Comment by cscheid** [comment]
Thanks for catching this! I made our code a little more careful around horizontal rules.

**Comment by ym-han** [comment]
One quick suggestion: if you aren't already using something like Hypothesis (https://hypothesis.readthedocs.io/en/latest/) to test the parsing stuff, it might be worth using that.

**Comment by plessl** [comment]
I stumbled over this problem again with a QMD file that used the --- as a horizontal rule. The file was processed just fine using a previous version of quarto (not sure which specific version, I believe 1.3.xxx). But rendering the same file with quarto 1.4.298 failed with the same obscure error message.

Maybe the fix for better error reporting does no longer work?
