### ISSUE TITLE
Do not always show stack trace when error

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#9032]
Usually, it appears when in debug mode (when using dev version which set `QUARTO_DEBUG` env var or when explicitly opting in stack trace with `QUARTO_PRINT_STACK` env var. 

But it seems to be shown here without those being set... 🤔 

So I looked and we have now: 
https://github.com/quarto-dev/quarto-cli/blob/b222df50198848437ebcaa2b6489b4b29ddfc907/src/core/log.ts#L335

This changed in 1.4 at 2e405396ec96d7da89b3f717de474637e7f7acdc
````diff
- if (isDebug && err.stack && err.printStack) {
+ if (err.stack && (isDebug || err.printStack)) {
````

And now we print always when `err.printStack` is `true`... This is a change in behavior. 

And in fact I think `printStack` is always set to `true` because we normalize
https://github.com/quarto-dev/quarto-cli/blob/b222df50198848437ebcaa2b6489b4b29ddfc907/src/core/log.ts#L318-L320
and `errorEx` will always set `printStack` when there is a `message`
https://github.com/quarto-dev/quarto-cli/blob/b222df50198848437ebcaa2b6489b4b29ddfc907/src/core/lib/error.ts#L47-L60

So I think we are now always printing the stack trace.

Initial intention with 2e40539 was 
> to have a stack trace when it was requested in an exception without a message.

We are currently opting-out printing Stack when no message 
https://github.com/quarto-dev/quarto-cli/blob/4b0bbb9709044ff26deb3833a06aa99dc69836f2/src/core/lib/error.ts#L55

So it seems to me that we would like to remove this. 

I still believe we should print stack trace only when `isDebug` is `true`
https://github.com/quarto-dev/quarto-cli/blob/4b0bbb9709044ff26deb3833a06aa99dc69836f2/src/core/log.ts#L332-L334

_Originally posted by @cderv in https://github.com/quarto-dev/quarto-cli/issues/8996#issuecomment-1983829411_

**Comment by cscheid** [comment]
The problem is that I'm pretty sure that the change I made in https://github.com/quarto-dev/quarto-cli/commit/2e405396ec96d7da89b3f717de474637e7f7acdc was necessary for an internal crash to show a stack trace.

It's definitely the case that #8996 shouldn't have a stack trace, but every uncaught exception in Quarto _should_ have a stack trace, and I'd like us to err on the side of being conservative here.

I'm not sure how to fix this.
