### ISSUE TITLE
Quarto dashboard adds extra column with ipynb notebooks

### ISSUE THREAD

**Issue by szsctt** [quarto-dev/quarto-cli#9056]
### Bug description

I'm trying to reproduce a quarto dashboard from example provided [in the documentation](https://quarto.org/docs/dashboards/).  When I render the dashboard with `quarto preview <.ipynb file> --no-browser --no-watch-inputs`, there is an extra column in each of the rows.

### Steps to reproduce

![Screenshot 2024-03-13 at 15 01 28](https://github.com/quarto-dev/quarto-cli/assets/23192453/a5d92246-ce0d-4246-b930-672ce6f425c6)

### Expected behavior

There should be one column in the first row and two in the second row.

### Actual behavior

There is one extra column in each row.

### Your environment

- IDE: VSCode
- OS: Linux ubuntu 22.04

### Quarto check output

```
Quarto 1.4.550
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.58.3: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.550
      Path: /data/home/sscott/micromamba/envs/aavolve_test/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.13 (Conda)
      Path: /data/home/sscott/micromamba/envs/aavolve_test/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
Thanks for the report.
I can reproduce on the latest development version of Quarto.

Copy/pasting the Quarto document given in https://quarto.org/docs/dashboards/#walkthrough

<details><summary>Quarto document.</summary>

````qmd
--- 
title: "Development Indicators by Continent"
author: "Gapminder Analytics Group"
format: dashboard
--- 

```{python}
import plotly.express as px
df = px.data.gapminder()
```

## Row {height=60%}

```{python}
#| title: GDP and Life Expectancy 
px.scatter(  
  df, x="gdpPercap", y="lifeExp", 
  animation_frame="year", animation_group="country", 
  size="pop", color="continent", hover_name="country",
  facet_col="continent", log_x=True, size_max=45, 
  range_x=[100,100000], range_y=[25,90] 
)  
```

## Row {height=40%}

```{python}
#| title: Population
px.area(
  df, x="year", y="pop", 
  color="continent", line_group="country"
)
```

```{python}
#| title: Life Expectancy
px.line(
  df, x="year", y="lifeExp", 
  color="continent", line_group="country"
)
```
````

</details>

Then using Quarto to get a Jupyter notebook

```sh
quarto convert dashboard.qmd
```

Finally to reproduce the issue:

```sh
quarto render dashboard.ipynb --execute
````

Note that executing from the Quarto document itself gives the expected result:

```sh
quarto render dashboard.qmd
````

**Comment by szsctt** [comment]
An update on this - I was reading through the [documentation on dashboard formatting](https://quarto.org/docs/dashboards/data-display.html) a little more carefully and noticed this:

>> Note that if you are authoring using a Jupyter Notebook then markdown cells automatically become .card divs (i.e. they don’t need the explicit ::: div enclosure).

So I guess that this is happening because the cells that contain `##Row` are markdown cells.  If I change them to raw, the extra columns in the example above disappear.  It might be useful to mention this somewhere in the documentation (all the examples are for `.qmd` files so it's easy to miss information about notebooks), and also when converting from .qmd to .ipynb, anything in a .card div should become markdown and anything else should become a raw cell.

**Comment by mcanouil** [comment]
Thanks @szsctt that is indeed the issue.

**Comment by cscheid** [comment]
This more or less fell off my radar - apologies. We definitely want to fix it, and I'll take a closer look in the next couple of days.
