### ISSUE TITLE
Can't run lua script with `quarto run`

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#9059]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/9057

<div type='discussions-op-text'>

<sup>Originally posted by **GuillaumeDehaene** March 13, 2024</sup>
### Description

Hello everyone

I'm trying to get back into developping a lua filter to simplify how math can be inputted in pandoc and quarto Markdown.
As part of that, I would like to have:
- a list of examples pairing raw markdown with their conversion
- a test script to check that these examples are correctly converted

However, as part of that, I can't seem to be able to use `quarto run test.lua`
Am I doing something wrong? Here is the error trace.

```
PS D:\Desktop\Dojo\quarto\filters\simple_tex_math> quarto run test.lua
Error running filter C:\Users\Guillaume\AppData\Local\Programs\Quarto\share\filters\init\init.lua:
...ppData\Local\Programs\Quarto\share\filters\init\init.lua:4: module 'readqmd' not found:
        no field package.preload['readqmd']
        no file 'C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin\tools\lua\readqmd.lua'
        no file 'C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin\tools\lua\readqmd\init.lua'
        no file 'C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin\tools\readqmd.lua'
        no file 'C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin\tools\readqmd\init.lua'
        no file 'C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin\tools\..\share\lua\5.4\readqmd.lua'        
        no file 'C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin\tools\..\share\lua\5.4\readqmd\init.lua'   
        no file '.\readqmd.lua'
        no file '.\readqmd\init.lua'
        no file 'D:\Lua\lua\readqmd.luac'
        no file 'C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin\tools\readqmd.dll'
        no file 'C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin\tools\..\lib\lua\5.4\readqmd.dll'
        no file 'C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin\tools\loadall.dll'
        no file '.\readqmd.dll'
stack traceback:
        ...ppData\Local\Programs\Quarto\share\filters\init\init.lua:4: in main chunk
PS D:\Desktop\Dojo\quarto\filters\simple_tex_math>
```

Other debug information:
```
- IDE VSCode 1.87.1
- OS  Windows 11 version 23H2

>> quarto check
Quarto 1.5.24
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.24
      Path: C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: Installation From Path
      Path: C:\texlive\2023\bin\windows
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

The issue was also present on my earlier quarto 1.4.X and 1.3.X installs. I've also tried to uninstall and reinstall.
Quarto filters run perfectly and no other issue with lua is apparent</div>

**Comment by cderv** [comment]
On my side when testing I get this. 

````
> quartoPreRelease run test.lua
Error running filter C:\Users\chris\scoop\apps\quarto-prerelease\current\share\filters\init\init.lua:
cannot open C:\Users\chris\scoop\apps\quarto-prerelease\current\share\filters\init\init.lua: No such file or directory
````

It seems it requires a file which is missing. 

https://github.com/quarto-dev/quarto-cli/blob/265e3dc002455fc1e3e56fe2e2bbf731e5ef0055/src/core/run/lua.ts#L40-L43

and this file has been moved quite some time ago https://github.com/quarto-dev/quarto-cli/commit/f01b00872ee0b3dededcee4af30cdb499b3094ea

We probably need to adapt or just removed this windows specific. I'll need to look into this more closely because I don't know well this part of the code.

**Comment by cderv** [comment]
Based on the diff in the commit, I think we can safely remove. `init.lua` will be loaded as part of Pandoc as it is in the `datadir` part.

**Comment by jimjam-slam** [comment]
Just a small thank you note for this one - I've been [trying to get my Lua filters working on Windows](https://github.com/jimjam-slam/sverto/actions/runs/8354006576/job/22866641080) and had thought I just didn't understand how to run them on Windows properly! [All working great](https://github.com/jimjam-slam/sverto/actions/runs/8367172102/job/22908981017) once I moved my CI up to the 1.5.25 🥳
