### ISSUE TITLE
Quarto in VS Code tries to run the MatLab Jupyter kernel rather than the built in MatLab plug-in in VS-Code

### ISSUE THREAD

**Issue by ncworstell** [quarto-dev/quarto-cli#9067]
### Bug description

When I generate the Markdown preview of a quarto document with MatLab code in it, it tries to run the MatLab kernel for jupyter and does not give the option or seem to look for the MatLab plug-in for VS Code. Presumably this is because the MatLab plug-in only recently started to support code execution (https://marketplace.visualstudio.com/items?itemName=MathWorks.language-matlab)

### Steps to reproduce
````qmd
---
title: "Untitled"
format: html
---

```{matlab}
ver
```
````

### Expected behavior

Something like this should output (I have XXX'd out personal information) should appear in the pdf output.
````bash
>> ver
-----------------------------------------------------------------------------------------------------
MATLAB Version: 23.2.0.2365128 (R2023b)
MATLAB License Number: XXXXXXXXX
Operating System: Microsoft Windows 10 Enterprise Version 10.0 (Build 19045)
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 23.2        (R2023b)
Simulink                                              Version 23.2        (R2023b)
Bioinformatics Toolbox                                Version 23.2        (R2023b)
Computer Vision Toolbox                               Version 23.2        (R2023b)
Curve Fitting Toolbox                                 Version 23.2        (R2023b)
DSP System Toolbox                                    Version 23.2        (R2023b)
Deep Learning Toolbox                                 Version 23.2        (R2023b)
Fuzzy Logic Toolbox                                   Version 23.2        (R2023b)
Global Optimization Toolbox                           Version 23.2        (R2023b)
Image Processing Toolbox                              Version 23.2        (R2023b)
MATLAB Compiler                                       Version 23.2        (R2023b)
MATLAB Compiler SDK                                   Version 23.2        (R2023b)
Optimization Toolbox                                  Version 23.2        (R2023b)
PLS_Toolbox                                           Version 9.3         (24529) 
Parallel Computing Toolbox                            Version 23.2        (R2023b)
Signal Processing Toolbox                             Version 23.2        (R2023b)
SimBiology                                            Version 23.2        (R2023b)
Spreadsheet Link                                      Version 23.2        (R2023b)
Statistics and Machine Learning Toolbox               Version 23.2        (R2023b)
Symbolic Math Toolbox                                 Version 23.2        (R2023b)
Wavelet Toolbox                                       Version 23.2        (R2023b)
````
### Actual behavior

![image](https://github.com/quarto-dev/quarto-cli/assets/29806699/8462fce8-971e-4248-844f-c9affcfbfbc5)

### Your environment

-IDE: VSCode
Version: 1.87.1 (user setup)
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:21:36.258Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

- MatLab plug in v1.2.0
- Quarto Plug in v1.111.0
- 

### Quarto check output
````bash
A new release of Deno is available: 1.28.2 → 1.41.2 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Users\worstn\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Users/worstn/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.3.1
      Kernels: python3, jupyter_matlab_kernel

(\) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
````

**Comment by mcanouil** [comment]
VSCode Quarto extension repository is <https://github.com/quarto-dev/quarto>.

Could you properly format your post using code blocks for code and terminal outputs? Thanks.
If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.
Currently it's not very legible.

**Comment by cderv** [comment]
@ncworstell can you format your issue correctly please ? This way will be able to look at your example correctly. 

See https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us

thanks !

**Comment by ncworstell** [comment]
@cderv, I think I updated it properly. Please let me know how else I can help/what else I might need to correct.

**Comment by mcanouil** [comment]
@ncworstell GitHub uses markdown. You only have to edit your post to make it "pretty". Take a look at the current formatting, you have `quarto check` output outside of a code block, you have a weird sections headers in the middle, etc. You can use the "preview" button to see your formatting.
![image](https://github.com/quarto-dev/quarto-cli/assets/8896044/106d946f-11d6-4b83-948a-2ffd09058fa4)

**Comment by ncworstell** [comment]
Just commenting that the MatLab issue at play here has been resolved [https://github.com/mathworks/jupyter-matlab-proxy/issues/48](https://github.com/mathworks/jupyter-matlab-proxy/issues/48.). It is worth noting that for MatLab the usual #| syntax used in the quarto documentation is replaced with %|, but otherwise everything works that I have tested.

**Comment by cscheid** [comment]
> It is worth noting that for MatLab the usual #| syntax 

To clarify: this is not the "usual" syntax. Quarto's syntax has always been "comment character followed by `|`". Note the comments on the diagram blocks in [our documentation](https://quarto.org/docs/authoring/diagrams.html), for example.
