### ISSUE TITLE
Issue with block layout (pdf and html)

### ISSUE THREAD

**Issue by matthiasbaitsch** [quarto-dev/quarto-cli#9077]
### Bug description

Two column block layout with graphics and text not formatted as expected.

### Steps to reproduce

````qmd
---
title: Test
format:
    html: default
    pdf: default
keep-tex: true
---

```{r}
#| include: false
library(ggplot2)
library(tidyverse)
```

:::: {layout="[40, -5, 115]" layout-valign="top"}

::: {#col1}
```{r}
#| fig-asp: 1
#| echo: false
#| out-width: "100%"
tibble(X = c(1, 2, 2, 2, 3, 3)) |> ggplot() + geom_bar(aes(x = X)) + theme_void()
```
:::

::: {#col2}
**Some text:** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc magna nisi, tempor nec tincidunt 

**Some test in new line:** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc magna nisi, tempor nec tincidunt 
:::

::::
````

#### PDF output

<img width="488" alt="Screenshot 2024-03-14 at 20 46 38" src="https://github.com/quarto-dev/quarto-cli/assets/41143412/1b91a1dc-f172-4ade-b900-5f9371b31634">

The following LaTeX code (needs `adjustbox` package) results in the expected layout (no float, top-aligned, text in two lines)

```tex
\begin{minipage}[t]{0.25\linewidth}

\includegraphics[width=1\textwidth,height=\textheight,valign=t]{test_files/figure-pdf/unnamed-chunk-2-1.pdf}

\end{minipage}%
%
\begin{minipage}[t]{0.03\linewidth}
~\end{minipage}%
%
\begin{minipage}[t]{0.72\linewidth}
\textbf{Some text:} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
magna nisi, tempor nec tincidunt

\textbf{Some test in new line:} Lorem ipsum dolor
sit amet, consectetur adipiscing elit. Nunc magna nisi, tempor nec
tincidunt
\end{minipage}%
```

#### HTML output

Specified spacing between figure and text

#### PDF Output

<img width="499" alt="Screenshot 2024-03-14 at 20 39 57" src="https://github.com/quarto-dev/quarto-cli/assets/41143412/94707439-6940-4adb-b5db-174bcd9fc892">

```tex
\begin{figure}

\begin{minipage}{0.25\linewidth}

\includegraphics[width=1\textwidth,height=\textheight]{test_files/figure-pdf/unnamed-chunk-2-1.pdf}

\end{minipage}%
%
\begin{minipage}{0.03\linewidth}
~\end{minipage}%
%
\begin{minipage}{0.72\linewidth}
\textbf{Some text:} Lorem ipsum dolor sit amet, consectetur adipiscing
elit. Nunc magna nisi, tempor nec tincidunt\textbf{Some test in new
line:} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
magna nisi, tempor nec tincidunt\end{minipage}%

\end{figure}%
```

Problems
- vertical alignment
- text on one line
- figure environment

#### HTML Output

<img width="958" alt="Screenshot 2024-03-14 at 20 42 13" src="https://github.com/quarto-dev/quarto-cli/assets/41143412/3e3ca879-b1ef-49d0-995f-0c282c8d4224">

Problems
- Spacing between figure and text too large

### Your environment

- IDE: Visual Studio Code
- MacOS Sonoma 14.2.1 (23C71)

### Quarto check output

```
Quarto 1.4.551
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.551
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: 5.7.1
      Kernels: julia-1.10, julia-1.9, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/maba/Library/R/x86_64/4.2/library
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report I can reproduce with a little bit more simple example (without the extra divs and R dependencies).

Note that it has nothing to do with mixed content, see below.
`layout-valign` is simply ignored here fir `pdf` format.

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
format: pdf
---

::: {layout="[40, -5, 115]" layout-valign="top"}

{{< lipsum 1 >}}

**Some text:** Lorem ipsum dolor sit amet,
consectetur adipiscing elit. Nunc magna nisi, tempor nec tincidunt  
**Some test in new line:** Lorem ipsum dolor sit amet, 
consectetur adipiscing elit. Nunc magna nisi, tempor nec tincidunt

:::
````

</td><td>

<img width="588" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/99618dd8-bbe7-4b0e-b3b6-72ef3648b863">

</td></tr>
</table>

**Comment by matthiasbaitsch** [comment]
Thanks a lot! This is the second bug report I ever filed - apologies if I get it wrong. Probably the report is too complex since it addresses multiple points. Should I split it up?

**Comment by mcanouil** [comment]
> Thanks a lot! This is the second bug report I ever filed - apologies if I get it wrong. Probably the report is too complex since it addresses multiple points. Should I split it up?

I don't understand. What are the other "points" beside the vertical alignment being ignored in LaTeX output?

Lipsum is a shortcode extension provided as a standalone (for Quarto < 1.5) and integrated (Quarto >= 1.5)

> By the way, how do you get the amazing combination of Quarto code and the resulting output?

That's a GitHub kind of thing that you really should not do in Quarto documents.

`````
<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
CODE
````

</td><td>

<!-- IMAGE -->

</td></tr>
</table>
`````

**Comment by matthiasbaitsch** [comment]
> > Thanks a lot! This is the second bug report I ever filed - apologies if I get it wrong. Probably the report is too complex since it addresses multiple points. Should I split it up?
> 
> I don't understand. What are the other "points" beside the vertical alignment being ignored in LaTeX output?

In addition to the vertical alignment this is

- Two lines of text in the div scrambled into one

- Figure environment is a problem if the block should be in the text

- Vertical spacing in HTML output

This information is actually in the bug report but perhaps the report is confusing.

I added the figure since it needs special treatment in order for the vertical alignment to work in pdf output.


> 
> > Note that `{{< lipsum 1 >}}` does not work on my system.
> 
> Lipsum is a shortcode provided as a standalone extension for Quarto < 1.5 and integrated in Quarto >= 1.5.
> 

Get it

> > By the way, how do you get the amazing combination of Quarto code and the resulting output?
> 
> That's a GitHub kind of thing that you really should not do in Quarto documents.
> 
> ```
> <table>
> <tr><th>Quarto document</th><th>HTML</th></tr>
> <tr><td>
> 
> ````qmd
> CODE
> ````
> 
> </td><td>
> 
> 
> 
> </td></tr>
> </table>
> ```

Fine, just a table. I thought that it is generated automatically from the source code

**Comment by mcanouil** [comment]
> * Vertical spacing in HTML output

You mean horizontal spacing? You defined the three columns to be 25 % ($\frac{40}{40 + 5 + 115}$), 3.1 % ($\frac{5}{40 + 5 + 115}$) and 71.9 % ($\frac{115}{40 + 5 + 115}$) which is exactly what you get.

<img width="265" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/ce83198c-5990-4132-a9ce-f638b06080f4">

> Figure environment is a problem if the block should be in the text

Sorry but this is unclear.

> Two lines of text in the div scrambled into one

I can reproduce that the linebreak is discarded here.

<table>
<tr><th>Quarto document</th><th>LaTeX</th></tr>
<tr><td>

````qmd
---
format: pdf
---

::: {layout="[25, -5, 70]"}

{{< lipsum 1 >}}

:::: {}
**Some text:** Lorem ipsum dolor sit amet,
consectetur adipiscing elit. Nunc magna nisi, tempor nec tincidunt

**Some test in new line:** Lorem ipsum dolor sit amet, 
consectetur adipiscing elit. Nunc magna nisi, tempor nec tincidunt
::::

:::
````

</td><td>

<img width="626" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/4d40c100-5474-43d7-9673-d36dcc7b62a9">

</td></tr>
</table>

**Comment by matthiasbaitsch** [comment]
> > * Vertical spacing in HTML output
> 
> You mean horizontal spacing? You defined the three columns to be 25 % (4040+5+115), 3.1 % (540+5+115) and 71.9 % (11540+5+115) which is exactly what you get.
> 
> <img alt="image" width="265" src="https://private-user-images.githubusercontent.com/8896044/313176926-ce83198c-5990-4132-a9ce-f638b06080f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDgzNzksIm5iZiI6MTcxMDUwODA3OSwicGF0aCI6Ii84ODk2MDQ0LzMxMzE3NjkyNi1jZTgzMTk4Yy01OTkwLTQxMzItYTljZS1mNjM4YjA2MDgwZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMTMwNzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWFjYmVkY2JmMmFiNDc5NzZiMDY1OTFkMTk1NDg4MWVhNTZjM2JhNTBjOGM0ZTBlMzVjN2JmNmViMmYwMjljMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6wjYVJRhbQ4uvuJm5BYnirSfUXR1LUx9hkisbcCwDVw">
> You get the exact same thing as per the LaTeX output you shared. There is nothing wrong here.

Of course horizontal, thanks for pointing out. The sizes of the divs are correct but visual appearance is not. I think the reason is that the css style adds a right margin of 20px to the `quarto-layout-cell` class. When it is removed, the output is as expected.

<img width="1234" alt="Screenshot 2024-03-15 at 14 19 58" src="https://github.com/quarto-dev/quarto-cli/assets/41143412/a39baafa-0f2b-4538-88cc-9d162d3ead1f">


> 
> > Figure environment is a problem if the block should be in the text
> 
> ~Sorry but this is unclear.~
> 
> Edit: I think you mean that it is unexpected to have the minipage enclosed within a figure environment, if that's so, then I can reproduce. Even if it is unexpected, it renders fine (not fully sure it is a bug or kind of a feature here). CC @cscheid

Actually, I operated under the false assumption that the creation of a floating environment (figure/table) is triggered by the presence of a corresponding label. Sorry for the confusion.

However, in my current work (bringing my lecture notes from LaTeX to Quarto) there are situations where it is not desirable to have the content in a figure environment, here is an example: 

<img width="457" alt="Screenshot 2024-03-15 at 14 35 49" src="https://github.com/quarto-dev/quarto-cli/assets/41143412/0c567b1e-cb63-49c1-a60c-57be6a06d93e">

> 
> Quarto document	LaTeX
> ```
> ---
> format: pdf
> keep-tex: true
> ---
> 
> ::: {layout="[25, -5, 70]"}
> 
> ![](https://placehold.co/600x400.png)
> 
> Text
> 
> :::
> ```
> 
>  ```
> \begin{document}
> 
> \begin{figure}
> 
> \begin{minipage}{0.25\linewidth}
> \includegraphics{index_files/mediabag/600x400.png}\end{minipage}%
> %
> \begin{minipage}{0.05\linewidth}
> ~\end{minipage}%
> %
> \begin{minipage}{0.70\linewidth}
> Text\end{minipage}%
> 
> \end{figure}%
> 
> 
> 
> \end{document}
> ```
> 
>  > Two lines of text in the div scrambled into one
> 
> I can reproduce that the linebreak is discarded here, see:
> 
> * [Linebreaks removed in divs within a layout in LaTeX #9088](https://github.com/quarto-dev/quarto-cli/issues/9088)

**Comment by mcanouil** [comment]
To elaborate on Christophe: the issue you are having with the enclosing figure environment deserves its own issue, similarly to the one I opened for you regarding the linebreak being skipped. (https://github.com/quarto-dev/quarto-cli/issues/9088)

You can reuse/expand my example to show where it becomes an issue in your case:


<table>
<tr><th>Quarto document</th><th>LaTeX</th></tr>
<tr><td>

````qmd
---
format: pdf
keep-tex: true
---

::: {layout="[25, -5, 70]"}

![](https://placehold.co/600x400.png)

Text

:::
````

</td><td>

````latex
\begin{document}

\begin{figure}

\begin{minipage}{0.25\linewidth}
\includegraphics{index_files/mediabag/600x400.png}\end{minipage}%
%
\begin{minipage}{0.05\linewidth}
~\end{minipage}%
%
\begin{minipage}{0.70\linewidth}
Text\end{minipage}%

\end{figure}%



\end{document}
````

</td></tr>
</table>

<details><summary>Code of the above table.</summary>
<p>

`````

<table>
<tr><th>Quarto document</th><th>LaTeX</th></tr>
<tr><td>

````qmd
---
format: pdf
keep-tex: true
---

::: {layout="[25, -5, 70]"}

![](https://placehold.co/600x400.png)

Text

:::
````

</td><td>

````latex
\begin{document}

\begin{figure}

\begin{minipage}{0.25\linewidth}
\includegraphics{index_files/mediabag/600x400.png}\end{minipage}%
%
\begin{minipage}{0.05\linewidth}
~\end{minipage}%
%
\begin{minipage}{0.70\linewidth}
Text\end{minipage}%

\end{figure}%



\end{document}
````

</td></tr>
</table>

`````

</p>
</details>

**Comment by matthiasbaitsch** [comment]
> > Probably the report is too complex since it addresses multiple points. Should I split it up?
> 
> @matthiasbaitsch about this, it is best to have one issue per feedback or problem you find, especially if you know there are not directly related. You can open new issues and link between them. It helps keep things scoped and not missed something when dealing with an issue;

Thanks a lot for the advice, I will do that.

**Comment by matthiasbaitsch** [comment]
Issues in this report now in #9108, #9108 and #9110.
