### ISSUE TITLE
index.qmd and index.R produce file-move error

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#9078]
### Bug description

Given a Quarto site having an `index.qmd` and rendered script `index.R`, those files together result in an error about an `index.html` file not existing. Having two resources render to the same location should be caught earlier.

### Steps to reproduce

```yaml
project:
  type: website
```

````markdown
---
title: this is index.qmd
---

this is index.qmd
````

````r
#' ---
#' title: index.R
#' ---

#| output: asis
cat("this is index.R\n")
````

```bash
quarto render
```

### Expected behavior

Rendering fails with an error indicating that two files produce the same output.

### Actual behavior

```
[1/2] index.R


processing file: index.R
1/3
2/3 [unnamed-chunk-1]
3/3
output file: index.knit.md

[2/2] index.qmd

ERROR: NotFound: No such file or directory (os error 2): rename '/Users/aron/bar/index.html' -> '/Users/aron/bar/_site/index.html'

Stack trace:
    at Object.renameSync (ext:deno_fs/30_fs.js:267:3)
    at renderProject (file:///Users/aron/Downloads/quarto-1.5.24-macos/bin/quarto.js:77737:22)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async Command.actionHandler (file:///Users/aron/Downloads/quarto-1.5.24-macos/bin/quarto.js:82294:32)
    at async Command.execute (file:///Users/aron/Downloads/quarto-1.5.24-macos/bin/quarto.js:8009:13)
    at async Command.parseCommand (file:///Users/aron/Downloads/quarto-1.5.24-macos/bin/quarto.js:7899:20)
    at async quarto (file:///Users/aron/Downloads/quarto-1.5.24-macos/bin/quarto.js:117159:5)
    at async file:///Users/aron/Downloads/quarto-1.5.24-macos/bin/quarto.js:117171:9
    at async mainRunner (file:///Users/aron/Downloads/quarto-1.5.24-macos/bin/quarto.js:117068:9)
    at async file:///Users/aron/Downloads/quarto-1.5.24-macos/bin/quarto.js:117162:5
```

### Your environment

Quarto 1.5.24 and Quarto 1.4.551

### Quarto check output

```
Quarto 1.5.24
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.24
      Path: /Users/aron/Downloads/quarto-1.5.24-macos/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/aron/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /usr/local/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report.
I believe this is another case a:

- https://github.com/quarto-dev/quarto-cli/issues/4802

Which falls under the "epic":

- https://github.com/quarto-dev/quarto-cli/issues/6518

**Comment by aronatkins** [comment]
If #4802 is included in 1.5.24, then this is not resolved already, but agree that it appears to fall under #6518.

**Comment by mcanouil** [comment]
> If https://github.com/quarto-dev/quarto-cli/issues/4802 is included in 1.5.24, then this is not resolved already

What do you mean? That #4802 is still an issue?

For clarity, I linked #4802 because fundamentally, the issue is the same, *i.e.*, the temporary files location. I did not mean to state that this issue was solved for all cases such as the one you described.

@cscheid you closed this one as completed, but I don't find any commits/prs regarding this case.

**Comment by aronatkins** [comment]
@mcanouil No, sorry. I misunderstood your intent. I thought that you were saying that my reported problem was solved by #4802.

**Comment by cscheid** [comment]
> as completed

GitHub's ui for completed vs duplicate is very stupid; so if the label says duplicate and there's a link to the other issue, please disregard the completed status.

**Comment by mcanouil** [comment]
Or use the other "close" action ;)
![image](https://github.com/quarto-dev/quarto-cli/assets/8896044/70813818-fc7e-458f-b325-c7d6775afb42)

**Comment by cscheid** [comment]
Yes, that's the "ui is very stupid" part.
