### ISSUE TITLE
SVGs with styles defined in <defs> element may not render correctly

### ISSUE THREAD

**Issue by DougManuel** [quarto-dev/quarto-cli#9092]
### Bug description

SVG files with color styles defined within a <defs> section may not render as expected when included in Quarto documents using the ![]( ) syntax. The SVG structure displays as an outline, omitting the intended fills. 

### Environments
- The issue happens in Quarto v1.4. I believe the same SVG images with styles rendered correctly in early Quarto versions. 
- SVG with styles used in this example pass SVG validation, and render correctly in Rstudio, VSCode, and all browsers tested. SVG with styles is the default export in Adobe Illustrator and other design programs.

### Steps to reproduce

SVG code in this example are at the end.

1) Display a SVG with styles in <defs> using markdown:
 
`![](assets/circle_with_styles.svg)`

<img width="178" alt="Screenshot 2024-03-15 at 2 24 11 PM" src="https://github.com/quarto-dev/quarto-cli/assets/13246138/b809e78a-d812-487b-9db2-655c3de69aec">

2) Display a SVG with style in <dev> using HTML:

`<object data="assets/circle_with_styles.svg"></object>`

<img width="178" alt="Screenshot 2024-03-15 at 2 24 21 PM" src="https://github.com/quarto-dev/quarto-cli/assets/13246138/d9dda6ee-72f4-4c0f-925b-3e8cf775a9b0">

3) Display a SVG without styles in Quarto:

`![](assets/circle_without_styles.svg)`

<img width="178" alt="Screenshot 2024-03-15 at 2 24 21 PM" src="https://github.com/quarto-dev/quarto-cli/assets/13246138/52d970c7-f8c0-400e-ac4c-c1ad68d4703e">

### cicrle_with_sytles.svg
```
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 150 150">
  <defs>
    <style>
      .cls-1 { fill: #f37f58; }
    </style>
  </defs>
  <g>
    <circle class="cls-1" cx="60" cy="60" r="30" /> 
  </g>
</svg>
```

### cicrle_without_sytles.svg
```
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 150 150">
  <g>
    <circle fill="#f37f58" cx="60" cy="60" r="30" /> 
  </g>
</svg>
```

### Expected behavior

SVGs with valid XML structure, regardless of whether styles are inline or within <defs>, should render correctly in Quarto documents.

### Actual behavior

SVGs using the <defs> element to centralize styles may fail to render their fills, displaying only an outline.

### Your environment

- macOS 14.3.1 (23D60)
- SVG with styles in the example validates in online SVG validators and displays correctly in Rstudio 2023.12.0+369 (2023.12.0+369) and earlier versions, VSCode 1.87.2, and Safari, Google Chrome and MS Edge.

### Quarto check output

Quarto 1.4.551
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.551
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.11
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/dmanuel/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.8
      Path: /private/var/folders/9f/sdnz_n353pb_w189n7rz3j8w0000gp/T/RtmpaE7bvM/rstudio/terminal/python3
      Jupyter: 4.11.1
      Kernels: python3, mu_venv-38-20230520-143707

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
[✓] Checking Jupyter engine render....OK

**Comment by cscheid** [comment]
How did you generate the .html file?

**Comment by DougManuel** [comment]
`quarto render`

**Comment by mcanouil** [comment]
@DougManuel See below what we expect to reproduce.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by cscheid** [comment]
I can't repro on `main` or `1.4`:

<img width="1927" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/adbc2d50-919a-40f7-afbe-f1b03139caeb">
