### ISSUE TITLE
insert-citation dialog in RStudio visual mode does not see all Zotero references

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-cli#910]
I'm using all latest versions as of now, I believe:
- RStudio-2022.06.0-daily-410.exe
- quarto-0.9.415-win.msi
- Zotero 6.0.7 Windows standalone software

quarto does not see all references in a Zotero folder. 

Here's what's in my Zotero folder ("dummy"):
![image](https://user-images.githubusercontent.com/6538392/168813760-7867f14f-8f7b-4c8e-bb50-aaf28e57f226.png)

Here's what I get when I use the insert-citation dialog:
![image](https://user-images.githubusercontent.com/6538392/168814120-b3d2f255-26f6-469b-9afd-562682d62c03.png)

You can see that one of the Ron Snell citations does not show.

I am not sure what distinguishes it. However, I created it by hand rather than saving it to the Zotero library through a browser (Chrome) web extension.

The problem does not seem to be on the Zotero end. Here is what I get if I export the dummy subcollection:
![image](https://user-images.githubusercontent.com/6538392/168814630-95bf7b6c-9db5-47b5-bdf1-9dcee112f86f.png)

It is clearly there in the exported .bib file.

**Comment by dragonstyle** [comment]
Transferred to the Rstudio repo
