### ISSUE TITLE
Do not allow `quarto typst update` to run

### ISSUE THREAD

**Issue by ForceBru** [quarto-dev/quarto-cli#9106]
### Bug description

I'm unable to update Typst to [version 0.11.0](https://github.com/typst/typst/releases/tag/v0.11.0).

### Steps to reproduce

```
~> quarto typst update
Downloading release ...
 10.0 MiB /  10.0 MiB (100 %)  10.0 MiB/s in  0s ETA:  0s
error: failed to self-replace running executable (Permission denied (os error 13) at path "/Applications/quarto/bin/tools/x86_64/.typst.__temp__x2lnN2").
```

### Expected behavior

The command should update Typst.

### Actual behavior

I get the above error.

### Your environment

- OS: macOS Ventura 13.6.3
- Quarto 1.5.23 and 1.5.25

### Quarto check output

```
~> quarto check
Quarto 1.5.25
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.25
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/forcebru/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: /Users/forcebru/.pyenv/versions/3.12.1/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

~> 
```

**Comment by mcanouil** [comment]
How did you install Quarto?

**Comment by ForceBru** [comment]
@mcanouil, I installed Quarto with the regular installer. Indeed, `ls -lah /Applications/quarto/` shows that everything in this directory is owned by root.

I was able to update using `sudo`:

```
/A/quarto> sudo quarto typst update
Password:
Downloading release ...
 10.0 MiB /  10.0 MiB (100 %)  10.0 MiB/s in  0s ETA:  0s
/A/quarto> quarto typst --version
typst 0.11.0 (2bf9f95d)
```

**Comment by gordonwoodhull** [comment]
Needless to say,  neither Pandoc nor Quarto directly supports Typst 0.11, so this may or may not work. 

We hope to look into it soon!

**Comment by cderv** [comment]
> This being said, I don't think you can upgrade Typst embedded version, as you can't for Pandoc.
Typst/Pandoc are updated and embedded at each new version of Quarto.

I agree with that. I did no know typst allowed to be updated from itself. Doing this will probably break Typst support with Quarto and Pandoc as you mention @gordonwoodhull. 

I don't think `quarto typst update` should be allowed to prevent any breaking of the Quarto installation

**Comment by baptiste** [comment]
Is there any way to point Quarto to use the system Typst instead of the built-in one? I'm trying to use contexts in Typst, which is new.

**Comment by cscheid** [comment]
Our plan is to release Quarto 1.5 with support for Typst 0.11. We're in the process of ensuring everything works.

In the meantime, you can use the `QUARTO_TYPST` env variable, **but that Voids The Warranty**.

In other words: we make no promise if something breaks when you run Quarto with a non-builtin version of Pandoc or Typst!

**Comment by mpr1255** [comment]
> Our plan is to release Quarto 1.5 with support for Typst 0.11. We're in the process of ensuring everything works.
> 
> In the meantime, you can use the `QUARTO_TYPST` env variable, **but that Voids The Warranty**.
> 
> In other words: we make no promise if something breaks when you run Quarto with a non-builtin version of Pandoc or Typst!

I just made a PR adding some documentation for this hidden feature, since it is extremely useful and I only found it in this discussion thread. 

https://github.com/quarto-dev/quarto-web/pull/1407

Really excellent & helpful feature; thanks.

**Comment by cscheid** [comment]
This feature is intentionally not documented. It exists for third-party packagers, not for users. So I don't want to spend precious documentation inches on discussing it. Instead, I'd prefer to document how document rendering can stop at `.typ` instead of `.pdf`:

```yaml
format:
  typst:
    output-ext: typ
```
