### ISSUE TITLE
Observable "Linked Views" example not working correctly

### ISSUE THREAD

**Issue by z3tt** [quarto-dev/quarto-cli#9124]
### What would you like to do?

Report an issue on quarto.org

### Description

Currently, the [example on linked views in the Quarto dashboard gallery using Observable](https://quarto.org/docs/dashboards/examples/#observable) is loading but not working correctly:

![image](https://github.com/quarto-dev/quarto-cli/assets/7523556/c7ae940c-f2cb-408d-95d3-c49601343e98)

**Comment by cscheid** [comment]
Thanks for the report. I'm the author of that demo 🤦 

The issue is this:

```
  const vg = await import('https://cdn.jsdelivr.net/npm/@uwdata/vgplot/+esm');
```

`vgplot` probably changed their API on the latest version and I need to ensure this import is version bound. Can you file this bug over on https://github.com/cscheid/quarto-dashboard-ojs-examples? Thanks.
