### ISSUE TITLE
quarto preview fails when path contains an apostrophe

### ISSUE THREAD

**Issue by kevinushey** [quarto-dev/quarto-cli#9133]
### Bug description

Originally filed at https://github.com/rstudio/rstudio/issues/13900, but this is actually a separate issue from what's described in that issue (since the one here is related to Quarto documents containing Python chunks). It looks like Quarto does some substitution here:

https://github.com/quarto-dev/quarto-cli/blob/8df775135b4b4197dc2f750bf0cf88393550fa2d/src/resources/jupyter/lang/python/setup.py#L185-L187

However, if the inserting string contains a single quote, then the `os.chdir()` request will fail.

### Steps to reproduce

Create a quarto document within a directory containing an apostrophe, and then try to execute `quarto preview <doc.qmd>`. Here's a minimal example:

`````
--- 
format: dashboard
--- 

```{python}
```
`````

**Comment by cscheid** [comment]
(I was reading this _today_ for #9130 and thinking it was only a matter of time...)
