### ISSUE TITLE
"docs: add a note to show how to upgrade ojs core library" now fails

### ISSUE THREAD

**Issue by kletts** [quarto-dev/quarto-cli#9142]
### What would you like to do?

Report an issue on quarto.org

### Description

The PR request to [add a note to show how to upgrade ojs library](https://github.com/quarto-dev/quarto-web/pull/802) suggests adding the following to a quarto doc: 
```{ojs}
Plot = import("https://esm.sh/@observablehq/plot")
```
Also noted at [Quarto Libraries](https://quarto.org/docs/interactive/ojs/libraries.html#stdlib)

As of March 2024 this fails and produces the error: 
```
SyntaxError: The requested module '/v135/d3@7.9.0/esnext/d3.mjs' does not provide an export named 'schemeObservable10'
```

Potentially stemming from the 14 March release of d3 as v7.9.0. 

As a workaround I found that using the skypack CDN provides the latest Plot functionality without also updating d3 and avoids this error: 
```
Plot = import("https://cdn.skypack.dev/@observablehq/plot") 
```
I don't know enough about d3 otherwise with regards to the consequences of the schemeObservable10.

**Comment by cscheid** [comment]
Do I understand correctly that this happens because observable's plot library imports from the latest d3 release and that release doesn't have the requested export? In that case, I think I would like to wait for Plot to issue a patch.

**Comment by kletts** [comment]
If you are asking me, sorry I can't help, way beyond my expertise. 

All I can observe is that the link to esm.sh points to very simple website that simple collects a whole bunch of other libraries:

```
/* esm.sh - @observablehq/plot@0.6.14 */
import "/v135/@observablehq/plot@0.6.14/es2022/src/plot.js";
import "/v135/d3@7.9.0/es2022/d3.mjs";
import "/v135/interval-tree-1d@1.0.4/es2022/interval-tree-1d.mjs";
import "/v135/isoformat@0.2.1/es2022/isoformat.mjs";
export * from "/v135/@observablehq/plot@0.6.14/es2022/plot.mjs";
```

**Comment by cderv** [comment]
For reference, this is upstream issue reported first at 
* https://github.com/observablehq/plot/issues/2022

and then reported at esm.sh
* https://github.com/esm-dev/esm.sh/issues/810

So using another CDN seems the good solution for now.

**Comment by cscheid** [comment]
Let's use jsdelivr https://github.com/observablehq/plot/issues/2022#issuecomment-1994494407

They didn't use to have an `esm` option but it seems they do now, and I expect them to be more stable than esm.sh or skypack.dev
