### ISSUE TITLE
Source code link for Quarto Dashboard Observable penguins example broken

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-cli#9143]
### What would you like to do?

Report an issue on quarto.org

### Description

The Penguin example at the bottom of this page under the Observable heading (https://quarto.org/docs/dashboards/examples/) has a broken link for the source code that points to here: https://github.com/jjallaire/ojs-penguins-dashboard/blob/main/penguins.qmd

**Comment by mcanouil** [comment]
Thanks.

Closing in favour of:
- https://github.com/quarto-dev/quarto-cli/issues/9005
