### ISSUE TITLE
Example is incomplete

### ISSUE THREAD

**Issue by daaronr** [quarto-dev/quarto-cli#9147]
### What would you like to do?

Report an issue on quarto.org

### Description

https://quarto-ext.github.io/manuscript-template-jupyter/

This example is good but incomplete. Data section is missing etc.

**Comment by mcanouil** [comment]
What do you need in "data section" and "conclusion"? Some kind of lorem ipsum?
Could you clarify what could improve the example?

**Comment by daaronr** [comment]
Still, I wanted an example to show the data pipeline transparently, that showed how the data could be brought in from a source, filtered (e.g., according to a pre-analysis plan) and transformed, and analysed. To show how well this worked for open science and replicability. OK, this does hint at how this would be done. 

Maybe I prefer the code generating the tables to be in a 'fold' in the paper rather than linked out to another space? That feels easier and more concrete.

The "Conclusion" and "Data and methods" sections are empty, which makes it seem a bit incomplete

It would also be nice if the example had at least some interactive dashboard content, such as the DT:datatables thing in R. 

But OK, it is pretty good. It just didn't hit home the point that "we should be using this for our research from now on" (which I think we should do).

**Comment by mcanouil** [comment]
You have many interactivity examples in the documentation.
You also have various examples of computations in the documentation.

It's up to you to fill the blank with whatever you need.

A Manuscript project is mostly for publication, so I the data and conclusion sections are the usual sections of scientific articles.

The manuscript example is to show what a manuscript project is and not to aggregate all Quarto features into one single example.

**Comment by daaronr** [comment]
OK, thesemay be in the documentation, true.  But one of the big selling points of this format, rather than just a PDF in a journal, is the ability to show, interactive graphics, dashboards, etc. So I want to try to sell this to academics as an improvement, and this is one of the features I want to be able to show in the example.

**Comment by mcanouil** [comment]
I am sorry but the example is a Git repository you can clone/fork, then modify to your own liking.
You can for example, go to the interactivity pages of the documentation, copy/paste the example where you want, etc.
