### ISSUE TITLE
Project resources fails to copy with `../`

### ISSUE THREAD

**Issue by kylebutts** [quarto-dev/quarto-cli#9154]
### Bug description

Using [`resources` option](https://quarto.org/docs/reference/projects/websites.html) fails to work with `../` path. 

### Steps to reproduce

Run `quarto create website` to set up template website. Run `touch hello.txt` to create a file up one directory from the website. Then, add 
``` yml
project:
  type: website
  resources: 
    - ../hello.txt
```

After rendering, `hello.txt` does not show up in the output folder. This also fails with absolute path. This does not happen when using `hello.txt`, or using `./hello.txt`.

### Expected behavior

The files should be copied to the output dir

### Your environment

Visual Studio Code: 

Version: 1.87.2 (Universal)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:21:31.043Z (1 wk ago)
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

R: 

R version 4.3.2 (2023-10-31) -- "Eye Holes"
Platform: aarch64-apple-darwin20 (64-bit)

### Quarto check output

Quarto 1.4.545
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.545
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: ir, julia-1.9, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
I believe it is expected as you are trying to get resources external to the project here.

**Comment by kylebutts** [comment]
Hmm, I'm using quarto in `_quarto` within a larger project and I wanted to copy files over from a different directory within the project. But maybe there's not a good solution to this?

**Comment by mcanouil** [comment]
The main design choice in Quarto is to make projects self-contained, *i.e.*, all (or nearly) paths are relatives to project root and a path starting with `/` means root of the project not root of your file system.

You can copy the resources, try hard links, and possibly symbolic links (known to not work well so far).

**Comment by kylebutts** [comment]
It is obviously your call and it's not too much hassle to copy files. Also, I think a lot of folks set up quarto in subfolders and would find this useful. 

https://github.com/search?q=output-dir:+../docs+language:YAML&type=code&l=YAML shows 432 projects use `output-dir: ../docs/` in their yaml file, presumably to upload to github pages. All these projects would need to make duplicate files in the quarto folder *and* need to keep them in sync by your answer.

**Comment by mcanouil** [comment]
`output-dir` is a completely different thing. It is the target directory of the rendered files with their resources.

You are specifically trying to use resources are not not in the project. `output-dir` being outside of the project or not, won't change that fact.

**Comment by cscheid** [comment]
> Hmm, I'm using quarto in _quarto within a larger project and I wanted to copy files over from a different directory within the project. But maybe there's not a good solution to this?

If you're on Unix, you can use hard links. But one way or another, this is something that you will have to handle externally. As @mcanouil said, it's an explicit decision on our part. I'm going to go ahead and close this.
