### ISSUE TITLE
`---` no whitespace YAML parse exception

### ISSUE THREAD

**Issue by grcatlin** [quarto-dev/quarto-cli#9156]
### Bug description

If I have a `---` followed by a chunk anywhere in my document I get this error message after all of the chunks have been processed:

```
Error running Lua:
YAML parse exception at line 3, column 0,   
while scanning for the next token:
found character that cannot start any token 
stack traceback:
        ...a\Local\Programs\Quarto\share\pandoc\datadir\readqmd.lua:158: in function 'readqmd.readqmd'
        ...pData\Local\Programs\Quarto\share\filters\qmd-reader.lua:13: in function 'Reader'
```

Not sure if related to #3004 or not.

## Errors Out

````qmd
---
```{r}
print(mtcars)
```
````

## Is fine

````qmd
---

```{r}
print(mtcars)
```
````

### Expected behavior

If it's not having whitespace is unacceptable, I'd really appreciate a more helpful error message (specifically the line number on which the error occurred - I had to go through the whole `.qmd` and check line by line to figure out what was going on). If it's supposed to work without whitespace then this is just a bug.

### Your environment

- IDE: VS Code 1.87.2
- OS: Windows 11

### Quarto check output

```bash
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\X\AppData\Local\Programs\Quarto\bin
      CodePage: unknown

[>] Checking tools....................OK    
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK    
      Using: TinyTex
      Path: C:\Users\X\AppData\Roaming\TinyTeX\bin\windows\
      Version: undefined

[>] Checking basic markdown render....OK    

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK    
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/X/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.26

[>] Checking Knitr engine render......OK 
```

**Comment by mcanouil** [comment]
Thanks for the report.

This is clearly the same and anyhow it is considered as a bad syntax by any Markdown linter: https://github.com/quarto-dev/quarto-cli/issues/3004#issuecomment-1289197773

Closing as duplicate.

**Comment by cscheid** [comment]
(I was going to reopen it as a `lint` issue, but it's there on our `lint` epic already.

@grcatlin This is definitely ugly on our side, but Pandoc's reader unfortunately doesn't provide location information, and so we can't do it either. It's something we will fix, but it's a large engineering task, so it won't happen right away.
