### ISSUE TITLE
quarto 1.4.551 causes docx table rendering issue on flextable

### ISSUE THREAD

**Issue by datapython** [quarto-dev/quarto-cli#9157]
### Bug description

My qmd file was rendered ok for docx including the flextable with 1.3.433 but only one problem of caption missing. After updated to 1.4.551, the caption started working, but the rendered table inside the docx was totally squeezed into a strip. By the way, this table is coded with gtsummary and converted into flextable for autofit the width of docx.  

This was rendered with 1.3.433.
![image](https://github.com/quarto-dev/quarto-cli/assets/4671952/3cada247-7e32-42fa-9027-48df02e9fe0d)

This was rendered with 1.4.551.
![image](https://github.com/quarto-dev/quarto-cli/assets/4671952/ced37236-5411-4b88-8402-d6f1542aed17)

However, testing with mtcars by adding a column with long colname and long string value could not replicate the issue. At this time I cannot share my data.    

RStudio Pro 2023.09.0
Ubuntu 22.04.3 LTS

**Comment by mcanouil** [comment]
Could you share a small **self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.
---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by mcanouil** [comment]
Very likely a duplicate or related to:

- https://github.com/quarto-dev/quarto-cli/issues/7321
