### ISSUE TITLE
Documentation won't work with python in visual studio code. 

### ISSUE THREAD

**Issue by HHpaul1996** [quarto-dev/quarto-cli#9167]
### What would you like to do?

Report an issue on quarto.org

### Description

Hey, 
I just got the assigment to generate a pdf file with python in visual studio and its super annoying, that just a small percentage of the documentation works with this combination. Most of it seems to be meant for html. Could you please specify your documentation for pdf?

**Comment by mcanouil** [comment]
Could you elaborate? Which part of the documentation does not work across format when using Python?

**Comment by HHpaul1996** [comment]
I tried for example to put in a footnote (https://quarto.org/docs/authoring/footnotes-and-citations.html, section footnote), which didn’t work. I don’t remember everything, which didn’t. Just ^[footnote] worked. 

 

Von: Mickaël Canouil ***@***.***> 
Gesendet: Freitag, 22. März 2024 13:46
An: quarto-dev/quarto-cli ***@***.***>
Cc: HHpaul1996 ***@***.***>; Author ***@***.***>
Betreff: Re: [quarto-dev/quarto-cli] Documentation won't work with python in visual studio code. (Issue #9167)

 

Could you elaborate? Which part of the documentation does not work across format when using Python?

**Comment by mcanouil** [comment]
Could you share a small **self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

PS: don't keep previous replies when answering by email, as it gets added with your reply.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.
