### ISSUE TITLE
Duplicated References Title in html export.

### ISSUE THREAD

**Issue by f10w3r** [quarto-dev/quarto-cli#920]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/20207927/169019697-731f01b1-96c6-4222-a323-47b04f079b5e.png">
<img width="216" alt="image" src="https://user-images.githubusercontent.com/20207927/169019941-50ea82a7-d7fa-49f8-add7-2ea33353261b.png">

The references title in html export is duplicated, while the docx and pdf versions are OK.

**Comment by jjallaire** [comment]
@dragonstyle Could you take a look at this?

**Comment by dragonstyle** [comment]
Could you provide a copy of a document that reproduces the issue? I'm having trouble reproducing it locally with a simple document

![Screen Shot 2022-05-18 at 9 52 42 AM](https://user-images.githubusercontent.com/261654/169056873-f93ffa1f-54ac-49ab-934f-48231f512f64.png)
.

**Comment by cderv** [comment]
@dragonstyle I believe this is a difference in behavior from R Markdown and default Pandoc. 
Is quarto setting a default title for the Reference Part ? 

Try this 
````markdown
---
title: "Untitled"
author: "Dick Startz"
date: "`r Sys.Date()`"
bibliography: packages.bib
---

```{r}
knitr::write_bib(file = "packages.bib")
```

See about [@R-base]

# References 
````

With `rmarkdown::render("test.qmd", "html_document")`, you'll get the reference section title as included in the body. 

With `quarto render --to html`, you'll get a duplication. 

With Pandoc, you'll get the same behavior as R Markdown
````
quarto pandoc -f markdown -t html -s --citeproc -o test.html test.qmd
````

Manual says: https://pandoc.org/MANUAL.html#placement-of-the-bibliography
> If the style calls for a list of works cited, it will be placed in a div with id refs, if one exists:
>
> ::: {#refs}
> :::
> Otherwise, it will be placed at the end of the document.

Are we setting `reference-section-title` somewhere ? If set, then you can reproduce with Pandoc / R Markdown also
See
````sh
quarto pandoc -t html -s --citeproc -Mreference-section-title=References -o test.html test3.qmd
````

Hope it helps

**Comment by dragonstyle** [comment]
The note about only affecting H1s was the key, @cderv! Should be fixed here where we should now collect even H1. headings in this case:

b16b36a1185981d289633a4064bc36b60e30c449

**Comment by cderv** [comment]
Glad I could help :

**Comment by f10w3r** [comment]
Thank you so much! @jjallaire @dragonstyle @cderv 
I am sorry for obscure description, but I think you guys have got the idea. 
You guys are just so quick. I am in China and I am sorry that I can't catch up with your time.

I have checked the new version. The only problem right now is that it is The Bigger Title that is supposed to stay.
<img width="405" alt="image" src="https://user-images.githubusercontent.com/20207927/169205080-29d934f8-c354-4d0d-90c0-c4e4b36e9249.png">

The smaller title looks too smaller than the other Heading-1s.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/20207927/169205549-f9f74ad2-f981-4571-8343-a7bb8906d74a.png">

I am using Quarto for writing my PhD dissertation, I love the philosophy in it. I have recommended it to my supervisor, and he loves it too. Your work is promising for building a reproducible research routine.

Good luck to you all!

**Comment by dragonstyle** [comment]
By default, Quarto provides a stylized appendix for documents. You can control the behavior of the appendix using `appendix-style`. More about this here: https://quarto.org/docs/authoring/appendices.html#appendix-style

I would recommend you try either:

```yaml
appendix-style: plain
```

or 

```yaml
appendix-style: none
```

**Comment by cderv** [comment]
@dragonstyle this is our default style to bibliography in appendix right ? 
Maybe this would be worth mentioning in the bibliography section: https://quarto.org/docs/authoring/footnotes-and-citations.html#bibliography-generation
> It will be placed in a div with the id refs if one exists: (...) 
> If no such div is found, the works cited list will be placed at the end of the document.

Maybe I missed this part in the doc, but it may not be obvious behavior, especially coming from Pandoc or R Markdown

````markdown
---
title: "Untitled"
author: "Dick Startz"
date: "`r Sys.Date()`"
format: html
bibliography: packages.bib
---

```{r}
knitr::write_bib(file = "packages.bib")
```

See about [@R-base]

# References

::: {#refs}
:::

# Appendix after Ref

Content
````

This put references in the appendix even if the div with id has been added in middle of the doc. 

Can we say somewhere, I don't want references put in appendix ? 
Something like 
````markdown
# References { appendix=false} 

::: {#refs}
:::
````

or 
````markdown
# References {.no-appendix}

::: {#refs}
:::
````

Maybe we don't want this but I least we should clarify the different part of the documentation. 
What do you think ?

**Comment by dragonstyle** [comment]
Definitely agree that note in docs would be helpful no matter what we conclude below! I'll leave this open until I get that added...

You're right that we do find and collect the references into the appendix, by default. The user can control the styling and organization / gathering via:

`default` - organize and style the appendix
`plain` - organize but don't style the appendix
`none` - do not organize or style the appendix

I would normally expect users to write something like:

````markdown
---
title: "Untitled"
author: "Dick Startz"
date: "`r Sys.Date()`"
format: html
bibliography: packages.bib
---

```{r}
knitr::write_bib(file = "packages.bib")
```

See about [@R-base]

# References

::: {#refs}
:::

# Appendix after Ref  {.appendix}

Content

````

To have their last section added to the appendix (we'll organize it into the appendix for them if specified in one of the above options). Alternatively, they could write:


````markdown
---
title: "Untitled"
author: "Dick Startz"
date: "`r Sys.Date()`"
format: html
bibliography: packages.bib
appendix-style: none
---

```{r}
knitr::write_bib(file = "packages.bib")
```

See about [@R-base]

# References

::: {#refs}
:::

# Appendix after Ref

Content

````

And we would just render the sections as is without manipulating them at all.

Do you think if documented better / linked from the references documention this is clear enough?

**Comment by cderv** [comment]
> Do you think if documented better / linked from the references documentation this is clear enough?

As discussed, I think we just need to document better our default behavior and our choice, and linking Reference documentation section with Appendicies as they are directly linked. 

Thanks !

**Comment by cderv** [comment]
I agree. This sounds good ! Thanks !
