### ISSUE TITLE
Float crossref breaks longtable in a quarto PDF book

### ISSUE THREAD

**Issue by jonpeake** [quarto-dev/quarto-cli#9207]
### Bug description

When rendering a book in PDF form and including a longtable in a custom float reference div, the table does not break across multiple pages. I believe this is an extension of https://github.com/quarto-dev/quarto-cli/issues/7604, which appears to be fixed for some formats, but not book format.

### Steps to reproduce

Create quarto book project, add following to introduction.qmd:
````
::: {#apptbl-tbl1}
```{r}
knitr::kable(cars, format = "latex", longtable = T)
```

This is a long table
:::
````

### Expected behavior

Table should render in long format, i.e., split across pages

### Actual behavior

Table produces on one page, cut off at bottom

### Your environment

RStudio 2023.12.1 Build 402
Windows 10

### Quarto check output

```
Quarto 1.5.27
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.27
      Path: C:\Users\jonathan.peake\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.02
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\jonathan.peake\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.7
      Path: C:/Users/jonathan.peake/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 4.11.1
      Kernels: python3

(\) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\jonathan.peake\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\jonathan.peake\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 14, in
<module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK
```

**Comment by cscheid** [comment]
Longtables are unfortunately not supported in custom crossref and there's nothing we can do about it. The latex longtable package hard-codes the crossref counter for the `table` environment, and so we need to convert longtable environments into tabulars before rendering.

**Comment by jonpeake** [comment]
Well that is certainly a bummer, but I appreciate the quick response. Thank you!
