### ISSUE TITLE
Bibliography can be generated by commented out div

### ISSUE THREAD

**Issue by pmoris** [quarto-dev/quarto-cli#9209]
### Bug description

A commented out bibliograpy div like the one below, still causes the bibliography to be created on that particular chapter/page for quarto books.

```
<!-- ## References

::: {#refs}
::: -->
```

I initially didn't realize that a quarto book could only have a single bibliography. When I noticed my second chapter didn't show the bibliography and reading through the documentation, I commented out the divs in both chapters and added an (unnumbered) reference chapter with just the #refs div. However, the bibliography kept showing up in the 1st chapter, and then moved to the 2nd one after I tried removing the entire 1st chapter (thinking it was some kind of weird caching issue). Eventually I realized that the commented out div sections were the culprit and that they were still triggering the bibliography creation.

I'm using the `strip-comments: true` option, in case that matters.

Incidentally, I had also been playing around with the [section-bibliographies](https://github.com/pandoc-ext/section-bibliographies) extension and couldn't get it to work, but I'm beginning to suspect that the same thing was causing an issue.

### Steps to reproduce

_quarto.yml
```
project:
  type: book

book:
  title: "booktest"
  author: "Norah Jones"
  date: "3/27/2024"
  chapters:
    - index.qmd
    - 1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
```

1.qmd
```
citation @knuth84

<!-- ## References

::: {#refs}
::: -->
```

references.qmd
```
# References {.unnumbered}

::: {#refs}
:::
```

### Expected behavior

Commented out #refs divs should not generate the bibliography on the respective page of a quarto book project.

### Actual behavior

Commented out #refs divs do generate the bibliography on the respective page of a quarto book project, ignoring any uncommented such divs that appear elsewhere.

### Your environment

OS: Windows 10
IDE: VSCode + WSL Ubuntu 22.04 for quarto render/preview

### Quarto check output

Quarto 1.4.551
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.551
      Path: /home/pmoris/opt/quarto/quarto-1.4.551/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.03.13
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/pmoris/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.14 (Conda)
      Path: /home/pmoris/miniforge3/envs/itptest/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

      There is a environment.yml file in this directory. Is this for a conda env that you need to restore?

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /home/pmoris/miniforge3/envs/itptest/lib/R
      LibPaths:
        - /home/pmoris/miniforge3/envs/itptest/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")

**Comment by mcanouil** [comment]
That's not how the "ref div" works.
It is not an opt-in/out thing.

The "ref div" is there to explicitly place the bibliography, if not set it means "at the end".

**Comment by pmoris** [comment]
> The "ref div" is there to explicitly place the bibliography, if not set it means "at the end".

> removing the explicit positioning of the bibliography makes the bibliography appear on every chapters ("at the end") that include a reference. That's the designed behaviour (not a bug) you are experiencing.

Oh, I see! Based on the docs I thought that this meant "at the end of the book", not "the end of each chapter". 

That means the section-bibliography is indeed unnecessary for what I want to do.

**However, I'm still seeing strange behaviour when commenting out the ref div.** I expected it to act as if it's not there at all when I comment it out, and that it default to the standard behaviour (i.e., references at the end of each chapter in this case). However, having a single (or multiple) commented out divs, together with either no explicit div or an explicit div, still causes the bibliography to appear where the commented out div is placed, instead of where the real one is or at the end of each chapter.

I've seen a few different behaviours of this too when not doing a full build, but a preview. Doing a new preview or render does seem to result in consistent behaviour though.

Am I still missing something here?

**Comment by mcanouil** [comment]
The HTML comments only works for text.
All other contents are processed.
It's unrelated to the "ref div".

- https://github.com/quarto-dev/quarto-cli/issues/5100

**Comment by pmoris** [comment]
Roger, thanks for clarifying!
