### ISSUE TITLE
Rstudio render error

### ISSUE THREAD

**Issue by Damonsoul** [quarto-dev/quarto-cli#921]
As shown in the  screenshot，when I  create mlr3 learner inRstudio, it can work in chunk. But when I render it, it failed
![1652880829(1)](https://user-images.githubusercontent.com/95331558/169051454-3bb7bd75-f455-4976-b723-cc6dacb8ba30.png)

my project is encoded by UTF-8,but my local is encoded as follow

> Sys.getlocale()
[1] "LC_COLLATE=Chinese (Simplified)_China.936;LC_CTYPE=Chinese (Simplified)_China.936;LC_MONETARY=Chinese (Simplified)_China.936;LC_NUMERIC=C;LC_TIME=Chinese (Simplified)_China.936"

**Setup**
I use

- R version 4.1.3 (2022-03-10) Platform: x86_64-w64-mingw32/x64 (64-bit)
- Quarto v0.9.424
- RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**Comment by jjallaire** [comment]
If you could provide a git repo with a minimal reproducible example of this error we can take a look.

**Comment by Damonsoul** [comment]
@jjallaire  thank u for replying，example as follow
https://github.com/Damonsoul/Quarto/blob/main/quarto_mlr3_error.qmd

**Comment by jjallaire** [comment]
This same error occurs if you paste this code into an R script and execute it (so it has nothing to do with Quarto). If you get it  working in .R then it should also work in Quarto. Best of luck and sorry we couldn't be of more help.
