### ISSUE TITLE
[1.5 Docs] Update Disabling Table Processing Docs 

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#9215]
For the 1.5 release, we will need to update https://quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing
to reflect changes in https://quarto.org/docs/prerelease/1.5/lua-table-processing.html.

In particular:

* Add an example of adding the comment to a HTML Raw Block in the main section
* ~Discuss emitting the comment to table output in the [Library Authors](https://quarto.org/docs/authoring/tables.html#library-authors) section, as an alternative to putting an attribute in the `<table>` tag.~ Completed

**Comment by cderv** [comment]
Feedback from @jeremy-allen: we should also add clear implications of what disabling html table processing means. What feature are lost for example. (like cross reference with caption processing )

**Comment by cwickham** [comment]
@cderv and @cscheid I think the minimum for 1.5 is complete: we mention being able to add the comment at https://prerelease.quarto.org/docs/authoring/tables.html#library-authors

Is there a use case for disabling Quarto table processing via the HTML comment for your general Quarto user? And what exactly are the features that are lost?

**Comment by cscheid** [comment]
> Is there a use case for disabling Quarto table processing via the HTML comment for your general Quarto user? 

Not a new one over being able to do it in the table itself (and that was already available). The reason to do it in the comment is in the off-chance that the library code doesn't control the emission of the table element itself.

> And what exactly are the features that are lost?

Our one-sentence description for this feature is "HTML table is table AST". So turning this off means that the HTML table will not be parsed into Markdown, and so will not be rendered to other outputs. This means no Quarto Markdown features, like crossreferences, shortcodes, etc.
