### ISSUE TITLE
Lists do not seem to work inside examples/theorems/etc in typst

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#9219]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/9218

<div type='discussions-op-text'>

<sup>Originally posted by **psads-git** March 28, 2024</sup>

All the below special fenced divs don't properly emit Typst.

```
---
format: typst
---

::: {#thm-some}
Some text:

- item 1
- item 2

:::

::: {#lem-some}
Some text:

- item 1
- item 2

:::

::: {#cor-some}
Some text:

- item 1
- item 2

:::

::: {#prp-some}
Some text:

- item 1
- item 2

:::

::: {#cnj-some}
Some text:

- item 1
- item 2

:::

::: {#def-some}
Some text:

- item 1
- item 2

:::

::: {#exm-some}
Some text:

- item 1
- item 2

:::

::: {#exr-some}
Some text:

- item 1
- item 2

:::
```

</div>

---

The following will emit the proper Typst.

````qmd
---
format: typst
---


::: {#sol-some}
Some text:

- item 1
- item 2

:::

::: {#rem-some}
Some text:

- item 1
- item 2

:::

````

**Comment by psads-git** [comment]
Thanks, @mcanouil!

**Comment by psads-git** [comment]
Thanks, @mcanouil! Is there some workaround for the time being?

**Comment by mcanouil** [comment]
> Thanks, @mcanouil! Is there some workaround for the time being?

Write raw Typst.

**Comment by psads-git** [comment]
OK, @mcanouil, thanks.

**Comment by cscheid** [comment]
(I can take this one.)
