### ISSUE TITLE
Multiple entries of Large table in the list of tables for scrbook class, when I use knitr::kable()

### ISSUE THREAD

**Issue by bhattmaulik** [quarto-dev/quarto-cli#9236]
### Bug description

I am creating a LaTeX document, with the document class `scrbook`. In this document, I am creating a long table, which would span through multiple pages. If I format the table using knitr::kable() function, it will show multiple entries in the list of tables. But when I remove knitr::kable(), there is only one entry for this table in the list of tables.

### Steps to reproduce

````
---
title: "Long Table"
author: "Maulik Bhatt"
format:
  pdf:
    documentclass: scrbook
    toc: true
    lot: true
    pdf-engine: lualatex
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).

## Long Table

```{r}
#| echo: false
#| label: tbl-dummy
#| tbl-cap: "Long Table Spanning Multiple Pages"
dummy_table <- data.frame(Index = 1:100,Value = rnorm(100))
dummy_table |> knitr::kable()
```
````

### Expected behavior

There should be only one entry of the long table in the list of tables

### Actual behavior

In the list of table, the long table appears as many times as the number of pages on which the table is present. If the table is 5 pages long, then there will be 5 entries of "Long Table" in the list of tables.

### Your environment

IDE: RStudio 2024.04.0-daily+668 "Chocolate Cosmos" Daily (844078e919e804808ccbc1c2661fc0476785b304, 2024-03-29) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0-daily+668 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.5.27 (C:/Users/Hp/AppData/Local/Programs/Quarto/bin/quarto.exe)
OS: Windows 11

### Quarto check output

$ quarto check
Quarto 1.5.27
[>] Checking versions of quarto bi
nary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation..
....OK
      Version: 1.5.27
      Path: C:\Users\Hp\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

(|) Checking tools................
[>] Checking tools................
....OK
      TinyTeX: (external install)
      Chromium: (not installed)

(|) Checking LaTeX................
....OK
      Using: TinyTex
      Path: C:\Users\Hp\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

(|) Checking basic markdown render
....OK

[>] Checking Python 3 installation
....(None)

      Unable to locate an installe
d version of Python 3.
      Install Python 3 from https:
//www.python.org/downloads/

(|) Checking R installation.......
....OK
      Version: 4.3.3
      Path: C:/PROGRA~1/R/R-43~1.3
      LibPaths:
        - C:/Users/Hp/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.3/library
      knitr: 1.45
      rmarkdown: 2.26

(|) Checking Knitr engine render..
....OK

**Comment by cscheid** [comment]
(I can't seem to reproduce your example because `lualatex` freezes during rendering for me in your example, but `pdflatex` works for me)

That's `longtable` behavior, not Quarto.
https://tex.stackexchange.com/questions/26024/how-to-use-a-longtable-with-only-one-entry-in-the-list-of-tables
