### ISSUE TITLE
Issues using {gt} objects as cross-referenced tables

### ISSUE THREAD

**Issue by SEthanMilne** [quarto-dev/quarto-cli#924]
I'm trying to incorporate a {gt} object as a table in a Quarto .qmd document that outputs to PDF.

When I try to add a table caption within a code chunk (using #| tbl-cap: xyz), I get the following error:

> **Package array Error:  Illegal pream-token (\caption): `c' used.**
> 
> **See the array package documentation for explanation.**
> **Type  H <return>  for immediate help.**
>  **...**                                              
>                                                   
> **l.252 \caption**
>               **{\label{tbl-test}Results }** 
> 
> **see Untitled.log for more information.**

This error occurs whether I try to output the {gt} object using only `gt()` AND if I use `as_latex()` afterwards.

Here's a test document:

---
title: "Untitled"
format: pdf
---

## Libraries

```{r}
library(tidyverse)
library(gt)
```

## Fake Data

```{r}
test_data <- tribble( ~a, ~b,
                      1, 2,
                      3, 4,
                      5, 6
)
```

## Table Output

```{r}
#| label: tbl-test
#| tbl-cap: "Results"


test_data |> gt()
```

## Cross-reference

@tbl-test

**Comment by cderv** [comment]
For reference this has also been asked on Stakoverflow: https://stackoverflow.com/questions/72251411/quarto-table-cross-reference-gt

@SEthanMilne can you format your issue correctly so it is easier to read the example ? Thanks you. 
See https://yihui.org/issue/#please-format-your-issue-correctly

As I answered on SO, I can't reproduce on my end using this example

````markdown
---
title: "example"
format: 
  pdf: 
    documentclass: article
editor: visual
---

```{r}   
library(tidyverse)
library(gt)
tbl_1 <- tribble(~x, ~y,
                 1, 2,
                 3, 4)
```


```{r}
#| label: tbl-table-1
#| tbl-cap: "table 1"
tbl_1 %>% gt()
```

See table @tbl-table-1
````

I am using TinyTeX distribution though, which is TeX Live 

````
❯ tlmgr --version
tlmgr revision 63033 (2022-04-15 07:19:42 +0200)
tlmgr using installation: C:/Users/chris/AppData/Roaming/TinyTeX
TeX Live (https://tug.org/texlive) version 2022
````

**Comment by SEthanMilne** [comment]
Sorry! This is my second issue — thanks for the link re: formatting.

My session info:
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.3.1, RStudio 2022.2.2.485

Locale: en_CA.UTF-8 / en_CA.UTF-8 / en_CA.UTF-8 / C / en_CA.UTF-8 / en_CA.UTF-8

Package version:
  askpass_1.1         assertthat_0.2.1    backports_1.4.1     base64enc_0.1.3    
  bit_4.0.4           bit64_4.0.5         bitops_1.0.7        blob_1.2.3         
  broom_0.8.0         bslib_0.3.1         callr_3.7.0         cellranger_1.1.0   
  checkmate_2.1.0     cli_3.3.0           clipr_0.8.0         colorspace_2.0-3   
  commonmark_1.8.0    compiler_4.2.0      cpp11_0.4.2         crayon_1.5.1       
  curl_4.3.2          data.table_1.14.2   DBI_1.1.2           dbplyr_2.1.1       
  digest_0.6.29       dplyr_1.0.8         dtplyr_1.2.1        ellipsis_0.3.2     
  evaluate_0.15       fansi_1.0.3         farver_2.1.0        fastmap_1.1.0      
  forcats_0.5.1       fs_1.5.2            gargle_1.2.0        generics_0.1.2     
  ggplot2_3.3.5       glue_1.6.2          googledrive_2.0.0   googlesheets4_1.0.0
  graphics_4.2.0      grDevices_4.2.0     grid_4.2.0          gt_0.5.0           
  gtable_0.3.0        haven_2.5.0         highr_0.9           hms_1.1.1          
  htmltools_0.5.2     httr_1.4.2          ids_1.0.1           isoband_0.2.5      
  jquerylib_0.1.4     jsonlite_1.8.0      knitr_1.38          labeling_0.4.2     
  lattice_0.20.45     lifecycle_1.0.1     lubridate_1.8.0     magrittr_2.0.3     
  MASS_7.3.57         Matrix_1.4.1        methods_4.2.0       mgcv_1.8.40        
  mime_0.12           modelr_0.1.8        munsell_0.5.0       nlme_3.1.157       
  openssl_2.0.0       pillar_1.7.0        pkgconfig_2.0.3     prettyunits_1.1.1  
  processx_3.5.3      progress_1.2.2      ps_1.7.0            purrr_0.3.4        
  R6_2.5.1            rappdirs_0.3.3      RColorBrewer_1.1.3  readr_2.1.2        
  readxl_1.4.0        rematch_1.0.1       rematch2_2.1.2      reprex_2.0.1       
  rlang_1.0.2         rmarkdown_2.14      rstudioapi_0.13     rvest_1.0.2        
  sass_0.4.1          scales_1.2.0        selectr_0.4.2       splines_4.2.0      
  stats_4.2.0         stringi_1.7.6       stringr_1.4.0       sys_3.4            
  tibble_3.1.6        tidyr_1.2.0         tidyselect_1.1.2    tidyverse_1.3.1    
  tinytex_0.38        tools_4.2.0         tzdb_0.3.0          utf8_1.2.2         
  utils_4.2.0         uuid_1.1.0          vctrs_0.4.1         viridisLite_0.4.0  
  vroom_1.5.7         withr_2.5.0         xfun_0.31           xml2_1.3.3         
  yaml_2.3.5         

My TinyTex distribution:
❯ tlmgr --version
tlmgr revision 57970 (2021-02-27 15:17:34 +0100)
tlmgr using installation: /usr/local/texlive/2021
TeX Live (https://tug.org/texlive) version 2021


My reproducible example:

````
---
title: "test"
format: pdf
---

## Libraries

```{r}
library(tidyverse)
library(gt)
```

## Fake Data

```{r}
test_data <- tribble( ~a, ~b,
                      1, 2,
                      3, 4,
                      5, 6
)
```

## Table Output

```{r}
#| label: tbl-test
#| tbl-cap: "Results"


test_data |> gt()
```

## Cross-reference

@tbl-test

````

**Comment by cderv** [comment]
I can reproduce now, not sure why. I'll have a closer look at the issue.

**Comment by cderv** [comment]
This is the markdown output produced before Quarto processing and pandoc conversion: 

````markdown
::: {.cell-output-display}
\captionsetup[table]{labelformat=empty,skip=1pt}
\begin{longtable}{rr}
\toprule
a & b \\ 
\midrule
1 & 2 \\ 
3 & 4 \\ 
5 & 6 \\ 
\bottomrule
\end{longtable}
:::
:::
````

In the TeX file, this is what we get
````tex
\captionsetup[table]{labelformat=empty,skip=1pt}
\begin{longtable}
\caption{\label{tbl-test}Results }
{rr}
\toprule
a & b \\ 
\midrule
1 & 2 \\ 
3 & 4 \\ 
5 & 6 \\ 
\bottomrule
\end{longtable}
````

I believe the caption is not placed in the right place, and `\\` new line are missing maybe. 

We need to place the caption after the alignement information. Lua filter for tbale caption needs to be adjusted

**Comment by cderv** [comment]
> Do you want an issue for that ?

As discussed with @rich-iannone, we'll improve LaTeX table generation in **gt** first then adapt Quarto cross ref feature accordingly.

**Comment by kwakuduahc1** [comment]
Dear @jjallaire , 

Am I right that the label for the table must be preceded by `tbl-` else the crossref will not work?

E.g. 

````
```{r}
#| label: mytable
#| tbl-cap: "My wonderful table"

mtcars |> head() |> knitr::kable()
```

See @mytable will not work

**However**

```{r}
#| label: tbl-mytable
#| tbl-cap: "My wonderful table"

mtcars |> head() |> knitr::kable()

```

See @tbl-mytable works

````

If so, it must be stated clearly in the documentation because both would have worked with rmarkdown.

Also, I think the documentation examples should rather focus on computational tables than markdown tables as tables are more likely to be generated than typed.

Best.

**Comment by jjallaire** [comment]
@kwakuduahc1 Thanks for the feedback! I've revised the docs to emphasize computational tables and to include a more prominent mention of the `tbl-` prefix requirement: https://quarto.org/docs/authoring/tables.html#cross-references

**Comment by kwakuduahc1** [comment]
Thank you. I have read it and it is now very explicit.

Best.
