### ISSUE TITLE
knitr global chunk option fig.format/fig-format only allows a single value if defined in frontmatter

### ISSUE THREAD

**Issue by sebkopf** [quarto-dev/quarto-cli#9241]
### Bug description

The `fig.format` knitr chunk option makes it possible to output plots to multiple file formats during rendering. This works inside a single chunk with the YAML syntax `#| fig.format: !expr c("png", "pdf")` or for the entire document via `knitr::opts_chunk$set(fig.format = c("png", "pdf"))`. 

However, it does not work if defined in the YAML frontmatter:

```
format: 
  html:
    knitr: 
      opts_chunk: 
        fig.format: !expr c("png", "pdf")
```

which results in error `Error in `auto_exts[x]`: ! invalid subscript type 'list'`.

It does also not work if using `fig-format` instead of `fig.format` in either the frontmatter OR the single chunk. I.e. although `#| fig.format: !expr c("png", "pdf")` works for a chunk, `#| fig-format: !expr c("png", "pdf")` results in the following error: 

```
Field "fig-format" has value !expr c("png", "pdf"), which must instead be one of: `retina`, `png`, `jpeg`, `svg`, `pdf`
```

Am I doing something wrong in how I'm defining knitr chunk options in the frontmatter?

### Steps to reproduce

# Example 1

With `fig.format: !expr c("png", "pdf")` (or `fig-format: ...`) in front matter:

````
---
title: "Reproducible example 1"
format: 
  html:
    knitr: 
      opts_chunk: 
        fig.path: "plots/"
        fig.format: !expr c("png", "pdf")
---

```{r}
#| label: plot
plot(cars)
```
````

# Example 2

With `#| fig-format: ` (or `fig-format: !expr c("png", "pdf")`) in chunk:

````
---
title: "Reproducible example 2"
format: 
  html:
    knitr: 
      opts_chunk: 
        fig.path: "plots/"
---

```{r}
#| label: plot
#| fig-format: !expr c("png", "pdf")
plot(cars)
```
````

### Expected behavior

Generation of files `plots/plot-1.pdf` AND `plots/plot-1.png` during rendering.

### Actual behavior

# Example 1

```
Quitting from lines  at lines 12-14 [plot] (example1.qmd)
Error in `auto_exts[x]`:
! invalid subscript type 'list'
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
 10. knitr:::process_group.block(group)
 11. knitr:::call_block(x)
 12. knitr:::block_exec(params)
 13. knitr:::eng_r(options)
 14. knitr:::dev2ext(options)
                                                                                                 
Execution halted
```

# Example 2

```
In file example2.qmd
(line 12, columns 16--37) Field "fig-format" has value !expr c("png", "pdf"), which must instead be one of: `retina`, `png`, `jpeg`, `svg`, `pdf`
11: #| label: plot
12: #| fig-format: !expr c("png", "pdf")
                  ~~~~~~~~~~~~~~~~~~~~~~
13: plot(cars)

ERROR: Validation of YAML cell metadata failed.
ERROR: Render failed due to invalid YAML.
```

### Your environment

- IDE: RStudio 2023.12.1+402
- R `sessionInfo()`:

```
R version 4.3.1 (2023-06-16)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Denver
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] digest_0.6.33     fastmap_1.1.1     xfun_0.43         Matrix_1.6-1.1    lattice_0.22-5    reticulate_1.34.0
 [7] knitr_1.45.17     htmltools_0.5.6.1 png_0.1-8         rmarkdown_2.25.1  cli_3.6.1         grid_4.3.1       
[13] withr_2.5.2       compiler_4.3.1    rstudioapi_0.15.0 tools_4.3.1       evaluate_0.23     Rcpp_1.0.11      
[19] yaml_2.3.8        jsonlite_1.8.7    rlang_1.1.1     
```

### Quarto check output

```
Quarto 1.4.552
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.552
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2020

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.7.6 (Conda)
      Path: /Users/sk/opt/anaconda3/bin/python
      Jupyter: 4.6.1
      Kernels: python3, ir

(-) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```

**Comment by mcanouil** [comment]
`!expr` is a `knitr` specific syntax which is not YAML.
Options provided to `knitr.opts_chunk` are not evaluated through R as far as I know.

In YAML, an array is defined as:

```yaml
key:
 - value1
 - value2
key: [value1, value2]
```

This being said and as described in the documentation, a lot of options are directly available to Quarto as YAML: https://quarto.org/docs/reference/cells/cells-knitr.html
`fig-format` defines the format to be included/embedded in the document, in that regard it does not make sense to want to include several format of the same image at the same place in one document.

I believe you want to generate several figures, which is not what `fig-format` purpose is.
Instead, you want to define the graphic devices to be used:

```
knitr: 
  opts_chunk: 
    dev:
      - svglite
      - ragg_png
```

or at a code cell level:

```
#| dev: [svglite, ragg_png]
```

**Comment by sebkopf** [comment]
Thank you for explaining the difference between `dev` and `fig-format`, `dev` works great!

**Comment by cderv** [comment]
To be clear here, `fig-format` from Quarto is passed onto `dev` for **knitr** engine. `fig-format` is initially a Quarto option, and even if `fig.format` can be set at **knitr** level, this will end up being `dev`. Though as `fig-format` is Quarto generic, it doesn't allow to set different formats which is a **knitr** only feature (**knitr** will create several files for same plots, and use only one in the output). So for this specific feature, you need to use `dev` directly. 

You can do 
````
#| dev: 
#|   - png
#|   - pdf
````

which will use the default device associated with those `png` or `pdf` format, or you can indeed define more specific one like shared above.

**Comment by adomingues** [comment]
Hi @cderv, just to confirm that I got this right:

In `quarto` it is not possible to output a plot in two different formats whilst rendering the `qmd`? 

I am asking because I tried this 

```
#| dev: 
#|   - png
#|   - pdf
```

on a code chunk and only the `png` was generated.

**Comment by mcanouil** [comment]
This is only for `engine: knitr`.
