### ISSUE TITLE
Observable libraries offline

### ISSUE THREAD

**Issue by neocarto** [quarto-dev/quarto-cli#9267]
### Bug description

Is there a way to use Observable local libraries to work offline?

**Comment by mcanouil** [comment]
@neocarto Why did you open an issue?

- https://github.com/quarto-dev/quarto-cli/discussions/9266

**Comment by cscheid** [comment]
You can start tracking down the issue from this file and work your way back should you want to fix it yourself:

https://github.com/observablehq/stdlib/blob/main/src/dependencies.js
