### ISSUE TITLE
Quarto never finishes rendering 

### ISSUE THREAD

**Issue by amzon-ex** [quarto-dev/quarto-cli#9278]
### Bug description

I'm using Quarto on a hybrid setup - VSCode running the remote extension with WSL. I've installed `quarto-cli` on my WSL distro and the Quarto extension on vscode. However, when I want to render an .ipynb or .qmd file, Quarto just keeps rendering (it shows so on the statusbar) and never finishes. No preview opens.

I can use quarto manually from the commandline to open the rendered document on my browser, however.

### Expected behavior

Quarto completes render and shows preview.

### Actual behavior

Rendering never completes and no preview is shown.

### Your environment

- Visual Studio Code on Windows 11
- Ubuntu 23.10 on WSL on Windows 11

### Quarto check output

```
Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/local/texlive/2022/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /bin/python
      Jupyter: 5.7.1
      Kernels: pypy, python3, octave, igwn-py38, igwn-py39-lw

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
Unfortunately, if you don't provide the steps to reproduce, it's unlikely at best we can help you.
We need you to provide us with the means to reproduce this to help you.

**Comment by amzon-ex** [comment]
The thing is, there is no process involved in reproducing this. I just open vscode, open a .ipynb or .qmd file, press `Ctrl+Shift+K` or alternatively the command palette to invoke the render command, and nothing happens, except a text on the statusbar saying
`Rendering foo.ipynb`
which stays that way as long as I keep vscode open.

**Comment by cderv** [comment]
@amzon-ex I can't reproduce this

- I am on Windows and have Ubuntu 22 in WSL
- VSCODE can open using WSL extension. 
- In Ubuntu I have installed quarto cli 
- The Quarto extension is installed in VSCODE WSL version
- When I render, a preview window open in VSCODE. 

Rendering and preview works ok 
![Code_CERMSAF1aC](https://github.com/quarto-dev/quarto-cli/assets/6791940/48c907e9-3484-451d-aaf6-9ee9792d2bc3)

So maybe something related to configuration somehow. Digging through VSCODE logging may help maybe. 

Until we can reproduce, this will be hard to look into. Can you share more details ? Or a specific project this happens with ?

**Comment by amzon-ex** [comment]
Sorry for the delay, had been caught up.

I don't know what to show more than this. I open up a qmd file, and here is how it goes.

![testvid](https://github.com/quarto-dev/quarto-cli/assets/45428344/1445bacf-0ea5-4967-9c31-cffb5054f072)

Happens with a fresh standalone file as well.

**Comment by amzon-ex** [comment]
Thanks for getting back!

Yes, the same thing happens when I replace `jupyter: python3` with `engine: markdown`. 

> Did you try using directly Quarto CLI from the terminal?

Yes, that's how I did my presentation, which I originally started using Quarto for. I had to run quarto via the cli and view the output in a browser.

> When performing tests, you should remove all unnecessary files and ensure there are no obvious things wrong. For instance, i see you are making references, but you never set bibliography and does not have manual references entry in your YAML front matter.

I understand, but as I mentioned in the comment with the video, I've tried this with a fresh file in a folder with no other files at all.

**Comment by mcanouil** [comment]
Well, your video shows a "polluted" environment and only using VSCode Quarto extension buttons, so not the best to highlight your issue.

Could you try using the [troubleshooting guide](https://quarto.org/docs/troubleshooting/index.html) (stack trace, verbose mode, etc.) and using Quarto CLI from the terminal, in a clean workspace?

**Comment by cderv** [comment]
> I had to run quarto via the cli and view the output in a browser.

@amzon-ex I understand that your project works ok in the terminal, and the rendering issue is only in VSCODE  through the menu. What is not clear to me is does it work ok in the VSCODE terminal ?

This is to understand if issue is with the Quarto extension only. 

Thanks
