### ISSUE TITLE
Local render (using preview) of Quarto blog is different from the published end-result

### ISSUE THREAD

**Issue by v-poghosyan** [quarto-dev/quarto-cli#9281]
### Bug description

**Issue**

So far, I've noticed that the published site lacks the left side panel which contains the posts and the navbar styling. On the local everything looks as expected, see screenshots.

**Local vs Published Blog**

![Screenshot 2024-04-05 at 1 30 55 PM](https://github.com/quarto-dev/quarto-cli/assets/30192766/911ff3bf-309f-4805-b362-6d5f2f9ab9da)
![Screenshot 2024-04-05 at 1 31 16 PM](https://github.com/quarto-dev/quarto-cli/assets/30192766/180e865c-3837-4774-89b6-7c6356664fd4)

### Steps to reproduce

No specific steps as I've developed the blog over a course of months, however here are useful links to the repo.

[Blog Repository](https://github.com/v-poghosyan/v-poghosyan.github.io)

[Published Site]()

**Config**

[Quarto YAML file](https://github.com/v-poghosyan/v-poghosyan.github.io/blob/main/_quarto.yml)

[Index YAML](https://github.com/thegilpatrick/Blog/blob/main/index.qmd)

**Styles**

In case it's a custom CSS issue, here are my custom style sheets. Note that the differences are there in either mode (dark/light).

[Dark styles](https://github.com/v-poghosyan/v-poghosyan.github.io/blob/main/theme-dark.scss)

[Light styles](https://github.com/v-poghosyan/v-poghosyan.github.io/blob/main/theme-light.scss) 

### Expected behavior

Styling and layout should be the same in preview mode and published end result.

### Actual behavior

Preview mode and published end result are different. See screenshots.

### Quarto check output

```bash quarto check
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Users/vahrampoghosyan/Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /Users/vahrampoghosyan/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3, spylon-kernel

(/) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
Please don't hide your links behind text especially when the links are not correct.
Also, please do provide a small example, not an entire website.
it seems you are using GitHub Action to publish your website using the default option (see <https://github.com/quarto-dev/quarto-actions/tree/main/setup>), meaning you are using the stable release of Quarto which is as of today `1.4.553`, while your Quarto check output shows `1.3.450`.
Since in 1.4, Bootstrap was updated, it is very likely you need to make some changes in your custom (S)CSS, and of course update your local version.
