### ISSUE TITLE
Using `kableExtra::cell_spec(..., italic = TRUE)` to italicize a cell messed up with PDF table format

### ISSUE THREAD

**Issue by marklhc** [quarto-dev/quarto-cli#9283]
### Bug description

This is something I've noticed since I updated to quarto 1.4 (or around that time), but haven't got the time to document until now. I used the `kableExtra::cell_spec()` function in R to format specific cells in a table, and it had been working fine in quarto 1.3 or before. However, after quarto 1.4, when making specific cells italic using `kableExtra::cell_spec()`, the format is off in PDF output. It seems that for some reason, for markdown tables, if `\em{}` is used (for italics in LaTeX) in one of the cells, the table is rendered differently to LaTeX.

### Steps to reproduce

````qmd
---
format:
  pdf:
    keep-tex: true
---

```{r}
library(kableExtra)
```

```{r}
tbl1 <- head(iris)
tbl1[1, 1] <- cell_spec(tbl1[1, 1], bold = TRUE)
tbl1  # `\\textbf{}` is added
knitr::kable(tbl1) # format is fine
```

```{r}
tbl2 <- head(iris)
tbl2[1, 1] <- cell_spec(tbl2[1, 1], italic = TRUE)
tbl2  # `\\em{}` is added
knitr::kable(tbl2)  # format is off
```
````

The same issue happens when just using markdown tables without `kableExtra`:

````qmd
---
format: pdf
---

First table is fine

| Default | Left | Right | Center |
|---------|:-----|------:|:------:|
| \textbf{12}      | 12   |    12 |   12   |
| 123     | 123  |   123 |  123   |
| 1       | 1    |     1 |   1    |

Second table is off

| Default | Left | Right | Center |
|---------|:-----|------:|:------:|
| \em{12}      | 12   |    12 |   12   |
| 123     | 123  |   123 |  123   |
| 1       | 1    |     1 |   1    |

````

### Expected behavior

The table is aligned properly:

### Actual behavior

Table is off

![image](https://github.com/quarto-dev/quarto-cli/assets/6175332/7785f602-c404-46d1-8712-279081ee2710)

### Your environment

- IDE: VS Code 1.88.0
- OS: Ubuntu 22.04

### Quarto check output

```
Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.03.13
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/markl/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /bin/python3
      Jupyter: 5.7.1
      Kernels: julia-1.9, python3, julia-1.10

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /usr/lib/R
      LibPaths:
        - /home/markl/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Why you would expect that mixing different languages would be fine?
You really should not mix markup languages or at least use raw syntax to tell the tools you are mixing things together.

This being said, I cannot reproduce your issue. The only thing is that the `em` command is escaped thus not rendered.
Also, look at the markdown table syntax.

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
title: "Reproducible example"
format: pdf
execute:
  echo: false
---

## Table 1

```{r}
library(kableExtra)
tbl2 <- head(iris)
tbl2[1, 1] <- cell_spec(tbl2[1, 1], italic = TRUE)
knitr::kable(tbl2, format = "latex")  # format is off
```

## Table 2

```{r}
library(kableExtra)
tbl2 <- head(iris)
tbl2[1, 1] <- cell_spec(tbl2[1, 1], italic = TRUE)
knitr::kable(tbl2)  # format is off
```

## Table 3

| Default              | Left | Right | Center |
|----------------------|:-----|------:|:------:|
| `\em{12}`{=latex}    | 12   |    12 |   12   |
| `\emph{123}`{=latex} | 123  |   123 |  123   |
| 1                    | 1    |     1 |   1    |

````

</td><td>

<img width="485" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/264fe0a7-413e-4c3a-891b-00a88d239c73">

</td></tr>
</table>

**Comment by mcanouil** [comment]
I believe the issue is in `kableExtra`.
I was using `1.3.4`.

I see your output with `1.4.0`.

I am afraid it has nothing to do with Quarto, so please report upstream: https://github.com/haozhu233/kableExtra

**Comment by marklhc** [comment]
Thank you very much, @mcanouil. I used `knitr::kable()` and `kableExtra` because they seem to be an easy way to create tables that can be rendered into different formats (PDF, HTML), without needing to tailor the code for each specific format. It seems that `kableExtra::cell_spec()` uses LaTeX (for PDF output) or HTML (for interactive R or HTML output) for formatting the cells, but then it's knitted into a Markdown table (when not specifying the `format` argument). I'll report to the `kableExtra` author.

**Comment by marklhc** [comment]
Closing this as it is solved. The solution is to use `kableExtra::kbl()` instead of `knitr::kable()`.

**Comment by cderv** [comment]
Just adding some context here: 

**kableExtra** used to set automatically set the `format` for `kable()` when **kableExtra** was loaded. It seems it changed in latest version
https://github.com/haozhu233/kableExtra/blob/a9c509af285bc34b37538d08fdb7e29a76ce71a7/R/zzz.R#L5-L6

Now, this is done directly in kableExtra::kbl (), which is why it solves your issue here. This is really interesting to know !

Without `kbl()`, you would need to set the format explicitly in `kable(..., format = "latex")`. This is because `knitr::kable()` always defaults to `format = "pipe" inside the context where Pandoc will be run. 

 Also in all example above, when trying to insert some raw content, `escape = FALSE` should probably be added. otherwise, `\em{}` will be escaped, and not interpreted as the command in LaTeX.
