### ISSUE TITLE
Collaborative documents

### ISSUE THREAD

**Issue by higgi13425** [quarto-dev/quarto-cli#93]
Feature request:
It would be amazing if quarto could include native collaborative writing tools, with the capabilities of {trackdown} https://github.com/claudiozandonella/trackdown

**Comment by jjallaire** [comment]
Yes that is definitely on the roadmap! (not in precisely that form, but functionally a similar idea). I will close this issue for now since we aren't working on this in the immediate term.

**Comment by drriguz** [comment]
> Yes that is definitely on the roadmap! (not in precisely that form, but functionally a similar idea). I will close this issue for now since we aren't working on this in the immediate term.

@jjallaire Hi, is there any progress on that topic?
