### ISSUE TITLE
Output-dir keeps the subdirectory the quarto file is in

### ISSUE THREAD

**Issue by JT-39** [quarto-dev/quarto-cli#9300]
### Bug description

When setting the _quarto.yml option `output-dir:` to a folder, the function works as expected but if the quarto file being rendered is inside a folder, the quarto output is produced into the output-dir + this original folder.

### Steps to reproduce

```
project:
  title: "test"
  output-dir: "./Outputs/Results"
``` 

### Expected behavior

I have my .qmd file in `./Anlaysis/file_name.qmd`.

I want it to render into `./Outputs/Results/file_name.html`.

### Actual behavior

However, currently is renders the .html output into `./Outputs/Results/Analysis/file_name.html`.

**Comment by mcanouil** [comment]
That's not a bug.
That's the current behaviour:
- https://github.com/quarto-dev/quarto-cli/discussions/2171

**Comment by cscheid** [comment]
I can confirm this is is intended behavior.
