### ISSUE TITLE
Hosting using Github Pages won't render all files

### ISSUE THREAD

**Issue by virajvekaria** [quarto-dev/quarto-cli#9314]
### Bug description

I will be using Quarto for write my blogs on Machine learning and mathematics, which btw is an awesome tool. I will write code and text (using markdown) in jupyter notebooks and render them using quarto. Then I had planned to post them using Github Pages, but it won't show all the files. I have written two blogs but one won't show on the index.html when hosted with Github pages. I viewed the same file locally using my browser and it renders perfectly, I can't find the issue please can someone help me.

### Expected behavior

I expected gh pages to render the website just like when viewing it locally, like the image attached
![image](https://github.com/quarto-dev/quarto-cli/assets/130538599/24e85649-171e-4f7c-8d39-1c826bea92b6)

### Actual behavior

It completely ignores the second blog that I have written (not sure why...), here is the picture attached
![image](https://github.com/quarto-dev/quarto-cli/assets/130538599/358e8fdb-4354-420c-8506-6e3b14cb6281)

**Comment by mcanouil** [comment]
Unfortunately, we can't help if you don't fill properly the issue template, in particular the steps to reproduce, which might contains a repository.

Screenshots won't help us help you investigate a code issue, as there is no code.

Please update your issue report with the required information.

Also, be sure to (re)read the documentation about publishing: https://quarto.org/docs/publishing/index.html

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by virajvekaria** [comment]
I am extremely sorry, it is my first time reporting an issue to quarto, well actually the bug disappeared somehow, I was doing some custom theming and when I pushed the staged changes and let gh pages publish, it rendered all the files. Now that it has disappeared should the issue be closed or should I try reproducing the issue by going back to the corresponding commit?

**Comment by mcanouil** [comment]
> I am extremely sorry

No needs to apologise.

> Now that it has disappeared should the issue be closed or should I try reproducing the issue by going back to the corresponding commit?

If you cannot see the issue any longer, I believe you will be unable to reproduce, so I'm going ahead and close.
