### ISSUE TITLE
Unexecuted code block in code blocks should respected the number to braces like inlines

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#9335]
We document this here: 
https://quarto.org/docs/computations/execution-options.html#unexecuted-blocks

but the example does not show the `{{ python }}` as it should 

Example: 
`````markdown
---
title: "Example"
format: 
   html: default
---

```` markdown
---
title: "A julia engine notebook"
engine: julia
---

```{{{julia}}}
1 + 2
```
````

```{{{julia}}}
1 + 2
```
`````

Results in 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/2083c1f6-3dc0-43e7-a199-d14c195a5784)

Inside the code block, only two braces `{{ }}` should be removed like for inlines. 

it is a regression as it works in 1.3 but not in 1.4 

Results with 1.3.450 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/73132fa2-b8d0-441d-ba10-628b0c4c1bfe)

**Comment by cderv** [comment]
It comes from dae6fbe79770005d6a95d84e4009dd81216cdbb0 where a fix about escaping messed up with this other kind of escaping
* https://github.com/quarto-dev/quarto-cli/pull/8391
* https://github.com/quarto-dev/quarto-cli/issues/8389

So we need a solution that correctly works for inline in code block, and code block in code blocks

**Comment by cscheid** [comment]
This is both a dumb bug and a _really_ hard one to fix. Consider this:

``````````
``````
This here is an inline code element:

````{{julia}} code with a three backticks inside it ``` ````

But how should we detect it?
``````
``````````
