### ISSUE TITLE
Quarto running from VS Code cannot find a jupyter install

### ISSUE THREAD

**Issue by tpoisot** [quarto-dev/quarto-cli#9338]
### Bug description

When running any quarto command from VS Code, it fails because it cannot find jupyter. This is from the VS Code terminal:

~~~
tpoisot@werk:~/Code/JlDash> quarto check jupyter
Quarto 1.5.28
[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter
~~~

But if I run the _same_ command from my usual terminal, it works:

~~~
tpoisot@werk:~/Code/JlDash> quarto check jupyter
Quarto 1.5.28
[✓] Checking Python 3 installation....OK
      Version: 3.11.8
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: julia-1.9, julia-1.10, python3, python3.11

[✓] Checking Jupyter engine render....OK
~~~

### Expected behavior

Running the same command in the system terminal and in the VS Code terminal should give the same result.

### Actual behavior

The VS Code terminal is unable to find the Jupyter kernels that the system terminal can locate.

### Your environment

- IDE: VS Code 1.88.0
- Quarto: 1.5.28
- OS: Linux (OpenSUSE Tumbleweed), kernel 6.8.4

### Quarto check output

the output of `quarto check` *is* the bug here ;-)

**Comment by cderv** [comment]
In your terminal you are using Python 3.11.8 , and in VSCODE you have 3.12.2 

You need to check if those are using virtual environment and if Juoyter is indeed available from 3.12.2. 

In VSCODE, python version used is the one from your Python extension via the python selector

**Comment by tpoisot** [comment]
That does it. Python environments break my heart a little more everyday...

**Comment by mcanouil** [comment]
@tpoisot In VSCode there is a global default setting you can check:

```json
"python.defaultInterpreterPath": "python"
```

<img width="532" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/a308cf33-1659-4d84-8fa4-8386187ce6e3">
