### ISSUE TITLE
`engine: julia` errors  

### ISSUE THREAD

**Issue by dmbates** [quarto-dev/quarto-cli#9344]
### Bug description

I installed pre-release 1.5.29 to try the `engine: julia` facility on a Quarto-based book with Julia code chunks at https://github.com/JuliaMixedModels/EmbraceUncertainty .  See the `db/juliarunner` branch of the repository.  I consistently get errors like
```
Running [37/40] at line 742:  dsm01trace = fit(
Running [38/40] at line 779:  only(dsm01.b)
Running [39/40] at line 803:  caterpillar!(
Running [40/40] at line 818:  qqcaterpillar!(
ERROR: TypeError: output.text.map is not a function

Stack trace:
    at mdOutputStream (file:///Applications/quarto/bin/quarto.js:32951:37)
    at mdFromCodeCell (file:///Applications/quarto/bin/quarto.js:32858:29)
    at jupyterToMarkdown (file:///Applications/quarto/bin/quarto.js:32287:34)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async Object.execute (file:///Applications/quarto/bin/quarto.js:41272:25)
    at async renderExecute (file:///Applications/quarto/bin/quarto.js:77765:27)
    at async renderFileInternal (file:///Applications/quarto/bin/quarto.js:77933:43)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:77801:17)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:78187:25)
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:82777:32)
```
when trying to render a chapter (`intro.qmd` in this case).

I have been trying to create a smaller example illustrating this problem but have been unable to do so.

### Your environment

- IDE: VSCode: version 1.88
- julia> versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 6 default, 0 interactive, 3 GC (on 6 virtual cores)

(@quarto) pkg> st
Status `~/.julia/environments/quarto/Project.toml`
  [4c0109c6] QuartoNotebookRunner v0.9.1

### Quarto check output

```bash
% quarto check
Quarto 1.5.29
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.29
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/dmbates/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.13 (Conda)
      Path: /Users/dmbates/.julia/conda/3/bin/python3
      Jupyter: 5.7.2
      Kernels: julia-1.11, julia-1.10, julia-1.9, julia-1.12, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by dmbates** [comment]
@jkrumbiegel It doesn't appear that the error is coming directly from the QuartoNotebookRunner.jl code but I thought I should ping you in case this has come up for others.

**Comment by cscheid** [comment]
```
ERROR: TypeError: output.text.map is not a function
```

This is a good hint, I believe. For this specific notebook, `output.text` is somehow not an array of strings, which is what `mdOutputStream` expects.

**Comment by cscheid** [comment]
The error is coming from

https://github.com/quarto-dev/quarto-cli/blob/main/src/execute/julia.ts#L164

@jkrumbiegel will be able to say more here, hopefully.

**Comment by jkrumbiegel** [comment]
It looks like the ipynb that QuartoNotebookRunner creates does not match what the quarto code expects in this case. Specifically, quarto looks at some cell output of type `stream` whose field `output.text` is not an array as Carlos mentioned above. To start debugging, I would render the notebook directly with QuartoNotebookRunner into an ipynb file like

```julia
using QuartoNotebookRunner

QuartoNotebookRunner.render(the_qmd_file; output="output.ipynb")
```

And then look at the json data underlying that ipynb file, find the place where an `output.text` of a cell is not an array (I'd guess it's a string as null and undefined give different error messages when you call `.map` on them). Then you'd know which cell is the culprit, and you can reduce your script to just that cell. That should give an MWE.

**Comment by dmbates** [comment]
In the examples I see, `output.text` is always a string, not an array of strings, if I am looking at the right sections.  A simple example is
```json
        {
            "id": "72",
            "cell_type": "code",
            "metadata": {
            },
            "source": [
                "show(only(dsm01.β) .+ [-2, 2] * only(dsm01.stderror))"
            ],
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": "[1492.110894544422, 1562.8891054555756]"
                }
            ],
            "execution_count": 1
        },
```

I do get some Unicode characters in the `stdout` stream when there are warnings.  For example

```json
       {
            "id": "78",
            "cell_type": "code",
            "metadata": {
            },
            "source": [
                "#| code-fold: true\n",
                "#| fig-cap: Caterpillar plot of prediction intervals for dsm01 random effects\n",
                "#| label: fig-caterpillar_dsm01\n",
                "#| warning: false\n",
                "caterpillar!(\n",
                "  Figure(resolution=(800, 250)),\n",
                "  ranefinfo(dsm01, :batch),\n",
                ")"
            ],
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": "\u001b[33m\u001b[1m┌ \u001b[22m\u001b[39m\u001b[33m\u001b[1mWarning: \u001b[22m\u001b[39mFound `resolution` in the theme when creating a `Scene`. The `resolution` keyword for `Scene`s and `Figure`s has been deprecated. Use `Figure(; size = ...` or `Scene(; size = ...)` instead, which better reflects that this is a unitless size and not a pixel resolution. The key could also come from `set_theme!` calls or related theming functions.\n\u001b[33m\u001b[1m└ \u001b[22m\u001b[39m\u001b[90m@ Makie ~/.julia/packages/Makie/ND0gA/src/scenes.jl:220\u001b[39m\n"
                },
```

Would that be a problem?

**Comment by cscheid** [comment]
Looks like it's always a string: https://nbformat.readthedocs.io/en/latest/format_description.html#stream-output

**Comment by cscheid** [comment]
Maybe some formats (maybe even Quarto 😬 ) output a list of strings, but we should try to handle both cases.

@jkrumbiegel I can make a fix here, it looks simple enough. I'll ask for a quick review from you

**Comment by cscheid** [comment]
I have a PR up at #9346, but I'm a little suspicious of what's happening here, and I think it's Quarto's fault. We need to investigate thoroughly.

**Comment by jkrumbiegel** [comment]
Looks like it can be both given the schema file we're using to validate our outputs.

https://github.com/PumasAI/QuartoNotebookRunner.jl/blob/f95ee95e27de27f5f33758d05cffe2ba499e015d/test/schema/nbformat.v4.schema.json#L362

https://github.com/PumasAI/QuartoNotebookRunner.jl/blob/f95ee95e27de27f5f33758d05cffe2ba499e015d/test/schema/nbformat.v4.schema.json#L460-L465

cc @MichaelHatherly
