### ISSUE TITLE
Under the navbar an address bar is coming which is not required & it's not worth it for a blogging web

### ISSUE THREAD

**Issue by ABHI20-STAT** [quarto-dev/quarto-cli#9364]
### Bug description

When I add the sidebar on left side, an unwanted address bar is appearing as per the screenshot
![Screenshot (3)](https://github.com/quarto-dev/quarto-cli/assets/85644282/4487829e-dd90-4df1-be5a-9cc35d5f5617)
![Screenshot (4)](https://github.com/quarto-dev/quarto-cli/assets/85644282/322271fe-28c5-49f1-bb8a-82dc926fd607)
 attached here. 

### Expected behavior

According to a usual blogging website, I want the side bar on the left & the navbar at the top 

### Actual behavior

Under the navbar an address bar is coming which is not required & it's not worth it for a blogging web.  
![Screenshot (3)](https://github.com/quarto-dev/quarto-cli/assets/85644282/ddc3c1b0-2b5e-4724-b3c2-c9d2613e6587)
![Screenshot (4)](https://github.com/quarto-dev/quarto-cli/assets/85644282/3484c8c4-7cb1-478a-a800-c889154e791f)

### Your environment

R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default

locale:
[1] LC_COLLATE=English_India.utf8  LC_CTYPE=English_India.utf8   
[3] LC_MONETARY=English_India.utf8 LC_NUMERIC=C                  
[5] LC_TIME=English_India.utf8    

time zone: Asia/Calcutta
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.3 tools_4.3.3   

### Quarto check output

Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\maths\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.3
      Path: C:/PROGRA~1/R/R-43~1.3
      LibPaths:
        - C:/Users/maths/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.3/library
      knitr: 1.46
      rmarkdown: 2.26

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
If you don't want the bread crumbs, disable it, there are no bugs here.

```yaml
bread-crumbs: false
```
