### ISSUE TITLE
`*cap-location` options does not work well for tables

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#938]
Quarto version: 0.9.414

According to https://quarto.org/docs/authoring/tables.html#caption-location, the following should not happen. in my unterstanding.

Using in yaml header (root): 

- `cap-location: bottom`:
  - figures: bottom => OK
  - tables: bottom => OK
- `cap-location: margin`:
  - figures: margin => OK
  - tables: bottom => __WRONG__ (or unexpected)
- `cap-location: top`:
  - figures: top => OK
  - tables: top => OK
- `tbl-cap-location: bottom`:
  - tables: bottom => OK
- `tbl-cap-location: margin`:
  - tables: bottom => __WRONG__ (or unexpected)
- `tbl-cap-location: top`:
  - tables: bottom => __WRONG__ (or unexpected)

In code cell option: `#| tbl-cap-location: bottom` or `#| tbl-cap-location: margin` have no effect at all in contrast to `fig-cap-location`.

See examples in https://github.com/mcanouil/quarto-tbl-cap-location

**Comment by dragonstyle** [comment]
This should be resolved now, thanks for reporting!
