### ISSUE TITLE
Boolean metadata with value `false`  is not passed onto templates

### ISSUE THREAD

**Issue by gl-eb** [quarto-dev/quarto-cli#9380]
### Bug description

I'm working on a Typst template and have come across an unexpected behaviour.
Unfortunately I don't understand the inner workings of Pandoc and Quarto well enough to determine whether this is expected behaviour and which lines of code it comes from exactly.

### Steps to reproduce

All relevant files can be seen in the develop branch of the following repo: https://github.com/gl-eb/minimal-doc

To reproduce locally:
1. Clone my git repo and switch to the develop branch
```bash
git clone https://github.com/gl-eb/minimal-doc
cd minimal-doc
git switch develop
```
2. Render the example file
```bash
quarto render template.qmd
```

### Expected behavior

The `titleinheader: false` flag is set in the YAML block of [`template.qmd`](https://github.com/gl-eb/minimal-doc/blob/develop/template.qmd). This should result in the document title not being written to the header in the [PDF](https://github.com/gl-eb/minimal-doc/blob/develop/template.pdf).

### Actual behavior

For some reason, the `titleinheader` variable does not make it into the [`template.typ`](https://github.com/gl-eb/minimal-doc/blob/develop/template.typ) file, where it should be written as part of the `#let minimal()` function (line 287). Using quotes (`titleinheader: "false"`) will lead to the expected behaviour. Since the variable is not being set to `false`, the function reverts to the default value of `true`.

The same behaviour is observed with the `toc` variable, that is part of the default Typst template in Quarto. When set to `false` it's not written to the `.typ` file. Since `false` is the default value, it does not matter (and might be by design?).

### Your environment

- IDE: VSCodium 1.88.1
- OS: macOS Sonoma 14.4.1

### Quarto check output

```
Quarto 1.5.29
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.29
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/gleb/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.0 (Conda)
      Path: /Users/gleb/micromamba/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources
      LibPaths:
        - /Users/gleb/Library/R/arm64/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Your template has this:

```
$if(titleinheader)$
  titleinheader: $titleinheader$,
$endif$
```

I don't know what you're expecting to happen with you have an if condition that checks for false in this case, but what's going to happen is that the template is not going to expand because, well, `titleinheader` is `false`.

**Comment by gl-eb** [comment]
My understanding of the [pandoc documentation](https://pandoc.org/MANUAL.html#conditionals) is that Pandoc conditionals on check for a non-empty value, which `false` would be. Or am I misunderstanding?

**Comment by gl-eb** [comment]
In case anyone else stumbles upon this: The pandoc `if` conditional apparently looks for a truthy value. My confusion came from the pandoc documentation that sais "the `if` section is used if variable has a non-empty value" and I did not consider `false` to be empty.

**Comment by cscheid** [comment]
@gl-eb That's a good catch - the Pandoc docs could probably benefit from a PR. Or they might even consider this a bug! (and thus my comment to be completely wrong)
