### ISSUE TITLE
BUG: Additional figure window shown when rendering matplotlib jshtml animation from python code cell

### ISSUE THREAD

**Issue by ndfcampbell** [quarto-dev/quarto-cli#9397]
When rendering a JSHTML animation using the matplotlib package an extra blank figure window is shown. 

This also happens in Jupyter in notebook mode and the solution is to close the extra figure window. 

When this is attempted in quarto, no animation is shown (just the animation controls) which is different to the Jupyter behaviour. 

I think it might be to do with the matplotlib backend being used or the logic to do with capturing the figure output but I'm afraid I have tried a number of things and nothing works - as I say, the plt.close() fix is sufficient for rendering in the Jupyter notebook so this change in behaviour is confusing. 

- Is there a sensible way to do this? 
- I don't think this is expected behaviour and it would be great to be able to show animations!

Many thanks.

### Example script:

````
---
title: "Animation Example"
author: "John Doe"
format: revealjs
---

## Simple JS HTML Animation

- This one creates an extra figure..

```{python}
import matplotlib.pyplot as plt
plt.rcParams["animation.html"] = "jshtml"
import matplotlib.animation
import numpy as np

t = np.linspace(0, 2 * np.pi)
x = np.sin(t)

fig, ax = plt.subplots()
ax.axis([0, 2 * np.pi, -1, 1])
l, = ax.plot([], [])

def animate(i):
    l.set_data(t[:i], x[:i])

matplotlib.animation.FuncAnimation(fig, animate, frames=len(t))
```

## With plt.close()

- This one stops the extra figure in jupyter but removes the whole animation in quarto..

```{python}
import matplotlib.pyplot as plt
plt.rcParams["animation.html"] = "jshtml"
import matplotlib.animation
import numpy as np

t = np.linspace(0, 2 * np.pi)
x = np.sin(t)

fig, ax = plt.subplots()
ax.axis([0, 2 * np.pi, -1, 1])
l, = ax.plot([], [])

def animate(i):
    l.set_data(t[:i], x[:i])

result = matplotlib.animation.FuncAnimation(fig, animate, frames=len(t))
plt.close()

# Show result
result
```
````

### Rendering results:

![quarto_animation_extra_figure_shown](https://github.com/quarto-dev/quarto/assets/2907723/8b30b2df-718b-4e69-91a5-9ab394dcc08d)

![quarto_animation_nothing_shown](https://github.com/quarto-dev/quarto/assets/2907723/e99d33c7-e06f-4f1f-b213-dc67a0252528)

**Comment by cscheid** [comment]
> I think it might be to do with the matplotlib backend being used or the logic to do with capturing the figure output but I'm afraid I have tried a number of things and nothing works - as I say, the plt.close() fix is sufficient for rendering in the Jupyter notebook so this change in behaviour is confusing.

We use `nbclient` for running jupyter notebooks, so there should be no difference in the logic of figure output capture.

The only changes we make are to set some default options:

````py
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = fig_dpi
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
````

**Comment by mcanouil** [comment]
See <https://github.com/quarto-dev/quarto-cli/discussions/6657>.

````qmd
---
title: "Animation Example"
author: "John Doe"
format:
  revealjs:
    auto-stretch: false
---

## Simple JS HTML Animation

- This one creates an extra figure..

```{python}
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

plt.rcParams["animation.html"] = "jshtml"

t = np.linspace(0, 2 * np.pi)
x = np.sin(t)

fig, ax = plt.subplots()
ax.axis([0, 2 * np.pi, -1, 1])
l, = ax.plot([], [])

def animate(i):
    l.set_data(t[:i], x[:i])

anim = FuncAnimation(fig, animate, frames=len(t))
plt.close()
HTML(anim.to_jshtml())
```

````

**Comment by ndfcampbell** [comment]
Brilliant - thanks very much! Sorry - that didn't come up on google. Very kind, much appreciated
