### ISSUE TITLE
Install issue with homebrew

### ISSUE THREAD

**Issue by rmhorne** [quarto-dev/quarto-cli#9401]
### Bug description

When running a fresh install of homebrew, python, jupyter lab, and quarto, quarto fails to detect jupyter, apparently ignoring the jupyter lab install.

### Steps to reproduce

1. Install homebrew as normal (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)")
2. install python: `brew install python`
3. install jupyter lab: `brew install jupyterlab`
4. install quarto: `brew install --cask quarto` (or downlnad from the site, the result is the same)
5. Run `quarto check`

### Expected behavior

Quarto should detect that jupyter lab is installed

### Actual behavior

Quarto fails to detect jupyter. I can run it in a virtual environment through the command line, but the preview functions in virtual studio code return a jupyter not found error

### Your environment

OS: MAC OS 14.4.1 (23E224)

### Quarto check output

Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.03.21
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/rayanhorne/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in .venv. Did you forget to activate it?

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")

**Comment by mcanouil** [comment]
What Quarto needs is not the Jupyter Lab IDE, which is the thing you are installing via homebrew.

Please see <https://quarto.org/docs/computations/python.html#installation>.

I am going ahead and close as there is no bugs here.

**Comment by matthiasbaitsch** [comment]
Have the same problem using a homebrew installed python. When I run

`python3 -m pip install jupyter`

I get the error message 

`error: externally-managed-environment`

which tells to use homebrew to install the package. And to my understanding, the homebrew jupyterlab package includes jupyter.

**Comment by mcanouil** [comment]
The homebrew cask/formula "jupyterlab" is not the same thing as the Python module "jupyter".

It's best to create environments and to install Python modules in it rather than installing them system-wide, especially if the path requires root permission.
This also makes your project more reproducible and portable if you record Python modules.

**Comment by rmhorne** [comment]
To follow up on this thread - 
1) Thanks @mcanouil - your first reply really helped me out!
2) @matthiasbaitsch - how I solved it was to follow the steps that @mcanouil outlined. Create a new environment and install packages there. If you are running Visual Studio Code or some other IDE, make sure you switch it over to use the new environment in the program itself. I was stumped for a few minutes when I thought I was fine launching VS Code after activating the environment on the command line, only to find I had to switch it *with in* the program itself via the MS Python plugin. *sigh* 
3) Along the same lines, make sure you activate your environment before issuing any quarto commands (which, to my shame, I forgot to do a few times).

**Comment by matthiasbaitsch** [comment]
Thanks a lot for the replies!

1. @rmhorne - Since I am programming in Julia, to my understanding, virtual python environments do not solve my problem.

2. @mcanouil - From what I can read in https://formulae.brew.sh/formula/jupyterlab, the homebrew formula jupyterlab actually provides the jupyter package. And it isn't is a quarto issue if the procedure outlined in https://quarto.org/docs/computations/julia.html#jupyter-lab does not work for homebrew python?

**Comment by mcanouil** [comment]
Jupyter Lab is an IDE. Jupyter Lab needs Jupyter but that does not mean it makes it available system-wide and IDEs don't usually expose their internals to users.

**Comment by matthiasbaitsch** [comment]
OK, get it, thanks a lot. Not being able to install jupyter as advised in https://quarto.org/docs/computations/julia.html is due to https://peps.python.org/pep-0668. Creating a venv and activating it in my .zshrc solved it for me.
