### ISSUE TITLE
I believe that nbdev / quarto doesn't fully work with a windows system. 

### ISSUE THREAD

**Issue by ronfan** [quarto-dev/quarto-cli#9409]
### nbdev_install_quarto doesn't seem to work within a windows system.

This is the error code that I received when I attempted nbdev_install_quarto from pip install:

User
```
PS C:\Users\RongFangLi\test> nbdev_new --lib_name test_repo
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\RongFangLi\anaconda3\Scripts\nbdev_new.exe\__main__.py", line
 4, in <module>
  File "C:\Users\RongFangLi\anaconda3\Lib\site-packages\nbdev\cli.py", line 13
, in <module>
    from .quarto import nbdev_readme, refresh_quarto_yml
  File "C:\Users\RongFangLi\anaconda3\Lib\site-packages\nbdev\quarto.py", line
 6, in <module>
    from os import system, uname
ImportError: cannot import name 'uname' from 'os' (C:\Users\RongFangLi\anacond
a3\Lib\os.py)
```

### Steps to reproduce

Follow this guide on a windows 10 system:
https://nbdev.fast.ai/getting_started.html 

### Expected behavior

No error

### Actual behavior

Error code above

### Your environment

Windows 10 system on a standard i7 Lenovo laptop

### Quarto check output

There was no other output other than the error message above. I believe it is simply a issue because the package is produced with Linux and Mac system in mind.

**Comment by mcanouil** [comment]
@ronfan Please edit the title of your report and your report itself to be meaningful and useful.
Also, please fill the different section properly.

Currently, we cannot use or help you with the current state of your report.
Thank you for your understanding and for providing all the informations requested in the issue template.

**Comment by ronfan** [comment]
> @ronfan Please edit the title of your report and your report itself to be meaningful and useful. Also, please fill the different section properly and use the formatting tools provided by GitHub to make it legible, _e.g._, use code blocks for code.
> 
> Currently, we cannot use or help you with the current state of your report. Thank you for your understanding and for providing all the informations requested in the issue template.

Hi apologies this is now updated.

**Comment by ronfan** [comment]
Right, apologies for the time wasted.
