### ISSUE TITLE
IS there a way to diagnose why body-footer is going in above the blog list?

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#941]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/939

<div type='discussions-op-text'>

<sup>Originally posted by **ggirton** May 19, 2022</sup>
I have made the _quarto yaml that looks like this, for a blog

project:
  type: website

website:
  title: "mvpblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  body-footer: |
        ---   all photos Copyright &copy; 2022 MeMeMe all rights reserved

format:
  html:
    theme: cosmo
    css: styles.css

Then, the stock index.qmd, like this:

---
title: "mvpblog"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---

The result is that the body footer comes out ABOVE the blog entries in the listing (not after them, as I sort of expected).
I know there must be a way for me to set up logging so I can see where in the process my specification of the body footer is going awry.  It's even possible that I'm doing everythnig right and there is a bug!  (note from me: this has pretty much never happened before, though).

What I lack is an understanding of how to turn on dedbugging instrumentation, so I can get the dedbugs ded.  I mean, debugging, but you know what I mean.  Does it think it is doing what I think it should be doing, etc. etct.

Thank you, TIA!
</div>

**Comment by dragonstyle** [comment]
This was caused by a bug (fixed here: b5c0e9e7f7632546384e21d226595190d9cdd10a). A fresh release is being built now.

One other note - you may want to also check out `page-footer:` if you haven't, which will be more opinionated about centering and appearing at the bottom of your page (rather than flush up against the bottom of your content).

Thanks for reporting this!
