### ISSUE TITLE
Python jupyter kernel error

### ISSUE THREAD

**Issue by zcline91** [quarto-dev/quarto-cli#942]
While trying to compile any file using a python jupyter kernel, the CLI returns a kernel error.

Example file `hello.qmd`:
```
---
title: "Hello world"
format:
  html:
    code-fold: true
jupyter:
  python3
---

This is a test file.
```

Output from the command `quarto render hello.qmd --to html --log-level info`:
```
Starting python3 kernel...ERROR: 

Kernel died before replying to kernel_info
```
.ipynb files run fine on jupyterlab on the same PC, and compiling .qmd files with the R kernel `ir` with jupyter doesn't produce any errors, so I'm not sure what the issue is.

**Comment by jjallaire** [comment]
If you add the `--execute-debug` flag you'll get a bit more in the way of diagnostics:

```bash
quarto render hello.qmd --to html --execute-debug
```

**Comment by jjallaire** [comment]
I would google for that error message and see what you come up with, eg.

- https://github.com/jupyter/jupyter_client/issues/499
- https://stackoverflow.com/questions/51588840/jupyter-kernel-dies-from-nbconvert-but-not-on-jupyter

**Comment by zcline91** [comment]
Thank you very much for the help and patience with a newbie! For anybody else who ever runs into this issue, be sure to include the `--user` flag when initially installing ipykernel: 
```
python -m ipykernel install --user
```
On a separate note, thank you for your significant contributions to open source software!

**Comment by cmaerzluft** [comment]
I just bumped into this issue and updating ipykernel didn't help nor did any of the other solutions I was able to find after extensive googling. Sharing my solution in case anyone else has the same issue I did.

I have an M1 Mac (2021) running Monterey 12.6 and ultimately, the issue for me came from psutil. While running quarto with `--execute-debug` didn't give me any information, running 
```
quarto check
```
gave a much more detailed output; including the following output:
```
ImportError: dlopen(/Users/user/Library/Python/3.9/lib/python/site-packages/psutil/_psutil_osx.cpython-39-darwin.so, 0x0002): tried: '/Users/user/Library/Python/3.9/lib/python/site-packages/psutil/_psutil_osx.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
2022-10-20 16:29:45,563 - traitlets - ERROR - Error occurred while starting new kernel client for kernel d9b133d0-0120-4c08-a630-a947b162ae08: Kernel died before replying to kernel_info
```
which lead me to this [stackoverflow](https://stackoverflow.com/questions/72619143/unable-to-import-psutil-on-m1-mac-with-miniforge-mach-o-file-but-is-an-incomp). Based on the solution there I ran:
```
pip uninstall psutil
pip install --no-binary :all: psutil
```
Everything started working after that.

**Comment by benz0li** [comment]
I experience the same issue with my current deployment (Julia 1.8.5, image `glcr.b-data.ch/jupyterlab/julia/pubtools:1.8.5`) at https://demo.jupyter.b-data.ch.  
ℹ️ When executing `quarto preview /path/to/file.qmd --no-browser --no-watch-inputs --no-execute-daemon`, rendering succeeds.

Related to https://github.com/quarto-dev/quarto-cli/issues/2539 as I could reproduce this issue with Julia 1.8.4 (image `glcr.b-data.ch/jupyterlab/julia/pubtools:1.8.4`).

This issue does not occur with Julia versions ≤ 1.8.3 (image `glcr.b-data.ch/jupyterlab/julia/pubtools:1.8.3`).

**Comment by cderv** [comment]
@benz0li can you open a new issue with relevant information to reproduce ? 

This one is quite old now, and it is better to track new issue (here new because ok with 1.8.3 but not with 1.8.4) in their own thread. thank you !

**Comment by PavoDive** [comment]
In my case

```
pip uninstall ipykernel
pip install ipykernel
```

Solved the problem

**Comment by xjlc** [comment]
In my case the following helped: 
`conda install executing `
