### ISSUE TITLE
jupyter asis output reordering text and plots

### ISSUE THREAD

**Issue by bhogan-mitre** [quarto-dev/quarto-cli#9422]
### Bug description

I'm trying to programmatically generate section headers and plots, and running into an issue where all plots get lumped together at the end of the code chunk's output.  This seems like a bug in the rendering process, or at least something that should be able to be changed with a configuration option.

Example modified from https://matplotlib.org/3.5.3/gallery/lines_bars_and_markers/categorical_variables.html#sphx-glr-gallery-lines-bars-and-markers-categorical-variables-py 

````
```{python}
#| label: multiple-plots-subsections
#| output: asis

print("### Bar")

plt.bar(names, values)
plt.show(block=False)

print("### Scatter")

plt.scatter(names, values)
plt.show(block=False)

print("### Line")

plt.plot(names, values)
plt.show(block=False)
```
````

Generates: 

![Screenshot 2024-04-19 at 9 56 14 AM](https://github.com/quarto-dev/quarto-cli/assets/32336739/92758883-b220-434c-a012-9619c35a06d7)

### Steps to reproduce

````
---
title: "Generate Plots within Sub-Sections"
format:
  html:
    echo: false
    embed-resources: true
engine: jupyter
---

```{python}
#| label: setup
import matplotlib.pyplot as plt
```

```{python}
#| label: define-data

data = {'apple': 10, 'orange': 15, 'lemon': 5, 'lime': 20}
names = list(data.keys())
values = list(data.values())
```

## Plots and Subsections

```{python}
#| label: multiple-plots-subsections
#| output: asis

print("### Bar")

plt.bar(names, values)
plt.show(block=False)

print("### Scatter")

plt.scatter(names, values)
plt.show(block=False)

print("### Line")

plt.plot(names, values)
plt.show(block=False)
```

````

### Expected behavior

The rendered output of the code chunk should be: header, plot, header, plot, header, plot.

### Actual behavior

The rendered output of the code chunk is: header, header, header, plot, plot, plot.

### Your environment

- IDE: VS Code 1.78.2
- OS: Windows Server 2016

### Quarto check output

```
$ quarto check
Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.11
      Path: C:/WPy64-310111/python-3.10.11.amd64/python.exe
      Jupyter: 5.3.0
      Kernels: octave, python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.2
      Path: C:/PROGRA~1/R/R-4.2.2
      LibPaths:
        - C:/Program Files/R/R-4.2.2/library
      knitr: 1.43
      rmarkdown: 2.22

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
That's not a bug - it happens because `plt.show(block=False)` produces output in a different way from the stream outputs, and it's impossible for Quarto to tell the order based on the information in the executed notebook. You'll need to split those into different cells.

**Comment by bhogan-mitre** [comment]
@cscheid  is it an issue with the lua processing?  I'd be interested to learn more about where this breaks down.  If I `keep-ipynb`, the generated notebook has things in the expected order.  But yet a `quarto convert` on that ipynb file ends up looking like the original html.

![Screenshot 2024-04-19 at 3 25 18 PM](https://github.com/quarto-dev/quarto-cli/assets/32336739/78de84ed-79cb-423f-aeff-1aedea7b4ad4)

**Comment by cscheid** [comment]
> @cscheid is it an issue with the lua processing?

No, it's not an issue with Lua processing.

**Comment by cscheid** [comment]
Thanks for following up. Update: I was wrong.

> That's not a bug - it happens because plt.show(block=False) produces output in a different way from the stream outputs, and it's impossible for Quarto to tell the order based on the information in the executed notebook. You'll need to split those into different cells.

It's not a Lua issue. "plt.show(block=False) produces output in a different way from the stream outputs" is true, but what comes next, "it's impossible for Quarto ..." is not.

> But yet a `quarto convert` on that ipynb file ends up looking like the original html.

We have an explicit step that merges the stream outputs from the rendered .ipynb that is not invoked in the .qmd path. The output of the execution of your notebook cell looks like this:

```json
[
  {
    "name": "stdout",
    "output_type": "stream",
    "text": ["### Bar\n"]
  },
  {
    "data": {
      "image/png": "...",
      "text/plain": ["<Figure size 672x480 with 1 Axes>"]
    },
    "metadata": {
      "image/png": {
        "height": 411,
        "width": 579
      }
    },
    "output_type": "display_data"
  },
  {
    "name": "stdout",
    "output_type": "stream",
    "text": ["### Scatter\n"]
  },
  {
    "data": {
      "image/png": "...",
      "text/plain": ["<Figure size 672x480 with 1 Axes>"]
    },
    "metadata": {
      "image/png": {
        "height": 411,
        "width": 566
      }
    },
    "output_type": "display_data"
  },
  {
    "name": "stdout",
    "output_type": "stream",
    "text": ["### Line\n"]
  },
  {
    "data": {
      "image/png": "...",
      "text/plain": ["<Figure size 672x480 with 1 Axes>"]
    },
    "metadata": {
      "image/png": {
        "height": 411,
        "width": 566
      }
    },
    "output_type": "display_data"
  }
]
```

Note the interspersed outputs of `"output_type": "stream"` and `"output_type": "display_data"`.

I incorrectly remembered the output format of jupyter as providing the `stream` outputs in a separate list from the `display_data` outputs, which would make reassembling the order incorrect. But your `quarto convert` comment implies that the original order is still preserved somewhere (and it is).

The problem is that our stream merging algorithm coalesces stream outputs even if they have other data in between them. When stream outputs are used to provide error messages, this is at best inconvenient. But stream outputs are used for markdown generation in `output: asis`, so we need to not merge those stream if at all possible in those cases.

**Comment by bhogan-mitre** [comment]
Thanks for looking into it.  If I use proper `display(Markdown())` instead of `print()` I get a list of all `display_data` outputs without the `stream` outputs in the rendered .ipynb.  That would at least help have things in the correct order.

![Screenshot 2024-04-19 at 4 22 31 PM](https://github.com/quarto-dev/quarto-cli/assets/32336739/6fcf2f59-50e0-4aab-bb73-735805a36a2d)

**Comment by bhogan-mitre** [comment]
The html output in that case is in the correct order... but is only grabbing the header from the first `display_data` object.


![Screenshot 2024-04-19 at 4 29 32 PM](https://github.com/quarto-dev/quarto-cli/assets/32336739/e64d8bb5-138f-4b7d-9129-e8d237742550)


Updated reprex

````
---
title: "Generate Plots within Sub-Sections"
date: last-modified
format:
  html:
    echo: false
    warning: false
    message: false
    embed-resources: true
    toc: true
    toc-title: "Outline"
    toc-depth: 4
    format-links: false
engine: jupyter
execute:
  keep-ipynb: true
---

```{python}
#| label: setup
import matplotlib.pyplot as plt
from IPython.display import display, Markdown
```

Example modified from <https://matplotlib.org/3.5.3/gallery/lines_bars_and_markers/categorical_variables.html#sphx-glr-gallery-lines-bars-and-markers-categorical-variables-py>

```{python}
#| label: define-data

data = {'apple': 10, 'orange': 15, 'lemon': 5, 'lime': 20}
names = list(data.keys())
values = list(data.values())
```

## Plots and Subsections

```{python}
#| label: multiple-plots-subsections
#| output: asis

display(Markdown("### Bar"))

plt.bar(names, values)
plt.show(block=False)

display(Markdown("### Scatter"))

plt.scatter(names, values)
plt.show(block=False)

display(Markdown("### Line"))

plt.plot(names, values)
plt.show(block=False)
```

````

**Comment by cscheid** [comment]
If you add `keep-md: true`, you'll see that the headers are there, they're just being rendered incorrectly because of missing line breaks. (you can see the `### Scatter` text next to your chart)

**Comment by cscheid** [comment]
I can confirm that the issue here is our stream merging. At the same time, we can't disable it, because it was introduced to fix https://github.com/quarto-dev/quarto-cli/issues/4968. I need to improve the algorithm.

**Comment by bhogan-mitre** [comment]
Got it, thanks for explaining what is happening here!  Maybe there is a way to merge the `stream` outputs without merging the `display_data` outputs.  Probably easier said than done, but I appreciate you taking a look.

**Comment by cscheid** [comment]
PR incoming, but note that you'll still need to change your code slightly to include additional line breaks:


````
```{python}
#| output: asis

print("\n### Bar\n")

plt.bar(names, values)
plt.show(block=False)

print("\n### Scatter\n")

plt.scatter(names, values)
plt.show(block=False)

print("\n### Line\n")

plt.plot(names, values)
plt.show(block=False)
```
````

**Comment by bhogan-mitre** [comment]
Thanks @cscheid!  Would that still work if you're using `Markdown()` instead of `print()`?  Either way, I'd be happy to have a workaround with `print` and line breaks.

```{python}
#| label: multiple-plots-subsections
#| output: asis

display(Markdown("### Bar"))

plt.bar(names, values)
plt.show(block=False)

display(Markdown("### Scatter"))

plt.scatter(names, values)
plt.show(block=False)

display(Markdown("### Line"))

plt.plot(names, values)
plt.show(block=False)
```

**Comment by cscheid** [comment]
With `display(Markdown())` you shouldn't use `output: asis`

````
```{python}
#| label: multiple-plots-subsections
from IPython.display import Markdown

display(Markdown("### Bar"))

plt.bar(names, values)
plt.show(block=False)

display(Markdown("### Scatter"))

plt.scatter(names, values)
plt.show(block=False)

display(Markdown("### Line"))

plt.plot(names, values)
plt.show(block=False)
```
````

This works on `main` for me.

**Comment by bhogan-mitre** [comment]
Good to know, thank you!  Would you expect that to show in the table of contents as well?  I'm running with `toc-depth: 4` in this case, and it doesn't include the level 3 headers.  Aside from the TOC it looks great though.

![Screenshot 2024-04-19 at 5 26 14 PM](https://github.com/quarto-dev/quarto-cli/assets/32336739/fef79409-e01c-4a5f-906b-a6b916249ee3)

**Comment by cscheid** [comment]
You're seeing a separate bug (I can't find the link on github at the time). Look at the output of `keep-md: true` and you'll find an enclosing div even if `output: asis`. That div means that the headings won't be at the top level of the document, and so not part of the TOC.
