### ISSUE TITLE
Get started links are broken

### ISSUE THREAD

**Issue by gcgbarbosa** [quarto-dev/quarto-cli#9424]
### What would you like to do?

Report an issue on quarto.org

### Description

Links on the top-left panel are broken on this page: https://quarto.org/docs/get-started/

**Comment by mcanouil** [comment]
@gcgbarbosa is it a mistake? If not, please be accurate on the links you are reporting being broken.

**Comment by cscheid** [comment]
They're totally broken

**Comment by cscheid** [comment]
@gcgbarbosa (Small world! 👋)

**Comment by cscheid** [comment]
There's something _very weird_ going on with our redirections from `/` paths. I wonder if it's something from the upstream provider.

**Comment by mcanouil** [comment]
There is a custom JavaScript to tweak the links on those pages if I am mistaken.

**Comment by cscheid** [comment]
Yes, I see that now

the redirection I was getting was to a `jupyterlab.html` page, which I don't understand how it could have gotten there.

**Comment by cscheid** [comment]
Ahhh it's a nasty bug on our webpage. We're using localStorage for two different things, and if someone happened to visit the manuscripts page and chose the jupyterlab tools, then we automatically redirect to the wrong one in the get started page.

**Comment by cscheid** [comment]
@cwickham The problem is in the two different `_redirect.html` files, in `docs/manuscripts` and `docs/get-started`. The two files share the `tutorialTool` key but each directory expects a different set of tools.

**Comment by cscheid** [comment]
(I'm going to add a temporary workaround to unbreak the live page but this needs a proper cleaning up.)
