### ISSUE TITLE
rendering into Github flavoured markdown

### ISSUE THREAD

**Issue by martinscripts** [quarto-dev/quarto-cli#9457]
Hey all, 

I am trying to render with 

```
format:
    gfm:
        html-math-method: plain
```

but I don't get correct cross references in the resulting .md file. 

this figure `![model schema, based on @iec61970-3022023](drawings/GovCT2.drawio.svg){#fig-modelSchema}`

is turned into this `![](drawings/GovCT2.drawio.svg)`.

Cross references don't seem to lead anywhere.

I get this error: 

```
WARNING (C:\Users\mfranke\AppData\Local\Programs\Quarto\share\filters\main.lua:20141) 
Emitting a placeholder FloatRefTarget
Output format commonmark does not currently support FloatRefTarget nodes.
```

Does anyone have a workaround? 

(context: I want to add an .md file to an already existing github page, based on a quarto .qmd file with references and citations.)

**Comment by mcanouil** [comment]
Could you share a small **self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by martinscripts** [comment]
Hey @mcanouil, thank you.

Sure, here is an MWE: 

**mwe.qmd:**
```
---
title: "The Title"
format: gfm
---

# The Heading

| Pet type | Rating |
| -------- | ------ |
| Dog      | 4/5    |
| Cat      | 4/5    |
| Horse    | 3/5    |
| Ant      | 5/5    |
: Rating of pets {#tbl-pets_rating}

See @tbl-pets_rating
```

When rendering this using vscode (it runs `quarto render d:/[...path to file...]/mwe.qmd --to gfm
pandoc`), I get this .md file:
 
**mwe.md:**
```
# The Title


# The Heading

| Pet type | Rating |
|----------|--------|
| Dog      | 4/5    |
| Cat      | 4/5    |
| Horse    | 3/5    |
| Ant      | 5/5    |

See <a href="#tbl-pets_rating" class="quarto-xref">Table 1</a>

```

## Quarto Check

```
Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: C:\Users\mfranke\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\mfranke\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.11
      Path: d:/User/mfranke/documents/projects/colib/.venv/Scripts/python.exe
      Jupyter: 5.7.1
      Kernels: python3, .venv, py_venv, venv

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\mfranke\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\mfranke\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
There is an unactivated Python environment in .venv. Did you forget to activate it?

[>] Checking Jupyter engine render....OK
```

**Comment by mcanouil** [comment]
Thanks, I can reproduce. The message seems pretty clear.
The new cross-reference system from Quarto 1.3 is not fully supported for gfm:

> Emitting a placeholder FloatRefTarget
> Output format commonmark does not currently support FloatRefTarget nodes.

Note the above is not an error, it's a warning.

In your original post, you said:

> but I don't get correct cross references in the resulting .md file.

What do you mean by "correct" here?

I am not aware of CommonMark or GitHub Flavoured Markdown to support links to markdown content, so I don't see how you would have working links.

Here, I think the HTML code should not be emitted for markdown based format.
Beside this HTML piece, the output follows GFM/CommonMark specifications.

**Comment by martinscripts** [comment]
Thanks for checking. 
By correct cross reference I mean that the *Table 1* referenced in 
`See <a href="#tbl-pets_rating" class="quarto-xref">Table 1</a>`
should exist.  There is no table heading nor numbering. 
My expected behaviour would be: 

```
# The Title


# The Heading

**Table 1: Rating of Pets**

| Pet type | Rating |
|----------|--------|
| Dog      | 4/5    |
| Cat      | 4/5    |
| Horse    | 3/5    |
| Ant      | 5/5    |

See <a href="#tbl-pets_rating" class="quarto-xref">Table 1</a>
```

Does that make sense? 

What do you mean by 
> the HTML code should not be emitted for markdown based format.

?

**Comment by cscheid** [comment]
> My expected behaviour would be:

````
# The Title

# The Heading

**Table 1: Rating of Pets**

| Pet type | Rating |
|----------|--------|
| Dog      | 4/5    |
| Cat      | 4/5    |
| Horse    | 3/5    |
| Ant      | 5/5    |

See <a href="#tbl-pets_rating" class="quarto-xref">Table 1</a>
````

That output wouldn't be correct either, because `#tbl-pets_rating` does not exist anywhere in the output.

I think the output Quarto should be emitting is something like:

````
# The Title

# The Heading

**Table 1: Rating of Pets**

<div id="tbl-pets_rating">

| Pet type | Rating |
|----------|--------|
| Dog      | 4/5    |
| Cat      | 4/5    |
| Horse    | 3/5    |
| Ant      | 5/5    |

</div>

See <a href="#tbl-pets_rating" class="quarto-xref">Table 1</a>
````

I think GFM allows divs in that way.

**Comment by mcanouil** [comment]
> I think GFM allows divs in that way.

GFM does but not sure for CommonMark which I think follow nearly the same code path.
See "HTML blocks" of <https://github.github.com/gfm/>.

**Comment by martinscripts** [comment]
thanks! 💐

**Comment by martinscripts** [comment]
Hey @cscheid, an update regarding the table and figures behaviour: 

With the new updates, it renders into 

```
<div id="tbl-pets_rating">

Table 1: Rating of Pets

| Pet type | Rating |
|----------|--------|
| Dog      | 4/5    |
| Cat      | 4/5    |
| Horse    | 3/5    |
| Ant      | 5/5    |

</div>
```

It turns out that the table does not get rendered properly by github pages if it is inside the div.
It does work, though, if I manually correct it like this: 


```
<div id="tbl-pets_rating">

Table 1: Rating of Pets

</div>

| Pet type | Rating |
|----------|--------|
| Dog      | 4/5    |
| Cat      | 4/5    |
| Horse    | 3/5    |
| Ant      | 5/5    |

```

same thing with figures: 

This does not work:

```
<div id="fig-frequencyDependentLimit">

![](drawings/some_image.svg)

Figure 1: Frequency dependent valve limit as described in [1]

</div>
```

but this does: 

```
![](drawings/some_image.svg)

<div id="fig-someimage">

Figure 1: Some image

</div>
```

**Comment by martinscripts** [comment]
Hey @cscheid, sure. 
It works when rendering a github readme, but apparently it is different when rendering into github pages. 
I am contributing to a github pages website, built out of markdown files. Locally I test things using [jekyll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll). For some reason the  table is not rendered (but displayed raw) if the div encloses it. 
Although I can see that the reason for this may be at many places.

**Comment by cscheid** [comment]
> I am contributing to a github pages website, built out of markdown files. Locally I test things using [jekyll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll).

Ok. That's not what `gfm` is for. GFM is for "user content on GitHub.com and GitHub enterprise": https://github.github.com/gfm/ Note that there's no mention of Jekyll of GitHub pages on that. So this is not a bug, it's just not something you're supposed to be doing (or, which we don't offer support for).

**Comment by martinscripts** [comment]
Alright! I also just found out that pages renders things slightly differently (using jekyll), until now I thought that it should be fully compatible with GFM, since it is made from .md files and it mostly supports the format, but unfortunately it isn't. 

Thanks for your support here and generally for the development work.
