### ISSUE TITLE
invisible links of subgraphs in mermaid

### ISSUE THREAD

**Issue by tbugfinder** [quarto-dev/quarto-cli#9461]
### Bug description

Use of invisible links when combining subgraphs ends up in "undefined".

### Steps to reproduce

```{mermaid}

graph TD;

    subgraph s1
        direction LR
        A --> B
    end

    subgraph s2
        direction LR
        C --> D
    end

s1 ~~~ s2
```

### Expected behavior

Subgraphs are ordered but no link displayed.

### Actual behavior

output undefined

### Your environment

- IDE: VScode
- quarto on Windows 1.4.553

### Quarto check output

quarto check
Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: c:\tools\quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.0
      Path: C:/Program Files/Python312/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.2.2
      Path: C:/PROGRA~1/R/R-42~1.2
      LibPaths:
        - C:/Users/Documents/R/4.2.2
        - C:/Program Files/R/R-4.2.2/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")

**Comment by mcanouil** [comment]
Mermaid.live does not display any link either, why would you expect one to be displayed in Quarto?
<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/1d983dd4-bac9-4efb-91ed-eeaf5657ea29">

**Comment by tbugfinder** [comment]
Indeed the output should not show a visible link.
Within my environment output ends up in "undefined". 

My version is 1.4.x, not 1.5 preview.

**Comment by tbugfinder** [comment]
I've updated to 1.5 pre-release.
VSCode shows this undefined within the preview if ~~~ is used.:

![image](https://github.com/quarto-dev/quarto-cli/assets/15378237/1fbc35a2-6f5d-4847-b13f-12649211e3dd)

**Comment by mcanouil** [comment]
Could you share the steps to reproduce this?

**Comment by tbugfinder** [comment]
Hello,

not sure if an update is still possible, however I noticed the difference.
I have two options within VSCode:

a) Command Palette -> Quarto: Preview Diagram => that one ends up in displaying undefined.
b) click on the "Quarto Preview" option at the top right of the editor window => this properly executes quarto preview on localhost

The issue within a) only applies if ~~~ is being used, though. All other previews are displayed properly.

Quarto extension v1.111.0 is installed.


Thanks

**Comment by cderv** [comment]
> /reopen

What did you mean by that ? You can just ask for the issue to be reopen or just wait a bit more than 1 day so that we read you previous post and answer. 

> I've updated to 1.5 pre-release. VSCode shows this undefined within the preview if ~~~ is used.:
> 
> ![image](https://private-user-images.githubusercontent.com/15378237/325123351-1fbc35a2-6f5d-4847-b13f-12649211e3dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODMxMjEsIm5iZiI6MTcxNjg4MjgyMSwicGF0aCI6Ii8xNTM3ODIzNy8zMjUxMjMzNTEtMWZiYzM1YTItNmY1ZC00ODQ3LWIxM2YtMTI2NDkyMTFlM2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA3NTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZmFiMjI4NTJiNjM5OTU4NGVhOGE0NGM0ZGJmNjI1ZGVmMWI5NmUzNjc1MjU2NGFmZDBjYWJjNDhiMzM4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cpXV5Gm606N6q7e4uh9qOTxlT2zmqxCl87tZOWRR5ck)
> 
> I'll have to investigate further, then.
> 
> Using `quarto preview` command the output renders properly. Seems to be an issue with VSCode layer (sort of).

This seems to be the issue you are reported. It seem the "Quarto: Preview Diagram" command does not correctly handle this syntax, or is just broken. 

I'll create an issue from your last comment.
