### ISSUE TITLE
Figure sizing according to the manual does not work.

### ISSUE THREAD

**Issue by piiskop** [quarto-dev/quarto-cli#9465]
### Bug description

Figure sizing according to the manual does not work.

### Steps to reproduce

````qmd
---
author:
  - name: 'peacecop kalmer:'
title: Erialapraktika aruanne
institute: Tallinna Ülikool
date: 2024-04-29

link-citations: yes

output-file: presentation.html
format:
  revealjs:
    incremental: false
    self-contained: true
    theme: [../olis.scss]
    slide-number: true
    logo: ../logos.svg

---

## Probleemne ülesanne

![Mis on konverteerimises meetrist sekundi kohta miilideks tunni kohta valesti?](../IMG_20231020_111150.jpg){width=100}

````

![IMG_20231020_111150](https://github.com/quarto-dev/quarto-cli/assets/14224528/16c4dec5-43dc-4f34-b024-0be559a158a4)
![logos](https://github.com/quarto-dev/quarto-cli/assets/14224528/9bcebdf9-7671-467b-be8c-5cc56ce1e82e)

Whatever I put as the value of "width", it has no influence. I have also experiencing with "height" and it also remains the same.

### Expected behavior

Setting the width or height works as directed in the manual.

### Actual behavior

Setting the width or height according to the manual has no effect.

### Your environment

- IDE: RStudio Server
2023.03.3 Build 539

- OS: Ubuntu 22.04.4 LTS

### Quarto check output

> [✓] Checking Quarto installation......OK
>       Version: 1.2.475
>       Path: /usr/lib/rstudio-server/bin/quarto/bin
> 
> [✓] Checking basic markdown render....OK
> 
> [✓] Checking Python 3 installation....OK
>       Version: 3.10.12
>       Path: /usr/bin/python3
>       Jupyter: (None)
> 
>       Jupyter is not available in this Python installation.
>       Install with python3 -m pip install jupyter
> 
> [✓] Checking R installation...........OK
>       Version: 4.3.3
>       Path: /usr/lib/R
>       LibPaths:
>         - /home/kalmer/R/x86_64-pc-linux-gnu-library/4.3
>         - /usr/local/lib/R/site-library
>         - /usr/lib/R/site-library
>         - /usr/lib/R/library
>       rmarkdown: 2.25
> 
> [✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Unfortunately your example is not reproducible or self-contained, i.e., we don't have your files.

Additionally, you are running a quite old version of Quarto. Please consider upgrading your to 1.4.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by piiskop** [comment]
What files do you miss and how is my example not usable? I used four backticks.

I upgraded _Quarto_ and the result is the same.

```
Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /usr/lib/R
      LibPaths:
        - /home/kalmer/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
We don't have `olis.scss`, `logos.svg`, and `IMG_20231020_111150.jpg`.
