### ISSUE TITLE
Automatic footnote identifier prefixing normalizes filenames imperfectly

### ISSUE THREAD

**Issue by salim-b** [quarto-dev/quarto-cli#9475]
### Bug description

RStudio’s Markdown [canonicalization](https://quarto.org/docs/visual-editor/markdown.html#canonical-mode), which is provided [by Quarto](https://github.com/quarto-dev/quarto/blob/f9edec34e53817e9c9f73cb349f524a82bcc6474/packages/editor/src/editor/editor.ts#L771-L791), adds a normalized version of the edited file's name as footnote (and other) identifiers via Pandoc's [`--id-prefix`](https://pandoc.org/MANUAL.html#option--id-prefix) CLI argument. This is a good thing, in principle.

But the filename normalization is very imperfect, I recently discovered. It should be extended to also normalize (i.e. remove) the special characters it currently doesn't touch. See below for an example (note that it is by no means exhaustive, I just typed special characters until I lost interest).

### Steps to reproduce

1. Create a text file named `such.a <[{(weird)}]>|@#§°\&%$£:;*+"´`'~=filename - – — RIGHT?!.md` (this is a totally valid filename on Linux).

1. Paste some Markdown content including at least one footnote in it.

1. Open the file in RStudio and click on <kbd>Visual</kbd> editor mode, then switch back to <kbd>Source</kbd> editor mode and look at the first footnote identifier.

### Expected behavior

Quarto should normalize the above filename to the (footnote) ID prefix:

```
[^such.a-weirdfilename-----right-1]
```

### Actual behavior

Quarto actually normalizes the above filename to the (footnote) ID prefix:

```
[^such.a-(weird§°£´filename---–-—-right-1]
```

### Your environment

- IDE: 2023.12.1+402
- OS: Ubuntu 22.04

### Quarto check output

```
Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /home/salim/.local/bin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /usr/lib/R
      LibPaths:
        - /home/salim/.software/managed/r
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
The Visual Editor repository is <https://github.com/quarto-dev/quarto>.

Footnotes as far as I know comes directly from Pandoc which is also the main tool used for the Visual Editor.

**Comment by salim-b** [comment]
Ouch, I totally missed the different repos 🙈. I've opened https://github.com/quarto-dev/quarto/issues/424.

**Comment by mcanouil** [comment]
I suggest to try your example using Pandoc before opening an issue.

```sh
quarto pandoc reprex.md --from markdown --to html 
```

**Comment by salim-b** [comment]
> It feels here that you are discussing an issue with Pandoc itself.

Nope.

> I suggest to try your example using Pandoc before opening an issue.
> 
> ```shell
> quarto pandoc reprex.md --from markdown --to html 
> ```

Pandoc is not responsible for the ID prefix *value*, the value (i.e. normalized filename) is passed on to Pandoc via its [`--id-prefix`](https://pandoc.org/MANUAL.html#option--id-prefix) param, as I already explained above.

**Comment by mcanouil** [comment]
The id-prefix flag is only set by the Visual Editor?
Is this only an issue when using the Visual Editor? How does Quarto behaves on its own? (AFK, so cannot test)

**Comment by salim-b** [comment]
> The id-prefix flag is only set by the Visual Editor?

I think so. Source: https://github.com/quarto-dev/quarto/blob/f9edec34e53817e9c9f73cb349f524a82bcc6474/packages/editor/src/pandoc/pandoc_converter.ts#L207-L210

> Is this only an issue when using the Visual Editor? How does Quarto behaves on its own? (AFK, so cannot test)

I think so. Quarto on its own doesn't normalize (footnote) identifiers, cf. https://github.com/quarto-dev/quarto-cli/issues/7894#issuecomment-1854615781
