### ISSUE TITLE
quarto render fails with relative path and knitr-based notebook.

### ISSUE THREAD

**Issue by gordonwoodhull** [quarto-dev/quarto-cli#9478]
### Bug description

When producing multiple outputs for side-by-side comparison, I prefer to run my `utils/render-all-formats.ts` script from a parent directory.

However, I'm currently unable to run a `knitr`-based notebook using a relative path. 

The error is

```
Error in rmarkdown:::abs_path(input) : 
  The file 'baz/foo.qmd' does not exist.
```

but the file does exist, and running `rmarkdown:::abs_path('baz/foo.qmd')` directly in R is okay.

I only somewhat regret bisecting this over a slow internet connection. I think it will be no surprise that the bad commit seems to be "create ProjectContext in single-file mode to guarantee engine and target caching" a28ac250a. Two big steps forward and a baby step back!

### Steps to reproduce

Minimal repro: put any knitr-based notebook in a subdirectory, e.g. this `baz/foo.qmd`

````
---
title: "relative path"
---

```{r}
print(1+1)
```
````

Then run

```sh
quarto render baz/foo.qmd
```

I'm not sure how to write a regression test for this, since it's about invocation rather than the content of the example.

### Expected behavior

It should render the qmd inside the directory.

### Actual behavior

```
Error in rmarkdown:::abs_path(input) : 
  The file 'baz/foo.qmd' does not exist.
Calls: .main -> execute -> setwd -> dirname -> <Anonymous>
Execution halted
ERROR: Error
    at renderFiles (file:///Users/gordon/src/quarto-cli/src/command/render/render-files.ts:350:23)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///Users/gordon/src/quarto-cli/src/command/render/render-shared.ts:102:18)
    at async Command.actionHandler (file:///Users/gordon/src/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/gordon/src/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/gordon/src/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/gordon/src/quarto-cli/src/quarto.ts:156:3)
    at async file:///Users/gordon/src/quarto-cli/src/quarto.ts:170:5
    at async mainRunner (file:///Users/gordon/src/quarto-cli/src/core/main.ts:35:5)
    at async file:///Users/gordon/src/quarto-cli/src/quarto.ts:160:3
```

### Your environment

MacOS Sonoma 14.4.1

### Quarto check output

```
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.13: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
fatal: not a git repository (or any of the parent directories): .git
      Path: /Users/gordon/src/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/gordon/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

(|) Checking Jupyter engine render..../Users/gordon/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

```

**Comment by cscheid** [comment]
This is a really bad one 😬.

**Comment by cscheid** [comment]
## More information

Adding an empty _quarto.yml file to the same directory is a workaround.

**Comment by gordonwoodhull** [comment]
If only I had remembered this hint this morning!

Yes, adding empty `_quarto.yml` to the root works great for `render-all-formats.ts`.

**Comment by bastianolea** [comment]
I'mm running in this very issue while trying ro render .qmd files that are part of a {blogdown} Hugo blog in RStudio. Rendering .qmd files in their own folders returns the `does not exist` error, but rendering other .md files from the blog that trigger rendering updated .qmd files do render the stubborn .qmd files. Empty `_quarto.yml` allowed rendering the .qmd file, but broke {blogdown} website preview. I'm on Quarto 1.5.1, blogdown 1.23 and R 4.4.2

**Comment by mcanouil** [comment]
@bastianolea Note that your are using a more than 2 years old pre-release. Current stable release is 1.9.37.
Also note that as the issue shows (commit, PR mention, "Development" section of the right sidebar), this was fixed and was integrated in Quarto 1.5.52.

Unless you are willing to update frequently, you should not use pre-releases, but you should definitely keep your version up to date as with any software.

**Comment by bastianolea** [comment]
@mcanouil sorry, I meant I'm in {quarto} _R package_ version 1.5.1 and running Quarto 1.9.37 (latest stable, if I'm not mistaken). Sorry for the confusion. Empty `_quarto.yml` fixes it, and rendering from command line on the file's directory works too, but rendering from RStudio (2026.04.0) doesn't work for me.

**Comment by mcanouil** [comment]
Could you open a new GitHub discussion or eventually a new GitHub issue (bug report template) and provide all needed informations (i.e., `quarto check` output, small reproducible example, etc.).
This issue is closed.
