### ISSUE TITLE
Update Typst to 0.11

### ISSUE THREAD

**Issue by skane88** [quarto-dev/quarto-cli#9479]
### Bug description

Can't use the table cell merge feature in templates because it is not supported in earlier versions of Typst. I downloaded the latest binary from Typst, overwrote the one that came with Quarto and it all worked again.

### Steps to reproduce

Use ```table.cell(colspan:number)``` in your code and you get an error.

### Expected behavior

Table should have nicely merged cells.

### Actual behavior

Document doesn't compile.

### Your environment

- IDE: VS Code
- OS: Windows 11

### Quarto check output

Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: C:\Users\Sean Kane\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by mcanouil** [comment]
You need the 1.5 pre-release to get Typst 0.11.

**Comment by skane88** [comment]
Thanks for letting me know.

**Comment by mcanouil** [comment]
FYI, that is listed in the changelog of the pre-release: https://quarto.org/docs/download/
