### ISSUE TITLE
Code cells "tags" displayed when indented (items list)

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#948]
The following markdown code displays `::: {.cell}` `:::` tag, at least for `html` and `revealjs` format

```md
1. Expliquer les relations entre `a`, `b`, `d` et `e`.

    ```{r}
    #| echo: true
    #| eval: false
    a <- 1:10
    b <- a
    b -> e
    e <- d <- 1:10
    ```
```

```md
1. Expliquer les relations entre `a`, `b`, `d` et `e`.

    ::: {.cell}

    ```{r}
    #| echo: true
    #| eval: false
    a <- 1:10
    b <- a
    b -> e
    e <- d <- 1:10
    ```

   :::
```

To note, using `.r` works as expected.

Example: https://github.com/mcanouil/quarto-issues/tree/main/quarto-cli%23948
Version: `0.9.433`

**Comment by jjallaire** [comment]
In order to nest a div inside a list item pandoc requires that the div line up with the beginning of the list item text. For example, the following plain markdown code exhibits the same behavior:

```
1. Pandoc list

    ::: {.clz}
   
    :::
```

Whereas this code works as expected:

```
1. Pandoc list

   ::: {.clz}
   
   :::
```

If you change your markdown to line up the list item and the div then things will work as you want them to.

**Comment by mcanouil** [comment]
Thanks, I did not know about the text alignment.
I thought it was the indentation level, especially since with `knitr`, I never had the issue.

**Comment by jjallaire** [comment]
Yes, that's because rmarkdown doesn't create an enclosing div around the chunk code/output whereas quarto does.

**Comment by jjallaire** [comment]
...and it appears as if Pandoc treats code blocks different than divs within list items (the former not requiring a matching indent level and the latter requiring it)
