### ISSUE TITLE
Figures left aligned (discrepancy with docs / bug?)

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#949]
As documented on the website (<https://quarto.org/docs/authoring/figures.html#figure-alignment>):

> Figures and their captions are center aligned by default.

But this is currently not true:

- When a figure has a caption, the figure is center aligned, but not the caption.
- When a figure has no caption, the figure is left aligned.

This is consistent for both `html` and `revealjs` formats.

Example: <https://github.com/mcanouil/quarto-issues/tree/main/quarto-cli%23949>
Version: `0.9.433`

**Comment by jjallaire** [comment]
I think we just need to update the docs here. The intended behavior is:

1) "Figures" (which in the Pandoc AST are images standing alone in a paragraph _with_ a caption) are center aligned (and their captions left-aligned, as captions are often long-ish and in that case look very strange center-aligned)

2) Plain images (no caption) are left aligned

**Comment by jjallaire** [comment]
Addressed here: https://github.com/quarto-dev/quarto-web/commit/ddbbe85899adecaa5bb49e4968b2ac93a0bbf33b

**Comment by fecet** [comment]
How can I adjust caption align? Caption are not always long and they are better be center-aligned in that case

**Comment by mcanouil** [comment]
@fecet Please use GitHub Discussions to ask questions.
In this case, the question has already been asked and answered, see for example #2304 (there are other threads with the answer).
