### ISSUE TITLE
doc-or-bug: aliases referencing qmd/md

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#9494]
### Bug description

The Quarto documentation contains some `aliases` which are in terms of Markdown files, not HTML files.

https://github.com/quarto-dev/quarto-web/blob/4d9a6310705e768d0029c0e0713c448b1afca15d/docs/extensions/filters.qmd#L3-L5

```yaml
aliases: 
  - /docs/authoring/shortcodes-and-filters.qmd
  - /docs/authoring/filters.qmd
```

As a result, files like the following are published to the site:

https://quarto.org/docs/authoring/filters.qmd

This is either a documentation mistake (because the aliases should mention HTML files) or a Quarto bug (because `*.qmd` should be rewritten).

**Comment by mcanouil** [comment]
I believe this to be an error in the "code" because the redirection is HTML based and <https://quarto.org/docs/websites/website-navigation.html#redirects>.

**Comment by aronatkins** [comment]
> I believe this to be an error in the "code" because the redirection is HTML based

You are saying that this is a bug in the code for the Quarto documentation page, not Quarto itself, yes?

**Comment by mcanouil** [comment]
Yes, the aliases should use HTML valid paths, so it can be `path/` or `path/index.html`, etc.

I made a PR to fix this. There were two other pages with the same issue.
Thanks for the report.

FYI, I think that's a copy/paste issue from the original location of the Quarto document where the extension was not changed.

- https://github.com/quarto-dev/quarto-web/pull/1090
