### ISSUE TITLE
download button duplicated in shiny quarto document

### ISSUE THREAD

**Issue by mikabr** [quarto-dev/quarto-cli#9498]
### Bug description

We're making a shiny app within a quarto document as [described here](https://quarto.org/docs/dashboards/interactivity/shiny-python/index.html) and want to put in a download file button in it as [described here](https://shiny.posit.co/py/api/core/ui.download_button.html). This appears to result in the download button being duplicated.

### Steps to reproduce

````qmd
---
format: dashboard
server: shiny
---

```{python}
import asyncio
import random
from datetime import date

from shiny import render, ui
```

```{python}
ui.download_button("downloadData", "Download")
```

```{python}
@render.download(
    filename=lambda: f"新型-{date.today().isoformat()}-{random.randint(100, 999)}.csv"
)
async def downloadData():
    await asyncio.sleep(0.25)
    yield "one,two,three\n"
    yield "新,1,2\n"
    yield "型,4,5\n"
```
````

### Expected behavior

a download button in the rendered document

### Actual behavior

two download buttons in the rendered document

### Your environment

- IDE: RStudio 2023.12.0+369
- OS: MacOS Venture 13.5

### Quarto check output

```
Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.10
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mikabr/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /Users/mikabr/Dropbox (Personal)/projects/_langcog/_levante/demographics/env/bin/python3
      Jupyter: 5.7.2
      Kernels: python3, childes-mor

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by gadenbuie** [comment]
Hi @mikabr! In Quarto documents, Shiny will automatically create the outputs for you, so there's no need to include `ui.output_download()` -- the `@render.download()` decorated function is enough.

````markdown
---
format: dashboard
server: shiny
---

```{python}
#| output: false
import asyncio
import random
from datetime import date

from shiny import render, ui
```

```{python}
@render.download(
    filename=lambda: f"新型-{date.today().isoformat()}-{random.randint(100, 999)}.csv"
)
async def downloadData():
    await asyncio.sleep(0.25)
    yield "one,two,three\n"
    yield "新,1,2\n"
    yield "型,4,5\n"
```
````

Our work on Quarto documents with `runtime: shiny` inspired [Shiny Express](https://shiny.posit.co/blog/posts/shiny-express/), a which lets you write Shiny apps in the same way inside `.py` files. Our API documentation now includes a section specifically for Shiny Express, and the examples demonstrated in those docs closely follows the syntax you'd use in Quarto: https://shiny.posit.co/py/api/express/express.render.download.html

**Comment by mikabr** [comment]
oh I see, thank you
