### ISSUE TITLE
R-package citations can not be found

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#950]
Creating citations for packages from R with `knitr` generates bib entries of the form:

```
@manual{R-knitr,
  type = {Manual},
  title = {Knitr: {{A}} General-Purpose Package for Dynamic Report Generation in r},
  author = {Xie, Yihui},
  year = {2020}
}
```

using: `knitr::write_bib(.packages(), "packages.bib")`, see https://bookdown.org/yihui/rmarkdown-cookbook/write-bib.html.
According to this: "There are two possible types of citation entries. One type is generated from the package’s DESCRIPTION file, and the other type is generated from the package’s CITATION file if provided. For the former type, the citation keys are of the form R-pkgname, where pkgname is the package name (e.g., R-knitr). For the latter type, the keys are created by concatenating the package name and the publication year (e.g., knitr2015)."

But it seems that bib-keys prefixed with `...-` can not be used in quarto, which excludes package citations for packages that don't contain a CITATION file but only a DESCRIPTION.

```
See @knuth84, See. @R-knitr
```

![image](https://user-images.githubusercontent.com/17450586/169685473-6f0ca3f3-30ec-4932-aa45-9fe17d143c1a.png)

Any citation key containing a dash is not recognized.
I assume quarto doesn't allow underscores here as to not clash with `fig-` `sec-` and the likes. Would it make sense to make an exception for `R-`?

**Comment by mcanouil** [comment]
Hi,

It works just fine.

```
---
title: 'quarto-dev/quarto-cli#950'
author: Mickaël Canouil, *Ph.D.*
bibliography: bibliography.bib
format:
  html:
    self-contained: true
    output-file: index-html.html
---

## Figures from code cell

Quarto version `` `r system("quarto --version", intern = TRUE)` ``.

I am using `knitr`[@R-knitr, @knitr2014, @knitr2015] to write my bibliography as follow:

```{.r}
knitr::write_bib("knitr", "bibliography.bib")
```

```

<img width="817" alt="image" src="https://user-images.githubusercontent.com/8896044/169686593-257de974-a07f-41ee-8aab-51fb5ef669a5.png">

Example: <https://github.com/mcanouil/quarto-issues/tree/main/quarto-cli%23950>
Version: `0.9.433`

**Comment by jmbuhr** [comment]
Your example only renders the citation for knitr2015, not R-knitr. See the paragraph about packages with only a DESCRIPTION file vs. those with a CITATION file.

**Comment by jmbuhr** [comment]
Try only R-knitr, or a package which does not have an associated publication (knitr was probably not a good example because of this)

**Comment by mcanouil** [comment]
> Your example only renders the citation for knitr2015, not R-knitr. See the paragraph about packages with only a DESCRIPTION file vs. those with a CITATION file.

I updated my example, I initially put commas instead of semicoluns between references.

**Comment by mcanouil** [comment]
> Try only R-knitr, or a package which does not have an associated publication (knitr was probably not a good example because of this)

Could you provide a reproducible example then?

**Comment by jmbuhr** [comment]
Just updating quarto to the latest version to be sure, but it takes a while since I'm on a train :)

**Comment by jmbuhr** [comment]
Maybe this is only in projects? Here is my example:
Repo: https://github.com/jmbuhr/quarto-r-citations
Rendered version on gh pages: http://jmbuhr.de/quarto-r-citations/

**Comment by mcanouil** [comment]
Indeed, in `book` type, dashes in bib keys do not work.
To note, `website` type works as expected here.

**Comment by dragonstyle** [comment]
I confirmed an issue where we were treating all `@elements` that included a `-` character as being a cross reference rather than a citation. I fixed it here:

https://github.com/quarto-dev/quarto-cli/commit/3ea3313465de18dfa5a4842d0692395c11fb4739

It will be in the next release, thanks for reporting!
