### ISSUE TITLE
Documentation seems to be outdated for inline R code

### ISSUE THREAD

**Issue by sebastian-gerdes** [quarto-dev/quarto-cli#9532]
R inline code seems not to work as described in the [documentation](https://quarto.org/docs/computations/inline-code.html) on my system. Specifically, I have to use `r *expression*` instead of `{r} *expression*`

Quarto Version: 1.3.433
RStudio Version: Version 2023.12.1+402 (2023.12.1+402)

Reproducible example (qmd-file):
```
---
engine: knitr
---
* This works: `r sqrt(10)`
* This doesn't: `{r} sqrt(10` 
```

Thanks for your great work and best greetings,
Sebastian

**Comment by mcanouil** [comment]
Try updating to at least Quarto 1.4.
