### ISSUE TITLE
Mermaid GitGraph: rotateCommitLabel doesn't rotate labels

### ISSUE THREAD

**Issue by mrmeloman** [quarto-dev/quarto-cli#9544]
### Bug description

Hello!
I'm trying to build a horizontal git graph with 45 degrees commits id's. However, all id labels are horizontal no matter what.

### Steps to reproduce

This is the code:

```
%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'rotateCommitLabel': true} } }%%
gitGraph
  commit id: "Initial commit"
  commit id: "Added commit definition to glossary" tag: "Мы тут" type: HIGHLIGHT
```

However, the id labels are horizontal:

![image](https://github.com/quarto-dev/quarto-cli/assets/58267804/68a1ead3-ec34-4626-ad55-fb2b9b825de9)

Am I missing something?

### Expected behavior

Labels should appear diagonal.

### Actual behavior

Labels are horizontal.

### Your environment

- IDE: RStudio 2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-05) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.0+421 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
- R version 4.3.1 (2023-06-16 ucrt)

```bash
### Quarto check output

Microsoft Windows [Version 10.0.19043.2364]
(c) Microsoft Corporation. All rights reserved.

E:\RProjects\git_course>quarto check
A new release of Deno is available: 1.28.2 → 1.42.4 Run `deno upgrade` to install it.

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.353
      Path: H:\RStudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: C:/Users/winge/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.46
      rmarkdown: 2.26

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
We don't do anything special with the mermaid output, so I imagine it's something that was added to a later version of mermaid than the one we currently have. You'll need to way until we upgrade (once per release, so the next upgrade will be around June/July)

**Comment by mcanouil** [comment]
Why is there a note about upgrading Deno in the check outputs? 🤔

**Comment by cscheid** [comment]
`Version: 1.3.353` <- that's why. 1.3 uses an old version of deno where we weren't disabling the upgrade warnings.

@mrmeloman You're running an outdated version of quarto

**Comment by cscheid** [comment]
This works on `main`:

<img width="264" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/2110c028-66fd-4c48-8429-aff5e15d3b0e">
