### ISSUE TITLE
`*-subcap` not working as expected and crashing

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#9550]
### Bug description

`*-subcap` are not working as expected and crashing.

Initially reported in #9546

### Steps to reproduce

<table>
<tr><th>Quarto document</th><th>Status</th></tr>
<tr><td>

````qmd
---
format: html
---

```{python}
#| label: fig-plots
#| fig-cap: "Plots"
#| fig-subcap: true
#| layout-ncol: 2

import matplotlib.pyplot as plt
plt.plot([1,23,2,4])
plt.show()

plt.plot([8,65,23,90])
plt.show()
```
````

</td><td>

No crash, but no a/b under the figures contrary to what is documented (screenshots)

</td></tr>
<tr><td>

````qmd
---
format: html
---

```{python}
#| label: tbl-tables
#| tbl-cap: "Tables"
#| tbl-subcap: true
#| layout-ncol: 2

import pandas as pd
from IPython.display import display

df = pd.DataFrame({'cars': ['BMW', 'Volvo', 'Ford'],
                   'pressure': [1.0, 1.5, 2.0]})

df2 = pd.DataFrame({'cars': ['BMW', 'Volvo', 'Ford'],
                   'pressure': [1.0, 1.5, 2.0]})

display(df)
display(df2)
```

````

</td><td>

Crash

</td></tr>
<tr><td>

````qmd
---
format: html
---

```{r}
#| label: fig-figure
#| fig-cap: "Figure"
#| fig-subcap: true
#| layout-ncol: 2
plot(1)
plot(2)
```

````

</td><td>

No crash, but no a/b under the figures contrary to what is documented (screenshots)

</td></tr>
<tr><td>

````qmd
---
format: html
---

```{r}
#| label: tbl-tables
#| tbl-cap: "Tables"
#| tbl-subcap: true
#| layout-ncol: 2
knitr::kable(head(cars))
knitr::kable(head(pressure))
```

````

</td><td>

Crash

</td></tr>
</table>

### Expected behavior

No crash and a/b under figures/tables as documented in <https://quarto.org/docs/authoring/cross-references.html#floats>.
<img width="879" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/c429fff0-8fcc-411e-97e7-7dab5c066032">
<img width="871" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/f8843009-73b9-4886-a068-3d237f81e0a5">

### Your environment

Quarto development version at 84ee8099cb1631d548f68bb1876c3c5285f8afa0

**Comment by cscheid** [comment]
This is actually a v1.4 regression (of course we learn of it on the day that we have a new patch release :sob:)
