### ISSUE TITLE
Add a Quarto LUA api function to easily get quarto binary path from Lua

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#9572]
This is useful for extensions that needs to run `quarto run` for example (like https://github.com/quarto-ext/shinylive/issues/50) 

and also in our own filters if we need to call Quarto (cc @gordonwoodhull )

This is necessary because  

- Quarto may not always be on PATH
- On Linux and Mac , this should work `pandoc.path.join({os.getenv('QUARTO_BIN_PATH'), 'quarto'})`
- On windows, we need `pandoc.path.join({os.getenv('QUARTO_BIN_PATH'), 'quarto.exe'})` or `pandoc.path.join({os.getenv('QUARTO_BIN_PATH'), 'quarto.cmd'})` depending if Dev or installed version. 

A Lua filter should not have to compute all this logic, and we should help with that.

**Comment by gordonwoodhull** [comment]
Do I understand correctly that using just `pandoc.path.join({os.getenv('QUARTO_BIN_PATH'), 'quarto'})` would fail in Windows distributions because it needs `quarto.cmd` there?

**Comment by cscheid** [comment]
I think that's right, but we're about to merge #9576 which would solve the problem (you'd just use `quarto.config.bin_path()`).

**Comment by cderv** [comment]
> Do I understand correctly that using just pandoc.path.join({os.getenv('QUARTO_BIN_PATH'), 'quarto'}) would fail in Windows distributions because it needs quarto.cmd there?

More precisely, `pandoc.path.join({os.getenv('QUARTO_BIN_PATH'), 'quarto'})` used in `pandoc.pipe()` fails in Quarto dev version because `pandoc.pipe()` looks for `quarto.exe` on Windows, and the cli is a script `quarto.cmd` in that case. 

With installed version of Quarto, `quarto.exe` exists so it works. 

I confirmed that in shinylive testing. 

As you are using `io.open`, this could be different, I need to test your PR or small try to confirm. I have not yet. 

> we're about to merge https://github.com/quarto-dev/quarto-cli/pull/9576 which would solve the problem (you'd just use quarto.config.bin_path()).

I kept other name `quarto.config.cli_path()` to match with TS API which as `quartoConfig.binPath()` and associated `QUARTO_BIN_PATH` env var are just pointing to the binary folder, not the CLI command. 

Though if you still think `quarto.config.bin_path()` is better, I'll do a latest update to the PR. See new version in #9576

**Comment by cderv** [comment]
In fact, you did review already and accepted ! All good then, I'll merge. 

`quarto.config.cli_path()` will point to the binary used to run the filter now. And can be used even in `io.open()`.

**Comment by gordonwoodhull** [comment]
Thanks @cderv - exactly what I wanted to understand.

I will use `quarto.config.cli_path()`!

**Comment by cderv** [comment]
@gordonwoodhull I now confirm that 

- run.lua
````lua
local quarto_path = pandoc.path.join({os.getenv('QUARTO_BIN_PATH'), 'quarto'})
local jout=pandoc.pipe(quarto_path,  { "--version" }, '')
print(jout)
````
This fails
````powershell
> quarto run .\run-pandoc-pipe.lua
Error running filter .\run-pandoc-pipe.lua:
C:\Users\chris\Documents\DEV_R\quarto-cli\package\dist\bin\quarto: createProcess: does not exist (No such file or directory)
stack traceback:
        .\run-pandoc-pipe.lua:2: in main chunk
````

but using io.open works
````lua
local quarto_path = pandoc.path.join({os.getenv('QUARTO_BIN_PATH'), 'quarto'})
local jout=io.popen(quarto_path .. ' --version', 'r')
print(jout:read('a'))
````

````powershell
> quarto run run.lua
99.9.9
````

So this is a difference.
