### ISSUE TITLE
sysctl command not found after R upgrade

### ISSUE THREAD

**Issue by rubinjm** [quarto-dev/quarto-cli#9580]
### Bug description

Render PDF from QMD file

### Expected behavior

PDF rendered successfully with prior version of R and RStudio

### Actual behavior

==> quarto preview Report.qmd --to pdf --no-watch-inputs --no-browse

quarto script failed: unrecognized architecture 
/Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto: line 129: sysctl: command not found

### Your environment

RStudio  2024.04.0+735 (2024.04.0+735)
Mac OS 14.4.1

### Quarto check output

Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.05
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/jrubin/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: /Users/jrubin/opt/anaconda3/bin/python
      Jupyter: 4.9.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
This error usually happens when you have a mismatched version of the architectures for your installed binaries. I think you probably need to install a universal version of RStudio (intel + apple silicon)

I'm not sure that this is a bug in Quarto, given that you didn't change your Quarto install, but did change the RStudio installation? In that case, maybe the correct place to file a bug is https://github.com/rstudio/rstudio

**Comment by cderv** [comment]
This was reported in the upstream repo indeed
- https://github.com/rstudio/rstudio/issues/13993

This was related to a Quarto issue 
- https://github.com/quarto-dev/quarto-cli/pull/8177

It has been merged, but it requires a Quarto 1.5 pre-release: https://quarto.org/docs/download/prerelease.html

Or you need to make `sysctl` available in PATH. I let you see the discussion on issue linked.

**Comment by rubinjm** [comment]
Thanks @cderv! That prerelease version fixed it.
