### ISSUE TITLE
Function after an empty div breaks source code blocks

### ISSUE THREAD

**Issue by kmmsks** [quarto-dev/quarto-cli#9589]
### Bug description

I have  quarto document (code A:starting_point below) in Rstudio. It renders as it should, but the Run All Chunks Above button does not work.

When I  insert a code chunk above the ### Refs -section, unexpected behaviour takes place. This is shown in code (A:unexpected).

If there is not a function defined in the last code block (see example B1), inserting a new code chunk above the `### Refs` section works as expected (outcome shown in code B2) and now, the Run All Chunks Above button does work.

If I remove 
`
::: {#refs}
:::
`

from the code (A:starting_point) this odd behaviour disappears.

Is there something I don't understand?

### Steps to reproduce

A:starting_point:

````qmd
---
title: "Untitled"
format: html
---

## Quarto


```{r}

c(1, 2)

```



### Refs

::: {#refs}
:::

## Next

```{r}

my_fun <- function(x){
x+1
}
my_fun(1)

```
````

Consider code A:starting_point,  move cursor between the first code block and the row containing `### Refs`, and press Insert a new code chunk to reproduce the problem. 

### Expected behavior

A:expected

````qmd
---
title: "Untitled"
format: html
---

## Quarto



```{r}

c(1, 2)

```

```{r}

```


### Refs

::: {#refs}
:::

## Next

```{r}

my_fun <- function(x){
x+1
}
my_fun(1)

```
````

Consider code B1. Again, move cursor between the first code block and the row containing `### Refs`, and press Insert a new code chunk. 

B1.
````cmd
---
title: "Untitled"
format: html
---

## Quarto


```{r}

c(1, 2)

```



### Refs

::: {#refs}
:::

## Next

```{r}

my_fun <- c(2,3)
my_fun

```
````

Now I get  the expected behavior (see code B2), as there is not a function defined in the last code chunk.

B2:
````qmd
---
title: "Untitled"
format: html
---

## Quarto


```{r}

c(1, 2)

```

```{r}

```


### Refs

::: {#refs}
:::

## Next

```{r}

my_fun <- c(2,3)
my_fun

```
````

### Actual behavior

In the case of the code A:starting_point, what I get after pressing the Insert a new code chunk -button is the following:

A:unexpected:
````qmd
---
title: "Untitled"
format: html
---

## Quarto


```{r}
c(1, 2)

```
```


```{r}
### Refs

::: {#refs}
:::

## Next

```{r}

my_fun <- function(x){
x+1
}
my_fun(1)

```
````

 In the code `A:starting_point`, when there is a function defined after the ### Refs -section, unexpected behavior (code A:unexpected) is seen as far as I concern. What I would expect, is the code A:expected

The same happens if there is 
`
::: {}
:::
`

instead of
`
::: {#refs}
:::
`

and the same happens if bibliography is defined in YAML: f.ex. bibliography: references.bib

The example function works as expected in a plain R script file.

In the example B1, there is not a function defined after the section `### Refs`, and what I get after inserting a new code chunk before the `### Refs` section is as expected (see B2)

### Your environment

rstudio:  2024.04.0+735 Chocolate Cosmos (desktop)
R version 4.4.0 (2024-04-24)
macOS Sonoma 14.4.1

### Quarto check output

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.02
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/ksuokas/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

LM3-345-29535:ci_paper ksuokas$ quarto check
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.02
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/ksuokas/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
@kmmsks Could you check your example as for instance B is completely invalid. But maybe that's the output and not the "steps to reproduce". Please edit your post to make it clear the steps to reproduce, and where there is something wrong.
Could you also make it clearer and next to the snippet of code what is working or not? `A. Work`, `B. does not work`, etc. Currently, you have to scroll up and down to get the whole picture which is not very clear.

**Comment by cderv** [comment]
> I have quarto document (A) in Rstudio. It renders as it should, but the Run All Chunks Above button does not work.

It seems like a RStudio IDE issue for there interactive feature in UI when the document contains this type of content. If no issue already opened in https://github.com/rstudio/rstudio, you could open one. 

This integration for Quarto in IDE source mode is a RStudio IDE feature.

**Comment by kmmsks** [comment]
Thank you for your quick responses. I have now improved the naming of the example codes in the question and I'll continue to studio issues

**Comment by mcanouil** [comment]
I cannot reproduce using Visual Editor in VSCode.
So it seems to be specific to RStudio.
