### ISSUE TITLE
Quarto autocomplete and indentation not working in source editor but it does in visual editor

### ISSUE THREAD

**Issue by egarcias** [quarto-dev/quarto-cli#9610]
### Bug description

Autocompletion and exploration of functions' arguments don't work within chunks in the source editor (Quarto document) once I use `:::` to add a tabset or any other functionality. However, autocompletion works fine in the console and in the visual editor.  

### Steps to reproduce

---
title: "Untitled"
format: html
---

```{r}
library(tidyverse)
```

```{r}
# the code is properly indented and autocompletion works
mtcars |> 
  select(cyl) |> 
  filter(cyl < 10)
```

::: panel-tabset
## block 1

```{r}
# when I press tabs, there are no matches to extract information
mtcars$
```

## block 2

```{r}
# functions do not display their available options 
mtcars |> 
  select()

```

:::

```{r}
# the problem persist after using the :::
mtcars |> 
  select()
```

- Note: this problem happen in the source editor, but not in the visual editor

### Expected behavior

I should be able to examine function arguments and use autocomplete options in chunks in a Quarto document.

### Actual behavior

not able to use autocompletion or explore functions arguments in the source editor in a Quarto document after I use `:::`. This issue, however, this doesn't happen in the console or the visual editor.

### Your environment

- macOS Sonoma 14.4.1
- Rversion: 4.4 "puppy cup"
- Quarto version: 1.5.32 (I also tried 1.4)

### Quarto check output

Quarto 1.5.32
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.13: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.32
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/egarcias/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
It looks like you're reporting an editor bug.

- If you're using RStudio, you need to report it to https://github.com/rstudio/rstudio
- If you're using VS code, you need to report it to https://github.com/quarto-dev/quarto

**Comment by egarcias** [comment]
Thanks for the clarification
