### ISSUE TITLE
How to generate .bbl 

### ISSUE THREAD

**Issue by rafaelorozco** [quarto-dev/quarto-cli#9617]
### What would you like to do?

Report an issue on quarto.org

### Description

Hello, I am trying to submit a quarto generated latex to arxiv but need to submit a .bbl file. I could not find on the documentation how to generate a .bbl file with quarto. 

Thank you for your attention!

**Comment by cscheid** [comment]
`keep-tex: true` will keep all latex temporaries after rendering. We document this in https://quarto.org/docs/output-formats/pdf-basics.html#latex-output but should be clearer about the other files as well.

**Comment by cscheid** [comment]
This is now fixed on [quarto.org](https://github.com/quarto-dev/quarto-web/commit/3864305078a30f08f3778db529e98ae14e7af6f3), pending a website rebuild.
