### ISSUE TITLE
Misleading doco states that Quarto comes with a built in PDF compilation engine?

### ISSUE THREAD

**Issue by KyleHaynes** [quarto-dev/quarto-cli#9624]
### What would you like to do?

Report an issue on quarto.org

### Description

This doco states 

> We also recommend the use of Quarto’s built in PDF compilation engine, which among other things performs automatic installation of any missing TeX packages.

Is this true? Output from rendering to PDF:

> No TeX installation was detected.
Please run 'quarto install tinytex' to install TinyTex.
If you prefer, you may install TexLive or another TeX distribution.

**Comment by cscheid** [comment]
That is referring not to the tex binaries, but to the way in which we call them.

**Comment by KyleHaynes** [comment]
@cscheid, thanks for the super quick response. That makes sense. Closing.

**Comment by cscheid** [comment]
FWIW, we document that you need to install TeX in our [PDF basics](https://quarto.org/docs/output-formats/pdf-basics.html#prerequisites).
