### ISSUE TITLE
Setting a running header for typst output clears the page after title block.

### ISSUE THREAD

**Issue by JoFrhwld** [quarto-dev/quarto-cli#9639]
### Bug description

I'd like to set a running header in a typst document. I put the following typst code in a `header.typ` document

```typst
#set page(
  header: align(center)[Draft]
)
```

And added the following to my quarto doc header:

```yaml
format: 
  typst: 
    include-in-header: header.typ
```

This has the effect of clearing the page after the title block, and the running header begins on the second page.

<img width="614" alt="quarto-typst-header_pdf" src="https://github.com/quarto-dev/quarto-cli/assets/178755/439bee3f-3973-44a3-979f-48f10f0a929b">

I believe this is because the code in `header.typ` gets inserted into the output typst document *after* the `#show doc:` block. ([Link](https://github.com/JoFrhwld/quarto-typst-header/blob/34ab85452529a86e9286054db8a8e6352f39af58/quarto-typst-header.typ#L237-L256))

### Steps to reproduce

I've set up a demo repository here: [https://github.com/JoFrhwld/quarto-typst-header/tree/main](https://github.com/JoFrhwld/quarto-typst-header/)

### Expected behavior

If I manually move the `header.typ` code above the `#show doc` block, I get desired result.
<img width="616" alt="quarto-typst-header_pdf" src="https://github.com/quarto-dev/quarto-cli/assets/178755/99e20665-c546-4d52-90d7-ceb62093a95f">

### Actual behavior

As documented above.

### Your environment

- IDE: RStudio 2024.04.0+735
- Quarto: 1.4.553

### Quarto check output

```
Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/joseffruehwald/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /Users/joseffruehwald/.pyenv/versions/lin511-2024/bin/python3
      Jupyter: 5.5.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/joseffruehwald/Library/CloudStorage/OneDrive-UniversityofKentucky/Projects/1_Beginning/quarto-typst-header/renv/library/macos/R-4.4/aarch64-apple-darwin20
        - /Users/joseffruehwald/Library/Caches/org.R-project.R/R/renv/sandbox/macos/R-4.4/aarch64-apple-darwin20/f7156815
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
This isn't a bug, rather it's a limitation of the typst format. When using typst (especially in comparison with LaTeX), you have to lean harder into changing the typst template (or writing a new one).

**Comment by mcanouil** [comment]
See <https://quarto.org/docs/output-formats/typst-custom.html#advanced-customization> for advanced Typst customisation and of course the Typst documentation itself.

**Comment by ThomasFaria** [comment]
I am experiencing a similar issue as @JoFrhwld because I want to make the outline a bit more stylish, as described in the Typst documentation: [Typst Outline Definitions](https://typst.app/docs/reference/model/outline/#definitions-entry).

The problem is that both of these configurations produce the exact same .typ file:

```
format: 
  typst: 
    include-before-body: 
      - text: |
          #show outline.entry.where(
            level: 1): it => {
              v(12pt, weak: true)
              strong(it)
            }
```

```
format: 
  typst: 
    include-in-header: 
      - text: |
          #show outline.entry.where(
            level: 1): it => {
              v(12pt, weak: true)
              strong(it)
            }
```
@cscheid, you said it is not a bug but is this the desired behavior ?
Would it be possible to make the `include-in-header` incorporate text immediately after including your `definitions.typ` file (https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/typst/pandoc/quarto/definitions.typ)?

I don't know how difficult/possible it is to change this behavior without creating a new typst template, otherwise I will go into that direction.
Thanks a lot for your help and for the amazing work you are doing with Quarto!

**Comment by mcanouil** [comment]
@ThomasFaria Moving the `include-*` might make your case works but breaks other cases in the process.
See the template partials documentation for advanced customisation.

**Comment by ThomasFaria** [comment]
Modifying the template-partials worked as needed thanks a lot @mcanouil !
