### ISSUE TITLE
quartoInspect() prevents deployment of shiny app to shinyapps.io.  

### ISSUE THREAD

**Issue by rccline** [quarto-dev/quarto-cli#9642]
### Bug description

quartoInspect prevents shiny app deployment to shinyapps.io

### Steps to reproduce

When I attempt to publish a local shiny app to shinyapps.io I get the following error:  ─ Preparing for deployment ────────────────────────────────────────────────────
✔ Re-deploying "shiny_solar_production" using "server: shinyapps.io  
Error in `quartoInspect()`:
! `quarto` not found.
ℹ Check that it is installed and available on your `PATH`.
Backtrace:
    ▆
 1. └─rsconnect::deployApp(...)
 2.   └─rsconnect:::appMetadata(...)
 3.     └─rsconnect:::inferQuartoInfo(...)
 4.       └─rsconnect:::quartoInspect(appDir = appDir, appPrimaryDoc = appPrimaryDoc)
 5.         └─cli::cli_abort(c("`quarto` not found.", i = "Check that it is installed and available on your {.envvar PATH}."))
 6.           └─rlang::abort(...)
Execution halted  

### Expected behavior

I expect the app to deploy.  I uninstalled Quarto and the error still exists..  The shiny app was created in a shiny project and NOT a quarto project.    

### Actual behavior

When trying to publish the shiny app, I get the error message reported above.  Execution is halted.  

### Your environment

RStudio 2024.04.0+735 "Chocolate Cosmos" Release (a00d0e775dbc93e0d79a1bf474e3e8e8de677383, 2024-04-24) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0+735 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36  
R version 4.3.3 (2024-02-29 ucrt) -- "Angel Food Cake"

### Quarto check output

I uninstalled Quarto from my computer.

**Comment by mcanouil** [comment]
Thanks for the report.
I don't believe this to be a Quarto CLI issue but unfortunately you did not provide sufficient information for us to investigate, in particular you did not described what is needed to reproduce.

Also note that the error is about the R package `rsconnect` not finding Quarto, so removing Quarto is unlikely to resolve that issue.
I don't know which version of `rsconnect` you are using but you should report the issue to the correspondng repository: https://github.com/rstudio/rsconnect
