### ISSUE TITLE
Python code chunk is evaluated in R environment when setting `chunk_output_type` to `console`

### ISSUE THREAD

**Issue by hewag1975** [quarto-dev/quarto-cli#9647]
### Bug description

Setting the `chunk_output_type` to `console` in the YAML header causes Python chunks to be evaluated in R instead of Python. Setting it to `inline`, all works as expected. Same goes when executing the Python code in the chunk line by line. 

### Steps to reproduce

````
---
title: "Untitled"
editor_options: 
  chunk_output_type: console
---

```{r}

library(reticulate)
```

```{python}

import numpy as np
```
````

### Expected behavior

Evaluating the Python chunk should start the Python environment and evaluate the code there. 

### Actual behavior

The chunk is evaluated in R and throws an error.

### Your environment

RStudio 2024.04.0+735 "Chocolate Cosmos" Release (a00d0e775dbc93e0d79a1bf474e3e8e8de677383, 2024-04-24) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2024.04.0+735 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.4.553 (/opt/quarto/bin/quarto)

### Quarto check output

Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/hendrik/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /home/hendrik/Documents/repos/gitlab/shiny/smart/.venv/bin/python3
      Jupyter: 5.5.1
      Kernels: python3, geo, d2l, fastai, hug

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /opt/R/4.3.2/lib/R
      LibPaths:
        - /home/hendrik/R/x86_64-pc-linux-gnu-library/4.3
        - /opt/R/4.3.2/lib/R/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Could you properly format your post using code blocks for code and terminal outputs? Thanks.
If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.

Could you also elaborate on how to reproduce, as currently there is not enough information.

I am assuming you are talking about an editor issue, possibly RStudio, if so, then please do report this on the appropriate repository:
- https://github.com/rstudio/rstudio
- https://github.com/quarto-dev/quarto (Quarto VSCode extension and Visual Editor)

**Comment by hewag1975** [comment]
Sorry for the poorly formatted code. Just updated it. To reproduce the issue, please open a new Quarto doc it in RStudio and evaluate the code blocks by clicking on `Run current chunk`.
