### ISSUE TITLE
VScode can't render a qmd file. 

### ISSUE THREAD

**Issue by shengpeishu** [quarto-dev/quarto-cli#9663]
I can't render the .qmd file in vscode.  The issue is as follows. 
However, the .ipynb file renders well. 

![屏幕截图 2024-05-14 105946](https://github.com/quarto-dev/quarto/assets/153803900/191062f5-4374-4cb1-af59-51afe89d29e5)

**Comment by cscheid** [comment]
Sorry, but we need a full reproducible example in order to follow up.
