### ISSUE TITLE
Katex cannot be loaded with Jupyter widget-like content

### ISSUE THREAD

**Issue by kendrewlau** [quarto-dev/quarto-cli#967]
When the math rendering method is set to katex, and there is Jupyter widget-like content (e.g. displaying a pandas dataframe in rich format), then math equations cannot be rendered. An example file is katex.ipynb in the zip file. This is the html output:

![katex](https://user-images.githubusercontent.com/25242516/170162926-37f90ee0-c039-4768-bbaf-a951a8b2671e.png)

It seems that the injection of require.js affects the loading of katex.js. As a workaround, modify the generated html file to add a <script> tag of katex.js without defer="" before the <script> tag of require.js.

```html
<!-- existing content before the script tag of loading require.js -->

<!-- add a script tag of loading katex.js without defer="" -->
<script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>

<!-- existing content of the script tag of loading require.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
```
[katex.zip](https://github.com/quarto-dev/quarto-cli/files/8767304/katex.zip)

**Comment by jjallaire** [comment]
Hi there, thanks for reporting this! This is fixed here: https://github.com/quarto-dev/quarto-cli/commit/e82d4eb19ea57ec2c3326922fc7ef757def28f85 (but a build w/ the fix might be a day or so out)

**Comment by kendrewlau** [comment]
The fix works great. Thank you!
