### ISSUE TITLE
md_extensions support?

### ISSUE THREAD

**Issue by jinlin82** [quarto-dev/quarto-cli#968]
rmarkdown support Pandoc `md_extensions` option, does quarto support it yet?

**Comment by cderv** [comment]
You can use the `from` key for that  (https://quarto.org/docs/reference/formats/html.html#rendering)

````markdown
---
title: "Hello, world!"
format: html
from: markdown+emoji
---

:smile:
````

**Comment by jinlin82** [comment]
great!
