### ISSUE TITLE
Empty slide created for parsed HTML tables in powerpoint

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#9681]
Found while looking at #9680 

````markdown
---
title: "Test"
format: pptx
keep-md: true
---

## Test Table

```{r}
#| label: test

head(iris, 1) |>  
    knitr::kable(format = "html")
```

## Test Table

```{r}
#| label: test

head(iris, 1) |>  
    knitr::kable(format = "pipe")
```

````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/02721a86-f3b0-4ca9-8b63-6c714c52e150)

<details>
<summary>Intermediate md</summary>

````markdown
---
title: "Test"
format: pptx
keep-md: true
---




## Test Table



::: {.cell}
::: {.cell-output-display}

`````{=html}
<table>
 <thead>
  <tr>
   <th style="text-align:right;"> Sepal.Length </th>
   <th style="text-align:right;"> Sepal.Width </th>
   <th style="text-align:right;"> Petal.Length </th>
   <th style="text-align:right;"> Petal.Width </th>
   <th style="text-align:left;"> Species </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 5.1 </td>
   <td style="text-align:right;"> 3.5 </td>
   <td style="text-align:right;"> 1.4 </td>
   <td style="text-align:right;"> 0.2 </td>
   <td style="text-align:left;"> setosa </td>
  </tr>
</tbody>
</table>

`````

:::
:::

## Test Table

::: {.cell}
::: {.cell-output-display}

| Sepal.Length| Sepal.Width| Petal.Length| Petal.Width|Species |
|------------:|-----------:|------------:|-----------:|:-------|
|          5.1|         3.5|          1.4|         0.2|setosa  |

:::
:::

````

</details>

**Comment by cderv** [comment]
Note that this does not happen with **gt** 
````markdown
---
title: "Test"
format: pptx
keep-md: true
---

## Test Table

```{r}
#| label: test

head(iris, 1) |>  
    gt::gt()
```

## Test Table

```{r}
#| label: test2

head(iris, 1) |>  
    knitr::kable(format = "pipe")
```

````
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/13d5519b-2649-4c48-9d5a-a5c6ad4e98fb)


which shows the other issue #9680

**Comment by cderv** [comment]
In fact we get the same with computed table 

``````markdown
---
title: "Test"
format: pptx
keep-md: true
---

## Test Table


`````{=html}
<table>
 <thead>
  <tr>
   <th style="text-align:right;"> Sepal.Length </th>
   <th style="text-align:right;"> Sepal.Width </th>
   <th style="text-align:right;"> Petal.Length </th>
   <th style="text-align:right;"> Petal.Width </th>
   <th style="text-align:left;"> Species </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 5.1 </td>
   <td style="text-align:right;"> 3.5 </td>
   <td style="text-align:right;"> 1.4 </td>
   <td style="text-align:right;"> 0.2 </td>
   <td style="text-align:left;"> setosa </td>
  </tr>
</tbody>
</table>

`````

``````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/27dbde3c-49fc-4bb7-b304-175c9a267ff7)

**Comment by cderv** [comment]
Looking at our trace I see this at the end of the parsed table 
````
foot:
      t: "TableFoot"
      attr: "('', [], [])"
      rows: []
  - t: "RawBlock"
    format: "html"
    text: "\n"
  - t: "Div"
    attr: "('3ade8a4a-fb1d-4a6c-8409-ac45482d5fc9', ['hidden'], [])"
    content: []
````

Maybe this is messing with Pandoc writer for PPTX 🤔 

the hidden div is also in the working example, so I don't think it will do something. Though IDK what it is about 🤷‍♂️ 

Rawblock is introduced at 
https://github.com/quarto-dev/quarto-cli/blob/b35914c9e8aa0814ee698db164795abfea15496d/src/resources/filters/quarto-pre/table-rawhtml.lua#L16-L34

Maybe we need to do that only for HTML or at least not for powerpoint 🤔

**Comment by cderv** [comment]
Ok so I prototype a cleanup step for powerpoint to remove any HTML rawblocks
````lua
function pptx_raw_cleanup() 
  if not _quarto.format.isPowerPointOutput() then
    return {}
  end
  return {
    -- Remove any html RawBlock
    RawBlock = function(el)
      if string.find(el.format, "^html") then
        return {}
      end
      return el
    end
  }
end 
````

And this solves this issue and also #9680 

On Pandoc side, Raw Block should be correctly ignored except for openxml 

https://github.com/jgm/pandoc/blob/13c8e7c9f01ed79282a20cb65740f41ab6c78b97/src/Text/Pandoc/Writers/Powerpoint/Presentation.hs#L486-L488
````haskell
-- TODO: work out the format
blockToParagraphs blk@(RawBlock _ _) = do addLogMessage $ BlockNotRendered blk
                                          return []
````
https://github.com/jgm/pandoc/blob/13c8e7c9f01ed79282a20cb65740f41ab6c78b97/src/Text/Pandoc/Writers/Powerpoint/Presentation.hs#L617-L618
````haskell
-- If the format isn't openxml, we fall through to blockToPargraphs
blockToShape (RawBlock (Format "openxml") str) = return $ RawOOXMLShape str
````

Maybe there is an issue in Pandoc itself about all this... though I think we can do something ourself on that... 

I'll push a PR with the idea to discuss.

**Comment by cderv** [comment]
This is now fixed by removing the rawblock - though I understand now why there was a new slides I think 

In this parsed HTML tables 

`````markdown
```{=html}
<table>
 <thead>
  <tr>
   <th style="text-align:right;"> Sepal.Length </th>
   <th style="text-align:right;"> Sepal.Width </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 5.1 </td>
   <td style="text-align:right;"> 3.5 </td>
  </tr>
</tbody>
</table>

```
`````

There is a blank line in the raw HTML block. This is what caused the insertion of the html RawBlock in our processing 
```` 
  - t: "RawBlock"
    format: "html"
    text: "\n"
````

And it seems it lead to a new slide in Powerpoint. 

Just sharing this in case another fix would be to trim blank lines around html content inside a rawblock before parsing the HTML in our processing;

**Comment by cscheid** [comment]
> Just sharing this in case another fix would be to trim blank lines around html content inside a rawblock before parsing the HTML in our processing;

This is a good idea.
