### ISSUE TITLE
Importing `.css` from parent directory not working

### ISSUE THREAD

**Issue by arnaudgallou** [quarto-dev/quarto-cli#969]
I'm trying to import a `.css` file using the `css` format option in a RStudio project.

The following works:
```
---
format:
  html:
    css: styles.css
---
```
or
```
---
format:
  html:
    css: some_dir/styles.css
---
```
However, importing the `.css` file from a parent directory does not seem to work:
```
---
format:
  html:
    css: ../styles.css
---
```
Currently using Quarto v. 0.9.440 in RStudio v. 4.2.0.

**Comment by jjallaire** [comment]
I'm not able to reproduce this problem (I can successfully use the styles.css file in a parent). Could you create a git repo or gist that reproduces this (also let us know what platform you are running/testing on)

**Comment by arnaudgallou** [comment]
My bad, it seems to work but only when I open the HTML in a web browser. For some reasons, neither the integrated Viewer in RStudio nor the Quicklook preview on Mac will style the document accordingly. That's very confusing because moving `styles.css` in the same directory as the `.qmd` file or in a lower level folder will make both the Viewer and Quicklook preview will style the document. I made a repo [here](https://github.com/arnaudgallou/quarto-css-path) in case. I'm running on macOS Monterey.
