### ISSUE TITLE
OJS `width` variable evaluates in surprising ways

### ISSUE THREAD

**Issue by jimjam-slam** [quarto-dev/quarto-cli#970]
I recently discovered the [`width` special](https://github.com/observablehq/stdlib/blob/main/README.md#width) included with the OJS standard library! And here I've been, manually sizing my charts like a chump 😛

This isn't necessarily an issue - I would class it more as "surprising behaviour - but `${width}` appears not to be the local width of the chunk in which it is called, but instead appears to be a global variable whose value depends on the location of the chunk in which it is first evaluated.

There might be a race condition here with regard to exactly which chunk that is, but I'm not 100% sure.

Since Observable Notebooks typically run in an environment where all cells have the same width (on <https://observablehq.com>), I'm not entirely surprised that this hasn't come up before! But it could lead to unexpected or surprising results in a Quarto document context.

## Sample A: not called in any OJS chunk (only interpolated into Markdown)

```
---
title: "Test width"
---

The width of this section is **${width}**.
```

![image](https://user-images.githubusercontent.com/6520659/170202074-8a836d32-4d2d-4caa-ad8e-a8007381c416.png)

Here, `${width}` doesn't evaluate at all. I'm speculating that if no OJS cell is defined then maybe the standard library isn't loaded at all, since even regular string interpolation (eg. `${1+1}`) isn't evaluated.

## Test B: calling in a single OJS chunk

````
---
title: "Test width"
---

Let's see if we detect width!

The width of this section is **${width}**.

## In an OJS block

```{ojs}
md`Width is **${width}**`
```
````

Here, `${width}` evaluates to the width of the section it's called in (_not_ the width of the entire page). it responds as I expect to page-resizing, getting smaller as I shrink the section but maxxing out at the max section width.

![image](https://user-images.githubusercontent.com/6520659/170202620-b7859265-ac43-414c-9446-da3bad9d0a9d.png)

## Test C: calling in two OJS chunks of different widths

````
---
title: "Test width"
---

Let's see if we detect width!

The width of this section is **${width}**.

## In an OJS block

```{ojs}
md`Width is **${width}**`
```

And what about in a screen-width section?

::: {.column-screen style="background-color:#ccddff"}
```{ojs}
md`The width of this screen-wide section is **${width}**.`
```
:::
````

![image](https://user-images.githubusercontent.com/6520659/170202897-aff60904-f18b-4433-beb2-42641b001f49.png)

Here, _both_ calls of `${width}` refer to the width of the screen section, even though the first call is still in the narrower section. As I resize the page, it responds to the changing size of the screen section.

**Comment by cscheid** [comment]
(Welcome to the deep end of the ojs pool! :)) 

1) The inline evaluation should be happening, that's a bug.

2) The HTML layout in quarto is different from observablehq, and so we need to override it ourselves. Right now, this happens [here](https://github.com/quarto-dev/quarto-ojs-runtime/blob/main/src/quarto-ojs.js#L556-L570), and it should track the `clientWidth` attribute of the `main` element. That's likely not what you want!

3) We have a (unadvertised, not sufficiently tested!) _different_ special variable that tracks clientWidths of different divs. We've tested it for setting widths of panel layouts. It's called `layoutWidth`, and returns a map from div ids to client widths. It's possible that it won't work for your case, but we should probably figure out how to solve your use case, since it'll be common for other OJS users.

**Comment by cscheid** [comment]
wrt to 1. This is a silly bug: That inline evaluation isn't working because we try to sniff the .qmd for the presence of OJS, and we're not using inline evaluation for that. A simple workaround for now is to add this to your cell:


    ```{ojs}
    //| echo: false
    //| output: false
    null
    ```

**Comment by cscheid** [comment]
As of the latest commit, we now support an `ojs-engine` boolean field in the metadata of html formats, like so:

```
---
format:
  html:
    ojs-engine: true
---

This will work: ${width}
```

**Comment by cscheid** [comment]
Going back to point 3. Previously, `layoutWidth` only tracked the widths of panel divs.
As of commit e27c5937d1d04101462482e7a79a9afe31ec7ad3, we now look for DOM elements with `id`s and `data-ojs-track-layout`. Once we have a new build out, we'll add the corresponding documentation to the website as well.

**Comment by jimjam-slam** [comment]
That all makes sense! I'll upgrade and have a play around with layoutWidths and see how it works 😊 Thanks for taking a look!

![image](https://user-images.githubusercontent.com/6520659/170479448-c133d1c9-fb19-48ed-b43d-5658bb8d925f.gif)
