### ISSUE TITLE
Lua error when rendering Quarto docs in RStudio

### ISSUE THREAD

**Issue by mroberts1** [quarto-dev/quarto-cli#9714]
I am getting the error below when attempting to render any Quarto repository in RStudio. I am running  the latest version of Quarto (1.4.554),  the latest version of MacOS Monterey (12.7.5), and the latest release of RStudio (2024.04.1+748).

I am attaching an example of one file generating the error, although no .qmd files are currently rendering and are generating the same error.
[index.qmd.zip](https://github.com/quarto-dev/quarto/files/15362818/index.qmd.zip)

```
Error running Lua:
error loading module 'lpeg' from file '/usr/local/lib/lua/5.4/lpeg.so':
	dlopen(/usr/local/lib/lua/5.4/lpeg.so, 0x0006): tried: '/usr/local/lib/lua/5.4/lpeg.so' (code signature in <ADDBC93A-9F32-3E8C-A046-33C5CF6698F9> '/usr/local/Cellar/lpeg/1.1.0/lib/lua/5.4/lpeg.so' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/lpeg/1.1.0/lib/lua/5.4/lpeg.so' (code signature in <ADDBC93A-9F32-3E8C-A046-33C5CF6698F9> '/usr/local/Cellar/lpeg/1.1.0/lib/lua/5.4/lpeg.so' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
stack traceback:
	[C]: in upvalue 'orig_require'
	[string "..."]:1442: in function 'require'
	/Applications/quarto/share/pandoc/datadir/lpegshortcode.lua:4: in main chunk
	[C]: in upvalue 'orig_require'
	[string "..."]:1442: in function 'require'
	/Applications/quarto/share/pandoc/datadir/readqmd.lua:6: in main chunk
	[C]: in upvalue 'orig_require'
	[string "..."]:1442: in function 'require'
	/Applications/quarto/share/filters/qmd-reader.lua:6: in main chunk
```

**Comment by cscheid** [comment]
@mroberts1 see this specific line:

```
error loading module 'lpeg' from file '/usr/local/lib/lua/5.4/lpeg.so':
```

This is a library that's installed in your system, and not by Quarto. You could start by inspecting your environment variables `LUA_PATH` and `LUA_CPATH` to see if they're set.

**Comment by mroberts1** [comment]
>  You could start by inspecting your environment variables LUA_PATH and LUA_CPATH to see if they're set.

I don't know how to do this. Here's what I've tried:

- Uninstalled homebrew pandoc
- Reinstalled pandoc 3.2 outside homebrew. 
- Reinstalled lua and luarocks via homebrew, resulting in same error.

Versions: 

Quarto: 1.4.554
RStudio: 2024.04.1+748
MacOS: 12.5.7 (Monterey)

I did notice that I have only been receiving this error since installing Monterey update 12.5.7.

As of now, all Quarto projects throw same error when rendering a .qmd file.

**Comment by mcanouil** [comment]
Quarto embeds Pandoc. You should not need to install Pandoc as Quarto should not use your global Pandoc if it is properly installed.

**Comment by mroberts1** [comment]
I deleted global Pandoc

reinstalled Quarto: 1.4.554 via homebrew

reinstalled lua, luarocks, and lpeg via homebrew

checked path of lua: lua: /usr/local/bin/lua /usr/local/share/man/man1/lua.1

checked path of luarocks: luarocks: /usr/local/bin/luarocks

checked path of lpeg: whereis lpeg returns only lpeg:

The error remains unchanged (see below) when rendering a .qmd file

I checked, and the module 'lpeg' is present at /usr/local/lib/lua/5.4/lpeg.so

```
Error running Lua:
error loading module 'lpeg' from file '/usr/local/lib/lua/5.4/lpeg.so':
	dlopen(/usr/local/lib/lua/5.4/lpeg.so, 0x0006): tried: '/usr/local/lib/lua/5.4/lpeg.so' (code signature in <ADDBC93A-9F32-3E8C-A046-33C5CF6698F9> '/usr/local/Cellar/lpeg/1.1.0/lib/lua/5.4/lpeg.so' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/lpeg/1.1.0/lib/lua/5.4/lpeg.so' (code signature in <ADDBC93A-9F32-3E8C-A046-33C5CF6698F9> '/usr/local/Cellar/lpeg/1.1.0/lib/lua/5.4/lpeg.so' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
stack traceback:
	[C]: in upvalue 'orig_require'
	[string "..."]:1442: in function 'require'
	/Applications/quarto/share/pandoc/datadir/lpegshortcode.lua:4: in main chunk
	[C]: in upvalue 'orig_require'
	[string "..."]:1442: in function 'require'
	/Applications/quarto/share/pandoc/datadir/readqmd.lua:6: in main chunk
	[C]: in upvalue 'orig_require'
	[string "..."]:1442: in function 'require'
	/Applications/quarto/share/filters/qmd-reader.lua:6: in main chunk
```

**Comment by cscheid** [comment]
````
reinstalled lua, luarocks, and lpeg via homebrew

checked path of lua: lua: /usr/local/bin/lua /usr/local/share/man/man1/lua.1

checked path of lpeg: whereis lpeg returns only lpeg:
````

That's likely the issue. We _shouldn't_ be using your system installation of Lua, but somehow we are. Can you try something like

```
LUA_PATH="" LUA_CPATH="" quarto render test-file.qmd
```

**Comment by mroberts1** [comment]
This worked from the terminal with a test index.qmd file. However, when I tried rendering the same file in RStudio it failed with again the same Lua error.

I uninstalled my homebrew lua, luarocks, and pandoc. I reinstalled Quarto 1.4.544. Still the same error.

I have been using Quarto for the past two years and have dozens of projects, but I am at my wits end with this.

**Comment by cscheid** [comment]
> This worked from the terminal with a test index.qmd file. However, when I tried rendering the same file in RStudio it failed with again the same Lua error.

This to me suggests that it's indeed your environment that's confusing us. Do you have something like `export LUA_PATH="something-here"` in your .bashrc, .zshrc, or similar file? If you open a terminal and type `echo $LUA_CPATH` and `echo $LUA_PATH`, what do you get?

> Could the cause be my recent upgrade to MacOS Monterey 12.5.7?

I'm on Ventura (13.5.2), so I'm almost certain that isn't the case. 

My theory still remains that something in your environment is causing Pandoc's embedded version of Lua to search for libraries where it shouldn't.

**Comment by cscheid** [comment]
> but this Lua error has taken down my entire development environment.

I'm truly sorry you're running into trouble, but I don't understand how that could have happened given the instructions we're providing.

**Comment by mroberts1** [comment]
Thank you I really appreciate your assistance. I'll keep trying!

**Comment by mroberts1** [comment]
> If you open a terminal and type echo $LUA_CPATH and echo $LUA_PATH, what do you get?

I get nothing.

I'm running fish as my terminal shell. I'm going to try switching back to zsh as my shell and see if that helps.

**Comment by cscheid** [comment]
> So looks like $LUA_CPATH and $LUA_PATH are somehow not set?

It's very strange that `LUA_PATH="" LUA_CPATH="" quarto render test-file.qmd` would work, but `echo $LUA_PATH $LUA_CPATH` would return no output. Did you try that from the RStudio terminal?

**Comment by cderv** [comment]
I believe this could have been fixed from 
* https://github.com/quarto-dev/quarto-cli/issues/8274

Though it requires Quarto v1.5- can you install latest pre-release version and try again ?

**Comment by mroberts1** [comment]
Yes, also no output from echo $LUA_PATH $LUA_CPATH in the RStudio terminal.

What's baffling is that I can render and preview from the terminal in RStudio like this (for example)

LUA_PATH="" LUA_CPATH="" quarto preview index.qmd

and it renders/previews just fine. 

But if I click on the Render button, or save the document (triggering Render on Save), it fails with the Lua error again.

Reinstalled RStudio via homebrew, but same result.

**Comment by mroberts1** [comment]
Thanks for your help - the Lua PATH/CPATH error was finally fixed by upgrading to Quarto 1.5.37.

**Comment by bassamsdata** [comment]
Just I wanna mention that I had the same issue on Mac and the latest pre-release 1.5.39 solved the issue.

**Comment by pchr8** [comment]
I'm not sure if this is best addressed here or in the AUR package page, but I got this error using the latest [AUR (en) - quarto-cli](https://aur.archlinux.org/packages/quarto-cli) quarto-cli 1.5.52-1. Got fixed by dowgrading to 1.4.555-1

**Comment by cscheid** [comment]
@pchr8 Unfortunately, we don't maintain AUR packages and can't offer support.

I also don't understand how this would be happening in 1.5.52 given the fix in https://github.com/quarto-dev/quarto-cli/issues/8274 was merged in 1.5.39.

I will note that Pandoc very recently merged this PR: https://github.com/jgm/pandoc/pull/9922. It is related to this issue. I wonder if somehow it's both the case that

1. Arch is using a different Pandoc version than the one we recommend
2. this change is causing us to regress on the behavior

**Comment by nfaux** [comment]
Hi all, 
I am hitting this issue now as well :(
Mac Book Pro - OS: 14.6.1
RStudio: Version 2024.04.2+764 (2024.04.2+764)

```bash
quarto pandoc --version

pandoc 3.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/nfaux/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

My basic test.qmd
```qmd
---
title: "Quarto Basics"
format:
  html:
    code-fold: true
---

## It's a test
Hello world

\```{r}
a <- "BIG FISH"
\```

The fish was a `{r} a`.
```
The \ is just to get the markdown here ok - the \ are not in the file.

Run within RStudio via the Render button I get the following error:
```bash
==> quarto preview test.qmd --to html --no-watch-inputs --no-browse



processing file: test.qmd
                                                                                                            
output file: test.knit.md

pandoc 
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Quarto Basics
  
Error running Lua:
error loading module 'lpeg' from file '/usr/local/lib/lua/5.4/lpeg.so':
	dlopen(/usr/local/lib/lua/5.4/lpeg.so, 0x0006): symbol not found in flat namespace '_luaL_addlstring'
stack traceback:
	[C]: in upvalue 'orig_require'
	[string "..."]:1442: in function 'require'
	...ources/app/quarto/share/pandoc/datadir/lpegshortcode.lua:4: in main chunk
	[C]: in upvalue 'orig_require'
	[string "..."]:1442: in function 'require'
	...ts/Resources/app/quarto/share/pandoc/datadir/readqmd.lua:6: in main chunk
	[C]: in upvalue 'orig_require'
	[string "..."]:1442: in function 'require'
	...ntents/Resources/app/quarto/share/filters/qmd-reader.lua:6: in main chunk
```

If run with in the RSudio terminal:
```bash
LUA_PATH="" LUA_CPATH="" quarto render test.qmd 


processing file: test.qmd
                                                                                                            
output file: test.knit.md

pandoc 
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Quarto Basics
  
Output created: test.html
```

I am running `zsh` and have not set `LUA_PATH` or  `LUA_CPATH` in my `.zshrc` file.
Running the below in an independent terminal window:
```bash
quarto render test.qmd


processing file: test.qmd
1/3
2/3 [unnamed-chunk-1]
3/3
output file: test.knit.md

pandoc
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Quarto Basics

Output created: test.html
```

This also works in the independent terminal:

```bash
quarto preview test.qmd --to html --no-watch-inputs --no-browse


processing file: test.qmd
1/3
2/3 [unnamed-chunk-1]
3/3
output file: test.knit.md

pandoc
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Quarto Basics

Output created: test.html

Watching files for changes
Browse at http://localhost:3080/
```

So it seems there is an issue with the call in RStudio, associated with the Render button.

Not sure where to go from here, except running the render from the command line.

**Comment by mcanouil** [comment]
> The \ is just to get the markdown here ok - the \ are not in the file.

Could you properly format your post using code blocks for code and terminal outputs? Thanks.
If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.
See <https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us>.

**Comment by nfaux** [comment]
> > The \ is just to get the markdown here ok - the \ are not in the file.
> 
> @nfaux Could you properly format your post using code blocks for code and terminal outputs? Thanks. If your code contains code blocks, you need to enclose it using more backticks, _i.e._, usually four `` ```` ``. See https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us.
> 
> > ```
> > quarto pandoc --version
> > 
> > pandoc 3.2
> > Features: +server +lua
> > Scripting engine: Lua 5.4
> > User data directory: /Users/nfaux/.local/share/pandoc
> > Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
> > This is free software; see the source for copying conditions. There is no
> > warranty, not even for merchantability or fitness for a particular purpose.
> > ```
> 
> We don't need the version of Pandoc, we need the version of Quarto being used or better the output of `quarto check`.

I have updated the post with the `quarto check` and fixed the markdown.

**Comment by mcanouil** [comment]
@nfaux Could you try using a release instead of the development version to rule out the building operation that occurs when using the latter?

**Comment by nfaux** [comment]
> @nfaux Could you try using a release instead of the development version to rule out the building operation that occurs when using the latter?

Download the latest version and reran the checks:
```bash
quarto check
Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/nfaux/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/nfaux/Library/R/x86_64/4.4/library
        - /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: /Users/nfaux/.pyenv/versions/3.10.4/bin/python3
      Jupyter: 4.11.1
      Kernels: nsqip_validation, python3

(\) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
[✓] Checking Jupyter engine render....OK
```

Ran the render again with in the RStudio terminal:
```bash
✗ quarto preview test_doc.qmd --to html --no-watch-inputs --no-browse


processing file: test_doc.qmd
                                                                                                                                         
output file: test_doc.knit.md

Warning message:
In in_dir(input_dir(), expr) :
  You changed the working directory to /Users/nfaux/Projects/Repos/test-project/R (probably via setwd()). It will be restored to /Users/nfaux/Projects/Repos/test-project/R/src. See the Note section in ?knitr::knit
pandoc 
  to: html
  output-file: test_doc.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  toc: true
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Test Doc
  author: Noel Faux
  date: 09-June-2024
  lastmod: 26-July-2024
  draft: true
  editor_options:
    chunk_output_type: console
  output-dir: /Users/nfaux/test-project/R/reports/
  toc_float: true
  toc_depth: 3
  
Output created: test_doc.html

Watching files for changes
Browse at http://localhost:5488/
```
All good.

Via the render button in RStudio the issue has now been resolved. So either there was an issue with the RStudio packaged version, or the development version caused an issue. Or, both, as I was hitting the error before I installed the development version on my system. Taken together, I suspect its the latter, and if others are seeing this, I would suggest to install Quarto on the local system and not rely on the one packaged with RStudio.
