### ISSUE TITLE
Use Microsoft Edge for rendering (on Windows)

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#972]
Currently it seems that Chrome is required to render files that contain mermaid.
I think it is guaranteed that Windows has Microsoft Edge installed, so it would be useful to be able to use Microsoft Edge instead of Chrome.

https://github.com/quarto-dev/quarto-cli/blob/cc5119e1c657ed0e11fc2a32ab46559062167113/src/core/puppeteer.ts#L201-L226

**Comment by jjallaire** [comment]
I'm not sure if Edge implements enough of the protocol for our use case (see https://github.com/cyrus-and/chrome-remote-interface). @cscheid Have we tried w/ Edge yet?

**Comment by cderv** [comment]
@jjallaire FWIW we have support for Edge in `pagedown::chrome_print` . Not extensively tested but no issue reported yet. We are just using a small part of the protocol for printing though.

If you decide to add support, just sharing that on Windows the key in registry should `MSEdgeHTM` instead of `ChromeHTML`.

**Comment by jjallaire** [comment]
Okay, great to know! I don't think @cscheid has a windows machine for development -- any chance you could give this a try in your environment based on the code you have for pagedown?

**Comment by cderv** [comment]
Yes sure I can add that. 

Regarding version, I checked on the `http://localhost:9222/json/version` with msegde remote debugging protocol. Version is 1.3 so I think it is the latest  stable of the protocol. 

We could check more precisely `http://localhost:9222/json/protocol` for the protocol content to check that all that is needed is in there.
