### ISSUE TITLE
Quarto Lightbox and df_print do not seem to work together

### ISSUE THREAD

**Issue by arvindvenkatadri** [quarto-dev/quarto-cli#9727]
### Bug description

I am trying to print a tibble and also create a chart in a Quarto document, a blog entry on a Quarto website. When `lightbox:auto` is used in the _quarto.yml file, the images show the lightbox behaviour ( zoom ) but the tibble does not print in the rendered HTML file. 

### Steps to reproduce

https://github.com/arvindvenkatadri/DemoWebSite.git

### Expected behavior

1) lightbox: auto - The tibble should render as per the preference stated in `df_print` ( paged in my case), and the images should be zoom-able on click, when the option `lightbox:auto` is used in the _quarto_yml. 

2) lightbox not used: The tibble should still render, but images should not zoom on click. 

### Actual behavior

1) lightbox: auto  - In this situation only the images zoom, the tibble does not print.

2) lightbox not used: The tibble now renders, but the images do not zoom.

It seems we can either use one or the other of `lightbox:auto` OR `df_print: paged`. 

### Quarto check output

Quarto 1.4.554
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.554
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/arvindv/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

**Comment by arvindvenkatadri** [comment]
OS: MacOS Ventura 13.4
IDE: RStudio 2023.03.1+446

**Comment by mcanouil** [comment]
What does `df_print` have to do with images and lightbox?

Also `label` should not contain special characters such as spaces as they are used as HTML ids which are required by lightbox amongst other tools.

**Comment by cscheid** [comment]
It's a bug on _both_ our usage of lightbox and pagedtable :(

Both libraries do the following:

## paged table

```js
window.onload = function() {
  PagedTableDoc.initAll();
};
```

## Our lightbox filter

```lua
          local scriptContents = "var lightboxQuarto = GLightbox(" .. optionsJson .. ");\n"
          scriptContents = scriptContents .. [[
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });
...
```
