### ISSUE TITLE
Quarto preview hangs

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#9737]
### Bug description

Sometimes `quarto preview` just hangs. And hitting `ctrl-c` doesn't do anything at all:

<img width="757" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/1813121/bb096d68-cddb-471a-a04b-98e808a7d06c">

Is there a way to view logs to see what is going on? I've waiting for more than 15 minutes.

Closing the tab and re-opening it does the same thing sometimes. There is no issue with `quarto render`.

### Your environment

- MacOS

### Quarto check output

```bash
$ quarto check
Quarto 1.5.22
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.22
      Path: /Users/USER/Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.13 (Conda)
      Path: /Users/USER/miniforge3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment]
1. We need a repro to be able to track this down.
2. We're on https://github.com/quarto-dev/quarto-cli/releases/tag/v1.5.37 and you're on 1.5.22. Could you check with the latest version? Thanks.

**Comment by kdheepak** [comment]
I'm not able to reproduce it on a new project unfortunately. You may be able to `git clone https://github.com/kdheepak/kdheepak.github.io` to reproduce? It doesn't seem to happen every time. It has happened more after adding more `index.ipynb` files recently. 

I'm trying it with the latest version of quarto now, I'll report back.

**Comment by kdheepak** [comment]
One definite issue I'm having is that `ctrl-c` doesn't work (even after the `quarto preview` works):

<img width="678" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/1813121/670e09e8-863f-4cfd-a3e8-c331b391a805">

**Comment by cscheid** [comment]
Unfortunately I can't repro that. You might want to check Activity Monitor or `top` to see what other processes might be going on. Can you Ctrl-Z instead?

**Comment by kdheepak** [comment]
Yes, I'm able to `ctrl-z`, and then `kill %1` works to stop the process. With the latest version of quarto it doesn't hang forever (it takes ~5 minutes to load the preview) but I'm still not able to `ctrl-c` to stop the preview. I'll close this issue because it is not reproducible and it is a minor improvement for me over the previous version.

**Comment by kdheepak** [comment]
Are you able to clone https://github.com/kdheepak/kdheepak.github.io?

I ran `git clean -fxd` and then ran `quarto preview` at 12:06 pm:

<img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/1813121/5db6265f-5c6b-436b-bec4-64e615fa7aec">
 
It is 12:15 pm at the moment and the preview still hasn't loaded for me.

**Comment by cscheid** [comment]
I get a crash with

```
[ 8/68] blog/understanding-variables-and-mutability-in-julia/index.md
Error running filter /Users/cscheid/repos/github/quarto-dev/quarto-cli/src/resources/filters/main.lua:
svgbob_cli: createProcess: posix_spawnp: does not exist (No such file or directory)
```

**Comment by kdheepak** [comment]
It loaded around 12:24pm for me:

<img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/1813121/a0a6c80d-df88-4a05-b8ab-626e2cde8c27">

**Comment by kdheepak** [comment]
Ah, can you remove the `quarto-svgbob` filter from the `_quarto.yml` file? 

https://github.com/kdheepak/quarto-svgbob

The extension I wrote doesn't bundle the cli.

**Comment by kdheepak** [comment]
I did a fresh `git clean -fxd` and ran `quarto preview` again at 12:25pm:

<img width="1181" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/1813121/001db6fe-7f66-4567-9499-0f0b571b5c0a">

It seems like it finishes rendering all the pages in less than 3 minutes (screenshot from 12:28pm) but then is doing something that doesn't respond to `ctrl-c`. `htop` says it is `quarto / deno`:

<img width="1512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/1813121/2bd87401-187e-4a4e-973e-a39cad8f9da3">

**Comment by cscheid** [comment]
Ok, I can repro now.

**Comment by kdheepak** [comment]
This is the full command:

`/Users/kd/Applications/quarto/bin/tools/aarch64/deno run --unstable-ffi --no-config --allow-read --allow-write --allow-run --allow-env --allow-net --allow-ffi --no-check --v8-flags=--max-old-space-size=8192,--max-heap-size=8192 --importmap=/Users/kd/Applications/quarto/bin/vendor/import_map.json /Users/kd/Applications/quarto/bin/quarto.js preview`

**Comment by kdheepak** [comment]
Thanks for looking into this!

**Comment by cscheid** [comment]
The issue is somewhere in `src/project/types/website/listing/website-listing.ts:completeListingGeneration`

**Comment by cscheid** [comment]
**Hello, and welcome to "find regex engine performance problems week". This is your host**

On Tuesday, we had https://github.com/quarto-dev/quarto-cli/pull/9733

Today, we have:

```
$ deno
> let r = /(.*?(?:preview|feature|cover|thumbnail).*?(?:\\.png|\\.gif|\\.jpg|\\.jpeg|\\.webp))/
undefined
> let s = "https://kdheepak.com/blog/graphing-cgpgrey-rock-paper-scissors-youtube-game/data:image/png;base64, " + "f".repeat(100000) + "="
undefined
> r.test(s) // this takes 5 seconds!!
false
```

**Comment by cscheid** [comment]
O(n^2) running time truly is the devil: fast enough for you not to notice, and slow enough to happen in production:

```ts
async function foo(l: number) {
  let r = /(.*?(?:preview|feature|cover|thumbnail).*?(?:\\.png|\\.gif|\\.jpg|\\.jpeg|\\.webp))/
  let s = "https://kdheepak.com/blog/graphing-cgpgrey-rock-paper-scissors-youtube-game/data:image/png;base64, " + "f".repeat(l) + "="
  let m = s.match(r)
  return m;
}

for (let i = 0; i < 24; ++i) {
  let t = performance.now();
  const l = 1 << i;
  let m = foo(l);
  console.log(l, performance.now() - t);
}
```

```
$ deno run test-regex.ts
1 0
2 0
4 0
8 0
16 0
32 0
64 0
128 0
256 0
512 2
1024 0
2048 4
4096 16
8192 54
16384 214
32768 850
65536 3404
131072 13676
```

**Comment by kdheepak** [comment]
oof. So it's just that one file? I guess I can save the images to disk and use markdown syntax to load them again. 

Nice debugging!

**Comment by cscheid** [comment]
This is fixed in https://github.com/quarto-dev/quarto-cli/releases/tag/v1.5.38

**Comment by kdheepak** [comment]
Awesome! Thank you!

**Comment by kdheepak** [comment]
It tested it out and `quarto preview` loads instantly now (after rendering all the files)!
