### ISSUE TITLE
Add `repo-subdir` config option for website/book projects

### ISSUE THREAD

**Issue by salim-b** [quarto-dev/quarto-cli#975]
Bookdown's `bs4_book` format [supports a `repo.subdir`configuration option](https://bookdown.org/yihui/bookdown/html.html#specifying-the-repository), allowing to specify a path relative to the Git repo given in the `repo.base` config option.

Adding support for a similar Quarto config option **`repo-subdir`** in addition to the existing `repo-url` and `repo-branch` options for website/book projects would accommodate use cases where the actual Quarto project files are stored in a subdirectory of a (bigger) Git repository.

**Comment by jjallaire** [comment]
You should be able to just include the subdir in the `repo-url` and it will be automatically handled correctly e.g. `repo-url: http://github.com/example/repo/subidr` should work as expected.

**Comment by salim-b** [comment]
Well, that means Quarto's current implementation of the Git `repo-*` spec is based on the premise that there are no subgroups in the URL structure, which happens to be true for Git**Hub** repos but not for Git**Lab** ones. The latter do [support subgroups](https://docs.gitlab.com/ee/user/group/subgroups/) which means you can have a repository with a repo root URL like `gitlab.com/rstudio/quarto/cli`.

With Quarto's current implementation, the generated URLs are always wrong for a "subgrouped" GitLab repo, even regardless whether the Quarto project lives under the root or a subdir of that repo.

**Comment by jjallaire** [comment]
Okay, fair enough! I've implemented support for the `repo-subdir` option here: https://github.com/quarto-dev/quarto-cli/commit/9d33db35c1c9faae471343871f1c0233ee263857

**Comment by salim-b** [comment]
Thank you very much, you're awesome!

I've just tested Quarto 0.9.481, my findings:

- Specifying `repo-url: https://gitlab.com/rstudio/quarto/cli` **together with** a `repo-subdir` results in valid URLs.
- Specifying `repo-url: https://gitlab.com/rstudio/quarto/cli` **without** `repo-subdir` (assuming the Quarto project is located under the repo's root) results in invalid URLs like `https://gitlab.com/rstudio/quarto/tree/master/cli/`. It seems you've missed to adapt some code that's still based on the old premise about no subgroups...

**Comment by jjallaire** [comment]
Okay (sorry to have missed that!). I think the right answer is to not do any special handling of `repo-url` paths (and rely entirely on `repo-subdir`). That change is here: https://github.com/quarto-dev/quarto-cli/commit/38cb169b5b109a08b7dde07d70b01d3bdc30beb8. This is available in v0.9.483

**Comment by salim-b** [comment]
Perfect, thanks! Now all URLs are valid.
