### ISSUE TITLE
Sidebar and TOC are still clickable when they are collapsed

### ISSUE THREAD

**Issue by royfrancis** [quarto-dev/quarto-cli#9781]
### Bug description

An example page with sidebar menu on the left and TOC on the right.

![Screenshot 2024-05-27 at 18 25 54](https://github.com/quarto-dev/quarto-cli/assets/5083500/097469fe-a70c-4dba-9fd4-ed046021f319)

These menus collapse when there are wide content or content in the margin.

![Screenshot 2024-05-27 at 18 27 46](https://github.com/quarto-dev/quarto-cli/assets/5083500/8d676415-d961-4fa5-a3af-6906ba278aa4)

Although the menu looks collapsed, the menu items are still present and clickable although invisible. Easy to identify by hovering over with the mouse.

### Steps to reproduce

**_quarto.yml**

```
project:
  type: website

website:
  sidebar:
    contents:
      - section: Reports
        contents:
          - a.qmd
format:
  html:
    toc: true

```

**a.qmd**

```
---
title: Report A
---

## Section A

::: {.column-page}
![](https://quarto.org/docs/authoring/images/elephant.jpg)
:::

- A
- l
- i
- n
- e
- o
- f
- t
- e
- x
- t
- t
- h
- a
- t
- i
- s
- v
- e
- r
- y
- l
- o
- n
- g

## Section B

::: {.column-margin}
![](https://quarto.org/docs/authoring/images/elephant.jpg)
:::

::: {.column-margin}
|A|B|
|---|---|
|Bla|Bla|
|Bla|Bla|
|Bla|Bla|
:::

## Section C

::: {.column-page}
![](https://quarto.org/docs/authoring/images/elephant.jpg)
:::

```

### Expected behavior

Collapsed menu must not be clickable.

### Actual behavior

Collapsed menu is invisible but clickable.

### Your environment

MacOS Sonoma 14.5 , VS Code

### Quarto check output

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/user/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by cderv** [comment]
Thanks for the report. This should solve it
