### ISSUE TITLE
xxx.ipynb file gets deleted when quarto render xxx.qmd gets called

### ISSUE THREAD

**Issue by statquant** [quarto-dev/quarto-cli#98]
Hello, I noticed the following behaviour:

starting with `document_02.ipynb` only :
![image](https://user-images.githubusercontent.com/3612473/131385451-d6a56082-fa6b-439b-bcfc-f3802fc4c3f2.png)

`document_02.ipynb` is converted to `qmd`
![image](https://user-images.githubusercontent.com/3612473/131385680-91d412bb-1159-4af7-ac24-f9f01c65efb5.png)

then `document_02.qmd` is rendered
![image](https://user-images.githubusercontent.com/3612473/131385850-1a65e97b-01b0-455c-87fc-849ae846082a.png)

it looks like `document_02.ipynb` has now disapeared
![image](https://user-images.githubusercontent.com/3612473/131386012-ed0887be-d691-4cc8-a604-ffe19b08d1ee.png)

Is that expected behaviour ?
If yes I think that would be great to have a option to keep both files.

Regards

**Comment by jjallaire** [comment]
You can add the `keep-ipynb: true` option to the YAML to keep both files (https://quarto.org/docs/computations/execution-options.html?q=keep#intermediates)
