### ISSUE TITLE
SVG are loosing classes when using `embed-resources`, impacting revealjs features (`class="slide-logo"`, `.absolute`)

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#9803]
Using Quarto 122b0f3093c560a6c24365fc9241bb83d4590ef4
It works as expected using v1.4.554

## Expected behaviour

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
title: "Quarto Playground"
format:
  revealjs:
    logo: https://raw.githubusercontent.com/mcanouil/hex-stickers/main/SVG/rlille.svg
    embed-resources: false
---

## Slide

This is a playground for Quarto.

![An image](https://placehold.co/600x400.png)

````

</td><td>

<img width="1241" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/2cbfff15-493c-4615-8cad-87ccc9520779">

</td></tr>
</table>

## Actual behaviour

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
title: "Quarto Playground"
format:
  revealjs:
    logo: https://raw.githubusercontent.com/mcanouil/hex-stickers/main/SVG/rlille.svg
    embed-resources: true
---

## Slide

This is a playground for Quarto.

![An image](https://placehold.co/600x400.png)

````

</td><td>

<img width="1241" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/c368cf6d-a484-4990-ba0e-059fd5317a35">

</td></tr>
</table>

The `class="slide-logo"` is lost when embedding.

**Comment by cderv** [comment]
This is Panodc issue IMO so if it was working before probably following an update of pandoc 

Try 
````
❯ quarto pandoc --to html --embed-resources -o embed.html
<img src="https://raw.githubusercontent.com/mcanouil/hex-stickers/main/SVG/rlille.svg" class="slide-logo">
^Z
````
And look in `embed.html` - the class is missing.

**Comment by cderv** [comment]
But doing the same with Quarto 1.4.554 works - so this is a change in Pandoc.

**Comment by cderv** [comment]
1.4.554 uses pandoc 3.1.11.1 and latest use pandoc 3.2

And we can determine that change happens in Pandoc 3.2

``` r
library(pandoc)

min <- "3.1.11"
max <- "3.2"


versions <- pandoc::pandoc_available_releases()
#> ℹ Fetching Pandoc releases info from github...
versions <- versions[seq.int(which(versions == min), which(versions == max))]

for(version in versions) {
  if (!pandoc::pandoc_is_installed(version)) {
    pandoc::pandoc_install(version)
  }
  embed <- pandoc::pandoc_convert(
    text = '<img src="https://raw.githubusercontent.com/mcanouil/hex-stickers/main/SVG/rlille.svg" class="slide-logo">',
    to = "html",
    args = "--embed-resources", 
    version = version)
  if (!any(grepl("slide-logo", embed))) {
    cat("pandoc version ", version, " does not keep classes")
    break
  }
}
#> pandoc version  3.2  does not keep classes
```

<sup>Created on 2024-05-31 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by cderv** [comment]
Probably related to @cscheid PR in pandoc
* https://github.com/jgm/pandoc/issues/9652
* https://github.com/jgm/pandoc/pull/9653

so we may have broken ourself Quarto through Pandoc by trying to fix another issue 😅  

Though I don't see how merging would mess this up, because we should have kept the class. 
So either if no class on the svg, it does not keep image class. 

Or this is a side effect of this change somewhere else

**Comment by cderv** [comment]
Testing with another svg from pandoc repo 
````powershell
❯ quarto pandoc --to html --embed-resources -o embed.html
```{=html}
<img class="something" src="https://raw.githubusercontent.com/jgm/pandoc/7abfec3d2c0e6084b8029d38cd45912697822f3a/test/command/SVG_logo.svg" />
```
^Z
````

I don't get the class name either 
````html
<svg id="svg_7e8f68c20ccd090c0566" role="img" viewBox="-50 -50 100 100" width="100" height="100">
<title>SVG Logo</title>
````

So it seems when no class on the svg, the one from img tag is lost. 

@cscheid I don't know Haskell enough to know if your change is supposed to handle this case.

**Comment by cscheid** [comment]
Hm - if this is a Pandoc regression we won't be able to fix it for 1.5.

**Comment by cderv** [comment]
What about doing a "hack" to at least restore behavior ?  I have a branch working with the following 

- wrap the logo image in a span of a class we know. 
- Leverage revealjs plugin system to restore the class on the element in the span when it is missing. 

This would not solve the underlying svg issue, but this would "hide" this issue until we have a proper fix. I can make a PR with the idea.

**Comment by cscheid** [comment]
I don't know. This would only fix it in `logo` and `format: revealjs`, right? The bug would still exist in other usages of `embed-resources`. I'm not sure it's worth the extra complexity in the code base, that would then need to be reverted once upstream is fixed.

**Comment by cderv** [comment]
> This would only fix it in logo and format: revealjs, right? 

Yes exactly. 

> I'm not sure it's worth the extra complexity in the code base, that would then need to be reverted once upstream is fixed.

That is the question. I'll share the idea in a PR and you'll be the judge of that.

**Comment by cderv** [comment]
Here is one use case where another class is lost: When using `.absolute` class for positioning on an svg element. See 
- https://github.com/quarto-dev/quarto-cli/discussions/10613

````markdown
---
title: test SVG
format: revealjs
embed-resources: true
---

## Slide 1

![](https://quarto.org/docs/presentations/revealjs/demo/mini/images/kitten-450-250.jpeg){.absolute top=50 right=50 width="450" height="250"}

![](https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg){.absolute top=50 right=50 width="450" height="250"}
````

**Comment by ZokszY** [comment]
I was having a similar issue with this template on version 1.5.57:

````qmd
---
title: "Quarto Playground"
format:
  revealjs:
    embed-resources: true
---

## No width

::: {layout-ncol=2}
![Simple Linear Regression](https://upload.wikimedia.org/wikipedia/commons/e/ec/Anscombe%27s_quartet_3.svg)

![K-NN Classification](https://upload.wikimedia.org/wikipedia/commons/e/e7/KnnClassification.svg)
:::

## width="200px"

::: {layout-ncol=2}
![Simple Linear Regression](https://upload.wikimedia.org/wikipedia/commons/e/ec/Anscombe%27s_quartet_3.svg){width="200px"}

![K-NN Classification](https://upload.wikimedia.org/wikipedia/commons/e/e7/KnnClassification.svg){width="200px"}
:::

## width="500px"

::: {layout-ncol=2}
![Simple Linear Regression](https://upload.wikimedia.org/wikipedia/commons/e/ec/Anscombe%27s_quartet_3.svg){width="500px"}

![K-NN Classification](https://upload.wikimedia.org/wikipedia/commons/e/e7/KnnClassification.svg){width="500px"}
:::
````

In this example there are two SVG files with different behavior. The first one is properly resized and almost properly placed on every slide, while the second is not resized and has a wrong position except in the last slide. I then tried using using v1.4.554 which didn't help. However the latest version v1.6.32 does work properly.

Here are the results I get with each version (exported to PDF using the PDF Export Mode of RevealJS):

- [v1.4.554](https://github.com/user-attachments/files/17558669/test_1-4-554.pdf)
- [v1.5.57](https://github.com/user-attachments/files/17558670/test_1-5-57.pdf)
- [v1.6.32](https://github.com/user-attachments/files/17558671/test_1-6-32.pdf)
