### ISSUE TITLE
Fenced div doesn't allow insertion of `id` when using a `callout` class

### ISSUE THREAD

**Issue by rich-iannone** [quarto-dev/quarto-cli#982]
These two fenced divs

````
:::{#my_id}
text
:::

:::{.callout-note #my_id}
text
:::
````

produce these HTML fragments:

```
<div id="my_id">
  <p>text</p>
</div>
```

```
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div id="my_id" class="callout-body-container callout-body">
<p>text</p>
</div>
</div>
```

In the first case, the id is inserted into the div tag but in the second it is not included in the outer div. This is not what I expect according the guidelines on fenced divs in the pandoc manual (https://pandoc.org/MANUAL.html#extension-fenced_divs).

Would it be possible to incorporate id values (even in callouts) into the outer div? This would allow for further customization using the id value.

**Comment by jjallaire** [comment]
That's an oversight! We will fix this soon!

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/43d231530bd489a87dfcca3906ebf9a2ef3aec36
