### ISSUE TITLE
The visualization mode of Python notes cannot run code.

### ISSUE THREAD

**Issue by yuhcuan** [quarto-dev/quarto-cli#9838]
### Bug description

Recently started using Quarto to take notes on Python. Honestly, I find it much more convenient for note-taking than Jupyter! However, I found that in the visual editing mode, in Vscode, I can't run code with Ctrl+ Enter. In Source model
![picture](https://github.com/quarto-dev/quarto-cli/assets/130506347/22377238-f3d0-420d-9eee-a175293fd453)
, running code and shortcuts work without any issues. I checked the command settings in Visual mode and found no issues. But for some reason, it's not running.

### Your environment

 IDE: Visual Studio Code 1.89

OS：Windows 11

![picture](https://github.com/quarto-dev/quarto-cli/assets/130506347/96dde119-5faf-44da-8d89-4dca2999b325)

**Comment by yuhcuan** [comment]
Quarto performs flawlessly in RStudio, thank you to your team!

**Comment by mcanouil** [comment]
Thanks for the feedback.

That's something to report on the IDE/extension repository if not already there (https://github.com/quarto-dev/quarto).

This repository is about Quarto CLI itself not the tools that integrate it.
