### ISSUE TITLE
Commented-out inline R code unexpectedly executes

### ISSUE THREAD

**Issue by bclarke-nes** [quarto-dev/quarto-cli#9847]
### Bug description

When rendering Quarto to HTML, inline R code that is commented-out inappropriately executes and causes rendering to fail.

### Steps to reproduce

The following qmd will fail to render to HTML

````qmd
---
title: "Commented code executes"
format: html
---

<!-- `r 2 + "two"` -->
````

### Expected behavior

Rendering should proceed normally

### Actual behavior

Rendering fails with message 

````
in `2 + "two"`:
! non-numeric argument to binary operator
Quitting from lines 6-7 (error.qmd)
Execution halted
````

### Your environment

Windows 10 x64 build 19045	x86-64R 4.3.1
Rstudio desktop 2024.04.0+735
Quarto 1.4.553

### Quarto check output

```
Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: C:\Program Files\RStudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/*****/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.47
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Could you properly format your post using code blocks for code and terminal outputs? Thanks.
If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by bclarke-nes** [comment]
Apologies @mcanouil, failed to save my last edit.

**Comment by mcanouil** [comment]
Note that you cannot comment inline code, as it will be evaluated anyway and at the beginning of rendering.
I can't find it again right now, but there is a discussion about commenting.

Overall, there are no bugs here, but simply a limitation.

**Comment by bclarke-nes** [comment]
Thanks, wasn't aware of that limitation

**Comment by cderv** [comment]
For the context, this is a knitr engine parsing limitation. More on this in and related
* https://github.com/yihui/knitr/issues/2301
