### ISSUE TITLE
jupyter python3 error: isinstance() arg 2 must be a type or tuple of types?

### ISSUE THREAD

**Issue by smc77** [quarto-dev/quarto-cli#985]
I just installed quarto for the first time and am just trying to run through the "getting started" example, but I immediately hit an error when trying to render the document.  I am able to open the ipynb document that's created with jupyter and run that without any issues.  

> quarto check jupyter

[✓] Checking Python 3 installation....OK
      Version: 3.6.3 (Conda)
      Path: /Users/smc77/anaconda/bin/python
      Jupyter: 4.9.1
      Kernels: python3, ir, python2

(\) Checking Jupyter engine render....

isinstance() arg 2 must be a type or tuple of types
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[✓] Checking Jupyter engine render....OK

Similarly, when I try to render a simple test document, I get:

> quarto render test.qmd --to html
ERROR: 

isinstance() arg 2 must be a type or tuple of types

**Comment by jjallaire** [comment]
Definitely mystified about how/where this could be happening (this is the first report of this we've seen and we have thousands of people using Jupyter w/ Quarto). Perhaps somehow related to Python v3.6? We have two uses of `isinstance()` in our codebase -- I've revised one of them here as a speculative workaround: https://github.com/quarto-dev/quarto-cli/commit/ed27f30d18c82b2f99490f4ae25005249a1ec892

**Comment by smc77** [comment]
Just to note: I pulled in your changes and it works now.  Thank you so much!
