### ISSUE TITLE
Missing caption causes later fig/table caption spacing issues.

### ISSUE THREAD

**Issue by m-clark** [quarto-dev/quarto-cli#9850]
### Bug description

I came across an issue where the table and figure captions were not spaced correctly from the table/figure number within a pdf document (book) - basically there was little or no space between the number and text of the header. This problem appears to have originated after a table that was given a label but no caption. Every subsequent table and figure then had the spacing problem. Adding the missing caption appears to fix the problem. 

I was able to reproduce with default settings as indicated. As near as I can tell, removing the chunk label, with or without a table cap, would not cause a problem with the subsequent figure caption

### Steps to reproduce

````
---
title: "Untitled"
format:
    pdf
---

```{r}
#| label: tbl-problem
gt::gtcars[1:5, 1:5] |> 
    gt::gt()
```

![Problem Image Spacing](img/gp.png)
````

vs. the following which renders the subsequent images and tables correctly

````
---
title: "Untitled"
format:
    pdf
---

```{r}
#| label: tbl-problem
#| tbl-cap: A TABLE!
gt::gtcars[1:5, 1:5] |> 
    gt::gt()
```

![Problem Image Spacing Gone!](img/gp.png)
````

### Expected behavior

<img width="719" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/4720569/7bcd5aa7-8ccd-4fe0-8be0-c38cfe9d32cb">

### Actual behavior

<img width="762" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/4720569/b440f008-fae8-4623-9b9e-cdee4f8e643a">

### Your environment

- IDE: VS Code 1.89.1
- MacOS Ventura 13.4

### Quarto check output

Quarto 1.5.6
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.6
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/micl/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /Users/micl/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: abbvie-pro, cta-ts, 1848takeup, test-quarto-conda, python3

[✓] Checking Jupyter engine render....OK

(-) Checking R installation...........── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ ::() masks 
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘scales’

The following object is masked from ‘package:purrr’:

    discard

The following object is masked from ‘package:readr’:

    col_factor

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/micl/Rlib
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
This is a clear bug.

We're explicitly emitting a \captionsetup{labelsep=none} in captionless floats:

https://github.com/quarto-dev/quarto-cli/blob/3c6f484e351acf1eb981bfb129d142d08f11c2e8/src/resources/filters/customnodes/floatreftarget.lua#L345-L363

It's not clear that this is necessary: commenting out that block appears to fix the bug.

![Uploading image.png…]()

**Comment by cscheid** [comment]
Thanks for the report - this is fixed on `main` now.

**Comment by m-clark** [comment]
Thanks for your efforts!
