### ISSUE TITLE
Vertical Alignment of Subfigures not working in PDFs

### ISSUE THREAD

**Issue by Mavoort** [quarto-dev/quarto-cli#9861]
### Bug description

I would like to create a PDF document that contains a figure environment with two images side by side.
The images are of different sizes and should be vertically aligned using `layout-valign=bottom`, as described in the [documentation](https://quarto.org/docs/authoring/figures.html#vertical-alignment).

Unfortunately this doesn't work, because this feature doesn't seem to be supported for LaTeX documents.

### Steps to reproduce

```` quarto
---
format:
    pdf:
        keep-tex: true
---

# Vertical Alignment

::: {layout="[30, 70]" layout-valign="bottom"}
![Lion](lion.jpg)

![Bird](bird.jpg)
:::
````

### Expected behavior

The two images should be vertically aligned, as described in [the documentation](https://quarto.org/docs/authoring/figures.html#vertical-alignment):

![expected_result](https://github.com/quarto-dev/quarto-cli/assets/46296384/97f60224-e8ed-4239-b12b-c46a10d933e3)

### Actual behavior

The two images not aligned:
![actual_result](https://github.com/quarto-dev/quarto-cli/assets/46296384/a0a53d70-fc94-44a8-b450-d3467db8e656)

In fact, the `layout-valign` attribute is completely ignored; the LaTeX-code that is generated is exactly the same.

### Your environment

- OS: Ubuntu 23.10 (mantic)

### Quarto check output

````bash
Quarto 1.4.554
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.554
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /usr/bin/python3
      Jupyter: 5.3.1
      Kernels: julia-1.10, python3, sagemath

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib/R
      LibPaths:
        - /home/marcel/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK

````

**Comment by Mavoort** [comment]
The problem seems to come from the fact that Quarto uses `miniframe` to create subfigures, whereas [the recommended way](https://tex.stackexchange.com/a/119985) is to use `subfigure` environments.

This is the LaTeX code generated by Quarto:
```latex
\begin{figure}
    \begin{minipage}{0.30\linewidth}
        \begin{figure}[H]
            {   
                \centering \includegraphics{lion.jpg}
            }   
            \subcaption{Lion}
        \end{figure}
    \end{minipage}
    \begin{minipage}{0.70\linewidth}
        \begin{figure}[H]
            {   
                \centering \includegraphics{bird.jpg}
            }   
            \subcaption{Bird}
        \end{figure}
    \end{minipage}
\end{figure}
```
And this is how it would work correctly:
```latex
\begin{figure}[H]
    \begin{subfigure}{0.30\linewidth}
        \centering
        \includegraphics{lion.jpg}
        \caption{Lion}
    \end{subfigure}
    \hfill
    \begin{subfigure}{0.70\linewidth}
        \centering
        \includegraphics{bird.jpg}
        \caption{Bird}
    \end{subfigure}
\end{figure}
```

**Comment by cderv** [comment]
I believe this is a duplicated of this one 
* https://github.com/quarto-dev/quarto-cli/issues/9109
