### ISSUE TITLE
`page-layout: full`, our two-column setup, and `code-tools: true` interact badly

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#987]
It looks like there’s some bad interaction between `page-layout: full`, our two-column setup, and `code-tools: true`. Evidence:

- the bootstrap buttons in [this page](https://quarto.org/docs/interactive/ojs/examples/layout.html
) don't work.
- the bootstrap buttons in [this page](https://quarto.org/docs/interactive/ojs/examples/penguins.html) _do_ work.
- if we take the `layout.qmd` file that generates the first page and render it outside of a website (so we don't get a two-column layout), then the buttons work again.

**Comment by dragonstyle** [comment]
This got fixed somewhere along the way and we just needed to re-generate the site! Should be all set now.
