### ISSUE TITLE
`.webp` size bug when rendering to PDF

### ISSUE THREAD

**Issue by xmaxrayx** [quarto-dev/quarto-cli#9876]
### Bug description

I can't use `.webp` picture format when exporting to `PDF` but it works with `HTML`.

### Steps to reproduce

1. make general quarto file
2. use any `.webp` picture
3. `quarto preview test.qmd --to pdf --no-watch-inputs --no-browse`

### Expected behavior

convert the `webp` file automatically if PDF/Latex doesn't support it (idk)

### Actual behavior

````
LaTeX Error: Cannot determine size of graphic in images/67f6d2c4-1107-49eb-82f8-50f04b1e8f6c.webp (no BoundingBox).
````
whole error
````
Max_Laptop@DESKTOP-89LE5JL MINGW64 ~/Documents/Quarto/test
$ quarto preview test.qmd --to pdf --no-watch-inputs --no-browse
pandoc
  to: latex
  output-file: test.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  editor: visual
  title: GUMI


Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages
ERROR:
compilation failed- error
LaTeX Error: Cannot determine size of graphic in images/67f6d2c4-1107-49eb-82f8-50f04b1e8f6c.webp (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.228 ...7f6d2c4-1107-49eb-82f8-50f04b1e8f6c.webp}


see C:\Users\Max_Laptop\Documents\Quarto\test\test.log for more information.
````

### Your environment

RStudio
2024.04.1 Build 748
© 2009-2024 Posit Software, PBC
"Chocolate Cosmos" Release (3ada7c6d, 2024-05-07) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.1+748 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.5.40 (C:/Users/Max_Laptop/AppData/Local/Apps/Quarto/bin/quarto.exe)

### Quarto check output

````
$ quarto check
Quarto 1.5.40
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.40
      Path: C:\Users\Max_Laptop\AppData\Local\Apps\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.06
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Max_Laptop\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: C:/Users/Max_Laptop/AppData/Local/Programs/Python/Python312/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.4.0
      Path: C:/PROGRA~1/R/R-44~1.0
      LibPaths:
        - C:/Users/Max_Laptop/AppData/Local/R/win-library/4.4
        - C:/Program Files/R/R-4.4.0/library
      knitr: 1.47
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK
````

**Comment by xmaxrayx** [comment]
file:


---
title: "GUMI"
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

```{}
```

# Character licenses

![GUMI license](images/2024-06-04%2009.02.59%20www.ssw.co.jp%20f2c71c1151c0.png){fig-alt="GUMI license picture" width="661" height="2243"}

icecream

:   ice cream is a an iceream

# dfdfdfdffdddddddddd

## ahgaghaghghagha

### lalal;al;al;al;al;

#### skskskkl

##### kakakak 

###### akakaklkla 

-   sss

-   sss

    -   sss

    -   sss

        -   sss

            -   s

                -   s

                    -   s

                        -   s

                            -   s

                                -   s

                                    -   s

                                        -   s

![](images/0a6591d7d1c959aaf1f0fead9fdd1e235981c5cf_full.jpg){width="61"}

ddddd ![](images/00017-4011788507.png){width="20"}sssssssssssssssss![](images/0a6591d7d1c959aaf1f0fead9fdd1e235981c5cf_full-01.jpg){width="22"} ggg ![](images/67f6d2c4-1107-49eb-82f8-50f04b1e8f6c.webp){width="33"} sss

loool

**Comment by cscheid** [comment]
That's not a bug.

Not all file formats are supported in PDF, and webp is not one of them.
