### ISSUE TITLE
Blog post: Beautiful tables in Typst 

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#9882]
* Non-technical, more a showcase of tables that look good in HTML and now also look good in PDF via Typst
* A paragraph that give a little detail and links to docs
* At least one kable/pandas example 
* gt/ Great_tables beautiful examples

**Comment by gordonwoodhull** [comment]
Closed by https://github.com/quarto-dev/quarto-web/pull/1219
