### ISSUE TITLE
Flag to turn off Typst CSS

### ISSUE THREAD

**Issue by gordonwoodhull** [quarto-dev/quarto-cli#9885]
There should really be a way to turn this off, at least so that people can diagnose if it is doing something weird.

Something like

````qmd
---
format:
  typst:
    typst-css: false
---
````

with default `true`.

Currently I don't see any need to turn it on/off within a document e.g. with fenced divs.

**Comment by cderv** [comment]
We should definitely add this ! 

Naming is hard. For the HTML table processing, we went with 
````yaml
format:
	html:
		html-table-processing: none
````

I don't remember the reason for not using `false` 🤔 It seems ok to use `false`

However, the name is quite explicit and I like that - I find it clearer to user and avoid any potential option clash in the future

**Comment by cscheid** [comment]
> I don't remember the reason for not using `false` 🤔 It seems ok to use `false`

The idea was that `none` implies a future refinement of the feature to other settings, while `false` only lets you do `true` afterwards (without a bigger schema change at least)

**Comment by gordonwoodhull** [comment]
Okay I'll think of a longer, more specific name. Maybe something like `typst-translate-css-properties`.

This feature is adjacent to
* `html-table-processing` 
* (new) `html-pre-tag-processing`
and somewhat reliant on them in normal usage. 

But it's really nothing like them - it's a Lua filter that takes css properties and produces typst properties.

**Comment by mcanouil** [comment]
Would `typst-css-processing` not work?

**Comment by gordonwoodhull** [comment]
It's not perfect, because it's not the same kind of processing, but it'll do just fine!

**Comment by mcanouil** [comment]
I thought that `format-what-processing` was the scheme^^

**Comment by gordonwoodhull** [comment]
The other flags enable parsing of html into the Pandoc AST.

This one enables translation of CSS (attributes and) properties into Typst properties.

I guess following the scheme it would be `css-properties-processing` with default `translate` and also settable to `none`.

**Comment by mcanouil** [comment]
Hum, I would indeed drop the "typst" if it's a Typst specific option that is falling under:

```
format:
  typst:
    css-property-processing: non
 ```
 
or even (is there other kind of css other than "property")
 
```
format:
  typst:
    css-processing: non
```
 
I guess the name depends a bit on the future of this feature for other formats if there is such future.

**Comment by gordonwoodhull** [comment]
I think `css-property-processing` is specific enough without being a burden.

Who knows, maybe we will have `css-stylesheet-processing` in the future. (I hope not! 🤣) 

In theory someone could write a `css-property-processing` Lua filter for latex or docx, so I agree it makes sense to drop the `typst-`.

You have shared some examples and have some extensions which do this kind of thing - the only difference is that this uses [typst property output attributes on Pandoc](https://pandoc.org/typst-property-output.html) instead of directly manipulating the AST.

**Comment by mcanouil** [comment]
I agree and it does allow to eventually extend this to other formats in the future without headache.
