### ISSUE TITLE
Link RSS feed from `posts.qmd` rather than `index.qmd`

### ISSUE THREAD

**Issue by shamindras** [quarto-dev/quarto-cli#989]
Many thanks for creating this wonderful `quarto` package. I have switched [my blog](https://www.shamindras.com/posts.html) from [`distill`](https://rstudio.github.io/distill/blog.html) to quarto.

I wanted to setup an RSS feed per the [quarto instructions](https://quarto.org/docs/websites/website-blog.html#rss-feed). Since my main [`index.qmd`](https://github.com/shamindras/ss_personal_quarto_blog/blob/main/index.qmd) is a title page, and my blog posts are contained in a separate [`posts.qmd`](https://github.com/shamindras/ss_personal_quarto_blog/blob/main/posts.qmd) file, I added the `feed : true` change in the `posts.qmd` file instead of the `index.qmd`, as seen [here](https://github.com/shamindras/ss_personal_quarto_blog/blob/main/posts.qmd#L10). I then added in [this line](https://github.com/shamindras/ss_personal_quarto_blog/blob/main/_quarto.yml#L25-L26) in `_quarto.yml`.

However the [rendered RSS feed](https://www.shamindras.com/index.xml) gives a `404 Error`. Is there a way for me to get this working for my blog given my setup?

**Comment by dragonstyle** [comment]
The feed file uses the name of the page it appears on, in this case:

https://www.shamindras.com/posts.xml

That appears in the head of the HTML in a meta tag so feed readers will correctly discover it when viewing your blog.

**Comment by shamindras** [comment]
> The feed file uses the name of the page it appears on, in this case:
> 
> [shamindras.com/posts.xml](https://www.shamindras.com/posts.xml)
> 
> That appears in the head of the HTML in a meta tag so feed readers will correctly discover it when viewing your blog.

Thanks for the clarifications. The `404` error when clicking the RSS link is undesirable, especially for a new user.
Is there a way to set up things in quarto to avoid this error in the first place?

**Comment by dragonstyle** [comment]
Just change the content you added in `quarto.yml` here:

https://github.com/shamindras/ss_personal_quarto_blog/blob/main/_quarto.yml#L25-L26

to point to `posts.xml` instead and you should be good to go!
