### ISSUE TITLE
ERROR: Book chapter 'abstract.qmd' not found

### ISSUE THREAD

**Issue by GraceEMc** [quarto-dev/quarto-cli#9893]
### Bug description

I am running into the error code below when rendering a document. I have tried reinstalling Quarto and RStudio but still getting the error. It doesn't seem specific to the document - have tried rendering a blank doc and still get the issue. 
Any ideas on how to fix/troubleshoot?

==> quarto preview test.qmd --to html --no-watch-inputs --no-browse

ERROR: Book chapter 'abstract.qmd' not found

Stack trace:
    at throwInputNotFound (file:///C:/Users/#####/AppData/Local/Programs/Quarto/bin/quarto.js:90696:19)
    at findInputs (file:///C:/Users/#####/AppData/Local/Programs/Quarto/bin/quarto.js:90727:17)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async findChapters (file:///C:/Users/#####/AppData/Local/Programs/Quarto/bin/quarto.js:90739:13)
    at async bookRenderItems (file:///C:/Users/####/AppData/Local/Programs/Quarto/bin/quarto.js:90742:5)
    at async Object.bookProjectConfig [as config] (file:///C:/Users/####/AppData/Local/Programs/Quarto/bin/quarto.js:90648:25)
    at async projectContext (file:///C:/Users/####/AppData/Local/Programs/Quarto/bin/quarto.js:72807:37)
    at async Command.fn (file:///C:/Users/####/AppData/Local/Programs/Quarto/bin/quarto.js:98091:25)
    at async Command.execute (file:///C:/Users/####/AppData/Local/Programs/Quarto/bin/quarto.js:8104:13)
    at async quarto (file:///C:/Users/####/AppData/Local/Programs/Quarto/bin/quarto.js:115004:5)

### Expected behavior

The document should render as a pdf or html

### Actual behavior

nothing and the error is output

### Your environment

RStudio
2024.04.1 B
Windows 10 Enterprise

### Quarto check output

Quarto 1.4.555
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.555
      Path: C:\Users\a1846236\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\a1846236\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.7
      Path: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python39_64/python.exe
      Jupyter: 5.3.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.3
      Path: C:/PROGRA~1/R/R-42~1.3
      LibPaths:
        - C:/Users/a1846236/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.3/library
      knitr: 1.45
      rmarkdown: 2.26

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Could you share a **small self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository? The goal is to make it as easy as possible for us  to recreate your problem so that we can fix it: please help us help you! Thanks.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by cderv** [comment]
> ==> quarto preview test.qmd --to html --no-watch-inputs --no-browse

> ERROR: Book chapter 'abstract.qmd' not found

Are you in a book project context ? Or are you not expected to be in one ? 

You are not mentioning, and it is as if you are trying to render a single document but got this unexpected message; 

Just a note to check: If there is a `_quarto.yml` somewhere in the directory tree up from your `test.qmd` document, quarto may have caught it. 

Just a wild guess that would be worth verifying.

**Comment by GraceEMc** [comment]
ahh right, I was in a book project (although I wasn't rendering the book) and had deleted the abstract.qmd file without updating the _quarto.yaml. Thank you!
