### ISSUE TITLE
left sidebar has scrollbar even though content is not overflowing

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#99]
Looking at the [quarto.org](https://quarto.org) site we see that the left sidebar has a scrollbar (both x and y), even though it should not need on:
![image](https://user-images.githubusercontent.com/17450586/131641580-48a25169-7c84-42ed-95bc-c1b1c7ad3753.png)

I tried adding:

```
/*-- scss:rules --*/ 
.overflow-scroll {
  overflow: auto !important;
}
```

to a custom scss theme, but this seems to get overridden by bootstrap once loaded:

![image](https://user-images.githubusercontent.com/17450586/131641547-2ceeecc7-6f4f-4f3c-87d3-2d9886cd8096.png)

**Comment by jmbuhr** [comment]
hm, there was an earlier issue (https://github.com/quarto-dev/quarto-cli/issues/25), so maybe this is expected? Though the bootstrap website itself does it differently: https://getbootstrap.com/docs/5.1/getting-started/introduction/ , the scrollbar appears only when you expand enough sections.

**Comment by dragonstyle** [comment]
Thanks for reporting this issue. It is indeed unintended and we should have a fix available shortly!

**Comment by dragonstyle** [comment]
This should be resolved now- thanks for letting us know!
