### ISSUE TITLE
Book docs state that headings are unnumbered in index.qmd by default (false or misleading)

### ISSUE THREAD

**Issue by kkaja123** [quarto-dev/quarto-cli#9908]
### What would you like to do?

Report an issue on quarto.org

### Description

Page in question: https://quarto.org/docs/books/book-structure.html#overview

Quoted text:
>This page should include the preface, acknowledgements, etc. and headings in the `index.qmd` file are unnumbered by default.

This statement seems to suggest that the `{.unnumbered}` class is redundant for headings in the `index.qmd`, but if this isn't used, the headings **are** numbered by default.

Example where `.unnumbered` is needed for the index: https://github.com/jjallaire/visualization-curriculum/blob/master/index.md?plain=1#L1

Possibly, the original intent of this statement was to imply that users *typically* make their index headings unnumbered. If this is the case, then the statement should be reworded to avoid the implication that there's a hidden behavior to `index.qmd` headings and it should probably link to the section that explains how to make chapters unnumbered (https://quarto.org/docs/books/book-structure.html#chapter-numbers). Otherwise, the statement could be removed completely.

**Comment by cwickham** [comment]
Indeed, even our book template using `quarto create project book` uses `{.unnumbered}` on headings in `index.qmd`.

Thanks for the report @kkaja123
