### ISSUE TITLE
Documentation updates for "Manifest" work

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#9909]
Placeholder for documentation required for 1.5 changes to "Manifest".

@cscheid I don't understand enough here to know what the documentation implications are. 

May be related to https://github.com/quarto-dev/quarto-cli/issues/9462

**Comment by cscheid** [comment]
PR is up: https://github.com/quarto-dev/quarto-web/pull/1223

**Comment by cderv** [comment]
PR was merged
