### ISSUE TITLE
Apparent Incorrect Sass File Merge

### ISSUE THREAD

**Issue by cadojo** [quarto-dev/quarto-cli#9911]
### Bug description

I have a custom theme file that I'm using for a website. The theme is forked from one of the official Quarto themes, with color variables overridden to new values.

I then have a second Sass file that sets variables, such as `$navbar-fg`. I want to set `$navbar-fg` to one of the colors defined in the first theme file, e.g. `$dark`, but when I do I get an error saying that `$dark` is not recognized. 

My website source is available [here](https://github.com/cadojo/loopy.codes/tree/new-site).

Also, I'm trying to set the color of `$navbar-fg` and others because the computed navbar color is too light to be visible in the "light mode" of the site, in case that's also a "bug" :)

### Steps to reproduce

```
gh repo clone cadojo/loopy.codes -- --branch new-site
cd loopy.codes 
quarto preview
```

```
Cloning into 'loopy.codes'...
remote: Enumerating objects: 1661, done.
remote: Counting objects: 100% (1049/1049), done.
remote: Compressing objects: 100% (499/499), done.
remote: Total 1661 (delta 471), reused 977 (delta 422), pack-reused 612
Receiving objects: 100% (1661/1661), 25.72 MiB | 23.19 MiB/s, done.
Resolving deltas: 100% (669/669), done.
Preparing to preview
[1/2] index.md
ERROR: Theme file compilation failed:

Error: Undefined variable.
     ╷
1043 │ $navbar-fg: $dark;
     │             ^^^^^
     ╵

Stack trace:

Error: Undefined variable.
     ╷
1043 │ $navbar-fg: $dark;
     │             ^^^^^
     ╵
    at dartCommand (file:///Applications/quarto/bin/quarto.js:42806:15)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async dartCompile (file:///Applications/quarto/bin/quarto.js:42768:5)
    at async compileWithCache (file:///Applications/quarto/bin/quarto.js:42997:17)
    at async compileSass (file:///Applications/quarto/bin/quarto.js:42858:12)
    at async resolveSassBundles (file:///Applications/quarto/bin/quarto.js:65208:27)
    at async resolveExtras (file:///Applications/quarto/bin/quarto.js:69234:18)
    at async runPandoc (file:///Applications/quarto/bin/quarto.js:68748:24)
    at async renderPandoc (file:///Applications/quarto/bin/quarto.js:70046:26)
    at async Object.onRender (file:///Applications/quarto/bin/quarto.js:77266:36)
```

### Expected behavior

Sass variables in `latte.scss` (and `mocha.scss`) are visible in `light.scss` (and `dark.scss`).

### Actual behavior

Runtime error that states that previously defined colors, like `$dark`, are not recognized. 

### Your environment

- IDE: VSCode
- MacOs 14.5

### Quarto check output

```bash
Quarto 1.4.554
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.554
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/joey/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: 5.7.2
      Kernels: julia-1.10, julia-1.9, rust

      NOTE: No Jupyter kernel for Python found

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
Your mocha.scss does not respect the format: https://quarto.org/docs/output-formats/html-themes.html#theme-options

**Comment by cderv** [comment]
I believe the comments are ok: https://github.com/cadojo/loopy.codes/blob/new-site/_style/mocha.scss#L1

So probably something else. I'll try to reproduce base on your branch

**Comment by cscheid** [comment]
(I'm going to go ahead and close this one.)

**Comment by cadojo** [comment]
Yes thank you! Funny, I'm 99% sure I read from an old version of the Quarto documentation from Google, because I definitely read the documentation example somewhere in the link you just sent. 

I corrected the order and things work perfectly again. Thanks for your help!

**Comment by cderv** [comment]
We fixed the example in the doc - it was a bad example we found some time ago, and we did not correct it in every places. It is correctly modified now. 

Thanks !
