### ISSUE TITLE
GitHub Pages doesn't update html by ipywidgets

### ISSUE THREAD

**Issue by gianfa** [quarto-dev/quarto-cli#9917]
### Bug description

Hello,
The following ipywidgets-based code is supposed to create a table that is interactively filtered according to what you select as a name from a dropdown menu.
When I render it as a local preview, I get the desired behavior; while when I publish it to GH Pages the table is not updated when I select an item from dropdown.
Am I doing something wrong?

[UPDATE]
What is written above refers to the preview of `{python}` cell.
Rendering by `quarto render`, I realize that **even in my local broswer**, the table is not updated.

### Steps to reproduce

```markdown
---
title: "Interactive Example"
format: html
---

```{python}
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, HTML

# Simple example dataframe
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'value': [10, 20, 30, 40, 50]
}
df = pd.DataFrame(data)

# Create a dropdown menu for name filter
name_dropdown = widgets.Dropdown(
    options=['All'] + df['name'].unique().tolist(),
    value='All',
    description='Name:',
    style={'description_width': 'initial'}
)

# Filter function
def filter_dataframe(name):
    if name == 'All':
        filtered_df = df
    else:
        filtered_df = df[df['name'] == name]
    display(HTML(filtered_df.to_html(index=False)))

# Link the widget to the function
out = widgets.interactive_output(filter_dataframe, {'name': name_dropdown})

# Display the widget and the output
display(name_dropdown, out)

```

### Expected behavior

Selecting an item from the dropdown menu should cause the table to update by filtering the names

### Actual behavior

Selecting an item from the dropdown menu will not update the table

### Your environment

- VSCode 1.89.1
- MacOs 14.1
- Quarto 1.4.555
- Python 3.10.13
- Ipykernel 6.29.4

### Quarto check output

```bash



[✓] Checking LaTeX....................OK
      Tex:  (not detected)


(|) Checking basic markdown render....
[✓] Checking basic markdown render....OK


(|) Checking Python 3 installation....
[✓] Checking Python 3 installation....OK
      Version: 3.10.14
      Path: /home/<my_path>/bin/python3
      Jupyter: 5.7.2
      Kernels: python3


(|) Checking Jupyter engine render....
[✓] Checking Jupyter engine render....OK


(|) Checking R installation...........
[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by cscheid** [comment]
This is not a bug. Interactive widgets are not supported in Quarto, because they require a running Python process. Where would your Python `filter_dataframe` execute if the page were on Github Pages?

Consider using Shiny for Python (with a server that supports it), or shinylive so that Python code is compiled to WASM.

**Comment by cscheid** [comment]
In the future, if you have "Am I doing something wrong?" in your bug report, please consider starting a discussion first.
