### ISSUE TITLE
`format-resources` now recurse in directory and copy files to root instead of the directory

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#9918]
## Originally discussed in https://github.com/quarto-dev/quarto-cli/discussions/9874

<div type='discussions-op-text'>

<sup>Originally posted by **ramiromagno** June  5, 2024</sup>
### Description

How to avoid recurse behavior on directories supplied in `format-resources:`?

```
      format-resources:
        - wiley-ndj-v5
        - _environment
```

`wiley-ndj-v5/` is a directory with many files and subdirectories. I would like Quarto not to put everything at the root of the project but just the directory `wiley-ndj-v5/`. Is there a way?

My plan is then to use `_environment` as:

```
TEXINPUTS="wiley-ndj-v5"
```

Related to: https://github.com/quarto-dev/quarto-cli/discussions/6526.</div>

## Context 

It seems like an issue following a change we made... 

File globbing now works in format resources following this change 7d95eb886f161a4cee5572b49b191ce1b084f3e7 to solve #6241

https://github.com/quarto-dev/quarto-cli/blob/e09ae925dd92950394ca7eb2376ca0e3fba34bc5/src/extension/extension.ts#L724-L736 

And this is a 1.4 regression compared to 1.3, because now `format-resources` does not accept directory anymore. This has a big impact on some template. 

Using v1.4.516 will copy the directory and v1.4.517 and later will copy the file inside the directory. 

Introducing the glob support was done with the default smart globbing support 
https://github.com/quarto-dev/quarto-cli/blob/e09ae925dd92950394ca7eb2376ca0e3fba34bc5/src/core/path.ts#L248-L266

which makes now a directory become a list of files 

so 

````yaml
format-resources:
	- wiley-njd-v5/
````
is now equivalent to listing every files in `format-resources`

I think we should use strict mode here to solve this regression.

**Comment by camelusminimus** [comment]
If I may add my thanks (after the fact) for this change. I ran into it whenever the change was made, and was deeply annoyed by it, but thought (from reading the changelog etc.) that it _was_ the intended behaviour (i.e. to clutter up my project directory with stuff that I defined as format resources, Reading the description of how that should work with latex project could give one the impression...i think..)

`git clean` was the only thing keeping me halfway sane...

Now to revert the changes I made to make my internal style work with the (now fixed) bug ;-)
