### ISSUE TITLE
Quarto, Rstudio server and Latex library

### ISSUE THREAD

**Issue by aetiologicCanada** [quarto-dev/quarto-cli#992]
I have Rstudio running as a workstation and as Rstudio server on (the same) Ubuntu 20 laptop.  Current version of Rstudio, markdown, tinytex, quarto.  I can generate PDFs from Rmarkdown and Quarto in Rstudio workstation, but attempts to generate PDFs from Rstudio Server fail with: 
```

compilation failed- no matching packages
LaTeX Error: File `scrartcl.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.10 \usepackage
                {amsmath,amssymb}

```
I would welcome suggestions for fixing this.

**Comment by bryce-carson** [comment]
I experience the same error on RStudio community workstation.

RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

**Comment by cderv** [comment]
> LaTeX Error: File `scrartcl.cls' not found.

This is usually a missing LaTeX dependency. Quarto uses by default `koma-script` as explained (https://quarto.org/docs/output-formats/pdf-basics.html#document-class) and this LaTeX package needs to be available. It seems for you both it is not. 

When using TeX Live distribution (like TinyTeX for example [which Quarto recommands](https://quarto.org/docs/output-formats/pdf-basics.html#prerequisites) ), Quarto will try to auto install missing packages. 

However, on some system with no CTAN mirror or not using TeX Live or using system package manager install for example, the installation of packages should be do manually. 

So here you can either: 

* Install `koma-script`
* change `documentclass` as explained in the doc (but you may ran into similar issues with other packages required)

Please both check your LaTeX installation and available tools to confirm this. 

Hope it helps.

**Comment by bryce-carson** [comment]
@cderv, on my system, `koma-script` is already installed using the TinyTeX interface in R. Quarto then attempts to reinstall the package, because it cannot find it for some reason. The installation fails.

That is an endless loop. Install outside Quarto document compilation (ie, manually call `tlmgr_install("koma-script")`, which finishes sucessfully). Try to compile the document. The document does not compile because `scrartcl.cls` is not found, and then an installation failure of `koma-script` within the process causes an abnormal exit.

```
> tlmgr_install("koma-script")
tlmgr update --all --self
tlmgr install koma-script
TeX Live 2022 is frozen
and will no longer be routinely updated.  This happens when a new
release is made, or will be made shortly.

For general status information about TeX Live, see its home page:
https://tug.org/texlive

tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
tlmgr install: package already present: koma-script
```

```
output file: Report.knit.md

pandoc 
  to: latex
  output-file: Report.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Report on population growth
  author: Bryce Carson
  editor: visual
  
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
finding package for scrartcl.cls
> 1 package to install
> installing koma-script (1 of 1)
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
finding package for scrartcl.cls

compilation failed- package installation error
LaTeX Error: File `scrartcl.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.10 ^^M
         

see Report.log for more information.
```

🌳🪵 [Report.log](https://github.com/quarto-dev/quarto-cli/files/10984382/Report.log)

**Comment by bryce-carson** [comment]
I installed the Quarto tool from Brew casks (`brew install --cask quarto`), then updated TinyTeX by running the following command.

```
╭─bryce@Tutankhamun.local ~
╰─➤  sudo quarto install tinytex
 ? tinytex is already installed. Do you want to update to v2023.03? (Y/n) › Yes

Updating TinyTeX from undefined to v2023.03
[✓] Downloading TinyTex v2023.03
Removing undefined
[✓] Removing directory
Installing v2023.03
[✓] Unzipping TinyTeX-v2023.03.tgz
[✓] Moving files
Finishing update
[✓] Verifying tlgpg support
[✓] Default Repository: https://mirrors.rit.edu/CTAN/systems/texlive/tlnet/
Update successful
```

After this update, _without_ restarting RStudio, I tried to render the Quarto document again. Below is the different output.

```
output file: Report.knit.md

pandoc 
  to: latex
  output-file: Report.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Report on population growth
  author: Bryce Carson
  editor: visual
  
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
finding package for tikzfill.image.sty
> 1 package to install
> installing tikzfill (1 of 1)
ERROR: tlmgr returned a non zero status code
You don't have permission to change the installation in any way,
specifically, the directory /Users/bryce/Library/TinyTeX/tlpkg/ is not writable.
Please run this program as administrator, or contact your local admin.
tlmgr: An error has occurred. See above messages. Exiting.
```

I understand what this error means, so I'll try rendering the document on the command line with privileges given to Quarto. That should _also_ use the updated TinyTeX (I'm really not sure why RStudio's Quarto reported a different TinyTeX version after updating).

```
╭─bryce@Tutankhamun.local ~/Desktop/bigData/Assignment Three
╰─➤  sudo quarto render Report.qmd                                                                                          1 ↵
Password:


processing file: Report.qmd
  |..............                                                        |  20%
  ordinary text without R code

  |............................                                          |  40%
label: unnamed-chunk-1
  |..........................................                            |  60%
  ordinary text without R code

  |........................................................              |  80%
label: unnamed-chunk-2
  |......................................................................| 100%
   inline R code fragments


output file: Report.knit.md

pandoc
  to: latex
  output-file: Report.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Report on population growth
  author: Bryce Carson
  editor: visual

running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages
finding package for tikzfill.image.sty
> 1 package to install
> installing tikzfill (1 of 1)
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode


Output created: Report.pdf
```

It seems that having whichever version of TinyTeX, R, Rstudio, and Quarto on my machine caused problems.

Updating TinyTeX using Quarto seems to have worked.

**Comment by cderv** [comment]
>  The document does not compile because scrartcl.cls is not found, and then an installation failure of koma-script within the process causes an abnormal exit.

I would have said this is a hint that another installation of TeX Live is available (two TinyTeX install or one TinyTeX and one system TeX Live  or else ...) 

> I understand what this error means, so I'll try rendering the document on the command line with privileges given to Quarto. That should also use the updated TinyTeX (I'm really not sure why RStudio's Quarto reported a different TinyTeX version after updating).

I don't know exactly how RStudio sever works but it seems it can't use your user installed TinyTeX. It is possible that RStudio server (worbench) run with a specific user and this won't have access to any user side tooling maybe. 

It seems you found the issue anyway. 

@dragonstyle do you think we could add a `quarto check tinytex` feature to give feedback on the installation and some info on what we expect (writable for auto installation, koma-script for default PDF rendering, ...) ? 
This would probably help diagnose issues. What do you think ?

**Comment by cderv** [comment]
> @dragonstyle do you think we could add a quarto check tinytex feature to give feedback on the installation and some info on what we expect (writable for auto installation, koma-script for default PDF rendering, ...) ?
This would probably help diagnose issues. What do you think ?

It seems @cscheid already open an feature request to track this idea https://github.com/quarto-dev/quarto-cli/issues/4845

**Comment by bambirombi** [comment]
In my case I had this error: LaTeX Error: File `tikzfill.image.sty' not found.
Installing texlive-pictures solved it.
