### ISSUE TITLE
Regression: Multi-part figures get stretched in recent versions

### ISSUE THREAD

**Issue by Robinlovelace** [quarto-dev/quarto-cli#9927]
### Bug description

Quarto creates outputs in which figures are distorted with `layout-ncol` values above one, e.g. in the following [reproducible](https://github.com/geocompx/geocompy) example:

```{python}
#| label: fig-raster-slope
#| fig-cap: Slope and aspect calculation from a DEM
#| layout-ncol: 3
#| fig-subcap: 
#| - Input DEM
#| - Slope (degrees)
#| - Aspect (degrees)
# Input DEM
src_srtm = rasterio.open('output/srtm_32612.tif')
srtm = src_srtm.read(1).astype(float)
srtm[srtm == src_srtm.nodata] = np.nan
fig, ax = plt.subplots()
rasterio.plot.show(src_srtm, cmap='Spectral_r', ax=ax)
fig.colorbar(ax.imshow(srtm, cmap='Spectral_r'), ax=ax);
# Slope
src_srtm_slope = rasterio.open('output/srtm_32612_slope.tif')
srtm_slope = src_srtm_slope.read(1)
srtm_slope[srtm_slope == src_srtm_slope.nodata] = np.nan
fig, ax = plt.subplots()
rasterio.plot.show(src_srtm_slope, cmap='Spectral_r', ax=ax)
fig.colorbar(ax.imshow(srtm_slope, cmap='Spectral_r'), ax=ax);
# Aspect
src_srtm_aspect = rasterio.open('output/srtm_32612_aspect.tif')
srtm_aspect = src_srtm_aspect.read(1)
srtm_aspect[srtm_aspect == src_srtm_aspect.nodata] = np.nan
fig, ax = plt.subplots()
rasterio.plot.show(src_srtm_aspect, cmap='twilight', ax=ax)
fig.colorbar(ax.imshow(srtm_aspect, cmap='twilight'), ax=ax);
```

### Steps to reproduce

See code chunk above.

To reproduce, follow steps here: https://github.com/geocompx/geocompy

You can also reproduce in a devcontainer hosted on GitHub: 

[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=447558863)

From there try typing `quarto preview` in the terminal.

### Expected behavior

It should look like this, as it did in previous versions of Quarto:

![image](https://github.com/quarto-dev/quarto-cli/assets/1825120/e1e4a020-efd4-4856-912a-d9ce4956ba8d)

Source: https://github.com/geocompx/geocompy/issues/230#issue-2312556674

### Actual behavior

The figures are stretched

### Your environment

- IDE: VS Code. This has nothing to do with the IDE though.

### Quarto check output

```
quarto check
Quarto 1.5.41
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.41
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /usr/local/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by Robinlovelace** [comment]
See work-around here: https://github.com/geocompx/geocompy/pull/233

Follow-on question, are there any good work-arounds on the quarto side?

**Comment by mcanouil** [comment]
Thanks for the report.

Could share a small self-contained example as you seem to imply the code cell options snippet (not reproducible) is enough?

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by Robinlovelace** [comment]
OK will try to create a minimal reprex..

**Comment by mcanouil** [comment]
Thanks!

**Comment by Robinlovelace** [comment]
> OK will try to create a minimal reprex..

Here you go:

````

---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
#| layout-ncol: 3

import rasterio
import numpy as np
import matplotlib.pyplot as plt
from rasterio.plot import show

# Example raster dataset: SRTM

src_srtm = rasterio.open('https://github.com/geocompx/geocompy/raw/main/data/srtm.tif')
srtm = src_srtm.read(1).astype(float)
srtm[srtm == src_srtm.nodata] = np.nan
fig, ax = plt.subplots()
rasterio.plot.show(src_srtm, cmap='Spectral_r', ax=ax)

```

The end.

````

**Comment by Robinlovelace** [comment]
Try rendering that doc. You will see something like this, if the bug persists on your computer (figure should be square):

![image](https://github.com/quarto-dev/quarto-cli/assets/1825120/b1dc4e05-0ffb-428c-b831-0a4ba189e101)

I see no good reason for Quarto to stretch figures. As per image above, it looked fine without the stretching.

**Comment by Robinlovelace** [comment]
How it should look is shown in the image in the previous post: https://github.com/quarto-dev/quarto-cli/issues/9927#issue-2341627209

That is how it *does* look on older versions of Quarto before this regression I think. We're not sure when the regression was introduced.

**Comment by cscheid** [comment]
You've requested `layout-ncol: 3` here. What did you expect to happen?

**Comment by mcanouil** [comment]
You titled "regression", but compared to which version?

**Comment by mcanouil** [comment]
The Python code (or Jupyter) emits the images with an absolute size, so no resizing can happen responsively.
`layout-ncol` makes a constraint on the width but Quarto has no way to know what kind of content there is: it can be as simple as an image, but it can be a mix of anything thus you cannot also add a constraint on height.

If I set the height/width myself in your code:

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
format: html
engine: jupyter
keep-md: true
---

```{python}
#| layout-ncol: 3
import rasterio
import numpy as np
import matplotlib.pyplot as plt
from rasterio.plot import show

# Example raster dataset: SRTM

src_srtm = rasterio.open('https://github.com/geocompx/geocompy/raw/main/data/srtm.tif')
srtm = src_srtm.read(1).astype(float)
srtm[srtm == src_srtm.nodata] = np.nan
fig, ax = plt.subplots(figsize=(2, 2))
rasterio.plot.show(src_srtm, cmap='Spectral_r', ax=ax)

plt.show()
```

````

</td><td>

<img width="728" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/2ff85116-4871-4896-9d5e-db9dcc52ea86">

</td></tr>
</table>

If you look at the intermediate markdown the image look lke this:

```
![](index_files/figure-html/cell-2-output-1.png){width=207 height=188}
```

The same thing without computations:

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

````qmd
---
format: html
keep-md: true
---

::: {layout-ncol="3"}

![](https://placehold.co/450x450.png)

![](https://placehold.co/450x450.png)

![](https://placehold.co/450x450.png)

:::

---

::: {layout-ncol="3"}

![](https://placehold.co/450x450.png){width=450 height=450}

![](https://placehold.co/450x450.png)

![](https://placehold.co/450x450.png)

:::

````

</td><td>

<img width="727" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/a85e6869-8b01-4446-ac10-9b4238c5652d">

</td></tr>
</table>

**Comment by Robinlovelace** [comment]
> You titled "regression", but compared to which version?

We're not sure when the regression was introduced.

**Comment by Robinlovelace** [comment]
> You've requested `layout-ncol: 3` here. What did you expect to happen?

I would expect the aspect ratio of the images not to altered, see the aspect ratio of the image below (zoomed in version of image in original post to highlight that this was also generated by Quarto):

![image](https://github.com/quarto-dev/quarto-cli/assets/1825120/b4bc6aa8-0f9a-4fd2-9862-479df2243a2e)

Source: https://github.com/geocompx/geocompy/issues/230#issue-2312556674

In terms of the version of Quarto that generates that expected non-stretched version, I'm not sure but Michael might. @michaeldorman do you know what version of Quarto generated the image shown above? Thanks all.

**Comment by mcanouil** [comment]
If you have the HTML, the Quarto version is written as metadata in it.

**Comment by Robinlovelace** [comment]
```diff
fig, ax = plt.subplots()
fig, ax = plt.subplots(figsize=(2, 2))
```

That looks like a good work-around. Would be great if the figures were not stretched, as seems to have happened in older versions of Quarto.

**Comment by cscheid** [comment]
I do see a behavior change from 1.3.450.

**Comment by cscheid** [comment]
This is interesting, though. In the "good" versions, Quarto is completely removing the `height` attribute from the image as provided. The `keep-md` output is:


````
---
format: html
engine: jupyter
keep-md: true
---


::: {#dda85de0 .cell layout-ncol='3' execution_count=1}
``` {.python .cell-code}
import rasterio
import numpy as np
import matplotlib.pyplot as plt
from rasterio.plot import show

# Example raster dataset: SRTM

src_srtm = rasterio.open('https://github.com/geocompx/geocompy/raw/main/data/srtm.tif')
srtm = src_srtm.read(1).astype(float)
srtm[srtm == src_srtm.nodata] = np.nan
fig, ax = plt.subplots()
rasterio.plot.show(src_srtm, cmap='Spectral_r', ax=ax)

plt.show()
```

::: {.cell-output .cell-output-display}
![](9927_files/figure-html/cell-2-output-1.png){width=443 height=411}
:::
:::
````

Note `{width=443 height=411}` specifically.

The HTML output we produce in `1.4.366` (the "good" version) has

```
<p><img src="9927_files/figure-html/cell-2-output-1.png" class="img-fluid" width="443"></p>
```

Note how the height attribute got dropped.

I think the fundamental problem here is that it's impossible for Quarto to properly handle existing sizing constraints on images inside a `layout-ncol` declaration.

In a vacuum, what would be desired outcome here? `layout-ncol:3` specifies the desire for three evenly-spaced columns, in which case each column has a max-width lower than the image. Because height is explicitly specified instead of aspect ratio, the web browser goes "cool, I'll keep the height while squeezing the width".

In 1.4.366, Quarto actively decides to drop the height of the images in a layout cell, see

https://github.com/quarto-dev/quarto-cli/blob/c5b6176d824aae87667f7925132e6638320f135e/src/resources/filters/layout/layout.lua#L132

which calls

https://github.com/quarto-dev/quarto-cli/blob/c5b6176d824aae87667f7925132e6638320f135e/src/resources/filters/layout/width.lua#L129-L135

Note how line 134 drops the height.

We'll fix this soon.

**Comment by Robinlovelace** [comment]
great job! Will look to install latest version to fix on our book also.

**Comment by Robinlovelace** [comment]
Any ideas of ETA when there will be a release with this patch? Just looking here https://github.com/quarto-dev/quarto-cli/releases

**Comment by Robinlovelace** [comment]
Hi @cscheid I'm sorry to report that the issue persists for us. As I said, it was not an issue in previous versions but it persists. Any suggestions to keep the aspect ratio unchanges please let us know. Happy to provide more details.

**Comment by Robinlovelace** [comment]
Fully reproducible example inside a devcontainer: 

- Click here: https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=447558863
- Open a terminal and run `quarto preview`
- As shown below I've tried on the latest version of Quarto 

```
quarto --version
1.5.47
```




![image](https://github.com/quarto-dev/quarto-cli/assets/1825120/b7b5883a-0e27-4ee0-9f4b-86e6cb00f225)

**Comment by Robinlovelace** [comment]
I've identified the cause here: subcaptions. Will open a new issue.
