### ISSUE TITLE
Insert anything on mac keyboards not working in quarto

### ISSUE THREAD

**Issue by ncjacquinot** [quarto-dev/quarto-cli#9959]
### Bug description

In mac on a azerty french keyboard, forward slashes are typed with " Shift + : " as the forward slash is above the colon

In order to use the inline "Insert Anything" in Quarto, I would theoretically need to press " Command + Shift + : " but this doesn't give the appropriate Insert Anything shortcut

When starting a new line, the regular " Shift + : " will work as intended and offer the "Insert Anything" shortcut

I think the shortcut hasn't been mapped properly for the French azerty keyboards

### Your environment

- IDE : RStudio 2024.04.2+764, R 4.4.0
- MacBook Air M2 MacOS Sonoma 14.4.1

### Quarto check output

(r-reticulate) Nicolass-MacBook-Air:these_med ncjacquinot$ quarto check
Quarto 1.4.555
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.555
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/ncjacquinot/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Users/ncjacquinot/.virtualenvs/r-reticulate/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

(r-reticulate) Nicolass-MacBook-Air:these_med ncjacquinot$

**Comment by cscheid** [comment]
It looks like you're describing something about either the VS Code extension or RStudio. This repository concerns the command-line `quarto` utility, which knows nothing about this:

> In order to use the inline "Insert Anything" in Quarto, I would theoretically need to press " Command + Shift + : " but this doesn't give the appropriate Insert Anything shortcut

You should either report to https://github.com/quarto-dev/quarto or https://github.com/rstudio/rstudio as the case may be.
