### ISSUE TITLE
invalid numbering pattern... using typst format

### ISSUE THREAD

**Issue by sinamoghimi73** [quarto-dev/quarto-cli#9972]
"When rendering a qmd file with a section/subsection/... followed by {-} or {.unnumbered}, I encounter an error:

[typst]: Compiling index.typ to index.pdf...error: invalid numbering pattern
    ┌─ index.typ:288:0
    │
288 │ "none"
    │ ^^^^^^

Upon inspecting index.typ:288, I find that the word 'none' is enclosed in quotes, which is incorrect. After removing the quotes, I compile index.typ using 
typst compile index.typ

This resolves the issue and generates the desired PDF file."

**Comment by cscheid** [comment]
@sinamoghimi73 Can you please provide a full .qmd example?

**Comment by sinamoghimi73** [comment]
Hello,
The following is the script I have

---
title: QUARTO TYPST PROJ
bibliography: references.bib
jupyter: python3
---

# Section {-}
This is a simple placeholder for the manuscript's main document ***@***.***.



Thanks

**Comment by sinamoghimi73** [comment]
Hello, 
The following is the script I have:


---
title: QUARTO TYPST PROJ
bibliography: references.bib
jupyter: python3
---

# Section {-}
This is a simple placeholder for the manuscript's main document [@knuth84].



I have tried {.unnumbered} as well, it knows that a none is required but the none is in quotations thus it can't proceed

**Comment by sinamoghimi73** [comment]
in case of {.unlisted} also throws error:


```sh
Error running filter /Applications/quarto/share/filters/main.lua:
...rto/share/pandoc/datadir/../../filters/modules/typst.lua:16: attempt to index a boolean value (local 'v')
stack traceback:
        ...rto/share/pandoc/datadir/../../filters/modules/typst.lua:36: in function 'modules/typst.function_call'
        (...tail calls...)
        [C]: in ?
        [C]: in method 'walk'
        /Applications/quarto/share/filters/main.lua:557: in function </Applications/quarto/share/filters/main.lua:546>
        (...tail calls...)
        /Applications/quarto/share/filters/main.lua:1334: in local 'callback'
        /Applications/quarto/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
        /Applications/quarto/share/filters/main.lua:1388: in function </Applications/quarto/share/filters/main.lua:1385>
stack traceback:
        /Applications/quarto/share/filters/main.lua:557: in function </Applications/quarto/share/filters/main.lua:546>
        (...tail calls...)
        /Applications/quarto/share/filters/main.lua:1334: in local 'callback'
        /Applications/quarto/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
        /Applications/quarto/share/filters/main.lua:1388: in function </Applications/quarto/share/filters/main.lua:1385>
```

**Comment by cscheid** [comment]
Thanks. I can repro both cases, and they look to be bugs in different parts of the code.

**Comment by sinamoghimi73** [comment]
Thank you. I look forward to being able to use the amazing Quarto+Typst combination.

**Comment by mvuorre** [comment]
I just installed the latest Quarto but still encounter this issue.

```
<!-- myfile.qmd -->
---
title: "Hello, Quarto"
format: typst
number-sections: true
knitr: 
  opts_chunk: 
    echo: false
---

## List {.unnumbered}
```

`quarto render myfile.qmd` returns

```
processing file: myfile.qmd
1/1
output file: myfile.knit.md

pandoc
  to: typst
  output-file: myfile.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  number-sections: true

metadata
  section-numbering: 1.1.a
  title: 'Hello, Quarto'
  knitr:
    opts_chunk:
      echo: false

[typst]: Compiling myfile.typ to myfile.pdf...error: invalid numbering pattern
    ┌─ myfile.typ:283:0
    │
283 │ "none"
    │ ^^^^^^
```

`quarto -v` returns "1.5.45".

**Comment by mcanouil** [comment]
Look at the commit/pull request that contains the fix, it's not part of a release yet.
51736dbb716d9597b65b655f28e2de1096d00af2

You need to wait for the next one.

**Comment by mvuorre** [comment]
Hi, thanks for the quick reply! I am looking at the commit through the link you posted, but unfortunately cannot see where it indicates that it is not yet part of a release. For future reference, where should I be looking for that info?

**Comment by mcanouil** [comment]
You can't see what's not there.

When a commit is part of a release:
<img width="592" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/2b88223f-754b-40bc-b1c2-1fcc9fd9be9e">

When it's not, there are no release displayed:
<img width="480" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/71b40b63-bcd6-46a0-ae92-e34b3c4973b0">
