### ISSUE TITLE
folder not ignored when rendering

### ISSUE THREAD

**Issue by JaumeAmoresDS** [quarto-dev/quarto-cli#9978]
### Bug description

Using render section and `!ignore_folder` doesn't actually ignore the folder, but converts everything inside. 

### Steps to reproduce

I have the following `_quarto.yml` in a folder called `mydocs`, as follows:

```
mydocs
-- _quarto.yml
-- index.qmd
-- one
---- one.ipynb
-- two
---- two.ipynb
-- three
---- three.ipynb
```

```
project:
  title: "My Docs"

output-dir: markdown_docs
toc: true
format: gfm
render:
  - "*.ipynb"
  - "*.qmd"
  - "!two/"
```

Then I render the project with:
```
quarto render mydocs
```

Such setup can be found in following repo: https://github.com/JaumeAmoresDS/test_quartodoc

### Expected behavior

Do not convert notebook in folder two, create folder called `markdown_docs`, and include TOC in each markdown.

### Actual behavior

It converts everything to .md, including the notebook in folder `two`. Plus, it doesn't include any TOC, and doesn't create a folder called `markdown_docs`.

### Your environment

- IDE: Terminal
- OS: Ubuntu in WSL2 for Windows

### Quarto check output

Quarto 1.5.45
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.45
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /home/jaumeamllo/miniconda3/envs/tsforecast/bin/python
      Jupyter: 5.2.0
      Kernels: python3, nn, sql, tabularml, tsforecast

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by cwickham** [comment]
`render` needs to be nested under `project`:

```yaml
project:
  title: "My Docs"
  render:
    - "*.ipynb"
    - "*.qmd"
    - "!two/"
```

With that change `two/` is ignored:
```bash
quarto render
[1/3] one/one.ipynb
[2/3] three/three.ipynb
[3/3] index.qmd

Output created: index.md
```

**Comment by cwickham** [comment]
Missed the other part of this...`output-dir` is also a [project option](https://quarto.org/docs/reference/projects/options.html) so also needs to be nested under `project`:
```yaml
project:
  title: "My Docs"
  render:
  - "*.ipynb"
  - "*.qmd"
  - "!two/"
  output-dir: markdown_docs

toc: true
format: gfm

```

The `toc` generated is part of each document. For example, in the generated `one.md` the toc is:
```md

- [sub](#sub)
```

**Comment by JaumeAmoresDS** [comment]
Thank you very much for your help. It works as you say, apologies for mistakingly filing a bug :-S

**Comment by mcanouil** [comment]
@JaumeAmoresDS when you have doubt, you can always open a GitHub Discussion first. Then, if that's a bug, we can create an issue from there when needed.

**Comment by JaumeAmoresDS** [comment]
Thanks @mcanouil, I will do that moving forward.
