### ISSUE TITLE
Quarto Pub account removed, but contents are still there

### ISSUE THREAD

**Issue by jandermoreira** [quarto-dev/quarto-cli#9993]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/9706

<div type='discussions-op-text'>

<sup>Originally posted by **jandermoreira** May 17, 2024</sup>
### Description

I decided to delete my account at quarto.pub, but after deletion, old contents are still available at [jandermoreira.quarto.pub](http://jandermoreira.quarto.pub).

Now I can't update or delete anything.

Is it a matter of time to the contents to be removed or I need to ask someone for help? In the latter case, who?</div>

**Comment by mcanouil** [comment]
Let's keep this in the discussion please.
